### ISSUE TITLE
Modified Hello world sample shows strange behavior

### ISSUE THREAD

**Issue by vivekmishra-sft** [dotnet/core#100]
I simply followed the steps given at [https://www.microsoft.com/net/core#windows] after installing dotnet core on Windows 7 sp1 system.

Here is the complete modified program:

```C#
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
	    Console.Write("Enter a number to see magic: ");
	    int num = Convert.ToInt32(Console.ReadLine());
	    for(int i=0; i <=num; i++)
	    {
		Console.WriteLine(i);
	    }
        }
    }
}
```

It compiled correctly and when I run it with "dotnet run" command, it writes "Hello world!" and waits for the user input without showing the message first which is strange behavior.

The same program when i run on .Net 4.5 compiler, gives me the correct result.

**Comment by blackdwarf** [comment]
@vivekmishra-sft this is strange? Can you please open an issue for this on the dotnet/cli repo and close this one? Thanks!

**Comment by vivekmishra-sft** [comment]
@blackdwarf I am closing this issue here and opening the new one as told by you. Thanks
