### ISSUE TITLE
DisplayFormatAttribute not used while rendering control

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/core#1000]
We have two datecontrols (startdate and enddate) that we used the attribute DisplayFormatAttriute with a DataFormatString("{0:d}") as well as ApplyFormatInEditMode = true. This was rendered as an input with type date in the past but now is rendered as a datetime-local input. So the user has to enter the time as well.

Code from View:
```
<div class="form-group m-l-3">
                                <span>Från</span>
                                <input asp-for="StartDate" asp-format="{0:d}" />
                            </div>
                            <div class="form-group">
                                <span>Till</span>
                                <input asp-for="EndDate" asp-format="{0:d}" />
                            </div>
```

Code From Class (ViewModel):
```
[Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime StartDate { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime EndDate { get; set; }
```

Usings in the ViewModel:
```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
```

Have you changed the behaviour for this?

Using:
VS 2017 15.3.5
.Net Core 2.0.0

**Comment by Petermarcu** [comment]
Copied this issue to here: https://github.com/dotnet/corefx/issues/24440
