### ISSUE TITLE
.kill() on single process kills all solution console apps

### ISSUE THREAD

**Issue by maroallegro** [dotnet/core#1005]
It would be faster to read mine StackOverflow post and few comments there ;)

https://stackoverflow.com/questions/46488212/kill-only-one-console-app-when-multiple-are-started

**Comment by Petermarcu** [comment]
@gregg-miskelly in case he has any insights. This isn't the best place to track this issue if there is anything to be done about it so I'll close this in a few days but I want to give folks a chance to decide if there is anything to fix and open a tracking issue for it elsewhere.

**Comment by maroallegro** [comment]
@Petermarcu I do not know if I understand correctly... 
My question here is: Why in .Net Core when I will start for instance 3 apps (with Start mode) i cannot kill only one of them. Isn't it a bug ? For comparison, when exactly the same process will be made in .Net 4.6 everything works as expected (only one app is closing).

Solution from stackoverflow is only workaround because changing mode of one app to "start without debugging" blocks debugging possibility of one app.

**Comment by gregg-miskelly** [comment]
Assuming this happens only when you are debugging - this is a known bug in the .NET Core project system in Visual Studio. I can't seem to find the bug to reference it at present. You can open or search for a problem through Visual Studio's Report a problem feature if you want to track it.

**Comment by gregg-miskelly** [comment]
Found it. Here is the issue: https://developercommunity.visualstudio.com/content/problem/88707/debugging-multiple-dotnet-core-applications-all-te.html

**Comment by maroallegro** [comment]
@gregg-miskelly Thanks for your help Greg !

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/project-system #2874](https://github.com/dotnet/project-system/issues/2874) via [**ZenHub**](https://www.zenhub.com/)
