### ISSUE TITLE
Path is not added to `.zshrc` during the install of 2.0 (macOS: 10.13 (17A365))

### ISSUE THREAD

**Issue by sushihangover** [dotnet/core#1009]
The **Install .NET and build your first app on macOS** instructions at:

*  https://www.microsoft.com/net/core#macos

State:

>This installer will install the latest stable version of the tools and put them on your PATH so you can run dotnet from the Console.

If you only a `.profile` and a `.zshrc` in your home dir, the path is not added during the install of 2.0 to either of these files and you must manually add `/usr/local/share/dotnet/` yourself.

OS: macOS: 10.13 (17A365)

**Comment by Petermarcu** [comment]
@rakeshsinghranchi @livarcocc can you take a look?

**Comment by Petermarcu** [comment]
I actually moved this to another repo where it will get better traction. https://github.com/dotnet/core-setup/issues/3275. I'm going to close this copy.
