### ISSUE TITLE
Using DotnetCore Class Libraries in Multi Target Scenario

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/core#101]
I have some problems to understand the portable class libraries and the new .NET Core System (RC2). My goal is to manage my code base in multiple solutions and to target Windows10, ASP.NET Core and .NET 4.6.1. Depending on the project, the targets might be different, e.g. my Utils Library with some methods like Guard.NotNull should target all three platforms. A MongoDB helper library must target ASP.NET Core and .NET 4.6.1 only.

I created a .NET Core Class Library with the following settings:

	{
	  "version": "1.0.0-*",

	  "dependencies": {
		"Microsoft.NETCore": "5.0.0"
	  },

	  "frameworks": {
		"netstandard1.4": {
		  "imports": [ "uap10.0", "dnxcore50" ]
		}
	  }
	}

But when I try to reference it from a Universal Class Library (where I have some of my controls) I get the following error:

    Checking compatibility of packages on UAP,Version=v10.0 (win10-x64-aot).
    ClassLibrary1 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
    CodicePlastico 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).

At the moment, I am really confused.

**Comment by gulbanana** [comment]
UAP implements a subset of netstandard, not the whole thing. there must be some code in ClassLibrary1 or CodicePlastico which uses apis unavailable in uwp

**Comment by blackdwarf** [comment]
@SebastianStehle can you please open this issue on dotnet/corefx repo? It seems like a better place than here. I
