### ISSUE TITLE
"Unable to initialize the application (Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.  The System cannot find the file specified"

### ISSUE THREAD

**Issue by john1726** [dotnet/core#1010]
# General

Please note that when I attempt to perform a deployment using ClickOnce, I receive the above error when it tries to install the application.  Here is the batch file I use for publishing the app:

```
@echo Publishing SD2

@echo off

SET MSBUILD_PATH=C:\Program Files (x86)\MSBuild\14.0\Bin
SET projectPath=Cpr.Apps.Sam.App\Cpr.Apps.Sam.App.csproj

@echo on
"%MSBUILD_PATH%\MSBUILD.exe" %projectPath% /p:Configuration=SD2 /p:Platform=x64 /t:Publish /p:SolutionDir=..\

@pause

```

Please find attached the files generated by the above command.  The NuGet package manager says it is installing System.Runtime 4.3.3, but in app.config it also adds these lines:

```
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
```

This is what is in packages.config:

`<package id="System.Runtime" version="4.3.0" targetFramework="net47" />`

Should I be removing the System.Runtime NuGet package from my solution, or downgrading to a previous version?  Do you have any other suggestions?  TIA.

**Comment by Petermarcu** [comment]
@john1726 what is bringing in the System.Runtime reference? Is that one you added explicitly? Do you know why?

There can often be a difference between package version and assembly version. Newer packages carry copies of older implementations that NuGet may select for you depending on your applications target.

/cc @dsplaisted

**Comment by john1726** [comment]
If I remove the System.Runtime package, then I have to remove these packages:

```
System.Security.Cryptography.Algorithms
System.Security.Cryptography.Encoding
System.Security.Cryptography.Primitives
System.Security.Cryptography.X509Certificates
```

Then when I try to deploy using ClickOnce, I get this error:

`System.Deployment.Application.InvalidDeploymentException (HashValidation) - File, has a different computed hash than specified in manifest. - Source: System.Deployment - Stack trace: at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)`

**Comment by john1726** [comment]
Here are the full details on the error I get when I try to remove the Cryptography and Runtime libraries:

```
PLATFORM VERSION INFO
	Windows 			: 10.0.15063.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2046.0 built by: NET47REL1
	clr.dll 			: 4.7.2110.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2046.0 built by: NET47REL1
	dfshim.dll 			: 10.0.15063.0 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/src/SAM/trunk/Publish/2.26.1.8694/SD2/Structures%20Inspection.application
	Application url			: file:///C:/src/SAM/trunk/Publish/2.26.1.8694/SD2/Application%20Files/Structures%20Inspection_2_26_1_8694/Structures%20Inspection.exe.manifest

IDENTITIES
	Deployment Identity		: Structures Inspection.application, Version=2.26.1.8694, Culture=en-CA, PublicKeyToken=37e4c3401a2d9a51, processorArchitecture=amd64
	Application Identity		: Structures Inspection.exe, Version=2.26.1.8694, Culture=en-CA, PublicKeyToken=37e4c3401a2d9a51, processorArchitecture=amd64, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\src\SAM\trunk\Publish\2.26.1.8694\SD2\Structures Inspection.application resulted in exception. Following failure messages were detected:
		+ File, ConnectionInfo.xml, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/4/2017 5:17:29 PM] : Activation of C:\src\SAM\trunk\Publish\2.26.1.8694\SD2\Structures Inspection.application has started.
	* [10/4/2017 5:17:29 PM] : Processing of deployment manifest has successfully completed.
	* [10/4/2017 5:17:29 PM] : Installation of the application has started.
	* [10/4/2017 5:17:29 PM] : Processing of application manifest has successfully completed.
	* [10/4/2017 5:17:32 PM] : Found compatible runtime version 4.0.30319.
	* [10/4/2017 5:17:32 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/4/2017 5:17:34 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, ConnectionInfo.xml, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

            

```

I've found a potential solution here https://blogs.msdn.microsoft.com/gauravb/2008/10/06/clickonce-filename-has-a-different-computed-hash-than-specified-in-manifest/, but I work in a corporate environment and don't have permission to modify that file.

**Comment by Petermarcu** [comment]
In .NET Core 2.0, higher versions of all of those libraries are included which is likely why you were getting the downgrade problem. Does your application run fine now without ClickOnce in the picture?

**Comment by john1726** [comment]
The application runs fine if I don't use ClickOnce, but that is not an acceptable solution, but the applications to be distributed to hundreds of inspectors via ClickOnce.

**Comment by Petermarcu** [comment]
@terrajobst can you help here?

**Comment by terrajobst** [comment]
ClickOnce is broken and we have a tracking bug for that internally. Basically, the installer isn't correctly gathering your project dependencies into the setup, causing the app to miss files. I'm not aware of any workarounds besides either not using ClickOnce or not using .NET Standard dependencies.

Potentially, might be able manually deploy the necessary files, but I'm not a ClickOnce expert. I'll ask.

**Comment by Petermarcu** [comment]
@NikolaMilosavljevic do you have any ideas on how this can be worked around?

**Comment by terrajobst** [comment]
We have a workaround now. I'm working with @ericstj and @NikolaMilosavljevic to finish my draft of the guidance. Will post tomorrow at the latest.

**Comment by john1726** [comment]
Please note that I was able to get rid of this exception:

`Unable to initialize the application (Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The System cannot find the file specified`

By removing the following packages from all projects in the solution:

```
System.Runtime
System.Security.Cryptography.Algorithms
System.Security.Cryptography.Encoding
System.Security.Cryptography.Primitives
System.Security.Cryptography.X509Certificates
```

So now it runs no problem in debug mode, but this is code I have inherited, so it is not clear to me, do I need to have the above libraries to allow for proper code signing for releasing to production?

**Comment by Petermarcu** [comment]
You should be fine. You shouldn't have to reference any of those things individually and if you used them, the compiler would complain when you removed them. Those libraries would be for you to call and shouldn't have anything to do with your ability to sign your app.

**Comment by john1726** [comment]
OK, thank you!

**Comment by terrajobst** [comment]
For future reference: I've [documented the work around](https://github.com/dotnet/standard/issues/529) now as well.

**Comment by Petermarcu** [comment]
I'm going to go ahead and close this issue now.
