### ISSUE TITLE
dotnet: command not found after installing dotnet core 2 on ubuntu linux 16.04

### ISSUE THREAD

**Issue by andremarcondesteixeira** [dotnet/core#1012]
I followed the steps in [https://www.microsoft.com/net/core#linuxubuntu](https://www.microsoft.com/net/core#linuxubuntu) to install dotnet core 2 (dotnet-sdk-2.0.0) in my machine, which has an Ubuntu Linux 16.04.

Tried it 3 times, and certified that I was executing the commands for my distro and that any previous version was uninstalled, but no success.

**Expected Behavior:**
running `dotnet` in the command line returns me the helper page of dotnet

**Actual Behavior:**
running `dotnet` in the command line gives an error `dotnet: command not found`

Also, the docker package on the official site gets me dotnet core version 1.x, and the docker package with the version 2 (sdk) does nothing when I run it.

**Comment by Petermarcu** [comment]
For this install issue, I'm going to move that elsewhere so it can be tracked.

Are you saying the docker instructions here: https://www.microsoft.com/net/core#dockercmd are giving you 1.X when you point to latest? @richlander any ideas?

**Comment by andremarcondesteixeira** [comment]
@Petermarcu yes, it gives me the 1.x version

**Comment by Petermarcu** [comment]
I just did a clean install and got this:

```
C:\Users\Peter>docker run -it microsoft/dotnet:latest
Unable to find image 'microsoft/dotnet:latest' locally
latest: Pulling from microsoft/dotnet
219d2e45b4af: Pull complete
ef9ce992ffe4: Pull complete
d0df8518230c: Pull complete
38ae21afde7b: Pull complete
d8597196fae8: Pull complete
01a7bdcfe48a: Pull complete
a9e767050d45: Pull complete
Digest: sha256:b3537d0eb23afa684254b74ee2dd6c99e684990896bc8491656f0c560c86271d
Status: Downloaded newer image for microsoft/dotnet:latest
root@60e430d166a2:/# dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by andremarcondesteixeira** [comment]
Oh snap! It was some issue with the previous image I had. Removed the previous image and now it is working.

Anyway, I still can't properly install dotnet 2 in my machine.

**Comment by Petermarcu** [comment]
Yeah, I opened an issue in the core-setup repo linked above to track that. The more details you can provide there the better. I'm going to close this issue and we can make progress in https://github.com/dotnet/core-setup/issues/3278
