### ISSUE TITLE
Debugging NuGet packages containing src and pdb

### ISSUE THREAD

**Issue by bbski** [dotnet/core#1013]
# Visual Studio 2017 does not reference the **src** folder in my NuGet package that was packaged using MSBuild. 

I packaged my NuGet to include pdb and source as follows with the **/p:IncludeSource=true**
_/t:pack myproj.csproj /p:Configuration=Debug /p:PackageOutputPath="." /p:IncludeSource=true /p:PackageVersion=$(Major).$(Minor).$(RevisionNumber)_

In VS, I set a reference to my package and I'm able to step into but VS then asks for the location of the source file I'm stepping into.

The only way I can make VS happy is to locate where my NuGet package is located as such:
_%UserProfile%\.nuget\packages\mypackagename\1.0.417\src_

Once I do this, the next debug session allows me to step into.

Is it possible for VS to seamlessly determine the src folder contained within the Nuget package?

Forgot to add both the Nuget lib and project are .net core 2.0

**Comment by Petermarcu** [comment]
@gregg-miskelly @rrelyea is there a good place to track this?

**Comment by gregg-miskelly** [comment]
@bbski As of VS 2017 version 15.5 you can embed sources in your PDB, and Visual Studio will automatically open them. Does this solve your issue?

https://stackoverflow.com/questions/42714352/embedding-c-sharp-sources-in-pdb-with-new-csproj

**Comment by bbski** [comment]
@gregg-miskelly This is awesome.  Let me play with SourceLink a bit and see what comes of it.  I'll update with my findings.  Much appreciated.

**Comment by Petermarcu** [comment]
Going to close this issue now. Go ahead and open new issues specific to whatever you hit as you go down that path.
