### ISSUE TITLE
System.Data.Sqlient isn't supported on this platform error in Update-Database

### ISSUE THREAD

**Issue by deanilvincent** [dotnet/core#1018]
# Title: System.Data.Sqlient isn't supported on this platform error

# General

**Environment specifications:**
Visual Studio 2017 15.3
Installed 2.0 .Net Core

I'm trying to use the command "update-database -context NameOfMyContext" but somehow I got this error message that says "System.Data.Sqlient isn't supported on this platform error"

Here's my connection string

`            services.AddDbContext<CompanyDbContext>(options => options.UseSqlServer(@"data source=ipaddress;initial catalog=testingdbcore;user id=username;password=password;integrated security=false;"));`

To add up, I successfully added a migration and everything is working fine but then suddenly when I trigger the command for updating my database, I got this issues. 

Thank you in advance!

![bugerrorcore](https://user-images.githubusercontent.com/10904957/31386641-11c0dfc6-adfa-11e7-944d-7518e8404183.PNG)

**Comment by Petermarcu** [comment]
@divega would this be an issue that should be in the EF repo or @saurabh500 should this issue go to corefx?

**Comment by saurabh500** [comment]
It should go to Corefx

**Comment by deanilvincent** [comment]
What should I do now guys? Is there any option?

**Comment by saurabh500** [comment]
What is your OS that you are running the above steps on @deanilvincent ?

**Comment by saurabh500** [comment]
@deanilvincent From the screen shot it is Windows.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24586](https://github.com/dotnet/corefx/issues/24586) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24587](https://github.com/dotnet/corefx/issues/24587) via [**ZenHub**](https://www.zenhub.com/)
