### ISSUE TITLE
DotNetCore.1.0.7_1.1.4-WindowsHosting.exe link does not work

### ISSUE THREAD

**Issue by BJMdotNET** [dotnet/core#1019]
The page https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.7-download.md contains a link to download DotNetCore.1.0.7_1.1.4-WindowsHosting.exe : 

https://download.microsoft.com/download/B/0/D/B0D6D983-3188-4008-A852-94BCED5355E6/DotNetCore.1.0.7_1.1.4-WindowsHosting.exe

However, this link seems to be broken. When I click it (in Chrome) I get this error:

> The webpage at https://download.microsoft.com/download/B/0/D/B0D6D983-3188-4008-A852-94BCED5355E6/DotNetCore.1.0.7_1.1.4-WindowsHosting.exe might be temporarily down or it may have moved permanently to a new web address.

Internet Explorer also fails to download the file and reports it "couldn't be downloaded".

**Comment by leecow** [comment]
Thanks for the report @BJMdotNET! Link should be correct now.
