### ISSUE TITLE
"How to run the samples?" is misleading

### ISSUE THREAD

**Issue by mrts** [dotnet/core#102]
`samples/README.md` contains the following instructions:

----

* *Compile and run using the following commands*
   * *dotnet restore*
   * *dotnet build*
    * *./bin/Debug/[framework]/[binary name]*

---

When I launch the `microsoft/dotnet:latest` Docker container, clone this repository and run `dotnet restore` and `dotnet build` in `samples/helloworld`, then I get the following tree in `bin`:

```
bin/
`-- Debug
    `-- netcoreapp1.0
        |-- helloworld.deps.json
        |-- helloworld.dll
        |-- helloworld.pdb
        |-- helloworld.runtimeconfig.dev.json
        `-- helloworld.runtimeconfig.json
```

There is no executable binary there that I can run - or am I missing something?

Version:

```
# dotnet --version
1.0.0-preview1-002702
```

**Comment by mrts** [comment]
I figured it out - `dotnet bin/Debug/netcoreapp1.0/hello_world.dll` works well. Will send a patch to update docs.

**Comment by mrts** [comment]
However, neither `dotnet path/to/netcoreapp1.0/application.dll` nor `cd path/to/netcoreapp1.0; dotnet application.dll` work with console apps that reference other DLLs, resulting in the following coredump:

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'MyApp.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Aborted (core dumped)
```

**Comment by mrts** [comment]
The correct way to run the console apps that reference other DLLs seems to be

```
dotnet publish
dotnet bin/Debug/netcoreapp1.0/publish/application.dll
```

Should I update the merge request accordingly?

**Comment by blackdwarf** [comment]
@mrts thanks for catching this and fixing the README.md. I've merged your PR. 

For the second thing, the samples in this repo are simple and don't have any P2P references, so the second issue referenced above and the fix is not really needed here. There are other docs on dotnet.github.io/docs/ that cover these. 

With this, I will go ahead and close this issue as it was resolved by your PR.
