### ISSUE TITLE
Is not possible to create custom cultures in .Net Core

### ISSUE THREAD

**Issue by carcarbe** [dotnet/core#1020]
Is not possible to create custom cultures in .Net Core

In .Net framework is possible to create custom cultures, e.g en-US-NY (English from New York). using CultureAndRegionInfoBuilder class  as is describe in this example http://www.c-sharpcorner.com/UploadFile/GemingLeader/creatingextending-a-culture/  .

Are there any plans to implement this in .Net Core?

In the project were I am working at the moment we need this to be able to create different localizations for different dialects  of the same language.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24559](https://github.com/dotnet/corefx/issues/24559) via [**ZenHub**](https://www.zenhub.com/)
