### ISSUE TITLE
Failed to create prime the NuGet cache. new failed with: 5

### ISSUE THREAD

**Issue by dinjonya** [dotnet/core#1022]
on macOs version is 10.13

dotnet core install 1.04 & 2.0 
my prj use .net core 1.04
when restore or build or run    console print

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft andshared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 4866 ms
Expanding 100% 6208 ms
Failed to create prime the NuGet cache. new failed with: 5

**Comment by dinjonya** [comment]
i tried delete global.json file. 
it's ok. who can tell me why?

**Comment by Petermarcu** [comment]
@dinjonya are you saying that after deleting the global.json file, it fixed the issue?

**Comment by Petermarcu** [comment]
I opened this issue to track this in the NuGet repo. https://github.com/NuGet/Home/issues/6017
