### ISSUE TITLE
How to default to WinHTTP proxy not the WinINet for a .Net core app

### ISSUE THREAD

**Issue by rohitshrivastava04** [dotnet/core#1023]
# Issue Title
How to set proxy settings for a .Net Core application

# General

We have a .Net Core Windows Service which makes few calls to AWS or other internet services. For this, it needs to use proxy settings. There are two options either we configure each call to use proxy server or set proxy setting machine wide. Setting WinHTTP proxy configuration is easier than WinINet. However .net core process uses wininet as default proxy policy. How can I set it to default to WinHTTP than WinINet for the whole app rather than changing in each WinHttpHandler?

**Comment by karelz** [comment]
This issue was moved to dotnet/corefx#24574
