### ISSUE TITLE
Is System.Net.Sockets a Implement Of NIO?

### ISSUE THREAD

**Issue by anthonywanted** [dotnet/core#1025]
# Issue Title

Is System.Net.Sockets an Implement Of NIO?

# General

Just few questions.
Is System.Net.Sockets an Implement of NIO?
In windows, is it an implement of IOCP?
In Linux, is it an implement of epoll?

How about aspnet core?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24610](https://github.com/dotnet/corefx/issues/24610) via [**ZenHub**](https://www.zenhub.com/)
