### ISSUE TITLE
ackage System.Net.Security 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0)

### ISSUE THREAD

**Issue by FerHenrique** [dotnet/core#1028]
Hey all!

I'm trying to install Microsoft.Azure.DocumentDB.Core on my project, and the error messages are:
- Package System.Net.Security 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0)
-  Package System.Security.SecureString 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0)

If I try to install the same package on the project using another machine, it works well. This is why I think it's not a problem on DocumentDB SDK. 

My setup is:
	Microsoft Visual Studio Enterprise 2017 - Version 15.4.0 (VisualStudio.15.Release/15.4.0+27004.2002)
	Microsoft .NET Framework - Version 4.7.02046
	Installed Version: Enterprise
	ASP.NET and Web Tools 2017 - 15.0.30925.0
	NuGet Package Manager - 4.4.0
	.NET Core Runtime - 2.0
	.NET Core SDK - 2.0
	My project is configured to user .NET Core 2.0 as the target framework. And the project is a class library. 

Some more details from Package Manager: 
=================================================
Install-Package : Package System.Net.Security 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Net.Security 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
At line:1 char:1
+ Install-Package Microsoft.Azure.DocumentDB.Core -Project MM.ArchCore
+ + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package System.Security.SecureString 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.SecureString 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
At line:1 char:1
+ Install-Package Microsoft.Azure.DocumentDB.Core -Project MM.ArchCore
+ + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'MM.ArchCore'.
At line:1 char:1
+ Install-Package Microsoft.Azure.DocumentDB.Core -Project MM.ArchCore
+  + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
=================================================

**Comment by Petermarcu** [comment]
@dsplaisted @terrajobst @emgarten any ideas. This looks like it should work and it works for me in my simple repro:

```
dotnet new console
dotnet add package Microsoft.Azure.DocumentDB.Core --version 1.5.1
dotnet publish
```
on
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="1.5.1" />
  </ItemGroup>

</Project>
```
succeeds.

**Comment by Petermarcu** [comment]
@FerHenrique can you try `dotnet nuget locals all –clear` on the machine in a bad state?

**Comment by emgarten** [comment]
I was not able to repro this either, this package should be compatible due to the netstandard1.3 support.

```json
"compile": {
  "ref/netstandard1.3/System.Net.Security.dll": {}
}
```

@FerHenrique would you make a copy of the obj folder for the project including project.assets.json before trying to fix the problem.

After that
1. Clear the caches as @Petermarcu mentioned
1. Delete the obj folder for the project to force restore to create a new project.assets.json file

If the above fixes your issue it would be great if you could share the original project.assets.json file, if it doesn't fix the issue then I would still like to see it to figure out what is wrong.

**Comment by Petermarcu** [comment]
@emgarten do you think this is a NuGet issue and we should move it to nuget/home?

**Comment by emgarten** [comment]
I think this should be tracked with https://github.com/NuGet/Home/issues/5995, it is likely that nuget is unable to see the ref file and that leads to this compat error.

**Comment by Petermarcu** [comment]
Ok, I'll close this one here and we can use https://github.com/NuGet/Home/issues/5995 to track this.

**Comment by FerHenrique** [comment]
Thanks for the update.

**Comment by FerHenrique** [comment]
Hi all!
Clearing the cache worked for me. 
My project.assets.json is attached. 

Tks!

[project.assets.json.txt](https://github.com/dotnet/core/files/1384102/project.assets.json.txt)

**Comment by Jalalx** [comment]
Sometimes just clearing the Nuget cache is not enough. I also deleted `obj` folder and that fixed my problem.
