### ISSUE TITLE
Misleading information shown when the dotnet command is passed duplicated arguments

### ISSUE THREAD

**Issue by nigurr** [dotnet/core#1029]
`C:\Tests> dotnet test --logger trx --logger trx`
`MSBUILD : error MSB1009: Project file does not exist.
Switch: trx`

The same one works 
`C:\Tests> dotnet test --logger trx`
`Build started, please wait...`

The error message is misleading or the duplicated arguments should be skipped

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #7836](https://github.com/dotnet/cli/issues/7836) via [**ZenHub**](https://www.zenhub.com/)
