### ISSUE TITLE
 .NET Core 2.0  Invoke  .so file (c++)   on Centos

### ISSUE THREAD

**Issue by luckyhappy** [dotnet/core#1030]
on windows, i can user DllImport  call .dll file(c++).
on linux ,how  i do?

**Comment by omajid** [comment]
Same way! For example, see https://github.com/dotnet/corefx/blob/dce54eac6369631bf9e0af274cb0abd484edb331/src/System.Drawing.Common/src/System/Drawing/LibX11Functions.cs#L14

**Comment by luckyhappy** [comment]
@omajid ok,thanks

**Comment by jatpat** [comment]
@omajid thanks
