### ISSUE TITLE
Performance issue with IFormFile

### ISSUE THREAD

**Issue by prashanthi-ediga** [dotnet/core#1031]
# Issue Title

Reading the stream from http posted file using IFormFile is very slow.

# General

We have implemented an ASP.Net application to read very large Excel Files(100 MB).
Our requirements was to not save the file to any temp location or save file at server.

So, we have implemented an API which reads stream data using 'HttpPostedFileBase' and send this stream to openXMLReader. The performance is very good and we were able to achieve good results with 100 MB file for 1000 concurrent users in a ramp up period of 5 minutes.

Recently,we had to move to .net core in which 'HttpPostedFileBase' was not supported.
So I am using IFormFile to read stream data and pass it to excelReader.
But the performance degraded to a great extent.As the number of concurrent users increase the performance is degrading rapidly.

I have seen few blogs stating to use 'MultipartReader' for large files.But this is storing the stream to a temporary path which is not possible in our scenario.

Code Sample:
[HttpPost]
        public string ReadExcel_OpenXML(IFormFile postedFile)
        {
            var inputStream = postedFile.OpenReadStream();
             ....
         }
Can you please suggest any alternative or fix to this.
Please let me know if you need any other details.

Thanks,
Prashanthi.

**Comment by Petermarcu** [comment]
Moved this bug here: https://github.com/aspnet/Home/issues/2250
