### ISSUE TITLE
Missing download for dotnet 1.1.4 for Fedora

### ISSUE THREAD

**Issue by johnnyasantoss** [dotnet/core#1032]
Hello!
Shouldn't this [page][download-archive] have a link to download the SDK for Fedora 24?
There's info about the tar file in the [checksums][checksums], but there's no download link.

[download-archive]: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.4-download.md
[checksums]: https://dotnetcli.blob.core.windows.net/dotnet/checksums/1.1.4-sdk-sha.txt

**Comment by Petermarcu** [comment]
@leecow

**Comment by leecow** [comment]
Sorry about that and thanks for the report @johnnyasantoss , fixed!

**Comment by johnnyasantoss** [comment]
Hey! I've had send a PR fixing this.
I've referred it in this issue.
