### ISSUE TITLE
Parse CultureInfo no longer supported in .NET Core

### ISSUE THREAD

**Issue by viktor-morin** [dotnet/core#1035]
Hi!

I reported an error using Newtonsoft.Json where I recieved that the error was in .NET Core and not Newtonsoft.Json itself. Copy paste the issue here below:

We are now changing to .NET Core and we get following error when trying to parse a following class:

`Dictionary<CultureInfo,string>`

> ArgumentException: Could not cast or convert from System.String to System.Globalization.CultureInfo.
> Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(object value, Type initialType, Type targetType)
> JsonSerializationException: Error converting value "en-US" to type 'System.Globalization.CultureInfo'. Path 'Name.en-US', line 1, position 17.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)
> JsonSerializationException: Could not convert string 'en-US' to dictionary key type 'System.Globalization.CultureInfo'. Create a TypeConverter to convert from the string to the key type object. Path 'Name.en-US', line 1, position 17.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, string id)

This is working in .NET Framwork.

Link to original post:
[https://github.com/JamesNK/Newtonsoft.Json/issues/1457](url)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24755](https://github.com/dotnet/corefx/issues/24755) via [**ZenHub**](https://www.zenhub.com/)
