### ISSUE TITLE
.NET Core 2.0: ResourceManager ignores Culture, always reads neutral RESX file

### ISSUE THREAD

**Issue by hardcodet** [dotnet/core#1036]
VS2017, 15.3.5

I have an ASP.NET Core 2.0 app to which I added two resource files - the neutral one and one for German:

* `SiteResources.resx` (English strings)
* `SiteResources.de.resx` (German strings)

Both have their Build Action set to `EmbeddedResource`  and the `ResxFileGenerator` as the Custom Tool. So far so good.

The problem is: The following code returns always the English value from the **neutral** RESX file:

    SiteResources.Culture = new CultureInfo("de");
    string s1 = SiteResources.SomeTestString;

Same would go for this, which is equivalent

    string s1 = SiteResources.ResourceManager.GetString("SomeTestString", new CultureInfo("de"));

This somewhat defeats the whole purpose of having RESX files and the `ResourceManager`. Any idea how to work around this?

### Some additional infos

* My main DLL is called `TaxiLink.Site.dll`
* The compiler creates the following resource file that is put into a culture-specific folder:
   `\bin\Debug\netcoreapp2.0\de\TaxiLink.Site.resources.dll`
* I had my resources in a dedicated folder, and also tried a pair of resource files at the root of the application - both didn't work.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24786](https://github.com/dotnet/corefx/issues/24786) via [**ZenHub**](https://www.zenhub.com/)
