### ISSUE TITLE
.NET Core 2.0 Runtime on MacOS:  Error running dotnet

### ISSUE THREAD

**Issue by keithnicholson** [dotnet/core#1038]
# Issue Title

.NET Core 2.0 Runtime on MacOS:  Error running dotnet

# General

Good day!  I had a buddy with a Mac install the .NET Core 2.0 Runtime from:  

https://www.microsoft.com/net/download/core 

Chose the macOS (x64) PKG file.  It ran and we see  - 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The following was installed at /usr/local/share/dotnet 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Microsoft .NET Core Runtime - 2.0.0

However, when we go to a Terminal and type "dotnet --version"  we get the following item:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Did you mean to run dotnet SDK commands? Please install dotnet SDK from: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

We added "sudo" in front and got the same.

We do not want to develop there.  We simply want to run a package.

Have we missed something?

Best wishes,
Keith

**Comment by livarcocc** [comment]
This happens because you only installed the runtime, which is used to run applications.

The dotnet --version and other development commands are implemented by the SDK, which you can acquire at https://dot.net.

**Comment by keithnicholson** [comment]
I'd rather not install the SDK to simply run a console app on a user's machine.  I say that because, calling my basic helloworld app on the Mac in question throws the error after stating:

`dotnet GoJerry.dll`

> A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/gerald.hansen/Desktop/Release 1/netcoreapp2.0/'.

I figured at least calling "dotnet --version" would at least validate that the Core runtime was working.  Was this a bad assumption?

**Comment by livarcocc** [comment]
You don't need the SDK to run your application.

The error you are getting above indicates that you have missing files in your deployment. To deploy your app, you should execute dotnet publish and then you should copy all the contents under the publish folder that will be generated.

If you are just building and copying the build contents, that's not really deployable bits.

dotnet --version is an SDK command that displays the version of the SDK that is being resolved by the host, not the runtime version.

**Comment by omajid** [comment]
I try and use `dotnet --info` as a replace for `dotnet --version` which I know works even when the SDK is not around.

**Comment by keithnicholson** [comment]
@omajid -- thanks that validated part of the core deployment.

@livarcocc  -- I did do the publish option.  But where I goofed was distributing what was in the release folders and not the publish folder that was also created.  Thanks for your help.
