### ISSUE TITLE
Instructions for CentOS should use ~/bin

### ISSUE THREAD

**Issue by m-ghaoui** [dotnet/core#104]
The instructions on https://www.microsoft.com/net/core#centos say:

```bash
curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet
sudo ln -s ~/dotnet/dotnet /usr/local/bin
```

In My Humble Opinion, I don't think it's wise to link a global `/usr/local/bin` to point to an executable in a user's home directory. This can cause problems on a multi-user system.

I think the instructions should be:

```bash
curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet
mkdir -p ~/bin
sudo ln -s ~/dotnet/dotnet ~/bin
```

**Comment by blackdwarf** [comment]
@m-ghaoui we have changed the instructions for CentOS to now install in `/opt` and symlink info `/usr/local/bin`. Does that work?

**Comment by m-ghaoui** [comment]
Looks good to me!
