### ISSUE TITLE
Microsoft.Win32.SafeHandles.SafeHandleMinusOneIsInvalid doesn't exist

### ISSUE THREAD

**Issue by Oj18** [dotnet/core#1041]
# Microsoft.Win32.SafeHandles.SafeHandleMinusOneIsInvalid does not exist

# General

.NET Core (.NETCoreApp) 1.1, Visual Studio 2017, Windows 10.

Code:
`using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;

namespace HackingGame
{
    class Program
    {
        static void Main()
        {
            var handle = NativeMethods.GetStdHandle(NativeMethods.STD_INPUT_HANDLE);

            int mode = 0;
            if (!(NativeMethods.GetConsoleMode(handle, ref mode))) { throw new Win32Exception(); }

            mode |= NativeMethods.ENABLE_MOUSE_INPUT;
            mode &= ~NativeMethods.ENABLE_QUICK_EDIT_MODE;
            mode |= NativeMethods.ENABLE_EXTENDED_FLAGS;

            if (!(NativeMethods.SetConsoleMode(handle, mode))) { throw new Win32Exception(); }

            var record = new NativeMethods.INPUT_RECORD();
            uint recordLen = 0;

            Console.Clear();

            while (true)
            {
                if (!(NativeMethods.ReadConsoleInput(handle, ref record, 1, ref recordLen))) { throw new Win32Exception(); }

                switch (record.EventType)
                {
                    case NativeMethods.KEY_EVENT:
                        {
                            Console.Write(record.KeyEvent.AsciiChar);
                        }
                        break;
                }
            }
        }
    }

    public class NativeMethods
    {
        public const Int32 STD_INPUT_HANDLE = -10;

        public const Int32 ENABLE_MOUSE_INPUT = 0x0010;
        public const Int32 ENABLE_QUICK_EDIT_MODE = 0x0040;
        public const Int32 ENABLE_EXTENDED_FLAGS = 0x0080;

        public const Int32 KEY_EVENT = 1;
        public const Int32 MOUSE_EVENT = 2;

        [DebuggerDisplay("EventType: {EventType}")]
        [StructLayout(LayoutKind.Explicit)]
        public struct INPUT_RECORD
        {
            [FieldOffset(0)]
            public Int16 EventType;
            [FieldOffset(4)]
            public KEY_EVENT_RECORD KeyEvent;
            [FieldOffset(4)]
            public MOUSE_EVENT_RECORD MouseEvent;
        }

        [DebuggerDisplay("{dwMousePosition.X}, {dwMousePosition.Y}")]
        public struct MOUSE_EVENT_RECORD
        {
            public COORD dwMousePosition;
            public Int32 dwButtonState;
            public Int32 dwControlKeyState;
            public Int32 dwEventFlags;
        }

        [DebuggerDisplay("{X}, {Y}")]
        public struct COORD
        {
            public UInt16 X;
            public UInt16 Y;
        }

        [DebuggerDisplay("KeyCode: {wVirtualKeyCode}")]
        [StructLayout(LayoutKind.Explicit)]
        public struct KEY_EVENT_RECORD
        {
            [FieldOffset(0)]
            [MarshalAsAttribute(UnmanagedType.Bool)]
            public Boolean bKeyDown;
            [FieldOffset(4)]
            public UInt16 wRepeatCount;
            [FieldOffset(6)]
            public UInt16 wVirtualKeyCode;
            [FieldOffset(8)]
            public UInt16 wVirtualScanCode;
            [FieldOffset(10)]
            public Char UnicodeChar;
            [FieldOffset(10)]
            public Byte AsciiChar;
            [FieldOffset(12)]
            public Int32 dwControlKeyState;
        };

        public class ConsoleHandle : SafeHandleMinusOneIsInvalid
        {
            public ConsoleHandle() : base(false) { }

            protected override bool ReleaseHandle()
            {
                return true; //releasing console handle is not our business
            }
        }

        [DllImportAttribute("kernel32.dll", SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern Boolean GetConsoleMode(ConsoleHandle hConsoleHandle, ref Int32 lpMode);

        [DllImportAttribute("kernel32.dll", SetLastError = true)]
        public static extern ConsoleHandle GetStdHandle(Int32 nStdHandle);

        [DllImportAttribute("kernel32.dll", SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern Boolean ReadConsoleInput(ConsoleHandle hConsoleInput, ref INPUT_RECORD lpBuffer, UInt32 nLength, ref UInt32 lpNumberOfEventsRead);

        [DllImportAttribute("kernel32.dll", SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern Boolean SetConsoleMode(ConsoleHandle hConsoleHandle, Int32 dwMode);

    }

}

internal static class DllImports
{
    [StructLayout(LayoutKind.Sequential)]
    public struct COORD
    {

        public short X;
        public short Y;
        public COORD(short x, short y)
        {
            this.X = x;
            this.Y = y;
        }

    }
    [DllImport("kernel32.dll")]
    public static extern IntPtr GetStdHandle(int handle);
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool SetConsoleDisplayMode(
        IntPtr ConsoleOutput
        , uint Flags
        , out COORD NewScreenBufferDimensions
        );
}`

Thanks for any help.

**Comment by Oj18** [comment]
Code isn't working in markdown, I might be doing it incorrect though.

**Comment by svick** [comment]
[`SafeHandleMinusOneIsInvalid` exists in .Net Core 2.0, but not in .Net Core 1.x.](https://apisof.net/catalog/Microsoft.Win32.SafeHandles.SafeHandleMinusOneIsInvalid) Can you upgrade to 2.0?

---

And for code formatting use triple backticks. If you also want syntax highlighting, include the language name after the opening set. E.g.:

````md
```c#
class C { }
```
````

produces:

```c#
class C { }
```

**Comment by Oj18** [comment]
Oh, how do I upgrade to 2.0? It doesn't show up as an option...

**Comment by Oj18** [comment]
Updating Visual Studio, I'll try it. Thanks for your help.
