### ISSUE TITLE
Add packages for Ubuntu 17.10 Artful Aardvark

### ISSUE THREAD

**Issue by ggobbe** [dotnet/core#1042]
# Add packages for Ubuntu 17.10 Artful Aardvark

There is no packages available in the repository for Ubuntu 17.10 Artful Aardvark:
https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod/

Thanks

**Comment by Petermarcu** [comment]
@rakeshsinghranchi

**Comment by Petermarcu** [comment]
@leecow is going to publish packages for this very soon.

**Comment by Petermarcu** [comment]
@leecow did you do this today? I thought I saw some things go by.

**Comment by leecow** [comment]
Yep, changes are live - https://github.com/dotnet/core/pull/1043
