### ISSUE TITLE
System.Data.SQLClient throws an Exceoption by calling open Method

### ISSUE THREAD

**Issue by Martin-Stein** [dotnet/core#1045]
Hi folks,

Its great to have direct SQL access, but my UWP Application, with target Fall Creators Update, runs into an IO Exception when I call open-Method on my SQLConnection object:
 
System.IO.FileNotFoundException  occurred.
  HResult=0x80070002
  Message= Could not load file or assembly 'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. File not found   
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei SQLDBDiagrammGenerator.UWP.MainPage.connect_Click(Object sender, RoutedEventArgs e) 

I have loaded System.data.common version 4.3.0
System.Data.SQLClient 4.4.0
Microsoft.NETCore.UniversalWindowsPlatform Ver. 6.0.1 via Nuget.

What can it be, how can it be solved?

Best regards,

Martin

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24919](https://github.com/dotnet/corefx/issues/24919) via [**ZenHub**](https://www.zenhub.com/)
