### ISSUE TITLE
How to debug StackOverflowException

### ISSUE THREAD

**Issue by Daniel15** [dotnet/core#1047]
I'm getting this error while moving a site from ASP.NET Core 1.1 on Mono to ASP.NET Core 2.0 on .NET Core 2.0:
```
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Daniel15.Web.Controllers.ShortUrlController.Index (Daniel15.Web), returned result Microsoft.AspNetCore.Mvc.ContentResult.
Process is terminating due to StackOverflowException.
[1]    12976 abort      LD_LIBRARY_PATH=/tmp/ssltest ASPNETCORE_ENVIRONMENT=Development =
```

How do I get a full stack trace for the `StackOverflowException` to determine where it's coming from?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #14720](https://github.com/dotnet/coreclr/issues/14720) via [**ZenHub**](https://www.zenhub.com/)
