### ISSUE TITLE
How to debug the source code of ServiceModel.Http (4.4.0) using Visual Studio 2017

### ISSUE THREAD

**Issue by SCKlausZ** [dotnet/core#1048]
Visual Studio 15.3.4
.net core 2.0.0
System.ServiceModel.Http NuGet package 4.4.0

I'm having a strange transient error when calling a web service and I would like to step into WinHttpHandler (and WinHttpRequestCallback) to get more information, but I just get an "Source Not Available".

I have cloned both the coreclr and corefx repositories, I have setup VS2017 according to [Visual Studio Doc](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger) and [issue 897](https://github.com/dotnet/core/issues/897), and I can step into things like System.Private.CoreLib.dll.

In the Modules window, I can see that the System.ServiceModel.Http.pdb is loaded. I can find the source code in ...\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs. I can open the source file, and if I set a breakpoint it is brown (red?) as if it is enabled. But execution doesn't break at the breakpoint.

I can set a breakpoint in ExceptionDispatchInfo, but when I try to switch to a frame in WinHttpHandler/WinHttpRequestCallback I get "Source Not Available (see screendump).

![debugwinhttphandler](https://user-images.githubusercontent.com/33118160/32053847-c028aa3a-ba5c-11e7-94bf-06090700899c.png)

Can I do something so that I can step into the source code for the System.ServiceModel.Http NuGet package?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24918](https://github.com/dotnet/corefx/issues/24918) via [**ZenHub**](https://www.zenhub.com/)
