### ISSUE TITLE
Hello, I am Chinese,

### ISSUE THREAD

**Issue by netnr** [dotnet/core#1049]
# Issue Title
`asp.net core 2.0 mvc` 
Development project, cookies has Chinese, access site return error code: 400

# General

![1.png](https://i.loli.net/2017/10/27/59f27ec08b50f.png)
![2.png](https://i.loli.net/2017/10/27/59f27ec093424.png)
![3.png](https://ooo.0o0.ooo/2017/10/27/59f27ec097fc0.png)

**Comment by Petermarcu** [comment]
Move this to the ASP.NET repo. https://github.com/aspnet/Home/issues/2259
