### ISSUE TITLE
 .Net Plaform Standard implementation on .Net 4.7 has version inconsistency for System.Net.Http

### ISSUE THREAD

**Issue by santhoshkumarmksss** [dotnet/core#1050]
I have been using WCF service with .Net 4.7 version and it has project reference of Standard library with version 1.6. If I am using reflection getting bellow error

System.IO.FileLoadException: 'Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Code which generates error:
  Type type = (from assembly in AppDomain.CurrentDomain.GetAssemblies()
                         where assembly.GetName().Name == "TestStandard"
                         select assembly.GetType("MoE.ERS.DTO.ResourceRequests.PlaygroupResourceRequestDTO")).FirstOrDefault();

I have attached sample project reference for which i am getting below error. Also i tried binding redirect in Web.config and still no luck. 

Any quick help will be much appreciated.

[WcfService1.zip](https://github.com/dotnet/core/files/1420552/WcfService1.zip)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/standard #559](https://github.com/dotnet/standard/issues/559) via [**ZenHub**](https://www.zenhub.com/)
