### ISSUE TITLE
Instructions for running on Raspberry PI is missing in the "Prerequisites for .NET Core on Linux"

### ISSUE THREAD

**Issue by olavt** [dotnet/core#1051]
The instructions found here: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md contains these instructions for running .NET Core 2.0 on a Raspberry Pi:

Getting the app to run on the Pi.
Linux
1) Install Linux on your Pi.
2) Install the prereq packages for .NET Core.
3) Copy your app, i.e. whole publish directory mentioned above, to the Raspberry Pi and execute run ./helloworld to see Hello World! from .NET Core running on your Pi! (make sure you chmod 755 ./helloworld)

Number 2) links to this page:

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#tabpanel_-r1y2MrINK_netcore2x

There are no instructions here for installing the "prereq packages for .NET Core" on Raspberry Pi.

**Comment by Petermarcu** [comment]
The wording could probably be better but its telling you to install the stuff under the section "Linux distribution dependencies" in that document from the package manager on your distro.

**Comment by Petermarcu** [comment]
I made a small commit to the instructions to hopefully clarify. https://github.com/dotnet/core/commit/a500d1be4c51101e01eeed996e47c617a7b38427
