### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Spitik** [dotnet/core#1052]
![image](https://user-images.githubusercontent.com/33177445/32134229-edeb0bc4-bbe8-11e7-97c3-9ad390c487f4.png)

**Comment by svick** [comment]
It looks like you installed the .Net Core *runtime*, but to use `dotnet new`, you need the .Net Core *SDK*, Did you find the error message unclear?

**Comment by yaakov-h** [comment]
It looks like you're running on a Raspberry Pi.

If so, only the .NET Core Runtime supports the Pi, not the SDK. You'll need to develop your application on another machine, then publish your application and copy it to the Pi.

**Comment by Petermarcu** [comment]
Take a look here for Pi instructions. https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by Petermarcu** [comment]
Going to close this now. The instructions provided should help you get up and running on a Raspberry Pi.
