### ISSUE TITLE
ObfuscationAttribute and ObfuscateAssemblyAttribute have wrong definitions in System.Runtime assembly

### ISSUE THREAD

**Issue by hrumhurum** [dotnet/core#1054]
# System.Runtime assembly provides wrong definitions of obfuscation attributes

_System.Reflection.ObfuscationAttribute_ and _System.Reflection.ObfuscateAssemblyAttribute_ are defined without _AttributeUsage_ declarations. This breaks the expected attribute usage semantics.

# General

.NET Core version: 2.0
OS version: Windows 10 1702 15063.674
Visual Studio version: 15.4.1

Related assembly:
**System.Runtime,** Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
located at _C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll_

Please note that provided sample compiles and works as expected in .NET and .NET Standard 2.0 platforms.

## Steps to reproduce

Try to compile the following .NET Core 2.0 console app:

```c#
using System;
using System.Reflection;

[assembly: Obfuscation(Feature = "Feat 1")]
[assembly: Obfuscation(Feature = "Feat 2")]

namespace MyApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

```
## Expected results
Assembly successfully compiles.

## Actual results
Program.cs(5,12,5,23): error CS0579: Duplicate 'Obfuscation' attribute

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25116](https://github.com/dotnet/corefx/issues/25116) via [**ZenHub**](https://www.zenhub.com/)
