### ISSUE TITLE
Unsupported raw socket programming

### ISSUE THREAD

**Issue by jakubaleksanderpolkowski** [dotnet/core#1059]
# Unsupported raw socket programming

# Unable to create new raw socket using .net core and C# on armhf hardware under linux

As above i can't create raw socket in any way. 
It seems like .net core does not support raw socket programming yet.

Hardware: Raspberry Pi3
CPU: armhf
OS: Raspbian
Runtime: 2.0.0-preview1-001887-00

Language: C#

Published on x64 Linux with sdk 2.0.0

Received error:

> " Unhandled Exception: System.Net.Sockets.SocketException: Protocol not supported
> at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType > protocolType) "

Code that whrows error:
`mainSocket = new Socket(AddressFamily.InterNetwork,SocketType.Raw, ProtocolType.IP);`

**Comment by stephentoub** [comment]
What happens if you run with sudo?

Are you able to write/run a C program that creates a raw socket successfully?

**Comment by jakubaleksanderpolkowski** [comment]
I all ready run this as sudo, I even gave CAP_NET_RAW capability to this program

**Comment by stephentoub** [comment]
And what about a C program... you have a program in C that runs successfully opening a raw socket on the same machine?

**Comment by wfurt** [comment]
https://stackoverflow.com/questions/19732145/python-raw-socket-protocol-not-supported

You need to use AF_PACKET (17 on Linux) but that does not seems to be defined for .net.  
Try Cprogram as @stephentoub suggested and check it with strace.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25115](https://github.com/dotnet/corefx/issues/25115) via [**ZenHub**](https://www.zenhub.com/)
