### ISSUE TITLE
Incorrect documentation for dot.net and Debian

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/core#106]
Today I did the following steps and could not install dotnet cli.

1. Bring up a stock Azure image for Debian 82
2. Tried to do step 1 from this URL https://www.microsoft.com/net/core#debian

It looks like you have to have libunwind and gettext before you can run the curl command.  I was able to get myself unblocked but only after following the developer guide for the corefx repo.

**Comment by blackdwarf** [comment]
@Chrisboh The script is supposed to tell you what to install. Did the script not print out the lines on the dependencies that were missing?

**Comment by Chrisboh** [comment]
It told me it was missing libunwind and gettext.  What it didn't tell me was that I need to specify libunwind8 to apt-get in order for it to work.  

On a whole though I think its a bad experience to have someone to hit errors for dependencies that we know about.  We should either install them for them or tell them up front.

**Comment by blackdwarf** [comment]
@Chrisboh there is a document on the dependencies in the CLI repo. We can't install it because that would make the script have to be run under `sudo` and we don't want it. The number there is maybe problematic, but you can search the apt-get repos for libunwind and see which version is there (which is 8). 

Ideally, by RTM time, we would/will have native packages for all of these, so it would install dependencies like that.

**Comment by Chrisboh** [comment]
@blackdwarf it is a terrible experience that we know the user is very likely to hit an error message out of box.  What I don't understand is I already have to `sudo apt-get curl` as step 1 why can't we add libunwind8 and gettext to the end of that command and make it a better user experience?

**Comment by blackdwarf** [comment]
@Chrisboh we have changed the instructions for Debian for RTM/Preview 2 bits. I've also added an issue to track adding a `sudo` mode to the the install script so it can perform the installation of dependencies: dotnet/cli#3637. 

With this, I will close this issue.
