### ISSUE TITLE
Add support for ARMv6

### ISSUE THREAD

**Issue by ivpadim** [dotnet/core#1066]
# Include support for ARMv6

This was mentioned a while ago (issue [667](https://github.com/dotnet/core/issues/667)).
Is there a plan to support ARMv6? 
The only option right now is to install mono which works ok.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #14932](https://github.com/dotnet/coreclr/issues/14932) via [**ZenHub**](https://www.zenhub.com/)
