### ISSUE TITLE
Do we need CI in this repo?

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core#1068]
I believe the only reason we had CI in this repo was to test the python scripts for building the bootstrap runtime.

**Comment by Petermarcu** [comment]
@richlander @mmitche @sunandabalu

**Comment by mmitche** [comment]
It has samples.  Maybe we should be building them?  There is CI available for this repo already.

**Comment by Petermarcu** [comment]
I think we could build the samples but it hasn't been a problem to date. Are there any other things that CI covers here?

**Comment by Petermarcu** [comment]
I'm happy to have this issue turn into. CI should build the samples if thats the only purpose of CI left :)

**Comment by mmitche** [comment]
@Petermarcu I'm not that familiar with what is in this repo.  If no CI is needed, then just empty out the netci.groovy file for now, or augment it to build the samples.

**Comment by Petermarcu** [comment]
Sounds good. I think emptying it out for now is probably the right thing to do.

**Comment by sunandabalu** [comment]
https://github.com/dotnet/core/pull/1069

**Comment by richlander** [comment]
This can be closed now, right?
