### ISSUE TITLE
Created a new classlib project using CLI/ VS code and it's throwing dotnet restore error 

### ISSUE THREAD

**Issue by teo2akt** [dotnet/core#1070]
Created a new classlib project using CLI/ VS code and it's throwing dotnet restore error. 
I did create this new project with .NET core SDK 2.0.0

E:\t>dotnet restore
C:\Program Files\dotnet\sdk\2.0.2\NuGet.targets(476,5): error : Value cannot be nul
l.\r [E:\t\t.csproj]
C:\Program Files\dotnet\sdk\2.0.2\NuGet.targets(476,5): error : Parameter name: pat
h1 [E:\t\t.csproj]
is this a known issue? and resolution?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #7990](https://github.com/dotnet/cli/issues/7990) via [**ZenHub**](https://www.zenhub.com/)
