### ISSUE TITLE
TransactionScope Support

### ISSUE THREAD

**Issue by SoggySocks2** [dotnet/core#1071]
# TransactionScope Support When Not Using EF

Using .NET Core 2.0

I wanted to use MVC for a new project but we don't want to use Enitity Framework since it will be based on an existing, large database used by other products.

However, when using our own business layer which uses TransactionScope, the .NET Core framework throws an exception.

I've since read TransactionScope is not yet supported.

This means we cannot possible use MVC with .NET Core 2.0 to build new products since data integrity is crucial

**Comment by mstfcck** [comment]
As I see it in the API, can you check it again?
https://docs.microsoft.com/en-us/dotnet/api/?term=TransactionScope&view=netcore-2.0

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25150](https://github.com/dotnet/corefx/issues/25150) via [**ZenHub**](https://www.zenhub.com/)
