### ISSUE TITLE
libhostfxr.dylib could not be found

### ISSUE THREAD

**Issue by Marksion08** [dotnet/core#1072]
# libhostfxr.dylib could not be found

$ hello> dotnet new
## _A fatal error occurred, the required library libhostfxr.dylib could not be found at /usr/local/bin/_

# Info
So happy to heart that .netcore support macOS sierra, but while I have tried that's still a big disappointment!

**Comment by Petermarcu** [comment]
Can you describe how you installed .NET Core?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #3400](https://github.com/dotnet/core-setup/issues/3400) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Marksion08** [comment]
Final solution:

Go to default user directory `cd ~`, and add below `export PATH=$PATH:/usr/local/share/dotnet` line to the end of `~/.zshrc` file 

```
cd ~
vim ~/.zshrc

export PATH="$PATH:/usr/local/share/dotnet" # Append this line to end.
```
