### ISSUE TITLE
[Suggestion] nuget packages bring the code along, like npm

### ISSUE THREAD

**Issue by mhamri** [dotnet/core#1074]
the fact that if a developer wants to do a change to a NuGet package he/she has to separately find the code in many different places like GitHub/CodePlex/google code, SourceForge, .... then do the changes, and create a new package for himself and also do a pull request, all of this is very troublesome. 

because day to day i am working with different programming languages, I see this benefit, if something doesn't work, the code is just one folder far from me (vendor folder in case of composer or node_module in case of npm, ...).  I saw many occasion that it leads to an instant pull request. on the other side, i saw .net developers if something doesn't work in a NuGet package, they try to find another package if that one also doesn't work they go and create their own code instead of fixing or contributing to that package. unfortunately, this behavior of NuGet that brings a ready to use black box, leads to have a less willing developer community to contribute. 

my suggestion is to bring the code along the packages to a local nuget folder that is not hidden from the user (not like now that the packages folder is not part of the explorer window). on the first build the new package also will build along with the other code. if everything is good, then on subsequent builds those packages will be used. if not, the changed code inside the package will build along with the others code. 

i know it's a very hard to achieve task, but it's a game changer for the .net community.

**Comment by Petermarcu** [comment]
Its a good suggestion and something that I think we'll want to do eventually. At least making source one step away where packages at least have a link to the source and there are CLI commands to easily get those packages, build them from source, and then use that build instead of the package. Its a little easier for non-compiled languages but its definitely a real scenario that would be nice.

**Comment by richlander** [comment]
Would [SourceLink])(https://github.com/ctaggart/SourceLink) work for you?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8814](https://github.com/dotnet/cli/issues/8814) via [**ZenHub**](https://www.zenhub.com/)
