### ISSUE TITLE
dotnet command build and run.

### ISSUE THREAD

**Issue by daviatorstorm** [dotnet/core#108]
When i trying to migrate aspnet dnx project to netcoreapp1.0 some packages not supported in dotnet core makes input "Object is not set to an instanse of object". But no "Wrong package in project.json file [blabla.bla:"1.1.0"]" or something like this is not shown so i do not know where exect problem is.

**Comment by blackdwarf** [comment]
@daviatorstorm is this still reproing with the latest tools/bits?

**Comment by blackdwarf** [comment]
Closing this due to the lack of activity.

**Comment by daviatorstorm** [comment]
The problem with dependencies in project.json. When all dependencies are resolved, problem disapeared.
