### ISSUE TITLE
Downloads link in Release note is broken

### ISSUE THREAD

**Issue by olakara** [dotnet/core#1088]
# Issue Title
The "Downloads" link in https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.3.md page is broken. It's pointing to https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.3-download.md which shows a 404 page.

![image](https://user-images.githubusercontent.com/570905/32851464-73bf87de-ca4e-11e7-9928-52ebfc311e76.png)

**Comment by olakara** [comment]
I have created a PR for this #1089

**Comment by richlander** [comment]
Fixed. Thanks!
