### ISSUE TITLE
DnxInvisibleFolder and DnxInvisibleContent

### ISSUE THREAD

**Issue by zygimantas** [dotnet/core#109]
I am not sure if this is a tooling or Core issue, but:

DnxInvisibleFolder and DnxInvisibleContent are still valid options in .xproj file.

```
  <ItemGroup>
    <DnxInvisibleContent Include="file.txt" />
  </ItemGroup>
```

hides file.txt from VS2015 Solution Explorer.

Should not these tags be renamed to DotNet* ?

---

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@zygimantas with the move to csproj, this will become a non-issue, so I'm going to close this one. If you feel this is in error, please reopen.
