### ISSUE TITLE
2.0.3 checksum links are broken

### ISSUE THREAD

**Issue by rgl** [dotnet/core#1095]
the checksum links at https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.3.md are broken. They should point to:

 * https://dotnetcli.blob.core.windows.net/dotnet/checksums/2.0.3-runtime-sha.txt
 * https://dotnetcli.blob.core.windows.net/dotnet/checksums/2.0.3-sdk-sha.txt

**Comment by leecow** [comment]
Sorry about that @rgl . Fixed!
