### ISSUE TITLE
Why Not Enable Least Building Works

### ISSUE THREAD

**Issue by eaglexiang** [dotnet/core#1096]
Makefile is used for many causes including reduce repeatedly building works. Files not effected by changes needn't to be built again.

But dotnet will build every file each time, which waste our time a lot. Why not build a feature to improve that like command `make`?

**Comment by Petermarcu** [comment]
Dotnet build is incremental. There are places where there are bugs or things need improvement but if something hasn't changed, generally, it shouldn't get rebuilt. If you are seeing that it may be a bug in the sdk. Msbuild supports incremental build. Can you give more details on where you see this?

**Comment by eaglexiang** [comment]
Thanks for reply, this is my environment:
OS: ArchLinux
dotnet: 2.0.2

BTW, do you mean incremental build is only supported by msbuild but not dotnet? 

I tried `dotnet run` but still happened 'rebuild'.

**Comment by eaglexiang** [comment]
Thanks for reply, this is my environment:
OS: ArchLinux
dotnet: 2.0.2

BTW, do you mean incremental build is only supported by msbuild but not dotnet? 

I tried `dotnet run` but still happened 'rebuild'.

**Comment by eaglexiang** [comment]
No output show that files're rebuilt. I judge it with the time `dotnet run` waste. In Visual Studio I can run bin output directly, but time taken in first and second times are same.

**Comment by eaglexiang** [comment]
Sorry I fixed my words.

**Comment by Petermarcu** [comment]
Ok, I'm going to move this issue to the dotnet/cli repo where the right people can get engaged to make sure we can address the incremental run scenario.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8036](https://github.com/dotnet/cli/issues/8036) via [**ZenHub**](https://www.zenhub.com/)
