### ISSUE TITLE
System.Net.Http.dll 4.6.25220.1和 System.Net.Http.dll 4.6.25514.4不兼容

### ISSUE THREAD

**Issue by ghd258** [dotnet/core#1098]
System.Net.Http.dll 4.6.25220.1和
System.Net.Http.dll 4.6.25514.4 不兼容 而且NuGet就没有4.6.25514.4 这个版本

**Comment by Petermarcu** [comment]
Translated:
System.Net.Http.dll 4.6.25220.1 and System.Net.Http.dll 4.6.25514.4 is not compatible and NuGet is not 4.6.25514.4 this version

@davidsh is this another instance of the OOB/Binding redirect challenges with System.Net.Http?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25516](https://github.com/dotnet/corefx/issues/25516) via [**ZenHub**](https://www.zenhub.com/)
