### ISSUE TITLE
Unable to bind route parameters

### ISSUE THREAD

**Issue by pavankoppineni** [dotnet/core#1099]
# Issue Title

Unable to bind route parameters

# General

I am not able to bind route parameters or query parameters to an action and am getting following error.

**Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.**

For my project, I am using 'System.ComponentModel.TypeConverter, Version=4.3.0.0' and .Net Core 1.1.

**Comment by Petermarcu** [comment]
@zhenlan is this issue best moved to the WCF repo?

**Comment by zhenlan** [comment]
Is this MEF?

@pavankoppineni, do you have a code snippet or call stack when encountering this error?

**Comment by Petermarcu** [comment]
Moved this issue here: https://github.com/aspnet/Home/issues/2291

**Comment by pavankoppineni** [comment]
@zhenlan , following is the code snippet we are using.

`// PUT: api/Default/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }`

When I try to call Put action from UI, it is giving me following error.

**Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.**

For our project, we are using **Newtonsoft.Json 10.0.3**. It internally uses **System.ComponentModel.TypeConverter, Version=4.3.0.**

**Comment by zhenlan** [comment]
@pavankoppineni this does look like asp.net related issue. @Petermarcu has moved the issue to asp.net repo. Please share any extra information you have at aspnet/Home#2291 and right folks should be able to help there.

**Comment by pavankoppineni** [comment]
@zhenlan, it is .netcore 1.1.
