### ISSUE TITLE
Link to getting started docs

### ISSUE THREAD

**Issue by BethMassi** [dotnet/core#11]
When you search for ".net core" on Google, this is repo the first hit. It would be good to add a link in the readme to help people get started.

- What is .NET Core?: http://dotnet.github.io/core/
- Get Started with .NET Core: http://dotnet.github.io/core/getting-started/ 

@richlander @blackdwarf what do you think?

**Comment by blackdwarf** [comment]
+1 to that, sounds like a great idea.

**Comment by voltagex** [comment]
And now ironically I think it's this page that's causing a search "dnvm hello world" to link to a page that doesn't exist any more. (https://dotnet.github.io/core/getting-started/ instead of https://dotnet.github.io/getting-started/)
