### ISSUE TITLE
Installer installs x86-64 version on ARMv7 Ubuntu Chromebook

### ISSUE THREAD

**Issue by ststeiger** [dotnet/core#110]
The install-script is buggy.

If I go to:
https://www.microsoft.com/net/core#debian

It says I should do this:
curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet

However, when I do that, I get:
(trusty)root@localhost:~# dotnet
bash: /usr/local/bin/dotnet: cannot execute binary file: Exec format error 

Then I run file /root/dotnet/dotnet
and discover
/root/dotnet/dotnet: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=4d1d55536bcbcce0a35a094ae691f3607b8c15a6, not stripped

However, uname -m shows
armv7l

(trusty)root@localhost:~# uname -m
armv7l

And cat /proc/cpuinfo shows  
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae 
Hardware	: NVIDIA Tegra SoC (Flattened Device Tree)
Revision	: 0000

The install script installs the x86-64 version on a ARM 32-bit version. 
BUG, you can't do that. 
Don't use x86 processors anymore, they consume too much power.

**Comment by blackdwarf** [comment]
@ststeiger interesting. If this still repros, can you please file this issue in dotnet/cli? Thanks!
