### ISSUE TITLE
Invalid Content Disposition Header

### ISSUE THREAD

**Issue by StefanoD** [dotnet/core#1106]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition the parameters of the content disposition header must be quoted. Instead APS.Net Core sends them without quote:

`attachment; filename=latest_bin.txt; filename*=UTF-8''latest_bin.txt`

I'm using .Net Core 2.0

**Comment by Petermarcu** [comment]
Moved this issue here: https://github.com/aspnet/Home/issues/2288
