### ISSUE TITLE
LAZY LOADING

### ISSUE THREAD

**Issue by joehoeller** [dotnet/core#1109]
# .NET Core 2.1 Lazy Loading
Because of this there are tons of articles written by dev's online, combined with the thoughts of enterprise to steer clear of Core because of no lazy loading support. (Dont believe me? Just google it)

# General

To say, "compatibility" will be chosen over "enhancements" is arrogant and internally driven, versus user driven.

Lazy loading should be top priority so enterprise and app dev's can fully adopt this wonderful foundation for a WebAPI.

**Comment by richlander** [comment]
Can you provide a more specific request? Do you mean APIs like [Assembly.LoadFrom](https://docs.microsoft.com/dotnet/api/system.reflection.assembly.loadfrom)?

**Comment by svick** [comment]
Are you talking about lazy loading of database entities in Entity Framework Core 2.1? In that case, you might want to have a look at [the EF Core roadmap](https://github.com/aspnet/EntityFrameworkCore/wiki/Roadmap) and the related issue (https://github.com/aspnet/EntityFrameworkCore/issues/3797).

**Comment by joehoeller** [comment]
I saw it listed as a stretch goal, when it should be moved to a priority. Another priority should be 2 factor auth using something like Google Authenticator with JWTs for secure REST services. Enterprise will be slow to adopt in these times without these 2 req;s being fulfilled.

**Comment by joehoeller** [comment]
Other than that the .NET Core team has done a great job, its an excellent start for something to build web api's from.

**Comment by richlander** [comment]
PTAL @divega

**Comment by divega** [comment]
@joehoeller please see https://github.com/aspnet/EntityFrameworkCore/issues/3797#issuecomment-345040322 for a recent update on the plan for lazy loading in EF Core 2.x. 

Your other comment about auth seems related to the features maintained at https://github.com/aspnet/Security/ or https://github.com/aspnet/Identity/. It would probably be best to provide your feedback (or ask any questions you have about the subject) in that repo.

**Comment by richlander** [comment]
Looks like this is resolved. Thanks.
