### ISSUE TITLE
Wrong Link on https://github.com/dotnet/core/releases

### ISSUE THREAD

**Issue by GuilhermeMorais** [dotnet/core#1111]
# Wrong link - Quick fix

This is a really quick fix, in the URL: https://github.com/dotnet/core/releases, as you can see on the image below, the link of "Download .NET Core 1.1.2" is going to 1.0.5, not the correct 1.1.2.

Correct link:
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md

![2017-11-22](https://user-images.githubusercontent.com/3579394/33137218-42e06b78-cf9f-11e7-89b6-112aa121fcdc.png)

**Comment by omajid** [comment]
This seems to be an SDK vs runtime versioning confusion. If you follow the link and go to the document, you will see that the download contains:

- .NET Core Runtime 1.0.5
- .NET Core Runtime 1.1.2
- .NET Core SDK 1.0.4

So it is the right document, just a little confusing in terms of versioning.

**Comment by Petermarcu** [comment]
Actually, its not SDK/Runtime confusion, its SDK that contains two runtimes confusion :) This is by design. The 1.0.5 page is shared for runtimes 1.0.5 and 1.1.2 as well as SDK 1.0.4. Yes, the versions are confusing and there are many conversations going on about how to make them better.

**Comment by Petermarcu** [comment]
Actually, this is is a bug. I don't see a link to download the 1.1.2 runtime installers. It's pointing to the SDK 1.0.4 where the runtime download links are only for the 1.0.5 and not 1.1.2.

@leecow, there seem to have been a discrpancy in the github release. I was able to update it.

**Comment by leecow** [comment]
Thanks @Petermarcu - copy/paste error :-(
