### ISSUE TITLE
Finalizer no longer called in .NET Core 2.0 after GC.Collect / GC.WaitForPendingFinalizers

### ISSUE THREAD

**Issue by sfmskywalker** [dotnet/core#1115]
Update: I also reported this issue [here](https://github.com/dotnet/coreclr/issues/15207), since that repo might be more appropriate. I'll close either this one or the other once I know for sure.

# Finalizer no longer called in .NET Core 2.0 after GC.Collect / GC.WaitForPendingFinalizers

As of **.NET Core 2.0**, an object's finalizer **is no longer called** when calling `GC.Collect` and `GC.WaitForPendingFinalizers`.

# General

To be clear: the following code works as advertised in .NET Framework 4.7 and earlier; .NET Core 1.1 and earlier; but not in .NET Core 2.0:

```csharp
[TestClass]
public class GarbageCollectionTest
{
    [TestMethod]
    [Description("Asserts that an un-rooted object's finalizer will be called.")]
    public void GarbageCollectionTest01()
    {
        // Instantiate a spy to record that the Foo finalizer is called.
        var spy = new Spy();

        // Instantiate a new Foo.
        var foo = new Foo(spy);

        // Unroot foo.
        foo = null;

        // Force a collection.
        GC.Collect(0, GCCollectionMode.Forced, blocking: true);

        // Wait for all finalizers to have executed.
        GC.WaitForPendingFinalizers();

        // Assert that Foo's finalizer is called.
        // WARNING: This assertion fails in .NET Core 2.0, but works in .NET Core 1.1 and .NET Framework 4.7 and before.
        Assert.IsTrue(spy.FinalizerIsCalled);
    }

    private class Spy
    {
        public bool FinalizerIsCalled { get; set; }
    }

    private class Foo
    {
        ~Foo()
        {
            spy.FinalizerIsCalled = true;
        }

        public Foo(Spy spy)
        {
            this.spy = spy;
        }

        private readonly Spy spy;
    }
}
```

Unit test output:

![image](https://user-images.githubusercontent.com/938393/33224269-df6ee77a-d167-11e7-857c-2fdfec794574.png)

To demonstrate the issue, I created a unit test project for the following frameworks which all share the same .cs file:

- .NET Framework 4.7 [passing]
- .NET Core 1.0 [passing]
- .NET Core 1.1 [passing]
- .NET Core 2.0 *[failing]*

[GarbageCollectionTests.zip](https://github.com/dotnet/core/files/1502553/GarbageCollectionTests.zip)

**Comment by jkotas** [comment]
CoreCLR repo is the right place for this issue.
