### ISSUE TITLE
Is System.CodeDom a part of .NET Core 2?

### ISSUE THREAD

**Issue by jlahteen** [dotnet/core#1117]
According to .NET Api Browser [System.CodeDom](https://docs.microsoft.com/en-us/dotnet/api/system.codedom?view=netcore-2.0) should be a part of .NET Core 2. However, .NET Core 2 SDK does not seem to contain the library System.CodeDom.dll. Some googling on the topic suggests that .NET Core 2 doesn't cover System.CodeDom. Is this a bug in the documentation?

**Comment by terrajobst** [comment]
That's a bug in the documentation. It's _available_ for .NET Core 2.0 but it's not _part of_ .NET Core. In other words, you'll need to reference the [System.CodeDom](https://www.nuget.org/packages/System.CodeDom) NuGet package.

**Comment by jlahteen** [comment]
Thanks for the answer. It's great that CodeDom is available for .NET Core since it enables dynamic code compilation for different scenarios.

However, the current version of [System.CodeDom](https://github.com/dotnet/corefx/tree/master/src/System.CodeDom) throws PlatformNotSupported for every CompileAssembly* method of [CSharpCodeGenerator](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.cs) since they all end up to the method [FromFileBatch](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.PlatformNotSupported.cs) which throws that exception systemically. Just wondering whether this is still the current state of development or should it already work. Everything works well in my experiment project if I just change the target framework from netcoreapp2.0 to net462.

**Comment by terrajobst** [comment]
That's unfortunately by-design as the compilers are not part of the .NET Core runtime. However, given that CodeDOM isn't referenced by the core (it only comes in when people depend on it/via the compat pack) we could probably fix this. I've filed [this bug](https://github.com/dotnet/corefx/issues/25555).

**Comment by dgamma3** [comment]
I'm getting the same issue as @jlahteen, how do we resolve it?
