### ISSUE TITLE
Instructions for CentOS fail when inside Dockerfile

### ISSUE THREAD

**Issue by DonSchenck** [dotnet/core#112]
When running the CentOS instruction inside a Dockerfile, and using docker build, the install script DOES download, but then bombs with

`dotnet_install: Error: curl is required to download dotnet. Install curl to proceed.`

Note that curl IS present. I suspect the issue revolves around the curl command being executed inside the install script is missing backticks.

**Comment by blackdwarf** [comment]
@DonSchenck is this still reproing with the install script from `rel/1.0.0-preview2` from the dotnet/cli repo? 

If so, could you please file a bug on the dotnet/cli repo and close this one, since this issue should be tracked over there for fixing? Thanks!

**Comment by blackdwarf** [comment]
@DonSchenck since there is no reply here, I will close this issue. If this still repros, please open an issue on the dotnet/cli repo. Thanks!

**Comment by DonSchenck** [comment]
Sorry I'm overwhelmed. Close it. Thanks.
