### ISSUE TITLE
Visual studio version required  for CORE 2.0.3

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/core#1122]
Unable compile VS 2017 15.3.2 project with core adi 2.0.3

Could you please confirm if it is required to
 upgrade VS 2017 to 15.4 .

**Comment by richlander** [comment]
Can you elaborate on what you mean by "core adi 2.0.3"?

**Comment by Petermarcu** [comment]
I'm assuming adi == sdk :) I don't think 15.4 is required but if you can share your error, we'd be able to help more. I'm going to close this now because we need more information but will re-open if you provide more info.
