### ISSUE TITLE
kb3035131 (exited -2145124329) - Error while running 'C:\ProgramData\chocolat ey\lib\KB3035131\Tools\ChocolateyInstall.ps1'

### ISSUE THREAD

**Issue by pinterl** [dotnet/core#1123]
# Issue Title

kb3035131 installation error during .NET Core SDK 2.0.3 installation 
# General

OS: Windows Server 2012 R2
I use Chef to I install the .NET Core SDK 2.0.3, the Chef script is

```
    chocolatey_package 'dotnetcore-sdk' do
      source 'devops-chocolatey'
      options "--allow-empty-checksums --ignore-package-exit-codes"
    end

```

It looks like the pre-requisite KB3035131 would be installed twice. It was already successfully installed, and the Dot Net Core installation may try to install it again unsuccessfully. 

The command throws the error: 

> KB3035131 v1.0.1
> 
> kb3035131 package files install completed. Performing other installation steps.
> 
> File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
> 
> Hashes match.
> 
> Virus checking skipped/turned off. Not verifying 'Windows8.1-KB3035131-x64.msu'
> 
> Hashes match.
> 
> Installing Windows8.1-KB3035131-x64.msu...
> 
> ERROR: 
> 
> Running ['C:\Windows\System32\wusa.exe' "C:\Windows\TEMP\chocolatey\KB3035131\1.0.1\Windows8.1-KB3035131-x64.msu" /quiet /norestart /log:"C:\Windows\TEMP\chocolatey\KB3035131.Install.evt"] was not successful. 
> 
>  Exit code was '-2145124329' See log for possible error messages.
> 
> The install of kb3035131 was NOT successful.
> 
> Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
> 
>  See log for details.

The attached file contains the command output of

`choco install dotnetcore-sdk -Y  --force --debug`

[dot Net Core SDK 2.0.3 Installation Error.txt.zip](https://github.com/dotnet/core/files/1519972/dot.Net.Core.SDK.2.0.3.Installation.Error.txt.zip)

**Comment by richlander** [comment]
I think that this is specific to the chocolately installer. We don't pre-req any Windows KBs/MSUs. Isn't that right @livarcocc ?

**Comment by Petermarcu** [comment]
Weird, that KB also looks like its for the Windows Kernel. I also don't think .NET Core depends on that patch.

**Comment by pinterl** [comment]
@Petermarcu @livarcocc @richlander 
When I internalize the dot net core package with 
`choco download dotnetcore-sdk --internalize`

I get the following list of NuGet packages in my working directory:

chocolatey-core.extension.1.3.3.nupkg
chocolatey-windowsupdate.extension.1.0.2.nupkg
dotnetcore-sdk.2.0.3.nupkg
KB2533623.1.0.2.nupkg
KB2919355.1.0.20160915.nupkg
KB2919442.1.0.20160915.nupkg
KB2999226.1.0.20170509.nupkg
KB3033929.1.0.3.nupkg
KB3035131.1.0.1.nupkg
vcredist140.14.11.25325.0.nupkg
vcredist2015.14.0.24215.20170201.nupkg

Is this list scripted in the dotnet core Chocolatey package, or it is based on the operating system I run the internalize command?

**Comment by Petermarcu** [comment]
Seems like whoever created that chocolatey package is putting a whole bunch of things in there that aren't needed. For example, in .NET Core 2.0, the vcredist isn't needed either. There are no dependencies that are required.

**Comment by livarcocc** [comment]
Yeah, is there a way to know who is he author? So that we can reach out to them and maybe get them to update the package? That is not us.

**Comment by Petermarcu** [comment]
https://chocolatey.org/packages/dotnetcore-sdk

**Comment by pinterl** [comment]
Thank you for following up. Yes, it is the correct package. It looks like I did not post the error at the correct forum. I have contacted the authors through Chocolatey.

**Comment by richlander** [comment]
Thanks. Looks like this is resolved.
