### ISSUE TITLE
Suggestion: Support for platform packaging/ilmerge type capability

### ISSUE THREAD

**Issue by hallambaker** [dotnet/core#1124]
# Issue  Suggestion: Support for ilmerge/libZ etc. functionality

# General

I am currently trying to package up some tools for use on Windows, OSX and Linux. And it is a real bear.

Writing platform independent code is one thing. To date there is no such thing as platform independent installation. OSX, Windows and Linux all have very different ideas about how code should be distributed. iOS and Android have more.

The ability to generate docker containers from a project is really welcome. It would be nice if there was a similar feature that allowed a developer sitting on a Windows box to cut platform native installers for all the major platforms in one compile. Like the Docker tools, the installers need not be anything fancy, people could always upgrade to something better and more full featured (Wix etc). But having a system that is supported out of the box would be a major advance.

The idea that installing programs should require modification to other parts of the computer is bogus.  One of the things I like most about .NET is that installing a program does not affect anything else on the machine. Shared libraries, dll hell, no thank you. 

The problem with the ,NET solution is that by default, programs are still delivered in IKEA flat pack format, a collection of .dll files in a directory. This is also bogus. Shared libraries should be for code that is likely to be shared.  And even then, there should always be the option of producing a stand alone executable that doesn't rely on anything outside the one file.

Apple has realized this already and deliver their applications as .ZIP files. There are tools like libZ that purport to do this for .NET but they are independent efforts and they don't work with .NET Core 2.0. Worse, the approach to signing is of the 'make it work' variety, not 'make it safe'. Everyone should be using named keys, not key files. There are far too many of those floating about on GitHub as it is.

The delivery team must have solved these problems already to deliver .NET Core. If the means of doing this was generalized just slightly and packaged up, everyone could use it.

**Comment by richlander** [comment]
Can you be more specific about what you would like? Is it fair to say that you want single file EXEs?

**Comment by hallambaker** [comment]
One thing I would like is single file .exe files that run just like any other .exe on a particular platform. I don't mind having to cut a different .exe for each platform because the loader file formats are different. I would much prefer that over having to use dotnet foo.exe

Yes, I know that there are third party, unsupported tools. But none of those will cut .NET Core 2.0 executables right now. I am using iLmerge to produce single file .exes for Windows platform using .net framework.

Another is I would like to be able to distribute code in the platform specific distribution formats. That is a .dmg for OSX, a Debian package for Linux, an MSI for Windows. I have Wix in my tool chain to do that for Windows. It would be nice if I could cut the platform executables for OSX and Debian at the same time. 

What I like about .NET versus Java is that it allows me to build platform specific versions of my code with native look and feel. Java is really great if you are happy with everything looking like it was written with the MIT Athena widgets from the 1980s. Windows 7 when it came out was the prettiest OS ever. OSX only caught up after Jobs passed on and all the skendomorphic crud was eliminated. I want native look and feel, including the installation experience.

I do have some tools of my own that might help here. I use domain specific languages a lot. If I can find one worked example of how to do a thing, I can generalize. The only tooling challenge that might be faced in generating Debian packages is having to use .tar format rather than .zip. But the tool almost certainly exists in the windows system somewhere. There is already something to build .apps but I didn't write down the reference.

**Comment by richlander** [comment]
We have been discussing single-file EXEs. It's an expensive project for us since we need to include both the runtime and managed code in the single file. With the .NET Framework scenario you mention, only the managed code needs to be included in the file, so that's much simpler.

So, we love the direction you are mentioning. We just don't have a specific timeline on it currently. We're looking for more votes on this scenario and some interesting customer scenarios that significantly benefit from this build type.

/cc @russellhadley

**Comment by hallambaker** [comment]
Thank you for considering the proposal. How about if we could compromise with just enough of the runtime to pull the additional libraries from one location on the machine?

Here is how I think it could work. Let us say that the user written parts of the program consists of program.dll and library.dll.

program.exe = {bootstrap.dll + program.dll + library.dll}

Bootstrap.dll is a chunk of code that contains load on demand links for all the libraries referenced in program.dll and library.dll. It is also the code that is the entry point for the .exe.

When invoked, the Bootstrap.dll code searches for dotnet.ext the same as if it had been typed on the command line. Then it uses the dlls in the same directory to resolve all references for linked libraries.


The combined effect is that we now have single file executables that will run on any platform without modification[*]. The only condition being that the executable for dotnet (or some new loader assistant) has to be in the search path or discoverable by some defined search scheme.

[*] If the code requires platform specific code then it will be a different executable per platform of course. Cleaning up that issue can be left to a later point however.

**Comment by richlander** [comment]
My understanding is that the problem isn't so much the runtime in the file but the managed DLLs. We don't have a way of loading them as a filestream today.

Love the idea and pragmatism but I don't think it lines up with the currently reality. @russellhadley  can fact check me.

**Comment by RUSshy** [comment]
+1 what i love about Apple is how easy it is to distribute programs, you only have to care about the .app and you ready to go, user don't have to figure out what .exe should they run in a folder with ton of different files

**Comment by Petermarcu** [comment]
I'm going to move this to the coreclr repo because it is primarily a runtime feature + some tooling.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #17026](https://github.com/dotnet/coreclr/issues/17026) via [**ZenHub**](https://www.zenhub.com/)
