### ISSUE TITLE
Gentoo ebuilds for the .Net core ecosystem provided by the .NET Foundation

### ISSUE THREAD

**Issue by cnd** [dotnet/core#1126]
Here is related issue on dotnet overlay: https://github.com/gentoo/dotnet/issues/354#issue-274318270

Currently, gentoo and gentoo-based distributions are very popular either for development and for container-based applications setups and it will be very good for us to have an actual and complete environment for .NET there.

I want Gentoo to be added to the pool of official supported distributions. As a developer for .NET related packages in Gentoo, I can offer and receive any help for making this possible.

You can contact me on cynede at gentoo.org

Thank you

**Comment by richlander** [comment]
Sent you mail to discuss further.

**Comment by Petermarcu** [comment]
Based on our conversation in email. I think the next step is to try to use http://www.github.com/dotnet/source-build inside the ebuild script.

**Comment by dorvan** [comment]
we have a portfolio of 10 and more application in .net running on Gentoo linux based production systems. We are interested in ebuild availability in official sources. At moment we use the ebuilds maintained by @mpkh  on offcial repo and overlay.

**Comment by Petermarcu** [comment]
Since there hasn't been any further conversation here, I'm going to close this now. If there are follow ups, please open an issue in http://www.github.com/dotnet/source-build
