### ISSUE TITLE
Support Console.beep on Linux (Fedora/RHEL)

### ISSUE THREAD

**Issue by chiddekel** [dotnet/core#1130]
Run on OS: Fedora 27  
Kernel Linux:  4.13.16-302.fc27.x86_64  

Step zero: `yum install beep`  
First, run` sudo modprobe pcspkr` and then beep should work.
  
Additional uncomment the /etc/modprobe.d/beep.conf line at:
`# alias platform:pcspkr pcspkr`
to
`alias platform:pcspkr pcspkr`
For automatic load pcspkr module  

 Run application beep e.g -  `/usr/bin/beep  -f 2000 -l 1000 ` 
 The beep in this case equal to n = 2000 Hz and duration 1000 ms

This is tiny, small C source includes, of beep application. 
 https://goo.gl/E3kfPy  

The portion of this code can be re-write to C# and use in Console.beep implementation for Linux platform.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25746](https://github.com/dotnet/corefx/issues/25746) via [**ZenHub**](https://www.zenhub.com/)
