### ISSUE TITLE
How do we download SDK 2.1.2?

### ISSUE THREAD

**Issue by ctaggart** [dotnet/core#1131]
Visual Studio 2017 15.5 came with dotnet 2.1.2. How do we download that version on other systems such as Mac?

There is no 2.1.2 here:
https://github.com/dotnet/core/tree/master/release-notes/download-archives

Visual Studio 2017 15.5 came with dotnet 2.1.2. How do we download that version on other systems such as Mac? 

May be the best work-a-round for now is download the daily build from master.
https://github.com/dotnet/cli

**Comment by ctaggart** [comment]
I added a global.shjson to hopefully allow dotnet 2.1.2 from Mac:
``` json
{
  "sdk": {
    "version": "2.1.2"
  }
}
```

**Comment by ctaggart** [comment]
I am looking for how to download the sdk outside of Visual Studio 2017.
![image](https://user-images.githubusercontent.com/80104/33721596-4d53e1fe-db46-11e7-8b70-1609aee2988b.png)

**Comment by Petermarcu** [comment]
The official released builds are all linked off of http://www.dot.net

**Comment by ctaggart** [comment]
@peterhuene Do you see a 2.1.2 listed there? I do not.

**Comment by richlander** [comment]
We're working on it. It will be available by Friday noon (Pacific time). Sorry for the inconvenience.

FYI: We have a release process gap that we are working on "patching".

**Comment by EdiWang** [comment]
Seems VS2017 tooling is not support .NET Core 2.1.2 even in VS2017 15.5.1. I can't change target framework to .NET Core 2.1, it only have 1.0,1.1,2.0. If I modify the csproj file manually. VS won't compile the code:

The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1

**Comment by Petermarcu** [comment]
There is no .NET Core 2.1.2. Thats the SDK version. I believe the 2.2 SDK is the one that currently supports .NET Core 2.1 targeting.

@KathleenDollard @richlander we really need to make the SDK's not have a version cap for the runtime and somehow fix the versioning confusion.

**Comment by EdiWang** [comment]
@Petermarcu so "dotnet --version" returns 2.1.2 that is the SDK version not runtime version?

**Comment by Petermarcu** [comment]
That has to be the SDK version because there is no 2.1.2 runtime version in existence. 

I can see how this is all very confusing.

@KathleenDollard is there a good doc that explains what `dotnet --info` and `dotnet --version` return.

**Comment by Petermarcu** [comment]
What does `dotnet --info` return? The reality is that there can be more than one runtime available for an SDK. I believe there is a `dotnet --list-runtimes` command that was added recently that will give you all available runtime versions. Also, because you have have many versions, dotnet really needs to see the application you intend to run in order to say which framework it will run on. It may have explicitly set a framework version for example.

**Comment by KathleenDollard** [comment]
Help for dotnet is not that easy to find, but it is correct for


dotnet --version


How/where else do you think it should be documented? Blog post?


I don't know about runtime caps, but I do not think that will be available to help us on the 2.1 SDK not supporting 2.1 runtime.

________________________________

**Comment by richlander** [comment]
Fixed: https://www.microsoft.com/net/download

**Comment by dasMulli** [comment]
@richlander @leecow There's usually also a MD file with the links in this repo (download-archives dir), is this being discontinued or was it just forgotten?

**Comment by leecow** [comment]
@dasMulli - this release managed to sneak around me and I'm still catching up to it. download-archives page will be up shortly.

**Comment by sinand99** [comment]
.NET core server bundle doesn't work with current sdk 2.1.2. Because bundle version is 2.0.3.
When I deploy my web app to local IIS, it shows "HTTP Error 502.5 - Process Failure".

dotnet --version returns 2.1.2 but runtime installed is 2.0.3

![core](https://user-images.githubusercontent.com/5251826/33993705-c29a8b14-e0e8-11e7-9246-26d02939614c.jpg)

How can we fix this whole mess? Why doesnt microsoft use proper versioning?

**Comment by ctaggart** [comment]
This original issue here was about being able to download the SDK 2.1.2 outside of Visual Studio 2017. There was a few days of lag time between publishing the VS release and the downloads being available. That downloads have been published and they are going to try and fix the lag time next time. This issue is  fixed. Please open up separate GitHub issues for other problems.
