### ISSUE TITLE
No support to use middleware in .NetStandard 1.6 from a .Net framework 4.6.1Web API App

### ISSUE THREAD

**Issue by RajKorimilli** [dotnet/core#1134]
No support found to hook in Middle-ware defined in .Net Standard 1.6 library which is referenced from .Net framework 4.6.1 Web API. From the following link from Microsoft, it mentions that Net Standard 1.6 supports Framework 4.6.1 platform. I wanted to know if my understanding on this correct and if so, would like to know the solution for this. Thanks.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Details:
----------
Visual Studio 2017 15.4.1
.Net Standard 1.6 Library
.Net Framework 4.6.1 Web API

Repro:
---------
1. Create a .Net Standard 1.6 library with a Middleware defined.
2. Reference the client library from .Net Framework 4.6.1 Web API app.
3. No provision found to hook in Middleware.

**Comment by richlander** [comment]
PTAL @glennc

**Comment by davidfowl** [comment]
This is by design. There is no interop story beteeen ASP.NET Core and WebAPI. .NET Standard does *not* apply to different ASP.NET Core versions

**Comment by richlander** [comment]
Ah, I see. This is with the ASP.NET Web API (not Core). Yes, that would not work. Does that help, in terms of an explanation, @RajKorimilli ?

**Comment by RajKorimilli** [comment]
Yes, Thanks for quick response. 
Can you please point me to any website or video where I can learn more details on .Net standard. I could not find one.
