### ISSUE TITLE
debian auto-updating package?

### ISSUE THREAD

**Issue by Spongman** [dotnet/core#1140]
currently the debian packages are version-specific.

for example, the current package is `dotnet-sdk-2.0.2`. this package will not upgrade automatically when a new version comes out. 

can we get a set of virtual packages `doetnet-sdk` , `dotnet-sdk-x`, and `dotnet-sdk-x.y` that automatically update? (and similar for the runtimes?)

for example, there's only one `openjdk-8-jdk` package. it installs the latest SDK, and it updates automatically. all packages that follow SemVer correctly can behave in this way without breaking existing clients.

EDIT: oh look at that, the docs i was looking at (https://www.microsoft.com/net/learn/get-started/linuxdebian) are out of date. the latest package is actually `dotnet-sdk-2.0.3`. i think this illustrates perfectly the need for non-version-specific packages.

**Comment by richlander** [comment]
PTAL @leecow

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8209](https://github.com/dotnet/cli/issues/8209) via [**ZenHub**](https://www.zenhub.com/)
