### ISSUE TITLE
debian packages install to the wrong location

### ISSUE THREAD

**Issue by Spongman** [dotnet/core#1141]
according to https://wiki.debian.org/FilesystemHierarchyStandard the `/opt` directory is for "Pre-compiled, non ".deb" binary distribution".

the dotnet packages _are_ .deb packages, and so therefore should not go into `/opt`. Also, the `dotnet` symlink should go into `/usr/bin` _not_ `/usr/local/bin`. `/usr/local` is reserved for use by the system administrator.

**Comment by richlander** [comment]
PTAL @leecow

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #3506](https://github.com/dotnet/core-setup/issues/3506) via [**ZenHub**](https://www.zenhub.com/)
