### ISSUE TITLE
Core does't read the server certificate

### ISSUE THREAD

**Issue by hammond-of-texas** [dotnet/core#1142]
# Issue Title

Core doesn't read the server certificate

# General

In general, a simple request like this will work in .Net:

        static void Main(string[] args)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://www.sbb.ch");
            HttpWebResponse response = (HttpWebResponse) request.GetResponse();
            X509Certificate cert = request.ServicePoint.Certificate;
        }

The same thing will fail in core 2.0 with a "System.PlatformNotSupportedException: 'Operation is not supported on this platform.'" exception.

**Comment by richlander** [comment]
PTAL @davidsh

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25816](https://github.com/dotnet/corefx/issues/25816) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #25817](https://github.com/dotnet/corefx/issues/25817) via [**ZenHub**](https://www.zenhub.com/)
