### ISSUE TITLE
Install dotnet core using npm/yarn

### ISSUE THREAD

**Issue by aminebizid** [dotnet/core#1144]
# Feat Title

use dotnet core as NPM Package in my project

# General
My application is a set of projects with different languages (nodejs, python, dotnet core, etc.) stored on a unique git repo.
The idea is to use a unique package.json file to install all build tools via npm or yarn.
Nowaday, we need to install dotnetcore manually on dev and build machines.
It will be great if we could run such commands:
npm install @microsoft/dotnetcore@latest
this will install dotnetcore locally in my project
npm run dotnet-restore
npm run dotnet-build
npm run dotnet-test

**Comment by Petermarcu** [comment]
That would require someone putting .NET Core in NPM.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8208](https://github.com/dotnet/cli/issues/8208) via [**ZenHub**](https://www.zenhub.com/)
