### ISSUE TITLE
dotnet restore on debian 9 dotnet sdk 2.0.3 fails to download any packages

### ISSUE THREAD

**Issue by dvogel** [dotnet/core#1146]
I downloaded the [minimal install of debian 9](https://gemmei.ftp.acc.umu.se/debian-cd/current/amd64/iso-cd/debian-9.3.0-amd64-netinst.iso) and installed it using defaults.

Then I followed [the directions for installing dotnet sdk](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x). I ran:

```
export PATH=$PATH:$HOME/dotnet
mkdir test0
cd test0
dotnet new mvc
dotnet restore
```

The restore command printed out:

```
  Restoring packages for /home/dvogel/test0/test0.csproj...
  Restore completed in 39.83 ms for /home/dvogel/test0/test0.csproj.
  Restore completed in 60.96 ms for /home/dvogel/test0/test0.csproj.
```

That output looked successful at first but a subsequent `dotnet build` will fail due to missing packages. The `$HOME/.nuget/packages` directory is empty.

Here's an OVA exported from virtualbox: http://acfa3ee7d7a82c5cc99c3982b6dab6ab.s3.amazonaws.com/dotnet-devel1.ova (password is "microsoft" for both the root and dvogel accounts).

The `PATH` change seems suspect because nothing is actually installed into `$HOME/dotnet` and the `dotnet` commands don't seem to create any files in that directory.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8203](https://github.com/dotnet/cli/issues/8203) via [**ZenHub**](https://www.zenhub.com/)
