### ISSUE TITLE
.NET Core 2.1 download link missing from archive/docs

### ISSUE THREAD

**Issue by enricosada** [dotnet/core#1147]
in https://www.microsoft.com/net/download/windows there is `v2.1.2` as default to download .net core.
but no info/link in docs and https://github.com/dotnet/core/blob/master/release-notes/download-archive.md etc

**Comment by richlander** [comment]
That will be fixed tomorrow. We didn't fully follow our own release process for 2.1.2. As a result, the release notes got missed.

**Comment by mattzink** [comment]
Seems like Core 2.0.3 and SDK 2.1.3 we're also stealth released a few days ago without any release notes,

**Comment by Petermarcu** [comment]
@leecow did we get all the release notes out and we can close this issue?

**Comment by leecow** [comment]
2.1.2 SDK was a 15.5 release with no runtime updates - https://github.com/dotnet/cli/releases/tag/v2.1.2. Everything else should be caught up in the github archive.
