### ISSUE TITLE
ASP.NET Core Web Application Visual Basic (VB)

### ISSUE THREAD

**Issue by tb-mtg** [dotnet/core#1151]
Any idea on when we will be able to create new projects for ASP.NET Core Web Application using Visual Basic?

**Comment by richlander** [comment]
PTAL @AnthonyDGreen

**Comment by tb-mtg** [comment]
Any idea?

**Comment by simonmilne80** [comment]
Agree, any update on when this will be available would be great! I have lots of code i would like to update to work under .net core and dont want to re-write in c#

**Comment by Petermarcu** [comment]
@KathleenDollard . I believe you can write a .NET Standard 2.0 Library in VB but haven't tried myself. You should then be able to reference that as a dll just about anywhere.

**Comment by tb-mtg** [comment]
Yes but what about .NET Core projects and the ability to use Razor Pages Web Projects using Visual Basic (.vbhtml).

**Comment by Petermarcu** [comment]
I wasn't saying that was a complete solution. You mentioned .NET Standard so I figured I'd mention that. @KathleenDollard is probably best to answer vb for .NET Core and @DamianEdwards may be able to comment on vbhtml.

**Comment by tb-mtg** [comment]
I have found .NET Core projects that support custom ViewEngines  for [.pug](https://github.com/AspNetMonsters/pugzor) & [.md](https://github.com/hishamco/MarkdownViewEngine) file types but cannot make it work for .vbhtml files.

It would be great to make it happen using a .vbproj  with `<Project Sdk="Microsoft.NET.Sdk.Web">`.

**Comment by KathleenDollard** [comment]
I apologize for our delay, some things here have even in transition. 

ASP.NET Core WebApi applications are supported. There are some Entity Framework developer issues that are not yet resolved, but other things should work. Please report issues you encounter. 

However, vbhtml files are not supported in ASP.NET Core and that is not on the current roadmap. With the high level of interest in Angular, React, etc front ends and fairly low VB usage in Core and Razor scenarios, the is not a current priority. You can place views in a different (C#) projects. The current focus is on VB working in other scenarios. 

We are working in a broader statement to put this decision in context, but that will take a bit of time and I don't want to delay answering your specific question.

**Comment by Petermarcu** [comment]
I'm going to close this issue now because VB support in ASP.NET is tracked here: https://github.com/aspnet/Home/issues/2738

@Eilon
