### ISSUE TITLE
dotnet new Command keep telling me to download sdk but it is installed

### ISSUE THREAD

**Issue by abel406** [dotnet/core#1152]
# Issue Title

dotnet new Command keep telling me to download sdk but it is installed

# General

I am using Windows Pro 10.0.16299.15 and dotnet sdk version 1.0.4, 1.1.5 and 2.1.2. When i go to the cmd and run "dotnet new" it keeps giving me the following ,essage: 

> C:\Users\necn>dotnet new
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
I have searched all over internet and found nothing related to this. Have someone had the same issue ?
 
When running dotnet --info i have the following message:

> C:\Users\necn>dotnet --info
Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Thanks.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8219](https://github.com/dotnet/cli/issues/8219) via [**ZenHub**](https://www.zenhub.com/)
