### ISSUE TITLE
.NET Framework reference in ASP .NET Core project

### ISSUE THREAD

**Issue by troncomputers** [dotnet/core#1162]
Project ASP .NET Core 2.0. I referenced .NET Framework dll. 
```html
<div class="test">
    <form method="post">
        <input type="submit" value="Zapisz" />
    </form>
</div>
```
```csharp
        public void OnPost()
        {
            Utils.Logowanie();

            Utils.DodajKontrahenta();
            Utils.DodanieTowaru();
            Utils.DodanieFaktury();

            Utils.Wylogowanie();
        }
```
All this methods uses methods from referenced dlls. And when I hit `Zapisz` button I'm getting this:
```
BadImageFormatException: Could not load file or assembly 'ICDNBase, Version=2018.0.1.549, Culture=neutral, PublicKeyToken=5179454a0b814fab'. 
An attempt was made to load the program in an incorrect format.
```

[Utils.zip](https://github.com/dotnet/core/files/1558509/Utils.zip)

![reference_net_core](https://user-images.githubusercontent.com/29543667/33984352-a2ce2ec0-e0b7-11e7-8a39-ca1571579acf.png)

**Comment by richlander** [comment]
Did you compile ICDNBase as 32-bit and loaded into a 64-bit process or vice-versa?

You can use the Fusion Log viewer to get more information on why loading fails: https://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx

Report back?

**Comment by troncomputers** [comment]
Assemblies listed on screenshot aren't mine. I've changed debuging to x86 and in Visual Studio Output tab is the same error but pointing to my project dll - Optima365.dll
```
Unhandled Exception: System.BadImageFormatException: 
Could not load file or assembly 'C:\Users\AdamWozniak\source\repos\Optima365\Optima365\bin\x86\Debug\netcoreapp2.0\Optima365.dll'. 
An attempt was made to load the program in an incorrect format.
```
In browser I'm getting `HTTP Error 502.5 - Process Failure`

**Comment by richlander** [comment]
Are you using the 32-bit or 64-bit version of .NET Core? If you are using the 64-bit version, then this error is expected.

**Comment by troncomputers** [comment]
Is there any chance to choose bit version in .NET Core? I have installed both 32 and 64.

**Comment by jhudsoncedaron** [comment]
`dotnet publish -r win7-x86` or `dotnet publish -r win7-x64`

**Comment by Petermarcu** [comment]
To produce a compiled output that is 32bit, yes, you can `dotnet publish -r win-x86`. That will produce a self-contained application. In .NET Core 2.0 and beyond, you can add a `--self-contained=false` to that command to prevent the whole runtime being placed in your output folder. 

Lastly, if you want to run the SDK as 32bit, you need to create a 32-bit environment with the 32-bit dotnet.exe being the one on your path or find some other solution for ensuring that only the 32-bit SDK is used. 

I'm going to close this now. If there are still challenges. Let us know and we can help open up an issue on the specific case where there are challenges.
