### ISSUE TITLE
Errors on Clean Install of Visual Studio & Core

### ISSUE THREAD

**Issue by Gfweis** [dotnet/core#1164]
I had a Core 2.0 project that ran perfectly (https://CondoAdmin.net). However,  I had to reformat my main workstation computer.  The last thing that I installed was VS 2017 (v15.5.2) with the appropriate items checked to build Core web apps (I also later tried Preview 15.6 with the same bad results).

Whether old or new Core Web, console or class library project, I get nothing but errors similar to the following…

error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
NU1202: Package Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.1 does not support any target frameworks.

If I do dotnet –version, I get 2.1.2
If I do dotnet restore I get... D:\DotNetRazor\yyyZLib\yyyZLib.csproj : warning NU1701: Package 'Microsoft.CSharp 4.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'.    

What am I missing? Is 2.1.2 compatible with 2.0?

I also posted a similar question on StackOverFlow.com 

Any help/direction appreciated.   

From the web app project file..
`<ItemGroup>
    <PackageReference Include="GoogleAnalyticsTagHelperComponent" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCaching" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.1" />
    <PackageReference Include="TagHelperSamples.Authorization">
      <Version>2.0.37</Version>
    </PackageReference>
  </ItemGroup>
`

**Comment by Petermarcu** [comment]
For completeness, what is your TargetFramework? I'm assuming it's netcoreapp2.0?

**Comment by Petermarcu** [comment]
Actually, looks like it's netstandard2.0. Right?

**Comment by Petermarcu** [comment]
Not sure but it may already be included in the ASP.net All package. Can you try removing Microsoft.VisualStudio.Web.CodeGeneration.Design?

**Comment by Gfweis** [comment]
It is 2.0.  I can remove Microsoft.VisualStudio.Web.CodeGeneration.Design from the web project, but there are two NetStandard.library that also fail with  a system not found among a variety of other errors. 

Even if I start a brand new core web app project, I get lots of errors including...
NU1202: Package Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.1 does not support any target frameworks.
NuGet package restore failed.

**Comment by richlander** [comment]
The error on Microsoft.CSharp is odd, since it has a netstandard asset. Why is that @Petermarcu ?

**Comment by livarcocc** [comment]
cc @mlorbetske to comment on the CodeGeneration package failure.

**Comment by mlorbetske** [comment]
@prafullbhosale

**Comment by prafullbhosale** [comment]
> NU1202: Package Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.1 does not support any target frameworks.

>NU1202: Package Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.1 does not support any target frameworks.

The part of the error message `does not support any target frameworks.` in the above seems very fishy. Could it be an installation issue or perhaps the NuGet cache is corrupted somehow? 

@Gfweis have you tried clearing out the nuget cache and re-installing the dotnet CLI

**Comment by Gfweis** [comment]
@prafullbhosale  ... I did try clearing the cache, didn't work. Did a lot of  Google searches with no good results. This was kind of my last resort. My other computer is on 2.1.2 and all works there. The only difference is that it was upgraded from 2.0. This machine didn't have 2.0 first, just what was installed  by VS 2017 and the actual Core downloads.  This is a slow day and I found a download of 2.0  so I may strip the machine again and before installing VS I will install Core 2.0 and then let the upgrades be done. A real pain, but maybe it will work.

**Comment by Gfweis** [comment]
Finally had time to get back to the problem. I stripped the computer, reinstalled Windows and before anything else I installed .Net Core 2.0. After installing SQL and VS, all worked. If you ever have to redo you computer, you may want to install Core 2.0, before installing VS.
