### ISSUE TITLE
run on Openwrt or LEDE ?

### ISSUE THREAD

**Issue by timiil** [dotnet/core#1165]
# Issue Title

run on Openwrt or LEDE ?

# General

do we have any seccuss story about install .net core runtime into a openwrt or lede, if a walkrhrough will be very very nice:)

**Comment by Petermarcu** [comment]
.NET Core runs on basically any glibc based distro. Assuming the version of OpenWRT/LEDE you are using is glibc based, you can try this:

Download the runtime tar.gz and extract it somewhere and put it on your path. https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.4-linux-x64-binaries

Follow the same instructions as for a RaspberryPi and publish a self contained application from any developer machine. https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

Use linux-x64 instead of linux-arm. Also make sure you have installed the linux pre-reqs into your distro. https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md#getting-the-app-to-run-on-the-pi

**Comment by Petermarcu** [comment]
I'm going to close this for now. We're constantly exploring how to run on more distros. Give my suggestions a try and let us know how it goes.

**Comment by YumingLin** [comment]
has anyone tried this? I got no luck trying to get it running on my wrt32x running openwrt-18.06. I think it is libc based instead of glibc.

**Comment by AddRemover** [comment]
I also need to run one .net app on my Openwrt router on ARMv7 (Linksys WRT3200ACM), but there is no linux-musl-arm binaries.
linux-arm does not work :(

**Comment by matthew-yee** [comment]
2 options (first one is tested by me, the 2nd is from a post that i found but didnt go down tat path)
Option 1 - run using lxc:
Tested on Pi4 with usb stick

- Install LXC luci app and veth

- mount a tmpfs at "/run" else you wont get lxc creation working in the following steps ("unable to get lock" type errors). In my case, i added this to my openwrt startup script
`mount -t tmpfs -o size=32k tmpfs /run`

- mount a usb partition to /srv/lxc (as above, added to start up, theres better ways though such as fstab)

- reboot 

- Create a lxc container from the luci services menu. i decided ubuntu 18 thats what i'm used to

- setup network in the lxc config file
my config has the following core bits

 `lxc.net.0.type = veth
lxc.net.0.link = br-lan
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:0a:2f:ca
lxc.net.0.ipv4.address = 192.168.1.128/24
lxc.net.0.ipv4.gateway = 192.168.1.1
`

- start lxc container via luci lxc menu

if all has gone well, you should have a green dot and should be able to attach to it via the openwrt command "lxc-attach -n <name of container>

from there you can install .net and setup ssh (the container hopefully got an ip address from openwrt).


option 2 - compile .net apps for openwrt
summered by the post  https://davidjmclaughlin.com/projects/how-to/2020/03/15/running-.net-core-on-openwrt-and-raspberry-pi-4.html


I went with option 1 as the pi (running openwrt as the host os) and lxc containers as my "vm" within openwrt.
- didnt need to worry about accidentally breaking openwrt (the lcx is pretty isolated) 
- liked ubuntu for the day to day stuff 
- liked to kill off lxc containers when they no longer needed (easy to clean up afterwards)
- space / cpu wasnt an issue as it was on a pi running as a router

your mileage may very based on hardware etc

![image](https://user-images.githubusercontent.com/65748936/89922449-65acd800-dc42-11ea-99be-7d721710c32d.png)
![image](https://user-images.githubusercontent.com/65748936/89922909-13b88200-dc43-11ea-8617-9df9a5659550.png)
![image](https://user-images.githubusercontent.com/65748936/89922773-df44c600-dc42-11ea-98f8-dc32e8436e74.png)
