### ISSUE TITLE
.NET Core 2.0.4 release notes

### ISSUE THREAD

**Issue by jnm2** [dotnet/core#1167]
##### At @karelz's [request](https://gitter.im/dotnet/corefx?at=5a35621c540c78242dd1efc3)

Unlike other releases, there do not seem to be release notes for 2.0.4. Why is this?

**Comment by karelz** [comment]
BTW: @leecow mentioned offline that he is working on the release notes, he just didn't publish them yet :). Should be early this week.

**Comment by leecow** [comment]
https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.4.md

**Comment by jnm2** [comment]
Thank you!
