### ISSUE TITLE
dotnet build hangs in docker container 

### ISSUE THREAD

**Issue by CodeObsess** [dotnet/core#117]
I am using docker version 1.11.1  UBUNTU 14.04. VM=VMWareplayer 
dotnet restores starts for my aspnet core rc2 application but it hangs after restoring packages.

**Comment by DonSchenck** [comment]
What does your Dockerfile look like?

**Comment by CodeObsess** [comment]
I run the dotnet build and restore and then copy the directory by using the copy command in Dockerfile. The technique works flawlessly.

**Comment by blackdwarf** [comment]
@CodeObsess I'm not sure what the problem is here based on your description. If this is still reproing for you, can you please open an issue on the dotnet/cli repo? I will close this one. Thanks!
