### ISSUE TITLE
Process.Start not working properly in Mac

### ISSUE THREAD

**Issue by viswa18** [dotnet/core#1171]
# Process.Start not working properly in Mac

I have simple C++ command line application , which is running from .net core 2.0. I have set pinfo.CreateNoWindow = true;
 and 
pinfo.WindowStyle = Hidden;

When running the application in mac, it opens the application icon in dock and close it. But it does not show any icon in windows and Linux. Can anyone help me to overcome this. I do not want the icon in dock. If it is a issue in .net core, when it will be fixed?

Thanks in advance.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #26340](https://github.com/dotnet/corefx/issues/26340) via [**ZenHub**](https://www.zenhub.com/)
