### ISSUE TITLE
.NET Core December 2017 Update

### ISSUE THREAD

**Issue by leecow** [dotnet/core#1172]
# .NET Core December 2017 Update

The .NET Core December 2017 Update is available. This release includes .NET Core 2.0.4 and .NET Core SDK 2.1.3

You can read about the update in the [.NET Core release notes](https://github.com/dotnet/core/blob/master/release-notes/README.md).

Please report any issues you find with the December 2017 Update, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by smarts** [comment]
the release notes for this update in this repository has an incorrect link to the corresponding core-setup release

**Comment by tomgron** [comment]
I agree - please link changelog to release, would be easier to find.

**Comment by Petermarcu** [comment]
closing in favor of https://github.com/dotnet/core/issues/1199
