### ISSUE TITLE
Open .dll in new console window on Linux .Net Core

### ISSUE THREAD

**Issue by maroallegro** [dotnet/core#1177]
I am able to run program.dll in same console window by running:

    var process = new Process
    {

        StartInfo = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = "program.dll",
            UseShellExecute = true,
            RedirectStandardOutput = false,
            RedirectStandardError = false,
            CreateNoWindow = false
        }
    };

    process.Start();

How to open program.dll in new console window on Linux using .NET Core 2.0?

Flag `CreateNoWindow = false` do not open new console as on Windows system.

Is it a bug?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28182](https://github.com/dotnet/corefx/issues/28182) via [**ZenHub**](https://www.zenhub.com/)
