### ISSUE TITLE
Request.Path is empty while Request.PathBase is not

### ISSUE THREAD

**Issue by markentingh** [dotnet/core#1178]
# Request.Path is empty while Request.PathBase is not

# General

Using .NET Core 2.0, Windows 10, IIS Express.

While debugging my .NET Core web application, IIS Express launches a new browser window with the address `localhost:7777/dashboard`. Usually, I am able to view my web site at this point, but upon transferring my project over to a new machine with a fresh copy of Visual Studio Community 2017, the project returns a very strange error. The environment is identical to the environment on my last machine, so I see no reason why this error should occur. The error occurs because `HttpContext.Request.Path` is empty, even though I am accessing the path `/dashboard` in the URL. I noticed something very strange while looking into the error. `HttpContext.Request.PathBase` returns `/dashboard` even though `HttpContext.Request.Path` is returning an empty string.

The `HttpContext` object is accessed from the `context` argument passed within the line of code, `app.Run(async (context) =>{});` located in `Startup.cs`.

**Comment by chernovol** [comment]
Got same issue, why you have closed this ticket?

**Comment by markentingh** [comment]
I closed it because I thought perhaps it was my own fault since I inherited the startup class with another startup class. But after some experimentation, I realized the problem persisted. I have a few other projects that work just fine, uses similar code base, same .NET Core version. I thought the problem was my own, but now I am reopening this because I can’t get request.path to populate in this one project no matter what I try.

**Comment by markentingh** [comment]
Also, I’ve come to realize that this issue persists on both dev machines, not just on the machine I transferred the project to.

**Comment by markentingh** [comment]
I think I've narrowed down the issue at hand. All of my projects use Microsoft.AspNetCore NuGet packages for version 2.0.0, except for the project with this issue. That project uses NuGet packages 2.0.1. I can confirm that this issue only exists in Microsoft.AspNetCore NuGet packages version 2.0.1 because after installing & updating my project to version 2.0.0, everything works again.

**Comment by markentingh** [comment]
It worked for a few minutes after downgrading Microsoft.AspNetCore NuGet packages down from 2.0.1 to 2.0.0, and then it stopped working again. I haven't touched any code or closed the project, or done anything in any way to affect anything. I simply pressed play, stop, and play again, and it worked the first time, and now Request.Path is returning "/" instead of "/dashboard". Before it was working at all, though, Request.Path was returning an empty string, so now I'm getting even stranger behavior.

**Comment by markentingh** [comment]
Now I've narrowed it down even further. The first page request comes from dotnet.exe, then all other page requests are coming from a second instance of dotnet.exe. Very strange behavior!!!

Here is a log of page requests coming from my Startup.cs app.Run function. I am unable to break on any break points after my first request because all code is executed on a second dotnet.exe.
```
Websilk> Hosting environment: Development
Websilk> Content root path: C:\Projects\Websilk\Home\App
Websilk> Now listening on: http://localhost:26577
Websilk> Application started. Press Ctrl+C to shut down.
Websilk> --------------------------------------------
Websilk> 10:12:42 GET /
Websilk> END GET / 446 ms page
Websilk> 
Websilk> Hosting environment: Development
Websilk> Content root path: C:\Projects\Websilk\Home\App
Websilk> Now listening on: http://localhost:12425
Websilk> Application started. Press Ctrl+C to shut down.
Websilk> --------------------------------------------
Websilk> 10:12:51 GET /
Websilk> END GET / 14 ms page
Websilk> 
Websilk> --------------------------------------------
Websilk> 10:13:42 GET /
Websilk> END GET / 15 ms page
Websilk> 
Websilk> --------------------------------------------
Websilk> 10:14:01 GET /
Websilk> END GET / 9 ms page
Websilk> 
Websilk> --------------------------------------------
Websilk> 10:14:02 GET /
Websilk> END GET / 12 ms page
Websilk> 
Websilk> --------------------------------------------
Websilk> 10:14:24 GET /
Websilk> END GET / 9 ms page
Websilk> 
```

**Comment by markentingh** [comment]
For whatever reason, IIS Express launches two applications for my website. There is absolutely no reason for this! No where in my launchSettings.json does it tell IIS Express to do this.

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:7778",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

![2017-12-27 1](https://user-images.githubusercontent.com/2896371/34390528-254ca7b8-eaf5-11e7-9a2d-b91fb6667961.png)

**Comment by markentingh** [comment]
I figured out a solution. I simply deleted the hidden folder `.vs` and everything went back to normal :)

**Comment by chernovol** [comment]
Thanks, I've just moved to use IIS instead IISExpress, that helps too.

**Comment by Segment22** [comment]
Error still exists. Changing App URL in project properties corrupts .vs\config\applicationhost.config file.

```
<application path="/" applicationPool="WebMonitoring AppPool">
          <virtualDirectory path="/" physicalPath="C:\Repository\Monitoring\Sources\Application\WebMonitoring\WebMonitoring" />
          <virtualDirectory path="/api/Cfg" physicalPath="C:\Repository\Monitoring\Sources\Application\WebMonitoring" />
          <virtualDirectory path="/api" physicalPath="C:\Repository\Monitoring\Sources\Application" />
</application>
<application path="/api/Cfg/Register" applicationPool="Register AppPool">
           <virtualDirectory path="/" physicalPath="C:\Repository\Monitoring\Sources\Application\WebMonitoring\WebMonitoring" />
</application>
```

**Comment by Tankatronic** [comment]
Also seeing this issue even when running as a local site outside of visual studio. Path is null but PathBase is not. I did try to delete my .vs folder but that did not resolve it.

**Comment by jose-solorzano** [comment]
I got into this state by changing the applicationUrl in launchSettings.json. Changing it back didn't fix it, however, until I deleted the hidden .vs folder.
