### ISSUE TITLE
.NET Core SDK for Windows installer doesn't honor custom location

### ISSUE THREAD

**Issue by zorbasolutions** [dotnet/core#118]
1. Download and run DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe
2. Click options and enter the path for e.g. c:\.NetCoreSDK-1.0.0-RC2
3. Click Install and installer will put files under c:\program files\dotnet and NOT in c:\.NetCoreSDK-1.0.0-RC2

**Comment by blackdwarf** [comment]
@zorbasolutions does this repro with the RTM installers you can download from https://dot.net/core?

**Comment by zorbasolutions** [comment]
Yes, same results. From the page you sent me, I downloaded https://go.microsoft.com/fwlink/?LinkID=809122 which is version Preview 2. I clicked on options and changed the directory to C:\mydotnet

Installer ran just fine but after install is complete my c:\mydotnet is still Empty.

Thanks,

**Comment by mairaw** [comment]
I remember seeing this issue reported before and the answer was that custom paths would be disabled in the future but can't remember where I saw this. @ericstj do you know anything about this?

**Comment by ericstj** [comment]
Just use the ZIP if you want this.  https://github.com/dotnet/cli/issues/3568

**Comment by zorbasolutions** [comment]
Fine, Zip can work but please remove the option from the installer msi. It is confusing to any user if it doesn't work.

**Comment by ericstj** [comment]
Yep, I believe the linked issue is tracking the removal.

**Comment by Petermarcu** [comment]
Closing this issue as its tracked in the repo where the fix needs to be.
