### ISSUE TITLE
Core assets missing / Nuget Packages do not restore, and/or corrupt NuGetFallbackFolder

### ISSUE THREAD

**Issue by steevcoco** [dotnet/core#1181]
This issue is exactly as described in:

#1006 - ".Net Core v2.0 - Nuget Packages are not getting restored"
and
#5995 - "Assets from packages are missing after restore"
#920 - ".NET Core 2 does not work...."

But, I actually just performed a Windows Defender full "System Refresh", and then a full reinstall of VS Enterprise 15.5.2, and had the issue, so then uninstalled, and did VS Installer InstallCleanup -f, and even after that yet one more full Repair ...

And still I was only able to fix it by eventually removing the NuGetFallbackFolder.

I thought I should post another issue because none of those extensive 'Repairs' actually fixed the problem!

**Comment by Petermarcu** [comment]
@rrelyea probably should move to nuget/home?

**Comment by salmonz** [comment]
I have the same problem. Workaround is run dotnet restore in the console.

**Comment by salmonz** [comment]
@steevcoco what was the permanent resolution? I don't think running dotnet restore int the console is acceptable. Preferred behaviour is when you create a new project in Visual Studio and build, all dependencies should resolve.

**Comment by steevcoco** [comment]
@salmonz sorry: I actually closed the issue because I have not seen the problem again ...

My ACTUAL solution did require deleting the NuGetFallbackFolder. You THEN can do dotnet restore on some solution to rebuild that folder: I had to delete the folder to get it in working order again.

I closed the issue because it has just been sitting open ... Perhaps I should re-open it.
