### ISSUE TITLE
.NET Core 1.1 Release Builds Missing

### ISSUE THREAD

**Issue by bleepzter** [dotnet/core#1182]
# Release builds are missing or pointing to a 404 page in Git Hub

All the links in this screen shot point to 404 pages. Why!?!?!?! People who depend on these particular versions (like me) can't find the binaries because they are no longer available in git hub or the asp.net core page.

![image](https://user-images.githubusercontent.com/3333921/34315114-2cf1a956-e739-11e7-80f0-e2f80952b28b.png)

**Comment by Petermarcu** [comment]
I think this page has been totally changed now. Let us know if you still see 404 pages behind links.
