### ISSUE TITLE
Referenced assemblies set to copy local are not copied to the output directory

### ISSUE THREAD

**Issue by nefcanto** [dotnet/core#1183]
**Referenced assemblies which are set to Copy Local are not copied to the output directory**

I've described this in [this StackOverflow question](https://stackoverflow.com/questions/47952361/assembly-referenced-in-csproj-is-not-copied-to-output-directory) too.

I want to work with Azure Storage. I've added Nuget package references, this way:

```
<ItemGroup>
	<PackageReference Include="WindowsAzure.Storage" Version="8.7.0" />
	<PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
</ItemGroup>
```

However, when I build the project (which is a web project by the way), I receive an error that it can't find the required DLL files from these packages. When I look at the output folder which is `bin\Debug\netcoreapp2.0\` in my case, I see that no DLL from those packages exist in that folder.
The point that it can't find those DLL files means that something is not working properly. We expect by including a package reference in CSPROJ, all of the required actions be taken care of automatically.

So, I decided to add extra lines of code, to explicitly copy the required DLL files to the output folder:

```
<ItemGroup>
    <Reference Include="Microsoft.WindowsAzure.Configuration">
        <HintPath>..\Microsoft.WindowsAzure.Configuration.dll</HintPath>
        <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.WindowsAzure.Storage">
        <HintPath>..\Microsoft.WindowsAzure.Storage.dll</HintPath>
        <Private>true</Private>
    </Reference>
</ItemGroup>
```

But they are not getting copied. What's the problem?

**Comment by Petermarcu** [comment]
I think you need to go back to package references and you need to do `dotnet publish` to produce a build of your application with everything copied. `dotnet build` and `dotnet run` do things the "fast way" which is to reference things where they are on disk and avoid the cost of copying to the app folder. Publish is the way to build your final application with everything copied local. Make sure you run your app from the publish folder at that point using `dotnet path/to/publish/folder/App.dll`.

**Comment by brentmorrisa** [comment]
Dotnet publish is not getting my copy-local true files, either.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8837](https://github.com/dotnet/cli/issues/8837) via [**ZenHub**](https://www.zenhub.com/)
