### ISSUE TITLE
Release Notes need to be updated

### ISSUE THREAD

**Issue by Allann** [dotnet/core#1186]
# .Net 2.1.3 has been release, yet release notes page says 2.0.3

I just installed 2.1.3 and wanted to know what had changed so that I could test our applications that are affected by this update.  I clicked on the release notes link (https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0.md) however I was taken to a very old page that needs to be updated.

# General

These release notes are extremely important for the community so that we know what is affected by changes, features and bug fixes introduced in each release.  As an example when VS Code is released it automatically displays a page of all changes, this would be great to replicate for Core too.

**Comment by Petermarcu** [comment]
I believe this is all noted here: https://github.com/dotnet/core/blob/master/release-notes/2.0/README.md

Does that help?

**Comment by Allann** [comment]
yep.  I didn't know this existed, it wasn't what "Release Notes" was linked to.
