### ISSUE TITLE
Asp.NET Core 1.0.1 published web application is Slow on Windows server2008 R2

### ISSUE THREAD

**Issue by Elias-Heydarpour** [dotnet/core#1187]
hi ,
when i host my asp.net core 1.0.1 mvc application (api controller)on IIS in windows server 2008r2
,responses to http requests are very slow,and application performance is very slow 
but  same application's publish when host on iis in windows server2012 R2 ,every thing will be good
and we have no slow performance,
any one has this problem or
any idea for this ?

**Comment by Petermarcu** [comment]
@Eilon

**Comment by Eilon** [comment]
@Elias-Heydarpour thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimal repro project that illustrates the problem? If so, please log a new issue in the https://github.com/aspnet/Home/issues repo and we can try to investigate further.
