### ISSUE TITLE
Fedora 27 Support and Fedora 25 EOL

### ISSUE THREAD

**Issue by AluminiumTech** [dotnet/core#1191]
# Issue Title

Fedora 27 Support and Fedora 25 EOL

# General

Could Fedora 27 support be added to .NET Core 2.0? Also, [Fedora 25 is now EOL](https://fedoramagazine.org/fedora-25-end-life/) and thus support for that should probably be removed.

**Comment by leecow** [comment]
https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md updated.
