### ISSUE TITLE
BuildBundlerMinifier Causes NuGet Dependencies to Break

### ISSUE THREAD

**Issue by coultonluke** [dotnet/core#1194]
# Issue

After installing the BuildBundlerMinifier v2.6.362 NuGet package as suggested in the Bundling and Minification tutorial (https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?tabs=visual-studio%2Caspnetcore2x) all other NuGet packages disappear from the list of packages, or they all appear with a yellow triangle.

Before I install the package, my project's NuGet packages contain multiple things:

![image](https://user-images.githubusercontent.com/16463338/34640940-0c70805a-f2f4-11e7-8af1-31cf80f816bb.png)

Once I have installed the NuGet package, the front end seems to 'forget' about the other NuGet packages as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/16463338/34640933-f53994da-f2f3-11e7-9df7-1bf05293a222.png)

If I go into the .csproj for my solution and remove the following line:

`<PackageReference Include="BuildBundlerMinifier" Version="2.6.362" />`

The error goes away and the list of packages in the NuGet section appear back again.

Another symptom of this problem, is that all of my views fail to resolve anything built into ASP.NET Core, like `Model` and `Section` helpers etc when the package is installed:

![image](https://user-images.githubusercontent.com/16463338/34640964-7657c780-f2f4-11e7-9d5e-b2525a20077d.png)

All of these problems are alleviated by uninstalling the package, but I would like to use on-build bundling.

# General

Windows 10
Microsoft Visual Studio Enterprise 2017 (2) - Version15.5.2
AspNetCore v2.0 website

**Comment by Petermarcu** [comment]
@Eilon

**Comment by Eilon** [comment]
@coultonluke can you post what your CSPROJ file looks like before/after adding the BuildBundlerMinifier package? At this point it's hard to tell if it's a VS issue, NuGet issue, or something else. Thanks!

**Comment by Eilon** [comment]
Pinging @madskristensen - any chance you've seen this behavior before? This seems quite odd.

**Comment by Eilon** [comment]
This issue was moved to madskristensen/BundlerMinifier#373
