### ISSUE TITLE
Installation repo signing error on OpenSUSE

### ISSUE THREAD

**Issue by liamdawson** [dotnet/core#1195]
When following the official OpenSUSE installation instructions as per https://www.microsoft.com/net/learn/get-started/linuxopensuse, the following error occurs as part of the `zypper update` step:

```
Retrieving repository 'packages-microsoft-com-prod' metadata ----------------[-]
Warning: File 'repomd.xml' from repository 'packages-microsoft-com-prod' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications
    occurred after the data were signed. Accepting data with no, wrong or
    unknown signature can lead to a corrupted system and in extreme cases even
    to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures
    the integrity of the whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not
    be trustworthy anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'packages-microsoft-com-prod' is unsigned, continue? [yes/no] (no): 
```

**Comment by Petermarcu** [comment]
We're looking into it. Thanks!

**Comment by leecow** [comment]
@liamdawson - can you include the contents of /etc/zypp/repos.d/dotnetdev.repo?

**Comment by heronsilva** [comment]
@leecow I get the same warning as @liamdawson 
The contents of my dotnetdev.repo file is:
```
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
enabled=1
autorefresh=0
baseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod
type=rpm-md
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

**Comment by liamdawson** [comment]
Mine is slightly different, but still much the same:

```
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod 
baseurl= https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

**Comment by leecow** [comment]
Thanks. I confirmed on things are working correctly on my 42.3 VM.

Just to check, you've both installed the Microsoft repo key with `sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc`?

If so, it might be good to refresh things to use the latest config info. To clean things up:

Remove cached repo data and previous dotnetdev.repo: 

- `sudo rm-rf /var/cach/zypp/raw/packages-microsoft*` 
- `sudo rm /etc/zypp/repos.d/dotnetdev.repo`

Install the updated repo definitions with 

- curl https://packages.microsoft.com/config/opensuse/42.2/prod.repo

Looks like the config file doesn't enable gpg checking by default so you'll need to add the following

- `gpgcheck=1`
- `gpgkey=https://packages.microsoft.com/keys/microsoft.asc`

Then move it into place

- sudo mv prod.repo /etc/zypp/repos.d/microsoft-prod.repo

Not strictly necessary but `sudo zypper refresh` will rebuild the repo data in `/var/cach/zypp/` before trying `update` but I usually do when performing this kind of cleanup.

**Comment by heronsilva** [comment]
Yep, I installed the Microsoft repo key.
After refreshing the repo info, I don't receive any warnings anymore. And updating to `dotnet-sdk-2.1.4` worked well.

**Comment by liamdawson** [comment]
I'm not using OpenSUSE any more, but one thing different from your setup is that I was using Tumbleweed.
