### ISSUE TITLE
How to update .net core on Mac. A preview version has been installed.

### ISSUE THREAD

**Issue by zwszwszws** [dotnet/core#1202]

**Comment by Petermarcu** [comment]
Do you want to get to a newer preview or get out of preview? What version do you want? Is this the SDK you are trying to get? @livarcocc @wli3

**Comment by zwszwszws** [comment]
I want my .net core version to be the latest version.
And get out of the old version..

**Comment by Petermarcu** [comment]
@rakeshsinghranchi @wli3 @leecow do we have pkg uninstall instructions anywhere?

@zwszwszws you should be able to just install the latest installer from https://www.microsoft.com/net/download/macos and you will have the latest.

**Comment by leecow** [comment]
There is no pkg uninstall and I don't believe we have written down what manual removal looks like.

@zwszwszws - as Peter suggests, you can just run the latest Mac installer and you'll be good to go.

**Comment by Petermarcu** [comment]
@zwszwszws does that work for you?

**Comment by Petermarcu** [comment]
Closing now as we haven't heard back in a month. Let us know if there are still open questions.

**Comment by lednhatkhanh** [comment]
![image](https://user-images.githubusercontent.com/9303093/61764104-2f67a500-ae02-11e9-96ed-158cec56d348.png)

I now have 2 folders after trying to update dotnet core 3.0 preview7, so if I keep installing newer version of dotnet core then there will be more folders until the disk is full?

**Comment by rstolpe** [comment]
> 

https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-macos

**Comment by durandt** [comment]
> > 
> 
> https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-macos

The ".NET Uninstall Tool" has not been updated to support .NET 8 so we are back to doing this manually. 

See
https://github.com/dotnet/docs/issues/39400
https://github.com/dotnet/cli-lab/issues/273
https://github.com/dotnet/cli-lab/issues/276
