### ISSUE TITLE
dotnet pack does not respect assembly atttributes

### ISSUE THREAD

**Issue by junalmeida** [dotnet/core#1203]
# Issue Title

Compiling and packing using Visual Studio 2017 or dotnet pack does not respect assembly attributes while using AssemblyInfo.cs

# General 

Using the following csproj structure: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Alma.Core</AssemblyName>
    <RootNamespace>Alma.Core</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```

When building the project, binaries are generated correctly with my attributes from .cs file, but nuget package is wrong: 

![image](https://user-images.githubusercontent.com/991675/34752832-cba0a618-f59b-11e7-8d8d-235483050534.png)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8399](https://github.com/dotnet/cli/issues/8399) via [**ZenHub**](https://www.zenhub.com/)
