### ISSUE TITLE
.NET Core 1.0.8 download page links to incorrect Windows Server Hosting exe

### ISSUE THREAD

**Issue by BJMdotNET** [dotnet/core#1204]
The page https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.8.md links to DotNetCore.1.0.7_1.1.4-WindowsHosting.exe , whereas the correct version should be DotNetCore.1.0.8_1.1.5-WindowsHosting.exe , as linked on https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.5.md .

**Comment by livarcocc** [comment]
cc @leecow

**Comment by leecow** [comment]
fixed - thanks @BJMdotNET
