### ISSUE TITLE
Flag `CreateNoWindow` does not work on linux

### ISSUE THREAD

**Issue by maroallegro** [dotnet/core#1206]
Used framework: .NET Core 2.0

Running below code on Windows opens new console window with program.dll running. When running below code on linux new console window is not opening. Seems like flag `CreateNoWindow = false` does not work.

    var process = new Process
    {

        StartInfo = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = "program.dll",
            UseShellExecute = true,
            RedirectStandardOutput = false,
            RedirectStandardError = false,
            CreateNoWindow = false
        }
    };

    process.Start();

Is it a bug?

How to open program.dll in new console window on Linux using .NET Core 2.0?

**Comment by wfurt** [comment]
How exactly do you execute this? I don't see new window when executed from simple app running in  xterm. Conceptually .NET Core does not have GUI functions - like opening window. It is possible that the windows is created by your desktop manager or something else. 

If you still think it is bug please provide full repro app and instructions how to run it.

**Comment by Petermarcu** [comment]
Isn't that what the issue is? On Windows, when you set "CreateNoWindow" to true is when you'd expect no new window. I think @maroallegro is wanting to create a new window so setting it to false. And it works that way on Windows.

**Comment by maroallegro** [comment]
@Petermarcu exactly as you said. On Windows OS when `CreateNoWindow = false` new console window is opened. On Linux OS script is executed in same window unfortunately.

**Comment by maroallegro** [comment]
@wfurt 

> How exactly do you execute this? 


On linux
`dotnet <scriptName.dll>
`

>  I don't see new window when executed from simple app running in xterm. 

And that is the problem :) Because that script opens new console window when runned on Windows System.

> If you still think it is bug

I don't know, I just see the difference how program acts on Linux and Windows. I would like to open new window functionality on both systems. On linux I managed to open new console by running new instance of xterm but it seems as workaround for me if we have flag `CreateNoWindow = false`.

@Petermarcu exactly as you said, 

> @maroallegro is wanting to create a new window so setting it to false. And it works that way on Windows.

but on linux does not.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #26337](https://github.com/dotnet/corefx/issues/26337) via [**ZenHub**](https://www.zenhub.com/)
