### ISSUE TITLE
Just-In-Time debugger does not work for .Net Core

### ISSUE THREAD

**Issue by svick** [dotnet/core#121]
When I create a .Net Core RC2 application that crashes and run it on Windows 10 with .NET Core Tooling Preview 1 for VS2015 installed, the Just-In-Time debugger window is shown, but trying to use it does not let me debug the .Net Core application.

This might be related to the fact that debugging in VS without project with Debugger Type set to Auto does not work either.

1. `dotnet new`

2. Change Program.cs to `throw new Exception();`.

3. `dotnet restore`, `dotnet run`.

4. Start JIT debugging:

 ![JIT debugger](http://imgur.com/UujbhWl.png)
5. No useful information:

 ![Unhadled exception dialog](http://imgur.com/q4cgX3O.png) ![Call Stack window](http://imgur.com/HiECZUS.png)
6. Try to set up the debugger manually:

 ![Setting up debugger](http://imgur.com/dhYNSoE.png)
7. F5
8. Works:

 ![Working debugger](http://imgur.com/WcxCV8N.png) ![Call Stack window](http://i.imgur.com/f9RUmKr.png)
9. Set Debugger Type to Auto; F5

10. Does not work again:

 ![Unhadled exception dialog](http://imgur.com/WQ2qZP2.png) ![Call Stack window](http://i.imgur.com/BW51Zjf.png)

Is this expected to work now? Can I expect it to work in the future?

**Comment by blackdwarf** [comment]
@svick does this repro with the Preview 2 tooling?

**Comment by svick** [comment]
@blackdwarf Yes, it still behaves exactly the same: Debugger Type: Auto does not seem to recognize that the application is using .Net Core.

**Comment by blackdwarf** [comment]
@svick all right, this seems like a problem. @gregg-miskelly do you know where we can file this issue to be more visible?

**Comment by gregg-miskelly** [comment]
@blackdwarf I would suggest porting this to coreclr. Fixing this would require work from both the coreclr team and the VS debugger team.

**Comment by blackdwarf** [comment]
@svick can you please move this issue to dotnet/coreclr and closing this one? Thanks!

**Comment by svick** [comment]
Added some more information, and split into https://github.com/dotnet/coreclr/issues/6380 and https://github.com/dotnet/coreclr/issues/6381.
