### ISSUE TITLE
How do Angular create templates using the I command?

### ISSUE THREAD

**Issue by laoshangwei** [dotnet/core#1210]
PS E:\Project\NiceAdmin\CoreAdmin\clientapp> ng g c User
Unable to find any apps in `.angular-cli.json`.

**Comment by Petermarcu** [comment]
This one needs to get moved to aspnet/home. I will likely make a pass a copy things over there unless the issue opener wants to move it themselves.

**Comment by Petermarcu** [comment]
@Eilon

**Comment by Eilon** [comment]
This issue was moved to aspnet/JavaScriptServices#1582
