### ISSUE TITLE
StreamWriter.WriteLine looks to be writing on LF as opposed to CRLF

### ISSUE THREAD

**Issue by diamondes3** [dotnet/core#1211]
Core 2.1.2

When using a StreamWriter and issuing a WriteLine, the output data is being appended with a LF only.  I don't know for certain, but I'm pretty sure, that is used to append CRLF.

This doesn't seem to affect anything that I have noticed, except, when opening a file in NotePad, the data is one long line.

Excel can open the file and properly figure out the columns.  NotePad++ can figure it out.  Other .net programs can figure it out.

I have a VB program that also outputs data via a StreamWriter.Writeline and it's putting out CRLF.  I understand, that Core is a different animal than VB, but I put this in here for comparison purposes.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #26336](https://github.com/dotnet/corefx/issues/26336) via [**ZenHub**](https://www.zenhub.com/)
