### ISSUE TITLE
Easy to parse feed to make automated updating chocolatey packages easier

### ISSUE THREAD

**Issue by riezebosch** [dotnet/core#1214]
To make maintaining the [chocolatey-packages](https://github.com/jberezanski/dotnetcore-chocolateypackages/) more convenient I would like a stable endpoint to check for latest version of releases with download url's.

I tried to parse to the [download page](https://www.microsoft.com/net/download/windows) and the [releases page](https://github.com/dotnet/core/releases) on github but there are to much hops to go through.

For example I also maintain the [docker-for-windows package](https://github.com/riezebosch/BoxstarterPackages/tree/master/docker-for-windows) and there I found a nice [feed](https://download.docker.com/win/stable/appcast.xml) with version number and download url that was easy to parse and thereby easy to auto update.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8386](https://github.com/dotnet/cli/issues/8386) via [**ZenHub**](https://www.zenhub.com/)
