### ISSUE TITLE
CLI didn't take proper environment 

### ISSUE THREAD

**Issue by KhaledSMQ** [dotnet/core#1215]
# Issue Title
on windows 10 32bit  .NET Core SDK 2.1.2  i am setting the env to Local 
using set ASPNETCORE_ENVIRONMENT=Local and the settings on windows environment variables for system and user both i set the key to Local but still taking Development `MyProject.Host` in my `launchSettings.json`  dotnet core must to take `MyProject.Host.Local` profile
 
launchSettings.json file
```
{
	"iisSettings": {
		"windowsAuthentication": false,
		"anonymousAuthentication": true,
		"iisExpress": {
			"applicationUrl": "http://localhost:5000/",
			"sslPort": 0
		}
	},
	"profiles": {
		"IIS Express": {
			"commandName": "IISExpress",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			}
		},
		"MyProject.Host": {
			"commandName": "Project",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			},
			"applicationUrl": "http://localhost:5000/"
		},
		"MyProject.Host.Local": {  ` <------- targeted profile  `
			"commandName": "Project",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Local"
			},
			"applicationUrl": "http://localhost:5000/"
		}
	}
}
```

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8398](https://github.com/dotnet/cli/issues/8398) via [**ZenHub**](https://www.zenhub.com/)
