### ISSUE TITLE
Debug.Assert causing an application to crash.

### ISSUE THREAD

**Issue by anpaz-msft** [dotnet/core#1216]
# Issue Title

Debug.Assert causing an application to crash.

# General

Typically, Debug.Assert should bring a pop-up with Abort, Retry, Ignore, or if the `assertuienabled` property is `false` then it should just continue, however in version 2.1.2 hitting the assert is causing the app to crash with a `FailFast` message.

For a simple console app:
```C#
using System;
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Debug.Assert(false, "Assert hit");
            Console.WriteLine("Goodbye World!");

        }
    }
}
```

You get this:
```
C:\Users\anpaz\source\repos\ConsoleApp1\ConsoleApp1>dotnet run
Hello World!
FailFast: Assert hit

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at ConsoleApp1.Program.Main(String[] args) in C:\ConsoleApp1\ConsoleApp1\Program.cs:line 11

   at System.Environment.FailFast(System.String, System.Exception)
   at ConsoleApp1.Program.Main(System.String[])
```

I'm finding this to be problematic in my xUnit tests: when I run the tests and they (purposely) hit a Debug.Assert the run pauses and eventually fails.

```
> dotnet --version
2.1.2
```

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #15857](https://github.com/dotnet/coreclr/issues/15857) via [**ZenHub**](https://www.zenhub.com/)
