### ISSUE TITLE
Cannot add audio resource to .NET Standard 2.0 project

### ISSUE THREAD

**Issue by chakrabar** [dotnet/core#1217]
I have an existing `.NET Framework` codebase, and I'm trying to port that to `.NET Core`. As part of the process, I'm converting my class libraries to `.NET Standard 2.0` project.

In one of my projects, I'm using bunch of files as project resource (`Resource.resx`). When I add other files as `Files`, such as Excel.xlsx files, they work fine and I can simply use them in my code as 

    byte[] fileData = Resources.MyFileName;

But when I'm trying to add some `Audio` (.wav) file I'm facing the problem
 1. it is always getting added as `Other`. 
 2. The project fails to compile with following error (see image below)
> System.IO.MemoryStream, netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 cannot be located.

This whole process works fine when I'm using in `.NET Framework 4.6.1` project.

Note: I've also tried installing `System.IO v4.3.0` NuGet package.

### Further technical details
Class Library: .NET Standard 2.0
Operating system: Windows 8.1 x64
IDE: Visual Studio Community 2017 v15.5.2

![netcore_resource_error](https://user-images.githubusercontent.com/8323721/34909596-62b01b70-f8ca-11e7-8457-7bf0838f1e04.png)

**Comment by Petermarcu** [comment]
@livarcocc @davkean Do you think this is SDK or project system?

**Comment by livarcocc** [comment]
@chakrabar Does a build of this project work from the command line?

**Comment by chakrabar** [comment]
@livarcocc It worked! I built the project from cli and the project built fine without any errors!

    dotnet build MyProject.csproj --no-incremental -f netstandard2.0 -r win81-x64 -v m

And strange enough, once it was built using cli, the resource appeared properly in VS as `audio` resource and it built in VS as well!!


![netcore_resource_error_solved](https://user-images.githubusercontent.com/8323721/35050576-2b089aba-fbc9-11e7-8922-1fc182087ae3.png)

**Comment by livarcocc** [comment]
@chakrabar glad it worked.

@Pilchie can you take a look? Seems to be failing only when trying to add it through VS.

**Comment by Petermarcu** [comment]
Which repo is the best to track this in?

**Comment by Pilchie** [comment]
dotnet/project-system.

**Comment by chakrabar** [comment]
@Petermarcu is this being tracked anywhere?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/project-system #3399](https://github.com/dotnet/project-system/issues/3399) via [**ZenHub**](https://www.zenhub.com/)
