### ISSUE TITLE
Cleaner file structure when publishing please

### ISSUE THREAD

**Issue by njbrown09** [dotnet/core#1226]
Can we please get a way to put everything but the binary in a folder? Its so frustrating having 50 DLLs in the same folder as the binary

**Comment by DevSidious** [comment]
I second that.

**Comment by Petermarcu** [comment]
In 2.1, I believe all the runtime/host features are there to put them wherever they want to be. The work would be in the SDK to allow for more options.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8840](https://github.com/dotnet/cli/issues/8840) via [**ZenHub**](https://www.zenhub.com/)
