### ISSUE TITLE
what is .net core?

### ISSUE THREAD

**Issue by single010203** [dotnet/core#1228]
I'm not a newer for devlep,but i really don't know what is .net  core?
give me a simple answer...
thanks

**Comment by richlander** [comment]
.NET Core is an application platform. You can use it to build apps, web sites, services, or tools. Some folks have been working on enabling games, UI apps and other types of applications with .NET Core.

It is most similar to Java and has similarities to other application platforms, too.

More info: https://docs.microsoft.com/dotnet/core/

**Comment by sid504** [comment]
simple in real world dotnet core is used for cross platform deployment

**Comment by Petermarcu** [comment]
Closing now as this is answered.
