### ISSUE TITLE
Debug Unit tests

### ISSUE THREAD

**Issue by FvdG** [dotnet/core#1229]
# Unable to debug (x)unit test(s) in a .Net Core 2.0 application

I was able te get my xunit test up and running from the console with the _dotnet xunit_ command.
The problem, i want to be able to debug my unit tests in case of a complex problem.

How can I debug my unit tests? I would love to keep using XUnit but if there are working unit test frameworks I would glady switch.

The error inside VS2017:

> Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8836](https://github.com/dotnet/cli/issues/8836) via [**ZenHub**](https://www.zenhub.com/)
