### ISSUE TITLE
dotnet.exe has stopped working saying can't load coreclr.pdb

### ISSUE THREAD

**Issue by jaydeept** [dotnet/core#1230]
This issue I have already reported [here](https://github.com/aspnet/Home/issues/2798) but just wanted to make sure it's reported at right place.

**Comment by jaydeept** [comment]
#https://github.com/aspnet/Home/issues/2798

**Comment by jaydeept** [comment]
aspnet/Home#2798

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #17016](https://github.com/dotnet/coreclr/issues/17016) via [**ZenHub**](https://www.zenhub.com/)
