### ISSUE TITLE
How long will Microsoft support .NET Core on MacOS 10.12?

### ISSUE THREAD

**Issue by meatballcoder** [dotnet/core#1231]
In light of the fact Core 2.x requires 10.12, which was released in 2015, and there are many people who use older Macs that cannot upgrade to 10.12, how long does Microsoft plan on supporting new/old MacBook/Apple Operating Systems?

I am not complaining, nor is this a veiled complaint.  I only need to know what to get to replace what I have.  I know my MBP is older.  I need to get a newer one, but the machines are costly.  If I want to develop on .NET Core 2.x and beyond, how long does Microsoft anticipate it will support a non-MS OS version?  How long on 10.12, for example?

**Comment by svick** [comment]
From [.NET Core Supported OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md):

> When an OS version reaches end-of-life as defined by the OS owner, .NET Core will also cease to provide support for that OS version. Previously released packages will remain available for customers needing access but formal support and updates of any kind will no long be provided.

I'm not sure what Apple's policy about supporting macOS 10.12 is, but Microsoft's policy about supporting .Net Core 2.0 on macOS 10.12 seems to depend on that.

**Comment by Petermarcu** [comment]
In general, I expect that we will keep working on 10.12 for longer than previous versions. We made a change to depend on Apple Crypto in 2.0 to eliminate the need for users to get keep updating OpenSSL. If it weren't for that, I think we would have supported lower versions in .NET Core 2.0. Yes, we will only officially support 10.12 as long as Apple does.
