### ISSUE TITLE
.NET Core 2.0 Authorization filter causes an internal error

### ISSUE THREAD

**Issue by mcurko** [dotnet/core#1233]
An authorization filter will cause an internal error on a .NET Core 2.0 web application. Steps to reproduce the problem are very simple: create a new .NET Core 2.0 MVC project with "no authentication", put an authorization filter on a controller method, access the corresponding URL and a "500 Internal Server Error" will be returned.

```
[Authorize]
public IActionResult Contact()
{
    ViewData["Message"] = "Your contact page.";

    return View();
}
```

A similar code in .NET Core 1.1 will correctly return the response "401 Unauthorized".

(The reason I use  a "no authentication" project is that I wrote custom authentication logic which is not shown here in order not to clutter the core of the problem.)

The stack trace is:

`    System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
       at Microsoft.AspNetCore.Authentication.AuthenticationService.<ChallengeAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()`

**Comment by embryologist** [comment]
how did you configure your auth at startup? can you show you code

**Comment by mcurko** [comment]
There is no configuration whatsoever beyond what I described. Here I have an anonymous user accessing a protected content, and he should be denied by returning "401 Unauthorized". That was the case in .NET Core 1.1, everything worked fine.

In my application, where I discovered the problem, I use custom cookie middleware for authentication.

In Startup.cs:

`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	...
	app.UseTeamAuthentication();
	...
}`

and here is the middleware, where I assign ClaimsPrincipal to context.User, which is afterwards checked in [Authorize] filters (maybe my expressions are somewhat imprecise here, but I think the idea is clear):

`public class TeamAuthentication
{
	private readonly RequestDelegate next;
	private readonly ILogger<TeamAuthentication> logger;

	public TeamAuthentication(RequestDelegate _next, ILogger<TeamAuthentication> _logger)
	{
		next = _next;
		logger = _logger;
	}

	public async Task Invoke(HttpContext context, ApplicationDbContext db)
	{
		if (TeamConfig.AuthDebug)
		{
			logger.LogDebug("Auth-Invoke: " + context.Request.Path);
		}

		const string LoginPath = "/Login";
		const string LoginPathTimeout = "/Login?timeout";
		const string LogoutPath = "/Logout";

		bool Login =
			(context.Request.Path == LoginPath ||
			context.Request.Path == LoginPathTimeout);
		bool Logout = (context.Request.Path == LogoutPath);

		string TokenContent = context.Request.Cookies["t"];

		bool DatabaseSelected = context.Items["ConnectionString"] != null;
		bool Authenticated = false;
		bool SessionTimeout = false;

		// check token
		if (!Login && !Logout && DatabaseSelected && TokenContent != null)
		{
			try
			{
				var token = await Security.CheckToken(db, logger, TokenContent, context.Response);
				if (token.Status == Models.TokenStatus.OK)
				{
					Authenticated = true;
					context.Items["UserID"] = token.UserID;
					List<Claim> userClaims = new List<Claim>();

					var person = await db.Person.AsNoTracking()
						.Where(x => x.UserID == token.UserID)
						.FirstOrDefaultAsync();

					if (person != null)
					{
						var emp = await db.Employee.AsNoTracking()
							.Where(x => x.PersonID == person.ID)
							.FirstOrDefaultAsync();
						if (emp != null)
						{
							context.Items["EmployeeID"] = emp.ID;
						}
					}

					string UserName = "";
					if (person != null && person.FullName != null)
					{
						UserName = person.FullName;
					}
					else
					{
						var user = await db.User.AsNoTracking()
							.Where(x => x.ID == token.UserID)
							.Select(x => new { x.Login }).FirstOrDefaultAsync();
						UserName = user.Login;
					}
					context.Items["UserName"] = UserName;
					userClaims.Add(new Claim(ClaimTypes.Name, UserName));

					if ((token.Roles & (int)Security.TeamRoles.TeamAdmin) == (int)Security.TeamRoles.TeamAdmin)
					{
						userClaims.Add(new Claim(ClaimTypes.Role, Security.TeamAdmin));
					}

					if ((token.Roles & (int)Security.TeamRoles.SuperAdmin) == (int)Security.TeamRoles.SuperAdmin)
					{
						userClaims.Add(new Claim(ClaimTypes.Role, Security.TeamAdmin));
						userClaims.Add(new Claim(ClaimTypes.Role, Security.SuperAdmin));
					}

					ClaimsPrincipal principal = new ClaimsPrincipal(new ClaimsIdentity(userClaims, "local"));
					context.User = principal;
				}
				else if (token.Status == Models.TokenStatus.Expired)
				{
					SessionTimeout = true;
				}
			}
			catch (System.Exception ex)
			{
				logger.LogCritical(ex.Message);
			}
		}

		if (Login || (Logout && DatabaseSelected) || Authenticated)
		{
			await next.Invoke(context);
		}
		else
		{
			if (Utility.IsAjaxRequest(context.Request))
			{
				if (TeamConfig.AuthDebug)
				{
					logger.LogDebug("Auth-Invoke => AJAX 401");
				}
				context.Response.StatusCode = 401;
				context.Response.Headers.Add(SessionTimeout ? "X-Team-Timeout" : "X-Team-Login", "1");
			}
			else
			{
				string RedirectPath = SessionTimeout ? LoginPathTimeout : LoginPath;
				if (TeamConfig.AuthDebug)
				{
					logger.LogDebug("Auth-Invoke => " + RedirectPath);
				}
				context.Response.Redirect(RedirectPath);
			}
		}
	}`

I tried to find some help on the subject [on stackechange](https://stackoverflow.com/questions/48073548/custom-cookie-authentication-not-working-after-migration-from-asp-net-core-1-1-m) but noone seems to have a clue on what's the problem.

**Comment by Eilon** [comment]
I'm pretty sure that the Authorize attribute is designed to work with the rest of ASP.NET Core's security/auth system. It might be possible to use it in other ways, but that is probably outside of the scope of supported scenarios. If you still have issues with this, please log a new issue at https://github.com/aspnet/Security/issues
