### ISSUE TITLE
App service in Azure stops responding - libuv reports EOF error

### ISSUE THREAD

**Issue by cgenin7** [dotnet/core#1235]
# Issue Title

App service in Azure stops responding - libuv reports EOF error

# General

I have app services built using dotnet core 2.0 and visual studio 2017 and running on azure. Sometimes they stop responding with the following error in the logs:

2018-01-21 20:53:34.893 +00:00 [Error] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv: ListenerPrimary.ReadCallback
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4095 EOF end of file
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.PipeReadContext.ReadCallback(UvStreamHandle dispatchPipe, Int32 status)

During that time no other transaction is logged, so there is no traffic in the app service at that time.
A restart of the app service fixes the error.

**Comment by hoeflerm** [comment]
@cgenin7 did you achieve anything regarding this topic?
Ran into the same issue with dotnet core 2.0 and visual studio 2017, just like you.

Would be very helpful :)

**Comment by cgenin7** [comment]
Unfortunately no. I submitted the error to the Azure team and they asked for a memory dump. I will provide one if the problem reappears but it did not occur again yet.

**Comment by hoeflerm** [comment]
Thank you for your answer, your post solved the issue for the moment

**Comment by cgenin7** [comment]
You can try moving your app services to local cache, if nothing is stored locally with your application. They seem to have issues moving the app services around when this mode is not enabled: 
                https://docs.microsoft.com/en-us/azure/app-service/app-service-local-cache

**Comment by hoeflerm** [comment]
Thank you for your answer, it solved the issue for the moment.
I will try :+1:

**Comment by Petermarcu** [comment]
@Eilon @muratg

**Comment by Eilon** [comment]
@halter73 @davidfowl @jkotalik - any ideas on this? Kestrel issue? Libuv? Other?

**Comment by leecow** [comment]
Closing as it looks like the conversation was continued with the Azure folks.

**Comment by mahisanka** [comment]
@cgenin7 have you resolved this error ?

**Comment by cgenin7** [comment]
There are still occasionnally problems when Azure is moving app services. We fixed this issue by having two occurrences of each app service.
