### ISSUE TITLE
Error - The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/core#1236]
Hi All I am facing issue "The specified CGI application encountered an error and the server terminated the process." after hosting it on Azure Web Sites. On Local it works fine. I have developed application on asp.net core 1.0 and deployed on Azure.

Is there any timeout issue or any thing missing when deployed code on azure ?
Please help me out regarding this issue.

**Comment by Petermarcu** [comment]
@muratg @DamianEdwards @Eilon any pointers on where to start?

**Comment by Eilon** [comment]
@muratg any ideas? Or any idea where to get more logs to dig into this?

**Comment by muratg** [comment]
Dup of: https://github.com/aspnet/KestrelHttpServer/issues/2269
