### ISSUE TITLE
WCF WebOperationContext Replacement?

### ISSUE THREAD

**Issue by jsbarkan** [dotnet/core#1237]
What should we use in .NET Core since the "WebOperationContext" (found in .NET Framework, from System.ServiceModel.Web) is no longer available?

The purpose is to modify the response header being returned from a WCF service method.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/wcf #2686](https://github.com/dotnet/wcf/issues/2686) via [**ZenHub**](https://www.zenhub.com/)
