### ISSUE TITLE
Two Lambda functions created

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#1238]
Two C# lambda functions created

When I publish, I see that two Lambda functions have been created. One is xxx-RootPathFuction-yyyy and the other is xxx-ProxyFunction-yyy

The root path one is attached to / in the API Gateway and the proxy one connected to a proxy resource.

Is this always going to be the case or have I done something odd in my application?

**Comment by Petermarcu** [comment]
This sounds more like a question for AWS Lambdas. https://github.com/aws/aws-lambda-dotnet

**Comment by Petermarcu** [comment]
I moved this issue here: https://github.com/aws/aws-lambda-dotnet/issues/248
