### ISSUE TITLE
Url length

### ISSUE THREAD

**Issue by rajurh** [dotnet/core#1239]
Is there a way to set a maxUrlLength configuration value in Asp.Net Core? I see how this is done in web.config in earlier versions of the framework.

I am trying to incorporate the url encryption due to which its exceeding 260 charc and in that case it give bad request for url length greater than 260.

Help on this will be much appreciated.

**Comment by Petermarcu** [comment]
@DamianEdwards @muratg

**Comment by h3smith** [comment]
If you are thinking about encrypting URL parameters, don’t. This is a bad security approach and you shouldn’t do it.

**Comment by muratg** [comment]
@rajurh I agree with @h3smith, there are probably better ways to do what you want.  That being said, I think the answer somewhat depends on your setup. Kestrel/HttpSysServer?  Behind IIS/nginx or as an edge server? Azure?

cc @halter73 @Tratcher

**Comment by rajurh** [comment]
@halter73 If you don't want me to encrypt the url what do you suggest I don't want the url to be tampered like for e.g. xyz.com?requestid=121. If its plain any one can change the id's in the browser.

What is your thoughts on the above scenario if you think the above approach is not good?

**Comment by muratg** [comment]
@rajurh And what's the problem with people changing the ID in the browser?

**Comment by h3smith** [comment]
People guessing URL parameters should be mitigated by 1) enduring that the user can access the resource defined in the URL parameter 2) never use primary keys as identifiers you send to the world, use guid / random values.

**Comment by halter73** [comment]
:+1: about it being a bad idea to encrypt URL parameters. Others have already suggested alternative for that.

If there is some other reason you want to increase Kestrel's allowed URL length, you can do so via [KestrelServerLimits.MaxRequestLineSize](https://github.com/aspnet/KestrelHttpServer/blob/d996f6b7fcc805b749a6dfaf3c3dd88dff691f85/src/Kestrel.Core/KestrelServerLimits.cs#L92).

As the MaxRequestLineSize doc comments point out, Kestrel already allows URLs approaching 8KB, so I doubt you're actually running into that limit. You're probably running into a limit enforced by either a proxy (e.g. IIS, nginx) or the client/browser.

**Comment by Petermarcu** [comment]
@rajurh did you get everything you need from the responses? Can we close this issue?

**Comment by rajurh** [comment]
Yes please goahead
