### ISSUE TITLE
Get the .NET Core version number at runtime

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet/core#1242]
Is there a reliable way to get the **.NET Core version number** at runtime that works on **Nano Server** and **Ubuntu** **Docker** containers as well, please?
I've seen some hacks deriving it from folder structure that breaks when the app is deployed onto Nano Server and Ubuntu Docker container images.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28132](https://github.com/dotnet/corefx/issues/28132) via [**ZenHub**](https://www.zenhub.com/)
