### ISSUE TITLE
'Microsoft.AspNet.WebApi.C|ient 5.2.2‘ was restored using '.NE|'Framework.Version=v4.6.1' instead of the project target framework '.NE|'Standard,Version=v2.0'

### ISSUE THREAD

**Issue by steevcoco** [dotnet/core#1243]
In a new Visual Studio Azure Function App project --- version 2 --- the imported Nuget package restores an incompatible version of Microsoft.AspNet.WebApi.Client:

Package 'Microsoft.AspNet.WebApi.C|ient 5.2.2‘ was restored using '.NE|'Framework.Version=v4.6.1' instead of the project target framework '.NE|'Standard,Version=v2.0'. This package may not be fully compatible with your project.

Microsoft.NET.Sdk.Functions (1.0.7)
    -> Microsoft.Azure.WebJobs.Extensions.Http (3.0.0-beta4)
        -> Microsoft.AspNetCore.Mvc.WebApiCompatShim (2.0.1)
            -> Microsoft.AspNet.WebApi.Client (5.2.2)

![image](https://user-images.githubusercontent.com/22354363/35491819-f869ff5c-0476-11e8-89d1-bbadb4d4435d.png)

The Function App project is created as NetStandard 2.0, and it's not clear why the dependencies don't restore that way ... I checked in the Microsoft.AspNetCore.Mvc.WebApiCompatShim nuget nuspec file, and there is a targetFramework=".NETStandard2.0" dependency in it ... Although there is also a newer version of Microsoft.AspNetCore.Mvc.WebApiCompatShim.

I have quit and done two NuGet Restores from the cli, and also deleted the dotnet sdk fallback folder:

C:\Program Files\dotnet\sdk\NuGetFallbackFolder

... Which was a cause of another restore failure (you could see #1181) ... But still the project doesn't restore without warnings.

**Comment by JontyMC** [comment]
I got this error too. Went back to Microsoft.NET.Sdk.Functions (1.0.6) fixed it. Still get the warning, but at least the code runs.

**Comment by teamboyd** [comment]
I have this same issue but no resolution.  Thanks Microsoft.

**Comment by myyandar** [comment]
What does this mean and how can it be resolved properly?

**Package 'Microsoft.AspNet.Mvc 5.2.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0'. This package may not be fully compatible with your project.**
