### ISSUE TITLE
Can a .net core rc2 class library project access app.config settings?

### ISSUE THREAD

**Issue by gitmaheshk** [dotnet/core#125]
Is it possible to read app settings defined in the app.config in a .net core 1.0 class library project? In the asp.net core web project the settings/custom sections are read correctly from the config however they are not accessible when referred from a test class library project. 

Prior to the upgrade and in a rc1 class library proj the app.config sections were being read however that is not the case after the upgrade.

Is this a bug or should we be using the full .net framework regular class library project to use app.config?

**Comment by blackdwarf** [comment]
@gitmaheshk can you please share your project.json and overall project setup? I would like to understand a little bit better what are you trying to accomplish.

**Comment by gitmaheshk** [comment]
@blackdwarf thanks for reaching out. For time constraints and my inability to address the issue I have since converted the test project to a regular class library project. As I seek to learn, I have created a sample test project. All I am trying to do here is create a .net core test class library project using xunit targeting the full framework and read an app setting key from the app.config.  I understand the preferred way is to use strongly typed configuration via appsettings.json however my actual solution has references to several custom built class libraries on the older fwk(4.0) which are referenced as nuget packages and these libraries need the app.config. The app.config file has app settings, connection strings and other custom configuration settings (msdn.microsoft.com/en-us/library/2tw134k3.aspx). 
--
{
   "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "Microsoft.Extensions.Configuration": "1.0.0"
  },
    "frameworks": {
      "net461": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "1.0.1"
        },
        "frameworkAssemblies": {
          "System.Configuration": "4.0.0.0",
          "System.Data.Entity": "4.0.0.0"
        }
      }
      }    
    }

**Comment by gitmaheshk** [comment]
@blackdwarf thanks for reaching out. For time constraints and my inability to address the issue I have since converted the test project to a regular class library project. As I seek to learn, I have created a sample test project. All I am trying to do here is create a .net core test class library project using xunit targeting the full framework and read an app setting key from the app.config.  I understand the preferred way is to use strongly typed configuration via appsettings.json however my actual solution has references to several custom built class libraries on the older fwk(4.0) which are referenced as nuget packages and these libraries need the app.config. The app.config file has app settings, connection strings and other custom configuration settings (msdn.microsoft.com/en-us/library/2tw134k3.aspx). 

Please let me know if you need additional information, below is the project.json appended. 
*--
{
   "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "Microsoft.Extensions.Configuration": "1.0.0"
  },
    "frameworks": {
      "net461": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "1.0.1"
        },
        "frameworkAssemblies": {
          "System.Configuration": "4.0.0.0",
          "System.Data.Entity": "4.0.0.0"
        }
      }
      }    
    }

**Comment by akuzhan** [comment]
Have you found solution yet?

**Comment by Petermarcu** [comment]
Thanks for the input. We're actively working on adding back many of the configuration API's to .NET Core. That work is being tracked here: https://github.com/dotnet/corefx/issues/13481
