### ISSUE TITLE
Multi-target of class library to netstandard1.6/.NET 4.6.1

### ISSUE THREAD

**Issue by TerraVenil** [dotnet/core#1251]
I have class library with `<TargetFrameworks>net461;netstandard1.6;</TargetFrameworks>.`. One of the reference contains dependencies to .NET 461/.NET 462 which loaded from NuGet packages.

- microsoft.win32.registry\4.0.0\lib\net46\Microsoft.Win32.Registry.dll
- system.reflection.typeextensions\4.1.0\lib\net462\System.Reflection.TypeExtensions.dll

When I build library in oputput folder net461 all previously mentioned dll's were absent. Then I create NuGet package based on that library and when consuming it in runtime get `System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`.

I am glad to modify `.nuspec` file with additional sections
`<file src="microsoft.win32.registry" target="lib/net461" />
<file src="system.reflection.typeextensions" target="lib/net461" />` and I expected to have those dependencies on .NET 461 in bin folder that I was able to copy them inside NuGet package.

How should I create my own NuGet package if runtime dependencies were absent in bin folder?

**Comment by Petermarcu** [comment]
@weshaggard any thoughts? @TerraVenil is this still a problem for you?

**Comment by TerraVenil** [comment]
After migration to netstandard2.0 issue dissapeared.
