### ISSUE TITLE
dotnet core install via official script not working

### ISSUE THREAD

**Issue by noelmcgrath** [dotnet/core#1255]
Browse to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
Download script https://dot.net/v1/dotnet-install.ps1 
Run script

Expected:
Would download zip and install .net core sdk

Actual:
Getting 404

Other info:
Get one of the urls and paste into browser
Get the following:

<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:ea148153-001e-00df-075c-9cf99f000000 Time:2018-02-02T19:28:52.4221024Z
</Message>
</Error>

**Comment by Petermarcu** [comment]
Wondering if this was some temporary glitch. The script seems to be there for me now.

**Comment by noelmcgrath** [comment]
the script is there, thats not the problem. Its the urls in the script that give back 404

**Comment by noelmcgrath** [comment]
Also was trying to run with -Version stable.
Changed to run with no parameters just to check if that worked.
It tries to download Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.5/dotnet-sdk-1.1.5-win-x64.zip
Current SDK is v2.1.4 I believe

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8651](https://github.com/dotnet/cli/issues/8651) via [**ZenHub**](https://www.zenhub.com/)
