### ISSUE TITLE
Give UpDownBase.upDownButtons a less restrictive accessibility level

### ISSUE THREAD

**Issue by jmeberlein** [dotnet/core#1256]
I recently had to extend the functionality of NumericUpDown to replace the string "0" with a domain-specific string. (This seemed preferable to using DomainUpDown, because the numeric values were still the important part, and this was only for display) But because UpDownBase.upDownButtons is internal, the only way to implement GetPreferredSize() was to include a magic number to account for the width of the control.

Changing the field to have a less restrictive access modifier would allow developers to create their own types of spin boxes, in addition to extending the behavior of the two existing types.

**Comment by Petermarcu** [comment]
I don't believe UpDownBase is in .NET Core.

**Comment by Petermarcu** [comment]
I'm going to close this issue here because its not related to .NET Core. You can open it here: https://github.com/microsoft/dotnet/issues if you'd like.
