### ISSUE TITLE
System.DirectoryServices is not supported on Ubuntu 14.04

### ISSUE THREAD

**Issue by coolrz** [dotnet/core#1258]
# Issue Title
System.DirectoryServices is not supported on Ubuntu 14.04

# General
I use the .net core 2.0 to get domain user group information and it works well in IIS.  I installed theSystem.DirectoryServices 4.5.0-preview2-26202-05 via Nuget in the project. But when i use the same code deploy on ubuntu 14.04, it throws exception "System.DirectoryServices is not supported on this platform." Is that possible to work well in Ubuntu ? if not  any third part LDAP library provide and can work well in Ubuntu? The purpose is to get the domain user information and the hosted Ubuntu server is joined the company domain network. 

asp.net core code see below
UserController.cs

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.DirectoryServices;
using System.Net.Http;
using System.Security.Principal;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace IsupportESOApi
{
    [Route("api/[controller]")]
    public class UserController : Controller
    {
        IList<string> groups = new List<string>();
        // GET: api/user/steven.rui.zhang
        [HttpGet("{eid}")]
        public IActionResult Get(string eid)
        {
            try
            {
                DirectorySearcher ds = new DirectorySearcher();
                ds.Filter = String.Format("(&(objectClass=user)(sAMAccountName={0}))", eid);
                SearchResult sr = ds.FindOne();

                DirectoryEntry user = sr.GetDirectoryEntry();
                user.RefreshCache(new string[] { "tokenGroups" });

                for (int i = 0; i < user.Properties["tokenGroups"].Count; i++)
                {
                    SecurityIdentifier sid = new SecurityIdentifier((byte[])user.Properties["tokenGroups"][i], 0);
                    try
                    {
                        NTAccount nt = (NTAccount)sid.Translate(typeof(NTAccount));
                        //result.Add(nt.Value.ToLower());
                        groups.Add(nt.Value);
                    }
                    catch (Exception ex)
                    {
                        continue;
                    }
                }
            }
            catch (Exception ex)
            {
                return new ObjectResult(ex.Message);
            }

            return new ObjectResult(groups);
        }

        
    }
}

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #27308](https://github.com/dotnet/corefx/issues/27308) via [**ZenHub**](https://www.zenhub.com/)
