### ISSUE TITLE
logger. logInformation() parameter index issue

### ISSUE THREAD

**Issue by emailtowalter** [dotnet/core#126]
Hi... logger.log...() fundtion behaves strangely. 

logger.loginformation("{1} test {0}", "a", "b"); 

I would expect the result to be "b test a", but the result is "a test b". It happens to all log functions. 

Is it right?

**Comment by svick** [comment]
I'm assuming you're talking about ASP.NET Core Logging.

In that case, I believe this behavior is correct. The format string is not standard .Net format string (which is used e.g. in `string.Format` or `Console.WriteLine`). It's a custom string format, where you're supposed to name the values you're logging. For example:

```c#
logger.LogInformation("{a} test {a}", "a", "b");
```

So, what your code does is to confusingly name the first logged value `1` and the second `0`.

**Comment by emailtowalter** [comment]
thanks. Just tested, and it still does not work 

    string a = "a";
    string b = "b";
    logger.LogCritical("{b} like {a}", a, b);

result: a like b

thought?

**Comment by svick** [comment]
Naming the values is not for reordering, it's for recording the names in advanced loggers.

**Comment by mairaw** [comment]
Maybe this could explained here: https://docs.asp.net/en/latest/fundamentals/logging.html
@danroth27?

**Comment by danroth27** [comment]
I believe it already is explained:

> The call to the log method can utilize a format string with named placeholders (like {path}). These placeholders are populated in the order in which they appear by the args values passed into the method call. Some logging providers will store these names along with their mapped values in a dictionary that can later be queried. In the example below, the request path is passed in as a named placeholder:

**Comment by mairaw** [comment]
Thanks @danroth27. Had trouble reading on my phone this morning. So, the function is behaving as expected and the behavior is documented. I think this issue can be closed then, @emailtowalter.

**Comment by emailtowalter** [comment]
Thanks for the help. I will close this one.
