### ISSUE TITLE
Does RHEL 6 covered under Microsoft Supported OS versiosn

### ISSUE THREAD

**Issue by AmeetShinde** [dotnet/core#1260]
It looks like .Net Core has added support for RHEL 6 since v2.0.3, does this also mean RHEL 6 is also covered under Microsoft supported OS version and will there be active support available for this OS version?

**Comment by AmeetShinde** [comment]
Thanks for the confirmation. Requesting to comment on couple of items below 
1.  are there any considerations for self contained application support on RHEL 6
2. .Net Core SDK availability for building solutions on RHEL6

**Comment by Petermarcu** [comment]
@livarcocc can you speak to a RHEL.6 option for the SDK?

Self-contained applications should work just fine. You have to publish one specifically for rhel.6 like:

`dotnet publish -r rhel.6-x64 --self-contained`

**Comment by livarcocc** [comment]
We currently have the change available for our 2.1.300 release, that will match the .NET Core 2.1 release.

**Comment by AmeetShinde** [comment]
Also couple of queries on this support
1. Will the same binaries published for RHEL.6 work for CentOS.6 as well
2. I am assuming the binaries published for rhel.6 would work for any rhel 6.x version, is this correct assumption.

**Comment by Petermarcu** [comment]
1. Yes, 
2. We are testing on RHEL 6.9. 

There are also special instructions you have to follow to get the prereqs on RHEL 6. https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

**Comment by Petermarcu** [comment]
Ok, I'm going to close this now as I think the question is answered. We will support this in .NET Core 2.1.
