### ISSUE TITLE
Troubles to set up internal NuGet server for .NET Core development/publishing

### ISSUE THREAD

**Issue by lextm** [dotnet/core#1261]
A company can block internet access for its internal development machines. In such cases, an internal NuGet server would be required to host the necessary packages, so as to enable .NET Core development and publishing.

I built a detailed example and documented it in [my blog post](https://blog.lextudio.com/offline-publishing-asp-net-core-apps-cf22f45158af), which shows how troublesome the experience is today, when attempting to publish the default ASP.NET Core MVC project. 

To summarize,

* The default NuGet source setting specifies nuget.org, which if blocked leads to an error. This error can only be resolved by adding a custom nuget.config file, which is not pleasant.
* `dotnet publish -r win-x64` would generate errors on missing packages, which is good, but there is no easy way to extract a list of NuGet packages (with version numbers) out and download them. Ideally, such can be done by a PowerShell script, but no sample anyway.
* The `Detected package downgrade` error message can be misleading, while the fix is to explicitly set `<RuntimeFrameworkVersion>`.

Hope there can be official guides from Microsoft to show how such internal NuGet server should be set up (especially which packages are mandatory). That can save tons of hours for those companies to explore on their own.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8650](https://github.com/dotnet/cli/issues/8650) via [**ZenHub**](https://www.zenhub.com/)
