### ISSUE TITLE
Question: Type / TypeInfo 2.0

### ISSUE THREAD

**Issue by lucasphi** [dotnet/core#1263]
Hello,

Could anyone explain to me what happened to the Type and TypeInfo classes? I mean, in .net core 1.1 I had to use TypeInfo to access information like "IsPrimitive" etc. TypeInfo now inherits from Type instead of MemberInfo. I have been searching for this all morning and could not find an answer.

Did they change the way Type and TypeInfo works? Is it still faster to use Type then TypeInfo or did they change it back to the .Net Framework ways?

Thanks,

Lucas

**Comment by svick** [comment]
The best documentation about this I could find is in [this document](https://github.com/terrajobst/platform-compat/blob/0f89defe564209545ba0f56cfe5ec13095e2f177/docs/DE0008.md) (from https://github.com/dotnet/platform-compat/pull/46). Basically, `TypeInfo` now exists only for backwards compatibility, all new code should use `Type`.
