### ISSUE TITLE
.Net Standard 2.0 library with custom output and intermediate files path?

### ISSUE THREAD

**Issue by rraallvv** [dotnet/core#1265]
In a .Net Standard 2.0 library project, what's the correct way to specify custom paths for the output and intermediate files directly?

I tried the configuration below which is working fine for previos versions of the .Net Standard library.

Please notice that those paths are relative to the project, I just copied the same path that were working before upgrading to .Net Standard 2.0, besides anything I put from the IDE settings window is converted to relative paths when saved to .csproj file.

![screenshot](https://i.stack.imgur.com/5YAzQ.png)

```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnableDefaultEmbeddedResourceItems Condition=" '$(EnableDefaultEmbeddedResourceItems)' == '' ">false</EnableDefaultEmbeddedResourceItems>
    <ProjectName Condition=" '$(ProjectName)' == '' ">MyLibrary</ProjectName>
    <SolutionOutputPath Condition=" '$(SolutionOutputPath)' == '' ">..\..\..\..\..\..\tmp\com.company.myapp</SolutionOutputPath>
    <BaseIntermediateOutputPath>..\..\..\..\..\..\tmp\com.company.myapp\MyLibrary\obj\Debug</BaseIntermediateOutputPath>
</PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>false</Optimize>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <OutputPath>$(SolutionOutputPath)\$(ProjectName)\bin\$(Configuration)</OutputPath>
    <BaseOutputPath>$(SolutionOutputPath)\$(ProjectName)\bin\$(Configuration)</BaseOutputPath>
    <IntermediateOutputPath>$(SolutionOutputPath)\$(ProjectName)\obj\$(Configuration)</IntermediateOutputPath>
    <BaseIntermediateOutputPath>$(SolutionOutputPath)\$(ProjectName)\obj\$(Configuration)</BaseIntermediateOutputPath>
</PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType></DebugType>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <OutputPath>$(SolutionOutputPath)\$(ProjectName)\bin\$(Configuration)</OutputPath>
    <BaseOutputPath>$(SolutionOutputPath)\$(ProjectName)\bin\$(Configuration)</BaseOutputPath>
    <IntermediateOutputPath>$(SolutionOutputPath)\$(ProjectName)\obj\$(Configuration)</IntermediateOutputPath>
    <BaseIntermediateOutputPath>$(SolutionOutputPath)\$(ProjectName)\obj\$(Configuration)</BaseIntermediateOutputPath>
</PropertyGroup>
```

**Comment by imacks** [comment]
Did you write ```<Project SDK="...>```? The problem is SDK target imports are after Base* Path, so it won't work. See [my scaffold script](http://www.github.com/buildcenter/DotNetBuild) for what I mean.

**Comment by rraallvv** [comment]
@imacks I tried removing the `SDK` attribute in the tag `Project` and importing the target manually after the `PropertyGroup` that specifies the custom paths. I din't work though, maybe because I'm in Visual Studio for Mac. What I eded up doing was adding the custom paths to the file Directory.Build.props for the .Net Standard Library project. Thanks.
