### ISSUE TITLE
Segmentation fault on dotnet [name-of-app].dll on Debian

### ISSUE THREAD

**Issue by ChristianHaase** [dotnet/core#1266]
Getting segmentation fault when running the application. Only on HTTP client request sending to external API. The app start fine and I can navigate fine, but whenever I try to login _(calling external API)_, I'm getting the segfault. Same goes for creating a new user, when calling the external API from my MVC backend.

Running the app locally, everything works as expected, and I can login fine, as well as creating a new user.

I have a try/catch around the enitre method, but I'm never hitting the catch. The segfault happens instead of the catch.

# Technical details
dotnet --info

    .NET Command Line Tools (1.0.4)
    
    Product Information
      Version: 1.0.4
      Commit SHA-1 hash: afefd

    Runtime Environment
      OS Name: debian
      OS Version: 9
      OS Platform: Linux
      RID: debian.8-x64
      Base Path: /opt/dotnet/sdk/1..4

Is there any fancy way for me te debug, or get some kind of log about what's happenening?

**Comment by Petermarcu** [comment]
@leecow is Debian 9 supported by 1.0?

**Comment by leecow** [comment]
No, Debian 9 is 2.0. https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md.

**Comment by ChristianHaase** [comment]
I suppose that would explain some issues, but the application runs fine on the server. It's only remote HTTP request that causes the segfault?

**Comment by wfurt** [comment]
What version of curl and openssl do you have? This may be same as #24891 and #24552
You can try container with supported OS. That should get you around linkage problems.

**Comment by ChristianHaase** [comment]
@wfurt 

OpenSSL version:
`OpenSSL 1.10f 25 May 2017`

curl version:
`curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3`

I don't know what issues you are referring to (#24891 and #24552)?

**Comment by wfurt** [comment]
oh, the link did not work ;( 
https://github.com/dotnet/corefx/issues/24552 and https://github.com/dotnet/corefx/issues/24891

**Comment by ChristianHaase** [comment]
I'm trying to convert my project to .NET core 2.0, and updating the installed version on my server. I will update my progress here once done. Thanks for the inputs.

**Comment by ChristianHaase** [comment]
I updated the project to 2.0, but it's still a problem. I'll take a look at the links you provided @wfurt

**Comment by ChristianHaase** [comment]
I looked at the installed version of libcurl, and this is what I could find: 
![libcurl](https://user-images.githubusercontent.com/7237574/36634093-b2b8545c-199f-11e8-93b9-1b161627d681.PNG)

Anything I can do here?

**Comment by Petermarcu** [comment]
I'm going to move this to the corefx repo where it will be tracked better.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #27951](https://github.com/dotnet/corefx/issues/27951) via [**ZenHub**](https://www.zenhub.com/)
