### ISSUE TITLE
DateTime.TryParse produces different results in different environments

### ISSUE THREAD

**Issue by Doff3n** [dotnet/core#1267]
# DateTime.TryParse produces different results in different environments

# General
I am trying to parse a date, with DateTime.TryParse and with a provided Norwegian culture and no DatetimeStyles:
``` csharp
var result: DateTime.TryParse("29.01", new CultureInfo("nb-NO", false), DateTimeStyles.None, out var parsedDateTime)
``` 

I am purposely sending in "29.01" and expecting the result to parse to a default Datetime: "29.01.2018",
I also expect that 29.01.18 and 29.01.2018 parses to the correct dates. 

In norway the date format is dd.MM.YYYY HH:mm
Code:
https://github.com/Doff3n/HelloDate

Commands:
- dotnet build
- dotnet run

Running this on my PC:
- dotnet run
parsedDateTime: 29.01.2018 00:00:00
result: True

Running this on the VM:
- dotnet run
parsedDateTime: 01.01.0001 00.00.00
result: False

.Net core sdk version: 2.1.4, runtime: 2.0.5

In desperation I have also tried setting Date and Time formats in Windows, but I would have expected the property UseUserOverride: false to not allow user settings.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #27306](https://github.com/dotnet/corefx/issues/27306) via [**ZenHub**](https://www.zenhub.com/)
