### ISSUE TITLE
Missing creation of StringComparer for other languages

### ISSUE THREAD

**Issue by jtsoftware** [dotnet/core#127]
I'm trying to retarget a portable C# library for .Net core 1.0.

I used to do something like this to get a string comparer for a different language, once I obtained a CultureInfo object for the language (via a delegate set by the caller):
IComparer<T> comparer = (IComparer<T>)StringComparer.Create(cultureInfo, caseInsensitive);

.Net Core currently seems to only support it for the current culture via properties like StringComparer.CurrentCulture.

Is there a way to get a string comparer for a given language or culture?

This is important for an app that uses multiple languages simultaneously, such as an app for language-learning.

**Comment by svick** [comment]
If you want to propose adding new API to .Net Core, I believe you should follow [the API Review Process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) by posting this to [the corefx repo](https://github.com/dotnet/corefx).
