### ISSUE TITLE
Unmanaged DLLs of a nuget package show up in the root .csproj in vs2017 Solution Explorer

### ISSUE THREAD

**Issue by leblancdavid** [dotnet/core#1270]
We have a nuget package which consumes unmanaged dlls that need to be copied to the output directory. That seems to work fine. However when adding a reference to the package for a .csproj in Visual Studio 2017, the dlls show up in the root directory of the .csproj in the Solution Explorer. I can't seem to find a way to hide those, I'm not sure if it's an issue with our nuget package or vs2017. Has anyone experienced this or know what could cause that?

**Comment by cdrnet** [comment]
Yes, I'm seeing this as well.

In my case, this is related to an ItemGroup along the lines of the following being added through a `.targets` file, for example as in the `MathNet.Numerics.MKL.Win` NuGet package:

```
<ItemGroup>
  <None Include="..">
    <Link ../>
    <CopyToOutputDirectory../>
  </None>
</ItemGroup>
```

Such `<None>` items used to be hidden in earlier VisualStudio versions, now it seems they always show up. Should such libraries be packaged differently now?

**Comment by Petermarcu** [comment]
@Pilchie do you know which repo this should be tracked in?

**Comment by Pilchie** [comment]
`dotnet/project-system` is probably the right repo.

@cdrnet can you try adding a `<Visible>False</Visible>` metadata to your `<None Include`?

Also, are these packages being referenced from SDK style projects, or regular ones? If regular, using packages.config or `<PackageReference>` (or project.json)?

**Comment by dsplaisted** [comment]
This was intentional, I think.  I don’t have the details immediately available but I can probably find them.

Sent from my Windows 10 phone

**Comment by cdrnet** [comment]
In my case, with VS 15.6.0 Preview 5.0:

- C#/F#, SDK style, with PackageReference: files _**do**_ show up
- C#, regular, with PackageReference: files _**do not**_ show up
- F#, regular, with packages.config: files _**do not**_ show up

**Comment by cdrnet** [comment]
If I add `<Visible>False</Visible>`, then the files no longer show up, but their folders all still visible (in my case the files are structured in an x64 and an x86 folder, using `%(RecursiveDir)` in the link). So it does not really help much to remove the noise.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/project-system #3302](https://github.com/dotnet/project-system/issues/3302) via [**ZenHub**](https://www.zenhub.com/)
