### ISSUE TITLE
.Net Core 2.0 Nuget packages not being restored on build server

### ISSUE THREAD

**Issue by philultfin** [dotnet/core#1271]
**.Net Core 2.0 Nuget packages not being restored on build server**

**Local Machine:** Windows 7, Visual Studio 2017 Professional 15.5.6, dotnet core 2.1.4
**Build Server:**  Windows Server 2012 R2, msbuild 15.5.180.51428, dotnet core 2.1.4, nuget 4.5.1.4879

Solution with 20+ dotnet core projects and one third-party developed project on framework 4.5.2. The solution compiles fine locally, but fails on build server. Various errors on nuget packages e.g. 

Running msbuild /t:rebuild gives (truncated but lots more)
Startup.cs(3,32): error CS0234: The type or namespace name 'Builder' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?) 
Startup.cs(5,32): error CS0234: The type or namespace name 'Configuration' does not exist in the namespace 'Microsoft.Extensions' (are you missing an assembly reference?) 
also
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Microsoft.Common.CrossTargeting.targets(141,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 

Looked at  issue  #1006 and that helped, but still getting nuget failures, running combinations of nuget restore, dotnet build, msbuild etc, gives different errors each time, but all nuget related. 

I've tried clearing caches etc. multiple times, basically trying to find root cause. other core 2.1.4 solutions all build fine and all are the same mix of web, web api and class libraries. I found Visual Studio Community edition on the build server so updated it to latest version and built the solution with that. It built successfully, but still fails at command line. 

If I run Get-package in the console manager I only see the packages for the framework 4.5.2 project from a packages.config file, I see no projectreferences and the UI has the yellow warning on each one. If I do the same on the local machine, I see all the packages including the projectreferences listed (I also waited for package console to initialise before loading solution as that was a reported issue). 

I compared the caches on the local and build server, there is a projectreference to \microsoft.aspnetcore.mvc 2.0.2, it is on the local machine (along with 2.0.0), but is not in the cache on the build server, it only has 2.0.0. I can't understand how it can build in VS community edition without that package in cache unless VS has another cache it accesses (assume C:\Program Files\dotnet\sdk\NuGetFallbackFolder). My next attempt will be to manually copy missing packages to the cache from local to build server, while this might allow builds to work, if the cache is cleared, the situation will occur again. Any ideas on how to resolve this would be appreciated. I'm thinking the VS Community Edition shouldn't be on the server and may be causing an issue with build tools and will uninstall it, but I'd guess they should work side-by-side.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8649](https://github.com/dotnet/cli/issues/8649) via [**ZenHub**](https://www.zenhub.com/)
