### ISSUE TITLE
String.IndexOf behaviour differs from .NET Standard, but only on Linux

### ISSUE THREAD

**Issue by bachowny** [dotnet/core#1273]
# String.IndexOf behaviour differs from .NET Standard, but only on Linux

```
using System;

namespace Bug
{
  public class Program
  {
    static void Main(string[] args)
    {
      string lSOH1 = Convert.ToChar((byte)1).ToString();
      Console.WriteLine(lSOH1);
      var lLine1 = string.Format("123{0}", lSOH1);
      Console.WriteLine(lLine1);
      Console.WriteLine(lLine1.IndexOf(lSOH1)); // Should print "3"
    }
  }
}
```

If I build and run this code in Visual Studio 2017 on Windows 7 the output of the last line is, as expected, "3". However if I run the built code on Centos 7 with dotnet core 2 (rh-dotnet20-2.0-6.el7), the output is "0". Running the same code under mono works fine. Building the code using dotnet itself on Centos makes no difference to the behaviour.

**Comment by benaadams** [comment]
I think its by design https://github.com/dotnet/corefx/issues/26293, try using Ordinal `lLine1.IndexOf(lSOH1, StringComparison.Ordinal)` instead

**Comment by bachowny** [comment]
Thanks for that, that has fixed my problem. I don't understand how "sorting" has anything to do with the places where characters are in an array of characters (a string), but OK! :-)
