### ISSUE TITLE
Running "dotnet store" command fails with "MSB3026: Could not copy" errors  

### ISSUE THREAD

**Issue by scottmendel** [dotnet/core#1274]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by scottmendel** [comment]
Apologies, I submitted this accidentally while trying to fill in the details. I will try and reopen with details.

**Comment by scottmendel** [comment]
I ran the following command: dotnet.exe store --skip-optimization -m "C:\Panorama\hedzup\mn\bin\InstallNetCore.manifest" -o "C:\Program Files\dotnet\store"

I received the following error: C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ComposeStore.targets(351,5): warning MSB3026: Could not copy "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.antiforgery\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Antiforgery.dll" to "C:\Program Files\dotnet\store\x64\netcoreapp2.0\\microsoft.aspnetcore.antiforgery\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Antiforgery.dll". 

The assembly in question was in fact "in use" but I expect this is a problem that needs to be addressed. The Microsoft.AspNetCore.Antiforgery dll in the NuGetFallBackFolder I suspect is "Any CPU", at least the "Optional" PE header marks it with magic 0x10B. The same assembly in the store has a optional header with magic 0x20B which makes it an x64 version of the same assembly. The version of the assembly is the same in both cases 2.0.0.17205, so I am wondering why the copy is even attempted. because this is the "x64" area of the store, replacing the "x64 version of the assembly with the "Any CPU" version, this seems like it is undoing an optimization made previously.

I am attempting to add something to the store, but not this assembly. Microsoft.AspNetCore.Antiforgery is a dependency of another assembly that is the main target of the store command which is Riverbed.AppInternals.DotNetCore.dll. But the store command will not complete. I do understand that stopping the dotnet applications using the antiforgery dll will work around the problem, but we have a requirement to do a "hot" install on a production server where it is not desirable to stop services that are running.

If I remove the --skip-optimazation flag, I run into the reverse scenario; assemblies can be "in use" trying to place optimized version of the assemblies into the store area. 

Conceptually, I would like the store command to add only the dependencies that are missing, and not get hung up on things that already may be in the store and possibly in use. 

Environment Details:

.NET Command Line Tools (2.1.2)
Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\
Microsoft .NET Core Shared Framework Host
  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #3712](https://github.com/dotnet/core-setup/issues/3712) via [**ZenHub**](https://www.zenhub.com/)
