### ISSUE TITLE
OpenSUSE Leap 42.2 reached EOL

### ISSUE THREAD

**Issue by savornicesei** [dotnet/core#1275]
Hi all,

Similar to #1191 and as described in the [official OpenSUSE docs](https://en.opensuse.org/Lifetime), the only supported OpenSUSE Leap version right now is 42.3 (it is expected to be maintained until January next year).

OpenSUSE Leap 42.2 reached EOL in january 26, this year.

Best,
Simo

**Comment by leecow** [comment]
Supported OS documents updated. Still work to do to get the core-setup repo builds updated.
