### ISSUE TITLE
Getting error "Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'"

### ISSUE THREAD

**Issue by xs2bharat** [dotnet/core#1276]
# Issue Title

Getting error "Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'"

# General

I am using .net core 2.0 framework to design asp.net web api and using Microsoft.Windows.Compatibility pack to port few internally designed library

**Comment by BetsyOstrander** [comment]
I am getting this too.  No error until I added a .net standard lib for accessing Active Directory, which includes the Windows Compatibility pack.

**Comment by CarlosOnline** [comment]
Any status on a fix?

**Comment by joshfree** [comment]
Hi Folks,
I've moved this issue to the dotnet/corefx repo where the Windows Compatibility Pack lives.

The new issue is https://github.com/dotnet/corefx/issues/31276
