### ISSUE TITLE
dotnet core 2.1.4 bug with large dictionaries of <string, double?>.  "Aborted, core dumped"

### ISSUE THREAD

**Issue by errantmind** [dotnet/core#1277]
### Description
On Ubuntu 16.04 LTS, in a 'command line' app, creating a large dictionary of type <string, double?> crashes the application but creating the same dictionary a type of <string, double> does not.  This bug only affects Linux and does not appear when running the same code on Windows.

In our app we have an unrolled loop (not relevant to this bug to my knowledge) where we add 16504 entries of <"some unique key",null> to the dictionary.  This causes the program to crash with an error of "Aborted, core dumped". When we change the dictionary to additions to do <"some unique key", double.MinValue> it works just fine.  Here is a sample of the failing code and successful code : 

### Failure Case
var dict =  new Dictionary<string, double?>(); 
dict.Add("JAN_SUN_1|00:00:00", null);
dict.Add("JAN_SUN_1|00:30:00", null);
dict.Add("JAN_SUN_1|01:00:00", null);
dict.Add("JAN_SUN_1|01:30:00", null);
dict.Add("JAN_SUN_1|02:00:00", null);
dict.Add("JAN_SUN_1|02:30:00", null);
dict.Add("JAN_SUN_1|03:00:00", null);
dict.Add("JAN_SUN_1|03:30:00", null);
dict.Add("JAN_SUN_1|04:00:00", null);
dict.Add("JAN_SUN_1|04:30:00", null);
dict.Add("JAN_SUN_1|05:00:00", null);
... 16504 times
return dict;

### Success Case
var dict =  new Dictionary<string, double>(); 
var minValue = double.MinValue;
dict.Add("JAN_SUN_1|00:00:00", minValue);
dict.Add("JAN_SUN_1|00:30:00", minValue);
dict.Add("JAN_SUN_1|01:00:00", minValue);
dict.Add("JAN_SUN_1|01:30:00", minValue);
dict.Add("JAN_SUN_1|02:00:00", minValue);
dict.Add("JAN_SUN_1|02:30:00", minValue);
dict.Add("JAN_SUN_1|03:00:00", minValue);
dict.Add("JAN_SUN_1|03:30:00", minValue);
dict.Add("JAN_SUN_1|04:00:00", minValue);
dict.Add("JAN_SUN_1|04:30:00", minValue);
dict.Add("JAN_SUN_1|05:00:00", minValue);
... 16504 times
return dict;

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #16510](https://github.com/dotnet/coreclr/issues/16510) via [**ZenHub**](https://www.zenhub.com/)
