### ISSUE TITLE
WPF support on the another platform

### ISSUE THREAD

**Issue by UltWolf** [dotnet/core#1279]
Hello, i have a question.
Do you create wpf on the dotnet core platform or no, and  if you doing that, can  you say when this part of framework have been done.
Thx u,
With best regards, Vitaliy

**Comment by svick** [comment]
As far as I know, Microsoft has no plans to bring WPF (or any similar UI framework) to .Net Core.

That means that if you want a XAML-based cross-platform UI framework for .Net Core, you will have to rely on third-party projects, like [Avalonia](http://avaloniaui.net/).

**Comment by UltWolf** [comment]
Thx you for answer

**Comment by svick** [comment]
One thing that I forgot: Xamarin.Forms [does have plans](https://blog.xamarin.com/glimpse-future-xamarin-forms-3-0/) to work on Linux and macOS, though it's not quite the same as a UI framework like WPF
