### ISSUE TITLE
Visual Studio 2015 Professional - missing class icon on WinForms project

### ISSUE THREAD

**Issue by jabolx** [dotnet/core#128]
Hello,

I have a very strange issue with .NET Core 1.0.0 RC2-VS2015Tools.Preview version. Every time I install it in Visual Studio 2015 Professional and I want to do something inside a WinForms project all the partial classes icons in Solution Explorer are gone (the ones you see after expanding a Form in Solution Explorer). This way I can't anymore access the code under the form - the only way is to use View Code option on a form or use F7 which is pretty annoying as I'm used to just clicking on it.

The weird this that even after I uninstall .NET Core the issue still stays and I can only get rid of it after uninstalling and installing again whole Visual Studio. I was thinking that it might be some other reason, but it's clearly happening after installing .NET Core.

Best regards.

**Comment by blackdwarf** [comment]
@jabolx this is weird. Is this reproing with the RTM bits you can get from https://dot.net/core?

**Comment by jabolx** [comment]
Hello,

Yes I tried both with VS2015 Update 2 and Update 3. Also have all the required Redistributables for Visual C++. More details about my issue you can find under link to VS forums. One of the users also reproduced it.

[https://social.msdn.microsoft.com/Forums/vstudio/en-US/88310535-5013-4304-bd2b-c58b54d5d678/visual-studio-2012-is-missing-a-winforms-partial-class-in-solution-explorer?forum=visualstudiogeneral#b5ab628a-60bf-4727-bef0-2a0111d22d5c](url)

[https://social.msdn.microsoft.com/Forums/vstudio/en-US/20cd09c5-705f-4324-8009-2af974ffd8cb/problem-with-missing-winforms-form-class-file-in-solution-explorer?forum=visualstudiogeneral#20cd09c5-705f-4324-8009-2af974ffd8cb](url)

Best regards.

**Comment by blackdwarf** [comment]
@jabolx ok, so it seems this is a problem. Can you file this issue on https://github.com/aspnet/tooling/issues so that proper people can look and triage it? Thanks! I will close this one.
