### ISSUE TITLE
Adding new *.cs file while having the property EnableDefaultCompileItems on false

### ISSUE THREAD

**Issue by edsonaf** [dotnet/core#1280]
# Creating new *.cs file while having the property EnableDefaultCompileItems on false does not automatically add this file in the project file

# General

- This is on Visual Studio 2017 Version 15.5.57
- Using the new SDK project format style
- Has `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>`
- Has external files included using the `<Compile Include="" />` way
- Project was ported from the old .net framework project style to the new style as this project is now a netstandard2.0 project.

I can actually fix this issue very easily by just removing the <EnableDefaultCompileItems>false</EnableDefaultCompileItems> and removing the two files that are already included with the `<Compile Include="" />` 

However some solutions that we have, have cs files that are compiled with a Prebuild target. To use them while building, they needed  to be explicitly added in the project file and therefor the EnableDefaultCompileItems property was also used.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/project-system #3307](https://github.com/dotnet/project-system/issues/3307) via [**ZenHub**](https://www.zenhub.com/)
