### ISSUE TITLE
System.AppContext.GetData is in netstandard1.6 but not net462

### ISSUE THREAD

**Issue by nothrow** [dotnet/core#1281]
# Issue Title

Some .NET Standard calls are not implemented as expected in .NET Framework

# General

https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.getdata?view=netstandard-1.6#System_AppContext_GetData_System_String_

Here, it says that AppContext.GetData is supported in NetStandard 1.6, 2.0, but .NET Framework 4.7.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

this one says, that .NET 461 is fully supporting .NET Standard 2.0.

I have application, that is compiled as .NET Standard library, and then is expected to be called from some kind of service host, that is either net462, or netcoreapp (based on platform it is running on). However, some of the libraries (Microsoft.Extensions.DependencyModel) for netstandard uses this call.

**Comment by svick** [comment]
This is expected. .Net Framework 4.6.1 behaves as if it supported .Net Standard 2.0 and it does support the vast majority of it, but not everything. Specifically, it does not support APIs that were added in .Net Standard 1.5 and 1.6.

For more details, see [.NET Framework 4.6.1 supporting .NET Standard 2.0](https://github.com/dotnet/standard/tree/master/docs/netstandard-20#net-framework-461-supporting-net-standard-20).

As for your specific case, Microsoft.Extensions.DependencyModel 2.0.4 has versions for .Net Framework 4.5.1, .Net Standard 1.3 and .Net Standard 1.6. How exactly are you distributing your application/library? Maybe there's a way to use the .Net Framework 4.5.1 version of Microsoft.Extensions.DependencyModel from your .Net Framework 4.6.2 host?

**Comment by nothrow** [comment]
Thanks for the link, I missed this specific document. 

> Considering the number of APIs that .NET Framework 4.6.1 will not support is low and that these are all brand-new APIs with low adoption we believe this is a much better trade-off.

This is kind of unfortunate, since the brand new API is used by ASP.NET Core, so eventually anyone wanting to combine netstandard + full framework with web will probably hit the wall here.

I had troubles with 4.5.1 version, so I ended up with shipping my own forked version of DependencyModel. 

Just a suggestion, there is bunch of #if DOTNETCORE s  in `Microsoft.Extensions.DependencyModel`. Wouldn't it make sense to have libraries with #ifs in `runtime/`, so the correct one will be resolved, based on framework at run-time, not at compile-time?

**Comment by svick** [comment]
> eventually anyone wanting to combine netstandard + full framework with web will probably hit the wall here

I don't think so, that's what the .Net Framework 4.5.1 version is for. I think you're in a special situation, where you're distributing a single DLL to multiple frameworks, so that doesn't help. But most people will be fine.

> Wouldn't it make sense to have libraries with #ifs in `runtime/`, so the correct one will be resolved, based on framework at run-time, not at compile-time?

I don't know. You might consider creating a new issue about that in the repo where that code lives: [dotnet/core-setup](https://github.com/dotnet/core-setup).

**Comment by Petermarcu** [comment]
@terrajobst , sounds like this one is just unfortunately hitting the small set of API's that fell through the cracks. Anything actionable here? Should we move this to the standard repo or close?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/standard #684](https://github.com/dotnet/standard/issues/684) via [**ZenHub**](https://www.zenhub.com/)
