### ISSUE TITLE
Display issue for Euro currency

### ISSUE THREAD

**Issue by dpjain** [dotnet/core#1283]
In our application, we have used English and French language. We need to use Euro currency for French language and "," is used as separator for Euro currency. But have no idea how to display the same format. The numeric text box only accepts the decimal values, not accepting the comma. And also the property are set as Currency data type. 

ConfigureServices: 
services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new[]
                {
                    new CultureInfo("en-GB"),
                    new CultureInfo("fr-FR") { NumberFormat = { CurrencyDecimalSeparator = "," }, DateTimeFormat = new CultureInfo("en-GB").DateTimeFormat }
                };
                options.DefaultRequestCulture = new RequestCulture(culture: new CultureInfo("en-GB"), uiCulture: new CultureInfo("en-GB"));
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });

Configure:
 var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
            app.UseRequestLocalization(locOptions.Value);

**Comment by leecow** [comment]
Issue moved to [dotnet/corefx #27565](https://github.com/dotnet/corefx/issues/27565) via [**ZenHub**](https://www.zenhub.com/)
