### ISSUE TITLE
Page needs clarity for people brand-new to .NET Core

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#13]
Listing the issues here on a per-section basis.

## Get Started

What is .NET Core? link leads to another landing page, not something that tells me what .NET Core is.

## .NET Core Platform

Text here references BCL - a newcomer to .NET probably doesn't understand the acronym (I didn't until I looked it up online)

## License

This section describes multiple licenses, so the plural form should probably be used here.

## Understand the relationship between .NET Core and the .NET Framework.

- The whole first paragraph needs to be rewritten.  After re-reading it a few times, I'm still not sure about what it's telling me.  Is .NET Core a part of .NET Framework?  Does .NET Framework call into .NET Core?  Describing their relationship as a subset-superset is confusing.
- The last sentence isn't really helpful.  I'm already assuming Microsoft is improving these components.

## Learning about ASP.NET and .NET Core

"ASP.NET is the new cross-platform version of ASP.NET" is confusing.  I understand that one is a link to the "new" ASP.NET, but referring to two different things with the same name is confusing.

**Comment by jameswalkoski** [comment]
Related:
The **.NET Core Contributor Info** links on this page are broken: https://github.com/dotnet/corefx/wiki
Project priorities: https://github.com/dotnet/coreclr/blob/master/Documentation/project-priorities.md
Contribution guidelines: https://github.com/dotnet/corefx/blob/master/Documentation/contributing.md

**Comment by Petermarcu** [comment]
@cartermp, I took a stab at making these updates. The only one I could find better wording for was the relationship between .NET Core and .NET Framework. I'll keep thinking about how to explain that better.

**Comment by cartermp** [comment]
(It's interesting reading this now that I'm no longer new to the team/project)

@BethMassi 's [blog post about understanding .NET](http://blogs.msdn.com/b/bethmassi/archive/2015/02/25/understanding-net-2015.aspx) was very helpful to me in terms of understanding what things looked like for the last release.  Perhaps a similar sort of diagram would suit this section well?

**Comment by nteague22** [comment]
I know personally that the teams on some sub projects to the dotnet oss push have strong pythonic backgrounds, and the new direction seems to emulate a lot of aspects of the pyenv philosophy. Perhaps that would be a good angle to reference/allude to

**Comment by blackdwarf** [comment]
@cartermp can we close this one? Or move it to dotnet/core-docs?

**Comment by cartermp** [comment]
Let's go ahead and close it for now, since we have docs on this.

**Comment by blackdwarf** [comment]
I will close this one as we have the docs.
