### ISSUE TITLE
does dotnet core support server-side wcf?

### ISSUE THREAD

**Issue by vincentshow** [dotnet/core#130]
i want to build a cross-platfom app that contains wcf services which can be found and referenced by others using dotnet core, but i just found there was only a client-oriented wcf repo https://github.com/dotnet/wcf. can i add server-side wcf in dotnet core? and is there any example or tutorial show how to do this?  any suggection will be appreciate

**Comment by vincentshow** [comment]
i dont know which repo is suitable for getting help between dotnet/wcf and dotnet/core, so i create this issue both here and wcf #https://github.com/dotnet/wcf/issues/1310

**Comment by zhenlan** [comment]
Hi @vincentshow, [dotnet/wcf](https://github.com/dotnet/wcf) is the right repo for any questions regarding WCF. As you have been aware of, WCF is only supported for the client side currently on .NET Core. The only way to build a WCF service is by using WCF in full .NET Framework at this point. 

However, we are very interested to understand your scenarios where WCF server side is required on .NET Core for you. Lots of discussions have happened on dotnet/WCF#1200. Do you mind to share more of your details there too?

**Comment by vincentshow** [comment]
thanks a lot, i've put my story in #https://github.com/dotnet/wcf/issues/1200

**Comment by zhenlan** [comment]
Thanks for the feedback @vincentshow. I am closing this issue now.

**Comment by gosukonda-gopala** [comment]
Hi I am new to .net core I want to consume a wcf service without adding service reference in .net core project... can someone help me on how to consume. .net core version I am using is 1.1.

also can someone help me is it possible to add a nugget package developed in 4.5.1 in a .net core 1.1 project?

**Comment by zhenlan** [comment]
@gosukonda-gopala you don't need to use "add service reference". You can just write WCF client code like you normally did for full .NET Framework. Below is one of tests as an example. Please feel free to check out other tests too.
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs
