### ISSUE TITLE
For other CPU Arch support.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/core#1309]
Is any plan for support other arch cpu? e.g. mips64el,ppc ...

**Comment by kasper3** [comment]
You can vote up this issue https://github.com/dotnet/coreclr/issues/969. I asked the mips-linux channel over at IRC for someone familiar with assembly instructions to help providing bit for MIPS based on https://github.com/dotnet/coreclr/tree/master/src/vm, but couldn't find volunteers.

mono/java/node.js/go/ruby/lua/python and other runtimes work on mips...

**Comment by Petermarcu** [comment]
The linked issue is the best way to track this. We are supportive of .NET Core being used on more CPU's and architectures and encourage the community to help us do that. I'm going to close this issue here and conversations can continue at dotnet/coreclr#969
