### ISSUE TITLE
Install Instructions for .NET Core Runtime 2.1.0-preview1 on Linux Ubuntu 16.04

### ISSUE THREAD

**Issue by billpratt** [dotnet/core#1310]
Environment: Ubuntu 16.04 using WSL

Following the instructions here to install 2.1.0-preview1 on Ubuntu 16.04 gives me an error when running apt update: https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-2.1.0-preview1

```
# apt update
E: Type 'deb[arch' is not known on line 1 in source list /etc/apt/sources.list.d/dotnetdev.list
E: The list of sources could not be read.
```

This line in the instructions should be changed from
```
sudo sh -c 'echo "deb[arch = amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
```

to 

```
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
```

which adds a space beteween ```deb``` and ```[arch``` and removes the spacing between ```arch = amd64```

Doing this fixed apt and allowed me to install.

**Comment by leecow** [comment]
Thanks @billpratt - Fixed and changes should be live soon. Noticed similar errors in a few other deb feed definitions.
