### ISSUE TITLE
netstandard2.0 library, dependent on Microsoft.Win32.Registry, doesn't work from net471 when loaded via MEF

### ISSUE THREAD

**Issue by jherby2k** [dotnet/core#1311]
# Issue Title

I'm building a .net standard 2.0 library that uses MEF to load extensions. The MEF parts are also .net standard 2.0.

Everything works fine when called from netcore2.0 test project. But if i have the test project also target net471, calls to Microsoft.Win32.Registry from the MEF part fail (Registry.LocalMachine returns null). I assume this is because Microsoft.Win32.Registry has a net461-specific library that isn't present.

I see this problem doesn't exist if, instead of using MEF, i just directly depend on the part. I imagine MEF prevents the framework-specific dependencies from flowing through correctly. Any suggestions?

# General

You can repro this by cloning https://github.com/jherby2k/AudioWorks.git then changing the AudioWorks.Api.Tests projects to also target net471. Tests using the AudioWorks.Extensions.Apple extension will fail because it can't read the registry.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/standard #683](https://github.com/dotnet/standard/issues/683) via [**ZenHub**](https://www.zenhub.com/)
