### ISSUE TITLE
.NET Core returned  a Adar A in a non-leap year

### ISSUE THREAD

**Issue by MosheL** [dotnet/core#1314]
# Issue Title

Adar (אדר) month name on the .net core is displayed as a Adar A (אדר א')

# General

Example code:

		static System.Globalization.HebrewCalendar hc = new System.Globalization.HebrewCalendar();
		static System.Globalization.CultureInfo jewishCulture = 
                System.Globalization.CultureInfo.CreateSpecificCulture("he-IL");

		static public string toHebrewString(DateTime dDate)
		{
			var s= dDate.ToString("dd בMMMM y", jewishCulture);
			return s;
		}
...

           toHebrewString(new DateTime(2018,2,28) // י"ג באדר א' תשע"ח

28/2/2018 is  in Adar( י"ג באדר), not in  Adar A (י"ג באדר א'), as  תשע"ח  is not a leap year.

On Windows  10 machine the correct month (אדר) is displayed.

**Comment by leecow** [comment]
Issue moved to [dotnet/corefx #27564](https://github.com/dotnet/corefx/issues/27564) via [**ZenHub**](https://www.zenhub.com/)
