### ISSUE TITLE
.Net Core 2.1 P1 - Can't website from fresh Angular web template: '@angular-devkit/core'

### ISSUE THREAD

**Issue by WereDev** [dotnet/core#1315]
# Issue Title

Can't website from fresh Angular web template: Error with `@angular-devkit/core`

# General

Trying to start the website after creating a fresh project using the Angular web template nets me `Error: Cannot find module '@angular-devkit/core'.`

Adding `@angular-devkit/core` as a devDependency in package.json seems to fix the issue.

**Comment by Petermarcu** [comment]
@Eilon @muratg @DamianEdwards

**Comment by Eilon** [comment]
This issue was moved to aspnet/JavaScriptServices#1578
