### ISSUE TITLE
Restart .NetCore 2.0 app

### ISSUE THREAD

**Issue by jasieg** [dotnet/core#1316]
I'm using IApplicationLifetime to stop my application, however it doesn't contain method for restart. How can it be achieved? I played a bit with CancellationToken, but on linux all it does is stop application.

**Comment by embryologist** [comment]
Does this help?
https://stackoverflow.com/questions/36121999/how-to-restart-asp-net-core-app-programmatically

**Comment by jasieg** [comment]
That's what I meant by playing with CancellationToken. It works on Windows, but not on Linux.

**Comment by Petermarcu** [comment]
@Eilon @muratg @DamianEdwards

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1353
