### ISSUE TITLE
dotnet restore and run do not work reliable

### ISSUE THREAD

**Issue by ecwan** [dotnet/core#1320]
General
```dotnet --version```
1.1.5
running on Windows 7 

steps to reproduce it on my system:

```cd myproject```

```dotnet restore```

 ...
  Restore completed in 20,87 sec for C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj.

-> everything looks fine

```dotnet run sample1```

CSC : error CS0006: Metadata file 'C:\myproject\Workflow.Awl\bin\Debug\netstandard1.3\Workflow.Awl.dll' could not be found [C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj]

The build failed. Please fix the build errors and run again.

```dotnet restore```

  Restore completed in 31,33 ms for C:\myproject\Workflow.Awl\Workflow.Awl.csproj.
  Restore completed in 42,67 ms for C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj.

```dotnet run sample1```

The application to execute does not exist: 'C:\myproject\AWLReaderAndProcessor\bin\Debug\netcoreapp1.1\AWLReaderAndProcessor.dll'

```dotnet run sample1```

-> now does it work

Question: Why do I have to repeat the restore and run commands until it works?

My expectation: Every command like restore and run should already work the first time or give a clear indication about the current status.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8746](https://github.com/dotnet/cli/issues/8746) via [**ZenHub**](https://www.zenhub.com/)
