### ISSUE TITLE
.net core issue, System.BadImageFormatException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

### ISSUE THREAD

**Issue by bnlakshmibn** [dotnet/core#1322]
# .Net core issue with some System reference libraries

Hi,
I am trying to create a .net core Web api. I had added my logic there. But while trying to run that, I am getting the exception as Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

This kind of exception is happening with many "System."  assemblies.

**Comment by seriouz** [comment]
Yeah you cannot use dotnet core for WinForms!
You have to user FullFramework.

**Comment by Petermarcu** [comment]
Looks like you need to figure out what is bringing in the System.Windows.Forms dependency. What is your TargetFramework? What are the other System assemblies?

**Comment by joshfree** [comment]
Closing this old issue.  Feel free to re-open this with more information.

**Comment by lindexi** [comment]
I start up my application that throw BadImageFormatException

System.BadImageFormatException: 未能加载文件或程序集“System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”或它的某一个依赖项。该模块应包含一个程序集清单。
文件名:“System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”

**Comment by patillaxmi123** [comment]
i am also facing the same issue when i try to call the .net core 3.0 api to windows workflow foundation.
getting following issue.
BadImageFormatException: Could not load file or assembly 'System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (0x80131058)
Microservices.Controllers.WWFController.Get(int age) in WWFController.cs, line 31

Please help on this

**Comment by ChahatKumar** [comment]
@seriouz  Hey , i am trying to use winforms for .net Core console app.
Is there any documentation for the same that it is not possible  for .NET CORE

The same referencing and code works smooth on .NET FRAMEWORK

**Comment by seriouz** [comment]
@ChahatKumar  Try it with dotnet 5.

**Comment by ChahatKumar** [comment]
> @ChahatKumar Try it with dotnet 5.

Thanks ! I tried using this but I find that a dotnet 5 console app cannot produce both the form and console window ?right?

**Comment by seriouz** [comment]
No i don't think you can run a console app as WinForms app. Why do you need a console app in the first place?

**Comment by ChahatKumar** [comment]
I basically have a libarary written as a console app  which I plan to release. 
But for collection of user data I need a contest frok the user for the same for which I was planning to add a form.

Altho this is possible in a. . Net Framework console app, but I am unsure since a similar procedure didn't work for. NET CORE

My whole library is written in. NET CORE

**Comment by seriouz** [comment]
Try this in your csproj. It should keep the console window open of a winforms app.

```xml
<PropertyGroup>
  <OutputType>Exe</OutputType>
</PropertyGroup>
```

**Comment by ChahatKumar** [comment]
Hi , it did works .. Thanks !
But now giving an error that a dll is not connected ..

Just wanted to cofirm one thing -> for dll's like System.Windows.Forms -> i referenced them using my internal program files where they are present and added path in .csproj

If i add through COM  reference , it gives error and doesn't load  ( in case of .net Core app)

I wasnt able to find document for winforms in .NET CORE solving my issue 
Am i referencing them the right way ?

Thannks and apologies for the out of topic doubt

**Comment by seriouz** [comment]
Yes, reference the Packages in your .csproj. Dlls you have to reference like this:

```xml
<ItemGroup>
  <Reference Include="YourAssembly">
    <HintPath>Path/To/YourAssembly.dll</HintPath>
  </Reference>
</ItemGroup>
```

**Comment by ChahatKumar** [comment]
Thanks a lot 👍
