### ISSUE TITLE
Broken libcurl dependency on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by bwalkenhorst** [dotnet/core#1327]
# Broken libcurl dependency on openSUSE Tumbleweed

Trying to install dotnet core on openSUSE Tumbleweed, following the instructions found here, I get the following error message:
```
[20:06|root@schwarzgeraet:~]# zypper in dotnet-sdk-2.0.0
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libcurl needed by dotnet-runtime-2.0.0-2.0.0-1.x86_64
 Solution 1: do not install dotnet-sdk-2.0.0-2.0.0-1.x86_64
 Solution 2: break dotnet-runtime-2.0.0-2.0.0-1.x86_64 by ignoring some of its dependencies
```

When I ask the package manager about it, I get the following reply:
```
[20:06|root@schwarzgeraet:~]# zypper se libcurl
Loading repository data...
Reading installed packages...

S  | Name                | Summary                                | Type   
---+---------------------+----------------------------------------+--------
   | libcurl-devel       | A Tool for Transferring Data from URLs | package
   | libcurl-devel-32bit | A Tool for Transferring Data from URLs | package
i+ | libcurl4            | Version 4 of cURL shared library       | package
i  | libcurl4-32bit      | Version 4 of cURL shared library       | package
```

So there is a libcurl, it is just called libcurl4. I am not certain who I should blame here. But I hope that updating the dependencies on dotnet will be less work than getting the openSUSE developers to rename the package.

**Comment by omajid** [comment]
Related to https://github.com/dotnet/core-setup/issues/3791

**Comment by bwalkenhorst** [comment]
FWIW: I tried `Solution 2: break dotnet-runtime-2.0.0-2.0.0-1.x86_64 by ignoring some of its dependencies`

I wasn't all that surprised, but it seems to have worked. MonoDevelop still isn't convinced .Net Core 2.0 is actually installed, but when I try to build and run a simple Hello-World project from the command line, it works

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #27936](https://github.com/dotnet/corefx/issues/27936) via [**ZenHub**](https://www.zenhub.com/)
