### ISSUE TITLE
SDK 2.1.100 installed after updating VS 2017 15.6.1

### ISSUE THREAD

**Issue by Vaiune** [dotnet/core#1329]
I've updated visual studio 2017 to 15.6.1 this morning.
After that i got 
```
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Prior to update I had 2.1.4 and everything was fine. 
```dotnet new react``` scaffolds the old template that doesn't use create-react-app as it should.
If I create a global.json file indicating SDK 2.1.4 then it scaffolds the correct template with CRA.

https://www.microsoft.com/net/download/Windows/build shows 2.1.4 as the latest version.

Is this supposed to happen with the update VS 2017 15.6.1?

**Comment by Kritner** [comment]
Ok, so not just me!

I see that I do in fact have 2.1.4 in my sdks folder, but even at root, with no global.json config, `dotnet --version` shows 2.1.100.

I unfortunately cannot confirm that it said 2.1.4 prior to the VS update.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8757](https://github.com/dotnet/cli/issues/8757) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mattsonnhalter** [comment]
I am having this issue as well. I can confirm that right before the update of Visual Studio to 15.6.1 I was getting 2.1.4 from dotnet --version command as expected and now am getting version 2.1.100 as others have mentioned.
