### ISSUE TITLE
VS 2015 not installing dependencies - rc2 - Windows 7

### ISSUE THREAD

**Issue by MarkPieszak** [dotnet/core#133]
Running a project the node_modules folder is showing things are installed (I even did an `npm i` as well), but VS thinks they aren't installed.

![image](https://cloud.githubusercontent.com/assets/2574412/16243885/5d4d889a-37c7-11e6-96c2-34de53b04bb8.png)

Also when running the project, it throws internal server errors for the same reason (saying things aren't installed)

![image](https://cloud.githubusercontent.com/assets/2574412/16243896/711b1a90-37c7-11e6-93c9-c5d27c4c8a9e.png)

Is this a Windows 7 issue, or potentially something I set up wrong when going from rc1 to rc2?

**Comment by neyromant** [comment]
I have the same problem on Win7 x64, VS 2015. There was after an upgrade to RC2

**Comment by MarkPieszak** [comment]
Oh really, yeah strangely it's actually making the whole project not able to run (throws that error that the package isn't installed). Very bizarre, doesn't happen on MAC of course.

**Comment by Petermarcu** [comment]
@barrytang , This looks like an issue with the VS bits. Those issues are tracked internal to Microsoft. @barrytang can you let folks know if this is still an issue in newer builds and when it may be addressed?

**Comment by MarkPieszak** [comment]
I'm currently on holiday, but I believe it might of been a rc2 issue, unable to try if it works with the RTM (I'm guessing it's fixed in that one)

**Comment by blackdwarf** [comment]
@MarkPieszak is there any update on this?

**Comment by neyromant** [comment]
@blackdwarf , I upgraded to the RTM , but the problem has not disappeared . It does not interfere with the work , but the label and warning icon confused me.

**Comment by MarkPieszak** [comment]
I'm still experiencing this with RTM as well, but read something today that potentially this might be linked with using `nvm` or some type of node version manager. I'm going to try removing the nvm and uninstalling/reinstalling node, and giving it another shot. I'll get back to you in the morning! @blackdwarf 

In my case it won't let the project run since dotnet thinks the packages aren't installed (yet they are in node_modules)

**Comment by blackdwarf** [comment]
@MarkPieszak if it is still reproing, can you please move this issue to https://github.com/aspnet/tooling/issues and close this one? That repo is a much better home for it. Thanks!

**Comment by MarkPieszak** [comment]
Not a problem! I'll update today if it fixes the issue as well. Thanks again Zlatko.
