### ISSUE TITLE
.Net core publish output is ugly

### ISSUE THREAD

**Issue by HolyOne** [dotnet/core#1330]
Hello,
I have built a website using .net core razor pages. 
My problem is when I publish the website there are hundreds of dll files.
Most often, what I am trying to find is appconfig / webconfig or main Application file

I think you should package rest of them in a bin folder or something because it looks like all compiled files are dumped in the publish root folder and this is annoying on publishing situations

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8764](https://github.com/dotnet/cli/issues/8764) via [**ZenHub**](https://www.zenhub.com/)
