### ISSUE TITLE
.NET Core 2.1 download link is broken

### ISSUE THREAD

**Issue by iantalarico** [dotnet/core#1334]
Go to [download archive](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) and click on [download](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.1-preview1-download.md) for .NET Core 2.1 (2.0.1-Preview1 with SDK 2.0.1-Preview1).  Following the link gives a 404.

**Comment by Petermarcu** [comment]
@leecow I updated the links and text to all say 2.1.0 instead of 2.0.1. Go ahead and check my work but I merged. :)

**Comment by leecow** [comment]
LGTM! cc @preetikr
