### ISSUE TITLE
422 in HttpStatusCode

### ISSUE THREAD

**Issue by incompletude** [dotnet/core#1335]
Why `HttpStatusCode` does not contain the 422 status?

**Comment by svick** [comment]
In .Net Core 2.1, `HttpStatusCode` will contain 422, see https://github.com/dotnet/corefx/issues/4382 and [the source code](https://github.com/dotnet/corefx/blob/fb930db/src/System.Net.Primitives/src/System/Net/HttpStatusCode.cs#L70).

**Comment by incompletude** [comment]
Okay, thank you.
