### ISSUE TITLE
 Secondary AppDomains are not supported on this platform 

### ISSUE THREAD

**Issue by euroUK** [dotnet/core#1339]
#  Secondary AppDomains are not supported on this platform 

# General
Just checked .Net Core 2.1 - preview, still  Secondary AppDomains are not supported on this platform.

Are there any plans to implement this in near future? There are still no way to unload assembly from application.

**Comment by svick** [comment]
As far as I know, there is no plan to bring AppDomains to .Net Core. But unloading assemblies in the form of collectible assemblies is likely going to happen after .Net Core 2.1, see https://github.com/dotnet/coreclr/issues/552. Do you think that would work for you?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #16925](https://github.com/dotnet/coreclr/issues/16925) via [**ZenHub**](https://www.zenhub.com/)
