### ISSUE TITLE
Tests are grouped under the "No Traits" section in the Test Explorer even though the class has a [Trait] attribute

### ISSUE THREAD

**Issue by TheBeardedLlama** [dotnet/core#134]
Cross posting from xunit/xunit#889

I have set up my controller tests for a .net core web api xproj.

I have a `TraitAttribute` on the class, but it's not showing up in the *Test Explorer* in VS.

My `dependencies` have `"dotnet-test-xunit": "1.0.0-*"` and `"xunit": "2.2.0-*"` and the test runner is set up as `"testRunner": "xunit"`.

Have I hit a bug or am I doing something wrong? I'm hoping I'm doing something wrong :smile:

**Comment by blackdwarf** [comment]
Posted this to aspnet/tooling. Closing this issue.
