### ISSUE TITLE
.NET Core March 2018 Update

### ISSUE THREAD

**Issue by leecow** [dotnet/core#1341]
The .NET Core March 2018 Update is available. This release includes: 

* .NET Core 1.0.10, 1.1.7 and .NET Core SDK 1.1.8
* .NET Core 2.0.6 and .NET Core SDK 2.1.101

This release includes security fixes. You can read about the updates in the [.NET Core release notes](https://github.com/dotnet/core/blob/master/release-notes/README.md).

Please report any issues you find with the March 2018 Update, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by XavierDa** [comment]
2.0.6 hosting packages seems to fail on my server. i got 0x80070001 incorrect function and in the logs i have : 
[13E8:1018][2018-03-14T11:45:27]e000: Error 0x80070001: Failed to extract all files from container, erf: 1:2:0
[13E8:0DE0][2018-03-14T11:45:27]e000: Error 0x80070001: Failed to wait for operation complete.
[13E8:0DE0][2018-03-14T11:45:27]e000: Error 0x80070001: Failed to open container.
[13E8:0DE0][2018-03-14T11:45:27]e000: Error 0x80070001: Failed to open container: WixAttachedContainer.
[13E8:0DE0][2018-03-14T11:45:27]e312: Failed to extract payloads from container: WixAttachedContainer to working path: C:\Windows\Temp\{0C5BEBA4-A477-414E-9BD5-B7FEE1F2A19C}\4813312A2F31CD01D00A0E9C533F14EA75763888, error: 0x80070001.
[13E8:13A0][2018-03-14T11:45:27]e000: Error 0x80070001: Cache thread exited unexpectedly.

Size seems awfully low (564kB) compared to 2.0.5 hosting (93157kB)

**Comment by BarakatAli** [comment]
Same issue here

**Comment by glat** [comment]
DotNetCore.2.0.6-WindowsHosting.exe does not include the AspNetCore 2.0.6 RuntimePackageStore but the 2.0.5 ones. Install manually the 2.0.6 ones.
@leecow Please check that file.

**Comment by fabiano** [comment]
@XavierDa Had the same problem https://github.com/dotnet/core-setup/issues/3830.

Downloaded the file from my machine and was able to get the full file. Maybe some problem with the CDN.

**Comment by leecow** [comment]
We're looking into the hosting bundle issues. https://github.com/aspnet/Home/issues/2954#issuecomment-373025371

**Comment by leecow** [comment]
@fabiano - the bundle does not contain the 2.0.6 Runtime Package Store. We're in the process of rebuilding and testing the bundle and will update as soon as it's ready. https://github.com/aspnet/Home/issues/2954#issuecomment-373116879

**Comment by fabiano** [comment]
@leecow I saw the message from @Eilon. I'll wait for the fix. Thanks.

**Comment by DoCode** [comment]
@leecow What about the 2.1.0-preview1(2.1.300.8174) bits? Does this base also get an update?

**Comment by leecow** [comment]
@DoCode - 2.1.0 will be updated at the next preview release.

**Comment by yyjdelete** [comment]
Get an `ERR_INVALID_RESPONSE` when download [DotNetCore.2.0.6-WindowsHosting.exe](https://download.microsoft.com/download/8/D/A/8DA04DA7-565B-4372-BBCE-D44C7809A467/DotNetCore.2.0.6-WindowsHosting.exe), it it already be removed?

**Comment by MrAntix** [comment]
![image](https://user-images.githubusercontent.com/873305/37451226-dafaea64-2828-11e8-9c11-28f8a0169b13.png)

will this be available?
may we have an eta if it is or not when the next update will be?

**Comment by daniel-white** [comment]
I'm getting this when trying to build my docker manually. I'm guessing its all related:

```
The following packages have unmet dependencies:
dotnet-hosting-2.0.6-rtm-10011 : Depends: aspnetcore-store-2.0.6-rtm-10011 but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y dotnet-hosting-2.0' returned a non-zero code: 100
../../build/docker/docker.mk:2: recipe for target 'package' fail
```

I'll manually point my build at 2.0.5 until this is resolved.

**Comment by vandreytrindade** [comment]
Getting error of file not found when trying to download DotNetCore.2.0.6-WindowsHosting.exe

**Comment by preetikr** [comment]
Thanks, for your patience on this.  [The issue with the DotNetCore 2.0.6 Hosting bundle](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.6.md#windows-server-hosting-bundle-dotnetcore206-windowshostingexe-does-not-contain-the-updated-aspnetcore-runtimepackagestore) is now resolved and you can download the updated file from [here](https://go.microsoft.com/fwlink/?linkid=869674). Please note as part of the refresh we have changed the file name from DotNetCore.2.0.6-WindowsHosting.exe to DotNetCore.2.0.6-1-WindowsHosting.exe.

**Comment by IDisposable** [comment]
Added PR to correct internal link to fixes list in the release notes https://github.com/dotnet/core/pull/1353

**Comment by fabiano** [comment]
Download and installed the latest version DotNetCore.2.0.6-1-WindowsHosting.exe without problems. Thank you all!

**Comment by benbenwilde** [comment]
We had problems running with System.Data.SqlClient version 4.4.0, getting a FileLoadException.
https://www.nuget.org/packages/System.Data.SqlClient

Upgrading the package to 4.4.3 fixed it.

**Comment by cocowalla** [comment]
> This release includes security fixes. You can read about the updates in the [.NET Core release notes](https://github.com/dotnet/core/blob/master/release-notes/README.md).

No I can't - the release notes only go up to 2.0.**_5_**.

**Comment by dmumladze** [comment]
I'm trying to install only the hosting part for self-contained apps, and using the below command, but it installs the runtimes as well, which I do not want. Any changed?

`DotNetCore.2.0.6-1-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0`

**Comment by Eilon** [comment]
@joeloff - is this in your wheelhouse?

**Comment by joeloff** [comment]
@Eilon Yes.

@dmumladze The LTS/FTS options are only supported in the 1.x hosting bundle since there is no LTS/FTS designation for 2.x at this point.

We added better support in 2.1 for selecting separate items (runtime, shared framework and ANCM), but for 2.0 this is a known problem unfortunately.

The work-arounds are not that ideal:

1. You can decompile and extract ANCM from the two hosting bundle
2. You can take the 2.1 preview bundle and run it to only install ANCM. With the 2.1 bundle you can pass in OPT_NO_RUNTIME=1 OPT_NO_SHAREDFX=1 and that will only install ANCM for you.

@Eilon , @muratg we might want to look at back porting the 2.1 swithces to 2.0

**Comment by Eilon** [comment]
@joeloff - can you log an issue for that suggestion in the appropriate repo and tag me and @muratg in it.

**Comment by muratg** [comment]
@joeloff @Eilon I did (before seeing your comment)

**Comment by dmumladze** [comment]
@joeloff Unfortunately previews aren’t allowed in client’s production env as well as the runtime, so my only option is #1. Question: I can see three components installed from 2.0.* package, out of which, two are runtime x86 and x64, but can I remove them manually?

**Comment by leecow** [comment]
Closing as subsequent updates have been released.
