### ISSUE TITLE
Cannot update Microsoft.NETCore.App (Implicit reference by a SDK)

### ISSUE THREAD

**Issue by lkfr** [dotnet/core#1354]
Hi,

I am working on an Asp.Net Core 2.0 application and I cannot upgrade the Microsoft.NETCore.App package (2.0.0) to a newer version. NuGet tells me that this version is implicitely referenced by a SDK and I should update the SDK.

I am a bit puzzled as I have the last version of the SDK installed (2.1.101) and that is the one used in the build process. I cannot find any reference to an older SDK.

Am I missing something or is there some kind of problem?

The project file contains the following:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="dotnet --version" />
  </Target>

</Project>
```

Thanks!

LK

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8818](https://github.com/dotnet/cli/issues/8818) via [**ZenHub**](https://www.zenhub.com/)
