### ISSUE TITLE
Problem with ProjectReference for Layering with netcoreapp2.0

### ISSUE THREAD

**Issue by FlorianRainer** [dotnet/core#1355]
OS: Windows 10, Visual Studio 15.6.2 / Dotnet CLI Version 2.1.101 NetCore 2.0

I have the following Problem, i have a quite large Solution with multiple Projects organized in different Layers. Some Layers are hidden from the Top Level Application and are used only by the layers below.
I had this already back in old csproj projects, on .net 4.x and later with new csproj system and asp.net core but based on full framework "net462" i never had any problems with this.

now i was upgrading to netcoreapp2.0 (netcore in general) and i have noticed some problems.

i was not able to run my application if i use `PrivateAssets All` on ProjectReference if the references project uses SubProjects or NuGet Packages (exclusive used by this referenced SubProject)
```
<ProjectReference Include="....">
      <PrivateAssets>All</PrivateAssets>
</ProjectReference>
```

I have created a example Repo on GitHub based on new Projects from "File New Project" in VS linked together and explained the problems and solutions in a few small commits.

i hope this explains the Problem.
https://github.com/FlorianRainer/Report_ExampleApp/commits/master

Please Read the Commit Messages for more details.

Maybe i have missed something and there is a easy built in way to do this, maybe something else then `PrivateAssets All` but i havn't found anything working.

Thanks for any feedback on this, hopefully there whould be a better solution then this hacky workaround.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8826](https://github.com/dotnet/cli/issues/8826) via [**ZenHub**](https://www.zenhub.com/)
