### ISSUE TITLE
HttpStatusCode compatibility across framework

### ISSUE THREAD

**Issue by incompletude** [dotnet/core#1356]
This is very inconvenient. Both ways produce errors.

```
[ProducesResponseType(HttpStatusCode.OK)] // cast

return StatusCode(HttpStatusCode.OK, users); // cast
```

Is there any reason for this?

Thx.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28157](https://github.com/dotnet/corefx/issues/28157) via [**ZenHub**](https://www.zenhub.com/)
