### ISSUE TITLE
Runtime library loading

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/core#1357]
# Issue Title

How to load libraries at runtime and resolve their dependencies or have workarounds for that.

# General

I'm currently converting a netfx 4.7 with asp.net core 2.0 application to .net core 2.0/2.1.
The solution looks more or less like this:
1. Web project (has references to the shared projects and business logic projects)
2. Business Logic projects
3. Shared projects (e.g. framework libraries)
4. Test projects
5. Tools

The normal development process looks like this:
1. Build solution in VS 2017 (all projects build to the web project output directory)
2. Run a custom tool on command line (which is part of the solution) to prepare shared test database, this tool loads all libraries (Assembly.Load) with a specific name to prepare the database (e.g. seed data etc.)
3. Develop
4. Run Tests (they use the databases)

The build process on the build machine does a dotnet publish for the web project and this is gets then deployed.

The above process works fine on netfx 4.7 because the build process in VS 2017 copies all libraries and their dependencies from nuget packages to the build directory and i can run the custom tool and build my databases.

On .net core 2.0 the nuget dependencies do not get copied to the build directory during VS 2017 build, so while I see binaries for my test libraries in the build directory several dependencies (e.g. xunit.core.dll) are missing and my tool can't Assembly.Load the test libraries because of that.

As far as I understood e.g. @natemcmaster in several issues related to DependencyContext, that it is possible to properly resolve the nuget dependencies myself but it's a lot of work and probably a lot of hurt too. I got it working fairly nicely, but the whole dependency resolving is kinda poorly documented and I'd rather not use that code.

So I'm looking for alternatives:
The most promising alternative I found is to conditionally include all projects (test/tools etc.) in my web project behind a msbuild property which is only true in DEV, just like in https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition

Are there any msbuild properties which are only true during build in Visual Studio?
This would make the above approach easy and msbuild would copy all nuget dependencies because the dependency graph is well known during build as all projects are referenced.

Are there any plans for e.g. 2.1 (couldn't find any) to simplify external library loading during runtime or some MsBuild setting which copies all the nuget dependencies to the output directory just as dotnet publish does?

Any better ideas besides conditionally include all projects, which is kinda ugly (because you need to know that some projects are used conditionally)?

**Comment by Petermarcu** [comment]
@jeffschwMSFT

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #17014](https://github.com/dotnet/coreclr/issues/17014) via [**ZenHub**](https://www.zenhub.com/)
