### ISSUE TITLE
HttpStatusCode compatibility across framework

### ISSUE THREAD

**Issue by incompletude** [dotnet/core#1358]
Is there any reason for this?

[ProducesResponseType(HttpStatusCode.OK)] // requires cast
return StatusCode(HttpStatusCode.OK); // requires cast

Thx

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28172](https://github.com/dotnet/corefx/issues/28172) via [**ZenHub**](https://www.zenhub.com/)
