### ISSUE TITLE
error on .net core projects not opening and creating

### ISSUE THREAD

**Issue by umarsolehri** [dotnet/core#1359]
issue comes on while opening or creating .net core project . this issue comes after latest updates
please take a look at attached files

[VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt](https://github.com/dotnet/core/files/1822073/VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt)

**Comment by umarsolehri** [comment]
[VsProjectFault_4bff3231-b012-4fc1-b936-76b13034f267.failure.txt](https://github.com/dotnet/core/files/1822078/VsProjectFault_4bff3231-b012-4fc1-b936-76b13034f267.failure.txt)
[VsProjectFault_8bf73e3f-2c04-4e53-bf70-6e7554b2bc83.failure.txt](https://github.com/dotnet/core/files/1822079/VsProjectFault_8bf73e3f-2c04-4e53-bf70-6e7554b2bc83.failure.txt)
[VsProjectFault_8e04af0c-8349-4ec2-b671-de05c02e6dd6.failure.txt](https://github.com/dotnet/core/files/1822080/VsProjectFault_8e04af0c-8349-4ec2-b671-de05c02e6dd6.failure.txt)
[VsProjectFault_28deb9fa-7b99-44eb-92e8-dc13222194ad.failure.txt](https://github.com/dotnet/core/files/1822081/VsProjectFault_28deb9fa-7b99-44eb-92e8-dc13222194ad.failure.txt)
[VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt](https://github.com/dotnet/core/files/1822082/VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt)
[VsProjectFault_2779d11f-0df7-431c-8457-2375f9e39b02.failure.txt](https://github.com/dotnet/core/files/1822083/VsProjectFault_2779d11f-0df7-431c-8457-2375f9e39b02.failure.txt)
[VsProjectFault_8724be7f-9f17-41f3-970c-9f606b0c3f83.failure.txt](https://github.com/dotnet/core/files/1822084/VsProjectFault_8724be7f-9f17-41f3-970c-9f606b0c3f83.failure.txt)
[VsProjectFault_8957c0ad-5189-4f14-9a06-c29e472e95d1.failure.txt](https://github.com/dotnet/core/files/1822085/VsProjectFault_8957c0ad-5189-4f14-9a06-c29e472e95d1.failure.txt)
[VsProjectFault_ab59b504-6c20-4636-ad79-608840c1c310.failure.txt](https://github.com/dotnet/core/files/1822086/VsProjectFault_ab59b504-6c20-4636-ad79-608840c1c310.failure.txt)
[VsProjectFault_afc05dff-5957-4aa6-89e0-5db14361fa56.failure.txt](https://github.com/dotnet/core/files/1822087/VsProjectFault_afc05dff-5957-4aa6-89e0-5db14361fa56.failure.txt)
[VsProjectFault_bf2bb93c-d970-4950-9a6e-4c9c42a2049b.failure.txt](https://github.com/dotnet/core/files/1822088/VsProjectFault_bf2bb93c-d970-4950-9a6e-4c9c42a2049b.failure.txt)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/project-system #3398](https://github.com/dotnet/project-system/issues/3398) via [**ZenHub**](https://www.zenhub.com/)
