### ISSUE TITLE
Compilation Symbols ignored?

### ISSUE THREAD

**Issue by khionu** [dotnet/core#136]
[You can see here](https://i.lithi.io/KUdQ.jpg) that the Compilation Symbols seem to be ignored. Furthermore, I can't locate the Build Configurations for this project in the actual project directory.

**Comment by blackdwarf** [comment]
@khionu this will be mitigated with move to msbuild and csproj. I will close this one. If you feel that this was in error, please open this issue on aspnet/tooling. Thanks!
