### ISSUE TITLE
Missing information about LTS on download page

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/core#1360]
_From @rhegner on March 19, 2018 8:16_

The .NET Core download page used to have a clear separation between Current and LTS releases.

This information is missing on the [current page](https://www.microsoft.com/net/download/windows/run).

I want to upgrade my project from 1.1 to 2.0 as soon as there is a LTS version of 2.0 available. But I can't see from that website if 2.0.6 is a LTS version or not.

_Copied from original issue: dotnet/coreclr#17031_

**Comment by RussKeldorph** [comment]
_From @shahid-pk on March 19, 2018 8:47_

2.0.0 is LTS, 2.0.*  releases are bug fixes versions to the LTS so the latest version in that line the better and more bug fixes. 1.0.*  are LTS versions too. But yes it should be mentioned somewhere if not already.

**Comment by RussKeldorph** [comment]
@richlander

**Comment by Petermarcu** [comment]
2.0.X are not LTS releases. This issue should get moved to the website repo.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/dotnet-core-website #545](https://github.com/dotnet/dotnet-core-website/issues/545) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rhegner** [comment]
What is the current state of this? I can't access the dotnet-core-website repo...

**Comment by Petermarcu** [comment]
@rowanmiller can you give an update?

**Comment by rowanmiller** [comment]
Changes to the Download section got put on hold in the crazy lead up to //build conference. I'm working on them this week and expect to have them live next week.

**Comment by rhegner** [comment]
Nice... looking forward to having this back on the page (because it's still unclear to me whether one of the 2.0.x revisions has been labelled as LTS by now...)

**Comment by rowanmiller** [comment]
The main downloads page just displays current, but we've updated the all downloads page to include info on LTS releases now - https://www.microsoft.com/net/download/all.

**Comment by rhegner** [comment]
Yeah I already saw it earlier today, thank you!
Do you know what the plans are for a new LTS release? Do you plan to make the latest release of the 2.0.x branch a LTS at some point or will it be a 2.1 release?

**Comment by rowanmiller** [comment]
@leecow do you know what the plans are around the next LTS release?

**Comment by leecow** [comment]
Plan is to declare 2.1 the next LTS after a couple of updates. Some details in the [release blog post](https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1) today
