### ISSUE TITLE
Runtime installation fails on Server Core with WoW64 subsystem removed

### ISSUE THREAD

**Issue by jberezanski** [dotnet/core#1362]
On a Windows Server 2016 Core installation with the `WoW64-Support` feature removed, installation of the 64-bit .NET Core runtime fails:

````
PS C:\Users\Administrator> .\dotnet-runtime-2.0.6-win-x64.exe /install /quiet /norestart
Program 'dotnet-runtime-2.0.6-win-x64.exe' failed to run: The application has failed to start because its side-by-side configuration is
incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
````

The Application event log gives more details:

````
PS C:\Users\Administrator> Get-WinEvent -ProviderName SideBySide -MaxEvents 10 | fl *
(...)
Message              : Activation context generation failed for "C:\Users\Administrator\dotnet-runtime-2.0.6-win-x64.exe". Dependent
                       Assembly Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="X86",publicKeyToken="6595b64144
                       ccf1df",type="win32",version="6.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.
````

Apparently, the 64-bit .NET Core runtime installer is a 32-bit application and references the 32-bit common controls library, so it fails on servers with the 32-bit subsystem removed.

Steps to reproduce:
- install any Windows Server 2016 Core, for example Hyper-V Server 2016
- start PowerShell
- remove the 32-bit subsystem: 
    `Uninstall-WindowsFeature -Name WoW64-Support -Restart`
- log on and start PowerShell again
- download 64-bit .NET Core runtime 2.0.6 installer: 
    `Invoke-WebRequest -UseBasicParsing -Uri https://download.microsoft.com/download/8/D/A/8DA04DA7-565B-4372-BBCE-D44C7809A467/dotnet-runtime-2.0.6-win-x64.exe -OutFile dotnet-runtime-2.0.6-win-x64.exe`
- attempt installation:
    `.\dotnet-runtime-2.0.6-win-x64.exe /install /quiet /norestart`

Update: corrected download command.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #3856](https://github.com/dotnet/core-setup/issues/3856) via [**ZenHub**](https://www.zenhub.com/)
