### ISSUE TITLE
Can't publish to Azure with .NET Core 2.0

### ISSUE THREAD

**Issue by sittmannkatia** [dotnet/core#1363]
# General Issue

When attempting to publish app to Azure, get an error regarding the target framework in the project.assets.json file. Error is:

```
Assets file 'C:\...\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'.
Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project
```

When I go look at the project.assets.json file, the target framework is netcoreapp2.0 and everything else looks correct.

# Steps taken to Fix

1) Tried to manually delete obj and bin folders and run dotnet restore from command line
2) Tried to change <TargetFramework> to <TargetFrameworks> per suggestion in another github issue
3) Tried to publish an ASP.NET Web Application (.NET Framework) to confirm it's core specific

# Reproduction Steps

1) Create new project in VS 2017 Community
2) Select ASP.NET Core Web Application
3) Attempt to publish to Azure

**Comment by Zorzin** [comment]
I fixed it by removing "C:\Program Files\dotnet\sdk\2.1.102" folder and having only "2.1.101". Solution provided from [StackOverflow](https://stackoverflow.com/questions/49397793/error-publishing-net-core-2-0-web-applicaiton-to-azure-app-service)

**Comment by akinix** [comment]
I have the same problem when vs2017  upadted  to 15.6.3 and .net core uptated to 2.1.102.
csproj:
```
<TargetFrameworks>net461;netcoreapp2.0</TargetFrameworks>
```
error:
```
C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167
```

**Comment by dasMulli** [comment]
This may be due to a recent issue with ReSharper. Try deactivating ReSharper.

**Comment by akinix** [comment]
@Zorzin 
```
delete C:\Program Files\dotnet\sdk\2.1.102
```
this way was ok !now can compile successfully. thank you!

**Comment by sittmannkatia** [comment]
I can confirm that deleting the 2.1.102 sdk fixes the issue. Thanks!
