### ISSUE TITLE
身份验证无法在IE中写入cookie

### ISSUE THREAD

**Issue by Hsinky** [dotnet/core#1368]
在asp.net core 2.0+版本中，写入身份验证时，IE内核浏览器无法写入cookie，但谷歌或火狐是正常的，如下是我的代码
![image](https://user-images.githubusercontent.com/10111222/37711673-6ef5d698-2d4c-11e8-97a9-0ebeeed8800c.png)

**Comment by Petermarcu** [comment]
Translated: In asp.net core 2.0+, when writing authentication, the IE kernel browser cannot write cookies, but Google or Firefox is normal. The following is my code.

@DamianEdwards @Eilon

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Home/issues/2985.

@Hsinky - please try not to open the same issue in multiple repos.
