### ISSUE TITLE
Easier creation of RSACryptoServiceProvider from public key data

### ISSUE THREAD

**Issue by DiskJunky** [dotnet/core#1371]
# Issue Title

Currently when using public/private signing/encrypting using RSA, it's not possible to directly create an instance of RSACryptoServiceProvider easily, given just a public key in PEM (or variant) format.

# General

Given a PEM, in order to create an instance of RSACryptoServiceProvider it requires the programmer to have a knowledge of ASN.1, know that a PEM is in this format and how to correctly specify the AsnEncodedData settings accordingly after parsing and base64 decoding a PEM - a high bar for entry when trying to use it. This appears on all versions of .NET and OSes to date that I'm aware of.

Example of this issue occurring; [Correctly Create RSACryptoServiceProvider from public key
](https://stackoverflow.com/q/41808094/1838819)
Given the relatively recent post and the specificity of the issue, the view count is higher than would be expected - people are encountering/searching this regularly.

A proposed way forward would be for a constructor (or similarly accessible route) to create the necessary RSACryptoServiceProvider directly from given PEM data (bytes, file, base64 data.... [).](http://lapo.it/asn1js)

**Comment by bartonjs** [comment]
This is already on the CoreFx plan (https://github.com/dotnet/corefx/issues/20414).

(But when I write it, where will all my rep come from?)

**Comment by DiskJunky** [comment]
Hadn't seen that - I'll leave it with ye. Thanks again for all the info relating to that, it really helped us out!

**Comment by bartonjs** [comment]
No worries, it shows that there are customers who care about the feature :).
