### ISSUE TITLE
Net Native compilation fails with Out of Memory (Xamarin/UWP)

### ISSUE THREAD

**Issue by sebastianfilke** [dotnet/core#1372]
We have a big problem with the net native compilation in a relative big project.
The release build only works if we disable the option “Compile with .NET Native tool chain” or “Optimize code”.
Otherwise the build takes up to 10 minutes and ends with an out of memory error.

The build log file is attached: [build.log](https://github.com/dotnet/core/files/1837784/build.log)

There is also an ilcRepro.zip file attached:
https://drive.google.com/file/d/1bhEwZco0fugxxRDxj0hi86jnb9eJIpOV/view?usp=sharing

We tried several different settings in the Default.rd.xml, but nothing worked yet.

•	We comment out the application assembly tag

•	We also tried to add an extra assembly tag for every assembly and with DoNotOptimize

But neither worked. 

Please give me an advice or another solution. I don’t know if this is a bug or an assembly doesn’t worked or is not ready for net native.

**Comment by Petermarcu** [comment]
@jkotas do you know where this issue should get tracked/discussed?

**Comment by jkotas** [comment]
This issue was moved to dotnet/corert#5604
