### ISSUE TITLE
Inconsistent compile behavior for out parameters

### ISSUE THREAD

**Issue by marce155** [dotnet/core#1373]
When declaring an out parameter on a method I’m used to having to assign the parameter a value before leaving the method: 
```
public bool TryGet(string foo, out TimeSpan bar){
 bar = TimeSpan.FromSeconds(1);
 return true;
}
```

Today I encountered a behavior which was at least unexpected and feels inconsistent. When I’m targeting netcoreapp2.0 there are some cases where the program will compile and work even if the out parameter has not been assigned.

To be exact this is the case for TimeSpan or structs containing (only) a TimeSpan (that is as far as I tested). The same code will fail to compile for .NET 4.6.

```
class Program
    {
        public static void Main()
        {
            TimeSpan timeSpan;
            Foo foo;
            Bar bar;
            //Baz baz;

            TryTimeSpan(out timeSpan);
            TryFoo(out foo);
            TryBar(out bar);
            //TryBaz(out baz);

            Console.WriteLine(timeSpan);
            Console.WriteLine(foo);
            Console.WriteLine(bar);
        }
        private static bool TryTimeSpan(out TimeSpan timeSpan)
        {
	    // no compile error - unexpected
            return false;
        }
        private static bool TryFoo(out Foo foo)
        {
	    // empty struct works with target net461 as well
            return false;
        }
        private static bool TryBar(out Bar bar)
        {
	    // no compile error - unexpected
            return false;
        }
        /*
        private static bool TryBaz(out Baz baz)
        {
            // compile error, baz not assigned for all targets - expected
            return false;
        }
        */
    }
    struct Foo { }
    struct Bar
    {
        public TimeSpan TimeSpan { get; set; }
    }
    struct Baz
    {
        public int Int { get; set; }
    }
```
I assume that somehow proper defaults are assigned, yet it still feels a little strange. Could you please clarify if this is expected behavior and what causes it?

**Comment by danstur** [comment]
This definitely seems to violate the [specification](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#output-parameters): 

> Every output parameter of a method must be definitely assigned before the method returns.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28392](https://github.com/dotnet/corefx/issues/28392) via [**ZenHub**](https://www.zenhub.com/)
