### ISSUE TITLE
Dotnet add dont autocomplete like Nuget in VS Communite.

### ISSUE THREAD

**Issue by ucavalcante** [dotnet/core#1374]
Dotnet add cant do autocomplete like git or nuget when we type tab button.

I'm believe this will be a very valiable resource for improve speed up our coding without search whats wrong when we install packages.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8879](https://github.com/dotnet/cli/issues/8879) via [**ZenHub**](https://www.zenhub.com/)
