### ISSUE TITLE
Formating of double to string using G29 format sometimes returns wrong result

### ISSUE THREAD

**Issue by Eneuman** [dotnet/core#1376]
# Issue Title

Formating of double to string using G29 format sometimes returns wrong result.

# General

Using .Net core 2.0 latest, Windows 10 Pro, Swedish Version

Running this
```
      var test1 = double.Parse("1,5").ToString("G29");
      var test2 = double.Parse("1,6").ToString("G29");
      var test3 = double.Parse("1,7").ToString("G29");
```

results in this:

```
test1 = "1,5"
test2 = "1,6000000000000001"
test3 = "1,7"
```

I was expecting this:
```
test1 = "1,5"
test2 = "1,6"
test3 = "1,7"
```

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28409](https://github.com/dotnet/corefx/issues/28409) via [**ZenHub**](https://www.zenhub.com/)
