### ISSUE TITLE
Problem with .Net Core package, Ubuntu 14.04

### ISSUE THREAD

**Issue by Pedestrian22** [dotnet/core#1377]
I would like to ask you if somebody knows how to help with this problem. I cannot run my project in Ubuntu 14.04. There is missed package "**PacketDotNet**" and I need to run it in .Net Core project.
Thanks for any idea and help.

![screen1](https://user-images.githubusercontent.com/37690531/37826677-b168e15c-2e94-11e8-8ede-63ffa2872a77.png)

**Comment by dasMulli** [comment]
This package was authored for .net framework on windows, so this isn't really an issue of .NET Core per se - it fails to load WinPcap.

**Comment by dasMulli** [comment]
Oh I see that you already opened an issue on the corresponding repository: https://github.com/chmorgan/packetnet/issues/53

**Comment by Pedestrian22** [comment]
Yes, I did. Thanks for your answer. I'm trying to solve the problem ASAP. That's my first program run on Ubuntu and I have some troubles, as you see.

**Comment by Petermarcu** [comment]
Looks like you will need to work with that library author to get a version that doesn't have a Windows dependency. It looks like libpcap is likely what needs to be used on linux. I'm going to close this issue here because it really is an issue to work with the library author on.

**Comment by Petermarcu** [comment]
If you read the readme on that github project, it notes that it is only packaging the library for Windows and that you need to compile the library yourself and copy it into your application to get Mac and Linux support.
