### ISSUE TITLE
WebRequest.DefaultWebProxy in .net core for corss platform

### ISSUE THREAD

**Issue by nQuantPlatforms** [dotnet/core#1381]
# Issue Title

WebRequest.DefaultWebProxy in .net core for corss platform

# General
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
<PropertyGroup>
    <RuntimeIdentifiers>win10-x64;osx-x64;linux-x64;</RuntimeIdentifiers>
</PropertyGroup>

Using above RID and running on Win 10 gives me platform not supported exception.
My app need to read proxy from Win, OSX and Linux platform. Whats the best way to get proxy in Core app without having to create separate platform specific library ?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28642](https://github.com/dotnet/corefx/issues/28642) via [**ZenHub**](https://www.zenhub.com/)
