### ISSUE TITLE
What are the expected performance characteristics on linux-arm

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/core#1383]
I've tried the 2.1 preview1 build on my ASP.NET Core application. Most of my code is in `netstandard2.0` libraries and I have added `netcoreapp2.1` to my target frameworks in addition to `net47`. The result just works - wonderful!

The application runs on my embedded Linux platform based on Yocto 2.3 (poky) with an i.MX 6 SoloX. I have published it as `linux-arm`, deployed it and can successfully run it with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` (because I'm lazy) - yay!

I can, however, compare the performance of the .NET Core build to the `net47` build running via Mono 5.4.1.6. .NET Core 2.1 takes about double the time compared to Mono to fully start the application and all first web requests (Web API calls or SignalR) feel a lot slower on .NET Core as well. Subsequent calls, though, are fast.

So my question is: What are the expected performance characteristics of the preview1 build and what can I expect towards 2.1 RTM for `linux-arm`?

**Comment by Petermarcu** [comment]
There is active work underway to improve startup performance of arm32 and I expect some of that will land in 2.1 Preview2. On our x64 runtime, for example, we do a bunch of the startup compilation at build time. This usually results in cutting the startup time for helloworld in half. Results vary depending on the application of course. We are working on doing the same thing for arm32. 

Are you using MVC Views and if so, are you pre-compiling them? That would be another way to speed up startup for ASP.NET.

**Comment by Petermarcu** [comment]
@RussKeldorph @richlander

**Comment by Petermarcu** [comment]
@MeiChin-Tsai

**Comment by Tragetaschen** [comment]
In the ASP.NET community standup yesterday, @DamianEdwards mentioned his experience on a Raspberry Pi, which was pretty much what I'm describing above: Performance good, startup bad. He also mentioned that the ARM precompilation infrastructure has been pulled from 2.1 likely to be included in 2.2 "later this year" (with the appropriate disclaimers).
