### ISSUE TITLE
Product Version appears to not get set in SCD build while it does for FDD build

### ISSUE THREAD

**Issue by buckstephenh** [dotnet/core#1384]
# Issue Title

Product Version appears to not get set in SCD build while it does for FDD build

# General

.net core 2.0, Windows 7 64 bit

dotnet build 

will produce a dll with the correct project version in the Product Version attribute of the .dll file.  However when we do a SCD build as in 

dotnet publish -f netcoreapp2.0 -c Release -r win-x64

The dotnet.exe that has been renamed to the project at the end of the publish command is missing the Product Version that matches the project, and other expected fields, like Title, Company, Authors, etc.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9637](https://github.com/dotnet/cli/issues/9637) via [**ZenHub**](https://www.zenhub.com/)
