### ISSUE TITLE
Add links to macOS/Linux SDK Installer on Download site

### ISSUE THREAD

**Issue by SabotageAndi** [dotnet/core#1387]
# Issue Title

Add links to macOS/Linux SDK Installer on Download site

# General

Please link to the SDK Installer files on the SDK download sites of specific versions. 
Currently there are only links to the zipped binaries.
It would be easier to find the installers if you need them. 

Example:
https://www.microsoft.com/net/download/dotnet-core/sdk-1.1.8 

Screenshot:
![image](https://user-images.githubusercontent.com/859801/37959137-b8896242-31b2-11e8-9e89-da8853d59ed8.png)

The installers are still available, as they are linked in the GitHub releases.
See https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.10-download.md

Thanks!

**Comment by leecow** [comment]
Thanks @SabotageAndi - Will make these updates and they'll be live the next time we need to update the site metadata.
