### ISSUE TITLE
ASP.NET Core on Windows with IIS using a sqlite database very very slow

### ISSUE THREAD

**Issue by yunfandev** [dotnet/core#1388]
I build a samll webapi project using .net core, and host on windows in c drive with iis, but it was very very slow when read or write sqlite database.

But when i publish the project in d drive the problem does not exists, please tell me why.😂😂😂😂

**Comment by Petermarcu** [comment]
I'm not sure there is enough information here to help. Slower drive? If you can provide more details about the performance and hardware characteristics, there is a better chance of someone being able to help.

**Comment by joshfree** [comment]
Closing this old issue.  Please feel free to re-open this issue with more details.
