### ISSUE TITLE
Awit use delay Windows server 2012 R2

### ISSUE THREAD

**Issue by a641545621** [dotnet/core#1389]
Response response =  _client.Execute(request).Result;
Response response = awit  _client.Execute(request);
When using Awit to get results, there is no problem with the Win10 system, but when using Windows Server 2012 R2, occasionally it takes more than 20 seconds or more to wait. If you use .Result directly, you will not wait for a long time.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28641](https://github.com/dotnet/corefx/issues/28641) via [**ZenHub**](https://www.zenhub.com/)
