### ISSUE TITLE
Missing Classes in System.Reflection.Emit

### ISSUE THREAD

**Issue by hismichael** [dotnet/core#139]
I've found the following classes are missing in package System.Reflection.Emit:

System.Reflection.Emit:

- DynamicMethod

- ILGenerator

System
    

- Delegate.CreateDelegate method also no longer exists

**Comment by neyromant** [comment]
DynamicMethod located in "System.Reflection.Emit.Lightweight" package.
ILGenerator located in "System.Reflection.Emit.ILGeneration" package

**Comment by hismichael** [comment]
Okay. Yes I see they are there now. Thanks!
