### ISSUE TITLE
Broken download links for dotnet-runtime-2.0.6-win-x64.exe on 2.1.100-sdk-download.md and 2.1.102-sdk-download.md

### ISSUE THREAD

**Issue by BJMdotNET** [dotnet/core#1391]
On https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.100-sdk-download.md and https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.102-sdk-download.md , the download link to the 64-bit Runtime Installer is broken.

Both pages link to https://download.microsoft.com/download/1/1/0/11046135-4207-40D3-A795-13ECEA741B32/dotnet-runtime-2.0.6-win-x64.exe , whereas the correct link is https://download.microsoft.com/download/8/D/A/8DA04DA7-565B-4372-BBCE-D44C7809A467/dotnet-runtime-2.0.6-win-x64.exe (going by the working link on https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.103-sdk-download.md ).

**Comment by Petermarcu** [comment]
@leecow
