### ISSUE TITLE
Wrong debug directory entry in some .NET Core 2.1 preview1 libraries

### ISSUE THREAD

**Issue by KKatsnel** [dotnet/core#1392]
Here two possible versions of the data format of a debug directory are described:
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md 
However, there are two Debug Directory Entries in the "System.IO.FileSystem.dll" library of 4.1.1.0 version (it's from .NET Core 2.1 preview1):
- Major = 0x0100, Minor = 0x504d that corresponds to the Portable PDB format, and
- Major = 0x0100, Minor = 0, that doesn't correspond to any version.

As far as I understand the second entry is wrong, isn't it?

**Comment by Petermarcu** [comment]
@tmat

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29223](https://github.com/dotnet/corefx/issues/29223) via [**ZenHub**](https://www.zenhub.com/)
