### ISSUE TITLE
Console ReadKey echo escapes

### ISSUE THREAD

**Issue by devel0** [dotnet/core#1398]
Using Console.ReadKey(true) should not echo control keys but in linux terminal I got `^[OC` echos.

## version

- **dotnet version** : 2.1.101
- **os** : ubuntu 17.10

## repro

```
Console.ReadKey(true);
```

- press "right arrow" key

### expected

- no echoes

### current behavior

- echoed `^[OC` to the console

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #28694](https://github.com/dotnet/corefx/issues/28694) via [**ZenHub**](https://www.zenhub.com/)
