### ISSUE TITLE
Default proxy issues

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/core#1404]
# Default Proxy issues
Our organisation has a proxy and in previous versions on .NET (.net full framework), you can add the following to the web.config and the application will use your system's default proxy.

```XML
<system.net>
   <defaultProxy useDefaultCredentials="true" />
</system.net>
```
I have tried a lot of different options but just cant seem to get anything to work.

```csharp
string username = "test";
string password = "test";
WebProxy proxy = new WebProxy($"http://{username}:{password}@bluecoat.domain.gov.uk", 8080)
{
    Address = new Uri("http://{username}:{password}@bluecoat.domain.gov.uk:8080"),
    Credentials = new NetworkCredential(username, password)
};
HttpClientHandler clientHandler = new HttpClientHandler
{
    Proxy = proxy,
    UseProxy = true,
    Credentials = new NetworkCredential(username, password)
};
var httpClient = new HttpClient(clientHandler);
```

Any help would be greatly appreciated.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29028](https://github.com/dotnet/corefx/issues/29028) via [**ZenHub**](https://www.zenhub.com/)
