### ISSUE TITLE
Dotnet restore is looking for tools at dot net sdk folder rather than visual studio folder

### ISSUE THREAD

**Issue by sam-adh** [dotnet/core#1407]
# Issue Title

Dotnet restore is looking tools at dot net sdk folder rather than visual studio folder

# General

We had an issue while creating VS 2017 with .Net Core 1.*(I installed .Net Core 1.1.8 ). While triggering the dotnet restore, it failed as it was searching the components like wix, azure etc in dotnet folder rather than Visual studio folder. 

To replicate the problem, please install VS 2017 and .Net Core 1.1.8. Go to the visual studio and create a new project. Select Excel 2013 and 2016 VSTO Add-in. Now go to the solution folder and using cmd type "dotnet restore". You will get the following error.

_"C:\Users\buildadmin01\Documents\Visual Studio 2017\Projects\ExcelAddIn1\ExcelAddIn1\ExcelAddIn1.csproj(187,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.1.8\Microsoft\VisualStudio\v10.0\OfficeTools\Microsoft.VisualStudio.Tools.Office.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk."_

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9052](https://github.com/dotnet/cli/issues/9052) via [**ZenHub**](https://www.zenhub.com/)
