### ISSUE TITLE
Get full Url 

### ISSUE THREAD

**Issue by ekhtiari** [dotnet/core#1408]
HI 
in dotnet core v2.0 i use this code to get full path for pass to  ckeditor module 
`var _location= HttpContext.Request.GetUri().GetLeftPart(UriPartial.Authority);`

but in dotnet core v2.1 i can't use GetUri

can you help me why and what must i do ?

**Comment by Petermarcu** [comment]
@davidfowl ?

**Comment by Petermarcu** [comment]
@muratg

**Comment by muratg** [comment]
@Tratcher

**Comment by ekhtiari** [comment]
Thanks @Tratcher 
I used this code : 
`var myurl= new Uri(HttpContext.Request.GetDisplayUrl()).GetLeftPart(UriPartial.Authority);`

**Comment by Tratcher** [comment]
Use GetEncodedUrl instead.
