### ISSUE TITLE
Showing classes from indirectly referenced packages in .NET Core - broken "facade"

### ISSUE THREAD

**Issue by atuzovic** [dotnet/core#141]
This question has spurred decent amount of interest on StackOverflow, but I didn't get any answer to it, so I will submit it as an issue here. I am not sure if this is related to .NET Core or to Visual Studio itself, but nevertheless I would appreciate help on this.

[Link to original SO post](http://stackoverflow.com/questions/37963523/showing-classes-from-indirectly-referenced-packages-in-net-core)

I am trying to implement basic UoW/Repository pattern with ASP.NET/Entity Framework Core and I have encountered very troubling behavior.

My solution consists of 4 projects in total.

**.DAL project**, where my entity classes are defined and where my DbContext is defined:

```
public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

```
public class ApplicationDbContext : DbContext
{
    public DbSet<Product> Products { get; set; }
}
```

**.Facade** project, where my IUnitOfWork and IProductRepository are defined:

```
public interface IUnitOfWork
{
    IProductRepository Products { get; }
}
```

```
public interface IProductRepository
{
    string GetName(int id);
}
```
**.Facade.EF** project, where my Facade is implemented with EF:

```
public class UnitOfWork : IUnitOfWork
{
    private ApplicationDbContext _context;
    public IProductRepository Products { get; private set; }

    internal ApplicationDbContext Context { get { return _context; } }

    public UnitOfWork()
    {
        _context = new ApplicationDbContext();
        Products = new ProductRepository(this);
    }
}
```

```
public class ProductRepository : IProductRepository
{
    private ApplicationDbContext _context;
    public ProductRepository(UnitOfWork uow)
    {
        _context = uow.Context;
    }
    public string GetName(int id)
    {
        return _context.Products
            .Where(x => x.Id == id)
            .Select(x => x.Name)
            .FirstOrDefault();
    }
}
```
**.DemoApp** project where my application code should be. This project should only know about UnitOfWork and UserRepository and not about ApplicationDbContext class.
-     .DAL references Entity Framework 6.1.3.
-     .Facade does not reference anything.
-     .Facade.EF references .DAL project, .Facade project and Entity Framework 6.1.3.
-     .DemoApp references Facade and Facade.EF but NOT Entity Framework 6.1.3. NOR .DAL project. Even though EF assemblies are added to my bin folder on build, EF is not directly referenced by this project.

With **.NET Framework 4.6.x.**, if I try try to code against ApplicationDbContext in DemoApp, it tells me that class is not defined and is not providing me any usings to be added which is expected behavior.

<img width="652" alt="ssycy 1" src="https://cloud.githubusercontent.com/assets/5385262/16345823/3d261792-3a44-11e6-98fa-bcc4fa603253.png">

If I attempt to do the same with **.NET Core 1.0 RC2** (with Entity Framework Core 1.0 RC2), ApplicationDbContext is accessible from .DemoApp without adding direct reference to .DAL project which completely destroys my attempt to hide implementation details. 

<img width="576" alt="exg6o 1" src="https://cloud.githubusercontent.com/assets/5385262/16345872/8abfbef4-3a44-11e6-85d1-79feb6da674d.png">

.DAL project is not directly referenced by .DemoApp project - why am I allowed to see classes from it there? 
Is this expected behavior?
Is there a way to make .NET Core projects to have the same behavior as .NET Framework 4.6.x projects?

**Comment by blackdwarf** [comment]
@atuzovic can you please reopen this issue on aspnet/Tooling? We will take if from there. Thanks!

**Comment by mrpmorris** [comment]
Your project is being referenced indirectly, this is as designed. What you can do is right-click the project in the middle and select "Edit", then find the relevant <ProjectReference> node and include the XML attribute PrivateAssets="All"
