### ISSUE TITLE
dotnet-hosting-2.0.6 package not available

### ISSUE THREAD

**Issue by rlynch984** [dotnet/core#1410]
# dotnet-hosting-2.0.6 package not available on RHEL/CentOS after installing packages-microsoft-prod.rpm

dotnet-hosting-2.0.6 package is not available, even though dotnet-runtime-2.0.6 and aspnetcore-store-2.0.6 are.  Can this be added?

After installing packages-microsoft-prod.rpm, if you try to install dotnet-hosting-2.0.6, you receive an error saying 'No package dotnet-hosting-2.0.6 available'

**Comment by Petermarcu** [comment]
@Eilon @joeloff

**Comment by joeloff** [comment]
@JunTaoLuo

**Comment by Eilon** [comment]
@muratg - can you take a look?

**Comment by leecow** [comment]
I do see it on the feed - https://packages.microsoft.com/rhel/7.3/prod/. Checking if I can see it from a CentOS machine ...

**Comment by leecow** [comment]
Good to go now: 

```
[leecow@lbc-centos ~]$ yum list | grep dotnet-hosting
dotnet-hosting-2.0.0.x86_64                 2.0.0-1                    packages-microsoft-com-prod
dotnet-hosting-2.0.3.x86_64                 2.0.3-1                    packages-microsoft-com-prod
dotnet-hosting-2.0.4.x86_64                 2.0.4-1                    packages-microsoft-com-prod
dotnet-hosting-2.0.5.x86_64                 2.0.5-1                    packages-microsoft-com-prod
dotnet-hosting-2.0.6.x86_64                 2.0.6-1                    packages-microsoft-com-prod
```

**Comment by JunTaoLuo** [comment]
@leecow What was the issue here?

**Comment by leecow** [comment]
File was in the rhel/7.3 and rhel/7.4 repos but had not propped to rhel/7. Not sure why so will keep an eye on things during the next release.
