### ISSUE TITLE
Image Processing is not available in .Net Core 2.0

### ISSUE THREAD

**Issue by RanaMujahid** [dotnet/core#1411]
I want to resize image and clone into multiple images. I found solution in .Net framework or .Net Core 1.0 as ImageResizer or System.Drawing but i can't found any solution in .Net Core 2.0. Is there any suggestion?

**Comment by benaadams** [comment]
One Windows you can use the NuGet Package Microsoft.Windows.Compatibility https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack which will give you access to System.Drawing

Or you could use something like [SixLabors.ImageSharp](https://github.com/SixLabors/ImageSharp) which is fully .NET Standard and on NuGet

**Comment by jherby2k** [comment]
ImageSharp is the way to go. Its supposed to leave preview once netcore 2.1 is finished (package depends on System.Memory extensively which is still in preview). API is mostly stable at this point.

**Comment by Petermarcu** [comment]
Yes, as @benaadams mentioned, it is available in the Windows Compat Pack for .NET Core: https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack and as @jherby2k pointed out, there are other libraries in the ecosystem that provide a really nice story here.
