### ISSUE TITLE
Inconsistent collection navigation property projection

### ISSUE THREAD

**Issue by joshmouch** [dotnet/core#1426]
I have the following in latest versions of EF Core:

```
var entityOnes = await dbContext.EntityOnes.Where(blah)
    .Include(a => a.EntityTwos)
    .Include(a => a.EntityThrees)
    .ToListAsync();
```

After this executes, the following works fine, as expected:

```
var test = entityOnes[0].EntityTwos[0].EntityThrees[0];
```

However, the following could possibly throw a null exception because the `EntityThrees` property is null:

```
var test = entityOnes[0].EntityTwos[1].EntityThrees[0];
```

It seems like the `EntityThree` collection property only gets set if there are values to add to the collection.  If the collection is empty, then it leaves the property null.

This seems like inconsistent behavior to me.  I'm initializing these properties as null as a safeguard to let me know if EntityFramework has already projected values onto the relationship or not.

For example, if the following throws a null exception, then I know that I forgot to add EntityTwo as an Include() in EF query:
```
var test = entityOnes[1].EntityTwos[0];
```

**Comment by Petermarcu** [comment]
@divega

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFrameworkCore#11631
