### ISSUE TITLE
.NET Core roadmap beyond 2.1 

### ISSUE THREAD

**Issue by mcwienczek** [dotnet/core#1433]
Hey

I've been looking for some time in all the .NET Core repositories on github, and I couldn't find any indication about roadmap beyond 2.1. I would like to see some plans for both 2.2 and 3.0. It is concerning me that there is no roadmap because I don't know what this means for the future of .NET Core as a whole ecosystem.

So to the point:
1. What's the roadmap for 2.2 and 3.0?
2. Should I be concerned (as a developer that wants to bet on this platform) that there is no clear vision for the future of .NET Core? If there is a vision, could you point me to any document that describes it? 

Thanks in advance for help and for addressing my concerns.

**Comment by Petermarcu** [comment]
Our pattern is generally to focus on the release at hand. Once we're mostly complete, we start exploring what should be in the next minor and possibly the next major release. I would expect high level direction and thinking for whats in a 2.2 or a 3.0 to come out closer to when .NET Core 2.1 ships.

**Comment by Petermarcu** [comment]
@DamianEdwards @richlander @leecow

**Comment by richlander** [comment]
I was supposed to send a set of 2.2 plans to @DamianEdwards today, but neglected to. ;) The 2.1 release has been pretty consuming. I suspect we'll have a plan for 2.2 in the next couple weeks.

**Comment by mcwienczek** [comment]
Thanks a lot for help guys. That's enough for me. I just wanted some confirmation that Microsoft is still all-in for .NET Core. ;) Have a nice weekend

**Comment by DamianEdwards** [comment]
Rest assured, we're hard at work on the early stages of 2.2 planning and beyind, but as Peter said, we're focused on getting 2.1 out the door right now.

**Comment by leecow** [comment]
https://github.com/dotnet/core/blob/master/roadmap.md includes 2.2 and 3.0 mentions.
