### ISSUE TITLE
unable to run after upgrading to .net 2.0 => 2.1 [terminating with uncaught exception of type EEFileLoadException*]

### ISSUE THREAD

**Issue by davidparker** [dotnet/core#1435]
# terminating with uncaught exception of type EEFileLoadException*

when in ( visual studio code [mac os x] ) I go debug -->  run
It never runs, everything fails with:  terminating with uncaught exception of type EEFileLoadException*

All I have done is upgraded 2.0 -> 2.1   changed launch.json  to the following:

"program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/NetSo.dll",

Update nuget

removed DotNetCliToolReference  as they are no longer needed   ( now part of SDK )

Run  dotnet build  ( success )

and then run  

# General

I get no other output, as this seems to be more of a fail to launch issue, than a code issue
especially as no code changes have taken place,  and no code exceptions are thrown.   This seems more like that MACOS  wont run the new core framework.

I have attached the output from OSX  for clarity.  Any advice would be much appreciated.

[core-crash.mac.txt](https://github.com/dotnet/core/files/1903297/core-crash.mac.txt)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #17681](https://github.com/dotnet/coreclr/issues/17681) via [**ZenHub**](https://www.zenhub.com/)
