### ISSUE TITLE
Http Client performance drop in preview-2

### ISSUE THREAD

**Issue by rahul10992** [dotnet/core#1437]
Hello. I was trying out HttpClient benchmarking for net core 2.1 and well, I am seeing a serious drop in the HttpClient provided in preview 2.

for simple Get requests between 2 Windows Server 2016 VMs set up with network acceleration in Azure, 
1. for Preview-1 with the "AppContext.SetSwitch("System.Net.Http.UseManagedHttpClientHandler", true);" I get 75,000 requests/second
2. For preview-2 using the SocketsHttpHandler, the performance drops to 43,000 requests/second

Is there a reason for this performance drop?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29065](https://github.com/dotnet/corefx/issues/29065) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29066](https://github.com/dotnet/corefx/issues/29066) via [**ZenHub**](https://www.zenhub.com/)
