### ISSUE TITLE
Wrong reference path in NETStandard.Library.targets

### ISSUE THREAD

**Issue by cannehag** [dotnet/core#1440]
# After installing NetStandard.Library 2.0.2, a lot of warning occur.
NetStandard.Library.targets 2.0.2 have 
<Reference Include="$(MSBuildThisFileDirectory)\ref\Microsoft.Win32.Primitives.dll...
According to documentation MSBuildThisFileDirectory will include a final slash, thus giving a path with double slash and the error message 
The referenced component 'C:\Users\xxx\.nuget\packages\netstandard.library\2.0.2\build\netstandard2.0\\ref\Microsoft.Win32.Primitives.dll could not be found'

Version 2.0.1 does not have this issue since the targets file is including *.dll from another path
<ReferenceCopyLocalPaths Condition="'$(_NetStandardLibraryLibPath)' != ''" Include="$(_NetStandardLibraryLibPath)*.dll">

**Comment by elementalpete** [comment]
I experienced the same issue after upgrading (path in warning message contains a double slash, actual path has only a single slash).  Downgrading to 2.0.1 solved the issue for now.

**Comment by weshaggard** [comment]
Issue moved to [dotnet/standard #708](https://github.com/dotnet/standard/issues/708) via [**ZenHub**](https://www.zenhub.com/)
