### ISSUE TITLE
Finally not always called

### ISSUE THREAD

**Issue by mofibrian** [dotnet/core#1441]
# General

It seems that if you use a try/finally on its own, the finally block is never called. If you wrap the below invocation of fails/Fail in a try/catch, it behaves as you expect.

`dotnet --version`: 2.1.4
OS: Windows 10, macOS 10.13.2 & Linux (Ubuntu 16.04)

## Code
```fsharp
let fails _ =
    try
        failwith "try"
    finally
        failwith "finally"

[<EntryPoint>]
let main argv =
    fails ()
    0
```

```csharp
class Program
{
    static void Fail()
    {
        try
        {
            throw new Exception("try");
        }
        finally
        {
            throw new Exception("finally");
        }
    }

    static void Main(string[] args)
    {
        Fail();
    }
}
```

## Expected behaviour:
The "finally" exception is throw.

## Actual behaviour:
The "try" exception is propagated all the way up

**Comment by daniel-white** [comment]
sounds like an issue for the coreclr or rosyln teams.

**Comment by richlander** [comment]
See: https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/try-finally

It covers the behavior you are seeing. Right?

**Comment by joshfree** [comment]
Closing old issue.  Please feel free to re-open with more details.
