### ISSUE TITLE
Have you broken Kestrel configuration?

### ISSUE THREAD

**Issue by Mattacks** [dotnet/core#1442]
# Issue Title

Have you broken Kestrel configuration?

# General

In .Net Core 1.0 in Main you used to be able to '.Build()' on the builder to get the configuration resolved, in order to be able to use configuration in .UseKestrel(...)

Unless I am mistaken, that is now not possible in 2.1 - one can only use constants or read from files by hand.
Am I mistaken?

cheers

Matt

**Comment by benaadams** [comment]
Might want ti open this issue in https://github.com/aspnet/KestrelHttpServer
