### ISSUE TITLE
dotnet 2.1 preview1 package install error

### ISSUE THREAD

**Issue by joopip** [dotnet/core#1443]
OS: Ubuntu 16.04

#sudo apt-get install dotnet-sdk-2.1.300-preview1-008174

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 dotnet-sdk-2.1.300-preview1-008174 : Depende: dotnet-runtime-2.1.0-preview1-26216-03 pero no es instalable
Depende: aspnetcore-runtime-2.1.0-preview1-final pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

**Comment by leecow** [comment]
Ubuntu feeds should be up and running now for Preview 2.
