### ISSUE TITLE
Travis: Unable to locate package dotnet-sdk-2.1.300-preview2-008530

### ISSUE THREAD

**Issue by aguacongas** [dotnet/core#1444]
# Issue Title

I update my travis.yml to use 2.1.0-preview2 but the SDK is not found

# General

travis.yml:  

```
language: csharp
mono: none
dotnet: 2.1.300-preview2-008530
os:
  - linux
branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - develop
script: dotnet build
```

[log](https://travis-ci.org/aguacongas/chatle/jobs/366453017#L418):  
```
Installing .NET Core
$ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
$ export DOTNET_CLI_TELEMETRY_OPTOUT=1
Executing: /tmp/tmp.BK0NHLV9gi/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
BE1229CF
gpg: requesting key BE1229CF from hkp server keyserver.ubuntu.com
gpg: key BE1229CF: public key "Microsoft (Release signing) <gpgsecurity@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
4.81sW: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
3.59sE: Unable to locate package dotnet-sdk-2.1.300-preview2-008530
E: Couldn't find any package by glob 'dotnet-sdk-2.1.300-preview2-008530'
E: Couldn't find any package by regex 'dotnet-sdk-2.1.300-preview2-008530'
```

**Comment by leecow** [comment]
Update on this: Debian, Ubuntu, OpenSUSE and SLES feeds should be up and running for Preview 2 with a fix dotnet-host fix to resolve the compat. Update SDK build is 2.1.300-preview2-008533.

Still having trouble with the rhel feed used for RHEL, Fedora, CentOS and Oracle need another team to do some surgery to the repo so will need to wait for Monday.

**Comment by asadsahi** [comment]
@leecow might need to update https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.300-preview2 page as well?

**Comment by leecow** [comment]
Thanks, @asadsahi - will be re-enabling the various documentation locations today.

**Comment by leecow** [comment]
@asadsahi - looks like the https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.300-preview2 page is correctly referencing the updated SDK build now.
