### ISSUE TITLE
data-val-number is not added to int fields

### ISSUE THREAD

**Issue by thegodliek** [dotnet/core#1445]
As the title says, the unobtrusive data tag for int fields are not added to the html output, for example:

the view model class:
`public int Test { get; set; }` 

the razor view:
`<input asp-for="Test" class="form-control" />`

the html result:
`<input class="form-control" data-val="true" data-val-required="The Test field is required." id="Test" name="Test" value="" type="number">`

The problem is that now if I enter a text that is not a number, I'm getting the default jquery.validate message " Please enter a valid number. ", but if I manually add the data-val-number="some message", I get correctly the message I want.

Any thoughts?

thank you

**Comment by sven5** [comment]
Why not simply add the data-val-number attribute in your View like this:

```aspx
<input asp-for="Test" class="form-control" data-val-number="Must be NUMBER!"/>

**Comment by thegodliek** [comment]
I'm currently doing that @sven5, but my question is why isn't that done automatically by the framework just like MVC5.

**Comment by danroth27** [comment]
This is tracked by https://github.com/aspnet/Mvc/issues/7652
