### ISSUE TITLE
VSTS .NET Core Tool Installer for 2.1-Preview 2 problem

### ISSUE THREAD

**Issue by sven5** [dotnet/core#1447]
The .NET Core Tool Installer references [releases.csv](https://github.com/dotnet/core/blob/master/release-notes/releases.csv). 
It says that I need the version string "2.1.0-preview2" to target 2.1 Preview 2. But this is not working, I had to insert version string **2.1.300-preview2-008530**.

See 
![image](https://user-images.githubusercontent.com/8734624/38808788-a3289d3a-4181-11e8-8379-faefe21773b5.png)

Regards
Sven

**Comment by richlander** [comment]
PTAL @preetikr

**Comment by leecow** [comment]
Need to add 2.1.300-preview2-008533 as that's the re-release we just finished.
