### ISSUE TITLE
Documentation on C# version support

### ISSUE THREAD

**Issue by thiagomajesk** [dotnet/core#1449]
Hi, is there a table comparing dotnet core version along with C# support?
I'm kinda lost trying to find documentation on this (apart from official announcements).
I think would be nice to have this explicit somewhere in the docs - maybe with the roadmap too 
(if there is, somebody please tell me where).

**Comment by omajid** [comment]
Possible duplicate of https://github.com/dotnet/docs/issues/4154 ?

**Comment by omajid** [comment]
And for self-documentation, https://github.com/dotnet/cli/issues/8871 is about the `dotnet` command telling users which C# language version it supports.

**Comment by Petermarcu** [comment]
@jaredpar @MadsTorgersen

**Comment by richlander** [comment]
Work is progressing on this ... https://github.com/dotnet/core/pull/1454

We have another work item to generate markdown from releases.json.

**Comment by Petermarcu** [comment]
@richlander @jaredpar anything else left to track here?

**Comment by leecow** [comment]
Language version supported added to [releases.json](https://github.com/dotnet/core/blob/master/release-notes/releases.json) which is used to populate the download pages such as https://www.microsoft.com/net/download/dotnet-core/2.1.
