### ISSUE TITLE
Download links for 1.1.x OSX SDK install broken on microsoft.com

### ISSUE THREAD

**Issue by adcreare** [dotnet/core#1451]
# Issue Title
Various download links on microsoft.com for dotnet core 1.1 OSX sdk installers are broken. 

# General
For example: the macOS SDK installer link on https://www.microsoft.com/net/download/dotnet-core/sdk-1.1.8 points to https://www.microsoft.com/net/download/thank-you/dotnet-sdk-1.1.8-macos-x64-installer which in turn triggers a download from https://download.microsoft.com/download/6/5/F/65F1653E-F835-4DE3-BB36-F324D3925F32/dotnet-sdk-1.1.8-osx-x64.pkg

however that page can't be reached. 
There are several versions of the 1.x SDK installer for OS X that are like this. 

Happy to provide more examples if that helps get it fixed.

**Comment by richlander** [comment]
Thanks for the report. I sent it on to the right folks.

**Comment by ericwj** [comment]
Multiple versions are affected.
I can reach  
[Thanks for downloading .NET Core Hosting Bundle 2.0.7 (Installer for Windows)](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.7-windows-hosting-bundle-installer)  
but I get prompted what I want to do with a 1.2 kb `.exe.txt` file by Edge and the link on the page [Try again](https://download.microsoft.com/download/A/9/F/A9F8872C-48B2-41DB-8AAD-D5908D988592/DotNetCore.2.0.7-1-WindowsHosting.exe) yields 404.

**Comment by adcreare** [comment]
Its been a couple of weeks? Is there someone else I should contact about getting these links fixed?

**Comment by Petermarcu** [comment]
@leecow @livarcocc
