### ISSUE TITLE
Does the  “dotnet publish” have no “/subsystem:windows”  ?

### ISSUE THREAD

**Issue by maikebing** [dotnet/core#1452]
like this :
https://stackoverflow.com/questions/45200378/how-to-hide-kestrel-console
we can use  
`editbin.exe /subsystem:windows myself-contained.exe`
 
 Is there such a parameter as below? If not, can you add it? I think it's very necessary

`dotnet publish    My.csproj -c Release  -r   win-x64 --self-contained     /subsystem:windows   `

**Comment by richlander** [comment]
Great q. We intend to provide a first-class experience for this in an upcoming release (not 2.1). We also intend to make it possible to provide your own exe, for signing and icons.

I ported the request to the repo where the work will be done. Feel free to engage there. Closing this issue.

**Comment by emes001** [comment]
In the release notes, there is a known issue listed for **Windows Server Hosting bundle**. Has the correct install file be updated on the [downloads ](https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7) page? If not, can the link on that page be removed until a new, correct binary is published?
