### ISSUE TITLE
dotnet 2.1-preview 2 test unable to load dependent project libraries

### ISSUE THREAD

**Issue by lunim** [dotnet/core#1462]
Hello,

I have a simple xunit test project that references a single .net core 2.1 app.  Both define `<TargetFramework>netcoreapp2.1</TargetFramework>`.  The app references System.CommandLine: `<PackageReference Include="System.CommandLine" Version="0.1.0-preview2-180412-1" />` and includes the proper myget source in order to restore it. 

I can build the app without issue, but when I attempt to run the tests, I get the error: 
> Could not load file or assembly 'System.CommandLine, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

If I add the PackageReference to the test .csproj, the tests are able to run correctly.  The tests work without issue with .Net Core 2.0.

I am running the tests both locally and in the docker container 'microsoft/dotnet:2.1-sdk-alpine', both have the same issue.

**Comment by Petermarcu** [comment]
So the app builds and runs just fine? Its just the unit testing that doesn't work? @kendrahavens Do you know the best people to loop in to help here?

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1555
