### ISSUE TITLE
DotNetCore Hosting Bundle Installer broken link/file on microsoft.com/net/download

### ISSUE THREAD

**Issue by lukos** [dotnet/core#1463]
If you follow the link to the Windows Hosting Bundle Installer on this [download](https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7) page, it appears to load a page, which attempts a file download in the background but the file link is broken and it doesn't download.

Unfortunately, there is no obvious workaround to this.

The error in Chrome is: The web page at https://download.microsoft.com/download/A/9/F/A9F8872C-48B2-41DB-8AAD-D5908D988592/DotNetCore.2.0.7-1-WindowsHosting.exe might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by lukos** [comment]
(Actually, I found a workaround by downloading 2.0.6 instead)

**Comment by Petermarcu** [comment]
@joeloff is this a known issue tracked anywhere?

**Comment by joeloff** [comment]
Yes, we have another thread on it at https://github.com/aspnet/IISIntegration/issues/493#issuecomment-382485998

**Comment by Petermarcu** [comment]
Ok, closing here in favor of that one.
