### ISSUE TITLE
Async suffix

### ISSUE THREAD

**Issue by lukepuplett** [dotnet/core#1464]
# Should the Async suffix convention be used in 2018?

I'm so sorry for bringing this up, its not an issue as such, its debatable, but this might be the best forum for it. 

Should .NET and other open-source libraries continue to append `Async` on awaitables?

# General

My team here have begun to drop it; I always wondered whether this might happen but thought it premature until I read this.

https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

What do we feel is appropriate guidance in 2018?

Thanks

**Comment by MarcoTheFirst** [comment]
I totally agree. There are enough indications that a method is async:

1. Return type is Task / Task<>
2. Code completion presents an awaitable hint 
3. the IDE will warn you by underlining in green 
4. Compiler will present a warning when task is not awaited. 

Using the Async suffix only makes sense if your API offers the same functionality in both flavors:

```
GetObject()
GetObjectAsync()
```

For any other use case, using the Async-suffix is as silly as adding a Lazy-suffix to any Lazy<> property:

`public Lazy<Customer> CustomerLazy.`

If you wouldn't do that, then don't use the Async suffix :-)

**Comment by lukepuplett** [comment]
Thanks for your answer.

For accuracy, number one isn't quite right, the compiler works by looking for an awaitable type, which is any type that has `TaskAwaiter GetAwaiter()` on it.

**Comment by joshfree** [comment]
Hey Folks,
I've moved this discussion to the dotnet/corefx repo where Framework Design Guidelines and API discussions occur - as you're more likely to get engagement there.  For more details on the CoreFX API and FDG see http://aka.ms/api-review

The new issue is https://github.com/dotnet/corefx/issues/31275
