### ISSUE TITLE
.Net Core 2 - Environment variables specified in PATH are not recognized in command executed by Process.Start("C:\script.bat").

### ISSUE THREAD

**Issue by MarcinSzyszka** [dotnet/core#1465]
Hi.
I would like to run scripts from .bat file in Xunit .Net Core Class Library but Process.Start(/.../) but environment variables specified in PATH are not recognized. I am using VS 2017 in admin mode. The same thing in console app on full framework works properly. Any solution?

Bes regards

**Comment by MarcinSzyszka** [comment]
Ok, my bad. I did not restart VS after installing tool which added new environement variable. Sorry about tha, everything works ok ;)

**Comment by Petermarcu** [comment]
Great
