### ISSUE TITLE
Urgent: Ubuntu 18.04 has moved to curl 4 isntead of 3

### ISSUE THREAD

**Issue by borgdylan** [dotnet/core#1466]
Some tools such as cmake in Ubuntu 18.04 are making use of libcurl4 instead of libcurl3. These two versions may not be installed at the same time. This means that one cannot have cmake and .NET COre isntalled at the same time. Please make a repo for 18.04 targeting libcurl4.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29220](https://github.com/dotnet/corefx/issues/29220) via [**ZenHub**](https://www.zenhub.com/)
