### ISSUE TITLE
Encoding GB2312 is not available on Windows.

### ISSUE THREAD

**Issue by stdcppdev** [dotnet/core#1467]
# Issue Title
Encoding GB2312 is not available on Windows.

# General
If we try to use HttpClient.GetString for a GB2312 response, it throws exception.
Actually GB2312 encoding is quite important for Chinese developers.
Please consider to fix it.

**Comment by eriawan** [comment]
@stdcppdev 
This is quite known problem in .NET Core because Some codepages needs to be registered. 
It's quite easy to fix.

If you are using .NET Core 2.0, in your app entry point (such as main), use this:

`System.Text.Encoding.RegisterProvider(new CodePagesEncodingProvider())`

**Comment by stdcppdev** [comment]
@eriawan 
Yes, it works. Thanks!
Close for resolved.
