### ISSUE TITLE
Link to DotNetCore.2.0.6-WindowsHosting.exe is broken on 2.1.104-sdk-download.md and 2.1.103-sdk-download.md

### ISSUE THREAD

**Issue by BJMdotNET** [dotnet/core#1471]
Both of these pages feature a link to https://download.microsoft.com/download/8/D/A/8DA04DA7-565B-4372-BBCE-D44C7809A467/DotNetCore.2.0.6-WindowsHosting.exe , but that link doesn't work:

https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.104-sdk-download.md
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.103-sdk-download.md

**Comment by leecow** [comment]
Thanks for pointing this out @BJMdotNET - fixed.
