### ISSUE TITLE
Bug in HttpWebRequest when call an endpoint that returns 302

### ISSUE THREAD

**Issue by mrquake** [dotnet/core#1473]
# Issue Title

When you call an endpoint that returns 302 the redirection url will have backslashes instead of forward slashes in "localpath".

# General

For example when you call Azure API using Fiddler or any other web debugging tool: "https://management.azure.com/subscriptions/xxx-xxx-xxx-xxxx/providers/Microsoft.Commerce/RateCard" with property parameters, token, etc...

It will return 302 and redirect to: https://ratecard.blob.core.windows.net/ratecards/xxxx-xxxx-xxxxx-xxxxx/MS-AZR-0017P/USD/en-US/False/2015-06-01-preview/yyyy-yyyyy-yyyyy-yyyyy.json

No problem whatsoever...

But when you make the request using .NET Core 1.1/2.0 HttpWebRequest... 
The redirection tries to call something like that:

https://ratecard.blob.core.windows.net/ratecards/xxxx-xxxx-xxxx-xxxxx%5CMS-AZR-0017P%5CUSD%5Cen-US%5CFalse/2015-06-01-preview/yyyy-yyyy-yyyy-yyyy-yyyy.json

With encoded backslashes instead of forward slashes....

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29318](https://github.com/dotnet/corefx/issues/29318) via [**ZenHub**](https://www.zenhub.com/)
