### ISSUE TITLE
Core SDK available for AspNetCore 2.1.0-rc1-30676

### ISSUE THREAD

**Issue by sven5** [dotnet/core#1477]
Hi,

Yesterday I installed Microsoft.AspNetCore.All  2.1.0-rc1-30676 nuget package but it doesn't work with Core SDK 2.1.0-preview3-26404-01.
Are you planning to release an updated Core SDK in the next days?

Thanks
Sven

**Comment by karelz** [comment]
Hello, looks like we missed this feedback and didn't reply. Very sorry for that!
I believe that official post-Preview .NET Core 2.1 versions are fine and there are not any troubles, so closing.
If you are still experiencing any troubles with latest released .NET Core 2.1 builds, please let us know.

**Comment by sven5** [comment]
@karelz Thanks for replying. It's already resolved.
