### ISSUE TITLE
Bad HResult error codes with IOException on Linux

### ISSUE THREAD

**Issue by Odirb** [dotnet/core#1478]
Hi,

When a file cannot be access because it's used by another process, or when a file cannot be created because it already exists, the System.IO.File Open function throws an IOException with an invalid HResult value.

Sample code below returns 11 (EAGAIN?) instead of -2147024864 (ERROR_SHARING_VIOLATION). For a file in use it returns 17 (EEXIST?) instead of -2147024816 (ERROR_FILE_EXISTS). 

Since HResult is ok for a file not found (-2147024894 correspond to ERROR_FILE_NOT_FOUND) , it seems there is some missing mapping for conversion between Linux error code and Windows error code.

| Test | HResult on Windows | HResult on Linux | Result  |
| --- | --- | --- | --- |
| File in use | -2147024864 | 11 | Invalid |
| File already exists | -2147024816 | 17 | Invalid |
| File not found | -2147024894 | -2147024894 | Correct |

This problem is reproductible with dotnet core 2.0 running on an Ubuntu 16.04

# Code sample

```c#
using System;
using System.IO;

namespace FileInUseException
{
    class Program
    {
        static void Main(string[] args)
        {
            var file = @"locked.bin";
            using (File.Create(file))
            {
                Console.WriteLine("=== File in use");
                try
                {
                    File.OpenRead(file);
                    Console.WriteLine("No exception! Weird...");
                }
                catch (IOException ex)
                {
                    Console.WriteLine($"Get an IOException with code {ex.HResult}, message {ex.Message}");
                }
            }

            Console.WriteLine("\n=== File already exists");
            try
            {
                File.Open(file, FileMode.CreateNew, FileAccess.ReadWrite);
                Console.WriteLine("No exception! Weird...");
            }
            catch (IOException ex)
            {
                Console.WriteLine($"Get an IOException with code {ex.HResult}, message {ex.Message}");
            }


            Console.WriteLine("\n=== File not found");
            try
            {
                File.OpenRead("Not Here.bin");
            }
            catch (IOException ex)
            {
                Console.WriteLine($"Get an IOException with code {ex.HResult}, message {ex.Message}");
            }
        }
    }
}
```

**Comment by benaadams** [comment]
Probably want to open issue in https://github.com/dotnet/corefx?

**Comment by Odirb** [comment]
Thanks benaadams, I have copy the issue in corefx.

Sorry for having post in the wrong repository.

**Comment by benaadams** [comment]
Don't worry, it would have been routed to the right repository. Its just faster if you start there :)
