### ISSUE TITLE
Body have enum with invalid code

### ISSUE THREAD

**Issue by FabioMorcillo** [dotnet/core#1479]
Using .NET Core 2.0  having enum from body of method post with:

**Enum**
public enum FormaPagamento
{
     DEBITO = 0,
     CREDITO = 1,
     CAIXA = 2
}

**ViewModel**
public class ViewModel
{
     [Required]
     public FormaPagamento FormaPagamento { get; set; }
}

**Controller**
[HttpPost]
public Object Post([FromBody]ViewModel viewModel)
{
     if (ModelState.IsValid)
     {
          return viewModel.FormaPagamento.ToString();
     }

     return "Forma de pagamento inválida";
}

When send method post with existing values DEBITO or code 0 mode state is correct true and if send incorrect value DEBIT model state is correct to false, but when send not existing code 5, model state is true but this code don´t exist in enum and i think this is a bug.

Thank you,

**Comment by guilhermeluizsp** [comment]
An enum is basically just a number under the covers. You can assign any number and it would still be valid. Take a look at this example:

```
public enum Color
{
    Red = 1,
    Green = 2,
    Blue = 3
}

Color red = Color.Red;

/*
this is completely valid and won't throw an exception,
even though the enum doesn't define any element with value 65.
*/
Color foo = (Color)65;
```

When you use the ```[Required]``` attribute, you are just asserting that is has a value. It doesn't matter what value is (in the case of an enum), as long as there is one.

If you want to make sure the value is valid, you could decorate your property with the built-in ```[EnumDataType]``` attribute:

```
public class ViewModel
{
    [Required]
    [EnumDataType(typeof(FormaPagamento))]
    public FormaPagamento FormaPagamento { get; set; }
}
```
