### ISSUE TITLE
[Question] Resolving runtime assemblies for .NET Core application

### ISSUE THREAD

**Issue by jp2masa** [dotnet/core#1480]
## Scenario

I have a .NET Core application, and I need to get the full paths for all runtime assemblies. The application is self-contained, targets .NET Core 2.0 and the runtime identifier is win-x86. I need to get the runtime assemblies in an MSBuild target.

## What I've tried

1. Creating an MSBuild target which depends on `ResolveReferences;_ComputeNetPublishAssets`, and use `@(ResolvedAssembliesToPublish)`, but it contains some pdb files. I can filter them by extension, but is it the right way to do this?

2. Creating an MSBuild task using `DependencyContext`, but I have no idea how to resolve the relative paths (I tried using NuGet.ProjectModel to resolve the libraries, but no success).

What is the correct way of resolving the full paths for all runtime assemblies?

Any help would be appreciated.

**Comment by joshfree** [comment]
@dsplaisted
