### ISSUE TITLE
dotnetsay - nuspec project url

### ISSUE THREAD

**Issue by dazinator** [dotnet/core#1483]
Consider adding a project url to the nuspec of the DotNetSay tool: https://www.nuget.org/packages/dotnetsay/
 
I was pointed to the tool via https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/ which directed me to the nuget package on nuget.org - but then have to google separately to find the source code.

**Comment by richlander** [comment]
Good point. Me and @KathleenDollard will fix that.

**Comment by karelz** [comment]
@richlander @KathleenDollard can you please make the change?

**Comment by richlander** [comment]
It appears that this is fixed. The sourcecode link was enabled on the last upload.

https://www.nuget.org/packages/dotnetsay/
