### ISSUE TITLE
Default HttpClient not using configured web proxy

### ISSUE THREAD

**Issue by jagalves** [dotnet/core#1484]
# Issue Title

When using a web proxy setup (in my case Fiddler), HttpClient is not using it by default.

This behavior is different between .net core 2.0 and in 2.1 preview 2.

# General

With fiddler running, the following code will try to make a request to "http://localhost.fiddler:65530" (I'm assuming nothing is running on that port) and print the result or the exception message:

```
using System;
using System.Net.Http;

namespace HttpC
{
    class Program
    {
        static void Main(string[] args)
        {
            var http = new HttpClient();

            try
            {
                var response = http.GetStringAsync("http://localhost.fiddler:65530").GetAwaiter().GetResult();

                Console.WriteLine(response);
            }
            catch (Exception ex)
            {
                Console.WriteLine("exception: " + ex.Message);
            }
        }
    }
}

```

How to reproduce:
1. Start fiddler making sure it's capturing all requests
2. Setup a dotnet core 2.0 console app and add the code provided
3. Run -> the error is Response status code does not indicate success: 502 (Fiddler - Connection Failed).
4. Change to dotnet core 2.1 preview 2
5. Run -> the error is No such host is known

Note1: in browsers localhost.fiddler works
Note2: I tried the full hostname instead of "localhost.fiddler" and HttpClient still didn't use the proxy.

Link to fiddler: https://www.telerik.com/fiddler

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #29396](https://github.com/dotnet/corefx/issues/29396) via [**ZenHub**](https://www.zenhub.com/)
