### ISSUE TITLE
Problem deploy apps on Raspberry

### ISSUE THREAD

**Issue by Marcel-B** [dotnet/core#1485]
I've tried to deploy and run an app on a Raspberry Pi 3 B device. I've followed the install instruction and create an Emtpy .net core Web App (Hello world). I've ran "dotnet publish . -r linux-arm" and copied the release to the Rapberry device. 

After I made the program file executeable and execute it, I got the following error message:

Error:
  An assembly specified in the application dependencies manifest (FooBar.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'

**Comment by Petermarcu** [comment]
Can you try a simple console helloworld application? My guess is that you don't have the ASP.NET Core Runtime installed that matches the build you are targeting.

**Comment by Petermarcu** [comment]
That error tells me that you are not running `dotnet publish -r linux-arm` to create the application or that you are not copying the app from the output folder of that app. Can you confirm?

**Comment by Marcel-B** [comment]
I created the project on my Mac. Then I ran the command `dotnet publish -r linux-arm -c Release`. Then I copied the whole folder `linux-arm `, which is in the path `HelloWorld/bin/Release/netcoreapp2.0/linux-arm`, to the Raspberry.

**Comment by Petermarcu** [comment]
There should be a publish folder under there that is what you need to use.

**Comment by Marcel-B** [comment]
Okay. Thank you for your help up to here. I opened an issue on Github.

**Comment by Marcel-B** [comment]
Omg. Ok. It works. Tanks for your help!

**Comment by Petermarcu** [comment]
Did that fix the issue for you? (copying the publish folder output?)

**Comment by Petermarcu** [comment]
This is one of the places where people get confused a lot and something I'm hoping we can address in a future update. @livarcocc @KathleenDollard

**Comment by livarcocc** [comment]
Agreed. We have unify build/publish in our backlog.

**Comment by KathleenDollard** [comment]
Agreed.

@Marcel-B if you blog your experience, helping people around pitfalls, let us know.
