### ISSUE TITLE
Linux install instructions for .NET Core 2.1 on Fedora */CentOS/SLES still installs libunwind

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/core#1488]
The Linux install instructions for several of the Linux distros still specify to install libunwind, which I believe is no longer required as of .NET Core 2.1. The other dependencies should probably be checked as well.

https://www.microsoft.com/net/download/linux-package-manager/fedora26/sdk-2.1.300-preview2
https://www.microsoft.com/net/download/linux-package-manager/fedora25/sdk-2.1.300-preview2
https://www.microsoft.com/net/download/linux-package-manager/centos/sdk-2.1.300-preview2
https://www.microsoft.com/net/download/linux-package-manager/opensuse/sdk-2.1.300-preview2

**Comment by leecow** [comment]
Thanks Gregg, submitted an issue on the site repo to have those steps removed.

**Comment by Petermarcu** [comment]
Looks like this can be closed now.
