### ISSUE TITLE
Vulnerabilities found in microsoft/aspnetcore:2.0.5

### ISSUE THREAD

**Issue by yb101** [dotnet/core#1489]
# Issue Title

Vulnerabilities found in microsoft/aspnetcore:2.0.5

# General

Our company is using Clare docker scanning tool for docker image scanning before releasing to Production. We did a base image scanning for microsoft/aspnetcore:2.0.5 and found quit a lot vulnerabilities as shown in the screenshot attached.

Wondering if there is a way to patch the image. I also checked on other version. They all can not pass the scanning. Hope someone call help out here. Thanks.

![1](https://user-images.githubusercontent.com/30830804/39501083-6452e478-4deb-11e8-8b92-4c00c7cd1e77.png)
![2](https://user-images.githubusercontent.com/30830804/39501084-64c9f5fe-4deb-11e8-8d13-6da7a736776d.png)

**Comment by richlander** [comment]
We have been monitoring the vulnerability situation with Debian images. These vulnerabilities are a function of using Debian.

You can see a significant improvement in reported vulnerabilities from [.NET Core 2.0.5](https://anchore.io/image/dockerhub/678967989e777f8e6404e9b38e9585a5735be06234a3bba985eb6b39a560dc3b?repo=microsoft%2Fdotnet&tag=2.0.5-runtime#security) to [.NET Core 2.0.7](https://anchore.io/image/dockerhub/8114abd3b8bebcc43750167a82bdeda55cde3697604b1fd7da249dbda0d7daf5?repo=microsoft%2Fdotnet&tag=2.0.7-runtime#security). This improvement isn't a function of .NET Core itself, but of taking a dependency on later versions of the underlying [Debian image](https://anchore.io/image/dockerhub/8626492fecd368469e92258dfcafe055f636cb9cbc321a5865a98a0a6c99b8dd?repo=library%2Fdebian&tag=stretch#security). We move our images forward with each change to Debian.

In terms of guidance, you've got a four choices:

- Monitor Debian closely and hope that the situation improves over time. In general, I expect that vulnerabilities will ebb and flow, so this guidance isn't that great. You'd have to spend time analyzing each vulnerability and build a threat model around it.
- Adopt one of the other flavors of images that we provide: [Ubuntu 18.04](https://anchore.io/image/dockerhub/710c2dc47c1389ea2e5f1c3efbefb6dc4d03e147bdc4a26f809bda7f7eee877b?repo=microsoft%2Fdotnet&tag=2.1-runtime-bionic#security) and [Alpine 3.7](https://anchore.io/image/dockerhub/678967989e777f8e6404e9b38e9585a5735be06234a3bba985eb6b39a560dc3b?repo=microsoft%2Fdotnet&tag=2.1-runtime-alpine#security). Only problem with those choices is that they are only offered starting with .NET Core 2.1. We're working as hard as possible to make the .NET Core 2.1 RTM date not that far off, aiming for H1 2018.
- Build your own Linux images, selecting a distro that matches your patching needs. Alpine, Centos and RHEL are key options to look at.
- Switch to Windows containers.

This whole space has been a challenge for us. With Windows, our traditional deployment platform, we've had complete control (as a company) on patching velocity. With Linux, we cannot do much with CVEs that are marked "No Fix available". That's highly suggestive that the non-Docker variation of these Linux distros have the same CVE, too.

I'm happy to talk with you on the phone to discuss that in more detail. I've provided basic insight on the situation. I hope that's helpful.

**Comment by yb101** [comment]
@richlander 

Thanks for the prompt response. As you advised, we will try out with .Net Core 2.0.7 or to build our own image with the distro which we have in the company.

**Comment by richlander** [comment]
Can you share which distro that is?

**Comment by yb101** [comment]
Our company has one RHEL hardened base image. So based on it, we were able to include dotnet core runtime package and 2 dependent rpm pkgs, and build our own base image for dotnet core program.

**Comment by h3smith** [comment]
Now that 2.1 is out, curious if anyone can share their Dockerfile for Ubuntu or RHEL

**Comment by Petermarcu** [comment]
Looks like the original request here was answered so I'm going to close this now. If there are follow ups, please open new issues specific to those.
