### ISSUE TITLE
dotnet publish fails for Raspberry Pi: detected package downgrade

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/core#1491]
# Issue Title

dotnet publish produces **error NU1605** when publishing for the Linux-ARM platform.

# More info

When publishing for Raspberry Pi with this command:
```
dotnet publish -r linux-arm
```
the build doesn't complete and **lots of errors like this are shown** in the build output:

**F:\Repos\Plotty\CodeGeneration\CodeGen.Intermediate.Tests\CodeGen.Intermediate.Tests.csproj : error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.  [F:\Repos\Plotty\CodeGeneration\Code Generation.sln]**

# Snapshot

![image](https://user-images.githubusercontent.com/3109851/39572081-226413fa-4ece-11e8-8714-3adb1ad38ecc.png)

# General

The problem doesn't occur when with either `dotnet build` or `dotnet publish` (without the `-r linux-arm option`).

You can reproduce the issue cloning the following repository:

https://github.com/SuperJMN/CodeGeneration

# Version

Microsoft (R) Build Engine version **15.6.84.34536** for .NET Core
Under Windows 10 Fall Creators Update

**Comment by richlander** [comment]
Thanks for the report. It's not specific to linux-arm. It is specific to publishing by RID. I'll get some folks to PTAL.

**Comment by karelz** [comment]
@richlander was there any follow up here? Who should take a look?
@SuperJMN do you still face the problem?

**Comment by karelz** [comment]
No response, closing.
@SuperJMN if you still hit the issue, feel free to repopen. Thanks!
