### ISSUE TITLE
Looking for Signed Assymblies

### ISSUE THREAD

**Issue by TrueCodePoet** [dotnet/core#1492]
# Are Signed Assemblies available?
After looking at a few download sites as well as here I can't find Signed versions.  Where can I find signed versions.  Is this no longer implemented?
Currently this is a requirement in our infrastructure.

Thanks

**Comment by Petermarcu** [comment]
Where are you looking. Everything published should be signed.

**Comment by TrueCodePoet** [comment]
I have looked here: https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.5
as well as here: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md

When I download and unzip the file and then run >sn -vf I get

"does not represent a strongly named assembly"

**Comment by Petermarcu** [comment]
Is there a reason you need to strong name verify these? They are all authenticode signed.

**Comment by joshfree** [comment]
Closing this old issue.  Please feel free to reactivate with more details.
