### ISSUE TITLE
'libhostpolicy.so' required to execute the application was not found

### ISSUE THREAD

**Issue by emanueleleoni** [dotnet/core#1493]
I created an MVC .Net Core 1.1 application. It works on windows and I'd like to run in my raspberry py too.
But It doesn't work.

## Environment:
1. VS17 enterprise
2. Mvc .net core 1.1
3. Raspberry pi with Debian 9.4
4. Repo on github

## Expected behavior
After publishing in windows for linux-arm I have pull my repo into raspberry, but when 
I run 
`dotnet  myapp.dll`
I have the error:
_A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in [path]_

## Actual behavior
It doesn't work and I don't know how to solve

**Comment by Petermarcu** [comment]
Hi @emanueleleoni are you still hitting this? This usually happens because the folder that is copied to the raspberry pi isn't the published folder and is missing some stuff.

**Comment by joshfree** [comment]
Closing out this old issue with no recent response.  Please feel free to reactivate with more information.  Thanks
