### ISSUE TITLE
Add AOP capabilities

### ISSUE THREAD

**Issue by pleandre** [dotnet/core#1495]
Hello all,

Currently their are not many ways to do AOP (Aspect Oriented Programming) in .net core. The only way I see is to use libraries like Postsharp / Fody which adds some compilation steps ([MSIL rewritting](http://doc.postsharp.net/how-it-works)) and complex plumbing.

I think it would be great to have some functionalities embedded in .net core for aspect weaving.

It would make it more simple to create some custom attributes and logic (and be able to use it like annotations in java / spring aop / aspectJ) 
e.g. be able to develop a [Schedule], a [Caching], a [RegisterToEventBus] attribute easily with custom logic and injecting code at compilation time on methods, class, etc. tagged (adding code before a method runs, after, on return value, on a getter, setter, exception, etc.. at compilation time)

Is it something you think should be handled by dotnet core ?

Thank you,
Pierre

**Comment by joshfree** [comment]
This issue was moved to dotnet/corefx#31336

**Comment by SychevIgor** [comment]
In theory, microsoft create https://github.com/dotnetcore/AspectCore-Framework
but we need english version

**Comment by Expecho** [comment]
> In theory, microsoft create https://github.com/dotnetcore/AspectCore-Framework
> but we need english version

I am not sure this is officially backed by Microsoft!
