### ISSUE TITLE
Hosting Bundle Installer 1.1.8 link on download page broken

### ISSUE THREAD

**Issue by riezebosch** [dotnet/core#1504]
Download page: https://www.microsoft.com/net/download/dotnet-core/runtime-1.1.8

Broken link: https://www.microsoft.com/net/download/thank-you/dotnet-runtime-1.1.8-windows-hosting-bundle-installer

Redirecting to: https://download.microsoft.com/download/1/B/8/1B80E25B-316E-4DFB-9707-DB758681F175/DotNetCore.1.0.10_1.1.8-WindowsHosting.exe

Working link: https://download.microsoft.com/download/1/B/8/1B80E25B-316E-4DFB-9707-DB758681F175/DotNetCore.1.0.11_1.1.8-WindowsHosting.exe

The same issue applies to filename mentioned in https://github.com/dotnet/core/blob/master/release-notes/releases.json#L72 (and probably the version mentioned in https://github.com/dotnet/core/blob/master/release-notes/releases.csv#L8)

**Comment by leecow** [comment]
Thanks @riezebosch - releases files have been updated and we'll get this propagated to the download pages. 

cc @rowanmiller
