### ISSUE TITLE
.NET Core 2.1.0 RC 1

### ISSUE THREAD

**Issue by leecow** [dotnet/core#1506]
# .NET Core 2.1.0 RC1

[Blog post](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/)
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/Preview/2.1.0-rc1.md)

Please report any issues you find with 2.1 RC 1, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by NinoFloris** [comment]
Is there a soft guestimate on RTW date?

**Comment by RoySalisbury** [comment]
Finally found it after making some assumptions based on file names and other download locations...

https://download.microsoft.com/download/B/1/9/B19A2F87-F00F-420C-B4B9-A0BA4403F754/dotnet-sdk-2.1.300-rc1-008673-linux-arm.tar.gz

Why make it so hard to find this stuff?

**Comment by leecow** [comment]
Sorry @RoySalisbury, we'll get it worked into the download pages.

**Comment by Petermarcu** [comment]
@RoySalisbury there should be one without the build number in it. @leecow sound like he has it under control :)

**Comment by RoySalisbury** [comment]
Still having fun trying to find this one:

aspnetcore-runtime-2.1.0-rc1-final-linux-arm.tar.gz

Since its not part of the SDK install I figure I need that installed separately.

**Comment by Petermarcu** [comment]
It should be in the SDK tar.gz and there should be an ASP.NET Core Runtime for ARM32 tar.gz @livarcocc @DamianEdwards @muratg . Can you confirm whether the ASP.NET runtime made it in or if thats something we need to address for RTM?

**Comment by RoySalisbury** [comment]
The only thing the SDK installed (for ARM) was

/opt/dotnet/shared/Microsoft.NETCore.App/2.1.0-rc1

and 

/opt/dotnet/sdk/2.1.300-rc1-008673

But the hash listing here shows it exists as a separate file (my guess is it is not part of the SDK or runtime for ARM).

https://dotnetcli.blob.core.windows.net/dotnet/checksums/2.1-RC1-Runtime-SHA.txt

**Comment by Petermarcu** [comment]
That may be true. It should have its own runtime tar.gz and should have been in the sdk. I opened this to track it: https://github.com/dotnet/cli/issues/9218

**Comment by dloukola** [comment]
I have been working with dotnet core 2.1 preview 2 and earlier without issues. Installing the dotnet core 2.1 rc-1 SDK causes my webapi projects that are targeting 4.6.1 framework to fail to load. 

It fails in the Startup at ConfigureServices when calling services.AddMvcCore().

The error message is: "the given key was not present in the dictionary"
It seems to error out in the stack trace at: "DefaultAssemblyPartDiscoveryProvider"

Uninstalling the 2.1 SDK makes everything work again, so it's definitely the issue.

Any ideas?

**Comment by laultman** [comment]
Never used the global.json and the MS docs are still referencing 1.0 preview. What is the current reference for 2.1 SDK that should be in the global.json. Is it: 2.1.300-rc1-008673
There should be a list somewhere with all the numbers - suggestion.

**Comment by leecow** [comment]
@laultman - 2.1.300-rc1-00873 and https://github.com/dotnet/core/blob/master/release-notes/releases.json is the 'canonical' release version list.

**Comment by laultman** [comment]
@leecow Thanks, great. I had the correct version but had no way to know. On another though, VS 2017 15.7.1 Stills spits out this statement: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.
I found a thread where they were talking about how to stop or hide these messages. I guess that has not been done. Thanks again for the info!

**Comment by Petermarcu** [comment]
Closing this now as .NET Core 2.1 has released.
