### ISSUE TITLE
.NET Core SDK 2.1.4 on Linux Ubuntu 18.04: Unable to locate package

### ISSUE THREAD

**Issue by jasonkenneth** [dotnet/core#1522]
# .NET Core SDK 2.1.4 on Linux Ubuntu 18.04: Unable to locate package

Given the link here:
https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-2.1.4

When I run the last step of the procedure:
`sudo apt-get install dotnet-sdk-2.1.4`

I get:

```Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1.4
E: Couldn't find any package by glob 'dotnet-sdk-2.1.4'
E: Couldn't find any package by regex 'dotnet-sdk-2.1.4'
```

Comparing the contents between say [17.10](https://packages.microsoft.com/ubuntu/17.10/prod/dists/artful/main/) and [18.04](https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/), it definitely looks like the package is missing.

**Comment by leecow** [comment]
@jasonkenneth - The 2.1.4 SDK instructions should not reference 18.04 as support for that version was only added in April. The 2.1.4 SDK is not available on the 18.04 feed which accounts for the error you see. The latest available .NET Core 2.0 Runtime and SDK for 18.04 is SDK 2.1.200 and Runtime 2.0.7. 

`sudo apt-get install dotnet-sdk-2.1.200` and you'll be good to go.

**Comment by jasonkenneth** [comment]
Thanks! I'm confused by the versioning scheme here. 

I just saw a link to a slightly newer release today: 
[`sudo apt-get install dotnet-sdk-2.1.300-rc1-008673`](https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-2.1.300-rc1)

(from https://www.hanselman.com/blog/AnnouncingNETCore21RC1GoLiveANDNETCore30Futures.aspx)

**Comment by akalcik** [comment]
@leecow Seems that the documentation is wrong here https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial

**Comment by Cloudmersive** [comment]
Is this fixed yet???

**Comment by petrroll** [comment]
Still an issue.

**Comment by Marthyn** [comment]
It seems to be unfixable with apt-get, but you can manually install, check here https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md#installation-from-a-binary-archive

**Comment by petrroll** [comment]
This fixes it: https://github.com/dotnet/core/issues/1889#issuecomment-417092809

**Comment by marcelo-maciel** [comment]
> This fixes it: [#1889 (comment)](https://github.com/dotnet/core/issues/1889#issuecomment-417092809)

I needed one more step as mentioned in [this issue](https://github.com/dotnet/cli/issues/9876)
`sudo add-apt-repository universe`

and then:
`sudo apt-get install dotnet-sdk-2.1`

**Comment by nbgucer** [comment]
If the following methods does not help, you could try following the documentation for Ubuntu 18.04 down below:

https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md#ubuntu-1804

**Comment by shpsyte** [comment]
Work for me !

**Comment by Alexmitter** [comment]
Had the same issue.
Removed 2.1 to update to 2.2. And the Repo was just gone. 
I had to do the manual steps from https://github.com/dotnet/core/issues/1889#issuecomment-417092809 and it fixed it. But this seems to be a general problem with the way MS adds the repo with that deb package since i have the exact same issue with the pwsh repo.

**Comment by cwash** [comment]
Looks like some package wiring was missing, but specifying a few transitive deps explicitly seemed to work for me...

> #!/bin/bash
> wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
> wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu55_55.1-7_amd64.deb
> sudo dpkg -i packages-microsoft-prod.deb
> sudo dpkg -i libicu55_55.1-7_amd64.deb
> sudo add-apt-repository universe
> sudo apt-get install -y apt-transport-https
> sudo apt-get update
> sudo apt-get install -y dotnet-sdk-2.1 dotnet-runtime-2.1 aspnetcore-runtime-2.1 dotnet-runtime-deps-2.1 libicu55
