### ISSUE TITLE
Dotnet core 2.1 rc-1 won't load projects targeting net461

### ISSUE THREAD

**Issue by dloukola** [dotnet/core#1525]
I have been working with dotnet core 2.1 preview 2 and earlier without issues. Installing the dotnet core 2.1 rc-1 SDK causes my webapi projects that are targeting 4.6.1 framework to fail to load.

It fails in the Startup at ConfigureServices when calling services.AddMvcCore().

The error message is: "the given key was not present in the dictionary"
It seems to error out in the stack trace at: "DefaultAssemblyPartDiscoveryProvider"

Uninstalling the 2.1 SDK makes everything work again, so it's definitely the issue.

I am targeting some aspnet core 1.* versions...maybe that is the issue?
Example:
Microsoft.AspNetCore.Authentication.JwtBearer (1.1.1)
Microsoft.AspNetCore.Diagnostics (1.1.1)
Microsoft.AspNetCore.Mvc (1.1.2)
Microsoft.AspNetCore.Routing (1.1.1)
Microsoft.AspNetCore.Server.IISIntegration (1.1.1)
Microsoft.AspNetCore..Server.Kestrel (1.1.1)

Any ideas?

**Comment by thyams** [comment]
Try replacing the AspNetCore 1.0 packages with AspNetCore.All (v2.0.8),

**Comment by dloukola** [comment]
I appreciate the thought of updating...but like I said previously, I think we need a workaround that will allow the 2.1 sdk installed without having to change apps that aren't using 2.1. 
I have tried adding global.json files all over the place to no avail.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9241](https://github.com/dotnet/cli/issues/9241) via [**ZenHub**](https://www.zenhub.com/)
