### ISSUE TITLE
dotnet-sdk-2.1.200 could not be installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by yanhua2002** [dotnet/core#1526]
unmet dependencies: aspnetcore-store-2.0.8 but it is not going to be installed
and aspnetcore-store-2.0.8 depends on aspnetcore-store-2.0.7
and aspnetcore-store-2.0.7 depends on aspnetcore-store-2.0.6
but aspnetcore-store-2.0.6 is not a real package (virtual)

lsb_release -a:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:          18.04
Codename:     bionic

**Comment by leecow** [comment]
Looking into this ..

**Comment by leecow** [comment]
Good to go now.
