### ISSUE TITLE
 Json Reference Loop Problem - Possible Solution

### ISSUE THREAD

**Issue by Alissonerdx** [dotnet/core#1527]
For a long time the people talk about the reference loop problem when serializing a json, would it not be possible to implement a solution where the referenced objects of the first layer are used as search objects for the lower layers and when it encounters an equal object put a null from that point forward? I know that there are problems with performance and etc. of doing searches to solve a simple problem, is it simple or are there other problems in doing this?

**Comment by Petermarcu** [comment]
@Alissonerdx I'm not sure this is the right forum for that conversation. I'm going to close this issue now.
