### ISSUE TITLE
There are no tags or releases for SDK 2.1.200

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core#1534]
According to
https://blogs.msdn.microsoft.com/dotnet/2018/05/08/net-core-may-2018-update/
version 2.1.200 is available at
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.200-sdk-download.md

But there are no tags for 2.1.200 in https://github.com/dotnet/cli or https://github.com/dotnet/sdk and there is no 2.0.8 tag in https://github.com/aspnet/Home.

Can you provide tags and releases in those repos for 2.1.200 / 2.0.8 so we can build the latest security updates?

**Comment by vellozzi** [comment]
The tag in the dotnet/cli repo helps.  But I'd still like to see a release in this repo.

**Comment by leecow** [comment]
Created - https://github.com/dotnet/core/releases/tag/v2.0.7-2. This was a strange release to figure out how to communicate since there was not .NET Core Runtime update. We'll make it better the next time this scenario pops up!
