### ISSUE TITLE
.csproj linked to .sln for ASP.net core project

### ISSUE THREAD

**Issue by darewreck54** [dotnet/core#1535]
For some reason, it seems that whenever you create a .sln and associate the csproj, the csproj is actually liked directly to the .sln as well. 

This becomes a problem when you have multiple solutions that reference the a common .csproj and the solutions are at different root levels.  What happens is that the package folder that is generated to store all the nuget files are dl only at the level of the solution that is associated with the .csproj.  The other solution that are located at different directory won't get that package and won't build.

From my understanding, the .sln is only meant to as a way to group csproj together.  You only really need the csproj to build your project in asp.net core.  So I would expect that at each solution level, it would create a package folder and pull in all the required libraries needed by the associated csproj.  This is not happening thou.

Example:

Project layout
/solution1.sln (reference common.csproj)
/test/solution2.sln (reference common.csproj)

After building
/solution1.sln
/packages/{common nuguet dependencies}
/test/solution2.sln
/test/packages/{missing common nugut dependencies}

As a result, solution2.sln will not build successfully.  This is with visual studio 2017 and asp.net core 2.

Any help appreciated,
Thanks,
Derek

**Comment by Petermarcu** [comment]
@barrytang @Pilchie can you help with this one? Where should the issue get tracked?

**Comment by Pilchie** [comment]
This is a NuGet issue with packages.config, not related to .NET Core at all.  Adding @rrelyea

**Comment by rrelyea** [comment]
Yes, this is a known limitation of projects which use packages.config (nuget v1) to manage their dependencies.
Moving that project to PackageReference (nuget v4) will avoid that problem.

Please engage with the nuget team at github.com/nuget/home as needed.

**Comment by Petermarcu** [comment]
Ok, I'm going to close this issue here. @darewreck54 go ahead and follow up in github.com/nuget/home to dig in.
