### ISSUE TITLE
ASP.NET Core App project missing Models folder when selecting Windows Authentication mode

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/core#154]
When we create ASP.NET Core RC2 project using either `ASP.NET Core Web Application (.NET Core)` or `ASP.NET Core Web Application (.NET Framework)` template and select Windows Authentication mode the project does not create `Models folder` as shown [here](http://i.stack.imgur.com/TWS6Q.png). Why is that? If we select other authentication modes it does create the Models folder. We checked even in project folders in Explorer mode and there is no Models folder there. We've tried it on both windows 7 and windows 8.1 with VS2015. Thanks.

**Comment by blackdwarf** [comment]
@saf-itpro if this issue still repros, please open it on https://github.com/aspnet/tooling/issues. I will close this one. Thanks!
