### ISSUE TITLE
Running tests on ARM builds?

### ISSUE THREAD

**Issue by andreabioli** [dotnet/core#1542]
According to this issue:

https://github.com/dotnet/announcements/issues/29

There had to be some short term solution to run tests on ARM builds... Any news on the subject, or any indications on how to build up a 'quick and basic' testing support?

**Comment by richlander** [comment]
The .NET Core SDK is now available on ARM.

**Comment by andreabioli** [comment]
Thank you very much! I just saw it, indeed... even if it's still not officially released... :-)
