### ISSUE TITLE
SDK download links are returning invalid response

### ISSUE THREAD

**Issue by da1rren** [dotnet/core#1544]
# SDK download links are returning invalid response

All the links on https://github.com/dotnet/core/blob/master/release-notes/releases.csv are returning invalid response.

**Comment by andtii** [comment]
Trying to use blob for rc1 https://dotnetcli.blob.core.windows.net/dotnet/sdk/2.1.300-rc1-008673/ 
Got error > BlobNotFoundThe specified blob does not exist

**Comment by andtii** [comment]
Pretty big issue since all vsts builds fails

**Comment by leecow** [comment]
@andtii  - blob permissions to not enable browsing at that level. Tested a couple SDK and Runtime links and should be good to go now.

**Comment by da1rren** [comment]
@leecow I'm still getting an invalid response from them all.

**Comment by da1rren** [comment]
@leecow Figured it out, I was using the wrong version number. "2.1.300-rc1-008673".  I've got it working fine with VSTS now.

**Comment by andtii** [comment]
Works for me now aswell! Thnx!
