### ISSUE TITLE
2.1 download archives do not point to linux-arm SDK.

### ISSUE THREAD

**Issue by chuckries** [dotnet/core#1545]
I know that 2.1 now has a full SDK for linux-arm, because there are docker images for the linux-arm sdk here: https://github.com/dotnet/dotnet-docker/blob/master/2.1/sdk/stretch/arm32v7/Dockerfile

However, the download archives in this repo do not include a link to the linux-arm SDK: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-rc1-download.md

This just makes this harder to find. Is there a better location to find the linux-arm SDK links, or can the download archives be updated?

**Comment by chuckries** [comment]
@leecow

**Comment by leecow** [comment]
@chuckries - links added to the RC1 download archive page.
