### ISSUE TITLE
Installing dotnet-sdk-2.1.200 on Ubuntu 18.04 uninstalls Powershell

### ISSUE THREAD

**Issue by kwiknick** [dotnet/core#1548]
# Installing dotnet-sdk-2.1.200 on Ubuntu 18.04 uninstalls Powershell
I'm following along with the ML.Net getting started docs and when I did the "sudo apt-get install dotnet-sdk-2.1.200" it removed powershell. Also for some irrellevent reason it updated clamav and installed slack.  Is this by design?  Or am I seeing some funky behavior in the repository?

https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/linux/ubuntu18-04

**Comment by leecow** [comment]
@kwiknick - I'll have a look. How are you installer PowerShell on 18.04? I don't see that it's available on https://packages.microsoft.com/ubuntu/18.04/prod. 

apt-get update will look at all installed packages for possible updates. This might would account for the clamav and slack stuff. There's definitely nothing related to either in the .NET Core SDK installer or dependencies.

**Comment by leecow** [comment]
Thanks @kwiknick - will do some poking around.

**Comment by leecow** [comment]
Grabbed the 17.04 installer from https://github.com/PowerShell/PowerShell which would require some unnatural acts to install 'properly' as the deb has system dependencies specified which are older than what are available on 18.04. I was able to install the SDK 2.1.200, which brought along most of the dependencies that powershell defines (though current versions) then installed the 17.04 powershell deb and was able to launch `pwsh` and run a few rudimentary commands successfully. 

Still am not sure about the uninstall behavior you saw though it may be linked to the unmet dependencies as defined in the powershell deb. apt-get update is a really big hammer and, AFAIK, evaluates the dependency trees of every installed package and tries to figure out what to do with them if something is off.

**Comment by kwiknick** [comment]
Thanks for looking at this.  I wish I had the exact console output, but I'm notorious for typing "clear" in the console.  But at a minimum I wanted to submit this in case it wasn't just a one off.

**Comment by leecow** [comment]
Closing as this hasn't popped up anywhere else.
