### ISSUE TITLE
Fedora 28 support

### ISSUE THREAD

**Issue by Saevar2000** [dotnet/core#1551]
# Issue Title

Fedora 28 support

# General

Can Fedora 28 support be added for dotnet core 2.1?

I tried using [these](https://www.microsoft.com/net/download/linux-package-manager/fedora27/sdk-2.1.300-rc1) instructions for Fedora 28 Server but they didn't exactly work.

Here's what I ended up doing

`~$ sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc`
`~$ wget -q https://packages.microsoft.com/config/fedora/27/prod.repo`
`~$ sudo mv prod.repo /etc/yum.repos.d/microsoft-prod.repo`
`~$ sudo dnf update`

I replaced 
`~$ sudo dnf install libunwind libicu compat -openssl10`
with
`~$ sudo dnf install libicu compat -openssl10`

because [libunwind is no longer required](https://github.com/dotnet/core/issues/1488) but got this error

`dnf install: error: unrecognized arguments: -openssl10`

I managed to fix that by changing `compat -openssl10` to `compat-openssl10`

And finally `~$ sudo dnf install dotnet-sdk-2.1.300-rc1-008673` (worked without any issues)

Here's my `dotnet --info` output after installing successfully?
>.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

>Runtime Environment:
 OS Name:     fedora
 OS Version:  28
 OS Platform: Linux
 RID:         fedora.28-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

>Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

>.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

>.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

>To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by leecow** [comment]
@Saevar2000 - yep, that looks like a successful install. I'll remove the errant space in `compat-openssl10` in the instructions.
