### ISSUE TITLE
macOS version support for .net Core 2.x

### ISSUE THREAD

**Issue by appelgriebsch** [dotnet/core#1554]
# Issue Title

macOS version support for .net Core 2.x is currently stated as macOS Sierra and up (10.12+).

# General

macOS version support for .net Core 2.x is currently stated as macOS Sierra and up (10.12+). As it turns out there are still a stable baseline of macOS users (incl. myself) who are sticking to macOS El Capitan (for various reasons). See the recent stats from statcounter below...

<div id="desktop-macos_version-ww-monthly-201706-201804" width="600" height="400" style="width:600px; height: 400px;"></div><p>Source: <a href="http://gs.statcounter.com/os-version-market-share/macos/desktop/worldwide">StatCounter Global Stats - macOS Version Market Share</a></p>

As most of the available applications are supporting macOS systems down to the version 10.9 why is there the limitation for the .net Core SDK / Runtime 2.x to only work with the most recent versions of the OS?

**Comment by leecow** [comment]
Implementing support for a given OS version, no matter the vendor, has a number of associated costs. Those costs are considered alongside customer feedback and other data that point to where customers either are, or will be soon. The line has has to be drawn somewhere and it was generally decided to begin with what was in active support by the various OS owners (Apple, Linuxes and Windows) at the time we began .NET Core 2.0 which somewhat straddled the 10.11 / 10.12 line.
