### ISSUE TITLE
Incorrect Release Notes for the .NET Core SDK 2.1.200 Release

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core#1556]
Incorrect Release Notes for the .NET Core SDK 2.1.200 Release

The .NET Core SDK 2.1.200 release at https://github.com/dotnet/core/releases says corefx changed and points to a nonexistent tag, https://github.com/dotnet/corefx/releases/tag/v2.0.8

Can you change this to https://github.com/dotnet/corefx/releases/tag/v2.0.7 so that if/when v2.0.8 comes out the release page is correct?

**Comment by vellozzi** [comment]
Actually, did corefx even change?  shouldn't it just be left off the list for that release?

**Comment by leecow** [comment]
@vellozzi there was a single package updated - detailed in https://github.com/dotnet/core/blob/master/release-notes/2.0/2.1.200-sdk.md.

**Comment by leecow** [comment]
Link mentioned in this issue is updated.
