### ISSUE TITLE
Illegal Instruction when using dotnet commands on 2.1.300-rc1 SDK with Ubuntu 18.04 ARM64 on WSL

### ISSUE THREAD

**Issue by snickler** [dotnet/core#1561]
# Illegal Instruction when using dotnet commands on 2.1.300-rc1 SDK with Ubuntu 18.04 ARM64 on WSL

## Binary Information: 

Downloaded Ubuntu 18.04 from here https://www.microsoft.com/store/productId/9N9TNGVNDL3Q

Downloaded Linux ARM (glibc) 64-bit from https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-rc1-download.md

### msinfo32 output:
```

OS Name	Microsoft Windows 10 Pro Insider Preview
Version	10.0.17666 Build 17666
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	NovaGo TP370QL
System Type	ARM64-based PC
System SKU	6
Processor	Snapdragon(TM) 835, 2208 Mhz, 8 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Qualcomm Inc. TP370QL.253, 3/30/2018
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	NovaGo TP370QL
BaseBoard Version	1.0

```

### lsb_release output from Ubuntu 18.04:
```

Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           1
Vendor ID:           ARM
Model:               0
Model name:          Cortex-A57
Stepping:            r1p0
CPU max MHz:         2208.0000
BogoMIPS:            1900
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
```

## The following commands throw this error:

`dotnet new`

`dotnet --info`

`dotnet --version`

## Output: 

```
snickler@WOATARGET:~/dotnet-2.1-rc1$ ./dotnet new
Illegal instruction (core dumped)
snickler@WOATARGET:~/dotnet-2.1-rc1$ ./dotnet --info
Illegal instruction (core dumped)
snickler@WOATARGET:~/dotnet-2.1-rc1$ ./dotnet --version
Illegal instruction (core dumped)

```

**Comment by bitcrazed** [comment]
Hey @BenHillis @terrajobst - any thoughts on what's causing these `Illegal Instruction` errors?

**Comment by benhillis** [comment]
I'm not sure, I know @Brian-Perkins has been looking at some arm64 issues recently.

**Comment by snickler** [comment]
One thing I didn't add - the `--list-runtimes` and `--list-sdks` switches are the only ones that don't return `Illegal Instruction`

```
snickler@WOATARGET:~/dotnet-2.1-rc1$ ./dotnet --list-sdks
2.1.300-rc1-008673 [/home/snickler/dotnet-2.1-rc1/sdk]
snickler@WOATARGET:~/dotnet-2.1-rc1$ ./dotnet --list-runtimes
Microsoft.NETCore.App 2.1.0-rc1 [/home/snickler/dotnet-2.1-rc1/shared/Microsoft.NETCore.App]
```

**Comment by Brian-Perkins** [comment]
I attempted to install from the instructions linked in the OP and it doesn't appear ARM64 versions are present. If someone can provide a set of commands I can run from a clean Ubuntu 18 install in order to repro this, it would be very helpful.

**Comment by Brian-Perkins** [comment]
Thank you. I thought I had tried that link, but on attempt number two it looks good. I ended up [here](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1) which wasn't as useful.

**Comment by snickler** [comment]
@Brian-Perkins - Have you been able to reproduce?

**Comment by Brian-Perkins** [comment]
I was able to reproduce. It is complaining about a cache flush instruction -- I am looking into it.

**Comment by snickler** [comment]
Great, Thanks!

________________________________

**Comment by Brian-Perkins** [comment]
We are working on a WSL fix for this. I will add another update when it makes it out in an Insiders Build.

**Comment by snickler** [comment]
This is great to hear. Thanks so much @bitcrazed @Brian-Perkins

**Comment by Brian-Perkins** [comment]
This should be resolved in Insider Build [17692](https://blogs.windows.com/windowsexperience/2018/06/14/announcing-windows-10-insider-preview-build-17692) - WSL specific release notes [here](https://github.com/MicrosoftDocs/WSL/releases/tag/17692) if you are on the Insider track. There is no fix yet for the RS4 release -- I will update when that changes.

**Comment by snickler** [comment]
I know what I'm trying out when I get home tonight. Thanks for digging into this. I'll let you know if I happen to run into anything.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snickler** [comment]
I will mark this issue as fixed, but I'm opening another issue that I've discovered while trying to use it.
