### ISSUE TITLE
Microsoft.Build.Framework.XamlTypes namespace not found

### ISSUE THREAD

**Issue by abhisheksaxena741** [dotnet/core#1562]
# Microsoft.Build.Framework.XamlTypes

Microsoft.Build.Framework.XamlTypes not found in .Net core.

# Details

I need to use NameValuePair which is defined under "Microsoft.Build.Framework.XamlTypes" namespace.

NameValuePair, i was using this in .Net framework 4.6.1 but not able to locate in .Net core/ standard. As i am migrating my project from .Net framework to .Net core based project.
Please let me know the solution or any workaround.

**Comment by Petermarcu** [comment]
@terrajobst

**Comment by terrajobst** [comment]
Are you only using the MSBuild assembly for this type? In that case, you should replace it with the standard `KeyValuePair<string, string>` or `ValueTuple<string, string>`.

**Comment by Petermarcu** [comment]
@abhisheksaxena741 I'm going to close this now based on the guidance given by @terrajobst . Let us know if that wont work and we can discuss further if needed.
