### ISSUE TITLE
Where to download the 2.0.8 runtime

### ISSUE THREAD

**Issue by jingliancui** [dotnet/core#1564]
Hi,
I use vs to upgrade the nuget to the newest 2.0.8 version.
but [this download link](https://www.microsoft.com/net/download/all) not include the 2.0.8 runtime.
How to solve this issue

**Comment by jingliancui** [comment]
And  I  need the "Hosting Bundle Installer",Thanks.

**Comment by ColinRaaijmakers** [comment]
Hi,

Please check out the following thread, https://github.com/aspnet/Docs/issues/6281
You will find your answer here.

Grtz,
Colin

**Comment by jingliancui** [comment]
Thanks.Fixed it by using [DotNetCore.2.0.7-WindowsHosting.exe](https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/DotNetCore.2.0.7-WindowsHosting.exe) and [AspNetCore.2.0.8.RuntimePackageStore_x64.exe ](https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/AspNetCore.2.0.8.RuntimePackageStore_x64.exe)
