### ISSUE TITLE
Not allowing to post huge data in AJAX call in ASP .net core 2

### ISSUE THREAD

**Issue by SattarMomin** [dotnet/core#1566]
# Issue Title

Not allowing to post huge data in AJAX call in ASP .net core 2

# General

I have created 1 page in ASP .net core 2 MVC. Now I am posting data of form by AJAX call and calling Controller Action. But when data is huge on page it is giving error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)", same is working fine when data is less.

I am sure issue is due to exceeding data size limit. 

I have tried '[DisableRequestSizeLimit]' at action level and .UseKestrel(options => { options.Limits.MaxRequestBodySize = null; }) at global level, but giving same error.

Kindly suggest

**Comment by Eilon** [comment]
This issue was moved to aspnet/Home#3328
