### ISSUE TITLE
IL Linker does not remove unused classes / methods

### ISSUE THREAD

**Issue by a-student** [dotnet/core#1572]
It is stated [here](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) that
> The linker removes code in your application and dependent libraries that are not reached by any code paths

I am following [these instructions](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md#instructions). Before publishing the app I add unused class to the project:
```
echo internal class UnusedClass { private class UnusedNestedClass { private void UnusedMethod() { System.Console.WriteLine("This method is never called.");}}}> UnusedClass.cs
```
To make sure the linker processes the main assembly add these lines to the `testapp.csproj` file:
```xml
<PropertyGroup>
    <ExtraLinkerArgs>-c link -u link -t -l none -b true --skip-unresolved true --verbose</ExtraLinkerArgs>
</PropertyGroup>
```
My publish command:
```
dotnet publish -c release -r win-x64 -o out /p:ShowLinkerSizeComparison=true
```
After publishing decompile `out/testapp.dll` (I use ILSpy).

_Expected_: UnusedClass is removed.
_Actual_: UnusedClass is still there.

**dotnet --version**: 2.1.300-preview2-008533
**IL Linker** from [this package](https://dotnet.myget.org/feed/dotnet-core/package/nuget/ILLink.Tasks/0.1.5-preview-1461378)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #18449](https://github.com/dotnet/coreclr/issues/18449) via [**ZenHub**](https://www.zenhub.com/)
