### ISSUE TITLE
32 bit Linux support

### ISSUE THREAD

**Issue by cahitbeyaz** [dotnet/core#1573]
Is there any plan for 32 bit linux support

**Comment by kasper3** [comment]
You can chime in https://github.com/dotnet/coreclr/issues/9265. Basically it compiles and all runtime tests are passing. Some packaging stuff is left I think, which someone can push forward to bring it home.

**Comment by Petermarcu** [comment]
I'm going to close this now. The coreclr issue mentioned above is the best place to track progress and ask questions
