### ISSUE TITLE
dotnet core RHEL-x64 publish output doesn't work with RHEL 6.x versions

### ISSUE THREAD

**Issue by AmeetShinde** [dotnet/core#1576]
When we build and publish self contained application with runtime identifier rhel-x64 and tried to use it on RHEL 6.x platform, we get following error

"dlopen failed to open the libcoreclr.so with error /lib64/libc.so.6: version `GLIBC_2.14' not found"

If we publish with rhel.6-x64 identifier and use these published binaries, then it works correctly on RHEL 6.x platform.

We are using dotnet core SDK 2.1.4 with runtime version 2.0.4 which supports RHEL 6.x platform as per below link
https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

We expect binaries published with portable runtime identifier to work for all versions of that specific platform.

**Comment by AmeetShinde** [comment]
can we have this issue assigned?

**Comment by tmds** [comment]
This was explained here: https://github.com/dotnet/cli/issues/9375#issuecomment-393843956.
This issue can be closed.
