### ISSUE TITLE
Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions

### ISSUE THREAD

**Issue by amshekar** [dotnet/core#1577]
# Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions

# General

We have a .Net core 2.0 webapi project and want to call a old vb.net method. The method have some string functions like Left,right,space and trim . We added the DLL as a reference . But in runtime we are getting method not found exception.

like

> Method not found: 'System.String Microsoft.VisualBasic.Strings.Left(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Space(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Right(System.String)'.'

Any help\advice is most appreciated .
We might not changes the old custom dll code which have dependencies with other systems.
If we want to do the modification in old dll if possible what would be the better approach with minimum impact

**Comment by amshekar** [comment]
refer the following git repo where we have one console app on dotnet core . From this we are making a call to vb.net classlibrary which has string functions. 

https://github.com/csreehari/FxReferenceConsoleAppCore.git

**Comment by Petermarcu** [comment]
@jaredpar

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #30963](https://github.com/dotnet/corefx/issues/30963) via [**ZenHub**](https://www.zenhub.com/)

**Comment by bimonsubio1984** [comment]
You can use a custom made port of the library named Ported.VisualBasic:
No any warranties on code correctness after porting, just use on your own risk.

Imports Ported.VisualBasic
Strings.Left(S), etc.

More details:
https://github.com/dotnet/corefx/issues/31181#issuecomment-436422404

You can find a compiled assembly here:
https://github.com/bimonsubio1984/CommonCore/releases/download/First/Ported.VisualBasic.dll
Or build it from source by yourself.
