### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by fatagun** [dotnet/core#1578]
Dear dotnet core team, 

Thank you for messing up and ruining everything. 

Finally, nothing works without too much effort. best part about .net was easy to build projects with couple clicks. 

I have been searching and trying to get the shit working all day which back then how java was. You have made it worse. Congratulations on your contributions to making people lives suck.   

Thank you, really. I am holding myself very hard not to curse to your family and your very loved ones. 

Thanks.

**Comment by snickler** [comment]
What exactly is the problem that you're having? Completely bashing the dotnet core team, failing to reference the issue, and providing what you've tried won't warrant a response...

**Comment by fatagun** [comment]
Yeah sure homey, I am sitting here just to bash your dotnet core team. I am just thanking yall for the great work.
