### ISSUE TITLE
Links broken on readme.md

### ISSUE THREAD

**Issue by aochagavia** [dotnet/core#158]
Two links in the readme no longer point to a valid address (see below). I assume that the website of .NET Core has been redesigned because of the 1.0 release.

> If you're new to .NET Core and have 10 minutes to try it, start here:
> * What is .NET Core?
> * Get Started with .NET Core on Windows, OSX and Linux

**Comment by svick** [comment]
Both links work for me, though the first one is now just a redirect to the second one. Where should the first link point? To https://docs.microsoft.com/en-us/dotnet/articles/core/index? Or https://www.microsoft.com/net/core/platform?

**Comment by mairaw** [comment]
/cc @leecow @richlander 
We should also fix the reference to OSX.

**Comment by blackdwarf** [comment]
This is now fixed.
