### ISSUE TITLE
Use (more) standard format for date in releases.json

### ISSUE THREAD

**Issue by riezebosch** [dotnet/core#1581]
https://github.com/dotnet/core/blob/6deb5d96e2a6f5aa8894ecca35cf869ec340deac/release-notes/releases.json#L4

When using `2018-05-07` for example I have no problems parsing is it (in PowerShell). Or the full format `2018-05-07T00:00:00.000Z`.

It now fails because the month and date are the other way around due to my localization settings.

**Comment by leecow** [comment]
@riezebosch - just to make sure I understand the request, you would like `YYYY-MM-DD`? The json is being used quite heavily so I also worry about breaking others in the process. 

cc @rowanmiller

**Comment by rowanmiller** [comment]
The change would be OK from my end. The json parser should just handle this, and we have a test step before swapping to new versions of the file.

**Comment by riezebosch** [comment]
For me it already works now when using `[datetime]$_.date` in PowerShell. Nonetheless you should be aware of the culture specific notation that is currently used.
