### ISSUE TITLE
Asp.net core 2.1.0 RazorTemplateEngine not working

### ISSUE THREAD

**Issue by cinaradem** [dotnet/core#1590]
I am doing html minify on razortemplate engine on compiletime on asp.net core, but razortemplate engine does not work after updating project asp.net core 2.1.0.

It does not call CreateCodeDocument method. sample code below.

public class CustomRazorTemplateEngine : RazorTemplateEngine
{
    private HtmlMinifier _htmlMinifier = new HtmlMinifier();

    public CustomRazorTemplateEngine(RazorEngine engine, RazorProject project) : base(engine, project)
    {
        Options.ImportsFileName = "_ViewImports.cshtml";
    }

    public override RazorCodeDocument CreateCodeDocument(RazorProjectItem projectItem)
    {
        using (var inputStream = projectItem.Read())
        {
            using (var reader = new StreamReader(inputStream))
            {
                var text = reader.ReadToEnd();

                var markupStart = text.IndexOf("<!DOCTYPE");
                var directives = text.Substring(0, markupStart);
                var markup = text.Substring(markupStart);
                text = directives + Minify(markup);
                var byteArray = Encoding.UTF8.GetBytes(text);
                var minifiedInputStream = new MemoryStream(byteArray);

                var source = RazorSourceDocument.ReadFrom(minifiedInputStream, projectItem.PhysicalPath);
                var imports = GetImports(projectItem);

                return RazorCodeDocument.Create(source, imports);
            }
        }
    }

    private string Minify(string markup)
    {
        MarkupMinificationResult result = _htmlMinifier.Minify(markup, string.Empty, Encoding.UTF8, true);

        if (result.Errors.Count == 0)
        {
            MinificationStatistics statistics = result.Statistics;
            if (statistics != null)
            {
                Console.WriteLine();
                Console.WriteLine($"Original size: {statistics.OriginalSize:N0} Bytes | Minified size: {statistics.MinifiedSize:N0} Bytes | Saved: {statistics.SavedInPercent:N2}%");
            }
            //Console.WriteLine($"{Environment.NewLine}Minified content:{Environment.NewLine}{Environment.NewLine}{result.MinifiedContent}");

            return result.MinifiedContent;
        }
        else
        {
            IList<MinificationErrorInfo> errors = result.Errors;

            Console.WriteLine();
            Console.WriteLine($"Found {errors.Count:N0} error(s):");

            foreach (var error in errors)
            {
                Console.WriteLine($" - Line {error.LineNumber}, Column {error.ColumnNumber}: {error.Message}");
            }

            return markup;
        }
    }
}

startup.cs
   services.AddSingleton<RazorTemplateEngine, CustomRazorTemplateEngine>();

**Comment by twisig** [comment]
Like this:

If you implement the following example, do you have the same issue?

> https://github.com/aspnet/Docs/issues/4432#issuecomment-332923557

Add the service: services.AddSingleton<RazorTemplateEngine, **CustomTemplateEngine**>();

Have the class:

public class **CustomTemplateEngine** : MvcRazorTemplateEngine
{
    public CustomTemplateEngine(RazorEngine engine, RazorProject project) : base(engine, project)
    {
    }
        
    public override RazorCSharpDocument GenerateCode(RazorCodeDocument codeDocument)
    {
        var csharpDocument = base.GenerateCode(codeDocument);
        var generatedCode = csharpDocument.GeneratedCode;
            
        // Look at generatedCode
            
        return csharpDocument;
    }
}

**Comment by eguzelkucuk** [comment]
We did it the same way, but it does not work in .net core 2.1

**Comment by panost** [comment]
It appears that is no longer used and yet is registered in [AddRazorViewEngineServices](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L208) as a singleton. I suggest you open an issue in https://github.com/aspnet/Razor/issues or 
https://github.com/aspnet/Mvc

**Comment by leecow** [comment]
Tracked by https://github.com/aspnet/Razor/issues/2422
