### ISSUE TITLE
Default MVC Project don't work in production mode

### ISSUE THREAD

**Issue by ODuchon** [dotnet/core#1593]
# Create default MVC project

After I create a new MVC ASP.NET Core project with command:
dotnet new mvc

.NET Core create a new template asp.net core application. I am building app in visual studio code a run in debug mode and everything works very well. But when I stop debugging and run the app with .NET Core command:
dotnet hellomvc.dll

I view a standard message:

> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile is available. Using '/home/duchonovi/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
> Hosting environment: Production
> Content root path: /home/duchonovi/devel/dotnetcore/hellomvc/bin/Debug/netcoreapp2.0
> Now listening on: http://localhost:5501
> Application started. Press Ctrl+C to shut down.

When I run app in internet browser, I get a blank page and in the terminal I view this error message:

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5501/  
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method hellomvc.Controllers.HomeController.Index (hellomvc) with arguments ((null)) - ModelState is Valid
> fail: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[3]
>       The view 'Index' was not found. Searched locations: /Views/Home/Index.cshtml, /Views/Shared/Index.cshtml
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action hellomvc.Controllers.HomeController.Index (hellomvc) in 130.789ms
> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
>       An unhandled exception has occurred: The view 'Index' was not found. The following locations were searched:
>       /Views/Home/Index.cshtml
>       /Views/Shared/Index.cshtml
> System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
> /Views/Home/Index.cshtml
> /Views/Shared/Index.cshtml
>    at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
>    at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method hellomvc.Controllers.HomeController.Error (hellomvc) with arguments ((null)) - ModelState is Valid
> fail: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[3]
>       The view 'Error' was not found. Searched locations: /Views/Home/Error.cshtml, /Views/Shared/Error.cshtml
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action hellomvc.Controllers.HomeController.Error (hellomvc) in 11.2623ms
> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
>       An exception was thrown attempting to execute the error handler.
> System.InvalidOperationException: The view 'Error' was not found. The following locations were searched:
> /Views/Home/Error.cshtml
> /Views/Shared/Error.cshtml
>    at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
>    at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HLE1Q004JIKM", Request id "0HLE1Q004JIKM:00000001": An unhandled exception was thrown by the application.
> System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
> /Views/Home/Index.cshtml
> /Views/Shared/Index.cshtml
>    at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
>    at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 821.6983ms 500 
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5501/favicon.ico  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 7.6255ms 404 
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5501/favicon.ico  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.1777ms 404 

I got this error on Linux Ubuntu system, Arch Linux system and in Microsoft Windows 10 system too. I have a newest version of .NET Core SDK 2.1.200. But in the older version, I think because earlier the default app working as well.

I attached my project. Can you tell me where I have error(s)? Thank you very much.
[hellomvc.zip](https://github.com/dotnet/core/files/2037483/hellomvc.zip)

**Comment by dasMulli** [comment]
To deploy the application you need to publish it:

`dotnet publish -c Release`

This will create the published output in `bin/Release/netcoreapp2.0/publish` which you can then copy other computers and run using `dotnet hellomvc.dll`.

**Comment by Petermarcu** [comment]
Let us know if @dasMulli 's advice doesn't solve your problem.  Closing for now.

**Comment by allistoncarlos** [comment]
I'm having the same problem, with one difference... I just created my app on macOS and it works fine with Docker. Then I cloned the code on a production server running Debian, docker-compose up and then this error occurs... Maybe there's a problem involving Linux's filesystem and Release mode?

**Comment by juanp3053** [comment]
@allistoncarlos I know a long time has passed since this happened to you but I am experiencing a similar situation, it runs perfectly while debugging but then it throws the same errors mentioned after publishing in kubernetes, did you ever figure out your issue?

**Comment by allistoncarlos** [comment]
> @allistoncarlos I know a long time has passed since this happened to you but I am experiencing a similar situation, it runs perfectly while debugging but then it throws the same errors mentioned after publishing in kubernetes, did you ever figure out your issue?

For what I remember, I think it was some problem with my web host's system. I asked them for help, and they configured it correctly. In my case, I was using macOS for development, and Linux for production

**Comment by juanp3053** [comment]
@allistoncarlos If you don't mind me asking, who did you ask for help? Docker?

**Comment by dasMulli** [comment]
@juanp3053 do you have a dockerfile / repro info? This issue was for asp.net core 2.1 and the architecture for views - esp. pre-compilation for deployment - changed quite a bit

**Comment by juanp3053** [comment]
@dasMulli 
Yes! I'm sorry I didn't add this information before. It is a weird situation, I have no issues when my MVC project is in .NET 5, as soon as I upgrade to .NET 6 (I do change the docker file to use the 6.0 libraries) the same exception starts coming up, only when deployed to the AKS cluster (Linux), so debugging with IIS works just fine (Windows), I might have to change my project so that I can debug it locally with Docker because I am using Pod Identity and that integrates with VS not Docker unfortunately.  Here is my Docker file:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0.100 AS build
WORKDIR /src
COPY ["IdentityApp/IdentityApp.csproj", "IdentityApp/"]
COPY ["LanguageResources/LanguageResources.csproj", "LanguageResources/"]
COPY ["NID.DalEf/NID.DalAdo.csproj", "NID.DalEf/"]
COPY ["NIDWeb.Operations/NIDWeb.Operations.csproj", "NIDWeb.Operations/"]
COPY ["NID.Dal/NID.Dal.csproj", "NID.Dal/"]
COPY ["BP.Operations/BP.Operations.csproj", "BP.Operations/"]
COPY ["NID.Operations/NID.Operations.csproj", "NID.Operations/"]
COPY ["BP.Web.Operations/BP.Web.Operations.csproj", "BP.Web.Operations/"]
RUN dotnet restore "IdentityApp/IdentityApp.csproj"
COPY . .
WORKDIR "/src/IdentityApp"
RUN dotnet build "IdentityApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IdentityApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IdentityApp.dll"]
```

**Comment by dasMulli** [comment]
So I assume this does not happen with the default templates but when using the views of a product like IdentityServer?

I used to debug running AKS k8s containers by adding vsdbg to the containers - (https://twitter.com/dasmulli/status/1326821395221925890). That might help you as well. (attach can be done in VSCode, not in VS)
![image](https://user-images.githubusercontent.com/6129250/159482066-6e31ebff-64d1-4879-8f62-7f1fdc85aec1.png)
