### ISSUE TITLE
releases.json contains undownloadable release

### ISSUE THREAD

**Issue by splatteredbits** [dotnet/core#1595]
# Issue Title

The releases.json file on master contains a 2.0.8 release which can't be downloaded by dotnet-install.ps1.

# General

We have dozens of applications and they could all be on different versions of .NET Core. We are writing automation to download the version of the .NET Core runtime at deploy time. We are using each project's TargetFramework property (e.g. netcoreapp1.0, netcoreapp2.0, etc.) to download the latest patch version of each target framework. We use the releases.json file to find the latest patch version.

Unfortunately, the latest version of 2.0 (according to releases.json) is 2.0.8. When we use dotnet-install.ps1 to download 2.0.8, we get a 404 error.

Here's the PowerShell code we wrote to do the download and install [1]. It would be nice if the releases.json file didn't contain releases that couldn't be downloaded or had some kind of flag to filter them out.

[1]
```
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]
    # The name of the package in ProGet.
    $TargetFramework,

    [string]
    # The directory where the .NET Core runtime should be installed. Defaults to `$env:ProgramFiles`.
    $InstallRoot = $env:ProgramFiles
)

#Requires -Version 4
Set-StrictMode -Version 'Latest'

$targetFramework -match '^netcoreapp(.*)$'

$majorMinor = '{0}.*' -f $Matches[1]

$runtimeVersion = Invoke-RestMethod -Uri 'https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json' |
                        ForEach-Object { $_ } |
                        Where-Object { $_ | Get-Member 'version-runtime' } |
                        Where-Object { 
                            $_.'version-runtime' -like $majorMinor 
                        } |
                        Where-Object { 
                            [version]$version = $null ; 
                            return [Version]::TryParse($_.'version-runtime', [ref]$version)
                        } |
                        Sort-Object -Property { [version]($_.'version-runtime') } -Descending |
                        Select-Object -First 1 |
                        Select-Object -ExpandProperty 'version-runtime'

$installDotNetPath = Join-Path -Path $PSScriptRoot -ChildPath 'bin\dotnet-install.ps1' -Resolve

$installDir = Join-Path -Path $InstallRoot -ChildPath ('dotnet-{0}' -f $runtimeVersion)

& $installDotNetPath -Version $runtimeVersion -SharedRuntime -Installdir $installDir
```

**Comment by leecow** [comment]
@johnbeisner

**Comment by leecow** [comment]
The 2.0.8 release was a little different in that the ASP assets were updated and versioned but the .NET Core Runtime components had no changes so were not rebuilt with the matching version. This turns out to have been a mistake. Going forward, there will alway be a full version update across ASP Core and .NET Core when either side has an update which results in a new patch version.
