### ISSUE TITLE
Resolve Core naming ambiguity

### ISSUE THREAD

**Issue by karelz** [dotnet/core#1598]
_From @SjoerdWesterhof on May 25, 2018 10:35_

It is unclear to me what Core means with:
- .NET Core the framework implementation
- ASP.NET Core the ASP.NET implementation running on both Desktop and .NET Core
- .NET Core class libraries able to target Desktop. f.e. net471

I think it would help for developer understanding of these new technologies and tools to have unambiguous naming. Right now i can't pinpoint what "Core" means.

_Copied from original issue: dotnet/corefx#29916_

**Comment by karelz** [comment]
_From @danmosemsft on May 25, 2018 18:46_

@richlander do you want to share your thoughts on this?

**Comment by leecow** [comment]
Names are definitely hard to get right. .NET Core can be thought of as the overarching umbrella brand for .NET Core, ASP.NET Core and Entity Framework Core. Core is the lightweight, cross platform stack, whereas .NET Framework (ie Desktop) is Windows-only. https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server details a number of the differences.

**Comment by SjoerdWesterhof** [comment]
It could be that it is not .NET Core that is not properly named, but some other components that use the Core name.

For me choosing a .NET Core project template for a console app and then be able to target net471 or something is just not intuitive any more. I guess it's the project file and build tooling that is Core about it, but the name is not giving intention.

Running ASP.NET of EF Core on net471 has the same issue in my opinion. For me i guess it would have been clearer when certain application frameworks/tools that are developed on top of .NET with the intention in mind (in the initial phase at least) to run on both overlapping net471 and .NET Core to have a name with which we could associate this behavior. 

Using the name Core in application frameworks/tools that are not by definition running on .NET Core is creating unnecessary confusion in my honest opinion.

**Comment by danmosemsft** [comment]
@richlander thoughts?

**Comment by Petermarcu** [comment]
I think there are very rational arguments here for what we might have done in hindsight but rebranding at this point is not likely to happen.

**Comment by Petermarcu** [comment]
@DamianEdwards

**Comment by leecow** [comment]
Seems like this can be closed.
