### ISSUE TITLE
Using directly referenced dlls

### ISSUE THREAD

**Issue by borgdylan** [dotnet/core#1600]
I am referencing a dll that is targeting .NET Standard using the Reference/HintPath mechanism. The project compiles fine but refuses to run. I have used the usual trick of CopyLocal=True to make the dll be copied to teh output directory, yet the CoreCLR cannot load it. Should I change some of the json config file soutpout by the build process? Is there some magic property I have to set in the project?

**Comment by dasMulli** [comment]
Is the problem just loading the assembly in "normal" code or in razor views/pages?

**Comment by borgdylan** [comment]
This is for a console application. Also, the dll is referenced statically in the assembly metadata at compile time.

**Comment by borgdylan** [comment]
After some hacking around with runtime config files generated by teh build process I managed ot get the code to run. Can this be included in the sdk. Like dlls in packages get added to runtime config, manually referenced dlls should also get added in there.

**Comment by borgdylan** [comment]
The repro is in an uncommited piece of code that will be committed soon. I am using the sdk bundled with the mono fork of msbuild. I am not sure if they are using old versions of the sdk or not. The version they are using seems to be 2.1.300-preview3-62804-06.

**Comment by borgdylan** [comment]
My issue seems to be a dupe of https://github.com/dotnet/sdk/issues/2162. I will chime in there to see what can be done.

**Comment by leecow** [comment]
Closing this issue as you seem to be getting help in dotnet/sdk#2162
