### ISSUE TITLE
2.0.8 is distributing the same runtime as 2.0.7

### ISSUE THREAD

**Issue by akulbe** [dotnet/core#1605]
I have been attempting to update the 2.0.7 runtime to 2.0.8 on my machine with Chocolatey. It still downloads the 2.0.7 runtime.

In the [release notes](https://github.com/dotnet/core/blob/master/release-notes/releases.json#L15-L16) for 2.0.8 it's even mentioned that it's coming with the 2.0.7 runtime. Was this intended?

**Comment by riezebosch** [comment]
On the [download page](https://www.microsoft.com/net/download/all) there isn't even a 2.0.8 release.

**Comment by leecow** [comment]
Sorry about that. We managed to this release in the most confusing way possible. The only updates were in ASP.NET Core so those updates, along with the previously release runtime, was bundled up into an updated .NET Core SDK. We'll bring ASP and Runtime versions back together with the next update to 2.0 - IOW, they'll both be something like 2.0.9.
