### ISSUE TITLE
[Moved from Dotnet] Docs : gpg: no valid OpenPGP data found - Ubuntu 18.04 

### ISSUE THREAD

**Issue by SusLes** [dotnet/core#1621]
Moving from Dotnet Issues:  [https://github.com/Microsoft/dotnet/issues/769](https://github.com/Microsoft/dotnet/issues/769)
<br><br>
Posted on Dotnet Issues by @TheBeachMaster on  5/30/2018
<br><br>
From the given steps in this link, the command wget -qO- https://packages.microsoft.com/keys/microsoft.asc \| gpg --dearmor > microsoft.asc.gpg  fails with gpg: no valid OpenPGP data found. on a fresh Ubuntu 18.04. 
<br><br>
But running wget -qO- https://packages.microsoft.com/keys/microsoft.asc --no-check-certificate | gpg --dearmor > microsoft.asc.gpg works.

**Comment by leecow** [comment]
@TheBeachMaster - Confirmed on a couple of 18.04 VMs and Docker image that this does work. Now - what's different here? Silly question - in your first example `wget -qO-` is on a separate line followed by the `https..` on a second line. This will result in OpenPGP data error. So

```
wget -qO- 
https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
```

doesn't work because the key file needs to be downloaded first.

```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
```

**Comment by BSp-r** [comment]
The same for Debian9.7 x64
The verbose command returns that 'The certificate of 'packages.microsoft.com' is not trusted' and/or '...hasn't got a known issuer'.
![image](https://user-images.githubusercontent.com/7537770/57581370-3b102480-74bf-11e9-8e71-8bb1946fbf33.png)

**Comment by karelz** [comment]
@leecow any idea what is going on?

**Comment by leecow** [comment]
You can't run wget with quiet and verbose switches at the same time.

**Comment by jakkn** [comment]
Encountered this while building a debian based docker image `FROM debian:buster-slim`.
It fails due to missing certificate store. Install with `apt-get install ca-certificates` to proceed
