### ISSUE TITLE
System.BadImageFormatException: 'Bad IL format.'

### ISSUE THREAD

**Issue by atpyk** [dotnet/core#1622]
I've upgraded dotnetcore2.0 to 2.1, and upgraded all packages too.
When I startup my web application, the exception prompts.

StackTrace:
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at GrapeLEAF.AdminService.Program.BuildWebHost(String[] args) in E:\workspace\dotnet\XXX\XXX.AdminService\XXX.AdminService\Program.cs:line 16
   at GrapeLEAF.AdminService.Program.Main(String[] args) in E:\workspace\dotnet\XXX\XXX.AdminService\XXX.AdminService\Program.cs:line 12

**Comment by atpyk** [comment]
I uninstall original .net core sdk and runtime; and reinstall VS2017. 
But, it doesn't work.

**Comment by VladislavAntonyuk** [comment]
https://blogs.msdn.microsoft.com/webdev/2018/05/07/asp-net-core-2-1-0-rc1-now-available/

**Comment by atpyk** [comment]
So sad, it doesn't work too.

**Comment by VladislavAntonyuk** [comment]
Make sure you have installed the latest VS and try to reinstall .net core.
Roolback your changes to .net core 2.0 and follow the instruction I have sent you

**Comment by Merurino** [comment]
Having the same problem. Runs fine on windows but when I build it on docker (using 2.1-sdk image) and then run on another container it gives me this issue as well. Both in web apps and console apps.

**Comment by VladislavAntonyuk** [comment]
make sure you have installed version 2.1.300 and try to uninstall all previous versions. Also doublecheck you have finished all steps in the instruction I've sent you

**Comment by atpyk** [comment]
I have reinstall my OS, it works.
Thanks.

**Comment by Merurino** [comment]
@mangod3 I was about to comment here. My issue seemed to be Newrelic.

**Comment by noahfalk** [comment]
Sorry you are running into trouble! Feel free to start with me as the investigator and I can pull in others as needed. To help get us started:
1) Could you post steps I can follow to try reproducing the problem?
2) Can you let me know what you observed while debugging that lead you to your conclusions?

**Comment by mangod3** [comment]
Thanks for your response @noahfalk. Will package up a repro and send over email.

**Comment by joseclament** [comment]
I have a web job built on netcoreapp2.1 console application, targeting the win10-x64 and getting the  "Unhandled Exception: System.BadImageFormatException: Could not load file or assembly exception". 
I haven't had any issue with locally. Deployed using the visual studio directly to the app service. Any thoughts?

**Comment by noahfalk** [comment]
@joseclament - Are you aware of any .NET profiler or monitoring agent being used in your deployment environment? If not we should probably a open a new issue because there would be a decent chance that the root cause for you will be unrelated to the root cause here.

**Comment by joseclament** [comment]
@noahfalk , I am using AppInsight to push the logs, other than no profiling or tooling.
Let me know if I need to open a new issue.

**Comment by nil4** [comment]
@noahfalk I am seeing a similar issue using the [AppDynamics .NET Core profiler agent](https://docs.appdynamics.com/display/PRO44/Install+the+.NET+Core+Microservices+Agent+for+Windows) on a netcoreapp2.1 application and .NET Core SDK 2.1.300. 

When the application starts, the following exception is thrown:

```
System.BadImageFormatException
  HResult=0x8007000B
  Message=Bad IL format.
  Source=System.Private.CoreLib
  StackTrace:
   at System.AppDomainManager..ctor()
   at System.Reflection.Assembly.GetEntryAssembly()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyApp.Web.Startup.Main(String[] args) 
```

**Comment by joseclament** [comment]
@noahfalk  and @nil4 , I got the bottom of the problem. It took couple of days to get the bottom of the issue and made me bit nuts. I was able to dig and find this link: https://tutel.me/c/programming/questions/42726350/how+to+change+azure+app+service+to+64bit

Your core should be built on x86 version even if the deploying server(Azure) is based on 64 bit architecture. Because the 64 bit .NET core processes using the .NET core runtime (as opposed to the .NET Framework runtime) are not yet supported on Azure but is planned to be coming in the future. You can verify this by go to the kudu and type  dotnet --info. You can see something like this below:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    32f29b6eb9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 _Base Path:   D:\Program Files (x86)\dotnet\sdk\2.1.300\_ [**You  can see only the x86 version here**]

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.1.8 [D:\Program Files (x86)\dotnet\sdk]
  2.1.101 [D:\Program Files (x86)\dotnet\sdk]
  2.1.300 [D:\Program Files (x86)\dotnet\sdk]

You may be able to debug this locally "Any CPU" option as you might have x86 and x64 based libraries installed on your machine. I could not find any documentation on MSDN about this. I was assumed it would have been automatically support x64 version.

**Comment by nil4** [comment]
I am not using Azure. The error occurs on my local PC when launching the application, with IIS Express, under the VS debugger, regardless of whether IIS Express 64-bit or 32-bit is selected.

The application starts up correctly if I remove the AppDynamics.Agent.Windows NuGet package, or set `CORECLR_ENABLE_PROFILING` environment variable to `0` in my Web.config (disabling the profiler).

**Comment by mangod3** [comment]
is it possible for you to capture a full native stack of the exception. That might help with identifying if you are hitting the same issue or something different.

**Comment by nil4** [comment]
@noahfalk  Here are the steps to reproduce the issue I see. In a command prompt, run:

```cmd
mkdir Repro1622 && pushd Repro1622
dotnet new web
dotnet add package AppDynamics.Agent.Windows --version 4.4.3
```
Open the project in Visual Studio, and build it once. 

A number of files brought by the AppDynamics package show up under the project, including `Repro1622.AppDynamicsConfig.json`. Edit this file and replace its content with:

```json
{
  "controller": {
    "host": "localhost",
    "port": 443,
    "account": "customer1",
    "password": "c025be84-d72d-4f6e-b5b4-b33ce264992b",
    "ssl": true,
    "enable_tls12": true
  },
  "application": {
    "name": "irrelevant",
    "tier": "irrelevant",
    "node": "irrelevant"
  }
}
```

These values are not important, they just need to be different than the default placeholders for the profiler to activate.

Add a `Web.config` file to the project, with the following content:

```xml
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%">
      <environmentVariables>
        <environmentVariable name="CORECLR_ENABLE_PROFILING" value="1" />
        <environmentVariable name="CORECLR_PROFILER" value="{39AEABC1-56A5-405F-B8E7-C3668490DB4A}" />

        <environmentVariable name="CORECLR_PROFILER_PATH_32" value="D:\Repro1622\bin\Debug\netcoreapp2.1\AppDynamics.Profiler_x86.dll"/>
        <environmentVariable name="CORECLR_PROFILER_PATH_64" value="D:\Repro1622\bin\Debug\netcoreapp2.1\AppDynamics.Profiler_x64.dll"/>
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

⚠️ Per the [AppDynamics docs](https://docs.appdynamics.com/display/PRO44/Install+the+.NET+Core+Microservices+Agent+for+Windows), the two `CORECLR_PROFILER_PATH_*` variables must be full paths; **adjust as required**.

Start debugging (F5) with IIS Express and note `BadImageFormatException` is thrown at `System.AppDomainManager..ctor()` when the application starts.

Find the newest `.log` file under *%ProgramData%\AppDynamics\DotNetAgent\Logs\Profiler*, which should be similar to:
```
2018-06-07 18:22:31.086553<info>:Use CoreCLR profiler
2018-06-07 18:22:31.089553<info>:Should instrument standalone profiler process (config found at D:\Repro1622\bin\Debug\netcoreapp2.1\Repro1622.AppDynamicsConfig.json): dotnet as app Repro1622.dll
2018-06-07 18:22:31.092555<info>:Agent Configuration: {"controller":{"account":"customer1","enableTls12":true,"ssl":true,"host":"localhost","password":"***","port":443},"application":{"tier":"irrelevant","node":"irrelevant","name":"irrelevant"}}
2018-06-07 18:22:31.092555<info>:Enabled rejit normally, disabled all NGEN images.
2018-06-07 18:22:31.163553<error>:InjectMEE failed.
2018-06-07 18:22:31.935346<info>:Transforming 57540:clrhost:System.Void System.AppDomainManager..ctor() with [[],[]]
```

**Comment by noahfalk** [comment]
@joseclament - Glad you were able to get the bottom of it and very appreciated that you came back to post your findings in case others hit the same issue in the future! Indeed it looks like your issue had a similar symptom but different root cause than the other ones here. I created #1670 to track any further work there.

@nil4 - Thanks for the repro! Let me try repro your issue so we can figure out if this is the same root cause or something else.

**Comment by nil4** [comment]
@noahfalk glad I could help, and thank you for the update, much appreciated! I am a customer, and have opened an AppDynamics support ticket about this; will update it shortly with a link to this issue.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #18448](https://github.com/dotnet/coreclr/issues/18448) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cuvillier** [comment]
My build just stuck beacuse of a "Bad IL format" .

I just clean up all the nuget caches (local & global) and restore everything.
Then, it works...

Hop this help.
