### ISSUE TITLE
Ensure that restore has run and that you have included 'netcoreapp2.1' in the TargetFrameworks

### ISSUE THREAD

**Issue by grapecitycarlzhang** [dotnet/core#1626]
# Issue Title

I've upgraded .netcore2.0 to 2.1 and rebuild my app with the errors showing.

# General

errors:
Assets file '...\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.1'. Ensure that restore has run and that you have included 'netcoreapp2.1' in the TargetFrameworks for your project.		
C:\ProgramFiles\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets

environment:
windows10 Enterprise 2016 LTSB;
vs 2017 version 15.7.2;
.net core sdk 2.1.300(x64);

**Comment by Jagbri** [comment]
Did you install .net core 2.1 sdk ([Microsoft downloads](https://www.microsoft.com/net/download)) and setted it your Project target platform?

**Comment by VladislavAntonyuk** [comment]
https://blogs.msdn.microsoft.com/webdev/2018/05/07/asp-net-core-2-1-0-rc1-now-available/

**Comment by grapecitycarlzhang** [comment]
dotnet-sdk-2.1.300-win-x64.exe download at the morning do not works ,however download at the afternoon do works.
what a interesting.
thank you for answering
