### ISSUE TITLE
How to use 2.1 with current netstandard2.0 class libraries

### ISSUE THREAD

**Issue by bitfringe** [dotnet/core#1628]
Hello, I have updated to .NET Core 2.1. Quite a simple question, and I am hoping I have missed something.

I dont see a new `netstandard 2.1`, that would facilitate the new API's, like `Span<T>`. Therefore existing `netstandard2.0` class libraries can not use any of the new goodness API-wise from 2.1.  These class libs still sit on top of `NETStandard.Library 2.0.3` metapackage.

Moreover, even the latest .NET Core 2.1 CLI scaffolds `netstandard2.0` class libraries by default.

Example API's im trying to use: `Span<T>` based overloads on `Socket` class.

However, using `netcoreapp2.1` as target framework for a class library works out fine, and the latest packages are referenced. (As a side note, netcore**app** as target for library is just weird).

But you can't reference `netcoreapp2.1` from `netstandard2.0` library....

Surely I'm not the only one facing this issue here. We got a fantastic 2.1 release, and I can't seem to figure out how do I use all that goodness having to support my clients using netstandard.

Any guidance?

**Comment by MatthewLymer** [comment]
`netstandard2.1` hasn't been standardized yet, and from what I know there's no complementary implementation to `Span<T>` on the .NET Framework, hence why you're forced to use `netcoreapp2.1` if you want that new functionality.

**Comment by MarcoRossignoli** [comment]
> New APIs will first become available in specific .NET platforms, such as .NET Core. If the .NET Standard review board believes the new APIs should be made available everywhere, they'll be added in a new .NET Standard version.

From https://github.com/dotnet/standard/blob/master/docs/versions.md#versioning-rules

Maybe @terrajobst could clarify.

**Comment by terrajobst** [comment]
That's correct, we don't have an updated version of .NET Standard but we're planning on having one. Stay tuned.
