### ISSUE TITLE
dotnet-hosting-2.1 package missing on Ubuntu 18.04

### ISSUE THREAD

**Issue by shravan2x** [dotnet/core#1630]
# dotnet-hosting-2.1 package missing on Ubuntu 18.04

I've registered the feed and followed the other instructions at https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/runtime-2.1.0, but the package is still not found.

# General

```
shravan@ubuntu:~/Desktop$ sudo apt-get install dotnet-hosting-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-hosting-2.1
E: Couldn't find any package by glob 'dotnet-hosting-2.1'
E: Couldn't find any package by regex 'dotnet-hosting-2.1'
```

**Comment by akunaatrium** [comment]
It is also missing for Ubuntu 16.04.

**Comment by leecow** [comment]
Sorry about that, the correct package name is `aspnetcore-runtime-2.1`. Fixing up the site. 

This was called `dotnet-hosting` in 2.0 but has been changed. Still not a great name so will be looking at a better option for this package.

**Comment by SergeyChanaev** [comment]
@leecow can you also amend this on page for CentOS describes runtime download? Seems to be same issue there: `dotnet-hosting` instead of `aspnetcore-runtime`

**Comment by leecow** [comment]
@SergeyChanaev - yes, I have an issue logged with @rowanmiller to make the change.

**Comment by leecow** [comment]
Closing this issue as it's a dupe of https://github.com/dotnet/core/issues/1620

**Comment by rowanmiller** [comment]
Fixed on the live site

**Comment by Scandal-UK** [comment]
Anyone want to update the Linux section on this document??
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.1-download.md
