### ISSUE TITLE
Command for downloading packages-microsoft-prod.deb is defective

### ISSUE THREAD

**Issue by akunaatrium** [dotnet/core#1631]
On this page: https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-current
there is the command: `wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb` but the command is defective.

Currently it tries to download two files, one from the correct location and another from a URL "packages-microsoft-prod.deb" which obviously is not a valid URL and therefore it quietly fails because of the `-q` flag. The exit code of the command (which is 4 - Network failure) of course indicates that an error has occurred.

The problem is hidden when the command is executed on the command line as it is but when trying to execute it as a RUN command in Dockerfile, as part of building a Docker image, it fails because of the non-zero exit code.

The fix would include the `-O` option, or removing the `packages-microsoft-prod.deb` part. I would propose this as a fix:

`wget -qO packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb`

**Comment by leecow** [comment]
Thanks for reporting this @akunaatrium . I think the correct fix for the standard instructions (docker run may well need something a little different) is to just remove the first `packages-microsoft-prod-deb`. The updated command will be `wget -q https://packages.microsoft.com/config/ubuntu/17.10/packages-microsoft-prod.deb`. I've tested this on 14.04 through 18.04 VMs and seems to be ok.

**Comment by leecow** [comment]
Instructions on  https://www.microsoft.com/net/download/linux-package-manager have been updated.
