### ISSUE TITLE
aspnetcore-runtime-2.1 dotnet does not support --version flag

### ISSUE THREAD

**Issue by shravan2x** [dotnet/core#1633]
# aspnetcore-runtime-2.1 dotnet does not support --version flag

After installing the `aspnetcore-runtime-2.1` package on Ubuntu 18.04/16.04, running `dotnet --version` returns a generic error:

```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

`--version` is not an SDK command and is supported by almost all linux applications. Could this flag be added back?

**Comment by livarcocc** [comment]
--version is an SDK only command and it has never been supported by the runtime alone.

**Comment by shravan2x** [comment]
Is there any reason for this?

Isn't `--version` a pretty generic command for linux executables?

**Comment by omajid** [comment]
There is a lot of old history about why `--version` works the way it does here: https://github.com/dotnet/cli/issues/3773. Pretty much everyone finds it confusing.

You probably want to use `dotnet --info` instead, meanwhile.
