### ISSUE TITLE
Projectfile in C# - Multiple TargetFrameworks, .Net Core 2.1, a propertygroup to suppress warnings stops Manage nuget packages working 

### ISSUE THREAD

**Issue by JRBonnema** [dotnet/core#1634]
I have a class library project in .NET Core that targets two environments 
```
>  <PropertyGroup>
>        <TargetFrameworks>netcoreapp2.0;net4.6.1</TargetFrameworks>
>  </PropertyGroup>
```
All is working fine until after I install FxCopAnalyzers and suppress a warning (CA1707). 
```
>    <ItemGroup>
>         <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.0" />
>         <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" />
>         <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />
>         <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.1.0" />
>         <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />
>     </ItemGroup> 
```
When I add the warning suppression CA1707 the following section is automatically added to the project file
```
>  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'   
>        =='Debug|netcoreapp2.0|AnyCPU'">
>     <NoWarn>1701;1702;1705; CA1707;</NoWarn>
>   </PropertyGroup>
```
After that the Manage Nuget Packages... on Dependencies is not working anymore. No installed nuget packages are shown at all and no updates are possible. The moment I remove the Suppress warning Property Group Manage Nuget Packages is working fine again and I can update my projects to .Net Core 2.1

**Comment by leecow** [comment]
Issue moved to [dotnet/cli #9426](https://github.com/dotnet/cli/issues/9426) via [**ZenHub**](https://www.zenhub.com/)
