### ISSUE TITLE
.NET 2.1.003 Breaking continuous delivery to azure app service

### ISSUE THREAD

**Issue by daemnin** [dotnet/core#1636]
# .NET 2.1.003 Breaking continuous delivery

I've been developing a project using asp.net core 2.0, I'm using CI/CD from VSTS today I pushed changes that triggered the CI/CD. Everything was successful, but when I trying to access my appservice it was throwing a HTTP Error 502.5 - Process Failure.

Afte looking into the "Diagnostics and solve problems" section of the app service in azure portal I find out that the application was faling to start. I headed to the Advanced tools section, in here I found the site\wwwroot folder of my app and ran the command that was failing in order to see the complete error message.

D:\home\site\wwwroot>dotnet API.dll
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at API.Program.Main(String[] args)

Then I checked the runtime version using:
D:\home\site\wwwroot>dotnet --version
2.1.300

# Workaround
After checking this, I installed the new SDK and upgraded my ASP.NET Core API project to 2.1 and updated all my nuget references, then just push another CI/CD and my issue was fixed.

**Comment by leecow** [comment]
@natemcmaster @muratg

**Comment by natemcmaster** [comment]
What did your project look like before you upgraded to 2.1? Can you share a minimal repro?

**Comment by daemnin** [comment]
Sorry for the late reply, the code where this issue happen can't be shared due to a privacy agreement with the company I work for. In my spare time I've been trying to reproduce this issue in a project that could be shared but no luck so far, the original project has many components and the error thrown by the azure portal's diagnostic tool doesn't help as much to identify the exact component that is causing this issue. I'll update the post once I get to reproduce the error.

**Comment by leecow** [comment]
Thanks @daemnin - will keep this open for a time then.

**Comment by daemnin** [comment]
At this point I haven't been able to replicate this issue, so I'm closing it, if I manage to consistently recreate it I will reopen including a minimal repository
