### ISSUE TITLE
Cannot install dotnet-sdk-2.1.101 on Debian Jessie anymore

### ISSUE THREAD

**Issue by TomGroeneboer** [dotnet/core#1643]
# Cannot install dotnet-sdk-2.1.101 on Debian Jessie anymore

Cannot install dotnet-sdk-2.1.101 on a Debian Jessie Docker image anymore due to `Unable to correct problems, you have held broken packages.` error.

# General

I'm trying to install .NET Core SDK 2.1.101 on Debian Jessie, which used to work in the past. However, today I noticed that I cannot do that anymore. I'm facing the following error:

```
The following packages have unmet dependencies:
 dotnet-sdk-2.1.101 : Depends: dotnet-runtime-2.0.6 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm using the following script:
```
RUN apt-get update && \
    apt-get install -y curl libunwind8 gettext apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && \
    mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg && \
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-jessie-prod jessie main" > /etc/apt/sources.list.d/dotnetdev.list' && \
    apt-get update && \
    apt-get install -y dotnet-sdk-2.1.101
```

Full output of the Docker step here: 
[out.txt](https://github.com/dotnet/core/files/2062293/out.txt)

**Comment by leecow** [comment]
Something is tripping up the package manager dependency resolution and dotnet-host is not getting picked up. You can workaround this by explicitly installing dotnet-host first, then dotnet-sdk.

```
apt install dotnet-host=2.0.6-1
apt install dotnet-sdk-2.1.101
```

cc @rakeshsinghranchi

**Comment by leecow** [comment]
Looks like this was resolved by the round of repo metadata updates that finished yesterday.
