### ISSUE TITLE
API diffs not showing readonly ref as readonly

### ISSUE THREAD

**Issue by jnm2** [dotnet/core#1644]
It looks like the API diff generator not aware of readonly ref, so it reads as though you're adding APIs that return a writable ref to ImmutableArray elements:

https://github.com/dotnet/core/blob/5185cd6ad31a8e6dd9cb9d4b5a2986cc28e3f925/release-notes/2.1/api-diff/2.0-vs-2.1_System.Collections.Immutable.md#systemcollectionsimmutable

Differentiating `readonly ref` from `ref` seems like it could be helpful to folks like me.
@karelz suggested filing the issue until @weshaggard is available.

**Comment by ViktorHofer** [comment]
cc @terrajobst

**Comment by leecow** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
I used a UI version of our tools which don't understand this concept, we did add support with https://github.com/dotnet/buildtools/pull/1849. I will use a commandline version to update the diff. Thanks for pointing out @jnm2
