### ISSUE TITLE
Profiling from Linux/macOS

### ISSUE THREAD

**Issue by doyouevensunbro** [dotnet/core#1647]
So, Visual Studio has profiling tools to help you optimize your .Net Core projects. I was wondering if this is possible to do on Linux or macOS. Not in Visual Studio, of course, but something that possibly can be run from the command line. Coming from Java, the JMX gives you a lot of visibility on what is going on. Having a way to do that in Net Core, then feeding the data to StatsD/Graphite is incredibly helpful.

Sorry if this belongs in dotnet/corefx, I wasn't sure.

Thanks!

**Comment by leecow** [comment]
@brianrob may have some ideas.

**Comment by brianrob** [comment]
@doyouevensunbro, Visual Studio doesn't have any profiling tools that work with .NET Core on Linux.  At the current time, we recommend collecting performance data on Linux using perf.  Instructions are available at https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md.

We're also working on exposing a .NET-centric profiler using functionality called EventPipe in CoreCLR.  There's not much documentation on the subject yet.

**Comment by doyouevensunbro** [comment]
@brianrob ok, thanks! Using perfcollect seems to be a very manual process. Looking forward to the changes coming in EventPipe. Having a way to poll (or push) this data would be great. 

Thanks again

**Comment by brianrob** [comment]
Yes, it is a manual process.  Are you looking for detailed tracing information, or are you looking for something more like performance monitoring?

**Comment by doyouevensunbro** [comment]
Looking for performance monitoring. We are using .Net Core as our dedicated game server, as it gives us the ability to share libraries with our Unity code base. My main use case would be monitoring performance during a load test while the dedicated server is under stress, and see where we can make improvements or where it falls over. 

Hope that helps. And thanks again for .Net Core!

**Comment by brianrob** [comment]
Gotcha.  Thanks @doyouevensunbro!  Thanks for the feedback!
