### ISSUE TITLE
Feature request: provide way to acquire latest, stable 2.1 Windows/macOS bits

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core#1649]
**Is your feature request related to a problem? Please describe.**
Starting in .NET Core 2.1, the .deb/.rpm acquisition experience changed. Linux users can now reference `dotnet-sdk-2.1` and `dotnet-runtime-2.1`. This makes it easy to upgrade by just running `apt upgrade`. There is no way to get the equivalent behavior on Windows and macOS

**Describe the solution you'd like**
I'd like a way to be able to get the latest, stable `2.1` runtime and SDK. I'm not concerned about floating the patch version.

**Describe alternatives you've considered**
* Update `dotnet-install.ps1` to support a "2.1" stable channel.
* Use a stable link that I can curl/wget from such as `https://aka.ms/dotnet/2.1/dotnet-runtime-2.1-win-x64.{exe,zip}`

**Additional context**
https://github.com/travis-ci/travis-build/pull/1397#issuecomment-393988234

**Comment by leecow** [comment]
Moving to core-setup

**Comment by leecow** [comment]
Issue moved to [dotnet/core-setup #4187](https://github.com/dotnet/core-setup/issues/4187) via [**ZenHub**](https://www.zenhub.com/)
