### ISSUE TITLE
Feature request: in-place, upgradeable installers

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core#1650]
**Is your feature request related to a problem? Please describe.**
Old versions of .NET Core are taking a lot of disk space on my dev machine. This is in part because Visual Studio so rapidly updates and automatically brings in new .NET Core versions.

Runtime: I don't need most of them because the runtime will auto-rollforward to latest patched versions. 
SDK: because the SDK is highly backwards compatible, I generally don't use global.json because the latest stable SDK works well for most projects.

**Describe the solution you'd like**
I'd like a way to have the Windows installers upgrade in place and trim unused older runtimes and SDKs. I'd also like a way to cleanup unsued packages from `C:\Program Files\dotnet\sdk\NuGetFallbackFolder`.

**Describe alternatives you've considered**
* The runtime and SDK installers could use MSI to do the in-place upgrade
* Provide a tool such as `dotnet-uninstaller` which can trim unused versions of the runtime/SDK.
* Provide a tool to cleanup `C:\Program Files\dotnet\sdk\NuGetFallbackFolder` to remove packages matching unused, old runtimes

**Additional context**

<img src="https://user-images.githubusercontent.com/2696087/40861032-69794690-659c-11e8-85b3-e307e8998c44.png" width="300" />

**Comment by leecow** [comment]
moving to core-setup

**Comment by leecow** [comment]
Issue moved to [dotnet/core-setup #4188](https://github.com/dotnet/core-setup/issues/4188) via [**ZenHub**](https://www.zenhub.com/)

**Comment by natemcmaster** [comment]
While it certainly applies to core-setup, I think this applies more broadly. If we do this, it applies to dotnet/cli and aspnet as well.
