### ISSUE TITLE
Does .Net core on Raspberry 3 Model B+ 64 bit or only on Model B 32 bit?

### ISSUE THREAD

**Issue by BenHayat** [dotnet/core#1652]
Hi guys;

I'm about to order a Raspberry 3 starter kit. Their latest version is Model B+ which is 64-bit. However I keep reading about .Net core supporting ARM32. Does this mean I can't use Model B+ and only Model B?

Thanks
..Ben

**Comment by Petermarcu** [comment]
Just make sure you use a 32bit OS and use 32bit .NET core

**Comment by BenHayat** [comment]
Hi Peter;
I see what you mean. So I should just install the 32 bit Linux and 32bit .net core runtime.
Thank you...

Do you know if MSFT will be shipping the ARM64 version of .Net core anytime soon?

**Comment by Petermarcu** [comment]
There is a 64bit arm build available. No official timeline for officially supporting it.

**Comment by BenHayat** [comment]
That's a good news. We're half way there. :-)
I'm very excited about .Net core running on Raspberry Pi. 
Thanks Peter!

**Comment by Petermarcu** [comment]
Let us know how it goes.
