### ISSUE TITLE
filenames in compiler errors to not contain enough path information to disambiguate , confusing visual studio

### ISSUE THREAD

**Issue by Spongman** [dotnet/core#1656]
when i build one of the dotnet core projects in my solution, i get the following error:

```
1>------ Rebuild All started: Project: MyProject, Configuration: Debug Any CPU ------
1>Program.cs(58,4,58,30): error CS0234: The type or namespace name 'ServicePointManager' does not exist in the namespace 'System' (are you missing an assembly reference?)
1>Done building project "MyProject.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

when i double-click on that error in the Visual Studio output window it opens the _wrong_ `Program.cs` file. this is no doubt due to the fact that the full solution-relative path to the file containing the error isn't included.

when building with the desktop csc.exe the full (ie c:\\-relative) path is displayed so there is no ambiguity.

**Comment by leecow** [comment]
Issue moved to [dotnet/cli #9425](https://github.com/dotnet/cli/issues/9425) via [**ZenHub**](https://www.zenhub.com/)
