### ISSUE TITLE
Behavioral Change Between SocketsHttpHandler and WinHttpHandler with HTTP method names

### ISSUE THREAD

**Issue by martincostello** [dotnet/core#1660]
# Behavioral Change Between SocketsHttpHandler and WinHttpHandler with HTTP method names

A behaviour change between using `WinHttpHandler` (the 2.0 default) and `SocketsHttpHandler` (the new 2.1 default) with `HttpClient` when making HTTP requests with a user-specified HTTP method string that is lower-case that may cause HTTP requests to be rejected as invalid.

# General

I help maintain an ASP.NET Core 2.0 application which we recently upgraded to ASP.NET Core 2.1. This application is hosted on AWS EC2 instances with IIS as a reverse proxy, with client requests being routed to AWS' Application Load Balancer (ALB).

In the end-to-end tests for the application, we have some test cases that perform some validation against the application as part of the deployment into AWS, one of which, when simplified, looks like this:

```csharp
[Theory]
[InlineData("get")]
[InlineData("head")]
[InlineData("options")]
public async Task Validate_Application_Health(string httpMethod)
{
    var requestUri = new Uri("https://my-application-load-balancer");

    using (var httpClient = new HttpClient())
    {
        using (var request = new HttpRequestMessage(new HttpMethod(httpMethod), requestUri))
        {
            using (var response = await httpClient.SendAsync(message))
            {
                Assert.Equal(response.StatusCode, HttpStatusCode.OK);
            }
        }
    }
}
```

Upon upgrading the application to run on ASP.NET Core 2.1, when the application was first deployed into AWS and the tests run, they failed with HTTP 400 responses instead of the expected HTTP 200. The same test pointed at the deployed 2.1 application targeting 2.0 locally passed as expected, indicating the difference was somewhere in the tests client-side.

After various bits of trial and error, I eventually narrowed the issue down to the use of _lower case_ HTTP methods being passed as argument to the `HttpMethod` constructor. It appears that ALB rejects HTTP requests that are using lowercase HTTP methods, as changing the test case to send through _upper case_ strings when using 2.1 made them pass again ([StackOverflow](https://stackoverflow.com/a/50685566/1064169)).

I guess something in the previous stack normalised the HTTP methods to upper case before sending them over the wire, but from [looking at the code](https://github.com/dotnet/corefx/blob/eaba0885c15404b41aa9a5113cf7cc8e7252053c/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L377) this appears to not be the case in the new 2.1 networking stack for `HttpClient`.

While this was easy to workaround and fix, it is a change in behaviour between 2.0 and 2.1 (at least on Windows) that as far as I'm aware isn't documented and is sort-of a breaking change, so I thought it best to report this as an issue, even if it does end up being closed as _By Design_ or _Won't Fix_.

Below is a repro console application the exhibits the difference in behaviour. On my machine, it outputs the following when the request URI is a valid AWS ALB:

```console
WinHttpHandler GET -> OK
WinHttpHandler get -> OK
SocketsHttpHandler GET -> OK
SocketsHttpHandler get -> BadRequest
HttpClient GET -> OK
HttpClient get -> BadRequest
```

<details>

`HttpMethodCase.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="4.0.0" />
  </ItemGroup>
</Project>
```

`Program.cs`
```csharp
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace HttpMethodCase
{
    internal static class Program
    {
        internal static async Task Main(string[] args)
        {
            var requestUri = new Uri("http://url-for-a-valid-aws-application-load-balancer/");

            using (var handler = new WinHttpHandler())
            {
                await SendAsync("GET", requestUri, handler);
                await SendAsync("get", requestUri, handler);
            }

            using (var handler = new SocketsHttpHandler())
            {
                await SendAsync("GET", requestUri, handler);
                await SendAsync("get", requestUri, handler);
            }

            await SendAsync("GET", requestUri);
            await SendAsync("get", requestUri);
        }

        private static async Task SendAsync(
            string httpMethod,
            Uri requestUri,
            HttpMessageHandler handler = null)
        {
            using (var httpClient = handler == null ? new HttpClient() : new HttpClient(handler, disposeHandler: false))
            {
                using (var request = new HttpRequestMessage(new HttpMethod(httpMethod), requestUri))
                {
                    using (var response = await httpClient.SendAsync(request))
                    {
                        await Console.Out.WriteLineAsync($"{handler?.GetType().Name ?? "HttpClient"} {httpMethod} -> {response.StatusCode}");
                    }
                }
            }
        }
    }
}
```

</details>

**Comment by MarcoRossignoli** [comment]
maybe open issue on https://github.com/dotnet/corefx

**Comment by martincostello** [comment]
Sorry, that's where I thought I was already because I saw core in the URL 🤦‍♂️

**Comment by martincostello** [comment]
Moved to dotnet/corefx#30143.
