### ISSUE TITLE
Installing dotnet sdk 2.1 via yum fails due to 404

### ISSUE THREAD

**Issue by jeff-powell** [dotnet/core#1661]
# Issue Title
Installing dotnet sdk 2.1 via yum fails due to 404

# General
Our build process uses the following command to install our environments, but is now failing:
`yum install -y dotnet-sdk-2.1`

And here's the error we are getting.
`Downloading packages:`
`https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/dotnet-host-2.1.0-rc1-x64.rpm`
`[Errno 14] HTTPS Error 404 - Not Found.   Trying other mirror.`
`https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/dotnet-runtime-deps-2.1.0-rc1-rhel.7-x64.rpm`
`[Errno 14] HTTPS Error 404 - Not Found.    Trying other mirror.` 

We we jump over to https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/ and look at the packages there, we see these two packages dropped the "-rc1"
- dotnet-host-2.1.0-x64.rpm                                    29-May-2018 22:38               46179
- dotnet-runtime-deps-2.1.0-rhel.7-x64.rpm           29-May-2018 22:38                2857

Were can we fix the yum command to grab the correct files?

**Comment by spartanetsru** [comment]
Try this [solution](https://github.com/dotnet/core/issues/1657#issuecomment-394739490)

**Comment by jeff-powell** [comment]
It looks that resolves the issue.  Thanks @spartanetsru

**Comment by leecow** [comment]
Clean up of the prod repo is now complete (removed pre-release 2.1 host). [package manager] refresh|update should resolve this issue.
