### ISSUE TITLE
创建.NET 控制台应用程序 疑问

### ISSUE THREAD

**Issue by mkc-xuliangjie** [dotnet/core#1662]
问题：

使用.NET core 2.0 创建 控制台应用程序 疑问

描述：
1.创建.net core 2.0控制台应用程序，解决方案命名为MSFRAM.Console，运行程序
显示错误如下：
错误	CS0234	命名空间“MSFRAM.Console”中不存在类型或命名空间名“WriteLine”(是否缺少程序集引用?)	MSFRAM.Console	D:\测试代码\MSFRAM.Console\MSFRAM.Console\Program.cs	

using System;

namespace MSFRAM.Console
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
    }
}

2.如果我的解决方案命名为MSFRAMConsole，直接运行程序却不会报错

以上，望悉知！

**Comment by smokedog2** [comment]
Console是关键字，不允许作为程序的命名空间

**Comment by leecow** [comment]
If Google Translate is to be believed, I think this can be closed.
