### ISSUE TITLE
Ubuntu packaging violates debian rules

### ISSUE THREAD

**Issue by damageboy** [dotnet/core#1665]
# Issue Title

As I'm trying to create local mirrors for both ubntu 14.04 and 18.04 I'm encountering issues with how MS maintains its ubuntu mirrors

# General

According to [this page](https://www.aptly.info/doc/feature/duplicate/) which links to the debian [documentation on repository format](https://wiki.debian.org/DebianRepository/Format?action=show&redirect=RepositoryFormat) the following has to be true:
> A repository must not include different packages (different content) with the same package name, version, and architecture. When a repository is meant to be used as a supplement to another repository this should hold for the joint main+supplement repository as well.

As such, the current format of the 14.04 / 18.04 repositories:
http://packages.microsoft.com/ubuntu/14.04/prod
...
http://packages.microsoft.com/ubuntu/18.04/prod

contains, for every package the microsoft provides, multiple files with the same name but with different content, for example:
```
$:/tmp/truty/packages.microsoft.com/ubuntu$ sha1sum */aadlogin_1.0.005200001_amd64.deb
22d3fea107fe2c2fa9669532c051fc2728f2d5f0  14.04/aadlogin_1.0.005200001_amd64.deb
750137f3ba17423c5132440f0270a306d2297476  18.04/aadlogin_1.0.005200001_amd64.deb
```

This can be resolved rather easily by making sure the names of the package file names contain the name of the ubuntu distro, for example, take mono's packages:

```
mono-complete_5.12.0.226-0xamarin3+ubuntu1404b1_amd64.deb
mono-complete_5.12.0.226-0xamarin3+ubuntu1804b1_amd64.deb
```

which include the string `ubuntu1804` and `ubuntu1404` in their filenames...

**Comment by leecow** [comment]
@damageboy - to make sure I understand, the issue isn't necessarily the packaging, but the representation on the repo, right?

**Comment by damageboy** [comment]
It's literally the filenames. If you take a look in the repo itself, some filenames have a distro component in them, some don't.

It is technicaly ok to have the same filename twice, served for different distros, as long as it is the same file content.

**Comment by leecow** [comment]
I don't know how much governance we have around submissions to the repos at this point but have included Matt so they are aware. Do let me know if there is any trouble with the .NET Core files as that is what I can directly do something about ;-)

**Comment by damageboy** [comment]
Hmm, I see, I guess this is a wider issue...

Maybe as a rolling solution for this we could start with fixing up the bionic repo which is pretty much only dotnet at this moment:

On my local repo, I downloaded the microsoft file and renamed them like this (by adding an `-1804` suffix):

```
aadlogin_1.0.004850001_amd64-1804.deb
aadlogin_1.0.004860002_amd64-1804.deb
aadlogin_1.0.004870001_amd64-1804.deb
aadlogin_1.0.004880001_amd64-1804.deb
aadlogin_1.0.005150001_amd64-1804.deb
aadlogin_1.0.005160001_amd64-1804.deb
aadlogin_1.0.005200001_amd64-1804.deb
aadlogin-selinux_1.0.004850001_amd64-1804.deb
aadlogin-selinux_1.0.004860002_amd64-1804.deb
aadlogin-selinux_1.0.004870001_amd64-1804.deb
aadlogin-selinux_1.0.004880001_amd64-1804.deb
aadlogin-selinux_1.0.005150001_amd64-1804.deb
aadlogin-selinux_1.0.005160001_amd64-1804.deb
aadlogin-selinux_1.0.005200001_amd64-1804.deb
aspnetcore-runtime-2.1.0-preview2-final-x64-1804.deb
aspnetcore-runtime-2.1.0-rc1-final-x64-1804.deb
aspnetcore-runtime-2.1.0-x64-1804.deb
aspnetcore-store-2.0.0-ubuntu.18.04-x64-1804.deb
aspnetcore-store-2.0.3-ubuntu.18.04-x64-1804.deb
aspnetcore-store-2.0.5-ubuntu.18.04-x64-1804.deb
aspnetcore-store-2.0.6-ubuntu.18.04-x64-1804.deb
aspnetcore-store-2.0.7-ubuntu.18.04-x64-1804.deb
aspnetcore-store-2.0.8-ubuntu.18.04-x64-1804.deb
dotnet-host-2.0.7-ubuntu.18.04-x64-1804.deb
dotnet-host-2.1.0-x64-1804.deb
dotnet-hostfxr-2.0.7-ubuntu.18.04-x64-1804.deb
dotnet-hostfxr-2.1.0-preview2-26406-04-x64-1804.deb
dotnet-hostfxr-2.1.0-rc1-x64-1804.deb
dotnet-hostfxr-2.1.0-x64-1804.deb
dotnet-hosting-2.0.7-ubuntu.18.04-x64-1804.deb
dotnet-hosting-2.0.8-ubuntu.18.04-x64-1804.deb
dotnet-runtime-2.0.7-ubuntu.18.04-x64-1804.deb
dotnet-runtime-2.1.0-preview2-26406-04-x64-1804.deb
dotnet-runtime-2.1.0-rc1-x64-1804.deb
dotnet-runtime-2.1.0-x64-1804.deb
dotnet-runtime-deps-2.1.0-ubuntu.18.04-x64-1804.deb
dotnet-sdk-2.1.105-ubuntu.18.04-x64-1804.deb
dotnet-sdk-2.1.200-ubuntu.18.04-x64-1804.deb
dotnet-sdk-2.1.201-ubuntu.18.04-x64-1804.deb
dotnet-sdk-2.1.300-preview2-008533-x64-1804.deb
dotnet-sdk-2.1.300-rc1-008673-x64-1804.deb
dotnet-sdk-2.1.300-x64-1804.deb
packages-microsoft-prod_1.0-ubuntu18.04.1_amd64-1804.deb
```

This was enough to untangle the situation as far as I was concerned...

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #4228](https://github.com/dotnet/core-setup/issues/4228) via [**ZenHub**](https://www.zenhub.com/)
