### ISSUE TITLE
Investigate: can we improve docs or diagnostics when 64 bit .NET Core app fails on Azure App Service

### ISSUE THREAD

**Issue by noahfalk** [dotnet/core#1670]
This issue is forked from #1622 where @joseclament reported that he was getting an unexplained BadImageFormatException. The limitation from Azure App Service is by design, but perhaps we could offer better guidance in docs or diagnostic error messages so that developers will more quickly discover the right path forward. Thanks @joseclament for raising the issue!

> @noahfalk  and @nil4 , I got the bottom of the problem. It took couple of days to get the bottom of the issue and made me bit nut. I was able to dig and find this link: https://tutel.me/c/programming/questions/42726350/how+to+change+azure+app+service+to+64bit
> 
> Your core should be built on x86 version even if the deploying server(Azure) is based on 64 bit architecture. Because the 64 bit .NET core processes using the .NET core runtime (as opposed to the .NET Framework runtime) are not yet supported on Azure but is planned to be coming in the future. You can verify this by go to the kudu and type  dotnet --info. You can see something like this below:
> 
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.300
>  Commit:    32f29b6eb9
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x86
>  _Base Path:   D:\Program Files (x86)\dotnet\sdk\2.1.300\_ [**You  can see only the x86 version here**]
> 
> Host (useful for support):
>   Version: 2.1.0
>   Commit:  caa7b7e2ba
> 
> .NET Core SDKs installed:
>   1.1.8 [D:\Program Files (x86)\dotnet\sdk]
>   2.1.101 [D:\Program Files (x86)\dotnet\sdk]
>   2.1.300 [D:\Program Files (x86)\dotnet\sdk]
> 
> You may be able to debug this locally "Any CPU" option as you might have x86 and x64 based libraries installed on your machine. I could not find any documentation on MSDN about this. I was assumed it would have been automatically support x64 version. Also make sure that the application setting is enabled for the "32" bit.
>

**Comment by bcisnero** [comment]
Probably a fast solution to this will be to add a note in the document explaining just what are the Azure limitations and the the workaround at this point because and this is going to change at some point in the future.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #18894](https://github.com/dotnet/coreclr/issues/18894) via [**ZenHub**](https://www.zenhub.com/)
