### ISSUE TITLE
Plan to develop a management tool similar to IIS on Linux?

### ISSUE THREAD

**Issue by JaneConan** [dotnet/core#1672]
We can see that IIS on window has been able to host dotnetcore applications, but Linux can only rely on Kestrel. Do you have a development plan for Web service management tools of Linux?

**Comment by leecow** [comment]
Adding a few ASP folks that may have insight - cc @danroth27 @glennc

**Comment by Petermarcu** [comment]
@muratg can you move this to ASP.NET's repo for the conversation?

**Comment by muratg** [comment]
https://github.com/aspnet/Home/issues/3226
