### ISSUE TITLE
Nuget packages restore failed (Yellow triangle)

### ISSUE THREAD

**Issue by fatih905** [dotnet/core#1674]
This my error message,  help me pls.

'C:\Users\erol_\source\repos\WebApplication38\WebApplication38\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	WebApplication38	C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9476](https://github.com/dotnet/cli/issues/9476) via [**ZenHub**](https://www.zenhub.com/)
