### ISSUE TITLE
dotnet.exe, версия: 2.1.26515.5 crash on ntdll.dll

### ISSUE THREAD

**Issue by edwardsky** [dotnet/core#1676]
# Issue Title
Name error app: dotnet.exe, version: 2.1.26515.5, time stamp: 0x5afb4a19
Fail module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Code exception: 0xc0000409
Err: 0x000000000008aa2f
Error app path: C:\Program Files\dotnet\dotnet.exe
Error module path: C:\WINDOWS\SYSTEM32\ntdll.dll
ID report: 3f7f4a99-c8ee-4cb0-8d6d-3880638e65ee
``` XML
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-06-09T10:40:40.884334100Z" />
    <EventRecordID>2457</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Megamozg</Computer>
    <Security />
  </System>
  <EventData>
    <Data>dotnet.exe</Data>
    <Data>2.1.26515.5</Data>
    <Data>5afb4a19</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.17134.1</Data>
    <Data>207580e2</Data>
    <Data>c0000409</Data>
    <Data>000000000008aa2f</Data>
    <Data>3278</Data>
    <Data>01d3ffdd59254146</Data>
    <Data>C:\Program Files\dotnet\dotnet.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>3f7f4a99-c8ee-4cb0-8d6d-3880638e65ee</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

```

**Comment by edwardsky** [comment]
Yes. This bug regularly, but i don't know how get more details. VS 2017 debbuger cant see exceprion becose my corefx console app closed! I have error in application log event on Windows. And as you see this error with dotnet.exe and ntdll.dll. May be you can help me correct my c# code, and error will be fixed.
1. My core app is WebServer on TcpListner 
2. I use SslStream with AuthAsServer option and OpenSSL test localhost cert from localhost CertAuth
3. Some times I have Exceptions on SSL System.IO.IOException: Authentication failed because the remote party has closed the transport stream. and  Authentication failed because the remote party has closed the transport stream. Maybe this exceptions crash dotnet.exe. BUT on Ubuntu and MacOSX i dont have this Issues. 
I can send you my code for testing on email

**Comment by edwardsky** [comment]
In general, this mistake made me very sad. Since I did not have time to start writing my code, I already got a full stop of the code. Of course, you can make a script that will check whether dotnet mycode.dll has stopped and start the service again. This is very sad. The databases will not be closed as needed, and the reception from other clients will cease. I even thought about throwing C # and switching to C ++. This has been torturing me for 4 days already!

**Comment by edwardsky** [comment]
You need to use NTdll more gently, so as not to crash the main start of the program dotnet.ehe. As after such a serious flight I can generally rely on your coolest cross platform environment. If it can be put so quickly on the shoulder blades. Although I did not write anything loadable yet

**Comment by Petermarcu** [comment]
@muratg can you have someone help take a look?

**Comment by muratg** [comment]
@edwardsky could you please share your repro code on a GitHub repo? 

Also, what do you mean by "WebServer on TcpListener"? Are you using Kestrel?

**Comment by edwardsky** [comment]
@muratg No, i wrote it itself by using TcpListener class and SslStream on TcpClient  iin ThreadPool.QueueUserWorkItem. I cant share my code. Becouse it is not open source. But i can send  sources in your email.

**Comment by Petermarcu** [comment]
@karelz

**Comment by muratg** [comment]
@edwardsky Can you create a simple app that reproduces the problem and share it on GitHub then? That way more people can take a look to understand what the issue may be.

**Comment by karelz** [comment]
Agreed, I think we need an isolated minimal repro to make heads and tails of it.
Alternatively, you can collect a dump (either OS settings, or by running it under windbg) and check the callstack there (VS is capable of opening dumps). There is a small chance it could help to point out the problem, but a minimal repro might be needed anyway.

**Comment by edwardsky** [comment]
@muratg Ok! I make new clean project may be this happens again, but not sure if it get an error again)

**Comment by edwardsky** [comment]
@muratg @karelz I again repeated the application's bug in the new project, check my project that there might crash the program. This repo https://github.com/edwardsky/dotnetntdllbug.
my os is https://yadi.sk/i/ugKl7roj3XtNuJ

**Comment by edwardsky** [comment]
@karelz i dont use tool windbg and cant get stack trace( What i need to do step by step, or maybe some instruction for how i can record this information

**Comment by muratg** [comment]
@edwardsky 

I think this is your problem:

```csharp

            // catch requests
            while (true)
            {
                // Принимаем новых клиентов. После того, как клиент был принят,
                // он передается в новый поток (ClientThread)
                // с использованием пула потоков.
                ThreadPool.QueueUserWorkItem(new WaitCallback(ClientThread),
                    Listener.AcceptTcpClient());
            }
```

You're trying to create an infinite number of WaitCallbacks. 

@karelz may talk about the right pattern to use here instead.

**Comment by edwardsky** [comment]
@muratg I will be very happy if the desired pattern solves my problem. But why is it just closing? Why there is no exception that can be processed and continue working? Okay, I nakosyachil but how do I continue to catch my bugs?

**Comment by edwardsky** [comment]
Good-bye guys. I turn to C ++ development and this solution is no longer necessary to me! Very much disappointed in dotnet. I do not see any further development of myself as a developer in C #.

**Comment by karelz** [comment]
@edwardsky sorry to hear that.
I expect that you will soon notice that C++ requires exactly same knowledge (and even deeper) - you need to know how to get exceptions info (StackOverflow, corruptions, etc.) as I suggested above (i.e. windbg / other debugger knowledge).
I wish you good luck!

**Comment by edwardsky** [comment]
@karelz I know that I need more knowledge, although it stopped me and started programming in C ++. But now I know for sure that this is my new path. Thank you for your wish. I wish you and your product luck and prosperity

**Comment by edwardsky** [comment]
@karelz Hello, ill setup WinDbg Preview and run dotnet w param myproject.dll. In loadel dll I found CryptoPro CSP dll, and this dll write to system log many errors. I'll uninstall this program. And no more crashes!

**Comment by karelz** [comment]
Looks like a bug in CryptoPro CSP. Happy to hear you were able to resolve your problem.
When other buggy DLLs inject themselves through OS and do harm, there is not much we can do about it :(
