### ISSUE TITLE
Can't add new migration using startup project with netCore2.1

### ISSUE THREAD

**Issue by alentor** [dotnet/core#1677]
# Issue Title
 Can't add new migration using startup project with netCore2.1 getting null on connection string param

# General
Example:
In the following repository I'm using a startup project to initiate a connection string to a dbContext.
it's working with 2.0  but not with netCore2.1, code base is the same only the target framework and libraries have changed to 2.1

https://github.com/alentor/Bloggerium

The code base it one to one, the only differences is that I'm targeting netcoreapp2.1 and using 
Microsoft.EntityFrameworkCore 2.1 instead of 2.0.3
Microsoft.EntityFrameworkCore.Design 2.1 instead of 2.0.3
Microsoft.EntityFrameworkCore.SqlServer 2.1 instead of 2.0.3

For 2.0 and 2.1 using dotnet cli 3.1.300 and netcore ef 2.1.0-rtm-30799
windows 10 version 1803 build 17134.81

**Comment by alentor** [comment]
Please close the issue, as I have resolved it.

According to bricelam's stackoverflow [thread ](https://stackoverflow.com/questions/45995931/does-ef-core-migrations-call-startup-configure-on-add-migration)

> "Startup.Configure() should only contain code to configure the request pipeline. Any app startup/initialization code should go in Program.Main()."

I have moved my dbContext initialization to Program.Main() and now it's working!

**Comment by MarcoRossignoli** [comment]
If I'm not mistaken if you create an issue you can close it by yourself with "Close issue" button
![closeissue](https://user-images.githubusercontent.com/7894084/41216869-58559fdc-6d56-11e8-941c-e63ebff85b5e.png)
.
