### ISSUE TITLE
.Net Core and Native dll's always throw BadImageFormat

### ISSUE THREAD

**Issue by SharperC** [dotnet/core#1678]
# BadImageFormatException, everytime...

After a LOT of times trying to load native code or rather call a native method using `DllImport`, I'm reporting this as a issue, because it seems like there is no solution.

## So what did I try?

First of all, I tried the way it works with .Net Framework, what of course didn't work.
I searched in the Internet for solutions but i only found the same problems with "could work" solutions. For example compiling the .Net Core application and the native libary in 64 bit (what i did).
I also tried a non .Net c++ compiler (MinGW) and the default Visual Studio c++ compiler.
Both give the same `BadImageFormat` Exception.

### The c# part
```cs
[DllImport(@"testlib.dll", EntryPoint = "test")]
static extern int Test();

static void Main(string[] args)
{
    Console.WriteLine(Test());
    Console.ReadLine();
}
```

### The c++ part
```cpp
#define EXTERN extern "C" __declspec(dllexport)

EXTERN int test()
{
    return 1234;
}
```

I also tried it on Linux using the g++ compiler, for some reason it worked on Linux.

Thanks for taking the time to read.

**Comment by markusschaber** [comment]
In my experience, the main reason for this exception is when you try to load a 32-bit DLL into a 64 Bit process, or the other way round.

Mismatch between x86/ARM could also be.

Note that sometimes, .NET core on Windows runs in an unexpected CPU architecture, as some tools (e. G. Visual Studio, xUnit etc.) tend to ignore the target CPU architecture defined in the project, and just run the code in the first installation they find in PATH.

We had to change the order of entries in PATH environment variable to run our code with x86, as the native DLL we depend on is not (yet) 64 bit.

**Comment by dasMulli** [comment]
for `dotnet` it will use the version of `dotnet.exe` that's in the path - either the 32bit or 64bit `dotnet.exe` host.
There will be some changes that will allow patching the csproj to allow `dotnet run` to switch architectures (when launching a sub-process) but until then, it's a bit of a pain - https://github.com/dotnet/sdk/issues/1905

**Comment by SharperC** [comment]
@markusschaber I know that you mean, but i tried both using a 32bit and a 64bit for c++ and dotnet, and yes a already noticed that dotnet tends to totaly ignore if you set the assembly in vs to 32 bit

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #18447](https://github.com/dotnet/coreclr/issues/18447) via [**ZenHub**](https://www.zenhub.com/)

**Comment by WaqarAzeem** [comment]
I created two projects

1. ASP.NET Core Web Application | Core 2.2
2. ASP.NET Web Application (.NET Framework) | .Net 4.6.1 

In my test controller, I used an exported function from a 32-bit unmanaged DLL, using [DllImport("Testing.DLL")]
Copy that 32-bit native DLL file in both the project folders
Run as “Any CPU” on my Windows 64-bit Windows 10 with IIS Express

Only the project created in Core 2.2 crashed with following exception
[
  {
    "errorCode": -1001,
    "errorString": "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)",
    "exception": {
      "ClassName": "System.BadImageFormatException",
      "Message": "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at WebApplication1.DCCAPI.BUICExit()\r\n   at WebApplication1.Controllers.TS240Controller.BUICInit() in C:\\Users\\Waqar Azeem\\source\\repos\\WebApplication1\\WebApplication1\\Controllers\\TS240Controller.cs:line 71",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": null,
      "HResult": -2147024885,
      "Source": "WebApplication1",
      "WatsonBuckets": null,
      "BadImageFormat_FileName": null,
      "BadImageFormat_FusionLog": null
    }
  }
]
