### ISSUE TITLE
how to get filename of embedded resource of an dll(assembly

### ISSUE THREAD

**Issue by tukzer** [dotnet/core#1679]
# Issue Title

I'm working on a project where i'm trying to involve a plugin system on aspnetcore2.0 , i want to load views and controllers in seperated assemblies dynamically, thus, load static files in assembly using relative path.  I implemented a EmbeddedResourceFileProvider based on IFileProvider, but failed to load resource file names.

# General
I use code like below to find all the resource files embedded in assembly, which translates resourceName like "App.NYMC.UI.Views.Account.Register.js" into relative path like ''Views/Account/Register.js" which can be used in views while accessing that javascript file;

`        internal virtual void AddResources(Dictionary<string, EmbeddedResourceItem> resources)
        {
            foreach (var resourceName in Assembly.GetManifestResourceNames())
            {
                if (!resourceName.StartsWith(ResourceNamespace))
                {
                    continue;
                }

                using (var stream = Assembly.GetManifestResourceStream(resourceName))
                {
                    var filePath = RootPath + ConvertToRelativePath(resourceName);

                    resources[filePath] = new EmbeddedResourceItem(
                        CalculateFileName(filePath),
                        stream.GetAllBytes(),
                        Assembly
                    );
                }
            }
        }
`
Then i can reference file like this in .cshtml:

`<script src="/Views/Account/Register.js"></script>
`

The problem is that the filePath is invalid when the file name include ".". For example, file "Views/Content/js/site.min.js" got a resource name as 'Views.Content.js.site.min.js'. So i was not able to discover its orginal file name via resourceName.
I tried to get file name like this, but it returned null.
`var resourceInfo = Assembly.GetManifestResourceInfo(resourceName);`

It seems like that the "." symbol in file name is used to be convert to "_" in .net framework, will we able to  do something like or beyond that so we can identify the file name part in resourceName.

**Comment by leecow** [comment]
@natemcmaster @danmosemsft

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #30287](https://github.com/dotnet/corefx/issues/30287) via [**ZenHub**](https://www.zenhub.com/)

**Comment by natemcmaster** [comment]
This is a known limitation for ASP.NET Core 2.0 and older. In ASP.NET Core 2.1, @javiercn wrote a new file provider which will better map embedded resources back to file names. [`Microsoft.Extensions.FileProviders.ManifestEmbeddedFileProvider`.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.manifestembeddedfileprovider?view=aspnetcore-2.1)

cc @javiercn - do we have docs for how to enable this?

**Comment by javiercn** [comment]
@natemcmaster I'm not sure if this is covered as part of the razor in class libraries topic.

**Comment by natemcmaster** [comment]
Ok, let's use https://github.com/aspnet/Docs/issues/6988 to get this feature document.

**Comment by danmosemsft** [comment]
Should this remain closed then (and the corefx one)?

**Comment by natemcmaster** [comment]
Yes, I don't think this is an actual issue for corefx. IIUC the problem @tukzer is asking about is how to map from embedded resource name back to the original file path that produced this resource. This is not possible using vanilla .NET runtime and SDK bits. You have to capture this mapping at compile time, which is what @javiercn implemented in the new ManifestEmbeddedFileProvider API.

**Comment by alsfyani** [comment]
<script src="https://ideone.com/e.js/M3JlJV" type="text/javascript" ></script>
