### ISSUE TITLE
Release versions not consistent between CSV and JSON

### ISSUE THREAD

**Issue by ds-ms** [dotnet/core#1680]
I'm a contributor of  `Microsoft/vsts-tasks` repository. We have a `Dotnet Core Installer` task to aid the users to install a specific version of dotnet Runtime/SDK. For helping the user to figure out the versions, we added https://github.com/dotnet/core/blob/master/release-notes/releases.csv to our help text. 

We are facing some issues, because of some mismatches in the .csv file. Here's a GitHub issue link: https://github.com/Microsoft/vsts-tasks/issues/7032 

![image](https://user-images.githubusercontent.com/25762922/41221081-ce5dd986-6d80-11e8-92d0-ff76394ed798.png)

Although, the version-sdk here says `2.1.0-preview2`, it should have been `2.1.300-preview2-008533` instead (based on the urls) or something along those lines. 

Addressing this issue, we assumed we could rely on the [Releases.json](https://github.com/dotnet/core/blob/master/release-notes/releases.json) for mapping a display-value to the download URL, but given the inconsistency between the CSV file and JSON file, it would result in failures when using `2.x` (~preview) versions.

**Comment by ds-ms** [comment]
![image](https://user-images.githubusercontent.com/25762922/41224663-a55b6bde-6d8a-11e8-9942-60526c8ae202.png)
Also, there's a space in a couple of URLs which doesn't allow us to consume this value straight way i.e. leads to a 400 error. Could you do a sanity check on the values in this CSV?

**Comment by leecow** [comment]
@preetikr

**Comment by Petermarcu** [comment]
I made a PR that should address what you found. Feel free to submit PR's for things like this. Especially the spaces problem is probably faster for everyone if you just submit a PR :) Thanks for reporting this.

**Comment by ds-ms** [comment]
Appreciate the fix, will raise it myself from next time :) 
Also, what is the expected source of truth here? Do you want the customers to rely on Releases.JSON or Releases.CSV for figuring out the new versions?

**Comment by Petermarcu** [comment]
@leecow I assume you intend these files to be the source of truth?

**Comment by leecow** [comment]
The json should be considered the source of truth.
