### ISSUE TITLE
$(PROJECTDIR) Set Incorrectly in .NET Core Projects

### ISSUE THREAD

**Issue by cculver** [dotnet/core#1682]
I began investigating problems with EF migrations which led me down a diagnostic path that eventually led to me discovering that PROJECTDIR is not set correctly on any .net core projects. Entity Framework depends on PROJECTDIR to resolve its depsfile, so this seems to be breaking some things. I'm not sure if this is specific to my machine, but I have reproduced it across different .NET core projects.

# General

I am using Visual Studio 2017 15.7.3 along with .NET Core 2.1.0/SDK version 2.1.3 on Windows 10 Pro build 17134.81 / Version 1803.
The steps to reproduce this are as follows. I have a main directory for my solutions, C:\Git\. I create a test solution, Test. Inside the solution, I create four projects: .NET Core 2.1 Console App (test1), ASP.NET Core Web Application 2.1 (test2), .NET Framework 4.5 Console App (test3), and ASP.NET Web Application (.NET Framework) (test4). Do nothing to the projects except hit build, then go to the properties for each project in the solution, then to build events, then edit either pre- or post-build button, then click the macros button to list the variables for the project. Check the ProjectDir variable. 

For the .NET Core projects, I see a ProjectDir of "C:\Git\" whereas for the non-Core projects, I see C:\Git\Test\test3\ and C:\Git\Test\test4\, respectively.

This probably wouldn't matter to me, but msbuild is used to elicit ProjectDir from the project file here: https://github.com/aspnet/EntityFrameworkCore/blob/908491ca0f55a27c43a7b5b91a92a3714f7c89cd/src/dotnet-ef/Project.cs#L131. That code, in turn, is used here https://github.com/aspnet/EntityFrameworkCore/blob/9f0a44e29ee28fee57739c2f4bccaa4e46e74b4f/src/dotnet-ef/RootCommand.cs#L98 to generate the depsfile location. Thus, any EF commands executed on a .NET Core project find themselves using the wrong ProjectDir, and end up executing dotnet exec --depsfile C:\Git\bin\Debug\netcoreapp2.1\test1.deps.json, which should really be dotnet exec --depsfile C:\Git\Test\test1\bin\Debug\netcoreapp2.1\test1.deps.json.

**Comment by leecow** [comment]
@livarcocc

**Comment by livarcocc** [comment]
Adding @bricelam to comment on the EF issue.

Adding @Pilchie to comment on the ProjectDir issue. I don't believe the SDK sets it.

**Comment by bricelam** [comment]
EF Core has used `$(ProjectDir)` since the beginning. This is the first issue I've seen reported on it.

**Comment by cculver** [comment]
Anyone know where I can find code that sets $(ProjectDir) or is that closed source? Might be worth trying to chase on my machine in case it's me.

**Comment by cculver** [comment]
I found another reference to this problem on SO. https://stackoverflow.com/questions/43656260/projectdir-prebuild-event-macro-incorrect/43656609
This contains a workaround (https://github.com/dotnet/project-system/issues/1569#issuecomment-289939906). Do you suggest I go this route for EF .NET Core-based projects until this is remedied?

**Comment by dasMulli** [comment]
@cculver are you using `dotnet ef` tooling that runs into errors or are you trying to invoke `dotnet ef` commands from pre/post-build events?

VS 2017 15.3 changed the project system to make MSBuild targets instead of changing the legacy build event properties.

Can you share a project that reproduces the error? Or just a binary log (`dotnet build -bl`, then (zip for GitHub) and upload the msbuild.binlog file) (note that this will contain project files (csproj) and environment variable contents).

I suggest using `$(MSBuildProjectDirectory)` for better compatibility.

**Comment by dasMulli** [comment]
About the source code: https://github.com/Microsoft/msbuild/blob/4972ebc6d2b81c5e967cd3260943a95c8e5eb4be/src/Tasks/Microsoft.Common.CurrentVersion.targets#L291

**Comment by cculver** [comment]
@dasMulli, I believe that I may have confused the explanation of my problem (that EF is unable to locate a depsfile) by providing an example that demonstrates the issue easier than providing debug files (the macro part). I am including an image of this macro part just to put an end to the question of what I'm seeing here, but please know that I am not trying to actually use the pre-/post-build macros in any way.
![image](https://user-images.githubusercontent.com/1117512/41325603-3c8957ce-6e89-11e8-8368-db65758cf8e0.png)
Please note that the ProjectDir listed in the image above references C:\Git\, not the actual project directory. My question is why is this showing up this way?
To address your requests, I am providing a repo here: https://github.com/cculver/test. Make the project WebApplication1 the startup project, build the solution, and from the package manager console, execute: 
PM> cd .\WebApplication1
PM> dotnet ef migrations list
On my computer, I get the following error:
dotnet : The specified deps.json [C:\Git\bin\Debug\netcoreapp2.1\WebApplication1.deps.json] does not exist
At line:1 char:1
+ dotnet ef migrations list
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The specified d... does not exist:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The important part about this result is that it shows you the location where it looked for the deps file: C:\Git\bin\Debug\... rather than C:\Git\test\WebApplication1\bin\Debug....

Just so we have a record of what my machine is using during the build process, I have uploaded the binlog file as well.
[msbuild.zip](https://github.com/dotnet/core/files/2096376/msbuild.zip)

**Comment by cculver** [comment]
I think I resolved the issue and it was machine-specific. There's no problem here. I will reopen if it reoccurs. Thanks for your time.
