### ISSUE TITLE
Visual Studio support for Gitlab Registry

### ISSUE THREAD

**Issue by cculver** [dotnet/core#1683]
I've been toying around with using an onsite Gitlab instance to host a registry for Docker images for .NET Core 2.1 projects, but I'm having great difficulty using the publish feature in Visual Studio 15.7.3. It seems the publish feature has been designed to work with only two registries: Azure and Docker Hub, despite the "Custom" selection. It could certainly be that I'm not doing this right, or there could be an issue with Gitlab's registry implementation, but I have debugged as much as I can and have found that the custom feature lacks full support for Gitlab's registry. I should note that I can easily publish to Gitlab's registry from the command line, but not when using Visual Studio. Does anyone have any insight here?

**Comment by Petermarcu** [comment]
@mlorbetske what is the best place for this issue to go to get tracked?

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/websdk#365
