### ISSUE TITLE
Setting Authorization header on an HttpClient instance does not work in .NET Core 2.1 

### ISSUE THREAD

**Issue by pereiraarun** [dotnet/core#1684]
Testing on .NET Core 2.1 (by setting Target Framework 2.1), the following code results in a 403 Forbidden since the header is not set correctly.
Header is set using the following method:

    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Token", "9ac..b87b20");
    var result = client.GetStringAsync("/api/ipam/prefixes/").Result;

Moving back to .NET Core 2.0 (by setting Target Framework 2.0) fixes the issue. The same happens when using RestSharp. Seems there is some bug with HttpClient and setting authorization headers. 

Testing through: Vs Professional 2017 (15.7.3) on Windows 10 with the latest updates.

**Comment by brockallen** [comment]
Are you sure the scheme is correct? Normally it should be "Bearer" (not "Token") if you're doing an OAuth2 style client.

**Comment by pereiraarun** [comment]
The code works as posted in .Net Core 2.0. The code is used for https://netbox.readthedocs.io/en/latest/api/authentication/

`  $ curl -H "Authorization: Token d2f763479f703d80de0ec15254237bc651f9cdc0" -H "Accept: application/json; indent=4" http://localhost/api/dcim/sites/`
` {`
`     "count": 10,`
`     "next": null,`
`     "previous": null,`
`     "results": [...]`
  `}`

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #30349](https://github.com/dotnet/corefx/issues/30349) via [**ZenHub**](https://www.zenhub.com/)
