### ISSUE TITLE
Dotnet Core 2.1 Run error in centos 7

### ISSUE THREAD

**Issue by CrystalWindSnake** [dotnet/core#1686]
# Dotnet Core 2.1 run error in centos 7
Dotnet core console program build in **Window10** didn't work on the **Centos**. But If i use the command line to compile in the **CentOS** system, it can run normally. 

## Exception
Exception is:
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/ConsoleApp1.dll'. The module was expected to contain an assembly manifest
```

## Configure
 vs2017 publish  configure is:
```  xml
<PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PublishDir>bin\Release\netcoreapp2.1\publish\centos</PublishDir>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <_IsPortable>true</_IsPortable>
  </PropertyGroup>
```

I also tried to use  centos-x64 and centos.7-x64 in RuntimeIdentifier.but still can't work.

Thanks All.

**Comment by Petermarcu** [comment]
Have you tried building on centos to see if you get different behavior? Trying to narrow down where the problem may be.

**Comment by CrystalWindSnake** [comment]
@Petermarcu Thank you for follow up my question。
I tried the following operation today。
1，Create a console program using commands，and it work on windows.
```
dotnet new console
dotnet run
```

2,Copy the debug folder directly to the centos system，and cd to debug folder and run using commands
```
dotnet xxx.dll
```

3,The following error message appears
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/home/t1/wins/bin/Debug/wins.dll'. An attempt was made to load a program with an incorrect format.
```

According to my understanding, he should be able to work。This problem bothers me for two days, thank you for your reply。

# dotnet --info
**windows**:
![wins-infos](https://user-images.githubusercontent.com/36034954/41350707-9567c4e4-6f46-11e8-83b4-77cdd9ef4a3b.png)

**centos**:
![centos-info](https://user-images.githubusercontent.com/36034954/41350720-9eadf226-6f46-11e8-95d0-222692d160ff.png)

**Comment by Petermarcu** [comment]
It looks like the problem is that you aren't publishing the application. The exception is a little misleading so this may not be it. Try 'dotnet publish' and using the contents of the publish folder on the other machine. If you have OS specific dependencies, you will need to 'dotnet publish -r linux-x64'.

**Comment by Petermarcu** [comment]
were you able to try a published application?

**Comment by CrystalWindSnake** [comment]
@Petermarcu So sad,it don't work.I have a question about the release and published.My program is just a very simple “Hello World” Console,Why did it have to published?

**Comment by CrystalWindSnake** [comment]
@Petermarcu  I create a new project on windows use the 'dotnet new console' this time.and published use 'dotnet publish -r linux-x64 --self-contained=false'.and then i copy to the 'microsoft/dotnet' docker's image and 'dotnet xxx.dll' run it.but it still the same problem.is that my windows system problem?
 thank you and have a nice weekend

**Comment by Petermarcu** [comment]
Hi, sorry, I missed the responses and realize that its been a long time. Were you able to get this working? Is this still a problem you are facing?

**Comment by karelz** [comment]
No response, closing.
@CrystalWindSnake if you are still hitting the problem, feel free to reopen.
I would recommend to try it from different OS (Linux or at least different Windows VM) to avoid tracking down weird one machine setup problems.
