### ISSUE TITLE
com.apple.installer.pagecontroller error -1.

### ISSUE THREAD

**Issue by lukywong** [dotnet/core#169]
I have installed rc2, when i get latest package `.NET Core SDK Installer
(Preview 2)` to install, but gets the error 
```
The operation couldn’t be completed. (com.apple.installer.pagecontroller error -1.)
Couldn't open "dotnet-dev-osx-x64.1.0.0-preview2-003121.pkg".
```
my system is OSX EI Captain 10.11.5

**Comment by blackdwarf** [comment]
@lukywong can you please move this issue to dotnet/cli if it still repros? This is a much better place for it. Thanks!
