### ISSUE TITLE
DotNet Core 2.0 Thread.Start issue

### ISSUE THREAD

**Issue by TheProxyRE** [dotnet/core#1695]
# Issue Title

Single thread instance cannot be executed twice

# General

Ok so issue here is that single thread instance cannot be executed twice even if first execution was completed (This works fine in Framework)

And when i was trying to debug Execute method doesn't execute at second .Start();

Here is example code:
```csharp 
 public class AdvancedThread
    {
        private bool abort;
        readonly Thread thread;
        public int Value = 0;
        public AdvancedThread()
        {
            thread = new Thread(Execute)
            {
                IsBackground = true
            };
        }
        public void Start()
        {
            abort = false;
            thread.Start();
        }
        public void Abort()
        {
            abort = true;
        }
        private void Execute()
        {
            while (!abort)
            {
                Value++;
                Thread.Sleep(10);
            }
        }
    }

 static void Main(string[] args)
        {
            var thread = new AdvancedThread();
            Console.WriteLine(thread.Value);
            thread.Start();
            Thread.Sleep(500);
            Console.WriteLine(thread.Value);
            thread.Abort();
            Thread.Sleep(5000);
            Console.WriteLine(thread.Value);
            thread.Start();
            Thread.Sleep(5000);
            Console.WriteLine(thread.Value);
        }
Output:
0
46
46
```

**Comment by mikedn** [comment]
> Ok so issue here is that single thread instance cannot be executed twice even if first execution was completed (This works fine in Framework)

This doesn't work in the .NET Framework either. It's also stated in the [documentation](https://msdn.microsoft.com/en-us/library/6x4c42hc(v=vs.110).aspx):

> Once the thread terminates, it cannot be restarted with another call to Start.

**Comment by leecow** [comment]
Closing - thanks @mikedn !
