### ISSUE TITLE
Cannot `dotnet run` F# project on Mac OS X (macOS)

### ISSUE THREAD

**Issue by sivabudh** [dotnet/core#170]
I installed DotNet 1.0 released yesterday using this dmg.

`dotnet-dev-osx-x64.1.0.0-preview2-003121.dmg`

I then created an F# project:

```
$ dotnet new -l fsharp
$ dotnet restore
```
Then, when it came time to run it, I got this error:
```
$ dotnet run
Project fsharp_dotnet_core (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling fsharp_dotnet_core for .NETCoreApp,Version=v1.0
The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc3-004459-00' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002702
  - Alternatively, install the framework version '1.0.0-rc3-004459-00'.
/usr/local/share/dotnet/dotnet compile-fsc @/Users/Pac/Code/fsharp_dotnet_core/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 131

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.4526408
```

Sadly, I didn't get the "Hello World!" =(

**Comment by jolson88** [comment]
This is the case for me on Ubuntu as well :(.

**Comment by gregkalapos** [comment]
This is already addressed in:
https://github.com/dotnet/cli/issues/3705
and something was even merged from here:
https://github.com/Microsoft/visualfsharp/pull/1290

I guess the platform is not relevant, since the dependencies are wrong. 

This bug also prevents me to work with F# on RTM...

**Comment by blackdwarf** [comment]
@cartermp can you share what the fix is here? This seems to be a known issue with wrong dependencies for F# projects that crept into Preview 2 release of the tooling.

**Comment by ForNeVeR** [comment]
@blackdwarf try to create new project. The bug I think was fixed yesterday; I was able to compile and run F# project generated by `dotnet new -l F#` (because new packages were published).

**Comment by sivabudh** [comment]
@ForNeVeR thanks for updating us. It works now. Closing the ticket. =)

**Comment by ckuhn203** [comment]
Does anyone know how to solve this. Downloaded dotnet core on my mac today, 6 months later and am having the same issue.

**Comment by blackdwarf** [comment]
@ckuhn203 the exact same issue that is the root of this thread? 

/cc @cartermp

**Comment by cartermp** [comment]
See here: https://github.com/dotnet/cli/issues/3705#issuecomment-274275752

I was able to get the latest Preview2 tooling that's on the dot.net/core site running without issue.
