### ISSUE TITLE
DotNetCore WindowsHosting URLs give 404s for 1.1.7 and 2.0.6

### ISSUE THREAD

**Issue by ashemedai** [dotnet/core#1700]
I hope I got the correct repository to file this.

We run automated OS builds that use the WindowsHosting.exe files to install the appropriate .NET Core runtimes.

This morning we noticed that our builds were failing. `DotNetCore.1.0.10_1.1.7-WindowsHosting.exe` and `DotNetCore.2.0.6-1-WindowsHosting.exe` are available and get downloaded, but their pointed to URLs `https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.7/dotnet-win-x64.1.1.7.zip` and  `https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.6/dotnet-win-x64.2.0.6.zip`, respectively, result in  an XML message stating `<Code>ResourceNotFound</Code>`, effectively a 404.

Can someone look into this?

**Comment by ashemedai** [comment]
See also dotnet/core-setup#4245

**Comment by leecow** [comment]
Something happed with the azure account which has been corrected. Should be good to go now.
