### ISSUE TITLE
Failing to download dotnet core packages from https://dotnetcli.azureedge.net/dotnet

### ISSUE THREAD

**Issue by bishal-pdMSFT** [dotnet/core#1701]
Getting 404 error while trying to download any dotnet SDK/runtime version. i.e. for runtime version 2.0.7 from https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-win-x64.2.0.7.zip, I get this error: Error: Unexpected HTTP response: **404**.

**Comment by bishal-pdMSFT** [comment]
Same error for https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.7/dotnet-runtime-2.0.7-win-x64.zip

**Comment by ashemedai** [comment]
See also #1700

**Comment by leecow** [comment]
Something happed with the azure account which has been corrected. Should be good to go now.
