### ISSUE TITLE
Is the table controller supported?

### ISSUE THREAD

**Issue by gayan1991** [dotnet/core#1706]
In previoud .net core environments, azure mobile sync services were not supported and because of that table controllers were replaced by api controllers?

With the .net core 3.0 coming up, are table controller sync services supported with the new .net core standard?

**Comment by DamianEdwards** [comment]
I think this is a question best asked of the Azure Mobile Services team. @paulbatum is that you these days?

**Comment by paulbatum** [comment]
Nope its not me. The appropriate place for this question is https://github.com/Azure/azure-mobile-apps-net-server - I would move it there.

**Comment by gayan1991** [comment]
@paulbatum Have you moved this issue to Azure Mobile apps or should I create new issue over there?

**Comment by Petermarcu** [comment]
@gayan1991 go ahead and move the issue over there. I'll close it here for now.
