### ISSUE TITLE
ModelBinding error with boolean values

### ISSUE THREAD

**Issue by WinthorpeCross** [dotnet/core#1711]
I have a potential problem with the ModelBinder in my ASP.NET Core  2.0 project.  I have the following 'Index' controller action:
```
[HttpGet]
public async Task<IActionResult> Index(SortFilterIndexOptions options) { ... }
```
The SortFilterIndexOptions are four parameters defined in the following class:

```
public class SortFilterIndexOptions
{
    public int SelectedBirdId { get; set; }
    public bool ShowAll { get; set; }
    public bool ShowInTable { get; set; }
    public int page { get; set; }
}
```
These enable the user to filter a paged index page using checkbox toggle buttons.

Everything works until I change 'ShowAll' bool member to TRUE and then try to navigate to a different page. The 'ShowAll' parameter part of the url then contains two bool values ('ShowAll=true, false'):

![screeshot](https://user-images.githubusercontent.com/35421339/41627649-0a0b992a-7419-11e8-8a51-082a1dcbfa1c.jpg)

which of course results in a parse error ('FormatException: String was not recognised as a valid Boolean').

My understanding that the ModelBinder in ordinary MVC automatically parses the TRUE from the true,false.

It only happens when the 'ShowAll' parameter is toggled to TRUE.

**Comment by eopeter** [comment]
Is it possible you have two ShowAll input name in your form?

**Comment by WinthorpeCross** [comment]
No, just one.  I have since refactored all the code but I have retrieved the original markup:

```
<form id="sort-filter-form" class="form-horizontal">
    <div class="form-group">
        <div class="col-sm-4">
            <label class="control-label">Select and view specific species...</label>
            @Html.DropDownListFor(m => m.SelectedBirdId,
                 new SelectList(Model.AllBirdsDropDownList, "BirdId", "EnglishName"),
                       new
                       {
                           @class = "form-control selectpicker showtick",
                           title = "Choose a bird species...",
                           data_live_search = "true",
                           data_show_subtext = "true",
                           onchange = "this.form.submit()"
                       })
        </div>
        <div class="col-lg-8">
            <label class="control-label">Filter or search the birds species list...</label>
            <div>
                <input asp-for="ShowAll" type="checkbox" data-toggle="toggle" onchange="this.form.submit()" data-on="All birds" data-off="Common birds">
            </div>
             <div>
                <input asp-for="ShowInTable" type="checkbox" data-toggle="toggle" onchange="this.form.submit()" data-on="Table" data-off="Thumbnails list">         
            </div>
        </div>
    </div>
</form>
```

**Comment by leecow** [comment]
Issue moved to https://github.com/aspnet/Home/issues/3246
