### ISSUE TITLE
ASP.NET Core 2.1 Web API wont start with Microsoft.AspNetCore.All 2.1.1

### ISSUE THREAD

**Issue by poteb** [dotnet/core#1712]
ASP.NET Core 2.1 Web API wont start with Microsoft.AspNetCore.All 2.1.1

I'm debugging my Web API from VS 2017 (15.7.1) and it's working with Microsoft.AspNetCore.All 2.1.0.
But if I update Microsoft.AspNetCore.All to 2.1.1 it wont start up. It doesn't even give me an exception, the console window flashes briefly and then the debugger detaches. Downgrading to 2.1.0 fixes this. No help in Windows event log.

**dotnet --info**
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by leecow** [comment]
cc @muratg

**Comment by leecow** [comment]
Moving to ASPNET repo - https://github.com/aspnet/Home/issues/3245
