### ISSUE TITLE
Confusion on ARM support matrix

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/core#1713]
# Title

There are several different docs about dotnet core around ARM support but they are conflict to each others.

# General

- The following link: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions shows `NET Core 2.1 is supported on the following Linux 64-bit (x86_64 or amd64) distributions/versions`, I guess the doc want to tells me dotnet core 2.1 support ARM64 on any linux?

- The following link: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux shows `ARM32 support starts with Debian 9 and Ubuntu 18.04. Earlier versions of those distros are not supported on ARM32`, So why this doc doesn't tells me anything about ARM64?

- The following link: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#windows shows dotnet core 2.1 only support Windows x86/x64, it doesn't support any Windows ARM.

- The following link: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids shows there is not Linux ARM RID instead, there are ARM RID for Windows?

My goal is  to publish a self-contained dotnet core app that target ARM.
I want to know what kind of ARM i can target:
`win-arm32` ?
`win-arm64` ?
`linux-arm32` ?
`linux-arm64` ?

**Comment by leecow** [comment]
The currently supported ARM targets are detailed in the [2.1-supported-os](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md) document.  ARM32 on Debian and Ubuntu are the supported platforms at the moment. 

We have begun building ARM64 runtime and SDK. These are in the experimental stages right now. The same is true for the Win ARM builds. 

@richlander for additional info and to fact check me.

**Comment by TingluoHuang** [comment]
Should we update all docs to make them consist?

**Comment by leecow** [comment]
Where needed, yes. 

* https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions says nothing about ARM so needs to have current info added. @JRAlexander 
* https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux is current and correct?
* https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux should be thought as as API documentation and is not a statement of support.

**Comment by TingluoHuang** [comment]
I assume your are reference to  https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids for `should be thought as as API documentation and is not a statement of support.`

**Comment by leecow** [comment]
Yes, sorry about that!

**Comment by arokoyo** [comment]
I know one day I will write a matrix code

**Comment by Petermarcu** [comment]
Does this leave this where there is just the need to have the docs updated as mentioned above?

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions says nothing about ARM so needs to have current info added. @JRAlexander

**Comment by karelz** [comment]
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions already mentions ARM32 from PR https://github.com/dotnet/docs/pull/6901 on 8/8. Closing.
