### ISSUE TITLE
Deploying ASP.NET Core from git with kudu fails because of locked pdb file

### ISSUE THREAD

**Issue by ellern** [dotnet/core#1721]
I got a couple of web apps running .NET Core 2.1.0 on different Azure service plans running on Windows. 

Lately I've started getting a file locked error when deploying from git on Azure. Almost every single time I push, it errors out telling me the file (Site.Views.pdb) is in use. Restart app, redeploy works every time, but it's annoying. I found out if I push two changes within a short timespan then there is no lock on the pdb file and the deployment works as expected.

Remote debugging is disabled for the web apps, so I have no idea why there is a lock on the pdb file.

I can't remember having any issues before I updated my web apps to .NET Core 2.0.0

```
KuduSync.NET from: 'D:\local\Temp\8d5d80c09bb9d1c' to: 'D:\home\site\wwwroot'
Error: Failed to change file that is currently being used "D:\home\site\wwwroot\Site.Web.Views.pdb"
Copying file: 'Site.Web.deps.json'
Copying file: 'Site.Web.runtimeconfig.json'
Copying file: 'Site.Web.Views.dll'
Copying file: 'Site.Web.Views.pdb'
Failed exitCode=1, command="kudusync" -v 50 -f "D:\local\Temp\8d5d80c09bb9d1c" -t "D:\home\site\wwwroot" -n "D:\home\site\deployments\c764c8a77ef871df3f13953049f5bc51088cac1f\manifest" -p "D:\home\site\deployments\bd8a3c2f17acba1e45b1c14276d9530f24e5a649\manifest" -i ".git;.hg;.deployment;deploy.cmd"
An error has occurred during web site deployment.
Error: Failed to change file that is currently being used "D:\home\site\wwwroot\Site.Web.Views.pdb"\r\nD:\Program Files (x86)\SiteExtensions\Kudu\74.10611.3437\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

![screen shot 2018-06-22 at 09 01 15](https://user-images.githubusercontent.com/4930511/41796425-c3d23612-7666-11e8-965b-a99180d6853b.png)

This issue is copied from projectkudu/kudu#2788

**Comment by leecow** [comment]
@muratg, please take a look.

**Comment by muratg** [comment]
@pakrym could you take a look? Thanks.

**Comment by leecow** [comment]
Moved to https://github.com/aspnet/Home/issues/3269
