### ISSUE TITLE
Add advance math class 

### ISSUE THREAD

**Issue by khoshroomahdi** [dotnet/core#1724]
# Issue Title
Please add a library like math.net to. Net core
Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by leecow** [comment]
Issue moved to [dotnet/corefx #30671](https://github.com/dotnet/corefx/issues/30671) via [**ZenHub**](https://www.zenhub.com/)
