### ISSUE TITLE
No AccountController and ManageController from auth Individual template

### ISSUE THREAD

**Issue by retifrav** [dotnet/core#1731]
# No AccountController and ManageController from auth Individual template

Template

```
dotnet new mvc --auth Individual
```

no longer provides `AccountController` and `ManageController`.

## Description

With host version 2.0.5 this template generates those controllers and with host version 2.1.0 it does not. See the listings below.

### Host 2.0.5

```
$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Folder structure after `dotnet new mvc --auth Individual`:

```
$ tree
.
├── Controllers
│   ├── AccountController.cs
│   ├── HomeController.cs
│   └── ManageController.cs
...
```

### Host 2.1.0

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]
```

Folder structure after `dotnet new mvc --auth Individual`:

```
$ tree
.
|-- Controllers
|   `-- HomeController.cs
...
```

## Question

Was this change intentional?
If yes, then how does one gets those controllers generated with host version 2.1.0 (or later)?
If no, then I guess it is a bug.

*If I chose the wrong tracker to report this issue, sorry for that and please guide me to the right one.*

**Comment by leecow** [comment]
Moved to ASP.
