### ISSUE TITLE
System.Data.SqlClient 4.4.3 is not compatible with netcoreapp 2.0

### ISSUE THREAD

**Issue by shpsyte** [dotnet/core#1735]
# System.Data.SqlClient 4.4.3 is not compatible with netcoreapp 2.0

Hi, after install .net core 2.1, I just Create WebApp using .net Core 2.0.8 and I get this error.

# General

I Know if downgrade to .net core 2.0.3 I resolve this, but why this happens ?

.Net Core 2.0.8
![capturar](https://user-images.githubusercontent.com/3891610/42039291-6d2058b0-7ac3-11e8-814e-ac50cd8eab8f.PNG)

**Comment by shpsyte** [comment]
Someone ?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #31052](https://github.com/dotnet/corefx/issues/31052) via [**ZenHub**](https://www.zenhub.com/)
