### ISSUE TITLE
Cant login to rabbitmq through RestClient on 2.1.1

### ISSUE THREAD

**Issue by PavelMekhnin** [dotnet/core#1739]
After I updated project to 2.1.1 my restClient stoped login to rabbit - Unauthorized. 
![image](https://user-images.githubusercontent.com/5836560/42077474-477395c4-7ba3-11e8-9b02-0d04c56764a7.png)
But if I'm trying login with browser - evething works fine

**Comment by Eilon** [comment]
@Petermarcu this doesn't seem related to ASP.NET Core directly.

@PavelMekhnin - can you provide more info about the problem, such as your code, or other project info?

**Comment by Petermarcu** [comment]
@PavelMekhnin can you also let us know what you updated from? For example, were you on 2.1.0 and went to 2.1.1 or were you on 1.0 and moved to 2.1.1?

**Comment by PavelMekhnin** [comment]
@Petermarcu I updated from 2.0.6 to 2.1.1 and it broked. I'm sure it's bacouse of update.
how I send request before and its worked:
`var ub = new UriBuilder(managementUri)
                {
                    UserName = rabbitMqConfig.User,
                    Password = rabbitMqConfig.Password
                };

                var client = new RestClient(ub.Uri);
                try
                {
                    if (HasHaModeAllPolicy(queue, client, rabbitMqConfig)
                        || TryCreatePolicy(queue, client, rabbitMqConfig))
                    {
                        return true;
                    }
                }`
and method
`        private bool TryCreatePolicy(string queue, RestClient client, RabbitMqConfig config)
        {
            var createQueuePolicyRequest = new RestRequest
            {
                RequestFormat = DataFormat.Json,
                Resource = $"api/policies/%2f/ha-{queue}",
                JsonSerializer = new RestSharpNewtonsoftSerializer(),
            };

            var policy = _rmqHaClusterPolicyFactory.CreatePolicy(queue);
            createQueuePolicyRequest.AddBody(policy);

            var response = client.Put(createQueuePolicyRequest);
            return response.IsSuccessful;
        }`
how I fix after update: Added to **createQueuePolicyRequest** 
`Credentials = new NetworkCredential(config.User, config.Password)`

**Comment by davidsh** [comment]
@PavelMekhnin what OS are you using? Windows?  Linux?

**Comment by PavelMekhnin** [comment]
@davidsh Linux
@karelz yes, before it  worked with just uriBuilder and cridensionals 
```
 UriBuilder(managementUri)
                {
                    UserName = rabbitMqConfig.User,
                    Password = rabbitMqConfig.Password
                };
```

**Comment by davidsh** [comment]
.NET Core 2.0 on Linux used CurlHandler as the HTTP stack.  CurlHandler supported embedded username/password in the URL with formats such as:

```
http://username:password@example.com/
```

.NET Core 2.1 on Linux uses SocketsHttpHandler.  SocketsHttpHandler is following a stricter security model where embedded username/password is ignored in the URL.

In general, the recommendation is to use place username/password in the HttpClientHandler.Credentials property using a NetworkCredential object.

**Comment by karelz** [comment]
Sounds like by design then. @PavelMekhnin is it ok to close? Or do you think the workaround is not acceptable?
