### ISSUE TITLE
Please include deleting ASP.NET Core Runtime in Uninstaller

### ISSUE THREAD

**Issue by VSDekar** [dotnet/core#1740]
We had huge problems with dotnet core SDK 2.1.301 so we went back to 2.1.300. But the uninstaller did not delete the ASP.NET Core runtime.

Because the runtime was still there after we uninstalled 2.1.301 we got some very strange problems.

So my expectation is, that everything that an installer installs on the system will be deleted by the uninstaller. I had to delete manually the folder in `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App`

Thx

**Comment by leecow** [comment]
@JunTaoLuo - can you have a look and move this issue to the right repo?

**Comment by JunTaoLuo** [comment]
This issue was moved to aspnet/SetupSharedFramework#10

**Comment by JunTaoLuo** [comment]
Moved the issue again to https://github.com/aspnet/Home/issues/3286 since it's easier to discuss this in a public repo.
