### ISSUE TITLE
dotnet tool install have trouble installing when an private feed is in nuget.config

### ISSUE THREAD

**Issue by DerAlbertCom** [dotnet/core#1741]
# Issue Title

dotnet tool install  -g foobar  does not install any tool if private nuget feed is in the nuget.config which requires authentication.

# General

I tried 'dotnet tool install -g sourcelink', and have in the the global nuget.config the company nuget feed from vsts.

```
C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error : Fehler beim Abrufen von Informationen zu "sourcelink" aus der Remotequelle "https://XYZ.pkgs.visualstudio.com/_packaging/172bc92f-50b3-48bc-b4cf-9555b7f0fd10/nuget/v3/flat2/fo/index.json". [C:\Users\DerAl\AppData\Local\Temp\ctdjxp0q.bbs\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\DerAl\AppData\Local\Temp\ctdjxp0q.bbs\restore.csproj]
```

If i comment out the private feed out in then nuget.config, then the tool get's installed.

nuget restore has not problem with the nuget feed. dotnet restore (which should not be used with VSTS because you have to store a Cleartext PAT in the nuget.config) clearly has the same problem like dotnet tool

**Comment by leecow** [comment]
Issue moved to [dotnet/cli #9586](https://github.com/dotnet/cli/issues/9586) via [**ZenHub**](https://www.zenhub.com/)
