### ISSUE TITLE
*** Error in `dotnet': double free or corruption (fasttop): 0x74918920 ***

### ISSUE THREAD

**Issue by RhavoX** [dotnet/core#1744]
# Issue Title

After running a background service on Raspberry Pi for about a week this is the crash message I've been given.

*** Error in `dotnet': double free or corruption (fasttop): 0x74918920 ***

No other information was given.

# General
Occured on latest Raspbian Stretch

Dotnet version:
  Version: 2.1.1
  Commit:  6985b9f684

**Comment by leecow** [comment]
I'm sure we'll need more information. @RussKeldorph to help with the right questions.

**Comment by RussKeldorph** [comment]
@RhavoX 

There's not much we can do without more information--preferably instructions to reproduce the crash.

Can you provide a callstack when the crash happens at least?

Is this a regression from a previous .NET Core version, or is 2.1.1 the first build you've tried?

Others may have better advice and/or questions.

@jkotas @janvorli @dotnet/dotnet-diag

**Comment by jkotas** [comment]
This is duplicate of https://github.com/dotnet/coreclr/issues/18486. The memory corruption at this calllstack has been reported by multiple people. We were not able to get to the bottom of it yet.
