### ISSUE TITLE
Attempt to update Microsoft.AspNetCore.App from 2.1.0 to 2.1.1 fails everytime

### ISSUE THREAD

**Issue by zinov** [dotnet/core#1746]
Attempt to update Microsoft.AspNetCore.App from 2.1.0 to 2.1.1 fails everytime

**I have an App that is compiling with Microsoft.AspNetCore.App in 2.1.0, trying to update it to 2.1.1 through Manage Nuget Package always fails, even if I update the version directly from the csproj too.**

Apart from this question, If I try to make an update on my csproj manually to any version and let's say the Visual Studio finds a conflict with another Nuget package, from that point on, I can't make any updates again through the Manage Nuget Package because it sees those errors as compiled errors, and the only workaround to fix them is by editing the csproject and removing the conflicting references to add them again with the previous version which were not failing.

**Comment by EnricoReich** [comment]
A few days ago I had the same problem and that turned out to be a problem with SDK v2.1.300.
Installing SDK version 2.1.301 fixed it for me.

**Comment by zinov** [comment]
It worked for me

**Comment by Petermarcu** [comment]
@Eilon as FYI 

I'm going to close this for now. Let us know if using the 2.1.301 or higher SDK doesn't fix this for you.
