### ISSUE TITLE
how to add assembly info to PrecompiledViews dll generated by dot net core 2.0

### ISSUE THREAD

**Issue by parthakbari** [dotnet/core#1751]
# how to add assembly info to PrecompiledViews dll generated by dot net core 2.0

# General

views in my .net core 2.0 project is getting generated in PrecompiledViews dll..

How to add the assembly info to this dll, information such as company name, copyrights etc..

Tried to some tag in project file but didn't work

      `<PropertyGroup Label="Assembly">
           <AssemblyName>HegicMvc_Poc.PrecompiledViews</AssemblyName>
           <PackageId>Library</PackageId>
           <Product>Library</Product>
           <Authors>StackOverflow Answer</Authors>
           <Company>Test</Company>
           <Description>Library</Description>
           <Copyright>Copyright © 2016 - 2017 Test</Copyright>
           <Version>2.0.0</Version>
           <AssemblyVersion>1.0.0</AssemblyVersion>
           <FileVersion>1.0.0</FileVersion>
      </PropertyGroup>` 

Is there any way to do this?

**Comment by Petermarcu** [comment]
@Eilon @muratg

**Comment by Eilon** [comment]
@pranavkm can you move this issue to the appropriate repo and answer it?

I believe the short answer is: by default the precompiled views assembly will use the same metadata as the app's metadata, though there might also be a way to customize it beyond that.

**Comment by pranavkm** [comment]
This issue was moved to aspnet/Mvc#8044
