### ISSUE TITLE
Reference Issue: System.Web.Services

### ISSUE THREAD

**Issue by Sivasekare** [dotnet/core#1752]
Hello, 

Below is the error message im getting when trying to run my ASP.Net Core app that references System.Web.Services.dll.  Please help me to address the same.

System.BadImageFormatException
  HResult=0x80131058
  Message=Could not load file or assembly 'System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

Inner Exception 1:
BadImageFormatException: Cannot load a reference assembly for execution.

**Comment by Petermarcu** [comment]
Looks like your application is getting a reference assembly that you are trying to load and execute? @muratg @Eilon , can someone help provide guidance here?

**Comment by Eilon** [comment]
@Sivasekare can you provide more info on your app, such as the contents of the CSPROJ file? Or perhaps upload your app to GitHub so we can take a look?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
