### ISSUE TITLE
Is there any real world web site running dotnet core with unix-like os?

### ISSUE THREAD

**Issue by Tony427** [dotnet/core#1753]
Hello guys. 

Is there any well-known real world web site using dotnet core on RHEL or other unix-like OS ?
Just have to convince the clients to believe that dotnet core is mature enough using linux os.

thx!

**Comment by manuelcardoso** [comment]
Well… I heard that there is a (internal) real world web application who manages customer support flow and reports of a well-known swedish group.
ASP.NET Core WebApp with WebApi also on a Ubuntu OS

**Comment by leecow** [comment]
I can't provide details but can acknowledge large .NET Core investments on Linux by the likes of American Express, General Motors, Barclays, Morgan Stanley, Walmart and others.

**Comment by shmellyorc** [comment]
I am running dotnet core standard 2.1 on a ubuntu 18.10 server using an async tcp game server. its not "asp.net" but it has been running for months with over 25-50 ppl daily. no issues yet.

**Comment by Eilon** [comment]
@DamianEdwards / @jongalloway / @shanselman - do we have any public-facing list of sites running ASP.NET Core, especially on Linux? Maybe some whitepapers? I did a few searches and couldn't find anything.

**Comment by Eilon** [comment]
I'm closing this issue because it is somewhat off topic for this forum. If you do have further ASP.NET Core questions, please post them at https://github.com/aspnet/Home. Thanks!
