### ISSUE TITLE
dotnet core  on  arm-linux .  How to distinguish between armel and armhf.

### ISSUE THREAD

**Issue by wq807319473** [dotnet/core#1758]
1.    dotnet publish -r linux-arm         The content of the publish is  about armel or about armhf ?
2.    On command,  How to distinguish that ?

AND ,          When will arm64 be released ?

**Comment by Petermarcu** [comment]
There are no concrete dates for arm64 although it is being worked on. linux-arm is armhf. I don't think there are armel builds available but I may be wrong. @RussKeldorph @jkotas in case they know more.

**Comment by jkotas** [comment]
Samsung has been publishing armel packages for Tizen: https://www.nuget.org/packages/runtime.tizen.4.0.0-armel.Microsoft.NETCore.App/

cc @alpencolt @gbalykov

**Comment by Petermarcu** [comment]
Looks like the answer then is to use `linux-arm` for armhf and `tizen-arm` for armel for now. I'm going to close this issue. Let us know if you have other questions.
