### ISSUE TITLE
List of .NET Core compatible NuGet packages

### ISSUE THREAD

**Issue by hickford** [dotnet/core#176]
Most the packages on https://www.nuget.org/packages appear to be incompatible with .NET Core:

    >dotnet restore
    Package Microsoft.Net.Http 2.2.29 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). 
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Is there a list anywhere of which NuGet packages *are* compatible with .NET Core? I'd like to think about what I could build.

**Comment by hickford** [comment]
See also https://github.com/NuGet/NuGetGallery/issues/3098

**Comment by blackdwarf** [comment]
@hickford the NuGet/NuGetGallery seems like a much better place for this issue. Closing this one in favor of NuGet/NuGetGallery#3098.
