### ISSUE TITLE
dotnet core in Chromium Native Client

### ISSUE THREAD

**Issue by tekrat** [dotnet/core#1761]
# .NET Core on Chromium Native Client

Is there a planned to the NaCI / Chromium Native Client?

# General

I want to run .NET Core applications on my ChromeBook.  Porting this to Native Client would open every platform that runs Chrome.

**Comment by Petermarcu** [comment]
@danroth27

**Comment by danroth27** [comment]
I believe NaCl has been largely deprecated in favor of WebAssembly. We are working on bringing [.NET to WebAssembly via Mono](http://www.mono-project.com/news/2017/08/09/hello-webassembly/, which is the basis for the [Blazor](https://blazor.net) experimental project.
