### ISSUE TITLE
Feature Request: FindSystemTimeZoneById enhancement

### ISSUE THREAD

**Issue by devkws** [dotnet/core#1762]
It would be nice if .netcore could remove the idiosyncrasies of running code on windows vs linux by adding methods which would handle conversions for the developer.

As an example: TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time") fails on linux.
Because of this we must build extensions to handle conversions so the app runs on both windows and linux. 

example of workaround:
```
            try
            {
                easternZone = TimeZoneInfo.FindSystemTimeZoneById("America/New_York");
            }
            catch (TimeZoneNotFoundException)
            {
                easternZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
            }
```

**Comment by kenleese** [comment]
https://github.com/dotnet/corefx/issues/11897

**Comment by devkws** [comment]
I see that this is a duplicate, closing
