### ISSUE TITLE
SqlConnection open method hangs connecting to SQL Server 2005 when running the core app on linux box

### ISSUE THREAD

**Issue by vsundaralingam** [dotnet/core#1763]
I am using .NET Core 2.1 and System.Data.SqlClient 4.5.1 to connect to SQL Server 2005. It works great on a windows machine but running the same app in Linux machine just hangs indefinitely in  connection.Open() line.

Here is the linux server and .NET CORE info:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Please let me know if you need any other details.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #30961](https://github.com/dotnet/corefx/issues/30961) via [**ZenHub**](https://www.zenhub.com/)
