### ISSUE TITLE
Debug symbols link in 2.1.2 download release notes looks wrong

### ISSUE THREAD

**Issue by luqq** [dotnet/core#1769]
In
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.2-download.md
Debug symbols for:
Shared Framework:
https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/coreclr-2.1-preview1-symbols.zip
and Runtime:
https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/corefx-2.1-preview1-symbols.zip

**Comment by Petermarcu** [comment]
@dagood do you know what the appropriate links are?

**Comment by dagood** [comment]
I don't. /cc @leecow @SusLes (+Padmasri, but I don't know the alias)

The correct links should be CoreCLR, CoreFX, and Core-Setup, like [2.1.1](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.1-download.md).
