### ISSUE TITLE
.NET Core tools telemetry must be opt in

### ISSUE THREAD

**Issue by gguimaraesbr** [dotnet/core#177]
We must avoid unwanted data sharing giving users the ability to consciously agree to collect and share usage data.

**Comment by svick** [comment]
There's already a discussion about this here: https://github.com/dotnet/cli/issues/3093.

**Comment by gguimaraesbr** [comment]
@svick Should I close this one?

**Comment by svick** [comment]
@gguimaraesbr Yeah, I think there is no reason to have two separate issues.

**Comment by gguimaraesbr** [comment]
Closing because there is another issue regarding this theme: https://github.com/dotnet/cli/issues/3093
