### ISSUE TITLE
vs2017 new project shows wrong version of .net core 2.1.2

### ISSUE THREAD

**Issue by dncAdmin** [dotnet/core#1772]
After installing .net core SDK 2.1.302 with Runtime 2.1.2 ,

vs2017 15.7.5 -> new project -> asp.net core project still shows the version of 2.1.1 and 2.1.0 in the Nuget and SDK dependence.

it should be 2.1.2

![image](https://user-images.githubusercontent.com/38060128/42567756-57f52f2c-853d-11e8-85d9-0169e173af07.png)

PC:

Win10

**Comment by joshfree** [comment]
This issue was moved to dotnet/project-system#3791
