### ISSUE TITLE
Unable to run self contained on 64 bit Red Hat

### ISSUE THREAD

**Issue by jjxtra** [dotnet/core#1783]
I am running Red Hat 64 bit. I get the following error when running self-contained x64 Linux builds:
```
cannot execute binary file
```

This is with latest .NET core as of July 12, 2018 (2.1.302). I am running in Virtual Box. This build works fine on Ubuntu Server 64 bit.

Here is CPU info:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD Ryzen Threadripper 1950X 16-Core Processor
Stepping:              1
CPU MHz:               3892.684
BogoMIPS:              7785.36
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              32768K
NUMA node0 CPU(s):     0
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt rdtscp lm art rep_good nopl extd_apicid pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm cr8_legacy abm sse4a misalignsse 3dnowprefetch retpoline_amd vmmcall fsgsbase avx2 rdseed clflushopt arat
```

Please advise...

**Comment by Petermarcu** [comment]
How did you publish your application?

**Comment by jjxtra** [comment]
Visual Studio
![publishscreenshot](https://user-images.githubusercontent.com/1271832/42657727-5ca770ea-85e0-11e8-8127-d7612642bafe.png)
. Same published binary works fine on Ubuntu Server. Screenshot attached.

**Comment by Petermarcu** [comment]
Is this Redhat 7.2 or higher?

**Comment by jjxtra** [comment]
Yes.

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

**Comment by Petermarcu** [comment]
Looks like it should have worked just like it did on Ubuntu. @janvorli @jkotas @jeffschwMSFT @steveharter  any ideas?

**Comment by jjxtra** [comment]
I don't know if it makes a difference, but I am running in VirtualBox on a threadripper 1950x CPU. Perhaps it is new enough to not quite be supported?

**Comment by Petermarcu** [comment]
Adding @RussKeldorph

**Comment by jjxtra** [comment]
It's also worth noting that I can run ``` /usr/bin/dotnet MyApp.dll ``` and it works fine.

**Comment by steveharter** [comment]
@jjxtra some thoughts
1) Verify the permission of your executable. Compare with `/opt/rh/rh-dotnet21/root/usr/bin/dotnet`
2) Verify you have the correct executable. Run `file <myapp>` to see if it reports back a valid executable file and as x86-64. Compare that with `file /opt/rh/rh-dotnet21/root/usr/bin/dotnet`
3) Run `strace` on your executable and report back the output

**Comment by jjxtra** [comment]
```chmod +x``` fixed it! That's awesome. Wish the error message was more clear, but that is not a dotnet issue. I am not an expert Linux user apparently either. Thanks so much for the suggestion.
