### ISSUE TITLE
Suggestion: Dotnet core project template to support Grpc with DI and additional middle-wares

### ISSUE THREAD

**Issue by saurabhlogward** [dotnet/core#1784]
# Issue Title
dotnet core has some basic template to work with MVC based web api's. These template supports many things like DI and support for various middle-wares. But no template as such to support Grpc along with DI and middle-wares. 

# General

My Development Environment:
dotnet core 2.1.301
ubuntu 16.04

What I am trying to do is to leverage the web api template to use the Grpc, in order to make use of the features like DI, middle-wares etc. But the way I am doing is bit ugly, I myself is not satisfied with it. I did refer to some of the git repositories which has some solution like:

https://github.com/m-andrei/grpc-example-for-.net-core/tree/master/Grpc.Example.Server

but still, I think it will be a good idea to have some standard/official dotnet core project template with combined support for following:
1. Grpc
2. DI
3. Middle-wares (tracing, monitoring etc)

**Comment by davidfowl** [comment]
Google's GPRC server doesn't integrate with DI, nor does it have a middleware pipeline (AFAIK). We haven't done enough work yet in this area to give a definitive answer but I can tell you the current thinking (at least my thinking). 
- We're working on HTTP2 support right now in Kestrel
- Support GRPC as a feature within MVC itself

> But the way I am doing is bit ugly, I myself is not satisfied with it. I did refer to some of the git repositories which has some solution like

The sample has a bunch of problems but to your point there is no guidance here and we could do a better job by working with google to come up with something that fits more naturally.

**Comment by saurabhlogward** [comment]
So if someone want to work with dotnet core with grpc framework, then they have to cook their own project structure(like the one in the link)? 
Any suggestions ? 
When will the points you mentioned about http2 support and grpc as a feature available ?

**Comment by davidfowl** [comment]
> So if someone want to work with dotnet core with grpc framework, then they have to cook their own project structure(like the one in the link)?

You'd probably host the GRPC server side by side with the main server instead of replacing it since it doesn't compose very well. For middleware, you'd have to use whatever google provided. Basically, the GRPC support that exists today from Google is a different framework that doesn't integrate at all. I'm not sure integrating it is trivial without design changes to their stack but I haven't looked deeply enough to make that call.

> When will the points you mentioned about http2 support and grpc as a feature available ?

HTTP2 is slated for ASP.NET Core 2.2 GRPC would be after that (GRPC requires HTTP2).

**Comment by Eilon** [comment]
Closing this issue because there are no current plans to implement these suggestions. If you have further thoughts, please log an issue in the ASP.NET Core Templating repo: https://github.com/aspnet/Templating/. Thanks!
