### ISSUE TITLE
Incorrect link on https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

### ISSUE THREAD

**Issue by BJMdotNET** [dotnet/core#1785]
On the page https://github.com/dotnet/core/blob/master/release-notes/download-archive.md , in ".NET Core 2.0", the ""download" link of "2018/05/08 | 2.0.7 with SDK 2.1.200" is broken. Links to https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.200-sdk-download but this gives a 404.

**Comment by Petermarcu** [comment]
@leecow

**Comment by Petermarcu** [comment]
Fixed with https://github.com/dotnet/core/commit/aedc86a1963cafd6228a455c3880a02ab25d8901
