### ISSUE TITLE
Links for debug symbols of 2.1.2 release don't work

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/core#1786]
On page https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.2-sdk-download.md the links to the debug symbols fail to download.  Getting an invalid response error.  Both the Shared Framework and Runtime links fail.

**Comment by danmosemsft** [comment]
@dleeapho do you know who owns this? Powershell folks need it to do profiling for us.

**Comment by dleeapho** [comment]
@leecow , @dagood PTAL.

**Comment by danmosemsft** [comment]
@SteveL-MSFT good to go?

**Comment by SteveL-MSFT** [comment]
@danmosemsft thanks for following up on this, just tried a link and worked.  Thanks.
