### ISSUE TITLE
Link for "Download the latest .NET Core SDK" on the main page Readme.md is broken

### ISSUE THREAD

**Issue by drk-mtr** [dotnet/core#1787]
# Issue Title

Link for "Download the latest .NET Core SDK" on the main page Readme.md (URL https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.302-download.md) is broken

# General

Thanks to the dotnet core team for a brilliant product / ecosystem. One issue is that I often find versioning difficult i.e. it's hard to find a "single source of truth" that will tell me which is the latest release version, which is the latest prerelease version etc.

**Comment by leecow** [comment]
Thanks @drk-mtr - fixed. We're working on some structural and content updates which we hope will help.
