### ISSUE TITLE
releases.json file has invalid entry for sdk-mac-x64 

### ISSUE THREAD

**Issue by vineetmimrot** [dotnet/core#1790]
https://github.com/Microsoft/vsts-tasks/issues/7731

Because of the [recent commit](https://github.com/dotnet/core/commit/2f2194c11cff7248c57f2f0938f3570b807e0ba5#diff-134da986ed7a3f87e53f741ec8db93c2) in releases.json file, VSTS DotNetCore Installer Task is failing. We have raised the [Pull request](https://github.com/dotnet/core/pull/1789), can you please merge it on priority.

**Comment by leecow** [comment]
The current entry is a workaround until an issue with https://download.microsoft.com can be resolved. Hopefully that issue will be addressed in the next day or so, then the releases.json can be updated. There is a breaking change coming to the json file in which the entire url will be included in the file metadata. Have a look at https://github.com/dotnet/core/blob/master/release-notes/releases-v2.json for the direction.
