### ISSUE TITLE
Character encoding errors with .NET Core on Linux

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/core#1791]
This has been driving me batty for days, and I've finally got it down to a simple, reproducible issue.

I have a NUnit test project, which is .NET Core 2.1. It references a library (let's call it "Core") which is .NET Standard 2.0.

In my test project:
```
	[TestCase(true, false)]
	[TestCase(false, false)]
	[TestCase(false, true)]
	public void ShouldStartWith(bool useInternal, bool passStartsWith)
	{
		var result = useInternal ? StartsWithQ("¿Que?") : StringUtilities.StartsWithQ("¿Que?", passStartsWith ? "¿" : null);
		result.ShouldBeTrue();
	}

	public static bool StartsWithQ(string s)
	{
		return _q.Any(q => s.StartsWith(q, StringComparison.InvariantCultureIgnoreCase));
	}
```
and in the `Core` project in the `StringUtilities` class:
```
	public static bool StartsWithQ(string s, string startsWith = null)
	{
		return startsWith == null
			? _q.Any(q => s.StartsWith(q, StringComparison.InvariantCultureIgnoreCase))
			: s.StartsWith(startsWith, StringComparison.InvariantCultureIgnoreCase);
	}
```
Both classes have defined a list of special characters:
```
	private static readonly List<string> _q = new List<string>
	{
		"¡",
		"¿"
	};
```
In a Windows environment, all test cases pass. But when the same tests run in the Linux environment, the test case `ShouldStartWith(False,False)` fails!

That means that when everything is running in the test project, the string comparison works correctly, and even if you pass the special characters to the `StringUtilities` method, the comparison works. But when you compare to a string that was compiled in the Core project, the special characters are no longer equivalent!

Is this a .NET bug? How to work around it?

P.S. I have also asked this question on [StackOverflow](https://stackoverflow.com/q/51364469/7850), in case you want to answer it there, too.

**Comment by joshfree** [comment]
Hi @shaulbehr, I've moved this issue to dotnet/corefx where System.Globalization and the libicu dependency for unicode casing and coalescing support for linux lives.

The new issue is https://github.com/dotnet/corefx/issues/31278
