### ISSUE TITLE
The links on the release page for this repo are often broken

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core#1792]
# Issue Title
The links on the release page for this repo are often broken.

# General
The links to the repo tags in many releases on https://github.com/dotnet/core/releases are broken.
We use this page to find the tags of the repos that we need to build together.

- Is there somewhere more reliable that we can find the combination of repo tags we need to build for each SDK release?
- Can you do an audit of the links and improve your process to be more accurate?

Here are some examples, just from the latest round of patches:
2.1.2, cli
2.0.9, coreclr, forefx
1.1.9, cli
1.0.12, cli

**Comment by leecow** [comment]
Went through cli, core, coreclr, corefx and coresetup releases back to 1.1.8 and corrected links. Hopefully I didn't miss anything.
