### ISSUE TITLE
Problem with building URLs with Areas in .NET Core 2.1 

### ISSUE THREAD

**Issue by piecho1991** [dotnet/core#1796]
I have problem with URL-s in ASP.NET Core 2.1 Web Application.

I have used code like below:
```html
<a asp-area="Area" asp-controller="Controller" asp-action="List">nasihdfgasih</a>
```

and Razor is generating wrong URL not like `http://example.com/Area/Controller/List` but `http://example.com/Controller/List?area=Area`.

My routes configuration:
```csharp
app.UseMvc(routes =>
{
	routes.MapRoute(
		name: "default",
		template: "{controller=Home}/{action=Index}/{id?}"
	);

	routes.MapRoute(
		name: "areas",
		template: "{area:exists}/{controller=Home}/{action=Index}/{id?}"
	);
});
```

**Comment by Eilon** [comment]
This issue was moved to aspnet/Routing#623
