### ISSUE TITLE
netcore  home directory not accessible

### ISSUE THREAD

**Issue by JaneConan** [dotnet/core#1797]
When I runing web project on linux , the console show this error.
dotnet sdk 2.1.302

**Comment by JaneConan** [comment]
Sorry, I'm in a bit of a hurry. This is the case, we publish the Web application to the Linux arm64, 

the direct use of the dotnet instructions to run,

When runing to insert data, console prompts 

[Netcore home directory is inaccessible: Insufficient permissions!]

Could it be that the Wwwroot folder does not give permissions?

**Comment by leecow** [comment]
Would it be possible to give a detailed example of your configuration, or even better, a sample project. As it is, I don't think there's enough information for us to go on to try and help.
