### ISSUE TITLE
Visual Studio 2015 on .NET Core: F# needs to be able to change the file order

### ISSUE THREAD

**Issue by Thorium** [dotnet/core#180]
File order is significant in the F# language project.
The Visual Studio .NET can do it for normal .NET projects.
But on .NET Core, project.json, the Visual Studio is not able to change the file order.

**Comment by blackdwarf** [comment]
@cartermp can you comment on this?

**Comment by cartermp** [comment]
Yep.  The project system in VS for project.json-based projects does not support file order.  You need to specify this in the project.json file itself, under `buildOptions`.

**Comment by Thorium** [comment]
Is the plugin open source? Shouldn't be so hard to add the Visual Studio file order to come from buildOptions instead of alphabetical order?

**Comment by cartermp** [comment]
There isn't a plugin that I'm aware of.  If you're referring to the *existing* project system in Visual Studio, then no, I do not believe that is open source.

**Comment by blackdwarf** [comment]
@cartermp @Thorium can we close this issue?

**Comment by cartermp** [comment]
Let's close it out.  This is something that's being looked at with the new project system.  File ordering is a requirement for F# there, anyways.
