### ISSUE TITLE
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request

### ISSUE THREAD

**Issue by AhmedMKamal** [dotnet/core#1803]
I got this error when I tried to run a released app

Command used to publish `dotnet publish --configuration Release`

Result:
```
Hosting environment: Production
Content root path: /path-to-my-app/publish
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLFDGHBE8F9H", Request id "0HLFDGHBE8F9H:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```
dotnet version 2.1.302
OS Ubuntu 18.04 LTS

**Comment by AhmedMKamal** [comment]
Ok, it was about coping the ClientApp file please close this issue.

**Comment by abdu292** [comment]
@AhmedMKamal Hi, how did you solve this? I have the same issue after publishing the app on to the server.

**Comment by AhmedMKamal** [comment]
@DwiYI  @abdu292 check `outputPath` at `angular.json` and `spa.Options.SourcePath` at `Startup` class.

**Example:**
```
// angular.json
...
"outputPath": "dist"
```
```
// Startup.cs
...
spa.Options.SourcePath = "ClientApp"
```
my problem was that when i run the build command the `Angular` app moved to `ClientApp/dist/dist` instead of `ClientApp/dist`

**Comment by DwiYI** [comment]
i have solved the issue. I am using kestrel to serve content from asp .net core. 
my issue is write wrong path (working directory) in kestrel service.

`[Service]`
`WorkingDirectory=/var/www/helloapp`
`ExecStart=/usr/bin/dotnet /var/www/helloapp/helloapp.dll`

**Comment by abdu292** [comment]
Thanks a lot @AhmedMKamal  & @DwiYI

**Comment by ColinM9991** [comment]
@DwiYI

I am also using systemd to host my ASP.NET Core + Angular app on Linux and have this issue.

Can you please confirm whether your index.html lives in the specified working directory? I'm quite unsure as to what's causing this issue as everything is configured as it should and the application does work just fine in production, but my logs are riddled with this error.

**Comment by DwiYI** [comment]
@ColinM9991 

my _index.html_ is inside dist folder. and make sure `spa.Options.SourcePath = "ClientApp"`

this is my folder structure (inside `/var/www/helloapp`)
```
-ClientApp/dist/index.html
-ClientApp/dist/main.js
-wwwroot/favicon.ico
-helloapp.dll
-appsettings.json
-etc
```

**Comment by ColinM9991** [comment]
@DwiYI

Thank you for confirming your structure.

The source path in the Startup.cs and angular.json files is correct for me, the application builds and runs successfully but my logs are plagued with this error regardless, I'm wondering if it's a Linux issue as I host on Ubuntu 18.04 with nginx as a reverse proxy as described here https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#configure-a-reverse-proxy-server

**Comment by HalidCisse** [comment]
Solved it by adding :
`new WebHostBuilder()
                .UseContentRoot(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location))`

**Comment by kakins** [comment]
I simply modified my launcSettings.json ASPNETCORE_ENVIRONMENT to be a custom environment name, and this caused the app to blow up with this error.  No idea how to resolve it.

**Comment by kakins** [comment]
My issue was with setting a custom ASPNETCORE_ENVIRONMENT variable in launchSettings.json.  This was on a new project, and I had forgotten to modify the following line in the Startup.cs `Configure()` method.

From
```
if (env.IsDevelopment())
```

To
```
if (Environment.IsEnvironment("MyCustomEnv"))
```

Because this if block wasn't being executed, the `spa.UseAngularCliServer` method was not being called while debugging.

**Comment by eltiare** [comment]
I'm getting this error randomly. It works most of the time.

**Comment by liberalmeida** [comment]
> Solved it by adding :
> `new WebHostBuilder() .UseContentRoot(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location))`

Where did you add this?

**Comment by liberalmeida** [comment]
> WorkingDirectory

@DwiYI Where did you add this?

**Comment by eltiare** [comment]
@liberalmeida `WebHostBuilder` is usually found in `Program.cs` - the entrypoint.

**Comment by SamuelQZQ** [comment]
I have already deployed our web service. Most of the time it works fine, but randomly I will get this error.

**Comment by abdu292** [comment]
Moved to [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor). I can't express the joy & how productive I really am. I'm unsure if I'll ever look back to Angular/React/Vue.

(Just thought to share this with my old friends, probably time for me to unsubscribe from this thread)

Thanks!

**Comment by james-poulose** [comment]
Angular 11, .NET 5.0, trying to host on the dev machine IIS. All the settings are correct according to the suggestions above, but I am still getting the error :-(

**Comment by james-poulose** [comment]
In my case this was because of a trailing slash in the Angular Api root.

Instead of 

    http://localhost:81

i had

    http://localhost:81/

Remove the slash and you will be fine.
I have answered this [here](https://stackoverflow.com/a/65623100/249097)

**Comment by davidboothe** [comment]
> I'm getting this error randomly. It works most of the time.

did you ever fix this? or find the root cause of it happening randomly for you?

**Comment by code1line** [comment]
> > I'm getting this error randomly. It works most of the time.
> 
> @eltiare did you ever fix this? or find the root cause of it happening randomly for you?

I'm getting this error randomly too...

**Comment by chrisfcarroll** [comment]
I've had this as a transitory error, not with Angular but with React, and my first guess is that it happens if I try to load the site during the seconds it takes for client app to build. In my case, that can take 10-20seconds.

**Comment by roboter** [comment]
Before that error I have a lot of requests that try to find random vulnerabilities in different type of sites
So my guess that this error is triggered by some malformed URL.
`
02 Jan 2023 11:53:42.318419 <158>1 2023-01-02T09:53:41.801874+00:00 heroku router - - at=info method=GET path="/passport/index.php?action=manage&mtype=userset&backurl=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E"
02 Jan 2023 11:53:42.342371 <158>1 2023-01-02T09:53:41.80013+00:00 heroku router - - at=info method=GET path="/wp-admin/admin-ajax.php?action=memberhero_send_form&_memberhero_hook=phpinfo"
02 Jan 2023 11:53:42.342533 <158>1 2023-01-02T09:53:41.800053+00:00 heroku router - - at=info method=GET path="/plugins/editors/jckeditor/plugins/jtreelink/dialogs/links.php?extension=menu&view=menu&parent=\"%20UNION%20SELECT%20NULL,NULL,CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION(),0x6e75636c65692d74656d706c617465),NULL,NULL,NULL,NULL,NULL--%20aa" 
02 Jan 2023 11:53:42.369309 <158>1 2023-01-02T09:53:41.803044+00:00 heroku router - - at=info method=GET path="/goforms/menu" 
02 Jan 2023 11:53:43.176311 <158>1 2023-01-02T09:53:42.796472+00:00 heroku router - - at=info method=GET path="/users/sign_in" 
02 Jan 2023 11:53:43.228326 <158>1 2023-01-02T09:53:42.797236+00:00 heroku router - - at=info method=GET path="/lab.html?vpath=//interact.sh" 
02 Jan 2023 11:53:43.276375 <158>1 2023-01-02T09:53:42.814777+00:00 heroku router - - at=info method=GET path="/webui/file_guest?path=/var/www/documentation/../../../../../etc/passwd&flags=1152" 
02 Jan 2023 11:53:44.056309 <158>1 2023-01-02T09:53:43.874393+00:00 heroku router - - at=info method=POST path="/checkValid" 
02 Jan 2023 11:53:44.407306 <158>1 2023-01-02T09:53:43.94351+00:00 heroku router - - at=info method=POST path="/login.htm" 
02 Jan 2023 11:53:44.407333 <158>1 2023-01-02T09:53:43.965605+00:00 heroku router - - at=info method=POST path="/ws/v1/cluster/apps/new-application" 
02 Jan 2023 11:53:44.407330 <158>1 2023-01-02T09:53:43.966111+00:00 heroku router - - at=info method=POST path="/index.php?m=member&f=login_save" 
02 Jan 2023 11:53:44.451321 <158>1 2023-01-02T09:53:44.098226+00:00 heroku router - - at=info method=POST path="/filemanager/upload.php"
02 Jan 2023 11:53:44.472325 <158>1 2023-01-02T09:53:43.960103+00:00 heroku router - - at=info method=POST path="/cgi-bin/libagent.cgi?type=J" 
02 Jan 2023 11:53:44.481309 <158>1 2023-01-02T09:53:44.05796+00:00 heroku router - - at=info method=POST path="/scrm/crm/admin" 
02 Jan 2023 11:53:44.515308 <158>1 2023-01-02T09:53:44.034938+00:00 heroku router - - at=info method=POST path="/RPC2_Login" 
02 Jan 2023 11:53:45.518400 <158>1 2023-01-02T09:53:44.945391+00:00 heroku router - - at=info method=GET path="/api/console/api_server?sense_version=%40%40SENSE_VERSION&apis=../../../../../../../../../../../etc/passwd" `
