### ISSUE TITLE
"Could not copy" error when the project reference is shared

### ISSUE THREAD

**Issue by IgorXq** [dotnet/core#1806]
# Issue Title

"Could not copy" error when the project reference is shared between several projects

# General

Suppose that two projects of  the solution share one reference.

 <ProjectReference Include="..\........src\SomeSharedLibrary.csproj"  />

The first project  (the service) is running in console window with **dotnet run** , the other app is the client for this service and runs (_usually, but indeed does not matter_) from Visual Studio.

Whenever you stop the client project and run it again it will fail to compile with annoying error

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB3021	Unable to copy file "D:\projects\....\bin\Debug\netcoreapp1.1\....dll" to "bin\Debug\netcoreapp2.0\X.....". The process cannot access the file 'bin\Debug\netcoreapp2.0\...dll' because it is being used by another process.	.....	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4277	

It happens regardless if you have made any changes or not, moreover, even though you stop and restart the service in console windows - it does not help. The error is still occur. 

Formerly I was able at least  to restart the service to get rid of error, without closing the window, Now it became impossible, I have to close window, then reopen it and re-run **dotnet run**. 

Also, if I just  make changes to the service and therefore want to restart it (client is stopped but Visual Studio is open) , it also fails to compile because of locked files. Need to close the window and open again.

I even do not dream about the normal scenario - e.g when I make changes to the  client project (_not touching Shared library - it gets changed very seldom_),  and I am able to run it again without stopping the service.

Tried **PrivateAssets="All"** didn't help, shared files are still get locked.

Therefore I have to terminate the service, then close the window, then reopen the window and run it again, run the client, reattach to service process (if I need to debug) - just to run the client app again, even without any changes in it. Nightmare !

**Comment by joshfree** [comment]
@dsplaisted @nguerrera

**Comment by dsplaisted** [comment]
This issue was moved to dotnet/cli#9742
