### ISSUE TITLE
2.2.100-preview1-009009 not found in releases.json

### ISSUE THREAD

**Issue by ds-ms** [dotnet/core#1807]
@leecow Please check out this issue: https://github.com/Microsoft/vsts-tasks/issues/7792 
This issue is related to DotnetCoreInstaller VSTS task, where we use the releases.json for downloading.

**Comment by leecow** [comment]
At this time, the releases.json file only tracks releases meant for broader public consumption (eg public previews, release candidates and ga releases). We're looking into ways to better enable consumption of daily builds but it likely won't be in this file or its replacements.
