### ISSUE TITLE
Any plan to add Microsoft.SqlServer.Replication?

### ISSUE THREAD

**Issue by andrewb273** [dotnet/core#1808]
# Issue Title

Add `Microsoft.SqlServer.Replication` (Microsoft.SqlServer.Rmo.dll)

# General

We host SQL server in an enterprise environment where database servers are taking offline randomly. Currently we have a master DB server which is replicated to a number of slave servers. If the master DB server goes down, then we manually promote one of the slaves to master, along with updating the configuration of applications that depend on them.

Given the pain in this and the added downtime, we're looking to build a tool that does this automatically, and it seems as though the .NET Framework library `Microsoft.SqlServer.Replication` should help.

However we're moving everything to .Net Core, so using this library is a bit of a step backwards. Is adding this library to .Net Core on the roadmap?

Note: I see that there is https://www.nuget.org/packages/Unofficial.Microsoft.SQLServer.RMO, but as it's not open source, has minimal usage, and hasn't been updated for a year, I'm unwilling to use it.

**Comment by joshfree** [comment]
This issue was moved to dotnet/corefx#31377
