### ISSUE TITLE
UnderstandingJwtBearerOptions RequireHttpsMetadata functionality

### ISSUE THREAD

**Issue by tker** [dotnet/core#1812]
We would  like some help understanding the functionality set by the JwtBearerOptions RequireHttpsMetadata boolean option.

[The documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions.requirehttpsmetadata?view=aspnetcore-2.1) for this option is somewhat sparse, and I have been unable to find a more complete description.

While the documentation states that this should only be set to false in a development environment, all of our services including the authentication (bearer token issuing) service operate exclusively behind a reverse proxy gateway, within which environment they are HTTP not HTTPS. 

The name of the option suggests that the token issuer needs to be an HTTPS endpoint; however, in our scenario this will not be the case.

Given the significance of proper security configuration I would like to know exactly what effect this flag has, how it works and what the implications of leaving it false in our scenario are.

We are not using OIDC or Identity, just the JWT bearer packages.

**Comment by joshfree** [comment]
@Eilon could you help route this?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Security#1825
