### ISSUE TITLE
.net core sdk 2.1.302  conflict with hosting 2.1.2

### ISSUE THREAD

**Issue by RenshuozZ** [dotnet/core#1815]
# Issue .net core sdk 2.1.302  conflict with hosting 2.1.2

i install sdk 2.1.302 in instead of 2.1.2
but when i deploy the web api project to my machine  
it is error 502.5 

  An assembly specified in the application dependencies manifest (THTOC.Code.WebApi.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

**Comment by Eilon** [comment]
@JunTaoLuo / @natemcmaster - any ideas on this? Likely an ASP.NET Core issue?

**Comment by natemcmaster** [comment]
This happens because ASP.NET Core 2.0 apps do not run on .NET Core 2.1, and the 2.1.302 SDK only installs .NET Core 2.1 **runtime**. The 2.1.2 SDK installed .NET Core 2.0 **runtime**.

@RenshuoZz you can find .NET Core 2.0 runtime installers here: https://www.microsoft.com/net/download/dotnet-core/2.0

**Comment by RenshuoZz** [comment]
@natemcmaster    i installed 2.1.302 sdk and installed 2.1 runtime it is conflict , and dotnet command can't run  , when i uninstall 2.1 runtime(x84) and retain 2.1 runtime(x64), it run normally

**Comment by JunTaoLuo** [comment]
Can you share your .csproj? I suspect you are referencing `Microsoft.AspNetCore.All` with a version of `2.0.*`. This is the only way the runtime is looking for runtime assets in the runtime store as listed in the aspnetcore-store manifests. Since you have the 2.1 runtime installed, you should update your metapackage reference so that your app runs on the 2.1 runtime (by changing the existing reference to `<PackageReference Include="Microsoft.AspNetCore.App" />` or `<PackageReference Include="Microsoft.AspNetCore.All" />` depending on which metapackage suits your needs). I'm not sure how runtime bitness affected your deployment but it should match the machine architecture.

**Comment by RenshuozZ** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>Documents\THTOC.Code.WebApi.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\" />
    <Folder Include="Documents\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\framework\THTOC\THTOC.csproj" />
    <ProjectReference Include="..\THTOC.Code.Data\THTOC.Code.Data.csproj" />
    <ProjectReference Include="..\THTOC.Code.Model\THTOC.Code.Model.csproj" />
    <ProjectReference Include="..\THTOC.Code.Repository\THTOC.Code.Repository.csproj" />
    <ProjectReference Include="..\THTOC.Code.Service\THTOC.Code.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Documents\THTOC.Code.Model.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Documents\THTOC.Code.WebApi.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
@JunTaoLuo

**Comment by RenshuozZ** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>Documents\THTOC.Code.WebApi.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\" />
    <Folder Include="Documents\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\framework\THTOC\THTOC.csproj" />
    <ProjectReference Include="..\THTOC.Code.Data\THTOC.Code.Data.csproj" />
    <ProjectReference Include="..\THTOC.Code.Model\THTOC.Code.Model.csproj" />
    <ProjectReference Include="..\THTOC.Code.Repository\THTOC.Code.Repository.csproj" />
    <ProjectReference Include="..\THTOC.Code.Service\THTOC.Code.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Documents\THTOC.Code.Model.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Documents\THTOC.Code.WebApi.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
@JunTaoLuo

**Comment by RenshuozZ** [comment]
![image](https://user-images.githubusercontent.com/11639841/43298793-1dde1d5e-918a-11e8-8b86-8fd18c21e108.png)
@JunTaoLuo

**Comment by JunTaoLuo** [comment]
That's strange, you don't have any references to `Microsoft.AspNetCore.All` with a version of 2.0.*. As far as I can tell, this project should be able to publish and run correctly assuming you have the 2.1 runtime on the target machine. The host should not try to load anything from the runtime store. Are you still seeing the same `An assembly specified in the application dependencies manifest (THTOC.Code.WebApi.deps.json) was not found:` error during deployment?

**Comment by RenshuozZ** [comment]
![image](https://user-images.githubusercontent.com/11639841/43299636-89acd20c-918d-11e8-8682-9aaa33ca5e6e.png)
@JunTaoLuo   it not only delpoyment aslo error during build  when i install runtime 2.1.2 (i hava  installed sdk 2.1.302 ) , i try to uninstall runtime(x86) and  it work  and deployment success

**Comment by natemcmaster** [comment]
> i try to uninstall runtime(x86) and it work and deployment success

It sounds like you have run into multiple problems. At this point, it's unclear to me which issue you are running into.

Are you still getting `An assembly specified in the application dependencies manifest (THTOC.Code.WebApi.deps.json) was not found` with a project that targets ASP.NET Core 2.1?

If not, I would recommend we close this one and open a new issue with details about the issues you are having in regard to x86/x64 and dotnet commands which fail.
