### ISSUE TITLE
dotnet-sdk-2.1.302 missing  https://apt-mo.trafficmanager.net/repos/dotnet-release/

### ISSUE THREAD

**Issue by jfborie** [dotnet/core#1817]
# Issue Title

Couldn't find any package by glob 'dotnet-sdk-2.1.302'

# General
https://apt-mo.trafficmanager.net/repos/dotnet-release/dists/xenial/main/binary-amd64/Packages

is missing dotnet-sdk-2.1.302 who is incharge of updating this?

**Comment by omajid** [comment]
The .NET Core apt feeds are no longer hosted on apt-mo.trafficmanager.net. They are instead hosted on packages.microsoft.com.

Please see https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.302 for steps on how to enable the repository and install the packages.

**Comment by leecow** [comment]
Omair is correct. You'll need to update you /etc/apt/sources.list.d/[dotnetrepo].list to point to `deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main`

**Comment by jfborie** [comment]
Thank you

**Comment by jfborie** [comment]
Went to fast to close it. I do once he 
RUN apt-get install -y dotnet-sdk-2.1
in Package file it says
-------------------------
Package: dotnet-sdk-2.1
Priority: standard
Section: devel
Installed-Size: 222988
Maintainer: Microsoft <dotnetcore@microsoft.com>
Architecture: amd64
Version: 2.1.302-1
Depends: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.8), dotnet-runtime-2.1 (>= 2.1.2), aspnetcore-runtime-2.1 (>= 2.1.2)
Filename: pool/main/d/dotnet-sdk-2.1/dotnet-sdk-2.1.302-x64.deb
Size: 85194272
MD5sum: 8f7b1669b87cf008cf35cf0675bb9794
SHA1: 794bbc20ceb9ba89e1dd9f78cf5ad78c11b4027c
SHA256: e5e6b919d4a37e1f4ff264e91f3ebc136f8cb0618cf07e6dae82d07fe74aabfc
SHA512: f7343d6cdcd5d726de013865426d8b542090fd0e28e2fcc9aec888802b2abe1c13ddfeda17d0481c448ec6a623ed88df880d498661915ba320a5d10d42376ae4
Description: Microsoft .NET Core SDK 2.1.302
 .NET Core is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/core). We happily accept issues and PRs.
Homepage: https://dotnet.github.io/core
-------------------------

but when i build my project i am still getting this error
/usr/share/dotnet/sdk/2.1.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. 


It looks to me it is not installing this one
 pool/main/d/dotnet-sdk-2.1/dotnet-sdk-2.1.302-x64.deb

why we have multiple package with the same name but different version.

it there a way to forace to take the package 2.1.302
