### ISSUE TITLE
Visual Studio 2015 on .NET Core: Find the references?

### ISSUE THREAD

**Issue by Thorium** [dotnet/core#182]
When I do a project on .NET Core, I should be able to find the references as it seems all the .NET Core libraries are not in by default (like reflection libraries). So how can I find all the needed NuGet references to be able to compile my code?

I'm using an F# source code.

**Comment by svick** [comment]
VS includes the "Add Package" code fix. So, if you have some code that uses a type from a package that's not referenced, activate the code fix (start using <kbd>Ctrl</kbd>+<kbd>.</kbd> or clicking the light bulb), restore packages and your code should work.

As an alternative, you could also use https://packagesearch.azurewebsites.net/.

**Comment by Thorium** [comment]
Thanks for the link, however Visual studio help works only on C# project, not helping me with the existing F# code.

**Comment by svick** [comment]
Sorry, somehow I missed that part.

**Comment by cartermp** [comment]
Hey @Thorium, the link to https://packagesearch.azurewebsites.net from @svick is currently the best way to find which .NET package contains a given API when writing F# code.

Reflection was initially changed significantly in .NET Core.  The APIs are changing back to their original surface, but for the time being you can use the [ApiPort tool](https://github.com/Microsoft/dotnet-apiport/blob/master/docs/HowTo/Introduction.md) to learn the API alternatives to .NET Framework Reflection code you may be using.

**Comment by blackdwarf** [comment]
With the responses above, I think that the issue can be closed. For any API questions/issues, please file an issue on dotnet/corefx and for command line tooling file an issue on dotnet/cli.

**Comment by Thorium** [comment]
This is not solved. Apiport tool is not working microsoft/dotnet-apiport#304 so I'm trying to use the https://packagesearch.azurewebsites.net but: It doesn't found anything. Not even [FSharp.Core package](https://www.nuget.org/packages/FSharp.Core/4.0.0.1) which clearly supports .NET Core.

**Comment by cartermp** [comment]
@Thorium note that the FSharp.Core package is a _community_ package, and not officially built by nor supported by the F# team.  The current Microsoft-supported package to use is this one: https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore/1.0.0-alpha-160805

However, F# types are not supported in the Reverse Package Search website today, which should be fixed.

**Comment by Thorium** [comment]
Is the https://packagesearch.azurewebsites.net source code open?
Or do you know if it has any kind of issue reporting site on somewhere?

**Comment by cartermp** [comment]
I do not think it's OSS, no.  Nor do I know of any place where issues can be reported.
