### ISSUE TITLE
Self-contained publish failing with error NU1605: Detected package downgrade: Microsoft.NETCore.App from 2.1.2 to 2.1.0

### ISSUE THREAD

**Issue by leandro-fernandez** [dotnet/core#1820]
# Self-contained publish failing in .net core sdk 2.1.302 with `error NU1605 : Detected package downgrade: Microsoft.NETCore.App from 2.1.2 to 2.1.0`

# Description

After I migrated from .netcoreapp2.0 to .netcoreapp2.1, I am getting a `error NU1605: Detected package downgrade: Microsoft.NETCore.App from 2.1.2 to 2.1.0` when running `dotnet publish` with the `-r` option.

snapshot
![image](https://user-images.githubusercontent.com/22692447/43290485-949f3828-9104-11e8-8f73-8f35750f3c30.png)

one of my class libs csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.1" />
    <PackageReference Include="xunit" Version="2.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rubicon.ReverseProxy\Rubicon.ReverseProxy.csproj" />
  </ItemGroup>
</Project>
```

main project csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />
    <PackageReference Include="Polly" Version="6.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.0.0" />
    <PackageReference Include="Steeltoe.Management.CloudFoundryCore" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="deploy.*.bat">
      <DependentUpon>deploy.bat</DependentUpon>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="manifest.*.yml">
      <DependentUpon>manifest.yml</DependentUpon>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="manifest.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JSONSchema="" /></VisualStudio></ProjectExtensions>

</Project>
```

**Comment by joshfree** [comment]
@weshaggard

**Comment by Petermarcu** [comment]
One of the packages you are referencing is likely pulling in a lower version of a package. @DamianEdwards have you seen this?

**Comment by weshaggard** [comment]
Based on the error screenshot it looks like a couple of your test projects are directly referencing 2.1.0 of the runtime either via a direct PackageReference or via overriding the RuntimeFrameworkVersion. Can you provide a pointer to your Rubicon.ReversProxy.Tests.Common.csproj?

**Comment by leandro-fernandez** [comment]
The weird part is that running `dotnet publish` without `-r` (i.e., to output a dll) doesn't cause any issues.
Here's the Rubicon.ReverseProxy.Tests.Common.csproj.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.2" />
    <PackageReference Include="xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rubicon.ReverseProxy\Rubicon.ReverseProxy.csproj" />
  </ItemGroup>

</Project>

```

**Comment by DamianEdwards** [comment]
Have you tried updating your reference to Microsoft.AspNetCore.TestHost to the latest version?

**Comment by leandro-fernandez** [comment]
I have. Doesn't make a difference with regards to the `NU1605 : Detected package downgrade` error.
I left it as `2.0.2` in the end because the latest version of `Microsoft.AspNetCore.TestHost` changed its behavior somehow and it broke our tests.

**Comment by dasMulli** [comment]
In your test project, try setting

```xml
<PropertyGroup>
  <TargetLatestRuntimePatch>false</TargetLatestRuntimePatch>
</PropertyGroup>
```

This is likely a side-effect of NuGet using different parameters to restore than the actual build will use - the RuntimeIdentifier will not be forward across P2P references during the build but NuGet will evaluate all projects using the global property and thus the runtime roll-forward kicks in.

Also see https://github.com/dotnet/sdk/issues/1834

**Comment by dasMulli** [comment]
And btw roll-forward doesn't kick in for test projects since they are libraries by default and the test SDK changes them to `<OutputType>Exe</OutputType>` too late for the self-contained roll-forward IIRC.

In theory, you can also work around this by setting `<OutputType>Exe</OutputType>` in the test project instead of the `TargetLatestRuntimePatch` mentioned above.

**Comment by jkruer01** [comment]
I have the same issue.  Builds locally fine, but throws same error as above for my test project on the build server.

**Comment by jkruer01** [comment]
Adding `<OutputType>Exe</OutputType>` worked for me.

**Comment by duncanawoods** [comment]
Adding just `<OutputType>Exe</OutputType>` got over the downgrade warning but publish then failed on `NETSDK1061: The project was restored using Microsoft.NETCore.App version 2.1.2, but with current settings, version 2.1.0 would be used instead`.

Adding `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>` fixes it fully.

**Comment by ramoneeza** [comment]
Change .csproj doesn't work.

Nuget problems are persistent with any .net core 2.1 project I start.

When I use "Nuget Console" with "Update-Package -reinstall", then Project name is cleared and it displays "'default' project not found" error. :-(

My visual studio has several Nuget related errors and repair/reinstall doesn't fix anything.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-sdk #81](https://github.com/dotnet/core-sdk/issues/81) via [**ZenHub**](https://www.zenhub.com/)
