### ISSUE TITLE
Create package for Raspbian OS (ARM32)

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/core#1828]
_From @ygoe on June 30, 2018 14:13_

While there is a working binary download for dotnet (.NET Core) for ARM32 that works on a Raspberry Pi B 3+ with a current Raspbian OS, there are no instructions how to install it. And there are no packages for the OS, too. So it's a bit of a mystery how to actually make .NET Core work on a Raspi.

I think there should be a package for that OS. It should be as simple as that:

    sudo apt install dotnet

Maybe a custom package source needs to be added, but definitely no manual tar file works. Mono was easier to install when it was current like 5 years ago.

Since the docker support on the Raspi with dotnet-runtime packages is very poor (multi-arch fails, need to select arm32 image specifically, can't get my app in a custom image), I need to install .NET Core on the Raspi OS itself.

_Copied from original issue: dotnet/coreclr#18732_

**Comment by RussKeldorph** [comment]
_From @ghost on June 30, 2018 16:45_

Current blocker for ARM32 in general is https://github.com/dotnet/cli/issues/8998. In my understanding it's about couple of lines of XML changes in dotnet/cli to pack the right binaries (like done for ARM64 https://github.com/dotnet/cli/pull/9011/files) and then testing cross build on x64 (which is a more involved task).
That said, CoreCLR/CoreFx/CoreSetup parts for ARM32 are done.

**Comment by RussKeldorph** [comment]
@Petermarcu Wasn't sure how big the gap is or where this request should be tracked.  Sorry if this is already covered somewhere else.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #4419](https://github.com/dotnet/core-setup/issues/4419) via [**ZenHub**](https://www.zenhub.com/)
