### ISSUE TITLE
Microsoft WCF Web Service Reference Provider Not Generating Found Services

### ISSUE THREAD

**Issue by DanJ210** [dotnet/core#1829]
Hello, I'm hoping someone can shed some light into what's going on here. I'm trying to add the NetSuite Web Service (which I hate btw) and I'm using the built in feature to add a WCF service. It seems to work correctly as you'll see in the screenshot, it does find all of the operations. This is the web service URL https://webservices.netsuite.com/wsdl/v2018_1_0/netsuite.wsdl

![ns_webservice_reference](https://user-images.githubusercontent.com/16159685/43482969-35d6b74e-94d8-11e8-932a-bf4ee1eea118.PNG)

The problem is that when I click finish, the result seems to be way different than what's found. The Reference.cs that's generated contains all of these async methods and the code snippet below seems to show that it's taking the original operations and converting them to an async Task. I'm not opposed to this but the problem is that the Task that is returned is not working. It's requiring way more parameters than what the original operation requires and I'm being denied access due to "Ambiguous Authentication" which is most likely because I'm providing login details with token based authentication where I just want token. Even if I modify the generated method I'm still not getting the correct response. The original operation works.

So is there a way to not have all of this generated/converted into async methods and just get the original operations? Below is an example of what looks like the original `get` operation being converted to an `getAsync` operation. I've never worked with web services or SOAP before. I'm just trying to use .Net Core instead of .Net 4.6.

```
[System.ServiceModel.OperationContractAttribute(Action="get", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.InsufficientPermissionFault), Action="get", Name="insufficientPermissionFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.InvalidSessionFault), Action="get", Name="invalidSessionFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.InvalidCredentialsFault), Action="get", Name="invalidCredentialsFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.ExceededConcurrentRequestLimitFault), Action="get", Name="exceededConcurrentRequestLimitFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.ExceededRequestLimitFault), Action="get", Name="exceededRequestLimitFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.ExceededUsageLimitFault), Action="get", Name="exceededUsageLimitFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.ExceededRecordCountFault), Action="get", Name="exceededRecordCountFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.ExceededRequestSizeFault), Action="get", Name="exceededRequestSizeFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceNetSuite.UnexpectedErrorFault), Action="get", Name="unexpectedErrorFault", Namespace="urn:faults_2018_1.platform.webservices.netsuite.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoapFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRef))]
        System.Threading.Tasks.Task<ServiceNetSuite.getResponse> getAsync(ServiceNetSuite.getRequest request);
```

**Comment by Lxiamail** [comment]
Issue moved to [dotnet/wcf #3078](https://github.com/dotnet/wcf/issues/3078) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DanJ210** [comment]
It looks like using a web service is generated and used different in .Net Core than it is in regular .Net and Core converts everything to async. So manipulation of the generated code has to happen which is ok.

**Comment by DanJ210** [comment]
Just to update, the Web Service Reference actually does work and it does generate .Net Core compatible code. .Net Core uses the .Net standard anyway so I'm guessing it shouldn't matter too much, it's all just C# code. The Web Service Reference does seem to wrap everything into async calls which I don't know if that can be turned off or not and I don't know if that's a .Net Core only thing. However, the generated code does work and I'm using it with a .Net Core project. The ambiguous authentication comes from the generated code using ALL parameters possible from the Web Service when you may only want a couple, so you'll have to modify the generated code some.

First time I've worked with Web Service, SOAP, and I hope it's the last lol. But the Web Service Reference tool seems to do a good job for consuming the intense and very large Web Service that it did.
