### ISSUE TITLE
project.json has C# in the icon file even on F# projects

### ISSUE THREAD

**Issue by Thorium** [dotnet/core#183]
project.json has C# in the icon (also in Visual Studio) file even on F# projects.

icons should be language-agnostic.

**Comment by blackdwarf** [comment]
@Thorium can you please move this issue to https://github.com/aspnet/tooling/issues? It seems like a much better place for this issue. I will close this one. Thanks!

**Comment by ubbeK** [comment]
Issue fixed in https://github.com/aspnet/Tooling/issues/699 if anyone is interested.
