### ISSUE TITLE
Migrate from ASP.NET Core 2.0 to 2.1- Request to Web API failed(503-Service Unavailable )

### ISSUE THREAD

**Issue by 280919911** [dotnet/core#1830]
I have changed target framework 2.1 and also replaced the packages Microsoft.AspNetCore.All to Microsoft.AspNetCore.App.

On Web API project- I have set environment variable and enabled SSL from the project property
I am able to run the Web project but while calling Web API from web project 
I'm getting following error
Response status code does not indicate success: 503 (Service Unavailable).

**Comment by Eilon** [comment]
This issue was moved to aspnet/Home#3381
