### ISSUE TITLE
Cannot find reference assembly

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/core#1838]
after upgrading to 2.1 and publishing to server website cannot load any of .NET assembly

Project is mixed .net and core
<TargetFramework>net461</TargetFramework>    

InvalidOperationException: Cannot find reference assembly '.NETFramework/v4.6.1/Facades/System.Runtime.InteropServices.WindowsRuntime.dll' file for package System.Runtime.InteropServices.WindowsRuntime

And so on
if I copy missing dll to project bin folder it goes for an other dll and so on

**Comment by oshmytov** [comment]
Consider the following advice, it helped me with my .NET Standard assembly being used in mixed .net and core environment: https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx

**Comment by Petermarcu** [comment]
@dvdobrovolskiy did that help?

**Comment by Petermarcu** [comment]
Hopefully that helped. Closing now.
