### ISSUE TITLE
Duplicate SDK Version Installs

### ISSUE THREAD

**Issue by DanJ210** [dotnet/core#1839]
Hello, I'm trying to clear up space on my Surface and noticed that I have quite a few .Net Core SDK's installed. One version has a duplicate entry. I'm guessing that I need all of the versions if they are installed but if there is a duplicate, is that a problem? Are they different or can I delete one?

I also have a .Net Core 1.* SDK and since I don't have Visual Studio 2015 installed anymore, can that be removed as well since nothing uses it? I have nothing in version 1. The only reference to Visual Studio 2015 is this (isolated) install which I don't know what that is or where it came from or if I can even install that. It's relatively small so I don't need to remove it but if it's excess and never needed, then why keep it?

Screenshot shows the 2.* duplicate I'm referring to plus all the others and the 1.* I mentioned. Sorry if this is a silly question.

![dotnet_core_sdk](https://user-images.githubusercontent.com/16159685/43671953-31168206-9772-11e8-9702-a3f0506f7e58.png)

![visual_studio_2015_install](https://user-images.githubusercontent.com/16159685/43671956-3ba21384-9772-11e8-8b48-0b18360c2d15.png)

**Comment by rakeshsinghranchi** [comment]
@DanJ210 , can you please click on the duplicate product names and share the version number it shows ? 
For e.g : 
![image](https://user-images.githubusercontent.com/6225949/44282667-a4a12200-a210-11e8-8e75-26541b9bec16.png)

It is possible that you have different version of the same product being installed. 

cc @wli3

**Comment by DanJ210** [comment]
Sure I will get these once I return  home. Thanks.

**Comment by DanJ210** [comment]
And I'm guessing that's what it is then. Different sub versions. Idk we'll see.

**Comment by DanJ210** [comment]
Ok so I just checked @rakeshsinghranchi and of the two versions above, one is 2.1.100 and the other is 2.1.100.7326.

So I don't know what I need and what I can remove. I'm guessing that I can remove the 1.* versions because I don't use those versions at all? And I can remove all versions of 2.1 except for the latest?

In five years I don't want a building up 50 versions because I install the updated versions but leave the old ones behind where at half a GB a piece, that would take up 25 GB on my 256GB Surface Pro 4. In 5 years I'll probably have a new Surface Pro with a 1 TB drive but for now this is what I've got. So I'm just trying to get a grasp on deleting what I don't need.

**Comment by wli3** [comment]
We have an issue existing issue https://github.com/dotnet/cli/issues/6896

**Comment by wli3** [comment]
And I created the one above for the specific issue

**Comment by Petermarcu** [comment]
Closing because we are tracking this in dotnet/cli#6896

**Comment by DanJ210** [comment]
Ok, thank you @wli3 and @Petermarcu
