### ISSUE TITLE
ARM64 architecture in Debian 9 repository

### ISSUE THREAD

**Issue by Levi--G** [dotnet/core#1840]
# ARM64 architecture in Debian 9 repository

I just tried installing ARM64 runtime with the package manager and apparently its not in there.

# Details

This is more of a question/documentation clarification than an actual issue, but it was annoying enough for me to make this.
So after going to [https://www.microsoft.com/net/download/dotnet-core/2.1](https://www.microsoft.com/net/download/dotnet-core/2.1) I got the impression I could also install arm64 runtime through the package manager since there are no limitations listed.

![](https://gyazo.com/2270b0e96a39364619bdc1e222a3cace.png)

But unfortunately after following the guide at [https://www.microsoft.com/net/download/linux-package-manager/debian9/runtime-2.1.2](https://www.microsoft.com/net/download/linux-package-manager/debian9/runtime-2.1.2) (still no limitations listed to amd64 only) I found out the repo doesn't contain an arm package, so I had to manually download the tar etc... Now that isn't that bad but I would rather have known that sooner, is it possible to mention this in the listing of the versions? Is there a package planned for arm? I would expect it to not be that much effort (but then again I am only a noob what do I know 🤣)

Friendly regards,

**Comment by leecow** [comment]
Excellent points. Thanks @Levi--G . There are currently not plans to add package manger support for ARM64 but that could certainly change. Will work on some dl instruction content to make it clear that it's all referring to AMD64.

cc @vivmishra

**Comment by vielmetti** [comment]
Thanks @Levi--G @leecow . I too would like to see arm64 support in Debian packaging for the runtime.

**Comment by Petermarcu** [comment]
@dleeapho as FYI
