### ISSUE TITLE
.net core  .net framework HttpWebRequest

### ISSUE THREAD

**Issue by a641545621** [dotnet/core#1846]
class Program
    {
        static void Main(string[] args)
        {
            string msg = HttpConnectToServer("https://www.okex.com/api/v1/exchange_rate.do");
            Console.WriteLine("Core:"+msg);
            Console.ReadKey();
        }
        private static string HttpConnectToServer(string url)
        {
            //创建请求
            HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(url);
            request.Method = "GET";

            //读取返回消息
            string res = string.Empty;
            try
            {
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                StreamReader reader = new StreamReader(response.GetResponseStream(), Encoding.UTF8);
                res = reader.ReadToEnd();
                reader.Close();
            }
            catch (Exception ex)
            {
                return ex.ToString();
                //连接服务器失败
            }
            return res;
        }
    }

![1](https://user-images.githubusercontent.com/33652128/43945824-fb1773d8-9cb5-11e8-98dd-81f436abce45.jpg)
![2](https://user-images.githubusercontent.com/33652128/43945826-fba00496-9cb5-11e8-9243-ffcc211411fb.jpg)

The same code is a .net core One is a different .net framework results Why?

**Comment by jonechenug** [comment]
It seem is the https question. You may need set :
```
webRequest.AllowAutoRedirect = false;
```
Such like [corefx#23422](https://github.com/dotnet/corefx/issues/23422)

**Comment by a641545621** [comment]
.net core 2.1     Request failed
.net core 2.0     Request successfully

**Comment by MarcoRossignoli** [comment]
i think is better move this issue to https://github.com/dotnet/corefx repo

**Comment by karelz** [comment]
It was moved: https://github.com/dotnet/corefx/issues/31772
