### ISSUE TITLE
ICMP Destination Unreachable identified as Timeout

### ISSUE THREAD

**Issue by gserfont** [dotnet/core#1848]
# Issue Title

ICMP Destination Unreachable identified as Timeout

# General
Using .Net Core 2.1.301 on OSX 10.13.6

SendPingAsync seems to incorrectly report the reason for Ping failure.

   var reply = await ping.SendPingAsync(Theip, timeout);
            if (reply.Status == System.Net.NetworkInformation.IPStatus.Success)
            {
                Console.WriteLine("Success:" + Theip);
            }
            if (reply.Status == System.Net.NetworkInformation.IPStatus.DestinationHostUnreachable)
            {
                Console.WriteLine("Destination host unreachable:" + Theip);
            }
            if (reply.Status == System.Net.NetworkInformation.IPStatus.DestinationUnreachable)
            {
                Console.WriteLine("Destination unreachable:" + Theip);
            }
            if (reply.Status == System.Net.NetworkInformation.IPStatus.TimedOut) //Everything hits here .. 
            {
                Console.WriteLine("Destination timedout:" + Theip);
            }

![screen shot 2018-08-10 at 15 31 41](https://user-images.githubusercontent.com/20953201/43960560-ade899a0-9cb2-11e8-927b-5f71b6c058fc.png)

<img width="1001" alt="screen shot 2018-08-10 at 15 20 34" src="https://user-images.githubusercontent.com/20953201/43960083-2cb1c646-9cb1-11e8-8638-0426bdf27b2e.png">

<img width="683" alt="screen shot 2018-08-10 at 15 27 59" src="https://user-images.githubusercontent.com/20953201/43960356-0b6e9cd8-9cb2-11e8-9251-b11352f7bdcf.png">

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32238](https://github.com/dotnet/corefx/issues/32238) via [**ZenHub**](https://www.zenhub.com/)
