### ISSUE TITLE
dotnet crashing with segfault in libcoreclr.so every 2-4 hour in docker on workload

### ISSUE THREAD

**Issue by legigor** [dotnet/core#1849]
The application processes lots of messages from Azure Storage Queues and putting them into another queue. Deployed as Docker service. Every 2-4 hours the container stops with status `Exited (139) 3 hours ago`. When doing `dmesg | grep dotnet` I see there lots of messages like this

    [595338.233964] dotnet[22020]: segfault at 7f00de3077d8 ip 00007f01bf4fe555 sp 00007f00f77fbde8 error 6 in libcoreclr.so[7f01bf4fe000+1000]

I've redeployed the container with  source files, core dumps enabled and grabbed one. Then I've committed the crashed container as an image with dump within, pulled it to my machine, jumped into the container, installed `lldb` and discovered the following threads info

    (lldb) sos Threads
    ThreadCount:      15
    UnstartedThread:  0
    BackgroundThread: 14
    PendingThread:    0
    DeadThread:       0
    Hosted Runtime:   no
                                                                                                            Lock
           ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
      11    1    7 00000000008AD1B0  2020020 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn
      13    2    f 000000000079B410    21220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Finalizer)
      14    3   10 00000000009E8870    21220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn
      21    4   11 00000000009EE730  2021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn
      22    5   12 00007F01140009F0  1020220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
      20    6   13 0000000000A0D9A0    21220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn
       8   19  5c4 00007F010E3074C0  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
      10   15  5f1 00007F00F02086C0  1021220 Cooperative 0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
       9   11  5ff 00007F00FC936390  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
      17   12  678 00007F00F980AA30  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
       1   24  67d 00007F0100A92770  1021220 Cooperative 0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
      18   28  68d 00007F00FE004950  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
      16   22  68e 00007F01401E06F0  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
       4   32  68f 00007F01402B4F90  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
      15   26  690 00007F00FC16F3F0  1021220 Preemptive  0000000000000000:0000000000000000 00000000008B2F10 0     Ukn (Threadpool Worker)
    (lldb) thread list
    Process 7 stopped
    * thread #1: tid = 1661, 0x00007f01bf4fe555 libcoreclr.so`JIT_ByRefWriteBarrier + 3, name = 'dotnet', stop reason = signal SIGSEGV
      thread #2: tid = 13, 0x00007f01c0c5c83d libpthread.so.0`__GI_open64 + 45, stop reason = signal SIGSEGV
      thread #3: tid = 987, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV
      thread #4: tid = 1679, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #5: tid = 9, 0x00007f01c00f4229 libc.so.6`syscall + 25, stop reason = signal SIGSEGV
      thread #6: tid = 12, 0x00007f01c00ef67d libc.so.6`__poll + 45, stop reason = signal SIGSEGV
      thread #7: tid = 8, 0x00007f01c00f4229 libc.so.6`syscall + 25, stop reason = signal SIGSEGV
      thread #8: tid = 1476, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV
      thread #9: tid = 1535, 0x00007f01c00e1c77 libc.so.6`__sched_yield + 7, stop reason = signal SIGSEGV
      thread #10: tid = 1521, 0x00007f01c0c5bffa libpthread.so.0`__lll_unlock_wake + 26, stop reason = signal SIGSEGV
      thread #11: tid = 7, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #12: tid = 14, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #13: tid = 15, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV
      thread #14: tid = 16, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV
      thread #15: tid = 1680, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #16: tid = 1678, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV
      thread #17: tid = 1656, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #18: tid = 1677, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #19: tid = 23, 0x00007f01c0c5c20d libpthread.so.0`__libc_read + 45, stop reason = signal SIGSEGV
      thread #20: tid = 19, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV
      thread #21: tid = 17, 0x00007f01c0c5915f libpthread.so.0`__pthread_cond_wait + 191, stop reason = signal SIGSEGV
      thread #22: tid = 18, 0x00007f01c0c59508 libpthread.so.0`__pthread_cond_timedwait + 296, stop reason = signal SIGSEGV

The environment:

 - `Linux version 4.15.0-1018-azure (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #18~16.04.1-Ubuntu SMP Thu Jul 19 13:13:57 UTC 2018
i`
 - `Docker version 18.03.1-ce, build 9ee9f40`
 - `microsoft/dotnet:2.1.2-runtime@sha256:4a127234d2b2eb6a2274c8d43078870d03f33845c8a2d645e2cf52f10c1b487b`
 - `microsoft/dotnet:2.1.302-sdk@sha256:9e243db15f910e00f0a699011b1a438c648fb03710d1a6d385b6cf254b5fbacc`

**Comment by legigor** [comment]
I wish I would just share the image with embedded dump but I can't :)
So, I'm ready to do anything with it to help to find the bugger

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #19796](https://github.com/dotnet/coreclr/issues/19796) via [**ZenHub**](https://www.zenhub.com/)
