### ISSUE TITLE
Console App for DotNet Core 2.1.2 fails to compile

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#1850]
Uninstalled all DotNet Frameworks and removed C:\Program Files\dotnet\shared
========================
Installed 2.1.302 SDK only
========================
Info shows:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
========================
Visual Studio is at 15.7.6
========================
Create Empty project.
Add New Project Console App(.NET Core)
csproj shows <TargetFramework>netcoreapp2.1</TargetFramework>
Microsoft.NETCore.App blocked above Version 2.1.0
========================
Change csproj to <TargetFramework>netcoreapp2.1.2</TargetFramework>
========================
Error list shows
Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 2.1.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.2.	ConsoleApp1	C:\Program Files\dotnet\sdk\2.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	
========================
Same for <TargetFramework>netcoreapp2.1.1</TargetFramework>
========================
In all cases Microsoft.NETCore.App blocked above version 2.1.0
========================
Is this a problem with release 2.1.302?

**Comment by dasMulli** [comment]
If you want to build for a specific patch release of .net core, you can use

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.1</TargetFramework>
  <RuntimeFrameworkVersion>2.1.2</RuntimeFrameworkVersion>
</PropertyGroup>
```

or alternatively set `TargetLatestRuntimePatch` to `true` instead of setting `RuntimeFrameworkVersion` to target the latest patch release that the current SDK knows about.

However, if you develop a framework-dependent application, there should only be a few cases where you actually need to do either of these as your application will run on the latest patch release available.
