### ISSUE TITLE
dotnet application crash with segfault in libc.so

### ISSUE THREAD

**Issue by aididhaiqal** [dotnet/core#1851]
I have few dotnet application that works fine on Windows. But when I start using it on Linux ubuntu 18.04 the application crashes after a while

Aug 10 20:29:49 ns345778 kernel: [64810.293987] dotnet[7601]: segfault at 0 ip 00007fcdeab6d5a1 sp 00007fcd02fface8 error 4 in libc-2.27.so[7fcdea9df000+1e7000]
Aug 11 10:37:13 ns345778 kernel: [115655.290526] dotnet[3302]: segfault at 0 ip 00007f93381a75a1 sp 00007f9246ffad38 error 4 in libc-2.27.so[7f9338019000+1e7000]
Aug 11 11:39:20 ns345778 kernel: [119382.541704] dotnet[6543]: segfault at 0 ip 00007f27f36315a1 sp 00007f27027f9d18 error 4 in libc-2.27.so[7f27f34a3000+1e7000]
Aug 11 11:39:23 ns345778 kernel: [119384.972187] dotnet[10224]: segfault at 0 ip 00007f8845a765a1 sp 00007f876affacc8 error 4 in libc-2.27.so[7f88458e8000+1e7000]
Aug 11 11:39:43 ns345778 kernel: [119405.432725] dotnet[10223]: segfault at 0 ip 00007fcdc38b35a1 sp 00007fccf97f7cc8 error 4 in libc-2.27.so[7fcdc3725000+1e7000]
Aug 11 11:39:55 ns345778 kernel: [119416.872661] dotnet[8649]: segfault at 0 ip 00007f7fb21175a1 sp 00007f7fa4c50cc8 error 4 in libc-2.27.so[7f7fb1f89000+1e7000]

**Comment by svick** [comment]
Can you provide a short, self-contained code that reproduces the issue?

**Comment by aididhaiqal** [comment]
Basically our project use .net socket (async) and NetMQ as dealer socket

**Comment by leecow** [comment]
@janvorli for possible troubleshooting suggestions.

**Comment by Petermarcu** [comment]
I think we're going to need more information or the ability to repro the problem in order to help.

**Comment by Petermarcu** [comment]
I'm going to close this now. Please provide more information and we can reopen and try to diagnose.
