### ISSUE TITLE
Hosting Bundle Doesnt contain the ASP.NetCore installer.

### ISSUE THREAD

**Issue by ranjicgnr** [dotnet/core#1853]
Hosting Bundle Doesnt contain the ASP.NetCore installer.

Installing the hosting bundle never installs the ASP.net core framework. It only installs .net core section. For a website working on IIS requires ASP.net core installation separately.

 Reference : AspDotNetCore 2.1, Runtime 2.1.2

**Comment by leecow** [comment]
@ranjicgnr are you referring to [dotnet-hosting-2.1.2-win.exe](https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/dotnet-hosting-2.1.2-win.exe)?

@joeloff

**Comment by joeloff** [comment]
@ranjicgnr Do you have logs? There was an issue in a previous 2.1 release where the hosting bundle would fail to install the ASP.NET shared framework if you had another 2.x version on the machine, but that was fixed for 2.1.2 AFAIK.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
