### ISSUE TITLE
System.AccessViolationException with Span

### ISSUE THREAD

**Issue by RustyCZ** [dotnet/core#1854]
Following code crashes with System.AccessViolationException when compiled in Release mode with "Optimize code". I tried that on Windows 64bit with .NET Core 2.1.302. Older version of .NET Core and Debug does not cause this exception.

Note that this code alone does not make any sense. It was isolated from larger code base.

```
using System;

namespace AccessViolationExceptionTest
{
    class Program
    {
        static void Main()
        {
		MyReader r = new MyReader();
		r.ReadBytesInner(0);
	        Console.WriteLine("Everything OK");
        }
    }

	public struct MyStruct
	{
		public Span<byte> Span1
		{
			get { return Span<byte>.Empty; }
		}
	}

	public struct MyReader
	{
		public void ReadBytesInner(int batch)
		{
			MyStruct value = new MyStruct();
			for (int i = 0; i < batch; i++)
			{
				value.Span1[i] = 0;
			}
		}
	}
}
```

**Comment by MarcoRossignoli** [comment]
i think is better move to https://github.com/dotnet/corefx repo Span<T> lives there

**Comment by RustyCZ** [comment]
I am not sure, it seems to be more like an issue with JIT compilation. That for cycle does not even execute, because that method is called with 0.

**Comment by MarcoRossignoli** [comment]
Ok jitter repo is https://github.com/dotnet/coreclr

**Comment by RustyCZ** [comment]
Closing, moved to [](url)https://github.com/dotnet/coreclr/issues/19454
