### ISSUE TITLE
Process.Start() doesn't work in netcoreapp2.1 but good in 2.0

### ISSUE THREAD

**Issue by LincolnYang1** [dotnet/core#1857]
# Process.Start() doesn't work in netcoreapp2.1 but good in 2.0
i have below simple code to demo the issue, it works well in netcoreapp2.0 but not in netcoreapp2.1
system is aws cloud, 
Linux version 4.9.81-35.56.amzn1.x86_64 (mockbuild@gobi-build-64010) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC) ) #1 SMP Fri Feb 16 00:18:48 UTC 2018

```
        static void Main(string[] args)
        {
            var fileName = args[0];
            Console.WriteLine($"{fileName} : exists: {File.Exists(fileName)}");
            
            var processStartInfo = new ProcessStartInfo(fileName)
            {
                Arguments = "--info",
                UseShellExecute = true
            };
            var process = Process.Start(processStartInfo) ?? throw new Exception("failed to start process");
            process.WaitForExit();
        }
```
run-time parameter is, /opt/dotnet/dotnet is the dotnet executable path
dotnet testapp.dll /opt/dotnet/dotnet

project file is 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>rhel.7.4-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```

# Build and Publish

if change project to 2.0, build and publish with dotnet core  2.0, it works fine.

dotnet build --runtime rhel.7.4-x64
dotnet publish --runtime rhel.7.4-x64 -c Release --framework netcoreapp2.0

but if change to 2.1 
dotnet build --runtime rhel.7.4-x64
dotnet publish --runtime rhel.7.4-x64 -c Release --framework netcoreapp2.1

it throw error, there is Win32Exception throw out.

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at testapp.Program.Main(String[] args) in source\repos\testapp\testapp\Program.cs:line 14

**Comment by omajid** [comment]
For your case, you probably want to set `UseShellExecute` to `false` to run `dotnet --info`, or pretty much any other program. Unless you actually care about `/bin/bash` being used to invoke it? I can't see how that would be useful in your example.

**Comment by LincolnYang1** [comment]
thanks for reply, 
sample code just to demo inconsistency of `UseShellExecute` between 2.0 and 2.1, the actual code is more complicate and need `UseShellExecute` 2.0 feature, 
after migrate to 2.1 it suddenly doesn't work, since` "xdg-open", "gnome-open", "kfmclient"` are not  really shell, like `/bin/sh` and `/bin/bash` , does it make sense to obey its original definition?

**Comment by omajid** [comment]
@LincolnYang1 I suggest bringing it up here: https://github.com/dotnet/corefx/issues/24704. That's an ongoing discussion about this exact same issue.

In the meantime, can you invoke `/bin/bash` explicitly?

**Comment by Petermarcu** [comment]
Yes, lets move this discussion to dotnet/corefx#24704. I'll close this one here.
