### ISSUE TITLE
.NET Core August Update - 2.1.400 SDK

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#1861]
# .NET Core August Update - 2.1.400 SDK

[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.400-SDK/2.1.400-sdk.md)
[Download 2.1.400](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.400-SDK/2.1.400-sdk-download.md)

Please report any issues you find with 2.1.400, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by glat** [comment]
I've an issue about transformation of web.config.

Trasformation of:

processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt"

occurs by adding a new row in another <location> zone. See attached files 
[web.config.before.txt](https://github.com/dotnet/core/files/2293188/web.config.before.txt)
[web.config.after.txt](https://github.com/dotnet/core/files/2293189/web.config.after.txt)

Previous SDK (302) worked correctly. I just upgraded to VS 15.8.0

Kind regards

**Comment by vivmishra** [comment]
@livarcocc   @natemcmaster

**Comment by natemcmaster** [comment]
@vijayrkn PTAL. 

For reference, the diff is:
```diff
--- web.config.before.txt	2018-08-17 13:41:29.000000000 -0700
+++ web.config.after.txt	2018-08-17 13:41:29.000000000 -0700
@@ -38,7 +38,9 @@
     <system.webServer>
       <handlers>
         <remove name="aspNetCore" />
+        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
       </handlers>
+      <aspNetCore processPath="dotnet" arguments=".\App.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
     </system.webServer>
   </location>
   <location path="wwwroot/css/bundles">
@@ -97,4 +99,5 @@
       </handlers>
     </system.webServer>
   </location>
-</configuration>
\ No newline at end of file
+</configuration>
+<!--ProjectGuid: 76566af5-8a6c-4750-be96-0969bc67b266-->
\ No newline at end of file

```

**Comment by natemcmaster** [comment]
@glat @vijayrkn please use https://github.com/aspnet/Home/issues/3437 to discuss further.

**Comment by leecow** [comment]
.NET Core SDK 2.1.401 released. Closing this issue.

cc @vivmishra
