### ISSUE TITLE
When GenerateAssemblyInfo Is False, Project File (.csproj) and Project Properties Are No Longer in Sync

### ISSUE THREAD

**Issue by elmojo** [dotnet/core#1863]
If you add

`<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`

to a .NET Core project file (.csproj), entering information in the project's properties package tab no longer updates the project file and any package information already within the project file no longer is displayed within the project's properties package tab.

# Steps to Reproduce

.NET Core Version 2.0

Save the following markup as a Visual Studio project file (.csproj).

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp2.0</TargetFramework>
        <Version>1.1.0.0</Version>
        <Authors>Author Test</Authors>
        <Company>Test Company</Company>
        <Product>AssemblyTest DLL</Product>
        <Description>A test of the description field</Description>
        <Copyright>Copyright 2018</Copyright>
        <PackageTags>tag1, tag2</PackageTags>
        <AssemblyVersion>1.2.0.0</AssemblyVersion>
        <FileVersion>1.3.0.0</FileVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      </PropertyGroup>
    </Project>

Open this project file within Visual Studio 2017.  Edit the project's properties either in the package tab GUI or edit the properties through project file directly.  Updating one will no longer update the other.  Remove the "GenerateAssemblyInfo" tag/property from the project file and the information will be in sync again.

Is this by design?

**Comment by elmojo** [comment]
Also, when trying to add a Pre-build command line event, the event disappears after hitting the save button.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/project-system #3934](https://github.com/dotnet/project-system/issues/3934) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DILEEP-KS** [comment]
IN my project there no like that file...
dear my friends can you help how get back that error
