### ISSUE TITLE
Create New Minimal Start From Scratch DotNet

### ISSUE THREAD

**Issue by zero0000zero** [dotnet/core#1866]
How to create new minimal start from scratch DotNet?

**Comment by uffebjorklund** [comment]
You should just google "gettings started with dotnet core" => [https://docs.microsoft.com/en-us/dotnet/core/get-started](https://docs.microsoft.com/en-us/dotnet/core/get-started)

**Comment by leecow** [comment]
Also, visit https://www.microsoft.com/net and click "Getting Started".
