### ISSUE TITLE
Issue Consuming Connected Service (SOAP asmx) from behind a proxy

### ISSUE THREAD

**Issue by u112592** [dotnet/core#1867]
# Issue Title

Be as descriptive as you can with your title.

# General
I am having trouble to call a web service from .net core 2.0/2.1 behind a proxy. However from the full framework it works fine.
Here are the code sample (full Framework that works)
`BasicHttpBinding binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
            binding.UseDefaultWebProxy = false;
            binding.ProxyAddress = new Uri( "http://proxy");
            EndpointAddress add = new EndpointAddress("https://demo.ippayments.com.au/interface/api/dts.asmx");
            Bambora.dtsSoap client = new Bambora.dtsSoapClient(binding, add);
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            var response = client.SubmitSinglePayment(new Bambora.SubmitSinglePaymentRequest(new Bambora.SubmitSinglePaymentRequestBody(xml)));`

On the .net core i generated the proxy using connected service WCF web service client code below:
`BasicHttpBinding binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
            binding.ProxyAddress = new Uri("http://proxy");
            EndpointAddress add = new EndpointAddress("https://demo.ippayments.com.au/interface/api/dts.asmx");
            BamboraApi.dtsSoap client = new BamboraApi.dtsSoapClient(binding, add);
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            var response = client.SubmitSinglePaymentAsync(new BamboraApi.SubmitSinglePaymentRequest(new BamboraApi.SubmitSinglePaymentRequestBody(xml))).Result;`

As you can see there is hardly any difference apart from the fact that the proxy was generated through different tools. 
Is there is a workaround or a fix for this.

Many thanks

Mo

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/wcf #3167](https://github.com/dotnet/wcf/issues/3167) via [**ZenHub**](https://www.zenhub.com/)
