### ISSUE TITLE
Support .NET Core SDK Portable Mode

### ISSUE THREAD

**Issue by jamiewest** [dotnet/core#1868]
I would like to be able to use the .NET Core SDK from a USB drive, this is already somewhat possible but there are still default folders created on the host system (.nuget, .dotnet, .templateengine, etc.). There is already some issues around this:

[7569 - Request, able to config the location of ~/.dotnet and ~/.templateengine](https://github.com/dotnet/cli/issues/7569)
[4003 - Change default .nuget/package folder .NET Core](https://github.com/dotnet/cli/issues/4003)

It would be nice to have an option, maybe in the [dotnet-install](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) script, to enable a `-Portable` option that would change the path for all directories used by the SDK to point to a single location (i.e. a USB `.\data\` folder). This way full usage of the SDK would never touch the host file system. 

The Dream Setup:

Use [VS Code Portable](https://code.visualstudio.com/docs/editor/portable) with .NET Core SDK Portable living solely on a USB drive, and being able to move from computer to computer with a full dev environment on your key chain.

**Comment by leecow** [comment]
Issue moved to [dotnet/cli #9853](https://github.com/dotnet/cli/issues/9853) via [**ZenHub**](https://www.zenhub.com/)
