### ISSUE TITLE
Unable to analyze dotnet core dump in Amazon linux AMI container

### ISSUE THREAD

**Issue by shelgeram07** [dotnet/core#1870]
# Unable to analyze dotnet core dump in Amazon linux AMI container

We are facing memory utilization issues with our dotnet core application and want to analyze memory dumps. We followed below document for taking dump.
https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md

however, if try to open the dump with lldb it fails. 

is there any different way for taking memory dump in AWS linux AMI. 

@mikem8361 : Can you please help here?

**Comment by mikem8361** [comment]
I need some more details on how lldb fails. Are not getting any modules in the "target modules list" command? If your "host" is the dotnet program, then you need the exact version that the core dump was generated.  The symbol downloader should download the proper version.

What is your exact lldb command line/commands?

**Comment by shelgeram07** [comment]
Hi Mike, 
thanks for quick reply. I am getting below error

![image](https://user-images.githubusercontent.com/39510029/44382857-450a8580-a534-11e8-8c31-48b31e3cc874.png)

**Comment by mikem8361** [comment]
What does "target modules list" display? What is your the exact command you used to start lldb and all the commands to get the above point.  Need more info.  

It could also mean that the libmscordaccore.so doesn't match the libcoreclr.so in the dump. It may be easier to zip up core dump and all the other relevant binaries and send it to me.

**Comment by Petermarcu** [comment]
Looks like we need more information to help. I'm going to close this now. If there is more information, we can reopen and move this to the coreclr repo.
