### ISSUE TITLE
What is a correct way to add 'runtime' libs in netcore/netstandard NuGet package?

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/core#1871]
Some nuget packages need to copy native libs with managed part. For full .NET Framework working solution is 'build\netXX\*.targets' files, which copy native libs to output directory.
In .NET Core it is done by 'runtimes\**' directory, but I cannot find any docs about this feature.

This is needed for example for System.Data.Sqlite package - https://system.data.sqlite.org/index.html/tktview/d292f2e23d8a74e0e761

**Comment by Petermarcu** [comment]
@rrelyea

**Comment by Petermarcu** [comment]
This issue would be better to open on the Nuget/Home repo.

**Comment by AlexeiScherbakov** [comment]
I don't know where better, but I think that is related more to .NET Core infrastructure than directly to NuGet. .NET Core used runtimes to deploy some architecture/OS specific parts - but nowhere is explained how. Author of System.Data.Sqlite tried to 'mirror' this logic how he understand it, but it give problems like 'working in windows/not working anywhere else' 'working while debugging in VS/not working after deploy' and other. Also when normall .NET app started it Visual Studio, bin\Debug|Release folder contains all needed Dlls, when .NET Core app started in VS absolutely unclear from what location runtime dlls are loaded

**Comment by Petermarcu** [comment]
There are a few questions mixed in there. I'll move this issue to the CLI repo where the experts on how things get run in VS vs after publish work. Beyond that, how to pack nugey packages is definitely a nuget question.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9946](https://github.com/dotnet/cli/issues/9946) via [**ZenHub**](https://www.zenhub.com/)
