### ISSUE TITLE
TPL Joinblock sample works on .NET Framework 4.6, but has thread issue on Core

### ISSUE THREAD

**Issue by ZeroPKI** [dotnet/core#1872]
# Issue Title

I'm using the following sample on .NET Framework 4.6 and it runs properly, however when I use the same code with .Core, the other threads never get called.
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-joinblock-to-read-data-from-multiple-sources

# General

All information is included in the link
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-joinblock-to-read-data-from-multiple-sources

Simply compare the output between a .NET Core and .NET Framework console app

**Comment by MarcoRossignoli** [comment]
i think i better move this to https://github.com/dotnet/corefx where core TPL dataflow lives https://github.com/dotnet/corefx/tree/master/src/System.Threading.Tasks.Dataflow

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32057](https://github.com/dotnet/corefx/issues/32057) via [**ZenHub**](https://www.zenhub.com/)
