### ISSUE TITLE
Outdated statement about comment edit histories

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/core#1885]
https://github.com/dotnet/core/blob/master/Documentation/contributing/maintainers.md

Currently states:

> **Maintainers won't**
>
> * Edit contributor comments as a general rule. GitHub comments don't provide edit history and therefore don't offer maintainers a transparent and accurate way to describe changes made to contributor comments. Transparency is a cornerstone of effective discourse and its absence undermines trust.

This was changed in May. 

https://blog.github.com/changelog/2018-05-24-comment-edit-history/

I'm not advocating that maintainers should or should not edit contributor comments, but this statement as it stands is no longer correct.

**Comment by drewnoakes** [comment]
While looking at this it might also be good to include guidance on when maintainers will hide/delete comments. The ability to hide/minimise comments is a new GitHub feature, and can help push tangential discussion out of the main flow.

https://help.github.com/articles/managing-disruptive-comments/

**Comment by leecow** [comment]
@richlander @terrajobst

**Comment by terrajobst** [comment]
Good point. I've actually sent email to the team at that point but updating our guidance on GitHub didn't occur to me. Good catch!
