### ISSUE TITLE
support building ReadyToRun images

### ISSUE THREAD

**Issue by tmds** [dotnet/core#1886]
[bing.com is using .NET Core 2.1 with ReadyToRun images to reduce startup time](https://blogs.msdn.microsoft.com/dotnet/2018/08/20/bing-com-runs-on-net-core-2-1/).

It would be nice if the sdk supports building ReadyToRun images.

CC @KathleenDollard

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/cli/issues/1437

**Comment by Petermarcu** [comment]
I'm closing this because its a duplicate of dotnet/cli#1437 and I added this issue to track delivery of crossgen from the runtime to the SDK. https://github.com/dotnet/coreclr/issues/19797
