### ISSUE TITLE
Suggestions for the .NET Core 2.2 Preview 1

### ISSUE THREAD

**Issue by Amine-Smahi** [dotnet/core#1887]
Suggestion : 
1) The page1 an page2 navbar links should link to real pages and they should be about and contact, That will be helpful to demonstrate the routing, and how you link to other pages.
2) For better UI consistency the page1 and page2 navbar links should be aligned to the right (in mvc project)
3) Change the url from https://example.com/?action=Index&controller=Home to htps://example.com/Index or Home to make it SEO friendly
4) Add button bootstrap class to the counter button

**Comment by Eilon** [comment]
This issue was moved to aspnet/Templating#712
