### ISSUE TITLE
Open device using operating system open-function returns EISDIR using .NET Core

### ISSUE THREAD

**Issue by FrankPfattheicher** [dotnet/core#1891]
# Open device using operating system open-function returns EISDIR using .NET Core

I am using interop to access basic file api of linux (Respberry Pi).

`[DllImport("libc", SetLastError = true, CharSet = CharSet.Auto)] internal static extern int open(string fileName, int mode);
`

Opening a device like tty

`var handle = Interop.open("/dev/tty", Interop.O_RDWR);
`

fails with errno=21 (EISDIR)

Same code running full framework (Mono 4.6.2) the device is opened successfully and i can use read and write!

Where comes this difference?

**Comment by joshfree** [comment]
This issue was moved to dotnet/corefx#32442
