### ISSUE TITLE
dotnet core 2.1.3 runtime deployment on Azure app services

### ISSUE THREAD

**Issue by branstraub** [dotnet/core#1898]
# dotnet core 2.1.3 runtime deployment on Azure app services

Is there any timeline for deploying the runtime / sdk to the app services environment?
If no.. is there a way to do it manually trough the terminal' bash of the appService.

Regards :)

**Comment by leecow** [comment]
@branstraub West Central US is up and running with 2.1.3 as of this morning. Other regions will roll out over the next few days.

**Comment by Petermarcu** [comment]
@glennc isn't there also a way to use site extensions to get the latest?
