### ISSUE TITLE
.NET Core 2.1 Benchmarking, req/s far below what's expected.

### ISSUE THREAD

**Issue by pimbrouwers** [dotnet/core#1899]
I was running an arbitrary benchmark on an empty .NET Core web app today and was disappointed at how low the req/s numbers consistently were. I've seen [examples][1] online where people are getting 50-60k req/s, [some][4] as crazy as 1.15M req/s, and mine clock in between 1-2.5k. 

### My machine specs:

[![enter image description here][2]][2]

### Code:
```c#
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using System.IO;
namespace NetCore
{
  public class Startup
  {
    public static void Main(string[] args)
    {
      CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();

    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
      app.Run(async (context) =>
      {
        await context.Response.WriteAsync("Hello World!");
      });
    }
  }
}
```
Which I'm running using the **release** configuration, targeting `netcoreapp2.1`:

    dotnet publish -c release -f netcoreapp2.1

And I'm benchmarking using bombardier:

    bombardier http://localhost:5000 -c 250 -d 30s

### Results:

![image](https://user-images.githubusercontent.com/4595453/44748134-fa14e300-aadc-11e8-94b0-3823c645a3b9.png)

  [1]: https://medium.com/@tampajohn/net-core-2-and-golang-797566350095
  [2]: https://i.stack.imgur.com/cyYLA.png
[4]: https://www.ageofascent.com/2016/02/18/asp-net-core-exeeds-1-15-million-requests-12-6-gbps/

Just wondering whether I'm missing something obvious here. Or doing something wrong.

**Comment by benaadams** [comment]
Might have console logging on? (There are faster forms of logging)

Try switching it off by adding a `appsettings.json` file
```
{
  "Logging": {
    "LogLevel": {
      "Default": "None"
    }
  }
}
```
Also ensure you are using Server GC; the top of your `.csproj` should have `.Web` at the end
```
<Project Sdk="Microsoft.NET.Sdk.Web">
```

Also you are running the published dll?
```
dotnet bin\release\netcoreapp2.1\publish\myapp.dll
```

**Comment by pimbrouwers** [comment]
Hi Ben!

Feel like I'm talking with a living legend here!

Thanks for the feedback. The logging level appears to be the culprit. You mention faster forms of logging. I assume that this is anything that's doing it's io asynchronously?

I implemented the logging level in the startup code (lazy):

```c#
public void ConfigureServices(IServiceCollection services)
    {
      services.AddLogging(
        builder =>
        {
          builder.AddFilter("Microsoft", LogLevel.Warning)
                 .AddFilter("System", LogLevel.Warning)
                 .AddConsole();
        });
    }
```

Which is yielding me around 70k req/s, even on my ultra low-voltage machine:
![image](https://user-images.githubusercontent.com/4595453/44779603-ece40c80-ab4d-11e8-9437-fe1890ecbac4.png)

**Comment by benaadams** [comment]
The issue with Console logging is it has a lock on the output so only one thing can Write at a time (also is slow); coupled with `Information` level being very verbose

**Comment by benaadams** [comment]
Opened issue  https://github.com/aspnet/Home/issues/3473

**Comment by benaadams** [comment]
Add to your .csproj
```xml
<PropertyGroup>
  <ServerGarbageCollection>false</ServerGarbageCollection>
</PropertyGroup>
```
And it should use less memory; though also may not have support as high a throughput

**Comment by pimbrouwers** [comment]
Wild! That drops the values to:
(Idle) 16mb / 390 handles
(Mid-benchmark) 32mb / 1148 handles 

For what it's worth, adding `<ServerGarbageCollection>false</ServerGarbageCollection>` also increase the http throughput.

I assume the increased process handle coincides with the lack of Garbage collection?  What are the side effects of using that property? I find it so strange that disabling Server Garbage Collection which is supposed to facilitate high throughput and scalability, actually improves performance here.

**Comment by benaadams** [comment]
> What are the side effects of using that property? 

Server Garbabge collection runs on all cores; uses multiple allocating heaps and much larger triggering threasholds; it operates as if the machine is dedicated to running

@sebastienros did a good overview on this week's ASP.NET Community Standup: https://youtu.be/DiqqlDPfch4?t=49m51s

Also he has done a write up at: https://github.com/sebastienros/memoryleak

**Comment by benaadams** [comment]
> I find it so strange that disabling Server Garbage Collection which is supposed to facilitate high throughput and scalability, actually improves performance here.

Might be freeing up resources for the benchmarker to run as you are running them both on the same machine (the Server GC also uses all cores when it runs)
