### ISSUE TITLE
Resharper: Intellisense partially broken in Visual Studio 2015 on Preview2 Tooling

### ISSUE THREAD

**Issue by psibernetic** [dotnet/core#190]
I have this issue on 3 separate machines, all Visual Studio 2015 Update 3, Tooling installed, Resharper latest.

http://stackoverflow.com/questions/38133604/how-to-fix-partial-intellisense-for-dotnetcore-rtm-in-visual-studio-2015

**Comment by psibernetic** [comment]
This is a Resharper bug, I finally found how to suspend it. Leaving this here as a FYI.

**Comment by rdghickman** [comment]
Try using Resharper 2016.2 EAP 6, this fixed the issue for me.

**Comment by blackdwarf** [comment]
Will close this one as it seems to be solved.
