### ISSUE TITLE
machine wide installation of user created .net core package

### ISSUE THREAD

**Issue by VishDev2018** [dotnet/core#1900]
# Issue Title

Machine wide installation of user created .net core package

# General
I have a package which I want to deploy once on a machine and let more than one application to use it at run time. Its more of a traditional .NET fullframework application  GAC deployment approach. I want to see if there are any support for such scenario with .NET Core. 

Thanks
Vishwa

**Comment by Petermarcu** [comment]
There currently is not any good support for this. It is something that we're exploring for .NET Core 3.0. I'm going to move this to the right repo where the people working on that problem will see it.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #4525](https://github.com/dotnet/core-setup/issues/4525) via [**ZenHub**](https://www.zenhub.com/)
