### ISSUE TITLE
RegEx.IsMatch appear to fall into infinite loop

### ISSUE THREAD

**Issue by ie-zero** [dotnet/core#1901]
# Issue Title
Regex.IsMatch appears to fall into an infinite loop when attempting to match 

string ```"BEGIN:VCOMPONENT\r\nBEGIN:VCOMPONENT\r\n"``` 
against ```@"^(BEGIN\:VCOMPONENT\r\n)(.*\n*)*(END:VCOMPONENT\r\n)$"``` regular expression.

# General
I have experienced this behaviour on Windows 7 under .NET Core 2.1.401 using the following tests

```C#
[Fact]
public void PassingTest()
{
	const string regEx = @"^(BEGIN\:VCOMPONENT\r\n)(.*\n*)*(END:VCOMPONENT\r\n)$";
	var actual = Regex.IsMatch("BEGIN:VCOMPONENT\r\nBEGIN:VCOMPONENT\r\n", regEx);

	Assert.False(actual);
}
```
```C#
[Fact]
public void InfiniteLoopTest()
{
	const string regEx = @"^(BEGIN\:VCOMPONENT\r\n)(.*\n*)*(END:VCOMPONENT\r\n)$";
	var actual = Regex.IsMatch("BEGIN:VCOMPONENT\r\nDummyName:DummyValue\r\nBEGIN:VCOMPONENT\r\n", regEx);

	Assert.False(actual);
}
```

# System Information 

.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3-servicing-26724-03
  Commit:  124038c13e

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32055](https://github.com/dotnet/corefx/issues/32055) via [**ZenHub**](https://www.zenhub.com/)
