### ISSUE TITLE
dotnet run System.ArgumentNullException: for a simple program with new installation of .netcore 2.1.401

### ISSUE THREAD

**Issue by noorrocks** [dotnet/core#1904]
# Issue Title

dotnet run System.ArgumentNullException: for a simple program with new installation of .netcore 2.1.401

# General

Trying to get started with .netcore programming. Followed the basic tut from asp.net website but failed.

https://www.asp.net/get-started

I get the error (attached) after dotnet run command. 

[Powershell output](https://codeshare.io/5w3X9p)

This is my first ever program after a fresh installation of the latest SDK (as of now). I have tried console app and it works fine. Even a simple app with 'web' template works ok and display 'Hello World' in the browser. However, as soon as I add 'services.addMVC' to the app it breaks with the same error. I have done all my research and tried a lot of things, but not sure what is happening.

Program files:
[Files](https://app.box.com/s/kzsy7t5tzmg93ykqkhvxbyci1l5zgre7)

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9932](https://github.com/dotnet/cli/issues/9932) via [**ZenHub**](https://www.zenhub.com/)
