### ISSUE TITLE
How many supports does .NET Core have for games？

### ISSUE THREAD

**Issue by forestbat** [dotnet/core#1906]
Or any plans？Although it's probably difficult，I still want .NET Core to generate cross-platform games instead of Mono or Xamarin。

**Comment by benaadams** [comment]
For graphics you can use https://github.com/mellinoe/veldrid (which is .NET Standard and runs on .NET Core)

Do you mean a game engine?

**Comment by forestbat** [comment]
@benaadams Yes，there is no game engine rely on .NET Core（unity 3d still uses mono）。
And in visual studio，we still only can use .NET Core to generate console programs or class library instead of desktop programs。

**Comment by Petermarcu** [comment]
We are working on supporting Desktop applications in .NET Core (WPF and WinForms).

**Comment by Petermarcu** [comment]
Xamarin is the plan for mobile platforms. It is based on mono but may at some point in the future consider being based on .net core. Which runtime is under the hood shouldn't matter too much. Is there a specific reason you want .net core under the hood for mobile apps?

**Comment by forestbat** [comment]
I just think .net core is better than mono，so I want to ask if MS want to unify the two platform to simplify work。
And in VS，although most of disk space wasted by Google's emulator and SDK，unify xamarin and .net core can also save plenty of disk space。

**Comment by Petermarcu** [comment]
Unification is something we will explore and consider in the future but don't have any concrete plans at this point.
