### ISSUE TITLE
How to get hardware information for MacOs、Linux and other OS

### ISSUE THREAD

**Issue by linkanyway** [dotnet/core#1908]
# How to get hardware information for MacOs、Linux and other OS

is any possible to get hardware information by .net core

there is have `RuntimeInformation` class can help me to get .net core version some other helpful information, but i really need get hardware information also  like CPU core number,CPU speed, memory size,disk information...

thanks!

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32054](https://github.com/dotnet/corefx/issues/32054) via [**ZenHub**](https://www.zenhub.com/)
