### ISSUE TITLE
Net Standard 2 is not compatible with Net Core 2

### ISSUE THREAD

**Issue by wgutierrezr** [dotnet/core#1909]
I have multiple projects in one solution, two of them class libraries: Net Core 2 Class Library (EMS.Entities) and Net Standard 2 Razor UI class library (EMS.UIService), using VS 2017 Pro.

EMS.UIService cannot compile because the error (included dotnet restore command) :
**C:\Projects\EMS2\EMS\EMS.UIService\EMS.UIService.csproj : error NU1201: Project EMS.Entities is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project EMS.Entities supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [C:\Projects\EMS2\EMS\EMS.sln]**

I googled this error and did almost every recommendation to solve it but still the same error.

I will appreciate any suggestion to solve it.

Regards.

**Comment by Petermarcu** [comment]
Is the UIService Project a netstandard project while the Entities project is netcoreapp? You can't reference a netcoreapp project from a netstandard project. Only the other way around.

**Comment by Petermarcu** [comment]
You can switch the UIService class library project to be netcoreapp and it should work. Otherwise, you need to make the Entities project netstandard.

**Comment by Petermarcu** [comment]
I'm going to close this now. Let us know if you have more details or can clarify whether you were trying to have a .NET Standard Library reference a .NET Core library or the other way around.
