### ISSUE TITLE
I can't find the ConvertAll() in Array class. How can I convert an object to array in .net core?

### ISSUE THREAD

**Issue by BingyuLiu** [dotnet/core#191]
I can't find the ConvertAll() in Array class. 
How can I convert an object to array in .net core? Thanks.

**Comment by svick** [comment]
`Array.ConvertAll` converts one array into another by invoking a delegate on each member.

You can achieve the same result by using `source.Select(converter).ToArray()`.

**Comment by blackdwarf** [comment]
@BingyuLiu in addition, https://docs.microsoft.com/en-us/dotnet/core/api/index contains the .NET Core API reference documentation. 

With this and @svick answer, I will close this issue.
