### ISSUE TITLE
.NET Core 2.1 downgrades HTTP/2 requests

### ISSUE THREAD

**Issue by lukebondespok** [dotnet/core#1910]
Hello!

I have a Console application that targets .NET Core 2.1 in which I make an HTTP/2 request to google. However, when I inspect the outgoing HTTP request, I notice that the request was downgraded to HTTP/1.1. This can also be verified by checking the Version of the response.

```C#
var client = new HttpClient();

var req = new HttpRequestMessage(HttpMethod.Get, "https://www.google.com")
{
      Version = new Version(2, 0)
};

var x = client.SendAsync(req);

var version = x.Result.Version; // 1.1
```

If I target .NET Core 2.0 or earlier, the HTTP/2 header is not altered.

Is this a known issue? Does anyone have any insight into this problem?

For the record, this is a problem on both Windows and Mac.

Thanks!

**Comment by MarcoRossignoli** [comment]
i think is better move to corefx repo https://github.com/dotnet/corefx/issues 
where HttpClient lives https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs

/cc @karelz

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32068](https://github.com/dotnet/corefx/issues/32068) via [**ZenHub**](https://www.zenhub.com/)
