### ISSUE TITLE
 Some methods supported in lower version but not in higher version

### ISSUE THREAD

**Issue by wengxk** [dotnet/core#1912]
I got some questions that why there are some methods  supported in lower version but not in higher version. For example, SqlParameterCollection.Add(String, SqlDbType, Int32, String)  method  and SqlDataAdapter.UpdateBatchSize property applies to .net core 2.0 but 2.1 not yet.
Is there anybody konw about it , i will very appreciate! Thanks!

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32105](https://github.com/dotnet/corefx/issues/32105) via [**ZenHub**](https://www.zenhub.com/)
