### ISSUE TITLE
system.InvalidOperationException: No connection string named test' could be found in the application config file.    at System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel()    at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()    at System.Data.Entity.Internal.InternalContext.Initialize()    at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)    at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()    at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()

### ISSUE THREAD

**Issue by maddy027** [dotnet/core#1914]
I am using EF6 DB first with Asp.net core . when I try to retrieve the details from db using context object , getting error as "System.InvalidOperationException: No connection string named 'test' could be found in the application config file."
And flow is Asp.net core webpai(controller)-> BL->DAL(EDMX)

I have added connection string in the app setting . What could be the issue

**Comment by maddy027** [comment]
Does asp.net core supports EF 6 with DB First approach ?. Most of the blogs i found using code first approach https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1

**Comment by ajcvickers** [comment]
Duplicate filed here: https://github.com/aspnet/EntityFramework6/issues/620
