### ISSUE TITLE
.NET Core 2.1 DirectoryInfo.EnumerateFiles() Performance is Slower than .NET Framework

### ISSUE THREAD

**Issue by ONeill45** [dotnet/core#1916]
# Issue Title

.NET Core 2.1 DirectoryInfo.EnumerateFiles() Performance is Slower than .NET Framework

# General

I have a .NET Core 2.1 Web API that is being built as a replacement for an older .NET Framework MVC Web Application (.NET Framework 4.5).

One of the responsibilities of this application is to take in a directory and search template and return the top 10 results, ordered by most recent. This is being accomplished using System.IO.DirectoryInfo and the EnumerateFiles() method:

```

List<FileInfo> fileInfos = new DirectoryInfo(directory).EnumerateFiles(fileTemplate)
.OrderByDescending(f => f.LastWriteTime).Take(10).ToList();

```

However, I am noticing that this search is much, much slower in .NET Core than in .NET Framework. I created two console apps with the same code, one .NET Framework and one .NET core, to compare run times. Below are the results in .NET Framework:

![image](https://user-images.githubusercontent.com/13375042/45037835-e6620300-b02d-11e8-8864-8959deaa85e8.png)

And then the results in .NET Core:

![image](https://user-images.githubusercontent.com/13375042/45037921-1f9a7300-b02e-11e8-9711-ff262816856b.png)

Can anyone help me understand why there is such a dramatic decrease in performance?

**Comment by MarcoRossignoli** [comment]
better move to https://github.com/dotnet/corefx

/cc @JeremyKuhne, @pjanotti

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32098](https://github.com/dotnet/corefx/issues/32098) via [**ZenHub**](https://www.zenhub.com/)
