### ISSUE TITLE
Amazon Linux distro - official support

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core#1917]
# Issue Title

What's the process for getting .NET Core to officially support an additional Linux distribution?

# General

I'd like to work toward getting Amazon Linux added to the list of officially supported Linux distributions for .NET Core. 

What needs to be done, and where can I get started?

**Comment by vellozzi** [comment]
moved to https://github.com/dotnet/coreclr/issues/19854

**Comment by Petermarcu** [comment]
This is probably the best place to discuss this.

**Comment by vellozzi** [comment]
It's derived from Red Hat.

**Comment by vellozzi** [comment]
Any update?
I'm hoping to have this done by the end of the year.  Is that a realistic goal?

**Comment by joshfree** [comment]
Is there an official distribution of Amazon Linux for use outside the Amazon cloud that can be used for OSS development and testing purposes?

**Comment by vellozzi** [comment]
There are docker images of the Amazon Linux releases.  Those could be used for testing.
https://hub.docker.com/_/amazonlinux/

**Comment by joshfree** [comment]
Hi @vellozzi you can send a PR to update `Microsoft.NETCore.Platforms` in the dotnet/corefx repo to add the new OS to the RID graph.  The instructions are here https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/readme.md#adding-a-new-os; but basically you’ll need to add a new entry to `runtimeGroups.props` and then run `build -- /p:UpdateRuntimeFiles=true` to update the build generated `runtime.compatibility.json` and `runtime.json` artifacts.  Let me know if you have any questions and feel free to tag me in the PR.  Thanks 😃
