### ISSUE TITLE
Net Core Instant Code Changes (Like JRebel)

### ISSUE THREAD

**Issue by ozibrahim** [dotnet/core#1919]
Hi,
Is there any net core alternative of JRebel to apply instant code changes? (For .cs files)
I'm already aware of dotnet-watch, but it is not apply our code changes faster, only automate by saving file action. I mean, is it possible to update only builded c# code without restart app?

Thanks,

**Comment by igoventura** [comment]
Visual Studio hot reload the project when you make an modification with the execution paused (with a breakpoint or pausing the execution itself) so you can make modifications, continue the execution and will not have to restart the execution from zero.

**Comment by ozibrahim** [comment]
@igoventura  thanks for comment but do you know about this feature on Jetbrains Rider? 
I'm developing .net core on Mac OS.

**Comment by Eilon** [comment]
Sounds like Edit & Continue? This probably isn't ASP.NET Core specific.

@Petermarcu - do you know who a contact is regarding E&C?

**Comment by karelz** [comment]
Edit & Continue is supported in Visual Studio IDE (on Windows).
It is IDE specific feature. If you need it in Jetbrains Rider, I would ask on their forums.
