### ISSUE TITLE
2.1.1 is not compatible with net47

### ISSUE THREAD

**Issue by drauch** [dotnet/core#1921]
* I have an ASP.NET Core app which is targeting the FULL .NET Framework 4.7.1.
* Until yesterday VS build and MSBuild-based console build both worked
* Upgraded from ASP.NET Core 1.1.x to 2.1.x today
* VS build still works, no problem at all
* MSBuild-based console build fails with TONS of errors like this:

> Package Microsoft.Extensions.Configuration.CommandLine 2.1.1 is not compatible with net47 (.NETFramework,Version=v4.7). Package Microsoft.Extensions.Configuration.CommandLine 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
> [...]
> Package Microsoft.AspNetCore.Mvc 2.1.2 is not compatible with net47 (.NETFramework,Version=v4.7). Package Microsoft.AspNetCore.Mvc 2.1.2 supports: netstandard2.0 (.NETStandard,Version=v2.0)
> [...]

What are we doing wrong? Do we need to udpate MSBuild somehow? Note: we're NOT using the "dotnet build" tool.

**Comment by dasMulli** [comment]
Which version of msbuild / visual studio are you using? (`msbuild /version`)

**Comment by drauch** [comment]
Visual Studio 2017 15.8.2
    Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework

**Comment by Petermarcu** [comment]
@livarcocc who are the right people to take a look at this one?

**Comment by livarcocc** [comment]
@natemcmaster to comment.

**Comment by natemcmaster** [comment]
Seems odd. It might be the result of some overaggressive caching. Try a full `git clean -ixd` and also try restarting your PC to make sure all `msbuild.exe` background nodes are dead.

**Comment by drauch** [comment]
I installed Visual Studio 15.8.3, as they said "15.8.2 contained a pre-release build of .NET Core SDK 2.1.401 that is incompatible with Visual Studio" but it didn't help either. Even reinstalled the .NET Core SDK 2.1.401 no change.

@natemcmaster : But it isn't just me. It's also happening on our build agents (they also have Visual Studio installed). Still, git clean and restart didn't help.

**Comment by drauch** [comment]
Ah, I think I found the problem after many hours of tinkering...I updated NuGet.exe from 4.1.0 to 4.7.1, now the console build works too.

Thanks for engaging guys - hope this helps somebody out there facing similar troubles!

**Comment by dasMulli** [comment]
@drauch If the project is SDK-based (asp.net core), you should build with `msbuild /restore foo.csproj` instead of restoring with nuget.exe, then you automatically get the NuGet version included in VS

**Comment by drauch** [comment]
Actually we are doing that. But not all our projects are SDK-based yet, so in a second step we restore using nuget.exe as well. That's probably not a good idea. I'll try to rewrite it so that only the non-SDK-based projects get restored using nuget.exe

Thanks for the advice!

**Comment by dasMulli** [comment]
Actually it's not so much SDK vs non-SDK projects but rather a PackageReference vs. packages.config projects.
fyi non-SDK projects can also use PackageReference and should work with `msbuild /restore` ([migration documentation](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference)). There's an issue logged to enable packages.config restore using msbuild but that's a little more complicated.

**Comment by drauch** [comment]
It's a little tricky actually, we have only a single classical project called "SolutionPackages" which is used to obtain tools and install them in the SolutionDir\packages folder. This is not possible anymore with PackageReferences which are "installed" into the NuGet cache folder outside the solution dir.

**Comment by dasMulli** [comment]
If you ever want to move off this approach or looking for alternatives, I'm happy to chat about it here or on the [community slack workspace](http://tattoocoder.com/aspnet-slack-sign-up/).
Your scenarios might help uncover tooling needs or shortcomings.
There's now global tools in .net core tooling and local tools are currently being implemented. And a lot of `$(SolutionDir)packages\tools\foo.exe` things in project files are being replaced by NuGet authors through packages that contain some .targets files that are auto-imported and tools (dll / exe / shell scripts / msbuild tasks) local to the package.

**Comment by dasMulli** [comment]
JetBrains does offer a zip download as well in addition to NuGet packages.

There is a feature coming in NuGet 4.9 / VS 15.9 / dotnet 2.1.5xx that can help migrating:
NuGet can create MSBuild properties pointing to the path of the package - https://github.com/NuGet/NuGet.Client/pull/2271 / https://github.com/NuGet/Home/issues/6949 

So you could annotate the package using
```xml
<PackageReference Include="Some.Inspection.Tool" Version="1.2.3" GeneratePathProperty="MyInspectionPackage" />
```
and then use it like:
```xml
<Target AfterTargets="AfterBuild">
  <Exec Command="$(MyInspectionPackage)tools\inspect.exe" />
</Target>
```
