### ISSUE TITLE
Trivial dotnet example hangs indefinitely during configuration step.

### ISSUE THREAD

**Issue by astrophys** [dotnet/core#1922]
I am running CentOS 6.9 and I am installing dotnet so I can use the [Microsoft Quantum Development Kit](https://docs.microsoft.com/en-us/quantum/quantum-installconfig?view=qsharp-preview&tabs=tabid-vscode).  I have no experience with using dotnet.  I followed the instructions for the [installation](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md).  I installed the yum packages, ICU and CURL.  I pointed LD_LIBRARY_PATH and PATH to the appropriate directories for ICU and CURL (I installed them in a non-standard directory).

Following Microsoft's [tutorial](https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial), I ran  

```
$ ../dotnet/dotnet new console -o myApp

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 5825 ms
```

It seems that `dotnet` hangs in this instance.  It stays in this state (indefinitely?).  I killed it after 30minutes.  Running `strace`:

```
$ strace -p 26644
Process 26644 attached
futex(0x2368d14, FUTEX_WAIT_PRIVATE, 3, NULL
```
This seems to [indicate](https://meenakshi02.wordpress.com/2011/02/02/strace-hanging-at-futex/) that it is waiting for the other threads to finish.  However, there aren't any daughter threads, e.g. 

`pgrep -P 26644`

returns nothing.

Question: How do I get this trivial example to work?

**Comment by Petermarcu** [comment]
@livarcocc 

I dont believe we support the .NET Core SDK running on Centos 6.9. You should be able to run it on Centos 7.2 or higher and create apps that will run on the .NET Core Runtime on Centos 6.9 following those instructions.

**Comment by livarcocc** [comment]
Right, we don't support that OS, which is likely why you are hitting issues. You could try skipping the first run experience, but that would likely just be one in a series of issues.

**Comment by astrophys** [comment]
So the instructions [here](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md) are out of date?

**Comment by danmosemsft** [comment]
@astrophys I think so. (cc @janvorli )

The supported platforms for 2.1 are listed here: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md
