### ISSUE TITLE
ASP.NET Core SDK version and Hosting Bundle version should be released together

### ISSUE THREAD

**Issue by ackava** [dotnet/core#1924]
If Hosting Bundle is not Production ready (still in "Preview" state), there is no point in updating ASP.NET Core assemblies to release state. I accidentally updated NuGet packages and production site went down !!

**Comment by leecow** [comment]
The latest Preview release is for .NET Core / ASP.NET Core 2.2 (preview 2 coming later this week). The September update for 2.1 was released this morning. The SDK runs on a somewhat different versioning cadence which does confuse matters a bit but you can easily tell what goes together on our download pages. Here's the 2.1 page as an example - https://www.microsoft.com/net/download/dotnet-core/2.1

**Comment by ackava** [comment]
Hi, I understand versioning but you must consider a production environment
where I just updated all nuget packages and Core 2.2 packages went in
production with no production ready hosting package.

My request is simple, till Core 2.2 hosting package is not production
ready, all nuget packages of 2.2 should be in preview and not in live.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
