### ISSUE TITLE
Cannot install dotnet-hosting-2.0.9

### ISSUE THREAD

**Issue by farazahmed879** [dotnet/core#1926]
# Issue Title

Can not install hosting bundle on ubuntu 18

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

root@ubuntu-s-1vcpu-2gb-blr1-01:~/production#lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

root@ubuntu-s-1vcpu-2gb-blr1-01:~/production# sudo apt-get install dotnet-hosting-2.0.9
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-hosting-2.0.9
E: Couldn't find any package by glob 'dotnet-hosting-2.0.9'
E: Couldn't find any package by regex 'dotnet-hosting-2.0.9'

**Comment by pietrodicaprio** [comment]
Have you registered the key and the feed?
Try to follow this procedure: https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current

**Comment by Petermarcu** [comment]
@joeloff

**Comment by leecow** [comment]
@farazahmed879 - Please follow the configuration guidance at https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/runtime-2.0.9 and you should be good to go. Just tried this on a clean 18.04 image and everything is fine. 

```
root@9ca485c88922:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@9ca485c88922:/# apt install dotnet-hosting-2.0.9
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-store-2.0.0 aspnetcore-store-2.0.3 aspnetcore-store-2.0.5 aspnetcore-store-2.0.6 aspnetcore-store-2.0.7
  aspnetcore-store-2.0.8 aspnetcore-store-2.0.9 dotnet-host dotnet-hostfxr-2.0.9 dotnet-runtime-2.0.9 krb5-locales libasn1-8-heimdal
  libcurl3 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal
  libicu60 libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblttng-ust-ctl4
  liblttng-ust0 libnghttp2-14 libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.0.0
  libunwind8 liburcu6 libwind0-heimdal
Suggested packages:
  krb5-doc krb5-user libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp
  libsasl2-modules-sql
The following NEW packages will be installed:
  aspnetcore-store-2.0.0 aspnetcore-store-2.0.3 aspnetcore-store-2.0.5 aspnetcore-store-2.0.6 aspnetcore-store-2.0.7
  aspnetcore-store-2.0.8 aspnetcore-store-2.0.9 dotnet-host dotnet-hostfxr-2.0.9 dotnet-hosting-2.0.9 dotnet-runtime-2.0.9 krb5-locales
  libasn1-8-heimdal libcurl3 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libicu60 libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
  liblttng-ust-ctl4 liblttng-ust0 libnghttp2-14 libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db
  libsqlite3-0 libssl1.0.0 libunwind8 liburcu6 libwind0-heimdal
0 upgraded, 41 newly installed, 0 to remove and 13 not upgraded.
Need to get 69.3 MB of archives.
After this operation, 237 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by JunTaoLuo** [comment]
I'm trying this on a local VM and hit a separate issue. @leecow can you also try 18.04.1? 

When I try to install `dotnet-hosting-2.0.9` I get an error:
```
The following packages have unmet dependencies:
 dotnet-hosting-2.0.9 : Depends: dotnet-runtime-2.0.9 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Using aptitude, I was able to get a more useful message:
```
The following NEW packages will be installed:
  aspnetcore-store-2.0.0{a} aspnetcore-store-2.0.3{a} aspnetcore-store-2.0.5{a} 
  aspnetcore-store-2.0.6{a} aspnetcore-store-2.0.7{a} aspnetcore-store-2.0.8{a} 
  aspnetcore-store-2.0.9{a} dotnet-host{a} dotnet-hostfxr-2.0.9{a} dotnet-hosting-2.0.9 
  dotnet-runtime-2.0.9{a} libcurl3{ab} liblttng-ust-ctl4{a} liblttng-ust0{a} liburcu6{a} 
0 packages upgraded, 15 newly installed, 0 to remove and 63 not upgraded.
Need to get 57.8 MB of archives. After unpacking 194 MB will be used.
The following packages have unmet dependencies:
 libcurl3 : Conflicts: libcurl4 but 7.58.0-2ubuntu3.2 is installed
 libcurl4 : Conflicts: libcurl3 but 7.58.0-2ubuntu2 is to be installed
```

Looks like this may be related to https://github.com/dotnet/core-setup/issues/3791. Looks like out 2.0.x packages depend on libcurl3 and Ubuntu 18.04 comes with libcurl4 instead. I assume 2.1.x and later packages won't run into this issue since there is no libcurl dependency.

However, given that this is a 2.0.x package which are EOL in October, is this something that we want to fix?

**Comment by leecow** [comment]
Tried on my 18.04.1 machine and it worked fine both with no version of libcurl installed and with libcurl4 installed before installing dotnet-hosting-2.0.9.

**Comment by moijafcor** [comment]
I've been trying to install on three Ubuntu 18.04 boxes with no success in two of them. There is some rare combination of dependencies that prevent it from installing because libcurl3 refuses to install with no good reason though:

```bash
 dotnet-runtime-2.0.9 : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
```

**Comment by leecow** [comment]
@moijafcor - what do you see if you try to install libcurl3 directly (`apt install libcurl3`)?

**Comment by karelz** [comment]
No response for 13 days, closing. Let us know if you find more information about the problem.
This seems related: https://github.com/dotnet/core-setup/issues/3875

**Comment by karelz** [comment]
@Thraka do you get the same failure with .NET Core 2.1? (2.0 is out of support)
2.1 should not have that dependency of Runtime.

**Comment by Thraka** [comment]
@karelz Yes sorry, this is core 2.1 I **believe** this is a libcurl4 vs 3 problem. I basically cannot install the .net core package via `apt-get install` as it fails with a package conflict. It won't tell me what package is conflicting. I'm not a linux guru so it's taken me some time to try and figure out what is going on.

**Comment by karelz** [comment]
cc @wfurt to comment on the libcurl4 vs. 3.

**Comment by leecow** [comment]
@Thraka , the system components are installed by the dotnet-runtime-deps-2.1 package. If you try installing that directly, we should see exactly what library is causing the trouble. 

`sudo apt install dotent-runtime-deps-2.1`

**Comment by Thraka** [comment]
@leecow I installed that, and it worked. But when I try to install the SDK, it still fails

```bash
andy@adegeolinux:~$ sudo apt install dotnet-sdk-2.1.202
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to randy@adegeolinux:~$ esolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1.202 : Depends: dotnet-runtime-2.0.9 but it is not going to be installed
```
I listed the packages and it says it's installed:

```bash
andy@adegeolinux:~$ sudo apt list dotnet-runtime*
Listing... Done
dotnet-runtime-2.0.7/bionic 2.0.7-1 amd64
dotnet-runtime-2.0.9/bionic 2.0.9-1 amd64
dotnet-runtime-2.1/bionic 2.1.5-1 amd64
dotnet-runtime-2.1.0-preview2-26406-04/bionic 2.1.0-preview2-26406-04-1 amd64
dotnet-runtime-2.1.0-rc1/bionic 2.1.0-rc1-1 amd64
dotnet-runtime-deps-2.1/bionic,now 2.1.5-1 amd64 [installed]
```

**Comment by karelz** [comment]
@Thraka you are still trying to install the out-of-support SDK for .NET Core 2.0 (the version 2.1.202) - see [2.0.9 release notes](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.9.md) or [2.0 versions table](https://github.com/dotnet/core/tree/master/release-notes/2.0#net-core-20-releases---out-of-support).

Install 2.1.5 + its SDK 2.1.403: see [2.1.5 release notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.5/2.1.5.md).

**Comment by leecow** [comment]
More specifically, run `sudo apt install dotnet-sdk-2.1` and you should be golden. This will install the latest version of the 2.1 SDK.

**Comment by Thraka** [comment]
@karelz @leecow uhghhghghgahahrrrr Thanks... google search must have pulled me into the 2.0 install instructions page because and because of the version of the sdk showing 2.1 I just didn't notice the page title said 2.0 ... 

This versioning is confusing 😄

**Comment by cdaf** [comment]
If someone else stumbles across this supporting a legacy app on current LTS Ubuntu, I got this working by simply removing curl before install
```
apt-get update
apt-get install -y apt-utils apt-transport-https
apt-get install -y aspnetcore-runtime-2.2
apt remove -y curl
apt-get install -y dotnet-hosting-2.0.9
```

**Comment by thisclubhouse-is-weird** [comment]
sus
