### ISSUE TITLE
Remote debugging - variable does not exist in the current context

### ISSUE THREAD

**Issue by pietrodicaprio** [dotnet/core#1928]
# Remote debugging - variable does not exist in the current context

#### Issue

I'm trying to debug a code using the remote debugger.
The application is in .Net Core and is running in Linux.
The connection works fine and the breakpoints are hit.

The only issue is that i can't read the variables value (when the BP is hit) and if i add the variable to the Watch List or check the value using the Immediate Window i receive an error because the variable "does not exist in the current context".

Of course if i run the project on my computer instead of the remote server all the variables are read without any kind of issue.
And of course the remote DLL(s) are compiled in Debug mode.

#### Base info
.NetCore.App 2.0.1
.AspNetCore.App 2.1.1
It happens both in Library project and AspNet project
Visual Studio 2017 [15.8.2] Enterprise
Dev machine running W10
Server running CentOS

#### Additional, important, note
In this specific scenario the DLL is loaded with Reflection.
Since i had some issue with breakpoints i set `<DebugType>embedded</DebugType>` and `<DebugSymbols>true</DebugSymbols>` (in .csproject file) to include all the symbols to the .dll

#### Question
Anyone had the same issue? Solution?

**Comment by Petermarcu** [comment]
@gregg-miskelly

**Comment by gregg-miskelly** [comment]
@pietrodicaprio do you see this for all variables? In all methods, or just some? 

Are you sure a debug version of your dll is being used? You can confirm/deny by:

1. Copy the dll back to Windows from your container
2. Open a developer command prompt and run `ildasm <path-to-dll>`
3. Check View->Verbal CA Blobs
4. Look for the 'DebuggableAttribute'
5. Check if the DisableOptimizations [DebuggingModes](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggableattribute.debuggingmodes?view=netframework-4.7.2) flag (256) is set

Example:
  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [System.Runtime]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [System.Runtime]System.Diagnostics.DebuggableAttribute/DebuggingModes)
  //           = {int32(263)}

**Comment by pietrodicaprio** [comment]
Hello @gregg-miskelly ,
in my MANIFEST there is the same of your example:

`// --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [System.Runtime]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [System.Runtime]System.Diagnostics.DebuggableAttribute/DebuggingModes)
  //           = {int32(263)}`

I'm also 100% sure about the debug dlls because my process flow is:
- use clean solution
- be sure to be in debug
- compile solution
- manually go to debug bin folder
- copy and transfer the new compiled dlls

Double checked right now:
it happens only with dll loaded using Reflection.
For a given `var assembly = Assembly.LoadFrom(Directory.GetCurrentDirectory() + part);`, depending on a previous check, i use `services.AddMvc().AddApplicationPart(assembly);` or `services.AddMvc().AddApplicationPart(assembly).AddControllersAsServices();`.
In both scenarios the issue is the same. As already said before i set the projects to include all the symbols into the dll because the debugger was not able to find the pdb(s).
Now, while the debugger is connected, if i open the Debug -> Windows -> Modules the ' Symbol Status' is 'Symbols loaded' for all my dlls.

**Comment by Petermarcu** [comment]
@gregg-miskelly is there a good place to track this issue? Any other thoughts?

**Comment by karelz** [comment]
@gregg-miskelly ping? Should we use VS Developer Community for these bugs? https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by gregg-miskelly** [comment]
Sorry for the delay.

A VS Developer community issue would be a more logical home than this repo, so that probably makes sense. Please post the issue link here.

By chance do you have a repo that is shareable?

**Comment by NJullienSweet** [comment]
Hello @pietrodicaprio 
Did you end up finding what was going on and a solution to fix it?

**Comment by pietrodicaprio** [comment]
> Hello @pietrodicaprio Did you end up finding what was going on and a solution to fix it?

Hi, no, I never found a solution. I honestly don't even remember if I then posted on the VS Dev Community, it was 5 years ago 😅
