### ISSUE TITLE
Getting NU1202  Package Microsoft.NETCore.App 2.0.9 is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/core#1929]
# Issue Title

When publishing project, I'm getting some NU1202  errors:
```
...\AutoMasshTik.Engine.csproj : error NU1202: Package Microsoft.NETCore.App 2.0.9 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.NETCore.App 2.0.9 supports: [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp (.NETCoreApp,Version=v0.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp2.0 (.NETCoreApp,Version=v2.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202: Package Microsoft.NETCore.App 2.0.9 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0) / win10-x86. Package Microsoft.NETCore.App 2.0.9 supports: [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp (.NETCoreApp,Version=v0.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp2.0 (.NETCoreApp,Version=v2.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
```

# General

The project in question is [AutoMasshTik](https://github.com/MihaMarkic/AutoMasshTik). 
I invoke something like 
`
 dotnet publish -o somepath\files  -r win10-x86 -c release /p:ShowLinkerSizeComparison=true
`
and get those errors.

`dotnet restore`
does not have issues and the project can be published/run just fine otherwise.

Note: you have to add latest ILLink.Tasks 0.1.5-preview-1841731 to AutoMasshTik.UI.csproj.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #19896](https://github.com/dotnet/coreclr/issues/19896) via [**ZenHub**](https://www.zenhub.com/)

**Comment by toryb** [comment]
I have a similar problem, only it shows up when attempting to add an assembly and its dependencies to the Runtime Package Store. The `dotnet store` command creates the error, but the solution can be successfully built and deployed without error.
>  error NU1202: Package Microsoft.NETCore.App 2.0.0 is not compatible with netstandard2.0

I have tried 2.1 & 2.2.
> error NU1202: Package Microsoft.NETCore.App 2.1.0 is not compatible with netstandard2.0

> error NU1202: Package Microsoft.NETCore.App 2.2.0 is not compatible with netstandard2.0

**Comment by karelz** [comment]
@toryb the issue has been moved ... check the replies above
