### ISSUE TITLE
String IndexOf method return different results on mac an windows

### ISSUE THREAD

**Issue by fujihara** [dotnet/core#193]
IndexOf method of string class is returning different results on macOs and Windows. 

This issue started after .NET Core release update. 

```
var str = "The quick brown fox jumps over the lazy dog\r\n";
if (str.IndexOf("\n") >= 0) {
    Console.WriteLine("OK");
}
else {
    Console.WriteLine("BAD");
}
```

On Windows machine it always print:
`OK`

On Mac it prints:
`BAD`

I fixed my code passing a char to IndexOf instead string:
``if (str.IndexOf('\n') >= 0) ``

But would be better if both platform to work consistently.

Thanks

**Comment by Petermarcu** [comment]
Thanks for reporting this issue. Do you mind filing it in the http://github.com/dotnet/coreclr repo? The code lives there: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L2378

**Comment by fujihara** [comment]
Sure, thanks for tip.

**Comment by sivasubramani222666** [comment]
> IndexOf method of string class is returning different results on macOs and Windows.
> 
> This issue started after .NET Core release update.

Hi Team,

Same kind of occur for the following code snippet. 

string str = "\0.\u0001.";           
Console.WriteLine("Value is "+str.IndexOf("\u0001")); 

On Windows machine and ASP.NET CORE platform it always print:
Value is 2.

On Mac it prints:
Value is 0.

Please check and provide me suggestion on this.

Thanks,
Sivasubramani.
