### ISSUE TITLE
.NET Core September Update - 2.1.4

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#1932]
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.4/2.1.4.md)
[Download 2.1.4](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.4/2.1.4-download.md)

Please report any issues you find with 2.1.4, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by SpaceShot** [comment]
Would this require an update to the lifecycle support document?   I didn't start a PR but have an update in my fork: https://github.com/SpaceShot/core/blob/patch-1/microsoft-support.md and I could open the PR.

**Comment by leecow** [comment]
Thanks, @SpaceShot! Yes, the 2.1 supported patch version in microsoft-support.md needs to be incremented. Release date remains unchanged as that marks the initial 2.1 release. Go ahead and submit a PR.

**Comment by tomaszzmudzinski** [comment]
I installed this sdk on my Mac and my .net core projects stops to build. First I was getting 

> /Users/tomaszzmudzinski/Documents/Projects/Spinner/Spinner/Spinner/Spinner.csproj: Error: NETSDK1061: The project was restored using Microsoft.AspNetCore.App version 2.1.4, but with current settings, version 2.1.1 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection. (Spinner)

I removed all .net core sdks from my laptop, and made clean install of newest .net sdk (.NET Core SDK 2.1.402). Now I am getting another error while trying to build project:

> /Users/tomaszzmudzinski/Documents/Projects/Spinner/Spinner/Spinner/Spinner.csproj: Error NU1605: Detected package downgrade: Microsoft.AspNetCore.App from 2.1.4 to 2.1.1. Reference the package directly from the project to select a different version.

**Comment by Petermarcu** [comment]
What version of ASP. NET are you referencing in your project?

**Comment by tomaszzmudzinski** [comment]
@Petermarcu I had this .net core SDK installed:

![41705668_538538003234128_6289081617524719616_n](https://user-images.githubusercontent.com/4519335/45556728-3e71e400-b83c-11e8-8dd3-e708e75dd0ec.png)

**Comment by Petermarcu** [comment]
In your project file, you should have a reference to MICROSOFT.ASPNETCORE.APP. What is the version?

**Comment by karelz** [comment]
Superseded by newer release 2.1.5 - see #1973
