### ISSUE TITLE
System.Security.Claims.ClaimTypes.Email value does not match the summary URI for the claim

### ISSUE THREAD

**Issue by mattchidley** [dotnet/core#1933]
# The value of the Email claim type does not match the URI for the claim, is this intentional?

# General

Current value:
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"

Should this be:
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/email"

The documentation below leads me to believe it should be the ladder:

https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes?view=netcore-2.1

//
// Summary:
//     The URI for a claim that specifies the email address of an entity, http://schemas.xmlsoap.org/ws/2005/05/identity/claims/email.
public const string Email = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress";

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32236](https://github.com/dotnet/corefx/issues/32236) via [**ZenHub**](https://www.zenhub.com/)
