### ISSUE TITLE
CSProj project format

### ISSUE THREAD

**Issue by lyptt** [dotnet/core#194]
Hi there. I read recently that .NET Core is moving to using the CSProj project format, but I can't seem to find a mention of that in any of the roadmaps / other .NET Core docs as it currently stands.

Is this still going ahead? Or can we rely on the project.json format to stick around?

**Comment by svick** [comment]
The [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) says that among features planned for 1.1 is:

> Transition to MSBuild and csproj as the default build system and project model for all versions of .NET.

**Comment by lyptt** [comment]
Ah cool, thanks for confirming!
