### ISSUE TITLE
The SSL connection could not be established on Ubuntu

### ISSUE THREAD

**Issue by vitaaaly** [dotnet/core#1941]
I have simple app that get request to website like this:

```csharp
            using (var httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync("https://www.microsoft.com");
                Console.WriteLine(response.StatusCode);
            }
```

This code work fine on Windows, but on Ubuntu 18.04 it crash with error:

`System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
`

This code work fine on Ubuntu only with websites that using http protocol.
Why it does not work with https?

dotnet --info:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by bartonjs** [comment]
There are two main possibilities.  One is you don't have any trusted roots installed.  The second is that you're seeing a problem that we've so far only seen on SLES15 and Fedora28 regarding the contents of the trusted roots store.

I can't reproduce the problem on Ubuntu 18.04, I just did an update/upgrade and manually invoked `sudo update-ca-certificates` just to see if it was a new(ish) package update, but can't reproduce it.

The simplest diagnostic test is to set two environment variables before running your program:

```sh
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/dev/null
```

If your program is successful after that, then this is the same as https://github.com/dotnet/corefx/issues/32224.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32300](https://github.com/dotnet/corefx/issues/32300) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vitaaaly** [comment]
@bartonjs when I set this environment variables, my program is successful.
Thank you!

**Comment by jasonsultana** [comment]
This worked for me too, hosting under CentOS on Webfaction.
