### ISSUE TITLE
Blocking error when trying to create instance of EventHubClient in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by allenh100** [dotnet/core#1943]
I am building a ASP.NET Core 2.1 MVC application and when I attempt to create an instance of the EventHubClient as follows:

```
EventHubClient client = EventHubClient.CreateFromConnectionString("connString", "hubName");
```

I receive the following exception:
```
$exception.Message = "The type initializer for 'Microsoft.ServiceBus.Messaging.Constants' threw an exception."

$exception.InnerException.Message = "Could not load type 'System.UriTemplate' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."
```

I have added references to the following packages as advised by numerous online posts but still continue to receive the above exception:
```
System.ServiceModel.Duplex
System.ServiceModel.Http
System.ServiceModel.NetTcp
System.ServiceModel.Primitives
System.ServiceModel.Security
```

Any advice/guidance on how to address this issue?

Thanks,
allen

**Comment by Petermarcu** [comment]
Are you targeting .NET Framework or .NET Core?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/wcf #3172](https://github.com/dotnet/wcf/issues/3172) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jitendriyag2** [comment]
I am having same issue while using Service Bus service

**Comment by jitendriyag2** [comment]
> I am having same issue while using Service Bus service in .net standard library

My Issue was fixed by replacing nuget package from Windows.Azure.ServiceBus (.Net FW) to Microsoft.Azure.ServiceBus(.Net Standard)
