### ISSUE TITLE
Enum.Parse() gives Cannot load assembly 'dll-name'

### ISSUE THREAD

**Issue by claudiobottari** [dotnet/core#1948]
# Issue Title

Enum.Parse() gives Cannot load assembly 'dll-name' when the enum type is defined in another dll

# General

Just porter from net462 to netcoreapp2.1, everything works smoothly but I got this error on a tiny portion of my code which is crucial: Enum.Parse() gives Cannot load assembly 'dll-name' when trying to instanciate from a different dll (which is part of the project, and everything else works... I an load Assembly, crete objects and so on).

Some examples:

if (parameterNestedClass.IsEnum)
{
    var enumNames = parameterNestedClass.UnderlyingSystemType.GetEnumNames(); // this works
    var enumValues = parameterNestedClass.UnderlyingSystemType.GetEnumValues(); // this doesn't, says "internal c# error"
}

Any ideas?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32349](https://github.com/dotnet/corefx/issues/32349) via [**ZenHub**](https://www.zenhub.com/)
