### ISSUE TITLE
Average with linq on big collection

### ISSUE THREAD

**Issue by bdhamelicodra** [dotnet/core#1951]
On a big array, the method "System.Linq.Enumerable.Average(this IEnumerable<long> source)" (in .Net Core 2.1) throw the exception "OverflowException: Arithmetic operation resulted in an overflow.".
Why not use an algorithm that can prevent this, like :
```
double Average(this IEnumerable<long> source) {
double avg = 0;
int t = 1;
foreach (long x in source) {
avg += (((double)x) - avg) / ((double)t);
t += 1;
}
return avg;
}
```​

**Comment by MarcoRossignoli** [comment]
better move to https://github.com/dotnet/corefx/issues where https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Average.cs#L77 lives

**Comment by Megact** [comment]
use static keyword

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32414](https://github.com/dotnet/corefx/issues/32414) via [**ZenHub**](https://www.zenhub.com/)
