### ISSUE TITLE
Cross-platform replacement for SoundPlayer for playing audio across devices/paltforms

### ISSUE THREAD

**Issue by jjgriff93** [dotnet/core#1952]
Cannot play sound files as part of .net core console apps in windows and running on windows IoT Core on Raspberry Pi due to lack of audio support. Third party libraries don't offer any simple solution for playing wav or mp3 streams like the .NET Framework SoundPlayer does.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #32413](https://github.com/dotnet/corefx/issues/32413) via [**ZenHub**](https://www.zenhub.com/)
