### ISSUE TITLE
Running .NET Core app with Nuget dependency on Raspbian.

### ISSUE THREAD

**Issue by Venzz** [dotnet/core#1957]
# Running .NET Core app with Nuget dependency

I've published an app in Windows and i'm trying to run the result on Raspberry Pi.

# General

The app contains one dependency from Nuget. There are no trails of it in \PublishOutput after publishing. I assume in Windows it takes dependencies from C:\Users\...\.nuget\packages
But what about Linux? I was putting dependency manually in the same directory with the app, in the \lib\netcoreapp2.0\
I installed nuget and used nuget install. Any attempts leads to the fact that it can't find library.

```
Error:
  An assembly specified in the application dependencies manifest (main.deps.json) was not found:
    package: 'LibVenzTest1', version: '1.0.0'
    path: 'lib/netcoreapp2.0/Lib.dll'
```

Even though dotnet command works, dotnet --version gives me:
```
venz@raspberrypi:~ $ dotnet --version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by Petermarcu** [comment]
You need to publish the application. If you just build, it wont create a complete application for you, it saves time by just loading things from where they are instead of getting them into your app. 

You likely need to run `dotnet publish -r linux-x64 --self-contained=false` and copy that folder to linux instead.

Note, you should probably get on .NET Core 2.1. 2.0 is out of support very soon.

**Comment by Petermarcu** [comment]
Note that you can leave off the `--self-contained=false` if you want to deploy the whole runtime with your app.

**Comment by Venzz** [comment]
As i see, the output is the same is if it was done via Visual Studio 2017 menu. And it doesn't work or throws System.BadImageFormatException.

**Comment by Petermarcu** [comment]
Are you publishing for Linux? How are you copying the files over to Linux?

**Comment by Petermarcu** [comment]
The high level summary is that a properly published application will not depend on the NuGet or any assets from the nuget folder. If it is loading from there, its not a published application. Are you running using `dotnet run`?

**Comment by Venzz** [comment]
> Are you publishing for Linux? How are you copying the files over to Linux?
Yes, for Linux, for Raspbian GNU/Linux 9.1 (stretch) specifically, at lease the idea is to do that. I copy files using OneDrive + Browser, the whole \netcoreapp2.0\target\ folder which in my case contains:
```
publish\Lib.dll (that is Nuget lib)
publish\Main.deps.json
publish\Main.dll (this is my "executable")
publish\Main.pdb
publish\Main.runtimeconfig.json
Main.deps.json
Main.dll
Main.pdb
Main.runtimeconfig.dev.json
Main.runtimeconfig.json
```
Is it a properly publushed app?

> Are you running using dotnet run?
No, i use `dotnet Main.dll`

**Comment by Petermarcu** [comment]
Are you running 'dotnet Main.dll' on the contents of the publish folder? You should only need what's in the publish folder that is output after you run the publish command.

**Comment by Venzz** [comment]
Yes. On the contents of publish i receive System.BadImageFormatException which AFAIK means that there is an target platform mismatch.

**Comment by Venzz** [comment]
Solved it.
To publish from Windows to Raspberry we need to use
`dotnet publish -r **linux-arm** --self-contained=false`
As i understand it is not possible to do with Visual Studio.

**Comment by Petermarcu** [comment]
Glad you have it working now! :)
