### ISSUE TITLE
Can't target framework 2.1.3 after being upgraded to 2.1.4

### ISSUE THREAD

**Issue by dennyChandler** [dotnet/core#1958]
I started developing a new website prior to .net core framework 2.1.4 was released, we got our production environment all set up with "Coming Soon" pages, etc.

As this server hosts other sites, we do not want to restart for an upgrade to 2.1.4, so I updated the csproj file with

    <RuntimeFrameworkVersion>2.1.3</RuntimeFrameworkVersion>

I also checked the NuGet packages for Microsoft.NETCore.App and it is set to 2.1.3

I even went so far as to uninstall Microsoft .NET Core Runtime 2.1.402 from my dev machine

Yet, when I publish the site and copy it to the folder on the host, it still logs

> It was not possible to find any compatible framework version The specified framework 'Microsoft.NETCore.App', version '2.1.4' was not found. 
> - Check application dependencies and target a framework version installed at: "PATH" 
> - Installing .NET Core prerequisites might help resolve this problem: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409 
> - The .NET Core framework and SDK can be installed from: https://aka.ms/dotnet-download 
> - The following versions are installed: 
> 1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 
> 1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 
> 2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 
> 2.1.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

I'm not sure if this is the right place to report this, but I am out of options at this point... So sorry if I'm at the wrong place.

**Comment by Petermarcu** [comment]
/cc @livarcocc @dsplaisted 

It sounds like 2.1.4 is getting burned into your deps file. Can you search for it in there in your published application? Published applications that run on the shared framework are supposed to specify 2.0.0 as the min version. I wonder if this is a regression in the tooling due to recent changes to try to keep more people up to date by default.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #10037](https://github.com/dotnet/cli/issues/10037) via [**ZenHub**](https://www.zenhub.com/)
