### ISSUE TITLE
Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer Warning

### ISSUE THREAD

**Issue by pgmolloy** [dotnet/core#1965]
Just started getting a build warning after updating Visual Studio. Can this be disabled as it doesn't seem to affect anything that I can tell, app builds, deploys and runs in Azure without a problem so not sure why this is a warning except maybe for that package developer. CSC : warning AD0001: Analyzer 'Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

I am not using the RawSqlStringInjectionDiagnosticAnalyzer but it may be a dependency so without feedback I am hesitant to do anything besides leave the warning display annoyingly 30 times every build.
Cheers Peter

**Comment by karelz** [comment]
This issue was moved to aspnet/EntityFrameworkCore#13474
