### ISSUE TITLE
IEnumerable<IFormFile> is not correctly binding

### ISSUE THREAD

**Issue by ranouf** [dotnet/core#1967]
Hi,

I have an Issue when I try to upload Files from my Angular 6 app to .net core web api.

Here is my C# classes:
   ```
 public class SampleDetailsDto 
    {
        public Guid Id{ get; set; }
        [Required]
        public string Text { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<IFormFile> Files { get; set; }
        public IList<SampleItemDto> SampleItems { get; set; }
    }
    public class SampleItemDto : EntityDto<Guid?>, IAuditedDto, IDeleteAuditedDto
    {
        public Guid Id{ get; set; }
        [Required]
        public string Text { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<IFormFile> Files { get; set; }
    }
```

My C# Controller:

```
        [Route("{id:guid}")]
        public async Task<IActionResult> UpdateAsync([FromRoute]Guid id, [FromForm] SampleDetailsDto dto)
        {
              Console.Write(dto.Files?.Length); // return null
              return OK();
       }

```
![image](https://user-images.githubusercontent.com/1764519/46158581-29d61880-c24c-11e8-828c-a7b16dbb3ebb.png)
As you can see Files are null.

But if I look in the request:
![image](https://user-images.githubusercontent.com/1764519/46158648-512ce580-c24c-11e8-942d-3651f96fd02b.png)

With more details:
![image](https://user-images.githubusercontent.com/1764519/46158699-6c97f080-c24c-11e8-877d-92000dbbcc5e.png)

As we can see the Files are correctly sent to the server, in the name we can see that there are supposed to be correctly bind to the DTO which is not the case.

I read here: https://github.com/aspnet/Mvc/issues/7719 that It s recommended to use IFormCollection, so yes, I can see all the Files uploaded, but they are all in one property called "Files" instead of being linked to SampleDetailsDto or ChildSampleDto.

Did you notice this bug too? Did you find a way to patch it?

**Comment by alsami** [comment]
Hi,

this should work just fine. I have create a small sample with a static file [here](https://github.com/alsami/multifile-upload-withprops-aspnet-core).

**Comment by ranouf** [comment]
Hi,

Thank for your help and to have taken the time to do a repository.
In your example, you test with a list of files. In my situation, I have a more complex object (maybe there is a difference?), a parent containing and a list of children who both can have a name and a list of files.
I did a repository, so you will be able to test the problem:
https://github.com/ranouf/TestMultipleUpload

Let me know if you have questions :)

**Comment by alsami** [comment]
Indeed, does not work, even with nested formdata. I updated the sample. It works fine with normal nested properties, not for the files though.

**Comment by ranouf** [comment]
Thanks @alsami, I created a new issue on  [MVC Repository](https://github.com/aspnet/Mvc/issues).

**Comment by ranouf** [comment]
An issue has been found:
https://github.com/aspnet/Mvc/issues/8527#issuecomment-425978956
