### ISSUE TITLE
Proposal: Release API references 

### ISSUE THREAD

**Issue by leecow** [dotnet/core#197]
@richlander @bleroy @terrajobst @ericstj 

Github is unable to render larger files and the complete .NET Core 1.0.0 set is beyond the current limit. This is a proposal to add the following to the [Release Notes content structure](https://github.com/dotnet/core/tree/master/release-notes/1.0). 

```
1.0.0-api.md
1.0.0-api/
    - 1.0.0-api_<namespace>
    - ...
```

This will provide a clean entry point with links to API details. The 1.0.0 api directory would contain individual files representing each namespace. 103 files in all.

**Comment by Petermarcu** [comment]
@leecow , is this still actionable and the direction you want to go?

**Comment by leecow** [comment]
@Petermarcu , I've already implemented the proposed structure so closing the issue.
