### ISSUE TITLE
.NET Core October Update - 2.1.5

### ISSUE THREAD

**Issue by leecow** [dotnet/core#1973]
.NET Core October Update - 2.1.5

[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.5/2.1.5.md)
[Download 2.1.5](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.5/2.1.5-download.md)

Please report any issues you find with 2.1.5, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by mkleijn** [comment]
Hi, it seems the download urls in [releases.json](https://github.com/dotnet/core/blob/master/release-notes/releases.json) now uses absolute URL's instead of relative paths to the base url _blob-sdk_   
This brakes the [.NET Core VSTS task](https://go.microsoft.com/fwlink/?linkid=853651) from installing sdk 2.1.403 on my build agent

Is this change intentional? In that case I probably should raise an issue in the VSTS Tasks GitHub

**Comment by leecow** [comment]
@mkleijn - yes, this is intentional. We have changed our publishing CDN  and they do not have a stable "container" portion of the resulting URL. Without this, it would be extremely unpleasant to construct URLs in the current json file. Apologies for the breaking change.

**Comment by bishal-pdMSFT** [comment]
@leecow this is breaking the Azure pipelines(formerly VSTS) task. What is the long term approach here as want to make sure that the task work well over the time?
Are blob urls not longer going to be there? Will each location directly point to full dlc url? Are you going to change this behavior for older versions as well? There seems to be no set pattern.

**Comment by bishal-pdMSFT** [comment]
Created a new issue #1977 as the current one is an "announcement".

**Comment by asheeshv** [comment]
I'm currently on .Net Core 2.0, and trying to upgrade to v2.1. I'm following this [https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1](2.0 to 2.1). However, my .Net Core app uses the target framework as .Net4.7 using .Net core references to 2.0. With the 2.1.5 release, should I update these references to v2.1.5, or just update these to use 2.1. Would it be of any significant difference of going in with 2.1.0 over 2.1.5? Thanks!

**Comment by karelz** [comment]
Superseded by newer release 2.1.6 - see #2053
