### ISSUE TITLE
ASP.NET Core runtime binaries for non-admin ? 

### ISSUE THREAD

**Issue by ststeiger** [dotnet/core#1979]
Question regarding the downloads of .NET SDKS: 

I want to download the .NET Core 2.2. Preview 2. 
But on my dev-machine I don't have admin rights. 

So I downloaded the runtime-binaries and the sdk-binaries from 
https://github.com/dotnet/core/blob/master/release-notes/2.2/preview/2.2.0-preview2.md

Unpacked to a directory in user-dir, and then I overwrote the path environment variable in cmd, and started visual studio from the command line. 
Seems to work. 

Now the download | ASP.NET Core Runtime | does not have binaries, it only has an installer, which requires admin rights. 

Why is there no zip-file for the ASP.NET Core runtime ? 
Or is |  ASP.NET Core runtime | the same as | Runtime Binaries | ? 
Or is this not required at all, and will it just download that from nuget ? 
Or is that some sort of IIS integration that I don't require with IIS express, as hosting-bundle would imply ?

**Comment by karelz** [comment]
@leecow @Eilon do you know where to route this problem?

**Comment by karelz** [comment]
Thanks @natemcmaster.
Closing as it seems to be answered.
