### ISSUE TITLE
Feature request: OS-specific "long" integer (for p/invoke)

### ISSUE THREAD

**Issue by jherby2k** [dotnet/core#1980]
# Issue Title

There is no integer type that behaves like a C "long" across different OSes. As in, is 4 bytes on Windows but 8 bytes of OSX/Linux.

# General

I have a cross-platform .net core library that does a lot of p/invoke. Some of the structs (and functions) use native longs in the signature, which are 4 bytes on Windows but 8 bytes on OSX/Linux. Right now I have multiple configurations and a lot of preprocessor blocks to deal with this. I don't think this a unique situation.

I can see two possible solutions:

1) A "nativelong" type that compiles to an int on Windows and a long on OSX/Linux. Probably good to have a "nativeulong" as well.
2) Something like a MarshalAs(UnmanagedType.nativelong) attribute you can apply to "long" parameters and struct fields.

**Comment by karelz** [comment]
You can use `System.IntPtr` (it's a bit limited, but ok - see https://github.com/dotnet/corefx/issues/20256 for further planned improvements)
 There is also proposal for native-sized number types in https://github.com/dotnet/csharplang/issues/435.

**Comment by jherby2k** [comment]
Sorry, IntPtr accomplishes something different from what i'm describing. This has nothing to do with word length.

Type | Windows 32-bit | Windows 64-bit | *nix 32-bit | *nix 64-bit
--- | --- | --- | --- | ---
IntPtr | 4 | 8 | 4 | 8
int | 4 | 4 | 4 | 4
long | 8 | 8 | 8 | 8
_native_ long | 4 | 4 | 8 | 8

**Comment by jherby2k** [comment]
maybe "c long" is a better name for it than "native long".

**Comment by karelz** [comment]
I was not aware that Linux and Windows differ in C/C++ `long` size - https://stackoverflow.com/a/384672/4100992
I would definitely not use "native int/long" as name - that is IMO mostly associated with 32-bit vs. 64-bit.

Even the table above is a bit confusing ... what is "int (Int32)" and "long (Int64)"? Are those meant to be C# types? ... Can you clarify that first please to avoid further confusion? Is this what you meant?

Type | Windows 32-bit | Windows 64-bit | *nix 32-bit | *nix 64-bit
--- | --- | --- | --- | ---
C#: `System.IntPtr` | 4 | 8 | 4 | 8
C#: `int` (`System.Int32`) | 4 | 4 | 4 | 4
C#: `long` (`System.Int64`) | 8 | 8 | 8 | 8
C: `long` (no C# equivalent) | 4 | 4 | 8 | 8

It sounds like a reasonable topic for discussion on new API in interop space. Can you please file an issue in CoreFX repo? (ideally with clarified table to avoid further confusions)

**Comment by jherby2k** [comment]
you are correct, and updated as suggested. Will do so.

**Comment by karelz** [comment]
I just copied the table from @jherby2k :) - looks like he fixed it in the CoreFX issue. I will update it even here just to avoid further confusion.
