### ISSUE TITLE
Task in Tasks array get executed before Task.WhenAll() is procesed

### ISSUE THREAD

**Issue by teleprom** [dotnet/core#1985]
Hi guys, i'm doing a task in my project where i need to send multiple http request at the same time, then wait for all responses and do some work on that.

The problem is, when i´m doing this array of tasks, some tasks in random order get executed before i call Task.WhenAll(), and i don't know why, i'm using httpclient async method to do the call and i try with RestSharp and i get the same behavior.

For me knowledge this is not the expected behavior, maybe i'm wrong.

I attach a solution with an example.

[AsyncTask.zip](https://github.com/dotnet/core/files/2452065/AsyncTask.zip)

Hope u can help me!

Thanks!

**Comment by karelz** [comment]
This is expected behavior - tasks can finish before you get chance to call `Task.WhenAll`. If you don't want that, then you need to pause the tasks until you are ready to start them (e.g. via semaphore).
