### ISSUE TITLE
Can't consume local netstandard2.0 NuGet package built with .NET Core 2.1 SDK

### ISSUE THREAD

**Issue by ryakstis** [dotnet/core#1993]
# Can't consume local netstandard2.0 NuGet package built with .NET Core 2.1 SDK

## Environment
* Windows 10 Enterprise
* Visual Studio 2017 Professional 15.8.6
* .NET Core SDK 2.1.402
* NuGet 4.6.0

I created a .NET Standard Class Library, checked `Generate NuGet package on build` with the Target framework set to `.NET Standard 2.0`, then put it in my local NuGet package directory.

I then created a second .NET Standard Class Library, and attempted to install the above library from the `Manage NuGet Packages...` command.  I receive the following error:

```
Package is not compatible with netstandard2.0 (.NETStandard, Version=v2.0). Package supports: netcoreapp2.1 (.NETCoreApp, Version=v2.1).
```

I would attempt to see if using the .NET Core SDK 2.0 works, but I don't have it installed and #1992 has stopped me from continuing anyway.

Have I packaged my first library incorrectly, misunderstood what can consume .NET Standard assemblies, or is this a problem with the .NET Core SDK/Runtime 2.1?

**Comment by ryakstis** [comment]
Just removed all SDK versions above 2.1.202 (the last 2.0 SDK listed) and runtimes above 2.0.9, downloaded and installed the .NET Core Runtime 2.0.9, and it made no difference and, weirdly enough, gives the same error about supporting `netcoreapp2.1` only.

This points to a misconfiguration on my behalf, so what have I done incorrectly? Do I need to do something else other than marking the `Target framework` as `.NET Standard 2.0` and checking `Generate UnGet package on build` in Visual Studio 2017? Also, how can it support `netcoreapp2.1` when I don't even have that installed to package it that way?

**Comment by ryakstis** [comment]
Recreating the project structure using `dotnet new sln`, `dotnet new classlib -f netstandard2.0` and the like allows building and consuming the intended `netstandard2.0` assembly, so something in the way I used Visual Studio 2017 to set up .NET Standard 2.0 projects must have gone wrong.

If this helps isolate a bug in VS2017, cool.  Otherwise, I have a workaround, so let's close this.

**Comment by karelz** [comment]
Are you able to reproduce it with latest VS? If yes, it would be great to submit bug report via Send Feedback from within VS with the steps (or via https://developercommunity.visualstudio.com).
Closing here per suggestion above.
