### ISSUE TITLE
On the website write dates as yyyy-mm-dd

### ISSUE THREAD

**Issue by ffes** [dotnet/core#1999]
Not use if this is the right repo. Probably not, but I couldn't find any repository that contains the .Net Core download page.

Not being from the US, I always have difficulties with the date notation that is used on the .Net Core download pages like https://www.microsoft.com/net/download/dotnet-core/2.1

At the moment of writing the latest version is from `10/2/2018`. I always read that as 10th of February. At first think that is old, and then get that it is the US notation, so it means 2th of October.

So please use the ISO notation of `yyyy-mm-dd`, in this case obviously `2018-10-02`. I don't think anybody will misunderstand that notation.

**Comment by karelz** [comment]
Sounds like reasonable request. @leecow @vivmishra can you please help route it?

**Comment by vivmishra** [comment]
@rowanmiller

**Comment by rowanmiller** [comment]
Change is live. @ffes many thanks for suggesting this 👍 

![image](https://user-images.githubusercontent.com/4741851/46969752-ec56f500-d06b-11e8-9128-3efad3c9c61a.png)
