### ISSUE TITLE
Make use of Code Contracts where ever applicable

### ISSUE THREAD

**Issue by ReverseBlade** [dotnet/core#2]
I wonder the reason why while the code contracts are part of BCL and it is a research project of Microsoft, only some of the API makes use of it. This this is effectively preventing making use of code contracts for the end consumers as well. 
I would appreciate at least if you can make use of Code Contracts on the public surface API.

**Comment by MattWhilden** [comment]
@ReverseBlade you'll get a better answer from folks over at dotnet/corefx. I'll close this out and presume you'll follow up there.
