### ISSUE TITLE
Could we still use wsdl command to generate proxy class to call soap ?

### ISSUE THREAD

**Issue by jeff881208** [dotnet/core#200]
Hi ,
In .net Framework ,we can use wsdl command to generate proxy class to call soap .
Now Could we still use wsdl command to generate proxy class to call soap in .net Core ?

Thanks

Jeff Du

**Comment by jeff881208** [comment]
No one answer this issue . So sad ? Do you have  some plan about this ?

Thanks
Jeff Du

**Comment by jeff881208** [comment]
No one answer this issue . So sad . Do you have some plan about this ?

Thanks
Jeff Du

**Comment by blackdwarf** [comment]
@jeff881208 `wsdl.exe` will create classes that are not compatible with .NET Core, so I guess the answer to your question would be "no". However, you may want to take a look at https://blogs.msdn.microsoft.com/webdev/2016/05/25/announcing-wcf-connected-service-for-net-core-rc2-and-asp-net-core-rc2/. This could be something that could help you in this case.

**Comment by Gvo87** [comment]
maybe this will help
http://tattoocoder.com/asp-net-core-getting-clean-with-soap/

**Comment by da5407** [comment]
reference this document

https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x
