### ISSUE TITLE
Dependency scaffolder error when adding controllers

### ISSUE THREAD

**Issue by adriaandavel** [dotnet/core#2005]
# Issue Title

Dependency scaffolder error when adding a controller

# General

I just loaded preview 3 hoping it would solve this error but it does not. I created a WebAPI project, and deleted the default values controller. When I try to add a new controller I get an error with message "Dependency scaffolder support the project runtime version". Google has not given me any usable alternatives

**Comment by karelz** [comment]
Is that an error from Visual Studio? If yes, then I would recommend to report it via VS Feedback (Send Feedback icon in VS or https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by adriaandavel** [comment]
Apologies for the omission, my VS version is 15.3.2. Is this a VS bug or a ASP.Net Core 2.2 project template issue?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#917
