### ISSUE TITLE
release build possibly with optimization

### ISSUE THREAD

**Issue by fansgit** [dotnet/core#201]
`dotnet 1.0.0-preview2-003121` on Linux

```
$ dotnet new
$ dotnet restore
$ dotnet build

$ tree -d

bin
   debug
...
```

Will `dotnet build` produce release build possibly with optimization in the future?

**Comment by svick** [comment]
If you run `dotnet help build`, you'll notice that it has a parameter that specifies configuration. You can use the default configuration called `release` to enable optimizations: `dotnet build -c release`.

**Comment by fansgit** [comment]
I did but below was too concise to grasp. Thanks anyway for your info.

`  -c|--configuration <CONFIGURATION>  Configuration under which to build`
