### ISSUE TITLE
.NET core 2.1.1 - System.DllNotFoundException with CoolProp Shared Library on Ubuntu 18.04

### ISSUE THREAD

**Issue by EduBic** [dotnet/core#2015]
I have a .NET project written in C# that has a dependency with the CoolProp library (available here https://github.com/CoolProp/CoolProp). It calls the CoolProp functions using PInvoke.

Unluckily I have to run this program in a linux environment (precisely the AWS lambda env https://docs.aws.amazon.com/en_us/lambda/latest/dg/current-supported-versions.html).

For now, I want to execute it with .NET core (command `dotnet run`) on my PC with Ubuntu 18.04 OS but I get always the following error:

```
Unhandled Exception: System.DllNotFoundException: 
Unable to load shared library 'libCoolProp.so' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibCoolProp.so.so: cannot open shared object file: No such file or directory
   at Test1.Program.PropsSI(String Output, String Name1, Double Prop1, String Name2, Double Prop2, String Ref)
   at Test1.Program.Main(String[] args) in /home/user/Desktop/TestDllInUbuntu/Test1/Program.cs:line 23
```

The test program (C#) is:

```C#
using System; 
using System.Runtime.InteropServices;

namespace Test
{ 
    class Program 
    { 
        [DllImport("libCoolProp.so")] 
        private static extern double PropsSI(string Output, string Name1, double Prop1, string Name2, double Prop2, string Ref); 

        static void Main(string[] args) 
        {
            double propsRes = PropsSI("H", "T", 300.0, "Q", 0.0, "R410A"); 
            Console.WriteLine(propsRes); 
        } 
    } 
}
```

The Program.cs is in the same folder of libCoolProp.so.

Notes:
- The same program on Windows 10 compiled and executed with .Net Core 2.1 and its libCoolProp.dll works.
- The same program on **Ubuntu 18** compiled and executed with **Mono Runtime 5.16.0** works.

What could be the causes? Any suggestions?

**Comment by karelz** [comment]
Is the libCoolProp deployed next to the executable from where you execute the app?

cc @janvorli @wfurt

**Comment by karelz** [comment]
Does it create 'build' directory on Windows as well?
The DLL must be next to it - so either your project somehow marks it as dependency (IMO likely), or due to some magic it ends up in the right place.

As it seems to be answered, closing.

**Comment by EduBic** [comment]
Yes! If I change the path in `[DllImport("path")]` to `"../../../libCoolProp.so"` the program executed with `dotnet run` works.

Thank you karelz.


In **Windows** the build process is the same, `dotnet run` create two folders `bin` and `obj` but the lib.dll file is not inside those directories.
How .NET core in Windows 10 automatically finds the path of CoolProp.dll remains unknown.

**Comment by karelz** [comment]
@EduBic I find it fairly suspicious that Windows would load DLL from another directory on its own, unless it is part of WinSxS cache - i.e. installed globally.
Can you check under debugger where the DLL is loaded from?

**Comment by EduBic** [comment]
I don't know how to debug it using only the console.
After the creation of a console project I run the following commands:
`dotnet publish`
`dotnet run`

I noticed that in Visual Studio 2017 the program doesn't run, it crashes with DllNotFoundException. I have to set `Copy to Output Directory` to **Copy Always** for the `CoolProp.dll` file. In this case the file .dll is copied inside the `bin/debug/netcoreapp2.1` directory and the program works.

Does vs2017 build using .NET core?

**Comment by karelz** [comment]
You can attach debugger (VS or windbg) to running process, or use other tools (like ProcessExplorer) to see loaded DLLs into a process.
Or you can launch the command line under a ddbugger.

**Comment by EduBic** [comment]
I tried with ProcessExplorer and the `CoolProp.dll` is correctly loaded from the project directory (`CoolProp-dotnet-core`).

![immagine](https://user-images.githubusercontent.com/13170564/47584146-aea27800-d959-11e8-962f-ad6b9534356b.png)

**Comment by karelz** [comment]
Was it maybe the current folder at the time dotnet was invoked? That would make some sense ...

**Comment by EduBic** [comment]
Yes, if I run the command `dotnet run --project .\CoolProp-dotnet-core\` from the parent directory I got the `DllNotFoundException`. 

So in _Windows 10_ the dynamic linker search the lib also in the path where `dotnet run` is called, this is **not** done in _Ubuntu 18_.

**Comment by karelz** [comment]
Sounds like that. And that would be OS difference, not something .NET has impact on.

**Comment by daniliammo** [comment]
> Похоже на то. И это будет разница в ОС, а не то, на что влияет .NET.

found a solution to the problem?
