### ISSUE TITLE
.Net core 2.2 web app gives an error 503 when run on an azure web app service

### ISSUE THREAD

**Issue by jobou363** [dotnet/core#2016]
# Issue Title
.Net core 2.2 web app gives an unclear error 503 when we access the site in the azure web app

# General
I created a web app in azure to host my new .net app.

I created a new project ASP.NET Core Web Application by selecting a web application MVC from the template in visual studio preview (15.9.0) and i have selected .net core ASP.NET Core 2.2 ( SDK 2.2.100-preview3-009430). When I run the project locally, everything is fine. When I deploy the project build as win-x64 as a web app service on azure, the web site give this server error : 
> Service Unavailable HTTP Error 503. The service is unavailable.

I have followed the documentation to install the extension x64 .net core preview needed to run .net core preview version in azure. I saw in the message that the .NET Extensibility Feature is not installed but it is.

Then I realize that the platform 64 bits is not supported in the free basic plan.

I have than change the plan to a higher plan and after changing in the Azure Web App the application settings platform from 32 bits to 64 bit.

I think it would better to have more detail that indicates that process fail because we run a 64 bit apps in an 32 bit web process. I activated every app logs and the sdtout but I couldn't find more details about the error.

# DotNet environement :
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100-preview3-009430
 Commit:    e0a11c9929

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100-preview3-009430\

Host (useful for support):
  Version: 2.2.0-preview3-27014-02
  Commit:  525082ca3e

.NET Core SDKs installed:

>  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
>   2.1.101 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.400 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.403 [C:\Program Files\dotnet\sdk]
>   2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
>   2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by karelz** [comment]
@jobou363 just to clarify I understand your suggestion:
You would like to see a clear error when you deploy into Azure Web App a 64-bit app when only 32-bit apps are supported by the Azure Web App. Is that correct summary?

**Comment by jobou363** [comment]
@karelz Yes.

**Comment by karelz** [comment]
That sounds like a reasonable enhancement. Not sure if it is part of VS tooling, or Azure Web App service itsself - @Eilon do you know where to route it?

**Comment by Eilon** [comment]
@vijayrkn - should we move this bug to the https://github.com/aspnet/websdk repo? Or is there a better home for it?

**Comment by vijayrkn** [comment]
This is a VS request. The right place for this feature request would be https://developercommunity.visualstudio.com/spaces/8/index.html.

From VS -> Help -> Send Feedback -> Provide a Suggestion.
