### ISSUE TITLE
Crypto DllNotFoundException on OSX v. 1.0.0-preview2

### ISSUE THREAD

**Issue by AlyssaDaemon** [dotnet/core#202]
I am running OS X El Capitan, I installed dotnet from the installer (as well as the latest openssl via homebrew). However, it seems I am missing the DLL for the Crypto package. Could this be tied to having the mono runtime installed? (I've already linked openssl libs with brew)

```
$ dotnet new

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
[1]    91638 abort      dotnet new
$ dotnet --version
1.0.0-preview2-003121
$ openssl version
OpenSSL 1.0.2h  3 May 2016
$ mono --version
Mono JIT compiler version 4.4.0 (tarball Wed Jun 15 18:28:03 BST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen
$ find /Library/Frameworks/Mono.framework/Versions/Current -iname ".*crypto.*" -print
$
```

**Comment by bartonjs** [comment]
@AlyssaDaemon Did you do `brew link --force openssl`?  In particular, you're looking for /usr/local/lib/libcrypto.1.0.0.dylib.  (See https://github.com/dotnet/core/issues/173#issuecomment-229130612)

**Comment by AlyssaDaemon** [comment]
As I said in the beginning, **yes, I did do** `brew link --force openssl` before trying this. /usr/local/lib/libcrypto.1.0.0.dylib *does* exist on my system. 
```
$ ls /usr/local/lib/libcrypto.1.0.0.dylib
/usr/local/lib/libcrypto.1.0.0.dylib
```

**Comment by bartonjs** [comment]
@AlyssaDaemon Sorry, just had to check; sort of like the IT question "have you tried turning it off and on again?".

I can't think of any reason why the presence of Mono would affect loading that library.  It needs

* libcrypto.1.0.0.dylib, from rpath
* libssl.1.0.0.dylib, from rpath
* /usr/lib/libc++.1.dylib
* /usr/lib/libSystem.B.dylib

The first two dependencies should be met by brew install/link of the OpenSSL package.  The second two should just be there on the Mac.

The library asserts that in addition to the standard rpath it includes loader_path; so it will first try the directory the library itself is in before falling back to system probing.

While the default probing path is $HOME/lib;/usr/local/lib;/usr/lib, it can be altered by some environment variables.  See https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html#//apple_ref/doc/uid/TP40001928-SW21 for more information.

The only things that I can think of at this point are:
* Check that the /usr/local/lib symlinks are valid
* Check that you don't have any of the rpath-changing environment variables defined (or, that if you do, you try unsetting them to diagnose the problem)

You're the first person who has reported that `brew link --force openssl` didn't fix everything for them, so I'm at a bit of a loss, advicewise.

**Comment by AlyssaDaemon** [comment]
Sorry that I came off a bit cross, thank you for helping me. I have been thinking about reinstalling El Capitan anyway, so perhaps that might fix things. I checked my symlinks, and my environment variables and they seemingly checkout (well $DYLD_FALLBACK_LIBRARY_PATH was defined and had mono's libs defined, but even unsetting it didn't help). See you on the other side as it were.

```
$ ls -l /usr/local/lib/libssl.1.0.0.dylib
lrwxr-xr-x  1 alyssadaemon staff  49 Jul  3 09:40 /usr/local/lib/libssl.1.0.0.dylib -> ../Cellar/openssl/1.0.2h_1/lib/libssl.1.0.0.dylib
$ ls -l /usr/local/lib/libcrypto.1.0.0.dylib
lrwxr-xr-x  1 alyssadaemon  staff  52 Jul  3 09:40 /usr/local/lib/libcrypto.1.0.0.dylib -> ../Cellar/openssl/1.0.2h_1/lib/libcrypto.1.0.0.dylib
$ ls /usr/local/Cellar/openssl/1.0.2h_1/lib/
engines               libcrypto.1.0.0.dylib libcrypto.a           libcrypto.dylib       libssl.1.0.0.dylib    libssl.a              libssl.dylib          pkgconfig
$ echo $LD_LIBRARY_PATH

$ echo $DYLD_LIBRARY_PATH

$ echo $DYLD_FALLBACK_LIBRARY_PATH
/Library/Frameworks/Mono.framework/Versions/Current/lib:/Users/alyssadaemon/lib:/usr/local/lib:/usr/lib
$ unset DYLD_FALLBACK_LIBRARY_PATH; dotnet new

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by AlyssaDaemon** [comment]
I am sorry, I forgot to report what happened. Indeed reinstalling OS X fixed the issue. Sorry to trouble you all.
