### ISSUE TITLE
Using System.Net.Sockets on Linux

### ISSUE THREAD

**Issue by florianislitzer** [dotnet/core#2020]
I develop an application which uses a .Net Framework v4.6.1-compiled library to connect to a payment terminal over udp sockets. If I debug or publish it on Windows everything works fine, when publishing to Linux and running it as root I get the following error:

> System.Net.Sockets.SocketException (13): Permission denied
>    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
>    at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)

I tried to change firewall settings, checked the Linux kernel security settings, changed the file permissons, but everthing without success.
Is there something special to keep in mind for running the application on Linux?
Thanks

**Comment by wfurt** [comment]
run the app under ```strace -f -s 20 -e trace=%network dotnet foo.dll```
That will show you what is happening. 
Note that you need root privilege to use ports bellow 1024. 
Check if you have SELinux enabled in enforcing mode. 
If so, policy there may need to be adjusted.

**Comment by florianislitzer** [comment]
Using strace i found the following error:


> [pid  3998] bind(254, {sa_family=AF_INET, sin_port=htons(33335), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)
> [pid  3998] socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP) = 257
> [pid  3998] sendmsg(257, {msg_name={sa_family=AF_INET, sin_port=htons(33334), sin_addr=inet_addr("127.255.255.255")}, msg_namelen=16, msg_iov=[{iov_base="SIXml\r\nTerminalReque"..., iov_len=47}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_WAITALL|MSG_BATCH|MSG_ZEROCOPY|MSG_CMSG_CLOEXEC|0x2600000}, 0) = -1 EACCES (Permission denied)

**Comment by wfurt** [comment]
That is good clue. 
Are you setting SocketOptionName.Broadcast on the socket? 
(https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=netcore-2.1)
Sending broadcast is restricted operation on Linux.

https://stackoverflow.com/questions/16217958/why-do-we-need-socketoptions-so-broadcast-to-enable-broadcast

You should be able to see same problem with running ```echo foo | nc -v  -u 127.255.255.255```

**Comment by florianislitzer** [comment]
The socket is generated by the library, which means that I cannot set SocketOptionName to Broadcast
Is there a way to start the application with a flag which allows broadcasts?

**Comment by karelz** [comment]
My understanding was that you need to turn OFF the broadcast.
We do not have overrides like that, it would create giant mess. The library needs to be updated and ported to Linux.

**Comment by wfurt** [comment]
I'm not aware of any global flag.  But that does not need to be done at creation. 
You can do it any time after - just before the send.

**Comment by florianislitzer** [comment]
@wfurt so there isnt any way without a library update?

**Comment by wfurt** [comment]
What API do you have available? You can try to find the socket object via reflection and make the call as needed.

**Comment by karelz** [comment]
Answered - there is no magic solution, just potential hacks or update of the library.
Closing.
