### ISSUE TITLE
Core SDK Installition fails on ubuntu 18.04.1

### ISSUE THREAD

**Issue by huzeyfecoskun** [dotnet/core#2024]
# Issue Title

Core SDK Installition fails on ubuntu 18.04.1

# General

Core SDK installition fails on ubuntu

![issue](https://user-images.githubusercontent.com/673053/47571548-78f19500-d941-11e8-879e-3b3456d1d0bf.png)

**Comment by karelz** [comment]
@rakeshsinghranchi @dleeapho @livarcocc can you advise where to route this issue?

**Comment by rakeshsinghranchi** [comment]
This issue was moved to dotnet/core-setup#4707
