### ISSUE TITLE
Cannot run DotNet Core app on Windows using Linux Docker Containers

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/core#2025]
When switching from Windows to Linux containers, I am unable to run a fresh DotNet core application.

I switched docker to Linux containers so that I can replicate the behavior of Cloud-hosting. I tried to create a fresh Asp.Net core 2.1 application. My operating system build is 17134.345. Every time I run I receive this error message:

Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Volume sharing is not enabled. Enable volume sharing in the Docker CE for Windows Settings.

For more info, please see: http://aka.ms/DockertoolsTroubleshooting.

I have looked online and found the solution is to reset credentials in Docker CE and then re-apply Sharing to C drive. This did not work. I also found the answer was to set up a Docker user, find the NAT, and set up sharing permissions for the Docker NAT. This also did not work.

**Comment by svick** [comment]
I don't know about the volume sharing issue (if there is one), but the first error message implies that you're trying to run a .Net Core SDK command when you only have the .Net Core Runtime installed.

What are the commands that you're running? What Docker image are you using? Can you share your Dockerfile?

**Comment by EdLichtman** [comment]
Hello,

Here is the entire solution, having pulled it straight from a new project.
[ThrowawaySol2.zip](https://github.com/dotnet/core/files/2523300/ThrowawaySol2.zip)

**Comment by EdLichtman** [comment]
Well this is odd I guess restarting my computer fixed this particular error. However I build this solution to try and get a dotnet core application running in a docker container on digital ocean and I'm still unable to resolve host from my other application. 

The symptom is: I run the program and see this output: 

docker ps --filter "status=running" --filter "name=dockercompose4513464889098130869_raspberrypilabsolutions_" --format {{.ID}} -n 1
92b77e3e623d
docker exec -i 92b77e3e623d dotnet  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.1/RaspberryPiLabSolutions.dll
The URL '' is not valid.
realpath(): Invalid argument
realpath(): Invalid argument
realpath(): Invalid argument
realpath(): Invalid argument
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Development
Content root path: /app
Now listening on: http://[::]:5123
Application started. Press Ctrl+C to shut down.

However, when I try to visit http(s)://localhost:5123 the namespace never resolves and I see an empty screen. attached are the dockerfile, the program file and the docker compose files.
[DotNetHelp.zip](https://github.com/dotnet/core/files/2523305/DotNetHelp.zip)

**Comment by karelz** [comment]
I would recommend to check documentation here: https://github.com/dotnet/dotnet-docker
cc @MichaelSimons if he has more targeted advice ...

**Comment by EdLichtman** [comment]
Thank you very much. Since it appeared to be a case of solving it by turning off and on again, I will close this issue.
