### ISSUE TITLE
Auto install global tools with a csproj

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [dotnet/core#2029]
# Issue Title

Can we auto install global tools with a csproj

# General

Previously, under DotNetCliToolReference tag, if new developers would checkout the project, they only needed to run `dotnet restore` to make the commands available.
If there are a few tools in a project, this was a very easy and natural operation. 

Is there some way for us to make it easy for developers to automatically get all the necessary global tools when checking out a new project?

**Comment by karelz** [comment]
@KathleenDollard @wli3 @livarcocc should it go to CLI repo?

**Comment by livarcocc** [comment]
We have a feature coming for .NET Core 3.0 called local tools, where your repo can specify a tool manifest file and then, once you run `dotnet tool restore` (@wli3 can confirm the exact gesture and provide more info), your tools will be available in your repo.
