### ISSUE TITLE
Set clientDomain in SmtpClient

### ISSUE THREAD

**Issue by olmobrutall** [dotnet/core#2031]
The old implementation of SmtpClient (https://referencesource.microsoft.com/#system/net/System/Net/mail/SmtpClient.cs) was able to use the clientDomain from configuration `MailConfiguration.Smtp.Network.ClientDomain;` 

```
  <smtp>
     <network host="somehost" port="25" clientDomain="mymachine.mydomain.com" enableSsl="false" />
  </smtp>
```

solving problems like this one: https://stackoverflow.com/questions/37410598/fqdn-with-smtpclient-in-powershell

But in the .Net Core implementation https://github.com/dotnet/corefx/blob/master/src/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs only the fallback to `IPGlobalProperties.GetIPGlobalProperties().HostName;` is implemented.

Unfortunately, I get a SmtpException because my Smtp server requires fully-qualified hostnames: 

![image](https://user-images.githubusercontent.com/720953/47702891-98790e00-dc1e-11e8-8b22-bf734e411323.png)

Maybe we can find a solution by changing the SMTP server, but our admins say that FQDN check is a POSTFIX default setting, so I'm surprised I'm the only one having this problem. 

Thanks

**Comment by MarcoRossignoli** [comment]
Maybe better move issue to https://github.com/dotnet/corefx

**Comment by olmobrutall** [comment]
Sorry, moved to https://github.com/dotnet/corefx/issues/33123
