### ISSUE TITLE
support for MFC in WPF applications running on .NET Core 3.0

### ISSUE THREAD

**Issue by bitbonk** [dotnet/core#2032]
We have some very large WPF applications that still use quite a lot of MFC through C++/CLI and mixed mode assemblies. Since .NET Core 3.0 will [support mixed mode assemblies](https://github.com/dotnet/coreclr/issues/18013), it would be great if this scenario is also officially supported in 3.0

Are you planning to support this in 3.0?

**Comment by morganbr** [comment]
.NET Core 3.0 will support C++/CLI on Windows. I don't know much about MFC or how that interacts though.

**Comment by karelz** [comment]
@diverdan92 @fabiant3 any insights about MFC support in WPF?

**Comment by diverdan92** [comment]
@jeffschwMSFT - do you know?

**Comment by jeffschwMSFT** [comment]
I am not aware of any explicit product decision around MFC usage.  @bitbonk can you share a sample of what you have been doing on .NET Framework WPF + MFC?  We can take a look.  If it is WIndows only and C++/CLI I would expect it would align with our C++/CLI work.

**Comment by NN---** [comment]
@morganbr Is it official statement ?
I didn't see any blogpost about this

**Comment by karelz** [comment]
C++/CLI is official. MFC support depends on what is expected.

**Comment by julre** [comment]
@karelz
Does that mean it will be possible to use .NET standard and .NET core assemblies from C++/CLI? It would bei awesome to use libraries like Microsoft.Extensions.Logging   in our C++/CLI code!

**Comment by karelz** [comment]
It means that C++/CLI assemblies (targeting .NET Core) will be able to run on .NET Core.

**Comment by bitbonk** [comment]
I can't share the whole application because it is too big, but this is basically what we do:

Our root application are (have now become) regular C# WPF application projects. In `System.Windows.Application.OnStartup` we call in to a mixed mode (C++/CLI) to initialize MFC (using a ref class `MfcInitializer`).

_`MyApp.cpp` in the mixed mode assembly_:
``` 
// static instance, with is declared as follows:
// class _declspec(dllexport) CMyApp : public CWinAppEx
CMyApp* myApp;

public ref class MfcInitializer
{
public:
    static bool Initialize()
    {
        myApp = new CMyApp();        
        ComponentDispatcher::ThreadFilterMessage += gcnew System::Windows::Interop::ThreadMessageEventHandler(&MfcInitializer::OnThreadFilterMessage);
        ComponentDispatcher::ThreadIdle += gcnew System::EventHandler(&MfcInitializer::OnThreadIdle);
        return theApp->InitInstance() != 0;
    }

    static void Exit()
    {
        myApp->ExitInstance();
        ComponentDispatcher::ThreadFilterMessage -= gcnew System::Windows::Interop::ThreadMessageEventHandler(&MfcInitializer::OnThreadFilterMessage);
        ComponentDispatcher::ThreadIdle -= gcnew System::EventHandler(&MfcInitializer::OnThreadIdle);
    }

    static void OnThreadFilterMessage(System::Windows::Interop::MSG %msg, bool %handled)
    {
        ::MSG m;
        m.message = msg.message;
        m.hwnd = (HWND)msg.hwnd.ToPointer();
        m.wParam = (WPARAM)msg.wParam.ToPointer();
        m.lParam = (LPARAM)msg.lParam.ToPointer();
        m.pt.x = msg.pt_x;
        m.pt.y = msg.pt_y;
        m.time = msg.time;
        handled = ::AfxPreTranslateMessage(&m) != 0 ? true : false;
    }

    static void OnThreadIdle(Object^, EventArgs^)
    {
        LONG lIdle = 0;
        while (AfxGetApp()->OnIdle(lIdle++))
        {
        }
    }
}
```

Our application has an extensibility model for MFC/C++ developers. They can write purely unmanaged MFC dlls that get loaded by us using `LoadLibraryEx`. The extensibility APIs are declared in a header file we deploy. This header file is also the place where `class _declspec(dllexport) CMyApp : public CWinAppEx` is declared. Extension authors can derive from a special plugin class that is declared as`_declspec(dllexport)`. At runtime we load (`LoadLibraryEx`) an instantiate those classes.

The native MFC content is displayed in a `System.Windows.Forms.Integration.WindowsFormsHost` which is then displayed in a `System.Windows.Forms.Integration.ElementHost`.

**Comment by bitbonk** [comment]
Any update on this? I suppose at some point before the release of 3.0 you'd need to make a somewhat official statement. cc @onovotny

**Comment by jeffschwMSFT** [comment]
Our C++/CLI support is coming along.  We hope to have it in an upcoming preview.  There are a number of moving parts with the compilers/libraries shipping in an upcoming VS 2019 release and the runtime support coming in an upcoming .NET Core 3.0 Preview.  I do not have a firm date at this point, though all seems on track for a .NET Core 3.0 ship.

**Comment by bitbonk** [comment]
@jeffschwMSFT
C++/CLI support is one thing and it is great to know that it is coming along. But what about the *MFC* support (which this issues is about).

The developer in me kind of hopes that MFC will not be supported (so I have arguments to get rid of the old stuff) but my boss may think differently. 🤷🏻‍♂️

**Comment by jeffschwMSFT** [comment]
Adding @cmckinsey

**Comment by carlossanlop** [comment]
Here's an announcement: https://devblogs.microsoft.com/cppblog/the-future-of-cpp-cli-and-dotnet-core-3/

**Comment by bitbonk** [comment]
Still no mention of MFC anywhere.

**Comment by weltkante** [comment]
Maybe clarify what support you are asking for? MFC is C++/win32 and has nothing to do with .NET - neither Core nor Desktop - so there's no mention of MFC anywhere because there's nothing needing mentioning. MFC is doing its own thing and you can use the general purpose .NET Core / WinAPI interop, but there's nothing MFC specific required or available.

The closest I can think of is the ActiveX API which is not MFC specific but which is probably still supported by WinForms. I don't think they are actively testing it, so if you have scenarios which need ActiveX WinForms interop to host MFC then this probably needs to be discussed/resolved in the WinForms repo.

**Comment by bitbonk** [comment]
I though I already did clarify what I meant to great extend?

**Comment by weltkante** [comment]
What you described is general purpose interop and not related to MFC? Thats why its not mentioned anywhere. What I'm asking is what *MFC specific* support are you expecting?
