### ISSUE TITLE
How to transfer an amr stream to aac stream?

### ISSUE THREAD

**Issue by liuweizzuie** [dotnet/core#2036]
# How do I transfer an amr stream to aac stream?

I'm using netcore 2.0 for centos with my company's webapi service, it is some kind of IM system. however I come across an request.

our users send messages , TXT, IMAGE, VOICE, short VIDEO, etc,  to Platform A.

our service read the messages from the APIs provided by Platform A, and transport them to Platform B.
while the messages from users of Platform B shall be transported to Platform A, too.

Platform A provides the AMR file format for voice,  but platform B require the voice message be AAC format, so that's the problem.

someone said the [ffmpeg](http://ffmpeg.org/) will do the work, just call the shell command. but that's not what I want, because it read and store  files from/to disk, and the calling between progresses will not be fast enough.  

and another project [NAudio](https://github.com/naudio/NAudio) sounds good, but it seems to be a desktop project,  it doesn't support for netcore for linux.

I want a library that works in my thread,  just like [ImageSharp](https://github.com/SixLabors/ImageSharp)  for image streams, without disk and process work to do.

I worked on the voice problem for days,  maybe not enough. maybe it's a good idea to call the c library of ffmpeg, or recompile NAudio for netcore. but both will take me too long time.

I believe there would be a netcore library that do this work.

there are 5 github search results for keyword "audio"  &  "netcore",  one of them is [SharpAudio](https://github.com/feliwir/SharpAudio), but it only supports for wav, mp3, ogg. 

and nuget results are too many of.   most of them depends on net framework and I cant use them with netcore.

so, maybe I should write one myself.  but I must solve this in limited time. I don't know where to ask questions, stackoverflow ? not a good idea.

netcore team made lots of outstanding works for developers, they help me a lot, so  I come here to ask if there's a library can do my task, maybe someone knows.

**Comment by karelz** [comment]
This is beyond scope of this repo, closing.
I think your best option is to ask on StackOverflow or other kind of forums.
Or maybe you will be lucky and someone will notice it here and answer ...
