### ISSUE TITLE
Swapping from ASP .Net Core 1.0.0-rc2-final to 1.0.0 causes published site to fail with CGI errors

### ISSUE THREAD

**Issue by dumbledad** [dotnet/core#204]
I've just upgraded my ASP project from ASP .Net Core 1.0.0-rc2-final to 1.0.0. There were two issues that were not handled by the Nuget Package Manager. 

Firstly 

    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },

was updated to just 

    "Microsoft.NETCore.App": "1.0.0",

which failed to compile and so I changed that to

    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },

Secondly I needed to change

    services.AddMvc();

to 

    services
        .AddMvc()
        .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

in my `Startup.cs` file. The only other changes were those made by Nuget to my `project.json` file.

The project runs without issue locally, and successfully publishes from VS2015 to Azure. However, when I open a browser onto my site on Azure I get the error message 

> The specified CGI application encountered an error and the server terminated the process.

Why? How do I diagnose and fix this error?

**Comment by svick** [comment]
Does your application work locally?

**Comment by dumbledad** [comment]
It does. Works fine locally. No deployment errors reported during publishing. It's just when I go to the published site on Azure I see the CGI error reported

**Comment by Petermarcu** [comment]
@Eilon

**Comment by Eilon** [comment]
@Tratcher is this something gone wrong in AspNetCoreModule?

**Comment by Tratcher** [comment]
Usually it's an environmental/config problem causing the application to crash on start. Check the events (in the portal?) and enable logs (stdoutLogEnabled="true") in web.config. See https://github.com/aspnet/Docs/issues/1358

**Comment by dumbledad** [comment]
I've set `stdoutLogEnabled="true"` in the `web.config` file and redeployed. I cannot see where to get the events from. I'll keep looking.

**Comment by dumbledad** [comment]
Found the logs. In that Azure Portal console I needed `../../LogFiles/eventlog.xml` That's full of entries like this:

    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1000</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2016-07-06T08:55:16Z"/>
            <EventRecordID>532761796</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FFB01B32</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Failed to start process with commandline '%LAUNCHER_PATH% %LAUNCHER_ARGS%', Error Code = '0x80070002'.</Data>
        </EventData>
    </Event>

The `web.config` is the same between RC2 (which works) and 1.0 (which fails) and looks like this:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <system.webServer>
        <handlers>
          <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
        </handlers>
        <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="true" />
      </system.webServer>
    </configuration>

**Comment by dumbledad** [comment]
I'm wrong there, the web.config files are not the same (I was confused by there being two web.config files in each deployment). In RC2 the `%VARIABLE%` are replaced with values, in 1.0 they are not. Has something changed there? Is this still the correct entry in the `project.json` file?

    "scripts": {
      "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }

**Comment by dumbledad** [comment]
Fixed: http://stackoverflow.com/a/38228793/575530

**Comment by nilavghosh** [comment]
I commented the sdk version from global.json of the solution and everything started working when deploying the application to azure web apps.
