### ISSUE TITLE
Running an ASP.NET Core website on Raspberry PI eventually crashes

### ISSUE THREAD

**Issue by rgelb** [dotnet/core#2040]
# Running an ASP.NET Core website on Raspberry PI 2 eventually crashes

I published a relatively simple (as far as server side processing) site onto my Raspberry Pi.  It ran for about 2 days, then I got the following error:

*** Error in `./ValueYourHome': double free or corruption (fasttop): 0x4fe51b60 ***
Aborted

Not sure where on the system I could find further information on this error.  Don't see any obvious places where an error log would be, but I am not a Linux expert.  The model in question is _Raspberry Pi 2 Model B Rev 1.1_.

Here is the dump from /proc/cpuinfo:

> processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

> processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

> processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

> processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

> Hardware        : BCM2835
Revision        : a21041
Serial          : 000000001d8e1ab1

**Comment by wfurt** [comment]
https://github.com/dotnet/coreclr/issues/18486 ???

**Comment by karelz** [comment]
That one was fixed in 2.1.5: https://github.com/dotnet/coreclr/issues/18486#issuecomment-428402126 ... @rgelb can you please try that version? (and check that you used earlier 2.1 version?) Thanks!

Thanks @wfurt!

**Comment by rgelb** [comment]
> Which version of .NET Core do you use? 

I believe it was some version of .NET Core 2.1.x.  I don't remember exactly the version that was installed during the build/publish cycle.  And I am not clear as to how to interrrogate this information from the binaries deployed on the raspberry pi.

> Which Linux distro do you use? (Only certain distros are [supported on arm](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux))

The distro is Raspbian, which comes with the Raspberry.  The version is "Raspbian GNU/Linux 8 (jessie)".  Based on wiki [page](https://en.wikipedia.org/wiki/Raspbian) about Raspbian, it is based on Debian 8, which is on the supported list (from link you provided).  And...I've seen Hanselman install apps to it on his blog.  

> Are you able to collect crash dumps? (some Linux background will be needed for that)

I do not have a linux background and it hasn't failed since that one time, but if you provide me instructions, I'll be happy to do that.  

> 
> cc @wfurt @janvorli for additional guidance / pointers

**Comment by rgelb** [comment]
> That one was fixed in 2.1.5: [dotnet/coreclr#18486 (comment)](https://github.com/dotnet/coreclr/issues/18486#issuecomment-428402126) ... @rgelb can you please try that version? (and check that you used earlier 2.1 version?) Thanks!

@karelz I'll give it a shot and report if the problem recurs.

**Comment by karelz** [comment]
@rgelb did you get chance to give it a try?

**Comment by rgelb** [comment]
@karelz Yes, it's running on it now.  It hasn't failed so far.  I've compiled with 2.1.403 SDK and 2.1.5 runtime. I think it's safe to shut this issue down.

**Comment by karelz** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/18486
