### ISSUE TITLE
Could WPF on .net core  have `Program.Main`?

### ISSUE THREAD

**Issue by John0King** [dotnet/core#2045]
AFAIK  `App.Xaml` hide the entry-point in WPF .
Could the template of WPF  always has the `Program.Main` entry-point ?

```c#
public static void Main(string[] args)
{
    var app = new MyApp.App();
    //app.InitializeComponent();  call this in App's constructor
    app.Run();
}
```

this will let developer know  how Xaml app start, and customize app start easily (control start as command line app or UI app).

**Comment by karelz** [comment]
@John0King is that something that exists on WPF for .NET Framework?
BTW: This repo tracks only work for porting WPF to .NET Core. We are not set up yet to track feature requests that are beyond parity with WPF on .NET Framework.

cc @fabiant3 @diverdan92

**Comment by rido-min** [comment]
@John0King you can always use your custom entry point to start a WPF app:

1. Remove the StartupUri from App.xaml
2. Add the next Program.cs file

```cs
[STAThread]
static void Main(string[] args)
{
    App a = new App();
    a.StartupUri = new Uri("/MainWindow.xaml", UriKind.Relative);
    a.Run();
}
```
3. Change the project startup in your csproj
```xml
 <StartupObject>MyWpfApp.Program</StartupObject>`
```

Is this a request to change the default template?

**Comment by John0King** [comment]
I simply want  `App.Xaml` not generate the Entry-point , just put the Entry-point in ` App.Xmal.cs`

**Comment by karelz** [comment]
@John0King please file your question on WPF repo: https://github.com/dotnet/wpf

**Comment by thomasclaudiushuber** [comment]
I just want to add here that you can control whether an entrypoint is generated or not with the App.xaml's Build Action. It's `ApplicationDefinition` by default, which will generate the Main-method. If you set it to `Page`, you won't get a Main method and you can implement your own file. 

As linked above by @John0King: Discussion continued on https://github.com/dotnet/wpf/issues/192
