### ISSUE TITLE
.Net Core not enforcing implementation of members in a Class C inherited from Interface A through Interface B

### ISSUE THREAD

**Issue by dannyjacosta** [dotnet/core#2046]
# .Net Core not enforcing implementation of members in a Class C inherited from Interface A through Interface B

# General
I'm seeking some guidance with the following issue.
I have an Interface A with a method A.DoSomething
I have another interface B with a method B.DoSomethingElse. B Inherits from A
I have a class C that inherits from interface B
```
interface A
{
   void DoSomething();
}

interface B : A
{
   void DoSomethingElse();
}

public class C : B
{
   public void DoSomethingElse()
   {
      //do something else here
   }
}
```
If I have the above code in .NET Standard I get a compile time error stating that class C must implement interface A. However if I write the same code in .NET Core I don't get any compile time error to enforce the implementation of interface A in class C.
I'm using .NET Core 2.1 with Visual Studio Enterprise 2017 version 15.8.9.

**Comment by svick** [comment]
I created a brand new .Net Core 2.1 application in VS 15.8.9 with the following code:

```c#
class Program
{
    static void Main() { }
}

interface A
{
    void DoSomething();
}

interface B : A
{
    void DoSomethingElse();
}

public class C : B
{
    public void DoSomethingElse()
    {
        //do something else here
    }
}
```

And I got the expected error:

>Error	CS0535	'C' does not implement interface member 'A.DoSomething()'

Is it possible that something else is going on on your side, like you editing a file that isn't part of the project? If not, could you provide exact steps to reproduce the problem?

**Comment by dannyjacosta** [comment]
@svick, Indeed it might have been something on my side. I get the expected error after rebooting my machine. I spent hours struggling with this issue and the one things that I had not done was rebooting. Thank you for your time.

**Comment by dannyjacosta** [comment]
This not an issue. It was something on my side.
