### ISSUE TITLE
"Official" Abbreviation

### ISSUE THREAD

**Issue by mmacneil** [dotnet/core#2047]
# "Official" Abbreviation for .NET Core & ASP.NET Core

Sorry if this doesn't belong here or is a waste of time but I'm just wondering if there is an abbreviation/acronym to represent *dotnet core* sensibly and by extension *asp.net core*.

I find repeatedly typing and speaking the names to be wordy - maybe it's just me.

I think `dnx` for *dotnet core* is ideal, but it was the name of the related, now retired [dnx](https://github.com/aspnet/dnx) project which I suppose would be too confusing.  However, `aspdnx` would be a good counterpart in that case.

Am I crazy?

Thanks,
Mark

**Comment by kjsingh** [comment]
dnc and anc? 😃

**Comment by karelz** [comment]
We do not have official abbreviations beyond ".NET Core" and "ASP.NET Core" ... the names are already short enough.
I have seen on few occasions DNC being used for DotNetCore (in file names), but it was VERY confusing to me and others IMO. It is NOT something I would recommend to use a lot.

**Comment by scottpage** [comment]
It may, or may not, be short enough, but searching for "aspnet core", "asp.net core", "aspnetcore", etc produces blurry results that include the .NET Framework.  I come from several worlds were acronyms are king, the Marines, aerospace, and control systems.  Any misunderstood technology gets you into a heap of trouble.

There must a something that pins .NET Core down to it's own domain.
