### ISSUE TITLE
Apply to add Priority Queue to .Net Core

### ISSUE THREAD

**Issue by memoryfraction** [dotnet/core#2048]
Apply to add Priority Queue to .Net Core

# General
Priority Queue is a useful data structure. Some one may explain that SortedSet can handle similar scenarios. Problem is, sometimes, users  need to add duplicate items.

So, I apply to add Priority Queue to .NET CORE.

Thanks

**Comment by karelz** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/574
