### ISSUE TITLE
Running dotnet on Alpine Linux yields errors loading libstdc++ and libgcc

### ISSUE THREAD

**Issue by mattmon1** [dotnet/core#2050]
I'm trying to run a .NET Core 2.1 console application on an Alpine Linux (3.8.1) VM that's hosted by W10 HyperV. Just reaching out to the community to see if you can provide some guidance for getting up and running. Unfortunately, I'm experiencing some issues when I run dotnet from the Alpine Linux console.

For the Alpine Linux install, I followed [this](https://wiki.alpinelinux.org/wiki/Install_to_disk) install procedure by mounting the 3.8.1 Virtual ISO (https://alpinelinux.org/downloads/) to the VM and answering the command prompt questions per the procedure. I installed OpenSSH, was able to login as root and run add-user. Then from a W10 admin command prompt, I ran ssh to get into the Alpine
Linux VM using ssh -l <added-user-name> <vm-ip> and then ran su root. 

I downloaded the .NET Core 2.1.2 runtime using the download link on [this](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore21) page and used PowerShell with Hyper-V Guest Services to transfer the ISO to Alpine Linux. From the Linux console, I executed:
	mkdir $HOME/dotnet
	tar zxf dotnet-runtime-2.1.2-linux-musl-x64.tar.gv -C $HOME/dotnet

All seemed well up to this point. However, when I run dotnet from the Linux console as root, I get the following output:

![alpine linux dotnet exec 2018-11-12_22-12-24](https://user-images.githubusercontent.com/35613928/48427292-0d276e80-e72e-11e8-9130-19a0c5a8474e.png)

I was disappointed to see that the dotnet output suggests that gcc is needed since I was hoping to get away from gcc by using Alpine. The output prompted me to run apt to search, find & install libstdc++ and libgcc packages, which fail with the following unsatisfiable constraint error:

![alpine linux apt](https://user-images.githubusercontent.com/35613928/48427421-4a8bfc00-e72e-11e8-9c4f-76c601b99814.png)

At this point, I'm at an impasse and in need of some guidance...

**Comment by mattmon1** [comment]
Sorry, a correction... it typed that I ran apt.... which should read that I ran apk

**Comment by karelz** [comment]
@wfurt @leecow any suggestions? I don't see libstd or libgcc in list of prereqs for Alpine or other distro: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore21#install-net-core-for-supported-alpine-linux-versions-64-bit

cc @bartonjs

**Comment by leecow** [comment]
@janvorli to help puzzle out the sys dependency issue.

**Comment by wfurt** [comment]
try `apk add libstdc++`. That is normally part of OS so it is not listed as extra prerequisite.

**Comment by mattmon1** [comment]
Tried apk add liststdc++

I can find the package with a search but Alpine shell returns 'unsatisfiable constraint' when I try to install the package

![apk add liststdc 2018-11-13_15-21-40](https://user-images.githubusercontent.com/35613928/48443917-30671380-e758-11e8-8223-bd6c76d3a548.png)

**Comment by mattmon1** [comment]
fwiw, here's a list of the installed packages. It's pretty much the Alpine Linux default set since the only 2 package install's i tried failed per my earlier comments.

![apk info 2018-11-13_15-28-02](https://user-images.githubusercontent.com/35613928/48444229-f21e2400-e758-11e8-98dd-1b5440825ce3.png)

**Comment by mattmon1** [comment]
and i mistyped - I did add the hvtools package

**Comment by wfurt** [comment]
mistyped what? You should not need version when adding package and it is `libstdc++` not `liststdc++`

```
bash-4.4# apk info libstdc++
libstdc++-6.4.0-r9 description:
GNU C++ standard runtime library
```

**Comment by mattmon1** [comment]
Mistyped "the only 2 package install's i tried failed per my earlier comments." - i did install hvtools.

Running:
apk add liststdc++
apk add libgcc

without version numbers worked. Now, when I run dotnet, i get the expected usage output.

![dotnet good 2018-11-13_16-21-50](https://user-images.githubusercontent.com/35613928/48447439-7ffe0d00-e761-11e8-9c0e-211396761ed2.png)

For .NET Core 2.1.2 to work on Alpine Linux 3.8.1, these 2 packages are needed in addition to running tar on the runtime distributable.  Feeling a little rusty with my Linux commands at the moment... Thanks for you help in resolving this issue.

**Comment by wfurt** [comment]
note that `apk add libgcc` should not be needed. That should be pulled in as dependency for libstdc++
do we plan Alpine specific instructions @leecow ?

**Comment by leecow** [comment]
Yep, do need to add Alpine steps to the docs.
