### ISSUE TITLE
dotnet build fails with "MSB3030 unable to copy dll because it was not found"

### ISSUE THREAD

**Issue by tpardhu561** [dotnet/core#2052]
# dotnet build fails with "MSB3030 unable to copy dll because it was not found"

# issue

I'm trying to build with .Net core 2.1.302 on a Windows node thru Jenkins.

steps to reproduce the issue:
`dotnet build
`
`E:\apps\dotnet-v2.1.3\sdk\2.1.302\Microsoft.Common.CurrentVersion.targets(4172,5): error MSB3030: Could not copy the file "obj\Debug\netstandard2.0\Expression.dll" because it was not found. [E:\jh\a1\d2rqwrw\workspace\common\app-name\dev\services\ExpressionService\master-pipeline\Source\Expression\expression.csproj]`

Project builds successfully on my local machine but fails with above error thru a Jenkins pipeline.
I'm able to build other .Net core apps on same Jenkins nodes.

Thanks
Partha

**Comment by karelz** [comment]
What is Expression.dll? Is it part of your app?
Are all prereqs installed on the Jenkins machine?
Are you able to reproduce the same on brand new VM (without Jenkins)?

**Comment by tpardhu561** [comment]
@karelz Expression.dll is part of our app and will be generated during the build process.
Yes, all the prereqs were installed on Jenkins machine and I'm able to build other apps.
I tried but unable to reproduce the issue. I see this issue only when built thru a pipeline in Jenkins but works fine with a freestyle job in Jenkins.

As per logs, I get an error message that the DLL was not found but in reality, I can see the DLL is present in requested path.

I'm not a Dotnet developer but a DevOps Engineer trying to figure out the issue.

**Comment by karelz** [comment]
@tpardhu561 in that case I would suggest to involve some developers to help you out debug the build. It seems like the DLL is referenced at the moment it was not build yet. Maybe there is bug in parallelism of build and how projects depend on each other.

**Comment by tpardhu561** [comment]
@karelz I'm trying to get app Developer to discuss.

**Comment by karelz** [comment]
@tpardhu561 by prereqs I meant - .NET Core SDK and all other things your project needs.

**Comment by tpardhu561** [comment]
We didn't knew what was the exact root cause but Rebuilding the project files and Solution file resolved our issue.

Thank you
