### ISSUE TITLE
The specified framework 'Microsoft.AspNetCore.App', version '2.1.4' was not found.

### ISSUE THREAD

**Issue by vlapenkov** [dotnet/core#2056]
#  Dotnet core Framework 2.1.4 is installed on Windows but can't run

# General

dotnet .\WebAppCore.dll error
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.4' was not found.
- Check application dependencies and target a framework version installed at:
    \
 - Alternatively, install the framework version '2.1.4'.

PS C:\inetpub\wwwroot\testcore.yst.ru> **dotnet --info**
Программы командной строки .NET (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

**Here is csproj file**
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

 <!-- <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup> -->

  <PropertyGroup>
    <UserSecretsId>aspnet-WebAppCore-6516f79b-cb7c-43cd-b942-286829c40402</UserSecretsId>
    <DockerTargetOS>Windows</DockerTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\main.js" />
    <None Remove="Scripts\main.ts" />
    <None Remove="Scripts\site.min.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Scripts\main.js">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\lib\**" CopyToPublishDirectory="Never" />
    
  </ItemGroup>

 <!-- <ItemGroup>
    <Content Include="wwwroot\css\custom.css" />
    <Content Include="wwwroot\css\custom.min.css" />
    <Content Include="wwwroot\js\custom.js" />
    
  </ItemGroup>-->
  <ItemGroup>
    <PackageReference Include="Elasticsearch.Net" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.4"/>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />   
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.4.1" /> 
  </ItemGroup>
  <ItemGroup>  
    <PackageReference Include="X.PagedList.Mvc.Core" Version="7.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApp.DAL\WebApp.DAL.csproj" />
    <ProjectReference Include="..\WebApp.Services\WebApp.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="Scripts\main.ts" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Pages\_ViewImports.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Pages\_ViewStart.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Controllers\HomeController.en.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers\HomeController.ru.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>
</Project>
```

**Comment by vlapenkov** [comment]
Here is .csproj file
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

 

  <PropertyGroup>
    <UserSecretsId>aspnet-WebAppCore-6516f79b-cb7c-43cd-b942-286829c40402</UserSecretsId>
    <DockerTargetOS>Windows</DockerTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\main.js" />
    <None Remove="Scripts\main.ts" />
    <None Remove="Scripts\site.min.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Scripts\main.js">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\lib\**" CopyToPublishDirectory="Never" />
    
  </ItemGroup>

 
  <ItemGroup>
    <PackageReference Include="Elasticsearch.Net" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.4"/>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />   
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.4.1" /> 
  </ItemGroup>
  <ItemGroup>  
    <PackageReference Include="X.PagedList.Mvc.Core" Version="7.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApp.DAL\WebApp.DAL.csproj" />
    <ProjectReference Include="..\WebApp.Services\WebApp.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="Scripts\main.ts" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Pages\_ViewImports.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Pages\_ViewStart.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Controllers\HomeController.en.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers\HomeController.ru.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>
</Project>

**Comment by karelz** [comment]
Are you able to reproduce the same problem on brand new machine/VM?

**Comment by karelz** [comment]
Does it fail for newly created project (with manually added dependencies) as well or is it specific to your larger project?
If you can repro with newly created project, can you please share your steps? Thanks!

**Comment by karelz** [comment]
Can you please post entire `dotnet --info` output? Does it have this entry?
`Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]`

**Comment by Eilon** [comment]
Projects should generally not reference `Microsoft.AspNetCore.App` with a specific version:

```xml
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.4"/>
```

But instead they should leave off the version and the SDK will choose the appropriate version:

```xml
    <PackageReference Include="Microsoft.AspNetCore.App" />
```

But, if you think you have 2.1.4 installed, that should still work...

More info on the package version can be found in the migration doc: https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#update-the-project-file-to-use-21-versions

> * Remove the "Version" attribute on the package reference to Microsoft.AspNetCore.App. Projects which use <Project Sdk="Microsoft.NET.Sdk.Web"> do not need to set the version. The version will be implied by the target framework and selected to best match the way ASP.NET Core 2.1 works. (See below for more information.)

**Comment by vlapenkov** [comment]
It solved when i installed runtime and hosting bundle from https://www.microsoft.com/net/download/dotnet-core/2.1
I hadn't runtime yet

**Comment by titonton** [comment]
I still have this error with the correct runtime and installed in the server

```
Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

csproj file
<TargetFramework>netcoreapp2.1</TargetFramework>

**Comment by titonton** [comment]
it works for the first 10 minutes and then I get this error in the logs 
```
It was not possible to find any compatible framework version

The specified framework 'Microsoft.AspNetCore.All', version '2.1.4' was not found.

  - Check application dependencies and target a framework version installed at:

      \

  - Alternatively, install the framework version '2.1.4'.

```

**Comment by Eilon** [comment]
@titonton this is a very old bug so it is not likely that the people who work on this project will see your updates. Could you log a new issue with detailed steps to reproduce your issue? That should help get a faster response for the problem you're seeing. Thanks!

**Comment by titonton** [comment]
@Eilon Thanks for the quick reply. I figured out the problem. My server was being mirrored. So I had to install the version on the other machine as well. All my bad.
