### ISSUE TITLE
Missing 2.1.403 SDK

### ISSUE THREAD

**Issue by vcsjones** [dotnet/core#2059]
For a while we've had this in our Travis builds for installing the 2.1.403 SDK prior to test execution.

```
- "curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin --version 2.1.403 --install-dir /opt/dotnet"
```

That has worked for months until recently, which seems to coincide with the 2.1.500 SDK release. At ~10:30 AM EST, this resulted in a 404.

![image](https://user-images.githubusercontent.com/361677/48504269-5355fe00-e812-11e8-9ca5-a4fabc1b9a3d.png)

<strike>Is this expected behavior?</strike>

I can't seem to reproduce this any more, but I'll leave the issue here open until someone confirms it has been fixed (in case it was intermittent) and include any additional details if necessary.

**Comment by karelz** [comment]
@leecow can you please take a look? Or recommend someone to take a look?

**Comment by leecow** [comment]
Everything looks fine on the Azure storage - https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.403/dotnet-sdk-2.1.403-linux-x64.tar.gz downloads the file as expected.

**Comment by karelz** [comment]
Any idea what caused the hiccup @leecow? Something we can watch for / avoid in future? Maybe caused by our 2.1.6 release? Or is it just mystery?

**Comment by vcsjones** [comment]
@leecow This was for 2.1.403 though, not 2.1.500.
