### ISSUE TITLE
Broken link in .net core download page for 2.1.6 release notes

### ISSUE THREAD

**Issue by Yanal-Yves** [dotnet/core#2062]
Hello,

At writting time when I go to https://www.microsoft.com/net/download/dotnet-core/2.1 and click on "Release notes" link of .net core 2.1.6, link is broken.
It points to https://www.microsoft.com/net/download/dotnet-core/2.1 instead of https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.6/2.1.6.md

Could you fix the link ?

**Comment by karelz** [comment]
Confirmed.
@leecow @vivmishra do you know how to fix that page? Does it live in some private repo?

**Comment by leecow** [comment]
It's a private repo and Vivek has checked in a fix. Should be live soon.

**Comment by vivmishra** [comment]
Pushed out the fix.
