### ISSUE TITLE
How to edit Post-build script which can support windows & Linux

### ISSUE THREAD

**Issue by tiayi** [dotnet/core#2065]
# General

I have a aspnetcore project need copy some files to other folder after build, post-build script is best idea.
Example: 
`xcopy $(OutDir)Mocks\* $(ProjectDir)\Mocks\ /Y /D /R /S`

But it just work on windows.

Does it support cross-platform?

My build environment is in docker, docker image `microsoft/dotnet:2.1.500-sdk`.

**Comment by karelz** [comment]
I think msbuild has copy-file options. Can you use that?
Otherwise you will have to have specific Linux vs. Windows copy code.

@nguerrera @dsplaisted any insights?

**Comment by dsplaisted** [comment]
@tiayi You can do this with the MSBuild `Copy` task in a target.  Something like this:

```xml
<Target Name="CopyMocks" AfterTargets="Build">
  <ItemGroup>
      <MockFile Include="$(OutDir)Mocks\**\*.*" />
  </ItemGroup>
  <Copy 
      SourceFiles="@(MockFile)" 
      DestinationFolder="$(ProjectDir)\Mocks\%(RecursiveDir)" 
      SkipUnchangedFiles="true" />
</Target>
```

**Comment by tiayi** [comment]
Oh, that's helpful. Thank you.

**Comment by karelz** [comment]
Seems to be answered, closing.
