### ISSUE TITLE
Issue on add-migration in this current bridging class (many-to-many)

### ISSUE THREAD

**Issue by dcpartners** [dotnet/core#2066]
# Issue Title

An issue on add-migration in this current bridging class (many-to-many)

# General

Platform:
.Net Core 2.1
Ms SQL Server 

Currently, we have this model - HostApplicationUser and it's bridging for Many-To-Many between Host and ApplicationUser (extended from IdentityUser) model  relationship:

```c#
public class HostApplicationUser
{
    public Guid HostID { get; set; }
    public Host Host { get; set; }
   public string Id { get; set; }
   public ApplicationUser ApplicationUser { get; set; }
   public bool IsDeleted { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }

}
```

And in our, ApplicationDBContext we modified the protected override void OnModelCreating(ModelBuilder builder) to include as follow:

```c#
// Many to Many relationships

            builder.Entity<HostApplicationUser>()
                .HasKey(bc => new { bc.HostID, bc.Id });


            builder.Entity<HostApplicationUser>()
                .HasOne(bc => bc.Host)
                .WithMany(b => b.HostApplicationUsers)
                .HasForeignKey(bc => bc.HostID);

            builder.Entity<HostApplicationUser>()
                .HasOne(bc => bc.ApplicationUser)
                .WithMany(c => c.HostApplicationUsers)
                .HasForeignKey(bc => bc.Id);
```

This code has been running ok. BUT now we have a new requirement to add a few properties/navigation especially CreatedBy, LastModifiedBy which is enforcing the ForeignKey into these models ApplicationCreatedUser and ApplicationLastModifiedUser  etc etc as follow :

```c#
public class HostApplicationUser
{
    public Guid HostID { get; set; }

    public Host Host { get; set; }

    public string Id { get; set; }

    public ApplicationUser ApplicationUser { get; set; }

    public DateTime CreatedUTC { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedUTC { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? DeletedUTC { get; set; }

    public string DeletedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }

    [ForeignKey("CreatedBy")]
    public ApplicationUser ApplicationCreatedUser { get; set; }

    [ForeignKey("LastModifiedBy")]
    public ApplicationUser ApplicationLastModifiedUser { get; set; }

}
```

These approaches that we did is working OK with other models (One-To-Many) relationship. But not with this bridging model and we have an error when we run the add-migration:

> Unable to determine the relationship represented by navigation property 'HostApplicationUser.ApplicationCreatedUser' of type 'ApplicationUser'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

Any ideas on how to fix this? I believe this something to do with OnModelCreating(ModelBuilder builder) to include the other navigation but not sure how to do that.

Thanks

**Comment by karelz** [comment]
Which APIs to do you use? Is it database? EntityFramework? Something entirely else?

**Comment by dcpartners** [comment]
@karelz Updated already.

**Comment by ajcvickers** [comment]
@karelz For future reference this is [EF Core](https://github.com/aspnet/EntityFrameworkCore), but this issue is actually specifically about use of EF Core by [ASP.NET Core Identity](https://github.com/aspnet/Identity)

@dcpartners There is [a guide to customizing the Identity model in the docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.1). I would suggest going through that documentation as a guide to how to do this. If that still doesn't work, then please file an issue on the [Identity repo](https://github.com/aspnet/Identity) including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
