### ISSUE TITLE
System.Globalization.CultureInfo (fi-FI or sv-SE) differs inside Docker container and Windows

### ISSUE THREAD

**Issue by eerokosk** [dotnet/core#2069]
# System.Globalization.CultureInfo (fi-FI and sv-SE) differs inside Docker container and Windows

CultureInfo object instances for fi-FI and sv-SE are containing different values between operating systems which are causing portability problems when you are moving your application to the Docker world.

Especially CultureInfo.NumberFormat.NegativeSign causes problems when you are trying to parse negative integers inside containers because negative sign inside container is '−' (U+2212) instead of '-' (U+002D) which are breaking machine readable formats. I did use image microsoft/dotnet:2.1.500-sdk from hub.docker.com.

When you are running attached [cultureinfo.zip](https://github.com/dotnet/core/files/2598547/cultureinfo.zip) on Windows 10 with .NET Core version 2.1.402 negative sign is U+002D for fi-FI and sv-SE. Under Docker (microsoft/dotnet:2.1.500-sdk) or Fedora 29 (2.1.403) negative sign is U+2212.

**Comment by tarekgh** [comment]
Yes, net core depends on the underlying OS for the globalization data. this is by design. in general, apps shouldn't assume the globalization data never change or even be consistent between OS's and even different versions of the same OS.
