### ISSUE TITLE
is not compatible with netcoreapp

### ISSUE THREAD

**Issue by PeterJD** [dotnet/core#2077]
Hi

Having spent many hours trying to sort this issue out, this is what I have tried so for

A few days earlier this project which i had down loaded from GitHub functioned correctly with no errors,
These errors are not just occuring in this project alone, but all projects I downloaded.

Un-installed netcoreapp2.1

Still had same error reported

Twice repaired VS 2017

Ref 1 - 2

clear all  NuGet caches

Errors changed Ref 3

Any advise on what to do next?

Kind regards

Peter

Ref 1 Microsoft.Build 15.3.409
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.Build 15.3.409 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Build 15.3.409 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

Ref  1-2 netcoreapp2.1
Error	NU1202	Package Microsoft.Build.Utilities.Core 15.3.409 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Build.Utilities.Core 15.3.409 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

Error	NU1202	Package Microsoft.Extensions.Primitives 2.0.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Extensions.Primitives 2.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

Error	NU1202	Package Microsoft.Build.Framework 15.3.409 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Build.Framework 15.3.409 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

Error	NU1202	Package NuGet.Frameworks 4.0.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package NuGet.Frameworks 4.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

Error	NU1202	Package System.Buffers 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Buffers 4.4.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	EMS.Domain	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Domain\EMS.Domain.csproj	1	

Error	NU1202	Package System.Numerics.Vectors 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	EMS.Domain	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Domain\EMS.Domain.csproj	1	

  Error	NU1202	Package System.Buffers 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Buffers 4.4.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	EMS.Persistance	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Persistance\EMS.Persistance.csproj	1	

  Error	NU1202	Package System.Numerics.Vectors 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	EMS.Persistance	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Persistance\EMS.Persistance.csproj	1	

Error	NU1202	Package System.Buffers 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Buffers 4.4.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	EMS.ApplicationCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.ApplicationCore\EMS.ApplicationCore.csproj	1	

Error	NU1202	Package System.Numerics.Vectors 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	EMS.ApplicationCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.ApplicationCore\EMS.ApplicationCore.csproj	1	

  Error	NU1202	Package Microsoft.AspNetCore.JsonPatch 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.JsonPatch 2.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.Extensions.ObjectPool 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.ObjectPool 2.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Protocols.OpenIdConnect 2.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Protocols.OpenIdConnect 2.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.CodeAnalysis.CSharp 2.3.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.CodeAnalysis.CSharp 2.3.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.CodeAnalysis.Common 2.3.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.CodeAnalysis.Common 2.3.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package SQLitePCLRaw.bundle_green 1.1.7 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package SQLitePCLRaw.bundle_green 1.1.7 supports: wp8 (WindowsPhone,Version=v8.0)	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Clients.ActiveDirectory 3.14.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Clients.ActiveDirectory 3.14.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Protocols 2.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Protocols 2.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package System.IdentityModel.Tokens.Jwt 5.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.IdentityModel.Tokens.Jwt 5.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Tokens 5.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Tokens 5.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Logging 1.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Logging 1.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.CodeAnalysis.CSharp.Workspaces 2.3.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.CodeAnalysis.CSharp.Workspaces 2.3.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package NuGet.Frameworks 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package NuGet.Frameworks 4.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	
Error	NU1202	Package Microsoft.CodeAnalysis.Workspaces.Common 2.3.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.CodeAnalysis.Workspaces.Common 2.3.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	
-----------------------------------------------------------------------------------------------------------------------
Ref 3 after caches cleared
----------------------------------------------------------------------------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package System.Numerics.Vectors 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	EMS.Domain	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Domain\EMS.Domain.csproj	1	

  Error	CS0006	Metadata file 'C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.ApplicationCore\bin\Debug\netstandard2.0\EMS.ApplicationCore.dll' could not be found	EMS.IntegrationTests	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.IntegrationTests\CSC	1	Active

  Error	CS0006	Metadata file 'C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Domain\bin\Debug\netstandard2.0\EMS.Domain.dll' could not be found	EMS.IntegrationTests	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.IntegrationTests\CSC	1	Active

  Error	CS0006	Metadata file 'C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Persistance\bin\Debug\netstandard2.0\EMS.Persistance.dll' could not be found	EMS.IntegrationTests	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.IntegrationTests\CSC	1	Active

  Error	CS0006	Metadata file 'C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.ApplicationCore\bin\Debug\netstandard2.0\EMS.ApplicationCore.dll' could not be found	EMS.UnitTests	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.UnitTests\CSC	1	Active

  Error	CS0006	Metadata file 'C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Domain\bin\Debug\netstandard2.0\EMS.Domain.dll' could not be found	EMS.UnitTests	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.UnitTests\CSC	1	Active

  Error	NU1202	Package Microsoft.AspNetCore.JsonPatch 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.JsonPatch 2.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.Extensions.ObjectPool 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.ObjectPool 2.0.0 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Protocols.OpenIdConnect 2.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Protocols.OpenIdConnect 2.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.CodeAnalysis.CSharp 2.3.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.CodeAnalysis.CSharp 2.3.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.CodeAnalysis.Common 2.3.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.CodeAnalysis.Common 2.3.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package SQLitePCLRaw.bundle_green 1.1.7 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package SQLitePCLRaw.bundle_green 1.1.7 supports: wp8 (WindowsPhone,Version=v8.0)	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Clients.ActiveDirectory 3.14.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Clients.ActiveDirectory 3.14.1 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Protocols 2.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Protocols 2.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package System.IdentityModel.Tokens.Jwt 5.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.IdentityModel.Tokens.Jwt 5.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Tokens 5.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Tokens 5.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package Microsoft.IdentityModel.Logging 1.1.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.IdentityModel.Logging 1.1.4 does not support any target frameworks.	EMS.WebCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.WebCore\EMS.WebCore.csproj	1	

  Error	NU1202	Package System.Buffers 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Buffers 4.4.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	EMS.Persistance	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Persistance\EMS.Persistance.csproj	1	

  Error	NU1202	Package System.Numerics.Vectors 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	EMS.Persistance	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Persistance\EMS.Persistance.csproj	1	

  Error	NU1202	Package System.Buffers 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Buffers 4.4.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	EMS.ApplicationCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.ApplicationCore\EMS.ApplicationCore.csproj	1	

  Error	NU1202	Package System.Numerics.Vectors 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	EMS.ApplicationCore	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.ApplicationCore\EMS.ApplicationCore.csproj	1	

  Error	NU1202	Package System.Buffers 4.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Buffers 4.4.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	EMS.Domain	C:\Users\liudm\Downloads\CORE\Core_2_DI\Good\Employee-Management-System-master\EMS.Domain\EMS.Domain.csproj	1

**Comment by PeterJD** [comment]
May have solved these errors, all reference needed to be removed nuget cache cleaned 
then re-assign reference seems to have revolved my issue. 
But the question is why?
Might be
Nuget manager needs improving

**Comment by karelz** [comment]
Are you able to reproduce the same problem on more than 1 machine?
Did you try to chop off parts of the project to create small repro that you could share with us?

**Comment by PeterJD** [comment]
Hi Karel Zikmund
Not able to reproduce on other PC, my thinking on this subject is more to do with references being corrupted in some way, may be nuget is failingto re-attach (restore) references correctly.
Just Solved the issue
WOW what triggered that memory, Zip files will report path or file is to long; so not able to zip the file
Moved solution to root directory C:\
Only reported one error
Error Could not find a part of the path 'C:\Users\liudm\.nuget\packages\microsoft.aspnetcore.dataprotection.abstractions\2.0.3\microsoft.aspnetcore.dataprotection.abstractions.2.0.3.nupkg'.any quick answer for the above error.
How can something so unrelated cause such a waste of time
My folder structure was not that long, but for VS or nuget were, well am AP and should remember little things can cause a lot of painThanks for your time
Kind regardsPeter
PS only checked one solution



On 27 Nov 2018, at 17:10, Karel Zikmund <notifications@github.com> wrote:

Are you able to reproduce the same problem on more than 1 machine?
Did you try to chop off parts of the project to create small repro that you could share with us?

**Comment by karelz** [comment]
I still don't understand what exactly happened. Can you distill a repro? Maybe there is something we can improve ...

**Comment by PeterJD** [comment]
Hi
Yes will do all you need to do is create a number of sub-directories, place solution in last sub-directories.Increase sub-directories until references fail
I will send my directory structure tomorrow
C:\sub-directories\sub2\sub3\sub4\sub5\sub6\sub7\solution.sln
Peter

    On Tuesday, 27 November 2018, 20:07:26 GMT, Karel Zikmund <notifications@github.com> wrote:  
 
 
I still don't understand what exactly happened. Can you distill a repro? Maybe there is something we can improve ...

**Comment by karelz** [comment]
If you can narrow it down to a small repro and info how long the directory have to be, that would be very helpful.

**Comment by PeterJD** [comment]
Look in the error messages I sent you the directory  are listed there

    On Tuesday, 27 November 2018, 21:47:17 GMT, Karel Zikmund <notifications@github.com> wrote:  
 
 
If you can narrow it down to a small repro and info how long the directory have to be, that would be very helpful.

**Comment by karelz** [comment]
I am not sure which error message you mean. Can you please point me to the exact one, that will be extremelly helpful.

**Comment by PeterJD** [comment]
Hi
Yes will do all you need to do is create a number of sub-directories, place solution in last sub-directories.Increase sub-directories until references fail
I will send my directory structure tomorrow
C:\sub-directories\sub2\sub3\sub4\sub5\sub6\sub7\solution.sln
Peter



On 27 Nov 2018, at 20:07, Karel Zikmund <notifications@github.com> wrote:

I still don't understand what exactly happened. Can you distill a repro? Maybe there is something we can improve ...

**Comment by karelz** [comment]
No more action is needed, closing.
If there is specific information how we can improve our tooling to be more resilient for long paths, please let us know. Thanks!

**Comment by PeterJD** [comment]
Hi you should specify that there is such an issue 
Took me a very long time to figure this out
Some project are big and this may cause a lot of issues

**Comment by rambotech** [comment]
If an app is running when a NuGet package reference is changed, or even when the build process runs with a thread not closed from an execution of the app, the output from either can causes directories to be cascaded under the existing directories.  This may be from the VS code not honoring a file/folder lock by the OS.
