### ISSUE TITLE
NU1605: Detected package downgrade: Xamarin.Forms from 3.3.0.912540 to 2.5.0.280555. Reference the package directly from the project to select a different version.   App3.Android -> App3 -> Xamarin.Forms (>= 3.3.0.912540) 

### ISSUE THREAD

**Issue by GanesanRengasamy** [dotnet/core#2083]
Hi All,

I have tried to downgrade the Xamarin.Forms NuGet package in the Xamarin NetStandard project. But I have faced the below issue. 

NU1605: Detected package downgrade: Xamarin.Forms from 3.3.0.912540 to 2.5.0.280555. Reference the package directly from the project to select a different version. 
 App3.Android -> App3 -> Xamarin.Forms (>= 3.3.0.912540) 

NU1605: Detected package downgrade: Xamarin.Forms from 2.5.1.527436 to 2.5.0.280555. Reference the package directly from the project to select a different version.

Could you please suggest me to resolve this problem?

**Comment by karelz** [comment]
@rrelyea can you please help route this issue?

**Comment by GanesanRengasamy** [comment]
@rrelyea  Could you please suggest me to resolve this issue?

**Comment by rrelyea** [comment]
also, we have warning/error documentation that may help explain ways to address: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605

**Comment by Redth** [comment]
https://github.com/xamarin/xamarin.forms would be a good place to post the issue, and hopefully provide a bit more info/context around the errors, but it sounds like you may need to add something like this to your project(s):

```
<PackageReference Include="Xamarin.Forms" Version="3.3.0.912540" />
```

**Comment by karelz** [comment]
@GanesanRengasamy can you please post your question on the recommended Xamarin repo?

Thanks @rrelyea for your advice!

**Comment by karelz** [comment]
@GanesanRengasamy your report mentions Android and Xamarin. The conclusion is that it is specific to Xamarin.Forms package specifically, so that's why starting there might be best.
If you have evidence it is not specific to that package or to Xamarin TFM, please provide that info and we can re-evaluate.

**Comment by Adrian93Box** [comment]
I am having a similar issue too and I need a solution. I'm guessing you guys want to move his question because no one here knows the answer? Has it been resolved elsewhere?

**Comment by reesaam** [comment]
> Hi All,
> 
> I have tried to downgrade the Xamarin.Forms NuGet package in the Xamarin NetStandard project. But I have faced the below issue.
> 
> NU1605: Detected package downgrade: Xamarin.Forms from 3.3.0.912540 to 2.5.0.280555. Reference the package directly from the project to select a different version.
> App3.Android -> App3 -> Xamarin.Forms (>= 3.3.0.912540)
> 
> NU1605: Detected package downgrade: Xamarin.Forms from 2.5.1.527436 to 2.5.0.280555. Reference the package directly from the project to select a different version.
> 
> Could you please suggest me to resolve this problem?

The Packages Versions of Android and iOS Projects remain! I don't know why!
You can go to the Android and iOS Project Root Folder, which couldn't be seen in the Solution Explorer in the VS, So you should modify it by Notepad. You will see the Previous versions, edit them to the new desired version.
