### ISSUE TITLE
where to get .NET core 3

### ISSUE THREAD

**Issue by apobekiaris** [dotnet/core#2087]
There are projects here already using .NET Core 3. Where they get it? I couldn't discover a download url

**Comment by lindexi** [comment]
[dotnet/core-setup: Installer packages for the .NET Core runtime and libraries](https://github.com/dotnet/core-setup#daily-builds )

**Comment by karelz** [comment]
Also linked from README.md of this repo: https://github.com/dotnet/core/#net-core-releases-and-daily-builds
