### ISSUE TITLE
'sudo apt-get install dotnet-dev-1.0.0-preview2-003121'  fail

### ISSUE THREAD

**Issue by yajore** [dotnet/core#209]
下列软件包有未满足的依赖关系：
 dotnet-dev-1.0.0-preview2-003121 : 依赖: dotnet-sharedframework-microsoft.netcore.app-1.0.0 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系

**Comment by blackdwarf** [comment]
@yajore this issue has been opened on the dotnet/cli repo at dotnet/cli#3855. Closing this one as a duplicate. Please refer to the other issue.
