### ISSUE TITLE
Is there support for appsettings.JSON transforms? similar to XML config file transformations

### ISSUE THREAD

**Issue by aberbegall** [dotnet/core#2095]
# Issue Title
I'm not able to make the content of appsettings.json from Nuget package to be transformed in .NET Core project.

# General
I generate a Nuget package (.NET Standard library) which contains a default appsettings.json. 
If I try to add that package to my .NET Core App the file content is being replace instead of transformed or merged. 

With .NET FW I was able to use web.config transformations, as described [here](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations).

Is there a way to achieve that in .Net Core?

Connected issue:
https://github.com/NuGet/docs.microsoft.com-nuget/issues/1063

Thank you

**Comment by Eilon** [comment]
This issue was moved to aspnet/Extensions#796
