### ISSUE TITLE
Why there are different SDK 2.2 binaries packages between two download links

### ISSUE THREAD

**Issue by chawyehsu** [dotnet/core#2105]
**dotnet-sdk-2.2.100-win-x64.zip**:
> https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.2.100/dotnet-sdk-2.2.100-win-x64.zip
> SHA512: 87776c7124cd25b487b14b3d42c784ee31a424c7c8191ed55810294423f3e59ebf799660864862fc1dbd6e6c8d68bd529399426811846e408d8b2fee4ab04fe5

> https://download.visualstudio.microsoft.com/download/pr/02a78e5a-3e7b-4d7e-a730-b46c9f551346/6dae57a34f649095d745acedb773d75f/dotnet-sdk-2.2.100-win-x64.zip
> SHA512: 950dc685294c6423438ba5b38d444c08e492e25a630a552cb5d3a170775ed6e6247ea8c06e6b1c26df90e91e3b9041e87e93db2a59349b814f6b2cfba59629a5

**dotnet-sdk-2.2.100-win-x86.zip**:
> https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.2.100/dotnet-sdk-2.2.100-win-x86.zip
> SHA512: 03bcc252839ef2d07d8f6a860afdbceb5944721b445f48a9a605b4d6f0b22c5ca0e0157f73b1cd09c0efd792fd5209fb118afba8ab8d597a0e547a6e9f6de7fb

> https://download.visualstudio.microsoft.com/download/pr/84beb25f-e3ad-4fde-b90d-907d499d3dfc/2cadffd93faaf3c6e5b9b8f8c1767180/dotnet-sdk-2.2.100-win-x86.zip
> SHA512: f007b3912f265f5ca5397cbb7aa55fc2d34788adb77cac53b45643d76088c01e47a70576417957de75ba4543be298dbc8c31dc82a33aefdae9490f6e64c9ab6a

**Comment by karelz** [comment]
@vivmishra @leecow can you please take a look / comment?
