### ISSUE TITLE
Incorrect documentation in linker-instructions.md

### ISSUE THREAD

**Issue by stefanov-stefan** [dotnet/core#2108]
There is email address listed at the end of this article: https://github.com/dotnet/core/blob/master/samples/linker-instructions.md which no longer seems to be working.

**Comment by karelz** [comment]
@RussKeldorph can you please help route it to the right team? cc @BruceForstall

**Comment by RussKeldorph** [comment]
@sbomer @jeffschwMSFT

**Comment by stefanov-stefan** [comment]
Yep I had, and i logged it as issue: https://github.com/dotnet/winforms/issues/210 

Thanks.

**Comment by jeffschwMSFT** [comment]
The address is active again.  Sorry for the inconvience.
