### ISSUE TITLE
An assembly specified in the application dependencies manifest (....deps.js on) was not found

### ISSUE THREAD

**Issue by Kajirinn** [dotnet/core#2111]
This is my first time using a raspberry pi and I'm trying to get a Discord bot using discord.net to work on said pi. I've followed a few tutorials and got a quick "Hello World!" working using .net core. However, upon trying the same thing: Writing the app in visual studio, sharing the netcoreapp2.0 using ssh I'm getting this errror;

```
dotnet dc_bot.dll

Error:
  An assembly specified in the application dependencies manifest (dc_bot.deps.js on) was not found:
    package: 'Discord.Net.Commands', version: '1.0.2'
    path: 'lib/netstandard1.1/Discord.Net.Commands.dll'
```

This sounds fairly logical as I've installed a nuget package containing discord.net. However, I have no idea how to fix this; I'm sorry if this isn't the right place to ask this but I have no clue where else to post it...

Thanks for taking your time reading through this.

**Comment by Kajirinn** [comment]
I figured out that you have to install nuget yourself. After I installed nuget and attempted to download Discord.NET I got this error:

```
sudo nuget install Discord.NET

Attempting to resolve dependency 'Discord.Net.Core (≥ 1.0.2)'.
'Discord.Net.Core' already has a dependency defined for 'NETStandard.Library'.
```

No clue what's wrong..

**Comment by karelz** [comment]
@rrelyea any idea where to route it?

**Comment by rrelyea** [comment]
Generally, this is how this kind of thing works:

Put a packagereference in you csproj
Dotnet build
   This will do an implicit restore, and put any packagereference sand their transitive dependencies into the global package folder on the dev box. This also builds a deps.json file in the bin dir.

Dotnet publish 
    This is probably necessary to take all the binaries from the dev machine and create a directory full of the entire set of files that need to be copied to the other computer (the pi?)

Then run the app.

You should never need to do a nuget install or restore on the execution computer...just the dev box.

Given that info, once they try that, or give reasons why that may not make sense, maybe we’ll know where to route.

**Comment by Kajirinn** [comment]
Right, so all I had to do was publish it; that indeed fixed it. Sorry for that; thanks for your time!
