### ISSUE TITLE
.NET Core 3.0 - WPF, the type 'x:Static' was not found

### ISSUE THREAD

**Issue by Symbai** [dotnet/core#2113]
Trying to port an existing WPF app to .NET Core 3.0 using VS 2019 Preview. I created a new WPF project using .NET core then imported my existing files, so far everything is fine. But some XML files have errors about:

`XLS0414	The type 'x:Static' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.`

Where x is being defined as:

`xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"`

Example where I'm using this:

`ToolTip="{x:Static properties:Resources.PlayButtonTooltip}"`

Example project:
[CoreTest.zip](https://github.com/dotnet/core/files/2651359/CoreTest.zip)

**Comment by vivmishra** [comment]
cc: @vatsan-madhavan ; @amit-kabra

**Comment by Symbai** [comment]
I'm closing this as problem is being addressed in WPF repo https://github.com/dotnet/wpf/issues/117#
