### ISSUE TITLE
How to get number of connections  in asp.net core 

### ISSUE THREAD

**Issue by akaylh** [dotnet/core#2115]
I Want to get number of connections  in asp.net core.

**Comment by karelz** [comment]
Number of incomming or outgoing connections?
It sounds more like a task for monitoring tool, or OS tool

**Comment by akaylh** [comment]
I found it :https://stackoverflow.com/questions/49798923/total-hit-visitor-counter-in-asp-net-core-mvc-application, May solve my problem。

Thanks @karelz
