### ISSUE TITLE
.NET Core 2.2 deployment to Azure App Service

### ISSUE THREAD

**Issue by jansokoly** [dotnet/core#2120]
After every stable .NET Core release, it's pain to figure out if the deployment of that version to App Service has finished. The only way (at least I know of) being - deploy upgraded app and see if it runs or breaks.

https://github.com/Azure/app-service-announcements seemed like the place to look for that info for some time, but it looks neglected at the moment. They do remind everybody not to create issues, but don't create them themselves.

Can't we find some reasonable way where would you publish info about latest versions of .NET deployed to App Service?

**Comment by karelz** [comment]
@DamianEdwards @glennc @Eilon is it something you can follow up on or route?

**Comment by Eilon** [comment]
@muratg - any thoughts on this?

**Comment by karelz** [comment]
I already got the right team on internal email thread, thanks for help @Eilon @muratg!

**Comment by donma** [comment]
got the same problem  T.T.

**Comment by karelz** [comment]
Per offline discussion, it will be announced once the roll out is finished.
@shirhatti answered similar question on the blog post: https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-2-2/ (see discussion comments)
>The Azure App Service deployment for the ASP.NET Core Module is **currently in-process** and we expect to be generally available across all regions before the **end of December**.

I am not sure if Azure App Service team plans to do just a blog post, or post on https://github.com/Azure/app-service-announcements. I let that decision and its communication to their team.
If you feel like that particular channel is neglected (I don't have enough background to have opinion here), I would suggest to send them the feedback (naively maybe via creating issue, although as you point out they may not like it, or via other appropriate channels - although I don't know what they would be).

Hope it helps!

**Comment by karelz** [comment]
FYI: https://github.com/Azure/app-service-announcements/issues/151 - .NET Core 2.2 availability on App Service.
