### ISSUE TITLE
I did not manage to convert an old project to netcore3 for wpf yet.

### ISSUE THREAD

**Issue by taori** [dotnet/core#2124]
I originally posted my problem [here](https://developercommunity.visualstudio.com/content/problem/400819/converting-net40-wpf-project-to-netcore3-issues.html) with screenshots, but got sent to post it here.

Essentially my csharp files are being mentioned in the error list, saying how they contain an error at the root level of the resx file. This is rather odd.

Is there something i need to keep in mind when converting projects manually? Is there tooling i can execute on an old project to run an update?

I am using netcore3.0 preview 1.

**Comment by dasMulli** [comment]
Are you building from inside VS or using the `dotnet` CLI?
if you're using the CLI, could you try to rebuild your project using `msbuild -t:Rebuild` from the VS 2019 developer command prompt?
some resx related features still only work from the "full framework MSBuild" shipped with VS

**Comment by karelz** [comment]
@taori are you able to track it down to a standalone repro?
This seems to be specific to your project ...

**Comment by taori** [comment]
@dasMulli building from within VS 2019 preview 

now i got it to execute but it won't start properly. Not sure why the error messages are gone now. Yesterday i cleaned, rebooted and they still would not go away...

I got this when starting from VS:
Das Programm "[5096] Desktop.exe" wurde mit Code -532462766 (0xe0434352) beendet.
Das Programm "[5096] Desktop.exe: Programmablaufverfolgung" wurde mit Code 0 (0x0) beendet.

Building with your command does work.

Executing it with dotnet run (since vs didn't launch properly) resulted in this:
![image](https://user-images.githubusercontent.com/5545184/49680161-dc6af880-fa91-11e8-8eb3-6df5314d4643.png)

**Comment by taori** [comment]
Ok - i guess this explains why this is such an edgecase - i am referencing a .net40 class library which contains a xaml file. While i can obviously move that around, i guess that is still worth knowing, in case other ppl use user controls from an external project?

**Comment by taori** [comment]
@karelz  Interesting. That error does not happen if i strip down a sample to the bare essentials. Program just starts fine in isolation without errors.

**Comment by taori** [comment]
I have removed the Xaml file - This revealed the actual reason(one of them? still progressing) the application won't launch properly:

![image](https://user-images.githubusercontent.com/5545184/49680658-4a65ee80-fa97-11e8-9676-0e97611fb8aa.png)

**Comment by karelz** [comment]
Weird, why would that happen? Can you get callstack? (in textual form please)
cc @bartonjs

**Comment by taori** [comment]
This i experienced in the process of upgrading this:

- At some point of the application there is a Process.Start(filepath) to a log file if all other logging attempts fail, which threw the following exception
```
The specified executable is not a valid application for this OS platform. ->    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
```

- There was a reference to another project, which was set to application as well, which prevented the application from executing properly.
- Removing that reference + saving the project did not suffice - i had to restart VS for the build system to fully forget about that reference.
- @dasMulli at this time it appears devconsole + msbuild -t:Rebuild was more useful in figuring out what's preventing builds than VS. At least i found out what's wrong there immediately.
- some license validation crashed the application. If i recall correctly in debug mode that would usually prompt VS to highlight the error source at the call site, instead of terminating the process. (Not 100% sure about it in this case since years have passed since i had to setup the license for it)
- missing type: Could not load type 'System.Data.OleDb.OleDbConnection' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by taori** [comment]
@karelz the original code was
`var desCrypto = (DESCryptoServiceProvider)DES.Create()`
which after turning it into
`var desCrypto = new DESCryptoServiceProvider()`
worked fine - i guess the API simply changed, so that isn't an issue anymore.

**Comment by taori** [comment]
Oh well. After doing a little bit of research it looks like i won't be the only one who will be blocked by the OleDb dependency. I wish ppl stopped using excel + access instead of real databases. Thanks for the support though. Feel free to close this once you are done picking up the feedback i guess (if you're interested in it, that is. Just thought i'd try preview1 on this legacy application to finally move past net40 on that project)

**Comment by taori** [comment]
one `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` later:

```
'The invocation of the constructor on type 'Telerik.Windows.Controls.RadRibbonBackstage' that matches the specified binding constraints threw an exception.' Line number '19' and line position '18'. ->    at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
```

**Comment by karelz** [comment]
@taori what is the remaining problem here? Do you have isolated minimal repro we can look at?

**Comment by taori** [comment]
@karelz 
now i'm getting this when attempting to execute dotnet run:

![grafik](https://user-images.githubusercontent.com/5545184/53673690-67225480-3c89-11e9-9fc5-6906c691ab4d.png)

**Comment by karelz** [comment]
Do you have isolated repro we can investigate?

**Comment by taori** [comment]
@karelz Sorry for the delay. I'm afraid i no longer have access to the source code in question to reproduce the issue.

**Comment by karelz** [comment]
OK, let's close it then.
