### ISSUE TITLE
CLI-Created Web Projects All have the Same Project ID For User Secrets

### ISSUE THREAD

**Issue by MisterJames** [dotnet/core#213]
It seems that all projects - even on different machines - are using this same GUID when created from the CLI: `0799fe3e-6eaf-4c5f-b40e-7c6bfd5dfa9a`, resulting in a shared set of user secrets. The userSecretsId for all project.json files created is `aspnet-WebApplication-0799fe3e-6eaf-4c5f-b40e-7c6bfd5dfa9a`.

These projects are created with `dotnet new -t web`.

**Comment by blackdwarf** [comment]
@MisterJames there is already an issue in the CLI repo tracking this in dotnet/cli#3617. Will close this one as a duplicate.
