### ISSUE TITLE
Issues compiling after installing SDK 2.2

### ISSUE THREAD

**Issue by SkinnySackboy** [dotnet/core#2130]
Hi,

Having already been using .NET Core 2.0 and 2.1 in production already, earlier this week we decided to start upgrading to .NET Core 2.2. On our machines (i.e. in Visual Studio), so far so good - we installed the SDK without having modified any projects and everything still works as it always used to.

On our TeamCity agents, we decided to do the same as we have in the past, i.e. to install the .NET Core 2.2 SDK. This is where the interesting problems start. Suddenly, our existing solutions which contain a .NET Core 2.1 project (event unit tests) started failing with the following error:

**error NU1202: Package Microsoft.NETCore.App 2.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.NETCore.App 2.2.0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)**

This does not happen from Visual Studio - it only seems to happen when using the dotnet CLI. It gets even more interesting as if we first compile from Visual Studio and subsequently run dotnet build from the command line, it all works. If however you delete the bin/obj folders, dotnet build from the command line fails with the previous error.

Has anyone else come across this issue, as I was not expecting the mere presence of the 2.2 SDK to suddenly cause all previous builds still targeting .NET Core 2.1 to start failing?

Thanks in advance

**Comment by karelz** [comment]
.NET Core is side-by-side. You need to either upgrade your project to latest version (netcoreapp2.2), or keep appropriate version installed (netcoreapp2.1 in your case).

**Comment by SkinnySackboy** [comment]
The thing is we did keep the old SDK that was previously working installed - the thing that caused our projects to start failing is the additional installation of the .NET Core 2.2 SDK. We didn't uninstall the previous SDKs.

For sure upgrading the projects fixes this problem as I tried it, but unfortunately I cannot force all other teams to upgrade simultaneously. Despite having both SDKs installed on our Team City agents, projects still targeting netcoreapp2.1 are failing with this error.

**Comment by karelz** [comment]
Installing additional SDK should not break build of your previously-building apps. That is weird.
Are you able to reproduce it with HelloWorld app? Or is it specific to your project?
Does it repro on more than 1 machine?
If we have a repro, we can take a look ...

cc @nguerrera @dsplaisted

**Comment by SkinnySackboy** [comment]
This is indeed happening with all our projects previously targeting netcoreapp2.1 and on each machine where we installed the 2.2 SDK. Tomorrow I will create a test project to reproduce the issue.

On the runtime side we have had zero issues installing things side-by-side, so this is only an issue at compile time outside of Visual Studio.

**Comment by SkinnySackboy** [comment]
@karelz Today we did some more investigation and realised that this problem had absolutely nothing to do with the code itself. We create a brand new solution in Visual Studio, containing a single project targeting netcoreapp2.1 with no code inside it.

After multiple tests, we realised that it was succeeding/failing depending on which versions of the 2.1.x SDK was installed on a machine. Here's what we found. If you compile on a machine with the following SDKs installed, it works:
**2.1.200 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]**

If you now install the 2.2 SDK it fails with the error in the original post:
**2.1.200 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.2.100 [C:\Program Files\dotnet\sdk]**

If we now install the 2.1.500 SDK, magically it works again, with zero code changes:
**2.1.200 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.2.100 [C:\Program Files\dotnet\sdk]**

So it looks to me (apologies if this is obvious or commonly known) as though there is some issue with some 2.1.x versions prior to 2.1.500, which only manifests itself once you install the 2.2.x SDK or above.

**Comment by nguerrera** [comment]
> .NET Core is side-by-side

Indeed, but `dotnet build` will use latest SDK unless you have a global.json file specifying an older version.

> You need to either upgrade your project to latest version (netcoreapp2.2), or keep appropriate version installed (netcoreapp2.1 in your case).

This isn't exactly the case. Latest SDK can _build_ projects targeting older versions of .NET Core. To _run_ the output (if framework-dependent), you need the older runtimes installed. That can either be through having the full older SDK installed SxS or only the older runtime.

> Installing additional SDK should not break build of your previously-building apps. That is weird.

It should not, but latest used by `dotnet` can come with a bug. :(

> So it looks to me (apologies if this is obvious or commonly known) as though there is some issue with some 2.1.x versions prior to 2.1.500, which only manifests itself once you install the 2.2.x SDK or above.

This is not obvious or commonly known. I am moving this issue to our repo to investigate further.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/cli#10466
