### ISSUE TITLE
3.0/releases.json missing root element

### ISSUE THREAD

**Issue by leecow** [dotnet/core#2131]
{
  "channel-version": "3.0",
  "latest-release": "3.0.0-preview1",
  "latest-release-date":"2018-12-04",
  "support-phase": "preview",
  "eol-date": "",
  "lifecycle-policy": "https://www.microsoft.com/net/support/policy",    
  "releases": 
  [
   ...
  ]
}

**Comment by vivmishra** [comment]
Fixed by #2135
