### ISSUE TITLE
Inconsistent/incorrect value provided for release-version in the 2.1 releases.json file

### ISSUE THREAD

**Issue by tristanbarcelon** [dotnet/core#2139]
# Issue Title
A change to 2.1 releases.json yesterday bucked the convention for releases.

# General

I wrote a script for enumerating dotnetcore assets by version and type (sdk, runtime, hosting bundle) and it produced an uncharacteristic value for runtime version that is not consistent with previous releases. This  only seems to affect [releases.json for 2.1](https://github.com/dotnet/core/blob/master/release-notes/2.1/releases.json) which was updated yesterday.  

![image](https://user-images.githubusercontent.com/5810165/49876845-32250500-fdf2-11e8-8430-1f0479909013.png)

Previous release entries were predicated by an update in the runtime or at least pegged to a runtime version. Thus, it is possible to have 2 or more sdk versions for the same runtime release. In yesterday's update, it is now possible to have a release with only an SDK component in it. Not only that, it introduces a runtime-version in the sdk object which is not present in previous releases of the sdk object. We would prefer a predictable pattern for parsing these json files or an enhanced install-dotnet.ps1 that can install sdk, runtime, or hosting bundle.

I have a [related but general issue](https://github.com/dotnet/core/issues/2090) posted as well.

**Comment by leecow** [comment]
Thanks @tristanbarcelon . I left a longer reply in the other issue. As mentioned there it is possible to have an SDK release which includes previously released runtimes. Discussion in https://github.com/dotnet/core/issues/2134 to work through solutions.

cc @vivmishra
