### ISSUE TITLE
AddJsonFile throws invalid directory name when optional is true

### ISSUE THREAD

**Issue by dankellett** [dotnet/core#214]
`var builder = new Microsoft.Extensions.Configuration.ConfigurationBuilder()`
`.SetBasePath(env.ContentRootPath)`
`.AddJsonFile(@"C:/myDirectory/mySub/appsettings.json", optional: true)`

When adding a configuration file during app startup, the above code will throw an exception if the "C:/myDirectory/mySub/" does not exist. Since this is set as an optional file, the directory should not need to exist.

**Comment by svick** [comment]
`AddJsonFile` is in the [aspnet/Configuration](https://github.com/aspnet/Configuration) repository. I think you should report this issue there and close it here.

**Comment by dankellett** [comment]
Thanks, will do.
