### ISSUE TITLE
Centos7.3 Cannot get required symbol EC_KEY_set_public_key_affine_coordinates from libssl

### ISSUE THREAD

**Issue by xinschen** [dotnet/core#2143]
Centos7.3 Cannot get required symbol EC_KEY_set_public_key_affine_coordinates from libssl
openssl info
OpenSSL 1.0.2k-fips  26 Jan 2017

Referenced to ”https://github.com/dotnet/core/issues/1930" and Upgrade openssl to version 1.1.0g，but did not solve

dotnet --info
![image](https://user-images.githubusercontent.com/26127685/49913316-2e63b200-fec8-11e8-95d3-31c34a84949e.png)

dotnet new  -h
![image](https://user-images.githubusercontent.com/26127685/49913365-58b56f80-fec8-11e8-83e4-313539d07511.png)

**Comment by karelz** [comment]
@tmds @bartonjs can you please help route the question?

**Comment by karelz** [comment]
@bartonjs ping?

**Comment by bartonjs** [comment]
@xinschen .NET Core 2.1 doesn't use OpenSSL 1.1, so updating the 1.1 package wouldn't do anything.  Updating to the newest openssl-libs 1.0 package would be the thing to try; or to move from CentOS 7.3 (12 Dec 2016) to 7.5 (10 May 2018) or 7.6 (3 Dec 2018).

**Comment by xinschen** [comment]
@bartonjs  Already upgraded, but not resolved
![image](https://user-images.githubusercontent.com/26127685/50260599-a3dcfe80-0443-11e9-9e78-6332bda3b3ad.png)

**Comment by karelz** [comment]
@bartonjs can you please help troubleshoot it further or route it appropriately? Thanks!

**Comment by karelz** [comment]
@bartonjs ping

**Comment by omajid** [comment]
AFAIK, no current stable/public release of .NET Core supports OpenSSL 1.1. So when `openssl version -a` says `OpenSSL 1.1.1a` or when `ldd` says `libssl.so.1.1`, that's not very helpful for fixing this issue.

We want to know what `rpm -q openssl` and `rpm -q openssl-libs`. If that says "1.1", we need to remove those packages and install (actually downgrade to) OpenSSL 1.0 on CentOS. An `strace dotnet new console` would be use after OpenSSL 1.0 has been installed to find out what fails and when.

**Comment by karelz** [comment]
Looks like we do not have actionable information, closing.
Please let me know if I made a mistake. Thanks!

**Comment by omajid** [comment]
Just as an FYI: recent releases of .NET Core 2.x should support OpenSSL 1.1 (as well as OpenSSL 1.0) out of the box. If this issue still occurs, please re-open this bug.
