### ISSUE TITLE
How can run WPF in macOS?

### ISSUE THREAD

**Issue by William201807** [dotnet/core#2144]
Run WPF in macOS.
I want to run WPF in macOS, but run error is "It was not possible to find any compatible framework version The specified framework 'Microsoft.WindowsDesktop.App', version '3.0.0-alpha-27128-4' was not found", I can't find this runtimes in macOS version.

**Comment by William201807** [comment]
reopened

**Comment by jfbueno** [comment]
Basically, you can't. 

Although .NET Core 3 supports WPF, WinForms and UWP XAML they're only for Windows. You can read about this topic in [.NET Blog](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/).

I don't really know if there are any hacks that you can do to get WPF running on MacOS, but I suppose this is not the place to talk about it.

**Comment by karelz** [comment]
@William201807 the blog post and [WPF repo](https://github.com/dotnet/wpf/blob/master/README.md) both contain information, that WPF is Windows-only. Currently there are no plans to make it cross-platform. See https://github.com/dotnet/wpf/issues/48

**Comment by chrisfcarroll** [comment]
For those of us coming to this page from a websearch for "WPF on MacOs" I guess what we'd like is a pointer to good options for https://www.bing.com/search?q=netcore+cross+platform+gui

I appreciate that this isn't what dotnet/core/issues is for, but this page now ranks high

**Comment by Bron-Code** [comment]
I had the same problem with WPF and found a solution of sorts. I ended up using Unity to create a C# UI interface that works on MacOS, Windows, and more. Here is a basic tutorial I made on how to do it: https://medium.com/@A51/how-to-easily-develop-a-c-ui-app-that-works-on-mac-and-windows-8eaf32ea0ed6. I am happy to help with any questions I can.

**Comment by chrisfcarroll** [comment]
Yes, good point. I guess MAUI is due to be our way forwards but really, Unity has been working for years and let's face it, most games are more demanding than LoB apps.
