### ISSUE TITLE
GetBuiltProjectOutputGroup task ignores outputName (SDK rc2)

### ISSUE THREAD

**Issue by kovalikp** [dotnet/core#215]
`GetBuiltProjectOutputGroup` task (from c:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Tasks.dll assembly) ignores `outputName` defined in `project.json`. This means that, any build system that uses `BuiltProjectOutputGroup` target to collect output of the project, will not be able to find result assembly.
**tested on:**
.NET Core SDK for Windows-rc2
**example:** 
msbuild ProjectName.xproj /t:BuiltProjectOutputGroup /v:diag
**project.json:**
```
{
  ...
  "buildOptions": {
    "outputName": "OutputName"
  }
}
```
**result:**
```
  Output Item(s):
      _BuiltProjectOutputGroupOutput=
          C:\...\ProjectName\bin\Debug\netstandard1.6\ProjectName.dll
```
**expected:**
```
  Output Item(s):
      _BuiltProjectOutputGroupOutput=
          C:\...\ProjectName\bin\Debug\netstandard1.6\OutputName.dll
```

**Comment by blackdwarf** [comment]
@kovalikp I believe this will be solved once we fully migrate over to msbuild in the tooling. You can read the ["Changes to project.json" blog post](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) for more context. I will close this issue. If you feel it is still needed, can you please open it up on dotnet/cli repo? Thanks!
