### ISSUE TITLE
MSTest Unit Test Generators

### ISSUE THREAD

**Issue by leo2d** [dotnet/core#2155]
Currently has an alternative for intellitest on .Net core? I have Visual Studio 2017 enterprise and need to generate many unit tests with MSTEST on .NET CORE apps. But... The plugins i have found only works with xUnit/NUnit  and Visual Studio intellitest  only works with .Net Framework.

**Comment by karelz** [comment]
It seems that the feature IntelliTest supports only .NET Framework: https://docs.microsoft.com/en-us/visualstudio/test/generate-unit-tests-for-your-code-with-intellitest?view=vs-2017
@leo2d can you please provide feedback directly to Visual Studio? https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017 ... that way it will find the right team faster.
cc @kendrahavens 

Closing as out of scope here.

**Comment by kendrahavens** [comment]
Thanks @karelz.

We are tracking adding Intellitest support for .NET Core on [developer community here](https://developercommunity.visualstudio.com/idea/359250/add-intellitest-support-for-net-corestandard.html). It is on the roadmap. (Please upvote if it's an important scenario to you. It does help us prioritize.)

Unfortunately, I don't have any recommendations for other .NET Core MSTest generation tools at this time.

**Comment by leo2d** [comment]
Thank you for the supporting.
