### ISSUE TITLE
I suggest to Create .net's "Spring Framework" by Microsoft.

### ISSUE THREAD

**Issue by codeex** [dotnet/core#2162]
# I suggest to Create .net's "Spring Framework" by Microsoft.

Because Dot Net Core Require Bussiness Framework to fly in the cloud world.

# General

Provide Framework 、Interface and Implement document, and then Many coder to implement this.

**Comment by karelz** [comment]
Look into ASP.NET Core - it has many parts of similar framework and other goodies.
