### ISSUE TITLE
30 Second pause when opening an NFS file for read or write 

### ISSUE THREAD

**Issue by Nanook** [dotnet/core#2164]
Tested on **dotnet core 2.2 and 3.0 pre 1** - **ARM32**

Hardware: **Odroid XU4Q**
OS: Ubuntu **18.04.1** LTS (Kernel 4.14.87-153 armv7l) 
NAS: **DLink 320L** with 2018 firmware

The NAS filesystems can be enumerated, but there is a 30 second pause when opening any and every subsequent file for read or write. I have not seen this pause with any other software. Even testing with .Net 4.5 and mono it's fast (well normal). Any non NAS paths work as expected also.

Each file pauses for 30 seconds. I've tried the static File Open methods as well as StreamReader etc too. They all do it. 

Example: File.WriteAllText("NasPathAndName", "Content"); //30 second hang

The mount command shows the mount as (masked IP): x.x.x.x:/mnt/HD/HD_b2 on /media/nas2 type nfs (rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,proto=tcp,timeo=14,retrans=2,sec=sys,mountaddr=x.x.x.x,mountvers=3,mountport=60319,mountproto=udp,local_lock=none,addr=x.x.x.x)

I've tried changing various values like the nfs version to 4 and locks etc. This mount output appears to always show no locks and nfsver 3. It's not the greatest NAS, but it's good enough for my needs.

Thanks.

**Comment by wfurt** [comment]
`strace -f -s 200 -e trace file dotnet XX`
Traditionally, I would look for any appearance of "sync" call. Some simple repro code would still be nice se I can get better idea what functions and calls are involved.

**Comment by wfurt** [comment]
The Activity.log does not have info I was looking for. It seems like the 'file' group has only subset of the system calls ;( Could you please re-run it with `strace -tt -f -s 200 -T -e trace=%file,%desc` 

I run the code fragment you posed and I see openat, fstat, flock, ftruncate, lseek, write, flock and close sequence. It takes 3-4 ms on my system. There is also some timezone processing but I'm not sure if that matters.

**Comment by Nanook** [comment]
I thought the timezone might have been the issue as I had noticed Mono had output the U.S. date format when calling ToString(). I checked the Language settings and the dialog had no format examples (dates, currency etc) and the dropdown lists were empty. I added English and set them all to British English, but it appears to have made no difference. I'm going to test that dotnet core has picked them up now. In the meantime here's the log, it looks a lot more detailed.

[hang2.log](https://github.com/dotnet/core/files/2696865/hang2.log)

Thanks.

**Comment by wfurt** [comment]
yes, locking seems to be the problem.  You can try to mount your volume with `nolock` option.
I don't know if there is any option to do IO without locking.
cc: @JeremyKuhne

**Comment by Nanook** [comment]
x.x.x.x:/mnt/HD/HD_b2 on /media/nas2 type nfs (rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,nolock,proto=tcp,timeo=14,retrans=2,sec=sys,mountaddr=x.x.x.x,mountvers=3,mountport=60319,mountproto=udp,local_lock=all,addr=x.x.x.x)

Is the result from **mount** after adding nolock. Same 30 second pause unfortunately.

**Comment by Nanook** [comment]
I'd be interested in knowing what people's opinions are of this. I feel like nolocks is bad and that I should be using locks. It's not too much of an issue for me as I mainly only use the NAS from this one system (which will be managing locks from itself).

It appears older NAS drives (NFS3?) don't support flock and lockf is preferred. I have very little experience with this so I thought I'd ask. Is this a bug? All my other apps and services (Plex, NGINX etc) all currently work with NAS side locking.

**Comment by wfurt** [comment]
cc: @janvorli I'm still not sure why the flock() would take so long to fail.

**Comment by karelz** [comment]
@wfurt @janvorli anything we can do here? Or is it external OS problem?

**Comment by wfurt** [comment]
I think observed problem is specific to particular OS/NAS combination. it is clear from the trace that we spent time in OS call and I don't think there is much we can do about it. If anything, the question is why do we lock in such trivial cases.  It would be nice if there is some way how to choose. Perhaps question for IO experts.

**Comment by JeremyKuhne** [comment]
We need to make the call or the feature just doesn't make any sense. Your current process may not care about locking the file but it should care about it being locked by some other process.

@stephentoub Do you have any context to add here?

I'll note that locking of files on *nix is a known mess. A few links for reference:

https://loonytek.com/2015/01/15/advisory-file-locking-differences-between-posix-and-bsd-locks/
http://0pointer.de/blog/projects/locking.html
http://nfs.sourceforge.net/ (search for flock)

**Comment by stephentoub** [comment]
> Do you have any context to add here?

Not really; like you say, we need to make the call, or else the FileShare is meaningless.

**Comment by karelz** [comment]
What's the next step here?
Can we close it?

**Comment by tmds** [comment]
Locking files is indeed a mess on Linux.
The OS doesn't check the permissions on read/write, and everything is left over to the applications. So non .NET Core applications won't respect the FileShare unless they are using the same APIs.
Maybe we can add an envvar that disables the locking.

@Nanook Maybe your NAS logs give some hint about why the locking is taking so long.

**Comment by karelz** [comment]
@JeremyKuhne what is your suggestion? Should we file CoreFX issue to improve it?

**Comment by karelz** [comment]
@JeremyKuhne ping?

**Comment by JeremyKuhne** [comment]
I don't think there is anything more we can do here. We need to lock. If a better locking feature in Unix shows up in the future we can certainly look into it.

**Comment by maraspin** [comment]
Experienced same issue. NFS V4 seems to have solved it - ref. https://unix.stackexchange.com/questions/1777/flock2-versus-fcntl2-over-a-nfs, see rjh reply
