### ISSUE TITLE
Kestrel returns 415 if Content-Type header isn't provided for GET calls

### ISSUE THREAD

**Issue by manish-panwar** [dotnet/core#2166]
# Issue Title

Kestrel in net core 2.2 returns 415 if Content-Type header isn't provided for GET call

# General

I am using .net core 2.2 and created a web api. When we make GET call with "Accept" header then Kestrel is  returning 415, it works fine if I pass the Content-Type header. In dotnet core 2.1.x it used to work fine even if I didn't pass Content-Type header. I am wondering what has changed in 2.2

Generally one shouldn't need to pass Content-Type header for GET call, and Accept header should be enough.

I hope this is the right place to raise this question. If not then if someone knows where I can raise this issue. Thanks a lot for your help!

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetCore#5707
