### ISSUE TITLE
developer communication channel availability

### ISSUE THREAD

**Issue by cdaringe** [dotnet/core#217]
hi all:

do we have a good irc/slack/gitter/chat-thing/whatever for devs to hang out, ask Qs, and bounce ideas off of each other?

if not, should/can we start one?  for instance [atom puts a link to their chat channel](https://github.com/atom/atom) right on the repo README.md, which is helpful.

it would be really great to have a go-to place for learning where the docs just aren't quite enough.  i'm a senior dev new to c#, and although MS has huge doc sets, it's often difficult to get pointer on the challenges i'm facing.

thx!

**Comment by akoeplinger** [comment]
There are gitter channels for each of the main repos: https://gitter.im/dotnet/corefx, https://gitter.im/dotnet/coreclr,https://gitter.im/dotnet/cli (those are mentioned in the READMEs)

Additionally there **a lot** of people in the ASP.NET/.NET Core community Slack: http://tattoocoder.com/aspnet-slack-sign-up 😄

**Comment by cdaringe** [comment]
Thanks!
