### ISSUE TITLE
Doesn't dotnet core verify the strong named assembly ?

### ISSUE THREAD

**Issue by foman** [dotnet/core#2173]
For example, assembly A and B(1.0) are both strong named, and A reference B(1.0). If B(1.0) is replaced by B(2.0) which is also signed, It still work, but In .netframework, it will throw exception.
Is this by design?

**Comment by karelz** [comment]
@jkotas @jeffschwMSFT is there any official high-level documentation about assembly loading differences between .NET Core and .NET Framework?
I couldn't find anything except specific documentation on AssemblyLoadContext, etc. -- which already assumes I know what to look for.

**Comment by karelz** [comment]
@jkotas @jeffschwMSFT ping post holidays ...

**Comment by karelz** [comment]
Thanks @jkotas! Closing as it is answered and docs are tracked in another issue ...
