### ISSUE TITLE
Fail to install dotnet core 2.2 on SLES 12

### ISSUE THREAD

**Issue by rtssrl** [dotnet/core#2174]
Following instructions at https://dotnet.microsoft.com/download/linux-package-manager/sles/runtime-current:

```
zypper install aspnetcore-runtime-2.2

Problem: nothing provides dotnet-host >= 2.2.0 needed by dotnet-hostfxr-2.2-2.2.0-1.x86_64
 Solution 1: do not install aspnetcore-runtime-2.2-2.2.0-1.x86_64
 Solution 2: break dotnet-hostfxr-2.2-2.2.0-1.x86_64 by ignoring some of its dependencies

```
Looks like dotnet-host-2.2 RPM is missing from https://packages.microsoft.com/sles/12/prod/

**Comment by karelz** [comment]
@rakeshsinghranchi @leecow can you take a look please and help route it?

**Comment by rakeshsinghranchi** [comment]
This issue was moved to dotnet/core-setup#4890
