### ISSUE TITLE
CoreCLR crash in SLES 11 SP3

### ISSUE THREAD

**Issue by FZ14** [dotnet/core#218]
Hi!
I try to install dotnet core in SUSE Linux Enterprise Server 11 SP3.

After installing dependencies I have an error, when I try execute command:
`dotnet --version`
or
`dotnet new`

### Failed to initialize CoreCLR, HRESULT: 0x80131500.

[DotnetCoreVersionTrace.txt](https://github.com/dotnet/core/files/359189/DotnetCoreVersionTrace.txt)

For install I use instruction from https://www.microsoft.com/net/core#opensuse:

`sudo zypper install libunwind libicu`
`curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=816867`
`sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet`
`sudo ln -s /opt/dotnet/dotnet /usr/local/bin`

PS:
SUSE Linux Enterprise Server 11 SP3 is officialy supported? Or only openSUSE 13.2?

**Comment by blackdwarf** [comment]
@FZ14 can you please open this issue on dotnet/cli? Thanks!
