### ISSUE TITLE
NETCore with MSTest Framework cannot find references

### ISSUE THREAD

**Issue by MatthewR** [dotnet/core#219]
Created a new Solution, then added an ASP.NET Core Web Application (NETCoreApp, v1.0)
Created a test folder
Created a .NET Core Class library (for test projects) (NETStandard v1.6)
Installed MS Test packages (MS Test and the test Runner).
The whole project compiles, and I can see my basic tests fine.
I added a reference from my website to the test assembly, and put a using statement at the front of a test class. Now it won't recognise namespaces in my added assemblies, but it still compiles. I get the same issue if I try to use xUnit instead of MSTest.

**Comment by blackdwarf** [comment]
@MatthewR can you share your project.json?

**Comment by MatthewR** [comment]
Just rebooted into that environment, and the system did some updates and it worked. Sorry for the fals post :$
