### ISSUE TITLE
Publish winforms application for Mac miss System.Windows.Forms

### ISSUE THREAD

**Issue by MaxAkbar** [dotnet/core#2192]
# Using VS2019 Preview 1 on (Windows 10) to publish winforms (.NET Core 3.0) application for Mac generates error: System.IO.FileNotFoundException System.Windows.Forms

# General
On a Widows 10 using .NET core cli created a simple winform application. Then opened the projet 
with Visual Studio 2019 preview 1. Next created a publish profile from VS2019 to deploy on a Mac. Deployed the published folder to Mac system and tried to run the winform. 
I get the following error: 

**Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.**

Please note that the Mac system does not have .Net Core 3.0 and the publish profile is set to self contained.

## Sample Code
https://github.com/MaxAkbar/WinformRepro

**Comment by livarcocc** [comment]
WinForms applications (or WPF applications for that matter) are not supported crossplatform and only work on Windows.

This is by design.
