### ISSUE TITLE
Linker - Failed to resolve assembly: 'System.Private.CoreLib'

### ISSUE THREAD

**Issue by Symbai** [dotnet/core#2193]
###  Issue
Linker thrown an exception when I tried to follow the docs building the sample.

Windows 10 64-Bit
<details>
  <summary>Click to expand</summary>

Host (useful for support):
  Version: 3.0.0-preview-27224-1
  Commit:  b9d9540371
.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009844 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27218-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27224-1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27218-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

</details>

###  Steps
1. Downloaded sample linked in the docs https://github.com/dotnet/dotnet-docker-samples/archive/master.zip
2. Extracted to desktop
3. Run commands
```
cd C:\Users\...\Desktop\dotnet-docker-samples-master\dotnetapp-selfcontained
dotnet publish -c release -r win-x64 -o selfcontained-win-x64
```

###  Stacktrace:
```
  dotnetapp -> C:\Users\...\Desktop\dotnet-docker-samples-master\dotnetapp-selfcontained\bin\release\netcoreapp2.0\win-x64\dotnetapp.dll
Fatal error in IL Linker
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.CoreLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.CoreLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(String name)
   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run()
   at Mono.Linker.Driver.Main(String[] args)
```

**Comment by karelz** [comment]
@sbomer @jeffschwMSFT should we move it to https://github.com/mono/linker?

**Comment by sbomer** [comment]
@karelz yes, please move it to mono/linker. Thank you!

**Comment by karelz** [comment]
This issue was moved to mono/linker#443
