### ISSUE TITLE
FileVersionProvider Class missing

### ISSUE THREAD

**Issue by leitocardoso** [dotnet/core#2195]
## Bug Description
FileVersionProvider Class missing.

In my code, under .NET Core 2.1, I used FileVersionProvider class in a TagHelper that calls the AddFileVersionToPath method without any problem. 
Today, after upgrading to .NET Core 2.2.101 FileVersionProvider wasn't found in Microsoft.AspNetCore.Mvc.TagHelpers.Internal NS.

Any help will be much appreciated

**Comment by k290** [comment]
I have the same issue

**Comment by k290** [comment]
Based on the changes here: https://github.com/aspnet/Mvc/pull/8455/commits/00d6771f73394def3696e39d344a1de2212bc5d5

It seems like the FileVersionProvider was replaced with DefaultFileVersionProvider. This is internal so you can't use it directly. Seems to relate to the following issue. https://github.com/aspnet/Mvc/issues/6371

I will update here if I figure out how to make use of it.

**Comment by k290** [comment]
Figured it out. Code should look like something like this now (if you're using a Razor page, for example for context):

Instead of:
```
        public static string AddFileVersionToPath(this IRazorPage page, string path)
        {
            var context = page.ViewContext.HttpContext;
            IMemoryCache cache = context.RequestServices.GetRequiredService<IMemoryCache>();
            var hostingEnvironment = context.RequestServices.GetRequiredService<IHostingEnvironment>();
            var versionProvider = new FileVersionProvider(hostingEnvironment.WebRootFileProvider, cache, context.Request.Path);
            return versionProvider.AddFileVersionToPath(path);
        }
    }
```
It is now:

```
public static string AddFileVersionToPath(this IRazorPage page, string path)
        {
            var context = page.ViewContext.HttpContext;
            IFileVersionProvider fileVersionProvider = context.RequestServices.GetRequiredService<IFileVersionProvider>();
            return fileVersionProvider.AddFileVersionToPath(context.Request.PathBase, path);
        }
```

And you will need these namespaces:

﻿using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.DependencyInjection;

**Comment by karelz** [comment]
@leitocardoso maybe it won't be needed, but in future, I recommend to report bugs with minimal repro steps / code.

**Comment by leitocardoso** [comment]
@karelz thanks for your advice. I thought that my message was pretty self-explanatory and didn't require portions of code. Next time I'll do that.
