### ISSUE TITLE
Why IList does not have the method signature RemoveAll?

### ISSUE THREAD

**Issue by DouglasDRF** [dotnet/core#2199]
public class List<T> : ICollection<T>, IEnumerable<T>, IEnumerable, IList<T>, IReadOnlyCollection<T>, IReadOnlyList<T>, ICollection, IList

public interface IList<T> : ICollection<T>, IEnumerable<T>, IEnumerable

IList only have Remove() and RemoveAt()... Wouldn't be more interesting put the RemoveAll() method signature in IList for access it?? Neither ICollection or IEnumerable has these methods signatures. Because if I want to remove all items under a specific condition through IList interface I have to transform to a List first

```
// Enderecos is IList type
       var listEnderecos = clienteModel.Enderecos.ToList();
            listEnderecos.RemoveAll(p => p == null);
            clienteModel.Enderecos = listEnderecos;
```

With RemoveAll() method in IList

```
// Enderecos is IList type
       clienteModel.Enderecos.RemoveAll(p => p == null);
```

**Comment by DouglasDRF** [comment]
No. Clear deletes all whole list and RemoveAll removes all on a specific condition (empty strings, int values lower or greater, DateTime values lower or grater for exemple)

**Comment by MarcoRossignoli** [comment]
IList is very old interface, you could write an extension method or propose new method on https://github.com/dotnet/corefx/issues following proposal guide https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md but I think that IList is implemented by a lot of class and could be a lot of work...maybe in future with default interface methods https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md

**Comment by karelz** [comment]
Adding method to existing interface is a breaking change. As @MarcoRossignoli suggests above using extension method is likely the best option.
CoreFX is the right repo for BCL types like lists. Closing.
