### ISSUE TITLE
Tools for VS '15

### ISSUE THREAD

**Issue by SoonDead** [dotnet/core#220]
VS '15 cannot open ASP.NET Core 1.0 projects yet since it installs with either the VS2015 Update 3 or the .NET Core 1.0 for Visual Studio.

`Microsoft.DotNet.Web.targets` is missing so the project cannot be opened.

**Comment by blackdwarf** [comment]
Hi, can you please open an issue on the dotnet/cli repo and we will make sure that it gets redirected where needed? Thanks!
