### ISSUE TITLE
sfx_x64.cab has an invalid digital signature

### ISSUE THREAD

**Issue by FinchYang** [dotnet/core#2202]
# Issue Title

sfx_x64.cab has an invalid digital signature

# General

In the process of installing Microsoft .NET Core SDK 3.0.100-preview, error ocurred and prompted "A file that is required cannot be installed because the cabinet file C:\ProgramData\Package Cache\{849917F8-9A15-34CD-B971-A7478B010F70}V3.0.0.0\sfx_x64.cab has an invalid digital signature. This may indicate that the cabinet file is corrupt. "
Plus, my system environment ： Windows Server 2008 R2 Enterprise Service Pack 1, no internet connection. Thanks.

**Comment by karelz** [comment]
@FinchYang try it on another machine to avoid HW issues or bad download.

**Comment by zsanhong** [comment]
I have the same problem

**Comment by karelz** [comment]
@zsanhong are you able to reproduce the problem on 2 different machines? It feels like corrupted download ...

Closing due to no response to original question above.

**Comment by Uchiha-Peng** [comment]
I encountered the same problem, but it was solved. Because your computer needs to connect to Microsoft to register a signature when installing the .NET Core environment, you must ensure that your computer is connected to the external network, otherwise this error will occur.

**Comment by hsb0307** [comment]
缺少数字证书：

microsoft root certificate authority 2010

microsoft root certificate authority 2011

解决办法：

一、先安装数字证书；

找一台正常装了VS2015的电脑，Win+R打开运行，输入certmgr.msc，打开证书管理界面。我们从自己电脑导出一个，我的win7 系统。

导出及导入步骤如下：

1.开始→运行→certmgr.msc

2，展开：证书→受信任的根证书颁发机构→证书

3.右击展开菜单，所有任务→导入

4.剩下的，就是选择你下载好的cer文件，然后无限下一步了。

二、证书安装成功以后，安装Microsoft Visual C++ 2015 Redistributable

下载地址：https://www.microsoft.com/en-us/download/details.aspx?id=48145

三、安装Windows补丁

下载地址：https://support.microsoft.com/en-us/kb/2533623

四、重启电脑，再次安装.net core hosting和skd，安装成功。

**Comment by jerrychoubear** [comment]
Had a similar situation while mine error file was sfx_x86.cab,
and resolved using @hsb0307 's reply.

When I ran```certmgr.msc``` on my no-internet-connection Windows Server 2008 R2 Standard sp1,
there was only _microsoft root certificate authority 2010_ but **no** _microsoft root certificate authority 2011_.

So I exported it from my VS2017-installed laptop, imported to that server, ran the installation with repair, and everything were good.

Thanks @hsb0307

**Comment by fhazraty** [comment]
For fixing the problem just import these three certificates from https://github.com/fhazraty/MicrosoftCertificates to "Trusted Root Certification Authorities" in certmgr.msc
