### ISSUE TITLE
On Ubuntu Request.Scheme Returns http and Request.IsHttps Returns False When Connection is Secure

### ISSUE THREAD

**Issue by robinwilson16** [dotnet/core#2203]
In ASP .NET Core 2.2 you are supposed to be able to check whether the connection is secure or not by using:
```Request.Scheme``` (returns ```https``` or ```http```)

Or
```Request.IsHttps``` (returns either ```true``` or ```false```)

This is working fine on Windows servers but on my Ubuntu server running on Apache it is returning ```http``` and ```false``` even though the connection is showing as secure in the browser and accessed over https.

Is this a bug or is it the way I have Apache2 configured?

I need to output the current website address and am using the following:
```httpContextAccessor.HttpContext.Request.Scheme + "://" + httpContextAccessor.HttpContext.Request.Host.Value;```

However due to the issue above it is returning ```http://website``` rather than ```https://website```.

I would rather not hard code this in if possible.

**Comment by Eilon** [comment]
@Tratcher - thoughts on this?

@robinwilson16 - is there a reverse proxy in play here, such as nginx, something with Docker, ARR, etc.?

**Comment by Tratcher** [comment]
Right, Apache is acting as a reverse proxy. See the proxy setup instructions here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2

**Comment by karelz** [comment]
@Tratcher should we close the issue here, or transfer it to ASP.NET repo?

**Comment by Tratcher** [comment]
Closing, you can open a new one in AspNetCore if you have additional trouble.

**Comment by robinwilson16** [comment]
Thanks for the response but I have already followed those instructions and it makes no difference whether I add those forwarding headers etc or not. The request always shows as not being https whether it is or isn't.
It must be something to do with Apache2 not passing on this information as the cert and everything are configured in Apache2 and not Net Core. Both run on localhost though. Maybe the connection is secure up to Apache2 and then insecure when proxied?
I will log the issue on AspNetCore thanks.

**Comment by Lechus** [comment]
same issue with ASP.Net Core 2.1 on ubuntu on CloudFoundry
IsHttps just checks scheme and returns false.

**Comment by Tratcher** [comment]
@Lechus read https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer
