### ISSUE TITLE
Type.IsEquivalent does not seem to work as per documentation

### ISSUE THREAD

**Issue by bclothier** [dotnet/core#2204]
According to the documentation for [Type.IsEquivalent](https://docs.microsoft.com/en-us/dotnet/api/system.type.isequivalentto?view=netframework-4.7.2) and the related article [Type Equivalence and Interop Types](https://docs.microsoft.com/en-us/dotnet/framework/interop/type-equivalence-and-embedded-interop-types?view=netframework-4.7.2), a pair of types should be considered equivalent given the following conditions:

1) Both types have their `Assembly` marked with a `ImportedFromTypeLibAttribute` attribute
2) Both types have `ComImportAttribute` marked
3) Both types have `GuidAttribute` and both contains equivalent values
4) Both types have same `Type.FullName`.
5) Both types' assemblies are loaded for execution context, not for reflection only. 

Note that the articles also describe the different condition of having an `TypeIdentifierAttribute` attribute applied. In this case, neither types have this attribute so that branch does not apply. However, the first branch as described above should be sufficient to make both types equivalent.

The code below requires the following:

1) NUnit test framework (or changing `Assert`s into the equivalent)
2) A COM reference to the type library for `Scripting` -- this is labeled as `Microsoft Scripting Runtime` in the COM tab, and is usually located in the `scrrun.dll` within the system folder.

MCVE:
```c#
        [DllImport("ole32.dll", CharSet = CharSet.Unicode, ExactSpelling = true, PreserveSig = true)]
        private static extern int CLSIDFromProgID(string lpszProgID, out Guid lpclsid);

        [DllImport("oleaut32.dll", CharSet = CharSet.Unicode, ExactSpelling = true, PreserveSig = true)]
        private static extern int LoadTypeLib(string fileName, out ITypeLib typeLib);

        [Test]
        public void Demo()
        {
            const string progId = "Scripting.FileSystemObject";
            if (CLSIDFromProgID(progId, out var clsid) != 0)
            {
                throw new InvalidOperationException("scrrun.dll should be enabled on Windows");
            }

            var libPath = !Environment.Is64BitProcess && Environment.Is64BitOperatingSystem
                ? "C:\\Windows\\SysWOW64\\scrrun.dll"
                : "C:\\Windows\\system32\\scrrun.dll";
            if (LoadTypeLib(libPath, out var lib) != 0)
            {
                throw new InvalidOperationException("Unable to load the type library");
            }

            lib.GetTypeInfoOfGuid(ref clsid, out var typeInfo);
            if(typeInfo == null)
            {
                throw new InvalidOperationException("Unable to load the type info");
            }

            var pUnk = Marshal.GetIUnknownForObject(typeInfo);
            var type = Marshal.GetTypeForITypeInfo(pUnk);
            var imported = typeof(Scripting.FileSystemObject);
            Marshal.Release(pUnk);
            
            var typeComImport = type.GetCustomAttributesData().SingleOrDefault(x => x.AttributeType == typeof(ComImportAttribute));
            var typeGuid = type.GetCustomAttributesData().SingleOrDefault(x => x.AttributeType == typeof(GuidAttribute));
            var typeTypeLib = type.Assembly.GetCustomAttributesData().SingleOrDefault(x => x.AttributeType == typeof(ImportedFromTypeLibAttribute));
            var typeReflection = type.Assembly.ReflectionOnly;

            var importedComImport = imported.GetCustomAttributesData().SingleOrDefault(x => x.AttributeType == typeof(ComImportAttribute));
            var importedGuid = imported.GetCustomAttributesData().SingleOrDefault(x => x.AttributeType == typeof(GuidAttribute));
            var importedTypeLib = imported.Assembly.GetCustomAttributesData().SingleOrDefault(x => x.AttributeType == typeof(ImportedFromTypeLibAttribute));
            var importedReflection = imported.Assembly.ReflectionOnly;

            Assert.AreEqual(type.FullName, imported.FullName);
            Assert.AreEqual(type.GUID, imported.GUID);
            Assert.AreEqual(typeComImport.ToString(), importedComImport.ToString());
            Assert.AreEqual(typeGuid.ToString(), importedGuid.ToString());
            Assert.AreEqual(typeTypeLib.ToString(), importedTypeLib.ToString());
            Assert.IsFalse(typeReflection);
            Assert.IsFalse(importedReflection);
            Assert.AreEqual(typeReflection, importedReflection);
            
            // Those asserts fail; those should be true given the conditions above
            Assert.IsTrue(type.IsEquivalentTo(imported));
            Assert.IsTrue(imported.IsEquivalentTo(type));
        }
```

**Comment by 0xd4d** [comment]
Have you tried .NET Core 3.0 daily build? https://github.com/dotnet/core/blob/master/daily-builds.md

**Comment by bclothier** [comment]
No, and I don't think I can - from what I see, the .NET Core doesn't fully support COM interop - the above code is based on the framework 4.7. I may have posted this in wrong place.

**Comment by bclothier** [comment]
Ok, is there a guide on how to get 3.0 loaded? I downloaded and installed but couldnt go higher than 2.1 Furthermore, it did not recognize the member `GetTypeForItypeInfo`  on the `Marshal` class.

**Comment by bclothier** [comment]
I had another go at this - I seem to be able to install the 3.0 preview but I am unable to build a project for following reasons:

1) With a .NET core app, we cannot have a `COMReference` entry.
2) With a .NET core app, `Marshal.GetTypeForITypeInfo` is not defined.

I tried to build using .NET 4.7 via `dotnet build` which still fails due to the `COMReference` entry.

**Comment by karelz** [comment]
We do not track .NET Framework questions on GitHub, closing - please use community sites like StackOverflow or report it via [VS Developer Community Portal](https://developercommunity.visualstudio.com/) (although, I would not expect any change in the space, given the high bar for changes in .NET Framework).
