### ISSUE TITLE
Suggestion: .NET Core can be managed directly on the client using Winform/wpf/mono Blazor

### ISSUE THREAD

**Issue by 199621616** [dotnet/core#2207]
[**Translated**](https://www.bing.com/translator?ref=TThis&&text=%E5%A4%A7%E9%87%8F%E7%9A%84WinForm%EF%BC%8CWPF%E5%BA%94%E7%94%A8%E6%97%A0%E6%B3%95%E7%9B%B4%E6%8E%A5%E8%BD%AC%E5%9E%8B%E4%B8%BA%E4%BA%92%E8%81%94%E7%BD%91%E7%8E%B0%E4%BB%A3%E5%BA%94%E7%94%A8%E3%80%82%E8%AF%B7%E8%80%83%E8%99%91%E8%BF%99%E4%B8%AA%E8%B7%AF%E5%BE%84%EF%BC%9AAsp.NetCore%20WebApi%20%2B%20Blazor%20%2B%20WinForm%EF%BC%88WPF%EF%BC%89%EF%BC%9F%E5%83%8Fmblataric%E6%89%80%E8%AF%B4%E7%9A%84%EF%BC%8C%E2%80%9C%E6%B5%B7%E9%87%8F%E6%95%B0%E6%8D%AE%E8%BE%93%E5%85%A5%EF%BC%8C%E4%B8%8E%E6%89%AB%E6%8F%8F%E4%BB%AA%EF%BC%8C%E6%9D%A1%E5%BD%A2%E7%A0%81%E9%98%85%E8%AF%BB%E5%99%A8%EF%BC%8CRFID%E6%89%AB%E6%8F%8F%E4%BB%AA%E7%AD%89%E8%AE%BE%E5%A4%87%E7%9A%84%E8%BF%9E%E6%8E%A5......%E6%B5%8F%E8%A7%88%E5%99%A8%E6%B0%B8%E8%BF%9C%E4%B8%8D%E4%BC%9A%E6%88%90%E4%B8%BA%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%E7%9A%84%E5%B9%B3%E5%8F%B0%E3%80%82%E2%80%9C%EF%BC%8C%E8%80%8CWebApi%20%2B%20Blazor%20%2B%20WinForm%EF%BC%88WPF%EF%BC%89%E5%88%99%E5%BE%88%E5%AE%B9%E6%98%93%E5%81%9A%E5%88%B0%E8%BF%99%E4%B8%80%E7%82%B9%E3%80%82%E8%AE%A9WinForm%EF%BC%88WPF%EF%BC%89%20%EF%BC%89%E7%9B%B4%E6%8E%A5%E6%89%98%E7%AE%A1Blazor%EF%BC%81%E5%AE%9E%E7%8E%B0%E7%9C%9F%E6%AD%A3%E7%9A%84C%EF%BC%83%E5%85%A8%E6%A0%88%E5%BC%80%E5%8F%91%E3%80%82&from=&to=en)

A large number of WINFORM,WPF applications cannot be directly transformed into modern Internet applications. Consider this path: Asp.netcore WebApi + Blazor + WinForm (WPF)? As Mblataric it, "massive data entry, connections to devices such as scanners, barcode readers, RFID scanners ... Browsers will never be a platform for this situation. ", while Webapi + Blazor + WinForm (WPF) is easy to do. Let WinForm (WPF) directly host blazor! Realize true C # full stack development.

## Original

大量的WinForm，WPF应用无法直接转型为互联网现代应用。请考虑这个路径：Asp.NetCore WebApi + Blazor + WinForm（WPF）？像mblataric所说的，“海量数据输入，与扫描仪，条形码阅读器，RFID扫描仪等设备的连接......浏览器永远不会成为这种情况的平台。“，而WebApi + Blazor + WinForm（WPF）则很容易做到这一点。让WinForm（WPF） ）直接托管Blazor！实现真正的C＃全栈开发。

**Comment by karelz** [comment]
@199621616 please post questions and bug reports in English, we do not have capacity to support other languages

**Comment by karelz** [comment]
Sounds related to https://github.com/aspnet/Blazor - please ask there.
