### ISSUE TITLE
Error MSB4044 - CheckEmbeddedRootDescriptor

### ISSUE THREAD

**Issue by Symbai** [dotnet/core#2208]
# Issue 
I got this error in console when trying to publish:
`ILLink.Tasks.targets(451,5): error MSB4044: The CheckEmbeddedRootDescriptor task did not receive a value for the required AssemblyPath parameter.`

# General

Created a new .NET Core 3.0 WPF project
Added ILLink.Tasks nuget package
Ran this command:
`dotnet publish -c release -r win-x64 -o out`

**Comment by Symbai** [comment]
Is already reported in mono linker repo: https://github.com/mono/linker/issues/428

**Comment by karelz** [comment]
Duplicate of https://github.com/mono/linker/issues/428

**Comment by cup** [comment]
https://github.com/dotnet/core/issues/2208
https://github.com/dotnet/coreclr/issues/24397
https://github.com/dotnet/winforms/issues/210
https://github.com/mono/linker/issues/428
