### ISSUE TITLE
.NET Core January Update - 2.1.7 and 2.2.1

### ISSUE THREAD

**Issue by leecow** [dotnet/core#2210]
# .NET Core January Update - 2.1.7 and 2.2.1

Included fixes address security issues detailed in the release notes.

**Note:** The 2.2 SDK was re-released on 1/16/2019 to address an issue ([dotnet/source-build#942](https://github.com/dotnet/source-build/issues/942)) where developers targeting the 2.1 Runtime (LTS) will not get the latest release when building self-contained applications.

## .NET Core

* **.NET Core 2.1.7 and .NET Core SDK 2.1.503**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.7/2.1.7.md)
  [Download 2.1](https://dotnet.microsoft.com/download/dotnet-core/2.1)

* **.NET Core 2.2.1 and .NET Core SDK 2.2.103**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.1/2.2.1.md)
  [Download 2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2)

Please report any issues you find with these releases, either responding to this issue, creating a new issue here or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

## .NET Support Policies

Microsoft support policies are defined in the following documents:

* [Microsoft .NET Support Policy](https://www.microsoft.com/net/support/policy)
* [.NET Core OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md)

**Comment by johnkors** [comment]
The links to the CVEs in the releas notes of 2.2.1 are broken. Fix: https://github.com/dotnet/core/pull/2214

**Comment by karelz** [comment]
@johnkors thanks for the fixes!

**Comment by Ryszka** [comment]
When can we expect 2.2.1 packages to be available on NuGet? I can see 2.1.x packages had been updated to 2.1.7, but newest 2.2.x packages are still at version 2.2.0.

**Comment by Ryszka** [comment]
@leecow I have checked again and they're in fact there. Must have been some caching issue or I just missed it before.

**Comment by jsoques** [comment]
I just installed **dotnet-sdk-2.2.103-win-x64.exe**. When I do a **dotnet new mvc** at the command line I get the error: **C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.**

When I do **dotnet --version** I get **2.2.103**

Here is a complete output:

> D:\VSProjects\DotNet2.2>dotnet new mvc
> The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
> This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on D:\VSProjects\DotNet2.2\DotNet2.2.csproj...
> C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [D:\VSProjects\DotNet2.2\DotNet2.2.csproj]
> 
> Restore failed.
> Post action failed.
> Description: Restore NuGet packages required by this project.
> Manual instructions: Run 'dotnet restore'

Help would be appreciated, Thanks.

**Comment by leecow** [comment]
@murat / @bradygaster, can you have a look at @jsoques issue above?

**Comment by muratg** [comment]
@jsoques You don't happen to have a global.json do you?

@leecow This looks like a CLI/SDK question to me.  @livarcocc any thoughts here?

**Comment by livarcocc** [comment]
@jsoques what happens when you run dotnet --info on the project folder?

**Comment by jsoques** [comment]
@muratg No global.json
@livarcocc This is the output:

> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.103
>  Commit:    8edbc2570a
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17763
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.2.103\
> 
> Host (useful for support):
>   Version: 2.2.1
>   Commit:  878dd11e62
> 
> .NET Core SDKs installed:
>   1.0.1 [C:\Program Files\dotnet\sdk]
>   1.0.4 [C:\Program Files\dotnet\sdk]
>   1.1.4 [C:\Program Files\dotnet\sdk]
>   1.1.5 [C:\Program Files\dotnet\sdk]
>   1.1.7 [C:\Program Files\dotnet\sdk]
>   1.1.8 [C:\Program Files\dotnet\sdk]
>   1.1.9 [C:\Program Files\dotnet\sdk]
>   1.1.10 [C:\Program Files\dotnet\sdk]
>   1.1.11 [C:\Program Files\dotnet\sdk]
>   2.0.0 [C:\Program Files\dotnet\sdk]
>   2.0.2 [C:\Program Files\dotnet\sdk]
>   2.0.3 [C:\Program Files\dotnet\sdk]
>   2.1.2 [C:\Program Files\dotnet\sdk]
>   2.1.4 [C:\Program Files\dotnet\sdk]
>   2.1.100 [C:\Program Files\dotnet\sdk]
>   2.1.101 [C:\Program Files\dotnet\sdk]
>   2.1.102 [C:\Program Files\dotnet\sdk]
>   2.1.103 [C:\Program Files\dotnet\sdk]
>   2.1.104 [C:\Program Files\dotnet\sdk]
>   2.1.200 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.302 [C:\Program Files\dotnet\sdk]
>   2.1.400 [C:\Program Files\dotnet\sdk]
>   2.1.401 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.403 [C:\Program Files\dotnet\sdk]
>   2.1.500 [C:\Program Files\dotnet\sdk]
>   2.1.502 [C:\Program Files\dotnet\sdk]
>   2.1.503 [C:\Program Files\dotnet\sdk]
>   2.2.103 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
>

**Comment by jsoques** [comment]
@livarcocc Ah, now that you've mentioned it, yes I have a MSBuildSDKsPath pointing to that version. I had created it because of an issue I had with VS Code/Omnisharp.
I removed MSBuildSDKsPath and it works now! <Facepalm>

Thanks,

**Comment by Leon99** [comment]
[Known Issues](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.1-known-issues.md) points to a non-existing file

**Comment by muratg** [comment]
@Leon99 ANCM was deployed to Azure in late December. What's the exact issue you're having?

**Comment by Leon99** [comment]
@muratg I had a problem described on https://stackoverflow.com/questions/53811569/using-netcore-2-2-and-using-the-in-process-hosting-model last week, solved by switching to OutOfProcess.

**Comment by muratg** [comment]
@Leon99 Ah, so you haven't deployed to Azure. Did you install the latest .NET Core SDK/runtime? (`dotnet --info` output would tell.)

**Comment by Leon99** [comment]
I did deploy to Azure (App Service).

**Comment by muratg** [comment]
@Leon99 could you please share your csproj file?

**Comment by Leon99** [comment]
I can't reproduce it now, InProcess seems to work fine once I put it back and re-deployed. There was nothing fancy about it when I encountered the issue, just a standard Core 2.2 API one generated by the latest VS.

**Comment by leecow** [comment]
Closing this release discussion issue in favor of https://github.com/dotnet/core/issues/2304
