### ISSUE TITLE
Missing 2018 usage data

### ISSUE THREAD

**Issue by ericis** [dotnet/core#2213]
# Missing 2018 usage data

https://github.com/dotnet/core/blob/master/release-notes/cli-usage-data.md

**Comment by karelz** [comment]
@richlander @leecow who handles the published CLI usage data? Do we have plans to keep publishing them?

**Comment by karelz** [comment]
@richlander ping

**Comment by SabotageAndi** [comment]
Any news on this?

**Comment by karelz** [comment]
@richlander ping?

**Comment by karelz** [comment]
@richlander ping ...4.5 months old question :(

**Comment by ericis** [comment]
Next will be the 2019 data hahah 👍

**Comment by KathleenDollard** [comment]
@ericis We are working to update this data.

**Comment by carlossanlop** [comment]
@KathleenDollard do you have an update on this?

**Comment by maxandersen** [comment]
I was reading https://devblogs.microsoft.com/dotnet/what-weve-learned-from-net-core-sdk-telemetry/ which linked to this now removed file. Does this mean that .net cli no longer gather telemetry data ?
