### ISSUE TITLE
Specify custom probing folder for loading assemblies

### ISSUE THREAD

**Issue by disklosr** [dotnet/core#2220]
# Issue Title

Specify custom probing folder for loading assemblies

# General

How can I tell the runtime to look for assemblies in a custom folder of my choice, for example a "bin" folder located in app root?

**Comment by karelz** [comment]
Check out AssemblyLoadContext: https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md
