### ISSUE TITLE
ASP.NET SignalR project packaged against netcoreapp2.1 not running on machine with netcoreapp2.2 due to dependency version change

### ISSUE THREAD

**Issue by IanYates83** [dotnet/core#2223]
Apologies if this is the wrong team, I don't know whether this issue is related to the CLR, Azure, ASP.NET Core, or me 😊

We have released a set of web projects to multiple environments as Azure Web Apps, compiled and packaged (Framework-Dependent) against netcoreapp2.1.
These projects pull in the `Microsoft.AspNetCore.App` project version 2.1.2 and make use of SignalR.

The package itself contains `Microsoft.AspNetCore.SignalR.Common.dll` version 1.0.3, but doesn't have any other `Microsoft.AspNetCore` libraries, presumably because they're not needed, given that the framework includes them.

Sample of the project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
...
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
...
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />
...
```

Today, we noticed that the nightly environment didn't start as expected.
I eventually tracked the issue down to this in the logs:
> [Critical] Microsoft.AspNetCore.Hosting.Internal.WebHost: Application startup exception
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.SignalR.Common, Version=1.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.SignalR.Common, Version=1.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

I have checked every other environment and all have been updated to `dotnet` version `2.2.102`.
As a test, I rebooted one of the other environments and confirmed that the running application could no longer start.

I realise that I can install the 2.2 SDK, update the dependencies, and release the new packages, but this would require regression testing and would take us a lot of time to get through all environments.
Additionally, this wouldn't prevent the problem in the future.

I could also change to Self-Contained packages, but this massively increases our package size, release time, and running footprint.

I have also tried changing the launch script to specify `--fx-version 2.1.7` (latest available 2.1 version), but no success.

Is it intentional that all dependencies are "auto-upgraded" to the latest version available, or have we got our project or package configured incorrectly?

**Comment by Eilon** [comment]
Hi @IanYates83 , sorry you are running into this issue. We have identified this as a recent bug and you can find workarounds and other discussion here: https://github.com/aspnet/AspNetCore/issues/3503

**Comment by IanYates83** [comment]
Thank you. That worked.
