### ISSUE TITLE
Corrupt terminal state after execution

### ISSUE THREAD

**Issue by ygoe** [dotnet/core#2227]
After executing the program attached to #2226, the terminal is left in a corrupt state. It seems like the Control key is still pressed down. Pressing it once doesn't resolve the situation. It shows when back at the command prompt, entering a command, then pressing the left or right arrow keys: The cursor doesn't move a single character but always a full word to the left or right. Using the "Reset Terminal" command in PuTTY fixes the problem. But it comes back every time the program was started.

One key action that this program does it moving the cursor position to the first column in the line to overwrite an ongoing status with a new value. When pressing Ctrl+C while that is running, ANSI control codes become visible at different places (in the last program output and also after the command prompt – where it shouldn't be possible).

So whatever .NET Core does to the terminal, it has serious side effects.

Same environment as in #2226.

**Comment by karelz** [comment]
@ygoe there is no repro attached anywhere.
Either way, can you please minimize the repro to small app and then share that?
Please make sure it reproduces on more than 1 machine to avoid chasing down weird 1 machine corruptions.

**Comment by ygoe** [comment]
It's not there? Did you receive the code for the referenced issue? Not sure where it went. I'll have to recompile the archive, I don't have it here anymore.

And I've only got a single Linux machine, so I won't be able to test it on more of them.

**Comment by karelz** [comment]
Not actionable, closing. If you have minimal repro and evidence it fails on more than 1 machine, feel free to reopen.
