### ISSUE TITLE
Can't attach lldb to running process on raspbian

### ISSUE THREAD

**Issue by myrup** [dotnet/core#2229]
# Can't attach lldb to running process on raspbian
We are experiencing a deadlock on our fleet of raspbian jessie's running dotnet 2.2.102 self contained. I'm attempting to debug this using lldb but the debugger hangs when I attempt to attach to the running (deadlocked or not) process.

```
sudo lldb-3.9
(lldb) plugin load /path/to/scd-app/libsosplugin.so
(lldb) setclrpath /path/to/scd-app
(lldb) process attach -p 6001
```
The last command hangs forever. `libmscordaccore.so` is present in `/path/to/scd-app/` as well as everything else outputted to `bin/Release/netcoreapp2.2/linux-arm/publish/`.

**Comment by mikem8361** [comment]
I have heard of various problems with lldb on arm. I recommend trying a later version of lldb. The same plugin should work.

/cc: @sywhang, @hoyosjs

**Comment by hoyosjs** [comment]
@myrup I'm sorry you hit this problem while trying to diagnose problems with your app. My experience on raspbian + lldb is that lldb 3.9 itself is severely unstable. There were often cases where running the process itself with no plugin loaded and trying to get the help messages from lldb ended up on a SIGSEGV. The [LLVM Status page](https://lldb.llvm.org/status.html) reports Linux ARM to be untested. I don't have access to a Pi right now so I can't tell you how well it works now on other versions or if there are any workarounds to this.

As for issues regarding SOS, the best place to track this would be [dotnet/diagnostics](https://github.com/dotnet/diagnostics). For example, one where this had come up previously, although in dump debugging, is dotnet/diagnostics#38. We are currently evaluating possible alternatives for diagnostics in cases where our use of LLDB is not meeting our desired user experience.

**Comment by karelz** [comment]
@hoyosjs do we want to move this issue to better place, or just close it as non-actionable at this point?

**Comment by hoyosjs** [comment]
@myrup Also, might not be everyone's cup of tea, but a scenario that I've tried on other platforms and really helped out was be using the remote debugger. Say using [vscode](https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm), which I've previously used, or [visual studio](https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio).

I hope this unblocks your investigations for now and I'll close this issue for the time being. However, if you feel like there is still a gap and this doesn't quite work for your scenarios, feel free to open a bug on the diagnostics repo and we'll follow up.

**Comment by myrup** [comment]
@mikem8361 LLDB 3.9 seems to be the latest for jessie. 

@hoyosjs Thanks for elaborating. It would be really wonderful with debugging support straight on the ARM. Even more quick and useful would be a nu-get package that works across platforms to dump all thread stacktraces at any point (like MSE provided for .Net framework clients on windows for us in the past). But for now I will look into remote debugging our clients across the internet using vscode since i'm on a mac (no visual studio for mac remote debugging as far as I can see).
