### ISSUE TITLE
I can't find following method in .net core.

### ISSUE THREAD

**Issue by BingyuLiu** [dotnet/core#223]
Hi dotnet core  team, 

I am trying to migrate my code  to .net core which is based on .net framework, but following methods/Class are not supported in .net core.

version: 1.0.0-preview2-003121

1. System.DirectoryServices
2. System.Runtime.Remoting
3. System.Runtime.Remoting.Messaging
4. System.Security.Principal.WindowsImpersonationContext
5. System.Type.IsGenericType

Thanks,
John Liu

**Comment by mairaw** [comment]
Have you tried following the process documented here: https://docs.microsoft.com/en-us/dotnet/articles/core/porting/index?

**Comment by blackdwarf** [comment]
@BingyuLiu is this issue resloved?

**Comment by blackdwarf** [comment]
Seems like this issue is not reproing anymore. Closing. If you still need help, please reopen.

**Comment by ewaschen** [comment]
With my EF6 project I'm using `System.Runtime.Remoting.Messaging` and then use `CallContext.LogicalSetData(...);`   So with my new .Net Core project this is obviously not supported but I do not know what / how to replace it in core.

**Comment by mairaw** [comment]
@divega can you help with this EF question?

**Comment by divega** [comment]
@ewaschen for replacing call context data, take a look at [`AsyncLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netcore-2.0).

**Comment by SenyaMur** [comment]
I have the same problem

System.Security.Principal.WindowsImpersonationContext not found 

```
<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="12.2.1100" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.0" />
    <PackageReference Include="System.Security.Permissions" Version="4.4.0" />
    <PackageReference Include="System.Security.Principal" Version="4.3.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="4.4.0" />
  </ItemGroup>
```
Error text:
```
Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```
