### ISSUE TITLE
[Required] attributes lets empty strings get saved

### ISSUE THREAD

**Issue by rp0m** [dotnet/core#2232]
# Issue Title
Marking a model property with [Required] (System.ComponentModel.DataAnnotations.RequiredAttribute, Version 4.2.0.0) lets that model get saved into the database when the string property value is "" or string.Empty.

I can see that the DB column is marked as non-nullable and recognize that empty string is not NULL, however, according to the documentation, I expect this attribute to protect from empty strings as well by default.

# General
`// Model
public class TestModel
{
    [Required]
    public string TestProperty { get; set; }
}

// Saving
context.Add(testModel); // TestProperty = "" in Immediate Window to make sure
context.SaveChanges(); // Works fine

// Documentation
//
// Summary:
//     Gets or sets a value that indicates whether an empty string is allowed.
//
// Returns:
//     true if an empty string is allowed; otherwise, false. The default value is false.
public bool AllowEmptyStrings { get; set; }
`

**Comment by ajcvickers** [comment]
@rp0m This looks like an Entity Framework issue. In the future, please file EF issue at https://github.com/aspnet/EntityFrameworkCore

In this case, the behavior is by-design. See https://github.com/aspnet/EntityFrameworkCore/issues/14279 for more details.

**Comment by rp0m** [comment]
Ahh okay - will do next time! Was 50/50 on where to raise this one..

Just to confirm - if this behaviour is by design, does that not go against the documentation? This seems like a bug to me. If such behaviour is not handled by EF - that's fine, but having a property that seemingly does nothing seems misleading.
