### ISSUE TITLE
TypeLoadException when using Nuget references

### ISSUE THREAD

**Issue by elangelo** [dotnet/core#2234]
# Issue Title

We are encountering a TypeLoadException on System.Security.Cryptography.Cng when we add a package reference to a project that contains that same PackageReference

# General

1. We have an internal library that uses System.Security.Cryptography.Cng to encrypt some strings for safe storage. That library is both net472 and netcoreapp2.1 compatible.
For netcoreapp2.1 apps we add the following PackageReference:
`<PackageReference Include="System.Security.Cryptography.Cng" Version="4.5.0" Condition="'$(TargetFramework)' == 'netcoreapp2.1'" />`
This library is published on our private  nuget feed.

2. We have a dotnet coreapp (2.1) that uses System.Security.Cryptography.Cng internally (same package reference, same version) and it uses the above internal library. References to the above library are added with a PackageReference (so nuget basically)
This app will always fail with 
`System.TypeLoadException: Could not load type 'System.Security.Cryptography.AesCng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`
when it tries to use the above library.
The code that is hosted within that project works just fine (even though that also references exactly the same classes within System.Security.Cryptography.Cng)

3. When compiling the dotnet coreapp i do find back the following messages in the compile log:
```
       C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(41,5): message NETSDK1041: Encountered conflict between 'Platform:System.Security.Cryptography.Cng.dll' and 'Runtime:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.cryptography.cng\4.5.0\lib\netcoreapp2.1\System.Security.Cryptography.Cng.dll'.  NETSDK1036: Choosing 'Platform:System.Security.Cryptography.Cng.dll' because it comes from a package that is preferred. [C:\vsts\SharedLibrary\UsingNuget\UsingNuget.csproj]
       C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(41,5): message NETSDK1041: Encountered conflict between 'Platform:System.Security.Cryptography.Cng.dll' and 'Runtime:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.cryptography.cng\4.5.0\runtimes\win\lib\netcoreapp2.1\System.Security.Cryptography.Cng.dll'.  NETSDK1036: Choosing 'Platform:System.Security.Cryptography.Cng.dll' because it comes from a package that is preferred. [C:\vsts\SharedLibrary\UsingNuget\UsingNuget.csproj]
```

4. The weird thing is that if i add the project files of the library directly into the solution of the .netcore app and just use ProjectReferences everything works just fine.

**Comment by elangelo** [comment]
```     <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />
     <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
     <PackageReference Include="Polly-Signed" Version="5.9.0" />
-    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.1" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
-    <PackageReference Include="System.Net.Http" Version="4.3.3" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
-    <PackageReference Include="System.Security.Cryptography.Cng" Version="4.5.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
     <PackageReference Include="WindowsAzure.Storage" Version="8.6.0" />
   </ItemGroup>
-  <ItemGroup>
-    <Reference Condition="'$(TargetFramework)' == 'net472'" Include="System.Configuration" />
-    <Reference Condition="'$(TargetFramework)' == 'net472'" Include="System.Net.Http" />
+  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
+    <Reference Include="System.Configuration" />
+    <Reference Include="System.Net.Http" />
+  </ItemGroup>
+  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netcoreapp2.1' ">
+    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.1" />
+    <PackageReference Include="System.Security.Cryptography.Cng" Version="4.5.0"/>
+    <PackageReference Include="System.Net.Http" Version="4.3.3" />
   </ItemGroup>
```

this is the change that somehow fixes this. don't really make sense to me though

**Comment by elangelo** [comment]
I have to reopen this issue again. Apparently this is still happening. Problem is I have no idea why the dotnet core runtime would try to find System.Security.Cryptography.AesCng in System.Core. That simply doesn't make sense to me.
I've tried to create a demo application that shows the same behavior but i have not been successful.

**Comment by karelz** [comment]
@elangelo I think we will need a repro to be able to help here.
I would first try to create an environment where you can always reproduce the problem, then chop off parts of the app, move it from NuGet library to local project library, simplify it, while still checking it fails. Once you have a reasonably small repro, please share it with us and hopefully we can help.

**Comment by elangelo** [comment]
While trying to reproduce the issue on a smaller code project i accidentally found what was wrong. Apparently our build process to build the nuget package of the internal library only withheld one .dll (net472) instead of 3 dll's (net472, netstandard20 and netcoreapp21) and somehow that net472 dll was distributed as the dll for the different frameworks. Obviously that could never work. 
Just to make it perfectly clear this is how the nupkg file actually looked like:
```Aprimo.Configuration.nuspec  
[Content_Types].xml
lib:
    net472:
        Aprimo.Configuration.dll -- NET472 VERSION
    netstandard2.0
        Aprimo.Configuration.dll -- NET472 VERSION
    netcoreapp2.1
        Aprimo.Configuration.dll -- NET472 VERSION
package:
    services:
        metadata:
            core-properties:
                67c6f55284d64e37964de2dd4159fff0.psmdcp
_rels:```

The reason that only one of the dll's was kept was due to a bug in the signing script. 

Some random thoughts....
1. it's weird that the build process of the dotnetcore app didn't stumble of this, or maybe even during the adding of the package to the project. The fact that it's a runtime exception still amazes me.
2. a good tutorial on how to setup 'mixed' nuget packages (targeting multiple frameworks) might be nice. 

Anyway mystery fixed.
