### ISSUE TITLE
'AssemblyResourceStringProvider' could not be found (Are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by senyg1** [dotnet/core#2237]
# Issue Title

I have upgrade my projet from dotnet ocre 1.1 to 2.1 and getting this error.
'AssemblyResourceStringProvider' could not be found (Are you missing a using directive or an assembly reference?)

# General

I have a project that is working fine in dotnet core 1.1.
I have decided to upgrade it to 2.1.
And I'm getting nthe above error on the following code bloc:

```c#
public class SingleFileResourceManagerStringLocalizer : IStringLocalizer
    {
        private readonly ConcurrentDictionary<string, object> _missingManifestCache = new ConcurrentDictionary<string, object>();
        private readonly IResourceNamesCache _resourceNamesCache;
        private readonly string _keyPrefix;
        private readonly ResourceManager _resourceManager;
        private readonly IResourceStringProvider _resourceStringProvider;
        private readonly string _resourceBaseName;

        /// <summary>
        /// Creates a new <see cref="SingleFileResourceManagerStringLocalizer"/>.
        /// </summary>
        /// <param name="resourceManager">The <see cref="ResourceManager"/> to read strings from.</param>
        /// <param name="resourceAssembly">The <see cref="Assembly"/> that contains the strings as embedded resources.</param>
        /// <param name="baseName">The base name of the embedded resource that contains the strings.</param>
        /// <param name="resourceNamesCache">Cache of the list of strings for a given resource assembly name.</param>
        public SingleFileResourceManagerStringLocalizer(
            ResourceManager resourceManager,
            Assembly resourceAssembly,
            string baseName,
            IResourceNamesCache resourceNamesCache,
            string keyPrefix)
            : this(
                resourceManager,
                new AssemblyResourceStringProvider(
                    resourceNamesCache,
                    new AssemblyWrapper(resourceAssembly),
                    baseName),
                baseName,
                resourceNamesCache,
                keyPrefix)
        {
            if (resourceAssembly == null)
            {
                throw new ArgumentNullException(nameof(resourceAssembly));
            }
        }
```

Can anyone help me on this?

**Comment by karelz** [comment]
@krwq @tarekgh can you please help route the question?

**Comment by tarekgh** [comment]
AssemblyResourceStringProvider is ASP.NET class. @muratg or @Eilon can help. 

@karelz I think this can be moved to the asp.net repo.

**Comment by karelz** [comment]
Thanks @tarekgh for your help!

**Comment by muratg** [comment]
@tarekgh What namespace is that in? I couldn't find it with a cursory search.

**Comment by tarekgh** [comment]
> What namespace is that in? I couldn't find it with a cursory search.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.internal.assemblyresourcestringprovider?view=aspnetcore-2.0

**Comment by muratg** [comment]
Thanks! @mkArtakMSFT, seems like this is in Localization. Is this an area you own? Was there a change between 1.x and 2.x here?

**Comment by tarekgh** [comment]
@muratg the doc I sent link for saying this apply to 1.1 and 2.0 but it is not mentioning 2.1. I am not sure how we support such libraries especially it is listed inside a namespace Microsoft.Extensions.Localization.Internal (which kind indicating it is internal).

**Comment by Eilon** [comment]
This issue was moved to aspnet/Extensions#1000
