### ISSUE TITLE
Issues while referencing .Net 4.5.1 class libraries

### ISSUE THREAD

**Issue by narenkv** [dotnet/core#224]
I was trying out to refer class libraries .net framework 4.5.1 in Core 1.0 latest 2016 release.

in the project.json "imports": [ "dnxcore50", "net451" ,"net452"] is been taken care and the following gets added as dependencies in project.json

"Core.Framework.Testing": { "target": "project" },

I see no errors in the references but in the class file , I cant access the namespace like using Core.Framework.Testing in the class files in the same core project.

is there something which I am missing here, 

Could you help me on this

Naren

**Comment by svick** [comment]
Using `"imports"` lets you specify that something is compatible, even when it's not. And this is exactly what happens: `net451` is not compatible with .Net Core, you can't use a .Net Framework 4.5.1 library from a .Net Core application.

**Comment by blackdwarf** [comment]
@svick's explanation is correct. `imports` is used mostly for restore-time compatibility, not for build and/or run time compat. 

With this, I will close this issue. @narenkv if you believe this is in error, please open a new issue on dotnet/cli repo. Thanks!

**Comment by narenkv** [comment]
i happen to see a thread , https://github.com/dotnet/cli/issues/3199#issue-156249706

They claim that you can refer a .Net 4.5.1 from a Core Application, Could you please throw some light here please

/Naren

**Comment by svick** [comment]
@narenkv That question is using ASP.NET Core and .Net Core CLI (the `dotnet` command), but the application is targeting .Net Framework, not .Net Core. You can use .Net Framework libraries from such application. (Yes, it's confusing.)

**Comment by narenkv** [comment]
Hope some one posts a sample soon in github
