### ISSUE TITLE
Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase is not working in .net core 2.0 above versions

### ISSUE THREAD

**Issue by synckarthik** [dotnet/core#2240]
# Issue Title

`Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase` is not working in .net core 2.0 above versions

# General

We used the html upload box in our project. While upload fails, we will pass the custom message through httprequest to client side.  Our server side section is in .net core project (2.0).  So we have used the below code to send custom message

`Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = "File already exists.";`

It working fine.

While using the above code in .net core 2.1 project, it does not works.

How to resolve this in our side? Please suggest your ideas.

**Comment by synckarthik** [comment]
Hi Guys,

I have attached the sample for HTML 5 uploader with xmlHttpRequest to send the form data. 

Steps to reproduce: 

Run the sample and select any file. Then click on uploadFile button,. Your file will be uploaded in to wwwroot folder now.
Upload the same file again, you will receive the custom message which we sent from server end 'File Already Exists' in load event.

But message jot received in dotnet core 2.1 project.

**Below you can get 2.0 project.**

[UploaderDotNetCore2Point0.zip](https://github.com/dotnet/core/files/2786412/UploaderDotNetCore2Point0.zip)


**Below you can get 2.1 project.**

[UploadDotnetcore2Point1.zip](https://github.com/dotnet/core/files/2786413/UploadDotnetcore2Point1.zip)

Please check it.

**Comment by synckarthik** [comment]
Hi @karelz / @Eilon , Any ideas on this issue?

**Comment by karelz** [comment]
@synckarthik no idea from me - when @Eilon is back, he can route it on ASP.NET team.

**Comment by karelz** [comment]
@muratg can you please help move it & route it on ASP.NET team while @Eilon is OOF?

**Comment by muratg** [comment]
@Tratcher Can you take a look?

**Comment by Tratcher** [comment]
@synckarthik I was able to reproduce this with your samples and I see the difference. This is not caused by any code changes in the framework, it's caused by a project configuration change.

The 2.0 project templates did not have HTTPS enabled by default, the 2.1 templates do. When using HTTP the browser uses HTTP/1.1 and ReasonPhrase works as expected. When using HTTPS the browser uses HTTP/2 and ReasonPhrase no longer works. The reason it doesn't work is because the HTTP/2 protocol has removed the concept of ReasonPhrase. That's one of the reasons we excluded it from HttpResponse.

Suggested workaround: use a custom header instead.

**Comment by synckarthik** [comment]
@Tratcher , Thank you for your detailed explanation. I will use custom header.

**Comment by Gopigovin** [comment]
Hi Guys, 

Http response custom header not working properly asp.net core 2.2 web api response.  

We used the html upload box in our project. While upload fails, we will pass the custom message through httprequest to client side. Our server side section is in .net core project (2.1). So we have used the below code to send custom message

Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = "File already exists.";

It working fine core 2.1. While using the above code in .net core 2.2 project, it does not works.

How to resolve this in our side? Please suggest your ideas.

Regards,
Gopi G

**Comment by Tratcher** [comment]
Are you sure it's not using Http/2 a like discussed above?
