### ISSUE TITLE
Sometime .net core 2.0 deployed on IIS error 500

### ISSUE THREAD

**Issue by dovandap** [dotnet/core#2242]
# Issue Title

i using .net core 2.0 and deployed to IIS on server 2016 but sometime error 500.
# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

.net core 2.0

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.
 
![imgpsh_fullsize](https://user-images.githubusercontent.com/22220139/51512292-e4131080-1e37-11e9-876c-df1f6ec45910.jpg)

**Comment by karelz** [comment]
.NET Core 2.0 is out of support. Try it on .NET Core 2.1. If you still have the issue, please make sure it reproduces on more than 1 machine, then gather actionable information - ideally a repro, call stack, etc.
