### ISSUE TITLE
X509Extension - OID 2.5.29.17 gives different format on Windows vs. Linux

### ISSUE THREAD

**Issue by vjirovsky** [dotnet/core#2243]
# X509Extension - OID 2.5.29.17 gives different format on Windows vs. Linux

If you parse X509 certificate extensions by X509Certificate2 object, there is difference between X509 certificate extension (Subject alternative name - SAN) output format on Windows .NET Core vs. Linux .NET Core.

# General

Tested .NET Core version: 2.1, 2.2
OS: Windows, Linux (that's the problem - it's not the same)

Sample code loads my x509 certificate in base64 and displays found SANs in certificate 

## Expected result
Attached sample code's result on Windows: `DNS Name=vjirovsky.cz\r\nDNS Name=www.vjirovsky.cz\r\n`
Attached sample code's result on Linux: `DNS Name=vjirovsky.cz\r\nDNS Name=www.vjirovsky.cz\r\n`

## Current result
Attached sample code's result on Windows: `DNS Name=vjirovsky.cz\r\nDNS Name=www.vjirovsky.cz\r\n`
Attached sample code's result on Linux: `DNS:vjirovsky.cz, DNS:www.vjirovsky.cz`

# Errors
1. on Linux is used delimeter `, ` -> should be `\r\n`
2. on Linux is different prefix `DNS:` -> should be `DNS Name=`

# Sample
https://gist.github.com/vjirovsky/33479dd4c0d071b04fa96e593aa1e7d9

**Comment by bartonjs** [comment]
Yep, the behavior of the Format methods is not guaranteed to be the same across the operating systems, it is deferred to the underlying provider for pretty-printing.

**Comment by vjirovsky** [comment]
ok, could be this information into method `public virtual string Format(bool multiLine)` documentation?

**Comment by karelz** [comment]
@vjirovsky would you mind submitting PR in docs repo? (edit button will lead you there - it is fairly simple) Thanks!

**Comment by vjirovsky** [comment]
@karelz PR created here https://github.com/dotnet/dotnet-api-docs/pull/1681

**Comment by karelz** [comment]
Thank you @vjirovsky!
