### ISSUE TITLE
.NET Core 3.0.0 preview is no longer working with VS 2017 preview

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/core#2245]
# Issue Title

See title

# General

I was using older builds (from december), but decided to try the latest bits (because I want to provide as much feedback as possible). Now suddenly I am getting errors:

```
C:\Program Files\dotnet\sdk\2.2.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
```

*Luckily I was able to fix this* by using an older build from a setup I had stored on my build agents setup. This version still works fine:

![image](https://user-images.githubusercontent.com/1246444/51609295-04b39700-1f1a-11e9-8fef-89b80cbf8956.png)

Your answer is probably: use VS 2019 Preview. But I cannot use that because some extensions (Multilingual App Toolkit) have not been updated yet... MS promised some updates end of december, but nothing yet so far.

**Comment by karelz** [comment]
@GeertvanHorrik updates to what were promised where?
@leecow can you help here?

**Comment by GeertvanHorrik** [comment]
> @GeertvanHorrik updates to what were promised where?

@karelz the VS extension holding me back to start using VS 2019.

But again, why would support for VS 2017 (preview) be dropped, it's "just" an sdk?

**Comment by GeertvanHorrik** [comment]
Because I can't use VS 2019 at the moment since required extensions have not been made compatible yet. Why should that block me from using the .NET Core 3.0 SDK?

**Comment by leecow** [comment]
Sorry for the troubles here. 

There are 3.0 features which have (or will have) dependencies on new Visual Studio and, given the scope, migrating this work back to Visual Studio 2017 isn't practical. This is the reason for blocking on VS2017. We chose to not block the use of 3.0 in 2017 on the first Preview because none of these features were yet available in 2019.
