### ISSUE TITLE
.NET Core 2.2 not available on Debian 8 (jessie)

### ISSUE THREAD

**Issue by radwan92** [dotnet/core#2248]
For some reason dotnet runtime 2.2 is not available on debian8 even though there are [official instructions](https://dotnet.microsoft.com/download/linux-package-manager/debian8/runtime-2.2.1) on how to install it.

After inspecting the [repository](https://packages.microsoft.com/debian/8/prod/pool/main/d/) we can see that indeed the packages for 2.2 are not there.

It seems that dependencies on debian9 haven't changed between 2.1 and 2.2 (libicu57, libssl1.0.2). That said:

1. Am I going to run into any issues by running from the [binaries](https://download.visualstudio.microsoft.com/download/pr/53cace8f-2907-487e-84d7-bc7a7ba5de05/326704ffa2ef9d4dcd0db2f1da996ebb/aspnetcore-runtime-2.2.1-linux-x64.tar.gz)?
2. Has jessie support been dropped? If not, are you going to provide version 2.2 for jessie any time soon?

**Comment by leecow** [comment]
@radwan92 - Support for Jessie was dropped when it went EOL 6/17/2018. Running from binary should work but there will be no support if any issues are encountered.  

https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md
