### ISSUE TITLE
\

### ISSUE THREAD

**Issue by rakesh-shrivastav** [dotnet/core#2249]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by karelz** [comment]
@rakesh-shrivastav looks like a mistake - no original content in the bug report. Closing.

**Comment by rakesh-shrivastav** [comment]
Never opened anything. Details are definitely mine. 🤔😂

**Comment by ajcvickers** [comment]
@rakesh-shrivastav Do you have a :cat:?

**Comment by rakesh-shrivastav** [comment]
@ajcvickers Yeah, Schrodinger's cat
