### ISSUE TITLE
input for checkbox always false

### ISSUE THREAD

**Issue by drowhunter** [dotnet/core#2258]
# General

I just spent two days trying to figure out why this is not working
```
    <form method="post" asp-page-handler="Callback" class="consent-form">
        <input asp-for="ViewModel.UserCode" type="hidden" value="@Model.ViewModel.UserCode" />
            <label>
                <input class="consent-scopecheck" asp-for="ViewModel.RememberConsent" />
                <strong>Remember My Decision</strong>
            </label>                          
            <button name="Button" value="yes" class="btn btn-primary" autofocus>Push</button>
    </form>
```
On Post value of check box is always false, and the user code is null
![wrongvalues](https://user-images.githubusercontent.com/2817488/51794044-7dc02200-2198-11e9-9fad-b279115cca66.png)
but if you look at the request the values are there
![requestform](https://user-images.githubusercontent.com/2817488/51794052-b19b4780-2198-11e9-88f0-e8616fab9511.png)

my code is below

 ```
public DeviceAuthorizationViewModel ViewModel { get; set; }

public async Task<IActionResult> OnPostCallbackAsync(DeviceAuthorizationInputModel model)
 {
            if (model == null) throw new ArgumentNullException(nameof(model));
           // code removed...
}
        
``` 

My model
```
public class DeviceAuthorizationViewModel
    {
        public string UserCode { get; set; }
        public string Button { get; set; }
        public IEnumerable<string> ScopesConsented { get; set; }
        public bool RememberConsent { get; set; }
        public string ReturnUrl { get; set; }
    }
```

**Comment by leecow** [comment]
@muratg - can you have a look and redirect if necessary?

**Comment by muratg** [comment]
cc @mkartakmsft, @danroth27

**Comment by drowhunter** [comment]
Just to be clear, in order to work around this issue, I had to go into the Request.Forms Items and select the first value from the `RememberConsent` Array.  And Grab the value for UserCode myself. 

Something is not right with the PageModelBinder or something

**Comment by danroth27** [comment]
This issue was moved to aspnet/AspNetCore#7560
