### ISSUE TITLE
.NET CLI Blob's Release Metadata JSON for .NET Core 3.0 Links to Nonexistent File

### ISSUE THREAD

**Issue by TheFanatr** [dotnet/core#2264]
# The [Release Metadata JSON for .NET Core 3.0 Hosted on the .NET CLI Blob](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.0/releases.json) Links to Nonexistent Resources in this Repo
See images below; I don't know how official this ".NET CLI Blob" is but I see it being used a lot, and it is pointing to nonexistent files, so I thought it might be important to point out.
### Snippet of Returned JSON as Text
![image](https://user-images.githubusercontent.com/16641853/51951149-4f388600-23e8-11e9-811b-72d2316b304b.png)
### Snippet of the Page that Gets Loaded on GitHub at that URI
![image](https://user-images.githubusercontent.com/16641853/51951419-662ba800-23e9-11e9-8df4-b113a60ff309.png)
This is [the page it was likely supposed to link to](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview2.md).

**Comment by leecow** [comment]
Fixed!
