### ISSUE TITLE
the symbol has no implementation visual studio 2017

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/core#2266]
# Symbol has no implementation

It is very simple to reproduce. I have web API & class library in dot net core 2.0. From any function, which is implemented in the class library, API controller, whenever I press ctrl+F12, a pop up appears with the following text "the symbol has no implementation" but when I simply press F12 it takes me into the definition I mean into the interface. And interestingly when I press ctrl+F12 from a class library it works perfectly and landed me into the implementation eiter pointing to the same class library or to the different class library project

I am using visual studio enterprise latest version 
version: 15.9.6
windows 10 enterprise
version 1803
os build 17134.523

**Comment by karelz** [comment]
.NET Core 2.0 is not supported as of 2018/10/1: https://github.com/dotnet/core/blob/master/release-notes/2.0/README.md
Closing.

If you can reproduce it on supported .NET Core version on more than one machine (to avoid bad install problem), we can reopen. I can try to route it in such case (please include clear step-by-step instructions how to reproduce the problem from scratch and what is expected where). Thanks!
