### ISSUE TITLE
What's the intended behavior of Environment.CurrentDirectory

### ISSUE THREAD

**Issue by JC-85** [dotnet/core#2269]
I recently had some problem when I needed to read from a text file that was linked into the project from another place. 

It seems that the default behavior of `Environment.CurrentDirectory` is to be set to the project root dir, at least when running the project with `dotnet run`. When running an asp.net core project in IIS Express from VS2017 the current working dir is set to the install path of IIS Express, in my case C:\Program Files\IIS Express.

So I'm wondering if this is the intended behavior? As far as I know `Environment.CurrentDirectory` is the default base dir for all System.IO operations when a relative path is provided.

In the end I got some help on stackoverflow to work around my problem. https://stackoverflow.com/questions/54420382/copying-resources-on-build-in-asp-net-core

**Comment by karelz** [comment]
I believe that `Environment.CurrentDirectory` is what the process sets it to at OS level - IIS chose one dir, `dotnet run` another dir.
If you need to find the project location, you need to use path of your main assembly, or something like that ...

cc @JeremyKuhne to double check my reply
