### ISSUE TITLE
Broken link for C# 8 preview 2

### ISSUE THREAD

**Issue by juniormayhe** [dotnet/core#2274]
Broken link in C# 8 Preview  at **C# 8 Preview 2 (see highlights in the blog post)**: https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/dotnet-blog

Source page: https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview2.md

**Comment by karelz** [comment]
Fixed, thanks for report!
