### ISSUE TITLE
Multidimensional Arrays on .NET Core on MacOS much slower than .NET 4.7 

### ISSUE THREAD

**Issue by ZeroPKI** [dotnet/core#2279]
# Performance issue with Jagged arrays

I'm testing the performance of Jagged and multidimensional arrays on various platforms and CLR versions.  I'm  using the code here (https://stackoverflow.com/a/597790/420003 ) to test the performance.

 ```
.NET 4.7 on MacOS
Jagged 5.661   7.232   2.190   4.300   2.180   3.926   2.168   3.137   2.200   4.753 
 MultiDimensional 19.352   9.227  10.745   9.073   8.803   9.183   9.639  14.307  11.179  12.467 
 Single 3.615   3.554   4.003   4.506   5.059   4.134   6.286   3.578   3.487   3.740 

.NET Core on MacOS
Jagged 1176.692 821.192 345.853 476.196 650.264 449.611 413.252 586.237 364.870 395.155 
Multi 689.579 756.033 648.543 725.105 658.745 894.070 635.648 498.737 685.457 975.397 
Single 442.124 259.102 268.668 471.452 415.785 432.108 447.149 464.441 261.718 276.784 
```

From what I've read the method of measuring performance may be different between the platforms.  In case this is simply a result of different underlying tools, how can I benchmark the effective performance difference between the platforms?

**Comment by karelz** [comment]
What is .NET 4.7 on MacOS? Do you mean Mono? It might have entirely different performance characteristics.
I would suggest to change the perf test to [BenchmarkDotNet](https://benchmarkdotnet.org/) to get proper statistics, and avoid `Stopwatch` mistakes, then we can check further ...

cc @adamsitnik @billwert

**Comment by ZeroPKI** [comment]
Thank you for this information. I'll update with the test results, but this does put me in the right direction.  I'll close this ticket so to not affect any SLA you may have. Thanks for again for the (knowledge) that I'll be digging into.
