### ISSUE TITLE
Building Console App on Windows, Deploying to Ubuntu 14.04

### ISSUE THREAD

**Issue by sb421** [dotnet/core#228]
I am building a console app on Windows using VS2015 with .NetCore Tools.

How do I port this app to Linux?

I am able to build and run this app in VS using the .Net Core project.

I ran dotnet publish and copied the files over to Linux.  Do I need to manually fix up the one of the json config files?  Is there a way to automate this?

Thanks

**Comment by svick** [comment]
If it's a [portable application](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#portable-applications), using `dotnet publish` and then running it with `dotnet yourapp.dll` should just work.

If it's a [self-contained application](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#self-contained-application), with the right runtime specified, then using `dotnet publish`, and running `./yourapp` should also just work.

If you encountered a problem, could you describe what exactly did you do (including your project.json) and how exactly did it fail?

**Comment by sb421** [comment]
Is is a portable application.  With I run it with dotnet my.dll it says run with Visual Studio

![image](https://cloud.githubusercontent.com/assets/20506001/16903382/8babbc10-4c4a-11e6-82a0-6aed25435868.png)


Here is my project json:
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
This was created in Visual Studio.

**Comment by Petermarcu** [comment]
Did you try "dotnet App.dll"?

**Comment by sb421** [comment]
Nevermind, it is working.
