### ISSUE TITLE
Is bounds check elimination removed from for loops with i < array.Length ?

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/core#2280]
Using .net core 3.0 Preview 2

I have noticed the bounds check elimination is not happening any more. Is it removed from RYU JIT?
I have the following code:
```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Arrays
{
    [DisassemblyDiagnoser]
    [SimpleJob(launchCount: 1, warmupCount: 5, targetCount: 20)]
    public class TestSuite
    {
        const int itemCount = 64 * 1024 * 1024;
        static readonly int[] items = new int[itemCount];
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Benchmark]
        public void Loop1()
        {
            for (var i = 0; i < items.Length; i++)
            {
                items[i] *= 3;
            }
        }
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Benchmark]
        public void Loop2()
        {
            var count = itemCount - 10;
            for (var i = 0; i < count; i++)
            {
                items[i] *= 3;
            }
        }
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Benchmark]
        public unsafe void Loop3()
        {
            fixed (int* item = items)
                for (var i = 0; i < itemCount; i++)
                {
                    item[i] *= 3;
                }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<TestSuite>();
        }
    }
}
```
My common sense expects Loop1 and Loop3 should be the same and Loop2 should be slower as with simple Length check RyuJIT was checking effectively eliminating the bounds check for array. However results say : 
```
 Method |     Mean |    Error |   StdDev |
------- |---------:|---------:|---------:|
  Loop1 | 96.63 ms | 4.302 ms | 4.782 ms |
  Loop2 | 89.44 ms | 2.373 ms | 2.638 ms |
  Loop3 | 67.04 ms | 6.268 ms | 7.218 ms |
```

And again checking the disassembly code from BDN for loop 1:

```

Arrays.TestSuite.Loop1() |  
-- | --
  | xor     esi,esi
  | mov     rcx,7FFA0C0462F0h
  | mov     edx,1
  | call    coreclr!coreclr_shutdown_2+0xd8e0
  | mov     rax,1EB90002B98h
  | mov     rax,qword ptr [rax]
  | cmp     dword ptr [rax+8],0
  | jle     M00_L01
M00_L00 |  
  | mov     rax,1EB90002B98h
  | mov     rax,qword ptr [rax]
  | cmp     esi,dword ptr [rax+8]         ###still checking the bounds here!!!
  | jae     00007ffa`0c0f8139
  | movsxd  rdx,esi
  | lea     rax,[rax+rdx*4+10h]
  | mov     edx,dword ptr [rax]
  | lea     edx,[rdx+rdx*2]
  | mov     dword ptr [rax],edx
  | inc     esi
  | mov     rax,1EB90002B98h
  | mov     rax,qword ptr [rax]
  | cmp     dword ptr [rax+8],esi
  | jg      M00_L00
M00_L01 |  
  | add     rsp,20h

```
As with line `esi,dword ptr [rax+8]` there is still bounds check happening.
Is this optimization revoked?

**Comment by mikedn** [comment]
The following should work as expected:
```C#
int[] items = TestSuite.items;
for (var i = 0; i < items.Length; i++)
{
    items[i] *= 3;
}
```
In general, the index and the array reference must be local variables. Range check elimination might work when they're not but a relatively recent JIT bug fix has made the JIT more conservative in this regard.

**Comment by mikedn** [comment]
> and Loop2 should be slower

FWIW cases like Loop2 may be better served by spans:
```C#
Span<int> s = items.AsSpan().Slice(0, itemCount - 10);
for (var i = 0; i < s.Length; i++)
    s[i] *= 3;
```
or the more compact
```C#
foreach (ref int item in items.AsSpan().Slice(0, itemCount - 10))
    item *= 3;
```

**Comment by OnurGumus** [comment]
@mikedn Thanks for clarifiying. Yes making it local variable works. I think I can live with it. So I will close the ticket. Strangy loop2 got also faster but from assembly code I can see it keeps the bounds check.

And Thanks for the span hint. That's a clever way to eliminate bounds check that I didn't think it was possible. And I would have avoided foreach for performance but that also runs as fast.

**Comment by mikedn** [comment]
> Strangely loop2 got also faster but from assembly code I can see it keeps the bounds check.

Not surprising, things tend to work better if you use local variables. The JIT can sometimes introduces such local variables by itself by CESing loads, but it doesn't always work as well.

> And I would have avoided foreach for performance but that also runs as fast.

Note that `foreach` always had special support in the C# compiler for arrays (and now spans) so that `foreach (var i in a)` is the same as `for (int i = 0; i < a.Length; i++)`. Bonus, if `a` is not a local variable the C# compiler automatically creates a temporary variable for it thus avoiding the issues associated with using the array reference from a static/instance field.

If it weren't for the fact that your code modifies the array, the best solution for code like `Loop1` would be to simply use `foreach`:
```C#
foreach (var i in items)
    sum += i;
```
will have the range check eliminated without you having to copy `items` to a local variable.
