### ISSUE TITLE
Channel for notifications of new releases

### ISSUE THREAD

**Issue by jjpepper** [dotnet/core#2282]
# Notification of releases

Is there an official way for people to be notified via email (or something similar) when new dotnet core framework versions are released?  Visual Studio updates don't seem to keep the installed dotnet core framework up to date.

**Comment by leecow** [comment]
Hi @jjpepper , We don't have any subscription channels beyond what is already provided by Visual Studio. I'm surprised that Visual Studio is not prompting you for .NET Core updates as the functionality for included versions (eg VS2017 has 1.0, 1.1 and 2.1) is definitely there.

We do have a metadata endpoint which many are starting to monitor for update notification. You can find this at https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json.

**Comment by karelz** [comment]
Seems to be answered. If you have troubles with VS, please file feedback via VS bug reporting tool. Thanks!

**Comment by jjpepper** [comment]
> Hi @jjpepper , We don't have any subscription channels beyond what is already provided by Visual Studio. I'm surprised that Visual Studio is not prompting you for .NET Core updates as the functionality for included versions (eg VS2017 has 1.0, 1.1 and 2.1) is definitely there.

Are you saying that visual studio is updating you for .NET Core updates?

> We do have a metadata endpoint which many are starting to monitor for update notification. You can find this at https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json.

This helps a great deal.
