### ISSUE TITLE
What is .NET Core link not working

### ISSUE THREAD

**Issue by hanpari** [dotnet/core#229]
On the main page there are two links:

# Get Started

    If you're new to .NET Core and have 10 minutes to try it, start here:

        What is .NET Core?
        Get Started with .NET Core on Windows, OSX and Linux

Both leads here:
https://www.microsoft.com/net/core#windows

**I suppose the first one is incorrect. At least it is not explaining what is .NET Core**

**Comment by blackdwarf** [comment]
This is fixed by #225 .
