### ISSUE TITLE
.NET Core database connectivity

### ISSUE THREAD

**Issue by vinothkhanna** [dotnet/core#2290]
Security Patches causing issues in database connectivity

All,

After installing the following security patches on our Database Server (Windows Server 2012), all .NET Core applications > 2.1 ceased to connect to database server. Any applications with .NET Core 2.0 or microsoft/aspnetcore images are working fine. 

Patches : 
![image](https://user-images.githubusercontent.com/20160888/52359847-b4335200-2a60-11e9-94bb-bdd17c9af7ba.png)

Can someone let us know if the above patches have a potential to cause impact on .NET Core images? 
It fails to connect to the physical server via TCP & not even considering the database.

**Comment by karelz** [comment]
@vinothkhanna are you seeing the problem on more than one machine? (to avoid corrupted install or something)
Did you try to debug the problem, or isolate a repro? (minimal repro would be ideal)

**Comment by vinothkhanna** [comment]
@karelz My entire organization is facing this issue. All applications with .NET Core > 2.1 are not working. Am working with Microsoft team on this, though they are mostly Network team, just wanted to post the issue in .NET Core forum as well. If I use microsoft/aspnetcore image with 2.0 it works. Btw, to your question, all the repos are facing this issue.

**Comment by karelz** [comment]
> Btw, to your question, all the repos are facing this issue.

FYI: I meant repro - isolated small app reproducing the problem ...

Closing as it is being followed up on by support.
If there are more people hitting this problem, we can reopen and look into it deeper. Thanks for your report!
