### ISSUE TITLE
BadImageFormatException: System.Security.Permissions

### ISSUE THREAD

**Issue by sansjunk** [dotnet/core#2294]
This exception is thrown during build when the LicenseCompiler is run to generate a license for the component. The project is multi-target and it works fine for net40 target, issue only happens for netstandard2.0 build. Below is the full error details.

```
error LC0004: Exception occurred creating type 'Acme.Licensing.License, Acme.Feature, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fc8cb3ab6a24df63' System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.BadImageFormatException: Could not load file or assembly 'System.Security.Permissions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
---> System.BadImageFormatException: Could not load file or assembly 'file:///C:\Users\User\.nuget\packages\system.security.permissions\4.5.0\ref\netstandard2.0\System.Security.Permissions.dll' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
---> System.BadImageFormatException: Cannot load a reference assembly for execution.`
```

**Comment by karelz** [comment]
Do you have exact steps to reproduce it? What is LicenseCompiler and where do I find it and how do I run it?
Ideally provide steps starting with clean latest VS + latest .NET Core installed on machine. Thanks!

**Comment by karelz** [comment]
Actually looking at the details, it seems the app.library tries to load a reference assembly for execution: `Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context`
Who owns the library / app Acme? Is that Microsoft product?

**Comment by sansjunk** [comment]
[LicenseCompiler](https://docs.microsoft.com/en-us/dotnet/framework/tools/lc-exe-license-compiler) is a .NET Framework tool. In order to provision a runtime license it loads and inspects the assembly being built. This is where the issue shows up.

**Comment by karelz** [comment]
OK< how can I reproduce it locally?
Can you please try to create minimal repro?

**Comment by karelz** [comment]
Not actionable. Closing. Feel free to reopen when there is minimal repro.

**Comment by gnosticeinfotech** [comment]
Sorry I was held up with something else and couldn't respond. Here is a simple solution and two projects that can be used to repro this. When you build ConsumerApp the License Compiler tries to obtain a license and fails.
[LicenseToolIssue.zip](https://github.com/dotnet/core/files/2991100/LicenseToolIssue.zip)

**Comment by sansjunk** [comment]
Sorry I was held up with something else and couldn't respond. Here is a simple solution and two projects that can be used to repro this. When you build ConsumerApp the License Compiler tries to obtain a license and fails.
[LicenseToolIssue.zip](https://github.com/dotnet/core/files/2991103/LicenseToolIssue.zip)

**Comment by sansjunk** [comment]
@karelz Can you please reopen this?

**Comment by danmosemsft** [comment]
@zsd4yr do you know where license compiler comes from ? I assume we have a .NET Core version. I know it's very Winforms focused.

**Comment by zsd4yr** [comment]
> @zsd4yr do you know where license compiler comes from ? I assume we have a .NET Core version. I know it's very Winforms focused.

I am completely unfamiliar -- you mean this? https://docs.microsoft.com/en-us/dotnet/framework/tools/lc-exe-license-compiler it is a part of VS

After a brief talk with @Tanya-Solyanik , it is not surprising at all to us that a tool using a library which is not supported on Core would not work in VS when run on a multi-targeted project. This is the scenario, correct? I do not think we have a larger story for licensing

**Comment by danmosemsft** [comment]
I see. Feel free to close. You might check with @OliaG what the story is for lc.exe though. I belivee it's been commonly requested for Core and as I mentioned often comes up in a winforms context.

**Comment by carlossanlop** [comment]
No comments in a month. Closing.
