### ISSUE TITLE
error in dotnet aspnet-codegenerator razorpage -m Movie -dc AppDbContext -udl -outDir Pages\Movies --referenceScriptLibraries

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/core#2297]
Hi

I run these commands:
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet tool install --global dotnet-aspnet-codegenerator

My web app Project v 2.2.101 start correctly but _dotnet aspnet-codegenerator razorpage -m Movie -dc AppDbContext -udl -outDir Pages\Movies --referenceScriptLibraries_ not work for scaffolding movie.

first error : hostfxr.dll not found in "C:\Users\sap-komaei.CII\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.1\dotnet-aspnet-codegenerator\2.2.1\tools\netcoreapp2.1\any".
So I copied it from C:\dotnet\host\fxr\2.2.0 to above path.

now command give  this error : **The specified framework 'Microsoft.NETCore.App', version '2.1.3' was not found.  - Check application dependencies and target a framework version installed at:
      C:\Users\sap-komaei.CII\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.1\dotnet-aspnet-codegenerator\2.2.1\tools\netcoreapp2.1\any\
  - Installing .NET Core prerequisites might help resolve this problem:      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download**

._csproj_ :
![image](https://user-images.githubusercontent.com/17564001/52530915-a6145880-2d22-11e9-875a-ae5b2da3ef45.png)

I can not install anything in my pc for network policies in my work. I downloaded vs code portable and _dotnet-sdk-2.2.101-win-x64portable_ and extracted it to _C:\dotnet_ and add C:\dotnet to Path variable.
Every thing work except scaffolding.

**Comment by mammadkoma** [comment]
oooooooooooooooooooooooo
I deleted all files and folders in my user folder (C:\Users\sap-komaei.CII\.dotnet)
Then run _dotnet tool install --global dotnet-aspnet-codegenerator_ agin
Now scaffolding worked for movie.

**Comment by Eilon** [comment]
@mammadkoma OK so this issue is resolved?

**Comment by mammadkoma** [comment]
Yes
