### ISSUE TITLE
Build error on arm64 - BindingFlags not found

### ISSUE THREAD

**Issue by ranjeshj** [dotnet/core#2299]
# Issue Title

BindingFlags not found when building for arm64. CS7069: Reference to type 'BindingFlags' claims it is defined in 'System.Reflection', but it could not be found

# General

When building for arm64, we get a build error for BindingFlags
CS7069: Reference to type 'BindingFlags' claims it is defined in 'System.Reflection', but it could not be found

The same code builds find for other configurations.

The repo/pull request where this can be repro'd can be found below.
https://github.com/Microsoft/microsoft-ui-xaml/pull/288

**Comment by karelz** [comment]
@wfurt any idea?

**Comment by wfurt** [comment]
There were few cases when things moved between corefx and coreclr and you would get strange errors when caught in wrong snapshot. That would not explain why other platforms would work. I assume you build in same tree? When cross-compiling or changing target OS or ARCH, make sure you clean whole build tree.
If you still have issue please post exact steps and perhaps bit of logs so we can try to reproduce it.

**Comment by karelz** [comment]
Not actionable, closing.
