### ISSUE TITLE
brew link --force openssl not working

### ISSUE THREAD

**Issue by paulopez78** [dotnet/core#230]
Hello,
When installing  [.net core](https://www.microsoft.com/net/core#macos) you have to install the openssl dependency but when trying to link with `brew link --force openssl` is not working, I've got that error:
`Linking /usr/local/Cellar/openssl/1.0.2h_1... 
Error: Could not symlink share/man/man5/config.5ssl
/usr/local/share/man/man5 is not writable.`

I've found a solution just executing that command: 
`sudo chown -R `whoami`:admin /usr/local/share` 
I think it should be pointed out in the official web page. I've tried in different mac laptops with latest OSX(10.11.6) and it's all the time failing so it should be a common problem for everyone.
I don't know if I'm right or not or I'm doing something wrong but I think we should provide better instructions for "non windows users", by the way +1 for the workaround using oh-my-zsh.

Thanks!!

**Comment by blackdwarf** [comment]
@paulopez78 I'm of a split mind on this. On one hand, I agree with you that people will get confused by this error (which comes from the way El Capitan changes permissions on `/usr` directory) and that they would benefit from gettting this on the getting started page. On the other hand, this is not a clear tooling/.NET problem but `brew` problem. This means that we would have to match any brew known issues on the getting started page, which would inflate the instructions (text) that people need to read. 

I'm thinking we could put this into the "Known issues" document and then point people in the getting started instructions to that document. Something like (provisional text): "if you encounter any issues with installation, please check out the Known Issues document". 

Thoughts?

**Comment by paulopez78** [comment]
@blackdwarf I agree with you it's a `brew` issue but it's the recommended way to install the dependencies in the home page for macusers. I really want to help to make dotnetcore better for macusers as in my company we're working with that setup. From my point of view I'd like to have that warning or workaround just after or before the workaround for `oh-my-zsh`, if not at least some link pointing to known issues. I can write the workaround for that problem I'm willing to help that community.

Thanks.

**Comment by blackdwarf** [comment]
OK, so I think that adding this to the known issues section and will be updating the site with the warning and the link. I think this is a better solution.

**Comment by blackdwarf** [comment]
This is now added to the known issues: https://github.com/dotnet/core/blob/master/cli/known-issues.md#problems-using-brew-to-link-openssl-after-uprading.

**Comment by paulopez78** [comment]
Thanks @blackdwarf  for the update, from my side the issue is closed.
