### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client'

### ISSUE THREAD

**Issue by jigarce** [dotnet/core#2301]
# InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client'

I have uploaded .NET core 2.1 website on AWS .

Installed framework 4.7 and Dot net core framework 2.2 from https://dotnet.microsoft.com/download

Website URL : http://ec2-13-127-52-63.ap-south-1.compute.amazonaws.com/login

not able to found why it is giving error for the package 

Regards,
Jigar

**Comment by n-alex-white** [comment]
@jigarce I notice you closed this - did you find out what the problem was? I’m experiencing the same problem right now...

**Comment by jigarce** [comment]
Yes,

It was website publish issue.

Select Deployment Mode : Self-Contained 

![image](https://user-images.githubusercontent.com/8125778/54338175-1f230a80-4657-11e9-9381-0f5ecef8c34c.png)

**Comment by n-alex-white** [comment]
Great advice, worked for me too.

Thanks
