### ISSUE TITLE
Inconsistencies in releases.json format for 2.2.2?

### ISSUE THREAD

**Issue by martincostello** [dotnet/core#2307]
# Inconsistencies in releases.json?

We've recently wrote some automation as part of our EC2 AMI image provisioning to automate downloading the relevant versions of .NET 2.1 and 2.2 from the new `releases.json` files.

However, this automation has failed to find 2.2.2 this morning because the file names don't match the convention we assumed would be used that held true for 2.2.0 and 2.2.1.

For example, the ANCM hosting bundle has this format for 2.2.0 and 2.2.1:

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/2.2/releases.json#L705-L710

However for 2.2.2 it has this format:

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/2.2/releases.json#L264-L269

Because we are using the `name` as the key, it has broken the query we were using to find the relevant assets to download and install.

Similarly, this also applies to the runtime. For 2.2.1:

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/2.2/releases.json#L516-L521

For 2.2.2:

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/2.2/releases.json#L75-L80

Are our assumptions incorrect, and we should have been keying on `rid` rather than `name`, or were the assumptions correct but the file format is incorrect?

These assumptions _have_ held for the 2.1 channel's file, which has caused extra confusion on our part, so 2.1.8 was found by our automation.

/cc @leecow

**Comment by martincostello** [comment]
The same inconsistencies are in the older file format too:

2.2.1:

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/releases.json#L353

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/releases.json#L366

2.2.2:

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/releases.json#L29

https://github.com/dotnet/core/blob/0a53ce5d8b0700dd8db0784c208bfb8db47a42d4/release-notes/releases.json#L42

**Comment by leecow** [comment]
Thanks for the report @martincostello. The versions in the field names was missed by my validation code. Will get that fixed up right away. 

With respect to the Hosting installer, it includes both x86 and x64. Because there are no .NET Core rids which cover that situation, I couldn't decide on a route so left it empty. Perhaps 'win-x86-x64' would be appropriate?

**Comment by martincostello** [comment]
Thanks @leecow - I don't have a strong opinion regarding the `rid` being empty, I was just looking at it to be reactive to the change if it wasn't a mistake.

If the original assumptions our automation solution made were correct and this was just an unfortunate mistake, then I guess I can just remove the changes I made to work around this earlier today.
