### ISSUE TITLE
Include Performance evolution of netcore versions on readme or related wiki/site

### ISSUE THREAD

**Issue by juniormayhe** [dotnet/core#2308]
Could we have in readme a table follow up the performance evolution of all netcore frameworks 1.x, 2.1.x, 2.2, 3.0? 

This would provide a public overview of **netcore performance improvements**. 
It can also help us justify a netcore migration in our companies and encourage IT to update netcore frameworks.

In this public readme we could show speed for some common use cases as presented by @stephentoub, [available here](https://blogs.msdn.microsoft.com/dotnet/2018/04/18/performance-improvements-in-net-core-2-1).

**Comment by karelz** [comment]
@juniormayhe aren't the blog posts sufficient? Or TechEmpower benchmarks?
The problem is that everyone uses different benchmarks, or cares about different things, so it is EXTREMELLY hard to provide anything super-useful.

cc @adamsitnik @billwert @brianrob

**Comment by karelz** [comment]
No response, closing

**Comment by juniormayhe** [comment]
> @juniormayhe aren't the blog posts sufficient? Or TechEmpower benchmark results? ... or blog post like this one: https://www.ageofascent.com/2019/02/04/asp-net-core-saturating-10gbe-at-7-million-requests-per-second/
> The problem is that everyone uses different benchmarks, or cares about different things, so it is EXTREMELLY hard to provide anything super-useful.
> 
> cc @adamsitnik @billwert @brianrob

Yes, I understand this might be hard. Every benchmark will care more or less about some aspects. I picked a [sample](https://github.com/juniormayhe/BenchmarkAndSpanExampleNetcore) of Steve Gordon to evaluate netcore performance on string manipulation and first runs on 3.0 were slower but after couple of executions it got similar to 2.2 and 2.1. Hope netcore 3.0 performance won't decrease!

Thanks for the heads up Karel

**Comment by adamsitnik** [comment]
@juniormayhe you can also run all the benchmarks we have for testing .NET Runtimes performance in the dotnet/performance repository

the docs that explain how to do it:
https://github.com/dotnet/performance/blob/master/docs/benchmarkdotnet.md#Multiple-Runtimes 
the benchmarks: https://github.com/dotnet/performance/tree/master/src/benchmarks/micro

it's more or less **a single command**:

```cmd
dotnet run -c Release -f netcoreapp2.1 --filter * --runtimes netcoreapp2.1 netcoreapp3.0
```
