### ISSUE TITLE
Allow "Add Reference" to .NET Core class library that uses .NET Framework from a traditional class library

### ISSUE THREAD

**Issue by ryanelian** [dotnet/core#231]
First of all, I would like to say that I love how .NET Core projects can automatically manage package dependencies. Brilliant.

Hence I began developing projects using ASP.NET MVC Core, albeit still using the full .NET 4.5 instead of .NET Core due to various reasons. So my class libraries `project.json` often ended up like this:

```json
{
  "version": "1.0.0-*",

  "dependencies": {
  },

  "frameworks": {
    "net45": {
    }
  }
}
```

Which is great and works beautifully in MVC Core land. However, as soon as someone need `Add Reference` to my class libraries without being packaged into NuGet packages (actually I haven't tried packaging those classes into NuGet packages, but I don't see why they wouldn't work), this happens:

```
---------------------------
Microsoft Visual Studio
---------------------------
A reference to 'My.Class.Library' could not be added. An assembly must have a 'dll' or 'exe' extension in order to be referenced.
---------------------------
OK   
---------------------------
```

I realized that this scenario is the opposite of the ".NET Core project needs to reference the .NET 4.5 DLLs", but is it possible to have this feature for convenience?

**Comment by blackdwarf** [comment]
@ryanelian can you please open a new issue on aspnet/tooling and close this one? That repo will be a better place for this issue. Thanks!

**Comment by blackdwarf** [comment]
Actually, now that I look at the issue, I believe this should be mitigated with moving to `csproj`. Will close this. Please reopen if you feel this was in error.

**Comment by Daniel15** [comment]
> I believe this should be mitigated with moving to csproj

@blackdwarf Is there a task I can follow for this?
