### ISSUE TITLE
Recommended version number scheme for SDK?

### ISSUE THREAD

**Issue by riezebosch** [dotnet/core#2314]
For maintainting the [dotnetcore-chocolateypackages](https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages) I want to add `3.0-preview` but I'm not sure what version for the SDK currently is recommended.

The SDK version from the [releases.json](https://raw.githubusercontent.com/dotnet/core/master/release-notes/3.0/releases.json) is not `semver` and the `latest-release` tend to be aligned with the runtime and not the SDK.

Should I be using the `3.0-preview2` for now and switch to runtime & sdk specific versions when out of preview? Or is the `latest-release` version the way forward and encapsulates this underlying versions?

Any advice on this?

**Comment by leecow** [comment]
We're in the process of standing up release branches which would make sense for you to follow. For the sdk, picking up the latest from release/3.0.1xx should do the trick. 

@livarcocc to confirm.

**Comment by riezebosch** [comment]
Got it. But what about the `aspnetcore-runtime` and `windows-hosting`?  Should it be `3.0.0-preview2`? Because there are already multiple `3.0.0-preview` releases that only differ in last part (which doesn't fit into `semver`).

**Comment by leecow** [comment]
All components should be picking up the *-preview{n}-{buildnumber} scheme.

**Comment by riezebosch** [comment]
But the {buildnumber} part is breaking semver and the *-preview part seems not unique.

**Comment by karelz** [comment]
Why is the {buildnumber} part breaking semver? It seems complaint to me according to: https://semver.org/#spec-item-9

That said, I don't think we claimed we follow semver, although it would be nice ...

**Comment by riezebosch** [comment]
My point is that translating the version from the `releases.json` into something that is unique and [supported by chocolatey](https://github.com/chocolatey/choco/issues/1610) is or might be a problem. It seems to work now for creating packages but I'm not sure yet if it can be published in that format.

```
 dotnetcore-sdk.3.0.100-preview-010184.nupkg
```

**Comment by leecow** [comment]
I would think that's OK. 

We're in the process of finishing up Preview 3 (hopefully out Tuesday) and the SDK version will look like `3.0.100-preview3-010402` (not finale, just an example from the current build).

**Comment by riezebosch** [comment]
Okay, it looks like it's possible: https://chocolatey.org/packages/dotnetcore-runtime.install/3.0.0-preview-27324-5 😄
