### ISSUE TITLE
Please add download archive for 1.0.14 or include RHEL on main download page

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core#2319]
# Please add download archive for 1.0.14 or include RHEL on main download page

Can you add a download archive for 1.0.14 to https://github.com/dotnet/core/tree/master/release-notes/download-archives ?

The GitHub download archives include RHEL builds but the regular download page doesn't.  I'm really looking for the RHEL download.  So if you could add that to https://dotnet.microsoft.com/download/dotnet-core/1.0 that would work too.

**Comment by karelz** [comment]
@leecow can you please help here?

**Comment by leecow** [comment]
@vivmishra

**Comment by vellozzi** [comment]
I found the RHEL build here: https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.14/1.0.14-download.md
