### ISSUE TITLE
Is there any documentations to install .Net Core on Windows IoT Core?

### ISSUE THREAD

**Issue by alfeosilvestro** [dotnet/core#232]
Hi,

I am a developer and I am so excited about .Net Core release. 

I would like to try it on Windows IoT Core. Since it is ARM based processor, I would like to check if current release supports IoT Core and if it is supported, is there any documentations that I can refer to?

Thanks!

**Comment by Kinani** [comment]
Anything on this? 
Just to make sure, Currently there's noway to run .NET Core apps on ARM devices. more specifically Windows 10 IoT?

**Comment by BenjaminAbt** [comment]
@Kinani .NET Core on ARM is on roadmap for Q4 2016 / Q1 2017
https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by Petermarcu** [comment]
Daily builds are being published here: https://github.com/dotnet/core-setup

I've had .NET Core running on Win10 IoT Core for a few months now. I published an app from my Windows machine using a matching framework, extracted the zip from the links on that page and was up and running.

Give it a try and let us know how it goes. Should run great! :)

**Comment by Petermarcu** [comment]
BTW, I followed the instructions here to get it all configured on my Pi 3. https://developer.microsoft.com/en-us/windows/iot

**Comment by darxis** [comment]
@Petermarcu I am tryign to get an empty ASP.NET Core running on W10 IoT. I've downloaded the daily build for Windows arm32 and extracted it. Then, when I run the dotnet tool, it gives me the following error:
> U:\netcore\dotnet\dotnet.exe : Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
    + CategoryInfo          : NotSpecified: (Did you mean to...tnet SDK from: :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
  > http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by Petermarcu** [comment]
I got an email but dont see the comment here so I'm putting it in: 

>> @Petermarcu I am tryign to get an empty ASP.NET Core running on W10 IoT. I've downloaded the daily build for Windows arm32 and extracted it. Then, when I run the dotnet tool, it gives me the following error:
```
U:\netcore\dotnet\dotnet.exe : Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
+ CategoryInfo : NotSpecified: (Did you mean to...tnet SDK from: :String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

This is because the zip files are only for the runtime. They don't contain the SDK. There are a few options. 

I wrote the app on another machine and published to IoT Core. The app didn't have any native code in it. Just managed code. I published it and copied it over to the IoT Core machine and ran it by calling dotnet myapp.dll.

The alternative way to do it is to take an existing SDK like this one: https://go.microsoft.com/fwlink/?LinkID=834991

And overwrite everything that is also in here: https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-win-arm.latest.zip

That should replace all the native components and give you a runnable SDK on the IoT Core machine.

**Comment by Brilbroeder** [comment]
How do you install the core on the IOT-device ?

**Comment by pwoestmann** [comment]
@Petermarcu it would be relly nice if you could write a short tutorial about how to get .net Core beta working on Windows 10 IoT. Thanks in advance

**Comment by Petermarcu** [comment]
@pwoestmann , I finally got to this and wrote instructions for both Win10 IoT Core and Linux on the Raspberry Pi. Things are still early but you can definitely get code running :) See my doc here: https://github.com/dotnet/core/blob/RaspberryPi/samples/RaspberryPiInstructions.md

**Comment by Petermarcu** [comment]
Give it a try and let me know if it works out for you.

**Comment by pwoestmann** [comment]
@Petermarcu Thank you very much! It seems to auspicious. Ill definitely give it a try next week.

**Comment by Petermarcu** [comment]
Yeah, it was surprisingly straight forward :) very soon here we'll have a story for doing everything on the Pi although it will likely always be a better experience to develop elsewhere and deploy to the Pi.

**Comment by h3smith** [comment]
Excited for this. Great job guys.

**Comment by BitawareUnleashed** [comment]
@Petermarcu thanx for this great news! I tryed to follow your instructions, but how can I do that:

> Extract dotnet-win-arm.1.2.0-beta-001291-00.zip to a folder on your Pi and cd into that folder in the terminal.

Thanx a lot!

**Comment by Petermarcu** [comment]
@BitawareUnleashed, I believe I actually extracted it on another machine and just copied the bits over using WinSCP.

**Comment by Petermarcu** [comment]
I'm going to close this issue now as we have published instructions. I plan on making some updates to them soon but this should all be unblocked now.

**Comment by BitawareUnleashed** [comment]
@Petermarcu Please, on Raspberry PI how you can do that:

> Add the folder where you extracted it to your path.

Thanx

**Comment by Petermarcu** [comment]
@BitawareUnleashed, I run 

```
set PATH=<location_where_I_put_dotnet.exe>;%PATH% 
```

**Comment by BitawareUnleashed** [comment]
Thanx a lot!
Now I have another error while running a simple asp.net core app

> c:\DotNETCore\dotnet : The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
>     + CategoryInfo          : NotSpecified: (The specified f... was not found.:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
> 
>   - Check application dependencies and target a framework version installed at:
>       c:\DotNETCore\shared\Microsoft.NETCore.App\
>   - The following versions are installed:
>       1.2.0-beta-001291-00
>   - Alternatively, install the framework version '1.0.1'.
> 

What could be?
I'm sorry to bug you.

**Comment by Petermarcu** [comment]
Is your project a csproj or a project.json? Are you using VS 2017?

**Comment by BitawareUnleashed** [comment]
Hi @Petermarcu and thanx,
no, I've made the dll with visual studio 2015 enterprise with ASP.NET Core preview installed. On my PC it works well in each configuration, but when I try to run it on PI that error appear.
Note that I've created the solution with the tempalte and I haven't modified the code.
Thanx for answer

**Comment by Petermarcu** [comment]
Did you do the step in my writeup to update the helloworld.runtimeconfig.json in the app folder to say 1.2.0-beta-001291-00 in it?

I think alternatively I think you could launch the app like this:

`dotnet --fx-version 1.2.0-beta-001291-00 MyApp.dll`

I haven't tried the latter but it could work and would be nicer :)

**Comment by BitawareUnleashed** [comment]
Oh... I've lost that step... Now I can't try, but asap I'll try and I'll answer you, but I think could be that the problem.
Thanx a lot

**Comment by BenjaminAbt** [comment]
This is online now: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by 0807Jpatel** [comment]
@Petermarcu @BenjaminAbt   can you update RaspberryPiInstructions.md  since console .net core apps don't generate .exe  but .dll

**Comment by Petermarcu** [comment]
@0807JPatel the way the instructions are written, you will get an exe you can just run.
