### ISSUE TITLE
Problems marshalling strings on linux platform

### ISSUE THREAD

**Issue by bachowny** [dotnet/core#2325]
We are using dotnet version 2.4.1 in our automated tests which we perform on both Windows and Linux (Centos 7), however there is a failure in our tests but only on Linux and I'm trying to work out whether the problem is in a particular 3rd party native DLL or in dotnet.

There is a certain string that we are checking which contains the following characters:
`A.P. MÖLLER - MAERSK B`

We read this string from an XML file and compare it to one which has arrived over the network which we must Marshal in from the 3rd party native DLL using PtrToStringAnsi. I can confirm that the network data is the same on both Windows and Linux.

On Windows the string is correctly marshalled. On Linux we get 
`A.P. MLLER - MAERSK B[NUL][NUL]`

I've tried using PtrToStringUTF8 instead and then I get
`A.P. M�LLER - MAERSK B`

Can anyone confirm or deny a difference in behaviour between these functions on different OSes? Either way it will help me focus my search for a fix!

Thanks,
Bachowny Plamborgs.

**Comment by karelz** [comment]
Either create minimal repro without any 3rd party library, or get it under debugger and see what the native side has vs. what you're recieving in .NET layer.

**Comment by bachowny** [comment]
I have created the following minimal repro:

`using System;
using System.Runtime.InteropServices;

namespace ConsoleApp2
{
  class Program
  {
    static void Main(string[] args)
    {
      IntPtr lPtr = Marshal.AllocHGlobal(2);

      Marshal.WriteByte(lPtr, 0, 0xD6);
      Marshal.WriteByte(lPtr, 1, 0x00);

      string lStr = Marshal.PtrToStringAnsi(lPtr);
      Console.WriteLine("Native land said: '" + lStr + "'");
      Console.ReadKey();
    }
  }
}`

Windows says:
`Native land said: 'Ö'`

Linux says:
`Native land said: ''`

**Comment by karelz** [comment]
I believe that Unicode processing is OS specific - @tarekgh can you please comment?

**Comment by tarekgh** [comment]
@bachowny I believe this operation depends on the default codepage on your system. On Windows I believe the default code page in your system is 1252 which has the code point 0xD6 as "Ö". But on Linux you can have different codepage (which is most of the time is Utf8). decoding 0xD6 using UTF8 will result invalid character (or 0xFFFD)

First, you want to know what encoding of the bytes you are receiving over the wire, then would be better to use the encoding class to do the decoding using that bytes encoding. 
Here is some example if you want to use 1252 codepage:

```C#
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Encoding encoding1252 = Encoding.GetEncoding(1252);
            string s = new String(encoding1252.GetChars(new byte[] { 0xD6 }));
```

**Comment by bachowny** [comment]
Thanks very much for the insight @tarekgh 

Is there a straightforward way to read out a null-terminated set of bytes using `Marshal` or would I have to do that by hand?

I will definitely give it a try tomorrow (I'm just leaving now) and report back if I have a solution.

**Comment by karelz** [comment]
Isn't 0 byte allowed part of a Unicode character? That would make it impossible without interpretting the characters properly ...

**Comment by bachowny** [comment]
@karelz Probably, but I know this is actually an ANSI string coming from a C interface, so even if I end up truncating the string I'll only be mishandling things in the same way the 3rd party will mishandle it.

**Comment by bachowny** [comment]
I've put together the following improved program which does operate correctly on Linux but I have further questions about it...

```
c#
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace ConsoleApp2
{
  class Program
  {
    public static Encoding mLatinEncoding;

    static void Main(string[] args)
    {
      Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
      mLatinEncoding = Encoding.GetEncoding(1252);

      IntPtr lPtr = Marshal.AllocHGlobal(2);

      Marshal.WriteByte(lPtr, 0, 0xD6);
      Marshal.WriteByte(lPtr, 1, 0x00);

      string lStr = PointerToString(lPtr);
      Console.WriteLine("Native land said: '" + lStr + "'");
      Console.ReadKey();
    }

    public static string PointerToString(IntPtr aPointer)
    {
      if (aPointer.Equals(IntPtr.Zero))
      {
        return "";
      }
      else
      {
        int lOffset = 0;
        List<byte> lBytes = new List<byte>();

        while (lOffset < 999)
        {
          byte lByte = Marshal.ReadByte(aPointer, lOffset);
          if (lByte == 0) break;
          lBytes.Add(lByte);
          lOffset++;
        }

        return new string(mLatinEncoding.GetChars(lBytes.ToArray()));
      }
    }
  }
}
```

**Comment by bachowny** [comment]
@tarekgh So now the question I have is about this `CodePagesEncodingProvider`, for which I had to add a NuGet package and will have to work out how to make that work on the AWS instances we spin up to run these tests.

My question is simply is there another way to get this encoding? It seems that whatever is being used to parse the XML file that contains this string was already using the correct encoding. If I could just get a hold of that encoding I might not have to introduce this new package dependency.

**Comment by bachowny** [comment]
@tarekgh OK so kind of answering my own question here but this works just as well:

```c#
    public static string PointerToString2(IntPtr aPointer)
    {
      if (aPointer.Equals(IntPtr.Zero))
      {
        return "";
      }
      else
      {
        int lOffset = 0;
        List<char> lChars = new List<char>();

        while (lOffset < 999)
        {
          byte lByte = Marshal.ReadByte(aPointer, lOffset);
          if (lByte == 0) break;
          lChars.Add((char) lByte);
          lOffset++;
        }

        return new string(lChars.ToArray());
      }
    }
```

So now the question is, what is `Marshal.PtrToStringAnsi` doing to interfere with this seemingly straightforward operation? If I do

```c#
      char lChar = 'Ö';
      Console.WriteLine((int) lChar);
```

then the output is the same on both Windows and Linux. So it seems to me that `PtrToStringAnsi` is the thing that is getting this wrong.

**Comment by bachowny** [comment]
Sorry for the constant barrage of comments on this issue but for posterity this is now solved for me, and here is the slightly improved code.

```c#
    private unsafe char* mBuff = (char*) Marshal.AllocHGlobal(999);
    public unsafe string PointerToString(IntPtr aPointer)
    {
      if (aPointer.Equals(IntPtr.Zero))
      {
        return "";
      }
      else
      {
        int lOffset = 0;

        while (lOffset < 999)
        {
          byte lByte = Marshal.ReadByte(aPointer, lOffset);
          if (lByte == 0) break;
          mBuff[lOffset] = (char) lByte;
          lOffset++;
        }

        return new string(&mBuff[0], 0, lOffset);
      }
    }
```

**Comment by tarekgh** [comment]
It looks to me for your scenario you'll just need to use the ISO-8859-1 encoding, which you can use without using Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); at all. so you can just do 

```C#
Encoding isoEncoing = Encoding.GetEncoding(28591);
```

Your way casting the byte to a char may be acceptable if you don't care about the code point ranges 0~0x20 and 0x80~0x9F. I believe the ISO encodign would be more desirable to use. 

Let me know if you have any more questions.

**Comment by karelz** [comment]
Seems to be answered.

**Comment by bachowny** [comment]
@karelz I was waiting to see if someone knew why on Linux PtrToStringAnsi doesn't correctly handle ANSI characters even when the character code is identical on Linux and Windows.

**Comment by karelz** [comment]
I assumed that was answered by @tarekgh's response. Wasn't it?

**Comment by bachowny** [comment]
@tarekgh recommended a different encoding that could be used in his workaround. My question was why the ANSI encoding is not correct on Linux and why simply marshalling the character values (which is what one would expect ANSI marshalling to do) gives a different answer to the built in function.

Both platforms agree on the character code for the character in question and it is the same value as found in any quick google for "ANSI character codes", so why the discrepancy?

**Comment by tarekgh** [comment]
@bachowny PtrToStringAnsi is simply calling the String constructor with the SByte* you are passing. The string constructor is simply converting the bytes to Unicode values using the system code page. on Linux we always use Utf8 as system code page for all bytes conversions. So, this is by design on Linux.

**Comment by bachowny** [comment]
@tarekgh OK thanks, I understand now why there's a discrepancy. I can only assume there's some reason why this must be done and why PtrToStringAnsi is _not actually ANSI_ on Linux. We can now close this issue.
