### ISSUE TITLE
Unable to build .net core projects in Visual Studio

### ISSUE THREAD

**Issue by mgolois** [dotnet/core#2327]
I'm not sure what happened, but some some reasons any solutions with ..net core, .net standard projects are not building any more. No errors are throwns, just 
`========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========`

I updated visual Studio to the latest version `15.9.7` and updated dot .net core SDK, current version `2.2.104`.
I have cleaned the projects, deleted bin/obj, and vs folders, but still nothing. However, I can run the project thru command line with no problem using `dotnet run`. In visual studio, my dependencies, assemblies, ad project references are all displaying the yellow warning icon.
Am I missing something?

**Comment by karelz** [comment]
Did you try to repair VS? (to avoid corrupted install) ... Or reinstall of VS?
Does it happen only on one machine?
Does it happen for other project types (e.g. .NET Framework)

**Comment by mgolois** [comment]
@karelz, I'm going to try VS repair. 
Yes it happens on one machine, the same project works well on other computer.
I can run other .NET Framework projects with no problem, the issue is just with .net core and .net standard projects.
I'll try VS repair later tonight after work and see.

**Comment by karelz** [comment]
If it is problem only on one machine, I would recommend to fix it there - by repairing / reinstalling.
It is likely some setup / environmental issue. Tracking down such problem is super-costly for everyone involved.
If you find the root-cause, or if you have evidence of repro on other machines, then we can follow up. Thanks and good luck!

**Comment by mgolois** [comment]
@karelz - I tried VS repair that did not solve it. However, I realize that my .net core/.netstandard projects build fine in visual studio only if I run it as admin. This is happening only on my computer, not sure what's happening... anyway, I can run the projects now

**Comment by karelz** [comment]
@mgolois interesting. If you find out more, let us know. Otherwise I suggest to ignore it as one-machine environmental problem (aka costly to track down :().

**Comment by nefcanto** [comment]
I also have the same problem, only for some of my projects. Even for a solution of multi projects, some of them get built, while some don't. When I copy/paste code of those projects that are getting skipped to a new project, it gets built. I also copy the content of .csproj file. It's so frustrating. I ran into this after upgrading to 3.1.

@karlez, this is not one-machine environmental problem anymore. Could you please create a "force clear cache and restart" option in Visual Studio just like Android Studio?

**Comment by nefcanto** [comment]
For me [removing projects from solution and adding them again](https://stackoverflow.com/a/55259335/811785) worked. So stupid.

**Comment by nefcanto** [comment]
I highly recommend improving stdout in the algorithm that decides to skip a project during build. This way troubleshooting gets much easier. For now it only says "skipped" but doesn't give us a clue on "why skipped". After all, some code decided to skip it. That code can print out some info.
