### ISSUE TITLE
dotnet new -i '{path}' 2.1.504 vs 2.2.104

### ISSUE THREAD

**Issue by TomekDex** [dotnet/core#2328]
Hello
Are there any differences between the templates for these dotnet versions?

After upgrading to 2.2.104, this command stopped working.

It prints everything in the same way as in the previous version and doesn't add any templates to the list

**Comment by karelz** [comment]
@livarcocc @nguerrera can you please help route the question?

**Comment by livarcocc** [comment]
@vijayrkn @mlorbetske

**Comment by mlorbetske** [comment]
This issue was moved to dotnet/templating#1773
