### ISSUE TITLE
MSI Silent Install

### ISSUE THREAD

**Issue by leedhi** [dotnet/core#233]
Hi...  are there plans (or already something available) to make an MSI with silent install options for windows installations? The EXE currently doesn't support installing silently. I know I could use the ZIP package and add the location to the PATH. But I was hoping there was something a bit more elegant.

**Comment by blackdwarf** [comment]
@leedhi can you please open this issue on dotnet/cli and close this one? That repo is a much better place for this issue.

**Comment by Petermarcu** [comment]
Btw, it should already support a quiet install. Visual Studio installs it silently I believe.

**Comment by blackdwarf** [comment]
I don't know if the exe (bundle) supports a silent install though. I'm pretty sure that each individual MSI within it supports it.

**Comment by Petermarcu** [comment]
I just downloaded it and installed it from an admin command prompt by calling the exe with -q . Worked like a charm.

`DotNetCore.1.0.0-SDK.Preview2-x64.exe -q`
