### ISSUE TITLE
.Net Core 2.2 Auth AzureAD Startup Generated Code is Complete?

### ISSUE THREAD

**Issue by DanJ210** [dotnet/core#2331]
Generated startup code is very light and when I try it in other .Net Core 2.2 MVC Web Applications it doesn't work. I'm trying to find documentation on this small snippet of code but the .Net Core documentation is on 2.0 and doesn't talk about what's going on in 2.2, [.Net Core Documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-2.2)

# General

The code below is all that's in the .Net Core `Startup.cs` file to enable AzureAD auth. In previous .Net Core versions I had an `AccountController.cs` along with a couple of other files. In this, 2.2 version, there is none of those files which would be great if they are no longer needed in 2.2. But I'm trying to figure out how this is working because I'm updating .Net Core Web Apps that I have to 2.2 and I'm using the same code as shown below but am being told that `No AuthenticationScheme was specified, and there was no DefaultChallengeScheme found.` Which makes sense because it's not declared in `Startup.cs` but then how does this work for the app that .Net Core generates and not other apps?

So this is what I'm trying to understand, how does the code below work for the generated 2.2 .Net Core app and not when added to other 2.2 .Net Core apps?

```c#
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetCore#8180

**Comment by DanJ210** [comment]
@Eilon why was this closed?

**Comment by Eilon** [comment]
I moved it to the ASP.NET org: https://github.com/aspnet/AspNetCore/issues/8180

**Comment by DanJ210** [comment]
Oh excuse me, thank you.
