### ISSUE TITLE
Project version texts causing rpm builds fail with 'Unknown tag: x.x.x.x' (x are version numbers)

### ISSUE THREAD

**Issue by ahmedowsky** [dotnet/core#2332]
I am facing this issue since our first rpm package i've built.

I am building a .NET Core project on my Windows machine, and then copying the built project onto the CentOS machine and then wrapping it up in an RPM.

I have a spec file which kind'a automates rpm builds. To specify rpm's version info, this spec file reads my dll's version (file version). I set this version information using "project properties -> package -> Assembly version & Assembly file version & Package version" inputs over visual studio (2017-windows).

Sometimes, not always but quite frequently, those version numbers are causing rpm builds fail with 'Unknown tag: x.x.x.x' message (x-es are version numbers). I found a turnaround for that which is ridiculous but works great.

I am opening a web browser, searching for the version number i want to use. Once the search is complete, i copy the text from one of search results and paste that text into "assembly version", "assembly file version" and "package version" inputs.

For example: current version is '1.1.1.1' and i want to change it as '1.1.1.2'. Then i google '2', copy another '2' from one of the search results and paste it into the last inputs of "assembly version", "assembly file version" and "package version".

And this solution never fails. The text i copy from a google search result works, buy my keyboard's input doesn't...

I don't even know where this issue belongs but it doesn't make one's life easy.

**Comment by karelz** [comment]
I don't quite understand what is the problem - it seems that you cannot edit fields in package properties inside Visual Studio. Is that correct?
Does it happen on more than 1 machine?
Did you try latest VS build?

**Comment by ahmedowsky** [comment]
@karelz i know you don't like reading, it's hard or whatever but, can you at least read the title?
Your question is really so irrelevant, so absurd.
Details (including examples) are below the title.
**Those properties, are making, my rpm builds, to fail, if i use my keybord, to write, those version numbers.**

**Comment by karelz** [comment]
@ahmedowsky no need to get angry here ... I am just trying to help you here. Personal attacks won't speed things up.

The fact is I never heard about rpm builds. The title may be self-explanatory for you, but sadly it is not clear to me. And while I read all your text, it was not clear to me either. Otherwise I would not ask the questions above.

For example, it is still not clear to me if you are unable to type anything in the text boxes (from keyboard), or if the values are just not being respected when typed from keyboard.
BTW: That's why clear step-by-step repro steps (starting with new project) help clarify things. If you don't know where the issue is (which component), it is GREAT help and usually makes routing to the right place much faster.

**Comment by ahmedowsky** [comment]
I'm sorry, i really am. I didn't mean to upset you. I was assuming that someone commenting under this issue would know about rpm builds.

I can edit package inputs over VS no problem there. I can build the project, no problem there. Published dll's are also has the right version information on them. All cool on windows / VS part.

Here's a step-by-step example

* open a dotnet core console app / web api (doesn't matter)
* build it & publish it & copy them inside a centos7 machine
* create a spec file (this file is something like a rpm build instruction)
* modify that spec file so it would be able to read rpm package's version information directly from the published dll (by doing so you won't have to edit spec file for every new version)
* build rpm package for that published output inside the centos7 machine
* build passes, rpm package is ready (all cool)

* open project properties -> package
* change "assembly version", "assembly file version" and "package version" as you wish, using numbers on your keyboard (lets say 1.1.1.1)
* build it & publish it & copy them inside a centos7 machine
* build rpm package for that published output inside the centos7 machine
* build fails (usually)

* open project properties -> package
* change "assembly version", "assembly file version" and "package version" as you wish, by copy-paste-ing numbers from a google search result (lets say 1.1.1.1)
* build it & publish it & copy them inside a centos7 machine
* build rpm package for that published output inside the centos7 machine
* build **always** succeeds

**Comment by karelz** [comment]
Thanks for the steps! That will (hopefully) help me help you! ;)

> build fails (usually)

Why did you say "usually"? Is it intermittent? (as in repeating builds sometime fail) Or is it just random if the problem will be hit or not and once it is, then it is persistent? How often does it happen? (in either case)
Is the error the one from title? "Unknown tag: x.x.x.x' (x are version numbers)" ... so in this case it would be "... 1.1.1.1"?

This is overall very weird (and interesting ;)). It sounds like VS in the "bad" case does not save some files. Can you please compare the project and its output between the "working case" and the "broken case" (ideally both changing to the same version number from the same original number) to observe if there is any difference.
Once we track down which file is different (i.e. it was not saved), maybe we can figure out which component is to blame (and to be routed to).

**Comment by karelz** [comment]
BTW: I updated your steps to add numbers and bad/good case titles for easier references during further discussion.

**Comment by ahmedowsky** [comment]
> Why did you say "usually"? Is it intermittent? (as in repeating builds sometime fail) Or is it just random if the problem will be hit or not and once it is, then it is persistent?

Random, if it's a fail, it always fails, doesn't matter how many times i repeat rpm build process after that

> How often does it happen?

Quite often, i just prefer copy-paste-ing approach all the time

> Is the error the one from title? "Unknown tag: x.x.x.x' (x are version numbers)" ... so in this case it would be "... 1.1.1.1"?

Yes, rpm build error will be "Unknown tag: 1.1.1.1" in this case

> This is overall very weird (and interesting ;))

Watching your teammates faces right after explaining this situation is also funny

> It sounds like VS in the "bad case" does not save some files

I'm not sure about that. All i do is reading the dll's version information. And spec file actually can read that, even in the 'bad case'.
On Spec file i have those two lines below.
`%define assemblyFileVersion %(strings /bla/bla/app.dll | egrep '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$')`
`Version:        %{assemblyFileVersion}`

**Comment by omajid** [comment]
An error of the type `Unknown tag: Foo` generally means `rpmbuild` thinks the file contains this line:

`Foo:  Bar `

As a test, I did:

    %define assemblyFileVersion %(echo -e '1.\\n2.3\n4')
    Version: %{assemblyFileVersion}

And the rpmbuild error is:

    error: line 6: Unknown tag: 2.3n4

So, I can't help but wonder what `assemblyFileVersion` actually evaluates to. Can you print it out in hex form? I suspect newlines are somehow sneaking in.

**Comment by karelz** [comment]
@ahmedowsky it seems that @omajid is waiting on your response here - or did I miss something?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
