### ISSUE TITLE
Identifying cause of program exit

### ISSUE THREAD

**Issue by shravan2x** [dotnet/core#2338]
This question was previously posted on SO. I'm cross-posting it here since it might call for runtime improvements too.

.NET Core version: 2.1.6
OS: Ubuntu Server 16.04 LTS

I have a console application written in C# targeting .NET Core for Linux. I'm facing a bug where rarely the application would just exit for seemingly no reason. I'm also unsure if this is an issue with the runtime itself or a library that I'm referencing.

I tried adding these extra event handlers:

```cs
AppDomain.CurrentDomain.UnhandledException += UnhandledExceptionTrapper;
AppDomain.CurrentDomain.ProcessExit += CurrentDomainOnProcessExit;
AssemblyLoadContext.Default.Unloading += DefaultOnUnloading;
```

And I see no unhandled exception. The second two functions are also called properly and display log messages so I don't think the kernel is terminating the program.

How could I proceed to debug this issue and identify the cause of the exit?

**Comment by kp2017** [comment]
You could try running the framework code locally and check for exceptions?

**Comment by shravan2x** [comment]
I don't believe that will be helpful since the `UnhandledExceptionTrapper` is already registered. When called, it should log to a file, but it doesn't get called at all.

**Comment by karelz** [comment]
@shravan2x you need to collect dump and examine what has happened. That should be the same as for other runtimes / applications on Linux (inlc. C/C++ apps).
Some exception in .NET cannot be caught (e.g. AV, StackOverflow, etc.)
