### ISSUE TITLE
docker-file

### ISSUE THREAD

**Issue by SoukainaHyn** [dotnet/core#2347]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-file
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
@SoukainaHyn - could you elaborate on what you're seeing?

**Comment by leecow** [comment]
Feel free to re-open with additional details,.
