### ISSUE TITLE
VsDbg SourceLink Null Reference Exception 

### ISSUE THREAD

**Issue by divinebovine** [dotnet/core#2348]
# Issue Title

When trying to use sourcelink with vscode, a null reference exception is thrown by vsdbg

> Internal error in the debugger.
> Exception = System.NullReferenceException
> Message = Object reference not set to an instance of an object.
> Code = 80004003
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at VsDbg.Handlers.SourceLinkHandler.GetOrCreateReference(String originalFilePath, VSSourceLinkInfo sourceLinkInfo)
>    at VsDbg.Handlers.SourceHandler.HandleSourceLinkAsync(JObject sourceToken, VSSourceLinkInfo sourceLinkInfo, Boolean isBreakpointSource)
> Internal error in the debugger.

Sometimes clearing all nuget locals and restarting vscode will prevent this error, but not always.

# General

OS: Windows 10.0.17134 Build 17134
dotnet version: 2.2.104

**Comment by karelz** [comment]
This may be better suited for https://github.com/dotnet/sourcelink repo ... can you please check to see if it was reported there and if not, ask there?
Thanks!
