### ISSUE TITLE
Problem installing for Mac OS 10.10.5

### ISSUE THREAD

**Issue by jostroff** [dotnet/core#2349]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

It just stated that "there was a problem" downloading version dotnet-sdk-2.2.104 for the Mac OS 10.10.5. It didn't say what the problem was, however.

**Comment by karelz** [comment]
Is it persistent problem?
Did you check your network connection?
Are you able to try it on more than 1 machine to see if it is something environmental?

**Comment by karelz** [comment]
No response, not enough info. Closing. Feel free to reopen if there is actionable info.
