### ISSUE TITLE
Create github pages

### ISSUE THREAD

**Issue by 9034725985** [dotnet/core#235]
The deb file refers to https://dotnet.github.io/core as its website 

![screenshot from Ubuntu Xenial](https://cloud.githubusercontent.com/assets/1676445/17146266/c9cf6bc6-532b-11e6-831b-6207b506a139.png)

Please create a gh-pages branch and stuff so folks can start contributing towards the website. 

If not, please redirect the link in the deb file to something like https://dotnet.github.io/ or direct people to the new and improved docs.microsoft website

**Comment by svick** [comment]
As far as I know, the new URL is https://www.microsoft.com/net/core, so I created a PR to fix this: https://github.com/dotnet/core-setup/pull/226.

**Comment by blackdwarf** [comment]
Thanks @svick. Closing this one.
