### ISSUE TITLE
Problem with Assembly.LoadFile and Activator.CreateInstance in .net core 2.2

### ISSUE THREAD

**Issue by tamasVajda** [dotnet/core#2352]
Problem with Assembly.LoadFile and Activator.CreateInstance

.net core version: 2.2 
dll to load: .net framework 2.0

We tried to implement a kind of dependency injection in .net standard what could use out client from .net framework side and our server from .net core 2.0.

The location of class described in json configuration file, like following:

```json
"Namspace1.SomeData": {
      "class": "Namespace2.ClassName",
      "Assembly": "MyAssambly.dll"
    }
```

our Factory class implemented in .net standard what can provide an instance from a required object:

```c#
               Assembly assembly = Assembly.LoadFile("assemplyPath/MyAssambly.dll");

                Type objtype = assembly.GetType("Namespace2.ClassName");
                var objectInstance = Activator.CreateInstance(objtype);
                return objectInstance as IMyClassInterface;
```

Of coarse ClassName class implement IMyClassInterface interface.

The factory class works well, if called from .net framework side, create an instance from the loaded dll and can cast it to interface type.

BUT can not work if it's called this factory method from .net core project: the assembly load success, there is all types according to configuration, but the cast fail, this function return null (or invalid cast if i try other way to cast it)!  It seems to not working a reflection in .net core properly, if the types are defined in .net standard dll? Why lost all instantiated classes his interfaces? 

We tried some comvisibility attributes, without any result.

Have you any idea how could we solve this issue?

**Comment by karelz** [comment]
Can you post a minimal .NET Core repro? Something we can copy-paste into VS, run and see the problem?
cc @steveharter @joshfree

**Comment by tamasVajda** [comment]
For code axample see the following repository:
https://github.com/tamasVajda/ClassLoadTest.git

**Comment by joshfree** [comment]
This issue was moved to dotnet/corefx#35771
