### ISSUE TITLE
Need help how to consume websocket based java service in dotnet core

### ISSUE THREAD

**Issue by prasadmamidi7** [dotnet/core#2353]
# Issue Title

Need to consume web socket based java  web service in dot net core

# General
I am looking for documentation or sample which will explain how to consume a web socket based java web service  in dotnet core **without full .Net Framework dependency**

**Comment by karelz** [comment]
.NET Core and .NET Framework have the same APIs.
It does not matter if the WebSocket server is implemented in Java or .NET, or something else - the client code won't be affected by that.
Doing quick internet search pops a few examples: https://www.bing.com/search?q=.NET+WebSocket+example

BTW: In general, docs repo https://github.com/dotnet/docs is better place for filing documentation issues.

I hope it helps, closing as answered.
