### ISSUE TITLE
Error while installing .net core 2.2

### ISSUE THREAD

**Issue by irreverencieux** [dotnet/core#2357]
# Issue Title

I was following the procedure but ran into an error...

sudo apt-get install aspnetcore-runtime-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 aspnetcore-runtime-2.2 : Depends: dotnet-runtime-2.2 (>= 2.2.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karelz** [comment]
Which distro did you try?
Does it happen on clean VM as well?

@dagood can you please help here?

**Comment by leecow** [comment]
@irreverencieux - could you run `sudo apt-get install dotnet-runtime-deps-2.2`? This should tell us exactly which system dependency is unable to be installed.

**Comment by cjvalenzuela** [comment]
I had that same issue: https://github.com/dotnet/core/issues/2381

`sudo apt-get update && sudo apt-get upgrade` the re-run, that did the trick. From https://askubuntu.com/questions/1065231/dpkg-deb-error-archive-has-premature-member-control-tar-xz-before-contr/1065237#1065237

**Comment by SuperTal3** [comment]
Possibly its the libicu57 package that won't install.  Thats what happens to me.  I have the same error on this thread.
```

Package libicu57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Comment by SuperTal3** [comment]
You could try using snap to install the beta.

**Comment by SuperTal3** [comment]
> @irreverencieux - could you run `sudo apt-get install dotnet-runtime-deps-2.2`? This should tell us exactly which system dependency is unable to be installed.

It's libicu57 that won't install.

**Comment by karelz** [comment]
What's the next step here?
cc @tarekgh @janvorli

**Comment by tarekgh** [comment]
CC @rakeshsinghranchi

**Comment by karelz** [comment]
cc @dagood instead of @rakeshsinghranchi

**Comment by dagood** [comment]
Original poster's issue didn't have enough info to follow up on--closing as stale.

Thanks all for the input! To sum up:
* cjvalenzuela's tip to use `sudo apt-get update && sudo apt-get upgrade` (https://github.com/dotnet/core/issues/2381) may have fixed it, but we don't know. I've asked Lee in that thread if we can add something to the install page to inform people about this issue.
* SuperTal3's libicu issue is tracked at https://github.com/dotnet/core/issues/2416 (which has significantly more detail than this issue, thanks 😄). We don't know if it's the same issue, and if it is, we don't need this duplicate open.
