### ISSUE TITLE
can not register

### ISSUE THREAD

**Issue by Emmagrabergs** [dotnet/core#2361]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant..

**Comment by leecow** [comment]
Moving to the ML repo. @Emmagrabergs - chances are they will need additional details on what you were doing and the errors you see.

**Comment by leecow** [comment]
Issue moved to [dotnet/machinelearning #2823](https://github.com/dotnet/machinelearning/issues/2823) via [**ZenHub**](https://www.zenhub.com/)
