### ISSUE TITLE
Help correct Microsoft Linux package feed after in-place distro upgrade

### ISSUE THREAD

**Issue by dagood** [dotnet/core#2362]
@dagood, @rowanmiller  -  folks who upgrade their distro in-place (eg 16.04 -> 18.04) after first setting up .NET Core will hit the problem and not necessarily return to https://dotnet.microsoft.com/download/linux-package-manager/. Likely something that we can add to be of help though.

_Originally posted by @leecow in https://github.com/dotnet/core/issues/2149#issuecomment-461133693_

**Comment by karelz** [comment]
@dagood who should do what and where? (sorry I don't quite get it from the description)

**Comment by dagood** [comment]
I'm not sure if we know the exact action yet--here's the things I see to investigate:

@leecow, maybe you have ideas related to this:

> Likely something that we can add to be of help though.

@mbearup also mentioned that we might [be able to programmatically determine the feed](https://github.com/dotnet/core/issues/2149#issuecomment-460322735), which I think would address the issue if doable. (Look further into this?)

Maybe there's a better place to track this? Not sure where Microsoft repository installer package stuff happens.

**Comment by leecow** [comment]
@dagood - Part of the mitigation I'm thinking of would be a note on the [linux installer pages](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current) calling out the issue and adding a section to [linux-setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) detailing the various ways to fix up prod.list.

Detecting the correct repo and potentially fixing things up automatically on our side feels like it's verging on "too clever".

**Comment by rowanmiller** [comment]
On the [Linux install pages](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current) I guess we should call out the issue on the non-18.04 versions in the hopes that some folks remember it when they hit the issue and come back. 

What operation would someone be doing when they encounter the issue after upgrading? Running a command with `dotnet`?

**Comment by dagood** [comment]
Impact, I think:
* Unable to install a new .NET Core package after a distro upgrade.
* Unable to get patch updates for installed .NET Core packages after a distro upgrade.

How I understand it, this is the easiest way to hit `Unable to locate package dotnet-sdk-2.2` via distro upgrade:

1. On Ubuntu 16.04, install .NET Core 2.1.
2. Upgrade distro in place to Ubuntu 18.04.
3. Try to install .NET Core 2.2. (`sudo apt-get install dotnet-sdk-2.2`)

You wouldn't be able to get patches after (2), I think, because your package manager only knows about the 16.04 feed which doesn't provide 18.04 packages.

I believe the `sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb` workaround on the download page right now fixes this problem. (I wonder if people might be missing that you have to also run `sudo apt-get update` before trying the install command again? At least I think you do.)

**Comment by rowanmiller** [comment]
@dagood I'm far from an expert in this area, so just making sure I understand. Are these the first set of commands that someone should try in order to resolve the `Unable to locate package dotnet-sdk-2.2` issue?

```
sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
```

**Comment by dagood** [comment]
I believe so. What's currently recommended by https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current has some steps that don't look necessary to me:

```
sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb

# "then re-attempt the install" interpreted to mean run every install command again:
sudo add-apt-repository universe
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2 
```

I think some people might be interpreting "re-attempt the install" too far the other way, and _only_ running the last command, `sudo apt-get install dotnet-sdk-2.2`.

Just adding the apt-get update and apt-get install commands to the purge suggestion may help, if I'm right with my guess.

**Comment by rowanmiller** [comment]
Changes are pushed to the site https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current

Updated instructions for 18.04 and added a note to earlier versions.

Let me know if you think anything else needs updating.

**Comment by rowanmiller** [comment]
Closing as I think we've done everything needed now.
