### ISSUE TITLE
No executable found matching command "dotent-newconsole"

### ISSUE THREAD

**Issue by asemalpha** [dotnet/core#2366]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relev
![cmd error](https://user-images.githubusercontent.com/48081535/53693677-20754d00-3da4-11e9-84e2-8089c923300b.png)
ant.

**Comment by KexyBiscuit** [comment]
The command is `dotnet new console -o myApp`, there's a whitespace between `new` and `console`.

**Comment by karelz** [comment]
Thanks @KexyBiscuit for catching that.
Closing as resolved.
