### ISSUE TITLE
Kali GNU/Linux Rolling 2019.1 failed to install dotnet core sdk 2.2

### ISSUE THREAD

**Issue by s2p16** [dotnet/core#2369]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux kali 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After following instructions (https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current) on installing dotnet core sdk 2.2 I got an error on trying to installing the dotnet-runtime-deps-2.2 -> the following package is not installable 'libicu57'.

Not sure why isn't in the kali repo any more, but after installing it manually (https://packages.debian.org/stretch/amd64/libicu57/download) everything worked fine.

I used to point to Debian based repos for dotnet core on Kali before without having this problems.

Just let you know, 
Maybe there are issues with libicu57 and Kali current version?

**Comment by karelz** [comment]
@dagood @omajid @leecow is it a known problem?

**Comment by dagood** [comment]
I think we'd need to specifically support Kali to make this work by default. The version of libicu available on certain distros varies a lot, and at least in the `kalilinux/kali-linux-docker` image, Kali has `libicu60` and `libicu63` available in its default repos.

See [dotnet-runtime-deps-debian_config_debian.9-x64.json](https://github.com/dotnet/core-setup/blob/75f03d69c9c1ef5d5fb6122770a375c4f5ae8eb1/src/pkg/packaging/deb/dotnet-runtime-deps-debian_config_debian.9-x64.json) vs. [dotnet-runtime-deps-debian_config_ubuntu.18.04-x64.json](https://github.com/dotnet/core-setup/blob/75f03d69c9c1ef5d5fb6122770a375c4f5ae8eb1/src/pkg/packaging/deb/dotnet-runtime-deps-debian_config_ubuntu.18.04-x64.json) for another example version difference. (57 vs 60.)

**Comment by karelz** [comment]
Should we move it to core-setup repo?
cc @krwq @tarekgh as FYI

**Comment by dagood** [comment]
Issue moved to [dotnet/core-setup #5320](https://github.com/dotnet/core-setup/issues/5320) via [**ZenHub**](https://www.zenhub.com/)
