### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by robinleeping** [dotnet/core#2371]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Not enough info to make it actionable. Please provide detailed steps, OS info and symptoms. Try to donwload again or try another machine/VM.
