### ISSUE TITLE
Dead repo - dotnet/dotnet.github.io

### ISSUE THREAD

**Issue by NextTurn** [dotnet/core#2374]
No one is maintaining dotnet/dotnet.github.io?

**Comment by karelz** [comment]
Looks like that @richlander @martinwoodward @terrajobst @leecow can you please help there?

**Comment by leecow** [comment]
Looks like it's now an entry point to docs.microsoft.com?

**Comment by NextTurn** [comment]
It's a website itself instead of a redirect link.

**Comment by karelz** [comment]
@richlander @martinwoodward @terrajobst @leecow ping?

**Comment by karelz** [comment]
@richlander @martinwoodward @terrajobst @leecow ping again ... almost 4 weeks no response ...

**Comment by NextTurn** [comment]
;)

**Comment by NextTurn** [comment]
This site is now redirected to dotnet.microsoft.com

https://github.com/dotnet/dotnet.github.io/commit/8f2b06ac65d7da9cd46d230390179cc98cf456b5

**Comment by NextTurn** [comment]
Closing as unneeded.
