### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image

### ISSUE THREAD

**Issue by shamexln** [dotnet/core#2375]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I got error as below:
```
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: open //./pipe/docker_engine:
The system cannot find the file specified.
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=rdpnox1bgk35hqgsvqjcni34i&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1:
    open //./pipe/docker_engine: The system cannot find the file specified.
In the default daemon configuration on Windows, the docker client must be run elevated to connect.
This error may also indicate that the docker daemon is not running.
```

And I check services on windows services. There is no Docker for Windows Service installed.
But I follow the step (Install Docker),  I did install Docker correctly by typing docker --version, which gives me version of docker.

**Comment by karelz** [comment]
@MichaelSimons @leecow @richlander can you please help route the problem?

**Comment by leecow** [comment]
@Eilon @danroth27

**Comment by Eilon** [comment]
@glennc - do you know about this article?

**Comment by glennc** [comment]
@shamexln this look like something wrong with Docker on the machine. Does `docker run hello-world` work on the commandline?

**Comment by shamexln** [comment]
@glennc I tried it There is also error message as below
C:\Users\tester\myMicroservice>docker run hello-world
##############################
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.
######################################

**Comment by shamexln** [comment]
yes.I ran it on windows commandline

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by glennc** [comment]
@shamexln Right, that means there is something wrong with the Docker for Windows installation on your machine, Docker itself is not working regardless of what you are trying to do. Which is a bit outside the scope of what we can help you with in the .NET repo. All I can suggest is the Docker troubleshooting guide (https://docs.docker.com/docker-for-windows/troubleshoot/), Stackoverflow, and other Docker specific help channels. Just removing all of Docker from your machine and starting again might help, making sure you have the latest of everything.

**Comment by shamexln** [comment]
got with thanks.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Glenn Condron <notifications@github.com>
发送时间: Thursday, March 7, 2019 1:52:44 AM
收件人: dotnet/core
抄送: shamexln; Mention
主题: Re: [dotnet/core] Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image (#2375)


@shamexln<https://github.com/shamexln> Right, that means there is something wrong with the Docker for Windows installation on your machine, Docker itself is not working regardless of what you are trying to do. Which is a bit outside the scope of what we can help you with in the .NET repo. All I can suggest is the Docker troubleshooting guide (https://docs.docker.com/docker-for-windows/troubleshoot/), Stackoverflow, and other Docker specific help channels. Just removing all of Docker from your machine and starting again might help, making sure you have the latest of everything.

―
