### ISSUE TITLE
Installer and release notes for SDK 2.2.200

### ISSUE THREAD

**Issue by nil4** [dotnet/core#2378]
Steps to reproduce:

1. Install Visual Studio 2019 RC.
2. Run `dotnet --info`:

    ```
    .NET Core SDK (reflecting any global.json):
     Version:   2.2.200
     Commit:    27f814f6ba

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.17763
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\2.2.200\

    Host (useful for support):
      Version: 2.2.2
      Commit:  a4fd7b2c84
    ```
3. Look for SDK 2.2.**200** at [.NET Core 2.2 downloads](https://dotnet.microsoft.com/download/dotnet-core/2.2), and discover that SDK 2.2.**104** is the latest published version.

Where are the release notes and downloads for SDK 2.2.200?

**Comment by nil4** [comment]
Similarly, VS 2019 RC installs SDK 2.1.**600**, while version 2.1.**504** is the latest documented at [.NET Core 2.1 downloads](https://dotnet.microsoft.com/download/dotnet-core/2.1).

**Comment by leecow** [comment]
Apologies for being slow getting the repo release pages up. We'll do a full release of 2.1.6xx and 2.2.2xx when VS 2019 is GA. In the meantime, you can install using the dotnet-install script.Links for usage can be seen on the release pages:

https://github.com/dotnet/cli/releases/tag/v2.2.200
https://github.com/dotnet/cli/releases/tag/v2.1.600
