### ISSUE TITLE
Cannot install .NET Core 2.2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by cjvalenzuela** [dotnet/core#2381]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu14-04/sdk-current
Operating System: Linux Ubuntu 14.04

I'm getting an exception (**dpkg-deb: error: archive '/var/cache/apt/archives/aspnetcore-runtime-2.2_2.2.2-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up**) when running "**apt-get install dotnet-sdk-2.2**"

c.valenzuela@MX-IT00659:~/GITHUB/wb-avails$ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-101 linux-headers-4.4.0-101-generic
  linux-image-4.4.0-101-generic linux-image-extra-4.4.0-101-generic
  linux-lts-xenial-tools-4.4.0-101 linux-signed-image-4.4.0-101-generic
  linux-tools-4.4.0-101-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  aspnetcore-runtime-2.2 dotnet-hostfxr-2.2 dotnet-runtime-2.2
  dotnet-runtime-deps-2.2
The following NEW packages will be installed:
  aspnetcore-runtime-2.2 dotnet-hostfxr-2.2 dotnet-runtime-2.2
  dotnet-runtime-deps-2.2 dotnet-sdk-2.2
0 upgraded, 5 newly installed, 0 to remove and 349 not upgraded.
Need to get 132 MB of archives.
After this operation, 385 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty/main dotnet-runtime-deps-2.2 amd64 2.2.2-1 [2 600 B]
Get:2 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty/main dotnet-hostfxr-2.2 amd64 2.2.2-1 [144 kB]
Get:3 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty/main dotnet-runtime-2.2 amd64 2.2.2-1 [20.7 MB]
Get:4 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty/main aspnetcore-runtime-2.2 amd64 2.2.2-1 [22.8 MB]
Get:5 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty/main dotnet-sdk-2.2 amd64 2.2.104-1 [88.5 MB]
Fetched 132 MB in 1min 45s (1 257 kB/s)                                        
Selecting previously unselected package dotnet-runtime-deps-2.2.
(Reading database ... 238644 files and directories currently installed.)
Preparing to unpack .../dotnet-runtime-deps-2.2_2.2.2-1_amd64.deb ...
Unpacking dotnet-runtime-deps-2.2 (2.2.2-1) ...
Selecting previously unselected package dotnet-hostfxr-2.2.
Preparing to unpack .../dotnet-hostfxr-2.2_2.2.2-1_amd64.deb ...
Unpacking dotnet-hostfxr-2.2 (2.2.2-1) ...
Selecting previously unselected package dotnet-runtime-2.2.
Preparing to unpack .../dotnet-runtime-2.2_2.2.2-1_amd64.deb ...
Unpacking dotnet-runtime-2.2 (2.2.2-1) ...
dpkg-deb: error: archive '/var/cache/apt/archives/aspnetcore-runtime-2.2_2.2.2-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/aspnetcore-runtime-2.2_2.2.2-1_amd64.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Selecting previously unselected package dotnet-sdk-2.2.
Preparing to unpack .../dotnet-sdk-2.2_2.2.104-1_amd64.deb ...
Unpacking dotnet-sdk-2.2 (2.2.104-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/aspnetcore-runtime-2.2_2.2.2-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by omajid** [comment]
I think this is a bug in Ubuntu 14.04. Have you tried upgrading `dpkg` itself?

- https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
- https://askubuntu.com/questions/1065231/dpkg-deb-error-archive-has-premature-member-control-tar-xz-before-contr/1065237#1065237 suggests upgrading 
- https://github.com/travis-ci/travis-ci/issues/9361#issuecomment-408431262

**Comment by cjvalenzuela** [comment]
Thanks @omajid! Indeed, `dpkg` needed to be upgraded

`sudo apt-get update && sudo apt-get upgrade`  did the trick.

**Comment by dagood** [comment]
@leecow Do you think it would be reasonable to add a tip for this situation on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu14-04/runtime-2.2.3? (Is there a bar for putting known external issues like this on that page?)

**Comment by leecow** [comment]
The bar is generally to address issues with multiple reports so I think we can just keep an eye on this one.
