### ISSUE TITLE
Could not load file or assembly 'Leadtools.Kernel.Codecs.DLL' or one of its dependencies. The specified module could not be found. 

### ISSUE THREAD

**Issue by xinyuefu** [dotnet/core#2382]
hi everyone,
  today I met a trouble,when I run the source,page hints leadtools porblem.
The program has 50 warnings,no error,and there is leadtools.kernel.codecs.dll in bin folder.
here are the warnings:
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
警告	BC42304	XML ドキュメント解析エラー: XML 終了要素の前には、一致する開始要素が必要です。 XML コメントは無視されます。	bizdock	C:\Bizdockfile\bizdock\Common\clsLog\cDefLog.vb	991	アクティブ
警告	BC42304	XML ドキュメント解析エラー: XML 終了要素の前には、一致する開始要素が必要です。 XML コメントは無視されます。	bizdock	C:\Bizdockfile\bizdock\Common\clsLog\cDefLog.vb	995	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_ap_tanto.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_Contact_matter.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_docup_fileUp.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_docup_list.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_docup_otherdocUp.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_docup_tradeUp.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_docup_tscUp.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_pop_comment.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_pop_set.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_pop_set_file.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_pop_syukan_file.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_check_view_1.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_check_view_2.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_detail.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_furiwake.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_set_update.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_update.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_view_1.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_view_2.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_view_3.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_view_4.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\logout.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_check_view_1.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_check_view_2.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_check_view_3.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_check_view_4.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_Contact_matter.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_Contact_matter_amend.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_detail_tab_1.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_detail_tab_2.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_detail_tab_3.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_detail_tab_4.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_docup_list.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_genpon_check.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_input_data.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_pop_Contact_matter.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_syodan_detail.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_syodan_his.aspx.designer.vb	32	アクティブ
警告	BC40004	WithEvents variable 'header' は、property 'header' とベース class 'Page' で競合しています。'Shadows' として宣言されなければなりません。	bizdock	C:\Bizdockfile\bizdock\sc_syodan_view_1.aspx.designer.vb	32	アクティブ
警告		同じ依存アセンブリの異なるバージョン間で競合が見つかりました。Visual Studio では、この警告をダブルクリックする (または選択して Enter キーを押す) ことで、この競合を修正できます。または、アプリケーション構成ファイル内の "runtime" ノードに、次のバインド リダイレクトを追加します: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Leadtools.Codecs" culture="neutral" publicKeyToken="9cf889f53ea9b907" /><bindingRedirect oldVersion="0.0.0.0-20.0.4.0" newVersion="20.0.4.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Leadtools" culture="neutral" publicKeyToken="9cf889f53ea9b907" /><bindingRedirect oldVersion="0.0.0.0-20.0.4.0" newVersion="20.0.4.0" /></dependentAssembly></assemblyBinding>	bizdock			
警告		規則セット ファイル "MinimumRecommendedRules.ruleset" を検出できませんでした。	bizdock			
警告	BC42104	変数 'dsChk' は、値が割り当てられる前に使用されています。Null 参照の例外が実行時に発生する可能性があります。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_check_view_1.aspx.vb	267	アクティブ
警告	BC42105	関数 'GetCost' は値を返さないコード パスがあります。結果が使用されるときに、null 参照の例外が実行時に発生する可能性があります。	bizdock	C:\Bizdockfile\bizdock\bu_syodan_view_4.aspx.vb	662	アクティブ
警告	BC42104	変数 'ds' は、値が割り当てられる前に使用されています。Null 参照の例外が実行時に発生する可能性があります。	bizdock	C:\Bizdockfile\bizdock\Class\clsExportCsv.vb	44	アクティブ
警告	BC42104	変数 'dsChk' は、値が割り当てられる前に使用されています。Null 参照の例外が実行時に発生する可能性があります。	bizdock	C:\Bizdockfile\bizdock\sc_check_view_2.aspx.vb	383	アクティブ
警告	BC42104	変数 'dsChk' は、値が割り当てられる前に使用されています。Null 参照の例外が実行時に発生する可能性があります。	bizdock	C:\Bizdockfile\bizdock\sc_syodan_view_1.aspx.vb	378	アクティブ
警告	BC42104	変数 'row' は、値が割り当てられる前に使用されています。Null 参照の例外が実行時に発生する可能性があります。	bizdock	C:\Bizdockfile\bizdock\SysCommon\sysCsv\clsSysCsv.vb	81	アクティブ
警告	BC42353	関数 'ExValueRange' には値を返さないコード パスがあります。'Return' ステートメントが不足していないかどうかを確認してください。	bizdock	C:\Bizdockfile\bizdock\Validator\clsValidator.vb	464	アクティブ
メッセージ		Could not find schema information for the element 'applicationSettings'.	bizdock	C:\Bizdockfile\bizdock\Web.config	31	
メッセージ		Could not find schema information for the element 'bizdock.My.MySettings'.	bizdock	C:\Bizdockfile\bizdock\Web.config	32	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	33	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	33	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	33	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	34	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	36	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	36	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	36	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	37	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	39	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	39	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	39	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	40	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	42	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	42	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	42	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	43	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	45	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	45	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	45	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	46	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	48	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	48	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	48	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	49	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	51	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	51	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	51	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	52	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	54	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	54	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	54	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	55	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	57	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	57	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	57	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	58	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	60	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	60	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	60	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	61	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	63	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	63	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	63	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	64	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	66	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	66	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	66	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	67	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	69	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	69	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	69	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	70	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	72	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	72	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	72	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	73	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	75	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	75	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	75	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	76	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	78	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	78	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	78	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	79	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	81	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	81	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	81	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	82	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	84	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	84	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	84	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	85	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	87	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	87	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	87	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	88	
メッセージ		Could not find schema information for the element 'setting'.	bizdock	C:\Bizdockfile\bizdock\Web.config	90	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	90	
メッセージ		Could not find schema information for the attribute 'serializeAs'.	bizdock	C:\Bizdockfile\bizdock\Web.config	90	
メッセージ		Could not find schema information for the element 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	91	
メッセージ		Could not find schema information for the element 'log4net'.	bizdock	C:\Bizdockfile\bizdock\Web.config	96	
メッセージ		Could not find schema information for the element 'appender'.	bizdock	C:\Bizdockfile\bizdock\Web.config	97	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	97	
メッセージ		Could not find schema information for the attribute 'type'.	bizdock	C:\Bizdockfile\bizdock\Web.config	97	
メッセージ		Could not find schema information for the element 'param'.	bizdock	C:\Bizdockfile\bizdock\Web.config	98	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	98	
メッセージ		Could not find schema information for the attribute 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	98	
メッセージ		Could not find schema information for the element 'param'.	bizdock	C:\Bizdockfile\bizdock\Web.config	99	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	99	
メッセージ		Could not find schema information for the attribute 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	99	
メッセージ		Could not find schema information for the element 'param'.	bizdock	C:\Bizdockfile\bizdock\Web.config	100	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	100	
メッセージ		Could not find schema information for the attribute 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	100	
メッセージ		Could not find schema information for the element 'param'.	bizdock	C:\Bizdockfile\bizdock\Web.config	101	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	101	
メッセージ		Could not find schema information for the attribute 'value'.	bizdock	C:\Bizdockfile\bizdock\Web.config	101	
メッセージ		Could not find schema information for the element 'param'.	bizdock	C:\Bizdockfile\bizdock\Web.config	102	
メッセージ		Could not find schema information for the attribute 'name'.	bizdock	C:\Bizdockfile\bizdock\Web.config	102	
メッセージ		エラーまたは警告の数が最大数を超えました。	bizdock	C:\Bizdockfile\bizdock\Web.config	136

**Comment by xinyuefu** [comment]
the page hints:

FileNotFoundException: Could not load file or assembly 'Leadtools.Kernel.Codecs.DLL' or one of its dependencies. The specified module could not be found.]
--

**Comment by karelz** [comment]
Do you have a minimal repro which reproduces on multiple machines/VMs? Thanks!

**Comment by karelz** [comment]
Closing as not actionable.
If you have additional details, feel free to reopen.
