### ISSUE TITLE
Referencing a legacy library which uses System.Web

### ISSUE THREAD

**Issue by deastr** [dotnet/core#2384]
I have .NET Core 1.1 app which targets net452 that I'm trying to upgrade to .NET Core 2.1 but I'm having a problem with a library which uses System.Web. Here's the structure:

```
CoreApp (coreapp2.1 - target frameworks can be changed) 
  -> LibraryA (standard2.0 - target frameworks can be changed) 
    -> LegacyLibraryA (net452 - fixed target framework) 
      -> System.Web.dll
```

Here's my problem:

```
Could not load type 'System.Web.Configuration.VirtualDirectoryMapping' from 
assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'
```

`System.Web.Configuration.VirtualDirectoryMapping` is used by a code in `LegacyLibraryA`.

Since I can't seem to be able to add System.Web.dll directly as a reference to CoreApp, any ideas how can I solve this? I have tried various net452, net461, netstandard2.0 as single and multiple targets but unable to overcome the problem.

**Comment by karelz** [comment]
What do you mean .NET Core 1.1 app which targets net452?
.NET Core 1.1 targets .NET Core. net452 can be targeted only by .NET Framework 4.5.2+ app.

That said, System.Wed is not available on .NET Core. You need to remove that dependency, or stay on .NET Framework.
