### ISSUE TITLE
An error occurred while writing the output file:

### ISSUE THREAD

**Issue by gethang** [dotnet/core#2385]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant

CSC : error CS8104: An error occurred while writing the output file: System.IO.IOException: Incorrect function [C:\Users\ehunter\myapp\myapp.csproj]
CSC : error CS0016: Could not write to output file 'C:\Users\ehunter\myapp\obj\Debug\netcoreapp2.2\myapp.dll' -- 'Incorrect function' [C:\Users\ehunter\myapp\myapp.csproj]

The build failed. Please fix the build errors and run again..

**Comment by karelz** [comment]
This is weird. Are you able to reproduce it repeatedly? Always?
Can you reproduce it with another project?
Can you try it on another machine/VM?

**Comment by karelz** [comment]
Not actionable, no response - closing. If you have more details later, feel free to reopen

**Comment by thabomatsie** [comment]
CS0016	Could not write to output file 'C:\[PATH]\obj\Debug\netcoreapp2.2\Document.dll' -- 'Incorrect function.	Document

Have posted here too: https://developercommunity.visualstudio.com/content/problem/1046621/cs8104-an-error-occurred-while-writing-the-output.html
