### ISSUE TITLE
Cannot install .Net core on Kali Linux 2018.2 because of G-Lib critical error

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [dotnet/core#2392]
Good day for everyone.
I Was following the instructions on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current to do manual installation on a machine running **Kali Linux 2018.2** (I was following instructions for Ubuntu 18.04) 

On that link , there was a set of commands to run in terminal:

```
sudo apt-get install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
```
However , after running `sudo apt-get update` i get the following error message:

> Hit:1 http://packages.microsoft.com/repos/vscode stable InRelease              
> Get:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3,225 B]
> Hit:3 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease    
> Fetched 3,225 B in 2s (2,110 B/s)                  
> 
> (appstreamcli:5398): GLib-CRITICAL **: 00:20:51.326: g_atomic_ref_count_dec: assertion 'g_atomic_int_get (arc) > 0' failed
> Reading package lists... Done

And the installation fails , what's the reason for this ?

**Comment by leecow** [comment]
Kali is not an officially supported distro and this is likely a subtle system dependency difference. 

Couple of things you can try that may work. 

1) install using the tar.gz instead of apt-get, 
2) install using dotnet-install.sh, 
3) install using our Snap. 

Option 3 would be my first recommendation to try. Each of these methods are detailed in our [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.

**Comment by Eyad-Mohammed-Osama** [comment]
@leecow Thanks for your reply
I've downloaded the .NET SDK , decompressed the `.tar.gz` archive , `export`ed dotnet executable into `PATH` , this seems to be working fine for me.

Now all i have to do is to find a way to make the change on `PATH` variable permanent .

**Comment by leecow** [comment]
I should have included that option and is basically the manual version of using dotnet-isntall.sh.

Regarding the path, you can either add an EXPORT to your .bashrc to append PATH or you can create a symlink in /usr/bin. Either route should work fine.
