### ISSUE TITLE
Failure to download product key

### ISSUE THREAD

**Issue by dangerousHobo** [dotnet/core#2395]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 16.04

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Following the steps in the link above for Ubuntu 16.04, I'm unable to download/register the product key.
```
> wget -v https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb 
--2019-03-07 10:31:56--  https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 40.76.35.62
Connecting to packages.microsoft.com (packages.microsoft.com)|40.76.35.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2452 (2.4K) [application/octet-stream]
packages-microsoft-prod.deb: No such file or directory

Cannot write to ‘packages-microsoft-prod.deb’ (Success).
```

**Comment by leecow** [comment]
Confirmed that `https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb` exists and downloads as expected. Give it another go? Alternatively, just click on the following to download: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
