### ISSUE TITLE
Unable to install SDK 2.2 on Debian testing

### ISSUE THREAD

**Issue by tigersoldier** [dotnet/core#2396]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.2.104
Operating System: Linux Debian 9

This is caused by `dotnet-runtime-deps-2.2` depending on `libssl1.0.2` and `libicu57`.  Only `libssl1.1` and `libicu63` are available.

**Comment by leecow** [comment]
Confirmed that libssl1.0.2 and libicu57 are available in default Debian 9 archives and confirmed by searching https://packages.debian.org/stretch/. Do an `apt search libicu57` to see if your archive config can find the needed versions. If not, you'll need to figure out what archive to register. As an example, here's what I have on the container I just tested:

```
root@4237e6dedf6d:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@4237e6dedf6d:~# cat /etc/apt/sources.list
deb http://deb.debian.org/debian stretch main
deb http://deb.debian.org/debian stretch-updates main
deb http://security.debian.org/debian-security stretch/updates main
```

**Comment by Palpatineli** [comment]
I'm having the same issue. I think what tigersoldier was saying was that debian testing (not stretch) has libraries with versions too high for the installation. The solution, beside compiling the packages ourselves, is to see if the dependencies requirement could be relaxed to allow these new libs, or provide a .run file to install own dependencies.

**Comment by Angr1st** [comment]
Maybe try the tarball like suggested here-> https://github.com/dotnet/core/issues/2707#issuecomment-496696123
