### ISSUE TITLE
AspNetCoreModuleV2 IIS In Process hosting adding server header

### ISSUE THREAD

**Issue by Red6Porkins** [dotnet/core#2399]
# Issue Title
AspNetCoreModuleV2 In Process hosting adding server header

# General
After upgrading a few projects to net core 2.2, I've noticed that the server header is being added in on all responses. We are hosting on IIS 10 using the new InProcess method. The exact header being added is "server: Microsoft-IIS/10.0" . I have verified that this is not being added by the HttpResponse headers option within IIS's gui. I tried switching the hosting process back to the out of process style, and the server header disappeared like I would expect. It appears it's only being added when using the InProcess hosting method.

**Comment by Eilon** [comment]
@shirhatti / @Tratcher - is this an ANCM thing or an IIS thing?

**Comment by shirhatti** [comment]
This is an IIS thing.

You can remove by adding this to your `web.config`. This works on versions of Windows Server, version 1709 and newer.

```xml
<configuration>
  <system.webServer>
     <security>
       <requestFiltering removeServerHeader="true" />
     </security>
  </system.webServer>
</configuration>
```
