### ISSUE TITLE
New tooling bits, next preview release?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/core#240]
I have a critical question about the timeline of the next tooling bits, as the guys at dotnet-docker are stuck on a CLI version that's completely broken for linux 4.6+ kernels.

Related:
https://github.com/dotnet/core/issues/171
https://github.com/dotnet/dotnet-docker/issues/61
https://github.com/dotnet/cli/issues/3681
and many more (ubuntu 16.04 issues etcetera)

As more and more distro's move to 4.6+ kernels and a lot of CI's  using these in turn have as well (including the CI we use) there are more and more people grinding to a halt with this CLI version inside docker containers.
On top of that there is no obvious fix but to compile the CLI from source and then include this in your own docker build. Which is really quite an embarrassing answer for a company like Microsoft to point to as the only fix for now. 

It seems this would require just a tiny bit of coordinated efforts to get resolved and I would love to know an estimate timeframe of the next tooling release with this fix.

EDIT: This is of course not exclusive to docker containers but to all dotnet cli instances running on 4.6+ kernels, I have the luck that my dev env is OSX and not an up-to-date linux distro.

**Comment by blackdwarf** [comment]
@richlander @leecow can you comment on this please?

**Comment by joshfree** [comment]
@NinoFloris we're tracking a fix for this here: https://github.com/dotnet/coreclr/issues/6604
