### ISSUE TITLE
Problem during dotnet install under Ubuntu 18

### ISSUE THREAD

**Issue by mariappandct** [dotnet/core#2404]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Closing due to insufficient information. Need information on what you're doing and what you see. Feel free to re-open after the issue has been updated.
