### ISSUE TITLE
Can't install on Debian Buster

### ISSUE THREAD

**Issue by kashfshah** [dotnet/core#2406]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian sid (Debian unstable - Debian 10, Buster)
```
$ uname -a
Linux hostname 4.19.0-3-amd64 #1 SMP Debian 4.19.20-1 (2019-02-11) x86_64 GNU/Linux
```
**Description:**

Apparently the installer depends on an old version of libicu.  Currently depends on libicu57 and doesn't accept libicu63 as satisfying the dependency.  Workaround may be similar to https://github.com/dotnet/core/issues/1400#issuecomment-378418318 or https://github.com/dotnet/core/issues/1587#issuecomment-391700837.  Also, see https://github.com/dotnet/core/issues/2369 and https://github.com/dotnet/core-setup/issues/5320.

**Install failure:**
```
$ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.2) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Dependency issue:**
```
$ sudo apt-get install dotnet-runtime-deps-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

No packages being held:
`$ sudo apt-mark showhold
`

**Comment by leecow** [comment]
Debian 10 is not yet supported by .NET Core. When we do add support, it will likely be to 2.1 (the LTS channel) and 3.0.

**Comment by MrM40** [comment]
Manual installation of runtime 2.2.3 on Debian Buster:

1. Download binaries:
`wget -O /tmp/dotnet_runtime_2.2.3.tar.gz https://download.visualstudio.microsoft.com/download/pr/28271651-a8f6-41d6-9144-2d53f6c4aac4/bb29124818f370cd08c5c8cc8f8816bf/dotnet-runtime-2.2.3-linux-x64.tar.gz`

2. Make dir
`mkdir /usr/share/dotnet/`
3. Unpak
`tar zxf /tmp/dotnet_runtime_2.2.3.tar.gz -C /usr/share/dotnet/`
4. Create symbolic link to dotnet
`ln --symbolic /usr/share/dotnet/dotnet /usr/bin/dotnet`
5. Confirm installation
`dotnet --info`
