### ISSUE TITLE
The installer don't clean up old versions

### ISSUE THREAD

**Issue by charlesmilette** [dotnet/core#241]
![2016-08-03](https://cloud.githubusercontent.com/assets/6440374/17371480/fe7dcb9a-596d-11e6-8d2a-321459a10aa5.png)

**Comment by blackdwarf** [comment]
This is by design as the installer is side-by-side by default.

**Comment by charlesmilette** [comment]
Then maybe during the setup find old versions and ask the user if he wants to remove them
