### ISSUE TITLE
Modify step does not work on Core 3.0.100-preview3-010431

### ISSUE THREAD

**Issue by nkev** [dotnet/core#2412]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/modify
Operating System: macos

When I replace the contents of the /Pages/Index.html and save it. Then when I refresh the page in the browser, it does not update. I have to restart the webapp to see the change. This is on Mac VS-Code with `Core 3.0.100-preview3-010431 `

**Comment by leecow** [comment]
Confirmed - @dougbu @Eilon

**Comment by Eilon** [comment]
@danroth27 - can you take a look?

**Comment by danroth27** [comment]
This is expected with .NET Core 3.0. Starting with .NET Core 3.0 we no longer enable runtime compilation of pages or views by default: https://github.com/aspnet/Announcements/issues/343. You can add back runtime compilation support by adding the appropriate package. Once we ship .NET Core 3.0 we will need to update this content.

@rowanmiller

**Comment by nkev** [comment]
I expect a lot of people will be unhappy about that default development experience.

**Comment by nkev** [comment]
Anyway, tutorial still needs to be edited:

![image](https://user-images.githubusercontent.com/5410916/55199760-39d8b000-520f-11e9-952f-2410463cee69.png)

It needs to say, "Save the file, stop the app, recompile the app and run it again to see the change" :)

**Comment by danroth27** [comment]
@nkev Right, the tutorial steps are currently written for 2.2, which the latest shipped version. Once we ship 3.0 later this year will look at updating this content.
