### ISSUE TITLE
Getting NU1101 error When installing dotnetsay global tool

### ISSUE THREAD

**Issue by loviji** [dotnet/core#2414]
# ERROR NU1101 when installing global tools

 Using command 

`dotnet tool install --global dotnetsay --version 2.1.4 --configfile NuGet.Config`

get an error in NU1101.

> error NU1101: Не удалось найти пакет dotnetsay. Пакеты с таким идентификатором отсутствуют в следующих источниках пакетов: C:\Program Files\dotnet\sdk\NuGetFallbackFolder
> Не удалось восстановить пакет инструмента.
> Не удалось установить средство "dotnetsay". Возможные причины сбоя:
> 
> * Вы пытаетесь установить предварительный выпуск и не указали версию с помощью параметра --version.
> * Пакет с таким именем найден, но он не является средством .NET Core.
> * Недоступен требуемый веб-канал NuGet, возможно, из-за проблемы с подключением к Интернету.
> * Неправильно введено имя средства.

**My NugetConfig File Configuration**
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
     <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
</configuration>
```
# dotnetcore envirement
PS C:\> dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by karelz** [comment]
@KathleenDollard is it something you can help with please?

**Comment by KathleenDollard** [comment]
@loviji Do you need to specify the nuget.config? You are specifying the default, which you normally need to do when there is a nuget.config for your project that blocks the standard feed. If you can try this from a directory that does not contain a nuget.config, that may unblock you while we look at this. 

@wli3 Any ideas? Is there an issue with NuGet.config (the file looks fine, it matches a sample in https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)

**Comment by wli3** [comment]
activepackagesource is [deprecated](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#activepackagesource)

You need to change it to the following

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
     <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
