### ISSUE TITLE
The following packages have unmet dependencies error

### ISSUE THREAD

**Issue by SuperTal3** [dotnet/core#2416]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 (Parrot Security OS v 4.5.1)
Every time I try to install dotnet-sdk-2.2 using sudo apt-get install dotnet-sdk-2.2, or sudo apt install dotnet-sdk-2.2, I get this error.
`The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.2) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`
The issue seems to be this package:
`Package libicu57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
`

**Comment by Elrashid** [comment]
https://github.com/dotnet/core-setup/issues/4247

sudo apt-get autoremove dotnet-host

sudo rm -rf /usr/share/dotnet/

wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu60_60.2-6ubuntu1_amd64.deb

sudo dpkg -i libicu60_60.2-6ubuntu1_amd64.deb

sudo apt-get install dotnet-sdk-2.2

**Comment by SuperTal3** [comment]
It still fails...  It shows this error now.
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.2) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by SuperTal3** [comment]
I've found the best way is to install via snap.  It doesn't throw errors and ends up working fine that way.

**Comment by karelz** [comment]
@dagood @tarekgh can you help route it please? Is it dupe of the other libicu57 problems I have seen here?

**Comment by tarekgh** [comment]
CC @rakeshsinghranchi may help here I think. should such issues be moved to core-setup repo?

**Comment by karelz** [comment]
cc @dagood instead of @rakeshsinghranchi (the ownership was transfered in January)

**Comment by dagood** [comment]
> Operating System: Linux Debian 9 (Parrot Security OS v 4.5.1)

Unfortunately Parrot Security OS is not an [officially supported 2.2 distro](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md).

> [Quoted from @leecow, [#2392](https://github.com/dotnet/core/issues/2392#issuecomment-470321027))]
> ...
> Couple of things you can try that may work.
> 
> 1. install using the tar.gz instead of apt-get,
> 2. install using dotnet-install.sh,
> 3. install using our Snap.
> 
> Option 3 would be my first recommendation to try. Each of these methods are detailed in our [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.

Some background: the libicu dependency is particularly tricky, because different distros have different versions of ICU available in their repositories. We produce `runtime-deps` packages for supported distros that includes the libicu dependency needed on that distro. Using a distro derived from Debian is a common way to hit this issue and I don't know any general guidance we can give.

I'm closing this issue: known to happen on distros that aren't officially supported.
