### ISSUE TITLE
core 2.2 SDK installation fails on ubuntu 18.04.2

### ISSUE THREAD

**Issue by dreamerNcoder** [dotnet/core#2418]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04.2

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
```
 dotnet-runtime-deps-2.2 : Depends: libicu60 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

When tried sudo apt install  dotnet-sdk-2.2

```
The following packages have unmet dependencies:
 aspnetcore-runtime-2.2 : Depends: dotnet-runtime-2.2 (>= 2.2.2) but it is not going to be installed

```

I followed all the steps mentioned in the sample but no of the things works :(

**Comment by Elrashid** [comment]
https://github.com/dotnet/core-setup/issues/4247

sudo apt-get autoremove dotnet-host

sudo rm -rf /usr/share/dotnet/

wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu60_60.2-6ubuntu1_amd64.deb

sudo dpkg -i libicu60_60.2-6ubuntu1_amd64.deb

sudo apt-get install dotnet-sdk-2.2

**Comment by dreamerNcoder** [comment]
Perfect 👍 Can we update the same in [documentation ]( https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current) it will help some facing this issue.
