### ISSUE TITLE
Update roadmap.md

### ISSUE THREAD

**Issue by svick** [dotnet/core#242]
[roadmap.md](https://github.com/dotnet/core/blob/master/roadmap.md) currently says this:

> ## Ship Dates
> 
> At Microsoft, .NET has always been an important component of other teams' products and has largely shipped on their schedules. It means that we have to take their dates seriously and integrate them into the .NET Core schedule.
> 
> | Milestone | Release Date |
> | --- | --- |
> | 1.0 | June 2016 |
> | 1.1 | Fall 2016 |
> ## Planned 1.1 features
> - Broader API support, bringing parity with .NET Framework and Mono at the BCL level.
> - Transition to MSBuild and csproj as the default build system and project model for all versions of .NET. 
> 
> Notes:
> - The 1.0 release is accompanied with a preview version of the Visual Studio and command-line tooling. The tooling should reach RTM quality with version 1.1 of the .NET Core runtime in Fall 2016.
> - The [ASP.NET Core roadmap](https://github.com/aspnet/Home/wiki/Roadmap) articulates the ASP.NET projects's roadmap and dates.

But [the _.NET Core Roadmap_ article](https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/) shows a different picture, with minor 1.0.1 update planned for August, MSBuild (with no version number?) planned for "Q4 2016 / Q1 2017" and Broader API support for "Q1 2017 / Q2 2017".

I think this document should be updated to reflect that.

**Comment by leecow** [comment]
@svick Thanks for the feedback. Our relatively new openness with upcoming plans certainly creates opportunities and challenges in keeping information fresh! Generally speaking, roadmap pages should provide a better view into coming activities and be updated as needed. Unless there are rather grave errors, blog posts will tend to be static and it won't be unexpected if forward looking release information diverges a bit over time. 

I'll update [roadmap.md](https://github.com/dotnet/core/blob/master/roadmap.md) with some "1.0,1" information and will add details to the 1.1 section as appropriate. We're expecting to have a blog post ready for publication around the first of September updating everyone on MSBuild progress. 

/cc @richlander @blackdwarf

**Comment by Petermarcu** [comment]
I think this was addressed with my commit https://github.com/dotnet/core/commit/427b2f13a3b218d5fa309f6a12fa7b8b307ce20d

I'm going to close this assuming it was.
