### ISSUE TITLE
dotnet run error in powershell, after .NET SDK installation.

### ISSUE THREAD

**Issue by PhantomXL** [dotnet/core#2420]
OS Version : Windows Home 10.0.17763
Issue : Installed .NET SDK 2.2 and followed the tutorial contained in https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create . I encountered the following error, after executing the `dotnet run` command. **Couldn't find a project to run. Ensure a project exists in C:\WINDOWS\system32, or pass the path to the project using --project.**

**Comment by leecow** [comment]
Did you `cd myApp` before `dotnet run`?

**Comment by PhantomXL** [comment]
Yes. I followed the instructions carefully.

?p??t?ste t? Outlook ??a Android<https://aka.ms/ghei36>

________________________________

**Comment by PhantomXL** [comment]
Yes. I followed the instructions carefully.


Από: Lee Coward
Eστάλη: Δευτέρα, 18 Μαρτίου - 19:46
Θέμα: Re: [dotnet/core] dotnet run error in powershell, after .NET SDK installation. (#2420)
Προς: dotnet/core
Κοιν.: PhantomX, Author


Did you cd myApp before dotnet run?

**Comment by karelz** [comment]
It looks like something weird happened on your machine.
Can you please try to reinstall .NET Core?
Or try another machine or VM?

**Comment by PhantomXL** [comment]
I tried reinstalling it numerous times even before I sent my initial error message. Ok, I will try through a VM and another device and keep you posted.

?p??t?ste t? Outlook ??a Android<https://aka.ms/ghei36>

________________________________

**Comment by PhantomXL** [comment]
I tried reinstalling numerous times before I sent my initial error report, although I haven't tried a VM or through another device. I will keep you posted, once I try those.
________________________________

**Comment by karelz** [comment]
@PhantomXL did you get a chance to try it?

**Comment by PhantomXL** [comment]
I tried on a different machine, but I didn't get a chance to try a VM yet. I encountered the same problem.
________________________________
Από: Karel Zikmund <notifications@github.com>
Στάλθηκε: Σάββατο, 30 Μαρτίου 2019 8:12 μμ
Προς: dotnet/core
Κοιν.: PhantomX; Mention
Θέμα: Re: [dotnet/core] dotnet run error in powershell, after .NET SDK installation. (#2420)


@PhantomXL<https://github.com/PhantomXL> did you get a chance to try it?

**Comment by karelz** [comment]
If you can reproduce on multiple machines, can you please share here EXACT steps you're doing?

**Comment by PhantomXL** [comment]
Once I get the chance, I'll send some screenshots.
________________________________

**Comment by karelz** [comment]
Commands and results will be better - they are also searchable 😉

**Comment by PhantomXL** [comment]
Ok. Fair enough.

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by PhantomXL** [comment]
Ok. Fair enough.

**Comment by karelz** [comment]
Gentle ping

**Comment by karelz** [comment]
No response in 4 weeks, closing. Feel free to reopen when there is actionable info again. Thanks!
