### ISSUE TITLE
Foreach enumeration assigning value to two elements at the same time

### ISSUE THREAD

**Issue by rexyque** [dotnet/core#2421]
# Foreach enumeration assigning value to two elements at the same time

I'm using dotnet core 2.1.6 on Windows 10 and I just spent an hour figuring out this weird bug within a foreach loop. My project uses Entity Framework Core to connect to a database, and I was working on a method to convert a complex word document into the database entries needed to store it properly. Part of this task is creating a reference table that contains the heading ids used during file parsing and the database id that they end up actually having. Then I iterate through all of the parts that need to have their id updated from the id used for parsing to the corresponding database id before saving them.

The code that was causing the problem looks something like this:

```csharp
foreach (var item in items) {
    item.headingId = headingTable.Rows.First(row => row.ParsingId == item.headingId).DbId;
    context.SaveItem(item);
}
```

For some reason, on the penultimate item in the list, the assignment to headingId was happening for both the correct item AND the final item in the list. I discovered this because I kept getting an error that there wasn't a row matching the lambda expression for the final item. I solved this problem by creating a local variable and performing the assignment onto that, and then creating a new object from the enumerated object and performing the assignment onto that object like so:

```csharp
foreach (var item in items) {
    var databaseId = headingTable.Rows.First(row => row.ParsingId == item.headingId).DbId;
    context.SaveItem(new Item(item) {
        headingId = databaseId
    });
}
```

I'm reporting this bug because I thought it was very odd that this is happening and I'm not sure if the team is aware of this or not.

**Comment by karelz** [comment]
@ajcvickers @divega is it something specific to EF?

**Comment by divega** [comment]
@karelz It looks like this. 

@rexyque I am not able to understand the issue. If you can provide a complete code listing (including entity types) that repros the behavior you are seeing, please create a new issue with that information at https://github.com/aspnet/EntityFrameworkCore/issues/new.

**Comment by karelz** [comment]
Thanks @divega! Closing here as it will be filed in EFCore repo.
