### ISSUE TITLE
RaspberryPi 3

### ISSUE THREAD

**Issue by mhectorgato** [dotnet/core#2422]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-2.2.2
Operating System: Linux Debian 9

Am trying to run my 2.2 dll on my pi. When I run it I get 
> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       /
>   - Alternatively, install the framework version '2.2.0'.

---

When I followed instructions in the above link, I get:

> sudo apt-get install dotnet-runtime-2.2
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package dotnet-runtime-2.2
> E: Couldn't find any package by glob 'dotnet-runtime-2.2'
> E: Couldn't find any package by regex 'dotnet-runtime-2.2'

I've also tried to use: aspnetcore-runtime-2.2 with the same result
---
Linux raspberrypi 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

**Comment by leecow** [comment]
We do not provide native installers for ARM devices yet. You will need to follow the guidance for installing from tar.gz found in the [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.
