### ISSUE TITLE
.Net Core 3 preview2 dot work

### ISSUE THREAD

**Issue by sishen2** [dotnet/core#2425]
use  .Net Core 3 preview2  publish
![image](https://user-images.githubusercontent.com/16297734/54180768-62ef0600-44d7-11e9-9655-e9dd9bc7aa24.png)

**Comment by karelz** [comment]
Looks like corrupted installation.
Can you try it on clean machine/VM?

**Comment by karelz** [comment]
Not enough info, not actionable, closing. Feel free to reop when you have additional details.
