### ISSUE TITLE
Support for Synology

### ISSUE THREAD

**Issue by picrap** [dotnet/core#2427]
Hi,

are there plans to support Synology NAS?  
Currently, a Mono packet is available, this make me think that .NET Core could be ported there.
Another positive point is that DSM (Synology OS) is Linux-based, so porting to this platform could probably be done with big problems.

Thanks.

**Comment by leecow** [comment]
@picrap - we currently do not have plans to officially support Synology at this time. If it's a glibc-based distro, you may be able to use .NET Core from our tar.gzs to get up and running though, no promises :-). Is Synology provided support for [Snaps](https://snapcraft.io/), that would be another option as we do provide Snap installers for the SDK and Runtimes.

- [Linux Prereqs](https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md)
- [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md)

**Comment by D0rmouse** [comment]
> Hi,
> 
> are there plans to support Synology NAS?
> Currently, a Mono packet is available, this make me think that .NET Core could be ported there.
> Another positive point is that DSM (Synology OS) is Linux-based, so porting to this platform could probably be done **without** big problems.
> 
> Thanks.
