### ISSUE TITLE
Dotnet tool restore search wrong paths on ubuntu

### ISSUE THREAD

**Issue by ehhnwidex** [dotnet/core#2428]
# Dotnet tool restore search windows pathes on Ubuntu

# General

When trying to restore a local dotnet tool from \.config\dotnet-tools.json on an ubuntu debian 16.04, by running the command:

dotnet.exe tool restore

the dotnet tool will search for a dotnet-tools.json in the following directories, instead of relative pathes from your current position to the root folder.

Cannot find any manifests file. Searched:
C:\WINDOWS\system32\.config\dotnet-tools.json
C:\WINDOWS\system32\dotnet-tools.json
C:\WINDOWS\.config\dotnet-tools.json
C:\WINDOWS\dotnet-tools.json
C:\.config\dotnet-tools.json
C:\dotnet-tools.json
No tools were restored.

**Comment by leecow** [comment]
@livarcocc @KathleenDollard

**Comment by KathleenDollard** [comment]
@wli3

**Comment by wli3** [comment]
Filed https://github.com/dotnet/corefx/issues/36003

And apparently you can run an exe in WSL (!!!)

**Comment by ehhnwidex** [comment]
@leecow Yes i have only tested on a windows subsystem, but other console applications using System.IO.Path to handle directories, does not seem to have the same problem

**Comment by leecow** [comment]
Closing this issue in favor of dotnet/corefx#36003
