### ISSUE TITLE
输入dotnet命令之后就没有任何反应，按CTRL+C也没有反应

### ISSUE THREAD

**Issue by Laoguoguo** [dotnet/core#2429]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04

输入dotnet命令之后就没有任何反应，按CTRL+C也没有反应

**Comment by leecow** [comment]
Not enough information to know what's being encountered.
