### ISSUE TITLE
ARM Support?

### ISSUE THREAD

**Issue by fonix232** [dotnet/core#243]
It's good to see .Net Core mature into the platform it's becoming, but I miss one small feature from the roadmap - ARM support. This one little thing could mean that over 2 billion devices could receive .Net goodness  in the near future. 

I suppose this could fall under the "broader Linux distro support" part, but I think it would be important to get .Net Core up and running on ARM devices too.

**Comment by rusty21** [comment]
+1

**Comment by Petermarcu** [comment]
Totally agree. Our daily builds https://github.com/dotnet/core-setup/blob/master/README.md . It's still early but it is starting to come up. I can't speak to the quality of the builds yet. Happy to have community help on that effort as well.

**Comment by jacobsmith928** [comment]
Howdy @Petermarcu @fonix232  i realize this is closed but you guys need ondemand build servers, we can offer  up (via Packet.net) our 96-core ARMv8 to anyone in the community.
