### ISSUE TITLE
Dot NET EXE

### ISSUE THREAD

**Issue by HamdaouiJ** [dotnet/core#2430]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Error Message
The program cant start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by leecow** [comment]
Need a bit more information to know how to help. What version of Windows? What steps did you perform leading up to the error message?

**Comment by karelz** [comment]
Duplicate of https://github.com/dotnet/core-setup/issues/4388

**Comment by HamdaouiJ** [comment]
Thanks for your email:
Windows 7 HomePremiumIntel i3 CPU M380 @ 2.53 GHz 2.53 GHz64 Bit Operating System

Sincerely yours,Chokri Jack Belgacem Hamdaoui
c.hamdaoui@aol.com


-----Original Message-----
