### ISSUE TITLE
.NET Core March Update - 1.0.15, 1.1.12, 2.1.9 and 2.2.3

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#2432]
Included fixes address security issues detailed in the release notes.

## .NET Core

* **.NET Core 1.0.15 and .NET Core SDK 1.1.13**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.15/1.0.15.md)
  [Download 1.0](https://dotnet.microsoft.com/download/dotnet-core/1.0)

* **.NET Core 1.1.12 and .NET Core SDK 1.1.13**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.12/1.1.12.md)
  [Download 1.1](https://dotnet.microsoft.com/download/dotnet-core/1.1)

* **.NET Core 2.1.9 and .NET Core SDK 2.1.505**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.9/2.1.9.md)
  [Download 2.1](https://dotnet.microsoft.com/download/dotnet-core/2.1)

* **.NET Core 2.2.3 and .NET Core SDK 2.2.105**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.3/2.2.3.md)
  [Download 2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2)

Please report any issues you find with these releases, either responding to this issue, creating a new issue here or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

## .NET Support Policies

Microsoft support policies are defined in the following documents:

* [Microsoft .NET Support Policy](https://www.microsoft.com/net/support/policy)
* [.NET Core OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md)

**Comment by omajid** [comment]
There's a typo in title, I think. Should be March, right?

**Comment by onovotny** [comment]
The announce post lists 2.2.1, not 2.2.3 as the version.

**Comment by ctyar** [comment]
The SDK versions are also wrong.

**Comment by vivmishra** [comment]
Fixed

**Comment by Nothing-Works** [comment]
https://dotnet.microsoft.com/download/dotnet-core/2.2 this download page shows that the latest SDK is Included in Visual Studio 15.9. I just updated my VS, I only got 2.1.505 not 2.2.x. Is this my end problem?

**Comment by leecow** [comment]
@Nothing-Works - answered the question in https://github.com/dotnet/core/issues/2435. 2.2 is not included in 15.9 but if you update, it can be targeted.

**Comment by michael-x** [comment]
The announcement post still says ".NET Core 2.1.9 and .NET Core SDK 2.1.**503**" where the SDK version should be "2.1.**505**".

**Comment by karelz** [comment]
@michael-x which post? Can you provide link? This issue and [the blog post](https://devblogs.microsoft.com/dotnet/net-core-march-2019/) both seem fine.

**Comment by michael-x** [comment]
@karelz the original announcement at https://github.com/dotnet/announcements/issues/103.

**Comment by karelz** [comment]
@michael-x thanks! Fixed ;)

**Comment by karelz** [comment]
Fully replaced by #2727
