### ISSUE TITLE
Dotnet download website info

### ISSUE THREAD

**Issue by Nothing-Works** [dotnet/core#2435]
https://dotnet.microsoft.com/download/dotnet-core/2.2 this download page shows that the latest SDK is Included in Visual Studio 15.9. I just updated my VS, I only got 2.1.505 not 2.2.x. Is this my end problem?

**Comment by leecow** [comment]
Sorry for the confusion on this. 2.2 is not included "in-box" with 15.9. When you install it separately, it will show up in the Target Framework drop down of the Project Options dialog. 

cc @vivmishra

**Comment by Nothing-Works** [comment]
@leecow Ahhhh I see So I need to download the latest SDK separately, and then I can choose from VS when I File>new>new project ? is that right?

**Comment by leecow** [comment]
I believe it will default to targeting 2.2 after you install. The only time you would need to re-target is if you needed to build for something older.
