### ISSUE TITLE
But it's not on the path!

### ISSUE THREAD

**Issue by chaim1221** [dotnet/core#2438]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-2.1.1
Operating System: Linux Debian 9

I followed these instructions to add the runtime, but I end up with the problem that `dotnet` isn't on the PATH.

**Comment by leecow** [comment]
That's correct, .NET Core installs don't alter the path. We create a symlink which points to the dotnet host location. `ls -al /usr/bin/dotnet` should show you if this happened correctly.

Are you looking to build an application, then run it or do you already have an application? If the former, then you need to start with the SDK. `sudo apt-get install dotnet-sdk-2.2` will get you the latest channel release of the SDK.

**Comment by chaim1221** [comment]
It just so happens that I had commented out the line
`    apt-get install -yq aspnetcore-runtime-2.1 && \`
to troubleshoot something, and my problem was due to not having the runtime installed at all.

PEBKAC
