### ISSUE TITLE
Reduce number of compiled files after dotnet publish

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/core#244]
HI. I build a program on .NET Core on ubuntu. When I run:
```
dotnet publish -f netcoreapp1.0 -r ubuntu.14.04-x64
```
 it compiles all library on publishing folder. Do you now the way to reduce the number of dependencies or maybe store them somewhere on the system. Thanks.

**Comment by tehbilly** [comment]
Unless I'm mistaken, this is something on the roadmap for 1.1: https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by SerhiiS-in6k** [comment]
Thanks. Ok. Will be waiting release 1.1 .
