### ISSUE TITLE
"...\15.0\Microsoft.Common.props" was not found when using 3.0.100-preview3

### ISSUE THREAD

**Issue by Dresel** [dotnet/core#2442]
# Issue Title

"...\15.0\Microsoft.Common.props" was not found when using 3.0.100-preview3

# General

Using a custom MSBuild task fails with the message

> The imported project "C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\15.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

On my local machine I could work around this issue by creating a symbolic link from Current -> 15.0 or changing the Import declaration of Sdk.props to Current.

If you need some [logs](https://dresel.visualstudio.com/Automaty/_build/results?buildId=353&_a=summary) (see dotnet build or dotnet test tab) or a [repository (experimental branch)](https://github.com/Dresel/Automaty).

**Comment by leecow** [comment]
@livarcocc

**Comment by livarcocc** [comment]
@Dresel can you tell us more about your setup? Do you happen to have MSBuildToolsVersion as an environment variable set to 15.0 for some reason? Or have it set as a property somewhere in your build?

cc @rainersigwald

**Comment by rainersigwald** [comment]
From the logs, it looks like the failure isn't coming from the custom task but from your tool that's running inside it (that uses the MSBuild API to load a project).

@Dresel Can you reproduce that failure in a smaller test case and file a bug at https://github.com/Microsoft/msbuild/issues/new, please? I think I'm beginning to understand the problem--I suspect a mismatch between the MSBuild assemblies you're loading and the MSBuild assemblies in the SDK. I suspect we'll want to move you over to MSBuildLocator's new support for .NET Core (https://github.com/Microsoft/MSBuildLocator/pull/51#issuecomment-463281861).

**Comment by Dresel** [comment]
Yes I can do that.

**Comment by Dresel** [comment]
You were right, this has nothing todo with the custom MSBuild task.

See the minimal [repro](https://github.com/Dresel/Repro-2442):

- ~~dotnet info is called via `ProcessStartInfo` to get the MSBuild location~~
- ~~MSBUILD_EXE_PATH is set to previous retrieved MSBuild location~~
- Using MSBuildLocator to register MSBuild
- ProjectCollection.LoadProject is called

**Comment by Dresel** [comment]
Updating `Microsoft.Build` and `Microsoft.Build.Utilities.Core` to `16.0.452` from the `https://dotnet.myget.org/F/msbuild/api/v3/index.json` feed seems to solve this problem.

Thanks for your time and help.

**Comment by Dresel** [comment]
Using Microsoft.Build 16.0.452 only works when running on .NET Core 3.0, not with .NET Core 2.2 (for this I still have to use 15.9.20). Is this by design?

**Comment by rainersigwald** [comment]
@Dresel You can support both if you use MSBuildLocator.

**Comment by Dresel** [comment]
Sorry I wasn't able to look earlier into this. Maybe I'm doing something wrong but I wasn't able to use ProjectCollection.LoadProject with .NET Core 2.2 when using Microsoft.Build 16.0.452, even with MSBuildLocator - am I doing something wrong? This is basically what I'm doing

    public class Program
    {
        private static void Main(string[] args)
        {
            RegisterMSBuild();
            LoadProjectCollection();
        }

        private static void LoadProjectCollection()
        {
            ProjectCollection projectCollection = new ProjectCollection();
            Project project = projectCollection.LoadProject("..\\..\\..\\Repro2442.Console.csproj");
        }

        private static void RegisterMSBuild()
        {
            MSBuildLocator.RegisterInstance(MSBuildLocator.QueryVisualStudioInstances(
                new VisualStudioInstanceQueryOptions()
                {
                    DiscoveryTypes = DiscoveryType.DotNetSdk
                }).SingleOrDefault());
        }
    }

See [repro](https://github.com/Dresel/Repro-2442).

**Comment by rainersigwald** [comment]
@Dresel can you please open a new bug on MSBuild with the full repro? Note that I tried your repo and got this in the initial build before running, so I think some changes may have gotten lost:

```
error MSB4062: The "MSBuildTask" task could not be loaded from the assembly S:\repro\dotnet\core\issues\2442\Repro2442.Console\..\Repro2442.MSBuild\bin\Debug\net472\Repro2442.MSBuild.dll. Could not load file or assembly 'S:\repro\dotnet\core\issues\2442\Repro2442.Console\..\Repro2442.MSBuild\bin\Debug\net472\Repro2442.MSBuild.dll'
```

**Comment by taori** [comment]
I am getting this issue too using 3.1.100 - What should i be using here? MSBuildLocator or MSBuildProjectLoader to get info on my csproj files?

**Comment by taori** [comment]
> 
> 
> I am getting this issue too using 3.1.100 - What should i be using here? MSBuildLocator or MSBuildProjectLoader to get info on my csproj files?

Okay. It's working now after properly calling MSBuildLocator
