### ISSUE TITLE
core 3 SDK 3.0.100-preview3-010431 JsRuntime.Current doesn't exist

### ISSUE THREAD

**Issue by niconico49** [dotnet/core#2444]
Before this update were possible to do something like:

```c#
using Microsoft.JSInterop;
using System.Threading.Tasks;
public static class MyClass
{
        public static Task<bool> someMethod(object parameter)
            => JSRuntime.Current.InvokeAsync<bool>("js.method", parameter);
}
```

saved in MyClass.cs file

and from the .cshtml file

```html
@functions {
void method() {
    object test = null;
    await MyClass.someMethod(test);
}
```

all "static"!!!!
but now you have removed .Current from JSRuntime!!!!
why? is inside some other static class or where?

I know that is possible to use

```c#
 [Inject] IJSRuntime JsRuntime { get; set; }
```

but the class will became not static and I must create the constructor for every call
for me in that situation "static" is better!!!!

**Comment by benaadams** [comment]
Probably want to raise in https://github.com/aspnet/AspNetCore

Though announcement issue for it https://github.com/aspnet/Announcements/issues/347 and discussion on change https://github.com/aspnet/AspNetCore/issues/8117

**Comment by Eilon** [comment]
Yup, what @benaadams said. Thanks, @benaadams !
