### ISSUE TITLE
Tutorial examples fail due to invalid command line option

### ISSUE THREAD

**Issue by smpeters** [dotnet/core#2445]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/create
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I ran the command `dotnet new webapi -o myMicroservice --no-https` which failed.  Based on the errors displayed, `--no-https` is not a valid parameters on the command line.

**Comment by leecow** [comment]
Did a quick successful test on my Mac using the 2.2.104 SDK so need to dig a little deeper to try and understand what you have going on. 

- What version of macOS
- What version(s) of .NET Core on the machine (dotnet --info will provide all of this)?
- What is the exact error?

**Comment by Eilon** [comment]
@ryanbrandenburg - any idea on this particular template option? Did anything change regarding it in some version?

**Comment by ryanbrandenburg** [comment]
No extra info here, so far as I know --no-https hasn't changed since March of last year. The info @leecow requested would be very helpful.

**Comment by smpeters** [comment]
```$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54```

**Comment by smpeters** [comment]
```$ dotnet new webapi -o myMicroservice --no-https
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Invalid input switch:
  --no-https

**Comment by leecow** [comment]
Thanks @smpeters - I believe `--no-https` was added in the 2.1 release so you should upgrade to at least that channel. It looks like you are running 2.0 and that went end of life October 2018.

[2.1 (our LTS release)](https://dotnet.microsoft.com/download/dotnet-core/2.1)
[2.2 (a bunch of ASP enhancements)](https://dotnet.microsoft.com/download/dotnet-core/2.2)

**Comment by ryanbrandenburg** [comment]
@smpeters let us know if that doesn't solve your issue, otherwise we'll close this out.

**Comment by smpeters** [comment]
Hmmm... it looks like it was installed with Visual Studio when I installed it in December 2018.  OK, well, I updated Visual Studio and that command works now.
