### ISSUE TITLE
linux 下载问题

### ISSUE THREAD

**Issue by FreeXiaoSuYu** [dotnet/core#2450]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-current
Operating System: Linux CentOS / Oracle

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
We need information about what you are seeing in order to try and help. If you are still having troubles, reopen this issue and please provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
