### ISSUE TITLE
boxing in struct HashCode

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/core#2451]
# Issue Title
The implementation in public struct System.HashCode perhaps should be less boxing

# General
The code does not follow the general guidlines in regards to boxing. Perhaps one could reconsider refactoring the internals of the code to get a better heep vs stack execution.

**Comment by khellang** [comment]
This would probably be better suited for https://github.com/dotnet/corefx?

**Comment by karelz** [comment]
@PeterPann23 if you have suggestion what to change, please create PR in CoreFX, thanks!

**Comment by PeterPann23** [comment]
lots of casts to uint that are not usefull

**Comment by khellang** [comment]
> lots of casts to uint

Casting to `uint` isn't boxing.

> that are not usefull

They're not just useful, they're necessary. You don't want to be bit-shifting signed integers like that.
