### ISSUE TITLE
Http response custom header not working properly asp.net core 2.2 web api response.

### ISSUE THREAD

**Issue by Gopigovin** [dotnet/core#2456]
Hi Guys, 

Http response custom header not working properly asp.net core 2.2 web api response.

We used the html upload box in our project. While upload fails, we will pass the custom message through httprequest to client side. Our server side section is in .net core project (2.1). So we have used the below code to send custom message

Response.Headers.Add("status", "File processed correctly");

It working fine core 2.1. While using the above code in .net core 2.2 project, it does not works.

How to resolve this in our side? Please suggest your ideas.

Regards,
Gopi G.

**Comment by leecow** [comment]
@dougbu @Eilon

**Comment by dougbu** [comment]
@Tratcher @anurse @muratg any ideas?

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetCore#8567
