### ISSUE TITLE
Package not found on set up .net Core

### ISSUE THREAD

**Issue by AhmetAymed** [dotnet/core#2457]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-current
Operating System: Linux Debian 9

I did sudo apt-get update after set up Os.

Os name : Raspbian 
Os Language : Turkish
I did the insructures but ı have
E: aspnetcore-runtime-2.2 paketi bulunamadı. (package not found)
exception when i type, `$sudo apt-get install aspnetcore-runtime-2.2`

Any help please.

**Comment by leecow** [comment]
We do not provide native installers for ARM devices yet. You will need to follow the guidance for installing from tar.gz found in the [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.
