### ISSUE TITLE
dotnet on cmd won't do anything

### ISSUE THREAD

**Issue by Ruben2015** [dotnet/core#2465]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
@Ruben2015 - We'll need more information to attempt to help. Operating system and did the install appear to complete correctly will be a good start. Please re-open the issue with this information if you're still have troubles.
