### ISSUE TITLE
Assets file '/src/myMicroservice/F:/TechStuff/myMicroservice/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/src/myMicroservice/myMicroservice.csproj]

### ISSUE THREAD

**Issue by manojshingare** [dotnet/core#2468]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Need details on what you're experiencing in order to try and help.
