### ISSUE TITLE
C# tutorial command fails

### ISSUE THREAD

**Issue by bclanton40** [dotnet/core#2469]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: windows

Ran this command provided from the tutorial.

`dotnet new webApp -o myWebApp --no-https`

Received this  output
`No templates matched the input template name: webApp.`

**Comment by leecow** [comment]
what version of .NET Core do you have installed? The `--no-https` flag requires 2.1 or newer. Run `dotnet --info` for complete installed version information.

**Comment by Inathi-Gqola** [comment]
To addto what @leecow said above.  If you are using a version lower thab 2.1, you can use the template name 'webApp' with 'razor'.
