### ISSUE TITLE
Not found ubuntu 18.10 install instruct document

### ISSUE THREAD

**Issue by netroby** [dotnet/core#2470]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04

Not found ubuntu 18.10 install instruct document

**Comment by karelz** [comment]
@leecow it seems we have tutorial instructions only for Ubuntu 18.04, 16.04 and 14.04, while we support also 18.10 in .NET Core 2.2: https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md#linux
But only .NET Core 2.1 supports 14.04: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux

It seems like the samples are refering to .NET Core 2.1 only ...

@netroby did you try to use Ubuntu 18.04 steps? Did they work?

**Comment by leecow** [comment]
Thanks for bringing this up. I have a PR out for the website to add 18.10 to the dropdown. In the meantime, 18.10 instruction can be found in the [linux-setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) doc.

**Comment by netroby** [comment]
See it，already had 18.10 list in the dropdown
Thanks for help.
