### ISSUE TITLE
Issue Installing dotnet on Virtual Machine

### ISSUE THREAD

**Issue by northsideauto** [dotnet/core#2472]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The error says "Windows can't open this file...    To open this file, Windows needs to know what program you want to use to open it. Windows can go online to look at it automatically, or you can manually select from a list of programs that are installed on your computer."

I've installed two programs I found on that page including WinRAR and Pacifist and I'm still having issues. I'd love any tips I can get about how to do this correctly.

Thanks!

**Comment by karelz** [comment]
Does only the tutorial fail, nothing else?
Can you try another machine/VM?

**Comment by leecow** [comment]
The error you quote usually happens which you double-click or download and run and file which Windows doesn't know about. Can you describe the steps you take to get the error?

**Comment by karelz** [comment]
Not enough info, not actionable, closing. Feel free to reopen when there is more details available ...
