### ISSUE TITLE
Error response from daemon: Dockerfile parse error line 1: unknown instruction: ��F R O M

### ISSUE THREAD

**Issue by brennfoster** [dotnet/core#2473]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows

Getting this error: "Error response from daemon: Dockerfile parse error line 1: unknown instruction: ��F R O M" when attempting to run this command: "docker build -t microservice ."

**Comment by karelz** [comment]
@leecow who can help troubleshoot Docker problems? This one seems general - maybe corrupted Docker install?

**Comment by gortok** [comment]
@brennfoster I copy and pasted the Dockerfile into a hex editor and didn't see those characters in the beginning. What did you copy the sample dockerfile into?  It's possible it left in a BOM or some other artifact when you copied the text.  Can you upload your sample repo and link us to it?

**Comment by gortok** [comment]
To resolve your issue, I'd open the dockerfile into a text editor capable of showing it in hex (I use notepad++ with HexEditor plugin); and manually removing those non characters.  The first hex addresses you should see are 46 52:
![Hex](https://user-images.githubusercontent.com/699891/54633673-0ea7d100-4a57-11e9-9c87-3af41b850baf.PNG)

**Comment by leecow** [comment]
@karelz - the illegal characters snuck in during the OP's copy/paste when creating the Dockerfile. Clean those out and it should build fine.

**Comment by karelz** [comment]
OK, seems to be user error. Closing. Let us know if that is not the case.

**Comment by brennfoster** [comment]
Sorry for not getting back to this sooner.

I typed out the content found here: https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-file into the dockerfile and I'm still getting this error. I did this using VS Code and again using Notepad++. I shouldn't have copied any illegal characters doing this.

**Comment by brennfoster** [comment]
Here's some screenshots of the error and my docker version.

![image](https://user-images.githubusercontent.com/419283/56306798-abb26400-6100-11e9-80ec-5c51c4ed98f4.png)

![image](https://user-images.githubusercontent.com/419283/56306816-bb31ad00-6100-11e9-945d-e0972935bce0.png)

**Comment by gortok** [comment]
You're definitely getting a byte-order mark being put into that file.  You need to check the encoding of the file in Notepad++ and make sure "Encode in UTF-8 with BOM" is not selected. I would change the encoding of the file to "ANSI" and try again.  I copied the same code and typed it in manually and did not get a byte-order mark, so it's likely to be a setting on your PC that's doing this.

**Comment by brennfoster** [comment]
Okay, switching encoding to "ANSI" worked. Thank you!

**Comment by KhadayatShailendra** [comment]
> You're definitely getting a byte-order mark being put into that file. You need to check the encoding of the file in Notepad++ and make sure "Encode in UTF-8 with BOM" is not selected. I would change the encoding of the file to "ANSI" and try again. I copied the same code and typed it in manually and did not get a byte-order mark, so it's likely to be a setting on your PC that's doing this (I have no knowledge of what such a setting would be).

Thanks @gortok changing encoding in notepad++ to ANSI worked for me.

**Comment by srinivasjuluri1224** [comment]
Error response from daemon: Dockerfile parse error line 1: unknown instruction: <!DOCTYPE
I am receiving this error when I am building my docker image

**Comment by srinivasjuluri1224** [comment]
> Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
> Operating System: windows
> 
> Getting this error: "Error response from daemon: Dockerfile parse error line 1: unknown instruction: ��F R O M" when attempting to run this command: "docker build -t microservice ."

perfect its working now

**Comment by vijayakumarpattanashetti** [comment]
For mac users who face this issue:

Just edit/create your Dockerfile in Python IDLE and remove extension. This worked for me.

**Comment by gowthm** [comment]
Please check your docker file. This issue come from user wrong command in docker file. It is user command **error**.
