### ISSUE TITLE
Update supported scenarios for portable PDBs

### ISSUE THREAD

**Issue by loic-sharma** [dotnet/core#2474]
This documentation seems to be out of date: https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md#supported-scenarios

It states that "Symbol server (ex: SymbolsSource.org)" do not support portable PDBs. This should be updated as nuget.org's symbol server (`https://symbols.nuget.org/download/symbols`) does support portable PDBs. For more information, please refer to: https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

@karann-msft @tmat

**Comment by leecow** [comment]
@noahfalk

**Comment by noahfalk** [comment]
Thanks! Does [this update]( https://github.com/dotnet/core/commit/c1317f1cf475a59fed6b3f6d7cfcb18aa99bf189#diff-ce42d92d63cfc4f4ca357357ab902ceb) look good?

**Comment by tmat** [comment]
LGTM
