### ISSUE TITLE
Certificate not signed

### ISSUE THREAD

**Issue by terriblespl** [dotnet/core#2475]
received the error when trying to deploy microservice to Azure. I was following the example found
here : https://dotnet.microsoft.com/learn/web/aspnet-deploy-microservice-tutorial/deploy

C:\myMicroservice>kubectl apply -f deploy-myMicroservice.yaml
Unable to connect to the server: x509: certificate signed by unknown authority

Any ideas on how to resolve would be appreciated.

**Comment by karelz** [comment]
@glennc can you help with this one? (or help route it?)

**Comment by terriblespl** [comment]
it looks like its my company that is blocking the connection

**Comment by karelz** [comment]
@terriblespl can we close it then? Or is there something for us left to do?

**Comment by terriblespl** [comment]
Yes, it can be closed. Thanks.
