### ISSUE TITLE
AddJsonOptions setting SerializerSettings.DateTimeZoneHandling to Local Causes Problems in Alaskan Timezones

### ISSUE THREAD

**Issue by yanbu0** [dotnet/core#2476]
# MVC's Json Parser Assigning Old Dates to Incorrect Timezone in Alaska 

Prior to 1983 Alaska was primarily in -10, currently it is -8.  MVC does not take this into account but Javascript's Date object does.  This only comes into play when DateTimeZoneHandling is set to local.

```
services.AddMvc().AddJsonOptions(options =>
{
    options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Local;
})
```

The problem is a date stored in the database as `1981-04-23 00:00:00` will be serialized into this: 
![image](https://user-images.githubusercontent.com/26099646/54645021-a99cad00-4a4f-11e9-9140-f8c343c6eabb.png)

If I parse this into a Date object though, Javascript knows that dates before 1983 should be -10 and parses it to:
![image](https://user-images.githubusercontent.com/26099646/54645260-4a8b6800-4a50-11e9-96b4-5f3435e552bd.png)

So everything is two hours off.

**Comment by karelz** [comment]
Is it ASP.NET Core deserialization or .NET Core deserialization? cc @tarekgh

**Comment by Eilon** [comment]
This is Json.NET deserialization but I'm not sure where the DateTime / timezone issue comes in. In other words, is this an issue with time zone data, or how Json.NET is using that info?

cc @JamesNK as well

**Comment by JamesNK** [comment]
The logic Json.NET uses when converting an existing `DateTime` to local:

```cs
        private static DateTime SwitchToLocalTime(DateTime value)
        {
            switch (value.Kind)
            {
                case DateTimeKind.Unspecified:
                    return new DateTime(value.Ticks, DateTimeKind.Local);

                case DateTimeKind.Utc:
                    return value.ToLocalTime();

                case DateTimeKind.Local:
                    return value;
            }
            return value;
        }
```

**Comment by tarekgh** [comment]
This is Windows TZ data problem. 

```
Alaskan Standard Time * **-09:00:00**
----------------------------------------------
1/1/0001 12:00:00 AM (Unspecified) - 12/31/2006 12:00:00 AM (Unspecified)
    DaylightDelta: **01:00:00**
    DaylightTransitionStart: 4/1
        DayOfWeek: Sunday
        TimeOfDay: 1/1/0001 2:00:00 AM
        Week: 1
        IsFixedDateRule: False
    DaylightTransitionEnd: 10/1
        DayOfWeek: Sunday
        TimeOfDay: 1/1/0001 2:00:00 AM
        Week: 5
        IsFixedDateRule: False
    baseUtcOffsetDelta: 00:00:00
```

Looks the data is not matching whatever JavaScript is using for time zone (I guess on Linux the data more accurate for Alalska). I would say send this issue to Windows team.

**Comment by karelz** [comment]
@tarekgh do you know how to send/report the bug to Windows?

**Comment by tarekgh** [comment]
I have reported the issue to Windows team. 

@yanbu0 if you want to track the issue with Windows team, please report it through Windows 10, you can just click the search on the task bar and then type "Feedback Hub" and then open it and report the issue. 

per that, I am going to close this issue here as there is no action from .NET side.
