### ISSUE TITLE
this happened, no idea what to do I'm a beginner

### ISSUE THREAD

**Issue by SFTSM1L3** [dotnet/core#2477]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by harissg** [comment]
I believe this can be fixed by doing the following assuming you have installed dotnet sdk.

- Head over to Environment Variables
- Select Path under "System Variables"
- Click Edit
- Click New
- Add C:\Program Files\dotnet\
- Exit "OK"
- Close terminal/cmd
- try dotnet now

**Comment by karelz** [comment]
How exactly did you install dotnet SDK, which steps did you follow? I would expect the steps to do the right thing ...

**Comment by karelz** [comment]
Not actionable, not enough info. Feel free to reopen when there is additional info available. Thanks!
