### ISSUE TITLE
Resource group could not be found.

### ISSUE THREAD

**Issue by amercehic** [dotnet/core#2480]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-deploy-microservice-tutorial/azure-resources
Operating System: windows

I am following tutorial for deploying microservice to Azure and I run into a problem.
When I run this command: 'az aks create --resource-group myMicroserviceResources --name myMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys', I received error from uploaded picture. 

![image](https://user-images.githubusercontent.com/35527380/54712626-0fbb2a00-4b4d-11e9-9042-bff3e9ee2d5a.png)

Any solutions? 
Thanks in advance!

**Comment by Eilon** [comment]
@glennc - can you have a look?

**Comment by glennc** [comment]
@amercehic Did you run the command to create the resource group first? `az group create --name myMicroserviceResources --location <location>`

**Comment by anarsen** [comment]
@amercehic Also, have you selected the correct subscription?

You can find out through `az account show`.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by surudran** [comment]
you may have multiple subscriptions.  set the subscription to default which you want to use in CLI.

https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest
