### ISSUE TITLE
Error in the command prompt

### ISSUE THREAD

**Issue by DragonCityBreeder** [dotnet/core#2485]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have tried entering the command that the tutorial says to, but it keeps coming up as an error.
![Coding 1](https://user-images.githubusercontent.com/42077039/54781896-ef927600-4bf3-11e9-8bc1-69975088bab2.JPG)

**Comment by jlindner** [comment]
It is not docnet, it is DOTNET.  Try that and see if it fixes it.

**Comment by DragonCityBreeder** [comment]
@jlindner Thank you so much! I was wondering why it wouldn't work!

**Comment by jlindner** [comment]
No problem.  Sometimes, just having a second set of eyes looking at it helps.

**Comment by DragonCityBreeder** [comment]
@jlindner That's so true. I realized that I put in `docnet` instead of `dotnet' which I tend to misspell things easily.
