### ISSUE TITLE
Apt install on Ubuntu 18.10 not working

### ISSUE THREAD

**Issue by RobSeder** [dotnet/core#2486]
## Overview:

Using the instructions from here: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-2.2.105 on Ubuntu 18.10 - something isn't working. Receiving an error of:

> **`E: Unable to locate package dotnet-sdk-2.2`**

## Steps to reproduce:

1. Created a new VM (in Hyper-V, on WIndows 10)
1. Install latest Ubuntu - specifically from `ubuntu-18.10-live-server-amd64.iso`
1. Update the OS with: `apt update && apt dist-upgrade`, etc, - reboot.
1. Run the instructions on the page above.

## Unexpected Results:

Below is what I get. Note the results of the `apt-get install dotnet-sdk-2.2` line:

```bash
root@ubuntu01:~/# wget -q https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb
root@ubuntu01:~/# dpkg -i packages-microsoft-prod.deb
(Reading database ... 101054 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.10.2) over (1.0-ubuntu18.10.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.10.2) ...

root@ubuntu01:~/# apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.7.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@ubuntu01:~/# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Get:2 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease [74.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu cosmic-security InRelease [88.7 kB]
Fetched 252 kB in 7s (35.1 kB/s)
Reading package lists... Done

root@ubuntu01:~/# apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

root@ubuntu01:~/# apt search dotnet
Sorting... Done
Full Text Search... Done
libgtk-dotnet3.0-cil/cosmic 2.99.3-2 amd64
  GTK.NET library

libgtk-dotnet3.0-cil-dev/cosmic 2.99.3-2 amd64
  GTK.NET library - development files

libgtk2.0-cil/cosmic 2.12.40-2 amd64
  CLI binding for the GTK+ toolkit 2.12

libgtk2.0-cil-dev/cosmic 2.12.40-2 amd64
  CLI binding for the GTK+ toolkit 2.12

winetricks/cosmic 0.0+20180815-1 all
  package manager for Wine to install software easily
```

**Comment by leecow** [comment]
I don't see `https://packages.microsoft.com/ubuntu/18.10/prod cosmic InRelease` reported in the 2nd apt-get update output so the repo is not being found. 

Could you let us know the output of `cat /etc/apt/sources.list.d packages.microsoft.list`? It should be something like `deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.10/prod cosmic main`

**Comment by jslang25** [comment]
##:~$ cat /etc/apt/sources.list.d packages.microsoft.list
cat: /etc/apt/sources.list.d: Is a directory
cat: packages.microsoft.list: No such file or directory
##:~$


Sent from Mailspring<https://link.getmailspring.com/link/2C9F2E59-DB5D-4419-BBED-17BF41FE9B51@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrMDJlYjVlY2IyZDJiN2EwMmUyN2Q1NzFjYTgwNTk5OTc3YzEyOTBlYWIyYTQxOTJjOTJjZjAwMDAwMDAxMThiM2E2ZmY5MmExNjljZTE5NDVjZjNiQHJlcGx5LmdpdGh1Yi5jb20%3D>, the best free email app for work
On Mar 27 2019, at 2:02 pm, Lee Coward <notifications@github.com> wrote:
I don't see https://packages.microsoft.com/ubuntu/18.10/prod cosmic InRelease reported in the 2nd apt-get update output so the repo is not being found.

Could you let us know the output of cat /etc/apt/sources.list.d packages.microsoft.list? It should be something like deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.10/prod cosmic main

**Comment by RobSeder** [comment]
## Workaround

I'm OP for this issue. I just worked around it. Using the troubleshooting from the previous Ubuntu version worked:

> **https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.105**

I did the `--purge` and the `-i` again and everything worked.

I didn't close this issue because it's still present, but above is a workaround.

**Comment by karelz** [comment]
So what is the next step here? What has to change where?
cc @dagood

**Comment by dagood** [comment]
@rowanmiller Can you put the instructions on every page that uses a package that may have been affected by the bug in https://github.com/dotnet/core/issues/2149 causing the repo lists not to be installed correctly? I didn't realize these instructions were specifically on the Ubuntu 18.04 page.

/cc @mbearup

**Comment by karelz** [comment]
@rowanmiller ping?

**Comment by rowanmiller** [comment]
@dagood @leecow can you let me know which distros the instructions should be displayed for?

At the moment we display this for Ubuntu 18.04

![image](https://user-images.githubusercontent.com/4741851/55976585-97262580-5c41-11e9-9b40-80af71bc3a8f.png)

And this for Ubuntu 16.04 and 14.04

![image](https://user-images.githubusercontent.com/4741851/55976617-ae651300-5c41-11e9-8b5e-80e1297e4bb5.png)

I'm definitely not an expert in this the Linux install area 😄, so if you can tell me what should be displayed on what distros that would be great.

**Comment by dagood** [comment]
<details><summary>It's missing for Ubuntu 18.10 (where it was hit in this issue)</summary>

https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-2.2.105

<img alt="18.10" src="https://user-images.githubusercontent.com/12819531/55978793-48cf5180-5c56-11e9-85f8-27726f3c83f3.png">

</details>

> every page that uses a package that may have been affected by the bug in #2149

@mbearup have any thoughts on this? Is there any point where this notice doesn't have to be shown?

**Comment by welkie** [comment]
Just chiming in to mention this affected me on 18.10 as well. I never thought to look at the 18.04 instructions to see that workaround with the purge command. Some output for my system (before I ran the workaround):

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

dpkg -l | grep "packages-microsoft-prod"
ii  packages-microsoft-prod                    1.0-ubuntu18.10.2                             all          Apt configuration for packages.microsoft.com

dpkg -L packages-microsoft-prod
/etc
/etc/apt
/etc/apt/sources.list.d
/etc/apt/sources.list.d/microsoft-prod.list
/etc/apt/trusted.gpg.d
/etc/apt/trusted.gpg.d/microsoft-prod.gpg
/usr
/usr/share
/usr/share/doc
/usr/share/doc/packages-microsoft-prod
/usr/share/doc/packages-microsoft-prod/changelog.Debian.gz
/usr/share/doc/packages-microsoft-prod/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/packages-microsoft-prod
```

**Comment by dagood** [comment]
@rowanmiller Any update on getting this added to the 18.10 page?

**Comment by rowanmiller** [comment]
Changes are live for 18.10.

**Comment by dagood** [comment]
Thanks! Looks good to me, closing as done.

(FWIW, the 19.04 page should also have it, once that goes up.)
