### ISSUE TITLE
Does .Net core support Extension Method.

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/core#249]
Can i use code from this [example](http://www.dotnetperls.com/extension). I tried to use it but it didn't work.

**Comment by svick** [comment]
Yes, .Net Core certainly supports extension methods. And the code from the article works for me just fine in .Net Core.

If you want help with the failure, you will have to explain:

1. What exactly did you do?
2. How exactly did it not work?

**Comment by blackdwarf** [comment]
Given the lack of activity, I'm closing this issue. Please reopen if more help is needed.
