### ISSUE TITLE
Dotnet run unhandled error

### ISSUE THREAD

**Issue by 1devill** [dotnet/core#2491]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/run
Operating System: windows 10

Необработанное исключение типа "System.BadImageFormatException" в Неизвестный модуль.
Could not load file or assembly 'C:\Windows\System32\myWebApp\bin\x86\Debug\netcoreapp2.2\myWebApp.dll'. Была сделана попытка загрузить программу, имеющую неверный формат.

**Comment by karelz** [comment]
[Translation](https://www.bing.com/translator?ref=TThis&&text=%D0%9D%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5%20%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%82%D0%B8%D0%BF%D0%B0%20%22System.BadImageFormatException%22%20%D0%B2%20%D0%9D%D0%B5%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B9%20%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C.%0ACould%20not%20load%20file%20or%20assembly%20%27C%3A%5CWindows%5CSystem32%5CmyWebApp%5Cbin%5Cx86%5CDebug%5Cnetcoreapp2.2%5CmyWebApp.dll%27.%20%D0%91%D1%8B%D0%BB%D0%B0%20%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D0%BD%D0%B0%20%D0%BF%D0%BE%D0%BF%D1%8B%D1%82%D0%BA%D0%B0%20%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%83%2C%20%D0%B8%D0%BC%D0%B5%D1%8E%D1%89%D1%83%D1%8E%20%D0%BD%D0%B5%D0%B2%D0%B5%D1%80%D0%BD%D1%8B%D0%B9%20%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82.&from=&to=en):

**Comment by karelz** [comment]
@1devill it looks like corrupted install, or something. Can you please try on another machine/VM?
Or just create new application and try that one.

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
