### ISSUE TITLE
Service unavailable.

### ISSUE THREAD

**Issue by anlarini** [dotnet/core#2492]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by leecow** [comment]
We'll need some specific information on what you're experiencing in order to help. Feel free to re-open this issue with additional details.

**Comment by anlarini** [comment]
I’m really not sure how to use this but I’m dying to learn. What exactly is a repository and where are these commands and/or repos activated? In the url ??

**Comment by karelz** [comment]
@anlarini are you familiar with GitHub and its workflows? What exactly is the problem you encountered?
