### ISSUE TITLE
.Net installation

### ISSUE THREAD

**Issue by ashilshah** [dotnet/core#2493]
I successfully installed .Net Core SDK of 64 bit on my windows system.

Then I typed command **_dotnet_** in command prompt but it says dotnet is not recognized as an internal or external command, operable program or batch file.

Please let me know how can I check whether my dotnet installation has been successfully done?

**Comment by leecow** [comment]
Did you use the installer? Type `path` at the command prompt and see if `C:\Program Files\dotnet\` is included in the list.

**Comment by ashilshah** [comment]
Got it.... Thanks.... My Bad, I was just looking till Program Files only.

**Comment by karelz** [comment]
I assume this is answered then. Closing
