### ISSUE TITLE
i try to publish on vm

### ISSUE THREAD

**Issue by rakesh4951** [dotnet/core#2496]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/run
Operating System: Linux Ubuntu 18.04

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

This site can’t be reached 104.211.99.0 refused to connect.
Search Google for 104 211 5000
ERR_CONNECTION_REFUSED

**Comment by karelz** [comment]
@rakesh4951 what is the command you run?
Did you check your OS? Did you try another (brand new) VM to avoid firewall and other VM-setup-specific problems?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
