### ISSUE TITLE
error creating new .net core project on ubuntu 18.04

### ISSUE THREAD

**Issue by BigBoss2011** [dotnet/core#2497]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: Linux Ubuntu 18.10

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

on executing the commande "dotnet new console -o myApp"
I'd received the error bellow
Failed to load �D^, error: /usr/share/dotnet/host/fxr/3.0.0-preview-27410-4/libhostfxr.so: cannot open shared object file: No such file or directory
The library libhostfxr.so was found, but loading it from /usr/share/dotnet/host/fxr/3.0.0-preview-27410-4/libhostfxr.so failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

I'd removing .NET core 3.0 preview version but the error steel there.
thank you for helping

**Comment by leecow** [comment]
Do you want to run the 3.0 Preview or a production release? How did you install and remove the Preview? 

Our recommendation for Previews is to use our [Snap installer](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview3-download.md).

**Comment by karelz** [comment]
No response for 2 weeks, closing. Feel free to reopen if you have more details. Thanks!
