### ISSUE TITLE
Why can I see support for ARM64 on 2.1.9?

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/core#2503]
The [release page of 2.1.9](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.9/2.1.9.md) shows that ARM64 binaries are available. I started jumping from my seat out of joy, but then could not find the docker images.

I thought that ARM64 support was only coming for .NET Core 3.0, so why are the binaries available?

**Comment by leecow** [comment]
We have been shipping Linux ARM64 binaries since [2.1.0](https://dotnet.microsoft.com/download/dotnet-core/2.1). @MichaelSimons for info on ARM64 images.

**Comment by MichaelSimons** [comment]
See the [.NET Core Runtime ARM64 Status](https://github.com/dotnet/announcements/issues/82) for details.

**Comment by NicolasDorier** [comment]
Ok so if I understand, support for ARM64 has been done in 2.1 but is not maintained, which is why no docker image are provided.

**Comment by MichaelSimons** [comment]
That is correct for the most part except instead of saying `2.1 but is not maintained` I would classify it as `community supported`.  Regardless, waiting for 3.0 when it is officially supported is what most customers want.
