### ISSUE TITLE
Cannot run the dotnet command on windows 8.1

### ISSUE THREAD

**Issue by JTSek** [dotnet/core#2504]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After installing the .Net Framework on Windows 8.1, I ran the dotnet command but I got an error mesage that Program cannot run because api-ms-win-crt-runtime-l1-1-0.dll is missing from my computer. 

Please need your help on this

**Comment by svick** [comment]
This almost certainly means that your Windows 8.1 installation is not up to date and you need to install a specific update. See [this document](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies) for more details.
