### ISSUE TITLE
Windows Services on .NET Core 3.0?

### ISSUE THREAD

**Issue by gordon-matt** [dotnet/core#2505]
I'm not sure if this is the right place to ask this, but will **.NET Core 3** support windows services like it is supporting WinForms and WPF? At the moment, I am using a regular **.NET Framework 4.7.1** windows service with the **Microsoft.AspNetCore.Hosting.WindowsServices** NuGet package. That app is the host and then the rest of my code is in a library that targets **.NET Standard 2.0**. It has to be this way in order to make use of other shared libraries that also target **.NET Standard 2.0**. It would be nice to know when windows services will be fully supported by .NET Core, so that this kind of workaround is not necessary.

**Comment by leecow** [comment]
@terrajobst @danmosemsft

**Comment by xqrzd** [comment]
Windows services are supported in .NET Core currently, just pull in the nuget package System.ServiceProcess.ServiceController. There's also Microsoft.Extensions.Hosting.WindowsServices, that you can use to run the new .NET generic host as a windows service.

**Comment by danmosemsft** [comment]
The answer above is correct. Please reopen if you have difficulty (or in the dotnet/corefx repo(
