### ISSUE TITLE
I am running Debian buster and I am in trouble installing dotnet due to the dependent packages not installable

### ISSUE THREAD

**Issue by GreenYun** [dotnet/core#2506]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

root@debian:~# apt install -f dotnet-runtime-deps-2.2 aspnetcore-runtime-2.2 dotnet-runtime-2.2 dotnet-sdk-2.2 -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libssl1.0.2 but it is not installable
                           Depends: libicu57 but it is not installable

**Comment by leecow** [comment]
Can you share the output of `cat /etc/apt/sources.list.d/microsoft-prod.list`?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
