### ISSUE TITLE
Error while creating webapp from console "ASP.NET Tutorial - Hello World in 10 minutes"

### ISSUE THREAD

**Issue by TruJan34** [dotnet/core#2507]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: windows 10

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I got following error.

C:\Users\trushartj>dotnet new webApp -o myWebApp --no-https --force
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.

Processing post-creation actions...
Running 'dotnet restore' on myWebApp\myWebApp.csproj...
  Restoring packages for C:\Users\trushartj\myWebApp\myWebApp.csproj...
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\Users\trushartj\myWebApp\myWebApp.csproj]
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error :   Response status code does not indicate success: 407 (Proxy Authorization Required). [C:\Users\trushartj\myWebApp\myWebApp.csproj]

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

C:\Users\trushartj\myWebApp>dotnet restore
  Restoring packages for C:\Users\trushartj\myWebApp\myWebApp.csproj...
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\Users\trushartj\myWebApp\myWebApp.csproj]
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error :   Response status code does not indicate success: 407 (Proxy Authorization Required). [C:\Users\trushartj\myWebApp\myWebApp.csproj]

Please help.

**Comment by karelz** [comment]
Do you have the same problem from multiple machines? (you can try clean VM)
Looks like a network hiccup.

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
