### ISSUE TITLE
libssl wants 1.0.0 when newer libssl versions are available; breaking installation

### ISSUE THREAD

**Issue by RobotJulia** [dotnet/core#2510]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current#ubuntu18-04-issue
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello,
I am trying to install on a Debian system which has libssl1.0.1 and libssl1.1 installed but the installer is still dependent on libssl1.0.0 breaking installation because my apt can't fix it.

**Comment by leecow** [comment]
Which installer are you trying to run? Is this a debian system or an Ubuntu system? You mention both. Please share the output of `cat /etc/os-release`, then we'll have a good starting point.

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
