### ISSUE TITLE
Better package for installing just the runtime on RHEL 7

### ISSUE THREAD

**Issue by omajid** [dotnet/core#2511]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current
Operating System: Linux RHEL - x64

The website currently suggests installing `rh-dotnet22` for both the sdk and the runtime. That is correct and it works. However, we should tell users how to install only the runtime if they want:

    yum install rh-dotnet22-dotnet-runtime-2.2

This is the scl name (`rh-dotnet22`) + the expected package name (`dotnet-runtime-2.2` based on [the docs](https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging)).

The yum command above would replace the `yum install rh-dotnet22` command on the *runtime* install page. The SDK page needs no changes.

This was prompted by [this stackoverflow question](https://stackoverflow.com/questions/55361976/net-core-runtime-only-on-linux).

**Comment by karelz** [comment]
@leecow @dagood any thoughts?

**Comment by dagood** [comment]
Thanks @omajid! We should take this change. To get to this page, the user specifically clicks a runtime setup link, so they should see how to install the runtime package. The URLs are unique (there may have been some nuance if the links went to the same page):

https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-2.2.3
https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-2.2.105

@rowanmiller Are you the right person to help make this change?

> ```
> yum install rh-dotnet22-dotnet-runtime-2.2
> ```
>
> The yum command above would replace the `yum install rh-dotnet22` command on the _runtime_ install page. The SDK page needs no changes.

**Comment by rowanmiller** [comment]
I can make this change on the site. 

This isn't my area of expertise, so couple of questions...

* For the package names, what are the names for 2.1 and 2.0? Is it `rh-dotnet20-dotnet-runtime-2.0` and `rh-dotnet21-dotnet-runtime-2.1`?
* Is the `scl enable ...` command required for the runtime?

**Comment by omajid** [comment]
IMO:

- 2.0 is EOL, so we can probably skip that
- The runtime package names are: `rh-dotnet21-dotnet-runtime-2.1` (for 2.1) and `rh-dotnet22-dotnet-runtime-2.2` (for 2.2).
- Yes, the `scl enable ..` is (unfortunately) required for all invocations of `dotnet` command. We put `dotnet` somewhere under `/opt/...` and without the `scl enable...`, `$PATH` never gets fixed up to search there. Without a `scl enable ... ` users will just get a `command not found` error.

**Comment by rowanmiller** [comment]
We have this page already for 2.0, so it will need to keep existing. We mark 2.0 as clearly EOL but still let folks install/download it if they need it. Do we have a package for it? If not, I can just leave it as-is, displaying the sdk instructions.

**Comment by rowanmiller** [comment]
Here are the staged changes. Currently I have the 2.0 instruction using the `rh-dotnet20-dotnet-runtime-2.0` package, but will hold off on publishing til I know if that is correct.

![image](https://user-images.githubusercontent.com/4741851/57048539-35961d00-6c29-11e9-8bdd-5ceee74017fc.png)

**Comment by omajid** [comment]
> Do we have a package for it? If not, I can just leave it as-is, displaying the sdk instructions.

Yes, it's named along the same lines: `rh-dotnet20-dotnet-runtime-2.0`

> Here are the staged changes

Oops. I think I see a mixup. The `scl` commands don't need to change from what they were before. Here's what the final commands should look like in each case:

2.2 SDK:

    yum install rh-dotnet22 -y     # No change from the currently live page
    scl enable rh-dotnet22 bash    # No change from the currently live page

2.2 Runtime:

    yum install rh-dotnet22-dotnet-runtime-2.2 -y  # This needs to change on the currently live page
    scl enable rh-dotnet22 bash                    # No change from the currently live page. Should be just rh-dotnet22

2.1 SDK:

    yum install rh-dotnet21 -y     # No change from the currently live page
    scl enable rh-dotnet21 bash    # No change from the currently live page

2.1 Runtime:

    yum install rh-dotnet21-dotnet-runtime-2.1 -y  # This needs to change on the currently live page
    scl enable rh-dotnet21 bash                    # No change from the currently live page. Should be just rh-dotnet21

2.0 SDK (but since it's EOL, we could leave it as it is. I don't really have a strong opinion either way)

    yum install rh-dotnet20 -y     # No change from the currently live page
    scl enable rh-dotnet20 bash    # No change from the currently live page

2.0 Runtime:

    yum install rh-dotnet20-dotnet-runtime-2.0 -y  # This needs to change on the currently live page
    scl enable rh-dotnet20 bash                    # No change from the currently live page. Should be just rh-dotnet20

**Comment by rowanmiller** [comment]
@omajid perfect, that's exactly the list I was after. Many thanks.

Changes will be live later today.

![image](https://user-images.githubusercontent.com/4741851/57248720-ed477800-6ff7-11e9-90a4-023dcb83cb98.png)

**Comment by rowanmiller** [comment]
Changes are live, so closing this issue out.
