### ISSUE TITLE
 Unable to locate package dotnet-sdk-2.2 E: Couldn't find any package by glob 'dotnet-sdk-2.2' E: Couldn't find any package by regex 'dotnet-sdk-2.2'

### ISSUE THREAD

**Issue by mastbit** [dotnet/core#2516]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Operating System: Linux Ubuntu 16.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
We'll need detailed information on how you attempted to install. Feel free to re-open this issue when that info is available.
