### ISSUE TITLE
Request: conda package for `dotnet` executable

### ISSUE THREAD

**Issue by acesnik** [dotnet/core#2518]
Installation of mono using the conda package manager is easy (https://anaconda.org/conda-forge/mono). But there doesn't appear to be a dotnet package in conda. This would make using C# dotnetcore projects in analysis pipelines easier.

**Comment by karelz** [comment]
What is conda package manager?
@leecow is it anything on our roadmap?

**Comment by acesnik** [comment]
It's a package, dependency and environment management for any language—Python, R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, C#, FORTRAN. https://conda.io/en/latest/#

It's used a lot in bioinformatics, at the very least.

**Comment by karelz** [comment]
Why should we support it over other package managers? https://en.wikipedia.org/wiki/List_of_software_package_management_systems

**Comment by acesnik** [comment]
I can't speak to its utility over other package managers, but it's frequently used in data science, so it would allow tools written in C# against .NET Core to be used like any other python/C++/java program in our pipelines.

**Comment by leecow** [comment]
An interesting idea but not something that's on our roadmap. This would be a great opportunity for a community solution, which is how we are included in Homebrew.

**Comment by karelz** [comment]
Seems to be answered, closing.
