### ISSUE TITLE
The path to an application .dll file to execute.

### ISSUE THREAD

**Issue by terieyenike** [dotnet/core#2519]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Not enough info. If you have detailed description, please paste it here.
Also, try new donwload / another machine if you can.
