### ISSUE TITLE
dotnet-core compatible packages 

### ISSUE THREAD

**Issue by fansgit** [dotnet/core#252]
Is there a central repository hosting `dotnet-core` compatible packages ? 

How is it planned to port `nuget` packages inwards ? 

Is there a complete list of the already ported packages ?

**Comment by Petermarcu** [comment]
@danmosemsft 

This is something we're looking into now and plan to generate a list as well as reach out to many of the most popular packages to make sure they can run on .NET Core.

**Comment by Petermarcu** [comment]
There are two things here:

1. We've asked for the ability to filter packages on NuGet.org by the platform you search for. 
2. We're working on adding rules to NuGet to allow you to import packages that didn't know about .NET Standard but we know are highly likely to be compatible. 

You can follow the work in the https://github.com/dotnet/standard and ask more question there if you have them.
