### ISSUE TITLE
Net Core documentation should link to source code

### ISSUE THREAD

**Issue by oliverjanik** [dotnet/core#2520]
When I go to eg: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.mvcapplicationbuilderextensions.usemvcwithdefaultroute?view=aspnetcore-2.2

it would be *very* handy to be able to quickly navigate to the source code of that particular class/method on github at a specific release tag.

Apologies if this is not the right repo.

**Comment by karelz** [comment]
@mairaw is it something the docs team did consider?

**Comment by karelz** [comment]
docs repo is probably better place ...

**Comment by mairaw** [comment]
Yeah, this was discussed at https://github.com/MicrosoftDocs/feedback/issues/433

Here's the response from the engineering team:
https://github.com/MicrosoftDocs/feedback/issues/433#issuecomment-411228539
