### ISSUE TITLE
Installing .net core 2.2 on Kali Linux

### ISSUE THREAD

**Issue by kasman007** [dotnet/core#2521]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.3) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karelz** [comment]
@dagood can you pelase help here?

**Comment by dagood** [comment]
Sure. Kali Linux isn't a supported distro, but there are ways to get this to work--see https://github.com/dotnet/core/issues/2392:

> [@leecow]
> Kali is not an officially supported distro and this is likely a subtle system dependency difference.
> 
> Couple of things you can try that may work.
> 
> 1. install using the tar.gz instead of apt-get,
> 2. install using dotnet-install.sh,
> 3. install using our Snap.
> 
> Option 3 would be my first recommendation to try. Each of these methods are detailed in our [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.

**Comment by karelz** [comment]
Closing as addressed then.
THanks @dagood!

**Comment by kasman007** [comment]
Thank you. Appreciate it!
