### ISSUE TITLE
dotnet publish is picking up other projects dotnet framework

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#2525]
# Issue Title

dotnet publish fails to publish to 2.1 with faulty reference to 2.2

# General

I am publishing a project to AWS Lambda that requires netcoreapp2.1
The csproj that is being published (BVTagging) uses <TargetFramework>netcoreapp2.1</TargetFramework> as does all of its referenced class libraries.

In the same solution is a standalone project (BVSynchronizationLocalService) that uses <TargetFramework>netcoreapp2.2</TargetFramework>
This project does not currently reference any of the 2.1 class libraries.

However, when I try to dotnet publish the 2.1 BVTagging, I get the error:
... publish: C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1005: Assets file '...\BVSynchronizationLocalService\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.1'. Ensure that restore has run and that you have included 'netcoreapp2.1' in the TargetFrameworks for your project. [...\BVSynchronizationLocalService\BVSynchronizationLocalService.csproj]

Why is this project even being referenced? Yes it is in the same solution, but that is the only reference. It is as though the dotnet publish is going from the BVTagging.csproj up to the .SLN and checking ALL of the projects in the solution for netcoreapp2.1

**Comment by karelz** [comment]
Is it specific to AWS Lambda publishing or general publish command?
Are you able to reproduce it in minimal repro? I.e. simple solution with 2 HelloWorld projects targetting 2.1 and 2.2.
I assume as a temporary workaround you can have 2 different solutions ...

**Comment by genifycom** [comment]
Hi karelz thanks for the response. I can reproduce this in dotnet publish outside of AWS publish so yes it seems to be a dotnet publish issue. My current workaround is to unload the 2.2 project to publish so I can workaround this one.

**Comment by karelz** [comment]
OK, can you create and share a minimal repro then please?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more info. Thanks!
