### ISSUE TITLE
Linux Ubuntu 19.04 support

### ISSUE THREAD

**Issue by oliverkane** [dotnet/core#2526]
Linux Ubuntu 19.04 beta is out.  Consider this a request to add this as an option for package sources, instructions how to wander into the unsupported world, or a reminder to add that option after it comes out of beta.

**Comment by karelz** [comment]
I don't think it makes sense to track each missing OS in this repo. Ubuntu is supported, latest version will be also supported once it is released.
Cc @leecow

**Comment by leecow** [comment]
Yep, we'll add it the list closer to release.

**Comment by filtration** [comment]
Hi, @leecow 

Any eta on when 19.04 will be added?

Regards.

**Comment by leecow** [comment]
There are a couple things to do first. 

1) build the 19.04 dependencies installer (https://github.com/dotnet/core-setup/issues/5852)
2) Have the packages.microsoft.com owners spin up a 19.04 repo. I've submitted this request but don't have an eta yet.

**Comment by mezzo9** [comment]
Any solutions?
How can one install dotnet core on Ubuntu 19.04?

**Comment by stevepentland** [comment]
> Any solutions?
> How can one install dotnet core on Ubuntu 19.04?

@mezzo9 until the actual Ubuntu repositories are added, you can download the prebuilt binaries from [here](https://dotnet.microsoft.com/download/dotnet-core/2.2) and add them to your path. There should be instructions when you click the link for your particular platform.

**Comment by Ayanrocks** [comment]
Whats the status of support?

**Comment by dagood** [comment]
Installing .NET Core on Ubuntu 19.04 using the binaries (`tar.gz`) is supported.

Ubuntu 19.04 Debian packages are implemented and expected to be built during the next servicing release, but we're waiting for an update from @leecow on the status of the 19.04 Microsoft package repository.

**Comment by Ayanrocks** [comment]
When using .net core with tar.gz and using it like ./dotnet create it says
dotnet-create command not found

**Comment by dagood** [comment]
@Ayanrocks please open a new issue with what you expect to happen with that command and info about your environment. (Right now it seems like you might mean `dotnet new`, but I'm not familiar with the full set of SDK tools.)

Also note that the download page gives you some tips on how to set up `dotnet` on `PATH` so you don't need to specify the full path to execute it.

**Comment by smiron** [comment]
Ubuntu 19.04 is out and all of this is still happening. Don't know .. was this release of Ubuntu unexpected or something?

**Comment by stevepentland** [comment]
@smiron I know it is not as convenient, but https://github.com/dotnet/core/issues/2526#issuecomment-486024705 works just fine in the meantime if you really need it on your machine. I'm sure they'll have a solution out in the near future and I believe there were some unforeseen package issues this time around

**Comment by smiron** [comment]
Thanks for the reply @stevepentland. I tried that yesterday. I get the below on build. And yes .. it is installed. 

```
No usable version of the libssl was found
Aborted (core dumped)
```

**Comment by stevepentland** [comment]
@smiron well the only things I can think of in that particular case on 19.04 x64 would be either

- `openssl`
- `libssl-dev`

I currently only have `openssl` installed, without libssl-dev and I have not encountered the same issue as you. Aside from that, I'm not too sure except to ask if it was for sure [these binaries](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.203-linux-x64-binaries) as that is the one I'm currently using

**Comment by dagood** [comment]
Yeah, that would be a prerequisite library issue. One benefit to having Debian packages to install is that we build a runtime-deps package that takes care of it. Really unfortunate how long it's taking.

I found https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md to point to, but... it doesn't have Ubuntu 19.04. 😕 Filed https://github.com/dotnet/core/issues/2687 about that.

**Comment by stevepentland** [comment]
Thanks @dagood! from my current setup, it looks like people can get away with:

- `libunwind8`
- `libicu63`
- `openssl`

Which are adapted from the provided link for 2.0. I notice that libunwind isn't in the 2.1 column, but I noticed that I have it locally anyway and figured it couldn't hurt :wink:

**Comment by smiron** [comment]
Turned out that I had all the packages installed but a slightly older version of the binaries. Re-downloaded dotnet and now it works - thanks for suggesting this @stevepentland 

Thanks for all the help guys! Much appreciated.

**Comment by filtration** [comment]
```
downloads="$HOME/downloads"
location="$programs/dotnet"

if [ -d "$location/2" ]; then return; fi

#########################
# Download dotnet 
#########################
if [ ! -e $downloads/dotnet-sdk-2.2.106-linux-x64.tar.gz ]; then
    wget https://download.visualstudio.microsoft.com/download/pr/9bef40df-fd90-4693-a16f-76fd40358c89/13e2cbd999ab248e9cf5d10d98d3e5fc/dotnet-sdk-2.2.106-linux-x64.tar.gz -P $downloads
fi

if [ ! -e $downloads/dotnet-sdk-3.0.100-preview3-010431-linux-x64.tar.gz ]; then
    wget https://download.visualstudio.microsoft.com/download/pr/35c9c95a-535e-4f00-ace0-4e1686e33c6e/b9787e68747a7e8a2cf8cc530f4b2f88/dotnet-sdk-3.0.100-preview3-010431-linux-x64.tar.gz -P $downloads
fi

######################
# Make the main dir
######################
if [ ! -d "$location" ]; then mkdir $location; fi

#####################
# Install version 2
#####################
if [ ! -d "$location/2" ]; then 
    mkdir $location/2; tar xf $downloads/dotnet-sdk-2.2.106-linux-x64.tar.gz -C $location/2 
fi

#####################
# Install version 3
#####################
if [ ! -d "$location/3" ]; then
    mkdir $location/3; tar xf $downloads/dotnet-sdk-3.0.100-preview3-010431-linux-x64.tar.gz -C $location/3
fi

####################
# Add to path
####################
export PATH=$PATH:$location/2


```

**Comment by dagood** [comment]
We now have Ubuntu 19.04 Debian packages for 2.1 and 2.2 which work for me! I tried them out like this:

```
docker run -it --rm ubuntu:19.04 bash -c '
  apt-get update
  apt-get install -y sudo wget

  wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
  sudo dpkg -i packages-microsoft-prod.deb

  sudo apt-get install apt-transport-https
  sudo apt-get update
  sudo apt-get install -y dotnet-sdk-2.1

  dotnet new console -o project
  cd project
  dotnet run'
```

I filed https://github.com/dotnet/core/issues/2728 to track updating the download pages to include this information.

**Comment by stevepentland** [comment]
> We now have Ubuntu 19.04 Debian packages for 2.1 and 2.2 which work for me! 

Also worked fine locally for me on my Kubuntu 19.04 install. Thanks for the update!

**Comment by ketchums** [comment]
> We now have Ubuntu 19.04 Debian packages for 2.1 and 2.2 which work for me! I tried them out like this:


Am I missing something?
`devmachine@heaven-master:~$  sudo apt-get install -y dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'
`

**Comment by dagood** [comment]
@ketchums, you may need to run the workaround steps on e.g. https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current (instead of "18.10", use "19.04" of course.)

If that doesn't fix it, please open a new issue with the output of these commands to help us diagnose:

```
# Show the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro info.
cat /etc/os-release
```

**Comment by elvisbaugh** [comment]
@ketchums Just a few weeks ago I was unble to install dotnet-sdk-2.2 on ubuntu 19.04. From what I have learnt during that time microsoft hadn't yet updated their packages so that dotnet-sdk-2.2  can be easily installed on 19.04. But now if you go on the microsft website here: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current

and follow their instructions to install dotnet-sdk-2.2 it will work. Just two things to point out:
1. You won't see a dropdown option for ubuntu 19.04 distribution (guess that will be added sometime in the future).

2. Make sure you replace the ubuntu version with 19.04 in the package link. eg
wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb

**Comment by stnlylee** [comment]
I have a solution
https://medium.com/@stnlyli/install-netcore-2-2-sdk-on-ubuntu-19-04-36173134a142

**Comment by dagood** [comment]
As of ~May 20th, 19.04 shows up in the dropdown!

I hoped I was clear with [my earlier comment](https://github.com/dotnet/core/issues/2526#issuecomment-492403195) how to get the 19.04 packages installed without instructions, but it appears the work was duplicated a couple times. Sorry about that, I'm giving some thought on how to make that happen less often.
