### ISSUE TITLE
MyStart

### ISSUE THREAD

**Issue by FireTao1** [dotnet/core#2527]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
What's the problem you're facing?

**Comment by leecow** [comment]
We need some details around what you're trying and any errors you're seeing. Feel free to re-open this issue when the extra information is available.
