### ISSUE TITLE
how to open INdex.cshtml file

### ISSUE THREAD

**Issue by rajeshwai** [dotnet/core#2528]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Rymix** [comment]
You can open this file with any text editor.
But use Visual studio.

**Comment by karelz** [comment]
Or just go to the web site if you want to see the content of the file.
