### ISSUE TITLE
Declaring minor version for dotnet-sdk-2.2

### ISSUE THREAD

**Issue by sewol2405** [dotnet/core#2537]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.2.101
Operating System: Linux Debian 9 - x64

While apt was updating my machine, I realized, that dotnet SDK was updated from 2.2.101 to 2.2.105. For my infrastructure its not possible to upgrade the application for now(Docker usage). Is there any way to specify the "2.2.**101**" version for apt?

Thanks in advance

Wolf

**Comment by leecow** [comment]
@sewol2405 - you can see specific available versions with `apt-cache madison dotnet-sdk-2.2`. To install, use `apt-get install dotnet-sdk-2.2=2.2.101-1`

Keep in mind that this will also install the older runtime files which means you will be missing any security updates which have been released. You can install the updated runtimes separately with apt install `aspnetcore-runtime-2.2` (or if you don't need ASP, `apt install dotnet-runtime-2.2`)

**Comment by karelz** [comment]
Seems to be answered. Feel free to reopen if I am wrong. Thanks!
