### ISSUE TITLE
Proposal: C++/CX support

### ISSUE THREAD

**Issue by MathiasMagnus** [dotnet/core#254]
Sorry for posting this here, but I found no better alternative, due to the highly cross-platform and cross-language nature of the issue.

**Could .NET Core support C++/CX on all supported platform?**

The sheer awesome feature of C++/CX is the ability to wrap native C/C++ applications/libraries with managed-friendly material. With the recent release of PowerShell Core, this feature could really strengthen the value of PowerShell. Though my background is scientific HPC, so my main motivation is FFTW, BLAS and alike libraries, the audience of C/C++ wrapped with script-friendly material is far larger, than the HPC community. Some of the tools I would enjoy being wrapped as Cmdlets:
- Compilers such as MSVC (cl.exe/link.exe) when refactored as a library, so that the well known command-line executable is only one of the consuming end, would enable a script-friendly Cmdlet front-end as well. Propagating compiler errors (and warnings when opted for) as exceptions would allow for script writers not to rely solely on exit codes for information, neither to resort to regex voodoo to obtain additional information.
- Makefiles generators such as [CMake](https://cmake.org/) could be wrapped with a nice ConvertFrom-CMake cmdlet to convert makefiles into [MSBuild](https://github.com/Microsoft/msbuild) or [Ninja](https://ninja-build.org/) scripts with tab-completion of available generators on the system. Note, that while MSBuild has a PS wrapping project ([psbuild](https://github.com/ligershark/psbuild)), but features such as Write-Progress support (a long time dream of mine) requires programmatic access to the internals of the MSBuild machinery.

These are only a few examples of what I head in mind off the top of my head, but surely, there are a horde of C/C++ tools and utilities out there that could benefit from some managed and script love.

**Comment by svick** [comment]
C++/CX is targeted at the (Windows-specific) WinRT, it's not a general language usable with native libraries, so I don't think it makes much sense for .Net Core.

C++/CLI is not specific to WinRT, so it could make more sense; there's already a discussion about it at the CoreCLR repo: https://github.com/dotnet/coreclr/issues/659.

**Comment by richlander** [comment]
We have no plans for this and have had very few requests for it. Thanks.
