### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll missing 

### ISSUE THREAD

**Issue by AlbasterGaster** [dotnet/core#2541]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows 
OS version: Windows 7 Ultimate
error:  when trying dotnet command prompt this error pops up: api-ms-win-crt-runtime-l1-1-0.dll is missing. I'm unable to continue the tutorial without the missing script.

**Comment by karelz** [comment]
@dagood is it a known issue?

**Comment by dagood** [comment]
Yes, this happens when necessary updates aren't installed for Windows 7.

@AlbasterGaster, take a look at https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies for help on setting up your machine.

**Comment by AlbasterGaster** [comment]
turns out the computer never had updates installed. 11 updates in total, It's going to take awhile. I will reinstall when it finishes. Thank you for your time gentlemen.
