### ISSUE TITLE
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

### ISSUE THREAD

**Issue by leechuyem** [dotnet/core#2546]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: Linux Ubuntu 18.10 - x64

OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded:

**Comment by karelz** [comment]
Can you try it on another machine or VM? It looks like incomplete steps (eg paths not set) or corrupted install

**Comment by leechuyem** [comment]
Turns out, I needed to link omisharp to the sdk. 
I've fixed it by adding an omisharp.json file to the project folder.
