### ISSUE TITLE
Core 3.0 预览版编译的 WinForm 程序在没有安装 Runtime 并配置的系统上无法运行

### ISSUE THREAD

**Issue by 15092368540** [dotnet/core#2560]
我希望 Core 编译的 WinForm 程序只要与依赖的 dll 文件同处于同一目录中就可以正常运行，而无需安装和配置 Runtime，即便是在 Win PE 上也可以运行

**Comment by karelz** [comment]
Please use English. We do not scale to translate from various languages ourselves.

Translation:
I want the Core-compiled WinForm program to work as long as it is in the same directory as the dependent DLL files without having to install and configure Runtime, even on Win PE

**Comment by karelz** [comment]
Self-contained applications should enable that.
Not sure if WinPE is supported though - there may be some important OS components missing there.
