### ISSUE TITLE
.NET SDK problem (0xc000007b)

### ISSUE THREAD

**Issue by PranksterHalcyon** [dotnet/core#2561]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Whenever I type dotnet on cmd to make sure everything is installed correctly, this error (0xc000007b) pops up stating the application was unable to start correctly.

Hope you can accommodate me!
![image](https://user-images.githubusercontent.com/49463587/55845641-92555a80-5af7-11e9-8c1e-d1da064cd469.png)

**Comment by karelz** [comment]
Given that it is the first report I see of this type, I would guess corrupted install or machine. Try different machine or VM.

**Comment by leecow** [comment]
Closing as the thread has gone quiet. Please re-open if there is you are still having trouble and have additional information to provide.
