### ISSUE TITLE
The "Create Feedback" button does not work in Safari 12.1 on macOS 10.14.4

### ISSUE THREAD

**Issue by spATLASti** [dotnet/core#2564]
# Issue Title
The "Create Feedback" button does not work in Safari 12.1 on macOS 10.14.4

# General

1. Coming from https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
2. When clicking "I ran into an issue"
3. The "Create Feedback" button does not work in Safari 12.1 on macOS 10.14.4

**Comment by karelz** [comment]
@leecow @mairaw do you know where is the web site functionality tracking?

**Comment by leecow** [comment]
@rowanmiller 

I tried this on my system (also Safari 12.1 / macOS 10.14.4) and it worked fine.

**Comment by rowanmiller** [comment]
@spATLASti Is it the `Leave feedback` button that you are talking about? If so, was the issue that nothing happened when you clicked it?

![image](https://user-images.githubusercontent.com/4741851/55913876-8f5f7600-5b9a-11e9-93cf-3b95021fd1d1.png)

**Comment by spATLASti** [comment]
Exactly.

**Comment by rowanmiller** [comment]
Thanks for confirming. There are occasions when the system we use for in-site feedback isn't loaded and we should handle this more gracefully. I've opened an issue to fix this in our internal bug tracker for the website.

**Comment by spATLASti** [comment]
Thank you all for the work!
