### ISSUE TITLE
When I try to install he can add the key (Doesnt find KeyServer) and dont download the List.

### ISSUE THREAD

**Issue by blackside2000** [dotnet/core#2565]
Problem encountered on "Ubuntu .Net Installation Tutorial"
Operating System: Linux Ubuntu 18.04 - x64

I copy and paste the commands correctly and try many different solutions but the issue happens, the terminal says that he doesnt find the key server and the List file is not found making unable to install .Net on Ubuntu. This happens with some apps too.

**Comment by karelz** [comment]
@blackside2000 can you please post exact steps you did and what was the result?
Did you get the same problems on more than 1 machine / VM?

**Comment by karelz** [comment]
No response in 2+ weeks, not actionable, closing. Feel free to reopen when there is actionable info. Thanks!
