### ISSUE TITLE
libicu55 dependencies conflicts with libcicu60 used by others

### ISSUE THREAD

**Issue by jaykrell** [dotnet/core#2567]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current#ubuntu18-04-issue
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Looks similar to #1822 -- @dagood?
cc @omajid @tmds @tarekgh

**Comment by dagood** [comment]
No, this looks related to the unfortunate version-specific `libicuXX` dependency in our Debian packages.

The Ubuntu 18.04 `dotnet-runtime-deps-2.2` package *should* depend on `libicu60`, so this conflict doesn't make sense. I have a writeup of this issue at https://github.com/dotnet/core-setup/issues/4247#issuecomment-480553725 for some more info how how this could be caused. (Basically: unclean system.)

@jaykrell, can you provide logs of what's going wrong, and run these steps to diagnose?

```sh
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show what version of libicu you have available to you.
apt search libicu
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

**Comment by karelz** [comment]
@dagood should we move it to core-setup? Or is it too early?

**Comment by dagood** [comment]
Good point, moving.

**Comment by dagood** [comment]
Issue moved to [dotnet/core-setup #5780](https://github.com/dotnet/core-setup/issues/5780) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dagood** [comment]
Moved to https://github.com/dotnet/core-setup/issues/5780.
