### ISSUE TITLE
No package rh-dotnet22 available

### ISSUE THREAD

**Issue by sudheerforu** [dotnet/core#2568]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-2.2.4
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by sudheerforu** [comment]
[micloud@blrvslalm0026 ~]$ sudo yum install rh-dotnet22 -y
Loaded plugins: product-id, subscription-manager
https://cdn.redhat.com/content/beta/rhel/server/7/x86_64/rt/os/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

No package rh-dotnet22 available.
Error: Nothing to do
[micloud@blrvslalm0026 ~]$ ^C

**Comment by karelz** [comment]
@dagood @leecow 
@omajid @tmds

**Comment by omajid** [comment]
@sudheerforu Can you install any other packages? Does `sudo yum install coreutils` work? If not, I would suggest contacting Red Hat support to figure out what is configured incorrectly with your installation.

**Comment by tmds** [comment]
> To address this issue please refer to the below knowledge base article
https://access.redhat.com/solutions/69319

@sudheerforu have you done this?

**Comment by sudheerforu** [comment]
I am able to install other software’s using yum

Regards
Sudheer T

________________________________

**Comment by sudheerforu** [comment]
Yes I have done that but no luck

Regards
Sudheer T

________________________________

**Comment by omajid** [comment]
@sudheerforu Have you tried doing all the steps on https://access.redhat.com/documentation/en-us/net_core/2.2/html/getting_started_guide/gs_install_dotnet#install_register_rehel? Does that work?

**Comment by sudheerforu** [comment]
I have performed all the issues given in the above link and it worked,Thank you all.
