### ISSUE TITLE
-bash: dotnet: command not found

### ISSUE THREAD

**Issue by benster1** [dotnet/core#2569]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
after runing dotnet new webApp -o myWebApp --no-https  I get  -bash: dotnet: command not found
dotnet sdk already installed

**Comment by leecow** [comment]
The installer should have added the dotnet install location to your path. Could you run the following in a terminal window and see if any dotnet entries are shown?

`echo $PATH | grep dotnet`

**Comment by leecow** [comment]
Closing this up. If you have additional info, feel free to re-open.
