### ISSUE TITLE
How to Get All Child Process PIDs

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/core#257]
I tried this

var searcherObj = new ManagementObjectSearcher("SELECT * FROM Win32_Process WHERE ParentProcessId=" + Process.GetCurrentProcess().Id);
Process[] childProcesses = searcherObj.Get();

 but it seems to doesn't work with .Net Core.
 Do you know another way to get all child processes?

**Comment by stevenshort** [comment]
Did you ever solve this?

**Comment by SerhiiS-in6k** [comment]
Hi. No.

**Comment by DongLei-tw** [comment]
Anybody got a solution?

**Comment by Petermarcu** [comment]
Did you try https://www.nuget.org/packages/System.Management/4.5.0-preview1-25914-04 . Its still in preview but enables System.Management API's on .NET Core 2.0.

**Comment by adibyte95** [comment]
System.Management is only for windows
