### ISSUE TITLE
not use anymore!!!!!!

### ISSUE THREAD

**Issue by batsword** [dotnet/core#2573]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-2.1.300
Operating System: Linux CentOS / Oracle - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

----------------------------------------------------------------
rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
sudo yum update
sudo yum install dotnet-sdk-2.1

not work! tips:no package~~
i am really not well. network is workng,package can't be pulled.!!!

**Comment by leecow** [comment]
Could let us know the exact message you see when attempting to install?

**Comment by batsword** [comment]
i have used docker replace that way

**Comment by batsword** [comment]
yum install aspnetcore-runtime-2.1  
or
yum install aspnetcore-runtime-2.2  

ehco back:
loaded plugins:fastestmirror
`
`
`
No package aspnetcore-runtime-2.1  available.
Error:Nothing to do


@leecow

**Comment by leecow** [comment]
It seems like packages.microsoft.com isn't registered correctly. Could you run `rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm` again? You should see output similar to the following.

```
[root@1c6446d1d015 /]# rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
Retrieving https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
warning: /var/tmp/rpm-tmp.qkVWAj: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:packages-microsoft-prod-1.0-1.el7################################# [100%]
[root@1c6446d1d015 /]# yum update
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.jaleco.com
 * extras: mirror.jaleco.com
 * updates: mirror.jaleco.com
packages-microsoft-com-prod                                                                                                                  | 2.9 kB  00:00:00
packages-microsoft-com-prod/primary_db                                                                                                       | 164 kB  00:00:00
No packages marked for update
```

Then a search for the package ...

```
[root@1c6446d1d015 /]# yum search aspnetcore-runtime-2.1
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.jaleco.com
 * extras: mirror.jaleco.com
 * updates: mirror.jaleco.com
=============================================================== N/S matched: aspnetcore-runtime-2.1 ================================================================
aspnetcore-runtime-2.1.x86_64 : Microsoft ASP.NET Core 2.1.10 Shared Framework
aspnetcore-runtime-2.1.0-preview2-final.x86_64 : Microsoft ASP.NET Core 2.1.0-preview2-final Shared Framework
aspnetcore-runtime-2.1.0-rc1-final.x86_64 : Microsoft ASP.NET Core 2.1.0-rc1-final Shared Framework
```

**Comment by batsword** [comment]
rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
sudo yum update
this work
but next step:
sudo yum install dotnet-sdk-2.1
it also tips :
No package aspnetcore-runtime-2.1 available.
Error:Nothing to do

**Comment by batsword** [comment]
yum search aspnetcore-runtime-2.1

i will try this.
later echo the result~3q
