### ISSUE TITLE
How do I add a line and then save "Program.cs" in Notepad and then in "Command Prompt" run "dotnet run" again?

### ISSUE THREAD

**Issue by anviljdp2** [dotnet/core#2574]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

How do I add a line and then save "Program.cs" in Notepad and then run "dotnet run" again? My "Program.cs" ended up looking like this:

using System;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
Console.WriteLine("The current time is " + DateTime.Now);
        }    
}
}

and in my "Command Prompt," my "dotnet run" did not run.

**Comment by leecow** [comment]
`dotnet run` will rebuild the app if any changes are detected. Can you expand on "dotnet run did not run"? Was there an error? Did it run without your code change? Did it do nothing?

**Comment by leecow** [comment]
Closing because thread has gone quiet. Please re-open if you have additional information.
