### ISSUE TITLE
installing Flash drive driver

### ISSUE THREAD

**Issue by siemoppe** [dotnet/core#2578]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Unclear what the problem is, or if there is any. Closing. Feel free to reopen with additional details ...

**Comment by siemoppe** [comment]
> Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
> Operating System: windows
> 
> Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I  have an Acer Aspire E 17 running under Windows 8.1, that cannot run a card reader 3.0. I updated all my drivers, but that did not help.

**Comment by siemoppe** [comment]
Oh yes,if I plug the device in, I shows on Windows explorer,but I can't open it.

**Comment by karelz** [comment]
How is that related to .NET Core?

**Comment by siemoppe** [comment]
don't know what you means(?)

**Comment by karelz** [comment]
Same here. What is your question about? This is .NET Core GitHub repo.
If you don't know what .NET Core is, then you are in the wrong place.
