### ISSUE TITLE
"the following packages have unmet dependencies" error when installing dotnetcore on ubuntu 18.04

### ISSUE THREAD

**Issue by imranulhaq** [dotnet/core#2580]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I get the following error on the last command.
--------------------------------------------------------
The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karelz** [comment]
@leecow @dagood is it known issue?

**Comment by dagood** [comment]
The steps work for me in a fresh ubuntu:18.10 Docker container. The most common reason for this to happen is that a mismatching Microsoft package repository is being used, like Ubuntu 16.04's and the old package depends on a libicu that no longer exists.

@imranulhaq Can you run these commands and post the output to help diagnose?

```sh
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met. (Probably libicu##)
sudo apt-get install dotnet-runtime-deps-2.2
# Show what version of libicu you have available to you.
apt search libicu
```

**Comment by imranulhaq** [comment]
There was some version mismatch issue. I was creating the latest ubuntu image (18.04) and was trying to add dotnet core with commands that were not correct for this version. Kindly refer to the below URL for getting the correct commands according to the docker OS. 
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current#ubuntu18-04-issue

Thank you @dagood  for your prompt feedback. Much appreciated.

**Comment by karelz** [comment]
@imranulhaq is your question answered now? Or do you still need help? (sorry it is not clear to me from your reply ...)

**Comment by imranulhaq** [comment]
@karelz yeah my issue is solved now. I posted the link so that anyone else facing the same issue can use it to get the correct versions. Again much appreciated for such prompt feedback

**Comment by dagood** [comment]
Thanks for confirming, closing as resolved. 🙂
