### ISSUE TITLE
Problem encountered on installation of DotNet on Linux Fedora 29 - x64

### ISSUE THREAD

**Issue by HenrikBach1** [dotnet/core#2583]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Fedora 28 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I followed your above installation guide.

When I tested my `dotnet` installation in a new terminal, I got the below result:

```
[sad@localhost ~]$ dotnet
bash: dotnet: command not found
[sad@localhost ~]$ echo $PATH 
/home/sad/.local/bin:/home/sad/bin:/home/sad/.local/bin:/home/sad/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
```

However, my Operating System is: `Linux Fedora 29 - x64`

/Henrik

**Comment by dagood** [comment]
Moving to Core-Setup, this could be a problem with the `dotnet-host` package.

**Comment by dagood** [comment]
Issue moved to [dotnet/core-setup #5832](https://github.com/dotnet/core-setup/issues/5832) via [**ZenHub**](https://www.zenhub.com/)
