### ISSUE TITLE
command line install of dotnet-sdk error on Kali

### ISSUE THREAD

**Issue by idzireit** [dotnet/core#2590]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karelz** [comment]
@dagood is it known problem?

**Comment by dagood** [comment]
Yeah, copying from https://github.com/dotnet/core/issues/2521:

Kali Linux isn't a supported distro, but there are ways to get this to work--see https://github.com/dotnet/core/issues/2392:

> Kali is not an officially supported distro and this is likely a subtle system dependency difference.
> 
> Couple of things you can try that may work.
> 
> 1. install using the tar.gz instead of apt-get,
> 2. install using dotnet-install.sh,
> 3. install using our Snap.
> 
> Option 3 would be my first recommendation to try. Each of these methods are detailed in our [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.
