### ISSUE TITLE
error during dotnet core 2.2 installation on Ubuntu:

### ISSUE THREAD

**Issue by pgkrishnan205** [dotnet/core#2591]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-2.2.0
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I get following error during dotnet core 2.2 installation on Ubuntu:
------------------------------------------------------------
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 ca-certificates : Depends: openssl (>= 1.1.0) but 1.0.2g-1ubuntu4 is to be installed
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by dagood** [comment]
This is likely a failure to find dependencies. What is the output when you try
`apt-get install dotnet-runtime-deps-2.2`?

**Comment by raaraya** [comment]
Got similar problems in my installation on Ubuntu 19.04, however it seems that I am not the only one with problems on Ubuntu.
```
sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

And when trying to get the other dependencies:
```
sudo apt-get install dotnet-runtime-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.2 : Depends: dotnet-runtime-deps-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
```
sudo apt-get install dotnet-runtime-deps-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libssl1.0.2 but it is not installable
                           Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

But couldn't install such dependencies in the end:
```
sudo apt-get install libssl1.0.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0.2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.2' has no installation candidate
```
```
sudo apt-get install libicu57
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libicu57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu57' has no installation candidate
```

**Comment by raaraya** [comment]
On the other hand I also found that I have `libssl1.1` installed, however `libssl1.0.2` is not and cannot be located in the Ubuntu 19.04 repositories.

```
sudo apt install libssl1.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl1.1 is already the newest version (1.1.1b-1ubuntu2).
libssl1.1 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by pgkrishnan205** [comment]
> This is likely a failure to find dependencies. What is the output when you try
> `apt-get install dotnet-runtime-deps-2.2`?

Hello, Thanks for your reply on this.

I got it fixed by running apt --fix-broken install, it is all good now.

**Comment by dagood** [comment]
@pgkrishnan205 Awesome, thanks for posting back. Reading the output in the original issue again, it wasn't actually quite the situation I thought it was... glad you were able to resolve it.

@raaraya 19.04 is a different issue, it's known not to work right now. It looks like the "main" issue is https://github.com/dotnet/core/issues/2526. (I expect 19.04 to work with the next servicing release.)
