### ISSUE TITLE
The content on get start page cannot work. 

### ISSUE THREAD

**Issue by hunter-xue** [dotnet/core#26]
I tried to install .net core and run hello world follow the get start page, but either Mac OSX or Ubuntu cannot work. 
Get start page URL: http://dotnet.github.io/getting-started/
My Mac OS version is Capitan EI and Ubuntu is 14.04 LTS. 

Alway get error when I run "dotnet run" like below: 
[on MAC OS]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

[on Ubuntu 14.04 LTS]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.Console.WriteLine(String value)
   at HelloWorldSample.Program.Main()

**Comment by StefanKert** [comment]
You need to replace the dependencies section of the given project.json file with following json:

	"dependencies": { 
		"System.Console": "4.0.0-beta-*", 
		"System.IO": "4.0.10-beta-*",
		"System.Runtime": "4.0.21-beta-*" 
	}

System.Console depends on System.IO so you need to get this package to get it running. Same problem exists for Windows and for Linux. Maybe this has something to do with Nuget? Shouldn´t it restore the needed Depencies for the installed packages?

**Comment by hunter-xue** [comment]
Many thanks for you reply. Ubuntu is working well with upon settings, but still get the same error on MAC OSX EI Capitan 10.11.1
I guess maybe there are something wrong with nuget, but I don't know what happened. 

[project.json on MAC OSX]
"dependencies": { 
    "System.Console": "4.0.0-beta-*", 
    "System.IO": "4.0.10-beta-*",
    "System.Runtime": "4.0.21-beta-*" 
}
[Error msg]
/Users/xuehaitao/Coding/dnx/p03/project.json(9,22): warning NU1012: Dependency conflict. Microsoft.NETCore.Runtime.CoreCLR 1.0.1-beta-23516 expected System.IO 4.0.11-beta-23516 but got 4.0.10-beta-23109
/Users/xuehaitao/Coding/dnx/p03/project.json(9,22): warning NU1012: Dependency conflict. Microsoft.NETCore.Runtime.Native 1.0.1-beta-23516 expected System.IO 4.0.11-beta-23516 but got 4.0.10-beta-23109

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

[project.json on MAC OSX]
"dependencies": {
        "System.Console": "4.0.0-beta-23019", 
        "System.Runtime": "4.0.21-beta-*" 
    },
[Error msg]
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processenvironment-l1-1-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.Console.<>c__DisplayClass0.<get_Out>b__3()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.WriteLine(String value)
   at ConsoleApplication.Program.Main(String[] args)

**Comment by dlech** [comment]
I came across this issue because I am getting the same errors on OSX 10.11.

One difference I noticed between "System.Console": "4.0.0-beta-23019" and later versions are that the later versions are missing `lib/DNXCore50/*`. Also beta-23019 has `ref/dotnet/` whereas the later versions have `ref/dotnet5.1`.

**Comment by StefanKert** [comment]
Hey there,

from this line in your error message: 

Microsoft.NETCore.Runtime.CoreCLR 1.0.1-beta-23516 expected System.IO 4.0.11-beta-23516 but got 4.0.10-beta-23109

I expect you have some troubles with conflicting references between the packages. I really cannot test this on a MAC, but I tested it on a Win 10 and it worked fine.
If you use this dependencies it should work for you. Just replace the System.IO 4.0.10. package with the 4.0.11 package.

	"dependencies": { 
		"System.Console": "4.0.0-beta-*", 
		"System.IO": "4.0.11-beta-*", 
		"System.Runtime": "4.0.21-beta-*" 
	}, 
	"frameworks": { "dnxcore50": { } }

**Comment by dlech** [comment]
I'm still getting an error with those dependecies and dnxcore50.

```gerda:dotnet-hello david$ dotnet restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

  CACHE https://www.nuget.org/api/v2/
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /Users/david/work/dotnet-hello/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'
  GET https://api.nuget.org/v3-flatcontainer/system.console/index.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'
  GET https://api.nuget.org/v3-flatcontainer/system.io/index.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://api.nuget.org/v3-flatcontainer/system.runtime/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.io/index.json 916ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console' 1091ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime' 915ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO' 917ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime/index.json 922ms
  OK https://api.nuget.org/v3-flatcontainer/system.console/index.json 966ms
Writing lock file /Users/david/work/dotnet-hello/project.lock.json
Restore complete, 1835ms elapsed

NuGet Config files used:
    /Users/david/.config/NuGet/nuget.config

Feeds used:
    https://www.nuget.org/api/v2/
    https://api.nuget.org/v3-flatcontainer/
    /Users/david/work/xdg-base-directory
gerda:dotnet-hello david$ dotnet run

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Is there a way to turn on more verbose output, like `DNX_TRACE=1` in ASP.NET 5?

**Comment by hunter-xue** [comment]
Looks like we run into a compatibility issue on MAC OS 10.11.1

**Comment by blackdwarf** [comment]
The project.json are now updated for all samples. However, I can repro the issue with System.Console on OS X as well. Will log an issue at dotnet/cli to actually solve this.

**Comment by jgowdy** [comment]
I have this exact same issue on Ubuntu.  The version of System.IO seems to be bumped to 4.0.11, which breaks the dotnet init sample project.json, but even when I fix that, it gives me:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by blackdwarf** [comment]
@jgowdy I don't follow, the samples' project.json System.IO is set to 4.0.11-beta-23516. So, did you try the old clone, by any chance?

Also, the System.Console thing is something more in depth, but I see you already mentioned it in dotnet/cli#291 so that's good.

**Comment by jgowdy** [comment]
I originally tried with the "dotnet init" version which seems to still be the old one pointed to 4.0.10-beta-*.  Then I modified to have the 4.0.11-beta-23516 version for System.IO, which got me past that problem, but I'm stuck at the Could not load file or assembly issue.

dnx run works, despite the fact that dotnet run doesn't work, and dotnet compile generates an executable that throws the same error as dotnet run.

**Comment by pjustino** [comment]
Hi,

I'm also having problems with the dotnet restore on ubuntu.14.04-x64.

The error is the following:

info : Installing System.IO 4.0.11-beta-23516.
error: System.Console 4.0.0-beta-23516 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
error: System.Text.Encoding 4.0.0 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
error: System.Threading.Tasks 4.0.0 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64).
info : Committing restore...

My project.json is this one:
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
	"System.Console": "4.0.0-beta-*", 
	"System.IO": "4.0.11-beta-*",
	"System.Runtime": "4.0.21-beta-*" 
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

**Comment by brthor** [comment]
@pjustino Please try using the project.json provided by `dotnet new`

Those dependencies are very old

**Comment by pjustino** [comment]
Hi @brthor ,

Thanks for the help. I created a new sample with the project.json provided and I still got an error restoring the packages:

warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23727) but ended up with NETStandard.Library 1.0.0-rc3-23720.
warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23727) but ended up with NETStandard.Library 1.0.0-rc3-23720.
error: System.Security.Principal.Windows 4.0.0-rc3-23720 provides a compile-time reference assembly for System.Security.Principal.Windows on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64).
info : Committing restore...


project.json file:
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23727"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

**Comment by brthor** [comment]
@pjustino Can you give this a try:
`dotnet restore -s https://myget.org/f/dotnet-core-rel`

**Comment by pjustino** [comment]
It restored the dependencies with success, but when I tried to run (dotnet run) it gave me the following error:

Could not resolve coreclr path

Here is my nuget.config file:
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

**Comment by brthor** [comment]
@pjustino How did you install the cli?

**Comment by pjustino** [comment]
with the command:

sudo apt-get install dotnet-nightly

**Comment by blackdwarf** [comment]
Seems like something is messed up with the deb package. It is installed in `/usr/share/dotnet-nightly` so @pjustino can you try to do `export DOTNET_HOME=/usr/share/dotnet-nightly` and see if it fixes it?

**Comment by brthor** [comment]
Just gave this a try on the latest version and was not able to repro.

If you do `apt-cache policy dotnet-nightly` which version do you have installed?

**Comment by brthor** [comment]
@blackdwarf there is a symlink in place `/usr/share/dotnet -> /usr/share/dotnet-nightly` in the latest version which should not require that environment variable to be set.

**Comment by pjustino** [comment]
Hi @blackdwarf  it worked.

@brthor  the version I have installed is:
dotnet-nightly:
  Installed: 1.0.1.001172-1
  Candidate: 1.0.1.001174-1

Thanks for the help

**Comment by blackdwarf** [comment]
@pjustino can you try to purge dotnet-nighly and then reinstall, remove the var and see if it repros still?

**Comment by brthor** [comment]
What version of Ubuntu are you on?

**Comment by pjustino** [comment]
@brthor   the sim link is not set properly is a regular folder

@blackdwarf  now it gives an error retrieving the deb package:

Err http://apt-mo.trafficmanager.net/repos/dotnet/ trusty/main dotnet-nightly amd64 1.0.1.001174-1
  404  Not Found
E: Falhou obter http://apt-mo.trafficmanager.net/repos/dotnet/pool/main/d/dotnet-nightly/dotnet-nightly_1.0.1.001174-1_amd64.deb  404  Not Found


Is the package still building?

**Comment by pjustino** [comment]
Linux Mint 17 Qiana

**Comment by brthor** [comment]
The package is syncing across mirrors in that 404. I am working on getting this issue fixed.

We don't currently support Linux Mint. For the moment the DOTNET_HOME workaround is the way to go. I'll have to take a look at this later.

For the package, you can keep trying or install a previous version like
`sudo apt-get install dotnet-nightly=1.0.1.001172-1`

**Comment by pjustino** [comment]
@brthor  I finally managed to get the package. 

I solved by creating myself the symbolic link with this command:

sudo ln -s /usr/share/dotnet-nightly/ dotnet

Thanks for your help, it helped alot.
Cheers

**Comment by blackdwarf** [comment]
@pjustino seems like this is resolved. I will close the issue; if you find this repros again, please reopen.
