### ISSUE TITLE
When I put in dotnet run, it doesn't return Hello World!

### ISSUE THREAD

**Issue by Con351** [dotnet/core#2601]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

I'm using .net core 3.0 preview 3, and the issue was that it couldn't find a project to run, however in Microsoft's own tutorial, it says it should already contain, and run, Hello World.

**Comment by leecow** [comment]
You do need to create a new project to run. See https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create.
