### ISSUE TITLE
Error while creating an AKS(Azure Kubernetes Service) cluster in the resource group

### ISSUE THREAD

**Issue by sethvikas** [dotnet/core#2604]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-deploy-microservice-tutorial/azure-resources
Operating System: Windows 10 (version 1809)

I was trying to run the example from above URL to deploy a microservice to Azure. I was able to create the resource group successfully using the command 'az group create --name VikasTestMicroserviceResources --location westus'. The next was to create an AKS(Azure Kubernetes Service) cluster in the resource group using the below command:

az aks create --resource-group VikasTestMicroserviceResources--name VikasTestMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys

This command failed with the below error:
"Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service VikasTestMicroserviceCluster in resource group VikasTestMicroserviceResources failed. Message: Resource 'aks-agentpool-37645640-routetable' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"SDOStdPolicyNetwork","id":"/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/providers/Microsoft.Authorization/policyAssignments/SDOStdPolicyNetwork"},"policyDefinition":{"name":"SDOStdPolicyNetwork","id":"/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/providers/Microsoft.Authorization/policyDefinitions/SDOStdPolicyNetwork"}}]'.. Details:"

Kindly suggest what can I do to overcome this error. Thank you for looking into this issue.

**Comment by Pilchie** [comment]
@glennc / @davidfowl any ideas?

**Comment by davidfowl** [comment]
Contact azure support? This looks unrelated to anything .NET

**Comment by Pilchie** [comment]
Closing due to lack of response.

**Comment by kuiwen** [comment]
Any update for this? Hit the same issue
