### ISSUE TITLE
Failed to fetch https://packages.microsoft.com/ubuntu/14.04/prod/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

### ISSUE THREAD

**Issue by kristopher** [dotnet/core#2608]
Failed to fetch https://packages.microsoft.com/ubuntu/14.04/prod/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

Occurs after installing this package and running apt-get update. 
https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb

Started getting that error this morning while running chef. Did the same runs yesterday without issue. Not sure if something in the repo changed or what.

**Comment by yairyog** [comment]
Seeing the same issue since yesterday

**Comment by karelz** [comment]
@dagood is it known problem? cc @leecow 

Which version are you installing? .NET Core 2.1 / 2.2 / 3.0 Preview 4?

**Comment by levhaikin** [comment]
same here.
trying to install .net core 2.2

**Comment by dagood** [comment]
It certainly looks like the 14.04 Microsoft repo is broken. People are unable to get Powershell with the same error: https://github.com/PowerShell/PowerShell/issues/9424. It's also easy to repro in Docker.

Doc link for reference: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu14-04/sdk-current. You don't even get as far as picking which SDK to install so 2.1 vs. 2.2 etc. doesn't matter.

Ubuntu 14.04 hit end of standard support just a couple days before this issue was filed--got to wonder if that's related.

@leecow can you reach out to Microsoft repo owners?

**Comment by justinboswell** [comment]
Also seeing the same issue, installing .NET Core 2.2 during ```apt-get update```

**Comment by dagood** [comment]
I've reached out to the Microsoft repository admins via email about this issue, will update here with more info.

**Comment by bonesoul** [comment]
same here.

**Comment by kristopher** [comment]
I also thought it was very coincidental that is started a few days before 14.04 goes EOL

**Comment by dagood** [comment]
The Microsoft repo admins are looking into it, no status yet.

`ubuntu-distro-info` tells me it's EOL 5 days ago, FWIW (but I wouldn't expect it to affect this):

```sh
#> ubuntu-distro-info --all -yeol -f | grep 14.04
Ubuntu 14.04 LTS "Trusty Tahr" -5
#> date -d 'now - 5 days'
Wed Apr 17 22:16:07 UTC 2019
```

**Comment by dagood** [comment]
They fixed it! I confirmed in an `ubuntu:14.04` container. Thanks for filing the issue.

**Comment by jakkaj** [comment]
I've started seeing this issue again today on a Dockerfile that worked yesterday. 

`W: Failed to fetch https://packages.microsoft.com/ubuntu/14.04/prod/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch`

**Comment by shachar-av** [comment]
Same here, issue happens again.

**Comment by beldougie** [comment]
We're also experiencing this issue since approximately 5pm UTC yesterday although we're trying to install msodbcsql17 and ms-tools, the symptoms are the same. I have also tried the suggested trick of clearing `/var/lib/apt/lists/*` but there was no change to the situation.

**Comment by dagood** [comment]
Yeah... repros with a clean Docker container as well. Sending another mail to the Microsoft repo admins.

**Comment by bonesoul** [comment]
same here

**Comment by yairyog** [comment]
same...

**Comment by dagood** [comment]
They fixed it, and I confirmed it works for me now. Thanks for the reports!

**Comment by kimbaudi** [comment]
Instead of creating a new issue, I thought I should mention here that I started receiving the following error this morning when I attempted to reinstall dotnet-sdk-2.1 after `sudo apt upgrade` caused the same exact issue (which is why I uninstalled dotnet and reinstalled dotnet-sdk2.2 and dotnet-sdk2.1).

```sh
$ sudo apt install dotnet-sdk-2.1 -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-runtime-2.1 dotnet-hostfxr-2.1 dotnet-runtime-2.1 dotnet-runtime-deps-2.1
The following NEW packages will be installed:
  aspnetcore-runtime-2.1 dotnet-hostfxr-2.1 dotnet-runtime-2.1 dotnet-runtime-deps-2.1 dotnet-sdk-2.1
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 134 MB of archives.
After this operation, 387 MB of additional disk space will be used.
Err:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-runtime-deps-2.1 amd64 2.1.12-1
  404  Not Found [IP: 13.91.48.226 443]
Err:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-hostfxr-2.1 amd64 2.1.12-1
  404  Not Found [IP: 13.91.48.226 443]
Err:3 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-runtime-2.1 amd64 2.1.12-1
  404  Not Found [IP: 13.91.48.226 443]
Err:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 aspnetcore-runtime-2.1 amd64 2.1.12-1
  404  Not Found [IP: 13.91.48.226 443]
Err:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-sdk-2.1 amd64 2.1.701-1
  404  Not Found [IP: 13.91.48.226 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-runtime-deps-2.1/dotnet-runtime-deps-2.1.12-x64.deb  404  Not Found [IP: 13.91.48.226 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-hostfxr-2.1/dotnet-hostfxr-2.1.12-x64.deb  404  Not Found [IP: 13.91.48.226 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-runtime-2.1/dotnet-runtime-2.1.12-x64.deb  404  Not Found [IP: 13.91.48.226 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/a/aspnetcore-runtime-2.1/aspnetcore-runtime-2.1.12-x64.deb  404  Not Found [IP: 13.91.48.226 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-sdk-2.1/dotnet-sdk-2.1.701-x64.deb  404  Not Found [IP: 13.91.48.226 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by dagood** [comment]
@kimbaudi The error you're receiving is also different, `404  Not Found` rather than `Hash Sum mismatch`. Can you open a new issue with the rest of the commands and output too? (`sudo apt-get update` in particular.)

**Comment by kimbaudi** [comment]
@dagood yes, I just submitted [issue 3010](https://github.com/dotnet/core/issues/3010)

**Comment by ruimaciel** [comment]
I'm also experiencing this issue, but with Ubuntu 18.04 running dotnet 2.2.401.

Here's the output of a `sudo apt-get update`

```
rui@localhost:~$ sudo apt-get update
[sudo] password for rui: 
Hit:1 http://pt.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://pt.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                                                                                      
Hit:3 http://pt.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                                                                                    
Hit:4 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease                                                                                                                                                                  
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                                                                                       
Hit:7 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                                                                                                       
Hit:8 https://download.docker.com/linux/ubuntu bionic InRelease                                                                                                                                                                       
Get:9 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3226 B]                                                                                                                                
Hit:6 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                                                               
Hit:10 https://packages.gitlab.com/runner/gitlab-runner/ubuntu bionic InRelease                       
Get:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66,6 kB]
Err:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
  Hashes of expected file:
   - Filesize:66619 [weak]
   - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
   - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
   - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
   - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
Fetched 3226 B in 2s (1475 B/s)                          
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jhawe** [comment]
> I'm also experiencing this issue, but with Ubuntu 18.04 running dotnet 2.2.401.
> 
> Here's the output of a `sudo apt-get update`
> 
> ```
> rui@localhost:~$ sudo apt-get update
> [sudo] password for rui: 
> Hit:1 http://pt.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:2 http://pt.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                                                                                      
> Hit:3 http://pt.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                                                                                    
> Hit:4 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease                                                                                                                                                                  
> Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                                                                                       
> Hit:7 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                                                                                                       
> Hit:8 https://download.docker.com/linux/ubuntu bionic InRelease                                                                                                                                                                       
> Get:9 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3226 B]                                                                                                                                
> Hit:6 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                                                               
> Hit:10 https://packages.gitlab.com/runner/gitlab-runner/ubuntu bionic InRelease                       
> Get:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66,6 kB]
> Err:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
>   File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
>   Hashes of expected file:
>    - Filesize:66619 [weak]
>    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
>    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
>    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
>    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
>   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
> Fetched 3226 B in 2s (1475 B/s)                          
> Reading package lists... Done
> E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
>    Hashes of expected file:
>     - Filesize:66619 [weak]
>     - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
>     - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
>     - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
>     - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
>    Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```

same for me

**Comment by rob-glas** [comment]
Yep happening again.

**Comment by kangaroodle** [comment]
Being affected by the same issue.

**Comment by s177437** [comment]
Being affected by the same issue here

**Comment by roblen45** [comment]
Being affected by the same issue here

**Comment by Tychus** [comment]
can confirm dealing with the same here.

**Comment by joefavergel** [comment]
I have the same issue trying update repositories on Ubuntu 18.04.

**Comment by Tychus** [comment]
#3221

**Comment by gongwan33** [comment]
Ubuntu 18.04 cannot update
Hit:1 http://mirrors.cloud.aliyuncs.com/ubuntu bionic InRelease
Hit:2 http://mirrors.cloud.aliyuncs.com/ubuntu bionic-updates InRelease               
Hit:3 http://mirrors.cloud.aliyuncs.com/ubuntu bionic-security InRelease                                     
Get:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3,226 B]                            
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease                                              
Get:6 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66.6 kB]                  
Err:6 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.76.190.189 443]
  Hashes of expected file:
   - Filesize:66619 [weak]
   - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
   - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
   - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
   - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease                   
Hit:8 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.76.190.189 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]

**Comment by Isazero** [comment]
I have same problem
Hit:1 http://kg.archive.ubuntu.com/ubuntu bionic InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://kg.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:5 http://kg.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:7 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease    
Get:8 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3,226 B]
Get:10 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66.6 kB]
Err:10 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
  Hashes of expected file:
   - Filesize:66619 [weak]
   - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
   - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
   - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
   - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
Reading package lists... Done   
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by dagood** [comment]
This (or something very similar) is definitely happening again! The current issue is tracked by https://github.com/dotnet/core/issues/3221.

**Comment by harshavardhana** [comment]
Looks like this is happening again on our 16.04 builds on Ubuntu
```
lists...
4763
[91mE: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.gz  Hash Sum mismatch
4764
E: Some index files failed to download. They have been ignored, or old ones used instead.
4765
[0mThe command '/bin/sh -c apt-get --yes update && apt-get --yes 
```

**Comment by dagood** [comment]
@harshavardhana Yep! The current outage is tracked over at https://github.com/dotnet/core/issues/3988.

I'm going to lock this issue to encourage everyone to file new issues rather than add comments to this one, since it's happened a couple times now. Because the thread is closed, new comments might not be seen by the right people in the future. A new issue is more likely to get noticed. There's nothing wrong with posting relevant comments to old issues, but I want to make sure outages are seen as soon as possible. Thanks!
