### ISSUE TITLE
Please make new version of .NET Core not bound to linux version

### ISSUE THREAD

**Issue by rv82** [dotnet/core#261]
Hello! When I install current version of dotnet to, e.g. OpenSUSE 42.1, it doesn't work. The almost same history is with Linux Mint 18. Dotnet's CLI tools work, but debugging in VSCode doesn't work and appears message: "unsupported linux version".

I like .NET Core very much but I cannot use it with more fresh linuces, then specified in tools and SDK. Please make new version of .NET Core not bound to linux version (and specific versions of libraries) like java and other universal tools/sdks/environments.

Thank you!

**Comment by richlander** [comment]
Yes. We would like this, too. We haven't decided on a particular solution for this yet.

/cc @blackdwarf

**Comment by Petermarcu** [comment]
@janvorli , Can you make sure we have an issue tracking this in the coreclr repo. @rv82 , we're actively investigating this.
