### ISSUE TITLE
MongoDB Driver Exception in Preview 4

### ISSUE THREAD

**Issue by cyberjaws** [dotnet/core#2611]
I installed .NET Core Preview 4, startup my app, and received this exception. This is a .NET Core Console Application that is referencing an object in a .NET Standard Library. The types all appear appear in the debugger however the mongo driver throws this exception. 

I moved back to .NET Core Preview 3, recompiled, and there is no issue.

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap' threw an exception.
  Source=MongoDB.Bson
  StackTrace:
   at MongoDB.Bson.Serialization.BsonClassMap.LookupClassMap(Type classType)
   at MongoDB.Bson.Serialization.BsonClassMapSerializationProvider.GetSerializer(Type type, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Bson.Serialization.BsonSerializerRegistry.CreateSerializer(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MongoDB.Bson.Serialization.BsonSerializerRegistry.GetSerializer[T]()
   at MongoDB.Driver.MongoCollectionImpl`1..ctor(IMongoDatabase database, CollectionNamespace collectionNamespace, MongoCollectionSettings settings, ICluster cluster, IOperationExecutor operationExecutor)
   at MongoDB.Driver.MongoDatabaseImpl.GetCollection[TDocument](String name, MongoCollectionSettings settings)
   ...

Inner Exception 1:
ArgumentNullException: Value cannot be null.
Parameter name: type
```

**Comment by karelz** [comment]
Are you able to compare working and non-working repro side by side to figure out what changed between those 2?
We need to narrow down which API behavior change in .NET Core caused the misbehaior. It is also possibility (albeit small) that it is a bug in the library, or elsewhere ...

**Comment by ebekker** [comment]
I think [this](https://github.com/mongodb/mongo-csharp-driver/blob/v2.8.x/src/MongoDB.Bson/Serialization/BsonClassMap.cs#L40) be the problem.

**Comment by ebekker** [comment]
MongoDB driver needs a reference to [`System.Runtime.Serialization.Formatters`](https://www.nuget.org/packages/System.Runtime.Serialization.Formatters/).

**Comment by mostafa-tag** [comment]
> Are you able to compare working and non-working repro side by side to figure out what changed between those 2?
> We need to narrow down which API behavior change in .NET Core caused the misbehaior. It is also possibility (albeit small) that it is a bug in the library, or elsewhere ...



> I installed .NET Core Preview 4, startup my app, and received this exception. This is a .NET Core Console Application that is referencing an object in a .NET Standard Library. The types all appear appear in the debugger however the mongo driver throws this exception.
> 
> I moved back to .NET Core Preview 3, recompiled, and there is no issue.
> 
> ```
> System.TypeInitializationException
>   HResult=0x80131534
>   Message=The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap' threw an exception.
>   Source=MongoDB.Bson
>   StackTrace:
>    at MongoDB.Bson.Serialization.BsonClassMap.LookupClassMap(Type classType)
>    at MongoDB.Bson.Serialization.BsonClassMapSerializationProvider.GetSerializer(Type type, IBsonSerializerRegistry serializerRegistry)
>    at MongoDB.Bson.Serialization.BsonSerializerRegistry.CreateSerializer(Type type)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at MongoDB.Bson.Serialization.BsonSerializerRegistry.GetSerializer[T]()
>    at MongoDB.Driver.MongoCollectionImpl`1..ctor(IMongoDatabase database, CollectionNamespace collectionNamespace, MongoCollectionSettings settings, ICluster cluster, IOperationExecutor operationExecutor)
>    at MongoDB.Driver.MongoDatabaseImpl.GetCollection[TDocument](String name, MongoCollectionSettings settings)
>    ...
> 
> Inner Exception 1:
> ArgumentNullException: Value cannot be null.
> Parameter name: type
> ```

I faced the same exception after upgrading to .net 3.0 preview 4 , it was working fine with preview 3

**Comment by EvgenSav** [comment]
I've the same issue on 3.0 preview 4. Is there any solution?

**Comment by mostafa-tag** [comment]
a fix was done but not yet merged to the master branch nor branch 2.8
https://github.com/mongodb/mongo-csharp-driver/pull/372

**Comment by karelz** [comment]
Looks like external problem, with solution. Closing.

**Comment by Malavos** [comment]
@mostafa-tag  will the PR be merged in the future?

@ebekker  what did you do to fix the problem?

**Comment by mostafa-tag** [comment]
I believe it should be merged because the fix was made by @KonH<https://github.com/KonH> via a pull request on the master branch .

Mostafa Tag-

**Comment by Malavos** [comment]
@mostafa-tag  thank you. I have also made contact with one of the maintainers of the mongo driver. Let's wait for their input now.

**Comment by ebekker** [comment]
The fix in the PR looks like it will address the issue by referencing the missing `Serialization.Formatters` package.  For the time being I've reverted back to the preview 3 until the change is officially released in the MongoDB driver -- don't want to mess around with building my version, it would be overkill for my current needs.

**Comment by dewelloper** [comment]
I am facing same problem in version 2.8 even i have downgrade project to 2.7.3 problem same but no problem with 2.7.2
What has been there :)
