### ISSUE TITLE
Problem encountered on installation of DotNet on Linuxmint Tessa 19

### ISSUE THREAD

**Issue by hattricks98** [dotnet/core#2613]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04 - x64

I'm not able to install it on my linux mint Tessa => 19.

`sudo apt-get install -y gpg`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
 gnupg : Depends: gpg (= 2.2.4-1ubuntu1.1)
 gpg : Depends: gpgconf (= 2.2.4-1ubuntu1.2)
 gpg-wks-client : Depends: gpg (= 2.2.4-1ubuntu1.1)
 gpg-wks-server : Depends: gpg (= 2.2.4-1ubuntu1.1)
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by karelz** [comment]
Is it supported distro? @leecow @dagood

**Comment by dagood** [comment]
It is (https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md#linux). I'm not sure how you're supposed to install based on the dropdown in the tutorial, but it would make sense to me if the Ubuntu 19.04 packages will work on Linux Mint 19. Ubuntu 19.04 package availability is discussed in https://github.com/dotnet/core/issues/2526.

@hattricks98, In the meantime, you should be able to install from tarball or Snap. There's a document about these methods here: https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md. More download links are at https://dotnet.microsoft.com/download.

Closing based on comment in https://github.com/dotnet/core/issues/2526 that we aren't tracking new release bringup in this repo. (I think we need to figure out a reasonable place for people to look for this info, though.)
