### ISSUE TITLE
This site can’t be reached localhost refused to connect. 

### ISSUE THREAD

**Issue by sindhuindurthi** [dotnet/core#2616]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
@sindhuindurthi can you please check your firewall settings, etc.?
That is usually what is causing these kind of troubles.
Another option is to try it out on fresh new VM where firewall settings are not present yet.
Let us know how it goes!

**Comment by karelz** [comment]
No response for 6 days, closing. Feel free to reopen once there is actionable info. Thanks!

**Comment by sindhuindurthi** [comment]
Hello... Arijith sandbox..  thank you @Google
