### ISSUE TITLE
Cannot install dotnet-sdk-2.2 on Debian - Raspberry Pie

### ISSUE THREAD

**Issue by federico-caldas-tdn** [dotnet/core#2622]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Followed instructions as in https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current

On last step, when trying to install dotnet sdk I get the following error

`pi@raspberrypi:~ $ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by regex 'dotnet-sdk-2.2'
`

**Comment by karelz** [comment]
@dagood any thoughts? cc @richlander

**Comment by dagood** [comment]
Raspberry Pi uses an ARM architecture--the x64 instructions on that page won't work for it. You can find Linux ARM32/ARM64 SDK download links at https://dotnet.microsoft.com/download.
