### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by luisa2011** [dotnet/core#2623]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Cannot download:  
https://download.visualstudio.microsoft.com/download/pr/b5b2c515-9909-4912-9631-b5b8adeaac1f/e44d9456a5ffb5d325f361f3babc67c0/dotnet-sdk-2.2.203-win-gs-x64.exe

**Comment by MarioLung** [comment]
same here

**Comment by karelz** [comment]
Are you able to donwload the link directly? (it works for me)

@leecow @dagood can you please take a look?

**Comment by dagood** [comment]
It works for me too (clicking the button on the getting started site, as well as direct). Initial guess would be a CDN issue, but I don't know how to follow up on that.

@vivmishra any ideas?

**Comment by vivmishra** [comment]
Same here, I could download this successfully -- maybe it was a temporary issue. 

@luisa2011 if you continue to see this then I'll get CDN folks involved to see if they can track it down.

**Comment by karelz** [comment]
@luisa2011 @MarioLung were you able to try it again?

**Comment by karelz** [comment]
No update/info, closing
