### ISSUE TITLE
error running dotnet

### ISSUE THREAD

**Issue by AutodidacticStar** [dotnet/core#2625]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I get this message: 
Thrown:
ReferenceError: dotnet is not defined
>

**Comment by ljgstudy** [comment]
did you open the NEW command prompt to test _dotnet_ command?

**Comment by karelz** [comment]
Seems like new command prompt with env var set ws not opened. Closing.
