### ISSUE TITLE
.NetCore 2.2 not using ViewFeature or IRazorCompiledItemprovider

### ISSUE THREAD

**Issue by ShaZeh** [dotnet/core#2629]
.NetCore 2.2 not using ViewFeature or IRazorCompiledItemprovider

I recently made a custom IApplicationFeature for ControllerFeature which is added after adding MVC to the services 👍 

```c#
services.AddMvc()
.ConfigureApplicationPartManager(apm =>
 {
      apm.FeatureProviders.Add(new CustomControllerProvider(typeof(Startup).Assembly));
  // apm.FeatureProviders.Add(new CustomViewProvider(typeof(Startup).Assembly));
  // apm.ApplicationParts.Add(new CustomRazorViewProvider(typeof(Startup).Assembly)); 
})
```

While this appear to work fine for the ControllerFeature, .net core seems to ignore any changes made in in the ViewFeature or RazorCompiledItemProvider.

When using the ViewFeature provider, the code execute PopulateFeature multiple time (for each assembly I am assuming) and even if I clear the entire list of ViewDescriptors, the views appear to load fine as if no changes had been done. 

I thought it was perhaps because the ViewFeature is now marked as obsolete, so I have tried implementing the IRazorCompiledItemProvider as an application part as suggested. However the results are even worse, views are still loaded even if no items are returned by the CompiledItems property.

I am starting to believe that something silly might have been missed, do we need to do anything unusual within our controllers to obtain the views such as using dependency injection with a specific type or it should just works with the embedded View() method.

Sorry if I might have misunderstood how the feature should work, there is not much documentation about it. I haven't tested adding views yet , perhaps these implementations only support adding elements as opposed to the ControllerFeature which support both adds and removes. It would still be an issue regardless though.

**Comment by Eilon** [comment]
@javiercn / @pranavkm - any ideas on this? Should we move this issue to AspNetCore?

**Comment by pranavkm** [comment]
> Should we move this issue to AspNetCore?

Yes please

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetCore#9748
