### ISSUE TITLE
macosx install pc

### ISSUE THREAD

**Issue by jcr111** [dotnet/core#2631]
# command "dotnet" after install says :"  command not found

Macos Mojave 10.14.3
install successfully completed with "dotnet-sdk-3.0.100-preview4-011223-osx-x64.pkg"

**Comment by dagood** [comment]
Did you try to run `dotnet` in an existing terminal, or did you open a new one?

The "getting started" tutorial has this tip: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install. It might be useful to follow along with that with your 3.0 SDK.

If you open a new terminal and still have this problem, the next thing I think we should check is:

```
ls /etc/paths.d
cat /etc/paths.d/dotnet
```

**Comment by jcr111** [comment]
Hi,

Thanks for your quick answer which solve my issue.

I effectively ran the dotnet command in an already opened terminal…

Best regards 

JCR

Le 24 avr. 2019 à 17:17, Davis Goodin <notifications@github.com> a écrit :

Did you try to run dotnet in an existing terminal, or did you open a new one?

The "getting started" tutorial has this tip: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install <https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install>. It might be useful to follow along with that with your 3.0 SDK.

If you open a new terminal and still have this problem, the next thing I think we should check is:

ls /etc/paths.d
cat /etc/paths.d/dotnet

**Comment by dagood** [comment]
Good to hear! No problem. 😄
