### ISSUE TITLE
Lack 3.0.100-preview4 in releases.json

### ISSUE THREAD

**Issue by minhhieugma** [dotnet/core#2632]
# Issue Title

Could not fetch download information for version 3.0.100-preview4 in Devops CI

![image](https://user-images.githubusercontent.com/9654744/56648875-489b7100-66ae-11e9-8388-85b3257a6891.png)

**Comment by karelz** [comment]
@minhhieugma I would recommend to copy paste text instead of screenshot picture. Text in pictures is not searchable.

@dagood is it a known issue? cc @leecow

**Comment by dagood** [comment]
I'm not familiar with releases.json updates. Maybe @vivmishra?

**Comment by vivmishra** [comment]
Release Metadata that has the CDN path is at: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.0/releases.json

If you are directly downloading from the Azure blob then the path is as per following:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/**3.0.100-preview4-011223/dotnet-sdk-3.0.100-preview4-011223-linux-x64.tar.gz** 

@minhhieugma where are you picking up the paths from as I see an obvious problem in that.

**Comment by dagood** [comment]
It looks like the AzDO task uses an old static URL pointing at the deprecated GitHub releases json:

https://github.com/Microsoft/azure-pipelines-tasks/blob/e239620b93b1d2c6339893cc86b0d51d6bf2ee88/Tasks/DotNetCoreInstallerV0/releasesfetcher.ts#L148

```ts
const DotNetCoreReleasesUrl: string = "https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json";
```

Deprecation announcement: https://github.com/dotnet/core/issues/1986.

I would move, but the AzDO task repo has an extensive issue template that we might not want to bypass.

**Comment by dagood** [comment]
Closing: I filed https://github.com/Microsoft/azure-pipelines-tasks/issues/10213 to get the process rolling on a fix.
