### ISSUE TITLE
where can i find the program.cs file so that i can edit it

### ISSUE THREAD

**Issue by soumyagupta123** [dotnet/core#2633]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Which commands / steps did you run?
Do you know where the project was created?
Did you try to search for the file?
Which OS are you on?

**Comment by karelz** [comment]
Not enough info, no reply for 3 weeks. Closing.
