### ISSUE TITLE
ASP Hello world - webApp is not a template

### ISSUE THREAD

**Issue by Raamyy** [dotnet/core#2640]
Problem encountered on [Asp Hello World](https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create)
Operating System: windows

When I type **_dotnet new webApp -o myWebApp --no-https_** in the cmd  It says: **No templates matched the input template name: webApp.**

My Dotnet version is **2.1.102** 

How to solve it ?
Thanks

**Comment by Eilon** [comment]
@Raamyy can you show the output of `dotnet --info`?

@vijayrkn / @seancpeters - any idea on this?

**Comment by svick** [comment]
As far as I can tell, `dotnet new webApp` (which was added in https://github.com/aspnet/Templating/pull/467) requires a newer version of the .Net Core SDK. Of the SDKs installed on my machine, it works with 2.1.300, but doesn't work on 2.1.202.

@Raamyy Can you [install the latest version of the SDK](https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install) and try again?
