### ISSUE TITLE
Fail to save child records by using EF Core 2.2.4 after upgrading .Net Core from 2.1.5 to 2.2.4

### ISSUE THREAD

**Issue by Michaelwan777** [dotnet/core#2641]
Fail to save child records 

Hi! My project is developed by using .Net Core 2.1.5. Recently, I upgraded my project to 2.2.4. After the upgrading, searching performance becomes faster, which is nice. However, I realized that it failed to save multiple child records completely. It can only save the last record of multiple child records(There is no such serious case in 2.1.5) I'm still investigating the reasons for this bug.  

# General
.NET Core: From 2.1.5 to 2.2.4
OS: Win10
EF Core: 2.2.4

**Comment by ajcvickers** [comment]
@Michaelwan777 This looks like an EF issue, so I moved it to https://github.com/aspnet/EntityFrameworkCore/issues/15507
