### ISSUE TITLE
Dot Net 

### ISSUE THREAD

**Issue by SimonD123** [dotnet/core#2642]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

In the CMD.exe the code is
C:\users\user> 
instead of 
C:\users\user\

so it will not run.

**Comment by karelz** [comment]
I don't understand what you mean. The prefix `C:\users\user>` is just cmd prompt, not something you need to type. What am I missing?

**Comment by SimonD123** [comment]
![dotnet screen 1](https://user-images.githubusercontent.com/50017573/56867757-245acf80-69e1-11e9-9f53-b8a654f5fc56.PNG)
![dotnet screen 2](https://user-images.githubusercontent.com/50017573/56867759-26bd2980-69e1-11e9-8ef9-4c95050d5601.PNG)

Hi,

I have attached two screen shots.  One showing the instructions on the website and the other showing what happened when I tried to run the file.

Regards

Simon

**Comment by svick** [comment]
@SimonD123 "Run your app" is just one section of the tutorial, and does not make sense on its own. At the very least, it looks like you have not followed the ["Create your app"](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create) section.

If you did, your command prompt would be `C:\Users\User\myApp>` (notice that it has `\` where you have `>`) and if you typed `dotnet run`, it would run the app. You're certainly not supposed to type the `myApp>` part.

**Comment by karelz** [comment]
Answered above, thanks @svick!
