### ISSUE TITLE
Core3 EF Migration Issue

### ISSUE THREAD

**Issue by ikonezg** [dotnet/core#2645]
# Issue Title

Can't do Add-Migration InitMigration . I'm getting 'Unable to create an object DataContex'

# General

It was just empty DbContex class.

**Comment by karelz** [comment]
@ikonezg can you please raise it on EF Core repo? https://github.com/aspnet/EntityFrameworkCore
I assume `Add-Migration` and `InitMigration` are some dotnet commands specific to EFCore?
