### ISSUE TITLE
.NET Core Nightly build links by version

### ISSUE THREAD

**Issue by prajaybasu** [dotnet/core#2649]
I wanted to test the fix to a known issue in .NET Core 3.0 Preview 4 which was supposed to be fixed in a specific daily build for Preview 5 (not yet announced as of now),  but I cannot find a list of the daily build SDK version numbers and their download links - it seems like the repository only has the link to the *latest* build - which is currently at Preview 6. 

The CI link is private and it seems like the only way to figure out the download link is guesswork - I had to check the recently updated dockerfile to figure out the download link syntax from blob storage.

Are there any plans to make a publicly accessibly list of nightly builds with download links so that users can install them before the preview is announced - like the MyGet feeds? Preview 5 was finalized 2 days ago and I'd like to test the fix before it is announced.

Perhaps something like a tracker that polls https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/latest.version for changes
and maintains a list with entries like https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$Env:DOTNET_SDK_VERSION/dotnet-sdk-$Env:DOTNET_SDK_VERSION-win-x64.zip (and .exe) would be nice.

**Comment by KexyBiscuit** [comment]
See https://github.com/dotnet/core-sdk/tree/master/README.md

**Comment by KexyBiscuit** [comment]
Release/3.0.1XX (3.0.x Runtime) would be what you want.
