### ISSUE TITLE
About dll filename with version info

### ISSUE THREAD

**Issue by akaylh** [dotnet/core#2655]
Java jar package, the file name is with version information, this is very intuitive, it is conducive to troubleshooting, although the nuget package has version information, but the final product is a dll file. You can see the version information through the file properties under windows. But it is very troublesome under linux. Is there a plan to support similar features?

jar:

<img width="157" alt="企业微信截图_15565219272756" src="https://user-images.githubusercontent.com/437330/56880979-72c7a700-6a91-11e9-8a75-a65ac564bd4b.png">

dll:

![image](https://user-images.githubusercontent.com/437330/56881022-94c12980-6a91-11e9-9e4e-06799eded77d.png)

**Comment by karelz** [comment]
Is it developer scnario? Your project file has nuget versions baked in.
Or is it "I have random app installed on my computer and want to find details about its DLLs"-scenario? That would be best addressed by tools like ildasm and other to open the DLL and browse its custom attributes, assembly version, etc.

**Comment by karelz** [comment]
Not actionable, closing.
