### ISSUE TITLE
RID missing architecture for sdk version version: "1.1.12" in releases.json of channel 1.0  

### ISSUE THREAD

**Issue by hiyadav** [dotnet/core#2656]
# Issue Title

RID is missing architecture for version 1.1.12 sdk in file https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/1.0/releases.json. This cause DotNetCoreInstallerTaskV2 version to fail as the matching os-arch RID "ubuntu.16.04-x64" could not be found. 

Kindly update the same. and if more such anomalies are present.

# General

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by karelz** [comment]
@leecow can you please take a look?
