### ISSUE TITLE
packages-microsoft-prod.deb for Ubuntu 19.04 contains wrong component

### ISSUE THREAD

**Issue by dagood** [dotnet/core#2657]
@fubar-coder commented on [Mon Apr 29 2019](https://github.com/dotnet/core-setup/issues/6175)

## Steps to reproduce

```bash
wget https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

## Expected  behavior

Line in `/etc/apt/sources.list.d/microsoft-prod.list` should read:

```text
deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod disco main
```

## Actual behavior

Line in `/etc/apt/sources.list.d/microsoft-prod.list` is actually:

```text
deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod xenial main
```

The distribution identifier ist wrong. It's `xenial` instead of `disco`.

## Environment data

Ubuntu 19.04

**Comment by dagood** [comment]
FYI @leecow, if this feed is meant to be set up, it isn't done correctly quite yet.

@fubar-coder, for more info about 19.04, check out https://github.com/dotnet/core/issues/2526. Even if this feed worked, we don't have .NET Core packages uploaded there yet.

**Comment by dagood** [comment]
Assigning based on this todo:

> Have the packages.microsoft.com owners spin up a 19.04 repo. I've submitted this request but don't have an eta yet.

Might be closable as a duplicate but I don't know the current state of communications with the Msft repo owners.

**Comment by leecow** [comment]
I've sent an email to them about the config deb error. Looks like prod.list is correct but, as you say, we don't have any files up yet. 19.04 install will be available for the May Update.

**Comment by fubar-coder** [comment]
I know that there are no packages (and didn't really expected any), but just wanted to report this error to avoid problems in the future (when packages are available) 😁

**Comment by NathanHannon** [comment]
Hopefully the packages are released soon. I need this for school!

**Comment by dagood** [comment]
@NathanHannon what for? If you just need to get .NET Core set up, there's no need to wait, check out https://github.com/dotnet/core/issues/2526.

**Comment by carlossanlop** [comment]
@leecow @dagood was this resolved? Can we close the issue or does this need more followup?

**Comment by dagood** [comment]
Yep, Lee got in touch with the repo admins, who fixed it.
