### ISSUE TITLE
Can't follow .Net tutorial

### ISSUE THREAD

**Issue by Slawson91gd** [dotnet/core#2659]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Was following along with the tutorial and was able to create my first app using the command prompt. Now the tutorial wants me to open the Program.cs file for editing. HOWEVER, When I try to open the program in Visual Studio 2019, this is what is says: "The following files were specified on the command line:  C:\Windows\System32\MyApp\Program.cs - These files could not be found and will not be loaded." 

I've followed the instructions to a T and now I can go no further. Might anyone have some kind of advice or solution? I'm just starting to pick up on dotnet and now I'm stuck before I've even gotten anywhere and it's VERY frustrating.
![Command Line BS](https://user-images.githubusercontent.com/42984603/56927416-baeac780-6a99-11e9-93ca-32a81cf307d3.PNG)

**Comment by stevepentland** [comment]
Hi @Slawson91gd can you please provide the method you used to open the file in Visual Studio? Was it from the command prompt, or did you open VS first and navigate to find the file via the open dialog?

**Comment by karelz** [comment]
No response, not actionable.
BTWL Nothing should be created in system32, unless you ran cmd there when running dotnet.
