### ISSUE TITLE
downloading .net core

### ISSUE THREAD

**Issue by moadij** [dotnet/core#2660]
When I opened a new terminal and entered "~$ botnet" I got this response:

```
Moas-Air:~ moastigsson$ ~$dotnet
-bash: ~: command not found
Moas-Air:~ moastigsson$ 
```

**Comment by dagood** [comment]
`~$` is not part of the command, you only need to type `dotnet`. `~$` is just a common shell prompt shown as a way to indicate the command should be run in a terminal.
