### ISSUE TITLE
lqtDemo

### ISSUE THREAD

**Issue by linqitai** [dotnet/core#2661]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by linqitai** [comment]
lqtdemo

**Comment by karelz** [comment]
Unclear what kind of problem you are hitting. Closing.
Feel free to reopen with additional info. Thanks!
