### ISSUE TITLE
Index.cshtml

### ISSUE THREAD

**Issue by lcp3npedusg** [dotnet/core#2662]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
\myWebApp.csproj]
Pages\Index.cshtml.cs(8,13): error CS1002: ; expected [C:\Users\lcp3n\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,20): error CS1002: ; expected [C:\Users\lcp3n\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,20): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\lcp3n\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,27): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\lcp3n\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,44): error CS1031: Type expected [C:\Users\lcp3n\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,44): error CS1003: Syntax error, ',' expected [C:\Users\lcp3n\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,45): error CS1003: Syntax error, ',' expected [C:\Users\lcp3n\myWebApp\myWebApp.csproj]

The build failed. Please fix the build errors and run again.

**Comment by arphox** [comment]
Please fix your title to be more detailed, "Index.cshtml" is not the title anyone wants to see.
To address your problem, you probably inserted code to the wrong place.
Please show us a screenshot of your IDE, or copy-paste your full code so we can help.

**Comment by karelz** [comment]
No info for more than a week. Closing.
