### ISSUE TITLE
.Net Standard class library not loading NuGet packages referenced

### ISSUE THREAD

**Issue by abhinayrg** [dotnet/core#2663]
# Issue Title
.Net Standard class library not loading NuGet packages referenced and getting file not found exception when .Net Standard dll is referenced in .Net Core projects.

# General
I have a class library created on .Net Standard. When I try to reference .Net standard dlls in .Net Core and try to execute the project, the NuGet packages referenced in .Net standard are not getting loaded and getting FileNotFoundException. If I have .Net Standard and .Net Core projects in the same solution and add the .Net standard as a project reference to .Net core then the NuGet packages are getting loaded. Apparently I don't want to include .Net standard and .Net Core in the same solution, since .Net standard is being referenced in some other projects as well. What is the fix for this solution?

**Comment by AlseinX** [comment]
You need to pack your .net standard library as a nuget package and upload it into a nuget repository, which could be based on a file system if you want to use it on the local machine or host a nuget server for cooperation.

**Comment by karelz** [comment]
Answered above - thank you @AlseinX!
