### ISSUE TITLE
Update .NET Core hosting bundle requires IIS restart?

### ISSUE THREAD

**Issue by mferraricloudsurfers** [dotnet/core#2668]
# Issue Title

Update .NET Core hosting bundle requires IIS restart?

# General

I have a Windows Server 2016 with .NET Core 2.1 hosting bundle installed to host a web application on IIS. 
I want to update the hosting bundle from version 2.1 to 2.2. What I need to understand is if the update requires an IIS restart like the first installation, or is not necessary for updating?

**Comment by Pilchie** [comment]
@joeloff do you know the answer to this one?

**Comment by joeloff** [comment]
ACNM would remove and install a new copy of the ASP.NET Core Module into IIS along with schema updates. If the module is in use I'd expect that some app pools would need to restart at a minimum. And ANCM would actully stop and start some services during the upgrade as well.

@jkotalik is this correct?

**Comment by jkotalik** [comment]
The ANCM installers will start/stop some services, but it won't restart larger windows services like WAS. From my experience though, after the first installation, you usually don't need to restart IIS.

**Comment by Pilchie** [comment]
I think this is answered - let us know if you have further questions.

**Comment by hintbw** [comment]
Maybe this shouldn't be reopened, but I wanted to share my experience with our apps which install hosting bundles from 2.2.x as we deploy them and all run on a shared web server. We regularly see web server reboots occurs (which is frustrating and disruptive to other services running on that same server) when a new hosting bundle is installed. We haven't yet been able to understand exactly why however.

**Comment by joeloff** [comment]
@hintbw do you have any logs from installs where a restart occurred? Although we don't explicitly restart anything, the individual MSIs might. That decision ultimately rests with the Restart Manager service in the OS. If a reboot is needed, MSIs and the hosting bundle will likely return 3010. If something is returning 1641 then that would indicate that the reboot was started.

**Comment by hintbw** [comment]
@joeloff - I do have log from several of the incidents (including one that happened today). We are moving towards being able to push our applications in a more CD type of way, but if one of them upgrades the .net core bundle we are using and that has to get installed, causing a reboot and disruption to other services, that is obviously a problem.

What might be the best way to private share those logs?

Also, as we evaluate this issue we are considering whether (using this url https://docs.microsoft.com/en-us/dotnet/core/deploying/) a Self-contained deployment gets around this potential restart problem for us or is there a way to install the hosting bundle and force a deferment of the restart.

**Comment by joeloff** [comment]
@hintbw Let me think about the logs. Meanwhile, you can try running the bundle from the commandline with /norestart and see whether that makes a difference.
