### ISSUE TITLE
unable to restore from command line/scripts

### ISSUE THREAD

**Issue by af4jm** [dotnet/core#2675]
# Issue Title

unable to restore from command line/scripts

# actual

(from either PowerShell or cmd)

```
C:\src\MyApp> dotnet restore --configfile "NuGet.config" --interactive
C:\Program Files\dotnet\sdk\2.2.203\NuGet.targets(119,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/af4jm/_packaging/af4jm/nuget/v3/index.json. [C:\src\MyApp\MySln.sln]
C:\Program Files\dotnet\sdk\2.2.203\NuGet.targets(119,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\src\MyApp\MySln.sln]
```

*dotnet build* results in the same error, thus rendering build scripts useless

# expected
either it just works (with cached credentials), or it gives me a URL to authenticate

**Comment by karelz** [comment]
What do you need credentials for? Some proxy?
@dagood any thoughts?

**Comment by dagood** [comment]
Sounds like a question for NuGet folks. The content of the NuGet.Config, output of `dotnet --info`, and version of NuGet being used seem to me the necessary first steps to figure it out.

**Comment by karelz** [comment]
@rrelyea can you help to route it please?

**Comment by rrelyea** [comment]
To support authenticated feeds via dotnet restore or msbuild /restore use 2.1.500 or 2.2.100 sdks (or later) 
Then use this project
https://github.com/Microsoft/artifacts-credprovider

Some related docs:
 (https://docs.microsoft.com/en-us/Nuget/reference/extensibility/nuget-cross-platform-authentication-plugin)

Cc @alexmullans

**Comment by karelz** [comment]
Looks like answered, closing.
Please let me know if I missed anything.
