### ISSUE TITLE
Windows SDK installer is not accessible in High Contrast mode

### ISSUE THREAD

**Issue by jtippet** [dotnet/core#2677]
dotnet = Version 2.2.203 for Windows.
OS = build 18892, high contrast mode = enabled, theme = "High Contrast Black"

See screenshot.  There are, I think, some checkboxes, but their captions are white text on a white background.  This makes it unreadable.

When the OS is in high contrast mode, you should either:
* Use the OS theme colors for *every* UI element's foreground and background; or
* Hardcode *all* your colors.

This sort of bug occurs when you honor the OS theme color for some things (in this case, text foreground color), but hardcode other things (text background color).

![image](https://user-images.githubusercontent.com/10259764/57184417-032a3100-6e70-11e9-8b1b-eaf5e16d8e6b.png)

**Comment by dagood** [comment]
Issue moved to [dotnet/core-sdk #1885](https://github.com/dotnet/core-sdk/issues/1885) via [**ZenHub**](https://www.zenhub.com/)
