### ISSUE TITLE
domain work

### ISSUE THREAD

**Issue by jomarca24** [dotnet/core#2680]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by stevepentland** [comment]
HI @jomarca24, can you please elaborate on the issue you encountered on the linked page?

**Comment by karelz** [comment]
No response, not actionable.

Thanks @stevepentland for helping us push on bug reports!
