### ISSUE TITLE
Resource Unavailable - https://packages.microsoft.com

### ISSUE THREAD

**Issue by titan550** [dotnet/core#2682]
I cannot access the Microsoft repository for Ubuntu at https://packages.microsoft.com. I get connection failure errors. I could successfully access it when I last tried on 4/28.

Error:

```
Err:19 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 40.76.35.62 443]
Fetched 16.1 MB in 30s (535 kB/s)
Reading package lists...
W: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/InRelease  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 40.76.35.62 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
@dagood @leecow is it already addressed?

**Comment by leecow** [comment]
Yes, I'm not seeing any issues with the repo. @titan550 , let us know if you're still having the issue.

**Comment by kimbaudi** [comment]
Hi, I'm also facing this issue when updating Ubuntu 18.04 with using `sudo apt upgrade -y`. I opened a new issue [3010](https://github.com/dotnet/core/issues/3010).
