### ISSUE TITLE
linux-prereqs.md is missing Ubuntu 19.04 requirements

### ISSUE THREAD

**Issue by dagood** [dotnet/core#2687]
https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md doesn't have Ubuntu 19.04 requirements listed. It also doesn't have a column for 2.2, and has a column for the now-EOL 2.0.

@leecow Is this table out of date, or is there a better place to get this information?

**Comment by leecow** [comment]
This is the right place - will update the doc today.

**Comment by leecow** [comment]
https://github.com/dotnet/core/commit/3cc9101c053a9ab319c6de5182a8448432f391ce

**Comment by stevepentland** [comment]
@leecow I notice that the requirements of `libssl` and `openssl` frequently alternate. Is there a reason for this? I've noted that openssl1.1 on 19.04 works with prebuilt binaries, and I do not have libssl-dev itself installed

**Comment by leecow** [comment]
Unfortunately, I don't know the details. @bartonjs?
