### ISSUE TITLE
COMMAND NOT FOUND

### ISSUE THREAD

**Issue by lusayosayo** [dotnet/core#2692]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.10 - x64

When I try to execute 'dotnet' on the terminal, it returns: 
```
Command 'dotnet' not found, but can be installed with:

sudo snap install dotnet-sdk
```
But, I've already installed it, and the problem is that in the /snap/bin/ folder, the binary installed is dotnet-sdk.dotnet instead of just dotnet.

Can I just rename this?

**Comment by dagood** [comment]
This is normal for snaps, see https://github.com/dotnet/core/blob/8ff6a63bfe67b522714386ef2a48a2a6da88414b/release-notes/2.2/2.2.4/2.2.4-download.md#install-using-snap for more info.

To make it so you can just type `dotnet`, you can run:

```
sudo snap alias dotnet-sdk.dotnet dotnet
```
