### ISSUE TITLE
Container restarts with exit code 137 when running .net core webapi on Linux Kubernetes Cluster

### ISSUE THREAD

**Issue by evhfla** [dotnet/core#2696]
# Container restarts with exit code 137 when running asp.net core webapi on Kubernetes

# General

Hi all, I have several microservices running on a Linux Kubernetes Cluster in Azure.  Half of my services are .net core grpc services and the other half are asp.net webapi services.  The issue is that whereas the gRPC never restarts, the asp.net core webapi eventually always get killed by Kubernetes with exit code 137 and restarted because of High Memory Usage.  I am setting my memory request for my containers at 500 Mb, and memory limits at 1 GB.  From looking around the web, it seems that my issue might be related to the processor count that asp.net core is detecting since those containers are running on nodes with 8 Processors.  However, from what I am reading, the problem with not respecting the kubernetes/docker limits should have been fixed in .net core 2.0.  All my services are running .net core 2.2.3 and using kestrel.

Also, setting servergarbagecollection to false as someone else recommended in another thread, still resulted in container restarts, but this time with exit code 255.

P.S. My Kubernetes cluster nodes are running Ubuntu 16.04.5 LTS.

Any help in this matter would be greatly appreciated.

**Comment by karelz** [comment]
Do you see similar memory usage outside of Kubernetes? Did you try to track down what consumes the memory?

**Comment by Pilchie** [comment]
Closing due to lack of response.
