### ISSUE TITLE
Handle leak  in WCF communication

### ISSUE THREAD

**Issue by aruntmenons** [dotnet/core#2697]
Issue: Handle leak observed in WCF communication

In my C++ application, I have added CLR support((/clr) to use WCF communication.

Everything is working well, but i observed handle leak. When I analyze this with WinDbg(!htrace). Its shows handle leaks in .NET libs as shown below.

Handle = 0x0000000000003300 - OPEN
Thread ID = 0x0000000000004dbc, Process ID = 0x000000000000414c

0x000000007785a30a: ntdll!ZwCreateThreadEx+0x000000000000000a
0x000007fefd37ac73: KERNELBASE!CreateRemoteThreadEx+0x0000000000000163
0x00000000776e57a6: KERNEL32!CreateThread+0x0000000000000036
0x000007fedaf3f0aa: clr!ClrCreateManagedInstance+0x000000000001ae0a
0x000007fedaf3efb8: clr!ClrCreateManagedInstance+0x000000000001ad18
0x000007fedaf3f5e3: clr!ClrCreateManagedInstance+0x000000000001b343
0x000007fedaf3f623: clr!ClrCreateManagedInstance+0x000000000001b383
0x000007fedaeb3b5e: clr!PreBindAssemblyEx+0x0000000000007e5e
0x000007fedae0a05f: clr!LogHelp_LogAssert+0x000000000000525f
0x000007fedae0837c: clr!LogHelp_LogAssert+0x000000000000357c
0x000007fedae08125: clr!LogHelp_LogAssert+0x0000000000003325
Handle = 0x00000000000032fc - OPEN
Thread ID = 0x0000000000004dbc, Process ID = 0x000000000000414c

0x0000000077859d0a: ntdll!ZwCreateEvent+0x000000000000000a
0x000007fefd372d15: KERNELBASE!CreateEventExW+0x0000000000000065
0x000007fedaf3db8a: clr!ClrCreateManagedInstance+0x00000000000198ea
0x000007fedaf3dd27: clr!ClrCreateManagedInstance+0x0000000000019a87
0x000007fedaf3f077: clr!ClrCreateManagedInstance+0x000000000001add7
0x000007fedaf3efb8: clr!ClrCreateManagedInstance+0x000000000001ad18
0x000007fedaf3f5e3: clr!ClrCreateManagedInstance+0x000000000001b343
0x000007fedaf3f623: clr!ClrCreateManagedInstance+0x000000000001b383
0x000007fedaeb3b5e: clr!PreBindAssemblyEx+0x0000000000007e5e
0x000007fedae0a05f: clr!LogHelp_LogAssert+0x000000000000525f
0x000007fedae0837c: clr!LogHelp_LogAssert+0x000000000000357c
0x000007fedae08125: clr!LogHelp_LogAssert+0x0000000000003325
0x000007fedaeb5abf: clr!PreBindAssemblyEx+0x0000000000009dbf
0x00000000776e571d: KERNEL32!BaseThreadInitThunk+0x000000000000000d
Handle = 0x00000000000032f8 - OPEN
Thread ID = 0x0000000000004dbc, Process ID = 0x000000000000414c

0x0000000077859d0a: ntdll!ZwCreateEvent+0x000000000000000az
0x000007fefd372d15: KERNELBASE!CreateEventExW+0x0000000000000065
0x000007fedaf3db8a: clr!ClrCreateManagedInstance+0x00000000000198ea
0x000007fedaf3dd19: clr!ClrCreateManagedInstance+0x0000000000019a79
0x000007fedaf3f077: clr!ClrCreateManagedInstance+0x000000000001add7
0x000007fedaf3efb8: clr!ClrCreateManagedInstance+0x000000000001ad18
0x000007fedaf3f5e3: clr!ClrCreateManagedInstance+0x000000000001b343
0x000007fedaf3f623: clr!ClrCreateManagedInstance+0x000000000001b383
0x000007fedaeb3b5e: clr!PreBindAssemblyEx+0x0000000000007e5e
0x000007fedae0a05f: clr!LogHelp_LogAssert+0x000000000000525f
0x000007fedae0837c: clr!LogHelp_LogAssert+0x000000000000357c
0x000007fedae08125: clr!LogHelp_LogAssert+0x0000000000003325
0x000007fedaeb5abf: clr!PreBindAssemblyEx+0x0000000000009dbf
0x00000000776e571d: KERNEL32!BaseThreadInitThunk+0x000000000000000d

Am using VS 2015 , .NET version is 4.5.2 and Windows 7

Regards,
Arun Menon

**Comment by karelz** [comment]
You're having problem with .NET Framework, not .NET Core. Please use Microsoft support channel, or VS Feedback - that's where we track .NET Framework issues. Thanks!
