### ISSUE TITLE
.NET core version correlation for coreclr and corefx 

### ISSUE THREAD

**Issue by bsagal** [dotnet/core#270]
How can I find out which version of  coreclr and corefx are used in a .NET core release?

I need to rebuild the native parts of  coreclr and corefx but i am not sure which release of these package are used to make  .NET core  1.0.1

**Comment by svick** [comment]
This information is in the Releases tab of each project, which then links you to a git tag:

* [The summary is in this repository](https://github.com/dotnet/core/releases/tag/1.0.1)
* [The version of coreclr used is .Net Core 1.0.1 is 1.0.4](https://github.com/dotnet/coreclr/releases/tag/v1.0.4)
* corefx didn't seem to change in .Net Core 1.0.1, so [version 1.0.0 is the one you want](https://github.com/dotnet/corefx/releases/tag/v1.0.0)

**Comment by bsagal** [comment]
thanks
