### ISSUE TITLE
How to retrieve ReleaseVersion property at runtime?

### ISSUE THREAD

**Issue by cspital** [dotnet/core#2700]
My solution has 4 projects, that I'd like to lock to the same version. I've configured those projects to 'Get version from parent solution'. Doing so creates a ReleaseVersion property in those csproj files.

INFO:
.NET Core Version: 2.2.106
OS: macOS Mojave 10.14.4
Visual Studio for Mac: 8.0.5

PROBLEM:
In the API project, my entry assembly, I'd like to retrieve that ReleaseVersion number without manually keeping the projects in sync with the Version property.

There is no Version element in the csproj file. The ReleaseVersion element is set to `3.0.1`.
```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.1</TargetFramework>
  <TieredCompilation>true</TieredCompilation>
  <ReleaseVersion>3.0.1</ReleaseVersion> <-- what I want
</PropertyGroup>
```

`System.Reflection.Assembly.GetEntryAssembly().GetName().Version` returns `1.0.0.0`.

`Assembly.GetEntryAssembly().CustomAttributes` does not contain any such custom attribute to retrieve the ReleaseVersion property.

I don't disagree with `System.Reflection.Assembly.GetEntryAssembly().GetName().Version` not returning the ReleaseVersion if present and there is no Version attribute, that's unpredictable. But shouldn't either:
- The tooling just sync the Version element directly instead of relying on the ReleaseVersion element?
- There be a way to get the ReleaseVersion value through `GetCustomAttribute<>()`?

There are some questions on StackOverflow that address this, but they do not have working answers where the Solution manages the version number of all contained projects and there is no Version element.
https://stackoverflow.com/questions/52213020/get-asp-net-core-2-mvc-releaseversion
https://stackoverflow.com/questions/37798075/display-project-version-in-asp-net-mvc-core-application-rc2

**Comment by dasMulli** [comment]
The `ReleaseVersion` seems to be specific to an app model, but I don't know which. It is not the one being used by .NET Core / the SDK used for building .NET Core applications.

As has been pointed out in the SO answer already, you should be using either `Version` or `VersionPrefix` (he latter one allows you too specify a suffix during build).

If you want to have multiple projects use the same number, create a [`Directory.Build.props`](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets) file in your solution folder with the following content:
```xml
<Project>
  <PropertyGroup>
    <VersionPrefix>1.2.3</VersionPrefix>
  </PropertyGroup>
</Project>
```

This will be automatically imported into all projects but also allow you two override the value if it is set in the csproj file.

**Comment by cspital** [comment]
@dasMulli thank you for the quick reply.

Should the project versioning also be decoupled from the solution when pursuing the Directory.Build.props strategy? Or does it not matter since ReleaseVersion doesn't make it into the Assembly MetaData anyways?
