### ISSUE TITLE
Unable to locate package dotnet-sharedframework-microsoft.netcore.app-1.0.5 (Debian 9)

### ISSUE THREAD

**Issue by oceaneLonneux** [dotnet/core#2701]
Hello, I am trying to get the packages "dotnet-sharedframework-microsoft.netcore.app-1.0.5" and "dotnet-dev-1.1.0" on my Debian 9 Stretch server but it isn't going that well. I am running these commands:

`sudo apt-get install dotnet-sharedframework-microsoft.netcore.app-1.0.5`
`sudo apt-get install dotnet-dev-1.1.0`

I expected those packages to be downloaded and ready to use, but it returns

`Unable to locate package dotnet-sharedframework-microsoft.netcore.app-1.0.5`
`Couldn't find any package by glob 'dotnet-sharedframework-microsoft.netcore.app-1.0.5'`
`Couldn't find any package by regex 'dotnet-sharedframework-microsoft.netcore.app-1.0.5'`

I have seen on the github issues from almost 2 years ago that it seemed a bit problematic back then, but I would think it is okay now?

I have tried those steps as well (from here https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md) after downloading the Debian8 package.

`sudo mkdir -p /opt/dotnet`
`sudo tar zxf [dotnet-debian-x64.1.1.0-preview1-005051] -C /opt/dotnet`
`sudo ln -s /opt/dotnet/dotnet /usr/local/bin`

But it stops working at the second one, maybe I just don't the correct syntax as I usually use Windows.

Is there another way to do for Debian 9?

Thanks a lot!

**Comment by dagood** [comment]
Why are you trying to install such an old version?

2.2.x is the current recommendation, and if you're just starting off, you'll have a much easier time there. Take a look at https://dotnet.microsoft.com/download if you haven't yet.

---

For your specific issue, it's just a syntax error. 😄

```
sudo mkdir -p /opt/dotnet
sudo tar zxf [tar.gz filename] -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin
```

When you plug in `[tar.gz filename]`, you have to leave out `[` and `]`. You'll find a lot of instructions wrap words in `[]` or `<>` to tell you where you need to supply some input while being clear where the description begins and ends.

But there's also more direct instructions on the download page:
https://dotnet.microsoft.com/download/dotnet-core/1.1

For example, for Ubuntu 16.04 it says this, no replacement required:

```sh
mkdir -p $HOME/dotnet && tar zxf dotnet-dev-ubuntu.16.04-x64.1.1.13.tar.gz -C $HOME/dotnet
export PATH=$PATH:$HOME/dotnet
# Then there's some more notes to set up PATH permanently.
```

(It also installs it locally so you don't need `sudo`.)

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is more info. Thanks!
