### ISSUE TITLE
Add the ability to alias a reference

### ISSUE THREAD

**Issue by hez2010** [dotnet/core#2702]
# The ability to alias a referene
Sometimes if different assemblies use the same namespace, there will be conflict problems. And this problem will be wider and wider with .NET ecosystem growing up. We cannot guarantee that we can access code of all the references, for example some reference are packages so that we cannot modify their source code to resolve the problem. And also if some packages are no longer being maintained, the problem will always exist and cannot be resolved.

For example: 
```bash
dotnet new classlib -f netstandard2.1
dotnet add package SixLabors.ImageSharp --version 1.0.0-beta0006
```

Then you cannot use `Span<T>` because:
```
error CS0433: The type 'Span<T>' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

The same for .net core 3.0 project with language version 8.0 and reference to package Microsoft.EntityFrameCore: in this case you will lose the ability to use `IAsyncEnumerable<T>` for the same reason.

Another scenario:   
Project A reference package X 1.0, while project B reference package X 1.1. But unfortunately package X 1.0 to 1.1 has breaking changes so that Project A must lock at 1.0 and the same for Project B.  
In this case we will never be able to reference A and B in a single project because of incompatible references.

# Solution
Introduce alias for reference, for example:
```xml
<PackageReference Include="xxxxxx" Alias="pkg1" Version="1.0" />
<ProjectReference Include="./MyProject.csproj" Alias="proj1" />
```

Then in code we can use in code:
```csharp
pkg1::xxx.yyyy
proj1::abc.defg
```
which perfectly resolve all the problems above.

**Comment by svick** [comment]
First, that error with `SixLabors.ImageSharp` looks like a bug somewhere to me and something that should be reported.

Second, you already can add an alias to an assembly that is part of a NuGet package: https://github.com/NuGet/Home/issues/4989#issuecomment-310565840. Though you could view that as a hack and so you might want to see a better supported solution.

**Comment by hez2010** [comment]
@svick Thanks for your reply. This is a great solution: https://github.com/NuGet/Home/issues/4989#issuecomment-426666530
I think add the ability to alias reference is important.

**Comment by hez2010** [comment]
In TypeScript we have
```typescript
import * as [alias] from [file/package]
```
and also in python we have
```python
import [package] as [alias]
```

This is necessary for project to avoid name conflicts, in addition, node.js has its method to avoid version conflicts through packages.lock.json.

Therefore, I think .NET Core project need a way to avoid name conflicts and version conflicts. 
For example, use `<XXXReference Include="xxx" Alias="xxx" />` to avoid name conflicts, and use `<XXXReference Include="xxx" Private="true" />` to keep things referenced by xxx private so that its references won't affect its parent project.

**Comment by nkolev92** [comment]
@hez2010 

Regarding the PackageReference aspect, the right issue is the one in the NuGet repo. 

A few notes: 
NuGet already has packages.lock.json support. 
https://blog.nuget.org/20181217/Enable-repeatable-package-restores-using-a-lock-file.html

NuGet packages can have more than 1 assembly reference. Do you want alias all of those?
I believe the design is not as straightforward as adding an alias metadata at the PackageReference level. 

```
<XXXReference Include="xxx" Private="true" />
```

For PackageReference, look into PrivateAssets https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by karelz** [comment]
Seems to be answered, closing.
