### ISSUE TITLE
dotnet restore cannot download Package from case-sensitive nuget mirror

### ISSUE THREAD

**Issue by Parcley** [dotnet/core#2703]
# dotnet restore cannot download Package from case-sensitive nuget mirror

When using `dotnet restore` to resolve NuGet dependencies, NuGet fails when using a nuget registry, which has a case-sensitive API. 

# General

used tools:
- .NET Command Line Tools (2.2.203) on Linux
- Ubuntu 18.04 x86_64
- private NuGet registry hosted on Artifactory 6.6.5

When specifying a dependency, which has a name with UpperCase characters, like this:
`<PackageReference Include="Newtonsoft.Json" Version="[12.0.2]" />`

And specifying an internal Artifactory 6.6.5-based NuGet registry, like this:
```
<packageSources>
  <add key="ArtifactoryNuGetV3" value="https://####.net/api/nuget/v3/####/" protocolVersion="3" />
</packageSources>
``` 

and using `dotnet restore -v n --no-cache` to load NuGet dependencies, we can see in dotnet's cmd line output that dotnet is issuing these HTTP requests to the artifactory server:
```
1>Restore:
         Restoring packages for /home/perzl/git/####.csproj...
           GET https://####.net/api/nuget/v3/####/registration-semver2/newtonsoft.json/index.json

[....]

1>/usr/share/dotnet/sdk/2.2.203/NuGet.targets(119,5): error : The feed 'ArtifactoryNuGetV3 [https://####.net/api/nuget/v3/####/]' lists package 'Newtonsoft.Json.12.0.2' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/home/perzl/git/####.csproj]
/usr/share/dotnet/sdk/2.2.203/NuGet.targets(119,5): error :   Unable to find package 'Newtonsoft.Json.12.0.2'. [/home/perzl/git/####.csproj]
```

Especially have a look at the request URL
`GET https://####.net/api/nuget/v3/####/registration-semver2/newtonsoft.json/index.json`
in which the package name is converted to lower case

In my opinion, I think this is a problem in both tools: dotnet restore and Artifactory NuGet registry. 
- dotnet restore is making requests to the NuGet API with package names converted to lower case (it should not change the case of package names)
- Artifactory should handle requests to its API case-insensitive

Any of these two changes would solve this issue for me, but I think that both should be solved. 

Any feedback is appreciated

**Comment by Parcley** [comment]
This is the corresponding ticket in the JFrog Artifactory ticket system:
https://www.jfrog.com/jira/browse/RTFACT-18567

When using a NuGet API v2, I can resolve my dependencies with dotnet and Artifactory without any problems. 

```
<packageSources>
  <add key="ArtifactoryNuGetV3" value="https://####.net/api/nuget/####/" />
</packageSources>
```

So to make my initial issue more specific: it only affects NuGet protocol version 3

**Comment by karelz** [comment]
@rrelyea can you please help route this issue?

**Comment by joelverhagen** [comment]
Hey @Parcley, thanks for taking the time to report this.

The V3 protocol by design expects the "registration" (package metadata) JSON URLs to contain lowercase IDs. The official protocol is documented to expect `ID_LOWER`:
https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-pages-and-leaves

For a real-life example, nuget.org's V3 expoints expect the ID to be lowercase.
https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.json (200 OK)
https://api.nuget.org/v3/registration3-gz-semver2/Newtonsoft.Json/index.json (400 Not Found)

**Comment by joelverhagen** [comment]
Here's the code in NuGet client that lowercases the ID:
https://github.com/NuGet/NuGet.Client/blob/46afef4bc537ef92559d543e1e013d6f37072812/src/NuGet.Core/NuGet.Protocol/Resources/RegistrationResourceV3.cs#L56-L57

In short, this is by design.

**Comment by Parcley** [comment]
Thank you all for the clarification. 

I have linked this issue in the mentioned JFrog issue.

- `dotnet restore` is working correctly and is NuGet protocol v3 compliant.
- JFrog Artifactory is case-sensitive with regard to IDs and thus not NuGet protocol v3 compliant.
