### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by surajwate** [dotnet/core#2707]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.10 - x64

I have run all the commands given in instruction still the system is showing following error.

@ubuntu:~$ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by AdvancedPowerArmor** [comment]
I don't know what the problem is but can you update the Ubuntu?

**Comment by dagood** [comment]
Can you run these diagnosis steps and share the results?

```sh
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

This normally happens when the repository you're using doesn't match the distro or specific distro release.

**Comment by surajwate** [comment]
Hi @dagood. I have updated the system a few days back. That may be the problem. I am sharing the result of the commands you have given to me. 

suraj@ubuntu:~/Coding/codingit$ grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco main restricted
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-updates main restricted
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco universe
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-updates universe
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco multiverse
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-updates multiverse
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-backports main restricted universe multiverse
/etc/apt/sources.list:deb http://archive.canonical.com/ubuntu disco partner
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-security main restricted
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-security universe
/etc/apt/sources.list:deb http://es-mirrors.evowise.com/ubuntu/ disco-security multiverse
/etc/apt/sources.list.d/google-chrome.list:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.10/prod cosmic main
/etc/apt/sources.list.d/rednotebook-ubuntu-stable-disco.list:deb http://ppa.launchpad.net/rednotebook/stable/ubuntu disco main
suraj@ubuntu:~/Coding/codingit$ cat /etc/os-release
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
suraj@ubuntu:~/Coding/codingit$ sudo apt-get install dotnet-runtime-deps-2.2
[sudo] password for suraj: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libssl1.0.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
suraj@ubuntu:~/Coding/codingit$

**Comment by dagood** [comment]
Thanks @surajwate! That is indeed the problem. You're on Ubuntu 19.04, but have the 18.10 Microsoft repository installed:

```
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64]
  https://packages.microsoft.com/ubuntu/18.10/prod cosmic main
...
VERSION="19.04 (Disco Dingo)"
```

Running the 19.04 instructions should upgrade your Microsoft repository and work:

```
wget -q https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
```

(I filed https://github.com/dotnet/core/issues/2728 to track getting instructions for 19.04 on dot.net.)

The mismatched repository vs. distro causes a problem because some Ubuntu packages are available in 18.10 but not 19.04, and `dotnet-runtime-deps-2.2` has to match. There are plans to make the `dotnet-runtime-deps` packages work across multiple versions but we haven't got that into a 2.1/2.2 release yet. (https://github.com/dotnet/core-setup/issues/5812)

**Comment by surajwate** [comment]
@dagood thanks for the help.

**Comment by Angr1st** [comment]
@dagood  is there an eta when (dotnet/core-setup#5812) will be released?

**Comment by dagood** [comment]
It's merged for the next servicing updates, 2.1.12 (https://github.com/dotnet/core-setup/pull/6246) and 2.2.6 (https://github.com/dotnet/core-setup/pull/6247). The current plan has those releasing in July (although it may change).

**Comment by Angr1st** [comment]
I guess I could just build the dotnetcore-runtime-deps myself If I want
them sooner or would I then have to build everything myself?

Davis Goodin <notifications@github.com> schrieb am Di., 28. Mai 2019, 17:03:

**Comment by dagood** [comment]
Since the `dotnet-runtime-deps` package doesn't contain anything (it's only used for the dependencies it declares), building it yourself should work fine.

Depending on your use case, it might be cleaner to make sure you have the dependencies installed yourself and ignore `dotnet-runtime-deps`. Or, it would arguably be the cleanest to just install from the tarball for now.

**Comment by Angr1st** [comment]
Which tarball so you mean? Could you please elaborate?

Davis Goodin <notifications@github.com> schrieb am Di., 28. Mai 2019, 18:20:

**Comment by dagood** [comment]
On https://dotnet.microsoft.com/download you'll see a table a bit lower on the page--I'm referring to the "Binaries" row. There's some instructions to follow after you click a download link, or you can also take a look at https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md.

You can also check out if [Snaps](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#installation-using-snap) suit you!

**Comment by Angr1st** [comment]
Thanks I will try it. 👍

Davis Goodin <notifications@github.com> schrieb am Di., 28. Mai 2019, 23:27:

**Comment by Angr1st** [comment]
Tried installing dotnet via the tarball and it just worked. Just FYI I am
running PureOS(Debian 10(Testing)based distro). 👌 Thanks for pointing me
in the right direction.

Torben Clasen <torbenclasen@gmail.com> schrieb am Mi., 29. Mai 2019, 08:25:
