### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by jonahjameshills** [dotnet/core#2709]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Says it is not recognized as an internal or external command.

**Comment by AdvancedPowerArmor** [comment]
Can you reinstall .NET Core SDK? It looks like you didn't install it correctly.

**Comment by dagood** [comment]
Another common issue is trying to use an old command prompt that was started before the install completed. A new prompt is required to get the change to `PATH` that includes the `dotnet` install directory.

@jonahjameshills can you make sure you opened a new command prompt?

**Comment by karelz** [comment]
Should be addressed above, closing. Feel free to reopen if it does not help and you need more suggestions. Thanks!
