### ISSUE TITLE
Unable to access microservice hosted using docker image

### ISSUE THREAD

**Issue by chitranjan32** [dotnet/core#2715]
Operating System: windows 10 

I was trying following tutorial from Microsoft Learning centre 
https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/run-docker

while trying to run service using docker image , i gave following command 

![image](https://user-images.githubusercontent.com/27756222/57604036-87825f80-75a6-11e9-9842-34b1bd121980.png)

Even though i can see the message that : "Now listening on .." i am unable to access the service using following URL : 
http://localhost:3000/api/values

I am getting following screen 

![image](https://user-images.githubusercontent.com/27756222/57604201-efd14100-75a6-11e9-8a45-ff1d59053103.png)

I am not sure ..whats the issue .. ?? 
Do i need to check any other url ??

**Comment by karelz** [comment]
Did you check your docker settings, firewalls, etc.

**Comment by Pilchie** [comment]
Closing due to lack of response.  @chitranjan32 This sounds like an issue with your Docker setup.
