### ISSUE TITLE
Build with "Generate serialization assembly: On" throws errors

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/core#2716]
I have a pure C# class library - previously compiled, working and used on .NET Framework 4.8.  I was working on porting this code to .NET Core 3.0. I am using C# 8.0 as the language. I am using Visual Studio 2019 16.1.0 Preview 3.0 as my IDE environment.

When I compile the library project with the **Generate serialization assembly** set to `Auto` or `Off`, the project builds fine. 

However, when I build it with the **Generate serialization assembly** set to `On`, the build fails with two different errors.

**In the Visual Studio Output Window:**
```
SGEN : error : An attempt was made to load an assembly with an incorrect format: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview5-27626-15\ref\netcoreapp3.0\Microsoft.VisualBasic.Core.dll.
```

**Output at end of `dotnet build -v d`:**
```
"[Path to .csproj]" (default target) (2:6) ->
       (GenerateSerializationAssemblies target) ->
         C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Microsoft.Common.CurrentVersion.targets(3541,5): error MSB4062: The "Microsoft.Build.Tasks.SGen" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [[Path to .csproj]]
```

If I reset the flag to `Off` and rebuild, both builds complete correctly.

**Comment by karelz** [comment]
Do you have a minimal repro you could share with us?

**Comment by sujayvsarma** [comment]
@karelz - How do you prefer I share a repro with you?

**Comment by karelz** [comment]
Ideally create steps to repro on new project. Post minimal code here as code block.

**Comment by fenriv** [comment]
I have similar issues. In my case the message is following:

> SGEN : error : An attempt was made to load an assembly with an incorrect format: C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.annotations\4.5.0\ref\netstandard2.0\System.ComponentModel.Annotations.dll.

Environment:
Windows 10 Pro
Visual Studio 2019 (16.1.0)

Project:
SDK -> NETStandard.Library 2.0.3
NuGet -> "System.ComponentModel.Annotations" Version="4.5.0" 

Class:
```csharp
[DataContract]
public class Platform
{
    [DataMember(Name = "platformId")]
    public Guid? PlatformId { get; set; }
}
```

While the "Generate serialization assembly" is set to "on" project build fails with the error message above.
Removal of nuget reference resolves the issue. Usage of annotations is not influencing a build result.

**Comment by sujayvsarma** [comment]
@karelz Here you go (sorry for the delay):

**My environment:**
Windows 10 Pro + Visual Studio 2019 16.2.0 Preview 1.0 (Community Edition)

**Repro steps:**
1. Open Visual Studio
2. Create a new **Class Library** project, select **.NET Core** and **C#** language. Accept all defaults, click on **Create**.
3. Once the project is ready and loaded, you will have `Class1` loaded in your editor.
4. Ensure **Solution Explorer* is opened. Right-click on the `ClassLibrary1` (Project Name), select **Properties**
5. Go directly into the **Build** tab, at the bottom of the screen, for **Generate serialization assembly**, change the selection to **On** (default is `Auto`). 
6. Save the properties and Build the project.

You will see the above error in the output window:
```
1>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>SGEN : error : An attempt was made to load an assembly with an incorrect format: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview5-27626-15\ref\netcoreapp3.0\Microsoft.VisualBasic.Core.dll.
1>Done building project "ClassLibrary1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Now, go back into the project properties (Step 4 & 5 above). This time, select the option `Auto` or `Off` for the **Generate serialization assembly** setting. Build again.

With the setting at `Auto` or `Off`, the build works correctly.

**Comment by shenzhigang** [comment]
I have a same issue.
`
1>SGEN : error : An attempt was made to load an assembly with an incorrect format: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\Microsoft.VisualBasic.Core.dll.
1>Done building project "wyUpdate.NetCore.csproj" -- FAILED.
`

**Comment by ladipro** [comment]
This bug still exists, reproduces in VS 2019 trivially by setting "Generate serialization assembly" to "On" in an empty .NET Core console app.

The problem appears to be in the SGen tool which loads references using `Assembly.LoadFrom`. This doesn't work for .NET Core reference assemblies:

```
Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context.
```

@karelz, this issue should be re-opened. MSBuild can detect this scenario and issue a user-friendly error pointing the developer to Microsoft.XmlSerializer.Generator but it's silly to provide the switch in the project UI in the first place.

Before we get into the workaround territory, do you think that fixing SGen to use the reflection-only load context is realistic?

**Comment by karelz** [comment]
In general, we do not monitor comments on long-closed issues.
This one was closed by the original reporter, unclear why.

Core repo in general is just incoming "I don't know where to file the issue" repo.
SGen is owned by [Serialization area](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md) I believe - @StephenMolloy @HongGit can you comment if it is possible to fix the tool and where to file the issue?
If we need to "just" fix VS UI to disable the option, where would we file that?
Thanks!

**Comment by chucker** [comment]
> MSBuild can detect this scenario and issue a user-friendly error pointing the developer to Microsoft.XmlSerializer.Generator

I tried adding that as a `DotNetCliToolReference` to a project with a WCF client proxy, and it didn't generate a serialization DLL. Was it supposed to?
