### ISSUE TITLE
Local host did not send any data

### ISSUE THREAD

**Issue by tpallone** [dotnet/core#2719]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Check your firewalls and other restrictions. Try it on brand new VM without any antivirus / firewall settings first./
If you still have problems, please create full repro and share it here. Thanks!
