### ISSUE TITLE
Resource file "**/*.resx" cannot be found. Ubuntu 18.04.

### ISSUE THREAD

**Issue by ShawnRG** [dotnet/core#2720]
After cloning the project fresh from my repo and then running it in Rider 2019, everything works fine. After restarting the application my build failes and hits this error.

I am using the latest stable version of the .NET core 2.1 SDK

`  Microsoft.Common.CurrentVersion.targets(3054, 5): [MSB3552] /usr/share/dotnet/sdk/2.1.603/Microsoft.Common.CurrentVersion.targets(3054,5): error MSB3552: Resource file "**/*.resx" cannot be found.`

**Comment by karelz** [comment]
Which project did you clone? Does it happen for HelloWorld? Are you able to create minimal repro?
Did you check if there are any resx files in your project?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is actionable info available. Thanks!

**Comment by CodeSwimBikeRunner** [comment]
using the latest .net core 3.0 preview sdk. ran dotnet new console in a folder `console`
Here is the `.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

</Project>
```
This is the windows version btw. I run the command.
`dotnet publish -o output -c Release -r win10-x86 --self-contained`
This works, I get hello world.
So I would guess the windows version of the sdk is fine. 

Here is the dockerfile, attempting to build the linux executable.
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine as builder

COPY . .

RUN dotnet publish -o output -c Release -r linux-x64 --self-contained

FROM scratch

COPY --from=builder ./output ./run
WORKDIR /run
RUN chmod +x ./console
ENTRYPOINT [ "./console" ]
```

I get the same error the OP is saying and i get it on the `dotnet publish` step of the docker build.

**Comment by GmeduoyeClaymore** [comment]
Seems like MSBuild barfs if it finds a .resx file with a path longer than a certain character limit (in any subfolder of your project)
IF you are using npm to install any dependencies there is probably something in there. Try deleting your node_modules folders or placing your project at a shorter path. Seems like it's a known issue.

https://github.com/dotnet/cli/issues/6561
