### ISSUE TITLE
Asp.net microservice issue with docker file

### ISSUE THREAD

**Issue by inabeel** [dotnet/core#2722]
![SolarEdge issue](https://user-images.githubusercontent.com/620829/57664264-e7adeb80-7610-11e9-8415-e511b5aa9b62.png)
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-file
Operating System: windows 10.

I am running Docker to create Micro service and following tutorial as it is. But after running command: docker build -t solaredgeservice .
results are available in screen shot. it crashes on step 5

**Comment by stevepentland** [comment]
Hi @inabeel is the `SolarEdgeAPI.csproj` in the `C:\Code\Alexander\solaredgeapi` directory? Also I noted that you are on windows and that your directory name is `solaredgeapi` are the casings in your `Dockerfile` an exact match to those on your local file system? The build context is Linux which is a case-sensitive.

**Comment by stevepentland** [comment]
As a follow up, here is an example I tried to check the contents of the Dockerfile on the site.

My working directory:
![image](https://user-images.githubusercontent.com/8147610/57808882-63538980-7732-11e9-894e-8eb6f94e8878.png)

The contents of `Dockerfile`:
![image](https://user-images.githubusercontent.com/8147610/57809358-479cb300-7733-11e9-9533-bd0bc4f07eff.png)

And the results of `docker build -t solaredgeservice .`:
![image](https://user-images.githubusercontent.com/8147610/57809509-96e2e380-7733-11e9-867d-ede73271f661.png)

My guess would be either of the two options that I listed in https://github.com/dotnet/core/issues/2722#issuecomment-492819071 that a casing is not exactly the same between the `Dockerfile` and your build context directory, or that you may be in an incorrect context

**Comment by Pilchie** [comment]
Closing due to lack of response. @inabeel Please let us know if you have more details here.
