### ISSUE TITLE
Run dotnet new --help for usage information. See https://aka.ms/dotnet-install-templates to learn how to install additional template packs.

### ISSUE THREAD

**Issue by n1schith** [dotnet/core#2723]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by stevepentland** [comment]
Hi @n1schith can you please provide some more details about the problem you encountered?

**Comment by karelz** [comment]
Unclear what is the problem, closing. Feel free to reopen if there is more info/details. Thanks!
