### ISSUE TITLE
.NET Core May Update - 1.0.16, 1.1.13, 2.1.11 and 2.2.5

### ISSUE THREAD

**Issue by leecow** [dotnet/core#2727]
Included fixes address security issues detailed in the release notes.

## .NET Core

* **.NET Core 1.0.16 and .NET Core SDK 1.1.14**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.16/1.0.16.md)
  [Download 1.0](https://dotnet.microsoft.com/download/dotnet-core/1.0)

* **.NET Core 1.1.13 and .NET Core SDK 1.1.14**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.13/1.1.13.md)
  [Download 1.1](https://dotnet.microsoft.com/download/dotnet-core/1.1)

* **.NET Core 2.1.11 and .NET Core SDK**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.11/2.1.11.md)
  [Download 2.1](https://dotnet.microsoft.com/download/dotnet-core/2.1)

* **.NET Core 2.2.5 and .NET Core SDK**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.5/2.2.5.md)
  [Download 2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2)

Please report any issues you find with these releases, either responding to this issue, creating a new issue here or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

## .NET Support Policies

Microsoft support policies are defined in the following documents:

* [Microsoft .NET Support Policy](https://www.microsoft.com/net/support/policy)
* [.NET Core OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md)

**Comment by vivmishra** [comment]
Replaced by #3007
