### ISSUE TITLE
Package repository based install pages need Ubuntu 19.04 entries

### ISSUE THREAD

**Issue by dagood** [dotnet/core#2728]
.NET Core has packages available for Ubuntu 19.04 as of 2.1.11 and 2.2.5, just released today. 🎉 However, the dropdown in the docs needs to be updated (SDK and Runtime):

https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current

The "Ubuntu 19.04 - x64" page should be identical to the 18.10 page, but:

```diff
-wget -q https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb
+wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
```

/cc @rowanmiller @leecow

**Comment by leecow** [comment]
I have submitted a pr for the site repo to make this update.

**Comment by dagood** [comment]
@leecow any idea how long it'll take to get it merged/deployed? Do you mind reopening the issue to track it?

**Comment by dagood** [comment]
As a historical note, on ~May 20th we got 19.04 instructions available:
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
