### ISSUE TITLE
Running Net core 2.0 and .Net Core 2.2  on the same machine

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/core#2729]
# Issue Title

Can I run .Net core 2.0 and .Net Core 2.2  on the same machine ? I will install 2.2.5 hosting bundle for runtime and have already .Net core 2.0 runtime running to support other apis which we dont want to upgrade.  so we need both runtimes to coexist on the same machine. is this possible?

**Comment by leecow** [comment]
@arunprasathv - yes, no worries. The runtimes will live side-by-side in the dotnet/shared/Microsoft.NETCore.App/[version number] directory after installation and the runtime version dependency set in the application's csproj file. See details in the [Target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) document.

**Comment by arunprasathv** [comment]
Thanks @leecow
