### ISSUE TITLE
enable .NET NATIVE tool chain Issue

### ISSUE THREAD

**Issue by YingjieT** [dotnet/core#273]
Hello All,

We are working on the migration windows phone 8.1 project to UWP project under VS2015 update 3.
We are facing some unknown issue when we enable .net native tool chain for C# application.

Our C# project is calling WRT component written in C++/CX, in C++/CX, there is a function as below :

```
bool NameSpace::test(IVector<IVector<int>^>^ rtVector) {
    Vector<int>^  each = ref new Vector<int>();
    each->Append(1);
    each->Append(2);
    each->Append(3);

    rtVector->Append(each);  --> Exception throw if enable .net native tool chain
    return true;

}

```

In C# project, to call this function: 

```
  List<IList<int>> d = new List<IList<int>>();
  bool  b = obj.test(d);
```

I steped in append function, the exception was thrown by below: 
`
System.Runtime.InteropServices.SharedCcw_IVector.Append(System.IntPtr, System.IntPtr)`

The exception ONLY happened when we enable .net tool chain in C# project.
If we disable this option, it works fine.

Thanks for your help.
Best Regards,
Yingjie

**Comment by Petermarcu** [comment]
@yizhang82 , Any ideas? Where is the best place for people to file issues and questions around UWP apps?

**Comment by yizhang82** [comment]
This looks like a bug to me. @luqunl Can you take a look?
@Petermarcu Right now the best way is to mail your question/issue to dotnetnative@microsoft.com

**Comment by Petermarcu** [comment]
Thanks. I'm going to close this issue here. @YingjieT, Thanks for reporting the issue and if there are more follow ups, go ahead and send mail to dotnetnative@microsoft.com. @luqunl, can you make sure you are tracking this in your issue lists.
