### ISSUE TITLE
Cannot load dot prefixed files using FileProvider

### ISSUE THREAD

**Issue by rsouthgate** [dotnet/core#2733]
Specifically reproducible if trying to use a rewriter with an mvc app... Take the following line:

`app.useRewrite(new Rewriteoptions().AddApacheModRewrite(env.ContentRootFileProvider, ".htaccess"));`

Fails with a CLR/System.IO.FileNotFoundException, yet file exists.

To check - copy file and call it tmp.htaccess and change line to 

`app.useRewrite(new Rewriteoptions().AddApacheModRewrite(env.ContentRootFileProvider, "tmp.htaccess"));`

Results in no exception thrown.

dotnet core 2.1
Mac OS Mojave 10.14.4

Given the exception is CLR/System.IO.FileNotFOundException I wonder if this issue should reside in coreclr - but I'll start here until someone tells me otherwise!

**Comment by karelz** [comment]
Can you please post a minimal repro demonstrating the problem?

**Comment by anurse** [comment]
This is probably an issue for FileProviders (which are in Extensions). I'll move this issue and we'll investigate further there.

**Comment by anurse** [comment]
This issue was moved to aspnet/Extensions#1729
