### ISSUE TITLE
arm64 runtime hang on unhandled exception

### ISSUE THREAD

**Issue by spencercw** [dotnet/core#2734]
.NET Core version: 2.2.5 (official arm64 build downloaded from the Microsoft website)
Operating system: Yocto Linux 2.6.1

.NET Core 3.0.100-preview5-011568 is not affected by this issue.

On my Linux x64 dev machine, if my application encounters an unhandled exception, it prints a message that looks like this and exits:
```
Unhandled Exception: [trim]
Aborted (core dumped)
```

But when I run it on my arm64 board, an unhandled exception causes the runtime to hang. It does not print anything to the console, and it puts 100% load on one CPU core.

I'm guessing there's probably something wrong with my environment which is somehow causing the runtime to get into an infinite loop. Any thoughts on what might be causing this?

**Comment by karelz** [comment]
BTW: Yocto is not officially supported distro

@wfurt any idea?

**Comment by wfurt** [comment]
ARM64 was never supported with 2.2 https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md

Fact, that we start making builds back than, does not change that. Yocto is not on supported list so we do not run tests on it. But it should work as long as you have proper dependencies.

**Comment by spencercw** [comment]
Ok, understood. It might be worth a mention on the download page, since it's not apparent there that arm64 is an unsupported platform.

**Comment by wfurt** [comment]
note that debugging with visual studio should be ready soon. For now, lldb + sosplugin is only available option.
