### ISSUE TITLE
Stream is not a valid resource file

### ISSUE THREAD

**Issue by balukantu** [dotnet/core#2735]
I am uploading a file to Api and trying to read the resource key and values. I am getting below exception when I try to read the file.

`System.ArgumentException: Stream is not a valid resource file.
at System.Resources.ResourceReader._ReadResources()
at System.Resources.ResourceReader.ReadResources()
at System.Resources.ResourceReader..ctor(String fileName)`

Below is the code which I tried.

```c#
    [HttpPost]
    public async Task<ActionResult> Post(IFormFileCollection files)
    {
        try
        {
            files = this.Request.Form.Files;
            var tempFolder = Path.GetTempPath();

            foreach (var formFile in files)
            {
                string fileName = ContentDispositionHeaderValue.Parse(formFile.ContentDisposition).FileName.Trim('"');
                string filePath = Path.Combine(tempFolder, fileName);

                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream).ConfigureAwait(false);
                    }

                    var resReader = new ResourceReader(@filePath); // Throwing an exception.
                }
            }
        }
        catch (Exception ex)
        {
            throw;
        }

        return this.Ok("Success.");
    }
```

Below is the request Uri and file

![image](https://user-images.githubusercontent.com/18113877/57844701-395f9d00-77ee-11e9-925b-daed89226ead.png)

Am I missing any configuration?

**Comment by karelz** [comment]
Are you able to open the same file locally on disk? (aka remote the HTTP server part from your repro)
Are you able to send regular TXT file correctly this way?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is actionable info available. Thanks!
