### ISSUE TITLE
 DateTime command running issue

### ISSUE THREAD

**Issue by KamalSaeidi** [dotnet/core#2736]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The following error encountered when running command:

```
> Console.WriteLine("The current time is " + DateTime.Now);
At line:1 char:43
+ Console.WriteLine("The current time is " + DateTime.Now);
+                                           ~
You must provide a value expression following the '+' operator.
At line:1 char:44
+ Console.WriteLine("The current time is " + DateTime.Now);
+                                            ~~~~~~~~~~~~
Unexpected token 'DateTime.Now' in expression or statement.
At line:1 char:43
+ Console.WriteLine("The current time is " + DateTime.Now);
+                                           ~
Missing closing ')' in expression.
At line:1 char:56
+ Console.WriteLine("The current time is " + DateTime.Now);
+                                                        ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression
```

**Comment by karelz** [comment]
This is super weird. Are you able to reproduce it on clean VM/another machine?
It looks like something is hijacking the C# compiler, or bits on disk are horribly corrupt ...

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is actionable info available. Thanks!
