### ISSUE TITLE
dotnet publish on a project fails due to "Access to the path denied"

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#2737]
# Issue Title

dotnet publish on a project fails due to "Access to the path denied".

# General

I am publishing without Visual Studio running (to make sure that it was not a Visual Studio issue).

When I publish with dotnet publish -c Release -r linux-arm

I receive the error:

error MSB3021: Unable to copy file "obj\Release\netcoreapp2.1\MyUtilities.pdb" to "bin\Release\netcoreapp2.1\MyUtilities.pdb". Access to the path 'C:\Dev\...\MyUtilities\bin\Release\netcoreapp2.1\MyUtilities.pdb' is denied.

This happens multiple times a day and in different files.

A check on locked files show no lock on the file above indicating that it is some internal process to the dotnet publish task.

Using verbosity diagnostic shows the same error with no additional detail.

**Comment by genifycom** [comment]
I can also delete the Release directory completely (indicated no locked files) and the dotnet publish still produces the "Access to the path denied"

**Comment by genifycom** [comment]
Process monitor shows that the locking process is C:\Program Files\dotnet\dotnet.exe
Command Line is
"C:\Program Files\dotnet\dotnet.exe" "C:\Program Files\dotnet\sdk\2.2.105\MSBuild.dll" C:\Program Files\dotnet\sdk\2.2.105\MSBuild.dll /nologo /nodemode:1 /nodeReuse:true

The event is a CreateFile, Result: ACCESS DENIED
Desired Access: Generic Read/Write, Delete, Write DAC

**Comment by karelz** [comment]
This is usually caused by background processes running on the machine, like antivirus, file monitoring, etc.
Use tools like ProcessExplorer to see who is touching the file and keeping it in weird state. Or just exclude your output directories from antiviruses, etc.

**Comment by LukasChristel** [comment]
I ran into the same problem where publishing multiple projects into the same output folder caused 
```sh
C:\Program Files\dotnet\sdk\10.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(372,5): error MSB3021: Unable to copy file "<source\myproject.dll>" to "<destination\myproject.dll>". Access to the path '<destination\myproject.dll>' is denied.
```
disabling `BuildInParallel` works around the issue and is not even that much slower when using `--no-build`.
`dotnet publish ______ --output <destination> --no-build --no-self-contained -p:BuildInParallel=false`
