### ISSUE TITLE
Using .NET Core SDK without installing it on dev machines or servers

### ISSUE THREAD

**Issue by abhiphirke** [dotnet/core#274]
Hello,

I want to **_use .Net Core SDK and all other libraries for enterprise application without running the installer but by copying required files and pointing to them from my VSCODE environment_**. This will greatly simplify setting up my dev environment (which will be a big convenience in my project's case and probably for many other enterprise application builders). My development is all done on Windows OS.
Is there a way I can achieve this?

**Comment by livarcocc** [comment]
You can download the SDK binaries directly: https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-dev-win-x86.latest.zip

This is a link to our latest preview2.

**Comment by abhiphirke** [comment]
Thanks, Livar!
