### ISSUE TITLE
the sdk downloaded will not run on my windows 10

### ISSUE THREAD

**Issue by jimmiefingerz** [dotnet/core#2740]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Do you have latest Win10 version? Or at least the minimal supported? (whichever the version is)
Try to download again to make sure it is not corrupted download ...
If that fails, try it on brand new VM/machine to see if it is some weird machine problem. Feel free to reopen if you have more info ...
