### ISSUE TITLE
无法定位软件包 dotnet-sdk-2.1.200

### ISSUE THREAD

**Issue by zgpmc** [dotnet/core#2741]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-2.1.200
Operating System: Linux Ubuntu 16.04  -  x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
This version don't exists. You can use the [SDK 2.1.604](https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-2.1.604) or migrate to the [current 2.2 version](https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-2.2.204).

**Comment by karelz** [comment]
Thanks @igoventura for your answer. Closing.
@zgpmc feel free to reopen if there is more information available. Thanks!

**Comment by zgpmc** [comment]
I use the following address for the installation method: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.204 . My system has been upgraded to 18.04 :The prompt cannot locate the package. Can offer some Suggestions .Thanks
