### ISSUE TITLE
creating the skasia UI to rule them all

### ISSUE THREAD

**Issue by reader-man** [dotnet/core#2742]
This is a suggestion to MS
https://readerman1.wordpress.com/2019/03/04/xamarin-vs-flutter-3rd-party/

to start a Flutter like, that will have all the power and feature rich UI, to work on all OSs, using .net core as its base.

**Comment by karelz** [comment]
Thanks for letting us know. Closing as no follow up is necessary.

cc @richlander @leecow @terrajobst if they are interested
