### ISSUE TITLE
what we can place inplace of <repo>

### ISSUE THREAD

**Issue by saikeerthi12** [dotnet/core#2744]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Can you share more details about the problem, like the "step-by-step"?

**Comment by karelz** [comment]
Not enough information, closing. Feel free to reopen if there is additional details available. Thanks!
