### ISSUE TITLE
The packages are broking unnecessarily

### ISSUE THREAD

**Issue by saikeerthi12** [dotnet/core#2745]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current#ubuntu18-04-issue
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Can you share more details about the problem?

**Comment by karelz** [comment]
Not enough info, please provide additional details and reopen. Thanks!
