### ISSUE TITLE
I can't open the program.cs file that contains the hello world command

### ISSUE THREAD

**Issue by bramdevylder** [dotnet/core#2747]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by igoventura** [comment]
Can you share more details about the problema?

**Comment by karelz** [comment]
Find it on disk, open it in your favorite editor. Unless something truly bad happened, it should be there - maybe just in a subdirectory.
