### ISSUE TITLE
Need help with .NET

### ISSUE THREAD

**Issue by magi9** [dotnet/core#2748]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: windows

Until I ve installed .NET SDK there was no new command promt

**Comment by igoventura** [comment]
Can you share more details about the problem?

Anyway have you restarted your cmd after installed the .net core SDK?

**Comment by magi9** [comment]
so i have just installed .net sdk but no new command line have been
installed.
so i can not restart non existing cmd

pi 17. 5. 2019 o 21:29 Igo Ventura <notifications@github.com> napísal(a):

**Comment by karelz** [comment]
@magi9 I don't understand your question.
Did you follow these steps?
1. Install .NET Core SDK
2. Run new cmd window
3. Run `dotnet` command in that cmd window?

If that does not work, something really bad happened on your machine. Maybe you didn't install the .NET SDK correctly, or your machine is somehow in weird state.
If that's the case, try to restart, or try to install .NET Core SDK on brand new VM/another machine (ideally clean).

**Comment by magi9** [comment]
I have installed the .NET Core SDK but it was installed without the cmd.I
can not find new cmd window in pc. And I have reinstalled it 3 times.

pi 17. 5. 2019 o 22:41 Karel Zikmund <notifications@github.com> napísal(a):

**Comment by karelz** [comment]
cmd is part of the OS - it is the "Command Prompt"

**Comment by magi9** [comment]
yeah i know but you said that any new cmd

pi 17. 5. 2019 o 22:59 Karel Zikmund <notifications@github.com> napísal(a):

**Comment by karelz** [comment]
Yes, run new instance of cmd.
I start to be lost at what is unclear now :( ... maybe a snapshot would help?

**Comment by karelz** [comment]
Not actionable, closing. Feel free to reopen if there is more info available.
