### ISSUE TITLE
.NET CORE3 

### ISSUE THREAD

**Issue by sunkaixuan** [dotnet/core#2749]
Preview5 has a problem ，EMIT，Entity mapping error.Bad IL format

**Comment by sunkaixuan** [comment]
Old version is good.

**Comment by dj2792** [comment]
The target version is preview5.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by karelz** [comment]
Please create minimal repro that is actionable.
Once you have that, feel free to reopen.
