### ISSUE TITLE
dotnet command doesn't exist on macOS

### ISSUE THREAD

**Issue by grosch** [dotnet/core#2751]
# Issue Title

dotnet command doesn't exist after installing SDK

# General

I just went to https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install and downloaded the SDK.  It installed without any errors.  I then closed all terminals and opened a new one, but the dotnet command doesn't exist.

I'm on macOS Mojave 10.14.4

**Comment by CPoffWebster** [comment]
Have the same issue.

**Comment by grosch** [comment]
Their installer is screwy.  This will fix your issue:

```bash
sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/
```

**Comment by CPoffWebster** [comment]
Thank you this fixed the issue!

**Comment by karelz** [comment]
@dagood any idea who could help fix this in our installers?

**Comment by leecow** [comment]
The Mac installer does not create a symlink, it adds /usr/local/share/dotnet to PATH. We can discuss if changing the approach makes sense as well as try to figure out why PATH was not updated in this case.

**Comment by grosch** [comment]
@leecow Updating the PATH is *never* the right thing to do.  You have no idea how the system or the user's environment is configured.  Every time you add to the path, for example, the shell has to re-find everything.  The path should be set one and only one one time for performance reasons.  

Regardless, you're making an assumption as well that I'm using Bash as my shell, for example.  I hate bash, I'm using tcsh, and you're not updating that.  The proper way to install local software is to install it into /usr/local/bin, or ask the end user where it should be installed.  Don't try to have your software modify the path.

**Comment by leecow** [comment]
Thanks for that feedback @grosch. We'll have a look at making the change. Moving this issue to core-setup.

**Comment by leecow** [comment]
Issue moved to [dotnet/core-setup #6521](https://github.com/dotnet/core-setup/issues/6521) via [**ZenHub**](https://www.zenhub.com/)
