### ISSUE TITLE
I downloaded the asp.net core sdk and installed and it doesn't appeare in my visual studio and even it doesn't response in cmd 

### ISSUE THREAD

**Issue by esmatullahmohabat** [dotnet/core#2755]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by AdvancedPowerArmor** [comment]
I think you can try repair Visual Studio 2019 via Control Panel and then try to reinstall .NET Core.

**Comment by karelz** [comment]
First make it work from cmd - you need to stat new cmd. If that does not work, check the installation, or try on another VM/machine.
