### ISSUE TITLE
Dotnet issue in MS Visual Studio Code

### ISSUE THREAD

**Issue by Aayush1008** [dotnet/core#2756]
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of  the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + dotnet + ~~~~~~     + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by karelz** [comment]
Sounds like a good issue for VS Code as it seems to be integration related.
If you have troubles with command line, please let us know here. Thanks!
