### ISSUE TITLE
Question: SxS install of SDK v2.2.204 and 2.2.107

### ISSUE THREAD

**Issue by odalet** [dotnet/core#2757]
# SxS install of SDK v2.2.204 and 2.2.107

In various places I read that depending on the version of Visual Studio one uses, he should install preferably Version 2.2.107 (for VS2017) or Version 2.2.204 (for VS2019). In my case, I've installed both VS versions (specifically v15.8.2 and v16.0.0). 

I wonder:
* Whether Side by side install of both SDKs allows seamless usage in both VS?
* In case SxS install is not a solution, will a future SDK will be published that supports both VS2017 and VS2019?

**Comment by odalet** [comment]
OK, answering (at least partially) my own question:
* After having installed SDK v2.2.107, then SDK v2.2.204, 
  * VS 2019 can correctly build a netcoreapp2.2 project (just tested with the default generated console app, so it does nothing...)
  * VS 2017 cannot build anything targeting .NET Core >= 2.0 (in the Project Properties > Application tab > Target Framework combo, I can only see .NET Core 1.x)
* Then I uninstalled v2.2.204 and kept v2.2.107
  * VS 2017 can build netcoreapp2.2 projects
  * VS 2019 as well...

It seems that - contrarily to what's explained [here](https://dotnet.microsoft.com/download/dotnet-core/2.2), [here](https://github.com/dotnet/announcements/issues/113) and [here](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.204-SDK/2.2.204-SDK-download.md), VS 2019 can handle building against v2.2.107 SDK... (unless this works because I have VS2017 installed or my test project is too simple).

**Comment by karelz** [comment]
@livarcocc @nguerrera can you please help with this one?

**Comment by nguerrera** [comment]
Make sure that your VS 2017 is updated to 15.9.x and things would work fine SxS with VS 2017 pickinh 2.2.1xx and VS 2019 picking 2.2.2xx+. We did some work in 15.9 to make this happen. The behavior you describe sounds like you have 15.8 or earlier. If not, there's an issue that will need more info and investigation.

**Comment by odalet** [comment]
Thanks for the reply! Indeed I'm using 15.8.2; I'll give a try to updating my VS2017.
