### ISSUE TITLE
releases.json missing 2.2.203 and 2.2.204 SDK

### ISSUE THREAD

**Issue by directhex** [dotnet/core#2758]
DotNetCoreInstaller@0 uses https://github.com/dotnet/core/blob/master/release-notes/releases.json as its source of truth on SDKs which exist

That file was last updated on 2019-04-03, so is missing .NET Core 2.2.4 and 2.2.5 (and matching SDK versions) which were released after 2019-04-03

**Comment by leecow** [comment]
@directhex, I'm seeing this content in the current [releases.json](https://raw.githubusercontent.com/dotnet/core/master/release-notes/2.2/releases.json). Do you have a fork or branch you're working from that needs a refresh?

**Comment by directhex** [comment]
It looks like a generic unversioned releases.json is used?

`Could not fetch download information for version 2.2.203. Please check if the version specified is correct. You can refer the link for supported versions => https://github.com/dotnet/core/blob/master/release-notes/releases.json. Falling back to creating convention based URL.`

It looks like the problem might be specific to `DotNetCoreInstaller@0` which uses a different parsing method to `DotNetCoreInstaller@1`?

**Comment by leecow** [comment]
I'm not familiar with `DotNetCoreInstaller@0` or `DotNetCoreInstaller@1`. Where do they come from?

**Comment by directhex** [comment]
Various versions of the Azure DevOps tasks to install .NET Core. Which seems to have changed again since last week. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops

**Comment by leecow** [comment]
Interesting, I didn't know about that. I can try to find the maintainers on this side to update their tool and perhaps you could drop a comment on the tool page. Between those, we'll find the right people.

**Comment by MattGal** [comment]
@leecow not something our team owns, but from skimming through their code at  https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreInstallerV0 and V1, I'd ask folks like @hiyadav or @bishal-pdMSFT , who have touched it in functional ways recently for a redirection.

**Comment by hiyadav** [comment]
@directhex 
We have released 2.* version of DotNetCoreInstaller task, which uses the updated json file: [releases-index.json](https://github.com/dotnet/core/blob/master/release-notes/releases-index.json), to find out download URL. You can use 2.* version for all the new versions of .Net core sdk/runtime.

Both 1.* and 2.* versions were very recently released with some breaking changes in respect to 0.* version, thus are kept as preview.
