### ISSUE TITLE
NETCore.UniversalWindowsPlatform 5.2.2 DesignTime Issue

### ISSUE THREAD

**Issue by MengYunfan** [dotnet/core#276]
Hi:

In Visual Studio 2015 Update 3, If i use designtime data, this will make xaml designer broken.

Error message:

`BadImageFormatException: Cannot load a reference assembly for execution.`
`StackTrace: Empty`
`InnerException: None`

**Comment by iamsid** [comment]
Hi. Found any solution or workaround for this?

**Comment by MengYunfan** [comment]
only method, go back to 5.1.0

**Comment by MengYunfan** [comment]
@iamsid only method, go back to 5.1.0

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
