### ISSUE TITLE
dotnet-sdk-3.0.100-preview5-011568-linux-x64 restore fails on ubuntu for private feeds

### ISSUE THREAD

**Issue by arthis** [dotnet/core#2761]
# Issue Title

I am using ubuntu 16.04
when performing dotnet restore upon project that references nuget within private  feeds ( in my case , TFS 2017), it fails. The problem is a nuget related one that has been solved in the version 5.2. 

Currrently the version of nuget included in the 3.0.100 version of the sdk include the 5.1 version.

When is it planned to include version 5.2 to solve the issue ?

# General

Nuget restore calls  $HOME/.config/NuGet/NuGet.Config
dotnet restore calls $HOME/.nuget/NuGet/NuGet.Config

I have the following NuGet.Config file : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Store" value="https://My tfs 2017 connection goes here" />
  </packageSources>
  <packageSourceCredentials>
    <Store>
        <add key="Username" value="vsts" />
        <add key="ClearTextPassword" value="xxxxxxxxxxxxxx" />
      </Store>
  </packageSourceCredentials>
</configuration>
```

When calling nuget restore on my csproj with dependencies in the TFS store , and with nuget version 5.2, everything is ok.
Doing the same with up to the latest preview of dotnet available at the moment  (dotnet-sdk-3.0.100-preview5-011568-linux-x64), I have embedded the version 5.1 for nuget components. Calling dotnet restore with the NuGet.Config  forementionned results in : 

```
john@MyMachine:~/dotnet$ dotnet --version
3.0.100-preview5-011568
john@MyMachine:~/dotnet$ dotnet restore /pathTo/myProjectWithTfsDependencies.csproj
/home/john/dotnet/sdk/3.0.100-preview5-011568/NuGet.targets(121,5): error : Unable to load the service index for source "https://My tfs 2017 connection goes here". [/pathTo/myProjectWithTfsDependencies.csproj]
/home/john/dotnet/sdk/3.0.100-preview5-011568/NuGet.targets(121,5): error :   GSSAPI operation failed with error - An invalid name was supplied (Configuration file does not specify default realm). [/pathTo/myProjectWithTfsDependencies.csproj]
```

When will Nuget 5.2 version be included in dotnet core sdk ? Currently dotnet restore with private feed TFS does not work on ubuntu. I have an ugly script that either append --configfile to all dotnet isntruction or, nuget script that performs the restore operations.

**Comment by karelz** [comment]
@livarcocc @nguerrera is it something you can help with or help route?

**Comment by nguerrera** [comment]
Routing to NuGet folks: @nkolev92 @rrelyea

**Comment by nkolev92** [comment]
Not sure what is different in 5.2 from 5.1 that'd make this behave differently. We really do anything special networking wise on NuGet side. 

As far as 5.2 in 3.0 is concerned, it should have already made it in the latest nightly builds.

The only other time I remember seeing a similar issue was https://github.com/NuGet/Home/issues/6902#issuecomment-414952160. 
Is it maybe related to https://github.com/dotnet/corefx/issues/28961?

**Comment by arthis** [comment]
Indeed my Bad, I just check using nuget version 5.02 , it works with this version so the issue might not be the version of nuget after all. But the issue still exists.
Whant I do not get is that I have both NuGet.Config  files (~/.nuget/NuGet/NuGet.Config, and ~/.config/NuGet/NuGet.Config) identical to this script:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Store" value="https://xxxx.com/MainCollection/_packaging/Store/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <Store>
        <add key="Username" value="vsts" />
        <add key="ClearTextPassword" value="xxxxxxxxxxxxxxxxxxxxxxxxx" />
      </Store>
  </packageSourceCredentials>
</configuration>
```

I do perform these steps :

```
nuget locals all -clear
nuget restore myProject.csproj

```
Msbuild is called and the nuget in the TFS are fetched, auth is ok

```
nuget locals all -clear
dotnet restore
```

```
/home/xxxx/dotnet/sdk/3.0.100-preview5-011568/NuGet.targets(121,5): error : Unable to load the service index for source https://xxxxxxxxxxxxx/MainCollection/_packaging/Store/nuget/v3/index.json. [/home/xxxx/sources/zzzzzzzzzz/fio/yyyyy/src/yyyyy_presentation/yyyyy_presentation.csproj]
/home/xxxx/dotnet/sdk/3.0.100-preview5-011568/NuGet.targets(121,5): error :   GSSAPI operation failed with error - An invalid name was supplied (Configuration file does not specify default realm). [/home/xxxx/sources/zzzzzzzzzz/fio/yyyyy/src/yyyyy_presentation/yyyyy_presentation.csproj]
```


I thought that dotnet resrore relied on nuget to achieve restoring packages, if so two questions :
1) is the nuget.config used by dotnet restore different from the nuget one?
2) is the nuget.condif used really the ~/.nuget/NuGet/NuGet.Config one ?

**Comment by nkolev92** [comment]
dotnet.exe should work mostly the same as nuget.exe. The only different is that dotnet.exe does not support packages config. 

As far as config reading goes they should be the same. 
If you enable normal or verbose logs you will be able to see which configs NuGet uses.

**Comment by karelz** [comment]
No response, not actionable. Closing.
Feel free to reopen if there is more information available.
