### ISSUE TITLE
NO PUEDO CREAR CONTROLADORES EN LA VERSION SDK 3.0 PREVIEW.  VS2019

### ISSUE THREAD

**Issue by restrellasosa** [dotnet/core#2762]
![Capture](https://user-images.githubusercontent.com/6253560/58108572-17816400-7bba-11e9-8a33-bcdd4e43629a.JPG)

# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by karelz** [comment]
Quick search on internet leads to this: https://developercommunity.visualstudio.com/content/problem/431328/scaffolding-error-there-are-no-scaffolders-support.html
