### ISSUE TITLE
dotnet 2.2 issue ubuntu

### ISSUE THREAD

**Issue by Grandy631** [dotnet/core#2765]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My terminal says dotnet is not installed ,whereas dotnet was installed and it can be refreshed by snap but cannot be run through terminal.

**Comment by karelz** [comment]
@dagood can you please help?

**Comment by leecow** [comment]
Can you run `snap list` to confirm the dotnet sdk is installed? If so, try `dotnet-sdk.dotnet --info`. Our snap installer currently uses a different default namespace so commands start with `dotnet-sdk.dotnet` instead of just `dotnet`.

**Comment by karelz** [comment]
No response, not actionable. Closing
