### ISSUE TITLE
Access denied to path C:\\windows\system32\file.resources

### ISSUE THREAD

**Issue by Ihavenoideawhatido** [dotnet/core#2767]
I get this error everytime i try to bind files togetherer. 

So i don't know much about computer and have searched for solutions but can't really understand how to fix this issue at hand. So i'm looking for someone to explain this to me like im five lol.

**Comment by karelz** [comment]
What is the minimal repro that runs into this problem?

**Comment by karelz** [comment]
Also, does it happen to you on more than 1 machine? (try a brand new VM/machine)
Also, specify OS version please.

**Comment by karelz** [comment]
No response. Feel free to reopen if/when there is additional info.
