### ISSUE TITLE
dotnet-sdk-2.2 does not install because of missing libssl1.0 in Ubuntu 19.04

### ISSUE THREAD

**Issue by zegracia** [dotnet/core#2769]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Ubuntu 19.04 has libssl1.1, and not 1.0. This results in broken packages error, so dotnet-sdk-2.2 does not install.

**Comment by karelz** [comment]
Duplicate of #2526
