### ISSUE TITLE
How the error message is displayed by Chinese with .NET Core 3.0.0-preview5

### ISSUE THREAD

**Issue by 15092368540** [dotnet/core#2770]
![Net Framework](https://user-images.githubusercontent.com/49462433/58139337-d007e000-7c6c-11e9-954c-345618c45402.png)
![Net Core 3](https://user-images.githubusercontent.com/49462433/58139338-d0a07680-7c6c-11e9-9194-3ea4027e5031.png)

**Comment by karelz** [comment]
Exceptions are not localized on purpose in .NET Core. We do not expect exceptions to be user-facing. They are for developers.
