### ISSUE TITLE
Cannot run dotnet in  command prompt

### ISSUE THREAD

**Issue by johnny-intergreat** [dotnet/core#2772]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
You need to start new cmd window. If that does not help, check your installation / try on another VM/machine.
Closing, feel free to reopen of it persists.
