### ISSUE TITLE
Error when installing a dotnet App on my Windows 10 desktop (dev mode)

### ISSUE THREAD

**Issue by hrugani** [dotnet/core#2774]
Operating System: Windows 10

I am trying to install an app via ps script on my windows 10 desktop (dev mode).

**I am getting the following error:**

"Windows cannot install package XXXXX.com.op2b.smartax_1.0.1.0_x86__v1qg3v2068v1t because this package depends on a
framework that could not be found. Provide the framework "Microsoft.NET.CoreRuntime.1.0" published by "CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and
minimum version 1.0.23819.0, along with this package to install. The frameworks with name
"Microsoft.NET.CoreRuntime.1.0" currently installed are: {}"

**I already installed some versions of "dotnet.runtime" as you can see:**

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.204
 Commit:    8757db13ec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.204\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.204 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

On "microsoft-downloads" I only found binary versions for runtime 1.0.0. (without installer)
How can I install the 1.0.0 (binary) and make the Windows recognize it as installed?

**Comment by karelz** [comment]
Get the 1.0 download: https://dotnet.microsoft.com/download/dotnet-core
