### ISSUE TITLE
about support risc-v

### ISSUE THREAD

**Issue by mfjiang** [dotnet/core#2778]
# Issue Title

about support risc-v

# General

Does .net have plans to support the RISC-V architecture?

**Comment by windsOne** [comment]
I am equally curious if I can support it.

**Comment by karelz** [comment]
There are currently no plans to support additional processor architectures.
You can check Mono if it has that support.

**Comment by logicethos** [comment]
RISC-V is gaining popularity.
Allwinner & Alibaba are launching a new  RISC-V-based SoC. https://www.techradar.com/uk/news/here-comes-the-most-formidable-rival-to-the-raspberry-pi-yet
There is the OpenTitan project, backed by Google, Western Digital, and others.
FPGA's are getting cheaper, and more accessible, which can run RISC-V.

**Comment by the-mentor** [comment]
Now that RISC-V becoming more popular I would love to see support for it as a prerequisite to PowerShell

**Comment by InCerryGit** [comment]
> RISC-V is gaining popularity.
> Allwinner & Alibaba are launching a new RISC-V-based SoC. https://www.techradar.com/uk/news/here-comes-the-most-formidable-rival-to-the-raspberry-pi-yet
> There is the OpenTitan project, backed by Google, Western Digital, and others.
> FPGA's are getting cheaper, and more accessible, which can run RISC-V.
> 
> This should be re-opened.

I agree

**Comment by 0xStuart** [comment]
Please please reopen this.  RISC-V is going to be everywhere.

Look at this https://twitter.com/SipeedIO/status/1443486484112183298?s=20
