### ISSUE TITLE
docker container (based on 2.1-runtime-apline) crashed with no logs/errors/exceptions

### ISSUE THREAD

**Issue by mchenx** [dotnet/core#2786]
I'm not sure if this is the right place to raise the issue...(or maybe it's not an issue at all)

I have an netcoreapp2.0 web application and it was compiled based on microsoft/dotnet:2.1-sdk-alpine, and then copied to the new image based on microsoft/dotnet:2.1-runtime-alpine.

The docker container of this new image runs fine on azure vm or vmware workstation on my laptop, or windows 10 (wsl). However, it doesn't work correctly on the vm on vmware vsphere.

Basically, I can execute 'docker run' successfully with this new image. But as long as I send http request to the container, it crashed without any exception, error, no logs at all. 

BTW, this can also be reproduced on my macbook pro (10.13.6).

I still can start the container and attach to it. Under the working folder, I could find there were dump files, core.xxx (core.1, core.60, core.255, etc., each time it crashed it created on with different number)

I tried to use lldb and load the dump file, but got no luck, no exceptions but "read memory from xxxxxxxxxx failed"

![image](https://user-images.githubusercontent.com/1550186/58345110-2ef67080-7e8a-11e9-94d0-ac37635f1ac5.png)

As this is a company internal app, I cannot publish the docker image here (maybe I can try to reproduce with an simple small web app)

I have no ideas what happened and why, for now, I can get rid of this by 
1) upgrade the web application to netcoreapp2.1, 
2) replace Microsoft.AspNetCore.All with Microsoft.AspNetCore.App and
3) rebuild the image with microsoft/dotnet:2.1-sdk-alpine but create the new docker image based on microsoft/dotnet:2.1-aspnetcore-runtime-alpine (instead of microsoft/dotnet:2.1-runtime-alpine)

Not sure if this is about dotnet core or microsoft/dotnet image issue...

I thought it could be the vsphere issue, however other docker images (like nginx) run well

BTW, the vm on vsphere is, the vm on my laptop running in vmware workstation, and the azure vm are all CentOS Linux 7 (core)  7.6.1810

**Comment by mchenx** [comment]
after a few hours testing, I find that it doesn't matter if the framework is netcoreapp2.0 or netcoreapp2.1, what matters is the package reference is 2.0.x or 2.1.x.
If the referenced packages are 2.0.x and with 2.1-runtime-alpine, it causes such issue on macOS and vm on vsphere, but it works fine on azure vm and windows 10 WSL 
If the reference packages are 2.1.x and with 2.1-runtime-alpine, it works fine on macOS, vsphere vm, windows 10 WSL, etc.

If you are interested im you can try below images
mvn11/dockerweb:aspnetcore-2.0.3 (with Microsoft.AspNetCore-2.0.3 and Microsoft.AspNetCore.Mvc-2.0.3 packages)
mvn11/dockerweb:aspnetcore-2.1.1  (with Microsoft.AspNetCore-2.1.1 and Microsoft.AspNetCore.Mvc-2.1.1 packages)

both runtime image are microsoft/dotnet:2.1-runtime-alpine

when the container runs, try  /api/values, if it works, it will return ["value1", "value2"]
otherwise, it will crash without any log/output

**Comment by svrooij** [comment]
What you're describing is expected behavior.
The runtime images need to use the same version as the packages. So is you use dotnet core 2.2 you’ll need the 2.2 runtime image.

I cannot find the actual documentation page at the moment, but I’ve definitely seen this explained in the documentation. It has something to do with the asp dlls already being in the base image.

**Comment by mchenx** [comment]
but the interesting thing is this works fine on the vmware workstation player vm on my laptop and also runs fine on windows WSL ... I mean dotnet core 2.0 packages with 2.1 runtime image...

**Comment by karelz** [comment]
We do not support ASP.NET Core 2.0 applications to run on ASP.NET Core 2.1 without recompilation AFAIR.
Given all works after recompile, we should close it, unless there is some serious and wide-spread scenario that is broken by this.
