### ISSUE TITLE
Creating this template will make changes to existing files:

### ISSUE THREAD

**Issue by amitbhi** [dotnet/core#2790]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm using windows 10 and installed .net
I'm new to this so was following instructions. I got the following error in red:
C:\Users\Amit\myApp>dotnet new webApp -o --no-https
Creating this template will make changes to existing files:
  Overwrite   myApp.csproj
  Overwrite   Program.cs

Rerun the command and pass --force to accept and create.

**Comment by karelz** [comment]
Run the command in new directory, not in existing one and it should work.
It seems you ran the command twice in the same directory ...

**Comment by PH68** [comment]
esta acontecendo o mesmo comigo hj como resolver

**Comment by mairaw** [comment]
@PH68 isso acontece pq já tem um projeto no local onde vc está executando o comando.

Tem algumas opções diferentes:
- executar o comando num diretório diferente 
- executar o comando adicionando a opção --force. Isso vai substituir o projeto existente 

Avise se isso te ajudou!

**Comment by PH68** [comment]
@mairaw consegui fazer um novo diretorio, é que é a segunda vez que faço isso pra mim é tudo muito novo, obrigado por responder ;)

**Comment by PH68** [comment]
então@mairaw  como faço pra forçar a mudança??

**Comment by mairaw** [comment]
Na primeira vez que executa, o comando é `dotnet new webApp -o myWebApp --no-https
cd myWebApp`

Se vc já executou uma vez e quer começar de novo, pode forçar a mudança adicionando `--force`
`dotnet new webApp -o myWebApp --no-https
cd myWebApp --force`

Esse artigo explica as opções:
https://docs.microsoft.com/pt-br/dotnet/core/tools/dotnet-new

**Comment by svdevendra** [comment]
Let's understand with an example,

Suppose you are working on a console application so to create a new console app you will execute a command **dotnet new console**, a new project will create in your directory.  Now if you will execute the same command in the same directory again then you will end up with this error.

Hope this will help you..
