### ISSUE TITLE
error MSB4019 .NET Core 3.0.100-preview5-011568 Linux

### ISSUE THREAD

**Issue by johnlarfour** [dotnet/core#2791]
I downloaded .NET Core 3.0.100-preview5-011568 SDK and I have installed on my system follow this guide https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview5-linux-x64-binaries.
Then i use this command ```dotnet new winforms -o app```
and then `dotnet run`

This is the output:
```
/home/john/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets(14,2): error MSB4019: The imported project "/home/john/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/home/john/Desktop/app/app.csproj]

The build failed. Please fix the build errors and run again.

```

Did I do something wrong?

**Comment by svick** [comment]
Winforms apps are not supported on Linux, so I think it's expected that this does not work.

**Comment by karelz** [comment]
Correct, WinForms and WPF are Windows-only. Even build has to happen on Windows.
