### ISSUE TITLE
3.0.100 - preview5 OAuth functions not found

### ISSUE THREAD

**Issue by McClean** [dotnet/core#2792]
While attempting a Twitter login to via the native Twitter package **[Microsoft.AspNetCore.Authentication.Twitter" Version="2.2.0"]**

I received the following error upon successful callback:

> MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Authentication.OAuth.Claims.ClaimAction.Run(Newtonsoft.Json.Linq.JObject, System.Security.Claims.ClaimsIdentity, System.String)'.

Twitter login was configured using the following snippet as taken from the guide [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.0)
>`services.AddAuthentication().AddTwitter(options =>
                {
                    options.ConsumerKey = Configuration["Twitter:API_KEY"];
                    options.ConsumerSecret = Configuration["Twitter:APP_SECRET"];
                });`

Also when using the package **[AspNet.Security.OAuth.Instagram" Version="2.0.1"]** I received the folliwing error:

> MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Authentication.OAuth.OAuthCreatingTicketContext..ctor(System.Security.Claims.ClaimsPrincipal, Microsoft.AspNetCore.Authentication.AuthenticationProperties, Microsoft.AspNetCore.Http.HttpContext, Microsoft.AspNetCore.Authentication.AuthenticationScheme, Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions, System.Net.Http.HttpClient, Microsoft.AspNetCore.Authentication.OAuth.OAuthTokenResponse, Newtonsoft.Json.Linq.JObject)'.

Instagram Configuration:

`.AddInstagram(options =>
                {
                    options.ClientId = Configuration["Instagram:CLIENT_ID"];
                    options.ClientSecret = Configuration["Instagram:APP_SECRET"];
                     });`

Both configurations correctly load the external login page as well as respond to the appropriate callback. The issue seems to be with handling the callback request.

**Comment by McClean** [comment]
This was my fault. My nuget wasn't set to allow previews and so I didn't get the latest twitter and OAuth packages.

**Comment by wxf1223138295** [comment]
how to set the nuget to allow previews? Can you teach me?

**Comment by fariz1992** [comment]
Installing and updating pre-release packages
By default, NuGet does not include pre-release versions when working with packages, but you can change this behavior as follows:

Package Manager UI in Visual Studio: In the Manage NuGet Packages UI, check the Include prerelease box:

The Include prerelease checkbox in Visual Studio

Setting or clearing this box will refresh the Package Manager UI and the list of available versions you can install.

Package Manager Console: Use the -IncludePrerelease switch with the Find-Package, Get-Package, Install-Package, Sync-Package, and Update-Package commands. Refer to the PowerShell Reference.

NuGet CLI: Use the -prerelease switch with the install, update, delete, and mirror commands. Refer to the NuGet CLI reference

Reference: https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

**Comment by fariz1992** [comment]
> how to set the nuget to allow previews? Can you teach me?
> 
> ## Here is the error info
> MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Authentication.OAuth.Claims.ClaimAction.Run(Newtonsoft.Json.Linq.JObject, System.Security.Claims.ClaimsIdentity, System.String)'

Installing and updating pre-release packages
By default, NuGet does not include pre-release versions when working with packages, but you can change this behavior as follows:

Package Manager UI in Visual Studio: In the Manage NuGet Packages UI, check the Include prerelease box:

The Include prerelease checkbox in Visual Studio

Setting or clearing this box will refresh the Package Manager UI and the list of available versions you can install.

Package Manager Console: Use the -IncludePrerelease switch with the Find-Package, Get-Package, Install-Package, Sync-Package, and Update-Package commands. Refer to the PowerShell Reference.

NuGet CLI: Use the -prerelease switch with the install, update, delete, and mirror commands. Refer to the NuGet CLI reference

Reference: https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages
![prerelease_02-checkprerelease 1](https://user-images.githubusercontent.com/5210578/58753681-e6633680-84cb-11e9-8d79-ee693be98b1e.png)
