### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by ankitpanwar9196** [dotnet/core#2794]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by viveknatarajan** [comment]
@ankitpanwar9196 : Do you have entry for dotnet (exe path) in environment variable?

**Comment by karelz** [comment]
You need to open new command line window after the installation. That is typically the problem.
Otherwise check your PATH settings.

**Comment by Orji-QA** [comment]
dotnet' is not recognized as an internal or external command,
operable program or batch file.
I have similar issues, How can check my computer file? and what steps would I use to add python to my path?

**Comment by kdarodker** [comment]
> You need to open new command line window after the installation. That is typically the problem.
> Otherwise check your PATH settings.

This was my issue. I used an existing Command window. 

Thanks Karelz

**Comment by RukeshB** [comment]
same problem. i check path (the correct path is there) and also reopen command window too.
But it doesn't work

**Comment by TristanKnox** [comment]
Same here, I have uninstalled the SDK and reinstalled, set the path to C:\Program Files\dotnet and reopened cmd but still nothing

**Comment by Joeshibha** [comment]
This works for me! 
Go to Settings->Apps and features->.net sdk->Uninstall->Repair

**Comment by mairaw** [comment]
@TristanKnox can you paste the output of `where.exe dotnet`?
