### ISSUE TITLE
Unable to locate package dotnet-sdk-2.2 (Ubuntu 19.04, key present)

### ISSUE THREAD

**Issue by aaronfjerstad** [dotnet/core#2796]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Unlike other reported bugs, the key is installed:

```
/etc/apt/trusted.gpg.d/microsoft.gpg
------------------------------------
pub   rsa2048 2015-10-28 [SC]
      BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF
uid           [ unknown] Microsoft (Release signing) <gpgsecurity@microsoft.com>
```

I ran each command found in https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current. I have updated and upgraded and rebooted in every conceivable way. On the last command, I always get the following:
```
sudo apt install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'
```

**Comment by dagood** [comment]
Can you run these diagnosis steps and share the results? Hopefully it'll help determine what state your system's in right now:

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

**Comment by karelz** [comment]
Not actionable, closing. Feel free to reopen if there is more info available.
