### ISSUE TITLE
mac cannot run dotnet when i install dotnet

### ISSUE THREAD

**Issue by lixiaodong** [dotnet/core#2798]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
Make sure you run new shell. Check that your path contains dotnet.
If you still face problems, check your installation. Try it again.
If you can, try it on another machine to make sure it is not a one machine problem.
If you still have problems, please provide more details.
