### ISSUE TITLE
MSBUILD : error MSB1001: Unknown swith.

### ISSUE THREAD

**Issue by craigdanforthHome** [dotnet/core#2800]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by craigdanforthHome** [comment]
when I ran new webApp -o --no--https 
[error for #2800.txt](https://github.com/dotnet/core/files/3225034/error.for.2800.txt)

**Comment by craigdanforthHome** [comment]
I attempted to attach the command verbiage.

**Comment by karelz** [comment]
What is the `--no--https` option is not present in `dotnet new -h`. Are you sure it is correct?

If you read the error output, that is exactly what dotnet is telling you - it used it as project name, but interpretted as option because it starts with `--`:
```
C:\Users\Craig Danforth\myApp>dotnet new webApp -o --no--https
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.

Processing post-creation actions...
Running 'dotnet restore' on --no--https\--no--https.csproj...
MSBUILD : error MSB1001: Unknown switch.
Switch: --no--https\--no--https.csproj
```
