### ISSUE TITLE
Integrated terminal in vscode doesn't recognise dotnet

### ISSUE THREAD

**Issue by dupr0n** [dotnet/core#2801]
![dotnet](https://user-images.githubusercontent.com/40289345/58460853-0dc4a700-814c-11e9-8e42-2acf7e005a43.JPG)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

You'll find an image, attached to this post, which shows that dotnet is installed, but the integrated terminal in vscode doesn't pick up on it. I also tried using an external terminal for vscode and got the same result. 
VS Code couldn't find .NET

**Comment by karelz** [comment]
Did you start new instance of vscode?
I assume this is more question for vscode terminal feature and how it picks up path settingsbfrom OS.

**Comment by RKDupron** [comment]
Ok, got it. Restarting vscode didn't fix it, but restarting my laptop did... Thanks
