### ISSUE TITLE
Ugly url in SPA template

### ISSUE THREAD

**Issue by Amine-Smahi** [dotnet/core#2804]
When requesting the fetch data component in any of the angular or react template without being authenticated we get back an ugly url

`https://localhost:5001/Identity/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DASP.NETCoreWebApplication2%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A5001%252Fauthentication%252Flogin-callback%26response_type%3Did_token%2520token%26scope%3DASP.NETCoreWebApplication2API%2520openid%2520profile%26state%3D2a2c1f381b274a06a09c836c6d63a33c%26nonce%3Dae2559be95624fb980b8cdfe41341cb7`

dotnet version 3.0 preview 5

**Comment by Pilchie** [comment]
@ryanbrandenburg - any idea where this should be moved?

**Comment by ryanbrandenburg** [comment]
https://github.com/aspnet/AspNetCore, with the tag "area-identity".

**Comment by Pilchie** [comment]
This issue was moved to aspnet/AspNetCore#10627
