### ISSUE TITLE
cannot install .net

### ISSUE THREAD

**Issue by venkateshbelgaonkar7** [dotnet/core#2805]

**Comment by dagood** [comment]
This usually indicates you're using a feed that doesn't match your distro release. Can you run these diagnosis steps and share the results?

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

Please copy and paste the text in the terminal rather than sending a screenshot.

**Comment by venkateshbelgaonkar7** [comment]
Issue solved! Thanku very much.

**Comment by famotril** [comment]
Hi, I received time ago this message I tried almost everything to solve it:

****The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.****

I do not have idea of what does it mean the message **dagood** wrote in the upper message but I copied it and entered into the Terminal and I received this message, that I do not understand either:

**Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. Todos los derechos reservados.

PS C:\Users\RAFA> # Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
PS C:\Users\RAFA>
>> grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
grep : El término 'grep' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. 
Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e 
inténtelo de nuevo.
En línea: 2 Carácter: 1
+ grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sou ...
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\RAFA>
>> # Show your distro version.
PS C:\Users\RAFA>
>> cat /etc/os-release
cat : No se encuentra la ruta de acceso 'C:\etc\os-release' porque no existe.
En línea: 2 Carácter: 1
+ cat /etc/os-release
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\os-release:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
PS C:\Users\RAFA>
>> # This install command will show exactly which dependency can't be met.
PS C:\Users\RAFA>
>> sudo apt-get install dotnet-runtime-deps-2.2**

Anyone can help?



> This usually indicates you're using a feed that doesn't match your distro release. Can you run these diagnosis steps and share the results?
> 
> ```
> # Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
> grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
> # Show your distro version.
> cat /etc/os-release
> # This install command will show exactly which dependency can't be met.
> sudo apt-get install dotnet-runtime-deps-2.2
> ```
> 
> Please copy and paste the text from the terminal rather than sending a screenshot.

**Comment by dagood** [comment]
Unfortunately the contents of the original issue were edited out, I think that misled you a little. 😕 It was about a specific error on Linux (Ubuntu), but you're on Windows. Your error is unrelated, and you're trying to run Linux commands in Windows PowerShell.

@famotril Please open a new issue, and include how you installed the .NET Core SDK (which version, where you got it from).

**Comment by famotril** [comment]
Wow I realize I am lost! I am forcing the update of windows 10 to the last version that is 1903, because it looks a compatibility issue, if is works I will confirm here to help others. 
Thanks by replying!
