### ISSUE TITLE
Assembly Redirection For Plugin Framework

### ISSUE THREAD

**Issue by zeus82** [dotnet/core#2806]
# Issue Title

I've written an application in .Net Core 2.2 that is extensible with plugins. A plugin is a dotnet standard 2.0 DLL that has an implementation of my plugin base class. The plugin base class is defined in a shared dotnet standard 2.0 dll.

I have updated the dll that has the base class with some non-breaking changes. I have now updated my application to use the new version of the shared dll. Now when I try to load a plugin I wrote using the old version of the shared DLL I get an error. If I don't rev the version of my shared DLL the plugin loads fine.

Here is the code for loading the plugins:
```c#
foreach (var dll in Directory.GetFiles("baseDir", "*.dll", SearchOption.AllDirectories))
{
    _logger.Info("Loading {0}", dll);
    var a = Assembly.LoadFile(dll);
    availableAssemblies[a.GetName().Name] = a;
}

// setup assembly resolver with scanned assemblies
AssemblyLoadContext.Default.Resolving += (_, b) =>
{
    if (availableAssemblies.ContainsKey(b.Name))
        return availableAssemblies[b.Name];

    _logger.Info("Can't file assembly {0}", b.Name);
    return null;
};


foreach (var a in availableAssemblies)
{
    _logger.Info("Searching {0} for plugin", a.Value.FullName);
    plugin = Array.Find(a.Value.GetTypes(), t => t.IsClass && !t.IsAbstract && GetAllBaseClasses(t).Any(b => b.FullName == typeof(PluginBase).FullName));
}
```

**Comment by karelz** [comment]
This is very end-to-end scenario. Can you please narrow it down to minimal repro?
Post the error. Ideally debug into it in CoreFX source code.

**Comment by karelz** [comment]
Not actionable, closing. Feel free to reopen if there is more info available.
