### ISSUE TITLE
Cant install .netcore 2.2 on Debian9 stretch

### ISSUE THREAD

**Issue by upretyrohan** [dotnet/core#2807]
cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/

/etc/apt/sources.list:deb cdrom:[Debian GNU/Linux 9.3.0 _Stretch_ - Official amd64 DVD Binary-1 20171209-12:11]/ stretch contrib main
/etc/apt/sources.list:deb http://security.debian.org/debian-security stretch/updates main contrib
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/debian/9/prod stretch main

**Comment by dagood** [comment]
Thanks for including the output from some of the diagnostic commands! The output of those looks like what I'd expect. Can you show what the install error is? What's the output of these commands:

```
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
sudo apt-get install dotnet-runtime-deps-2.2
```

**Comment by karelz** [comment]
Not actionable, closing. Feel free to reopen if there is more info available.
