### ISSUE TITLE
An assembly specified in the application dependencies manifest   was not found

### ISSUE THREAD

**Issue by wind8147** [dotnet/core#2808]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-2.2.300
Operating System: Linux CentOS / Oracle - x64
package: 'Microsoft.Extensions.Caching.Abstractions', version: '2.2.0'
    path: 'lib/netstandard2.0/Microsoft.Extensions.Caching.Abstractions.dll'

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
What exactly did you do? Is it some tutorial? Real application?
Does it happen all the time?
Did you try it on another VM / machine?

**Comment by karelz** [comment]
Not actionable, closing. Feel free to reopen if there is more info available.
