### ISSUE TITLE
No "User preview versions" checkbox in "projects and solutions" options tab

### ISSUE THREAD

**Issue by Padanian** [dotnet/core#2809]
While configuring a new WPF project via the start screen of VS2019, a dialog box appear informing that I have to select "User preview versions" under ".NET core" section of "Projects and solutions" option tab. Unfortunately such item does not exist.

Can be reproduced all times. Note: VS2019 in IT-it locale.

Further: creating a new WPF project via CLI: "dotnet new wpf" restores succesfully, but tring to open the project via VS2019 ends in "One or more errors found" dialog box.

Supposedly, some imports declarations are missing.

As a side note, the --list-sdks shows 3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk while --list-runtimes shows 
Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App and Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App .
Not sure if this is relevant, though.

**Comment by Padanian** [comment]
Microsoft Visual Studio Community 2019
Versione 16.1.1
VisualStudio.16.Release/16.1.1+28922.388

**Comment by karelz** [comment]
Seems like a bug in VS. Can you please use VS Feedback channel? (e.g. from inside VS - at the right top there is "Send Feedback" icon, or via Help menu)

**Comment by Padanian** [comment]
It's a bug in .net core. 
"User preview versions" under ".NET core" section of "Projects and solutions" option tab does not actually exist. It's been moved to "Preview features"

![74632-1](https://user-images.githubusercontent.com/7769348/58641658-e7de0480-82fb-11e9-80f2-b8bbd3de6006.jpg)

**Comment by karelz** [comment]
I am confused. Why is it .NET Core bug when .NET Core does not have any UI? UI part is VS.
What am I missing?

**Comment by Padanian** [comment]
Because the message is in english in a completely IT-it localised version of VS (the screenshot above is for your convenience, shot from an english version of VS), and because the VS team cannot know they moved the option to another tab, while leaving an unlocalised misleading text in a msgbox.

**Comment by karelz** [comment]
Now I am even more confused - which message box?

Nevertheless, I have no idea where to route it other than VS.

**Comment by Padanian** [comment]
The msgbox of the first post in this thread. But never mind, I reckon you are not interested, as you closed the thread before understanding the issue. I already sorted it out anyway.

**Comment by karelz** [comment]
Oh, maybe I start to understand now what you were trying to report:
When you create new WPF project for .NET Core in VS 2019, there is dialog referencing incorrect category/tab in Options -- it says "User preview versions" but it should say "Environment -- Preview Features -- Use previews of the .NET Core SDK".

Is that what you were trying to report?
If yes, then this is indeed part of Visual Studio, not .NET Core, so please report it there. Thank you!

**Comment by Padanian** [comment]
https://developercommunity.visualstudio.com/content/problem/576973/use-previews-of-the-net-core-sdk-checkbox-is-now-m.html
