### ISSUE TITLE
Proposal:  jupyter/ipython kernel

### ISSUE THREAD

**Issue by milijan** [dotnet/core#281]
It would be an interesting addition to the roadmap.

**Comment by Petermarcu** [comment]
@milijan , thanks for the pointer. Definitely something to add to the roadmap with respect to data scientists and their ability to use .NET.

@richlander

**Comment by julianonunes** [comment]
In fact there is already a C# kernel project for iPython at https://github.com/zabirauf/icsharp, thus it has not been updated since May.

**Comment by milijan** [comment]
@julianonunes there is and I have not tried it on linux (not on windows) with mono but it is my understanding that it targets windows (clue in the in chm help file) and its GPL...

**Comment by cdrnet** [comment]
(there is also nicely working .Net kernel for F# - https://github.com/fsprojects/IfSharp)

**Comment by richlander** [comment]
Love these projects. We don't have any plans to do any work in this space ourselves.

**Comment by PrashanthKarnam** [comment]
Hi @richlander 

Do we have support for C# applications targeting dotnet core using jupyter notebook ?

Thanks and Regards,
Prashanth Karnam
