### ISSUE TITLE
Project .Net Core Call to library 4.6.1 thats use System.Data.Ole

### ISSUE THREAD

**Issue by guillermo2007** [dotnet/core#2813]
# Issue Title

Project .Net Core Call to library 4.6.1 thats use System.Data.Ole

# General

I have a project in .Net Core 2.2 and i try to call a function in a library to .net framework 4.6.1. This library use System.Data.OleDb and when y try to call, throws a exception and cant load assembly.

is there any way this works?

Thanks

**Comment by guillermo2007** [comment]
Tjis is the message when the program try to call any function

"Could not load type 'System.Data.OleDb.OleDbConnection' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."

**Comment by karelz** [comment]
Running .NET Framework libraries on .NET Core is on your own risk. You have to validate that the library uses only types available in .NET Core - you can use [.NET API Portability Analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) for that.
OleDb is part of .NET Core 3.0 AFAIK - try our latest previews instead. cc @saurabh500
