### ISSUE TITLE
How to get only console logs in output?

### ISSUE THREAD

**Issue by wpitallo** [dotnet/core#2814]
How to get only console logs in output?

Hi, currently I have set my logs to only log program output but I am still getting a lot of unwanted information. Is there a way to get just my logs and also none of the namespaces etc

![image](https://user-images.githubusercontent.com/12214559/58662970-abc29800-832b-11e9-99af-59b1ae7a98e8.png)

Also is there an easy way like in Node.js to log in color without having to configure custom providers?

**Comment by Pilchie** [comment]
This issue was moved to aspnet/Extensions#1773
