### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by ahlstart** [dotnet/core#2815]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run#
Operating System: Microsoft Windows [Version 10.0.17134.799]

"dotnet run" command generated the following error message instead of expected greeting:
c:\program files\dotnet\sdk\2.2.300\Roslyn\Microsoft.CSharp.Core.targets(59,5): error : A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'c:\program files\dotnet\shared\Microsoft.NETCore.App\2.1.9'. [C:\Users\Arto\myApp\myApp.csproj]

The build failed. Please fix the build errors and run again.

**Comment by karelz** [comment]
Looks like bad install. Can you try to reinstall or try on another machine/VM please?

**Comment by ahlstart** [comment]
Will do when I get to that machine. I canceled out first attempt, that may have left things in a bad way. OTOH, the error message suggests that somewhere is a dependency of a file installed by previous version and it has been left as it was. Hold your bug hunting horse though until I have tried it again on the box where this occurred.

**Comment by ahlstart** [comment]
I uninstalled version *1.0.4* and then 2.2.300 and then reinstalled 2.2.300. I also removed all traces of myApp. When trying to run myApp again, I get the exact same error message. I tried it with another box.
Result: Self-built AMD Athlon X2 5000+ PC with Microsoft Windows [Version 10.0.17134.376] printed "Hello World!". So my main machine is just confused and unable to use dotnet Core. How nice, but little the dev team can do.

**Comment by karelz** [comment]
OK, can you try to uninstall all .NET Core versions from your broken machine as first step?
Make sure the installation directory is empty, Windows installers, etc.
Then install .NET Core version again.

Another option is to try to use ZIP "install" from https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries ... put it into different directory, then use environment variables to override default and see if you can run it that way.

**Comment by ahlstart** [comment]
While I do not have an immediate need for .NET Core, getting it running would mean that this machine is not actually very broken. So I did a thorough clean-up and installed once more. AND IT WORKS. Thank you for caring and the sound advice.
