### ISSUE TITLE
unable to locate package dotnet-sdk-2.1 on debian 9 

### ISSUE THREAD

**Issue by utsushimi** [dotnet/core#2817]
> Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.1.700
> Operating System: Linux Debian 9 - x64

```
$ sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'
```

Have found through various similar threads, trying many workarounds, such as purging the packages, following steps of manual installation, updating my OS, probably whatever else was said as well... I'm very new to Linux, so this is all super confusing. Source list:

```
/etc/apt/sources.list /etc/apt/sources.list.d/
/etc/apt/sources.list:deb http://ftp.us.debian.org/debian/ stretch main non-free contrib
/etc/apt/sources.list:deb http://security.debian.org/debian-security stretch/updates main contrib non-free
/etc/apt/sources.list:deb http://ftp.us.debian.org/debian/ stretch-updates main contrib non-free
/etc/apt/sources.list:deb https://dl.winehq.org/wine-builds/debian/ stretch main
/etc/apt/sources.list:deb https://dl.winehq.org/wine-builds/ubuntu/ stretch main
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu stretch universe
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/debian/9/prod stretch main
```

Tried adding `deb http://deb.debian.org/debian stretch main `as a source but didn't change anything. Not sure what other information I need to include to get help but please let me know!!!

**Comment by dagood** [comment]
I can think of two extra commands to run for diagnosis:

```
# Show your distro info.
cat /etc/os-release
# Show the result of apt-get update (maybe this is failing).
sudo apt-get update
```

Your list of sources looks reasonable to me, here's the similar list I end up with when I run through an install in a `debian:9` Docker container:

```
/etc/apt/sources.list:deb http://deb.debian.org/debian stretch main
/etc/apt/sources.list:deb http://security.debian.org/debian-security stretch/updates main
/etc/apt/sources.list:deb http://deb.debian.org/debian stretch-updates main
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/debian/9/prod stretch main
```

**Comment by wfurt** [comment]
also did you add do all the PGP steps?

**Comment by karelz** [comment]
Not actionable with the info above, closing.
Feel free to reopen once there is more info.
