### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tartdoccom** [dotnet/core#2818]
Original title: ติดตั้งไม่ได้ 
Translated: Can't install

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 - x64 [Original text: Linux เดเบียน 9 - x64]

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment]
There is not enough information to make it actionable.
Can you please try it on another VM/machine?

Also, please report problems in English - we don't scale to translate from other languages. Thank you!

**Comment by karelz** [comment]
No response, no info, closing.
