### ISSUE TITLE
[Request] Net Core 3 Preview apt-get based installation

### ISSUE THREAD

**Issue by SirJosh3917** [dotnet/core#2819]
# Net Core 3 Preview apt-get based installation

I would really love if dotnet core 3 could be integrated with an apt-get based upstream, so I can globally update dotnet and maintain compatibility with the existing infrastructure I have (daemons to run asp net core applications). I got some help and was pointed in the direction of using snap for the dotnet sdk, but I tried to use snap, and I was able to run the command from both the command line and as root, but the daemon refuses to start up now (which is why I'd like an apt-get based solution). (`/snap/core/current/usr/bin/snap run dotnet-sdk.dotnet /path/to/service.dll
`)

cc @tannergooding

**Comment by tannergooding** [comment]
CC. @leecow, @richlander

**Comment by leecow** [comment]
@SirJosh3917 - something that we're looking at enabling at some point but it's not likely to happen for 3.0. Based on another piece of customer feedback we will publish the deb/rpm which you can use locally. Hopefully, that will somewhat help your situation. 

Regarding the Snap troubles. Could you provide more details? What's your environment?

**Comment by SirJosh3917** [comment]
Debian 9 on an Azure VM `Standard B1ls (1 vcpus, 0.5 GiB memory)`, and the service looks like
```
x@y-z:~$ cat /etc/systemd/system/apinetcore.service
[Unit]
Description=API for my stuff

[Service]
Type=simple
WorkingDirectory=/path/to/
ExecStart=/snap/core/current/usr/bin/snap run dotnet-sdk.dotnet /path/to/service.dll
Restart=always
RestartSec=10
KillSignal=SIGINT
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production

[Install]
WantedBy=multi-user.target
```
(`/path/to/service.dll` and `x@y~z` are replaced in this snippit, they aren't the real values)

**Comment by bklooste** [comment]
Most common issue with snap we have is windows sub system to avoid duel booting. .,.
ie
"Interacting with snapd is not yet supported on Windows Subsystem for Linux."

**Comment by carlossanlop** [comment]
@leecow is there any progress on this request?

**Comment by GoodMirek** [comment]
@carlossanlop RPM and DEB packages are available from https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview9-download.md. I am not aware of any package repository yet.

**Comment by scalablecory** [comment]
Hi @SirJosh3917, apt install is supported -- please follow the instructions here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
