### ISSUE TITLE
Framework-dependent deployment build behavior change between .Net Core 2.1 and .Net Core 3.0

### ISSUE THREAD

**Issue by StreamingTodd** [dotnet/core#2820]
If I build something like this in .Net Core 2.1, I get a dll, no exe:

```
  PropertyGroup>
    OutputType>Exe</OutputType>
    TargetFramework>netcoreapp2.1</TargetFramework>
    RuntimeFrameworkVersion>2.1.0</RuntimeFrameworkVersion>
  /PropertyGroup>
```

If I try to build something like this in .Net Core 3.0, I get a dll AND exe:

```
  PropertyGroup>
    OutputType>Exe</OutputType>
    TargetFramework>netcoreapp3.0</TargetFramework>
    RuntimeFrameworkVersion>3.0.0-preview5-27626-15</RuntimeFrameworkVersion>
  /PropertyGroup>
```

Is this expected? Why is this seemingly no longer a framework-dependent deployment? Is there another flag I need to add when building in .Net Core 3.0?

I am using 3.0.100-preview5-011568.

**Comment by StreamingTodd** [comment]
Actually, I found that there is a behavior change:

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0

Default executables

.NET Core now builds framework-dependent executables by default. This behavior is new for applications that use a globally installed version of .NET Core. Previously, only self-contained deployments would produce an executable.

So, this one executable runs on Windows, Linux, and MacOS? Is it possible to sign this executable with strong name signing or only Authenticode? Is the dll that gets produced usable without the exe like a dll produced with netcoreapp2.1?

**Comment by karelz** [comment]
I think you should be able to run the DLL via dotnet run.
The EXE is just copy of dotnet host

cc @steveharter @jeffschwMSFT
