### ISSUE TITLE
dotnet test gives me error while running tests 

### ISSUE THREAD

**Issue by manojmsrit** [dotnet/core#2824]
Hello, I am getting below error when i try to use "dotnet test", can you please suggest me regarding this

dotnet test Test.kommmit.Offers/Test.kommmit.Offers.csproj
Build started, please wait...
/usr/local/share/dotnet/sdk/2.2.107/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETPortable,Version=v4.5,Profile=Profile259" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/kommmit.Offers/kommmit.Offers/kommmit.Offers.csproj]
/usr/local/share/dotnet/sdk/2.2.107/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETPortable,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
Before this error i got one more error shown as below which i resolved by updating path of "Microsoft.Portable.CSharp.targets" manually.

dotnet test Test.kommmit.Offers/Test.kommmit.Offers.csproj
Build started, please wait...
/Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/kommmit.Offers/kommmit.Offers/kommmit.Offers.csproj(220,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.2.107/Microsoft/Portable/v4.5/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by karelz** [comment]
It looks like something is referencing .NETPortable ...
Do you have a minimal repro you can share?

@nguerrera @davkean can you please help route it? Thanks!

**Comment by davkean** [comment]
This behavior is to be somewhat expected, dotnet SDK doesn't come with portable support.

**Comment by karelz** [comment]
Closing then, or is there anything left to track?

**Comment by nguerrera** [comment]
The path forward would be to convert the portable class library projects to target .NETStandard.
