### ISSUE TITLE
Can't Connect to LocalHost After DotNet Setup

### ISSUE THREAD

**Issue by theaby** [dotnet/core#2826]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/run
Operating System: windows

I followed the instructions to set up .NET core and came across this in the tutorial:
Once the command completes, browse to http://localhost:5000

In my attempt to browse to the link provided, I kept receiving the following message (screenshot attached):
Hmmm… can't reach this page localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I am using Microsoft Windows Version 1903 (OS Build 18362.145)
![CantReachLocalHostAfterDotNetSetup](https://user-images.githubusercontent.com/23208341/58829783-8ff61500-85fd-11e9-8727-26cabdd3ba62.jpg)

**Comment by karelz** [comment]
How did you run the app? From command line? What is the output? Does it fail to bind to the port?
Did you check your firewall settings?
Here's similar troubleshooting: #2411

**Comment by Pilchie** [comment]
Closing due to lack of response.

**Comment by theaby** [comment]
I actually got it working just now. I don't believe that I have done anything different but it works.
