### ISSUE TITLE
when i write dotnet command on my command prompt, it shows up the following error...

### ISSUE THREAD

**Issue by Manthan0599** [dotnet/core#2829]
![Screenshot (35)](https://user-images.githubusercontent.com/42907759/58948540-ed849000-87bc-11e9-9a83-fcb64f8ad2b2.png)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by viveknatarajan** [comment]
@Manthan0599 : After installing donet core, did you close and open the command prompt?

**Comment by Manthan0599** [comment]
I'll try that now,  thanks

**Comment by karelz** [comment]
Thanks @viveknatarajan for help! Closing ng as it is now answered.
