### ISSUE TITLE
ASP.NET Web API Authentication Using HMAC

### ISSUE THREAD

**Issue by Xavierh95** [dotnet/core#283]
Hi everyone,

I want to secure an ASP.NET Web API project with HMAC auth.

This REST API project will be used by third-party developers to access my application's data.

I'm trying to adapt [this post](http://www.codeguru.com/csharp/.net/net_asp/learn-to-secure-an-asp.net-web-api-using-hmac.html)  in .NET Core without success...

Some of the class / interface used don't exist anymore (ex: IAuthenticationFilter, HttpAuthenticationContext, HttpAuthenticationContext, IHttpActionResult)

How can I add a sample HmacAuthentication attribute to my API methods in order to protect them with HMACSHA256 ?

Thanks for your answers!

**Comment by Petermarcu** [comment]
@danroth27 Whats the best place to ask this question where some ASP.NET folks can help?

**Comment by danroth27** [comment]
I don't think we have a good built-in solution for this today in the framework.

@leastprivilege @bockallen Is this something you can setup with [IdentityServer](http://identityserver.io)?

**Comment by blowdart** [comment]
@danroth27 No - it's something entirely different. It's signing the request, with a preshared key. It's not something we support out of the box, but you should be able to do it with authorization middleware.

**Comment by blowdart** [comment]
@Xavierh95 Do you mean something like https://github.com/blowdart/Idunno.WebApi.SharedKeyAuth, except for core?

**Comment by blowdart** [comment]
I could look at porting my one.

**Comment by ademcaglin** [comment]
@Xavierh95 Take a look at https://github.com/ademcaglin/Security.HmacAuthentication. It might be useful for you.

**Comment by hope15** [comment]
@Xavierh95 Maybe it's worth a look

https://github.com/ademcaglin/Security.HmacAuthentication

**Comment by richlander** [comment]
Please re-activate if this is still an issue.

**Comment by danroth27** [comment]
This issue was moved to aspnet/Security#1141
