### ISSUE TITLE
latest link to release notes broken

### ISSUE THREAD

**Issue by jstallm** [dotnet/core#2835]
# Issue Title

Latest release notes link broken

# General
link on releases page for latest release leads to 404

https://github.com/dotnet/core/blob/master/release-notes/1.1/2.2.5/2.2.5.md

**Comment by karelz** [comment]
Where is the broken link? I checked top level and 2.2 main pages and they are both ok.

**Comment by karelz** [comment]
Also, would you mind submitting a OR with a fix? That may be easiest ... Thanks!

**Comment by leecow** [comment]
I think I've cleaned up all instances of this.
