### ISSUE TITLE
This revision of snap "dotnet-sdk" was published using classic confinement and thus may        perform arbitrary system changes outside of the security sandbox that snaps are usually        confined to, which may put your system at risk.      

### ISSUE THREAD

**Issue by kamula** [dotnet/core#2837]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by kamula** [comment]
on Ubuntu 19.04

**Comment by syumaK** [comment]
I am also getting the same error on Ubuntu 18.04.2 LTS

**Comment by leecow** [comment]
This is expected as the SDK, by definition, needs additional access to system resources. To install using the Snap package, use the `--classic` flag as indicated by the warning.
