### ISSUE TITLE
How to force include newer version of NuGet package that is part of the Microsoft.NETCore.App runtime meta-package

### ISSUE THREAD

**Issue by lp-brainspire** [dotnet/core#2842]
We use Snyk to stay up to date and fix vulnerabilities in our dependencies as soon as possible.

Snyk is telling us there is a [vulnerability](https://snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTREGULAREXPRESSIONS-174708) with our version of `System.Text.RegularExpressions` and that we should upgrade to version `4.3.1`.

`System.Text.RegularExpressions` is part of the `Microsoft.NETCore.App` meta-package.  However, the latest runtime, `2.2.5`, only includes version `4.2.1` of `System.Text.RegularExpressions`.

There is a NuGet package with `4.3.1` that could bring us up to the latest with no current vulnerabilities.  However, according to [this page](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#implicit-package-references) (and our own experiments), the `System.Text.RegularExpressions` will not be published with our application because it is part of `Microsoft.NETCore.App` meta-package:

> These references to ASP.NET Core metapackages have a slightly different behavior from most normal NuGet packages. Framework-dependent deployments of applications that use these metapackages automatically take advantage of the ASP.NET Core shared framework. When you use the metapackages, no assets from the referenced ASP.NET Core NuGet packages are deployed with the application—the ASP.NET Core shared framework contains these assets. The assets in the shared framework are optimized for the target platform to improve application startup time. For more information about shared framework, see .NET Core distribution packaging.

Is there any way to force the NuGet version of  `System.Text.RegularExpressions` to be published with our application and/or to override the version in the latest `Microsoft.NETCore.App` runtime?

This is a general question, as there are other libraries similar to `System.Text.RegularExpressions` that are part of the meta-packages that have vulnerabilities but are not yet updated in the latest runtimes but *are* available in NuGet packages.

We have self-contained builds and variations of `CopyLocalLockFileAssemblies`, `CopyToOutputDirectory`, `IncludeAssets`, etc... in our .csproj file with no luck.  *If* `System.Text.RegularExpressions` gets copied to our publish folder (i.e. self-contained), it is still the runtime library's version - not the NuGet version.

**Comment by cremor** [comment]
This is not related to your actual question, but why do you think version 4.2.1 of System.Text.RegularExpressions doesn't fix the bug? Have you tested it?

According to both the security advisory announcement (dotnet/announcements#111) and the [2.2.5 release notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.5/2.2.5.md) the runtime 2.2.5 does fix it.

There is no package listed for version 4.2.1 of System.Text.RegularExpressions on nuget.org, so it's hard to tell when it was released. But at least there was a version 4.1.1 released at the same day as version 4.3.1, which is very likely a backport of that fix.

**Comment by omajid** [comment]
This seems very similar to https://github.com/dotnet/core/issues/2291. The (relevant parts of the) summary from that discussion was that packages that are included with the latest `Microsoft.NETCore.App` are safe. Their nuget versions (like `4.2.1`) are irrelevant and any tooling that flags those packages is producing a false alarm.

**Comment by carlossanlop** [comment]
Since it's a nuget related question, I'm assigning it to @rrelyea. Rob, is this something you can help with?

**Comment by rrelyea** [comment]
No, please work with the asp.net team.
They should analyze the situation and determine the right thing to do to ensure their customers don’t need to use a security vulnerability.

**Comment by carlossanlop** [comment]
@Pilchie can your team please take a look, as suggested by Rob?

**Comment by Pilchie** [comment]
Looping in @livarcocc because this is a publishing question.  Also note that `System.Text.RegularExpressions` is only transitively included by the Asp.NET metapackage - it's actually included by `Microsoft.NETCore.App`.

**Comment by livarcocc** [comment]
I believe you can simply reference the package directly in your project. If the version is newer than what the framework has, we will use that.

**Comment by Pilchie** [comment]
Closing, since @livarcocc has hopefully answered this.  @lp-brainspire let us know if the guidance didn't help

**Comment by sorin-bolos** [comment]
I have the same security issue. Need to use `System.Text.RegularExpressions` version `4.3.1` instead of the default `4.3.0`. I refernced the System.Text.RegularExpressions nuget version 4.3.1. After publishing to a folder I see no `System.Text.RegularExpressions.dll` copied, but in the `.deps.json` file all references to this assembly have swithced to `4.3.1`.
What does this mean? Does the `Microsoft.NETCore.App` meta-package have both versions included? Where will the runtime find the new version?

**Comment by YarikProkop777** [comment]
> I have the same security issue. Need to use `System.Text.RegularExpressions` version `4.3.1` instead of the default `4.3.0`. I refernced the System.Text.RegularExpressions nuget version 4.3.1. After publishing to a folder I see no `System.Text.RegularExpressions.dll` copied, but in the `.deps.json` file all references to this assembly have swithced to `4.3.1`.
> What does this mean? Does the `Microsoft.NETCore.App` meta-package have both versions included? Where will the runtime find the new version?

I have the same issue. Please help us with it.

**Comment by Pilchie** [comment]
Please file a new issue at https://github.com/dotnet/runtime.  People often don't see comments on issues that have been closed for years.
