### ISSUE TITLE
Debug.Print and Debug.Indent/Unindent don't work correctly in .NET Core.

### ISSUE THREAD

**Issue by rlundy** [dotnet/core#2843]
# Issue

In .NET Core, Debug.Print, Debug.Indent, and Debug.Unindent don't behave as they did in previous versions of .NET, and the changes are for the worse.

When outputting to the Output window in Visual Studio 2019:

`Debug.Print(string)`: Formerly automatically produced a line break after the string; no longer does.

`Debug.Indent`: Does not appear to indent.

`Debug.Unindent`: Does not appear to unindent.

# Environment
Windows 10 x64
Visual Studio Community 2019 preview, version 16.2.0 Preview 1.0
.NET Core version 3.0.100-preview5-011568

# Sample

Run sample in Visual Studio 2019.  Afterwards, check the Output window for results.

Expected: Each Debug.Print statement should produce its own line, and the line with "indented" should be indented.

Actual: All Debug.Print text appears on one line, and there's no indentation.

[DebugPrintSample.zip](https://github.com/dotnet/core/files/3265588/DebugPrintSample.zip)

**Comment by Anipik** [comment]
cc @maryamariyan

**Comment by maryamariyan** [comment]
Looking...

**Comment by maryamariyan** [comment]
Debug.Print should behave the same way as Debug.Write

If you want a new line you should be using Debug.WriteLine, rather than Debug.Write("...\n")

**Comment by maryamariyan** [comment]
closing as it got fixed through https://github.com/dotnet/corefx/issues/38359

**Comment by rlundy** [comment]
@maryamariyan Do you know which version of .NET Core I should watch for this fix in?  Will it be 3.0.100-preview6, or something else?
