### ISSUE TITLE
Add API Diffs for .Net Core versions earlier than 3.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/core#2845]
We have API diffs for all previews of .Net Core 3.0, starting with `3.0-preview1` vs. `2.2`: https://github.com/dotnet/core/tree/master/release-notes/3.0/preview/api-diff. We should add diffs for versions earlier than 3.0, starting with 2.2 vs 2.1 and working backwards. Note that this is different from ApiCompat baselines, which exist in the Standard repo for compatibility of various frameworks (and old .Net Standard versions) with the current version of .NetStandard: https://github.com/dotnet/standard/tree/master/src/apicompat/baselines.

CC @karelz

**Comment by carlossanlop** [comment]
Hey @wtgodbe you self-assigned this. Have you done any progress on this issue?

**Comment by wtgodbe** [comment]
@Anipik did this for 2.2 vs 3.0 here: https://github.com/dotnet/core/pull/3411

Will leave this open in case we want to continue backwards later on

**Comment by carlossanlop** [comment]
@Anipik did you get a chance to look into this?

**Comment by Anipik** [comment]
@carlossanlop i already added the api diff for 2.2 and 3.0. i think that  we need to go back any further as 2.1 and 2.2 are going out of support.

**Comment by carlossanlop** [comment]
Okay, thanks @Anipik. Let's close this issue.
