### ISSUE TITLE
i tried installing dotnet core on ubuntu 

### ISSUE THREAD

**Issue by yuthan** [dotnet/core#2846]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Operating System:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by yuthan** [comment]
sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

**Comment by guftall** [comment]
you should first run these two command
```
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

anyway, i suggest to install .net core with `dotnet-install.sh` script which you can find here:
`https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script`
By using this, it's so easy to install different .net core or asp.net core sdk and runtime versions side by side.
Then using `global.json` to specify which version you want to use in each project
```
https://docs.microsoft.com/en-us/dotnet/core/tools/global-json
```

**Comment by yuthan** [comment]
Thanks  that resolved my issue :)

**Comment by guftall** [comment]
your welcome, i think we can close this issue now ^_^
