### ISSUE TITLE
How to use Clipboard in .Net Core 3.0 MVC

### ISSUE THREAD

**Issue by EdoRguez** [dotnet/core#2847]
I have my ASP.Net Core 3.0 MVC web application on Visual Studio 2019 and I’m trying to use the clipboard as I can do in Windows Forms.

I have added `System.Windows.Forms` to references and it works, the problem is when I call it on the document by writting `using System.Windows.Forms;` but Visual Studio cannot find it.

In Windows Forms I am able to select and copy text on the clipboard inside the code. I would like select and copy text inside the code using the clipboard as I can do in Windows Forms.

According to the documentation it should allow me use the clipboard in my ASP.Net Core 3.0 MVC web app.

My References:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview5-19227-01" />
  </ItemGroup>

<ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
```

**Comment by davidfowl** [comment]
> In Windows Forms I am able to select and copy text on the clipboard inside the code. I would like select and copy text inside the code using the clipboard as I can do in Windows Forms.

Can you explain which clipboard you're trying to capture text from? Is it the browser clipboard? Or the clipboard on the server machine (which it sounds like you're doing...)

**Comment by EdoRguez** [comment]
@davidfowl I mean the clipboard on the server machine. The user uploads a .Doc file, this file has some bookmarks and I'm getting text between bookmarks. The way that I solved it in Windows Forms was using the clipboard when I'm reading the .Doc file.

Here is an example.

`// Demonstrates SetText, ContainsText, and GetText.
public String SwapClipboardHtmlText(String replacementHtmlText)
{
    String returnHtmlText = null;
    if (Clipboard.ContainsText(TextDataFormat.Html))
    {
        returnHtmlText = Clipboard.GetText(TextDataFormat.Html);
        Clipboard.SetText(replacementHtmlText, TextDataFormat.Html);
    }
    return returnHtmlText;
} `

**Comment by davidfowl** [comment]
Can't you get the text of a range without copying? https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.range.text?view=word-pia#Microsoft_Office_Interop_Word_Range_Text

**Comment by EdoRguez** [comment]
@davidfowl It works perfectly for me. The problem is I need the text in HTML format with its styles. That's the reason why I'm using the clipboard to get the text in HTML format.

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.range.formattedtext?view=word-pia#Microsoft_Office_Interop_Word_Range_FormattedText

**Comment by EdoRguez** [comment]
Sorry @davidfowl but I used `Range.FormattedText` property, but there is still no way to get the HTML and its styles :(

The only method I could use was `Range.FormattedText.XML` but I need it as HTML format with styles.

This is what I've done.
```
var myRangeText = wordDocument.Range(ref firstBookmark, ref secondBookmark);
String myText =  myRangeText.FormattedText;
```
Are you sure Interop contains a property to get the HTML of a .Doc document? I remember I had to use `Clipboard` in Windows Forms to solve this problem.

**Comment by davidfowl** [comment]
@EdoRguez are you running inside of IIS?

**Comment by EdoRguez** [comment]
@davidfowl Yes, I'm running inside of IIS.

**Comment by davidfowl** [comment]
Does it work outside of IIS? (I'm just trying to narrow it down).

**Comment by EdoRguez** [comment]
@davidfowl I've tried creating a Windows Forms app by creating a button and a textbox. When you press the button you get the text of the word document into the textbox using the previous code, but still with no styles and html format. :(

I think this is not possible with `Microsoft.Office.Interop.Word` but I cannot find out how to solve this problem without using the clipboard.

**Comment by davidfowl** [comment]
You may need to use the clipboard but I'm wondering if the API is broken only when running on ASP.NET Core on IIS or if it's broke in general. Try running your ASP.NET Core application outside of IIS with the clipboard API to see if it works.

**Comment by carlossanlop** [comment]
@EdoRguez no follow up since June. Closing. Feel free to ping us to reopen if you have more info or need more help.
