### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by lodhe54** [dotnet/core#2850]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows 10
Docker version 18.06.1-ce, build e68fc7a

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

U:\myMicroservice>docker build -t mymicroservice -f Dockerfile .
ERRO[0001] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: open //./pipe/docker_engine: The system cannot find the file specified.
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=p2y5rorgr0qqxxcwj2wa762c3&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by carlossanlop** [comment]
@lodhe54, the error message states:

"The system cannot find the file specified." -> Can you please confirm that the file exists in the expected location?
"In the default daemon configuration on Windows, the docker client must be run elevated to connect." -> Can you please verify if it's running elevated?
"This error may also indicate that the docker daemon is not running." -> Can you please verify that the daemon is up and running?

**Comment by karelz** [comment]
3 weeks no response, closing. Feel free to reopen if there is more info available.
