### ISSUE TITLE
Getting exception | No package rh-dotnet22-dotnet-runtime-2.2 available

### ISSUE THREAD

**Issue by SumitBajaj** [dotnet/core#2856]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@SumitBajaj can you please provide more details?

**Comment by karelz** [comment]
3 weeks no response, not enough details available, closing. Feel free to reopen if there is more info.
