### ISSUE TITLE
'Dotnet.exe publish' silently creates bad format for mis-matching architectures

### ISSUE THREAD

**Issue by jjxtra** [dotnet/core#2869]
When using `dotnet.exe publish` for specific runtimes, say win-x86, if using the 64 bit dotnet.exe, this runs without error, but when running the result executable, a `BadImageFormatException `is thrown. Same with target win-x64 from 32 bit dotnet.exe

It should be an error to create a runtime with the wrong 32 bit or 64 bit dotnet.exe, there should be an exception clearly stating that you need to run the dotnet.exe with the same architecture as the runtime you are targetting.

After two days of pain, I finally realized I had to fully qualify the path to dotnet.exe as I had both 32 bit and 64 bit sdk installed. So now for my 32 bit runtime targets, I use the 32 bit dotnet.exe, for the 64 bit targets, the 64 bit dotnet.exe. All run fine without errors.

Please add this as an error condition and save many, many people a lot of pain, headaches and frustration.

Example that fixes the problem in powershell:

```powershell
& "c:/program files/dotnet/dotnet.exe" publish Project.csproj -f netcoreapp2.2 -o package/linux-x64 -c Release -r linux-x64
& "c:/program files (x86)/dotnet/dotnet.exe" publish Project.csproj -f netcoreapp2.2 -o package/win-x86 -c Release -r win-x86
```

**Comment by karelz** [comment]
@livarcocc @nguerrera does it belong to CLI or core-setup?

**Comment by livarcocc** [comment]
CLI would be a good starting point. We can move it to core-setup if the issue was in the production of the apphost.

cc @peterhuene

**Comment by peterhuene** [comment]
Issue moved to [dotnet/cli #11564](https://github.com/dotnet/cli/issues/11564) via [**ZenHub**](https://www.zenhub.com/)

**Comment by peterhuene** [comment]
@nguerrera thanks for closing.  I didn't notice that the tool hadn't closed it 😞.
