### ISSUE TITLE
How to Call Registered COM Components in. net core？

### ISSUE THREAD

**Issue by cwsheng** [dotnet/core#2870]
#  How to Call Registered COM Components in. net core

Call registered COM components in. net core WinForm program

# General

**Comment by carlossanlop** [comment]
@cwsheng can you provide more information? What are you trying to do? Can you provide a code example? What version of .NET Core are you using?

**Comment by karelz** [comment]
3 weeks no response, closing. Feel free to reopen if there is more info.
