### ISSUE TITLE
.NET Core 3.0.100-preview6-012264 upgrade breaks Culture Comparison

### ISSUE THREAD

**Issue by NichUK** [dotnet/core#2872]
- .NET Core 3.0.100-preview6-012264
- Windows Server 2019

**Problem Description**
I upgraded a project to Preview 6 (from Preview 5) and started getting exceptions on a line of code that has been working for months...

`return _oeContext.ConfigItems.Where(c =>`
`                c.Name.Equals(key, StringComparison.CurrentCultureIgnoreCase));`

My current culture is "en-GB"

When replaced with:

`return _oeContext.ConfigItems.Where(c =>`
`                c.Name.ToLower() == key.ToLower());`

everything started working again, so I think there is something wrong with culture comparison in Preview6.

I also tried changing the culture to en-US both by using CurrentThread.CurrentCulture and by changing the whole machine to en-US, but it still didn't work with the original code.

**Comment by ajcvickers** [comment]
@NichUK Is `_oeContext` a `DbContext` from EF Core?

**Comment by NichUK** [comment]
Yes, it's a `Microsoft.EntityFrameworkCore.DbContext`

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/EntityFrameworkCore/issues/16125 since this is an EF query.
