### ISSUE TITLE
use .useSockets(), got many connection time out at Linux

### ISSUE THREAD

**Issue by sharbui** [dotnet/core#2873]
my Environment is 
CentOS 7 latest
dotnet verion 2.2.105

i  use dotnet new web to create a project and use ab to test performance
when  i use default and dotnet run
![image](https://user-images.githubusercontent.com/16458001/59500557-47c3d600-8ecc-11e9-9460-aaf58a5bed28.png)
the ab result was
![image](https://user-images.githubusercontent.com/16458001/59500822-cb7dc280-8ecc-11e9-912b-a7dfb3fdea3b.png)
got so many failed requests

but if i add libuv package and use .UseLibuv()
![image](https://user-images.githubusercontent.com/16458001/59500931-fa943400-8ecc-11e9-8ebf-f65c7b6f7846.png)
the ab result was 
![image](https://user-images.githubusercontent.com/16458001/59501016-34653a80-8ecd-11e9-9dd5-5389cb4263bc.png)

From the results
I feel that using libuv is relatively stable in the Linux environment.

have anyone know about this or how to tuning kestrel with sockets?

**Comment by carlossanlop** [comment]
@Pilchie does this sound like something the ASP.NET team can help with?

**Comment by Pilchie** [comment]
This issue was moved to aspnet/AspNetCore#12017
