### ISSUE TITLE
Couldn't find any package by glob 'dotnet-sdk-2.2', Debian 9

### ISSUE THREAD

**Issue by Souky23** [dotnet/core#2874]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Couldn't find any package by glob 'dotnet-sdk-2.2'
Couldn't find any package by regex 'dotnet-sdk-2.2'

**Comment by dagood** [comment]
The steps work fine for me in a fresh `debian:9` Docker container. Can you paste the output from all the commands as they happened on your machine? It's possible something went wrong in an earlier step without an obvious error message.

**Comment by carlossanlop** [comment]
@Souky23 do you have more information about your issue, as requested?
@chaos1908 since you reported the related issue #2897, do you have more information that could assist with this problem?

**Comment by karelz** [comment]
5 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
