### ISSUE TITLE
Install .NET Core 2.0 SDK on Linux Ubuntu 16.04 - x64 failed

### ISSUE THREAD

**Issue by abahadirdogan** [dotnet/core#2879]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-2.1.4
Operating System: Linux Ubuntu 16.04 - x64

$ uname -a
Linux mahzen 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
$ wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
$ sudo dpkg -i packages-microsoft-prod.deb
$ sudo apt-get install apt-transport-https
$ sudo apt-get install dotnet-sdk-2.1.4
```

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package dotnet-sdk-2.1.4
> E: Couldn't find any package by glob 'dotnet-sdk-2.1.4'
> E: Couldn't find any package by regex 'dotnet-sdk-2.1.4'

**Comment by dagood** [comment]
How did you get to this page, @abahadirdogan?

I'm wondering if our download site is leading you on the wrong path. SDK 2.1.4 is very old and out of support: you can see in the download table that it's actually for .NET Core 2.0 which is end of life: https://dotnet.microsoft.com/download/dotnet-core/2.0.

If you go to https://dotnet.microsoft.com/download and click the "Install .NET Core SDK" button, it should give you instructions to the latest recommended version.

**Comment by dungam** [comment]
Here is how I got the same error message

I downloaded a project targeting .Net Core 2.1

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Example.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
  </ItemGroup>

</Project>
```

Upon trying to build the project in Monodevelop 7.3.3 (build 5), I got an error asking me to install .Net 2.0 SDK

```
Error: .NET Core 2.0 SDK is not installed. This is required to build .NET Core 2.0 projects. https://aka.ms/vs/mac/install-netcore2
```
The url in error message redirects to https://dotnet.microsoft.com/download for latest versions.  This page has instructions for Monodevelop users to install NET Core SDK 2.2.107

```
This SDK version has known issues with MonoDevelop. If you use MonoDevelop, you should install install .NET Core SDK 2.2.107.
```

Ubuntu 18.04 users finally land on the URL https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.107. All instructions on this page resolve to the error message 

```
$ sudo apt install  dotnet-sdk-2.2.107=2.2.107-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2.107
E: Couldn't find any package by glob 'dotnet-sdk-2.2.107'
E: Couldn't find any package by regex 'dotnet-sdk-2.2.107'
```

**Comment by dagood** [comment]
@dungam, that isn't the same, and actually much more clearly something we need to fix, so I filed https://github.com/dotnet/core/issues/2934 to expand on it. (That error message is unfortunately way too general to connect issues like these.) Thanks for the report!

**Comment by karelz** [comment]
6 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
