### ISSUE TITLE
Unable to dynamically load assemblies for exe .NET Core 3.0 apps

### ISSUE THREAD

**Issue by godrose** [dotnet/core#2881]
# Issue Title

Unable to dynamically load assemblies for exe .NET Core 3.0 apps

# General

Repro steps:

-  Create a .NET Core 3.0 Desktop app - App-A
- Create a .NET Core 3.0 Console app - App-B
- Create a .NET Core 3.0 Class Library - App-C
- Create a .NET Standard 2.0 Class Library - Lib
- Add dynamic assembly loading code into each one of the apps:
`Assembly.Load(new AssemblyName(name))`
- Execute each one of them while invoking the assembly loading code 

Expected: All are able to load the assembly dynamically
Actual: Only App-C is successful

**Comment by carlossanlop** [comment]
Thanks for reporting, @godrose .
@ericstj @joperezr  is this something you could help with, since it's related to usage of .NET Standard libraries?

**Comment by joperezr** [comment]
I'm not sure i fully understand what you mean by a .NET Core 3.0 Desktop app, do you mean an app that targets .net framework? Same question goes for the class library, is it an actual app or is that a library? If you could attach a minimal repro solution with all projects we can take a look.

**Comment by karelz** [comment]
1 month no response, closing. Feel free to reopen if there is more info available. Thanks!
