### ISSUE TITLE
https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current Operating System: Linux RHEL - x64

### ISSUE THREAD

**Issue by deywit** [dotnet/core#2884]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@deywit can you provide more information? What problem are you facing?

**Comment by karelz** [comment]
3 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
