### ISSUE TITLE
Fail to install DotNetCore.1.0.1-VS2015Tools.Preview2.0.2

### ISSUE THREAD

**Issue by allenz0810** [dotnet/core#289]
![error](https://cloud.githubusercontent.com/assets/5561722/19482177/4290d174-951e-11e6-8392-2dcdc26b426b.PNG)

[dd_DotNetCoreTools__20161018102707.txt](https://github.com/dotnet/core/files/536531/dd_DotNetCoreTools__20161018102707.txt)

I try all methods in following link but still getting this error. 

https://social.msdn.microsoft.com/Forums/vstudio/en-US/14ccc37f-d70a-454d-bea2-a0244394ac5e/installation-failed-with-error-code-0x80070643-fatal-error-during-installation?forum=netfxsetup

Also reinstall VS Enterprise 2015 with Version 14.0.25431.01 Update 3.

**Comment by richlander** [comment]
Please re-activate if this is still an issue.

**Comment by allenz0810** [comment]
@richlander this issue still exist.
open #289

**Comment by Petermarcu** [comment]
At this point we're recommending people to move to VS 2017 which has the released support for .NET Core tooling.

**Comment by Petermarcu** [comment]
@allenz0810, if you can get the install logs that show what the error is, perhaps we can get a clue as to what's going on.

**Comment by Petermarcu** [comment]
I see you posted them and NuGet is failing to install. To get to the next level I think we'd need the install logs for the NuGetVisualStudio14_rc2_39.msi.

Applying execute package: NuGetVS14, action: Install, path: C:\ProgramData\Package Cache\{08D9540E-77B1-37B3-909A-813DAA5523D0}v3.5.0.1484\packages\NuGetVisualStudio14_rc2_39.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" SKIP_SETUP="1"'
[170C:2344][2016-10-18T10:30:11]e000: Error 0x80070643: Failed to install MSI package.
[170C:2344][2016-10-18T10:30:11]e000: Error 0x80070643: Failed to execute MSI package.
[120C:06C4][2016-10-18T10:30:11]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[120C:06C4][2016-10-18T10:30:11]i319: Applied execute package: NuGetVS14, result: 0x80070643, restart: None
[120C:06C4][2016-10-18T10:30:11]e000: Error 0x80070643: Failed to execute MSI package.

**Comment by Petermarcu** [comment]
@rrelyea @livarcocc
