### ISSUE TITLE
Info Request - Where is this file

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/core#2891]
Hello,
Where is the actual source file where these changes have been done? 

API DIFF: 
https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/api-diff/preview6/3.0-preview6_System.Collections.Generic.md

**Comment by leecow** [comment]
Most of the APIs will be found in the corefx repo. This particular library can be found at https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic.

**Comment by sujayvsarma** [comment]
The API DIFF talks about changing the interface specs of `IDictionary` and `IReadonlyDictionary`. I don't see those objects at the [location](https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic) you mentioned.

**Comment by sujayvsarma** [comment]
@leecow Hopefully you will check if the response you provide is **actually** helpful before closing out the requests.

**Comment by leecow** [comment]
Sorry about that. Again, all of that code should be in the corefx repo so let's move this question over there.

**Comment by leecow** [comment]
Issue moved to [dotnet/corefx #38726](https://github.com/dotnet/corefx/issues/38726) via [**ZenHub**](https://www.zenhub.com/)
