### ISSUE TITLE
3.0.100-preview6 sdk and runtime information not available in releases.json for 3.0 version 

### ISSUE THREAD

**Issue by hiyadav** [dotnet/core#2892]
The version: 3.0.100-preview6 is available online for download but its download information is not updated in [releases.json for version 3](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.0/releases.json). 

Users are failing in trying to download this version via Dot Net Core Installer Task in Azure DevOps, as the task gets download information from [releases-index.json](https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json)

Here is tracking bug for the same on Azure-pipelines-tasks repo: https://github.com/microsoft/azure-pipelines-tasks/issues/10663

**Comment by jabbera** [comment]
I open the same issue three days ago with exactly 0 comments from an owner:-) I thought maybe you guys/gals had the inside track and could fix this with an email or magic dust.

https://github.com/dotnet/core/issues/2878

**Comment by jabbera** [comment]
This issue appears resolved.
