### ISSUE TITLE
Unable to locate package dotnet-sdk-2.2

### ISSUE THREAD

**Issue by terrymandin** [dotnet/core#2894]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

I followed the instructions here: https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.2.300

The very last step resulted in these error messages:

```
root@Moxa:/home/moxa/IoTSamples# sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'
root@Moxa:/home/moxa/IoTSamples# E: Unable to locate package dotnet-sdk-2.2
```
Here is my Debian version info:
```
root@Moxa:/home/moxa/IoTSamples# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

**Comment by terrymandin** [comment]
Ah, I think I see the problem.  I am installing 64 bit on an ARM 32.

**Comment by dagood** [comment]
That would do it! We only produce Debian packages for x64. You'll have to install from binaries for now, see https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md for more info. Binaries are in the "Advanced" button on https://dotnet.microsoft.com/download.
