### ISSUE TITLE
Wich version to choose?

### ISSUE THREAD

**Issue by Lelleflow** [dotnet/core#2895]
I tried to install synctoy and i ran in to problem. 
The installationwizzard says that i need ".NET Framework version 2.0.50727?
Did not find this version on your downloadsite?

**Comment by StevenThuriot** [comment]
Hi,

Go to Microsoft and look in the Downloads center for MS software

.Net Framework 2.0
http://www.microsoft.com/en-us/download/details.aspx?id=6523

.Net Framework 2.0 SP 1
http://www.microsoft.com/en-us/download/details.aspx?id=16614

SyncToy is built upon the .NET Framework, not .NET Core.

**Comment by Lelleflow** [comment]
Thanks. I'll try this
