### ISSUE TITLE
Unable to locate the package dotnet-sdk-2.2

### ISSUE THREAD

**Issue by chaos1908** [dotnet/core#2897]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 - x64

Unable to locate package dotnet-sdk-2.2

**Comment by dagood** [comment]
I'm tentatively closing this as a duplicate of https://github.com/dotnet/core/issues/2874, because it seems to be the same error and the other issue has slightly more detail.

**Comment by dagood** [comment]
Duplicate of #2874
