### ISSUE TITLE
"System.DirectoryServices is not supported on this platform" on Win10

### ISSUE THREAD

**Issue by DerKiLLa** [dotnet/core#2898]
Hi! I tried to use the package today with UWP and C# on Windows 10.

I used the NuGet-Package 2.1.1 and also tried the newest beta and only get the following error:
`System.PlatformNotSupportedException: "System.DirectoryServices is not supported on this platform."`

Any help?

Edit: Found it ... UWP is not supported and DirectoryService is also still in progress ... its just dissapointing, that u can not manage an Directory (LDAP) with UWP ... wow. On one side, u want users to use UWP (Microsoft Graph) and then u can not use Active-Directory ... Is there any option, to use Graph AND DirectoryService?!

**Comment by carlossanlop** [comment]
Thank you for reporting, @DerKiLLa.
@tquerec, @josephisenhour, @bongiovimatthew-microsoft as the owners of System.DirectoryServices, do you have an answer for the question posted above?

**Comment by tquerec** [comment]
I can answer for the DirectoryServices portion.  It's true that the Directory Services APIs in core are not supported on UWP.  This is because the underlying APIs the framework uses ( ADSI for example ) are not supported on UWP.

**Comment by carlossanlop** [comment]
Answered. Closing.

**Comment by CodCase** [comment]
> I can answer for the DirectoryServices portion. It's true that the Directory Services APIs in core are not supported on UWP. This is because the underlying APIs the framework uses ( ADSI for example ) are not supported on UWP.

Would be awesome to get this back, we was building a uwp app for this but stopped now because its not possible to use things like System.DirectoryServices
