### ISSUE TITLE
would not download

### ISSUE THREAD

**Issue by lCoderbossl** [dotnet/core#2908]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
I've confirmed the links on Windows for hello-world-tutorial/install are working fine so will need for you to elaborate on your system and exactly what you're doing and seeing.

**Comment by Keinkil** [comment]
The download links do not work for me either using Mozilla Firefox 67.
However, Google Chrome 75 works fine.

System:
Win10 Pro N
i7 6700K
nVidia GTX 980Ti
16GB RAM

**Comment by carlossanlop** [comment]
I can also confirm the download works fine. I'm closing the issue as resolved, but feel free to reopen it if you have any more questions.
