### ISSUE TITLE
Nuget.config - relative paths not working with dotnet restore

### ISSUE THREAD

**Issue by radekpribyl** [dotnet/core#291]
Hi all,
I'm not sure if the issue is .net core cli or nuget issue but I will try to start here. Our intention is have a shared folder where all nuget packages are restored to. The folder should be referenced relatively as each developer may sync the code from source control into a different folder. We followed instructions available at https://docs.nuget.org/ndocs/schema/nuget.config-file.md 
Let's say we have the following folder structure:

``` txt
D:\TST
└───f1
     └───f2
```

and in folder TST we have nuget.config file. The content of the file is:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="globalPackagesFolder" value="packages" />
    </config>
    <packageSources>
        <clear />
        <add key="nuget v3" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>
```

Based on this config file I would expect the packages to be restored into "packages" folder as outlined:

``` txt
D:\TST
├───f1
│   └───f2
└───packages
```

however when running dotnet restore from within the "f2" directory the packages folder is created there and the structure looks like:

``` txt
D:\TST
└───f1
    └───f2
        └───packages
```

It means that the "packages" folder is specific to a project and cannot be shared. We tried several ways of defining the relative path e.g. "./packages" but nothing worked. When specifying the path as absolute one it works fine. 

So is it a problem of dotnet restore or nuget? We are using dotnet core 1.0.0-preview2-003131 

Thanks for any suggestion.
Radek

**Comment by Petermarcu** [comment]
@piotrpMSFT @rrelyea , should this be opened in the cli or nuget repo?

**Comment by piotrpMSFT** [comment]
This should go to the nuget repo. FWIW, in the CLI repo we use relative paths to specify local package feeds, but set the packages folder using the NUGET_PACKAGES environment variable. I'm curious to see how the NuGet.config option works.

**Comment by Petermarcu** [comment]
Can you move it over there, reference this issue and close this issue?

**Comment by radekpribyl** [comment]
Closing as I moved it to nuget
