### ISSUE TITLE
Npgsql Client Certificates not working on Linux

### ISSUE THREAD

**Issue by rgause** [dotnet/core#2911]
# Issue Title

Npgsql Client Certificates not working on Linux

# General

.Net Core version: 2.1 & 2.2

When making a PostgreSQL connection, I need to use a Client Certificate generated by the DBA’s.

The connection works successfully when run on Windows and Mac, but not on Linux. The error in Linux is “connection requires a valid certificate”. Same code & pfx file on all 3 platforms.

I’ve tried it in Ubuntu 14 & 16 and I get the same results.

I will upload the code I used later today.

Thanks,
Bob

**Comment by rgause** [comment]
I’ve attached a small console app that helps to demonstrate the issue. Runs fine on Windows - fails on Linux.

Here is the log I kept from building the Ubuntu 16.04 image for testing:

1. Install Base OS + SSH Server + Postgres
2. Add the secondary NIC so that we can connect with SSH & Postgres
  a. Use ifconfig -a to list out all the interfaces
  b. Add missing interfaces to /etc/network/interfaces
3. Postgres Config & SSL Setup
  a. su or sign in as the postgres user
  b. Server Cert - (see https://www.postgresql.org/docs/9.5/ssl-tcp.html for this example)
    i. cd /var/lib/postgresql/{postgres version number}/main
    ii. openssl req -new -x509 -days 365 -nodes -text -out server.crt -keyout server.key -subj "/CN=`hostname`"
    iii. chmod og-rwx server.key
    iv. openssl req -new -nodes -text -out root.csr -keyout root.key -subj "/CN=root"
    v. chmod og-rwx root.key
    vi. openssl x509 -req -in root.csr -text -days 3650 -extfile /etc/ssl/openssl.cnf -extensions v3_ca -signkey root.key -out root.crt
    vii. openssl req -new -nodes -text -out server.csr -keyout server.key -subj "/CN=ubuntu-16"
    viii. openssl x509 -req -in server.csr -text -days 365 -CA root.crt -CAkey root.key -CAcreateserial -out server.crt
  c. Server Config - check the following values to insure they are correct:
    i. ssl_cert_file
    ii. ssl_key_file
    iii. ssl_ca_file
    iv. ssl_crl_file
    v. check the listen_addresses - needs to be '*'
  d. Server Listener Config
    i. Rem out the "host md5" entry
    ii. Add a "hostssl md5 clientcert=1" entry
  e. Client Cert
    i. cd /var/lib/postgresql/{postgres version number}/main 
    ii. openssl genrsa -des3 -out /tmp/postgresql.key 1024
    iii. openssl rsa -in /tmp/postgresql.key -out /tmp/postgresql.key
    iv. openssl req -new -key /tmp/postgresql.key -out /tmp/postgresql.csr -subj '/C=US/ST=Wisconsin/L=De Pere/O=rgause@express-scripts.com/CN=rgause <mailto:Pere/O=rgause@express-scripts.com/CN=rgause> '
    v. openssl x509 -req -in /tmp/postgresql.csr -CA root.crt -CAkey root.key -out /tmp/postgresql.crt -CAcreateserial
    vi. copy off the key & crt files from /tmp to another location - /tmp gets cleared on reboot
  f. Create the Client pfx file from the cert - .Net Core uses certs in PFX format
    i. openssl pkcs12 -export -out pg-client-cert-104.pfx -inkey postgresql.key -in postgresql.crt
4. .Net Core install
  a. Check pre-requisites - https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
  b. Install per details by distro - https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current
5. Test DB
  a. As the postgres user, run psql with the following commands:
    i. CREATE USER simple WITH PASSWORD 'simon';
    ii. CREATE DATABASE simple_db;
    iii. GRANT ALL PRIVILEGES ON DATABASE simple_db TO simple;
    iv. CREATE SCHEMA simple AUTHORIZATION simple;
    v. CREATE TABLE simple.simple
(
   id bigserial NOT NULL PRIMARY KEY,
   name character varying(40) NOT NULL,
   notes text
);
    vi. INSERT INTO simple.simple (name, notes) VALUES ('test1', 'this is a note');
    vii. INSERT INTO simple.simple (name, notes) VALUES ('test2', 'this is another note');
    viii. \q to exit
6. Test App from Windows & Linux

[pg-test-console.zip](https://github.com/dotnet/core/files/3308533/pg-test-console.zip)

**Comment by carlossanlop** [comment]
Hello @rgause, thanks for taking the time to report this issue.

Would you mind sharing the exception your code is throwing?

I suspect this issue is caused by missing configuration for PostgreSQL or for the [npgsql library ](https://github.com/npgsql/npgsql)you are using to connect to the database.

I found this link with the same error message and a provided solution. Maybe you have the same issue? Can you see if this helps?
https://stackoverflow.com/questions/18497299/psql-fatal-connection-requires-a-valid-client-certificate

**Comment by carlossanlop** [comment]
Adding @divega who owns the System.Data area in case this is an actual issue on the .NET side.

**Comment by rgause** [comment]
Here is the stack trace:

6/20/2019 12:45:21 PM [APP/PROC/WEB/0] at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
6/20/2019 12:45:21 PM [APP/PROC/WEB/0] Npgsql.PostgresException (0x80004005): 28000: connection requires a valid client certificate
6/20/2019 12:45:21 PM [APP/PROC/WEB/0] Connection id "0HLNLKPS5O2BT", Request id "0HLNLKPS5O2BT:00000001": An unhandled exception was thrown by the application.
6/20/2019 12:45:21 PM [APP/PROC/WEB/0] [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]

**Comment by rgause** [comment]
The stackoverflow link references an issue with psql - psql actually works fine, as does a Java app hitting the same database from all 3 platforms.

Again, the code attached runs fine on Windows & Mac, but fails on Linux. Exact same code, exact same config.

My guess is that it is either a bug, or that it was not implemented on Linux.

**Comment by divega** [comment]
cc @roji who is the Npgsql lead. Shay, does this ring any bells?

**Comment by roji** [comment]
Hmm, not really... Npgsql doesn't actually do much here - it simply passes the user-provided delegate to `SslStream.AuthenticateAsClient()`, [the code can be seen here](https://github.com/npgsql/npgsql/blob/68147c48df71206a96fed0e619237bc5855d80b4/src/Npgsql/NpgsqlConnector.cs#L548).

If this exact same code does work against the same database when running on Windows/MacOS, and only fails on Linux, then there's a chance we have an issue... I can try to repro sometime next week but won't have much added value beyond the PostgreSQL setup steps.

**Comment by rgause** [comment]
Just had a successful run on OpenSuse Tumbleweed.

I’m going to try several others and see what I get - I thinking Ubuntu 18, then CentOS.

Ubuntu 16 is the latest I have available in the problem environment, but thinking 18 is coming down the road. I know we have some Red Hat, too, so trying Cent to get an idea on that.....

**Comment by roji** [comment]
Thanks for testing and for the updates @rgause, please keep this issue up to date with your findings!

**Comment by rgause** [comment]
Sorry, OpenSuse Tumbleweed did not work. I had had issues with its local firewall and had added a line in pg_hba.conf to help with debugging that. Once I removed that line, the Linux run failed while the Windows run succeeded.

I also finished testing Ubuntu 18 today - it also fails on the Linux run.

CentOS 7 image build is in progress......

**Comment by roji** [comment]
Post back on the CentOS situation, but the tendancy seems clear :) I'll try to make time to repro this myself and investigate.

**Comment by rgause** [comment]
CentOS also has a similar failure. Only difference was that CentOS7 could not seem to install lttng-ust. It only seems to be for user space tracing & I've had similar results with or without that lib on other distros, so I kept going.

Stacktrace is similar:

[rgause@centos-7 pg-test-console]$ dotnet run

Unhandled Exception: Npgsql.PostgresException: 28000: connection requires a valid client certificate
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1003

**Comment by carlossanlop** [comment]
Npgsql is third party, we don't own it. @rgause please share a small repro that does not go through a 3rd party library.
cc @roji

**Comment by carlossanlop** [comment]
@roji if you think this issue is on our side, please reopen it. Otherwise, a bug should be opened for npgsql.
