### ISSUE TITLE
i am getting api-ms-win-crt-runtime-l1-1-0-dll is missing warning when typing dotnet in command prompt 

### ISSUE THREAD

**Issue by jaswanth3014** [dotnet/core#2913]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
This means you're missing required updates (prerequisites to run .NET Core), take a look at https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies.

**Comment by dagood** [comment]
Duplicate of #2541
