### ISSUE TITLE
Is it possible to create WPF or WinForms Class Library

### ISSUE THREAD

**Issue by groogiam** [dotnet/core#2916]
I have a couple of .NET Framework class library projects which provide reusable functionality for WPF and Winforms. These projects currently do so by referencing the .NET Framework assemblies like WindowsBase.dll or System.Windows.Forms. I cannot figure out how to replicate this using .NET Core 3 Preview 6. I tried referencing the Microsoft.WindowsDesktop.App package but got the following error. Is this supported? It seems like it should be.

`NU1202	Package Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)`

**Comment by carlossanlop** [comment]
@ericstj @joperezr is this an issue you can help with? It's related to .NET version. Let me know if we should instead transfer the issue to the wpf or winforms repos.

**Comment by ericstj** [comment]
You can create a class library that uses the WindowsDesktop SDK.

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <!-- use one of the following or both -->
    <UseWindowsForms>true</UseWindowsForms>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

</Project>
```

Essentially it's the same as `dotnet new winforms` or `dotnet new wpf` with `<OutputType>WinExe</OutputType>` removed.

@diverdan92 do you know if class-library templates are planned for WPF and WinForms?

**Comment by groogiam** [comment]
That seems to do the trick. Thanks for the help.

**Comment by carlossanlop** [comment]
This issue seems to be resolved, so I'm closing it. @groogiam if you need more assistance, feel free to create a new issue, we'll be happy to help.
