### ISSUE TITLE
can't find .net core on visual studio 2015

### ISSUE THREAD

**Issue by tacko98** [dotnet/core#2920]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
VS 2017 is the minimum version required to run .NET Core, or you can use Visual Studio Code.
Here's more information: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x
