### ISSUE TITLE
unmet dependencies in installing dotnet sdk 2.2 on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by NagalakshmiVJ** [dotnet/core#2922]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by carlossanlop** [comment]
Similar to this issue reported around the same time: https://github.com/dotnet/core/issues/2927

@Pilchie  can you please take a look?

**Comment by dagood** [comment]
The title says you're on Ubuntu 16.04, but the issue description says Ubuntu 19.04. Can you try again with the 16.04 instructions? https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current

**Comment by James4real888** [comment]
I'm on Android Version 9, with a Huawei P20 Pro, CLT-L04 (Cellphone), build
number 9.0.0.283, EMUI Version 9.0.0

**Comment by Pilchie** [comment]
@leecow can you help with this?

**Comment by leecow** [comment]
19.04 repo confirmed good. Check your repo registration and make sure it's pointed to the correct endpoint. It should look like this. 

```
$ cat /etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod disco main
```

**Comment by dagood** [comment]
Based on the submitter's post title edit, they're on Ubuntu 16.04, not 19.04, and this error is expected if someone tries to run 19.04 instructions on 16.04. I'm closing because we haven't heard back in about a week since I suggested running the instructions that match the distro version.

@NagalakshmiVJ, let us know if you're still running into this issue!
