### ISSUE TITLE
Consuming the latest nightly is impossible due to missing package Microsoft.AspNetCore.App.Ref

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/core#2924]
# General
I've installed the nightly SDK for `3.0.100-preview7-012564`, however attempts to build projects with the preview SDK fails with the following error:
```cs
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Microsoft.AspNetCore.App.Ref with version (= 3.0.0-preview7.19322.1)
  - Found 28 version(s) in dotnetcore-feed [ Nearest version: 3.0.0-preview4-19121-14 ]
  - Found 4 version(s) in NuGet [ Nearest version: 3.0.0-preview6.19307.2 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in dotnet.myget.org roslyn
```

I have followed the [Dogfooding daily builds instruction on corefx repo](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) and just created a new console project; I'm not sure if I'm missing any other steps.
```cs
using System;
using System.Globalization;

namespace ConsoleApp23
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by dagood** [comment]
Looks like you're missing the NuGet feeds required by the SDK daily build: https://github.com/dotnet/core-sdk#installers-and-binaries.

**Comment by Gnbrkm41** [comment]
Ah, thought I'd need only one of it... I believe that'd solve the issue.
