### ISSUE TITLE
apt-get install aspnetcore-runtime-2.2

### ISSUE THREAD

**Issue by jaggedjagged** [dotnet/core#2927]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

# apt-get install aspnetcore-runtime-2.2
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 aspnetcore-runtime-2.2 : Hängt ab von: dotnet-runtime-2.2 (>= 2.2.5) soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by carlossanlop** [comment]
Translation:

> Reading package lists... ready
> Dependency tree is being built.
> Reading in status information.... ready
> Some packages could not be installed. This may mean that
> you have requested an impossible situation or, if you have requested the
> unstable distribution that some required packages are still
> have not been created or have not yet left Incoming.
> The following information may help you solve the situation:
> 
> The following packages have unfulfilled dependencies:
> aspnetcore-runtime-2.2 : Depends on: dotnet-runtime-2.2 (>= 2.2.5) but should not be installed
> E: Problems cannot be corrected, you have retained defective packages.

@Pilchie can you please take a look?

**Comment by carlossanlop** [comment]
Similar to this issue reported around the same time: https://github.com/dotnet/core/issues/2922

**Comment by Pilchie** [comment]
@leecow any ideas?

**Comment by techiechap** [comment]
Hii It might be cause of the repos, pls check below url
https://github.com/dotnet/core/issues/2940

**Comment by techiechap** [comment]
You can open firefox, download the script [microsft](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) 
and see if its getting installed, or you can refer the [git](https://github.com/dotnet/core/issues/2940)

**Comment by leecow** [comment]
Confirmed again that all is well with the 18.04 repo. @techiechap's recommendation to follow the guidance in [#2940](https://github.com/dotnet/core/issues/2940) is a good next step.

**Comment by Pilchie** [comment]
Closing due to lack of response.

**Comment by jaggedjagged** [comment]
Thanks a lot!
I was on vacation. Now the installation worked without this error.
