### ISSUE TITLE
Fail to install dotnet-dev-osx-x64.1.0.0-preview2-003131 on macOS Sierra 10.12

### ISSUE THREAD

**Issue by z2xlong** [dotnet/core#293]
The official installer dotnet-dev-osx-x64.1.0.0-preview2-003131.pkg can't be installed to macOS sierra, how to fix it? where can I find the error log?

**Comment by leecow** [comment]
Hi @z2xlong - We've just released an [updated installer for macOS](https://go.microsoft.com/fwlink/?LinkID=831679). Give it a try and let me know if it resolves the issue.

**Comment by z2xlong** [comment]
The new version works fine, thanks.
