### ISSUE TITLE
ResX generator - 'Type' does not contain a definition for 'Assembly'

### ISSUE THREAD

**Issue by Evangelink** [dotnet/core#2930]
Hi there,

I have a library project with a multi target `<TargetFrameworks>net45;net47;netstandard1.3;netstandard1.6;netstandard2.0;netcoreapp2.0</TargetFrameworks>` and when I am trying to add a resx file to handle some translations I start having the following issue:

```
Error CS1061 'Type' does not contain a definition for 'Assembly' and no accessible extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
```

I have read on issue #595 that to get the `Assembly` we need to get through `GetTypeInfo()` but I would expect the `ResXFileCodeGenerator` to take care of that automatically.

Am I missing something? Or doing something wrong?

**Comment by Evangelink** [comment]
I can confirm that if I create a new netstandard class library and add a resx (keeping only `<TargetFramework>netstandard1.3</TargetFramework>`) everything works fine but as soon as I add the `net45` as multi-target (`<TargetFrameworks>net45;netstandard1.3</TargetFrameworks>` I start having the designer generated properly only for net45.

**Comment by 0xd4d** [comment]
Seems like it only happens if you have net45 as the first TFM, so move it to the 2nd position or later. Delete the *.designer.cs file and regenerate it (edit any field in the .resx file and save it)

**Comment by carlossanlop** [comment]
@ericstj @joperezr since it's related to .NET versions, maybe it's your area of expertise. Can you help? If not, please let me know who can help with this.
Adding @adamsitnik as well, since he helped in the referenced issue https://github.com/dotnet/core/issues/595.

**Comment by ericstj** [comment]
I believe this is a problem with the code-generator for the resources.designer.cs.  It's not handling multi-targeting.  It needs to consider all frameworks targeted by the project, not just the first.  @dmonroym  @davkean does the Designer.cs code generator live in the project system or winforms?

**Comment by davkean** [comment]
We don't have a lot of control over this - the relationship we have with the code gen doesn't give us the ability to say "factor in all these TFMs". @Tanya-Solyanik did the original hook for us and they own it in the Framework itself and that would be need to be extended. Once .NET Standard 1.x and portable usage is reduced, this issue will start going away.

**Comment by Evangelink** [comment]
Sorry to get back to you that late. I do confirm that by putting one of the `netstandard` first everything works well.

I still decided to create this ticket hoping you could find a way to improve the UX for others. Feel free to close if you don't think that you can have some easy win.

**Comment by carlossanlop** [comment]
Thanks @Evangelink, I'll close the issue. @davkean feel free to reopen it if you want to add more information.
