### ISSUE TITLE
System.TypeLoadException: Could not load type 'System.Diagnostics.Eventing.EventDescriptor' from assembly  'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

### ISSUE THREAD

**Issue by singhkamall** [dotnet/core#2933]
I used following code to execute commands on Exchange Online for creating a new mailbox

```c#
void Create(CreateMailboxInput input)
{
    Command myCommand = new Command("New-MailBox");
    myCommand.Parameters.Add("Name", input.Name);

    List<Command> commands = new List<Command>() { myCommand };
    ExecuteCommand(commands);
}
```

```c#
public static Collection<PSObject> ExecuteCommand(List<Command> commands)
{
    string pass = Utility.AppSettings.ExchangeAppSettings.Password;
    System.Security.SecureString securePassword = new System.Security.SecureString();

    foreach (char c in pass.ToCharArray())
    {
        securePassword.AppendChar(c);
    }

    PSCredential newCred = new PSCredential(Utility.AppSettings.ExchangeAppSettings.Mailbox);

    WSManConnectionInfo connectionInfo = new WSManConnectionInfo(
        new Uri("https://outlook.office365.com/PowerShell-LiveID"),
        "http://schemas.microsoft.com/powershell/Microsoft.Exchange",
        newCred);

    connectionInfo.AuthenticationMechanism = AuthenticationMechanism.Basic;

    Runspace myRunSpace = RunspaceFactory.CreateRunspace(connectionInfo);
    myRunSpace.Open();

    Collection<PSObject> result = new Collection<PSObject>();
    foreach (var command in commands)
    {
        Pipeline pipeLine = myRunSpace.CreatePipeline();
        pipeLine.Commands.Add(command);
        result = pipeLine.Invoke();
    }

    myRunSpace.Close();
    return result;
}
```

It works perfectly in .NET Framework application but when I try to execute it in a ASPNET Core application, it fails. It gives following error-

```
> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Runspaces.RunspaceFactory' 
threw an exception. ---> System.TypeLoadException: Could not load type 'System.Diagnostics.Eventing.EventDescriptor' from assembly 
'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.Management.Automation.Runspaces.RunspaceFactory..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(RunspaceConnectionInfo connectionInfo)
   at ConsolePS.ExchangeOnlinePS.ExecuteCommand(List`1 commands) in C:\Projects\ConsolePS\ExchangeOnlinePS.cs:line 30
```

Any thoughts on how this can be resolved?

**Comment by carlossanlop** [comment]
@Pilchie the issue is happening in ASP.NET, is this something your team can address or should it be sent to another area?

**Comment by Pilchie** [comment]
@carlossanlop This doesn't appear to have anything to do with ASP.NET?  It's Exchange automation using WMI...

**Comment by Pilchie** [comment]
@carlossanlop This appears to be Exchange automation with WMI - nothing to do with ASP.NET>

**Comment by karelz** [comment]
@Anipik can you please take a look? Should we move it to CoreFX?

**Comment by karelz** [comment]
@singhkamall are you able to reproduce it in HelloWorld-style app? (console app ideally)

**Comment by Anipik** [comment]
sure i will take a look

**Comment by Anipik** [comment]
@singhkamall can you tell me the version of .net core you are running on ?

**Comment by singhkamall** [comment]
@karelz Yes, I can reproduce it in console app also.

**Comment by singhkamall** [comment]
@Anipik Its .NET Core 2.2

**Comment by Anipik** [comment]
> Could not load type 'System.Diagnostics.Eventing.EventDescriptor' from assembly 
'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

This type is not available in .Net Core 2.2 and is only available 3.0 preview 4 and upwards

**Comment by singhkamall** [comment]
Any work around for .NET Core 2.2?
When will .NET Core 3.0 stable version will be releasing?

**Comment by Anipik** [comment]
> Any work around for .NET Core 2.2?

cc @ericstj @danmosemsft 

> When will .NET Core 3.0 stable version will be releasing?

Release of 3.0 GA is expected in Sept.

**Comment by Anipik** [comment]
@singhkamall On a secondary look at the exact type name. This type  ```System.Diagnostics.Eventing.EventDescriptor```  is not present on .NET core 3.0.
 I will check why we didn't ported this api when we ported the other eventing apis.
But for the time being, you wont be able to use this api on .NET core.

**Comment by Anipik** [comment]
Created a new issue in corefx to track why we didn't port these apis in dotnet core. https://github.com/dotnet/corefx/issues/39670

**Comment by Anipik** [comment]
@singhkamall just to let you know we wont be adding eventDescriptor types in .net core as they are older functionality of writing code. You should be using eventsources to do writing.

**Comment by singhkamall** [comment]
@Anipik Appreciate the update.

I am not working with `EventDescriptor` directly but I'm using `RunspaceFactory` and looking at stack trace it seems like eventDescriptor is used in its constructor. Does it means `System.Management.Automation.Runspaces.RunspaceFactory` is also not supported?

Not sure how else I can execute commands for automation of Exchange Online without it. Any idea in regards to that?

**Comment by ericstj** [comment]
Looks like that assembly comes from Powershell and is implemented here: https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/hostifaces/ConnectionFactory.cs#L17  Maybe follow up with powershell team?  I think they have a version of that library that works on .NETCore. @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@singhkamall, please try https://www.nuget.org/packages/Microsoft.PowerShell.SDK which is .NET Core compatible.

**Comment by BrayanKhosravian** [comment]
I noticed this issue as well in net5.
Then I changed the target platform from net5 to core3.1.

I noticed that i get the following error in core3.1.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8830	'App.AChild.GetB()': Target runtime doesn't support covariant return types in overrides. Return type must be 'App.B<string>' to match overridden member 'App.A<string>.GetB()'	...App.xaml.cs	38	Active
```

I wonder if this should be supported in net5 and if this error check is missing.

**Comment by matteotrapani** [comment]
Hi all,

I'm sorry to write under this closed issue, but I have a similar issue which I can't come over with.

I'm working on a ASP.NET Core 3.1 solution which references Nuget packages from the client feed.
These nuget packages are using .Net Framework 4.7 and are referenced in projects targeting .NetStandard 2.0.

The problem is that the client nuget packages use some code from namespace System.Diagnostics.Eventing.EventDescriptor and I have the same error as first described from @singhkamall .

Have you or someone else found a solution?

Thank you in advance

**Comment by Pilchie** [comment]
As @Anipik said [above](https://github.com/dotnet/core/issues/2933#issuecomment-514719334), that type is not available in .NET Core.  You'll need to update that dependency to a version which supports .NET Core 3.1.
