### ISSUE TITLE
2.2.107 SDK is not available on Microsoft Debian package repository

### ISSUE THREAD

**Issue by dagood** [dotnet/core#2934]
@dungam reported at https://github.com/dotnet/core/issues/2879#issuecomment-505241984 how our notice for MonoDevelop users points to instructions that don't work:

> Here is how I got the same error message
> 
> I downloaded a project targeting .Net Core 2.1
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>    
>     <TargetFramework>netcoreapp2.1</TargetFramework>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <Compile Remove="Example.cs" />
>   </ItemGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.1" />
>     <PackageReference Include="xunit" Version="2.4.1" />
>     <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> Upon trying to build the project in Monodevelop 7.3.3 (build 5), I got an error asking me to install .Net 2.0 SDK
> 
> ```
> Error: .NET Core 2.0 SDK is not installed. This is required to build .NET Core 2.0 projects.
> https://aka.ms/vs/mac/install-netcore2
> ```
> 
> The url in error message redirects to https://dotnet.microsoft.com/download for latest versions. This page has instructions for Monodevelop users to install NET Core SDK 2.2.107
> 
> ```
> This SDK version has known issues with MonoDevelop.
> If you use MonoDevelop, you should install install .NET Core SDK 2.2.107.
> ```
> 
> Ubuntu 18.04 users finally land on the URL https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.107. All instructions on this page resolve to the error message
> 
> ```
> $ sudo apt install  dotnet-sdk-2.2.107=2.2.107-1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package dotnet-sdk-2.2.107
> E: Couldn't find any package by glob 'dotnet-sdk-2.2.107'
> E: Couldn't find any package by regex 'dotnet-sdk-2.2.107'
> ```

---

I see two problems here:

1. There is no `dotnet-sdk-2.2.107` package on the Microsoft package repository.
1. ~The command on the install instructions says to install `dotnet-sdk-2.2.107=2.2.107-1`, but I *think* it should say `dotnet-sdk-2.2=2.2.107-1`. (Although that package doesn't exist either.)~ (Edit: This is now fixed.)

@leecow, thoughts? Should we direct users to install from binaries in this case?

Related, discussion about which major/minor trains we release packages for: https://github.com/dotnet/core/issues/2825

**Comment by leecow** [comment]
I've updated all repos to include 2.2.107 to unblock anyone having difficulty with MonoDevelop. Should be available in an hour or so after the repo indexes update.

**Comment by carlossanlop** [comment]
@leecow @dagood closing, seems @leecow resolved it.
