### ISSUE TITLE
netcoreapp2.2 windows : Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run

### ISSUE THREAD

**Issue by tedyyu** [dotnet/core#2935]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

c:\hands-on\\.NETCore\myConsoleApp>dotnet run

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'c:\hands-on\\.NETCore\myConsoleApp\bin\X86\Debug\netcoreapp2.2\myConsoleApp.dll'. An attempt was made to load a program with an incorrect format.

**Comment by carlossanlop** [comment]
Sounds like this issue is related to the fact that you compiled your app in X86 but running it in X64, although I don't know why the exception would be thrown.
@nguerrera @livarcocc can you please help @tedyyu with this problem?

**Comment by nguerrera** [comment]
I suspect something in your environment or directory structure is forcing the wrong architecture.

Can you provide a binary log? See https://aka.ms/binlog, in particular make note that this will share project contents and environment variables.

To generate it for this tutorial project, you can use `dotnet build /bl` and it will produce an msbuild.binlog file.

**Comment by tedyyu** [comment]
[msbuild.binlog.zip](https://github.com/dotnet/core/files/3328078/msbuild.binlog.zip)

@nguerrera Here is the binlog, please help.

**Comment by tedyyu** [comment]
any findings? @nguerrera @livarcocc

**Comment by carlossanlop** [comment]
@tedyyu can you try this on 3.0 Release? Closing. Feel free to open a new issue if you are still seeing problems.
