### ISSUE TITLE
Can't install Dot Net Core on CentOS 7

### ISSUE THREAD

**Issue by DRepinSLB** [dotnet/core#2939]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-2.1.300
Operating System: Linux CentOS / Oracle - x64

```
drepin@viz-json-build-agent:~$ more /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
As directed, I am trying to add the dotnet product feed, but see Failed dependencies: /bin/sh is neede
```
drepin@viz-json-build-agent:~$ sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
Retrieving https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
warning: /var/tmp/rpm-tmp.5b9Lmj: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
error: Failed dependencies:
        /bin/sh is needed by packages-microsoft-prod-1.0-1.el7.noarch
```
However
```
drepin@viz-json-build-agent:~$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Feb 17  2016 /bin/sh -> dash
```

**Comment by omajid** [comment]
This is strange. `/etc/os-release` says you are using `ubuntu`. And Ubuntu (not CentOS) has `/bin/sh` as a symlink to `/bin/dash`. But the title says CentOS. And you are using the CentOS/RHEL package feeds. Can you double check what your OS is? CentOS/RHEL feeds are not going to work on Ubuntu. Have you tried following the steps for Ubuntu?

**Comment by DRepinSLB** [comment]
Sorry. User error. My VM is CentOS 7, while the build machine is Ubuntu, as you rightfully noticed. Please close the issue.
