### ISSUE TITLE
Dotnet cli installation error on WSL

### ISSUE THREAD

**Issue by techiechap** [dotnet/core#2940]
Problem encountered on while installing the dotnet cli on wsl ubuntu,
WSL:Ubuntu 18.04.1 LTS

> The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by dagood** [comment]
What instructions were you following? The most common reason for this error is using a package repository that doesn't match your distro or release number.

If that doesn't help, can you run these diagnosis steps and share the results?

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

**Comment by techiechap** [comment]
Thanks dagood, 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Below are my repos 

/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic universe
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ bionic-security universe
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ bionic-security multiverse
/etc/apt/sources.list:deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
/etc/apt/sources.list:deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
/etc/apt/sources.list.d/dotnetdev.list:deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
/etc/apt/sources.list.d/sublime-text.list:deb https://download.sublimetext.com/ apt/stable/

**Comment by dagood** [comment]
Good start, a few questions you missed:

> What instructions were you following?
 
> ```
> # This install command will show exactly which dependency can't be met.
> sudo apt-get install dotnet-runtime-deps-2.2
> ```

**Comment by techiechap** [comment]
My apologies,  below is the output,

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libicu55 but it is not installable

**Comment by techiechap** [comment]
ashish@Latitude7470:~$ dotnet --list-sdks
2.2.300 [/usr/share/dotnet/sdk]

I found the solution here  [github](https://github.com/dotnet/core/issues/1587)
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.4_amd64.deb -P /tmp
sudo dpkg -i /tmp/libicu55_55.1-7ubuntu0.4_amd64.deb

**Comment by techiechap** [comment]
Thank you dagood,

**Comment by dagood** [comment]
This source is unusual:

> `/etc/apt/sources.list.d/dotnetdev.list:deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main`

Xenial is Ubuntu 16.04, so I'm betting it's finding the 16.04 `dotnet-runtime-deps`, not the 18.04 `dotnet-runtime-deps`. This would explain why it's asking for `libicu55` rather than `libicu60`. If you removed that source, your install command would probably pick up the right packages from the correct source (which you also have installed):

> `/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main`

You've already worked around it, but you might want to get rid of the weird source to avoid more mismatches in the future.
