### ISSUE TITLE
ResXFileCodeGenerator/StronglyTypedResourceBuilder generates classes without the 'partial' modifier

### ISSUE THREAD

**Issue by jeroenlandheer** [dotnet/core#2943]
When generating a class with from a resources (.resx) file, the resulting class in the .Designer.cs is either an internal or public class, without the 'partial' keyword. 

If you want to implement some additional code in these files (i.e. make a few extra methods that are related to resources in that same project) they are overwritten whenever the resource file is changed, removing the changes. 

If the generator adds the 'partial' keyword to the class, we can make these items in a different file without having to resort to extension methods.

**Comment by carlossanlop** [comment]
@davkean do you know if this is an issue that the project system team could help with?

**Comment by carlossanlop** [comment]
@jeroenlandheer you might get better traction if you report this issue on Visual Studio User Voice. Closing since there's no follow up.

**Comment by jeroenlandheer** [comment]
@carlossanlop  I'll mention this in the product feedback, thanks. (User Voice has been closed for Visual Studio.)

**Comment by mamift** [comment]
Did anything come of this? This would be super helpful!

**Comment by ViRuSTriNiTy** [comment]
The partial keyword is also needed when you want to use the designer file in connection with a Blazor component. Here you would typically name the files like

- `MyComponent.resx`
- `MyComponent.razor` 

and when activating the designer file generation for `MyComponent.resx` you end up with the following file structure

- `MyComponent.resx`
- `MyComponent.Designer.cs`
- `MyComponent.razor` 

but in `MyComponent.Designer.cs` the missing partial keyword on the generated `MyComponent` class results in a compiler error as the compiler also generates a `MyComponent` class for `MyComponent.razor`.
