### ISSUE TITLE
dotnet sdk installation error on WSL ubuntu

### ISSUE THREAD

**Issue by techiechap** [dotnet/core#2946]
Error thrown while installing dotnet for  linux
Operating System: Windows 10 WSL  Ubuntu 18.04 - x64

Below error is shown,however when i run dotnet.exe it seems showing the output.

2.1.505 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]

while installing the dotnet sdks from [https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current]   i get below error

> The following packages have unmet dependencies
dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.11) but it is not going to be installed
 Depends: aspnetcore-runtime-2.1 (>= 2.1.11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by dagood** [comment]
Looks like a duplicate of https://github.com/dotnet/core/issues/2940, let me know if not.

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/core/issues/2940

**Comment by techiechap** [comment]
Yes, its duplicate Thanks
