### ISSUE TITLE
Microsoft key

### ISSUE THREAD

**Issue by Stiles-Micaiah** [dotnet/core#2953]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Permission denied to get Microsoft key

**Comment by carlossanlop** [comment]
@Stiles-Micaiah in which step did you get that error? Was it a step that required "sudo"?

**Comment by Stiles-Micaiah** [comment]
@carlossanlop Hey sorry for the delay. i Dont remember exactly how i did it but i either restarted or reinstalled ubuntu and just kept doing the steps given on the site over and over and eventually it let me install.

**Comment by carlossanlop** [comment]
Okay, thanks for the clarification. I'll close the post as resolved.
