### ISSUE TITLE
daily builds don't include libsos

### ISSUE THREAD

**Issue by tmds** [dotnet/core#2956]
I downloaded today's daily build:
```
$ ./dotnet --version
3.0.100-preview7-012697
```
It doesn't include any sos:
```
$ find . -name '*sos*'
```

CC @mikem8361

**Comment by mikem8361** [comment]
Yes, SOS is not included in the runtime anymore.  It can be installed with these directions: https://github.com/dotnet/diagnostics#installing-sos.  Once it is installed, this SOS will work with 1.1, 2.x and 3.x runtimes.

**Comment by omajid** [comment]
Was this change made after preview 6? My source-build-based preview 6 builds have a `libsos.so` and I am trying to find out if I need to file a bug there.

**Comment by mikem8361** [comment]
Yes. It will be in Preview 7.

**Comment by omajid** [comment]
Thanks!
