### ISSUE TITLE
No new folder was created

### ISSUE THREAD

**Issue by mazharwhite** [dotnet/core#2957]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@mazharwhite can you provide details about your problem?

**Comment by mazharwhite** [comment]
i followed the setup for setting up when i ran the command nothing was created in the directory i was running the command also tried changing the directory file but alas still facing the same issue

**Comment by leecow** [comment]
@mazharwhite - Are you still having troubles? What OS are you on? I presume you're referring to these commands?

```
dotnet new webApp -o myWebApp --no-https
cd myWebApp
```

**Comment by karelz** [comment]
2 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
