### ISSUE TITLE
.NET Core 1.0 and 1.1 should be marked as EOL in releases-index.json

### ISSUE THREAD

**Issue by omajid** [dotnet/core#2962]
They are EOL since a few days ago and should no longer be in maintenance mode:

https://github.com/dotnet/core/blob/310b169c26d79cd352c338d4a0532ce48af862b6/release-notes/releases-index.json#L59

https://github.com/dotnet/core/blob/310b169c26d79cd352c338d4a0532ce48af862b6/release-notes/releases-index.json#L71

**Comment by carlossanlop** [comment]
@leecow I see you normally modify this file. Can you please take a look?

**Comment by omajid** [comment]
Both https://github.com/dotnet/core/pull/2974/ and https://github.com/dotnet/core/pull/2998/ include a fix for this.

**Comment by omajid** [comment]
Closing since https://github.com/dotnet/core/pull/2974 was merged.
