### ISSUE TITLE
Missing file information in stack trace with portable pdbs

### ISSUE THREAD

**Issue by pp1609** [dotnet/core#2969]
I am trying to get the line numbers and column numbers from stack trace in case of exception but if the debug type is selected as portable the file info is showing as unknown. If i changed the debugtype to pdbonly i can see the fileinfo details.

Kindly help.

**Comment by pp1609** [comment]
Can anyone please help with this

**Comment by carlossanlop** [comment]
@pp1609 what .NET Core version are you using? Can you provide a code example of what you're trying to do?

**Comment by karelz** [comment]
3 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
