### ISSUE TITLE
Azure CLI login failure

### ISSUE THREAD

**Issue by kylepeters** [dotnet/core#2975]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-deploy-microservice-tutorial/azure-resources
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Every time I attempt to use the >az login command, it launches a browser window for me to log in. After successful login via browser window, I get this error...
C:\>az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all the subscriptions to which you have access...
request failed: Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /tenants?api-version=2016-06-01 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by carlossanlop** [comment]
@Pilchie I am not sure if this is something for the ASP.NET team specifically, since the question is happening in Azure tools. Is this something your team would be able to address? If not, do you know who would be the best contact for this?

**Comment by Pilchie** [comment]
@Petermarcu any ideas?

**Comment by Petermarcu** [comment]
This is probably best opened here: https://github.com/Azure/azure-cli

**Comment by Pilchie** [comment]
This issue was moved to Azure/azure-cli#9898
