### ISSUE TITLE
Add a DataSource in Wpf Core

### ISSUE THREAD

**Issue by HADDADENICAR** [dotnet/core#2976]
Following a tutorial in Pluralsight about EF Core ,Julie Lerman the tutor used EF Core  with (.Net Framework) Wpf Project, I am trying to do the same but with Wpf (Core3).

I want to make my view fast with a dataSource, when i add a datasource from the domain model project , it's dosen't get added !

**Comment by carlossanlop** [comment]
Can you provide more details like a code example of what you're trying to do?

**Comment by carlossanlop** [comment]
This issue was moved to dotnet/wpf#1196
