### ISSUE TITLE
SocketException: Permission denied +Questions

### ISSUE THREAD

**Issue by Norc89** [dotnet/core#2978]
# Issue Title

Socket Exception

# General

Hi,
I'm new at the programing for raspberry at the moment i'm porting code from netduino to raspberry and i ran on problem with socketException: Permission denined. What can be the reason for this? I have try to change port to other and stil get the same problem. 

Just for info I'm running on dot net core 2.2.3. 

I have also question if is there any option to debug on raspberry and what is procedure to setup app that will run on raspberry each time when machine restart. 

Thanks.

**Comment by carlossanlop** [comment]
Can you provide more details?  What operating system is your raspberry pi running? Can we see a code example of what you're trying to do?

**Comment by karelz** [comment]
3 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
