### ISSUE TITLE
Fix latest.version file for 2.x and 3.x (outdated version)

### ISSUE THREAD

**Issue by alarco-l** [dotnet/core#2980]
I'm  trying to automate the dotnet sdk installation on a docker based on Ubuntu `18.04`.
Our goal is to be sure to always have the latest version of the sdk.
With the help of the [documentation](https://docs.microsoft.com/fr-fr/dotnet/core/tools/dotnet-install-script) and the `--help` option of the `dotnet-install.sh` script
```
.NET Tools Installer
Usage: dotnet-install.sh [-c|--channel <CHANNEL>] [-v|--version <VERSION>] [-p|--prefix <DESTINATION>]
       dotnet-install.sh -h|-?|--help


  -c,--channel <CHANNEL>         Download from the channel specified, Defaults to `LTS`.
          Possible values:
          - Current - most current release
          - LTS - most current supported release
          - 2-part version in a format A.B - represents a specific release
              examples: 2.0; 1.0
          - Branch name
              examples: release/2.0.0; Master
          Note: The version parameter overrides the channel parameter.
  -v,--version <VERSION>         Use specific VERSION, Defaults to `Latest`.
      -Version
          Possible values:
          - latest - most latest build on specific channel
          - coherent - most latest coherent build on specific channel
              coherent applies only to SDK downloads
          - 3-part version in a format A.B.C - represents specific version of build
              examples: 2.0.0-preview2-006120; 1.1.0
  -i,--install-dir <DIR>             Install under specified location (see Install Location below)
      -InstallDir
  --architecture <ARCHITECTURE>      Architecture of dotnet binaries to be installed, Defaults to `<auto>`.
      --arch,-Architecture,-Arch
          Possible values: x64, arm, and arm64
  --runtime <RUNTIME>                Installs a shared runtime only, without the SDK.
      -Runtime
          Possible values:
          - dotnet     - the Microsoft.NETCore.App shared runtime
          - aspnetcore - the Microsoft.AspNetCore.App shared runtime
  --skip-non-versioned-files         Skips non-versioned files if they already exist, such as the dotnet executable.
      -SkipNonVersionedFiles
  --dry-run,-DryRun                  Do not perform installation. Display download link.
  --no-path, -NoPath                 Do not set PATH for the current process.
  --verbose,-Verbose                 Display diagnostics information.
  --azure-feed,-AzureFeed            Azure feed location. Defaults to https://dotnetcli.azureedge.net/dotnet, This parameter typically is not changed by the user.
  --uncached-feed,-UncachedFeed      Uncached feed location. This parameter typically is not changed by the user.
  --no-cdn,-NoCdn                    Disable downloading from the Azure CDN, and use the uncached feed directly.
  --feed-credential,-FeedCredential  Azure feed shared access token. This parameter typically is not specified.
  --runtime-id                       Installs the .NET Tools for the given platform (use linux-x64 for portable linux).
      -RuntimeId
  -?,--?,-h,--help,-Help             Shows this help message

Obsolete parameters:
  --shared-runtime                   The recommended alternative is '--runtime dotnet'.
      -SharedRuntime                 Installs just the shared runtime bits, not the entire SDK.

Install Location:
  Location is chosen in following order:
    - --install-dir option
    - Environmental variable DOTNET_INSTALL_DIR
    - /root/.dotnet
```

I tried 
```
root@ff3bb56b7f4b:/# ./dotnet-install.sh -Channel Current -Version latest
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.204/dotnet-sdk-2.2.204-linux-x64.tar.gz

root@ff3bb56b7f4b:/# ./dotnet-install.sh -Channel 2.2 -Version latest
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.204/dotnet-sdk-2.2.204-linux-x64.tar.gz
```

As you can see, I didn't got the `2.2.300` version so I tried to directly got it to check if the version is on the cdn 
```
root@ff3bb56b7f4b:/# ./dotnet-install.sh -Channel Current -Version 2.2.300
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.300/dotnet-sdk-2.2.300-linux-x64.tar.gz
```

But that way, I can't automate it...

I decided to try with aspnet core version 3 
```
root@ff3bb56b7f4b:/# ./dotnet-install.sh -Channel 3.0 -Version latest
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview4-010988/dotnet-sdk-3.0.100-preview4-010988-linux-x64.tar.gz
^C
```
I got the `preview4` but there is actually `preview5` and `preview6`.

On other hand, on [dot.net download page](https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current) it say to use `apt-get install` and I got the `2.2.300` version.

* Should I use the script or the apt-get command in order to always be up to date?

* What's the delay for a version to be available on the [azure feed](https://dotnetcli.azureedge.net/dotnet) when is available on [dot.net](https://dotnet.microsoft.com/download/)  

* What did I missed on the script to have the latest version ?  

Thanks in advance for your response.

**Comment by carlossanlop** [comment]
@dagood is this something you can help with since it's related to install/setup?

**Comment by dagood** [comment]
> I'm trying to automate the dotnet sdk installation on a docker based on Ubuntu `18.04`.
> Our goal is to be sure to always have the latest version of the sdk.

You may be interested in https://github.com/dotnet/dotnet-docker depending on your scenario.

> * Should I use the script or the apt-get command in order to always be up to date?

For a typical user, apt-get, because `apt-get upgrade` works. There's no special commands needed to update the SDK vs. other packages.

If you're doing special automated upgrade stuff anyway, I believe either should be fine. But note that the script installs dotnet in a different way that's specifically suited for dev scenarios, especially when you don't have permission to install the `deb` package. For example, using `apt-get install` will set up `PATH` persistently for everyone, but `dotnet-install.sh` is per-user and only sets up `PATH` for the current running shell.

The right place for the questions specifically about `dotnet-install.sh` is https://github.com/dotnet/cli, I believe--that's [where the script lives](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh). Getting preview4 rather than preview6 definitely seems like a bug (potentially in the release process).

/cc @leecow

**Comment by alarco-l** [comment]
Thanks for your answers, do you want me to close this issue and open on it [https://github.com/dotnet/cli]( https://github.com/dotnet/cli) ?

**Comment by leecow** [comment]
dotnet-install is driven by values in a few different `latest.version` files. I missed updating that for 3.0-preview6.

@vivmishra - could you update https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0/latest.version to 

3.0.100-preview6-012264
99151dfa08364242d93c861568abaf044e134d8c

**Comment by vivmishra** [comment]
Following has been updated:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0/latest.version

**Comment by alarco-l** [comment]
Thanks a lot, I’m closing the issue.

**Comment by tebeco** [comment]
@vivmishra 
Hello,
It seems that is is still broken for `2.2` and `3.0` channel :

[2.2](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0/latest.version)
```
70d6be081437d5949d5661ca0c81f5de89079c6a
2.2.301
```

[3.0](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0/latest.version)
```
3.0.100-preview6-012264
99151dfa08364242d93c861568abaf044e134d8c
```

**Comment by carlossanlop** [comment]
@vivmishra @leecow can you followup on this?

**Comment by vivmishra** [comment]
Fixes were made -- let us know if anything still does not look right.

**Comment by tebeco** [comment]
weird to ask but....
as it's been the third time it happened, was the fix only targeting the value served ?
Or did it also fixes the release process, by that i mean "it should now be properly handle by an automation during a real. it should not happen ever again"

**Comment by leecow** [comment]
Not weird at all - this is, unfortunately, a manual task at the moment which is on our automation backlog.

**Comment by tebeco** [comment]
Good to know ;)

is their a ticket on github i can subscribe to ?
Our CI unfortunately cannot access github.com, so we like the `dotnet-install.ps1`

the issue is that for now we manually have to change the `-Version 1.2.3` on every sdk release.
the default value use `Latest`, which leads to this file
so `dotnet-install.ps1` cannot be trusted with `Latest` :(

**Comment by tebeco** [comment]
hello @leecow 

Do you know if this is a supported scenario ?

If so, do you know when this will be automated ?
![image](https://user-images.githubusercontent.com/2266487/99128444-16908d80-260b-11eb-8f2b-2ddea9ad4d23.png)

It sees impossible today to use `latest` or `channel` to get the `5.0.x` SDK
I would very much love having this CDN updated with the release of the SDK (like docker image for example)

**Comment by PureKrome** [comment]
I would have assumed @leecow that CDN updating is all part of the release cycle when a new version is shipped?

**Comment by mairaw** [comment]
@tebeco probably a new issue at https://github.com/dotnet/install-scripts/issues would be better

**Comment by tebeco** [comment]
Do think it would be a good idea to migrate the issue with history ?
because this would loose info about the fact that this issue is a long known and spanning since July 2019

**Comment by mairaw** [comment]
@bozturkMSFT what do you think?
