### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

### ISSUE THREAD

**Issue by Nazarius1** [dotnet/core#2982]
#Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows 10
Error message:
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

.net framework is installed with version 4.5 SDK
![Capture](https://user-images.githubusercontent.com/38841449/60682240-dfe12980-9e92-11e9-8af0-15c43793f57d.JPG)

**Comment by JanePamela** [comment]
verify whether the environmental variable contains C:\Program Files\dotnet\, if not there, include it and then try.
add ;C:\Program Files\dotnet\

**Comment by carlossanlop** [comment]
@Nazarius1, as the tutorial states, you need to open a **new** terminal window after installing, so the environment variables get updated.

**Comment by carlossanlop** [comment]
Closing as resolved. @Nazarius1 if you still have questions, feel free to reopen the issue and we will be happy to help.
