### ISSUE TITLE
Incorrect Dockerfile line

### ISSUE THREAD

**Issue by cloudreyes** [dotnet/core#2983]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-file
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The line:

COPY --from=publish /app .

Should be:

COPY --from=build /app .

We need to reference the previous build stage. Its named build, not publish. Using publish results into an error. 'invalid from flag value publish: pull access denied for publish,...'

**Comment by carlossanlop** [comment]
@Pilchie is this tutorial (and the related docker files) owned by the ASP.NET team If not, @MichaelSimons would you be the best contact for help with these docker containers in the tutorials?

**Comment by glennc** [comment]
No, you want to copy the publish output into your runtime image. The publish layer comes from build and then runs the publish command. Is your Dockerfile missing the publish layer?

```
FROM build AS publish
RUN dotnet publish myMicroservice.csproj -c Release -o /app
```

**Comment by richlander** [comment]
Here is a simpler version of the Dockerfile that I prefer. Give it a try and see if it works better.

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY myMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]
```

**Comment by karelz** [comment]
2.5 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
