### ISSUE TITLE
I have not been able to run MonoDevelop in Linux Mageia 6.1

### ISSUE THREAD

**Issue by Mondoshawa** [dotnet/core#2984]
I use the Linux Mageia X64 distribution, since it was created. It is a distribution of RPM packages
Currently I have installed the Mageia 6.1 x64 distribution, Cinnamon desktop.

Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-current
Operating System: Linux Mageia 6.1 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have followed the steps of installing this Web page:
https://www.mono-project.com/download/stable/#download-lin-fedora

https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-current

As you can see, I installed the Linux Fedora 29 repositories, (x86_64). But I have not managed or got MonoDevelop to work. The IDE does not start.

Please tell me what I can do to solve the problem and get me to run MonoDevelop in Linux Mageia 6.1 x64
Thank you for the help you can give me.

Atte, 
Luis Fernando Gutiérrez Vélez

**Comment by leecow** [comment]
Mageia is not an officially supported distro for .NET Core so we won't be able to offer much in the way of specific assistance. Is .NET Core installed and working? What SDK and Runtime version are reported by `dotnet --info`? We don't do any testing around MonoDevelop but it's our understanding that you need to run the .NET Core SDK 2.2.107.

* Installing from tar.gz is covered [here](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md)
* 2.2.107 download links are [here](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.5/2.2.5-download.md)
