### ISSUE TITLE
HttpListener not work on Ubuntu, but work on Debian

### ISSUE THREAD

**Issue by Persik3D** [dotnet/core#2986]
# HttpListener not work on Ubuntu, but work on Debian

I put a virtual machine which was debian. My little web server worked. After I was told that production was settled on ubuntu. I put the dotnet core there. It was established without errors. Then I launch my application and ...
It starts. No errors. All OK. But when I try to knock on this port, nothing happens. Nothing at all. No errors, no log about the attempt, nothing. What could be the problem?

The port is open 100%. I checked with other applications, they work fine.
The application works without errors on Windows 10 / Debian.

**Comment by carlossanlop** [comment]
Can you show us the code you're trying to execute so we can better understand the problem you're facing?

**Comment by karelz** [comment]
3 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
