### ISSUE TITLE
Couldn't find any package by glob 'dotnet-sdk-2.2.107' Ubuntu 19.04

### ISSUE THREAD

**Issue by mrunal77** [dotnet/core#2990]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-2.2.107
Operating System: Linux Ubuntu 19.04 - x64

Not able to install 2.2.107 version
Not able to run projects on monodevelop

**Comment by dagood** [comment]
You have to install from binaries for this version at the moment, we don't have 2.2.107 available as a Debian package: https://github.com/dotnet/core/issues/2934.

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/core/issues/2934
