### ISSUE TITLE
Cannot install .NET Core on debian

### ISSUE THREAD

**Issue by ChakritRakuang** [dotnet/core#2991]
sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

**Comment by dagood** [comment]
What instructions did you use? What OS release are you running? This error is unfortunately very general. The most common cause is using instructions that don't match your distro or distro version.

**Comment by enricoreich** [comment]
Have you already done this: https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.2.300 ?

**Comment by leecow** [comment]
Closing due to lack of response from OP.
