### ISSUE TITLE
Request finished in 404

### ISSUE THREAD

**Issue by LiuyangRY** [dotnet/core#2992]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/run
Operating System:Linux
I attempted to run my first Microservice with the tutorial, when I run the service and tried to get it, there was a info "Microsoft.AspNetCore.Hosting.Internal.WebHost[2]  Request finished in 55.0356ms 404", I don't know how to fix it.
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@Pilchie let me know if this is something the ASP.NET team can help with.

**Comment by glennc** [comment]
What URI did you try to browse to? That message typically means that your request made it to ASP.NET but the route didn't match any routes. So I would double check that the route on your controller matches the request you are sending. If you show the controller and URI you sent I might be able to see a problem.

**Comment by richlander** [comment]
This happened to me, too, when I used the 3.0 SDK (because the URLs are different). Can you share which .NET Core SDK you are using (`dotnet --version`)?

**Comment by LiuyangRY** [comment]
> This happened to me, too, when I used the 3.0 SDK (because the URLs are different). Can you share which .NET Core SDK you are using (dotnet --version)?

The version of SDK I used is 2.2.300. And I build the image of microservice successfully after reinstalling the lastest version of docker. I suggest you try to install the lastest version of docker as well, it should solve this problem.

**Comment by LiuyangRY** [comment]
> What URI did you try to browse to? That message typically means that your request made it to ASP.NET but the route didn't match any routes. So I would double check that the route on your controller matches the request you are sending. If you show the controller and URI you sent I might be able to see a problem.

Sorry, I don't know what the URI I tried to browse to, I just config the dockerfile and build it, this problem occured when the docker trying to pull the ASP.NET image.

**Comment by carlossanlop** [comment]
@rowanmiller 's team owns this tutorial and might be able to help.

**Comment by rowanmiller** [comment]
This is due to a change in the default site that is generated by `dotnet new webapi`. 

The URL to visit now is http://localhost:5000/WeatherForecast

@richlander is working on updating the tutorial. I'm closing this issue out as we have a central work item tracking the updates.

**Comment by crm-lms** [comment]
i have host my asp.net core web api project with database project but i am getting error 404  page not found
please kindly suggest me
