### ISSUE TITLE
Cannot install dotnet-sdk-2.2.107 on Ubuntu 18.04

### ISSUE THREAD

**Issue by Heimdell** [dotnet/core#2993]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.107
Operating System: Linux Ubuntu 18.04 - x64

> Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

On any branch on that page, i get this:
```
/tmp                                                                                                                                                                         
▶ sudo apt-get install dotnet-sdk-2.2.107=2.2.107-1

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2.107
E: Couldn't find any package by glob 'dotnet-sdk-2.2.107'
E: Couldn't find any package by regex 'dotnet-sdk-2.2.107'

```

**Comment by alighazi** [comment]
same here

**Comment by leecow** [comment]
We are only releasing the latest major.minor SDK versions to the repo so 2.2.107 is not available there. If you need it, you can install using tar.gz described [here](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md).

Do you need 2.2.107 for MonoDevelop?

**Comment by alighazi** [comment]
I actually tested with the exact same commands as the MS website https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current ie. used `sudo apt-get install dotnet-sdk-2.2` and it didn't work (same error message)

**Comment by leecow** [comment]
I assume that you have registered packages.microsoft.com? Steps are listed below if you need them. Can you try `sudo apt-get update && apt search dotnet-sdk-2.2`? You should see 2.2.301 if everything is set up correctly. 

```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

**Comment by karelz** [comment]
2 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
