### ISSUE TITLE
64 bit linux

### ISSUE THREAD

**Issue by Eden-shisso** [dotnet/core#2994]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.2.300
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Can you describe what issue you are seeing?

**Comment by leecow** [comment]
Closing due to lack of response from OP.
