### ISSUE TITLE
Debian Buster broken deps

### ISSUE THREAD

**Issue by techiedesu** [dotnet/core#2996]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 10 - x64. I'm using stretch repo, because buster doesn't exist.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by leecow** [comment]
The Debian 10 repo will be up in the next few weeks. In the meantime, you can install using either the Snap installer or tar.gz described in the [linux setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.

**Comment by leecow** [comment]
Debian 10 repo is up and running though not yet added to the documentation. Follow the instructions at https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current replacing 'debian/9' with 'debian/10'.

**Comment by techiedesu** [comment]
```bash
deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main
```
Perfectly works! Thanks!
