### ISSUE TITLE
 Access to the path '...dgspec.json' is denied

### ISSUE THREAD

**Issue by SimonHeffer** [dotnet/core#2999]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows

Error from the docker build step:

> Step 9/14 : RUN dotnet build smhMicro.csproj -c Release -o /app

>  ---> Running in 089f073fa544

> Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core

> Copyright (C) Microsoft Corporation. All rights reserved.

> C:\Program Files\dotnet\sdk\2.2.300\NuGet.targets(121,5): error : Access to the path 'C:\src\smhMicro\obj\smhMicro.csproj.nuget.dgspec.json' is denied. [C:\src\smhMicro\smhMicro.c

sproj]

> Build FAILED.

The only thing I changed in the tutorial was the name of the service.

dotnet --version
2.2.300
Windows Server 2019 Build 1809

I came across this but don't know if it's related (and no obvious soln:
https://github.com/NuGet/Home/issues/7836

**Comment by carlossanlop** [comment]
@SimonHeffer if you use the default name for the service, do the tutorial steps work normally?

@MichaelSimons would you be able to assist with this docker issue from the tutorial?

**Comment by MichaelSimons** [comment]
@SimonHeffer - Did you by chance build the project locally prior to building the Docker image?   This may explain the behavior you are seeing.  The sample should be including a `.dockerignore` which excludes any local `obj` and `bin` directories.

.dockerignore content
```
# directories
**/bin/
**/obj/
```

**Comment by carlossanlop** [comment]
@rowanmiller 's team owns this dotnet tutorial.

**Comment by rowanmiller** [comment]
Tutorial has been updated to include instructions for adding a `.dockerignore` file. 

@SimonHeffer feel free to reply back here if this doesn't solve your issue.
