### ISSUE TITLE
Asp.net core Microservices Tutorial - auth issue with dockerfile

### ISSUE THREAD

**Issue by parveen-kumar-1** [dotnet/core#3000]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: Linux Ubuntu 16.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I ran below command:
$ docker build -t mymicroservice .

I got the following error:
Step 1/14 : FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
Get https://registry-1.docker.io/v2/microsoft/dotnet/manifests/2.2-aspnetcore-runtime: unauthorized: incorrect username or password

Seems you have to be logged into the docker registry or something which the tutorial fails to specify earlier on.. Either that or the Dockerfile should pull the images from a diff location of the docker images somewhere auth isnt required..

**Comment by carlossanlop** [comment]
@MichaelSimons would you be able to assist with this docker issue?

**Comment by MichaelSimons** [comment]
@parveen-kumar-1 - It look like the sample was updated to use the official microsoft repository - `mcr.microsoft.com/dotnet/core/aspnet`.  Can you update your sample and try again?

**Comment by carlossanlop** [comment]
@rowanmiller 's team owns these tutorials.

**Comment by rowanmiller** [comment]
Closing this one out, as the change mentioned by @MichaelSimons should mean this is no longer an issue. 

@parveen-kumar-1 feel free to respond back if the latest instructions don't resolve the issue for you.
