### ISSUE TITLE
Treat warning as error (.Net Core Project)

### ISSUE THREAD

**Issue by shpsyte** [dotnet/core#3002]
Treat warning as an Error (.Net Core Project)

**General**
Is not an issue, but maybe a new feature when we were building  

I would like to see an option that I can set a **warning as an error** in my .net core project.

Will be perfect!

**Comment by omajid** [comment]
Are you familiar with the `TreatWarningsAsErrors` msbuild property? Would that work for your use case?

**Comment by carlossanlop** [comment]
@shpsyte the suggestion given by @omajid is probably what you're looking for.
I'm closing this issue as resolved, but feel free to reopen it if you have more questions, we'll be happy to help.
