### ISSUE TITLE
broken package

### ISSUE THREAD

**Issue by notmanoj** [dotnet/core#3003]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current#ubuntu-package-issue
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Can you provide more information about the issue you are facing?

**Comment by leecow** [comment]
19.04 repo confirmed OK. If you're still having trouble, please re-open with details around what you have tried and any error messages you are seeing.
