### ISSUE TITLE
Unable to locate package: Linux Ubuntu 18.04 - x64 / sdk-2.1.401

### ISSUE THREAD

**Issue by zbeer** [dotnet/core#3004]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.1.401
Operating System: Linux Ubuntu 18.04 - x64

I attempted all three methods on the linked page.  All result in the same three errors:

> E: Unable to locate package dotnet-sdk-2.1.401
> E: Couldn't find any package by glob 'dotnet-sdk-2.1.401'
> E: Couldn't find any package by regex 'dotnet-sdk-2.1.401'

**Comment by dagood** [comment]
I believe this was a doc bug that was coincidentally fixed very shortly after you hit it. 😄 

The new command is `sudo apt-get install dotnet-sdk-2.1=2.1.401-1`, I believe the command that was on the page earlier had you try to install `dotnet-sdk-2.1.401-1=2.1.401-1`, which doesn't work.

Give the new step a try and let me know if it still doesn't work. (It works for me in an Ubuntu 18.04 Docker container.)

**Comment by zbeer** [comment]
Looks like that did the trick.  Thank you for the prompt reply!

**Comment by dagood** [comment]
Awesome, thanks for confirming. 😄
