### ISSUE TITLE
Docker image build error.

### ISSUE THREAD

**Issue by LiuyangRY** [dotnet/core#3005]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-file
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I use "yum install docker" to install the docker on my CentOS 7.5 machine, and create a dockerfile to build the micro-service image. while the docker reminded me the error info, "Error parsing reference: "microsoft/dotnet:2.2.0-aspnetcore-runtime AS base" is not a valid repository/tag: invalid reference format" .
I flowed the .NET Tutorial “https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-file” step by step to build the image. 
I think the docker's version on the yum is lower than offical version may cause the error. I have uninstalled the docker and I will try to solve the error by installing the lastest docker with source code.

**Comment by carlossanlop** [comment]
@MichaelSimons would you be able to assist with docker related issues coming from the tutorial?

**Comment by MichaelSimons** [comment]
@carlossanlop - I don't have anything to do with these tutorials.  I don't know who authored them.  It seems like there are some improvements that should be made to them.  I looked in https://github.com/dotnet/docs as well as https://github.com/aspnet/AspNetCore.Docs and can't find a reference.  I don't understand why the `I ran into an issue` brings the user to this repo.

**Comment by carlossanlop** [comment]
@MichaelSimons ok thank you. I'll investigate who owns these tutorials.

**Comment by MichaelSimons** [comment]
@LiuyangRY - I am not seeing where the `microsoft/dotnet:2.2.0-aspnetcore-runtime` reference came from?  The tutorial reference `FROM mcr.microsoft.com/dotnet/core/aspnet:2.2`.  Did you change the tutorial or did it change since you opened the issue?

**Comment by MichaelSimons** [comment]
@carlossanlop - if you find the owner, I'd be interested in knowing.  I have a couple suggestions to improve the tutorial.

**Comment by carlossanlop** [comment]
@scottaddie, @mvelosop, @cesardl I was told you may know who owns these tutorials. Can you please help us?

**Comment by LiuyangRY** [comment]
> @carlossanlop - if you find the owner, I'd be interested in knowing.  I have a couple suggestions to improve the tutorial.

**Comment by LiuyangRY** [comment]
> @LiuyangRY - I am not seeing where the microsoft/dotnet:2.2.0-aspnetcore-runtime reference came from?  The tutorial references FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.  Did you change the tutorial or did it change since you opened the issue?

I searched the tutorial about docker in browser and then I finded this tutorial. I have tried my best to find it from the official tutorial again, but failed. The only thing I can confirm is that the tutorial really exist.
I wouldn't be able to find it if I haven't bookmarked the tutorial. 
In addition, it will be better if the tutorial navigation can be improved, so that the low-level programmer such as me will be able to find more useful tutorials.
Thanks for your help!
:)

**Comment by LiuyangRY** [comment]
Sorry, I closed this issue accidentally.

**Comment by carlossanlop** [comment]
@rowanmiller 's team owns these tutorials.

**Comment by rowanmiller** [comment]
> I think the docker's version on the yum is lower than offical version may cause the error.

We think this is most likely the cause. The tutorial has been updated to include a suggested min version of Docker.

@LiuyangRY feel free to reply back here if this doesn't solve your issue.
