### ISSUE TITLE
.NET Core July Update - 2.1.12 and 2.2.6

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#3007]
Included fixes address security issues detailed in the release notes.

## .NET Core

* **.NET Core 2.1.12 and .NET Core SDK 2.1.508**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.12/2.1.12.md)
  [Download 2.1](https://dotnet.microsoft.com/download/dotnet-core/2.1)

* **.NET Core 2.2.6 and .NET Core SDK 2.2.108**
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.6/2.2.6.md)
  [Download 2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2)

Please report any issues you find with these releases, either responding to this issue, creating a new issue here or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

## .NET Support Policies

Microsoft support policies are defined in the following documents:

* [Microsoft .NET Support Policy](https://www.microsoft.com/net/support/policy)
* [.NET Core OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md)

**Comment by willseward** [comment]
@vivmishra Could you provide tags of the non-vulnerable Docker images?

**Comment by vivmishra** [comment]
Windows Docker images are expected to be ready later in the day. 

@MichaelSimons can you share the tags for others?

**Comment by MichaelSimons** [comment]
All of Docker images are currently being updated and will be available in a bit.

**Comment by willseward** [comment]
FWIW, it looks like the tags are present now:
* `mcr.microsoft.com/dotnet/core/sdk:2.2.301`
* `mcr.microsoft.com/dotnet/core/aspnet:2.2.6`

**Comment by MichaelSimons** [comment]
Correct, all tags were just updated.

**Comment by pmachapman** [comment]
I tried to update to 2.2.6 using the instructions on https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-2.2.6 or `yum upgrade`, but I only receive the message "Package aspnetcore-runtime-2.2-2.2.5-1.x86_64 already installed and latest version". Will 2.2.6 be published to the repository, or am I doing something wrong?

**Comment by leecow** [comment]
I've confirmed that 2.2.6 is available and offered correctly. It's possible the repo cache on your machine is not getting updated. You could try `yum update` to see if that forces an update. A heavier hammer is to delete the cache entirely so that it is rebuilt. This should be found at`/var/cache/yum/x86_64/7/packages-microsoft-com-prod`.

**Comment by pmachapman** [comment]
`yum update` did the trick. Thanks - that is the first time I've had a problem like that!

**Comment by cortex93** [comment]
Is it normal latest releases on https://github.com/dotnet/core/blob/master/release-notes/releases.json are from april ?

**Comment by vivmishra** [comment]
Yes, that json has been deprecated. See related issue https://github.com/dotnet/announcements/issues/87

It also has details on what to use going forward.  

Cc: @leecow

**Comment by PhoenixKing13** [comment]
https://github.com/dotnet/core/issues/3052#issue-469540013
This bug seems to be happening for both Ubuntu and Pop!_OS 19.04 users.

**Comment by suprak** [comment]
Not sure if this the right place to ask, but when will the hosted agent pools owned by Azure Pipelines in DevOps be updated with the latest sdk/runtimes?

We have "component governanace alerts" we want to address, but none of the build environments yet have the latest runtimes.

I'm assuming this will cover it, but when is "later in July"?
> .NET Core 2.2.6 is being deployed to Azure App Services and the deployment is expected to complete later in July 2019.

**Comment by vivmishra** [comment]
The deployment is expected to complete by 7/29.

**Comment by icistrate** [comment]
First of all, sorry to ask here, maybe is the wrong place.
I cannot find 2.1.508 SDK (LTS) deployed on Azure App Service for quite a while now. Why would that be the reason?

**Comment by Jargon64** [comment]
> The deployment is expected to complete by 7/29.

I am very much looking forward to this as well.

**Comment by suprak** [comment]
> The deployment is expected to complete by 7/29.

@vivmishra It's now been several weeks past 7/29 and I'm still not seeing the images updated.
Any update on when this will happen?

**Comment by vivmishra** [comment]
Sorry, my comment was about  .NET Core deployment to Azure App Service. I am not sure who handles the ask you made.

**Comment by leecow** [comment]
September update released: closing this tracking issule.
