### ISSUE TITLE
Won't allow me to open to the program

### ISSUE THREAD

**Issue by monikadrone** [dotnet/core#3009]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm trying to install .net so I can use Synctoy, and it downloads, says the download is complete, but there is no icon, and no recent download in my toolbar that I can access to do the next stage. Also, when I try to download synctoy after having installed .net, it won't allow the download and indicates that I need to download .net.

**Comment by carlossanlop** [comment]
@monikadrone this sounds like an issue with Synctoy, not with .NET. Please try downloading the installer using a browser, wget or a package manager like apt-get.

**Comment by leecow** [comment]
@monikadrone please update this issue and re-open if you're still having troubles.
