### ISSUE TITLE
Cannot install dotnet sdk 2.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by loneshark99** [dotnet/core#3014]
I have same issue as reported before for 2.1 few hours ago where .NET sdk install fails. Can you please help take a look.

E:Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/dotnet-runtime-deps-2.2.....

**Comment by leecow** [comment]
I've confirmed that all is well with the 18.04 repo. Can you run `apt-get update` and `apt search dotnet-sdk-2.2` and let me know what you see?

**Comment by loneshark99** [comment]
works now. no issue.
