### ISSUE TITLE
No ipv6 on packages.microsoft.com

### ISSUE THREAD

**Issue by xaocel** [dotnet/core#3016]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-current
Operating System: Linux CentOS / Oracle - x64

packages.microsoft.com has no ipv6?

**Comment by carlossanlop** [comment]
@rowanmiller is this page owned by your team?

**Comment by rowanmiller** [comment]
@leecow @dagood any thoughts on this one?

**Comment by dagood** [comment]
The Linux package repo is maintained by a different team. @leecow may know how to ask them this question.

**Comment by karelz** [comment]
@leecow ping?

**Comment by leecow** [comment]
Sent the team email. Hopefully they will chime in soon.

**Comment by carlossanlop** [comment]
@xaocel any particular reason why you need ipv6?
@leecow any followup on this?

**Comment by xaocel** [comment]
@carlossanlop I wanted to install .net core on a VM that only had a public ipv6 address assigned to it.

**Comment by leecow** [comment]
@xaocel - is ipv6-only access a hard requirement for your scenario or is it something you are just experimenting with? Want to understand a little better so I can pass it along to the team that owns packages.microsoft.com.

**Comment by xaocel** [comment]
@leecow for this particular VM it is a hard requirement as it was only assigned an ipv6 public address by the provider and i was thinking that i could pair it with cloudflare in order to serve the app over ipv4 as my ISP has yet to implement ipv6 as well. Thank you for your time. :D

**Comment by leecow** [comment]
Thanks, @xaocel - I've passed the information along to the owning team. Work to support ipv6 is not yet on their backlog so this at least makes them aware. I meet with them somewhat regularly and will include this in future conversation.

**Comment by lipnitsk** [comment]
@leecow why was this closed if the issue is still not resolved?

**Comment by leecow** [comment]
@lipnitsk, the issue is owned and will be resolved by a different team and is tracked within their backlog which is not in a public forum.

**Comment by BartjeD** [comment]
It's well into 2022 and still no AAAA record?
This doesn't seem like a herculean task :confounded:
