### ISSUE TITLE
Environment.UserInteractive does not work as expected

### ISSUE THREAD

**Issue by bizzbizz** [dotnet/core#3017]
# `Environment.UserInteractive` returns true in WindowsService

We have a console application which can be run either as a console application or a windows service. There is a `if (Environment.UserInteractive)` statement in it which used to work as expected in netfx471 and older, but when we ported to dotnet core it always returns true.

I tried to test it outside of VisualStudio and I manually started the service in services.msc but it still returns true.

---

Windows 10 pro 1809 x64
netcore 3.0.0-preview6-27804-01
Visual Studio 2019

We are using ServiceBase from Microsoft.Windows.Compatibility for creating and running the service.
We are using TopShelf.ServiceInstaller for installing and uninstalling the service.

**Comment by 0xd4d** [comment]
See this issue https://github.com/dotnet/coreclr/issues/25595

**Comment by carlossanlop** [comment]
According to the code, we always return `true`: [corefx/src/Common/src/CoreLib/System/Environment.cs#L129](https://github.com/dotnet/corefx/blob/c1d441f293f2370b76a246d5bd541de379851393/src/Common/src/CoreLib/System/Environment.cs#L129)

This line was introduced 3 years ago: https://github.com/dotnet/corefx/commit/fe5f4fbebc9e85c8e512a273567719dca15ac764

@stephentoub @jkotas could you please help describe this behavior? Should it return a different value depending if it's a console app or a service?

**Comment by stephentoub** [comment]
@carlossanlop, see dotnet/coreclr#25595.

**Comment by stephentoub** [comment]
Closing as dup of dotnet/coreclr#25595.
