### ISSUE TITLE
The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by wicaodian** [dotnet/core#3018]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@wicaodian can you provide more details about your problem?
Judging by the title, you probably didn't close and reopen the terminal window after installing dotnet. You need to do this so the environment variables get updated.

**Comment by leecow** [comment]
If you're still having trouble, please re-open this issue with details on your OS, specifics on what you are doing when the error is seen.
