### ISSUE TITLE
unity

### ISSUE THREAD

**Issue by hatanesan** [dotnet/core#3019]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@hatanesan  can you please provide more details about your problem?

**Comment by siwiak** [comment]
He probably used provided link and didn't think of adding more details. 
I suspect I have exactly the same problem here: dotnet not visible from cmd nor from VisualStudio
on Win64.
I had to reboot and install again, then it worked. Just if someone else from Unity comes to search for answers.

**Comment by karelz** [comment]
Thanks for info. Unclear if it is real problem with .NET Core, or with Unity. Closing as there is no action to be taken.
