### ISSUE TITLE
'myApp' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by AyeChan1309** [dotnet/core#3022]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Hi @AyeChan1309, can you provide more details about your problem?

**Comment by leecow** [comment]
Closing because of actionable details. Please re-open if you're still having troubles and can provide information on your project.
