### ISSUE TITLE
dotnet-install.sh does not download correct version on RHEL 6 workstation

### ISSUE THREAD

**Issue by winnieryl** [dotnet/core#3025]
# Issue Title

dotnet-install.sh does not download correct version on RHEL 6 workstation

# General

https://dot.net/v1/dotnet-install.sh 
this script, at line 151, it does not consider RHEL 6 Workstation, when I run this on rhel6 workstation, it downloads the wrong version fo dotnet runtime.

**Comment by leecow** [comment]
@johnbeisner - thoughts?

**Comment by carlossanlop** [comment]
@johnbeisner can you please take a look? (2 weeks no response)

**Comment by johnbeisner** [comment]
@carlossanlop 
This issue was addressed. Issue: https://github.com/dotnet/cli/issues/11940

**Comment by johnbeisner** [comment]
@leecow 
Can you close this as a duplicate issue - I do not have permission.

**Comment by leecow** [comment]
Duplicate of dotnet/cli#11940.
