### ISSUE TITLE
Error when tried installing .net core SDK on redhat

### ISSUE THREAD

**Issue by yuthan** [dotnet/core#3027]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-2.1.300
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
this commands ran success
yum install rh-dotnet21 -y
when i tried run this command 
scl enable rh-dotnet21 bash
i am getting following error
unable to open /etc/scl/conf/rh-dotnet21

**Comment by leecow** [comment]
Have you configured the Software Collection per the [Red Hat getting started guidance](https://access.redhat.com/documentation/en-us/net_core/2.1/html/getting_started_guide/gs_install_dotnet#install_register_rehel)?

**Comment by karelz** [comment]
2 weeks no response, closing. Feel free to reopen if there is more info available. Thanks!
