### ISSUE TITLE
Problem at the time of using cmd to run dotnet command

### ISSUE THREAD

**Issue by harish0139** [dotnet/core#3028]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, co
![Captureqq](https://user-images.githubusercontent.com/52827586/61132121-5d7ee800-a4d8-11e9-9fc4-a96691dc238d.PNG) how to solve this problem
de sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
After installing dotnet, did you make sure to close the command line window and reopening it again, as stated in the tutorial? It's an important step to ensure the environment variables get updated in the command line window.,

**Comment by harish0139** [comment]
Please provide step by step instructions to set environmental variables.

Happy to hear from you soon.

**Comment by karelz** [comment]
@harish0139 the steps are part of the tutorial. Please follow all steps, including closing the open command line after install.
