### ISSUE TITLE
Should linux-prereqs.md have a 3.0 column?

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/core#3029]
When someone wants to download the SDK for Linux from a link like this one (Preview 6 in this case):

https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview6-linux-x64-binaries

The "Step 1" section has a hyperlink that points to this table:

https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md

But there's no 3.0 column in that table. @leecow should these instructions have a new column for 3.0?

It seems the list of dependencies is closely similar (if not identical) to the one we have for corefx development:

https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md

**Comment by leecow** [comment]
Thanks @carlossanlop - the list should be the same as for 2.2 so I replicated that column.

**Comment by carlossanlop** [comment]
Awesome, thanks!
