### ISSUE TITLE
The dotnet application fails to start

### ISSUE THREAD

**Issue by Veldora-HollowSoul** [dotnet/core#3031]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I launch the dotnet application in C:\Program Files\dotnet\dotnet the application does not start.

**Comment by leecow** [comment]
Please re-open with specific details on what you are doing and any errors you see.
