### ISSUE TITLE
https://m.facebook.com/%D8%A7%D9%84%D9%88%D8%A7%D9%81%D9%8A%D9%A1-2330731280282635/?msite_modal=composer&notif_t=aymt_upsell_tip&notif_id=1562910438659207&ref=m_notif&refid=48

### ISSUE THREAD

**Issue by alsfyani** [dotnet/core#3035]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by alsfyani** [comment]
https://www.facebook.com/profile.php?id=100005030236147

**Comment by leecow** [comment]
Please add details on what you are seeing and reopen this issue.

**Comment by alsfyani** [comment]
https://m.facebook.com/٪D8٪A7٪D9٪84٪D9٪88٪D8٪A7٪D9٪81٪D9٪8A٪D9٪A1-2330731280282635/؟msite_modal=composer¬if_t=aymt_upsell_tip¬if_id=1562910438659207&ref= m_notif & refid = 48
