### ISSUE TITLE
Version 2.2.301 does not support Q# 

### ISSUE THREAD

**Issue by khuslen** [dotnet/core#3036]
.NET Core version: 2.2.301
OS: macOS Sierra 10.12.6 and Windows 10 Pro 1803

On my macOS, I just installed .NET core from [here](https://dotnet.microsoft.com/download). `dotnet --version` shows versions 2.2.301.

Running `dotnet new --help` does not show Q# in the list of languages. Running this same command on a Windows laptop with version 2.2.101 shows Q# (as well as C#, F#, and VB). Upgrading my Windows laptop to version 2.2.301 also shows no support for Q#.

Was support for Q# purposely removed from .NET core? I couldn't find any mentions of this in the release notes.

**Comment by davidfowl** [comment]
Q# was never included with .NET Core. What did you see before and did you install another SDK (like this https://www.microsoft.com/en-us/quantum/development-kit)

**Comment by carlossanlop** [comment]
3 weeks no response. @khuslen please feel free to reopen the issue if you can provide the info requested. We'll be happy to help.
