### ISSUE TITLE
Collection model binding in mvc and upload file using ajax (dotnet core 3.preview-6)

### ISSUE THREAD

**Issue by bahmansh** [dotnet/core#3037]
I have one form with some fields and one collection of another fields that contains some input files.

So I need to post form using ajax and bind data collection to class (Model) in server side.

My main issue is that files of sub collections will pass null.

My file is type of IFormFile and posted data is (form data of browser network):

![image](https://user-images.githubusercontent.com/19801131/61180796-73ec8700-a631-11e9-89d0-2803c7185da7.png)

Earlier I was working with .net core 2.2, that it had big issue with sub collections files, so when I was using such sub collection it was throwing exception, I upgraded it to dot net core 3.preview-6 and now it's resolved.

How can I resolve this issue?

**Comment by mkArtakMSFT** [comment]
@bahmansh this is an ASP.NET Core MVC issue. Please file a new issue in https://github.com/aspnet/aspnetcore repo and we'll handle it there.
