### ISSUE TITLE
no winforms template on 3.0.100-preview6 linux

### ISSUE THREAD

**Issue by chergey** [dotnet/core#3038]
# Issue Title

No winforms template on 3.0.100-preview6 linux

# General

1. Download https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview6-linux-x64-binaries.
2. Run dotnet new winforms

**Expected**
Winforms project is generated.
**Actual**
No templates matched the input template name: winforms.
OS: Ubuntu 19.04, x64

**Comment by AlseinX** [comment]
WinForms and WPF are Windows only.

**Comment by chergey** [comment]
@AlseinX
Netcore 3 Preview 5 has it on Linux.

**Comment by dagood** [comment]
This is an intended change, see https://github.com/dotnet/cli/issues/11425 for more info.
