### ISSUE TITLE
Package runtime update

### ISSUE THREAD

**Issue by mateusz-dot** [dotnet/core#3041]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-2.2.6
Operating System: Linux CentOS / Oracle - x64

I tired to update my runtime from 2.2.5 to 2.2.6 on linux, but after executing:
`sudo yum install aspnetcore-runtime-2.2`
I got response:
`Package aspnetcore-runtime-2.2-2.2.5-1.x86_64 already installed and latest version
`

**Comment by leecow** [comment]
I have confirmed that the CentOS repo is up to date. Try running `yum update` to refresh your local repo catalog then try again. Please re-open if you're still having troubles.
