### ISSUE TITLE
When will preview7 and the first RC come out?

### ISSUE THREAD

**Issue by AlseinX** [dotnet/core#3042]
The roadmap says RC will come out in July, but is there a bit more detailed time based on the current progress? Or is there a problem that would put it off?

**Comment by EKanadily** [comment]
only 15 days is remaining in July. 
OK i admit i myself can't wait too because  i think RC is a good time to start learning the framework. happy waiting.

**Comment by leecow** [comment]
We were expecting to have it out tomorrow but ran into an issue in the final round of validation which reset the candidate build. The new target is next week.
