### ISSUE TITLE
System.ValueTuple nuget changed without chaning its version ?

### ISSUE THREAD

**Issue by kbeaugrand** [dotnet/core#3043]
# Issue Title
Nuget package for System.ValueTuple seems to be changed, since there is no update for it.

# General

I'm using System.ValueTuple since more than one year.
Since I'm working with a Nexus repository I'm not getting packages directly from Nuget.org repository but caching packages by this server. 
After regarding created dates from my nexus repository and nuget.org it seems that those on nuget.org has been modified after my nexus server has cached it.

Obviously this is not a good practice to update a pakage without changing its version. 

Here is my version on the cache: 

![image](https://user-images.githubusercontent.com/9513635/61202070-ce93ea80-a6e6-11e9-9a6e-60f60e884871.png)

Here is the version on nuget.org:
![image](https://user-images.githubusercontent.com/9513635/61202216-3813f900-a6e7-11e9-8d1c-bbcb6d232486.png)

**Comment by 0xd4d** [comment]
The sha1 of 4.5.0 matches your cached sha1 so it's just the 'last updated' column that got updated.

`f001a074be6f5c3a20940e88ac46f7c97a010d57 *system.valuetuple.4.5.0.nupkg`

**Comment by kbeaugrand** [comment]
Hoo, 

Sorry I didn't check it.

Thank you for the update.
