### ISSUE TITLE
Unable to install dotnet-sdk-2.1

### ISSUE THREAD

**Issue by Norfolgx** [dotnet/core#3046]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-2.1.4
Operating System: Linux CentOS / Oracle - x64

I get the following error:

Error: Package: dotnet-runtime-2.0.5-2.0.5-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs

Currently unable to install openssl-libs, is there a ms supported way of downloading that package?

**Comment by leecow** [comment]
What are the exact distro and version number you are running? 

According to [centos.pkgs.org](https://centos.pkgs.org/7/centos-updates-x86_64/openssl-libs-1.0.2k-16.el7_6.1.x86_64.rpm.html), openssl-libs is available in the CentOS repos. You will need to make sure that you have the appropriate repo registered on your system.

**Comment by leecow** [comment]
Closing for now. Please re-open if you can provide additional info.
