### ISSUE TITLE
Build 3.0.100-preview6-012264 missing Microsoft.WebApplication.targets

### ISSUE THREAD

**Issue by andez2000** [dotnet/core#3047]
# Missing targets Microsoft.WebApplication.targets error when using MSBuild and Roslyn to iterate through documents in a web project

This was working for the same dotnet core project I wrote that targets either dotnet2.2 or 3.0 when I had __3.0.100-preview5-011568__ installed.  Having just installed __3.0.100-preview6-012264__, the following error is displayed:

```txt
Failure - Msbuild failed when processing the file 'G:\andez2000\ld-working\find-endpoints\code-analysis\sample\dotnet\bar-context\Bar.Web\Bar.Web.csproj' with message: The imported project "C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  G:\andez2000\ld-working\find-endpoints\code-analysis\sample\dotnet\bar-context\Bar.Web\Bar.Web.csproj
```

No code changes were made to my project, nor the solution I am loading.  The solution I am loading is a dotnet web application targeting `dotnet v4.7.2`.

This uses `MSBuildLocator.RegisterDefaults()` to provide the ground work into locating msbuild, where I have the following information output.

## 3.0.100-preview5-011568

```txt
.NET Core SDK - 3.0.100
        MSBuild:                C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\
        VisualStudioRootPath:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\
        Version:                3.0.100
```
## 3.0.100-preview6-012264

```txt
.NET Core SDK - 3.0.100
        MSBuild:                C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\
        VisualStudioRootPath:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\
        Version:                3.0.100
```

Is it a case of the sdk missing the targets file or something more sinister?

The information listed is from my home PC.  My work computer just has the __3.0.100-preview6-012264__ installed and not other dotnetcore versions.

In __3.0.100-preview5-011568__  the targets file can be found under `C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Microsoft\VisualStudio\v16.0\WebApplications`.  In __3.0.100-preview6-012264__ the folder `C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Microsoft\VisualStudio` does not even exist.

When preview 6 is installed alongside preview 5, then the build target issue will appear.

**Comment by carlossanlop** [comment]
@livarcocc @nguerrera is this something your team should look into?

**Comment by livarcocc** [comment]
That target is not support by the .NET Core SDK. It ships with VS and is used for old style web projects.

To use that, you need to use full framework msbuild (msbuild.exe).

**Comment by nguerrera** [comment]
> This uses MSBuildLocator.RegisterDefaults()

You would need the locator to pick a Visual Studio installation, and not a .NET Core SDK installation.

This is maybe better discussed at https://github.com/microsoft/msbuildlocator

cc @rainersigwald

**Comment by carlossanlop** [comment]
This issue was moved to microsoft/MSBuildLocator#75
