### ISSUE TITLE
P/Invoke Fusion.dll works in .NET Framework, but not in .NET Core

### ISSUE THREAD

**Issue by Lindsey1986** [dotnet/core#3048]
# P/Invoke Fusion.dll works in .NET Framework, but not in .NET Core

# General

I have an app that uses P/Invoke to call functions inside of `Fusion.dll` to enumerate .NET Framework assemblies in the Global Assembly Cache.

**It works just fine when I target `net472` but - the exact same code - does not work when I target `netcoreapp2.2`**:

```csharp
class Program
{
    static void Main(string[] args)
    {
        GacUtility.CreateAssemblyCache(out var x, 0);
    }
}

public class GacUtility
{
    [DllImport("Fusion.dll")]
    public static extern int CreateAssemblyCache(out object asmCache, int reserved);
}
```

## Error Message

The error message I get (in .NET Core) is:

```
Unhandled Exception: System.DllNotFoundException:
Unable to load DLL 'Fusion.dll' or one of its dependencies:
The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
```

NB: I know that the correct signature of `CreateAssemblyCache` expects an `IAssemblyName` and I have that correct in my code, and gives me the same error. The code above is a simplified example that reproduces the error the same way...

**Comment by joperezr** [comment]
.NET Core can do P/Invokes just as .NET Framework, but the Probing path that we use to find assemblies is different. In order for that to work, Fusion.dll would need to be part of the probing path for core, Have you tried having Fusion.dll copy-pasted right next to your app?

**Comment by Lindsey1986** [comment]
Thank you for following-up @joperezr. It works if I use the full path of `Fusion.dll`, so I'm sure if I would to put ` Fusion.dll`  inside my apps folder, it would work too (provided I copy any dependencies it has, if any)

```csharp
[DllImport(@"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\fusion.dll")]
public static extern int CreateAssemblyCache(out IntPtr asmCache, int reserved);
```

My issue now is how to make this work properly:
* How do I determine the correct path of `Fusion.dll` as location may differ at least for x86/x64?
* Once I know the path of the `Fusion.dll` I want, how do I add that path to .NET Core's probing path?

**Comment by joperezr** [comment]
The ideal case is that you should ship all your native dependencies along with your app. I'm not familiar with Fusion.dll, but if it is possible to get it as a NuGet dependency, that would be great so you can package that with your app and not requiring fusion.dll to be installed somewhere in the machine.

**Comment by Lindsey1986** [comment]
@joperezr `Fusion.dll` is part of the .NET Framework... I don't think it would be possible to ship it with my app. I have to check if the .NET Framework is installed on the machine, if it is is, I know it has Global Assembly Cache there...

**Comment by carlossanlop** [comment]
Fusion.dll does not seem to be part of .NET Core, only Framework, so I'm not entirely sure it's expected to work, or if we support it.
What functionality are you trying to get from that DLL, @Lindsey1986 ? We might have something in Core that replaced it.
Are you still having this problem?

**Comment by carlossanlop** [comment]
Since there was no response in 3 weeks, I'll go ahead and close this issue. @Lindsey1986 feel free to reopen if you have any more questions.

**Comment by nietras** [comment]
I am running into the same issue here for .NET 5.0, I have a `.net5.0-windows` application that needs to load a specific assembly from the GAC, to do that we need to query the cache via the above mentioned method:
```
     [DllImport("Fusion.dll")]
    public static extern int CreateAssemblyCache(out object asmCache, int reserved);
```
If the probing path is the issue how I can I modify that to work?

**Comment by carlossanlop** [comment]
So Fusion.dll is a .NET Framework sub-system responsible for locating and loading assemblies. We probably have APIs in .NET 5.0 that can achieve the same results. 
@GrabYourPitchforks @steveharter is this something that falls in the System.Reflection area that you could help with?

**Comment by GrabYourPitchforks** [comment]
Use [`NativeLibary.Load(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.load?view=net-5.0#System_Runtime_InteropServices_NativeLibrary_Load_System_String_), passing in the full path ("c:\blahblah\mymodule.dll") to the DLL you wish to load. Do this _before_ attempting to p/invoke into the DLL. Once the unmanaged DLL is loaded in-process, any future p/invokes decorated with `[DllImport("mymodule.dll")]` will bind to the already-loaded DLL.

To get the full path to fusion.dll, query the registry key listed at https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#detect-net-framework-45-and-later-versions.

**Comment by GrabYourPitchforks** [comment]
I'm closing this issue because I believe the question has been answered. Please reopen the issue if further discussion is needed. Thanks!

**Comment by nietras** [comment]
Just a note that the following "hack" worked for me. That is, if .NET Core/5+ then use `NativeLibrary.Load` directly to load `fusion.dll` from fixed full paths in static constructor before calling P/Invoke as mentioned above. We need this to interact with third party library that can change version and is only available in GAC.

```csharp
    public static class AssemblyResolving
    {
#if NET5_0_OR_GREATER
        static AssemblyResolving()
        {
            var fusionFullPath = Environment.Is64BitProcess
                ? @"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\fusion.dll"
                : @"C:\Windows\Microsoft.NET\Framework\v4.0.30319\fusion.dll";
            NativeLibrary.Load(fusionFullPath);
        }
#endif

        /// <summary>
        /// Gets an assembly path from the GAC given a partial name.
        /// </summary>
        /// <param name="name">An assembly partial name. May not be null.</param>
        /// <returns>
        /// The assembly path if found; otherwise null;
        /// </returns>
        public static string GetAssemblyPath(string name)
        {
            if (name == null)
            { throw new ArgumentNullException(nameof(name)); }

            var hr = CreateAssemblyCache(out var assemblyCache, 0);
            if (hr >= 0)
            {
                var assemblyInfo = new AssemblyInfo();
                assemblyInfo.cchBuf = 1024; // should be fine...
                assemblyInfo.currentAssemblyPath = new string('\0', assemblyInfo.cchBuf);

                hr = assemblyCache.QueryAssemblyInfo(0, name, ref assemblyInfo);
                if (hr >= 0)
                {
                    return assemblyInfo.currentAssemblyPath;
                }
            }
            return null;
        }

        [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("e707dcde-d1cd-11d2-bab9-00c04f8eceae")]
        private interface IAssemblyCache
        {
            void Reserved0();

            [PreserveSig]
            int QueryAssemblyInfo(int flags, [MarshalAs(UnmanagedType.LPWStr)] string assemblyName, ref AssemblyInfo assemblyInfo);
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct AssemblyInfo
        {
            public int cbAssemblyInfo;
            public int assemblyFlags;
            public long assemblySizeInKB;
            [MarshalAs(UnmanagedType.LPWStr)]
            public string currentAssemblyPath;
            public int cchBuf; // size of path buf.
        }

        // System.DllNotFoundException: Unable to load DLL 'fusion.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
        // https://github.com/dotnet/core/issues/3048
        [DllImport("fusion.dll")]
        private static extern int CreateAssemblyCache(out IAssemblyCache ppAsmCache, int reserved);
    }
```
