### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by bobthenoobmanneedshelp** [dotnet/core#3050]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I tried to download .Net because visual studios was asking for it and i downloaded it but it says it cannot be located and visual studios also says that there are some projects having trouble loading

**Comment by leecow** [comment]
Can you provide details on your system (os version), version of Visual Studio and exact steps you did to install?

**Comment by karelz** [comment]
1.5 week no response, closing. Feel free to reopen if there is more info available. Thanks!
