### ISSUE TITLE
Package "https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb" wrong.

### ISSUE THREAD

**Issue by Yuri-01** [dotnet/core#3051]
Hi.

Please, edit file "/etc/apt/sources.list.d/microsoft-prod.list" in package "https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb".

(i.e., replace **xenial** in this file to **buster**)

**Comment by leecow** [comment]
I have let the owning team know about the issue.

**Comment by Yuri-01** [comment]
Hi, Lee.

Thank you.
(i hope this issue will be fixed).

**Comment by leecow** [comment]
https://packages.microsoft.com/config/debian/10/prod.list has been updated. They're still working on the deb.

**Comment by leecow** [comment]
Confirmed that https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb has also been updated.

**Comment by Yuri-01** [comment]
Thank you.
