### ISSUE TITLE
Problem installing on Pop!_OS 19.04

### ISSUE THREAD

**Issue by PhoenixKing13** [dotnet/core#3052]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-2.2.108
Operating System: Linux Pop!_OS 19.04 - x64

I tried to download and install the latest version of dotnet core on a fresh install of Pop!_OS 19.04. Previously I had successfully install dotnet core on pop 18.04 following the Ubuntu instructions, however after updating to 19.04 I encountered a problem when running "sudo apt-get update." I'm getting the following error:

> Err:8 https://packages.microsoft.com/ubuntu/19.04/prod disco/main amd64 Packages
>   File has unexpected size (8562 != 8396). Mirror sync in progress? [IP: 13.91.48.226 443]
>   Hashes of expected file:
>    - Filesize:8396 [weak]
>    - SHA512:3cc3bfb2c60ba8f3fc52a7dde70c6f968fe0d270dfb2b2b5d741d28be072477e6644e42b39ba6793408a54a6448bcee68d3a3b2fac06aae5f0d50a4e926d66c9
>    - SHA256:01c480722e325f82384a0fda852b58c8cf7e5181d609cbd1068ec5f72a89d572
>    - SHA1:fed05cf0ba4157167e441745fb1887131be9105e [weak]
>    - MD5Sum:b6a978f64f602f94ff5a03a69cf2f96e [weak]
>   Release file created at: Tue, 16 Jul 2019 22:15:00 +0000
> Get:9 http://us.archive.ubuntu.com/ubuntu disco-backports InRelease [88.8 kB]
> Fetched 190 kB in 1s (206 kB/s)     
> Reading package lists... Done
> E: Failed to fetch https://packages.microsoft.com/ubuntu/19.04/prod/dists/disco/main/binary-amd64/Packages.bz2  File has unexpected size (8562 != 8396). Mirror sync in progress? [IP: 13.91.48.226 443]
>    Hashes of expected file:
>     - Filesize:8396 [weak]
>     - SHA512:3cc3bfb2c60ba8f3fc52a7dde70c6f968fe0d270dfb2b2b5d741d28be072477e6644e42b39ba6793408a54a6448bcee68d3a3b2fac06aae5f0d50a4e926d66c9
>     - SHA256:01c480722e325f82384a0fda852b58c8cf7e5181d609cbd1068ec5f72a89d572
>     - SHA1:fed05cf0ba4157167e441745fb1887131be9105e [weak]
>     - MD5Sum:b6a978f64f602f94ff5a03a69cf2f96e [weak]
>    Release file created at: Tue, 16 Jul 2019 22:15:00 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.

I tried googling for a solution, but to no avail. Please help!

**Comment by Preylien** [comment]
Just ran into this issue. I am also on POP_OS! 19.04

**Comment by killruana** [comment]
Same here with ubuntu 19.04

**Comment by PhoenixKing13** [comment]
Taken today @ 3:30 pm
![Screenshot from 2019-07-18 15-35-08](https://user-images.githubusercontent.com/32967490/61493786-af5cbd80-a971-11e9-8922-d54a30ccbb14.png)

**Comment by PhoenixKing13** [comment]
The dotnet core team has resolved the issue. Here is the [link](https://github.com/dotnet/core-setup/issues/7274#issue-470006881)
