### ISSUE TITLE
System.ObjectDisposedException when posting stream content by HttpClient

### ISSUE THREAD

**Issue by nashangg** [dotnet/core#3053]
# System.ObjectDisposedException when posting stream content by HttpClient
Hello,

I have an API that receives stream content, and I wrote a piece of code to post stream to it:
```cs
var bytes = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(content, GetDefaultFormatter().SerializerSettings));
using (var resourceStream = new MemoryStream(bytes))
{
    var streamContent = new StreamContent(resourceStream);
    // Exception throwed after code ran into this line for about 1 minute
    var resopnseContent = (await client.PostAsync(requestUri, streamContent).ConfigureAwait(false)).Content;
    return await resopnseContent.ReadAsAsync<TResponseType>(new List<MediaTypeFormatter> { GetDefaultFormatter() }).ConfigureAwait(false);
}
```
The exception is:
> System.ObjectDisposedException: 'Cannot access a disposed object.
> Object name: 'SslStream'.'

While, the code worked perfectly with .net framework.

As a try, I changed the code to:
```cs
using (var resourceStream = new MemoryStream())
{
    var bytes = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(content, GetDefaultFormatter().SerializerSettings));
    resourceStream.Write(bytes, 0, bytes.Length);
    var streamContent = new StreamContent(resourceStream);
    var resopnseContent = (await client.PostAsync(requestUri, streamContent).ConfigureAwait(false)).Content;
    return await resopnseContent.ReadAsAsync<TResponseType>(new List<MediaTypeFormatter> { GetDefaultFormatter() }).ConfigureAwait(false);
}
```
Then it worked without any exception!

The difference I only know is the memory stream object changed to resizable from non-resizable. I don't know how did this lead to the exception. Is it a bug of .net core?

As a note, the byte array I use has about 21,000 bytes. I tested the code with smaller byte array (about 10 bytes), and the problem was gone. So I suspect the bug shows up only with large streams.

Since I've found a solution to solve my problem, I just report this as a potential bug. Please take a look if you have time.

**Comment by nashangg** [comment]
Updates:

I found it's nothing to do with a non-resizable or resizable memory stream, size is the key.
I compressed the stream then everything goes fine.

**Comment by carlossanlop** [comment]
@nashangg thank you for providing the details. Are you still encountering a problem so we can help you, or can we mark this issue as resolved?

**Comment by nashangg** [comment]
@carlossanlop As I'm not facing new problems, I close this issue now.
