### ISSUE TITLE
Not able to run REST API 

### ISSUE THREAD

**Issue by DasSurabhi** [dotnet/core#3055]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by DasSurabhi** [comment]
I want to run TabMigrate REST API for this I have installed Github and Visual Studio Code.

**Comment by carlossanlop** [comment]
@DasSurabhi can you provide more information? What exactly was the problem you encountered?

**Comment by karelz** [comment]
1 week no response, closing. Feel free to reopen if there is more info available. Thanks!
