### ISSUE TITLE
My web api not running  in container

### ISSUE THREAD

**Issue by rathinamshanmugam** [dotnet/core#3056]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/run-docker
Operating System: windows

 I am using windows docker tool box
My web api not running as per steps
http://localhost:3000/api/values 
http://172.17.0.3:3000/api/values 
http://192.168.99.100:3000  - docker running ip address
I have attached file for docker inspect and image name
>docker inspect de3fa2ea8d72
Please help to solve
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
[micro.txt](https://github.com/dotnet/core/files/3406546/micro.txt)

**Comment by carlossanlop** [comment]
@rowanmiller can you please look into this?
CC @MichaelSimons in case he detects something wrong in the Docker file.

**Comment by MichaelSimons** [comment]
`Docker ToolBox` is a legacy solution as noted at the top of the [installation instructions](https://docs.docker.com/toolbox/toolbox_install_windows/).  Is it possible for you to run through the tutorial with [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/)?

**Comment by carlossanlop** [comment]
Closing due to 1 month of inactivity.
