### ISSUE TITLE
dotnet restore can't find package if same package is included in library project

### ISSUE THREAD

**Issue by chriskdon** [dotnet/core#306]
I have two projects, that both include `Microsoft.ASpNetCore.Mvc: "1.0.1"`. If I reference one project in another the main web project cannot find `Microsoft.ASpNetCore.Mvc: "1.0.1"`. 

Running `dotnet restore` on the main project gives the error:  `project.json: error NU1001: The dependency Microsoft.ASpNetCore.Mvc >= 1.0.1 could not be resolved.`

However if I comment out `"Microsoft.AspNetCore.Mvc": "1.0.1"` on the main project then it will compile and run perfectly.

`dotnet --version`: `1.0.0-preview2-003131`

Example Configs

Main ASPNet Core Project project.json:

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },

    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "MyLibrary": { "target": "project" }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

MyLibrary example project.json:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {
    "Microsoft.ASpNetCore.Mvc": "1.0.1"
  },
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NETStandard.Library": "1.6.0"
      }
    }
  }
}
```

**Comment by Petermarcu** [comment]
@piotrpMSFT @davidfowl I believe this is a known issue with the project.json world. Do we need any issue tracking this somewhere or is it addressed in the msbuild world?

**Comment by piotrpMSFT** [comment]
I'd like to hear @rrelyea's input on this one. We're doing a bunch of work to make sure transitive dependencies work as they did in PJ, but this error message is coming from NuGet and we need to be sure the scenario is covered in the new client.

**Comment by Petermarcu** [comment]
Thanks, lets make sure we get an issue in a place where we can track it as nobody is tracking issue on this repo.

**Comment by Petermarcu** [comment]
@piotrpMSFT @rrelyea, any input here?

**Comment by davidfowl** [comment]
I think this is fixed in msbuild. In `project.json` you just need to use the "right" case.

**Comment by richlander** [comment]
Please re-activate if this is still the case.
