### ISSUE TITLE
Error during the build process

### ISSUE THREAD

**Issue by boMeX** [dotnet/core#3060]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Can you please tell us what was the problem you encountered?

**Comment by karelz** [comment]
1 week no response, closing. Feel free to reopen if there is more info available. Thanks!
