### ISSUE TITLE
Support documentation inconsistent with official support policy

### ISSUE THREAD

**Issue by maxnorth** [dotnet/core#3068]
# Issue Title

Support documentation inconsistent with official support policy

# General

The documentation in this repo [describing support lifecycle](https://github.com/dotnet/core/blob/e2f22a7106860c0e5dc98bb36dc648a779944ad5/microsoft-support.md#long-term-support-lts-releases) says that LTS releases are supported for one of two periods, 1) three years total, or 2) one year after the next LTS release, with the period that ends *sooner* being selected.

This is in disagreement with the [official support policy specified here](https://dotnet.microsoft.com/platform/support/policy/dotnet-core), which says that the period that ends *later* is selected.

Just want to get a firm answer on this and ideally get the documents to agree with eachother.

**Comment by carlossanlop** [comment]
@leecow @richlander can you please take a look?

**Comment by carlossanlop** [comment]
21 days with no answer, pinging @leecow @richlander

**Comment by leecow** [comment]
https://dotnet.microsoft.com/platform/support/policy/dotnet-core is the correct formulation. I'll update the github blurb to be in agreement.
