### ISSUE TITLE
Unable to instal .net core on raspbian buster lite

### ISSUE THREAD

**Issue by NimaVibeVans** [dotnet/core#3069]
# Issue Title

Ran through script commands however ran into the same issue on all attempts including corrections when installing .netcore: $sudo apt-get install dotnet-sdk-2.2

E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

# General

HW: 
raspberry pi 3B

OS: 
Raspbian Buster Lite
Minimal image based on Debian Buster
Version:July 2019
Release date:2019-07-10
Kernel version:4.19
Size: 426 MB

clean install enabled SSH and installed C++ Boost libraries.

**Comment by carlossanlop** [comment]
@NimaVibeVans did you add the dotnet repository before attempting to install the package?

**Comment by NimaVibeVans** [comment]
Hi Carlos,

Thank you for responding. Yes, I was able to resolve the issue.

Regards,
Nima
