### ISSUE TITLE
Cross platform single file executable compilation

### ISSUE THREAD

**Issue by AhmadChaker** [dotnet/core#3070]
I've been testing out single file self-contained executable functionality in .NET core 3.0 preview 6.
I've been using the following command:
dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true

Is it possible to run the command above on windows with an osx-x64 switch to get a self-contained MAC executable?

**Comment by carlossanlop** [comment]
@livarcocc @nguerrera are you the best contacts to help with this question?

**Comment by livarcocc** [comment]
Yes. Cross-publishing is supported.

**Comment by carlossanlop** [comment]
12 days of inactivity and question has been answered. Closing.
