### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by chethan-marideva** [dotnet/core#3071]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows 10

![image](https://user-images.githubusercontent.com/18300756/61703674-b7e13980-ad5f-11e9-9de0-e90b9d6fc13f.png)

The docker daemon is running
![image](https://user-images.githubusercontent.com/18300756/61704006-684f3d80-ad60-11e9-87c0-099facd8b07d.png)

**Comment by Boskim0n0** [comment]
this happens to me sometimes. I restart the hyper-V virtual machine management service and restart dockers and works. Not sure why.

**Comment by carlossanlop** [comment]
@MichaelSimons would you mind assisting with this question?

**Comment by MichaelSimons** [comment]
This looks to be a general Windows Container issue rather than something related to the .NET images themselves.  A better place to get help would be on the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).

**Comment by carlossanlop** [comment]
Thanks @MichaelSimons, I'll close the issue since it seems to be external.
