### ISSUE TITLE
failed to laod file 

### ISSUE THREAD

**Issue by mounirzz4** [dotnet/core#3076]
my command was a dotnet new webapp  -o mywebapp --no-https and it tells me that it failed to load the DLL from the file and it tells me to install .net core prerequisites

**Comment by carlossanlop** [comment]
Did you make sure to close and reopen the command line window after installing dotnet? The environment variables need to get updated, but if you had a CLI open while installing, they won't get updated.

**Comment by carlossanlop** [comment]
1 week old with no followup. Closing.
