### ISSUE TITLE
What's next version after preview7?

### ISSUE THREAD

**Issue by niltor** [dotnet/core#3079]
# What's next version after preview7?  preview 8  or  RC?

I believe that  many programer want to learn or try netcore with RC version ,and now `preview 7`  was available, in roadmap, we knew that `RC` will be released on `july`. 
 **So  will it be on time?**

**Comment by karelz** [comment]
Preview 7 was released in July: see #3075

**Comment by AlseinX** [comment]
So why is this issue closed?
Everyone is looking forward to it.
Is the RC put off?
@karelz

**Comment by karelz** [comment]
Preview 7 is RC. It is go-live license. Check the release details.
