### ISSUE TITLE
Mac: installing newer version doesn’t remove the old one

### ISSUE THREAD

**Issue by lednhatkhanh** [dotnet/core#3081]
So I’ve updated `dotnet core 3.0` to preview7 and still see the old version doesn'
t get cleaned while running `dotnet --info`:

![image](https://user-images.githubusercontent.com/9303093/61764263-c5033480-ae02-11e9-99d5-677225936610.png)

Also, there is no uninstaller for mac, so what should I do to clean the old version, I don't want my disk to be full just by updating the dotnet.

Thank you.

**Comment by leecow** [comment]
Thanks, @lednhatkhanh. We're doing two things to help with this. 1) We're in the process of creating a tool which will help with the cleanup of previous installations and will hopefully have that available soon. 2) We will be redesigning the Mac installers for a later release (probably early next year) which will automatically remove the previous version as part of the installation proces.

**Comment by carlossanlop** [comment]
@leecow is this still actionable or can we consider it answered and close it?

**Comment by leecow** [comment]
I think we can close it now.
