### ISSUE TITLE
Child node "2" exited prematurely / StackOverflow Exception on Build

### ISSUE THREAD

**Issue by peter-bull** [dotnet/core#3083]
# Issue Title

Child node "2" exited prematurely / StackOverflow Exception on Build with .NET Core 3.0 Preview 7 when referencing a WPF Class Library Project from an ASP.NET Core 3.0 Project

# General

I have a project which has a shared Class Library Project that uses the Windows Desktop SDK, this library which is used by a WPF Desktop Project (to offer desktop based ui but with functionality in core class library) and a ASP.NET Core Project (to offer web-based ui but re-used all other functionality) and this built in .NET Core 3.0 Preview 6 but does not build in .NET Core 3.0 Preview 7 - this can be easily replicated by creating a Class Library project and modifying the .csproj as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
	<UseWPF>true</UseWPF>
  </PropertyGroup>
</Project>
```

Then by creating a ASP.NET Core 3.0 Web Application and referencing this library, you don't need to create another project for WPF one as when referenced and built either a **Child node "2" exited prematurely** error will occur in **Visual Studio 2019 Preview 4** or a **StackOverflow** when doing **dotnet build** from the command line, this works in .NET Core Preview 6 without any errors but can be reproduced easily with just the two project types mentioned

**Comment by LeeDumond** [comment]
I can verify, I am having the identical issue on Preview 7. Worked on Preview 6 with no problem.

**Comment by danmosemsft** [comment]
When you get `Child node "2" exited prematurely` there will be text pointing to a log file in your temp folder. Can you please include the content of that?

**Comment by danmosemsft** [comment]
Also could you please reopen in https://github.com/microsoft/msbuild   and close this?

**Comment by peter-bull** [comment]
I'll
