### ISSUE TITLE
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

### ISSUE THREAD

**Issue by kjjghfhfjgv** [dotnet/core#3087]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.108
Operating System: Linux Ubuntu 18.04 - x64

sudo apt-get install -y gpg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpg is already the newest version (2.2.4-1ubuntu1.2).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mono-complete : Depends: mono-roslyn (= 6.0.0.313-0xamarin3+ubuntu1804b1) but it is not installable
 mono-devel : Depends: mono-roslyn (= 6.0.0.313-0xamarin3+ubuntu1804b1) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by danmosemsft** [comment]
Hello. Did you try what was suggested? Are you still blocked?

**Comment by carlossanlop** [comment]
1 week old with no followup. Closing.
