### ISSUE TITLE
Visual studio blazor templates preview 7 - client side and full stack both show same descriptions

### ISSUE THREAD

**Issue by BlazorDotCA** [dotnet/core#3089]
With the latest preview version of visual studio (16.3 Preview 1) - if you create a new Blazor project from the "File -- New" then it shows 3 different Blazor templates to choose from but 2 of them show the exact same description. The 2nd and 3rd  ones say "Blazor WebAssembly App" and they have the same description that says "A project template for creating a Blazor app that runs on WebAssembly. This template can be used for web apps for rich dynamic user interfaces (UIs)."

They create different templates too -- one creates the one known as a "full stack webassembly" (with the 3 projects) and the other one creates the client-only blazor template (1 project created).

**Comment by carlossanlop** [comment]
Can you please report this issue from the "Send Feedback" option within Visual Studio?

**Comment by carlossanlop** [comment]
Closing as it's not a dotnet related issue.
