### ISSUE TITLE
No package aspnetcore-runtime-2.1.0-1 available.

### ISSUE THREAD

**Issue by caobo171** [dotnet/core#3093]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-2.1.0
Operating System: Linux CentOSx64

I see "No package aspnetcore-runtime-2.1.0-1 available."
when I run "yum install aspnetcore-runtime-2.1.0-1"

How can I fix it ?

**Comment by carlossanlop** [comment]
Hi @caobo171, did you make sure to register the repository as the instructions explained?

**Comment by carlossanlop** [comment]
1 week old with no response. Closing.
