### ISSUE TITLE
When will "Supports VB ##.#" be included in the .NET Core release information?

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/core#3094]
I can see many useful VB runtime members and windows desktop related VB templates have been ported to .NET Core 3.0 . But VB is still not listed in the [release information page](https://dotnet.microsoft.com/download/dotnet-core/3.0) . I want to know when can we see "Supports VB 16.0-preview" in the release information.

**Comment by danmosemsft** [comment]
@leecow @KathleenDollard this is feedback on what's on https://dotnet.microsoft.com/download/dotnet-core/3.0 page

**Comment by leecow** [comment]
We do have a place for the information in the data which drives the site but need to get more consistent with including updates. I'll work with @rowanmiller to have it surfaced on the release pages.
