### ISSUE TITLE
this version is no longer found

### ISSUE THREAD

**Issue by jakehockey10** [dotnet/core#3096]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-2.2.203
Operating System: Linux Ubuntu 19.04 - x64

I receive the following message when I try any of the 3 approaches mentioned on the page above: `E: Version '2.2.203-1' for 'dotnet-sdk-2.2' was not found`

**Comment by carlossanlop** [comment]
Hi @jakehockey10 , did you make sure to add the key and repository before attempting to install? What does autocomplete give you as results when you type "sudo apt-get install dotnet-" and then the tab key?

**Comment by carlossanlop** [comment]
2 weeks old with no response. Closing.
