### ISSUE TITLE
My Live

### ISSUE THREAD

**Issue by Edik1012** [dotnet/core#3097]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-2.2.108
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
We'll need to understand the details of what you're seeing. Feel free to re-open this issue with those details if you're still having troubles.
