### ISSUE TITLE
"Microsoft.AspNetCore.Mvc.ViewFeatures.Internal" can not find in dotnet core 3.0.0-preview7-27912-14

### ISSUE THREAD

**Issue by Benknightdark** [dotnet/core#3098]
After I upgrade my dotnet core 2.2 MVC  application to 3.0.0-preview7-27912-14, my custom razor html extesion can not find   "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal".

![image](https://user-images.githubusercontent.com/5799487/61920145-29510000-af8b-11e9-9f0d-7e954c654f5a.png)

And, after "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal" can not find , here is some function I can not use , such as ExpressionHelper and ExpressionMetadataProvider.

![image](https://user-images.githubusercontent.com/5799487/61920252-8baa0080-af8b-11e9-92a5-5ef9044ac2ff.png)

Here is my example github url :  https://github.com/Benknightdark/dotnetcore3v7

**Comment by carlossanlop** [comment]
@Pilchie is this something you can help with?

**Comment by omajid** [comment]
Sounds like https://github.com/aspnet/AspNetCore/issues/4932

> In ASP.NET Core, pubinternal types are types that are declared as `public` but put in an `.Internal` namespace. While these types are public they have no support policy and are subject to breaking changes. Unfortunately accidental use of these types has been common, resulting in breaking changes to these projects and limiting our ability to maintain the framework.
>
> In ASP.NET Core 3.0, we are updating all pubinternal types in MVC to either be public in a supported namespace, or internal as appropriate. This includes types in the following namespaces:
>
>
>    Microsoft.AspNetCore.Mvc.ViewFeatures.Internal

**Comment by Pilchie** [comment]
@rynowak

**Comment by rynowak** [comment]
We answered the same question here: https://github.com/aspnet/AspNetCore/issues/12643#issuecomment-515702458

**Comment by Pilchie** [comment]
Closing, as this is answered.
