### ISSUE TITLE
"Get started" is not working as expected on OSX

### ISSUE THREAD

**Issue by avoxm** [dotnet/core#31]
I followed all the steps describer in http://dotnet.github.io/getting-started/ for OSX

And here what I see in console after running "dotnet run"

**Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**

**Comment by qnnnnez** [comment]
I got that too with Ubuntu.

**Comment by hunter-xue** [comment]
I ran into the same issue: 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by rjcobain** [comment]
`dotnet compile --native` outputs a working executable

**Comment by justinmchase** [comment]
:+1: 

After installation steps to reproduce on osx:
```
$ dotnet new
$ dotnet restore
$ dotnet run # error
```

**Comment by blackdwarf** [comment]
Given that things changed significantly between the time when this issue was opened and now, I'm going to close this issue. For any issues with the command line .NET Core tools, please file issues on the dotnet/cli repo.
