### ISSUE TITLE
Wrong package aspnetcore-runtime-2.2 on SLES 12.x

### ISSUE THREAD

**Issue by rtssrl** [dotnet/core#3100]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sles/runtime-current
Operating System: Linux SLES 12.4 - x64
Dotnet core 2.2.6

Following instructions, got package aspnetcore-runtime-2.2.6-rh.rhel.7-x64.rpm installed (it looks like a redhat 7 package)
dotnet core doesn't works (Microsoft.AspNetCore.App not present)

Downloaded http://packages.microsoft.com/sles/12/prod/aspnetcore-runtime-2.2.6-x64.rpm, run 
Run: zypper in aspnetcore-runtime-2.2.6-x64.rpm
Now it works

**Comment by leecow** [comment]
Errant packages have been removed from the sles repo.
