### ISSUE TITLE
i can't open the program 

### ISSUE THREAD

**Issue by shrouk123** [dotnet/core#3102]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmosemsft** [comment]
Can you give more details?

**Comment by leecow** [comment]
Closing due to lack of info from the OP. Feel free to re-open with additional details if you're still having troubles.
