### ISSUE TITLE
Build Error VS2019 for Mac 8.2 'The "ResolvePackageAssets" task failed unexpectedly.'

### ISSUE THREAD

**Issue by wuyuimac** [dotnet/core#3105]
# Issue Title

Build Error VS2019 for Mac 8.2 'The "ResolvePackageAssets" task failed unexpectedly.'

# General

/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018: “ResolvePackageAssets”task failed unexpectedly.。
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018: System.ArgumentOutOfRangeException: Offset must be within plus or minus 14 hours.
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018: Parameter name: offset
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.DateTimeOffset.ValidateOffset (System.TimeSpan offset) [0x0004a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/DateTimeOffset.cs:908 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.DateTimeOffset..ctor (System.DateTime dateTime) [0x0001d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/DateTimeOffset.cs:82 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.DateTimeOffset.FromFileTime (System.Int64 fileTime) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/DateTimeOffset.cs:522 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.IO.FileStatus.GetLastWriteTime (System.ReadOnlySpan`1[T] path, System.Boolean continueOnError) [0x00010] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs:187 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.IO.FileSystemInfo.get_LastWriteTimeCore () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.Unix.cs:60 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.IO.FileSystemInfo.get_LastWriteTimeUtc () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.cs:115 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.IO.FileSystemInfo.get_LastWriteTime () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.cs:109 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.IO.FileSystem.GetLastWriteTime (System.String fullPath) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:513 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at System.IO.File.GetLastWriteTimeUtc (System.String path) [0x00006] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:239 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader.CreateReaderFromDisk (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.Byte[] settingsHash) [0x00008] in <a7945d89c0ac41f8a1c76203a2991e34>:0 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task) [0x00015] in <a7945d89c0ac41f8a1c76203a2991e34>:0 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups () [0x00000] in <a7945d89c0ac41f8a1c76203a2991e34>:0 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore () [0x00018] in <a7945d89c0ac41f8a1c76203a2991e34>:0 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <a7945d89c0ac41f8a1c76203a2991e34>:0 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:573 
/usr/local/share/dotnet/sdk/2.1.701/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:810

**Comment by danmosemsft** [comment]
@tarekgh can you see how this could happen? most of the code in mono here is corefx. I think it is
```c#
        internal DateTimeOffset GetLastWriteTime(ReadOnlySpan<char> path, bool continueOnError = false)
        {
            EnsureStatInitialized(path, continueOnError);
            if (!_exists)
                return DateTimeOffset.FromFileTime(0); <---
```
Maybe misconfigured time zones on the machine? Should this move to mono repo?

**Comment by tarekgh** [comment]
The only logical reason here is the machine using up-normal time zone settings which has Utc offset less/more than 14 hours. 

https://github.com/dotnet/coreclr/blob/ac84ed3ce0bfecb74def2d3f86100c4ee5e323aa/src/System.Private.CoreLib/shared/System/DateTimeOffset.cs#L74

https://en.wikipedia.org/wiki/List_of_UTC_time_offsets
https://en.wikipedia.org/wiki/Time_zone
```
Most of the time zones on land are offset from Coordinated Universal Time (UTC) by a whole number of hours (UTC−12:00 to UTC+14:00)
```

@wuyuimac could you send the time zone information on the failed Mac machine?

**Comment by wuyuimac** [comment]
jamesdeMacBook-Pro:~ james$ date
Mon Jul 29 10:34:21 PST 2019
jamesdeMacBook-Pro:~ james$ date -R
Mon, 29 Jul 2019 10:35:06 +0800

**Comment by traffichero** [comment]
I have exactly the same issue - here's my info

mortens-mbp:~ morten$ date
Mon Jul 29 17:34:24 PST 2019
mortens-mbp:~ morten$ date -R
Mon, 29 Jul 2019 17:34:26 +0800

**Comment by tarekgh** [comment]
@danmosemsft this may be interesting to Mono to look at as the failing scenario is using PST time zone which cannot report UTC offset more/less 14 hours. Does mono using our TimeZoneInfo implementation? or they are using their own implementation? 

I am asking because if they are using their own implementation, would be nice to check what it returns as Utc offset when using PST and using Min DateTime (i.e. DateTime(1, 1, 1)). I am asking about using Min Date because I know in some cases System.IO can report the file date with min date when cannot retrieve it from the OS.

**Comment by danmosemsft** [comment]
>Does mono using our TimeZoneInfo implementation? or they are using their own implementation?

The code in the stack above is ours (`.../external/corefx/src/...`) so I"m guessing ours (?) 

@traffichero are you able to build a simple hello world app on the command line for Mono? Perhaps we can try providing code that just does `return DateTimeOffset.FromFileTime(0);` as in this repro and that will make it simpler to investigate.

**Comment by tarekgh** [comment]
> The code in the stack above is ours (.../external/corefx/src/...) so I"m guessing ours (?)

I am not sure if mono include the TimeZoneInfo*.cs files in their build or not. likely yes but I am not sure. 

> return DateTimeOffset.FromFileTime(0)

This is a good idea to try on mono stack on that failing machine.

**Comment by srdmnc** [comment]
Any solution to this issue?

**Comment by danmosemsft** [comment]
Hopefully @tarekgh can help engage with Mono folks.

**Comment by srdmnc** [comment]
@danmosemsft  This issue has also been raised [here](https://github.com/dotnet/sdk/issues/2251#issuecomment-389951448) before. 

By the way, I'm using VS 2019 Mac (for XF development)
System Time: UTC+8

**Comment by srdmnc** [comment]
This [solution](https://developercommunity.visualstudio.com/content/problem/607287/vs-for-mac-2019-broke-with-netcore-22107-sdk.html) fixed my problem.

**Comment by tarekgh** [comment]
@JeremyKuhne I suggested to change the Systsem.IO behavior for the missing files to have the time stamp of Linux epoch and not DateTime.MinValue https://github.com/dotnet/corefx/issues/29820#issuecomment-403320018 is there a chance to do that in 3.0? 

@srdmnc what time zone you had in your machine when the problem occurred?

@wuyuimac if you try changing the time zone to something else, would it work around the issue you are seeing?

**Comment by lambdageek** [comment]
This is mono/mono#15887.  The fix for mono 2019-02 (aka Mono 6.0 - used by VS for Mac 8.2) was done in our fork of corefx in mono/corefx#316 which was picked up by mono/mono#15960 and  merged as commit https://github.com/mono/mono/commit/6fa465240f20d68f680f26a26089f5e5e62780dd. Packages of **Mono 6.0.0.320 or later** should have the fix.

**Comment by tarekgh** [comment]
closing per @lambdageek comment.

**Comment by danmosemsft** [comment]
Thanks - I should have seen that Mono dupe.

**Comment by srdmnc** [comment]
> 
> @srdmnc what time zone you had in your machine when the problem occurred?
> 
@tarekgh  Asia/Manila (but even if I change the time-zone the error persist).
