### ISSUE TITLE
.NET

### ISSUE THREAD

**Issue by kingotu** [dotnet/core#3106]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\benotu> .NET --info
'.NET' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\benotu>

**Comment by josephmoresena** [comment]
.NET? Shouldn't be "dotnet"?

**Comment by danmosemsft** [comment]
Yep, @kingotu you should type "dotnet --info"

I'm going to close this, please reactivate if it's not resolved

**Comment by kingotu** [comment]
Thank you very much for your support and I have been able to activate it
