### ISSUE TITLE
Error parsing reference: "mcr.microsoft.com/dotnet/core/sdk:2.2 AS build" 

### ISSUE THREAD

**Issue by ravikumar-singi** [dotnet/core#3108]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/docker-image
Operating System: windows 10

docker build -t mymicroservice .
Sending build context to Docker daemon 14.34 kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
Error parsing reference: "mcr.microsoft.com/dotnet/core/sdk:2.2 AS build" is not a valid repository/tag: invalid reference format

**Comment by carlossanlop** [comment]
@MichaelSimons would you mind helping figure this issue out?

**Comment by MichaelSimons** [comment]
@ravikumar-singi - can you share the output from running `docker version`?  Given this error, I suspect that you may be running an older version of Docker which doesn't support [multi-staged builds](https://docs.docker.com/develop/develop-images/multistage-build/).  Support was added in 17.05.

**Comment by carlossanlop** [comment]
Closing as non-actionable due to 12 days of inactivity.

**Comment by aghazadehm** [comment]
I've the same issue
`# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /source
COPY . .
RUN donetn restore "./CustomerApi/CustomerApi.csproj" --disable-parallel
RUN donetn publish "./CustomerApi/CustomerApi.csproj" -c Release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal
WORKDIR /app
COPY --from=build /app ./
RUN dotnet restore

EXPOSE 5000

ENTRYPOINT ["dotnet", "CustomerApi.dll"]`

Docker version 17.03.1-ce-rc1, build 3476dbf
win 10

`docker build --rm -t first-docker .`

output:
Sending build context to Docker daemon  55.7 MB
Step 1/11 : FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
Error parsing reference: "mcr.microsoft.com/dotnet/sdk:6.0 AS build" is not a valid repository/tag: invalid reference format

**Comment by Sudhar287** [comment]
same error as above ^
```
Sending build context to Docker daemon 112.9 MB
Step 1/10 : FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
Error parsing reference: "mcr.microsoft.com/dotnet/sdk:6.0 AS build" is not a valid repository/tag: invalid reference format
```
