### ISSUE TITLE
.Net core 2.2 api not properly deployed on kestrel/nginx

### ISSUE THREAD

**Issue by JimSmith99** [dotnet/core#3110]
Probably same problem as here: https://github.com/dotnet/core/issues/948

My setup: 
//Program.cs
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .UseUrls("http://*:6980");
```
//launchSettings.json
` "applicationUrl": "https://localhost:6980",`

//parts of yml:
```
stage: build    
script:
- "dotnet restore"
- "dotnet build appName -c Release"
- "dotnet publish appName -c Release -o ../artifacts/appName"
```
    
After deploy, the old api is served, though I see new dll in www folder.
only way I have found how to solve this is: 
1. sudo netstat -plnt
2. sudo kill -9 [pid from running sudo netstat -plnt]
3. Refresh page

---> Now latest version of the api is served.

How do I fix this?

Edit:
When I run dotnet mydll.dll I get:
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://127.0.0.1:6980: address already in use.

This happens regardless of port and is always resolved by steps 1-3 above.

**Comment by carlossanlop** [comment]
@Pilchie is this something for your team to help figure out?

**Comment by Pilchie** [comment]
@anurse

**Comment by anurse** [comment]
The only steps you showed are publishing the new app to the directory. What takes care of shutting down the old version and starting up the new instance?

**Comment by Pilchie** [comment]
Closing due to no response.  @JimSmith99 let us know if this is still an issue for you and the answer to @anurse's question.

**Comment by lostphenomenon** [comment]
Would be interested in a solution if anyone has one

**Comment by anurse** [comment]
@lostphenomenon Can you file an issue in aspnet/AspNetCore with detailed steps describing how you can reproduce the issue? We can investigate further there. Since this issue is closed, it's not tracked in our triage process.
