### ISSUE TITLE
error encountered

### ISSUE THREAD

**Issue by michaelscofieldk** [dotnet/core#3112]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

after i typed in dotnet run in my terminal, it shows this   Couldn't find a project to run. Ensure a project exists in C:\Users\okunola michael\Desktop\C#, or pass the path to the project using --project.   

Operating system version: 64bit

error message: Couldn't find a project to run. Ensure a project exists in C:\Users\okunola michael\Desktop\C#, or pass the path to the project using --project.

code sample:
 using System;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

**Comment by leecow** [comment]
Can you confirm that you are in the same directory as your test project?

**Comment by carlossanlop** [comment]
1 week old with no followup from creator. Closing.
