### ISSUE TITLE
ASP.NET Core 2.1 SCD will not start

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#3115]
# Issue Title
ASP.NET Core 2.1 SCD will not start

# General
I have not struck this before. I built a win10-x64 SCD which works fine on developer machines but will not run on a production machine. The executable just returns to the command line with no message. Nothing in event log either.

How can I debug this on the client production machine?
The first line of Main is a Trace.WriteLine which does no get executed.

Any ideas gratefully received.

**Comment by carlossanlop** [comment]
@Pilchie can you assist with this issue?

**Comment by Pilchie** [comment]
@anurse any ideas?

**Comment by anurse** [comment]
Nothing immediate comes to mind. Does a `Console.WriteLine` at the start of `Main` get executed? If not, it sounds like an issue in the lower level of the stack (the host or runtime).

Could be a publishing issue maybe. @genifycom can you share a runnable sample that reproduces the problem (at least on your client machine, even if it doesn't repro on other machines) so we can see the full context?

**Comment by Pilchie** [comment]
Closing due to lack of response.  @genifycom if this is still an issue, can you reply with some of the info that @anurse asked for?
