### ISSUE TITLE
release-metadata/2.2/releases.json does not contain 2.2.401 SDK

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/core#3118]
I'm unable to install the 2.2.401 SDK using the DevOps "UseDotNet" task. Not sure if that task is using the wrong releases-index.json (related to #3114 ?) or if this is a bug in the json files here.

The DevOps UseDotNet task [gets the release info](https://github.com/microsoft/azure-pipelines-tasks/blob/9002e807e472a2f7ee77fadbba3bbff7cd6eadde/Tasks/UseDotNetV2/versionfetcher.ts#L292) from https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json.

That file contains the following block for the 2.2 channel - pointing to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json

![image](https://user-images.githubusercontent.com/4581460/62130019-5fb6b400-b2d8-11e9-8ded-7bf394e086c1.png)

However, that file does NOT contain the latest 2.2.401 SDK. 

![image](https://user-images.githubusercontent.com/4581460/62130176-bde39700-b2d8-11e9-9c65-32402f0d2bad.png)

**Comment by leecow** [comment]
Sorry about that. https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json has been updated to include 2.2.401.

cc @vivmishra

**Comment by cwe1ss** [comment]
Thank you very much @leecow for the quick fix!
