### ISSUE TITLE
In .NET Core 3.0 Preview 7 ResXResourceReader class is unavailable

### ISSUE THREAD

**Issue by kehoej** [dotnet/core#3121]
In .NET Core 3.0 Preview 7 ResXResourceReader class is unavailable.  The documentation states that it is available, but it is not.  

https://docs.microsoft.com/en-us/dotnet/api/system.resources.resxresourcereader?view=netcore-3.0

**Comment by carlossanlop** [comment]
@kehoej can you please provide a code example? It will help us assist you better.

**Comment by kehoej** [comment]
I found it, I was looking in Microsoft.NET.Sdk and not Microsoft.NET.Sdk.WindowsDesktop
