### ISSUE TITLE
Add support for ClearLinux

### ISSUE THREAD

**Issue by robertbaker** [dotnet/core#3124]
# Add support for ClearLinux

# General

ClearLinux is gaining popularity as it's the most performant modern linux distro to date.

In order for PowerShell to add support for ClearLinux, .netcore must add support.

**Comment by leecow** [comment]
Thanks for the request. We regularly evaluate what's available and, as you can imagine, the landscape of distros is large and ever-shifting. 

I did a quick test using a ClearLinux the official Docker image and basic functionality seems to work fine. That's not a support statement, just a note that you should be able to begin experimenting with .NET Core. To install, either use the [linux tar.gz directly](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#installation-from-a-binary-archive) or use the dotnet-install.sh [script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).

**Comment by carlossanlop** [comment]
@leecow seems like ClearLinux worked fine. Closing.
