### ISSUE TITLE
Again the question on when the first Release Candidate will come out

### ISSUE THREAD

**Issue by AlseinX** [dotnet/core#3125]
As explained in #3079 which is questionably closed without being answered.

The roadmap tells that both preview7 and the first RC will come out in July 2019.
Does it mean that RC1 is based on preview7?

But, when will RC1 come out? It is scheduled in July but it is the last day of July today.
And what will preview8 be? The daily build tells that there is a preview9.

Does it mean that RC1 is put off to be based on preview9 which means September, in which GA is scheduled to come out? Or will there be both RC and preview channels being available during these months?

That's so confusing really.

Please don't close this issue as "preview7 was released", thank you.

**Comment by dagood** [comment]
This caught my eye, and I found that the 3.0 preview 7 blog post has similar questions in the comments, with answers: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/

> https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/#comments-2564
> 
> > Should it be RC instead of preview?
> 
> We decided to stop using value-oriented terms like RC some time back. The problem is that we have to make the change to "rc" in our build relatively early before we've established that it is indeed an RC. There are three things at play: a date, a quality level and avoiding late changes ... pick 2. We prioritized the first and the last and then can make a judgement late in a given preview release what the quality level is. We often need to align with a conference or another product so having a fluid date isn't an option (unless something really bad is discovered).

> https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/#comments-2565
> 
> You can consider Preview 7 the first RC.

From the blog post itself, this is the part that I would *think* is the RC implication people are wanting to see, however I'll admit I'm not sure what RC fully meant for .NET Core releases:

> ## Go Live
> 
> NET Core 3.0 Preview 7 is supported by Microsoft and can be used in production. We strongly recommend that you test your app running on Preview 7 before deploying Preview 7 into production. 

Hope that helps. I do think it's not clear in the docs directly in this repo.

/cc @karelz

**Comment by AlseinX** [comment]
So `RC` is cancelled and `preview` keeps being used before GA comes out, even though supported in production?
And yet another confusing thing is, why is the daily build preview9, 2 versions ahead of the released version?
My guess is that preview8 is archived without tested or documented?

**Comment by dagood** [comment]
My reading of the comments is that RC is no longer used to describe .NET Core releases, but preview 7 fits the old RC expectations. What are you looking for in an RC release that isn't provided in preview 7?

> why is the daily build preview9, 2 versions ahead of the released version?

Preview 8 is currently stabilizing for release. I'm guessing you're looking at SDK daily builds--those repos have a separate branch for preview 9 to continue dev work while 8 stabilizes.

**Comment by leecow** [comment]
Davis is correct - we simply are not "branding" releases as RC any longer. When we feel the quality has attained a sufficient level to warrant more critical usage, we communicate the "go live" status and will iterate there until GA. Preview 8 is in the final stabilization stages now and is expected to be released in a few weeks. This is all coming together in the release/3.0.100-preview8 branch of the core-sdk repo.

**Comment by SeppPenner** [comment]
> Preview 8 is in the final stabilization stages now and is expected to be released in a few weeks

Seems like vacation is canceled for all of you 😅

**Comment by carlossanlop** [comment]
@leecow @dagood is this issue still actionable or should we consider it answered so we can close it?

**Comment by dagood** [comment]
An answer from @AlseinX to this question could spark some more discussion:

> What are you looking for in an RC release that isn't provided in preview 7?

But it's been a while, and the primary question is answered. Closing.
