### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by phuongmychi** [dotnet/core#3126]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/20487309/62179190-d655bf00-b375-11e9-9cca-94526c8ec683.png)

**Comment by lindexi** [comment]
Could you use `dotnet restore` to restore it?

**Comment by carlossanlop** [comment]
No response after the suggestion was provided. Closing due to 14 days of inactivity.
