### ISSUE TITLE
Error dotnet new (2.2.401)

### ISSUE THREAD

**Issue by adyazp** [dotnet/core#3128]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/create
Operating System: Linux Ubuntu 18.04 - x64

dotnet --version
2.2.401

when I exec this command
dotnet new mvc -o myApp

Template "ASP.NET Core Web App (Model-View-Controller)" could not be created.
Object reference not set to an instance of an object.

I have tried 
sudo rm -rf ~/.templateengine/
dotnet new --debug:reinit
and still get this error 

please help me

**Comment by leecow** [comment]
Are you able to do a simple console app? `dotnet new console -o myConsole`

**Comment by adyazp** [comment]
yes I can build simple console app

**Comment by carlossanlop** [comment]
@adyazp Can you try with 3.0 Release? We are not getting any other reports about this. Please open a new issue if you still see problems.
