### ISSUE TITLE
Authorization problem with myget.org in .NET CORE 3.0.100-preview7-012821

### ISSUE THREAD

**Issue by varghesep** [dotnet/core#3138]
# Authorization problem with myget.org in .NET CORE 3.0.100-preview7-012821

When I run the command ```dotnet watch run```, I get the following error:

```
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\NuGet.targets(123,5): error : Unable to load the service index for source https://www.myget.org/F/mycompany/api/v3/index.json. [C:\myproject\myproject.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\NuGet.targets(123,5): error : Response status code does not indicate success: 401 (Unauthorized). [C:\myproject\myproject.csproj]
```

# General

I can still build the application in ```Visual Stduio 2019``` and run it, not from command line due to the above error. I cleared the NuGet cache from the ```Visual Studio 2019``` which did not help. I ran the API install command for ```MyGet``` which also did not help.

**Comment by carlossanlop** [comment]
@livarcocc @nguerrera since this is a CLI issue, can one of you help with this problem?

**Comment by livarcocc** [comment]
This issue should go to NuGet actually. cc @nkolev92

**Comment by nkolev92** [comment]
@varghesep 

How are you authenticating with the feed? 

I'd imagine you needed to install some sort of a plugin in VS. 
You either need: 

1. Clear text creds in the config file. 
2. A plugin from MyGet that allows you do authentication on the commandline. https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin#authentication-in-dotnetexe

In Visual Studio, you install a VSIX, on the commandline, you need a plugin if you want it to work with dotnet.exe. 

Not sure if MyGet has a dotnet.exe plugin.n

**Comment by carlossanlop** [comment]
@varghesep no follow up since August. Closing. Feel free to reopen if you need more help.
