### ISSUE TITLE
RPM url in CentOS install instructions returns 404

### ISSUE THREAD

**Issue by jimbergstrom** [dotnet/core#3141]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-current
Operating System: Linux CentOS / Oracle - x64

## Steps to reproduce

Following the install instructions on https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-current 

1.  Try to install the RPM from https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm

## Expected  behavior

RPM downloads and installs

## Actual behavior

```
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm - transfer failed
```

I think the rpm URL in the instructions for CentOS may need to be updated to 

https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

**Comment by kupokev** [comment]
Adding to the above, if you navigate to https://packages.microsoft.com/config/rhel/7/ in a browser then you can see the rpm package in the directory. However, if you click on the rpm to download it, it pops up an error stating the file is not found.

![image](https://user-images.githubusercontent.com/15756436/62392735-cf71ac80-b52d-11e9-9b68-2c6ca0c90828.png)

**Comment by dagood** [comment]
@leecow, do you know if the Linux repository team is aware of this? (Regardless which repo the docs should point to, this seems to be an obvious bug.)

**Comment by leecow** [comment]
I haven't seen any mail on the issue so will send up a flare now.

**Comment by dagood** [comment]
This is fixed now, thanks @leecow for pinging them.

About the CentOS instructions pointing to the RHEL 7 RPM, https://github.com/dotnet/core/issues/2576 is tracking the general issue of how closely we should map instructions to individual package repositories. So far, we've tended to reuse package repositories between distros and releases as long as they're compatible.
