### ISSUE TITLE
Starting dotnet for the firsttime

### ISSUE THREAD

**Issue by database007** [dotnet/core#3143]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: windows

i typed in the command 
dotnet 

on my command prompt but it shows that the cmd is invalid, what should i do. tahnks

**Comment by FlyingWraptor** [comment]
Invalid? As in not found or this:
![image](https://user-images.githubusercontent.com/38633741/62414688-299e6a80-b61f-11e9-862b-65b060e557a5.png)


The bottom of the install page says:
> If you receive a 'dotnet' is not recognized as an internal or external command error, make sure you opened a new command prompt. If you can't resolve the issue, use the I ran into an issue button to get help fixing the problem.


So did you try that?

**Comment by Boskim0n0** [comment]
Did u installed the SDK? Can u check ur environment variables and see if there is an entry in the path with something like C:\Program Files\dotnet?

**Comment by carlossanlop** [comment]
You probably had a command line window open when you were installing dotnet. You need to close the window and reopen it so the environment variables get updated and you can execute "dotnet". Have you tried that?

**Comment by carlossanlop** [comment]
Closing this issue due to 1 week of inactivity.
