### ISSUE TITLE
Linux 32

### ISSUE THREAD

**Issue by honorarac** [dotnet/core#3144]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
What error did you encounter?

**Comment by carlossanlop** [comment]
Closing due to 1 week of inactivity with no response.
