### ISSUE TITLE
dotnet restore fails on mac (core 3 preview 7)

### ISSUE THREAD

**Issue by binish** [dotnet/core#3148]
# dotnet restore fails on macOS ( Sierra 10.12.6)

dotnet new react -au Individual  => failes
dotnet restore => fails

dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0-preview7-27912-14/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0-preview7-27912-14/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by dragfly** [comment]
Same problem with preview 8 and macOS Sierra 10.12.5


$ dotnet --version
3.0.100-preview8-013656

$ dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19377-01+dd8019d9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  [...]
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  [...]
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0-preview8-28405-07/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0-preview8-28405-07/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by dragfly** [comment]
It seems related to https://github.com/dotnet/corefx/issues/39701
.NET Core 3.0 is not supported on Sierra (10.12) as [it needs at least 10.13](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#macos) 

I guess this issue can be closed

**Comment by jchannon** [comment]
That did it!

**Comment by carlossanlop** [comment]
Seems to be resolved. Closing. Feel free to ping us or reopen the issue if you keep seeing problems.

**Comment by christianscheuer** [comment]
If .NET Core 3.0 needs at least 10.13, shouldn't https://dot.net and https://dotnet.microsoft.com/download be updated so that if you visit those sites on 10.12, you would be redirected to download a version of the SDK that works on these systems?
Or - at least get a more usable error message in the CLI?
I mean, it feels pretty weird that the main web page of the .NET SDK redirects you to download something that doesn't work...
