### ISSUE TITLE
dotnet is not available in internal or external memory

### ISSUE THREAD

**Issue by patllola** [dotnet/core#3151]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
What error did you encounter?

**Comment by carlossanlop** [comment]
No follow up. Closing.
