### ISSUE TITLE
ASP. 

### ISSUE THREAD

**Issue by cantelek** [dotnet/core#3152]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![errors](https://user-images.githubusercontent.com/23206352/62536598-065e0000-b857-11e9-82b7-e7c66dfdfd87.jpg)

**Comment by carlossanlop** [comment]
@cantelek, the error message is letting you know that you have syntax errors. Have you addressed them?

**Comment by carlossanlop** [comment]
No follow up. Closing.
