### ISSUE TITLE
The build failed on Win10

### ISSUE THREAD

**Issue by Prio777** [dotnet/core#3153]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
C:\Users\Prio\myApp>dotnet run
R_C.cs(2,9): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(2,14): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,9): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,16): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,31): error CS1001: Identifier expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,35): error CS1031: Type expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,35): error CS1001: Identifier expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,37): error CS1031: Type expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,37): error CS1001: Identifier expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,37): error CS1003: Syntax error, ',' expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,41): error CS1031: Type expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,41): error CS1001: Identifier expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(3,41): error CS1003: Syntax error, ',' expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(4,9): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(4,15): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(5,9): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(5,15): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(5,28): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(5,30): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(5,59): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]
R_C.cs(5,60): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Prio\myApp\myApp.csproj]

The build failed. Please fix the build errors and run again.

**Comment by carlossanlop** [comment]
Hi @prio777, the error message is telling you that you have syntax errors in your code. Have you addressed them?

**Comment by carlossanlop** [comment]
No follow up. Closing.
