### ISSUE TITLE
can't find program.cs while trying to run dotnet

### ISSUE THREAD

**Issue by TEBOTSO** [dotnet/core#3156]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Not enough information. Please provide more details about the problem you're encountering. From which folder did you run the dotnet command?

**Comment by carlossanlop** [comment]
No follow up. Closing.
