### ISSUE TITLE
cant run dotnet

### ISSUE THREAD

**Issue by TEBOTSO** [dotnet/core#3157]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Not enough information. Can you describe your problem?

**Comment by carlossanlop** [comment]
No follow up. Closing.
