### ISSUE TITLE
Method not captured correctly in production

### ISSUE THREAD

**Issue by WilbertE** [dotnet/core#3158]
Method not captured correctly

I've created an .Net core 2.2 web api and published it to an IIS 8.5 webserver.
We've also created an iOS app that communicates with the api and there is some very strange behaviour:

- When the app makes a valid request it does get the right answer from the api
- When the app makes _exactly_ the same request within a couple of minutes, it returns a 405 'Method not allowed' response.

So in order to see what is beeing captured as Method I used the following code in `startup.cs`:

`await context.HttpContext.Response.WriteAsync("Status code page, Method: " + context.HttpContext.Request.Method);`

Now when I do the request again it says the method for the second request is `T` (only 1 letter) which is ofcourse not valid. I've used Fiddler and just 'replayed' the first request to get the second request, so it should be exactly the same.

See the following image:
![Naamloos](https://user-images.githubusercontent.com/12847317/62649124-8d44d280-b954-11e9-960c-722c8df35006.png)

I'm using
.NET Core 2.2
And it is published to an IIS 8.5 webserver

How on earth is this possible?

**Comment by WilbertE** [comment]
After searching whole evening this might have to do with `AlomFire` https://github.com/Alamofire/Alamofire/issues?utf8=%E2%9C%93&q=is%3Aisue+405

**Comment by Garderoben** [comment]
Hmm wonder if its same problem or related to what i have.

https://github.com/dotnet/core/issues/3162

**Comment by carlossanlop** [comment]
Hey @Pilchie is this something the ASP.NET team can help with?

**Comment by WilbertE** [comment]
The iOS developer fixed it in the Alomfire lib. Didnt had to do with dotnet.

**Comment by carlossanlop** [comment]
Thanks for letting us know, @WilbertE . I will closed the issue as it seems to be resolved.
