### ISSUE TITLE
HttpClient cant authenticate when site is published Blazor Core hosted .Net 3.0 Preview7

### ISSUE THREAD

**Issue by Garderoben** [dotnet/core#3162]
# Issue Title

HttpClient cant authenticate with Bearer when site is published and running in IIS works fine from visual studio.

# General

Maybe im missing something new but i tried the token thats given from both my machine and the publised server in Postman and it works. But from the application it throws "Response status code does not indicate success: 401 (Unauthorized)."

This code was working fine in .net core 2.2 but i made a new project and moving over to .Net Core 3.0 Preview 7 (**Both projects are Blazor ASP.NET Core hosted project**)
![Dotnetproblem](https://user-images.githubusercontent.com/10367109/62686635-64105a80-b9c5-11e9-826e-ecad01e3631c.png)

# .NET Core version on developing machine
![DotnetDevelopComputer](https://user-images.githubusercontent.com/10367109/62686739-928e3580-b9c5-11e9-886b-38107555a26e.png)
# .NET Core version on published machine
![DotnetServerProblem](https://user-images.githubusercontent.com/10367109/62686767-a33eab80-b9c5-11e9-8f3e-eb4ff8f38ee4.png)

**Comment by carlossanlop** [comment]
@Pilchie is this something your team can help with?

**Comment by Pilchie** [comment]
@mkArtakMSFT @danroth27 @blowdart ?

**Comment by blowdart** [comment]
Move it to our repo?

There's no enough to go on here.

- Where are tokens issued from?
- What authentication and authorization services are configured and how?
- Contents of startup.cs, with any secrets removed.

All of the above is needed.

**Comment by Pilchie** [comment]
This issue was moved to aspnet/AspNetCore#13139
