### ISSUE TITLE
installation probleam

### ISSUE THREAD

**Issue by VINITPANDEY** [dotnet/core#3165]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

mono-devel : Depends: ca-certificates-mono (= 6.0.0.319-0xamarin1+ubuntu1804b1) but 5.18.1.28-0xamarin5+ubuntu1804b1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by RadioCaroline** [comment]
https://github.com/mono/monodevelop/issues/8356#issuecomment-519926539

**Comment by carlossanlop** [comment]
@VINITPANDEY did the link provided by @RadioCaroline help fix your issue?

**Comment by carlossanlop** [comment]
No follow up. Closing.
