### ISSUE TITLE
releases.json isn't up to date

### ISSUE THREAD

**Issue by Rutix** [dotnet/core#3166]
# releases.json isn't up to date

The json file located here: https://github.com/dotnet/core/blob/master/release-notes/releases.json (and where the .NET Core SDK Installer build task points to) doesn't seem to be up to date. I am missing a lot of runtimes in there. Some I have checked are 2.1.10, 2.1.11, 2.1.12 (and also the SDKs are missing for example 2.1.801). Is this file still being updated? And why are these runtimes missing? 

Tagging @leecow since he seems to be the last one who updated this file :).

**Comment by svick** [comment]
That file is no longer being updated and instead you should be using https://github.com/dotnet/core/blob/master/release-notes/releases-index.json together with version-specific releases.json (e.g. https://github.com/dotnet/core/blob/master/release-notes/2.1/releases.json). See https://github.com/dotnet/announcements/issues/87 for more details.

Though that announcement also says that the old releases.json should have been removed, which hasn't happened.

**Comment by Rutix** [comment]
@svick ahhh! I totally missed that announcement. I also see now that they updated the azure-pipelines task to point to releases-index.json instead. That they haven't removed it yet is a bit confusing though but good to know I shouldn't look at it anymore!

**Comment by leecow** [comment]
Sorry for the confusion! Obsoleted files (json and csv) have been removed.
