### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by AgieAja** [dotnet/core#3169]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos high siera version 10.13.6

after install dotnet-sdk-2.2.401-osx-gs-x64.pkg,i open terminal,and run command dotnet,i got command not found

**Comment by RobertWang** [comment]
so do i

+1

**Comment by AgieAja** [comment]
thanks,this solved
