### ISSUE TITLE
dotnet msbuild lost resource files in .Net Core 3.0 Preview 7

### ISSUE THREAD

**Issue by Lily721** [dotnet/core#3172]
Hi, 

I got a WPF .net core project, and I found out the resources in output dll is different between right click 'Build' button on Visual Studio and use command line 'dotnet msbuild ***.csproj'. Please try my attached sample. You'll see there's three images under resources folder, and I'd like to pack it to resources, so I added following code to RESX file:

`
  <data name="error" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>error.png;System.IO.MemoryStream, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
`

Then, I build the project in Visual Studio 2019 and following structure when reflect the output dll:

 WpfApp_ResourceTest.Resources.CheckResource.resources
    ┖ error
    ┖ info
    ┖ warning

But, if build this project with 'dotnet msbuild' or 'dotnet build' in command line, all the icon resource will lost. This will cause a big problem for our project, we can not find the resource file by resource key.

Another issue is, if the namespace is A, and my resource file located in B folder with the name C.resx, then it will create A.B.C.resources when you reflect output dll under .Net Core, but it creates A.C.resources when you use framework platform, I guess it is a bug for .Net Core.

Any idea is welcome.
[WpfApp_ResourceTest.zip](https://github.com/dotnet/core/files/3491669/WpfApp_ResourceTest.zip)

**Comment by carlossanlop** [comment]
Thanks for reporting this issue, @Lily721 . I am transferring it to the wpf repo, where they will be able to help you with your problem.

**Comment by carlossanlop** [comment]
This issue was moved to dotnet/wpf#1603
