### ISSUE TITLE
Running two dotnet core apps on the same iis server kills the session of the other app

### ISSUE THREAD

**Issue by kzish** [dotnet/core#3176]
When running two dot net core apps on the same iis server loggin into one app kills the session of the other app,

I have tried:
1) deploying both in process and out of process
2) placing them in the same app pool
3) placing them in different app pool

**Comment by carlossanlop** [comment]
@kzich I assume these are ASP.NET apps? In which case, @Pilchie may know who can help you.

**Comment by Pilchie** [comment]
@anurse @jkotalik ?

**Comment by jkotalik** [comment]
When you say:
> loggin into 

I'm not quite sure what you mean.

One change that could be related is if there is a global configuration change (changing the global applicationhost.config), we may trigger a shutdown of the application if it affects our site path. Logging into one site shouldn't affect the other though. Are the site names different?

**Comment by anurse** [comment]
> When running two dot net core apps on the same iis server loggin into one app kills the session of the other app,

Are you referring to login sessions (i.e. cookies)? If the apps share a domain name but are on separate paths, this could definitely be the case unless you add a path parameter to the cookie.

I'm going to move this to aspnet/AspNetCore since it's more appropriate to discuss there.

**Comment by anurse** [comment]
This issue was moved to aspnet/AspNetCore#13141

**Comment by arnaudov** [comment]
Was there any resolution of this issue? I'm experiencing the same issue when I'm starting two different .net core apps from visual studio in same solution
