### ISSUE TITLE
DefineDynamicAssembly

### ISSUE THREAD

**Issue by athinboy** [dotnet/core#3177]
# Issue Title

What about   AssemblyName has to be unique when invoke   AssemblyBuilder.DefineDynamicAssembly ?

# General

Now there is a error:
CS7069: Reference to type ****** claims it is defined in '****', but could not be found

**Comment by athinboy** [comment]
[https://developercommunity.visualstudio.com/storage/temp/87898-vs.png](url)

**Comment by athinboy** [comment]
https://developercommunity.visualstudio.com/storage/temp/87898-vs.png

**Comment by carlossanlop** [comment]
@steveharter, @GrabYourPitchforks, you guys own System.Reflection. Can you help @athinboy figure out his problem?
