### ISSUE TITLE
[Q] Is there any plain to reduce final exe file, compare to other languages, e.g Go?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/core#3179]
Hi,

_Thank you for dot net core, specially v3._

The final output of dot net core app, e.g hello-world, is really big, _[for hello world is currently 23MB](https://github.com/mono/linker/blob/master/src/ILLink.Tasks/README.md)_, is there any plain to reduce the size?

For example the final exe of [hugo](https://github.com/gohugoio/hugo) is ~35MB, it contains huge list of features, I think same app using dot net core will be +100MB.

**Comment by scalablecory** [comment]
There's currently a lot of work being done for .NET 5 to reduce the final exe size for self-contained exes. Thanks for your interest!
