### ISSUE TITLE
.NET Core 3.0 no longer shows on visual Studio 2019 16.2.2 after installing .,net core Preview 8

### ISSUE THREAD

**Issue by franciscohumarang** [dotnet/core#3186]
Hi,

After installing preview 8,I cannot select .NET Core 3.0 for starting a new project. Use Preview SDKS is checked on Tools but still I .net core 3 is not shown on the list. I also performed repair install, also checked installed sdks which shows the previe8, but still to no avail.

**Comment by paolobriones** [comment]
I just installed Preview 8 and updated VS2019 to 16.2.2; the same issue occurs for me

**Comment by franciscohumarang** [comment]
Found this:

To get started with ASP.NET Core in .NET Core 3.0 Preview 8 install the .NET Core 3.0 Preview 8 SDK

If you’re on Windows using Visual Studio, install the latest preview of Visual Studio 2019.

_.NET Core 3.0 Preview 8 requires Visual Studio 2019 16.3 Preview 2 or later_

To install the latest Blazor WebAssembly template also run the following command:

**Comment by ddivita** [comment]
I downgraded to to preview 7 under 16.2.3 and I see the options again

**Comment by prince272** [comment]
I'm also facing the same issue. It's only visible when I use the CLI.
