### ISSUE TITLE
ManagementClass can't work on .NET Core 3.0.0 Preview 8.

### ISSUE THREAD

**Issue by dxh-sc** [dotnet/core#3187]
on .NET Core 3.0.0 Preview 8:  i install NuGet "System.Management", and when i use ManagementClass to get disk information, has a error message: System.Runtime.InteropServices.MarshalDirectiveException: 'Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.'

**Comment by carlossanlop** [comment]
@Anipik you're listed as the owner of System.Management. Do you know what could be the problem?

**Comment by Anipik** [comment]
@carlossanlop I can take a look. 
@dxh-sc It will be helpful if you could provide a repro code ?

**Comment by dxh-sc** [comment]
@Anipik i create .NET Core 3.0.0 Preview 8 wpf app on windows 10, and i want to get disk information.

![image](https://user-images.githubusercontent.com/54095220/63100240-4042ab00-bfa9-11e9-8654-7dce57073f23.png)
 ManagementClass diskClass = new ManagementClass("Win32_Diskdrive");//like "Win32_Process"... also still can't work.
 ManagementObjectCollection dmoc = diskClass.GetInstances();

on first line code, it will report a error message, but works on .net framework.

System.Runtime.InteropServices.MarshalDirectiveException
  HResult=0x80131535
  Message=Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at System.Management.ManagementPath.GetWbemPath(IWbemPath wbemPath)
   at System.Management.ManagementPath.GetWbemPath()
   at System.Management.ManagementPath.get_Path()
   at System.Management.ManagementPath.get_IsEmpty()
   at System.Management.ManagementObject.ManagementObjectCTOR(ManagementScope scope, ManagementPath path, ObjectGetOptions options)
   at System.Management.ManagementObject..ctor(ManagementScope scope, ManagementPath path, ObjectGetOptions options)
   at System.Management.ManagementClass..ctor(ManagementScope scope, ManagementPath path, ObjectGetOptions options)
   at System.Management.ManagementClass..ctor(String path)

**Comment by 0xd4d** [comment]
You should use the latest preview of System.Management which currently is 4.6.0-preview8.19405.3. Don't use 4.5.0.

**Comment by Anipik** [comment]
@dxh-sc as @0xd4d mentioned you need to use the latest version of System.Management instead of 4.5.0
I verified that error occurs with 4.5 but no longer occurs with the latest version.

**Comment by dxh-sc** [comment]
@Anipik @0xd4d ok, thank for your information, so i need to wait the last release version. because now i only can see the 4.5 on nuget.
![image](https://user-images.githubusercontent.com/54095220/63240878-31e3e000-c284-11e9-954c-7d536144548a.png)

**Comment by Anipik** [comment]
@dxh-sc its available on nuget.org. There is a include prelease check box that you need to mark and ten you will be able to see the pre release versions. https://www.nuget.org/packages/System.Management/4.6.0-preview8.19405.3
