### ISSUE TITLE
Nullable DateTime returns time as 12:00 AM

### ISSUE THREAD

**Issue by kephax** [dotnet/core#3188]
# Issue Title
When having a nullable DateTime field in a model, the Date is read from the database while the time isn't and it's set to the default time of 12:00:00 AM

# General
.NET Core 2.2
Windows 10 1903
VisualStudio 2019
mySql database

I have a model:

public class TestModel {
  ...
  public DateTime Date1 { get; set; }
  public DateTime? Date2 { get; set; }
  ...
}

The Database table is generated using the EntityFramework Core.
If I manually set a date and time in the database for Date1 and Date2, when reading the values back in code the date is correct while the time in Date2 is set to 12:00:00 AM. 
With Date1 both the date and time are read correctly.

**Comment by carlossanlop** [comment]
@divega do you know what could be happening here?

**Comment by kephax** [comment]
Hi, I will try to reproduce this again this evening, There has been some weird things happening with our database today, I hope that’s the reason of this bug.

—
Best regards

Pietro Bua

Il giorno 14 ago 2019, alle ore 19:50, Carlos Sanchez Lopez <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@divega<https://github.com/divega> do you know what could be happening here?

**Comment by divega** [comment]
@carlossanlop nothing specific comes to mind.

@kephax if you are able to provide a repro, please create an issue on https://github.com/aspnet/EntityFrameworkCore/ so the EF team can triage.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/EntityFrameworkCore#17363
