### ISSUE TITLE
.net Core 3 Preview 8 - Component @ref attribute not functioning as stated

### ISSUE THREAD

**Issue by nikprotsman** [dotnet/core#3190]
# General

Issue experienced in VS Community 2019 preview, running on Windows 10 pro build 17763

After following migration instruction detailed at this link:
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/

Migrating from .net core 3 preview 7 to preview 8, 

The component reference attribute @ref"" does not work as stated in the post. If the @ref is used alone, a backing field is generated but is not accessible from the @code block. Any attempt to code against the reference produces a build error "The name 'componentRef' does not exist in the current context". 

Addition of a backing field for diagnosis produced build error "The type 'ComponentType' already contains a definition for 'componentRef''. Initial thought is that the field is being automatically created but is not being exposed to the code as expected. 

Removal of the backing field, and addition if the @ref:suppressField attribute produces the expected error "The name 'componentRef' does not exist in the current context". 

Addition of the @ref:suppressField together with the backing field in the @code block allows build to succeed and the application runs as expected. NOTE this is a successful workaround to the issue with only minor code adjustment until the issue can be resolved.

**Comment by carlossanlop** [comment]
@Pilchie could you assist with this issue?

**Comment by Pilchie** [comment]
I believe this is a duplicate of an issue over on AspNetCore.  @mkArtakMSFT ?

**Comment by nikprotsman** [comment]
With a point in the right direction I can confirm this is a duplicate of the AspNetCore issue #13099. 

This issue can be closed and I will track the above mentioned issue for status and clarification. Thank you all for your help.
