### ISSUE TITLE
BitArray.CopyTo(array, index) doesn't respect index - .NET Core 3.0 Preview 8

### ISSUE THREAD

**Issue by danielValdezR** [dotnet/core#3194]
# BitArray CopyTo(Array, Int32) doesn't respect index

When using CopyTo method, the index passed as parameter is not respected and the BitArray is copied at the end of the Array. I found this issue when using a Byte array.

# General

Console Project
.NET Core 3.0 Preview 8
Windows 10 Pro x64

```
byte[] byteArray = new byte[10];
BitArray bitArray = new BitArray(1);
bitArray[0] = true;

bitArray.CopyTo(byteArray, 5);
```

**Expected**: 1 in position 5 of byteArray
**Actual**: 1 at the end of the byteArray

Tested against past versions of .NET Core (.NET Core 2.X) and worked as `expected.```

**Comment by 0xd4d** [comment]
It's probably better to post this bug report to the corefx repo: https://github.com/dotnet/corefx

**Comment by danielValdezR** [comment]
There's an issue already open in dotnet/corefx...
https://github.com/dotnet/corefx/issues/39929
