### ISSUE TITLE
Unable to run published app on rpi4 (assembly not found)

### ISSUE THREAD

**Issue by AxxlForce** [dotnet/core#3196]
I just tried to run our .netcoreapp2.2 on a rpi4 with Raspbian.

I published the app without error via the following command:

`dotnet publish -c release -r linux-arm <<project name>>`

When I try to run it on the rpi I get the following error:

`Error:
  An assembly specified in the application dependencies manifest (ARTEC.AHC.Web.Application.deps.json) was not found:
    package: 'Antlr3.Runtime', version: '3.5.1'
    path: 'lib/netstandard1.1/Antlr3.Runtime.dll'`

However I see that "Antlr3.Runtime.dll" does exist in the "publish" folder

**Comment by scalablecory** [comment]
@livarcocc @nguerrera @krwq

**Comment by nguerrera** [comment]
@AxxlForce Can you supply full set of steps to reproduce the problem? 

> However I see that "Antlr3.Runtime.dll" does exist in the "publish" folder

And just to be sure, you are running the app from the publish folder and not from the parent build folder?

**Comment by AxxlForce** [comment]
ehhhmm... you can close the issue 😅😅 actually I did try that as well but it gave me a different error but that was the "right" error.

Anyhow: running it from the publish folder solves this issue. thanks!
