### ISSUE TITLE
Template "Console Application" could not be created.

### ISSUE THREAD

**Issue by EdwardGithinji** [dotnet/core#3197]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jaguar-515** [comment]
Can you provide us which OS of Windows it is? For example:
Windows 10 1903, Windows 10 1810, etc.

**Comment by leecow** [comment]
Closing due to no feedback from the OP. Please re-open this issue with additional information if you are still having trouble.
