### ISSUE TITLE
Can not create a WPF 3.0 Core Application

### ISSUE THREAD

**Issue by AndreasWaning** [dotnet/core#3198]
Can not Create a WPF core 3.0 application, since I installed the preview 8 version

I get the message, I should check "Use Preview .NET Core SDK" 

But this checkbox is activated !!!!

Is that a bug ?
Thanks Andreas

**Comment by fatihyildizhan** [comment]
I have a similar problem with .NET Core project.

**Comment by darktutu** [comment]
@AndreasWaning  you can try create a wpf project with dotnet command again.

**Comment by AndreasWaning** [comment]
@darktutu  That works. Thank you

**Comment by carlossanlop** [comment]
Closing since this seems to be resolved. Feel free to open a new issue if you keep encountering problems.
