### ISSUE TITLE
Cannot be installed alongside mono

### ISSUE THREAD

**Issue by ZClive** [dotnet/core#32]
The executable `/usr/bin/resgen` tend to be used by both `dotnet` and `mono-devel` package in ubuntu. So it is unable to install `dotnet` if you have `mono` already installed. 

Maybe consider using another name for it, like `dotnet-resgen`, or to utilize the `update-alternative` command in ubuntu to provide different `resgen` as user configured.

**Comment by akoeplinger** [comment]
See https://github.com/dotnet/cli/issues/313

**Comment by zmLGBBM** [comment]
@akoeplinger Great, thanks.

**Comment by Lewiscowles1986** [comment]
please close the issue if it's done
