### ISSUE TITLE
C# Interactive (CSI) in .NET Core

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/core#320]
I'm not sure where to post this.

What about C# Interactive (CSI) on .NET Core? How do I get this to run?

And should it be bundled with .NET Core in the future? I personally believe it is important to enable C# scripting (as well as F# scripting) out-of-box.

**Comment by Petermarcu** [comment]
@kuhlenh

**Comment by kuhlenh** [comment]
@tmat can help you out here!

**Comment by Petermarcu** [comment]
@tmat , is there a good place to have this conversation? It would be good to point this issue there and close it.

**Comment by tmat** [comment]
Files an issue on Roslyn: https://github.com/dotnet/roslyn/issues/17666
