### ISSUE TITLE
The value of the pointer is being changed after an attempt to get the value of the pointer? BUG?

### ISSUE THREAD

**Issue by faruknane** [dotnet/core#3204]
I have a struct where I hide three pointers. I want to use the struct to create a linkedlist. Since list, sortedlist and other classes are not optimized in C# (many gc operations etc, no offense), I have to write it my own to get max speed. I wrote the code. However, I think there is a bug going on with C# and I need an explanation about it. 

Note: I am using .Net Core 3.0 (pre)

My struct is below:

 ```
[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    unsafe struct FastNode
    {
        void* l;
        void* r;
        public void* val;

        public void SetValueFloat(float x)
        {
            val = &x;
        }
        public float GetValueFloat()
        {
            return *((float*)val);
        }
    }
```

The test code:
```
        static unsafe void Main(string[] args)
        {
            FastNode node = new FastNode();
            float x = 10.5f;
            node.SetValueFloat(x); //This sets correctly
            Console.WriteLine(*((float*)node.val)); //this prints correctly
            Console.WriteLine(*((float*)node.val)); //this prints a random value
            Console.WriteLine(*((float*)node.val)); //this prints the same random value above
            return;
        }
```
My question is that "why does the value of a pointer changes when I try to get the value of that pointer?".

**Comment by faruknane** [comment]
I solved the issue by editing code like below:
```
        public void SetValueFloat(ref float x)
        {
            fixed (float* ptr = &x)
                val = ptr;
        }
```

The issue was that I was taking the pointer of a parameter, not the variable itself. Sorry for misunderstood

**Comment by benaadams** [comment]
The pointers don't hold the memory so the data can be moved by the GC but the pointers won't be updated; unless the objects are pinned (like in a `GcHandle.Alloc(array, GCHandleType.Pinned)` array  or everything is entirely in stackspace.

If entirely in stackspace; you should define it as a `ref struct` e.g. `unsafe ref struct FastNode` and the C# compiler will help you ensure it is.

/cc @jkotas

**Comment by faruknane** [comment]
Thank you for your reply 👍 , I solved the issue. Now I'm working on writing Optimized Numerics library. Soon I will publish in my repo.
