### ISSUE TITLE
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown

### ISSUE THREAD

**Issue by alikovvl** [dotnet/core#3206]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
It sounds like the key may not have been installed. Can you please try installing it with the instructions provided on that page?

```
sudo apt-get install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
```

**Comment by scalablecory** [comment]
@alikovvl, has this resolved the issue for you?

**Comment by carlossanlop** [comment]
No response since August. Closing.
