### ISSUE TITLE
No templates matched the input template name: webApp.

### ISSUE THREAD

**Issue by findkashif** [dotnet/core#3207]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

I ran following command
"dotnet new webApp -o CoreApiDockerDemo1 --no-https"
and find this error message
"No templates matched the input template name: webApp."

**Comment by leecow** [comment]
Could you run `dotnet --info` paste the output here so we can see what you have installed?

**Comment by leecow** [comment]
Closing due to issue going stale. Please re-open if you're still having troubles.
