### ISSUE TITLE
Slow Omnisharp Package CDN server

### ISSUE THREAD

**Issue by ansarnisargill** [dotnet/core#3209]
# Updating Omnisharp files taking days
It takes forever for VS Code to update Omnisharp, .net core debugger files which are used by C# extension to provide intellisence, etc. Problem is that I and my team primarily use VS Code for .net core development. When an update for C# extension used to come, It took minutes to download necessary files and get back on running Omni server. But since the last update, It is taking days and days to download even a single package. It took an almost full day to update only Omnisharp package. Now It has been 4 to 5 hours and it is stuck on the next package. My internet connection is as stable and fast as ever. I just want to make sure that it is Ok for now or some CDN related issue for the South Asian region, where I am now. I know I can manually download files and extract them to extension folder but that's a step back from evolution for me. Hope I hear back soon.

![Capture](https://user-images.githubusercontent.com/25664383/63223918-29cd6700-c1d6-11e9-97b5-f57065b27919.PNG)
it is just stuck here for hours, I even Closed and opened VS Code window many times.

**Comment by scalablecory** [comment]
Hi @ansarnisargill, this repo is for .NET Core issues, but this looks like something that OmniSharp needs to look at. Can you please open an issue with them? Thanks. https://github.com/OmniSharp/omnisharp-vscode
