### ISSUE TITLE
ASP.Net Core sample doesnt work

### ISSUE THREAD

**Issue by kumarmohe** [dotnet/core#3210]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

ValuesContoller is not created, instead it creates WeatherForecastController.cs. So "dotnet run" command fails.

Thanks,
Mohan

**Comment by leecow** [comment]
It looks like an update to the sample application was introduced in the 3.0 preview templates. `dotnet run` should still work but you'll need to enter `http://localhost:5000/WeatherForecast` into the browser to see output from the service.

@bradygaster and @rowanmiller to decide on how to update the sample.

**Comment by rowanmiller** [comment]
The tutorial is written for the latest stable release of .NET Core (currently 2.2). We'll upgrade it to 3.0 once we reach stable release of 3.0.

**Comment by kumarmohe** [comment]
> It looks like an update to the sample application was introduced in the 3.0 preview templates. `dotnet run` should still work but you'll need to enter `http://localhost:5000/WeatherForecast` into the browser to see output from the service.
> 
> @bradygaster and @rowanmiller to decide on how to update the sample.

Yeah. Instead of adding a new controller, the old ValuesContoller.cs is good enough.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore.Docs#13947
