### ISSUE TITLE
How did I already mess this up?

### ISSUE THREAD

**Issue by homelessnickle** [dotnet/core#3213]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

i copied and pasted the commands "using Stystem;

namespace myApp
{
           class Program
  {
                      static void Main (string[] args)
                      {
                                Console.WriteLine("Hello World!")
                         }
            }
}"

And I got the response: "cursh cursh cursh dquote>

![Screen Shot 2019-08-19 at 9 55 07 AM](https://user-images.githubusercontent.com/46082326/63275601-70b76d00-c267-11e9-9cfa-4e9442b6a6a4.png)
![Screen Shot 2019-08-19 at 9 55 07 AM](https://user-images.githubusercontent.com/46082326/63275644-83ca3d00-c267-11e9-99d9-c779deca2035.png)

**Comment by bartonjs** [comment]
You seem to have pasted the source code directly into the shell.  The `dotnet new` command that I assume was the last command not copied into the report here should have created a `Program.cs` file in the `myApp` directory which already had the Hello World contents.  You'd need to edit the file with vi/nano/emacs/Xcode/VSCode/VSMac/etc (or just `cat` it to confirm the contents, then proceed in the demo).

The "cursh" seems to be a ZSH "there's an open curly brace" continuation prompt and "dquote" seems to be "there's an terminated quote"... suggesting that the exclamation mark is a ZSH escape character,  But all of that is really "installing .NET Core doesn't make the shell understand C#, you need to edit the C# in source files".
