### ISSUE TITLE
dotnet publish -o does not work as expected

### ISSUE THREAD

**Issue by uffebjorklund** [dotnet/core#3215]
# dotnet publish -o does not work as expected

I just updated a pretty large project to dotnet core 3 (`3.0.100-preview8-013656`). I have not had any issues at all until doing a dotnet publish. We publish to a folder like this.

```
dotnet publish -c Release -r linux-arm -o ../../build/linux-arm  src/MyProject/MyProject.csproj
```

Before the update to dotnet core 3 we always got the result into the expected folder. Now it seems like `-o` is relative from the actual location and not the location of the `.csproj` as in previous versions of dotnet core.

Maybe this is intended? If so, you can close this issue.

OS: MacOS High Sierra

Edit: I should probably have reported this at https://github.com/dotnet/cli/issues :/

**Comment by leecow** [comment]
@uffebjorklund , I'll move this issue over to cli.

**Comment by dasMulli** [comment]
Yes this was a breaking change made for 3.0 since before, `-o ..\foo` not being relative to the command location / current working directory was odd. Applies to some other commands as well.

https://github.com/dotnet/cli/pull/9892

**Comment by uffebjorklund** [comment]
Thanks for explaining! Not really an issue, but I wanted to report it just in case it was not intended.
