### ISSUE TITLE
i cant connect to your servers

### ISSUE THREAD

**Issue by Shazwie** [dotnet/core#3216]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Can you please provide information about your problem?

**Comment by leecow** [comment]
Closing due to lack of feedback from the OP. Please re-open if you're still having troubles and provide details.
