### ISSUE TITLE
Debian Buster cannot install the latest net core?

### ISSUE THREAD

**Issue by shouhujishu** [dotnet/core#3217]
Debian Buster cannot install the latest net core?
Looking for an installation tutorial
Thank you!

**Comment by scalablecory** [comment]
.NET Core 3.0 Preview does support Buster.

.NET Core 2.2 (stable release) does not officially support Buster, but it might be worth trying to see if it "just works".

**Comment by scalablecory** [comment]
Tutorial to configure package manager for Debian 9 is here: https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-2.2.401
Additional installation information, including without a package manager, is available here: https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md

**Comment by glaulher** [comment]
hi, about dotnet core 2.2:

the Ubuntu 19.04 package works perfectly on debian 10, the systems have the same dependencies.

**Comment by glaulher** [comment]
they created the package and named it ubuntu 19.04, version with reduced support, but did not put it for the Debian lts buster ... ubunto 19.04 is pretty much Debian buster in package versions.
