### ISSUE TITLE
.net installation problem

### ISSUE THREAD

**Issue by anupshivram** [dotnet/core#3223]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/core/issues/3221

**Comment by dagood** [comment]
Let us know if the duplicate isn't correct, there isn't enough info in the issue to know for sure.
