### ISSUE TITLE
Unable to install dotnetcore 2.2 Ubuntu 18.04 Hash sum mismatch 

### ISSUE THREAD

**Issue by s177437** [dotnet/core#3226]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.102
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Os output 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

When trying to install dotnetcore I get the following error message. 

Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.74.252.37 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:XXX(removed)
    - SHA256:XXX(removed)
    - SHA1:XXXX(removed) [weak]
    - MD5Sum:XXXXX (removed) [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000

Seems to be others experiencing the same problem. Is the microsoft apt repository not working properly at the moment?

**Comment by Greaky** [comment]
Hello,

Yes, there is currently an issue with their repo : https://github.com/dotnet/core/issues/3225

**Comment by leecow** [comment]
The issue has been resolved and you should be good to go.
