### ISSUE TITLE
Unable to download dotnet cli and sdk-2.2

### ISSUE THREAD

**Issue by gergelyblaha** [dotnet/core#3227]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current#
Operating System: Linux Ubuntu 18.04 - x64

I receive the following error when I try to run apt update:
Error: 13 https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic/main amd64 Packages
File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]

**Comment by Tychus** [comment]
#3221

**Comment by leecow** [comment]
Should be resolved now. Let us know if you're still having trouble.
