### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NoClueHowToDevelopShiit** [dotnet/core#3228]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
We'll need to know what it is that you're having trouble with. Please provide some details and reopen this issue if you're still having trouble.
