### ISSUE TITLE
E: Couldn't find any package by regex 'dotnet-sdk-2.1'

### ISSUE THREAD

**Issue by parth-mansata** [dotnet/core#3229]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.1.300
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
There was an issue with the 18.04 repo until a few minutes ago and I have confirmed the 2.1.300 SDK can be installed successfully. Please give it another try and let us know if there are still troubles.

**Comment by leecow** [comment]
Closing due to issue going stale. Please re-open if you're still having troubles.
