### ISSUE TITLE
AspNetCore.App 2.1 not installing latest patch version

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/core#3236]
I think this might be the same issue as dotnet/source-build#942 but I'm not 100% sure...

I removed the version from package reference as stated in the [ASP.NET Core 2.0 to 2.1 upgrade guide](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.2#update-the-project-file-to-use-21-versions) but when I look in my project -> dependencies -> NuGet I see `Microsoft.AspNetCore.App (2.1.1)` and I have the 2.1.603 SDK installed.  Shouldn't I be seeing `(2.1.10)`?

>Remove the "Version" attribute on the package reference to Microsoft.AspNetCore.App. Projects which use <Project Sdk="Microsoft.NET.Sdk.Web"> do not need to set the version. The version will be implied by the target framework and selected to best match the way ASP.NET Core 2.1 works. (See below for more information.)

## Workaround

Once I added the version number to the package I got the latest version under my project dependencies

`<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.10"/>`

![image](https://user-images.githubusercontent.com/14079228/57626886-d4dddd00-7564-11e9-80a1-ef46c7e64066.png)

## Questions
- The version number shouldn't be specified in the package reference, right?  I'm not supposed to have to do that, right?
- It's supposed to automatically find that SDK version installed on my machine, right?
- Was that the correct workaround?

**Comment by scalablecory** [comment]
> * The version number shouldn't be specified in the package reference, right?  I'm not supposed to have to do that, right?
> * It's supposed to automatically find that SDK version installed on my machine, right?
> * Was that the correct workaround?

You should not need to reference this package directly. The SDK noted in your csproj will bring in the appropriate package reference.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

**Comment by spottedmahn** [comment]
HI @scalablecory - I'm not sure I understand why this was closed 🤔.

>The SDK noted in your csproj will bring in the appropriate package reference.

It's not 😀.

![image](https://user-images.githubusercontent.com/14079228/65902417-628d5e00-e388-11e9-8b04-d161fb2269f4.png)

Should I have a version number my `Project` tag?  Is that what you're saying?

**Comment by spottedmahn** [comment]
Hi @scalablecory - any updates?  Why was this closed?  thanks
