### ISSUE TITLE
[Feature]Bringing FirstChanceException back

### ISSUE THREAD

**Issue by Luo-Liang** [dotnet/core#324]
Hey! I'm wondering if there is any chance to bring FirstChanceException handler, originally in System.AppDomain class back in .net core? We are developers of a monitoring system that needs this information to keep track of exception rate and etc.

We're aware of the System.AppDomain nuget package, but it does not contain FirstChanceException and from reflection it seems that handler is taken away from the binary.

Thanks!

**Comment by Petermarcu** [comment]
I believe this is already added back in .NET Core 1.2. @gkhanna79 can you confirm and close if thats true?

**Comment by gkhanna79** [comment]
Yes, this has been added in 1.2.0 (see https://github.com/dotnet/corefx/commit/5fde04fff39a6325e7ed5594807023f6958766ff#diff-f385e94efa80f66e8f1ee5d41032af30). 

CC @rahku

**Comment by Petermarcu** [comment]
Great @Luo-Liang I'm going to close this but sounds like we're on a good path to having what you need.

**Comment by Luo-Liang** [comment]
Thanks a lot! 👍
