### ISSUE TITLE
Error executing dotnet-ef from command line on .NET Core 3 Preview

### ISSUE THREAD

**Issue by franciscohumarang** [dotnet/core#3240]
I am having this error when i run

`
dotnet-ef dbcontext scaffold "Host=localhost;Database=mydb;Username=myuser;Password=mypassword" Npgsql.EntityFrameworkCore.PostgreSQL -o Updated -t meter_type
`

```
System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.

```

This was  working before on Preview 7.

So basically if I just type dotnet-ef, it will show the error.

**Comment by franciscohumarang** [comment]
I have solved the issue by unistalling dotnet-ef first then installing new dotnet-ef using the latest preview version from nuget:

`dotnet tool install --global dotnet-ef --version 3.0.0-preview8.19405.11`

Closing the issue..

**Comment by xichle** [comment]
I also have solved the issue by unistalling dotnet-ef first then installing new dotnet-ef.

dotnet tool install -g dotnet-ef --version 3.0.0

**Comment by vjdietrich** [comment]
I had 3.1 installed and am getting the same error. I uninstalled and reinstalled 3.1. Didn't help. I uninstalled and reinstalled System.Text.Json. Didn't help. I uninstalled all ef 3.1 packages and reinstalled at 3.0.1. I ran the suggested code dotnet tool install -g dotnet-ef --version 3.0.0 it said it was already installed. I tried it at 3.0.1 and it said it was already installed. I did not have dotnet cli tool utils loaded. I loaded it. I ran dotnet tool install --global dotnet-ef some instruction somewhere. Didn't help. Went back to everything in 3.1. Didn't help. I found in the properties that it was set to output type console. change it to windows application. Didn't help. Changed it back to console and removed the property group that changing it in the first place produced.  Please please please coan someone help me?!  Here is my cs.project file:
 <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseNETCoreGenerator>true</UseNETCoreGenerator>
    <EnvironmentName>Development</EnvironmentName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\TiPro\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Services\" />
    <Folder Include="Models\" />
    <Folder Include="Authentication\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.Cli.Utils" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="4.7.0" />
  </ItemGroup>
</Project>

**Comment by habouva** [comment]
help please i migrate from 2.2 to 3.1 and same problem i have
