### ISSUE TITLE
Text is longer than 43679 and its contents cannot be displayed in DataGridView

### ISSUE THREAD

**Issue by 15092368540** [dotnet/core#3242]
with NET Core 3.0.0-preview8, the point is that can't show, not long enough.
![88759-abug](https://user-images.githubusercontent.com/49462433/63627269-7d5a0d80-c639-11e9-82b6-9997a8c186f0.png)

**Comment by 15092368540** [comment]
Temporarily found a way to fix from developercommunity.visualstudio.com
Codes:
private void DataGridView1_CellFormatting(object sender, DataGridViewCellFormattingEventArgs e)
{
	string str = e.Value.ToString();
	if (str.Length >= 43679)
	{
		e.Value = str.Substring(0, 43679);
		e.FormattingApplied = true;
	}
}

**Comment by 15092368540** [comment]
by Tested, the above method does not achieve the desired purpose when there are two columns or more

**Comment by scalablecory** [comment]
This issue was moved to dotnet/winforms#1995
