### ISSUE TITLE
i am using operating version windows 7.and i am facing problem in .net and messaging is coming like this-'dotnet' is not recognized as an internal or external command error,

### ISSUE THREAD

**Issue by shubham-del** [dotnet/core#3243]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tubs989** [comment]
> If you receive a 'dotnet' is not recognized as an internal or external command error, make sure you opened a new command prompt. If you can't resolve the issue, use the I ran into an issue button to get help fixing the problem.

**Comment by scalablecory** [comment]
Closing stale issue; please feel free to re-open with more information if you haven't resolved things.
