### ISSUE TITLE
Program.cs(10,66): error CS0117: 'DateTime' does not contain a definition for 'now' 

### ISSUE THREAD

**Issue by AIMScto** [dotnet/core#3247]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Followed the tutorial and it seems the example's reference needed to be defined first...but that was not in the tutorial.

Program.cs(10,66): error CS0117: 'DateTime' does not contain a definition for 'now'

**Comment by svick** [comment]
Your error message says `now` (with lowercase `n`), but it has to be `Now` (with uppercase `N`). Capitalization matters in C#.

**Comment by AIMScto** [comment]
Thanks!

**Comment by AIMScto** [comment]
Just starting and I need to get into the rhythm of detail.

**Comment by QueenCitySmitty** [comment]
@AIMScto what IDE are you using to code?  If you're relatively new, I'd use something that has [Intellisense](https://en.wikipedia.org/wiki/Intelligent_code_completion), like [VS Code](https://code.visualstudio.com/).  It'll help with autocorrect, and it'll help you prevent these pesky errors :)

**Comment by AIMScto** [comment]
Thanks @QueenCitySmtty! I am using VS Code. I’ll go with your suggestion.
