### ISSUE TITLE
cant open dotnet script

### ISSUE THREAD

**Issue by amiinegal** [dotnet/core#3253]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Closing due to lack of additional information. Feel free to re-activate the issue with more details if you're still having trouble.
