### ISSUE TITLE
Debugging a .net Core App remote that uses a native dependency throws DLLNotFound

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/core#3255]
I create a WPF .NetCore app wich has a dependency to an native dll (x64). The dll is referenced in the c# project and set to copy always. The WPF app itself is referenced by an app package. This is set as startup project.

Debugging it local will work as expected. Debugging it remote will throw a DllNotFound Exception. However the *missing* dll was copyied to the remote machine.

tool|version
----------|--------------------------
.Net Version |`3.0.100-preview8-013656`|
VS Version | `16.3.0 Preview 2.0`|
Remote Debugger| `16.0.29123.88 build by: D16.2`|
Windows (Guest)| `Windows 10 Pro x64 1903 (Build 18362.295)` 
Windows (Host)| `Windows 10 Enterprise x64 1809 (Build 17763.720)` 

[Sample repo](https://github.com/LokiMidgard/RemoteDependencyProblemTest)

**Comment by LokiMidgard** [comment]
@diverdan92 Yes thats the name.

**Comment by LokiMidgard** [comment]
I think I have a general missunderstanding how Application Packaging works.

I managed to create a apppackage manually and install it on a VM. There I have the same issue.

![grafik](https://user-images.githubusercontent.com/389101/63754510-45f79500-c8b5-11e9-923e-e3039cafbacb.png)

While the DLL is next to the executable, this seems not be the place where the application searches for dll's when it is installed as an app package.

But it seems to find it when debugging locally with Visual studio.

**Comment by LokiMidgard** [comment]
I was able to start the remote debugging using release build.

For some reasons on my test vm it is not able to load the native dll build with debug.

**Comment by LokiMidgard** [comment]
Ok, I was able to fix this. I think the problem was the part "one of its depdendencys". I installed Visual studio on the VM.

Then I had the debug version of the dependencys (I guess)

**Comment by LokiMidgard** [comment]
@diverdan92 I have created an [issue](https://developercommunity.visualstudio.com/content/problem/715070/remote-debugging-native-dlls-in-c-build-with-debug.html).

**Comment by LokiMidgard** [comment]
forgot your question: On the remote machine I lunch Visual Studio 2019 Remote Debugger from start menu.

**Comment by LokiMidgard** [comment]
The dotnet runtime was installed when this exception came.

Actually at first it wasn't but then the program terminated with a pretty descriptive error that said *Install .net core*. And after I did, the described exception occured.

**Comment by LokiMidgard** [comment]
@sbanni I tried this, but I still got an DLLNotFoundException :(

**Comment by sbanni** [comment]
If you look at your appxmanifest.xml you should see this:
`<PackageDependency Name="Microsoft.VCLibs.140.00.Debug.UWPDesktop" MinVersion="14.0.27323.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />`
If you do I would try uninstalling the app on the remote machine to make sure it re-deploys.  Verify/try that and let me know if you still see it, I was seeing the same error locally with your test project and did that step and now it is working for me.

**Comment by LokiMidgard** [comment]
Thank you for your support.

I've updateded the project with the changes and testet it. I reseted the VM but still I got the same error. I updated the changes I made in the Sample Reposetory.
