### ISSUE TITLE
Typo in the release-notes/releases-index.json file

### ISSUE THREAD

**Issue by Vigour-S** [dotnet/core#3258]
Looks like in the [releases-index.json](https://github.com/dotnet/core/commit/5475e24945f7a01d1aaa184ff9e4e634d28c7476?_pjax=%23js-repo-pjax-container#diff-fd7e0ff94e2d15e4755675a517056433R17), for `.Net Core 2.2.6` which should be in the second block in the `releases-index `section, the `latest-release` property should be `2.2.6`. But is is `2.2.401` instead, which is the latest .net sdk version.

This value also doesn't match the `latest-release` value in the corresponding [releases.json](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json) file.
 

We have a .net core tracker tool which will parse the [releases-index.json](https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json) file and download the latest version of .Net core and .Net sdk automatically. This typo caused our .Net core tracker crashed.

Could you pls fix this?

**Comment by tubs989** [comment]
Why would this crash your "tracker"? Looking through the history it appears to jump between the SDK version and the runtime version. Wouldn't it be easier for you to analyse the `latest-release-date` section in the parsed JSON?
