### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kavindumanaramcalcey** [dotnet/core#3261]
When Irun `dotnet new console -o myApp` in Terminal.  it says `Expanding 6%Segmentation fault (core dumped)`

This is in `dotnet --info`

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19
 OS Platform: Linux
 RID:         linuxmint.19-x64

**Comment by kavindumanaramcalcey** [comment]
@scalablecory 
> It looks like you're on a super old version of .NET Core. Can you please retry with .NET Core 2.2 or 3.0?

Hi scalablecory, Actually I want to run my one of an old project.

**Comment by carlossanlop** [comment]
@kavindumanaramcalcey you could port your project to a newer version of .NET Core. Install the new version, then change your project's target .NET to the latest one so you now use that version to compile your project.

**Comment by scalablecory** [comment]
.NET Core 1.0 is no longer supported. Later releases of .NET Core are in most cases backward compatible, so I would try to update your app to 3.0 and see what happens.

Thanks -- please re-open if you're seeing the same segfault on 3.0.
