### ISSUE TITLE
command > dotnet failed

### ISSUE THREAD

**Issue by caosu** [dotnet/core#3264]
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Yeshuaihui** [comment]
It is very likely that this problem is not adding environment variables.

**Comment by Sm0k3scr33n** [comment]
check to make sure both the linux sdk is installed and the runtime pcakages USING SNAP not APT:
`sudo snap install dotnet-sdk --channel=beta --classic`
If that doesnt work try purging then try installing again:

```
sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo snap install dotnet-sdk --channel=beta --classic
```
also you could try an alias
`sudo snap alias dotnet-sdk.dotnet dotnet`

some linux distros need to do a reload 

`dotnet reload`


READ THIS DOCUMENT:
https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview8-download.md

**Comment by leecow** [comment]
Closing due to issue going stale. Please re-open if you're still having troubles.
