### ISSUE TITLE
Unable to start Kestrel - Unable to configure HTTPS endpoint

### ISSUE THREAD

**Issue by kofifus** [dotnet/core#3267]
When starting my deployment server (as a windows service using RunAsCustomService) I get:

> Unable to start Kestrel.
> System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
> To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.

I tried the following:
- used certmgr to remove all localhost certs
- dotnet dev-certs https --clean
- dotnet dev-certs https --trust
- dotnet dev-certs https --check

I get "A valid certificate was found."

Still the error is there and the server service does not start.

Any ideas how to solve this ?

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#13565
