### ISSUE TITLE
Error for add project folder in vs code

### ISSUE THREAD

**Issue by VINITPANDEY** [dotnet/core#3268]
OmniSharp server started with Mono 6.0.0.
    Path: /home/linux/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/OmniSharp.exe
    PID: 5226

System.TypeLoadException: Could not load type of field 'McMaster.Extensions.CommandLineUtils.CommandLineApplication:_validationErrorHandler' (36) due to: Could not load file or assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
  at OmniSharp.Stdio.StdioCommandLineApplication..ctor () [0x00000] in <cb48f4a2918a44a6886865ae1b4b14dc>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_0.<Main>b__0 () [0x00006] in <ef67332970734dbbb15e5d0e9b13d144>:0 
  at OmniSharp.HostHelpers.Start (System.Func`1[TResult] action) [0x0001c] in <150636dc45ea41d3a8efdf330bb7b52f>:0

**Comment by scalablecory** [comment]
It's not clear if this is a .NET, Mono, or Omnisharp issue. Can you reproduce this using just the .NET command line utilities?

**Comment by scalablecory** [comment]
Closing due to lack of response; please feel free to re-open if you're still having this issue and can provide more details.

**Comment by Shorotshishir** [comment]
Hello, I am facing the same problem for `DOTNET Core 3.1` in `Linux Mint 19.3` with __VSCode__.
```raw
OmniSharp server started with Mono 6.4.0.
    Path: /home/siratim/.vscode/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/OmniSharp.exe
    PID: 5483

System.TypeLoadException: Could not load type of field 'McMaster.Extensions.CommandLineUtils.CommandLineApplication:_validationErrorHandler' (36) due to: Could not load file or assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
  at OmniSharp.Stdio.StdioCommandLineApplication..ctor () [0x00000] in <27dcabbd1f5d4edeaffe820a1236c676>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_0.<Main>b__0 () [0x00006] in <2d02054c9f224f8aa95299738e820ffb>:0 
  at OmniSharp.HostHelpers.Start (System.Func`1[TResult] action) [0x0001c] in <1ed0cdfb5a5d42889b4f5df087ff7bd6>:0 
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
I was following the instruction given in the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804#troubleshoot-the-package-manager)

I tried with older `C#` extension from `VS Code` but had no luck. `dotnet 3.1` is installed as you can see here from the `dotnet --info`
``` raw
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.3
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]
```
Any idea how to resolve the issue !
