### ISSUE TITLE
Potential bug: Setting ASPNETCORE_ENVIRONMENT from the command line does not seem to work

### ISSUE THREAD

**Issue by opensrcken** [dotnet/core#327]
Representative of the script I'm using when I encounter said bug.

```
SET ASPNETCORE_ENVIRONMENT=Test
dotnet ef database update
```

`env.EnvironmentName` does not not seem to be aware of `ASPNETCORE_ENVIRONMENT` when running the second command. Instead, it is always set to `Development`.

**Comment by Petermarcu** [comment]
@Eilon , Whats the best place to track this?

**Comment by Eilon** [comment]
This issue was moved to aspnet/EntityFramework#7353

**Comment by Eilon** [comment]
Moved to the EF repo to start the investigation there. Thanks!
