### ISSUE TITLE
.Net SDK Issue

### ISSUE THREAD

**Issue by kumarmohe** [dotnet/core#3270]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

I get the below error while executing "docker build -t mymicroservice ." command.

Sending build context to Docker daemon  15.36kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
2.2: Pulling from dotnet/core/sdk
9cc2ad81d40d: Pull complete                                                                                                                                                                                        e6cb98e32a52: Pull complete                                                                                                                                                                                        ae1b8d879bad: Pull complete                                                                                                                                                                                        42cfa3699b05: Pull complete                                                                                                                                                                                        dcc190332ff6: Pull complete                                                                                                                                                                                        b49aea48d777: Pull complete                                                                                                                                                                                        67e832fd5d6a: Pull complete                                                                                                                                                                                        Digest: sha256:e1b19d391986f21b177c1ba47f8a8519bf5cff66a9459d04f3aea23e1a7ec30f
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:2.2
 ---> 08657316a4cd
Step 2/10 : WORKDIR /src
 ---> Running in 391b9432ad05
Removing intermediate container 391b9432ad05
 ---> 405695b0d74d
Step 3/10 : COPY myMicroservice.csproj .
 ---> 7e23f48a0171
Step 4/10 : RUN dotnet restore
 ---> Running in 78635ca8628f
/usr/share/dotnet/sdk/2.2.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/src/myMicroservice.csproj]
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

my .csproj file contains.

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
</Project>

**Comment by svick** [comment]
If you want to build a .Net Core 3.0 project, you need to use the .Net Core SDK 3.0. That means you need to change your `FROM` to use version 3.0. I.e.:

```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
```

Since it looks like you're using a two-stage Dockerfile, you'll also have to change the version to 3.0 in the second `FROM`.

**Comment by svick** [comment]
I think the problem is that you have .Net Core SDK 3.0 preview installed on your machine. Because of that, when you ran `dotnet new`, it created a .Net Core 3.0 project. But the tutorial links you to an installation of .Net Core SDK 2.2. Do you happen to know why you have .Net Core SDK 3.0 preview installed?

If this is a common problem, maybe it would make sense to update the `dotnet new` command to force using .Net Core 2.2:

```
dotnet new webapi -o myMicroservice --no-https -f netcoreapp2.2
```
