### ISSUE TITLE
[Blazor p8] OnInitializedAsync is executed for twice on pre-render

### ISSUE THREAD

**Issue by ctrl-alt-d** [dotnet/core#3273]
# Issue

OnInitializedAsync is executed for twice on pre-render

# General

```
[dani@localhost tw]$ dotnet --version
3.0.100-preview8-013656
```

I wrote this code:

```
@page "/"
@inject IUriHelper UriHelper

<h1>Hello, world!</h1>

Welcome to your new app.

@code{

    protected async override Task OnInitializedAsync()
    {
        System.Console.WriteLine("_*   ");
        System.Console.WriteLine("_**************************");
        System.Console.WriteLine("_***** Pre render ******");
        System.Console.WriteLine("_**************************");
        System.Console.WriteLine("_   ");
        return;
    }
}
```

And I see is executed for twice only on pre-render:

![prerender2](https://user-images.githubusercontent.com/3105983/63875371-9fe68080-c9c3-11e9-9537-41924ef83401.gif)

Has it some explanation?

The question on stackoverfow: [Blazor UriHelper.NavigateTo is calling the page twice](https://stackoverflow.com/questions/57680784/blazor-urihelper-navigateto-is-calling-the-page-twice/57696602)

**Comment by hez2010** [comment]
I think blazor related issues should be posted in AspNetCore repo:
https://github.com/aspnet/AspNetCore

**Comment by ctrl-alt-d** [comment]
Of course @hez2010 , thanks: https://github.com/aspnet/AspNetCore/issues/13607
