### ISSUE TITLE
Publish ReadyToRun framework-dependent apps

### ISSUE THREAD

**Issue by tmds** [dotnet/core#3278]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/ introduces ReadyToRun for self-contained apps. The blog post includes a note:

> Note: ReadyToRun is currently only supported for self-contained apps. It will be enabled for framework-dependent apps in a later preview.

Is this still planned for 3.0?

CC @leecow @richlander

**Comment by leecow** [comment]
@jeffschwMSFT - Do you know the status?

**Comment by fadimounir** [comment]
Yes, still planned for 3.0, and it should actually work right now with the current latest preview (Preview 9).

**Comment by tmds** [comment]
Thanks, I'll check that out!
