### ISSUE TITLE
.NET Core 3.0 Visual Studio 2019 SDK x64 Installer not starting

### ISSUE THREAD

**Issue by Sybren-** [dotnet/core#3279]
NET Core 3.0 Visual Studio 2019 SDK x64 Installer not starting

I'm trying to download the NET Core 3.0 Visual Studio 2019 SDK x64 Installer > https://dotnet.microsoft.com/download/visual-studio-sdks?utm_source=getdotnetsdk&utm_medium=referral

But after a while the following error appears, the installer won't start.

https://download.visualstudio.microsoft.com/download/pr/a46fa009-033b-430d-89a8-c9a107f73d87/d25f962e8212aafb3b0c426eb8cb4dc6/dotnet-sdk-3.0.100-preview8-013656-win-x64.exe werkt even niet, of de pagina kan verhuisd zijn naar een nieuw webadres.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by leecow** [comment]
Confirmed this is downloading fine. Please re-activate the issue if you're still having trouble.
