### ISSUE TITLE
VS2019 not showing core 3

### ISSUE THREAD

**Issue by dpro86** [dotnet/core#3282]
# Issue Title

VS2019 not showing core 3 (16.2.3)

# General
i've enabled the previews to show under Tools--> Options--> Enviornment -->  Preview Features --> Use the previews...

still not showing please help

![image](https://user-images.githubusercontent.com/4821346/63968803-5181c200-ca55-11e9-8f73-61979ceacfa6.png)

![image](https://user-images.githubusercontent.com/4821346/63968891-7d9d4300-ca55-11e9-940a-921010260da7.png)

![image](https://user-images.githubusercontent.com/4821346/63968955-a6bdd380-ca55-11e9-9b37-a5c4073fd079.png)

**Comment by alefranz** [comment]
Hi,
to use .NET Core 3.0 Preview 8 you need to use the preview channel of Visual Studio 2019 currently, as stated on the download page in the first column of the table.
https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by nguyenquyhy** [comment]
This is confusing. The announcement blog post encourages using preview 8 for production, but there is no preview 8 support for production version of Visual Studio...

**Comment by ddgweb** [comment]
> Hi,
> to use .NET Core 3.0 Preview 8 you need to use at least version 16.3 of Visual Studio 2019, as stated on the download page in the first column of the table, which is currently only on the preview channel.
> https://dotnet.microsoft.com/download/dotnet-core/3.0

I have the same question , and my vs 2019 is version 16.3.

**Comment by leecow** [comment]
16.3 Preview 3 released today and is the first version to include .NET Core 3.0 'in-box'.
