### ISSUE TITLE
not a debian package

### ISSUE THREAD

**Issue by n319** [dotnet/core#3289]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.107
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
The instructions on that page work fine for me currently. Can you paste the commands you're running and the errors you're hitting, and anything else that you think will be useful like what Linux distro you're running?

Maybe the `wget` command failed in some way, causing you to end up with a partially-downloaded file that isn't a valid Debian package?

**Comment by Sm0k3scr33n** [comment]
check to make sure both the linux sdk is installed and the runtime pcakages **USING SNAP not APT:**
`sudo snap install dotnet-sdk --channel=beta --classic
`
If that doesnt work try purging then try installing again:

```
sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo snap install dotnet-sdk --channel=beta --classic
```

READ THIS DOCUMENT:
https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview8-download.md

**Comment by leecow** [comment]
Closing due to issue going stale. Please re-open if you're still having troubles.
