### ISSUE TITLE
Removing a reference/dependency not working as expected

### ISSUE THREAD

**Issue by Kizmar** [dotnet/core#329]
_Using Visual Studio 2015 v14 Update 3 with .Net Core 1.0.0_

Regarding the removal of a project dependency from another project in a solution:

Doing so **should** break any usage of that assembly/namespace in the project, yet in some cases no errors are raised on rebuild. When this happens, we don't know there are build errors until we push a commit and our CI environment tries to build and deploy (at that point it blows up).

I've tried the following with no success:
- Removing the reference both manually in project.json, and using the VS right-click context
- A Clean and Rebuild after removing
- Building on a different configuration after removing
- Manually deleting the "bin" and "obj" folders under said project after removing
- Running "dotnet restore" and "dotnet build" from CMD after removing

Anyone else run into this?

**Comment by richlander** [comment]
Please re-activate if this is still the case.

/cc @blackdwarf
