### ISSUE TITLE
Fedora install docs one line wrong

### ISSUE THREAD

**Issue by 2E0PGS** [dotnet/core#3291]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-current
Operating System: Linux Fedora 28 - x64. 

Same for Fedora 27 instructions.

Should be `dnf check-update` not `dnf update`.

**Comment by dagood** [comment]
Is it useful to have a `dnf update`/`dnf check-update` line at all? When I run through the Fedora install steps, I skip this command entirely and it has worked fine for me. My usage of Fedora is very narrow, however, maybe there's some common configuration that makes it necessary.

I suspect the `dnf update` line is there because it seems analogous to the `apt-get update` step from Ubuntu (but it isn't).

/cc @leecow

**Comment by leecow** [comment]
`check-update` can be run without `sudo` and only refreshes the local package db. `update` requires `sudo` and will install all discovered updates. For the use case we are covering here, I think `check-update` is the better choice.

**Comment by dagood** [comment]
Why is it useful to run `dnf check-update` in this scenario?

**Comment by leecow** [comment]
This could be a faulty assumption on my part. I know apt searches the local package db to determine if something is available and if it's not found, simply says so. apt-get update refreshes the local db and then updates can be found.

**Comment by dagood** [comment]
Yeah, `dnf install` has no qualms about fetching info from remote repositories to find what things are available where. This works fine:

```
docker run -it --rm fedora:28 bash -c '
  dnf install -y wget
  rpm --import https://packages.microsoft.com/keys/microsoft.asc
  wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/27/prod.repo
  dnf install -y dotnet-sdk-2.2
  dotnet --info'
```

**Comment by scalablecory** [comment]
@dagood @leecow it looks like this is still the instruction given today; does a change need to be made here or can we close the issue?

**Comment by 2E0PGS** [comment]
I would suggest it needs to change otherwise it's instructing people to update their entire system. 

⁣-- 
Peter Stevenson (2E0PGS)
http://www.m3pgs.co.uk​

**Comment by dagood** [comment]
Agreed. Filed an internal issue to maybe get more visibility on removing the `dnf update`, `yum update`, and `zypper update` steps, which are along the same lines.

**Comment by leecow** [comment]
Merged the change to remove `update` from the rpm-based instructions. Should be live in about 20 minutes.
