### ISSUE TITLE
Can't reach http://localhost:5000/.

### ISSUE THREAD

**Issue by vincegu** [dotnet/core#3293]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

I'm new to ASP.NET. I used "> dotnet new webApp -o myWebApp --no-https" to create my first web app. But I can't browse to http://localhost:5000. It shows "Hmmm...can't reach this page". 

What did I miss?

**Comment by scalablecory** [comment]
You should see a line in the console like "Now listening on: http://localhost:5000" -- are you getting that?

**Comment by vincegu** [comment]
No. I ran "dotnet new webApp -o myWebApp --no-https" in command line again, all I got is a whole bunch of overwrites in red (e.g. "Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.min.js.map", etc.). The last line is "Rerun the command and pass --force to accept and create.".

**Comment by scalablecory** [comment]
"dotnet new" only creates a project. It sounds like you're missing the next step -- "dotnet run".

**Comment by vincegu** [comment]
You're right! I missed "dotnet run". I even missed "cd myWebApp". :-(
Thanks a lot! @scalablecory
