### ISSUE TITLE
"dotnet" command issue

### ISSUE THREAD

**Issue by blickyx** [dotnet/core#3297]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When trying to run "dotnet" in command prompt I am getting this error "dotnet is not recognized as an internal or external command "

tried a couple of times to make sure it was a fresh command prompt

Windows 10 1903

**Comment by blickyx** [comment]
nvm fixed it

**Comment by scalablecory** [comment]
right on :)
