### ISSUE TITLE
E: Version '2.2.106' for 'dotnet-sdk-2.2' was not found

### ISSUE THREAD

**Issue by monica-vrancean** [dotnet/core#3298]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Operating System: Linux Ubuntu 16.04 - x64

when trying to upgrade on ubuntu 16.04 from dotnet 2.1.202 to 2.2.106 using the command: 
 sudo apt-get install dotnet-sdk-2.2=2.2.106
I get the following error:
 E: Version '2.2.106' for 'dotnet-sdk-2.2' was not found

tried also with '2.2.106-1'

**Comment by leecow** [comment]
We did not publish 2.2.106 for Linux, 2.2.203 is the toolset for that month. 2.2.108 is the latest release in that version line and is available. This primary difference between the 2.2.1xx and 2.2.2xx toolsets is MSBuild 15 versus MSBuild 16. If you don't have a particular requirement, moving to the latest toolset is recommended.

**Comment by monica-vrancean** [comment]
I finally used version 2.2.401 cause this was the only one that I found published(apt-cache search dotnet-sdk-2.2). But I would recommend updating documentation where it describes the steps to use 2.2.106 as a published version: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-2.2.106.
Thank you.
