### ISSUE TITLE
Could not install .NET Core SDK on Ubuntu 18.04 (x64)

### ISSUE THREAD

**Issue by w4ssimh** [dotnet/core#3299]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Hi,
I'm using a Ubuntu 18.04 (x64) on a virtual machine (VM VirtualBox), connected to internet of the company I work for.
I fellow the instructions here:
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
But I still cannot install NET Core SDK
After running the last command : sudo apt-get install dotnet-sdk-2.2
Here is the message printed on the console:
**Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.6) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.6) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.**

**Comment by leecow** [comment]
This is usually caused by a missing system dependency. Running `apt-get install dotnet-runtime-deps-2.2` will tell you what the problem is. Install whatever that is, then you should be good to install the SDK.

**Comment by leecow** [comment]
Closing due to issue going stale. Please re-open if you're still having troubles.
