### ISSUE TITLE
Is it possible to get native compilation of FSharp ConsoleApp?

### ISSUE THREAD

**Issue by jakubsuchybio** [dotnet/core#33]
So I successfully native compiled some C# code on ubuntu. And I am wondering.. Is it possible for FSharp?
First I got some code from VS2015 on my Win10 for default ConsoleApp in F#. Removed all unnecessary dependencies. It needed only FSharp.Core, so i found its version on nuget.org and then
I tried this code:
Program.fs:
```
[<EntryPoint>]
let main argv =
    printfn "HelloWorld2"
    0
```
with
project.json
```
{
    "version": "1.0.0-*",
    "frameworks": {
        "dnxcore50": {
            "dependencies": {
                "FSharp.Core": "4.0.0.1"
            }
        }
    }
}
```
But when trying 'dotnet compile --native' I get:
```
root@ubuntu:/opt/dotnet/core/samples/fsharp# dotnet compile --native
Compiling fsharp for DNXCore,Version=v5.0
/opt/dotnet/core/samples/fsharp/warning CS2008: No source files specified.
/opt/dotnet/core/samples/fsharp/warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.

Compilation succeeded.
    2 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.9048438

Input Assembly: /opt/dotnet/core/samples/fsharp/bin/Debug/dnxcore50/fsharp.dll
/usr/share/dotnet/bin/libbootstrapper.a(main.cpp.o): In function `main':
(.text+0xb3b): undefined reference to `__managed__Main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Compilation of intermediate files failed.
```
Which compiles it into fsharp.dll in /bin/Debug, but no native code is available from this.
So I tried to add these lines into project.json:
```
"compilationOptions": {
        "emitEntryPoint": true
    },
```
But then I get error:
```
root@ubuntu:/opt/dotnet/core/samples/fsharp# dotnet compile --native
Compiling fsharp for DNXCore,Version=v5.0
/opt/dotnet/core/samples/fsharp/warning CS2008: No source files specified.
/opt/dotnet/core/samples/fsharp/warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
/opt/dotnet/core/samples/fsharp/error CS5001: Program does not contain a static 'Main' method suitable for an entry point

Compilation failed.
    2 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.7057666
```
So. How do I tell compiler to find source at Program.fs and to compile it into binary with entrypoint at main function? Is it possible?
Thanks

**Comment by jkotas** [comment]
cc @piotrpMSFT

FSharp is not supported by `dotnet` yet, but it is in the [roadmap](https://github.com/dotnet/cli/issues/45)

**Comment by blackdwarf** [comment]
@jakubsuchybio F# is now available to be installed as a per-project extension using the .NET Core command line tools. You use the `dotnet new -l fsharp` to get a simple F# console application with the Preview 2 of the tools. With this, I will close this issue. 

If you have more questions and/or comments, please file issues on dotnet/cli repo.

**Comment by samuela** [comment]
What's the current status of this? It looks like the `dotnet compile` command has been removed and I don't see a `--native` flag for `dotnet publish`...

**Comment by karelz** [comment]
@cartermp can you comment please?

**Comment by cartermp** [comment]
There is no supported native compile for .NET Core applications that is shipped in .NET Core today. F# support is predicated on native compile being a valid scenario.

However, you can use publish to produce a standalone folder that can contain your F# `.dll` and all its dependencies so that it's xcopy-deployable.

**Comment by samuela** [comment]
@cartermp Ah, that's unfortunate. Is this on the roadmap for .NET Core at all?
