### ISSUE TITLE
In linux Centos7, use .net core2.2 Post request error

### ISSUE THREAD

**Issue by ddgweb** [dotnet/core#3300]
httpclient or httpwebrequest
The same code ,for windows +ngix no error , everythiny is ok , bu in linux centos, error tips:
The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

 I already set "http.RemoteCertificateValidationCallback += (sender, certificate, chain, errors) => true;" but it's don't work

**Comment by leecow** [comment]
Could you post a minimal code sample showing the error?

**Comment by leecow** [comment]
Closing due to issue going stale. Please re-open if you're still having troubles.

**Comment by lostmagicK** [comment]
> Closing due to issue going stale. Please re-open if you're still having troubles.

I have same issue.. Is there any workaround?
