### ISSUE TITLE
.netcore 3.0 single publish temp folder location

### ISSUE THREAD

**Issue by lastlink** [dotnet/core#3303]
# Single publish temp folder location

When doing a single publish a [temp](https://dotnetcoretutorials.com/2019/06/20/publishing-a-single-exe-file-in-net-core-3-0/) folder is supposedly used. This is probably similar to [warp](https://github.com/dgiagio/warp). I'd like to know where the temp folder is on the different os's.

**Comment by Sm0k3scr33n** [comment]
published applications are generally located in the project folder under: 

 ~\<project>\bin\Release\netcoreapp*.*\publish\ 

I always just delete the contents of the publish folder before publishing again...

**Comment by lastlink** [comment]
This is already super clear, but when you do a `dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true` all the dlls are bundled together into a single exe and when run they are unzipped or unbundled into a temp folder as said in https://dotnetcoretutorials.com/2019/06/20/publishing-a-single-exe-file-in-net-core-3-0/

> When this is executed, the dependencies are extracted to a temporary directory and then everything is ran from there.

**Comment by dagood** [comment]
It looks like this is described in the design over here: https://github.com/dotnet/designs/blob/master/accepted/single-file/extract.md#extraction-location

The code lives here: https://github.com/dotnet/core-setup/blob/aae3e31d0011b09c8277d2f06f00b07e1fba8cb5/src/corehost/cli/apphost/bundle/bundle_runner.cpp#L169-L193

I've heard this called "single-file publish", not just "single publish", which may have caused some confusion. (Pretty clear from the link though!)

**Comment by replaysMike** [comment]
design files are 404 links :(

**Comment by omajid** [comment]
The moved the files around in that repo. Is https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/extract.md what you are looking for?

**Comment by dagood** [comment]
Updated my link and pinned it for the future. Thanks, surprised that rearrangement happened without placeholders given how many links you'd expect to that repo (where pinning makes it harder to later revise the docs, so I haven't always done it)....
