### ISSUE TITLE
.NET Core SDK 2.2 on Linux Debian 9

### ISSUE THREAD

**Issue by legrandos** [dotnet/core#3308]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

When I run the last command to install .NET Core SDK 2.2 on Linux Debian 9 which is:

sudo apt-get install dotnet-sdk-2.2

I see the following messages in the terminal:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

**Comment by scalablecory** [comment]
Have you added the Microsoft repository?

```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/debian/9/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
```

**Comment by legrandos** [comment]
Thanks for your reply scalablecory. It was a mistake on my part because I was trying to following the steps on a Raspberry Pi Model B+ which has a 32 bit processor as I later found out. Once I downloaded the 32 bit binaries it worked like a charm! Thank you.
