### ISSUE TITLE
No overload for method 'RenderComponentAsync' takes 0 arguments

### ISSUE THREAD

**Issue by Scobiform** [dotnet/core#3310]
With the Update to Preview 9...

> No overload for method 'RenderComponentAsync' takes 0 arguments

in _Host.cshtml - how should I use it now? What changed?

**Comment by igoventura** [comment]
Can you send a copy of your _Host.cshml or push a sample project with this issue? Or you can provide more details about it?

**Comment by Scobiform** [comment]
its is explained here =>
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/#multiple-components-in-views-or-pages

just give it the rendermode like:

` <app>@(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))</App>`
