### ISSUE TITLE
I cannot find Pages/Index.cshtml

### ISSUE THREAD

**Issue by ritika031** [dotnet/core#3311]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Please, provide more details about the issue.

**Comment by leecow** [comment]
Closing due to the issue going stale. Please reopen with specific information if you're still having troubles.
