### ISSUE TITLE
Does the .Net pkg run on MacOS?

### ISSUE THREAD

**Issue by IanKHall** [dotnet/core#3316]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Can you provide more details about this issue?

**Comment by scalablecory** [comment]
It does. Do you have a specific issue getting it to run?

**Comment by IanKHall** [comment]
I got it working , thanks.
Ian Hall
