### ISSUE TITLE
netcore3 preview9 doesn't publish in main wwwroot the files from wwwroot of sub-project

### ISSUE THREAD

**Issue by niconico49** [dotnet/core#3318]
# Issue Title
netcore3 preview9 doesn't publish the file inside the wwwroot of sub-project

# General
if you have two projects:
1: main web project with default wwwroot
2: library project with .cs classes and additional resources as .css, .js, .ts, img etc. inside
directory called wwwroot: see https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

The strange behaviour happens when Publish the project because if you try to see the wwwroot inside the folder Generated/Published, you will discover that all files are not there.

By some trial / error I discovered this for local / development environment and remote / production environment

1) Local: if EVERY file inside sub-project wwwroot directory has in the property
Build: None ==> the app doesn't find any file during web execution
2) Local: if at least ONE file inside sub-project wwwroot directory has in the property
Build: Content ==> the app find every file during web execution
3) Publish for Production ==> if EVERY file inside sub-project wwwroot directory has in the property
Build: None ==> the publish doesn't copy any file inside wwwroot during publish
2) Publish for Production: if at least ONE file inside sub-project wwwroot directory has in the property
Build: Content ==> the publish copy ONLY that files inside wwwroot during publish

After that my workaround was to change the property
Build: Content for every file inside every wwwroot directory inside every sub-project because if at least one is sufficient for the local development environment. the same is not true for the publish and consequentely for the Remote production environment

the question is: is normal? is a bug? and WHY this setting property is not specified in the documentation https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/ ???????

**Comment by scalablecory** [comment]
CC @Pilchie @livarcocc @nguerrera

**Comment by nguerrera** [comment]
What property are you referring to?

**Comment by scalablecory** [comment]
@nguerrera I think they're setting "Build: Content" in VS for each file that needs publishing

**Comment by leecow** [comment]
Closing due to the issue going stale. Please re-open if you're still having trouble.

**Comment by Cloudmersive** [comment]
Why is an issue that isn't fixed closed?
