### ISSUE TITLE
Nuget package with win-x64 runtime used in .NET Core 3.0 Preview 9 app cannot find delay-loaded DLLs

### ISSUE THREAD

**Issue by bxthomas** [dotnet/core#3323]
If a nuget package that when referenced in a .NET Core 3.0 Preview 9 application creates the following directory with native DLLs in it,

.\bin\Debug\netcoreapp3.0\runtimes\win-x64\native

and the main dll (main.dll) delay loads a dll (e.g. delayload.dll), then the main.dll is successfully loaded as a module in the process but the delay loading call to LoadLibraryEx fails with "module not found".

This situation can be worked around with the following C# code

```c#
        const uint LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x00001000;

        [DllImport("kernel32", CharSet = CharSet.Auto, SetLastError = true)]
        static extern bool SetDefaultDllDirectories(uint directoryFlags);

        [DllImport("kernel32", CharSet = CharSet.Unicode, SetLastError = true)]
        static extern IntPtr AddDllDirectory(string lpPathName);

        static void Main(string[] args)
        {
            // ensure main.dll is loaded here but delayload.dll has not yet been required

            ProcessModuleCollection modules = Process.GetCurrentProcess().Modules;

            ProcessModule dibModule = modules.OfType<ProcessModule>().FirstOrDefault(m => m.ModuleName == "main.dll");

            if (dibModule != null)
            {
                SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);

                AddDllDirectory(System.IO.Path.GetDirectoryName(dibModule.FileName));
            }

        }
```

**Comment by scalablecory** [comment]
Did this work on .NET Core 2.2 or .NET Core 3.0 Preview 8? If so, which Nuget package is failing? CC @jeffschwMSFT @jkotas 

To recap the issue, you have a directory structure like this:

```
..\native\main.dll
..\native\delayload.dll
```

You are P/Invoking into main.dll, which needs to load delayload.dll via `LoadLibraryEx`, but the default DLL search path does not include the "native" directory so it's not finding it. Is my understanding correct?

**Comment by jeffschwMSFT** [comment]
The way this typically works is that the native asset is part of the deps.json and the locations that contain native code are reported to the runtime.  Then during p/invoke module resolution we probe various places, including these paths.

You may want to consider trying is https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.0 which is new to .NET Core 3 and is intended to help with this situation.  Instead of calling AddDllDirectory, you can subscribe to the callback and resolve the native module at load time.

**Comment by bxthomas** [comment]
Thanks for the comments, I was able to narrow this down to a minimal set of projects to reproduce the problem.

**C++ DLL Project 1 => main.dll**, must go into linker settings and set /DELAYLOAD:"delayload.dll"
{code}
#include "stdafx.h"
#include <stdio.h>

extern "C" void TestMethod3();

#pragma comment(lib, "..\\delayload\\x64\\Debug\\delayload.lib")

extern "C" void _declspec(dllexport) TestMethod1()
{
	printf("TestMethod1");
}

extern "C" void _declspec(dllexport)TestMethod2()
{
	printf("TestMethod2");
	TestMethod3();
}
{code}

**C++ DLL Project 2=> delayload.dll**
{code}
#include "stdafx.h"

#include <stdio.h>

extern "C" void _declspec(dllexport)TestMethod3()
{
	printf("TestMethod3");
}
{code}

C# net core console app
{code}
using System.Reflection;
using System.Runtime.InteropServices;

namespace ConsoleApp6
{
    class Program
    {
        [DllImport("Main")]
        static extern void TestMethod1();

        [DllImport("Main")]
        static extern void TestMethod2();

        static void Main(string[] args)
        {
            TestMethod1();
            TestMethod2();
            System.Console.ReadKey();
        }

    }
}
{code}

Copy main.dll and delay.dll to some random directory.  Update "targets" section of Console6.deps.json to point to the dlls.

{code}
"targets": {
    ".NETCoreApp,Version=v2.1": {
      "ConsoleApp6/1.0.0": {
        "runtime": {
          "ConsoleApp6.dll": {}
        },
		"runtimeTargets": {
          "runtimes/win-x64/native/out/win/lib/main.dll": {
            "rid": "win-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
		  "runtimes/win-x64/native/out/win/lib/delayload.dll": {
            "rid": "win-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          }
		}
      }
    }
  },
{code}

Note that the native library DLL resolver is able to resolve the main.dll correctly, but when the main.dll tries to load the delayload.dll using LoadLibrary, it fails.  Adding a custom DLL resolver using NativeLibrary does not help.

**Comment by bxthomas** [comment]
The problem also seems to exist in .NET Core 2

**Comment by jeffschwMSFT** [comment]
@bxthomas that is correct, the OS must be able to find all the dependent loads (eg. delay loads).  The runtime is not involved in ensuring that all components have their dependencies.  AddDllDirectory or expanding the path (eg. part of LoadLibrary's search path) is the only solution for that problem.

**Comment by bxthomas** [comment]
OK, I will use a workaround then.   It may be worth a note somewhere that if you create nuget packages with native dependencies that they will not work if those native dependencies rely on any delay loaded DLLs (which I imagine is reasonably common).

**Comment by maxgolov** [comment]
Just want to mention that the `SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS)` [turns off the search in the standard search path](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa). So any mixed managed-native assemblies that load native libraries would not work with other framework libraries that require the PATH-based lookup, e.g. https://github.com/microsoft/service-fabric-issues/issues/539#issuecomment-338792544 ... The workaround for that is to explicitly add all native libraries via `AddDllDirectory` . This means that the workaround suggested in this thread may inadvertently affect the host process DLL loading policy by restricting the PATH-based lookup.
