### ISSUE TITLE
Create WSDL client dynamic, at runtime

### ISSUE THREAD

**Issue by joaomello** [dotnet/core#333]
Hi!
Today with Roslyn cross-plataform, is possible to do this: https://social.msdn.microsoft.com/Forums/vstudio/en-US/39138d08-aa08-4c0c-9a58-0eb81a672f54/adding-a-web-reference-dynamically-at-runtime?forum=csharpgeneral?

**Comment by richlander** [comment]
Are you asking for a Roslyn-based WSDL generator?

/cc @danroth27

**Comment by joaomello** [comment]
Yes, because with the code from post a can read WSDL, create my client and use dynamic. But not with .net core.

**Comment by danroth27** [comment]
@terrajobst @zhenlan Is the issue here that the solution folks are currently using requires CodeDOM support, which doesn't exist in .NET Core? Is this perhaps something that gets addressed with all the APIs we are adding back?

**Comment by terrajobst** [comment]
We do have [CodeDOM support now](https://github.com/dotnet/corefx/tree/master/src/System.CodeDom/src/System/CodeDom). What we don't have is the ability to compile the resulting assembly. We figured that the bulk of the code is generating the sources. It should be trivial to update whatever component relies on CodeDOM to compile the result using Roslyn.

**Comment by joaomello** [comment]
I don't know if I'm doing in _the best way_ this. I downloaded all wsdl from server and compile the client at runtime. Because Url can change (about 32 times) for same service/method, and I don't want to compile or add reference for each one, it's one of reasons.

For example my code:
```C#
private void Teste()
{
    var ass = CriarAssemblie(wsdl);
    dynamic service = Activator.CreateInstance(ass.GetType("Type1"));
}

private Assembly CreateAssembly(Stream wsdlFile)
{
    var serviceDescription = ServiceDescription.Read(wsdlFile);
    StringWriter strWriter = new StringWriter(CultureInfo.CurrentCulture);
    CSharpCodeProvider cProvider = new CSharpCodeProvider();
    cProvider.GenerateCodeFromNamespace(GerarNameSpace(serviceDescription), strWriter, null);

    string codigoClasse = strWriter.ToString();

    CompilerParameters parameters = new CompilerParameters(new string[] { "System.dll", "System.Xml.dll", "System.Web.Services.dll", "System.Data.dll" });
    parameters.GenerateExecutable = false;
    parameters.GenerateInMemory = true;
    parameters.TreatWarningsAsErrors = false;
    parameters.WarningLevel = 4;

    CompilerResults results = cProvider.CompileAssemblyFromSource(parameters, codigoClasse);
    return results.CompiledAssembly;
}

private CodeNamespace GerarNameSpace(ServiceDescription serviceDescription)
{
    var importer = new ServiceDescriptionImporter();
    importer.AddServiceDescription(serviceDescription, string.Empty, string.Empty);
    importer.CodeGenerationOptions = CodeGenerationOptions.GenerateProperties;

    var @namespace = new CodeNamespace();
    var unit = new CodeCompileUnit();
    unit.Namespaces.Add(@namespace);
    importer.Import(@namespace, unit);

    return @namespace;
}

XDocument parseXmlDocument(XmlElement ele)
{
    var xml = new XmlDocument();
    xml.LoadXml(ele.OuterXml);

    return xml;
}
```

And I'm trying to do this at .net core, to run on linux. I did in this way, because it was that worked for me.

**Comment by richlander** [comment]
This is now stale. Feel free to restart the conversation at dotnet/wcf.

**Comment by MiyamuraMiyako** [comment]
@joaomello Hi, What namespace have ```ServiceDescription``` class in dot net core, I can't find it.

**Comment by lee576** [comment]
> @joaomello Hi, What namespace have `ServiceDescription` class in dot net core, I can't find it.

me too

**Comment by mohdali** [comment]
Hi, is there an update on this? I'm looking for a similar scenario.

**Comment by MiyamuraMiyako** [comment]
@mohdali I think MS will not do this.
