### ISSUE TITLE
EventLog access is not supported on this platform (Linux)

### ISSUE THREAD

**Issue by kamaruddin-desai** [dotnet/core#3330]
# EventLog access is not supported on this platform (Linux)

System.PlatformNotSupportedException: EventLog access is not supported on this platform. An exception is thrown on linux platform(CentOS 7) when trying to read the remote windows host events. The same piece of code is working fine on Windows platform.

# General
`string queryString = "*[System/Level=2]"; // XPATH Query
                                                      //SecureString pw = new SecureString();//GetSecurePassword();
                                                      //SecureString theSecureString = new NetworkCredential("", "password").SecurePassword;
            string password = "PASSWORD";
            SecureString sec_pass = new SecureString();
            Array.ForEach(password.ToArray(), sec_pass.AppendChar);

            EventLogSession session = new EventLogSession(
             "IP_ADDRESS",                // Remote Computer hostname
			 "DOMAIN",                 // Domain
			 "USERNAME",                // Username
			 sec_pass,
             SessionAuthentication.Default);
            // Query the Application log on the remote computer.
            EventLogQuery query = new EventLogQuery("Application", PathType.LogName, queryString);
            query.Session = session;

            try
            {
                EventLogReader logReader = new EventLogReader(query);

                // Display event info
                //DisplayEventAndLogInformation(logReader);

                EventRecord eventInstance = logReader.ReadEvent();
                Console.WriteLine(eventInstance.ToXml());
            }
            catch (EventLogException e)
            {
                Console.WriteLine("Could not query the remote computer! " + e.Message);
                return;
            }`
.csproj file for the same
\<Project Sdk="Microsoft.NET.Sdk"\>

  \<PropertyGroup\>
    \<OutputType\>Exe\</OutputType\>
    \<TargetFramework\>netcoreapp3.0\</TargetFramework\>
  \</PropertyGroup\>
  \<ItemGroup\>
    \<PackageReference Include="System.Diagnostics.EventLog" Version="4.6.0-preview9.19421.4" /\>
  \</ItemGroup\>

\</Project\>

**Comment by ltouro** [comment]
The correct package refence is Microsoft.Extensions.Logging.EventLog. Looks like you are using System.Diagnostics.EventLog, which is from .NET Framework.

**Comment by leecow** [comment]
Closing due to this thread going stale. Please re-open if you're still having trouble.
