### ISSUE TITLE
beetween hrdware in qinten softeis on quantes

### ISSUE THREAD

**Issue by Bondzio** [dotnet/core#3331]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
It looks like this was created by accident or spam; can you please re-open with more information if you need help? Thanks.
