### ISSUE TITLE
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=w032eh4sjeeap8elwafzx94jg&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### ISSUE THREAD

**Issue by hellosav** [dotnet/core#3336]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by hellosav** [comment]
PLz ignore

**Comment by dasariramacharan** [comment]
If docker is not running in your PC you get this error.

Check if Docker is running by verifying  the system tray 

or 

Try running below command
`docker --version`
If the command runs, displaying some version information, then Docker is successfully installed.

Else please start the docker on your PC.
