### ISSUE TITLE
cannot get Auth code flow working with preview 9

### ISSUE THREAD

**Issue by murbanowicz** [dotnet/core#3338]
hi,
I am struggling to set up the identity server with 3.0. 
I provided detailed description on SO: https://stackoverflow.com/questions/57857813/identity-server-4-unauthorized-client

Client is now recognized when I added client to configuration json,.but cannot get it working with e.g. postman while the same postman working with the same flow on e.g. demo.identityserver.io 

I will really appreciate any help

**Comment by murbanowicz** [comment]
Giving more details:
It is for sure NOT LOADING clients added by: `.AddInMemoryClients(Config.GetClients())`
It is ignoring e.g. `"RequirePkce": false` in client section in `appsettings.development.json` and still requiring code challange...

**Comment by scalablecory** [comment]
Hi @murbanowicz,

Identity Server is a 3rd party software, not part of the .NET Core project. You will need to reach out to them through one of their [support channels](https://identityserver4.readthedocs.io/en/latest/intro/support.html).

**Comment by blowdart** [comment]
Wait a minute :)

Is this the build in identity server pieces in the SPA templates? Or is it in other app types?

**Comment by murbanowicz** [comment]
exactly, built in in the SPA templates

pon., 9 wrz 2019, 22:28 użytkownik Barry Dorrans <notifications@github.com>
napisał:

**Comment by blowdart** [comment]
Can someone move this to the asp.net repo please?

**Comment by murbanowicz** [comment]
Damn it! sorry, i am always confused where the issues should go.

pon., 9 wrz 2019, 22:36 użytkownik Barry Dorrans <notifications@github.com>
napisał:

**Comment by blowdart** [comment]
You and me both :)

**Comment by murbanowicz** [comment]
Further investigation shows that in any way I cannot make IdentityServer integration load my client.
I the logs, it is showing creating the client named as my project, nothing about my client, but this projectName client is also not available at all.
This is really strange.
I have tried to add it by `AddInMemoryClients` and also as:
```
.AddApiAuthorization<ApplicationUser, ApplicationDbContext>(c =>
                {
                    c.Clients = new ClientCollection(GetClients());
                });
```

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#13963
