### ISSUE TITLE
COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder564185280\myMicroservice.csproj: The system cannot find the file specified.

### ISSUE THREAD

**Issue by madhusudhan-v** [dotnet/core#3342]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

PS C:\Users\mveerabhadra\source\repos\dockerAspCoreDemo> docker build -t mymicroserviceimage .
Sending build context to Docker daemon  1.163MB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
 ---> 89ff00e52591
Step 2/10 : WORKDIR /src
 ---> Using cache
 ---> 157f0af6de03
Step 3/10 : COPY myMicroservice.csproj .
COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder564185280\myMicroservice.csproj: The system cannot find the file specified.

**Comment by MichaelSimons** [comment]
@madhusudhan-v - what is the name of your `csproj` file?  Where is it located?  Given the path you included in the description `C:\Users\mveerabhadra\source\repos\dockerAspCoreDemo`, it appears that you deviated from the tutorial.  That is fine, but you will need to update your Dockerfile accordingly.  Specifically the project name in the `COPY` and `ENTRYPOINT` instructions will need to be updated.

**Comment by scalablecory** [comment]
Closing stale issue; feel free to re-open if you have more details.

**Comment by mohan023** [comment]
You need to remove existing dockerfile and add new one using visual studio-->right click project->add new-> docker support.
There is a problem in project path defined in dockerfile.

**Comment by jhunexjun** [comment]
Answer is just move the Dockerfile to where your `.sln` project is, which your `.dockerignore` is also located.
