### ISSUE TITLE
Dotnet wont run after downlading .net frame

### ISSUE THREAD

**Issue by sreilly56** [dotnet/core#3346]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
After typing in Dotnet ,The command scree flashes for less than a second and disappears.

**Comment by sreilly56** [comment]
Yes that is what I was doing.  What should I do?

Shawn I. Reilly CPP®PSP®CHPA®CPD
6 Years of Service
Tech Systems, Inc.
4942 Summer Oak Drive<x-apple-data-detectors://0/1>
Buford, GA 30518<x-apple-data-detectors://0/1>
Office: 770-495-8700<tel:770-495-8700>, Ext. 138
Mobile: 864-238-7988
Fax: 770-495-1882<tel:770-495-1882>
Email: sreilly@techsystemsinc.com<mailto:sreilly@techsystemsinc.com>
www.techsystemsinc.com<http://www.techsystemsinc.com/>

Are you Motiv8ed?

ISO 9001 and ISO 27001 Certified
Tech Systems, Inc.
100% Employee Owned Company
Confidentiality Notice:
The information contained in this transmission is legally privileged and confidential, intended only for the use of the individual(s) or entities named above. This email and any files transmitted with it are the property of Tech Systems, Inc. If  the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, retention, or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. If you receive this communication in error, please notify us immediately by telephone call to 770-495-8700<tel:770-495-8700> or forward the e-mail to info@techsystemsinc.com<mailto:info@techsystemsinc.com> and then permanently delete the e-mail and destroy all soft and hard copies of the message and any attachments. Thank you for your cooperation.

On Sep 11, 2019, at 14:25, Carlos Sanchez Lopez <notifications@github.com<mailto:notifications@github.com>> wrote:


@sreilly56<https://github.com/sreilly56> where are you typing the "dotnet" command?

If you're typing it inside a terminal window like CMD or PowerShell, it shouldn't flash. Instead, it should print a message with the usage options.

The only possibility I can think about is that you may be typing "dotnet" in the "Run" window. Is this the case? Because if that's what's happening, then it makes sense that a window flashes, then disappears.

**Comment by scalablecory** [comment]
@sreilly56 many console apps close immediately when run; these will all "flash" when running via the Run window. The "dotnet" command is no different. You should be opening a command prompt first, and running "dotnet" from there.

Please re-open with some more details if this does not resolve your problem.

**Comment by sreilly56** [comment]
Sorry for not returning your email.  I have been out of town working and spent last two days with our company IT working it out.
It now works
Thank you
Shawn

Shawn I. Reilly CPP®PSP®CHPA®CPD
6 Years of Service
Tech Systems, Inc.
4942 Summer Oak Drive<x-apple-data-detectors://0/1>
Buford, GA 30518<x-apple-data-detectors://0/1>
Office: 770-495-8700<tel:770-495-8700>, Ext. 138
Mobile: 864-238-7988
Fax: 770-495-1882<tel:770-495-1882>
Email: sreilly@techsystemsinc.com<mailto:sreilly@techsystemsinc.com>
www.techsystemsinc.com<http://www.techsystemsinc.com/>

Are you Motiv8ed?

ISO 9001 and ISO 27001 Certified
Tech Systems, Inc.
100% Employee Owned Company
Confidentiality Notice:
The information contained in this transmission is legally privileged and confidential, intended only for the use of the individual(s) or entities named above. This email and any files transmitted with it are the property of Tech Systems, Inc. If  the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, retention, or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. If you receive this communication in error, please notify us immediately by telephone call to 770-495-8700<tel:770-495-8700> or forward the e-mail to info@techsystemsinc.com<mailto:info@techsystemsinc.com> and then permanently delete the e-mail and destroy all soft and hard copies of the message and any attachments. Thank you for your cooperation.

On Sep 19, 2019, at 14:18, Cory Nelson <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3346<https://github.com/dotnet/core/issues/3346>.
