### ISSUE TITLE
.NET Core 3.0 Blazor Server side <script> tag

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#3347]
# Issue Title
Can someone please explain why <script> tags are not allowed on a .razor page.
The error says "Script tags should not be placed inside components because they cannot be updated dynamically."

This makes no sense. I do not want the JavaScript to be updated dynamically. I want it to be static code executable by the component only.

It is extremely inconvenient to have to put JavaScript in a separate file outside the component. A component should be a view, style and code all in one place if one so chooses.

Is there a technical reason for this?

**Comment by carlossanlop** [comment]
I believe this question belongs to the https://github.com/aspnet/Blazor repo. @Pilchie since I don't have permission to transfer to aspnet repos, can you help transfer this issue to that repo (or whatever repo you think is the correct one).

**Comment by Pilchie** [comment]
This issue was moved to aspnet/AspNetCore#13917
