### ISSUE TITLE
Dead link in linker documentation

### ISSUE THREAD

**Issue by RemiBou** [dotnet/core#3348]
# Issue Title
In a linker documentation there is a dead link to the mono repo
# General

1. Open https://github.com/dotnet/core/blob/master/samples/linker-instructions-advanced.md
2. Scroll down
3. Click on " mono/linker documentation"
4. It goes to https://github.com/mono/linker/blob/master/linker/README which gives a 404. I couldn't find the good url for submitting a PR

**Comment by carlossanlop** [comment]
Thanks for reporting this, @RemiBou . I suspect the correct link is the README at the root of the repo: https://github.com/mono/linker/blob/master/README.md
I'll submit a PR to get it fixed.

**Comment by carlossanlop** [comment]
PR: https://github.com/dotnet/core/pull/3351

**Comment by RemiBou** [comment]
great thanks :)
