### ISSUE TITLE
error in building the docker image

### ISSUE THREAD

**Issue by yugandharmacherla** [dotnet/core#3349]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

getting error while building the docker from windows 10

Sending build context to Docker daemon  14.85kB
Step 1/5 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
ltsc2019: Pulling from windows/servercore
no matching manifest for linux/amd64 in the manifest list entries

**Comment by carlossanlop** [comment]
@rowanmiller I believe you own this tutorial. Do you have any contacts that could help with these instructions specifically?
@MichaelSimons if you get a chance, would you mind sharing your knowledge in case you happen to know what could cause this issue?

**Comment by MichaelSimons** [comment]
@yugandharmacherla - it appears that you are trying to build a Windows based Dockerfile within a Linux container environment.  This is not supported.  See Docker's [Get started with Docker for Windows guide](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) for details on how to switch the container mode on Windows.

**Comment by scalablecory** [comment]
Hi @yugandharmacherla, I'm assuming you've resolved your problem as we haven't seen a response for 8 days. I'm closing the issue, but if you're still having a problem please feel free to add more detail and re-open.
