### ISSUE TITLE
LINUX ONLY: Type.GetProperty does not find properties with cyrrilic chars if BindingFlags.IgnoreCase is set

### ISSUE THREAD

**Issue by volanavlad** [dotnet/core#3356]
# Issue Title

LINUX ONLY: Type.GetProperty does not find properties with cyrrilic chars if BindingFlags.IgnoreCase is set

The same code works fine at Windows.

# General

```
using System;
using System.Linq.Expressions;
using System.Reflection;

namespace GetPropertyTest
{

    class Program
    {
        public string Свойство_С_Киррилицей { get; set; }


        static void Main(string[] args)
        {
            var result = typeof(Program).GetProperty(nameof(Свойство_С_Киррилицей),
                BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public);
            Console.WriteLine(
                "typeof(Program).GetProperty(nameof(Свойство_С_Киррилицей),BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public)==" +
                result?.ToString());
            result = typeof(Program).GetProperty(nameof(Свойство_С_Киррилицей),
                BindingFlags.Instance | BindingFlags.Public);
            Console.WriteLine(
                "typeof(Program).GetProperty(nameof(Свойство_С_Киррилицей),BindingFlags.Instance | BindingFlags.Public)==" +
                result);

            var expr = Expression.New(typeof(Program).GetConstructor(new Type[0]));
            var exprProp = Expression.Property(expr, nameof(Свойство_С_Киррилицей));

            Console.WriteLine("Property expression was successfully created.");
        }
    }
}

```

see sample at https://github.com/volanavlad/DotnetCoreTests

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.801
 Commit:    c404ee777a

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /dotnet/sdk/2.1.801/

Host (useful for support):
  Version: 2.1.12
  Commit:  ccea2e606d

.NET Core SDKs installed:
  2.1.801 [/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/dotnet/shared/Microsoft.NETCore.App]

**Comment by MichalStrehovsky** [comment]
Let's keep just one issue for this.
