### ISSUE TITLE
.Net Core installation issue

### ISSUE THREAD

**Issue by sgaikar** [dotnet/core#336]
I am getting error '0x80070490 - elements not found' while installing .net framework core for Windows 7 machine from https://www.microsoft.com/net/core#windows
Attaching error log file. Can someone pls check. Thanks.

**Comment by Petermarcu** [comment]
@sgaikar , I don't see a log, can you please share?

**Comment by Petermarcu** [comment]
I'm going to close this assuming you got past it. Reopen with the log if you still need help.
