### ISSUE TITLE
dot net core support office project?

### ISSUE THREAD

**Issue by prasad-yadav** [dotnet/core#3363]
is there any support for office word add-in project in Dotnet core. as I am expecting will it be available in feature?

**Comment by scalablecory** [comment]
As far as I know, there is no "load a .NET Core DLL" plugin feature of Office. One recommended way to develop add-ins is [via HTML/Javascript](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins), so you could leverage ASP.NET Core toward that end.
