### ISSUE TITLE
Não consigo instalar o framework aspnetmvc no visual studio code linux mint

### ISSUE THREAD

**Issue by marcio36** [dotnet/core#3365]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Você pode fornecer uma descrição detalhada do que tentou e do erro que está recebendo?

(Por favor, perdoe se isso parecer estranho, estou usando um tradutor. 😊)

**Comment by leecow** [comment]
Closing due to lack of details. If you're still having troubles, please re-open with additional information about what you are experiencing.
