### ISSUE TITLE
HTTP GET string parameter ending with selected keywords are not allowed in .net core

### ISSUE THREAD

**Issue by maheshmore2691** [dotnet/core#3366]
Hi,

I know that this is not related to .NET core but still wanted to confirm that is there any way to fix it in .NET core.

Visual studio: 2019
.NET core: 2.2
Language: C#

#Issue: I have created .NET core API with GET endpoint decorated by attribute routing which accepts string parameter and here I am getting 404.7 response for some keywords  e.g. ".master", ".cs", ".mdf" etc. 

#Not Working code:
Accessing path: http://baseUrl/api/test/test.master
`[HttpGet("{userName}")]
        public ActionResult<string> Get(string userName)
        {
            return userName;
        } `

#Working code: Accepting userName as a query string is working perfectly. Is it best practice? 
Accessing path: http://baseUrl/api/test/test.master
`[HttpGet]
        public ActionResult<string> Get(string userName)
        {
            return userName;
        }`

I know that these are the file extensions which are not allowed to access as resources. But is there any other way to make it work other than accepting a parameter as a query string. Can I make it work with attribute routing?

Any lead would be appreciated.

Thanks

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#13958
