### ISSUE TITLE
Sending os specific notifications

### ISSUE THREAD

**Issue by fasetto** [dotnet/core#3368]
I want it to send a notification when certain event is done but could'nt find a way to do that.
Can we send os specific notifications ?

**Comment by leecow** [comment]
Can you elaborate on what you mean by "os specific notifications"? Have a look at https://docs.microsoft.com/en-us/dotnet/csharp/modern-events for .NET Core event handling.

**Comment by fasetto** [comment]
![no](https://user-images.githubusercontent.com/20834021/64962053-66f14b80-d89f-11e9-8489-7a65530a8e24.jpg)

Can we send notifications like this ?

**Comment by svick** [comment]
I don't think there is a built-in way to do that in .Net Core and I couldn't find a cross-platform library either. That means you will have to resort to a platform-specific approach. For Windows, [there is a guide that probably should work on .Net Core here](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop). For macOS, I think you should be able to use [`UNUserNotificationCenter` from Xamarin.Mac](https://docs.microsoft.com/en-us/dotnet/api/usernotifications.unusernotificationcenter?view=xamarin-mac-sdk-14). For Linux, you should be able to PInvoke [libnotify](https://developer.gnome.org/libnotify/0.7/NotifyNotification.html).

**Comment by fasetto** [comment]
@svick Thanks for the reply. I hope there was a build-in way to do that. 
Linux notifications seems easy but the other ones, don't know.

**Comment by scalablecory** [comment]
This seems like a useful library for someone to make!

**Comment by scalablecory** [comment]
Closing this out as there is nothing in .NET Core for it.
