### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by iegsaan** [dotnet/core#3370]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Can you provide specific information on what you are doing and what you are seeing?

**Comment by scalablecory** [comment]
Closing this out; please feel free to re-open with more info if you're still having the issue.

**Comment by iegsaan** [comment]
Hi sorry for my late reply Corey been in hospital . Thank you for your time
and patients
Regards
iegsaan adams
