### ISSUE TITLE
installing .NET SDK through terminal on ubuntu

### ISSUE THREAD

**Issue by FoxLenga** [dotnet/core#3372]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current?journey=vs-code
Operating System: Linux RHEL - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Can you provide specific information on what you are trying and what you are seeing? Details for installing on RHEL can be seen at [Using .NET Core 2.2 on Red Hat Enterprise Linux](https://access.redhat.com/documentation/en-us/net_core/2.2/html/getting_started_guide/gs_install_dotnet)
