### ISSUE TITLE
NETSDK1045 error

### ISSUE THREAD

**Issue by alinebernstein** [dotnet/core#3373]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/src/myMicroservice.csproj]
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by leecow** [comment]
Looks like you have a combination of 2.2 and a 3.0 preview installed and things are getting confused. Can you tell me more about your OS and provide the output of `dotnet --info`?

**Comment by alinebernstein** [comment]
[dotnetinfo.txt](https://github.com/dotnet/core/files/3616221/dotnetinfo.txt)

Hi Lee, yes I do have 3.0 preview installed, as I am a desktop developer and 3.0 was MS's first attempt to support WPF in Core. This is the kind of experience that makes Core feel rough around the edges and makes me stick with Framework.

Regards,
Aline

**Comment by alinebernstein** [comment]
Closed
