### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Nurbrock7** [dotnet/core#3379]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.****

**Comment by leecow** [comment]
Could you provide specific details on the problem you are having?

**Comment by Nurbrock7** [comment]
I can't save the file as Pages/Index.cshtml as Windows does not allow you
to Save a file using the '/' therefore I cannot run the file on Host 5000.

**Comment by svick** [comment]
If you followed the tutorial correctly, you will have the Index.cshtml file in the Pages subdirectory of the myWebApp directory. That's the file you're supposed to edit.

**Comment by scalablecory** [comment]
@Nurbrock7 did @svick's suggestion resolve your issue?

**Comment by scalablecory** [comment]
Closing this out; please feel free to re-open with more info if you're still having the issue.
