### ISSUE TITLE
Unable to reach deployed service with external IP address

### ISSUE THREAD

**Issue by TehAbyss** [dotnet/core#3382]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I followed the tutorial and had deployed my service to Azure and I was able to retrieve the external IP address. However, I am unable to reach the page http://[YOUR EXTERNAL IP ADDRESS]/api/Values. And I did replace [YOUR EXTERNAL IP ADDRESS] with the external IP address provided to me by the "kubectl get service mymicroservice --watch" command. I got the error "Hmmm...can't reach this page".

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14163
