### ISSUE TITLE
issue to resolved

### ISSUE THREAD

**Issue by AMULNISHASATHIK** [dotnet/core#3385]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by antonioortizpola** [comment]
Please add more info! the issue as is should be closed because it is not clear what are you asking for

**Comment by scalablecory** [comment]
@AMULNISHASATHIK, if you can provide some details we will be able to help, but currently there is nothing for us to act on. Please feel free to re-open the issue once you've added this, if you're still having problems.
