### ISSUE TITLE
Problemas con librerias externas

### ISSUE THREAD

**Issue by Tramaz** [dotnet/core#3390]
#Problemas con librerias externas

No crea archivos excel usando la librería SpreadSheetLight

# General

Net Core 3 preview 6
Sistema operativo: Windows 7

Hago uso de la librería SpreadsSheetLight para crear archivos de excel, al usar net core 3 el código compila y reconoce la librería así como sus clases y objetos, pero al hacer correr el programa no crea el archivo de excel y el programa se detiene.

**Comment by antonioortizpola** [comment]
Please in English, so we can join the conversation.

Also, It would help to share some code or the full error.

I also leave you issue description translated:

> I made use of the library `SpreadsSheetLight` to create excel files.  With Net Core the code compiles and the library is recognized, as their classes and objects, but when I try to run the code the file is not created and the program stops.

I would recommend to reach the maintainers of the library `SpreadsSheetLight`, since it will be probable that they need to make changes.

**Comment by carlossanlop** [comment]
@Tramaz this is not a dotnet issue, so I'll close this issue. Please contact the creators of SpreadSheetLight.
Este no es un problema con dotnet asi que cerrare el bug. Por favor contacta a los creadores de SpreadSheetLight para resolver el problema.
