### ISSUE TITLE
User.Identity.Name is null after login

### ISSUE THREAD

**Issue by neoffer** [dotnet/core#3391]
User.Identity.Name is null after login

Using .NET Core 3.0 rc1. I created a MVC project using VS 2019 Preview MVC template with Individual Authentication. I created a user using Register form, and Logged in. But **User.Identity.Name** returns **null** in my controller. I've tried httpContextAccessor, but it is still null.

Edit: I'm using JWT.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14160
