### ISSUE TITLE
CookieConsent does not exist in MVC template

### ISSUE THREAD

**Issue by neoffer** [dotnet/core#3392]
# CookieConsent does not exist in MVC template 

Using .NET Core 3.0 rc1 with VS 2019 Preview MVC template, the project does not contains CookieConsent.

# Also...

I’ve tried to add CookieConsent partial view, added Startup config for CookieConsent and added partial tag helper to the _Layout but the consent still did not appear.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14159
