### ISSUE TITLE
ApiAuthorizationDbContext does not support IdentityRole

### ISSUE THREAD

**Issue by neoffer** [dotnet/core#3395]
# ApiAuthorizationDbContext does not support IdentityRole

Using .NET Core 3.0 rc1 with IdentityServer4 and JWT. I couldn't find solution to add IdentityRole or my own ApplicationRole entity to the base class of ApplicationDbContext.

ApiAuthorizationDbContext<ApplicationUser> works but I need to use roles.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14161
