### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by swampig** [dotnet/core#3396]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant
no idea how to get this to work!

**Comment by HenningNT** [comment]
Without more information it would be impossible to help you.
Please explain what you are trying to do, what results you were expecting, and what you have tried to fix it.

**Comment by scalablecory** [comment]
@swampig, if you can provide some details we'll help, but right now there's nothing to work on -- feel free to re-open the issue once you've added these.

**Comment by swampig** [comment]
I was looking for a way to remotely control my recording studio software from my sound booth when on my own in the studio using my kindle fire i just need to control the transport functions and record functions
