### ISSUE TITLE
Installing .net core 2.2 SDK

### ISSUE THREAD

**Issue by meemwebsolutions** [dotnet/core#3397]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
The following error I received
Unable to loacate package dotnet-sdk-2.2

**Comment by antonioortizpola** [comment]
More info is needed, what was the output when you installed the version?, What did you type when the error was shown?

**Comment by scalablecory** [comment]
@meemwebsolutions have you performed the steps under "Register Microsoft key and feed"? The package is pulled from this feed.

**Comment by scalablecory** [comment]
Closing this out; please provide more info and re-open if you haven't been able to resolve this.
