### ISSUE TITLE
.NET Core native compilation fails with "No such file or directory"

### ISSUE THREAD

**Issue by SesticM** [dotnet/core#34]
Steps to reproduce the problem:

```bash
docker run -it --rm --name dotnet -w /root/myapp microsoft/dotnet bash
export DOTNET_HOME=/usr/share/dotnet/
dotnet init
dotnet restore
dotnet compile
bin/Debug/dnxcore50/myapp
```
outputs `Hello World!`

But when running a native compilation:

```bash
dotnet compile -n
```
generates:
```bash
....
Compiling [System.Private.CoreLib]System.Runtime.InteropServices.InteropExtensions.MightBeBlittable
No such file or directory
```

Could please someone help with this? Are there any relevant compilation logs generated? Am I doing something wrong?

**Comment by jkotas** [comment]
This is dup of #436. It is problem with stale bits or packaging - hello world works fine on Ubuntu in CoreRT CI.

**Comment by smartbitnl** [comment]
Try this before you compile native, it worked for me. 

```bash
sudo apt-get install -yq llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev make
```
Then I can run the binary `bin/Debug/dnxcore50/native/myapp` in the latest ubuntu-image and outputs `Hello World!`. If I run `bin/Debug/dnxcore50/myapp`in this same ubuntu I get `failed to locate CLR files` (as expected). This also runs fine in the ubuntu image although the binary is larger:
```bash 
dotnet compile -n --cpp
```

Still wondering where the relevant compilation & linking logs are generated. Can anyone help with that?

**Comment by SesticM** [comment]
Thank you [smartbitnl](https://github.com/smartbitnl), worked like a charm!
