### ISSUE TITLE
DataMember/JsonProperty Attribute is not honored in dotnet core 3.0

### ISSUE THREAD

**Issue by jikuma** [dotnet/core#3400]
I created a sample dotnet core 3.0 web api project and did the following changes,

1. Create a Model class TestData

```
using System.Runtime.Serialization;
namespace WebApplication17.Models
{
    [DataContract]
    public class TestData
    {
        [DataMember(Name = "testaction")]
        public string Action { get; set; }
    }
}
```

Then I made changes in controller WeatherForecastController, to add a post endpoint

```
[HttpPost("package/{packageName}/version/{version}")]
public void Post(string packageName, string version, [FromBody] TestData activityPayload)
        {
            Console.WriteLine(activityPayload.Action);
        }
```

Now I made a call from postman or curl with body 

```
{	
	"testaction": "action"	
}
```

Still in Post method of WeatherForecastController activityPayload.Action is null. I was expecting it to be 'action'

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14158

**Comment by antonioortizpola** [comment]
It could not be because Net core is using [Newtonsoft](https://www.newtonsoft.com/json)?

I have been achieving the same with [`JsonProperty`](https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm)

```
internal class IvrCardOperationRegistryResponseWrapper
{
    [SuppressMessage("ReSharper", "StringLiteralTypo")]
    [JsonProperty("registroOperacionTarjetaResponse")]
    public IvrResponseInfo IvrResponseInfo { get; set; }
}
```
