### ISSUE TITLE
PublishTrimmed on WPF Core 3 RC1 Could Not Load Type

### ISSUE THREAD

**Issue by kennymoto** [dotnet/core#3403]
When publishing WPF .net core 3 RC1 with PublishTrimmed I recieve the following edxception:
Could not load type Microsoft.CSharp.RuntimeBinder.Binder 
Publishing the application without trimming works fine.

**Comment by kennymoto** [comment]
The full error when publishing this WPF app is Could not load type 'Microsoft.CSharp.RuntimeBinder.Binder' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

**Comment by kennymoto** [comment]
Had to add <TrimmerRootAssembly Include="Microsoft.CSharp"/> to the proj file. Now the trimmed self contained exe works without error. Why is the reference dropped on trim?

**Comment by kennymoto** [comment]
Had to add <TrimmerRootAssembly Include="Microsoft.CSharp"/> to the proj file. Now the trimmed self contained exr works without error. Why is the reference dropped on trim?

**Comment by kennymoto** [comment]
'<TrimmerRootAssembly Include="Microsoft.CSharp"/>'

**Comment by kennymoto** [comment]
TrimmerRootAssembly Include="Microsoft.CSharp"

**Comment by kennymoto** [comment]
Had to add 'TrimmerRootAssembly Include="Microsoft.CSharp"' to the proj file. Now the trimmed self contained exr works without error. Why is the reference dropped on trim?

**Comment by carlossanlop** [comment]
@ericstj @joperez can you help with this issue?

**Comment by ericstj** [comment]
CC @eerhardt @sbomer 
Looks like ILLink is missing usage of RuntimeBinder.Binder.  I believe this is part of `dynamic` so I'm not surprised that the linker misses it.  I suspect the linker would also miss any types you reference from dynamic code. For Microsoft.CSharp   -- @jaredpar @cston @333fred

**Comment by mairaw** [comment]
What are the next steps on this issue? Should we move this to a different repo?

**Comment by eerhardt** [comment]
I think this issue can be closed. We have done a lot of work with PublishTrimmed in .NET 5 and 6. @kennymoto - can you try your app against the latest .NET 6 previews and see if you are still having problems? If so, please open a new issue in https://github.com/dotnet/runtime and upload an app that reproduces the problem. We can take a look there.

**Comment by eerhardt** [comment]
Also - please note that using `dynamic` in a trimmed application will produce a warning saying that it can break your application when trimming. In my experience, almost all usages of `dynamic` will result in a broken app - which is why we made it warn.
