### ISSUE TITLE
when i typed localhost:5000 on my browser it says "this site can't be reached" how can i start the local server and where can i get this local server

### ISSUE THREAD

**Issue by oddakussa12** [dotnet/core#3404]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by farshid3003** [comment]
Maybe your 5000 port is bussy. when you run the application it should shows you the port which application use

**Comment by scalablecory** [comment]
Are you starting the app with "dotnet run"? It should print the specific URL it binds to in console -- try using that instead of 5000.

**Comment by scalablecory** [comment]
Closing out due to lack of response; I hope you found a solution. Feel free to re-open with more information if you're still having an issue.
