### ISSUE TITLE
Consider also providing the sha256 hash in `releases.json`

### ISSUE THREAD

**Issue by isen-ng** [dotnet/core#3407]
# Issue Title

Consider also providing the sha256 hash in `releases.json`

# General

In the current `releases.json`, the hash is a sha512 hash. I am writing and maintaining a homebrew tap that allows users to download and install dotnet-sdk releases in parallel. I use your `releases.json` in your release notes to automatically update my taps weekly in a CI script.

However, the hash used in homebrew taps are sha256. This means that I cannot reuse the pre-computed sha512 and have to download the pkg and calculate the hash myself.

This is not a blocker, but is a waste of network bandwidth on your end, and a waste of time waiting for the download on my side.

**Comment by carlossanlop** [comment]
Hello @isen-ng , can you point the GitHub location of the releases.json? is it in this repo or in another one?

**Comment by isen-ng** [comment]
Hello! It is here in this repo.

Here is one of the releases.json

https://github.com/dotnet/core/blob/master/release-notes/2.2/releases.json

**Comment by leecow** [comment]
@MichaelSimons for awareness.

**Comment by carlossanlop** [comment]
@leecow has this been addressed?

**Comment by scalablecory** [comment]
@leecow should this be closed?

**Comment by leecow** [comment]
Yes. While this is an inconvenience, we prefer to maintain only the sha512 hash.
