### ISSUE TITLE
dotnet not install ubuntu

### ISSUE THREAD

**Issue by khairiGuiri123** [dotnet/core#3409]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Operating System: Linux Ubuntu 16.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Please share more information about your problem.

**Comment by leecow** [comment]
Closing due to the thread going stale. Please reopen with additional information if you're still having troubles.
