### ISSUE TITLE
Stateful Background Services in Container Orchestration?

### ISSUE THREAD

**Issue by BrandonCookeDev** [dotnet/core#3410]
# Issue Title

Alternative to Stateful Background Services in Container Orchestration?

# General

Hello, I'm the devops lead for my company. We use .NET Core and are currently running into a complication. Essentially we have code that uses a few background services in ASP.NET (using IHostedService), however it appears those services are stateful in nature. This is problematic because we wish to host this ASP.NET application in a container orchestration environment (AWS ECS). 

Because of the stateful nature, we can't have three different instances of the service running, otherwise data consistency issues or deadlocking issues become introduced. The obvious alternative is to create individual microservice/APIs for these, but given our timetable we are looking for a quicker solution that still may follow a "Best Practice".

I haven't been able to find information elsewhere on others running into this issue. Would you happen to have insight for what to do here? Thank you!

(PS. I think you guys are killing it with .NET Core. Keep up the great work!)

**Comment by carlossanlop** [comment]
@Pilchie can you help here?

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14583
