### ISSUE TITLE
i can't run dotnet on cmd

### ISSUE THREAD

**Issue by WKH-social** [dotnet/core#3415]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by farshid3003** [comment]
you need to install dotnet sdk to use dotnet cli
https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by scalablecory** [comment]
Hopefully @farshid3003's solution works for you; if not, please provide some additional information and re-open the issue. Thanks!
