### ISSUE TITLE
need .Net Framework for SyncToy?

### ISSUE THREAD

**Issue by sarahhardy** [dotnet/core#3418]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm not even sure if I am installing the right thing - what I really want to install is SyncToy, but it tells me I need to install .Net Framework, but when I go to the site this seems to be the only thing available.
This is the error I get:

Microsoft Windows [Version 10.0.17763.737]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\sarah>dotnet new console -o myApp
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by scalablecory** [comment]
Closing, solved in #3419.
