### ISSUE TITLE
please ignore my previous question

### ISSUE THREAD

**Issue by sarahhardy** [dotnet/core#3419]
please ignore my previous question. This is the answer to my issue 9though the SyncToy installer does send me automatically to this website):
https://answers.microsoft.com/en-us/windows/forum/windows_10-update/i-want-to-install-synctoy-but-it-say-i-need-net/61616e06-5785-4cac-a030-b59d1fe6ec2c

**Comment by scalablecory** [comment]
thanks, glad you found a solution.
