### ISSUE TITLE
[v3.0] When Newtonsoft will be dropped completely?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/core#3420]
Hi,

I used following command to generate single exe file for my project:
`dotnet publish -r win-x64 -c Release /p:PublishTrimmed=true`

In publish directory there are `Newtonsoft.Json.dll` and `Newtonsoft.Json.Bson.dll`. I didn't use `Newtonsoft` at all, so did you drop `Newtonsoft` in v3 or not?

Maybe `Newtonsoft` is referenced by other packages, am I right? if so, when Microsoft drop `Newtonsoft` from other packages (_`Microsoft.*` and `System.*`_)?

**Comment by nathan-alden** [comment]
You're almost certainly going to need Json.NET now and in the future as Microsoft's own JSON implementation does not support the higher-level abstractions we're all used to (i.e., traversing and modifying a JSON document). Microsoft's implementation, from what I've read and experimented with, is really more about performance than usefulness.

**Comment by dasMulli** [comment]
I think this particular issue is more about how the linker could do a better job breaking apart asp.net core to determine that no user path requires newtonsoft.json - or that the framework may need changes to enable to the linker to break it apart more easily.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14259
