### ISSUE TITLE
This package is not available in yum on Amazon Linux 2

### ISSUE THREAD

**Issue by petedev01** [dotnet/core#3421]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos7/runtime-2.1.0
Operating System: Linux CentOS 7 - x64

I have an EC2 instance, whose OS is "Amazon Linux 2".  I read that it was based on CentOS, so I tried these instructions but the installation package was not found by yum.

**Comment by leecow** [comment]
@petedev01 - 2.1.0 is not available in the CentOS repo (and it's out of support). If you're looking to write some code and give .NET Core a full test drive, you'll need the SDK. We've just release 3.0 so, follow the instructions at https://dotnet.microsoft.com/download/linux-package-manager/centos7/sdk-current and you should be good to go.

**Comment by scalablecory** [comment]
Closing stale issue; feel free to re-open if you think more is needed.
