### ISSUE TITLE
add new project  bugs after install .net core 3.0 rc1?

### ISSUE THREAD

**Issue by xubb1988** [dotnet/core#3422]
hi, i  install .NET CORE 2.2  on my computer, after install the .net 3.0 rc1, when i add a new project  in my project, i found it always  use the 2.2 SDK, not use the 3.0 rc SDK, but if i install the 3.0 pre sdk is ok.
 I try change the preview sdk options ,but i not work
my os is window 10 lastest ,vs2019  is lastest version
thanks for  you help

**Comment by farshid3003** [comment]
for using preview version on .net core sdk you need to install visual studio preview 
you can have both VS preview version and full version together in your machine.

**Comment by scalablecory** [comment]
.NET Core 3.0 templates are in the latest version of VS; please upgrade and you will find them there. If not, please re-open the issue with some details!
