### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by TupaL** [dotnet/core#3425]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by farshid3003** [comment]
You can go to the following address to download compatible sdk :
for 2.2 :
https://dotnet.microsoft.com/download/dotnet-core/2.2
for 3:
https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by leecow** [comment]
@TupaL, can you share the error you are seeing when installing?

**Comment by scalablecory** [comment]
Closing due to lack of response. Please feel free to reopen if you have more details.
