### ISSUE TITLE
libcurl dependency issue with Yocto build and pre-built .NET Core 2.1.603 arm binaries

### ISSUE THREAD

**Issue by CoderOnWinks** [dotnet/core#3427]
I am getting the below error when packaging one of my dotnet app. Can anyone please help

Problem: conflicting requests
  - nothing provides libcurl.so.4(CURL_OPENSSL_3) needed by linkagent-1.0-r0.armv7at2hf_neon

I am using curl-7.58 version.

I applied all changes which has been suggested as part of one of the existing issue in this repo. I have patched curl with .so.3. Any pointer will be helpful

**Comment by scalablecory** [comment]
It looks like you're using a binary built for a different version of curl.

@jeffschwMSFT @livarcocc is this one of your areas?

**Comment by livarcocc** [comment]
Not my area. Sorry.

**Comment by jeffschwMSFT** [comment]
@jkotas @jashook

**Comment by jkotas** [comment]
`libcurl` is dependency is optional for .NET Core 2.1. It is only used as a fallback that you need to explicitly activate. I would recommend to omit libcurl from your Yocto image unless you depend on this fallback (unlikely).

We plan to remove the dependency on libcurl completely for .NET 5: https://github.com/dotnet/corefx/issues/41183
