### ISSUE TITLE
Visual Studio 2019 .NET Core 3 project not included in release

### ISSUE THREAD

**Issue by rogerfar** [dotnet/core#3431]
When creating a new .NET core project, .NET core 3.0 is not listed in the templates:

![image](https://user-images.githubusercontent.com/1142915/65442613-b8db2980-dde9-11e9-9407-a5f94ad713b8.png)

Also it doesn't show up in the .NET Core selection of the project properties:
![image](https://user-images.githubusercontent.com/1142915/65442830-2424fb80-ddea-11e9-81a9-c652328d3598.png)

`dotnet --list-sdks` lists:
```
2.1.802 [C:\Program Files\dotnet\sdk]
2.2.204 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
```

This was an issue before too but I assumed that the release of 3 would include it.

I use VS2019 Community and installed `dotnet-sdk-3.0.100-win-x64.exe`

Will we have to wait for Visual Studio 16.4 before this is released?

**Comment by itorian** [comment]
I'm also excited to give it a try on VS 2019 Community, but same issue. Till date, i was using another instance of VS 2019 Community Preview with .net core 3 rc. Just, uninstalled it and installed .net core 3 and I can see it in VS 2019 Community Preview but not in VS 2019 Community.

**Comment by scalablecory** [comment]
@dagood any idea here?

**Comment by itorian** [comment]
Got it, .NET Core 3.0 requires Visual Studio 2019 16.3 or later. Ref https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0/

**Comment by rogerfar** [comment]
Sorry, just realized we're still on 16.2.5! I suppose we're waiting on the 16.3 release.

**Comment by dagood** [comment]
Glad you all were able to figure it out. 😄 

You can also see this info on the SDK download page, the yellow banner: https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-windows-x64-installer.

**Comment by rogerfar** [comment]
@dagood Any insider information about if 16.3 will be released soon? 😄

**Comment by itorian** [comment]
Yah, but waiting to see 16.3 in VS. Even MS team using Preview in live stream.

**Comment by rogerfar** [comment]
Well that was quick, 16.3 just released now 😅
