### ISSUE TITLE
Error 404 on Ubuntu 18.04 installation

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/core#3432]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-3.0.100
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The "sudo apt-get update" should be before "sudo apt-get install apt-transport-https" or else apt-get gets a 404 error

**Comment by scalablecory** [comment]
Thanks.

CC @rowanmiller

**Comment by scalablecory** [comment]
actually, @felipepessoto are you sure this is the case? apt-transport-https is not part of .NET, but it is required to be able to hit our https mirrors.

**Comment by rowanmiller** [comment]
cc @leecow and @dagood to chime in on this

**Comment by felipepessoto** [comment]
I created a VM from scratch (on Azure) and ran the instructions in https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-3.0.100.

Idk if this only happens on Azure. I'll create a new VM and get the output of the error

**Comment by dagood** [comment]
The `apt-transport-https` is required to download repo info from the Microsoft package repository, I believe, so I think you need another update in between, not just a move:

```sh
sudo add-apt-repository universe
sudo apt-get update # In case you didn't have universe enabled.
sudo apt-get install apt-transport-https
sudo apt-get update # Get the Msft repo into behind an https url.
sudo apt-get install dotnet-sdk-3.0
```

Your Azure VM probably has a minimal set of repos enabled--that would explain why you might see this there but not a Ubuntu Desktop VM, which I think has more enabled by default.

**Comment by felipepessoto** [comment]
Here is the output:

```
felipe@Teste:~$ wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
felipe@Teste:~$ ls
packages-microsoft-prod.deb
felipe@Teste:~$ sudo dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 56293 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.2) ...
felipe@Teste:~$ sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.
felipe@Teste:~$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 1692 B of archives.
After this operation, 153 kB of additional disk space will be used.
Err:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 apt-transport-https all 1.6.11
  404  Not Found [IP: 104.41.63.181 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_1.6.11_all.deb  404  Not Found [IP: 104.41.63.181 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by dagood** [comment]
Oh, that's different... appears that Azure has their own package mirror (`http://azure.archive.ubuntu.com/ubuntu`), wasn't aware of that. It looks like it was down for a bit, or the cache that's included in a fresh VMs is out of date and causes a 404, requiring an update before first use.

Seems more like an Azure issue at this point. If adding another `update` fixes it, I don't think it's *bad* for us to add it to the .NET Core install instructions, but it seems like it could be fixed closer to the source.

@leecow maybe you can weigh adding a workaround vs. directing this to Azure to fix?

**Comment by leecow** [comment]
I don't know anything about the Azure mirror but can imagine that it will lag release publishing by some amount.

**Comment by dagood** [comment]
`apt-transport-https` isn't our package, it should have been available for quite a while now. Note the 404 url:

```
http://azure.archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_1.6.11_all.deb  404  Not Found [IP: 104.41.63.181 80]
```
