### ISSUE TITLE
http://localhost:5000/api/Values is not opening

### ISSUE THREAD

**Issue by isiddhant** [dotnet/core#3435]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: macos

When I run http://localhost:5000/api/Values
it throws This site can’t be reachedlocalhost refused to connect. Search Google for localhost 5000 api Values ERR_CONNECTION_REFUSED error

**Comment by scalablecory** [comment]
When you launch your application, the URL it uses will print to console -- can you verify that you're using the correct URL? If you're still having an issue, please copy that console log and paste here. Thanks.

**Comment by isiddhant** [comment]
I am using this way

Amreshs-MacBook-Air:myMicroservice amresh$ dotnet run
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/amresh/myMicroservice

**Comment by isiddhant** [comment]
It looks like an update to the sample application was introduced in the 3.0 preview templates. dotnet run should still work but you'll need to enter http://localhost:5000/WeatherForecast into the browser to see output from the service.

They have to decide on how to update the sample.
