### ISSUE TITLE
.net core 3.0 xaml designer

### ISSUE THREAD

**Issue by gnimor** [dotnet/core#3439]
# XAML Designer does not show up

With Visual Studio 2019 Community 16.3.0 I created a WPF .Net core application. When I try to show the designer via the context menu in the XAML file, nothing happens. Is this the expected behavior - so is there no designer for WPF xaml files? At least I did no read anything in the release notes...

**Comment by LuvForAirplanes** [comment]
Open it with Visual Studio Preview 16.3 Preview 2.
Works in Preview, but not in standard.

**Comment by ValdimarThor** [comment]
Having the same problem using VS Professional

**Comment by Behodar** [comment]
Same here with the release version of 16.3 Enterprise. Works when using .Net Framework but not with Core; it just shows the XAML code and not the designer.

**Comment by fatihyildizhan** [comment]
This Pre-release VS Extension is just released. Try this: https://aka.ms/winforms-designer

or 

Update the `TargetFramework` in `.csproj` with this: `<TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>`

**Comment by ZhengDaoWang** [comment]
I download Pre-release VS Extension from https://aka.ms/winforms-designer，and I install it，but also
can't resolve this problem

**Comment by gnimor** [comment]
> This Pre-release VS Extension is just released. Try this: https://aka.ms/winforms-designer
> 
> or
> 
> Update the `TargetFramework` in `.csproj` with this: `<TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>`

We are talking about WPF not Windows Forms

**Comment by Darius82** [comment]
Same problem here VS 2019 16.3 CE

Can start a WPF Net Core project but there is no WPF designer available.

**Comment by Chcwh** [comment]
> This Pre-release VS Extension is just released. Try this: https://aka.ms/winforms-designer
> 
> or
> 
> Update the `TargetFramework` in `.csproj` with this: `<TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>`

It works, thanks!

**Comment by angelolopez** [comment]
Same issue with VS2019 16.3 CE

**Comment by Mika712** [comment]
> Update the TargetFramework in .csproj with this: <TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>

I use Wpf + Entity Framework Core
I changed TargetFramework => TargetFrameworks and have got:

NU1202	Package Microsoft.EntityFrameworkCore 3.0.0 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.EntityFrameworkCore 3.0.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)

**Comment by Behodar** [comment]
> Update the `TargetFramework` in `.csproj` with this: `<TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>`

Thanks; this does the trick in the meantime. However, I had to use net472 rather than net48; at least on my machine the VS 2019 installer didn't install/configure 4.8, so the newest framework I can build against is 4.7.2

**Comment by angelolopez** [comment]
Mi csproj file gas already that info bit xaml designer doesn't works

**Comment by mjuen** [comment]
Take a look at https://stackoverflow.com/questions/58077297/xaml-ui-designer-is-inactive-for-wpf-projects-in-net-core-3-0

It works when you re-enable the use of preview SDKs

![image](https://user-images.githubusercontent.com/7404431/65597620-da7b1300-df99-11e9-8870-b50aa106e0a2.png)

Filed an issue here:
https://developercommunity.visualstudio.com/content/problem/747608/wpf-designer-with-net-core-30-in-vs2019-163-only-w.html

**Comment by Herman44** [comment]
> Take a look at https://stackoverflow.com/questions/58077297/xaml-ui-designer-is-inactive-for-wpf-projects-in-net-core-3-0
> 
> It works when you (re-)enable the use of preview SDKs
> 
> ![image](https://user-images.githubusercontent.com/7404431/65597620-da7b1300-df99-11e9-8870-b50aa106e0a2.png)
> 
> Filed an issue here:
> https://developercommunity.visualstudio.com/content/problem/747608/wpf-designer-with-net-core-30-in-vs2019-163-only-w.html

This worked! Thank you so much!

**Comment by Behodar** [comment]
VS 16.3.1 is now available, and the designer now works correctly :)

**Comment by h0useRus** [comment]
I have 16.3.1 but still designer doesn't work

**Comment by M0n7y5** [comment]
Same

**Comment by Noemata** [comment]
When can we expect the designer to build with netcore 3 and the standard release of VS2019?  The build time is significantly longer if you have to use net48 just to get the designer.

**Comment by carlossanlop** [comment]
@grubioe can you help with this issue, or can you bring the right people to take a look?

**Comment by grubioe** [comment]
Seems that this was resolved via the following issue: 
 https://developercommunity.visualstudio.com/content/problem/743966/163-xaml-designer-not-showing-for-net-core-30-apps.html

@diverdan92 - FYI

**Comment by carlossanlop** [comment]
Since a fix was shared by @grubioe, I'm closing this issue as resolved.

**Comment by fatihyildizhan** [comment]
I upgraded **VS 2019 to 16.4.3** yesterday and XAML designer stop working. 

When I change **"Control Display Options"** to "Only Show Platform Controls" then it works but I lose Class Library or Third Party UserControls.

When I change **"Control Display Options"** to "Display All Controls" then the designer totally disappears.

* `C#, WPF, .Net Core 3.1`

![wpf-controls](https://user-images.githubusercontent.com/602600/72538975-ad77a680-388f-11ea-8827-d7a278c4e40d.png)
