### ISSUE TITLE
.NET Core 3.0 GA side-by-side with .NET Core 3.0 Preview 8

### ISSUE THREAD

**Issue by azureskydiver** [dotnet/core#3441]
# .NET Core 3.0 GA side-by-side with .NET Core 3.0 Preview 8

Is there a way to have .NET Core 3.0 GA and .NET Core Preview 8 run side-by-side on on the same IIS machine?

I have a set of QA and Production IIS machines which originally had .NET Core 3.0 Preview 8 Hosting Bundle. Some teams opted to go to Production with Preview 8 with their IIS hosted web applications because MS said that it was supported for production. Now that .NET Core 3.0 General Availability has been released, I installed this into the QA machine expecting Preview 8 to be left alone. As the installation ran, I saw the words "Previous installation" flash by on the progress bar and it made my stomach drop. When the installation finished, I found that Preview 8 had been uninstalled, and only the GA was left installed on the machine.

If I can't have the two versions running side-by-side, that will mean that my original plan to let teams transition from Preview 8 to GA as their sprint schedules allows them to do so. Now the various teams will be force to drop everything, do testing against GA, as well as synchronize their Production deployments with the installation of GA into Production.

As suggested in one of the comments in my [StackOverflow question](https://stackoverflow.com/q/58070360/56987), I tried re-running the Preview Installer. That resulted in me just being prompted to "Repair" or "Uninstall".

Or is this a non-issue because Preview 8 and GA sufficiently close to each other, than the teams really need to be doing something esoteric to hit upon any of the bugs and breaking changes between the two builds? e.g. It won't matter if they test against GA in the QA environment, and then go into Production which is running Preview 8. (I will admit that I've not yet dug through the list of bug fixes and breaking changes because originally I thought I'd have time to do this later while the two builds ran side-by-side.)

Or is this a non-issue because each web application has been built with all the binaries it needs, and the only thing that my IIS machines are providing to these teams is just the AspNetCoreModuleV2 ISAPI handler?

**Comment by leecow** [comment]
@shirhatti for the IIS side of the question.

**Comment by scalablecory** [comment]
CC @dagood

**Comment by scalablecory** [comment]
Generally the idea with installed versions is we *want* to upgrade to the latest version, but this case is a little more interesting.

I can't recall offhand if any APIs were changed or if it was purely bug fixes after Preview 8, but it was definitely (with very good justification) possible. I'm not sure how the IIS host runs, but you might be able to get away with using self-contained apps to ensure everyone has the same version.

**Comment by carlossanlop** [comment]
@wli3 @dsplaisted to confirm if the SDKs can live side by side.

**Comment by mairaw** [comment]
.NET Core 3.0 is no longer supported but I'm wondering if this is still a valid question for preview and GA releases. @shirhatti

**Comment by azureskydiver** [comment]
Go ahead close. I'll likely open a similar question about .NET 6.
