### ISSUE TITLE
.NET Core 3.0 GA didn't enable Nullable by default

### ISSUE THREAD

**Issue by hez2010** [dotnet/core#3443]
# .NET Core 3.0 GA didn't enable Nullable by default

Install .NET Core 3.0 SDK 3.0.100, run
```
dotnet new console
```

However, `<Nullable>enable</Nullable>` was not enabled by default.

**Comment by scalablecory** [comment]
@terrajobst did we intend to update our templates to enable NRT by default?

**Comment by terrajobst** [comment]
That's correct and by-design. We plan on doing this for .NET 5 /cc @MadsTorgersen @cartermp

**Comment by Gnbrkm41** [comment]
When is this happening? the preview SDKs don't seem to do this yet.
