### ISSUE TITLE
installed .NET CORE SDK 3.0 on my linux 16.04 server but getting below issue while making "dotnet --info" command.

### ISSUE THREAD

**Issue by dhaval905721** [dotnet/core#3445]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/runtime-3.0.0
Operating System: Linux Ubuntu 16.04 - x64

Failed to load ▒▒=, error: /usr/share/dotnet/host/fxr/5.0.0-alpha1.19427.12/libhostfxr.so: cannot open shared object file: No such file or directory
The library libhostfxr.so was found, but loading it from /usr/share/dotnet/host/fxr/5.0.0-alpha1.19427.12/libhostfxr.so failed

**Comment by leecow** [comment]
> Failed to load ▒▒=, error: /usr/share/dotnet/host/fxr/**5.0.0-alpha1.19427.12**/libhostfxr.so: cannot open shared object file: No such file or directory

Looks like you also have installed a daily build of .NET Core 5.0 which is causing trouble. Did you install using the .deb file at https://github.com/dotnet/core-sdk/ or did you use the tar.gz?

**Comment by dhaval905721** [comment]
i have just simply follow the below command to install same.

1 :: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
2 :: sudo dpkg -i packages-microsoft-prod.deb
3 :: sudo apt-get update
4 :: sudo apt-get install apt-transport-https
5 :: sudo apt-get install dotnet-sdk-3.0

**Comment by leecow** [comment]
Thanks for that. I would recommend cleaning the 16.04 machine up to ensure the 5.0.0-alpha files are removed. These steps should get you to a point where things are ok. 

```
sudo apt remove dotnet-host # this will use the package manager to uninstall everything it knows about. 
sudo rm -rf /usr/share/dotnet/ # this will remove everything the package manager doesn't know about
sudo apt-get install dotnet-sdk-3.0 # re-install the 3.0 SDK
```

**Comment by dhaval905721** [comment]
thanks leecow, it's works fine. we can close this issue.
