### ISSUE TITLE
I need to download, install .net core on SUSE 11 linux machine. I'm pretty new to linux.please help me

### ISSUE THREAD

**Issue by nazeer17** [dotnet/core#3448]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sles12/runtime-current
Operating System: Linux SLES 12 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
@nazeer17 If you're looking to get started, follow the install instructions at https://dotnet.microsoft.com/download/linux-package-manager/sles12/sdk-current and then work through the [Getting Started](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro) guide. 

There's an enormous amount of Linux tutorial information on the Internet. YouTube is your friend in this ;-)

**Comment by nazeer17** [comment]
Our machine is with  SUSE 11 version, please let me know if this version supports .Net Core?

**Comment by leecow** [comment]
12 is min supported version of SLES. See https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md.

**Comment by scalablecory** [comment]
Closing stale issue; @nazeer17 please feel free to re-open if you need more assistance.
