### ISSUE TITLE
Cannot find dotnet-sdk-3.0

### ISSUE THREAD

**Issue by N0tAI** [dotnet/core#3449]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-3.0.100
Operating System: Linux Ubuntu 19.04 - x64

When trying to download dotnet-sdk-3.0 from the console using "sudo apt-get install dotnet-sdk-3.0" I get the error message "E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'"

**Comment by dagood** [comment]
It works for me in a fresh `ubuntu:19.04` Docker container. Can you post the output of every command you ran during the install? It's possible you hit a problem during the `sudo apt-get update` step that prevented your machine from getting the Microsoft repository's list of packages. Sometimes it's hard to spot when that happens.

**Comment by N0tAI** [comment]
I got the solution, was just stupid me had done something to the Product key. I got it working, thanks!

**Comment by shakom** [comment]
i have the same issue ( ubuntu 18.04 / x64)

**Comment by dagood** [comment]
@shakom Please open a new issue with more details if you'd like help--in particular, this from above:

> Can you post the output of every command you ran during the install?

**Comment by shakom** [comment]
> @shakom Please open a new issue with more details if you'd like help--in particular, this from above:
> 
> > Can you post the output of every command you ran during the install?




here it is 

root@shakom:/home/shakom# wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

root@shakom:/home/shakom# sudo dpkg -i packages-microsoft-prod.deb
(Reading database ... 266700 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.2) over (1.0-ubuntu18.04.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.2) ...
root@shakom:/home/shakom# sudo add-apt-repository universe
'universe' distribution component enabled for all sources.
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                                                                                             
Hit:3 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                                                                                                                                                                                                              
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                                                                                                                                  
Hit:5 http://linux.teamviewer.com/deb stable InRelease                                                                                                                                                                                                                                   
Hit:6 http://repository.spotify.com stable InRelease                                                                                                                                                                                                               
Hit:7 http://dl.google.com/linux/chrome/deb stable Release                                                                                                                                                                                   
Hit:8 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                                                                            
Hit:9 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                                      
Hit:10 http://ppa.launchpad.net/lutris-team/lutris/ubuntu bionic InRelease                                                                     
Hit:11 http://repo.steampowered.com/steam precise InRelease                                                                                                                                             
Hit:12 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu bionic InRelease                                                                                                                              
Get:13 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                                          
Hit:14 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu bionic InRelease                            
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [9,051 kB]                                      
Hit:16 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu bionic InRelease                                                  
Hit:18 http://ppa.launchpad.net/snwh/pulp/ubuntu bionic InRelease                                                                            
Hit:19 http://ppa.launchpad.net/varlesh-l/bionic/ubuntu bionic InRelease                                               
Get:21 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                                                 
Hit:17 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                                                                                 
Fetched 9,214 kB in 3s (2,883 kB/s)                  
Reading package lists... Done
root@shakom:/home/shakom# sudo apt-get update
Hit:1 http://repo.steampowered.com/steam precise InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                                                                                             
Hit:3 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                                                                                                                                               
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                                                                                                                                  
Hit:5 http://linux.teamviewer.com/deb stable InRelease                                                                                                                                                                                                                                   
Hit:6 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                                                                                                                                                                                                 
Hit:7 http://repository.spotify.com stable InRelease                                                                                                                                                                                                
Hit:8 http://dl.google.com/linux/chrome/deb stable Release                                                                                                                                                                                          
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                                                                             
Hit:10 http://ppa.launchpad.net/lutris-team/lutris/ubuntu bionic InRelease                                                                                               
Hit:11 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                            
Hit:12 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu bionic InRelease                                                                                                      
Hit:13 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu bionic InRelease                                                                                                 
Get:14 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                          
Hit:15 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu bionic InRelease                                                                   
Hit:17 http://ppa.launchpad.net/snwh/pulp/ubuntu bionic InRelease                                                                                             
Hit:18 http://ppa.launchpad.net/varlesh-l/bionic/ubuntu bionic InRelease                                                                                                       
Get:20 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                              
Hit:16 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease        
Fetched 163 kB in 4s (40.9 kB/s)                                                      
Reading package lists... Done
root@shakom:/home/shakom# sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,692 B of archives.
After this operation, 153 kB of additional disk space will be used.
Selecting previously unselected package apt-transport-https.
(Reading database ... 266700 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.6.12_all.deb ...
Unpacking apt-transport-https (1.6.12) ...
Setting up apt-transport-https (1.6.12) ...
root@shakom:/home/shakom# sudo apt-get install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by dagood** [comment]
@shakom, it looks like `packages-microsoft-prod.deb` didn't install properly, your `sudo apt-get update` doesn't appear to have fetched from the Microsoft package repository.

It looks like the 3.0 instruction page is missing the workaround steps the 2.2 page has for this situation: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.402. I'm filing an internal issue to get the workaround steps ported forward.

For now, you should be able to replace `dotnet-sdk-2.2` with `dotnet-sdk-3.0` to use the workaround steps from that 2.2 page.

Locking because the original issue was resolved, this is an unrelated problem. Please file a new issue if the workaround steps don't work for you.
