### ISSUE TITLE
Incorrect instructions for Ubuntu 18.04?

### ISSUE THREAD

**Issue by gabthau** [dotnet/core#3451]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

The installation instructions seem to be incorrect.

In a fresh docker container running `ubuntu/latest`:
```sh
root@91e412352a08:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

Running the instructions in the "Register Microsoft key and feed" works fine.
```sh
root@91e412352a08:/# wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

root@91e412352a08:/# dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 4394 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.2) ...

root@91e412352a08:/# dpkg -l | grep microsoft
ii  packages-microsoft-prod 1.0-ubuntu18.04.2        all          Apt configuration for packages.microsoft.com
```

The first command of the "Install the .NET SDK" fails:

```sh
root@91e412352a08:/# add-apt-repository universe
bash: add-apt-repository: command not found
```

What is `add-apt-repository`?

```sh
root@91e412352a08:/# which add-apt-repository

root@91e412352a08:/# whereis add-apt-repository
add-apt-repository:


root@91e412352a08:/# dpkg-query -L packages-microsoft-prod
/etc
/etc/apt
/etc/apt/sources.list.d
/etc/apt/sources.list.d/microsoft-prod.list
/etc/apt/trusted.gpg.d
/etc/apt/trusted.gpg.d/microsoft-prod.gpg
/usr
/usr/share
/usr/share/doc
/usr/share/doc/packages-microsoft-prod
/usr/share/doc/packages-microsoft-prod/changelog.Debian.gz
/usr/share/doc/packages-microsoft-prod/copyright
/usr/share/doc/packages-microsoft-prod/microsoft-prod.gpg
/usr/share/doc/packages-microsoft-prod/microsoft-prod.list
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/packages-microsoft-prod
```

Skipping that command, the rest of the install works as expected.
```sh
root@91e412352a08:/# apt-get update
... snipped ...
root@91e412352a08:/# apt-get install apt-transport-https
... snipped ...
root@91e412352a08:/# apt-get install dotnet-sdk-3.0
... snipped ...

root@91e412352a08:/# dotnet --version
3.0.100
```

**Comment by dagood** [comment]
`add-apt-repository` is a command (part of the distro) to manage the active repositories. (It's from the `software-properties-common` package, I believe.) I'm not sure when it's available by default, maybe only in an Ubuntu Server installation?

There's some info about why that step was added in https://github.com/dotnet/core/issues/1822#issuecomment-409394938.

@leecow, do we need to reevaluate this step?

**Comment by leecow** [comment]
Yes. I'm afraid that chasing these configuration and repo specific variations will be a neverending challenge.

**Comment by carlossanlop** [comment]
@gabthau please take a look at the instructions again, they have been improved considerably, and add-apt-repository is no longer mentioned.
