### ISSUE TITLE
Missing assembly in PublishSingleFile

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#3455]
# Issue Title
An assembly specified in the application dependencies manifest (BVLocalSync.deps.json) was not found:
    package: 'Microsoft.PowerShell.Native', version: '6.2.0'
    path: 'runtimes/win-x64/native/pwrshplugin.pdb'

# General

The non PublishSingleFile application works fine. I have also tried installing nuget Microsoft.Powershell.Native but no change.

**Comment by scalablecory** [comment]
@livarcocc is this in your area?

**Comment by livarcocc** [comment]
cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
By default we do not bundle pdbs, you can explicitly include them with the following:

<ItemGroup>
    <Content Update="*.pdb">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
    </Content>
  </ItemGroup>

https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface

cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/PowerShell/PowerShell/issues/10266
The bug is fixed in the Powershell repo, not sure which version of the Powershell package has the fix.

@adityapatwardhan @SteveL-MSFT

**Comment by genifycom** [comment]
Thanks for the info Jeff
