### ISSUE TITLE
yum install rh-dontnet30 -y

### ISSUE THREAD

**Issue by ScathGames** [dotnet/core#3456]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current?journey=vs-code
Operating System: Linux RHEL 7 - x64

Simply I'm trying to get .NET for VSCODE on Ubuntu

The site says to use yum install rh-dontnet30 -y

ubbunto say
"Command 'yum' not found, but can be installed with:

sudo apt install yum
"
I do all of that and "sudo apt upadate"
so i retry "yum install rh-dotnet30 -y"
ubuntu says "You need to be root to perform this command.
"

retry "You need to be root to perform this command.
"

ubuntu says "There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
"
So I try all of these
~$ Run "yum repolist all"

Command 'Run' not found, did you mean:

  command 'zun' from deb python-zunclient
  command 'zun' from deb python3-zunclient

Try: sudo apt install <deb name>

~$ yum repolistall
No such command: repolistall. Please use /usr/bin/yum --help

:~$ repolist all
repolist: command not found

~$ yum repolist all
repolist: 0

:~$ yum-config-manager --enable<repo>
bash: syntax error near unexpected token `newline'

~$ yum-config-manager --enable <repo>
bash: syntax error near unexpected token `newline'

I'm just confused at this point .
How do I get .Net and C# support for VSCODE on Ubuntu

**Comment by dagood** [comment]
Ouch, I'm sorry you had to go through that. You were following the instructions for Red Hat (RHEL), not Ubuntu. You have to pick the `Linux Distribution` dropdown option matching your distro, Ubuntu, and its version, like 19.04: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current.

If you have any problems with the instructions that match your distro, please go ahead and file a new issue.
