### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by hmarco10** [dotnet/core#3458]
No existen repositorios habilitados.
dosnt not exist repositories enable
 Ejecute "yum repolist all" para conocer los repositorios existentes.
 Puede habilitarlos con yum-config-manager --enable <repositorio>

**Comment by leecow** [comment]
Can you provide specific details on what you have tried, what distro you're using and what error you're are seeing?

**Comment by scalablecory** [comment]
Closing out due to lack of response; please re-open if you have more detail.
