### ISSUE TITLE
Can't locate package in OpenSUSE repo

### ISSUE THREAD

**Issue by rusbaron** [dotnet/core#3459]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse15/sdk-3.0.100
Operating System: Linux openSUSE 15 - x64

I see only 2.2.402-1-x86_64 version of dotnet-sdk package in the repo. Did i miss something, or repo wasn't updated yet?

**Comment by NKarnam15** [comment]
@leecow @vivmishra

**Comment by vivmishra** [comment]
I do see the 3.0 SDK package in the repo. 
     https://packages.microsoft.com/opensuse/15/prod/ 
     dotnet-sdk-3.0.100-x64.rpm                         23-Sep-2019 15:25            67293098

Are you actually facing an issue while installing the same or just can't see the same?

**Comment by leecow** [comment]
OpenSUSE repo is updated and tested. Can you confirm that you are following the steps at https://dotnet.microsoft.com/download/linux-package-manager/opensuse15/sdk-current to install?

**Comment by jamshedd** [comment]
@rbhanda

**Comment by rusbaron** [comment]
@leecow Hi! Yes, i've done all this steps.
Today i see update for dotnet-host only. 
[https://i.imgur.com/TBHVjPy.png](Screenshot)
I'll try to delete all packages, delete repo and do all steps again

**Comment by rusbaron** [comment]
Yeap, after re-adding repo i see all packages.
Thanks!
