### ISSUE TITLE
in wsl,Unable to locate package dotnet-sdk-3.0

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/core#3464]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

in wsl : 
`sudo apt-get install dotnet-sdk-3.0:`

report:

E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by shakom** [comment]
i have the same issue ( ubuntu 18.04 / x64)

**Comment by vivmishra** [comment]
@leecow

**Comment by scalablecory** [comment]
Have you installed the feed?

```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

**Comment by leecow** [comment]
@kinglionsz - I've confirmed that 3.0 installs on WSL Ubuntu just fine after following the repo registration steps that @scalablecory has provided (also at https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current)

**Comment by kinglionsz** [comment]
> Have you installed the feed?
> 
> ```
> wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
> sudo dpkg -i packages-microsoft-prod.deb
> ```

Yes.

**Comment by kinglionsz** [comment]
> @kinglionsz - I've confirmed that 3.0 installs on WSL Ubuntu just fine after following the repo registration steps that @scalablecory has provided (also at https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current)

Yes. I installed step-by-step by the above process.But reported the issues.

And finally I [download the .NET Core binaries ](https://dotnet.microsoft.com/download/dotnet-core/3.0#sdk-3.0.100) and then:

`mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-linux-x64.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
sudo ln -s /home/kinglion/dotnet/dotnet /usr/local/bin/
`
It' OK now.

**Comment by vivmishra** [comment]
Closing as this is resolved.
