### ISSUE TITLE
CSHTML file not refreshing

### ISSUE THREAD

**Issue by justlearntutors** [dotnet/core#3467]
I make a change in a .cshtml file. I refresh the browser. I don't see the change. I rebuild the application. I see the change. It worked in asp net core 2.2.

How to solve?

https://stackoverflow.com/questions/54106058/why-does-page-not-update-after-refresh-when-cshtml-changes

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14430
