### ISSUE TITLE
Azure DevOps Build Agent scripts requires updated Release.json

### ISSUE THREAD

**Issue by 80dB** [dotnet/core#3475]
This file is currently not updated with the 3.0.0 release information:
https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json
( https://github.com/dotnet/core/blob/master/release-notes/releases.json )

This file is used by Azure DevOps Image Generation scripts (https://github.com/microsoft/azure-pipelines-image-generation) to create the hosted Azure DevOps build agents. Because it's missing the .NET Core 3.0 release information it's not possible to build .NET Core 3.0 apps using the hosted Linux agents in Azure DevOps (because it's not installed :)).

You get:
The current .NET SDK does not support targeting .NET Core 3.0.

Note: We are not affiliated with the Azure DevOps team, we just use their scripts to create our own build agent machines and we saw this issue.

**Comment by vivmishra** [comment]
@leecow

**Comment by leecow** [comment]
This will be handled by the Azure Pipelines folks. See https://github.com/microsoft/azure-pipelines-tasks/issues/11100
