### ISSUE TITLE
'WeatherForecast' could not be

### ISSUE THREAD

**Issue by hujingbao** [dotnet/core#3477]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: Linux CentOS 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
@hujingbao it's not clear what problem you're having here -- please provide some additional info and someone will try to help.

**Comment by scalablecory** [comment]
Closing out, please re-open if you can provide more information.
