### ISSUE TITLE
fsi error on ubuntu 19.04 and debian 10 

### ISSUE THREAD

**Issue by snashikkar** [dotnet/core#3482]
[fsierr.txt](https://github.com/dotnet/core/files/3658199/fsierr.txt)
# Issue Title

Starting dotnet fsi on the cli emits an error on ctrl-c handler installation failure
# General
Details:
snashik@hanuman ~> dotnet fsi                                                                             (base)

> Failed to install ctrl-c handler - Ctrl-C handling will not be available. Error was:
	Could not load file or assembly 'Mono.Posix, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. The system cannot find the file specified.

**Comment by scalablecory** [comment]
This issue was moved to dotnet/fsharp#7633
