### ISSUE TITLE
[Error] [JvmBridge] java.sql.SQLException: No suitable driver

### ISSUE THREAD

**Issue by schinchanikar-rms** [dotnet/core#3486]
I am trying to establish a connection to SQL server. I installed jdbc driver according to the instructions on https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver?view=sql-server-2017 with sqljdbc42.jar.
I also tried setting ClassPath as per the instructions. I still get the error 
[Error] [JvmBridge] java.sql.SQLException: No suitable driver

**Comment by scalablecory** [comment]
The SQL Server JDBC driver is not part of .NET Core. You might ask for some support from the [SQL Server forum](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?category=sqlserver).
