### ISSUE TITLE
No 3.0.0 version of Microsoft.NETCore.App

### ISSUE THREAD

**Issue by johnthcall** [dotnet/core#3488]
Some build systems use the refs in the Microsoft.NETCore.App nuget to build instead of installing the SDK of a specific version. Is there an ETA for the release of the 3.0.0 version of this package? I'm looking at package here: https://www.nuget.org/packages/Microsoft.NETCore.App

**Comment by NKarnam15** [comment]
@vivmishra @leecow

**Comment by vivmishra** [comment]
@wtgodbe @danmosemsft

**Comment by dagood** [comment]
We no longer produce this package, instead, .NET Core 3.0 uses targeting packs, apphost packs, and runtime packs. Check out https://github.com/dotnet/designs/pull/50 for more details.

The targeting pack has the refs, e.g. https://www.nuget.org/packages/Microsoft.NETCore.App.Ref/.
