### ISSUE TITLE
action in controller ends with 'Async' can not route correctly

### ISSUE THREAD

**Issue by skyridder** [dotnet/core#3489]
# Issue Title

action in controller ends with 'Async' can not route correctly

# General

I create a new MVC web project with net core 3.0 and in the  'Home' Conroller I write a action. Codes are blow

=== codes ===
public string TestAsync()
{
    return "aaa"
}
=== codes ===

when putting  url  '.../Home/TestAsync' in broswer, it appers 404.
when putting url  '.../Home/Test'  in broswer, it returns 'aaa'

I just create the default project and write the function, without doing something other.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/351
