### ISSUE TITLE
SDK Version 3.0.100 does not exist in OpenSuse 42.3 feed

### ISSUE THREAD

**Issue by ptfuller** [dotnet/core#3493]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse42-3/sdk-3.0.100
Operating System: Linux openSUSE 42.3 - x64

documentation at https://dotnet.microsoft.com/download/linux-package-manager/opensuse42-3/sdk-3.0.100 says to use this repo: packages.microsoft.com/opensuse/42.3/prod/

dotnet-sdk-3.0.100 does not exist at this location

**Comment by KoteshBoda** [comment]
@leecow

**Comment by leecow** [comment]
42.3 is [out of support](https://lists.opensuse.org/opensuse-security-announce/2019-07/msg00000.html) from OpenSUSE and therefore, is no longer supported by .NET Core. See [.NET Core Supported OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md) for details.
