### ISSUE TITLE
dotnet is not recognized

### ISSUE THREAD

**Issue by Krausso** [dotnet/core#3496]
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.

Could I include dotnet to PATH and how to do it if it's neccesary?

**Comment by scalablecory** [comment]
You're in Powershell, yea?

Windows installer should put dotnet in your path. However, you need to restart the console window after installing for it to take effect.

**Comment by scalablecory** [comment]
Please re-open with additional info if you need more help!
