### ISSUE TITLE
macOS .NET download issue

### ISSUE THREAD

**Issue by cherdeman** [dotnet/core#3497]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I've got a MacBook Pro running Mojave (10.14.6). I tried to follow the macOS download and install instructions and it seemed to install successfully. When I try to run the `dotnet` command in the terminal I get `-bash: dotnet: command not found`. I have tried restarting the termina. Thoughts?

**Comment by cherdeman** [comment]
The dotnet files are there and located in `/usr/local/share/dotnet/`. Path issue?

**Comment by dasMulli** [comment]
Maybe your bash profile fixes the PATH environment variable. (`~/.bash_profile` file).
New sessions should get `/usr/local/share/dotnet` added to their PATH because it was added to a file in `/etc/paths.d/`. This can be easily broken when the PATH is re-set in a profile (oh-my-zsh installer did this for zsh for quite a while)

**Comment by cherdeman** [comment]
Thats it! I added `export PATH="/usr/local/share/dotnet:$PATH"` to my bash profile and that works.

**Comment by dagood** [comment]
Yeah, we have https://github.com/dotnet/core-setup/issues/6521 open tracking removing our dependency on the macOS `path_helper` tool (`/etc/paths.d/`) in favor of symlinks in `/usr/local/bin/`. Then the .NET Core install shouldn't be affected by profiles that reset `PATH`.

Thanks for confirming the workaround helped.
