### ISSUE TITLE
Using Razor standalone in DotNet Core 3.0

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#3498]
# Issue Title
Now that we have separate invocations for MapRazorPages(), is it possible in DotNet Core 3.0 to create a console app that calls the Razor engine to create a page?

Are there any samples of this in DotNet Core 3.0?

# General

Calling the Razor engine without requiring routing, MVC etc is extremely use for reporting and a number of other scenarios. This has been frustratingly close in prior DotNet Core versions. With DotNet Core 3.0 several parts of the framework have been separated out and it would seem that it might be possible now to use Razor pages standalone.

Could someone on the team please help with a sample on how to do this?

**Comment by genifycom** [comment]
Is there something like RazorViewToStringRenderer for DotNet Core 3.0?

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14581
