### ISSUE TITLE
System.BadImageFormatException: 'Bad IL format.'

### ISSUE THREAD

**Issue by btogkas** [dotnet/core#3502]
Am working on code based on ZeroFormater Serializer where part of the serialization methodology is implemented by creating a dynamic method using IL Generator.
The implementation works on .Net Core 2.2 but not on 3

Are there any changes regarding how IL works-changes that might lead to this problem and how can it be resolved (have code to send but am waiting for your response)

**Comment by svick** [comment]
Can you share a small example code that demonstrates the problem? Or at least some details about what IL is causing the issue? Without that, I think it would be really hard to tell what change introduced in .Net Core 3.0 is causing this.

**Comment by btogkas** [comment]
[src.zip](https://github.com/dotnet/core/files/3666547/src.zip)

ByteAnalysis is the executing project. The IL generation happens on DynamicFormatter.cs, CreateSerialize method

**Comment by yyjdelete** [comment]
@btogkas 
`OpCodes.Callvirt` should be used instead of `OpCodes.Call` for `IZeroFormatterSegment.Serialize`.

**Comment by scalablecory** [comment]
@btogkas did @yyjdelete's note resolve your issue?

**Comment by scalablecory** [comment]
Please re-open with more info if you still need assistance. Thanks.
