### ISSUE TITLE
'GroupCollection' does not contain a definition for 'Count'

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/core#3504]
I recently tried to move my web application from .net cor 2.2 to 3.0. While the following code used to compile and run just fine, it now gives the error at every occurrence where Count is invoked on a System.Text.RegularExpressions.Match object

internal virtual bool IsValidKeywordFormat(Match m, out string error)
        {

            int matches = m.Groups.Count(t => t.Success);
            ......

Error: CS1061 : 'GroupCollection' does not contain a definition for 'Count' and no accessible extension method 'Count' accepting a first argument of type 'GroupCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by scalablecory** [comment]
The extension method you're looking for:

```c#
Enumerable.Count<T>(this IEnumerable<T> source)
```

Is not being resolved because `GroupCollection` only implements`IEnumerable`, not `IEnumerable<T>`.

You can instead use `Cast` to get a strongly typed `IEnumerable<T>`:

```c#
int matches = m.Groups.Cast<Group>().Count(t => t.Success);
```
