### ISSUE TITLE
project don't run after update to netcore 1.1

### ISSUE THREAD

**Issue by krzychu2** [dotnet/core#351]
Unfortunately, after upgrading my project to .net 1.1 Core project is not debugs
I click run and nothing happens
What could be the reason?

I have this error
The program '[13476] dotnet.exe' has exited with code -2147450749 (0x80008083).

**Comment by bartonjs** [comment]
@krzychu2 Try launching it as "Start Without Debugging" (Ctrl+F5).  I had a similar error and Ctrl+F5 let me see an error saying that the shared framework for version 1.1.0 was not found.  Then I ran the SDK installer from https://www.microsoft.com/net/core#windowscmd (https://go.microsoft.com/fwlink/?LinkID=835014) and everything was fine.

**Comment by Petermarcu** [comment]
@krzychu2 , did that help? Can you confirm you had .NET Core 1.1 installed?

**Comment by AdrienTorris** [comment]
I had the same problem, .NET Core 1.1 SDK wasn't installed. You can use the command _dotnet --info_ in the Package Manager Console to have the version of the dotnet framework your project uses (if it's not 1.1.0, the framework isn't installed)

**Comment by AdrienTorris** [comment]
To know if you have correctly install the .NET Core 1.1 SDK, you can also open the windows program and features and check if 1.1.0 SDK is installed.

**Comment by Petermarcu** [comment]
Ok, sounds pretty unanimous that its a missing 1.1.0 install. @krzychu2 I'm going to close this. Let us know if getting 1.1.0 installed doesn't fix the issue.
