### ISSUE TITLE
Returning 2D arrays on API

### ISSUE THREAD

**Issue by btogkas** [dotnet/core#3510]
Trying to return two dimensional decimal array from Controller.

public ActionResult<decimal[,]> TwoDArray()

This does not work on .Net Core 3 but works on 2.2
(Other methods work normally)

The configuration instead of UseMVC is 

app.UseRouting();
app.UseEndpoints(x =>
{
    x.MapControllers();
});

Is there something missing or?

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14577
