### ISSUE TITLE
No provider of 'dotnet-sdk-3.0' found.

### ISSUE THREAD

**Issue by RonaldGHempel** [dotnet/core#3511]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse42-3/sdk-3.0.100
Operating System: Linux openSUSE 42.3 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I followed along the steps as decribed here: https://dotnet.microsoft.com/download/linux-package-manager/opensuse42-3/sdk-3.0.100

But last step reports an error. Here is the output:

sudo zypper install dotnet-sdk-3.0
Refreshing service 'Basesystem_Module_x86_64'.
Refreshing service 'Containers_Module_x86_64'.
Refreshing service 'Desktop_Applications_Module_x86_64'.
Refreshing service 'Development_Tools_Module_x86_64'.
Refreshing service 'Legacy_Module_x86_64'.
Refreshing service 'Public_Cloud_Module_x86_64'.
Refreshing service 'SUSE_Cloud_Application_Platform_Tools_Module_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.
Refreshing service 'Server_Applications_Module_x86_64'.
Refreshing service 'Web_and_Scripting_Module_x86_64'.
Loading repository data...
Reading installed packages...
'dotnet-sdk-3.0' not found in package names. Trying capabilities.
No provider of 'dotnet-sdk-3.0' found.
Resolving package dependencies...

Nothing to do.

**Comment by dagood** [comment]
The instructions you used are the openSUSE Leap 42.3 ones, but based on `Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.`, it sounds like you're on SLES... can you post the output of `cat /etc/os-release` to be sure?

If you have more problems, can you post the output from all commands you ran during the install? Some error messages may pop up that aren't obviously errors.

**Comment by RonaldGHempel** [comment]
This is something a customer of mine reported. In trying to reproduce that I picked the wrong VM. Sorry for that. But customer is using openSuse 15.0. I asked him to send in his logs. As soon as I received them I will post them here.

**Comment by scalablecory** [comment]
@RonaldGHempel were you able to resolve this?

**Comment by RonaldGHempel** [comment]
Hello,
sorry for the delayed response. We had a long weekend over here. Did not receive any updated information from my customer. But I set up a VM with openSUSE Leap 15.0 and it worked just fine. Due to that result I will close this issue.
