### ISSUE TITLE
Install apt-transport-https before apt-get update

### ISSUE THREAD

**Issue by cidermole** [dotnet/core#3513]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Hi Microsoft team,

Following the install instructions, I encountered an issue where `apt-get install dotnet-sdk-3.0` would not work, due to `apt-get update` not getting the package information, due to:
```
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
```

Could you please change the order of the lines in the install instructions to the following, so the error does not happen?
```
apt-get install apt-transport-https
apt-get update
apt-get install dotnet-sdk-3.0
```

Thanks.

**Comment by dagood** [comment]
We rearranged this due to the opposite suggestion at https://github.com/dotnet/core/issues/3432, but moving the update line rather than adding a new one was a mistake IMO. We have an internal issue tracking changing this to have both updates to catch all scenarios--universe being newly activated and the system being unable to use the https feed without `apt-transport-https`.

The plan is:

```
sudo add-apt-repository universe
sudo apt-get update # In case you didn't have universe enabled.
sudo apt-get install apt-transport-https
sudo apt-get update # Get the Msft repo into behind an https url.
sudo apt-get install dotnet-sdk-3.0
```

**Comment by dagood** [comment]
I suppose in the Debian case it would be:

```
sudo apt-get update # In case you have never updated your repos. (E.g. Docker container.)
sudo apt-get install apt-transport-https
sudo apt-get update # Get the Msft repo into behind an https url.
sudo apt-get install dotnet-sdk-3.0
```

**Comment by scalablecory** [comment]
This has been resolved in code; please close once changes have deployed to the site.

**Comment by rowanmiller** [comment]
Change is live

**Comment by dagood** [comment]
Thanks! And thanks @cidermole for this detailed report.
