### ISSUE TITLE
problem in .NET

### ISSUE THREAD

**Issue by mamogo90** [dotnet/core#3517]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
ans:
windows 7 home premium
after installation 
in command prompt:
the application was unable to start correctlly (0xc000007b).

**Comment by scalablecory** [comment]
You might try reinstalling, that often indicates something was corrupted.
Alternately, can you do start->run->"winver" for me and give the full version # here?

**Comment by mamogo90** [comment]
i try reinstall but the same result...
version 6.1 (build 7601: service pack 1)
...
note:
 im noob ...this is my first time with .net ,, i try it from cmd, is it making diffrent to open it in any dir or i should be in where i installed it (program files)??????????????? it is possible that i make a silly mistake !!!!!

thank you very much .....

**Comment by carlossanlop** [comment]
Are you using the installer for the correct architecture? Meaning 32 bit or 64 bit. @mamogo90

**Comment by scalablecory** [comment]
Closing out due to lack of response; Please feel free to reopen if you can provide additional detail.
