### ISSUE TITLE
Cannot detect .Net Core, I downloaded, but I cannot see .Net Core templates

### ISSUE THREAD

**Issue by ZairovKutman** [dotnet/core#3523]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Can you execute `dotnet --version` on your terminal and print the result?

**Comment by scalablecory** [comment]
Where are you looking for templates? does `dotnet new console` not work, for instance?

**Comment by ZairovKutman** [comment]
1) I installed all .Net Core templates but didn't found System libraries, and 
2) I try again install .Net Core templates  this time I didn't see .Net Core tamplates in my Jetbrains Rider!
3) Now I haven't .Net Core templates, but System libraries found!

I didn't understand this?
>Среда,  2 октября 2019, 5:25 +12:00 от Cory Nelson <notifications@github.com>:
>
>Where are you looking for templates? does dotnet new console not work, for instance?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Кутман Заиров

**Comment by carlossanlop** [comment]
@ZairovKutman this sounds like a Jetbrains template issue, not related to .NET Core.
Feel free to reopen if you disagree or would like to clarify a bit more what you mean by .NET Core templates.
