### ISSUE TITLE
Support Requested For macOS 10.11.6

### ISSUE THREAD

**Issue by eat-sleep-code** [dotnet/core#3527]
# Issue Title

I can not install .net Core 3.0 SDK and runtime on a macOS 10.11.6

# General

The installation program for both the SDK and the runtime will not continue on El Capitan.   I have a perfectly fine 2009 Mac mini which can not install any later versions of macOS.   

The machine is more than adequately equipped in the hardware department and should be able to run .net Core 3.0 fine, but it appears you are arbitrarily blocking the install on this machine.

**Comment by dasMulli** [comment]
.NET core depends on security APIs introduced in 10.12 so even if you download and run the binaries (not installer), it would likely fail as soon as you start doing network calls over https.

**Comment by eat-sleep-code** [comment]
@dasMulli are there specifics on what security APIs these were?

**Comment by scalablecory** [comment]
I believe one feature lacking in 10.11 is ALPN support. @wfurt @bartonjs might have some more ideas.

**Comment by wfurt** [comment]
@dasMulli is correct. So going back to 10.11 is unlikely to happen for technical reasons. Also to goal is to support last 2 stable releases and 10.11 is far beyond that.
