### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by suyashs24** [dotnet/core#3529]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

OS - windows 8 32 bit machine
while trying to run dotnet have this dll file missing error
![Screenshot (4)](https://user-images.githubusercontent.com/56076220/66044039-4af7d600-e53e-11e9-95ab-95e71c63c5cc.png)

Please assist me

**Comment by scalablecory** [comment]
Please install the "Microsoft Visual C++ Redistributable for Visual Studio 2019" under "Other Tools and Frameworks" from our [Visual Studio downloads](https://visualstudio.microsoft.com/downloads/) page and let me know if this solves your problem.

**Comment by suyashs24** [comment]
Hi,

This didn't solved the problem the installation failed. The pop up asked to check log for more info. Please find attached log file.

[log.pdf](https://github.com/dotnet/core/files/3693090/log.pdf)

**Comment by scalablecory** [comment]
Thanks. @jeffschwMSFT any ideas?

**Comment by jeffschwMSFT** [comment]
Unfortunately the api-* binaries cannot be bundled within the app on Win8.  You can exclude these binaries using the following:
<ItemGroup>
    <Content Update="api-*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
We are looking into how to enable Win7/Win8 without this exclusion.

cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/coreclr/issues/26493
Please see further details in https://github.com/dotnet/coreclr/issues/26493
