### ISSUE TITLE
appsettings.json is included inside the executable when the project is published as a single file

### ISSUE THREAD

**Issue by IustinMicu** [dotnet/core#3531]
#appsettings.json is included inside the executable when the project is published as a single file

# General

I upgraded a .net core 2.2 application to 3.0 and I enabled the PublishSingleFile feature.

This is how the single file publish feature is configured:
`<TargetFramework>netcoreapp3.0</TargetFramework>`
`<PublishSingleFile>true</PublishSingleFile>`
`<RuntimeIdentifier>win-x64</RuntimeIdentifier>`
`<PublishTrimmed>true</PublishTrimmed>`
`<OutputType>Exe</OutputType>`

The issue is that the appsettings.json file is not published outside the executable file.
As a result I have no control to change the settings inside the file.
I tried different build actions for the appsettings.json file (ex: None, Resource, Content) but none of them placed the file outside the executable when being published.

**Comment by scalablecory** [comment]
This is intentional. You can override it by setting `ExcludeFromSingleFile` as explained in our [single-file publish](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface) document.

**Comment by IustinMicu** [comment]
I didn't know about `ExcludeFromSingleFile ` or that design doc that you shared.. I only learned about this feature from blogs on the microsoft website :D

Thanks for the answer.
