### ISSUE TITLE
Tutorial Hello World

### ISSUE THREAD

**Issue by tosser23** [dotnet/core#3540]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Operating System Windows 10

error message after having run docker build -t mymicroservice .

hcsshim::CreateComputeSystem 5cb2cda92e7b058f2d246f14ff74fe0fb8cb2268a7d3e8791eedc6ab5cfa34c5: The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"Container","Name":"5cb2cda92e7b058f2d246f14ff74fe0fb8cb2268a7d3e8791eedc6ab5cfa34c5","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\5cb2cda92e7b058f2d246f14ff74fe0fb8cb2268a7d3e8791eedc6ab5cfa34c5","Layers":[{"ID":"a77c493a-90ab-5be4-bd54-869b12df2302","Path":"C:\\ProgramData\\Docker\\windowsfilter\\20c61c8c3fa4fdcc2070f3fe52529e1dea2400f3b3034dbace3584b521b32eca"},{"ID":"5c52c06b-7646-5d79-a489-9f7b62d6c8eb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5e851f68fd74128091b011d836566953cdd2a733ad1bad0534976be78867ff06"},{"ID":"b583fe43-676f-5b0c-9c39-a7f2c1977673","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ae5686b65abc355d60d7e4001ad7db3f4939d3655c15a4d8b570522a594e82da"},{"ID":"7330528e-de58-508d-bd58-70ff496807f6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\992cbfda2fe8d3175e4fad5667e03052d7b93e915efb347a4426b36aedb2fedc"},{"ID":"67ee36a1-d331-5003-9379-1ded731d4e91","Path":"C:\\ProgramData\\Docker\\windowsfilter\\32c0d86ea6e0c49d12f6d37b3f88f91af56861333659ad855d8287d2bb9ce285"},{"ID":"23acdfac-6826-5e70-9277-55db3b92b19f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5698c2333e2e30c8e880b11a9b2eef0731f42b8205552d62eaa829cee3deed18"},{"ID":"dfcf552c-e459-5d5d-bb07-15163d80a98a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\36f7b46598ee7efec51b87250bdb6c4a3f189f9257efd3aa42e56af1291c5e67"},{"ID":"7376edd1-6d81-56b4-a8a3-a32f347b98d1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\36bbdc493c5721c0c9b465b278d88f5df103b724cff806e877bc6256012518ee"},{"ID":"25ca38ce-f4df-5d20-a400-e9bbc3360fbe","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ca5566a0e4600866e4672deb05fcd457c387ce46b2853afe7eb3a9e55a6d1e2b"}],"HostName":"5cb2cda92e7b","HvPartition":true,"EndpointList":["2DEC7148-2819-49E3-8AB1-DAC08B899428"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\ca5566a0e4600866e4672deb05fcd457c387ce46b2853afe7eb3a9e55a6d1e2b\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})

Could you please help on the above?
Regards giuseppe

**Comment by scalablecory** [comment]
@shirhatti

**Comment by leecow** [comment]
That looks like a Docker error and isn't even getting to the microservice. @tosser23 - can you successfully run the Docker hello-world test with `docker run hello-world`?

**Comment by tosser23** [comment]
Hello there,


nope actually same error even when trying docker run hello-world

**Comment by leecow** [comment]
Thanks - something is up with your Docker install then. You'll need to work that out before moving on to the .NET Core experimentation.

**Comment by tosser23** [comment]
Hello there,

reading the requirements for Docker installation

What to know before you install

System Requirements
•Windows 10 64-bit: Pro, Enterprise, or Education (Build 15063 or later).
•Hyper-V and Containers Windows features must be enabled.

•The following hardware prerequisites are required to successfully run Client Hyper-V on Windows 10:
◦64 bit processor with Second Level Address Translation (SLAT)
◦4GB system RAM
◦BIOS-level hardware virtualization support must be enabled in the BIOS settings. For more information, see Virtualization.

I certainly don't have SLAT on my laptop and that might be the reason. Suspecting that, I used a Azure VM with Windows 10 image as my development laptop. Same result.
Do you know which Azure images has SLAT capability?
Cheers giuseppe
