### ISSUE TITLE
multitargetting netstandard2.1 and netstandard2.0

### ISSUE THREAD

**Issue by achandlerwhite** [dotnet/core#3541]
Hello, I have a class library that supports both netcoreapp2.x and netcoreapp3.0 applications.

I am not clear on if I need the class library to target just netstandard2.0 or both 2.0 and 2.1. 

I do not use any new methods in netstandard 2.1. However, if I just target netstandard2.0 then netcore3.0 apps can reference my project but the older package version for EFCore 2.x would  cause a version conflict warning if the application itself is using EFCore 3.0.

I figure it I also target netstandard2.1 then at least I can control the package version my library uses and avoid a potential conflict.

Currently I have my csproj as shown below. Is there a better way to do this?

```
<Choose>
    <When Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
      </ItemGroup>
    </When>
    <When Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.0" />
      </ItemGroup>
    </When>
  </Choose>
```

**Comment by leecow** [comment]
Adding a few folks for guidance here. @anurse @davidfowl

**Comment by achandlerwhite** [comment]
@leecow thanks! I will update the question this with some more details tonight.

**Comment by anurse** [comment]
The 3.0 version of `Microsoft.AspNetCore.Identity.EntityFrameworkCore` requires a _minimum_ of `netstandard2.1` (or `netcoreapp3.0`) so if you want to be able to support `netstandard2.0` then the condition makes sense.
