### ISSUE TITLE
Deserialization of Arrays in Get Methods Fail to Parse Correctly

### ISSUE THREAD

**Issue by MikeAllen775** [dotnet/core#3543]
Just upgraded my API from .NET Core 2.2.3 to .NET Core 3.0.0.  For other reasons (using Swagger) I needed to downgrade JSON serialization back to Newtonsoft by using AddNewtonsoftJson in my startup.

Previous GET methods that accept an array argument were no longer parsing it correctly when passed JSON in JavaScript(which ends up defaulting to a comma-delimited string).

For example:

Sending the following JSON in JavaScript:

`{ values: ["a", "b", "c"] }`

Results in a querystring that looks like:

`?values=a,b,c`

In the C# method:

`[HttpGet]
public async Task<IActionResult<MyClass>> Get(string[] values) 
{
  // If .NET Core 3.0, values is an array with a single element of "a,b,c".
  // If .NET Core < 3.0 values is an array with 3 elements.
}
`

**Comment by carlossanlop** [comment]
@JamesNK should this issue be transferred to the [Newtonsoft repo](https://github.com/JamesNK/Newtonsoft.Json)?

**Comment by JamesNK** [comment]
It should be in aspnet/aspnetcore

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#14731
