### ISSUE TITLE
cannot install .net core 3.0 in Ubuntu 

### ISSUE THREAD

**Issue by AhmedRamadan001** [dotnet/core#3545]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-3.0.100
Operating System: Linux Ubuntu 18.04 - x64

i have .net core 2.2.402 on my ubuntu machine and trying to install .net core 3.0 
by the command line 
```
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-3.0
```

> sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-3.0

i got this output 

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
dotnet-sdk-3.0 is already the newest version (3.0.100-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

then when check the .net core version by 

> dotnet --list-sdks

i got this output

> 2.2.402 [/usr/share/dotnet/sdk]

**Comment by scalablecory** [comment]
@dagood @leecow

**Comment by dagood** [comment]
The output `dotnet-sdk-3.0 is already the newest version` means your machine already has the package installed, so the command didn't do anything this time. I'd suggest trying a reinstall in case the files were simply deleted, or if a failure occurred when the package was originally installed:

```
sudo apt-get install --reinstall dotnet-sdk-3.0
```

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if @dagood's suggestion didn't work for you.
