### ISSUE TITLE
.dll file failed to execute

### ISSUE THREAD

**Issue by Terieyenike** [dotnet/core#3548]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Can you paste the full output here please? Thanks.

**Comment by Terieyenike** [comment]
Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by aik-jahoda** [comment]
can you please run `dotnet --info` and provide the output? Can you also provide steps that you did and the console outputs?

**Comment by aik-jahoda** [comment]
From the ticket description, it is not clear what is the actual issue. I have tried to install 3.0 SDK on freshly installed mac and try the hello world tutorial. I success without any issue.

Can you please try again and share the error message?

**Comment by scalablecory** [comment]
Closing due to lack of response. Please re-open if you're still having a problem and have more info.
