### ISSUE TITLE
I mistakenly edited Index.cshtml.cs with code that should have gone into Index.cshtml.  How do I reset the code originally in Index.cshtml.cs

### ISSUE THREAD

**Issue by danmertens** [dotnet/core#3552]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I mistakenly edited Index.cshtml.cs with code that should have gone into Index.cshtml.  How do I reset the code originally in Index.cshtml.cs

**Comment by choXberg** [comment]
You could simply generate a new webApp and copy the cshtml.cs content back to your tutorial webapp:

`dotnet new webApp -o myWebApp --no-https`


/Pages/Index.cshtml.cs

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace myWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

```

/Pages/Index.cshtml
```
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
```

**Comment by danmertens** [comment]
Thank you.  That’s in fact what I did.

**Comment by scalablecory** [comment]
Thanks.
