### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Electrobits01** [dotnet/core#3558]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian10/sdk-current
Operating System: Linux Debian 10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I have run the following command and getting 3 error code , please see below:
sudo apt-get install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'
![2019-09-01-125502_1024x768_scrot](https://user-images.githubusercontent.com/35998620/66270356-78839e80-e820-11e9-9237-4e80530ada98.png)

**Comment by dagood** [comment]
Interesting... it looks like you may have posted the wrong screenshot, however it does show what the issue is. 😄

You followed the instructions for `Linux Debian 10 - x64`, however you're using a Raspberry Pi, which does not run x64. You need to follow this link from that page instead:

> Not running x64? You'll need to [download the .NET Core binaries](https://dotnet.microsoft.com/download/dotnet-core/3.0#sdk-3.0.100) instead.
