### ISSUE TITLE
Update .NET Core native prerequisites for Windows

### ISSUE THREAD

**Issue by VahidN** [dotnet/core#356]
Windows dependencies of [.NET Core native prerequisites](https://github.com/dotnet/core/blob/master/Documentation/prereqs.md#windows-dependencies) are outdated. 
It should be corrected to version 14.0.**24215**.1
Direct Download URLs:
https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe
https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe

[Reference](http://stackoverflow.com/a/34209692/298573)

**Comment by Petermarcu** [comment]
Thanks. I've opened this issue to track this: https://github.com/dotnet/core-setup/issues/1021

**Comment by Petermarcu** [comment]
I misread the issue. Reopening. I believe we're pointing to the right place but that page that we assumed would always point to the latest is not. I'll see if that page can get updated.

**Comment by Petermarcu** [comment]
In .NET Core 2.0, this will not be an issue any longer as we removed this dependency. Beyond that, I don't think I can do anything more to address this so I'm going to close it. Thanks for the feedback!
