### ISSUE TITLE
Problem installing .NET framework 

### ISSUE THREAD

**Issue by 100alex001** [dotnet/core#3561]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

System 32, well after i do dotnet run on command prompt this appears: 
Program.cs(10,54): error CS1003: Syntax error, ',' expected [C:\WINDOWS\system32\system32.csproj]

The build failed. Fix the build errors and run again.

Well i think it may be Program.cs which i edited but didnt know how to do it properly has it was asked on the tutorial.

**Comment by svick** [comment]
First of all, you created your project in the C:\WINDOWS\system32 directory. I would advise against doing that, since it's a system directory.

Second, can you post the code you have in your Program.cs?

**Comment by scalablecory** [comment]
Closing due to lack of response; please feel free to reopen if you're still having this problem and have more detail.
