### ISSUE TITLE
No .NET Core 3.0 RPM packages for RHEL 7

### ISSUE THREAD

**Issue by tomaxsas** [dotnet/core#3567]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current
Operating System: Linux RHEL 7 - x64

There is no RPM pakages from RHEL. When they will be available?

**Comment by RheaAyase** [comment]
As soon as technically possible. Sadly we could not build dotnet 3.0 before it was released by Microsoft therefor we're a bit behind.

**Comment by tomaxsas** [comment]
Any ETA when it will be available?

**Comment by RheaAyase** [comment]
None that could be publicly disclosed.

**Comment by hellfirehd** [comment]
Does this also affect CentOS 7?  See [this Issue](https://github.com/dotnet/core/issues/3487#issuecomment-539670974) for more information.

**Comment by omajid** [comment]
@hellfirehd From a quick look, that issue doesn't look related to me. `dotnet --info` there says `Microsoft.NETCore.App 3.0.0` is installed but the application wont run for some reason. This issue is about the .NET Core packages not being available for RHEL 7 at all.

**Comment by hellfirehd** [comment]
Yes
