### ISSUE TITLE
Links are backwards at Preview 3 build 004056.md page

### ISSUE THREAD

**Issue by GuardRex** [dotnet/core#357]
@blackdwarf @piotrpMSFT 

https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md

![capture](https://cloud.githubusercontent.com/assets/1622880/20457357/22bcf842-ae4f-11e6-8133-b1526018ce00.PNG)

The 32-bit link downloads the x64 installer ... the 64-bit link downloads the x86 installer.

**Comment by svick** [comment]
There are already two PRs to fix that: https://github.com/dotnet/core/pull/343 and https://github.com/dotnet/core/pull/350.
