### ISSUE TITLE
Upgrade to .Net Core 3.0 - dotnet ef is missing

### ISSUE THREAD

**Issue by ckruegerkpmg** [dotnet/core#3570]
# After Upgrades to .Net Core 3.0 dotnet ef is missing

# General

After upgrading Visual Studio 2019 from 16.0/16.1/16.2 to 16.3 .Net Core get's upgraded to 16.3
All Projects that are useing Entitfy Framework are failing.

This helps: dotnet tool install --global dotnet-ef
BUT
global didn't install dotnet-ef for the machine globally, only for the user account.
A build Agent typically doesn't run in the same identity than the user that is installing Visual Studio.

It's very annoing that .Net Core 3 installation prevent building .Net Core 2.x Code in it's default installation.

**Comment by scalablecory** [comment]
@Pilchie @livarcocc

**Comment by Pilchie** [comment]
This issue was moved to aspnet/EntityFrameworkCore#18282
