### ISSUE TITLE
daily-builds.md is outdated

### ISSUE THREAD

**Issue by EgorBo** [dotnet/core#3572]
`.NET Core SDK 3.0.1xx (Master)` link leads to .NET Core 5.0 SDKs
https://github.com/dotnet/core/blob/master/daily-builds.md

**Comment by scalablecory** [comment]
This table just needs some reworking; the target page holds all the SDKs so the 2.x and 3.x links are identical. No point in extending it with yet more dupes for 5.0.

It looks like https://github.com/dotnet/core-sdk/blob/master/README.md needs to be updated too, it is still pointing to the RC1 of 3.0.

**Comment by mairaw** [comment]
I'm wondering if this issue can be closed? It seems @rbhanda has updated that page last March.

**Comment by mairaw** [comment]
Closing since both files have been updated since then. Please reopen if there are still issues with any of the files.
