### ISSUE TITLE
Can't run Visual Studio on Ubuntu, plug-ins do not work, errors keep popping up.

### ISSUE THREAD

**Issue by aaeeoo** [dotnet/core#3573]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
There's not enough actionable information here. Can you please post details on the errors you're seeing?

Are they related to .NET Core, or are they VS Code errors? If the latter, a report to VS Code repository would make more sense.

**Comment by aaeeoo** [comment]
here are some of the errors...
at the beginning of the installation tutorial on the forum it says to
register the Microsoft key, what does that mean? where do I get this key?
where do I register it?
thank you in advance.

**Comment by scalablecory** [comment]
> at the beginning of the installation tutorial on the forum it says to register the Microsoft key, what does that mean? where do I get this key?

The dpkg command on that page should install it all for you:

```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

Are you getting an error when running this?

**Comment by scalablecory** [comment]
Closing due to lack of response. Please re-open if you're still having the issue and can provide additional detail.
