### ISSUE TITLE
dotnet : The term 'dotnet' is not recognized as the name of a cmdle

### ISSUE THREAD

**Issue by bak83** [dotnet/core#3574]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Did you restart your command prompt after installing? PATH variables are updated and existing prompts don't get them.

**Comment by scalablecory** [comment]
Closing due to lack of response; please feel free to re-open if you're still having this issue and can provide more detail.
