### ISSUE TITLE
Entity Framework logs not showing up anymore after migration to .NET Core 3

### ISSUE THREAD

**Issue by shoe-diamente** [dotnet/core#3576]
# Issue Title

Entity Framework SQL logs stop showing up in debug after I migrated from .NET Core 2.2 to .NET Core 3.0.

# General

By using this configuration:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}

```

in `appsettings.json` I was able to see logging informations about SQL queries made via Entity Framework.

Now, even with this configuration:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  }
}
```

I'm unable to see any logging regarding SQL queries made (but I see other debugging messages from .NET Core which suggests that the configurations are picked up correctly).

Did anything change with regards to logging that was not [documented here](https://docs.microsoft.com/it-it/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)?

**Comment by scalablecory** [comment]
This issue was moved to dotnet/wpf#2046
