### ISSUE TITLE
System.Componentmodel.IcollectionView not available for .net core 3.0

### ISSUE THREAD

**Issue by ebolefeysot** [dotnet/core#3578]
Despite what documentation on page https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.icollectionview?view=netcore-3.0 claims, this interface is not found in the nuget package for .net core 3.0.

Microsoft.Windows.SDK.Contracts offers an ICollectionView interface on .net core, but unfortunatly, it is not complete: Filter and refresh are not implemented.

Sample to compile:
```
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            ICollectionView v =new CollectionViewSource().View;
            v.Filter = null;
            v.Refresh();
        }
    }
```

**Comment by scalablecory** [comment]
This issue was moved to dotnet/wpf#2045
