### ISSUE TITLE
asp.net core cannot installer an windows server 2008?

### ISSUE THREAD

**Issue by lfkitty** [dotnet/core#3579]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Correct. The [minimum supported version](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md) is 2012 R2.
