### ISSUE TITLE
dotnet nuget push with disabled buffering cannot upload to Azure DevOps

### ISSUE THREAD

**Issue by danm-de** [dotnet/core#3582]
# Issue Title

`dotnet nuget push --disable-buffering` does not work with *Azure DevOps NuGet Feed* + Integrated Windows Authentication

# General
.Net Core 3.0 SDK (3.0.100)
dotnet tool version 3.0.100
Azure DevOps Server 2019.0.1 Patch 3

When adding the `--disable-buffering` option I cannot not push/upload NuGet packages using *Integrated Windows Authentication*. I receive the following error message:

```
C:\Program Files\dotnet\dotnet.EXE" nuget push "package.1.0.0.nupkg" --disable-buffering --api-key AzureDevOps --source MyCompanyAzureDevOps
No API Key was provided and no API Key could be found for 'https://server/nuget/v2/'. To save an API Key for a source use the 'setApiKey' command.
Pushing package.1.0.0.nupkg to 'https://server/nuget/v2/'...
PUT https://server/nuget/v2/
BadRequest https://server/nuget/v2/
Response status code does not indicate success: 400 (Bad Request - Die Anforderung an den Server enthielt keinen X-NuGet-ApiKey-Header, dieser ist aber selbst dann erforderlich, wenn Anmeldeinformationen angegeben wurde. Legen Sie diesen bei Verwendung von "NuGet.exe" mit der Option "-ApiKey" auf einen beliebigen Wert fest, z. B. "-ApiKey AzureDevOps". (DevOps-Aktivitäts-ID: 37BCF211-00B0-4E0F-AC94-41C731CCF59C)).
```

Without `--disable-buffering` everything works fine:
```
C:\Program Files\dotnet\dotnet.EXE" nuget push "package.1.0.0.nupkg" --disable-buffering --api-key AzureDevOps --source MyCompanyAzureDevOps
Pushing package.1.0.0.nupkg to 'https://server/nuget/v2/'...
PUT https://server/nuget/v2/
Accepted https://server/v2/
Your package was pushed.
```

**Comment by danm-de** [comment]
It seems that I am not the only one:

> Caution: when this option is used, integrated Windows authentication might not work.

Source:
http://www.nuke.build/api/Nuke.Common/Nuke.Common.Tools.NuGet.NuGetPushSettings.html#Nuke_Common_Tools_NuGet_NuGetPushSettings_DisableBuffering

**Comment by KoteshBoda** [comment]
@danm-de - This looks like a NuGet issue. Can you please move this over to nuget/home ?

**Comment by carlossanlop** [comment]
@rrelyea Is this something you can help with?

**Comment by mairaw** [comment]
@rrelyea friendly ping on this issue. Should we transfer this to dotnet/sdk or nuget/home?

**Comment by rrelyea** [comment]
Nuget/home for this and any nuget commands.
We own restore, pack and anything after “nuget”

**Comment by danm-de** [comment]
We switched from _Azure DevOp_ to another software months ago. Problem solved, thanks.
