### ISSUE TITLE
Cannot install .NET Core 3.0 on Amazon Linux AMI

### ISSUE THREAD

**Issue by hellowahab** [dotnet/core#3583]
# Cannot install .NET Core 3.0 on Amazon Linux AMI

Unable to install dotnet core 3.0 on Linux ARM. 

# General

Have tried following command:-

1. sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
2. sudo yum install dotnet-sdk-3.0

based on installation guide from Microsoft's below link for CentOS
https://dotnet.microsoft.com/download/linux-package-manager/centos7/sdk-current

Started receiving following error:-
Error: Package: dotnet-runtime-deps-3.0-3.0.0-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs

Tried installing openssl-libs as well but it states
No package opensll-libs available.

**Comment by hellowahab** [comment]
Tried installing the framework form tar found at the following location 
https://dotnet.microsoft.com/download/dotnet-core/3.0     (.NET Core Binaries:)

sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet-runtime-3.0.0-linux-x64.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin

It seems like working but let see if its the correct way of doing this.

**Comment by normj** [comment]
You mentioned this didn't work for Linux ARM but the steps you gave are for x86_64. I was able to follow your original instructions on a Amazon Linux AMI for x64 and .NET Core 3.0 ran successfully for me. I used ami id `ami-0ebbf2179e615c338` in `us-east-2`.  Could you share the ami id and region you used?

**Comment by hellowahab** [comment]
> You mentioned this didn't work for Linux ARM but the steps you gave are for x86_64. I was able to follow your original instructions on a Amazon Linux AMI for x64 and .NET Core 3.0 ran successfully for me. I used ami id `ami-0ebbf2179e615c338` in `us-east-2`. Could you share the ami id and region you used?

I have followed the below steps
1. dotnet publish -c release -r debian.9-x64  (Targetting Linux)
2. sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
3. sudo yum install dotnet-sdk-3.0
It gives me the error
**Error: Package: dotnet-runtime-deps-3.0-3.0.0-1.x86_64 (packages-microsoft-com-prod)**

Below are the Linux instance-related info

1. - NAME="Amazon Linux AMI"
2. - VERSION="2018.03"
3. - ID="amzn"
4. - ID_LIKE="rhel fedora"
5. - VERSION_ID="2018.03"
6. - PRETTY_NAME="Amazon Linux AMI 2018.03"
7. - ANSI_COLOR="0;33"
8. - CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
9. - HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by carlossanlop** [comment]
@dagood could you help with this?

**Comment by dagood** [comment]
There are a couple solutions already given in https://github.com/dotnet/core/issues/930, so I'm closing this issue, but to sum up:

One way to get it working is installing from the `tar.gz`, which is fine, although with our instructions the install goes under `~` with this method. The steps we have show up on the download page, e.g. https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-linux-x64-binaries

There is also a more direct solution to your original problem in that thread. Amazon Linux AMI is not a supported distro, so our RPM looks for dependencies with different package names than what Amazon Linux AMI provides. https://github.com/dotnet/core/issues/930#issuecomment-404296184 shows a way to bypass the dependency by making a fake package, then you can use the RPM package. (It's not important if the package is real, what matters is that openssl is present on your system.)
