### ISSUE TITLE
Update RHEL8 install guide noting 3.0 will be available starting in 8.1

### ISSUE THREAD

**Issue by jatin-cbs** [dotnet/core#3585]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel8/sdk-current
Operating System: Linux RHEL 8 - x64

The instructions are wrong as there is no dotnet 3.0 in the repository of RHEL 8 there is dotnet-sdk-2.1.x86_64 and dotnet-sdk-2.1.5xx.x86_64  only these two versions in RHEL 8 repository please check..

**Comment by RheaAyase** [comment]
Duplicate of #3491

**Comment by RheaAyase** [comment]
If anything the documentation on the download page needs clarifying?

**Comment by carlossanlop** [comment]
@leecow is this your area of expertise?

**Comment by leecow** [comment]
Will get the site fixed up.

**Comment by mairaw** [comment]
Can this be closed @leecow?

**Comment by RheaAyase** [comment]
This topic in regards to .NET 5 should be discussed...

**Comment by mairaw** [comment]
Is this still an issue for .NET 5 or can this be closed? /cc @adegeo

**Comment by adegeo** [comment]
I think this can be closed.
