### ISSUE TITLE
Add project reference to Asp.Net Core project

### ISSUE THREAD

**Issue by alexiordan** [dotnet/core#359]
I have project Alfa: Asp.Net Core web app
Project Beta: Universal Windows Class Library

When I try to add a reference of project Beta in project Alfa I get the following error:
```
The following projects are not supported as references : 

  - project Beta has target frameworks that are incompatible with targets in current project Alfa:. 

Alfa:

	.NETCoreApp,Version=v1.0

Beta :

	.NETCore,Version=v5.0
```

I think it should be possible to do it.
What should I do?

**Comment by benaadams** [comment]
Try adding an `imports` section to project Alfa's project.json
```csharp
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
```

**Comment by Petermarcu** [comment]
As @benaadams suggested, you can try forcing it through an imports but Universal Windows Class Libraries are projects designed for Universal Windows Apps. Those project types aren't really designed to work together. Is the library needing to be for UWP apps or did you want a generally reusable library? If you wanted generally reusable, you want a .NET Standard Library or Portable Class library.
