### ISSUE TITLE
WPF Core Xaml Designer RTL layout and custom fonts bugs

### ISSUE THREAD

**Issue by mrNo0b** [dotnet/core#3597]
When I set **FlowDirection="RightToLeft"** in MainWindow in WPF Core 3 app and when I add controls to the MainWindow they shows up in their correct locations in Designer but when I want to click on them to select, the selection highlight is in the opposite side of the window
`VS 2019 16.3.4`

![designerIssue](https://user-images.githubusercontent.com/12209347/65650408-5f564300-e013-11e9-9744-85ecd26f1a60.png)

Another issue that I have is that the designer don't support custom fonts, I added FontAwsome 
(_Font Awesome 5 Free-Solid-900.otf_) to my project and I use it in TextBlock for example:
`<TextBlock Text="&#xF0C7;" FontSize="16" Foreground="White"/>`
when I run the app I can see the fonts but in Designer I can only see empty character boxes

![bug2](https://user-images.githubusercontent.com/12209347/66603280-8769a880-ebb4-11e9-8304-e244491b88c1.png)

**Comment by scalablecory** [comment]
This issue was moved to dotnet/wpf#2044
