### ISSUE TITLE
.Net Core SDK install problem

### ISSUE THREAD

**Issue by Lillian-Wangs** [dotnet/core#3600]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
You will need to give some additional info for us to be able to help. Is there an instruction you don't understand, or a console command that is not working? Thanks.

**Comment by Lillian-Wangs** [comment]
Thank you for your reply.I have solved the problem.



---Original---
