### ISSUE TITLE
Unable to install .net framework 3.5 on Windows 10 Pro

### ISSUE THREAD

**Issue by martinsergio** [dotnet/core#3605]
I ran into an isue that don´t know how to fix. I can not install dotnet 3.5 framwwork on a PC running Windows 10 Pro v-1809 by any means.
When try with the MS Installer this is what I get. 
![dotnet error](https://user-images.githubusercontent.com/52013033/66658702-63d84980-ec18-11e9-9ba6-e553eebe1815.JPG)
Couldn't get it done with DISM either

**Comment by martinsergio** [comment]
Sorry.. Message is in spanish :P 
 
"El ensamblado referido no está instalado en su sistema." means "The referred assambled is not installed on your system,"

**Comment by scalablecory** [comment]
To install .NET 3.5 on Windows 10, you need to use the Add/Remove Control Panel for Windows features. It looks like this:
![image](https://user-images.githubusercontent.com/4665835/66683930-980a3500-ec2d-11e9-90a6-6762a260be47.png)

This repo is for .NET Core support. For .NET Framework, there is an [MSDN forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=netfxsetup) that you will be able to get better help at if the above doesn't work. Thanks.
