### ISSUE TITLE
Microsoft.NETCore.App 1.1.0-* do not match 1.1.0-preview1-001100-00????

### ISSUE THREAD

**Issue by laoshancun** [dotnet/core#361]
hi,
i have upgrade my sdk to 1.1.0-preview1-001100-00,
and change project.json to 1.1.0-*,when i run it ,the following error was thrown!
## project.json
```
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0-*"
          //"version": "1.0.1"
        }
```
## error info
```
The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.

  - Check application dependencies and target a framework version installed at:

      C:\Program Files\dotnet\shared\Microsoft.NETCore.App

  - The following versions are installed:

      1.0.1

      1.1.0-preview1-001100-00

  - Alternatively, install the framework version '1.1.0'.

```

**Comment by Petermarcu** [comment]
It looks like you have a preview of 1.1.0 installed but you are actually building against 1.1.0 without a pre-release. Is there a reason you are trying to specify a *? Are you still having trouble? 

@schellap, do you agree with my suspicion?

**Comment by Petermarcu** [comment]
I'm going to close this now. Please try the fully released tools at http://dot.net if you are still having trouble.
