### ISSUE TITLE
after install .net core ,error msg:api-ms-win-crt-runtime-l1-1-0.dll is missing

### ISSUE THREAD

**Issue by shenganjie** [dotnet/core#3610]
after install .net core ,run command dotnet has a error msg---"api-ms-win-crt-runtime-l1-1-0.dll is missing"

**Comment by dagood** [comment]
This means you're missing required updates (prerequisites to run .NET Core), take a look at https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies.

**Comment by dagood** [comment]
Duplicate of #2541
