### ISSUE TITLE
After install dotnet core 3.0 and I run dotnet it show error

### ISSUE THREAD

**Issue by nguyenthequyen** [dotnet/core#3611]
Command 'dotnet' not found, but can be installed with:

sudo snap install dotnet-sdk

**Comment by scalablecory** [comment]
Can you please give some detail on how you installed it?

**Comment by leecow** [comment]
When you install using a Snap, the default namespace established by the Snap system is `dotnet-sdk`. So, the command will be `dotnet-sdk.dotnet`. This can be aliased to just `dotnet`. See the [3.0 download docs](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0-download.md#install-using-snap) for details.
