### ISSUE TITLE
Receive an error message similar to Unable to locate package dotnet-sdk-3.0

### ISSUE THREAD

**Issue by xshone** [dotnet/core#3614]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-3.0.100
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Can't install dotnet-sdk-3.0 after using all methods provided in the page.

Error Message:
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by dagood** [comment]
I'm not able to reproduce the issue in a clean Docker container. Can you run these diagnosis steps and share the results?

```sh
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
```

**Comment by leecow** [comment]
Closing due to thread inactivity. Please re-open with additional info if you're still having troubles.
