### ISSUE TITLE
Does this support MacOs Catalina?

### ISSUE THREAD

**Issue by swapnild2111** [dotnet/core#3616]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I have lates MacOS - Catalina. Installed dotnet core as per documentation and still do not see `dotnet` command. I need to use `azcopy` command which required this .net core.

Could you please help?

**Comment by scalablecory** [comment]
It should work. Can you add step-by-step details on how you're installing it?

**Comment by dagood** [comment]
If you have a customized bash profile or similar script, you may be hitting https://github.com/dotnet/core-setup/issues/6521. In that case you can fix the profile script or get `/usr/local/share/dotnet/dotnet` into `PATH` manually.

**Comment by swapnild2111** [comment]
Exactly, I have customized `.zshrc` and after adding path it worked.
`export PATH=$PATH:/usr/local/share/dotnet`
