### ISSUE TITLE
can not install on Centos 7 sudo yum install aspnetcore-runtime-3.0

### ISSUE THREAD

**Issue by trogalko** [dotnet/core#3623]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos7/runtime-3.0.0
Operating System: Linux CentOS 7 - x64

This command also failed :
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
so, I resolved it by download the rpm file using wget, then install using rpm -Uvh packages-microsoft-prod.rpm

The second command : 
sudo yum install aspnetcore-runtime-3.0
failed completely, with below error message.

Here is the error message :
One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64

**Comment by WSLUser** [comment]
3 isn't in the 7 repos, only 2. http://mirror.centos.org/centos-7/7/dotnet/x86_64/Packages/

**Comment by omajid** [comment]
FWIW, there are two separate repositories that contain .NET Core RPMs for CentOS.

1. There's the Microsoft repository, where Microsoft builds and publishes packages for .NET Core on CentOS:  https://packages.microsoft.com/config/centos/7/

2. There's the CentOS repository, which contains rebuilds of the .NET Core packages originally built by Red Hat for RHEL: http://mirror.centos.org/centos-7/7/dotnet/x86_64/Packages/

They contain a different set of packages (eg CentOS repos don't have 3.0 yet), are built by different folks (CentOS vs Microsoft) and have a different update cadence.

**Comment by WSLUser** [comment]
sounds like Red Hat and Microsoft need to collab on package management like they do for cloud.

**Comment by trogalko** [comment]
Thanks for the info, so I just stick with .NET Core 2 for a while
