### ISSUE TITLE
Hello world did not run

### ISSUE THREAD

**Issue by kargirwar** [dotnet/core#3626]
![Screen Shot 2019-10-15 at 8 52 31 PM](https://user-images.githubusercontent.com/33156462/66845542-ce2d1900-ef8d-11e9-86cb-be6853c05fe2.png)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
.NET Core 3.0 requires Mac OS 10.13+, which from what I can tell is the version that first introduced the `utimenstat` function. Can you confirm which OS X version you're on?

CC @aik-jahoda

**Comment by aik-jahoda** [comment]
Can you provide `dotnet --info` command output?

I tested hello word on macOS 10.14 Mojave recently and it worked just fine.

**Comment by aik-jahoda** [comment]
Closing due to lack of information. Please re-open if you're still having a problem and have more info.
