### ISSUE TITLE
Error on typing dotnet in command prompt

### ISSUE THREAD

**Issue by deepakdalal315** [dotnet/core#3627]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

'dotnet' is not recognized as an internal or external command error

**Comment by scalablecory** [comment]
Have you tried opening a new command prompt window? The installer updates your PATH envvar, and command prompts don't see updates without restarting.

**Comment by scalablecory** [comment]
Closing out; please feel free to re-open if you're still seeing this issue and can provide more information.
