### ISSUE TITLE
Sample projects no longer build

### ISSUE THREAD

**Issue by cydhaselton** [dotnet/core#363]
The sample projects under samples/ no longer build according to the posted instructions.

`dotnet build` in samples/helloworld (or other directories) produces an error

`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or  solution file.`

There are no additional instructions on creating a project file.  Running `dotnet new` throws an error:

`Creating new C# project failed, directory already contains Program.cs`

**Comment by svick** [comment]
The sample projects use project.json. It looks like you're on SDK preview3 (or newer), which switched to msbuild. To build and run those projects with your version of the SDK, you first need to run `dotnet migrate`.

The instructions could probably mention this.

**Comment by cydhaselton** [comment]
Thanks for the info; I'll add the instruction when I'm in the office next

**Comment by Petermarcu** [comment]
I just submitted a PR that will enable both project.json and msbuild tooling to build the samples. https://github.com/dotnet/core/pull/417 . For the transition period that should help and then we can delete the project.json's when the time is right.

**Comment by Petermarcu** [comment]
I think this was fixed.
