### ISSUE TITLE
releases-index.json only contains 3.1 preview release

### ISSUE THREAD

**Issue by splatteredbits** [dotnet/core#3636]
It looks like the https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json file no longer contains all the .NET core releases. It only contains 3.1. I expect that it would be a copy of what's in the master branch (https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json).

We have a tool in our build pipeline that automatically downloads the right version of .NET Core for developers. That tool is now broken so our builds are broken.

**Comment by dleeapho** [comment]
PTAL @leecow

**Comment by leecow** [comment]
Yikes, sorry about that! Fixed.
