### ISSUE TITLE
netcore 3.1 preview 1 components namespace unknown

### ISSUE THREAD

**Issue by niconico49** [dotnet/core#3641]
# Issue Title
netcore 3.1 preview 1 components namespace unknown
Be as descriptive as you can with your title.

# General
After  update the visual studio 16.4.0 preview 2 that automatically installed
netcore 3.1 preview1 

every reference to the component razor are missed

I'll try to explain:
before if a components razor used another components razor, was only necessary using
the right namespace linked to the folder of the nested components

example: 
ComponetA is inside ProjectName/Components/FolderA
ComponetB is inside ProjectName/Components/FolderB

and in the ComponentA.razor
was only necessary to do:
@using ProjectName.Components.FolderB
<ComponentB></ComponentB>
or 
<ProjectName.Components.FolderB.ComponentB></ProjectName.Components.FolderB.ComponentB>

because the visual studio / intellisense and others was able to match the namespace with the folder automatically
Now, for every components there is an error like 
ProjectName.Components.FolderB namespace unknown ==> have you forgot some assembly reference and similar.

The solution (for now) is declare inside the every components the namespace too

Is a new request for the 3.1 preview 1 or is a bug?

and in that case, why disable the namespace and folder understating by the runtime / intellisense and other?

**Comment by scalablecory** [comment]
Can you zip up and attach a project that demonstrates this? It's a little hard to understand what's going on.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#15069
