### ISSUE TITLE
IApplicationBuilder missing

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/core#3642]
Hi, I'm trying to migrate a SignalR SDK i have made for 2.2 to 3.0.
It was netstandard 2.0 but it seems SignalR is now part of core so I changed from netstandard2.0 to etcoreapp3.0

One of the problems is that it cant find `IApplicationBuilder` resharper wants to install Microsoft.AspNetCore.Http.Abstractions 2.2 to solve it. But Microsoft.AspNetCore.Http.Abstractions is listed as deprecated. How should I solve this?

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#15067
