### ISSUE TITLE
its not allowing me to download

### ISSUE THREAD

**Issue by OltaPolta86** [dotnet/core#3643]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
The download works fine for me, can you provide more details?

**Comment by leecow** [comment]
Closing due to thread going quiet. If you're still having trouble, please re-open with additional information.
