### ISSUE TITLE
.Net Core Task failed to download version 3

### ISSUE THREAD

**Issue by nmiller45** [dotnet/core#3644]
.Net Core Task failed to download version 3

Using the "Use .Net Core" to build my application in Azure DevOps I had been passing in the parameter of 3.x and it has been downing the SDK (with runtime) just fine. Then today it was failing and telling me that no version 3 could be found. But when I changed it to 3.0.100 it worked. What changed? I liked just getting the latest version with 3.x.

**Comment by leecow** [comment]
I'm glad you hit upon the workaround (setting the version to 3.0.100). The team that owns that task is in the process of updating it to support 3.0 and newer Core versions more cleanly.

https://github.com/microsoft/azure-pipelines-tasks/issues/11100#issuecomment-535125307
