### ISSUE TITLE
Windows Forms default font is different between .Net Core and .Net Framework.

### ISSUE THREAD

**Issue by Lily721** [dotnet/core#3649]
See the attached sample code, we got two buttons with same size, but there's slightly differences between their font, see my attached snapshot.

My environment:
Win10 64-bit
.Net Core 3.0.1

If you try this two samples under a Win7 32-bit machine, there will be a big difference between them.

This issue will cause a big problem for our product, for example, the text will extends or can not show completely with original control size if users migrate from .Net Framework to .Net Core.

[WinFormApps.zip](https://github.com/dotnet/core/files/3737641/WinFormApps.zip)
![snapshot](https://user-images.githubusercontent.com/33749874/66982677-3fcdaa00-f0e9-11e9-8e0d-75bd415017b3.png)
![snapshot-win7](https://user-images.githubusercontent.com/33749874/66982687-465c2180-f0e9-11e9-92e9-b8a1d6e289c7.png)

**Comment by scalablecory** [comment]
This issue was moved to dotnet/wpf#2058

**Comment by weltkante** [comment]
@scalablecory this belongs to WinForms not WPF I believe?
