### ISSUE TITLE
Ran into a dotnet runn issue 

### ISSUE THREAD

**Issue by RoyalNW1** [dotnet/core#3653]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows 10

C:\Users\User\myWebApp>dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\User\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {d8c5b58f-aa0c-4738-8060-3fef9dd56d10} with creation date 2019-10-17 19:58:39Z, activation date 2019-10-17 19:58:38Z, and expiration date 2020-01-15 19:58:38Z.
info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
      Writing data to file 'C:\Users\User\AppData\Local\ASP.NET\DataProtection-Keys\key-d8c5b58f-aa0c-4738-8060-3fef9dd56d10.xml'.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\User\myWebApp

and it just hung there at the command prompt.

**Comment by scalablecory** [comment]
That's the behavior to expect from an ASP.NET Core app in console. You can go to the URL it printed to view the website from that point. You should see additional info print to console as you access the URL.

**Comment by scalablecory** [comment]
Closing this; please feel free to re-open if you think there's more going on here and can give more detail!
