### ISSUE TITLE
error on running dotnet run on command prompt

### ISSUE THREAD

**Issue by vishi06** [dotnet/core#3659]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

my system have 64-bit architecture os and after typing dotnet run on commant prompt an error is occured i.e Found .NET Core SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\3.0.100\dotnet.dll]

**Comment by scalablecory** [comment]
When you run `dotnet --list-runtimes`, what do you see?

**Comment by scalablecory** [comment]
Closing; please re-open with more detail if you're still having this issue.
