### ISSUE TITLE
dotnet test Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, Publ icKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by wvandeneede** [dotnet/core#366]
Hi,

When trying to add and launch a test project to my helloworld.api project under https://github.com/wvandeneede/playground.dotnetcore i am getting the following error:

`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, Publ
icKeyToken=adb9793829ddae60'. Le fichier spécifié est introuvable.
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.`

Creating a seperate test project (dotnet new -t xunittest) seems to work, only not when combined with an api-project it seems.

steps to reproduce:
+ clone https://github.com/wvandeneede/playground.dotnetcore
+ cd into helloworld.api/helloworld.api.service
+ dotnet restore
+ cd into helloworld.api/helloworld.api.test
+ dotnet restore
+ dotnet test 

dotnet --version: 1.0.0-preview2-1-003177

**Comment by justdmitry** [comment]
Workaround: add `Microsoft.DotNet.InternalAbstractions` to test dependencies manually (https://github.com/xunit/xunit/issues/1015)

**Comment by wvandeneede** [comment]
Updated as suggested, works now
