### ISSUE TITLE
i am not able to run dotnetcore on my mac 

### ISSUE THREAD

**Issue by mustafashakeel** [dotnet/core#3660]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
There's nothing actionable here; do you have more details we could look at?

**Comment by scalablecory** [comment]
Closing this; please feel free to re-open if you're still having an issue and can give detail.
