### ISSUE TITLE
Problem installing .net core on ubuntu 16.04

### ISSUE THREAD

**Issue by konstantinosDMS** [dotnet/core#3661]
Hi I tried to install .NET CORE 2.2 runtime on an Ubuntu 16.04 x32 (i686)machine but I am not able.I already have apache2 installed and I need to run .NET CORE Web Applications on it for publishing. Could you please suggest me what to do?

**Comment by scalablecory** [comment]
Please give us some details. How are you trying to install .NET Core 2.2, and what isn't working when you try it?

**Comment by leecow** [comment]
The [getting started ASP.NET Core tutorial](https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/intro) may give you some ideas.

**Comment by scalablecory** [comment]
Closing out, please re-open with some more detail if you still need help.
