### ISSUE TITLE
Freezing in CMD without starting browser

### ISSUE THREAD

**Issue by QVMaster** [dotnet/core#3662]
The problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Asp.net core tutorial web app just freezing in CMD without starting the browser.

**Comment by scalablecory** [comment]
It's not intended to launch a browser. You'll need to visit the URL printed to console in the browser of your choice, and you should see additional information printed to console when you do so.

**Comment by QVMaster** [comment]
Thanks man :)
