### ISSUE TITLE
dpkg: error: cannot access archive 'packages-microsoft-prod.deb': No such file or directory

### ISSUE THREAD

**Issue by arniwesth** [dotnet/core#3671]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current

Operating System: Linux Mint 19.2 (Linux Ubuntu 18.04) - x64

wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

results in

packages-microsoft-prod.deb: No such file or directory

The suggested alternatives result in similar errors. 

However, the package is downloadable from https://packages.microsoft.com/config/ubuntu/18.04 using eg Chromium.

**Comment by dagood** [comment]
> Lunix Mint 19.2

Just to make sure, this is meant to be `Linux Mint 19.2`, right? (Just in case it's actually a new distro. 🙂)

I found https://stackoverflow.com/a/31706461, which suggests that error from `wget` may mean your directory isn't writable.

Something like: your browser is able to download it into your user downloads folder fine, but your terminal's current directory is somewhere you can't write to and you need to `cd` to a writable location.

**Comment by arniwesth** [comment]
You're correct - got confused by the err message. I'm closing this.

**Comment by dagood** [comment]
Yeah, it had me scratching my head for a while until I stumbled upon the right search terms to get that particular q&a. Thanks for confirming.
