### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Eman929** [dotnet/core#3673]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Greetings,

I have this error you can see it in the screenshot that I will attach.
![Screenshot_1](https://user-images.githubusercontent.com/55553318/67235743-03cb7980-f448-11e9-888a-ddf87799a41f.png)

Sincere regards.

**Comment by dagood** [comment]
Have you tried going to the link and making sure your computer is up to date with the requirements? https://go.microsoft.com/fwlink/?linkid=798306

**Comment by scalablecory** [comment]
Closing out, please re-open with some more detail if you still need help.

**Comment by Eman929** [comment]
Greetings,

I am so sorry I forgot to reply to this message.It is okey I do not need aditional help I have listened to your advice and solve the problem.Sorry for any typing mistakes this reply is sent from my phone.

Sincere regards.

Preuzmite Outlook za Android<https://aka.ms/ghei36>

________________________________
