### ISSUE TITLE
What's the support status of .Net Core 3.x  for win7 SP1(cli)?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/core#3675]
The same as https://github.com/dotnet/core/issues/3588#issuecomment-543935027

According to #3588, `Win2008R2 SP1` is no longer supported by .netcore 3.x, but what about the status of Win7 SP1(client)? I think they are almost the same(both NT6.1), and they also share the same RID `win7-x86`/`win7-x64`, but Win7 SP1(client) is still in the supported-os list.

Is it still in support or out of support?

***BTW:*** [3.1-supported-os.md](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md) should also be updated to match the changes in `3.0-supported-os.md`.

**Comment by GrabYourPitchforks** [comment]
@leecow Can you confirm that this is a typo?

Regardless, please be aware that Win7 SP1 (client) goes out of support on the same day: January 14, 2020 (see https://www.microsoft.com/windows7). It is critical that anybody still running Win7 have a plan for migrating off of it in the next 90 days.

**Comment by carlossanlop** [comment]
@leecow do you have an answer for this?

**Comment by carlossanlop** [comment]
Ping @leecow

**Comment by mairaw** [comment]
@jamshedd @leecow do we need to make any updates here?

**Comment by jamshedd** [comment]
No change is needed. Win7 SP1 continues to be supported for 3.1 until end of the ESU (Jan 2023).
