### ISSUE TITLE
Would be nice if the controls color theme would take over the theme from the windows settings

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/core#3676]
# Windows Settings for theme is not applied to controls on winforms elements

# General
One can go over the Windows.UI.ViewManagement.UISettings and apply the themes as development time however as we are starting a new implementation one could already take the theme from windows and apply this on the form, or have a property on the form class that states UseTheme so if the user has "Dark-Mode" then the form draws "Dark-Mode" for as much as that's possible in a non WPF app.

**Comment by scalablecory** [comment]
This issue was moved to dotnet/wpf#2082
