### ISSUE TITLE
Unable to resolve libraries for '.NETCoreApp,Version=v3.0' in windows 10

### ISSUE THREAD

**Issue by anandbarthwal** [dotnet/core#3678]
We have developed a console application with .net core 3.0 + visual studio code + windows 10. Application could not compile and give following error:

error NU1100: Unable to resolve 'Microsoft.Extensions.Hosting (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'.
error NU1100: Unable to resolve 'Microsoft.Extensions.Configuration (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'. 
error NU1100: Unable to resolve 'MailKit (>= 2.3.1.6)' for '.NETCoreApp,Version=v3.0'. 
error NU1100:Unable to resolve 'Microsoft.Extensions.Logging (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'.
error NU1100:Unable to resolve 'Microsoft.Extensions.Logging (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'
error NU1100:Unable to resolve 'Microsoft.Extensions.Configuration (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'
error NU1100: Unable to resolve 'Newtonsoft.Json (>= 12.0.2)' for '.NETCoreApp,Version=v3.0'
error NU1100:Unable to resolve 'System.Data.SqlClient (>= 4.7.0)' for '.NETCoreApp,Version=v3.0'
error NU1100:Unable to resolve 'Microsoft.Extensions.Logging.Abstractions (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'
error NU1100: Unable to resolve 'Microsoft.Extensions.Logging.Configuration (>= 3.0.0)' for '.NETCoreApp,Version=v3.0'

Even when we tried to install these libraries using command like 
dotnet add package Microsoft.Extensions.Logging.Abstractions --version 3.0.0, 
it gives message like "Package 'Microsoft.Extensions.Logging.Abstractions' is incompatible with 'all' frameworks in project".

We have repaired the .net core 3.0, so it works fine for few builds and again same problem starts occurring. Later on we have repaired and install/uninstall .net core 3.0
multiple times but does not work for us. 

We have urgent deliveries related to this, so please guide us for the solution of this problem ASAP.

**Comment by scalablecory** [comment]
We will probably need a sample app that shows this problem.

CC @rrelyea @livarcocc

**Comment by scalablecory** [comment]
Closing out due to lack of response; please re-open if you're still hitting this issue and can provide more detail.
