### ISSUE TITLE
.net install problem

### ISSUE THREAD

**Issue by juliatroescher** [dotnet/core#3679]
install web page local host not found

Be as descriptive as you can with your title.

when running code in terminal everything as it should be I think but then when browsing for localhost nothing can be found
I'm running it on macOS Mojave 10.14.6, .NET 3.0
<img width="904" alt="Screenshot 2019-10-22 at 23 37 49" src="https://user-images.githubusercontent.com/56897922/67340326-06e86780-f525-11e9-8bee-ffd86108aa15.png">
<img width="570" alt="Screenshot 2019-10-22 at 23 37 16" src="https://user-images.githubusercontent.com/56897922/67340327-06e86780-f525-11e9-8479-a16097ea8040.png">
<img width="569" alt="Screenshot 2019-10-22 at 23 36 42" src="https://user-images.githubusercontent.com/56897922/67340328-0780fe00-f525-11e9-98c8-5d95825fe3ea.png">
<img width="567" alt="Screenshot 2019-10-22 at 23 36 06" src="https://user-images.githubusercontent.com/56897922/67340329-0780fe00-f525-11e9-80ce-285d7fa57f7f.png">

**Comment by scalablecory** [comment]
I'm not familiar with Safari's UI, but are you going to http://localhost:5000? It looks like you might be missing the port.

**Comment by scalablecory** [comment]
I'm closing this out due to lack of response. Please feel free to reopen if you're still having an issue and can provide more detail. Thanks.
