### ISSUE TITLE
Help resolve starting the dotnet console issue

### ISSUE THREAD

**Issue by judeabolo** [dotnet/core#3681]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

After installing the dotnet-sdk-3.0.100-win-gs-x64.exe then i went to my command prompt and checked to be sure it installed properlu shich was ok the i issued the command

dotnet new console -o myApp

then i get an error message  failed to load the hostfxr.dll even though it was found but loading it failed

please help

**Comment by scalablecory** [comment]
@jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@judeabolo this sounds like you are trying to run a 32bit .NET Core application with only 64bit .NET Core installed.  The error message is not very helpful and we are aware of that.

Can you provide the exact step that failed and the output?

cc @vitek-karas

**Comment by scalablecory** [comment]
Closing out due to lack of response; please re-open if you're still hitting this issue and can provide more detail.
