### ISSUE TITLE
new insue

### ISSUE THREAD

**Issue by tppss** [dotnet/core#3684]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current?journey=vs-code
Operating System: Linux RHEL 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
You haven't provided any details. What can we help you with?

**Comment by scalablecory** [comment]
Closing out, please re-open with some more detail if you still need help.
