### ISSUE TITLE
Error Downloading on MacBook Pro

### ISSUE THREAD

**Issue by RobbyDoz** [dotnet/core#3685]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try to download the .NET SDK on my MacBook Pro, I get this error message when I try to open it in my downloads: "“dotnet-sdk-3.0.100-osx-gs-x64.pkg” can’t be opened because Apple cannot check it for malicious software."

I'm using macOS Catalina V10.15 on a Mid 2012 MacBook Pro.

**Comment by scalablecory** [comment]
Is there a connection issue, or do you need to enable some sort of developer mode? @aik-jahoda does this ring any bells to you?

**Comment by RobbyDoz** [comment]
There isn't a connection issue as its done downloading in my downloads directory, just when you try to open it, it gives that error message and you can't do anything.

**Comment by aik-jahoda** [comment]
Show the file in the Finder and open context menu by right click on the downloaded package. Then select `Open` and a similar dialog will appear however there will be `Open` button available. When you open it in this way it will execute the package.

It is caused by Apple security and it forces you to explicitly open the downloaded content. Additional details are on Apple web pages: https://support.apple.com/en-us/HT202491.

**Comment by aik-jahoda** [comment]
Closing due to no response. Please re-open if you're still having a problem.

**Comment by robcamer** [comment]
Additional detail---I found that you have to use Finder to open the Downloads folder, then right-click on the downloaded package, select "Open With" (not just "Open") and then select "Installer (default)" in order to get the "Open" button with the error message.

**Comment by richardtallent** [comment]
On Catalina, you have to try to run it, then go to the Security & Privacy panel in System Preferences and click "Open Anyway." The "Open" and "Open With" suggestions above aren't enough.
