### ISSUE TITLE
dotnet test (machine independent)?

### ISSUE THREAD

**Issue by saxenark** [dotnet/core#3688]
Hi,
I have a dotnet core 2.2 web application and it's test project using NUnit 3.0. I build & publish my project & test project in machine 1. I copy the entire project to another machine say machine2 but which has different directory structure and user profile.

My web app is not a self contained executable.

When I run "dotnet test", I am getting error like so:

C:\<blah>\<blah>\bin\Release\netcoreapp2.2\testhost.dll. Please publish your test project and retry."

I think the reason is that the shared .net core paths in .runtimeconfig.dev.json file, which refer to the path on machine1 and which does not exist on machine2. The reason is that the test dll is also not a self contained (instead is a framework dependent) dotnet core binary and hence the shared paths are important. Not sure.

Therefore, my questions are:

1. Can dotnet core test dlls be build on machine1 and run on machine2 in general? Is that a supported scenario?
2. What is .runtimeconfig.dev.json?
3. How can I specify to use .runtimeconfig.json instead of .runtimeconfig.dev.son?
4. Suppose, I build on machine1 in a folder structure on D:\ and then try to run the tests+code coverage on machine2 in a folder structure on C:\. Wouldn't the coverage have issues as the pdbs would be referring to path on D:\?

Thanks.

**Comment by saxenark** [comment]
One possibility *may be* is to specify the runtimeconfig through the --runtimeconfig argument to dotnet. But I can't find out a documentation on how to use this command.

**Comment by scalablecory** [comment]
@livarcocc

**Comment by scalablecory** [comment]
Can you try this again with .NET Core 3.x or a .NET 5 preview? A lot of change has happened here. Thanks.

**Comment by mairaw** [comment]
@saxenark we'd need you to try this on a more recent version.
