### ISSUE TITLE
Unable to reference .NET Standard project from an UWP project

### ISSUE THREAD

**Issue by psoszynski** [dotnet/core#369]
1. Visual Studio 2017RC (fresh install)
2. New Project -> Universal Windows ('App1')
    References: a) Microsoft.NETCore.UniversalWindowsPlatform, b) Universal Windows
3. Add Project -> .NET Core -> Class Library (.NET Standard) ('Class Library1')
   References: a) Microsoft.NET.Sdk (1.0.0-alpha-20161104-2, b) NETStandard.Library (1.6.0)
4. Trying to add a project reference from 'App1' to 'Class Library1'
5. Error: "Unable to add a reference to project 'Class Library1'"

Any ideas?

**Comment by dsplaisted** [comment]
Thanks for reporting this issue.  Can you move it to https://github.com/dotnet/roslyn-project-system?

(The bug is probably in code that's internal to Visual Studio and not actually in that repo, but it's close enough.)

**Comment by psoszynski** [comment]
Ok, I will do it.

**Comment by dsplaisted** [comment]
Moved to dotnet/roslyn-project-system#818

**Comment by blackcid** [comment]
Year 2018. Same issue is still happening
