### ISSUE TITLE
.Net Core 3.0 WebApi Reports Error When Return OK(List<dynamic>)

### ISSUE THREAD

**Issue by carroty3334** [dotnet/core#3691]
When .net core 3.0 webapi returns Ok(List< dynamic >) or Ok(List< object >), this error occurs:
System.InvalidCastException: Unable to cast object of type '< GetEnumerator >d__9' to type 'System.Collections.IDictionaryEnumerator'.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#16610
