### ISSUE TITLE
Manifest entry requestedExecutionLevel ignored on Linux

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/core#3699]
# Issue Title

Manifest entry requestedExecutionLevel ignored on Linux

# General
I created a small console app with a manifest including:
``` XML
<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
```
It runs the code:
``` C#
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine($"Admin? {RunningAsAdmin()}");
        Console.ReadKey();
    }

    [DllImport("libc")]
    public static extern uint getuid();

    static bool RunningAsAdmin()
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            using var identity = WindowsIdentity.GetCurrent();
            WindowsPrincipal principal = new WindowsPrincipal(identity);
            return principal.IsInRole(WindowsBuiltInRole.Administrator);
        }
        else return getuid() == 0;
    }
}
```
On Windows, the app requests UAC and outputs `Admin? True`. On Linux, it outputs `Admin? False`. If I run the command with `sudo`, it outputs `Admin? True`.

Is that manifest element intended to be supported on non-Windows operating systems?

**Comment by scalablecory** [comment]
Manifest files to my knowledge are entirely a Windows feature; I don't know if we have anything in .NET to support them on other OSes.

@jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
That is correct, the Windows Manifest (https://docs.microsoft.com/en-us/windows/win32/secauthz/administrator-broker-model) is a windows concept.  Adding @lpereira  who may have thoughts on how to do this x-plat.

**Comment by lpereira** [comment]
> That is correct, the Windows Manifest ([docs.microsoft.com/en-us/windows/win32/secauthz/administrator-broker-model](https://docs.microsoft.com/en-us/windows/win32/secauthz/administrator-broker-model)) is a windows concept. Adding @lpereira who may have thoughts on how to do this x-plat.

If you want to check if the process is already running as superuser, then checking the output of `getuid()` and comparing it with `0` is pretty much the most common way of accomplishing this.

If you'd like to have something similar to the Windows UAC to raise the privileges, then there's no one single way of doing this that's cross-plat in the Unix side of the pond.  One somewhat popular way is using [Polkit](https://en.wikipedia.org/wiki/Polkit), which might trigger a UI prompt or use some other mechanism; but IIRC that's not really used outside Linux, and even then, it's not guaranteed it's going to be there.

**Comment by omajid** [comment]
> One somewhat popular way is using Polkit, which might trigger a UI prompt or use some other mechanism; but IIRC that's not really used outside Linux, and even then, it's not guaranteed it's going to be there.

Additionally, I dont think Polkit solves the problem being discussed here of elevating the application itself. As I understand it, Polkit lets unprivileged applications talk to privileged applications (through regular IPC) and handle the actual authentication/authorization checks. But both the unprivileged applications and privileged applications must already be running with the correct permissions.

Some more details here: https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

**Comment by scalablecory** [comment]
@ericjohannsen it sounds like we've got an answer here, so I'm closing the issue out. Please reopen if you think there's more to discuss.
