### ISSUE TITLE
SelectMany in LINQ

### ISSUE THREAD

**Issue by RassulYunussov** [dotnet/core#370]
Error in executing the SelectMany query in both forms - Methods Extension and LINQ.
NetFramework 4.5 doesn't have such error. Mono has this error also.
The following code produces the output of:

Group A 1 John Smith
Group A 2 Michael Jordan
Group A 3 Bruce Lee
Group A 1 Askar Akber
Group A 2 Tamerlan James
Group A 3 Viktor Kopernik
Group A 1 John Smith
Group A 2 Michael Jordan
Group A 3 Bruce Lee
Group A 1 Askar Akber
Group A 2 Tamerlan James
Group A 3 Viktor Kopernik

But should Be (and NetFramework actually produces the desired output):

Group A 1 John Smith
Group A 2 Michael Jordan
Group A 3 Bruce Lee
Group B 1 Askar Akber
Group B 2 Tamerlan James
Group B 3 Viktor Kopernik
Group A 1 John Smith
Group A 2 Michael Jordan
Group A 3 Bruce Lee
Group B 1 Askar Akber
Group B 2 Tamerlan James
Group B 3 Viktor Kopernik

Code:
`
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApplication
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public override string ToString()
        {
            return $"{Id} {Name}";
        }
    }
    public class Group 
    {
        public List<Student> students = new List<Student>();
        public string Name { get; set; }
    }
    public class Program
    {
        public static void Main(string[] args)
        {
            Group g= new Group(){Name = "Group A"};
            g.students.Add(new Student(){Id=1,Name="John Smith"});
            g.students.Add(new Student(){Id=2,Name="Michael Jordan"});
            g.students.Add(new Student(){Id=3,Name="Bruce Lee"});

            Group g2= new Group(){Name = "Group B"};
            g.students.Add(new Student(){Id=1,Name="Askar Akber"});
            g.students.Add(new Student(){Id=2,Name="Tamerlan James"});
            g.students.Add(new Student(){Id=3,Name="Viktor Kopernik"});

            List<Group> groups= new List<Group>();
            groups.Add(g);
            groups.Add(g2);

             var sm = groups.SelectMany(gg=>gg.students,(ggs,student)=>new {ggs.Name,student});

             var smLinq = from gg in groups
                            from st in gg.students
                             select new {gg.Name,st};
             
             foreach(var s in sm)
                System.Console.WriteLine(s.Name +" "+s.student);

            foreach(var s in smLinq)
                System.Console.WriteLine(s.Name +" "+s.st);
            

          
        }
    }
}
`

**Comment by stephentoub** [comment]
@RassulYunussov, the repro you provided has a bug in it: the students you're intending to add to g2 are actually being added to g:
```C#
        Group g2= new Group(){Name = "Group B"};
        g.students.Add(new Student(){Id=1,Name="Askar Akber"});
        g.students.Add(new Student(){Id=2,Name="Tamerlan James"});
        g.students.Add(new Student(){Id=3,Name="Viktor Kopernik"});
```
When I fix that, I see the expected output on both .NET Framework and .NET Core.

**Comment by RassulYunussov** [comment]
Dear Stephen,
Shame on me, my mistake! So sorry!

**Comment by stephentoub** [comment]
No problem :smile:
