### ISSUE TITLE
error : Unable to load the service index for source https://api.nuget.org/v3/index.json.

### ISSUE THREAD

**Issue by Meai1** [dotnet/core#3701]
```
pc@debian:~/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder$ dotnet build ./FlightFinder.sln
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/pc/workarea/software/dotnet/sdk/3.0.100/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/home/pc/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.sln]
/home/pc/workarea/software/dotnet/sdk/3.0.100/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/home/pc/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.sln]
/home/pc/workarea/software/dotnet/sdk/3.0.100/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/home/pc/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.sln]

Build FAILED.

```

Btw this happens for every project, I just used the sample project for illustration. And for some reason it works if I do the build via Jetbrains Rider IDE.
Before you point me to links like this: https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source ...
Please notice that I consider this a bug whether there is a manual workaround or not because I can access that given url in the browser perfectly fine. If it works from the browser, it has to work from inside dotnet executables too. This should not be up to me to solve.

**Comment by scalablecory** [comment]
This should be filed on the [Nuget repo](https://github.com/NuGet/NuGet.Client)

It sounds like this is a feature request (automatic proxy discovery on Linux) rather than a bug, yes?

CC @rrelyea

**Comment by Meai1** [comment]
@scalablecory absolutely not, it's 100% a bug. I am connected to the internet just fine, there is no reason whatsoever that nuget should be incapable of downloading things.

**Comment by scalablecory** [comment]
Are you using a proxy as the StackOverflow question suggests, or is this something else?

**Comment by rrelyea** [comment]
https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-not-accessible

**Comment by scalablecory** [comment]
This issue was moved to NuGet/Home#8805
