### ISSUE TITLE
install conflict Net core 2.0 vs 3.0

### ISSUE THREAD

**Issue by gnilsson2** [dotnet/core#3702]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux RHEL 7 - x64

Transaction check error:
  file /usr/share/bash-completion/completions/dotnet from install of rh-dotnet30-dotnet-host-3.0.0-3.el7.x86_64 conflicts with file from package rh-dotnet20-dotnet-sdk-2.0-2.0.3-4.el7.x86_64
 sudo scl enable rh-dotnet30 bash
Unable to open /etc/scl/conf/rh-dotnet30!
 cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)

**Comment by omajid** [comment]
Take a look at https://access.redhat.com/solutions/4537371 too for possible workarounds.

**Comment by leecow** [comment]
Closing as this is possibly mitigated using the Red Hat suggestions.
