### ISSUE TITLE
Example metadata file in tutorial needs clarification

### ISSUE THREAD

**Issue by anibalvelarde** [dotnet/core#3705]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The metadata file defined in [the example](https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file) points to dotnet core v2.2. I ran into issues because I was using dotnet v3.0.x.  My suggestion would be that you update the page with a note indicating that the user may need to update the metadata to target the dotnet SDK that they are using.

**Comment by scalablecory** [comment]
@shirhatti looks like we need to update this tutorial for 3.0

**Comment by mairaw** [comment]
It seems this has been resolved. I see the metadata on that page using 3.1 now.

**Comment by drumm227** [comment]
very good
