### ISSUE TITLE
Pointing browser to http://localhost:3000/weatherforecast needs clarification for Windows 7 users

### ISSUE THREAD

**Issue by anibalvelarde** [dotnet/core#3706]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows 7

It will probably be useful to have an additional note on the tutorial about the IP address that the docker machine is using.  I had to run the command:
`$ docker-machine ip default`
This command revealed the IP address that was actually being used for hosting the example WebAPI, `192.168.99.100`.

After knowing that IP address I was able to reach to my example docker-hosted Web API with:
`https://192.168.99.100:3000/weatherforecast`

[This resource](https://www.jhipster.tech/tips/020_tip_using_docker_containers_as_localhost_on_mac_and_windows.html) sorted out some of that info for me. Hope it may be useful for others.

**Comment by scalablecory** [comment]
@shirhatti this seems like good feedback.

**Comment by scalablecory** [comment]
@shirhatti any thoughts on this?

**Comment by mairaw** [comment]
Also pinging @nishanil

**Comment by nishanil** [comment]
Per system requirements stated on Docker website, it requires Windows 10. Ref: https://docs.docker.com/docker-for-windows/install/#system-requirements 

![image](https://user-images.githubusercontent.com/3107766/92127229-b87f4700-ee1e-11ea-9fa0-84b1bd0c0ac1.png)

**Comment by mairaw** [comment]
So we probably need to update our intro to add the Windows version required in the prereqs, right?

https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro

**Comment by laxmikanth-d** [comment]
I am still facing the issue.

**Comment by sughosneo** [comment]
Hi @laxmikanth-d, just checking if you are still facing this issue. If yes, could you please share some more details? Thank you.

**Comment by wfurt** [comment]
Support for Windows 7 ended. I'm wondering if we can just add vague note about supported OS @mairaw. Adding and maintaining full list seems excessive.
