### ISSUE TITLE
Unable to create docker image getting below error

### ISSUE THREAD

**Issue by ChandraSiddamreddy** [dotnet/core#3708]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/57074578/67640895-5931db80-f8cb-11e9-9679-5763dfc05318.png)

D:\MicroServices\workdir\myMicroservice>docker build -t mymicroservice .
Sending build context to Docker daemon  15.36kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
2.2: Pulling from dotnet/core/sdk
9ff41eda0887: Pull complete
eba129c33046: Pull complete
a4c0d2f2580a: Pull complete
791b5d8fed81: Pull complete
56dd617621f8: Pull complete
04880854cb22: Pull complete
bcfd153f4c39: Pull complete
Digest: sha256:e23ba80a63c11e9a99e577761c330c76f25abbd1b7280dd754b7e59cddc3cfa3
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:2.2
 ---> 3e706675d42e
Step 2/10 : WORKDIR /src
 ---> Running in 6f5b3153ccd4
Removing intermediate container 6f5b3153ccd4
 ---> 581f3fffb177
Step 3/10 : COPY myMicroservice.csproj .
 ---> 701c018e1625
Step 4/10 : RUN dotnet restore
 ---> Running in ce1a076de2f3
hcsshim::CreateComputeSystem ce1a076de2f39747e0f496c74dc2e266ea7126f02f36ac67022c605925875f62: The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"Container","Name":"ce1a076de2f39747e0f496c74dc2e266ea7126f02f36ac67022c605925875f62","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\ce1a076de2f39747e0f496c74dc2e266ea7126f02f36ac67022c605925875f62","Layers":[{"ID":"c1148e68-2e16-58e2-a2d0-03bc992c726e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4955bf0763adf19ca1b00f18977709ed337379d1d9486bb772942a4b47569be8"},{"ID":"621a402b-f0a9-5f1f-9ad7-b3c78820eeb1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3213855f6d41042a4214bb8cdc81ac2bd7fee76742b936f24decada39df1e80b"},{"ID":"a245efd1-b0b2-57fb-8e73-4b14a329b0e9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\907ed77a07529790104352ae9fe2d626783b55e35bd52f5b827ba3b1a5e9c877"},{"ID":"a2897ebf-ef9e-59c8-9137-563df009e8d1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\76efb0eae1763061e8e7ac8a0f9e1e0d116a5a7c3eecec12ff5e2efcb8302599"},{"ID":"ca986a93-9a41-505c-96fe-e29c2df08f40","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3443589d41cb256b0286dc34776149c29154a42ae170a3105e533ef78ef12286"},{"ID":"c1084cd7-10a1-57ac-8b23-b8c8a25ff886","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0b5a7b66908e2d0d4b7fa6a392a2ed0b37e2dcd7c9a14b972590254fdfb8d079"},{"ID":"463a21b0-5b2f-56ce-bc1b-8c6c1168d4d9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f99ef7cb9f2e732a7fb2af277e864c07e9eb2d7274c875f2c5bd4c382c482f89"},{"ID":"6303711a-dbe8-59ae-8c9f-a9c8fc300137","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8e605726f76bbeb106e0f316c597a7218fb8f34eca917494f333124f2e6ee4fa"},{"ID":"f96d2e93-9c5f-561a-a35d-7c61a704bab1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3c9436796833a729e10a365422de2318cba2e1ae8386b18fc0bb2a5d0563ebd9"}],"HostName":"ce1a076de2f3","HvPartition":true,"EndpointList":["CD6D50EF-7599-4E94-81F4-1962664DEF15"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\3c9436796833a729e10a365422de2318cba2e1ae8386b18fc0bb2a5d0563ebd9\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})

**Comment by scalablecory** [comment]
@shirhatti any thoughts here?

**Comment by nishanil** [comment]
I'm not sure how to reproduce this error. 
@ChandraSiddamreddy Can you try the steps again and confirm if you're still facing this error with 3.1 SDK?

**Comment by shirhatti** [comment]
Spelunking through issues on the `moby` project, this seems to happen when you haven't enabled virtualization on your machine BIOS. If you continue to have problems, I'd recommend opening an issue on the https://github.com/moby/moby repo
