### ISSUE TITLE
could not run app in a container using the following command 

### ISSUE THREAD

**Issue by agbadamosi** [dotnet/core#3709]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\ahmed\myMicroservice>docker run -it --rm -p 3000:80 --name mymicroservicecontainer mymicroservice
Unable to find image 'mymicroservice:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:41765->192.168.65.1:53: i/o timeout.
See 'docker run --help'.

**Comment by scalablecory** [comment]
This might be a networking config issue based on that error response.

@shirhatti

**Comment by shirhatti** [comment]
Closing as this is external to .NET Core.

On a quick glance, it sounds like you may have a DNS issue in resolving docker.io. Do you have an antivirus/corporate proxy/restrictive ISP that's blocking your DNS?
