### ISSUE TITLE
kubectl apply -f deploy-myMicroservice.yaml unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1" unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Service" in version "v1"

### ISSUE THREAD

**Issue by ssamueluk** [dotnet/core#3711]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
@ssamueluk have you been able to figure this out? @shirhatti any ideas here?

**Comment by mairaw** [comment]
We did update that page yesterday and customers who where having issues reported that things are working now. I think we can close this one.
