### ISSUE TITLE
https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb not found

### ISSUE THREAD

**Issue by netroby** [dotnet/core#3713]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-10/sdk-current
Operating System: Linux Ubuntu 19.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
How did you get to that page, and what is it showing for you? I don't see a 19.10 entry in the dropdown, and the link just takes me to RHEL instructions (the default). We don't have a 19.10-specific package feed, as you can see by the 404.

(Keeping up better is tracked by https://github.com/dotnet/core/issues/2576.)

**Comment by netroby** [comment]
just guess the package name should exists. but it not.

**Comment by dagood** [comment]
For what it's worth, the 19.04 repository's packages work in 19.10 for me.

**Comment by pysiak** [comment]
Yeah, https://packages.microsoft.com/ubuntu/19.10/prod/pool/main/ doesn't have the packages just like 19.04 would under: https://packages.microsoft.com/ubuntu/19.04/prod/pool/main/

Should we be expected to install the 19.04 or wait for 19.10 or ...?

**Comment by dagood** [comment]
> Should we be expected to install the 19.04

It's definitely not ideal, but yes, in cases like this you need to use the "nearest" packages available (or an alternative install method like snaps or tar.gz), and they should work. Our plans to get better at having packages for each distro are at https://github.com/dotnet/core/issues/2576.

**Comment by scegg** [comment]
cannot use 19.04 package on 19.10.

apt update will report error:
Err:2 https://packages.microsoft.com/ubuntu/19.04/prod disco/main amd64 Packages
  File has unexpected size (23655 != 156065). Mirror sync in progress? [IP: 13.75.127.55 443]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000

**Comment by dagood** [comment]
@scegg That's caused by an outage tracked at https://github.com/dotnet/core/issues/3988, once that's fixed up it should work.
