### ISSUE TITLE
err 31 when installing .net for ubuntu 16.04 x64

### ISSUE THREAD

**Issue by geekToes** [dotnet/core#3715]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Operating System: Linux Ubuntu 16.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
This is the error that I suddenly get when trying to install .net on my ubuntu 16.0 X64:

```
Err:31 http://debian.neo4j.org/repo stable/ Release.gpg                        
  The following signatures were invalid: KEYEXPIRED 1572135620
Hit:32 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease 
Fetched 119 kB in 11s (10.4 kB/s)                                              
Reading package lists... Done
W: GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4773BD5E130D1D45
W: The repository 'http://repository.spotify.com stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://debian.neo4j.org/repo stable/ Release: The following signatures were invalid: KEYEXPIRED 1572135620
W: Failed to fetch http://debian.neo4j.org/repo/stable/Release.gpg  The following signatures were invalid: KEYEXPIRED 1572135620
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Please help me.
Thanks

**Comment by dagood** [comment]
It looks like your machine is in a bad state with these `http://debian.neo4j.org/repo` and `http://repository.spotify.com` repositories, unrelated to installing .NET Core. Which command ran into that issue, and what is the full output? Why do these errors seem to you to be connected to installing .NET Core?

What happens if you continue with the next steps in the instructions? They may work, because the warnings aren't related to our repository.

**Comment by leecow** [comment]
Closing due to stale thread and looks like the issue has to do with general machine confi and not .NET Core. If you're still having trouble after getting the machine cleaned up, please re-open with additional information.
