### ISSUE TITLE
VS16.3.7 - Cannot compile Core 2.2 MVC project with sdk 3.0.100

### ISSUE THREAD

**Issue by Darthruneis** [dotnet/core#3718]
In summary, I updated VS 2019 to the latest version, and it broke an existing project on .NET Core 2.2.

I loaded up an old project which I was going to start working on again. It was built on .NET Core 2.2 previously and worked fine last I ran it (months ago). I loaded VS2019 today and updated it to 16.3.7. This has included the 3.0.100 SDK for .NET Core.

The only error information I have found so far in the build output is the following:

> 0>Skipping target "CoreGenerateRazorTargetAssemblyInfo" because all output files are up-to-date with respect to the input files.
0>C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Compilation.targets(156,10): Error MSB4064: The "Nullable" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.
0>C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Compilation.targets(120,5): Error MSB4063: The "Csc" task could not be initialized with its input parameters. 
0>------- Finished building project: HireRight.Web.UI. Succeeded: False. Errors: 2. Warnings: 4
Build completed in 00:00:09.670

Using Windows 10 64-bit

This issue seems to be similar/related to #3212, which was closed and mentioned preview-8 of the SDK, but didn't seem to have a resolution.

I have tried setting the language version for all of my projects to 7.3 - the error persists.

**Comment by scalablecory** [comment]
Do you have a sample project that demonstrates this?

@livarcocc @Pilchie

**Comment by Darthruneis** [comment]
Hm, I updated Microsoft.Net.Compilers after comparing my project file with a newly-created ASP.NET MVC 2.2 app, and updating from 3.1.1 to 3.3.1 has allowed the solution to build successfully again.
