### ISSUE TITLE
.NET Core 3 doesn't pick up previous configuration file when upgrading from .NET Framework

### ISSUE THREAD

**Issue by Pettor** [dotnet/core#3721]
# General

I am currently migrating a .NET Framework console application to .NET Core 3. The current application uses C# configuration files for application and user settings. When running the .NET Core 3 application it doesn't pick up the previous configuration but instead creates a new empty one.

The configuration path uses the following information about the assembly to find corresponding config `[c:\Documents and Settings]\[username]\[Local Settings]\Application Data\[companyname]\[appdomainname]_[eid]_[hash]\[version]`. The hash should be used the actual filepath which should be the same. However the AppDomain friendly name was `Application Name.exe` but `Application Name` in .NET Core 3. This could be the main issue for picking up the configuration file. I can't find anyway to actually change the friendly name except changing the assembly name to be `Application Name.exe`, but then the output file will be `Application Name.exe.exe` and path will be wrong anyway (and output unacceptably ugly).

To be clear, the application usually used configuration files found in:
`[...\Application Data\[companyname]\application_name_exe_[somehash]\[version]`

.NET Core 3 create a configuration file in:
`[...\Application Data\[companyname]\application_name_[otherhash]\[version]`

**Comment by scalablecory** [comment]
This is a ClickOnce deployment?

**Comment by Pettor** [comment]
This is not an ClickOnce deployment, just regular C# Console application.

**Comment by scalablecory** [comment]
What are you using for configuration?

**Comment by Pettor** [comment]
Not exactly sure I understand the question but the system I am using comes from `ApplicationSettingsBase` and basically using the `ApplicationName.Properties.Application.Default` with values set in `Properties/Application.settings` and `App.config`.

**Comment by scalablecory** [comment]
Can you provide a sample project showing this? It's not clear from this info what the issue might be and this will help a lot. Thanks.

**Comment by carlossanlop** [comment]
13 days no response. Closing.
@Pettor feel free to reopen if you have more info.
