### ISSUE TITLE
Hello world is not run

### ISSUE THREAD

**Issue by Dinushi94** [dotnet/core#3722]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: Linux RHEL 7 - x64

I install .NET to my POp OS(18.04) 
using terminal command **$ dotnet new console -o myApp** create a new application and its name "myApp" and I  open "progarm.css" file in my text editer and I try  to run "hello world" using **$ dotnet run** terminal command, but I can not run "Hello world" 

I got this...
"A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/dinushi/myApp/bin/Debug/netcoreapp3.0/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location]."

**Comment by scalablecory** [comment]
are you on RHEL7 or on Pop (which appears to be Ubuntu-based)?

@jeffschwMSFT

**Comment by Dinushi94** [comment]
Pop Os

**Comment by leecow** [comment]
@Dinushi94, PopOS is not officially supported but because it's a fairly clean downstream distro of Ubuntu, this should work. Can you tell us how you installed .NET Core and provide the output of `dotnet --info`?

**Comment by leecow** [comment]
I set up a Pop! VM using their LTS image (18.04) then, installed .NET Core using the instructions at https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.1.802. The 'hello world' console app worked fine.

**Comment by Dinushi94** [comment]
@leecow Install .NET Core SDK on Linux Ubuntu 18.04 - x64 using flowing link https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current

**Comment by Dinushi94** [comment]
@leecow dinushi@dinushi:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Dinushi94** [comment]
@leecow I will try it using windows :-)

**Comment by leecow** [comment]
I see from your `dotnet --info` output that you're actually running 19.10 and not 18.04. That matters. We don't have a specific 19.10 feed up but the one for 19.04 will work. Use the instructions at https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-3.0.100 and you should be up and running.

**Comment by Dinushi94** [comment]
thnk you
