### ISSUE TITLE
Cannot get symbol u_charsToUChars_50 from libicuuc

### ISSUE THREAD

**Issue by dboehm** [dotnet/core#3725]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Dear Support, on my Linux Laptop having installed Ubuntu 18.04 64 Bit I ran in an issue 

with the command 
dotnet new --help
Cannot get symbol u_charsToUChars_50 from libicuuc
Error: /lib/x86_64-linux-gnu/libicuuc.so.50: undefined symbol: u_charsToUChars_50
Abgebrochen (Speicherabzug geschrieben)

dotnet without any parameter works fine : 

dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

I tried several consoles, even non-graphical BASH 

Please help, fix or workarround in any way .

Many thanks 

Detlef

**Comment by scalablecory** [comment]
Seems like an old version of ICU. @livarcocc @tarekgh

**Comment by tarekgh** [comment]
This weird as we shouldn't be trying to get the address of u_charsToUChars_50, instead we should try to get u_charsToUChars. This API exist since ICU 2.0. 

@janvorli what you think could be happening here? Could be the following macro producing wrong result? 

```C#
#define PER_FUNCTION_BLOCK(fn, lib) extern __typeof(fn)* fn##_ptr;
```

note that u_charsToUChars is the first API we try to get address for so I expect this issue will exist for all ICU APIs.

**Comment by tarekgh** [comment]
@dboehm could you please run the following command to know what ICU version you have? 

```
uconv -V
```

**Comment by tarekgh** [comment]
@dboehm any news?

**Comment by scalablecory** [comment]
@dboehm I'm closing due to lack of response. If you still haven't solved this and can provide more detail, please re-open. Thanks.

**Comment by StarmanAkremis** [comment]
I'm having this issue and can try to help, I'm running a dotnet 8 app and I'm having this issue

```
C:\users\starman\AppData\local\Programs\ILSpy>dotnet ILSpy.dll
016c:fixme:process:GetProcessGroupAffinity (FFFFFFFFFFFFFFFF,000000000019F2E4,0000000000000000): stub
016c:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019F280
016c:fixme:process:GetProcessGroupAffinity (FFFFFFFFFFFFFFFF,000000000019F280,0000000000000000): stub
016c:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\8.0.19\\mscordaccore.dll", 00006FFFFC0C0000) stub
016c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
016c:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019E110) :semi-stub
016c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000001011C5D98, 34) stub
016c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000001011B9E00, 17) stub
016c:err:module:find_forwarded_export module not found for forward 'icuuc68.u_charsToUChars_68' used by L"C:\\windows\\system32\\icu.dll"
Cannot get symbol u_charsToUChars from libicuuc
Error: 127
```


> [@dboehm](https://github.com/dboehm) could you please run the following command to know what ICU version you have?
> 
> ```
> uconv -V
> ```

`uconv v2.1  ICU 76.1`

**Comment by tarekgh** [comment]
@StarmanAkremis we cannot help without more details about your scenario, what is the OS you are using and what you are running to get this failure. From the stack you sent, it shows Windows paths like `C:\\windows\\system32\\icu.dll` and `C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\8.0.19\\mscordaccore.dll`. While you are running the command `uconv -V` which is usually run on Linux. Additionally, this command shows `ICU v76.1` which Windows doesn't carry. Looks to me you have something seriously wrong in your running environment.

**Comment by StarmanAkremis** [comment]
I am using fedora, the windows command was using the wine cmd

**Comment by StarmanAkremis** [comment]
oh wait, it's probably a wine thing really, and I just figured out this is the actual mscore thing, I read everything wrong I'm going to ask on the proper repo
