### ISSUE TITLE
I tried this on a Debian instance. Couldn't get localhost:5000 to work.  I'm not real familiar with Linux and especially Debian.

### ISSUE THREAD

**Issue by maxmin88** [dotnet/core#3726]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
You say a Debian instance... does that mean VM? Is it possible you ran your server on your VM, then tried to access it from a different machine? `localhost` refers to the current machine, you would need to use the VM's address instead, or access the site from a browser inside the VM.

That's all a big guess, though... we need more info about your setup and what's going wrong to help more with this.

**Comment by leecow** [comment]
Closing due to stale thread. If you're still having troubles, please re-open with the requested additional information.
