### ISSUE TITLE
Installation for .Net core3 on RHEL7/Azure failed

### ISSUE THREAD

**Issue by tamatsuxyz** [dotnet/core#3731]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel7/sdk-3.0.100
Operating System: Linux RHEL 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

=====================================================
I tried to install  according to the following doc, but dependency errors showed.

Install .NET Core 3.0 SDK on Linux RHEL 7 - x64:
https://dotnet.microsoft.com/download/linux-package-manager/rhel7/sdk-3.0.100
 
CHAPTER 1. USING .NET CORE 3.0 ON RED HAT ENTERPRISE LINUX
https://access.redhat.com/documentation/en-us/net_core/3.0/html/getting_started_guide/gs_install_dotnet

Finally, I could download libssh2 >= 1.8.0 from Red hat Subscription Page directly.
After install that, rh-netcore30 installation  succeeded.

**Points are the following**
- custom RHUI doesn't provide libssh2 >=1.8.0. so user must download newest rpm from Redhat subscription
- It's better not to exec subscrption-manager command for RHEL(PAYG) on Azure.
   because RHEL(PAYG) on Azure is provided with custom RHUI

   I know that this docment explain general case, but could you add exception ?
   In aspect of technical, user can register RH subscription/RHUI, but this situation mean that user pay extra cost.
  and RHUI configuration is not azure specific. other cloud servies also provids it.
 
------------------------------------------------------------------------------------------
[root@rhel76b tmp]# yum install rh-dotnet30 -y 
~~
 
~~
Error: Package: rh-dotnet30-libcurl-7.61.0-5.el7.x86_64 (rhui-rhel-7-server-dotnet-rhui-rpms)
           Requires: libssh2(x86-64) >= 1.8.0
           Installed: libssh2-1.4.3-12.el7_6.2.x86_64 (@rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-12.el7_6.2
           Available: libssh2-1.4.3-8.el7.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-8.el7
           Available: libssh2-1.4.3-10.el7.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-10.el7
           Available: libssh2-1.4.3-10.el7_2.1.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-10.el7_2.1
           Available: libssh2-1.4.3-12.el7.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-12.el7
           Available: libssh2-1.4.3-12.el7_6.3.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-12.el7_6.3
You could try using --skip-broken to work around the problem
------------------------------------------------------------------------------------------

**Comment by RheaAyase** [comment]
Hi, is there support service on Azure? This doesn't look like neither dotnet issue nor packaging problem, but Azure having things out of date or something. I'd rather direct it to Azure folk specifically.

**Comment by BorisB2015** [comment]
@RheaAyase - the right team got pinged on this one - we are looking into it. Agree that the right place for such issues is with Microsoft Support (portal.azure.com --> Help/Support --> File an issue).

**Comment by atul-ram** [comment]
this seems to be resolved for now. Can you check again !!

**Comment by scalablecory** [comment]
@tamatsuxyz @BorisB2015 can you confirm if this has been resolved? Thanks.

**Comment by nickysaini** [comment]
We do face same issue..
Error: Package: rh-dotnet30-libcurl-7.61.0-5.el7.x86_64 (rhui-rhel-7-server-dotnet-rhui-rpms)
           Requires: libssh2(x86-64) >= 1.8.0
           Installed: libssh2-1.4.3-12.el7_6.3.x86_64 (@rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-12.el7_6.3
           Available: libssh2-1.4.3-8.el7.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-8.el7
           Available: libssh2-1.4.3-10.el7.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-10.el7
           Available: libssh2-1.4.3-10.el7_2.1.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-10.el7_2.1
           Available: libssh2-1.4.3-12.el7.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-12.el7
           Available: libssh2-1.4.3-12.el7_6.2.x86_64 (rhui-rhel-7-server-rhui-eus-rpms)
               libssh2(x86-64) = 1.4.3-12.el7_6.2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by tamatsuxyz** [comment]
Did you try it ?
>I could download libssh2 >= 1.8.0 from Red hat Subscription Page directly.
>After install that, rh-netcore30 installation succeeded.

You can only download newest packages of RHEL **minor** version in EUS repository (RHUI).
So, if you use RHEL under 7.6 version, you can't download libssh2 >= 1.8 from EUS repository.

* you can also disalbe EUS repository.

**Comment by scalablecory** [comment]
Seems like this is a RHEL repository issue and a workaround has been found -- closing this out.
