### ISSUE TITLE
Unable to locate package dotnet-runtime-3.0

### ISSUE THREAD

**Issue by CoffeeUnderstands** [dotnet/core#3735]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian10/runtime-current
Operating System: Linux Debian 10 - x64

I'm unable to install the dotnet-runtime-3.0 package.  I keep getting this message.  I tried is with several other packages and get the same results. 

sudo apt-get install dotnet-runtime-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-runtime-3.0
E: Couldn't find any package by glob 'dotnet-runtime-3.0'
E: Couldn't find any package by regex 'dotnet-runtime-3.0'

**Comment by dagood** [comment]
Can you post the results from every step you ran? Not finding `dotnet-runtime-3.0` is usually caused by a failure in an earlier step.

Could you also confirm what OS you're using by posting the output of `cat /etc/os-release`? The automatic issue filing says Debian 10 x64 based on the page you filed from but I want to make sure that's accurate.

**Comment by CoffeeUnderstands** [comment]
The full story: 

My OS Info:
 cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

To install the .net Core 3 runtime for Debian 10 x32, I followed these instructions 

mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-linux-arm.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

which I got form this location
https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-linux-arm32-binaries

After this, I tried to install the SDK, thinking I would need this for development, but this was my mistake because the SDK isn't available for the Raspberry Pi (as far as I know).  Rather, you have to develop on a separate machine and then deploy to the Pi. 

Before I realized that, I executed the instructions below. You can see the error I get in the final step, which is might make sense if the SDK isn't available for my situation, but when trying to load the runtime (which i know I already had, but just wanted to see that happened if I tried), I get the same message, which is strange. 

pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://packages.microsoft.com/debian/10/prod buster InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.8.2).
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                
Hit:3 https://packages.microsoft.com/debian/10/prod buster InRelease        
Reading package lists... Done                         
pi@raspberrypi:~ $ sudo apt-get install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'
pi@raspberrypi:~ $ 

Output (below) when trying to load the runtime, which should have worked (or at least given a different message, I feel). 

sudo apt-get install dotnet-runtime-3.0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-runtime-3.0
E: Couldn't find any package by glob 'dotnet-runtime-3.0'
E: Couldn't find any package by regex 'dotnet-runtime-3.0'

I don't think there is a technical problem, but rather a procedural/instructional problem with the instructions being unclear as to what is available for which platform. 

I am able to develop on a separate machine and deploy to the Pi, so everything is working, it was just painful to get to that point.

**Comment by dagood** [comment]
Raspberry Pi runs on ARM, not x64. You have to follow the link in this message on the linux-package-manager page:

> Not running x64? You'll need to [download the .NET Core binaries](https://dotnet.microsoft.com/download/dotnet-core/3.0#runtime-3.0.0) instead.

But you say you installed the `dotnet-sdk-3.0.100-linux-arm.tar.gz` binaries successfully this way. That is the SDK! 🙂 Note `dotnet-sdk` rather than `dotnet-runtime`. If you really do want just the runtime, there is a different tar.gz you can get in the runtime column.
