### ISSUE TITLE
While attempting to install Docker on Windows 10 Home Edition, the installation aborted itself stating that Docker can only install on Windows 10 Pro or Enterprise Editions..... Is there some kind of bypass or possibly a setting that I can change in order to successfully install the application? Thank in advance.

### ISSUE THREAD

**Issue by Skrappy** [dotnet/core#3736]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install-docker
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
You may need to ask Docker for info on this, but @shirhatti @MichaelSimons may have some thoughts.

**Comment by MichaelSimons** [comment]
This is a question for the [Docker Community](https://www.docker.com/docker-community).

**Comment by shirhatti** [comment]
Hyper-V is a Windows feature that is not included as part of Windows 10 Home. There's pretty much no workaround here since Docker for Windows requires Hyper-V
