### ISSUE TITLE
Download RSSReader

### ISSUE THREAD

**Issue by Virapan-Pulges** [dotnet/core#3738]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I could not find Program.cs on my Window 10

**Comment by scalablecory** [comment]
Program.cs should be created as part of the `dotnet new console` template. Can you verify you ran this step "create your app" in the tutorial?

**Comment by scalablecory** [comment]
Closing out; please feel free to reopen if you're still having a problem and can provide details.
