### ISSUE TITLE
Could not parse the JSON file

### ISSUE THREAD

**Issue by beefsteak** [dotnet/core#3739]
1.Create new worker service project.
2.Debug is error, but run is right.
![image](https://user-images.githubusercontent.com/14013918/68070114-fe095880-fda4-11e9-96d5-53d2345a41f6.png)

**Comment by beefsteak** [comment]
@scalablecory 
![image](https://user-images.githubusercontent.com/14013918/68101166-388b0680-ff07-11e9-93d4-cd74042847eb.png)
![image](https://user-images.githubusercontent.com/14013918/68101172-40e34180-ff07-11e9-9c8a-c1731691482f.png)
![image](https://user-images.githubusercontent.com/14013918/68101179-4a6ca980-ff07-11e9-830f-4aa1da94800d.png)
![image](https://user-images.githubusercontent.com/14013918/68101193-57899880-ff07-11e9-8994-71c9ee1cdbc8.png)
![image](https://user-images.githubusercontent.com/14013918/68101198-5fe1d380-ff07-11e9-802b-5b6e4a5dcfc9.png)

**Comment by beefsteak** [comment]
@scalablecory All net core projects that contain the appsetting file report the same error.

**Comment by beefsteak** [comment]
@scalablecory But running without debugging does not cause errors

**Comment by davidfowl** [comment]
Looks like a BOM problem. Did this happen by default?

**Comment by beefsteak** [comment]
yes，it happen by default

**Comment by beefsteak** [comment]
Appseting.json default format is utf-8
![image](https://user-images.githubusercontent.com/14013918/68101630-902a7180-ff09-11e9-9cf5-678d3be29bd1.png)

**Comment by beefsteak** [comment]
@scalablecory Does this error have anything to do with net core built-in system.text.json component

**Comment by beefsteak** [comment]
@scalablecory That's fine if project sdk is net core 2.2. So my guess is that net core 3.0 caused the problem

**Comment by scalablecory** [comment]
Thanks for the detail. We'll need to take a look at the file to know for sure, but it's possible.

**Comment by scalablecory** [comment]
@davkean @Pilchie possible template or appsettings parser issue, can you help route this to the right people?

**Comment by Pilchie** [comment]
if it's templates, that would depend on the exact template.  If it's System.Text.Json then corefx.  @ahsonkhan for S.T.J...

**Comment by ahsonkhan** [comment]
I tried to repro the issue on .NET Core 3.0 and **couldn't** (TFM netcoreapp3.0 with `<PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />`). Same with .NET Core 3.1 (even if I explicitly save the appsettings json file to UTF-8 **with BOM**).

@beefsteak, can you share a copy of your project that is showing the error?
What version of VS are you using?

When I create a new worker service (using VS Version 16.4.0 Preview 3.0), the appsettings.json file doesn't contain a BOM so I don't see why the file you are seeing would start with a 0xEF byte.

There was a BOM issue with the JsonSerializer that was fixed for 3.1 (that is if the JSON file did contain a BOM marker), but I can't tell if that is relevant here without a repro:
https://github.com/dotnet/corefx/issues/42145

**Comment by beefsteak** [comment]
![image](https://user-images.githubusercontent.com/14013918/68917192-2d0bcb00-07a4-11ea-9b84-174527144773.png)
Please see the attachment for the project
[WorkerService1.zip](https://github.com/dotnet/core/files/3849812/WorkerService1.zip)

**Comment by ahsonkhan** [comment]
> Please see the attachment for the project

This isn't a valid project/solution (and the files contain gibberish, including the cs/json files). Please fix this before sharing. What encoding are you saying these files as?

![image](https://user-images.githubusercontent.com/6527137/68975363-eb7d1f00-07a7-11ea-8084-9c109c7c6e98.png)

**Comment by beefsteak** [comment]
@ahsonkhan Sorry,I forgot that our project has been encrypted, so we can't transfer the project and I checked  that the file format was utf-8

**Comment by scalablecory** [comment]
If you can't attach your full project, can you attach just the json file?

**Comment by beefsteak** [comment]
@scalablecory Hello, I think I have found the problem, it should be my machine installed the encryption firewall problem, it caused the json file to be encrypted, but I haven't found out why only debugging this problem, but thank you for your patience to solve, I think this problem can be closed.

**Comment by nyf16** [comment]
Hello, have you encountered this problem because you put a password on your own computer ?

**Comment by KrishnaManju** [comment]
> @scalablecory Hello, I think I have found the problem, it should be my machine installed the encryption firewall problem, it caused the json file to be encrypted, but I haven't found out why only debugging this problem, but thank you for your patience to solve, I think this problem can be closed.

Hi, I am getting the same problem in my machine. Could you please help me the steps you followed to fix this problem. Thanks in advance

**Comment by KrishnaManju** [comment]
@beefsteak  am getting the same problem in my machine. Could you please help me the steps you followed to fix this problem. Thanks in advance

**Comment by dilaraozirmak** [comment]
I had the same issue on .net core 3.1 console app. 

I was working on Development environment. And my  ConfigurationBuilder was as follows:
`var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{environment}.json", true, true)
                .Build();`

Since my environment was Development, first i checked the appsettings and appsetting.development files. I didnt check the appsettings.Production.json file. 

Lastly i checked the appsettings.Production.json file, and irrelevent char in the file was like "hello dude!", which caused it.

So make sure you alreaady checked ALL of your json files.

**Comment by moataz2009** [comment]
I have the same problem... i solved it where i find the problem in appsettings.json ... i forgot to add comma ... now all is working fine
