### ISSUE TITLE
Scaffolding Identity on visual studio 2019 core 3.0 issue

### ISSUE THREAD

**Issue by MohammadElKhatib** [dotnet/core#3742]
I just installed visual studio 2019 and core 3.0 is included with the installation.

Then i created new project without authentication after that i scaffolded the identity with custom user and run the application but not able to reach register and login page it is redirecting me to home page with url:

https://localhost:44391/?area=Identity&page=%2FAccount%2FLogin

**Comment by MohammadElKhatib** [comment]
also 
using Microsoft.AspNetCore.Identity;
is missing in RegisterConfirmation Page

**Comment by leecow** [comment]
@vijayrkn and @mkArtakMSFT for some ideas.

**Comment by vijayrkn** [comment]
@HaoK has addressed some of these issues. @HaoK - can you please help with this?

**Comment by HaoK** [comment]
This is being tracked here https://github.com/aspnet/AspNetCore/issues/16802, closing as dupe
