### ISSUE TITLE
donate.exe system error

### ISSUE THREAD

**Issue by asran1** [dotnet/core#3748]
error   because api-ms-win-crt-runtime-i1-1-0.dll is missing 

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Which version of Windows are you running?

**Comment by asran1** [comment]
Windows 7

**Comment by scalablecory** [comment]
.NET Core 3.0 supports Windows 7 SP1. It requires the [Universal CRT](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) update to be installed.

**Comment by carlossanlop** [comment]
1 week no response. Closing.
Feel free to reopen if you have more information.
