### ISSUE TITLE
Test project is was discovered and running test. After a password change, test in separate project are no longer discoverable.

### ISSUE THREAD

**Issue by jllblk** [dotnet/core#375]
Thanks for your interest in .NET Core. 

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

**Comment by svick** [comment]
What kind of password change are you talking about? How are you running the tests?

**Comment by Petermarcu** [comment]
I think we're going to need more info to get any further here. I'm going to close this. Please reopen if you can provide any more data.
