### ISSUE TITLE
'dotnet' is not recognized as an internal or external command error

### ISSUE THREAD

**Issue by Clipping-Creative** [dotnet/core#3750]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error
'dotnet' is not recognized as an internal or external command error

**Comment by leecow** [comment]
Need to know what OS, what version, how you installed and exactly what you did before getting the error.

**Comment by scalablecory** [comment]
Closing out; please feel free to reopen if you're still having a problem and can provide details.
