### ISSUE TITLE
No packages for CentOS 8

### ISSUE THREAD

**Issue by alexsaesee** [dotnet/core#3751]
# No packages for CentOS 8

The packages repository don't have definitions for CentOS 8 but the "supported os" page list CentOS 8.

# General

The documentation on [dotnet.microsoft.com](https://dotnet.microsoft.com/download/linux-package-manager/centos7/sdk-current) list installations for CentOS 7 but not for the 8.

On [packages.microsoft.com](https://packages.microsoft.com/) the CentOS 8 directory doesn't exist.

The documentation [NET Core 3.0 - Supported OS versions](https://github.com/dotnet/core/blob/f24e7e7dba5900c9effc9e50979da7875f0df714/release-notes/3.0/3.0-supported-os.md#linux) list CentOS 8 as supported but if the repo/packages are not yet created, is CentOS 8 supported and if yes, how to get net core 3 on it without the official/clean way ?

**Comment by dagood** [comment]
At this time, you have to use the instructions for the nearest listed distro version, CentOS 7. We support doing it this way, so let us know if you have any problems. https://dotnet.microsoft.com/download/linux-package-manager/centos7/sdk-current

https://github.com/dotnet/core/issues/2576 tracks our plans to get better with handling new distros/versions.

**Comment by alexsaesee** [comment]
Thank you all for your feedback.
