### ISSUE TITLE
dpkg-deb: error: 'packages-microsoft-prod.deb' is not a Debian format archive

### ISSUE THREAD

**Issue by evandropomatti** [dotnet/core#3752]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

### Details

Hi, I'm installing .NET Core 3 on Ubuntu running on WSL 2 (Standard Microsoft Ubuntu app from the marketplace), getting an error.

Following the procedure I download this file:

```s
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
```

Then I get the following when installing it:

```s
pomatti@NT-03024:/tmp$ sudo dpkg -i packages-microsoft-prod.deb
dpkg-deb: error: 'packages-microsoft-prod.deb' is not a Debian format archive
dpkg: error processing archive packages-microsoft-prod.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 packages-microsoft-prod.deb
```

My Ubuntu version (fully updated):

```s
pomatti@NT-03024:/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Comment by dagood** [comment]
It works for me, maybe you hit a network or short-lived error and you ended up with an incomplete file or the error page's html on disk? Try looking at the file contents, and downloading the file on another machine to try to make sure it's not a proxy issue or something like that.

For me, in a Docker container:

```sh
root@4a1ad2c41c80:/# wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
root@4a1ad2c41c80:/# dpkg -i packages-microsoft-prod.deb
[... works]
root@4a1ad2c41c80:/# sha256sum packages-microsoft-prod.deb
bf47049a5838ac6b7f79063b8908727f2ec2a83d95d3da23333bc3c006016583  packages-microsoft-prod.deb
root@4a1ad2c41c80:/# stat packages-microsoft-prod.deb
  File: packages-microsoft-prod.deb
  Size: 3132            Blocks: 8          IO Block: 4096   regular file
Device: 40h/64d Inode: 1420364     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-11-05 15:22:13.549528515 +0000
Modify: 2019-01-02 23:49:00.000000000 +0000
Change: 2019-11-05 15:22:08.938535860 +0000
 Birth: -
```

**Comment by evandropomatti** [comment]
@dagood oh boy that is exactly what happened, file was empty 0kb.

Tried downloading it again from within the WSL but got the same error, but downloading it from outside Windows got the correct file with 4kb. Thanks.

**Comment by evandropomatti** [comment]
Well thought, here is the output: `ERROR: cannot verify packages.microsoft.com's certificate`

```s
pomatti@NT-03024:/tmp$ wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/pomatti/.wget-hsts'. HSTS will be disabled.
--2019-11-05 14:05:28--  https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 40.76.35.62
Connecting to packages.microsoft.com (packages.microsoft.com)|40.76.35.62|:443... connected.
ERROR: cannot verify packages.microsoft.com's certificate, issued by ‘CN=Microsoft IT TLS CA 1,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US’:
  Self-signed certificate encountered.
To connect to packages.microsoft.com insecurely, use `--no-check-certificate'.
```

**Comment by dagood** [comment]
Interesting. I don't quite know enough in this area... I do see a bunch of issues reported for other downloads online that suggest the WSL config in particular is somewhat fragile about this--having out of date or incomplete certificate authorities and stuff around that. I'll leave it alone for now, thanks for the extra info.

**Comment by evandropomatti** [comment]
If that is the case adding it to the store should do the trick. I'll try it tomorrow.

https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu

**Comment by evandropomatti** [comment]
@dagood solved it following [this answer](https://superuser.com/a/719047/1080306). Just had the same problem downloading the GoLang SDK.

1. Download the certificate to `/usr/local/share/ca-certificates`. Extension should be `.crt`, like this: `packages_microsoft_com.crt`
2. Execute the command `sudo update-ca-certificates`. Output was:

```s
pomatti@NT-03024:/usr/local/share/ca-certificates$ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

After that I was able to download it directly from my WSL Ubuntu.

**Comment by dagood** [comment]
@leecow, do you know if the Linux Repo Admins maybe know about this issue in WSL? Something to consider when combining the docs for setting up the repos? Maybe we should at least drop the `-q` so it's easier to diagnose these with initial issue submissions.

**Comment by leecow** [comment]
I wouldn't expect them to have specific insights into WSL. I do aggree we should do some work in this area and perhaps adjust docs and install instructions.

**Comment by evandropomatti** [comment]
Just so you guys know I am having a similar problem with `dotnet add package` and `dotnet restore`.

I tried adding the NuGet certificate manually as I did above but no bueno.

Trying to bypass it somehow:
https://stackoverflow.com/q/58793109/3231778

**Comment by dagood** [comment]
I'd recommend looking at similar issues at https://github.com/microsoft/WSL/issues and filing one there to get at the root cause. I'd use a `wget` example for simplicity. A lot more people with relevant expertise there.

Going after the NuGet restore, I'm worried you might end up disabling a security feature in NuGet's http client. (Not 100% sure that's what you'd end up doing to work around that, but maybe. It also might not be possible to add a workaround on that end anyway.)

**Comment by evandropomatti** [comment]
https://github.com/microsoft/WSL/issues/4666

**Comment by alex-jitbit** [comment]
In my case it was VPN I had ON. Disabling the VPN solved the issue

**Comment by c0d3x27** [comment]
> I'd recommend looking at similar issues at https://github.com/microsoft/WSL/issues and filing one there to get at the root cause. I'd use a `wget` example for simplicity. A lot more people with relevant expertise there.
> 
> Going after the NuGet restore, I'm worried you might end up disabling a security feature in NuGet's http client. (Not 100% sure that's what you'd end up doing to work around that, but maybe. It also might not be possible to add a workaround on that end anyway.)

I was having the same problem this person had, I just solved it by adding the version I needed instead of the bash script on the URL to call the download.

**Comment by XmlmXmlmX** [comment]
In my case it was the company VPN SSL decryption insanity.
