### ISSUE TITLE
Can't find version 3.0 of 'Microsoft.AspNetCore.Mvc'

### ISSUE THREAD

**Issue by mgolois** [dotnet/core#3753]
Hello,
I'm trying to upgrade one of my many class libraries that was used by a Asp.Net Core 2.2 project.
The class library has 'Microsoft.AspNetCore.Mvc' version 2.2 as dependency. Now we are trying to upgrade all the projects using .net core 3.0, net standard 2.1 and asp.net core.
Unfortunately, I can't find many of the Microsoft.AspNetCore packages for the 3.0 version. Am I missing anything?

**Comment by leecow** [comment]
In 3.0, the way a core set of AspNetCore packages is reference changed to only need Microsoft.AspNetCore.App and Microsoft.AspNetCore.All to simplify a number of difficulties around keeping up with dependencies. You should be able to see how this is wired together by spinning a new mvc app (`dotnet new mvc`) using the 3.0.100 SDK. 

/cc @anurse in case I'm saying something misleading.

**Comment by mgolois** [comment]
@leculver, I got you. So in as 3.0, we  only need Microsoft.AspNet.App  (.all is no longer used).
So does it mean that if I only want a single package such as "Microsoft.AspNetCore.Mvc" I have to get the entire meta-package (Microsoft.AspNetCore.App)?

**Comment by anurse** [comment]
In .NET Core 3.0, the packages moved to the new "FrameworkReference" concept. So instead of referencing individual packages, you reference the ASP.NET Core framework in your library, like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

That includes most of the `Microsoft.AspNetCore.*` components. Some are still external, for things like Redis integration and Newtonsoft.Json support. Those have 3.0 versions on NuGet.org you can reference.

**Comment by AlseinX** [comment]
Microsoft.AspNetCore.App version 3.0+ is no longer shipped as a nuget meta package but a framework included in the sdk. So there is no such "entire package" and you don't need to worry about it.

**Comment by mgolois** [comment]
Thank you!!

**Comment by mgolois** [comment]
@anurse , @AlseinX  that means that if I have a .netStandard2.0 project with Microsoft.AspNetCore.Mvc now I have to migrate that project to a .netcoreapp3.0 then add the FrameworkReference "Microsoft.AspNetCore.App". Am I correct?

**Comment by anurse** [comment]
> that means that if I have a .netStandard2.0 project with Microsoft.AspNetCore.Mvc now I have to migrate that project to a .netcoreapp3.0 then add the FrameworkReference "Microsoft.AspNetCore.App". Am I correct?

This is correct. ASP.NET Core 3.0 requires .NET Core 3.0. See https://github.com/aspnet/Announcements/issues/324 for details here.

If you need to continue to support ASP.NET Core 2.x versions you can [multi-target your library](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks).

**Comment by scalablecory** [comment]
Sounds like the question was answered, so closing. Please re-open if there's more to discuss.
