### ISSUE TITLE
Issue with installing microsoft.NETcore.App

### ISSUE THREAD

**Issue by coccipuc** [dotnet/core#3755]
Hello everyone, 

I am new on linux environment, but also on visual studio code.
I am trying to work on R codes on VS code but encounter an issue with the R tools extension. I followed the tutorial to install the extension but I get a strange issue every time i start VS code: 

**It was not possible to find any compatible framework version**
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Is it why I do not have zero syntax highlighting of my package function (e.g mutate from dplyr)

Operating System: Linux Ubuntu 18.04 - x64

Thanks in advance ! 

> sudo apt install dotnet-runtime-2.1

**Comment by leecow** [comment]
Sounds like an extension is wanting the .NET Core 2.1 runtime. If this is true, `sudo apt install dotnet-runtime-2.1` should get you going. I didn't find anything called "T tools" so I couldn't test the assumption.

**Comment by coccipuc** [comment]
> Sounds like an extension is wanting the .NET Core 2.1 runtime. If this is true, `sudo apt install dotnet-runtime-2.1` should get you going. I didn't find anything called "T tools" so I couldn't test the assumption.

Thank you for your answer it worked ! I do not get any warning for the microsoft.NETCore.app with your solution, but I still do not have any  syntax completion of the function that comes from additional packages (ggplot52, dplyr, stringr ...).

I do have autocompletion for Python (i tested with numpy and tkinter package) so I believe my VS code is still not so well set up. It is an other issue so I might create a new one if I don't find an existing one. 

Thank you leecow !

PS: I edited my issue, i am trying to use R tools and not T tools.

**Comment by leecow** [comment]
Glad that got you going!
