### ISSUE TITLE
CentOS7 x64 - Unable to install due to missing dotnet-runtime-deps-3.0.0-rhel.7-x64.rpm

### ISSUE THREAD

**Issue by minimusgeekus** [dotnet/core#3756]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos7/sdk-current
Operating System: Linux CentOS 7 - x64

Unable to install due to missing dotnet-runtime-deps-3.0.0-rhel.7-x64.rpm

Assistance appreciated thanks.

Start>>>
This was OK...
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

 however...
This was NOT OK...
Is this ok [y/d/N]: y
Downloading packages:
dotnet-runtime-deps-3.0.0-rhel FAILED                                          
https://packages.microsoft.com/centos/7/prod/dotnet-runtime-deps-3.0.0-rhel.7-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Error downloading packages:
  dotnet-runtime-deps-3.0-3.0.0-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by leecow** [comment]
The 3.0 deps file name is `dotnet-runtime-deps-3.0.0-centos.7-x64.rpm`. What is your complete `zypper install` command line that is failing?

**Comment by carlossanlop** [comment]
Closing due to lack of response. @minimusgeekus feel free to reopen if you have an answer for @leecow 's question.
