### ISSUE TITLE
CentOS support on arm?

### ISSUE THREAD

**Issue by AlseinX** [dotnet/core#3759]

**Comment by omajid** [comment]
I am working on making .NET Core build from source on arm64 here: https://github.com/dotnet/source-build/pull/1300. If/when that gets reviewed and merged, we will most likely enable it on RHEL too, though I am not sure of the timelines. CentOS might pick up arm64 support via RHEL, then.

(I work for Red Hat; I can't speak for Microsoft's plans)

**Comment by SusLes** [comment]
@leecow

**Comment by leecow** [comment]
ARM64 enablement is definitely in the plans but the timeline is uncommitted at the moment.
