### ISSUE TITLE
Is it possible to support typescript language

### ISSUE THREAD

**Issue by buffge** [dotnet/core#3761]
# Issue Title

l want to know if dotnet core has plans to support typescript language

It's too tired to learn another language(c#)

**Comment by scalablecory** [comment]
TypeScript is not a .NET language, and there are no plans to make it one. However, it can be used inside an ASP.NET Core project to write client-side scripts, where it works well paired with an ASP.NET Core backend.

What are you looking to do with it, were it a .NET language?

**Comment by scalablecory** [comment]
Closing out, thanks for the question.
