### ISSUE TITLE
i can't use dotnet, i've already check o cmd , it said 'dotnet' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by dnhan1707** [dotnet/core#3762]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
We'll need a bit more information to try and help figure out what's going on. What OS and version are you running and how did you install .NET Core?

**Comment by dnhan1707** [comment]
I knew the problem, it said that error system , because I lost
"api-ms-win-crt-runtime-l1-1-0.dll " .So can you please help me with
downloading and setup it for running Net.core

On Nov 6, 2019 11:42 PM, "Lee Coward" <notifications@github.com> wrote:

We'll need a bit more information to try and help figure out what's going
on. What OS and version are you running and how did you install .NET Core?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/core/issues/3762?email_source=notifications&email_token=ANWITIRRAJLAEW3X6RUE3J3QSLXWFA5CNFSM4JJUR5YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDHFWQQ#issuecomment-550394690>,
or unsubscribe

**Comment by scalablecory** [comment]
Are you on Windows 7? You need to install SP1 and the [Universal C Runtime](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows).

**Comment by dnhan1707** [comment]
Ok, thanks.very much

**Comment by carlossanlop** [comment]
Seems to be resolved, thanks @scalablecory . Closing the issue.
Feel free to reopen @dnhan1707 if you keep encountering issues.
