### ISSUE TITLE
Dot net not being recognised

### ISSUE THREAD

**Issue by peterbignold** [dotnet/core#3764]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Despite  installing .NET Core SDK 3.0 or later from the site
and it showing up in the list of programs in control panel
I get the following when I try to run dot net commands in a cmd window

Microsoft Windows [Version 10.0.17763.805]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\peter_000>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\peter_000>dotnet new console -o myApp
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

C:\Users\peter_000>cd myApp

**Comment by scalablecory** [comment]
Is it possible you installed the "runtime" rather than the "sdk" package?

Can you give the output of "dotnet --list-sdks"?

Thanks.

**Comment by scalablecory** [comment]
Closing out, please re-open if you're still having the issue and can provide more detail.
