### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by rajesh-sys** [dotnet/core#3766]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Not running how? Need more detail.

**Comment by rajesh-sys** [comment]
Hi 

 

Please check the screenshot  after I type dotnet on cmd.

 



 

 

Thanks and Regards

 

Rajesh Subramanian

**Comment by scalablecory** [comment]
Screenshots don't reach GitHub when you attach them to an email reply.

**Comment by carlossanlop** [comment]
12 days no response. Closing.
