### ISSUE TITLE
'Dotnet' is not recognized as as an y=internal or extenal command

### ISSUE THREAD

**Issue by tleungcredo** [dotnet/core#3773]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Have you closed and reopened your console window? PATH variables need to be re-read to recognize dotnet.

**Comment by scalablecory** [comment]
Closing due to lack of response; if you're still having this issue, please re-open and provide additional detail.
