### ISSUE TITLE
Checksum verification failing while installing dotnet core 2.1.802 in docker container based on linux buildpack-deps

### ISSUE THREAD

**Issue by arroyc** [dotnet/core#3774]
Since morning checksum is not matching and dotnet core 2.1.802 installation is failing. I cross checked the checksum as mentioned in https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.1/releases.json
`"name": "dotnet-sdk-linux-x64.tar.gz",
            "rid": "linux-x64",
            "url": "https://download.visualstudio.microsoft.com/download/pr/8029a774-0cc8-4c62-945e-169a473b51d3/2c3f6a18aed152e5e498035695ed816f/dotnet-sdk-2.1.802-linux-x64.tar.gz",
            "hash": "8601EC68FA8978C5A08A696CC69F5E0AA9DABF274BADE40E2FD9DED2E563F2CC7A1CB418A95C9B52E1FA9B6C4A30993BE68CB3B6BBDA4598C57B37EC9CE992AD"`

This is what I'm seeing in the log ....

> + echo
> + echo 'Installing .NET Core SDK 2.1.802 ...'
> + echo
> + DEFAULT_DOTNET_SDK_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.802/dotnet-sdk-2.1.802-linux-x64.tar.gz
> + DOTNET_SDK_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.802/dotnet-sdk-2.1.802-linux-x64.tar.gz
> 
> Installing .NET Core SDK 2.1.802 ...
> 
> + curl -SL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.802/dotnet-sdk-2.1.802-linux-x64.tar.gz --output dotnet.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  159M  100  159M    0     0  19.0M      0  0:00:08  0:00:08 --:--:-- 18.1M
> 
> Verifying archive hash...
> + '[' 8601EC68FA8978C5A08A696CC69F5E0AA9DABF274BADE40E2FD9DED2E563F2CC7A1CB418A95C9B52E1FA9B6C4A30993BE68CB3B6BBDA4598C57B37EC9CE992AD '!=' '' ']'
> + echo
> + echo 'Verifying archive hash...'
> + echo '8601EC68FA8978C5A08A696CC69F5E0AA9DABF274BADE40E2FD9DED2E563F2CC7A1CB418A95C9B52E1FA9B6C4A30993BE68CB3B6BBDA4598C57B37EC9CE992AD dotnet.tar.gz'
> + sha512sum -c -
> dotnet.tar.gz: FAILED
> sha512sum: WARNING: 1 computed checksum did NOT match

**Comment by SusLes** [comment]
@leecow

**Comment by arroyc** [comment]
It started working again … seems to be an temporary issue, but it blocked all our builds for a day.. it will be nice if you have some tests on your side to check the checksum verification
