### ISSUE TITLE
Wrong Login parameter ASP.NET Core 3.1 Identity

### ISSUE THREAD

**Issue by AlexNek** [dotnet/core#3779]
# Issue Title

Why _signInManager.PasswordSignInAsync received as 1st parameter email value? It must be user name.

# General
By the user registering you fill username field with email value. If I test it immediate after register  with email then login work but when I change user name then login doesn't work. In addition invalid model "Cleared" all fields. My facebook login button on the right side will disappear.

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#16991
