### ISSUE TITLE
ShowLinkerSizeComparison=true does not show the linker size comparison

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/core#3790]
# ShowLinkerSizeComparison=true does not show the linker size comparison

If I run dotnet publish with

```
dotnet publish -c Release --runtime win-x64 -p:SelfContained=true -p:PublishTrimmed=true -p:ShowLinkerSizeComparison=true -p:LinkDuringPublish=true -p:PublishSingleFile=true
```

The linker size comparison should show, but it does not.
You can easily replicate on a `dotnet new console` project.

# Version
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```

**Comment by SusLes** [comment]
@carlossanlop

**Comment by carlossanlop** [comment]
@nguerrera @livarcocc can you please help with this issue?

**Comment by nguerrera** [comment]
I am not aware of the property. @sbomer can you  help?

**Comment by sbomer** [comment]
@NicolasDorier this property existed in a preview out-of-band package, but a lot has changed since then and the out-of-band package is no longer supported. Please see https://aka.ms/dotnet-illink for the current docs - sorry for the trouble.

**Comment by NicolasDorier** [comment]
I understand, I hope it could be added again in the future, this was very useful.
