### ISSUE TITLE
curl "error setting certificate verify locations" after installing rh-dotnet30 on RHEL 7.7

### ISSUE THREAD

**Issue by DmitryGulin** [dotnet/core#3794]
Summary: cURL starts failing with "curl: (77) error setting certificate verify locations" after installing rh-dotnet3 package and enabling rh-dotnet30 SCL.

Steps to reproduce with RHEL 7.7 VM in Azure:
1. Create a new Azure VM from RHEL 7.7 image;
![image](https://user-images.githubusercontent.com/1832857/68692318-4a8e2a00-0543-11ea-84b3-2738b00382ee.png)

2. Log into the newly created VM with Cloud (or local) Shell;
3. Execute 'sudo yum update' to make sure that all recent updates have been installed;
![image](https://user-images.githubusercontent.com/1832857/68692267-2d595b80-0543-11ea-8383-2315664b8e0f.png)

4. Confirm that cURL works, e.g. `curl https://www.google.com`
5. Install rh-dotnet30 package: `sudo yum install rh-dotnet30 -y`;
![image](https://user-images.githubusercontent.com/1832857/68692336-537efb80-0543-11ea-9e8c-a39c02a9ba91.png)

6. Confirm curl is still functional;
7. Switch to rh-dotnet30 SCL: `scl enable rh-dotnet30 bash`;
8. Try using curl to connect to any resource and observe the error
![image](https://user-images.githubusercontent.com/1832857/68692221-1b77b880-0543-11ea-9150-244a611ed036.png)

Expected behavior:
cURL is functional with rh-dotnet30 software collection.

Impact:
I cannot complete Azure DevOps build agent configuration on a RHEL 7.7 machine with .NET Core 3 support, since Build Agent uses cURL internally to connect to Azure DevOps server.

New Issue:
rh-dotnet22 works fine and doesn't have similar issue.

**Comment by omajid** [comment]
Also tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1768029

There's a workaround suggested [here](https://github.com/redhat-developer/dotnet-jenkins-slave/issues/24):

    export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

Depending on what you are doing (do you need `curl` when running .NET Core?) you can invoke `curl` first, then run the `scl ... ` commands for invoking .NET Core.

**Comment by carlossanlop** [comment]
@DmitryGulin  did the suggestion provided by @omajid work for you?

**Comment by omajid** [comment]
A fix for the RPM to address this bug was just released. If you update the VM, a workaround shouldn't be needed anymore.

**Comment by omajid** [comment]
> Are there any plans to publish that update to rhel-7-server-dotnet-rpm repo as well, so that I can update our on-prem server?

I thought that's exactly where the update was pushed. And Azure picked it up from there. Are you seeing something different on your end?

**Comment by DmitryGulin** [comment]
I've got rh-dotnet30 package and all dependencies installed from rhui-rhel-7-server-dotnet-rhui-rpms on Azure VM and noticed that rh-dotnet30-libcurl, for example, was version 7.61.0-6.el7.
Installing rh-dotnet30 on my corporate server would get it installed from rhel-7-server-dotnet-rpms and rh-dotnet30-libcurl version I'm getting from there is 7.61.0-5.el7.
Thus a assumed that update was not available outside of RHUI repos yet.

**Comment by omajid** [comment]
@DmitryGulin Can you open a support ticket? If you are not seeing `rh-dotnet30-libcurl-7.61.0-6.el7.x86_64.rpm` as the latest release, that seems like a problem somewhere in software delivery pipeline.

**Comment by DmitryGulin** [comment]
@omajid  I've got this update installed on my on-prem server via rhel-7-server-dotnet-rpms today.
Not sure what was the reason for delay yesterday, but I confirm that the issue has been fixed on-prem as well, thus it can be closed.

Thank you so much!
