### ISSUE TITLE
win7无法成功建立应用程式

### ISSUE THREAD

**Issue by fapengzhang** [dotnet/core#3795]
![微信截图_20191113113200](https://user-images.githubusercontent.com/57212458/68731009-a327fa80-0609-11ea-970c-b5e9396f780c.png)

**Comment by huoyaoyuan** [comment]
The file to create already exists. Add `--force` to the command, or manually delete them first, or change the name (myApp).

需要创建的文件已经存在。在命令中加入`--force`来覆盖，或者手动打开删除该文件/文件夹，或者更换一个名称（myApp）。

**Comment by carlossanlop** [comment]
I believe the response is the actual solution. Closing this issue as it seems to be resolved.
