### ISSUE TITLE
Access denied when using "dotnet new" in system32 directory

### ISSUE THREAD

**Issue by Sushanta565** [dotnet/core#3796]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Sushanta565** [comment]
OS version-WIndows 7 64 bit
![Net](https://user-images.githubusercontent.com/57709687/68757750-7936fe00-0632-11ea-801f-f8c514434816.png)
screenshot of the error msg is attached .Kindly help

**Comment by huoyaoyuan** [comment]
You are running command under Windows system folder (`C:\Windows\system32>`), which shouldn't be written by the user.
The way you launched your command prompt seems bad. I don't know a common way to start a non-administrator cmd from the system path. Maybe you are double-clicking cmd.exe from file explorer?
To properly launch a command prompt: open the desired folder in explorer, hold Shift and right click, and select "open command prompt here".

**Comment by scalablecory** [comment]
Your user does not have permissions to write to the system32 directory. System32 is an operating system directory and not intended for user files, so this is a good thing. You should try doing this somewhere under your Documents directory.
