### ISSUE TITLE
Unable to start Kestrel. Failed to bind to address address already in use

### ISSUE THREAD

**Issue by mohamad-alibrahim** [dotnet/core#3797]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
You can open a command prompt as admin and run "netstat -abn" to see what other app is using that port.

**Comment by carlossanlop** [comment]
@mohamad-alibrahim did the suggestion provided by @scalablecory work for you?

**Comment by scalablecory** [comment]
Closing out. Please feel free to reopen if you're still seeing this issue and can provide more detail.
