### ISSUE TITLE
Late Binding Models from the Controller

### ISSUE THREAD

**Issue by GrantHoffman** [dotnet/core#3799]
I'm trying to figure out a way to leverage the existing model binding in the project.  To Bind to an entity at run time.

I have a stackoverflow question for it [here](https://stackoverflow.com/questions/58828401/resolve-models-dynamically-from-httpcontext)

Basically I'm trying to resolve a type from a controller. e.g

    public T ResolveType<T>(HttpContext httpContext, string parameterName)
    {
          //How can I resolve the Type from the query string with the parameterName?
    }

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#17075
