### ISSUE TITLE
How to join .NET Platform organization

### ISSUE THREAD

**Issue by PeterPreter** [dotnet/core#3800]
Is it possible to become a member of [ .NET Platform](https://github.com/dotnet)  for guys not from Microsoft?

If yes, are there any requirements for that? I know that I should contribute a lot, but how much? Let's  say I have 20+ commits in different repositories from .NET Platform organization, then should I create some request or wait until someone will notice me?

I know how to become a member of [.NET Foundation](https://github.com/dotnet-foundation), but I'm interested in [ .NET Platform](https://github.com/dotnet).

Thank you in advance and sorry if this is not the place to ask such questions.

**Comment by carlossanlop** [comment]
@terrajobst @richlander do you have an answer for this? Do you know if external people can join the .NET Platform group?

**Comment by PeterPreter** [comment]
It would be great to know, thanks

**Comment by richlander** [comment]
In general, we add people working directly on .NET Foundation projects to the dotnet org. In the case of the .NET Core project and associated repos, we only add Microsoft people. We may change that in future, but that's our current approach. Here is our latest updated on that: https://github.com/dotnet/announcements/issues/144. 

On topic of committer permissions, we have no plan to offer that to folks outside of the .NET team. We get questions from time to time on our governance strategy for committer access, and most big organizations (commercial and government) appreciate this approach. It isn't the most OSS friendly approach one could imagine, but it works.

**Comment by carlossanlop** [comment]
@PeterPreter , did @richlander's response answer your question?

**Comment by PeterPreter** [comment]
yes, thanks
