### ISSUE TITLE
Debugging our partially stalled .NET Core 3.0.0 Linux process dump

### ISSUE THREAD

**Issue by efoleymsft** [dotnet/core#3801]
We have a .NET core 3.0 application that is hung and we would like to figure out what it is doing and what it is hung on. 

I collected a process dump from the running process on the Linux machine with (9915 being the process Id I got from ```ps -A```: 
```sudo /usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/createdump -u 9915```

This created a coredump.9915 file. I tried to download this and load this in VS and dotmemory and it didn't work as it wasn't recognized as a valid .dmp file (which I understand). Then I installed sos and lldb on the box with the process, based on the documentation https://github.com/dotnet/diagnostics/blob/master/documentation/installing-sos-instructions.md, with:
```sudo apt install lldb```
```dotnet tool install -g dotnet-sos```
```dotnet-sos install```

Next I attempted to load lldb based on the coredump and our process file:
```lldb --core /tmp/coredump.9915 /path/to/our/executable```

I can do ```thread list``` to get a list of threads but every time I selected a thread and tried ```clrstack``` I get:
```
(lldb) clrstack
OS Thread Id: 0x0 (1)
Failed to start stack walk: 8000ffff
```

I read somewhere that there needs to be a link between the clrthread and a thread to get the clrstack due to some bug, not sure if it applied to 3.0.0, but I did that with an example:
```setsostid 26cc 1```

This gave me a stack for that thread but none of the stacks from any of the clrthreads I linked to seemed to have very relevant information. **One was WaitForShutdown for our HostBuilder usage, which makes sense, but I couldn't figure out how to view stacks for currently operating tasks in the threadpool.** 

I also was trying to pull this dump file (not .dmp) to my local machine and use windbg to get more information but loading SOS and coreclr never seemed to properly work. For example, I would do:
```.load C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\coreclr.dll```
```.load C:\Users\efoley\.dotnet\sos.dll```
```.load C:\Users\efoley\.dotnet\SOS.NETCore.dll```

SOS calls would fail with
```
The call to LoadLibrary(C:\Users\efoley\.dotnet\sos) failed, Win32 error 0n126
    "The specified module could not be found."
Please check your debugger configuration and/or network access.
```
**Is there something I'm doing wrong with SOS loading here?** I'm going off of this MSDN blog:
https://blogs.msdn.microsoft.com/rohithrajan/2018/03/26/looking-inside-a-net-core-process-using-windbg/

I still have the Linux machine with the partially stalled process and I have the dump file as well. Mentioning Mike @mikem8361 as it looks like he's a primary point of contact here for the last 2 years of github related issues to windbg debugging.

**Comment by mikem8361** [comment]
What version of lldb was installed? SOS on core dumps really only works on 3.9 or greater. You shouldn't have to use the `setsostid` command with a newer lldb.

The Windows SOS under windbg isn't supported for Linux coredumps. The only way to debug Linux core dumps is with lldb or [dotnet-dump](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md#dump-collection-and-analysis-utility-dotnet-dump) on Linux. Windbg can load Linux core dumps now but not run the SOS extension against them.

FYI, `.load` under Windbg is meant only for extensions and "coreclr.dll" and "SOS.NETCore.dll" are not windbg extensions.  The `sos.dll` extension will only work with Windows minidumps or live .NET core sessions.

**Comment by scalablecory** [comment]
Looks like no response for some time, closing this out.
