### ISSUE TITLE
Could not install in linux

### ISSUE THREAD

**Issue by vinay1411** [dotnet/core#3804]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Do you have any details?

**Comment by leecow** [comment]
Closing due to no response from @vinay1411. Please re-open with additional details if you're still having troubles.
