### ISSUE TITLE
Windows Services crashes occasionally with exit code c0000005

### ISSUE THREAD

**Issue by tukzer** [dotnet/core#3805]
# Issue Title

We create some windows services using generic host based on dotnetcore 2.1.3. However, we found it crashed randomly with following exception in **different places**.

Application: dotnet.exe
CoreCLR Version: 4.6.26725.6
Description: The process was terminated due to an internal error in the .NET Runtime at IP XXX (XXX) with exit code c0000005.

# General

Problems:

1.  Windows services exited with error but we found **different positions** via .dmp file. Postions includes:

- call async task synchronously. The services is a Calstle.Core proxied stub.
[calcfor.zip](https://github.com/dotnet/core/files/3845721/calcfor.zip)

- call unmanaged code. create an db2 connection via ibm.data.db2.core\1.3.0.100.
[triagedump.zip](https://github.com/dotnet/core/files/3845717/triagedump.zip)

2.  Windows services on certain machine (virtual host) using dotnet.exe offen **crashes at the same time** together (All or some).

Environment:
Windows Server 2012 R2 Standard.    /  x64   

Addition:
We add log as belows:
```c#
        public Task WaitForStartAsync(CancellationToken cancellationToken)
        {
            cancellationToken.Register(() => _delayStart.TrySetCanceled());

            ApplicationLifetime.ApplicationStarted.Register(() =>
            {
                Logger.Info("Application started. Hosting environment: {0}; Content root path: {1}",
                    Environment.EnvironmentName, Environment.ContentRootPath);
            });

            ApplicationLifetime.ApplicationStopping.Register(() =>
            {
                Logger.Info("Application is shutting down...");
            });
            ApplicationLifetime.ApplicationStopped.Register(() =>
            {
                _delayStop.Set();
            });

            new Thread(Run).Start(); // Otherwise this would block and prevent IHost.StartAsync from finishing.
            return _delayStart.Task;
        }
```

And we sometimes captured the ApplicationStopping event with no manual operation.  So where does this request come from? 

We've binged a lot for that problem, and found no clues. Any help would be gratefully appreciated.

**Comment by scalablecory** [comment]
> we found it crashed randomly with following exception

Did you mean to add some stack traces?

**Comment by tukzer** [comment]
We cannot capture any exception, try..catch was not working， and was only able to find exceptions via Windows Error Reporting, but with no more details here. The attachments shows more stack trace info as belows:
`0:015> !clrstack -a
OS Thread Id: 0x4fe0 (15)
        Child SP               IP Call Site
000000C9DC2FD550 00007ffb00afa40d BaoNeng.Bnp.Core.Tasks.TaskBase+d__10.MoveNext()
    PARAMETERS:
        this (0x000000C9DC2FD6F0) = 0x00000222c7ae8ae8
    LOCALS:        
000000C9DC2FD6F0 00007ffb5f343b19 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib]](System.__Canon ByRef)
    PARAMETERS:
000000C9DC2FD760 00007ffb00afa095 BaoNeng.Bnp.Core.Tasks.TaskBase.TryUpdateTaskResultAsync(BaoNeng.Bnp.Admin.ServiceInterface.Tasks.ITaskDispatcher, BaoNeng.Bnp.Admin.Model.TaskInfo, BaoNeng.Bnp.Core.Tasks.ExecuteResult)
    PARAMETERS:
        this (0x000000C9DC2FD7D0) = 0x00000222c6f27e68
000000C9DC2FD7D0 00007ffb004bf801 BaoNeng.Bnp.Core.Tasks.TaskBase+d__9.MoveNext()
    PARAMETERS:
        this (0x000000C9DC2FDA90) = 0x00000222c72ce750
    LOCALS:        
000000C9DC2FDA90 00007ffb5f343b19 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib]](System.__Canon ByRef)
    PARAMETERS:
000000C9DC2FDB00 00007ffb004bec0e BaoNeng.Bnp.Core.Tasks.TaskBase.ExecuteTaskAsync(System.Threading.CancellationToken)
    PARAMETERS:
        this (0x000000C9DC2FDB70) = 0x00000222c6f27e68
        cancellationToken (0x000000C9DC2FDB78) = 0x00000222c6f27e98
    LOCALS:
        0x000000C9DC2FDB48 = 0x00000222c72ce750
        0x000000C9DC2FDB40 = 0x0000000000000000
000000C9DC2FDB70 00007ffb004be897 BaoNeng.Bnp.Core.Tasks.TaskBase+d__8.MoveNext()
    PARAMETERS:
        this (0x000000C9DC2FDC50) = 0x00000222c6f280a8
    LOCALS:
        `
And our code ：
`        /// <summary>
        /// Update Task status
        /// </summary>
        /// <param name="taskDispatcher"></param>
        /// <param name="task"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        private async Task TryUpdateTaskResultAsync(ITaskDispatcher taskDispatcher, TaskInfo task, ExecuteResult result)
        {
            var taskIdentifier = GetTaskIdentifier(task);
            try
            {
                var executeResult = new TaskExecuteResult
                {
                    TaskId = task.TaskId,
                    CalculateStart = result.CalculateStart,
                    Result = result?.Message.NulllOrEmptyThen("Unknown Error"),
                    IsSuccess = result?.IsSuccess ?? false,
                    TaskIdentifier = taskIdentifier
                };

                await taskDispatcher.UpdateTaskResultAsync(executeResult);
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Update task status failed, taskId: [{0}], {1}", taskIdentifier, ex.Message);
            }
        }
`
Does this help?  Now we found exceptions on both generic host and web host,  and have to restart the process using a watchdog. It would be highly appriaciated for any suggestions that we can take a try.

**Comment by tukzer** [comment]
We have 4 windows service apps. These apps crashed one or more at a time. It's really confusing for apps crashed together. I found no firewall or other server events at that time, and app crashes in my dev machine (windows10, x64) as well.
![image](https://user-images.githubusercontent.com/2265311/70286709-30283300-1807-11ea-8283-7df3057731cf.png)

**Comment by tukzer** [comment]
We finally found it was due to a improper use of db2command. It's solved after use 'using' statement.  These code worked well on other database drivers , but caused exceptions on db2 connection pool when paralleling database accessing.

            var cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = selectSql;

            //SqlBuilder.BuildCommand(cmd, whereOptions);
            cmd.BuildCommand(whereOptions);

            var retObj = cmd.ExecuteScalar();
