### ISSUE TITLE
Cannot build a WPF .net core 3.0 app on platform target x86 

### ISSUE THREAD

**Issue by magicmanone** [dotnet/core#3812]
Hi,
I can't build/run a WPF desktop application with netcore 3.0 with platform target x86.
My OS is Windows 10 x64 1909.
Both .net core sdk 3.0 (x86/x64) are installed.

my steps to reprduce the issue:

1. dotnet new wpf
2. add <PlatformTarget>x86</PlatformTarget> to the .csprj
3. dotnet run 

The program does not start.
if I open this solution in Visual Studio Enterprise 2019 16.3.8, the build stops with the error message:

Error MSB3030: File "C:\Temp\obj\x86\Debug\netcoreapp3.0\Temp.exe" could not be copied ... 

Can you help me please?

With best regards

**Comment by scalablecory** [comment]
Do you have more to the error message? It looks like you might have the app running already.

**Comment by magicmanone** [comment]
Unfortunately no. The program does start and terminate itself immediately without showing the window.
The Temp.csprj looks like
`<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">`
`<PropertyGroup>`
    `<OutputType>WinExe</OutputType>`
    `<TargetFramework>netcoreapp3.0</TargetFramework>`
	`<PlatformTarget>x86</PlatformTarget>`    
    `<UseWPF>true</UseWPF>`    
    `<Platforms>x86</Platforms>`
  `</PropertyGroup>`
`</Project>`

**Comment by scalablecory** [comment]
Would you be able to give us your solution?

**Comment by magicmanone** [comment]
Hi,
my solution was to upgrade to .net core 3.0.101 sdk.
Then it was no problem anymore.
