### ISSUE TITLE
Dictionary`2.TryGetValue Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by 2881099** [dotnet/core#3813]
# Issue Title

Dictionary`2.TryGetValue Object reference not set to an instance of an object. 

# General

![image](https://user-images.githubusercontent.com/16286519/68923858-4586e000-07ba-11ea-8066-b731553b63de.png)

This mistake doesn't happen every time. There is a certain probability.

```csharp
static void Main(string[] args)
{
    ThreadPool.SetMinThreads(100, 100);

    Dictionary<int, ConcurrentDictionary<string, bool>> dic = new Dictionary<int, ConcurrentDictionary<string, bool>>();
    var dicLock = new object();
    var par = Parallel.For(0, 100, a =>
    {
        if (dic.TryGetValue(1, out var val) == false)
        {
            lock (dicLock)
            {
                if (dic.TryGetValue(1, out val) == false)
                {
                    dic.Add(1, new ConcurrentDictionary<string, bool>());
                }
            }
        }
    });

    while (!par.IsCompleted) ;

    return;
}
```

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/68928277-a6b3b100-07c4-11ea-9098-6aa9c0ae88de.png)

Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at ConsoleApp2.Program.<>c__DisplayClass0_0.<Main>b__0(Int32 a) in C:\Users\28810\Desktop\testredis\ConsoleApp2\Program.cs:line 19
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

**Comment by bartonjs** [comment]
Dictionary (as opposed to ConcurrentDictionary) is not thread-safe.  This type of exception is expected under concurrent writes.

If you need concurrent access, you need to use ConcurrentDictionary, or an explicit locking mechanism.

https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netframework-4.8

**Comment by 2881099** [comment]
But this error will not occur when I use. NetFramework 4.5

**Comment by 2881099** [comment]
This exception of the TryGetValue method is very unfriendly.

**Comment by bartonjs** [comment]
> But this error will not occur when I use. NetFramework 4.5

The race condition (Add changing the bucket strategy while TryGetValue is reading it) is still there, it just means you haven't hit it.
