### ISSUE TITLE
getting started with sdk microsoft .net on windows 7 64bit

### ISSUE THREAD

**Issue by gbengaolanipekun** [dotnet/core#3814]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows 7

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\>dotnet new console -o myApp -----this is the code I ran
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\3.0.0\hostfxr.dll]
, HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\h
ost\fxr\3.0.0\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306  ....this is the error i got

**Comment by dagood** [comment]
Did you go to https://go.microsoft.com/fwlink/?linkid=798306 and make sure you have the .NET Core prerequisites installed?

**Comment by carlossanlop** [comment]
No response in 10 days. Closing.
