### ISSUE TITLE
hostfxr.dll will not load

### ISSUE THREAD

**Issue by cblike** [dotnet/core#3818]
Noob here.  I've installed .NET Core SDK 3.0.100 on Windows 10, but every time I try to run a dotnet command in the CLI, I get the following error:

Failed to load the dll from [C:\Program Files\dotnet\host\fxr\3.0.0\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\3.0.0\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
What am I doing wrong here?

**Comment by jeffschwMSFT** [comment]
In .NET Core you need to install a matching architecture for the app you are running: on Windows either x86 or x64.  Which did you install, and what command did you run?

cc @livarcocc @elinor-fung

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
