### ISSUE TITLE
"install packages-Microsoft-prod.deb" fails on Debian

### ISSUE THREAD

**Issue by carterdacat** [dotnet/core#3820]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Operating System: Linux Ubuntu 16.04 - x64

Hi. whenever i try to install packages-Microsoft-prod.deb it ways it is not a Debian format archive. please help

**Comment by scalablecory** [comment]
There are Debian-specific instructions, can you try those? If those don't work, please provide the exact commands/errors you're getting.

**Comment by carlossanlop** [comment]
No response in a week. Closing.
