### ISSUE TITLE
After running "yum install rh-dotnet30 -y" I get " There are no enabled repos.  Run "yum repolist all" to see the repos you have.  You can enable repos with yum-config-manager --enable <repo>"

### ISSUE THREAD

**Issue by SilverStrings024** [dotnet/core#3821]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current?journey=vs-code
Operating System: Linux RHEL 7 - x64

I ran ```yum install rh-dotnet30 -y``` but got "There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>" and how to get the DotNet repo is not mentioned in the installation instructions. I'm using Linux Mint (Cinnamon) 19.2

**Comment by dagood** [comment]
The page you were on had the RHEL 7 instructions, but Linux Mint is a derivative of Ubuntu, so you should select it in the dropdown instead. It looks like Mint 19.2 is based on Ubuntu 18.04, so you would pick that.

**Comment by carlossanlop** [comment]
@dagood gave the accepted response: Mint is based on Ubuntu.
Closing since there was no response in a week.
