### ISSUE TITLE
Is it possible to change login url from one place? 

### ISSUE THREAD

**Issue by Aleksej-Shherbak** [dotnet/core#3822]
I will describe what I mean here.  By default, Identity has the following login URL: `/Identity/Account/Login`. I would like to change it on just `/Login`. 

And I have it done! For this I have added on the `Login.cshtml` file the following code: 
```
@page "/Login"
```
And it works, but after logout I have redirect on the previous URL and 404 error. I have added the following on the `Startup.cs` to avoid this behavior: 
```
services.PostConfigure<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme,
                opt =>
                {
                    opt.LoginPath = "/Login";
                });
``` 

And it works. Now I have redirection on  `/Login` after logout.  But if I want change URL again I must replace two places, not one. It's uncomfortable. Is it possible from one place? I tried this: 

```
services.PostConfigure<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme,
                opt =>
                {
                    opt.LoginPath = "/Login";
                    opt.LogoutPath = "/Login";
                });
``` 
But without any effect. 
Somebody suggested me to keep login URL in the `appsettings.json` but, I think, it's nonsense. I think, `appsettings.json` is the most unexpected place for URLs. 

Any ideas?

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#17211
