### ISSUE TITLE
.NET Tutorial - Deploy a microservice to Azure, Create Azure resources

### ISSUE THREAD

**Issue by mtb1990** [dotnet/core#3824]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

From the tutorial, cmd command "az group create --name myMicroserviceResources --location westus" succeeds, but after that command "az aks create --resource-group myMicroserviceResources --name myMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys" fails with error:
"Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'. The available VM sizes are Standard_D1,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_D2,Standard_D3,Standard_D4,Standard_H16,Standard_H16m,Standard_H16mr,Standard_H16r,Standard_H8,Standard_H8m For more details, please visit https://aka.ms/cpu-quota"

I have setup and used a free azure trial account as tutorial suggested

**Comment by anandbaskaran** [comment]
I am faxing the same issue but with the different error: `The operation is not permitted for namespace 'Microsoft.ContainerService'. List of permitted provider namespaces is 'Microsoft.AlertsManagement,Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web'.`

**Comment by mairaw** [comment]
@shirhatti can you help?

**Comment by shirhatti** [comment]
I'd ask this question over on the AKS forum- https://docs.microsoft.com/answers/topics/azure-kubernetes-service.html
