### ISSUE TITLE
hello i ran into an issue with the code when i type dotnet run it says Couldn't find a project to run. Ensure a project exists in C:\Users\MD, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by hmm0920** [dotnet/core#3827]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by APossing** [comment]
From the very limited info, it would seem that you didn't CD into the WebApp directory. Check your file structure.

**Comment by mairaw** [comment]
Did you make sure you were running the command inside the myWebApp directory @hmm0920?

**Comment by mairaw** [comment]
Closing due to the lack of response.
