### ISSUE TITLE
yum install rh-dotnet30 -y You need to be root to perform this command.

### ISSUE THREAD

**Issue by ClaudiaShu** [dotnet/core#3828]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current?journey=vs-code
Operating System: Linux RHEL 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Try
```
sudo yum install rh-dotnet30 -y
```

**Comment by leecow** [comment]
Closing on the assumption that sudo solved the problem. If you're still having trouble, please reopen.
