### ISSUE TITLE
Wrong links on the .NET Core page

### ISSUE THREAD

**Issue by tLXvGt** [dotnet/core#383]
I thought I was crazy after downloading, reinstalling .NET Core 5 times and seeing 1.0.0 every time.

The link on https://www.microsoft.com/net/core#macos just under the "install .NET Core 1.1 on macOS" is serving 'dotnet-dev-osx-x64.1.0.0-preview2-1-003177.pkg' -- 1.0.0 version.

Where can I get .NET Core 1.1? I'm really interested in .csproj (XML) projects and MSBuild.

**Comment by kellah** [comment]
I believe what you're seeing is the confusion around the version of the SDK (1.0.0) as compared to the .NET runtime version (1.1.0). I have the SDK installed on macOS and this what I see:

```
$ dotnet --version
1.0.0-preview2-1-003155

$ dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
<snip>
```

**Comment by tLXvGt** [comment]
That's a great news, indeed you're right.

But why my projects are still using project.json while on Windows I created one with .csproj?

**Comment by kellah** [comment]
As far as I know runtime 1.1.0 still relies on project.json even if you create a csproj. Though I'm not the right person to provide details on that.

**Comment by Petermarcu** [comment]
Yeah, the versioning is super confusing. As far as I know, only the SDK that comes through the VS installers is updated to use csproj. I assume thats how you got it. I know the team was trying to decide when to flip the standalone SDK's for all the OS's over to the MSBuild based tooling. @piotrpMSFT , where did you guys land on that?

**Comment by Petermarcu** [comment]
Things should get cleaned up with the next release as the tooling will RTM and then next refresh of the sites and links should remove a lot of the confusion. I'm going to close this but please file an issue pointing to any additional confusion after the VS 2017 Release that will be coming out soon.
