### ISSUE TITLE
Modal popup not showing in first click in razor page

### ISSUE THREAD

**Issue by prasanthjayaprakash** [dotnet/core#3832]
Please help me  , when page is loading i can see the all list  items. But i am clicking  the more button on the first time or any the popup is not showing in  the first time.  Again will click it is working. it is  need a double click.
<button @onclick="(e=> SelectProduct(product.Id))" data-toggle="modal" data-target="#productModal"
                            class="btn btn-primary">

@if (selectedProduct != null)
{
    <div class="modal fade" id="productModal" tabindex="-1" role="dialog" aria-labelledby="productTitle" aria-hidden="true">

**Comment by scalablecory** [comment]
This issue was moved to aspnet/AspNetCore#17202
