### ISSUE TITLE
按照教程进行手动安装 还是无法安装dotnet-sdk-3.0

### ISSUE THREAD

**Issue by YouXinxing** [dotnet/core#3839]
root@abc-desktop:~# sudo apt-get install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

按照教程进行手动安装 还是无法安装dotnet-sdk-3.0

**Comment by carlossanlop** [comment]
Which instructions did you follow to add the proper repository so the package could be located?

**Comment by carlossanlop** [comment]
No response in a week. Closing.
