### ISSUE TITLE
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Users\obaid.qadri\myMicroservice\Dockerfile: The system cannot find the file specified.

### ISSUE THREAD

**Issue by obaidqadri115** [dotnet/core#3840]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Dockerfile](https://user-images.githubusercontent.com/39720771/69119390-6b62fc00-0abc-11ea-97d7-46314f4f3928.JPG)

**Comment by obaidqadri115** [comment]
https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image

**Comment by mairaw** [comment]
@shirhatti can you look at this one?

**Comment by shirhatti** [comment]
It's my understanding, that this is just a misleading error message from Docker. Please have a look at https://stackoverflow.com/a/57724377/2487788
