### ISSUE TITLE
Step 9/10 : COPY --from=build /app . COPY failed: stat /var/lib/docker/overlay2/0f5b84fa3e34dbf13893a735bd31d85a4b496111280126e161455a88a26a5c72/merged/app: no such file or directory

### ISSUE THREAD

**Issue by obaidqadri115** [dotnet/core#3843]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@obaidqadri115 Can you please provide more information about your problem? Did you follow all the steps identically or did you change anything? Can you paste the full output? Did you retry the steps to get the issue fixed?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide detail.
