### ISSUE TITLE
Entity Framework 3.0 or Entity Framework 6.4 which supports core does not have ADO.Net Entity Data Model for Data Base Approach

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/core#3844]
# Issue Title

Entity Framework 3.0 or Entity Framework 6.4 which supports core does not have ADO.Net Entity Data Model for Data Base Approach to connect with Oracle Database.

# General

Trying to use .Net Core 3.0 for webapi, in earlier .Net Framework version and with Entity Framework 5, we used have ADO.Net Entity Data Model to add EDMX for Database approach.
Now with .Net Core 3.0, when we try to use Entity Frame work 3.0  or Entity Framework 6.4 both does not have ADO.Net Entity Data Model for Database approach to connect with Oracle Database.

We are trying not to use Devart, please suggest what we can to now.

**Comment by carlossanlop** [comment]
@ajcvickers @cheenamalhotra @david-engel can you help answer this question?

**Comment by ajcvickers** [comment]
@pardhumeduri Oracle creates and ships both the EF6 and EF Core database providers. You will need to follow up with them about if and when they will have new releases available.
