### ISSUE TITLE
bash: dotnet: command not found

### ISSUE THREAD

**Issue by sunguangquan** [dotnet/core#3846]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
[happy@] ~$dotnet
-bash: dotnet: command not found
[happy@] ~$

**Comment by carlossanlop** [comment]
Did you close and reopen the command line window after installing the SDK, as the instructions stated?
Can you provide more information?

**Comment by xNarkon** [comment]
I also got this problem. This is quite strange, I just wanted to reinstall dotnet-sdk and now after successfully reinstallation via apt-get on ubuntu 19.10 there is no dotnet on the path: `/usr/share/dotnet`

`total 32K
drwxr-xr-x   6 root root 4.0K Nov 24 14:23 .
drwxr-xr-x 307 root root  12K Nov 24 14:23 ..
drwxr-xr-x   5 root root 4.0K Nov 24 14:23 packs
drwxr-xr-x   3 root root 4.0K Nov 24 14:23 sdk
drwxr-xr-x   3 root root 4.0K Nov 24 14:23 shared
drwxr-xr-x   3 root root 4.0K Nov 24 14:23 templates
`
`Sorting... Done
Full Text Search... Done
dotnet-apphost-pack-3.0/disco,now 3.0.1-1 amd64 [installed,automatic]
  Microsoft.NETCore.App.Host 3.0.1

dotnet-host/disco,now 3.0.1-1 amd64 [installed,automatic]
  Microsoft .NET Core Host - 3.0.1

dotnet-hostfxr-2.1/disco 2.1.14-1 amd64
  Microsoft .NET Core Host FX Resolver - 2.1.14 2.1.14

dotnet-hostfxr-2.2/disco 2.2.8-1 amd64
  Microsoft .NET Core Host FX Resolver - 2.2.8 2.2.8

dotnet-hostfxr-3.0/disco,now 3.0.1-1 amd64 [installed,automatic]
  Microsoft .NET Core Host FX Resolver - 3.0.1 3.0.1

dotnet-runtime-2.1/disco 2.1.14-1 amd64
  Microsoft .NET Core Runtime - 2.1.14 Microsoft.NETCore.App 2.1.14

dotnet-runtime-2.2/disco 2.2.8-1 amd64
  Microsoft .NET Core Runtime - 2.2.8 Microsoft.NETCore.App 2.2.8

dotnet-runtime-3.0/disco,now 3.0.1-1 amd64 [installed]
  Microsoft .NET Core Runtime - 3.0.1 Microsoft.NETCore.App 3.0.1

dotnet-runtime-deps-2.1/disco 2.1.14-1 amd64
  dotnet-runtime-deps-2.1 2.1.14

dotnet-runtime-deps-2.2/disco 2.2.8-1 amd64
  dotnet-runtime-deps-2.2 2.2.8

dotnet-runtime-deps-3.0/disco,now 3.0.1-1 amd64 [installed,automatic]
  dotnet-runtime-deps-3.0 3.0.1

dotnet-sdk-2.1/disco 2.1.802-1 amd64
  Microsoft .NET Core SDK 2.1.802

dotnet-sdk-2.2/disco 2.2.402-1 amd64
  Microsoft .NET Core SDK 2.2.402

dotnet-sdk-3.0/disco,now 3.0.101-1 amd64 [installed]
  Microsoft .NET Core SDK 3.0.101

dotnet-targeting-pack-3.0/disco,now 3.0.1-1 amd64 [installed]
  Microsoft.NETCore.App.Ref 3.0.1

libgtk-dotnet3.0-cil/eoan 2.99.3-3 amd64
  GTK.NET library

libgtk-dotnet3.0-cil-dev/eoan 2.99.3-3 amd64
  GTK.NET library - development files

libgtk2.0-cil/eoan 2.12.40-2 amd64
  CLI binding for the GTK+ toolkit 2.12

libgtk2.0-cil-dev/eoan 2.12.40-2 amd64
  CLI binding for the GTK+ toolkit 2.12

netstandard-targeting-pack-2.1/disco,now 2.1.0-1 amd64 [installed,automatic]
  NETStandard.Library.Ref 2.1.0

`

**Comment by carlossanlop** [comment]
What do you get if you type `whereis dotnet` ?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide detail.

**Comment by peval27** [comment]
This happened to me today, while investigating [issue 4135](https://github.com/dotnet/core/issues/4135).

I deleted all dotnet stuff on CentOS 7 (`sudo rm -rf /user/share/dotnet`) then installed the latest SDK (`sudo yum install dotnet-sdk-3.1`). Even closing/opening the Terminal doesn't help

**Comment by peval27** [comment]
wunning `whereis dotnet` I get `dotnet: /usr/bin/dotnet /usr/share/dotnet /usr/share/man/man1/dotnet.1`

**Comment by peval27** [comment]
I solved by downloading the exe and copying to `/usr/shared/dotnet`  and creating the symlink `/usr/bin/dotnet` to  `/usr/shared/dotnet/dotnet`

**Comment by dagood** [comment]
The original issue here was likely this known issue with `path_helper` being broken: https://github.com/dotnet/core-setup/issues/6521.
