### ISSUE TITLE
Enum implicit cast to string fails when element is named "ToString"

### ISSUE THREAD

**Issue by agustins** [dotnet/core#3850]
When you have an enum with an element named "ToString" compiler fails with

`"csc.exe" exited with code -2146232797. ...Bin\Roslyn\Microsoft.CSharp.Core.targets	59`

# Environment
 * .NET Core 3.0 and SDK Version 3.0.100
 * Visual Studio Enterprise 2019 Version 16.3.9

# Reproduce

``` csharp
using System;

namespace ConsoleApp
{
    class Program
    {
        public enum Foo
        {
            ToString
        }

        static void Main(string[] args)
        {
            Console.WriteLine(Foo.ToString + "");
        }
    }
}
```

**Comment by carlossanlop** [comment]
I cannot repro: I was able to build and run the app with no issues. This is a problem with something else, problably with VS or your .NET installation. If you rename the enum value to something else, and compile again, are you getting the same error? Can you paste the full error message?

**Comment by agustins** [comment]
If I rename the value to "ToString2" for example builds successfully.

The exact error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"csc.exe" exited with code -2146232797.	ConsoleApp2	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets	59	
```

**Comment by SusLes** [comment]
@carlossanlop

**Comment by scalablecory** [comment]
This issue was moved to dotnet/csharplang#3012

**Comment by scalablecory** [comment]
This issue was moved to dotnet/roslyn#40256
