### ISSUE TITLE
incorrect file size

### ISSUE THREAD

**Issue by sarapayne** [dotnet/core#3851]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-current?journey=vs-code
Operating System: 

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

Err:17 https://packages.microsoft.com/ubuntu/19.04/prod disco/main amd64 Packages
  File has unexpected size (20934 != 19614).
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by dagood** [comment]
I'm not able to reproduce the issue, can you try again? It looks like a package was uploaded close to the time you uploaded this, which I believe can cause temporary instability like this. /cc @leecow

**Comment by leecow** [comment]
Yes, I noticed it as well when I was testing last night. I presume the issue cleared up once the mirror process had completed. Going to close but please re-open if you're still having issues.
