### ISSUE TITLE
Where can I find the minimum memory requirements specification for .NET core open source?

### ISSUE THREAD

**Issue by crowdwave** [dotnet/core#386]
I've searched but I can't find any documentation specifying the memory requirements.

Can anyone suggest to me where the minimum memory requirement on Linux is specified?

**Comment by svick** [comment]
Minimum memory requirement of what? Building .Net Core (corefx, coreclr, cli, sdk, ...)? Building your own simple console or ASP.NET Core application? Running your own simple console or ASP.NET Core application?

**Comment by CodeChaser** [comment]
I came here looking for the same information.  I guess it is not documented or at the very least buried inside of another point.

**Comment by crowdwave** [comment]
@CodeChaser - I am getting the impression from the answers here and elsewhere that I have asked, that .NET core effectively takes almost no memory, thus it will work on the smallest possible RAM and CPU configurations, and the needed RAM is defined by the size of your application.

**Comment by Petermarcu** [comment]
We haven't officially doc'd it but we should. I'll look into that. It does run in very constrained environments including low end phones and pretty small IoT devices that are able to run Linux or Windows. Do you have the constraints you are dealing with?

**Comment by crowdwave** [comment]
@Petermarcu when using any new software, the first question is "how much RAM does this need?", that answers the basic question of "how small is the machine I can run this on?".

My base expectation is that .NET is some sort of big virtual machine that needs lots of memory to get going.  That's why I ask the question.

And yes I would also like to know, well just how small can the machine be that runs this?

It seems to be assumed knowledge in the community that .NET core runs on any sized RAM.

Put more succinctly: .NET core should specify the minimum hardware requirements to run it.

**Comment by CodeChaser** [comment]
Yea an Arduino ;)..   Well looks like I will be using it on a Raz PI 3 in the near future.  My goal is to see if I can get EF Core running against a SQLite db pn a PI3.   I have been using EF Core for the pass few months on a desktop, DB first.  If I remember , I believe it requires .Net Standard, so I am not sure if it is even going to work.  I need the ability use a SQL based DB such as SQLite the results of my decision tree's, as in realtime ML results.
