### ISSUE TITLE
There isn't ValuesController.cs

### ISSUE THREAD

**Issue by durandv** [dotnet/core#3869]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
@durandv you can find that file as Controllers/WeatherForecastController.cs -- thanks for reporting this.

@rowanmiller it looks like the tutorial has an incorrect file name on the code panel.

**Comment by rowanmiller** [comment]
@durandv many thanks for reporting this. The page has been updated.

![image](https://user-images.githubusercontent.com/4741851/69290677-882f2a80-0bb5-11ea-8b7c-f63da623d6bc.png)
