### ISSUE TITLE
I am getting error saying package not available

### ISSUE THREAD

**Issue by dpanchal-visuallease** [dotnet/core#3870]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-3.0.101
Operating System: 

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
A few questions:
* Which distro did you select in the dropdown?
* What linux distro are you running?
* What type of device are you using? (Raspberry Pi, for example, or ordinary desktop computer?) 

Please also paste the commands you ran and their output here.

**Comment by dpanchal-visuallease** [comment]
Following commands were working fine via packer (since today morning), and it suddenly started failing.

{
           "execute_command": "echo 'ec2-user' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
           "type": "shell",
           "inline": [
               "rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm",
               "yum update",
               "yum install -y apt-transport-https",
               "yum update",
               "yum install -y aspnetcore-runtime-3.0.1",
               "yum install -y dotnet-sdk-3.0.1",
               "yum install -y curl"
           ]
       },

**Comment by dagood** [comment]
What are the errors, and what's the output of the commands? What type of machine is this and what Linux distro does it run?

There are some issues in general with the RPM package repos right now that might be related (https://github.com/dotnet/core/issues/3853) but there isn't enough info to tell yet.

**Comment by devintrack** [comment]
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================
 Package                                               Arch                          Version                          Repository      
======================================================================================================================================
Installing:
 dotnet-sdk-3.0                                        x86_64                        3.0.101-1                        packages-microso
Installing for dependencies:
 aspnetcore-runtime-3.0                                x86_64                        3.0.1-1                          packages-microso
 aspnetcore-targeting-pack-3.0                         x86_64                        3.0.1-1                          packages-microso
 dotnet-apphost-pack-3.0                               x86_64                        3.0.1-1                          packages-microso
 dotnet-host                                           x86_64                        3.0.1-1                          packages-microso
 dotnet-hostfxr-3.0                                    x86_64                        3.0.1-1                          packages-microso
 dotnet-runtime-3.0                                    x86_64                        3.0.1-1                          packages-microso
 dotnet-runtime-deps-3.0                               x86_64                        3.0.1-1                          packages-microso
 dotnet-targeting-pack-3.0                             x86_64                        3.0.1-1                          packages-microso
 netstandard-targeting-pack-2.1                        x86_64                        2.1.0-1                          packages-microso

Transaction Summary
======================================================================================================================================
Install  1 Package (+9 Dependent packages)

Total size: 107 M
Total download size: 2.1 M
Installed size: 107 M
Is this ok [y/d/N]: y
Downloading packages:
netstandard-targeting-pack-2.1 FAILED                                          
https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended downckages-microsoft-com-prod clean metadata
Trying other mirror.

**Comment by dagood** [comment]
@devintrack, that would be https://github.com/dotnet/core/issues/3853, based on `[Errno -1] Package does not match intended downckages-microsoft-com-prod`, although the log line appears to have been messed up a little bit.

Leaving open to wait for a response from @dpanchal-visuallease.

**Comment by dagood** [comment]
Looking at this again, I don't understand how these lines could have worked before:

>                "yum install -y aspnetcore-runtime-3.0.1",
>                "yum install -y dotnet-sdk-3.0.1",

These packages don't exist, for a few reasons:
1. "3.0.1" is not an SDK version, you're looking for "3.0.101". See https://dotnet.microsoft.com/download/dotnet-core/3.0
2. We only create package names `aspnetcore-runtime-3.0` and `dotnet-sdk-3.0`, the patch version isn't included. By installing one of those, you get the latest version of that package.

If you really want to specify a specific version, the syntax to do that with an RPM package manager like `yum` would be `yum install dotnet-sdk-3.0-3.0.101`. In that case, the package name is `dotnet-sdk-3.0` and its version is `3.0.101`.

(Also, a side note: you don't need to install both `aspnetcore-runtime` and `dotnet-sdk`. The SDK includes the runtime.)

**Comment by dpanchal-visuallease** [comment]
I am using circleCI pipeline, using dotnet/core 3.0
Mostly my PC has Ubuntu 18.4 installed.

docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:3.0<http://mcr.microsoft.com/dotnet/core/sdk:3.0>

**Comment by oppakjt** [comment]
i have same issue.
[Info]
[root@localhost excon]# dotnet --info
.NET Core SDK(global.json 반영):
 Version:   3.0.101
 Commit:    bc5f8df0f5

런타임 환경:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  2.0.0 [/usr/share/dotnet/sdk]
  2.0.2 [/usr/share/dotnet/sdk]
  2.0.3 [/usr/share/dotnet/sdk]
  2.1.2 [/usr/share/dotnet/sdk]
  2.1.3 [/usr/share/dotnet/sdk]
  2.1.4 [/usr/share/dotnet/sdk]
  2.1.101 [/usr/share/dotnet/sdk]
  2.1.103 [/usr/share/dotnet/sdk]
  2.1.104 [/usr/share/dotnet/sdk]
  2.1.105 [/usr/share/dotnet/sdk]
  2.1.200 [/usr/share/dotnet/sdk]
  2.1.201 [/usr/share/dotnet/sdk]
  2.1.202 [/usr/share/dotnet/sdk]
  2.1.300-preview2-008530 [/usr/share/dotnet/sdk]
  2.1.300-preview2-008533 [/usr/share/dotnet/sdk]
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

------
[Error]
[root@localhost excon]# dotnet run
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018: "ResolveTargetingPackAssets" 작업에서 예기치 않은 오류가 발생했습니다. [/home/brandon/01.Work/excon/excon.csproj]
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018: System.IO.FileNotFoundException: Could not find file '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.0.0/data/FrameworkList.xml'. [/home/brandon/01.Work/excon/excon.csproj]
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018: File name: '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.0.0/data/FrameworkList.xml' [/home/brandon/01.Work/excon/excon.csproj]
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) [/home/brandon/01.Work/excon/excon.csproj]
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) [/home/brandon/01.Work/excon/excon.csproj]
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) [/home/brandon/01.Work/excon/excon.csproj]
...
...
...
...
/usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/brandon/01.Work/excon/excon.csproj]

**Comment by mdx0111** [comment]
The same issue is happening here on Fedora 31.

The first issue which is already reported is the mismatch between the checksum of the "netstandard-targeting-pack-2.1-2.1.0-1.x86_64". I have downloaded the rpm package for that and installed it through command line.

Then I updated the .Net Core which updated the Asp.Net Core runtime and SDK as well. I have also removed all the .Net Core versions and just install version 3.0.101 through the following command:

`sudo dnf install dotnet-sdk-3.0`

Then I created a web app using the following command:

`dotnet new web`

Then in the root folder of my test project ran the following command:

```
dotnet build
dotnet run
```

Even though dotnet build runs correctly and compiles the project, dotnet run returns the following message:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

The following shows my dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
The only way to get my project run is by installing ASP.NET Core Runtime 3.0.0 through the following command:

`sudo dnf install aspnetcore-runtime-3.0-3.0.0-1`

Please do not hesitate to let me know if you need any further details to investigate this.

Many thanks.

**Comment by dagood** [comment]
@dpanchal-visuallease I don't understand, can you please show the error and describe when it happens? Are you trying to install on your machine, some other machine, or use that Docker image? 

---

@oppakjt That issue looks very different to me... like a corrupted install. I would suggest verifying the install, or reinstalling, then open a new issue if you have problems.

@mdx0111 That's also quite different, that's a known problem tracked by https://github.com/dotnet/core/issues/3863.

**Comment by mdx0111** [comment]
> @dpanchal-visuallease I don't understand, can you please show the error and describe when it happens? Are you trying to install on your machine, some other machine, or use that Docker image?
> 
> @oppakjt That issue looks very different to me... like a corrupted install. I would suggest verifying the install, or reinstalling, then open a new issue if you have problems.
> 
> @mdx0111 That's also quite different, that's a known problem tracked by #3863.

Yes, I understand that; hence, stating that it's already reported but the rest of the information and details that I have provided are related to the issue originally reported here.

**Comment by dagood** [comment]
> Yes, I understand that; hence, stating that it's already reported but the rest of the information and details that I have provided are related to the issue originally reported here.

I'm sorry, I'm missing how it relates to the original issue here. There isn't much to go on yet. Can you give more context why you think they're connected? I'm trying to keep this issue focused if I can.

**Comment by mdx0111** [comment]
AAh! My mistake! Sorry, got confused by the title. I'll open another issue for what I'm experiencing.

Many thanks and apologies again for the confusion.

**Comment by dpanchal-visuallease** [comment]
Good morning,

Culprit  is the MIRROR, it did work once, but then it’s been failing all the times.,

amazon-ebs: netstandard-targeting-pack-2.1 FAILED
amazon-ebs: https://packages.microsoft.com/rhel/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
amazon-ebs: Trying other mirror.
amazon-ebs: (4/5): dotnet-sdk-3.0.101-x64.rpm

Did you try installing it (dotnet-sdk-3.0.101) manually?

Thanks,
Dinesh

**Comment by dagood** [comment]
Thanks for posting the logs @dpanchal-visuallease, that is a known issue with the RPM feeds that hasn't been resolved yet: https://github.com/dotnet/core/issues/3853.

In the meantime, you can work around this by manually installing netstandard-targeting-pack-2.1 before the SDK, ignoring the "package does not match intended download" check. Details at https://github.com/dotnet/core/issues/3853#issuecomment-556036495.

**Comment by dpanchal-visuallease** [comment]
AWS kindly replied and it did install dotnet 3.0.101, hopefully it will fix my issue.



These are the commands that worked for me:



                $ sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm

                $ sudo yum install dotnet-runtime-3.0 -y



This installed .Net 3.0. runtime. I run these command within the Packer builder template and I was able to create a RHEL7-based AMI pre-backed with .Net 3.0 runtime.



To install the .Net SDK as well, I needed to run these commands:



                $ sudo rpm -Uvh https://packages.microsoft.com/rhel/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm

                # This is a required dependency that yum is unable to find in the its repositories so they need to be manually installed.



                $ sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm

                $ sudo yum install dotnet-runtime-3.0 -y

                $ sudo yum install dotnet-sdk-3.0 -y

**Comment by dagood** [comment]
Good to hear! That is indeed the workaround recommended at https://github.com/dotnet/core/issues/3853#issuecomment-556036495, so agreed, it should work around the current problem with the linux repo.
