### ISSUE TITLE
Missing packages for Fedora 31

### ISSUE THREAD

**Issue by ShaihutdinovRZ** [dotnet/core#3876]
What about NET Core 3 packages for Fedora 31 in https://packages.microsoft.com/fedora/ ?

**Comment by mdx0111** [comment]
You can use the packages for Fedora 30. They should work without any problem.

**Comment by ShaihutdinovRZ** [comment]
They should work or exactly work without any problem? There is any succesfull use case of packages from Fedora 30 in Fedora 31? Or is it just a guess?

**Comment by mdx0111** [comment]
I'm on Fedora 31 and have installed the SDK for .Net Core 3 using the packages for Fedora 30. However, currently there are few issues in regards to the RPM packages which they are being looked at. Please see #3870 and #3853 and #3867.

**Comment by dagood** [comment]
Yeah, when there aren't instructions on https://dotnet.microsoft.com/download for your distro and your distro is listed as supported (https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md for 3.0), then you can expect the nearest instructions to work. Then if they don't, go ahead and file an issue. We have https://github.com/dotnet/core/issues/2576 tracking getting better at listing distros to avoid the confusion here.

Thanks for confirming it worked for you and linking to the known issues, @mdx0111.

**Comment by omajid** [comment]
The Fedora .NET SIG builds .NET Core for Fedora 31, if you want to try that out: https://developer.fedoraproject.org/tech/languages/csharp/dotnet-installation.html

**Comment by murbanowicz** [comment]
@omajid I have installed using those instructions but even if I see sdk in install logs, dotnet does not list any SDK installed :/

**Comment by omajid** [comment]
@murbanowicz Sorry to hear that. Can you share more information? Can you do an `rpm -qa | grep dotnet`? `dnf list installed '*dotnet*'`? Output of `dotnet --info` would be nice to have too.

My prime suspect is a mix of packages. The Fedora .NET SIG packages and the Microsoft packages dont play nice with each other. I would completely remove dotnet packages, disable the the repo you dont want to use, and re-install `dotnet-sdk-3.0`.

**Comment by murbanowicz** [comment]
which one repo should I disable then?

**Comment by omajid** [comment]
If you want to try the Fedora .NET SIG packages, disable the Microsoft repo. Remove .NET Core. Then add the Fedora .NET SIG repo and install the .NET Core packages.

If (or when) you want to try the Microsoft repo, disable the Fedora .NET SIG repo and uninstall .NET Core packages. Then add/enable the microsoft repo and install the packages from there.
