### ISSUE TITLE
aspnetcore-runtime-2.2 shows in index but seems to be missing from repo

### ISSUE THREAD

**Issue by jgerry** [dotnet/core#3882]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-aspnetcore-2.2.8
Operating System: 

Centos 7

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

aspnetcore-runtime-2.2.8 seems to be missing from the repo. `yum search aspnet` returns `aspnetcore-runtime-2.2.x86_64 : Microsoft ASP.NET Core 2.2.8 Shared Framework` but

`yum install aspnetcore-runtime-2.2` returns `aspnetcore-runtime-2.2.8-rh.rh FAILED
https://packages.microsoft.com/rhel/7/prod/aspnetcore-runtime-2.2.8-rh.rhel.7-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found`

**Comment by brockallen** [comment]
dup? https://github.com/dotnet/core/issues/3863

**Comment by jgerry** [comment]
Yeah looks like I didn't search thoroughly enough. My bad, I'll close the issue as a dup.
