### ISSUE TITLE
AddAuthorization Add Policies Need Clarification Please

### ISSUE THREAD

**Issue by cgountanis** [dotnet/core#3883]
Upgraded to Core 3 and in the past releases (1-2) you had to pre-define the policy names in StartUp AddAuthorization > Options aka AuthorizationOptions before you could use in controller annotation `[Authorize(Roles = "Utilities_Navigation")]`. It would seem now that are dynamically found?

I spent time converting my old:
```
...
scopeFactory = services.BuildServiceProvider().GetRequiredService<IServiceScopeFactory>()
...DbContext Get Data...
options.AddPolicy(item.Name, policy => policy.RequireRole(item.Name));
...
```

to the new improved:
```
...
services.AddSingleton<IConfigureOptions<AuthorizationOptions>, ConfigureAuthorizationOptions>();
...
ConfigureAuthorizationOptions(IServiceScopeFactory serviceScopeFactory)
...
```

Can someone explain if this is even needed anymore?

**Comment by cgountanis** [comment]
Just need confirmation on this, we used to get an error when using the `[Authorize(Roles = "Utilities_Navigation")]` on a controller if it was NOT added to the `AddAuthorization(options => options.AddPolicy...` from StartUp, now it would seem it is able to grab those from the code and set all that up automatically which is cool, but I want to confirm is all, before I scrap unneeded code.

Hoping this is the correct place to ask.

**Comment by scalablecory** [comment]
@Pilchie can you help here?

**Comment by cgountanis** [comment]
Seems to be working. Don't really have any issues no reason to keep this open.
