### ISSUE TITLE
 i install  NVIDIA's docker and i got error:  gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by chenlei1234321** [dotnet/core#3884]
# Issue Title

 error:  gpg: no valid OpenPGP data found.

# General

when i setup GPU for tensorflow in google cloud, i install  NVIDIA's docker.My code is as follows:

curl -s -L https://nvidia.github.io/nvidia-docke... | sudo apt-key add - \
    && curl -s -L "https://nvidia.github.io/nvidia-docke.... /etc/os-release; echo $ID$VERSION_ID)/nvidia-docker.list" \
    | sudo tee /etc/apt/sources.list.d/nvidia-docker.list \
    && sudo apt-get update \
    && sudo apt-get install -y nvidia-docker2 \
    && sudo pkill -SIGKILL dockerd
But i got an error just like this:
gpg: no valid OpenPGP data found.

how should i to fix it?thx

**Comment by scalablecory** [comment]
Are you installing this as part of a .NET Core tutorial?

https://github.com/NVIDIA/nvidia-docker may be a more appropriate project to file an issue under, as it does not appear you are using any .NET tools based on those commands.

**Comment by scalablecory** [comment]
Closing due to lack of response; please reopen if you're still having the issue and can provide additional details specific to .NET Core.
