### ISSUE TITLE
fedora 31

### ISSUE THREAD

**Issue by akghasemi** [dotnet/core#3888]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-current
Operating System: 

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by akghasemi** [comment]
I am trying to install .net core 3 sdk on Fedora 31 with package manager but I receive these errors
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[FAILED] netstandard-targeting-pack-2.1.0-x64.rpm: No more mirrors to try - All mirrors were already tried without success                                              
(10/10): dotnet-sdk-3.0.101-x64.rpm                               49% [===============================                                 ] 357 kB/s |  53 MB     02:36 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download netstandard-targeting-pack-2.1.0-x64.rpm: All mirrors were tried

**Comment by dagood** [comment]
You're running into this problem that we're working on fixing: https://github.com/dotnet/core/issues/3853. There are workarounds listed in that thread, specifically this comment: https://github.com/dotnet/core/issues/3853#issuecomment-556036495.
