### ISSUE TITLE
ASP.NET Core Runtime 3.0.1 broke production linux machine

### ISSUE THREAD

**Issue by for7raid** [dotnet/core#3890]
# ASP.NET Core Runtime 3.0.1 broke production linux machine

App does not start with ASP.NET Core Runtime 3.0.1

# General

On my linux machine was installed 
ASP.NET Core Runtime 3.0.0 wiht SDK 3.0.101
`dotnet --info` shows next:
```
.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

today I updated packages with `yum update` command
and now
```
.NET Core runtimes installed:
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
I have only one runtime and my application doesn't want to run, tries find runtime, but cant.

Why the same yum package `yum install aspnetcore-runtime-3.0` in minor version update does not contains needed runtimes?
Why minor version has braking changes and there is not any notes and issues at release notes?

I manually changed file `*.runtimeconfig.json` from `Microsoft.AspNetCore.App 3.0.0` to `Microsoft.NETCore.App 3.0.1`, app started, but crashed on loading assembly dependencies.

I had to downgrade packages to get app working.
`yum downgrade aspnetcore-runtime-3.0-3.0.0-1.x86_64`

# System info
OS LINUX X64 Linux 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 Cent OS 7
.NET Core 3.0.1

**Comment by leecow** [comment]
@for7raid, we'll need some information to try and determine what may be going on. Adding @anurse to ask the clarifying questions.

**Comment by dagood** [comment]
This is a known issue: https://github.com/dotnet/core/issues/3886. Two `aspnetcore-runtime-3.0-3.0.1` packages were uploaded to the repo, and the repo ended up serving the wrong one. The workaround I listed at https://github.com/dotnet/core/issues/3886#issuecomment-557312983 should work for you as-is because you're on CentOS 7.

**Comment by dagood** [comment]
The install instructions actually work for me in a fresh CentOS 7 Docker container at the moment, so it's possible all you have to do is upgrade `aspnetcore-runtime-3.0` back up. (You may also need to `yum clean packages` before the upgrade to get rid of a cache of the old/bad package. Apologies, I don't know for sure when that's necessary.)
