### ISSUE TITLE
Can't install Arm64 package from aptitude on Debian 10

### ISSUE THREAD

**Issue by SylvainDevidal** [dotnet/core#3892]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-current
Operating System: Linux - Debian 10 - x64

Hello,

I found ASP.NET Core  3.0 is released for Arm64 and should be compatible with Debian 10

I'm trying to install it on my "Freebox" (interne box from the french ISP "Free") but aspnetcore-runtime-3.0 and dotnet-runtime-3.0 are not found.

Here are all the command I executer :

freebox@drive:$ wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
freebox@drive:$ sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
freebox@drive:$ wget -q https://packages.microsoft.com/config/debian/10/prod.list
freebox@drive:$ sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
freebox@drive:$ sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
freebox@drive:$ sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
freebox@drive:$ sudo apt-get update
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Get:5 https://packages.microsoft.com/debian/10/prod buster InRelease [29.8 kB]
Get:6 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages [16.6 kB]
Get:7 https://packages.microsoft.com/debian/10/prod buster/main all Packages [556 B]
Get:8 https://packages.microsoft.com/debian/10/prod buster/main arm64 Packages [556 B]
Get:9 https://packages.microsoft.com/debian/10/prod buster/main armhf Packages [556 B]
Fetched 144 kB in 2s (88.9 kB/s)
Reading package lists... Done
freebox@drive:$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 149 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main arm64 apt-transport-https all 1.8.2 [149 kB]
Fetched 149 kB in 0s (394 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 40882 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2_all.deb ...
Unpacking apt-transport-https (1.8.2) ...
Setting up apt-transport-https (1.8.2) …
freebox@drive:$ sudo apt-get install aspnetcore-runtime-3.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package aspnetcore-runtime-3.0
E: Couldn't find any package by glob 'aspnetcore-runtime-3.0'
E: Couldn't find any package by regex 'aspnetcore-runtime-3.0'
freebox@drive:$ sudo apt-get install dotnet-runtime-3.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-runtime-3.0
E: Couldn't find any package by glob 'dotnet-runtime-3.0'
E: Couldn't find any package by regex 'dotnet-runtime-3.0'
freebox@drive:$ hostnamectl
   Static hostname: drive
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 0559478f56ee4a33987041091e6adf81
           Boot ID: 52b4f54d33a74ca0bb9700e12f084b9f
    Virtualization: kvm
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-6-arm64
      Architecture: arm64
freebox@drive:$

**Comment by leecow** [comment]
We do not yet produce or publish ARM installer packages. You can use either [dotnet-install.sh](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) or manually [install from tar.gz](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#installation-from-a-binary-archive).

**Comment by scalablecory** [comment]
Looks like this was answered. Manual install instructions are here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#manual-install

Closing out, thanks.
