### ISSUE TITLE
Publish AddRazorRuntimeCompilation > Microsoft.CodeAnalysis.resources.dll

### ISSUE THREAD

**Issue by cgountanis** [dotnet/core#3895]
I found that when I publish my Core 3+ MVC projects and you have .AddRazorRuntimeCompilation() enabled you get a dozen folders with Microsoft.CodeAnalysis.resources.dll files. I think this is a bug.

`    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.X.X" />`

Is there a solution for this? I mean I really like the ability to edit cshtml/save and refresh to get the instant changes.

![image](https://user-images.githubusercontent.com/14899817/69469391-37a30300-0d56-11ea-8a21-3d3cd672b636.png)

**Comment by cgountanis** [comment]
Any thoughts? Am I just missing something?

**Comment by cgountanis** [comment]
Maybe this will be fixed or addressed in 3.0.2+?, unless there is a better way to do it, not blowing up the publish file count with debug files?

**Comment by cgountanis** [comment]
Still an issue with 3.1 LTS, just wanted to test and see if there was a work-around for on the fly CSHTML editing without the AddRazorRuntimeCompilation()/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation? Right now ever publish I have to remove that package ref and tweak the Startup.cs to Release build and not get all those debug files in my Folder publish.

**Comment by cgountanis** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/16028

I can confirm with the settings above, might be slightly different for various setups, MVC/Pages/Blazor but overall the Publish - Configuration: Release, now does NOT include all those debug files in the published file output.

I still think there has to be an easier way down the road but for now, this does work.

Thank you!

**Comment by cgountanis** [comment]
Maybe something under Startup Configure // Environmental options.

**Comment by scalablecory** [comment]
CC @Pilchie

**Comment by Pilchie** [comment]
This is https://github.com/aspnet/AspNetCore/issues/15255 (and transitively https://github.com/dotnet/roslyn/issues/39458)
