### ISSUE TITLE
Dot net core for Ubuntu 18.04

### ISSUE THREAD

**Issue by mhassan4641** [dotnet/core#3896]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-aspnetcore-2.0.9
Operating System: Linux - Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
This issue does not have a description of a problem, either in the title or in the issue description, so I'm closing it.
If you can provide details of a problem, feel free to reopen.
