### ISSUE TITLE
Couldn't find a project to run. Ensure a project exists in C:\Users\User, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by Nortyboy1983** [dotnet/core#3899]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Are you running dotnet within the folder of your project?

**Comment by carlossanlop** [comment]
No response in 19 days. Closing.

**Comment by Gabbyog-cloud** [comment]
Couldn't find a project to run. Ensure a project exists in C:\Users\User, or pass the path to the project using --project. currently having this issue on my mac
kindly help

**Comment by Jozkee** [comment]
@Gabbyog-cloud take a look at https://stackoverflow.com/a/56775533/4231460. Sounds like you don't have a .csproj file. If that's not the case, please file a new issue, don't seek help on closed issues since they are rarely looked at by the repo maintainers.
