### ISSUE TITLE
System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by alexeycalinovski** [dotnet/core#39]
I have managed to install and run *dnu restore* on openSUSE 13.2 as detailed in [#37](https://github.com/dotnet/core/issues/37). The problem is that I am getting the following error whenever I try and run the above command : 

    System.Net.Http.HttpRequestException: An error occurred while sending the request. --->    System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates

It seems to be an issue of curl not having the CA bundle, but the *curl* command works just fine for HTTPS.

	curl --version
	curl 7.46.1-DEV (x86_64-suse-linux-gnu) libcurl/7.46.1-DEV GnuTLS/3.5.0 zlib/1.2.8
	Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
	Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

I have also seen this [wcf#438](https://github.com/dotnet/wcf/issues/438). What is the status of this issue?

**Comment by roncain** [comment]
@iamjasonp -- can you add any info regarding the WCF issues showing this same error?
/cc @alexeycalinovski

**Comment by iamjasonp** [comment]
We've been seeing this in WCF Core when running tests. The errors look like the following: 

```
 Exception: System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
         at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, CURLcode messageResult)
```

We're investigating this on our end. I've tried to import the root CA cert for the WCF Bridge (test) component but so far it hasn't resolved the issue
