### ISSUE TITLE
ASP.NET Core 3.0 console app on Ubuntu: Cannot find dll

### ISSUE THREAD

**Issue by Oleg26Dev** [dotnet/core#3900]
I have created a small ASP.NET Core 3.0 self-contained app console in VS2019. 
It is Kestrel-based web server.
Build for Windows - it works. But when publish for linux, copy and run it in linux then I receive:

> The specified framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.

Check the files: really, no this file in the directory.
I have tried to add a NuGet package Microsoft.AspNetCore.App but it cannot be added because it requires NET Core <=2.2.

What need to correct?

**Comment by mihaibanu** [comment]
I had the same issue. Make sure you're compiling with the same SDK version as you have for the runtime. I haven't tried with 3.0.101 as the only compiler available to me is 3.0.0

**Comment by Oleg26Dev** [comment]
I have solved the issue this way: 
1. I have installed the VS 2019 Update 
2. Installed the 3.1
3. Rebuilt the project.
After these actions it works and does not require any Microsoft.AspNetCore.App dll.
It looks like a bug in VS2019.

**Comment by carlossanlop** [comment]
Seems that the issue got resolved. @Oleg26Dev if you can confirm there is a bug with Visual Studio, please report the issue using [the "Report a problem" feature](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
Closing.
