### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by AbdulazizCyber** [dotnet/core#3903]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-current
Operating System: Linux - RHEL 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Neither the title nor the descripbion of the issue contain information about a problem. Closing.
