### ISSUE TITLE
When I Deploy the asp.net core 3.0 App to windows server 2012 R2，the all of IIS website are stopped？

### ISSUE THREAD

**Issue by jesen20160925** [dotnet/core#3904]
as the title says，anybody can help me ? thanks!

**Comment by Pilchie** [comment]
How are you doing the deployment?

**Comment by jesen20160925** [comment]
I installed dotnet-hosting-3.0.1-win.exe on Windows Server 2012 R2, and publish the website on IIS, and set the application pool without managed code.  and then the .net core website can run,but all of the asp.net website are can not be running,when I start them and access , they are stopped.

**Comment by Pilchie** [comment]
@anurse @jkotalik @joeloff ideas on where this should be?

**Comment by joeloff** [comment]
This sounds like an IIS/ANCM issue to me, but it's possible it could just be a configuration issue causing the app pools to maybe become disabled. I'm not an IIS expert, so I'd defer to @jkotalik to ask the right questions.

**Comment by jesen20160925** [comment]
OK,Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jacques Eloff"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 凌晨1:50
收件人:&nbsp;"dotnet/core"<core@noreply.github.com&gt;;
抄送:&nbsp;"jesen"<237745378@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnet/core] When I Deploy the asp.net core 3.0 App to windows server 2012 R2，the all of IIS website are stopped？ (#3904)




This sounds like an IIS/ANCM issue to me, but it's possible it could just be a configuration issue causing the app pools to maybe become disabled. I'm not an IIS expert, so I'd defer to @jkotalik to ask the right questions.

**Comment by jesen20160925** [comment]
I uninstalled dotnet-hosting-3.0.1-win.exe and installed the dotnet-hosting-3.0.0-win.exe on my server,it runs well,does the 3.0.1 version not support the windows server 2012 R2?

**Comment by Pilchie** [comment]
This issue was moved to aspnet/AspNetCore#17498
