### ISSUE TITLE
How can install preview version of SDKs in linux using command line

### ISSUE THREAD

**Issue by kmuthukumar23** [dotnet/core#3905]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-current
Operating System: Linux - RHEL 7 - x64

Is there any ways to install the preview versions of .Net Core SDKs in linux machine using command line?

I want to install the .net core 3.1 preview 3 in linux machine using command line. like below

> sudo apt-get update

> sudo apt-get install apt-transport-https

> sudo apt-get update

> sudo apt-get install dotnet-sdk-3.0

Above Command used to install the SDK 3.0 in linux. Now i want to install latest .net core 3.1 preview 3 by the same way.

Can any one please help me on this?

**Comment by dagood** [comment]
We don't provide preview RPM/Debian packages on the feeds yet, this is tracked by https://github.com/dotnet/core-setup/issues/4709 for the future.

You can use one of the other methods to install from the command line, though: [linux-setup.md](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md), also [`dotnet-install.sh`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).
