### ISSUE TITLE
command prompt

### ISSUE THREAD

**Issue by hela-benamor** [dotnet/core#3906]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by SimonCropp** [comment]
@hela-benamor did you forget to include the details of your problem?

**Comment by scalablecory** [comment]
Closing out; please feel free to reopen if you're still having an issue and can provide more detail.
