### ISSUE TITLE
Ubuntu 19.04 fresh install - 'N/A' is not a valid version string

### ISSUE THREAD

**Issue by jbenguira** [dotnet/core#3909]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-3.0.100
Operating System: Linux - Ubuntu 19.04 - x64

Installation is working as expected, but once installed when I run "dotnet run" inside the web template folder I get this error: 

root@backups ~/dotproj/web # dotnet run
/root/dotnet/sdk/3.0.101/NuGet.targets(123,5): error : 'N/A' is not a valid version string. (Parameter 'value') [/root/dotproj/web/web.csproj]
The build failed. Fix the build errors and run again.

**Comment by dagood** [comment]
I'm not able to repro in a fresh Ubuntu 19.04 Docker container. I do see some interesting tidbits in there, though:

https:\/\/dotnet.microsoft.com/download/linux-package-manager/sdk-**3.0.100**
vs.
/**root/dotnet**/sdk/**3.0.101**/
vs. the expected value (and what I end up with in my container):
/**usr/share/dotnet**/sdk/**3.0.100**/

The `/root/dotnet` part suggests you might have a manual install already on your machine, that's taking over from the 3.0.100 you tried to install. Can you try removing it (maybe just from `PATH` temporarily)?

Also, the link you have is 3.0.100, but the latest version is currently 3.0.101, which you should use instead. Starting from https://dotnet.microsoft.com/download should get you in the right place (even in the future when 3.0.102+ are released).

**Comment by jbenguira** [comment]
Indeed at some point I installed manually from the binary to make some tests.
I have reverted that and cleaned my PATH

After That I have reinstalled with instructions for ubuntu 19.04 from here: https://dotnet.microsoft.com/download

here is now result of "dotnet --info":
root@backups ~ # dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

And now after running "dotnet run" in the web sample folder:

root@backups ~/dotproj/web # dotnet run
/usr/share/dotnet/sdk/3.0.101/NuGet.targets(123,5): error : 'N/A' is not a valid version string. (Parameter 'value') [/root/dotproj/web/web.csproj]
The build failed. Fix the build errors and run again.

It seems the binary is not the culprit ...

Here is the content of the web.csproj file:
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
</Project>

It seems perfectly fine and the same template project works well on another VM with Ubuntu 18.04

**Comment by dagood** [comment]
Do you maybe have a `version` environment variable set? There are some issues in the NuGet repo that suggest it might be where "N/A" is coming from. Similar errors, with different values:

https://github.com/NuGet/Home/issues/8794
https://github.com/NuGet/Home/issues/7194
https://github.com/NuGet/Home/issues/6154
https://github.com/NuGet/Home/issues/5614
https://github.com/NuGet/Home/issues/5295

**Comment by jbenguira** [comment]
This was it! Thank you so much :)

I fixed it with this command:
`unset version`

**Comment by dagood** [comment]
Sweet, glad that was it. 😄 Thanks for confirming, closing as resolved. (With https://github.com/NuGet/Home/issues/8794 being the most recent request that maybe having a `version` env var shouldn't cause something as hard to diagnose as this.)
