### ISSUE TITLE
.NET Core 1.0.3

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/core#391]
Thanks for your interest in .NET Core. 

You can read about .NET Core 1.0.3 in the announcement: [December 2016 Updates for .NET Core 1.0](https://blogs.msdn.microsoft.com/dotnet/2016/12/13/december-2016-update-net-core-1-0)

Please report any issues you find with .NET Core 1.0.3 here, either responding to this issue or creating a new issue.

Please include the following information plus any other info that you think is relevant:

OS version
Repro steps
Repro code (if you can share it / is relevant)
Error messages
Whether this worked before
Method of installing .NET Core

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

**Comment by bgribaudo** [comment]
Thanks for all the hard work you've put into this new version!

When I go to https://www.microsoft.com/net/download/core/#/runtime and download then launch [.Net Core 1.0.3 SDK - Installer, Windows x64](https://go.microsoft.com/fwlink/?LinkID=836281), the installer indicates that it's installing _Microsoft .Net Core 1.0.3 - SDK 1.0.0. Preview 2-003156_. 

Is the SDK a preview release?

**Comment by Petermarcu** [comment]
@bgribaudo, yes, the runtime is RTM but the sdk tooling is still in preview.

**Comment by bgribaudo** [comment]
Thanks, @Petermarcu!

**Comment by bgribaudo** [comment]
Hi @kendrahavens! In your https://blogs.msdn.microsoft.com/dotnet/2016/12/13/december-2016-update-net-core-1-0/ post, the 'see the .NET Core 1.0.3 release notes' link points to the [ASP.Net Core 1.0.3 release notes](https://github.com/aspnet/Home/releases/tag/1.0.3). Did you mean to instead link to https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.3.md?

**Comment by kendrahavens** [comment]
@bgribaudo Yes, I did! Thank you for the catch!

**Comment by enricosada** [comment]
@kendrahavens it's possible to update the blog post to add some info about f# changes too? We do some work and that is committed inside `dotnet/cli` (the sdk), so is nice if we can show that release notes too.

In this sdk update we aligned all the `dotnet new` F# templates to c#. So OOTB `dotnet new -l fsharp -t web` works now (also `console`/`lib`/`xunittest`)

**Comment by kendrahavens** [comment]
@enricosada I pulled in @cartermp to help me with the update. Posted!

@enricosada I'm not sure if I'm doing the preview4 blog post, but I know who will be. Can you email me? ke havens @ microsoft. com (Added spaces to avoid spam).

**Comment by enricosada** [comment]
@kendrahavens seen the updated blog! thx a lot! @cartermp you too!

**Comment by replete** [comment]
Is there anywhere that explains the current scheme for versioning/naming across the board?

I've dipped in and out of this stuff over the last year, and it's always difficult to figure out what the latest version of x is and how version numbers relate to each other. e.g. now their's tools, CLI, framework, clr?

**Comment by kendrahavens** [comment]
@replete I'm building a table of this information and I'll post it here as well as docs.msft.com. You are definitely not the only one with this issue.

**Comment by replete** [comment]
That's great until you guys change it all again. 

Where are the templates? I've done dotnet new - now what? How do I use WebAPI? There are no answers. Templates are out of date. Code repo samples are out of date.

I installed the SDK on OSX, and get a load of symbol missing errors on debug, and no idea how to get started with packages (plus resolving issues, finding AspNet but not AspNetCore). I checked the doc site (missing stuff from the old one) and find no answers. 

The MVC repo had a samples folder, but it referenced 'dnxcore50' - ancient!

It was frustrating when I invested my time learning RC1 for my app (let's be honest, it was alpha not an RC). Now it's ridiculous that I'm struggling so much at 1.1.

I guess the people doing stuff all use visual studio

It's mostly there, can someone just sit down, think what a new user would want to do, and put some instructions together?

In 15 minutes I'm writing an API in node.js. Install packages. Read the documentation. Do stuff.

Sorry for the rant, it's just so frustrating.

**Comment by kendrahavens** [comment]
This is a **rough draft** of the table that I'll post to our docs. I still want to add columns for Entity Framework and ASP.NET.

**NOTE**: We are looking into ways of simplifying the version issues in the next releases.

|    LTS or Current     |    .NET Core version   (Framework and runtime)    |    SDK Version (CLI)               |    csproj/project.json    |    IDE              |
|-----------------------|---------------------------------------------------|------------------------------------|---------------------------|---------------------|
|    LTS (outdated)     |    1.0.0                                          |    Preview 1                       |    project.json           |    VS2015 or CLI    |
|    LTS (outdated)     |    1.0.1                                          |    Preview 2                       |    project.json           |    VS2015 or CLI    |
|    LTS (supported)    |    1.0.3                                          |    Preview 2                       |    project.json           |    VS2015 or CLI    |
|    Current            |    1.1.0                                          |    Preview 2.1                     |    project.json           |    CLI Only         |
|    LTS                |    1.0.3                                          |    Preview 3 = RC1                 |    csproj                 |    VS2017 or CLI    |
|    LTS                |    1.0.3                                          |    Preview 4 = RC2                 |    csproj                 |    VS2017 or CLI    |
|    LTS                |    1.0.3                                          |    Preview 5 = NOW   working on    |    csproj                 |    VS2017 or CLI    |

* [General Versioning Documentation](https://docs.microsoft.com/en-us/dotnet/articles/core/versions/)
* [Support Life Cycle Fact Sheet (LTS and Current)](https://www.microsoft.com/net/core/support)

**Comment by kendrahavens** [comment]
@replete That is frustrating. I'd like to help. Can I ask a few more questions about the issues you brought up?

First: What OS are you developing on? What code editor are you mainly using? (I'm assuming from your comment its macOS using VS Code.)
 
- Can you provide links to the code repos that are out-of-date? We definitely have a challenge of keeping our docs up-to-date with each release! Of course, the other challenge is deciding which release track our docs must focus on.
- Have you seen the [Getting Started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started)? There are many ASP.NET Core tutorials there. Not all of them are specific to 1.1 tooling, but they don't need to be for many of the important concepts. [This one shows you how to get started debugging in VS Code on a Mac.](https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet) (It uses a project.json example but the steps are the same when using csproj.) 
  - There does appear to be a significant lack of tutorials for macOS. Is that the main problem with these tutorials?
-  Are you referring to the [aspnet/Templates](https://github.com/aspnet/Templates/tree/dev/src/BaseTemplates/WebAPI) as being out-of-date? If so, what appears to be missing? Please note: the dev branch and the master branch have different tooling with the dev branch using the "Current" track.
- When you say you are getting a load of symbol missing errors on debug - are you using VS Code or another editor? Is it still able to debug properly? Some of the symbol missing errors in VS Code are normal and just letting the editor know its on a Mac. The best way to get help with VS Code and its C# extension is to search the [issues in their repo](https://github.com/OmniSharp/omnisharp-vscode/issues) and create one if yours doesn't exist.
- Not sure what you mean by dnxcore50 being ancient. We do use this import in our latest tooling. Can you elaborate?

I'm always trying to figure out what a new user would want to do! :-) It gets tricky when many new users are familiar with different OSes, tools, and languages. I'd love to hear a little more background on your ideal scenario?

**Comment by bgribaudo** [comment]
@kendrahavens, thanks for working on the version chart!

Do you know if https://www.microsoft.com/net/core/support will be updated to reflect .Net Core 1.01 & 1.0.3?

**Comment by kendrahavens** [comment]
@bgribaudo No problem! Thank you for pointing that out! We just made the PR to update the support page.

**Comment by dasMulli** [comment]
@kendrahavens is the table you drafted in https://github.com/dotnet/core/issues/391#issuecomment-268108521 already available somewhere? PR for discussion and to show ppl would be enough.
Have watched and participated in quite a few of discussions on the aspnetcore slack where the table would be much more illustrative than explaining from scratch (esp. VS2015 vs. VS2017 support).
It would also be great to include the full CLI version numbers (e.g. `1.0.0-preview2-1-003177`) in the table so you could copy&paste into a `global.json`.

It may even gain more complexity as there is now a CLI version and an SDK version for the `Microsoft.NET.Sdk` package. (Explicitly specified in preview3 as NuGet package. In preview4, this was included in the CLI layout but for preview5 or later, MSBuild seems to be planning a versioning strategy with resolvers to do `<Project Sdk="Microsoft.NET.Sdk/1.0.0">`).

**Comment by blackdwarf** [comment]
@dasMulli when you say "full CLI version number" you mean the full CLI version that is given on dot.net/core for example as a download that brings in a given version of the runtime?

**Comment by dasMulli** [comment]
@blackdwarf yes. It would help to quickly answer:
- What version number do I put into `global.json`?
- What zip/tar do I need to download to get X? Useful for CI scripts or docker files [like this one](https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/sdk/projectjson/Dockerfile#L20)

E.g. for 1.0.3 the CLI ("SDK".. though that name is now also used for the msbuild target package), I should update from `1.0.0-preview2-003131` to `1.0.0-preview2-003156`.

**Comment by replete** [comment]
@kendrahavens Hi Kendra, got caught up in new job and then holidays.  

When I get a chance I will try and repro the problems I had. I will record a screencast too, might reveal more gaps.

Thanks so much for the response.

**Comment by replete** [comment]
Also, @kendrahavens, that table is _immensely_ helpful in understanding _what the heck is going on_. The thought of trying dotnet core again summons feelings of lethargy, but I will try again.

Why _isn't_ there a more public (e.g. on the project website, _not_ tucked away in a dev blog) explanation of what's happening with dotnet core? I know there are _a lot_ of people committing, but the project needs more minds on the 'how do I use this' part.

Thanks

**Comment by blackdwarf** [comment]
@dasMulli well, no, not really. For 1.0.3 to work, you need to install the 1.0.3 runtime and that should be it. There is no need to update the CLI.

**Comment by dasMulli** [comment]
@blackdwarf well, it works but the main problem is that updating the installer of runtime + cli causes the cli version to increment. And global.json does not support wildcards like `1.0.0-preview2-1-*`. So if you download the latest package / MSI from dot.net I can't guarantee that the project works when an msbuild version is installed side by side.
And there are going to be subtle differences. E.g. The nuget version in the preview2.1 branch has been updated so a future 1.1.1 would include that.

**Comment by kendrahavens** [comment]
@replete Okay, great! If you'd ever like to email me directly I'm kehavens-@-micro-soft.-com (but without the dashes, I added dashes for the spam bots.) 

I think the team is gradually learning that blog posts != documentation. New docs are showing up everyday on https://docs.microsoft.com/en-us/dotnet, but one of the reasons we open sourced much of our docs site is so users can help us keep up-to-date and voice their concerns on our documentation. (So thank you.) I'm currently working on adding installation guidance there which might be of interest to you: dotnet/docs/issues/1321. I'm planning to expand these instructions to give better context on what each .NET Core download contains.

**Comment by 2933396120** [comment]
How to read the csv file used the .net core?

**Comment by Petermarcu** [comment]
Closing this in favor of: https://github.com/dotnet/core/issues/532

**Comment by g4genious** [comment]
I had Visual Studio 2015 CE and all my Asp.net core projects were working fine. I have just installed VS 2017 CE and none of my VS 2015 CE Asp.net projects are working. I have checked dotnet --info. It is returning 1.0.3. My porject.json currently looks like

{
  "projects": [ "src" ],
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}

I have 1.0.0-preview2-003121 folder in C:\Program Files\dotnet\sdk too. But still getting following error

error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

Any suggestions?

**Comment by enricosada** [comment]
@g4genious `projects` is not supported anymore in `global.json` (i think what you pasted is the global.json).
leave just sdk

**Comment by robianmcd** [comment]
@kendrahavens is there an up to date / official version of the table you posted on Dec 19 (https://github.com/dotnet/core/issues/391#issuecomment-268108521)?

**Comment by kendrahavens** [comment]
@robianmcd Yes, this problem as it relates to our Docker images is addressed in our [release notes](https://github.com/dotnet/core/blob/master/release-notes/docker-image-reference.md). You can look back through the history to see previous versions. Project.json versus msbuild is noted as part of the tag name in earlier versions.

Since a lot of these issues were resolved by .NET tooling going RTM I did not add the chart above to docs.microsoft.com. Also, the download archive had been simplified to reflect the fact that the sdk can target different runtimes. There has also been much discussion on how to make the versions of .NET components better understood by making `dotnet --version` more verbose. I think this issue is best addressed in how we implement that.

**Comment by ojoadeolagabriel** [comment]
Dot. Net core is a joke, why spend so much time learning an rc only for it
to change again. The effort required to achieve the same old things
possible in other platforms with out hassle is not worth it. My
recommendation to u all.... Move it. Java, groovy and python provide
excellent alternatives without all the hassle. You will never miss a
feature, tool or paradigm

**Comment by terrajobst** [comment]
@ojoadeolagabriel while I understand your frustration with our tooling I don't think your comment is helping anyone. It's simply ranting. If you have concrete issues, name them and we can talk about them.
