### ISSUE TITLE
dotnet publish Localization zh-CN resource folder missing

### ISSUE THREAD

**Issue by vadomlore** [dotnet/core#3910]
# dotnet publish Localization zh-CN  resource folder missing

```
dotnet --version
2.2.108

```
os:centos 7

I use `dotnet publish -o ./artifacts` to build dll, with Resources de-DE resx file and zh-CN resx file, but the generated files in artifacts only exists de-DE but without zh-CN; however, build on windows
will not have his issue.

**Comment by scalablecory** [comment]
Have you tried this with the .NET Core 3.0 SDK? If it's still broken there, can you provide a small sample solution we can take a look at?

**Comment by scalablecory** [comment]
Closing due to lack of response. Please re-open if you're still having an issue and can provide more detail.
