### ISSUE TITLE
How to migrate all projects from a solution easily?

### ISSUE THREAD

**Issue by renato04** [dotnet/core#3911]
# How to migrate all projects from a solution easily

Hello, 

I am working with a solution with 44 projects targeting the Dotnet core 2.1 framework.
I want to target 2.2 framework, Is there an easy way to do that without editing each `csproj` file?

I'm sorry if this isn't the right channel to ask that.

Thank you

**Comment by scalablecory** [comment]
There's nothing in-box for this. You might try writing a short xslt to do it.

**Comment by renato04** [comment]
@scalablecory  Thank you for responding to me.

What do you mean with 'short xslt'? 

I think a tool like that will be very helpful for big project migrations.

**Comment by scalablecory** [comment]
> What do you mean with 'short xslt'?

You might write an XSLT script and run it against all of your csproj files with e.g. xsltproc.

> I think a tool like that will be very helpful for big project migrations.

Yea I think this seems like a useful feature. I don't know that it makes sense to be part of .NET Core CLI, as that doesn't currently act on solutions -- the [VS Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) site may be a better place. CC @terrajobst

**Comment by terrajobst** [comment]
Quite frankly I wouldn't bother with XSLT. Just use regular replace in files:

```diff
-<TargetFramework>netcoreapp2.1</TargetFramework>
-<TargetFramework>netcoreapp2.2</TargetFramework>
```

However, please note that 2.1 is LTS while 2.2 is not. If you want the 2.2 features as LTS, you must upgrade to 3.1.

**Comment by renato04** [comment]
@terrajobst I tried that way but there are a lot of NuGet package references and I have to update them.
And I think open all my solution csproj files is not the better way to do that.
I already tried to use the Manage Package for Solution option in Visual Studio without success because after some changes it did not restore the packages anymore.

So I think it does not just replace the target in the csproj file.

I'll try to update it directly to the 3.1 version.

**Comment by terrajobst** [comment]
> @terrajobst I tried that way but there are a lot of NuGet package references and I have to update them.

Sorry about that. FWIW, this is why we moved more and more of those to framework provided references in 3.0. Moving to latest version of the packages should fix most of your problems though.

**Comment by carlossanlop** [comment]
@renato04 did you updated to 3.0 or 3.1 as @terrajobst suggested? Did it solve your problem?

**Comment by renato04** [comment]
@carlossanlop I can't do it right now because we don't have the VS 2019 licence yet. I will have to wait until we buy it.

Thanks!

**Comment by carlossanlop** [comment]
Closing this issue since it has been answered.

**Comment by renato04** [comment]
Hello! Folks!

Now we have a tool to help us.

[https://dotnet.microsoft.com/platform/upgrade-assistant](url)

Thank you all!
