### ISSUE TITLE
.NET Tutorial - Hello World Microservice Issue

### ISSUE THREAD

**Issue by paulmcmillon** [dotnet/core#3917]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows 10 Pro Version 1903 Build 18362.476
Microsoft Visual Studio Professional 2017 Version 15.9.17
.NET Core 2.2 SDK

First of all the name ".NET Tutorial - Hello World Microservice" is misleading since there is no hello world code in the sample.  Given what the tutorial actually creates, a better name might be "WeatherForecast Microservice"

When I run the very first command in the tutorial "**dotnet new webapi -o myMicroservice --no-https
cd myMicroservice"**

The command does create a WEB API project, but fails to create the "WeatherForecast" class or controller, so all bets are off at this point.

**Comment by scalablecory** [comment]
The tutorial you're reading is for .NET Core 3.0. Can you please try again with an updated SDK?

**Comment by carlossanlop** [comment]
6 days no response. Closing.
