### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install Operating System: windows

### ISSUE THREAD

**Issue by zeeturi** [dotnet/core#3918]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Hi @zeeturi, what problem are you having?

**Comment by carlossanlop** [comment]
6 days no response. Closing.
