### ISSUE TITLE
FileNotFoundException thrown when referring to WSUS API DLL

### ISSUE THREAD

**Issue by DCourtel** [dotnet/core#3921]
**Config**: Visual Studio 2019 + .Net Core 3.0.101 on Windows Server 2019 with WSUS role installed.

I have a console project that reference 
`C:\Program Files\Update Services\Api\Microsoft.UpdateServices.Administration.dll` 
and in the code I try to get an instance of IUpdateServer object : 

`var updateSrv = AdminProxy.GetUpdateServer();`

Which throw an exception: 
`System.IO.FileNotFoundException : 'Could not load file or assembly 'Microsoft.UpdateServices.Utils, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. `

If I add a reference to this DLL: `C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.UpdateServices.Utils\v4.0_4.0.0.0__31bf3856ad364e35\Microsoft.UpdateServices.Utils.dll`

I receive this exception: 
`System.IO.FileNotFoundException : 'Could not load file or assembly 'Microsoft.UpdateServices.BaseApi, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. `

Adding this DLL: `C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.UpdateServices.BaseApi\v4.0_4.0.0.0__31bf3856ad364e35\Microsoft.UpdateServices.BaseApi.dll`

I receive: 
`System.IO.FileNotFoundException : 'Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. `
And I don’t have this DLL.

By the past, with .Net Framework, referencing the first DLL was enough to work with WSUS API. Is it still possible to do this with .Net Core?

**Comment by scalablecory** [comment]
The WSUS APIs are built for .NET Framework, not .NET Core.

You can technically reference assemblies that target .NET Framework, but with the understanding that some APIs or even references the assembly needs might not be available.

In this case, ConfigurationManager is included as part of our WinForms and WPF targets, but not as part of NetCoreApp (console app) or ASP.NET targets.

**Comment by DCourtel** [comment]
Ok then, I need to change my plans. Thanks.
