### ISSUE TITLE
MissingMethodException in Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by Hariongit** [dotnet/core#3922]
Issue : MissingMethodException in *Microsoft.Extensions.DependencyInjection*

System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IHttpClientBuilder Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.String, System.Action`1<System.Net.Http.HttpClient>)'.

It doesn't happen in developer machine but on windows-7 computer that i want to run the application i have seen above issue.
I tried switches .net core versions from 3.0.1 to 2.1.0 with clean builds each time but none of them worked.
Any thoughts on how to resolve this issue ?

**Comment by scalablecory** [comment]
It looks like you're referencing a newer version of the DLL than you've got deployed.

@Pilchie

**Comment by Pilchie** [comment]
Can you share your entire .csproj file?

**Comment by Pilchie** [comment]
Closing due to lack of response.  Please let us know if this is still happening, and we'll continue to try to diagnose.
