### ISSUE TITLE
when i try to key dotnet in command prompt, i am getting error as "The program can't start because api-ms-win-cor-timezone-i1-1-0.dll is missing

### ISSUE THREAD

**Issue by saravanan1981** [dotnet/core#3923]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by saravanan1981** [comment]
![image](https://user-images.githubusercontent.com/58271430/69752523-6d415500-1177-11ea-9f18-81d5ccb9d482.png)

**Comment by mairaw** [comment]
Hi @saravanan1981!

What is the version of Windows you're running?
You might need to install some additional dependencies as described in https://docs.microsoft.com/en-us/dotnet/core/install/dependencies.

@leecow @Thraka the error message is very similar to the one described in the section Windows 7 / Vista / 8.1 / Server 2008 R2, not quite the same.

There, the filename is api-ms-win-crt-runtime-l1-1-0.dll. Here the one shown is api-ms-core-timezone-l1-1-0. Should we add this to the docs too?

**Comment by leecow** [comment]
afaik, the timezone dll is also installed by the 2015 crt installer so yes, we could add this error to the docs and point to the same solution. If the 2015 crt is already installed, a repair could be tried.

**Comment by mairaw** [comment]
Closing due to the lack of response.
