### ISSUE TITLE
When will 3.1 LTS come out?

### ISSUE THREAD

**Issue by AlseinX** [dotnet/core#3924]
According to the roadmap, 3.1 LTS would come out on Nov 2019. But up to now, there is still not an rc version like 3.0 rc1. Is it delayed?

**Comment by omajid** [comment]
From [the recent 3.1 Preview 3 blog post](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1-preview-3/):

> Today, we’re announcing .NET Core 3.1 Preview 3. ... We are coming near the end of the 3.1 release and expect to release it in early December.

It sounds like there will be no RC (RC1 or otherwise). And the release will be in early December. I suspect the roadmap that you looked at is out of date.

**Comment by Symbai** [comment]
I'm curious myself too. There hasn't been any exact date yet and the "early December" has started.

**Comment by KamranShahid** [comment]
Don't know why so late and no official announcement? I were thinking of release candidate around 24/25 and then release after a week at max on 2nd December

**Comment by KamranShahid** [comment]
> According to the roadmap, 3.1 LTS would come out on Nov 2019. But up to now, there is still not an rc version like 3.0 rc1. Is it delayed?

It is Obviously delayed. Don't know why? I were thinking of release candidate around 24/25 and then release after a week at max on 2nd December. But no official date yet

**Comment by Symbai** [comment]
It's out: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/

**Comment by KamranShahid** [comment]
yes. But there seems that pacakge for different operating system is still not available
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804
tried runing out 
sudo apt-get install aspnetcore-runtime-3.1
sudo apt-get install dotnet-runtime-3.1

but unsuccessful

**Comment by scalablecory** [comment]
.NET 3.1 is out now, so I'm going to close this issue.

@KamranShahid can you please open a separate issue re: linux package availability? Thanks.
