### ISSUE TITLE
Need help when I run dotnet cmd

### ISSUE THREAD

**Issue by zsanhong** [dotnet/core#3925]
when I run cmd : dotnet  --info ,I got msg:

> 
.NET Core SDK（反映任何 global.json）:

 Version:   3.0.100
 Commit:    04339c3a26

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

when I run cmd :dotnet tool install --global dotnet-ef --version 3.0.1,I got msg:

> 

已安装工具“dotnet-ef”

but when I run cmd: dotnet ef
I got wrong msg:

> 

Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1

So I set COREHOST_TRACE  to 1, and I run cmd dotnet ef again,I go msg:

> 

Tracing enabled @ Thu Nov 28 02:45:42 2019 GMT
--- Invoked dotnet [version: 3.0.0-preview5-27626-15, commit hash: 61f30f5a23af498908cadd9cc282d4d67d71f522] main = {
dotnet
ef
}
Reading fx resolver directory=[C:\Program Files\dotnet\host\fxr]
Considering fxr version=[3.0.1]...
Detected latest fxr version=[C:\Program Files\dotnet\host\fxr\3.0.1]...
Resolved fxr [C:\Program Files\dotnet\host\fxr\3.0.1\hostfxr.dll]...
Loaded library from C:\Program Files\dotnet\host\fxr\3.0.1\hostfxr.dll
Invoking fx resolver [C:\Program Files\dotnet\host\fxr\3.0.1\hostfxr.dll] v2
Host path: [C:\Program Files\dotnet\dotnet.exe]
Dotnet path: [C:\Program Files\dotnet\]
App path: [C:\Program Files\dotnet\dotnet.dll]
Tracing enabled @ Thu Nov 28 02:45:42 2019 GMT
--- Invoked hostfxr_main_startupinfo [commit hash: 19942e71998242599a0b6d4496066eaa38588af5]
Checking if CoreCLR path exists=[C:\Program Files\dotnet\coreclr.dll]
--- Executing in muxer mode...
Using the provided arguments to determine the application to execute.
Application 'ef' is not a managed executable.
--- Resolving .NET Core SDK with working dir [C:\Users\zsh]
Probing path [C:\Users\zsh\global.json] for global.json
Probing path [C:\Users\global.json] for global.json
Probing path [C:\global.json] for global.json
Terminating global.json search at [C:\]
Resolving SDKs with version = 'latest', rollForward = 'latestMajor', allowPrerelease = true
Searching for SDK versions in [C:\Program Files\dotnet\sdk]
Version [3.0.100] is a better match than [none]
Ignoring invalid version [NuGetFallbackFolder]
SDK path resolved to [C:\Program Files\dotnet\sdk\3.0.100]
Using .NET Core SDK dll=[C:\Program Files\dotnet\sdk\3.0.100\dotnet.dll]
Using the provided arguments to determine the application to execute.
Using dotnet root path [C:\Program Files\dotnet\]
App runtimeconfig.json from [C:\Program Files\dotnet\sdk\3.0.100\dotnet.dll]
Runtime config is cfg=C:\Program Files\dotnet\sdk\3.0.100\dotnet.runtimeconfig.json dev=C:\Program Files\dotnet\sdk\3.0.100\dotnet.runtimeconfig.dev.json
Attempting to read runtime config: C:\Program Files\dotnet\sdk\3.0.100\dotnet.runtimeconfig.json
Attempting to read dev runtime config: C:\Program Files\dotnet\sdk\3.0.100\dotnet.runtimeconfig.dev.json
Runtime config [C:\Program Files\dotnet\sdk\3.0.100\dotnet.runtimeconfig.json] is valid=[1]
--- The specified framework 'Microsoft.NETCore.App', version '3.0.0', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '3.0.0'.
--- Resolving FX directory, name 'Microsoft.NETCore.App' version '3.0.0'
Searching FX directory in [C:\Program Files\dotnet]
......

So,Any One tell me,What's the problem？ How to fix it? Thanks a lot

**Comment by scalablecory** [comment]
@jeffschwMSFT @Pilchie

**Comment by kapilepatel** [comment]
Not sure but can you try to uninstall all version of dot net core sdk/runtime and do a fresh install

**Comment by Pilchie** [comment]
This is https://github.com/aspnet/EntityFrameworkCore/issues/19150.  It should have been addressed by the release of `dotnet-ef` 3.1.0
