### ISSUE TITLE
The last Version of .Net Core is 3.0 Not 2.2

### ISSUE THREAD

**Issue by locoalien** [dotnet/core#3931]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: macos

The last Version of .Net Core is 3.0 Not 2.2, you should modify the dockerfile on the tutorial.

I have modified the dockerfile, and this works correctly.

![image](https://user-images.githubusercontent.com/1004466/69839653-71787b80-1226-11ea-9070-b07d92c3d943.png)

Thanks! 👍 :)

**Comment by vijaysahu12** [comment]
Yes it's working for me too. 
Reason : I have installed VS2019 with .net core 3.0 which does not has 2.2.
Hence once update the sdk  2.2 to 3.0 , It start working smoothly.. 
Thanks (Y)

**Comment by scalablecory** [comment]
@shirhatti can you take a look at our docker tutorial?

**Comment by mairaw** [comment]
You're right @Xavina. It has been updated to 3.1 already.
