### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Kburak12** [dotnet/core#3937]
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\3.0.1\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\3.0.1\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
dotnet error

**Comment by scalablecory** [comment]
Please install the required dependencies here:

https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore30&pivots=os-windows

**Comment by scalablecory** [comment]
CC @dotnet/docs @carlossanlop @mairaw it looks like the URL above had one segment changed from "setup" to "install" -- can we setup a permanent redirect so we don't break everything linking to it?

**Comment by Thraka** [comment]
The redirect was pointing to the wrong location, I've just filed a PR to fix it.

**Comment by mairaw** [comment]
Closing since redirects were fixed.
