### ISSUE TITLE
using .net to create simple webapp

### ISSUE THREAD

**Issue by 2010pctech** [dotnet/core#3938]
C:\WINDOWS\system32>program.cs using system; namspace myApp{ class program {  static void Main(string[]args) { Console.WriteLine("Hello World");  }  }  }
'program.cs' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>>dotnet run
Access is denied.
I was told I can use .NET to create simple web app I follow the instructions but get error message this is the info written  bellow

C:\WINDOWS\system32>dotnet run

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.101

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Couldn't find a project to run. Ensure a project exists in C:\WINDOWS\system32, or pass the path to the project using --project.

**Comment by scalablecory** [comment]
It looks like you are trying to type source into the command line rather than updating the program.cs file in an editor. Can you point to the tutorial you're following?

**Comment by 2010pctech** [comment]
i was following this tutorial:
https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Hilton Bristol

**Comment by scalablecory** [comment]
Can you try doing this in a directory you have better access to? System32 is part of the Windows installation folder and not meant to contain user files.

And finally, this command will not work -- you will want to open a file with an editor if you want to write code into it:
> program.cs using system; namspace myApp{ class program { static void Main(string[]args) { Console.WriteLine("Hello World"); } } }

**Comment by scalablecory** [comment]
Closing due to lack of response; please reopen if you're still having the issue and can provide additional details.
