### ISSUE TITLE
Misleading type error with implicit operator in generic type, from generic argument type to that generic type, when the generic argument is an interface

### ISSUE THREAD

**Issue by markonius** [dotnet/core#3939]
Fedora 31, dotnet 3.0.100

When using an implicit operator from a type variable `T` to a concrete type, if the type argument is an interface, a misleading error is shown: `Cannot implicitly convert type 'SomeType' to 'SomeGeneric<SomeType>'. An explicit conversion exists (are you missing a cast?)`
There is no explicit cast.

Here is a minimal example:

```cs
using System.Collections.Generic;
public class BadError<T> {
   public static implicit operator BadError<T>(T value) => new BadError<T>();
}
public class GoodError {
   // user-defined conversions to or from an interface are not allowed
   public static implicit operator GoodError(IReadOnlyList<int> value) => new GoodError();
}
public static class ObBoi {
   public static void Main()
   {
      IReadOnlyList<int> list = new List<int>();
      // Cannot implicitly convert type 'System.Collections.Generic.IReadOnlyList<int>' to 'BadError<System.Collections.Generic.IReadOnlyList<int>>'. An explicit conversion exists (are you missing a cast?)
      BadError<IReadOnlyList<int>> a = list;
   }
}
```

**Comment by scalablecory** [comment]
I believe what you're seeing is that implicit conversions to or from an interface is explicitly disallowed in C#. CC @jaredpar 

From section 15.10.4 "Conversion operators" of the [C# spec](https://www.ecma-international.org/publications/standards/Ecma-334.htm):

> User-defined conversions are not allowed to convert from or to interface-types. In particular, this
restriction ensures that no user-defined transformations occur when converting to an interface-type, and
that a conversion to an interface-type succeeds only if the object being converted actually implements the
specified interface-type.

**Comment by markonius** [comment]
Correct. That's why I included the `GoodError` snippet of code. My problem is that the error message I get with the generic class is mislieading.

**Comment by carlossanlop** [comment]
This issue was moved to dotnet/csharplang#3840
