### ISSUE TITLE
iqsharp could not be installed

### ISSUE THREAD

**Issue by kaiiyer** [dotnet/core#3942]
# Issue Title
iqsharp could not be installed

# General
.NET Core 3.0
---------------------
SDK Version: 3.0.101
---------------------
OS (Version): Parrot GNU/LINUX Release 3.11 (64-bit)

Tool 'microsoft.quantum.iqsharp' is already installed and when i try using the command "dotnet iqsharp install", I get the following error.

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-iqsharp does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by scalablecory** [comment]
This issue was moved to microsoft/iqsharp#68
