### ISSUE TITLE
This software needs to be updated. Contact the developer for more information.

### ISSUE THREAD

**Issue by MariaFL9815** [dotnet/core#3943]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macOS

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet-sdk-3.0.101-osx-x64.pkg” can’t be opened because Apple cannot check it for malicious software.

It is not updated to the latest macOS Catalina software update.

**Comment by scalablecory** [comment]
Can you provide your exact OS version and the commands you're using to install the SDK? Thanks.

CC @aik-jahoda

**Comment by ColCoutts** [comment]
Having same issue while trying to download dotnet-sdk-3.0.101-osx-x64.pkg

OS Version: Catalina v. 10.15.1

just following these install guides: https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.0.101-macos-x64-installer and getting the above error message

**Comment by dagood** [comment]
There's a workaround and more info posted here: https://github.com/dotnet/core/issues/3685#issuecomment-547411254

> Show the file in the Finder and open context menu by right click on the downloaded package. Then select `Open` and a similar dialog will appear however there will be `Open` button available. When you open it in this way it will execute the package.

@leecow @jcagme do we currently expect this issue to be popping up? Is it documented in a place people can find? Context: "dotnet-sdk-3.0.101-osx-x64.pkg can’t be opened because Apple cannot check it for malicious software." I see a lot of discussion online for other software installers that need this workaround, but people will naturally ask us when our instructions lead them down this path.

/cc @aik-jahoda

**Comment by gastonmuijtjens** [comment]
Still having this issue when downloading .NET Core SDK 3.1.100: https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.100-macos-x64-installer

macOS 10.15.1 (19B88)

**Comment by aik-jahoda** [comment]
@gastonmuijtjens Did you follow https://github.com/dotnet/core/issues/3943#issuecomment-560578020 comment? If it doesn't help, can you share your error message and os version?

**Comment by leecow** [comment]
This message is occurring due to new security features in Catalina. We have been working with Apple to understand what needs to be done and are working toward a resolution. This will take place over the next few months for 2.1, 3.0 and 3.1. See the [3.1 Known Issues document](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-installation-on-macos-catalina-1015) for more info on installing on Catalina if you get this error.

**Comment by andreacassioli** [comment]
Still happening here. Seriously, anyone have tried this before releasing such an important package? Catalina has been around for months now....

**Comment by aik-jahoda** [comment]
I tested it on Catalina and it works fine. You need to follow this comment https://github.com/dotnet/core/issues/3685#issuecomment-547411254 ?

>Show the file in the Finder and open context menu by right click on the downloaded package. Then select Open and a similar dialog will appear however there will be Open button available. When you open it in this way it will execute the package.

**Comment by andreacassioli** [comment]
It works following https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-installation-on-macos-catalina-1015

But it is annoying that such a distribution does not work out of the box.

**Comment by sadhakbj** [comment]
Facing same issue on MacOS Catalina 10.15.2
```
“dotnet-sdk-3.1.101-osx-x64.pkg” can’t be opened because Apple cannot check it for malicious software.
```

**Comment by leecow** [comment]
We have a note about this in the [Known Issues doc](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md) and workaround steps. Catalina includes additional security checks for installers which are downloaded from web sites which results in this error. We're on track to have the installers properly notarized by Apple for the February release.

**Comment by hontas** [comment]
The suggested solution does not work for me as I have no option to open it anyway, but... the following helped and has been my command in shining armour since the upgrade to Catalina:
```shell
xattr -d com.apple.quarantine path-to-whatever-catalina-wont-open
```
I use it all the time.

**Comment by DavosMarsh** [comment]
thanks @aik-jahoda  - right clicking  on file and open worked for me anyway on Catalina.

**Comment by kyle-rader** [comment]
Is it expected that this issue is still present for the dotnet 5.0.202 binaries on OSX 11.3 ?

**Comment by eshorr-cyber** [comment]
In order to install Package.dmg on Big Sur, you have to do it by the command line. 

1) Open the Package.dmg
2) Open the console and type:
sudo /usr/sbin/installer -pkg <Path to Packages.pkg> -target /
