### ISSUE TITLE
.NET Core 3.0 MongoDB driver support

### ISSUE THREAD

**Issue by nikola-mirkov-bm** [dotnet/core#3944]
# .NET Core 3.0 MongoDB C# driver support

Problem with the MongoDB C# driver support and Microsoft page that has a tutorial on how to set it up with .NET Core 3.0, while MongoDB official support is not present.

# Details

There is an official **Microsoft page that has a tutorial on how to set up .NET Core 3.0 with MongoDB** [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0). The thing is, **MongoDB does not support .NET Core 3.0 officially**, as seen [here](https://docs.mongodb.com/ecosystem/drivers/csharp/).
Screenshot attached - made during the writing of this request.
___
![2019-12-02 16_30_03-Window](https://user-images.githubusercontent.com/48907541/69972153-5907aa00-1521-11ea-9436-c6f635fddb14.png)
____

### Could you, please, explain what am I missing (and I honestly hope I am missing something), or what is the Microsoft team doing with publishing the aforementioned page and sort thing out a bit?
There is no mention on the page of "using the new C# beta drivers (2.10)" or anything.

**Comment by scalablecory** [comment]
The MongoDB driver is owned by MongoDB, not .NET, so you will need to ask them about official support for .NET Core 3.0.

In most cases libraries that work for .NET Core 2.x should work for .NET Core 3.0 without any changes. CC @Pilchie

**Comment by nikola-mirkov-bm** [comment]
Maybe I am mistaken, but if [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0) page exists, we can presume that the Microsoft Team confirmed that MongoDB C# drivers support .NET Core 3.0? 
If they don't support it, **the existence of the page is the problem**, not the drivers itself, that's MongoDB teams concern.

**Comment by nikola-mirkov-bm** [comment]
I confirmed that the tutorial for 3.0 works with the 2.9.0 drivers, but our current project is not when we switched. Obviously we need to have a detailed overlook of the changes.
Anyways, **the tutorial works, confirmed.**
