### ISSUE TITLE
Linux prereq link is broken

### ISSUE THREAD

**Issue by gvashishtha** [dotnet/core#3945]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

I am having an issue with the link in this part of the documentation: https://github.com/dotnet/core/blob/master/Documentation/prereqs.md

When I click on the Linux prerequisites, I do not see anything.

**Comment by scalablecory** [comment]
@Thraka @dotnet/docs 

Related to #3937

**Comment by mairaw** [comment]
What do you mean you don't see anything @gvashishtha?

**Comment by Thraka** [comment]
There was a bad redirect I fixed right around the time this was filed. I don't think this is an issue anymore. #16048 it was related to the change from the `/setup/` folder to the `/install/` folder.
