### ISSUE TITLE
When will be .net core 3.1 will be finally released?

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/core#3946]
.net core 3.1 was supposed to be released in end of November 2019. Then recently it was announced in some conference to be around 2nd/3rd of December. But there is no release since last three week after preview 3.
Any update about final date?

**Comment by Symbai** [comment]
Good question but dupe of https://github.com/dotnet/core/issues/3924

**Comment by KamranShahid** [comment]
> Good question but dupe of #3924

didn't see it earlier. Anyway i can delete issue in github?
