### ISSUE TITLE
The path to an application .dll file to execute.

### ISSUE THREAD

**Issue by alokrawat050** [dotnet/core#3947]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos 10.13.6

>> dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by scalablecory** [comment]
As the tutorial states,

> "If the command runs, printing out information about how to use dotnet, you're good to go."

So, everything looks good here. Was there something else you're having trouble with?

**Comment by carlossanlop** [comment]
6 days no response. Closing.
