### ISSUE TITLE
dotnet core 3.1 mvc application can not find Localization Data in docker container

### ISSUE THREAD

**Issue by Benknightdark** [dotnet/core#3955]
# dotnet core 3.1  mvc application can not find Localization Data in docker container

When I use docker Container to run  my dotnet core 3.1 mvc applicatoin , I can not find any Globalizatoin I Added. Could some one help me to fix it .

Here is my sample code repository link
https://github.com/Benknightdark/DotnetCore3-1-Globalization
# General

My dotnet core version

![image](https://user-images.githubusercontent.com/5799487/70139851-59917380-16ce-11ea-8409-d3c967c69b63.png)

**Comment by scalablecory** [comment]
@Pilchie

**Comment by Benknightdark** [comment]
After I added `<EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>` to csproj file, and I can see the localization data.

**Comment by Pilchie** [comment]
Adding @BenVillalobos who I believe is looking at this in MSBuild.

**Comment by Pilchie** [comment]
@BenVillalobos Move to MSBuild and/or dupe this?

**Comment by BenVillalobos** [comment]
@Pilchie sounds good. this issue is on my to-do list.

**Comment by carlossanlop** [comment]
@BenVillalobos can this be closed, or should it be moved to MSBuild?

**Comment by BenVillalobos** [comment]
Closing this due to the nature of the breaking change in the dependent upon convention.
