### ISSUE TITLE
During Admin installation getting key error

### ISSUE THREAD

**Issue by pthorsley** [dotnet/core#3965]
# Failure to write key when installing .Net Core 3.1
Have never had this issue in the past with other versions. 

Running in Admin mode

 ERROR Message:
"Could not write value Version to key \SOFTWARE\Microsoft\ASP.NET Core\Shared Framework\v3.1\3.1.0. Verify that you have sufficient access to that key, or contact your support personnel."

![image](https://user-images.githubusercontent.com/6778972/70250023-7f546200-173a-11ea-9f41-38c2e3bfe8fa.png)

After this message I clicked Ignore and then it said I installed successfully, but kind of wonder if that is true?

**Comment by pthorsley** [comment]
additional info:

C:\GitProjects>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.1.7 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by leecow** [comment]
@dagood @wli3 @johnbeisner

**Comment by dagood** [comment]
@joeloff 

Looks like source code is here, FWIW, but that file hasn't changed since early 3.0.0 previews: https://github.com/aspnet/AspNetCore/blob/v3.1.0/src/Installers/Windows/SharedFramework/Product.wxs#L66-L72

**Comment by joeloff** [comment]
Yeah, we haven't touched the registry keys since 2.0, but if it's coming back with a permission error, it's possible something in the registry is not right.

@pthorsley do you have logs, there should be one for the specific MSI itself in your %temp% folder. Also if you run regedit, do you see anything odd in the registry in terms of permissions that maybe changed, e.g. perhaps an OS policy that modified permissions or something like that.

**Comment by carlossanlop** [comment]
@pthorsley did you get a chance to collect the information requested by @joeloff?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide more detail.
