### ISSUE TITLE
'dotnet' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by jvme** [dotnet/core#3968]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Hey @jvme - we'll need a bit more information to try and help. What version of the .NET Core SDK did you install and what version of Windows are you using?

**Comment by carlossanlop** [comment]
5 days no response. Closing.
