### ISSUE TITLE
Installing dotnet core 3.1 breaks vs 2019 (nuget)

### ISSUE THREAD

**Issue by worldspawn** [dotnet/core#3969]
# Installing dotnet core 3.1 breaks vs 2019

I installed dotnet core 3.1

# General

I have a solution with a cloud services project. After I installed dotnet core 3.1 the project cannot resolve the path the azure tools sdk. After I manually corrected that path I have found the nuget package management is *completely broken* in vs 2019. Well done.

Manage packages for solution
![image](https://user-images.githubusercontent.com/819581/70280500-b09d6280-180c-11ea-8461-091560814558.png)

The context menu option to manage packages for a project is now gone. Its just not there.

![image](https://user-images.githubusercontent.com/819581/70280744-41743e00-180d-11ea-83ef-0203d7fdb80b.png)

**Comment by leecow** [comment]
Sorry that you're hitting an issue! We certainly do a lot of testing with VS so will be anxious to see what this is about. Adding a few folks to have a look and add others to the effort if needed - @livarcocc @Pilchie

**Comment by worldspawn** [comment]
I installed dotnet core 3.1, and _then_ updated vs 2019 to the latest version if that helps.

I need to continue working so I've uninstalled dotnet core 3.1, left the VS patch alone but repaired the installation of 2019. Nuget is now working.

**Comment by Pilchie** [comment]
Adding @rrelyea for the NuGet package manager.

**Comment by rrelyea** [comment]
Sorry for your problem. We are chasing down a bug. Likely using some nuget dlls via vs code, which cause an upgrade problem.

Please engage here: https://developercommunity.visualstudio.com/content/problem/784506/package-manager-multiple-errors-displayed-on-tools.html

Likely a reboot fixes

Cc @aortiz-msft

**Comment by ilmax** [comment]
I had a similar problem and clearing the MEF cache of VS solved it

**Comment by rrelyea** [comment]
@worldspawn - any details on the exact repro? Can you repro again with same steps?

**Comment by worldspawn** [comment]
Hi guys, sorry I repaired my install and have moved on. I haven't tried to reproduce

**Comment by carlossanlop** [comment]
@worldspawn if repairing your installation worked, then I think we can close this issue. Feel free to reopen it if you need more help.
