### ISSUE TITLE
Handler "aspNetCore" has a bad module "AspNetCoreModule" in its module list

### ISSUE THREAD

**Issue by klanglie** [dotnet/core#3970]
I uninstalled the old dotnet host runtime on my machine. Everything was working prior. I then installed dotnet-hosting-3.1.0-win.exe After doing that and deploying my latest code compiled for 3.1, I am now receiving the following error:
HTTP Error 500.21 - Internal Server Error
Handler "aspNetCore" has a bad module "AspNetCoreModule" in its module list
![image](https://user-images.githubusercontent.com/13773413/70290468-f6731000-17a5-11ea-9b3d-83c57accc2d9.png)
![image](https://user-images.githubusercontent.com/13773413/70290487-0b4fa380-17a6-11ea-9efc-71014cb4d30e.png)

I am a little stuck as to how to resolve this issue.

**Comment by 0x53A** [comment]
asp.net core 2.x registers a handler named ``AspNetCoreModule``, asp.net core 3.0 registers ``AspNetCoreModuleV2``.

Your web.config probably still specifies the old one.

**Comment by klanglie** [comment]
I tried modifying modules="AspNetCoreModule" to AspNetCoreModulV2 but am still getting the same error:
HTTP Error 500.21 - Internal Server Error
Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list

**Comment by klanglie** [comment]
Solved. I was missing Modules + Handler Mappings configuration. So had to re-add them.
