### ISSUE TITLE
Update support policy page

### ISSUE THREAD

**Issue by michha** [dotnet/core#3971]
https://dotnet.microsoft.com/platform/support/policy/dotnet-core needs to be updated about

- End of Support for 2.1
- End of Support for 3.0
- all about 3.1

https://github.com/dotnet/core/blob/master/microsoft-support.md should also be updated about End of Support for 2.1

**Comment by michha** [comment]
It seems that the first file is already updated, I made a patch für the second file #3976

**Comment by michha** [comment]
https://dotnet.microsoft.com/download/dotnet-core has the be updated regarding 2.1 End of Support too

**Comment by jawn** [comment]
It is sad and great that [this page](https://twitter.com/khellang/status/1204051745258819585) is more quickly up to date. Can we get this page upated as part of new dotnet core releases? https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by carlossanlop** [comment]
@leecow @rowanmiller do you know who owns these public pages so they get updated?

**Comment by scalablecory** [comment]
Looks like these pages were updated; thanks.
