### ISSUE TITLE
ARM32 Windows Build not fully functional

### ISSUE THREAD

**Issue by Qiangong2** [dotnet/core#3973]
# Issue Title

Latest ARM32 Windows build broken on Windows RT

# General

When launching he ARM32 windows binaries on a Windows RT device, the main dotnet.exe works, but when I want to run any other exe files like fsi, it always fails saying it can't be run on my PC.

I am in Test signing mode and it should be working (as dotnet.exe does). This is all on my Surface 2.

**Comment by scalablecory** [comment]
.NET Core [does not support Windows RT](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md). The ARM32 Windows build is intended for use on Windows Server Core only.

CC @richlander
