### ISSUE TITLE
After create WebApp, port 5000 is not listening in Centos 9

### ISSUE THREAD

**Issue by uranusperu** [dotnet/core#3978]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Can you copy the console output you see here? It should contain something like "listening on http://..." and may use a port other than 5000.

**Comment by uranusperu** [comment]
is Centos 8, 
From this page: https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
in Linux:
[root@localhost www]# dotnet new webApp -o myWebApp --no-https                                                                                                                                The template "ASP.NET Core Web App" was created successfully.                                                                                                                                 This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/3.1-third-party-notices for details.                                                                                                                                                                                                                                                   Processing post-creation actions...                                                                                                                                                           Running 'dotnet restore' on myWebApp/myWebApp.csproj...                                                                                                                                         Restore completed in 205.28 ms for /var/www/myWebApp/myWebApp.csproj.                                                                                                                                                                                                                                                                                                                     Restore succeeded.                                                                                                                                                                                                                                                                                                                                                                          [root@localhost www]# cd myWebApp                                                                                                                                                             [root@localhost myWebApp]# dotnet run                                                                                                                                                         info: Microsoft.Hosting.Lifetime[0]                                                                                                                                                                 Now listening on: http://localhost:5000                                                                                                                                                 info: Microsoft.Hosting.Lifetime[0]                                                                                                                                                                 Application started. Press Ctrl+C to shut down.                                                                                                                                         info: Microsoft.Hosting.Lifetime[0]                                                                                                                                                                 Hosting environment: Development                                                                                                                                                        info: Microsoft.Hosting.Lifetime[0]                                                                                                                                                                 Content root path: /var/www/myWebApp

**Comment by scalablecory** [comment]
Thanks. Can you verify via `netstat -lnp` in command line that the app is truly listening?

CC @Pilchie

**Comment by Pilchie** [comment]
@uranusperu I edited your comment to format nicer - hope you don't mind.

**Comment by Pilchie** [comment]
@anurse - any other ideas?  @uranusperu this isn't a Linux VM on another machine or something where   localhost might not line up?

**Comment by uranusperu** [comment]
is VM, i´m stop Apache, run only Kestrel service, and done. Microsoft documentation is confuse https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1

**Comment by uranusperu** [comment]
is VM, i´m stop Apache, run only Kestrel service, and done. Microsoft documentation is confuse https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1

**Comment by Pilchie** [comment]
Are you trying to access localhost from inside the VM, or from the host?  If it's the host, you probably need to access it via the IP address of the VM.

**Comment by uranusperu** [comment]
It already works, with Kestrel + Apache, thank you very much.

**Comment by Pilchie** [comment]
So, we should close this issue?

**Comment by uranusperu** [comment]
Yes.
