### ISSUE TITLE
The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1

### ISSUE THREAD

**Issue by eripin91** [dotnet/core#3980]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/16111160/70517488-9ef0ed80-1b73-11ea-96d0-f0dcce2fb9bd.png)

**Comment by jsonvoorhees11** [comment]
Please check your myMicroservice.csproj file, it seems using .net core 3.1 as target which causes the problem .
Changing target to 2.2 may help solve this issue.

**Comment by eripin91** [comment]
Yes, actually I want to use net core 3.1 
Is it possible ?

**Comment by jsonvoorhees11** [comment]
In your Dockerfile, replace mcr.microsoft.com/dotnet/core/sdk:2.2
with mcr.microsoft.com/dotnet/core/sdk:3.1 may help. @eripin91
