### ISSUE TITLE
Issue with docker set up for micro service

### ISSUE THREAD

**Issue by Pahadsingh** [dotnet/core#3983]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error while executing the build command. Please note i logged into Docer through command prompt as well. Before this step, I am able to browse the service @ - http://localhost:5000/WeatherForecast

C:\Users\lpaha\source\repos\myMicroservice>docker build -t mymicroservice .
Sending build context to Docker daemon  1.617MB
Step 1/10 : FROM mcr.microsoft.comdotnetcoresdk2.2 AS build
pull access denied for mcr.microsoft.comdotnetcoresdk2.2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by eripin91** [comment]
Looks like you have same issue with me
In your Dockerfile, replace mcr.microsoft.com/dotnet/core/sdk:2.2
with mcr.microsoft.com/dotnet/core/sdk:3.1. Also, replace mcr.microsoft.com/dotnet/core/aspnet:2.2 with mcr.microsoft.com/dotnet/core/aspnet:3.1
@Pahadsingh

**Comment by Pahadsingh** [comment]
@eripin91  - Thnaks that worked. however, i get a new error  in step 9 when i try to build.

C:\Users\lpaha\source\repos\myMicroservice>docker build -t mymicroservice .
Sending build context to Docker daemon  1.934MB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
3.1: Pulling from dotnet/core/sdk
16ea0e8c8879: Pull complete                                                                                                                                                        50024b0106d5: Pull complete                                                                                                                                                        ff95660c6937: Pull complete                                                                                                                                                        9c7d0e5c0bc2: Pull complete                                                                                                                                                        f4b600a3072b: Pull complete                                                                                                                                                        5bd47e7e8ad7: Pull complete                                                                                                                                                        c7e381a2ec88: Pull complete                                                                                                                                                        Digest: sha256:cb3bf412996fba3a8015b750974ca50d5ba9b40931410f2cd82654e6b11e8276
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1
 ---> 9817c25953a8
Step 2/10 : WORKDIR src
 ---> Running in 6627df81fb24
Removing intermediate container 6627df81fb24
 ---> 06cc148502d9
Step 3/10 : COPY myMicroservice.csproj .
 ---> 710286a60c34
Step 4/10 : RUN dotnet restore
 ---> Running in f7907ef749e1
  Restore completed in 107.17 ms for /src/myMicroservice.csproj.
Removing intermediate container f7907ef749e1
 ---> f1bfca9e906d
Step 5/10 : COPY . .
 ---> b82a617b527f
Step 6/10 : RUN dotnet publish -c release -o app
 ---> Running in a003e950fcf2
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 20.87 ms for /src/myMicroservice.csproj.
  myMicroservice -> /src/bin/release/netcoreapp3.1/myMicroservice.dll
  myMicroservice -> /src/app/
Removing intermediate container a003e950fcf2
 ---> 1301395b53ae
Step 7/10 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
3.1: Pulling from dotnet/core/aspnet
Digest: sha256:37c65f2780e2f8bd8efa60eb2c3e1531813509bccdcf75f63c477e92b6fc22dd
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/aspnet:3.1
 ---> 08096137b740
Step 8/10 : WORKDIR app
 ---> Using cache
 ---> 1993ed8ffb90
Step 9/10 : COPY --from=build app .
COPY failed: stat /var/lib/docker/overlay2/d92e68d6c02d838a84e05b3dbfc23c03a11627d192864d6e11f3a5a036f43557/merged/app: no such file or directory

**Comment by mairaw** [comment]
@shirhatti can you help here?

**Comment by sughosneo** [comment]
Hello @Pahadsingh,

The steps in the tutorial have been updated to use .NET 5. Could you please try executing again and see if the error still exists? Closing the issue due to inactivity. Please feel free to open it again if the issue persists.

Thank you.
