### ISSUE TITLE
.NET SDK

### ISSUE THREAD

**Issue by AyalewBinette** [dotnet/core#3985]
I was trying to download .NET SDK and it wouldn't let me download!. I there any help i can get to download C# on my Mac

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
> and it wouldn't let me download

This is a bit broad. Can you please provide more detailed repro steps? From which website were you trying to download? Which link did you click?

**Comment by scalablecory** [comment]
Closing due to lack of response; please feel free to re-open if you can provide more details. The download is working fine for me.
