### ISSUE TITLE
Multipart file loaded into memory when controller method has parameter

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/core#3986]
Multipart file upload will first load the file into memory and only then call the controller method as soon as the controller method as parameters. Even if the parameters are only url or query parameters.

## Background
We want to stream a large file directly from the frontend into azure storage and need to pass some ID in addition to the file (query parameter).

## Problem
Real streaming does only work when the controller method has no parameters. **This works correctly**, you can access the stream with the `MultipartReader`:
```csharp
[HttpPost]
public async Task<IActionResult> UploadFile()
```

**This does not work correctly** because the whole request is stored into memory before the controller method is called:

```csharp
[HttpPost]
public async Task<IActionResult> UploadFile([FromQuery] UploadDocumentProperties uploadDocumentProperties)
```

As soon as there is any parameter the whole request will be loaded into memory and only when this is done the controller method is called. This is even true when the parameter is only a url or query parameter.

We noticed this with big files. The UI control uploaded them to 100% and then the user had to wait about the same time again for the API to stream the file to azure. With debugging we could see that the controller is not called before the UI control uploaded the file completely. Now without the parameter the controller is called immediately and streams the file directly as expected.

## Workaround
We need some ID that is passed as query parameter. Since the controller method must not have any parameter for the streaming to work correctly we parse the query parameters by hand (`Request.Query`).

BR
Matthias

**Comment by ltouro** [comment]
Not related to the error you reporting, but I would suggest a different approach to uploading big files to Azure. 

Generate a SAS key on the server and send it to the client (with upload permission only). Then, the client upload the file directly to Azure. After the operation completes, the client notifies the server.

This way, the file is never sent to your server and you will have no memory problems. This is a common pattern and implemented by several upload controls libraries.

HTTP REQ 1 -> Client - Your server -> return upload URL with embedded SAS key
HTTP REQ 2 -> Client - Azure -> upload the file to Azure using the SAS key
HTTP REQ 3 -> Client - Your server -> notifies upload successful

**Comment by carlossanlop** [comment]
@Pilchie can you please move to the asp repo?

**Comment by Pilchie** [comment]
This issue was moved to aspnet/AspNetCore#17837

**Comment by Pilchie** [comment]
@carlossanlop @terrajobst I no longer have permissions to assign or close issues here? ☹️

**Comment by carlossanlop** [comment]
I can close it.
It's weird, I'll open an email thread to figure out write permissions, @Pilchie .
