### ISSUE TITLE
Error MSB6004 on Ubuntu 19.04

### ISSUE THREAD

**Issue by AlirezaAlipour** [dotnet/core#3987]
I can't run or debug my .Net Core projects, I'm getting the following error:

`/usr/share/dotnet/sdk/3.1.100/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6004: The specified task executable location "/" is invalid. [/home/ubuntu/Test/Test.csproj]`

My platform information:

- OS: Ubuntu 19.04
- Kernel Version: Ubuntu 5.0.0-28.30-generic 5.0.21 (I find it by `cat /proc/version_signature`)
- .NET Core SDK Information:
  - Version: 3.1.100
  - Commit: cd82f021f4

Base on some other issues like #3525 or actions/virtual-environments#2 I can infer that the issue is related to the kernel. Have you experienced similar issue on Ubuntu 19.04? Have you tested .NET Core with the mentioned version and commit on Ubuntu 19.04 or newer version?

**Comment by AlirezaAlipour** [comment]
I have installed Ubuntu 19.10 on my machine, now I can use .NET Core SDK without the MSB6004 error.

**Comment by scalablecory** [comment]
Hi @AlirezaAlipour, are you still having this issue? If so, can you please provide some project files that we can look at? Thanks.

CC @safern

**Comment by AlirezaAlipour** [comment]
Thank @scalablecory very much, at the moment I'm using Xubuntu 20.04.1 and I have not experienced any problem with .NET Core SDK, unfortunately I can't say whether the problem still exists on Ubuntu 19.04 or not.

**Comment by safern** [comment]
From reading the threads you included on the issue this is not an MSBuild or .NET Core SDK issue, it seems like this was an Ubuntu bug in the kernel that was exposing an error via MSBuild. Closing the issue, please feel free to re-open if you think this should be opened and investigated further.
