### ISSUE TITLE
dotnet core v3.1/3.0 Process.Start execute shell command Memory Leak

### ISSUE THREAD

**Issue by lychee-ui** [dotnet/core#3989]
# dotnet core v3.1/3.0 Process.Start execute shell command Memory Leak

System: Ubuntu 18.04 / CentOS 7.6 / SUSE 15
SDK: 3.1.100

ex:
``` CSharp
var psi = new ProcessStartInfo("dotnet");
psi.RedirectStandardOutput = true;

psi.Arguments = $"--version";
using (var proc = Process.Start(psi))
{
    var output = proc.StandardOutput.ReadToEnd();
    var version = output.Trim();

    if (!proc.HasExited)
    {
        proc.Kill();
    }
}
```

**Comment by irac-ding** [comment]
I have find the same issue.

**Comment by irac-ding** [comment]
any response ??

**Comment by irac-ding** [comment]
Please Pay Attention !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
System: CentOS 7.2
SDK: 3.1.201

ex:
class Program
{
static void Main(string[] args)
{
Console.WriteLine("Press any key to continue");
Console.ReadLine();
while (1 == 1)
{
List stdout = RunTaskAndReturnStdout("dotnet", $"--version");
}
}
}

public static List RunTaskAndReturnStdout(string fileName, string arguments, string workingDirectory = "")
{
List ret = new List();
try
{
using (Process proc = new Process())
{
proc.StartInfo.FileName = fileName;
proc.StartInfo.Arguments = arguments;
proc.StartInfo.UseShellExecute = false;
if (!string.IsNullOrWhiteSpace(workingDirectory))
proc.StartInfo.WorkingDirectory = workingDirectory;
proc.StartInfo.RedirectStandardOutput = true;
proc.Start();
while (!proc.StandardOutput.EndOfStream)
{
string line = proc.StandardOutput.ReadLine();
// Console.WriteLine(logstr);
if (!string.IsNullOrWhiteSpace(line))
ret.Add(line);
}
return ret;
}
}
catch (Exception ex)
{
return ret;
}
}

**Comment by BagJo** [comment]
We have the exact same problem. Is there any progress on this or at least a known workaround?

**Comment by mdisg** [comment]
I'm currently investigating an out of memory problem on our linux device (arm32) and came accross this issue. Every minute we start a process to collect dhcp information which over time seems to allocate/consume more and more memory in the process which does the `Process.Start`

I did a  test run using the modified sample code from @lychee-ui in which i start the cli tool `free`
```
var psi = new ProcessStartInfo("free");
psi.RedirectStandardOutput = true;
using (var proc = Process.Start(psi))
{
    var output = proc.StandardOutput.ReadToEnd();
    var version = output.Trim();
    proc.WaitForExit();
    if (!proc.HasExited)
    {
        proc.Kill();
    }
}
```

Every 100th call i logged the memory consumption of the running process using `process.WorkingSet64` from `Process.GetCurrentProcess()`

After 69500 calls of `Process.Start(psi)` the memory consumtion has grown by 70% compared to the working set at start of the proccess. Calling it that often in that short time may not be common but if the memory is never released this will cause OOM over time which happens on our device after about 1 month.

**Comment by BagJo** [comment]
FYI: Mono project had a similar [issue](https://github.com/mono/mono/issues/11615). 
The bug has already been fixed there. Maybe that can help to investigate the issue further.

**Comment by mdisg** [comment]
@BagJo i looked into the code of Process.Start and have not found retrieval of the path environment variable maybe i missed it.
As we use .NET 3.1 i only looked into that sources which are:

[pal_process.c](https://github.com/dotnet/corefx/blob/release/3.1/src/Native/Unix/System.Native/pal_process.c)
[Interop.ForkAndExecProcess.cs](https://github.com/dotnet/corefx/blob/release/3.1/src/Common/src/Interop/Unix/System.Native/Interop.ForkAndExecProcess.cs)

**Comment by ThomasBoettcherHolschen** [comment]
Can confirm the Memory Leak. Anybody knows a fix or workaround ?

**Comment by mdisg** [comment]
@ThomasBoettcherHolschen my workaround for the moment is a self implemented interop assembly which starts the process i need frequently by execv. I do not pass the arguments from managed code which the .net code does. But that's not an ideal solution.

**Comment by irac-ding** [comment]
It's disappointing that Microsoft has left such a serious bug alone for a year

**Comment by tmds** [comment]
A leak in `Process.Start` was fixed in .NET Core 3.1.7: https://github.com/dotnet/corefx/pull/42941, https://github.com/dotnet/runtime/issues/36661.

**Comment by mdisg** [comment]
I verified the fix with a quick test using .NET Core 3.1.9 using the sample code. The memory leak is no gone.

**Comment by ThomasBoettcherHolschen** [comment]
Thanks a lot! Great news!

**Comment by irac-ding** [comment]
> I verified the fix with a quick test using .NET Core 3.1.9 using the sample code. The memory leak is gone.

 How to install 3.1.9 intCentOS 7 ?

**Comment by mdisg** [comment]
@irac-ding you download the latest version from here https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by freddyrios** [comment]
This should be closed as resolved in both .net core 3.1.7 and .net core 5, no?

**Comment by mairaw** [comment]
@stephentoub @danmoseley can you let us know if this issue was already resolved? Trying to close some old issues.

**Comment by stephentoub** [comment]
I believe so.
