### ISSUE TITLE
api-ms-win-crt-runtime.dll is missing when i try to run dotnet via console

### ISSUE THREAD

**Issue by codemakaveli** [dotnet/core#3990]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Please see the Windows 7 prerequisites here: https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?pivots=os-windows&tabs=netcore31

**Comment by scalablecory** [comment]
Closing out, please reopen if you have more details.
