### ISSUE TITLE
Trying to install Micosoft ASP.NET

### ISSUE THREAD

**Issue by Nelsonh123** [dotnet/core#3992]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
'dotnet' is not recognized as an internal or external command error
64bit operationg system

:\Users\Dell>dotnet run
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell>

**Comment by erickvils** [comment]
Did you install the DotNet SDK for Windows 64?

After install it you can execute “dotnet” command line without the reported error. 

Download here:

[https://dotnet.microsoft.com/download](https://dotnet.microsoft.com/download)

**Comment by mairaw** [comment]
@Nelsonh123 did you try to open a new command prompt after you installed the SDK as detailed in the instructions?

**Comment by mairaw** [comment]
Closing due to the lack of response.
