### ISSUE TITLE
Unable to locate package dotnet-sdk-3.1 on Ubunto 18.04.3

### ISSUE THREAD

**Issue by PtrStruct** [dotnet/core#3993]
# I can't run the sudo apt-get install dotnet-sdk-3.1 command without getting that error

# General
I'm currently running Ubuntu 18.04.3 and I'm trying to install the .NET SDK so I can develop my ASP.NET Core 3.1 MVC web page but I keep running into that error every time I try to run it.

I even tried the manual approach it suggested.
These are the resources I've been using
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804#troubleshoot-the-package-manager

Is this a common issue?

**Comment by dagood** [comment]
Can you double check the output of the `apt-get update` step, to check for errors?

I believe you probably hit this outage, which is being worked on: https://github.com/dotnet/core/issues/3988. When the `update` fails, that means your machine isn't able to get the list of packages, so `apt-get install` will tell you `Unable to locate package`.

**Comment by dagood** [comment]
Closing due to lack of info. It seems safe to assume this was the outage, which were fixed last week.
