### ISSUE TITLE
Linux ARM package installer support

### ISSUE THREAD

**Issue by dleeapho** [dotnet/core#3996]
@fmcgarry commented on [Fri Dec 06 2019](https://github.com/dotnet/docs/issues/16144)

Are there any plans on supporting Linux ARM64 .NET Core installs through a package manager?

I'm running .NET Core on a Debian 9 ARM64 system and it would be nice to be able to install/update it through the package manager instead of having to do manual installs every time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4fb70e-8d93-5890-a259-06ae5f37c994
* Version Independent ID: 8846709d-4f43-30f8-3b09-b61dee716b90
* Content: [Install .NET Core on Debian 9 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian9#feedback)
* Content Source: [docs/core/install/linux-package-manager-debian9.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-debian9.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

---

@mairaw commented on [Fri Dec 06 2019](https://github.com/dotnet/docs/issues/16144#issuecomment-562664219)

@leecow can you help with this question about Linux ARM package installer support?

---

@leecow commented on [Fri Dec 06 2019](https://github.com/dotnet/docs/issues/16144#issuecomment-562665762)

@fmcgarry - producing installers for ARM64 is definitely on our list. Can't commit to when but we're in planning exercises for 5.0 now so we'll see if it will fit. 

/cc @dleeapho

---

@mairaw commented on [Fri Dec 06 2019](https://github.com/dotnet/docs/issues/16144#issuecomment-562668130)

Is there a better repo I should transfer this issue to @leecow?

---

@Thraka commented on [Fri Dec 13 2019](https://github.com/dotnet/docs/issues/16144#issuecomment-565578816)

Probably dotnet/core as other issues related to the linux installers are there.

**Comment by dagood** [comment]
We have some issues tracking this:
* arm (armhf) packages are tracked at https://github.com/dotnet/core-setup/issues/4419
* arm64 packages are tracked at https://github.com/dotnet/core-setup/issues/4560

Closing because the question's answered (it's on our list) and there are already issues.
