### ISSUE TITLE
Error on 'using System'

### ISSUE THREAD

**Issue by diltonnn** [dotnet/core#3998]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I followed one of the instructions to type: 'using System' and I get an error notice.

'using' is not recognized as an internal or external command,
operable program or batch file.

**Comment by scalablecory** [comment]
You're trying to type code into the console. You need to put it into a source file.

**Comment by carlossanlop** [comment]
No response since Dec 14. Closing.
