### ISSUE TITLE
dotnet run the helloworld  comes a error

### ISSUE THREAD

**Issue by biaotang** [dotnet/core#40]
Hello,   I tried to install .net core and run hello world follow the get start page, but  cannot work on ubuntu14.0.4 .   

Get start page URL: http://dotnet.github.io/getting-started/

>zero@zero:~/dotnet/core/samples/helloworld$ dotnet restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /home/zero/dotnet/core/samples/helloworld/project.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.console/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.runtime/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.runtime/index.json 1449ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime/index.json 1942ms
  OK https://api.nuget.org/v3-flatcontainer/system.console/index.json 3356ms
Writing lock file /home/zero/dotnet/core/samples/helloworld/project.lock.json
Restore complete, 4535ms elapsed

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
>zero@zero:~/dotnet/core/samples/helloworld$ dotnet run

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by ochowie** [comment]
I am getting the same issue running on Ubuntu 15.04.

**Comment by biaotang** [comment]
I restore ubuntu14.04,  and find that it works. Compare  the steps , i find that  in mint17  excute  "dotnet  restore"  , the dependence was just been load  but not install.  

>zero@zero:~/core/samples/helloworld$ dotnet restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

  GET https://api.nuget.org/v3/index.json
  OK https://api.nuget.org/v3/index.json 830ms
Restoring packages for /home/zero/core/samples/helloworld/project.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.io/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.console/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.runtime/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.runtime/index.json 6163ms
  OK https://api.nuget.org/v3-flatcontainer/system.io/index.json 6202ms
  GET https://api.nuget.org/v3-flatcontainer/system.runtime/4.0.21-beta-23516/system.runtime.4.0.21-beta-23516.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.io/4.0.11-beta-23516/system.io.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.console/index.json 6502ms
  GET https://api.nuget.org/v3-flatcontainer/system.console/4.0.0-beta-23516/system.console.4.0.0-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime/index.json 6679ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime/1.0.1-beta-23516/microsoft.netcore.runtime.1.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime/1.0.1-beta-23516/microsoft.netcore.runtime.1.0.1-beta-23516.nupkg 1111ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.coreclr/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.native/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.console/4.0.0-beta-23516/system.console.4.0.0-beta-23516.nupkg 1714ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.coreclr/index.json 336ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.coreclr/1.0.1-beta-23516/microsoft.netcore.runtime.coreclr.1.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.coreclr/1.0.1-beta-23516/microsoft.netcore.runtime.coreclr.1.0.1-beta-23516.nupkg 1293ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.windows.apisets/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.collections/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.globalization/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.objectmodel/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.threading/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.contracts/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.stacktrace/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.tools/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.globalization.calendars/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.reflection.extensions/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.resources.resourcemanager/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.handles/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.threading.timer/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.private.uri/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracing/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.reflection/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.native/index.json 1727ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.native/1.0.1-beta-23516/microsoft.netcore.runtime.native.1.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.collections/index.json 412ms
  GET https://api.nuget.org/v3-flatcontainer/system.collections/4.0.11-beta-23516/system.collections.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.io/4.0.11-beta-23516/system.io.4.0.11-beta-23516.nupkg 3903ms
  OK https://api.nuget.org/v3-flatcontainer/system.globalization.calendars/index.json 820ms
  OK https://api.nuget.org/v3-flatcontainer/system.resources.resourcemanager/index.json 815ms
  GET https://api.nuget.org/v3-flatcontainer/system.globalization.calendars/4.0.1-beta-23516/system.globalization.calendars.4.0.1-beta-23516.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.resources.resourcemanager/4.0.1-beta-23516/system.resources.resourcemanager.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.windows.apisets/index.json 1024ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.windows.apisets/1.0.1-beta-23516/microsoft.netcore.windows.apisets.1.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.runtime.native/1.0.1-beta-23516/microsoft.netcore.runtime.native.1.0.1-beta-23516.nupkg 1051ms
  OK https://api.nuget.org/v3-flatcontainer/system.reflection/index.json 5528ms
  GET https://api.nuget.org/v3-flatcontainer/system.reflection/4.1.0-beta-23516/system.reflection.4.1.0-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices/index.json 6050ms
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices/4.0.21-beta-23516/system.runtime.interopservices.4.0.21-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.resources.resourcemanager/4.0.1-beta-23516/system.resources.resourcemanager.4.0.1-beta-23516.nupkg 6124ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracing/index.json 7063ms
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracing/4.0.21-beta-23516/system.diagnostics.tracing.4.0.21-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.windows.apisets/1.0.1-beta-23516/microsoft.netcore.windows.apisets.1.0.1-beta-23516.nupkg 6242ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.handles/index.json 7505ms
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.handles/4.0.1-beta-23516/system.runtime.handles.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.threading.timer/index.json 7553ms
  GET https://api.nuget.org/v3-flatcontainer/system.threading.timer/4.0.1-beta-23516/system.threading.timer.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/index.json 7573ms
  GET https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/4.0.1-beta-23516/system.reflection.primitives.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.reflection.extensions/index.json 7627ms
  GET https://api.nuget.org/v3-flatcontainer/system.reflection.extensions/4.0.1-beta-23516/system.reflection.extensions.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.reflection/4.1.0-beta-23516/system.reflection.4.1.0-beta-23516.nupkg 2315ms
  OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks/index.json 8177ms
  GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.0.11-beta-23516/system.threading.tasks.4.0.11-beta-23516.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.0.0/system.threading.tasks.4.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.objectmodel/index.json 8371ms
  GET https://api.nuget.org/v3-flatcontainer/system.objectmodel/4.0.11-beta-23516/system.objectmodel.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.contracts/index.json 8373ms
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.contracts/4.0.1-beta-23516/system.diagnostics.contracts.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.threading/index.json 8473ms
  GET https://api.nuget.org/v3-flatcontainer/system.threading/4.0.11-beta-23516/system.threading.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/index.json 8571ms
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/4.0.11-beta-23516/system.text.encoding.extensions.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.globalization/index.json 8723ms
  GET https://api.nuget.org/v3-flatcontainer/system.globalization/4.0.11-beta-23516/system.globalization.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.globalization.calendars/4.0.1-beta-23516/system.globalization.calendars.4.0.1-beta-23516.nupkg 7931ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.stacktrace/index.json 8994ms
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.stacktrace/4.0.1-beta-23516/system.diagnostics.stacktrace.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.private.uri/index.json 9048ms
  GET https://api.nuget.org/v3-flatcontainer/system.private.uri/4.0.1-beta-23516/system.private.uri.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/index.json 9126ms
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/4.0.11-beta-23516/system.diagnostics.debug.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.tools/index.json 9143ms
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.tools/4.0.1-beta-23516/system.diagnostics.tools.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracing/4.0.21-beta-23516/system.diagnostics.tracing.4.0.21-beta-23516.nupkg 2168ms
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding/index.json 9267ms
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.0.11-beta-23516/system.text.encoding.4.0.11-beta-23516.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.0.0/system.text.encoding.4.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.threading.timer/4.0.1-beta-23516/system.threading.timer.4.0.1-beta-23516.nupkg 1746ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.handles/4.0.1-beta-23516/system.runtime.handles.4.0.1-beta-23516.nupkg 2347ms
  OK https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/4.0.1-beta-23516/system.reflection.primitives.4.0.1-beta-23516.nupkg 2411ms
  OK https://api.nuget.org/v3-flatcontainer/system.private.uri/4.0.1-beta-23516/system.private.uri.4.0.1-beta-23516.nupkg 1008ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.stacktrace/4.0.1-beta-23516/system.diagnostics.stacktrace.4.0.1-beta-23516.nupkg 1132ms
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.0.0/system.text.encoding.4.0.0.nupkg 7665ms
  OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.0.0/system.threading.tasks.4.0.0.nupkg 9063ms
  OK https://api.nuget.org/v3-flatcontainer/system.objectmodel/4.0.11-beta-23516/system.objectmodel.4.0.11-beta-23516.nupkg 9053ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/index.json 17782ms
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/4.0.11-beta-23516/system.runtime.extensions.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.0.11-beta-23516/system.text.encoding.4.0.11-beta-23516.nupkg 9211ms
  OK https://api.nuget.org/v3-flatcontainer/system.reflection.extensions/4.0.1-beta-23516/system.reflection.extensions.4.0.1-beta-23516.nupkg 10856ms
  OK https://api.nuget.org/v3-flatcontainer/system.globalization/4.0.11-beta-23516/system.globalization.4.0.11-beta-23516.nupkg 10077ms
  OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.0.11-beta-23516/system.threading.tasks.4.0.11-beta-23516.nupkg 11024ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.tools/4.0.1-beta-23516/system.diagnostics.tools.4.0.1-beta-23516.nupkg 10405ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/4.0.11-beta-23516/system.diagnostics.debug.4.0.11-beta-23516.nupkg 11260ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices/4.0.21-beta-23516/system.runtime.interopservices.4.0.21-beta-23516.nupkg 15184ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.contracts/4.0.1-beta-23516/system.diagnostics.contracts.4.0.1-beta-23516.nupkg 13472ms
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/4.0.11-beta-23516/system.text.encoding.extensions.4.0.11-beta-23516.nupkg 14477ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/4.0.11-beta-23516/system.runtime.extensions.4.0.11-beta-23516.nupkg 5429ms
  OK https://api.nuget.org/v3-flatcontainer/system.threading/4.0.11-beta-23516/system.threading.4.0.11-beta-23516.nupkg 31571ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime/4.0.21-beta-23516/system.runtime.4.0.21-beta-23516.nupkg 43693ms
  OK https://api.nuget.org/v3-flatcontainer/system.collections/4.0.11-beta-23516/system.collections.4.0.11-beta-23516.nupkg 43323ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.ubuntu.14.04-x64.microsoft.netcore.runtime.coreclr/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.diagnostics.debug/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.linux.system.runtime.extensions/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.threading/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.private.uri/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.console/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.private.uri/index.json 684ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.private.uri/4.0.1-beta-23516/runtime.unix.system.private.uri.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.console/index.json 1301ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.console/4.0.0-beta-23516/runtime.unix.system.console.4.0.0-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.diagnostics.debug/index.json 1364ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.diagnostics.debug/4.0.11-beta-23516/runtime.unix.system.diagnostics.debug.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.threading/index.json 1358ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.unix.system.threading/4.0.11-beta-23516/runtime.unix.system.threading.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.linux.system.runtime.extensions/index.json 1723ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.linux.system.runtime.extensions/4.0.11-beta-23516/runtime.linux.system.runtime.extensions.4.0.11-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.private.uri/4.0.1-beta-23516/runtime.unix.system.private.uri.4.0.1-beta-23516.nupkg 1178ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.ubuntu.14.04-x64.microsoft.netcore.runtime.coreclr/index.json 1931ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.ubuntu.14.04-x64.microsoft.netcore.runtime.coreclr/1.0.1-beta-23516/runtime.ubuntu.14.04-x64.microsoft.netcore.runtime.coreclr.1.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.console/4.0.0-beta-23516/runtime.unix.system.console.4.0.0-beta-23516.nupkg 645ms
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices/4.0.20/system.runtime.interopservices.4.0.20.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.resources.resourcemanager/4.0.0/system.resources.resourcemanager.4.0.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.handles/4.0.0/system.runtime.handles.4.0.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.io.filesystem.primitives/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.linq/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.0.10/system.threading.tasks.4.0.10.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.0.10/system.text.encoding.4.0.10.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.collections/4.0.10/system.collections.4.0.10.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.threading/4.0.10/system.threading.4.0.10.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/4.0.10/system.text.encoding.extensions.4.0.10.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/4.0.10/system.runtime.extensions.4.0.10.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.diagnostics.debug/4.0.11-beta-23516/runtime.unix.system.diagnostics.debug.4.0.11-beta-23516.nupkg 1037ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.unix.system.threading/4.0.11-beta-23516/runtime.unix.system.threading.4.0.11-beta-23516.nupkg 1303ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.linux.system.runtime.extensions/4.0.11-beta-23516/runtime.linux.system.runtime.extensions.4.0.11-beta-23516.nupkg 1659ms
  OK https://api.nuget.org/v3-flatcontainer/system.io.filesystem.primitives/index.json 1499ms
  GET https://api.nuget.org/v3-flatcontainer/system.io.filesystem.primitives/4.0.0/system.io.filesystem.primitives.4.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.linq/index.json 1692ms
  GET https://api.nuget.org/v3-flatcontainer/system.linq/4.0.0/system.linq.4.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.resources.resourcemanager/4.0.0/system.resources.resourcemanager.4.0.0.nupkg 1959ms
  GET https://api.nuget.org/v3-flatcontainer/system.reflection/4.0.0/system.reflection.4.0.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/system.globalization/4.0.0/system.globalization.4.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.threading/4.0.10/system.threading.4.0.10.nupkg 3405ms
  OK https://api.nuget.org/v3-flatcontainer/system.io.filesystem.primitives/4.0.0/system.io.filesystem.primitives.4.0.0.nupkg 2481ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.handles/4.0.0/system.runtime.handles.4.0.0.nupkg 4286ms
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/4.0.10/system.text.encoding.extensions.4.0.10.nupkg 4615ms
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.0.10/system.text.encoding.4.0.10.nupkg 5413ms
  OK https://api.nuget.org/v3-flatcontainer/system.reflection/4.0.0/system.reflection.4.0.0.nupkg 3987ms
  GET https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/4.0.0/system.reflection.primitives.4.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/4.0.10/system.runtime.extensions.4.0.10.nupkg 6190ms
  OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.0.10/system.threading.tasks.4.0.10.nupkg 6475ms
  OK https://api.nuget.org/v3-flatcontainer/system.collections/4.0.10/system.collections.4.0.10.nupkg 6789ms
  OK https://api.nuget.org/v3-flatcontainer/system.globalization/4.0.0/system.globalization.4.0.0.nupkg 5742ms
  OK https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/4.0.0/system.reflection.primitives.4.0.0.nupkg 1844ms
  OK https://api.nuget.org/v3-flatcontainer/system.linq/4.0.0/system.linq.4.0.0.nupkg 6300ms
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/4.0.10/system.diagnostics.debug.4.0.10.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/4.0.10/system.diagnostics.debug.4.0.10.nupkg 1135ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices/4.0.20/system.runtime.interopservices.4.0.20.nupkg 11000ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.ubuntu.14.04-x64.microsoft.netcore.runtime.coreclr/1.0.1-beta-23516/runtime.ubuntu.14.04-x64.microsoft.netcore.runtime.coreclr.1.0.1-beta-23516.nupkg 56973ms
Installing System.Console.4.0.0-beta-23516
Installing System.IO.4.0.11-beta-23516
Installing System.Text.Encoding.4.0.0
Installing System.Threading.Tasks.4.0.0
Installing System.Runtime.4.0.21-beta-23516
Installing System.Private.Uri.4.0.1-beta-23516
Installing Microsoft.NETCore.Runtime.1.0.1-beta-23516
Installing Microsoft.NETCore.Runtime.CoreCLR.1.0.1-beta-23516
Installing System.Resources.ResourceManager.4.0.1-beta-23516
Installing Microsoft.NETCore.Windows.ApiSets.1.0.1-beta-23516
Installing System.Reflection.4.1.0-beta-23516
Installing System.Globalization.Calendars.4.0.1-beta-23516
Installing System.Diagnostics.Tracing.4.0.21-beta-23516
Installing System.Threading.Timer.4.0.1-beta-23516
Installing System.Runtime.Handles.4.0.1-beta-23516
Installing System.Reflection.Primitives.4.0.1-beta-23516
Installing System.Diagnostics.StackTrace.4.0.1-beta-23516
Installing System.ObjectModel.4.0.11-beta-23516
Installing System.Text.Encoding.4.0.11-beta-23516
Installing System.Reflection.Extensions.4.0.1-beta-23516
Installing System.Globalization.4.0.11-beta-23516
Installing System.Threading.Tasks.4.0.11-beta-23516
Installing System.Diagnostics.Tools.4.0.1-beta-23516
Installing System.Diagnostics.Debug.4.0.11-beta-23516
Installing System.Runtime.InteropServices.4.0.21-beta-23516
Installing System.Diagnostics.Contracts.4.0.1-beta-23516
Installing System.Text.Encoding.Extensions.4.0.11-beta-23516
Installing System.Runtime.Extensions.4.0.11-beta-23516
Installing System.Threading.4.0.11-beta-23516
Installing System.Collections.4.0.11-beta-23516
Installing Microsoft.NETCore.Runtime.Native.1.0.1-beta-23516
Installing runtime.unix.System.Private.Uri.4.0.1-beta-23516
Installing runtime.unix.System.Console.4.0.0-beta-23516
Installing System.Threading.4.0.10
Installing runtime.unix.System.Threading.4.0.11-beta-23516
Installing System.IO.FileSystem.Primitives.4.0.0
Installing System.Runtime.Handles.4.0.0
Installing System.Text.Encoding.Extensions.4.0.10
Installing System.Text.Encoding.4.0.10
Installing System.Runtime.Extensions.4.0.10
Installing runtime.linux.System.Runtime.Extensions.4.0.11-beta-23516
Installing System.Threading.Tasks.4.0.10
Installing System.Collections.4.0.10
Installing System.Resources.ResourceManager.4.0.0
Installing System.Globalization.4.0.0
Installing System.Reflection.4.0.0
Installing System.Reflection.Primitives.4.0.0
Installing System.Linq.4.0.0
Installing System.Diagnostics.Debug.4.0.10
Installing runtime.unix.System.Diagnostics.Debug.4.0.11-beta-23516
Installing System.Runtime.InteropServices.4.0.20
Installing runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.1-beta-23516
Writing lock file /home/zero/core/samples/helloworld/project.lock.json
Restore complete, 115639ms elapsed

Feeds used:
    https://api.nuget.org/v3-flatcontainer/

Installed:
    52 package(s) to /home/zero/.dnx/packages
>zero@zero:~/core/samples/helloworld$ dotnet run
Hello World!

**Comment by biaotang** [comment]
“dotnet restore --runtime ubuntu.14.04-x64”  may  helps .   refer to  https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.ProjectModel/RuntimeIdentifier.cs
