### ISSUE TITLE
'Cannot find or open the symbol file' while debugging after following OSX install page instructions

### ISSUE THREAD

**Issue by replete** [dotnet/core#400]
Did everything [here](https://www.microsoft.com/net/core#macos), and I'm getting a wall of text each time:

```
Loaded '/Users/phil/Projects/curo/bin/Debug/netcoreapp1.1/curo.dll'. Symbols loaded.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Runtime.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/mscorlib.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Console.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.IO.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Threading.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.IO.FileSystem.Primitives.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Runtime.Handles.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Text.Encoding.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Runtime.Extensions.dll'. Cannot find or open the symbol file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Threading.Tasks.dll'. Cannot find or open the symbol file.
Hello World!
The program '/Users/phil/Projects/curo/bin/Debug/netcoreapp1.1/curo.dll' has exited with code 0 (0x00000000).
```

I downloaded [this](https://go.microsoft.com/fwlink/?LinkID=835011) package, and installed in OSX 10.11.6.

Is this file missing symbols? Should I use something else to install dotnet core?

**Comment by Joker666** [comment]
+1

**Comment by erhanyasar** [comment]
+1

There is no related app seen on Mac Sierra even after installed .Net Core 1.1 or 1.0.3. Niether I could find any related symbol to be able to execute.

**Comment by andrius-k** [comment]
It appears that those are just informational messages from debugger stating that we will not be able to step into dot net core libraries. This behavior is just fine because usually we don't have to debug .net libraries. Your app should run without problems and debugging (your own code) should also work. But is there any way to disable these messages? Because there are quite a few of them and they are very annoying.

**Comment by Petermarcu** [comment]
Are you using VS Code to launch the debugger?

**Comment by andrius-k** [comment]
Hey @Petermarcu. For me, yes, this happens when using VS Code to launch debugger.

**Comment by replete** [comment]
@Petermarcu Yes, VsCode.  I thought this was the best way to get going with .Net Core.  Of course there's the mac 'Visual Studio' now.

The point is - where's the information? 

What any normal user needs to know about this:

* Did I miss something in my install? Did I do something wrong. _What a waste of time :|_
* How do I get the missing files?
* How can I hide this information?

**Comment by Petermarcu** [comment]
@replete the reason I asked was to make sure the right people get looped in. @DustinCampbell @gregg-miskelly any idea whats going on here?

**Comment by gregg-miskelly** [comment]
Unless you are trying to debug into CoreFX, seeing a `Cannot find or open the symbol file' isn't actually a problem. We are planning to remove this message in the future (tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/837).

**Comment by replete** [comment]
@gregg-miskelly Thanks for responding. I know it's not a problem. But flagged it for new users.

It was such a bad 'get started' experience on mac, that I gave up and built my app in node. And I _really_ want to use dotnetcore. Just too frustrating right now. Clearly, VS on Windows is where it's at for getting started at the moment. It changes often.

What the project _really_ needs is someone who can own the user experience of getting started.

Meanwhile, I just hope 2.0 gets shipped _when it's ready_, rather than with a ton of gotchas.

**Comment by Petermarcu** [comment]
@richlander @blackdwarf for the getting started experience. Agreed we need to make it seamless for all our supported developer environments.

**Comment by gregg-miskelly** [comment]
@replete I am assuming you are referring to something more than the fact that the debugger says `Cannot find or open the symbol file`?

**Comment by replete** [comment]
@gregg-miskelly Yes. Documentation issues, Samples out of date in repos. Off-issue but relevant tangent captured elsewhere

**Comment by Petermarcu** [comment]
Thanks for the feedback @replete . I'm going to close this issue as its tracked here: OmniSharp/omnisharp-vscode#837
