### ISSUE TITLE
Having issues trying to complete the command

### ISSUE THREAD

**Issue by Nelsonh123** [dotnet/core#4003]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\Dell\myWebApp> dotnet run
obj\Debug\netcoreapp3.1\Razor\Pages\Index.cshtml.g.cs(57,71): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Dell\myWebApp\myWebApp.csproj]
obj\Debug\netcoreapp3.1\Razor\Pages\Index.cshtml.g.cs(58,81): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Dell\myWebApp\myWebApp.csproj]
obj\Debug\netcoreapp3.1\Razor\Pages\Index.cshtml.g.cs(59,16): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Dell\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by scalablecory** [comment]
@Pilchie

**Comment by Pilchie** [comment]
Hi @Nelsonh123 sorry for the delay - are you still blocked here?  If so, can you share your project somewhere?

**Comment by carlossanlop** [comment]
No replies since December 17. Closing.
