### ISSUE TITLE
microservice-tutorial: Docker build fails because of incompatible sdk version

### ISSUE THREAD

**Issue by jonasatadesso** [dotnet/core#4004]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Build failes with

```
/usr/share/dotnet/sdk/2.2.207/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/src/myMicroservice.csproj]
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1
```

After changing the dockerfile, it worked:

```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY myMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]
```

**Comment by bakhodir1986** [comment]
Thank you

**Comment by akselsoft** [comment]
After following the tutorial, the next fail is that it's missing all of the namespace references.
(this was noted on a Mac OS)

**Comment by mairaw** [comment]
It seems you don't have the latest SDK installed. Can you `dotnet --info` to see if you're running version 3.1 @jonasatadesso?

**Comment by jonasatadesso** [comment]
According to dotnet –info I’m running this:

Version:   3.1.101
Commit:    b377529961

IT Dienstleistungen fuer die Zeit der Krise
https://www.adesso.de/de/impulse/it-dienstleistungen-fuer-die-zeit-der-krise/index.jsp?pk_campaign=IT_Dienstleistungen_fuer_die_Zeit_der_Krise&pk_source=Signatur&pk_medium=Banner



-------------------------------------------------------
     >>> business. people. technology. <<<
-------------------------------------------------------

adesso SE mit Sitz in Dortmund
Vorstand: Michael Kenfenheuer (Vors.), Dirk Pothen, Andreas Prenneis, Stefan Riedel, Jörg Schroeder
Vorsitzender des Aufsichtsrates: Prof. Dr. Volker Gruhn
Amtsgericht Dortmund HRB 20663

**Comment by mairaw** [comment]
Thanks @jonasatadesso. I'm wondering if this was due to the Dockerfile being outdated on the site. That has been fixed on the site back in January.

So, I believe the issue was fixed.
