### ISSUE TITLE
Project Properties Page Saves Automatically

### ISSUE THREAD

**Issue by michaelbunney** [dotnet/core#4008]
STEPS:
1. Select a web project and choose Project > Properties.
2. On the Debug tab, start typing in the "Launch browser" box.
    Note that page title now has an asterisk (*) indicating page has unsaved changes.
3. Realize that you made a mistake and close the page.

RESULTS:
- You are not asked whether you want to save changes.
- The change you "discarded" is saved, and reopening the page does not take you back to the last version you actually saved.

EXPECTED:
- Prompt for confirmation before saving changes.
- Able to discard changes.

REMARKS:
Autosave is now default behavior in Office apps, but not in VS.  This page should not behave differently from all the other document windows in Visual Studio, especially when it results in data loss.

**Comment by scalablecory** [comment]
This repo is for .NET Core issues, but you're looking at a VS behavior. To report a VS issue, you can go in VS menus: Help > Send Feedback > Report a Problem. Thanks.
