### ISSUE TITLE
Questions about implementing tty communication code on Linux.

### ISSUE THREAD

**Issue by gaessanty** [dotnet/core#4009]
Hi.
I am writing a code in Linux that sends AT Command to a mobile phone and receives a response.

The command using bash
Send message
`bash$ echo "AT\r" > /dev/ttyACM0`

Receive message
`bash$ cat < /dev/ttyACM0`
`AT OK`

The code I wrote is this
program hangs at File.ReadAllText() Is there a way to solve this?

        static void Main(string[] args)
        {
            string cmd = "AT";
            string hwID = "/dev/ttyACM0";

            Send($"echo \"{cmd}\r\" > {hwID}");

            Console.WriteLine(Receive(hwID));
        }

        static void Send(string cmd)
        {
            var escapedArgs = cmd.Replace("\"", "\\\"");

            var process = new Process()
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = "/bin/bash",
                    Arguments = $"-c \"{escapedArgs}\"",
                    UseShellExecute = false,
                    CreateNoWindow = true,
                }
            };

            process.Start();
            process.WaitForExit();
        }

        static string Receive(string hwID)
        {
            return File.ReadAllText("/dev/ttyACM0");
        }

**Comment by bartonjs** [comment]
`ReadAllText()` won't finish until it gets an end of file; it wouldn't be useful for TTY send/receive/send.

**Comment by carlossanlop** [comment]
Answered. Closing.
