### ISSUE TITLE
Unable to run single file app as different users

### ISSUE THREAD

**Issue by bnls** [dotnet/core#4011]
## Environment
- Ubuntu 16.04
- .Net Core 3.0

## Steps to Reproduce
1. Create a single file app by publishing it with PublishSingleFile=true.
2. Run it as a user (eg. `user1`) and it works fine.
3. Now run it as another user (eg. `user2`), and the following error is produced:
```
Failure processing application bundle.
Failed to create directory [/var/tmp/.net/MyApp/] for extracting bundled files
A fatal error was encountered. Could not extract contents of the bundle
```

## Analysis
The /var/tmp/.net directory and subdirectories were created by `user1` with no read or write permissions for other users.
```
drwx------ 7 user1 user1 4.0K Dec 18 11:48 /var/tmp/.net
```

When `user2` tries to run an app, they don't have permission to extract to this location so they are unable to run the app.

## Possible Solutions
- Create the directories with read/write access for all users (which introduces security issues)
- Or, extract the application contents to a user specific directory, eg. ~/.dotnet

**Comment by omajid** [comment]
cc @tmds

**Comment by genifycom** [comment]
Facing this in production on Windows 10 Server as well.

**Comment by tmds** [comment]
You can override the location using the `DOTNET_BUNDLE_EXTRACT_BASE_DIR` envvar.

For example, add this line to `/etc/profile`:
```
[ -z "$DOTNET_BUNDLE_EXTRACT_BASE_DIR" ] && export DOTNET_BUNDLE_EXTRACT_BASE_DIR="${XDG_CACHE_HOME:-"$HOME"/.cache}/dotnet_bundle_extract"
```

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/core-setup/issues/8882
