### ISSUE TITLE
Building UAP project does not work on Visual Studio Mac, understandably...

### ISSUE THREAD

**Issue by olivegamestudio** [dotnet/core#4012]
I'm trying to multi-targeting on my Mac, and I can do the first three targets but UAP is a non-starter.

Is there anyway to ignore this platform if it doesnt exist? Is there another way to do this without creating another project? Is there something i missed a different target perhaps?

I apologise if this is not the right location for this issue.

Example:

```
<Project Sdk="MSBuild.Sdk.Extras/2.0.54">

  <PropertyGroup>
    <TargetFrameworks>xamarinios10;monoandroid71;net461;uap</TargetFrameworks>
  </PropertyGroup>
   
    <ItemGroup>
        <PackageReference Include="MSBuild.Sdk.Extras" Version="2.0.54" />  
    </ItemGroup>
    
</Project>
```

**Comment by scalablecory** [comment]
@safern @ViktorHofer is there some conditional statement that can be used here?

**Comment by safern** [comment]
I don't think there is a way to know if the tfm is supported for the current built OS via a property. However there is a property that MSBuild populates to tell you which OS you're building on. So basically you could condition based on that. 

You could do something like:
```xml
<PropertyGroup>
  <TargetFrameworks>xamarinios10;monoandroid71</TargetFrameworks>
  <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">$(TargetFrameworks);net461;uap</TargetFrameworks>
</PropertyGroup>
```

**Comment by ViktorHofer** [comment]
What @safern says makes most sense. Community members ued the same mechanism for .NET Framework back when reference assemblies weren't available for it.

**Comment by ViktorHofer** [comment]
Closing as question is answered. Feel free to reopen if you disagree.
