### ISSUE TITLE
SendKeys.SendWait() sends wrong characters for some particular characters

### ISSUE THREAD

**Issue by Naimad1CZ** [dotnet/core#4016]
Using:
Windows 10
.NET Core 3.1
Library System.Windows.Forms
Function SendKeys.SendWait()

Reproduce steps:
1. create a new project with those 2 lines in Main:
```
Thread.Sleep(5000);
SendKeys.SendWait("ĚŠČŘŽÝÁÍÉÚŮĎŤ");
```
2. Switch to Czech QWERTZ keyboard on Windows (on standard English keyboard you get the expected result)
3. Run the project and (during the first 5 second since the start) open some notepad or something like this
4. observe `ěščřžýáíéúůĎŤ` being written

Expected result:
observe `ĚŠČŘŽÝÁÍÉÚŮĎŤ` being written

Note + possible cause of problem:
On Czech Keyboard, all of letters `ĚŠČŘŽÝÁÍÉÚŮ` could be written by pressing a single button on keyboard in case that `CapsLock` is turned on, but `ĎŤ` couln't (`Ď` has to be written by pressing `ˇ` (actually `Shift` + key on the left of Backspace) and then `D` (`Shift` + `d`)), so maybe SendWait() gets info about keyboard keys, and if the characters that could be written on this keyboard using 1 key (+`Shift`/`CapsLock`), then it presses according keys, but in other case, it just presses maybe `Alt`+KeyCode or something. And in the first case, it forgets about pressing `CapsLock` when writing letters that are keyboard language-dependent.

**Comment by scalablecory** [comment]
This issue was moved to dotnet/winforms#2660
