### ISSUE TITLE
Will VS 2019 support NET 5 past preview ?

### ISSUE THREAD

**Issue by voltcode** [dotnet/core#4019]
I'd like to know whether NET 5 that is due November 2020 as per roadmap, will be supported in full in VS 2019, or maybe an upgrade to VS 2021 will be required to develop on NET 5 (stable, non-preview version)?

**Comment by scalablecory** [comment]
It might be too early to know. @richlander any plans yet on what VS versions will support .NET 5?

**Comment by richlander** [comment]
I haven't heard anything on this topic. My working theory is that .NET 5 (stable) will be supported in VS 2019. No one has said anything to the contrary.
