### ISSUE TITLE
Problem blazorwasm Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder

### ISSUE THREAD

**Issue by toshiossada** [dotnet/core#4027]
Hello everyone, I'm trying Blazor but I got some troubles.
I simply create a new project with blazorwasm but when I try to build I get some erros.

```
dotnet new blazorwasm -o WebApplication4
cd WebApplication4\
dotnet build
```

> obj\Debug\netstandard2.0\RazorDeclaration\App.razor.g.cs(49,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]
> obj\Debug\netstandard2.0\RazorDeclaration\Shared\MainLayout.razor.g.cs(49,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]
> obj\Debug\netstandard2.0\RazorDeclaration\Shared\NavMenu.razor.g.cs(49,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]
> obj\Debug\netstandard2.0\RazorDeclaration\Shared\SurveyPrompt.razor.g.cs(49,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]
> obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(51,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]
> obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(51,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]
> obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(51,91): error CS0234: O nome de tipo ou namespace "RenderTreeBuilder" não existe no namespace "Microsoft.AspNetCore.Components.Rendering" (você está sem uma referência de assembly?) [C:\projetos\blazor\blazor_1\WebApplication4\WebApplication4.csproj]

I'm using dotnet --version 3.1.100

A solution that I find is replace every 

> Microsoft.AspNetCore.Components.**Rendering**.RenderTreeBuilder

to
> Microsoft.AspNetCore.Components.**RenderTree**.RenderTreeBuilder

this works but I need to do this every build

**Comment by scalablecory** [comment]
Seems like this might be a renamed type and a template that wasn't updated. Hopefully this is solved by now -- @Pilchie do you remember anything around this?

**Comment by Pilchie** [comment]
@danroth27 @SteveSandersonMS @mkArtakMSFT ?

**Comment by danroth27** [comment]
Hi @toshiossada. Could you please try installing the latest .NET Core 3.1 SDK (version 3.1.400 or later) and see if that addresses the issue you're seeing?

**Comment by SteveSandersonMS** [comment]
The type `RenderTreeBuilder` should be in the namespace `Microsoft.AspNetCore.Components.Rendering`, *not* `Microsoft.AspNetCore.Components.RenderTreeBuilder`. We moved it a really long time ago - before ASP.NET Core 3.0 shipped last November.

Since you're getting this error, it suggests you're trying to use some really old pre-3.0 preview versions of the framework libraries. So I agree that @danroth27's suggestion is the right thing to try - make sure you're on an up-to-date SDK, both when you create the project and when you compile and run it.
