### ISSUE TITLE
Outdated Release Notes

### ISSUE THREAD

**Issue by snovak7** [dotnet/core#4029]
# Issue Title

Outdated Release Notes

# General

I want to use newer version of DotNetCore in Azure DevOps Server 2019 and I get that information couldn't be fetched for version 3.1.0, upon inspecting the https://github.com/dotnet/core/blob/master/release-notes/releases.json

I saw that after 3.0-preview3 there are no more entries.

**Comment by jkateva** [comment]
I have exactly the same problem. Here are some details: I use the task "DotNetCoreInstaller@0" in Azure DevOps Server 2019. That task will fetch the .NET Core SDK versions from file https://github.com/dotnet/core/blob/master/release-notes/releases.json, which does not seem to contain .NET Core versions after 3.0-preview3 like said above.

Will that release list be updated at some point or is it considered as deprecated?

I know that the task "UseDotNet@2" is able to install even 3.1 versions as it uses different release listing, but unfortunately, Azure DevOps Server 2019 does not include that task.

**Comment by omajid** [comment]
> Will that release list be updated at some point or is it considered as deprecated?

It was announced that the "older" releases.json file has been deprecated and will be removed: https://github.com/dotnet/announcements/issues/87

https://github.com/dotnet/core/issues/2758 has some suggestions on what to do. They suggest using `DotNetCoreInstaller@2` if possible.

**Comment by snovak7** [comment]
It's not possible, that's the problem! There's no "DotNetCoreInstaller@2" just @0

**Comment by jkateva** [comment]
We had to work-around this by installing dotnet SDK manually, not great but works. I guess there is nothing that can be done here, should be fixed on Azure Server side then.

**Comment by Xavina** [comment]
I think we can close this one.

'releases.json' was finally deprecated in favour of 'releases-index.json' (https://github.com/dotnet/core/blob/master/release-notes/releases-index.json).

**Comment by snovak7** [comment]
Updating Azure DevOps Server fixed the issue with me.
