### ISSUE TITLE
[IgnoreAntiforgeryToken] not working with .net core 1.1.0. It is working with .net core 1.0.

### ISSUE THREAD

**Issue by chintan3100** [dotnet/core#403]
Thanks for your interest in .NET Core. 

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

**Comment by chintan3100** [comment]
For reproduce issue apply attribute   [ValidateAntiForgeryToken] on class level and use    [IgnoreAntiforgeryToken] on some of method

**Comment by nielstanis** [comment]
+1 on this, ran into the same problem today.

**Comment by Petermarcu** [comment]
I moved this issue to: https://github.com/aspnet/Mvc/issues/5657
