### ISSUE TITLE
on running the command "dotnet new webapi -o myMicroservice --no-https " the generated code does not have any file called "WeatherForecastController.cs".

### ISSUE THREAD

**Issue by devasishmudoi** [dotnet/core#4030]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rkrishnav** [comment]
Yes. I experienced the same. I see the controller named ValuesController got created and proceeded with that and worked

**Comment by mairaw** [comment]
That is not expected. Can you confirm what version of the .NET Core SDK you're running? You can type dotnet --info to see that.
Thanks!

**Comment by mairaw** [comment]
Closing due to the lack of response.
