### ISSUE TITLE
Dotnet

### ISSUE THREAD

**Issue by Su1616** [dotnet/core#4033]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
You'll need to provide some details -- what're you having trouble with?

**Comment by scalablecory** [comment]
Closing due to lack of response -- please reopen if you can provide detail.

**Comment by scalablecory** [comment]
Duplicate of #4166
