### ISSUE TITLE
i cant run these code @page @model IndexModel @{     ViewData["Title"] = "Home page"; } <div class="text-center">     <h1>Hello, world!</h1>     <p>The time on the server is @DateTime.Now</p> </div>

### ISSUE THREAD

**Issue by birju1992** [dotnet/core#4037]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
No response in 2 weeks. Closing.
