### ISSUE TITLE
ContentControl Content Property Binding Breaks after a few changes

### ISSUE THREAD

**Issue by alexdbatschi** [dotnet/core#4039]
# ContentControl Content Property Binding Breaks after a few changes

I have a very simple wpf app running on .net core 3.1 in which I have a ContentControl with a content bound to a property. I initialize and set this property to null resulting in a ControlTemplate showing and not showing per commands. After 2-4 times of this interaction (showing a popup then closing the popup), the binding just breaks. I can tell this is the binding because if I watch for a change in the property and then set the content on the ContentControl directly it will work just fine.

**Comment by scalablecory** [comment]
Can you provide some small sample code showing the issue?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide more detail.
