### ISSUE TITLE
Received a build Error

### ISSUE THREAD

**Issue by subhromisra** [dotnet/core#4042]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My operating System version is Mac 10.14 Mojave
I got the below error

```
Program.cs(4,7): error CS0246: The type or namespace name 'Internal' could not be found (are you missing a using directive or an assembly reference?) [/Users/subhro/Documents/programming/dotnetCore/dotnetCore.csproj]
The build failed. Fix the build errors and run again.
```

This is after the normal Hello World run. Meaning, I just added another Console.WriteLine statement with only a string.

The code snippet that fails for me is 
```
using Internal;
using System;

namespace dotnetCore
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("This is another line");
        }
    }
}
```

**Comment by scalablecory** [comment]
the `using Interal;` line is causing the issue. You have no "Internal" namespace in your project.
