### ISSUE TITLE
.NET Core installer with option to remove older versions

### ISSUE THREAD

**Issue by RomBrz** [dotnet/core#4046]
# Issue Title

.NET Core installer with option to remove older versions

# General

I would like to suggest an option to remove older versions of .NET Core when installing new ones. 
i know that they are cumulative and i don't HAVE to uninstall, but i don't se a reason to keep many .NET Core versions, as they have backward compatibility with same family versions..

I have a server with a lot of projects with each one using a specific .NET Core family. So, for example, i have 3.0.0 installed on  and want to install the 3.0.1 version. I always remove the 3.0.0 and keep only the 3.0.1 (so the new project that use 3.0.1 version can use it, while the project that still use 3.0.0 will work with the 3.0.1 too).

Maybe a parameter to install with Powershell to automatically remove older versions and keep just the last one.

So right now i have on my machine onlye the v2.0.9, v2.1.14, v2.2.8, v3.0.1 and v3.1.0.

When the 2.1.15 arrive, i will remove the 2.1.14 and keep only the 2.1.15.. but always have to manually uninstall the older one (and this have a second problem that i will post in another thread).

Thanks for the attention

**Comment by scalablecory** [comment]
@dagood

**Comment by dagood** [comment]
> I always remove the 3.0.0 and keep only the 3.0.1 (so the new project that use 3.0.1 version can use it, while the project that still use 3.0.0 will work with the 3.0.1 too).

> When the 2.1.15 arrive, i will remove the 2.1.14 and keep only the 2.1.15.. but always have to manually uninstall the older one (and this have a second problem that i will post in another thread).

The runtime installers are designed to do this automatically (always). For runtimes, 3.0 is the "product band" and installing a newer patch will remove the older patch as part of the upgrade. I guess we'll get into what's happening in your case in the other issue! 😄

**Comment by RomBrz** [comment]
> The runtime installers for Windows are designed to do this automatically (always). For runtimes, 3.0 is the "product band" and installing a newer patch will remove the older patch as part of the upgrade. I guess we'll get into what's happening in your case in the other issue! 😄

In this issue the main question is that installing a newer version, the Windows installer always keep the older. So if i'm installed every 2.2 version, i will have 2.2.1, 2.2.2, 2.2.3, 2.2.4, etc, until i choose to manually uninstall the older versions. This is the default behavior? If i didn't uninstall, i will keep every version installed?

If this is the behavior, there's come my suggestion to give an option to "clear the server" during the install, something like "Click here to install .NET Core 2.2.8 and uninstall from 2.2.0 to 2.2.7".

If this is not the behavior and by default a newer .NET Core uninstall older versions, so i have a problem 😅

About the other issue: https://github.com/dotnet/core/issues/4047
To install, just the Server Hosting Bundle that install 3 itens. To uninstall, i have to uninstall 3 itens.

Thanks!

**Comment by dagood** [comment]
Ah, sorry, it slipped my mind that the "upgrade in place" behavior that uninstalls old patches is only available in 3.0+. So the when you install 3.0.1, 3.0.0 should be automatically uninstalled, but yeah, nothing gets automatically uninstalled in 2.1 and 2.2. This isn't something we can reasonably port to 2.1/2.2, but it should work in 3.0+.

There is some discussion about cleanup tools in https://github.com/dotnet/core/issues/3778 to take care of this problem in general. (The issue applies to your other issue too (thanks for the link!) but the cleanup bit is relevant here.)

**Comment by RomBrz** [comment]
Oh, good to know that the behavior have been changed to the 3.0+.
If you could at least port to the 2.1 (since it's a LTS version) it would be great. But if it's not possible, at least the #3778 should get me some help.
I already made one script to install every .NET Core version, maybe uninstalling everything with that cleanup script, and after that running my script to install the latest from each family should be OK.

**Comment by RomBrz** [comment]
@dagood i start the rollup of 2.1.15, 3.0.2 and 3.1.1 on some servers. I tested what you told about 3.x.x removing older ones, and worked fine! 

Except for the fact that the "Windows Server Bundle" wasn't uninstalled. I kept with Server Bundle 3.0.1, Server Bundle 3.0.2 and .NET Core 3.0.2 (both x86 and x64).

Is this expected?

**Comment by dagood** [comment]
It looks like the hosting bundle should also upgrade in place in 3.0+ based on https://github.com/dotnet/aspnetcore/issues/7729. I'm less familiar with that installer, though.

@joeloff can you confirm?

**Comment by RomBrz** [comment]
@dagood sorry to ask, but with the hosting bundle not upgrading, should the issue be closed?
Thanks!

**Comment by joeloff** [comment]
This hosting bundle should be upgrading. We added two special cases since it wasn't supported until after 3.0.0-preview2. However, the upgrade code generation is tied to the major/minor versions since those are SxS always. 

ANCM itself is authored as an upgradable MSI. The hosting bundle however does chain the runtime bundle itself (not the MSIs). those should also be upgradable unless we ever did something odd like pull a 3.0 runtime into a 3.1 hosting bundle. But just wanted to call that out. 

@RomBrz do you have logs from the 3.0.2 install. I'll also set up a machine on my end.

**Comment by dagood** [comment]
@RomBrz this issue is a suggestion to have the installer uninstall the old version, which is already done. What you're hitting now is unexpected behavior. I think it'd be useful to open a new, specific issue in case others hit this (perhaps on https://github.com/dotnet/aspnetcore to keep it closer to the code that produces the installer), however it's also fine by me to keep the conversation going here.

**Comment by RomBrz** [comment]
@joeloff i uninstalled 3.0.2 on one server, installed 3.0.1 again and then installed 3.0.2 again. Have 3 log files (seems like one for Server Hosting Bundle, one for .NET Core x86 and another for .NET Core x64). Does the log generated has some private info? Looking for the log, i didn't saw anything "private" (folder D:\Tools).
@dagood for me it's ok here too, so let's keep going :)

**Comment by joeloff** [comment]
I definitely see different upgrade codes

```
<WixBundleProperties DisplayName="Microsoft .NET Core 3.0.2 - Windows Server Hosting" LogPathVariable="WixBundleLog" Compressed="no" 
  Id="{17254454-af64-4189-87aa-b8a8ec20dc9c}" UpgradeCode="{C8320CBC-29C1-3D96-8B1C-89A4E3821125}" PerMachine="yes" />
```

```
<WixBundleProperties DisplayName="Microsoft .NET Core 3.0.1 - Windows Server Hosting" LogPathVariable="WixBundleLog" Compressed="no" 
  Id="{c80ac067-8d3a-4599-9cdb-61c923369662}" UpgradeCode="{B32A606F-E9C8-3DB8-AD7A-BCE9E6C93630}" PerMachine="yes" />
```
Looking at the history it seems we explicitly called out that 3.0.1 wont upgrade to 3.0.2, BUT, anything in 3.0.2 would upgrade, e.g. 3.0.2-preview1 and 3.0.2-preview 99 are upgradable.

**Comment by RomBrz** [comment]
@joeloff it's strange that this happened with 3.0.1 -> 3.0.2 and 3.1.0 -> 3.1.1. Both leave the older "Windows Server Hosting" installed.

**Comment by RomBrz** [comment]
@joeloff just to know, still happens with 3.0.2 -> 3.0.3 and 3.1.1 -> 3.1.2

**Comment by joeloff** [comment]
Yup, this hasn't been fixed. The upgrade pivots on the build and not the patch in the case of the hosting bundle.

@anurse Depending on when 3.0 hits EOL maybe we do this for 3.1.x?
