### ISSUE TITLE
aks create failed in the .NET Tutorial - Deploy a microservice to Azure tutorial

### ISSUE THREAD

**Issue by ldotreed** [dotnet/core#4055]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'. The available VM sizes are Standard_D1,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_D2,Standard_D3,Standard_D4,Standard_H16,Standard_H16m,Standard_H16mr,Standard_H16r,Standard_H8,Standard_H8m

**Comment by mairaw** [comment]
Duplicate of #3824
