### ISSUE TITLE
unable to perform actions using my iMac, Catalina OS, and Safari browser. Unable to install .NET sdk pkg to iMac. Please advise

### ISSUE THREAD

**Issue by guaglijg** [dotnet/core#4056]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by guaglijg** [comment]
unable to perform actions using my iMac, Catalina OS, and Safari browser. Unable to install .NET sdk pkg to iMac. Please advise.

how to learn the basics of c# on my iMac computer?
- John

**Comment by dagood** [comment]
Are you hitting this known issue with Catalina? https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-installation-on-macos-catalina-1015

Can you provide some details why you're unable to install? Do you have an error message?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide detail.
