### ISSUE TITLE
File not found error from VS when following aspnet core hello world tutorial

### ISSUE THREAD

**Issue by apollosnyder** [dotnet/core#4057]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: Windows 10

![Annotation 2019-12-28 232857](https://user-images.githubusercontent.com/54876111/71552377-01e2e100-29ca-11ea-9f2c-317f1415112e.jpg)

Files not created/Found? Is there a fix??

**Comment by scalablecory** [comment]
What part of the instructions are you seeing this with? It looks like you're opening up a file from command line.

**Comment by scalablecory** [comment]
Closing out, please re-open if you can provide more detail.
