### ISSUE TITLE
error converting YAML to JSON:

### ISSUE THREAD

**Issue by rkrishnav** [dotnet/core#4059]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Getting below error while deploying the service.

error: error parsing deploy-myMicroservice.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key

**Comment by rkrishnav** [comment]
Never mind. It worked. Had an extra space causing the issue

**Comment by guilhermelionzo** [comment]
> Never mind. It worked. Had an extra space causing the issue
Rkrishnav, could you provide the right YAML? I'm facing the same problem.

**Comment by guilhermelionzo** [comment]
> Never mind. It worked. Had an extra space causing the issue

Rkrishnav, could you provide the right YAML? I'm facing the same problem and I didn't figure out what is going on. Thanks :D
