### ISSUE TITLE
Markdown files showing as modified directly after cloning repo on Windows

### ISSUE THREAD

**Issue by jpierson** [dotnet/core#406]
Line endings for Markdown files (119 of them) show up as modified in git directly after cloning.

Repro steps from Powershell:

1. `git clone 
2. `git clone https://github.com/dotnet/core.git x-core`
3. `cd x-core`
4. `git status`

Expected results:
I should see no modified files when looking at the status of the files with git.

Actual results:
Over 119 files (all markdown files) are listed.

![image](https://cloud.githubusercontent.com/assets/1467146/21491453/d605a3a2-cbca-11e6-8fb7-bc41b96270dd.png)

I'm running Windows 10 and my git configuration has `core.autocrlf` set to the the default for Windows.

**Comment by jpierson** [comment]
Adding the following line to `.gitattributes` seems to have worked around this issue for me for the time being. 

```
*.md -text -diff
```

Without looking into it too more it appears that the .md files may have mixed line endings.

Running `git --version` on my machine yields `git version 2.8.1.windows.1` in case that is important.

**Comment by richlander** [comment]
This is our repo, but it has nothing to do with the product. Sorry.
