### ISSUE TITLE
Transpiler?

### ISSUE THREAD

**Issue by wgrudda** [dotnet/core#4061]
Hallo,
is it allowed to use .Net in a transpiler?
We planned an opensource rust transpiler, which is for example to translate .NET into Rust.

We planned to transpile the complete .NET SDK to Rust and use this Rust .NET SDK in next Projects.

Is this allowed or not?
We will start our transpiler project after you allowed it.

If you have any further Questions, please ask.

Kind regards
Wolfgang

**Comment by scalablecory** [comment]
Please see https://github.com/dotnet/core#licenses for links to the various licenses the project is under.

CC @terrajobst

**Comment by wgrudda** [comment]
Thank you
Licenses allow modifications, so I think itˋs allowed.

as soon as we have a good base, we will share it. you can use the knowledge for project Verona.
