### ISSUE TITLE
Migration to .NET Core 3.1 Requires Manual Edit of PublishProfile pubxml File

### ISSUE THREAD

**Issue by robinwilson16** [dotnet/core#4064]
The instructions for Migrating to .NET Core 3.1 from 3.0 (https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31) say you only need to amend the project file but then whilst you can run your project successfully when it comes to trying to publish it you get an error saying project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.0.

To make it publish you must manually edit the `.pubxml` file and find:
```
<TargetFramework>netcoreapp3.0</TargetFramework>
```

Replace this with:
```
<TargetFramework>netcoreapp3.1</TargetFramework>
```

Someone else logged this issue on the docs page (aspnet/AspNetCore.Docs#15986) and their issue was closed. As it has now been marked off topic it no longer even shows up on the docs page which is a shame as is helpful to know what the fix is as it is not included in the documentation even though it is probably not expected functionality and more a bug.

This is the same issue has carried over unfixed from .NET Core 2.2 to 3.0 migration which I originally logged back in October (aspnet/AspNetCore#14842) and my issue is also closed.

**Comment by thamathar** [comment]
The strange thing is when we go into Publish Window (right click on the project -> Publish) and choose Edit it will apear on the Settings -> Target Framework it will show netcoreapp3.1, if we press save it will not save into the file, we really require to manual edit the file

**Comment by scalablecory** [comment]
@mairaw this looks like an improvement we can make to our tutorials.

**Comment by mairaw** [comment]
@Rick-Anderson @scottaddie can you please take a look? Should we move this to the docs repo?

**Comment by Rick-Anderson** [comment]
> Should we move this to the docs repo?

YEs

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#20551
