### ISSUE TITLE
Couldn't find an installed template that matches the input, searching online for one that does...

### ISSUE THREAD

**Issue by JayParmar101** [dotnet/core#4066]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
We'll need a bit more information to help you.
Can you confirm what version of the .NET Core SDK you have installed? You can do that by typing `dotnet --info`.

**Comment by mairaw** [comment]
Closing due to the lack of response.
