### ISSUE TITLE
.net build failed

### ISSUE THREAD

**Issue by Hazeez-ur-Rehman** [dotnet/core#4067]
![Screenshot (8)](https://user-images.githubusercontent.com/59432052/71655115-47fdb480-2cea-11ea-9562-ae944dd07571.png)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @Hazeez-ur-Rehman! Can you share what your code looks like after you've modified it? It seems it had some issues in the modified code since it ran ok the first time.

**Comment by mairaw** [comment]
Closing due to the lack of response.
