### ISSUE TITLE
VS2019 and Microservice tutorial - Docker images 2.2 should be updated to 3.1 

### ISSUE THREAD

**Issue by Alex-B09** [dotnet/core#4071]
About the tutorial : https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file

With the default C# ASP on VS2019 core, the 2.2 images (both for the build and for the run) give version errors.

Using 3.1 (mcr.microsoft.com/dotnet/core/sdk:3.1 and mcr.microsoft.com/dotnet/core/aspnet:3.1) solves the issue

**Comment by scalablecory** [comment]
@shirhatti do you know who can update these?

**Comment by carlossanlop** [comment]
Ping @shirhatti

**Comment by shirhatti** [comment]
The doc has since been updated.
