### ISSUE TITLE
IHostApplicationLifetime bug

### ISSUE THREAD

**Issue by FrenkR** [dotnet/core#4072]
# IHostApplicationLifetime ApplicationStopping is not waiting events

when registering IHostApplicationLifetime.ApplicationStopping event, event is called, but application stops before registered event is finished. According to documentation, application should wait for events (to be fully executed).

# Steps to reproduce

1.) create new "asp.net core web application" using standard VS template.

2.) inject "IHostApplicationLifetime" into "configure" method and register "applicationStopping" event:

`

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime hostApplicationLifetime )
        {
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            hostApplicationLifetime.ApplicationStopping.Register(() =>
            {
                var _i = 0; // place debug breakpoint here!
                _i++;
            });

        }
 `

3.) start application in debug mode using "console" start. After starting, console window appears.
4.) set breakpoint inside "register" method. Then click "close"("x" on right upper corner of console application). You will notice that "applicationstopping" event is called, this is correct. But if you just wait on a breakpoint for 5-10 secons, you will notice that application has stopped without waiting for event to be executed. 
`

**Comment by scalablecory** [comment]
The event is likely only triggered if you perform a graceful shutdown. @Pilchie

**Comment by FrenkR** [comment]
event is triggered, but it does not block application termination.

**Comment by Pilchie** [comment]
This issue was moved to aspnet/Extensions#2827
