### ISSUE TITLE
The path to an application .dll file to execute.

### ISSUE THREAD

**Issue by sasikalath** [dotnet/core#4074]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by sasikalath** [comment]
when i run command prompt with dotnet, it returns the below response

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by swaroop-sridhar** [comment]
@sasikalath  Looks like this is the expected behavior when you just run `dotnet` at the prompt. 
What's the issue here? Thanks.

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide detail.
