### ISSUE TITLE
After changing the code its showing error 

### ISSUE THREAD

**Issue by maakhone** [dotnet/core#4076]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Can you give step by step details on what you're doing that causes the problem?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide detail.

**Comment by scalablecory** [comment]
Duplicate of #4166
