### ISSUE TITLE
Deploy a microservice to Azure cannot reach deployed service (can't even ping the IP)

### ISSUE THREAD

**Issue by ldotreed** [dotnet/core#4077]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Can you give more details? What is the console output, what IP are you trying, etc.

**Comment by ldotreed** [comment]
I had to change the SDK version in the Dockerfile because the microservice
project provided by the previous tutorial as the basis for the deploy
tutorial was created with the 3.1 sdk.  Tried to attach a zip of the
folder, but it's too big.  I can't ping the ip and I don't get a response
when I try to browse http://13.83.67.102/WeatherForcast.   Here's the
console output that I just ran today.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Try the new cross-platform PowerShell https://aka.ms/pscore6

D:\Source\repos\docker-working-ms\myMicroservice> docker run
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
D:\Source\repos\docker-working-ms\myMicroservice> docker ls
docker: 'ls' is not a docker command.
See 'docker --help'
D:\Source\repos\docker-working-ms\myMicroservice> docker containers
docker: 'containers' is not a docker command.
See 'docker --help'
D:\Source\repos\docker-working-ms\myMicroservice> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED
    STATUS              PORTS               NAMES
D:\Source\repos\docker-working-ms\myMicroservice> docker ps --all
CONTAINER ID        IMAGE               COMMAND                  CREATED
          STATUS                   PORTS               NAMES
26c7e82289cb        dee950af1daa        "/bin/sh -c 'dotnet …"   4 weeks
ago         Exited (1) 4 weeks ago                       focused_robinson
REPOSITORY                             TAG                 IMAGE ID
   CREATED             SIZE
<none>                                 <none>              502d2efc64af
   2 weeks ago         690MB
<none>                                 <none>              dee950af1daa
   4 weeks ago         1.74GB
ldotreed/mymicroservice                latest              5f303057827c
   4 weeks ago         208MB
mymicroservice                         latest              5f303057827c
   4 weeks ago         208MB
ldotreed/bulletinboard                 latest              5f303057827c
   4 weeks ago         208MB
<none>                                 <none>              3570e74955f4
   4 weeks ago         690MB
mcr.microsoft.com/dotnet/core/sdk      3.1                 9817c25953a8
   7 weeks ago         689MB
mcr.microsoft.com/dotnet/core/aspnet   3.1                 08096137b740
   7 weeks ago         207MB
mcr.microsoft.com/dotnet/core/sdk      2.2                 84120c6c3491
   2 months ago        1.74GB

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
D:\Source\repos\docker-working-ms\myMicroservice> dotnet run
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Source\repos\docker-working-ms\myMicroservice
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
D:\Source\repos\docker-working-ms\myMicroservice> docker build -t
mymicroservice .
Sending build context to Docker daemon  22.02kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
 ---> 9817c25953a8
Step 2/10 : WORKDIR /src
 ---> Using cache
 ---> 003a47ec0a85
Step 3/10 : COPY myMicroservice.csproj .
 ---> Using cache
 ---> 0fe2dca3dde5
Step 4/10 : RUN dotnet restore
 ---> Using cache
 ---> 5b2beeb5f7a9
Step 5/10 : COPY . .
 ---> ac21857e46da
Step 6/10 : RUN dotnet publish -c release -o /app
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 26.23 ms for /src/myMicroservice.csproj.
  myMicroservice -> /src/bin/release/netcoreapp3.1/myMicroservice.dll
  myMicroservice -> /app/
Removing intermediate container d1c7b4bc0cf5
 ---> 5b3a210ac750
Step 7/10 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
 ---> 08096137b740
 ---> Using cache
 ---> dbe542188a55
 ---> 1b9db6fe7d81
Step 10/10 : ENTRYPOINT ["dotnet", "myMicroservice.dll"]
 ---> Using cache
 ---> 5f303057827c
Successfully built 5f303057827c
Successfully tagged mymicroservice:latest
SECURITY WARNING: You are building a Docker image from Windows against a
non-Windows Docker host. All files and directories added to build context
will have '-rwxr-xr-x' permissions. It is recommended to double check and
reset permissions for sensitive files and directories.
D:\Source\repos\docker-working-ms\myMicroservice> docker run -it --rm -p
3000:80 --name mymicroservicecontainer mymicroservice
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
^Cinfo: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
D:\Source\repos\docker-working-ms\myMicroservice> docker login
Authenticating with existing credentials...
Login Succeeded
D:\Source\repos\docker-working-ms\myMicroservice> docker tag mymicroservice
ldotreed/mymicroservice
D:\Source\repos\docker-working-ms\myMicroservice> docker push
ldotreed/mymicroservice
The push refers to repository [docker.io/ldotreed/mymicroservice]
1f88720bff9c: Layer already exists
62b3f719c3a6: Layer already exists
239bf536471e: Layer already exists
cad0d4e88a35: Layer already exists
831c5620387f: Layer already exists
latest: digest:
sha256:14f9d8bff2b6f821be8fdcc8798cf1e3c566527c4c757a97f60f64e7acd242ae
size: 1790
D:\Source\repos\docker-working-ms\myMicroservice> az login
You have logged in. Now let us find all the subscriptions to which you have
access...
[
  {
    "cloudName": "AzureCloud",
    "id": "da1dbe54-624e-423d-893d-2633ca8e76bd",
    "isDefault": true,
    "name": "Pay-As-You-Go",
    "tenantId": "354710ab-09bb-4323-ba88-da2ac7db5f2d",
    "user": {
      "name": "larry_reed@verizon.net",
      "type": "user"
    }
  }
]
D:\Source\repos\docker-working-ms\myMicroservice> az aks install-cli
Downloading client to "C:\Users\Larry\.azure-kubectl\kubectl.exe" from "
https://storage.googleapis.com/kubernetes-release/release/v1.17.2/bin/windows/amd64/kubectl.exe
"
D:\Source\repos\docker-working-ms\myMicroservice> az group create --name
myMicroserviceResources --location westus
{
  "id":
"/subscriptions/da1dbe54-624e-423d-893d-2633ca8e76bd/resourceGroups/myMicroserviceResources",
  "location": "westus",
  "managedBy": null,
  "name": "myMicroserviceResources",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}
D:\Source\repos\docker-working-ms\myMicroservice> az aks create
--resource-group myMicroserviceResources --name myMicroserviceCluster
--node-count
1 --enable-addons http_application_routing --generate-ssh-keys
{
  "aadProfile": null,
  "addonProfiles": {
    "httpApplicationRouting": {
      "config": {
        "HTTPApplicationRoutingZoneName": "
41cd25f296f14e39b491.westus.aksapp.io"
      },
      "enabled": true
    }
  },
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "enableNodePublicIp": null,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "name": "nodepool1",
      "nodeTaints": null,
      "orchestratorVersion": "1.14.8",
      "osDiskSizeGb": 100,
      "osType": "Linux",
      "provisioningState": "Succeeded",
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "type": "VirtualMachineScaleSets",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": null
    }
  ],
  "apiServerAccessProfile": null,
  "dnsPrefix": "myMicroser-myMicroserviceRe-da1dbe",
  "enablePodSecurityPolicy": null,
  "enableRbac": true,
  "fqdn": "mymicroser-mymicroservicere-da1dbe-be52398a.hcp.westus.azmk8s.io
",
  "id":
"/subscriptions/da1dbe54-624e-423d-893d-2633ca8e76bd/resourcegroups/myMicroserviceResources/providers/Microsoft.ContainerService/managedClusters/myMicroserviceCluster",
  "identity": null,
  "kubernetesVersion": "1.14.8",
  "linuxProfile": {
    "adminUsername": "azureuser",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABgQCnRG3wQYkfwq33r62xz/40wnuX2NnFnFabaPm2VjnUCZwAHHXfHyfzCanfBCmy/3TvLFUthGFQ43Wxjp/ElNIXpXpLLlY2ttzHoIJAA0fzfu1wBeji2VxdJ3ZPqkyzEr+AL7yF5ANSTv85SeEWNJM6MRpCmw1VYnesEc42RkxgR4nRqglxJAwtxSO1jzoh7CV1RqvLfpW+pSXvjeCCPqToqiGeTE/KSnSaSYlO8jV6odBC5inLjE43KwDQhrjxNTP4IpVWZaaUSGGsZQHt7CflVOzVubripS/firl5jF0wMbrHU0QXm3567h10a/LHCPYCjyThsUf6niwQcWJVnYpgjEIWU63FAXop14OL7IisscAygzXcYQm4HjzO0Bkaz0108nrZGKzRDJIv6tsWCsZXmVM7dxqj6S0Z2Fe2ZAZmILd6j/SqxvjeHZTNf5Qy/uofCl25c4FntC30R9PujRZrP3Dih1CXk+neUi372XBRyJeqp8FXClqG1ge3vEBd6uk=
Larry@LANDM-PC6\n"
        }
      ]
    }
  },
  "location": "westus",
  "maxAgentPools": 8,
  "name": "myMicroserviceCluster",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "loadBalancerProfile": {
      "effectiveOutboundIps": [
        {
          "id":
"/subscriptions/da1dbe54-624e-423d-893d-2633ca8e76bd/resourceGroups/MC_myMicroserviceResources_myMicroserviceCluster_westus/providers/Microsoft.Network/publicIPAddresses/a988a25c-ff20-40fc-a6c5-7c0f12bb359d",
          "resourceGroup":
"MC_myMicroserviceResources_myMicroserviceCluster_westus"
        }
      ],
      "managedOutboundIps": {
      },
      "outboundIpPrefixes": null,
      "outboundIps": null
    },
    "loadBalancerSku": "Standard",
    "networkPolicy": null,
    "outboundType": "loadBalancer",
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup":
"MC_myMicroserviceResources_myMicroserviceCluster_westus",
  "privateFqdn": null,
  "resourceGroup": "myMicroserviceResources",
  "servicePrincipalProfile": {
    "clientId": "5b380d16-0944-4205-9d28-9848f7c3816f",
    "secret": null
  },
  "tags": null,
  "type": "Microsoft.ContainerService/ManagedClusters",
  "windowsProfile": null
}
D:\Source\repos\docker-working-ms\myMicroservice> az aks get-credentials
--resource-group myMicroserviceResources --name myMicroserviceCluster
A different object named myMicroserviceCluster already exists in your
kubeconfig file.
Overwrite? (y/n): y
A different object named
clusterUser_myMicroserviceResources_myMicroserviceCluster already exists in
your kubeconfig file.
Overwrite? (y/n): y
Merged "myMicroserviceCluster" as current context in
C:\Users\Larry\.kube\config
D:\Source\repos\docker-working-ms\myMicroservice> cd myMocroservice
cd : Cannot find path
'D:\Source\repos\docker-working-ms\myMicroservice\myMocroservice' because
it does not exist.
At line:1 char:1
+ cd myMocroservice
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound:
(D:\Source\repos...\myMocroservice:String) [Set-Location],
ItemNotFoundException
    + FullyQualifiedErrorId :
PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand



    Directory: D:\Source\repos\docker-working-ms\myMicroservice


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         1/5/2020   8:46 AM                .vscode
d-----         1/5/2020   8:45 AM                bin
d-----         1/5/2020   8:44 AM                Controllers
d-----        1/26/2020   7:29 AM                obj
d-----         1/5/2020   8:44 AM                Properties
-a----         1/5/2020   8:47 AM             28 .dockerignore
-a----         1/5/2020   8:44 AM            162
appsettings.Development.json
-a----         1/5/2020   8:44 AM            192 appsettings.json
-a----         1/5/2020  11:14 AM           1136 deploy-myMicroservice.yaml
-a----         1/5/2020   8:46 AM            298 Dockerfile
-a----         1/5/2020   8:44 AM            150 myMicroservice.csproj
-a----         1/5/2020   8:44 AM            722 Program.cs
-a----         1/5/2020   8:44 AM           1383 Startup.cs
-a----         1/5/2020   8:44 AM            310 WeatherForecast.cs


D:\Source\repos\docker-working-ms\myMicroservice> type
.\deploy-myMicroservice.yaml
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
    metadata:
      labels:
    spec:
      containers:
        image: ldotreed/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
          value: http://*:80
---
apiVersion: v1
kind: Service
  name: mymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice
deployment.apps/mymicroservice created
service/mymicroservice created
D:\Source\repos\docker-working-ms\myMicroservice> kubectl get service
mymicroservice --watch
NAME             TYPE           CLUSTER-IP   EXTERNAL-IP    PORT(S)
 AGE
mymicroservice   LoadBalancer   10.0.65.67   13.83.67.102   80:30406/TCP
54s
D:\Source\repos\docker-working-ms\myMicroservice> az container logs
--myMicroserviceResources -- mymicroservice
az: error: unrecognized arguments: --myMicroserviceResources --
mymicroservice
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {container} ...
D:\Source\repos\docker-working-ms\myMicroservice> az container logs
--myMicroserviceResources --name mymicroservice
az: error: unrecognized arguments: --myMicroserviceResources
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {container} ...
D:\Source\repos\docker-working-ms\myMicroservice> az container logs
--resource-group --myMicroserviceResources --name mymicroservice
az container logs: error: argument --resource-group/-g: expected one
argument
usage: az container logs [-h] [--verbose] [--debug]
                         [--output {json,jsonc,table,tsv,yaml,none}]
                         [--query JMESPATH] [--subscription _SUBSCRIPTION]
                         [--resource-group RESOURCE_GROUP_NAME] [--name
NAME]
                         [--container-name CONTAINER_NAME] [--follow]
                         [--ids ID [ID ...]]
D:\Source\repos\docker-working-ms\myMicroservice> az container logs
--resource-group myMicroserviceResources --name mymicroservice
The Resource 'Microsoft.ContainerInstance/containerGroups/mymicroservice'
under resource group 'myMicroserviceResources' was not found.
D:\Source\repos\docker-working-ms\myMicroservice>

**Comment by shirhatti** [comment]
```diff
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
    metadata:
      labels:
    spec:
      containers:
        image: ldotreed/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
-        - name: ASPNETCORE_URLS
          value: http://*:80
```

@ldotreed It's really hard to read your logs because of the formatting, but it looks your `deploy-myMicroservice.yaml` is malformed and missing the `ASPNETCORE_URLS` environment variable

**Comment by sughosneo** [comment]
Hi @ldotreed, just checking if you had a chance to perform the further test?
