### ISSUE TITLE
TTY

### ISSUE THREAD

**Issue by BoillinG** [dotnet/core#4078]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

```
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```
--

**Comment by scalablecory** [comment]
@shirhatti any ideas?

**Comment by shirhatti** [comment]
As indicated in the error message, you're using a console that isn't a TTY (e.g., Git bash for Windows).

Re-run from a windows command prompt or follow the suggestion in the error and prefix the command with winpty

```
winpty docker run -it --rm -p 3000:80 --name mymicroservicecontainer mymicroservice
```

**Comment by mairaw** [comment]
Did this solve your issue @BoillinG?

**Comment by carlossanlop** [comment]
No answer since Jan 7. Closing.
