### ISSUE TITLE
openSUSE 15 Linux package repository is broken: "Signature verification failed for file 'repomd.xml'"

### ISSUE THREAD

**Issue by dagood** [dotnet/core#4085]
When I run `sudo zypper install dotnet-sdk-3.1`, I get this prompt:

```
Signature verification failed for file 'repomd.xml' from repository 'packages-microsoft-com-prod'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: This file was modified after it has been signed. This may have been a malicious change,
    so it might not be trustworthy anymore! You should not continue unless you know it's safe.

Signature verification failed for file 'repomd.xml' from repository 'packages-microsoft-com-prod'. Continue? [yes/no] (no):
```

When I select `no`, the install fails. Typing `yes` allows the install to continue, but accepts the risks mentioned in the message.

I've filed an internal ticket to track this and I'll update here once I get a response from the repo owners. It's possible this is just a normal post-publish delay, and it will resolve itself, but I'm not familiar with how long the delay normally takes.

**Comment by dagood** [comment]
The repo admins have tracked this down to delays in the signing infra they depend on, and have filed their own ticket to track that. The signing infra owners haven't been able to find many details yet and there is no ETA.

**Comment by dagood** [comment]
The repo admins noticed the signing delay decreased (although we don't have information why this happened), so they refreshed the repos that were affected by this problem. Installing via RPM package on openSUSE 15 now works for me.

**Comment by josef-marec** [comment]
well, everything inside /opensuse/15/prod/repodata/ has now newer modification date "10-Jan-2020 00:31"

when running automatic update, the tool complaints "Signature verification for Repository packages-microsoft-com-prod failed"

**Comment by dagood** [comment]
Hmm, yeah, new outage, slightly different error. Opening a new ticket and issue for it, thanks for the ping.

**Comment by dagood** [comment]
FYI @josef-marec, I filed https://github.com/dotnet/core/issues/4108 for this, and they resolved it pretty quickly. Works for me now. Thanks again for the report.

**Comment by josef-marec** [comment]
great, everything works for me too, thanks
