### ISSUE TITLE
Pages/Index.cshtml

### ISSUE THREAD

**Issue by hao249113531** [dotnet/core#4088]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Do you have any details to provide? What step is failing for you?

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide more detail.

**Comment by scalablecory** [comment]
Duplicate of #4166
