### ISSUE TITLE
Office Automation in dotnet core - are there any plans for this?  

### ISSUE THREAD

**Issue by dnbr2002** [dotnet/core#409]
Really the title says it all.  We want to build a conversion engine in .NET core that leverages the Office Automation components.  Nothing converts Office documents as well as Office Automation but we need to use dotnet core as our framework.  It is an edict where I work that the backend framework must be Open Source.  Is there anything in the pipeline at Microsoft to expose this functionality to dotnet core in the future??  It would surely be a big hit if you did.

**Comment by Petermarcu** [comment]
What libraries do you use to do this today on .NET Framework? It would be interesting to see how far off the existing components are from "just working".

**Comment by richlander** [comment]
> I may be in fantasy land but if Microsoft could offer some cross platform API (not saying it has to be open source) that we could plug into dotnet core (or maybe a jar for Java) then it allows us to modernize our conversion engine for office documents in a way that makes the most sense.

It sounds like you are looking for a cross-platform solution for Office document conversion all-up. I'm not on the office team, so I don't know what the options are there. I would suggest looking at the OpenXML SDK: https://msdn.microsoft.com/en-us/library/office/bb448854.aspx. It does seem like .NET Core is not the primary technical issue in your project. Closing under that assumption.
