### ISSUE TITLE
Hello World under standard user fails with Ubuntu/GNOME

### ISSUE THREAD

**Issue by elliotrodriguez** [dotnet/core#41]
I don't know if the Getting Started steps are implied to be run as root (they don't appear to be because the installation steps specify sudo), but I get a variety of permissions errors when attempting to run `dotnet run` as a standard non-root user under Ubuntu with GNOME. It looks like Hello World is trying to access hidden directories.

It started with my .gvfs from my HOME directory and, after granting permissions to it, continued with `.cache/dconf`. I stopped there.

`sudo dotnet run` works fine. However, I'm curious if anyone knows why the steps don't work OOTB. Thanks.

**Comment by jrwren** [comment]
Steps to reproduce:

Start a fresh ubuntu 14.04 instance.

    sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
    echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > sudo tee /etc/apt/sources.list.d/dotnetdev.list
    sudo apt-get update
    sudo apt-get install --no-install-recommends dotnet
    mkdir a
    cd a
    dotnet new
    dotnet restore

hangs after a single log line:

    log  : Restoring packages for /home/ubuntu/a/project.json...

I do not even get permission denied errors.

Running `sudo dotnet restore` shows info messages for requested urls almost immediately after invoking. As non-root (the ubuntu user) `dotnet restore` hangs indefinitely.

The package version is 1.0.0.001793-1

**Comment by DonSchenck** [comment]
I have this same issue; In my case, IPv6 is the preferred address lookup, and it's hanging. I moved IPv4 ahead of IPv6 in the precedence by adding the line

`precedence ::ffff:0:0/96 100`

in the file /etc/gai.conf

**Comment by blackdwarf** [comment]
Hm, this is strange. I was not able to repro this on Linux Mint or on Ubuntu 14.04. I will close down this issue, but if this behavior still repros, can you please open up a new issue in the dotnet/cli repo? Thanks!
