### ISSUE TITLE
Issue in in cmd after installation of .NET sdk 32 bit

### ISSUE THREAD

**Issue by NILOY5493** [dotnet/core#4101]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

received a 'dotnet' is not recognized as an internal or external command error in cmd after installation of .NET sdk 32 bit

**Comment by scalablecory** [comment]
Please restart your console window; the installer updates PATH variables that aren't refreshed automatically.

**Comment by mairaw** [comment]
Did you try opening a new console window @NILOY5493? Also, did you confirm that you're running a 32-bit Windows?

**Comment by mairaw** [comment]
Closing due to the lack of response.
