### ISSUE TITLE
i can't open it

### ISSUE THREAD

**Issue by hvu81** [dotnet/core#4102]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Please restart your console window; the installer updates PATH variables that aren't refreshed automatically.

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide more detail.

**Comment by scalablecory** [comment]
Duplicate of #4166
