### ISSUE TITLE
NetCore3.1 does not work on High Sierra 10.13.6

### ISSUE THREAD

**Issue by xukev** [dotnet/core#4103]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

-----
I installed .NetCore3.1 on my Mac Pro(High Sierra 10.13.6).  Then run tutorial, then i got below error. 

kevins-mac-pro:~ xukev$ dotnet
-bash: dotnet: command not found

**Comment by Matsa59** [comment]
I think this can help you https://github.com/dotnet/core/issues/4091

**Comment by xukev** [comment]
> I think this can help you #4091

Thanks!

**Comment by scalablecory** [comment]
Looks like you found a solution, closing.
