### ISSUE TITLE
Creating new console application with dotnet command

### ISSUE THREAD

**Issue by SalaheddineEtangi** [dotnet/core#4104]
The message error after running the command:
                    >dotnet new console -o myApp
is _Template "Console Application" could not be created.
    Access to the path 'C:\Windows\System32\myApp' is denied._

**Comment by KameronKales** [comment]
Can you try it in another folder? My first guess would be there are permissions blocking you from creating a new project in that location. Try on your Users directory

**Comment by carlossanlop** [comment]
Answered. An app cannot be created in that folder.
