### ISSUE TITLE
Software Development Kit (SDK) error on Visual Code

### ISSUE THREAD

**Issue by Bessanje** [dotnet/core#4106]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Bessanje** [comment]
Hi guys,

I downloaded the SDK and installed it. Next, I run it in C # visual code on my Windows 10 operating system.
Then he showed me the following message: "'dotnet' is not recognized as an internal or external command".

How can I solve this problem?

**Comment by scalablecory** [comment]
Have you restarted the console after installing? It updates PATH variables that aren't refreshed automatically by apps using them.

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide more detail.
