### ISSUE TITLE
Demo service build to .net core 3.1, docker setup points to sdk:2.1 and aspnet:2.1

### ISSUE THREAD

**Issue by ferdeen** [dotnet/core#4110]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

I had to go out to docker to get the images for 3.1 to complete the demo on the above page.

https://hub.docker.com/_/microsoft-dotnet-core-aspnet/

**Comment by scalablecory** [comment]
Duplicate of https://github.com/dotnet/core/issues/4071
