### ISSUE TITLE
az group create... --location westus failed

### ISSUE THREAD

**Issue by ferdeen** [dotnet/core#4111]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

azure cli command:

`az group create --name myMicroserviceResources --location westus` 

failed with:

> request failed: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/4142177e-d22e-44a9-a424-fc9dac2789a6/resourcegroups/myMicroserviceResources?api-version=2019-07-01 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04FDD430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

worked when I did:

 `az group create --name myMicroserviceResources --location eastus`

After following [this](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough?toc=%2Fcli%2Fazure%2Ftoc.json#create-a-resource-group).

**Comment by GrabYourPitchforks** [comment]
The .NET team does not own Azure CLI - have you tried contacting Azure support regarding this?

**Comment by ferdeen** [comment]
Hi, not I just clicked on the 'I ran into an issue' button during the tutorial.  Is there a contact url or something?

**Comment by GrabYourPitchforks** [comment]
Contacts are listed at https://azure.microsoft.com/en-us/support/options/. If you're seeing problems region-wide in westus, create a support ticket (blue box near bottom-left of that page). There's also the less formal route of using social media to contact their support team (black box near bottom-right of that page).

For Azure CLI bugs and issues, check out the issue tracker at https://github.com/Azure/cli.

**Comment by scalablecory** [comment]
I'm not familiar with the az tools to know this for certain but the error may be an issue with your DNS server, not Azure ("getaddrinfo failed").

**Comment by mairaw** [comment]
Given that it worked for eastus, I think we should close this issue.
