### ISSUE TITLE
Installation problem for .Net SDK on MacOS

### ISSUE THREAD

**Issue by saimanojk1** [dotnet/core#4114]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

The error message I got is: “dotnet-sdk-3.1.100-osx-x64.pkg” can’t be opened because Apple cannot check it for malicious software.

Someone send a fix for the problem.

**Comment by scalablecory** [comment]
Duplicate of https://github.com/dotnet/core/issues/3943
