### ISSUE TITLE
This is still an issue

### ISSUE THREAD

**Issue by drk-mtr** [dotnet/core#4116]
https://github.com/dotnet/core/issues/3221

**Comment by scalablecory** [comment]
Can you please provide details?

**Comment by dagood** [comment]
It would be good to see fresh logs and a more detailed issue title including OS next time. I assume you're getting this:

```
  File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.91.48.226 443]
```

I'm unable to reproduce the problem on Ubuntu 18.04 or 19.04 currently.

We're in the middle of a release, and unfortunately this is expected to temporarily show up after we publish new packages.

**Comment by drk-mtr** [comment]
> I assume you're getting this:
> 
> ```
>   File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.91.48.226 443]
> ```

Yes that's correct.

> We're in the middle of a release, and unfortunately this is expected to temporarily show up after we publish new packages.

Thanks very much for the explanation, this makes sense if it has to replicate across servers etc. I wonder whether it's worth adding a footnote to the Linux installation instructions page to highlight that this might happen at times and is expected?

I had waited an hour or so and retried (after doing an `apt-get update` and refreshing `microsoft*` files within the `sources.list` folder) before logging the issue. I can't confirm this is resolved as not in front of work PC any more, however will close if it's expected that this breaks sometimes.

**Comment by dagood** [comment]
> I wonder whether it's worth adding a footnote to the Linux installation instructions page to highlight that this might happen at times and is expected?

I like this, filed https://github.com/dotnet/docs/issues/16670. Thanks. 😄
