### ISSUE TITLE
Will you move the video learning materials to Chinese video website like Youku??

### ISSUE THREAD

**Issue by WinChance** [dotnet/core#4125]
In China, We can't visit Youtube website . It's hard for us to learn all your video course in Youtube of Microsoft. Such as :
1.Videos in https://dotnet.microsoft.com/learn/aspnet .
2.Like https://www.youtube.com/watch?v=lE8NdaX97m0&list=PLdo4fOcmZ0oW8nviYduHq7bmKode-p8Wy 
Provide just Youtube to watch all the videos is no friendly. I hope this will improve.
Thx.

**Comment by scalablecory** [comment]
@terrajobst @richlander

**Comment by timheuer** [comment]
Hi there -- these are also available on the Channel 9 site: https://channel9.msdn.com/Series/ASPNET-Core-101 which you should be able to access in China.

**Comment by timheuer** [comment]
Issue moved to [dotnet/website #1702](https://github.com/dotnet/website/issues/1702) via [**ZenHub**](https://www.zenhub.com/)

**Comment by timheuer** [comment]
Issue moved to website repo, can be closed here.

**Comment by timheuer** [comment]
@WinChance - we've logged the issue with the website team to add the Channel 9 URLs which you can download/watch.  I apologize as that repo is not a public one and in moving this off the product repo for .NET Core here.  Apologies for any confusion this may cause.

**Comment by WinChance** [comment]
Thank you very much!!
