### ISSUE TITLE
When trying to install on Catalina an error is thrown, saying that Apple is not able to determine wether it has malicious software

### ISSUE THREAD

**Issue by adrx24** [dotnet/core#4128]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/core/issues/3943
