### ISSUE TITLE
.NET Core class library with netcoreapp1.1 and net461 cannot be found in a 4.6.1 project in the same solution

### ISSUE THREAD

**Issue by denishuvelle** [dotnet/core#413]
Hello,

I have recently migrated an existing solution from .NET Core but not all the projects in the solution, I want to have our API project in .NET Core with netcoreapp1.1 but our small tools (Console apps and MVC 5 sites) to stay in .NET 4.6.1...

Here is my configuration:

- Visual Studio 2015 with update 3
- .NET Core 1.1 SDK

So, our main "common" project is a class library with models, enums, translations, etc. and this project is now a .NET Core class library with this project.json:

`{
  "version": "1.0.0-*",

  "buildOptions": {
    "preserveCompilationContext": true
  },

  "dependencies": {
    "Dapper": "1.50.2",
    "MailKit": "1.10.1",
    "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
    "Polly": "4.3.0",
    "StackExchange.Redis": "1.1.608",
    "WindowsAzure.Storage": "7.1.3-preview"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ],
      "dependencies": {
        "System.ComponentModel.Annotations": "4.3.0",
        "System.Reflection.TypeExtensions": "4.3.0",
        "System.Threading.Tasks.Parallel": "4.0.1",
        "System.Security.Cryptography.Cng": "4.3.0",
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
        "NETStandard.Library": "1.6.1"
      }
    },
    "net461": {
      "dependencies": {
        "Microsoft.AspNet.Mvc.DataAnnotations": "6.0.0-rc1-final",
        "Microsoft.ApplicationInsights": "2.1.0"
      }
    }
  }
}
`

The project compiles without error for the both frameworks and it is used by a ASP.NET Core project in production and all is working fine.

But I also want to use this project in my other "old" projects (console apps and MVC 5 projects so) and that does not compile: I can add a reference from an ASP.NET 5 project on my "Common.Core" project but the "content" of the DLL cannot be found in the code:

![image](https://cloud.githubusercontent.com/assets/1088713/21581923/a1ea3cd4-d045-11e6-992f-fcc00095f771.png)
![image](https://cloud.githubusercontent.com/assets/1088713/21581924/a725288a-d045-11e6-85f8-b9aa2bca07a9.png)

I have tried to take Common.Core.dll from \Common.Core\bin\Debug\net461 in a Console App with Framework 4.6.1 in a new solution and in this case, I can access to the code from Common.Core... (but it's not a project reference in this case)

Did I miss something?

**Comment by Petermarcu** [comment]
Project to Project references from different project types was one of the major challenges with the project.json tools. Many things didn't work and many things are being fixed in the MSBuild based tooling that shipped a Preview in Nov. 

Sharing with .NET 4.6.1 as a Project to Project reference is likely best done through a library targeting .NET Standard as opposed to .NET Core. I'm not sure if all of those dependencies are targeting .NET Standard yet but it's probably the direction to aspire to. The MSBuild based tooling will allow you to reference a .NET Standard Library project from a .NET 4.6.1 project.

**Comment by denishuvelle** [comment]
Hello,

Thank you for your quick response!

I have installed Visual Studio 2017 RC and I have tried to convert project.json to csproj: the project references are now working with the new changes in the preview :)

But for my case: a part of my dependencies are not ready if I want to use NetStandard so I will wait a little bit and I will directly reference the DLLs that I need in VS 2015.

**Comment by Petermarcu** [comment]
Great, which dependencies weren't ready for .net standard. You may be able to use imports to force them to be referencable.

**Comment by paqogomez** [comment]
I've gone this same route.  I'm now on 2017 RC and using the csproj format in my solution.  

My older .NET 451 projects are able to be referenced, but when I build and run I get a runtime error saying:

`FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.`

Any chance this configuration is supported?

**Comment by dsplaisted** [comment]
@paqogomez It's not clear to me what project you're trying to reference from what. Can you open a new issue with a description of your project structure, and ideally a repro?

**Comment by igor-1024** [comment]
Apologies if it’s not the right place or not related, but I get @paqogomez 's “System.Core” issue and can’t find the solution for it.

To replicate using Visual Studio 2017

1. Create ASP .NET Core Web Application (.NETCoreApp 1.1), say ProjectA
2. Create Class Library (.NET Framework 4.6.1), say ProjectB
3. Add a class with method, which uses anything from System.Linq namespace to ProjectB (for example, => new List<string>().Count();)
4. Add “Microsoft.NETCore.Portable.Compatibility” NuGet package to ProjectA (say version 1.0.1)
5. Reference (project reference) Class Library (ProjectB) from .NET Core project (ProjectA) 
6. Instantiate dummy class anywhere in ProjectA and call that method, which uses anything from System.Linq namespace
