### ISSUE TITLE
Path Not Found error  malith@malith-Aspire-E5-575G:~$ dotnet

### ISSUE THREAD

**Issue by bmalith** [dotnet/core#4150]
When I ran this code it gt this error : 
malith@malith-Aspire-E5-575G:~$ dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by scalablecory** [comment]
That's not an error; did you mean to type "dotnet run" to run code directory, or "dotnet <foo.dll>" to run a compiled app?

**Comment by scalablecory** [comment]
Closing due to lack of response; please reopen if you can provide more detail.
