### ISSUE TITLE
Dockerfile FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build - Wrong version

### ISSUE THREAD

**Issue by tdmiller1** [dotnet/core#4152]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
Operating System: windows

Is this supposed to be version 3.1 instead? I ran into issues when running the doctor build command. After altering this file to 3.1 I no longer had these issues. It specifically says in the myMicroservice.csproj file `<TargetFramework>netcoreapp3.1</TargetFramework>`

Not sure if this needs corrected or just something with my personal environment. Thanks!

**Comment by guilhermelionzo** [comment]
Tucker Miller, I had the same issue. The tutorial was done a while ago and possibly the most recent version was 2.2. I think our dev environment is ok, but let us wait for another answer to confirm this.

**Comment by carlossanlop** [comment]
The tutorial seems to be correct now.
