### ISSUE TITLE
Program.cs

### ISSUE THREAD

**Issue by Bhargavskr97** [dotnet/core#4156]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows
I do not know how to open program.cs file in dot net . which command to use if i want to open it in notepad?

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by joacar** [comment]
You can use `>notepad program.cs`
