### ISSUE TITLE
Dotnet does not properly terminate on Linux build agents when launched with pscore 

### ISSUE THREAD

**Issue by v-kyljon** [dotnet/core#4157]
When dotnet is launched in a powershell terminal on Linux build/release agents there is a disconnect occurring where dotnet is not terminating its own processes on completion and causing the agent job to run on the powershell step until it times out. 

We have determined that the powershell terminal exits upon execution of the last line of code in the script and orphans the dotnet processes which are collected by Init.

The following cmdlets will not stop the process and exit the session on Linux agents:
return
break
exit
$host.SetShouldExit()
$host.Exit()

The [-ErrorAction stop] argument will also fail.

**Comment by scalablecory** [comment]
Might need more info here to route. @safern is this one of yours?

**Comment by safern** [comment]
> @safern is this one of yours?

I don't think so. This seems like another issue in the host or something. @vitek-karas might know more or know who to redirect to.

**Comment by vitek-karas** [comment]
If these are msbuild or roslyn server nodes then I think this is sort of by design. That said I don't know if msbuild/roslyn does that in the specified environment and/or if it's a desirable behavior there.

@rainersigwald  for msbuild
@jaredpar  for Roslyn

@v-kyljon what is the dotnet command being executed in this case?

**Comment by v-kyljon** [comment]
@vitek-karas For each instance I have seen in the CSS queue they are just running dotnet build.

**Comment by jaredpar** [comment]
For roslyn there are indeed resident processes remaining after the build completes. This is by design though. We keep the server around to speed up future compilation.

**Comment by v-kyljon** [comment]
@jaredpar Okay so for the instance of a build agent, assuming that it is dynamically allocated and nothing is kept, how would you recommend stopping that server or preventing it from persisting? In this scenario it is preventing the signal that the step has been completed from being received by the agent causing even successful builds to timeout when using a pscore script. All other orphaned processes are automatically cleaned up at the end of the job.

**Comment by jaredpar** [comment]
The `dotnet build-server` command can be used to shutdown the compiler process, as well as the other server processes that persist after the initial build commands complete.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build-server

**Comment by scalablecory** [comment]
@v-kyljon did @jaredpar's answer help you with this? Can we close? Thanks.
