### ISSUE TITLE
It either says that myWebApp is not a viable command or that WebApp is also not a viable command

### ISSUE THREAD

**Issue by Killmeplsblyat** [dotnet/core#4158]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
How are you trying to run your app? Provide detail please.

**Comment by scalablecory** [comment]
Closing due to lack of response; please reopen if you can provide more detail.
