### ISSUE TITLE
Debian 9 Linux package repository unavailable, "Mirror sync in progress?"

### ISSUE THREAD

**Issue by dagood** [dotnet/core#4165]
> It appears to be broken again
> 
> ```
> Reading package lists...
> E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  File has unexpected size (72896 != 72828). Mirror sync in progress? [IP: 40.76.35.62 443]
>    Hashes of expected file:
>     - Filesize:72828 [weak]
>     - SHA512:3e2135a607d82f3d0fb22a952998f1306ce456553daedb681bee125507c96d0b6e6429b110c92ae9cef8ae09974c74fbabb4e28aeab32ebed9962d2c61238686
>     - SHA256:4217b6ad3a63657ec03df9a3f95c0c5a55401f760790b48269e80dcf6ac19171
>     - SHA1:5b709f4947671085a4172e9d90248fef90be7355 [weak]
>     - MD5Sum:3564888127c08fa04b2b27e345507089 [weak]
>    Release file created at: Tue, 21 Jan 2020 18:06:13 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```

_Originally posted by @esetnik in https://github.com/dotnet/core/issues/4122#issuecomment-576813296_

**Comment by dagood** [comment]
This doesn't repro for me currently in a fresh Debian 9 Docker container. Looking at timestamps, this may have been the sync delay after these `moby-*` packages were pushed: https://packages.microsoft.com/debian/9/prod/pool/main/m/. Sync delays are "normal" service outages.

**Comment by esetnik** [comment]
Is there a place where we can check for these normal service outages? These "sync delays" are breaking CI builds so we'd like to avoid releasing anything to production during the sync delay period if it can't be fixed.

Are these changes scheduled for a certain time of day we could avoid?

**Comment by dagood** [comment]
> Is there a place where we can check for these normal service outages?

No, we have asked the team maintaining the service to give us something like this, and make it public. I'm not aware of any schedule for that work.

> Are these changes scheduled for a certain time of day we could avoid?

Any team can publish packages to the repos at any time, so unfortunately not.

**Comment by esetnik** [comment]
Maybe this issue should be left open so that other people who come across it understand that it's a known problem with no resolution. When I read #4122 I misunderstood that it was a temporary outage, not the expected behavior.

**Comment by lrstanley** [comment]
> Sync delays are expected as "normal" service outages whenever anyone publishes a package to these repos.

I think the problem here is that to everyone else, this isn't (or shouldn't be?) normal. We have ~15 redhat/ubuntu repos in our build containers from various companies (many with various subpaths), which likely get updated more frequently than the Microsoft ubuntu repo, and Microsofts ubuntu repo is the only one that experiences the above issues.

**Comment by dagood** [comment]
> I think the problem here is that to everyone else, this isn't (or shouldn't be?) normal.

It doesn't make sense to me either, hence the scare quotes. 😛 More on that in https://github.com/dotnet/core/issues/4122.

I opened https://github.com/dotnet/docs/issues/16670 for that issue too, to track adding a description of this problem to the docs (including how to identify it). IMO that's the best place to broadcast it as a known issue because it's where we direct people--it's a bit harder to get to dotnet/core.

**Comment by dagood** [comment]
On second thought, opened https://github.com/dotnet/core/issues/4167 as well. Thanks for the suggestion. Even once we have a description on the docs, it will be good to have a place to inform the community if we're able to make progress with the team responsible for these repos.

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/core/issues/4167

**Comment by jhdscript** [comment]
what is the solution ? i have this error :-(

`root@zemxeon:/home/jhd# apt update
Ign:1 http://mirrors.online.net/debian stretch InRelease
Hit:2 http://mirrors.online.net/debian stretch Release
Hit:3 http://security.debian.org stretch/updates InRelease
Get:6 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages [72.9 kB]
Err:6 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages
  Writing more data than expected (73307 > 72896)
  Hashes of expected file:
   - Filesize:72896 [weak]
   - SHA512:29d29a280aba2f0ee4f4b23375ab236a1c1000bc00474d761f95288e698ff897f95607aab391fed3c28c52b5225ff9bd5af0152a871153d4f3fdd3a176562176
   - SHA256:5f4c1c5e7c6bbd935da728a274ebe509a8f67c06561ad8ff528fd34838a847c3
   - SHA1:1c43c51bee2f71e4f36b8cde2b9e0f227828feec [weak]
   - MD5Sum:60045479c796d66d2fb677ea5327a378 [weak]
  Release file created at: Tue, 21 Jan 2020 21:32:06 +0000
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Writing more data than expected (73307 > 72896)
   Hashes of expected file:
    - Filesize:72896 [weak]
    - SHA512:29d29a280aba2f0ee4f4b23375ab236a1c1000bc00474d761f95288e698ff897f95607aab391fed3c28c52b5225ff9bd5af0152a871153d4f3fdd3a176562176
    - SHA256:5f4c1c5e7c6bbd935da728a274ebe509a8f67c06561ad8ff528fd34838a847c3
    - SHA1:1c43c51bee2f71e4f36b8cde2b9e0f227828feec [weak]
    - MD5Sum:60045479c796d66d2fb677ea5327a378 [weak]
   Release file created at: Tue, 21 Jan 2020 21:32:06 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

Any help will be appreciated. regards

**Comment by dagood** [comment]
@jhdscript Please file an issue if it doesn't resolve itself after 30 minutes. (I'm not able to reproduce it on my machine.) Frequent temporary outages are unfortunately a known issue with the service. See https://github.com/dotnet/core/issues/4167.

**Comment by jhdscript** [comment]
Ok thanx i retry tomorrow. Regards

**Comment by dagood** [comment]
Ahh, sorry @jhdscript, I think I messed up my test. I now see it happening on Debian 9. I'm now tracking that at https://github.com/dotnet/core/issues/4179.

**Comment by jhdscript** [comment]
Ok thanx i m waiting for a fix. Good luck friend
