### ISSUE TITLE
You can't open the application error message

### ISSUE THREAD

**Issue by RamsesMac** [dotnet/core#4170]
Got this error message after installing Visual Studio (opens fine) and .Net: 

You can’t open the application “Microsoft.NETCore.App.app” because it may be damaged or incomplete.

Running Catalina, with latest update, just updated Visual Studio.

New to this, any help is appreciated!

**Comment by carlossanlop** [comment]
> _You can’t open the application “Microsoft.NETCore.App.app” because it may be damaged or incomplete._
Have you tried reinstalling/restoring Visual Studio? The installation might be corrupted.

> _typed in ~$ dotnet in Terminal, said command not found._

Do you mean you typed "~$ dotnet"  including the tilde and the dollar sign, or just "dotnet"? You need to only type "dotnet". That command should be available after installing Visual Studio and the .NET Core SDK, making sure you open the Terminal _after_ the installation finishes.

I suggest you post your question in the "Report a problem" section of the Visual Studio Community website: https://developercommunity.visualstudio.com/content/problem/post.html?space=41

**Comment by RamsesMac** [comment]
I figured the Terminal part out shortly after I posted the original issue. I'm still getting the error message "You can't open the application....." when I try to open .Net in Finder

Any idea how I can fix that? Thanks.

I will post my question in VS community like you suggested.

**Comment by dagood** [comment]
> I'm still getting the error message "You can't open the application....." when I try to open .Net in Finder
> 
> Any idea how I can fix that? Thanks.

You aren't supposed to do that, is there a specific reason you're trying? (Something we can fix in the documentation to clarify this?)

If you want to explore the content, right click and select `Show package contents`. It's not an app, macOS is falsely assuming so because it's a directory that ends with `.App`.

**Comment by RamsesMac** [comment]
Thanks for letting me know. No, there is not a specific reason I need to open it, I was just trying to familiarize myself with what I've installed and I thought that's how you launch it.

But now I know it's not supposed to be opened, and of course not damaged.

Thank you!

**Comment by dagood** [comment]
Cool, yeah, it's unfortunate the error shows up that way. No problem. 🙂 Closing as resolved.
