### ISSUE TITLE
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4075.0 

### ISSUE THREAD

**Issue by Yuri-Assen** [dotnet/core#4172]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Note that .NET Core is a different product than .NET Framework.

The linked tutorial, and this repository, are for `Core`. You can retrieve .NET Core version info by running `dotnet --info`.

**Comment by scalablecory** [comment]
Closing due to lack of response; please reopen if you have more details.
