### ISSUE TITLE
User defined data type in Ado.net cause issue after upgrading to .net 3.1

### ISSUE THREAD

**Issue by Mrpankaj666** [dotnet/core#4174]
In .net core 2.2 its working fine but once I upgrade the project to .net core 3.1 its start failing only for user defined data type in ado
Error: Object must implement IConvertible

**Comment by carlossanlop** [comment]
@Mrpankaj666 can you please share a code snippet reproing the issue so we can better understand your problem?

cc @ajcvickers @cheenamalhotra @david-engel

**Comment by Mrpankaj666** [comment]
`var cmd = db.Database.GetDbConnection().CreateCommand();
			cmd.CommandText = "[dbo].[userfile123]";
			cmd.CommandType = CommandType.StoredProcedure;

            var fileParam = new SqlParameter
            {
                ParameterName = "@UserFileRecord",
                SqlDbType= SqlDbType.Structured,
                Value = `stageRecords`,
                TypeName = "[dbo].[UserFile]"
            };

			cmd.Parameters.Add(fileParam);
			
			cmd.Parameters.Add(new SqlParameter("@1", 1));
		

			if (cmd.Connection.State != ConnectionState.Open)
			{
				cmd.Connection.Open();
			}

			var results = new List<string>();
			using (var reader = await cmd.ExecuteReaderAsync(CommandBehavior.CloseConnection))`

@carlossanlop  here is the code but i cant share more as per the company policy
so there is type [dbo].[userfile] which is user defined table value type 
so this code working fine before upgrading to .net core 3.1
but now it says you need to implement iconvertible

**Comment by Mrpankaj666** [comment]
Hi @carlossanlop, can I get the reference for .net core 3.1 code packages like we have 
refrence.micorsoft.com for .net framework 4.8

**Comment by Mrpankaj666** [comment]
@carlossanlop 
here is the same error has been discussed which is most probably fixed in .net standard 2.0 for dapper
https://github.com/dotnet/corefx/issues/19708#issue-228274758

**Comment by Mrpankaj666** [comment]
Closing it as it was namespace issue
https://github.com/dotnet/SqlClient/issues/323
