### ISSUE TITLE
run dotnect in cmd

### ISSUE THREAD

**Issue by gaoqingweiGitHub** [dotnet/core#4181]
![image](https://user-images.githubusercontent.com/48580200/73125044-669b5680-3fdd-11ea-9226-3c67a7ab0a4a.png)

![screenshot](https://user-images.githubusercontent.com/48580200/73125091-f04b2400-3fdd-11ea-99ff-adf407d85832.jpg)

**Comment by scalablecory** [comment]
Please see the [Windows 7 / Vista / 8.1 / Server 2008 R2 instructions](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows#windows-7--vista--81--server-2008-r2) to install this dependency.
