### ISSUE TITLE
SignalR cannot connect to remote server

### ISSUE THREAD

**Issue by Latifjon** [dotnet/core#4183]
I have a SignalR project in winform.
When I start the server, the application starts the server at the address I specified. For example: "http: // localhost: 4951"
In the client, I specify the IP address of my computer as "http: //192.169.1.101:8080/signalr". However, the client cannot connect to the remote computer on which the server application is running, and it catches exception 400 (invalid request). If I run the client application locally where the server is running, everything is fine.

**Comment by Latifjon** [comment]
Anyone can help, please

**Comment by scalablecory** [comment]
When you bind to localhost, you can only connect via localhost addresses -- not addresses that are routable on your network. You should specify either "any" address or the IP specifically.
