### ISSUE TITLE
 http://localhost:5000  is not opening in my browser. Please help

### ISSUE THREAD

**Issue by tiwari6694** [dotnet/core#4190]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
What is the console output of your app?

**Comment by leecow** [comment]
Closing due to lack of response. Feel free to re-open and add details if you're still having issues.
