### ISSUE TITLE
Method with Yield Return not compiled correctly

### ISSUE THREAD

**Issue by gsscoder** [dotnet/core#4197]
This thing is really weird, I can't figure out why this method is not executed correctly and why it's impossible to step debugger into. More, this is true also for **.NET Framework** and using **Visual Studio**. Normally I use **.NET Core** with **VS Code**.

The code is the following:
```csharp
Weird(Enumerable.Empty<int>());

static IEnumerable<T> Weird<T>(IEnumerable<T> source)
{
    var e = source.GetEnumerator();
    if (!e.MoveNext()) throw new ArgumentException();
    while (e.MoveNext()) {
        yield return e.Current;
    }   
}
```
I would expect an `ArgumentException` to be thrown. But this doesn't happen!

But if I remove `yield return` (_with a forced change to the result type_), the exception is correctly thrown.
```csharp
static void Weird<T>(IEnumerable<T> source)
{
    var e = source.GetEnumerator();
    if (!e.MoveNext()) throw new ArgumentException();
    while (e.MoveNext()) {
        // yield return e.Current;
    }   
}
```
Also keeping the same method firm in the following way, makes the code work.
```csharp
static IEnumerable<T> Weird<T>(IEnumerable<T> source)
{
    var e = source.GetEnumerator();
    if (!e.MoveNext()) throw new ArgumentException();
    while (e.MoveNext()) {
        // yield return e.Current;
    }   
    return Enumerable.Empty<T>();
}
```
I think this proofs that compilation of `yield return` is the **guilty**.

This is the output of `dotnet --info` on my **macOS** Catalina:
```sh
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I'm really curious if I am wrong or this is something to be fixed.

Thank you for excellent job and thank you in advance for reply!

Best regards,
Giacomo

**Comment by SimonCropp** [comment]
if u dont enumerate the result of Weird i dont think it will ever execute

**Comment by GrabYourPitchforks** [comment]
There are some good answers at https://stackoverflow.com/q/30176121/59641 that explain this behavior. As soon as you write the `yield` keyword, the compiler turns your method implementation into a state machine. Your state machine won't start executing until the first time your caller invokes `IEnumerable.MoveNext()`.

So if you change your original sample from this:

```cs
Weird(Enumerable.Empty<int>());
```

To this:

```cs
IEnumerable<int> enumerable = Weird(Enumerable.Empty<int>());
IEnumerator<int> enumerator = enumerable.GetEnumerator();
bool success = enumerator.MoveNext(); // exception will be thrown here
```

Your code will activate and your `ArgumentException` will be thrown as soon as the commented line above is invoked.

**Comment by gsscoder** [comment]
@SimonCropp, I can't believe I didn't spotted this! I was so focused on writing a test on a method like this, that I was completely blind on something trivial. _Mea culpa_.

@GrabYourPitchforks, thank you for explanation! I'm aware of this. Sorry for useless issue, I think I've worked too much these days...
