### ISSUE TITLE
Not able to browse the microservice on the ExternalIP after deployment to AKS

### ISSUE THREAD

**Issue by anjkhan01** [dotnet/core#4201]
[SimpleMicroservice.zip](https://github.com/dotnet/core/files/4140030/SimpleMicroservice.zip)
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
