### ISSUE TITLE
Increase Nonce Limit on AES GCM

### ISSUE THREAD

**Issue by Tohrment** [dotnet/core#4202]
According to IETF RFC 5084 (https://tools.ietf.org/html/rfc5084) the nonce byte size ranges from 12-16 with the default being 12 bytes. The problem here is some things outside of my control are being sent with a 16 byte nonce byte size. My request is that the nonce byte size MaxSize be set to 16 and not the standard of 12.

**Comment by bartonjs** [comment]
The Windows cryptography libraries only support 96-bit nonces for GCM, even if we raised the check in the C# layer, it would fail at runtime due to a lack of system support.

Sorry, but there's nothing we can really do about it.

**Comment by Tohrment** [comment]
How does Python accomplish this if the OS itself does not support the 16 Byte nonce? I am not a dev and this is not meant to be a dig but rather a serious question. I can accomplish this using Python but this will be operating in an environment where getting Python installed is not necessarily feasible and would be much easier if possible to do it through .NET

**Comment by bartonjs** [comment]
Presumably, Python has their own implementation of GCM instead of asking the OS for it. .NET relies on the OS for cryptographic implementations for a variety of reasons.

**Comment by necoc-yaotl** [comment]
The most likely reason is conformance with [NIST SP 800-38D](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf), section 5.2.1.1:

  > For IVs, it is recommended that implementations restrict support to the length of 96 bits, to 
promote interoperability, efficiency, and simplicity of design.
