### ISSUE TITLE
.net Core 3.0.102 Kestrel Socket problem

### ISSUE THREAD

**Issue by yogigrantz** [dotnet/core#4204]
# Issue Title

.net Core 3.0.102 Kestrel Socket problem

# General

Created a default Web Application with .Net Core 3.0, using Visual Studio 2019 v**16.4.4**

Just out of the box - Published the application, and run the executable.

When publishing this solution and try to run the executable, it raised a **Kestrel error**:

System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions. at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName) at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapShot, SocketAddress socketAddress) at System.Net.Sockets.Socket.Bind(EndPoint localEP) at Microsoft.AspnetCore ..... .....

This error screen came up really really fast, and then disappeared.

GitHub: https://github.com/yogigrantz/WebApplication1KestrelProblem 

When this solution is published in a machine with VS2019 version **16.3.9** however, it **works fine**.

I am suspecting there is a faulty between 16.3.9 and 16.4.4 - Please see the [screenshots in the GitHub](https://github.com/yogigrantz/WebApplication1KestrelProblem)

**Comment by yogigrantz** [comment]
After further testing - uninstalled VS2019, uninstalled all .net Core versions. Rebooted. Reinstalled .net Core 3.0.102. Without VS 2019 I run **dotnet** publish from command line -> it produced the .exe. 

Clicked the executable - > Same error perists:  System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions. 

Copied that executable to a colleague machine, ran it from there. It ran fine!

Something in my machine tripped this: System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException

**Comment by yogigrantz** [comment]
OK just found the cause of the problem. It was IIS. IIS was running in my machine and it was obviously causing a conflict for Kestrel. When I stopped IIS. Kestrel would work fine. Lesson learned!

**Comment by scalablecory** [comment]
Glad you were able to solve this. Closing.
