### ISSUE TITLE
It Dosent Works in Cmd prompt but Visual Studio Works Well

### ISSUE THREAD

**Issue by syedshabeermtp** [dotnet/core#4205]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by SusLes** [comment]
Can you please give us more information?

**Comment by carlossanlop** [comment]
No response in 10 days. Closing.

**Comment by carlossanlop** [comment]
https://github.com/dotnet/core/issues/4166
