### ISSUE TITLE
error 4 in libcrypto.so.1.0.2k

### ISSUE THREAD

**Issue by itri-cyber** [dotnet/core#4206]
Hi,

When we are switching in smtp session to TLS with the code below for a specific domain the .net core crashes with

**dotnet[11913]: segfault at 0 ip 00007f0888c4ce20 sp 00007f07cc7e6a28 error 4 in libcrypto.so.1.0.2k[7f0888aeb000+236**

mmp.service: main process exited, code=killed, status=11/SEGV

The strange thing is for thousands of domains there is no problem but when we try to switch to TLS for domain **econika.ru** domain, the service crashes since it gets SEGV from libcrypto

The code is typical code to switch:

_tlsStream = new SslStream(new NetworkStream(_smtpServerSocket), false, ValidateServerCertificate, null)
{
// set timeouts.
ReadTimeout = GetReceiveTimeout(),
WriteTimeout = GetSendTimeout()
};

**_tlsStream.AuthenticateAsClient(_connectedServerIp, new X509CertificateCollection(), SslProtocols.Default | SslProtocols.Tls11 | SslProtocols.Tls12, false);**

The operating systems we have tried: 
CentOS Linux release 7.7.1908 (Core)
Oracle Linux Server 7.6

Important Note: There is no problem in windows. This problem is only with Linux os

Can you help ?

Thanks

**Comment by itri-cyber** [comment]
I believe this is much better output for you. This is the output of the lldb. Is it possible to fix using this output!...

Process 8030 stopped                                                                                                                  
* thread #48: tid = 8544, 0x00007f5747319e20 libcrypto.so.10`X509_get_subject_name, name = 'dotnet', stop reason = invalid address (fault address: 0x0)
    frame #0: 0x00007f5747319e20 libcrypto.so.10`X509_get_subject_name
libcrypto.so.10`X509_get_subject_name:
-> 0x7f5747319e20:  movq   (%rdi), %rax
   0x7f5747319e23:  movq   0x28(%rax), %rax
   0x7f5747319e27:  ret    
   0x7f5747319e28:  nopl   (%rax,%rax)

**Comment by itri-cyber** [comment]
Any help please ?

**Comment by itri-cyber** [comment]
I have solved the problem... On the linux, OpenSsl version was 1.0.2k. .netcore is using OpenSSL on linux to manage TLS. 

Just update OpenSSL version to 1.1.1c. Everything works much better

https://www.osradar.com/how-to-install-the-latest-version-of-openssl-on-centos-7/

**Comment by omajid** [comment]
Sorry I didn't see this issue earlier. You probably would have gotten more feedback if it was reported on https://github.com/dotnet/runtime. I have some thoughts, though:

- Recent versions of .NET Core support both OpenSSL 1.0.x and 1.1.x. Both OpenSSL versions should be supported.
-  The fact that it only fails against server makes me suspect it could be a bug in OpenSSL itself. Have you reporting it to CentOS/Oracle Linux folks?
- The assembler output of `lldb` is not very useful. If you could `debuginfo-install openssl-libs`, and re-run lldb, that output would be more useful for us.
- https://www.osradar.com/how-to-install-the-latest-version-of-openssl-on-centos-7/ tells you how to install one version of OpenSSL from source. You wont get automatic updates to any newer OpenSSL releases. That means any security vulnerabilities will not be automatically fixed unless you rebuild OpenSSL again. For example, at least 6 CVEs have been identified and fixed between 1.1.1c and 1.1.1g. I wouldn't recommend that for production.
