### ISSUE TITLE
error running microservice sample

### ISSUE THREAD

**Issue by payme2018** [dotnet/core#4208]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Copying the text title 

> error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=tr5k8zpc7b4qc44azjp9m2mkf&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

The last bit of the error message points to something important. Is Docker installed and running on your machine?

**Comment by scalablecory** [comment]
Closing out due to lack of response. Please reopen if you're still having an issue and able to provide more details.
