### ISSUE TITLE
Strange C: folder in ASP.NET Core 1.1 web app with Visual Studio 2017 RC

### ISSUE THREAD

**Issue by AdrienTorris** [dotnet/core#421]
I have a strange problem with Visual Studio 2017 RC. I created a solution (some class libraries and a ASP.NET Core 1.1 web application), and a C: folder appears in the solution, with the icon like it's deleted.

![strange-c-folder-in-visual-studio-2017-solution](https://cloud.githubusercontent.com/assets/1014357/21752693/52860a72-d5dd-11e6-846d-7d9efe4ab7f1.png)

When I try to delete it, I have this error :
> projectRelativePath must be a project relative path. Parameter name : projectRelativePath

Is somebody know what's happen here ?

**Comment by Petermarcu** [comment]
Thanks for reporting this. This is a known issue and one that is being addressed. I don't know if there is a workaround for now but I'm going to consolidate the discussion here: https://github.com/dotnet/core/issues/360
