### ISSUE TITLE
Cannot load netmodules in .NET Core 3.1

### ISSUE THREAD

**Issue by npolyak** [dotnet/core#4212]
# Cannot load netmodules in .net core 3.1

# General

Roslyn still produces netmodules. I am trying to assemble them into an assembly using Assembly.LoadModule(...). I am getting NotImplementedException. What is happening? Can I still build an assembly out of the netmodules? If not, what are the alternatives?

**Comment by 0xd4d** [comment]
It's not supported, see https://github.com/dotnet/runtime/issues/10598

**Comment by npolyak** [comment]
Thanks. I thought so too. I just thought that if one has completely independent code files, it will be faster and more memory efficient to compile them first to netmodules and then assemble together, rather then to either compile them all together or create a separate assembly for each one of them. Pity...
