### ISSUE TITLE
Options:   -h|--help         Display help.   --info            Display .NET Core information.   --list-sdks       Display the installed SDKs.   --list-runtimes   Display the installed runtimes.

### ISSUE THREAD

**Issue by DevTech2008** [dotnet/core#4213]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Closing out due to lack of response. Please reopen if you're still having an issue and able to provide more details.
