### ISSUE TITLE
not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2).

### ISSUE THREAD

**Issue by kingsleyfrancis** [dotnet/core#4214]
I have a .net core application that has been working fine as of last week. But I had to run a new OS due to a bad hard drive. Now am getting the following errors

> NU1202	Package Microsoft.CodeAnalysis.Workspaces.Common 2.8.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.CodeAnalysis.Workspaces.Common 2.8.0 does not support any target frameworks.	Soar	D:\Drive\OneDrive\Documents\Visual Studio 2017\Projects\Private\Soar\Soar\Soar.csproj	1	
> 
> NU1202	Package Dapper 1.50.5 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Dapper 1.50.5 does not support any target frameworks.	Soar	D:\Drive\OneDrive\Documents\Visual Studio 2017\Projects\Private\Soar\Soar\Soar.csproj	1	
> 
> NU1202	Package NuGet.Frameworks 4.7.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package NuGet.Frameworks 4.7.0 does not support any target frameworks.	Soar	D:\Drive\OneDrive\Documents\Visual Studio 2017\Projects\Private\Soar\Soar\Soar.csproj	1	
> 
> NU1202	Package Microsoft.VisualStudio.Web.CodeGeneration.Core 2.2.3 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.VisualStudio.Web.CodeGeneration.Core 2.2.3 does not support any target frameworks.	Soar	D:\Drive\OneDrive\Documents\Visual Studio 2017\Projects\Private\Soar\Soar\Soar.csproj	1	
> 
> NU1202	Package Npgsql 4.0.7 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Npgsql 4.0.7 does not support any target frameworks.	Soar	D:\Drive\OneDrive\Documents\Visual Studio 2017\Projects\Private\Soar\Soar\Soar.csproj	1	
> 
> NU1202	Package System.Runtime.CompilerServices.Unsafe 4.5.2 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package System.Runtime.CompilerServices.Unsafe 4.5.2 does not support any target frameworks.	Soar	D:\Drive\OneDrive\Documents\Visual Studio 2017\Projects\Private\Soar\Soar\Soar.csproj	1	

I installed several SDKs trying to fix the issue but its not just going away. Here is my dotnet info 

> NET Core SDK (reflecting any global.json):
>  Version:   2.2.207
>  Commit:    f7b16a2cd5
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x86
>  Base Path:   C:\Program Files (x86)\dotnet\sdk\2.2.207\
> 
> Host (useful for support):
>   Version: 2.2.8
>   Commit:  b9aa1abc51
> 
> .NET Core SDKs installed:
>   2.1.301 [C:\Program Files (x86)\dotnet\sdk]
>   2.1.502 [C:\Program Files (x86)\dotnet\sdk]
>   2.2.101 [C:\Program Files (x86)\dotnet\sdk]
>   2.2.105 [C:\Program Files (x86)\dotnet\sdk]
>   2.2.207 [C:\Program Files (x86)\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 
> 

My VS and Nuget Version are 
**Microsoft Visual Studio Enterprise 2017 Version 15.9.19
Nuget Package Manager - 4.6.0**

I have cleared nuget, bin and obj (in each of the projects) serveral times. I also changed the libraries from netcoreapp2.2 to netstandard2.0, the issues didnt go away. When I changed it back to netcoreapp2.2 I got the following error

> 2/3/2020 11:29:12 AM
> Recoverable
> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETCoreApp,Version=v2.2'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
>    at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
>    at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
>    at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
>    at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
>    at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
>    at Microsoft.VisualStudio.Design.VSTypeResolutionService.ClearReferenceEntries(Boolean normal, Boolean project, Boolean disposing)
>    at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceRemoved(Reference r)
>    at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.<>c__DisplayClass36_0.<OnReferenceRemoved>b__0()
>    at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass37_0.<Invoke>b__0()
>    at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
>    at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
>    at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
>    at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Please any idea of how to get out of this very much welcome as I have been stuck at this very point for several days now.

**Comment by scalablecory** [comment]
@rrelyea any ideas?

**Comment by scalablecory** [comment]
@kingsleyfrancis were you able to resolve this? It looks like your dependencies were not updated to support netcoreapp2.2 and maybe you should try their .NET Standard versions instead.

**Comment by kingsleyfrancis** [comment]
@scalablecory Yeah had to upgrade the project to .netcore 3.1. Thanks

**Comment by ilvarol** [comment]
Hey, I have the same problem you have, Please share solution of this problem with me if you've solved the problem

**Comment by ilvarol** [comment]
> Hey, I have the same problem you have, Please share solution of this problem with me if you've solved the problem

I solved my problem that way; 
https://stackoverflow.com/a/66173087/10995103

**Comment by scalablecory** [comment]
Glad this was solved, closing out.
