### ISSUE TITLE
PublishTrimmed will cause RESX satellite file not working.

### ISSUE THREAD

**Issue by lekia** [dotnet/core#4215]
# Issue Title
PublishTrimmed will cause RESX satellite file not working.

# General
.Net Core 3.0
Visual Studio 16.3.6

Sorry for my bad English.

I am building a Console App with .Net Core 3.0. 
I have a resx file (default language) with two satellite resx files(zh-Hans and zh-Hant, three of them are in the same assembly) for globalization.
Everything works fine before setting PublishTrimmed to True.
I can build with debug/release conf and it works as I set the CultureInfo and the language changed.

But when PublishTrimmed is set to True, without any other change, only the first satellite(zh-Hans) works while the latter one(zh-Hant) won't, and default language is shown.

Workaround:
As I published, I got a **full** version of the output in

> bin\Release\netcoreapp3.0\\**win-x86** (as folder "full" below)

and a **trimmed** version in

> bin\Release\netcoreapp3.0\\**publish**. (as folder "trimmed" below)

Each of the folder has a folder named

> "zh-Hans" (as "lang1" below)

and a folder named 

> "zh-Hant" (as "lang2" below)

 with .dll files in them.

The **lang2** works fine if I replace the .dll in the

> \trimmed\lang1

 with the one in 

> \trimmed\lang2

and set the culture to **lang1**, 

or replace the one in 

> \trimmed\lang2

with the **full** one in 

> \full\lang2

and set the culture to **lang2**.

changing the "zh-Hans" to "zh-CN" and the "zh-Hant" to "zh-TW" will not solve the issue.

Therefore, I guess the resx file compiled with PublishTrimmed works fine, but only in the first language folder.

**Comment by scalablecory** [comment]
@nguerrera

**Comment by swaroop-sridhar** [comment]
CC: @sbomer  @vitek-karas @tlakollo

**Comment by sbomer** [comment]
@lekia I haven't been able to reproduce this issue. Could you please try the following project and see if it works for you? [repro.zip](https://github.com/dotnet/core/files/4325978/repro.zip) Otherwise would you be able to provide a repro and additional information about the SDK you are using? Thanks!

**Comment by scalablecory** [comment]
Closing from lack of response.
