### ISSUE TITLE
Dotnet n;ao reconhecido

### ISSUE THREAD

**Issue by Smarisco** [dotnet/core#4217]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Apareceu a seguinte msg no prompt:
'dotnet' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by ltouro** [comment]
@Smarisco check if you opened a new command prompt after the installation (verifique se abriu um novo prompt de comando após a instalação).
```
If you receive a 'dotnet' is not recognized as an internal or external command error, make sure you opened a new command prompt. If you can't resolve the issue, use the I ran into an issue button to get help fixing the problem
```

**Comment by carlossanlop** [comment]
This is a common question with the same root cause, the cmd window needs to be opened after installing. No reply in 18 days, closing.
