### ISSUE TITLE
Listing packages does not work for Xamarin target frameworks

### ISSUE THREAD

**Issue by Cheesebaron** [dotnet/core#4218]
I would love to get a list of transitive packages for my Xamarin projects. However, running the `dotnet list package --include-transitive` command gives me the following errors.

For a Xamarin.Android project I get:

```
error: The imported project "/usr/local/share/dotnet/sdk/3.1.101/Xamarin/Android/Xamarin.Android.CSharp.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/3.1.101/Xamarin/Android/Xamarin.Android.CSharp.targets" is correct, and that the file exists on disk.
```

Similarly for a Xamarin.iOS project I get:

```
error: The imported project "/usr/local/share/dotnet/sdk/3.1.101/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/3.1.101/Xamarin/iOS/Xamarin.iOS.CSharp.targets" is correct, and that the file exists on disk.
```

Doesn't matter whether the `--include-transitive` flag is included or not.

**Comment by wilsondy** [comment]
try export MSBuildExtensionsPath=</path/to/>
before running the command
I had to make a custom denuded Xamarin.<platform>.CSharp.targets file because the real included other stuff that I could get to work
