### ISSUE TITLE
Getting message "IIS Express 8.0 or higher is not installed" trying to install .NET Core 1.0.1 VS 2015 Tooling Preview 2 in Windows 10 Enterprise

### ISSUE THREAD

**Issue by roberto-abs** [dotnet/core#422]
Hello

When trying to install .NET Core 1.0.1 VS 2015 Tooling Preview 2 I get the message specified on the subject;
My Pc has windows 10 Enterprise 10.0.14393 Build 14393 and I have IIS 10 installed

I attach three files: Two screen captures and the installation log; I've searched far and wide on Google but didn't find anything that solved the issue

Regards,

Roberto
[dd_DotNetCoreTools__20170110170806.txt](https://github.com/dotnet/core/files/696845/dd_DotNetCoreTools__20170110170806.txt)
![capture1](https://cloud.githubusercontent.com/assets/20423116/21816624/a4a36512-d758-11e6-8344-abdd611dfbce.png)
![capture2](https://cloud.githubusercontent.com/assets/20423116/21816625/a4a4f2d8-d758-11e6-954c-9563317114dc.png)

**Comment by juking** [comment]
It seems that I encountered the same problem

**Comment by Petermarcu** [comment]
Have you tried the VS 2017 RC tooling? Thats probably the better place to get started at this point and that is where all the bug fixes are going. https://www.microsoft.com/net/core#windowsvs2017

**Comment by Petermarcu** [comment]
@barrytang , Making sure you see this in case you believe this will also be an issue in 2017...

**Comment by roberto-abs** [comment]
Hello 

Thank you for your reply; I have just tried VS 2017 RC and the issue is not present there; I guess you can close this issue (or do I have to close it myself?)

**Comment by LorenzMichels** [comment]
Hi, I get the same message. Because I want to follow some book tutorials, I want to work with VS2015 and .NET core 1.0.1. Therefore I need to install .NET Core 1.0.1 VS 2015 Tooling Preview 2, but it shows the error "IIS Express 8.0 or higher is not installed". I am on Windows 10. How can I fix this?

**Comment by barrytang** [comment]
@LorenzMichels, VS 2015 tooling is in Preview. VS 2017 15.3 is now released and supports both 1.x and 2.0.
