### ISSUE TITLE
Unable to run the dotnet app after editing the Pages/Index.cshtml

### ISSUE THREAD

**Issue by chhavi811** [dotnet/core#4222]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Trying to run the edited file (Pages/Index.cshtml) by entering "dotnet run" on CMD. but it gives below error:

Couldn't find a project to run. Ensure a project exists in C:\Users\DELL, or pass the path to the project using --project.

Can anyone help please ?

**Comment by scalablecory** [comment]
Try "dotnet run" from inside the project directory.

**Comment by scalablecory** [comment]
Closing due to lack of response.
