### ISSUE TITLE
dotnet not fond

### ISSUE THREAD

**Issue by rburgiss** [dotnet/core#4226]
the term dotnet is not recognized as the name of a cmdlet, function, script file, or operable program.

Running windows 10

**Comment by rburgiss** [comment]
What does that mean?

**Comment by hkbiet** [comment]
i think dotnet is not supposed to run as a standalone command on the terminal , is that what you are trying to do ?

**Comment by rburgiss** [comment]
Trying to run windows 10 as a 16 bit system to run old pc game on it.

**Comment by hkbiet** [comment]
Seems like you might have got it removed from the ENVIRONMENT ; probably by uninstalling something old.. You may also want to try your hands here again ..https://dotnet.microsoft.com/download

**Comment by hkbiet** [comment]
> Trying to run windows 10 as a 16 bit system to run old pc game on it.

Seems like you might have got it removed from the ENVIRONMENT ; probably by uninstalling something old.. You may also want to try your hands here again ..https://dotnet.microsoft.com/download

**Comment by hkbiet** [comment]
> the term dotnet is not recognized as the name of a cmdlet, function, script file, or operable program.
> 
> Running windows 10

Seems like you might have got it removed from the ENVIRONMENT ; probably by uninstalling something old.. You may also want to try your hands here again ..https://dotnet.microsoft.com/download

**Comment by hkbiet** [comment]
Specifically, you have to Repair the Visual C++ 2015 Redistributable (both x86 and x64) via the "Programs and Feature" Window (a.k.a. Add/Remove Programs)

**Comment by rburgiss** [comment]
Hi

And thanks

I fix it now what?

**Comment by carlossanlop** [comment]
Did you install dotnet already? Did you make sure to open the command line _after_ you installed dotnet in your system?

**Comment by carlossanlop** [comment]
No response in 11 days. Closing.
