### ISSUE TITLE
Could not handshake: The TLS connection was non-properly terminated. | The repository 'https://packages.microsoft.com/ubuntu/19.04/prod disco Release' does not have a Release file.

### ISSUE THREAD

**Issue by hkbiet** [dotnet/core#4230]
# Could not handshake: The TLS connection was non-properly terminated. | The repository 'https://packages.microsoft.com/ubuntu/19.04/prod disco Release' does not have a Release file.

Trying to add above repo in Ubuntu 19 by following instructions as here https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904
and i get the error message . I have checked my https proxy settings in bash_rc file .

# Please see the image attached
![Screenshot from 2020-02-06 21-25-01](https://user-images.githubusercontent.com/15969042/73953990-32059400-4927-11ea-8ab0-79bfdeed1e58.png)

**Comment by dagood** [comment]
I'm unable to reproduce this issue here or see any issue with the feed currently. This appears to be a common problem with proxies, can you be more detailed with what you've tried so that others can help if they have ideas (or have seen this before)?
