### ISSUE TITLE
GraphicsPath.AddString is wrongly positioned on linux?

### ISSUE THREAD

**Issue by Hexxonite** [dotnet/core#4237]
I am currently writing a .NET Core 2.0 App to run cross-platform. Part of this is App is Drawing a Text and overlay onto a Bitmap.

So I added the latest System.Drawing.Common and finally ended up with a working Code(On Windows) like this:

    public static Bitmap WriteText(Bitmap bmp, string txt)
    {
        RectangleF rectf = new RectangleF(0, 0, bmp.Width, bmp.Height);

        // Create graphic object that will draw onto the bitmap
        using (Graphics g = Graphics.FromImage(bmp))
        {
            g.SmoothingMode = SmoothingMode.AntiAlias;
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            g.PixelOffsetMode = PixelOffsetMode.HighQuality;
            g.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            StringFormat format = new StringFormat()
            {
                Alignment = StringAlignment.Center,
                LineAlignment = StringAlignment.Center
            };
            // dampening
            using (Brush brush = new SolidBrush(Color.FromArgb(69, Color.Black)))
                g.FillRectangle(brush, rectf);

            var fSize = 26;
            var fFam = Fonts.GetDefaultFontName();
            // Draw the path
            GraphicsPath p = new GraphicsPath();
            p.AddString(txt, fFam, (int)FontStyle.Regular, g.DpiX * fSize / 72.2f, rectf, format);
            g.DrawPath(new Pen(Color.FromArgb(180, Color.Black), 8), p);
            // Draw the text
            g.DrawString(txt, new Font(fFam, fSize), Brushes.White, rectf, format);
            // Flush all graphics changes to the bitmap
            g.Flush();
        }
        // Now save or use the bitmap
        return bmp;
    }

On Windows 10 Outputs are generated correctly or as expected like this for Example:

https://i.stack.imgur.com/nHBl7.png

But when run on my Ubuntu 18.04 server, the GraphicsPath/Shadow would generate like this:

Notice the top left corner (it's a bit hard to see on dark background)

https://i.stack.imgur.com/onO2e.png

My first thought was an Error in the DPI-calculation since my Server doesn't have an X-Server installed but apparently the GraphicsPath is drawn correct; just the positioning is wrong?

Since the "Formatting" apparently works on the usual `DrawString` this behaviour seems weird to me, maybe the lack of the Emoji-Icon in the Font could be the cause of this?

Otherwise this looks like a platform-specific bug in the `System.Drawing` package to me... perhaps `.Net Standard 2.0` is also affected by this...

Thanks in advance.

**Comment by danmosemsft** [comment]
closing in favor of https://github.com/dotnet/runtime/issues/31979
