### ISSUE TITLE
16 BIT

### ISSUE THREAD

**Issue by rburgiss** [dotnet/core#4238]
Hi

Trying to play old computer games on windows 10 so have to make it into a 16 bit computer.
On this website it says  https://www.groovypost.com/howto/enable-16-bit-application-support-windows-10/    Configure 16-bit Application Support in Windows 10
16 Bit support will require enabling the NTVDM feature. To do so, press Windows key + R then type: optionalfeatures.exe then hit Enter. Expand Legacy Components then check off NTVDM and click OK. In the photo on the website it shows Legacy Components with the directplay and below that is NTVDM. But when I do the samething on my computer it does not show the NTVDM. See screen shot 
![image](https://user-images.githubusercontent.com/60711629/74060901-ef8c9780-49b8-11ea-90fb-cea7cd1b904c.png)

**Comment by scalablecory** [comment]
This repo is for .NET Core issues. This is unrelated to .NET Core, so I'm closing it.

See official NTVDM docs here: https://docs.microsoft.com/en-us/windows/compatibility/ntvdm-and-16-bit-app-support
