### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by martinpriv-cyber** [dotnet/core#4239]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by martinpriv-cyber** [comment]
al poner en internet http://localhost:5000, no me abre nada, me dice 
![image](https://user-images.githubusercontent.com/60798320/74068686-0643e600-49db-11ea-881e-5d79177ff927.png)

**Comment by antonioortizpola** [comment]
You have run the command to create a project, you need then to compile and run it.

It can be with

    dotnet run

while you are in the project folder

**Comment by martinpriv-cyber** [comment]
dale, ahora no encuentro la carpeta para editar el codigo, como la busco

**Comment by carlossanlop** [comment]
@martinpriv-cyber please make sure to follow the instructions step by step: https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run and also make sure to not save your project in `C:\Windows\System32`, use a different folder.
@martinpriv-cyber por favor asegúrate the seguir las instrucciones paso a paso https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run y evita guardar tu proyecto en `C:\Windows\System32`, tienes que usar un folder diferente.
