### ISSUE TITLE
Is .NET Core 3.1.1 deployed to Azure App Services?

### ISSUE THREAD

**Issue by kmuthukumar23** [dotnet/core#4244]
Deployed .NET Core 3.1.1 app into Azure App Services

Hi Team,

Is .NET Core 3.1.1 deployed to Azure App Services? 

https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.1/3.1.1.md#azure-app-services

I have faced the 503 error when i am install the core 3.1.1 sdk extension in azure service.

Can any one update the details regarding this?

**Comment by HeathU** [comment]
.NET Core 3.1.1 runtime is now showing today (February 10, 2020) on my App Service.

From the App Service console, try "dotnet --list-runtimes"

**Comment by leecow** [comment]
Confirmed, I'm seeing 3.1.1 in all regions.
