### ISSUE TITLE
Unable to install dotnet-sdk-2.2 on Ubuntu 19.10

### ISSUE THREAD

**Issue by dipunm** [dotnet/core#4245]
# Issue Title

Unable to install dotnet-sdk-2.2.

# General

I am using Ubuntu 19.10, and I have followed this page to the letter:
https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-ubuntu-1910
Including the part at the end labelled "Troubleshoot the package manager".

No matter what, dotnet-sdk-2.2 is missing:

Here is what is avaliable:
```bash
$> sudo apt search dotnet-sdk        
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1/eoan,now 2.1.803-1 amd64 [installed]
  Microsoft .NET Core SDK 2.1.803

dotnet-sdk-3.0/eoan 3.0.102-1 amd64
  Microsoft .NET Core SDK 3.0.102

dotnet-sdk-3.1/eoan,now 3.1.101-1 amd64 [installed]
  Microsoft .NET Core SDK 3.1.101
$> 
```
Not sure what more information I can provide, please let me know.

**Comment by dagood** [comment]
2.2 is EOL, so this is expected in new distros like 19.10. Earlier versions may have 2.2 versions available still, but only because we don't typically remove EOL versions from the repos.

I've filed https://github.com/dotnet/docs/issues/17034 to correct the docs, thanks for pointing this out.
