### ISSUE TITLE
How do I resolve a 'dotnet' is not recognized as an internal or external command error message

### ISSUE THREAD

**Issue by fmelles** [dotnet/core#4246]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Did you open a new command line _after_ you installed dotnet?

**Comment by carlossanlop** [comment]
No response in 11 days. Closing.
