### ISSUE TITLE
Pull from mcr.microsoft.com is too slow in china mainland

### ISSUE THREAD

**Issue by shikelong** [dotnet/core#4253]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

------

the speed is 4kb/s when I pull .net Core SDK image from`mcr.microsoft.com/dotnet/core/aspnet:3.1`. 

I try to pull from mcr.azk8s.cn (https://github.com/Azure/container-service-for-azure-china/tree/master/aks) and it still waiting.

```bash
docker pull mcr.azk8s.cn/dotnet/core/aspnet
```

How can I fix it? thanks.

**Comment by MichaelSimons** [comment]
@shikelong - Can you please log an issue for this at https://github.com/microsoft/ContainerRegistry/issues?

**Comment by shikelong** [comment]
Ok, thank you.
