### ISSUE TITLE
While running my first docker command i get the following error:

### ISSUE THREAD

**Issue by itsupportginatricot** [dotnet/core#4257]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install-docker
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by itsupportginatricot** [comment]
myMicroservice>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by scalablecory** [comment]
> In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Can you verify that you've checked these two things?

**Comment by scalablecory** [comment]
Closing out, please reopen if you can provide more detail.
