### ISSUE TITLE
usb flash driver

### ISSUE THREAD

**Issue by aneelk6** [dotnet/core#4259]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
It's not clear what issue you're encountering, can you please provide some detail?

**Comment by scalablecory** [comment]
Closing out, please reopen if you can provide detail.
