### ISSUE TITLE
Could not create an instance of type 'Microsoft.AspNetCore.Mvc.Rendering.SelectList'. Model bound complex types must not be abstract or value types and must have a parameterless constructor

### ISSUE THREAD

**Issue by ebonat** [dotnet/core#4260]
# Issue Title

hi,

i'm build a .net core 3.1 razor page now. i have a model table with fieldID and fieldName. 

in the index page i create a new column with a dropdown list as:

<select asp-for="fieldID " asp-items="@Model.dropdownName">
                            <option value=""></option>
                        </select>

this dropdownName  is defined in the  public async Task OnGetAsync() as:

 [BindProperty]
SelectList dropdownName = new SelectList(iEnumerable, "fieldID ", "fieldName");

when i open the index page, i got the error:

_InvalidOperationException: Could not create an instance of type 'Microsoft.AspNetCore.Mvc.Rendering.SelectList'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, set the 'dropdownName' property to a non-null value in the 'WebApp.IndexModelSites' constructor._

I did use the  [BindProperty] of dropdownName  because in the post event 'public IActionResult OnPost()' i want to get these values fieldID and fieldName to update another table. so far without [BindProperty] the dropdownName = null. 

how to pass these values to the post event, or the 'dropdownName'? or how to set the 'dropdownName' property to a non-null value in the constructor?

any good tip or work around about this issue? any good google link? is anyone had this issue before?

thank your for your help

-ernest

**Comment by scalablecory** [comment]
have you been able to resolve this? if not, can you please paste your model class in here? Thanks. CC @Pilchie

**Comment by ebonat** [comment]
Yes and thank you!

Cheers

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Analyst

**Comment by odomaf** [comment]
I would love to know what the solution was, as I am having the same problem.

**Comment by sondt** [comment]
Check null value properties

**Comment by widemar** [comment]
You have to create an empty constructor in your model class.

**Comment by widemar** [comment]
You have to create an empty constructor in your model class.

**Comment by BruceInCalgary** [comment]
Hi widemar,

I have an ASP.Net Core web application and am getting this same error with a SelectList class instance bound to a Bootstrap Select list object on the form.  My constructor is injecting several resources so I cannot have an empty constructor for my model class (I get an error of course if I have 2 different constructors).  Here is my constructor:

`public CreateEmailModel(
               Book2DayDbContext B2Ddb,
               Book2DayWebApp.Services.IEmailSender emailSender,
               IDataProtectionProvider provider,
               IWebHostEnvironment hostingEnvironment,
               INotyfService notifyService,
               IConfiguration configuration)
        {
            _B2Ddb = B2Ddb;
            //_B2DUserdb = B2DUserdb;
            _emailSender = emailSender;
            _dpProvider = provider.CreateProtector(Protector.PurposeStringV1);
            _Protector = new Protector(provider);
            _env = hostingEnvironment;
            _notifyService = notifyService;
            _configuration = configuration;  //used for pagination

        }`

Do you have any other ideas that could solve this issue in my case?  

P.S. I don't have a lot of web development experience! :-)  Am primarily a Windows application developer.

Thank you!  best regards, Bruce

**Comment by BruceInCalgary** [comment]
Hi widemar,

I took a look at my code and solved the problem I was having (getting the error Could not create an instance of type 'Microsoft.AspNetCore.Mvc.Rendering.SelectList').  I had the [BindProperty] attribute for my select list:

` [BindProperty]
`
`        public SelectList SpecialsSelect { get; set; }`

I removed the BindProperty attribute and now the error doesn't occur.  

The Html for my select list is:

` <div class="col-6 ">
`        <label asp-for="@Model.EmailForClients.SpecialOfferId" class="mb-1">Special Offers</label>
`       <select disabled class="form-select justify-content-start" id="SpecialOffer" name="SpecialsId" asp-for="@Model.EmailForClients.SpecialOfferId" asp-items="@Model.SpecialsSelect">
`                        <option selected value="0">Select A Special</option>
`                    </select>
`                    <span asp-validation-for="@Model.EmailForClients.SpecialOffer" id="SpecialOfferError" class="text-danger"> </span>
`</div>

Hope this helps!

Best regards, Bruce

**Comment by wallym** [comment]
> Hi widemar,
> 
> I took a look at my code and solved the problem I was having (getting the error Could not create an instance of type 'Microsoft.AspNetCore.Mvc.Rendering.SelectList'). I had the [BindProperty] attribute for my select list:
> 
> `[BindProperty]` ` public SelectList SpecialsSelect { get; set; }`
> 
> I removed the BindProperty attribute and now the error doesn't occur.
> 
> The Html for my select list is:
> 
> `<div class="col-6 ">` Special Offers ` <select disabled class="form-select justify-content-start" id="SpecialOffer" name="SpecialsId" asp-for="@Model.EmailForClients.SpecialOfferId" asp-items="@Model.SpecialsSelect">` Select A Special ` </select>` `
> 
> Hope this helps!
> 
> Best regards, Bruce

I just ran across this error.  I just knew that taking away the 'BindProperty' wouldn't do anything any more, and it solved my problem as well.  :-)
