### ISSUE TITLE
Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\myWebApp' is denied.

### ISSUE THREAD

**Issue by emperorboy888** [dotnet/core#4263]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Try running the "dotnet new" command from a directory you have access to, such as a subdirectory in your user directory.

**Comment by carlossanlop** [comment]
Closing since the question has been answered.
