### ISSUE TITLE
 error: 'packages-microsoft-prod.deb' is not a Debian format archive Ubuntu-Mate 18.04

### ISSUE THREAD

**Issue by chgruver** [dotnet/core#4264]
In trying to install .net Core on Ubuntu Mate I get the following error when trying to run the command "sudo dpkg -i packages-microsoft-prod.deb" 
 error: 'packages-microsoft-prod.deb' is not a Debian format archive 
preventing me from further installing .net Core on my system and the troubleshooting section assumes that you have sucessfully gotten past this step in installing .net Core.

**Comment by dagood** [comment]
What most likely happened here is a failed download. I'd suggest trying again (perhaps on a different machine) and comparing the file size and a checksum.

* I assume you're following https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804, can you confirm?
* With the `wget -q` command, can you try running it without `-q` to show more diagnostic info, and post the results here?

See https://github.com/dotnet/core/issues/3752

**Comment by scalablecory** [comment]
Closing; please reopen if you can provide more detail.
