### ISSUE TITLE
Docker installation failed.. I have windows 10 pro OS nad 10240 build number

### ISSUE THREAD

**Issue by supriyasunildhage** [dotnet/core#4265]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install-docker
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@supriyasunildhage can you please provide more information? What command did you run? What was the exact error message?

**Comment by scalablecory** [comment]
Closing out, please reopen if you can provide detail.

**Comment by scalablecory** [comment]
#4166
