### ISSUE TITLE
Is .NET Core 3.1.1 getting deployed on GCP?

### ISSUE THREAD

**Issue by dheerajyadav25** [dotnet/core#4267]
Unable to deploy .net core 3.0+ app on google cloud
Be as descriptive as you can with your title.

getting error o valid .NET Core runtime version found for the app or it is not a supported app.

**Comment by leecow** [comment]
Hi @dheerajyadav25 - availability on GCP will be entirely update to the Google Cloud maintainers. They generally keep up with releasesd, particularly when security-related. Please check with them.
