### ISSUE TITLE
Ubuntu 16.10 apt packages

### ISSUE THREAD

**Issue by damccull** [dotnet/core#427]
When trying to install the dotnet cli preview 4, I can't find the packages on the Ubuntu 16.10 repo. The 16.04 repo contains it, but it won't install because there's no ability to install libicu55. It says it has no installation candidate. You can only find this out after trying to manually install dotnet-sharedframework-microsoft.netcore.app-1.0.1.

Please set up a way for us to install this preview on the latest ubuntu system too!

**Comment by Petermarcu** [comment]
@piotrpMSFT @gkhanna79 , do we need to update the libicu dependency in our runtime 16.10 apt packages and then flow them up through the CLI?

**Comment by Petermarcu** [comment]
These are missing and we're working on making sure they build for the RTM release. Thanks for pointing this out. In the meantime, I posted some hacks to get up and running on 16.10 here if you are interested: https://github.com/dotnet/core/issues/496

Also, you may see a daily dev build show up here: https://github.com/dotnet/cli/tree/rel/1.0.0
