### ISSUE TITLE
uwp: when will we have .netcore runtime 3.1 ? [question]

### ISSUE THREAD

**Issue by jtorjo** [dotnet/core#4271]
# uwp: when will we have .netcore runtime 3.1 ?

Currently, UWP apps use .netcore 2.2 runtime. It seems that UWP is always the last to get updates, and they are the buggiest.

**When will we have support for .netcore runtime 3.1 in UWP?**

**Comment by carlossanlop** [comment]
@tommcdon @jashook can you please take a look?

**Comment by tommcdon** [comment]
Thank you for the feedback.  UWP issues are tracked as Azure DevOps issue.  If you are running into .NET native issues, please see https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options.

**Comment by jtorjo** [comment]
@tommcdon I don't understand. It's useless for me to ask this question on the VS2019 app. Where I am I supposed to ask it, if not here?
