### ISSUE TITLE
Utter confusion

### ISSUE THREAD

**Issue by Korporal** [dotnet/core#428]
Is ".Net Core 1.0.1" the same thing as ".Net Core 1.0.1 tools Preview 2"? The proliferation of confusing and overlapping product names and versions is maddening, how do you expect developers to keep up?

Could someone please let us all know every .Net Core download Microsoft have released so far and exactly what they are?

You may understand my confusion when you consider I was simply trying to follow a tutorial here:

http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

That mentions ".Net Core 1.0.1" and the link for that takes me here:

https://blogs.msdn.microsoft.com/dotnet/2016/09/13/announcing-september-2016-updates-for-net-core-1-0/

That page talks a lot about installing ".Net Core 1.0.1" but seems to have no helpful Download link!!

Searching for downloads of .Net Core gets me here:

https://www.microsoft.com/net/download/core

But that page refers to ".Net Core 1.0.3 SDK"? Excuse me? SDK, Tools, erm what's going on here?

So utterly confused, I visit this page next:

https://www.microsoft.com/net/core#windowsvs2015

That doesn't mention ".Net Core 1.0.3 SDK" but rather ".Net Core 1.0.1 tools Preview 2".

Sorry Microsoft this make all make sense to those deeply involved in these emerging technologies, but you're all doing a terrible job at actually explaining all this.

So far I see these "product" mentioned by Microsoft:

".Net Core 1.0.1"
".Net Core 1.0.1 tools Preview 2"
".Net Core 1.0.3 SDK".

Don't you agree that setting up a page that collects all of .Net Core downloads into a single place, with a brief summary of what each one is would be nice for all the developers who are keen to explore what you've been doing?

How hard is that? a ".Net Core Downloads" page with every published/released installable product mentioned and summarized?

**Comment by Korporal** [comment]
@kendrahavens - Perhaps you can get someone to look at this?

**Comment by Petermarcu** [comment]
Yeah, there is a lot of confusion here and we're working on what to do for the next release. 

SDK == Command line tools, Tools == Visual Studio in this context. The Visual Studio Tools releases install the SDK for you. That could be more clear. 

Maybe it shouldn't say Tools as that is implied by Visual Studio?

This is the place that is intended to be where you get the collection of .NET Core downloads all listed out.
https://www.microsoft.com/net/download/core

**Comment by AndrewCarre** [comment]
I am encountering the same issues when trying to launch sample projects and seed projects. I always have the wrong version installed despite having the latest version installed...

Why isn't these versions backward compatible? We are still on 1.* right? Is .net core following [semvers](http://semver.org/)?

**Comment by Lutando** [comment]
I agree with OP. It is even confusing when you try your best to keep up. It sometimes feel like they use preview postfixes to jump out of the ruleset that semantic versioning requires.

**Comment by filipw** [comment]
this calls for @terrajobst

**Comment by terrajobst** [comment]
Thanks for filing his. There are several folks here discussing what we can do. The naming and downloads pages aren't exactly helpful, I agree.

**Comment by n-alex-white** [comment]
Equally confusing - I hear that dotnet 1.1 is moving from project.json to csproj. On my Mac I'm generating things with project.json, so I try to get dotnet 1.1 - but all the installers are 1.0.0*. However, it then turns out that that installer was installing dotnet 1.1 ... but still creates project.json rather than csproj files.

So I'm confused. Is dotnet 1.1 different for different platforms? What else can I expect to find or not find?

**Comment by davidfowl** [comment]
> Equally confusing - I hear that dotnet 1.1 is moving from project.json to csproj.

That's not quite right. The toolchain and the runtime are separate. Right now the **released** .NET Core Tools still target `project.json` as the MSBuild support is still heavily being developed. If you want to use the new csproj then you need to acquire a pre-release build of the .NET Core Tools.

**Comment by n-alex-white** [comment]
Thanks for the clarification (perhaps it is just the messaging around this that I've found confusing). 

Oddly it seems that Visual Studio Mac preview 3 **only** understands csproj projects, while everything else on the mac (aspnet new, yo aspnet) **only** produces .json projects. This element of being out of step doesn't help while attempting to grok what is going on.

**Comment by davidfowl** [comment]
Yes, we're in the thick of it. Once we have shipped msbuild support in a non-prerelease form, all things will be updated to use it. Right now we're a bit staggered.

**Comment by Jeremiad** [comment]
It would be also nice to have meta-packages for Linux repos so that you can easily upgrade between versions without installing every minor version manually.

As a example:

dotnet-dev-1.0.0-preview
dotnet-dev-1.0.0-rc
dotnet-dev-1.0
dotnet-dev-1
and so on.

**Comment by Petermarcu** [comment]
Today the RTM of the tooling was released. You can look here . All the preview versions confusion should be gone. Everyone should be using the RTM bits now. https://www.microsoft.com/net/download/core#
