### ISSUE TITLE
dotnet-projectmodel-server

### ISSUE THREAD

**Issue by Korporal** [dotnet/core#429]
This is really wasting my time, after just installing ".Net 1.0.1 tools Preview 2" (hoping this is the same thing or includes ".Net 1.0.1 <without the tools bits>) then opening VS 2015 and selecting the template "ASP.NET Core Angular 2 Starter Application (.NET Core)" I get this wonderful message box (from which I can't copy paste incidentally, when ARE Microsoft gonna fix that?).

The error message box whines about 1.0.0-preview4-004233 and an inability to start dotnet-projectmodel-server.

Apart from this it is bewildering to see a message referring to "1.0.0-preview4" after I just installed ".Net Core 1.0.1 tools Preview 2".

The versions differ: 1.0.0 v 1.0.1
The previews differ: 4 v 2

Yes I know half the planet have complained about this error but it's one more thing you need to understand, this unreliability and poor quality experience is avoidable, all it takes is that someone CARES and makes it an agenda action at your next team meeting to improve customer satisfaction and simplify the effort needed to actually use your technologies.

My previous issue post is related.

I just do not have the time to unravel all of this version/preview/tools/sdk/1.01/1.0.03/ etc etc just to create and work on a simple TypeScript Angular project!!

I have a small team of developers to lead, I need to understand and answer questions posed by management - we PAY for all of this via our MSDN subscription, please be mindful if that.

**Comment by davidfowl** [comment]
Does your project have a global.json? Did you install vs2017?

**Comment by blackdwarf** [comment]
This can also help: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md

**Comment by richlander** [comment]
Please re-activate if this is still an issue.

**Comment by r0f3n** [comment]
I think David's question means, "A global.json file with the correct version information could help you". Well, did the trick for me.
