### ISSUE TITLE
dotnet: command not found. 

### ISSUE THREAD

**Issue by rahat036** [dotnet/core#4295]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

![image](https://user-images.githubusercontent.com/3930410/74921382-e6a7b700-53f7-11ea-9ec9-3f7ecd6756b0.png)

After installing the dotnet core sdk, I can't create application in Windows Terminal as well as the cmd. 

Need your support.

**Comment by scalablecory** [comment]
Are you trying to run the Windows SDK in WSL? If so, you will instead want to install the Linux SDK.

**Comment by rahat036** [comment]
> 
> 
> Are you trying to run the Windows SDK in WSL? If so, you will instead want to install the Linux SDK.

Hi, Yes I am using WSL. Installed Linux SDK also, but no luck!

**Comment by leecow** [comment]
@rahat036 - exactly how did you perform the installation?

**Comment by scalablecory** [comment]
Closing out due to lack of response. Please reopen if you're still having an issue and able to provide more details.
