### ISSUE TITLE
3.1.102 release - regression in dotnet build command

### ISSUE THREAD

**Issue by adnan-kamili** [dotnet/core#4296]
After upgrading from 3.1.0 to 3.1.102 the following command
```
dotnet build
```
generates dll instead of binary on MacOS.

I tried adding `<OutputType>Exe</OutputType>` property to .csproj file (which is not even required), but still it is generating dll.

My .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IncludeOpenAPIAnalyzers>true</IncludeOpenAPIAnalyzers>
    <DocumentationFile>bin\Debug\netcoreapp3.1\MyWebApi.xml</DocumentationFile>
    <noWarn>1591</noWarn>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  ...
```

**Comment by Pilchie** [comment]
Adding @wli3 and @jeffschwMSFT - I believe this is a planned change to not use the AppHost by default on macOS because of notarization requirements.  Where did we document that change?

**Comment by jeffschwMSFT** [comment]
@adnan-kamili sorry for the surprise on this.  As @Pilchie points out this was an intentional change.  To opt into using the apphost please use the following:
```
<PropertyGroup>
  <UseAppHost>true</UseAppHost>
</PropertyGroup>
```
The documentation to explain this is in pr: https://github.com/dotnet/docs/pull/17092

**Comment by leecow** [comment]
@rbhanda / @vivmishra  - Please add this to the 3.1 release notes.
