### ISSUE TITLE
Flakiness in CentOS 7 Linux package repository, encountered >5 times per day

### ISSUE THREAD

**Issue by dagood** [dotnet/core#4298]
> Ok so I am running into this over five times a day, each time it seems to work if I try again in a few minutes. It's turning out to be a major productivity problem when we have multiple image builds per day on cluster - each one has to be manually checked and rerun when they fail. I am just wondering if the RPM repo will ever be reliable:
> ```
> Downloading packages:
> https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
> Trying other mirror.
> 
> Error downloading packages:
>   netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.
> ```

_Originally posted by @yoshiya8 in https://github.com/dotnet/core/issues/4280#issuecomment-589175267_

**Comment by dagood** [comment]
I wonder if you are possibly getting routed to a broken/unhealthy mirror vs. a healthy one. We recently discovered that the package repos can have per-mirror problems and the repo owners don't have a way to find the issues by themselves yet. (https://github.com/dotnet/core/issues/4236, very scary. We're following up the best we can with the service owners as part of the general push for reliability tracked at https://github.com/dotnet/core/issues/4167.)

@yoshiya8 do you have IP addresses packages.microsoft.com is being resolved to in your logs? That could be used to tell which mirror cluster you're using and help the repo owners narrow down their search, if this is indeed the problem.

**Comment by yoshiya8** [comment]
```
$ping packages.microsoft.com
PING apt-eus-d.cloudapp.net (40.76.35.62) 56(84) bytes of data.
```
Then hangs

**Comment by dagood** [comment]
Interesting, thanks for the details. Yeah, it's actually easy to repro even outside the region using the IP:

```
$ while :; do wget --no-check-certificate https://40.76.35.62/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm; done
...
$ for x in net*; do echo "$(md5sum $x | cut -d' ' -f1 ) $(wc -c $x)"; done
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm
8214edb8e45e49e909fcf4def15bd110 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.1
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.10
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.2
8214edb8e45e49e909fcf4def15bd110 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.3
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.4
8214edb8e45e49e909fcf4def15bd110 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.5
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.6
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.7
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.8
403fff7fe128c636d71c082086fe6a3b 2201944 netstandard-targeting-pack-2.1.0-x64.rpm.9
```

@NikolaMilosavljevic is passing this along to the linux repo owners to get fixed, we'll update here once they've tried something. They were able to manually fix up the mirroring last time.

**Comment by NikolaMilosavljevic** [comment]
This issue was fixed yesterday, by repo owners - all mirrors have correct files now.

@yoshiya8 , have you experienced any more instances of this issue?

**Comment by NikolaMilosavljevic** [comment]
Closing the issue as there has been no more reported instances.
