### ISSUE TITLE
System.ComponentModel.Win32Exception (13): Permission denied

### ISSUE THREAD

**Issue by chudix** [dotnet/core#4303]
**Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run**
**Operating System: linux**

Hi. Im facing an issue in asp.net tutorial. After installing i just created an app using:
```sh
 $ dotnet new webApp -o myWebApp --no-https
```

Then i just ran:
```
myWebApp/$ dotnet run
```

which fails with this traceback:
```
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

Here is dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  e5d3faa5b3

.NET Core SDKs installed:
  3.1.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

Needless to say that i dont know asp.net.. so any help is wellcome.

**Comment by scalablecory** [comment]
It seems like you don't have execute permissions for whatever path it is trying to execute. @wli3 @dsplaisted any ideas what it could be?

**Comment by dsplaisted** [comment]
How did you install the .NET Core SDK?  I think this might happen if you install it as root and then try to use it as a normal user, or vice versa.

**Comment by chudix** [comment]
Hi! Sorry for the delay i was on a trip.
**I just solved it.** 
Altought at the time to post this question i double checked execution permissions in the project folder(traceback explicitly says it), it was a permission issue, as @scalablecory mentioned.
So... here's the situation:

I've got a "projects" folder where i put all my sources, which is on another partition mounted with fstab. It has execution permissions but among all options it seems like *exec* directive should be **after** *user* directive. So i changed:
```sh 
#/etc/fstab
UUID....  <mount_point> <fs_type> <some_opts>,exec,user <dump> <pass>
to
UUID....  <mount_point> <fs_type> <some_opts>,user,exec <dump> <pass>
```
And it ran smoothly, so im closing this issue as it was an OS issue rather than dotnet. 

Thanks for the answers anyway!!

**Comment by Arslan-Munir** [comment]
Hi @chudix 
Can you please tell me how you solved this issue?
I am facing exactly this permission problem. and unable to solve.

**Comment by chudix** [comment]
Hi @Arslan-Munir. 
As i mentioned in closing comment it was a wrong fstab configuration, refer to that for a deeper explanation. There is a thing with user and exec options position so i just change my fstab file and reset.

Anyway... if you are seeing that error message you should check for execution permissions in the project's folder. Or maybe check @dsplaisted comment: 

> How did you install the .NET Core SDK? I think this might happen if you install it as root and then try to use it as a normal user, or vice versa.

Hope you find the solution. :)

**Comment by Arslan-Munir** [comment]
@chudix 
I follow this guideline to install dotnet core on Ubuntu
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

My project is in another mounted disk.
When i run dotnet run from that folder, i got permission error.
The permission are like this
![image](https://user-images.githubusercontent.com/46858790/89924143-08516080-dc1b-11ea-96ad-64f9b76848b3.png)

Can you help me? I would really thankful. Its almost three days now and i am stuck.

**Comment by chudix** [comment]
I'll do my best.

I suggest:
Make a dummy project on your os disk/partition where you installed dotnet.
```
$ dotnet new dummy -o dummy --no-https
```
Then run it with dotnet run. If it runs then the problem is how you are mounting the disk for sure.
```
dummy/$ dotnet run
```
Btw... how are you mounting it? I remember that permissions seemed to be right but that option misconfig was messing all silently.

**Comment by Arslan-Munir** [comment]
@chudix i did what you said. and i got the same error on both dotnet run and dotnet watch run.
I mount disk at the time of installation. One thing i notice that when i restart or power on the machine, the partitions are again mounted. but data inside them not lose.

**Comment by chudix** [comment]
So it seems like it's the install rather than a mounting issue.

I would uninstall dotnet via apt and give it a try to a non admin scripted install...

https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#scripted-install

Anyway, since i'm not an ubuntu user i cant help you troubleshot the apt installation. I'll give a try on a VM later... and see what happens.

Maybe you could take that issue to the ubuntu forums?
