### ISSUE TITLE
dotnet is not recognized as an internal or external command. How i can fix this ? 

### ISSUE THREAD

**Issue by Neicle** [dotnet/core#4304]
![download](https://user-images.githubusercontent.com/796298/75063173-2e324f80-5499-11ea-96fa-2ab4f19f3abc.png)

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

Operating System: windows

Error: dotnet is not recognized as an internal or external command

**Comment by blowdart** [comment]
Did you install the SDK? That error looks like it hasn't been installed.

**Comment by Neicle** [comment]
I download a net Sdk (64 bit) after that i enter in cmd dotnet and recive a
dotnet is not recognized.... Can you tel me how to install it? I need c#

**Comment by blowdart** [comment]
Once you've download it you need to install it by clicking the file you downloaded. 

Once it's installed and you open a new command window the dotnet command should work for you. 

It does have to be a new command window though, any ones you had open before you ran the installer won't be updated.

**Comment by carlossanlop** [comment]
The cmd window needs to be opened _after_ installing dotnet so that it detects the new path in the environment variable.
This is a common question, so I'll consider the issue resolved.
