### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Thushacsc** [dotnet/core#4306]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message,
![error on cmd](https://user-images.githubusercontent.com/30925366/75093291-4774f200-55a6-11ea-8161-347f19ecf0c1.PNG)
 code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
The compiler is telling you that Program.cs isn't valid C#. What are the exact contents of your Program.cs file?

**Comment by GrabYourPitchforks** [comment]
No response. Closing.
