### ISSUE TITLE
dotnet not being used by other files

### ISSUE THREAD

**Issue by Racingduck** [dotnet/core#4309]
I am trying to install SpringSharp but it will not see dotnet being installed and I just need help and there is zero guides/tutorials on this issue I am on windows 10 and just need help figuring this out

**Comment by scalablecory** [comment]
It looks like SpringSharp is a .NET Framework application, not .NET Core. Try ensuring you have the latest version of .NET Framework installed -- I see they have a link to it on their download page

If this doesn't work, you may need to get help from SpringSharp on how to set it up. Thanks.
