### ISSUE TITLE
"Dotnet: command not" found after install

### ISSUE THREAD

**Issue by radding** [dotnet/core#431]
I'm using mac OS seirra on two computers. One is running:10.12.2 (16C68). I'm not sure about the other computer. On both machines I follow the instructions on https://www.microsoft.com/net/core#macos. Both are using Bash.

How ever, after that is complete, you can't run `dotnet` in the terminal. But the instructions for [Z-shell on the known issues page](https://github.com/dotnet/core/blob/master/cli/known-issues.md#users-of-zsh-z-shell-dont-get-dotnet-on-the-path-after-install) works, perhaps that is not an issue for just z-shell users?

**Comment by leecow** [comment]
Hi @radding, how are you installing .NET Core?

**Comment by radding** [comment]
The same way the first link describes. I follow those instructions exactly.

**Comment by richlander** [comment]
Please re-activate if this is still an issue.

**Comment by MasiahX** [comment]
I am also facing this issue. How was it resolved?

**Comment by karelz** [comment]
@MasiahX please try to download again to avoid corrupted install situation. Ideally try on more than 1 machine / VM if you can.
If you have a repro with our latest supported version (either .NET Core 2.2 or .NET Core 3.0 Preview), please file a new issue. Thanks!

**Comment by msarm** [comment]
I've the same issue on mac OS seirra :-(
