### ISSUE TITLE
.Net not working with VS ?? I can't find reason 

### ISSUE THREAD

**Issue by robert0525** [dotnet/core#4310]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi, I want to learn C# as my first backend language. I am following tutorial from Treehouse but instead of using an online text editor I want to use Visual Studio. However, when I run "dotnet run" in a terminal in VisualStudio the program won't run.  :( .  I installed C#  extension as well as dotnet version 3.1 

But when I want to run my program this message coimg out " The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Roberts-MacBook-Pro:Lesson_3 robertrydlewski$ ls
Program.cs              bin                     obj                     workspace.csproj
Roberts-MacBook-Pro:Lesson_3 robertrydlewski$ dotnet run
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64
"

I don't understand the .NET is already installed the program working only with a treehouse text editor. 
any clue what's going on and how to fix it ??  Do I have to install version 2.1 ??? I thought since I have the latest version it should be working with the old version.  Please help as  I am stuck with it for past 8 hours :(

**Comment by scalablecory** [comment]
I'm not familiar with Treehouse, but they may be using a private version of .NET somehow. Have you followed the installation steps for .NET?

**Comment by GerardSmit** [comment]
I think the TargetFramework in the project file (`workspace.csproj` in your case) is set to `netcoreapp2.1`. If this is the case, `dotnet` tries to compile the project using .NET Core 2.1, which you don't have installed.

You can do the following:

1. **Install .NET Core 2.1**  
   Which can be downloaded here: https://dotnet.microsoft.com/download/dotnet-core/2.1
2. **Replace `netcoreapp2.1` to `netcoreapp3.1` in workspace.csproj**  
   I don't know what kind of Treehouse tutorial you're following but there are some changes in ASP.Net Core (see https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1). You'll have to keep that in mind that the tutorial may be outdated.

**Comment by mairaw** [comment]
Thanks @GerardSmit. @robert0525 please let us know if any of the options above worked for you.

If not, please post the contents of your csproj here so we can further help you.

**Comment by robert0525** [comment]
Hey, yes it works for me.
In my case, first I installed the newest version 3.1 of .Net however, when
I run my program I get error and message about version (2.1 or 2.8 don't
 remember exactly now)
The point is, I was confused as I thought the newest update have it all.
However that wasn't the case. I had to installed older version as well and
the errors disaster. Why??? I have no clue ( I didn't delete the new
version, just installed older one)

**Comment by GerardSmit** [comment]
This is because .NET Core is not backwards compatible with previous major releases.

So for example, if you have .NET Core 3.1 installed, you can compile and run .NET Core 3.0 and 3.1 projects but you can't compile 2.x projects.

**Comment by robert0525** [comment]
Thank you for the explanation.
It makes sense now.

Enjoy your weekend

**Comment by leecow** [comment]
Resolved by the @GerardSmit answer. Closing.
