### ISSUE TITLE
Even after installing dotnet, still dotnet not recognized as command in terminal

### ISSUE THREAD

**Issue by neeschalgrd** [dotnet/core#4313]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Thanks for your feedback @neeschalgrd. Did you follow the advice on the page?

If you receive a 'dotnet' is not recognized as an internal or external command error, make sure you opened a new command prompt. If you can't resolve the issue, use the I ran into an issue button to get help fixing the problem.

**Comment by scalablecory** [comment]
Closing this out; please reopen if you can provide additional detail.
