### ISSUE TITLE
not recognized

### ISSUE THREAD

**Issue by sundarraj11** [dotnet/core#4316]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

C:\Users\sundarraj.A>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by scalablecory** [comment]
Please close and reopen command prompt windows. The installer updates PATH variables that need to be re-read.

**Comment by scalablecory** [comment]
Closing out due to lack of response. Please reopen if you're still having an issue and able to provide more details.
