### ISSUE TITLE
Ubuntu 18.04 Error after update

### ISSUE THREAD

**Issue by tukafab** [dotnet/core#4319]
Hello,
i need help :(
After updating my system this morning, i cant compile or debug my code.
I get an permission error. After that i have to uninstall and reinstalled all dotnet components.

If i now run "dotnet run" as sudo it runs fine, but without root permission i get this error message:

/usr/share/dotnet/sdk/3.1.102/NuGet.targets(528,5): error : Unable to obtain lock file access on '/tmp/NuGetScratch/lock/665f0adc76874c4064f8c5bf3760fa1cc76a5603' for operations on '/home/fabian/.nuget/NuGet/NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/665f0adc76874c4064f8c5bf3760fa1cc76a5603' will allow NuGet to continue. [/home/fabian/Workspace/VMToolKIT/VMToolKIT.csproj]

My System Ubuntu 18.04.4 LTS
With vscode 1.42.0
My system had installed the following packages this morning:
dotnet-runtime-3.1:amd64 (3.1.1-1, 3.1.2-1), 
dotnet-apphost-pack-3.1:amd64 (3.1.1-1, 3.1.2-1), 
dotnet-sdk-3.1:amd64 (3.1.101-1, 3.1.102-1), 
dotnet-host:amd64 (3.1.1-1, 3.1.2-1),
dotnet-hostfxr-3.1:amd64 (3.1.1-1, 3.1.2-1),
dotnet-runtime-deps-3.1:amd64 (3.1.1-1, 3.1.2-1), 
aspnetcore-targeting-pack-3.1:amd64 (3.1.0-1, 3.1.2-1),
aspnetcore-runtime-3.1:amd64 (3.1.1-1, 3.1.2-1),

**Comment by leecow** [comment]
> After updating my system this morning

Can you tell us more about what update you did?

**Comment by tukafab** [comment]
Sure :) 
Here the complete apt history.log 

Start-Date: 2020-02-26  08:56:59
Commandline: aptdaemon role='role-commit-packages' sender=':1.83'
Install: fwupd-signed:amd64 (1.10~ubuntu18.04.3+1.2.10-1ubuntu2~ubuntu18.04.3, automatic)
Upgrade: dotnet-runtime-3.1:amd64 (3.1.1-1, 3.1.2-1), dotnet-apphost-pack-3.1:amd64 (3.1.1-1, 3.1.2-1), dotnet-sdk-3.1:amd64 (3.1.101-1, 3.1.102-1), dotnet-host:amd64 (3.1.1-1, 3.1.2-1), fwupdate:amd64 (12-3bion
ic2, 12-7~ubuntu18.04.3), apport:amd64 (2.20.9-0ubuntu7.9, 2.20.9-0ubuntu7.11), python3-apport:amd64 (2.20.9-0ubuntu7.9, 2.20.9-0ubuntu7.11), dmidecode:amd64 (3.1-1, 3.1-1ubuntu0.1), dotnet-hostfxr-3.1:amd64 (3.
1.1-1, 3.1.2-1), libfwupd2:amd64 (1.0.9-0ubuntu2, 1.2.10-1ubuntu2~ubuntu18.04.3), apport-gtk:amd64 (2.20.9-0ubuntu7.9, 2.20.9-0ubuntu7.11), fwupd:amd64 (1.0.9-0ubuntu2, 1.2.10-1ubuntu2~ubuntu18.04.3), dotnet-run
time-deps-3.1:amd64 (3.1.1-1, 3.1.2-1), aspnetcore-targeting-pack-3.1:amd64 (3.1.0-1, 3.1.2-1), fwupdate-signed:amd64 (1.19bionic2+12-3bionic2, 12-7~ubuntu18.04.3), aspnetcore-runtime-3.1:amd64 (3.1.1-1, 3.1.2-1
), python3-problem-report:amd64 (2.20.9-0ubuntu7.9, 2.20.9-0ubuntu7.11)
End-Date: 2020-02-26  08:57:15

Start-Date: 2020-02-26  11:30:25
Commandline: apt-get upgrade
Requested-By: fabian (1000)
Upgrade: xserver-common:amd64 (2:1.19.6-1ubuntu4.3, 2:1.19.6-1ubuntu4.4), xserver-xephyr:amd64 (2:1.19.6-1ubuntu4.3, 2:1.19.6-1ubuntu4.4), nautilus:amd64 (1:3.26.4-0~ubuntu18.04.4, 1:3.26.4-0~ubuntu18.04.5), libnautilus-extension1a:amd64 (1:3.26.4-0~ubuntu18.04.4, 1:3.26.4-0~ubuntu18.04.5), xwayland:amd64 (2:1.19.6-1ubuntu4.3, 2:1.19.6-1ubuntu4.4), nautilus-data:amd64 (1:3.26.4-0~ubuntu18.04.4, 1:3.26.4-0~ubuntu18.04.5)
End-Date: 2020-02-26  11:30:28

**Comment by carlossanlop** [comment]
@leecow

**Comment by leecow** [comment]
About the only thing I can think of is to clear out the nuget cache (/home/fabian/.nuget and /tmp/NuGetScratch. It will be rebuilt on your next build or `dotnet restore`.

**Comment by mairaw** [comment]
Did you try that @tukafab?

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
