### ISSUE TITLE
Starting Com interop access failed

### ISSUE THREAD

**Issue by sidatacom** [dotnet/core#4320]
If i open a accdb normal with access itself it works greate,
but if i open via BindToMoniker its directly closing after startup.
                      
`App.OAccess = (Access)Marshal.BindToMoniker(db)`

I use Visual Studio 2019 new newest one and .Net Core 3.1 with WPF also the newest one.

The Access has a Autoexce Macro which open a Form.
When i add a MessageBox in the Autoexec Macro at first everything works fine.

**Comment by scalablecory** [comment]
Can you provide more context and code reproducing the issue? It's not clear what you're using / trying to do.

**Comment by sidatacom** [comment]
sorry actually i have no time to create a sample. we don't use the Marshal.BindToMoniker(db) Methode any more because its buggy and wait for the next updates in the com area.
than we tested again.

**Comment by scalablecory** [comment]
Okay. Please feel free to open a new issue if you're able to provide a repro or further detail.

**Comment by sidatacom** [comment]
So now we have more time to test and its 100% clear that the bindtomoniker function not working with 64Bit version of Access.
Everything worked fine with 32bit version.
So its not possible to oben any database with the function.
