### ISSUE TITLE
is not compatible with netcoreapp

### ISSUE THREAD

**Issue by warniaha** [dotnet/core#4323]
is not compatible with netcoreapp

I'm having what looks like an identical issue to https://github.com/dotnet/core/issues/2077

One minute every worked perfectly, and then suddenly I get the "is not compatible with netcoreapp" error.
Other machines with identical paths are working perfectly.  There were some online references to the paths being too long, but I think that has been eliminated based on it working on other machines, and it previously working on that machine in that same path.

Error	NU1202	Package <my-home-grown-package-built-for-netcoreapp2.1> is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package <my-home-grown-package-built-for-netcoreapp2.1> does not support any target frameworks.

I've tried clearing the caches and wiping out every instance of my packages on the disk to no avail,

How can I find out what the real error is?

**Comment by warniaha** [comment]
Thinking I could attempt to debug it myself, I forked & built https://github.com/NuGet/NuGet.Client  This fixed the issue on the machine.  I still don't know what the root cause for the issue was.  I hope this helps someone else encountering the same issue.

A note for Nuget.exe developers:  When an issue is encountered, please try to bubble up the real issue and report it instead of the high level error.  In my coding I utilize the Exception class inner exception for keeping a list of all of the problems encountered and finally reporting all of them as a tree.  For example:
Error NU1202 Package <package-name> is not compatible with netcoreapp2.1
+ Failed to include Package <package-name> because file package-name.nuspec was inaccessible
++ Package path c:\some\very\long\path\that\breaks\nuget exceeds the path limitation

**Comment by carlossanlop** [comment]
Please open an issue in the NuGet repo.
