### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by naveenvamshi971** [dotnet/core#4325]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

C:\Users\Naveen\Downloads>dotnet                                                                                       
 'dotnet' is not recognized as an internal or external command,                                                          operable program or batch file.

**Comment by scalablecory** [comment]
Please close and reopen your console window.

**Comment by scalablecory** [comment]
CC https://github.com/dotnet/runtime/issues/1610
