### ISSUE TITLE
Smaller release package size

### ISSUE THREAD

**Issue by 15092368540** [dotnet/core#4328]
Smaller release package size， do not need to install .NET Core 3.1 Desktop Runtime, Enjoy!

[dotnet Cleanup.zip](https://github.com/dotnet/core/files/4261559/dotnet.Cleanup.zip)
![S1](https://user-images.githubusercontent.com/49462433/75444718-ee8acc80-599e-11ea-8478-6424a672552e.png)

**Comment by scalablecory** [comment]
Do you have a comment or suggestion regarding these files?

**Comment by scalablecory** [comment]
Closing out due to lack of response. Please reopen if you're able to provide more details.
