### ISSUE TITLE
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check  the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by hsujason127** [dotnet/core#4337]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Did you close and reopen the cmd window before running "dotnet"?

**Comment by scalablecory** [comment]
Closing this out; please reopen if you can provide additional detail.

**Comment by Constantino** [comment]
I had this issue when setting up the environment for the first time in a new virtual machine.

I fixed by installing the latest PowerShell x64 version, then I ran this command and worked: 
> dotnet --version
