### ISSUE TITLE
.NET sdk installation issue

### ISSUE THREAD

**Issue by HemanthVarmaS** [dotnet/core#4339]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I am using windows 10, 64 bit, I tried installing as per the instructions give in the above link, couldn't even get par the first instruction, please help me fix this:
I am receiving this message " 'dotnet' is not recognized as an internal or external command error", even after opening new command prompt.
![Annotation 2020-03-02 0843191](https://user-images.githubusercontent.com/45379484/75642641-35f4af80-5c62-11ea-82ae-e4ba759dd82d.png)
 a new command prompt

**Comment by scalablecory** [comment]
Can you take a look at your environmental variables and see if .NET is located in your PATH?

**Comment by scalablecory** [comment]
Closing this out; please reopen if you can provide additional detail.

**Comment by HemanthVarmaS** [comment]
hello
sorry for the delay
Below are the path's' I have in "system variables"
![Screenshot (71)](https://user-images.githubusercontent.com/45379484/77536853-11879e00-6ec3-11ea-89b8-8f13f0dde7d0.png)

**Comment by HemanthVarmaS** [comment]
and this one is what has appeared when clicked path in "user variables" section
![Screenshot (72)](https://user-images.githubusercontent.com/45379484/77536918-33812080-6ec3-11ea-9d43-ced0df52014f.png)

**Comment by HemanthVarmaS** [comment]
Thank You!
Finally got it.
