### ISSUE TITLE
.net stylesheet

### ISSUE THREAD

**Issue by Dananafez** [dotnet/core#4341]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Did you need help with something? Please provide detail.

**Comment by GrabYourPitchforks** [comment]
No response. Closing.
