### ISSUE TITLE
GitHub Builds Failing Due to Invalid releases-index.json or releases.json

### ISSUE THREAD

**Issue by definesfineout** [dotnet/core#4344]
See https://github.com/microsoft/azure-pipelines-tasks/issues/10968
This is a recurring issue that's been opened and resolved multiple times.

**Comment by dustinfineout** [comment]
##[error]Unexpected token : in JSON at position 3
Run actions/setup-dotnet@v1.2.0
  with:
    dotnet-version: 3.1.100
/home/runner/work/_actions/actions/setup-dotnet/v1.2.0/externals/get-os-distro.sh
Primary:linux-x64
Legacy:ubuntu.18.04
Checking tool cache
Getting a download url 3.1.100
##[error]Unexpected token : in JSON at position 3

**Comment by dustinfineout** [comment]
This morning, tried updating the setup-dotnet to v1.4.0 (above 1.2.0 we were previously using) and the builds are passing. I'm not certain where the fix is, but thought I'd share this resolution.

**Comment by Kengelgon** [comment]
> This morning, tried updating the setup-dotnet to v1.4.0 (above 1.2.0 we were previously using) and the builds are passing. I'm not certain where the fix is, but thought I'd share this resolution.

How about a fix for 2019 sever/on prem edition? DotNetCoreInstaller@0 is the only option we have

**Comment by dustinfineout** [comment]
> > This morning, tried updating the setup-dotnet to v1.4.0 (above 1.2.0 we were previously using) and the builds are passing. I'm not certain where the fix is, but thought I'd share this resolution.
> 
> How about a fix for 2019 sever/on prem edition? DotNetCoreInstaller@0 is the only option.

Alas, I'm a complete newcomer to GitHub workflows 😞

**Comment by adamralph** [comment]
What's the status of this? I cannot build a release package due to this.

**Comment by adamralph** [comment]
FWIW, I managed to work around it by upgrading to a later version of https://github.com/actions/setup-dotnet.

**Comment by leecow** [comment]
I'm glad the pipelines scenario got straightened out. The last update to the 3.1 releases-json was 3 weeks ago so seems to be something in the azure pipeline task which was fixed.

@adamralph - https://github.com/actions/setup-dotnet is a community project and not controlled or driven by the .NET release folks. If you experience issues with the action in the future, please log an issue in that repo. Now that I know it exists, I can also keep an eye out.

**Comment by adamralph** [comment]
@leecow I don't think there's anything wrong with https://github.com/actions/setup-dotnet. This seems to be a recurring problem in the .NET releases. It's just that later versions of setup-dotnet seem to be immune to it. There could well be other things out there which rely on the .NET releases being well-formed.

**Comment by leecow** [comment]
> There could well be other things out there which rely on the .NET releases being well-formed.

I definitely agree with that statement!
