### ISSUE TITLE
dotnet run is not working

### ISSUE THREAD

**Issue by rhwong07209** [dotnet/core#4349]
I follow the instruction provided to start my .Net app but I stucked at the localhost/:5000 part. After I install the .Net features using command prompt. I type in dotnet run but it shows "Couldn't find a project to run. Ensure a project exists in C:\Users\HAO, or pass the path to the project using --project."
localhost:/:5000 is also not working. Please help me I solve this problem. I cant run my .cs file. Thank you.

**Comment by scalablecory** [comment]
Did you create a new project? You must run "dotnet run" from within the project directory.

**Comment by rhwong07209** [comment]
I have a simple file with .cs extension within the project directory

**Comment by davidfowl** [comment]
You need to make a project, you cannot run a single cs fie (at least not yet). Try `dotnet new console`, then try to `dotnet run` it.

**Comment by rhwong07209** [comment]
The "dotnet new console" runs successfully, i get a HAO.csproj and
program.cs file after that. Then, i try "dotnet run" it give me an another
error message

**Comment by svick** [comment]
What is the error message?

**Comment by mairaw** [comment]
Closing due to the lack of response.
