### ISSUE TITLE
.NET Core 1.0.3 for Mac is "404 Not Found"

### ISSUE THREAD

**Issue by winzig** [dotnet/core#435]
On the downloads page: https://www.microsoft.com/net/download/core

If you try to download the pkg or .tar.gz for macOS 64-bit of .NET Core, a 1KB .pkg and .zip file gets downloaded, and if you open the file in a text editor, you will see that it's a 404 Not Found HTML webpage. 

As far as I can tell, .NET Core 1.0.3 is required if you want to develop Lambda applications for C# on macOS, so that is why I am trying to download it.

**Comment by kendrahavens** [comment]
It looks like the LTS SDK and Runtime installs for Windows x64 and x84 are also missing.

**Comment by leecow** [comment]
Sorry about that ... fixed!

**Comment by hknakata** [comment]
it seems the download links for 5.0.8 for mac is missing again. an HTTP 404 page is shown.

**Comment by mairaw** [comment]
@hknakata we were having a download site outage that started on 7/23 and was resolved a few days later.
For more information, see https://github.com/dotnet/core/issues/6509.
