### ISSUE TITLE
.netcore for Microcontroller

### ISSUE THREAD

**Issue by PankajRawat333** [dotnet/core#4350]
# .Netcore on ESP32 Microcontroller

I would like to run .netcore on ESP32 or any other microcontroller. As of now I found only [nanoFramework](https://nanoframework.net/) to run .net code with very limited packages for Azure.

Is there any future plan to support .net core on microcontroller, especially low memory device like ESP32?

**Comment by scalablecory** [comment]
There are currently no plans to bring .NET Core to microcontrollers. Currently we require one of Windows, Linux, Mac OS to run on.

**Comment by PankajRawat333** [comment]
> There are currently no plans to bring .NET Core to microcontrollers. Currently we require one of Windows, Linux, Mac OS to run on.

Thanks for reply... Then we can play with nanoframework

**Comment by Korporal** [comment]
> There are currently no plans to bring .NET Core to microcontrollers. Currently we require one of Windows, Linux, Mac OS to run on.

Can you explain why we need an OS? Why can't the CLR just be run without the OS?
