### ISSUE TITLE
Timout issue running RUN dotnet restore

### ISSUE THREAD

**Issue by jloomis87** [dotnet/core#4353]
![Capture](https://user-images.githubusercontent.com/12769169/75918582-3d11ee00-5e19-11ea-8cea-025b19f7dbd9.PNG)

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Seems like this might be either a temporary issue (network error etc.), or a misconfiguration of docker (no networking support) -- have you been able to resolve this?

CC @MichaelSimons
