### ISSUE TITLE
Can not get Datetime to work. Tried using on corresponding cs files.

### ISSUE THREAD

**Issue by proafxin** [dotnet/core#4358]
![image](https://user-images.githubusercontent.com/2643770/75960298-ffc96100-5ee9-11ea-87d1-3b57da8f9b79.png)

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by svick** [comment]
Based on the error message, I think you have `Datetime` (with lowercase t) in your code, when it should be `DateTime` (with capital T).
