### ISSUE TITLE
dotnet tool install -g mlnet

### ISSUE THREAD

**Issue by sheen1** [dotnet/core#4359]
# Issue Title

Be as descriptive as you can with your title.

# General
Nothing happending post firing of this commond in terminal.

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by scalablecory** [comment]
There must be something happening. What is the output of the command? Can you run "mlnet" in console now?

**Comment by sheen1** [comment]
Yes I tried running it in the terminal, there's just nothing happening post
that command.
When I run that , it says the command Is not found.

**Comment by leecow** [comment]
What environment are you running on? What do you see in the terminal after running `dotnet tool install -g mlnet`? For example, when I run on my Mac I see. 

```
➜ dotnet tool install -g mlnet
You can invoke the tool using the following command: mlnet
Tool 'mlnet' (version '0.15.1') was successfully installed.
```

**Comment by carlossanlop** [comment]
No response in 20 days. Closing. @sheen1 feel free to reopen if you have an answer.
