### ISSUE TITLE
sailor219

### ISSUE THREAD

**Issue by Sailor219** [dotnet/core#4364]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Sailor219** [comment]
it was blocked

**Comment by scalablecory** [comment]
Is the website hosting the download blocked? Is the EXE blocked?

What's going on?

**Comment by GrabYourPitchforks** [comment]
Closing as no response received.
