### ISSUE TITLE
Problem of transaction asynchronously executed in environment other than Windows

### ISSUE THREAD

**Issue by 7k8m** [dotnet/core#4368]
# Issue Title
Transaction of System.Data executed asynchronously fails in environment other than Windows

# General
In Windows environment transaction processing in asynchronous execution works, but samecode fails in other environment like as ubuntu.

Please see next URL for detail.
https://github.com/DirectSQL/DirectSQL/issues/1

**Comment by scalablecory** [comment]
It's not clear where the problem is here. Can you reduce this to a small case that does not depend on another library? Thanks.

**Comment by 7k8m** [comment]
Not only with System.Data.SQLite, but similar phenomena happened with Microsoft.Data.Sqlite also.

I just tried Microsoft.Data.Sqlite instead of System.Data.SQLite, but result was same. 
https://github.com/DirectSQL/DirectSQL/issues/1#issuecomment-596166864

SQLite itself is a *library*. 
There might be some restriction on SQLite when executed asynchronously other than, on Windows. 😬

**Comment by scalablecory** [comment]
We probably won't be able to look at GitHub automation for you. Does this reproduce if you run it manually in Ubuntu?

**Comment by 7k8m** [comment]
Yes.

````
tmnk@toy:~/DirectSQL$ dotnet test
Test run for /home/tmnk/DirectSQL/TestSqlLiteDatabase/bin/Debug/netcoreapp3.1/TestSqlLiteDatabase.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: This SqliteTransaction has completed; it is no longer usable.                                                                                       
   at Microsoft.Data.Sqlite.SqliteTransaction.Rollback()
   at DirectSQL.Database`5.TransactionAsync(C connection, AsyncSqlExecution`2 execute) in /home/tmnk/DirectSQL/DirectSQL/Database.cs:line 408
   at TestSqlLiteDatabase.TransactionTest.<>c.<<TestTransactionAsync>b__1_0>d.MoveNext() in /home/tmnk/DirectSQL/TestSqlLiteDatabase/TransactionTest.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

                                                                                                                                                                                                                                                                                
Test Run Aborted.
Total tests: Unknown
     Passed: 9
 Total time: 1.9519 Seconds
````

**Comment by 7k8m** [comment]
This might have something to do with ...
https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/async

**Comment by 7k8m** [comment]
I found this was just bug in code of testing.
Sorry for disturbing. 🙏🏻
