### ISSUE TITLE
net core 3.1 worker service as windows service

### ISSUE THREAD

**Issue by azizkazdal** [dotnet/core#4371]
net core 3.1 worker service as windows service does not work

tried to run windows service on Windows 10 Pro 1909 and Windows Server 20102 R2

Working on net core 3.1 worker project. I am facing a weird situation I can not understand the reason behind it. When I start the worker service as a console application (double clicking the exe file) worker service which has a few background task working fine but when start the worker windows server (I added it as windows service and it started without error) nothing happens. There are no signal that worker service is working. It is not accessing the API or don't do any other jobs.
And also can not see anything on Event viewer. 
I published the application as self-contained and x64
Need some help please.

**Comment by ilyoniss** [comment]
any updates..? I have the same issues.

**Comment by mars-boy** [comment]
Check if u have added Microsoft.Extensions.Hosting.Windowsservices package

**Comment by ilyoniss** [comment]
> Yes, I have Microsoft.Extensions.Hosting.WindowsServices.dll  3.1.8 build.
Problems that service is starting, but Backgroudservice and task ExecuteAsyinc is starting but only performs only one loop cycle.

**Comment by sannanify** [comment]
Hi I am having the same issue that my worker service doesn't seems to be working after installation. Does anyone of you know how you have fixed this issue. Please I need an urgent response on this one. 

Thank you.

**Comment by sannanify** [comment]
It is working when I run the .exe file manually but when I install it in services.msc it doesn't seems to be working even though the status shows that the worker service is in "running" state.

**Comment by ramprudvi** [comment]
I am having same issue any useful link would be great
Steps to reproduce:
1. Simple Worker Service project
2.  Worker Code 
 public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                WriteLog($"log{DateTime.Now.ToString("ddMMyyyy")}.txt", $"Worker running at: { DateTimeOffset.Now}");
                await Task.Delay(1000, stoppingToken);
            }
        }
        public static bool WriteLog(string strFileName, string strMessage)
        {
            try
            {
                FileStream objFilestream = new FileStream(string.Format("{0}\\{1}", Path.GetTempPath(), strFileName), FileMode.Append, FileAccess.Write);
                StreamWriter objStreamWriter = new StreamWriter((Stream)objFilestream);
                objStreamWriter.WriteLine(strMessage);
                objStreamWriter.Close();
                objFilestream.Close();
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

    }
Program.cs
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args).UseWindowsService()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
    }
3. dotnet publish --output "C:\custom\publish\directory"
4. sc create SampleService binPath=C:\custom\publish\directory\SamplerService.exe
5. sc start SampleService
Service is starting and running but no events are firing up.

**Comment by ramprudvi** [comment]
> Hey @azizkazdal I am facing the same issue may i found the workaround for the same

Please suggest

**Comment by azizkazdal** [comment]
@ramprudvi 
I have changed the release model of application that time and all worker background service was successfulyy worked. So I have not tried self contained release yet. Now I am on Net 5 an still not using self contained application.

**Comment by ramprudvi** [comment]
Hi Dotnet/Core,

May I know release model suited for you

**Comment by barama199612314566767** [comment]
hello, i have problem all project in where install windows 10,workerservice cannt go tu run,its ready always,what problem its can be? can someone help me, please
