### ISSUE TITLE
HTTP Error 404.0 not found

### ISSUE THREAD

**Issue by bharathsai1211** [dotnet/core#4372]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
What is the link you're trying to reach?

**Comment by GrabYourPitchforks** [comment]
No response - closing issue.
