### ISSUE TITLE
CSC : error CS2019: Tipo de destino no válido para /target: se debe especificar 'exe', 'winexe', 'library' o 'module' [/home/pablo/mipuntonet/mipuntonet.csproj]  No se pudo llevar a cabo la compilación. Corrija los errores de compilación y vuelva a ejecutar el proyecto.

### ISSUE THREAD

**Issue by pquezadam** [dotnet/core#4375]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by pquezadam** [comment]
CSC : error CS2019: Tipo de destino no válido para /target: se debe especificar 'exe', 'winexe', 'library' o 'module' [/home/pablo/mipuntonet/mipuntonet.csproj]

No se pudo llevar a cabo la compilación. Corrija los errores de compilación y vuelva a ejecutar el proyecto.

**Comment by mairaw** [comment]
Can you paste a screenshot of the error you're getting?

Google translate: 
¿Puedes pegar una captura de pantalla del error que estás recibiendo?
