### ISSUE TITLE
Azure Devops Server ".Net Core SDK Installer" task fails

### ISSUE THREAD

**Issue by stavroskasidis** [dotnet/core#4376]
Hello, I am trying to use the core sdk installer task on Azure Devops Server to install the latest sdk on the agent, however the following error occurs. It seems to me that it is looking for a json file in this repo that does not exist or is invalid.

![image](https://user-images.githubusercontent.com/12549761/76294179-0b86a000-62bb-11ea-857f-ae2aff97b229.png)

![image](https://user-images.githubusercontent.com/12549761/76294097-e4c86980-62ba-11ea-9ae5-227d2268e3ec.png)

**Comment by dagood** [comment]
I would guess the task is thrown off by the 404 page of the deprecated file that was finally removed in https://github.com/dotnet/core/pull/4343:

https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json `404: Not Found`

I'm not too familiar with these AzDO tasks though, particularly through the UI. Whoever provides this build task needs to fix it. You might be able to find more info through https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#build-environment
