### ISSUE TITLE
this revision of snap "dotnet-sdk" was published using classic confinement and thus may        perform arbitrary system changes outside of the security sandbox that snaps are usually        confined to, which may put your system at risk.

### ISSUE THREAD

**Issue by bacmed** [dotnet/core#4378]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
This is by design. The SDK snap uses classic confinement. To install, use `snap install dotnet-sdk --classic`
