### ISSUE TITLE
Asset file - project.assets.json not found

### ISSUE THREAD

**Issue by chandanch** [dotnet/core#4380]
# Issue Title
Asset file - project.assets.json not found

# General
Following the quick start tutorials from this link: [https://docs.microsoft.com/en-us/dotnet/core/](https://docs.microsoft.com/en-us/dotnet/core/) 

1. Created a new console application: `dotnet new console`
2. Running the application: `dotnet run` resulted in the following error:

_**C:\Program Files\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file 'E:\pros\donet-cli-proj\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [E:\csharp projects\donet-cli-proj\donet-cli-proj.csproj]
The build failed. Fix the build errors and run again.**_

I also tried `dotnet restore` but still showing the above error. 

## dotnet Info:
`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`

**Comment by qaliwebguru** [comment]
Facing the same issue. Tried both dontnet and nuget restore but still same issue.

**Comment by pasca15** [comment]
Same here

**Comment by mairaw** [comment]
Did you just run `dotnet new console` and `dotnet run` and got that error? Can you provide more details of which SDK version you're using, screenshots of the errors, etc.? On command prompt, VS Code?

**Comment by pasca15** [comment]
SDK version: 3.1.302
On VS Code, I received this error message  error NETSDK1004: Assets file '...\obj\project.assets.json' not found. Run a NuGet package restore to generate this file

I have tried dotnet run and dotnet restore, also tried disabling the customised package source, adding the environment variable EnableNuGetPackageRestore as true.

**Comment by mairaw** [comment]
Can you do the same outside of VS Code (like command prompt, powershell) to see if you get the same results? Just trying to pinpoint where the issue is.

**Comment by pasca15** [comment]
I got the same result using the command prompt in VS Code

**Comment by waritthornnudee** [comment]
I also facing the same error when building DockerFile
using this command `dotnet publish -c release -o /app --no-restore`
