### ISSUE TITLE
dotnet core 3.0 restore fails on docker daemon

### ISSUE THREAD

**Issue by dewanymca** [dotnet/core#4387]
I am trying to build a docker image out of dotnet core 3.1 application. When i use to run docker build locally, everything works fine.

However as i am using private nuget feed, i am restoring package in Azure Devops using dotnet restore and in dockerfile providing path to where all package all stored. When i run docker build locally or in azure devops, i am getting unable to find package. Looking at error mostly are system namespace package.

Can you please help. Below is snippet of error message"

[/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.Storage/Azure.Storage.csproj : error NU1101: Unable to find package NETStandard.Library. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.Storage/Azure.Storage.csproj : error NU1101: Unable to find package System.ComponentModel.TypeConverter. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.Storage/Azure.Storage.csproj : error NU1101: Unable to find package System.Runtime.Serialization.Formatters. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.Storage/Azure.Storage.csproj : error NU1101: Unable to find package System.Runtime.Serialization.Primitives. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.Storage/Azure.Storage.csproj : error NU1101: Unable to find package System.Xml.XmlDocument. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.ServiceBus/Azure.ServiceBus.csproj : error NU1101: Unable to find package Microsoft.NETCore.Targets. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.ServiceBus/Azure.ServiceBus.csproj : error NU1101: Unable to find package NETStandard.Library. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.ServiceBus/Azure.ServiceBus.csproj : error NU1101: Unable to find package System.Diagnostics.Process. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.ServiceBus/Azure.ServiceBus.csproj : error NU1101: Unable to find package System.ComponentModel.TypeConverter. No packages exist with this id in source(s): /src/nugets [/src/ProformaInvoiceCore/ProformaInvoiceService/ProformaInvoiceService.csproj]
/src/ProformaInvoiceCore/Azure.ServiceBus/Azure.ServiceBus.csproj : error NU1101: Unable to find package System.Runtime.Serialization.Primitives. No

**Comment by carlossanlop** [comment]
Any chance you can help with this issue, @MichaelSimons ?

**Comment by MichaelSimons** [comment]
@dewanymca, I find it to be generally useful to make your Dockerfiles self-contained as much as possible.  What that means in this situation is that the restore should be performed within the Dockerfile.  Please see the [Managing NuGet Credentials in Docker Scenarios](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md) for guidance on how to do this with private NuGet feeds.

That aside, it is possible to restore locally and copy the packages with a Dockerfile.  From the looks of your errors, it may be a simple path issue.  My recommendation would be to _debug_ your Dockerfile to ensure how you copying the packages is working as expected.
