### ISSUE TITLE
error - create AKS cluster in Azure resource group

### ISSUE THREAD

**Issue by xmg2019** [dotnet/core#4391]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

Hi there, I kept getting the error message "The operation is not permitted for namespace 'Microsoft.ContainerService' when I pass the following code: "az aks create --resource-group myMicroserviceResources --name myMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys" to create AKS cluster in the Azure resource group.

Even after I tried to register Microsoft.ContainerService for preview, i still receive the same error message

![image](https://user-images.githubusercontent.com/55222906/76586420-b6959480-651b-11ea-9366-ef8e7c035b60.png)

![image](https://user-images.githubusercontent.com/55222906/76586230-44bd4b00-651b-11ea-87c6-0a6f1bae4a0d.png)

**Comment by mairaw** [comment]
It might be something specific to the offer you're using @xmg2019 
https://social.msdn.microsoft.com/Forums/en-US/56f860c5-ab0a-4b63-a967-bdcec0a326ed/the-operation-is-not-permitted-for-namespace?forum=ssdsgetstarted

Let us know if this helps.
