### ISSUE TITLE
Single-file executable command line  not recognize by linux-x64 target platform

### ISSUE THREAD

**Issue by Thraka** [dotnet/core#4397]
_From @naughtyGitCat on Saturday, March 14, 2020 4:45:07 AM_

If it was target for windows, I will be better to pointed out that

psyduck@PsyDuck ~/P/S/DBAInternalAPI (master) [1]&gt; dotnet pulish -r linux-64 -p:PublishSingleFile=true
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-pulish does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
psyduck@PsyDuck ~/P/S/DBAInternalAPI (master) [1]&gt; dotnet --version
3.1.102
psyduck@PsyDuck ~/P/S/DBAInternalAPI (master)&gt; dotnet wrap --help
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-wrap does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
psyduck@PsyDuck ~/P/S/DBAInternalAPI (master) [1]&gt; dotnet publish -r win10-x64 -p:PublishSingleFile=true
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/psyduck/Projects/SAL/DBAInternalAPI/DBAInternalAPI.csproj : warning NU1701: Package 'ini-parser 2.5.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  Restore completed in 14.65 sec for /Users/psyduck/Projects/SAL/DBAInternalAPI/DBAInternalAPI.csproj.
/Users/psyduck/Projects/SAL/DBAInternalAPI/DBAInternalAPI.csproj : warning NU1701: Package 'ini-parser 2.5.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Areas/Redis/Services/RedisMetaBaseService.cs(47,31): warning CS1574: XML comment has cref attribute 'FetchRedisMetaBaseInfo(IPagerOrderQueryParameter)' that could not be resolved [/Users/psyduck/Projects/SAL/DBAInternalAPI/DBAInternalAPI.csproj]
  DBAInternalAPI -&gt; /Users/psyduck/Projects/SAL/DBAInternalAPI/bin/Debug/netcoreapp3.1/win10-x64/DBAInternalAPI.dll
  DBAInternalAPI -&gt; /Users/psyduck/Projects/SAL/DBAInternalAPI/bin/Debug/netcoreapp3.1/win10-x64/publish/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#compiledeploy)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

_Copied from original issue: dotnet/docs#17461_

**Comment by Thraka** [comment]
_From @Thraka on Saturday, March 14, 2020 9:21:39 PM_

Hello. If you're having a problem with the command, please file a bug with https://github.com/dotnet/core

I'll move your issue there.

**Comment by omajid** [comment]
> dotnet pulish -r linux-64 -p:PublishSingleFile=true

There's a typo here. It should be `publish` not `pulish`.

**Comment by Thraka** [comment]
@omajid I think there was just a misprint on the customers original issue. You can see further down the issue information a correct command was used ` dotnet publish -r win10-x64 -p:PublishSingleFile=true`

**Comment by naughtyGitCat** [comment]
thanks, it was a typo

**Comment by Thraka** [comment]
Thanks for letting us know.
