### ISSUE TITLE
where is Program.cs

### ISSUE THREAD

**Issue by pandaventurer** [dotnet/core#4399]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

You say "open Program.cs" but i don't know where can i find this file. Can you help me, please?
![Annotation 2020-03-15 082833](https://user-images.githubusercontent.com/36056418/76697399-051b6e00-6697-11ea-80d3-388788eb2a3a.jpg)

**Comment by TehWardy** [comment]
It's in the root folder for all new dotnet projects.
If it doesn't exist then something has gone wrong in the project creation process.

**Comment by pandaventurer** [comment]
Okay. Oui, je l'ai trouvé. Merci.
