### ISSUE TITLE
.NET 5 Preview 1

### ISSUE THREAD

**Issue by leecow** [dotnet/core#4405]
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.1.md)

Please report any issues you find with .NET 5, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by mairaw** [comment]
Closing older announcement issues.
