### ISSUE TITLE
Integration testing does not support graceful shutdown (.net core - any version)

### ISSUE THREAD

**Issue by JeviScript** [dotnet/core#4409]
# Bug or feature request

It seems that, as it stands, there is no way to do a graceful shutdown on (ctrl+c) when running integration tests in .net core (any version). Using IHostApplicationLifetime, `ApplicationStarted` event is triggered, however if you attempt to do (ctrl + c) in the console afterwards, `ApplicationStopping` and `ApplicationStopped` events are ignored. Tests terminate abruptly. I would like to be able to do some clean up work after shutdown.
**Os**: ubuntu 18.04
**.net core**: Version: 3.1.1

**Comment by carlossanlop** [comment]
3.1 is out of support. Do you still see this issue in 6.0 or 7.0?
