### ISSUE TITLE
visual studio preview 3 MacOS error MSB4057: The target "Build" does not exist in the project 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotnet/core#441]
I have created a simple C# .net core console application project in VS MacOS. But I get error MSB4057.  There a similar question on [stackoverflow](http://stackoverflow.com/questions/2035414/target-build-does-not-exist-in-the-project-for-visual-studio) but doesn't explain anything how to fix this kind of error. 

The problem is same when I create asp.net core project. 

```
Build FAILED.

/Users/abhimanyuaryan/Unity3D/LearnCSharp/LearnCSharp/LearnCSharp.csproj : error MSB4057: The target "Build" does not exist in the project.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.02

---------------------- Done ----------------------

Build: 1 error, 0 warnings
```
```

**Comment by PeterAronZentai** [comment]
How did you solve?

**Comment by AbhimanyuAryan** [comment]
You need to download newer version of SDK @PeterAronZentai

Try 1.1 preview 4
