### ISSUE TITLE
Ubuntu 18.04 not able to download dotnet core 3.1 using package manager

### ISSUE THREAD

**Issue by Devarsh14** [dotnet/core#4411]
Hi, I am using below command to install dotnet core on My work VM. 
I have also used Snap command as well. 
Not able to install dotnet core somehow on my system. 
May be related to  #3988.
```
sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libwayland-egl1-mesa
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  aspnetcore-targeting-pack-3.1 dotnet-apphost-pack-3.1 dotnet-targeting-pack-3.1
  netstandard-targeting-pack-2.1
The following NEW packages will be installed:
  aspnetcore-targeting-pack-3.1 dotnet-apphost-pack-3.1 dotnet-sdk-3.1
  dotnet-targeting-pack-3.1 netstandard-targeting-pack-2.1
0 to upgrade, 5 to newly install, 0 to remove and 3 not to upgrade.
Need to get 42.8 MB/47.2 MB of archives.
After this operation, 232 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-sdk-3.1 amd64 3.1.200-1 [42.8 MB]
Err:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-sdk-3.1 amd64 3.1.200-1
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:ff2e4a0dcb84c60326c32a3d8bf211b36fbcd11a7921bc169ed2a5397243efacb7c4b9406bc3628229b3f1801cb29a22b164d214393f12793f4106322b90829d
   - SHA256:3cf2d26dddb9016312982100f89077c5af5853bef3d4fad4ee0ad3de948b06f1
   - SHA1:9bd83c8060a243e68e1bd95d91de8c136a6817fb [weak]
   - MD5Sum:4a9da7b65dca5759aebc9da20e1c87ab [weak]
   - Filesize:42834136 [weak]
  Hashes of received file:
   - SHA512:c93db768b0d8d931bf89ad9091cd01ddeaf5ad6088d76eb4190d3fd596a0a6fd94809b83fca4ad48402c8c92d687addecda42912afefdd749a72fcd8661d3e20
   - SHA256:6d573bcc5710ede8b5d2ccf296c01e53a76b15dd1ebf6d2449d17b221fea8228
   - SHA1:f145756d5439ded8dc4c11c26e71ce4601473ff6 [weak]
   - MD5Sum:c876029402d70b3cc35b3bccae463a81 [weak]
   - Filesize:42834136 [weak]
  Last modification reported: Mon, 16 Mar 2020 18:40:58 +0000
Fetched 42.8 MB in 36s (1,203 kB/s)                                                           
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-sdk-3.1/dotnet-sdk-3.1.200-x64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:ff2e4a0dcb84c60326c32a3d8bf211b36fbcd11a7921bc169ed2a5397243efacb7c4b9406bc3628229b3f1801cb29a22b164d214393f12793f4106322b90829d
    - SHA256:3cf2d26dddb9016312982100f89077c5af5853bef3d4fad4ee0ad3de948b06f1
    - SHA1:9bd83c8060a243e68e1bd95d91de8c136a6817fb [weak]
    - MD5Sum:4a9da7b65dca5759aebc9da20e1c87ab [weak]
    - Filesize:42834136 [weak]
   Hashes of received file:
    - SHA512:c93db768b0d8d931bf89ad9091cd01ddeaf5ad6088d76eb4190d3fd596a0a6fd94809b83fca4ad48402c8c92d687addecda42912afefdd749a72fcd8661d3e20
    - SHA256:6d573bcc5710ede8b5d2ccf296c01e53a76b15dd1ebf6d2449d17b221fea8228
    - SHA1:f145756d5439ded8dc4c11c26e71ce4601473ff6 [weak]
    - MD5Sum:c876029402d70b3cc35b3bccae463a81 [weak]
    - Filesize:42834136 [weak]
   Last modification reported: Mon, 16 Mar 2020 18:40:58 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by NikolaMilosavljevic** [comment]
@Devarsh14 Can you run the following command and share the output - it would tell us which server mirror you are being redirected to?

`wget http://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-sdk-3.1/dotnet-sdk-3.1.200-x64.deb`

**Comment by Devarsh14** [comment]
@NikolaMilosavljevic  : Please kindly check below response to above command. 

wget http://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-sdk-3.1/dotnet-sdk-3.1.200-x64.deb
URL transformed to HTTPS due to an HSTS policy
--2020-03-19 09:15:33--  https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-sdk-3.1/dotnet-sdk-3.1.200-x64.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.76.190.189
Connecting to packages.microsoft.com (packages.microsoft.com)|13.76.190.189|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42834136 (41M) [application/octet-stream]
Saving to: 'dotnet-sdk-3.1.200-x64.deb’

dotnet-sdk-3.1.200-x64. 100%[===============================>]  40.85M  2.78MB/s    in 16s     

2020-03-19 09:15:50 (2.62 MB/s) - 'dotnet-sdk-3.1.200-x64.deb’ saved [42834136/42834136]

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic : Please kindly check below response to above command.
> 

Does the issue still repro? We have checked all package mirrors including 13.76.190.189 and there were no issues today. What is the checksum of the of the file you downloaded, i.e.?

`md5sum dotnet-sdk-3.1.200-x64.deb`

**Comment by Devarsh14** [comment]
@NikolaMilosavljevic  : Please kindly check below response to above command.
md5sum dotnet-sdk-3.1.200-x64.deb
7aece93254dac5bd650e2719ff34cfcd  dotnet-sdk-3.1.200-x64.deb

**Comment by Devarsh14** [comment]
Hi Please check, repro, for installation. 

sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libwayland-egl1-mesa
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  aspnetcore-targeting-pack-3.1 dotnet-apphost-pack-3.1
  dotnet-targeting-pack-3.1 netstandard-targeting-pack-2.1
The following NEW packages will be installed:
  aspnetcore-targeting-pack-3.1 dotnet-apphost-pack-3.1 dotnet-sdk-3.1
  dotnet-targeting-pack-3.1 netstandard-targeting-pack-2.1
0 to upgrade, 5 to newly install, 0 to remove and 4 not to upgrade.
Need to get 42.8 MB/47.2 MB of archives.
After this operation, 232 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-sdk-3.1 amd64 3.1.200-1 [42.8 MB]
Err:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-sdk-3.1 amd64 3.1.200-1
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:ff2e4a0dcb84c60326c32a3d8bf211b36fbcd11a7921bc169ed2a5397243efacb7c4b9406bc3628229b3f1801cb29a22b164d214393f12793f4106322b90829d
   - SHA256:3cf2d26dddb9016312982100f89077c5af5853bef3d4fad4ee0ad3de948b06f1
   - SHA1:9bd83c8060a243e68e1bd95d91de8c136a6817fb [weak]
   - MD5Sum:4a9da7b65dca5759aebc9da20e1c87ab [weak]
   - Filesize:42834136 [weak]
  Hashes of received file:
   - SHA512:69187d2315a4c553acdace1491317dadf963b2f64e44649503cdb502e82ea6cf3f146852d1a56ac8af12beb7e06c2eebb23fd4909ea27a2ab1c7bf5dd0c63dee
   - SHA256:67026aaac6ad215d274290a9a5828e888b29958a698fdea7127cdb1568b42926
   - SHA1:b21208d8d4bdc268f3f78a90bfa71c04da321087 [weak]
   - MD5Sum:e4dd26c8529563ec9bd0fa65386e25fb [weak]
   - Filesize:42834136 [weak]
  Last modification reported: Mon, 16 Mar 2020 18:40:58 +0000
Fetched 42.8 MB in 15s (2,932 kB/s)                                            
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-sdk-3.1/dotnet-sdk-3.1.200-x64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:ff2e4a0dcb84c60326c32a3d8bf211b36fbcd11a7921bc169ed2a5397243efacb7c4b9406bc3628229b3f1801cb29a22b164d214393f12793f4106322b90829d
    - SHA256:3cf2d26dddb9016312982100f89077c5af5853bef3d4fad4ee0ad3de948b06f1
    - SHA1:9bd83c8060a243e68e1bd95d91de8c136a6817fb [weak]
    - MD5Sum:4a9da7b65dca5759aebc9da20e1c87ab [weak]
    - Filesize:42834136 [weak]
   Hashes of received file:
    - SHA512:69187d2315a4c553acdace1491317dadf963b2f64e44649503cdb502e82ea6cf3f146852d1a56ac8af12beb7e06c2eebb23fd4909ea27a2ab1c7bf5dd0c63dee
    - SHA256:67026aaac6ad215d274290a9a5828e888b29958a698fdea7127cdb1568b42926
    - SHA1:b21208d8d4bdc268f3f78a90bfa71c04da321087 [weak]
    - MD5Sum:e4dd26c8529563ec9bd0fa65386e25fb [weak]
    - Filesize:42834136 [weak]
   Last modification reported: Mon, 16 Mar 2020 18:40:58 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by NikolaMilosavljevic** [comment]
@Devarsh14, it is puzzling that you got a completely different checksum of a file downloaded with wget. Would it be possible to share that file on OneDrive or Google Drive?

Are you using any proxies or corporate internal mirrors or caches? The following page has some recovery steps for users hitting issues related to stale caches, it might be helpful: https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error

**Comment by NikolaMilosavljevic** [comment]
Closing this issue as it cannot be reproduced anymore. @Devarsh14 if you hit this issue again, please reactivate the GitHub issue.
