### ISSUE TITLE
i Cannot  Open It on visual 2017

### ISSUE THREAD

**Issue by MostafaQC** [dotnet/core#4414]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
