### ISSUE TITLE
Is that any way to fix Couldn't find a valid ICU package installed on the system error

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/core#4415]
I run the project in Centos 7 on **ARM**,,I use the Huawei Kunpeng cloud server

I exe dotnet --info,return like this:

![image](https://user-images.githubusercontent.com/18448413/77039335-aa647800-69f0-11ea-816d-635b5d191c6c.png)

it seem like the core framework is install success,and I install the libicu ,and exe icuinfo return like this:

![image](https://user-images.githubusercontent.com/18448413/77039615-4d1cf680-69f1-11ea-900b-3ffedab80da8.png)

but when I run the project it throw the error like this:

![image](https://user-images.githubusercontent.com/18448413/77039725-80f81c00-69f1-11ea-9130-a6844c691154.png)

Is that any way to fix this error?I need the Multiple Language

**Comment by omajid** [comment]
Did some very quick testing.... this is caused by `sudo`, right? This error doesn't happen if you just run `/opt/dotnetrun3.0/dotnet /usr/website/api/.....dll`

**Comment by kugarliyifan** [comment]
I found some way to fix it!!!!

**Comment by kugarliyifan** [comment]
https://bbs.huaweicloud.com/forum/thread-46787-1-1.html   use this article,,and the step1 is very important ,,and don't use "yum install libicu" to  install the icu lib,,,because on yum libicu is the version 50,,,,
