### ISSUE TITLE
i have issues running dotnet after a successful installation

### ISSUE THREAD

**Issue by belrah** [dotnet/core#4416]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by belrah** [comment]
OP system is 64-bit, RAM is 4gb, processor is AMD E2-900e RADEON R2, core 2c+2g. 1.50God. The error massage says: 'the program cant start because april-ms-win-crt-runtime-[1-1-0.d] is missing from your computer. Try reinstalling the program to fix this problem.' Even after reinstalling i still end up with the same massage

**Comment by mairaw** [comment]
Can you paste a screenshot of the steps you have done in the console window?

**Comment by carlossanlop** [comment]
Related: https://github.com/dotnet/core/issues/4541

**Comment by mairaw** [comment]
Closing due to the lack of response.
