### ISSUE TITLE
new using scope does not dispose the object

### ISSUE THREAD

**Issue by LiorBanai** [dotnet/core#4417]
The following unit test fails to call the Dispose method:
```csharp
 using H5ReadOnlyFile readFile = new H5ReadOnlyFile(filename);
readFile.ReadPatientInformation();
Assert.IsTrue(readFile.PatientInformation.Equals(kama.PatientInfo));

File.Delete(filename);

``` 

while the below code does:
```csharp
using (H5OnlyFile readFile = new H5ReadOnlyFile(filename))
{
    readFile.ReadPatientInformation();
    Assert.IsTrue(readFile.PatientInformation.Equals(kama.PatientInfo));
}

File.Delete(filename);
``` 

the dispose closes the underline handle to the file:
```csharp
        public void Dispose()
        {
            PatientInformation?.Dispose();
            if (!fileClosed)
            {
                Hdf5.CloseFile(fileId);
                fileClosed = true;
            }
        }
``` 

Am  I doing something wrong here? I was under the assumption that once the file is not used  it will disposed the same when exiting the {}

repo to show the issue:
https://github.com/LiorBanai/UsingStatementDisposing

**Comment by GrabYourPitchforks** [comment]
What do you mean _fails to call the Dispose method_? Are you absolutely sure the Dispose method isn't being called - can you put `Console.WriteLine` statements through the code or step through a debugger to confirm this?

Keep in mind also that the code you've written:

```cs
using H5ReadOnlyFile readFile = new H5ReadOnlyFile(filename);
readFile.ReadPatientInformation();
Assert.IsTrue(readFile.PatientInformation.Equals(kama.PatientInfo));
File.Delete(filename);
```

Is equivalent to this C# code:

```cs
using (H5OnlyFile readFile = new H5ReadOnlyFile(filename))
{
    readFile.ReadPatientInformation();
    Assert.IsTrue(readFile.PatientInformation.Equals(kama.PatientInfo));
    File.Delete(filename); // <-- this line is now INSIDE the using statement
}
```

**Comment by LiorBanai** [comment]
> 
> 
> What do you mean _fails to call the Dispose method_? Are you absolutely sure the Dispose method isn't being called - can you put `Console.WriteLine` statements through the code or step through a debugger to confirm this?
> 
> Keep in mind also that the code you've written:
> 
> ```cs
> using H5ReadOnlyFile readFile = new H5ReadOnlyFile(filename);
> readFile.ReadPatientInformation();
> Assert.IsTrue(readFile.PatientInformation.Equals(kama.PatientInfo));
> File.Delete(filename);
> ```
> 
> Is equivalent to this C# code:
> 
> ```cs
> using (H5OnlyFile readFile = new H5ReadOnlyFile(filename))
> {
>     readFile.ReadPatientInformation();
>     Assert.IsTrue(readFile.PatientInformation.Equals(kama.PatientInfo));
>     File.Delete(filename); // <-- this line is now INSIDE the using statement
> }
> ```

if the File.Delete is inside the scope than this explain the behavior since the Dispose was not called yet.
But I assumed (wrong apparently)  that the scope of the using is the **last reference** to the member of the using and not the entire scope of the method.

**Comment by GrabYourPitchforks** [comment]
The proposal at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using explains the scoping rules a little better IMO. The way that I think of it is that the compiler keeps track of the current `{` nesting level. When a matching `}` is seen to terminate the current nesting level, the object is also disposed at the same time. In your case, the opening `{` would be the method body itself, so the matching terminating `}` would be when the method body ends.
