### ISSUE TITLE
When building a .NET Core 3.1 project that references a .NET Standard 2.1 project, I get Error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized (NETSDK1073) 

### ISSUE THREAD

**Issue by lewisgauss** [dotnet/core#4419]
`/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized (NETSDK1073) `

I am building the solution on a Mac machine, so my question is why is Microsoft.WindowsDesktop.App even in my project's framework reference? When I expand the framework list on my project, I don't even see Microsoft.WindowsDesktop.App on the list. 

![image](https://user-images.githubusercontent.com/8966669/77081302-621b7900-6a35-11ea-8919-a0021eea8ecf.png)

However, when I use JetBrains Rider, I can see it, but with an error. 

![image](https://user-images.githubusercontent.com/8966669/77081403-92631780-6a35-11ea-8323-595cef151e87.png)

**Comment by lewisgauss** [comment]
Any update or tip from someone?

**Comment by jadenrogers** [comment]
Same here , did you solve this? @lewisgauss

**Comment by lewisgauss** [comment]
@jadenrogers it stopped becoming a problem for me, after updating to a new .NET Core version some time ago. So I can't help you much here...

**Comment by hillin** [comment]
I had the same problem when building in azure pipeline (building locally on my Windows box had no problem). Changing the vm image to windows from ubuntu solved the problem. I guess the Windows related frameworks are simply not available on non-Windows systems.
