### ISSUE TITLE
automatically reflect changes without restarting server

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotnet/core#442]
Hi when ever make any changes in my application. I  have to restart server with `dotnet run` to reflect changes in Web app. 

I am using dotnet version 1.0.0-rc4-004597 with VS code. Is this an issue with me or everybody here?

**Comment by Petermarcu** [comment]
@DamianEdwards , is there where `dotnet watch` comes in?

**Comment by AbhimanyuAryan** [comment]
`dotnet watch` & `dotnet watch run`  command says: No executable found matching command "dot-watch"

**Comment by Jagadeesh-Govindaraj** [comment]
possible duplicate [aspnet/DotNetTools](https://github.com/aspnet/DotNetTools/issues/147)

**Comment by Petermarcu** [comment]
Looks like a good linked issue to track this. `dotnet watch` from aspnet is the solution to this.
