### ISSUE TITLE
No package dotnet-sdk-3.1 available.

### ISSUE THREAD

**Issue by brsoft001** [dotnet/core#4422]
```
[root@ecs ~]# sudo yum install dotnet-sdk-3.1
Loaded plugins: fastestmirror
Repository packages-microsoft-com-prod is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.cn99.com
 * remi-safe: mirror.innosol.asia
 * updates: mirrors.cn99.com
No package dotnet-sdk-3.1 available.
Error: Nothing to do
```

**Comment by igoventura** [comment]
Try following this tutorial: [https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-centos7](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-centos7)

I think you don't have the Microsoft Key and the feed configured on your machine. If so, try running the following commands:

```bash
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

sudo yum install dotnet-sdk-3.1
```

**Comment by meriturva** [comment]
Actually seems that version 3.1.201 is not present, only version 3.1.103.
am i correct?

**Comment by mairaw** [comment]
Tagging @dagood @leecow

**Comment by dagood** [comment]
@brsoft001 what instructions did you follow to get to this point? What are the console logs for previous commands? It appears you don't have the package repository set up.

Instructions are here: https://docs.microsoft.com/en-us/dotnet/core/install/linux (slightly more general link than above, for various Linux distros)

(I edited the original post to remove the new-issue template and format the console log.)
