### ISSUE TITLE
Different behavior from calling .NET Core COM Server and .NET 4.6.1 COM Server

### ISSUE THREAD

**Issue by pcuong** [dotnet/core#4424]
# Issue Title

Got "Unknown error 0x80131515" after the first successfully call .NET Core COM Server.

# General

In the attached solution (
[DotNetCore (2).zip](https://github.com/dotnet/core/files/4358972/DotNetCore.2.zip)
). I have 2 COM Servers

- WindowsFormsApp1 (.NET Core 3.1)
- WindowsFormsControlLibrary1 (.NET 4.6.1)

and 2 client projects.

- Project1 will consume .NET Core COM Server
- Project2 will consume .NET 4.6.1 COM Server

**Steps to reproduce.**
1. Extract and rebuild the attached solution
2. Run "Project1" and hit "Show" button few times. After the first hit, the "Unknown error 0x... " is continuously shown --> **not expected.**
![image](https://user-images.githubusercontent.com/606823/77154929-4664b100-6acf-11ea-8e8b-7a0dfa1ff04c.png)

3. Run "Project2" and hit "Show" button few times. The hello message is continuously shown --> **expected**.
![image](https://user-images.githubusercontent.com/606823/77154476-59c34c80-6ace-11ea-9c34-9175869eeceb.png)

Same codes are used to consume the COM Servers as below
`
::CoInitialize(nullptr);
            {
                try
                {
                    CComPtr<ITestMgr> apTestMgr;

                    // .NET 4.6.1
                    //HRESULT hr = apTestMgr.CoCreateInstance(L"WindowsFormsControlLibrary1.TestMgr.1", nullptr, CLSCTX_INPROC);

                    // .NET Core
                    HRESULT hr = apTestMgr.CoCreateInstance(L"WindowsFormsApp1.TestMgr.1", nullptr, CLSCTX_INPROC);
                    if (FAILED(hr))
                        _com_issue_error(hr);

                    CComBSTR bstrMessage(L"Hello");
                    hr = apTestMgr->Show(bstrMessage);
                    if (FAILED(hr))
                        _com_issue_error(hr);
                }
                catch (const _com_error& e)
                {
                    ::MessageBox(hDlg, e.ErrorMessage(), L"NET Core!", MB_OK | MB_ICONERROR);

                    _bstr_t bstrDescription = e.Description();
                    if(bstrDescription.length())
                        ::MessageBox(hDlg, (LPCTSTR)bstrDescription, L"NET Core!", MB_OK | MB_ICONERROR);
                }
                
            }
            ::CoUninitialize();
`

**Comment by carlossanlop** [comment]
@pcuong did you get a chance to solve your problem? Apologies for the delayed response.

cc @AaronRobinsonMSFT since this is COM related.

**Comment by pcuong** [comment]
@carlossanlop thanks for response.
I've ran the test against .NET Core 3.1 and .NET 6.0, the issue "Unknown error 0x... " did not appear.
The behavior is now same for both .NET Core 3.1, .NET 6.0 and .NET Framework 4.6.1

My system is now using .NET Core 3.1.32, I'm pretty sure that it is different to .NET Core 3.1 version on my old system which raised the issue.

**Comment by mairaw** [comment]
I'm glad it's working now. Closing the issue then.
