### ISSUE TITLE
Mapping between Core versions in runtime and actual values

### ISSUE THREAD

**Issue by DmitryLukyanov** [dotnet/core#4425]
I want to determine which versions of .net are used by our users.
For that target we use this code:

    RuntimeInformation.FrameworkDescription;

But it doesn't return actual .Net versions for Core versions less than 3.0, for example, for the application which is built with:

   *  `.NET Core 1.0`, it returns `.NET Core 4.0.0.0`
   *  `.NET Core 2.0`, it returns `.NET Core 4.6.27817.01`
   *  `.NET Core 2.1`, it returns `.NET Core 4.6.27817.01`
   *  `.NET Core 2.2`, it returns `.NET Core 4.6.27817.03`
   *  `.NET Core 3.0`, it returns `.NET Core 3.0.0-preview8-28405-07` 

Is there a way to map the `4.X.X` values(for core versions less than 3.0) with the real framework versions?

**Comment by DmitryLukyanov** [comment]
Can someone take a look at this issue?

**Comment by carlossanlop** [comment]
Apologies for the delayed answer. I found some answers in StackOverflow: https://stackoverflow.com/questions/49309108/programmatically-get-current-running-version-of-dotnet-core-runtime
You might have already solved your issue so I'll close this.
