### ISSUE TITLE
Not able to create docker image

### ISSUE THREAD

**Issue by abhaydesai76** [dotnet/core#4429]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Hi, got below error message while executing command "docker build -t mymicroservice .".

"error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=fcbjj7pxu7x56kexdqw1tgrvz&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running."

Also, On verifying "Task Manager" / "Performance" tab, "Virtualization" is showing ""Not Capable". Not sure, whether my machine permits to run docker !!!

**Comment by mairaw** [comment]
@shirhatti can you help with this one?

**Comment by shirhatti** [comment]
As I best understand from your error message, it looks like you're encountering this-https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message

If you don't have success with this, I'd recommend asking in the Docker for Windows forum where you'd probably have better luck- https://forums.docker.com/c/docker-desktop-for-windows
