### ISSUE TITLE
.NET Core and portable libraries / Xamarin

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/core#443]
Hi,

I'm pretty new to the world of cross-platform, and I believe Xamarin is the right choice.
Anyway, I AM familiar with .NET core, but I'd like to know how Xamarin and portable class libraries work. Do they target .NET core?
I mean, how many .NETs are there, is it just .NET standard and .NET Core, or there is also a special .NET for mono that has nothing to do with the above?
Why can't I target a .NET Core library/package from my Xamarin portable app?

**Comment by Petermarcu** [comment]
There are a few .NET Platforms out there. Portable Class Libraries has been the way to target multiple and that is evolving into .NET Standard Libraries. .NET Core is a concrete platform as is Xamarin. Sharing between them is done via .NET Standard Libraries or Portable Class Libraries. Create one of those and you should be able to reference it from your Xamarin Application.

**Comment by weitzhandler** [comment]
Where can I find a legend or so that describe all the .NETs and the compatibility between them, or maybe you can make up a quick one please?

* .NET Core
* .NET Standard
* Xamarin .NET (Mono?)
* Portable .NET

**Comment by manigandham** [comment]
@weitzhandler 

The official documentation has the info you need: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by weitzhandler** [comment]
@manigandham thanks a lot!
