### ISSUE TITLE
comand

### ISSUE THREAD

**Issue by ravi8412** [dotnet/core#4430]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
