### ISSUE TITLE
.net not recognized 

### ISSUE THREAD

**Issue by kushalsharma1818** [dotnet/core#4431]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Closing out due to lack of response; please feel free to re-open if you're able to provide more info.
