### ISSUE TITLE
when I command dotnet, cmd says dotnet is not recognised as an internal or external command.

### ISSUE THREAD

**Issue by IgRxFireStorm** [dotnet/core#4434]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Try installing the dotnet core SDK. You can find it at [https://dotnet.microsoft.com/download/dotnet-core/3.1](https://dotnet.microsoft.com/download/dotnet-core/3.1)

**Comment by mairaw** [comment]
The tutorial also says:
"If you receive a 'dotnet' is not recognized as an internal or external command error, make sure you opened a new command prompt. If you can't resolve the issue, use the I ran into an issue button to get help fixing the problem."

have you tried that @IgRxFireStorm?

**Comment by carlossanlop** [comment]
The description above is most likely the reason for this error. Closing. Please reopen if you have additional questions.
