### ISSUE TITLE
Could not copy ..\<ProjectName>\obj\Debug\netcoreapp3.1\<ProjectName>.exe to bin\Debug\netcoreapp3.1\<ProjectName>.exe

### ISSUE THREAD

**Issue by whiplash35** [dotnet/core#4435]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: Microsoft Windows 10 Pro, Version - 10.0.17763
Visual Studio - 2019
Visual Studio 2017 is also installed on this machine

ERROR: Could not copy ..\<ProjectName>\obj\Debug\netcoreapp3.1\<ProjectName>.exe to bin\Debug\netcoreapp3.1\<ProjectName>.exe

I've right-clicked and removed 'Read Only' from netcoreapp3.1 folder in bin\Debug but the above Error still happens.

Any ideas?

Thanks

**Comment by mairaw** [comment]
You don't need to mess with those folders. Did you find the Index.cshtml file to modify and run `dotnet run` again?

**Comment by mairaw** [comment]
Closing due to the lack of feedback.
