### ISSUE TITLE
olá, gostaria de saber se tem como explicar cada linha do arquivo dockerfile

### ISSUE THREAD

**Issue by joaopaulot** [dotnet/core#4445]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
@joaopaulot você pode consultar a documentação do docker em [https://docs.docker.com/](https://docs.docker.com/). 

De qualquer forma segue abaixo um gist detalhando o arquivo do tutorial informado.

[https://gist.github.com/igoventura/5dc1bde9849a7c1c6a3da89eb6b4b48f](https://gist.github.com/igoventura/5dc1bde9849a7c1c6a3da89eb6b4b48f)

**Comment by mairaw** [comment]
Olá @joaopaulot! Como o @igoventura falou, o melhor seria consultar a documentação do Docker para entender o formato e a sintaxe usada (https://docs.docker.com/engine/reference/builder/). E obrigada @igoventura por fornecer um tutorial detalhado no seu gist.

Como não acho que os tutoriais deveriam explicar cada linha passo a passo, eu vou fechar esse issue.
