### ISSUE TITLE
Issue System.Lazy.cs file

### ISSUE THREAD

**Issue by menua-web** [dotnet/core#4448]
For SDK 3.0 and 3.1 class System.Lazy.cs has issue in using region. It implements using statement "using System.Runtime.CompilerServices;" 34 times. Please fix this issue for incoming version. Thanks for attention.

**Comment by bartonjs** [comment]
Where are you getting that file from?  https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Lazy.cs certainly only has it once.

**Comment by scalablecory** [comment]
Closing out due to lack of response; please feel free to re-open if you're able to provide more info.
