### ISSUE TITLE
in VSCode i face this error The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the  spelling of the name, or if a path was included, verify that the path is correct and try again

### ISSUE THREAD

**Issue by uuc110** [dotnet/core#4449]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Try installing the dotnet core SDK. You can find it on [https://dotnet.microsoft.com/download/dotnet-core/3.1](https://dotnet.microsoft.com/download/dotnet-core/3.1)

**Comment by mairaw** [comment]
Did you install the SDK @uuc110? If so, have you tried closing and reopening the terminal window?

**Comment by mairaw** [comment]
Closing due to the lack of response.

**Comment by idanmoalem** [comment]
still dosent work @mairaw
