### ISSUE TITLE
No .Net Core SDKs were detected

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [dotnet/core#4452]
I was trying to run my .Net Core project using 'dotnet run'; I got an error in cmd.exe that it couldn't find targeted SDK version, so I googled and I found a workaround suggested to uninstall previous versions of .Net Core SDKs and just keep the latest one. I did so but when I tried to create a new .Net Core project I got this warning 'No .Net Core SDKs were detected' as shown below. Currently I have .Net Core SDK version '3.1.102'. What should I do?

![Capture](https://user-images.githubusercontent.com/22199398/77475354-607cf700-6e21-11ea-937a-9a26beea624d.PNG)

**Comment by igoventura** [comment]
What is you VS version? To work with dotnet 3.1+ you need VS 16.5+.

**Comment by mahmoudahmedarafa** [comment]
I have VS' 17.

**Comment by memark** [comment]
@mahmoudahmedarafa If you have Visual Studio 2017, then it's too old. You need Visual Studio 2019 version 16.5 or higher.

**Comment by mahmoudahmedarafa** [comment]
@igoventura What should I do?

**Comment by igoventura** [comment]
You need to install VS 2019. You can download it by the link below. After the installation try using dotnet core 3.1 again.

VS 2019 download link:
[Download Visual Studio 2019](https://visualstudio.microsoft.com/pt-br/)

**Comment by mahmoudahmedarafa** [comment]
@igoventura You said above that I need VS' 16.5+, Isn't VS' 17 sufficient?

May I use lower SDK version with VS' 17?

**Comment by igoventura** [comment]
@mahmoudahmedarafa you need Visual Studio 2019, version 16.5 or higher. You're using Visual Studio 2017 and dotnet core 2+ and 3+ doesn't have support for Visual Studio 2017.

**Comment by mahmoudahmedarafa** [comment]
Thank you all. I am going to close the issue for now.

**Comment by memark** [comment]
@mahmoudahmedarafa Just to be clear, the version numbers work this way:

Visual Studio 2017 => version 15.x
Visual Studio 2019 => version 16.x

It can easily be confusing.
