### ISSUE TITLE
.NET Core March 2020 Updates – 2.1.17 and 3.1.3

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#4453]
[3.1.3 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.3/3.1.3.md)
[3.1.3 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.17 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.17/2.1.17.md)
[2.1.17 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-march-2020/)

Please report any issues you find with 2.1.17 or 3.1.3, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Status of availability of SDK on Linux feeds: 

| Distro | 3.1.3| 2.1.17 
|--|--|--|
| Ubuntu 16.04  |  ✅ | ✅  |
| Ubuntu 18.04  | ✅ |✅ |
| Ubuntu 19.10  |  ✅ | ✅ |
| Centos 7      | ✅| ✅ |
| Debian 9      |  ✅| ✅ |
| Debian 10     | ✅ |✅ |
| Fedora 30     | ✅ |✅ |
| Fedora 31     | ✅ |✅ |
| OpenSUSE 15   | ✅ | ✅ |
| SLES 12        | ✅  | ✅ |
| SLES15        | ✅  | ✅ |

-----
Here is a list of issues that we are tracking and working to resolve with the Feb 2020 release. We'll tick them off as each is resolved. See any linked issue for progress or resolution details.

- [x]  Incorrect macOS Notarization Issues link in 3.1.3 release page.

**Comment by cgountanis** [comment]
This included?

https://github.com/dotnet/efcore/issues/1833#issuecomment-603543685

**Comment by rbhanda** [comment]
> This included?
> 
> [dotnet/efcore#1833 (comment)](https://github.com/dotnet/efcore/issues/1833#issuecomment-603543685)

https://github.com/dotnet/efcore/pull/20279 was submitted recently. This did not make it to the current release.

**Comment by fwd079** [comment]
Chocolatey fails for 3.1.3, need to worry or not?

```bash
You have dotnetcore v3.1.2 installed. Version 3.1.3 is available based on your source(s).
dotnetcore not upgraded. An error occurred during installation:
 The remote server returned an error: (403) Forbidden. Forbidden
dotnetcore package files upgrade completed. Performing other installation steps.
The upgrade of dotnetcore was NOT successful.
dotnetcore not upgraded. An error occurred during installation:
 The remote server returned an error: (403) Forbidden. Forbidden
```

Regards.

**Comment by mletterle** [comment]
The 3.1.3 Release Notes links to an internal page for instead of https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues

**Comment by leecow** [comment]
Thanks @mletterle - link fixed.

**Comment by leecow** [comment]
@fwd079 - the Chocolatey packages are community maintained and not "official". We'll check a few things on this side to make sure nothing is obviously out of sorts. After that, it will be up to the maintainers.

**Comment by riezebosch** [comment]
something went wrong on publishing the package, it seems available but you cannot download it: https://packages.chocolatey.org/dotnetcore-runtime.install.3.1.3.nupkg

**Comment by leecow** [comment]
Just successfully installed 3.1.3 and SDK 3.1.201 via Chocolatey. Looks like that did it. Thanks @riezebosch!

/cc @rbhanda

**Comment by fwd079** [comment]
> @fwd079 - the Chocolatey packages are community maintained and not "official". We'll check a few things on this side to make sure nothing is obviously out of sorts. After that, it will be up to the maintainers.
> 
> Update: If I run `choco search dotnetcore`, 3.1.2 is reported even though https://chocolatey.org/packages/dotnetcore indicates 3.1.3.
> 
> @riezebosch - any thoughts?

So it **was** on this side, well I am glad then, since that made sorting out a swift thing,  checked this morning and working as expected and installed.

Thanks @riezebosch for looking into it.

Regards.

**Comment by 3dbrows** [comment]
The following relates to 3.1.3.

When restoring an fsproj project with SDK version 3.1.201, I am seeing this:

```
 /root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly. [foo.fsproj]
 /root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Git.TaskImplementation' threw an exception. [foo.fsproj]
 /root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error MSB4018:  ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Tasks.Git, Version=1.0.0.27001, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [foo.fsproj]
```

**If I use 3.1.103, it works fine.** Only 3.1.201 has the problem.

Command used was `dotnet test -c Release foo.fsproj`.

Is there any more information I can provide? Should I file an issue on this somewhere?

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.103
 Commit:    6f74c4a1dd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.103\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.103 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by irac-ding** [comment]
[Memory Leak]
System: CentOS 7.2
SDK: 3.1.201

ex:
class Program
{
static void Main(string[] args)
{
Console.WriteLine("Press any key to continue");
Console.ReadLine();
while (1 == 1)
{
List stdout = RunTaskAndReturnStdout("dotnet", $"--version");
}
}
}

public static List RunTaskAndReturnStdout(string fileName, string arguments, string workingDirectory = "")
{
List ret = new List();
try
{
using (Process proc = new Process())
{
proc.StartInfo.FileName = fileName;
proc.StartInfo.Arguments = arguments;
proc.StartInfo.UseShellExecute = false;
if (!string.IsNullOrWhiteSpace(workingDirectory))
proc.StartInfo.WorkingDirectory = workingDirectory;
proc.StartInfo.RedirectStandardOutput = true;
proc.Start();
while (!proc.StandardOutput.EndOfStream)
{
string line = proc.StandardOutput.ReadLine();
// Console.WriteLine(logstr);
if (!string.IsNullOrWhiteSpace(line))
ret.Add(line);
}
return ret;
}
}
catch (Exception ex)
{
return ret;
}
}

**Comment by rbhanda** [comment]
Closed in favor of https://github.com/dotnet/core/issues/4675
