### ISSUE TITLE
Unable to find entry point _configure_wide_argv in dotnet.exe

### ISSUE THREAD

**Issue by jvcmarcenes** [dotnet/core#4455]
After running the dotnet-sdk-3.1.201-win-x64.exe to install the .NET core into my machine, I tried executing 'dotnet' from the command prompt, upon which it returns an error of being unable to find the enrty poiny _configure_wide_argv in the dotnet.exe.

OS: Windows 8.1 x64

**Comment by igoventura** [comment]
Can you share the full call stack or the log with the error?

**Comment by carlossanlop** [comment]
No response. Closing.
