### ISSUE TITLE
The Ubuntu 19.04 Package Repository Is Not Being Updated

### ISSUE THREAD

**Issue by pnquest** [dotnet/core#4461]
# General

Not sure if this is the correct place to file this, but the deb packages for Ubuntu 19.04 (https://packages.microsoft.com/ubuntu/19.04/prod) are not being updated for `dotnet-sdk-3.1`, `dotnet-runtime-3.1`, and `aspnetcore-runtime-3.1`. The latest version for these packages seems to be from the `3.1.1` release from January. 

The 16.04 repo seems to be updated, any reason these are not being kept up-to-date?

**Comment by pnquest** [comment]
Just a note, this seems to also seems to be the case for the more recent 2.1.x releases

**Comment by SusLes** [comment]
@leecow

**Comment by leecow** [comment]
19.04 reached end of life Jan 2020 so we will no longer be providing updates for that version.
