### ISSUE TITLE
Are there plans to port the 2.2 version of the Healthcheck library to 2.1?

### ISSUE THREAD

**Issue by killyosaur** [dotnet/core#4464]
Considering support for .net core 2.2 ended last year, and while I understand new features are not really being added to the LTS version of .net core 2.1, it seems that unless I want to spend a whole lot of time getting my app to work in 3.1, I can never use the LTS version of .net until I do so if I want to use the Health Checks. So I was wondering if there were plans to make it work with the LTS version of .net core 2.x.

**Comment by igoventura** [comment]
The current LTS version of dotnet core is v3.1. v2.x are no longer supported. Porting your application to v3.1 is not so hard and warnings are showed on the console when you build the ported application, helping to know where to change the code.

**Comment by carlossanlop** [comment]
Closing since 2.x is out of support. Please upgrade to a newer version and if you encounter similar issues, please let us know.
