### ISSUE TITLE
.net core 3.1.200 `GLIBC_2.14' not found on Linux

### ISSUE THREAD

**Issue by cyboashu** [dotnet/core#4467]
# .net core 3.1.200 `GLIBC_2.14' not found on Linux

On windows 10, I created a .netCore (3.1.200) console application called helloWorld. Published it using the command:

`dotnet publish -r linux-x64 --self-contained true`
Copied over the publish folder to my linux machine (RHELS 6.10). Applied the executable permission chmod +x helloWorld

When I run the command, helloWorld, I am getting this error:

 

> helloWorld: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by helloWorld)

How can I resolve that?

**Comment by omajid** [comment]
Try:

    dotnet publish -r rhel.6-x64 --self-contained true

That should work on a RHEL 6 box. The ABI required by `linux-x64` isnt available on RHEL 6.

**Comment by omajid** [comment]
Also take a look at https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md for additional dependencies that might be needed on RHEL 6.

**Comment by cyboashu** [comment]
@omajid  That worked. thanks!
