### ISSUE TITLE
[สุริยาสั่งสอน]{√}ID3670400586184/06403864980gool@gmail.com

### ISSUE THREAD

**Issue by MrSuriyaSangson** [dotnet/core#4475]
#Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
No description of the issue. Closing.
