### ISSUE TITLE
Not able to create docker image

### ISSUE THREAD

**Issue by swapRepository** [dotnet/core#4479]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

after running the docker build command i ran into below issue:

Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
3.1: Pulling from dotnet/core/sdk
8e709836e4dc: Pull complete
46f7982b387f: Pull complete
af4b85272e91: Pull complete
9c1797fd1657: Pull complete
ebbb384999c4: Pull complete
675ff03c006c: Pull complete
6143bd2f3786: Pull complete
6f4ba9c241e1: Pull complete
Digest: sha256:a036559517e0bdf9f724111274ee3c6222418eae33a0b74d2f0ee4b8421e0dc2
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1
 ---> c67fa4d2a089
Step 2/10 : WORKDIR /src
 ---> Running in e735813a9277
Error removing intermediate container e735813a9277: container e735813a9277fc9b2a4d1ce73fa312600a07cd97b5316b6076c2b1d850dd0dc1: driver "windowsfilter" failed to remove root filesystem: failed to detach VHD: The device is not ready.: rename C:\ProgramData\Docker\windowsfilter\e735813a9277fc9b2a4d1ce73fa312600a07cd97b5316b6076c2b1d850dd0dc1 C:\ProgramData\Docker\windowsfilter\e735813a9277fc9b2a4d1ce73fa312600a07cd97b5316b6076c2b1d850dd0dc1-removing: Access is denied.
 ---> 90be6ba41acd
Step 3/10 : COPY myMicroservice.csproj .
Removing intermediate container e735813a9277
 ---> 63fdb518dfb4
Step 4/10 : RUN dotnet restore
 ---> Running in a8d3e4907643
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\src\myMicroservice.csproj]
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error :   No such host is known. [C:\src\myMicroservice.csproj]
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1

**Comment by carlossanlop** [comment]
@shirhatti

**Comment by AlenPelin** [comment]
Same issue with different windows container

**Comment by carlossanlop** [comment]
ping @shirhatti , can you help with this?

**Comment by AlenPelin** [comment]
In my case rebooting machine, manually removing all containers and rebooting again  helped to resolve the issue

**Comment by sughosneo** [comment]
Hello All,

The steps in the tutorial have been updated to use .NET 5. Could you please try executing again and see if the error still exists? Closing the issue due to inactivity. Feel free to open them again if the issue persists.

Thank you.
