### ISSUE TITLE
 linux dotnet 3.1.201 publish  OutputType WinExe still show console

### ISSUE THREAD

**Issue by shynome** [dotnet/core#4482]
### Envirmoent

- os: debian stable 10 kde 
- dotnet: 3.1.201

### Steps to reproduce
- install template https://github.com/AvaloniaUI/avalonia-dotnet-templates
- `dotnet new avalonia.mvvm -o MyApp && cd MyApp `
- `dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true`
- copy `bin/Release/netcoreapp3.0/win-x64/publish/MyApp.exe` to windows
- click MyApp.exe to run

### Expect

no Console just avalonia ui

### Actual

Console show first, then show avalonia UI

### More info

I have do the same step on window, the output exe run as expect no Console show

**Comment by carlossanlop** [comment]
@shynome AvaloniaUI is an external framework, so any questions about it should be directed to their repo.
