### ISSUE TITLE
Cannot "Save" .txt file as a ".html" file

### ISSUE THREAD

**Issue by JayMD5981** [dotnet/core#4483]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Cannot "Save" .txt file as a ".html" file. The instruction is to open Index.cshtml using any text editor, change the code and save the file. I can only save the file as a text file and not as a .html file.
[Index.cshtml.txt](https://github.com/dotnet/core/files/4401402/Index.cshtml.txt)

**Comment by scalablecory** [comment]
This seems like it's related to your browser or editor, not to .NET Core. Can you describe the steps you're taking to see that message?

**Comment by samigroup** [comment]
can you use "Index.cshtml" with quotes, or rename it to remove the .txt portions?

**Comment by mairaw** [comment]
After you run the commands to create the project, you should have a file named Index.cshtml on your project. You should replace its contents with the code we show on the tutorial. Is that what you have done @JayMD5981?

**Comment by carlossanlop** [comment]
@JayMD5981 I suspect you're using Notepad. So try saving the file enclosing the name with double quotes:

"file.html"

That way the extension will be respected, instead of adding the default extension "txt".

Since there was no response in 7 days, I'm closing this.

**Comment by JayMD5981** [comment]
Hello Mr. Lopez

 

Thank you, you can close off.

 

Thank you.

Enjoy your day.

Jay Moodley.

 

Cell:  083 277 1289
