### ISSUE TITLE
Core signing of .net core app giving error on MAC with produce single file enabled

### ISSUE THREAD

**Issue by jacobkochekkan** [dotnet/core#4486]
I created a sample.net core app that I would like to get notarized on MAC. A pre-requsite for notarization is code signing. When I try to code sign the app, i get the below errors:

1. Your Mach-O executable does not conform to modern Mach-O layout rules.
2. You may be using a third party development product that hasn't been brought up to date, or post-processed your file in unsupported ways.

I provided the below publish options : 

- deployment mode = Self-contained
- Targete Runtime = osx-x64
- Enabled produce single file

I also added UseAppHost  as true in the csproj file.

Code signing is successful when setting "produce single file" to false.

I would like to know why enabling produce single file fails code signing

**Comment by antoineazar** [comment]
I have the same issue

**Comment by swaroop-sridhar** [comment]
Dup of https://github.com/dotnet/runtime/issues/3671
