### ISSUE TITLE
NuGet.targets error : 'vxxxx.xx.xx' is not a valid version string. (Parameter 'value') 

### ISSUE THREAD

**Issue by amirmou** [dotnet/core#4491]
I am getting This error

/usr/share/dotnet/sdk/3.1.101/NuGet.targets(123,5): error : 'v2020.03.16' is not a valid version string. (Parameter 'value') 

"unset version" didn't work as well,  per

_Originally posted by @jbenguira in https://github.com/dotnet/core/issues/3909#issuecomment-558856208_

~> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by scalablecory** [comment]
Can you share your project files and whatever command line you're running that shows this? Thanks.

**Comment by amirmou** [comment]
~> dotnet new console --output sample1
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on sample1/sample1.csproj...
/usr/share/dotnet/sdk/3.1.101/NuGet.targets(123,5): error : 'v2020.03.16' is not a valid version string. (Parameter 'value') [~/sample1/sample1.csproj]

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

~> cd sample1
~/sample1> dotnet restore                  
/usr/share/dotnet/sdk/3.1.101/NuGet.targets(123,5): error : 'v2020.03.16' is not a valid version string. (Parameter 'value') [~/sample1/sample1.csproj]

**Comment by carlossanlop** [comment]
@wli3 @dsplaisted would you be the best people to help with this?

**Comment by dsplaisted** [comment]
@amirmou That is very strange.  What do the contents of sample1.csproj look like?

Could you also run `dotnet restore -bl` to create a binary log and share that?  Be aware that this will include information from your machine such as environment variables, paths, etc.  See here for more info: http://aka.ms/binlog

**Comment by amirmou** [comment]
[sample1.zip](https://github.com/dotnet/core/files/4457774/sample1.zip)

**Comment by carlossanlop** [comment]
ping @dsplaisted

**Comment by dsplaisted** [comment]
@amirmou There's nothing special in the project file, so this is probably something in your environment.  I think I'd need a [binlog](http://aka.ms/binlog) to be able to investigate what's going on.

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.

**Comment by fabioduque** [comment]
The same thing happened to me, and it was due to me setting up the Environment Variable "VERSION". 
Solved with with
`set VERSION=`

**Comment by AraHaan** [comment]
I have the same problem in github actions recently here with 7.0.100-rc.1 SDK https://github.com/Elskom/runtime/suites/8483406288/artifacts/377156352.

**Comment by omajid** [comment]
The longer term fix for this issue would be https://github.com/dotnet/msbuild/issues/2713

**Comment by qsdfplkj** [comment]
Do not use underscores.

**Comment by Nikita-T86** [comment]
> In my case, I was getting the error during "dotnet restore" in my CI Pipeline. Seems it was due to having a declared variable named "version" in the YAML of the pipeline.

I had the same problem in my Azure DevOps build pipeline on "dotnet restore" step. The root cause was that I created variable "VersionSuffix" with string value. The solution for me was to rename variable to "BuildSuffix". Seems like problems with parsing, so any variable with "version" in name is used by dotnet restore.
