### ISSUE TITLE
HttpCLientFactory correct usage to pass credentials and get access token 

### ISSUE THREAD

**Issue by eshwar-crystal** [dotnet/core#4494]
Following **Curl script** successfully returns the token from the Server

curl  "https://staging.tcsgsp.in/Tax-Tool-Core/services/accessMgmt/generateToken" -H  "accept: application/json" -H  "content-type: application/json" -H  "username: ********" -H  "password: ******" 

And the following script generates the document on the Server
curl  -X POST "https://staging.tcsgsp.in/Tax-Tool-Core/services/auth/ewbApi/generateEwayBillNoDataApi" -H "content-type: application/json" -H "Authorization: Bearer 5c****ea-****-4aad-a02c-****7fb****c" -H "clientCode: xxx" -H "Gstin: 05XYZXYZXXR" -d @ewaybill.txt

**In Dotnet Core 3.1 following code is in startup.cs**
services.AddHttpClient("Get AccessToken", client1 => {
                client1.BaseAddress = new Uri("https://staging.tcsgsp.in/");
                client1.DefaultRequestHeaders.Add("accept", "application/json");
                 client1.DefaultRequestHeaders.TryAddWithoutValidation("Content-Type", "application/json");
                client1.DefaultRequestHeaders.Add("username", "*********");
                client1.DefaultRequestHeaders.Add("password", "******");

**In Controller following code is in place**
            var client1 = _httpClientFactory.CreateClient("Get AccessToken");
            var result = await client1.GetAsync("Tax-Tool-Core/services/accessMgmt/generateToken");
            if (result.IsSuccessStatusCode)
            {
                var content = await result.Content.ReadAsStringAsync();
               // return JsonConvert.DeserializeObject<WeatherForecast>(content);
            }
            return null;

The above code returns error and we do not get the token.

Also I could not find any documentation on how to pass the credentials to get back token and 
in the next step how to pass the token to the Server along with the  text file in the body and get the generated document

Is it possible to get the above tasks done through HttpClientFactory or we need some other classes?
Can anyone throw some light?

Thanks in advance.
Eshwar

**Comment by carlossanlop** [comment]
@scalablecory is this System.Net or ASP.NET?

**Comment by drumm227** [comment]
pay me

**Comment by scalablecory** [comment]
@eshwar-crystal were you able to figure this out? It looks like you need to run Fiddler to check how your request differs. You're using POST in one example but GET with HttpClient, for instance.
