### ISSUE TITLE
"dotnet" is  not recognized as internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by l3erdnik** [dotnet/core#4498]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Did you make sure the cmd window was closed and reopened after you installed dotnet?

**Comment by drumm227** [comment]
pay me

**Comment by GrabYourPitchforks** [comment]
Closing due to no response.
