### ISSUE TITLE
DEBUGGING PROBLEM

### ISSUE THREAD

**Issue by iamcarlg** [dotnet/core#4507]
Bonjour, 
J'ai eu un problème au niveau du débogage de mon programme.

Voici en attaché les photos de ce problème; en espérant une reponse réconfortante et rapide. 

Mes Salutations,
Carl Gauss Rugero
![IMG_20200403_030031](https://user-images.githubusercontent.com/43496871/78314013-ebb06800-7558-11ea-9437-fc180a26a13b.jpg)
![IMG_20200403_030152](https://user-images.githubusercontent.com/43496871/78314016-ee12c200-7558-11ea-9d3a-22f45207d124.jpg)

**Comment by carlossanlop** [comment]
The first screenshot seems to be a crash in Visual Studio. Please report it following these steps:
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

The second issue seems to be caused because the necessary packages were not installed. Did you install the developer pack as suggested?

**Comment by rugero3** [comment]
Hello,
Effectively, the first picture is a crash of visual Studio After some
updates, the problem got solved.

However, another problem came along after those updates. Something like
Hyper V is blocking the emulator when I try to debug my code.

I've looked for some documentations about the issue, but none of them gave
me the right answer. Could you please guide exactly to fix the problem ?

Thank you,

Cordially,
Carl Gauss Rugero

**Comment by carlossanlop** [comment]
> _Something like Hyper V is blocking the emulator when I try to debug my code._

Can you please share the exact error message?

**Comment by rugero3** [comment]
Yes, of course. The message is :

CPU acceleration status: GVM is not installed on this machine
More info on configuring VM acceleration on Windows:
https://developer.android.com/studio/run/emulator-acceleration#vm-windows
If you are using an Intel CPU: please check that virtualization is enabled
in the BIOS and that HAXM is installed and usable.
Note: if Hyper-V or Credential Guard is enabled, the emulator will not work
with HAXM.
See https://github.com/intel/haxm/issues/105#issuecomment-470927735 for
info on how to disable Credential Guard.
If you are using an AMD CPU or need to run alongside Hyper-V-based apps
such as Docker, we recommend using Windows Hypervisor Platform.General
information on acceleration:
https://developer.android.com/studio/run/emulator-acceleration.
Impossible de démarrer l'émulateur pixel_2_pie_9_0_-_api_28.
Vérifications à l'exécution effectuées
La génération a été annulée.

**Comment by carlossanlop** [comment]
@iamcarlg apologies for the delay. Unfortunately, for the Hyper-V problem this repo is not a good option to get answers. Did you get a chance to solve your issue?
