### ISSUE TITLE
Unable to execute the command

### ISSUE THREAD

**Issue by gnsharans** [dotnet/core#4508]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

```
C:\Users\Sai Sharan>dotnet new webapi -o myMicroservice --no-http
Couldn't find an installed template that matches the input, searching online for one that does...
```
```
Invalid input switch:
  --no-http
```

**Comment by gnsharans** [comment]
`C:\Users\Sai Sharan>dotnet new webapi -o myMicroservice`
Executed the above part of the code and able to get that project

**Comment by mairaw** [comment]
The command you're showing above is missing an s at the end. It should be --no-https, not --no-http.

```console
dotnet new webapi -o myMicroservice --no-https
```

So I'm closing this issue. Thanks for contacting us!

**Comment by gnsharans** [comment]
Thank you for your response
