### ISSUE TITLE
my terminal not responding 

### ISSUE THREAD

**Issue by abhikhandekar** [dotnet/core#4510]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Closing due to no response.
