### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by Amaranoorani** [dotnet/core#4511]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\Amara Noorani\myApp>cd myApp
The system cannot find the path specified.

**Comment by GrabYourPitchforks** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
No response in 4 days. Closing.
