### ISSUE TITLE
No se puede acceder a este sitio web

### ISSUE THREAD

**Issue by jcdiazgm** [dotnet/core#4515]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Operating system: Windows 10 Pro ver 18363.720
Error message: ERR_CONNECTION_REFUSED

**Comment by mairaw** [comment]
The ERR_CONNECTION_REFUSED error usually happens on Chrome browsers. Have you tried some of the solutions to fix that problem? It's usually not a problem with the website you're trying to access.

Maybe try to open the page on a different browser to confirm the behavior?

**Comment by drumm227** [comment]
pay me

**Comment by carlossanlop** [comment]
No response in a week. Closing.
