### ISSUE TITLE
Command prompt command : dotnet run , wont work 

### ISSUE THREAD

**Issue by Quantumike** [dotnet/core#4516]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when trying to use the dotnet run command I get a large amount of errors :

MyFirstGame\Library\PackageCache\com.unity.textmeshpro@1.4.1\Scripts\Runtime\TMP_UpdateManager.cs(138,9): error CS1519: Invalid token '{' in class, struct, or interface member declaration

yFirstGame\Library\PackageCache\com.unity.textmeshpro@1.4.1\Scripts\Runtime\TMP_UpdateManager.cs(238,1): error CS1022: Type or namespace definition, or end-of-file expected

AppData\Local\Microsoft\VisualStudio\16.0_cafb57a9\VTC\79a5af6441823743f56e038617ff99e8\~IC\I\CSharp\Android\BroadcastReceiver.zip\Activity.cs(13,11): error CS1056: Unexpected character '$'

**Comment by scalablecory** [comment]
The linked tutorial doesn't load these files. They appear to have something to do with Unity. Can you link the tutorial you're following?

**Comment by GrabYourPitchforks** [comment]
Closing due to no response.
