### ISSUE TITLE
Unable to Create Docker Image

### ISSUE THREAD

**Issue by andycshi** [dotnet/core#4521]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

![image](https://user-images.githubusercontent.com/238997/78465166-b40c0200-76b7-11ea-8e46-41e2e6ff291e.png)

Using - Docker version 19.03.8, build afacb8b

**Comment by shirhatti** [comment]
See announcement- https://github.com/dotnet/announcements/issues/104

You're currently running on Windows 10 Fall Creators Update/Windows Server, version 1709 which no longer supported. Please upgrade your Windows OS to a newer version.
