### ISSUE TITLE
 'dotnet' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by abhichawla96** [dotnet/core#4522]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

 'dotnet' is not recognized as an internal or external command 

can someone help me

**Comment by scalablecory** [comment]
Have you tried restarting the console window after installing?

**Comment by carlossanlop** [comment]
The tutorial instructions specify that any cmd windows need to be closed and reopened. This is most likely the culprit. Closing.
