### ISSUE TITLE
i am getting issue as dornet notfound although i had installed dotnet sdk 2.2, added path in environment variables and restarted system after taht also i am getting dotnet not found ,, but if i go to C drive and  dotnet folder i can see dotnet was installed and if  i give command dotnet -version it is showing version,, but globally dotnet was not found  how to install dotnet globally

### ISSUE THREAD

**Issue by madhukiranka** [dotnet/core#4524]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @madhukiranka! The SDK is typically installed under C:\Program Files\dotnet\ for 64-bit/x64 or C:\Program Files (x86)\dotnet\ for 32-bit/x86.

Can you show what your PATH env variable looks like?

**Comment by GrabYourPitchforks** [comment]
Closing due to no response.
