### ISSUE TITLE
Build error MSB4018: The "ResolveTargetingPackAssets" task failed unexpectedly. 

### ISSUE THREAD

**Issue by seunsaber** [dotnet/core#4526]
I am trying to build a dotnet core project on a linux machine.

Build fails with the following error:
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018: The "ResolveTargetingPackAssets" task failed unexpectedly. [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018: System.IO.FileNotFoundException: Could not find file '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.0.0/data/FrameworkList.xml'. [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018: File name: '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.0.0/data/FrameworkList.xml' [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.XmlTextReaderImpl.FinishInitUriString() [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at System.Xml.Linq.XDocument.Load(String uri) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.AddReferencesFromFrameworkList(String frameworkListPath, String targetingPackDllFolder, ITaskItem targetingPack, List`1 referenceItems) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.ExecuteCore() [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(264,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/var/lib/jenkins/workspace/MyProject/MyProject.Shared/MyProject.Shared.csproj]

Build FAILED.

See my csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.0.30" />
        <PackageReference Include="Flurl.Http" Version="2.4.2" />
        <PackageReference Include="Flurl.Http.Xml" Version="1.6.1" />
        <PackageReference Include="LazyCache" Version="2.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
        <PackageReference Include="Microsoft.DotNet.PlatformAbstractions" Version="3.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.0.0" />
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="5.0.0-rc4" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="5.0.0-rc4" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="5.0.0-rc4" />
        <PackageReference Include="System.Data.SqlClient" Version="4.7.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.5.0" />
        <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="3.0.13" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Security\" />
    </ItemGroup>

</Project>
```

**Comment by seunsaber** [comment]
Please help.

**Comment by safern** [comment]
@seunsaber I see you're using 3.0 SDK and targeting netcoreapp3.0 which are out of support. The LTS version is 3.1, I recommend installing the 3.1 SDK and re-targeting your app and see if that still happens there. @dsplaisted might have more insights for the error.

**Comment by dsplaisted** [comment]
I think this is an issue we've seen before where the targeting pack was not installed correctly.  I think it had something to do with the package dependencies.  @wli3 do you remember more?

What is in the following folder? `/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.0.0/`

If you delete that folder, it may fix the problem.

**Comment by drumm227** [comment]
pay me

**Comment by wli3** [comment]
Sorry I that doesn't ring a bell

**Comment by dagood** [comment]
> I think this is an issue we've seen before where the targeting pack was not installed correctly.

Yep, here: https://github.com/dotnet/core/issues/3868. It's kind of the opposite: the package wasn't uninstalled correctly, so removing the folder is a workaround that lets the SDK download a replacement from nuget.org.

@seunsaber if you can tell us what Linux distro you're using and how you installed .NET Core (package manager?) we can probably confirm you're hitting the same problem.

**Comment by seunsaber** [comment]
Hi guys, thanks for the replies. I had to reinstall the SDk. Maybe I did something wrong during the original installation. All is well now, thanks.

**Comment by gusennan** [comment]
I ran into this same issue.  I'm using Fedora 32 and Fedora's dnf package system to update packages. I recently upgraded from Fedora 31 to 32.

**Comment by Idrisi19** [comment]
please tell me what to do
Error MSB4018 The "ResolveTargetingPackAssets" task failed unexpectedly. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.23\data\FrameworkList.xml'.
