### ISSUE TITLE
mistaken message

### ISSUE THREAD

**Issue by rgomez17544** [dotnet/core#4528]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I am using .NET on a Linux machine, not the one on which I am writing this; so I cannot put any files with this.  
The program that shipped with the .NET download worked: output hello world.  Next the MS tutorial asked me to add: Console.Writeline--- Please excuse this message, I just found out my error.
thanks, sorry for the inconvenience.
rgomez

**Comment by mairaw** [comment]
No worries @rgomez17544. Closing this issue then.
