### ISSUE TITLE
Docker issue when i run docker build -t dir .

### ISSUE THREAD

**Issue by Dalasa-ab** [dotnet/core#4529]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Dalasa-ab** [comment]
unable to prepare context: unable to evaluate symlinks in Dockerfile path: Cre
 The system cannot find the file specified.
 this is the error

**Comment by carlossanlop** [comment]
@shirhatti can you please help here?

**Comment by sughosneo** [comment]
Hi @Dalasa-ab, thank you for reaching out. 

Looking at the error message it seems like docker file is not present in the directory from where you are trying to build the image. Are you running this command `docker build -t mymicroservice .` from the directory `MyMicroservice` ?
