### ISSUE TITLE
[MacOS, Linux] NuGet writes the NuGet.Config in ~/.config folder, but dotnet restore reads from ~/.nuget

### ISSUE THREAD

**Issue by Iankodj** [dotnet/core#453]
When using NuGet to add a private feed, `NuGet Sources Add` writes in `~/.config/NuGet/NuGet.Config` file. But when using `dotnet restore` the `~/.nuget/NuGet/NuGet.Config` file is used to read the `packageSources` and `packageSourceCredentials`. 

This issue forces users to manually copy and paste all necessary information instead of having that generated automatically by the NuGet CLI. 

NuGet repo issue: https://github.com/NuGet/Home/issues/4413

**Comment by Petermarcu** [comment]
This is best tracked in the linked issue. Going to close it here.
