### ISSUE TITLE
Hash sum mismatch

### ISSUE THREAD

**Issue by jlgpjong** [dotnet/core#4531]
# Cannot install dotnet in 18.04 . erro is Hash sum mismatch

Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/d/dotnet-runtime-3.1/dotnet-runtime-3.1.3-x64.deb  Hash Sum mismatch

# General

cannot install dotnet

**Comment by scalablecory** [comment]
@dagood @leecow

**Comment by dagood** [comment]
@jlgpjong, can you please provide the output of **all** the commands you ran? I don't hit this issue on my machine, and there isn't enough info in this issue to figure it out.

/cc @NikolaMilosavljevic

**Comment by jlgpjong** [comment]
got it fix by restarting the pc and redo installation dotnet3.1
