### ISSUE TITLE
avvio dotnet run cursore lampeggia ma non parte applicazione

### ISSUE THREAD

**Issue by boroil** [dotnet/core#4536]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Translation:
> start dotnet run cursor flashes but no application starts

@boroil can you provide more information? What were you trying to do?

**Comment by GrabYourPitchforks** [comment]
Closing due to no response.
