### ISSUE TITLE
'dotnet' is not recognized as an internal or external command error

### ISSUE THREAD

**Issue by Ukieman** [dotnet/core#4537]
I was trying to confirm if my system has .NET Framework 4.8 installed. I used the 'dotnet' command but this may wrong approach as I got this command from a page that was discussing installation of .NET SDK (64 bit). 

I have looked at the Registry Editor subkey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP. The installed versions are listed under the NDP subkey. And found "Release   REG_DWORD 0x00080ea8 (528040)
Version    REG_SZ   4.8.03752

**Comment by leecow** [comment]
`dotnet` is a .NET Core command, not Framework so that won't do what you want. The regkey you found does indicate 4.8 so seems like you're good to go? You should also see an entry in the Programs Control Panel.

**Comment by Ukieman** [comment]
Thanks for your response.  If you have time I'd like to know why 4.8 shows
in registry but not in my Programs Control Panel.

**Comment by mairaw** [comment]
.NET Framework is a component of the Windows operating system, so that's why it's not shown on the control panel.

Hopefully that clarifies all your questions.
