### ISSUE TITLE
.Net Core 3.1 binding doesn't work??

### ISSUE THREAD

**Issue by RahmanM** [dotnet/core#4538]
Hi there,

I just created a OOB WEB API project with .net core 3.1, Visual Studio 2019, Windows 10. Somehow the FromQuery doesn't seem be working. The OOB WeatherForecastController with extra actions attached.

1) - This works -> https://localhost:44332/weatherforecast
2) - Doesn't work -> https://localhost:44332/weatherforecast?top=5 (doesn't work even if I add public IEnumerable<WeatherForecast> Get([FromQuery] int top)
3) - This works -> https://localhost:44332/weatherforecast/5
4) - This doesn't work e.g. I would like to pass two input parmeters into my get action -> https://localhost:44332/weatherforecast/5/false or https://localhost:44332/weatherforecast?top=5&cold=false (even if I add [FromQuery])

I would like to know why case 2 and 4 are not working and what are the other options. Sample code below:

       using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace WebApi.Sample.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }

        [HttpGet("{top}")]
        public IEnumerable<WeatherForecast> Get(int top)
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray().Take(top);
        }

        [HttpGet("{top},{cold}")]
        public IEnumerable<WeatherForecast> Get(int top, bool cold)
        {
            var rng = new Random();
            var result = Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();

            if (!cold)
            {
                result = result.Skip(4).Take(top).ToArray();
            }

            return result;
        }

    }
}

**Comment by XeonFX** [comment]
For example you can write just one Get function with nullable parameters.
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace WebApplication1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get(int? top, bool? cold)
        {
            var rng = new Random();
            var data = Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
            if (cold == true)
                data = data.Where(x => Array.IndexOf(Summaries, x.Summary) <= 3);
            else if (cold == false)
                data = data.Where(x => Array.IndexOf(Summaries, x.Summary) > 3);
            if (top > 0)
                data = data.Take(top.Value);
            return data.ToArray();
        }
    }
}
```

**Comment by RahmanM** [comment]
Sorry, would like to know why it is not working. According to docs it should work. And I have used it that way in the past.

**Comment by XeonFX** [comment]
You need to read more about how routing works. First the route matching happen then query parameters are passed.

> Doesn't work -> https://localhost:44332/weatherforecast?top=5 (doesn't work even if I add public IEnumerable Get([FromQuery] int top)

This doesn't work because you pass query _?top=5_ to this method.
`
[HttpGet]
public IEnumerable<WeatherForecast> Get()
`
> This doesn't work e.g. I would like to pass two input parameters into my get action -> https://localhost:44332/weatherforecast/5/false or https://localhost:44332/weatherforecast?top=5&cold=false (even if I add [FromQuery])

This doesn't work because you used comma instead of slash.
`[HttpGet("{top},{cold}")] -> [HttpGet("{top}/{cold}")]`
And again query _?top=5&cold=false_ is passed to function that matches your request adress /weatherforecast
`[HttpGet]
public IEnumerable<WeatherForecast> Get()
`

**Comment by RahmanM** [comment]
Thanks that slash was the solution!

**Comment by XeonFX** [comment]
You can write it this way to use all routes and query parameters at same time like:
with query parameters:
`/weatherforecast?top=5&cold=true`
with route:
`/weatherforecast/5/true`
or mixed:
`/weatherforecast/5?cold=true`
```
[HttpGet]
public IEnumerable<WeatherForecast> Get(int? top, bool? cold)
{
    ...
}

[HttpGet("{top}")]
public IEnumerable<WeatherForecast> GetByTop(int? top, bool? cold)
{
    return Get(top, cold);
}

[HttpGet("{top}/{cold}")]
public IEnumerable<WeatherForecast> GetByTopAndCold(int? top, bool? cold)
{
    return Get(top, cold);
}
```
