### ISSUE TITLE
Template "ASP.NET Core Web App" could not be created. Access to the path 'C:\WINDOWS\system32\myWebApp' is denied.

### ISSUE THREAD

**Issue by indyhicks** [dotnet/core#4539]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by indyhicks** [comment]
Access to the path "is denied"
Template "ASP.NET Core Web App" could not be created.
Access to the path 'C:\WINDOWS\system32\myWebApp' is denied.

**Comment by indyhicks** [comment]
OS: Windows 10

**Comment by mairaw** [comment]
The system32 folder is a protected path on Windows. Can you try changing the path to something else?
Typically, when you open a new command prompt, it will open on the users path.
