### ISSUE TITLE
dotnet.exe - System Error 

### ISSUE THREAD

**Issue by dukelangcen** [dotnet/core#4541]
The prorgramme can't start because 
api-ms-win-crt-runtime-|1-1-0.dll 
is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by XeonFX** [comment]
This could happen when you create self-contained application with windows runtime and don't have all files that start with `api-ms-*` in your executable directory.

**Comment by scalablecory** [comment]
Please ensure you have the dependencies listed at https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows installed

**Comment by danmosemsft** [comment]
@dukelangcen can you confirm that you have all dependencies? Have you tried repairing your .NET Core SDK? Did you publish the app as self contained -- if so is this file in the output publish folder?

**Comment by mairaw** [comment]
Closing due to the lack of response.
