### ISSUE TITLE
Expand on caller information

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/core#4544]
That said, I just learned about the utility of the various caller information attributes as described at [https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information). These are great,  but I often have a number of classes that implement an interface and thus all use the same member name. I'd like to be able to use this in my logging, but differentiate by the caller type, but this doesn't appear to be obtainable from the various attributes.

Thus, I'd like to file a feature request for a `CallerMemberType` attribute to return the type of the member that called the method. Ideally, it'd follow the same implementation approach as `CallerMemberName`:

```
public class SomeClass
{
  public void SomeMethod([CallerMemberType]string memberType = "")
  {
    Console.WriteLine(memberType); //Ideally, this outputs the type of the calling method
  }
}
```

Just as the caller info for the method name is emitted as a literal at compile time, so too it seems like the method type could be emitted in a similar manner.

I appreciate you considering this request!

Also, if this is the wrong place to have filed this issue, please point me to the correct repo and I'd be happy to open a new issue.

**Comment by leecow** [comment]
Issue moved to [dotnet/runtime #34695](https://github.com/dotnet/runtime/issues/34695) via [**ZenHub**](https://www.zenhub.com/)
