### ISSUE TITLE
Throwing error when trying to start the container

### ISSUE THREAD

**Issue by hemantwithu** [dotnet/core#4549]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

It was not possible to find any installed .NET Core SDKs

Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:

https://aka.ms/dotnet-download

The docker file I created -
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY myMicroservices.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]

**Comment by sughosneo** [comment]
Hi @hemantwithu, thank you for reaching out. 

Yes, you'll need to install .NET SDK as per instructions mentioned in [Install .NET SDK](https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install) section to test the API locally. Then you'll need [Docker Desktop for Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac) to dockerize your service.

Could you please share the exact error message?
