### ISSUE TITLE
dotnet did not work

### ISSUE THREAD

**Issue by jasader** [dotnet/core#4550]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I started Microsoft.NET Core SDK 3.1.201 and installed it in
my PC, and in Command Prompt, enter dotnet, but no responses. nothing happen.
Would you teach me what to do?

Using Windows 10 PC(Lenovo)
Path: C:\Program Files\dotnet\sdk\3.1.201\cs\dotnet.resources.dll
No error messages 
Hiroshi Hasegawa

**Comment by carlossanlop** [comment]
> but no responses. nothing happen.

Did you close and reopen the command line window after installing the SDK? It's one of the steps in the tutorial.
