### ISSUE TITLE
Server permission requirements not documented

### ISSUE THREAD

**Issue by dvdmatt** [dotnet/core#4551]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Running through the tutorial everything was fine until I tried to launch the app.  Nothing showed up.
I turned off the firewall, no help.  This step (or opening port 5000 should be added to the documentation)
I tried disabling selinux, no help.
There are no errors in the system logs.
I do get a warning, is IPV6 required or something?
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'.

**Comment by mairaw** [comment]
@Tratcher is this something you can help with?

**Comment by Tratcher** [comment]
When binding to localhost Kestrel will bind separately to IPv4 (127.0.0.1) and IPv6 (::1) and warn if one of them fails. The server should still work if at least one of them succeeds.
https://github.com/dotnet/aspnetcore/blob/a190fd34854542266956b1af980c19afacb95feb/src/Servers/Kestrel/Core/src/LocalhostListenOptions.cs#L39-L61

Your system may have IPv6 disabled, or something else may be using that port, but either way you should still be able to use the server.
@halter73 

> I turned off the firewall, no help. This step (or opening port 5000 should be added to the documentation)

The firewall should not block localhost scenarios.

> Running through the tutorial everything was fine until I tried to launch the app. Nothing showed up.

If you use the browser network tools, what does it say is the actual response status code, a 404, or a 500?

You can change the [logger settings]( https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging) to set "Microsoft" logs to the "Information" level. That will give you a basic status for each request. Setting them to the "Debug" level will give you even more detail.

**Comment by mairaw** [comment]
Closing since this seems to be answered. Let us know otherwise.
