### ISSUE TITLE
Why http://localhost:5000 didn't open with google chrome. 

### ISSUE THREAD

**Issue by MadukaDeAbrew** [dotnet/core#4556]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Provide details about the problem you're experiencing. Include the exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Closing due to lack of response; please reopen if you can provide more detail.
