### ISSUE TITLE
Build error with .NET Core 5 Preview 2 using Visual Studio for Mac

### ISSUE THREAD

**Issue by AlphaComposite** [dotnet/core#4558]
Getting this error when trying to build using Visual Studio for Mac (macOS Catalina - latest version). Yes, the .NET 5 Preview 2 SDK is installed. As a relevant aside, the same project builds and runs while using JetBrains Rider. 

![image](https://user-images.githubusercontent.com/25360554/79048261-7d674780-7be1-11ea-9b43-6c376fa81230.png)

**Comment by mairaw** [comment]
@jongalloway can you help with this?

**Comment by mairaw** [comment]
Closing since this is for a version no longer supported. @AlphaComposite if you continue to have issues, can you log them through VS so they can be more appropriately routed? Thanks.
