### ISSUE TITLE
AuthenticationException in SignalR client Hub in .netcore 3.1

### ISSUE THREAD

**Issue by dgroh** [dotnet/core#4565]
# Issue Title

AuthenticationException in SignalR client Hub in .netcore 3.1

# General

Basically I have an WPF client based on .netcore 3.1 (SignalR client) which receives notification from a SignalR Hub. The hub is hosted on our server and the WPF runs on users local machine. Locally everything works fine.

When the WPF App tries to connect to the Hub I get the following error message:

> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Net.Security.SslStream.ThrowIfExceptional() at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) at System.Net.Security.SslStream.<>c.b__65_1(IAsyncResult iar) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken) Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Skipping dispose, connection is already disposed.

Below is my application code.

**Startup.cs**

```csharp
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();

        services.AddSignalR(hubOptions => { hubOptions.EnableDetailedErrors = true; });
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseHttpsRedirection();

        app.UseRouting();

        app.UseAuthentication();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapHub<SyncCodeHub>("/signalr");
        });
    }
}
```

**SyncHub.cs**

```csharp
public class SyncHub : Hub
{
    public override Task OnConnectedAsync()
    {
        Clients.Caller.SendAsync("Connected", Context.ConnectionId);

        return base.OnConnectedAsync();
    }
}
```

```csharp
public class SyncHub : Hub
{
    public override Task OnConnectedAsync()
    {
        Clients.Caller.SendAsync("Connected", Context.ConnectionId);

        return base.OnConnectedAsync();
    }
}
```

**WebHookController.cs**

```csharp
// POST: /webhook
[HttpPost]
public async Task<IActionResult> Post([FromBody] JsonElement body)
{
    try
    {
        var eventType = body.GetProperty("eventType").ToString();

        _logger.LogInformation($"[HttpPost]: The current event type is '{eventType}'");

        switch (eventType)
        {
            case "build.complete":
                return await BuildComplete(body);
            default:
                return BadRequest();
        }
    }
    catch (Exception ex)
    {
        _logger.LogError($"[HttpPost] Exception: {ex}");

        return BadRequest();
    }
}
```

**WPF App**

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl(viewModel.Endpoint)
    .ConfigureLogging(logging => {
        // Log to the Output Window
        logging.AddDebug();

        // This will set ALL logging to Debug level
        logging.SetMinimumLevel(LogLevel.Debug);
    })
    .Build();

connection.On<string>("ReceiveMessage", (message) =>
{
    Dispatcher.CurrentDispatcher.Invoke(() =>
    {
        using (var db = new SettingsDbContext())
        {
            var userSettings = db.UserSettings.First(x => x.ItiUsername == Environment.UserName);

            SyncTo50Hertz.Sync(userSettings);
        }
    });
});

connection.On<string>("Connected", (connectionId) => { viewModel.ConnectionState = "Connected"; });

try
{
    connection.StartAsync();
}
catch (Exception ex)
{
    Debugger.Break();

    // TODO: Handle error
}
```

**Program.cs**

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder
                    .ConfigureLogging(logging =>
                    {
                        logging.ClearProviders();
                        logging.AddConsole();
                    })
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseIISIntegration()
                    .UseStartup<Startup>();
            });
}
```

**Comment by GrabYourPitchforks** [comment]
From the exception text:
> The remote certificate is invalid according to the validation procedure.

Please double-check that your web server's SSL certificate is valid.

**Comment by dgroh** [comment]
Although this might be an issue, I wanted to bypass the SSL. I tested with Fiddler and Postman disabling SSL and the endpoint could be hit. I also got an response from Fiddle. So, how can I disable bypass SSL validation in .netcore 3.1?

I tried this: https://stackoverflow.com/questions/42712844/ignore-bad-certificate-net-core but it didn't help

**Comment by dgroh** [comment]
The issue was indeed the server certificate. It was expired. I would be very interested still to know how to bypass an invalid certificate.

**Comment by redoz** [comment]
@dgroh Did you ever figure out how to bypass the cert check?
