### ISSUE TITLE
Impersonation

### ISSUE THREAD

**Issue by vanros** [dotnet/core#4567]
I need to do a impersonation in a .net core app, but this app will run on a linux container.

in windows a use like that
[DllImport("advapi32.dll", SetLastError = true, CharSet = CharSet.Unicode)]

I could not find any solution for this problem.

**Comment by scalablecory** [comment]
I don't know if Linux has the same level of impersonation support. `seteuid` is process-wide, for instance. @wfurt  do you know?

**Comment by wfurt** [comment]
Could you be little bit more specific @vanros? But I don't think Unix has same concept as Windows and I feel "Impersonation" may mean something very specific. 

cc: @davidsh

**Comment by davidsh** [comment]
@vanros Can you please post more information about your scenario? Are you asking about impersonation/delegation for an HTTP server request?

**Comment by mairaw** [comment]
Closing due to the lack of response.
