### ISSUE TITLE
.net core string operator does not execute with the excepted result

### ISSUE THREAD

**Issue by Danieladu** [dotnet/core#4570]
# Issue Title

.net core string operator does not execute with the excepted result

# General
SDK: .net core 3.1 
Environment: ubuntu 18/04

Code:
```
Console.WriteLine("abc\n".IndexOf("\n"));
Console.WriteLine("abc\r\n".IndexOf("\n"));
Console.WriteLine("abc\r\n".Contains("\n"));
Console.WriteLine("abc\r\n".Split('\n').Length);
Console.WriteLine("abc\n".EndsWith("\n"));
Console.WriteLine("abc\r\n".EndsWith("\n"));
```
Result:
```
3
-1   -> not as expected
True
2
True
False   -> not as expected
```

**Comment by benaadams** [comment]
It's the `StringComparison.CurrentCulture` that gets used on Linux; if you change to `Ordinal` or use a `char` parameter rather than a `string` one you should get the results you are expecting:
```
Console.WriteLine("abc\r\n".IndexOf("\n")); // -1
Console.WriteLine("abc\r\n".IndexOf("\n", StringComparison.Ordinal)); // 4
Console.WriteLine("abc\r\n".IndexOf('\n')); // 4
```

@GrabYourPitchforks @tarekgh

**Comment by Danieladu** [comment]
> It's the `StringComparison.CurrentCulture` that gets used on Linux; if you change to `Ordinal` or use a `char` parameter rather than a `string` one you should get the results you are expecting:
> 
> ```
> Console.WriteLine("abc\r\n".IndexOf("\n")); // -1
> Console.WriteLine("abc\r\n".IndexOf("\n", StringComparison.Ordinal)); // 4
> Console.WriteLine("abc\r\n".IndexOf('\n')); // 4
> ```
> 
> @GrabYourPitchforks @tarekgh

Cool, it works.

**Comment by tarekgh** [comment]
@benaadams thanks for your reply.
@Danieladu let's know if you have any more questions.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/roslyn-analyzers/issues/2581
