### ISSUE TITLE
 Ensure that 'npm' is installed and can be found in one of the PATH directories

### ISSUE THREAD

**Issue by michalzubkowicz** [dotnet/core#4573]
# ClientApp is not starting when node is not installed system wide. 

```
AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.

[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.dotnet/tools
Make sure the executable is in one of those directories, or update your PATH.

```
# General
It occurred on, but problem probably exists on every distrubution
Linux Mint 19.3
.NET Core 3.1

.NET Core is taking system wide $PATH env variable not users.  My current user $PATH value is slightly diffrent that one reported by exception details.

It should take $PATH variable of current user.  It's very important with tools like nvs (node version switcher) and other similiar also when it's running in shared environment as specific user.

**Comment by omajid** [comment]
(This isn't an official response or anything. I am most a bystander, not too different from you, in this case.)

Can you explain a little bit more about this issue? What is your "current user $PATH"? What is the "system wide $PATH"? If you start a new terminal, what is the output of `echo $PATH`? What does running `bash -c 'echo $PATH'` say? And finally, if you run your original `dotnet` command (what was it, btw?) in this new terminal, what error do you see now?

**Comment by michalzubkowicz** [comment]
My system wide path is:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.dotnet/tools` 
It's taken from /etc/profile.d, and this path is reported by exception. 

My users path is (just a excerpt):
`/home/user/.go/bin:/usr/local/go/bin:/home/user/.nvs/default/bin:/home/user/.nvs/default/bin:`
So it's slightly diffrent (it has my user's path addons) 

I've confirmed that it's the case because when I've added /home/user/.nvs/default/bin (so path to my NPM) to system wide PATH it's started to work correctly.

**Comment by omajid** [comment]
Thanks.

In my understanding, there isn't really a user vs system path. There's just one value of the environment variable that a program sees. So if you are setting your `$PATH` correctly, dotnet should be using that; it can't be seeing some other value of the environment variable `PATH` from elsewhere.

So, please help me make sense of this.

When you have a terminal, what does `echo $PATH` say? If you run your `dotnet` commands in that terminal, what do does it think the value of `$PATH` is?

> Dotnet is installed from repositories, I'm running it from Rider.

I wonder if you can ask Rider what it thinks your `$PATH` is. If Rider has not picked up your customized `$PATH`, it may be showing a bad/old value to `dotnet`.

**Comment by michalzubkowicz** [comment]
I've checked it again and it seems to be Rider's issue, it doesn't take into account PATH changes in user's profile. I'll report to them then. 
Thanks!

**Comment by ThiagoYuri** [comment]
Bom como o erro e de que o NPM não está instalado no diretório e por isso não e possível instalar as dependências eu coloquei em meu código um docker 3 linhas para acessar o diretório do "app" e baixar e instalar o NPM.

```
# installs NodeJS and NPM
WORKDIR /app
RUN apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -yq nodejs build-essential
```

![image](https://user-images.githubusercontent.com/78873117/160870643-9ceffc48-0033-4e5b-9cff-5e4af3f34f5e.png)

Importante: No primeiro build o meu sistema demorou e demostrou um erro de conexão porém na segunda tentativa de build ele funcionou corretamente trazendo a pagina web com o React funcionando.

Projeto em questão : https://github.com/ThiagoYuri/DocGenerator
