### ISSUE TITLE
dot-net issues

### ISSUE THREAD

**Issue by sweetjessyx** [dotnet/core#4575]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Closing due to the lack of response.
