### ISSUE TITLE
 .Net Core 3.1 Web API for video streaming from MySQL database

### ISSUE THREAD

**Issue by bugrakosen** [dotnet/core#4584]
I've already searched on google how to stream videos with ASP.NET Core 3 but I only find websites explaining it for ASP.NET Core 2 and making it with URL (e.g. http://anthonygiretti.com/2018/01/16/streaming-video-asynchronously-in-asp-net-core-2-with-web-api/) . I also searched range requests and SignalR.

I save my videos in type of LongBlob in MySql Database. When request comes to API i'll pull my video(blob) from database and streaming to client side partially(e.g like youtube).Youtube download the video part by part. Thats what I want.

So, how can I stream video like that in Asp.Net Core 3 ?

**Comment by jannavarro** [comment]
@bugrakosen Good day. It seems issue has been closed without answer. I'm interested to know how you solved this?

**Comment by bugrakosen** [comment]
@jannavarro  I solved this another way. Saved images as blob to database is not a good way i think. Because it causes the database to slow down and the data retrieved from the database needs to deserialize. So i changed the save method for images. I saved images to file system then streaming with url(FileStreamResult) and file path(VirtualPathResult).

With that way you just need to do this;



       [HttpGet("Stream/Path/{*path}")]
        public async Task<FileResult> GetStreamFromPathAsync(string path)
        {
            return new VirtualFileResult(path,"video/mp4");
        }


or


        [HttpGet("Stream/Url/{*videoUrl}")]
        public async Task<FileStreamResult> GetStreamFromUrlAsync(string videoUrl)
        {
            var stream = await _streamingService.GetVideoByUrlAsync(videoUrl).ConfigureAwait(false);
            return new FileStreamResult(stream, "video/mp4");
        }


Have a good day.

**Comment by jannavarro** [comment]
Thank you @bugrakosen for the response. It well help in my initial investigation.. :)

**Comment by doug62** [comment]
I'm also looking for something like this - i have a background service that updates a bitmap - i wish to stream that to subscribers.
