### ISSUE TITLE
'dotnet' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by LimaBravoSix** [dotnet/core#4586]
I am on a MacBook Air running Catalina OS 10.15.4.  When I open the Terminal and submit the ~$ dotnet, the terminal returns -bash: ~$: command not found.  Any suggestions?

**Comment by mairaw** [comment]
Have you tried closing and opening the terminal window?

https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

**Comment by mairaw** [comment]
Closing due to the lack of response.
