### ISSUE TITLE
Unable to add migration in the project

### ISSUE THREAD

**Issue by emamcoder** [dotnet/core#4589]
# Unable to add migration

I am using the dotNet Stander Library project version 2.1 (Visual Studio For Mac-Community 8.5.3 built 16 ), in that, I have added a package for EF 3.1.3. When I am trying to add the package for migration, getting error as mentioned below.

# NuGet Package Manager Console command which I have tried.
PM> dotnet add package Microsoft.EntityFrameworkCore.Tools.DotNet
  Writing /var/folders/mq/vmt_y3px15n3fx0x49yryh380000gn/T/tmpVWm6rJ.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.Tools.DotNet' into project '/Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj'.
info : Restoring packages for /Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.tools.dotnet/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.tools.dotnet/index.json 990ms
error: Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.3 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.3 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
error: Package 'Microsoft.EntityFrameworkCore.Tools.DotNet' is incompatible with 'all' frameworks in project '/Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj'.
PM> dotnet add package Microsoft.EntityFrameworkCore.Tools.DotNet -v 2.0.1
  Writing /var/folders/mq/vmt_y3px15n3fx0x49yryh380000gn/T/tmppIYBJQ.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.Tools.DotNet' into project '/Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj'.
info : Restoring packages for /Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj...
error: Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.1 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
error: Package 'Microsoft.EntityFrameworkCore.Tools.DotNet' is incompatible with 'all' frameworks in project '/Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj'.
PM> dotnet add package Microsoft.EntityFrameworkCore.Tools.DotNet -v 1.0.0
  Writing /var/folders/mq/vmt_y3px15n3fx0x49yryh380000gn/T/tmp7AWLvt.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.Tools.DotNet' into project '/Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj'.
info : Restoring packages for /Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.tools.dotnet/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.tools.dotnet/1.0.0/microsoft.entityframeworkcore.tools.dotnet.1.0.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.tools.dotnet/1.0.0/microsoft.entityframeworkcore.tools.dotnet.1.0.0.nupkg 1266ms
info : Installing Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0.
error: Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
error: Package 'Microsoft.EntityFrameworkCore.Tools.DotNet' is incompatible with 'all' frameworks in project '/Users/emamulhasan/Projects/SamuraiApp/Samurai.App.Data/Samurai.App.Data.csproj'.
PM>

 @shanselman

**Comment by mairaw** [comment]
@JeremyLikness @ajcvickers can you please take a look at this EF issue?

**Comment by ajcvickers** [comment]
@emamcoder `Microsoft.EntityFrameworkCore.Tools.DotNet` has been obsolete since EF Core 2.1. Don't use this package.

**Comment by mairaw** [comment]
@ajcvickers is it possible to add a description to the package page about that?

**Comment by ajcvickers** [comment]
@mairaw We will look into making this package officially obsolete. Last time I looked into it, the process required seemed to outweigh the value of doing it, but things may have got easier.

**Comment by emamcoder** [comment]
@ajcvickers As I mentioned the details about the framework and IDE I used.
Could you suggest to me how I can create a migration for it or any URL which I can refer to and move forward with my development work?

**Comment by ajcvickers** [comment]
@emamcoder Migrations documentation is here: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli

**Comment by emamcoder** [comment]
@ajcvickers As per the provided reference document I have tried and I am hitting below error.
PM> dotnet ef migrations add InitialCreate
No project was found. Change the current working directory or use the --project option.
PM> 

I referred to [this](https://github.com/dotnet/EntityFramework.Docs/issues/737) for the solution and tried the steps but no luck.

**Comment by ajcvickers** [comment]
@emamcoder If you're following the documentation and it is not working, then please file an issue on the [EF docs repo](https://github.com/dotnet/EntityFramework.Docs) and include reference to the documentation and detailed information about where and how it failed as you followed the instructions.

**Comment by emamcoder** [comment]
issue resolved.
