### ISSUE TITLE
Unable to install dotnet-sdk-3.1 on Raspberry Pi running Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by ParamOza** [dotnet/core#4592]
While trying to install the dotnet SDK onto my RasPi, I keep getting a 404 on the Microsoft Ubuntu packages repo. I can see the dotnet-sdk-3.1 package when I run `apt search dotnet-sdk` but I keep getting a "Unable to locate package dotnet-sdk-3.1" error when I try to run `sudo apt-get install dotnet-sdk-3.1`. Here is exactly what happens:

`ubuntu@ubuntu:~$ sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.1
E: Couldn't find any package by glob 'dotnet-sdk-3.1'
E: Couldn't find any package by regex 'dotnet-sdk-3.1'
`

**Comment by scalablecory** [comment]
@dagood @leecow

**Comment by dagood** [comment]
The Raspberry Pi runs on the ARM architecture, not x64, so you need to follow these instructions ([source](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804)) to install using binaries instead of using the apt feed:

> Package manager installs are only supported on the **x64** architecture. Other architectures, such as **ARM**, must [manually install the .NET Core SDK](https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-linux#download-and-manually-install) or [manually install the .NET Core Runtime](https://docs.microsoft.com/en-us/dotnet/core/install/runtime?pivots=os-linux#download-and-manually-install).

**Comment by dagood** [comment]
We are looking at creating deb packages for ARM and ARM64, tracked here:
https://github.com/dotnet/runtime/issues/3263
https://github.com/dotnet/runtime/issues/3298
Until then, you have to use the alternatives.
