### ISSUE TITLE
C:\Users\Grace>dotnet new console -o myApp Creating this template will make changes to existing files:   Overwrite   myApp.csproj   Overwrite   Program.cs  Rerun the command and pass --force to accept and create.

### ISSUE THREAD

**Issue by Grace-Hepsiba** [dotnet/core#4593]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
This indicates you've already created a "myApp" project. You can choose a different project name, force the overwriting of those files, or delete the original directory and re-run.
