### ISSUE TITLE
Bug? ConfigureApplicationCookie does not work when cookie.name = x

### ISSUE THREAD

**Issue by StanlyLife** [dotnet/core#4599]
# ConfigureApplicationCookie does not work when cookie.name = x

I have had an issue with authenticating my login, and i finally figured out that my cookie was not beeing applied when i had set

```
services.ConfigureApplicationCookie(options => {
  options.Cookie.Name = "MyCustomIdentityCookie";
  options.AccessDeniedPath = "/home/denied";
  options.LoginPath = "/home/loginRequired";
});
```

however, when using:

```
services.ConfigureApplicationCookie(options => {
  options.Cookie.Name = "My.Custom.Identity.Cookie";
  options.AccessDeniedPath = "/home/denied";
  options.LoginPath = "/home/loginRequired";
});
```

it works fine, i'm thinking this is a bug or am i wrong?

**Comment by mairaw** [comment]
@StanlyLife is this still an issue? I'm triaging some old issues and found this one.

@JeremyLikness is this something you can help with?

**Comment by JeremyLikness** [comment]
@StanlyLife what type of app is this? ASP.NET Framework? ASP.NET Core? I can get it moved to the right spot if I know more details and it's still an issue.
