### ISSUE TITLE
Server side WCF support?

### ISSUE THREAD

**Issue by bdowns** [dotnet/core#460]
Is there any support for running WCF on the server side with .net core?    We have alot of WCF, often times used with TCP/IP, and pipes that we would like to port over to .net core.  I cant seem to find any WCF on the server side available, only client calls?

**Comment by svick** [comment]
Yes, .Net Core does not have any support for WCF servers. There is already a discussion about this on the WCF repo: https://github.com/dotnet/wcf/issues/1200.

**Comment by Petermarcu** [comment]
Closing this here. This is best discussed on the WCF repo dotnet/wcf#1200
