### ISSUE TITLE
Learn ASP.NET hello-world-tutorial/modify error when following editing instruction. 

### ISSUE THREAD

**Issue by patriquefostere** [dotnet/core#4602]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows 10

The problem is with the editing: "Open Pages/Index.cshtml in any text editor and replace all of the code with the following, then save the file." 

I get a whole load of red errors:

**C:\Users\Surface\myWebApp>dotnet run
Pages\Index.cshtml.cs(2,8): error CS1002: ; expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(2,8): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(3,2): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(4,21): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(4,23): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(7,1): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(7,2): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(7,11): error CS1001: Identifier expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(7,11): error CS1514: { expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(7,11): error CS1513: } expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(7,11): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,6): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,8): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,9): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,16): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,21): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,24): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(8,26): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,6): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,7): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,17): error CS1002: ; expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,24): error CS1002: ; expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,24): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,31): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,48): error CS1031: Type expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,48): error CS1003: Syntax error, ',' expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(9,49): error CS1003: Syntax error, ',' expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(10,1): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(10,3): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Surface\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(10,6): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Surface\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.**

**Comment by mairaw** [comment]
Can you paste the contents of the Pages/Index.cshtml that you modified? Also make sure that's the only file being changed.
