### ISSUE TITLE
the program can not start because api-ms-win-crt-runtime-|1-1-0.dll

### ISSUE THREAD

**Issue by omidasghari1381** [dotnet/core#4603]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Please make sure you've installed all the [required dependencies](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows). The Windows 7/8 section has what you need.

**Comment by scalablecory** [comment]
@dagood @mairaw this is a somewhat common issue we see. Good opportunity to improve installer or tutorial.

**Comment by mairaw** [comment]
Good point @scalablecory! I'll add this to the tutorials.

**Comment by mairaw** [comment]
@omidasghari1381 can you confirm which version of Windows you have? The tutorials are missing some required dependencies for certain operating systems.
Please check at https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows#windows-7--vista--81--server-2008-r2

**Comment by mairaw** [comment]
@scalablecory @carlossanlop I made some changes to the install step of the tutorials.
Let's see if it will make a difference.

**Comment by mairaw** [comment]
Closing given the tutorials and docs were updated.
