### ISSUE TITLE
dotnet not accepting arguments

### ISSUE THREAD

**Issue by rawalsagar** [dotnet/core#4604]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Created "Hello World" program in Program.cs file, but console doesn't read ("The current time is " + DateTime.Now); arguement

**Comment by mairaw** [comment]
Can you paste your entire source code in program.cs? Also, how are you trying to run the program? Maybe paste a screenshot of the code running so we can try to help. Thanks!

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
