### ISSUE TITLE
Compiler directive for current method name

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#4608]
# Issue Title
Could we please have a compiler directive for the current method?

# General
Questions about how to print out the current method name date back to the beginning of dotnet core. These "solutions" usually require reflection or CompilerServices like CallerMemberName

e.g.
string method = $"{System.Reflection.MethodBase.GetCurrentMethod().DeclaringType.FullName}.{System.Reflection.MethodBase.GetCurrentMethod().Name}";

These options are long, cumbersome and for async method often get changed by the underlying implementation (e.g. MoveNext or OnResume). Also if the compiler decides to inline or optimize, these methods may interfere with that.

Is it possible to have a compiler directive like #Method that gets replaced at compile time with a string containing the currently compiling method?

So then we can write out the method entry e.g.
`Serilog.Log.Logger.Information("Starting #Method");`

Compiler directives were such a huge and useful part of C++ that seem to have been forgotten in C#.

**Comment by scalablecory** [comment]
This issue was moved to dotnet/csharplang#3389
