### ISSUE TITLE
I installed the SDK of .NET but it doesn´t seem to recognise it

### ISSUE THREAD

**Issue by MaroHer** [dotnet/core#4609]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

The installation went really fast like, not even 2 seconds. But it doesn't recognise de dotnet command.

**Comment by scalablecory** [comment]
Have you restarted your console windows? Path variables are updated that need to be refreshed.

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
