### ISSUE TITLE
Issue for running an app

### ISSUE THREAD

**Issue by satoryosuke4** [dotnet/core#4612]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello, my OS is Win 10, 
the error message after, input dotnet run is :

Program.cs(5,11): error CS0101: L'espace de noms 'myApp' contient déjà une définition pour 'Program' [C:\Users\Sato Ryosuke 4\myApp\myApp.csproj]
Program.cs(7,21): error CS0111: Le type 'Program' définit déjà un membre appelé 'Main' avec les mêmes types de paramètre [C:\Users\Sato Ryosuke 4\myApp\myApp.csproj]

La build a échoué. Corrigez les erreurs de la build et réexécutez-la.

**Comment by mairaw** [comment]
Can you paste the content of your cs file here? Maybe there's something wrong with the code.

Also, if you could take a screenshot of your file structure in the myApp folder.

Thanks!

**Comment by satoryosuke4** [comment]
Hello,

Thanks for the answer, this is the content of Program.cs

using System;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("The current time is " + DateTime.Now);
        }
    }
}

And, the attached Screenshot of myApp
[cid:image004.png@01D61A94.2D6739B0]


Provenance :

[cid:image001.png@01D558A8.D664FBF0]

Pour me joindre : courrier<mailto:satoryosuke4@outlook.fr> et site web<http://www.satoryosuke4.com>

De : Maira Wenzel<mailto:notifications@github.com>
Envoyé le :vendredi 24 avril 2020 22:41
À : dotnet/core<mailto:core@noreply.github.com>
Cc : satoryosuke4<mailto:satoryosuke4@outlook.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [dotnet/core] Issue for running an app (#4612)


Can you paste the content of your cs file here? Maybe there's something wrong with the code.

Also, if you could take a screenshot of your file structure in the myApp folder.

Thanks!

**Comment by mairaw** [comment]
The code looks correct. Screenshots cannot be sent via e-mail responses. You'd need to come to the GitHub UI to attach your image.

The other option would be to start over on a new directory and see if this would work.

**Comment by satoryosuke4** [comment]
![myApp 24_04_2020 23_56_42](https://user-images.githubusercontent.com/64251401/80271855-a5b47300-86c4-11ea-9bae-8dce3de3d326.png)

**Comment by satoryosuke4** [comment]
That's work. Thank you again.

**Comment by mairaw** [comment]
Are you still having issues or can this be closed?

**Comment by satoryosuke4** [comment]
Hello,

Yes, that work, now i can display the current time with the message Hello world.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Maira Wenzel<mailto:notifications@github.com>
Envoyé le :lundi 7 septembre 2020 21:14
À : dotnet/core<mailto:core@noreply.github.com>
Cc : Sato Ryosuke<mailto:satoryosuke4@outlook.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [dotnet/core] Issue for running an app (#4612)


Are you still having issues or can this be closed?

**Comment by mairaw** [comment]
Great to hear!
