### ISSUE TITLE
can't run .NET in cmb

### ISSUE THREAD

**Issue by sreenivasan1227** [dotnet/core#4614]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Have you restarted your command line windows? Environment variables are updated when you install, and need to be refreshed manually by restarting them.

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
