### ISSUE TITLE
az aks create needed --node-vm-size <value>  for westus region

### ISSUE THREAD

**Issue by hkommineni** [dotnet/core#4615]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

Below command worked after recieved default value is not supported for westus region.
az aks create --resource-group myMicroserviceResources --name myMicroserviceCluster --node-count 1 --enable-addons http_application_routing --node-vm-size Standard_D2s_v3 --generate-ssh-keys

**Comment by mairaw** [comment]
Duplicate of #4111
