### ISSUE TITLE
 Invalid input switch:   -0   ConsoleApp4

### ISSUE THREAD

**Issue by JairAguirre** [dotnet/core#4620]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JairAguirre** [comment]
i have this problem while i was creating the file of type console

**Comment by omajid** [comment]
This input switch is a lowercase letter "O" (`-o`, short for `--output`), not the number 0 (`-0`). I think you might be typing the number 0, incorrectly.

**Comment by mairaw** [comment]
@JairAguirre have you tried running the command with the letter o instead of zero to see if the problem goes away?

**Comment by JairAguirre** [comment]
> This input switch is a lowercase letter "O" (`-o`, short for `--output`), not the number 0 (`-0`). I think you might be typing the number 0, incorrectly.

Thanks!! that was the problem : D

**Comment by JairAguirre** [comment]
> @JairAguirre have you tried running the command with the letter o instead of zero to see if the problem goes away?

Thanks !
the problem goes away :D

**Comment by mairaw** [comment]
Awesome! So closing this issue.
