### ISSUE TITLE
MySql Connection Not Closed in docker linux

### ISSUE THREAD

**Issue by mohammadmoghadam70** [dotnet/core#4621]
Hi
i use mysql Connection in asp.net core 2.2 and open connection Successfully but when send close connection the connection not close 
i dont have any idea

**Comment by scalablecory** [comment]
You might be describing connection pooling, but without more info it's impossible to be certain. MysqlConnection is not an in-box type; you will want to file a support issue with whichever product you're using as they will have more in-depth knowledge.

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
