### ISSUE TITLE
Program.cs

### ISSUE THREAD

**Issue by vanshika1009** [dotnet/core#4622]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am facing an error "Access denied" if trying to open the file

**Comment by scalablecory** [comment]
What directory are you trying to create a project in?

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
