### ISSUE TITLE
Deploy to remote IIS Failed

### ISSUE THREAD

**Issue by EricPing** [dotnet/core#4624]
Hello all:

I have encountered a problem while using dotnet cli to deploy my app.

This is my deploy command

```powershell
dotnet publish -p:PublishProfile="PATH\Properties\PublishProfiles\Deploy.pubxml" 
```

This is my failed message

>C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): error : Package/Publish depends on Microsoft Web Deploy technology. Microsoft Web Deploy is not correctly installed on this machine. Please install from following link: For x86(32 bit): http://go.microsoft.com/fwlink/?LinkId=109365.For x64(64 bit): http://go.microsoft.com/fwlink/?LinkId=109366.. (3.6) [E:\APIService\APIService.csproj]

and this is my `Deploy.pubxml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is used by the publish/package process of your Web project. You can customize the behavior of this process
by editing this MSBuild file. In order to learn more about this please visit https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish>http://local.server/api</SiteUrlToLaunchAfterPublish>
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ProjectGuid>XXXXXXXXXXXX</ProjectGuid>
    <SelfContained>false</SelfContained>
    <MSDeployServiceURL>local.server</MSDeployServiceURL>
    <DeployIisAppPath>Default Web Site/api</DeployIisAppPath>
    <RemoteSitePhysicalPath />
    <SkipExtraFilesOnServer>True</SkipExtraFilesOnServer>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <EnableMSDeployBackup>False</EnableMSDeployBackup>
    <EnableMSDeployAppOffline>true</EnableMSDeployAppOffline>
    <UserName>USER</UserName>
    <Password>PASSWORD</Password>
    <AllowUntrustedCertificate>true</AllowUntrustedCertificate>
    <UseMSDeployExe>false</UseMSDeployExe>
    <_SavePWD>True</_SavePWD>
  </PropertyGroup>
</Project>
```

I have googled it, repaired dotnet core & WebDeploy 3.6, but not work.

I don't know how to solve this problem, please help! Thank you very much!

**Comment by scalablecory** [comment]
@wli3 @dsplaisted @Pilchie any ideas here?

**Comment by Pilchie** [comment]
Not sure.  Also tagging @vijayrkn though.

**Comment by vijayrkn** [comment]
Can you confirm if you have the MSDeploy V3 installed (default installation path is here - C:\Program Files\IIS\Microsoft Web Deploy V3)

**Comment by EricPing** [comment]
Dear @vijayrkn:

Yes I have the MSDeploy V3 installed in `C:\Program Files\IIS\Microsoft Web Deploy V3`

![image](https://user-images.githubusercontent.com/5001805/80432173-00003e80-8926-11ea-9e0f-f353d3e87ad7.png)

**Comment by EricPing** [comment]
Dear @vijayrkn:
Yes I have the MSDeploy V3 installed in `C:\Program Files\IIS\Microsoft Web Deploy V3`.

And I can use Visual Studio to Deploy, but command not work.

![image](https://user-images.githubusercontent.com/5001805/80432173-00003e80-8926-11ea-9e0f-f353d3e87ad7.png)

**Comment by vijayrkn** [comment]
Just noticed that you have set UseMsDeployExe to false. You need to set this to true if you are using dotnet publish. This is because the msdeploy dll does not target .NET Core. 
`    <UseMSDeployExe>false</UseMSDeployExe>`

Alternatively, you can use msbuild (full framework) to run the publish & this will be able to use the msdeploy apis directly. 

`msbuild WebApplication.csproj /p:DeployOnBuild=true /p:PublishProfile=<MsDeployProfile>`

**Comment by EricPing** [comment]
Dear @vijayrkn:

Thanks for your reply.

I set the `UseMSDeployExe` to `true` and run the command

```powershell
dotnet publish -p:PublishProfile="PATH\PublishProfiles\Jenkins.pubxml" --verbosity d
```
and get the result `System.MissingMethodException Method not found 'Void Microsoft.Web.Deployment.Tracing.WebDeployEventWriter.EventWriteVerbose(System.String, System.String, System.String)`

![image](https://user-images.githubusercontent.com/5001805/80433198-dd235980-8928-11ea-9561-92a80ac6cfd5.png)

Do you have any idea about this error? Thanks!

**Comment by vijayrkn** [comment]
Just tried this on a sample app and the command seems to be working fine 


```
C:\Users\<>\source\repos\WebApplication44\WebApplication44>dotnet publish /p:publishProfile=msdeploy /p:IsGetPasswordEnabled=true
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  WebApplication44 -> C:\Users\vramak\source\repos\WebApplication44\WebApplication44\bin\Debug\netcoreapp3.1\WebApplication44.dll
  WebApplication44 -> C:\Users\vramak\source\repos\WebApplication44\WebApplication44\bin\Debug\netcoreapp3.1\publish\
  Info: Using ID '73904947-cec6-46d6-8fc3-0b36a501d0be' for connections to the remote server.
  Info: Using ID '90ce9f98-7846-4e39-9d40-fabc49f574c0' for connections to the remote server.
  Info: Updating file (Anc21RazorWithRCLibCoreInd20200427094631\appsettings.Development.json).
  Info: Updating file (Anc21RazorWithRCLibCoreInd20200427094631\appsettings.json).
  Info: Updating file (Anc21RazorWithRCLibCoreInd20200427094631\web.config).
  Info: Adding file (Anc21RazorWithRCLibCoreInd20200427094631\WebApplication44.deps.json).
  Info: Adding file (Anc21RazorWithRCLibCoreInd20200427094631\WebApplication44.dll).
  Info: Adding file (Anc21RazorWithRCLibCoreInd20200427094631\WebApplication44.exe).
  Info: Adding file (Anc21RazorWithRCLibCoreInd20200427094631\WebApplication44.pdb).
  Info: Adding file (Anc21RazorWithRCLibCoreInd20200427094631\WebApplication44.runtimeconfig.json).
  Total changes: 8 (5 added, 0 deleted, 3 updated, 0 parameters changed, 284174 bytes copied)
  Publish Succeeded.
```

Alternatively, tried the msbuild equivalent and that also works: 

`msbuild /p:DeployOnBuild=true /p:publishProfile=msdeploy /p:IsGetPasswordEnabled=true`

Can you try running this outside the powershell? MsDeploy has had issues inside powershell in the past.

**Comment by EricPing** [comment]
Dear @vijayrkn 

I created a sample project and run two command using cmd.exe:

1. `dotnet publish /p:publishProfile=msdeploy /p:IsGetPasswordEnabled=true`
It's not worked because without `MsDeployServiceUrl` and `DeployIisAppPath`
So I changed it into 
```powershell
dotnet publish /p:publishProfile=msdeploy /p:IsGetPasswordEnabled=true /p:MsDeployServiceUrl=localhost /p:DeployIisAppPath=Ping/TestApp --verbosity d
```
And it still returned he result `System.MissingMethodException Method not found 'Void Microsoft.Web.Deployment.Tracing.WebDeployEventWriter.EventWriteVerbose(System.String, System.String, System.String)`

2. `msbuild /p:DeployOnBuild=true /p:publishProfile=msdeploy /p:IsGetPasswordEnabled=true`
It returned an error called `MSB4041`

**Comment by EricPing** [comment]
Dear @vijayrkn 

After I uninstall Web Deploy and re-install Web Deploy 4.0 by this link

https://developercommunity.visualstudio.com/solutions/330444/view.html

and it's worked!! But I don't know why.  Maybe it's because I have VS 2013 and VS 2019 on my computer...

Thanks for all your reply and help!! Thank you very much

**Comment by vijayrkn** [comment]
Glad to know reinstall fixed the issue.

**Comment by vijayrkn** [comment]
@EricPing - And by the way this property is only used if you have used VS to publish and a user file with encrypted password is present. otherwise you need to pass the password to the command.

`IsGetPasswordEnabled`
