### ISSUE TITLE
 error CS0234

### ISSUE THREAD

**Issue by RachelThevenard** [dotnet/core#4626]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

C:\Users\Admin\myApp>dotnet run
node_modules\selenium-webdriver\lib\test\data\Page.aspx.cs(4,40): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [C:\Users\Admin\myApp\myApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by RachelThevenard** [comment]
Fixed my own issue by changing directory to Desktop instead of User.... Idk why it worked.

**Comment by scalablecory** [comment]
It looks like you're missing a reference or setting an incorrect SDK type in your project file.

The tutorial you linked does not involve System.Web.UI; are you sure you linked the correct one?

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
