### ISSUE TITLE
 Attempted to update project that is not loaded!

### ISSUE THREAD

**Issue by bangugmark01** [dotnet/core#4627]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Can you please provide more detail? It's not clear what the issue is here, but it seems related to your editor.

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
