### ISSUE TITLE
Client browser: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by sunqiong1972** [dotnet/core#4632]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run

Host: Virtual Machine, linux(CentOS 7), no browser, IP: 192.168.1.199
Client: Notebook PC, Windows 10, Edge and Chrome, IP: 192.168.1.xxx

Detail:
Client browser -> http://192.168.1.199:5000 -> ERR_CONNECTION_REFUSED

Solution: 
Host -> /....../Properties/launchSettings.json -> "applicationUrl": "http://192.168.1.199:5000"
Host -> Enbale port -> firewall-cmd --permanent --add-port=5000/tcp -> firewall-cmd --reload

**Comment by scalablecory** [comment]
Thanks. I think the tutorial assumes you are running the server on the same machine as the client. I'm not sure if we want to over-complicate the tutorial by accounting for every "advanced" situation, but maybe something can be done. @mairaw

**Comment by mairaw** [comment]
Correct, this tutorial is meant to be run locally. Have you tried following the steps as described in the tutorial @sunqiong1972?

**Comment by sunqiong1972** [comment]
Sorry to reply late, because I tried to learn web development based on PHP, python, etc as a beginner recently. 
According to your reply, I tried it again, and it works correctly, thank you very much. 👍

**Comment by mairaw** [comment]
Great to hear!
