### ISSUE TITLE
localhost:5000 not opening

### ISSUE THREAD

**Issue by Surendra45** [dotnet/core#4633]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Can you please provide the console log when you run the server?

**Comment by Surendra45** [comment]
Hi,Sorry for the trouble,but I actually worked it out. I made a mistake but
finally I rectified it.

**Comment by mairaw** [comment]
Thank you for getting back to us. I'm glad it's working now.
