### ISSUE TITLE
the build has failed

### ISSUE THREAD

**Issue by briansas** [dotnet/core#4635]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by briansas** [comment]
Program.cs(12,18): error CS0101: The namespace 'myWebApp' already contains a definition for 'Program' [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Startup.cs(13,18): error CS0101: The namespace 'myWebApp' already contains a definition for 'Startup' [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Error.cshtml.cs(13,18): error CS0101: The namespace 'myWebApp.Pages' already contains a definition for 'ErrorModel' [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(11,18): error CS0101: The namespace 'myWebApp.Pages' already contains a definition for 'IndexModel' [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Privacy.cshtml.cs(11,18): error CS0101: The namespace 'myWebApp.Pages' already contains a definition for 'PrivacyModel' [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Program.cs(14,28): error CS0111: Type 'Program' already defines a member called 'Main' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Program.cs(19,36): error CS0111: Type 'Program' already defines a member called 'CreateHostBuilder' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Privacy.cshtml.cs(15,16): error CS0111: Type 'PrivacyModel' already defines a member called '.ctor' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Privacy.cshtml.cs(20,21): error CS0111: Type 'PrivacyModel' already defines a member called 'OnGet' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(15,16): error CS0111: Type 'IndexModel' already defines a member called '.ctor' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Index.cshtml.cs(20,21): error CS0111: Type 'IndexModel' already defines a member called 'OnGet' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Error.cshtml.cs(12,6): error CS0579: Duplicate 'ResponseCache' attribute [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Error.cshtml.cs(21,16): error CS0111: Type 'ErrorModel' already defines a member called '.ctor' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Pages\Error.cshtml.cs(26,21): error CS0111: Type 'ErrorModel' already defines a member called 'OnGet' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Startup.cs(15,16): error CS0111: Type 'Startup' already defines a member called '.ctor' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Startup.cs(23,21): error CS0111: Type 'Startup' already defines a member called 'ConfigureServices' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]
Startup.cs(29,21): error CS0111: Type 'Startup' already defines a member called 'Configure' with the same parameter types [C:\Users\MSI Gebruiker\myWebApp\myWebApp\myWebApp\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by mairaw** [comment]
There might be something wrong with your project since you seem to have many subdirectories called myWebApp. Maybe delete these folders and start over?

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more. We need to know if you tried again given your folder structure seems to have way too many levels of myWebApp folders. Maybe you tried the tutorial several times? Feel free to reopen if you have more info for us.
