### ISSUE TITLE
Can not install on Ubuntu20.04!

### ISSUE THREAD

**Issue by F-Unction** [dotnet/core#4640]
When i try to install it
```sh
下列软件包有未满足的依赖关系：
 dotnet-runtime-3.1 : 依赖: dotnet-runtime-deps-3.1 (>= 3.1.3) 但是它将不会被安装
``` 
`dotnet-runtime-3.1` depends on `dotnet-runtime-deps-3.1`
`dotnet-runtime-deps-3.1` depends on `libicu63`
But there is no libicu63 in Ubuntu20.04, only libicu66

**Comment by nielshenriksen** [comment]
I have same problem - It can be that 3.1 is not ready for 20.04 yet

**Comment by svick** [comment]
See https://github.com/dotnet/core/issues/4360. There are no official packages for Ubuntu 20.04 yet, though if you want, you can try the workarounds mentioned in that issue.

**Comment by mairaw** [comment]
Duplicate of #4360
