### ISSUE TITLE
Concurrent Execution of Single Executable on Linux Fails

### ISSUE THREAD

**Issue by mockjv** [dotnet/core#4644]
# Execution of a single executable (e.g., /p:PublishSingleFile=true) by multiple users on Linux results in an extraction failure.

# General

I first came across this while testing my build against CentOS 7, but I suspect this isn't limited to just CentOS 7.  Upon first execution, it appears the application files are extracted to /var/tmp/.net/<assembly name>/<potentially random string>

The permissions of the /var/tmp/.net directory are 0700 and owned by the first user that ran it.  As a result, if an additional user runs the same executable the extraction fails due to the permissions of /var/tmp/.net:
```
[test@localhost ~]$ /opt/myapp/myapp
Failure processing application bundle.
Failed to create directory [/var/tmp/.net/myapp/] for extracting bundled files
A fatal error was encountered. Could not extract contents of the bundle
```

The executable was built using .NET Core SDK 3.1.201.

This is easily reproducible by building the following as a single executable, and then trying to run it from multiple user accounts:
```
using System;
using System.Threading.Tasks;

namespace testApp
{
    class Program
    {
        async static Task Main(string[] args)
        {
            await Task.Delay(1000000);
        }
    }
}
```

Upon reading the "Single-File" design in [3.0](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md) vs. [5.0](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md), I do see that the goal is to no longer use the extraction based approach, so I suspect we wouldn't see that with 5.0p2.  That said, I doubt this is a desired behavior in 3.1 (LTS).

**Comment by omajid** [comment]
In the Fedora builds of .NET Core 3.1, we work around this issue by setting an environment variable to change the extraction directory to a per-user directory:

    export DOTNET_BUNDLE_EXTRACT_BASE_DIR=$HOME/.cache/dotnet_bundle_extract

See also https://github.com/dotnet/runtime/issues/35221

**Comment by mockjv** [comment]
Yea, I saw the potential work around but I also tend to agree with your [comment](https://github.com/dotnet/runtime/pull/2329#issuecomment-616797844) on (dotnet/runtime#35221)[https://github.com/dotnet/runtime/issues/35221] that it should potentially default to something less error-prone (at a minimum a reasonable fallback vs. the catastrophic failure).

For my particular case, knowing that the current mechanism results in extraction (additional space usage, and startup time), it makes the benefit of the single executable greatly reduced so I'm more inclined to publish without the single executable flag for the time being.

I just wanted it properly documented via an issue that the default mechanism in the LTS release produces startup errors in multi-user environments.

**Comment by swaroop-sridhar** [comment]
This issue is fixed in .net core 3.1.4
