### ISSUE TITLE
Cannot target .NET 5 in new project or any project

### ISSUE THREAD

**Issue by markus27183** [dotnet/core#4645]
I want to try to target .NET 5 in a C# console app.  But the highest .NET core I can target is 3.1. 

My version of Visual Studio is 16.5.4, when I check updates it says I'm at the latest update. 

Your web page says I need 16.6 preview, but the MSVS installer link doesn't give any way to update to 16.6. 

I have installed the SDK, .NET 5 and ASP .NET 5 packages, ran them, restarted, re-opened MSVS, still can't target .NET 5.

**Comment by svick** [comment]
You can't update from VS 16.5 to VS 16.6 preview, the preview installs side-by-side with the release version. If you go to https://visualstudio.microsoft.com/vs/preview/, download the preview installer from there and run it, does that work?

Alternatively, you could directly use .Net 5 preview without VS from the command line (possibly through VS Code).

**Comment by mairaw** [comment]
@svick is correct. You need a separate install of the VS preview version. Closing this issue.
