### ISSUE TITLE
Error trying https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit

### ISSUE THREAD

**Issue by jyizheng** [dotnet/core#4647]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Program.cs(10,56): error CS0103: The name 'DataTime' does not exist in the current context [/home/xxx/dotnet/myApp/myApp.csproj]

The build failed. Please fix the build errors and run again.

**Comment by svick** [comment]
This looks like you made a typo: it's <code>Dat<b>e</b>Time</code>, not <code>Dat<b>a</b>Time</code>.

**Comment by mairaw** [comment]
Closing since @svick's suggestion should fix the problem. Let us know if that's not the case.
