### ISSUE TITLE
【Terrible memory leak】 in dotnet core v3.1/3.0 Process.Start execute shell command 

### ISSUE THREAD

**Issue by irac-ding** [dotnet/core#4651]
Please Pay Attention !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
System: Ubuntu 18.04 / CentOS 7.6 / SUSE 15
SDK: 3.1.100

ex:

var psi = new ProcessStartInfo("dotnet");
psi.RedirectStandardOutput = true;

psi.Arguments = $"--version";
using (var proc = Process.Start(psi))
{
    var output = proc.StandardOutput.ReadToEnd();
    var version = output.Trim();

    if (!proc.HasExited)
    {
        proc.Kill();
    }
}

**Comment by irac-ding** [comment]
https://github.com/dotnet/core/issues/3989 has found the issue which over passed over half year?
There is no response. This is almost unacceptable !!!

**Comment by GrabYourPitchforks** [comment]
Please keep discussion in the original issue.
