### ISSUE TITLE
Microservice Demo Not Working. Build failure

### ISSUE THREAD

**Issue by swinterrowd-usbr** [dotnet/core#4652]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

C:\Users\swinterrowd\myMicroservice>docker build -t mymicroservice .
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=ijepzg6rki0deun0multd4yal&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

C:\Users\swinterrowd\myMicroservice>dir
 Volume in drive C is Windows (Primary)
 Volume Serial Number is 68DF-92C0

 Directory of C:\Users\swinterrowd\myMicroservice

05/06/2020  07:17 AM    <DIR>          .
05/06/2020  07:17 AM    <DIR>          ..
05/06/2020  07:17 AM                28 .dockerignore
05/06/2020  06:52 AM               162 appsettings.Development.json
05/06/2020  06:52 AM               192 appsettings.json
05/06/2020  06:56 AM    <DIR>          bin
05/06/2020  06:52 AM    <DIR>          Controllers
05/06/2020  07:15 AM               298 Dockerfile
05/06/2020  06:52 AM               150 myMicroservice.csproj
05/06/2020  06:56 AM    <DIR>          obj
05/06/2020  06:52 AM               722 Program.cs
05/06/2020  06:52 AM    <DIR>          Properties
05/06/2020  06:52 AM             1,383 Startup.cs
05/06/2020  06:52 AM               310 WeatherForecast.cs
               8 File(s)          3,245 bytes
               6 Dir(s)  374,172,352,512 bytes free

**Comment by scalablecory** [comment]
@swinterrowd-usbr, can you verify that you running an elevated command prompt as the error message suggests?
