### ISSUE TITLE
cannot recognise

### ISSUE THREAD

**Issue by hemalatayavarna** [dotnet/core#4654]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

C:\Users\Hemalatha_Yavarna>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by scalablecory** [comment]
Have you restarted any open command prompts? Environment variables have been updated as part of the install and need to be refreshed.
