### ISSUE TITLE
Broken Links on .NET Core SDK 1.0 RC3 download page

### ISSUE THREAD

**Issue by mikeball** [dotnet/core#466]
The links for the ubuntu binaries on the .NET Core SDK 1.0 RC3 build 004530 page below are broken. Following the links results in a site cannot be reached message. 

https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md

Here are the link addresses
https://go.microsoft.com/fwlink/?linkid=839636
https://go.microsoft.com/fwlink/?linkid=839628

The problem seems to exist on both linux and macos.

**Comment by leecow** [comment]
@mikeball - sorry for the inconvenience. Ubuntu links have been fixed up and are working now. Unless there's is a need to use the tarballs, installing from the deb feed as detailed on rc3-download https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md works well. 

Could you check the Mac link again? Seems to work for me.

**Comment by mikeball** [comment]
Links working great now. Yes, I need the tarball because I'm installing on Solus Linux and the ubuntu tarballs seems to work fine. Thanks!

**Comment by mikeball** [comment]
Sorry to re-open but it now appears that the Ubuntu 16.04 tarball may not be correct tarball.

dotnet-**dev**-debian-x64.1.0.0-rc3-004530.tar.gz
dotnet-**dev**-opensuse.13.2-x64.1.0.0-rc3-004530.tar.gz  
dotnet-**sdk**-ubuntu.16.04-x64.1.0.0-rc3-004530.tar.gz

Notice that the ubuntu file name is sdk, not dev?

It's not same folder structure as previous dotnet preview releases of ubuntu, nor the debian or opensuse tarball. When extracted, you get a directory "sdk", without a dotnet executable contained. I'm unable to locate a dotnet exectuable within ubuntu tarball.

**Comment by mikeball** [comment]
Ok, I see the download links have updated and now download what appear to be valid tarballs of the name "dotnet-dev-ubuntu.16.04-x64.1.0.0-rc3-004530.tar.gz". Thanks!
