### ISSUE TITLE
arjun

### ISSUE THREAD

**Issue by sharmaarjun1228** [dotnet/core#4661]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
