### ISSUE TITLE
Getting Error while adding Console.WriteLine("Hello World!"); Console.WriteLine("The current time is " + DateTime.Now);

### ISSUE THREAD

**Issue by Keshavjps28** [dotnet/core#4663]
Program.cs(13,9): error CS0116: A namespace cannot directly contain members such as fields or methods [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(13,19): error CS1031: Type expected [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(13,19): error CS8124: Tuple must contain at least two elements. [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(13,19): error CS1026: ) expected [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(13,19): error CS1022: Type or namespace definition, or end-of-file expected [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,9): error CS0116: A namespace cannot directly contain members such as fields or methods [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,20): error CS1031: Type expected [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,20): error CS8124: Tuple must contain at least two elements. [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,20): error CS1026: ) expected [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,20): error CS1022: Type or namespace definition, or end-of-file expected [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,53): error CS0116: A namespace cannot directly contain members such as fields or methods [/Users/keshavsingh/myApp/myApp.csproj]
Program.cs(14,56): error CS1022: Type or namespace definition, or end-of-file expected [/Users/keshavsingh/myApp/myApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by svick** [comment]
I get these errors when I follow [this tutorial](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit), but then I place the two lines at the very end of the file. But you're supposed to edit the code inside the `Main` method, so that it looks like this:

```c#
using System;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("The current time is " + DateTime.Now);
        }
    }
}
```

I wonder if the tutorial could make this clearer.
