### ISSUE TITLE
Can't install PowerShell on Ubuntu 20.04

### ISSUE THREAD

**Issue by superbonaci** [dotnet/core#4664]
PowerShell depends on this project to work on Ubuntu 20.04:
Issue: https://github.com/PowerShell/PowerShell/issues/12594

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/core/issues/4360. The official packages for Ubuntu 20.04 should be released on 12 May.

**Comment by superbonaci** [comment]
Thanks

**Comment by mairaw** [comment]
Duplicate of #4360

**Comment by mairaw** [comment]
Docs updates are in progress. You can see a draft at https://github.com/dotnet/docs/pull/18160/files
