### ISSUE TITLE
cant find index/page.cdhtml file

### ISSUE THREAD

**Issue by vishwah13** [dotnet/core#4665]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Thanks for your feedback @vishwah13! We plan on adding more context to these steps.
The file should be inside the myWebApp folder where you created your project.
