### ISSUE TITLE
Cannot execute dotnet on Debian 8.7

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core#467]
Moving from https://github.com/dotnet/cli/issues/5586 on behalf of @jinhale
CLI is Yet Another NetCore App, and underlying platform support is tied to dotnet core as a whole.

-----

## Steps to reproduce
Install Debian version 8.7 Linux (debian 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) i686 GNU/Linux)
Run the steps from https://www.microsoft.com/net/core#linuxdebian, but use su -c "#command" in place of sudo #command. 

## Expected  behavior
dotnet new should initialize a "Hello world!" CLI application.

## Actual behavior
bash: /usr/local/bin/dotnet: cannot execute binary file: Exec format error

## Environment data
`dotnet --info` output: 
bash: /usr/local/bin/dotnet: cannot execute binary file: Exec format error

**Comment by Petermarcu** [comment]
@gkhanna79, @janvorli , Can someone take a look at why we don't just work on 8.7?

**Comment by gkhanna79** [comment]
> Exec format error

@jinhale This error usually means that one is trying to execute binaries corresponding to an architecture that is not supported on the machine.  Can you please confirm that the host machine and binary architectures are the same? That said, please also help confirm the following:

1) Your steps above work on Debian 8.2
2) Are you able to use https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-linux-x64.latest.tar.gz on Debian 8.7 to execute a basic HelloWorld application?

**Comment by jinhale** [comment]
@gkhanna79 I'm currently using the i686 version, which may be the problem. I'll try Debian for AMD 64 and let you know if that fixes the problem. I'm not sure how to assess the binary architecture from https://go.microsoft.com/fwlink/?LinkID=835021. That appears to be a 64 bit binary when I tried to download it from my browser. I'm now guessing Microsoft assumes we all use a 64 bit processor and kernel.

**Comment by gkhanna79** [comment]
64bit binaries do require a 64bit machine running 64bit OS. Please do share your findings once you have tried the suggestion.

**Comment by Petermarcu** [comment]
@jinhale , yes, we have focused our attention on what gets the most people up and running. We haven't gotten to every processor, kernel, c library, etc version of Linux. We are more that happy to work with community members who want to help bring up builds for other things.

**Comment by jinhale** [comment]
I couldn't get a driver to work with the 64 bit version of Debian. I did get dotnet to work on 64 bit Fedora 24. I feel resolved on the issue. 

I would have liked to know before hand that dotnet was a 64-bit binary on Linux, but maybe I'm the only one that tried to install dotnet on a 32-bit Linux machine without realizing the dotnet binary was 64-bit.

**Comment by Petermarcu** [comment]
That is good feedback. Where were you downloading from? This set of pages? https://www.microsoft.com/net/core#linuxdebian

**Comment by Petermarcu** [comment]
Nevermind, I see you said that initially. I'll get your feedback to the folks that manage that site.

**Comment by gkhanna79** [comment]
@jinhale Please have a look at `Daily Build` section at https://github.com/dotnet/core-setup/blob/master/README.md that describes the architectures we support for various platforms.

**Comment by Petermarcu** [comment]
I'm going to close this. I opened an issue internally where the site is built to make sure it gets updated to clarify the x86, x64, etc on download links and instructions.

**Comment by chikehenderson** [comment]
I'm on old 32 bit hardware using debian 8, trying to get SOMETHING to run..

**Comment by Petermarcu** [comment]
We don't have an official build of x86 (32-bit) Linux.

**Comment by chikehenderson** [comment]
Ahhrghh!! ok do you have any suggestions.. or seen any workarounds by any
chance...

**Comment by chikehenderson** [comment]
Sounds interesting..

**Comment by Petermarcu** [comment]
@janvorli may also be able to give advice.

**Comment by chikehenderson** [comment]
Sure
