### ISSUE TITLE
.NET Core May 2020 Update - 2.1.18, 3.1.4 and 3.1.300 SDK

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#4675]
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.300-sdk.md)

[3.1.4 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.4.md)
[3.1.4 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.18 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.18/2.1.18.md)
[2.1.18 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-may-2020/)

Please report any issues you find with 2.1.18 or 3.1.4, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Status of availability of SDK on Linux feeds: 

| Distro | 3.1.300 | 3.1.4| 2.1.18 
|--|--|--|--|
| Ubuntu 16.04 |  ✅  |  ✅ | ✅  |
| Ubuntu 18.04 |  ✅ | ✅ |✅ |
| Ubuntu 19.10 |  ✅ |  ✅ | ✅ |
| Ubuntu 20.04 |  ✅ |  ✅ | ✅ |
| Centos 7    |  ✅  | ✅| ✅ |
| Debian 9   |  ✅   |  ✅| ✅ |
| Debian 10  |  ✅  | ✅ |✅ |
| Fedora 30  |  ✅   | ✅ |✅ |
| Fedora 31  |  ✅   | ✅ |✅ |
| Fedora 32  |  ✅   | ✅ |✅  |
| OpenSUSE 15 |  ✅  | ✅ | ✅ |
| SLES 12    |  ✅    | ✅  | ✅ |
| SLES15    |  ✅    | ✅  | ✅ |

-----
Here is a list of issues that we are tracking and working to resolve with the Feb 2020 release. We'll tick them off as each is resolved. See any linked issue for progress or resolution details.

- [x]  The release date on the [3.1 README](https://github.com/dotnet/core/blob/master/release-notes/3.1/README.md) is incorrect - Resolved by https://github.com/dotnet/core/pull/4678

**Comment by babelshift** [comment]
The release date on the [3.1 README](https://github.com/dotnet/core/blob/master/release-notes/3.1/README.md) shows as 3/24, but I assume it should be 5/12?

**Comment by mairaw** [comment]
Thanks @babelshift. I've opened #4678 for @rbhanda to review.

**Comment by Plasma** [comment]
I'm a bit lost how we update to this, a NuGet package update still shows `RuntimeInformation.FrameworkDescription` as 3.1.3 even though some pages did update.

Thank you

**Comment by MagicAndre1981** [comment]
What is fixed in the following packages?

_System.Collections.Immutable 1.7.1
System.IO.Pipelines 4.7.2
System.Reflection.Metadata 1.8.1
System.Text.Encoding.CodePages 4.7.1
System.Threading.Channels 4.7.1_

Normally I see them listed under [Packages updated in this release](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.18/2.1.18.md#packages-updated-in-this-release), but not this time.

Are they also part of 2.1.8 release?

**Comment by MagicAndre1981** [comment]
> What is fixed in the following packages?
> 
> _System.Collections.Immutable 1.7.1 System.IO.Pipelines 4.7.2 System.Reflection.Metadata 1.8.1 System.Text.Encoding.CodePages 4.7.1 System.Threading.Channels 4.7.1_
> 
> Normally I see them listed under [Packages updated in this release](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.18/2.1.18.md#packages-updated-in-this-release), but not this time.
> 

looks like they got updated because of [this pull request](https://github.com/dotnet/corefx/pull/42901) as I can see [in this version change](https://github.com/dotnet/corefx/pull/42901/files#diff-b995179dea2777d95e411456d77dafe8R5) but this PR is not listed in [the milestone](https://github.com/dotnet/corefx/pulls?q=milestone%3A3.1.4+label%3Aservicing-approved)

Now that I know what is changed I can test and commit the nuget updates

**Comment by MagicAndre1981** [comment]
@rbhanda thaks for updating the release notes, now [I see that the packages are part of 3.1.4 release](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.4.md#packages-updated-in-this-release)

**Comment by pmachapman** [comment]
Is there any word on when this update will be available for CentOS 8?

I realize that you don't host the RHEL8/CentOS8 packages on your own Linux feeds, but I imagine someone at Microsoft has some responsibility to make sure these make it to the AppStream repository?

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/4803

**Comment by rbhanda** [comment]
@pmachapman Centos 8 has been added as  supported OS with our latest release
