### ISSUE TITLE
Where did the UTF8Encoding class go in dotnet 3.1?

### ISSUE THREAD

**Issue by endian02** [dotnet/core#4687]
# Issue Title

Where did the UTF8Encoding class go in dotnet 3.1?

# General

I tried yesterday to upgrade one of my projects from dotnet 3.0 to 3.1, by changing in the .csproj file from 3.0 to 3.1.

It now fails to build from Visual Studio Community 2019 as it's missing the UTF8Encoding class (see below for full error message).

I have tried everything I could think of, adding a reference to the System.Text.Encoding.Extensions (as the message suggests) removing and completely reinstalling Visual Studio 2019 etc.

I also created a minimal library project which does nothing except create an instance of the above class but that one doesn't build either...

I checked the documenation at https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding?view=netcore-3.1 which indicates that it should still be there in 3.1.

What am I doing wrong?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1069	The type name 'UTF8Encoding' could not be found in the namespace 'System.Text'. This type has been forwarded to assembly 'System.Text.Encoding.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	ClassLibrary1	C:\Users\bk_ek\Source\repos\ClassLibrary1\ClassLibrary1\Class1.cs	9	Active

**Comment by svick** [comment]
Could you share that minimal library project that doesn't build? I tried the following and it works for me in VS 2019 version 16.5.4:

.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- try all common library TFMs -->
    <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>

</Project>
```

.cs:

```c#
using System.Text;

class C
{
    void M() => new UTF8Encoding();
}
```

**Comment by endian02** [comment]
.csproj: 

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
`

.cs
`using System;
using System.IO;
using System.Text;

namespace ClassLibrary1
{
  public class Class1
  {
    UTF8Encoding encoder = new UTF8Encoding(true, true);
  }
}
`

**Comment by endian02** [comment]
I see that the xml code was destroyed in upload however. Please let me know how to send it if you can't read it...

**Comment by svick** [comment]
@endian02 You should enclose code in triple backticks (` ``` `), e.g.:

````
```
<foo>
```
````

This shows as:

```
<foo>
```

**Comment by svick** [comment]
@endian02 When I tried your code (I was able to get the destroyed XML), it still compiled fine for me, which means there is likely something different between out computers. What exact version of VS are you using? (You can see that in Help → About.) And what versions of the .Net Core SDK do you have? (You can see that by running `dotnet --info` from the command line in the folder with your code.)

Also, are you getting any warnings along with the error you reported?

**Comment by endian02** [comment]
Microsoft Visual Studio Community 2019
Version 16.5.5

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

And this is the complete error list from my small project


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1069	The type name 'UTF8Encoding' could not be found in the namespace 'System.Text'. This type has been forwarded to assembly 'System.Text.Encoding.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	ClassLibrary1	C:\Users\bk_ek\Source\repos\ClassLibrary1\ClassLibrary1\Class1.cs	9	Active
Error	CS1069	The type name 'UTF8Encoding' could not be found in the namespace 'System.Text'. This type has been forwarded to assembly 'System.Text.Encoding.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	ClassLibrary1	C:\Users\bk_ek\Source\repos\ClassLibrary1\ClassLibrary1\Class1.cs	9	Active
Warning	MSB3106	Assembly strong name "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.IO.UnmanagedMemoryStream.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).	ClassLibrary1	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2081	
Warning	MSB3106	Assembly strong name "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Encoding.Extensions.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).	ClassLibrary1	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2081

**Comment by svick** [comment]
Ok, that warning was useful: I was able to reproduce the error, if I deleted the file C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Encoding.Extensions.dll from my computer. I think this means that your installation of .Net Core got somehow corrupted.

Can you [download the installer for .Net Core 3.1 SDK](https://dotnet.microsoft.com/download) and running it in repair mode? That restored the file for me (even though it then reported an error).

**Comment by endian02** [comment]
Thanks! This helped! Now it builds again!
