### ISSUE TITLE
vsCode problem

### ISSUE THREAD

**Issue by TAIGERMOS** [dotnet/core#4689]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
<img width="1680" alt="屏幕快照 2020-05-17 下午1 03 41" src="https://user-images.githubusercontent.com/54896690/82136335-76b29c80-983f-11ea-858e-4aaa796d920e.png">
?????

**Comment by svick** [comment]
I think you've found a bug in `dotnet run`: it doesn't work when your path contains a directory that ends with a period (in your case, `taigermos.`). I can reproduce it on Ubuntu:

```
~$ mkdir 'app.'
~$ cd app./
~$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/svick/app./app..csproj...
  Restore completed in 183.13 ms for /home/svick/app./app..csproj.

Restore succeeded.

~/app.$ dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/home/svick/app./bin/Debug/netcoreapp3.0/app..dll'. The system cannot find the file specified.

File name: '/home/svick/app./bin/Debug/netcoreapp3.0/app..dll'
```

Can you try running the tutorial in another directory, that's not under your home directory?

**Comment by TAIGERMOS** [comment]
> 至于错误，它似乎已在.Net 5中修复。

thanks
