### ISSUE TITLE
Suggestion - lexical ordering and reflection.

### ISSUE THREAD

**Issue by Korporal** [dotnet/core#469]
Hi,

There's no official way to reflect on a type and get (say) public properties in their lexical (declared) order. Many articles and utilities rely on ordering by MetadataToken and although this seems to work, is sometimes regarded as risky and potentially breaking in a future release.

However lexical ordering is extremely useful and quite natural for many applications so providing a way to do this that has official support would be superb.

(For example we have Dapper utility code that formats SQL queries with {0} and {1} etc where parameters are expected and then use reflection to replace these with @<some_property_name> ensuring the SQL text always contains a parameter name that exactly matches the anonymous object's property name, 0 being the first property, 1 the second etc.).

I guess you could either flatly commit to honoring the MetadataToken and say that this will always be the same as the lexical order or perhaps introduce a new property on the Type class LexicalPosition where 0 indicates the first declared property, 1 the second and so on.

If this integer was assigned increasingly based on lexical order of members (whether they be fields, properties, public private etc) then this would work - getting all public properties ordered by LexicalPosition would always order correctly.

A new member could be added to **BindingFlags** - **LexicalOrder** to get stuff in lexical order, not setting this would cause it to behave as it does now - ensuring backward compatibility for existing code that uses reflection.

I'm posting this here because it is the compiler that will know this lexical order as it processes the token stream.

One could argue that writing code which depends on lexical order is risky but it would be no more risky than writing code that depends on a the spelling of a property.

Thanks.

(I originally posted this in the roslyn repo https://github.com/dotnet/roslyn/issues/16733 but I guess it really requires changes lower down, although it would be the compiler that "knows" the lexical order (since it is aware of the token stream) it needs to persist that in the type info generated by the compilation process much as it does now with metadata token)

**Comment by Petermarcu** [comment]
@terrajobst @weshaggard , is this one for corefx?

**Comment by weshaggard** [comment]
Reflection simply reads it in the order they are put in the PE file the compiler is the right place to try and get this ordering so https://github.com/dotnet/roslyn/issues/16733 is the place continue this conversation.

**Comment by hgleaves-ncuadmin** [comment]
@Petermarcu @weshaggard 
I'm not sure that is a 100% compiler only change. What I'm suggesting is we modify reflection logic to provide an additional ordering option (so that we provide backward compatibility). If we change the compiler so that it writes stuff in a different ordinal manner then this changes existing behavior, which I'm not advocating.

As I see things we need this:

1. CLR/.Net Type change to include an additional data member "LexicalPosition" (0, 1, 2, etc)
1. Compiler changes to record a members lexical order by populating "LexicalPosition"
3. CLR/.Net change to support a new BindingFlags value "LexicalOrder".

I'm unfamiliar with the innards of this so apologies if this is simplistic/unrealistic.

**Comment by hgleaves-ncuadmin** [comment]
@Petermarcu @weshaggard 
Alternatively someone could take steps to commit to the view that current MetadataToken ordering is in fact the same as lexical ordering and takes steps to ensure this remains in force, then existing behavior will remain unchanged and we can all understand - going forward - that ordering by MetadataToken is garuanteed to always be the lexical order (as many believe to be the case today).

**Comment by weshaggard** [comment]
I agree this crosses many boundaries but it has to first start with the CLI spec and then the compiler then the runtime. However I think it is still best to start the conversation in the roslyn repo.

**Comment by Korporal** [comment]
@weshaggard - I did start it in the roslyn repo here:
https://github.com/dotnet/roslyn/issues/16733

I need some guidance please as to which repo I should really be directing this to, currently the discussion/issue has been closed in both places !

**Comment by karelz** [comment]
@Korporal do you need lexical order, or just any stable order?
Do you mean by lexical the order in which properties/fields/methods are defined in C# source code?

**Comment by hgleaves-ncuadmin** [comment]
@karelz - Hi.

I'm seeking to get reflected members in their lexical order (i.e. ordered by the declared name token's absolute offset in the source file). Every (validly) declared property or field has a name and that name text begins at some offset into the source file.

If this were recorded as part of the member's metadata (during the tokenize processing) then it would be trivial to use reflection and get the members in the desired order (...Orderby(PropertyInfo.SourceOffset)).

As I mentioned above, we have code (that works but assumes MetadatToken order is what we want) that makes it very natural to use the declared order.

**Comment by Korporal** [comment]
@karelz - Hi.

I'm seeking to get reflected members in their lexical order (i.e. ordered by the declared name token's absolute offset in the source file). Every (validly) declared property or field has a name and that name text begins at some offset into the source file.

If this were recorded as part of the member's metadata (during the tokenize processing) then it would be trivial to use reflection and get the members in the desired order (...Orderby(PropertyInfo.SourceOffset)).

As I mentioned above, we have code (that works but assumes MetadatToken order is what we want) that makes it very natural to use the declared order.

**Comment by Korporal** [comment]
Line 4165 here: https://github.com/dotnet/roslyn/blob/282679022963c053b7c2553b8e18faa6836e770b/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs

Use MetadataToken in a test.

**Comment by karelz** [comment]
So how is it supposed to work with partial classes? Which one takes precedence?

How common is the scenario? How many apps really need it?

**Comment by Korporal** [comment]
Actually this may be enough:
http://stackoverflow.com/questions/9062235/get-properties-in-order-of-declaration-using-reflection

**Comment by karelz** [comment]
Sorry, I don't follow how it answers my questions ...

**Comment by Korporal** [comment]
@karelz - Well I never said it should work with partial classes, but if that too were a requirement then yes that's a great question. The core use case is for situations where we use stuff like Dapper - numerous POCO classes.

**Comment by karelz** [comment]
@Korporal every feature has to be thought through all angles, we cannot design only for a few use cases.
Sadly, I don't know what Dapper is and what are POCO classes.
Please provide clear short description of the use case and how common it is and why it cannot be worked around.

**Comment by Korporal** [comment]
@karelz - A use case that has come up where I work is this (mentioned in my OP):

"(For example we have Dapper utility code that formats SQL queries with {0} and {1} etc where parameters are expected and then use reflection to replace these with @<some_property_name> ensuring the SQL text always contains a parameter name that exactly matches the anonymous object's property name, 0 being the first property, 1 the second etc.)."

In this example an anonymous object is passed in (with a sequence of properties that are assigned values in the initializer).

Consider this:

    string query = "select something from somewhere wehere a = {0} and b = {1} and c = {2}";
    string f = Parameters.Parameterize(query, new { Username = "Tony", Department = "Admin", Group = "Seniors" });

In this code the query text does not need to include the property names used in the anonymous class, indeed it doesn't care and is insensitive to them - the developer can call them what he wants:

    string query = "select something from somewhere wehere a = {0} and b = {1} and c = {2}";
    string f = Parameters.Parameterize(query, new { Junk = "Tony", Stuff = "Admin", Garbage = "Seniors" });

When the Parameterizew method completes the returned string in the second example is:

**"select something from somewhere wehere a = @Junk and b = @Stuff and c = @Rubbish"**

We (and many places too) have lots of code (and much of it old) that uses this kind of DB access, the queries in this code have hard-coded SQL parameter names (like in the output string above) and are hard to port and reuse and so on.

The above "Parameterize" method needs some way to order the properties it reflects from the anonymous type and lexical order is by far the most obvious and intuitive.

This is just one use case and there are more, currently we are discouraged from writing this kind of support code because reflection order is undefined - it need not be though.

**Comment by terrajobst** [comment]
You keep saying lexical order but it sounds like you want them to be returned in the order they were put in the source file. I don't think this definition would be sound (consider partial classes and code generation).

My opinion is that the order is generally undefined. This ensures we don't spend additional time sorting in case you don't care about sorting or need to apply your own sorting. Also, there are many ways to order members. For instance, many people want something like this:

* Order types by name and then by generic arity
* sort by kind (constructors, methods, properties, events, fields)
* Within each group, order by name and then by arity

I agree it's a useful thing to add and could be an extension methods over, say `IEnumerable<MemberInfo>`.

**Comment by Korporal** [comment]
@terrajobst - Hi, well consider my example above where an anonymous object is used (as in Dapper etc).

This is a real world requirement, since its an anonymous object we're not going to annotate members etc.

Also I'm not requesting sorting or ordering - but rather providing the metadata to _enable me_ to do sorting.

I use the phrase "lexical order" simply to mean the order that they're consumed by the compiler's lexical analyzer, yes I do mean declared order, offset within the source file etc.

**Comment by terrajobst** [comment]
> Also I'm not requesting sorting or ordering - but rather providing the metadata to enable me to do sorting.

The only think you'd have today is the token. There is nothing else recorded in the metadata that you could use. You could, however, read the PDB data and use the file and line information. I think our new PDB format has line information for everything, even if there is no code, but I might be wrong.

> Yes partial classes do raise questions but lets leave these aside for now (in my example of course the class is small and anonymous).

I'm not sure we can leave that out because it seems to me you're asking for a stable sort.

> so perhaps it's possible to review that code and say that yes MetadataToken order is - going forward - guaranteed to be source file order.

I don't think we're willing to make such a promise. The only guarantee we're giving you is the that there unique & stable when your'e building code using the deterministic option. /cc @tmat

**Comment by tmat** [comment]
>  I think our new PDB format has line information for everything

We haven't implemented that feature yet.

> MetadataToken order is - going forward - guaranteed to be source file order.

We can't guarantee that. In some scenarios, like Edit and Continue it is not true. Consider scenario when a member is added in between two other members during debugging.


Regarding the SQL scenario:

```
string query = "select something from somewhere wehere a = {0} and b = {1} and c = {2}";
string f = Parameters.Parameterize(query, new { Username = "Tony", Department = "Admin", Group = "Seniors" });
```

How about using tuples instead of anonymous types? 

```
string query = "select something from somewhere where a = {0} and b = {1} and c = {2}";
string f = Parameters.Parameterize(query, (Username: "Tony", Department: "Admin", Group: "Seniors" ));
```

Tuples have well defined ordering. You can easily read fields Item0, Item1, etc...

**Comment by tmat** [comment]
Just realized you won't be able to get the names from tuples like that. Maybe array of tuples?

```
string query = "select something from somewhere where a = {0} and b = {1} and c = {2}";
string f = Parameters.Parameterize(query, new[] { ("Username", "Tony"), ("Department", "Admin"), ("Group", "Seniors") });
```

**Comment by Korporal** [comment]
What I'm proposing is that we change either the CLR, the compiler or both to enable us to reflect items in their declared order. I'm not seeking a workaround as such but a change so that it becomes a supported capability in the CLR/Framework.

Most of the feedback is here is simply reiterating what we all already know - it can't be done today - what I'm asking is for is a change that allows us to do this. Surely this is not a hugely complicated thing? to be able to reflect a type's members in their declared order?

**Comment by Korporal** [comment]
From what I can deduce by some basic experiments the compiler seems to consume source files ordered by their file name spelling. So partial classes are then processed in that order and the members (when sorted by MetadataToken) seem to be ordered by a) source file name sort order then b) declaration order.

If this is true (I'm just experimenting) then perhaps that could be enforced so that going forward it is documented that partial classes "perceive" their member ordering to be as described above?

**Comment by terrajobst** [comment]
> Surely this is not a hugely complicated thing?

Any change affecting the metadata format isn't in the bag labeled "not hugely complicated things" ;-)

> If this is true (I'm just experimenting) then perhaps that could be enforced so that going forward it is documented that partial classes "perceive" their member ordering to be as described above?

I think what we're saying is that we're aren't seeing the value to be willing to make such a guarantee. Also, Roslyn is just one of our compilers. Mono has a separate C# compiler and there are many other compilers out there as well (such as F#). Even if we were to make the promise for Roslyn it wouldn't be a guarantee per ECMA335 spec (and adding additional constraints later is a breaking change from the existing spec). Of course, changes like this are doable in principle but I don't think we're seeing the value to justify such an impactful change.

On top of that, enforcing guarantees around token ordering might impose additional limitations we need to take into account as we're adding more constructs in the future. Assume, for instance, partial classes didn't exist and we made the guarantee you're asking for. Is adding partial classes now breaking the promise? I'd argue partial classes are much more useful than keeping the invariant you're asking for. That's another reason why I don't think we're willing to go down that path.

**Comment by svick** [comment]
@Korporal 

> the compiler seems to consume source files ordered by their file name spelling

I don't think that's true. I created a `partial` type `C`, declaring method `A` in A.cs and method `B` in B.cs, and put this code into `Main`:

```c#
foreach (var method in typeof(C).GetMethods(DeclaredOnly | Public | Instance))
{
    Console.WriteLine($"{method.MetadataToken:X} {method.Name}");
}
```

Then I ran `csc` on it, specifying the two files in different order and got:

```
PS C:\code\tmp\coreapp> csc .\Program.cs .\A.cs .\B.cs
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\code\tmp\coreapp> .\Program.exe
6000003 A
6000004 B
PS C:\code\tmp\coreapp> csc .\Program.cs .\B.cs .\A.cs
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\code\tmp\coreapp> .\Program.exe
6000003 B
6000004 A
```

(And I got the same result from version 2.3.0.61703 of `csc`.)

So it looks like it depends on the order the files are specified to the compiler, not on file names. (Tools like VS or `dotnet` might decide to order the files by name, but I don't think that's relevant here.)

**Comment by Korporal** [comment]
@terrajobst - Hi,

OK I guess this is dead in the water as a realistic expectation for future support. But I would argue that supporting this for non-partial types is better than not supporting it at all. 

After all saying "Ordering a type's reflected members by MetadataToken is guaranteed to order members in their declared order but only if the type is not a partial type." is rather a useful thing to be able to say. Like any feature there are limits on its flexibility.

This isn't a feature that's going to be used by every developer every day but the ability to get things in a predictable order like this is hugely useful when one does require it. 

If you look at the exposed properties of the [PropertyInfo ](https://msdn.microsoft.com/en-us/library/system.reflection.propertyinfo(v=vs.110).aspx)class from .Net 1.1 to today, there are quite a few properties that have been added over the years (e.g. [CustomAttributes](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.customattributes(v=vs.110).aspx), [ReflectedType](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.reflectedtype(v=vs.110).aspx)) old contracts are honored but those using new contracts get the new features - so we could in principle see a new property on a Type named (say) "SourceOffset" a long if the MetadataToken is too challenging as a way to do this.

All this amounts to is _implicit metadata_, as opposed to explicit metadata (attributes etc).  

As for the promise that would be simply what I outlined above - no guarantee is made for partial classes - simple as that, just like renaming a property in some class is not guaranteed to have no impact on XAML consumers of that class or other mechanisms that use reflection on that class.

I cannot say just how much effort is involved or what the pros/cons are for this - I am suggesting it and if it really is too hard to do then that's that !

Thanks for discussing this anyway, I'll consider this well and truly closed.

**Comment by terrajobst** [comment]
> As for the promise that would be simply what I outlined above - no guarantee is made for partial classes - simple as that, just like renaming a property in some class is not guaranteed to have no impact on XAML consumers of that class or other mechanisms that use reflection on that class.

Well, if you're happy with a "best effort" style solution than the current situation should already suit your needs as we largely (implicitly) follow the path you'd like. The difference is that it's not based on an explicit guarantee especially when other compilers are evolved.

**Comment by JMPSequeira** [comment]
Hey guys,
 
I know this is an old topic but I'd like to ask if it is safe to assume that local static functions will be assigned a metadata token greater than that of their containing method and less than any other method?
