### ISSUE TITLE
Raspbian ARM 64 .../dotnet/dotnet: No such file or directory

### ISSUE THREAD

**Issue by Ceron12** [dotnet/core#4694]
# General
Problem encountered after installing dotnet SDK 3.1 (arm64) on my raspberry pi.
Running dotnet results in No such file or directory

![image](https://user-images.githubusercontent.com/40286633/82148535-ed0dc980-9854-11ea-844c-b2ce75898144.png)

# Software Versions
- os: raspbian
- uname -a: Linux rpi1 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux  
- .net install arm 64: 
wget: https://download.visualstudio.microsoft.com/download/pr/15434752-2803-4722-b406-9a62d3e089d5/159bd7713f8a7ff82d7b2f756ae87f4f/dotnet-sdk-3.1.202-linux-arm64.tar.gz
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.1.202-linux-arm.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

**Comment by svick** [comment]
This looks like your `PATH` is not set correctly. Did you run the `export PATH=$PATH:$HOME/dotnet` command in the current terminal session? See the "tip" in [this article](https://docs.microsoft.com/en-us/dotnet/core/install/runtime?pivots=os-linux#download-and-manually-install-1) for more details.

**Comment by Ceron12** [comment]
@svick I did and after printing the path variable I get the following result:
![image](https://user-images.githubusercontent.com/40286633/82152507-010bf800-9862-11ea-9b10-1243f7b19d53.png)

**Comment by mairaw** [comment]
@leecow @joperezr can you help with this?

**Comment by dagood** [comment]
The error message seems a little strange to me:

```
pi@rpi1:~ $ dotnet -h
-bash: /home/pi/dotnet/dotnet: No such file or directory
```

If `PATH` were wrong, wouldn't it say something like: `bash: dotnet: command not found`?

And if it were the wrong arch, something like `bash: /home/pi/dotnet/dotnet: cannot execute binary file: Exec format error`?

I've got to wonder: what happens when you run the arm64 binary with its fully qualified path, so `PATH` isn't a factor? Is there some quirk of arm64, rpi, raspbian that I'm not aware of here?

Maybe running `set -x` before running the command would also tell us something, e.g. if there's some bash function interfering?

**Comment by dagood** [comment]
Oh, it does appear to be a quirk of running something that's been cross-compiled (`dotnet` is) on RPi, when something about the arch doesn't match up. https://unix.stackexchange.com/q/101429 has some more info and steps to diagnose.

**Comment by Ceron12** [comment]
@dagood Thanks for the fast response.

I tried to execute the following debug steps form your stackexchange link:
![image](https://user-images.githubusercontent.com/40286633/82162721-f6278680-98a6-11ea-9eb8-9c262a9d633c.png)

From what I read it is a mismatch between the architectures but that’s about all that I was able to do.
I tried to compile the SDK native on the pi but that failed due to the temp version of .net SDK not being found. Is there any way around this for example by using the 32bit version of the SDK to build the 64 bit one?

I also tried to build the SDK on my Windows PC without cross-compiling to see if the build.cmd would work. Sadly after following https://github.com/dotnet/sdk/blob/master/toolset/Documentation/project-docs/developer-guide.md I received two 401 errors form NuGet repositories. Is there a way around this and if so, how would I change over to cross-compiling?

![image](https://user-images.githubusercontent.com/40286633/82162811-7d74fa00-98a7-11ea-960e-de4e09265ae4.png)

**Comment by dagood** [comment]
The ".NET SDK" is not the dotnet/sdk repository, it's the product of a bunch of dotnet repos flowing into each other. Building dotnet/sdk downloads a prebuilt `dotnet` host, among other things: the same binaries you're trying to use now. It may be possible to build the .NET SDK from source using the orchestration infra in dotnet/source-build (some work was recently done to have it build on an arm64 host: https://github.com/dotnet/source-build/pull/1300), but this is not trivial to attempt.

About Raspbian--until recently, it was only available as a 32-bit OS. I'm seeing in some places that even the new version supports a 64-bit kernel, but still has 32-bit userland/user space. I'm not nearly an expert here: it is possible that's limiting which one you can run? What steps have you taken to get 64-bit support on your OS? (It looks like some people are installing Debian arm64 userland packages to supplement the Raspbian 32-bit ones?)

**Comment by dagood** [comment]
Silly me, I should have looked up instructions specific to .NET Core on linux-arm64 first. There's some very useful info out there about this exact scenario:
* https://gist.github.com/richlander/467813274cea8abc624553ee72b28213
* https://edi.wang/post/2019/9/29/setup-net-core-30-runtime-and-sdk-on-raspberry-pi-4

**Comment by Ceron12** [comment]
Sadly, I’m not able to switch over to ubuntu or any other distro due to k3s not being compatible. Therefore, I’ll use the 32bit version. Thanks a lot for your help.
