### ISSUE TITLE
dotnet not recognize in cmd 

### ISSUE THREAD

**Issue by infohaseeb** [dotnet/core#4698]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Annotation 2020-05-18 172230](https://user-images.githubusercontent.com/52865550/82212582-34b35480-992c-11ea-8312-3ba47feafaf4.png)

**Comment by mairaw** [comment]
It actually is recognizing. You typed dotnet and the command help appeared.

Did you try to continue the tutorial @haseebse?

**Comment by haseebse** [comment]
> It actually is recognizing. You typed dotnet and the command help appeared.
> 
> Did you try to continue the tutorial @haseebse?

YUP

**Comment by mairaw** [comment]
I'm assuming the issue was resolved, but please let us know otherwise.
