### ISSUE TITLE
WEC2013 on ARM7

### ISSUE THREAD

**Issue by GerhardKreuzer** [dotnet/core#47]
Hi,

any Chance to see .net core on ARM 7 Controllers, running WEC2013?

With best regards

Gerhard

**Comment by kika123** [comment]
Windows 10 IoT Core runs on the NT kernel and supports .NET Core
CE is near-abandonned now

**Comment by GerhardKreuzer** [comment]
Ok, but I have to use an ARMA5D3 MCU which is op-code compatible to ARMV7, as I found out. So is Win IOT running on that MCU or not? Is .net core running on that MCU or not?

With best regards

Gerhard

**Comment by kika123** [comment]
Do that MCU have a GIC(Cortex-A7,A9,A12,A15,A17 have one, but not the Cortex-A8)?
And does it have NEON?
If yes for both, then Windows IoT is relatively easy to run on the hardware

**Comment by kika123** [comment]
to clarify, you can run IoT on MCUs without NEON, but MS doesn't make interrupt controllers HAL extensions public

**Comment by GerhardKreuzer** [comment]
.. so there is no NEON on that chip. So what does this mean? I have to use SPI interface in slave mode and some serial lines.

 

With best regards

 

Gerhard

 

Von: Mohamed MEDIOUNI [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Februar 2016 09:50
An: dotnet/core
Cc: GerhardKreuzer
Betreff: Re: [core] WEC2013 on ARM7 (#47)

 

to clarify, you can run IoT on MCUs without NEON, but MS doesn't make interrupt controllers HAL extensions public

**Comment by GerhardKreuzer** [comment]
.. for what GIC stands for? Searched the manual, no hit …

 

Von: Mohamed MEDIOUNI [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Februar 2016 09:45
An: dotnet/core
Cc: GerhardKreuzer
Betreff: Re: [core] WEC2013 on ARM7 (#47)

 

Do that MCU have a GIC(Cortex-A7,A9,A12,A15,A17 have one, but not the Cortex-A8)?
And does it have NEON?
If yes for both, then Windows IoT is relatively easy to run on the hardware

**Comment by kika123** [comment]
GIC => Generic Interrupt Controller

**Comment by kika123** [comment]
no NEON means that you are screwed, as your core will only be able to run MinWin Windows 7 builds, that no one here is allowed to share(too strong NDAs)

**Comment by kika123** [comment]
sorry about the typo, I meant GIC, not NEON for  to clarify, you can run IoT on MCUs without NEON, but MS doesn't make interrupt controllers HAL extensions public 
newer Windows builds are compiled with NEON, which is an instruction set extension

**Comment by gkhanna79** [comment]
@richlander can comment on the overall platform support roadmap for .NET Core but supporting WinCE is not on the cards for now.

**Comment by blackdwarf** [comment]
I will close this issue due to lack of activity. @GerhardKreuzer if your answer was not satisfactory, can you please reopen this issue on dotnet/coreclr as that is a much better home for it. Thanks!
