### ISSUE TITLE
Incorrect file attributes for Debian 8 RC3 SDK binaries

### ISSUE THREAD

**Issue by benscobie** [dotnet/core#470]
For some reason the file attributes for the SDK .dlls & .exes shipped in the Debian 8 RC3 binary release are set to 600 which seems to only allow the file owner to execute dotnet commands. In 1.0.0-preview2-1-003177 these were set to 644. This is probably okay for a single user but not ideal for build servers (where I came across this issue).

A quick fix is to run `sudo find /opt/dotnet/sdk/1.0.0-rc3-004530/ -type f -name '*.dll' -exec chmod 644 {} \; ` & `sudo find /opt/dotnet/sdk/1.0.0-rc3-004530/ -type f -name '*.exe' -exec chmod 644 {} \; `

As this is a release/distribution issue I'm not sure which repository to log this issue in.

**Comment by leecow** [comment]
Thanks @benscobie. @Petermarcu, can you help route to the right person?

**Comment by benscobie** [comment]
Thanks @leecow - this is now also the case for RC4.

**Comment by Petermarcu** [comment]
@piotrpMSFT

**Comment by leecow** [comment]
Opened https://github.com/dotnet/cli/issues/5663 to track this.
