### ISSUE TITLE
Installing of aspnetcore-runtime-3.0-3.0.3-1.x86_64 failed on SLES 12 SP4

### ISSUE THREAD

**Issue by MatthiasBergen** [dotnet/core#4703]
Hi,

I am trying to install dotnet-sdk-3.0 on one of our customer systems that run on SLES 12 SP4. All dependencies are given however step 8/9 of the installing script fails every time with the following error:

> xxxxxx:/ # sudo zypper install dotnet-sdk-3.0
> 
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 
> The following 9 NEW packages are going to be installed:
>   aspnetcore-runtime-3.0 aspnetcore-targeting-pack-3.0 dotnet-apphost-pack-3.0 dotnet-host
>   dotnet-hostfxr-3.0 dotnet-runtime-3.0 dotnet-runtime-deps-3.0 dotnet-sdk-3.0
>   dotnet-targeting-pack-3.0
> 
> The following 9 packages have no support information from their vendor:
>   aspnetcore-runtime-3.0 aspnetcore-targeting-pack-3.0 dotnet-apphost-pack-3.0 dotnet-host
>   dotnet-hostfxr-3.0 dotnet-runtime-3.0 dotnet-runtime-deps-3.0 dotnet-sdk-3.0
>   dotnet-targeting-pack-3.0
> 
> 9 new packages to install.
> Overall download size: 105.0 MiB. Already cached: 0 B. After the operation, additional 105.0 MiB
> will be used.
> Continue? [y/n/...? shows all options] (y):
> Retrieving package dotnet-apphost-pack-3.0-3.0.3-1.x86_64      (1/9),  65.5 KiB ( 65.5 KiB unpacked)
> Retrieving: dotnet-apphost-pack-3.0.3-x64.rpm ................................................[done]
> dotnet-apphost-pack-3.0.3-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-apphost-pack-3.0-3.0.3-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): y
> Invalid answer 'y'. [a/r/i] (a): i
> Retrieving package dotnet-host-3.1.4-1.x86_64                  (2/9),  39.6 KiB (107.2 KiB unpacked)
> Retrieving: dotnet-host-3.1.4-x64.rpm ........................................................[done]
> dotnet-host-3.1.4-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-host-3.1.4-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package dotnet-runtime-deps-3.0-3.0.3-1.x86_64      (3/9),   2.8 KiB (  2.8 KiB unpacked)
> Retrieving: dotnet-runtime-deps-3.0.3-sles.12-x64.rpm ........................................[done]
> dotnet-runtime-deps-3.0.3-sles.12-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-runtime-deps-3.0-3.0.3-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package dotnet-targeting-pack-3.0-3.0.1-1.x86_64    (4/9),   3.4 MiB (  3.4 MiB unpacked)
> Retrieving: dotnet-targeting-pack-3.0.1-x64.rpm ..............................................[done]
> dotnet-targeting-pack-3.0.1-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-targeting-pack-3.0-3.0.1-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package dotnet-hostfxr-3.0-3.0.3-1.x86_64           (5/9), 146.8 KiB (146.8 KiB unpacked)
> Retrieving: dotnet-hostfxr-3.0.3-x64.rpm .....................................................[done]
> dotnet-hostfxr-3.0.3-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-hostfxr-3.0-3.0.3-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package aspnetcore-targeting-pack-3.0-3.0.1-1.x86_64
>                                                                (6/9),   1.4 MiB (  1.4 MiB unpacked)
> Retrieving: aspnetcore-targeting-pack-3.0.1.rpm ..............................................[done]
> aspnetcore-targeting-pack-3.0.1.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> aspnetcore-targeting-pack-3.0-3.0.1-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package dotnet-runtime-3.0-3.0.3-1.x86_64           (7/9),  28.6 MiB ( 28.6 MiB unpacked)
> Retrieving: dotnet-runtime-3.0.3-x64.rpm .....................................................[done]
> dotnet-runtime-3.0.3-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-runtime-3.0-3.0.3-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package aspnetcore-runtime-3.0-3.0.3-1.x86_64       (8/9),   7.0 MiB (  7.0 MiB unpacked)
> Retrieving: aspnetcore-runtime-3.0.3-x64.rpm .................................................[done]
> aspnetcore-runtime-3.0.3-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: BAD
>     MD5 digest: BAD Expected(1a85e86b73d6bb23c27e6651eb2140db) != (8c9e68a62a079f003a9c94e3faa179c5)
> 
> aspnetcore-runtime-3.0-3.0.3-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [2-Signature does not verify]
> Abort, retry, ignore? [a/r/i] (a): i
> Retrieving package dotnet-sdk-3.0-3.0.103-1.x86_64             (9/9),  64.3 MiB ( 64.3 MiB unpacked)
> Retrieving: dotnet-sdk-3.0.103-x64.rpm ..........................................[done (42.0 MiB/s)]
> dotnet-sdk-3.0.103-x64.rpm:
>     Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
>     V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> dotnet-sdk-3.0-3.0.103-1.x86_64 (packages-microsoft-com-prod): Signature verification failed [4-Signatures public key is not available]
> Abort, retry, ignore? [a/r/i] (a): i
> 
> Checking for file conflicts: .................................................................[done]
> (1/9) Installing: dotnet-apphost-pack-3.0-3.0.3-1.x86_64 .....................................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-apphost-pack-3.0.3-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (2/9) Installing: dotnet-host-3.1.4-1.x86_64 .................................................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-host-3.1.4-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (3/9) Installing: dotnet-runtime-deps-3.0-3.0.3-1.x86_64 .....................................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-runtime-deps-3.0.3-sles.12-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (4/9) Installing: dotnet-targeting-pack-3.0-3.0.1-1.x86_64 ...................................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-targeting-pack-3.0.1-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (5/9) Installing: dotnet-hostfxr-3.0-3.0.3-1.x86_64 ..........................................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-hostfxr-3.0.3-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (6/9) Installing: aspnetcore-targeting-pack-3.0-3.0.1-1.x86_64 ...............................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/aspnetcore-targeting-pack-3.0.1.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (7/9) Installing: dotnet-runtime-3.0-3.0.3-1.x86_64 ..........................................[done]
> Additional rpm output:
> warning: /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-runtime-3.0.3-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> 
> 
> (8/9) Installing: aspnetcore-runtime-3.0-3.0.3-1.x86_64 .....................................[error]
> Installation of aspnetcore-runtime-3.0-3.0.3-1.x86_64 failed:
> Error: Subprocess failed. Error: RPM failed: warning: /var/cache/zypp/packages/packages-microsoft-com-prod/aspnetcore-runtime-3.0.3-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
> **error: unpacking of archive failed on file /usr/share/dotnet/shared/Microsoft.AspNetCore.App/3.0.3/System.Security.Cryptography.Pkcs.dll;5ec3a74f: cpio: read failed - No such file or directory**
> error: aspnetcore-runtime-3.0-3.0.3-1.x86_64: install failed
> 
> Abort, retry, ignore? [a/r/i] (a):

despite the problem with signature verification failed, I can't run my dotnet webapi in that case.

Any suggestions?

**Comment by MatthiasBergen** [comment]
So..found a workaround for myself. I just took the missing files (total of 5) from the earlier version 3.0.2. Didn't find a way to exactly install this version instead of 3.0.3 via zypper so I just got the older files from another customer-system and copied them into 3.0.3 folder. 

My dotnet webapi now starts up..

it seems that the archive of 3.0.3 is some kind of broken. Don't know who can fix this.

**Comment by carlossanlop** [comment]
Apologies for the delayed response.  We have instructions to set-up zypper. https://learn.microsoft.com/en-us/dotnet/core/install/linux-sles 
3.x is currently out of support, but if you still repro this zypper problem in 6.0 or 7.0, please open a new issue.
