### ISSUE TITLE
Storing keys on non-Windows platforms

### ISSUE THREAD

**Issue by SCLDGit** [dotnet/core#4709]
# Issue Title

Question about how to store keys on non-Windows platforms

# General

While migrating some encryption code to be cross-platform capable, we're encountering some issues in instances where we would use the key store to retrieve RSA keys for use with AES encryption.

The important methods in question:

`
public void GenerateNewAsymmetricRsaKeyPair(string p_keyStoreContainerName)
{
    if (KeyExistsInKeyStoreContainer(p_keyStoreContainerName)) return;

    var cspParams = new CspParameters() { KeyContainerName = p_keyStoreContainerName, Flags = CspProviderFlags.UseMachineKeyStore };

    using var unused = new RSACryptoServiceProvider(2048, cspParams) { PersistKeyInCsp = true };
}
`

and

`
public byte[] AesEncryptStringToBytes(string p_keyStoreContainerName, string p_input)
        {
            using var rsaProvider = GetCryptoServiceProviderFromKeyStore(p_keyStoreContainerName);

            var inputBytes = Encoding.UTF8.GetBytes(p_input);
            using var aesProvider = new AesCryptoServiceProvider();
            aesProvider.GenerateIV();
            using var cryptoProvider = aesProvider.CreateEncryptor();
            var encrypt = cryptoProvider.TransformFinalBlock(inputBytes, 0, inputBytes.Length);

            var formatter = new RSAOAEPKeyExchangeFormatter(rsaProvider);
            var keyExchange = formatter.CreateKeyExchange(aesProvider.Key);

            // return the key exchange, the IV (public) and encrypted data
            var result = new byte[keyExchange.Length + aesProvider.IV.Length + encrypt.Length];
            Buffer.BlockCopy(keyExchange, 0, result, 0, keyExchange.Length);
            Buffer.BlockCopy(aesProvider.IV, 0, result, keyExchange.Length, aesProvider.IV.Length);
            Buffer.BlockCopy(encrypt, 0, result, keyExchange.Length + aesProvider.IV.Length, encrypt.Length);
            return result;
        }
`

Is there any equivalent on Linux and MacOS to using the machine keystore as we have done here? If not, what is the best practice for doing the same operations on Linux?

**Comment by bartonjs** [comment]
> Is there any equivalent on Linux and MacOS to using the machine keystore as we have done here? 

Not really.  The closest is just key import/export.  E.g.

```C#
byte[] pkcs8 = asymmetricKey.ExportPkcs8PrivateKey();
File.WriteAllBytes("your.rsa.pk8", pkcs8);
```

and

```C#
byte[] pkcs8 = File.ReadAllBytes("your.rsa.pk8");
RSA rsa = RSA.Create();
rsa.ImportPkcs8PrivateKey(pkcs8);
```

> what is the best practice for doing the same operations on Linux?

Usually the keys are just saved in a location where only the relevant user(s) have read permission, and they're loaded from files.  I don't know if it's a **best** practice, but it's probably the normal one :smile:.
