### ISSUE TITLE
'What is .NET Core?' page is down.

### ISSUE THREAD

**Issue by nikolenkoanton92** [dotnet/core#471]
Link to the page : https://www.microsoft.com/net/core/platform

**Comment by Petermarcu** [comment]
It works for me. Are you saying this link is down or one of the links on that page? https://www.microsoft.com/net/core/platform

**Comment by nikolenkoanton92** [comment]
@Petermarcu sorry cookie issue in chrome.

**Comment by Petermarcu** [comment]
ok :)
