### ISSUE TITLE
I am facing an issue while creating a web app directory in system32?

### ISSUE THREAD

**Issue by AshwaniYadav72** [dotnet/core#4720]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Try creating the app in your user folder. System32 is intended for Windows' system files and should not be used for documents or project files.
