### ISSUE TITLE
sudo apt-get install dotnet-sdk should install/update to SDK 3.1.300 not 3.1.201-1

### ISSUE THREAD

**Issue by solrevdev** [dotnet/core#4722]
# Issue Title

sudo apt-get install dotnet-sdk should install/update to SDK 3.1.300, not 3.1.201-1

So, is the latest version of dotnet-sdk in the apt-get repo and I just need to be patient or does something need to happen? 

It is available in the snap store but installing that does not get picked up by omnisharp or vscode and it just doesn't work as you expect so apt-get is the preferred way of installing/updating.

e.g this happens but should upgrade

```shell

sudo apt-get update 
sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dotnet-sdk-3.1 is already the newest version (3.1.201-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

# General

Environment:

```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

dotnet

```shell
dotnet --list-sdks
2.1.805 [/usr/share/dotnet/sdk]
2.2.402 [/usr/share/dotnet/sdk]
3.0.103 [/usr/share/dotnet/sdk]
3.1.201 [/usr/share/dotnet/sdk]

```

**Comment by svick** [comment]
When I follow [this guide](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910) to install the .Net Core SDK on Ubuntu 19.10, I get version 3.1.300:

> Setting up dotnet-sdk-3.1 (3.1.300-1)

Are you sure you're you're using up-to-date list of packages? You can refresh that by running `sudo apt-get update`.

**Comment by solrevdev** [comment]
> Are you sure you're you're using up-to-date list of packages? You can refresh that by running `sudo apt-get update`.

Sorry yes I should have said I’ve already done that, I’ve updated my question accordingly as well.

**Comment by svick** [comment]
What is the output of that `sudo apt-get update`? I think the repository for .Net Core moved in the past, so maybe you're still using the old repository? The output of `sudo apt-get update` should confirm that.

**Comment by solrevdev** [comment]
> What is the output of that `sudo apt-get update`? I think the repository for .Net Core moved in the past, so maybe you're still using the old repository? The output of `sudo apt-get update` should confirm that.

Here it is and thanks so much for helping by the way it’s appreciated 

```shell
sudo apt-get update Hit:1 http://gb.archive.ubuntu.com/ubuntu eoan InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]
Get:3 http://gb.archive.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu eoan-updates/main i386 Packages [209 kB]
Get:5 http://gb.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages [287 kB]
Get:6 http://gb.archive.ubuntu.com/ubuntu eoan-updates/universe i386 Packages [207 kB]
Get:7 http://gb.archive.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages [214 kB]
Get:8 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]
Hit:10 http://ppa.launchpad.net/peek-developers/stable/ubuntu eoan InRelease
Hit:11 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:12 http://ppa.launchpad.net/teejee2008/ppa/ubuntu eoan InRelease
Hit:13 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:9 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Fetched 1,201 kB in 11s (109 kB/s)                
Reading package lists... Done
```

**Comment by svick** [comment]
I don't see the Microsoft repository in that list, so I'm not sure where is your `dotnet-sdk-3.1` coming from. Can you add the Microsoft repository by following [the relevant section of the installation guide](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910#add-microsoft-repository-key-and-feed) and then trying again?

**Comment by solrevdev** [comment]
Aha! thank you! 

Even when I tried to run the following the repo would not appear in the list when apt-get update was ran.

```shell
wget https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

So I ran [stacer](https://oguzhaninan.github.io/Stacer-Web/) to quickly see what was going on and while the repo was listed it wasn't enabled for some reason so I went ahead and enabled it and that has worked!

![](https://i.imgur.com/4G4H6HH.png)

I now have the latest and greatest SDK installed. 👍

Do I need to worry about the warning **N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https:///packages.microsoft.com/ubuntu/19.10/prod eoan InRelease' doesn't support architecture 'i386'**?

```shell
sudo apt-get update
Hit:1 http://gb.archive.ubuntu.com/ubuntu eoan InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu eoan-updates InRelease
Get:3 http://gb.archive.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Get:4 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]                                                                     
Hit:5 http://ppa.launchpad.net/peek-developers/stable/ubuntu eoan InRelease                                                                   
Hit:6 http://ppa.launchpad.net/teejee2008/ppa/ubuntu eoan InRelease                                           
Hit:7 http://packages.microsoft.com/repos/vscode stable InRelease                        
Hit:8 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                   
Get:10 https://packages.microsoft.com/ubuntu/19.10/prod eoan InRelease [10.5 kB]                                                               
Get:11 https://packages.microsoft.com/ubuntu/19.10/prod eoan/main amd64 Packages [23.5 kB]                                                     
Hit:9 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                                                                        
Fetched 220 kB in 21s (10.7 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.microsoft.com/ubuntu/19.10/prod eoan InRelease' doesn't support architecture 'i386'

```
