### ISSUE TITLE
code coverage not available with 3.1.300

### ISSUE THREAD

**Issue by milbrandt** [dotnet/core#4725]
Following https://docs.microsoft.com/en-us/learn/modules/run-quality-tests-build-pipeline/6-perform-code-coverage with .NET core sdk 3.1.300 no code coverage is reported, already in `coverage.cobertura.xml` (see attachment) and also not on the Azure DevOps pipeline.

With sdk 3.1.100 the detailed report shows up including Azure DevOps.

For quick reference the link to the clone https://github.com/milbrandt/mslearn-tailspin-spacegame-web.git and commits:
- no report on 8b48d8e3f701932b07cb36d376b1ce92e4b81038
- report available 2af2da0057eb5e9fd51ba445c7dd0a5032fe5744

[coverage.cobertura.zip](https://github.com/dotnet/core/files/4664930/coverage.cobertura.zip)

**Comment by brockallen** [comment]
Same for me -- this has been a problem for months. Only the version that you get with the xUnit templates allows cover coverage to work.

**Comment by carlossanlop** [comment]
Apologies for the delayed answer. 3.x is out of support now. Are you still reproing this issue in 6.0 or 7.0?

**Comment by brockallen** [comment]
I've not seen this issue recently, no, but I also don't know if I have changed my behavior which might affect the observation of issue.
