### ISSUE TITLE
No package aspnetcore-runtime-3.1 available.

### ISSUE THREAD

**Issue by brsoft001** [dotnet/core#4730]
[root@i data]# sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
Retrieving https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:packages-microsoft-prod-1.0-1    ################################# [100%]
[root@i data]# sudo yum install aspnetcore-runtime-3.1
Loaded plugins: fastestmirror
Repository packages-microsoft-com-prod is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * remi-safe: mirrors.tuna.tsinghua.edu.cn
No package aspnetcore-runtime-3.1 available.
Error: Nothing to do
[root@i data]# yum install aspnetcore-runtime-3.1
Loaded plugins: fastestmirror
Repository packages-microsoft-com-prod is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * remi-safe: mirrors.tuna.tsinghua.edu.cn
No package aspnetcore-runtime-3.1 available.
Error: Nothing to do

**Comment by mairaw** [comment]
Closing since this is for a runtime no longer supported. Please open a new issue if this still repros with newer versions.
