### ISSUE TITLE
packages.microsoft.com not responding from several ISPs

### ISSUE THREAD

**Issue by renemadsen** [dotnet/core#4734]
None of the IP adresses rsolving for https://pacakges.microsoft.com works right now, so it's not possible to do an installation of dotnet core on ubuntu regardles of version.

wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
--2020-05-23 13:58:53--  https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 104.214.230.139
Connecting to packages.microsoft.com (packages.microsoft.com)|104.214.230.139|:443...failed: Connection timed out.
Retrying.

Expected it to work and not timeout.

**Comment by mikisid** [comment]
Same problem here, i resolve it with manual download and install packages-microsoft-prod.deb

**Comment by renemadsen** [comment]
> Same problem here, i resolve it with manual download and install packages-microsoft-prod.deb
> 
> :EDIT: Servers are unavailable sometimes, don't know why but it's work sometime. Maybe to weight servers to stabilise or do manual install.

I'm not even able to do that, not able to resolve the host or it gives error 500.

**Comment by mikisid** [comment]
You have to be persistent, the server is unstable but available from time to time.

**Comment by NikolaMilosavljevic** [comment]
@renemadsen are you still hitting this issue? I am not aware of any server mirror downtime, and the IP address you specified worked fine for me. The team that owns the server infrastructure could not confirm any server availability issues around the time you opened this issue.

**Comment by renemadsen** [comment]
> @renemadsen are you still hitting this issue? I am not aware of any server mirror downtime, and the IP address you specified worked fine for me. The team that owns the server infrastructure could not confirm any server availability issues around the time you opened this issue.

Hi @NikolaMilosavljevic No, the problem went away after something like 1 hour after I reported the issue. The problem was there at least 40 minutes before I reported the issue. So I was unable to install/update package doing that time.

It might not be server problems, it semed more like a network issue, no matter which IP was given, there where none or very little connectivity to the server.

**Comment by NikolaMilosavljevic** [comment]
> It might not be server problems, it semed more like a network issue, no matter which IP was given, there where none or very little connectivity to the server.

Thanks @renemadsen ! I will close this issue now. Feel free to reactivate it or create a new one, and ping me, in case you see this again.

**Comment by rolero** [comment]
FYI. Happening again. Not able to connect to packages.microsoft.com

**Comment by clystian** [comment]
I have same problem, installing deb manually repository is installed but packages.micosoft.com doesn't connect
```
Ign:14 https://packages.microsoft.com/ubuntu/21.04/prod hirsute InRelease
Err:15 https://packages.microsoft.com/ubuntu/21.04/prod hirsute Release
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.90.21.104 443]
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/ubuntu/21.04/prod hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by jstevense-vbe** [comment]
Same problem on Ubuntu 22.04 (WSL) . Have been trying for a day already.

**Comment by Bobsans** [comment]
And for now still having this issue for 22.04

**Comment by Finamore00** [comment]
Issue has surfaced again for Fedora 39. Can't seem to curl VSCode repo

**Comment by joshuaboniface** [comment]
It's also happening again here, but in our case, from GitHub Actions workers and my own system, over the last 4 days at least.

https://github.com/jellyfin/jellyfin-packaging/actions/runs/8461568587/job/23181631250#step:8:2092

```
joshua@base git:master ~/Projects/Jellyfin/projects/server/jellyfin-packaging $ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  bsdextrautils bsdutils containerd.io docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin dotnet-sdk-8.0 fdisk firefox-esr libblkid1 libfdisk1 libmount1 libsmartcols1 libuuid1 libwbclient0 mount nodejs util-linux
  uuid-runtime
20 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 110 MB/319 MB of archives.
After this operation, 4,129 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://packages.microsoft.com/debian/11/prod bullseye/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
  Connection failed [IP: 13.107.246.35 443]
E: Failed to fetch https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb  Connection failed [IP: 13.107.246.35 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This should definitely be reopened and checked by whoever is in charge of this infrastructure.

**Comment by joshuaboniface** [comment]
It's also happening again here, but in our case, from GitHub Actions workers and my own system, over the last 4 days at least. 


https://github.com/jellyfin/jellyfin-packaging/actions/runs/8461568587/job/23181631250#step:8:2092

```
joshua@base git:master ~/Projects/Jellyfin/projects/server/jellyfin-packaging $ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  bsdextrautils bsdutils containerd.io docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin dotnet-sdk-8.0 fdisk firefox-esr libblkid1 libfdisk1 libmount1 libsmartcols1 libuuid1 libwbclient0 mount nodejs util-linux
  uuid-runtime
20 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 110 MB/319 MB of archives.
After this operation, 4,129 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://packages.microsoft.com/debian/11/prod bullseye/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
  Connection failed [IP: 13.107.246.35 443]
E: Failed to fetch https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb  Connection failed [IP: 13.107.246.35 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

What's very curious though is that fetching the file with `wget` does work:

```
joshua@base git:master ~/Projects/Jellyfin/projects/server/jellyfin-packaging $ wget https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb 
--2024-04-01 01:07:22--  https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.107.213.35, 13.107.246.35, 2620:1ec:46::35, ...
Connecting to packages.microsoft.com (packages.microsoft.com)|13.107.213.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110251086 (105M) [application/octet-stream]
Saving to: ‘dotnet-sdk-8.0_8.0.203-1_amd64.deb’

dotnet-sdk-8.0_8.0.203-1_amd64.deb                            6%[========>                                                                                                                                  ]   6.85M  4.21MB/s               ^C
```

This should definitely be reopened and checked by whoever is in charge of this infrastructure. cc @NikolaMilosavljevic

**Comment by mike632t** [comment]
I found that updating `ca-certificates` resolved this issue.
