### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder184172198/myMicroservice.csproj: no such file or directory

### ISSUE THREAD

**Issue by gandhivishals** [dotnet/core#4735]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@shirhatti can you help here?

**Comment by shirhatti** [comment]
The most common issue here is that you probably is that your directory structure doesn't match what's specified in the tutorial. Your Dockerfile and csproj should be in the same directory which is probably not the case here.

If that isn't the case, feel free to re-open this issue and provide more information.
