### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by Michellejacob001** [dotnet/core#4738]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

How can we open Pages/Index.cshtml in a text editor

**Comment by mairaw** [comment]
You can open on any editor. You can use regular text editors like Notepad or code editors such as Visual Studio Code or Visual Studio.

Does that help?
