### ISSUE TITLE
dotnet issue 

### ISSUE THREAD

**Issue by purisha** [dotnet/core#4739]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What issue you're getting @purisha? 

Please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by purisha** [comment]
Hi everyone, I cannot find a dotnet for win 32
Thanks

**Comment by GrabYourPitchforks** [comment]
@purisha Can you please clarify the error you're receiving? Be sure to include your operating system version, __exact error message__, code sample, and anything else that is relevant.
