### ISSUE TITLE
dotnet at the prompt fails on ubuntu 18.4 hyper-v 

### ISSUE THREAD

**Issue by dcarlson661** [dotnet/core#4741]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What is the error message you're getting @dcarlson661?

**Comment by dcarlson661** [comment]
Hi Mairaw,
I stupidly didn't keep the message.   But I solved the issue by manually untarring the visual studio code archive in the ~/dotnet directory.

So this can be closed.  I was going to but my boss called with a different emergency so i didn't get to closing yet.

Thanks so much for your quick response.  I'll press "Close and comment" now

Dave Carlson
Valencia, Ca.

**Comment by mairaw** [comment]
No worries. Let us know if you run into any issues again.
