### ISSUE TITLE
The Framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found .net core 3.1 ubuntu

### ISSUE THREAD

**Issue by lcslouis** [dotnet/core#4743]
I have a very basic hello world type winforms app I built in visual studio 2019.

I installed .net core 3.1 runtime and sdk on ubuntu 20.04 using directions supplied from docs.ms website. 

When I try to run my application I get the error:

`The Framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found`

what do I need to do to get this to work

**Comment by svick** [comment]
You can't make it work, Winforms are only supported on Windows.

**Comment by scalablecory** [comment]
@svick is correct, the WinForms and WPF are both Windows-only. You might check out Xamarin.Forms (or, the upcoming .NET MAUI) which has some GTK# support.

**Comment by rustyx** [comment]
For cross-platform .NET UI, have a look at the [Avalonia](https://github.com/avaloniaui/avalonia) framework as an alternative to the Windows-only winforms.
