### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by clichte** [dotnet/core#4749]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: linux

I used the following command:
dotnet new webApp -o myWebApp --no-https

I got the following error:
No usable version of libssl was found
Aborted

I'm using Void Linux and I have the following ssl/tls packages installed:
libressl-3.0.2_2
libressl-devel-3.0.2_2
libssl47-3.0.2_2
libtls19-3.0.2_2

Thanks!

**Comment by clichte** [comment]
I tried the following command and it seems to be working now:
ln -s /usr/lib/libssl.so.47.0.6 /usr/lib/libssl.so.1.0.0

I'm not sure if this will result in any problems later.  Thanks for any help.

**Comment by omajid** [comment]
There's some more information at https://github.com/dotnet/runtime/issues/24869

**Comment by scalablecory** [comment]
I'm glad you found a solution. Please refer to the [dependencies](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux) to ensure you've got all the required prerequisites.

**Comment by dustinlacewell** [comment]
FWIW, the dependencies link in the comment above does not actually list what the native dependencies for running dotnet on linux actually are.

**Comment by mormonxyz** [comment]
I was trying to install PowerShell and had the same issue (_ No usable version of libssl was found_).
I installed a package named **libssl47** (available on Void Linux's official repository) and **pwsh** works fine now.

**Comment by albsen** [comment]
For futture me and anyone else searching this and ending up here.

Likely only an issue with your system not providing openssl-1 which dotnet 5.x expects.

Please note that you can always manually install these dependencies. In specific openssl-1.1.1-c can be installed using the following set of commands on most linux systems:

```
wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz
tar -xzvf openssl-1.1.1c.tar.gz
cd openssl-1.1.1c
./config
make
sudo make install (it puts it into /usr/local/lib so it doesn't mess with the rest of your system)
```

Messing with LD_LIBRARY_PATH is usually considered bad practice so please read up on how to do this on your linux in a better way!
Having said that, here is how to map this temporary via LD_LIBRARY_PATH:
```
LD_LIBRARY_PATH="/usr/local/lib" dotnet
# or
export export LD_LIBRARY_PATH="/usr/local/lib"
```

**Comment by benjamin-asdf** [comment]
Does somebody have a solution where I don't need to install an old openssl? I have libssl.so.3

CLR_OPENSSL_VERSION_OVERRIDE=3
export CLR_OPENSSL_VERSION_OVERRIDE

or

ln -s /usr/lib/libssl.so.3  /usr/lib/libssl.so.1.0.0

have the same effect

```
Cannot get required symbol ERR_put_error from libssl
```

I would settle for updating the LD path for dotnet. LD_LIBRARY_PATH
doesn't seem to have an effect

**Comment by omajid** [comment]
> Does anybody have a solution where I don't need to install an old openssl? 

If this is .NET Core 3.1, then no. There's no solution. .NET Core 3.1 just doesn't support OpenSSL 3.x, so you really do need to have an older version of OpenSSL (either 1.0 or 1.1) for it to work.

On the other hand, .NET Core 3.1 goes EOL next month. The newer supported releases - 6.0 and 7.0 - both support OpenSSL 3.0. Maybe you can think about moving to one of those supported releases 1 month early?

> `ln -s /usr/lib/libssl.so.3 /usr/lib/libssl.so.1.0.0`

Please don't do this. This file says "hey, over here! I am OpenSSL 1.0! use me!" .NET is fairly smart and errors out nicely. Another program may trust that claim and accidentally do something really bad.

**Comment by chylex** [comment]
Would https://github.com/dotnet/runtime/pull/80380 solve this issue?

**Comment by Ascyt** [comment]
Tried all the solutions above, still doesn't work

**Comment by s1lvershad0w** [comment]
Here's what worked for me on Ubuntu. Download "libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb" from [here](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/). 

To install run: sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb

**Comment by riddlocat** [comment]
On Fedora 32+ you can install [compat-openssl10](https://packages.fedoraproject.org/pkgs/compat-openssl10/) and everything should be fine😉

**Comment by Farazzaidi22** [comment]
> For futture me and anyone else searching this and ending up here.
> 
> Likely only an issue with your system not providing openssl-1 which dotnet 5.x expects.
> 
> Please note that you can always manually install these dependencies. In specific openssl-1.1.1-c can be installed using the following set of commands on most linux systems:
> 
> ```
> wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz
> tar -xzvf openssl-1.1.1c.tar.gz
> cd openssl-1.1.1c
> ./config
> make
> sudo make install (it puts it into /usr/local/lib so it doesn't mess with the rest of your system)
> ```
> 
> Messing with LD_LIBRARY_PATH is usually considered bad practice so please read up on how to do this on your linux in a better way! Having said that, here is how to map this temporary via LD_LIBRARY_PATH:
> 
> ```
> LD_LIBRARY_PATH="/usr/local/lib" dotnet
> # or
> export export LD_LIBRARY_PATH="/usr/local/lib"
> ```

This answer is great, however when I tried running 

```
openssl version
```
I got this error
`openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

To resolve this, we need to ensure that the system knows where to find the new libraries. Here are the steps to do so:

1. **Verify that the libraries are installed in `/usr/local/lib`:**
   ```bash
   ls -l /usr/local/lib | grep libssl
   ```

   You should see `libssl.so.1.1` and related libraries listed.

2. **Create a configuration file for the dynamic linker:**
   - Create a new file in the `/etc/ld.so.conf.d/` directory:
     ```bash
     sudo nano /etc/ld.so.conf.d/openssl-1.1.1c.conf
     ```

   - Add the following line to this file:
     ```bash
     /usr/local/lib
     ```

   - Save and exit the editor (Ctrl+X, then Y, then Enter).

3. **Update the dynamic linker run-time bindings:**
   ```bash
   sudo ldconfig
   ```

4. **Verify that the library path is updated:**
   - Run the following command to check if `ldconfig` has picked up the new libraries:
     ```bash
     ldconfig -p | grep libssl
     ```

   You should see entries for `/usr/local/lib/libssl.so.1.1` and similar libraries.

5. **Retry the OpenSSL version command:**
   ```bash
   openssl version
   ```

6. **Set the `LD_LIBRARY_PATH` environment variable (if necessary):**
   - Temporarily set `LD_LIBRARY_PATH` to include `/usr/local/lib`:
     ```bash
     export LD_LIBRARY_PATH=/usr/local/lib
     ```

   - Add this to your `~/.bashrc` or `~/.profile` for persistent changes:
     ```bash
     echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.bashrc
     source ~/.bashrc
     ```

7. **Verify the OpenSSL version again and try building your .NET application:**
   ```bash
   openssl version
   dotnet build
   ```

By following these steps, the system should recognize the newly installed OpenSSL libraries, allowing you to run `openssl` and `dotnet` commands without errors.

**Comment by ninianh** [comment]
don't use ubuntu-latest
let use runs-on: ubuntu-20.04

**Comment by michaelachrisco** [comment]
ubuntu-20.04 has now been deprecated in github actions, which breaks any ci/cd job that uses dotnet restore on older versions of dotnet. 

```
$ dotnet restore
No usable version of libssl was found
```
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

**Comment by michaelachrisco** [comment]
> - name: Install OpenSSL 1.1
>         run: |
>           wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
>           sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

When trying to use this, I am getting a 404 on 
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

**Comment by Jon2G** [comment]
Try with
`        
# sets up .NET SDK 9
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 9

    - name: Install OpenSSL 1.1
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb`

> > * name: Install OpenSSL 1.1
> >   run: |
> >   wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
> >   sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
> 
> When trying to use this, I am getting a 404 on http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

**Comment by CaseyHofland** [comment]
>       - name: Install OpenSSL 1.1
>         run: |
>           wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
>           sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

I'm trying to run this as well but I'm getting this error. Has anyone else encountered this?

```
Run wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
--2025-07-21 18:35:03--  http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
Resolving security.ubuntu.com (security.ubuntu.com)... 91.189.91.83, 185.125.190.83, 185.125.190.82, ...
Connecting to security.ubuntu.com (security.ubuntu.com)|91.189.91.83|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1323248 (1.3M) [application/vnd.debian.binary-package]
Saving to: ‘libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb’
     0K .......... .......... .......... .......... ..........  3%  751K 2s
    50K .......... .......... .......... .......... ..........  7% 1.57M 1s
   100K .......... .......... .......... .......... .......... 11% 2.84M 1s
   150K .......... .......... .......... .......... .......... 15% 2.82M 1s
   200K .......... .......... .......... .......... .......... 19% 3.33M 1s
   250K .......... .......... .......... .......... .......... 23% 6.54M 1s
   300K .......... .......... .......... .......... .......... 27% 7.11M 0s
   350K .......... .......... .......... .......... .......... 30% 8.01M 0s
   400K .......... .......... .......... .......... .......... 34% 8.57M 0s
   450K .......... .......... .......... .......... .......... 38% 8.04M 0s
   500K .......... .......... .......... .......... .......... 42% 9.35M 0s
   550K .......... .......... .......... .......... .......... 46% 11.8M 0s
   600K .......... .......... .......... .......... .......... 50% 10.9M 0s
   650K .......... .......... .......... .......... .......... 54% 17.5M 0s
   700K .......... .......... .......... .......... .......... 58% 13.6M 0s
   750K .......... .......... .......... .......... .......... 61% 15.4M 0s
   800K .......... .......... .......... .......... .......... 65% 17.6M 0s
   850K .......... .......... .......... .......... .......... 69% 18.4M 0s
   900K .......... .......... .......... .......... .......... 73% 27.4M 0s
   950K .......... .......... .......... .......... .......... 77% 19.8M 0s
  1000K .......... .......... .......... .......... .......... 81% 7.00M 0s
  1050K .......... .......... .......... .......... .......... 85% 21.3M 0s
  1100K .......... .......... .......... .......... .......... 88% 26.3M 0s
  1150K .......... .......... .......... .......... .......... 92% 32.4M 0s
  1200K .......... .......... .......... .......... .......... 96% 26.0M 0s
  1250K .......... .......... .......... .......... ..        100% 18.9M=0.2s
2025-07-21 18:35:04 (5.52 MB/s) - ‘libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb’ saved [1323248/1323248]
/home/runner/work/_temp/87fd9826-9c73-4df3-9eee-72f1cd69424b.sh: line 2: unexpected EOF while looking for matching ``'
Error: Process completed with exit code 2.
```

**Comment by CaseyHofland** [comment]
> > * name: Install OpenSSL 1.1
> >   run: |
> >   wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
> >   sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
> 
> When trying to use this, I am getting a 404 on http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

Did you try adding the env? Without it the install will fail.

```
    env:
      # Was getting an ICU not found error
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
```

**Comment by neptuwunium** [comment]
> When trying to use this, I am getting a 404 on
> http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
or
https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb

only replying here for people needing to use old dotnet versions for one reason or another.
