### ISSUE TITLE
Incorrectly identifying a null reference exception when referencing a value in the object initialiser

### ISSUE THREAD

**Issue by pcmichaels** [dotnet/core#4752]
# Issue Title

Incorrectly identifying a null reference exception when referencing a value in the object initialiser

# General

With a console app set-up with nullable reference types:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

The following code:

```
    class Test
    {
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
    }

    class Test2
    {
        public string? Name { get; set; }
        public string? Name2 { get; set; }
        public string? Name3 { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var x = new Test();

            RuntimeMethod(x);
        }

        private static void RuntimeMethod(Test x)
        {
            if (x == null) return;

            var test2 = new Test2()
            {
                Name = x.Name,
                Name2 = x?.Name2,
                Name3 = x.Name3
            };
        }
    }
```

Reports the line:

```
Name3 = x.Name3
```

As x may be null.  It appears that once the ? operator is used on x, everything after that is considered a possible null.

**Comment by mairaw** [comment]
@BillWagner @MadsTorgersen can you help with this question? It still repros with .NET 7.

**Comment by BillWagner** [comment]
Adding @RikkiGibson to check my work

I believe this is the correct behavior. The key part of the spec describes the null state of a [null conditional expression](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/nullable-reference-types-specification.md#null-conditional-expressions-).  Because `x` is a reference type, using `x?.` sets the null-state of `x` to *maybe-null*.

This can be closed.

**Comment by BillWagner** [comment]
Verified that the current behavior is correct.
