### ISSUE TITLE
 dotnet: command not found

### ISSUE THREAD

**Issue by francute2u** [dotnet/core#4758]
# Issue Title

 dotnet: command not found

# General

I have installed the .net core version. I dont know what version is it, I just downloaded the .net core and installed it few seconds ago. Operating System is MacOS Mojave.

here's the screenshot that I have successfully installed the .net core, when I type in dotnet in the terminal as instructed it says "command not found" and my mac details:

<img width="399" alt="screen3" src="https://user-images.githubusercontent.com/49874285/83266941-1b48bd00-a1f6-11ea-857c-eabc59cec0c2.png">
<img width="562" alt="screen2" src="https://user-images.githubusercontent.com/49874285/83266948-1d128080-a1f6-11ea-9250-76c95bd781a9.png">
<img width="619" alt="screen1" src="https://user-images.githubusercontent.com/49874285/83266954-1edc4400-a1f6-11ea-94ef-077e67ca2e3e.png">

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by mairaw** [comment]
Did you try to open a new terminal window after the installation? Sometimes that can help with the dotnet not found issue.

**Comment by MarcPhilippeJoly** [comment]
> Did you try to open a new terminal window after the installation? Sometimes that can help with the dotnet not found issue.

Same issue for me (-bash: dotnet: command not found), and opening a new terminal window doesn't fix it. 

Where is dotnet actually installed by the installer ?
What is the required context ?
Is it Intel Core 2 Duo compatible ? etc…

**Comment by jbaez001** [comment]
> Where is dotnet actually installed by the installer ?

Looks like "Summary" page of the installer tells you where it's being installed at. The 1st post for example, has a picture that shows that the installation was done in /usr/local/share/dotnet -- which matches what I have locally from a recent install. I added that locally to my PATH exports & good to go.
