### ISSUE TITLE
Problemas con .NET Framework

### ISSUE THREAD

**Issue by cfro3000** [dotnet/core#4760]
Parece que tengo problemas con el programa .NET y es que aunque instale la versión mas reciente cuando intento abrir programas que requieren de .NET no abren y no se si hay algo que bloquee o dañe el .NET

**Comment by carlossanlop** [comment]
Hola, necesitamos más información para poder ayudarte.
Qué pasos seguiste para instalarlo?
A qué te refieres con "intentar abrir el programa"?

-

Hello, we need more information to be able to help you.
What steps did you follow to install it?
What do you mean by "trying to open the program"?

**Comment by cfro3000** [comment]
> Hola, necesitamos más información para poder ayudarte.
> ¿Qué pasos seguiste para instalarlo?
> ¿A qué te refieres con "intentar abrir el programa"?
> 
> 
> Hola, necesitamos más información para poder ayudarte.
> ¿Qué pasos seguiste para instalarlo?
> ¿Qué quieres decir con "intentar abrir el programa"?

Seguí los pasos de instalación normales que aparecen al actualizarlo pero este problema ya lleva tiempo con el .NET que ya traía el dispositivo y por programas me refiero a juegos como Terraria o Borderlands 2 que requieren del .NET y también un actualizador de BIOS del dispositivo que requerían del .NET aunque también puede ser alguna actualización del Windows pero si encuentran alguna solución díganmela

**Comment by cfro3000** [comment]
> Hola, necesitamos más información para poder ayudarte.
> ¿Qué pasos seguiste para instalarlo?
> ¿A qué te refieres con "intentar abrir el programa"?
> 
> 
> Hola, necesitamos más información para poder ayudarte.
> ¿Qué pasos seguiste para instalarlo?
> ¿Qué quieres decir con "intentar abrir el programa"?

Creo que todo apunta a este error 0x80131040 Alguna solucion?
