### ISSUE TITLE
"dotnet run" error for starting up myApp in .NET EDIT: operating system is windows

### ISSUE THREAD

**Issue by mart64x2** [dotnet/core#4761]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

I got this code error when typing in " dotnet run " . Something to note is that I tried doing the .NET tutorial on the microsoft website before and it wouldnt work so I just deleted the SDK.NET file thing from my Files library on my pc. A couple days later I decided to try again so I redownloaded the same file and now I get this error message when I get to step 4 of this site, https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run .

All help is appreciated, thank you.

 The namespace 'myApp' already contains a definition for 'Program' [C:\Users\17802\myApp\myApp.csproj]
Program.cs(7,21): error CS0111: Type 'Program' already defines a member called 'Main' with the same parameter types [C:\Users\17802\myApp\myApp.csproj]

**Comment by mairaw** [comment]
Can you paste the content of your Program.cs file here for us to see?
