### ISSUE TITLE
Chrome nav

### ISSUE THREAD

**Issue by diegofernandini** [dotnet/core#4762]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi im using a win 8.1 os and up to date chrome nav, idk why but Chrome just shows a 
![Untitled](https://user-images.githubusercontent.com/63625708/83326707-d2b3f280-a23b-11ea-9310-46093adfbd89.png)
basic html textpage as interface rather than the one shown in the tutorial.

**Comment by mairaw** [comment]
@danroth27 @DamianEdwards any clues on what could have happened here?

**Comment by danroth27** [comment]
It looks like the app is running, but the Bootstrap CSS styles aren't getting download. 

@diegofernandini Can you check the browser dev tools and see if there are any errors in the browser console or the network tab?

**Comment by diegofernandini** [comment]
Hi, had to start it over and its working fine now, i totally left it and went to do something else, thanks for careing. I can continue learning .net now

**Comment by mairaw** [comment]
Great to hear @diegofernandini! I'm closing this issue then.
