### ISSUE TITLE
index cs editing error

### ISSUE THREAD

**Issue by diegofernandini** [dotnet/core#4763]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Did the cs step anyways and now it's messed up

![Untitled](https://user-images.githubusercontent.com/63625708/83326869-ee6bc880-a23c-11ea-98a7-a9aaa6f8095f.png)

**Comment by svick** [comment]
It looks like you put the code that's supposed to go into into Index.cshtml into the Index.cshtml.cs file. Can you try again, while making sure you edit only the Index.cshtml file?

**Comment by mairaw** [comment]
Or paste the contents of the file you edited so we can try to help you!
