### ISSUE TITLE
Can I run the project of. Net core 3.1 in Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by DevaloperHH** [dotnet/core#4767]
![image](https://user-images.githubusercontent.com/38316554/83349821-46ecb400-a36a-11ea-821d-5c522644c835.png)

**Comment by svick** [comment]
I don't know if this is what's causing your issue, but [.Net Core 3.1 is only supported on Ubuntu 16.04 and newer](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux#supported-operating-systems).
