### ISSUE TITLE
No templates matched the input template name: blazorwasm.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/core#4769]
Trying to run "dotnet new blazorwasm" gives: 

> No templates matched the input template name: blazorwasm.

Not sure what's wrong on my side?

**Comment by Youssef1313** [comment]
I've got it fixed thanks to [this blog](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/) by @danroth27.

Running the following command fixed it:

```
dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-rc1.20223.4
```

**Comment by danroth27** [comment]
@Youssef1313 The Blazor WebAssembly template is now included with the latest .NET Core 3.1 SDK, which is version 3.1.300. You can install it from here: https://dotnet.microsoft.com/download. If you have the 3.1.300 version of the SDK, then you don't need to separately install the Blazor WebAssembly template. You can verify that you have the correct version of the .NET Core SDK installed by running: `dotnet --version`
