### ISSUE TITLE
Unhandled Exceptions while trying to use System.Data.Odbc with reflection

### ISSUE THREAD

**Issue by chrisdecker1201** [dotnet/core#4776]
I've encounted a problem with my application where I had to load a component with dependencies to System.Data.Odbc. I'm using .NET Core 3.1.300 on a Windows 10 System (Build 17763)

In this repository I reproduced my issue, maybe someone has an idea what I could do.

https://gitlab.com/christian.decker/system_data_odbc_problems

In the .NET-Framework context everything works just fine, it must be an issue with .NET Core.

**Comment by benjohn88** [comment]
You could add the System.Data.Odbc as a package reference in your CLI project.
Something like
  <ItemGroup>
    <PackageReference Include="System.Data.Odbc" Version="4.7.0" />
  </ItemGroup>
in your CLI.csproj
