### ISSUE TITLE
Cant install dotnet core on ubuntu 16.04, apt-get update failed. Failed to fetch http://apt-mo.trafficmanager.net/repos/azurecore/dists/trusty/main/binary-amd64/Packages  Writing more data than expected (1982730 > 1975392)

### ISSUE THREAD

**Issue by mhatreabhay** [dotnet/core#4779]
# Issue Title
E: Failed to fetch http://packages.microsoft.com/repos/azurecore/dists/trusty/main/binary-amd64/Packages  Writing more data than expected (1995370 > 1975392)
E: Failed to fetch http://apt-mo.trafficmanager.net/repos/azurecore/dists/trusty/main/binary-amd64/Packages  Writing more data than expected (1982730 > 1975392)
E: Some index files failed to download. They have been ignored, or old ones used instead.

Be as descriptive as you can with your title.

# General

apt-get update is failing 

E: Failed to fetch http://packages.microsoft.com/repos/azurecore/dists/trusty/main/binary-amd64/Packages  Writing more data than expected (1995370 > 1975392)
E: Failed to fetch http://apt-mo.trafficmanager.net/repos/azurecore/dists/trusty/main/binary-amd64/Packages  Writing more data than expected (1982730 > 1975392)
E: Some index files failed to download. They have been ignored, or old ones used instead.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by richlander** [comment]
Did you follow these instructions: https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1604?

**Comment by mhatreabhay** [comment]
yes. current mitigation is to use bionic instead of trusty. product team is investigating package server state

**Comment by dagood** [comment]
> product team is investigating package server state

What do you mean by product team?

What was the full output of `apt update`? `http://packages.microsoft.com/repos/azurecore` is not involved with installing .NET Core on 16.04--if you only have the errors you're mentioning, you aren't blocked from installing .NET Core.

**Comment by StephenBonikowsky** [comment]
After further investigation the issue turned out not to be a .NET Core issue, this issue can be closed.
