### ISSUE TITLE
The application is unable to start correctly (0xc000007b)-dotnet.exe error.

### ISSUE THREAD

**Issue by vendhan0500** [dotnet/core#4780]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@vendhan0500 I'd probably try to uninstall and reinstall the SDK. Can you also make sure that you're installing the right version for your system (for example, ensure that you installed a 64-bit version on a 64-bit machine)?

You can try to post more information about your system, what you've installed, and when this error appears for us to try to help you.

**Comment by ssg** [comment]
This just happened to me now. 

![Screenshot](https://github.com/user-attachments/assets/5c264d26-b9c9-4202-a24b-f0957cee5fbf)
