### ISSUE TITLE
dotnet problem

### ISSUE THREAD

**Issue by Polenia** [dotnet/core#4782]
I have an issue with running dotnet, I installed it but when I checked if its okay with the command prompt and issued the command dotnet, it displayed a "dotnet is not recognized as …"

**Comment by mairaw** [comment]
Did you open a new command prompt after installing it?
Also, what have you installed? The dotnet runtime or SDK?

See if this article helps you:
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions
