### ISSUE TITLE
(.net core 3.1 app) The TCP server received an exception byte stream

### ISSUE THREAD

**Issue by youyouzaileizi** [dotnet/core#4783]
I developed a server APP with .net Core 3.1, which was compiled in Window7 and directly put into Linux platform to run. `SocketAsyncEventArgs` was used to handle network concurrency, but after the server ran for some time, the server received an abnormal byte stream.

The complete byte stream is:

    {0,0,0,164,255,83,77,66,114,0,0,0,0,8,1,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,6,0,0,1,0,0,129,0,2,80,67,32,78,69,84,87,79,82,75,32,80,82,79,71,82,65,77,32,49,46,48,0,2,77,73,67,82,79,83,79,70,84,32,78,69,84,87,79,82,75,83,32,49,46,48,51,0,2,77,73,67,82,79,83,79,70,84,32,78,69,84,87,79,82,75,83,32,51,46,48,0,2,76,65,78,77,65,78,49,46,48,0,2,76,77,49,46,50,88,48,48,50,0,2,83,97,109,98,97,0,2,78,84,32,76,65,78,77,65,78,32,49,46,48,0,2,78,84,32,76,77,32,48,46,49,50,0}

I tried to use ASCII parse it, the result is:

    {\0\0\0??SMBr\0\0\0\0\b\u0001@\0\0\0\0\0\0\0\0\0\0\0\0\0\0@\u0006\0\0\u0001\0\0?\0\u0002PC NETWORK PROGRAM 1.0\0\u0002MICROSOFT NETWORKS 1.03\0\u0002MICROSOFT NETWORKS 3.0\0\u0002LANMAN1.0\0\u0002LM1.2X002\0\u0002Samba\0\u0002NT LANMAN 1.0\0\u0002NT LM 0.12\0}

no idea what happened?

**Comment by scalablecory** [comment]
Can you provide a small repro? There isn't enough to go on here -- there could be a bug with your buffer management on either end, for instance.
