### ISSUE TITLE
load c/c++ dll fail with netcore 3.1.3 on win7(win10 worked)

### ISSUE THREAD

**Issue by heartacker** [dotnet/core#4784]
# Issue Title
there is a c/c++ dll built for target-x86  need to load in my wpf app;
and It works on OS_win10_x64,and doesn't work on OS_win7_x64

# General
```csharp
        [DllImport("kernel32.dll", EntryPoint = "LoadLibrary")]
        public static extern Int32 LoadLibrary([MarshalAs(UnmanagedType.LPStr)] String lpLibFileName);
```
there are the cases I try:
OS: Win10_x64, netcore runtime:3.1.300_x86, WPF:x86 ---> worked
OS: WIN7_X64, netcore runtime:3.1.300_x86,WPF:X86--->doesn't work,  LoadLibrary return ZERO;

**Comment by scalablecory** [comment]
Your signature for `LoadLibary` is incorrect. It should be:

```c#
[DllImport("kernel32.dll")]
public static extern IntPtr LoadLibrary(String lpLibFileName);
```

Can you please try again with this and see if you encounter an error?

**Comment by heartacker** [comment]
@scalablecory sorry，it doesn't work in win7 
with new signature, and still workes in win10:sob:

**Comment by heartacker** [comment]
The bug is solved after 'vcredist_x86_sp_2005'
thank for help

**Comment by scalablecory** [comment]
Thanks for following up! Glad you figured it out.
