### ISSUE TITLE
Should PInvoke marshall byte[] as pointer or array?

### ISSUE THREAD

**Issue by emmenlau** [dotnet/core#4787]
# General Summary

I'm not sure if what I'm seeing is a bug, or a mistake / misconception on my side. However I've spend more than a day, read anything I could find, tried hundreds of different parameters, and they all lead to the same "problem": A `byte[]` inside a struct only works when the corresponding C++ struct uses an array, not a pointer.

# Details and Motivation

I want to have an easy way to return an error code together with an error string from native code. To make it very convenient, I'd like to have these encapsulated in a struct. Many recommendations on the internet say that its better to pre-allocate memory in C# and pass it writable to C++, rather than allocating in C++. Since stringbuilders don't work inside structs, I assume a pre-allocated byte array is the best solution.

After much back and forth this is what I've come up with. The C# struct is:
```C#
[StructLayout(LayoutKind.Sequential)]
public struct ReturnStatus
{
    public int mErrorCode;
    public int mErrorMessageSize;

    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1024)]
    public byte[] mErrorMessage;

    public static ReturnStatus create()
    {
        ReturnStatus vReturnStatus = new ReturnStatus();
        vReturnStatus.mErrorMessage = new byte[1024];
        return vReturnStatus;
    }
}
```

In my understanding, the corresponding C++ struct should be:
```C++
struct ReturnStatus {
    int mErrorCode;
    int mErrorMessageSize;
    unsigned char* mErrorMessage;
};
```
However, this assumed-to-be-correct code produces two problems:
 * when passed by `ref`, the struct will always have `mErrorMessage` set to `nullptr` in C++, even though its allocated with `new` in C#
 * when passed with `[In, Out]` the struct is unwritable. Setting any field, even the integers, leads to a crash.

Confusingly, what works is the following C++ struct:
```C++
struct ReturnStatus {
    int mErrorCode;
    int mErrorMessageSize;
    unsigned char mErrorMessage[1024];
};
```

Passing this struct as `ref` works, the content from mErrorMessage are correctly passed from C# to C++ and back.

Can someone help me understand why this is correct, or what I'm doing wrong? According to everything I could find, the `byte[]` should be marshalled as an `unsigned char*`.

# Environment

I've observed this behavior in .NET Core 3.1 on Ubuntu Linux x86_64, macOS 10.15 XCode 11.5, and Windows 10 Visual Studio 2019 16.6 x64.

On Linux, I use:
```
#> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by KalleOlaviNiemitalo** [comment]
[Customizing array field marshaling (.NET guide)](<https://docs.microsoft.com/dotnet/standard/native-interop/customize-struct-marshaling#customizing-array-field-marshaling> "Customizing structure marshaling - .NET | Microsoft Docs") and [Arrays within Structures (.NET Framework)](<https://docs.microsoft.com/dotnet/framework/interop/default-marshaling-for-arrays#arrays-within-structures> "Default Marshaling for Arrays | Microsoft Docs") show that `UnmanagedType.ByValArray` causes the managed array to be marshaled as an array allocated within the unmanaged structure, not as a pointer.

**Comment by emmenlau** [comment]
I can see in [Arrays within Structures (.NET Framework)](https://docs.microsoft.com/dotnet/framework/interop/default-marshaling-for-arrays#arrays-within-structures) an example that marshalls arrays as arrays. Thanks for the clarification.
