### ISSUE TITLE
MSVCP71

### ISSUE THREAD

**Issue by hammaadmessi10** [dotnet/core#4791]
My problem is that this popup keeps coming up which is an error called msvcp71.
it says: 'The code exexution can not proceed because MSVCP71.dll was not found. Reinstalling the program may fix this problem.

**Comment by mairaw** [comment]
Can you give us more information? When does this error occur? Is it related to .NET?

**Comment by hammaadmessi10** [comment]
the matter is fixed now leave me alone you guys are literally giving me a
headache
