### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by leeroyrdsouza** [dotnet/core#4794]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

win 10 pro; chrome

 
**Using the external IP address, browse to http://[YOUR EXTERNAL IP ADDRESS]/WeatherForecast.**
 

**redid tutorial several times ; always get this at the end**

This site can’t be reached52.234.104.128 took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT
Check your Internet connection
Check any cables and reboot any routers, modems, or other network devices you may be using.
Allow Chrome to access the network in your firewall or antivirus settings.
If it is already listed as a program allowed to access the network, try removing it from the list and adding it again.
If you use a proxy server…
Check your proxy settings or contact your network administrator to make sure the proxy server is working. If you don't believe you should be using a proxy server: Go to the Chrome menu > Settings > Show advanced settings… > Change proxy settings… > LAN Settings and deselect "Use a proxy server for your LAN".

![Annotation 2020-06-08 054157](https://user-images.githubusercontent.com/65492263/84021762-d259dc80-a94a-11ea-84c8-c92802eaba7c.png)

**Comment by mairaw** [comment]
@shirhatti can you help here?

**Comment by sughosneo** [comment]
Hi @leeroyrdsouza, thank you for reaching out. 

Could you please check if the service is up and running? You can do that by using the following steps:

- Check the status of the deployment:
  `kubectl get deployment`

- Check the status of the service:
  `kubectl get svc`

You can also check the log of the pod by using the following steps.

- Fetch pod name :
  `kubectl get pods`

- And fetch the log using :
 `kubectl logs <pod_name_from_previous_step>`
