### ISSUE TITLE
path-to-application:   The path to an application .dll file to execute.after  installing .net core sdk 2.2  err in command promt while checking installation by dotnet command

### ISSUE THREAD

**Issue by duthEvo** [dotnet/core#4795]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you paste a screenshot of the error you're getting? And did you just install .NET Core SDK 2.2? Because our latest version is 3.1. The link on the tutorial should take you to install that instead.

**Comment by duthEvo** [comment]
yeah thanks for concern but issue resolved

**Comment by krwq** [comment]
Closing per comment above

**Comment by Marwa93mira** [comment]
@duthEvo  Hey, I have the same error can you share how you solve the problem?
