### ISSUE TITLE
Cannot uninstall DotNetCore.1.0.0-VS2015Tools.Preview2.exe

### ISSUE THREAD

**Issue by jivanova** [dotnet/core#480]
Uninstalling 1.0.0 leads to prompt for DotNetCore.1.0.0-VS2015Tools.Preview2.exe which has been deleted from the system. Where could I find it?

**Comment by benscobie** [comment]
Here's a download link for it: http://download.microsoft.com/download/A/3/8/A38489F3-9777-41DD-83F8-2CBDFAB2520C/DotNetCore.1.0.0-VS2015Tools.Preview2.exe

**Comment by Petermarcu** [comment]
I'm going to assume this was resolved and close it.
