### ISSUE TITLE
It was not possible to find any installed .NET Core SDKs

### ISSUE THREAD

**Issue by ashishsoni295** [dotnet/core#4800]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by ashishsoni295** [comment]
It was not possible to find any installed .NET Core SDKs

**Comment by mairaw** [comment]
What error message you're getting? Can you check what have you installed?

This doc goes over some ways to check: https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions
