### ISSUE TITLE
.NET Core June 2020 Update - 2.1.19  and 3.1.5

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#4803]
[3.1.5 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.5/3.1.5.md)
[3.1.5 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.19 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.19/2.1.19.md)
[2.1.19 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-june-2020/)

Please report any issues you find with 2.1.19 or 3.1.5, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

**Comment by jehof** [comment]
title should be .NET Core June 2020 Update - 2.1.19 and **3.1.5**

**Comment by JeffreyH1989** [comment]
Hi,
The SDK 2.1.515 reports supported for Visual Studio 2019, but the vs-version corresponds with 2017 (as it should). JSON release output aswell:
```
"version": "2.1.515",
            "version-display": "2.1.515",
            "runtime-version": "2.1.19",
            "vs-version": "15.9.24",
            "vs-support": "Visual Studio 2019 (v16.2 or later)",

```

**Comment by rbhanda** [comment]
The VS version issue for SDK 2.1.515 is fixed: https://github.com/dotnet/core/blob/master/release-notes/2.1/releases.json#L338

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/4939
