### ISSUE TITLE
how do I install multiple versions of dotnet core and manage dotnet osx

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotnet/core#482]
I want to know how can I install multiple versions of dotnet sdk on my machine OSX & also manage dotnet command in terminal just like ruby/python to select weather use python2/python3

**Comment by Petermarcu** [comment]
At a high level, you can always use the newest SDK. It lets you build for older versions. You select the version for an application in its project file. Does that help or are you trying to do something different?

**Comment by AbhimanyuAryan** [comment]
@Petermarcu `dotnet migrate` command does that migration right? But does that convert a `project.json` to `csproj` one as well?

I looking for some solution like we have for Ruby on Rails([rbenv & rvm](http://jonathan-jackson.net/rvm-and-rbenv))

**Comment by svick** [comment]
You should be able to install multiple versions of the SDK side-by-side.

To choose which one is used, create a [global.json file](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/global-json) in the current directory with the `sdk` property set.

**Comment by Petermarcu** [comment]
@AbhimanyuAryan yes, dotnet migrate entire reason for existing is to convert project.json projects to csproj projects.
