### ISSUE TITLE
How allocate memory in loop?

### ISSUE THREAD

**Issue by Li7ye** [dotnet/core#4820]
Hi ,

The question is that I try to create an instance to a variable in a loop and don't use this  variable. 
Like this :
![image](https://user-images.githubusercontent.com/42088918/84359149-cc8a2280-abfa-11ea-8be6-0516723a13d1.png)

Then I use the 'Diagnostic Tool' in VS to track the memory in managed heap , however , I get only a count of Foo type in heap without GC behavior , it makes me very confuse. Hence , I infere that there is a optimization at run time for the variable which don't use in context and this optimization in order to save memory to only allocate one time in managed heap as no impact for application. I'm very very very thank you to give me some advice for that as this question let me can't keep good sleep every day.
![image](https://user-images.githubusercontent.com/42088918/84359204-e0358900-abfa-11ea-9d73-dad559cd94ae.png)

**Comment by scalablecory** [comment]
Try adding the objects to a list.

**Comment by GrabYourPitchforks** [comment]
This question involves Visual Studio / .NET Full Framework question and is out of scope for the dotnet/core repo. The best place to receive assistance for Visual Studio questions is the forum at https://developercommunity.visualstudio.com/. You can also file an issue directly from within Visual Studio by using the reporting mechanism described [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio).
