### ISSUE TITLE
it says 'dotnet' is not recognized as an internal or external command error

### ISSUE THREAD

**Issue by vardhanvenkata** [dotnet/core#4824]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Have you restarted your console windows after installing .NET? Path variables are changed, and consoles do not get updated automatically.

**Comment by RahulB164** [comment]
look at your common language speciifcations(CLS)
