### ISSUE TITLE
CoreCLR path

### ISSUE THREAD

**Issue by PeFF1** [dotnet/core#4825]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try to create an application through "_dotnet console -o **name**_". I get an error like "_Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1_", the application was not created, did not touch anything. Please help.

**Comment by scalablecory** [comment]
Can you please try to reinstall .NET? If that doesn't work, can you try setting the COREHOST_TRACE variable as it suggests, and paste the output here?

@jeffschwMSFT @dagood any other ideas?

**Comment by dagood** [comment]
> "_dotnet console -o **name**_"

It looks like you missed `new`: `dotnet new console -o name` is the right command. (I suggest copy-pasting from the tutorial.)

That said, I don't know why got that error from this typo, I'd expect something more like `Could not execute because the specified command or file was not found`.

Another thing that might help narrow this down is running `dotnet --info` and pasting the output here.

**Comment by PeFF1** [comment]
> > " _консоль dotnet -o **name**_ "
> 
> Похоже, вы пропустили `new`: `dotnet new console -o name`это правильная команда. (Я предлагаю скопировать из учебника.)
> 
> Тем не менее, я не знаю, почему получил эту ошибку от этой опечатки, я ожидал что-то более похожее `Could not execute because the specified command or file was not found`.
> 
> Еще одна вещь, которая может помочь сузить это, - запустить `dotnet --info`и вставить вывод здесь.

Could not resolve CoreCLR path. For more details, enable tracing by setting CORE
HOST_TRACE environment variable to 1

**Comment by PeFF1** [comment]
> Можете ли вы попробовать переустановить .NET? Если это не сработает, вы можете попробовать установить переменную COREHOST_TRACE, как она предлагает, и вставить вывод здесь?
> 
> @jeffschwMSFT @dagood есть еще идеи?

Okey.

**Comment by jeffschwMSFT** [comment]
@marcpopMSFT

**Comment by marcpopMSFT** [comment]
What version of the .NET sdk is the customer using?  When I execute "dotnet console -o name" with 3.1.300, I correctly get an error that the command is not found and suggestions that you might have mispelled it which seems correct behavior.

**Comment by mairaw** [comment]
@PeFF1 can you paste here the information from the `dotnet --info` command?

**Comment by dagood** [comment]
> can you paste here the information from the `dotnet --info` command?

I believe they already tried that, and `dotnet --info` failed to resolve CoreCLR too (just some context lost in translation):

> > Еще одна вещь, которая может помочь сузить это, - запустить `dotnet --info`и вставить вывод здесь.
> > [Another thing that can help narrow this down is to run `dotnet --info` and paste the output here.]
> 
> Could not resolve CoreCLR path. For more details, enable tracing by setting CORE
> HOST_TRACE environment variable to 1

@PeFF1 can you confirm that's what you meant? (And if you don't mind, please turn off auto-translation before quoting, so we can follow the conversation more easily in English. 😄)

**Comment by PeFF1** [comment]
CoreCLR path visible everytime,
dotnet console -o name - CoreCLR error
dotnet --version - CoreCLR error

**Comment by danatcofo** [comment]
This happens on Italian language Windows as well.  Did you guys not test foreign language installs?

**Comment by dagood** [comment]
> Did you guys not test foreign language installs?

They are tested (last I saw). I don't see a clear connection between the error message and the OS language, though.

> This happens on Italian language Windows as well.

@danatcofo Can you file a new issue with more information, such as the output you get when you set `COREHOST_TRACE=1` before running the `dotnet` command? The current issue was closed, and closed issues typically aren't monitored here.

**Comment by danatcofo** [comment]
It looks like something is getting confused with the resolution paths...

On Italian Windows Program Files and Program Files (x86) are actually Programmi and Programmi (x86)

When I build the Core Application with PublishReadyToRun = false then its looking inside the English language version for that, when I build it with PublishReadyToRun = true, it embeds all of those dependencies in my app and runs fine

If I find some time I'll open a ticket but I've got a working resolution for the issue now.

**Comment by Psycho-Fox** [comment]
Can confirm broken on Japanese windows
