### ISSUE TITLE
Program.cs(10,60): error CS1002: ; expected [C:\Users\W.KAZIMOTO\myApp\myApp.csproj]

### ISSUE THREAD

**Issue by lutinwa** [dotnet/core#4826]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
It looks like you've got a syntax error in your code. Can you please provide a copy of your code here?
