### ISSUE TITLE
Error	MSB4018	The "ResolvePackageAssets" task failed unexpectedly.

### ISSUE THREAD

**Issue by SaifKb** [dotnet/core#4831]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

just loaded the project  as seen in the tutorial and the error appears in the console

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you provide the output of the `dotnet --info` command @SaifKb?

 @rainersigwald is this something you can help with?

**Comment by SaifKb** [comment]
hi Maria

problem solved, after uninstalling the older version
thanks and sorry for the delay, I did see your email

Saif Kbishi

SeatGeek Enterprise.

P.O.B 1137, Karmiel 2165318, Israel

Main Office: +972 (4) 9088913

saif@seatgeek.com

**Comment by mairaw** [comment]
No worries. Thanks for letting us know and I'm glad you sorted it out.
