### ISSUE TITLE
"dotnet" is not regonized

### ISSUE THREAD

**Issue by Rajucoder** [dotnet/core#4833]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Have you restarted your console windows? Environment variables are updated, and consoles don't get them without a restart.
