### ISSUE TITLE
To start building .NET apps

### ISSUE THREAD

**Issue by Faris-JS** [dotnet/core#4839]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
