### ISSUE TITLE
Where's the "any" key???

### ISSUE THREAD

**Issue by LastWordSword** [dotnet/core#4841]
![First NET stumper](https://user-images.githubusercontent.com/62988592/84868399-a6291480-b04a-11ea-9c1a-9a1dd8440183.png)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I don't know what I did wrong, but I'm betting it's pretty simple. 

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
Why did you type `Program.cs` into your console? You can open the `Program.cs` file in a text editor if you want to confirm its contents, but you're already done with that page and can continue on to the next. 😄

**Comment by mairaw** [comment]
To view the Program.cs file, you need to open the file in a text editor like @dagood mentioned or you can type `more Program.cs` to see the contents on the prompt. Let us know if that helps. You can continue the tutorial.

**Comment by shyboylpf** [comment]
This is interesting, You can edit Program.cs in your notepad maybe, but do not type Program.cs in the prompt as @dagood mentioned, If that helps please let us know, we care about you.
