### ISSUE TITLE
== and Equals return different results for IPAddress

### ISSUE THREAD

**Issue by erenturkm** [dotnet/core#4842]
# Issue Title

== and Equals return different results for IPAddress

# General
I am using c#, .net Core 3.1.4 on Windows 10 1909.
``
IPAddress IP1,IP2;
string Example="0.1.2.3";
IP1=IPAddress.Parse(Example);
IP2=IPAddress.Parse(Example);
bool B1=IP1.Equals(IP2);
bool B2=IP1==IP2;
``
B1 returns true, whereas B2 returns false

**Comment by scalablecory** [comment]
Thanks for the report.

What you're seeing is an example of reference equality versus value equality. `IP1` and `IP2` are different instances, even though they both store the same value.

`IPAddress` does not define an `operator==`, so it gets the default `==` behavior in .NET of testing reference equality, not value equality. Using `Equals` is the correct thing to do when value equality is desired.

Adding a different `operator==` now would be a breaking to any existing code depending on reference equality, so this isn't something we will be able to change.
