### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora .NET na Squadra Tecnologia

### ISSUE THREAD

**Issue by VictoriaBoaventura** [dotnet/core#4846]
## Descrição da vaga

Buscamos pessoas **Junior, Pleno ou Sênior** para atuar Desenvolvimento de sistemas com .Net Core.
Você vai participar de Squads para desenvolvimento de soluções para nossos clientes utilizando metodologias ágeis; Apoiará na definição de soluções arquiteturais/técnicas; Dará suporte ao planejamento do projeto e ao processo de implantação no cliente; Além de participar de reuniões e ritos.

## Local

Remoto ou Presencial (conforme preferencia do candidato e localidade)

## Benefícios

- Plano de saúde
- Plano odontológico
- VR
- Bolsa Certificação
- Acesso ao Alura, Udemy e PluralSigth
- Horário flexível

## Requisitos

- .Net Core
- Asp net
- MVC
- Dapper
- SQL Server
- GIT
- Azure DevOps
- Scrum ou Kanban

## Contratação

CLT

## Como se candidatar

Para se inscrever envie seu currículo para victoria.boaventura@squadra.com.br - colocando no assunto: Pessoa Desenvolvedora .NET - colocando a senioridade JR, PL ou SR

**Comment by mairaw** [comment]
Olá Victoria! Como esse repositório é para reportar problemas com o produto, vou fechar este issue. Obrigada.
