### ISSUE TITLE
error message : Unknown option -v while trying to download nuget artifact

### ISSUE THREAD

**Issue by deepend-dev** [dotnet/core#4848]
# Issue Title
Keep getting below error message when I register a repository in powershell and download nuget package from Azure artifact

# General
![image](https://user-images.githubusercontent.com/55054090/85006361-efb05700-b151-11ea-9d67-4aab1692a768.png)

**Comment by ChrisAtRelativity** [comment]
Seeing the same with Register-PSRepository with version 3.1.401... how did you work around?

**Comment by deepend-dev** [comment]
@ChrisAtRelativity  didn't find any?

**Comment by ChrisAtRelativity** [comment]
I found a related issue and also documented there.
https://github.com/PowerShell/PowerShellGet/issues/52#issuecomment-674350338
