### ISSUE TITLE
Installation requirements for SDK 2.1.515(Document)

### ISSUE THREAD

**Issue by kurehajime** [dotnet/core#4851]
The installation requirements for the SDK 2.1.515 listed on this page are "Visual Studio 2019 (v16.2 or later)".
And it also says Visual Studio 15.9.24.
Is this correct?
https://dotnet.microsoft.com/download/dotnet-core/2.1

Maybe it's related.
https://github.com/dotnet/core/blob/5c7c41d5007d7b740f7e11ab3357bbaafff051fd/release-notes/2.1/releases.json#L338

**Comment by JeffreyH1989** [comment]
Hi,

I posted this too in the news announcement [here](https://github.com/dotnet/core/issues/4803#issuecomment-641753528). Would be lovely if this could be fixed, our automated process now skips retrieving the latest 2017 sdk due to this invalid value

**Comment by kurehajime** [comment]
This issue fixed.

Thanks #4897
