### ISSUE TITLE
System.Runtime.Remoting.Lifetime

### ISSUE THREAD

**Issue by ahoirg** [dotnet/core#4854]
System.Runtime.Remoting library started to be supported with .net core 3.1.  The supported version does not have the System.Runtime.Remoting.Lifetime namespace. Therefore ILease and ISponsor interfaces are not available.

**Comment by carlossanlop** [comment]
@joperezr is this something you can help with?

**Comment by joperezr** [comment]
Not sure what you mean by it being supported in 3.1 but as you can see on the closed issue https://github.com/dotnet/runtime/issues/29784 we intentionally decided not to bring Remoting into Core. It is possible that with the effort put in for wpf and winforms for 3.0 some small part of remoting was brought back but only for the closure of those technologies.

**Comment by ahoirg** [comment]
Thanks for your message. I think, i was able to use this library because of .NET Platform Extensions.
