### ISSUE TITLE
Obj error 

### ISSUE THREAD

**Issue by andrew-sabol-31** [dotnet/core#4855]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: macOS

When doing this step and adding in the piece to add the time the Hello World message. I will get an error associated with the netcore Assembly attributes 
<img width="1029" alt="Screen Shot 2020-06-20 at 3 07 39 PM" src="https://user-images.githubusercontent.com/39058546/85209687-e7018180-b307-11ea-8b04-14e9807cca71.png">

It also gives me this error in the terminal window. 
{ "resource": "/Users/andrewsabol/Desktop/VIsual Studio/HelloWorld/myApp/obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs", "owner": "csharp", "code": "CS0579", "severity": 8, "message": "Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [myApp]", "source": "csharp", "startLineNumber": 4, "startColumn": 12, "endLineNumber": 4, "endColumn": 70 }

**Comment by KimKiHyuk** [comment]
https://developercommunity.visualstudio.com/content/problem/1055833/duplicate-globalsystemruntimeversioningtargetframe.html

it can resolve your problem.

**Comment by mairaw** [comment]
So all you've done is to edit the Program.cs file directly under the myApp folder and run `dotnet run` and you got this error?
