### ISSUE TITLE
Does dotnet core support server-side web service application?

### ISSUE THREAD

**Issue by kastier** [dotnet/core#486]
I'm really sorry to ask this but there is some old project running on iis and we want move to .net core

**Comment by Petermarcu** [comment]
Yes, it's one of its mainline scenarios. Depending on how old it is and what technology it uses, those technologies may or may not be supported on .NET Core. But .NET Core is absolutely for server-side web services. See here for more info and links to documentation, getting started, etc...

**Comment by Petermarcu** [comment]
https://www.microsoft.com/net/core/platform

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/

**Comment by Petermarcu** [comment]
I'm going to close this issue now as I think you got directed to the right place.
