### ISSUE TITLE
'dotnet' is not recognized as an internal or external command error 

### ISSUE THREAD

**Issue by shubhra23Oct** [dotnet/core#4863]
![error](https://user-images.githubusercontent.com/67266025/85501233-912c2280-b602-11ea-8030-a19a822c74df.PNG)
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial//install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Please restart your console windows after installing the .NET Core SDK. Environmental variables have been changed.

**Comment by mairaw** [comment]
You can also follow the steps on this article to ensure the SDK has installed correctly: https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows#check-for-install-folders

Let us know if any of these tips helped you solve your issue!
