### ISSUE TITLE
error during connect: 

### ISSUE THREAD

**Issue by hemanthgattu** [dotnet/core#4865]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=rfbn8zxl8bqigzc162kttg5aa&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by mairaw** [comment]
@nishanil @shirhatti can you help with this issue?

**Comment by sughosneo** [comment]
Hi @hemanthgattu, thank you for reaching out.

Can you verify if your Docker instance is running? You can verify that in your Docker Desktop dashboard. 
If yes, you can run your PowerShell window as Administrator and then try to execute the steps and see if it helps.
