### ISSUE TITLE
Dotnet Run facing error

### ISSUE THREAD

**Issue by gowthamd3** [dotnet/core#4870]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that [is](url
![2020-06-25](https://user-images.githubusercontent.com/65020517/85733192-9e880080-b719-11ea-8bdb-0bbec03af4e9.png)
) relevant.

ATTACHED Screenshot for refernce

**Comment by shyboylpf** [comment]
Hi gowthanmd3,
Can you show the code in HomeController,  and the content in file myapp.csproj?

**Comment by mairaw** [comment]
Also, this tutorial is about console apps, so I'm not sure why you're getting ASP.NET errors.

If you wanna try building a web app, follow this tutorial instead: https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/intro
