### ISSUE TITLE
I cannot uninstall old .Net Core SDKs

### ISSUE THREAD

**Issue by YF1999** [dotnet/core#4878]
# Issue Title

I currently have 4 .Net Core SDKs, 3.1.100, 3.1.101, 3.1.201 and 3.1.301. I have uninstalled the 3 old .Net Core SDKs but they still exist.

# General

Windows 10 Pro 1909 18363.900
Visual Studio 2019 Professional 16.6.2

`dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

But there is only one .Net Core SDK showed in Apps & Features list:
![image](https://user-images.githubusercontent.com/55199350/85822520-abeeca80-b7ad-11ea-81d9-d03e168e7781.png)

It doesn't work that I reinstall the 3 old SDKs and then uninstall them.

**Comment by shyboylpf** [comment]
Check out directory [C:\Program Files\dotnet\sdk] , confirm the older version of .netcore have removed.

**Comment by shyboylpf** [comment]
![image](https://user-images.githubusercontent.com/4532561/85934870-d6f72c80-b91b-11ea-832a-2db7c8a475db.png)
I uninstalled older version .netcore sdk 2.x and 3.x, only retained the latest version 3.1.301 and .net 5 , nothing error happend.

**Comment by YF1999** [comment]
The older versions of .netcore exist.
![image](https://user-images.githubusercontent.com/55199350/85935748-a7015680-b926-11ea-85bc-9e915e453281.png)

**Comment by shyboylpf** [comment]
Maybe change the directory name.
Like mv 3.1.100 3.1.100.bak

YF1999 <notifications@github.com> 于2020年6月28日周日 上午10:07写道：

**Comment by YF1999** [comment]
It does't work.

By the way, I tried repairing them, but failed. Here are the logs:
[Microsoft_.NET_Core_SDK_3.1.101_(x64)_20200628101800.log](https://github.com/dotnet/core/files/4841574/Microsoft_.NET_Core_SDK_3.1.101_.x64._20200628101800.log)
[Microsoft_.NET_Core_SDK_3.1.201_(x64)_20200628101907.log](https://github.com/dotnet/core/files/4841575/Microsoft_.NET_Core_SDK_3.1.201_.x64._20200628101907.log)
[Microsoft_.NET_Core_SDK_3.1.301_(x64)_20200628102015.log](https://github.com/dotnet/core/files/4841576/Microsoft_.NET_Core_SDK_3.1.301_.x64._20200628102015.log)

**Comment by shyboylpf** [comment]
Sorry, I have no idea.

**Comment by mairaw** [comment]
@KathleenDollard @sfoslund can you help here?

**Comment by sfoslund** [comment]
How are you uninstalling the SDKs (through add/remove programs, the standalone installers, Visual Studio installer)? @joeloff do have ideas here?

**Comment by joeloff** [comment]
For the 3.1.101 log, it seesm like a mismatched between installed sources. The second one indicates an issue with a mismatched package code (it's returning 1638 (0x80070666)). That's an issue we recently fixed, but it doesn't solve the problem for older SDK installs.

For the bundled installations, we'd need to get ASP.NET removed/replaced to unblock the rest of the install process.

@YF1999 to find the individual ASP.NET installers, open a command prompt and

```reg query HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL /s /d /f "*Microsoft ASP.NET Core 3.1.1*"```

You should see output similar to this (I only had 3.1.2 installed on my machine)

![image](https://user-images.githubusercontent.com/7409981/86048333-341add00-ba05-11ea-9ba8-3ae206ce12e3.png)

Grab the GUIDs (including the braces) and run the following command from an elevated prompt

 ```msiexec /x {GUID} /q IGNOREDEPENDENCIES=ALL``` 

If both MSIs are removed successfully, open Add/Remove Programs (Start + Run appwiz.cpl), right click on the SDK 3.1.101 entry (the first one in your screenshot) and select uninstall.

If this works, we can look at the other SDKs since they may need a different approach.

**Comment by YF1999** [comment]
> How are you uninstalling the SDKs (through add/remove programs, the standalone installers, Visual Studio installer)? @joeloff do have ideas here?

Through 'add or remove programs'. I have also tried 'dotnet-core-uninstall', but still doesn't work.

**Comment by YF1999** [comment]
I found the logs about SDKs uninstallation, these may be useful.
[Microsoft_.NET_Core_SDK_3.1.100_(x64)_20200630101133.log](https://github.com/dotnet/core/files/4849038/Microsoft_.NET_Core_SDK_3.1.100_.x64._20200630101133.log)
[Microsoft_.NET_Core_SDK_3.1.101_(x64)_20200630101552.log](https://github.com/dotnet/core/files/4849047/Microsoft_.NET_Core_SDK_3.1.101_.x64._20200630101552.log)
[Microsoft_.NET_Core_SDK_3.1.201_(x64)_20200630101659.log](https://github.com/dotnet/core/files/4849048/Microsoft_.NET_Core_SDK_3.1.201_.x64._20200630101659.log)

**Comment by YF1999** [comment]
@joeloff 
Microsoft ASP.Net Core 3.1.1 was removed successfully, but SDK 3.1.101 still cannot be entirely uninstalled.

**Comment by joeloff** [comment]
So for the 3.1.101 logs, when you look at the logs, you'll see these entries:

```
Will not uninstall package: netstandard_targeting_pack_2.1.0_win_x64.msi, found dependents: 3
[4B70:4D20][2020-06-30T10:15:53]w328: Found dependent: VS.{AEF703B8-D2CC-4343-915C-F54A30B90937}, name: Unknown
[4B70:4D20][2020-06-30T10:15:53]w328: Found dependent: {5e0a0ca7-8d37-4573-8d5b-03416809a484}, name: Microsoft .NET Core SDK 3.1.201 (x64)
[4B70:4D20][2020-06-30T10:15:53]w328: Found dependent: {7f230f6e-4c10-4ca6-8b68-aa8b8a719d70}, name: Microsoft .NET Core SDK 3.1.301 (x64)
```

That's because some of the runtimes are shipped in multiple SDKs. Sometimes the runtimes remain unchanged, e.g. if we ship new templates in the SDK. From the entries above both SDK 3.1.201 and 3.1.301 included the targeting pack installer as well as Visual Studio.

You can try removing the 3.1.301 and 3.1.201 SDKs, but Visual Studio would still hold on to a reference. 

From the 201 log you attached I can see that it removed some reference counts:

```
[519C:59B4][2020-06-30T10:17:00]i326: Removed dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: Microsoft.AspNetCore.SharedFramework_x64_ENU,v3.1.3, package AspNetCoreSharedFramework_x64
[519C:59B4][2020-06-30T10:17:00]i326: Removed dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: Dotnet_CLI_3.1.201.015034_x64, package dotnet_sdk_internal_3.1.201_win_x64.msi
[519C:59B4][2020-06-30T10:17:00]i326: Removed dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: NetCore_Templates_3.1_3.1.4.015034_x64, package dotnet_31templates_3.1.201_servicing_015034_win_x64.msi
[519C:59B4][2020-06-30T10:17:00]i326: Removed dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: windowsdesktop_targeting_pack_24.64.28315_x64, package windowsdesktop_targeting_pack_3.1.0_win_x64.msi
[519C:59B4][2020-06-30T10:17:00]i326: Removed dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: Microsoft.AspNetCore.TargetingPack_x64_ENU,v3.1.3, package aspnetcore_targeting_pack_3.1.3_win_x64.msi
[519C:59B4][2020-06-30T10:17:00]i326: Removed dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: netstandard_targeting_pack_24.0.28113_x64, package netstandard_targeting_pack_2.1.0_win_x64.msi
```

Until you remove the SDK from the Visual Studio install, it won't get fully removed. If that is a problem, I can provide help with deleting the reference counts, in which case you can uninstall everything and then just perform a repair on Visual Studio to get the latest SDK included with the version you have.

**Comment by YF1999** [comment]
I hope to uninstall the older SDKs for I have no projects that need to use them. I will not uninstall the lastest SDK until .Net 5 official release published.
So how can I do to remove the reference counts?

**Comment by joeloff** [comment]
Each MSI that opts to participate in reference counting has a registry entry called a dependency provider key. Effectively, each bundle (EXE installer of the SDK, Visual Studio) can then write their product IDs under the provider key. When these products are removed, they usually just remove the reference they created, except when there is only one reference left, then the actual uninstall happens.

The keys are located under HKCR\Installer\Dependencies.

When you look at the logs you shared, you'll see entries like this:

```
Registering dependency: {5e0a0ca7-8d37-4573-8d5b-03416809a484} on package provider: netstandard_targeting_pack_24.0.28113_x64
```
The provider key you want to edit, is ```HKCR\Installer\Dependencies\netstandard_target_pack_24.0.28133_x64```. It should have a subkey named ```{5e0a0ca7-8d37-4573-8d5b-03416809a484}```. Deleting the 5e0... subkey removes the reference.

I'd suggest just searching for the ```{5e0a0ca7-8d37-4573-8d5b-03416809a484}``` under HCKR\Installer\Dependencies and removing the reference. Then look at your logs from the other installs to find the remaining bundle IDs and repeat the search. From the logs I only saw two IDs for SDKs and then a VS reference as well.

```
{5e0a0ca7-8d37-4573-8d5b-03416809a484} --> SDK 3.1.201
{7f230f6e-4c10-4ca6-8b68-aa8b8a719d70} --> SDK 3.1.301
VS.{AEF703B8-D2CC-4343-915C-F54A30B90937} --> Visual Studio
```

You can probably script it to delete the subkeys that match the dependency IDs, but the ID for VS (```VS.{AEF703B8-D2CC-4343-915C-F54A30B90937}```) will show up in other products, so you might want to remove that one by hand so you don't impact non-SDK related installers.

**Comment by YF1999** [comment]
That helps a lot, the older SDKs have been completely uninstalled.

But here in this log, [Microsoft_.NET_Core_SDK_3.1.201_(x64)_20200704190533.log](https://github.com/dotnet/core/files/4872903/Microsoft_.NET_Core_SDK_3.1.201_.x64._20200704190533.log)
What does the `Plan disabled rollback` mean? Will something bad happen?
```
w208: Plan disabled rollback for package: aspnetcore_targeting_pack_3.1.3_win_x64.msi, due to incomplete cache: None, original rollback action: Install
w208: Plan disabled rollback for package: dotnet_apphost_pack_3.1.3_win_x64_arm.msi, due to incomplete cache: None, original rollback action: Install
```

**Comment by joeloff** [comment]
Glad to hear you managed to remove them.

It sounds like the engine believes that the packages aren't cached so it's disabling the rollback policy. I wouldn't worry too much about that. Normally when the bundle is executed it should cache all the package.

With a bundle, by default all the MSIs that it would install (or uninstall) are considered to be vital. For example, if we have 3 MSIs, A, B, and C and A installs successfully, but B fails, then C is skipped and A will be uninstalled (rolled back). The same happens for uninstalls. MSIs are removed in the reverse order, so keeping with the example, the uninstall would be C, B, A. But if B fails to uninstall, rollback would reinstall C to keep the state of the machine as stable as possible.

**Comment by YF1999** [comment]
Thank you for all your explanation.
My problems have been solved and I have no more problems now.

**Comment by winseros** [comment]
I also can't uninstall the SDK after I have uninstalled the Visual Studio:
![image](https://user-images.githubusercontent.com/6763540/141356815-88ea87e3-c856-42dc-946a-1d034f70b501.png)

The image says "Use Visual Studio installer" but I upgraded the Visual Studio to 2022 and no longer have 2019 installation.

**Comment by joeloff** [comment]
That is just a placeholder for when VS installs the SDK, it doesn't actually install anything. That entry appears quite old as it's 3.0.100 which shipped with 16.4. It's possible it got orphaned during an upgrade somehow, but I'd need to see the all the relevant VS logs to piece it together.

You can try running this: `reg query HKLM\SOFTWARE\Microsoft\Windows\currentversion\uninstall /s /d /f "from Visual Studio"`

And you'll see output similar to

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{8735B447-6C57-408D-ABC1-C1CF5DD96460}
    DisplayName    REG_SZ    Microsoft .NET SDK 6.0.100 (x64) from Visual Studio

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{A6889A2D-DA5E-4DED-B563-DAF5BE5252AA}
    DisplayName    REG_SZ    Microsoft .NET SDK 5.0.402 (x64) from Visual Studio
```
Grab the GUID for the entry for 3.0.100, then run `msiexec /x {GUID} IGNOREDEPENDENCIES=ALL ALLOWMSIUNINSTALL=1`

**Comment by winseros** [comment]
```powershell
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{C52DB3F0-440B-4A83-B795-B1180D70BBFF}
    DisplayName    REG_SZ    Microsoft .NET Core SDK 3.0.100 (x64) from Visual Studio
```

```powershell
msiexec /x C52DB3F0-440B-4A83-B795-B1180D70BBFF IGNOREDEPENDENCIES=ALL ALLOWMSIUNINSTALL=1
```

![image](https://user-images.githubusercontent.com/6763540/141497958-707de486-c135-47d5-aab1-7af4d8106b26.png)

And the SDK is still in place.

**Comment by joeloff** [comment]
Place { } around the GUID, otherwise it might be interpreted as a filename instead.

**Comment by winseros** [comment]
Worked this way, thanks a lot!

```powershell
msiexec /x "{C52DB3F0-440B-4A83-B795-B1180D70BBFF}" IGNOREDEPENDENCIES=ALL ALLOWMSIUNINSTALL=1
```

**Comment by CrossBound** [comment]
> For the 3.1.101 log, it seesm like a mismatched between installed sources. The second one indicates an issue with a mismatched package code (it's returning 1638 (0x80070666)). That's an issue we recently fixed, but it doesn't solve the problem for older SDK installs.
> 
> For the bundled installations, we'd need to get ASP.NET removed/replaced to unblock the rest of the install process.
> 
> @YF1999 to find the individual ASP.NET installers, open a command prompt and
> 
> `reg query HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL /s /d /f "*Microsoft ASP.NET Core 3.1.1*"`
> 
> You should see output similar to this (I only had 3.1.2 installed on my machine)
> 
> ![image](https://user-images.githubusercontent.com/7409981/86048333-341add00-ba05-11ea-9ba8-3ae206ce12e3.png)
> 
> Grab the GUIDs (including the braces) and run the following command from an elevated prompt
> 
> `msiexec /x {GUID} /q IGNOREDEPENDENCIES=ALL`
> 
> If both MSIs are removed successfully, open Add/Remove Programs (Start + Run appwiz.cpl), right click on the SDK 3.1.101 entry (the first one in your screenshot) and select uninstall.
> 
> If this works, we can look at the other SDKs since they may need a different approach.

This worked for me, but I did have to expand the search parameter in the reg query command listed above to find other versions of the .net core library such as the targeting pack and the desktop app, etc. I just searched for "*3.1*" and it pulled up  a whole list of candidates that I had to remove with the second command above. This worked great and solved my issue.

**Comment by 123anvar** [comment]
@joeloff 's answer worked for me !! Thanks !!
For Info : I was having trouble uninstalling SDK 5.0.409 from Visual Studio Modify and add or remove programs but the solution by @joeloff helped me.
