### ISSUE TITLE
Question: support for macOS on ARM

### ISSUE THREAD

**Issue by kristof12345** [dotnet/core#4879]
Hi!

Are you planning .Net Core (or unified .Net) to support the upcoming ARM (Apple Silicon) based Macs?

I know its a huge effort, but many developers are counting on you. .Net core was intended to be a multiplatform solution, so I expect it to be supported in a future release (maybe .Net 6?).

Thanks.

**Comment by omajid** [comment]
cc @richlander who was asking for user input for platform support at https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-6/

**Comment by mairaw** [comment]
Adding @leecow as well

**Comment by leecow** [comment]
Yes, we will support .NET Core on the new Mac hardware.

**Comment by richlander** [comment]
Little bit more context: https://twitter.com/runfaster2000/status/1279821716944900096

We are still working through this, so we don't have anything like release dates to share yet.

**Comment by guidupuy** [comment]
Hey is there any update on this?

**Comment by deinman** [comment]
With the M1 chip being announced today is there any additional information available?

**Comment by LukeStephen** [comment]
Just ordered the new macbook pro with apple silicone, cant wait to develop .NET Core using Visual Studio Code

**Comment by lokinfey** [comment]
Any road map about that ? I think MSFT need to add .NET 6 preview  asap ,  I need this to build MAUI in my new apple silicon mbp

**Comment by richlander** [comment]
Plan:

- Support .NET Core 3.1 and .NET 5.0 within Rosetta 2 (x64 emulation).
- Support .NET 6.0 with both Rosetta 2 and native architecture (M1).

Tracking issue for M1 enablement: https://github.com/dotnet/runtime/issues/43313. I asked for a tracking issue for Rosetta 2.

**Comment by richlander** [comment]
Rosetta 2 tracking issue: https://github.com/dotnet/runtime/issues/44897

**Comment by Fares-Steen** [comment]
I tested it.
I could run it but no debugging.

**Comment by ernstscheithauer** [comment]
Hi @richlander 
https://github.com/dotnet/runtime/issues/43313 only mentions .NET 5 and 6, not .NET 3.1
Is this now out-of-scope or in-scope?

**Comment by RobertoMachorro** [comment]
I'm curious as to why this issue is closed? Has it been resolved?

**Comment by mairaw** [comment]
@richlander has listed the tracking issues for this work above.
