### ISSUE TITLE
Publish single file generate 3 files.

### ISSUE THREAD

**Issue by pmout** [dotnet/core#4880]
# Issue Title

When I publish using PublishSingleFile option 3 files are created

# General
Using for publish:
dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:DebugType=None /p:DebugSymbols=false
the output files are:
xxxxx.exe
hostfxr.dll
hostpolicy.dll

I'm using .net 5.0.100-preview.5.20279.10 and project file like:

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

**Comment by swaroop-sridhar** [comment]
Please see: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md#preview-5-1
