### ISSUE TITLE
dotnet' is not recognized as an internal or external command error

### ISSUE THREAD

**Issue by piyabut** [dotnet/core#4881]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Have you tried opening a new command prompt after you've installed the .NET SDK @piyabut?
