### ISSUE TITLE
dotnet run does not open browser

### ISSUE THREAD

**Issue by elerizoazul** [dotnet/core#4882]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello, dotnet run command does not open browser to show application. But when i open browser manually and enter the localhost adress then i can see webapp.

how can i make dotnet run command to open browser and show webpage default?

**Comment by mairaw** [comment]
This is by design @elerizoazul. You have to manually do these steps. Do you think we should make that more clear in the tutorial? Thanks!

**Comment by elerizoazul** [comment]
Thank you for your comment. 

I read the tutorial page again and i realized that in the corresponding page, **browse to http://localhost:5000** is clearly written. So i think there is no need for further clarification. 

But it would be nice if the browser was launched automatically when we run the `dotnet run` command.

Thank you.

**Comment by mairaw** [comment]
Yes, I've passed this feedback to the product team. Thanks!

**Comment by danroth27** [comment]
https://github.com/dotnet/sdk/issues/9038
