### ISSUE TITLE
The path to an application .dll file to execute.

### ISSUE THREAD

**Issue by vivekvis486** [dotnet/core#4884]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@vivekvis486 can you clarify what's the error you're getting? At the page you're at, you're just installing the SDK and making sure it installed correctly.
