### ISSUE TITLE
dotnet command error

### ISSUE THREAD

**Issue by RaduTM-spec** [dotnet/core#4886]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was   
included, verify that the path is correct and try again.

How can i resolve this?

**Comment by mairaw** [comment]
Did you try to open a new command prompt after you installed the .NET SDK @RaduTM-spec?
