### ISSUE TITLE
ASP.NET Core Web App Creation 

### ISSUE THREAD

**Issue by shaungibson1** [dotnet/core#4905]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Using 
dotnet new webApp -o myWebApp --no-https
cd myWebApp

I received the following error message

Template "ASP.NET Core Web App" could not be created.
Access to the path 'C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\myWebApp' is denied.

**Comment by scalablecory** [comment]
You should not be creating projects inside of Program Files. You don't have permissions to create them there -- try instead to create them under your user folder.

**Comment by mairaw** [comment]
Did you manage to complete the tutorial @shaungibson1?
