### ISSUE TITLE
Long response time when exception is thrown

### ISSUE THREAD

**Issue by dev-fatih-erol** [dotnet/core#4906]
There are 3 layers in the application.

- Api
- Application
- Infrastructure

**Test 1**

An application level exception is thrown.

_here are the codes_

**Api**

```
 public async Task<IActionResult> Get()
 {
     await _app.Handler();
 }
```
**Application**

```
 public async Task Handler()
 {
     throw new NotFoundException();
 }

 public class NotFoundException : Exception
 {
     public NotFoundException()
         : base($"Product not found.")
     {
     }
 }
```
**Infrastructure**

```
 public async Task Service()
 {
     return null;
 }
```
_Here is the result_

Exception thrown: 'Application.Exceptions.NotFoundException' in Application.dll

Exception thrown: 'Application.Exceptions.NotFoundException' in System.Private.CoreLib.dll

Response Time 400ms between 500ms

**Test 2**

An infrastructure level exception is thrown.

_here are the codes_

**Api**

 ```
public async Task<IActionResult> Get()
 {
     await _app.Handler();
 }
```
**Application**

 ```
public async Task Handler()
 {
     return null;
 }
```
**Infrastructure**

 ```
public async Task Service()
 {
     throw new NotFoundException();
 }
 
 public class NotFoundException : Exception
 {
     public NotFoundException()
         : base($"Product not found.")
     {
     }
 }
```
_Here is the result_

Exception thrown: 'Application.Exceptions.NotFoundException' in Application.dll

Exception thrown: 'Application.Exceptions.NotFoundException' in System.Private.CoreLib.dll

Exception thrown: 'Application.Exceptions.NotFoundException' in System.Private.CoreLib.dll

Response Time 800ms between 900ms

**Question**

why response time increases?

is this a usual thing?

**Comment by winstxnhdw** [comment]
There's too little information here to know why the response time has increased. Please share your full infra.
