### ISSUE TITLE
"Expected error"

### ISSUE THREAD

**Issue by yaay1010** [dotnet/core#4907]
So, I was planning to make a pretty cool Executeble for DOTNET, using C#. I later found out it FAILED. I had open a new command prompt (cmd.exe) and more. At this point, I found out it had a "I ran into an issue" button. Please Help :(

**Comment by scalablecory** [comment]
What specific problem are you seeing? How can we help?

**Comment by mairaw** [comment]
Were you following any of the tutorials @yaay1010?
