### ISSUE TITLE
Couldn't start the Hello World example. [.Net Hello World tutorial]

### ISSUE THREAD

**Issue by mahlahj** [dotnet/core#4908]
![whelp](https://user-images.githubusercontent.com/37989755/86523247-27482000-be2f-11ea-8ada-f52405ce44c1.png)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
OS: Windows 10 home single language, ver 1909, compilation: 18363.900
Error: En línea: 1 Carácter: 6 (line: 1 Character: 6)
+ using System;
+      ~
Falta la directiva using (Misses directive using)
En línea: 7 Carácter: 20 (line: 7 Character: 20
+         static void Main(string[] args)
+                    ~
Falta '(' en la lista de parámetros del método de la clase. (Misses '(' in the list of class methods parameters)
En línea: 7 Carácter: 20
+         static void Main(string[] args)
+                    ~
Falta el cuerpo de función en la declaración function . (Misses in the function body declaration of function)
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingUsingStatementDirective

**Comment by mairaw** [comment]
You don't need to type that. We were just showing the contents of the Program.cs file created by the command in that step.
I'll see if I can improve that so it's more clear. You should be able to go to the next step and run `dotnet run` and continue with the tutorial.

I'd also recommend that you don't create your apps under the `C:\Windows\system32` path.

**Comment by mahlahj** [comment]
Thank you for the response.
Actually figured that out after two hours (LOL) and managed to understand that the .cs was a CSharp file. 
Also got away from the system32, do not want to "make my computer faster" or "download more RAM" with the modification of that folder...
(Jokes...)
