### ISSUE TITLE
i can not run the application through command line/terminal

### ISSUE THREAD

**Issue by madhunepal** [dotnet/core#4909]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\mypc\Desktop\Blazor\BlazorApp

**Comment by alberk8** [comment]
It looks like the aspnet core is running.  You just need to point your browser to http:://localhost:5000 to see the result.

**Comment by mairaw** [comment]
Correct. We try to indicate in the tutorial that you need to open a browser after the listening message is displayed.

@danroth27 we discussed about this behavior before. Not sure if you have an issue tracking the automatic launch of the browser for web apps. /cc @LadyNaggaga

**Comment by danroth27** [comment]
This is the tracking issue: https://github.com/dotnet/sdk/issues/9038

@KathleenDollard

**Comment by mairaw** [comment]
Thanks @danroth27. Closing this issue then. @madhunepal let us know if you were able to finish the tutorial now.
