### ISSUE TITLE
There is no any runtime downloading link in archives.

### ISSUE THREAD

**Issue by jarenduan** [dotnet/core#491]
There is no any runtime downloading link in archives: [download-archive.md](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md). All are SDKs.

**Comment by Petermarcu** [comment]
@leecow , There should probably be a link to the download pages. @jarenduan , Downloads for the runtime are here: https://www.microsoft.com/net/download/core

**Comment by jarenduan** [comment]
Hi, @Petermarcu, there are 1.03 and 1.1 runtime in the link you post, which partially solved the issue. But for an archive, each version released should be there, right? What about 1.0 - 1.02? I can not find them.

**Comment by Petermarcu** [comment]
You are right. @leecow , the content we point to in the archive link needs to have runtime download info not just SDK. https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

**Comment by leecow** [comment]
Thanks all. Updating the download archive pages to include runtime downloads.

**Comment by Petermarcu** [comment]
@leecow , I looked at your last PR that went in. It looks like you updated some but not all the download pages. Was that intentional?

**Comment by leecow** [comment]
@Petermarcu - just not done yet.

**Comment by leecow** [comment]
All download pages should now include runtime archive links. eg

- [1.0.4](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md)
- [1.1.1](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md)

/cc @preetikr
