### ISSUE TITLE
Siguiendo "Tutorial .NET - Hola mundo en 10 minutos" 

### ISSUE THREAD

**Issue by dmeneses2010** [dotnet/core#4912]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

No me aparece el cuadro de dialogo Program.cs

**Comment by carlossanlop** [comment]
Hola @dmeneses2010 , el cuadro de dialogo te va a aparecer si abres el archivo Program.cs en un editor de texto. Abriste ese archivo?
