### ISSUE TITLE
i got an error trying to run this command dotnet ,i am using windows 10

### ISSUE THREAD

**Issue by metagane** [dotnet/core#4914]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
