### ISSUE TITLE
cannot open CSPROJ

### ISSUE THREAD

**Issue by HedySusatyo** [dotnet/core#4916]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by HedySusatyo** [comment]
I try to follow the .NET tutorial and stop at "creating my app".
I have typed "dotnet new console -o myApp" but I cannot open CSPROJ or Program CS to see a console "Hello World".

**Comment by mairaw** [comment]
You can use an editor like Notepad or Visual Studio Code to see the contents of the Program.cs file.

**Comment by mairaw** [comment]
Does that help @HedySusatyo?
