### ISSUE TITLE
.NET 5 support for s390x on Linux distributions

### ISSUE THREAD

**Issue by jperezpbos** [dotnet/core#4917]
Hi,

I see that all .NET 5 previews are made available in most Linux distributions and for different chipsets like ARM 32, ARM64, x64, and x86.  

Support for s390x (IBM Z / LinuxONE platform) could complete full coverage across all architectures.  Also, a great opportunity to take over mostly Java and Python development in s390x right now.   Note that this platform is used for enterprise applications for the largest Financial Services organizations and a lot of FinTech, Blockchain, Data Science, and AI development.

I'm happy to take it off-line and make some introductions with the IBM open source community who can collaborate in this effort.

**Comment by mairaw** [comment]
Tagging @dagood @leecow @richlander

**Comment by dagood** [comment]
https://github.com/dotnet/runtime/issues/34195 is the thread about supporting s390x--you can find some more info there. There seems to be a reasonable level of interest. 🙂 Closing as a duplicate.

> full coverage across all architectures.

Maybe you didn't mean it this way, but the list of architectures here is definitely not all architectures. 😄 For example, what the sites call "ARM 32" is armhf--we don't have downloads for armel. And there are a *ton* of other archs out there, with new ones being developed all the time.
