### ISSUE TITLE
Why does downloading ".NET Core 1.1 SDK - Installer" give me version "1.0.0-preview2-1-003177" of the installer?

### ISSUE THREAD

**Issue by saravanaj** [dotnet/core#492]
I am downloading .NET Core from https://www.microsoft.com/net/download/core#/current

* Why aren't the version numbers in sync?
* Why is there a `preview` suffix in the installer? Isn't .NET core RTM yet?

**Comment by Petermarcu** [comment]
The SDK isn't RTM yet. It is tough to message through the brand name, if you click the runtime tab to go here, you will see RTM bits. https://www.microsoft.com/net/download/core#/current/runtime

This confusion should be over in the next month or two once the SDK tooling is RTM.
