### ISSUE TITLE
When i try to generate for a build or debug in vscode it says it cannot locate the .NET Core

### ISSUE THREAD

**Issue by jasamvuk** [dotnet/core#4922]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Did you install the .NET SDK? Did you make sure to reopen the VS and cmd windows after installing the SDK?

**Comment by jasamvuk** [comment]
Shit i forgot to cmd windows

**Comment by mairaw** [comment]
You can also use the terminal inside VS Code
