### ISSUE TITLE
Ubuntu 19.10 reaches end of life in 17th July 2020

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#4925]
This issue is created to track progress for the [end of support for Ubuntu 19.10](https://wiki.ubuntu.com/Releases).

### Product and Test updates

- [ ] Remove installers for the outdated distro

- [ ] Stop building Official Docker™ images

- [ ]  Remove build support

- [ ]  Remove test assets

### Infrastructure Team Accountabilities/Deliverables:

- [ ]  Send Notification to NetCore Engineering Partners

- [ ]  Remove the outdated version from the hardware pool 

### Release Team

- [ ]  Send Notification to every team in .NET for upcoming addition

- [ ]  Supported OS content gets updated on GitHub and marketing sites. 

- [ ]  Update release manifest files. 

- [ ]  Docker files which are used for install testing needs to be updated. 

### Document updates:
- [ ] Add/Remove OS prerequisites to the dependencies document

- [ ] Update distro install page

**Comment by adegeo** [comment]
@rbhanda You can check off `Update distro install page`
