### ISSUE TITLE
False positive Warning instead of Info at compilation (Azure DevOps)

### ISSUE THREAD

**Issue by tango-charly** [dotnet/core#4926]
# False positive Warning instead of Info at compilation (Azure DevOps)

Hi, 

We have an issue with compilation warning in Azure Devops, I know it's related with Build Agent but idon't know where exactly i have to open this issue.

# General
![image](https://user-images.githubusercontent.com/8989885/87077651-72787f00-c1f1-11ea-84b8-b968d6775665.png)

All pipelines with quality check failed, even if dotnet core sdk/runtime versions are are updated in projects (> 2.2 / 3.1)

There is no way to correct this warning because there is no real issue (just presuming)... The only way we found is to update our yaml pipelines to every project to disable quality check. (Way too loooong...)

Have you any ideas to by pass/ignore this warning with the minimum effort ?

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/azure-pipelines-tasks#13253

**Comment by mairaw** [comment]
Thanks @marcpopMSFT! Now I know why I couldn't find your user. You don't have your name on your profile 😉

**Comment by marcpopMSFT** [comment]
@mairaw added my name. I'd been using the 1ES extension to map to names but it seems to be having trouble working recently for me at least.
