### ISSUE TITLE
How can we load Certificate Signing Request using x509certificates?

### ISSUE THREAD

**Issue by NhatDuy1407** [dotnet/core#4928]
# How can we load Certificate Signing Request using x509certificates?
From a Certificate Signing Request as below:

Example:
-----BEGIN CERTIFICATE REQUEST-----
MIIClDCCAXwCAQAwTzELMAkGA1UEBhMCVk4xEDAOBgNVBAMMB2RldmljZTMxCjAI ...
-----BEGIN CERTIFICATE REQUEST-----

I am using system.security.cryptography.x509certificates, I would load it as a CertificateRequest/X509Certificate2 object to create new certificate from Certificate Signing Request.

Anyone who know how to do?

# Detail
Input: 
- self signed certificate as a CA
- certificate signing request
My code

`string rootCA = ""; // root certificate`
`string scrString = ""; // certificate signing request`
`byte[] rootRawData = Convert.FromBase64String(rootCA);`
`X509Certificate2 rootCert = new X509Certificate2(rootRawData);`

`var generator = X509SignatureGenerator.CreateForRSA(rootCert.GetRSAPrivateKey(), RSASignaturePadding.Pkcs1);`

`byte[] scrRawData = Convert.FromBase64String(scrString);`
`X509Certificate2 scrDeviceCert = new X509Certificate2(scrRawData);` ------> **ERROR: : 'Cannot find the requested object.'**
`CertificateRequest scrDeviceReq = new CertificateRequest(scrDeviceCert.IssuerName, scrDeviceCert.PublicKey, HashAlgorithmName.SHA256);`

`var deviceCert = scrDeviceReq.Create(rootCert.IssuerName, generator, DateTimeOffset.UtcNow.AddDays(1), DateTimeOffset.UtcNow.AddDays(6), new byte[] { 1, 2, 3, 4 });`

**Comment by bartonjs** [comment]
It's not currently possible, this is tracked as https://github.com/dotnet/runtime/issues/29547.

You could manually do it with the new System.Formats.Asn1 library, to manually interpret the CSR and recreate it as a CertificateRequest, just with all the caveats already called out in the feature tracking issue.
