### ISSUE TITLE
Avoid Northern Hemisphere seasons for Release Dates

### ISSUE THREAD

**Issue by jonorossi** [dotnet/core#493]
For those of us in the Southern Hemisphere, reading release dates of software using seasons is painful, and that is ignoring cultures with 6 seasons and the difference between meteorological and astronomical seasons 😉 . It is all a bit like 03/07/2017, is it July or March? So we use ISO 8601.

It would be great if the release dates listed in the roadmap used quarters (e.g. "2017 Q1" even though they are offset from seasons by a month) or even the last month in those seasons.

**Comment by nil4** [comment]
👍 to both suggestions, and particularly to using ISO dates (2017-03-07) everywhere.

**Comment by PeterSawyer** [comment]
Totally agree.  ISO dates naturally sort as well, its the only logical option.  I try to use them in all my UI's (avoid so much confusion) unless the clients specify they need local date format.

**Comment by Petermarcu** [comment]
I'm going to close this issue. The feedback has been heard and we'll try to make sure we communicate dates in a hemisphere agnostic way :) If you find something confusing, please file an issue and point to it specifically and we can address it and close the issue when it's addressed.

**Comment by jonorossi** [comment]
Thanks @Petermarcu, hopefully it was clear I was referring specifically to the release dates in the roadmap which currently has "Spring 2017" and "Summer 2017":

> It would be great if the release dates listed in the roadmap [...]

i.e. https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates

**Comment by Petermarcu** [comment]
Yup, I sent an email to the folks that own the schedule asking if changing it to Q2 and Q3 works for them. I'll get it updated when they confirm that change accurately represents the dates they are targeting at this point.
