### ISSUE TITLE
The build failed. Fix the build errors and run again. Macbook .net 

### ISSUE THREAD

**Issue by pratiksoni1** [dotnet/core#4936]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When running the command dotnet run in the terminal the error message is received which says The build failed. Fix the build errors and run again.

**Comment by mairaw** [comment]
Can you tell what was the build error that you got?

**Comment by pratiksoni1** [comment]
> Can you tell what was the build error that you got?

Hello Mairaw, 

This is the information from the error report . 

Dyld Error Message:
  Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.6/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by mairaw** [comment]
Thanks for the information. And which version of macOS are you on? It might be related to this issue: https://github.com/dotnet/core/issues/4005

**Comment by pratiksoni1** [comment]
version 10.12.6 if that seems to be the issue then upgrading the mac would put extra stress on the device. are there previous versions that are compatible with my os version for download?

**Comment by mairaw** [comment]
Yes, you can use .NET Core 2.1 on Sierra
https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-2.1.808-macos-x64-installer

I'd make sure to delete the other version you installed as well.

Some more info about supported releases:
https://docs.microsoft.com/en-us/dotnet/core/install/macos#supported-releases

I'll close this issue but let us know if you still run into more issues after installing 2.1.

I'll also add a note to the tutorial for users on macOS Sierra so they don't run into the same issue.
