### ISSUE TITLE
.NET Core July 2020 Update - 2.1.20 and 3.1.6

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#4939]
[3.1.6 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.6/3.1.6.md)
[3.1.6 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.20 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.20/2.1.20.md)
[2.1.20 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-july-2020/)

Please report any issues you find with 2.1.20 or 3.1.6, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Here is a list of issues that we are tracking and working to resolve with the July 2020 release. We'll tick them off as each is resolved. See any linked issue for progress or resolution details.

- [x]  [Can't install .NET Core on Ubuntu, Debian from the Linux package repository: "File has unexpected size](https://github.com/dotnet/core/issues/3988) popped up again. - This is resolved now

**Comment by jhockett** [comment]
We're seeing the same error from https://github.com/dotnet/core/issues/3988 pop up with the latest release in our CircleCI test suite.

```
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease

Ign:2 http://deb.debian.org/debian stretch InRelease

Hit:3 http://deb.debian.org/debian stretch-updates InRelease

Hit:4 http://deb.debian.org/debian stretch Release 

Get:5 https://packages.microsoft.com/debian/9/prod stretch InRelease [4009 B]

Get:7 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages [96.4 kB]

Err:7 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages

  Writing more data than expected (96509 > 96366)

  Hashes of expected file:

   - Filesize:96366 [weak]

   - SHA512:383e408b929517161a2c48b7b0ac38eaccc58bddbdca88250941867f31ef9f12138196552cd0549a2b129b0add9dd4a61f2b474165a7ca5f4a7231652b03f7fc

   - SHA256:63ce57b0a494d005bcccd829efe2b28dadec3823eea3047deb2a191aa7ce6287

   - SHA1:16a3b6bf3754e25c7dbc323b2144e6258ace9a78 [weak]

   - MD5Sum:9d5568e53a8d61f77d8449dcb31a262b [weak]

  Release file created at: Tue, 14 Jul 2020 16:28:55 +0000

Fetched 4009 B in 0s (7176 B/s)     

Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Writing more data than expected (96509 > 96366)

   Hashes of expected file:

    - Filesize:96366 [weak]

    - SHA512:383e408b929517161a2c48b7b0ac38eaccc58bddbdca88250941867f31ef9f12138196552cd0549a2b129b0add9dd4a61f2b474165a7ca5f4a7231652b03f7fc

    - SHA256:63ce57b0a494d005bcccd829efe2b28dadec3823eea3047deb2a191aa7ce6287

    - SHA1:16a3b6bf3754e25c7dbc323b2144e6258ace9a78 [weak]

    - MD5Sum:9d5568e53a8d61f77d8449dcb31a262b [weak]

   Release file created at: Tue, 14 Jul 2020 16:28:55 +0000

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by rbhanda** [comment]
@jhockett the issue should be resolved now

**Comment by jhockett** [comment]
I can confirm it's working, thanks so much for the quick reply and fix!

**Comment by CharlesNadolskiNtrs** [comment]
It looks like the issue "DotNetCoreCLI@2 restore broken for custom MsBuild SDKs" was regressed when migrating from /usr/share/dotnet/sdk/3.1.301/MSBuild.dll to /usr/share/dotnet/sdk/3.1.302/MSBuild.dll in azure pipelines.  Same situation and error is happening even though it was resolved before, as documented here:
https://github.com/microsoft/azure-pipelines-tasks/issues/10498
which is related to issue:
https://github.com/NuGet/Home/issues/8183

**Comment by CharlesNadolskiNtrs** [comment]
Workaround for anybody who has run into the same problem as myself in the past week, apparently this task is required for any Azure Pipeline task which needs to read from a NuGet feed which has a custom SDK:
- task: NuGetAuthenticate@0

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/5057
