### ISSUE TITLE
Issue When Trying To run Program.cs after adding code

### ISSUE THREAD

**Issue by kcelestinomaria** [dotnet/core#4941]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I opened Program.cs on Notepad as instructed and added the line of code then saved the file. When I tried to run it again on my command prompt, an error ensued indicating that "Datetime" does not exist in the current context... and then it says that the Build has failed and that I should try to fix the build errors and run again. I don't know any build errors and how to solve them

**Comment by mairaw** [comment]
Can you paste the contents of your Program.cs here?
