### ISSUE TITLE
Will by any chance the next releases of .net frameworks, offer more support for winforms and wpf on Linux?

### ISSUE THREAD

**Issue by UltimateYZ** [dotnet/core#4944]
Hi dotnet devs,

I only want to know if the next releases of .net frameworks will offer more support to sophisticated deployment of winform and wpf on Linux. I use JetBrains Rider on Linux, and I kinda have to develop C# GUI based apps in old ways... It's very tiresome! The mono-project is very helpful, but the UI is very ugly, and it looks like those from decade 90s... I tried to use gtk#, with monodevelop to make the work more productive, but it lacks too much components; even ListBox is missing (I don't remember correctly, I think it was ListView).

**Comment by scalablecory** [comment]
There are currently no plans to port these to non-Windows platforms.

Xamarin Forms already has a community-made GTK+ backend -- I'm not sure if this will carry over to the future .NET MAUI but it seems like a good place to start.
