### ISSUE TITLE
Problem with running dotnet

### ISSUE THREAD

**Issue by PedroN240** [dotnet/core#4946]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

System will not let me run Dotnet from command in Widows 10 and it tells me the following

Template "Console Application" could not be created.
Access to the path 'C:\windows\system32\myApp' is denied.

**Comment by mairaw** [comment]
Yeah, c:\windows\system32 is a system folder.

Try running on a different path such as the users folder similar to what we show at https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create.

**Comment by PedroN240** [comment]
Thanks Maira

Have done that now but I am fumbling around in the dark really!  I just
want to get Synctoy to work!

Regards,

Petrer
Sent from my PC


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mairaw** [comment]
Ah so you might be going in the wrong direction here. Are you getting an error message when you try to run SyncToy? Is it related to not having a certain version of .NET Framework?

**Comment by PedroN240** [comment]
Yes it is.

**Comment by mairaw** [comment]
What version is it requesting? You should be able to find the version it needs at https://dotnet.microsoft.com/download/dotnet-framework.

**Comment by mairaw** [comment]
Also, if you can paste the screenshot that you get and the link you clicked to see if we can improve the process on our side, it would be really helpful.

**Comment by PedroN240** [comment]
Thanks Maira

I assume you are in the States because of timing.  I am in UK.

When I run the Synctoy install it rushes through various actions and then
displays as its final request the attached image.  I followed the link and
downloaded .NET Framework 4.8 (recommended),  As you can see from the other
picture Microsoft Sync Framework 2.0 is installed as is Microsoft.NET but
when I open the folders there is nothing similar to the number displayed on
the other picture.

I have been running (and am even running currently at this time) SyncToy
2.1  on my previous computer, which was built in 2011 and I have just
replaced with this one as it should be faster for my video editing, and I
am really frustrated that I cannot get SyncToy 2.1 to run.

Any help will be gratefully appreciated!

Kind regards,

Peter
