### ISSUE TITLE
dotnet core

### ISSUE THREAD

**Issue by johnjessy92** [dotnet/core#4948]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Q1,How to open program.cs in text editor

**Comment by mairaw** [comment]
You can use any text editor like Notepad or a code editor like Visual Studio or Visual Studio Code. You can download those tools from https://visualstudio.microsoft.com/
