### ISSUE TITLE
.NET SDK not downloading properly on macOS Catalina 

### ISSUE THREAD

**Issue by Morgan-Mischo** [dotnet/core#4950]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Encountering the following output from my terminal when running 'dotnet' after running the installation for the SDK. 

Morgan@Taylors-MacBook-Pro-3 ~ % dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by vcsjones** [comment]
What is not downloading or installing correctly? Based on your output, you successfully ran `dotnet` and it gave you the default help text.

If you meant to run an application, use `dotnet run`.

**Comment by mairaw** [comment]
That's the expected output @Morgan-Mischo. You can continue the tutorial.
