### ISSUE TITLE
Couldn't find a project to run. Ensure a project exists in C:\Project, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by ahirajay15** [dotnet/core#4961]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Couldn't find a project to run. Ensure a project exists in C:\Project, or pass the path to the project using --project.

**Comment by mairaw** [comment]
Did you cd into myApp folder as shown in the create step? 
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
