### ISSUE TITLE
enabling Assembly Binding Logs (Fusion logs) on Linux

### ISSUE THREAD

**Issue by leszek95b** [dotnet/core#4969]
# Fusion logs on Linux

Is it possible to enable assembly binding logs on non-windows operating system?
Currently to enable logs collection you have to setup registry entries. There is no registry on Linux.

**Comment by davidfowl** [comment]
This is a new feature in .NET 5, see https://github.com/richlander/testapps/blob/master/trace-assembly-loading/README.md

**Comment by mairaw** [comment]
It seems this has been answered. Closing.
