### ISSUE TITLE
5.0.0-preview.7 install instructions filename contains an extra space character

### ISSUE THREAD

**Issue by justinian** [dotnet/core#4976]
Announcements and pages about the 5.0.0-preview.7 release link to [this url][correcturl] when linking to the installation instructions for Linux. (eg, on the [Download .NET 5.0][download] page) Note that this points to the file `release-notes/5.0/preview/5.0.0-preview.7-install-instructions.md` in this repo.

However, this file is actually named `release-notes/5.0/preview/5.0.0-preview.7-install-instructions .md` (note the extraneous space character before the file extension), which causes all the Linux installation instructions links to be 404s.

[correcturl]: https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.7-install-instructions.md
[download]: https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by mairaw** [comment]
Thanks @justinian. This was fixed by PR #4980
