### ISSUE TITLE
project.assets.json not found issue

### ISSUE THREAD

**Issue by Monchoun** [dotnet/core#4979]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
OS: windows 10
when I run the command in cmd 
Assets file '/src/C:/Users/xxxx/myMicroservice/obj/project.assets.json' not found.

**Comment by mairaw** [comment]
Can you help with this @shirhatti @nishanil?

**Comment by mairaw** [comment]
Closing since an old issue but @Monchoun please let us know if this is still an issue with the current version of the tutorial and .NET.
