### ISSUE TITLE
Validation Error in YAML

### ISSUE THREAD

**Issue by gopkumr** [dotnet/core#4982]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
**Operating System**: windows
**az version**: 
```
 "azure-cli": "2.9.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
```
**kubectl version**: 
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

While using the exact YAML as mentioned in the webpage,  kubectl throws couple of validation errors
**The first error**
```
> kubectl apply -f deploy-myMicroservice.yaml
error: unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
```
Fix to this is to change the apiVersion to apps/v1 in deployment

**The second error**
`error: error validating "deploy-myMicroservice.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false`

Fix to this error is to add a selector as below to the Deployment, match the label in the Service
```
selector:
      matchLabels:
       app: mymicroservice
```
Attaching the corrected YAML file that worked for me. Please review and advice if it is the kubectl version that i have causing the validation error.
[deploy-myMicroservice.yaml.txt](https://github.com/dotnet/core/files/4963777/deploy-myMicroservice.yaml.txt)

**Comment by scalablecory** [comment]
@shirhatti can you please help?

**Comment by mairaw** [comment]
This should be fixed by https://github.com/dotnet/website/pull/2118. I just want to review the tutorial one more time to make sure everything is working.

**Comment by gopkumr** [comment]
@mairaw I am not able to find a pull request #2118, the above gives me a 404.

**Comment by mairaw** [comment]
Apologies for not responding. That was in a private repo.
The tutorial should be working for .NET 8 now.
