### ISSUE TITLE
error parsing deploy-myMicroservice.yaml: error converting YAML to JSON: yaml

### ISSUE THREAD

**Issue by Ron-Zhong** [dotnet/core#4988]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I encountered an issue on running deployment with this command "kubectl apply -f deploy-myMicroservice.yaml"

![2020-07-24_175516](https://user-images.githubusercontent.com/43414651/88380351-fc6e3d80-cdd6-11ea-9a61-be1b9aed8317.png)

**Comment by som-nitjsr** [comment]
with aks 1.16 v1Beta api is deprecated please use this code.

apiVersion: apps/v1
kind: Deployment
metadata:

you also need to updated selector
as
https://github.com/dotnet/core/issues/5027

**Comment by mairaw** [comment]
We have deployed a fix to that page. Please let us know if you're still having issues.
