### ISSUE TITLE
Help with using Blazor

### ISSUE THREAD

**Issue by Waifer** [dotnet/core#4989]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

These all had errors.

**Comment by scalablecory** [comment]
What version of .NET are you running?

Have you created your project with the commands listed here? https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
