### ISSUE TITLE
  It was not possible to find any installed .NET Core SDKs   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:       https://aka.ms/dotnet-download

### ISSUE THREAD

**Issue by ashish53552** [dotnet/core#4993]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Maybe you've installed the .NET runtime instead of the SDK @ashish53552?

What's the output of the following command on your machine?
`dotnet --list-sdks`
