### ISSUE TITLE
Blazor server confusion with button onclick

### ISSUE THREAD

**Issue by lxman** [dotnet/core#4996]
Minimum repro here: https://github.com/lxman/TestCommunicate

So, in short, I am creating a list of SubComponent's on the index page. The first thing I am seeing is that whenever each SubComponent is initially created, the onclick seems to be firing. Is this normal? Or have I set something up incorrectly? The objective is to create a list of these things, then when I click on one of them, it disappears from the list, but I can't seem to get the signalling worked out.

One other odd thing I have seen as well. In attempting to figure this out, I moved my list initialization code from OnInitialized to OnAfterRender. When I do, I see that OnAfterRender is only called a single time with firstRender=true. I'm a bit confused by this as well.

**Comment by mairaw** [comment]
Tagging @danroth27 - Should this issue be transferred to a different repo?

**Comment by lxman** [comment]
Yeah, sorry, guess this should rather be aspnetcore - I'll close and move there.
