### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, an executable program or an order file

### ISSUE THREAD

**Issue by JackBN93** [dotnet/core#5001]
### .NET command failed when typing "dotnet" in the command prompt
Operating System: windows

**'dotnet' is not recognized as an internal or external command, an executable program or an order file.**

![dotnet command failed](https://user-images.githubusercontent.com/39662461/88828092-63269900-d1d3-11ea-8adb-6136eab82de7.JPG)

**Comment by mairaw** [comment]
Are you sure you have it installed? You can check on the install locations to see if the runtime/sdk is installed on your machine
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows#check-for-install-folders
