### ISSUE TITLE
How does System.Int32.CompareTo(int) work?

### ISSUE THREAD

**Issue by Alvin-Seville** [dotnet/core#5002]
Hello everyone! How does System.Int32.CompareTo(int) [System.Int32.CompareTo(int)](https://source.dot.net/#System.Private.CoreLib/Int32.cs,50) work? I mean by it the following question: How can we use `<`/`>` operators when they are not explicitly overloaded within Int32 type? Where are they defined?
```C#
        public int CompareTo(int value)
        {
            // NOTE: Cannot use return (_value - value) as this causes a wrap
            // around in cases where _value - value > MaxValue.
            if (m_value < value) return -1;
            if (m_value > value) return 1;
            return 0;
        }
```

**Comment by bartonjs** [comment]
By "explicitly" do you mean the "this." syntax? 

https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md

> 4. We avoid `this.` unless absolutely necessary.

**Comment by Alvin-Seville** [comment]
> By "explicitly" do you mean the "this." syntax?

No, don't. Sorry for my mistake. I've fixed my question above:

> How can we use `<`/`>` signs when they are not explicitly overloaded? Where are they defined?

**Comment by KalleOlaviNiemitalo** [comment]
The C# compiler translates the `<` and `>` operators of `int` to Common Intermediate Language (CIL) comparison instructions (`clt`, `cgt`), not to method calls.
