### ISSUE TITLE
Concerns about .Net frameworks support in ASP.NET Core

### ISSUE THREAD

**Issue by manikandan05** [dotnet/core#501]
Hi,

Initially, i have developed my library project with multiple framework support(net451 ,net452, net46, net461, net462). So, i have defined this framework version entries in my project.json file.

The generated Class library also working fine based on framework version (net451 to net462) wise applications without any issues.

Now i have modified my **project.json** entry to net451 alone. But this new entry also will resolve the remaining frameworks requirement such as net452 to net462.  

Meanwhile, if there is any framework related changes have rolled out? If its means can you please share those details.

Thanks.

**Comment by Petermarcu** [comment]
Hi @manikandan05 , I'm not sure I completely understand. You are correct that one library targeting net451 will be able to run on higher versions like net462. Are you asking whether you should be worried whether it will run on newer versions that come out? If so, it will always be loadable on future .NET Framework versions and those releases always maintain a very high compatibility guarantee.

If you are asking something else, can you clarify?

**Comment by manikandan05** [comment]
Hi @Petermarcu ,

Thanks for your detailed information.

I have an another one concern, when i have create a WebApplication(.NET Core) from Visual Studio 2015, the project created with netcoreapp1.0 framework entry in project.json.

During project creation time, we have framework selection combobox in project creation window. If i have choose any framework means, the selected framework will influenced in my (netcoreapp) project in any one places (cases) or not?

If its not affected means, then why framework selection options available during .NET Core application creation time.

![sshot-4](https://cloud.githubusercontent.com/assets/5366630/23014487/434ed12e-f455-11e6-98b5-b0a8b855712c.png)


Thanks,

**Comment by Petermarcu** [comment]
I dont know that that drop down does anything for you. For sure, it doesn't impact your .NET Core application. Those were preview tools and many of the aspects of the UI were not finished. You should try the most recent release of Visual Studio 2017 if you are getting started. It will get you on a much happier path.

**Comment by manikandan05** [comment]
Hi @Petermarcu,

I have one final concern as, in ASP.NET Core projects netcoreapp1.0, netcoreapp1.1 and netstandard1.6 have some default entry values like 

`"netcoreapp1.0": {
      "imports": [
        **"dotnet5.6",
        "portable-net45+win8"**
      ]
    }`


In this above code blocks, i need to know the imports section and its values!

Thanks.

**Comment by Petermarcu** [comment]
What that is telling NuGet is to allow you to reference libraries that say they support dotnet5.6 and portable-net45+win8. In general, the goal should be to not need them. 

@DamianEdwards , is there still a need for ASP.NET 1.0 apps to have imports?

**Comment by DamianEdwards** [comment]
Generally no. Depends on what you reference, but some of our less common packages have dependencies that used to require it that have since update to support netstandard directly, e.g. Microsoft.AspNetCore.AzureAppServices. In those cases you can often fix by adding a direct dependency to the new version of the package, e.g. WindowsAzure.Storage

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
