### ISSUE TITLE
Green WebDeveloper trying to learn

### ISSUE THREAD

**Issue by IanPerkins87** [dotnet/core#5011]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

---"Basically I am running into an issue creating a text web service on the ASP.NET framework. I am currently enrolled for online courses through WGU for my BS in computer science but I have no one to help guide me on this path Im on. Any assistance would be very much appreciated. Ill buy you a bottle of (Preferred Liquor) for being helpful and inciteful."

**Comment by mairaw** [comment]
I think we'd need more information to be able to help you. What do you have so far? Where exactly are you stuck on your code? Where do you need help?
