### ISSUE TITLE
CoreCLR path

### ISSUE THREAD

**Issue by PeFF1** [dotnet/core#5015]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try to create an application through "dotnet new console -o name". I get an error like "Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1", the application was not created, did not touch anything.

CoreCLR path visible everytime,
dotnet console -o name - CoreCLR error
dotnet --version - CoreCLR error
Screenshot:
![image](https://user-images.githubusercontent.com/66828796/89339234-7f7c7700-d6a6-11ea-84d5-33fb987982c3.png)

Please help.

**Comment by mairaw** [comment]
@KathleenDollard @richlander I've never seen this error before and similar issues were closed with no resolution:
https://github.com/dotnet/sdk/issues/8530

Any ideas what to try here? Reinstall the SDK perhaps?

**Comment by mairaw** [comment]
Closing since this is an old issue. Please let us know if this is still an issue.

Make sure you're following the advice from https://github.com/dotnet/sdk/issues/8530#issuecomment-318207494.
