### ISSUE TITLE
Add support for Ubuntu 20.10 "Groovy Gorilla"

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5017]
This issue is created to track progress for the work to enable Ubuntu 20.10 support for .NET Core 3.1, 2.1 and .NET 5.

### Product and Test updates
- [x] [All teams] Do a compatibility check for the product with the new OS
- [x] [CoreCLR/CoreFX] Runtime / RID Support update 
- [x] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable) 
- [x] [Infra] Replace docker tags used in builds across repos and branches
- [x] [CLI team] Update CI legs to latest updated Dockerfile 
- [x] [All teams] Update test infrastructure to support the new version
- [x] [Acquisition] Add support within nightly repos 
- [x] [Acquisition] Deploy to master (GA) during next patch release cycle        

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [x] Add feed for new OS release to packages.microsoft.com
- [x]  Update release manifest files 
- [x] Create new Docker files to test the new OS 
- [x] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [x] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by Mizux** [comment]
FYI while Ubuntu 20.10 is due for release on October 22, 2020.
ref: https://www.omgubuntu.co.uk/2020/05/ubuntu-20-10-release-features

You can already found docker image on DockerHub...

my test:
```Dockerfile
# Create a virtual environment with all tools installed
# ref: https://hub.docker.com/_/ubuntu
FROM ubuntu:20.10 AS env

RUN apt update -q
RUN apt install -y wget apt-transport-https

# Dotnet Install
# see: https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-2010
RUN wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt update -q
RUN apt install -yq dotnet-sdk-3.1

# Trigger first run experience by running arbitrary cmd
RUN dotnet --info
```

```sh
docker build .
```

**Comment by richlander** [comment]
FYI: We only publish container images for Ubuntu LTS releases.

**Comment by Mizux** [comment]
To avoid any ambiguity, I don't want any container image, I only need an **Ubuntu 20.10** `dotnet-sdk-3.1` feed so I can integrate it in our Google OR-Tools docker container to provide our .Net native prebuilt binaries...
ref: https://github.com/google/or-tools/blob/stable/tools/docker/ubuntu-20.10.Dockerfile

The simplify Dockerfile above is just a way to reproduce the error and what I'm looking for unless for 20.10 you'll manage to integrate dotnet-sdk directly into an official ubuntu feed ?

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/issues/5352

**Comment by dagood** [comment]
> .NET Core 3.1 and .NET 5.

Missing .NET Core 2.1?

**Comment by rbhanda** [comment]
Updated the issue with 2.1 as well. I am able to install both on Ubuntu 20.10

**Comment by dagood** [comment]
Neither 3.1 or 2.1 works for me using the package repository, for the same underlying reason installing 5.0-rc2 via `.deb` doesn't work.

**Comment by rbhanda** [comment]
@jamshedd FYI.

**Comment by Mizux** [comment]
FYI `ubuntu:rolling` has been bumped to Ubuntu 20.10, hope you'll fix your `libicu` usage ASAP...
ref: https://hub.docker.com/_/ubuntu

**Comment by Entomy** [comment]
~~~~
The following packages have unmet dependencies:
 dotnet-runtime-deps-2.1 : Depends: libicu but it is not installable or
                                    libicu66 but it is not installable or
                                    libicu65 but it is not installable or
                                    libicu63 but it is not installable or
                                    libicu60 but it is not installable or
                                    libicu57 but it is not installable or
                                    libicu55 but it is not installable or
                                    libicu52 but it is not installable
E: Unable to correct problems, you have held broken packages.
~~~~

Looks like the package is up, but in a broken state.

**Comment by rbhanda** [comment]
@Entomy thanks a lot for letting us know.  This is a known issue and a workaround has been posted on https://github.com/dotnet/core/issues/5352. Hope this helps

**Comment by Mizux** [comment]
Seems fixed today !
ref: https://github.com/dotnet/core/issues/5549#issuecomment-728362949

EDIT: Tested using my Dockerfile above

**Comment by dagood** [comment]
New packages were pushed for 5.0 and 3.1 to support Ubuntu 20.10, but not 2.1.

(`dotnet-sdk-2.1` still fails to install because `dotnet-runtime-deps-2.1` isn't compatible with Ubuntu 20.10. More info and workarounds at https://github.com/dotnet/core/issues/5352.)

**Comment by richlander** [comment]
Is this issue still active, or can it be closed?

**Comment by dagood** [comment]
`dotnet-sdk-2.1` now installs fine for me in an Ubuntu 20.10 container. There are still checkboxes open in the original issue so leaving it to @rbhanda to close if this is done.

**Comment by rbhanda** [comment]
This issue can be closed now.
