### ISSUE TITLE
Kubernetes error while running the deploy command

### ISSUE THREAD

**Issue by shahid-aman** [dotnet/core#5025]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I get an error when I try to run the deployment using this command:
$ kubectl apply -f deploy-myMicroservice.yaml

Error:
error: unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

**Comment by som-nitjsr** [comment]
with aks 1.16 v1Beta api is deprecated please use this code.

apiVersion: apps/v1
kind: Deployment
metadata:

**Comment by mairaw** [comment]
We deployed a fix to that page. Let us know if you're still having issues.
