### ISSUE TITLE
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

### ISSUE THREAD

**Issue by matshuis** [dotnet/core#5030]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

When I try to build I get an error. Below my cmd line output:

C:\Source\fls_ui\docker>docker build -t mymicroservice .
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
3.1: Pulling from dotnet/core/sdk
e8a609e7f617: Pull complete                                                                                             85e8dcd726b8: Pull complete                                                                                             1c6a1cdcb0f4: Pull complete                                                                                             3bf9faae7b18: Pull complete                                                                                             168d108c14b7: Pull complete                                                                                             80716ffc45f2: Pull complete                                                                                             7236ad6eb235: Pull complete                                                                                             44136ca5d3ab: Pull complete                                                                                             f1bcfee7f430: Pull complete                                                                                             6ea68ad1830a: Pull complete                                                                                             8d1b65661f1e: Pull complete                                                                                             5fbcaaa94361: Pull complete                                                                                             e5b883ac7270: Pull complete                                                                                             111c01d91634: Pull complete                                                                                             Digest: sha256:fa51d32593444097f2143e523abf1f97ff9dd58ee280b61f0a16ebe90c4237c2
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1
 ---> ac643c048209
Step 2/10 : WORKDIR /src
 ---> Running in 445050d4e652
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

**Comment by eriawan** [comment]
This problem is Docker for Windows problem, not .NET Core container images related, because it is already described in Docker for Windows issue below.
I have experienced this and I can confirm that it already exists not just when using .NET Core SDK container, but when running docker build on Windows.

See the troubleshooting workaround on this Docker for Windows issue: https://github.com/docker/for-win/issues/3884
Just follow the workarounds there, especially if the machine used to build docker image has some file sharing app installed such as Dropbox, box.com, CBFS.

Could somebody close this issue?

cc @richlander @rbhanda @mairaw

**Comment by matshuis** [comment]
Ok, tnx for the input
