### ISSUE TITLE
.net v4.5 installed but IDE is not visible in start menu, desktop . Suggestion plz

### ISSUE THREAD

**Issue by jhatwar** [dotnet/core#5031]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
I'm a bit confused since the tutorial doesn't use .net v4.5 and it's not about an IDE.

If this is an issue with Visual Studio, I'd recommend filing an issue at https://developercommunity.visualstudio.com/spaces/8/index.html.
