### ISSUE TITLE
Couldn't find a project to run. Ensure a project exists in D:\C#, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by Swarajsm** [dotnet/core#5037]
# Issue Title
I am trying to get started with C#. I have installed .Net SDK in my C drive (I think) and saved the hello world code sample in D drive. Whenever I try 

> dotnet run  
I get this error message 

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by svick** [comment]
What exactly is the content of the directory D:\C#? Also, it might be easier to properly create a hello world project by running `dotnet new console`.

**Comment by Swarajsm** [comment]
I have my hello world.cs in that directory I am currently using Visual Studio for C# and I feel more comfortable while using VSCode

**Comment by svick** [comment]
Just a .cs file is not enough, you also need a .csproj file. Have you tried `dotnet new console`, as I suggested?

**Comment by firdavszamirov** [comment]
> Just a .cs file is not enough, you also need a .csproj file. Have you tried `dotnet new console`, as I suggested?

thanks

**Comment by GmbTheGreat** [comment]
> Just a .cs file is not enough, you also need a .csproj file. Have you tried `dotnet new console`, as I suggested?

Thank you ♥

**Comment by charlieeustache-oss** [comment]
> Just a .cs file is not enough, you also need a .csproj file. Have you tried `dotnet new console`, as I suggested?

thanks

**Comment by Ledana** [comment]
you should do cd: "path to your project file" in the terminal
