### ISSUE TITLE
Dotnet cannot be found on my device

### ISSUE THREAD

**Issue by nethertoastcodes** [dotnet/core#5038]
Im using windows visual studio code, and when I went to create a new console 

'dotnet new console'

and I got this error code: 

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function,      
script file, or operable program. Check the spelling of the name, or if a path was   
included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet new console
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundEx  
   ception
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by svick** [comment]
Did you install [the .Net Core SDK](https://dotnet.microsoft.com/download)?
