### ISSUE TITLE
ImmutableDictionary.GetValueOrDefault's return value is not marked as possibly returning null

### ISSUE THREAD

**Issue by dmytro-gokun** [dotnet/core#5041]
As a result it does not produce an expected warning when compiling with &lt;Nullable&gt;enable&lt;/Nullable&gt;

```
ImmutableDictionary<string, string> dict = ...;
foo(dict.GetValueOrDefault('a')); <-- A warning is expected here

void foo(string s)
{
}

```

In contrast:

```
public static class CollectionExtensions
{
        [return: MaybeNull]		<-- here we have it
        public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key) where TKey : notnull
        {
            return dictionary.GetValueOrDefault(key, default);
        }


}
```

**Comment by svick** [comment]
This seems to be already fixed on .Net 5 preview 7. I compiled the following code there (with `<Nullable>enable</Nullable>`):

```c#
ImmutableDictionary<string, string> dict = ImmutableDictionary.Create<string, string>();
foo(dict.GetValueOrDefault("a"));

void foo(string s)
{
}
```

And I got:

> warning CS8604: Possible null reference argument for parameter 's' in 'void foo(string s)'.

**Comment by dmytro-gokun** [comment]
@svick Great, thanks! I'm not sure though if I have to close this issue right away or wait till .NET is officially out :)
