### ISSUE TITLE
NETSDK1

### ISSUE THREAD

**Issue by nkpresh** [dotnet/core#5044]
Unable to use C:\Program files\dotnet\packs as application host executable as it does not contain the expected placeholder byte sequence

**Comment by svick** [comment]
What is the context? What were you doing when you got that error?

**Comment by nkpresh** [comment]
I just created a new project and ran it; that's all

**Comment by nkpresh** [comment]
I resolved it by downloading the nutget package for it
Thanks for your help

**Comment by kcee1** [comment]
Please I am having this same issue with visual studio 2019. I created a .net core project and it refuse to build. Please which nugget package did you install

**Comment by mairaw** [comment]
@kcee1 please open a new issue with more details about error message, version, etc.
