### ISSUE TITLE
Cannot find hostfxr.dll on Windows after the last VS2019 update

### ISSUE THREAD

**Issue by GhostyJade** [dotnet/core#5054]
# General

I'm developing a console application using .NET Core 3.1 and Visual Studio 2019 on Windows 10 20H2 (Build 19042.423).
After the latest VS2019 update (v16.7.0), when I launch the debug of a .NET Core applcation, it doesn't start and in the console there's the following output:
```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [H:\Github Projects\ControllizerDeck\ControllizerDeckProject\ControllizerDeckProject\bin\Release\netcoreapp3.1\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64
```

The dotnet sdk is installed in C:\Program Files\dotnet. I've also tried to run (from a terminal) ```dotnet --info``` but the result is that ```A fatal error occurred. The folder [C:\Program Files\dotnet\host\fxr] does not exist```.

I really don't think this is normal.

**Comment by carlossanlop** [comment]
Since this happened after a VS upgrade, my suggestion is that you report this issue to them: https://developercommunity.visualstudio.com/content/problem/post.html?space=8
