### ISSUE TITLE
could not find my app program.cs to put in HELLO WORLD

### ISSUE THREAD

**Issue by pruthford101** [dotnet/core#5055]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
program.cs is a file, not an app. It should be available in the folder you created after you executed the command to create a new console application.

I'll close this since it's been resolved.
