### ISSUE TITLE
dotnet core::Unable to run your project. Ensure you have a runnable project type and ensure 'dotnet run' supports this project

### ISSUE THREAD

**Issue by guijoe** [dotnet/core#5060]
I have been running into an error lately trying to run some code with dotnetcore. When I try to run the project in the console (dotnet run), I get this error.

    Unable to run your project. Ensure you have a runnable project type and ensure 'dotnet run' supports this project. A runnable project should target a runnable TFM (for instance, netcoreapp2.0) and have OutputType 'Exe'. The current OutputType is 'Exe'.

FYI, here are entries in the .csproj file
![image](https://user-images.githubusercontent.com/10955674/89974784-e9bf8980-dc5b-11ea-90e7-4727421ab697.png)

Also, I have the following skds and runtimes installed. Yet, whatever TargetFramework I set in the .csproj, I get the same error.
![image](https://user-images.githubusercontent.com/10955674/89974828-065bc180-dc5c-11ea-8746-1ecd16cd59ec.png)

Furthermore, I have tried specifying the target framework with the run command, the result remains the same.

Any help would be appreciated. Many thanks !

**Comment by carlossanlop** [comment]
@wli3 @dsplaisted is this something you can help with?

@guijoe are you still facing this problem?

**Comment by dsplaisted** [comment]
If you can [provide a binlog](https://aka.ms/binlog) for a build of the project, that would probably enable us to figure out why you are getting this error.
