### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Susan1969** [dotnet/core#5063]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GeraudFabien** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**_problem you're experiencing :_** 
The problem i experience and i"m not sure how anyone can help you without more information.   

**_operating system version;_** 
 I'm on Windows 10 but work on docker not sure it's relevant.    

**_code sample, and anything else that is relevant._** 
Maybe you should describe what happend, submit an error message or take a screenshot.
