### ISSUE TITLE
i don't know how to open Index.cshtml from command prompt.

### ISSUE THREAD

**Issue by Rakeshpt300** [dotnet/core#5066]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
You need to open the file with a text editor. The tutorial says it explicitly:
>Open `Pages/Index.cshtml` in any **text editor**
I'll close the issue since this question is resolved.
