### ISSUE TITLE
Firefox can’t establish a connection to the server at localhost:5000.

### ISSUE THREAD

**Issue by hudthabit** [dotnet/core#5072]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you share some screenshots of the command window and the browser window so we can try to see what's going on?
