### ISSUE TITLE
Assembly.Evidence, Assembly.PermissionSet Properties replacement in .NET core

### ISSUE THREAD

**Issue by asbrum** [dotnet/core#5073]
In .NET Framework following properties were present on System.Reflection.Assembly

- Evidence
[https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.evidence?view=netframework-4.7.2](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.evidence?view=netframework-4.7.2)
- PermissionSet
  [https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.permissionset?view=netframework-4.7.2](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.permissionset?view=netframework-4.7.2)

Is there a way to query these properties from System.Reflection.Assembly in .NET Core?

Code example .NET Framework 4.7.2:
```
var assembly = System.Reflection.Assembly.Load("assemblystring");

var zone = assembly.Evidence.GetHostEvidence<Zone>();
var permissions = assembly.PermissionSet.Count;

```

**Comment by davidfowl** [comment]
the entire idea is gone in .net core. There is no more code access security cc @jkotas

**Comment by jkotas** [comment]
Yes, these properties were part of Code Access Security that is gone in .NET Core.
