### ISSUE TITLE
hello-world-tutorial

### ISSUE THREAD

**Issue by PeFF1** [dotnet/core#5075]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\Name>dotnet new console -o myApp
Cannot use stream for resource [C:\Program Files\dotnet\dotnet.deps.json]: No such file or directory
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1

**Comment by mairaw** [comment]
Should we reopen #4825 @PeFF1 and close this one? We have a couple of folks on that thread already.
