### ISSUE TITLE
kubectl apply -f deploy-myMicroservice.yaml command throwing error

### ISSUE THREAD

**Issue by zaaro** [dotnet/core#5082]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I have encountered following error while running kubectl apply -f deploy-myMicroservice.yaml command. I have followed all the steps in the tutorial. 
error: unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

deploy-myMicroservice.yaml file content : ---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: [YOUR DOCKER ID]/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: mymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice

**Comment by som-nitjsr** [comment]
@zaaro  Please follow https://github.com/dotnet/core/issues/5027#issuecomment-671236544

**Comment by mairaw** [comment]
We have deployed a fix. Please let us know if you're still having issues with the tutorial.
