### ISSUE TITLE
X509Certificate2::ctor(byte[]) works differently on Windows/Linux

### ISSUE THREAD

**Issue by vipeller** [dotnet/core#5086]
Want to process some incoming certificates encoded in PEM format. On windows, if I use:

new X509Certificate2(Encoding.ASCII.GetBytes(pemCertString));

that works fine. Actually, windows can figure out different formats, it can be a base64 encoded certificate without the PEM frame or the DER certificate itself, it can process whatever the passed byte array contains

on Linux it seems much more picky and the constructor that gets a byte[], only accepts a DER certificate. Now what I can do is to trim the PEM frame, base64 decode the remaining data, and pass the resulting DER certificate to the constructor.

Is there any more elegant solution than the following:

'
const string PemHeader = "-----BEGIN CERTIFICATE-----";
const string PemFooter = "-----END CERTIFICATE-----";

var certificateContent = Convert.FromBase64String(TrimPemFrame(encodedCertificate));
var certificate = new X509Certificate2(certificateContent);

static string TrimPemFrame(string pemEncoded)
{
   var result = pemEncoded.Trim();
   if (result.StartsWith(PemHeader))
   {
     result = result.Substring(PemHeader.Length);
   }

   if (result.EndsWith(PemFooter))
   {
     result = result.Substring(0, result.Length - PemFooter.Length);
   }

   return result;
}
`

**Comment by bartonjs** [comment]
The constructor on Linux accepts ASCII-encoded PEM-encoded certificates as well as DER-encoded certificates and PFX files.  It doesn't accept unarmored base64, and currently doesn't understand processing PKCS#7 the same way that the Windows constructor does.

**Comment by vipeller** [comment]
@bartonjs So you are saying that if I have a PEM certificate like this:

        private static readonly string ThumbprintTestCert =
"-----BEGIN CERTIFICATE-----" +
"MIICHDCCAX6gAwIBAgIJANqy0HwrEJqpMAoGCCqGSM49BAMCMB8xHTAbBgNVBAMM" +
.... / removed some lines
"K3X3YDtLgTQA01umm/XY5Q==" +
"-----END CERTIFICATE-----";

and I use it as:

var cer = new X509Certificate2(Encoding.ASCII.GetBytes(ThumbprintTestCert));

It should work? Unfortunately, I am getting the following error:

Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at CertParse.Program.Main(String[] args) in /mnt/d/dev/QuickTests/CertParse/Program.cs:line 29

The same error, if I remove the begin/end certificate lines, so I have the base64 encoded certificate. It works only on linux (I try with WSL right now), if I manually base64 decode the string and pass the received DER format to the constructor, like in the example in my first post.

**Comment by bartonjs** [comment]
Do you have the required newlines at the end of `-----BEGIN CERTIFICATE-----` and before `-----END CERTIFICATE-----`?

I don't believe OpenSSL's PEM parser cares about newlines after every 64 characters of base64 text, but I believe it does care about those two mandatory newlines.

```
-----BEGIN CERTIFICATE-----
base64
-----END CERTIFICATE-----
`````

**Comment by vipeller** [comment]
@bartonjs yes, that was it, the newlines! Thanks, closing it now.

**Comment by madelson** [comment]
@bartonjs is there a plan to make this class work consistently across platforms?
