### ISSUE TITLE
Help with version soup

### ISSUE THREAD

**Issue by refack** [dotnet/core#509]
Could someone help me understand the version soup.
There's 1.0.x and 1.1 and now 2.0preview, what's the difference, and the hierarchy?
As for the `dotnet` cli tool, I've got one that came with `dotnet-dev-win-x64.1.0.0-rc4-004771` it's signature is `1.0.1.4500` and an older one who's signature is `1.1.0.1179` which one should I use?

**Comment by refack** [comment]
P.S. When do I use `project.json` and when `myname.csproj`?

**Comment by leecow** [comment]
@refack - soup is a good description! We have not been very successful in helping folks track along as the Shared Framework and SDK progressed at different rates. Certainly something we are working to remedy in 2.0. 

The primary version split is between the project.json based tools, which we are moving away from, and csproj. The Shared Framework doesn't have any restriction so you can target any version using either project type. The following have been pre-releases of SDK 1.0.

* SDK Preview 2 and 2.1 support project.json
* SDK Preview 3+ and the recent RC3 and RC4 support csproj

1.0.x and 1.1 refer to Share Framework (Microsoft.NETCore.App) version as the .NET Core "umbrella".

Let me know if this was helpful or if I've just stirred the pot :-)

**Comment by refack** [comment]
Thank you so much @leecow 
We're getting there. So `project.json` = old SDK tools (bye, bye 😢) => `*.csproj` new SDK tools...


Now please help me understand my accumulated tree:
![image](https://cloud.githubusercontent.com/assets/96947/23085258/a8eb334e-f534-11e6-885e-58a40597f049.png)
What's the `host`?
What's the `2.xxx` in the `SDK` if you're talking about __SDK 1.0 RC4__?
And what's in `Shared`?

**Comment by Petermarcu** [comment]
dotnet.exe from the dotnet folder loads the latest host on the machine which will be able to load any framework older than it.

host == the thing that launches your application on a framework.

Shared contains the "framework" which is a copy of everything in netcoreappX.X including the clr and bcl. You can have a bunch of applications that don't carry the framework with them and can all run on a shared copy of them. That is the default. If you publish standalone, then the whole framework will get put with your app.

2.X.X is the 2.X.X SDK which is the next release, you must have gotten a daily build from the repo? That one will be msbuild based.

I'm not sure why the SDK chose alpha and the framework chose beta but those match up.

Does that help?

**Comment by refack** [comment]
@Petermarcu , yes thank you very much! A thick soup indeed...
(So even though SDK 1.0 is in RC, there's work on nextgen 2.0?! that actually nice)

**Comment by Petermarcu** [comment]
Yeah, 1.0 is finishing up and will be releasing soon. Some of us are getting out in front to make sure we have a 2.0 sdk to start from when the larger team shifts focus.
