### ISSUE TITLE
after I keyed dotnet run, 4 'info' appeared and hung forever. windows 10

### ISSUE THREAD

**Issue by TJ-beginner** [dotnet/core#5093]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![dotnetrun](https://user-images.githubusercontent.com/70000605/90848404-67437200-e39f-11ea-9bb4-8bbeba3261ae.JPG)

![image](https://user-images.githubusercontent.com/70000605/90848379-5135b180-e39f-11ea-99aa-452314c136fc.png)

**Comment by svick** [comment]
As both the tutorial and the output of the command explain, to see the web app, you should navigate to `http://localhost:5000` in your browser. Did you try that?

**Comment by ashrafulais** [comment]
Let me show you fully:
Select the text that says: `http://localhost:5000` and press `Ctrl+Insert` or just copy the URL that shows in your command prompt as shown in the image. (marked 1), paste the URL in your browser and voila, you will see your first .NET Core app running! 

If you want to shut down the running server, press `Ctrl+C` 
![dotnetRun](https://user-images.githubusercontent.com/22434190/91088807-76af0d80-e674-11ea-9baa-4179fa31c07f.png)

**Comment by danmosemsft** [comment]
@TJ-beginner does this help?

**Comment by TJ-beginner** [comment]
yes. see attached.
thank you very much.

[image: image.png]


Regards,
TJ Foo

**Comment by danmosemsft** [comment]
Ok I'll close then. Thanks for confirming
