### ISSUE TITLE
Default destination folder for Windows MSI is incompatible

### ISSUE THREAD

**Issue by Annih** [dotnet/core#51]
Hello,

Default installation path for the official MSI is `C:\Program Files\dotnet\`, but it seems that dotnet core doesn't like space in its path - see #50.

Because of that, following the [Getting started guide](http://dotnet.github.io/getting-started/) lead to this obscure error message:
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Program' or one of its dependencies. The system cannot find the file specified.

I think we should either fix the crash reported in #50, or change the default path to something else.

Regards

--
Annih

**Comment by mairaw** [comment]
@blackdwarf You mentioned someone was working on a fix for this, correct?

**Comment by blackdwarf** [comment]
@mairaw yup.

**Comment by Annih** [comment]
Seems to be fixed in `1.0.1.001091 dev` but I couldn't find the commit that fixed this
