### ISSUE TITLE
Micorsoft team needs to revisit this is not working

### ISSUE THREAD

**Issue by sachindabas** [dotnet/core#5101]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmosemsft** [comment]
Hello, this isn't enough information for us to investigate. Can you say more about what you are encountering?
