### ISSUE TITLE
The current .Net SDK does not support targeting .Net Core 3.1.

### ISSUE THREAD

**Issue by Millstream30** [dotnet/core#5105]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\>dotnet --version 
returns
3.1.101

As soon as I open the console project using Visual Studio Enterprise 2019 Version 16.0.4 I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.	myApp	C:\Program Files\dotnet\sdk\2.2.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137

**Comment by Millstream30** [comment]
Needed to update to Visual Studio 2019 v16.5+.

**Comment by Millstream30** [comment]
Needed to update to Visual Studio 2019 v16.5+.

**Comment by Millstream30** [comment]
Needed to update to Visual Studio 2019 v16.5+.

**Comment by Millstream30** [comment]
Needed to update to Visual Studio 2019 v16.5+.

**Comment by Millstream30** [comment]
Needed to update to Visual Studio 2019 v16.5+.

**Comment by Millstream30** [comment]
resolved

**Comment by Millstream30** [comment]
resolved

**Comment by Millstream30** [comment]
Needed to update to Visual Studio 2019 v16.5+.

**Comment by mairaw** [comment]
Correct! Given that it seems your problem is resolved, I'm closing this issue.
