### ISSUE TITLE
.NET Core Preview - links and install instructions missing for Windows ARM64 installers

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/core#5110]
Links and install instructions missing for Windows ARM64 installers

Issue:

1) Links to Windows installers in the preview release notes are not available for:
ARM64 .NET runtime and Windows Desktop runtime installers

Affected files:
Missing links to Windows ARM64 installers.

Expectation:
The links for Windows ARM64 .NET Runtime and Windows Desktop installers and possibly install instruction can be found in the release notes - very similar to other targets

**Comment by mairaw** [comment]
@rbhanda can you take a look at this issue?

**Comment by rbhanda** [comment]
This is covered in our current [release notes](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.8.md).

@NikolaMilosavljevic can we close this issue?
