### ISSUE TITLE
installed but not installed

### ISSUE THREAD

**Issue by unraujoe** [dotnet/core#5111]
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by danmosemsft** [comment]
Could you give us more information? Is `dotnet` in your path?

**Comment by unraujoe** [comment]
That is a very good question, and I am not sure. I have been able to start a chatbot emulator by going to settings, toggling use custom runtime, and then clicking get a new copy of runtime code. But i have not been able to get a bot that answers anything

**Comment by mairaw** [comment]
Maybe this article can help to figure out if it's really installed:
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows

Also, after you installed, make sure you opened a new prompt or terminal.

**Comment by unraujoe** [comment]
Hi, I am pretty sure it is installed, I was actually looking for help on the botFramework composer but it took me here! Thanks for the help everyone
