### ISSUE TITLE
5.0.0-preview.8 in releases.json lists dotnet-runtime-win-arm64.exe RID as win-x86 rather than win-arm64

### ISSUE THREAD

**Issue by dagood** [dotnet/core#5118]
https://github.com/dotnet/core/blob/d594843acebe3e289e0ed9205dc076b8052f2ce0/release-notes/5.0/releases.json#L99-L104

Not sure if this affects anyone, but I saw it and it seems unexpected. 😄 

@rbhanda @NikolaMilosavljevic

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/5119 for this issue
