### ISSUE TITLE
rider debug problem

### ISSUE THREAD

**Issue by zhangweilun** [dotnet/core#512]
my rider ide tell me I can not debug the the dotnet core,and the jetbrains tell me the problem is about the license, I want to know why have this problem, dotnet core is not open source?

**Comment by svick** [comment]
I think you're talking about the same issue as https://github.com/dotnet/core/issues/505, right? In that case, this issue should probably be closed as duplicate.

**Comment by Petermarcu** [comment]
Closing as dupe of https://github.com/dotnet/core/issues/505
