### ISSUE TITLE
How to use CA certificate in development instead of self-signed certificate in ubuntu server

### ISSUE THREAD

**Issue by Chewhern** [dotnet/core#5128]
I have put 2 URLs under launchsettings.JSON one is 0.0.0.0:5000(http) and the other one was 0.0.0.0:5001(https), I will need step by step working examples to let the https URL able to use the CA certificate that I have bought online.

If further clarification is needed, i will be glad to fill you in with details as long as i can use the CA certificate instead of self-signed certificate..

Any help from experts will be really much appreciated

**Comment by davidfowl** [comment]
Do you have a private key and a ssl certificate from the CA? Do yo have a pfx file or a PEM encoded certificate?

**Comment by Chewhern** [comment]
I have a private key with .PEM format and both SSL bundle file & certificate file from CA all are in .PEM format

**Comment by Chewhern** [comment]
I have also created a pfx file from my pem key and ca certificate pem file format

**Comment by davidfowl** [comment]
I'm assuming you're using .NET Core 3.1? If so you'll need to convert the PEM to a PFX using openssl:

```
openssl pkcs12 -export -out certificate.pfx -inkey privateKey.pem -in certificate.pem
```

This should give you a file called certificate.pfx, then you can configure this https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#endpoint-configuration

in `appsettings.json`:

Configure the default HTTPS cert:

```JSON
{
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Path": "certificate.pfx",
        "Password": "password"
      }
    }
  }
}
```

OR you can configure the certificate for a specific endpoint:

```JSON
{
  "Kestrel": {
    "Endpoints": {
      "HttpsEndPoint": {
        "Url": "https://localhost:5001",
        "Certificate": {
          "Path": "certificate.pfx",
          "Password": "password1"
        }
      }
    }
  }
}
```

**Comment by Chewhern** [comment]
Thanks!
