### ISSUE TITLE
Does these file structural change official in core 1.1 compared to core 1.0?

### ISSUE THREAD

**Issue by nithinbandaru1** [dotnet/core#513]
Hi,
I have seen lot of tutorial and articles online regarding .NET CORE 1.0.

Apart for many advantages there were lot of changes in file structure.

But when I created application in .NET CORE 1.1 and ASP.NET MVC 1.1 I realized that there are lot of changes in files structures compared to .NET CORE 1.0 file structure(Few files are missing and few folders are missing)

**Files missing in .NET CORE 1.1 from .NET CORE 1.0:**
1. project.json
2. global.json
3. package.json

_**Question 1: In few articles I read project.json is replaced with new .csproj file. But I think package.json and project.json are combined as .csproj file because I can see npm references in .csproj file. Am I right?**_

_**Question 2: I cant find the reference of sdk components "Microsoft.NETCORE.App" in any file which will be usually defined in global.json file in .NET CORE 1.0. Now in .NET CORE 1.1 I can find global.json file. Then where is the reference is mentioned? I think without mentioning a reference the sdk package will not load.**_ 

**Folders missing in .NET CORE 1.1 from .NET CORE 1.0:**
1. Src folder
2. Solution files folder

_**Question 3: Are these folders officially removed from the projects file structure?**
**Question 4: Are these folders and files optional? Personally I feel very good and less confused with this files not being there.**_

**Comment by Petermarcu** [comment]
@DamianEdwards , can you speak to #1 around package.json for npm?

For the Microsoft.NetCore.App reference, it is implicit in the csproj based on the TargetFramework.

**Comment by iberodev** [comment]
I'm also interested in finding information about the src folder and all the changes in file structure and dependency management from ASP.NET Core 1.0 to ASP.NET Core 1.1

 
I'm afraid this issue has been closed without any clear answer about that. Any link where these changes are summarized would be nice, especially for the ones like me that learned about AspNet Core 1.0 and see now that many things are different

**Comment by StrangeWill** [comment]
Yeah inconsistency in the project structure is really annoying. Considering Core 1.0 is LTS I'll probably be bringing Core 1.1 into line with 1.0's structure and _hoping_ we continue to keep a sensible structure that is less flat and crowded.

Any word from official staff @richlander @Petermarcu @tmat?
