### ISSUE TITLE
Issue with dotnet run

### ISSUE THREAD

**Issue by career-joke** [dotnet/core#5135]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: windows

Hi, I'm new to coding in general so please go easy.

I had no issues following this tutorial up until this "add a component" stage, where I could not run the page (server?) after closing it the first time. The error reads "Couldn't find a project to run. Ensure project exists in C:\Users\gaber, or pass the path to the project using --project."

I am using Visual Studio Code to edit the html and the only change I made anywhere was adding the "Counter /" in angle brackets which apparently I can't use on this forum.

Thanks in advance.
![dotneterror](https://user-images.githubusercontent.com/70484233/91666001-98225600-eac7-11ea-8403-adfe7234a8e9.PNG)

**Comment by svick** [comment]
`C:\Users\gaber` is the directory for your entire user profile. If you followed the tutorial, the app should be in the `BlazorApp` subdirectory. Can execute `cd BlazorApp` and then try `dotnet run` again?

**Comment by career-joke** [comment]
> `C:\Users\gaber` is the directory for your entire user profile. If you followed the tutorial, the app should be in the `BlazorApp` subdirectory. Can execute `cd BlazorApp` to enter that subdirectory and then try `dotnet run` again?

There it is. I didn't know how to stop hosting the site without exiting the command prompt, which I now realize reverted that. Thank you.

**Comment by career-joke** [comment]
Didn't realize I could do that. It is now closed @mairaw
