### ISSUE TITLE
Wrong .comhost.dll generated

### ISSUE THREAD

**Issue by EuroEager2008** [dotnet/core#5137]
.Net 5 COM server is not registered correctly

Made a class library implementing a simple COM server and added <EnableComHosting>true</EnableComHosting> to the .csproj file.
When .net core 3.1 is targeted all is ok after regsvr32.exe <classlib>.comhost.dll i.e Regsvr32 reports ok and registry is updated. Late bound COM object can easily be accessed from e.g. Excel VBA.

However, changing the target to .net 5 (preview 8) makes Regsvr32.exe not reporting neither success or not success and registry is not updated

**Comment by andygonzalez2010** [comment]
can you share your code or the steps to reproduce?

**Comment by EuroEager2008** [comment]
Sure:
See attached solution.
Compile it and register (regsvr32) the server comhost assembly.
Running the attached client project doesn't work for some reason (probably something to with keyword dynamic and DLR),
but if making a VBA call from e.g. Excel as:

Public Sub TestSub()
Dim server As Object
Set server = CreateObject("GitHubIssue5137.Server")
MsgBox server.GetText

is working fine.

Then change the target framework for the server to .NET 5.0, compile and re-register the 5.0 version of the comhost (mind the net5.0 folder this time), note that regsvr32 does not show any info, neither success nor not success.
Now it doesn't work from the VBA script anymore (or actually it works, but not with the .net 5 version because it seems like it is not registered and the old 3.1 version is still the registered one).
[GitHubIssue5137.zip](https://github.com/dotnet/core/files/5156814/GitHubIssue5137.zip)

**Comment by carlossanlop** [comment]
@AaronRobinsonMSFT this does not seem to be directly related to Office Interop but maybe you know who can help with this?

**Comment by AaronRobinsonMSFT** [comment]
>However, changing the target to .net 5 (preview 8) makes Regsvr32.exe not reporting neither success or not success and registry is not updated

@EuroEager2008 This almost sounds like a bitness issue. Thank you for the solution with the reproduction in it. It looks as though the 32-bit version of the runtime was desired - was the 32-bit version of .NET 5.0 also installed? Typically only the 64-bit versions are installed with Visual Studio so we should verify that. Next it would be good to verify the `*.comhost.dll` is also the correct bitness. This can be done from a Visual Studio Developer command prompt using the `dumpbin.exe` command.

`> dumpbin.exe /headers <name>.comhost.dll`

Look for `FILE HEADER VALUES` to see the "machine" type. That should be x86, otherwise it is an x86_64 (64-bit) binary.

There hasn't been any intentional changes in the `comhost` scenarios between .NET 3.1 and .NET 5.0 so hopefully one didn't sneak past our gates. The best way to do this is to make sure `regsvr32.exe` works and then move onto the activation paths.

/cc @elinor-fung @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
@EuroEager2008 @elinor-fung pointed out that an issue did exist in some of the later previews regarding `comhost` scenarios. That fix didn't make it into Preview 8 - https://github.com/dotnet/runtime/pull/40022. The fix in in later RC1 and later.

**Comment by EuroEager2008** [comment]
Now I got 5.0.100-rc.2.20479.15 and still exactly same behavior (nothing is actually registered when regsvr32 of the .Net 5 targeted comhost.dll

**Comment by elinor-fung** [comment]
@EuroEager2008 could you check on the bitness questions that @AaronRobinsonMSFT had?

Thanks for the repro. I pulled it down and was able to build and successfully register the server in it after retargeting to net5.0 (I'm using 5.0.100-rc.2.20479.15), so there must be something different in what I'm doing or my environment.

It would also be helpful to collect some logs from `comhost` when it is being registered. Before running `regsvr32`, set the environment variables:
- `COREHOST_TRACE=1`
- `COREHOST_TRACEFILE=<pathToOutputFile>`
  - The directory containing the `<pathToOutputFile>` has to exist (the file itself does not)

And then run `regsvr32` on your `.comhost.dll` - there should be a text file at `<pathToOutputFile>`.

**Comment by EuroEager2008** [comment]
Bitness was ok.
I think I found out:
Compiled just fine as before, not able to register.
Had a look around in the files and found that preview 8 was mentioned in *.runtimeconfig.json, no idea of how to get rid of it so I deleted the whole bin and object folder, but then I couldn't compile.
Searching around and found this: https://developercommunity2.visualstudio.com/t/shNETsh-shCoresh-Console-App-/1231595?entry=problem
(Is this at all documented in any realease notes?)
and this: https://github.com/dotnet/templating/issues/2615

Then I switched to vs2019 16.8.0 Preview 6.0 and voila everything is fine.
A bit weird experience!

**Comment by elinor-fung** [comment]
Glad things are working after moving to the newer version.

> Is this at all documented in any realease notes?

I know the [.NET 5.0 download page](https://dotnet.microsoft.com/download/dotnet/5.0) lists the version for Visual Studio support for each release.

I'm not sure if there are Visual Studio release notes around this - @marcpopMSFT would you know?

**Comment by marcpopMSFT** [comment]
We updated the .NET SDK installer to mention that it requires 16.8 (see below). I do not believe this was included in any release notes for VS or .NET though I can add it to the .NET 5 release notes if that would help.
![image](https://user-images.githubusercontent.com/12663534/97764941-83fdd380-1acd-11eb-8230-5d30abe736fa.png)

**Comment by carlossanlop** [comment]
It seems this has been answered so I'll close the issue.
@marcpopMSFT if you can mention this in the release notes, that would be great.
