### ISSUE TITLE
It was not possible to find any installed .NET Core SDKs

### ISSUE THREAD

**Issue by naamareuven** [dotnet/core#5138]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: linux
the sdk files are showed in the path computer/snap/dotnet-sdk but the following problem occurs when trying to start a new project. the command 'dotnet' is working fine.

**Comment by mairaw** [comment]
What is the problem exactly? You mentioned in the issue that the dotnet command is working fine.

**Comment by naamareuven** [comment]
After running "dotnet new webApp" got this error: "It was not possible to find any installed .NET Core SDKs"

**Comment by mairaw** [comment]
what does the dotnet command print? And what about dotnet --list-sdks?

This article should be able to help checking if the SDK installed correctly.

**Comment by mairaw** [comment]
Forgot to paste the link to the article: https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-linux
