### ISSUE TITLE
UWP .Net Native compiler crashing

### ISSUE THREAD

**Issue by edward-a** [dotnet/core#5141]
I posted the bug below to dotnetnative@microsoft.com on April 3rd as it was requested. It has never been addressed and the problem is still there.

The ilcRepro.zip file:
https://www.dropbox.com/s/3z3ifh3wys01xkl/ilcRepro.zip?dl=0

The sample app:
https://www.dropbox.com/s/xsk35tyqgdual9n/NetNativeCrash.zip?dl=0

**DISCRIPTION:**
I am unable to compile a newly created blank UWP application in Release configuration when the following two lines added to the project:

public struct TestStruct { }
public delegate ref TestStruct TestDelegate();

The below is from the Output window:

1>------ Build started: Project: NetNativeCrash, Configuration: Release x64 ------
1> NetNativeCrash -> C:\Projects\NetNativeCrash\bin\x64\Release\NetNativeCrash.exe
1> Processing application code
1> Computing application closure and generating interop code
1> Loading 44 modules…
1> Generating code…
1> Interop code generated.
1> Compiling interop code
1> Generating System.Reflection.DispatchProxy proxy code.
1> Cleaning up unreferenced code
1> Generating native code

1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: ‘C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\x64\ilc\Tools\nutc_driver.exe @“C:\Projects\NetNativeCrash\obj\x64\Release\ilc\intermediate\MDIL\NetNativeCrash.rsp”’ returned exit code 2

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by carlossanlop** [comment]
UWP issues are tracked as Azure DevOps issue. If you are running into .NET native issues, please see https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options.
