### ISSUE TITLE
error converting YAML to JSON: yaml: line 14: did not find expected key

### ISSUE THREAD

**Issue by davideusai** [dotnet/core#5143]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Hello,
I'm following this tutorial and I encountered a problem just on last step.
When I try to execute kubectl apply -f deploy-myMicroservice.yaml command PS termina return me the error
error converting YAML to JSON: yaml: line 14: did not find expected key

What kind of key is expectending?

Thanks a lot if you could help me.
Davide

**Comment by davideusai** [comment]
Additional info. I replaced [YOUR DOCKER ID] with my docker id so I give an other error:
error: unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

**Comment by mairaw** [comment]
We did update the yaml syntax yesterday to no longer reference the apps/v1beta. Can you refresh your page to make sure the apiVersion uses apps/v1?

**Comment by davideusai** [comment]
> We did update the yaml syntax yesterday to no longer reference the apps/v1beta. Can you refresh your page to make sure the apiVersion uses apps/v1?

Thanks a lot, it is working now. You saved me, I love you.

**Comment by mairaw** [comment]
I'm glad it's working now! ❤️
Let me know if you run into any other issues.
