### ISSUE TITLE
.NET Core standalone console app won't run via Task Scheduler

### ISSUE THREAD

**Issue by jucoxvt** [dotnet/core#515]
I'm not sure if this is correct place to ask, so please forgive me if it's not.  

I have a .NET Core 1.0.1 console application that I have published as a standalone app.  Once I build, publish, and copy the application files to the server I can double click on the executable and it will run without issues.  However, when I try to create a task in the Task Scheduler pointing to that same executable, it will not run.  The Task Scheduler reports that the task completed successfully in the history, yet there is nothing to indicate the application actually ran.  It didn't perform the tasks it was supposed to and there were no log files created.  I also checked the Windows Event Viewer to see if any application errors were recorded there, but again, nothing.  

I have tried this from both a Windows Server 2008 R2 machine (targeting the win7-x64 runtime in project.json) and a Windows Server 2012 R2 machine (targeting win81-x64 runtime in project.json) with the same results.  

Any thoughts?  Thanks!

**Comment by alexwiese** [comment]
Try setting up the task with the "Start in" option set to the folder your executable lives in. Are you running the scheduled task as local system or a user account?

**Comment by jucoxvt** [comment]
It was the missing "start in" option.  Can't believe it was that simple and that I overlooked it! None of our applications prior to .NET Core needed that option set, so it never even occurred to me to even try that.  Thanks!

**Comment by alexwiese** [comment]
That's because .NET core is using the current working directory to discover the standalone/bundled runtime etc. .NET desktop apps used the installed framework so weren't dependent on the current working directory to be where the Exe was deployed.

**Comment by Petermarcu** [comment]
@mairaw @blackdwarf , this seems like something work a quick "how to" doc on given its different from .NET Framework.

**Comment by mairaw** [comment]
It seems that a doc could be helpful indeed.

**Comment by mellinoe** [comment]
> That's because .NET core is using the current working directory to discover the standalone/bundled runtime etc. .NET desktop apps used the installed framework so weren't dependent on the current working directory to be where the Exe was deployed.

I don't think that's accurate. All of my standalone applications can be run from any working directory. Are you sure you don't have other assumptions in your code regarding the working directory?
