### ISSUE TITLE
Cross-framework guidance on .Net 5 porting

### ISSUE THREAD

**Issue by AnkHansen** [dotnet/core#5150]
Hi,

I've been trying to port/upgrade an existing software solution to .Net 5 Preview 8 (.Net 5.0.100-preview.8.20417.9)

It is a legacy solution, consisting of several generations of .Net technologies, which I am hoping to move in the direction of .Net 5. 

It's a quite large solution with 60+ projects using various .Net technologies. I will try to describe how it looks (simplified) now, and where I want to move to. 

I am hoping that some one on the team can reach out, and tell me whether or not I am trying to do the impossible - or there is a way for our solution to move forward. 

The solution consists of several projects, here grouped into categories. 

**Baseclasses/Common Business logic (6-7 projects, currently .Net 4.5)**
These are trivial to convert to .Net 5. 
Some of them make use of Windows Forms components, so have chosen net5.0-windows as TFM.
I have added the following to the .csproj for those requiring WinForms or WPF.
`<UseWindowsForms>true</UseWindowsForm>
<UseWpf>true<UseWpf>` 

**.Net Core 2.1 API** 
A few years ago we developed an API on top of the common business logic. 
This also has a almost trivial path to .Net 5. 
So have converted this, and this works almost as expected. 
A few custom middleware classes needs adjustments - but certainly doable.
This is the key project needing .Net 5, as we need to upgrade the framework for this to move on. 
.Net Core 3.1 was skipped since it's not compatible with .Net 4.5 (or 4.6/4.7) and our baseclasses will still need to support this. 

**Legacy Web projects**
We have some legacy webprojects, still active though. 
They are based on Asp.Net 2, Asp.Net WebApi, WCF, etc. 
Common for these are they use System.Web, the use WCF and they are stuck there - or doomed to be rewritten, as I understand it.
These are still used by customers, and I will estimate several months of work to convert to newer technology.
So these can't be moved to .Net 5. 

**Windows application**
We have a normal WinForms based windows application on top as well. 
Currently .Net 4.5, will assume it can be moved to .Net 5 even though using Windows Forms. 
It is currently referencing some of the Web projects, as it has some WCF generated client classes. 
So until the references to web projects is refactored, this will stay on e.g .Net 4.7.2

**My proposed solution**

- The idea I am going for is to let the baseclasses build for both net472 and net5.0-windows. So these projects has multiple TFM's. 
`<TargetFrameworks>net5.0-windows;net472</TargetFrameworks>`

- The api should build for net5.0-windows. (Down the road we can clean up and remove the -windows binding by removing Windows Forms from the baseclasses.

- The legacy webprojects should build for net472, and as such not be running as .Net 5. 

- The Windows application should in first step be net472, but over time moved to .Net 5, as we refactor the requirements and project references to legacy webprojects. 

**Status**
The baseclasses and the API works. So I have my API running .Net 5. 

Where I get stuck is with the webprojects. 

As an example I have a project IosDeviceIntegration.csproj
On my .Net 5 machine, I can build it using msbuild. 
`&"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe" .\IosDeviceIntegration.csproj`
Using dotnet cli it fails with the below
`dotnet build IosDeviceIntegration.csproj`

> C:\Users\Anders\sertica\IosDeviceIntegration\IosDeviceIntegration.csproj(206,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.

I assume this is expected, as the csproj file is not converted using try-convert. So this is still good old csproj with toolsversion 14 and a TargetFrameworkVersion v4.7.2. 

When I then try to build the WinForms project with MsBuild (targeting .Net 4.7.2), i run into problems. 
This gives me this error

> "C:\WinForms\logihold.csproj" (default target) (1) ->
(ResolveNuGetPackageAssets target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\NuGet\16.0\Microsoft.NuGet.targets(186,5): error : Your project file doesn't list 'win' as a "RuntimeIdentifier". You should add 'win' to the "RuntimeIdentifiers" property in your project file and then re-run NuGet restore. [C:\Winforms\logihold.csproj]

I have added the RuntimeIdentifier to the logihold.csproj - but somehow it seems to not pick it up. 

So the big question is:
Is it at all possible to keep .Net 4.7.2 old style projects referencing .Net 5 built assemblies, when these .Net 5 assemblies are built with TFM net472? 

If doable what steps do I need to take to make it work? 
- How do I overcome the "win missing runtime identifier" msbuild error - where does this come from? 
- Do I need split up my solution into several solutions for baseclasses, api, legacy web, and winforms? Or can they co-exist in same solution?

I hope someone can give me some hints here. 

I hope I can follow my idea, as having to maintain individual solutions and projects for "old" .Net and new .Net5 seems an hard and troubled way to go. Then developers will need to add new files two places for everything to work - which is doomed to fail. 

Let me know if any specific details are needed to answer this question. 

Best regards 
/Anders

**Comment by AnkHansen** [comment]
Hi 

Just a short feedback. 

It seems the "win" RuntimeIdentifier is caused by "corrupt" data in the obj folder. 
Reading the net, this could be caused by nuget having restored with the new project format in same folder. Which is not unreasonable to think I have tried - as I have been trying out a lot of things to experiment different paths. 

Deleting the obj folder seems to have put me in the right direction again. 

I am leaving the office for today - but will reply with an answer tomorrow, if I am stuck a new place.  Or if everything just works - then I can leave a small note on how I made it work.

**Comment by AnkHansen** [comment]
Hi again. 

I think it works now. 

I have some challenges left, on getting the output patchs matching for the old and new assemblies. 

My approach has been
**BaseClasses*
- Convert the csproj files with _try-convert -p projectfile.csproj_
- Adjust TargetFrameworks to net5.0-windows and net472
`<TargetFrameworks>net5.0-windows;net472</TargetFrameworks>`
- For those projects using WindowsForms or WPF add the corresponding tags
`<UseWindowsForms>true</UseWindowsForms>`
`<UseWPF>true</UseWPF>`
- Add conditional reference to Microsft.CSharp if net472 targetframework.
`<ItemGroup Condition=" '$(TargetFramework)' == 'net472'">`
`  <Reference Include="Microsoft.CSharp"></Reference>`
`</ItemGroup>`

**.Net Core API**
Follow the conversion guidelines moving from .Net Core 2.1->3.1->5.0 
Starting point [here](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-3.1&tabs=visual-studio)

**System.Web dependent projects and above**
I have not converted these, and as such they are just kept as old-style csproj files, compiling to .Net 4.7.2. 
So only change for now is that their target framework is moved from 4.5 to 4.7.2. 

Last question - if anyone gets here.
The "old" System.Web projects targeting .Net 4.7.2 and using System.Web. 

Is it the right approach to leave them alone, or should I convert them using try-convert, and moving to the new build chain, but only targeting net472?

**Comment by mairaw** [comment]
@cartermp @csharpfritz can you help here?

**Comment by carlossanlop** [comment]
@richlander @terrajobst do we have any guidance on how to perform migration?

**Comment by AnkHansen** [comment]
Closing this. 
After some time away from this I have now a working setup. 

Ended up with targeting .Net4.8 and .Net 5.0 

1. Assemblies depending on System.Web or other non .Net5.0 ported bits are kepts as .Net 4.8 assemblies, on old-style csproj files. So no conversions here. In this block is our existing Windows application and legacy webservcices. They also require some win only parts. The only target net48 in TargetFramework
2. The .Net Core API, and test projects are converted to .Net 5.0
3. Shared assemblies between legacy webservices, windows application and API, from the bottom up, is compiled with two TargetFrameworks both net5.0-windows and net48

References to external third party assemblies are for most parts changed to nuget packagereferences to avoid manually handling .Net4.8 /5.0 switching. 

Had to move some bits and parts around, some blocks are left out in .Net 5.0 with #if net48 preprocessor directives etc. 

Quite some work in figuring out when msbuild, mstest and dotnet CLI works best, and how to restore nuget references etc. 
.Net4.8 solutions is built with msbuild and tested using mstest. 
API solutions is built with msbuild, but tests run with dotnet test.
Visual Studio 2019 does it all - but on buildservers some trial and error should be expected. 

But... all in all, it seems like the 10-15 year old codebase can coexist and be used both in a .Net 4.8 and .Net 5.0 runtime.
