### ISSUE TITLE
Process.StartInfo Arguments not allowing the documented length.

### ISSUE THREAD

**Issue by nvrnight** [dotnet/core#5152]
# Issue Title

Process.StartInfo Arguments not allowing the documented length.

# General

This page(https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=netcore-3.1) says that the Arguments property allows for a length less than 32,699, however whenever I use an Arguments string with 1,941 characters long I get a Win32Exception "The parameter is incorrect.". It works fine with an Arguments string of 1,940 characters long.

Using Windows 10, .NET Core 3.1, VS 2019.

```
var exePath = "<path/to/my.exe>";
var arguments = "<some really long arguments string that is at least 1,941 characters long>";

var process = new Process
{
    StartInfo = 
    {
         FileName = exePath,
         Arguments = arguments,
         UseShellExecute = false,
         RedirectStandardOutput = true,
         RedirectStandardError = true,
         Username = "<username>",
         PasswordInClearText = "<password>",
         Domain = "<Domain>"
    }
};
//Output and Error handlers removed for brevity
process.Start();
process.BeginOutputReadLine();
process.WaitForExit(100000);
process.Close();
```

**Comment by mairaw** [comment]
@jeffhandley can you help route this? Not sure if this is a documentation issue or runtime issue

**Comment by jeffhandley** [comment]
@adamsitnik and @eiriktsarpalis - can you take a look at this please?

**Comment by adamsitnik** [comment]
Hi @nvrnight 

I've written the following app to see if the limit is lower than what is mentioned in the docs:

```cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Reflection;

namespace ArgsLength
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args?.Length > 0)
            {
                Console.WriteLine(args[0]);
            }
            else
            {
                string dllPath = Assembly.GetExecutingAssembly().Location;

                foreach (int length in Enumerable.Range(1, 32).Select(x => x * 1_000))
                {
                    using (var process = Process.Start(new ProcessStartInfo("dotnet", $"\"{dllPath}\" {new string('a', length)}")
                    {
                        RedirectStandardOutput = true,
                    }))
                    {
                        string output = process.StandardOutput.ReadToEnd().Trim();

                        if (output.Length != length)
                        {
                            Console.WriteLine($"Length mismatch! Expected {length}, got {output.Length}");
                            Console.WriteLine(FileVersionInfo.GetVersionInfo(typeof(object).Assembly.Location));
                            Console.WriteLine(Environment.OSVersion);
                            return;
                        }
                    }
                }

                Console.WriteLine("Everything works as expected.");
            }
        }
    }
}
```

It works fine for .NET Core 2.1, 3.1, and 5.0. Could you please run it and share the output here?

**Comment by adamsitnik** [comment]
> The parameter is incorrect

After giving it a second thought I believe that the problem might not be related to string length, but content. Are you sure that the value provided to `Arguments` property is properly escaped (things like spaces in paths etc)?

If my small repro app does not fail, could you please try using [ArgumentsList](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=netcore-3.1) property instead of `Arguments` property? It takes care of everything related to argument escaping.

```cs
new ProcessStartInfo
{
    ArgumentList = {
        "arg1",
        "arg2",
    }
}
```

**Comment by adamsitnik** [comment]
I've sent a PR to improve the docs: https://github.com/dotnet/dotnet-api-docs/pull/4817

**Comment by eiriktsarpalis** [comment]
I think we can close this issue then?

**Comment by adamsitnik** [comment]
> I think we can close this issue then?

I would wait a day or two to hear back from @nvrnight

**Comment by adamsitnik** [comment]
I am closing due to lack of response from @nvrnight

@nvrnight if you can repro the problem using the app that I've provided or switching to `ArgumentList` does not help, please feel free to reopen the issue
