### ISSUE TITLE
No Dotnet SDK's showing up, even though installed.

### ISSUE THREAD

**Issue by Slurp1e** [dotnet/core#5154]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Windows Home x64 

I am getting an issue with installing the .NET SDK, at first when I went into visual studio 2019 it said that I was missing the dotnet runtime sdk so I installed it like it asked and restarted my computer. I then went on to visual studio 2019 again, and the same issue arose, I went into my command prompt and typed `dotnet --list-sdks` and it displayed no sdks. I have all of the runtimes installed, but it says `No SDKs were found.` ![image](https://user-images.githubusercontent.com/54456440/92277203-5f7ce500-eeea-11ea-99be-958746163fe8.png) . I tried re-installing the sdks but the same problem stuck. I even went as far as to re-install IIS. I can't do anything without this being fixed please help soon!

**Comment by mairaw** [comment]
If you're trying to use Visual Studio to edit the files, make sure that you have the .NET Core workload installed.

To modify/view the current workloads you have installed, check https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019#modify-workloads.

Let us know if that helps!

**Comment by svick** [comment]
Just to make sure, are you certain you installed the .NET Core SDK and not the .Net Core Runtime?

**Comment by ZephyrDogma** [comment]
Mairaw i did what u said and didnt work

**Comment by ZephyrDogma** [comment]
and yes i am using Visual Studio to edit the files

**Comment by mairaw** [comment]
@ZephyrDogma can you paste the output of `where dotnet`? It would be better if you create a new issue since we don't typically keep an eye on closed ones.

**Comment by ZephyrDogma** [comment]
here is the new issue
https://github.com/dotnet/core/issues/6019

**Comment by ZephyrDogma** [comment]
@mairaw the new issue is #6019 can u help?
