### ISSUE TITLE
.Net 5 preview no longer builds

### ISSUE THREAD

**Issue by trampster** [dotnet/core#5155]
I'm now getting the following error on a Source Generator project that was previously working, Here is a link to the project that will no longer build https://github.com/trampster/JsonSGen

Here is the the error I get when trying to build

> /snap/dotnet-sdk/97/sdk/5.0.100-preview.8.20417.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file '/home/daniel/Work/JsonSG/UnitTests/obj/project.assets.json' doesn't have a target for 'net5.0'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. [/home/daniel/Work/JsonSG/UnitTests/UnitTests.csproj]

The target project has a target for net5.0:

`<TargetFramework>net5.0</TargetFramework>`

And I have tried running restore but it doesn't help

I'm using .NET 5 on linux (ubuntu 18.04) using the snap package, I have version 5.0.100-preview.8.20417.9, I'm not sure what made it stop working.

**Comment by trampster** [comment]
I cleared the obj/bin folders and it started working again.

Looking at my command line history it looks like I ran dotnet test instead of dotnet-sdk.dotnet test, once and then after that running dotnet-sdk.dotnet test didn't work.

I would not expect running the old dotnet to break things in an unrecoverable way like this.

**Comment by carlossanlop** [comment]
It looks like you had restore issues and deleting the folder helped. Closing since it's resolved.
