### ISSUE TITLE
I got an error "error during connect" when building image

### ISSUE THREAD

**Issue by lilhamad** [dotnet/core#5157]
I got the following error 

error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=3xrta9sf7qxuno655f0bx53q4&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by carlossanlop** [comment]
@lilhamad  Is this related to the Docker microservice tutorials?
