### ISSUE TITLE
Could not create a .NET Console App

### ISSUE THREAD

**Issue by shivanshsen7** [dotnet/core#5163]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows
# With IDE
![image](https://user-images.githubusercontent.com/42974761/92362461-a7c81d00-f10d-11ea-8b5a-4b95a9244d8a.png)
# With Console
![image](https://user-images.githubusercontent.com/42974761/92362524-be6e7400-f10d-11ea-8cb7-2da8e421ba7f.png)
# From Complete Package:
![image](https://user-images.githubusercontent.com/42974761/92362737-11482b80-f10e-11ea-9c65-4daac1a69d90.png)
![image](https://user-images.githubusercontent.com/42974761/92362758-19a06680-f10e-11ea-8e44-7374d0ca566f.png)

# Installed necessary file
![image](https://user-images.githubusercontent.com/42974761/92362689-fbd30180-f10d-11ea-8c08-c0c714e438dc.png)

**Comment by ericstj** [comment]
@marcpopMSFT this looks like a problem with the template factoring in Visual Studio, can you help route?

**Comment by shivanshsen7** [comment]
Repaired it via visual studio installer and it worked

Shivansh Sen
India

**Comment by marcpopMSFT** [comment]
@shivanshsen7 thanks for confirming.  Tracking down install issues can be difficult.  @joeloff for visibility but I would close this unless we get more comments from other users indicating a more widespread problem.

**Comment by mairaw** [comment]
Closing for now, but we can reopen if we get more comments.
