### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by NourMH** [dotnet/core#5167]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ericstj** [comment]
That would occur if you didn't successfully install the DotNET SDK or didn't launch a new command-prompt after installing.

Can you confirm that you installed the SDK successfully?  You can check for `C:\Program Files\dotnet\dotnet.exe` to confirm.

If not present, ensure you've run https://download.visualstudio.microsoft.com/download/pr/9706378b-f244-48a6-8cec-68a19a8b1678/1f90fd18eb892cbb0bf75d9cff377ccb/dotnet-sdk-3.1.402-win-x64.exe

Once you confirm that ``C:\Program Files\dotnet\dotnet.exe` is present, open a new command prompt and try typing `dotnet`.
