### ISSUE TITLE
dotnet命令无法使用

### ISSUE THREAD

**Issue by 3222368840** [dotnet/core#5168]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: linux

bash: /home/xdy/dotnet/dotnet：无法执行二进制文件: [可执行文件格式错误

**Comment by carlossanlop** [comment]
Translation:
> 命令无法使用 -> Command cannot be used
> 无法执行二进制文件: [可执行文件格式错误 Unable to execute binary file: [executable file format error

@3222368840 On which step of the tutorial did you encounter this problem? Did you download the correct dotnet SDK version for your computer architecture?
