### ISSUE TITLE
.NET Core September 2020 Update - 2.1.22 and 3.1.8

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5170]
[3.1.8 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.8/3.1.8.md)
[3.1.8 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.22 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.22/2.1.22.md)
[2.1.22 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-september-2020/)

Please report any issues you find with 2.1.22 or 3.1.8, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Status of availability of SDK on Linux feeds: 

| Distro | 3.1.8| 2.1.22 
|--|--|--|
| Ubuntu 16.04   |  ✅ | ✅ |
| Ubuntu 18.04 | ✅ | ✅|
| Ubuntu 20.04 |  ✅ |✅  |
| Centos 7    | ✅| ✅ |
| Debian 9    |  ✅| ✅ |
| Debian 10    | ✅ | ✅|
| Fedora 30  | ✅ |✅ |
| Fedora 31  | ✅ | ✅|
| Fedora 32   | ✅ | ✅ |
| OpenSUSE 15  | ✅ |✅  |
| SLES 12     | ✅  |✅ |
| SLES15     | ✅  |✅ |
-----
### Known Issues
If there are any issues with the September 2020 release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by fwd079** [comment]
First link in [release notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.8/3.1.8.md) (blog roundup) is a circular reference.

**Comment by jehof** [comment]
I´m missing the docker image **3.1.8-alpine**. Was there a change? We have always used the **xxx-alpine**-Image

**Comment by estensen** [comment]
Are there more detailed release notes somewhere? Specifically, I'm upgrading `Microsoft.Extensions.Http.Polly` from 3.1.2 to 3.1.8, but I can't find any release notes.
Nuget.org links to this release

**Comment by fwd079** [comment]
@rbhanda are you listening to people here?

**Comment by rbhanda** [comment]
@fwd079 circular reference is by design. This is done so that people can access release notes or blogs from either place

**Comment by rbhanda** [comment]
@estensen https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly/3.1.8 will this help?

**Comment by MichaelSimons** [comment]
> I´m missing the docker image aspnet:3.1.8-alpine. Was there a change? We have always used the aspnet:xxx-alpine-Image.

> What image should be used instead?

@jehof - the recommendation is to use the `3.1.8-alpine3.12` tag.  See https://github.com/dotnet/dotnet-docker/issues/2188 for more details.

**Comment by estensen** [comment]
@rbhanda no? There's no changelog there

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/5347
