### ISSUE TITLE
The status of ARM32 support on Windows

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/core#5176]
The 3.1 doc mentions that Windows ARM32 is supported: 

https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md

The 5.0 doc mentions that it's no longer supported:

https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#support-changes-from-net-core-31

But we are still producing an installer for it: 

https://github.com/dotnet/installer

![obraz](https://user-images.githubusercontent.com/6011991/92587339-c9eda680-f297-11ea-9be2-b2fb12a3a46f.png)

@richlander why are we producing an installer for unsupported configuration?

@danmosemsft what is somebody uses it and reports a bug in the product? Are we going to fix it?

**Comment by carlossanlop** [comment]
@echesakovMSFT @kunalspathak @BruceForstall

**Comment by BruceForstall** [comment]
It's still useful to build it for our own internal testing/debugging purposes, as a proxy for Linux/arm32 testing (it's much easier for our dev workflow in some cases). I'm not sure we need the full installer for that, but we do need a dotnet/runtime build. So it might not be worth the effort to actively remove functionality that already basically works.

**Comment by GrabYourPitchforks** [comment]
Just to confirm - it sounds like we're producing a Win-arm32 build for testing purposes, but we __do not__ support production use of that runtime. Is my understanding correct?

**Comment by BruceForstall** [comment]
@GrabYourPitchforks I believe that statement is correct. I'll leave it to @richlander to confirm.

**Comment by GrabYourPitchforks** [comment]
Just to clarify, there are two separate questions being considered in this thread.

* __If my OS is Windows 10 arm32, can I deploy a .NET 5.0 app to it?__ Answer: no, per [this page](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#support-changes-from-net-core-31).

* __If my OS is Windows 10 arm64, can I deploy a .NET 5.0 arm32-based app to it, relying on the OS's arm32-on-arm64 layer to handle things correctly?__ This answer is the one that's not clear.

**Comment by BruceForstall** [comment]
The answer is also no: Windows arm32-on-arm64 requires a Windows arm32 runtime, and that is not supported.

**Comment by GrabYourPitchforks** [comment]
Jan's got your back. :)
https://github.com/dotnet/runtime/issues/42231

**Comment by carlossanlop** [comment]
I believe this has been answered.
