### ISSUE TITLE
Linux Mint 20 is not supported by the .NET 5 Preview installer

### ISSUE THREAD

**Issue by Tridy** [dotnet/core#5177]
# Issue Title

Not possible to install .NET 5 Preview 8 on Linux Mint 20

# General

using the instructions on the page:
https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.8-install-instructions.md

and based on the information from the Supported OS:
https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md

Linux Mint is supported from the version 18+, so it should be possible to install on Linux Mint 20
Linux Mint | 18+ | x64 | Linux Mint

```
me@mypc:~/dotnet_install$ sudo bash install-dotnet-preview.sh
Linux Mint 20 is not supported by the .NET 5 Preview installer.
```

**Comment by dagood** [comment]
@leecow @rbhanda Can we add Mint detection to the script? I'd expect the Ubuntu deb packages to work on Mint.

/cc @dleeapho @MikeCodesDotNET

**Comment by MaximS** [comment]
Easy manual fix: Open the script in text editor and replace line `*"Ubuntu 20.04"* | *"Focal"*` with `*"Ubuntu 20.04"* | *"Focal"* |  *"Mint 20"*)`

**Comment by Tridy** [comment]
> Easy manual fix: Open the script in text editor and replace line `*"Ubuntu 20.04"* | *"Focal"*` with `*"Ubuntu 20.04"* | *"Focal"* |  *"Mint 20"*)`

Yep, that'll do it.

It could be nice to have a command line option like "-f" for force or skip os check or similar. Or have a message that says, your os is such and such is not supported but do you want to install anyways?

**Comment by carlossanlop** [comment]
@leecow do we have an official fix for this?

**Comment by rbhanda** [comment]
Mint 20 has been added as a supported OS for .NET 5 Preview install script.
