### ISSUE TITLE
System.Linq.Enumerable partial fake type???

### ISSUE THREAD

**Issue by KoromaruKoruko** [dotnet/core#5178]
# General

I'm writing a TypeResolver for use in a AOT-security plugin system that would allow a .net DLL to be scanned for all references and call-tree's crawled. while making this i have came across an interesting thing that i would assume is a bug. The `System.Linq.Enumerable` type is a strange special type.
```cs
Type Enumerable_type = typeof(System.Linq.Enumerable);
Assert(Enumerable_type, null); // =false
Type Enumerable_runtimeType = Type.GetType(Enumerable_type.FullName);
Assert(Enumerable_runtimeType, null);// =true
```

![image](https://user-images.githubusercontent.com/17232928/92597584-e7c30780-f2a7-11ea-995e-04d30e8a6915.png)

This is causing a slight issue because i allow loading of already known types so, say the dll references System.Int you can get the Reflection Type Definition of it (this is to allow better modifiability and make it easier to detect unknown external types).

If this is intended, why?

Version:  netcore3.1-8 (2020-09-08)
Type: Library&ConsoleApplication

Edit: Confirmed issue is still present in latest Release of 3.1(3.1.8, Released: 2020-09-08)

**Comment by KoromaruKoruko** [comment]
nvm, i had miss took the Linq Library to be in mscorelib.dll

**Comment by teo-tsirpanis** [comment]
`Type.GetType` accepts an _assembly-qualified_ name, containing both the type's name and the assembly it resides.

You should write `Type.GetType(Enumerable_type.AssemblyWualifiedName)` instead, in the third line.
