### ISSUE TITLE
CentOS71 docker to use LLVM3.9

### ISSUE THREAD

**Issue by am11** [dotnet/core#519]
Thought I should share that I am able to build CoreCLR (and CoreRT native code) with the following dockerfile:

```dockerfile
FROM centos:7
# it should pick the latest in 7 (atm 7.3.1611)
RUN cat /etc/*-release

RUN yum -y -q  install epel-release
RUN yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/alonid/llvm-3.9.1/repo/epel-7/alonid-llvm-3.9.1-epel-7.repo 
RUN yum -y -q update
RUN yum -y -q install \
      git cmake make icu libicu-devel lttng-ust lttng-ust-devel libuuid-devel \
      libunwind libunwind-devel llvm-3.9.1 clang-3.9.1 lldb-3.9.1 \
      lldb-3.9.1-devel --enablerepo=alonid-llvm-3.9.1

ENV PATH /opt/llvm-3.9.1/include:/opt/llvm-3.9.1/lib64:/opt/llvm-3.9.1/bin:$PATH

RUN git clone https://github.com/dotnet/coreclr -b master --single-branch \
    && cd coreclr \
    && ./build.sh
```

These are the minimum set of dependencies required to build the said repos.

However, the one [in the repo](https://github.com/dotnet/core/blob/d5ae4db/tools/dotnet-bootstrap/base/lab/containers/centos71/Dockerfile) seems to be using LLVM, Clang and LLDB version 3.6 and bit of extra dependencies.

**Comment by bryanar** [comment]
@am11 @richlander Thanks! I'll see if this works for me, and then update the script. Little optimizations like this are nice.

**Comment by leecow** [comment]
@bryanar - have you had a chance to update the script so we can close this issue?
