### ISSUE TITLE
File.Exists returns true, but File.Encrypt throws IOException: Element not found

### ISSUE THREAD

**Issue by Feanorek** [dotnet/core#5192]
# File.Exists returns true, but File.Encrypt throws IOException: Element not found

Due to increased security criteria in my application I need to encrypt multiple files on startup. However, It seems to be impossible, and exception message does not indicate actual reason - on the contrary, it seems to be plain wrong.

# General
In `Program.cs` during application startup following method is called:

    private static void EncryptAppSettings()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "appsettings.json");
        if (File.Exists(path))
        {
            File.Encrypt(path); // Unhandled exception. System.IO.IOException: Element not found. : 'P:\Balsam\appsettings.json'
        }
    }

This method works fine on dev machine (Windows 10 Enterprise Microsoft Visual Studio Professional 2019 Version 16.6.3). However, after deploying on Windows Server 2016 Datacenter application crashes on startup. After retrieving crash info from Event Viewer, following exception was found:

    Application: Balsam.Front.exe
    CoreCLR Version: 4.700.20.41105
    .NET Core Version: 3.1.8
    Description: The process was terminated due to an unhandled exception.
    Exception Info: System.IO.IOException: Element not found. : 'P:\Balsam\appsettings.json'
       at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
       at System.IO.FileSystem.Encrypt(String path)
       at System.IO.File.Encrypt(String path)
       at Balsam.Front.Program.EncryptAppSettings() in P:\JENKINS\x\Balsam.Front\Program.cs:line 40
       at Balsam.Front.Program.Main(String[] args) in P:\JENKINS\x\Balsam.Front\Program.cs:line 16

The file exists on specified path, and user account is in IIS_IUSRS group. IIS_IUSRS has every permission, Full Control included, on whole application folder.

I think that either this should work, or exception message should include more data about what is exact reason.

**Comment by NetMage** [comment]
The error message is the Win32 error message from the Window API `EncryptFileW` function. It basically does the same as setting the encrypt attribute on the file. What happens if you check that manually in File Explorer?

**Comment by Feanorek** [comment]
> 
> 
> The error message is the Win32 error message from the Window API `EncryptFileW` function. It basically does the same as setting the encrypt attribute on the file. What happens if you check that manually in File Explorer?

It fails with exactly same error message. Well, it seems it is not problem with .NET Core itself, but with OS Configuration. I will check it with Sysadmins. Thank you for help
