### ISSUE TITLE
Unable to identify objects in UIAutomation

### ISSUE THREAD

**Issue by preetipadalia** [dotnet/core#5194]
# Issue Title

Unable to identify objects in UIAutomation

# General

.net core version: 3.1.302

We have migrated from net472 to .net core 3.1 recently. most of the things are working with UIAutomation but some objects which have spaces in name in actual are not identifiable.

Also, the scroll bar page down and page up button which are identifiable using Inspect and Microsoft accessibility tool and was working with net472 are not identifiable now in .net core.

Please help, how can I resolve this issue?

**Comment by carlossanlop** [comment]
@RussKie is this something WinForms owns?

**Comment by RussKie** [comment]
We need more details to triage. UIA belongs to Windows, Windows Forms and WPF have own implementations on top of it.

**Comment by preetipadalia** [comment]
@RussKie Please let me know what details you would require to investigate it.

**Comment by RussKie** [comment]
To start with - what tech stack you are using - MFC, Windows Forms, WPF, something else? What runtime? What OS? Screenshots/error logs/memory dumps... anything that can be useful.

**Comment by preetipadalia** [comment]
We are automating windows Desktop applications using UIAutomation library. We were using net472 previously and now switched to .net core 3.1.

After the migration, most of the application objects were identifiable using UIA but few objects were not identifiable.
![Object issue](https://user-images.githubusercontent.com/36397242/93578108-89d6a400-f9ba-11ea-84a1-1b36b0a1403b.png)

In the above screenshot, there are spaces in the starting and end of the name property. But if we give the name the same as above i.e. " Financial " it is not identifying. The object is getting identified with the name property "Financial ". (first space trimmed but last space is there)

Along with the above issue the scroll bar page down, page up buttons are also unidentifiable using .netcore3.1. The same was working with net472.
![ScrollBarIssue](https://user-images.githubusercontent.com/36397242/93579763-82b09580-f9bc-11ea-9955-9aac413d4edd.png)

OS: Windows 10
Editor: Visual studio code
Language: c#
SDK:  Microsoft.NET.Sdk.WindowsDesktop
Target framework: netcoreapp3.1
ProjectType: Nunit enabled library
.net core version: 3.1.302

**Comment by RussKie** [comment]
What tech stack you are using - Windows Forms or WPF?
How do you set UIA names, e.g. " Financial "?
Which UIAutomation library do you use?

**Comment by preetipadalia** [comment]
@RussKie The application was developed using Lansa technology. 
We are not developing that application but automating it.

**csproj file entries:**
```
<?xml version="1.0" encoding="utf-8"?> 
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop"> 
  <PropertyGroup> 
    <OutputType>Library</OutputType> 
    <TargetFrameworks>netcoreapp3.1</TargetFrameworks> 
    <UseWPF>true</UseWPF> 
    <UseWindowsForms>true</UseWindowsForms>
```

**UIAutomation Code:**
```
using System.Windows.Automation;
PropertyCondition condition=new PropertyCondition(AutomationElement.NameProperty, “nameOfObject”)
AutomationElementCollection collection=windowElement.FindAll(TreeScope.Descendants, condition); 
```

**Comment by RussKie** [comment]
@preetipadalia you're using the WPF stack - [System.Windows.Automation](https://docs.microsoft.com/dotnet/api/system.windows.automation). In Windows Forms we provide accessible objects.

@carlossanlop I think this would belong to WPF repo.
Tagging @fabiant3 @ryalanms.

@preetipadalia it would be great to have a repro project that could help to investigate your issue.

**Comment by preetipadalia** [comment]
@RussKie I have created a sample Winform application and added vScroolBar control. With .net core "Page down" object is unidentifiable, but with net472 it's getting identified.

Thanks
Preeti

**Comment by RussKie** [comment]
Please raise an issue in dotnet/winforms repo with a sample.

**Comment by preetipadalia** [comment]
Closing as it raised in wpf repo.
