### ISSUE TITLE
Add an announcements repo or tracking process for dotnet

### ISSUE THREAD

**Issue by leecow** [dotnet/core#520]
copied from https://github.com/dotnet/corefx/issues/8948

**Comment by richlander** [comment]
I think that this could be useful. We made a bunch of changes to our Docker images, for example, and didn't have a good way of doing it. I used this fairly bad technique at [Docker Hub](https://hub.docker.com/r/microsoft/dotnet/).

![image](https://cloud.githubusercontent.com/assets/2608468/23784890/9720b978-0519-11e7-9ea6-2c5c96bcbd41.png)

**Comment by terrajobst** [comment]
Any reason this wouldn't be this repo?

**Comment by richlander** [comment]
I was thinking about that exact question this morning.

Here are 3 different types of communication that I would like to have:

- Announcements (I suggest we match what ASP.NET is doing https://github.com/aspnet/Announcements/issues)
- Bug reporting (that's what is happening here)
- Designs (like https://github.com/dotnet/csharplang/issues)

I think they have to be in separate repos to be useful.

**Comment by bleroy** [comment]
I second @terrajobst that doing that on a separate repo would not be optimal: we already have quite a few, and it seems like this is a good fit for this as it's general purpose. Seems like an `Announcement` tag would do the job quite well.

**Comment by svick** [comment]
@bleroy In my opinion, the main advantage of having a separate repo for announcements is that you can watch it, and you will get email notifications for announcements and only announcements. Since GitHub does not let you watch a tag, that would not work as well if announcements were added to an existing repo.

This repo has fairly low volume, so maybe it wouldn't be that bad. But it's still likely going to be unnecessary noise for most.

BTW, the aspnet org on GitHub has more repos than dotnet (including aspnet/Announcements). Maybe that means having more repos is not a big issue?

**Comment by richlander** [comment]
@svick I like your scenario.

There are >2k people watch that repo. That's very compelling to me.

**Comment by TWinsnes** [comment]
I would love to see a separate announcement repo, I'm trying to follow development on this repo, but I have limited time and I have been getting flooded with notifications. Having an announcement repo would be great, as it would improve the signal/noise ratio for people that want to stay on top of what is happening, but don't have time to get deeply involved.

**Comment by shanselman** [comment]
Agreed that an announcements repo makes sense. dotnet/core feels very "Core" and internal. Announcements is totally unambiguous and means folks can sub to it without getting all the regular Core noise.

:shipit:

**Comment by jongalloway** [comment]
The https://github.com/aspnet/Announcements/issues repo has been really helpful for me, and I point a lot of people to it in my talks. It's great to have a separate repo I can subscribe to that just has announcements, no discussion, no code churn, etc.

**Comment by richlander** [comment]
We're going to do it. I'll post here when the various repos are up, share the links and then close this issue.

**Comment by leecow** [comment]
https://github.com/dotnet/announcements/
