### ISSUE TITLE
No project templates for .NET Core Class Library in Visual Studio 2015

### ISSUE THREAD

**Issue by ChrisBellew** [dotnet/core#521]
Hi.

I can no longer see product templates in Visual Studio 2015 for .NET Core Class Libraries. I right click on the project > Add > New Item and I see no templates like this.

http://imgur.com/a/2ZDDx

Any idea how I can fix this. I've tried repairing the .NET Core SDK and VS tools (latest).

**Comment by Petermarcu** [comment]
I'm not sure. @barrytang, any ideas?

**Comment by barrytang** [comment]
@Srivatsn/@Pilchie?

**Comment by Pilchie** [comment]
Can you try running `devenv /setup` as an administrator?

**Comment by Petermarcu** [comment]
Since it's been a few weeks, I'm going to close this for now. If its still an issue, please let us know.
