### ISSUE TITLE
CentOS 8 Update to 3.1.8 Causes netstandard2.1 Target Build Failure (with Workaround)

### ISSUE THREAD

**Issue by TikiBill** [dotnet/core#5212]
# Issue

Upgrading from dotnet-sdk-3.1.7 to 3.1.8 causes any netstandard2.1 targeted builds to fail.

1) Upgrade (dnf update dotnet*)
2) dotnet new classlib
3) change target to netstandard2.1
4) build

```shell
/usr/share/dotnet/sdk/3.1.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error MSB4018: The "ResolveTargetingPackAssets" task failed unexpectedly. [/home/bill/Code/scratch/test1/test1.csproj]
/usr/share/dotnet/sdk/3.1.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error MSB4018: System.IO.FileNotFoundException: Could not find file '/usr/share/dotnet/packs/NETStandard.Library.Ref/2.1.0/data/FrameworkList.xml'. [/home/bill/Code/scratch/test1/test1.csproj]
```

# Fix

```shell
rm -rfv /usr/share/dotnet/packs/NETStandard.Library.Ref
rm -rfv /usr/share/dotnet/packs/Microsoft.NETCore.App.Ref
```

Now the build works.

A similar workaround is mentioned in https://github.com/dotnet/core/issues/4526#issuecomment-632341088 so perhaps this issue is a dup?

### Thanks!

(Also, thank you so much for all the work and great ecosystem!)

EDIT: Add second directory which needs to be deleted.

**Comment by dagood** [comment]
@TikiBill, could you try running `dnf list installed 'dotnet-*' 'netstandard-*' 'aspnetcore-*'`? For example, this is what I get with the packages installed that were built by CentOS:

```
aspnetcore-runtime-3.1.x86_64                     3.1.7-1.el8_2                @AppStream
aspnetcore-targeting-pack-3.1.x86_64              3.1.7-1.el8_2                @AppStream
dotnet-apphost-pack-3.1.x86_64                    3.1.7-1.el8_2                @AppStream
dotnet-host.x86_64                                3.1.7-1.el8_2                @AppStream
dotnet-hostfxr-3.1.x86_64                         3.1.7-1.el8_2                @AppStream
dotnet-runtime-3.1.x86_64                         3.1.7-1.el8_2                @AppStream
dotnet-sdk-3.1.x86_64                             3.1.107-1.el8_2              @AppStream
dotnet-targeting-pack-3.1.x86_64                  3.1.7-1.el8_2                @AppStream
dotnet-templates-3.1.x86_64                       3.1.107-1.el8_2              @AppStream
netstandard-targeting-pack-2.1.x86_64             3.1.107-1.el8_2              @AppStream
```

I think you probably have mixed Microsoft-built and CentOS-built packages installed. This can be a problem around new updates with both repos installed at the same time.

Some more details at: https://github.com/dotnet/sdk/issues/12075#issuecomment-644516182, and someone else mentioned this fix in the next comment:

> Disabling the repository using:
> 
> ```shell
> sudo dnf config-manager --set-disabled packages-microsoft-com-prod
> ```
> 
> Then uninstalling the binaries and reinstalling with the F32 provided packages did the trick. Thank you very much.

**Comment by TikiBill** [comment]
Thank you for the quick response.

Indeed the conflicting repositories caused the issue. I had a yet-to-be-updated VM and made the suggested configuration change (disabling the MS repo) and all went well. I've updated my ansible script (originally for CentOS 7) to not include the MS .NET repo.

Closing as user error.

Thanks again.

**Comment by HymanZHAN** [comment]
@dagood Sorry to comment on a closed issue, but I am curious if there'are conflicts between Fedora/CentOS-built ones and Microsoft-built ones, how can I use the one built by Microsoft? I am asking because the Fedora one is still on 3.1.108 which does not come with WASM templates OOB and I want to use the latest 3.1.403. Thanks!

**Comment by omajid** [comment]
> If there'are conflicts between Fedora/CentOS-built ones and Microsoft-built ones, how can I use the one built by Microsoft? 

One way to do that is to exclude (aka disable) these packages from the Fedora repo. Then you can install them using the Microsoft repo or through a manual tarball.

Adding this line under `[fedora]` and `[updates]` in `/etc/yum.repos.d/fedora.repo` and `/etc/yum.repos.d/fedora-updates.repo` should do the trick:

```
exclude=dotnet* aspnet* netstandard*
```

Here's what the files look like on my end after making this change:

`/etc/yum.repos.d/fedora.repo`:

```ini
[fedora]
name=Fedora $releasever - $basearch
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
countme=1
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
exclude=dotnet* aspnet* netstandard*

[fedora-debuginfo]
name=Fedora $releasever - $basearch - Debug
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/debug/tree/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-source]
name=Fedora $releasever - Source
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/source/tree/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

`/etc/yum.repos.d/fedora-updates.repo`:

```ini
[updates]
name=Fedora $releasever - $basearch - Updates
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
enabled=1
countme=1
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
exclude=dotnet* aspnet* netstandard*

[updates-debuginfo]
name=Fedora $releasever - $basearch - Updates - Debug
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/debug/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch
enabled=0
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-source]
name=Fedora $releasever - Updates Source
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/SRPMS/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch
enabled=0
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

The same change should work for CentOS 8 as well.

**Comment by HymanZHAN** [comment]
@omajid Thanks! I will give it a try.
