### ISSUE TITLE
is .net core supported on freebsd?

### ISSUE THREAD

**Issue by rykr** [dotnet/core#522]
Just wondering if it's available on freebsd or if this is planned?

**Comment by Petermarcu** [comment]
The community has contributed changes to make it build and test on FreeBSD. Someone may be able to point you at instructions for how to build something you could use.

**Comment by tushartyagi** [comment]
I am interested in this as well. There's already some [documentation](https://github.com/dotnet/coreclr/blob/master/Documentation/building/freebsd-instructions.md) to build this on Freebsd.

Moreover, there's a discussion going on  [Issue#6115](https://github.com/dotnet/coreclr/issues/6115) with a (probably working? don't know) port [here](https://github.com/DragonSA/dotnet).

**Comment by Petermarcu** [comment]
Yes, we are supporting the effort to run on FreeBSD and we run tests on it to ensure upstream changes don't regress it. Microsoft doesn't have any official plans to release a FreeBSD version but the community has done a great job making it happen.
