### ISSUE TITLE
Regarding Running of .NET 

### ISSUE THREAD

**Issue by Parul-gif** [dotnet/core#5222]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

After following the whole process at last i am not able to run the following command 'dotnet run' in command prompt. 
Following is the error message that I have received -

Couldn't find a project to run. Ensure a project exists in C:\Users\HP PAVILION, or pass the path to the project using --project.

**Comment by mairaw** [comment]
You have to run the dotnet run inside the directory where the project was created. Did you run the command `cd myApp` to enter the project directory?
