### ISSUE TITLE
Error reference assemblies for .NETFramework,Version=v5.0 were not found

### ISSUE THREAD

**Issue by jinudh** [dotnet/core#5223]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Installed .net 5.0.100-rc.1.20452.10 SDK x64 
installed VS 2019 16.7.3 ( before .net SDK install) . but when creating projects throug vs 2019 and cmd  getting following error on 
dotnet run or dotnet build 
I could see .net5 template in VS2019 

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Microsoft.Common.CurrentVersion.targets(1178,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

**Comment by ImmutableVector** [comment]
I just struggled through this issue and was able to get past it by instead using the preview release for visual studio 16.8.0 Preview 3.0.

**Comment by mairaw** [comment]
We haven't upgraded the tutorials to use .NET 5 yet and we're still using the LTS version (.NET Core 3.1) on the install step.

@ImmutableVector is right. The minimum version for .NET 5 RC1 is VS 16.8 Preview 3.

**Comment by jinudh** [comment]
Thanks

**Comment by 6rashmijoshi** [comment]
i am facing this issue plz help me

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): Error: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
