### ISSUE TITLE
Can't run deployment

### ISSUE THREAD

**Issue by krisrajzlive** [dotnet/core#5228]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

kubectl apply -f deploy-myMicroService.yaml
error: error parsing deploy-myMicroService.yaml: error converting YAML to JSON: yaml: line 25: could not find expected ':'

**Comment by carlossanlop** [comment]
@shirhatti can you please help?

**Comment by carlossanlop** [comment]
@nishanil

**Comment by sughosneo** [comment]
Hi @krisrajzlive, thank you for reaching out.

Looking at the error message, it seems like there could be some issue while creating the `deploy-myMicroservice.yaml` mentioned in the steps [Create a deployment file](https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy). 
Could you please validate the deployment yaml  ?
