### ISSUE TITLE
SDK for .NET Core 1.1.1?

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/core#523]
The latest .NET Core App package (https://www.nuget.org/packages/Microsoft.NETCore.App/) delivers version 1.1.1. However:

The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.1
      1.1.0
  - Alternatively, install the framework version '1.1.1'.

I can't seem to find a download for SDK 1.1.1; am I missing something or was 1.1.1 released prematurely?

Thanks in advance
-Simon

**Comment by mikeandersun** [comment]
I have the same issue!

**Comment by Petermarcu** [comment]
@leecow ?

**Comment by leecow** [comment]
The SDK install links at https://www.microsoft.com/net/download/core will be up at 7:30 pacific time. In the meantime you can use https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md.

**Comment by leecow** [comment]
https://www.microsoft.com/net/download/core is live.
