### ISSUE TITLE
Error building with docker

### ISSUE THREAD

**Issue by Sandra479** [dotnet/core#5236]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows 10

I entered this command 
docker build -t mymicroservice .

and got this error
error during connect: ................
The system cannot find the file specified. In the default deamon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker deamon is not running

**Comment by carlossanlop** [comment]
@shirhatti can you please help?

**Comment by carlossanlop** [comment]
@nishanil

**Comment by sughosneo** [comment]
Hi @Sandra479, thank you for reaching out.

Is the docker running in your environment ?

Could you also please verify that the `Dockerfile` mentioned in this step [Add a DockerFile](https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file) has been created properly ?
You need to make sure that the name of the file is as `Dockerfile` and not Dockerfile.txt or some other name. In Windows OS you can verify that in a few ways. For e.g : 
1) By enabling the `File name extensions` checkbox. 
2) Or by opening the `myMicroservice` directory in an IDE for e.g `VSCode`

Hope this helps !
