### ISSUE TITLE
Enterprise users with air-gapped/private cloud environments can easily determine the latest .NET Core update they need, fetch it and use it for local deployment

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5241]
Multiple customers need a way to deploy their app along with the dependent Core runtime to private clouds. This is difficult for them today because the installers/bits are only available on the public CDN and public Azure blob storage. Also the tools, scripts and release metadata we offer today is designed to work with these public end points.  Each customer is working around this in a different way, for e.g. one customer is packaging our installer with their source build in order to piggy-back with the build to get it over to the air-gapped cloud. Another is copying over bits from our public blob storage to their private blob storage and maintains its own version of install scripts that go to the private blob. We have work to do here to make it easier for customers that need to use our installers in air-gapped/private cloud scenarios. 

This area needs further customer development.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
