### ISSUE TITLE
Installation not working.

### ISSUE THREAD

**Issue by Gideon357** [dotnet/core#5244]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I downloaded and installed the dotnet-sdk pkg, but upon running `dotnet` in a new zsh iTerm window, I get `zsh: command not found: dotnet`.

**Comment by Gideon357** [comment]
I was able to fix this by symlinking dotnet into usr/bin. The installer should probably do this, as it seems to be a common problem (15+ SO questions, with a number of views). 

```bash
ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/
```

**Comment by mairaw** [comment]
@leecow @dagood can you look at this issue?

**Comment by dagood** [comment]
Yeah, we're tracking making a change like this at https://github.com/dotnet/runtime/issues/3603. For a basic summary: today the installer relies on the built-in macOS utility `path_helper`, but it's easy to accidentally break this utility by using a bad bash profile (one that overrides `PATH` without incorporating its initial value), and `zsh` can even break it by default.
