### ISSUE TITLE
unable to start program 'dotnet.exe'

### ISSUE THREAD

**Issue by rmtpraveenkumar** [dotnet/core#5253]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

While debugging .net core console application received "unable to start program 'dotnet.exe'. I am using Visual Studio 2017.
Please help in resolving this issue,

**Comment by mairaw** [comment]
If you want to use Visual Studio for this tutorial, you need to install Visual Studio 2019 (v16.7)
The Community edition is free: https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16

And you can install multiple versions of Visual Studio on the same machine.

However, you don't really need Visual Studio to complete this tutorial.
Have you installed the SDK as instructed in the install step?
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
