### ISSUE TITLE
.NET was not installing in my system. showing error code 5100

### ISSUE THREAD

**Issue by Prasanna-CA** [dotnet/core#5256]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Prasanna-CA** [comment]
unable to download .net 4.7.2 in my pc, showing error code 5100

**Comment by scalablecory** [comment]
The tutorial link you've provided is for .NET Core, but your subsequent comment mentions .NET Framework.

Can you confirm this is a .NET Core issue, and provide more data? Console output/screenshots etc.
