### ISSUE TITLE
releases.json shows support phase different from releases-index.json

### ISSUE THREAD

**Issue by ap0llo** [dotnet/core#5258]
I noticed that the `releases-index.json` at <https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json> lists .NET Core 1.0 and 2.2 as EOL (which is correct I suppose):

```
{

    "releases-index": [
        ....
        {
            "channel-version": "1.0",
            "support-phase": "eol",
            "eol-date": "2019-06-27",
            "releases.json": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/1.0/releases.json"
        },
        {
            "channel-version": "2.2",
            "support-phase": "eol",
            "releases.json": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json"
        }
        ....       
   ]
}
```

However, for both releases, the referenced `releases.json` specifies a support phase of  `maintenance`

<https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/1.0/releases.json>:
```json
{
  "channel-version": "1.0",
  "support-phase": "maintenance",
  "eol-date": "2019-06-27",
}
```

<https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json>
```json
{
  "channel-version": "2.2",
  "support-phase": "maintenance",
  "eol-date": "2019-12-23",
}
```

I think both files should contain the same support phase for a release.

**Comment by rbhanda** [comment]
@silvioguiso for investigation. I have updated both the files.

**Comment by carlossanlop** [comment]
@rbhanda closing since it's resolved. Feel free to reopen if needed.
