### ISSUE TITLE
Error response from daemon: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by petepolyak** [dotnet/core#5259]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by petepolyak** [comment]
File Structure:
Controllers			Properties			appsettings.Development.json	myMicroservice.csproj
DockerFile			Startup.cs			appsettings.json		myMicroservice.sln
Program.cs			WeatherForecast.cs		bin				obj

Dockerfile:
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY myMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]

**Comment by carlossanlop** [comment]
@shirhatti can you please help?

**Comment by carlossanlop** [comment]
@nishanil
