### ISSUE TITLE
error code 0x800704b3 when performing initial download

### ISSUE THREAD

**Issue by johndeoi** [dotnet/core#5262]
[Microsoft_.NET_Core_SDK_3.1.402_(x64)_20200926144052.log](https://github.com/dotnet/core/files/5287254/Microsoft_.NET_Core_SDK_3.1.402_.x64._20200926144052.log)

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmosemsft** [comment]
@johndeoi that means ERROR_NO_NET_OR_BAD_PATH "The network path was either typed incorrectly, does not exist, or the network provider is not currently available."

If you try again, does it work?

**Comment by mairaw** [comment]
Closing due to the lack of response. Please reactivate if you're still running into issues.
