### ISSUE TITLE
i have a error saying: "A Project With a output type of Class Library Cannot be directly started. In order to debug this project, Add an executable to this solution which references to the library. Set the Executable Project as the startup project." I currently don't know how to fix this. Any help?? I was trying to create a "Hello World" program with .NET, here's the code: https://pastebin.com/JhBT69hK

### ISSUE THREAD

**Issue by TjoshgGaming123** [dotnet/core#5266]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmosemsft** [comment]
Hi @TjoshgGaming123 how did you create the project? If on the command line, was it with "dotnet new console -o MyApp" as in the link above? If in Visual Studio, you need to choose the "application" rather than "class library" template.

**Comment by carlossanlop** [comment]
Try doing what the error message is suggesting:
```
In order to debug this project, Add an executable to this solution which references to the library. Set the Executable Project as the startup project.
```
