### ISSUE TITLE
.NET 5 RC.1 - UITypeEditor Class

### ISSUE THREAD

**Issue by Taiizor** [dotnet/core#5269]
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.design.uitypeeditor?view=net-5.0

The UITypeEditor class is not used for NET5. They say it's supported, but I don't agree with that.
I can't use it in a library that used NET5.

Examples:
![image](https://user-images.githubusercontent.com/41683699/94376531-b9587f80-0123-11eb-9505-42d02b7e0713.png)
![image](https://user-images.githubusercontent.com/41683699/94376549-cf664000-0123-11eb-90b9-b79ddf155615.png)

**Comment by svick** [comment]
It works fine for me in a .Net 5.0 library whose csproj looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```

Can you share your csproj?

**Comment by Taiizor** [comment]
> Bu csproj bu gibi görünüyor bir .Net 5.0 kütüphanede benim için iyi çalışıyor:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <TargetFramework>net5.0</TargetFramework>
>     <UseWindowsForms>true</UseWindowsForms>
>   </PropertyGroup>
> 
> </Project>
> ```
> 
> Csproj'unuzu paylaşabilir misiniz?

`<UseWindowsForms>true</UseWindowsForms>` It was fixed when I added the code :)
