### ISSUE TITLE
donet not recognized on windows server 2019 after installation

### ISSUE THREAD

**Issue by qboy21** [dotnet/core#5273]
<img width="346" alt="Screen Shot 2020-09-28 at 11 56 02 AM" src="https://user-images.githubusercontent.com/14353482/94456730-9d83c680-0181-11eb-9a51-32993d9cf4b5.png">
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
The tutorial states that you need to close the cmd window after you install the SDK, so that the next time you open the cmd window, the environment variables are updated. Did you make sure to do that?

**Comment by qboy21** [comment]
thank you. resolved.
