### ISSUE TITLE
http://localhost:5000/

### ISSUE THREAD

**Issue by sumongogo** [dotnet/core#5274]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by sumongogo** [comment]
when i tried to browse http://localhost:5000/
I got error message that "this site can't be reached. local host refused to connect

**Comment by sumongogo** [comment]
when i tried to browse http://localhost:5000/
I got error message that "this site can't be reached. local host refused to connect
My windows version is Windows7

**Comment by sumongogo** [comment]
please help me

**Comment by mairaw** [comment]
Are you running the project?
