### ISSUE TITLE
Span<T> and ReadOnlySpan<T> are tagged with System.ObsoleteAttribute in 5.0.0-rc.1.20451.14 (and before)

### ISSUE THREAD

**Issue by psmacchia** [dotnet/core#5275]
In **C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0-rc.1.20451.14\System.Private.CoreLib.dll** `Span<T>` and `ReadOnlySpan<T>` are tagged with `System.ObsoleteAttribute` the message is: **"Types with embedded references are not supported in this version of your compiler."**.

It looks like it is a compiler versioning issue when compiling _System.Private.CoreLib.dll_.

It looks like this Obsolete tag was here for long. [Here we can see that resharper stumbled on it in August 2018](https://stackoverflow.com/questions/51942986/types-with-embedded-references-are-not-supported).

![image](https://user-images.githubusercontent.com/511445/94511722-3c183200-022b-11eb-85ec-364907f568c7.png)

**Comment by svick** [comment]
This is not some issue, it's expected. The attribute exists so that compilers not aware of `Span` limitations can't use it. But `Span`-aware compilers ignore it.

**Comment by psmacchia** [comment]
Ok thanks for the precision, this is helpful.
