### ISSUE TITLE
Duplicate links in dotnet.microsoft.com

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/core#5279]
- Click **All Microsoft** in the top-right corner in https://dotnet.microsoft.com/
- Links for **Microsoft HoloLens** and **Mixed Reality** are **different** but redirects to the **same page**.

Also, consider avoiding localization for links when possible.

cc: @mairaw
Feel free if you want to move this issue to the internal (private) repository.

**Comment by mairaw** [comment]
Thanks for the feedback @Youssef1313. I'll keep this one open until the issue is fixed or I hear back from the team responsible for that menu.

**Comment by mairaw** [comment]
Seems to be fixed now. Closing.
