### ISSUE TITLE
Error when creating Docker Image from microsoft tutorial

### ISSUE THREAD

**Issue by trivli** [dotnet/core#5285]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows 10.0.18363

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Output:
C:\Users\til\myMircoservice>docker build -t mymicroservice .
[+] Building 0.7s (9/14)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 337B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/core/aspnet:3.1                                          0.7s
 => [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1                                             0.7s
 => CANCELED [build 1/6] FROM mcr.microsoft.com/dotnet/core/sdk:3.1@sha256:95f46b6614f7fb759cdad3b38286e6d9a25422  0.0s
 => => resolve mcr.microsoft.com/dotnet/core/sdk:3.1@sha256:95f46b6614f7fb759cdad3b38286e6d9a25422113a07b5862dec1  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 5.45kB                                                                                0.0s
 => CANCELED [stage-1 1/3] FROM mcr.microsoft.com/dotnet/core/aspnet:3.1@sha256:adeb306016cb11425faad95b59f138c58  0.0s
 => => resolve mcr.microsoft.com/dotnet/core/aspnet:3.1@sha256:adeb306016cb11425faad95b59f138c58910023f5754caeecd  0.0s
 => CACHED [build 2/6] WORKDIR /src                                                                                0.0s
 => ERROR [build 3/6] COPY myMicroservice.csproj .                                                                 0.0s
------
 > [build 3/6] COPY myMicroservice.csproj .:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/myMicroservice.csproj" not found: not found

**Comment by carlossanlop** [comment]
@shirhatti can you please take a look?

**Comment by carlossanlop** [comment]
@nishanil

**Comment by sughosneo** [comment]
Hi @trivli, thank you for reaching out.

From the output message, `CACHED [build 2/6] WORKDIR /src 0.0s` it seems like you are trying to rebuild the docker image again. 
Could you please try to `Clean/ Purge data` in `Docker Desktop` and try to build it from scratch ?

Hope this helps !
