### ISSUE TITLE
Run your app In your command prompt, run the following command:

### ISSUE THREAD

**Issue by mahmoud-abdeltawab** [dotnet/core#5287]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mahmoud-abdeltawab** [comment]
win 10 64 os 
![image](https://user-images.githubusercontent.com/72207961/94815507-e3978f00-03fa-11eb-9041-11d29ddc4f25.png)

**Comment by mahmoud-abdeltawab** [comment]
Help me !!

**Comment by mairaw** [comment]
So the app is running. Did you try to open a browser and navigate to http://localhost:500?
