### ISSUE TITLE
@page @model IndexModel @{     ViewData["Title"] = "Home page"; }  <div class="text-center">     <h1>Hello, world!</h1>     <p>The time on the server is @DateTime.Now</p> </div>

### ISSUE THREAD

**Issue by mahmoud-abdeltawab** [dotnet/core#5288]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What is the problem you're having @mahmoud-abdeltawab?
