### ISSUE TITLE
Open Pages/Index.cshtml in any text editor and replace all of the code with the following, then save the file.

### ISSUE THREAD

**Issue by mahmoud-abdeltawab** [dotnet/core#5289]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mahmoud-abdeltawab** [comment]
![Uploading image.png…]()

**Comment by mahmoud-abdeltawab** [comment]
Refresh the browser to see the change:

**Comment by mairaw** [comment]
I can't see the error you're having @mahmoud-abdeltawab. Can you try to upload the screenshot one more time?
