### ISSUE TITLE
How do the Known Issues entries work?

### ISSUE THREAD

**Issue by omajid** [dotnet/core#5293]
.NET 5 has a list of known issues: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md

I don't quite understand how the items on that work and when they are considered "resolved".

If there's a known issue listed under Preview 1, for example, does that mean that issue affects Preview 1 and later? Or does mean that it only affects Preview 1 and has been resolved in the future releases, starting from Preview 2? If a known issue affects multiple releases, will it be listed in multiple releases?

What does it mean when a commit (such as https://github.com/dotnet/core/pull/5198/files) removes some known issues? Does that mean it was fixed in that particular release? Was a Preview 8 respun to fix it?

For the items where there is no specific link to a github issue, what's the best way to track a fix? For example, the known issue "Running xUnit tests fails to discover tests in with message ..." doesn't have a link to a specific github issue. Does that mean it wont be fixed? And upgrading to .NET 5.0 GA involves applying the fix ("To solve this update your xunit.runner.visualstudio package to version 2.4.3") suggested? Or is that a temporary workaround only needed for Preview 8 that will not be required for later releases like RC1 or .NET 5 GA?

**Comment by omajid** [comment]
cc @dleeapho @leecow @rbhanda

**Comment by leecow** [comment]
The idea is that individual entries are evaluated for subsequent releases and, when fixed, decorated with "Resolved in Preview X" with a link to the appropriate commit. 

@rbhanda - let's make sure the teams review past known issues before the RC2 release so that the document is current and useful.

**Comment by omajid** [comment]
@leecow Thanks. Does that mean [this line](https://github.com/dotnet/core/pull/5198/files#r498477129 ) should be added back?

**Comment by leecow** [comment]
Yes, I think so. Digging through the changelog for resolved issues isn't a great experience and the Known Issues doc should be an easily understood historical record.

**Comment by omajid** [comment]
Thanks for answering my questions!
