### ISSUE TITLE
How to install NET .SDK

### ISSUE THREAD

**Issue by moiza261** [dotnet/core#5297]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You just need to click the button to download the file and click on it to execute it when it finishes downloading. Then just follow the prompts! Let us know if it works or if you run into any issues.

**Comment by moiza261** [comment]
my problem is not solved

**Comment by moiza261** [comment]
> You just need to click the button to download the file and click on it to execute it when it finishes downloading. Then just follow the prompts! Let us know if it works or if you run into any issues.

my problem is not solved

**Comment by mairaw** [comment]
What is exactly the problem you're having? Are you getting an error message? Not finding what you need?

**Comment by lindexi** [comment]
x 86 x 64?
