### ISSUE TITLE
Error In VS Code

### ISSUE THREAD

**Issue by NISARG100** [dotnet/core#5302]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My PC specs ..,
32-bit Windows 7 Ultimate

![Error](https://user-images.githubusercontent.com/72347021/95018079-e3a5c200-067a-11eb-9e2e-9a5463987126.png)

**Comment by scalablecory** [comment]
Have you tried installing the prerequisites from the link there?

**Comment by mairaw** [comment]
Also, can you try running this same command on a command prompt window outside VS Code to see if you'd get the same error message?
