### ISSUE TITLE
Ugly log level prefixes under CentOS 8

### ISSUE THREAD

**Issue by JoFrMueller** [dotnet/core#5303]
# Issue Title

CentOS 8 logs escaped log level prefixes in a strange way.

# General

## Dotnet core and operating system versions

```bash
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.1 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.1 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

$ dotnet --list-sdks
3.1.101 [/usr/lib64/dotnet/sdk]

$ rpm -q centos-release
centos-release-8.1-1.1911.0.9.el8.x86_64
```

## Weird behaviour

Default log messages do look quite confusing around the log level output. Seems like quite strangely formatted/escaped characters.

```bash
Oct 5 10:53:12 XXX XXX[43316]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
```

# Expected behaviour

* Default log messages should look *"normal"*.
* No further configuration of log output in CentOS8 environment.

**Comment by tmds** [comment]
@JoFrMueller I think this is the same issue as https://github.com/dotnet/runtime/issues/37421 and it will be better with .NET 5: when an ASP.NET application runs under a redirected environment it will no longer output ANSI color codes by default.

**Comment by scalablecory** [comment]
@JoFrMueller can you please try with .NET 5? Thanks.
