### ISSUE TITLE
Trying to install and run .NET

### ISSUE THREAD

**Issue by clairyone** [dotnet/core#5308]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I heve downloaded both 
32-bit download & 64- bit but nothing works, Do I have to do something else? I have windows 10
I attached a photo, question> Is that correct? Where is the command line?
![Στιγμιότυπο οθόνης (128)](https://user-images.githubusercontent.com/72437546/95207167-3d7bc880-07f0-11eb-8d47-388e39ca4d38.png)

**Comment by mairaw** [comment]
The tutorials are actually using .NET Core, not .NET Framework. .NET Core is our newer product.

For opening the command prompt:
- Press the Windows logo key on the taskbar ![image](https://user-images.githubusercontent.com/12971179/95250454-fa5d2d80-07ce-11eb-9f4d-53b1c77293ae.png)
- Type command and click on the command prompt app
![image](https://user-images.githubusercontent.com/12971179/95250532-16f96580-07cf-11eb-81f7-759306537602.png)

Let us know if this helps!

**Comment by clairyone** [comment]
Thank you, i found the Windows 10 through Windows logo key+R

**Comment by mairaw** [comment]
Closing since this issue seems resolved. Let us know otherwise.
