### ISSUE TITLE
dotnet command not found

### ISSUE THREAD

**Issue by MReeds** [dotnet/core#5309]
Problem encountered on https://dotnet.microsoft.com/install
Operating System: windows

Installed .NET 64-bit SDK and opened new terminal to execute "dotnet" but received not found. I've tried researching other ways but can't seem to find great resources

**Comment by mairaw** [comment]
Did you open a new command prompt to execute the command after the installation was done?

You might want to check if the SDK was properly installed:
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows#check-for-install-folders
