### ISSUE TITLE
Build Error using .net5

### ISSUE THREAD

**Issue by anaya-upadhyay** [dotnet/core#5311]
# Build Error: [The reference assemblies for .NETFramework,Version=v5.0 were not found]

I created a .Net Core Console Application.
It gives me build error as "The reference assemblies for .NETFramework,Version=v5.0 were not found".

- I've already installed .NET 5.0 SDK (v5.0.100-rc.1).
- I've got VS2019 v16.7.5

![image](https://user-images.githubusercontent.com/16795691/95302619-eb937b00-08a1-11eb-84db-3835628b4f97.png)

**Comment by mairaw** [comment]
The minimum version for using .NET 5 RC1 with Visual Studio is version 16.8 Preview 3. 
https://dotnet.microsoft.com/download/dotnet/5.0

Let us know if you see the same issues using that version.

**Comment by anaya-upadhyay** [comment]
@mairaw Thank you for the quick reply. My bad I didn't look for the version of VS.

Can I use .net 5 via Visual Studio Code?
