### ISSUE TITLE
core3.1 update to 5.0rc1 musl-x86_64.so.1: bad ELF interpreter

### ISSUE THREAD

**Issue by realJohnLock** [dotnet/core#5314]
# core3.1 update to 5.0rc1 musl-x86_64.so.1: bad ELF interpreter

When I update core3.1 to 5.0rc1 there are some error happend:
$ dotnet
-bash: /public/home/Skleac_wj_01/program/dotnet/5.0rc1/dotnet: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

I am sure in the core3.1 is ok. How could I fixed this.

**Comment by dagood** [comment]
I have a few questions:

* How did you install 5.0 rc1?
  * (What page did you go to, what file did you download, what method did you use to update, etc.)
* What OS are you running?
  * If it isn't something "ordinary" like Ubuntu, do you know if it uses *glibc*, or *musl*?

**Comment by realJohnLock** [comment]
The OS which I am running is the RedHat 7.2, The C standard library is glibc, we don't install the musl at all, I don't know why dotnet link to the musl.
I am trying to install the .net 5rc1 to my university cluster, I am not the root user, so I cann't install .net5 with RPM file.   I installed the .net5 as follow,
(1) I download the binary file dotnet-sdk-5.0.100-rc.1.20452.10-linux-musl-x64.tar.gz from the web.
(2) Then I untared the dotnet-sdk-5.0.100-rc.1.20452.10-linux-musl-x64.tar.gz to ~/program/dotnet/5.0rc1
(3) The PATH also add to the bash profile. export DOTNET_ROOT=$HOME/program/dotnet/5.0rc1; export PATH=$PATH:$HOME/program/dotnet/5.0rc1; 

 All the install process as well as the .net3.1. What did i wrong?

Thank your help.

**Comment by dagood** [comment]
This file is for musl:

> dotnet-sdk-5.0.100-rc.1.20452.10-linux-musl-x64.tar.gz

Instead, you should download the file for glibc:

> dotnet-sdk-5.0.100-rc.1.20452.10-linux-x64.tar.gz

You didn't mention where you got this file, but my theory is you got it from https://dotnet.microsoft.com/download/dotnet/5.0, specifically here:

![image](https://user-images.githubusercontent.com/12819531/95467105-b0955400-0942-11eb-9742-16a8fd6abc9b.png)

But that's actually the `x64 Alpine` link, which uses musl:

![image](https://user-images.githubusercontent.com/12819531/95467239-d884b780-0942-11eb-8781-443a2cff78ae.png)

You need to download this one instead for glibc:

![image](https://user-images.githubusercontent.com/12819531/95467298-e5a1a680-0942-11eb-9fa8-2c82d28d53f8.png)

https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.100-rc.1-linux-x64-binaries

I reported this wrapping problem on the (private) website repo a few weeks ago but it hasn't been fixed quite yet. /cc @mairaw 

---

@realJohnLock is that what happened?

**Comment by realJohnLock** [comment]
Thank you dagood. The net5 works now. No doubt I had blundered.

**Comment by dagood** [comment]
Cool, thanks for confirming. 🙂 Hopefully we'll get the UI clarified soon.
