### ISSUE TITLE
The "View code" command does not work for files with a custom extensions

### ISSUE THREAD

**Issue by 87Alex** [dotnet/core#5317]
**#The "View Code" command does not work for files with custom extensions

I have two solutions: one with a .NET Core 3.1 project and the second one with a Framework v4.7.2 project. Both projects have the XMLFileAAA.wersd file added as follows:

```
  <ItemGroup>
    <EmbeddedResource Include="XMLFileAAA.wersd" >
       <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

```

When I execute the View Code command in the XMLFileAAA.wersd file, it has no effect in the .NET Core project and successfully opens the Text Editor in the Framework project. See the video attached.
![YrF7G8DQu3](https://user-images.githubusercontent.com/39731874/95444077-0fb89000-0966-11eb-95a7-c7f1766c09fc.gif)

**Comment by carlossanlop** [comment]
This is a Visual Studio issue. Can you please report it here? https://developercommunity.visualstudio.com/spaces/8/index.html
