### ISSUE TITLE
This example does not work when you publish/run in WSL 2

### ISSUE THREAD

**Issue by samgithub** [dotnet/core#5320]
My target platform is a linux-64, so I am pre-publishing the microservice using
Step 1:  **dotnet publish -c Release -o publish -r linux-x64**

Then I create an image using
**docker build -t microservice -f Dockerfile .**

Then create a container within WSL **Ubunto** 20.0.4

**docker run -it --rm -p 3000:80 --name microservicecontainer microserviceI** 

Problem : I cannot access the service from a browser on Win10) (http://localhost:3000)
************************************************************
**Results From docker run in WSL**
info: Microsoft.Hosting.Lifetime[0]
      **Now listening on: http://localhost:5000**
info: Microsoft.Hosting.Lifetime[0]
      **Now listening on: https://localhost:5001**
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /publish
info: Microsoft.Hosting.Lifetime[0]
*************************************************************

I noticed that Ketrel was listening to 5000 and 5001

So I changed the run to:
**docker run -it --rm -p 5000:80 --name microservicecontainer microserviceI** 
BUT http://localhost:5000 doesn't work either.

**My Dockerfile**
**************************************
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
COPY ./publish /publish
WORKDIR /publish
ENTRYPOINT ["dotnet", "myMicroservice.dll"]
**************************************
The example as shown does work - but its strictly a Windows sample.
REQUEST: Can you provide the same sample, publish to a Linux-64 target; and run it under WSL?  --- please.

**Comment by mairaw** [comment]
Where are you seeing this example @samgithub?

**Comment by samgithub** [comment]
Its the example at

https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro

**Comment by mairaw** [comment]
Adding @shirhatti and @nishanil to help here

We do offer Linux versions of the tutorials too - just click on the Linux tab:
https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro?initial-os=linux

And then we also have a deployment one:
https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/intro?initial-os=linux

Does that help?

**Comment by samgithub** [comment]
Since VS is cross-platform and allows publishing to different targets, an example would greatly help.
Thanks

**Comment by mairaw** [comment]
@shirhatti @nishanil can you help on this issue?

**Comment by nishanil** [comment]
hey @samgithub ! I followed the exact steps listed on that the page and was able to run it inside WSL. See this: https://1drv.ms/u/s!AupZwrZ-sEsggZw9dmMeGjgZe7oG-Q?e=Dfn1ru

**Comment by nishanil** [comment]
I added some log info for you.
![image](https://user-images.githubusercontent.com/3107766/96029227-fb015e00-0e77-11eb-9a48-f0c85d6e3a43.png)
Try executing the exact steps listed in the page https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro?initial-os=linux first. Then compare the code with yours to see what you were doing wrong,

**Comment by samgithub** [comment]
Are you creating a LINUX IMAGE?  That's what I'm talking about. The Windows
image works. Its the publish to linux-x64 and Use a container from it that
does not work.

**Comment by nishanil** [comment]
Yes, it is a Linux image. See the OS Version.

**Comment by mairaw** [comment]
Given this is a bit old and beyond the scope of the tutorial, I'm closing this. Please reactivate if you still need assistance.
