### ISSUE TITLE
Change Directory did not work.  Did not create directory

### ISSUE THREAD

**Issue by justj1979** [dotnet/core#5332]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Getting ready...
Couldn't find an installed template that matches the input, searching online for one that does...
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.

Invalid input switch:
  --https
ASP.NET Core Web App (C#)
Author: Microsoft
Description: A project template for creating an ASP.NET Core application with example ASP.NET Core Razor Pages content
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/3.1-third-party-notices for details.
Options:
  -au|--auth                        The type of authentication to use
                                        None             - No authentication
                                        Individual       - Individual authentication
                                        IndividualB2C    - Individual authentication with Azure AD B2C
                                        SingleOrg        - Organizational authentication for a single tenant
                                        MultiOrg         - Organizational authentication for multiple tenants
                                        Windows          - Windows authentication
                                    Default: None

  --aad-b2c-instance                The Azure Active Directory B2C instance to connect to (use with IndividualB2C auth).
                                    string - Optional
                                    Default: https://login.microsoftonline.com/tfp/

  -ssp|--susi-policy-id             The sign-in and sign-up policy ID for this project (use with IndividualB2C auth).
                                    string - Optional

  -rp|--reset-password-policy-id    The reset password policy ID for this project (use with IndividualB2C auth).
                                    string - Optional

  -ep|--edit-profile-policy-id      The edit profile policy ID for this project (use with IndividualB2C auth).
                                    string - Optional

  --aad-instance                    The Azure Active Directory instance to connect to (use with SingleOrg or MultiOrg auth).
                                    string - Optional
                                    Default: https://login.microsoftonline.com/

  --client-id                       The Client ID for this project (use with IndividualB2C, SingleOrg or MultiOrg auth).
                                    string - Optional
                                    Default: 11111111-1111-1111-11111111111111111

  --domain                          The domain for the directory tenant (use with SingleOrg or IndividualB2C auth).
                                    string - Optional
                                    Default: qualified.domain.name

  --tenant-id                       The TenantId ID of the directory to connect to (use with SingleOrg auth).
                                    string - Optional
                                    Default: 22222222-2222-2222-2222-222222222222

  --callback-path                   The request path within the application's base path of the redirect URI (use with SingleOrg or IndividualB2C auth).
                                    string - Optional
                                    Default: /signin-oidc

  -r|--org-read-access              Whether or not to allow this application read access to the directory (only applies to SingleOrg or MultiOrg auth).
                                    bool - Optional
                                    Default: false / (*) true

  --exclude-launch-settings         Whether to exclude launchSettings.json in the generated template.
                                    bool - Optional
                                    Default: false / (*) true

  --no-restore                      If specified, skips the automatic restore of the project on create.
                                    bool - Optional
                                    Default: false / (*) true

  --no-https                        Whether to turn off HTTPS. This option only applies if Individual, IndividualB2C, SingleOrg, or MultiOrg aren't used for --auth.
                                    bool - Optional
                                    Default: false / (*) true

  -uld|--use-local-db               Whether to use LocalDB instead of SQLite. This option only applies if --auth Individual or --auth IndividualB2C is specified.
                                    bool - Optional
                                    Default: false / (*) true

  -rrc|--razor-runtime-compilation  Determines if the project is configured to use Razor runtime compilation in Debug builds.
                                    bool - Optional
                                    Default: false / (*) true

  -f|--framework                    The target framework for the project.
                                        netcoreapp3.1    - Target netcoreapp3.1
                                        netcoreapp2.1    - Target netcoreapp2.1
                                    Default: netcoreapp3.1

  --use-browserlink                 Whether or not to include BrowserLink in the project
                                    bool - Optional
                                    Default: false / (*) true

* Indicates the value used if the switch is provided without a value.

C:\Users\hp>cd myWebApp
The system cannot find the path specified.

C:\Users\hp>dotnet run
Couldn't find a project to run. Ensure a project exists in C:\Users\hp, or pass the path to the project using --project.

**Comment by scalablecory** [comment]
It looks like you entered "--https" rather than "--no-https". Can you make sure you've typed it exactly as it's shown in the tutorial and check back?
