### ISSUE TITLE
Getting the bundle executable location in single file app.

### ISSUE THREAD

**Issue by isness** [dotnet/core#5335]
When running an appliaction that was produced as a single file, the actual executable runs from user's TMP folder. The problem is that `System.Reflection.Assembly.GetExecutingAssembly().Location` returns the location inside the user's TMP folder.
I need to get the location of the original bundle that the application was extracted from.
How do I accomplish this?

**Comment by scalablecory** [comment]
This was resolved with a new API in .NET 6 here: https://github.com/dotnet/runtime/issues/40862

A workaround for older .NET versions is to call `Process.GetCurrentProcess().MainModule.FileName`.
