### ISSUE TITLE
getting 404 error while browsing /WeatherForecast  URL

### ISSUE THREAD

**Issue by harshendra181** [dotnet/core#5336]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

This localhost page can’t be foundNo webpage was found for the web address: http://localhost:5000/WeatherForecast
HTTP ERROR 404

**Comment by mairaw** [comment]
And do you have the project running? That is, did you type `dotnet run`?
