### ISSUE TITLE
webAPP is deprecated?

### ISSUE THREAD

**Issue by cos702003** [dotnet/core#5339]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

The tutorial says to create a new webApp, but the webApp function is deprecated it looks like. It suggests using "dotnet new mvc --auth Individual" or "dotnet new web" to create the project now.

**Comment by mairaw** [comment]
@danroth27 can you comment on that?

**Comment by danroth27** [comment]
`dotnet new webapp` isn't deprecated and is still the recommended way to create an ASP.NET Core web app project based on Razor ages. `dotnet new mvc` is how you'd create an ASP.NET Core MVC based project, which is also fully supported.

@cos702003 Where are you seeing that `dotnet new webapp` is deprecated? Maybe we have some incorrect docs someplace?
