### ISSUE TITLE
5.0/releases.json is malformed

### ISSUE THREAD

**Issue by martincostello** [dotnet/core#5342]
The JSON in [`5.0/releases.json`](https://github.com/dotnet/core/blob/21f817261f29fc4622fe3048b9ead6fc6f909308/release-notes/5.0/releases.json) is malformed and does not parse as valid (checked using [jsonlint](https://jsonlint.com/)).

The file appears to have been truncated when the 5.0 RC2 content was added by #5340.

```
Error: Parse error on line 3738:
...iles": []				}			}
```

/cc @rbhanda

**Comment by rbhanda** [comment]
Resolved by https://github.com/dotnet/core/pull/5343
