### ISSUE TITLE
.NET 5 RC 2

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5345]
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2.md)

Please report any issues you find with .NET 5, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

### Known Issues
If there are any issues with the October 2020 release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [x] 5.0 release.json is malformed https://github.com/dotnet/core/issues/5342
- [x] 5.0 Link for 5.0 RC2 release notes in 5.0 release.json is incorrect. This was resolved by https://github.com/dotnet/core/pull/5349
- [x] Microsoft.DotNet.Mage is not available on Nuget.org - [Resolved ](https://www.nuget.org/packages/Microsoft.DotNet.Mage/5.0.0-rc.2.20513.1) by https://github.com/dotnet/deployment-tools/pull/42.
- [x] Unable to install 5.0 RC2 on Ubuntu 20.10 https://github.com/dotnet/core/issues/5352

**Comment by reinux** [comment]
[This problem](https://github.com/dotnet/core/issues/5200#issuecomment-698735855) persists on my machine with RC2 (RC1 uninstalled).

Even just using .fsx, with preview language features enabled, I get a slew of errors:

> Error	FS3217	error NU1102: Unable to find package FSharp.Core with version (>= 5.0.0)	F# Miscellaneous Files	
> Error	FS3217	error NU1102:   - Found 35 version(s) in nuget.org [ Nearest version: 5.0.0-beta.20417.1 ]	F# Miscellaneous Files
> Error	FS3217	error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages	F# Miscellaneous Files
>

**Comment by mairaw** [comment]
Tagging @cartermp and @KathleenDollard

**Comment by TropicalThunder** [comment]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NETSDK1130	Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.	Project.SomeName	C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	934	
>

**Comment by ZacharyPatten** [comment]
_Sorry if this should be posted elsewhere..._

I've been seeing an issue in both Release Candidate 1 and 2 **_(so it is not specific to rc2)_** with Blazor Webassembly Projects. It appears like the `dotnet` executable is hanging after I stop debugging. So I can debug once, but successive times I get the following error:
```
The application is in break mode
```
![image](https://user-images.githubusercontent.com/3385986/96003199-fac97a00-0e07-11eb-8079-6c22b1b72b65.png)
Here is the content from the `Copy Details`
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'input')
  Source=System.Text.RegularExpressions
  StackTrace:
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.<>c__DisplayClass10_0.<CompleteTaskWhenServerIsReady>g__OnOutputDataReceived|0(Object sender, DataReceivedEventArgs eventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```
usually accompanied with the following pop-up
![image](https://user-images.githubusercontent.com/3385986/96003138-e84f4080-0e07-11eb-823d-ce16746ae66a.png)
However, if (after a debugging session) I kill the `dotnet` process then it works just fine
![image](https://user-images.githubusercontent.com/3385986/96003534-4f6cf500-0e08-11eb-8757-9f420eb0e374.png)
It is pretty annoying to have to kill the process after every debugging attempt.

Not sure if this is an issue unique to my machine or not.

**Comment by reinux** [comment]
I'm becoming more convinced that this is more of a problem with the SDK installer.

Steps:

- Uninstall all versions of .NET Core and VS
- Install SDK 5.0.100-rc.2 using the x64 MSI
- dotnet new console (C# project)
- dotnet run
- dotnet build

Output:

> C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Microsoft.Common.CurrentVersion.targets(1180,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\rei\source\repos\Test3\Test3.csproj]

**Comment by reinux** [comment]
Repairing the .NET 5 RC2 SDK fails. Here's the log file.
[Microsoft_.NET_SDK_5.0.100-rc.2.20479.15_(x64)_20201017040650.log](https://github.com/dotnet/core/files/5395516/Microsoft_.NET_SDK_5.0.100-rc.2.20479.15_.x64._20201017040650.log)

**Comment by rbhanda** [comment]
@joeloff Can you help here with .NET 5 RC2 SDK installation failure?

**Comment by joeloff** [comment]
@reinux can you try deleting this file: C:\ProgramData\Package Cache\{35392F9B-1C64-368F-BBE1-CDFD0B381B94}v5.0.0.0\AspNetCoreSharedFramework-x64.msi

Then run repair again

**Comment by waldimen** [comment]
Installed snap version of .NET 5 RC2 SDK on Kubuntu 20.04. When I try to run dotnet-sdk.dotnet build for a new console application I get MSB3644 error about not finding .NETFramework,Version=v5.0 references.

Also the error message is in polish language, can I set it to English without changing language for the whole desktop ?

**Comment by svick** [comment]
@waldimen That's the error you get when you try to compile a .Net 5.0 project using an older SDK. Did you follow [the guide](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2-install-instructions.md#install-using-snap) and ran `sudo snap alias dotnet-sdk.dotnet dotnet`?

**Comment by waldimen** [comment]
@svick I resolved it, it was caused by variable MSBuildSDKsPath set to net 3.1

**Comment by tanekim77** [comment]
![image](https://user-images.githubusercontent.com/20119808/98020368-ec4ffc00-1dd0-11eb-961c-1e0208efab8f.png)
Debugging using .net RC5 => blazorwebassembly causes the following error

**Comment by Trolldemorted** [comment]
>@reinux can you try deleting this file: C:\ProgramData\Package Cache{35392F9B-1C64-368F-BBE1-CDFD0B381B94}v5.0.0.0\AspNetCoreSharedFramework-x64.msi

>Then run repair again

I did that, but I am still unable to select .net5 in VS, and if I edit the .csproj VS refuses to build (MSB3644). Running dotnet build directly works like a charm, though. I am running VS 16.7.7, and the installer did not nag me about pending updates so far.

**Comment by mairaw** [comment]
@Trolldemorted .NET 5 RC 2 requires Visual Studio 2019 (v16.8, Preview 4)

https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/5545
