### ISSUE TITLE
I could not run .Net in my computer

### ISSUE THREAD

**Issue by shalaan66** [dotnet/core#5351]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What error message are you getting @shalaan66?

**Comment by shalaan66** [comment]
Please, find attached the Screenshot

**Comment by mairaw** [comment]
GitHub doesn't allow you to add screenshot via e-mail replies. When you can, can you come to the web UI to attach the screenshot?

**Comment by shalaan66** [comment]
<img width="566" alt="Screenshot 2020-10-14 at 00 38 11" src="https://user-images.githubusercontent.com/72838711/95927354-64209d00-0db6-11eb-865a-bec64519bb3f.png">

**Comment by mairaw** [comment]
So, the command is printing the options as expected. Have you tried creating the app already?

**Comment by shalaan66** [comment]
Not yet

**Comment by GlenCooper** [comment]
Wish my failed install got that far.  Looks like your dotnet install is working.

**Comment by mairaw** [comment]
What's the problem you're having @GlenCooper? Do you want to open a new issue with the details so we can sort that out?
What OS, error message, etc?

And @shalaan66 let me know if you managed to continue the tutorial since your installation seems good from what I can see.

**Comment by GlenCooper** [comment]
@mairaw https://github.com/dotnet/core/issues/5400
