### ISSUE TITLE
aspnetcore-targeting-pack-3.1 File Unexpected Size

### ISSUE THREAD

**Issue by pkts94** [dotnet/core#5353]
# File has unexpected size 

Trying to install ubuntu 18.04 aspnetcore-targeting-pack-3.1.  Receiving file size mismatch:
File has unexpected size (951058 != 950516). Mirror sync in progress?

Checking https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/pool/main/a/aspnetcore-targeting-pack-3.1/ shows the file size as 950516.  Where's the 951058 pulling from?  

Issue has been occurring for the past 7 hours.

**Comment by dagood** [comment]
Why are you using the `microsoft-ubuntu-xenial-prod` repo? I haven't heard of this one before. (Xenial isn't Ubuntu 18.04, either.)

Have you tried following the directions at https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#1804- ?

**Comment by dagood** [comment]
Ah, it looks like `microsoft-ubuntu-xenial-prod` was used in old instructions, sorry about that. Interesting that it seems to be getting recent updates.

@rbhanda @leecow @NikolaMilosavljevic can you see if this can be fixed up?

**Comment by rbhanda** [comment]
https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/a/aspnetcore-targeting-pack-3.1/ has the latest bits. I am curious how `microsoft-ubuntu-xenial-prod` got updated in the first place as we do nothing there to my knowledge. I will look into how we can update it.

**Comment by pkts94** [comment]
Sorry - this is all somewhat new to me.  In looking at our build logs I see a "Failed to fetch .....aspnetcore-targeting-pack-3.1/aspnetcore-targeting-pack-3.1.8.deb  File has unexpected size (951058 != 950516). Mirror sync in progress?".  When I googled the `aspnetcore-targeting-pack-3.1.8.deb` I ended up (incorrectly I think) at the xenial-prod link above.  

I'll have to touch base with my support group in the morning as our builds don't hit the MS package endpoints directly; we hit an internal proxy that's then routed over there.  So I'll have to troubleshoot with them to see where we're really pulling from.

Apologies for the wild goose chase.

**Comment by pkts94** [comment]
Can someone check the metadata for the aspnetcore-targeting-pack-3.1.8.deb?  Is it possible the metadata is specifying file size of 951058 when the actual file size is 950516?

**Comment by dagood** [comment]
Why are you linking to that NuGet package? I don't see the connection to the Debian package repos or `aspnetcore-targeting-pack-3.1`.

If you have your own mirror set up, yes, you should take a look at that, and consider changing it to use the currently documented repos at https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#1804- , which are working. (Or at least confirm where your repo mirror is mirroring from.)

In the meantime, rbhanda said earlier he'd look into `microsoft-ubuntu-xenial-prod` to see if we can fix that (assuming it's broken).

**Comment by pkts94** [comment]
That xenial was a red herring - ignore it.  Here's what I was told from our end:

this would be the direct path, without mirror:
https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/a/aspnetcore-targeting-pack-3.1/aspnetcore-targeting-pack-3.1.8.deb
 
now, this file isn't the problem necessarily. ubuntu uses the InRelease file from:
https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/
 
and the Packages* and Release files from:
https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/
 
these files (among others, depending on what you're trying to pull down/do) contain the hashes and index of all content within the repository (for faster lookup of packages without having to try random http urls to find a package), in addition to being able to use it to compare hashes against what should be in there vs what is. **_the problem is that what the metadata files have vs what the actual file is, is different_**. I'm showing our versions are the exact same as what's in the remote.

**Comment by dagood** [comment]
Thanks for finding the info. I'm not able to reproduce this from here (the install works fine for me from a fresh 18.04 Docker container), but a cause for this problem in the past has been the underlying service corrupting its globally distributed mirrors.

Can you run `wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/a/aspnetcore-targeting-pack-3.1/aspnetcore-targeting-pack-3.1.8.deb` or something similar and show the full output? We unfortunately need the IP address of the mirror you're hitting to file an issue with the team responsible for these repos:

```
Resolving packages.microsoft.com (packages.microsoft.com)... 40.117.131.251
Connecting to packages.microsoft.com (packages.microsoft.com)|40.117.131.251|:443... connected.
```

**Comment by pkts94** [comment]
I cannot b/c I don't have access to the environment that's actually building the packages.  I could ask our support team if they can do it.  However, someone just informed me our builds seem to be working again now and I was able to confirm.  So, not sure where the issue was, but it appears to have resolved.  So maybe whatever mirror we're hitting got the updates?
Thanks for the feedback/help on this - good experience for my first github issue report.  :)

**Comment by dagood** [comment]
Ah, cool, no problem. 🙂 I assumed you had confirmed the deb/Release-file mismatch without the proxy/mirror and could try out the command on that machine. In any case, should have a clearer path to gather the diagnostic info next time, if this pops up again.
