### ISSUE TITLE
.NET 5 RC2 / Oracle.ManagedDataAccess.Core cannot initialize

### ISSUE THREAD

**Issue by tyler-shuhnicki** [dotnet/core#5356]
Hi there,

Our team has been migrating our application from .NET framework 4.8 to .NET 5. We started when .NET 5 was on preview 4. Recently, only one of our team members upgraded to RC1, and now RC2. We use Oracle.ManagedDataAccess.Core (v.2.19.90) to connect Dapper to our Oracle databases, and both of these release candidates have thrown the error posted below. The application continues to work for team members who are still on preview 4. Is this a bug, or is there a dependency we are missing? 

Thanks for your time!

InnerException = {"The type initializer for 'Oracle.ManagedDataAccess.Types.TimeStamp' threw an exception."} System.Private.CoreLib at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor) at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache) at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) at System.Activator.CreateInstance[T]() at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, String instanceName, List`1 switchFailedInstNames) at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch) at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch) at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria) at Oracle.ManagedDataAccess.Client.OracleConnection.Open() at Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() in /_/Dapper/SqlMapper.cs:line 1079 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 721 at General.Data.AccountData.LoadAccount(RequestAccount request) in D:\GitLab\cfconnect-api-core\General\Data\AccountData.cs:line 333

**Comment by carlossanlop** [comment]
Can you please reach out to the owners of `Oracle.ManagedDataAccess` first? This is not an API we own. They can then reach out to us if necessary.
