### ISSUE TITLE
504 Gateway error after creating AKS cluster 

### ISSUE THREAD

**Issue by rajeev-roy** [dotnet/core#5358]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I have followed the tutorial to deploy docker container to AKS, deployment succeed but I am unable to access deployed service . it's showing 504 Gateway timeout error while accessing service using external IP address. 
i am not sure how to resolve this issue. 

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@shirhatti can you please help?

**Comment by carlossanlop** [comment]
Ping @shirhatti

**Comment by carlossanlop** [comment]
Ping @shirhatti

**Comment by carlossanlop** [comment]
Ping @shirhatti again, or @nishanil

**Comment by sughosneo** [comment]
Hi @rajeev-roy, thank you for reaching out.

This sort of behavior can be seen if there is any issue in DNS resolution within the node in the AKS cluster.
I could imagine there could be something wrong in the cluster itself.

Could you please validate the following things ?

1) If you could validate if the AKS node is healthy.
2) If you could validate if the DNS for that cluster is healthy. You can also check if the DNS endpoints are exposed by using the command `kubectl get ep kube-dns --namespace=kube-system`
3) If you notice that the `mymicroservice` pod is running fine, then you may want to validate if the `cluster ip` and `LoadBalancer Ingress` ip are assigned to the service by using the command `kubectl describe svc mymicroservice`.
4) If all the deployment goes fine, you should be able to see the below output when you run the command `kubectl logs <pod_name>`

```powershell
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
```
Hope this helps !

**Comment by Onkar1277** [comment]
I am still facing this issue, External IP when hit from Postman it is showing <title>504 Gateway Timeout</title>
Can someone please help
