### ISSUE TITLE
How to get info for specific culture formats when <InvariantGlobalization> true is used?

### ISSUE THREAD

**Issue by borjabolcina** [dotnet/core#5359]
# How to get info for specific culture formats when set InvariantGlobalization true is used?

.NET 5.0.100-preview.7.20366.6 WINDOWS
We need to parse dates and numbers from input strings that along specify the culture to parse in.
But we are running the API with <InvariantGlobalization> true  setting and we always get Invariant format example MM/dd/yyyy
for CultureInfo.CreateSpecificCulture("de-DE").DateTimeFormat.ShortDatePattern

**Comment by svick** [comment]
As I understand it, you can't. The Globalization Invariant Mode is meant for the cases where you don't need to do culture-dependent operations. But you do, so you should disable that mode. For more details, have a look at [the documentation](https://github.com/dotnet/runtime/blob/master/docs/design/features/globalization-invariant-mode.md).

**Comment by carlossanlop** [comment]
@GrabYourPitchforks can you please help with this?

**Comment by GrabYourPitchforks** [comment]
@svick's earlier comment is correct and provides links to more info. The solution is to disable the invariant globalization mode if the app requires access to culture-specific behavior. I'll close this issue for now, but if I missed something please feel free to reopen. Thanks!
