### ISSUE TITLE
Theme: Meeting Developer Expectations

### ISSUE THREAD

**Issue by bradygaster** [dotnet/core#5366]
.NET 5 introduced more incremental improvements for applications to realize faster startup times and smaller exe sizes using single file and app trimming. As we look ahead on how we continue to make .NET a compelling platform for developers to build their modern apps on, we will continue to evolve the platform by building on top of what .NET 5 has brought to the ecosystem.

Epics under this theme:

- [x] https://github.com/dotnet/runtime/issues/43538
  - [x] https://github.com/dotnet/runtimelab/issues/248
  - [x] https://github.com/dotnet/runtime/issues/43543
- [x] #5395
- [x] https://github.com/dotnet/machinelearning-modelbuilder/issues/1053
- [ ] Enable APIs to be discoverable and integrated in the Power Platform
  - [x] #5367
- [x] https://github.com/dotnet/runtime/issues/44314
- [x] https://github.com/dotnet/runtime/issues/43767
- [x] https://github.com/dotnet/runtime/issues/43545
- [x] https://github.com/dotnet/runtime/issues/43616
- [x] https://github.com/dotnet/runtime/issues/43620
- [ ] https://github.com/dotnet/efcore/issues/24107
- [x] https://github.com/dotnet/runtime/issues/48253

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.

**Comment by senmedine630-glitch** [comment]
> `Duplicate of #9930 `
