### ISSUE TITLE
Grpc.net working with Xamarin.Forms

### ISSUE THREAD

**Issue by speed2048** [dotnet/core#5376]
I am developing a project that uses xamarin.forms with grpc on a Mac ( getting ready for .net Maui ) and I am getting  exception errors (DebugException="System.MissingMethodException: Method not found: System.Buffers.IBufferWriter`1<byte> Grpc.Core.SerializationContext.GetBufferWriter()). 

So I did some digging and found out that Xamarin.Forms does not work with grpc.net at this time.

https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1

My question is. When will xf support grpc.net? I do not see this on the roadmap I admit I could be looking in the wrong place.

Also is Xamarin.Forms going to support the .net core Framework?

Also wondering if I should provide more details with this issue?

**Comment by carlossanlop** [comment]
Can you please open an issue in the grpc repo?

**Comment by Jacko1394** [comment]
I'm getting this error now, MissingMethod exceptions are ruining Xamarin.Forms for iOS.
I get the same thing with System.Text.Json now...

**Comment by valentasm1** [comment]
@Jacko1394 did you found any workarounds?
