### ISSUE TITLE
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the  spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by svdevendra** [dotnet/core#5379]
I encountered issue when tried to run "dotnet new console" command.

**System details:**
Operating System:  Windows 10 Pro, Version: 1909: , 64 bit operating system.

**Error details are given below.**

At line:1 char:1
+ dotnet new console
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : **CommandNotFoundException**

![dotnet_issue](https://user-images.githubusercontent.com/52192530/96330179-e3d99080-1070-11eb-9d58-b4add6748037.PNG)

I checked path and it seems it's already added. 
Find the screenshot below,

![image](https://user-images.githubusercontent.com/52192530/96359190-6162d680-112d-11eb-8e65-020471b56a09.png)

Thanks in advance for your help.

**Comment by vitek-karas** [comment]
Installing just VS Code does not install .NET Core. Please go to https://dotnet.microsoft.com/download and install the .NET Core SDK and then it should work.

If you did install .NET Core SDK already, then your PATH should point to the install location (typically in C:\Program Files\dotnet).

**Comment by mairaw** [comment]
Let us know if you have or not the SDK already installed.

**Comment by svdevendra** [comment]
Hi @vitek-karas and @mairaw 
Thank you so much for your reply. My issue resolved after adding the path into the environment variable.

**Comment by vitek-karas** [comment]
Glad to hear it works for you.

**Comment by JayNg17x** [comment]
@vitek-karas  Hi, I run the `dotnet run` fews seconds ago, it worked but for the second run, it does not work anymore even that I installed dotnet in C:\Program Files\dotnet .

**Comment by vitek-karas** [comment]
@JayNg17x Please open a new issue and provide more detail, things like:
* Which OS, version of .NET
* What commands did you run
* What is the error you get

**Comment by mj061203** [comment]
Hi, I'm facing the same problem, and I'm trying to understand how to fix it.
I couldn't seem to know how to 'check' or 'add' to a 'path'.
Such as 'then your PATH should point to the install location (typically in C:\Program Files\dotnet)' this. I don't know how to do it :(
Can anyone tell me how to do these 'Path' things?

**Comment by mairaw** [comment]
Here’s an explanation of adding to the path:
https://github.com/dotnet/sdk/issues/7428#issuecomment-270423072

**Comment by mj061203** [comment]
Wow! Never thought there would be an answer in just a few hours!
Thanks a lot

**Comment by AbanoubIbrahim98** [comment]
ctAttribute' attribute [E:\ITI\Projects\Day7Lab\Day7Lab.csproj]
E:\ITI\Projects\Day7Lab\obj\Debug\net5.0\Day7Lab.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [E:\ITI\Projects\Day7Lab\Day7Lab.csproj]
E:\ITI\Projects\Day7Lab\obj\Debug\net5.0\Day7Lab.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [E:\ITI\Projects\Day7Lab\Day7Lab.csproj]
E:\ITI\Projects\Day7Lab\Program.cs(5,11): error CS0101: The namespace 'Day7Lab' already contains a definition for 'Program' [E:\ITI\Projects\Day7Lab\Day7Lab.csproj]
E:\ITI\Projects\Day7Lab\Program.cs(7,21): error CS0111: Type 'Program' already defines a member called 'Main' with the same parameter types [E:\ITI\Projects\Day7Lab\Day7Lab.csproj]

The build failed. Fix the build errors and run again.

**Comment by vitek-karas** [comment]
@AbanoubIbrahim98 - in general please create a new issue if the failure doesn't look like the one described in this issue.

As for your problem - please try to delete the `obj` and `bin` folders and try again. Also - can you can that your project has only one `Main` method in it (it also seems that the `Program` class is duplicated).

**Comment by mairaw** [comment]
We don't monitor closed issues, so it is better to open a new one and link an existing if you think it's the similar issue @RyanPatton8.
