### ISSUE TITLE
Error when running Docker build

### ISSUE THREAD

**Issue by batcoder619** [dotnet/core#5380]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Facing below error when running the docker build command. I am running the command within the project folder where the ".dockerfile" resides

`unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\<path>\MyMicroservice\Dockerfile: The system cannot find the file specified.`

**Comment by carlossanlop** [comment]
@shirhatti can you please take a look?

**Comment by carlossanlop** [comment]
Ping @shirhatti

**Comment by carlossanlop** [comment]
Ping @shirhatti again, or @nishanil

**Comment by sughosneo** [comment]
Hi @batcoder619, thank you for reaching out.

From the error message, it seems like docker is not able to find the correct docker file while building the image.

Could you please verify that the `Dockerfile` mentioned in this step [Add a DockerFile](https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file) has been created properly ?
You need to make sure that the name of the file is as `Dockerfile` and not Dockerfile.txt or some other name. In Windows OS you can verify that in a few ways. For e.g : 
1) By enabling the `File name extensions` checkbox. 
2) Or by opening the `myMicroservice` directory in an IDE for e.g `VSCode`

Hope this helps !
