### ISSUE TITLE
I ran into an error failed to dial gRPC: unable to upgrade to h2c, received 500 

### ISSUE THREAD

**Issue by defney** [dotnet/core#5382]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by defney** [comment]
I ran into errors failed to dial gRPC: unable to upgrade to h2c, received 500

**Comment by carlossanlop** [comment]
@shirhatti can you please take a look?

**Comment by carlossanlop** [comment]
Ping @shirhatti

**Comment by mairaw** [comment]
Perhaps @nishanil can help

**Comment by nishanil** [comment]
@carlossanlop I haven't seen this error before. Based on the internet search results it looks like it happens due to the mismatch of the target OS specified in docker image and the container OS. Can you try resetting Docker and creating a new project? I will also verify these steps from my side.

**Comment by carlossanlop** [comment]
@nishanil The request is for @defney, who reported the issue.

**Comment by nishanil** [comment]
Oops! Thanks.

**Comment by carlossanlop** [comment]
@defney I'll mark this issue as `needs-more-info`. It will get auto-closed if we don't get a reply in the next week.

**Comment by nishanil** [comment]
We tested this - all the steps work fine on macOS with .NET 5 SDKs installed.

**Comment by defney** [comment]
Thank you for your help !
