### ISSUE TITLE
deploy to azure is not working. no where got the dashboard 

### ISSUE THREAD

**Issue by dhananjaypverma** [dotnet/core#5392]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@nishanil @shirhatti can you help with this issue?

**Comment by shirhatti** [comment]
@dhananjaypverma 

> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
