### ISSUE TITLE
How to construct X509Certificate2 from pem contents?

### ISSUE THREAD

**Issue by agniveshadhikari** [dotnet/core#5393]
I have a pem file contents as a string:
```
-----BEGIN PRIVATE KEY-----
MII[...multiple lines here...]Rt
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MII[...multiple lines here...]As=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MII[...multiple lines here...]LUm
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MII[...multiple lines here...]jXZA=
-----END CERTIFICATE-----
```
I want to construct an X509Certificate2 object from this. How do I do this?

### General
Right now my code looks like this
```
string cert = @"cert string contains the whole cert from above";
var certInByteArr = Encoding.UTF8.GetBytes(cert);
var x5c = new X509Certificate2(certInByteArr);
var cac = new ClientAssertionCertificate(this.dnsClientConfig.ClientId, x5c);
var serviceCredentials = ApplicationTokenProvider
          .LoginSilentWithCertificateAsync(
               this.dnsClientConfig.TenantId,
               cac)
          .GetAwaiter()
          .GetResult();
```
However, in this form, I get this exception `Cannot find the requested object` on the third line in the above snippet.

I dug around a little bit and it seems some people had luck with stripping the `-----END CERTIFICATE-----` lines, and that makes it pass thru line 3, but fails on the last line with `No valid private RSA key found for X509Certificate2.`

**Comment by bartonjs** [comment]
The .NET 5 method `X509Certificate2.CreateFromPemFile` will find the first certificate and match it to the private key (if the key matches something other than the first certificate the method will fail). Or the .NET 5 method `X509Certificate2Collection.ImportFromPemFile` will read all of the certificates, and disregard the key object.  To do both, you probably want

```C#
string data = File.ReadAllText(path);
X509Certificate2Collection coll = new X509Certificate2Coll();
coll.ImportFromPem(data);
RSA key = RSA.Create();
key.ImportFromPem(data);
coll[0] = coll[0].CopyWithPrivateKey(key);
```

Though if you just want one or the other of the behaviors then you'd just use that method as-is.  For older versions of .NET (.NET Core 3.1 or older, .NET Framework, or .NET Standard 2.x) you'd need to do a lot of data splitting; or convert that to a PFX with OpenSSL or other utilities.

**Comment by scalablecory** [comment]
Looks like Jeremy answered; closing.

**Comment by BethanyZhou** [comment]
Will ImportFromPem() be supported in dotnet standard?
