### ISSUE TITLE
.NET Core 1.1.1 Windows Server Hosting bundle

### ISSUE THREAD

**Issue by Skoucail** [dotnet/core#540]
Where can i find the .NET Core 1.1.1 Windows Server Hosting bundle?
Before the release of 1.1.1 i found the .NET Core 1.1.0 Windows Server Hosting bundle on the download page of .NET Core.
But now it seems to be gone.

**Comment by Petermarcu** [comment]
@DamianEdwards @muratg

**Comment by muratg** [comment]
The download link is being updated (could be up already).

The download link is: https://go.microsoft.com/fwlink/?linkid=844461

**Comment by Skoucail** [comment]
Thank you!
I now see that [https://www.microsoft.com/net/download/core#/runtime](https://www.microsoft.com/net/download/core#/runtime) is updated also.
