### ISSUE TITLE
.net core 3.1 doesnt work 32bit Linux OS

### ISSUE THREAD

**Issue by ahoirg** [dotnet/core#5403]
I installed Lubuntu 16.04 LTS 32bit on virtual machine. Package manager installs are only supported on the x64 architecture. Therefore, i followed the manual installation steps.

I downloaded the version for ARM32 since it is on a 32 bit operating system. Calling "dotnet" from the console failed.
bash: /home/ali/dotnet/dotnet: cannot execute binary file: Exec format error

Is there any way I can use .net core 3.1 on 32 bit Linux machines?

note: It works when I compile it in 64 bit in x64 ubuntu 20.04 LTS . but a dll in the project has a 32 bit dependency. I need to compile it on x86.

**Comment by carlossanlop** [comment]
There is no 32 bit installer for Linux
https://dotnet.microsoft.com/download/dotnet-core/3.1
https://dotnet.microsoft.com/download/dotnet/5.0

32 bit is not the same as ARM32, those are two different architectures.

@dagood what is the recommended thing to do here? I suspect it is to instead install Lubuntu in 64 bit.

**Comment by dagood** [comment]
I don't know of a recommendation here, unfortunately--`linux-x86` is simply not supported. I think https://github.com/dotnet/runtime/issues/7335 is the central issue tracking adding it in the future.

(If it helps clear things up: ARM32 is a weirdly Microsoft-specific way to say `armhf`. Linux distros tend to say `armhf` or just ARM when they're talking about that processor architecture.)
