### ISSUE TITLE
Visual Studio Preview 4 (7.0 Build 1566) has broken link for downloading .NET core

### ISSUE THREAD

**Issue by vboctor** [dotnet/core#541]
Just installed Visual Studio Preview 4 on my Mac and attempted to create a .NET Core Web API project, it detected that I don't have .NET core installed and directed me to Github link below to download it which is broken:
https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md

I know this is not strictly a .NET core issue, but I'm not sure about the repository to report this into.  If you let me know, I will report it accordingly.

**Comment by Petermarcu** [comment]
Here is the correct link. It got moved to archives: https://github.com/dotnet/core/blob/master/release-notes/download-archives/rc4-download.md

@leecow @richlander we should probably not move the docs so people referring to them aren't broken.

**Comment by richlander** [comment]
Interesting. I'll ask if they are using a forward link or what. Either way, we'll get a fix in place today.

**Comment by blackdwarf** [comment]
We will fix this with returning the RC4 page but we will point users to install RTW bits to keep them current.

**Comment by richlander** [comment]
Fixed by #544
