### ISSUE TITLE
The commands does not work

### ISSUE THREAD

**Issue by danaeellaprogramiz** [dotnet/core#5412]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: Windows

The commands in the command prompt does not work

**Comment by zeracorona** [comment]
I'm really interested in learning ASP, so I would love answers to this issue

**Comment by zeracorona** [comment]
I can't find the myWebApp directory

**Comment by vitek-karas** [comment]
Can you please provide a bit more detail?
* What version of .NET Core you installed (you can run `dotnet --info` to get that information)
* What is the exact error you get
* Do you follow the example or did you do something slightly different

**Comment by zeracorona** [comment]
I want to learn C++ instead :)

**Comment by vitek-karas** [comment]
Hope you like it. We'll be happy to see you whenever you decide to give .NET a second try.

**Comment by mairaw** [comment]
You have to run the commands one after the other @zeracorona. I've been thinking if we should split them into two separate sections to make it easier. Would that make it easier to understand?

**Comment by zeracorona** [comment]
Version 3.1.403, seems kinda low

The error I get is in step 2 of the ASP.NET introduction to installing, the files are created but I can't find Pages/cshtml

**Comment by mairaw** [comment]
You can see at https://dotnet.microsoft.com/download/dotnet-core/3.1 that 3.1.403 is the latest SDK version, so that's correct.

They should be inside the myWebApp folder. Did you cd into the directory? You mentioned in the other issue that you installed Visual Studio, you could open the project in VS to better see it.

**Comment by zeracorona** [comment]
Yes

**Comment by zeracorona** [comment]
The voices stopped when I quit mailing registrator.vast@polisen.se

**Comment by zeracorona** [comment]
But I still want to learn ASP.NET

**Comment by mairaw** [comment]
Have you given the tutorial a new try?
