### ISSUE TITLE
C++ questions

### ISSUE THREAD

**Issue by zeracorona** [dotnet/core#5414]
I don't know which IDE to install. Is it Visual Studio I should use? And what are the options I should set in the beginning? Also, I hear a voice from my computer that says "nothingness is surrounded", I think it's kinda annoyin.

**Comment by zeracorona** [comment]
I closed my Facebook account, there just seem to be a lot of problems with it. I have a psychosis, but I love programming. The voices has been really weird today :(

**Comment by zeracorona** [comment]
I have installed Visual Studio Community 2019, but the voices talk so weird since I began reading the book

**Comment by zeracorona** [comment]
I have a lot of problems with police, programming my game. I also want to make a text editor with C++ support, a calendar and a browser. The voice I talked about earlier I hear all the time when I call to mom, and it's since I began studying C++

**Comment by mairaw** [comment]
We can't help with the voices but hopefully this tutorial on the C++ docs will help you to get started: https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=vs-2019

**Comment by danaeellaprogramiz** [comment]
I think they are teddybears. It freaks me out

**Comment by danaeellaprogramiz** [comment]
It's working

**Comment by danaeellaprogramiz** [comment]
&*

**Comment by danaeellaprogramiz** [comment]
You don't need to create window oriented programs, because the game will pause automatically

**Comment by danaeellaprogramiz** [comment]
It was the Police
