### ISSUE TITLE
Support installing dotnet runtime and SDK using package manager on non-x64 systems.

### ISSUE THREAD

**Issue by misaz** [dotnet/core#5421]
Is possible make dotnet-runtime and dotnet-sdk packages (deb) availaible for non-x64 architectures like arm64 and armhf?

According to https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian (or the same page for Ubuntu), there are restriction

> Package manager installs are only supported on the x64 architecture. Other architectures, such as ARM, must manually install the .NET Core SDK or .NET Core Runtime. For more information, see the manually install section.

What is reason for that restriction? Is possible to make dotnet availabile for install on non-x64 systems? Repositories looks like they supports other platforms but dotnet packages is not present for that platforms. Installing using package manager has lot of advantages including simplified updates which brings more security to hosting dotnet apps.

**Comment by dagood** [comment]
It is possible, it's just a matter of development time now. ARM64 is tracked by https://github.com/dotnet/runtime/issues/3298, and armhf ("ARM32") is tracked by https://github.com/dotnet/runtime/issues/3263.

**Comment by dagood** [comment]
Closing: this is covered by https://github.com/dotnet/runtime/issues/3298 / https://github.com/dotnet/runtime/issues/3263.
