### ISSUE TITLE
.NET developers can use common Cloud Native OSS

### ISSUE THREAD

**Issue by glennc** [dotnet/core#5424]
There are many OSS libraries that commonly appear when building modern Cloud Native applications. The [CNCF Landscape](https://landscape.cncf.io/) is one view of that, but other libraries are commonly used as well.

As part of making sure that .NET is seen as suitable for Cloud Native applications we should spend some amount of effort in making sure that when a .NET developer reaches for common libraries/services that they work with .NET. E.g. if they want to use RabbitMQ their should be a good .NET library for that.

We can't go and build .NET libraries for every project in the CNCF landscape or put support for every technology in .NET, but we can support open source libraries with contributions and invest in enabling technologies that make sense to go into .NET itself for those libraries to work on.

There's no consistent approach to doing these engagements, we have several different recent models such as contributing to the Postgres driver, implementing and shipping gRPC support, and our Apache Spark work. Each of these are different models of enabling .NET customers to be successful with a set of technologies that they may want to use today.

For this epic we want to identify a couple of areas that we think .NET can have impact on, through contributions to libraries or innovation in the underlying platform, and also help define more guidance for which patterns work best when trying to support libraries/technologies this way. We have a couple of candidate libraries and are talking to some customers now to make sure that there are good opportunities while we work out the best ways to engage.

* [x] gRPC services can be called from .NET Framework #5713
* [ ] .NET developers have a first class experience working with GraphQL #5852

**Comment by danmosemsft** [comment]
Next step here is on @glennc who will continue customer development/research. 

@ajcvickers do you want to create a User Story for any research into possible GraphQL work, and parent under this?

**Comment by danmosemsft** [comment]
ping @ajcvickers

**Comment by atrauzzi** [comment]
I'd love to see libraries in the Apache ActiveMQ Artemis (NMS) and CouchDB ecosystems supported/created in whatever ways make sense.

For CouchDB, I wrote a `System.Reactive` chain that listens to the change stream that could probably be turned into a library.

**Comment by danmosemsft** [comment]
@atrauzzi just saw your note. @glennc , thoughts about those?

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
