### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by dradendavis1** [dotnet/core#5431]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am trying to run dotnet on my MacBook Pro running Mac OS 10.15.7 and every time I have tried to create a project my laptop throws this error: System.UnauthorizedAccessException: Access to the path '/Users/Dendar/.dotnet/3.1.403.toolpath.sentinel' is denied.
If you could provide a possible solution to this issue it would be greatly appreciated. 
Thank you!

**Comment by carlossanlop** [comment]
What was the command you executed that caused this error to show up?

**Comment by carlossanlop** [comment]
No replies in 9 days. Closing.
