### ISSUE TITLE
.NET apps in containers have good startup and steady-state performance

### ISSUE THREAD

**Issue by glennc** [dotnet/core#5438]
Take advantage of the immutable nature of container images and target modern hardware to produce more optimized assets.

- Take advantage of modern SIMD instructions (AVX2 instead of SSE2) in ready-to-run images. We are comfortable with this because all containers are likely to be running on newer hardware and OS versions.
- Use our Version Bubbles ideas to allow ready-to-run images to be more optimized, and as such more fragile to change. But the change is managed by the immutability of images.

 **Current Stories**
- [ ] Build composite image with Fx + asp.net Assemblies. 
- [ ] Enable composite Fx images for published container images

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
