### ISSUE TITLE
Reduce runtime container size

### ISSUE THREAD

**Issue by glennc** [dotnet/core#5439]
- In previous versions of .NET we introduced globalization invariant mode, and turned it on in our Alpine containers. This mode removes a large native dependency (ICU) but changes some behaviors that might be surprising to some customers. We want to find a plan to improve invariant mode enough that we are comfortable making it the default, removing the large dependency from our images.
WASM has similar problems with the ICU dependency so work here would be equally applicable to that effort.
Extra context:
	- https://github.com/dotnet/runtime/issues/43774
	- https://github.com/dotnet/dotnet-docker/issues/1877

- Spend more time on training for partial ready-to-run (we removed 10mb from the .NET layer in 3.0, we could look at more of the stack).

- [ ] [Improve invariant mode](https://github.com/dotnet/runtime/issues/43774)

**Comment by marek-safar** [comment]
We have done the work on slimming ICU in 5.0 version and got fully functional version (https://github.com/dotnet/icu) down to about 3 MB compressed

**Comment by richlander** [comment]
Nice. We'll have to figure out how to use that in containers.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
