### ISSUE TITLE
Developers can easily parse release metadata for .NET Core updates for use in their deployment process

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5440]
The goal of this one is the make available the source for an api that will parse releases.json.  The format of that file can be confusing to read for customers and we've gotten many requests for guidance or tooling around it so customers could build their own tooling based on the values in that file.

- [x] Update based on feedback from api review
- [x] Final review and signoff with PM team
- [x] Run compliance scanning on source and fix issues
- [x] Make source available
- [x] Build and publish NuGet package

**Comment by terrajobst** [comment]
@joeloff I assume we're done with API reviews, right?

**Comment by joeloff** [comment]
@terrajobst For now I think so. I'm working on getting it added to the deployment repo. @KathleenDollard and I chatted. We'll lit it simmer for a few months and look at the feedback and then do more revisions/changes, probably in the new year.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/deployment-tools/pull/75

**Comment by terrajobst** [comment]
@joeloff should I schedule another API review?

**Comment by joeloff** [comment]
@terrajobst  Now that it's merged, wouldn't we want to get the preview package out first and get feedback from some customers before doing another API review?

**Comment by joeloff** [comment]
Once we have feedback I think we can schedule another round.
