### ISSUE TITLE
Developers can easily build locally from source all or part of .NET 6  on Windows, Linux, and Mac

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5450]

**Comment by dagood** [comment]
I'm trying to understand a little better what this story tracks.
* My initial interpretation of "on the desktop" is shaky. I believe the intent is along the lines of "on my machine".
* "The product" from the source-build point of view is the .NET SDK, but this isn't clear IMO unless you already know what source-build is.
* Is the focus on "easily"? Or are there more significant gaps in the experience that the story's actually about?

Here's an alternative title with my current understanding of the story, does this sound right?
**As a developer, I can easily build .NET from source on my machine: either the whole .NET SDK or specific parts of it**

**Comment by jamshedd** [comment]
@dagood, you're right I did mean on my machine when I said on my desktop :) Desktop can mean different things in different contexts so machine is less ambiguous.

**Comment by danmosemsft** [comment]
@jamshedd is this Linux only? If so that should be in the title. (Obviously all OS can be built from source, but it's Linux that we're making it easiest)

**Comment by jamshedd** [comment]
> @jamshedd is this Linux only? If so that should be in the title. (Obviously all OS can be built from source, but it's Linux that we're making it easiest)

I updated the title to make it obvious this is all 3.

**Comment by danmosemsft** [comment]
@jamshedd could you say more here about the motivation for Windows? The motivation for Linux is clear -- so that distros can build from source.

**Comment by dagood** [comment]
I'd also like to hear more about this. (Note that dotnet/source-build [doesn't support Windows](https://github.com/dotnet/source-build/issues/1190).)

Side note: Homebrew now builds .NET Core for macOS using dotnet/source-build thanks to community effort, and historically dotnet/source-build has supported running on macOS. So there's also motivation there, like Linux.

**Comment by Fasjeit** [comment]
+1 for desktop builds.

We have a full fork for dotnet [runtime 3.1](https://github.com/CryptoPro/corefx) with custom crypto. The plans are to ship this modified runtime and SDK to customers to build apps with native GOST algorithms (Russian crypto) support in dotnet (including ASP.NET, X509, CMS, XML, etc.) both in Windows, unix, and mac. Many people already happy using it.

And even building runtime in 3.1 is real pain thanks to netstandard. It would be nice to have a fully offline build in 6.0, where we can build full dotnet runtime and SDK from modified sources without messing with CI pipelines and tons of API Compat issues.

**Comment by dleeapho** [comment]
Given the effort cost of higher pri epics and the diffuseness of the motivation for this epic we don't believe this work fits in the 6.0 timeframe. 

@Fasjeit desktop and fully offline builds for Linux and macOS is supported in 5.0 and we will maintain it for 6.0. If you encounter specific issues please file them at https://github.com/dotnet/source-build/issues

**Comment by mairaw** [comment]
Should this be moved to Cut then @dleeapho?
