### ISSUE TITLE
found error on dotnet run command

### ISSUE THREAD

**Issue by rupeshmca7** [dotnet/core#5458]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\rupess\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code 1. [D:\Learning\BLAZOR\myFirstBlazorApp\myFirstBlazorApp.csproj]

**Comment by carlossanlop** [comment]
What command did you run that caused this error?
