### ISSUE TITLE
Unable to create Blazor App

### ISSUE THREAD

**Issue by msingh1dm698** [dotnet/core#5459]
Hi,

I am trying to create a server-side blazor app but it shows me blank screen and create button is disable too. 

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

![image](https://user-images.githubusercontent.com/73603261/97462479-258df500-1915-11eb-8cb1-42d466b5c32f.png)

**Comment by carlossanlop** [comment]
@Pilchie do you know what could cause this?

**Comment by Pilchie** [comment]
@vijayrkn @phenning

**Comment by vijayrkn** [comment]
If you temporarily rename this folder `%userprofile%\.templateengine` & re-start VS does it work?
