### ISSUE TITLE
SDK Download Archive Links Identical for 1.0.4 and 1.1.1

### ISSUE THREAD

**Issue by tompazourek** [dotnet/core#546]
The SDK download links for .NET Core 1.0.4 and .NET Core 1.1.1 are identical:

https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md

Links from both of the pages point to .NET Core 1.1.1.

Am I missing something? Is there some way how to download SDK installer for .NET Core 1.0.4?

**Comment by Petermarcu** [comment]
I believe there is just one SDK installer and you get 1.0.4 and 1.1.1 runtimes in it. There is something going on with the naming of the sdk file though.

@livarcocc , Is the filename of the RTM SDK that is branded as 1.0.1 actually 1.1.1?

**Comment by tompazourek** [comment]
Ok, thanks for the explanation.

Are there any download links for **tooling for VS2015** or is it all VS2017-only now? I unfortunately cannot update to VS2017 at the moment.

I cannot get VS2015 to work with a .NET Core project based on project.json (even a brand new project from a VS template), I always get this:

![capture](https://cloud.githubusercontent.com/assets/370699/23824980/806a2fa2-0681-11e7-8bfd-0a3e06dc224c.PNG)

Tried uninstalling everything and installing the SDKs from the links above, so now I am looking for older versions, because I remember this used to work.

**Comment by Petermarcu** [comment]
All the updates are VS 2017 and a lot of improvements were made there. I'm not familiar with that error.

**Comment by richlander** [comment]
I assume that there were significant changes that are breaking to VS 2015.

There should be a help page that specifies how to lock your project back to the preview2 tooling. Where is that @blackdwarf @mairaw ?

**Comment by tompazourek** [comment]
@richlander Yeah, you're right, it seems that it's the preview2 tooling that I'm looking for (AFAIK the move from project.json to msbuild was in preview3). Is it still possible to get it somewhere?

**Comment by richlander** [comment]
> Is it still possible to get it somewhere?

Sorry, I'm slow. What does "it" refer to?

**Comment by blackdwarf** [comment]
I believe @tompazourek means the Preview 2 bits. The whole archive is @ https://github.com/dotnet/core/tree/master/release-notes/download-archives.

**Comment by daschult** [comment]
@blackdwarf What about the installers that contain the MSBuild DotNet Core targets and props files for Visual Studio 2015? I can't seem to find anything that installs those files.

**Comment by richlander** [comment]
@daschult - There isn't such a configuration. We didn't enable the msbuild tools to work with .NET Core. This is documented here: https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/
