### ISSUE TITLE
User Story: .NET 6 developers building desktop applications need to package and update their applications for multiple platform targets

### ISSUE THREAD

**Issue by rconard** [dotnet/core#5460]
### Summary

Desktop applications on .NET 6 introduce additional OS platforms to support with the inclusion of Xamarin and Blazor Desktop in the runtime. This will require a packaging pipeline that supports all Xamarin 6 and Blazor Desktop desktop targets.

>Note: This is a proposed experience for .NET 6 and not yet committed.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
