### ISSUE TITLE
User Story: .NET 6 desktop application developers need to manage their build pipelines, versions, telemetry, and channels for their releases

### ISSUE THREAD

**Issue by rconard** [dotnet/core#5461]
### Summary

It is difficult to manage the release of installers and updaters across platforms, architectures, and channels. Many large development teams have built cloud systems to manage their releases, and this service would provide these same tools to all desktop developers.

>Note: This is a proposed experience for .NET 6 and not yet committed.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
