### ISSUE TITLE
CompSci 100-200 level classes can be taught entirely in .NET Notebooks in VS Code

### ISSUE THREAD

**Issue by shanselman** [dotnet/core#5466]
### Summary

Anyone can get started in CompSci 100-200 level classes taught entirely in .NET Notebooks in VS Code ‘fast’. An entire curriculum for early in career could be taught entirely with notebooks. e.g.  data structures, algorithms, language features.

### User Stories

User Stories under this Epic:

- [ ] [.NET Interactive supports the basic requirements for notebook-based learning tasks](https://github.com/dotnet/core/issues/5843).
- [ ] [.NET Interactive notebooks are usable in flexible environments including GitHub Codespaces](https://github.com/dotnet/core/issues/5844)

**Comment by jarz** [comment]
It'd be probably an epic in itself, but building an open-source CS curriculum might be what it takes to get people interested in .NET over Java (my first CS language), JS, or Python.

I'm gonna sound like a total marketer goon but... what's the elevator pitch for C# over Java or Python?

**Comment by snow-jallen** [comment]
As someone who teaches an introductory computer science class in c# I would absolutely love this.

**Comment by ivdiazsa** [comment]
I had my programming introductory course on Python, and then used Java the most. When I tried C# and .NET, I didn't go back to Java. This would definitely be great.

**Comment by YourSenseiCreeper** [comment]
I would love to see it as Jupyter Notebook for example.

**Comment by viv718918** [comment]
[]()

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
