### ISSUE TITLE
Necessary tools are easy to find, install, and immediately get started.

### ISSUE THREAD

**Issue by shanselman** [dotnet/core#5467]
### Summary

A .NET Education pack offers one installer to get everything a professor or student needs. e.g. VS Code, .NET SDK, Git, C# Extension, Notebooks.

### User Stories

User Stories under this Epic:

- [ ] [Title of the linked User Story](hyperlink to the User Story issue).

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
