### ISSUE TITLE
Next-step tasks are easy to discover and intuitive 

### ISSUE THREAD

**Issue by shanselman** [dotnet/core#5470]
### Summary

Using libraries and other .NET ecosystem components is easy and discoverable relative to their starting point.

### User Stories

User Stories under this Epic:

- [ ] [Title of the linked User Story](hyperlink to the User Story issue).

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
