### ISSUE TITLE
New developers can easily deploy their apps/libraries

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5471]
### Summary

When a new developer has finished building their first app and wants to deploy it, the choices available to them are easy to understand and their app can be augmented to support the environment they wish to deploy to. This includes things like easily adding a file for CI/CD (e.g., GitHub actions), files to make their project better to collaborate with (e.g. `.gitignore`, `.editorconfig`), etc.

### User Stories

User Stories under this Epic:

- [ ] [New .NET developers can easily add second-level files to their codebases](https://github.com/dotnet/core/issues/5479).

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
