### ISSUE TITLE
Conceptual Computer Science learning in .NET is more interactive and easier to acquire.

### ISSUE THREAD

**Issue by shanselman** [dotnet/core#5474]
### Summary

Documentation for CompSci can delivered as ipynb notebooks on GitHub. One can git clone a whole semester and begin immediately.

### User Stories

User Stories under this Epic:

- [ ] [Title of the linked User Story](hyperlink to the User Story issue).

**Comment by cartermp** [comment]
Note for posterity: this is very similar to https://github.com/dotnet/core/issues/5466 but is still different:

* 5466 is focused specifically on coursework
* This item implies a broader way to learn about .NET, even if something like .NET Interactive powers the more interactive learning experience

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
