### ISSUE TITLE
Passing arguments by running self-contained app on Debian

### ISSUE THREAD

**Issue by hahyes** [dotnet/core#5475]
Hi there,

I built self-contained .NET Core console app for Debian 10 (using `dotnet build` command), but I wanna pass some arguments for Main method, `./myapp --value` like this. 

Sadly, in `string[] args` there is nothing, no matter what I will write after path of executive file. On Windows 10 program has all string values I'm writing after executive file.

I'm using .NET Core 3.1 (latest version) and Debian 10 with XFDE environment (with xfde4-terminal). Did someone had problem like that? How should I pass arguments on terminal in Debian?

**Comment by hahyes** [comment]
I did some investigation, trying to reproduce problem but I can't. On new test project passing arguments works fine. Problem still occurs on my old one. 

I forgot to mention, but project mentioned in yesterday post was earlier converted from .NET Framework 4.8. Maybe that's the issue here?

**Comment by mairaw** [comment]
How are you running the project? Is there a small repro for this?
