### ISSUE TITLE
dotnet quit unexpectedly

### ISSUE THREAD

**Issue by sgronblo** [dotnet/core#5476]
# Issue Title

Runtime exception in my own program incorrectly identified as a dotnet crash

# General

If I run a simple program that throws any runtime exception using `dotnet run`. It will be detected as a dotnet crash and a dialog saying "dotnet quit unexpectedly" giving me the offer to send a crash report to Apple.

dotnet --version: 3.1.403
OS: macOS Catalina 10.15.7

Simple reproduction:

```
open System

[<EntryPoint>]
let main argv =
    raise (Exception("testing"))
    0 // return an integer exit code
```

Running it through `dotnet run`

![image](https://user-images.githubusercontent.com/320449/97595590-2cb52000-1a47-11eb-8ed3-c4d7f73e7735.png)

I am now forced to click "ignore" every time I run into an exception when developing a real program.

**Comment by mairaw** [comment]
Can you check this @cartermp?

**Comment by cartermp** [comment]
This one isn't specific to F#, as you'll see the same behavior in a C# app that just throws an exception. Might be good to start with the cli/sdk cc @marcpopMSFT

**Comment by marcpopMSFT** [comment]
@wli3 is this specific to how dotnet run works on mac?

**Comment by wli3** [comment]
Nothing special on mac or dotnet run. We spin up a process to run the application just built. I'll ask runtime team to see if this is expected.

**Comment by wli3** [comment]
Issue moved to [dotnet/runtime #44567](https://github.com/dotnet/runtime/issues/44567) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mairaw** [comment]
FYI @wli3 we can transfer issues natively between same-org repos using the GitHub UI.
