### ISSUE TITLE
New users aren't confused by having to think about .NET Framework and non-.NET Framework when installing VS

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5477]
### Summary

New users using VS Community shouldn't be faced with the problem of having to understand what .NET Framework and .NET 6 are. They should only have to know about .NET.

### Details

Setup authoring in the VS Installer for .NET workloads should emphasize ".NET", not ".NET Framework" and ".NET 6". Some options:

* Mark all .NET Framework components as "legacy" when using VS Community
* Hide .NET Framework components from the list of dependencies in the installer when using VS Community
* Significantly trim the list of components for .NET workloads when using VS Community. For example, trimming this list down, even if some of the components are actually installed:
![image](https://user-images.githubusercontent.com/6309070/104383852-5e397580-54e5-11eb-9061-e438c7ff95f2.png)

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
