### ISSUE TITLE
New users on VS Community will only be able to create modern .NET projects by default

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5478]
### Summary

As a new user using **VS Community**, I want to only create modern .NET project types so that I'm not confused by the difference between .NET Core and .NET Framework.

As a new user using VS Community who must use .NET Framework, I want to still be able to load any older project types if that is required of me.

### Specifics

Reiteration: This is for **VS Community only**. VS Pro, Enterprise, etc. would remain the same as today.

This means that when I go to create a new project (either from the installer or via File > New Project) I will only see .NET 6-based project templates for a kind of template.

A more concrete example of changes:

* Console --> 1 template, no .NET Framework (-1 template)
* Library --> 7 templates: library, razor library, winforms/wpf library variants. No .NET Framework. (-4 templates)
* Desktop --> 6 templates: WinForms, Winforms Control/Class library, WPF, WPF Console/Class Library templates. No .NET Framework, no Shared Projects. (-9 templates)
* Web --> 12 templates: ASP.NET Core-based, various variants. Could get cleaned up. No .NET Framework, no Web Forms. (-2 templates)

This would reduce the number of shown templates, when you have Web and Desktop workloads installed, by 16. There may be a separate effort to reduce the total number of web and desktop templates to streamline it a little more.

**Comment by dasMulli** [comment]
As mentioned in https://github.com/dotnet/core/issues/5469#issuecomment-761800418, I believe that creation of .NET Framework projects should be possible in all SKUs, though maybe not by default (workload or optional feature in VS installer)

**Comment by pjmlp** [comment]
So UWP wouldn't be considered for modern .NET, am I reading future roadmap plans?

**Comment by ederbond** [comment]
Make it optional.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
