### ISSUE TITLE
New developers can create a Simple .NET App from the command line

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5481]
### Summary

Describe a specific user story experience. Use the format:

As a [new users], I want to [create my first app that is just source code] so that [I can focus on code and not be overwhelmed by the notion of project files].

**Comment by teo-tsirpanis** [comment]
Related: dotnet/sdk#12328.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
