### ISSUE TITLE
Modern C# is emphasized for newcomers

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5482]
### Summary

Describe a specific user story experience. Use the format:

As a [new developer], I want to [ensure I'm learning the latest and greatest ways to write C# code] so that [I am familiar with how to write "modern" .NET code].

**Comment by jzabroski** [comment]
This is great. An inspiring book early in my career was Accelerated C++, which dove straight into STL without bothering explaining a lot of technical things. It was the book recommended to me by the guy who wrote Dinkum Libraries.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
