### ISSUE TITLE
C# Simple Apps have a natural grow-up path when developers want to expand their app's capabilities

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5483]
### Summary

Describe a specific user story experience. Use the format:

As a [user who is familiar with C# after starting out], I want to ["grow" my Simple App without starting over] so that [I can add more capabilities like packages, projects, etc. without having to copy/paste and delete my work].”

**Comment by cinsola** [comment]
... How? Million dollar question

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
