### ISSUE TITLE
~ >>> dotnet                                                                                                                                     [127]              zsh: correct 'dotnet' to 'done' [nyae]? n zsh: command not found: dotnet ~ >>>                                                                                                                                            [127]

### ISSUE THREAD

**Issue by Linuxer-master** [dotnet/core#5487]
Problem encountered on https://dotnet.microsoft.com/learn/languages/fsharp-hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment]
From this bit, it sounds like you weren't able to successfully install .NET:

> `zsh: command not found: dotnet`

Can you paste the logs and exact install commands you used, so we can help figure out what went wrong?
