### ISSUE TITLE
A customer can give hints about what to optimize for, relatively simple configuration i.e. single broad switch

### ISSUE THREAD

**Issue by richlander** [dotnet/core#5488]
.NET offers both [high-level](https://docs.microsoft.com/dotnet/core/run-time-config/garbage-collector#workstation-vs-server) and [low-level](https://twitter.com/Nick_Craver/status/1189685719897460739) configuration knobs, but nothing in-between or that describes intent. In the cloud world, people are typically either concerned about controlling cost or maximizing performance. We aspire for .NET defaults (#5485) to be some mid-point between the two, with a bias to maximizing performance.

We should consider configuration knobs that enables developers, or deployment/cloud admins, to configure applications in terms of intent. It's possible we will enable setting multiple intents, ordered in terms of priority. The following is a first approximation of what those "intents" might be, with a mix of orientation on resources and outcomes:

- [Resource usage] Prioritize low memory usage.
- [Resource usage] Prioritize low CPU usage.
- [Outcome] Prioritize low latency.
- [Outcome] Prioritize high response rate.
- [Outcome] Enable handling bursty traffic.

More research needs to be done here. At present, this ideas (while seemingly attractive) are bordering on theory.

**Comment by mairaw** [comment]
This one seems to be missing some labels @richlander

**Comment by carlossanlop** [comment]
@terrajobst @richlander is this an Epic or a User Story?

**Comment by terrajobst** [comment]
> @terrajobst @richlander is this an Epic or a User Story?

Based on structure I'd assume user-story. @richlander, feel free to change this.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
