### ISSUE TITLE
Network compile for IoT

### ISSUE THREAD

**Issue by Lewiscowles1986** [dotnet/core#549]
It would be really great to be able to cross-compile for IoT & low-power devices using the network. Any machine reachable by standard SSH has the ability to run commands and to send files. It's obviously a power-user feature but it'd be nice to be able to register another local PC as a build box, have a process to confirm viability

* Does it have SSH
* Can we access that using credentials supplied
* Run a script to check tools are available
* tarball the source folders
* transfer via scp
* untar on remote machine
* build
* package build artifacts
* send build artifacts back to IoT device

**Comment by iAmjad1** [comment]
So the workload is on the network, does that add overhead.

**Comment by Lewiscowles1986** [comment]
I'd imagine it needs some overhead compared with single-machine development. It would'nt need an enterprise back-end though if that is what you are asking, only need a central VCS or single SCM active branch snapshot (much smaller than a repo), a bootstrap script for deps, and to transfer back the binaries (conveniently ignoring communications traffic overhead).

**Comment by richlander** [comment]
I'm not sure what you are asking for. This works today.

See: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by Petermarcu** [comment]
I think the ask here is to be able do work on the IoT device, send the files up to a server to do the builds, and then get the resulting app back on the IoT device. This could totally be built on top of git or another DVCS where you can push your changes to the server, have that server build when it gets changes, and then have something on the device looking for new outputs and acquiring them. Its an interesting idea for making the dev workflow on slow devices that either can't run the sdk or if they do, its unusable. The other alternative is to just do the dev work on the more powerful machine and automate the push to the device. @raffaeler has a solution for this published here: https://github.com/raffaeler/deploytool

**Comment by Petermarcu** [comment]
This is more of a developer experience/CLI feature request. I'm going to move this to the CLI repo.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #7778](https://github.com/dotnet/cli/issues/7778) via [**ZenHub**](https://www.zenhub.com/)
