### ISSUE TITLE
Developers can use PGO collection tools to collect PGO data from apps in a variety of scenarios

### ISSUE THREAD

**Issue by richlander** [dotnet/core#5492]
Apps are developed and deployed in a wider spectrum of environments today:

- For dev: local machine (the traditional option), [GitHub codespaces](https://github.com/features/codespaces), CI/CD servers.
- For deployment: on-prem servers (the traditional option), cloud VMs, and cloud container-orchestrators.

It is important that PGO data collection tools work on all of them (in the fullness of time). We will use the following staging for PGO collection tools:

- Local machine collection (including VMs).
- Container orchestrators, using [dotnet-monitor](https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor)

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
