### ISSUE TITLE
Developers can progressively optimize their .NET apps at runtime, using dynamic PGO data

### ISSUE THREAD

**Issue by richlander** [dotnet/core#5494]
[Tiered compilation](https://devblogs.microsoft.com/dotnet/tiered-compilation-preview-in-net-core-2-1/) is an important codegen related feature in the runtime. It has two primary challenges: it bases re-jit decisions on a single metric, and always generates the same tier 1 code.

Using PGO data, we can improve tiered compilation in the following ways:

- Target methods for re-jitting that are more likely to provide a significant benefit.
- Optimize methods in terms of actual application conditions (for example, take advantage of the observation that the else block of an if statement is never or rarely taken).
- Optimize methods aggressively for an upside win with an acceptable fallback in case the bet doesn't pay off, such as de-virtualizing method calls (and potentially inlining those methods).

There is significant prior art in this space. We need to do the following to ensure we have a good offering that is attractive for modern apps.

- Provide significant value, above and beyond static PGO.
- Limit runtime cost to a metric that users can accept.
- Develop a metric for predictable execution. For example, dynamic PGO should never be a contributor to P95 latency issues.

**Comment by JulieLeeMSFT** [comment]
dotnet/runtime/issues/43618 summarizes Dynamic PGO work plan.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
