### ISSUE TITLE
certificate issues on centos 7

### ISSUE THREAD

**Issue by snap254** [dotnet/core#5496]
# Issue Title

Getting Certificate issues trying to install dotnet core 3.1 to centos 7

# General

```
url: (60) Peer's Certificate has expired.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
error: skipping https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm - transfer failed
```

**Comment by carlossanlop** [comment]
@dagood can you help with this?

**Comment by dagood** [comment]
@snap254 can you please link the instructions you're following and the exact commands you ran?
I just want to make sure we don't make any assumptions. 🙂

The installation instructions at https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos#centos-7- work fine for me right now in a fresh environment.

/cc @NikolaMilosavljevic @leecow

**Comment by snap254** [comment]
We found a good reason for the issue in the end: the clocks on the machines were not accurate with global time. After working on getting them synchronized fully, the certificate problems went away.
