### ISSUE TITLE
 C:\Users\une04>cd myWebApp O sistema não pode encontrar o camin

### ISSUE THREAD

**Issue by Dhyones-silva** [dotnet/core#5497]
Bom dia, eu tive esse pequeno problema

C:\Users\une04>cd myWebApp
O sistema não pode encontrar o caminho especificado.

C:\Users\une04>cd
C:\Users\une04

C:\Users\une04>cd myWebApp
O sistema não pode encontrar o caminho especificado.

C:\Users\une04>

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Dhyones-silva** [comment]
> Bom dia, eu tive esse pequeno problema
> 
> C: \ Users \ une04> cd myWebApp
> O sistema não pode encontrar o caminho especificado.
> 
> C: \ Usuários \ une04> cd
> C: \ Usuários \ une04
> 
> C: \ Users \ une04> cd myWebApp
> O sistema não pode encontrar o caminho especificado.
> 
> C: \ Usuários \ une04>
> 
> Problema encontrado em https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
> Sistema operacional: windows
> 
> Forneça detalhes sobre o problema que você está enfrentando. Inclua a versão do seu sistema operacional, mensagem de erro exata, amostra de código e qualquer outra coisa que seja relevante.

olá, problema resolvido

**Comment by mairaw** [comment]
Que bom. Fechando o issue então.
