### ISSUE TITLE
Unable to create a new project

### ISSUE THREAD

**Issue by jesmanto** [dotnet/core#5499]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I typed `dotnet new console -o myApp` and I got an error that says 
**Template "Console Application" could not be created.**
**Access to the path 'C:\Windows\system32\myApp' is denied.**
I use a Windows 8

**Comment by jesmanto** [comment]
I changed the title of the issue

**Comment by mairaw** [comment]
Please navigate to a different directory. You won’t have permissions to create a project under c:\windows\system32.

Let us know if that worked!

**Comment by jesmanto** [comment]
It worked. Thanks

**Comment by mairaw** [comment]
Awesome!
