### ISSUE TITLE
Run of 'dotnet restore' fails with sample application created by 'dotnet new'

### ISSUE THREAD

**Issue by rcabreu** [dotnet/core#55]
After creating a new app by running ```dotnet new``` and consequently running ```dotnet restore```, the console spits out this error:

info : Running restore with 16 concurrent jobs.
info : Restoring packages for /home/kojak_/test/project.json...
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 779ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.platform/index.json 851ms

System: Linux Mint 17.2 Rafaela
$ uname -a
Linux kBox 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by blackdwarf** [comment]
@rcabreu I cannot repro this on Linux Mint 17.3 using the Preview 2 bits of the tooling that were release on 27th of June. I think the problem where was missing feed configuration in the NuGet.config file. 

With the above, I will close this issue. If it still persists for you, please open an issue on the dotnet/cli repo so we can investigate. Thanks!
