### ISSUE TITLE
No templates matched the input template name: blazorserver.

### ISSUE THREAD

**Issue by gargleblaster** [dotnet/core#5501]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I got this in red:
No templates matched the input template name: blazorserver.

I would think there's some kind of update command, but --help doesn't show anything like that.

**Comment by mairaw** [comment]
Can you type `dotnet --info` and let us know what is the information returned?
