### ISSUE TITLE
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?

### ISSUE THREAD

**Issue by Loamashitu** [dotnet/core#5507]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=duy41073vf2hudollzynkenau&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by Loamashitu** [comment]
I use Docker version 19.03.13, build 4484c46d9d

**Comment by mairaw** [comment]
Can you help here @nishanil @shirhatti?

**Comment by nishanil** [comment]
It looks like Docker isn't running. Can you verify it by running by the following command `docker run hello-world` on a command prompt?  If not, try the suggestions mentioned [here](https://stackoverflow.com/questions/52946810/error-during-connect-get-http-2f2f-2fpipe2fdocker-engine-v1-38-info).

**Comment by carlossanlop** [comment]
No response in 9 days. Closing.
