### ISSUE TITLE
dotnet" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.

### ISSUE THREAD

**Issue by antonio-jose20** [dotnet/core#5513]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by antonio-jose20** [comment]
dotnet" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by carlossanlop** [comment]
Hola @antonio-jose20 , te aseguraste de cerrar y reabrir las ventanas de línea de comando que tuvieras abiertas, después de que instalaste el SDK? Si no las cierras, las variables de entorno no se van a actualizar.

**Comment by mibxs** [comment]
Hi. Someone fixed it? ¿Alguien arregló este problema?

**Comment by carlossanlop** [comment]
This is not a bug. It means you installed dotnet, but had a command line open before it got installed. You need to close and reopen the command line window so the environment variables get updated. 

No es un bug de dotnet. Este error significa que instalaste dotnet, pero tenías una ventana de línea de comandos abierta cuando estabas instalándolo. Necesitas cerrar y reabrir la ventana de línea de comandos para que las variables de entorno se actualicen.
