### ISSUE TITLE
COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder701316953\obj\Docker\publish: The system cannot find the path specified.

### ISSUE THREAD

**Issue by fengyinyong** [dotnet/core#5515]
I created a asp.netmvc  project via vs2019,  it is based on .netframework4.8,and I add a dockerfile . But I can build a image successful.

my project:
![image](https://user-images.githubusercontent.com/68414905/97965344-2df29e00-1df5-11eb-8879-4709729d74f7.png)

the error message when run docker build:
![image](https://user-images.githubusercontent.com/68414905/97965414-48c51280-1df5-11eb-85fa-92c466f06eea.png)

Is there anyone can help me? I've working on it for a whole day and have no idea.

**Comment by unseriousdk** [comment]
Try to move "Dockerfile" to where your .sln and .dockerignore files are. Also build docker from this location.

**Comment by fengyinyong** [comment]
@unseriousdk
I put the three file in the same location, and build the image,But it still does not work.
![image](https://user-images.githubusercontent.com/68414905/98209268-98cce200-1f79-11eb-9813-7b2a7731654e.png)

**Comment by carlossanlop** [comment]
@MichaelSimons any chance you could help with this issue?

**Comment by vsnghpg** [comment]
Put your source folder/file in the same location as your Dockerfile. This fixed my problem.

**Comment by kumarz** [comment]
I am running into the same problem in spite of having them all in the same folder but I don't see the publish folder inside obj/Docker
