### ISSUE TITLE
.Net can't run

### ISSUE THREAD

**Issue by SotoMonge** [dotnet/core#5520]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: macos

**_The build failed. Fix the build errors and run again._**

dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by mairaw** [comment]
What is your version of macOS?
