### ISSUE TITLE
api-ms-win-crt-runtime|1-1-0.dll

### ISSUE THREAD

**Issue by lalkakaal** [dotnet/core#5521]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Which version of Windows do you have? In order to complete the tutorial, you need to install the dependencies too if you’re on an older version of Windows 

https://docs.microsoft.com/dotnet/core/install/windows?tabs=netcore31#additional-deps
