### ISSUE TITLE
Error with 'WORKDIR' command

### ISSUE THREAD

**Issue by ralfhempfling** [dotnet/core#5523]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows 10 pro

Docker version 19.03.13, build 4484c46d9d

when executing 'docker build -t  mymicroservice .' I get the following error (see also image below):

hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)

![docker_build_issue](https://user-images.githubusercontent.com/842948/98239508-eb2be580-1f1c-11eb-88df-03e5d059a809.jpg)

**Comment by mairaw** [comment]
Can you help here @nishanil @shirhatti?

**Comment by nishanil** [comment]
It looks like an issue with the configured custom storage location in Docker. I am not sure. Can you try the suggestions made in this thread https://github.com/moby/moby/issues/36831 ?

**Comment by carlossanlop** [comment]
No response in 9 days. Closing.
