### ISSUE TITLE
error or issue running dotnet cmd

### ISSUE THREAD

**Issue by Malphabetagama** [dotnet/core#5524]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

command prompt message
*******
>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
                                                                   ************

**Comment by mairaw** [comment]
That looks like the expected result. Have you continued the tutorial @Malphabetagama?

**Comment by Malphabetagama** [comment]
yes I have begun Thanks a Bunch mairaw 👍

**Comment by mairaw** [comment]
Awesome! I plan to add the expected output to make the tutorial a bit more clear. Let us know if you run into other issues.
