### ISSUE TITLE
There seem to be no Program.cs in my installed Visual Basic. What to do?

### ISSUE THREAD

**Issue by janmionez** [dotnet/core#5525]
Problem encountered on https://dotnet.micro
![Capture](https://user-images.githubusercontent.com/74028980/98313510-f95a2e80-200e-11eb-8000-bdda5f74de66.PNG)
soft.com/learn/dotnet/hello-world-tutorial/create#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

There seem to be no Program.cs in my installed Visual Basic. What to do?

**Comment by mairaw** [comment]
You should have another directory under the one you're currently in called myApp (the -o option creates a new subfolder). You can use any kind of code editor or text editor to open the Program.cs to continue the tutorial.

Please let us know if that helps.

**Comment by mairaw** [comment]
Also, this tutorial will use C# instead of Visual Basic. Let us know if you need any help finding some Visual Basic tutorials.
