### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by idhamrpg** [dotnet/core#5527]
The program can't start because api-msi-win-crt-runtime-|1-1-0.dll is issing form your computer. Try reinstalling the program to fix this problem.

**Comment by mairaw** [comment]
It’s not clear when you get this problem but it seems this is related to missing dependencies:
https://docs.microsoft.com/dotnet/core/install/windows?tabs=netcore31#additional-deps

If that’s not it, give us more information like OS, version, etc. so we can help you.
