### ISSUE TITLE
General RasPi Readme question...

### ISSUE THREAD

**Issue by SalvorinFex** [dotnet/core#553]
Hi there,  
I am a bit confused about the option of running "ubuntu 14.04 or 16.04" on a Pi.
The link in those words points to the general download page on the RasPi.org site and the only 'ubuntu' there is 'Core' and ubuntu MATE.  So, is the 'readme' referring to ubuntu core and MATE or one or the other.
I didn't think 'Core' has had version numbers, like the standard distro.  

Will the .NET core run on ubuntu MATE?

**Comment by Petermarcu** [comment]
Yes, use it on Ubuntu MATE. :) Which 'readme' are you looking at?

**Comment by SalvorinFex** [comment]
https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by Petermarcu** [comment]
Yeah, go with Ubuntu MATE 16.04 if you are just starting from scratch.

**Comment by SalvorinFex** [comment]
Alright, thanks!

**Comment by RamblingGeekUK** [comment]
I have built the app on PC, I have it copied over.. but how do I install dotnet core on to raspberry pi, I have pulled the build down but it won't run when I enter ./helloworld ?  dotnet runs but it doesn't feel installed?

**Comment by Tealons** [comment]
@Petermarcu Do you have a ETA for when we can do this on a raspberry pi: https://www.hanselman.com/blog/PublishingAnASPNETCoreWebsiteToACheapLinuxVMHost.aspx

**Comment by Petermarcu** [comment]
@RamblingGeekUK, If you follow the instructions, you shouldn't need to install dotnet core on the pi. It is in the folder with your app.

**Comment by Petermarcu** [comment]
@Tealons, which part of that do you want to do? In my quick read of it, I've done everything there except putting ASP.NET Core behing nginx.

**Comment by Tealons** [comment]
@Petermarcu : When I create a new MVC project via the cli, change the project file as described and upload the output to my Pi, i get the following error:

`Error: assembly specified in the dependencies manifest was not found -- package: 'Microsoft.Data.Edm', version: '5.8.2', path: 'lib/netstandard1.1/de/Microsoft.Data.Edm.resources.dll'`

**Comment by Petermarcu** [comment]
I believe thats a bug that was recently fixed: https://github.com/dotnet/core-setup/issues/2157 . It should be fixed if you get the very latest SDK from here: https://github.com/dotnet/cli

**Comment by Tealons** [comment]
One bug down, 99 to go :)

When publishing for ubuntu.16.04-arm I get the following error:

C:\Users\Martin & Monique\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview1-24647\build\netcoreapp2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(26,5): error MSB3073: The command "dotnet exec --runtimeconfig "C:\Users\Martin & Monique\Documents\Visual Studio 2017\Projects\test3\bin\Debug\netcoreapp2.0\ubuntu.16.04-arm\Projects.runtimeconfig.json" --depsfile "C:\Users\Martin & Monique\Documents\Visual Studio 2017\Projects\test3\bin\Debug\netcoreapp2.0\ubuntu.16.04-arm\Projects.deps.json" "C:\Users\Martin & Monique\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview1-24647\build\netcoreapp2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Debug\netcoreapp2.0\ubuntu.16.04-arm\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450749. [C:\Users\Martin & Monique\Documents\Visual Studio 2017\Projects\test3\Projects.csproj]

**Comment by Petermarcu** [comment]
@DamianEdwards , any thoughts? @Tealons can you share what you get when you run `dotnet --version`?

**Comment by Tealons** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/7141563/25537604/78b0aa28-2c3f-11e7-8129-1bcf057dd93a.PNG)

**Comment by Petermarcu** [comment]
@eerhardt , this sounds like the bug you were telling me about with the mixed back/forward slask problem. Do you think this could be related? Can you point to that issue if so?

**Comment by eerhardt** [comment]
This is a different issue.  The issue @Tealons is hitting is https://github.com/aspnet/MvcPrecompilation/issues/103

You can't cross-publish from a Windows machine to a Linux app with the default ASP.NET template.

To workaround this set:

```
<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

in your .csproj.

**Comment by Tealons** [comment]
Got it working on a Raspberry Pi 3 with Raspbian! Unbuntu has some problems with the Raspberry Pi 3: 
https://stackoverflow.com/questions/41353092/ubuntu-freezes-after-boot-starting-kernel-raspberry-pi-3
https://bugs.launchpad.net/ubuntu/+source/linux-raspi2/+bug/1652270

I created a new mvc project with the cli using the latest preview2 version. I followed the intructions at https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md and got it working. I will create a pull request with more details about the specific steps later on. 

Still need to figure out how to expose the dotnet server to the internet, but that will be a matter of figuring out the correct configuration. 

Thanks for the help!

**Comment by Tealons** [comment]
Simply adding .UseUrls("http://*:8088") did the trick:

```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseUrls("http://*:8088")
                .Build();
    }

```

**Comment by Petermarcu** [comment]
Awesome!
