### ISSUE TITLE
Blazor Server App could not be created

### ISSUE THREAD

**Issue by kingbasiir** [dotnet/core#5533]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your 

OS: Window 10 PRO

I want to run this: 

`dotnet new blazorserver -o BlazorApp --no-https`

ERROR:
Template "Blazor Server App" could not be created.
Access to the path 'C:\Windows\System32\BlazorApp' is denied.

![image](https://user-images.githubusercontent.com/20393342/98489107-8b5c7400-2267-11eb-94d5-a9cc87d16ea0.png)

**Comment by mairaw** [comment]
@kingbasiir make sure you're not running this command on the `C:\windows\system32` path. Change your directory and that should work as expected.
