### ISSUE TITLE
VS 2015 Tooling Downloads Gone?

### ISSUE THREAD

**Issue by benrr101** [dotnet/core#554]
I'm currently trying to find a download for the VS2015 Tooling for .NET Core. Since the big push to get people onto VS2017, it has been incredibly difficult to find downloads for older versions of the SDK, but it has been doable. However, the .NET VS 2015 Tooling appears to have disappeared off the face of the earth. I was only able to install it by finding a copy of the installer on my co-worker's machine. 

My team is not yet ready to upgrade to VS2017 and the associated csproj formatted projects in .NET core 1.1. Please make sure that when deploying new links you don't make it impossible to find the links for older releases.

**Comment by xsoul** [comment]
i having problem compiling my existing vs2015 project (.net core preview2) after i upgrade nuget package with latest .net core 1.1.1

Do you have same problem?

**Comment by richlander** [comment]
Good point. @leecow - can you add the VS 2015 tooling links to the release notes? We should also add a link to the download table on the .NET Core marketing site.

We didn't hide the links on purpose - definitely an oversight.

@xsoul - That can happen. Can you share your project.json file (say in a gist?). You can mail it to dotnet@microsoft.com if it is private.

**Comment by xsoul** [comment]
I reverted all my changes so i only have this copy of project.json which was have no problem for compiling before i upgrade to .net core 1.1.1

`{
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Serilog.Sinks.RollingFile": "2.2.0",
    "Serilog.Sinks.Literate": "2.0.0",
    "Serilog": "2.1.0",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Newtonsoft.Json": "9.0.1",
    "Serilog.Extensions.Logging": "1.1.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "System.Linq.Dynamic": "1.0.7",
    "NReco.PdfGenerator": "1.1.12",
    "RestSharp": "105.2.3"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
   },

  "frameworks": {
    "net461": {
      "dependencies": {
        "Biota.Auth": {
          "target": "project"
        },
        "Biota.Models": {
          "target": "project"
        },
        "Biota.QRGenerator": {
          "target": "project"
        },
        "Biota.Storage": {
          "target": "project"
        }     },
      "frameworkAssemblies": {
        "System.Configuration": "4.0.0.0"
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

after upgrade, those microsoft related assemblies should be version 1.1.1, and here is my global.json

`{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
`

**Comment by richlander** [comment]
What would be most useful is seeing the version that has an issue. I suggest you open a separate issue. This is different from the original issue.

**Comment by MaximRouiller** [comment]
Please ensure that supports with VS2015 is kept for a bit, please? I know of a client who just recently upgraded to 2015. Won't update to 2017 for at least 2 years as far as I know.

**Comment by richlander** [comment]
We'll add the link back later today and post the URL here.

**Comment by MaximRouiller** [comment]
Since .NET Core is mostly driven with command line tooling, can we expect VS2015 tooling to be supported for longer than previous .NET Tooling?

**Comment by leecow** [comment]
Hey folks, link to the Preview 2 tooling have been added to the current [1.0.4](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.4.md) / [1.1.1](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.1.md) release notes as well as the [Download Archive](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) index page. Will be updating [dot.net](https://dot.net) shortly. 

Sorry for unintentional omission!

/cc @preetikr

**Comment by benrr101** [comment]
Thanks very much for updating the download archive page!

**Comment by richlander** [comment]
See: https://www.microsoft.com/net/download/core
