### ISSUE TITLE
cant do anything

### ISSUE THREAD

**Issue by levytenthije** [dotnet/core#5544]
i get this and i dont know to fix it i have it installed It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you run the command `dotnet --info` and let us know the output? It seems that you only downloaded the runtime but not the SDK. Did you use the download button from the page? It should download the right product.
