### ISSUE TITLE
.NET Core November 2020 Update - 3.1.10

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5546]
[3.1.10 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.10/3.1.10.md)
[3.1.10 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-November-2020/)

Please report any issues you find with 3.1.10, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Status of availability of SDK on Linux feeds: 

| Distro | 3.1.10|  
|--|--|
| Ubuntu 16.04   | ✅  | 
| Ubuntu 18.04| ✅  | 
| Ubuntu 20.04 | ✅  | 
| Ubuntu 20.10 | ✅  | 
| Centos 7   | ✅  | 
| Debian 9    | ✅  | 
| Debian 10   | ✅  | 
| Fedora 32   | ✅  | 
| Fedora 33  | ✅  | 
| OpenSUSE 15 | ✅  | 
| SLES 12     | ✅ | 
| SLES15   | ✅  | 

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

-----
### Known Issues
If there are any issues with the November 2020 release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [x] [Unable to install .NET 5 RC2, .NET Core 2.1, .NET Core 3.1 on Ubuntu 20.10](https://github.com/dotnet/core/issues/5352) - This is resolved for 5.0 and 3.1. See https://github.com/dotnet/core/issues/5017#issuecomment-729208437 for more details

**Comment by yyjdelete** [comment]
#5569
The download page of netcore 3.1 from https://dotnet.microsoft.com/download is linked to net5.0

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/5838
