### ISSUE TITLE
Ubuntu 20.10 Linux package repo doesn't work: "E: The repository 'https://packages.microsoft.com/ubuntu/20.10/prod xenial Release' does not have a Release file."

### ISSUE THREAD

**Issue by dagood** [dotnet/core#5549]
Repro command using Docker:

```
docker run -it --rm ubuntu:20.10 bash -c '
  set -x
  apt update; apt install -y sudo wget
  wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  sudo dpkg -i packages-microsoft-prod.deb
  apt update'
```

This gives me:

```
...
+ apt update
Hit:1 http://security.ubuntu.com/ubuntu groovy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu groovy InRelease
Ign:3 https://packages.microsoft.com/ubuntu/20.10/prod xenial InRelease
Err:4 https://packages.microsoft.com/ubuntu/20.10/prod xenial Release
  404  Not Found [IP: 13.90.21.104 443]
Hit:5 http://archive.ubuntu.com/ubuntu groovy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu groovy-backports InRelease
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/ubuntu/20.10/prod xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb seems to have bad contents. 20.10 is not `xenial`--that's 16.04. 20.10 is `groovy`. The setup package should point to https://packages.microsoft.com/ubuntu/20.10/prod/dists/groovy/.

This prevents me from installing anything using the 20.10 feed.

As a workaround, the 20.04 feed can be used on Ubuntu 20.10 for now to get 5.0 and 3.1.

@rbhanda  
/cc @NikolaMilosavljevic @adegeo @dleeapho @leecow

**Comment by leecow** [comment]
You can alternately use the prod.list file, which is correct. For example: 

```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg \
    && mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ \
    && wget -q https://packages.microsoft.com/config/ubuntu/20.10/prod.list \
    && mv prod.list /etc/apt/sources.list.d/microsoft-prod.list \
    && chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg \
    && chown root:root /etc/apt/sources.list.d/microsoft-prod.list

```

**Comment by NikolaMilosavljevic** [comment]
This issue was fixed today by the team that owns repositories at https://packages.microsoft.com.

I've verified that all .NET installation steps work as expected. .NET Core 3.1 and .NET 5.0 can be properly installed on Ubuntu 20.10.

**Comment by Mizux** [comment]
cross link:
https://github.com/dotnet/core/issues/5017
https://github.com/dotnet/core/issues/5352

**Comment by jonmartinsolaas** [comment]
Remember to update https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

**Comment by efinder2** [comment]
Same for the german version: https://docs.microsoft.com/de-de/dotnet/core/install/linux-ubuntu
