### ISSUE TITLE
Your naming convention for Nuget Packages is beyond belief

### ISSUE THREAD

**Issue by f135ta** [dotnet/core#5560]
I'm using SignalR - I've updated to Net5.. Which - of the 30000000 packages am I supposed to use?

**Comment by BrennanConroy** [comment]
SignalR on the client or server side? If you're on the server side there is no package as SignalR is in the aspnetcore shared framework.

For client side you use https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/

**Comment by carlossanlop** [comment]
No response in two weeks, but the question seems to be answered. Closing.
