### ISSUE TITLE
Visual Studio 2019 and ability to build/debug a project that will target .NET 6 REL

### ISSUE THREAD

**Issue by bairog** [dotnet/core#5567]
**UPDATE**
For today latest Visual Studio 2019 (**16.11.x**) doesn't **officially** support .NET 6 development. Possible workround is [described here](https://github.com/dotnet/core/issues/5567#issuecomment-1097797519).
As .NET 5.0 reaches EOL in 05.2022 and .NET Core 3.1 - in 12.2022 ([.Net Core Lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)) so Visual Studio 2019 will be unable to target .NET in a supported manner. But Visual Studio 2019 16.11 itself is supported untill 2029 ([VS 2019 Product Lifecycle](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing-vs2019)).

I've created [**Developer Community feature demand**](https://developercommunity.visualstudio.com/t/Make-NET-6-final-version-development-/1404241#T-ND10012461) asking to make .NET 6 LTS development available in Visual Studio 2019.

**ORIGINAL POST**
Is it planned to support Windows 7 SP1 and Debian 9 by .NET 6 LTS (and MAUI)?
According to [.NET Core Supported OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md) block **Exceptions to the supported platform policy**:

> One example is Windows 7 SP1. Windows 7 SP1 is out of support, but enterprise customers can buy Extended Security Updates, and many do. Given the widespread use of Windows 7 in the .NET ecosystem we chose to include Windows 7 SP1 (with Extended Security Updates installed) as a supported platform for .NET 5.0. 

According to [Lifecycle FAQ - Extended Security Updates](https://docs.microsoft.com/en-us/lifecycle/faq/extended-security-updates) block **ESU Availability and End Dates**:

> Windows 7 Extended Security Updates 2022: January 12, 2022 - January 10, 2023

Debian 9 EOL is June 30, 2022.

So are you planning to support both operating systems by .NET 6 LTS (and MAUI)?

Thank you.

P. S. Are you planning to support .NET 6 LTS (and MAUI) development with Visual Studio 2019? Or it will be an upcoming Visual Studio 2021-only feature? Or maybe you don't have plans to release a new Visual Studio version in 2021?

**Comment by bairog** [comment]
@davidortinau You've asked about user experience and MAUI expectations [The New .NET Multi-platform App UI](https://devblogs.microsoft.com/xamarin/the-new-net-multi-platform-app-ui-maui/) article. I've wrote you an email [almost a week ago]( https://devblogs.microsoft.com/xamarin/the-new-net-multi-platform-app-ui-maui/#comment-982 ) - still no reponse. Any uptades on this?

**Comment by bairog** [comment]
@richlander According to [this](https://github.com/dotnet/core/blob/master/release-notes/6.0/6.0-supported-os.md) NET 6.0 will support  supports Windows 7 SP1 (Extended Security Updates EOL – January 10, 2023) but drops supporting Debian 9 (EOL is June 30, 2022) if compared to .NET 5. What is the reason for this decision?
And I still have no answer about OS support plans for MAUI for more than 3 month.
Even @davidortinau ignores my emails and this github topic..

**Comment by mairaw** [comment]
Adding @leecow to see if he can comment on support plans as well

**Comment by leecow** [comment]
With respect to the Debian 9 decision, our general process is to exclude support for an OS version when that version will go EOL early in the new .NET version lifecycle. I haven't had any discussions with @davidortinau about MAUI OS support plans and expectations yet so can't offer anything on that topic.

**Comment by davidortinau** [comment]
.NET MAUI will support what WinUI 3 offers for Windows. https://microsoft.github.io/microsoft-ui-xaml/about.html#controls

Additional platform and version information is available here https://github.com/dotnet/maui#xamarinforms-vs-net-maui

Linux support will not be part of the .NET 6 release for .NET MAUI. It is under consideration for a future release, so please connect with me so we can better understand your needs for .NET MAUI and Linux. david.ortinau@microsoft.com or join one of the several discussions at https://github.com/dotnet/maui/discussions/

**Comment by mairaw** [comment]
Closing the issue since I believe all questions were answered. Please let us know otherwise @bairog.

**Comment by bairog** [comment]
@mairaw my questions about Visual Studio IDE are still unanswered..
> .NET MAUI will support what WinUI 3 offers for Windows. https://microsoft.github.io/microsoft-ui-xaml/about.html#controls
No support for Windows 7 SP1 with ESU - sad to hear, Uno project still supporting it..

> Linux support will not be part of the .NET 6 release for .NET MAUI. It is under consideration for a future release
You are talking about plans for .NET 7, right? 
Is it planned that .NET 7 development will be supported by Visual Studio 2019?
What are MS plans for Visual Studio 2021/2022/etc.?

**Comment by bairog** [comment]
> With respect to the Debian 9 decision, our general process is to exclude support for an OS version when that version will go EOL early in the new .NET version lifecycle. 

Debian 9 goes EOL (June 30, 2022) 7 month after .NET 6 planned release (November 2021). And it is considered as "will go EOL early". 
Windows 7 SP1 with ESU goes EOL (January 10, 2023) 14 month after .NET 6 planned release and is still supported. So it is considered as "will NOT go EOL so early".
Am I understanded correctly that Windows 7 SP1 with ESU will be very unlikely supported by .NET 7?
Or maybe MS already have plans for .NET 7 OS support?

**Comment by bairog** [comment]
[Visual Studio 2019 16.9 is released](https://devblogs.microsoft.com/visualstudio/vs2019-v16-9-and-v16-10-preview-1/) and considered to be a new Servicing Baseline. 
In [Servicing Baseline docs](https://docs.microsoft.com/ru-ru/visualstudio/releases/2019/servicing) there is an image:
![](https://docs.microsoft.com/ru-ru/visualstudio/releases/2019/media/16.9/servicing-baseline-2019-16.9.png)
Did I understand it correctly that Visual Studio 16.9 will be the penultimate baseline version (before last baseline version **16.final**)?
Does this mean that .NET 6 will be the last version that can be targeted by VS 2019? 
Does .NET 7 development will be available exclusively in **Visual Studio VNext**?

**Comment by bairog** [comment]
@JacquelineWiddis @madskristensen  Visual Studio 2022 [is announced](https://devblogs.microsoft.com/visualstudio/visual-studio-2022/) and it is stated that
> Visual Studio 2022 will have full support for .NET 6 and its unified framework for web, client, and mobile apps for both Windows and Mac developers. That includes the .NET Multi-platform App UI (.NET MAUI) for cross-platform client apps on Windows, Android, macOS, and iOS. You can also use ASP.NET Blazor web technologies to write desktop apps via .NET MAUI.
Does .NET 6 development will be available **exclusively** in Visual Studio 2022 or it will be also possibe in latest versions of Visual Studio 2019?
What about plans for .NET 7?

**Comment by bairog** [comment]
**.NET Hot Reload** [was announced today ](https://devblogs.microsoft.com/dotnet/introducing-net-hot-reload/) and it is stated that

> While some capability is being made available in early .NET 6 previews and in Visual Studio 2019, for the full power of this feature we are targeting .NET 6 (and future releases of .NET) and Visual Studio 2022 as the set of frameworks and tooling that will have the most complete and optimized experience.

@LyalinDotCom maybe you clear MS intentions: does .NET 6 (I mean final version, not preview) development will be available **exclusively** in Visual Studio 2022 or it will be also possibe in future versions of Visual Studio 2019? 
Thank you in advance.

**Comment by timheuer** [comment]
@bairog Yes the current plan is that Visual Studio 2022 will be the supported tool version for .NET 6 development (when final as you note).

**Comment by bairog** [comment]
> @bairog Yes the current plan is that Visual Studio 2022 will be the supported tool version for .NET 6 development (when final as you note).

I think Microsoft should reconsider that plan and make .NET 6 (final version) available **both** for Visual Studio 2019 and 2022 (latter may have more rich tooling). 
Many companies recently invested in the purchase of Visual Studio 2019 due to the long lack of news about Visual Studio VNext.
Thank you in advance.

**Comment by John0King** [comment]
I can't understand why  the dotnet team  interested in  Drop OS(eg. Devs, Enterprise, customers)  ,  why can not you guys make thin native layer to make OS support easier ?   I mean look at Java,  they never try to drop any OS  in the past/ now / future  !!!!

**Comment by bairog** [comment]
@JacquelineWiddis @madskristensen @timheuer @mikadumont @richlander .NET 6 Preview 6 [is announced](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-6/) and it is stated that
> Starting with .NET 6 Preview 6, we’ve tested and support Visual Studio 2022 Preview 2.

But what exactly does it mean? Visual Studio 2022 is tested and supported **in addittion** to Visual Studio 2019?
Is it still possible to develop applications for .NET 6 preview 6 with Visual studio 2019?
Thank you in advance.

**Comment by mairaw** [comment]
You can see in the download page @bairog what's the minimum version of VS supported:
https://dotnet.microsoft.com/download/dotnet/6.0

**Comment by bairog** [comment]
> You can see in the download page @bairog what's the minimum version of VS supported:
> https://dotnet.microsoft.com/download/dotnet/6.0

There for example **.NET 6.0.0-preview.5** has some strange VS version **Visual Studio 2019 (v17.0 latest preview)**. Misprint? 

**P.S.** According to [Visual Studio 2019 16.11 Preview 2](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-16-11-preview-2/) announce
> Version 16.11 will be the final version of Visual Studio 2019 and receive support through April 2029

Please make .NET 6.0 final available both for Visual Studio 2019 version 16.11 and Visual Studio 2022. Visual Studio 2022 may have more rich tooling for example. But Visual Studio 2019 version 16.11 should be able to build and debug a project targeting NET 6 final. It is not good practice for a later .NET6 preview to drop support of IDE that was supported in the previous .NET6 preview. Hope MS will hear me and understand my agrumentation.

**Comment by mairaw** [comment]
@rbhanda can you check on the VS version for .NET 6 preview 5? @bairog is right that there's a mismatch there.

I'll let others on the team chime in about future support plans re. Visual Studio and .NET 6.

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/6485 is created to correct the VS support version for .NET 6 Preview 5

**Comment by bairog** [comment]
I perfectly understand (at least it looks like this) that Microsoft plans to release Visual Studio 2019 version 16.11 (the last one) sometime in August-September, and then concentrate all its efforts on polishing Visual Studio 2022 and .NET 6 until their joint final release in November.
And most likely the final version of Visual Studio 2022 by November will have more features and tooling regarding .NET development. I really hope that at least the ability to build and debug a project targeting NET 6 final will be then backported to Visual Studio 2019 version 16.11.**x**. Looking forward to your final correct decision.

**Comment by mairaw** [comment]
Tagging @jamshedd to help with this question.

**Comment by jamshedd** [comment]
> Tagging @jamshedd to help with this question.

There were many questions in this thread so which one were you particularly thinking about :)

I will take the Win7 one - while this is by no means a final decision yet it is likely .NET 7 will not support Win7 since we would be shipping .NET 7 very close (Nov 2022) to when Win7 ESU ends (Jan 2023). But there are many factors that go into the decision including the portion of customers actively using Win7 at that point. We should have something to share around that next year. 

Regarding VS support, as Tim already mentioned .NET 6 development (and also .NET7, etc.) will be supported on Visual Studio 2022.

**Comment by bairog** [comment]
> Regarding VS support, as Tim already mentioned .NET 6 development (and also .NET7, etc.) will be supported on Visual Studio 2022.

Very sad to hear. **.NET 6 preview 4** development was supported on **Visual Studio 2019 16.11**. Starting from **.NET 6 preview 5** onwards only Visual Studio 2022 is supported. It is not good practice to drop support of IDE between adjacent previews.

**Comment by bairog** [comment]
@timheuer @jamshedd @mairaw **.NET 6.0-rc1** was released yesterday and is [“go live”](https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-1/)
So there should be an IDE with the same license type - but as I can see yesterday's [**VS 2022-preview4**](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-4-is-now-available/) is still in preview.
**VS 2019 16.11.x** is stable but Microsoft team again ang again says that it is not supported for .NET 6.0.
1) So what’s the recommended way to build .NET 6.0-rc1 applications?
2) For today I can still build and debug .NET 6.0-rc1 applications (at least console, WinForms and WPF) by enabling preview SDKs in VS2019 settings and manually setting TFM in .csproj file - many thanks for leaving this possibility for developers. I kindly ask Microsoft to leave this unchanged also after .NET 6.0 release. Thank you in advance.

**Comment by timheuer** [comment]
> @timheuer @jamshedd @mairaw
> [**.NET 6.0-rc1**](https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-1/) was released yesterday and is **“go live”** - so there should be an IDE with the same license type.
> 
> 1. So what’s the recommended and supported way to build .NET 6.0-rc1 applications in production?

This is correct the runtime platforms now have a go-live license. The tools are still in preview as you note and this is very common given platforms lock down a bit before giving tools some more time to finish support for final runtime APIs, scenarios, packages, naming, etc. We are still finishing VS features for .NET 6 around areas like hot reload, editor support for new C# 10 Lang features, and more. In general VS is more than just the current runtime release and so many features across the IDE are still finishing and this is not uncommon to have a platform have a go-live license for deployment while an IDE is still in preview. In fact as you and other devs use VS2022 for development please keep logging feedback bugs from VS for things that may not be working for your project/scenarios. We are still working on finishing and improving quality for .NET 6 projects but for many more things across the IDE.

**Comment by bairog** [comment]
@timheuer @jamshedd @mairaw
[VS 2022](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-now-available/) and [.NET 6.0](https://devblogs.microsoft.com/dotnet/announcing-net-6/) were released yesterday. According to [.NET 6.0 Known Issues](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md) docs

> .NET 6 is supported with Visual Studio 2022 and MSBuild 17. It is not supported with Visual Studio 2019 and MSBuild 16.
> If you build .NET 6 projects with MSBuild 16.11, for example, you will see the following error:
> _**warning NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported**_
> You can use the .net 6 SDK to target downlevel runtimes in 16.11.

Could you clarify what exactly does phrase _You can use the .net 6 SDK to target downlevel runtimes in 16.11_ mean?
For today I was able to build and debug test **.NET 6.0** applications (at least Console, WinForms and WPF) with latest **VS 2019 16.11.5** by enabling preview SDKs in VS2019 settings and manually setting TFM in .csproj file. Warning NETSDK1182 appears in command line but allows me to build, run and debug my test applications with no issues.

**Comment by timheuer** [comment]
> You can use the .net 6 SDK to target downlevel runtimes in 16.11

If you target net5.0 or lower you can use the .NET 6 SDK to still build them and target.

**Comment by SymbioticKilla** [comment]
There is a problem with NET Analyzers in VS2019 + NET 6.0 SDK is installed:
![image](https://user-images.githubusercontent.com/59652865/141798851-d5e7c461-21c4-434b-83cb-6d40ac04c2d1.png)

Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Will it be fixed or is there any workaround? VS2019 should actually use lower version for analyzing.

**Comment by mairaw** [comment]
@SymbioticKilla is your project targeting .NET 6 or earlier versions? If targeting .NET 6, you need to use Visual Studio 2022. But typically, VS issues should be reported through Help > Send Feedback > Report a Problem to help us triage issues better.

**Comment by SymbioticKilla** [comment]
> @SymbioticKilla is your project targeting .NET 6 or earlier versions? If targeting .NET 6, you need to use Visual Studio 2022. But typically, VS issues should be reported through Help > Send Feedback > Report a Problem to help us triage issues better.

Hi @mairaw,

thank you for reply. No, the projects target .NET Core 3.1. The problem shows up after installing SDK 6.0.
I will try to report the issue.

**Comment by timheuer** [comment]
@SymbioticKilla please report through VS Feedback and send me the link of the issue you reported...I'll route it accordingly.

**Comment by SymbioticKilla** [comment]
> @SymbioticKilla please report through VS Feedback and send me the link of the issue you reported...I'll route it accordingly.

@timheuer  Thank you! https://developercommunity.visualstudio.com/t/VS2019--Installation-of-SDK-60-produce/1585314?space=8&q=vs2019+3.1&stateGroup=active

**Comment by bairog** [comment]
BTW. For today I was able to build and debug my test **.NET 6.0** applications (at least **Class Library**, **Console**, **WinForms** and **WPF**) with latest **Visual Studio 2019 16.11.12** by enabling **Environment**\->**Preview Features**\->**Use previews of the .NET SDKs (requires restart)** checkbox in VS 2019 options, creating a new project targeting .NET 5.0 and then manually setting **<TargetFramework>** tag to **net6.0** in .csproj file.  
Warning **NETSDK1182** appears in command line but allows me to build, run and debug applications with no issues.  
That workaround is not officially supported by Microsoft but still working for today…
You can also add **<LangVersion>preview</LangVersion>** line to .csproj file to be able to use **C# 10** features with Visual Studio 2019.

@timheuer People are still adding comments to [Developer Community feature demand](https://developercommunity.visualstudio.com/t/Make-NET-6-final-version-development-/1404241#T-ND10012461) asking to make .NET 6 LTS development available in Visual Studio 2019. 
.NET 5 reaches end of support at 8 May 2022. Developers that use Visual Studio 2019 (whose companies doesn't plan to upgrade IDEs in near future) soon will have only two options: stay on unsupported (and potentially insecure) .NET 5 or downgrade to . NET 3.1 or even .NET Framewrok 4.8 (which is  hardy acceptable). I really hope that Microsoft will carefully consider that proposal, reconsider current desicion and allow building and debugging .NET 6.0 LTS with VS 2019 16.11.x.

**Comment by Applesauce314** [comment]
> @timheuer People are still adding comments to [Developer Community feature demand](https://developercommunity.visualstudio.com/t/Make-NET-6-final-version-development-/1404241#T-ND10012461) asking to make .NET 6 LTS development available in Visual Studio 2019. .NET 5 reaches end of support at 8 May 2022. Developers that use Visual Studio 2019 (whose companies doesn't plan to upgrade IDEs in near future) soon will have only two options: stay on unsupported (and potentially insecure) .NET 5 or downgrade to . NET 3.1 or even .NET Framework 4.8 (which is hardy acceptable). I really hope that Microsoft will carefully consider that proposal, reconsider current decision and allow building and debugging .NET 6.0 LTS with VS 2019 16.11.x.

Even if you downgrade to 3.1 Core that reaches end of support in December 2022 ([.Net Core Lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)).

The support for Visual Studio 2019 v16.11 is listed to be until 2029 ([VS 2019 Product Lifecycle](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing-vs2019)) so if things remain as they currently are you will be unable to target a supported .Net version for the last 7 years of its lifecycle. (Ironically .NET Framework is still supported since its lifecycle is tied to Windows).

As it stands the latest LTS version of visual studio available on November 7, 2021, will be unable to target .Net in a supported manner _**11 months and 26 days later.**_

**Comment by bairog** [comment]
@Applesauce314 Absolutelly agree.
Don't forget to leave a comment and vote on [Developer Community feature demand](https://developercommunity.visualstudio.com/t/Make-NET-6-final-version-development-/1404241#T-ND10012461) - maybe Microsoft will finally hear us.

**Comment by richlander** [comment]
We are not going to support .NET 6 with Visual Studio 2019. This decision will not be changed. You need to use Visual Studio 2022 for .NET 6. I appreciate that some companies have not upgraded to that version.

Is it possible to close this issue given that clarity?

**Comment by bairog** [comment]
Very disappointing to hear that this decision will not be changed.

**Comment by SrinivasAjimera** [comment]
It was great to read your post and it was really useful in helping me update my knowledge. Your article is also very well written. Keep up the good work! Thank you for sharing.

https://espirittech.com/dot-net-application-development-company/
