### ISSUE TITLE
Download page of dotnet core 3.1 runtime is linked to net5.0

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/core#5569]
# Issue Title

Download page of dotnet core 3.1 runtime also link to net5.0

# General
Find  `Download xxx Runtime` from
https://dotnet.microsoft.com/download

For 3.1, get
https://dotnet.microsoft.com/download/dotnet-core/current/runtime
And for 5.0, get
https://dotnet.microsoft.com/download/dotnet/current/runtime

but both link to `.NET 5.0 Runtime` download page

**Comment by dagood** [comment]
@mairaw @richlander 

This might be related to 5.0 kinda oddly showing up on both https://dotnet.microsoft.com/download/dotnet-core vs. https://dotnet.microsoft.com/download/dotnet ?

@yyjdelete in case you haven't found it yet and you're looking for them, you can still get the 3.1 .NET Core installers at: https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by mairaw** [comment]
We changed the link structure quite a bit since this feedback, so it doesn't apply anymore. But feel free to reopen this if there are still issues to be fixed that I've missed.
