### ISSUE TITLE
.NET 5 windowsdesktop-runtime installers are not accessible

### ISSUE THREAD

**Issue by chawyehsu** [dotnet/core#5593]
Following URLs are not accessible:

- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0.0/windowsdesktop-runtime-5.0.0-win-x64.exe
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0.0/windowsdesktop-runtime-5.0.0-win-x86.exe

ref.: https://github.com/chawyehsu/dorado/issues/221

From https://dotnetcli.blob.core.windows.net/dotnet/checksums/5.0.0-sha.txt we can find checksums for `windowsdesktop-runtime-5.0.0-win-x64.exe` and `windowsdesktop-runtime-5.0.0-win-x86.exe`.

**These installers should be accessible from https://dotnetcli.blob.core.windows.net**

---

Previously, 3.0.0 version of desktop runtimes are accessible, proof:

- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0/windowsdesktop-runtime-3.0.0-win-x64.exe
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0/windowsdesktop-runtime-3.0.0-win-x86.exe

**Comment by mairaw** [comment]
@leecow @rbhanda can you help here?

**Comment by leecow** [comment]
The location for WindowsDesktop artifacts is different for 5.0. 

https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/5.0.0/windowsdesktop-runtime-5.0.0-win-x64.exe
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/5.0.0/windowsdesktop-runtime-5.0.0-win-x86.exe
