### ISSUE TITLE
.NET 5 is missing in RHEL (CentOS) & Fedora

### ISSUE THREAD

**Issue by RheaAyase** [dotnet/core#5596]
## .NET 5 is missing in RHEL & Fedora

~~As of today we are unable to build .NET 5 on Linux.~~

This is an FYI ticket, a reference, and I will update it when we get some bits and pieces released.

#### Current state for 5.0.0

- [x] Fedora RPMs built
- [x] RHEL7 RPMs built
- [x] RHEL8 RPMs built
- [x] UBI8 Containers built
- [x] Documentation published
- [x] GA Announcement published

#### 5.0.1 ???

Due to the lag there is a bit of catch-up to be done, and 5.0.1 should make it in January.

#### Containers

~~Currently UBI8 (RHEL8) base images are available with our last successful RHEL8 build of .NET 5 packages - **preview 8**~~  
UBI8 .NET 5.0.0 available at: https://catalog.redhat.com/software/containers/search?q=ubi8%2Fdotnet-50&p=1

#### Binary download

You can use the binary format provided on the [Microsoft download page](https://dotnet.microsoft.com/download/dotnet/5.0).

#### Microsoft vs COPR repo for Fedora 33

Ensure that you remove all the Microsoft provided packages and repositories.

Our [copr repository](https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/) should work side by side with dotnet packages in Fedora proper and therefore it would be the recommended way to go.

**Comment by eLPe21** [comment]
Is my problem related? On Mac:
`dotnet publish -r centos.7-x64 -o ../out /p:PublishSingleFile=true /p:DebugType=None;`

On Centos 7:
```
Error:
  An assembly specified in the application dependencies manifest (IssacAPI.deps.json) was not found:
    package: 'runtime.rhel.7-x64.runtime.native.System', version: '4.3.0'
    path: 'runtimes/rhel.7-x64/native/System.Native.a'
```

Everything works ok when I target netcoreapp3.1

**Comment by omajid** [comment]
> Is my problem related?

From a quick look, I don't think so (but maybe I am wrong). Can you please report this as a separate issue?

**Comment by azixaka** [comment]
I think it's been tagged now? https://github.com/dotnet/core/tree/v5.0.0

**Comment by dagood** [comment]
> I think it's been tagged now? [https://github.com/dotnet/core/tree/v5.0.0](https://github.com/dotnet/core/tree/v5.0.0)

dotnet/core is just a documentation and "starting point" repository. I believe the purpose of this particular tag is just to let repo watchers know that a release happened.

The repo that actually coordinates the variety of .NET repos and enables RHEL (among other Linux distros) to build from source is https://github.com/dotnet/source-build. We--Red Hat and Microsoft folks in collaboration--are actively working on getting 5.0.0 building in dotnet/source-build. This will end up with `v5.0.100-SDK` and `v5.0.0-runtime` tags in dotnet/source-build as a release artifact at some point, but this isn't something someone has to watch carefully for: we're already working together.

**Comment by RheaAyase** [comment]
.NET 5 was tagged in source-build a few days ago, and the cogs are spinning. I've added some checkboxes to the OP...

**Comment by RheaAyase** [comment]
RHEL RPMs and Containers are live with a side note that the documentation and official announcement are yet to be published.

**Comment by RheaAyase** [comment]
Fedora: 5.0 is built in our [copr repository](https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/), work continues towards bootstrapping for proper release...

**Comment by RheaAyase** [comment]
Oh and a fancy new developer page for dotnet on RHEL can be found at http://redhatloves.net :)

**Comment by the-black-wolf** [comment]
Centos 8 is still on preview 8. We are sort of threading water, wating for .net 5 rtm (any version) to get there. When is this due to go out, its been over a month since 5 was released.  

https://pkgs.org/download/aspnetcore-runtime-5.0

**Comment by omajid** [comment]
> Centos 8 is still on preview 8.

That's strange. I see that they built the GA version: https://koji.mbox.centos.org/koji/buildinfo?buildID=14975 but it's not available to users yet? I wonder what else needs to happen for CentOS to ship that update out.

Edit: Oh, I see. It's in `dist-c8-stream` (CentOS 8 Stream) not in `dist-c8` (CentOS 8).

**Comment by secana** [comment]
Hi! Any news when .NET 5 will hit official Fedora 33 repositories?

**Comment by RheaAyase** [comment]
[This didn't change.](https://github.com/dotnet/core/issues/5596#issuecomment-742624627)

> Fedora: 5.0 is built in our [copr repository](https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/), work continues towards bootstrapping for proper release...

**Comment by RheaAyase** [comment]
.NET 5 is in F33 and rawhide, soon to be in F32 as well. On that note I think that we can close this issue.

**Comment by GeeWee** [comment]
If anyone finds this post later and is struggling to install dotnet 5.0, it might be because you have the microsoft repository available. The package is available in the "updates" repository even though it might not be visible if you run e.g. `dnf list all "*dotnet-sdk*"`

If you set the priority of the microsoft repo to e.g. 100 in e.g. `/etc/yum.repos.d/microsoft.repo` it should work, or you can install the fedora version with something like `sudo dnf --disablerepo "*" --enablerepo updates install dotnet-sdk-5.0`

On related notes, it might be worth updating the [wiki page here](https://fedoraproject.org/wiki/DotNet) that says dotnet 5 is not available

**Comment by RheaAyase** [comment]
That is very well know and documented. One should **NEVER** combine packages from different sources. Bad idea.
