### ISSUE TITLE
RISC-V / FPGA Support

### ISSUE THREAD

**Issue by logicethos** [dotnet/core#5597]
RISC-V is gaining ground, as an opensource alternative to ARM.
AllWinnder with Alibaba's backing, are about to launch a low cost SOC, based on RISC-V
This will open the door to low cost IoT, on open hardware.
Google, Western Digital, Segate and others are backing OpenTitan. Open source security on RISC-V.
RISC-V can run on FPGA's.
FPGA's opens .NET to a whole new world of performance.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/36748 and https://github.com/dotnet/runtime/issues/12546
