### ISSUE TITLE
Can not find runtime target for framework 'DNXCore,Version=v5.0' and RID's 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes

### ISSUE THREAD

**Issue by xielongjiang** [dotnet/core#56]
I use 'dotnet restore' in the following error：
log  : Restoring packages for D:\core\samples\dotnetbot\project.json...
error: Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23704) for DNXCore,Version=v5.0.
info : Committing restore...
log  : Restore failed in 312ms.
Errors in D:\core\samples\dotnetbot\project.json
    Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23704) for DNXCore,Version=v5.0.
NuGet Config files used:

I use 'dotnet run' in the following error：
Can not find runtime target for framework 'DNXCore,Version=v5.0' and RID's 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. Project is not restored or restore failed - run `dotnet restore`
2. Project is not targeting `runable` framework (`netstandardapp*` or `net*`)

How do I fix it

**Comment by CreativeManix** [comment]
I do have same issue

**Comment by SMASH1337** [comment]
Same issue here

**Comment by SMASH1337** [comment]
One issue you have is there's errors in your restore.

**Comment by tiomke** [comment]
maybe you choose the wrong NuGet Feeds, the default Feed don't have NETStandard.Library yet.

try
```
dnu restore -s https://myget.org/f/dotnet-core
```
or write a NuGet.Config file adding the `myget` feed into it.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>
```

**Comment by TiFix** [comment]
After dotnet restore, i try to run dotnet run and get this error:
Can not find runtime target for framework 'DNXCore,Version=v5.0' and RID's 'win7-x64'. Possible causes:
1. Project is not restored or restore failed - run `dotnet restore`
2. Project is not targeting `runable` framework (`netstandardapp*` or `net*`)

**Comment by TiFix** [comment]
My problem was solved: problem is when vmware or virtualpc network adapters are activated in system. Disabling helps.

**Comment by joshfree** [comment]
Closing this old issue.  Please feel free to reactivate if there is still a problem.

Instructions are available at http://dot.net/core

**Comment by adrua** [comment]
hi, 

are you update  to .NET Core 1.0 for Visual Studio?. 
Please change your frameworks list in 'Project.json' by 

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  },

rebuild your application

Good luck
