### ISSUE TITLE
Can't create an app

### ISSUE THREAD

**Issue by SuryaGithub1996** [dotnet/core#5605]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Showing below error 👎 
It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
Did you click on the Download SDK button on the install step? If so, can you show the results of running `dotnet --info` on the command prompt?
