### ISSUE TITLE
. NET

### ISSUE THREAD

**Issue by zelihaarduclu** [dotnet/core#5608]
![Ekran Görüntüsü (183)](https://user-images.githubusercontent.com/61326828/99199302-cc441380-27a6-11eb-9b3a-0f0ea013447f.png)
bir web sitesini dahi calıstıramıyorum. Bu sorun hakkında ne yapmalıyım. .NET'i daha once bir cok kez indirdim onardım ama hala hata alıyorum.Bana yardımcı olurmusunuz.

**Comment by GrabYourPitchforks** [comment]
Translation from Turkish:

> I can't even get a website to work. What should I do about this problem? I've downloaded .NET many times before, repaired it, but I'm still getting errors. Can you help me?

**Comment by mairaw** [comment]
What is the error you're seeing @zelihaarduclu? Your site looks fine on the screenshot.
