### ISSUE TITLE
Mac can't find project ASP.NET Core on the terminal

### ISSUE THREAD

**Issue by John-Codes** [dotnet/core#5609]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you provide more information or a screenshot of the error?

**Comment by John-Codes** [comment]
Best regards I don’t even remember this issue anymore 😂 have a nice day.

**Comment by mairaw** [comment]
Apologies for taking so long to reply.

**Comment by John-Codes** [comment]
No worries better late than never.
