### ISSUE TITLE
Consider not enabling globalization by default for .NET Core 2.0 - space savings

### ISSUE THREAD

**Issue by richlander** [dotnet/core#561]
This would be the user experience:

- All sorting and string manipulation would be invariant by default.
- You can opt into full globalization support with one gesture.

Benefit: .NET Core 2 deployments (including with Docker) would be ~27MB smaller by default.

/cc @Petermarcu

**Comment by Petermarcu** [comment]
This was done in .NET Core 2.0. Closing now. https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md
