### ISSUE TITLE
Cannot find sdk-preview2-3131

### ISSUE THREAD

**Issue by dazinator** [dotnet/core#562]
I'm searching for .NET Core SDK version 1.0.0-preview2-003131
I can't seem to find that listed in the download archiver here:
 https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

Am I missing something?

**Comment by leecow** [comment]
@dazinator - The SDK builds for Preview 2 were 3133 for Windows and 3131 for everything else. We'll update the download archive index to include that information. This download page will have what you're looking for.

https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.1-preview2-download.md

/cc @preetikr
