### ISSUE TITLE
.NET 5 is missing in SLES 15

### ISSUE THREAD

**Issue by andreichuk** [dotnet/core#5623]
There are no .NET 5 packages available for SLES 15
[https://packages.microsoft.com/sles/15/prod/](https://packages.microsoft.com/sles/15/prod/)

**Comment by omajid** [comment]
https://docs.microsoft.com/en-us/dotnet/core/install/linux#sles says SLES 15 is supported. And https://docs.microsoft.com/en-us/dotnet/core/install/linux-sles says that the packages should be available.

**Comment by omajid** [comment]
cc @leecow

**Comment by dagood** [comment]
https://github.com/dotnet/core/issues/5545 also mentions .NET 5 on SLES 15 feeds. @rbhanda

**Comment by rbhanda** [comment]
I have uploaded the packages to sles15. This should take around 30 minutes to reflect on the feed at https://packages.microsoft.com/sles/15/prod/

**Comment by rbhanda** [comment]
This should be resolved, closing this issue.
