### ISSUE TITLE
Side by side unresolved

### ISSUE THREAD

**Issue by DHopkins** [dotnet/core#5626]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
No matter what I do I cannot install .NET SDK (64-bit) as the same box keeps appearing regarding the Side by side  configuration being incorrect.
Unfortunately, my technical knowledge is nil.

**Comment by scalablecory** [comment]
@dagood

**Comment by dagood** [comment]
@DHopkins what box are you seeing? Can you send a screenshot, or copy paste the contents?

/cc @joeloff

**Comment by joeloff** [comment]
+1 for what @dagood said. A screen shot or some logs would be good. The installer logs are kept in your %temp% folder. Open File Explorer, type %temp% in the address bar and then look for a file like "Microsoft_.NET_SDK_5.0.100_(x64)_20201124092512.log" (the numbers at the end would be different as it's a date/time stamp)
