### ISSUE TITLE
Debugging into nuget packages

### ISSUE THREAD

**Issue by PeterKottas** [dotnet/core#563]
Hello all, I've tried to figure out if this is proper place to place this issue but I am still not sure so I'll just try it. 
I have a nuget package that was packed from a dotnet build with release configuration. It contains *.pdb in "lib/netcoreapp1.1" and I've also included all *.cs files in "src" folder in the root of the nuget package.

However, when referencing this package in another project, I can't seem to be able to step into code from this nuget package. Am I missing something? I also tried dot peak to act as a symbol server but no luck there either. Just my code is switched off. 

I can see this in the output window while I start debugging which sounds promising but still no good:
'dotnet.exe' (CoreCLR: clrhost): Loaded 'pathToMyDll.dll'. Symbols loaded.

Is there a recommended way of achieving this? I am using vs2017 rc and therefore sdk rc4

Any help much appreciated.  

Thanks

**Comment by Petermarcu** [comment]
Are you able to try with the RTM tooling and SDK? I'm not sure that anything is fixed but it's a better baseline to get support from. 

@gregg-miskelly @noahfalk , any advice on how to get symbols properly loaded from a package? Any know issues? Where should an issue like this be created?

**Comment by gregg-miskelly** [comment]
@PeterKottas If symbols are loading, I am not quite sure what is going on. You are hitting the step-in command but the debugger is acting like you asked for a step over? Is the calling project also from the release configuration? If you open the disassembly window and step into the right 'call' instruction what happens?

**Comment by PeterKottas** [comment]
Hi guys, thanks for getting back to me. 
@Petermarcu I am trying this with the latest sdk available here https://www.microsoft.com/net/download/core
@gregg-miskelly Yep step in and it steps over automatically. If I put a break point on a method directly like [here,](https://msdn.microsoft.com/en-us/library/15d1wtaf(v=vs.90).aspx)  it goes into disassembly. 
Good point about release configuration. My nugets are 'release' (that kind of makes sense for nugets) while my app is in debug during development. Would that be causing the problem? If so, I kind of struggle to see the best practice with this. Cause on one hand, I want release conf for nugets for optimizations. On other, I probably want to debug in debug as that seems to be the sensible thing to do. And I definitely don't want to keep switching (and maintaining) both debug and release nugets. What do you guys do when debugging into net core nugets? (I would assume it's a common practice as the framework is still fairly new)

**Comment by gregg-miskelly** [comment]
@PeterKottas having any amount of release configuration bits may make things confusing/annoying, but you shouldn't be blocked like you are seeing. Mixing debug and release should actually be better than 'all release' as this will prevent some optimizations like inlining across modules.

Do you have a project that you can share?

**Comment by richlander** [comment]
Is this still an issue? Do you have any projects you can share?

**Comment by Petermarcu** [comment]
@PeterKottas , we debug into release binaries when we get issues reported from people using the contents of nuget packages. For now I'm going to close this issue because it's pretty old and I'm not sure there is still an issue but feel free to comment again if we should continue to explore this.
