### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GhostNetCCC** [dotnet/core#5636]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 

PS C:\Windows\system32> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by igoventura** [comment]
Have You installed dotnet on your machine?

**Comment by mairaw** [comment]
Also, have you opened a new command prompt after the installation?
