### ISSUE TITLE
Make 2.1 as default Target Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/core#5641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/919081/make-21-as-default-target-framework.html)._

---
Hi,

Please make the 2.1 .NET Standared as default Target Framework as all new packages are targeting the 2.1 version

Thanks,
[Jassim] (https://www.emiratesangels.org)

---
#### Feedback Bot on 2/16/2020, 05:20 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jamshedd** [comment]
@KathleenDollard, do you have suggestions on where this should go?

**Comment by danmoseley** [comment]
We don't plan to do this (a far as I know) as 2.0 includes .NET Framework support, which is likely be be a target of many libraries. Thanks for the suggestion though.
