### ISSUE TITLE
When doing the weekly servicing update, actually upgrade .Net Core, rather than installing another ~460Mb of Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/core#5642]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/370910/when-doing-the-weekly-servicing-update-actually-up.html)._

---
<p>It seems that on installing any update to Visual Studio, a new .Net Core SDK is installed, typically weighing in at about ~460Mb.</p><p>This quickly accumulates into a large amount of diskspace consumed, for little obvious benefit (after all, isn't nuget supposed to solve this?)</p>

---
#### Fiona Niu[MSFT] on 10/30/2018, 08:08 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by jamshedd** [comment]
Responded on the Dev Community site: https://developercommunity.visualstudio.com/content/idea/370910/when-doing-the-weekly-servicing-update-actually-up.html

**Comment by RowlandShaw** [comment]
Agree this is closed - when it was originally raised it was the case that installing (say) 2.0.10 would not remove 2.0.9, but I think that behaviour changed in 2019/early 2020
