### ISSUE TITLE
Need to know more about SDK and Runtime (LTS & Current)

### ISSUE THREAD

**Issue by manikandan05** [dotnet/core#565]
Hi,

During my ASP.NET Core and its documentation analysis, recently i have noticed in this link [https://www.microsoft.com/net/download/core](https://www.microsoft.com/net/download/core).

![image](https://cloud.githubusercontent.com/assets/5366630/24135608/cd3883d6-0e30-11e7-9c14-de0aedb87d54.png)

Previously this link holds the information for SDK exists in both LTS and Current like as below screenshot.

![120316_1628_multiplever1](https://cloud.githubusercontent.com/assets/5366630/24135669/26819090-0e31-11e7-9e6b-293d82a9d44d.png)

But, the latest online link holds only the LTS in runtime option only. Now, i want to switch my project with LTS version support (now 1.0.4). In this case, i have some doubt regarding this LTS version support.

1. How long this LTS version (1.0.4) supported in your future releases? (may be timeline)
2. If i have installed this LTS runtime setup in my machine, but i have previously installed SDK (1.0.0 with VS2017 March 14 update). Then how this will be works?. Also, after installed this runtime setup, i didn't find any packages with 1.0.4 version except "microsoft.aspnetcore" package. So i'm unable to declare the remaining packages with 1.0.4 version in my project, these packages are automatically takes 1.1.0 version. This is correct way or not?

![untitled](https://cloud.githubusercontent.com/assets/5366630/24135815/e651c0f2-0e31-11e7-8510-6ec4ae93b7b1.png)

Apart from that, if i have provided LTS (1.0.4) based on your reply in above query. In my local machine only i have installed 1.0.4 version. Now i want to run this project in another one machine without 1.0.4 LTS setup. This will be work? If , its working means no problem to me. If not means, what are the necessary steps need to followed in my new machine to deploy my project.

Can you please clarify my queries, is more helpful for switch my project from Current to LTS support.

Thanks.

**Comment by richlander** [comment]
If you install the latest 1.x SDK, you will get both 1.0.x and 1.1.x runtime versions. We recommend that you use .NET Core 1.1. It will have the same support timeframe as .NET Core 1.0.
