### ISSUE TITLE
ExcludeFromCodeCoverage not working on async methods

### ISSUE THREAD

**Issue by dpuckett** [dotnet/core#5664]
This is likely related to #4361, but is another area not being addressed/mentioned

A method marked as async returning any Task/Task<> is ignored by the ExcludeFromCodeCoverage attribute.

I'm working with Xamarin and some libs such as Xamarin.Essentials and AzureCrossPushNotification, the internals of which do not need to be tested by myself. So I have abstracted the exact use of these into separate wrapper classes and try to exclude from test coverage.

However it seems that with the methods marked "async", they're still included in test coverage. 
Removing async/await the method is instantly excluded from coverage correctly.

Not Excluded:
```c#
public class CrossAzurePushNotificationWrapper : ICrossAzurePushNotificationWrapper
{
    [ExcludeFromCodeCoverage]
    public async Task RegisterAsync(string[] tags)
    {
        await CrossAzurePushNotification.Current.RegisterAsync(tags);
    }
}
```

Excluded:

```c#
public class CrossAzurePushNotificationWrapper : ICrossAzurePushNotificationWrapper
{
    [ExcludeFromCodeCoverage]
    public void RegisterAsync(string[] tags)
    {
        CrossAzurePushNotification.Current.RegisterAsync(tags);
    }
}
```

**Comment by danmosemsft** [comment]
@jakubch1 is this and its related issues in your area? Could you help transfer?

**Comment by jakubch1** [comment]
@danmosemsft  I've created issue in vstest area. 

@dpuckett  I think you can fix it by moving `ExcludeFromCodeCoverage` to class level:

```
[ExcludeFromCodeCoverage]
public class CrossAzurePushNotificationWrapper : ICrossAzurePushNotificationWrapper
{   
    public async Task RegisterAsync(string[] tags)
    {
        await CrossAzurePushNotification.Current.RegisterAsync(tags);
    }
}
```

**Comment by dpuckett** [comment]
Thanks for looking at this @jakubch1.

I have tried adding to the class level before, but the blocks are still included in code coverage.

I get the feeling whatever is causing the problem is drilling deeper into the code blocks than just surface level.

**Comment by danmoseley** [comment]
It seems this is covered by the vstest issue
