### ISSUE TITLE
xproj to csproj migration missing BaseIntermediateOutputPath and OutputPath

### ISSUE THREAD

**Issue by mohamedmansour** [dotnet/core#567]
Hello, I just migrated from `xproj` to `csproj` from the Visual Studio 2017 process. And the migration missed two things:

- OutputPath
- BaseIntermediateOutputPath

When I filled them in manually, the `OutputPath` functioned correctly but the `BaseIntermediateOutputPath` didn't work. Who can help out?

    <OutputPath>..\bin\</OutputPath>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\obj</BaseIntermediateOutputPath>

**Comment by dsplaisted** [comment]
See https://github.com/Microsoft/msbuild/issues/1603#issuecomment-283104367 for information on how to do this correctly.

**Comment by Petermarcu** [comment]
I'm going to close this for now. You can get support for migrate here: http://landinghub.visualstudio.com/migrate-dotnetcore and it looks like @dsplaisted has pointed to the way to handle this.
