### ISSUE TITLE
GraphicsCapturePicker doesn't work in .NET 5.

### ISSUE THREAD

**Issue by aqibbanday** [dotnet/core#5670]
System.InvalidCastException: 'Invalid cast from 'Windows.Graphics.Capture.GraphicsCapturePicker' to 'WpfApp1.IInitializeWithWindow'.'

**Comment by aqibbanday** [comment]
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
An exception of type 'System.InvalidCastException' occurred in System.Private.CoreLib.dll but was not handled in user code
Invalid cast from 'Windows.Graphics.Capture.GraphicsCapturePicker' to 'WpfApp1.IInitializeWithWindow'.

**Comment by aqibbanday** [comment]
### WITHOUT IInitializeWithWindow
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Private.CoreLib.dll but was not handled in user code
The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))

**Comment by stevenbrix** [comment]
@aqibbanday, this may be an issue for the https://github.com/microsoft/cswinrt repo, but what does your `IInitailizeWithWindow` definition look like? 

See the COM interop guide here: https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md

**Comment by aqibbanday** [comment]
var interopWindow = new WindowInteropHelper(this);
            hwnd = interopWindow.Handle;

            var picker = new GraphicsCapturePicker();

            var interop = (IInitializeWithWindow)(object)picker;
            interop.Initialize(hwnd);
            GraphicsCaptureItem item = await picker.PickSingleItemAsync();

**Comment by aqibbanday** [comment]
This fixes the issue. Thanks.

            var interopWindow = new WindowInteropHelper(this);
            hwnd = interopWindow.Handle;
            var picker = new GraphicsCapturePicker();
            var window = picker.As<IInitializeWithWindow>();
            window.Initialize(hwnd);
            var item = await picker.PickSingleItemAsync();

**Comment by VAllens** [comment]
> ```
>         var interopWindow = new WindowInteropHelper(this);
>         hwnd = interopWindow.Handle;
> 
>         var picker = new GraphicsCapturePicker();
> 
>         var interop = (IInitializeWithWindow)(object)picker;
>         interop.Initialize(hwnd);
>         GraphicsCaptureItem item = await picker.PickSingleItemAsync();
> ```

In my computer: 
InitializeWithWindow is static class.

```C#
#region Assembly Microsoft.Windows.SDK.NET, Version=10.0.18362.21, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// C:\Users\Allen\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.18362.21\lib\Microsoft.Windows.SDK.NET.dll
#endregion

using System;

namespace WinRT.Interop
{
    public static class InitializeWithWindow
    {
        public static void Initialize(object target, IntPtr hwnd);
    }
}
```

my csproj code:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
    <TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
  </PropertyGroup>

</Project>
```

The following code works fine on my laptop.
```C#
var interopWindow = new WindowInteropHelper(this);
var hwnd = interopWindow.Handle;
var picker = new GraphicsCapturePicker();
InitializeWithWindow.Initialize(picker, hwnd);
var item = await picker.PickSingleItemAsync();
```

System: Windows 10 21H2 (19044.1387)

**Comment by aqibbanday** [comment]
> > ```
> >         var interopWindow = new WindowInteropHelper(this);
> >         hwnd = interopWindow.Handle;
> > 
> >         var picker = new GraphicsCapturePicker();
> > 
> >         var interop = (IInitializeWithWindow)(object)picker;
> >         interop.Initialize(hwnd);
> >         GraphicsCaptureItem item = await picker.PickSingleItemAsync();
> > ```
> 
> In my computer: InitializeWithWindow is static class.
> 
> ```cs
> #region Assembly Microsoft.Windows.SDK.NET, Version=10.0.18362.21, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> // C:\Users\Allen\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.18362.21\lib\Microsoft.Windows.SDK.NET.dll
> #endregion
> 
> using System;
> 
> namespace WinRT.Interop
> {
>     public static class InitializeWithWindow
>     {
>         public static void Initialize(object target, IntPtr hwnd);
>     }
> }
> ```
> 
> my csproj code:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <OutputType>WinExe</OutputType>
>     <TargetFramework>net5.0-windows</TargetFramework>
>     <UseWPF>true</UseWPF>
>     <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
>     <TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
>   </PropertyGroup>
> 
> </Project>
> ```
> 
> The following code works fine on my laptop.
> 
> ```cs
> var interopWindow = new WindowInteropHelper(this);
> var hwnd = interopWindow.Handle;
> var picker = new GraphicsCapturePicker();
> InitializeWithWindow.Initialize(picker, hwnd);
> var item = await picker.PickSingleItemAsync();
> ```
> 
> System: Windows 10 21H2 (19044.1387)

The answer has already been provided

**Comment by VAllens** [comment]
> var window = picker.As<IInitializeWithWindow>();
>         window.Initialize(hwnd);

These two lines of code compile with an error.
```C#
var window = picker.As<IInitializeWithWindow>();
window.Initialize(hwnd);
```

The correct code is as follows: 
```C#
InitializeWithWindow.Initialize(picker, hwnd);
```

**Comment by aqibbanday** [comment]
Are you referencing WinRT namespace

**Comment by VAllens** [comment]
> Are you referencing WinRT namespace

Yes, using `WinRT` namespace.
`IInitializeWithWindow` interface with protection level.
I can only use the `InitializeWithWindow` static class.

```C#
#region Assembly Microsoft.Windows.SDK.NET, Version=10.0.19041.21, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// D:\caches\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.21\lib\Microsoft.Windows.SDK.NET.dll
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion

using System;
using System.Runtime.InteropServices;

namespace WinRT.Interop
{
    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
    internal interface IInitializeWithWindow
    {
        void Initialize(IntPtr hwnd);
    }
}
```

**Comment by aqibbanday** [comment]
```
using System;
using System.Windows;
using System.Windows.Interop;
using Windows.Graphics.Capture;

namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private async void OnClick(object sender, RoutedEventArgs e)
        {
            var interopWindow = new WindowInteropHelper(this);
            var hwnd = interopWindow.Handle;
            var picker = new GraphicsCapturePicker();
            WinRT.Interop.InitializeWithWindow.Initialize(picker, hwnd);
            var item = await picker.PickSingleItemAsync();
        }
    }
}

```

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
`

**Comment by aqibbanday** [comment]
```
using System;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Interop;
using Windows.Graphics.Capture;
using WinRT;

namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private async void OnClick(object sender, RoutedEventArgs e)
        {
            var interopWindow = new WindowInteropHelper(this);
            var hwnd = interopWindow.Handle;
            var picker = new GraphicsCapturePicker();
            var window = picker.As<IInitializeWithWindow>();
            window.Initialize(hwnd);
            var item = await picker.PickSingleItemAsync();
        }
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
        internal interface IInitializeWithWindow
        {
            void Initialize(IntPtr hwnd);
        }
    }
}

```

**Comment by VAllens** [comment]
Can we get all screens automatically? thanks.
@aqibbanday

**Comment by aqibbanday** [comment]
Yes, as far as i remember in share your screens section you can select single screen or all screens.
