### ISSUE TITLE
Regex.Replace not work as expected

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/core#5675]
## Issue

Consider the following code:
```cs
Regex.Replace("The result is 1", @"(.*?)\d+", "$12")
```

Expected output: 
```
The result is 2
```

Actual output:
```
$12
```

![image](https://user-images.githubusercontent.com/4510984/100549683-692aa480-32af-11eb-85cd-f3fc23493394.png)

----------

#### Online tools output

![image](https://user-images.githubusercontent.com/4510984/100549823-41880c00-32b0-11eb-8eba-d7939e74b985.png)

#### VS Code

![b8S2jl5tHJ](https://user-images.githubusercontent.com/4510984/100549849-7005e700-32b0-11eb-91ba-a5f4022ebefe.gif)

**Comment by svick** [comment]
This works [exactly as documented](https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions?WT.mc_id=DOP-MVP-5002735#substituting-a-numbered-group). To get your expected output, you can use the following code:

```c#
Regex.Replace("The result is 1", @"(.*?)\d+", "${1}2")
```

**Comment by GF-Huang** [comment]
Thanks.
