### ISSUE TITLE
Visibility into the expected release date for 5.0.1

### ISSUE THREAD

**Issue by dazinator** [dotnet/core#5676]
# 5.0.1

I am currently [waiting on something](https://github.com/dotnet/aspnetcore/issues/27776) that was fixed in 5.0.1
Are you able to set any expectations as to when it will be released - this month? next month etc?
I tried to find this information but could not find it anywhere.
The answer to this will help us plan our upgrade path better from 3.1.0.

# General

As above. Moving forwards, it would be really helpful to be able to see estimated / scheduled release dates for servicing releases somewhere.. even if they were subject to change, it's better than nothing from a planning perspective.

**Comment by mairaw** [comment]
@leecow @rbhanda can you help here? Do we already know when 5.0.1 will be released? Typically, we release patches once a month.

**Comment by rbhanda** [comment]
Current planned date for 5.0.1 release is 8 December 2020

**Comment by dazinator** [comment]
Leaving this issue open because my issue was not solved in 5.0.1 and was told to wait for 5.0.2 so naturally I wanted to track 5.0.2!  Now 5.0.2 has been released today and there are still some issues - So I'd like to keep tabs on 5.0.3. It would be fantastic if there was some page somewhere that was updated with estimated release dates!

**Comment by mairaw** [comment]
Typically, the release will happen on the second Tuesday of every month. /cc @jamshedd @leecow

https://twitter.com/lbcoward/status/1334705051491729410?s=20

**Comment by dazinator** [comment]
Thank you for the clarification - that's helpful.
