### ISSUE TITLE
Could not execute (tutorial command) because the specified command or file was not found

### ISSUE THREAD

**Issue by Leipreachan15** [dotnet/core#5680]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/75273932/100652424-eb00e900-3314-11eb-9cba-204f7a608295.png)

**Comment by mairaw** [comment]
You're missing the new keyword as in dotnet new:

`dotnet new console -o myApp`

Copy and paste the command from the tutorial and it should work.

**Comment by Leipreachan15** [comment]
Uggh! Silly cockpit error; forgot to instantiate. Thank you!
