### ISSUE TITLE
'.NET Thank You!' website contribution counting

### ISSUE THREAD

**Issue by tmds** [dotnet/core#5682]
[Announcing .NET 5.0](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/) blog post has a [.NET 5.0 Contributors](https://dotnetthanks.azurewebsites.net/) link.

.NET 5 gets splits into many versions on this site. It would be nice to have a total number per contributor that indicates contributions since 3.1.

I also think the numbers of this website may be wrong. For example, for each .NET 5 RC/preview/final it shows exactly 2 contributions for me.

cc @richlander @leecow @spboyer @omajid

**Comment by leecow** [comment]
Thanks, Tom. That contributor page is definitely a work in progress. I don't know that we'll include pre-5.0 contributions owing to the repo consolidation effort that took place.

For the 5.0 release, [this contributor list](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-contributor-list.md) may be a little more accurate.

/cc @spboyer

**Comment by NickCraver** [comment]
Cross-referencing to the source repo: https://github.com/spboyer/dotnetthanks/issues/4

**Comment by spboyer** [comment]
Updated data loader, smoke tests look good.

**Comment by vcsjones** [comment]
I'm not so sure the data is accurate right now. Examining Kevin Jones for each release:

* `v5.0.0`: 0
* `v5.0.0-rc.2`: 0
* `v5.0.0-rc.1`: 4
* `v5.0.0-preview.8`: 4
* `v5.0.0-preview.7`: 0
* `v5.0.0-preview.6`: 5
* `v5.0.0-preview.5`: 1
* `v5.0.0-preview.4`: 0
* `v5.0.0-preview.3`: 2
* `v5.0.0-preview.2`: 0

Add it up and we get 16. In the linked issue with the [contributor list][1] I have 51. GitHub agrees that 51 looks like the right number. https://github.com/dotnet/runtime/pulls?q=is%3Apr+author%3Avcsjones+created%3A2019-09-24..2020-08-26+is%3Amerged

Automating this a bit with `jq`:

```shell
cat ~/Desktop/core.json | jq -c '[.[].Contributors[] | select(.Name == "Kevin Jones") | .Count] | add' #17
cat ~/Desktop/core.json | jq -c '[.[].Contributors[] | select(.Name == "Tom Deseyn") | .Count] | add' #5
```

Mine came out to 17 because I had one in v5.0.1, so the number agrees. Tom has 5 but the contributor docs show 22.

[1]: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-contributor-list.md

**Comment by danmoseley** [comment]
Cc @richlander

**Comment by mairaw** [comment]
@spboyer has been working on improving that data. I also think it could be fun to add a search by the person's name so it's easier to check yourself.

An update was pushed this morning. Can you let us know if that looks accurate now?

**Comment by vcsjones** [comment]
@mairaw 

> Can you let us know if that looks accurate now?

Well, I see it was updated for .NET 5.0.3. I had one servicing PR merged for 5.0.3 in https://github.com/dotnet/runtime/pull/46713 and I don't see myself in the 5.0.3 notes. 

Looking further in to 5.0.0 for myself:

```
v5.0.0-preview.2: 0
v5.0.0-preview.3: 0
v5.0.0-preview.4: 0
v5.0.0-preview.5: 5
v5.0.0-preview.6: 6
v5.0.0-preview.7: 3
v5.0.0-preview.8: 10
v5.0.0-rc.1: 9
v5.0.0-rc.2: 0
v5.0.0: 0
```

That totals up to 33. That's _closer_ but still seems fairly off. The counts that do exist also seem a bit off, but that could be my own faulty memory. I don't feel like I did 10 for preview 8 and I feel like I at least did a few in preview 2, 3, and 4.

Looking at @tmds' numbers:

```
v5.0.0-preview.2: 0
v5.0.0-preview.3: 1
v5.0.0-preview.4: 0
v5.0.0-preview.5: 3
v5.0.0-preview.6: 2
v5.0.0-preview.7: 6
v5.0.0-preview.8: 2
v5.0.0-rc.1: 1
v5.0.0-rc.2: 0
v5.0.0: 0
```

That comes out to 15. The contributor docs say 22, but I'd leave it to @tmds to say what the right number would be.

**Comment by tmds** [comment]
The number is more correct, but why is it not the same? Are these websites counting something different?

I'd prefer to see the aggregated count for .NET x.y, and not have it split across patch and preview releases.

**Comment by mairaw** [comment]
Yes, we have plans to consolidate the data under major.minor. @spboyer can comment on the difference.

**Comment by spboyer** [comment]
The most recent issue solved here was the contribution paging in the API was not implemented correctly.

moving forward these are plans to consolidate the releases to Major (maybe major.minor) and roll up the counts.

**Comment by tmds** [comment]
@spboyer feel free to close this issue when you know it is solved.

**Comment by danmoseley** [comment]
@spboyer do you have an idea of the time frame to do the rollup view? Specifically do you plan to enable anything like this for previews -- so eg for Preview 6 we could have a page for everyone that contributed since 5.0 GA up to that point?

if not I guess this can wait until 6.0 GA

**Comment by spboyer** [comment]
I endorse the idea here. There is some UI work to determine the best way to present it all. @mairaw

**Comment by tmds** [comment]
@danmoseley @richlander is there a document that list the contributors for .NET 6 release?

**Comment by danmoseley** [comment]
@tmds I do not know of one, but it would be easy to create one (a list of github handles at least). I already did the query in order to get the number of contributors and contributions for the launch events.

do you think this would be valuable, until someone works on thanks.dot.net? we could add it as a markdown to this repo. cc @richlander

**Comment by tmds** [comment]
For the previous releases there is also a contributor-list.md that is published as part of the core release-notes (https://github.com/dotnet/core/tree/main/release-notes).

It's a nice way to give visibility to the contributors of an open-source project.

**Comment by danmoseley** [comment]
I didn't actually realize that (and I agree). @rbhanda @leecow were you planning on generating another? If not I can give it a shot.

my inclination is to -- 
* omit the count of PR's (as it doesn't correlate well with impact) 
* continue to include both Microsoft and community folks on an equal basis

is that reasonable?

**Comment by mairaw** [comment]
I have a PR ready to update https://dotnet.microsoft.com/thanks

**Comment by tmds** [comment]
> omit the count of PR's (as it doesn't correlate well with impact)

I don't mind this number. It's common to see it on contributions lists.
Even if it does not reflect the impact, it is well defined what the number represents.

> continue to include both Microsoft and community folks on an equal basis

For the contributor-list that gets published in the https://github.com/dotnet/core/tree/main/release-notes, definitely.

For the Thank you website, my preference is also to include both (https://github.com/dotnet/website-thanks-data/issues/11#issuecomment-967734697).

**Comment by tmds** [comment]
I assume this has been fixed, so I'll close it.

As I put in my initial comment, I think it would also be an improvement if contributions were aggregated per major release. It would significantly reduce the number of links/buttons on the thank you site.

**Comment by mairaw** [comment]
Yes, aggregating per major/minor is on our backlog.

We'll have to continue to validate if the data is correct. If we have recent examples, we can look into it if you find any discrepancies.
