### ISSUE TITLE
Suggestion: Shorten username in windows docker containers

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/core#5683]
The default username on the windows docker containers (e.g. mcr.microsoft.com/dotnet/framework/sdk:4.8) is ContainerAdministrator, which is unusual long and leads sometimes to failing scenarios where paths become too long. One example is dealing with the temp folder which is in the container:

"C:\Users\ContainerAdministrator\AppData\Local\Temp\"

Those scenarios run well on the dev machine, because the dev machines username is mostly shorter.

I suggest to shorten the username in the windows docker containers.

**Comment by MichaelSimons** [comment]
@TFTomSun, Please open an issue in the https://github.com/microsoft/Windows-Containers repo for this.  The container users are defined in the base Windows images and would not make sense to change within the .NET images.
