### ISSUE TITLE
Couldn't find

### ISSUE THREAD

**Issue by kenjoseph1** [dotnet/core#5685]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by kenjoseph1** [comment]
![image](https://user-images.githubusercontent.com/75253099/100771314-1cb2a680-3420-11eb-8697-1cdf07ad4c60.png)

**Comment by mairaw** [comment]
Is this where you created your project? It doesn't seem that you're in the project directory. Did you run the command `cd myWebApp` as well?
