### ISSUE TITLE
Open Pages/Index.cshtml in any text editor and replace all of the code with the following, then save the file.

### ISSUE THREAD

**Issue by kwamean** [dotnet/core#5688]
_I open the text editor, but not sure where to open Pages/Index.cshtml. I will appreciate if the step is elaborate_

Step says  "Open Pages/Index.cshtml in any text editor and replace all of the code with the following, then save the file." 

I also copied the code onto a new test editor VS code and save file as Index.cshtml and run the cmd line but it did not display the changes 

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Would it help if it said something like:

"Open the Index.cshtml file in a text editor of your choice. The Index.cshtml file already exists in your project and it was created when you ran the dotnet new command. It's located in the Pages folder inside the myWebApp directory that was created earlier."
