### ISSUE TITLE
dotnet restore fails after upgrading to .NET 5

### ISSUE THREAD

**Issue by maaroen** [dotnet/core#5689]
# General
I'm trying to use dotnet restore to restore nuget packages from a private on premise azure devops 2020 nuget feed. 

I'm using the below part in a .NET Core 3.1 docker file and a .NET 5 docker file.
```
ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS \
    "{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URL}\", \"username\":\"ArtifactsDocker\", \"password\":\"${PAT}\"}]}"

ARG PROJECT_FILE
RUN dotnet restore ${PROJECT_FILE}
RUN dotnet build -c Release ${PROJECT_FILE}
RUN dotnet publish -c Release -o ./out ${PROJECT_FILE}
```

The docker build works with .NET 3.1, but after upgrading to .NET 5 it gives the following error:

```
GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate).
```

I'm using the credprovider:
```
RUN wget -qO- https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | sh

COPY . .

ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS \
    "{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URL}\", \"username\":\"docker\", \"password\":\"${PAT}\"}]}"
```

The strangest thing is that this same setup works with a .NET Core 3.1 docker image (3.1-alpine) but not with a .NET 5.0 (5.0-alpine)

Anyone has an idea what changes between .NET Core 3.1 and .NET 5.0 from this perspective? And how should the setup look like now to make this work.

**Comment by SymboLinker** [comment]
I have not yet updated to .NET 5 myself, but I read about updating NuGet to 5.8.

**Comment by maaroen** [comment]
Since I'm using .NET 5, the output of 
` dotnet nuget --version` is 
```
NuGet Command Line
5.8.0.6930
```

So it should be using NuGet 5.8

**Comment by mprigge** [comment]
Ran into this same problem - it seems there is a new way to reference a private nuget source using `dotnet nuget add source`. You no longer need the credential provider.

See: https://github.com/microsoft/artifacts-credprovider/issues/228

**Comment by carlossanlop** [comment]
The last comment seems to provide a potential solution. I'm closing this.
@maaroen feel free to reopen if you'd like to follow up.

**Comment by maaroen** [comment]
@carlossanlop You're right, that's a solution that works for now, I completely forgot about this issue, thanks for closing it!
