### ISSUE TITLE
Upgrading to DotNet 5 - CLI build and EF fails after 1 use

### ISSUE THREAD

**Issue by rolesvillesoftware** [dotnet/core#5691]
# Issue Title

Upgrading to DotNet 5 - CLI build and EF fails after 1 use

# General

Mac-Mini 2018, i5 6-Core, 64Gb Memory
byobu shell on Alacritty
Mac OS - Big Sur

Since upgrading to DotNet 5.0.100 CLI and the EF Tools 5.0.0, I can no longer build or do migrations after using the tool once. 

I am able to build once or do a migration once, but after that, I start to get errors that are not compile-time errors. 

I can build fine in Visual Studio for Mac.  
After building in Visual Studio for Mac, I can do EF migrations with the --no-build flag (why I am thinking it a build issue). 
I Still can not use the dotnet build or dotnet ef without the --no-build flag. 

Reboot does allow me to use the command once.  

Here are the errors that I am getting:

/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018: The "Csc" task failed unexpectedly. [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018: System.InvalidOperationException: The "Csc" task has not registered its resources. In order to use the "TaskLoggingHelper.FormatResourceString()" method this task needs to register its resources either during construction, or via the "TaskResources" property. [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args) [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation(Boolean condition, String resourceName, Object arg0) [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args) [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.LogErrorWithCodeFromResources(String messageResourceName, Object[] messageArgs) [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute() [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]
/usr/local/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/bryanlenihan/TiberProjects/TiberDWContext/TiberDWContext/TiberDWContext.csproj]

 
And after I get that error - all calls to dotnet ef have the following error (even when the --no-build is issued)
System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (0x8007001F)
File name: 'System.Threading.ThreadPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Diagnostics.Process.EnsureWatchingForExit()
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

If I use the --no-build, I get the above error, but the operation completes. 

Thank You for your help. 

Thanks,
Bryan Lenihan

**Comment by mairaw** [comment]
@KathleenDollard @timheuer can you help?

**Comment by timheuer** [comment]
@rolesvillesoftware is there any repo/repro we can see here? -- are you doing a restore operation explicitly before any of this?

**Comment by rolesvillesoftware** [comment]
I do not have a repo that I can share due to proprietary software; however, I did a dotnet new blazorserver and the base project (no changes) also showed the errors. 

This issue was happening with: 
dotnet restore
dotnet build
dotnet watch run
dotnet ef .anything.

If I built the application using Visual Studio for Mac - dotnet watch and dotnet ef worked until I needed a rebuild. 

It started with my Blazor app running DotNet 5.0 and then migrated to my 3.1 apps. 

Things I attempted to do:
1. Uninstall dotnet with the dotnet uninstaller script (I will have to lookup the link)
2. Reinstalled dotnet - builds started working but soon started showing the errors. 

3. I wiped my system and reinstalled Big Sur (with a disk wipe)
4. Reinstalled all the tools one at a time and everything was working as expected. 
5. Reinstalled my Virus watch program - Eset (I know that Mac supposedly do not need a virus checker, but I got hit last year with some malware)

The errors came back. 

I then removed the Virus scanner and the errors went away. 

I am tracing it down further tomorrow, but it looks like dotnet 5 cli does not like the network proxy. 

You can probably close this issue as it looks like it is an issue with Eset and not a CLI issue unless it has an issue with proxies in general (i.e. Fiddler)

Thanks for your time, 

Thanks,
Bryan Lenihan

**Comment by timheuer** [comment]
Ah, proxy may be the issue.  In Nuget you can set http_proxy setting and that may resolve (since build implicitly does a restore it may make sense it is failing there in restoring packages behind proxy)

**Comment by TomPADonaldson** [comment]
Had the same issue on Mac (Big Sur). Removed the Sophos anti-viral program, and the problem went away.

**Comment by tiberhealth** [comment]
This ended up not being a Proxy issue, but ESet or MacOS does not like the dotnet tool, especially when attempting to change the file system, such as in a restore. I added the /usr/local/share/dotnet folder to the exceptions/trusted applications list to get around the issue.  All seems to be working now - I get to use Big Surr and ESet.

**Comment by bhuwan-agarwal** [comment]
I'm facing the same error. Don't have sophos or eset but another anti-virus software. https://github.com/dotnet/msbuild/issues/6145

Not sure of the issues are related.
