### ISSUE TITLE
User Story: Package authors can validate that they didn't accidentally make an API breaking change

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5701]
Related to #5700, but focused on previous person of the same package.

- [ ] [Make PublicAPIAnalyzer support C#/binary inputs](https://github.com/dotnet/roslyn-analyzers/issues/3901)

Spec TBD

**Comment by safern** [comment]
Assigning myself as well as I will be driving this once specs are out.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
