### ISSUE TITLE
User Story: Package authors have guidance for building multi-targeted packages

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5702]
And while there are several well-established patterns for building cross-platform packages using the bait & switch approach, our guidance for building cross-platform packages is still very rudimentary. Especially with .NET 5 and the advent of operating system specific framework names we need to provide more prescriptive guidance.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
