### ISSUE TITLE
Hello i need some help

### ISSUE THREAD

**Issue by MRGODUP** [dotnet/core#5705]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I dont know what to do .Net dosent work
Keeps showing me this
![f6c845a923d42ebbf2dfef13eb6b2732](https://user-images.githubusercontent.com/61081716/101257496-6b19bb00-3728-11eb-89bd-d558a7615fce.png)

**Comment by mairaw** [comment]
Hi @MRGODUP! Did you click on the install SDK button on the tutorial? Can you run `dotnet --info` so we can see what you have installed? It seems you only have the runtime on your machine.

**Comment by MRGODUP** [comment]
> Hi @MRGODUP! Did you click on the install SDK button on the tutorial? Can you run `dotnet --info` so we can see what you have installed? It seems you only have the runtime on your machine.

Found the problem i dident install the SDK  Anyways ty for the help

**Comment by mairaw** [comment]
Given this is a common issue here, I'd love to understand how you ended up installing the runtime even though the tutorial points directly to the latest SDK. Can you help me to understand? This could help other customers that end up in a similar situation.
