### ISSUE TITLE
Problem on the microsoft tutorial ;-;

### ISSUE THREAD

**Issue by monmonerp** [dotnet/core#5711]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create#
Operating System: windows

I have this message :

It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

I tried to do the https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create tutorial ;-;

I'm on Windows and I have the 5.0.100 dotNet core :/

Thanks ^w^

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by monmonerp** [comment]
It's fine i find how to do it.
Just launch it at admin xD

**Comment by mairaw** [comment]
I'm curious about this scenario because we see some users running into this but you shouldn't need to run the commands on an admin window. Are you saying you can't run SDK commands on a regular prompt window?

**Comment by monmonerp** [comment]
Now it works without admin.  I didn't understand what happened but now it works :D

**Comment by mairaw** [comment]
You do need to open a new window so maybe when you opened the admin window, it helped.
