### ISSUE TITLE
Can't link openssl 1.0.2k on macOS 10.12.3

### ISSUE THREAD

**Issue by vladimirkrstic** [dotnet/core#572]
I get stuck with openssl 0.9.8zh preloaded with macOS which of course stops me from running .NET Core. Tried almost every workaround I've found online(all are written for macOS 10.11.xx) and could not make it work. 

With Homebrew I always get:
`Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew’s openssl.`

Can anyone help?

**Comment by bartonjs** [comment]
The instructions at https://www.microsoft.com/net/core#macos haven't involved `brew link` in quite some time.

```sh
brew update
brew install openssl
mkdir -p /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

That's the runtime directions.  If you're wanting to compile, there are some extra steps to make pkg-config happy.

**Comment by vladimirkrstic** [comment]
This is the first thing I've tried and still got 0.9.8zh in use, not the new version.

**Comment by bartonjs** [comment]
For a dotnet application, or some other application?  How do you know you're getting 0.9.8zh?  (Note that these steps are only for the openssl libraries, they don't change which openssl command line tool has preference on the path)

**Comment by vladimirkrstic** [comment]
Oh I see. Command line was referring to that version. I've thought it is connected somehow... I'm a big newb obviously. :/ Didn't even tried will .net work properly. Sorry for wasting your time, and thank you sir.

**Comment by bartonjs** [comment]
No worries, you're welcome.  I always get a bit worried that the directions don't work anymore when someone runs into trouble :smile:.
