### ISSUE TITLE
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile

### ISSUE THREAD

**Issue by ASefiani** [dotnet/core#5723]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I received this message: "myMicroservice> docker build -t mymicroservice .
**unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Users\xxx\myMicroservice\Dockerfile: Het systeem kan het opgegeven bestand niet vinden**".

**Comment by ASefiani** [comment]
The Dockerfile (.txt) was made with the mentioned code.

**Comment by mairaw** [comment]
There shouldn't be any extension on the Dockerfile. It's just Dockerfile. Let me know if this solves the issue.
