### ISSUE TITLE
.NET core 2.1 - System.TypeInitializationException

### ISSUE THREAD

**Issue by ssashok10** [dotnet/core#5724]
# .NET core 2.1 dependency injection fails

I am working on .NET Core 2.1 and .NET core 3.1 projects on my machine. All projects are working fine with .NET core 3.1. However, .NET Core 2.1 projects are failing with the below error

**MissingMethodException: Method not found: '!!0 Microsoft.Extensions.Configuration.ConfigurationBinder.Get(Microsoft.Extensions.Configuration.IConfiguration)'.**

The exact line I usually see this error is here,
**ServiceProvider.GetRequiredService<ILogger<Function>>();**

I have tried to re-install the .NET Core 2.1 SDK and re-started my machine as well. However, none of the .NET core 2.1 projects are working. I am using the "Microsoft.Extensions.Configuration" version 2.1.1. Any help will be really appreciated.

**Comment by scalablecory** [comment]
It seems like your app is built for a different SDK than what it is running under. Can you verify if that is the case?

If not, a small repro would be helpful. Thanks.
