### ISSUE TITLE
As a .NET OSS class library author, my concerns are heard

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5728]
Design a survey among .NET OSS authors to search for improvements, specifically around:

* Gaps in tooling
* Gaps in extension points, such as templates and designers
* Issues in the relationship with Microsoft, the .NET Foundation, or the ecosystem in general

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
