### ISSUE TITLE
As a .NET platform team member, I understand whether Java-style shading would be a useful feature

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5730]
We need to collect customer evidence to understand whether shading/private dependencies is a useful feature for the .NET platform.

This involves:

* Customer development to determine the scenarios this tooling would need to solve
* A document describing the problems (such as "hiding dependencies" and "side-by-side loading")
* Prototype(s) to verify that the intended solution is workable for .NET

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
