### ISSUE TITLE
Unable to get .NET 5.0.1 update via Windows Update on old Windows system.

### ISSUE THREAD

**Issue by fuchanghao** [dotnet/core#5732]
The update "2020-12 .NET 5.0.1 Update for xx"

https://www.catalog.update.microsoft.com/Search.aspx?q=2020-12%20.NET%205.0.1%20Update

I can only receive this update via Windows Update on Windows 10 20H2/Windows Server 2019.

But I can't receive this update via Windows Update on Windows Server 2008 R2（With ESU）or Windows Server 2012 R2.

I'm sure the option “Receive updates for other Microsoft products when you update Windows” stays open.

**Comment by leecow** [comment]
Adding @jamshedd who will have insight into the update offering matrix for Windows.

**Comment by jamshedd** [comment]
Server 2008 R2 is not a supported OS version for .NET 5.0, for a list of supported versions see this: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md

Server 2012 R2 is a supported platform. Supported client SKUs will receive updates via Automatic Updates, WSUS, and MU Catalog/SCCM, while Server SKUs will receive updates via WSUS and MU Catalog/SCCM. Server SKUs do not get updates pushed to them automatically since most customers want to control if/when their servers are updated.

**Comment by fuchanghao** [comment]
> Server 2008 R2 is not a supported OS version for .NET 5.0, for a list of supported versions see this: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md
> 
> Server 2012 R2 is a supported platform. Supported client SKUs will receive updates via Automatic Updates, WSUS, and MU Catalog/SCCM, while Server SKUs will receive updates via WSUS and MU Catalog/SCCM. Server SKUs do not get updates pushed to them automatically since most customers want to control if/when their servers are updated.

I test Supported OS “Windows 7 Ultimate SP1 With ESU” today, I still can't receive the ".NET 5.0.1 update" when I installed the ".NET Desktop Runtime 5.0.0"

**Comment by jamshedd** [comment]
@fuchanghao , these updates are delivered by Microsoft Update, not Windows Update. You need to opt-in specifically for receiving updates over Microsoft Update, the default if you do nothing only gives updates for the Windows OS from Windows Update. Could you confirm you have opted in to receive updates from Microsoft Update?

![image](https://user-images.githubusercontent.com/9440640/101853243-1e612600-3b14-11eb-8d95-d479da08e74d.png)

**Comment by fuchanghao** [comment]
> @fuchanghao , these updates are delivered by Microsoft Update, not Windows Update. You need to opt-in specifically for receiving updates over Microsoft Update, the default if you do nothing only gives updates for the Windows OS from Windows Update. Could you confirm you have opted in to receive updates from Microsoft Update?
> 
> ![image](https://user-images.githubusercontent.com/9440640/101853243-1e612600-3b14-11eb-8d95-d479da08e74d.png)

Some Strange bug happened 

I've got the update on windows 7 but there's another bug.

The webpage to add “enable Microsoft Update setting” in windows 7 only works with IE 11.

https://go.microsoft.com/fwlink/?LinkId=70156

Using Microsoft Edge or IE compatible mode in  Microsoft Edge can't view the page in the right way.


Also: In my Windows Server 2012 I still can't get the update even after I do “check update”

[![rAeyIH.png](https://s3.ax1x.com/2020/12/11/rAeyIH.png)](https://imgchr.com/i/rAeyIH)
[![rAesde.png](https://s3.ax1x.com/2020/12/11/rAesde.png)](https://imgchr.com/i/rAesde)
[![rAerZD.png](https://s3.ax1x.com/2020/12/11/rAerZD.png)](https://imgchr.com/i/rAerZD)
[![rAeBqO.png](https://s3.ax1x.com/2020/12/11/rAeBqO.png)](https://imgchr.com/i/rAeBqO)

**Comment by jamshedd** [comment]
This is expected. .NET Core updates are not pushed via Automatic Updates to Server SKUs, this is only applicable for client SKUs. These updates are available on WSUS or SCCM for server SKUs.

**Comment by fuchanghao** [comment]
> This is expected. .NET Core updates are not pushed via Automatic Updates to Server SKUs, this is only applicable for client SKUs. These updates are available on WSUS or SCCM for server SKUs.

OK I got it.
