### ISSUE TITLE
how hello world program is run

### ISSUE THREAD

**Issue by suraj1020** [dotnet/core#5733]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by suraj1020** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/75719903/101733940-98c68180-3ae5-11eb-9d37-b5f30ab979a2.png)
how is this run i am new

**Comment by suraj1020** [comment]
the link you provided is not working

**Comment by Rand-Random** [comment]
You should consider ditching this tutorial, and use a tutorial that is based on an IDE (integrated development environment), personally I believe that is easier to understand than typing commands and just explain it with "magic happened when you typed the commands".

A better starting point IMHO is:

if you want to use Visual Studio
https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio

Or if you want to use Visual Studio Code
https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code

-----

But to answer your question if you followed the tutorial precisely all you should have to do is type `dotnet run` into the console window.
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run

You must run this command on the location of your Program.cs file, so don't forget to call cd (change directory) to the said directory.
eg. 
`cd "C:\Users\[UserName]\myApp"`
`dotnet run`

If you want to just double click a *.exe, `dotnet run` triggered a `build` of your application and you should find a exe at this location
`C:\Users\[UserName]\myApp\bin\debug\net5.0\myApp.exe`
Notice: 
double clicking it, will only pop up a window and imidiatly close it, as the application only prints Hello World and doesn't wait for a user input, if you want to to exit the application on a key stroke of the user you have to add `Console.ReadKey();` into your `Program.cs`

**Comment by mairaw** [comment]
Thanks for the suggestion @Rand-Random.

@suraj1020 is there anything else you need to complete this tutorial?
