### ISSUE TITLE
Where is  ".NET SDK 5.0.200-preview.20601.7" - Visual Studio v16.9.0 Preview 2.0 installed it.

### ISSUE THREAD

**Issue by JeepNL** [dotnet/core#5734]
Visual Studio v16.9.0 Preview 2.0 installed ".NET SDK 5.0.200-preview.20601.7" on my Windows 10 development PC.

Normally I'd download the newest preview from here: https://github.com/dotnet/core/tree/master/release-notes/5.0 to install it on my Ubuntu 20.04 VPS to test it on Linux as well, but 5.0.200-preview.20601.7 isn't available there. The latest version I see is 5.0.1.

**Comment by JeepNL** [comment]
Today (December 22, 2020) **Windows Update** (!) installed .NET SDK 5.0.1 and **deleted**  ".NET SDK 5.0.200-preview.20601.7"

Dev. environment broke.

**Comment by JeepNL** [comment]
Accidentally closed this issue.

**Comment by joeloff** [comment]
@JeepNL This is a preview SDK that's been included in an early VS preview and it's not always published as a standalone because it targets a specific VS release.

@leecow can you confirm whether not having the standalone release of the preview SDK was intentional?

**Comment by JeepNL** [comment]
I've been running Visual Studio Preview for years now and If I remember correctly sometimes VS Preview installed a preview version of the SDK which wasn't the exact SDK that was available for download but there was never a difference in version numbers like x.0y and x.0(y+1) i.e: 5.01* -> 5.02*

With every SDK release over the past years I manually downloaded the binary .NET SDK to install on my Ubuntu VPS so I could compile/run my web apps (Blazor) on Linux. I haven't tested it yet, but I wonder if I develop apps on Windows with 5.02* SDK, if they will run on Linux 5.01* SDK. I don't transfer compiled (Linux) binaries from Windows to Linux, I compile the web app / source on Linux with the SDK installed there.

**Comment by JeepNL** [comment]
Tested: My Kestrel Hosted Blazor Wasm app developed with Visual Studio Preview .NET SDK 5.0.200-preview.20601.7 on Windows 10 compiles & runs on my Ubuntu 20.04 VPS with .NET SDK 5.0.101 installed on it without any problems. 

I don't know if this issue can be closed now, but if someone wants to close it, please do.

**Comment by leecow** [comment]
Yes, we generally don't do standalone preview releases of SDK-only updates going into VS Previews. If you need a build, you can see install options for all platforms in the table toward the bottom of the [dotnet/installer](https://github.com/dotnet/installer) page

fyi @marcpopMSFT

**Comment by JeepNL** [comment]
@leecow Thank you for your reply and the link. That answers my question so I'll close this issue.
