### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Shree92742** [dotnet/core#5739]
![Screenshot (573)](https://user-images.githubusercontent.com/69104608/101981758-1f6d9100-3c95-11eb-8df6-3c3ee1b0a468.png)

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You can use the copy button to make sure the entire command is correct. Let us know if that works for you!
