### ISSUE TITLE
don't run 

### ISSUE THREAD

**Issue by ThePackataz** [dotnet/core#5742]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What error are you getting? Can you paste a screenshot?

**Comment by ThePackataz** [comment]
> What error are you getting? Can you paste a screenshot?
