### ISSUE TITLE
Don't run 

### ISSUE THREAD

**Issue by ThePackataz** [dotnet/core#5743]
![Captura de pantalla (1)](https://user-images.githubusercontent.com/67211087/102001662-b69d0d80-3cc2-11eb-8073-48d4932152eb.png)
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
It doesn’t seem your program is compiling. Can you try running `dotnet build` to see what are the errors? Thanks!
