### ISSUE TITLE
Publishing with net50 in self-contained and single-file generates multiple files in OSX

### ISSUE THREAD

**Issue by GerardSoleCa** [dotnet/core#5752]
# Publishing with net50 in self-contained and single-file generates multiple files in OSX

When publishing a single-file and self-contained app in net5.0 for OSX it does not produce a single-file, but multiple files are written in the publish directory.

# General

I started a new project using NET50 since there was a stable release.
At the moment of publishing the executables for Linux and MacOS I decided to go through a single-file self-contained binary, so they can be distributed to Linux and OSX users without requiring the runtime.

While Linux works and successfully produces a single-file, in OSX the publishing directory contains multiple files (see examples below). 
I tried removing some of them just to test if the libraries where required or not, they are required.

Just for testing purposes, I downgraded the project to netcoreapp3.1 and tried again the publishing with self-contained and single-file for OSX. It just works as expected.

Let me show how I run the publishing command, and the resulting binaries:

```
dotnet publish katsuben/katsuben.csproj -c Release -r osx-x64 -p:PublishSingleFile=true --self-contained true
```

And the output of the previous command generates this files depending on the dotnet SDK:

#### NET50

```
/Users/_____/playground/katsuben/katsuben/bin/Release/net5.0/osx-x64/publish
katsuben                                             libSystem.Native.dylib                               libSystem.Security.Cryptography.Native.OpenSsl.dylib
katsuben.pdb                                         libSystem.Net.Security.Native.dylib                  libclrjit.dylib
libSystem.IO.Compression.Native.dylib                libSystem.Security.Cryptography.Native.Apple.dylib   libcoreclr.dylib
```

#### Netcoreapp3.1

```
/Users/_____/playground/katsuben/katsuben/bin/Release/netcoreapp3.1/osx-x64/publish
katsuben     katsuben.pdb
```

As you can see, netcoreapp3.1 generates the expected single file, while net50 does not embed the linked libraries so a single-file can't be shared to final users.

Thank you all!

**Comment by philipproplesch** [comment]
That behaviour is documented [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#other-considerations).

Setting `<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>` should give you the same behaviour as .NET Core 3.1.

**Comment by scalablecory** [comment]
Thanks @philipproplesch! Does this resolve your question, @GerardSoleCa?

**Comment by GerardSoleCa** [comment]
Hi @philipproplesch, @scalablecory and @mairaw, I've tested and it works with @philipproplesch approach.

Thanks!

**Comment by scalablecory** [comment]
Thanks for the follow-up! Closing out the issue now.

**Comment by chylex** [comment]
I have the same issue and the solution doesn't work for me. The publishing script for [this project](https://github.com/chylex/Discord-History-Tracker/tree/8f1c91b2cc7f268415d37d055cf73aa2ccf86c63) is (formatted for clarity)
```
dotnet publish Desktop
  -c Release
  -r osx-x64
  -o ./bin/osx-x64
  -p:PublishSingleFile=true
  -p:IncludeNativeLibrariesForSelfExtract=true
  -p:PublishReadyToRun=false
  -p:PublishTrimmed=true
  --self-contained true
```
and the output folder contains not just the executable, but also
```
libAvaloniaNative.dylib
libHarfBuzzSharp.dylib
libSkiaSharp.dylib
```
This is not happening on win-x64 or linux-x64.

**Comment by xecrets** [comment]
I see this is closed but I have the issue as described by @chylex , and I do wonder if that ever got resolved? All the right settings seems to be there, and it works fine for win-x64 and linux-x64, but not for osx-x64 - also with Avalonia.

**Comment by mairaw** [comment]
I'd recommend you open a new issue since the solution worked for the OP.

**Comment by luantian-terark** [comment]
@xecrets @chylex
try adding `/p:IncludeAllContentForSelfExtract=true`
