### ISSUE TITLE
Access Violation In C++/CLI Project

### ISSUE THREAD

**Issue by dign17** [dotnet/core#5753]
I created an NUnit test project depending on another C++/CLI project running with .NET Core Runtime Support (/clr:netcore) and .NET Core 3.1 target framework. There is a `ref class Class1` and another native `class Class2`. If I run the code I receive several exceptions like following:

> The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
> Exception thrown at 0x00007FF90EB5CE01 (ntdll.dll) in testhost.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
> ...
> The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
> Unhandled exception at 0x00007FF8BC361CE4 (coreclr.dll) in testhost.exe: 0xC0000005: Access violation writing location 0x000000E43DFC0E18.
> ...
> The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
> The thread 0x1d70 has exited with code -1073741819 (0xc0000005).
> ...
> The program '[22076] testhost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

The behaviour in the debugger also seems odd:
Before assigning `_pixelFormat` other variables (`_dpiX `and `_dpiY`) seem to have legit values

<p align="center">
  <img width="700" src="https://user-images.githubusercontent.com/4235489/102213365-efadcb80-3ed6-11eb-8221-01ad0f7421f6.png">
</p>

but afterwards it looks like memory was corrupted

<p align="center">
  <img width="700" src="https://user-images.githubusercontent.com/4235489/102213369-f2102580-3ed6-11eb-8bd6-91d3d09c7b35.png">
</p>

However changing `class Class2` to `ref class Class2` solves the issue:
Before `_pixelFormat` assignment

<p align="center">
  <img width="700" src="https://user-images.githubusercontent.com/4235489/102213377-f3d9e900-3ed6-11eb-91d3-dbbcf0a0e721.png">
</p>

and after

<p align="center">
  <img width="700" src="https://user-images.githubusercontent.com/4235489/102213383-f50b1600-3ed6-11eb-9bbb-f325b9e6434c.png">
</p>

So my question is whether this behaviour is inteded or a bug?

The complete project is attached here: [Project1.zip](https://github.com/dotnet/core/files/5695707/Project1.zip)

**Comment by scalablecory** [comment]
@jkoritzinsky can you help route this one?

**Comment by jkoritzinsky** [comment]
It looks like the failure is entirely in native code, so I think this should first route to the C++ team. @tgani-msft any ideas?

**Comment by tgani-msft** [comment]
Hi @dign17,

Please file an issue using the Feedback button in VS or going directly to this link:

https://developercommunity2.visualstudio.com/report?space=62&entry=problem

This is so we can properly track this issue.

**Comment by dign17** [comment]
Hi @tgani-msft,

created same issue here: https://developercommunity2.visualstudio.com/t/Access-Violation-In-CCLI-Project/1309711 (https://developercommunity.visualstudio.com/content/problem/1309711/access-violation-in-ccli-project.html)

**Comment by tgani-msft** [comment]
Thanks, I'll investigate it asap. Our initial triaging people are looking at it right now.

**Comment by carlossanlop** [comment]
Closing since the issue was routed to VS.
