### ISSUE TITLE
No templates found matching: 'webaApp'

### ISSUE THREAD

**Issue by taozui722** [dotnet/core#5756]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
The name of the template is webApp, not webaApp. Try using the copy button to make sure you have the right command. Let us know if that helps!
