### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by jethwanidhiraj** [dotnet/core#5757]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Screenshot (47)](https://user-images.githubusercontent.com/66103659/102309378-a3be5d80-3f8e-11eb-96c2-616240600015.png)
![Screenshot (48)](https://user-images.githubusercontent.com/66103659/102309386-a9b43e80-3f8e-11eb-8808-643c9c7c878e.png)

**Comment by mairaw** [comment]
It seems that you replaced the code in the Index.cshtml.cs file and not the Index.cshtml page. I’d recommend that you delete this project and start over making sure that you replace the code in the cshtml file. Let me know if that helps!

And I’m planning to add some clarification to the tutorial about this. /cc @danroth27
