### ISSUE TITLE
Add support for SLES 12.2

### ISSUE THREAD

**Issue by TheFlyingCorpse** [dotnet/core#576]
Please add support for SLES 12.2, it is needed to get powershell in a supported fashion on SLES.

Refs: https://github.com/dotnet/cli/issues/6152 and https://github.com/PowerShell/PowerShell/issues/3427

**Comment by richlander** [comment]
Check out the new platform support @ https://blogs.msdn.microsoft.com/dotnet/2017/06/28/announcing-net-core-2-0-preview-2/

You should be good now.
