### ISSUE TITLE
Can't run microservice in Docker

### ISSUE THREAD

**Issue by danorr** [dotnet/core#5760]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: linux 20.04

Was following through the tutorial write your first microservice. Everything was going well until I tried to run it in docker. Running the following command resulted in:
docker run -it --rm -p 3000:80 --name mymicroservicecontainer mymicroservice
```bash
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.1 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.0.0&arch=x64&rid=debian.10-x64
```
Manually installed dotnet 3.0.0 but had the latest version 3.0.3

Not sure what to try next.

**Comment by svick** [comment]
Based on the error message, you have a .Net Core 3.0 application, but are attempting to run it using a .Net 5.0 Dockerfile. Are you sure you have the .Net 5.0 SDK installed on your machine? You can verify that by running `dotnet --info`.

**Comment by danorr** [comment]
Hi there,

Have the following SDKs installed:

.NET SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

And the following runtimes:
.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8
[/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8
[/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3
[/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10
[/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1
[/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Cheers,
--
Daniel Orr
Lastpass - manage your passwords the easy way
<https://lastpass.com/f?3664716>

**Comment by svick** [comment]
In that case, when you run `dotnet new`, it should create a .Net 5.0 app, unless you have a `global.json` file that forces the use of .Net Core 3 SDK.

**Comment by danorr** [comment]
Yeah, that's what I did but with the dame result. I'm sure they're was a
point during the setup that I did have it running. Couldn't see a
global.json file anywhere in the project. Will give it another go.

Cheers

Dan Orr

**Comment by danorr** [comment]
Quick update. Ran a rebuild and copied the DockerFile from the previous version and everything ran as expected. Thanks for the responses. Cheers.

**Comment by mairaw** [comment]
Closing since this issue seems resolved now.
