### ISSUE TITLE
.Net Core 3.1 broke my JSON

### ISSUE THREAD

**Issue by LeslieMurphy** [dotnet/core#5766]
# Issue Title

HttpPost with FromBody was empty after upgrade

# General

My javascript was incorrectly serializing an integer field using quotes, e.g. "MystringKey":"ValueX", "MyInt":"123"

This worked just fine in .Net Core 2.2

All of a sudden it stopped working.  The framework now requires "MystringKey":"ValueX", "MyInt":123

There is evidently no way to log deserialization issues in the framework.

In the past this code worked for me to get the raw request - but that has now been broken too.

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

It would be great if the framework had a way to optionally log raw POST request bodies, and to optionally log deserialization errors.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

```
[HttpPost]
        public JsonResult CreateTable([FromBody] CreateTableRequest req)
        {
            CreateTableResponse r = new CreateTableResponse();

            if (req == null)
            {
                r.Error = true;
                r.Message = $"Internal Error. Invalid CreateTable input - unable to process request parameters";
                // THIS LOGGING OF RAW request now ONLY WORKS IF THE JSON CAN BE PARSED OK as of .Net Core 3.1!
                // as of .Net Core 3.1 this does not work "AutoDetectRowsToExamine":"200"
                // must be "AutoDetectRowsToExamine":200
                var m = new MemoryStream();
                Request.Body.Position = 0;  // Always fails as of .Net Core 3.1
                Request.Body.CopyTo(m);
                var rawRequest = System.Text.Encoding.UTF8.GetString(m.ToArray());
                _logger.LogError($"CreateTable deserialization failed for Json {rawRequest}");

```
For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by dasMulli** [comment]
The [Migration Guide](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#newtonsoftjson-jsonnet-support) contains details on how to still use the Newtsonsoft.Json based serialization in <3.0 or the guide [How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0) which has a dedicated section [Allow or write numbers in quotes](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#allow-or-write-numbers-in-quotes) for setting up a compatible behavior.

**Comment by scalablecory** [comment]
Looks like this was answered. Thanks for the question!
