### ISSUE TITLE
I couldn't install Dockerhub correctly

### ISSUE THREAD

**Issue by Hessam-vakil** [dotnet/core#5772]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install-docker
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Screenshot 2020-12-19 094017](https://user-images.githubusercontent.com/3979193/102682402-7962df00-41de-11eb-8442-292e10e2661b.png)

**Comment by mairaw** [comment]
You'd have to follow up with the Docker team on that. It seems similar to https://github.com/docker/cli/issues/2911.

**Comment by Hessam-vakil** [comment]
> 
> 
> You'd have to follow up with the Docker team on that. It seems similar to [docker/cli#2911](https://github.com/docker/cli/issues/2911).

Thanks a lot🙏
