### ISSUE TITLE
i have a error for installing net framework

### ISSUE THREAD

**Issue by shyamal-w** [dotnet/core#5779]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dikeshkumr135** [comment]
could you provide the error details?

**Comment by mairaw** [comment]
The tutorial is for you to learn about programming using .NET 5. If you need to install .NET Framework, you should go to https://dotnet.microsoft.com/download/dotnet-framework. 

What is the error you're getting?
