### ISSUE TITLE
 CS0105:     .NET toturial Hello World

### ISSUE THREAD

**Issue by habmat** [dotnet/core#5782]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit 
Operating System: linux

console.log:
CS0105: The using directive for 'System' appeared previously in this namespace

**Comment by mairaw** [comment]
You should make sure you don't have the using System; directive twice on your code like shown at https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0105

Can you paste the contents of your Program.cs file? It needs to look exactly like the code shown at https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
