### ISSUE TITLE
No templates matched the input template name: blazorserver.

### ISSUE THREAD

**Issue by ips138** [dotnet/core#5783]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by svick** [comment]
Are you sure you installed the .Net 5.0 SDK in the previous step? What is the output of `dotnet --info` for you?

**Comment by mairaw** [comment]
Let us know the output of `dotnet --info` so we can try to help you.
