### ISSUE TITLE
CLI Known Issues

### ISSUE THREAD

**Issue by mairaw** [dotnet/core#579]
We link to this topic from our docs:
https://github.com/dotnet/core/blob/master/cli/known-issues.md

Does it need to be updated for the latest version?

**Comment by richlander** [comment]
Good q! @mairaw, all known issues are recorded in the .NET Core release notes. We shouldn't use the link above for anything anymore.

@leecow Can you retire the cli known issues page?

**Comment by leecow** [comment]
@richlander @mairaw - seems like we could remove https://github.com/dotnet/core/tree/master/cli entirely?

**Comment by richlander** [comment]
Ya. Are all of those known issues captured in our 1.0 preview 2 known issues? We might just copy that whole file beside the 1.0 preview 2 release notes and link from it. yes?

**Comment by mairaw** [comment]
Sounds good. Should we also add the link to each Known Issues file from [here](https://github.com/dotnet/core/tree/master/release-notes)?

**Comment by mairaw** [comment]
also, is there a place where you have the full OS support matrix? We do link to this [one](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.md) but then for 2.0, only macOS 10.12 is supported not 10.11 correct?

**Comment by leecow** [comment]
Moved to https://github.com/dotnet/core/blob/master/release-notes/1.0/cli-known-issues.md and looks like all issues are captured in the 1.0 known issues doc. 

Complete OS matrix per Core version is at https://github.com/dotnet/core/blob/master/roadmap.md.

**Comment by Petermarcu** [comment]
I think this is done and I'm going to close it.
