### ISSUE TITLE
Learning about app

### ISSUE THREAD

**Issue by WebWiz23** [dotnet/core#5793]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Hello. My name is Mory. I am trying to experiment with .NET. I tried to run the "dotnet new console -0 myApp" does not work.
Is there any way to fix this? Here https://www.awesomescreenshot.com/video/2198595

**Comment by dikeshkumr135** [comment]
I cannot see the screenshot you have shared, but the command you are trying to run is not correc.
You are using `dotnet new console -0 myApp` it should not be -0(zero) it should be -o(output). 
So, the command you want to run is `dotnet new console -o myApp`
You can run `dotnet new -o --help` to know more about the commands.

**Comment by mairaw** [comment]
You can also try using the copy button on the website so you have the exact command. Closing since this has been answered, but let us know if you need more help.
