### ISSUE TITLE
Roadmap intro should be updated

### ISSUE THREAD

**Issue by svick** [dotnet/core#580]
The first paragraph of [the roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) document says:

> Our primary focus is to get the .NET Core 1.0 tooling to RTM quality for the Visual Studio 2017 RTM ([please try the 2017 RC update][vs2017-rc] we shipped with improvements in this area).

This is clearly not up to date and I think it should be updated.

[vs2017-rc]: https://blogs.msdn.microsoft.com/dotnet/2016/12/12/updating-visual-studio-2017-rc-net-core-tooling-improvements/

**Comment by svick** [comment]
Fixed by https://github.com/dotnet/core/pull/581.

**Comment by DominikDitoIvosevic** [comment]
Could we maybe also get more exact dates/months for the preview?  Q2 started this month right?
