### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Skypad-yt** [dotnet/core#5800]
'dotnet' is not recognized as an internal or external commandI ran into an issue

**Comment by DylanGTech** [comment]
Sounds like you had an issue installing it. Could you provide more details? Otherwise we won't know what is wrong or how we can help, assuming this is a problem with the dotnet code at all.

**Comment by mairaw** [comment]
Please give us more information like OS, which version you tried to install, etc. Sometimes, opening a new command prompt or terminal window after installation also helps.
