### ISSUE TITLE
C:\Users\Camila\OneDrive\Documentos\C#\exercicio.cs(7,21): error CS0017: Programa tem mais de um ponto de entrada definido. Compilar com /main para especificar o tipo que contém o ponto de entrada. [c:\Users\Camila\OneDrive\Documentos\C#\C#.csproj]  Ocorreu uma falha no build. Corrija os erros de build e execute novamente.

### ISSUE THREAD

**Issue by itsmyllaa** [dotnet/core#5802]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Oi @itsmyllaa! Parece que o seu programa tem mais de um método Main definido. Você pode colar o conteúdo do seu arquivo Program.cs aqui?
Ele deveria estar igual ao que é mostrado aqui: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
