### ISSUE TITLE
https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-ubuntu#1804-

### ISSUE THREAD

**Issue by Funny-dot** [dotnet/core#5803]
gn:14 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main i386 Packages
Ign:15 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
Ign:16 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main Translation-en_US
Ign:17 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main Translation-en
Fetched 7,883 B in 22s (354 B/s)
Reading package lists... Done
W: GPG error: http://download.virtualbox.org/virtualbox/debian xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A2F683C52980AECF
W: The repository 'http://download.virtualbox.org/virtualbox/debian xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mairaw** [comment]
What is this about @Funny-dot?

**Comment by Funny-dot** [comment]
It's settled. Thank you.

**Comment by scalablecory** [comment]
Glad to hear you resolved this! Thanks for following up.
