### ISSUE TITLE
its still running incremented by 1 and not 10

### ISSUE THREAD

**Issue by GoodspeedAmar** [dotnet/core#5811]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmosemsft** [comment]
@GoodspeedAmar are you still having trouble?

**Comment by mairaw** [comment]
Can you double check that you made the changes and ran the same project?

Maybe paste the contents of your Counter.razor and Index.razor files so we can try to help.

**Comment by GoodspeedAmar** [comment]
yes . I made the changes and now its running fine.
Thank you
Amar.

**Comment by danmosemsft** [comment]
Great!
