### ISSUE TITLE
dotnet core 5 and blazor install issue

### ISSUE THREAD

**Issue by edippity** [dotnet/core#5816]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Device name	
Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	
Product ID	00330-80000-00000-AA108
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	20H2
Installed on	‎8/‎28/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

I have installed the dotnet core 5.0 sdk (dotnet-sdk-5.0.101-win-x64.exe) but cannot get it to work.  When i run **dotnet --version** in powershell, it returns
**3.1.302** 
and i do not see 
dotnet core 5.0.  When i try to run a .net core 5 project in Visual Studio 2019, i get 
**Error	MSB3644	The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	BlazorMovies.Shared	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1180**

**When i run dotnet --list-sdks...**
C:\WINDOWS\system32>dotnet --list-sdks
Tracing enabled @ Tue Jan  5 14:08:34 2021 GMT
--- Invoked dotnet [version: 5.0.1, commit hash: b02e13abab3d6f499751af2ad1ae6333fb4e633d] main = {
dotnet
--list-sdks
}
Reading fx resolver directory=[C:\Program Files (x86)\dotnet\host\fxr]
Considering fxr version=[3.1.6]...
Considering fxr version=[5.0.1]...
Detected latest fxr version=[C:\Program Files (x86)\dotnet\host\fxr\5.0.1]...
Resolved fxr [C:\Program Files (x86)\dotnet\host\fxr\5.0.1\hostfxr.dll]...
Loaded library from C:\Program Files (x86)\dotnet\host\fxr\5.0.1\hostfxr.dll
Invoking fx resolver [C:\Program Files (x86)\dotnet\host\fxr\5.0.1\hostfxr.dll] hostfxr_main_startupinfo
Host path: [C:\Program Files (x86)\dotnet\dotnet.exe]
Dotnet path: [C:\Program Files (x86)\dotnet\]
App path: [C:\Program Files (x86)\dotnet\dotnet.dll]
Tracing enabled @ Tue Jan  5 14:08:34 2021 GMT
--- Invoked hostfxr_main_startupinfo [commit hash: b02e13abab3d6f499751af2ad1ae6333fb4e633d]
Checking if CoreCLR path exists=[C:\Program Files (x86)\dotnet\coreclr.dll]
--- Executing in muxer mode...
Using the provided arguments to determine the application to execute.
Application '--list-sdks' is not a managed executable.
Multilevel lookup is true
Gathering SDK locations in [C:\Program Files (x86)\dotnet]
Found SDK version [3.1.302]
3.1.302 [C:\Program Files (x86)\dotnet\sdk]

**Comment by mairaw** [comment]
What version of Visual Studio do you have?

You need Visual Studio 16.8.3 or later versions to run .NET 5 projects.
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by edippity** [comment]
Hello,

Version 16.8.3. I fixed the issue by installing the 32 bit version of net core 5.0.1.  The installation through visual studio installer installs the 64 bit version and it fails to work.

Thanks.

**Comment by mairaw** [comment]
This is odd given you mentioned your system was x64. Maybe VS should also be installed as x64? By the path it shows in your description, it seems you installed the x86.

**Comment by edippity** [comment]
I think Visual Studio is only 32 bit.

**Comment by mairaw** [comment]
My bad, yeah. 64-bit is coming with VS 2022.

I'll close the issue since you resolved the problem, even though I find it odd that you'd need to install the 32-bit version of the SDK. You didn't install the SDK through the VS installer, then?
