### ISSUE TITLE
How to "System call"?

### ISSUE THREAD

**Issue by leecow** [dotnet/core#5818]
---
**Issue moved from microsoft/dotnet#1283**
- Please respond to @BenLampson.

---

_From @BenLampson on Thursday, December 24, 2020 9:55:36 AM_

How to "System call"????
Is the Dotnet has some API to do this?
Or I need to use PINVOKE?

**Comment by danmosemsft** [comment]
@benlampson to call into a native library, or the system, you do need to do a pinvoke. It's essentially the same on Unix as it is on Windows .

Here's some docs https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke
There are many examples in dotnet/runtime, eg., https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/Interop/Unix/System.Native/Interop.ChMod.cs

**Comment by BenLampson** [comment]
Thx~
