### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by dd3825** [dotnet/core#5821]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\>dotnet new console -0 myApp
Couldn't find an installed template that matches the input, searching online for one that does...
Invalid input switch:
  -0
  myApp
For a list of valid options, run 'dotnet new console --help'.

WINDOWS 64BIT

**Comment by uffebjorklund** [comment]
@dd3825 do not use `-0` (zero) instead use `-o` (for output)
`dotnet new console -o myApp`

**Comment by dd3825** [comment]
Awesome Thank you
