### ISSUE TITLE
Release build runs extremely slowly on MacOS.

### ISSUE THREAD

**Issue by rootVIII** [dotnet/core#5828]
# Release build runs extremely slowly on MacOS.

# General

First of all thank you for bringing dotnet to Mac and Linux. I find this very exciting. Unfortunately any build that I create runs fairly slowly on an Intel-cpu Mac (both Debug and Release).  My apologies in advance if my below commands are the reason for this (I'm new to C# and the dotnet CLI).

I was creating a very simple OOP example in C# to get a feel for the language and decided to build it to Release just to see what a final product might be like.

```
using System;

namespace Practice
{
    class Practice
    {
        public string[] DOMs;

        public Practice(string[] doms)
        {
            DOMs = doms;
        }

        public string Test() => DOMs[0];
    }

    class PracticeClient
    {
        static void Main(string[] args)
        {
            string[] domains =
            {
                "www.unc.edu", "www.umb.edu", "www.harvard.edu",
                "www.cornell.edu", "www.psu.edu", "www.cam.ac.uk",
                "www.umass.edu", "www.mit.edu", "www.unimelb.edu.au",
            };

            Practice p = new Practice(domains);
            Console.WriteLine(p.Test());
        }
    }
}
```

And here is how I am creating and running the Release:

```
solsticenet@mm1 Practice % ls bin/  
Debug
solsticenet@mm1 Practice % dotnet build -c Release
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Practice -> /Users/solsticenet/VisualStudioProjects/Practice/bin/Release/net5.0/Practice.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.03


solsticenet@mm1 Practice % time dotnet run bin/Release/net5.0/Practice.dll
www.unc.edu
dotnet run bin/Release/net5.0/Practice.dll  1.62s user 0.32s system 134% cpu 1.442 total
```

That 1.62s feels _extremely_ long to me, especially for a program that is basically as simple as a hello world.

For example the same program (roughly) in python:

```
class Practice:
    def __init__(self, doms):
        self.doms = doms

    def test(self):
        return self.doms[0]


if __name__ == '__main__':
    domains = [
        "www.unc.edu", "www.umb.edu", "www.harvard.edu",
        "www.cornell.edu", "www.psu.edu", "www.cam.ac.uk",
        "www.umass.edu", "www.mit.edu", "www.unimelb.edu.au"
    ]
    print(Practice(domains).test())
```

and then console output:

```
solsticenet@mm1 Practice % time python3 practice.py
www.unc.edu
python3 practice.py  0.02s user 0.01s system 89% cpu 0.027 total
```

Am I missing something? Why is a compiled Release build more than 1s slower than the interpreted Python version? Perhaps I am not building to Release correctly? I feel like this sort of simple program should be finished executing before my finger has even been released from the Return key (ie: 0.02s).

Again, my apologies if I am not creating the Release build correctly.

**Comment by omajid** [comment]
Can you also run:

    time dotnet bin/Release/net5.0/Practice.dll

If that's results in a speed that you like, then please use that over `dotnet run`. `dotnet run` actually runs the compiler to rebuild your application behind the scenes.

**Comment by rootVIII** [comment]
Ah thank you. That is much better:

```
solsticenet@mm1 Practice % time dotnet bin/Release/net5.0/Practice.dll 
www.unc.edu
dotnet bin/Release/net5.0/Practice.dll  0.05s user 0.02s system 112% cpu 0.064 total
```

Closing now thanks.
