### ISSUE TITLE
.Net Core -> Crystal Report

### ISSUE THREAD

**Issue by premlad** [dotnet/core#5830]
How to create a Crystal Report in .Net Core ...?

**Comment by scalablecory** [comment]
You may need to consult documentation for Crystal Reports -- this is not a part of the .NET Core product.

**Comment by premlad** [comment]
Yes I know Sir that Crystal Report is not a part of .Net Core Product. But If I am hosting on Windows Server is it possible to configure with it as I didn't find any proper solutions for it....?????
