### ISSUE TITLE
This project is not building

### ISSUE THREAD

**Issue by mmadushanka** [dotnet/core#5834]
This is what I got when build the microservice

 => [internal] load build definition from Dockerfile                                                               0.6s
 => => transferring dockerfile: 2B                                                                                 0.0s
 => [internal] load .dockerignore                                                                                  0.9s
 => => transferring context: 34B                                                                                   0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount046231930/Dockerfile: no such file or directory

And when I check for docker images running , nothing showed,

REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

E:\\Test-pro\myMicroservice>docker run -it --rm -p 3000:80 --name mymicroservicecontainer mymicroservice

Unable to find image 'mymicroservice:latest' locally
docker: Error response from daemon: pull access denied for mymicroservice, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

My Docket file is 

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY myMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]

Should I change the SDK version to 3.1 here as well ? I have .net core 3.1

**Comment by scalablecory** [comment]
@MichaelSimons can you help here?

**Comment by mmadushanka** [comment]
Hi Cory,


That project I referenced is not building.

https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create.

I think I have provided details in the github link, in the issues section.


Manula

**Comment by MichaelSimons** [comment]
@mmadushanka, Can you share what command you are using to build your Dockerfile.  What directory are you executing the command in and where is your Dockerfile.  It appears that Docker is not finding your Dockerfile.

**Comment by mmadushanka** [comment]
Hi Michael,

This is the command that I used o build the dockerfile

docker build -t mymicroservice .

It is same the command you provide in the example.

Yes, I think my docker file is not found by docker.
My .net  sdk version is .net core 3.1.
Is there any version mismatch here with the included version of the exmaple dockerfile.?

**Comment by MichaelSimons** [comment]
Where is your Dockerfile located in reference to where to are running the `docker build` command?

If you want to use .NET Core 3.1 then you will need to change the two FROM instructions in the Dockerfile to reference `3.1` images versus the `5.0` images.  I don't think this is related to the issue you are currently encountering though.

**Comment by mmadushanka** [comment]
Here what I just did is follow, these flow to create an microservice and run it with docker.
There is a folder call mymicroservice in the local drive where the microservice and dockerfile is located, 
I have run these commands in the command prompt, pointing to the root folder ( mymicroservice) to run the service.
1). Service ran properly as in the example.
2), Then I added the dockerfile and dockerignor to the same folder, as following the instructions.
( My .net core version is 3.1, but I could that the sample dot net sdk version is .net 5, I think.)
( Docker version 20.10.2, build 2291f61)
3). Then I am trying to create the docker image.
so I got this error :
[ 
 Building 1.6s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                               1.8s
 => => transferring dockerfile: 2B                                                                                 0.3s
 => [internal] load .dockerignore                                                                                  1.3s
 => => transferring context: 34B                                                                                   0.2s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount365263377/Dockerfile: no such file or directory

]

Could not be able to create the docker image.
So the rest of the commands would not work.

Why could not I be able to create the dcoker image ?  Is that .net verion error or some configutation issue ?

**Comment by mairaw** [comment]
The tutorial assumes you have .NET 5 SDK, otherwise the Dockerfile shown needs to be tweaked.

**Comment by MichaelSimons** [comment]
@mmadushanka, Can you validate that you have a working Docker environment?  

Create a `Dockerfile` with the following contents:

```dockerfile
FROM alpine:3.12

ENTRYPOINT echo 'Hello World!'
```

Build it by running the following cmd in the same directory as the Dockerfile: `docker build --pull -t hello-world .`

Run the resulting image with the following cmd:  `docker run --rm hello-world`

**Comment by carlossanlop** [comment]
No response in 20 days. Closing.
