### ISSUE TITLE
.NET Core January 2021 Update - 5.0.2, 3.1.11, 2.1.24

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5838]
Release Notes 
[5.0.2](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.2/5.0.2.md)
[3.1.11](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.11/3.1.11.md)
[2.1.24](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.24/2.1.24.md)

Please report any issues you find with .NET 5.0.2, .NET Core 3.1.11 or .NET Core 2.1.24, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.2 | 3.1.11 | 2.1.24 
|--|--|--|--|
| Ubuntu 16.04  | ✅  | ✅  | ✅  |
| Ubuntu 18.04  |✅  | ✅  | ✅  |
| Ubuntu 20.04  | ✅  | ✅  | ✅  |
| Ubuntu 20.10  | ✅  | ✅  | ✅  |
| Centos 7    | ✅  | ✅  | ✅  |
| Debian 9    | ✅  | ✅  | ✅  |
| Debian 10    | ✅  | ✅ | ✅  |
| Fedora 32  |✅  | ✅   | ✅ |
| Fedora 33   |✅  | ✅  | ✅  |
| OpenSUSE 15  |✅  | ✅  | ✅ |
| SLES 12     | ✅  | ✅  | ✅  |
| SLES15  | ✅  | ✅  | ✅  |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with the January 2020 release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [ ] Issue with installing .NET Core 3.1.405 SDK on some Linux machines. https://github.com/dotnet/core/issues/5838#issuecomment-759129031 
Workaround: https://github.com/dotnet/core/issues/5838#issuecomment-759756016

- [x] GitHub core repos tagging is taking longer than expected. ETA - EOD (14th Jan 2021)
 Workaround: https://github.com/dotnet/core/issues/5838#issuecomment-760197914
Update:  Tagging for all January releases is complete.

**Comment by nealrowan** [comment]
Hi 

When doing an a install on centos server i getting the below, is the package correct?

Running transaction
  Installing : dotnet-sdk-3.1-3.1.405-1.x86_64
Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;5ffe3fd9: cpio: read
  Verifying  : dotnet-sdk-3.1-3.1.405-1.x86_64

Failed:
  dotnet-sdk-3.1.x86_64 0:3.1.405-1

**Comment by rbhanda** [comment]
> Hi
> 
> When doing an a install on centos server i getting the below, is the package correct?
> 
> Running transaction
> Installing : dotnet-sdk-3.1-3.1.405-1.x86_64
> Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
> error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;5ffe3fd9: cpio: read
> Verifying : dotnet-sdk-3.1-3.1.405-1.x86_64
> 
> Failed:
> dotnet-sdk-3.1.x86_64 0:3.1.405-1

Looking
Which version of Centos are you using?

**Comment by nealrowan** [comment]
centos 7.9 

performing a normal 'sudo yum -y install dotnet-sdk-3.1'

it failed in our build pipeline which creates a image, so was just doing some diagnostics when saw new release was made.

**Comment by nealrowan** [comment]
> > Hi
> > When doing an a install on centos server i getting the below, is the package correct?
> > Running transaction
> > Installing : dotnet-sdk-3.1-3.1.405-1.x86_64
> > Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
> > error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;5ffe3fd9: cpio: read
> > Verifying : dotnet-sdk-3.1-3.1.405-1.x86_64
> > Failed:
> > dotnet-sdk-3.1.x86_64 0:3.1.405-1
> 
> Looking
> Which version of Centos are you using?

centos 7.9

performing a normal 'sudo yum -y install dotnet-sdk-3.1'

it failed in our build pipeline which creates a image, so was just doing some diagnostics when saw new release was made.

**Comment by rbhanda** [comment]
> > > Hi
> > > When doing an a install on centos server i getting the below, is the package correct?
> > > Running transaction
> > > Installing : dotnet-sdk-3.1-3.1.405-1.x86_64
> > > Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
> > > error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;5ffe3fd9: cpio: read
> > > Verifying : dotnet-sdk-3.1-3.1.405-1.x86_64
> > > Failed:
> > > dotnet-sdk-3.1.x86_64 0:3.1.405-1
> > 
> > 
> > Looking
> > Which version of Centos are you using?
> 
> centos 7.9
> 
> performing a normal 'sudo yum -y install dotnet-sdk-3.1'
> 
> it failed in our build pipeline which creates a image, so was just doing some diagnostics when saw new release was made.

We tested on Centos 7 and not able to repro this issue. The files seems fine on the feed as well.

**Comment by rbhanda** [comment]
@nealrowan can you Ping packages.microsoft.com from the problematic machine? I would like to see if the package is corrupted in some other mirror which I am not able to hit.

**Comment by nealrowan** [comment]
> @nealrowan can you Ping packages.microsoft.com from the problematic machine? I would like to see if the package is corrupted in some other mirror which I am not able to hit.

resolving to sd-apt-sea-d-1.southeastasia.cloudapp.azure.com

might be something with way I have setup the repos, 
starting with a blank image and follow the guide, and using just 1 repo it seams to work, but doing similar in full builds its failing. 

where it has been working for 6+ months. doing more digging

**Comment by maxhamulyak** [comment]
Did the release strategy change for net5 as oposed to netcore3.1? (Microsoft.Extensions.*)
For example all packages were updated each time 3.1.9->3.1.10. But for the 5.* invariant not all packages are updated. For example not all FileProvider packages are updated. My team uses MSbuild property to set versions for things like package version, which breaks if not all packages are updated

**Comment by tahazayed** [comment]
Under this url https://dotnet.microsoft.com/download/dotnet/5.0 
This section Build apps - SDK -> SDK 5.0.102 -> Language support
C# 8.0
F# 4.7
Visual Basic 15.9

I think it should be
C# 9.0
F# 5.0
Visual Basic 15.9

**Comment by ebekker** [comment]
We're seeing the same error as @nealrowan on Amazon Linux 2 based images.

Package server resolves to:  `sd-apt-eus-d-1.eastus.cloudapp.azure.com (13.90.21.104)`

**Comment by n0mn0m** [comment]
Running into this on Amazon Linux 2 images hosted in `us-east-1` today. 

I get this when pinging `packages.microsoft.com`

```bash
sh-4.2$ ping packages.microsoft.com
PING csd-apt-eus-d-3.eastus.cloudapp.azure.com (13.90.56.68) 56(84) bytes of data.

--- csd-apt-eus-d-3.eastus.cloudapp.azure.com ping statistics ---
86 packets transmitted, 0 received, 100% packet loss, time 87045ms
```

This had been working for a few months:

```bash
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
sudo yum -y install dotnet-sdk-3.1
```

But started getting this error today (1/13/2021 noticed around 7AM EST and started looking into this):

```bash
dotnet-sdk-3.1-3.1.405-1.x86_64                            10/10Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
...
error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;5fff0d
...
netstandard-targeting-pack-2.1.x86_64 0:2.1.0-1
Failed:
dotnet-sdk-3.1.x86_64 0:3.1.405-1
```

**Comment by bgrainger** [comment]
Some of the download links in https://github.com/dotnet/announcements/issues/171 are incorrect.

> .NET Core 3.1.11 and .NET SDK 3.1.111 (Release Notes | Download)

"Download" links to https://dotnet.microsoft.com/download/dotnet/3.1 but it should be https://dotnet.microsoft.com/download/dotnet-core/3.1

> .NET Core 2.1.24 and .NET SDK 2.1.520 (Release Notes | Download)

"Download" links to https://dotnet.microsoft.com/download/dotnet/2.1 but it should be https://dotnet.microsoft.com/download/dotnet-core/2.1

**Comment by gustavomcastro** [comment]
Hi,

Running into this on Amazon Linux 2 images, failed unpackage sdk. see image below

![image](https://user-images.githubusercontent.com/25613651/104509807-f4929780-55c8-11eb-8d1a-6d54aa29d226.png)

Commands Docker File

```
RUN yum update -y && \
 yum -y install dotnet-sdk-3.1 && \
yum clean all
```

Temporary Solution

Installed and Run dotnet with manual install

https://docs.microsoft.com/pt-br/dotnet/core/install/linux-scripted-manual#manual-install

**Comment by nealrowan** [comment]
> We're seeing the same error as @nealrowan on Amazon Linux 2 based images.
> 
> Package server resolves to: `sd-apt-eus-d-1.eastus.cloudapp.azure.com (13.90.21.104)`



> Running into this on Amazon Linux 2 images hosted in `us-east-1` today.
> 
> I get this when pinging `packages.microsoft.com`
> 
> ```shell
> sh-4.2$ ping packages.microsoft.com
> PING csd-apt-eus-d-3.eastus.cloudapp.azure.com (13.90.56.68) 56(84) bytes of data.
> 
> --- csd-apt-eus-d-3.eastus.cloudapp.azure.com ping statistics ---
> 86 packets transmitted, 0 received, 100% packet loss, time 87045ms
> ```
> 
> This had been working for a few months:
> 
> ```shell
> sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
> sudo yum -y install dotnet-sdk-3.1
> ```
> 
> But started getting this error today (1/13/2021 noticed around 7AM EST and started looking into this):
> 
> ```shell
> dotnet-sdk-3.1-3.1.405-1.x86_64                            10/10Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
> ...
> error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;5fff0d
> ...
> netstandard-targeting-pack-2.1.x86_64 0:2.1.0-1
> Failed:
> dotnet-sdk-3.1.x86_64 0:3.1.405-1
> ```

check if you also have the rhel repo added, if I remove this repo and just have centos one it works for 3.1 & 2.1 but has issues if both exist, 

It looks like its using dotnet-runtime-deps-3.1.11-rhel.7-x64.rpm instead of dotnet-runtime-deps-3.1.11-centos.7-x64.rpm  when both repos are added. 

but in turn need to add the redhat repo, so can other microsoft tools eg powershell, so doing add & remove in build process

**Comment by ebekker** [comment]
@nealrowan, thanks for the tip.  Not happy about this approach, though -- we need to keep both repos around as well, for PWSH and MSSQL tools, so not crazy about this kludgey approach.

**Comment by gongomgra** [comment]
Hi,

Where can I get the source code for version 5.0.2? I can't find the `v5.0.2` tag here. Is there any other location for this?

Thanks!

**Comment by joancafom** [comment]
+1 to @gongomgra I couldn't find that tag either in https://github.com/dotnet/aspnetcore either.

**Comment by gustavomcastro** [comment]
@gongomgra you can downlod package in https://dotnet.microsoft.com/download/dotnet/5.0 and make manual install temporarily, for exemplo i make this

> Hi,
> 
> Running into this on Amazon Linux 2 images, failed unpackage sdk. see image below
> 
> ![image](https://user-images.githubusercontent.com/25613651/104509807-f4929780-55c8-11eb-8d1a-6d54aa29d226.png)
> 
> Commands Docker File
> 
> ```
> RUN yum update -y && \
>  yum -y install dotnet-sdk-3.1 && \
> yum clean all
> ```
> 
> **Temporary Solution**
> 
> Installed and Run dotnet with manual install, worked for me
> 
> https://docs.microsoft.com/pt-br/dotnet/core/install/linux-scripted-manual#manual-install
> 
> Using Docker:
> 
> DockerFile
> 
> ```shell
> RUN tar zxf dotnet-sdk-3.1.404-linux-x64.tar.gz -C "/tmp/dotnet"
> ENV DOTNET_ROOT /tmp/dotnet
> ENV PATH $PATH:/tmp/dotnet
> ```

**Comment by gongomgra** [comment]
Thanks for your reply. However, I can't find the source code in that website either. I'd like to build .NET core from source, but I can't find it for `v5.0.2`. Do you know if adding the tag was a missing step for this release? Are there any plans to tag this new release?

**Comment by rbhanda** [comment]
Hello @gongomgra , 5.0.2 release has been tagged.

**Comment by gongomgra** [comment]
@rbhanda Thank you so much!

**Comment by omajid** [comment]
Hey, @gongomgra if you really want to build all of .NET Core from source (sdk, runtime, ASP.NET Core), take a look at https://github.com/dotnet/source-build. A release hasn't been tagged, but `master` branch currently corresponds to SDK `5.0.102`

**Comment by gortok** [comment]
@rbanda the release notes link on the ["Releases" page](https://github.com/dotnet/core/releases) for 5.0.2 results in a 404. Here is the correct URL:

https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.2/5.0.2.md

**Comment by sam-cogan** [comment]
Any update on this? Installing any version dotnet core 3.1 using Yum seems broken:

`Total download size: 68 M
Installed size: 184 M
Is this ok [y/d/N]: y
Downloading packages:
dotnet-sdk-3.1.405-x64.rpm                                                                                                                                                                                                                                                                                                                                         |  68 MB  00:00:02
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : dotnet-sdk-3.1-3.1.405-1.x86_64                                                                                                                                                                                                                                                                                                                                        1/1
Error unpacking rpm package dotnet-sdk-3.1-3.1.405-1.x86_64
error: unpacking of archive failed on file /usr/share/dotnet/templates/3.1.12/microsoft.dotnet.web.projecttemplates.3.1.3.1.11.nupkg;6006e986: cpio: read
  Verifying  : dotnet-sdk-3.1-3.1.405-1.x86_64                                                                                                                                                                                                                                                                                                                                        1/1

Failed:
  dotnet-sdk-3.1.x86_64 0:3.1.405-1`

**Comment by xobob** [comment]
Does the Hosting Bundle include the .NET Core runtime or does it not?

note 2 at https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.11/3.1.11.md says "2. For hosting stand-alone apps on Windows Servers. Includes the ASP.NET Core Module for IIS and _can be_ installed separately on servers **without** installing .NET Core runtime."

this seems to conflict with

the documentation on the download page https://dotnet.microsoft.com/download/dotnet-core/3.1 says the .NET Core Runtime IS included in the Hosting Bundle "On Windows, we recommended installing the Hosting Bundle, **which includes** the .NET Core Runtime and IIS support."

**Comment by mairaw** [comment]
@rbhanda @leecow to help with the question from @xobob - maybe the note on the release notes is not super clear. Maybe it means you don't have to install the .NET Core runtime separately because it's already included in the bundle?

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/5932
