### ISSUE TITLE
.NET Interactive supports the basic requirements for notebook-based learning tasks

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5843]
### Summary

As a student, I can use .NET Interactive in a notebooks environment to perform the essential tasks I need for notebook-based learning.

### Details

"Essential tasks" include:

* Editing and executing code in cells, such as in a jupyter notebook
* Good formatting of output when evaluating code
* Ability to do visualizations with a charting library
* Ability to see documentation/hover text, such as inspecting the XML documentation for a type in a package I'm using

Additionally, there may be some magic commands relevant to my learning, such as `%%time` to time the output of some code. But these aren't necessarily essential for learning tasks.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
