### ISSUE TITLE
.NET Interactive notebooks are usable in flexible environments including GitHub Codespaces

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5844]
### Summary

As a student or teacher, I can use .NET Interactive notebooks in my preferred environment for learning tasks.

### Details

.NET Interactive notebooks must be available:

* Offline and on anyone's personal machine
* Installed in a lab environment that students can connect to
* Hosted in an online service, such as GitHub Codespaces or Binder

Critically, GitHub Codespaces is likely to be an essential environment for notebooks to be hosted _and executed_. This is because it supports a:

* Git repo-focused workflow so that there is a single source of truth for content: a git repo
   * Fork -> Work -> Submit pipeline
   * Ability to integrate CI into the equation, such as CI-based grading with nbgrader
* Zero (or minimal) installation requirements for students and teachers
* Reproducible and reliable environment to execute notebooks
* Freedom to move from online to offline expereinces without disruption or change of paradigm
* All dependencies needed to do an exercise (e.g., do data analysis and graph results) can be specified entirely within the notebook itself

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
