### ISSUE TITLE
Cross-Platform Publish related issue

### ISSUE THREAD

**Issue by SpiceyWolf** [dotnet/core#5847]
I have a library I maintain called SFML-Portable. It has some native C/C++ backend library requirements and recently I migrated to dotnet 5 with the SFML-Portable library.

Upon this migration I setup a test app in dotnet 5 and was testing that everything runs fine on linux and windows, to which it does out of the normal IDE environment. Testing publishing from Windows for Windows, Linux for Linux, and Linux for Windows etc this all worked fine.

I added another library backend to the mix to expand the functionality to include GUI stuff, that bit is not totally relevant... However what is relevant is it adds "layers" of extra dependancies. This gui backend also calls from a dotnet based frontend, to a C/C++ backend (of itself) which also wraps the C/C++ SFML files.

If I run from the debug or release produced on windows the app is still running properly and finding its dependancies with this added gui system. If i run release or debug on linux the app is still running properly etc. I can also publish On linux For linux, and On windows For windows and everything is STILL running fine.

Now that we have a little bit of an understanding where things are definitely working, the place where I have encountered an issue. Running publish ON windows, FOR windows, this test app can run fine. If however, I run the publish ON linux, FOR windows (which in most cases ive been playing with so far, for other apps I am developing, has NEVER been an issue) I get errors of some of the internal functions of the added gui dependancy failing. This only occurs if the publish was made ON linux FOR windows and otherwise I have not been able to reproduce this problem with the cross-platform publish functionality.

If anyone wants to try and figure out what could be the potential cause of this, the repository for my files is located at:
https://github.com/SpiceyWolf/SFML-Portable

The necessary steps to reproduce:
    Clone the repository somewhere, enter into TestApp folder, and run this command
        - (Linux) Performed from Terminal to create broken windows binary
        - (Windows) Performed from the 'git bash' that came with git.scm to produce working windows binary
    
  dotnet publish -c Win64 -r win-x64 -p:PublishSingleFile=true --self-contained
    
  Move the produced Win64 folder to windows, enter ./net5.0/win-x64/publish and run the TestApp.exe

As stated earlier, Ive made other apps using this publish command to have no issues cross-platform publishing, it seems to only be an issue with this 'layering' of native binary dependancies so it may be a pretty niche problem... However if theres a problem here it has a chance of being related to a deeper problem that may reach beyond the niche so I am leaving this here.

If any further information about my setup or systems is required I am fully willing to cooperate, thank you for taking the time to read this.

**Comment by scalablecory** [comment]
@eerhardt can you help route this?

**Comment by eerhardt** [comment]
@SpiceyWolf - it looks like you are using the wrong `-c` in that command. According to your .csproj:

https://github.com/SpiceyWolf/SFML-Portable/blob/b47328ea4eeccc5812e01c8be9c188b4c47c1d24/TGUI/TGUI_Portable.csproj#L49-L52

```xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='_WINDOWS_|AnyCPU'">
    <DefineConstants>_WINDOWS_;NETSTANDARD2_0</DefineConstants>
    <IsWindows>True</IsWindows>
  </PropertyGroup>
```

The command should be 

`dotnet publish -c _WINDOWS_ -r win-x64 -p:PublishSingleFile=true --self-contained`

I did that on my Ubuntu 18.04 box, and copied the output to my Windows machine and it ran successfully.

**Comment by SpiceyWolf** [comment]
I can confirm that fixed the problem... Im really thankful you found the issue so quickly and it was due to an error on my part rather than the build system! Still confused that some things did work despite that issue but I wont complain.
