### ISSUE TITLE
Add support for Ubuntu 21.04 (Hirsute Hippo)

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5850]
This issue is created to track progress for the work to enable Ubuntu 21.04 support for .NET Core 3.1, 2.1 and .NET 5.0.

### Product and Test updates
- [x] [All teams] Do a compatibility check for the product with the new OS
- [x] [CoreCLR/CoreFX] Runtime / RID Support update 
- [ ] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable) 
- [ ] [Infra] Replace docker tags used in builds across repos and branches
- [ ] [CLI team] Update CI legs to latest updated Dockerfile 
- [ ] [All teams] Update test infrastructure to support the new version
- [ ] [Acquisition] Add support within nightly repos 
- [ ] [Acquisition] Deploy to master (GA) during next patch release cycle        

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [x] Follow up with infra and add feed for new OS release to packages.microsoft.com 
- [ ]  Update release manifest files 
- [ ] Create new Docker files to test the new OS 
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by wfurt** [comment]
main & 5.0 https://github.com/dotnet/runtime/pull/37031
3.1 https://github.com/dotnet/corefx/pull/42928
2.1 https://github.com/dotnet/corefx/pull/42934

**Comment by josteink** [comment]
It Seems like `System.Security.Cryptography.Native.OpenSsl` has some issues on Ubuntu 21.04, as seen when trying to launch PowerShell:

https://github.com/PowerShell/PowerShell/issues/15101#issuecomment-808687551
