### ISSUE TITLE
.NET Developers have a first class experience working with GraphQL

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/core#5852]
[GraphQL](https://graphql.org) has been gaining traction over the last few years across a variety of platforms. We plan to investigate the space and find ways to improve the experience with .NET. This will involve working with the community as well as internal teams to understand and support the existing ecosystem. It may also involve specific investment from Microsoft, either in the form of contributions to existing work or in developing complimentary pieces in the Microsoft stack. Examples of this include but are not limited to:

- IntelliSense in Visual Studio products for `.graphql` schemas and definitions
- Interactive exploration of GraphQL endpoints similar to what [GraphiQL](https://github.com/graphql/graphiql) provides
- Services for exposing GraphQL endpoints and supporting schema stitching

These are not commitments but lines of exploration the team will investigate to enhance the GraphQL experience.

**Comment by danmosemsft** [comment]
[Using "team:libraries" for stuff that touches the core libraries team]

**Comment by SamuelCox** [comment]
Really excited to see this. I have heard of one organisation that is moving to node over .net because .net's graphql offerings does not have feature parity with the apollo implementation in node.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
