### ISSUE TITLE
NET Framework

### ISSUE THREAD

**Issue by sandeepkumarkasaudhan** [dotnet/core#5857]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@sandeepkumarkasaudhan can you provide more information about your problem? Are you trying to install .NET Framework? This tutorial is for you to learn about how to code with .NET 5.

**Comment by sandeepkumarkasaudhan** [comment]
Plz provide NET FRAMEWORK 2.0 LINK FOR WINDOWS 10 64BIT

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mairaw** [comment]
You should install .NET Framework 3.5 (which includes .NET Framework 2.0) on a Windows 10 machine:
https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10

Let me know if this helps!
