### ISSUE TITLE
Installation from repository fails on Fedora 31

### ISSUE THREAD

**Issue by Clifra-Jones** [dotnet/core#5865]
Getting this today.

Error: Transaction test error:
  package dotnet-sdk-3.1-3.1.405-1.x86_64 does not verify: no digest

**Comment by joeloff** [comment]
@rahku could you take a look?

@Clifra-Jones have you tried using a different feed, e.g. https://packages.microsoft.com/fedora/32/prod/?

**Comment by joeloff** [comment]
@rbhanda, @leecow

**Comment by rbhanda** [comment]
Hi, Fedora 31 is no longer supported as per our [supported OS document](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md).

**Comment by rbhanda** [comment]
Hello, we found an issue with dotnet-sdk-3.1.405-x64.rpm  and updated the file. This issue should be resolved now

**Comment by carlossanlop** [comment]
Closing since it seems to be resolved. Please create a new issue if you see this problem again.
