### ISSUE TITLE
Cannot download .NET SDK 5.0.2 , only download 5.0.102 .

### ISSUE THREAD

**Issue by donhuvy** [dotnet/core#5867]
Cannot download .NET SDK 5.0.2 , only download 5.0.102 .

https://dotnet.microsoft.com/download/dotnet/5.0

![501](https://user-images.githubusercontent.com/1328316/105333137-f59a7900-5c07-11eb-8fee-a635a89cdd55.png)

![image](https://user-images.githubusercontent.com/1328316/105333588-7c4f5600-5c08-11eb-9cf8-99cfb0389e7b.png)

![image](https://user-images.githubusercontent.com/1328316/105333576-76f20b80-5c08-11eb-8a4c-4b30477ca905.png)

**Comment by mairaw** [comment]
There are two different versions at play here.

5.0.2 is the runtime version.
5.0.102 is the SDK version. There is no 5.0.2 SDK yet.

/cc @rbhanda

**Comment by leecow** [comment]
To clarify further, there never will be a 5.0.2 sdk. the 5.1.102 SDK is the SDK that corresponds to the 5.0.2 release.
