### ISSUE TITLE
run command 

### ISSUE THREAD

**Issue by Ranjanaongit** [dotnet/core#5870]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by igoventura** [comment]
Please provide more details.

**Comment by mairaw** [comment]
Hi @Ranjanaongit! As @igoventura said, we'll need more details to try to help you. Maybe screenshots of the commands you ran and what's the problem you're experiencing.
