### ISSUE TITLE
how to open a new file

### ISSUE THREAD

**Issue by doyle123** [dotnet/core#5872]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @doyle123, you don't want to open a new file. You'd want to open an existing file on the edit step.

You can open the Program.cs file with notepad or a tool like Visual Studio Code.

Does that help?
