### ISSUE TITLE
I keep getting the same error

### ISSUE THREAD

**Issue by AmandaCaglioni** [dotnet/core#5873]
Everything was working well until I have to replace the code.

"Open Pages/Index.cshtml in any text editor and replace all of the code with the following, then save the file."

Once I replace it with the code provided and I run the app again it gives me this error:

/Users/myname/myWebApp/Pages/Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(4,13): error CS1002: ; expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(4,14): error CS1001: Identifier expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,6): error CS1002: ; expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,11): error CS1001: Identifier expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,11): error CS1514: { expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,11): error CS1513: } expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(8,14): error CS1002: ; expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(9,12): error CS1002: ; expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [/Users/myname/myWebApp/myWebApp.csproj]
/Users/myname/myWebApp/Pages/Index.cshtml.cs(10,7): error CS1002: ; expected [/Users/myname/myWebApp/myWebApp.csproj]

The build failed. Fix the build errors and run again.

How can I fix this?

**Comment by mairaw** [comment]
Hi @AmandaCaglioni! Is this related to https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify?

If so, it looks like you replaced the contents of the Index.cshtml.cs and not the Index.cshtml. You can perhaps delete your project and start over. It will probably be easier.

And I'm planning to add a note about this.

/cc @danroth27
