### ISSUE TITLE
Documentation is unclear about TokenValidationParameters.ValidateIssuerSigningKey 

### ISSUE THREAD

**Issue by marwalsch** [dotnet/core#5877]
I am setting up Basic AuthN for a JWT issued by the Windows STS. However, I am unsure about the correct way to do so and the Documentations are somewhat lacky about the correct way. These are my `AddJwtBearer `-options and the simplified Token:

```
options.TokenValidationParameters = new TokenValidationParameters  
                    {
                        ValidateIssuer = true,
                        ValidIssuer = "https://sts.windows.net/tenant/", 

                        ValidateAudience = true, 
                        ValidAudience = "api://domain.ngrok.io/resource",

                        ValidateIssuerSigningKey = true, 


                        ValidateLifetime = true
                    };
                    options.Audience = "api://domain.ngrok.io/resource";
                    options.Authority = "https://sts.windows.net/tenant/";
```

```
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "nOo3ZDrODXEK1jKWhXslHR_KXEg",
  "kid": "nOo3ZDrODXEK1jKWhXslHR_KXEg"
}
{
  "aud": "api://domain.ngrok.io/resource",
  "iss": "https://sts.windows.net/tenant/",
  "iat": 1611134241,
  "nbf": 1611134241,
  "exp": 1611141741,
}
{<SIGNATURE>}
```

Validation works as far as to deprecated Tokens or those lacking a signature partition entirely being rejected.
I am unsure about the most important step though, namely the Signature-Validation.
The docs have these description for the cirresponding parameters:

Authority: "Gets or sets the Authority to use when making OpenIdConnect calls." 
ValidateIssuerSigningKey: "Gets or sets a boolean that controls if validation of the SecurityKey that signed the securityToken is called. It is possible for tokens to contain the public key needed to check the signature. For example, X509Data can be hydrated into an X509Certificate, which can be used to validate the signature. In these cases it is important to validate the SigningKey that was used to validate the signature. This boolean only applies to default signing key validation. If IssuerSigningKeyValidator is set, it will be called regardless of whether this property is true or false."
([Link ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions?view=aspnetcore-5.0)to the docs)

This sounds like the Middleware uses the Authority ("https://sts.windows.net/tenant/") to retrieve the public key from the Windows STS and check the signature through the given alg-Parameter (RS256 in this case). 

Is this correct? Or am I lacking additional configuration to achieve the desired? Many samples have an additional parameter passed to `ValidIssuerSigninKey` but i suppose this is unnecessary if my Token hails from the STS and not my own implementation.

EDIT: I am referring to .NET Core 3.1

**Comment by mairaw** [comment]
@Rick-Anderson @scottaddie can you help here? Should this issue be transferred to a different repo?

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/Azure/azure-sdk-for-net/issues/18217
