### ISSUE TITLE
I install dotnet-sdk-3.1.405 but my setup required the .NET Framework version 3.5 is it ok for my set up or I should Install it also ?

### ISSUE THREAD

**Issue by Wadkarmanoj** [dotnet/core#5886]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![1234](https://user-images.githubusercontent.com/78091581/106006900-92c33a80-606a-11eb-9294-630bd53a723c.JPG)

**Comment by mairaw** [comment]
Hi @Wadkarmanoj! May I ask you how you ended up in the tutorial if you were trying to install .NET Framework 3.5?

Here's the article that explains how to install .NET Framework 3.5:
https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10

You can remove the .NET SDK if you're not going to be developing applications.
