### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll missed to install dotnet-sdk-5.0.10

### ISSUE THREAD

**Issue by ignasi-1943** [dotnet/core#5887]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @ignasi-1943! What version of Windows are you running? It seems that maybe you missed the additional dependencies as noted here:
![image](https://user-images.githubusercontent.com/12971179/106036139-c792ba00-6089-11eb-8b1f-7734a0097d56.png)

**Comment by ignasi-1943** [comment]
Tks. W7. The main reasson of all trouble is due that suddently I could not scan through my printer (god job done along 8 years) HPOfficejet Pro L7480) with no explanatios at all. So I had to start guessing everywhere about problem. Apologies

**Comment by mairaw** [comment]
Interesting, I'd love to learn how you ended up in that tutorial given you were trying to solve a printer problem.
What did you search for and where did you land?

That tutorial is only for folks that are trying to learn how to develop applications.
