### ISSUE TITLE
Unable to find image 'mymicroservice:latest' locally

### ISSUE THREAD

**Issue by saurabh-devloper** [dotnet/core#5893]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Screenshot (84)](https://user-images.githubusercontent.com/66743448/106350126-8c96bd80-62f9-11eb-97f1-d4fd8e061316.png)

**Comment by mairaw** [comment]
and what was the result of running `docker build -t mymicroservice .` on the previous step? It seems you only have an image that you created 10 days earlier.

**Comment by mairaw** [comment]
Tagging @nishanil and @shirhatti for suggestions as well
