### ISSUE TITLE
 i finished typing when i created the application

### ISSUE THREAD

**Issue by zcy-729** [dotnet/core#5894]
Creating this template will make changes to existing files:
  Overwrite   myApp.csproj
  Overwrite   Program.cs

Rerun the command and pass --force to accept and create

I finished typing when I created the application
dotnet new console -o myApp
When this happens, what should I do

**Comment by mairaw** [comment]
Have you run the same command twice @zcy-729? The error message is telling you that you have already a project on that location. You can either delete the existing folder and start over, or pass the `--force` option as the error message is telling you. Is this related to one of the tutorials on the dot.net website?
