### ISSUE TITLE
Getting Started not working on OS X 10.11.3

### ISSUE THREAD

**Issue by aschweiz** [dotnet/core#59]
Hi all,

I get an exception when trying to run 'dotnet restore':

$ mkdir hwapp
$ cd hwapp
$ dotnet new
Created new C# project in /Users/asr/hwapp.
$ dotnet restore
log  : Restoring packages for /Users/asr/hwapp/project.json...
error: The type initializer for 'Crypto' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)

This happens after installing the dotnet-osx-64.1.0.0.001598 installer package.

Does anybody know what's causing this issue?

Thanks
Andreas

**Comment by bartonjs** [comment]
Just as a quick guess, you might need to install OpenSSL (1.0.1 or 1.0.2): https://github.com/dotnet/coreclr/blob/master/Documentation/building/osx-instructions.md#openssl

**Comment by blackdwarf** [comment]
What @bartonjs  said is true. This is covered in the getting started. Also, that is a very old build and you should use the RC2 bits. The instructions are on: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
