### ISSUE TITLE
Allow outside access [Blazor]

### ISSUE THREAD

**Issue by lerichardson** [dotnet/core#5904]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: CentOS 7 linux

I am trying to set up a Blazor environment on my VPS and I'm trying to access it from the port 8080 instead of 5000. I tried both answers on [This stackoverflow post](https://stackoverflow.com/questions/65689042/is-there-a-way-to-make-blazor-allow-outside-http-access) and it still isn't working. My appsettings.json looks like this:
```
{
    "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Urls": "http://localhost:8080"
}
```
When I run `dotnet watch run`, I get this: 
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: <path>
```
I get this error when visiting it:
![image](https://user-images.githubusercontent.com/72626657/106661341-f01d2700-6555-11eb-9dc8-35262820705c.png)  
I don't know what to do. Sorry if this is a needless, useless issue

**Comment by omajid** [comment]
This program is using the `http://localhost:8080` URL. The `localhost` part means that it's only accessible from the same machine, not from anywhere else. Maybe you want to try changing it to this:

    "Urls": "http://0.0.0.0:8080"

**Comment by lerichardson** [comment]
Already tried that. Nothing changes. Same error from my browser.
```
watch : Started
Building...
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: <path>
```
I have looked at my firewall. Port 8080 is open.

**Comment by lerichardson** [comment]
I stand corrected. I am used to using Debian/Ubuntu Linux distros that have 8080 open by default. 

I am very sorry for being such an idiot.

**Comment by mairaw** [comment]
Don't be so harsh on yourself. Is there something we could add to the tutorial that would make this easier?

**Comment by lerichardson** [comment]
I'm not sure. I don't know if this is a common question/problem. I don't see why it wouldn't need to, but I also don't see why it would.

**Comment by mairaw** [comment]
Fair enough.
