### ISSUE TITLE
It's coming up as an error 

### ISSUE THREAD

**Issue by cassadichase** [dotnet/core#5905]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
<img width="817" alt="Screen Shot 2021-02-02 at 4 17 42 PM" src="https://user-images.githubusercontent.com/78448074/106663784-31bbcb00-6572-11eb-96c2-122794d62853.png">

**Comment by mairaw** [comment]
@cassadichase you need to open the Program.cs file that is inside the myApp directory and then paste that content. Let us know if that helps.
