### ISSUE TITLE
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\3.1.11\hostfxr.dll ], HRESULT: 0x80070057

### ISSUE THREAD

**Issue by AhmedAbdallah13** [dotnet/core#5906]
how to fix this error ???

Failed to load the dll from [C:\Program Files\dotnet\host\fxr\3.1.11\hostfxr.dll
], HRESULT: 0x80070057

this happened after i install .net skd 5.0.1 and when i type in cmd any thing after word " dotnet " like that the error happens
- dotnet new console
- dotnet --info 

![5123](https://user-images.githubusercontent.com/78449243/106668972-a2cfa280-65b3-11eb-824c-c1a4a784d3c6.PNG)

**Comment by AhmedAbdallah13** [comment]
I want an answer in the shortest time pleaseeeeeeee

**Comment by mairaw** [comment]
@AhmedAbdallah13 what's the version of your Windows? You might need to install some additional dependencies:
https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#additional-deps

Here is a thread related to this:
https://developercommunity.visualstudio.com/content/problem/805039/net-core-30-failed-to-load-dll.html

/cc @jeffschwMSFT @nguerrera

**Comment by jeffschwMSFT** [comment]
@AhmedAbdallah13 can you collect a host trace for us?  Here are the instructions: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-do-i-debug-the-probing-properties-construction 

cc @vitek-karas @agocke
