### ISSUE TITLE
Couldn't find a project to run. Ensure a project exists in C:\Users\Darlington, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by Decent1998** [dotnet/core#5911]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you navigate to the project's directory as instructed in the previous step?
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create

**Comment by rookie-** [comment]
I have the same problem. I create  a Program.cs file but there is no proj file and the program can't run. I get: 
_Couldn't find a project to run. Ensure a project exists in /workspaces/SortingCollection, or pass the path to the project using --project._

**Comment by mairaw** [comment]
@rookie- please open a new issue. But .NET projects require a csproj in order to run.
