### ISSUE TITLE
sistem error karena program api-ms-win-crt-runtime-11-1-0,dll

### ISSUE THREAD

**Issue by adenurkamal** [dotnet/core#5915]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What version of Windows are you running on? You might be missing some dependencies listed on the previous page
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

![image](https://user-images.githubusercontent.com/12971179/106959700-e3ccd180-66ef-11eb-90cd-e950a523941c.png)
