### ISSUE TITLE
Did you mean to run dotnet SDK commands?

### ISSUE THREAD

**Issue by BlaDrzz** [dotnet/core#592]
This may be more of a question instead of an issue but I followed the steps outlined to get an application running on my raspberry pi3 and everything goes well until I move the files over to the Pi and actually try to run the helloworld example.

I copied all the contents inside of the "Publish" folder into a folder on the ubuntu 16 desktop inside of a folder "helloworld". Navigated in there and then tried ./helloworld and I tried to right click and open as admin but both of these result in "sudo: ./helloworld: command not found".  When I try "sudo dotnet helloworld" it results in ""Did you mean to run dotnet SDK commands? Please install dotnet SDK from: <insert link to microsoft website>".

Sorry for the "noob" question but is there anything that I am missing?

**Comment by multic0r3** [comment]
Inside this folder, you have to use the filename of your executable dll, in your example something like `dotnet ./helloworld.dll`

**Comment by BlaDrzz** [comment]
Thanks for the reply, I will try this when I revert back to ubuntu. Currently playing around with windows IoT.
