### ISSUE TITLE
On Ubuntu machine I have .net 5 installed but VS code not able to find it.

### ISSUE THREAD

**Issue by anirugu** [dotnet/core#5937]
I have installed the .net core 5 and I can see it by running dotnet command. I installed it using given instruction on docs on 20.10. 

Suddenly today I see vs code not able to find it?. I  tried to create a azure function project. Now it's giving error like .net code is not installed. 

![image](https://user-images.githubusercontent.com/35772421/107485027-3c491680-6ba9-11eb-9659-b937453e67e4.png)

anyone having trouble like this?

**Comment by dasMulli** [comment]
This seems to be coming from the Azure Functions extension - https://github.com/microsoft/vscode-azurefunctions

**Comment by carlossanlop** [comment]
@anirugu did you install the full SDK or just the runtime?

**Comment by anirugu** [comment]
Full sdk and runtime as well.  ---- On Wed, 10 Feb 2021 22:53:10 +0530  notifications@github.com  wrote ----
@anirugu did you install the full SDK or just the runtime?

**Comment by dasMulli** [comment]
Judging from the Code of the Azure Functions SDK, you need a 2.* or 3.* SDK for this extension to work:
https://github.com/microsoft/vscode-azurefunctions/blob/68990431cae74f82b3cd3cc7e21f97f083f8cbf4/src/templates/dotnet/executeDotnetTemplateCommand.ts#L64-L77

I suggest moving this to the repo of this extension

**Comment by anirugu** [comment]
everything going good, suddenly one day I update my ubuntu and this problem start appearing and it was working earlier fine.

**Comment by dasMulli** [comment]
@anirugu it looks like you will need to install a 3.* SDK side by side for this to work again.

**Comment by danmoseley** [comment]
@anirugu are you working now?

**Comment by anirugu** [comment]
I haven't tested it. You can close it for now. I will report here if It don't work for me.  ---- On Mon, 15 Feb 2021 13:15:01 +0530  notifications@github.com  wrote ----
@anirugu are you working now?
