### ISSUE TITLE
Issue with Chocolatey package

### ISSUE THREAD

**Issue by gsscoder** [dotnet/core#5938]
Dear DotNet Core Team,
I don't know if this the correct place to post the issue in object.

Anyway more and more times when Chocolatey upgrade `dotnetcore-sdk` package it disappears from `dotnet --info`.

Machine is Microsoft Windows 10 professional.

_At moment I'm really busy and unable to add more details. Sorry._

I've reinstalled all SDKs manually.

Have a nice day,
Giacomo S. S.

**Comment by carlossanlop** [comment]
@dagood is Chocolatey something in our radar?

**Comment by dagood** [comment]
The Chocolatey .NET SDK packages are maintained by the community: https://chocolatey.org/packages/dotnetcore-sdk. There are a few different ways to contact the maintainers on that page.

My understanding is that the Chocolatey packages do rely on the same installers you can get from https://dotnet.microsoft.com/download, so someone could potentially help out anyway. But, we would need a lot more info, and it sounds like you've resolved it already.
