### ISSUE TITLE
error in dotnet

### ISSUE THREAD

**Issue by samsonite98765** [dotnet/core#5939]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: linux chromebook crouton

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
it said `"/ has 'other' write 40777"`
![Screenshot 2021-02-10 12 10 46 PM](https://user-images.githubusercontent.com/77023084/107545269-19af0180-6b99-11eb-9096-54a3feac7f13.png)

**Comment by carlossanlop** [comment]
@samsonite98765 did you install dotnet via snap? Can you try reinstalling? Maybe it got corrupted.
cc @dagood
