### ISSUE TITLE
 The type initializer for 'System.Drawing.KnownColors' threw an exception

### ISSUE THREAD

**Issue by lianggx** [dotnet/core#594]
debian.8.x.x64
if you throw The type initializer for 'System.Drawing.KnownColors' threw an exception 
to do:apt-get install libgdiplus

I hope some one can fix it！

**Comment by richlander** [comment]
@lianggx can you share a sample?

**Comment by MeetOct** [comment]
i found this in docker images(microsoft/dotnet:1.1.2-runtime) when i used  EPPlus.Core
```
The type initializer for 'System.Drawing.KnownColors' threw an exception.
   at System.Drawing.KnownColors.FromKnownColor(KnownColor kc)
   at System.Drawing.Color.get_White()
```

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24478](https://github.com/dotnet/corefx/issues/24478) via [**ZenHub**](https://www.zenhub.com/)
