### ISSUE TITLE
I am stuck at command prompt after receive message restore success. I use windows 7 64 bit.

### ISSUE THREAD

**Issue by Redmi456** [dotnet/core#5941]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you show a screenshot of where are you stuck? Did you run the app successfully?
