### ISSUE TITLE
.NET 5 features

### ISSUE THREAD

**Issue by balukantu** [dotnet/core#5942]
Hi Team,

I have gone through .NET 5 features and looks like everything is understandable but I have few points. Can anyone please correct my points that are listed below?

1. .NET 5 has a single CLR for both Framework and Core

2. .NET standard is the way to share a library between .NET framework and .NET core

3. As per the documentation, the .NET 5 is the next version of .NET Core. If we install .NET 5 on Linux, we can't create and run framework related projects on Linux because still, they are windows specific applications.

4. I think the backword compatibility from .NET 5/ .NET x to .NET Core 3.1/ .NET Core 2.1 will be possible if there are no breakage changes.

5. For .NET core 3.1, we can install the runtime and run the already built application. Is it the same case with .NET 5. we can just install the .NET runtime and run the .NET 5(Framework and Core) applications.

**Comment by danmoseley** [comment]
Hellow @balukantu 

1. .NET 5 is the future of .NET. Technically, it is the development of the .NET Core lineage , and as such is based on coreclr. .NET Framework is based on clr. .NET Framework continues to be supported, but the future is with .NET 5 and later, which is generally highly compatible.

2. Correct. [Here is more info](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

3. It depends on the app. If it uses Windows-specific features, such as Winforms or WPF, it won't work on Linux. A console app will work, after recompilation. A library will work without recompilation, if it doesn't use Windows specific features.

4. We try hard to avoid breaking changes so yes any code that runs on .NET Core 2.1/3.1 should run on .NET 5 or later.

5. Yes, the install model hasn't changed. You can install the .NET runtime pack, and then deploy the app separately. There is an advanced scenario, if you want it, to [deploy the framework as part of the app.](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file)

**Comment by danmoseley** [comment]
@balukantu  I'll close as answered but do reopen if not.

**Comment by balukantu** [comment]
@danmoseley , Thanks for the update. I have gone through the documentation observed that it is the next version of Core 3.1

Is there any difference between .NET Core 3.1 and .NET 5? in terms of features apart from adding framework API and libraries?

**Comment by danmoseley** [comment]
@balukantu yes, a whole year's worth of improvements 🙂

https://docs.microsoft.com/en-us/dotnet/core/dotnet-five
