### ISSUE TITLE
<Question> Is there any alternative to System.ServiceModel.Activities in . NET 5.0 ?

### ISSUE THREAD

**Issue by srvkmr130** [dotnet/core#5943]
I am currently using .NET 5.0 , missing System.ServiceModel.Activities reference .
Is there any substitute for this ?

**Comment by danmoseley** [comment]
@mconnew do you know ?

**Comment by mconnew** [comment]
Take a look at the non-Microsoft owned project [CoreWF](https://github.com/UiPath/corewf). It's not Microsoft owned, but it's got a company behind it who is taking it seriously.

**Comment by danmoseley** [comment]
@srvkmr130  I'll close as answered but do reopen if not.
