### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by staffordsmitht** [dotnet/core#5946]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-tools
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by staffordsmitht** [comment]
Fixed! Nevermind, thank you.

**Comment by mairaw** [comment]
Good to hear!
