### ISSUE TITLE
Build error when creating docker image from Microsoft tutorial 

### ISSUE THREAD

**Issue by spatrick195** [dotnet/core#5952]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: Windows 10 Version 1909

When running `docker build -t mymicroservice .` I receive the following build error:
<details>
<summary><b>Docker Build Output</b></summary>

```powershell
PS D:\Dev\myMicroService> docker build -t mymicroservice .
[+] Building 1.4s (9/14)
 => [internal] load build definition from Dockerfile                                         0.0s
 => => transferring dockerfile: 32B                                                          0.0s
 => [internal] load .dockerignore                                                            0.0s
 => => transferring context: 2B                                                              0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:5.0                         1.1s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0                            1.2s
 => [internal] load build context                                                            0.0s
 => => transferring context: 3.25kB                                                          0.0s
 => CANCELED [build 1/6] FROM mcr.microsoft.com/dotnet/sdk:5.0@sha256:c0dc643e15be6d5aad6f5  0.1s
 => => resolve mcr.microsoft.com/dotnet/sdk:5.0@sha256:c0dc643e15be6d5aad6f51a4cc5dc8966bbe  0.0s
 => => sha256:c0dc643e15be6d5aad6f51a4cc5dc8966bbecdc83647e58276fdc0b155361 2.53kB / 2.53kB  0.0s
 => => sha256:ce747ad71589455b2abfab2d0f10ef542aacfc4ca03b0babe9c3c74d8aa66 2.01kB / 2.01kB  0.0s
 => => sha256:dd6f8be8f903f116462640bfb9b0bb5da962546c016b73d20d465479f7e16 7.21kB / 7.21kB  0.0s
 => CANCELED [stage-1 1/3] FROM mcr.microsoft.com/dotnet/aspnet:5.0@sha256:7f862b33d4813e56  0.2s
 => => resolve mcr.microsoft.com/dotnet/aspnet:5.0@sha256:7f862b33d4813e566f51a6cb39778906a  0.0s
 => => sha256:c3a51e51a0f9d2c43589e645f493826343d3f6adc406cad581a8dd9f8bbf4 3.49kB / 3.49kB  0.0s
 => => sha256:7f862b33d4813e566f51a6cb39778906a65eb06a57cc9943e3161c8ead7cd 2.53kB / 2.53kB  0.0s
 => => sha256:de4f2c5131b9d51f84f20b2012c9f354ab55ed6f1f1cec4a5ba4b8626ac9f 1.37kB / 1.37kB  0.0s
 => CACHED [build 2/6] WORKDIR /src                                                          0.0s
 => ERROR [build 3/6] COPY myMicroservice.csproj .                                           0.0s
------
 > [build 3/6] COPY myMicroservice.csproj .:
------
failed to compute cache key: "/myMicroservice.csproj" not found: not found
```

</details>

I have tried: 

- Clearing NuGet cache
- Cleaning project with dotnet CLI
- Clean / Purge data in Docker Desktop.
- Factory Reset of Docker.

The docker version I am building with is 20.10.2. My Docker file content is copied from the MS Tutorial:

<details>
<summary><b>Dockerfile</b></summary>

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY myMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]
```

</details>

EDIT: I have noted that various answers on other sites have located this issue to the naming of the dockerfile. My docker file is named as 'Dockerfile'. I tried other variations of this, including: '.dockerfile', '.Dockerfile' but these seem to be incorrect naming for the file. Other sites have indicated that it may be something to do with docker buildkit.

**Comment by danmoseley** [comment]
@MichaelSimons

**Comment by MichaelSimons** [comment]
@spatrick195 - I suspect your issue is related to the casing of the `COPY myMicroservice.csproj` instruction in your Dockerfile.  I noticed the path you are building from is using a different casing - `D:\Dev\myMicroService`.  Notice the difference is the casing of the `s` in `service`.  

By looking at the sha of the image you are using, I can see you are pulling a linux image which uses a case sensitive OS.  The docker build output is indicating the `myMicroservice.csproj` file is not found in your Docker build context while executing the COPY instruction.  Please check to see if the casing of the `myMicroservice.csproj` in the `D:\Dev\myMicroService` matches the casing specified in your Dockerfile's COPY instruction.

**Comment by spatrick195** [comment]
That does seem to be the issue. It has now been resolved.
