### ISSUE TITLE
ClickOnce - Are there similar APIs to those in `System.Deployment.Application` for .NET 5?  Any plans to port them?

### ISSUE THREAD

**Issue by lucent-sea** [dotnet/core#5954]
I'm sorry if there's existing documentation or issues on this.  I couldn't find any.

Were any APIs from `System.Deployment.Application` namespace ported to .NET 5 with ClickOnce?  If so, could you link me the docs?  If not, are there any plans to bring them over?

**Comment by John-Hart** [comment]
+ @NikolaMilosavljevic can you please answer this?

**Comment by NikolaMilosavljevic** [comment]
@lucent-sea those APIs are not available in .NET 5. We are tracking the following 2 issues for improvements that would bring some of the functionality, using different model:
https://github.com/dotnet/deployment-tools/issues/27
https://github.com/dotnet/deployment-tools/issues/53

**Comment by lucent-sea** [comment]
Fantastic!  Thank you.  :)

**Comment by eiriktsarpalis** [comment]
It seems that this question has already been answered, so I'm going to close this issue. Feel free to reopen if that is not the case.
