### ISSUE TITLE
.NET SDK is not installed

### ISSUE THREAD

**Issue by Flipper00** [dotnet/core#5958]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
tried to execute "new console -o myApp" and it says"Could not execute because the application was not found or a compatible .NET SDK is not installed."
I have installed it more than once and still get the same message.
I am using windows 10.

**Comment by mairaw** [comment]
Can you check if the steps I added here help you?
https://stackoverflow.com/questions/63746838/net-sdks-not-installing-correctly/66128116#66128116

And what's your version of Windows? And is it 32-bit or 64-bit?

**Comment by mairaw** [comment]
I also added the step by step here:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535
