### ISSUE TITLE
dotnet restore from "non project folder" fails

### ISSUE THREAD

**Issue by GlenBoonzaier** [dotnet/core#596]
The command:
**_c:\>"c:\program files\dotnet\dotnet.exe" restore "c:\path\to\project\folder"_**
fails with the following error:
**_c:\path\to\project\folder\project.xproj(7,3): error MSB4019: The imported project "c:\program files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk._**

However, if I navigate to the project folder and execute the exact same command:
**_c:\path\to\project\folder>"c:\program files\dotnet\dotnet.exe" restore "c:\path\to\project\folder"_**
It works as expected.

The use case for the first command is that I am running TFS2013.  In order to build my project I need to run the dotnet restore command as a pre-build script.  In the pre-build script path I put:
**_c:\program files\dotnet\dotnet.exe_**
and in the arguments I put:
_**restore "$(TF_BUILD_BUILDDIRECTORY)\path\to\project\folder"**_

This results in the error as shown.

**Comment by richlander** [comment]
I just tried this is .NET Core 2.0 Preview 2 and it works like you want.
