### ISSUE TITLE
.NET Core automatic patch updates are not working

### ISSUE THREAD

**Issue by gaborposz** [dotnet/core#5966]
Hello,
Is it possible that the recently introduced [automatic .NET Core patch updates](https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/) (via Microsoft Update) are only working if there is already a recent .NET Core version installed?

E.g.:
We noticed that if **ASP.NET Core 3.1.7** is installed (hosting bundle), then it's not updated automatically, but if **3.1.9** is installed, then it is.

Is it possible, or did we do something wrong?

**Comment by mairaw** [comment]
@jamshedd can you help with this MU question?

**Comment by jamshedd** [comment]
The ASP.NET Core update should be offered via MU to any prior version of Core 3.1 (including 3.1.7). This is provided you're on a Client SKU of Windows and not a Server version. For server versions we do not "push" updates via MU, but they're available for you to "pull" via WSUS or the MU Catalog. Can you share more details including a list (or screenshot) of the relevant products from your ARP?

**Comment by gaborposz** [comment]
Ok, most probably the problem is that we need it on server (e.g. Windows Server 2019). 

By "MU Catalog" you mean a manual download from [https://www.catalog.update.microsoft.com](https://www.catalog.update.microsoft.com)?

And I don't understand the question regarding "relevant products from ARP" either. What does the ARP abbreviation mean? 

Maybe it helps to understand our situation:
We preinstall the [ASP.NET Core Runtime Hosting Bundle installer](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.7-windows-hosting-bundle-installer) on server machines that we deliver to customers, and we are looking for a way to preconfigure automatic .NET Core security updates, so that .NET Core will be always secure on the machine, preferably without any manual contribution of the local administrator.

**Comment by jamshedd** [comment]
Since this is an ASP.NET app it is very likely the machines are Server SKUs of Windows and not client SKUs. For this case an IT administrator can use either WSUS or SCCM to deploy .NET Core updates to the machines.  We don't push updates directly to server machines ourselves because the majority of enterprise customers prefer to maintain direct control over when servers are updated based on internal org specific patching policies, SLAs, etc.

**Comment by danmoseley** [comment]
I think this is answered.
