### ISSUE TITLE
On Fedora 32 Errors during downloading metadata for repository 'download.docker.com_linux_fedora_docker-ce.repp':   - Status code: 404 for https://download.docker.com/linux/fedora/docker-ce.repp/repodata/repomd.xml (IP: 13.224.177.25)

### ISSUE THREAD

**Issue by janakaw** [dotnet/core#5971]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@leecow @dagood can you help with this issue?

**Comment by dagood** [comment]
This doesn't seem to be related to .NET, it looks like you hit an error with a Docker CE repository set up on your machine:

> Status code: 404 for https://download.docker.com/linux/fedora/docker-ce.repp/repodata/repomd.xml

With a quick web search I see that Docker has changed the layout of their repository at some point in the past. You might need to update your configuration to match. https://docs.docker.com/engine/install/fedora/ might help.

**Comment by janakaw** [comment]
I solved this by following below: Remove all dotnet packages installed including any older sdks `sudo dnf list installed 'dotnet*'`  
Then, sudo dnf install dotnet-sdk-.5.0

**Comment by janakaw** [comment]
Closed
