### ISSUE TITLE
Docker run | Could not find any compatible framework version

### ISSUE THREAD

**Issue by manish41396** [dotnet/core#5972]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

On running command :
docker run -it --rm -p 3000:80 --name mymicroservicecontainer mymicroservice

Getting error:
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.3 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64

Although I have .NetCore 3.1 installed on my machine.

**Comment by mairaw** [comment]
If you're using .NET Core 3.1, some steps of the tutorial would have to be changed.
The Dockerfile on this step: https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
would have to point to 3.1 and not 5.0.

Are you on Linux or Windows?

**Comment by manish41396** [comment]
Hi,

Thanks for your response.
I am on Windows machine. It worked now.
I changed Dockerfile as below to point it to .Net Core 3.1, same as of my machine:

![image](https://user-images.githubusercontent.com/28561483/108466191-435add80-72a9-11eb-89b5-c46417563d27.png)

Thanks!!
