### ISSUE TITLE
Command 'dotnet' not found, but can be installed with:  sudo snap install dotnet-sdk

### ISSUE THREAD

**Issue by sarathisam** [dotnet/core#5973]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
@sarathisam , the default command after installing with the snap is `dotnet-sdk.dotnet`. See details and instructions on how to alias the command in any of the install notes such as [this one](https://github.com/dotnet/core/blob/master/release-notes/6.0/preview/6.0.0-preview.1-install-instructions.md#install-net-on-linux).

**Comment by mairaw** [comment]
Let us know if that solves your issue!
