### ISSUE TITLE
Microsoft.Net.Sdk.Web could not be found

### ISSUE THREAD

**Issue by LarryC42** [dotnet/core#5979]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

**Comment by LarryC42** [comment]
Found a reference to someone setting the MSBuildSDKsPath environment variable.  Fixed it build work.  Removed it, build worked.

**Comment by mairaw** [comment]
Ah was just going to refer to a similar issue discussing the MSBuildSDKsPath env variable. Thanks for confirming.
