### ISSUE TITLE
Unable to resolve package reference ''. on Ubuntu 20.04

### ISSUE THREAD

**Issue by JasonJ387** [dotnet/core#5981]
I'm using PowerShell with .net core 5.0 in Ubuntu 20.4; but I'm having an issue importing nuget libraries using the Install-Package command.

The machine is in a locked down environment with no access to the outside world so nuget pacakages are stored on a fileshare.

This works fine on Windows Devices, but the Ubuntu device is complaining.

The specific command I'm using is:
Install-Package -Source /mnt/share/DotNetCorePackages -Name system.xml.xpath.xmldocument -SkipDependencies

The error message I'm receiving is:
Install-Package: Unable to resolve package reference ''.

**Comment by eiriktsarpalis** [comment]
Hi @rrelyea @nkolev92, is this related to the Nuget.Client repo?

**Comment by nkolev92** [comment]
Nope, that's powershell's own Install Package. 

We got a dup issue in https://github.com/NuGet/Home/issues/10583.

**Comment by eiriktsarpalis** [comment]
In that case I'm going to close this issue in favor of the dup.
