### ISSUE TITLE
microsoft.aspnetcore.server.kestrel

### ISSUE THREAD

**Issue by sungka** [dotnet/core#5983]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
It's not clear what is the problem you're having. Can you provide more details?

**Comment by sungka** [comment]
Thank you. Will try another .NET 5.0 microservice tutorial that uses Visual Code on Windows.
--sung

    On Friday, February 19, 2021, 12:55:20 PM PST, Maira Wenzel <notifications@github.com> wrote:  
 
 


It's not clear what is the problem you're having. Can you provide more details?
