### ISSUE TITLE
Microsoft BBL ("Big Brother Language") Continues Attack on English Language

### ISSUE THREAD

**Issue by DavidLJ** [dotnet/core#5984]
".NET appeals to net-new developers, students, and new technologists" marks a new advance in the progress of BBL against English.
Bogdan B. Bogdanovicovich. former People's Democratic Leading Leader of Bulgarian People's Department of People's Democratic Communication, has hailed the phrase above as clear evidence of Microsoft's "popular democratic linguistic communication-type democratic communication."
"Is great advance in People's Democratic Popular Liberated Communication," said the Leading Leader at a rally to celebrate the new Microsoft headline. "Is must have all headlines hail appeal of Microsoft without regard to actual content," he democratically emphasized. "Is must all Liberated Peoples celebrate Microsoft revolutionary progress."

**Comment by eiriktsarpalis** [comment]
Closing as off-topic.
