### ISSUE TITLE
Problem in downloading .net

### ISSUE THREAD

**Issue by Paranjay-Sharma** [dotnet/core#5986]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rbhanda** [comment]
Hello, Can you provide more details on what are you trying to achieve and more details on the problem you are encountering?
