### ISSUE TITLE
SDK 3.1.406 for RHEL6?

### ISSUE THREAD

**Issue by georgevanburgh** [dotnet/core#5989]
Apologies if this is the wrong place to ask - but I was wondering if I could get some clarity on RHEL 6 support (sorry for being _that guy_).

SDK 3.1.406 was released a few weeks ago as part of #5932 (🎉). I'm aware of the fact that .NET 5 has now dropped support for RHEL6 - but was under the impression that Core 3.1 would continue support until it hits EOL next year. I'm not able to see a RHEL6 binary for SDK 3.1.406 [on the dotnet download side](https://dotnet.microsoft.com/download/dotnet/3.1) however. Has support been deprecated mid-train, or have these binaries just not been published yet?

**Comment by eiriktsarpalis** [comment]
hi @dagood, would you be able to take a look?

**Comment by dagood** [comment]
According to https://github.com/dotnet/installer/pull/9251, this was intentional:

> We've removed the RHEL leg in other branches so I'll do the same here unless anyone has any concerns about that.

> RHEL6 EOL was 11/30/2020 and I'm not aware of any directive to continue supporting it.

I'm not super familiar with the RHEL support cycle, myself.

/cc @leecow @sfoslund @dleeapho

**Comment by sfoslund** [comment]
The linked PR removed the CI leg for RHEL 6 as the images were no longer supported but this should be unrelated to if RHEL 6 SDKs are produced. I'm not aware of any changes with RHEL SDK support.

**Comment by FireEater64** [comment]
Sorry to bump this again, but I notice that SDK 3.1.13 was [just published](https://dotnet.microsoft.com/download/dotnet/3.1), again with no RHEL6 binaries . Is the conclusion that RHEL6 is now completely unsupported for new releases? It would be good to get some configuration either way.

**Comment by anatolybolshakov** [comment]
We affected also while updating of Azure pipelines agent to use last patch version of SDK 3.1 (related PR: https://github.com/microsoft/azure-pipelines-agent/pull/3432)
@georgevanburgh @sfoslund do you know if it's expected that there are no RHEL binaries with security updates shipped, so we need to rework our flow according to it? Or there are any plans to include it?

**Comment by sfoslund** [comment]
I'm not sure, @leecow are you the right person to comment?

**Comment by dleeapho** [comment]
The [.NET Core 3.1 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md) states that .NET Core 3.1 support ended with RHEL6 EOL on 11/30/2020
@georgevanburgh @anatolybolshakov do you have extended service programs with Red Hat for RHEL 6?

**Comment by leecow** [comment]
Dan is correct, our last update for RHEL 6 was 3.1.10 (3.1.404 SDK) on 11/10/2020.

**Comment by georgevanburgh** [comment]
> The [.NET Core 3.1 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md) states that .NET Core 3.1 support ended with RHEL6 EOL on 11/30/2020

@dleeapho @leecow - thanks for getting back to me on this. I'd clearly missed that documentation - but that makes it clear.

> Dan is correct, our last update for RHEL 6 was 3.1.10 (3.1.404 SDK) on 11/10/2020.

Per [`dot.net`](https://dotnet.microsoft.com/download/dotnet/3.1), I can see RHEL6 binaries were produced for 3.1.11 (3.1.405) on 2021-01-12 - which I think is what caused some of the confusion in the first place (given it didn't match with the RHEL6 EOL date).

> do you have extended service programs with Red Hat for RHEL 6?

Possibly - at that point I suppose we'd be looking to obtain binaries from Red Hat directly, rather than using Microsoft published binaries?

Either way - if the official position is that RHEL6 has been dropped - I think this can be closed out.

**Comment by dleeapho** [comment]
@georgevanburgh .NET is already available directly from Red Hat via their RHEL Software Collections. More information including supported versions is available at Red Hat's .NET page: https://developers.redhat.com/products/dotnet/overview

**Comment by anatolybolshakov** [comment]
@sfoslund @georgevanburgh got it, thanks for clarifying! No, we don't have any

**Comment by georgevanburgh** [comment]
Closing this out since it's clear not publishing RHEL6 binaries for SDK v3.1.12 and above was intentional. Thanks all 🙂.
