### ISSUE TITLE
Blazor foreach not nullsave when using conditional ?: operator

### ISSUE THREAD

**Issue by JohnFasc** [dotnet/core#5994]
When I am using the conditional operator :? in an foreach loop and the list, i want to iterate through is null, the runtime throws an exception. 

`@foreach(var tmp in condition ? consequent : alternative)
{
}
`

In my example the alternative was loaded and then the condition changed and the consequent was null. 

### Configuration
We Use .net 5 v5.0.3

**Comment by eiriktsarpalis** [comment]
Running foreach over null enumerables will invariably result in `NullReferenceException`, this is not particular to the `?:` operator. This is by design, I would recommend guarding with the null-coalescencing operator:

```csharp
foreach(var tmp in (condition ? consequent : alternative) ?? Enumerable.Empty<YourTypeGoesHere>()) { }
```
