### ISSUE TITLE
Unable to get the result in aws linux instance.

### ISSUE THREAD

**Issue by logambigaik** [dotnet/core#5995]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/54719289/108889490-73e8a180-7632-11eb-844a-7cabef631cb3.png)

**Comment by mairaw** [comment]
@leecow any suggestions here? Should the issue be filed with AWS directly?

The tutorial as written is supposed to be run locally.

**Comment by leecow** [comment]
Yes, the AWS instance (container?) will need to be configured to open a port through which the local browser can connect to the running MVC application. Unfortunately, I don't know off the top of my head how to set this up though something like `docker run -p 8080:80 -it amazonlinux` should set up an interactive instance with an open port. Hopefully that's enough to get you started.
