### ISSUE TITLE
how to convert command line generated project.json into vs project

### ISSUE THREAD

**Issue by anguoyang** [dotnet/core#60]
Hi, how to convert command line generated project.json into vs project and open it in visual studio?

I would like to develop in windows/vs, and then dotnet run it on ubuntu or docker.thanks

**Comment by livarcocc** [comment]
@anguoyang Just open the project.json file directly in VS. VS will generate an xproj file for it.

**Comment by seanshpark** [comment]
@livarcocc , wow, I was also looking something like this.

**Comment by anguoyang** [comment]
@livarcocc when I opened the json file in VS, it acted as common editor as notepad, no relevant project files created.

**Comment by seanshpark** [comment]
@anguoyang , try with "File" > "Open" > "Project/Solution..."

**Comment by anguoyang** [comment]
@seanshpark  Thanks a lot, it worked!!!

**Comment by anguoyang** [comment]
Kang sa mi da! @seanshpark , it could be opened and compiled successfully in VS, however, it could not be run due to "there is no command in project.json, so it could not be startup"?

**Comment by seanshpark** [comment]
@anguoyang , "chun man e yo~", for me, I've copied the output DLL, say "output.dll" file to my Linux(Ubuntu 14.04) and ran with
```./corerun output.dll```
where required DLLs exist in the same directory, just for testing.

**Comment by seanshpark** [comment]
If you can't find the DLL, right click on the "Project" and select "Properties". In the left "Build" tab, check on the "Product outputs on build".  You can see the DLL in "../artifacts/bin/..../Debug/dnxcore50/" folder.

**Comment by anguoyang** [comment]
굿 모닝 @seanshpark , I would like to build and run/debug it within visual studio, the IDE is powerful for debugging, after that, I will copy it into ubuntu to run it. My problem is, I could not run/debug the project in visual studio.

**Comment by seanshpark** [comment]
@anguoyang , hello. I had the same problem. I'm not sure but please try adding this in `project.json`.
```
  commands: {
     "start": "(your project name appearing in VS IDE)"
  },
```
`start` string will appear in the `debug go` button on the toolbar. You can give anything if you want :)

One more thing. When I open the `project.json` file in the IDE, there appears an URL on top of the window: `http://json.schemastore.org/project` . If you open this link, it shows the schema of this `project.json` with some useful information.

**Comment by blackdwarf** [comment]
This issue is dealing with DNX tooling which has been deprecated as of RC2 of .NET Core. With that I will close this issue. You can use the [DNX migration guide](https://docs.microsoft.com/en-us/dotnet/articles/core/migrating-from-dnx) to migrate DNX-based projects to RTM projects. RTM was released on 27th of June.

With this, I will close this issue. If you run into any problems with using .NET Core RTM, please file an issue on the dotnet/cli repo. Thanks!
