### ISSUE TITLE
 Is there a tool like ILMerge used to merge the .net core  program?

### ISSUE THREAD

**Issue by maikebing** [dotnet/core#600]
Merge all dlls into an executable file！

**Comment by benaadams** [comment]
Like the open sourced ILMerge? https://github.com/Microsoft/ILMerge

Though .NET Core and corefx itself is uses the mono linker which the .NET Core version itself is called IILLink https://github.com/mono/linker/pull/25 so that may work better?

**Comment by Petermarcu** [comment]
@russellhadley any ideas here?

**Comment by Nate-Wilkins** [comment]
This would be fantastic! I've wanted an easier way to do this from .NET for so long.

**Comment by Petermarcu** [comment]
@russellhadley is there someone @maikebing can watch to see progress in this direction? 

I don't think we need to keep this issue open as we have it tracked here: https://github.com/dotnet/cli/issues/7737
