### ISSUE TITLE
Just says dotnet isnt found..

### ISSUE THREAD

**Issue by Alaphine17** [dotnet/core#6003]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when i type in dotnet new console in visual studio code i get this error message

 It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

but i downloaded .net

**Comment by mairaw** [comment]
Can you paste the results of running `dotnet --info`?
