### ISSUE TITLE
Official support for .net on FreeBSD (or any other *BSD)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/core#6004]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Official-support-for-net-on-FreeBSD-or/1340213)._

---
**Official support for .net on FreeBSD (or any other *BSD)**
Just one step for "WORA". I think it is *BSD.

---
#### Feedback Bot on 2/17/2021, 10:59 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by wimdevriendt** [comment]
Any news for .net 5.0 core on FreeBSD ?

**Comment by svick** [comment]
The issue to follow regarding that is https://github.com/dotnet/runtime/issues/14537.

**Comment by mairaw** [comment]
Thanks @svick. Closing this one as a duplicate then.
