### ISSUE TITLE
Can I open a Discussion on an Idea about the runtime free version of .net?

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/core#6007]
Can I open a Discussion on an Idea about the runtime free version of .net?

Once managed code and runtime was an advantage of the java and .net. But as time is passed, now .net runtime is a big downside of the .net. Especially when we have to upgrade to the new version every 3 years, that is costly. 

Many solution architects, including me, are seriously considering starting to migrate on native code platforms. Go, Rust, Moder C++.

I love C# and would be happy If I see runtime less .net core edition, having optional classes without GC. With reference counters (e.g., smart pointers in C++) and user management (manually free up memory).
I’m really interested in what the community and Microsoft itself think about it?

**Comment by antonfirsov** [comment]
Sure, feel free to open a discussion under the runtime repo, you have better chance to reach out to relevant people than here:
https://github.com/dotnet/runtime/discussions
