### ISSUE TITLE
.NET Core March 2021 Update -  .NET 5.0.200 SDK

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6010]
Today we are releasing .NET 5.0 200 SDK as a supported SDK with the release of [Visual Studio 16.9](https://docs.microsoft.com/visualstudio/releases/2019/release-notes#16.9.0)

Release Notes 
[5.0.200 SDK](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.3/5.0.200-sdk.md)

Please report any issues you find with .NET 5.0.200 SDK, by responding to this issue.

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.200 | 
|--|--|
| Ubuntu 16.04   | ✅  | 
| Ubuntu 18.04    | ✅  | 
| Ubuntu 20.04   | ✅  | 
| Ubuntu 20.10   | ✅  | 
| Centos 7    |✅  | 
| Debian 9     | ✅  |
| Debian 10      | ✅  | 
| Fedora 32    |  | 
| Fedora 33    |   | 
| OpenSUSE 15   | ✅  | 
| SLES 12      | ✅  | 
| SLES15    | ✅  |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [ ] Trouble installing 5.0.200 SDK on Fedora 32/33. Part of the installation is coming from packages.microsoft.com (the SDK) and the runtime coming from the native Fedora update repo and the two use a different installation root. packages.microsoft.com is trying at /usr/share/dotnet while the Fedora installers go to /usr/lib64/dotnet. Similar issue occur with CentOS as well.

**Comment by nighby** [comment]
This isn't a SDK issue per se, but the file path for the F# compiler changed between 5.0.103 and 5.0.200. /usr/share/dotnet/sdk/5.0.103/FSharp/fsc.exe and /usr/share/dotnet/sdk/5.0.200/FSharp/fsc.dll respectively.

This has not appeared in any documentation, and breaks some tooling (e.g. websharper) that used a hardcoded assumption (see [here](https://github.com/dotnet-websharper/core/issues/1123) for this mornings fun)

**Comment by MaxHayman** [comment]
typed conditional expressions now require casting? I couldn't find any mention this. Works fine in 103 but produces an error in 200. 

```
        static void Main(string[] args)
        {
            bool k = true;
            ushort b = k ? 1 : 0;
            Console.WriteLine("Hello World! " + b);
        }
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'int' to 'ushort'. An explicit conversion exists (are you missing a cast?)	ConsoleApp8	Program.cs	10	Active
```

**Comment by vgist1** [comment]
Wo

> typed conditional expressions now require casting? I couldn't find any mention this. Works fine in 103 but produces an error in 200.
> 
> ```
>         static void Main(string[] args)
>         {
>             bool k = true;
>             ushort b = k ? 1 : 0;
>             Console.WriteLine("Hello World! " + b);
>         }
> ```
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0266	Cannot implicitly convert type 'int' to 'ushort'. An explicit conversion exists (are you missing a cast?)	ConsoleApp8	Program.cs	10	Active
> ```
> 
> This seems pretty breaking and in a minor release? I got less errors including every migration from Framework to 5.0 so far.

Something interesting I noticed is that if I build that exact same code with Visual Studio it works out of the box and subsequently dotnet build also works, however, if I try to use dotnet build prior to building it from cli it will error not matter what.

**Comment by pentp** [comment]
Upgrading from 5.0.103 to 5.0.200 SDK seems to downgrade/regress the runtime somehow, although the listed runtime versions are identical (Microsoft.NETCore.App 5.0.3). Tests that used to work fine are now failing with `InvalidProgramException: Common Language Runtime detected an invalid program`.

I've been unable to consistently repro it locally because of an unrelated issue with MSTest.TestAdapter that is broken in v2.2.1 - after narrowing down my local testing issues to that package version (after trying reinstalling, cleaning caches) this InvalidProgramException doesn't happen locally anymore. But build servers are failing somewhat consistently (about 80% of the time). This looks suspiciously like something has the same version but different contents and depending on installation/caching order it ends up running on either the broken or normal version.

**Comment by fabriciomurta** [comment]
> Something interesting I noticed is that if I build that exact same code with Visual Studio it works out of the box using .net 5.0.200 and subsequently dotnet build also works, however, if I try to use dotnet build prior to building it from IDE, cli will error not matter what.

Here I upgraded both .NET 5.0.103 to 5.0.200 -and- VS from 16.8.z to 16.9.0. In fact, I just upgraded VS Community and .NET 5.0.200 came in the package (commandline dotnet says now 5.0.200).

The same problem is reproducible both in commandline and visual studio.

**Comment by wzchua** [comment]
@MaxHayman https://github.com/dotnet/roslyn/issues/51597

**Comment by rbhanda** [comment]
Closed in favor of https://github.com/dotnet/core/issues/6035
