### ISSUE TITLE
Update release notes link on dotnet.microsoft.com for correct branch

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/core#6016]
In https://dotnet.microsoft.com/download/dotnet/5.0, the link there is master (it redirects automatically to `main` with a message saying "Branch master was renamed to main.").

It could be better to have the links point to main directly.

cc: @mairaw

**Comment by mairaw** [comment]
This would be fixed by #5997.

**Comment by MagicAndre1981** [comment]
The Release Notes from the Releases here on github still point to master 

![image](https://user-images.githubusercontent.com/8274816/119639003-7c11d200-be17-11eb-8ada-7b416ee309d8.png)

@mairaw @terrajobst
