### ISSUE TITLE
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.

### ISSUE THREAD

**Issue by web-jeromejose** [dotnet/core#6018]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by web-jeromejose** [comment]
![image](https://user-images.githubusercontent.com/1982297/109911487-25e43580-7ce5-11eb-8ce5-8320d347eaa7.png)
![image](https://user-images.githubusercontent.com/1982297/109911491-28df2600-7ce5-11eb-98be-8d4fdf710ab1.png)

**Comment by antonfirsov** [comment]
Assigning area owners of docker tutorials: @shirhatti @nishanil

**Comment by nishanil** [comment]
@web-jeromejose Hey! this looks like an issue similar to the ones reported here: https://github.com/docker/for-win/issues/1825 

You may want to try running `docker run hello-world` first to make sure Docker is setup correclty.

**Comment by shirhatti** [comment]
Unless there's a regression in the Docker that I'm not aware of, that isn't the case. The Docker for Windows installer creates a new group `docker-users` and adds the user that ran the installer to that group.

Assuming you don't want elevation every time you run a docker command, considering adding yourself to that group.

Beyond that suggestion, we can't really help you with your current problem. I'd recommend asking any additional questions about setting up docker correctly in the [Docker for Windows forum](https://forums.docker.com/c/docker-desktop-for-windows/)
