### ISSUE TITLE
No SDK's were found

### ISSUE THREAD

**Issue by ZephyrDogma** [dotnet/core#6019]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

like i installed the SDK but when i create a project in Visual Studio Community it shows like this:
![image](https://user-images.githubusercontent.com/77338971/109996882-8dab7800-7d07-11eb-8d28-72bede1cda37.png)
and as u can see in the red box it isn't showing correctly, as in theres no projects showing thats isnt correct!

Also when i do this:
![image](https://user-images.githubusercontent.com/77338971/109997760-702ade00-7d08-11eb-89d4-4935e4333c31.png)
i get this error

Any help guys?

**Comment by ZephyrDogma** [comment]
mariaw here it is:
![image](https://user-images.githubusercontent.com/77338971/110006477-a02aaf00-7d11-11eb-8153-c0a85b8483a6.png)

**Comment by mairaw** [comment]
And your Windows is x64, correct?

It seems you encountered the same issue as described in this issue where I added a step-by-step on how to fix it:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

Me avisa se funcionou ok?

**Comment by ZephyrDogma** [comment]
thank u soo much @mairaw u solved my issue

**Comment by mairaw** [comment]
Great to hear!

**Comment by antonfirsov** [comment]
Closing, since the issue seems to be resolved. @ZephyrDogma feel free to reopen/open new issues if you encounter further problems!
