### ISSUE TITLE
Missing EOL date in releases-index.json for 5.0

### ISSUE THREAD

**Issue by omajid** [dotnet/core#6033]
All other entries have a `eol-date` key which is either a date (past or future) or even `null`. But 5.0 doesn't:

https://github.com/dotnet/core/blob/35cb36103c4caaf36f5203dd8e3d41ee0f01a733/release-notes/releases-index.json#L15-L25

**Comment by antonfirsov** [comment]
@rbhanda is this something we need to fix?

**Comment by omajid** [comment]
https://dotnet.microsoft.com/platform/support/policy/dotnet-core says the EOL date is "around February 2022".

**Comment by mairaw** [comment]
Because it's dependent on when .NET 6 actually releases, we don't have a firm date EOL daye. We were trying to see if we can at least add month and year to the 5.0 release.

**Comment by antonfirsov** [comment]
>  We were trying to see if we can at least add month and year to the 5.0 release.

I assume then it can be updated sometime later after the decision has been made? Is there any way to label this issue so it's not lost? Or should we just close it for now?

**Comment by mairaw** [comment]
I do have some ongoing PRs for the website to test this, so I don't think it will be forgotten.

**Comment by omajid** [comment]
Thanks!

Just to clear up any confusion: my original bug report isn't about the website: it's about the `releases-index.json` file maintained in this repo.

**Comment by mairaw** [comment]
Correct @omajid. But any changes to the releases-index.json file impacts the website because those files are the source of truth for our download pages.

**Comment by mairaw** [comment]
EOL is now present for all releases. Closing.
