### ISSUE TITLE
.NET March 2021 Update - 5.0.4, 3.1.13, 2.1.26

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6035]
Release Notes 
[5.0.4](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.4/5.0.4.md)
[3.1.13](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.13/3.1.13.md)
[2.1.26](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.26/2.1.26.md)

Please report any issues you find with .NET 5.0.4, .NET Core 3.1.13 or .NET Core 2.1.26, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.4 | 3.1.13 | 2.1.26 
|--|--|--|--|
| Ubuntu 16.04   | ✅  | ✅  | ✅  |
| Ubuntu 18.04    | ✅  | ✅  | ✅  |
| Ubuntu 20.04   | ✅  | ✅  | ✅  |
| Ubuntu 20.10   | ✅  | ✅  | ✅  |
| Centos 7    | ✅  | ✅  | ✅  |
| Debian 9     | ✅  | ✅  | ✅  |
| Debian 10      | ✅  | ✅  | ✅  |
| Fedora 32    | ✅  |  ✅ | ✅  |
| Fedora 33    | ✅  | ✅  | ✅  |
| OpenSUSE 15   | ✅  | ✅  | ✅  |
| SLES 12      | ✅  | ✅  | ✅  |
| SLES15    | ✅  | ✅  | ✅  |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [x] 2.1.26 is not updated on https://dotnet.microsoft.com/download/dotnet/2.1 . 
- [x] 5.0.4 release date is in wrong format on https://dotnet.microsoft.com/download/dotnet/5.0 - https://github.com/dotnet/core/pull/6040 to resolve this

**Comment by sharkk121** [comment]
https://dotnet.microsoft.com/download/dotnet/5.0 says v5.0.4 released on 2021-09-03, which is not consistent with the date format of previous releases

**Comment by rbhanda** [comment]
Hi @sharkk121 https://github.com/dotnet/core/pull/6040 is created to resolve this issue.

**Comment by martyspiewak** [comment]
https://dotnet.microsoft.com/download/dotnet/5.0 says v5.0.3 was released on 2021-03-02, which is really the date that SDK v5.0.200 was released, but v5.0.3 was originally released with SDK v5.0.103 [on 2021-02-09](https://github.com/dotnet/core/blob/7b972d2c0a53500caa72de0bb49d83d7aaf93aab/release-notes/5.0/releases.json#L11).

Is there a way to get separate release dates for runtime versions and SDK versions to avoid this case where it looks like v5.0.3 was released a month later than it initially was?

**Comment by rbhanda** [comment]
Thanks for letting us know @martyspiewak . Adding @leecow and @mairaw 
It seems there is no good way for us right now to be able to differentiate the different dates between 5.0.200 SDK and .NET 5.0.3 releases

**Comment by leecow** [comment]
There's not a way to differentiate the dates in a release combination like this at the movement. The release metadata  ([releases.json](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json)) which drives the site and a bunch of other things was created before the notion of shipping an SDK separate from a "full" release identified under the Runtime version "umbrella" was conceived.

Something we're thinking about now and will hopefully have worked out before the next time the situation comes up.

**Comment by cgountanis** [comment]
After installing no net5.0 projects load?

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/6129
