### ISSUE TITLE
Running The File

### ISSUE THREAD

**Issue by count-source** [dotnet/core#6047]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Exited with error code 134
watch : Waiting for a file to change before restarting dotnet

**Comment by count-source** [comment]
Was there i can install Visual Studio Community with blue Logo on my linux
system......i have noted the other does not have  all the features

**Comment by Pilchie** [comment]
@pranavkm - do you know what the `dotnet watch` error above means?

**Comment by pranavkm** [comment]
There's a reference to this from the compiler crashing (https://github.com/dotnet/sdk/issues/9454) which could happen as part of the `dotnet run` that launch invokes. 

@count-source can you include all of your console output from running `dotnet watch run`?. Thanks!

**Comment by count-source** [comment]
No, I don't.

**Comment by count-source** [comment]
Was there way i can install the Visual Studio Community with the Purple log on my Linux System i have noted they differ......

**Comment by count-source** [comment]
i'm Forced to use Rider IDE

**Comment by count-source** [comment]
_that's not so good  i will have to migrate to windows
