### ISSUE TITLE
Releases.json doesn't provide zip files for linux sdks/runtimes

### ISSUE THREAD

**Issue by timmydo** [dotnet/core#6048]
AB#1285371
We were previously consuming linux .NET SDKs using the pattern: $"https://dotnetcli.azureedge.net/dotnet/Sdk/{netSdkVersion}/dotnet-sdk-{netSdkVersion}-linux-{arch}.zip";

We aren't able to migrate to using releases.json/Microsoft.Deployment.DotNet.Releases since this doesn't have matches: netSdkVersion.Files.First(r => r.Rid == $"linux-{arch}" && r.FileName.EndsWith(".zip")).Address.ToString();

sample json file referenced:
https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json

this link should probably be using the CDN (https://dotnetcli.azureedge.net/dotnet/release-metadata/6.0/releases.json)

**Comment by leecow** [comment]
@mairaw, I'm going to add Linux *.zip files to the release process and releases.json files but there's no need to surface them on the marketing site. *tar.gz files are still fine for that. The change will be live for the April releases. 

cc @rbhanda

**Comment by leecow** [comment]
@timmydo, I'm noticing that the Runtime does not produce *linux-x64.zips for 3.1, 5.0 or 6.0. Is it sufficient for your needs to pick up only the SDK linux zips?

**Comment by mairaw** [comment]
sounds good @leecow. Thanks for the heads up.

**Comment by timmydo** [comment]
@leecow that's fine--our pipeline is only using the SDKs (and getting the runtime bits from them). thanks

**Comment by danmoseley** [comment]
@leecow is this resolved now - can we close?

**Comment by leecow** [comment]
Yes, looks like the issue is resolved.
