### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Reddd18** [dotnet/core#6051]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows
Im don't know how to run the program.
Please help :)

**Comment by antonfirsov** [comment]
The next tutorial step explains how to run the program:
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run

Does this help, or are you stuck with something else?
