### ISSUE TITLE
How to call a .NET 4.6.2 DLL from a .NET Core MVC Web App

### ISSUE THREAD

**Issue by birdus01** [dotnet/core#606]
I'd like to write a web app in .NET Core, but I need to call a DLL that was compiled for .NET 4.6.2. Is this possible? I'm using Visual Studio 2017.

**Comment by Petermarcu** [comment]
This is something we're looking to make possible in the upcoming update to VS. The plan is to let you reference the dll but depending on the dll, it may or may not work depending on what it depends on.

**Comment by the-super-coder** [comment]
I think if you chose ASP.Net Core Web Application (.Net Framework), it will support all Libs and Dlls for .Net.

I was looking for TransactionScope in .Net Core which is not yet implemented in .Net Core v1 so I chose the target framework as .Net for now, until the feature arrives for .Net Core.

Hope it helps.

**Comment by richlander** [comment]
See: https://github.com/dotnet/core/pull/727

**Comment by Petermarcu** [comment]
This is now possible from a .NET Core 2.0 project. I am going to close this. It's expected to work so if you hit any issues, please open a new issue with the specific details.

**Comment by troncomputers** [comment]
Project ASP .NET Core 2.0. I referenced .NET Framework dll. 
```html
<div class="test">
    <form method="post">
        <input type="submit" value="Zapisz" />
    </form>
</div>
```
```csharp
        public void OnPost()
        {
            Utils.Logowanie();

            Utils.DodajKontrahenta();
            Utils.DodanieTowaru();
            Utils.DodanieFaktury();

            Utils.Wylogowanie();
        }
```
All this methods uses methods from referenced dlls. And when I hit `Zapisz` button I'm getting this:
```
BadImageFormatException: Could not load file or assembly 'ICDNBase, Version=2018.0.1.549, Culture=neutral, PublicKeyToken=5179454a0b814fab'. 
An attempt was made to load the program in an incorrect format.
```

[Utils.zip](https://github.com/dotnet/core/files/1558509/Utils.zip)


![reference_net_core](https://user-images.githubusercontent.com/29543667/33984352-a2ce2ec0-e0b7-11e7-8a39-ca1571579acf.png)

**Comment by nilanthasj** [comment]
Is this possible in .NET Core 2.0..? I have some issues in doing this...

**Comment by Petermarcu** [comment]
If you have the latest SDK's and Visual Studio, please open a new issue with the details of the issues you are encountering.

**Comment by aaronfranke** [comment]
@Petermarcu Where are the instructions for setting this up? I wasn't able to figure it out by just blindly poking around.
