### ISSUE TITLE
dotnet não reconhecido

### ISSUE THREAD

**Issue by fabiosimedo** [dotnet/core#6061]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
@fabiosimedo vc instalou o SDK como diz no tutorial? E vc fechou o command prompt e abriu um novo depois da instalação?

**Comment by fabiosimedo** [comment]
Sim, mas reparei só depois que meu notebook tem arquitetura 32bits e precisaria de mais pacotes pra instalação
________________________________
De: Maira Wenzel ***@***.***>
Enviado: sexta-feira, 12 de março de 2021 00:51
Para: dotnet/core ***@***.***>
Cc: Fabio Simedo ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnet/core] dotnet não reconhecido (#6061)


@fabiosimedo<https://github.com/fabiosimedo> vc instalou o SDK como diz no tutorial? E vc fechou o command prompt e abriu um novo depois da instalação?

**Comment by mairaw** [comment]
Qual versão do Windows você está usando? Instalou as outras dependências?
