### ISSUE TITLE
Docker Build Error response from daemon: i/o timeout

### ISSUE THREAD

**Issue by sklau228** [dotnet/core#6063]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by sklau228** [comment]
OS : Windows 10 Pro
Installed and reinstalled Docker still not working. Was running the tutorial and stopped and then try to build docker for the sample following the instruction in your webpage and got the error above

**Comment by antonfirsov** [comment]
Assigning to area owners: @shirhatti @nishanil

**Comment by sughosneo** [comment]
Hi @sklau228, thank you for reaching out. 
Is your docker daemon running? You can verify that in your Docker Desktop Dashboard. 
If you face any issue while starting the docker instance itself, then you can try the following in the mentioned sequence.

- Try to do `Reset to factory defaults` in the docker desktop `Troubleshoot` tab.
- Try running docker desktop as an Administrator.
- Uninstall the docker desktop --> Manually clean up `C:\Users\<name>\AppData\Roaming\Docker` --> Reboot the machine --> Install the docker desktop again and see if it helps.

>!NOTE : All the above steps are expected to run on the dev environments only.
