### ISSUE TITLE
not recognise

### ISSUE THREAD

**Issue by anas1441** [dotnet/core#6070]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

i have install the dotnet sdk file but when i run into my command promtpt it keep telling that itis not recognise

C:\Users\NANOPAL>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\NANOPAL>

 am using windows 10
 32 os

**Comment by mairaw** [comment]
Did you close and open a new command prompt after installing the SDK?
