### ISSUE TITLE
The C# extension is still downloading packages

### ISSUE THREAD

**Issue by JustALaptopUser** [dotnet/core#6072]
So when I got on Vs Code I started my program and it said:

The C# extension is still downloading packages. Please see progress in the output window below.

Under the text it said the 2 things:

Open launch.json and cancel

**Comment by mairaw** [comment]
Would this be an issue with the Omnisharp extension @cartermp @shanselman?

@JustALaptopUser can you please paste a screenshot of what you're seeing so it's easier for us to try to help you?

**Comment by cartermp** [comment]
Yes, this would be an issue that goes here: https://github.com/OmniSharp/omnisharp-vscode

@JustALaptopUser can you file an issue in the linked repo with some diagnsotic info?
