### ISSUE TITLE
Issue .NET SDK Installation

### ISSUE THREAD

**Issue by 77922118** [dotnet/core#6073]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

terminal cd myApp
then, "No such file or directory"
OS: MacOS

Please help

**Comment by mairaw** [comment]
Did you run the previous command to create the project first? `dotnet new console -o myApp`

What was the output of that?

**Comment by 77922118** [comment]
Yes

**Comment by mairaw** [comment]
And what was the output of the command? 

If you run the `ls` command, does it list the directory?

**Comment by 77922118** [comment]
Yes, it did in fact

**Comment by mairaw** [comment]
So I don't understand how you can't do `cd myApp`. Can you paste a screenshot?

**Comment by 77922118** [comment]
Of course I did, I’m stuck on one of the last steps...let me explain them
to you tomorrow so I can tell you about it from a better perspective.

;)

Regards! 😀

**Comment by mairaw** [comment]
Any updates?

**Comment by 77922118** [comment]
Hello Maura! Not yet...I ll tell you within two days
