### ISSUE TITLE
Need Help .NET not working

### ISSUE THREAD

**Issue by MaplLeaf** [dotnet/core#6074]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I just installed VS Code and .NET and I can't run it. It says
" It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download"
      I've tried reinstalling too and it didn't work.

**Comment by mairaw** [comment]
Can you paste the output of running the command `where dotnet`?

**Comment by MaplLeaf** [comment]
this is what it says: C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

**Comment by mairaw** [comment]
So it seems you ran into the same issue as I explained here:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

Can you let me know if that helps to solve your issue? I'm assuming you have a x64 machine and that's why this isn't working. But please let me know otherwise.

**Comment by MaplLeaf** [comment]
It Worked! Thanks for helping me.
