### ISSUE TITLE
Port already in use

### ISSUE THREAD

**Issue by mjl38** [dotnet/core#6077]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Port is already in use by process "dotnet". If I kill the process it automatically starts again.
Error message:
at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
.....
watch : Exited with error code 134
watch : Waiting for a file to change before restarting dotnet...

When I go to http://localhost/5000, I'm automatically redirected to https://localhost:5001 (httS !!)
I do see some text WELCOME and a link to "Learn about building Web apps with ASP.NET Core", but the menu icons on the left are missing and the page looks very simple. Not as shown on the website.
Sorry I'm a noob, maybe there's something else running from a previous attempt I tried with .Net?

If I edit LaunchSettings.json and use a different port, everything works fine.

kind regards,
MiguelL

![Screenshot from 2021-03-20 05-01-36](https://user-images.githubusercontent.com/8222403/111859513-6a084480-8939-11eb-8bc1-214857229cc7.png)

**Comment by mairaw** [comment]
@danroth27 @Pilchie can you help here?

**Comment by Pilchie** [comment]
@pranavkm any ideas?  Looks like maybe you ran a new mvc app first and it's still running.

@mjl38 what process did you kill above? The `dotnet watch` one?  It looks like you've got another app still running on your system maybe from another tutorial or command?

**Comment by mjl38** [comment]
Thank you all for answering.
Yes I probably tried another example application some weeks ago, but I think I rebooted my PC when I had the problem and still could not use port 5000 after that.
Strangely enough it now all seems to be working fine and I no longer have more than one "dotnet" running when I run the sample app.
Doing a "netstat -tulpn" would show several dotnet services running. The only one that allowed itself to be killed was the "dotnet watch" one, but of course that's the one I was trying have making use of port 5000.
I must have done something wrong, that's obvious, but can no longer reproduce.
regards,
MiguelL

**Comment by Dzivo** [comment]
Getting the same thing in codespaces on github when trying to run my project
