### ISSUE TITLE
Error while RUN

### ISSUE THREAD

**Issue by AKIIIIIL** [dotnet/core#6078]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows 64 bit

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![dot net error](https://user-images.githubusercontent.com/81112379/111918631-50c0de80-8a86-11eb-8482-664af099594d.png)
![dot net error 1](https://user-images.githubusercontent.com/81112379/111918677-882f8b00-8a86-11eb-8201-a050c67a1943.png)

**Comment by mairaw** [comment]
Can you show what are the contents of that directory @AKIIIIIL?

Your Program.cs looks correct. This is what my `myApp` folder looks like:
![image](https://user-images.githubusercontent.com/12971179/112068066-671e7700-8b26-11eb-837b-7ebdb57f1024.png)
