### ISSUE TITLE
Problema na execução do App

### ISSUE THREAD

**Issue by jessicazaparolli** [dotnet/core#6082]
C:\Users\Jessica\myApp>Hello World
'Hello' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\Jessica\myApp>

**Comment by ltouro** [comment]
Hi Jessica,

The command you typed is not valid. The executable for .NET is called "**dotnet**". You can start trying with the below command to make sure everything is installed:
```
dotnet -v
```

**Comment by mairaw** [comment]
@jessicazaparolli pelo visto vc está tentando seguir o tutorial https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial.

Até onde vc conseguiu seguir? Você conseguiu instalar o SDK e o comando `dotnet` funcionou?

O programa vai escrever Hello World na tela quando a execução for completada com sucesso. Nos dê mais detalhes para tentarmos te ajudar.
