### ISSUE TITLE
didnt download properly

### ISSUE THREAD

**Issue by RainbowJeremy** [dotnet/core#6084]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you give more information about what's happening?

**Comment by RainbowJeremy** [comment]
It’s fine, my bad
