### ISSUE TITLE
Error when trying to run the command docker build

### ISSUE THREAD

**Issue by beyond-kernel** [dotnet/core#6088]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows 10

When I tried to run the tutorial step by step, the prompt returned an error when I ran the run step for the docker build -t docker command.

Error: 
**rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR**

Dockerfile: 

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY MyMicroService.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MyMicroService.dll"]

**Comment by mairaw** [comment]
@nishanil @shirhatti can you help with this issue?

**Comment by jamesmontemagno** [comment]
So the issue here is "echo . > Dockerfile" actually puts an invalid character :( 

Delete that file and create a new one and then open and copy it in.

**Comment by jamesmontemagno** [comment]
additionally, if you have .NET Core 6 installed you will need to chagne the images to 6.0

**Comment by beyond-kernel** [comment]
That's work when i change the version of my .NET framework in the Dockerfile, thanks @jamesmontemagno

**Comment by jamesmontemagno** [comment]
I just updated the tutorial to specify .NET 5 as the version to create. This was a good find :)
