### ISSUE TITLE
On executing docker build -t mymicroservice .  command no image is being created.

### ISSUE THREAD

**Issue by prasadraju82** [dotnet/core#6092]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

After executing docker build -t mymicroservice . command in windows. It returned with the following message.
_Sending build context to Docker daemon  17.41kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
5.0: Pulling from dotnet/sdk
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries_

No image have got created.

Docker version 20.10.5, build 55c4c88

**Comment by jamesmontemagno** [comment]
So the issue here is "echo . > Dockerfile" actually puts an invalid character :( 

Delete that file and create a new one and then open and copy it in.

**Comment by mairaw** [comment]
I'm closing this since the tutorial has been updated to fix this. But let us know if you're still having issues.
