### ISSUE TITLE
space is required?

### ISSUE THREAD

**Issue by synapsys11** [dotnet/core#6094]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

This is the problem:  Notice I missed a space between get; and set;  The space is not required in C#, but it is here!  Without the space, you get a confusing runtime exception that it cannot convert a string to an int!
    [Parameter]
    public int incrementAmount {get;set;} = 1;

**Comment by mairaw** [comment]
I was able to run the app without a space between get; and set;

@danroth27 do you know anything about this?

**Comment by danroth27** [comment]
I've never seen this before. The space definitely shouldn't be required even in a .razor file.

**Comment by mairaw** [comment]
@synapsys11 maybe paste the contents of your Counter.razor file and the confusing error message you're getting so we can try to help you.
