### ISSUE TITLE
It was not possible to find any installed .NET Core SDKs

### ISSUE THREAD

**Issue by JohnGuih** [dotnet/core#6095]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows 10

I trying to do the tutorial but i am getting stuck when i use the command "dotnet new webApp -o myWebApp --no-https" the terminal send me this:
"It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download"

**Comment by mairaw** [comment]
Hi @JohnGuih, can you paste the output of running the command `where dotnet`?

If your system is x64 and the output returns the following:
C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

You might be able to fix that as explained here: https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by JohnGuih** [comment]
Thank you for your help

C:\Users\User>where dotnet
C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

**Comment by mairaw** [comment]
That seems like the same issue then. Your machine is x64, correct?

If so, try the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535. 

Let me know if that works.

**Comment by ElvenSpellmaker** [comment]
For those who stumble upon this and are trying to get a Web App in a container working, for me you need to set the `WEBSITES_ENABLE_APP_SERVICE_STORAGE` to false, else it obliterates your `/home/site/wwwroot` directory.

https://github.com/Azure/azure-cli/issues/16738#issuecomment-838229398

**Comment by hrai** [comment]
> Hi @JohnGuih, can you paste the output of running the command `where dotnet`?
> 
> If your system is x64 and the output returns the following: C:\Program Files (x86)\dotnet\dotnet.exe C:\Program Files\dotnet\dotnet.exe
> 
> You might be able to fix that as explained here: [#5962 (comment)](https://github.com/dotnet/core/issues/5962#issuecomment-780084535)

I had to run `where.exe dotnet`

**Comment by mairaw** [comment]
Thanks @hrai. I've updated my comment here. I've changed my suggestion on recent issues to where.exe dotnet so it works on both command prompt and PowerShell.

**Comment by Malcova34** [comment]
> Hola@JohnGuih¿Puedes pegar la salida de ejecutar el comando `where.exe dotnet`?
> 
> Si su sistema es x64 y la salida devuelve lo siguiente: C:\Archivos de programa (x86)\dotnet\dotnet.exe C:\Archivos de programa\dotnet\dotnet.exe
> 
> Es posible que puedas solucionarlo como se explica aquí: [#5962 (comentario)](https://github.com/dotnet/core/issues/5962#issuecomment-780084535)

I really appreciate it!!! Love you :)))))

**Comment by danielvafranca** [comment]
Saved me, thank you
