### ISSUE TITLE
.NET Tutorial - Your First Microservice - runtime error 

### ISSUE THREAD

**Issue by pa035** [dotnet/core#6096]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro/run-docker
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I received the following error when running this command 
docker run -it --rm -p 3000:80 --name mymicroservicecontainer mymicroservice

It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.4 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64

I have the SDK installed and installed the runtime as directed in the error message, although I would have expected that the runtime would have been installed with the dotnet SDK

**Comment by mairaw** [comment]
It seems that you're trying to use the 3.1 SDK somehow.

Can you paste the contents of your Dockerfile?

The one from the tutorial is supposed to be using 5.0 SDK:
```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY MyMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MyMicroservice.dll"]
```
