### ISSUE TITLE
 The .NET Framework 4.7.2 redistributable does not apply to this operating system. Please download the .NET Framework 4.7.2 for your operating system from the <A HREF="http://go.microsoft.com/fwlink/?LinkId=863273">Microsoft Download Center</A>. 

### ISSUE THREAD

**Issue by navya39345** [dotnet/core#6097]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @navya39345, 
Can you provide a little bit more information about the issue you're having?
What version of Windows do you have?

I'm also curious on how you ended up in the  Hello World tutorial. I wanna make sure that people looking to download .NET Framework, don't end up there.
