### ISSUE TITLE
Add BigInteger(string value) in System.Numerics

### ISSUE THREAD

**Issue by PanosSakkos** [dotnet/core#61]
Hello,

I would like to initialize BigInteger instances with string values, like I'm used to from java.

1. Would you accept such an addition to the Framework?
2. In case you would, which project should I fork in order to create the patch?

Thank you in advance,
:panos

**Comment by stephentoub** [comment]
Like this?
https://msdn.microsoft.com/en-us/library/dd268231(v=vs.110).aspx

**Comment by PanosSakkos** [comment]
Yes! :+1: 

I found it a few moments ago and I was about to close my issue :smile:
