### ISSUE TITLE
net framerork

### ISSUE THREAD

**Issue by ahmetkaratas34** [dotnet/core#6102]
hi, i am using windows 2019 server and i want to install net framework 1.1. I think it's giving an error because it's incompatible. Is there any way I can set it up?

**Comment by Jozkee** [comment]
Can you share more details about which error you are facing?

**Comment by Jozkee** [comment]
.NET framework 1.1 is unsupported on Windows Server 2008 R2 or higher. 
https://docs.microsoft.com/en-us/troubleshoot/windows-client/deployment/dotnet-framework-1dot1-not-supported

You may consider install a supported version of .NET in your server e.g: .NET 5.

**Comment by ahmetkaratas34** [comment]
The program I use only works with 1.1. Since 3.5 and 4.7 are installed in Server 2019, older versions cannot be installed. When I remove it, the server manager becomes unavailable.

**Comment by Jozkee** [comment]
@wli3 @dsplaisted @danmoseley is there any guidance that you may suggest for this case?

**Comment by danmoseley** [comment]
@ahmetkaratas34 as @Jozkee noted,  .NET Framework 1.1 is not supported any more: https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework

You have two options
1. continue to use your app on a version of Windows on which you can successfully install .NET Framework 1.1. If you continue to use .NET Framework 1.1 you should be aware that it is not supported, so eg., it will not receive security patches.
2. migrate your app so it works on a supported version of .NET Framework, or .NET Core. 

This document will help you migrate your app:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/migrating-from-the-net-framework-1-1
