### ISSUE TITLE
how i can insert the progrm.cs in dotnet

### ISSUE THREAD

**Issue by bhavadharanish** [dotnet/core#6103]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You don't insert Program.cs. The command creates that file for you in the myApp directory. The page is only showing its contents.

Does that help?
