### ISSUE TITLE
Is Linux Mint support dropped from .NET 6?

### ISSUE THREAD

**Issue by loic-sharma** [dotnet/core#6105]
.NET 5.0 supports Linux Mint: https://github.com/dotnet/core/blob/8fa18840f8da2771e6bc09abe2c22d2f2f63062b/release-notes/5.0/5.0-supported-os.md#linux

.NET 6.0 support does not include Linux Mint: https://github.com/dotnet/core/blob/8fa18840f8da2771e6bc09abe2c22d2f2f63062b/release-notes/6.0/6.0-supported-os.md#linux

However, the `Support changes from .NET 5.0` section is empty: https://github.com/dotnet/core/blob/8fa18840f8da2771e6bc09abe2c22d2f2f63062b/release-notes/6.0/6.0-supported-os.md#support-changes-from-net-50

Is this expected?

**Comment by mairaw** [comment]
Tagging @leecow

**Comment by richlander** [comment]
Great question @loic-sharma. The short version is that I'm hoping we change (only to improve) our Linux distro support story in .NET 6. Let's just hold on this one until that lands. 

In short, the plan is to do two things:

- Orient support on distro families.
- Establish support tiers, along the following lines:
  - Tier 1: Directly tested by .NET Team (AKA, this is the distro we test for the family)
  - Tier 2: Indirectly tested by the .NET Team, by virtue of being a member of a tested family.
  - Tier 3: Community tested.

Linux Mint would fall into tier 2.

We're still working out (for the proposal) which of these tiers would have Microsoft support (like call support to get help).  We're also working out how community testing would work. Ideally, this information could be recorded someone.

Sound good?

**Comment by FagnerMoraes** [comment]
Use docker.

**Comment by loic-sharma** [comment]
Thanks, closing as this question was answered.
