### ISSUE TITLE
Exited with error code 1

### ISSUE THREAD

**Issue by Elson-KaiDong** [dotnet/core#6107]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows
watch : Exited with error code 1
watch : waiting for a file to change before restarting dotnet . . .

**Comment by Jozkee** [comment]
Thanks for reporting, can you provide more details about what you are specifically doing that triggers this error? Do you hit it consistently?

cc @wli3 @dsplaisted

**Comment by mairaw** [comment]
Tagging @danroth27  as well

**Comment by danroth27** [comment]
> watch : Exited with error code 1

Adding @pranavkm as well.

**Comment by mairaw** [comment]
Just closed #6124 as a duplicate of this one, even though that was on a Linux machine.
