### ISSUE TITLE
when I type docket --version in command prompt I get the following error "docker is not recognized as internal or external command

### ISSUE THREAD

**Issue by kumarsril** [dotnet/core#6113]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/install-docker
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you try to run this on a new command prompt?

**Comment by kumarsril** [comment]
Hi Maria,

Thanks. I got this resolved by running in anew command prompt as
elevated user - Admin. Thanks again
Srikumar
