### ISSUE TITLE
The System Cannot find Dockerfile while creating a Microservice

### ISSUE THREAD

**Issue by kumarsril** [dotnet/core#6114]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-file
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you help here @shirhatti @nishanil?  

It would be great if you could include screenshots @kumarsril
