### ISSUE TITLE
Error in Hello word (Edit your code) segment

### ISSUE THREAD

**Issue by divyesh1995** [dotnet/core#6115]
![Screenshot (19)](https://user-images.githubusercontent.com/33441245/113414157-f3a81f80-93d9-11eb-9e88-f466beb4f47f.png)

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

OS : Windows10

**Comment by mairaw** [comment]
Can you make sure you edited the Index.cshtml file and not the Index.cshtml.cs file? Sometimes, Windows will hide the file extension.

So, in the example below the Index.cshtml file is the first one and not the second.
![image](https://user-images.githubusercontent.com/12971179/108442395-d0e7f000-720b-11eb-8059-ff4d4e181304.png)

Let me know if that helps.
