### ISSUE TITLE
HOW TO RUN HELLO WORLD IN VS CODE USING C SHARP

### ISSUE THREAD

**Issue by snlinfo2** [dotnet/core#6117]
![csharp hello world1 image](https://user-images.githubusercontent.com/39646808/113489173-99cb5680-94ba-11eb-843f-57889389053b.png)
I CAN'T RUN THE CODE IN SCREENSHOT. I NEED HELP - I AM USING VS CODE 2019, WINDOWS10 ON SURFACE PRO4
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by knilecrack** [comment]
Press f5?

**Comment by snlinfo2** [comment]
> Press f5?

SEE THE ERROR MESSAGE POPUP

**Comment by Jozkee** [comment]
Looks to me as a configuration error; cc @filipw since he might know more about what's the issue.

**Comment by mairaw** [comment]
What happens if you run from the command-line like we show in the tutorial without using the VS Code debugger? Just trying to pinpoint the problem.

**Comment by snlinfo2** [comment]
Find below what happened when ran of cmd:
![run hello world in cmd](https://user-images.githubusercontent.com/39646808/113782469-26c81700-972a-11eb-9062-ce4cfe205d29.png)

**Comment by mairaw** [comment]
Thanks. So it's working from the CLI. Thanks for confirming @snlinfo2.

**Comment by knilecrack** [comment]
Can you post configuration from launch.json ?

**Comment by hez2010** [comment]
![image](https://user-images.githubusercontent.com/14960345/118523197-7d843000-b76f-11eb-8f46-c803164848ff.png)

You specified an invalid path for the executable in `.vscode/launch.json`.

**Comment by mairaw** [comment]
@snlinfo2 can you please paste the contents from your `.vscode/launch.json` file?
