### ISSUE TITLE
HTTP Error 500.24 - Internal Server Error

### ISSUE THREAD

**Issue by sglee** [dotnet/core#6119]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
Have you tried this https://forums.asp.net/t/2094251.aspx?HTTP+Error+500+24+Internal+Server+Error?
cc @Pilchie

**Comment by Pilchie** [comment]
Also take a look at https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/.  @jkotalik - I don't see 500.24 in the trouble shooting there.  Do you have any ideas?

**Comment by jkotalik** [comment]
That's an IIS error (not an error from ANCM). 

> An ASP.NET setting has been detected that does not apply in Integrated managed pipeline mode.

Looks like you may have a setting in your applicationhost.config that is invalid.
