### ISSUE TITLE
.net The path to an application .dll file to execute.

### ISSUE THREAD

**Issue by NO0ne-17** [dotnet/core#6120]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
Can you please provide more info. Is this error displayed when you type `dotnet` in the cmd?  
cc @wli3 @dsplaisted
