### ISSUE TITLE
Could not find a MSBuild project file in 'C:\Users\User'. Specify which project to use with the --project option.

### ISSUE THREAD

**Issue by mahbubulhaque00** [dotnet/core#6125]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
Are you running `dotnet watch run` on the directory that contains your csproj or passing it with `-p`?
cc @wli3 @dsplaisted

**Comment by mairaw** [comment]
As stated in https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create, you need to change directory running `cd myWebApp`. Did you do that @mahbubulhaque00 before running the `dotnet  watch run` command?
