### ISSUE TITLE
The Debug Executable

### ISSUE THREAD

**Issue by christianwinters1989** [dotnet/core#6140]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

The debug executable
'C:\Users\xxxxxx.xxxxx\myApp\bin\Debug\net5.0\myApp.exe' specified in the 'myApp' debug profile does not exist.

**Comment by Jozkee** [comment]
cc @mairaw.

**Comment by mairaw** [comment]
Can you provide more information about this? The tutorial doesn't tell you to search for the executable, it just runs the app with the CLI commands. Are you getting any error messages?
