### ISSUE TITLE
Certificate issues with brand new project

### ISSUE THREAD

**Issue by lrdickson** [dotnet/core#6147]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: Arch Linux

I was attempting to follow the tutorial to create a dotnet project using the cli and got the following error message:

```
$ dotnet new console -o helloWorld
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on helloWorld/helloWorld.csproj...
  Determining projects to restore...
/home/lyn/Projects/cs/helloWorld/helloWorld.csproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/home/lyn/Projects/cs/helloWorld/helloWorld.csproj : error NU3037: Package 'Microsoft.AspNetCore.App.Ref 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/home/lyn/Projects/cs/helloWorld/helloWorld.csproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
  Failed to restore /home/lyn/Projects/cs/helloWorld/helloWorld.csproj (in 394 ms).
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore
```
`

**Comment by Jozkee** [comment]
Does this error also shows when you run `dotnet restore`?
cc @rrelyea @nkolev92

**Comment by nkolev92** [comment]
You can dup it to https://github.com/NuGet/Home/issues/10712, the pinned issue in the https://github.com/NuGet/Home/issues repo.

**Comment by mairaw** [comment]
@richlander last comment on that issue is that the latest .NET 5 build resolves that. Is that accurate?

@lrdickson can you paste the output of `dotnet --info`?

**Comment by lrdickson** [comment]
It turns out that the issue was caused by a certification issue with the Arch Linux dotnet package.

I was able to get around the issue by installing the Arch Linux dotnet-runtime-bin.

**Comment by richlander** [comment]
@lrdickson -- can you point me to the Arch Linux dotnet-runtime package?

**Comment by richlander** [comment]
I found it already.

**Comment by richlander** [comment]
To continue my spam on this thread, we've been wondering if there are a significant number of Arch users (for .NET) and if we should provide better/more support. Thoughts? Can you answer @ https://github.com/dotnet/core/issues/6201
