### ISSUE TITLE
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified.

### ISSUE THREAD

**Issue by SergeyBorisov** [dotnet/core#6148]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
Looks similar to https://stackoverflow.com/q/40459280/4231460.
@MichaelSimons, I am not very familiar with docker, could you please verify if this is the same issue as the StackOverflow's post that I linked?

**Comment by mairaw** [comment]
Hey @SergeyBorisov, please check issue #6018 that has a couple of things for you to try and some recommendations.
