### ISSUE TITLE
new mobile app(flutter or xamarin or mauimui...)

### ISSUE THREAD

**Issue by swiftinitdotcom** [dotnet/core#6155]
We urgently want to develop small new mobile app(flutter or xamarin or mauimui...) Xamarin is going away it seems with forms changes so is flutter better as of now?

**Comment by mairaw** [comment]
@davidortinau @jamesmontemagno can you help? I don't have permissions to transfer this to dotnet/maui it seems.

**Comment by jamesmontemagno** [comment]
.NET MAUI is the evolution of Xamarin.Forms and expands to building cross-platform native iOS, Android, macOS, and Windows apps from a shared single code base.

Xamarin.iOS, Xamarin.Android, and Xamarin.Mac are being upgraded to .NET 6 and are being renamed to iOS for .NET, Android  for .NET, and Mac for .NET. 

All project can be upgraded directly to .NET 6 or to .NET MAUI if you are already doing Xamarin.Forms.

Xamarin.Forms will also be supported until the end of 2022. 

Read the following for more information:

**Comment by swiftinitdotcom** [comment]
I mean can we start right now(from today) and build production ready single version UI for android and iphone nicely(not 2 versions...)

**Comment by jamesmontemagno** [comment]
Yes, that is exactly what you can do with Xamarin.Forms today :)

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/

**Comment by swiftinitdotcom** [comment]
You mean if we want to build 40 native mobile app forms we do not have to build 80 forms(40 for ios and 40 for android)? Please confirm nd I will start right away!

**Comment by jamesmontemagno** [comment]
Nope, your UI is shared between iOS, Android, and Windows. With .NET MAUI it will also be shared with macOS as well.

so if you have 40 pages in your app it will be 40 total and they are shared.
