### ISSUE TITLE
please assist with this error 

### ISSUE THREAD

**Issue by kalaime** [dotnet/core#6164]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial//create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
C:\Users\Admin>dotnet new webApp -o myWebApp --no-https
Creating this template will make changes to existing files:
  Overwrite   appsettings.Development.json
  Overwrite   appsettings.json
  Overwrite   myWebApp.csproj
  Overwrite   Program.cs
  Overwrite   Startup.cs
  Overwrite   Pages/Error.cshtml
  Overwrite   Pages/Error.cshtml.cs
  Overwrite   Pages/Index.cshtml
  Overwrite   Pages/Index.cshtml.cs
  Overwrite   Pages/Privacy.cshtml
  Overwrite   Pages/Privacy.cshtml.cs
  Overwrite   Pages/_ViewImports.cshtml
  Overwrite   Pages/_ViewStart.cshtml
  Overwrite   Properties/launchSettings.json
  Overwrite   wwwroot/favicon.ico
  Overwrite   Pages/Shared/_Layout.cshtml
  Overwrite   Pages/Shared/_ValidationScriptsPartial.cshtml
  Overwrite   wwwroot/css/site.css
  Overwrite   wwwroot/js/site.js
  Overwrite   wwwroot/lib/bootstrap/LICENSE
  Overwrite   wwwroot/lib/jquery/LICENSE.txt
  Overwrite   wwwroot/lib/jquery-validation/LICENSE.md
  Overwrite   wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
  Overwrite   wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js
  Overwrite   wwwroot/lib/jquery-validation-unobtrusive/LICENSE.txt
  Overwrite   wwwroot/lib/jquery/dist/jquery.js
  Overwrite   wwwroot/lib/jquery/dist/jquery.min.js
  Overwrite   wwwroot/lib/jquery/dist/jquery.min.map
  Overwrite   wwwroot/lib/jquery-validation/dist/additional-methods.js
  Overwrite   wwwroot/lib/jquery-validation/dist/additional-methods.min.js
  Overwrite   wwwroot/lib/jquery-validation/dist/jquery.validate.js
  Overwrite   wwwroot/lib/jquery-validation/dist/jquery.validate.min.js
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css.map
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-grid.min.css
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-grid.min.css.map
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.css
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.css.map
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.min.css
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.min.css.map
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap.css
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap.css.map
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap.min.css
  Overwrite   wwwroot/lib/bootstrap/dist/css/bootstrap.min.css.map
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js.map
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.min.js
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.min.js.map
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.js
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.js.map
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.min.js
  Overwrite   wwwroot/lib/bootstrap/dist/js/bootstrap.min.js.map

Rerun the command and pass --force to accept and create.

**Comment by mairaw** [comment]
The command is telling you a project with the same name already exists. Have you ran the command before?

There are a couple of options here. If you don't need that project, you can delete the myWebApp folder and start over.

Let me know if this helps.
