### ISSUE TITLE
.net 4.5 is not a valid value for -f

### ISSUE THREAD

**Issue by jpyogesh** [dotnet/core#6167]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
That's correct. The supported values can be found at https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks.

.NET Framework 4.5 is a different product. Maybe you can tell me what you were looking for so I can better help?
