### ISSUE TITLE
Q: NuGet (Xplat) Server - long term strategy 

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/core#617]
Hi
dotnet core is depending (extremely) on Nuget (Protocol, and Gallery)

Now, we have May 2017 and there is no Nuget Server (pure core/xplat) available or at least planned.

For my own/private Nuget Server i must use the full blown (Framework >=4) asp.net and SQL-Server implementation or a Java Implementation (Nexus) or something else.....

All this does not increases my confidence in this system (and i like dotnetcore)

I know that Nuget is a different project and currently not part of the dotnet foundation, but it is also MS-coupled and the Project is really critical for dotnetcore.

What is the plan, what is the strategy?

@terrajobst et.al. ?

regards
Werner

**Comment by terrajobst** [comment]
This issue was moved to NuGet/NuGetGallery#3899
