### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by igho4j** [dotnet/core#6171]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

This simple project ran on my windows 10 but when I copied it to windows server 2016 to run, it gave the above error even after I carried out the same .net core and run time installations. I need solution on how to fix this.

**Comment by igho4j** [comment]
This simple project ran on my windows 10 but when I copied it to windows server 2016 to run, it gave the above error even after I carried out the same .net core and run time installations

**Comment by mairaw** [comment]
Can you run the command `dotnet --info` on the Windows Server machine to make sure you have the SDK installed.

Another command I'd ask you to run is `where.exe dotnet` so I can confirm something as well.
