### ISSUE TITLE
I've Encountered an issue

### ISSUE THREAD

**Issue by AbhishekAnand2** [dotnet/core#6176]
![Screenshot 2021-04-19 223537](https://user-images.githubusercontent.com/79047834/115275642-af4dab00-a15f-11eb-8afc-5843401acbf4.png)
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Are you just trying to run the project created by the `dotnet new webApp -o myWebApp --no-https` command or did you modify the project? And what if you type `dotnet run`? Does it also present the same errors? 

/cc @danroth27 @rainersigwald

**Comment by rainersigwald** [comment]
This sounds like dotnet/msbuild#6253/dotnet/roslyn#52467 which is a crash in error handling. If you can share more detailed steps to reproduce the problem, we might be able to get past the crash and find the underlying problem.
