### ISSUE TITLE
Installing .NET5.05 failed 

### ISSUE THREAD

**Issue by jchintor** [dotnet/core#6177]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed new .NET 5.0.5.  A  successful installation message appeared.

![Microsoft Windows Desktop Runtime - 5 0 5 (x64)](https://user-images.githubusercontent.com/1315984/115277270-10e72880-a112-11eb-8a91-0952997c7870.png)

I verified that it was installed with the following command;

C:\Users\John>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

Device Specifications:

Device name	LAPTOP-38MOEDH9
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Product ID	00325-96344-09962-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

Windows specifications:

Edition	Windows 10 Home
Version	20H2
Installed on	‎2021-‎03-‎18
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

Installed version: windowsdesktop-runtime-5.0.5-win-x64

Here is the command line error message: when I tried to create a console.

C:\Users\John>dotnet new console -o myApp
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
Hi @jchintor! Your screenshot shows that you installed the Windows Desktop Runtime, not the SDK.

You need to install the SDK in order to create and run the tutorial as described in the install step:
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

Clicking on the **Download .NET SDK** button should download the proper version. If you're still having issues after doing this, please let us know. We can test a few other things.
