### ISSUE TITLE
webApp

### ISSUE THREAD

**Issue by MistahWrite** [dotnet/core#6179]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows 10 VS Code

PS C:\Users\Chad\Documents\.NET\HelloWorld> dotnet watch run
watch : Started
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]C:\Users\Chad\Documents\.NET\HelloWorld\obj\Debug\net5.0\HelloWorld.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Index.cshtml.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Index.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Index.cshtml.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Privacy.cshtml.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in 
the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Privacy.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in 
the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Privacy.cshtml.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in 
the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Program.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Program.cs(6,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Program.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Program.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(9,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(10,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(14,31): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Index.cshtml.cs(11,31): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Privacy.cshtml.cs(11,33): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Index.cshtml.cs(13,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Privacy.cshtml.cs(13,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(24,39): error CS0246: The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Program.cs(19,23): error CS0246: The type or namespace name 'IHostBuilder' could not be found (are you 
missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Index.cshtml.cs(15,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Privacy.cshtml.cs(15,29): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(30,31): error CS0246: The type or namespace name 'IApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(30,56): error CS0246: The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(16,24): error CS0246: The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Startup.cs(21,16): error CS0246: The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(12,6): error CS0246: The type or namespace name 'ResponseCacheAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(12,6): error CS0246: The type or namespace name 'ResponseCache' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(13,6): error CS0246: The type or namespace name 'IgnoreAntiforgeryTokenAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(13,6): error CS0246: The type or namespace name 'IgnoreAntiforgeryToken' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(12,20): error CS0246: The type or namespace name 'Duration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(12,34): error CS0246: The type or namespace name 'Location' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(12,45): error CS0103: The name 'ResponseCacheLocation' does not exist in the current context [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]     
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(12,73): error CS0246: The type or namespace name 'NoStore' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(20,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]
C:\Users\Chad\Documents\.NET\HelloWorld\myWebApp\Pages\Error.cshtml.cs(22,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Chad\Documents\.NET\HelloWorld\HelloWorld.csproj]

The build failed. Fix the build errors and run again.
watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...

**Comment by mairaw** [comment]
I'm wondering if you have distinct projects under that C:\Users\Chad\Documents.NET\HelloWorld path?

If you created the app using the command `dotnet new webApp -o myWebApp --no-https`, the name of your csproj file should be myWebApp.
Maybe start over on a new location?

**Comment by chaos-ui** [comment]
yes starting over too
