### ISSUE TITLE
unable to run the application

### ISSUE THREAD

**Issue by munna8099** [dotnet/core#6189]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by munna8099** [comment]
C:\Users\liveininfracon\myApp>dotnet run
C:\Users\liveininfracon\myApp\Program.cs(5,11): error CS0101: The namespace 'myApp' already contains a definition for 'Program' [C:\Users\liveininfracon\myApp\myApp.csproj]
C:\Users\liveininfracon\myApp\Program.cs(7,21): error CS0111: Type 'Program' already defines a member called 'Main' with the same parameter types [C:\Users\liveininfracon\myApp\myApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by mairaw** [comment]
Can you show you what files you have in your project and what your Program.cs file looks like?

**Comment by simpleZed** [comment]
Can .net run natively on tizen?

**Comment by mairaw** [comment]
@simpleZed I'd recommend that you open a new issue since your question is not related to the original issue
