### ISSUE TITLE
im unable to run the appliation

### ISSUE THREAD

**Issue by munna8099** [dotnet/core#6190]
C:\Users\liveininfracon>dotnet new console -o myApp
Creating this template will make changes to existing files:
  Overwrite   myApp.csproj
  Overwrite   Program.cs

Rerun the command and pass --force to accept and create.

**Comment by mairaw** [comment]
This command is telling you that there's already a project with the same name. You have a couple of options like:
- You can pass the --force option as the command is telling you like `dotnet new console -o myApp --force`. This will overwrite the files listed there.
- Delete the myApp folder and start over
- Create the project in a different location

Let us know how that goes.
