### ISSUE TITLE
Unable to build or create new F# project w/.Net 5.0.5

### ISSUE THREAD

**Issue by lc9er** [dotnet/core#6191]
### Description

Building an existing project, or even creating a new one fails.
```
dotnet new console -lang F#
```
Running the command fails to create the project with the error: "error NU1100: Unable to resolve 'FSharp.Core (>= 5.0.0)' for 'net5.0'"

This was the first version of the .NET 5* SDK installed on this machine.

### Configuration

.NET SDK 5.0.5
Win 10 v2004 Build 19041.928
x64 arch

### Regression?
Uninstalling and downgrading to SDK 5.0.4

**Comment by mairaw** [comment]
@cartermp can you take a look? I can't repro this with SDK 5.0.202

**Comment by mattsonlyattack** [comment]
for me `dotnet nuget list source` was empty, added nuget and I was good..

**Comment by cartermp** [comment]
Hmmm, yeah, that would point towards some kind of setup error. FSharp.Core is just in the regular old NuGet feed, so I wonder if there's an SDK install issue?

**Comment by mattsonlyattack** [comment]
fyi

```
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by PhilT** [comment]
Oh my! This was driving me mad! Just tried to restore a project I haven't used on my laptop and was getting the same error message. 

As suggested by @mattsonlyattack `dotnet nuget list source`  was empty so doing  `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` then `dotnet restore` sorted it.

**Comment by mairaw** [comment]
@lc9er did you check your NuGet sources as suggested?

**Comment by KevinRansom** [comment]
@PhilT --- sometimes, and I really have no idea why the root nuget.config can be empty:

The file can be edited by notepad using:
````
notepad %appdata%\nuget\NuGet.Config
````
It should look like this:
````
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
````

**Comment by lc9er** [comment]
No - I'm sorry. I missed this thread. I had reverted to the previous
version, just to get up and running and have installed the latest version,
which is working as expected.

**Comment by mairaw** [comment]
No worries. I'll close the issue then.
