### ISSUE TITLE
receive a 'dotnet' is not recognized as an internal or external command error

### ISSUE THREAD

**Issue by NaraBBQ** [dotnet/core#6197]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro?sdk-installed=true
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Have you closed and started a new command prompt after installing .NET? Or where are you running the command from?
