### ISSUE TITLE
Error when creating new blazorwasm project

### ISSUE THREAD

**Issue by OkilSaber** [dotnet/core#6203]
Problem encountered  when creating new blazorwasm project
Operating System: windows 19042.928
Sdk and runtimes versions:
![image](https://user-images.githubusercontent.com/54351241/116470812-31cb1e80-a874-11eb-8fc4-0bf4e28b4bc4.png)

Here is what happens:
![image](https://user-images.githubusercontent.com/54351241/116470887-490a0c00-a874-11eb-9399-596e8c82309d.png)
and when I try to do a ``dotnet restore`` it always says the same errors.
What is weird is that on my linux computer I have the exact same sdks and runtimes and everything runs perfectly.

**Comment by mairaw** [comment]
I have helped a couple of folks on the last few days with error NU1100. In those cases, the `%appdata%\NuGet\NuGet.Config` file didn't have the package source configured it correctly.
Similar to what is explained here for a different issue https://stackoverflow.com/questions/62102318/hello-world-dotnet-core-example-not-working

So, can you make sure it lists https://api.nuget.org/v3/index.json as a package source?

This might happen if you installed chocolatey for example: https://github.com/chocolatey/choco/issues/2233

**Comment by OkilSaber** [comment]
I in fact have chocolatey installed.
I ran the command `dotnet nuget add source https://api.nuget.org/v3/index.json` and now everything works perfectly! Thank you for your help!

**Comment by mairaw** [comment]
Great to hear!
