### ISSUE TITLE
Error running dotnet tutorial

### ISSUE THREAD

**Issue by thirdrock09** [dotnet/core#6204]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

'dotnet' is not recognized as an internal or external command error,

**Comment by mairaw** [comment]
Have you closed and started a new command prompt after installing .NET?

**Comment by KleberTomazi** [comment]
Make sure that "C:\Program Files\dotnet" is part of the "path" system environment variable. If not, after adding, the problem should be resolved. :)
