### ISSUE TITLE
Template "Console Application" could not be created.

### ISSUE THREAD

**Issue by joemumu** [dotnet/core#6205]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm not sure how get permissions properly to make a new folder in system32 directory. Is it possible to go up one to a different folder or is it essential that it be in a certain place? There may be a spot allowed in windows folder. If I'm feeling extra brave I'll play with that. I probably did the unthinkable when it seemed easier to get permissions by taking ownership of folders. If you could even just point me in the right direction I know I can figure it out.  Maybe. I'm 65 but I've been with computers since 1992. I had a machine shop and I had to learn how to repair the computer by DOS. 386 DX40 I think it had a math co-processor in it. A guy in town built it for me. That thing set me back $3500.00  back then, but I had no choice. Between the cad cam program and sending programs generated to the machinery I didn't have much time, it needed to work right away. Anyway I'll get back to it. TIA
alex

**Comment by mairaw** [comment]
You shouldn’t create your project under the system32 folder. If command prompt opens that location by default, you can use the `cd` command (which means change directory) to go to another location. `cd ..` for example will go up one level.

Let us know if that helps!

**Comment by joemumu** [comment]
Yes thank you. That did help. You were right, that is the default location, (I’ve always wondered why that was)  I went to users folder, which as you know, gives permission to anyone to do just about anything. I have continued the lesson.
alex

**Comment by mairaw** [comment]
Awesome to hear. I’ll close the issue then.
