### ISSUE TITLE
when i try to access my programs get error om asp.net

### ISSUE THREAD

**Issue by classicaL814** [dotnet/core#6209]
Problem encountered on my com puter running win 10 64 bit pro i cannot change my user credentials asp.net machine wants a password which I have no idea. The error I get when i run different programs asp.net shows up and wants a password
this happens on a number of programs

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Which asp.net programs are you referring to? Can you perhaps share some screenshots?
