### ISSUE TITLE
I can't use C# in Visual Studio Code

### ISSUE THREAD

**Issue by Whitestarlines** [dotnet/core#6210]
I tried as many tutorials as I could, to use VSCode for c# programming, but none of them are working. If I type in 'dotnet' in CMD once I am done downloading the dotnet-sdk files, it says ''dotnet' is not recognized as an internal or external command,
operable program or batch file.' and if I type in, 'dotnet new console', in VSCodes terminal, it says, 'dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was   
included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet new console
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException'

**Comment by KleberTomazi** [comment]
Make sure that "C:\Program Files\dotnet" is part of the "path" system environment variable. If not, after adding, the problem should be resolved. :)

**Comment by joperezr** [comment]
Thanks for logging your issue @Whitestarlines. Here are some good instructions on how to get VSCode setup for c# development: https://code.visualstudio.com/docs/languages/csharp

Given this was a question and I believe that the link I sent and the the comment from @KleberTomazi should resolve this, I'll go ahead and close this issue for now for bookkeeping purposes but if you have any additional follow up questions or comments feel free to re-open it.
