### ISSUE TITLE
When I used the command "dotnet run" the code was not run.

### ISSUE THREAD

**Issue by GabrPXT** [dotnet/core#6211]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I speak Portuguese if I have an error or something meaningless in my speech was the Translator. When I used the command "dotnet run" the code was not set. The terminal just waited a while as if it were executing the code, but it didn't show me any output, and followed with a new line as if it had already ended (... home / myuser / myApp #). Can you help me? My SO Ubuntu 20.04 LTS

**Comment by mairaw** [comment]
Oi @GabrPXT!

Você pode anexar um printscreen da sua tela aqui? E o comando dotnet executou direitinho depois da instalação? E você tentou rodar o comando de novo para ver se acontecia a mesma coisa?
