### ISSUE TITLE
Extending Razor Views in ASP.NET Core 5.0

### ISSUE THREAD

**Issue by croban** [dotnet/core#6212]
I'm trying to make an base class derivated from RazorPage

`public abstract class BaseRazorPage<TModel> : RazorPage<TModel>`  

unfortunately I'm getting compilation error when I use it inside cshtml in combination with helpers 

**Error CS1963: An expression tree may not contain a dynamic operation (12, 30)**

```cshtml
@inherits BaseRazorPage<SomeResult>
... 
<form> 
... 
@Html.HiddenFor(o => o.Whatsoever)
```

Basically, Html.HiddenFor can not resolve the strong type from `RazorPage<TModel>` it sees it as `dynamic` type
Should that work?

**Comment by KevinCathcart** [comment]
The HTML helper is not part of the base class. Instead it is injected as if you had written
`@inject IHtmlHelper<TModel> Html` at the top of the page. Whenever `TModel` is used in the page, it will get substituted for whatever you specify with `@model`, but if you specify nothing, then `dynamic` is used.

So I'd suggest doing this instead:
```razor
@inherits BaseRazorPage<TModel>
@model SomeResult
... 
<form> 
... 
@Html.HiddenFor(o => o.Whatsoever)
```
By using TModel in the inherits line, it will automatically use whatever you specify in the @model directive, so you don't need to repeat yourself. Also, if you are planning to use the same generic base model for most of your views, you can put the `@inherits` line `_ViewImports.cshtml`. Then you just have the @model directive in each page as normal.  You can still override this inherits in specific views if needed. 

If you are curious, you can see the exact set of directives that get implicitly added:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Razor/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/MvcImportProjectFeature.cs#L61

After those lines comes the lines from _ViewImports, and finally comes the lines from your specific cshtml file.

Hope this helps.

**Comment by croban** [comment]
@KevinCathcart yes that solved my problems thanks! ;)

**Comment by mairaw** [comment]
Looks like issue has been resolved so closing it.
