### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by giubine** [dotnet/core#6214]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![porjuh](https://user-images.githubusercontent.com/80356797/116788977-ecc90700-aa82-11eb-9944-25662654ee32.png)
![porjuh](https://user-images.githubusercontent.com/80356797/116788983-f3577e80-aa82-11eb-8875-a080090a1686.png)

**Comment by mairaw** [comment]
Espero que o seu problema tenha sido resolvido. Se você ainda tiver dúvidas, é só nos falar.

**Comment by giubine** [comment]
Não foi

Em seg, 3 de mai de 2021 22:00, Maira Wenzel ***@***.***>
escreveu:

**Comment by mairaw** [comment]
Você ainda não conseguiu executar o comando dotnet? Você instalou o SDK?
