### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run

### ISSUE THREAD

**Issue by DuaneBrinson** [dotnet/core#6215]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Windows 10 Pro (version 10.0.19041.928) - no error message - ran tutorial unmodified

![IMAGE - MyWebApp - unmodified](https://user-images.githubusercontent.com/80736139/116831523-d1cec380-ab64-11eb-94cf-4f3e11fc5b59.PNG)

**Comment by mairaw** [comment]
Can you run the command `dotnet --info` on the myWebApp folder so we can see which SDK version are you using? This seems like an old template.

/cc @danroth27

**Comment by DuaneBrinson** [comment]
Maria,

When I ran the dotnet --info command, I got ...

.NET Core SDK (reflecting any global.json):
 Version:   2.1.523
 Commit:    c294f2cbe4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.523\

Host (useful for support):
  Version: 2.1.27
  Commit:  37d16c2b4d

.NET Core SDKs installed:
  2.1.523 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
[https://dotnet.microsoft.com/static/images/redesign/social/square.png]<https://aka.ms/dotnet-download>
.NET Downloads (Linux, macOS, and Windows)<https://aka.ms/dotnet-download>
Official .NET downloads for Linux, macOS, and Windows. .NET is a free, cross-platform, open-source developer platform for building many different types of applications.
aka.ms

Hope this helps.

Sincerely,
Duane Brinson
Cell: (949) 292-3032
Cell: (619) 648-7825

________________________________

**Comment by mairaw** [comment]
Yeah, that's definitely an old template then. There are a couple of things that might be going on. If you know you have installed .NET 5 SDK and you're running on an x64 machine, you might be running into the same problem I described here: https://github.com/dotnet/core/issues/5962#issuecomment-780079522

Give that a try and let me know. After fixing the environment variable, you should be able to start over and get the newer layout.
