### ISSUE TITLE
VS version supported is incorrect in current .NET 6.0 release notes

### ISSUE THREAD

**Issue by eriawan** [dotnet/core#6216]
Looking at these lines in the 6.0 release note:

https://github.com/dotnet/core/blob/2a095bfab19f2014e161ce3c770851069ff7e6ad/release-notes/6.0/releases.json#L135-L144

It says VS 2019 Latest preview. Currently (on March and on this April) latest VS 2019 preview version is 16.10. Is this preview version correct? To me it seems incorrect, because VS 2019 has no preview version of 16.9.

**Comment by mairaw** [comment]
@rbhanda @leecow please verify VS version for .NET 6 preview releases

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/6220

**Comment by eriawan** [comment]
@mairaw 

It's been fixed by #6220
Close this now, thanks @rbhanda 🙂
