### ISSUE TITLE
Ninguna plantilla coincidió con el nombre de la plantilla de entrada: MyMicroservice.

### ISSUE THREAD

**Issue by Margareth539** [dotnet/core#6242]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Al intentar navegar hasta el nuevo microservicio no se encuentra en la ni en línea o en el equipo estos son los pasos que copie y pegue en simbolos del sistemas : 
dotnet new MyMicroservice
Luego, navegue hasta el nuevo directorio creado por el comando anterior:
cd MyMicroservice
la respuesta fue:
Couldn't find an installed template that matches the input, searching online for one that does...

Por favor agradezco su amable colaboración para poder hacerlo con éxito, muchas gracias

**Comment by GrabYourPitchforks** [comment]
/cc @Pilchie

Auto-translation follows.

```txt
When you try to navigate to the new microservice you are not on the online or computer these are the steps you copy and paste into system symbols:
dotnet new MyMicroservice
Then navigate to the new directory created by the previous command:
cd MyMicroservice
the answer was:
Couldn't find an installed template that matches the input, searching online for one that does...

Please thank you for your kind cooperation in being able to do so successfully, thank you very much
```

**Comment by GrabYourPitchforks** [comment]
@Margareth539 Please let us know if Maira's comment at https://github.com/dotnet/core/issues/6242#issuecomment-837611141 resolved the issue for you. Thanks!
