### ISSUE TITLE
Build on VSTS hosted server

### ISSUE THREAD

**Issue by prrobinson** [dotnet/core#625]
I upgraded my VS2015 solution to use 1.1.1.  Now my build on VSTS hosted server fails to discover the xunit tests.  Any ideas on how to solve this?

**Comment by richlander** [comment]
Still occuring?

**Comment by Petermarcu** [comment]
VS 2015 isn't a supported environment for .NET Core. It was in the early beta's but not anymore. This has also had no response for 3 months so I'm going to close it.
