### ISSUE TITLE
watch : Exited with error code 139

### ISSUE THREAD

**Issue by ossie01-ui** [dotnet/core#6253]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Brun0-Z** [comment]
Hi, 1 year late. I was having the same problem. I resolved it with the next steps:
1- Uninstall dotnet-sdk and dotnet-runtimes. I was using the last version (6.0 at this moment) of these. 
2- Checked in Snap if i was another version of dotnet installed. I delete this version too.

I think i corrupted my dotnet installation. However, after uninstall dotnet, i reinstalled it following the tutorial in https://docs.microsoft.com/es-mx/dotnet/core/install/linux-ubuntu#2204
In my case, i use Linux Mint 20.1 so follow the 20.04 steps. 
I hope can help somebody.

**Comment by MarcosDVS** [comment]
what does the error mean **Exited with error code -532462766** in blazor with visual studio code

**Comment by imran6099** [comment]
I'm facing the same issue for 3 days.

We have a Blazor app developed using Visual Studio Windows, it works fine on windows machines, but when we try to run the same app on Linux it exits with code 139. 

What we've tried so far: 
1. Unistall dotnet and try reinstalling it, it works fine on other projects, but not the project we needed. 
2. Containerize using docker but the container is not responding to any request. 

Any ideas on what can be done to solve this issue?
