### ISSUE TITLE
DotNet problems with running console template

### ISSUE THREAD

**Issue by YakobuDoesCode** [dotnet/core#6254]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have tried using dot net to open a dotnet new console template script on visual studio and whenever I do it it says this error message.

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the     
path is correct and try again.
At line:1 char:1
+ dotnet new console
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
Are you trying to run from Visual Studio or Visual Studio Code?
And what if you type the command directly on a command prompt window?

Try restarting the app to see if the error goes away.
