### ISSUE TITLE
Error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. (MSB3971)

### ISSUE THREAD

**Issue by FRazban** [dotnet/core#6256]
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(3,3): Error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. (MSB3971)

I am using visual studio for mac and my version is up to date, if I create a new project with version dotnet 5 all is well but as soon as I try to build the project I have worked on windows I get this error. I have also installed the latest version of SDK

**Comment by mairaw** [comment]
What SDK version and VS for Mac version are you running?
Make sure you have the minimum version required for the SDK version:
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by rainersigwald** [comment]
In addition to Maira's questions, do you have a `global.json` file in your repo? If so can you share its contents?

**Comment by Richbward** [comment]
I'm getting the same problem using VS2019 Preview (I'm on Windows 10).  When I click on Help/Check for Updates it comes back with, “Visual Studio is up to date”.

Per your response above I then went to https://dotnet.microsoft.com/download/dotnet/5.0 and chose SDK 5.0.300 for Windows x64.  When finished it reported:
.NET SDK 5.0.203
.NET Runtime 5.0.6

I tried running the same command again that originally raised this error: docker build . -t <my container name>
Output: the same error:
ERROR [build 6/6] RUN dotnet build "SpecialOffers.csproj" -c Release -o /api/build                                                                                                                                   1.6s
------
 > [build 6/6] RUN dotnet build "SpecialOffers.csproj" -c Release -o /api/build:
#13 0.627 Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
#13 0.627 Copyright (C) Microsoft Corporation. All rights reserved.
#13 0.627
#13 1.163   Determining projects to restore...
#13 1.427   All projects are up-to-date for restore.
#13 1.550 /usr/share/dotnet/sdk/3.1.409/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/src/SpecialOffers.csproj]

This is my Dockerfile:
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["SpecialOffers/SpecialOffers.csproj", "SpecialOffers/"]
RUN dotnet restore "SpecialOffers/SpecialOffers.csproj"
COPY . .
WORKDIR "/src/SpecialOffers"
RUN dotnet build "SpecialOffers.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SpecialOffers.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SpecialOffers.dll"]

**Comment by rainersigwald** [comment]
@Richbward 

These parts of that output 

> Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
> ...
> /usr/share/dotnet/sdk/3.1.409/Microsoft.Common.CurrentVersion.targets

indicates that you're using .NET Core SDK 3.1.409, rather than .NET SDK 5.0.xxx, which is required to target .NET 5.0.

I tried using your Dockerfile and it seems to work fine to me--the `dotnet/sdk:5.0` container has `5.0.300` installed.

One difference I find interesting is that the step number is 7/7 instead of 6/6 as you posted:

```
 => [build 6/7] WORKDIR /src/SpecialOffers                                                                         0.1s
 => [build 7/7] RUN dotnet build "SpecialOffers.csproj" -c Release -o /app/build                                   2.1s
 => [publish 1/1] RUN dotnet publish "SpecialOffers.csproj" -c Release -o /app/publish                             1.5s
```

Is that your full, exact Dockerfile?

**Comment by nifesimii** [comment]
I have the same issue everytime i run dotnet build even though my sdk is set to the right location.
`Ademoyes-MacBook-Air:MvcMovie ademoyeoluwanifesimi$ dotnet build
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/ademoyeoluwanifesimi/Projects/MvcMovie/MvcMovie/MvcMovie.csproj (in 1.1 sec).
/usr/local/share/dotnet/x64/sdk/3.1.416/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/Users/ademoyeoluwanifesimi/Projects/MvcMovie/MvcMovie/MvcMovie.csproj]

Build FAILED.

/usr/local/share/dotnet/x64/sdk/3.1.416/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/Users/ademoyeoluwanifesimi/Projects/MvcMovie/MvcMovie/MvcMovie.csproj]
    0 Warning(s)
    1 Error(s)

`

**Comment by rainersigwald** [comment]
@nifesimii Looks like you are running .NET Core SDK `3.1.416`, which did not understand how to target .NET 5.0+, and the error message is accurate.

> even though my sdk is set to the right location

How are you setting this?

**Comment by IvanZiubin** [comment]
This problem creates after installing .net 6 for arm architecture and already installed .net 5 for x64. And PATH has only one path used for our SDK.

**Comment by akutishevsky** [comment]
In case someone has similar issue on the Visual Studio for Mac. After updating to MacOS Ventura all projects started throwing same errors. In my situation the next steps helped:
1. Open the Visual Studio
2. Go to Preferences > SDK Locations
3. For the Location field use `/usr/local/share/dotnet/x64/dotnet` instead of the `/usr/local/share/dotnet/dotnet` path.

This one applies for dotnet 6.0 and 7.0, not sure it will help with the 5.0 version.

**Comment by brennhill** [comment]
I've got this same problem - it cannot find reference assemblies for .NET 6, despite the SDKs being found in visual studio.  
I'm at a loss here.

**Comment by rainersigwald** [comment]
@brennhill Please open a new issue with more information, including logs that show the version number of the SDK as above.
