### ISSUE TITLE
How to set application icon on Windows?

### ISSUE THREAD

**Issue by vadi2** [dotnet/core#6260]
Using .NET 5 and `<OutputType>WinExe</OutputType>`, how can one set the application icon of the generated `.exe`?

**Comment by vitek-karas** [comment]
Add `<ApplicationIcon>App.ico</ApplicationIcon>` to your project file.

**Comment by mairaw** [comment]
I believe this has been answered, so closing.

**Comment by vadi2** [comment]
While this helped with the explorer view, the icon used by the window manager and the task bar is not correct -

![image](https://user-images.githubusercontent.com/110988/118348512-2271f380-b54b-11eb-84f3-6bc30f28213e.png)

Is there a trick to this?

**Comment by vitek-karas** [comment]
This icon comes from the window itself. It depends which UI stack you're using to create the window. For example for WinForms it can be done like this: https://stackoverflow.com/a/18736559/327203
