### ISSUE TITLE
Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50

### ISSUE THREAD

**Issue by prateekchawla** [dotnet/core#6262]
### Description

Building a .net project on a worker node.  with .net sdk 5 installed &  Azure Functions Core Tools installed 
### Configuration

**Error** 
`error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.Azure.Functions.Worker 1.2.0 supports: net5.0 (.NETCoreApp,Version=v5.0`

> E:\Jenkins\workspace\DotNet\Azure\Builds\azure-fx-shift-build\ShiftRiskRelayFx\ShiftRiskRelayFx.csproj : error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.Azure.Functions.Worker 1.2.0 supports: net5.0 (.NETCoreApp,Version=v5.0) [E:\Jenkins\workspace\DotNet\Azure\Builds\azure-fx-shift-build\Shift.sln]
 
 
 **Proj file looks like this**
 
```
 <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.8.3" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
```

**Comment by mairaw** [comment]
@rrelyea can you help with this issue? Should we move this to NuGet?

**Comment by nkolev92** [comment]
You can move this to NuGet. 

Based on the stack trace though, I'm fairly confident it's an old tooling version that's being used. 

.NET 5 is only supported with NuGet.exe 5.8, VS 16.8, .NET 5.0.100 SDK and later.

**Comment by mairaw** [comment]
This issue was moved to NuGet/Home#10875
