### ISSUE TITLE
The program does not open

### ISSUE THREAD

**Issue by ZeR9111** [dotnet/core#6270]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

My system is Windows 7 Ultimate 64 bit. I downloaded the program. When I click to open the application, the screen comes up but it disappears immediately. I have tried everything I can try but it hasn't improved. I would be glad if you could help. Thanks.

**Comment by simpleZed** [comment]
Is there any Console.ReadLine();

**Comment by mairaw** [comment]
For Windows 7, you need to install the SDK and some additional dependencies as well:
https://docs.microsoft.com/en-us/dotnet/core/install/windows?pivots=os-windows&tabs=net50#additional-deps

Have you done that? Which screen disappears? Maybe try sending a screenshot of the problem or where you're clicking that is not working.
