### ISSUE TITLE
i am trying to download . net framework 4.8 . but did not installed in my windows 10

### ISSUE THREAD

**Issue by guru012345** [dotnet/core#6275]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment]
Please provide details about what exact steps you're taking, any files you're downloading (along with URLs), and the exact error messages you're seeing. Also please provide the operating system version you're using: you can get this information by running the `winver` command.
