### ISSUE TITLE
dotnet netstandard2.1 ECDiffieHellman Error in linux

### ISSUE THREAD

**Issue by ByboyCn** [dotnet/core#6276]
os centos7 x64
sdk dotnet core3.1.409
error code:
```c#
var p224r1 = new Oid ("1.3.132.0.33");
var eccP224r1 = ECCurve.CreateFromOid(p224r1);
ECDiffieHellman.Create(eccP224r1);//this line err
```
error in:
The specified curve '1.3.132.0.33' or its parameters are not valid for this platform.
but I didn't ask him on win10 x64

**Comment by bartonjs** [comment]
Curve support is provided by the OS.  It appears that CentOS 7 doesn't support the curve you want, you'll have to use a different distro (or a different build of OpenSSL).

**Comment by ByboyCn** [comment]
3Q update openssl

**Comment by ByboyCn** [comment]
I have found a problem. When I need to share the public key of ecdh with others, I use the code ecdh. Publickey. Tobytearray (), and a annoying prompt appears: operation is not supported on this platform
The tag location is: 
System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanOpenSslPublicKey.ToByteArray()
@bartonjs

**Comment by bartonjs** [comment]
instead of `ecdh.PublicKey.ToByteArray()`, use `ecdh.ExportSubjectPublicKeyInfo()`
