### ISSUE TITLE
Ubuntu 20.04 Install Failure via apt-get: File has unexpected size

### ISSUE THREAD

**Issue by LennyBEL** [dotnet/core#6277]
I get the following error when trying to install .NET Runtime 5.0 on Ubuntu 20.04, error occurs on apt-get update

E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 40.114.136.21 443]
   Hashes of expected file:
    - Filesize:73160 [weak]
    - SHA512:782bf0315c8de4314049e599009430053b75a5015491b3d383b09239fcf31857d52bac3399cef8e813f7b2131dce09b03eaf89d79c5ebd2849402cee7aa9d228
    - SHA256:dbf4bf81b4a0a17dae53f2aff3edd4cf5bb1dcd5dcd216ce5c5c8ab7c507a26a
    - SHA1:0e1b47276cae4168a08d8fd981891d4773f053b9 [weak]
    - MD5Sum:0fcf3ed335cd4efde65300bb48c05afe [weak]
   Release file created at: Sat, 15 May 2021 00:38:08 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by savarex** [comment]
Same here, both Debian 10 and Ubuntu 20.04

**Comment by MulticolorWorld** [comment]
Same. My env is Ubuntu 20.04 (Github Actions runs-on)

Err:20 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages
  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 13.90.21.104 443]
  Hashes of expected file:
   - Filesize:73160 [weak]
   - SHA512:782bf0315c8de4314049e599009430053b75a5015491b3d383b09239fcf31857d52bac3399cef8e813f7b2131dce09b03eaf89d79c5ebd2849402cee7aa9d228
   - SHA256:dbf4bf81b4a0a17dae53f2aff3edd4cf5bb1dcd5dcd216ce5c5c8ab7c507a26a
   - SHA1:0e1b47276cae4168a08d8fd981891d4773f053b9 [weak]
   - MD5Sum:0fcf3ed335cd4efde65300bb48c05afe [weak]
  Release file created at: Sat, 15 May 2021 00:38:08 +0000

**Comment by machaven** [comment]
> Same here, both Debian 10 and Ubuntu 20.04
> 
> Below Debian 10 log
> Err:5 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages
> File has unexpected size (98942 != 98600). Mirror sync in progress? [IP: 13.93.152.112 443]
> Hashes of expected file:
> 
> * Filesize:98600 [weak]
> * SHA512:6e5ddf767d63a5da6ad918ae0caf444393a431e1d1a715693b0889f925cf66eff24e963847d8e068b452f1289e9563b8925c8b945b683f10b47fa254e5d78f10
> * SHA256:d33418be63430f6fa2940ffe67a7b2ca07156537eb71a978f537efa9b7d1d54f
> * SHA1:621399e094255535eed7c78e4f6ee0375af5ea47 [weak]
> * MD5Sum:7c00873e30764169f9057b174ca714e8 [weak]
>   Release file created at: Sat, 15 May 2021 00:39:28 +0000

Same issue building our docker images

**Comment by vavuthu** [comment]
we have been hit with same issue. looks like packages are updated on 17-May-2021 17:59 

```
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 13.66.21.183 443]
   Hashes of expected file:
    - Filesize:73160 [weak]
    - SHA512:782bf0315c8de4314049e599009430053b75a5015491b3d383b09239fcf31857d52bac3399cef8e813f7b2131dce09b03eaf89d79c5ebd2849402cee7aa9d228
    - SHA256:dbf4bf81b4a0a17dae53f2aff3edd4cf5bb1dcd5dcd216ce5c5c8ab7c507a26a
    - SHA1:0e1b47276cae4168a08d8fd981891d4773f053b9 [weak]
    - MD5Sum:0fcf3ed335cd4efde65300bb48c05afe [weak]
   Release file created at: Sat, 15 May 2021 00:38:08 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: Process completed with exit code 100.
```

**Comment by drewmoore** [comment]
It looks like this has been fixed at this time.

**Comment by LennyBEL** [comment]
Looks like the issue has been fixed. It works for again for me.
