### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by rodia** [dotnet/core#6279]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @rodia! Can you please provide a screenshot or the exact error message you're getting and when?

**Comment by rodia** [comment]
![Screenshot-segmentation-fault-error](https://user-images.githubusercontent.com/1838648/118880489-eaa6db00-b8bf-11eb-81a3-12f7396c5335.png)

here is it, my current ubuntu version is 21.04

**Comment by rodia** [comment]
Thanks you for your time but I already have solved my issue. I used this instructions https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#apt-troubleshooting instead snap manager

**Comment by mairaw** [comment]
Thanks for letting us know!
