### ISSUE TITLE
DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe file missing

### ISSUE THREAD

**Issue by nash2k** [dotnet/core#6281]
Hi,

I'm trying to download this file (DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe) listed in _.NET Core Runtime and SDK download archive_ as it is required for uninstalling this version. It's going 404 on me, is there any way to get this file? 
Also, would be nice to update the URL in the mentioned doc.

Best,
Nenad

**Comment by GrabYourPitchforks** [comment]
@leecow The page in question is https://github.com/dotnet/core/blob/main/release-notes/download-archive.md, where the download links at the bottom of the page are 404ing. Can you restore these files or update these links?

**Comment by leecow** [comment]
That was a bit of an archeology project ;-) @nash2k - should be good to go now.

**Comment by nash2k** [comment]
Thanks for digging! You're the best!
