### ISSUE TITLE
Bug in dot.net website on support policy page

### ISSUE THREAD

**Issue by martincostello** [dotnet/core#6284]
I was looking at the [.NET Core and .NET 5 Support Policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) page and noticed it had a strange title:

![image](https://user-images.githubusercontent.com/1439341/118955816-f5f91580-b956-11eb-92d0-1ebe9eae8645.png)

Looking at the page source, seems there's a bug in the page rendering:

![image](https://user-images.githubusercontent.com/1439341/118955892-06a98b80-b957-11eb-89f1-0b73f7ed4c43.png)

```html
<title>Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString</title>
<meta name="description" content="Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString" />
```

**Comment by GrabYourPitchforks** [comment]
@terrajobst @richlander I'm not quite sure how to route this - can you assist? Per the issue description, there's some stray text in the file backing https://dotnet.microsoft.com/platform/support/policy/dotnet-core, and this stray text should be removed.

**Comment by rbhanda** [comment]
@mairaw Can you help us here?

**Comment by mairaw** [comment]
Thanks for reporting this and apologies for the delay. I was out for the last couple of days. I'll get that fixed.

We enabled globalization in our site and apparently introduced some bugs with it.
