### ISSUE TITLE
az aks create ---.. .

### ISSUE THREAD

**Issue by ddoffy** [dotnet/core#6288]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The operation is not permitted for namespace 'Microsoft.ContainerService'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Billing,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,Microsoft.Subscription,microsoft.support,microsoft.visualstudio,Microsoft.Web'.

**Comment by GrabYourPitchforks** [comment]
Please provide more information about the problem you're experiencing, including the exact commands entered at the terminal window. Thanks!
