### ISSUE TITLE
Ubuntu 15.10 Errors during 'dotnet restore'

### ISSUE THREAD

**Issue by AndrewBarfield** [dotnet/core#63]
Am I actually asking M$ for Linux help? Dear God help me...

I get a series of "features" when issuing a 'dotnet restore' command on version 15.10:

`drew@drew-ubuntu:~/hwapp$ dotnet restore
log  : Restoring packages for /home/drew/hwapp/project.json...
error: Microsoft.Win32.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.AppContext 4.1.0-rc2-23811 provides a compile-time reference assembly for System.AppContext on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Collections 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Collections on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Console 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Debug 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Tools 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tools on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Tracing 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tracing on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Globalization 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Globalization on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Globalization.Calendars 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Globalization.Calendars on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.IO 4.1.0-rc2-23811 provides a compile-time reference assembly for System.IO on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.IO.FileSystem 4.0.1-rc2-23811 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Net.Primitives 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Net.Sockets 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Net.Sockets on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection.Extensions 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection.TypeExtensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection.TypeExtensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.Extensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.Handles 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Runtime.Handles on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.InteropServices 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Text.Encoding 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Text.Encoding.Extensions 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading.Tasks 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading.Timer 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Threading.Timer on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.15.10-x64).
info : Committing restore...
log  : /home/drew/hwapp/project.json
log  : Restore failed in 582ms.

Errors in /home/drew/hwapp/project.json
    Microsoft.Win32.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.AppContext 4.1.0-rc2-23811 provides a compile-time reference assembly for System.AppContext on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Collections 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Collections on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Console 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Diagnostics.Debug 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Diagnostics.Tools 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tools on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Diagnostics.Tracing 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tracing on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Globalization 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Globalization on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Globalization.Calendars 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Globalization.Calendars on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.IO 4.1.0-rc2-23811 provides a compile-time reference assembly for System.IO on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.IO.FileSystem 4.0.1-rc2-23811 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Net.Primitives 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Net.Sockets 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Net.Sockets on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection.Extensions 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection.TypeExtensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection.TypeExtensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.Extensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.Handles 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Runtime.Handles on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.InteropServices 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Text.Encoding 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Text.Encoding.Extensions 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Threading 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Threading.Tasks 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Threading.Timer 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Threading.Timer on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.15.10-x64).

NuGet Config files used:
    /home/drew/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
drew@drew-ubuntu:~/hwapp$`

**Comment by seanshpark** [comment]
Could https://github.com/dotnet/cli/issues/1179 do some help?

**Comment by AndrewBarfield** [comment]
Thank you! I'll look into it.

**Comment by jchannon** [comment]
I also see this behaviour

**Comment by joshfree** [comment]
Hi @AndrewBarfield, Ubuntu 15.10 isn't one of the .NET Core 1.0 supported platforms (Ubuntu 14.04 LTS and 16.04 LTS are supported) https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0.md#rtm-platform-support.

More information is available at http://dot.net/core.

If you are running into issues feel free to reactivate this or create a new issue in https://github.com/dotnet/corefx.  Thanks
