### ISSUE TITLE
Solution item not included with CopyToPublishDirectory

### ISSUE THREAD

**Issue by julesrx** [dotnet/core#6307]
### Description
I'm having a difference in behavior when using CopyToPublishDirectory with a Solution item.

I want to copy my `cnxstrings.json` file in the publish output.
Here is my solution structure :
```
├── src
│   ├── Web
│   │   ├── ...
│   │   ├── Web.csproj
├── cnxstrings.json
└── Solution.sln
```

My csproj item :
```xml
<ItemGroup>
    <None Include="$(SolutionDir)\cnxstrings.json" CopyToPublishDirectory="Always" />
</ItemGroup>
```

When running `dotnet publish` (the folder defaults to `src/Web/bin/Debug/net5.0/publish`):
- from the solution root : the `cnxstrings.json` is present in the publish output
- from the project root (`src/Web`) or targeting the csproj file (`src/Web/Web.csproj`): the `cnxstrings.json` is not present

This can pose a problem if I want to publish only a selected project for example.

### Configuration
```
dotnet --version: 5.0.203
OS: Windows 10 x64
```

**Comment by ManickaP** [comment]
I'd suspect that `$(SolutionDir)` will be null/empty/undefined when you run the command from the project dir. Relative path to the project file (`$(ProjectDir)..\cnxstrings.json`) might work better in this case.

**Comment by julesrx** [comment]
> 
> 
> I'd suspect that `$(SolutionDir)` will be null/empty/undefined when you run the command from the project dir. Relative path to the project file (`$(ProjectDir)..\cnxstrings.json`) might work better in this case.

This works in both cases. Thank you 👍

**Comment by ManickaP** [comment]
Great to hear it helped. Closing the issue as it's resolved.
