### ISSUE TITLE
pjgpetecodes:add-pete-codes-remote-debug

### ISSUE THREAD

**Issue by Ao-2** [dotnet/core#6309]
pjgpetecodes:add-pete-codes-remote-debug

_Originally posted by @Ao-2 in https://github.com/dotnet/core/issues/6308#issuecomment-849014350_

**Comment by ManickaP** [comment]
It looks like automation generated content, perhaps your account has been hacked? ... Please try to address that and don't post issues without content, otherwise we might have to block your account / report it to GitHub. Thank you!
