### ISSUE TITLE
Uing Ctrl+R while running dotnet watch run command no longer works.

### ISSUE THREAD

**Issue by tjscience** [dotnet/core#6311]
When running "dotnet watch run" command for a project, if the code is not a supported edit, we must press Ctrl+R to reload the running app manually. This is no longer working in .net6 preview 4. Nothing happens.

**Comment by ManickaP** [comment]
Hi @tjscience,
I just quickly tried a simple MVC app in .NET 6.0 preview 4 (specifically Microsoft.AspNetCore.App 6.0.0-preview.4.21207.16 runtime), run it with `dotnet watch` and made a simple change in code. The app reloaded the change on it's own and it worked like charm.

Could you please specify in more detail under what conditions it doesn't work for you?
- operating system
- exact version of .NET (`dotnet --info`)
- source code of your app (preferably minimal code necessary to reproduce the problem)
- the change that doesn't work with the hot-reload

**Comment by tjscience** [comment]
Hi, can you please try with a blazor webassembly app? I just created a new project from the template in visual studio and it does not work.

- operating system => Windows 10
- .NET version => 6.0.100-preview.4.21255.9
- source code => the source code generated from creating a new blazor webassembly app in visual studio
- not working => I have not gotten any change to work that is a supported edit for hot-reload

**Comment by tjscience** [comment]
I change the browser from Brave to Chrome and it started to work.
