### ISSUE TITLE
Thought process behind why a lambda function value cannot be assigned to const variable?

### ISSUE THREAD

**Issue by shrinidhi111** [dotnet/core#6313]
I wrote a lambda function to generate repeated dashes and assign to a variable (I later understood this could be achieved with `new String('=', 20)` but thats another story). 

Code looks like this.

```csharp
public static string Dashes = ((Func<string>) (() =>{
            var dashes="";
            for (var i = 0; i < 20; i++)
            {
                dashes+="=";
            }
            return dashes;
        }))();
```

This works as expected but if I change `public static string Dashes` to `public const string Dashes` it will throw the error `The expression being assigned must be constant`

I understand if this error is thrown when the compiler thinks our value might vary (hence cannot be constant) but the lambda function here executes exactly once in program's lifetime... What is the thought process here for the error?

Just as a reference, the following code works perfectly fine in JS

```javascript
const Dashes = () =>{
            var dashes="";
            for (var i = 0; i < 20; i++)
            {
                dashes+="=";
            }
            return dashes;
    };
```

Will C# also have this feature in the future? Or is there a deeper reason why it might be impossible?

**Comment by svick** [comment]
The keyword `const` is a bit different in C# than in other languages. In C#, `const` requires the *the compiler* understands what the value is and that it never changes. And since the compiler is very limited in this regard, `const` fields are very limited in what you can assign to them. Instead, you should mark the field as `readonly`.

**Comment by ManickaP** [comment]
I hope the question is answered here, closing the issue.
