### ISSUE TITLE
The counter on index page continue to increment by 1

### ISSUE THREAD

**Issue by oddonet** [dotnet/core#6315]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/modify
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The parameter for incrementAmount did not work. The counter on index page is still incrementing by 1 after the change

**Comment by ManickaP** [comment]
Hi @oddonet,
can you confirm that the change doesn't propagate even after:
- reloading the page
- restarting the process

This might be an issue with hot-reload and blazor, but let's confirm that first.
