### ISSUE TITLE
我可以直接升级webform到.NET6吗

### ISSUE THREAD

**Issue by manpaiboy** [dotnet/core#6317]
我在2013年创办了 asp.net源码 网站 使用的是webform
现在想升级到.NET6 ，可行吗？

**Comment by manpaiboy** [comment]
网站的地址是 [www.myaspx.com](url)

**Comment by manpaiboy** [comment]
www.myaspx.com

**Comment by manpaiboy** [comment]
网站的地址是 www.myaspx.com

**Comment by expcat** [comment]
Cannot, .Net 6 doesn't support webform.

You can try [blazor](https://docs.microsoft.com/zh-cn/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio) or razor [pages](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/?view=aspnetcore-6.0).

**Comment by ManickaP** [comment]
Hi @manpaiboy,
I see that @expcat tried to answer your question and I hope it helped. Unfortunately, we cannot help unless you ask your question in English. I'll close this for now, since there's nothing we can do for you at the moment. If you have further questions, please feel free to reopen.
