### ISSUE TITLE
Problem running Blazor Tutorial on Windows 10 (x64)

### ISSUE THREAD

**Issue by BillEisenman** [dotnet/core#6318]
A problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: Windows 10 - 64-bit Pro

Unable to load - The connection for this site is not securelocalhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

on running BlazorApp using dotnet watch run

**Comment by ManickaP** [comment]
Hi @BillEisenman,

have you used `--no-https` when you created the project? https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create There shouldn't be any SSL involved.

**Comment by danroth27** [comment]
Please try either creating the site without HTTPS enabled using the `--no-https` switch, or run `dotnet dev-certs https --trust` to trust the ASP.NET Core development certificate.
