### ISSUE TITLE
I installed dotent, opened a new command prompt, and prompt is still not recognizing dotent

### ISSUE THREAD

**Issue by CypherCrow** [dotnet/core#6319]
As it says on the issue title, I tried to open a new command prompt after it did not recognize dotent. After doing so, I typed `dotent` again, and the command prompt is not recognizing it still.

**Comment by mairaw** [comment]
The name of the command is dotnet. Are you sure you're typing the command name correctly?

**Comment by CypherCrow** [comment]
Yes. I typed the command as it is. No misspellings.

**Comment by mairaw** [comment]
Can you paste a screenshot for us?

**Comment by CypherCrow** [comment]
![dotent-screenshot](https://user-images.githubusercontent.com/57231486/120567883-93c4f980-c3c7-11eb-9c41-f7d7b2dc0bc2.PNG)

**Comment by mairaw** [comment]
The name of the command is `dotnet` not `dotent`. See if typing `dotnet` will work for you.

**Comment by CypherCrow** [comment]
Oh, silly me. Thanks!
