### ISSUE TITLE
unable to install.NET

### ISSUE THREAD

**Issue by pinnaclepools** [dotnet/core#6324]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\pinna>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ManickaP** [comment]
Hi @pinnaclepools,

have you restarted the command line after installing the dotnet?
