### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by Pochpro** [dotnet/core#6326]
![cmd_MGloUJe9ob](https://user-images.githubusercontent.com/53707272/120701116-abda6d00-c4dc-11eb-9b24-cc6f74b2a433.png)
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
In that page, you can see some guidance around this specific error:
![image](https://user-images.githubusercontent.com/12971179/120701393-a0009380-c467-11eb-822b-66c523eee08c.png)

Change your directory to one that you have permissions to create a folder, such as `c:\users\<username>`, where `<username>` is your user name on Windows.
