### ISSUE TITLE
error in printing date and time

### ISSUE THREAD

**Issue by palashshrote** [dotnet/core#6329]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

//
Can't able to figure out the date and time
![Screenshot (2742)](https://user-images.githubusercontent.com/62279315/120796492-80956380-c558-11eb-9318-c9570532db2e.png)

**Comment by omajid** [comment]
It's `DateTime.Now`. Note the capital `N` in `Now`.

**Comment by ManickaP** [comment]
@palashshrote was your question answered? Can we close this now.
