### ISSUE TITLE
Type.GetMethod different behaviour then dotnet core 2.2

### ISSUE THREAD

**Issue by peirens-bart** [dotnet/core#6332]
I'm migrating code from dotnet core 2.2 to .Net 5.0, Here i have code that doesn't work anymore with breaks a core feauture off our app.

The code is getting the count off items per team where the user has reading wrights. for doing this I create a list of types off aggregates types and then gets the met Set<T> on the Entity framework DbContext so I can invoke a query on that set.
This code is working in dotnet core 2.2, but it throws an anbigious method exception in .Net 5.0

Type contectType = _context .GetType();
MethodInfo methodInfo = contectType.GetMethod(nameof(_context.Set)); <-- throws exception
MethodInfo methodInfoCreated = methodInfo.MakeGenericMethod(type);
var count = await ((IQueryable<Aggregate>)methodInfoCreated.Invoke(_context, null))
    .Where(x => x.Deleted == false && x.CreatedForTeam == _accountInfo.TeamId)
    .CountAsync();

the thing is that EF has an extra implementation Set<T>(string)
if I change the code to
MethodInfo methodInfo = contectType.GetMethod(nameof(_context.Set),new[] { typeof(string) });
the code is working I and I got the corret methodInfo, 
How can I get the methodInfo of Set<T>, or how can I say take the one without arguments.

### Regression?

works in dotnet core 2.2

### Other information

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Reflection.AmbiguousMatchException: Ambiguous match found.
         at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
         at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
         at System.Type.GetMethod(String name, BindingFlags bindingAttr)
         at System.Type.GetMethod(String name)
         at BookerTools.Business.Managers.TeamManager`1.CountAggregate(List`1 types) in C:\Code\BookerTools\dotnet\backend\BookerTools.Business\Managers\Account\TeamManager.cs:line 306

**Comment by ManickaP** [comment]
`contectType.GetMethod(nameof(_context.Set), Type.EmptyTypes);` should work for you.
See: https://docs.microsoft.com/en-us/dotnet/api/system.type.getmethod?view=net-5.0#System_Type_GetMethod_System_String_System_Type___
> An empty array of Type objects (as provided by the EmptyTypes field) to get a method that takes no parameters.

I hope the question is answered here, I'll close this. If you have more questions, please feel free to reopen.
