### ISSUE TITLE
Hello World in .net

### ISSUE THREAD

**Issue by cpmeena14** [dotnet/core#6333]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. It is not working
![image](https://user-images.githubusercontent.com/85111938/120919964-26d48c80-c671-11eb-8468-1dca84ea4f82.png)

**Comment by ManickaP** [comment]
Hi @cpmeena14,

The edits from the tutorial should go in `Index.cshtml` file not `Index.cshtml.cs` as your compilation errors show.

I'll close this as the question should be answered. Feel free to reopen if not.
