### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by bishal93-stack-ux** [dotnet/core#6335]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
Hi @bishal93-stack-ux could you please share more about your problem? Did you made any changes to the source code from the tutorial? Could you share them if so? Could you also share the version on .NET you're using? Also print screen of the error could help as well.

**Comment by bishal93-stack-ux** [comment]
I run hello world app of asp.net through windows terminal but there are
many error ,why is that?

**Comment by mairaw** [comment]
A screenshot of the errors would help us to provide any guidance on why this is happening.

For the ASP.NET tutorial, it's common for folks to edit the .cs file, instead of the .cshtml file because Windows by default hides the file extension and that would generate a lot of errors.

**Comment by bishal93-stack-ux** [comment]
Ok, I will do that.

**Comment by bishal93-stack-ux** [comment]
[image: Screenshot (50).png]

**Comment by mairaw** [comment]
@bishal93-stack-ux GitHub unfortunately doesn't let you add screenshots when you're replying via email. Can you come to the site to attach the screenshot? Or maybe copy and paste the text of the command window here. That would work too.
