### ISSUE TITLE
.NET June 2021 Update - .NET 5.0.7 and .NET Core 3.1.16

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6337]
Release Notes 
[5.0.7](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.7/5.0.7.md)
[3.1.16](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.16/3.1.16.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.7 | 3.1.16
|--|--|--
| Ubuntu 16.04   |  ✅  |  ✅  |
| Ubuntu 18.04    |  ✅  |  ✅  |
| Ubuntu 20.04    |  ✅  |  ✅  |
| Ubuntu 20.10    |  ✅  |  ✅  |
| Ubuntu 21.04     |  ✅  |  ✅  |
| Centos 7      |  ✅  |  ✅  |
| Centos 8     |  ✅  |  ✅  |
| Debian 9   |  ✅  |  ✅ |
| Debian 10   |  ✅  |  ✅  |
| Fedora 32    |  ✅  |  ✅ |
| Fedora 33    |  ✅  |  ✅ |
| Fedora 34  |  ✅  |  ✅|
| OpenSUSE 15   |  ✅  |  ✅  |
| SLES 12   |  ✅  |  ✅  |
| SLES15  |  ✅  |  ✅  |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [x] [ Centos 7 ](https://packages.microsoft.com/centos/7/prod/)on packages.microsoft.com is not updated with .NET 5.0.7 update
- [x] [Centos 8 ](https://packages.microsoft.com/centos/8/prod/)on packages.microsoft.com is not updated with .NET Core 3.1.16 and .NET 5.0.7 updates

**Comment by arocholl** [comment]
Hi, I get this error while trying to install dotnet-sdk-5.0 in Centos 7

https://packages.microsoft.com/rhel/7/prod/dotnet-runtime-deps-5.0.7-centos.7-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found

Is that the [Centos 7] knwon issue?

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/6459
