### ISSUE TITLE
Dotnet is not recognized

### ISSUE THREAD

**Issue by Warmzzz** [dotnet/core#6339]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![Capture d’écran 2021-06-08 205058](https://user-images.githubusercontent.com/84672573/121240990-333c2d80-c89b-11eb-958d-7dee51b49efe.png)

**Comment by mairaw** [comment]
Can you confirm whether you're system is x86 or x64?

**Comment by mairaw** [comment]
I have some suspicions that you're running into this problem with the PATH:
https://github.com/dotnet/core/issues/5962
