### ISSUE TITLE
Broken link for 2.0.0-preview1-download

### ISSUE THREAD

**Issue by colbylwilliams** [dotnet/core#634]
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md

Corrected link: https://download.microsoft.com/download/0/4/8/048C286D-59CB-4B7C-95A1-D0F7FD4D37D2/dotnet-win-x64.2.0.0-preview1-002111-00.exe

**Comment by leecow** [comment]
Thanks @colbylwilliams, fixed.
