### ISSUE TITLE
Unable to install .NET Framework 3.5 ( Windows 10)

### ISSUE THREAD

**Issue by Naveenhillard** [dotnet/core#6349]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

while installing the .Net 3.5, getting the below error message, kindly help.

Error Code 0x80080005 installation failure

**Comment by mairaw** [comment]
I'm also curious on how you landed on that tutorial when you're trying to install .NET Framework 3.5.

The installation guide for 3.5 is found at https://docs.microsoft.com/dotnet/framework/install/dotnet-35-windows-10
