### ISSUE TITLE
Buid Failed

### ISSUE THREAD

**Issue by mathabane** [dotnet/core#6351]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

A beginner:
Code sample

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>

Error sample

watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...
watch : Started
Building...
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(4,13): error CS1002: ; expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(4,14): error CS1001: Identifier expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,6): error CS1002: ; expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1001: Identifier expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1514: { expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1513: } expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(8,14): error CS1002: ; expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(9,12): error CS1002: ; expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]
C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\Pages\Index.cshtml.cs(10,7): error CS1002: ; expected [C:\Users\Eva.DESKTOP-JB5VL29\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by michaelgsharp** [comment]
What version of dotnet are you using? x86 or x64?

Can you share the whole Index.cshtml and Index.cshtml.cs files?

**Comment by michaelgsharp** [comment]
Yeah, looking at the stack trace you provided it looks likes the Index.cshtml.cs file was edited and not the Index.cshtml.

**Comment by mathabane** [comment]
I sorted it out, thank you. I was using the Index.cshtml.cs instead of the
Index.cshtml.

I even had to re create a new project as the Index.cshtml.cs was cleared.
