### ISSUE TITLE
Problems with packages on https://packages.microsoft.com/debian/10/prod/dists/buster/

### ISSUE THREAD

**Issue by dave-comfort** [dotnet/core#6356]
**Our builds just started failing today (2021-06-10) because of the following problem**

Errors encountered while downloading packages:

Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 12610 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-debian10.1) ...
Setting up packages-microsoft-prod (1.0-debian10.1) ...
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]

Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [292 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 https://packages.microsoft.com/debian/10/prod buster InRelease [29.8 kB]
Get:7 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
Get:8 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages [103 kB]

Err:8 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages
  File has unexpected size (102910 != 102798). Mirror sync in progress? [IP: 13.66.21.183 443]
  Hashes of expected file:
   - Filesize:102798 [weak]
   - SHA512:99f7473f7ad2aab2225d9300abdf7f4ab9f4227c3e7e7d360adb59972e59f2e3b733c8c966020c8dcb512c44dc265b3807f6fa288660369f0bd6915840306eb7
   - SHA256:5170712246fe4fe867b0249d897c9543cb83a6a489c308dc717def63b1f42ff7
   - SHA1:747baa8266e4c8b781a750bb3d9b88372b4f4268 [weak]
   - MD5Sum:3380e25ea2373130b96987027f7eaebf [weak]
  Release file created at: Tue, 08 Jun 2021 16:38:17 +0000
Get:9 https://packages.microsoft.com/debian/10/prod buster/main armhf Packages [13.0 kB]
Err:9 https://packages.microsoft.com/debian/10/prod buster/main armhf Packages
  
Get:10 https://packages.microsoft.com/debian/10/prod buster/main arm64 Packages [13.2 kB]
Err:10 https://packages.microsoft.com/debian/10/prod buster/main arm64 Packages
  
Get:11 https://packages.microsoft.com/debian/10/prod buster/main all Packages [3037 B]
Err:11 https://packages.microsoft.com/debian/10/prod buster/main all Packages

**Comment by michaelgsharp** [comment]
Do you have a rough time for when they started today?

Can you run another build and see if it keeps occuring?

**Comment by dave-comfort** [comment]
MS just pushed out new packages this afternoon (2021-6-10).  Our builds have been failing since.  We just tried again (4:00pm CT).

**Comment by aressler38** [comment]
I am having the same problem, and it has been ongoing for about 3 hours.

**Comment by Immich** [comment]
I am also having the same problem 👀

**Comment by dave-comfort** [comment]
They just pushed out a new release (10-Jun-2021 21:28) and no our builds are working again.

**Comment by aressler38** [comment]
Yep. It's working for me too.

**Comment by michaelgsharp** [comment]
Perfect. I'll go ahead and close this issue then.

**Comment by m00lecule** [comment]
Hello, this issue appears again - to reproduce


`docker run mcr.microsoft.com/dotnet/sdk:5.0 sh -c " wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb && apt-get install -y ./packages-microsoft-prod.deb && apt-get update -y"`

![image](https://user-images.githubusercontent.com/33501567/126477208-9db7f325-e0f4-464b-8922-3de665475ae7.png)
