### ISSUE TITLE
Could not execute because the specified command or file was not found.         Possible reasons for this include:   * You misspelled a built-in dotnet command.   * You intended to execute a .NET program, but dotnet-program does not exist.   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

### ISSUE THREAD

**Issue by MeghanaAnkam** [dotnet/core#6360]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you paste a screenshot of the error? Did just `dotnet` run fine?
