### ISSUE TITLE
SyncToy installation error.

### ISSUE THREAD

**Issue by fdariano** [dotnet/core#6361]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

OS: Windows 10 Pro
Version: 20H2

In trying to install Microsoft SyncToy in Windows 10, I got a popup to install .NET Framework first. I downloaded & installed it and tried to install SyncToy again but got the same error. I downloaded and installed .NET Framework again and tried to install SyncToy again but got the same error. I tried this several times and always get the same error. I checked to see if .NET Framework installed and saw that it did. I've attached an image of the error with the CMD in the background showing .NET Framework is working.
![image](https://user-images.githubusercontent.com/23079146/121809160-b3f78280-cc29-11eb-95a9-89580ca49d01.png)

**Comment by mairaw** [comment]
Hi @fdariano!

Can you paste where the yes button takes you? You shouldn't need to do the coding tutorial to be able to install .NET Framework. So, I'm trying to understand how you landed on the tutorial.

But to install .NET Framework 2.0 on Windows 10, you have to enable .NET Framework 3.5 (which also includes 2.0):
https://docs.microsoft.com/dotnet/framework/install/dotnet-35-windows-10
