### ISSUE TITLE
.NET Tutorial

### ISSUE THREAD

**Issue by browneye43** [dotnet/core#6370]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
is what i put in the command prompt
  {
'{' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>        static void Main(string[] args)
'static' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>        {
'{' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>            Console.WriteLine("Hello World!");
'Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>        }
'}' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>    }
'}' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>}{
'}{' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>    class Program
'class' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>    {
'{' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>        static void Main(string[] args)
'static' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>        {
'{' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>            Console.WriteLine("Hello World!");
'Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>        }
'}' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\myApp>    }
'}' is not recognized as an internal or external command,
operable program or batch file.
This is my return error report. I am not sure if I put it in right , Please help

**Comment by browneye43** [comment]
I'm not sure if I did it right

**Comment by mairaw** [comment]
Hi @browneye43! That page is just showing the code of the Program.cs file. I'm adding some improvements to that page to make that more clear.

Try to go to the next step to see if you can continue the tutorial.

**Comment by browneye43** [comment]
>donet run
came back return error
'}dotnet' is not recognized as an internal or external command,
operable program or batch file

**Comment by mairaw** [comment]
Make sure you typed dotnet run, not donet

Since it seems you were able to create the myApp folder
