### ISSUE TITLE
Unable to run your project. Ensure you have a runnable project type and ensure 'dotnet run' supports this project. A runnable project should target a runnable TFM (for instance, netcoreapp2.0) and have OutputType 'Exe'. The current OutputType is 'Library'.

### ISSUE THREAD

**Issue by qadir1020** [dotnet/core#6373]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
This error is because of a console app, a library app was created instead. 

Can you try again and make sure in the `Create your app` section you use `console` as the type for `dotnet new`
