### ISSUE TITLE
is there a way to download .net on school laptop without admin?

### ISSUE THREAD

**Issue by brickyosu** [dotnet/core#6376]
i know how to run scripts in powershell but they disabled scripts, so im here to say that is there even a way to get .net sdk portable?

**Comment by richlander** [comment]
There are a variety of instructions at https://github.com/dotnet/core/blob/main/release-notes/6.0/install.md. Can you tell me if that helps.

**Comment by arakieu** [comment]
> There are a variety of instructions at https://github.com/dotnet/core/blob/main/release-notes/6.0/install.md. Can you tell me if that helps?

so uhh i did `curl -o dotnet.zip https://download.visualstudio.microsoft.com/download/pr/74448616-c6d2-40bf-b6da-aa3a6c1009ab/62702150054089e2961aaf32e8ab3ffc/dotnet-sdk-6.0.100-preview.5.21302.13-win-x64.zip`

and it worked


but when i did `tar -C dotnet -xf dotnet.zip` then it said: `tar: could not chdir to 'dotnet'`

**Comment by mairaw** [comment]
We also have this option for you to use a coding pack with VS Code:
https://dotnet.microsoft.com/learntocode

It shouldn't require admin rights.

**Comment by catte-cloud** [comment]
this is probably by far the funniest bypass i've seen in decades

**Comment by armour-sheila** [comment]
I am the Owner, it would have been nice!

**Comment by brickyosu** [comment]
wait what i have a pc now lol

**Comment by brickyosu** [comment]
i have .net now
