### ISSUE TITLE
C:\Windows\System32\myApp>dotnet run Hello World!  C:\Windows\System32\myApp> C:\Windows\System32\myApp>dotnet run Hello World!  C:\Windows\System32\myApp> C:\Windows\System32\myApp>Hello World! 'Hello'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다.  C:\Windows\System32\myApp>The current time is 6/16/2021 12:53:58 PM

### ISSUE THREAD

**Issue by qwer987654321aazz** [dotnet/core#6378]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
What is the error you ran into?

**Comment by mairaw** [comment]
You just need to type `dotnet run`, not `dotnet run Hello World!`
