### ISSUE TITLE
Add Support for CBL-Mariner

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6379]
This issue is created to track progress for the work to enable CBL-Mariner support for .NET Core 2.1, 3.1 and .NET 5.

### Product and Test updates
- [x] [All teams] Do a compatibility check for the product with the new OS
- [ ] [CoreCLR/CoreFX] Runtime / RID Support update 
- [x] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable) 
- [x] [Infra] Replace docker tags used in builds across repos and branches
- [x] [CLI team] Update CI legs to latest updated Dockerfile 
- [ ] [All teams] Update test infrastructure to support the new version
- [x] [Acquisition] Add support within nightly repos 
- [x] [Acquisition] Deploy to master (GA) during next patch release cycle        

## Release team:
- [ ]  Notify .NET Core teams regarding new OS release
- [ ] Add feed for new OS release to packages.microsoft.com (if applicable)
- [ ]  Update release manifest files 
- [x] Create new Docker files to test the new OS
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by rbhanda** [comment]
https://github.com/dotnet/aspnetcore/pull/33388
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/453
https://github.com/dotnet/dotnet-docker/pull/2881

**Comment by adegeo** [comment]
@rbhanda  What should I do for docs on this?

**Comment by rbhanda** [comment]
Adding @leecow who can help guide for the docs.
