### ISSUE TITLE
erro ao executar o como dotnet new console 

### ISSUE THREAD

**Issue by Hewertonbsb** [dotnet/core#6380]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Você pode fornecer mais informações de qual erro está ocorrendo quando você executa o comando? E o comando `dotnet` executou direitinho?

Você pode tb dizer o que o comando `dotnet --info` retorna?
