### ISSUE TITLE
Cant run the dotnet because the api-ms-win.dll is missing, how do i fix this?

### ISSUE THREAD

**Issue by Sealthe** [dotnet/core#6382]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
What version of dotnet are you using and where did you install it from?

**Comment by mairaw** [comment]
What version of Windows are you running?
For a couple of older versions, you need to install additional dependencies:
https://docs.microsoft.com/dotnet/core/install/windows?pivots=os-windows&tabs=net50#additional-deps
