### ISSUE TITLE
json not refresh 

### ISSUE THREAD

**Issue by Maheshg8761** [dotnet/core#6384]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

hi i have change on weather.json but is not reflect in front end

**Comment by michaelgsharp** [comment]
What were you trying to do? Can you share your code and what your steps were?
