### ISSUE TITLE
BlazorApp

### ISSUE THREAD

**Issue by Suvynas** [dotnet/core#6385]
I made a Blazor App with click me button and counter but its not counting 
[Counter.razor.txt](https://github.com/dotnet/core/files/6667911/Counter.razor.txt)
[Index.razor.txt](https://github.com/dotnet/core/files/6667918/Index.razor.txt)

**Comment by michaelgsharp** [comment]
Were you following a tutorial? If so, which one? What version of dotnet are you using?
