### ISSUE TITLE
Got compile error while build the app

### ISSUE THREAD

**Issue by khurshidmalik** [dotnet/core#6394]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	myApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1179

**Comment by michaelgsharp** [comment]
So NetFramework version 5 does not exist. You were probably meaning just .NET5 instead. Is this for a tutorial? Or what?

In your project file, you should switch the `TargetFramework` tag to look like this:
`<TargetFramework>net5.0</TargetFramework>`

**Comment by mairaw** [comment]
Sometimes you also get this error if you don't have the .NET 5 SDK installed on the machine. Are you trying to build via CLI or VS? If VS, what version of VS are you on?
