### ISSUE TITLE
Zsh Shell: Cannot check if install was successful?

### ISSUE THREAD

**Issue by brennankapollock** [dotnet/core#6395]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I'm trying to check if my install succeeded but when i type dotnet it says the command cannot be found.

**Comment by michaelgsharp** [comment]
Did you open a new terminal window?

**Comment by michaelgsharp** [comment]
And what version of Mac are you on?
