### ISSUE TITLE
Support for Ubuntu 16.04 in .NET 6

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/core#6400]
Support for Ubuntu 16.04 was apparently [removed](https://github.com/dotnet/core/blob/06bc572c921014dc77c0d1217861ce10d1cd382b/release-notes/5.0/5.0-supported-os.md) in .NET v5.0.6, not long after it reached end-of-life on 2021-04-30.

Currently [.NET 6 Support](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md) still shows support for Ubuntu 16.04. Will this be the case or not when .NET 6 is released?

**Comment by mairaw** [comment]
We typically don't support EOL versions. @leecow @rbhanda should the .NET 6 support doc be updated too?

**Comment by richlander** [comment]
I believe that change to .NET 5 was a mistake. We had intended to continue to support Ubuntu 16.04.

> We typically don't support EOL versions.

Absolutely true. We believe that we still have sizable usage on Ubuntu 16.04. I believe we intend to keep Ubuntu 16.04 as a test leg to ensure we don't break it.

**Comment by jamshedd** [comment]
@richlander is correct - for 5.0, we got buyoff from the directors based on the usage stats so we do support 16.04 for 5.0. Once we have current stats for 16.04 we can probably make a similar case for 6.0.

**Comment by mairaw** [comment]
So should we add 16.04 back to the .NET 5 document @jamshedd?
https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md

**Comment by jamshedd** [comment]
> So should we add 16.04 back to the .NET 5 document @jamshedd?
> https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md

Yes please.

**Comment by xtqqczze** [comment]
See also: #6430
