### ISSUE TITLE
dotnet watch run blazor application error

### ISSUE THREAD

**Issue by DevHamza-Core** [dotnet/core#6403]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

![bApp](https://user-images.githubusercontent.com/73877190/122880875-f3be1880-d353-11eb-8cd0-d4db07b9d8dd.png)
This issue occured on first run. Please look into it and provide the solution.

**Comment by krwq** [comment]
cc:@Pilchie

**Comment by Pilchie** [comment]
@karelz @Tratcher does this socket error look familiar?

**Comment by Tratcher** [comment]
Port conflicts. Things like docker and WSL can reserve port ranges. You can stop those services, change their reservations, or change the application's port in launchsettings.json
https://github.com/dotnet/aspnetcore/issues/25562

**Comment by DevHamza-Core** [comment]
@Pilchie @krwq @Tratcher Thanks. I changed the port which might be occupied by the docker and it runs fine now. Need to dig into docker to understand it's working.

**Comment by krwq** [comment]
Thanks @DevHamza-Core! Sounds like your issue is fixed. Feel free to re-open this issue if you think we should do anything more here.
