### ISSUE TITLE
modify setup

### ISSUE THREAD

**Issue by NASIM537** [dotnet/core#6406]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

hi 
I have windows 10 Home on my computer.
When I download  .NET SDK ,  I get a modify setup which has three alternatives ; repair , close and something else. 
I don´t know how to fix the problem.
kind regards nasim

**Comment by mairaw** [comment]
That usually indicates you already have it installed. You can confirm by going to Add or remove programs.

Can you post the output of `dotnet --info`?

**Comment by NASIM537** [comment]
Hi and thank you for your comment.
I wonder if man can use  . Net without having visual studio.?
Kind regards nasim

**Comment by mairaw** [comment]
You don't necessarily need Visual Studio. Here are some options:
https://dotnet.microsoft.com/platform/tools

It will depend the kind of app you're trying to build.

**Comment by NASIM537** [comment]
Thank you so much again
Kind regards nasim

**Comment by mairaw** [comment]
Anything else we can assist you?

**Comment by NASIM537** [comment]
It is very nice of you to want to help me. 
Nothing so far.
best regards Nasim

**Comment by NASIM537** [comment]
Hi, I found a page on internet about getting started with .NET  . 
To create an application first you need to download   .NET SDK  and then open a termial like power shell and enter these commands.
dotnet new console -- output sample1
dotnet run-- project sample 1
The output should be hello world !
What  I got was that I had to rerun the command and pass -- force to accept and create. The resource file couldn´t be found.
I can not understand why I can not run the program?
I wonder if you could help me with this issue.
kind regards 
Nasim

**Comment by krwq** [comment]
@NASIM537 can you please:
- share output of `dotnet --info`
- share exact instructions you have run
- copy & paste error message or warning you are concerned about

**Comment by NASIM537** [comment]
I have written exakt instruction I have run and the output too. But unfortunately I don't know how to copy and paste the error message.

**Comment by NASIM537** [comment]
Hi ,  I have just succeded to copy and paste instructions I have run.
Could you please help me how to get the right output which is hello world!
kind regards nasim
soft Windows [Version 10.0.19041.1052]
(c) Microsoft Corporation. Med ensamrätt.

C:\Users\Nasim Khatibi>dotnet new console --force
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\Nasim Khatibi\Nasim Khatibi.csproj...
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.


C:\Users\Nasim Khatibi>run
'run' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Nasim Khatibi>dotnet run
C:\Program Files\dotnet\sdk\5.0.301\Microsoft.Common.CurrentVersion.targets(3161,5): error MSB3552: Resource file "**/*.resx" cannot be found. [C:\Users\Nasim Khatibi\Nasim Khatibi.csproj]

The build failed. Fix the build errors and run again.

**Comment by mairaw** [comment]
The SDK will usually tell you if you already have a project on the location you're trying to run `dotnet new console`. That's why it's telling you to run with the `--force` option. To avoid that, I'd run with the `-o` option like we show here: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create

If you already have a folder called myApp, give it a new name. I'd try to start over and have a clean project. Let us know how that goes.

If that doesn't work, please paste the contents of the .csproj file here.

**Comment by NASIM537** [comment]
I think I have succeeded .
Thank you so much for your help. 
best regards nasim

Microsoft Windows [Version 10.0.19041.1052]
(c) Microsoft Corporation. Med ensamrätt.

C:\Users\Nasim Khatibi>dotnet new console -o myApp
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myApp\myApp.csproj...
  Determining projects to restore...
  Restored C:\Users\Nasim Khatibi\myApp\myApp.csproj (in 102 ms).
Restore succeeded.


C:\Users\Nasim Khatibi>cd myApp

C:\Users\Nasim Khatibi\myApp>dotnet run
Hello World!

**Comment by mairaw** [comment]
Yay! Yep, it looks good. I'll close the issue for now but let us know if you have more issues on your .NET learning journey.
