### ISSUE TITLE
Error 404: Fresh project

### ISSUE THREAD

**Issue by kunaldas1997** [dotnet/core#6413]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows
Created the project as stated on the website. but returns error 404. 

Net 6.0 preview

**Comment by krwq** [comment]
Hello @kunaldas1997 can you please share `dotnet --info`?

Where are you getting 404? In the command prompt or you're seeing that in the browser when you try to navigate to your web app?
