### ISSUE TITLE
5.0 release.json doesn't contain 5.0.7

### ISSUE THREAD

**Issue by Jacksondr5** [dotnet/core#6420]
### Description
Note sure if this is the right place to put this issue or not, but the [5.0 specific releases.json on windows.net](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json) doesn't have 5.0.7 listed in it even though both the [releases-index.json](https://github.com/dotnet/core/blob/main/release-notes/releases-index.json) and [5.0 specific releases.json](https://github.com/dotnet/core/blob/main/release-notes/5.0/releases.json) files in this repo do.

**Comment by mairaw** [comment]
@rbhanda @leecow can you check this? I don't know how the windows.net location gets updated.

**Comment by kalaskarsanket** [comment]
The file has been corrected.

**Comment by mairaw** [comment]
Thanks @kalaskarsanket. Closing the issue then.
