### ISSUE TITLE
Synology DSM 7 - MONO

### ISSUE THREAD

**Issue by joombler** [dotnet/core#6426]
Dear team, just switched to DSM7 on my synology NAS. In the update list @ https://github.com/SynoCommunity/spksrc/issues/4524 for Mono is written: **avoid mono for DSM7, migrate related packages to dotnet instead**
Can you hint me on how to handle this (for me confusing) statement ? Thanks!

**Comment by krwq** [comment]
@joombler I think it will make more sense to ask this question in https://github.com/SynoCommunity/spksrc/ repo. If you have specific issues with mono you'd like to get fixed to get that package to work then open issue in the mono repo: https://github.com/mono/mono/issues

**Comment by joombler** [comment]
Hi Krzysztof,
Thanks for your reply. Will follow up!
 
Best regards,
Jos

**Comment by krwq** [comment]
Thank you! I'll close the issue since there is nothing to do on our side, feel free to reopen if you feel there is something we should do on our side.
