### ISSUE TITLE
change your current directory to one where you have permissions to create a new folder

### ISSUE THREAD

**Issue by nevets95** [dotnet/core#6428]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by nevets95** [comment]
change your current directory to one where you have permissions to create a new folder

**Comment by krwq** [comment]
@nevets95 the issue you're seeing is telling you the solution. Example solution would be to run this before any steps in the tutorial:

```
cd %USERPROFILE%
```
