### ISSUE TITLE
Problem while installing asp.net

### ISSUE THREAD

**Issue by divyajyotisingh01** [dotnet/core#6429]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet new console -o myApp (after installing when I write this in cmd.

![image](https://user-images.githubusercontent.com/47771990/124387369-f3cafa80-dcfb-11eb-8a2a-d9451abb9cb0.png)

**Comment by krwq** [comment]
Hi @divyajyotisingh01 have you read the note in the bottom of the tutorial? You need to run the tutorial steps from the directory you have access to. Example solution is go to your user profile before running any steps of the tutorial:

```
cd %USERPROFILE%
```

**Comment by WeihanLi** [comment]
Seemed access denied from the error, try to execute the command in another folder with permission or try to execute  with admin permission
