### ISSUE TITLE
Support for Ubuntu 16.04 in .NET 3.1/2.1

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/core#6430]
Release notes documenting support for Ubuntu 16.04 in .NET 3.1 was removed in https://github.com/dotnet/core/commit/0ba0707d9c989c3d8f209325f5241aa262b39603.

Since Ubuntu 16.04 in still supported in .NET 5.0, it is likely this removal was a mistake,

_Follow-up to #6400._

**Comment by xtqqczze** [comment]
Also removed in .NET 2.1 release notes: 432e8ce0329d75e60c1d333dd1ccbbe2d06e6455

**Comment by krwq** [comment]
cc: @jamshedd @leecow @rbhanda

**Comment by jamshedd** [comment]
@mairaw, we need to add this back for 3.1 too. I don't think we need to do the same for 2.1 since that will reach end of support by next month, so even if Ubuntu 16.04 were supported 2.1 itself will not be.

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/6436 is created to resolve this.
