### ISSUE TITLE
Creating web page using C#

### ISSUE THREAD

**Issue by Vaibhavking8** [dotnet/core#6432]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

I opened Index.cshtml
and replaced the code with:
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>

But it is showing error.
please send full sample code as i am a beginner.

**Comment by krwq** [comment]
Hey @Vaibhavking8 I'm not sure I understand the problem, can you please elaborate? What error are you seeing?

Are you seeing the error in the browser or in the command prompt where you've run `dotnet run`?

**Comment by mairaw** [comment]
Also make sure you edit the cshtml file and not the cs file. Sometimes Windows will hide the extension and you might end up editing the wrong file.

**Comment by Vaibhavking8** [comment]
I was opening cs file that's why I was getting error.
But now I have resolved it

**Comment by Vaibhavking8** [comment]
I was opening the wrong file.
But now the issue is resolved

**Comment by mairaw** [comment]
Thanks for letting us know. I'm glad you resolved it.
