### ISSUE TITLE
Uri (TryCreate, IsWellFormedUriString)

### ISSUE THREAD

**Issue by Despa22** [dotnet/core#6441]
### Validating URL Input

* I'm trying to validate a URL input using a predefined methods (TryCreate, IsWellFormedUriString) 
* Please find the below code snippet 
  
![Uri (TryCreate, IsWellFormedUriString)](https://user-images.githubusercontent.com/25004309/124763930-2152b680-df3d-11eb-867e-51b663a880ca.png)

**Comment by wfurt** [comment]
What is the problem @Despa22 ? 
cc: @MihaZupan

**Comment by bartonjs** [comment]
Both comma and colon are legal characters in a URL, so as strange as it looks, that URL _is_ a valid URL.

For example, the oldest capture of www.microsoft.com by archive.org is https://web.archive.org/web/19961020014044/http://www.microsoft.com:80/

web.archive.org is one of the few places I've seen where a URL is used as part of a bigger URL, so your test case is probably not locating a valid target... but it's syntactically valid.

**Comment by Despa22** [comment]
Thanks @bartonjs for your reply
Do you have any suggestions that I can apply here?

**Comment by RiadKatby** [comment]
I think you need not to reject this kind of URL because how you going to deal with URL that have commas like in google map location?

**Comment by MihaZupan** [comment]
Closing this as by-design.
