### ISSUE TITLE
csproj error

### ISSUE THREAD

**Issue by YoungSkuna** [dotnet/core#6445]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
The problem I am getting is when I try to run the changes within the above link this error shows:C:\Users\Nathan\myApp\myWebApp>dotnet watch run
watch : Started
Building...
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(4,13): error CS1002: ; expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(4,14): error CS1001: Identifier expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,6): error CS1002: ; expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1001: Identifier expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1514: { expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1513: } expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(8,14): error CS1002: ; expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(9,12): error CS1002: ; expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myApp\myWebApp\Pages\Index.cshtml.cs(10,7): error CS1002: ; expected [C:\Users\Nathan\myApp\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

and I have no clue how to fix it

**Comment by YoungSkuna** [comment]
im using windows 10

**Comment by wfurt** [comment]
What is Index.cshtml.cs? It seems like the project is trying to build it as c# source but it may be html? 
Could you include the failing files and perhaps output from `dotnet --info`?

**Comment by YoungSkuna** [comment]
can u elaborate

**Comment by YoungSkuna** [comment]
the project should be html if that helps

**Comment by wfurt** [comment]
So why does it have `.cs` extension? I think the project will pick it up and try to treat it based on the extension.

**Comment by YoungSkuna** [comment]
idk, i was just following the tutorial thing tbh and that error came up

**Comment by YoungSkuna** [comment]
im really new to coding if u cant tell so just need help to get this setup properly and then I can teach myself

**Comment by wfurt** [comment]
Why don't you start from begging. Create/download the project and try to build it and run it without modifications. 
And do not rename any files and don't change the file extensions.
If you run to problem zip whole folder and attach it to the issue.

**Comment by YoungSkuna** [comment]
ok ill do that, i dont think i changed anything but its possible

**Comment by YoungSkuna** [comment]
it still has .cs at the end of some of the files

**Comment by YoungSkuna** [comment]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(9,25): error CS1514: { expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(11,18): error CS1002: ; expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(12,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(12,2): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(13,21): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(13,23): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(15,1): error CS8803: Top-level statements must precede namespace and type declarations. [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(14,2): error CS1525: Invalid expression term '<' [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(16,6): error CS1002: ; expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(16,11): error CS1001: Identifier expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(16,11): error CS1514: { expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(16,11): error CS1513: } expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(16,11): error CS1525: Invalid expression term '=' [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(16,26): error CS1525: Invalid expression term '<' [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(17,14): error CS1002: ; expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(17,14): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(17,23): error CS1525: Invalid expression term '/' [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(17,27): error CS1525: Invalid expression term '<' [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(18,12): error CS1002: ; expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(18,20): error CS1003: Syntax error, ',' expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]
C:\Users\Nathan\myWebApp\Pages\Index.cshtml.cs(19,7): error CS1002: ; expected [C:\Users\Nathan\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by YoungSkuna** [comment]
thats the error this time

**Comment by wfurt** [comment]
Then run the `dotnet --info` and provide your content.

**Comment by YoungSkuna** [comment]
C:\Users\Nathan\myWebApp>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by YoungSkuna** [comment]
is that what u wanted

**Comment by wfurt** [comment]
yes. and compress your project and post it so I can look at it.

**Comment by YoungSkuna** [comment]
compress?

**Comment by YoungSkuna** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace myWebApp.Pages
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>

**Comment by YoungSkuna** [comment]
thats the code if it helps

**Comment by YoungSkuna** [comment]
well minus the <h> and that type of stuff

**Comment by YoungSkuna** [comment]
oh i see what u mean by compress now I think

**Comment by YoungSkuna** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace myWebApp.Pages
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>`

**Comment by wfurt** [comment]
https://support.microsoft.com/en-us/windows/zip-and-unzip-files-8d28fa72-f2f9-712f-67df-f80cf89fd4e5
And then you attach it to this issue.

**Comment by YoungSkuna** [comment]
[myWebApp.zip](https://github.com/dotnet/core/files/6787810/myWebApp.zip)

**Comment by tziemek** [comment]
You are mixing the *cshtml* with the *cs* file. See **Privacy.cshtml** and **Privacy.cshtml.cs** for reference. HTML (`@page` `<div>` etc.) should be in your `cshtml` file. The `namespace` und `using` declarations should be in your `cs` file. That is very basically what the compiler is telling you with these errors.

**Comment by mairaw** [comment]
Maybe delete the folder and start over? Pay attention to the file extension. Windows sometimes hides the file extensions, so it looks like you're editing the cshtml file, when in fact you're editing the .cs file.
