### ISSUE TITLE
 C:\Users\user>dotnet new console -o myApp Creating this template will make changes to existing files:   Overwrite   ./myApp.csproj   Overwrite   ./Program.cs  Rerun the command and pass --force to accept and create.

### ISSUE THREAD

**Issue by Pussyeater007** [dotnet/core#6447]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
What is the problem @Pussyeater007? If you want to you should create new project or not use 'new' on existing one.

**Comment by mairaw** [comment]
This error message usually means you have already created a project on that same location. You can delete the myApp folder and start over or pass the --force option to recreate the project from scratch.
