### ISSUE TITLE
dotnet is not recognized in command prompt

### ISSUE THREAD

**Issue by b1tn3tw0rk** [dotnet/core#6449]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

![image](https://user-images.githubusercontent.com/80435427/125153157-cfb65180-e11f-11eb-9238-90eab87dc202.png)

**Comment by wfurt** [comment]
did you install the SDK? 
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by mairaw** [comment]
Did you open a new terminal after you installed the SDK?
