### ISSUE TITLE
Imports.razor error on using the Shared folder.

### ISSUE THREAD

**Issue by ivwivw** [dotnet/core#6450]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Following the guide and starting the app with dotnet watch run. In Visual Studio code in _imports.razor there is a namespace does not exist error. Caused probably due to razor components not needing namespace declarations. If I add a cs class the namespace is resolved.

![afbeelding](https://user-images.githubusercontent.com/12259089/125162061-3e2dfa80-e186-11eb-97bb-ff0238559821.png)

Add a class to the shared folder...

![afbeelding](https://user-images.githubusercontent.com/12259089/125162206-e93eb400-e186-11eb-85e8-a60cac5bebed.png)

**Comment by eiriktsarpalis** [comment]
cc @mairaw

**Comment by mairaw** [comment]
Did you create that newclass file? That is not part of the tutorial.

**Comment by ivwivw** [comment]
Yes. To show (test) the issue.
________________________________

**Comment by mairaw** [comment]
So if you just run `dotnet new blazorserver -o BlazorApp --no-https` and try to run the app, you get an error?

**Comment by ivwivw** [comment]
Hi Maira.

I just tried reproducing the issue. By executing dotnet new blazorserver -o BlazorApp --no-https and making some changes.
The issue did not showed it self again. So I think it could have been caused by and extension and or my Visual studio code version.
