### ISSUE TITLE
Ubuntu 20.10 "Groovy Gorilla" reaches end of life on 22 July 2021

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6452]
[Ubuntu 20.10 reaches end of life on July 22, 2021](https://fridge.ubuntu.com/2021/06/18/ubuntu-20-10-groovy-gorilla-reaches-end-of-life-on-july-22-2021/)
This issue is created to track progress for the remove support for Ubuntu 20.10 from .NET Core 2.1, .NET Core 3.1 and .NET 5.0

### Repos team to update:

- [ ] Remove installers for the outdated distro
- [ ] Stop building Official Docker™ images
- [ ]  Remove build support
- [ ]  Remove test assets

### Infrastructure Team Accountabilities/Deliverables:

- [ ]  Notification to NetCore Engineering Partners
- [ ]  Remove the outdated version from the hardware pool 

### Release Team

- [x]  Send Notification to every team in .NET for upcoming addition
- [x]  Supported OS content gets updated on GitHub and marketing sites. 
- [x]  Update release manifest files. 
- [ ]  Docker files which are used for install testing needs to be updated. 

### Document updates:
- [ ] Add/Remove OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by richlander** [comment]
FYI: We only produce official docker images for the Ubuntu LTS releases (as it relates to Ubuntu). So, you can delete that task for this release.

We produce container images for:

- All Alpine releases.
- All Debian releases.
- Ubuntu LTS releases.

**Comment by ashnaga** [comment]
Resolving this one
