### ISSUE TITLE
.NET July  2021 Update - .NET 5.0.8 and .NET Core 3.1.17

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6459]
Release Notes 
[5.0.8](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.8/5.0.8.md)
[3.1.17](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.17/3.1.17.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.8 | 3.1.17
|--|--|--
| Ubuntu 16.04   |  ✅  |  ✅  |
| Ubuntu 18.04     |  ✅  |  ✅  |
| Ubuntu 20.04    |  ✅  |  ✅  |
| Ubuntu 21.04   |  ✅  |  ✅  |
| Centos 7     |  ✅  |  ✅  |
| Centos 8  |  ✅  |  ✅  |
| Debian 9    |  ✅  |  ✅  |
| Debian 10  |  ✅  |  ✅  |
| Fedora 33  |  ✅  |  ✅  |
| Fedora 34 |  ✅  |  ✅  |
| OpenSUSE 15  |  ✅  |  ✅  |
| SLES 12  |  ✅  |  ✅  |
| SLES15  |  ✅  |  ✅  |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by duke7553** [comment]
Does .NET 5.0.8 include the WinForms ARM64 backport from .NET 6?

**Comment by saul** [comment]
Should we expect 5.0.205 SDK Docker images to be released too? I can't find any here: https://mcr.microsoft.com/v2/dotnet/sdk/tags/list

**Comment by marcoteodoro** [comment]
Hi Guys, can you let me know if installing the [.net5 runtime ](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.8-windows-hosting-bundle-installer ) will require a server reboot?

**Comment by KoFrank** [comment]
Hi everyone, after installing these Updates the previous versions (.NET June 2021 Update - .NET 5.0.7 and .NET Core 3.1.16) are again showing up in the update list and of course they fail to install as they would downgrade the current update. As it presents itself these updates do not replace the older versions. Please advise on how I can proceed with this.

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/6553

**Comment by andergoros** [comment]
> Hi everyone, after installing these Updates the previous versions (.NET June 2021 Update - .NET 5.0.7 and .NET Core 3.1.16) are again showing up in the update list and of course they fail to install as they would downgrade the current update. As it presents itself these updates do not replace the older versions. Please advise on how I can proceed with this.

Same!!!

**Comment by Opwekking** [comment]
Well same problem here. For a few days now. Failing installation.
![image](https://user-images.githubusercontent.com/44204840/140626179-2386645d-a0bd-4640-9fb3-4d47417f33a8.png)
Ending in an error (sorry, it's Dutch):
![image](https://user-images.githubusercontent.com/44204840/140626199-2c400519-fe34-4c8b-b712-b17105c1d987.png)

|

**Comment by EngineerJack** [comment]
Ha, now I understand. I've been trying for the last week or so to get my Windows updates to work. And after essentially teaching myself how to do it all manually, I finally realize this is a known issue.

This has stressed me the hell out. But I'm glad to find out that I'm not missing those 3 essential updates.
