### ISSUE TITLE
Is whether .net core support Chinese char？

### ISSUE THREAD

**Issue by a764578566** [dotnet/core#646]
Is whether .net core support Chinese char ?

`string obj="中文";
ChineseChar chineseChar = new ChineseChar(obj);
string pinyin = `chineseChar.Pinyins[0].ToString();`

pinyin=="zhongwen"

**Comment by Petermarcu** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@a764578566 We don't support any type named "ChineseChar" could you send some more info what exactly this class does? and where did you use it before? we never supported such class even in the full framework.

**Comment by a764578566** [comment]
Download [ Visual Studio International Pack ](https://www.microsoft.com/en-us/download/details.aspx?id=15251)

`using Microsoft.International.Converters.PinYinConverter;`


`string obj="中文"; `
`ChineseChar chineseChar = new ChineseChar(obj);`
`string pinyin = chineseChar.Pinyins[0].ToString();`

**Comment by tarekgh** [comment]
Thanks @a764578566 for the pointer. 

I have ran the APIPort https://github.com/Microsoft/dotnet-apiport on a couple of assemblies existed in this International Pack and it is fully compatible with the netcore 2.0. so if you target netcore app 2.0 you'll be able to use these assemblies in your app. 

```
ApiPort.exe analyze -f "ChnCharInfo.dll" -t ".NET Core, Version=2.0" -r HTML -o AnalysisReport.html
```

```
Portability Summary
Assembly	.NET Core,Version=v2.0
ChnCharInfo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=18f031bd02e5e291	100.00 %
Hide rows:
 Hide rows that don't have problems
Hide columns:
 .NET Core,Version=v2.0   Recommended changes
```
