### ISSUE TITLE
.net issue windows 10

### ISSUE THREAD

**Issue by TenacityAdmin** [dotnet/core#6464]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\leigh>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\leigh>dotnet new console -o myApp
  **It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download**

C:\Users\leigh>cd myApp
The system cannot find the path specified.

C:\Users\leigh>

**Comment by John0King** [comment]
@TenacityAdmin  Maybe you only install runtime in your pc ,  you should install sdk.

and you can use `dotnet --info`   to see the sdk section or `dotnet --list-sdks`

**Comment by mairaw** [comment]
Can you let us know the output of `dotnet --info`? Did you install the SDK already?

If you did and it's still not showing when you run `dotnet --info`, I can provide some suggestions.
