### ISSUE TITLE
dotnet: command not found

### ISSUE THREAD

**Issue by lselector** [dotnet/core#6468]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

dotnet: command not found

**Comment by wfurt** [comment]
do you have `/usr/local/share/dotnet/dotnet` and if so can you execute it directly? The installer should add `/usr/local/share/dotnet/' to a search PATH but there can be some issue. You can try to close and re-open terminal and check if the PATH is set.

**Comment by lselector** [comment]
Right,

I added this to the PATH - and it works now.
Thank you.

-- 
Warm Regards
Lev Selector
+1-917-310-0088
(voice, text, whatsapp)




Tomas Weinfurt wrote on 7/14/21 11:18 PM:
