### ISSUE TITLE
think referencing seems to be broken in 1.1 but is ok in 1.0 (FileNotFoundException)

### ISSUE THREAD

**Issue by lilpug** [dotnet/core#647]
Hi,

I assume this could be a bug as i have been dealing with this all day after trying to reference different libraries. After further research i found out this does not seem to be an issue in 1.0 but only is affecting me on 1.1. I have been testing this on a web application using .Net core but others seem to be having the same issue even on the application versions.

I am using Visual Studio 2017, i have managed to replicated this problem on 3 machines now,  you can replicated the issue very easily by doing the following steps:-

- make a new asp.net core web application (.Net core) and a class library (.Net core) (**both .NETCoreApp 1.1 for target frameworks**). 
- build the empty library
- go to the web application, add the reference and reference the namespace in your HomeController.cs
- initialise the empty class from the library in the Index function.
- hit run

it will build and run the project but it will fail to load the library when it hits the function you have referenced the code in. It gives a "FileNotFoundException: Could not load file or assembly" error

i have also found some StackOverflow threads that seem to be related to the same issue as well.
http://stackoverflow.com/questions/43662331/how-do-i-add-a-net-core-class-library-dll-to-asp-net-core-project/43913795#43913795
http://stackoverflow.com/questions/43470906/reference-an-asp-net-core-class-library

**Comment by Frostbite952** [comment]
Hi, 

I followed what you said but did not get "FileNotFoundException: Could not load file or assembly" error. Below I have included the steps I took, let me know if I missed any steps or did something wrong here. 

- Created a new Core app. 
- Created a Core Class Library.
- Left it empty initially.
- Right clicked my web app and went to Add > Reference.
- Selected the class library I created.
- Opened the home controller. 
- Added the namespace. 
- In the Index IActionResult I put Class1 lstclass = new Class1();
- Ran the app no error. 

- I then went back to the class and did the follow. 
- Added field called name public string name;
- Set it to equal some text - public string name = "test";
- In the controller under index I used ViewData["Class"] = lstclass.name;
- Then on the index page I placed @ViewData["Class"] = lstclass.name; on to the page. 

If I’m way off what you have said, ignore everything I just put.

**Comment by lilpug** [comment]
thanks for testing this, that is rather interesting, as the steps that you have taken seem to be exactly what i have done on three different machines :-S, are you using 1.1?

**Comment by Frostbite952** [comment]
I'm using Visual Studio 2017 professional. When I created the new project I selected ASP.Net Core Web Application(.NET Core). The .csproj states i'm using 1.1 -<TargetFramework>netcoreapp1.1</TargetFramework> 

I have both VS 15 and 17 installed, don't want to do the one way conversion with some the projects we have running yet. I don't suppose you have ran a repair on VS encase something got corrupted during the install?

**Comment by lilpug** [comment]
that is definitely the same version as me and yes i have and unfortunately still get the issue, i even got my colleague to try on his version just in case as i did used to have development versions of .NET Core before it was released but i know he didn't and we still get the same issue :-S

**Comment by Frostbite952** [comment]
If you go to help > About Microsoft Visual Studio what version do you have? I've attached mine below. I'm wondering as I just seen a new update came out 3 hours ago for VS 2017 and I haven't done that yet. 
![about](https://cloud.githubusercontent.com/assets/5512959/25956858/cb3f3ac8-3664-11e7-918f-216dc69a1a2a.PNG)

**Comment by lilpug** [comment]
i think mine might be a version behind yours actually:-

![image](https://cloud.githubusercontent.com/assets/1824684/25957156/8f9b82be-3665-11e7-9052-3d6fef3845f2.png)

**Comment by Frostbite952** [comment]
I just had a colleague try his 15.2 and he got the same error as you. If you can find a 15.1 download hopefully your error goes away.

**Comment by lilpug** [comment]
o thank you very much i will give it a go tomorrow morning and hopefully that will solve the issue im just glad its not a .Net Core issue haha, thanks for helping look into this :)

**Comment by Frostbite952** [comment]
If that doesn't work I'm sure someone more knowledgeable than I can help you on here. I'm going to try and update my VS at home here to 15.2 and see if the issue is here or localised to the work PC's. I will let you know if the issue is still there.

**Comment by wstaelens** [comment]
asp.net core mvc: 
I started with VS2015 Pro on 1.0 tried upgrade to 1.1.
After hours of trying to get the config working I gave up and said f*ck it and created an asp.net mvc app like we used to do.

**Comment by lilpug** [comment]
unfortunately after updating my VS 2017 version that has not fixed the issue for me, i have even recreated the web and library projects from scratch again to test it and i still get the same error. 

I will ask my colleague to update his version today and see if it starts working for him as he did not use any previous development versions of .Net Core like me.

will update after

![image](https://cloud.githubusercontent.com/assets/1824684/25994397/9f1bf7f0-3705-11e7-925d-e01aa8838f46.png)

**Comment by Petermarcu** [comment]
@barrytang

**Comment by barrytang** [comment]
@Srivatsn?

**Comment by richlander** [comment]
@lilpug can you share your simple example? Something odd is happening. We create projects with dependencies all the time and they work. There must be something unique at play.

**Comment by richlander** [comment]
I tried this in VS 2017 15.2. I was not able to repo the issue. I've attached my sample. 
[aspnetcorewithdependencies.zip](https://github.com/dotnet/core/files/1120571/aspnetcorewithdependencies.zip)

Tell me if you can repro with that or how my sample is different from your case.

**Comment by lilpug** [comment]
this does not seem to be an issue any longer in the future versions so i will close this down.
