### ISSUE TITLE
'dotnet' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by saitarun-5** [dotnet/core#6470]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
did you install the SDK? Does it work if you call it with full path from "Program Files" ?
