### ISSUE TITLE
watch : Could not find a MSBuild project file in 'C:\Users\bhavi'. Specify which project to use with the --project option.

### ISSUE THREAD

**Issue by bhavishaymankani** [dotnet/core#6471]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

watch : Could not find a MSBuild project file in 'C:\Users\bhavi'. Specify which project to use with the --project option.

**Comment by wfurt** [comment]
Is there subdirectory with the project? When you create new project it would typically create subdiretory in the current project.
