### ISSUE TITLE
No templates matched the input template name: blazorserver.

### ISSUE THREAD

**Issue by shailesh6498** [dotnet/core#6472]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

No templates matched the input template name: blazorserver.

**Comment by mairaw** [comment]
Can you let us know what's the output of the `dotnet --info` command?
