### ISSUE TITLE
Assets/Scripts/GameManager.cs(8,65): error CS1002: ; expected

### ISSUE THREAD

**Issue by chegor0** [dotnet/core#6473]
// Unity said that i have a 1002 error when i created 
// public void CompleteLevel () and Debug.Log("LEVEL WON!");

using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : MonoBehaviour {

    bool gameHasEnded = false;

    public float restartDelay = 1f

    public void CompleteLevel ()
    {
        Debug.Log("LEVEL WON!");
    }

    public void EndGame () 
    {
        if (gameHasEnded == false) 
        {
            gameHasEnded = true;
            Debug.Log("GAME OVER");
            Invoke("Restart", restartDelay);
        }
    }

    void Restart () 
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
    
}

**Comment by wfurt** [comment]
There should be ';' after  '1f'. the compiler gives you the line (8) and line position (65) where this should go.
Seems like you did not put in whole file so the numbering seems off in example above.
