### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by mr-robot01212** [dotnet/core#6474]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
It's showing some errors about Shared does not exists and namespace could not be found

**Comment by wfurt** [comment]
Can you provide more details @mr-robot01212? This is not sufficient to triage.
