### ISSUE TITLE
Tried the <Counter IncrementAmount="10" /> when following instructions given.

### ISSUE THREAD

**Issue by babj57** [dotnet/core#6478]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I tried the instruction using <Counter IncrementAmount="10" /> and I received An unhandled error has occurred. When the counter was removed it worked. Project was done in Visual Studio Code Version 1.58.2 using Windows 10 Version 21H1 OS Build 19043.1083.

**Comment by wfurt** [comment]
Can you share your code @babj57?
