### ISSUE TITLE
Could not execute because the application was not found or a compatible .NET SDK is not installed

### ISSUE THREAD

**Issue by jvatec** [dotnet/core#6480]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows 10 - 21H1

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Command:
dotnet new console -o myApp
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

Donwloaded SDK   Asp.NET 5.0.8 - https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.302-windows-x64-installer
Installed and active IIS 
Installed PowerShell 7.1.3
Installed Web Platform - https://www.iis.net/downloads/microsoft/web-platform-installer

**Comment by wfurt** [comment]
Did you also install dotnet SDK? Can you provide output of `dotnet --info` ?

**Comment by jvatec** [comment]
Thank you very much, it has already been solved, it was a mistake of mine, the console was in C: \ Windows \ system32> the years are not forgiving 😉
