### ISSUE TITLE
it cannot find the file mymicroservice 

### ISSUE THREAD

**Issue by ShabanaParve** [dotnet/core#6481]
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.

I recall we created MyMicroservice.

**Comment by wfurt** [comment]
what `docker ps` and `docker ps --all` gives you?

**Comment by ShabanaParve** [comment]
Dear Tomas,

I have put that task on parked. So I cannot remember right now. However, I
really appreciate your prompt response.

Best Regards,
Shabana

**Comment by safern** [comment]
@ShabanaParve thank you for the update. If you could provide us with more info that @wfurt requested, it would be very helpful to move this issue forward.
