### ISSUE TITLE
Le modèle « Console Application » ne peut pas être créé. Failed to create template. Details: Access to the path 'C:\Windows\system32\myApp' is denied..

### ISSUE THREAD

**Issue by Kikwaya** [dotnet/core#6483]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
This part is on that same page:

![image](https://user-images.githubusercontent.com/12971179/126257063-b574da13-9ca2-4ecd-b810-12d5f47f1fb3.png)

This error message means you cannot create the app on that directory. Try for example going to a different directory, like going to the users directory, and trying again `cd %USERPROFILE%`

Let us know if this worked.
