### ISSUE TITLE
My problem:   Error CS1525, error CS1002, CS1003.

### ISSUE THREAD

**Issue by azul29** [dotnet/core#6486]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by azul29** [comment]
when i  change in the file index.cshtml,cs, to output error CS!525, error CS1525.

**Comment by mairaw** [comment]
Can you make sure that you edited the Index.cshtml file and not the Index.cshtml.cs?
