### ISSUE TITLE
Problems with packages on https://packages.microsoft.com/debian/10/prod/dists/buster/ 

### ISSUE THREAD

**Issue by m00lecule** [dotnet/core#6487]
### Description

Hello - I just found that issue with https://packages.microsoft.com/debian/10/prod/dists/buster/ on docker reappeared  #6356 #3995

`docker run mcr.microsoft.com/dotnet/sdk:5.0 sh -c "wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb && apt-get install -y ./packages-microsoft-prod.deb && apt-get update -y"`

![image](https://user-images.githubusercontent.com/33501567/126477860-e23508d9-84fa-46f1-9d72-1f5424cfa613.png)

### Configuration

* Docker version 20.10.7, build f0df350
* Ubuntu 20.04.2 LTS

**Comment by Dave-EMIS** [comment]
I'm getting the same issue:

```
#10 3.416 E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-armhf/Packages.bz2  File has unexpected size (14648 != 14446). Mirror sync in progress? [IP: 40.85.80.91 443]
#10 3.416    Hashes of expected file:
#10 3.416     - Filesize:14446 [weak]
#10 3.416     - SHA512:dcde6b0120201ffd3ce98ccc67a941c82206af4c9f6edacb21dececab859d151b6b05ab9f59c1c7a0215912eccb319a632c26580371f84dfb723f6cfb64ab807
#10 3.416     - SHA256:8123690a1cfd7380c63554906b4bba25fc83142a3bc22c387ebc739f1427e1a5
#10 3.416     - SHA1:f134ba1077765a3c3f1e84dc50f36cfb319eaa05 [weak]
#10 3.416     - MD5Sum:9dd887b5872fbb823fc0ba1aae7eb306 [weak]
#10 3.416    Release file created at: Tue, 20 Jul 2021 21:47:43 +0000
#10 3.416 E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by pedropombeiro** [comment]
+1 experiencing this too, and none of our CI pipelines are able to run anymore. Hoping we can get it fixed soon!

**Comment by AGheller** [comment]
Same problem

`Err:6 https://packages.microsoft.com/debian/10/prod buster/main armhf Packages
  File has unexpected size (14648 != 14446). Mirror sync in progress? [IP: 104.214.230.139 443]
  Hashes of expected file:
   - Filesize:14446 [weak]
   - SHA512:dcde6b0120201ffd3ce98ccc67a941c82206af4c9f6edacb21dececab859d151b6b05ab9f59c1c7a0215912eccb319a632c26580371f84dfb723f6cfb64ab807
   - SHA256:8123690a1cfd7380c63554906b4bba25fc83142a3bc22c387ebc739f1427e1a5
   - SHA1:f134ba1077765a3c3f1e84dc50f36cfb319eaa05 [weak]
   - MD5Sum:9dd887b5872fbb823fc0ba1aae7eb306 [weak]
  Release file created at: Tue, 20 Jul 2021 21:47:43 +0000
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-armhf/Packages.bz2  File has unexpected size (14648 != 14446). Mirror sync in progress? [IP: 104.214.230.139 443]
   Hashes of expected file:
    - Filesize:14446 [weak]
    - SHA512:dcde6b0120201ffd3ce98ccc67a941c82206af4c9f6edacb21dececab859d151b6b05ab9f59c1c7a0215912eccb319a632c26580371f84dfb723f6cfb64ab807
    - SHA256:8123690a1cfd7380c63554906b4bba25fc83142a3bc22c387ebc739f1427e1a5
    - SHA1:f134ba1077765a3c3f1e84dc50f36cfb319eaa05 [weak]
    - MD5Sum:9dd887b5872fbb823fc0ba1aae7eb306 [weak]
   Release file created at: Tue, 20 Jul 2021 21:47:43 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by ajuch** [comment]
I'm wondering why we download the armhf package feeds are downloaded. Since at least our buildserver is an amd64 machine, the armhf package feeds are not needed. Maybe the workaround is adding the apt keys and the amd64 repo only and not using packages-microsoft-prod.deb

But since this is the recommended way to do it, it should work.

**Comment by AGheller** [comment]
Yes the packages-microsoft-prod.deb add all architecture, even if the server is amd64.
I change the /etc/apt/sources.list.d/microsoft-prod.list like this
`
#deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/10/prod buster main
deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main
`

**Comment by Immich** [comment]
Experiencing the same, CI pipeline broken since earlier today

**Comment by Dave-EMIS** [comment]
Looks to be an issue with the code in my docker container that is installing .NET 5 SDK, if I remove that I'm OK.

**Comment by ajuch** [comment]
Thanks @Dave-EMIS for fiddling with sed :-) On my docker image the microsoft.list file doesn't exist, so this works for me:

```
RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && sed -i 's/,armhf//g' /etc/apt/sources.list.d/microsoft-prod.list \
    && apt-get update \
    && apt-get install -y apt-transport-https \
    && apt-get update \
    && apt-get install -y dotnet-sdk-3.1
```

**Comment by pedropombeiro** [comment]
This seemed to have gotten fixed without any action on my part a few hours ago.

**Comment by Dave-EMIS** [comment]
> This seemed to have gotten fixed without any action on my part a few hours ago.

Yep, same here.

**Comment by jan-oratowski** [comment]
Still have this problem, but answer from @ajuch fixed it for me.

**Comment by safern** [comment]
@richlander seems to be fixed per some responses, but do you know who usually handles these kind of issues?

**Comment by richlander** [comment]
I'll ensure the right people are aware of this outage.

I apologize to anyone affected by the outage.

**Comment by dleeapho** [comment]
@NikolaMilosavljevic PTAL cc @jamshedd

**Comment by jamshedd** [comment]
@rbhanda, have we seen any further reports of this?
