### ISSUE TITLE
.net core 6 and visual studio version compatibility discrepancies

### ISSUE THREAD

**Issue by mprevot** [dotnet/core#6490]
### Description
I observed discrepancies in the environment supporting/required for .net 6 development, in particular the preview 5 does not make sense: VS2019 is 16.x, and VS2022 is 17.0, there is not _VS2019 17.0_:

[Preview 4: Visual Studio 2019 version 16.9 preview 4 ](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-preview.4.md)
[Preview 5: Visual Studio 2019 version 17.0](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-preview.5.md) 
[Preview 6: Visual Studio 2022 version 17.0](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-preview.6.md) 

I believe it should be VS2019 all the way.

**Comment by mairaw** [comment]
Thanks @mprevot. I've created a PR to fix this similar to the changes made in #6485

**Comment by mprevot** [comment]
I wonder: why was the environment upgraded from VS2019 to VS2022 from preview 4 to preview 5 ? Since net 6 is has long term support, it seems important to have it supported in VS2019 (and net 7, 8 for 2022).

**Comment by mairaw** [comment]
@leecow @rbhanda @jamshedd can one of you comment on that change of VS versions for .NET 6?

**Comment by mprevot** [comment]
@leecow @rbhanda @jamshedd @mairaw Any update about the VS-.net6 regression ?
