### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by jmrfd** [dotnet/core#6492]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file 'C:\myApp\obj\project.assets.json' doesn't have a target for 'net5.0'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. [C:\myApp\myApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by mairaw** [comment]
Can you let us know what `dotnet --info` returns and the contents of your myApp.csproj file?
