### ISSUE TITLE
'DISPLAY' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by AKHILMELATH** [dotnet/core#6495]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @AKHILMELATH. 
Not sure how you're getting that error message. dotnet is the name of the command, not display. Can you share some screenshots?
