### ISSUE TITLE
MyApp is not found

### ISSUE THREAD

**Issue by melomelo926** [dotnet/core#6498]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I follow the instruction and type in dotnet run in the terminal, but I get the error message below:

**Operating System Version:**

Big Sur Version 11.4

**Exact Error Message**
Couldn't find a project to run. Ensure a project exists in /Users/melodychui, or pass the path to the project using --project.

**Comment by mairaw** [comment]
Did you change your directory to your newly created project like we show in https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create? `cd myApp`

**Comment by melomelo926** [comment]
> Did you change your directory to your newly created project like we show in https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create? `cd myApp`

Thank you, Mairaw!  It works now.  But the time doesn't show up in the terminal even after I save the file many times.  I copy and paste in the code and save the file again, the time still doesn't show up.

**Comment by mairaw** [comment]
make sure you're saving and running from the same folder. Maybe share some screenshots of the file location and you running the command for us to see what's going on.

**Comment by melomelo926** [comment]
Hi Mariaw,

Thank you for your answer!!  I have another question.  If I cannot see the applications or the contents in the development, QA, and production environments, what impersonate user utilities I can use?  Is it a must to install SQL server management?

**Comment by mairaw** [comment]
Not sure if I understand the question @melomelo926. Do you have an ops person you can talk to in your company to see if they can grant you access? What kind of environment are you using for hosting your app? I'm also not exactly sure what exactly you're trying to access.
