### ISSUE TITLE
dear microsoft,i have big problem

### ISSUE THREAD

**Issue by temur1ka** [dotnet/core#6503]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Failed to load the dll from [C:\Program Files\dotnet\host\fxr\5.0.8\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\5.0.8\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by mairaw** [comment]
Hi @temur1ka, can you confirm what is your Windows version?
Depending on your version, you might need to install some additional dependencies:
https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#additional-deps
