### ISSUE TITLE
Stuck in spincube tutorial 

### ISSUE THREAD

**Issue by Rorosemaryfrann** [dotnet/core#6504]
Problem encountered on https://dotnet.microsoft.com/learn/games/unity-tutorial/modify
Operating System: windows
Im using unity and visual studio 

Im doing a tutorial and I cant seem to get past this one coding part, I keep trying but I cant seem to get the rotate amount to come up
This is what I have, where did I mess up? Im a beginner 

```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpinCube : MonoBehaviour
{
    public Vector3 RotateAmount;
    // Start is called before the first frame update
    void Start()
    {

        // Start is called before the first frame update
        void Start()
    {
        
    }

    // Update is called once per frame
    void Update(// Update is called once per frame
void Update()
{
            transform.Rotate(RotateAmount);
        }
)
    {
        
    }
}
```

**Comment by safern** [comment]
Thank you @Rorosemaryfrann for sharing you experience. @mairaw can you help here?

**Comment by mairaw** [comment]
Hi @Rorosemaryfrann!

I think there were some steps missed in the tutorial.

So the tutorial shows the initial script which should look like this:

```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpinCube : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update(
    {
    }
}
``` 

Then the additional steps tell you to add a public field and update the Update() method. So your final code should look something like this:

```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpinCube : MonoBehaviour
{
    public Vector3 RotateAmount;
    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update(
    {
        transform.Rotate(RotateAmount);
    }
}
``` 

Let me know if this works and if there's something we could change to make this more clear.
