### ISSUE TITLE
Error code 1 during build

### ISSUE THREAD

**Issue by olumideo** [dotnet/core#6506]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows
Editor used: VSCode

Everything worked until the step where the index.cshtml file was to be updated:
![image](https://user-images.githubusercontent.com/6344318/126959736-ed6c4e4e-cb61-4f1e-bb8a-db86d98bc952.png)

**Comment by mairaw** [comment]
@danroth27 any suggestions here?

**Comment by mairaw** [comment]
@olumideo can you share what are the build errors?
