### ISSUE TITLE
Error while deploying docker image into AKS cluster

### ISSUE THREAD

**Issue by Srikarjvgeico** [dotnet/core#6507]
HI Team,

I am getting below error in docker.yaml file while deploying docker image into AKS cluster.

**error: error parsing deploy.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key**

**Comment by safern** [comment]
Hello, @Srikarjvgeico thank you for reporting the issue. Would you mind sharing an example of your docker.yaml file? It seems like the YAML syntax is somehow wrong based on the error.
