### ISSUE TITLE
.NET Download Site Outage

### ISSUE THREAD

**Issue by richlander** [dotnet/core#6509]
## .NET Download Site Outage

The .NET download site -- download.visualstudio.microsoft.com -- is currently experiencing a partial outage. There are reports from users from around the world who are experiencing 404 responses when downloading .NET installers (`.msi`, `.tar.gz`, ...). This includes downloading the .NET SDK with the [.NET Core Task](https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer) in Azure DevOps. The problem appears to be with the content delivery network (CDN) that we use. We are working closely with our CDN team to resolve the issue.

We will continue to update this issue until it is resolved. We're sorry about the inconvenience that this outage has caused.

**Update at 6:40 PM PDT:** The outage appears resolved. Please share any continued download failures.

## Details

We [first saw this issue](https://github.com/jellyfin/jellyfin/pull/6338#issuecomment-885821344) on Friday morning (July 23) with an Azure DevOps instance in Europe. Since then, we have seen this issue in India and US regions as well.

With Azure DevOps, you will see an [error message](https://github.com/jellyfin/jellyfin/pull/6338/checks?check_run_id=3146818385) like the following:

```
Failed while installing version: 5.0.103 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/a2052604-de46-4cd4-8256-9bc222537d32/a798771950904eaf91c0c37c58f516e1/dotnet-sdk-5.0.103-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
```

We have seen similar reports for multiple .NET versions, including .NET 5 and .NET Core 3.1.

## Workaround

If you are having trouble downloading .NET installers to your local machine, you may try downloading using a VPN set to a different region. It appears that the issue is sensitive to the user region.

There is no workaround using Azure DevOps.

**Comment by mairaw** [comment]
Should we close this now @richlander?

**Comment by ycrumeyrolle** [comment]
download.visualstudio.microsoft.com is still down from Europe

**Comment by mairaw** [comment]
Let me check with the team. What are you trying to download just so we can have a repro?

**Comment by ycrumeyrolle** [comment]
Looks good now. 
I was trying to download http://download.visualstudio.microsoft.com/download/pr/acfc792d-506b-4868-9924-aeedc61ae654/0c9b1333f4e013af5cd3b7278e7d85a335d807467bec5ba9782f205af9f7e480/vs_Enterprise.exe 
From https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=enterprise&rel=16
