### ISSUE TITLE
dotnet command does not work

### ISSUE THREAD

**Issue by daniel2141locked2141outlook2141** [dotnet/core#6514]
Problem encountered on dotnet command
Operating System: windows 10
It said 'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mairaw** [comment]
What error are you getting @daniel2141locked2141outlook2141?

**Comment by daniel2141locked2141outlook2141** [comment]
The error says 'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by safern** [comment]
@daniel2141locked2141outlook2141 could you check if `dotnet.exe` is installed under `C:\Program Files\dotnet\`?

**Comment by daniel2141locked2141outlook2141** [comment]
I don’t have it!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by safern** [comment]
So that is the reason why you are getting that error. You will need to install the dotnet SDK, you can do that from: https://dotnet.microsoft.com/download

**Comment by mairaw** [comment]
The tutorial points to the correct download you should get. Take a look at that.
