### ISSUE TITLE
when try to install .net framwork on my ubuntu 20.04 i got this error! anyone can help me?

### ISSUE THREAD

**Issue by juliandivakaran** [dotnet/core#6516]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by safern** [comment]
Hello @juliandivagaran12, could you please share the error you got and as much details as possible?

**Comment by juliandivagaran12** [comment]
" 'dotnet' is not recognized as an internal or external command"
Sorry, I forgot to mention the problem. Now the problem is solved

**Comment by safern** [comment]
Thanks for confirming. Will close the issue.

**Comment by juliandivakaran** [comment]
Thanks for your support 🤝
