### ISSUE TITLE
can't install c# in command prompt

### ISSUE THREAD

**Issue by Khingss0209** [dotnet/core#6519]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

can't go anywhere from "dotnet new console -o myApp"
it will pop up red word said 
Creating this template will make changes to existing files:
  Overwrite   ./myApp.csproj
  Overwrite   ./Program.cs

Rerun the command and pass --force to accept and create.

how do I fix it??

**Comment by armin555** [comment]
It seems like you have already a Project created with the same name (or it created automatically). So you can just open that one, create one with another name instead or force to create a new one with same name by appending "--force" to the command.

**Comment by mairaw** [comment]
@armin555 is correct. You can also delete the existing folder and start over if you don't need that project. If you run the same command twice, it will give you that error message.

Were you able to continue?
