### ISSUE TITLE
Failed to load the dll

### ISSUE THREAD

**Issue by Yuriccs** [dotnet/core#6522]
Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\5.0.8\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\5.0.8\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by mairaw** [comment]
So did you install the prerequisites? What version of Windows are you using?

**Comment by Yuriccs** [comment]
hello, i hope you are doing well, i don't really know which windows version
i am using but i think it's the latest version.

**Comment by mairaw** [comment]
So is it Windows 10? If so, you should be able to type "This PC" on the search box and look at its properties

![image](https://user-images.githubusercontent.com/12971179/128245045-e0ca9ebc-96d3-478a-ad5e-6c7c89b9307b.png)

**Comment by Yuriccs** [comment]
Windows edition: Windows 10 pro

**Comment by adamsitnik** [comment]
@Yuriccs could you please do the following:

1. Open "Event Viewer" app (just press the Windows button and type "Event Viewer" and hit enter)
2. Go to "Windows Logs -> Application"
![obraz](https://user-images.githubusercontent.com/6011991/128305900-5fca57bb-ae23-4aaa-a805-ea135bae7065.png)
3. Reproduce the problem by trying to run the dotnet app
4. Go back to Event Viewer and hit F5 to refresh the logs.
5. Find the error and post the details here? You should see something similar to this:
![obraz](https://user-images.githubusercontent.com/6011991/128306087-8e7eaf0d-2ea5-4320-8aeb-d16d1ae09137.png)

**Comment by adamsitnik** [comment]
FWIW I've googled this error code and found [this](https://www.windowsphoneinfo.com/threads/error-code-0x800700c1.257850/)

> The error code 0x800700C1 occurs because the Windows Authenticode Signature Verification function now verifies portable executable (PE) files.

When we have more data we should be able to say if you are hitting similar issue.

**Comment by burnyourmom** [comment]
geez we have the same problem....

**Comment by adamsitnik** [comment]
@burnyourmom is there any chance you could provide the information that I've asked in https://github.com/dotnet/core/issues/6522#issuecomment-893217907 ?

**Comment by burnyourmom** [comment]
@adamsitnik I checked it, I did what you said but it didn't show an error in event viewer.

**Comment by Yuriccs** [comment]
still have the same problem even after watching hundreds of youtube videos
so i deleted vs code and installed visual studio code 2019 and it works
correctly

**Comment by adamsitnik** [comment]
> so i deleted vs code and installed visual studio code 2019 and it works
correctly

Thank you for letting us know that you were able to workaround the problem. I am going to close the issue and help @burnyourmom  in #6548
