### ISSUE TITLE
+ dotnet new blazorserver -o BlazorApp --no-https + ~~~~~~     + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

### ISSUE THREAD

**Issue by Yz274419** [dotnet/core#6524]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
I don't understand the symbols. Can you paste a screenshot of the error?
