### ISSUE TITLE
Error MSB4019: The imported project "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/xbuild/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found.

### ISSUE THREAD

**Issue by MuneebSaeed** [dotnet/core#6525]
<img width="573" alt="Screenshot 2021-08-01 at 4 20 55 PM" src="https://user-images.githubusercontent.com/27008579/127852408-19bca070-fff6-4acd-8af3-88f96af25455.png">
Please help me out!
Stuck with this error, no project is compiling. Even new solutions are not compiling.
 Everything was working fine i updated MacOS to 11.4 and now facing this issue.
Tried many solutions, updated VS to different versions along MonoFramework but nothing happened.
=== Visual Studio Community 2019 for Mac ===
                Version 8.1.4 (build 5)
                Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273) 
                Package version: 518010028
=== Mono Framework MDK ===
Runtime:
                Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
                Package version: 518010028

**/Users/ufoneappledeveloper/Projects/TestAppXamarin/iOS/TestAppXamarin.iOS.csproj(3,3): Error MSB4019: The imported project "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/xbuild/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. (MSB4019) (TestAppXamarin.iOS)**

**Comment by safern** [comment]
@akoeplinger do you know who should/can help with this issue?

**Comment by akoeplinger** [comment]
Mono 5.18 is very old, it shouldn't be used. Can you please try removing
- Mono (https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019#uninstall-mono-sdk-mdk)
- Xamarin.iOS (https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019#uninstall-xamarinios)

 and then reinstall via the Visual Studio for Mac installer from https://visualstudio.microsoft.com/en/vs/mac ?

**Comment by MuneebSaeed** [comment]
I have done all this, but end up with Plugins issue, some plugins in my project does not support on Mono 6x, so i have to use 5.18 in any case.

After reinstalling VS latest new projects are building with Mono 6x.

**Comment by adamsitnik** [comment]
> After reinstalling VS latest new projects are building with Mono 6x

Does it mean that the problem has been solved?

**Comment by akoeplinger** [comment]
You can't use Mono 5.18 with current Xamarin, that won't work.

**Comment by adamsitnik** [comment]
@akoeplinger @marek-safar could you please transfer this issue to https://github.com/mono/mono?

**Comment by akoeplinger** [comment]
I don't think there's much to transfer here, the issue is using an ancient mono.
