### ISSUE TITLE
I can't find the mentioned file

### ISSUE THREAD

**Issue by landreyS** [dotnet/core#6527]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by landreyS** [comment]
I can't find the mentioned file

**Comment by mairaw** [comment]
The file should be inside the new project directory called BlazorApp and then under Pages:
![image](https://user-images.githubusercontent.com/12971179/127920918-79361d78-bd15-44f6-8547-6ae3e180657c.png)

Does that solve your issue?
