### ISSUE TITLE
Add support for Debian 11 ("bullseye")

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6529]
This issue is created to track progress for the work to enable Debian 11 support for .NET Core 3.1 and .NET 5.0.

- [Debian 11 ("bullseye")](https://www.debian.org/releases/bullseye/)
- [Debian 11 ("bullseye") release announcement](https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html)
- [Debian releases](https://www.debian.org/releases/)
- [.NET 6 Bullseye support](https://github.com/dotnet/dotnet-docker/issues/2576)

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [ ] [CoreCLR/CoreFX] Runtime / RID Support update 
- [ ] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable) 
- [ ] [Infra] Replace docker tags used in builds across repos and branches
- [ ] [CLI team] Update CI legs to latest updated Dockerfile 
- [ ] [All teams] Update test infrastructure to support the new version
- [x] Acquisition] Add support within nightly repos
- [ ] Acquisition] Deploy to master (GA) during next patch release cycle

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [x] Follow up with infra and add feed for new OS release to packages.microsoft.com 
- [ ]  Update release manifest files 
- [ ] Create new Docker files to test the new OS
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by ashnaga** [comment]
Supported, resolving this one
