### ISSUE TITLE
i cant to the > dotnet

### ISSUE THREAD

**Issue by diamondyoutubxd3** [dotnet/core#6531]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

how do i do the > dotnet
[dotnet.txt](https://github.com/dotnet/core/files/6923311/dotnet.txt)

**Comment by ryank425** [comment]
You do not seem to have dotnet installed. Install the dotnet, and type dotnet in the terminal to verify that it is installed.

**Comment by mairaw** [comment]
You should just type `dotnet`. Did you install the SDK? If so, did you open a new command window after the installation?
