### ISSUE TITLE
just got started

### ISSUE THREAD

**Issue by Myckei-Myc** [dotnet/core#6533]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Screenshot (2)](https://user-images.githubusercontent.com/86807647/128121009-22d1ea81-ba1d-473c-9615-12b4e7dad6cd.png)
![Screenshot (11)](https://user-images.githubusercontent.com/86807647/128121096-18a57c3f-dcdb-4254-86d4-b80375a79d95.png)

**Comment by ryank425** [comment]
You have forgotten following steps, and it is indeed the case according to your second screenshot.

`cd myApp` in your terminal.

Your Program.cs resides in C:\Users\user\myapp, and you are trying to do 

`dotnet run`

in parent folder of myApp which would not likely have your csproj to start from.

**Comment by Myckei-Myc** [comment]
Thanks alot

**Comment by adamsitnik** [comment]
@ryank425 thank you for your help! since the question has been answered, I am closing the issue.
