### ISSUE TITLE
just started another blockstop

### ISSUE THREAD

**Issue by Myckei-Myc** [dotnet/core#6534]
![Screenshot (13)](https://user-images.githubusercontent.com/86807647/128122405-389dd898-ac23-4695-98fa-07802748c9e1.png)
![Screenshot (14)](https://user-images.githubusercontent.com/86807647/128122464-58c6a9df-c9fb-4470-baf7-2af3c754302e.png)
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by svick** [comment]
I think the problem is that the file is named Index.cshtml.cs, when it should be just Index.cshtml. With the .cs extension, the file is treated as a regular C# file, which is why you're seeing all those errors.

**Comment by mairaw** [comment]
Correct. Can you start over the tutorial and edit the .cshtml page and not the .cshtml.cs page?
