### ISSUE TITLE
Problem when trying to use dotnet

### ISSUE THREAD

**Issue by GYKgamer** [dotnet/core#6536]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

This is the 'dotnet' is not recognized as an internal or external command, operable program or batch file. problom I'm having

**Comment by adamsitnik** [comment]
Hi @GYKgamer 

Did you install the SDK? If so, did you open a new command window after the installation?

**Comment by GYKgamer** [comment]
I did install the sdk version I've restarted I've opened a new cmd windows yet nothing works

**Comment by adamsitnik** [comment]
Could you please check if dotnet.exe has been placed in `C:\Program Files\dotnet` or `C:\Program Files (x86)\dotnet`?

To do that you can run following command from cmd:

```cmd
DIR "C:\Program Files\dotnet\dotnet.exe"
DIR "C:\Program Files (x86)\dotnet\dotnet.exe"
```

If they exists, has the folder been added to `PATH`? You can print `PATH` by running the following command:

```cmd
echo %PATH%
```

**Comment by GYKgamer** [comment]
It doesnt exist on the PATH so should I add the folder as a system variable or user variable

**Comment by adamsitnik** [comment]
User variable should be fine. After you add it, please start a new terminal (environment variables on Windows are not refreshed after terminal is started)

**Comment by GYKgamer** [comment]
ok thanks

**Comment by GYKgamer** [comment]
Wait I just found out the dotnet.exe doesn't exist

**Comment by GYKgamer** [comment]
What should I do now?

**Comment by adamsitnik** [comment]
Could you try to re-install the SDK?

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/128192341-91e78fd1-71fc-438f-8880-2cd70499b85b.png)
i get this error even though it exists

**Comment by GYKgamer** [comment]
I can't uninstall it

**Comment by GYKgamer** [comment]
and deleting the folder would give me another error telling me I have insufficient permissions
So I am giving myself owner to the folder

**Comment by GYKgamer** [comment]
Tried that but still have the same error about the insufficient permissions

**Comment by adamsitnik** [comment]
I am sorry to hear that. I've run out of ideas, @NikolaMilosavljevic could you please help us?

**Comment by NikolaMilosavljevic** [comment]
I have no other suggestions to offer, @adamsitnik covered everything. @joeloff do you have any suggestions for repairing .NET SDK that were not tried before?

**Comment by GYKgamer** [comment]
jeez now a 3rd developer

**Comment by joeloff** [comment]
What does ```get-acl C:\programdata\Microsoft\NetFramework\BreadcrumbStore\ | Format-List``` tell you (run from powershell)? 

Can you provide the full install logs? That error will only be generated if there's an inconsistency between the directory ACLs and the user's permissions associated with the SID making the changes.

**Comment by GYKgamer** [comment]
Is the log from powershell or from like a file I should see?

**Comment by GYKgamer** [comment]
because i have lots of text from powershell

**Comment by joeloff** [comment]
The log from running the installer. It should get dropped into your %temp% folder. Typically it looks something like this: Microsoft_.NET_Core_SDK_3.1.412_(x64)_20210805002246.log

That's the primary log. There will be additional logs for each underlying MSI, but those will all start with the primary log filename as a prefix, e.g. Microsoft_.NET_Core_SDK_3.1.412_(x64)_20210805002246._X_Y_Z.msi.log

**Comment by GYKgamer** [comment]
[Microsoft_.NET_SDK_5.0.302_(x64)_20210804134634.log](https://github.com/dotnet/core/files/6936774/Microsoft_.NET_SDK_5.0.302_.x64._20210804134634.log)
[Microsoft_.NET_SDK_5.0.302_(x64)_20210804141427.log](https://github.com/dotnet/core/files/6936775/Microsoft_.NET_SDK_5.0.302_.x64._20210804141427.log)
[Microsoft_.NET_SDK_5.0.302_(x64)_20210804112205.log](https://github.com/dotnet/core/files/6936776/Microsoft_.NET_SDK_5.0.302_.x64._20210804112205.log)
[Microsoft_.NET_SDK_5.0.302_(x64)_20210804113830.log](https://github.com/dotnet/core/files/6936777/Microsoft_.NET_SDK_5.0.302_.x64._20210804113830.log)

And powershell says 
![image](https://user-images.githubusercontent.com/41442793/128309508-507e7c59-98a6-4571-bc28-245c888df801.png)

**Comment by joeloff** [comment]
Access permissions don't look right. Once you're elevated, ACLs on that Breadcrumbstore folder will likely fail since you'll be running under NT AUTHORITY\SYSTEM which doesn't have access.

So the MSI log we need to see is this one, or one with a similar looking timestamp:

Microsoft_.NET_SDK_5.0.302_(x64)_20210804113830_000_dotnet_runtime_5.0.8_win_x64.msi.log

I suspect it will just show the ACL error, Regardless of whether that folder exists, access controls are always set to ensure that has the proper security settings.

**Comment by GYKgamer** [comment]
[Microsoft_.NET_SDK_5.0.302_(x64)_20210804141427_000_dotnet_runtime_5.0.8_win_x64.msi.log](https://github.com/dotnet/core/files/6937163/Microsoft_.NET_SDK_5.0.302_.x64._20210804141427_000_dotnet_runtime_5.0.8_win_x64.msi.log)
here

**Comment by GYKgamer** [comment]
[Microsoft_.NET_SDK_5.0.302_(x64)_20210804113830_000_dotnet_runtime_5.0.8_win_x64.msi.log](https://github.com/dotnet/core/files/6937166/Microsoft_.NET_SDK_5.0.302_.x64._20210804113830_000_dotnet_runtime_5.0.8_win_x64.msi.log)
Heres the correct file the other one was wrong

**Comment by joeloff** [comment]
Logs confirm, the permissions configured on that folder is causing the problem

```Error 1303. The installer has insufficient privileges to access this directory: C:\ProgramData\Microsoft\NetFramework\BreadcrumbStore.  The installation cannot continue.  Log on as administrator or contact your system administrator.```

**Comment by GYKgamer** [comment]
Any fixes?

**Comment by joeloff** [comment]
Yes, fix the security changes applied to the folder. Based on what I'm seeing, folder ACLs were manually changed. 

- If there are no files in the breadcrumbstore you can try to just delete the folder and let the installer create it and ACL it correctly. 
- If there are files, you need to change it so that it looks like this

![image](https://user-images.githubusercontent.com/7409981/128394537-538f0766-6c01-495c-ba1c-94662bf4f5d2.png)

If you manually change permissions on system folders, then that's not something we can fix for you. The best I can do is tell you what the permissions should look like.

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/128403061-6718cbcf-7745-4a0e-872e-0d67a209c563.png)
it had no files but after i deleted it I got this error
(The error you said)

**Comment by joeloff** [comment]
ok, the only option I can think of then is to create the folder and then set the permissions to match what's in my previous screenshot

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/128420750-c5e59e58-379f-41de-a802-ab4d4b174f24.png)
i couldn't change the group but i changed the owner of the folder it but i still got an error saying
![image](https://user-images.githubusercontent.com/41442793/128420831-a96f819d-d189-4f4f-8678-e0d7452fdfd8.png)
even tho its created

**Comment by joeloff** [comment]
The accounts are not the right ones. From an admin powershell prompt, you can try the following 3 commands

```
$tempACL = New-Object -TypeName System.Security.AccessControl.DirectorySecurity
$tempACL.SetSecurityDescriptorSddlForm("O:SYG:SYD:P(A;OICI;CCDCSWWPLORC;;;WD)(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)")
set-acl -Path "C:\programdata\Microsoft\NetFramework\BreadcrumbStore\" -AclObject $tempACL
```
That may not fix everything because there are inheritance rules configured on that directory that transfer permissions and access rights to child objects (sub directories and files).

**Comment by GYKgamer** [comment]
I did this and it did fix the group section

**Comment by GYKgamer** [comment]
It finally finished the installation

**Comment by GYKgamer** [comment]
and dotnet works

**Comment by GYKgamer** [comment]
Thanks very much everything now works for me

**Comment by joeloff** [comment]
Glad it worked. Enjoy .NET
