### ISSUE TITLE
unknown shorthand flag: 'r' in -rm

### ISSUE THREAD

**Issue by jcdalton2201** [dotnet/core#6539]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

unknown shorthand flag: 'r' in -rm and 
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'MyMicroservice.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
Can you paste the exact command you're trying to run? The command on that page is a `docker` command, not `dotnet`. The error message seems to indicate the dotnet command was used instead. Maybe try using the copy button to make sure the right command was used. Let me know if I'm missing anything.
