### ISSUE TITLE
path-to-application:   The path to an application .dll file to execute.  C:\Users\Tawat>dotnet new console -o myApp Getting ready... The template "Console Application" was created successfully.  Processing post-creation actions... Running 'dotnet restore' on myApp\myApp.csproj...   Determining projects to restore...   Restored C:\Users\Tawat\myApp\myApp.csproj (in 90 ms). Restore succeeded.   C:\Users\Tawat>cd myApp

### ISSUE THREAD

**Issue by Kamntheph12** [dotnet/core#6543]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @Kamntheph12 

From the output that you have provided it seems that you were able to succefully create and restore the project. 
Could you please provide more infomation? What exactly does not work?
