### ISSUE TITLE
Aspnet core installation error on Cent OS7

### ISSUE THREAD

**Issue by rsg-roberth** [dotnet/core#6545]
I'm following the documentation https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos and I'm having an error installing on Cent OS 7.

There is indeed a problem with this walkthrough.

**Comment by mairaw** [comment]
@adegeo @leecow can you look at this?

**Comment by rsg-roberth** [comment]
![Error](https://user-images.githubusercontent.com/44393025/128766983-18ad9b2a-25a0-4849-a06c-437c616f4a75.jpg)

**Comment by adegeo** [comment]
Can you try again? The error indicates you can't talk to `mirrorlist.centos.org`. I just tried what it's trying to connect to and it worked fine for me: <http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock> Also, according to https://status.centos.org/ everything is working.

If you cant reach the centos website, you'll have to ask them for help :( sorry we can't be of more help here.

**Comment by rsg-roberth** [comment]
The error is actually in the certificate and following the documentation this could not happen, as the installation was performed sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

That is, this installation should solve this problem.

**Comment by rsg-roberth** [comment]
Estou na versão  7.6.1810, mas acredito que isso não seja o problema.

O que estou fazendo:

rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

sudo yum install aspnetcore-runtime-5.0

![Error](https://user-images.githubusercontent.com/44393025/128782182-2f7a3884-34a7-40ce-b452-d1c9da0dbb68.jpg)

**Comment by rsg-roberth** [comment]
@adegeo  I'm on version 7.6.1810, but I don't think that's the problem.

What am I doing:

rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

sudo yum install aspnetcore-runtime-5.0

I believe the problem is with the certificate. What should not happen, because step by step this command is intended to solve: rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
![Error](https://user-images.githubusercontent.com/44393025/128837740-80fbb2f8-ea50-40fb-8028-496ad10c7650.jpg)

**Comment by rsg-roberth** [comment]
The problem was in the machine/structure.

I had to change the ddns pointing to google and also to the machine's local ip.

I also changed the links from /etc/yum.repos.d/microsoft-prod.repo replacing https with http.

Thank you very much.
