### ISSUE TITLE
Creating a new .net app error

### ISSUE THREAD

**Issue by itsdragz** [dotnet/core#6547]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

When I was trying to create a new console, I ran into an error stating this (using the command `dotnet new console`
![image](https://user-images.githubusercontent.com/68898630/128858999-53a2ef5f-71d7-4989-8351-d8a68266198b.png)
My .NET is already downloaded
![image](https://user-images.githubusercontent.com/68898630/128859154-b353c4af-0cff-4244-a4ee-627cd71c03d4.png)
Here is the output when I input `dotnet --info`
![image](https://user-images.githubusercontent.com/68898630/128859533-7432d36c-dda7-4cda-a961-15ec858cdd8c.png)

I don't know what the issue is, if anyone could help that'll be greatly appreciated!

**Comment by adamsitnik** [comment]
Hi @itsdragz 

Have you installed .NET SDK or .NET Runtime?

![obraz](https://user-images.githubusercontent.com/6011991/128887918-1cf54bcc-a2c1-48e1-957e-176935d41e79.png)

**Comment by mairaw** [comment]
The tutorial links to the SDK @adamsitnik. This might be a duplicate of #5962 

@itsdragz can you post the results of running `dotnet --info` and `where.exe dotnet`

If your system is x64 and the x86 path returns first, you need to follow these steps to fix the issue:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by itsdragz** [comment]
Thank you!
