### ISSUE TITLE
Symbol packages for Core 1.1.2

### ISSUE THREAD

**Issue by mzji** [dotnet/core#655]
I can't find the download url of Core 1.1.2 symbol packages. Is there a plan to provide them?

**Comment by karelz** [comment]
@leecow @lt72 any advice?

**Comment by lt72** [comment]
@vancem: did we upload the 1.1.2 symbols to DLC and //symweb ?

**Comment by leecow** [comment]
I think @vancem was working on a solution for 2.0 Preview 1. I've added download links for 1.0.5 / 1.1.2 to the respective [download pages](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md).

**Comment by vancem** [comment]
@lt72 As Lee indicates I was only working with 2.0 Preview 2 and even then only for the Native PDBs (only needed for profiling).
