### ISSUE TITLE
Error Install botnet

### ISSUE THREAD

**Issue by GameOver61** [dotnet/core#6550]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.When installing dotnet, when I enter the commands to be installed, this error is seen at the end of the work. Can anyone help?

E: Couldn't find any package by glob 'dotnet-sdk-5.0'
E: Couldn't find any package by regex 'dotnet-sdk-5.0'

**Comment by adamsitnik** [comment]
Hi @GameOver61 

Which Linux distro are you using?
