### ISSUE TITLE
Issue with installing .Net 5.0.4

### ISSUE THREAD

**Issue by nbdinara** [dotnet/core#6556]
### Description

I am getting this error when I run commands bellow:
Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile 'dotnet-install.ps1'
Unblock-File 'dotnet-install.ps1'
.\dotnet-install.ps1 -Channel 5.0 -InstallDir 'C:\Program Files\dotnet'

![image](https://user-images.githubusercontent.com/35890180/128910272-87581566-7662-4e28-942a-c227cf916b82.png)

Link is not working. But this one works: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.10400/dotnet-sdk-5.0.104-win-x64.zip
Why this happening? Worked as expected few hours before. Did you change the link? 

Thank you!

### Other information

PS C:\> .\dotnet-install.ps1 -Channel 5.0 -InstallDir 'C:\Program Files\dotnet'
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.400/dotnet-sdk-5.0.400-win-x64.zip
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.400/dotnet-sdk-5.0.400-win-x64.zip is not available.
Could not find ".NET Core SDK" with version = 5.0.400
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At C:\dotnet-install.ps1:1143 char:9
+         throw "Could not find `"$assetName`" with version = $Specific ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find ".NET Core SDK" with version = 5.0.400
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Comment by rbhanda** [comment]
Hello,
Can you retry and let us know if you are still facing this issue?

**Comment by nbdinara** [comment]
Hello, it looks like that it is working now! Thank you!
It looks like that the installation process takes more time though. Can it be possible?
