### ISSUE TITLE
mywebapp cd commands

### ISSUE THREAD

**Issue by paulcastro1** [dotnet/core#6558]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @paulcastro1! Can you give us more details about the issues you're having?

**Comment by paulcastro1** [comment]
Do not close

**Comment by paulcastro1** [comment]
> ng?
hello i can not upload specific ios files on here
