### ISSUE TITLE
Problem with packages

### ISSUE THREAD

**Issue by kreely** [dotnet/core#6559]
Err:2 https://packages.microsoft.com/debian/10/prod buster Release                       
  404  Not Found [IP: 52.230.121.169 443]

/etc/apt/sources.list.d/microsoft-prod.list 

deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/10/prod buster main

Worked yesterday, seems to not be working today.

Reading package lists... Done                            
E: The repository 'https://packages.microsoft.com/debian/10/prod buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by elmerreal98** [comment]
I'm facing the same issue. An hour ago everything was working fine in my ci cd pipeline. :(

**Comment by edisnezir** [comment]
Same issue with https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

**Comment by hayden-corney** [comment]
Also https://packages.microsoft.com/ubuntu/20.04/prod/

```
Ign:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Err:6 https://packages.microsoft.com/ubuntu/20.04/prod focal Release
  404  Not Found [IP: 13.90.21.104 443]
...
Reading package lists...
E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal Release' no longer has a Release file.
```

**Comment by adegeo** [comment]
@rbhanda @leecow

**Comment by richlander** [comment]
Tracking issue: https://github.com/dotnet/core/issues/6560

**Comment by xTEddie** [comment]
My CI pipeline is failing because of this as well

**Comment by richlander** [comment]
I'm closing this one in favor of https://github.com/dotnet/core/issues/6560.

I'm sorry about the outage! We'll talk to our upstream team.
