### ISSUE TITLE
ASP.NET Core release page link not working

### ISSUE THREAD

**Issue by stanuku** [dotnet/core#656]
The "ASP.NET Core release page" link on https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.5.md is not working. It is pointing to https://github.com/aspnet/home/releases/1.0.5 and gives a 404.

**Comment by karelz** [comment]
@leecow @danroth27 1.0.5 does not exist on ASP.NET page: https://github.com/aspnet/home/releases
Is that expected?

**Comment by Petermarcu** [comment]
@danroth27 , I think you need to get a 1.0.5 release page up. Is that correct?

**Comment by leecow** [comment]
Looks like the ASP.NET Core 1.0.5 release tag is live.
