### ISSUE TITLE
packages.microsoft.com outage (including dotnet packages)

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6560]
Hello,
.NET Team is aware of an issue with packages.microsoft.com where several repositories seem to be broken.

Our teams are actively looking into this and will keep this issue updated. 

Update: This is a total outage with packages.microsoft.com and our upstream team is trying to recover all regions one by one.

**Comment by richlander** [comment]
The issue has been reported to the packages.microsoft.com team and we are actively working with them.

**Comment by richlander** [comment]
We are hearing that the west-us region should be back up but other regions are still failing.

**Comment by matt-richardson** [comment]
Would this error exhibit as 
```
Failed to connect to packages.microsoft.com port 443: Connection timed out
```
☝️ this is the error I'm facing.

"several repositories seem to be broken" might imply that it's not the same?

**Comment by rbhanda** [comment]
Update: This is a total outage with packages.microsoft.com and the team is recovering the regions one by one.

**Comment by richlander** [comment]
@matt-richardson ... you are (sadly) affected by this outage. That error messages matches.

**Comment by rbhanda** [comment]
Update: packages.microsoft.com team are driving towards a 5:30 PM (PST) ETA. As per them, West US is recovered and now they are in the process of recovering East US now

**Comment by rbhanda** [comment]
Update: 
•	West US region and East US region are recovered completely now 
•	All regions have at least 1 Mirror back up. Hence PMC should work now with degraded performance.

**Comment by rbhanda** [comment]
Hello,
We have the final update from packages.microsoft.com team. All the mirrors should be up with full capacity now.

**Comment by ravindrabhartiya** [comment]
Thanks for updates @rbhanda . Confirming we are back with full capacity worldwide.

**Comment by richlander** [comment]
Closing as this is now resolved.

**Comment by DennisSc** [comment]
Hello,

is it normal to get data dripping in at only 104 kByte/sec when trying to download .NET Core SDK 3.1 on ubuntu?


Get:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-host amd64 5.0.9-1 [52.6 kB]
Get:2 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-hostfxr-3.1 amd64 3.1.18-1 [121 kB]
Get:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-runtime-deps-3.1 amd64 3.1.18-1 [2682 B]
Get:4 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-runtime-3.1 amd64 3.1.18-1 [21.9 MB]
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 aspnetcore-runtime-3.1 amd64 3.1.18-1 [5771 kB]
Get:6 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-targeting-pack-3.1 amd64 3.1.0-1 [1988 kB]
Get:7 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 aspnetcore-targeting-pack-3.1 amd64 3.1.10-1 [1063 kB]
Get:8 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-apphost-pack-3.1 amd64 3.1.18-1 [41.9 kB]Get:9 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 netstandard-targeting-pack-2.1 amd64 2.1.0-1 [1476 kB]
Get:10 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-sdk-3.1 amd64 3.1.412-1 [48.4 MB]
Fetched 80.9 MB in 12min 54s (104 kB/s)

best regards

**Comment by sapountzis** [comment]
Err:1 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy/main amd64 azure-functions-core-tools-4 amd64 4.0.5801-1
  504  Gateway Time-out [IP: 13.107.246.40 443]
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod/pool/main/a/azure-functions-core-tools-4/azure-functions-core-tools-4_4.0.5801-1_amd64.deb  504  Gateway Time-out [IP: 13.107.246.40 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Service Unavailable

Our services aren't available right now
We're working to restore all services as soon as possible. Please check back soon.

20240609T153853Z-r1556b9bb4cjhw6gvb66prztbn0000000df0000000005cbg

**Comment by parrotrueper** [comment]
Seems it is down again:

`Err:8 https://packages.microsoft.com/repos/code stable InRelease                                                                                                                                           
  Cannot initiate the connection to packages.microsoft.com:443 (2620:1ec:bdf::64). - connect (101: Network is unreachable) Cannot initiate the connection to packages.microsoft.com:443 (2620:1ec:46::64). - connect (101: Network is unreachable) Could not connect to packages.microsoft.com:443 (13.107.246.64), connection timed out Could not connect to packages.microsoft.com:443 (13.107.213.64), connection timed out`
