### ISSUE TITLE
Issues after installing dotnet

### ISSUE THREAD

**Issue by NiftyRunner** [dotnet/core#6563]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

After installing dotnet I am facing the following issue.
![image](https://user-images.githubusercontent.com/87975379/128982558-bb07d749-c5d1-43f5-9cda-c90e67abd244.png)

**Comment by adamsitnik** [comment]
@NiftyRunner  could you post the results of running `dotnet --info` and `where.exe dotnet`?

If your system is x64 and the x86 path returns first, you need to follow these steps to fix the issue:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by NiftyRunner** [comment]
![image](https://user-images.githubusercontent.com/87975379/129564411-c4fffd7e-6ae3-442a-8a53-a3211ae042a9.png)
![image](https://user-images.githubusercontent.com/87975379/129564496-3cae3c76-d999-4d92-bcb1-47b892d849a4.png)

**Comment by NiftyRunner** [comment]
![image](https://user-images.githubusercontent.com/87975379/129564632-7540138e-76d2-4a0e-a19e-9bbbdccc0d2a.png)
![image](https://user-images.githubusercontent.com/87975379/129564705-f6e0e4bb-3a0d-4cd8-b273-59f0de6c304f.png)

**Comment by NiftyRunner** [comment]
@adamsitnik Thank You the problem is now solved
