### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ildambek** [dotnet/core#6566]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant

@ildambek could you please provide more details? What problem exactly are you hitting?
