### ISSUE TITLE
What's new in .NET 6 RC2 [WIP]

### ISSUE THREAD

**Issue by leecow** [dotnet/core#6570]
# What's new in .NET 6 RC2

This issue is for teams to highlight work for the community that will release .NET 6 RC2

To add content, use a new conversation entry. The entry should include the team name and feature title as the first line as shown in the template below. 

```
## Team Name: Feature title

[link to the tracking issue or epic item for the work]

Tell the story of the feature and anything the community should pay particular attention 
to be successful using the feature.
```
Preview 1: https://github.com/dotnet/core/issues/5853
Preview 2: https://github.com/dotnet/core/issues/5889
Preview 3: https://github.com/dotnet/core/issues/5890
Preview 4: https://github.com/dotnet/core/issues/6098
Preview 5: https://github.com/dotnet/core/issues/6099
Preview 6: https://github.com/dotnet/core/issues/6325
Preview 7: https://github.com/dotnet/core/issues/6444
RC1: https://github.com/dotnet/core/issues/6569

**Comment by jkotas** [comment]
.NET 6 RC2 has API breaking changes. For example, the APIs for Json source generators have changed (#59042). The binaries compiled against .NET 6 RC1 are not supported on .NET 6 RC2.

**Comment by karelz** [comment]
We added API on `System.Net.Uri` (new constructor overloads and `UriCreationOptions`) to enable customers process Uris transparently, without normalization/canonicalization of path and query - https://github.com/dotnet/runtime/pull/59173

**Comment by karelz** [comment]
.NET 6 RC2 brings WinHttpHandler support for TLS 1.3 on Windows 11 - https://github.com/dotnet/runtime/issues/58587

**Comment by layomia** [comment]
> .NET 6 RC2 has API breaking changes. For example, the APIs for Json source generators have changed (dotnet/runtime#59042). The binaries compiled against .NET 6 RC1 are not supported on .NET 6 RC2.

For additional info on the motivation and mitigation for the JSON src-gen changes, see the breaking change doc - https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/6.0/json-source-gen-api-refactor?branch=pr-en-us-26222 and original issue https://github.com/dotnet/docs/issues/26200.
