### ISSUE TITLE
Couldn't find a project to run. Ensure a project exists in D:\Blazor\WebServerApplication1, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by sharvari257** [dotnet/core#6572]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @sharvari257 

Could you please list the content of `D:\Blazor\WebServerApplication1` ?

**Comment by adamsitnik** [comment]
For some reason your folder does not contain project file (should be  `webserverapplication1csproj` in your case). Could you please try to create a new solution and start from scratch?

**Comment by sharvari257** [comment]
Sure, I will do that.
Thanks for your help btw.

**Comment by mairaw** [comment]
Did starting over work?

**Comment by sharvari257** [comment]
Yes, it worked.
Thanks for your help.
