### ISSUE TITLE
executing gunthy-macos error

### ISSUE THREAD

**Issue by luisao8788** [dotnet/core#6578]
Hi I´m just having the error below when executing the gunthy-macos in my mac to start gunbot. I can not neither open localhost:5000 because I don´t know where to add the port 5000 to my mac to allow traffic in trough this port. 

the error when i execute the gunthy-macos is the following: 

luisramirez@MacBook-Pro-de-Luis ~ % /Users/luisramirez/OneDrive/Documentos/BTC/gunbot/gunthy_macos/gunthy-macos ; exit;
Error: Cannot find module '/snapshot/enricoranucci/Desktop/STABLE/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node'
Require stack:
- /snapshot/enricoranucci/Desktop/STABLE/node_modules/sqlite3/lib/sqlite3-binding.js
- /snapshot/enricoranucci/Desktop/STABLE/node_modules/sqlite3/lib/sqlite3.js
- /snapshot/enricoranucci/Desktop/STABLE/gui/index.js
- /snapshot/enricoranucci/Desktop/STABLE/bot.gunbot.js
- /snapshot/enricoranucci/Desktop/STABLE/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1027:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/snapshot/enricoranucci/Desktop/STABLE/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/enricoranucci/Desktop/STABLE/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/snapshot/enricoranucci/Desktop/STABLE/node_modules/sqlite3/lib/sqlite3.js',
    '/snapshot/enricoranucci/Desktop/STABLE/gui/index.js',
    '/snapshot/enricoranucci/Desktop/STABLE/bot.gunbot.js',
    '/snapshot/enricoranucci/Desktop/STABLE/index.js'
  ],
  pkg: true
} Uncaught Exception thrown

can you please help on this? 

thanks and Regards, 

Luis R

**Comment by adamsitnik** [comment]
Hi @luisao8788 

From the stacktrace that you have provided it seems that this particular product is implemented in Javascript, not in .NET. I am afraid we won't be able to help you.

Thanks,
Adam

**Comment by mairaw** [comment]
How does this relate to .NET @luisao8788?
