### ISSUE TITLE
System.Drawing.Common is not supported on non-Windows platforms

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/core#6584]
System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered() in System.Drawing.Common.dll:token 0x600058c+0x11
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize() in System.Drawing.Common.dll:token 0x6000b00+0x0
   at System.Drawing.SafeNativeMethods.Gdip..cctor() in System.Drawing.Common.dll:token 0x6000af8+0x2b

https://aka.ms/systemdrawingnonwindows  can't be open,How to solve this problem

**Comment by svick** [comment]
The exception message is correct: System.Drawing.Common is no longer supported on .Net 6 on Linux and macOS. For more information, see [this document](https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md) and https://github.com/dotnet/docs/issues/25257.

As that document states, if you want to continue using it on .Net 6, you can provide a [runtime config switch](https://docs.microsoft.com/dotnet/core/run-time-config/) named `System.Drawing.EnableUnixSupport` set to `true`. But even this will not work starting with .Net 7.

As for the aka.ms link, I'm not sure. Maybe it will be set up once this breaking change is properly documented (i.e. when https://github.com/dotnet/docs/pull/25367 is merged).

**Comment by mairaw** [comment]
It seems @svick has answered your question, so I’m closing this issue. Let me know if I missed anything.

**Comment by mairaw** [comment]
Reopening since the link goes to our internal tool somehow.
Tagging @ericstj @danmoseley @terrajobst @safern who seem to own that link.

**Comment by safern** [comment]
> Tagging @ericstj @danmoseley @terrajobst @safern who seem to own that link.

I'll work with @gewarren to post the doc ASAP on Monday and point the url to the doc.

**Comment by gewarren** [comment]
@safern Here is the PR; it's ready for review: https://github.com/dotnet/docs/pull/25367

**Comment by safern** [comment]
aka.ms/systemdrawingnonwindows should now resolve to the published docs. Thanks for the report.

**Comment by janseris** [comment]
What is the solution for this for developers? I have a server application running on Linux and I need to know what replaces System.Drawing for .NET 6 and later. I read in the documentatino that

> recommended alternatives include [ImageSharp](https://github.com/SixLabors/ImageSharp), [SkiaSharp](https://github.com/mono/SkiaSharp), [Windows Imaging Components](https://docs.microsoft.com/en-us/windows/desktop/wic/-wic-about-windows-imaging-codec), and [Microsoft.Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics).


So now developers will use multiple libraries and .NET will have no standard image manipulation API at all?
Which one of these is the right one?
So now when people will want to learn .NET image manipulation, there will be package-specific tutorials and all over time, support for these packages might drop etc? MAUI support might not be dropped but instead, it is a UI library so depending on MAUI on an ASP.NET server application is ridiculious.
What is the only suggested solution?

Thanks

**Comment by danmoseley** [comment]
@mattleibow can you confirm that SkiaSharp is fully supported by Microsoft?

Also, I have generally thought of SkiaSharp as client focused, and something like ImageSharp better for servers. Is it reasonable to use SkiaSharp on the server side? I know that unlike ImageSharp, it has some native dependencies.

**Comment by siddjain** [comment]
I am using `System.Drawing.Common` on Mac OS but with target framework 6.0 and have set 

```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
"configProperties": {
      "System.Drawing.EnableUnixSupport": true
   }
  }
}
```

but still seeing this exception:

```
Unhandled exception. System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.
   at System.Drawing.SystemFonts.get_DefaultFont()
```

can anyone help please?

**Comment by gewarren** [comment]
@siddjain Which file are those settings from?

**Comment by siddjain** [comment]
the settings are from `myapplication.runtimeconfig.json` under `bin/Debug/net6.0-windows` of the project root. I am trying to run the application from the project root using `dotnet run`. Thanks for your help.

**Comment by gewarren** [comment]
What does your project file look like? I'm surprised the output folder is net6.0-windows on macOS.

**Comment by siddjain** [comment]
its because I have set it so. setting it to `net6.0-macos` gave me another set of issues. here is the csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MyApp</RootNamespace>
    <AssemblyName>MyApp</AssemblyName>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>
</Project>
```

**Comment by gewarren** [comment]
Looks like you're using the 7.0 version of System.Drawing.Common. Does it work if you set that to 6.0.0?

**Comment by siddjain** [comment]
no it still doesn't work

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, String systemName)
   at System.Drawing.SystemFonts.get_DefaultFont()
```

**Comment by siddjain** [comment]
made some changes and that error is fixed but I get a new one now:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 0x0001): tried: 'liblibgdiplus' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibgdiplus' (no such file), '/usr/lib/liblibgdiplus' (no such file, not in dyld cache), 'liblibgdiplus' (no such file), '/usr/local/lib/liblibgdiplus' (no such file), '/usr/lib/liblibgdiplus' (no such file, not in dyld cache)
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
```

how do I fix this one?

**Comment by safern** [comment]
@siddjain for that specific error you need to make sure that `libgdiplus` is installed in your OS. 

https://www.mono-project.com/docs/gui/libgdiplus/

In Unix systems you can do it by running `sudo apt-get install libgdiplus` or whatever is the package manager for that OS.

on mac systems you need to run `brew install mono-libgddiplus`

**Comment by danmoseley** [comment]
@mattleibow just checking you saw my question above as it would be good to know the answer.
