### ISSUE TITLE
Issue on Edit You Code Section Of Tutorial

### ISSUE THREAD

**Issue by korahx64** [dotnet/core#6586]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

After updating the Pages/Index.cshtml from (A) to (B) - I got (C) Errors in the command line.
### ( A ) 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

### ( B ) 

@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>

### ( C )
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(4,13): error CS1002: ; expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(4,14): error CS1001: Identifier expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,6): error CS1002: ; expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1001: Identifier expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1514: { expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1513: } expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(8,14): error CS1002: ; expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(9,12): error CS1002: ; expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]
C:\Users\Anothony Mitchell\myWebApp\Pages\Index.cshtml.cs(10,7): error CS1002: ; expected [C:\Users\Anothony Mitchell\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...
watch : Shutdown requested. Press Ctrl+C again to force exit.

**Comment by svick** [comment]
@korahx64 You have updated the Index.cshtml.cs file, not the Index.cshtml file. Can you try again from the start, while making sure you edit the correct file?

@mairaw This mistake seems to happen fairly frequently. Would it make sense to update the tutorial to something like the following?

> Open `Pages/Index.cshtml` (not `Pages/Index.cshtml.cs`) in any text editor and replace all of the code with the following, then save the file.

I couldn't find the code of the tutorial on GitHub, otherwise I would submit a PR.

**Comment by mairaw** [comment]
Yes, I’m aware. I need to update it to mention the hidden file extensions in Windows.

**Comment by mairaw** [comment]
Closing since we no longer have this tutorial on the site. The current main one for ASP.NET Core uses Blazor and Visual Studio, so the extension issue no longer applies.
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro
