### ISSUE TITLE
Skyrim modding DepotDownloader.bat not working even with every step taken

### ISSUE THREAD

**Issue by Wolfknight9** [dotnet/core#6588]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. DepotDownloader.bat is still saying its not an internal or external file on the Win+r menu. I need help so I can continue to try and fix my mods on skyrim

**Comment by adamsitnik** [comment]
Hi @Wolfknight9 

What is `DepotDownloader.bat` and how is it related to .NET Core?

**Comment by mairaw** [comment]
Also, if you can paste what's the error message that you're getting.
