### ISSUE TITLE
VS Website cannot be reached

### ISSUE THREAD

**Issue by DjSloth** [dotnet/core#659]
[https://www.visualstudio.com/vs/preview/](https://www.visualstudio.com/vs/preview/)

can't tinker with .net core 2.0, cause it needs the new VS preview, unfortunately the website cannot be reached

**Comment by svick** [comment]
That link works fine for me. Does it work for you now? If not, what exactly is the error you're getting?

**Comment by leecow** [comment]
Confirmed I can reach the site as well.

**Comment by Petermarcu** [comment]
It also works for me. I'm going to close. Please reopen if its still a problem.
