### ISSUE TITLE
Unable to sign console apps in macOS with .net 6 preview 7

### ISSUE THREAD

**Issue by abelsayed** [dotnet/core#6591]
### Issue title
Unable to sign published single app executable in macOS using .net 6 preview 7
### OS
macOS 12 beta 4 running on Apple Silicon
macOS 11.5.2 running on Intel processor
macOS 10.15 (using Azure DevOps image)
### .NET Version
.NET SDK 6.0.100-preview.7.21379.14

### Issue Details
After publishing a console application using `dotnet publish` and generating a single file, whenever I try to sign the app; I'm getting this error
> arm64/HelloWorld: replacing existing signature
arm64/HelloWorld: internal error in Code Signing subsystem

In Azure DevOps pipeline, I'm getting this error
> /Users/runner/work/1/b/temp/files/testApp: replacing existing signature
/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /Users/runner/work/1/b/temp/files/testApp malformed object (code signature data at offset 84976 with a size of 18944, overlaps string table at offset 79844 with a size of 74050467)
/Users/runner/work/1/b/temp/files/testApp: the codesign_allocate helper tool cannot be found or used

**_When reverting back to .net 6 preview 6 (6.0.100-preview.6.21355.2), signing a published single file app is working as expected._**

### Repro steps
1. Create a console app using this command
```
dotnet new console
```
2. Publish the app
```
dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true -r osx-x64 -o output
```
3. Codesign the published app
```
codesign --verbose --timestamp --sign [identity] output/HelloWorld --force --options=runtime --no-strict
```

When running `codesign -dv --verbose=4 $temp/files/testApp` after publishing the app I'm noticing it's already signed (sort of) and this is the output of that command

> xecutable=/Users/runner/work/1/b/temp/files/testApp
Identifier=apphost-555549442cbd6afe0dd237308358b9254dccc678
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=833 flags=0x2(adhoc) hashes=21+2 location=embedded
VersionPlatform=1
VersionMin=658688
VersionSDK=658688
Hash type=sha256 size=32
CandidateCDHash sha256=416f85ea39932855071184cfcdc8610012f4375e
CandidateCDHashFull sha256=416f85ea39932855071184cfcdc8610012f4375e9247fc8cdb79bb4d65f94dc4
Hash choices=sha256
CMSDigest=416f85ea39932855071184cfcdc8610012f4375e9247fc8cdb79bb4d65f94dc4
CMSDigestType=2
Page size=4096
CDHash=416f85ea39932855071184cfcdc8610012f4375e
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12

**Comment by adamsitnik** [comment]
@wli3 @dsplaisted could you please take a look?

**Comment by dsplaisted** [comment]
The .NET SDK now codesigns by default: https://github.com/dotnet/sdk/pull/18216

You can set `_EnableMacOSCodeSign` to false to opt out.

@mateoatr @vitek-karas Is the experience described here expected?

**Comment by mateoatr** [comment]
Hi. Thanks for reporting this. We are already tracking the issue in https://github.com/dotnet/runtime/issues/57242 and working on a fix. Closing this as dup.
