### ISSUE TITLE
Document: to declare the support timeline schedular

### ISSUE THREAD

**Issue by cnmade** [dotnet/core#6592]
Hello, would you please provide us the .net support timeline as detail as possible.
like Ubuntu release table

![image](https://user-images.githubusercontent.com/278153/129537356-53ab5419-d1e4-49e0-837a-df76665f7590.png)

**Comment by adamsitnik** [comment]
Hi @cnmade 

Does https://dotnet.microsoft.com/platform/support/policy/dotnet-core answer your question?

**Comment by cnmade** [comment]
Yes, looks forward .net 6, .net 7, .net 8 road map. any detail plan for that ? i can see the table for .net 5.

and https://github.com/dotnet/core/blob/main/releases.md  these page should update the same?

**Comment by adamsitnik** [comment]
> Yes, looks forward .net 6, .net 7, .net 8 road map. any detail plan for that ? i can see the table for .net 5.

@richlander could you please answer this question?

**Comment by richlander** [comment]
Yes, the [releases.md](https://github.com/dotnet/core/blob/main/releases.md) file is a good place to look. It includes .NET 6. We don't include releases we haven't started yet, which seems to match the Ubuntu table you shared.

That said, the future plan will be:

- Current release (like .NET 7), supported for 18 months.
- LTS release (like .NET 8), supported for 3 years.

Our plan is to continue repeating out that model forever. You could write a program that writes the rest of the table for you, as many years as you want to go out.
