### ISSUE TITLE
Couldnt Build Docker image

### ISSUE THREAD

**Issue by Zadera85** [dotnet/core#6598]
![DockerError](https://user-images.githubusercontent.com/40142385/129673394-78d612ec-1810-4a48-993a-91ae928380a8.JPG)
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Please see attached image. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you show the contents of that folder and what it's in your Dockerfile?

**Comment by Rits333** [comment]
try this 
**docker build -t imagename:version_number  .  **
and once shared the dockerfile image
