### ISSUE TITLE
program.cs

### ISSUE THREAD

**Issue by jmegill62** [dotnet/core#6599]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

MicrosoftWindows 10
Acccess is Denied is the error message
C:\Users\John\myApp>program.cs
Access is denied.

**Comment by mairaw** [comment]
The command to run the app is `dotnet run`. Try that and let us know if that works.

**Comment by jmegill62** [comment]
> The command to run the app is `dotnet run`. Try that and let us know if that works.

Yes that worked.  Although I had to try it a few times but it finally registered.  Thankyou for your help.

**Comment by mairaw** [comment]
Great to hear.
