### ISSUE TITLE
string interpolation and dynamic object property

### ISSUE THREAD

**Issue by km-hussain-in** [dotnet/core#6601]
This code 

dynamic t = DateTime.Now;
Console.WriteLine($"Day = {t.Day}");

causes following exception

Unhandled exception. System.TypeLoadException: The generic type '<>A{00000002}`3' was used with an invalid instantiation in assembly 'Hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Work around
Replace
Console.WriteLine($"Day = {t.Day}");
by
Console.WriteLine("Day = {0}", t.Day);

**Comment by MihaZupan** [comment]
Hi. This is a bug in the Roslyn compiler for 6.0 when using the improved interpolated strings together with dynamic.
It is tracked by https://github.com/dotnet/roslyn/issues/55609.
