### ISSUE TITLE
Interpolated strings are garbled when concatenated

### ISSUE THREAD

**Issue by Silvertower** [dotnet/core#6603]
### Description

When concatenating multiple interpolated strings in .NET 6.0 preview 7, the resulting text is garbled.

Example code to reproduce:

```
using System;

string Name = "Bob";
string Article = "the";
string Direction = "north";

Console.WriteLine(
  $"{Name} arrives from " +
  $"{Article} " +
  $"{Direction}.");
```

Expected output:

```
Bob arrives from the north.
```

Actual output:

```
 arrives from Bob the.north
```

### Configuration

.NET 6.0 preview 7
Windows 10 21H1
x64

### Regression?

The example code above works as expected in .NET 5.0.

### Other information

No error messages; just unexpected behavior.

**Comment by MihaZupan** [comment]
Hi, this is a Roslyn bug that will be fixed in  .NET 6 RC 1, see https://github.com/dotnet/roslyn/issues/55493#issuecomment-895527098
