### ISSUE TITLE
Issue with "create your app" step

### ISSUE THREAD

**Issue by raband-cdw** [dotnet/core#6609]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Running through the steps on my windows 10 machine with the "dotnet-sdk-5.0.400-win-x64" install files the first step worked as outlined, but the newconsole cmd didn't.

C:\Users\user1>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\user1>dotnet new console -o myApp
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
@raband-cdw You might be running into this issue: #5962

Can you let us know what is the output of `where.exe dotnet`?

**Comment by raband-cdw** [comment]
![image](https://user-images.githubusercontent.com/62358395/130118364-3e04c5d2-9e57-4c33-92dc-f6da23df3302.png)

**Comment by mairaw** [comment]
It looks like you have both x86 and x64 versions installed. Fixing the path should fix your problem as outlined in https://github.com/dotnet/core/issues/5962#issuecomment-780084535

Let us know if that worked!

**Comment by raband-cdw** [comment]
That did it thanks!

**Comment by mairaw** [comment]
Great to hear!
