### ISSUE TITLE
Aspnet Core 1.1.0 does not properly add forwardWindowsAuthToken="true" to web.config when deploying

### ISSUE THREAD

**Issue by mackayj** [dotnet/core#661]
I noticed that when publishing my new Aspnet Core 1.1 (just updated to VS 2017) project it is always missing the forwardWindowsAuthToken="true" from the web.config.

More info and the fix I found was here:

https://developercommunity.visualstudio.com/content/problem/26751/publish-aspnet-core-to-iis-with-windows-authentica.html

I also tried adding:

services.Configure<IISOptions>(options => { options.ForwardWindowsAuthentication = true; });

to my ConfigureServices method but it didn't help.

So my question is, is there a way to get this to work properly? Some command line argument or other way to automate it other than having to manually edit the web.config after it has been deployed?

I don't think it matters, but this is a asp.net core 1.1 targeting 4.6.2 not core.

http://stackoverflow.com/questions/44057005/aspnet-core-1-1-missing-windows-authentication-when-published

Since we have the deploy automated its annoying to have to manually edit the web.config file, is it possible to automate that? Is it a known issue? Our older 1.0 core projects do properly add forwardWindowsAuthToken="true" in the web.config.

**Comment by Petermarcu** [comment]
@Eilon @DamianEdwards

**Comment by Eilon** [comment]
@Tratcher - any idea where this issue should go?

**Comment by Tratcher** [comment]
https://github.com/aspnet/aspnetcoremodule
@shirhatti 
Note that forwardWindowsAuthToken's default value was changed to true so most apps no longer need it in the web.config.

**Comment by mackayj** [comment]
@Tratcher when was it changed? In the 1.1 version with VS 2017 I have to manually set it in the web.config or it doesn't authenticate properly.

For example deploying the default project will show:

"Hello, !" in the top right where its supposed to show the username, with anon, asp.net impersonation, forms disabled and windows auth enabled in IIS

**Comment by Tratcher** [comment]
I'll defer to @shirhatti and @BillHiebert.

**Comment by shirhatti** [comment]
This issue was moved to aspnet/AspNetCoreModule#104
