### ISSUE TITLE
The console window displays garbled characters when type "dotnet --info"

### ISSUE THREAD

**Issue by quanljh** [dotnet/core#6614]
### Description

When type "dotnet --info" in console window, it displays garbled characters in the output information. My computer language is Japanese.

### Configuration

You can find my configuration in the attachment
![image](https://user-images.githubusercontent.com/38105306/130189697-7cf34b82-043c-4158-87d2-ed344593b4d4.png)

![image](https://user-images.githubusercontent.com/38105306/130189853-b7f8f02e-437e-4af7-8058-13528b9411c8.png)

**Comment by MihaZupan** [comment]
cc: @wli3 @dsplaisted

**Comment by dsplaisted** [comment]
This seems like a code page issue with the console.  Do any console programs correctly display Japanese characters?

**Comment by quanljh** [comment]
No, console program also displays ??. 
![image](https://user-images.githubusercontent.com/38105306/130307329-b4c27534-c5f8-45fb-88e8-5dd95d3f9742.png)

**Comment by quanljh** [comment]
This issue was solved, for more info please see https://github.com/dotnet/sdk/issues/19996
