### ISSUE TITLE
Add support for Windows 11

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6628]
This issue is created to track progress for the work to enable Windows 11 support for .NET Core 3.1 and .NET 5.

> Supported Architectures: x86, x64, and Arm64. Also add support for x64 emulation on Arm64

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [ ] [CoreCLR/CoreFX] Runtime / RID Support update
~- [ ] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable)~
~- [ ] [Infra] Replace docker tags used in builds across repos and branches~
~- [ ] [CLI team] Update CI legs to latest updated Dockerfile~
- [ ] [All teams] Update test infrastructure to support the new version
~- [ ] [Acquisition] Add support within nightly repos~
~- [ ] [Acquisition] Deploy to master (GA) during next patch release cycle~

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [ ]  Update release manifest files 
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by mthalman** [comment]
Windows Docker images are only being provided for Windows Server, not Windows client.  So I'm removing the Docker-related tasks.

**Comment by richlander** [comment]
Please clarify (for this and other similar "Add support" issues) that we need to add support for x86, x64, and Arm64. In this particular case, we also need to support x64 emulation on Arm64. So, that's four architectural scenarios.

**Comment by ianjoneill** [comment]
I take it this ticket indicates why my Windows 11 machine didn't get a .NET Core update via Windows Update yesterday (2021-10-12), but my Windows 10 machine did when manually checking for updates?

**Comment by richlander** [comment]
There are many such issues open. What is our policy on them?

https://github.com/dotnet/core/labels/os-support

**Comment by ashnaga** [comment]
Supported, resolving this one.
