### ISSUE TITLE
Add support for Windows Server 2022

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6629]
This issue is created to track progress for the work to enable Windows Server 2022 (Architecture: X64 only) support for .NET Core 3.1 and .NET 5.

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [ ] [CoreCLR/CoreFX] Runtime / RID Support update
- [ ] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable)
- [ ] [Infra] Replace docker tags used in builds across repos and branches
- [ ] [CLI team] Update CI legs to latest updated Dockerfile 
- [ ] [All teams] Update test infrastructure to support the new version
- [x] [Acquisition] Add support within nightly repos 
- [x] [Acquisition] Deploy to master (GA) during next patch release cycle        

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [ ]  Update release manifest files 
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by ashnaga** [comment]
Supported. Resolving.
