### ISSUE TITLE
 dotnet new --install Reactor.Template

### ISSUE THREAD

**Issue by hellogutssss** [dotnet/core#6637]
dotnet new --install Reactor.Template
라 했는데 왜 이렇게 나오죠? .NET SDK 깔았는데

Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by ryank425** [comment]
Please make sure that you have .NET SDK installed on your machine. 

NET Core 3.1  or NET 5 would work.
https://dotnet.microsoft.com/download

**Comment by mairaw** [comment]
@hellogutssss are you on a Windows machine? If so, can you let us know what's the output of `where.exe dotnet`?
