### ISSUE TITLE
.Net WebClient.DownloadData api result in different behavior in some kind of project

### ISSUE THREAD

**Issue by treeicnliu** [dotnet/core#664]
I got different http packages by fiddler4 when i call the same fucntion WebClient.DownloadData(string uri) api with the same param uri on web proj and console proj.

I found that webclient will auto decode uri in web proj,and keep the origin uri in console proj.

is it a .net issue ? 

The uri below can't access,but it can be used for test

http://objstore.qa.nt.ctripcorp.com/smartemailstorage/2017%5C4%5C6%5Cf809530b-0ded-49b4-8532-002c7ad73b41%5C%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C.pdf?AWSAccessKeyId=D1NNJCXLEF0O7JIB2U3L&Expires=1511426288&Signature=iJjQCreO6F7avac86Tg2S4e4Miw%3D

**Comment by karelz** [comment]
Do both of your projects use the same .NET Core 2.0-preview1 version?
The class is in `System.Net` namespace, if you still have troubles, please file it in CoreFX repo.

**Comment by richlander** [comment]
@treeicnliu can you share the before and after of the return value in both cases. 

Can you share how this property is set in both cases? https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.encoding?view=netcore-2.0#System_Net_WebClient_Encoding

**Comment by richlander** [comment]
@treeicnliu can you share a repro? I'm not quite sure what to test based on your description.

**Comment by treeicnliu** [comment]
[test.docx](https://github.com/dotnet/core/files/1217516/test.docx)

@richlander , i want to dowdload data from the url(with fixed signature) in .net web proj ,it doesn't work since the url has changed(broke the signature),but worked in console proj.  see the file test.docx i uploaded.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24477](https://github.com/dotnet/corefx/issues/24477) via [**ZenHub**](https://www.zenhub.com/)
