### ISSUE TITLE
Problem with .net

### ISSUE THREAD

**Issue by Maechto** [dotnet/core#6646]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

So I downloaded the .net core SDK, also tried many different versions, but when I type  --list-sdks it says ´´Der Befehl "--list-sdks" ist entweder falsch geschrieben oder konnte nicht gefunden werden.´´(this is in german). I also tried it in vs code and it didnt work either. Also nothing worked with .net as it should in vscode. but when I tried it with the x86 version it worked in vscode. But I couldnt program because it said debugging only works with x64. I have no clue how to get around this problem!?!?!

**Comment by Anipik** [comment]
you need to do dotnet --list-sdks, also verify if the dotnet path is present in your environment variables.

**Comment by mairaw** [comment]
You might be running into the same issue as #5962. Can you let us know what's the output of `where.exe dotnet`?

**Comment by Maechto** [comment]
its this: C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

**Comment by mairaw** [comment]
So try following the steps I laid out at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 and let us know if that solved your issue (I’m assuming you have a x64 Windows - let me know if you don’t)
