### ISSUE TITLE
Symbol package for Core 2.0.0 preview 1

### ISSUE THREAD

**Issue by mzji** [dotnet/core#665]
Where could I download the symbol package for Core 2.0.0 preview 1? I can't find it on the release page.

**Comment by karelz** [comment]
@leecow @lt72 can you please help?

**Comment by leecow** [comment]
Sorry about that - links added to the [2.0 Preview 1 download page](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md).
