### ISSUE TITLE
VSC

### ISSUE THREAD

**Issue by DivineKorey** [dotnet/core#6650]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

When I put in code dotnet then I put in dotnet new console -o myApp It will say Could not execute because the application was not found or a compatible .NET SDK is not installed. but I have .Net installed but it stills say that

**Comment by mairaw** [comment]
You might be running into the same issue as #5962. Can you check what `where.exe dotnet` returns?
