### ISSUE TITLE
Docker won't run dotnet restore.

### ISSUE THREAD

**Issue by jwillbrandt** [dotnet/core#6652]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Whenever I try to run the docker build command it fails on the restore, I've attached the error being thrown.

![image](https://user-images.githubusercontent.com/23642589/131917378-ea5b4c69-4198-4494-814c-81694a1d7b38.png)

**Comment by mairaw** [comment]
Can you help with this @nishanil @shirhatti?

**Comment by jwillbrandt** [comment]
I managed to solve this, the issue was being caused by zscaler intercepting the ssl traffic on my machine. The fix involves  exporting the zscaler root certificate and then importing it into the docker image. 

I added the following lines to the dockerfile just before the dotnet restore command:
COPY zscaler.crt /usr/local/share/ca-certificates/zscaler.crt
RUN chmod 664 /usr/local/share/ca-certificates/zscaler.crt
RUN update-ca-certificates
