### ISSUE TITLE
 error code 1

### ISSUE THREAD

**Issue by paskes718** [dotnet/core#6656]
atch : Started
Building...
C:\Users\User\myWebApp\obj\Debug\net5.0\Razor\Pages\Index.cshtml.g.cs(49,71): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\User\myWebApp\myWebApp.csproj]
C:\Users\User\myWebApp\obj\Debug\net5.0\Razor\Pages\Index.cshtml.g.cs(50,81): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\User\myWebApp\myWebApp.csproj]
C:\Users\User\myWebApp\obj\Debug\net5.0\Razor\Pages\Index.cshtml.g.cs(51,16): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\User\myWebApp\myWebApp.csproj]

The build failed. Fix the build errors and run again.

watch : Exited with
watch : Waiting for a file to change before restarting dotnet...

**Comment by mairaw** [comment]
Were you following the asp.net tutorial at https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/intro? Can you show the contents of your Index.cshtml.cs file? Perhaps you edited the .cs file and not the .cshtml as instructed?

**Comment by paskes718** [comment]
attached

**Comment by mairaw** [comment]
Files need to be attached via the website unfortunately. It doesn't work through email response.
