### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Santibianucci** [dotnet/core#6658]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mrbeeru** [comment]
I believe you either:
1) Don't have NET SDK installed
    Download and install the SDK
2) Don't have the SDK's path added to user or system environment variables
    Locate SDK installation path (for me it's `C:\Program Files\dotnet`) and add it to env variables to be recognized by cmd

**Comment by mrbeeru** [comment]
Also check out #5962

**Comment by mairaw** [comment]
Did you open a new command prompt after installing the SDK? Can you paste the output of `dotnet --info` and `where.exe dotnet`?

**Comment by CosmicAtom** [comment]
![DotnetError](https://user-images.githubusercontent.com/98534443/226406703-1de5c66a-dd8a-46c6-8cc6-ed0510825808.png)
![DotnetError1](https://user-images.githubusercontent.com/98534443/226406718-360ce318-fb15-4646-b72d-8464f8b0716b.png)
![DotnetError2](https://user-images.githubusercontent.com/98534443/226406726-0b08e05a-4f9c-49e7-9b70-ccf5a7ad5d27.png)

Please help me !
dotnet command only working in cmd but not in visual studio 2022 or visual studio code.
It open pop-up as show in figure.

**Comment by krwq** [comment]
@CosmicAtom you need to open terminal window in VS. What you currently have is package manager prompt not command line.

Go to `View` and select `Terminal` or press Ctrl+backtick key:

![image](https://user-images.githubusercontent.com/660048/226588292-e627e2ef-13ec-41da-b069-8e0e99edfe7e.png)
