### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by sunildotnet** [dotnet/core#6666]
dotnet watch run
watch : Could not find a MSBuild project file in 'C:\Users\sunil.AFCONSINFRA\myWebApp\Pages'. Specify which project to use with the --project option.

C:\Users\sunil.AFCONSINFRA\myWebApp\Pages>index.cshtml

C:\Users\sunil.AFCONSINFRA\myWebApp\Pages>dotnet watch run
watch : Could not find a MSBuild project file in 'C:\Users\sunil.AFCONSINFRA\myWebApp\Pages'. Specify which project to use with the --project option.

**Comment by sunildotnet** [comment]
I could not get the error

**Comment by mairaw** [comment]
Try running the command `cd..` to go one level up and then running the command again from the myWebApp folder.
