### ISSUE TITLE
Running .NET Core on Raspbian Jessie

### ISSUE THREAD

**Issue by melzoghbi** [dotnet/core#667]
I am trying to install .net core on Raspbian Jessie. Refering to this [link](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md), The link shows how to install and create .net core apps on Debian 64 bit which is not supported in my pi zero board. Is there any arm support for .net core that works on Raspbian Jessie?

Thanks

**Comment by eByte23** [comment]
I am also having the same issue. see https://github.com/dotnet/cli/issues/6726

**Comment by eerhardt** [comment]
I'm not sure if Raspberry Pi Zero is supported (yet) or not.

@Petermarcu - ?

**Comment by Petermarcu** [comment]
I believe we have dependencies on ARMv7 instructions and the Pi Zero is an ARMv6 device. I haven't looked into the details but I don't think it works yet.

**Comment by Petermarcu** [comment]
@RussKeldorph may be able to confirm what our minimum ARM support is.

**Comment by RussKeldorph** [comment]
Correct, 32-bit ARM CoreCLR currently requires ARMv7 as a minimum.  64-bit requires ARMv8.  Wouldn't run on Pi Zero without major work.

**Comment by melzoghbi** [comment]
Thanks for confirming this issue about .NET core is not supported on Pi Zero due to ARMv6 is not supported.

**Comment by Petermarcu** [comment]
I think everything on this issue is understood. I'm going to close it out.
