### ISSUE TITLE
I just downloaded .net sdk, and the installation was successful. However, when I try to download some tools on the cmd, it just says "  It was not possible to find any installed .NET Core SDKs   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:       https://aka.ms/dotnet-download"

### ISSUE THREAD

**Issue by BrayanOvalle16** [dotnet/core#6674]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by svick** [comment]
That error message is usually shown when you install the .Net *Runtime*, but not the .Net *SDK* (yes, it can be confusing). Can you try installing it again, this time making sure it's the SDK?

**Comment by mairaw** [comment]
This might also be the same problem as issue #5962 

Check the output of `where.exe dotnet` and if your system is x64 and the x86 path returns first, please follow the steps highlighted on that issue to fix the problem.

Let us know if that helps.

**Comment by BrayanOvalle16** [comment]
> This might also be the same problem as issue #5962
> 
> Check the output of `where.exe dotnet` and if your system is x64 and the x86 path returns first, please follow the steps highlighted on that issue to fix the problem.
> 
> Let us know if that helps.

It worked! Thank you.

**Comment by mairaw** [comment]
Great to hear. Closing the issue then.
