### ISSUE TITLE
> The same way it is applied on nicknames.

### ISSUE THREAD

**Issue by EzequielYa** [dotnet/core#6682]
> The same way it is applied on nicknames.
> 

[•••]

_Publicación original de @EzequielYa en https://github.com/prawnsalad/KiwiIRC/issues/834#issuecomment-918728476_

**Comment by EzequielYa** [comment]
> > The same way it is applied on nicknames.
> > 
> 
> [•••]
> 
> _Publicación original de @EzequielYa en https://github.com/prawnsalad/KiwiIRC/issues/834#issuecomment-918728476_

<ezequiel198>

**Comment by mairaw** [comment]
Can you clarify what this is about?
