### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by IRONMAN-clone** [dotnet/core#6684]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

So, I installed 3 different version of .DOTNET sdk's still nothing happens when I try to run my C# code so Can I get a fix ?

**Comment by mairaw** [comment]
This might be the same problem as issue #5962

Check the output of where.exe dotnet and if your system is x64 and the x86 path returns first, please follow the steps highlighted on that issue to fix the problem.

Let us know if that helps.
