### ISSUE TITLE
.NET September 2021 Update - .NET 5.0.10 and .NET Core 3.1.19

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/core#6687]
Release Notes 
[5.0.10](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.10.md)
[3.1.19](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.19/3.1.19.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.10 | 3.1.19
|--|--|--
| Ubuntu 16.04   | ✅  | ✅ |
| Ubuntu 18.04   | ✅  | ✅ |
| Ubuntu 20.04   | ✅  | ✅ |
| Ubuntu 20.10    | ✅  | ✅ |
| Ubuntu 21.04     | ✅  | ✅ |
| Centos 7     | ✅  | ✅ |
| Centos 8     | ✅  | ✅ |
| Debian 9    | ✅  | ✅ |
| Debian 10    | ✅  | ✅ |
| Debian 11  | ✅  | ✅ |
| Fedora 32   | ✅  | ✅ |
| Fedora 33   | ✅  | ✅ |
| Fedora 34  | ✅  | ✅ |
| OpenSUSE 15   | ✅  | ✅ |
| SLES 12   | ✅  | ✅ |
| SLES15  | ✅  | ✅ |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by RichardD2** [comment]
Are there no details with the release notes? There's a link to a blog post, but that just links back to the release notes.

**Comment by mairaw** [comment]
@RichardD2 The blog post has links to the improvements in the different areas.

**Comment by kalaskarsanket** [comment]
@RichardD2 - are you looking for changes in 3.1.19 ? as replied on [blogpost ](https://devblogs.microsoft.com/dotnet/september-2021-updates/#comment-10484) we have added 3.1.19 changes in additional improvements section and same has been updated on [release notes](https://devblogs.microsoft.com/dotnet/september-2021-updates/#comment-10484).

**Comment by RichardD2** [comment]
@mairaw The links were added after I posted this. :)

@kalaskarsanket: Thanks for adding that. So if I'm reading it correctly, the only change for 3.1.19 was adding RIDs for Debian and Alpine?

**Comment by avdv** [comment]
Hi.

Looking at the release page for the September .NET 5 Release, there are two:

 1. https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.10.md
 2. https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.207.md

According to the first page, it contains ".NET 5.0.401 SDK", whereas the second one is ".NET SDK 5.0.207".

What's the difference? :confused:

**Comment by kalaskarsanket** [comment]
> Hi.
> 
> Looking at the release page for the September .NET 5 Release, there are two:
> 
> 1. https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.10.md
> 2. https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.207.md
> 
> According to the first page, it contains ".NET 5.0.401 SDK", whereas the second one is ".NET SDK 5.0.207".
> 
> What's the difference? 😕

@avdv the difference is in which Visual Studio version they have been inserted SDK5.0.401 is inserted in vs-version: 16.11.3 and SDK 5.0.207 in 16.9.11. You can find all the information in [releases.json](https://github.com/dotnet/core/blob/822cbe9287e1d85379554a313d8e8347d26ba151/release-notes/5.0/releases.json#L107 )

**Comment by avdv** [comment]
> @avdv the difference is in which Visual Studio version they have been inserted SDK5.0.401 is inserted in vs-version: 16.11.3 and SDK 5.0.207 in 16.9.11. You can find all the information in [releases.json](https://github.com/dotnet/core/blob/822cbe9287e1d85379554a313d8e8347d26ba151/release-notes/5.0/releases.json#L107)

Thanks @kalaskarsanket! So basically there's no functional difference and usually it's nothing one should care about, only if you see version 5.0.207 does not mean it's older / buggier than 5.0.401 since these are equivalent... ?!

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/6794
