### ISSUE TITLE
.NET 6 RC1

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/core#6688]
[Release Notes](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-preview.7.md)

Please report any issues you find with .NET 6, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Important thing note is that this issue impacted VS Hot Reload scenarios only. Users who experienced this issue should update to the latest VS.

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

## Update
During the hot reload compilation, tag helpers from references were not being resolved which resulted in component tags being treated as plain html. The fix for this issue has been made to the Razor Source Generator. As a result we have updated the .NET 6 RC1 SDK to 6.0.100-rc.1.21463.6.

**Comment by buvinghausen** [comment]
The only thing I've noticed thus far is when I turned on ImplicitUsings I get a Microsoft.NET.Sdk project is a CS0234 error.

Error	CS0234	The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)

![image](https://user-images.githubusercontent.com/1130210/133314826-4b415901-9512-4296-b6ea-4d7b30ce3d70.png)

**Comment by jonathanpeppers** [comment]
I think they renamed `@(Import)` to `@(Using)`, you might try:
```xml
<ItemGroup>
  <Using Remove="System.Net.Http" />
</ItemGroup>
```

**Comment by buvinghausen** [comment]
@jonathanpeppers thanks for the info unfortunately it still yields the CS0234 error in the build output but when I navigate to the GlobalUsings.g.cs the red squiggly is no longer underneath the global using global::System.Net.Http; line.

**Comment by yamachu** [comment]
Although it is not directly related to core, I could not find the Feedback destination, so I will write it here.

I noticed when I downloaded rc.1, is the `Latest release date` intended?

https://dotnet.microsoft.com/download/dotnet/6.0

![image](https://user-images.githubusercontent.com/1955233/133319357-13caac3c-e54d-4957-9e21-b5ce036f0418.png)

**Comment by kalaskarsanket** [comment]
@yamachu Thanks for letting us know, we are working on date issue and should be corrected soon.

**Comment by MarcelMichau** [comment]
Hi there!

Not sure exactly where to post this, as it's more related to Azure App Service than .NET 6 specifically, but could anyone provide some information/timelines on when the .NET 6 RC1 runtime might be rolled out to App Service?

It seems like the App Service instances are still on Preview 7 at the moment, at least in the North Europe region.

Thanks very much!

**Comment by teo-tsirpanis** [comment]
Installing RC 1 removes Preview 7 from the installed programs list, but not the actual files. When I installed Preview 7 again, it completed very quickly, indicating that nothing was done. When I tried to remove it manually, it completed very quickly again, and the files remained.

**Comment by AroglDarthu** [comment]
We've ran into a similar problem as the one described here: https://github.com/dotnet/msbuild/issues/6389
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.PlatformNotSupportedException: Strong-name signing is not supported on this platform.
     at System.Reflection.AssemblyName.get_KeyPair()
```

Although https://github/dotnet/msbuild/issues is not in your list above, I am wondering if these are related. Does it need a separate fix in any of the other repos, or do we just have to be patient and wait for a future `net6.0-rc`?

**Comment by WeihanLi** [comment]
When I use the implicit using with multiple level `Directory.Build.props` in my project, it seemed not to work as expected,
project structure, there's reproducing commit for the issue: <https://github.com/WeihanLi/dotnet-httpie/tree/0ee81bd3bcafa07391392340eaa01726ee8ff75c>

![image](https://user-images.githubusercontent.com/7604648/133702848-d1557864-ff05-4668-83b7-d94e8a2d319f.png)

The global using file generated is as follows:

``` c#
// <auto-generated/>
global using global::FluentAssertions;
global using global::HTTPie;
global using global::HTTPie.Implement;
global using global::HTTPie.Middleware;
global using global::HTTPie.Models;
global using global::HTTPie.Utilities;
global using global::Xunit;
```

The `System`/`System.Threading.Task` included by the SDK had not been included, while when I remove the `Directory.Build.props` in the `tests` folder, the generated global usings file is:

```c#
// <auto-generated/>
global using global::HTTPie;
global using global::HTTPie.Implement;
global using global::HTTPie.Middleware;
global using global::HTTPie.Models;
global using global::HTTPie.Utilities;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::WeihanLi.Common;
global using global::WeihanLi.Common.Helpers;
global using global::WeihanLi.Extensions;
```

when navigate the latest commit of the repository, the issue could be fixed

**Comment by murbanowicz** [comment]
The snap version which is recommended to be used on Linux for preview/rc is still broken for this version.
It is impossible to install .NET 6 without the pain on Linux at the moment.
On Fedora we are hitting: `cannot snap-exec: cannot exec "/var/lib/snapd/snap/dotnet-sdk/142/snap/command-chain/snapcraft-runner": permission denied` for whole .NET 6 release chain since few months.
I still cannot get why Windows and Mac get installers for previews/rc, but Linux distros don't get them in package managers.

**Comment by leXorNet** [comment]
Hi,
While plain net6.0 (rc1) works fine for me, I'm having real issues when adding the MacOS workload.
Build times for a simple "hello world" goes from ~1 sec to ~10 sec and breakpoints stop working (VS-Mac 2019).
Also, I can't get a two project setup to work (console-project that depends on a lib-project), when one or both is targeting macos. A sample solution for this would be appreciated :) Please see error below.

Project:
<TargetFramework>net6.0-macos</TargetFramework>
<RuntimeIdentifier>osx-x64</RuntimeIdentifier>

Error:
"/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.MonoTargets.Sdk/6.0.0-rc.1.21451.13/Sdk/RuntimeComponentManifest.targets(3,5): error : Empty ResolveFrameworkReference.RuntimePackPath while trying to read runtime components manifest. ResolvedFrameworkReference available: { Microsoft.NETCore.App, RuntimePackPath:  }"

**Comment by AlexeyStarkov** [comment]
> Hi, While plain net6.0 (rc1) works fine for me, I'm having real issues when adding the MacOS workload. Build times for a simple "hello world" goes from ~1 sec to ~10 sec and breakpoints stop working (VS-Mac 2019).
> 
> Also, I can't get a two project setup to work (console-project that depends on a lib-project), when one or both is targeting macos. A sample solution for this would be appreciated :) Please see error below.
> 
> Projects:
> 
> ```
> <TargetFramework>net6.0-macos</TargetFramework>
> <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
> ```
> 
> Error: `"/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.MonoTargets.Sdk/6.0.0-rc.1.21451.13/Sdk/RuntimeComponentManifest.targets(3,5): error : Empty ResolveFrameworkReference.RuntimePackPath while trying to read runtime components manifest. ResolvedFrameworkReference available: { Microsoft.NETCore.App, RuntimePackPath: }"`

Did you solve that "Empty ResolveFrameworkReference.RuntimePackPath" problem? I'm facing the same issue with MAUI and "net7.0-ios" target framework

**Comment by jongfeel** [comment]
> > Hi, While plain net6.0 (rc1) works fine for me, I'm having real issues when adding the MacOS workload. Build times for a simple "hello world" goes from ~1 sec to ~10 sec and breakpoints stop working (VS-Mac 2019).
> > Also, I can't get a two project setup to work (console-project that depends on a lib-project), when one or both is targeting macos. A sample solution for this would be appreciated :) Please see error below.
> > Projects:
> > ```
> > <TargetFramework>net6.0-macos</TargetFramework>
> > <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error: `"/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.MonoTargets.Sdk/6.0.0-rc.1.21451.13/Sdk/RuntimeComponentManifest.targets(3,5): error : Empty ResolveFrameworkReference.RuntimePackPath while trying to read runtime components manifest. ResolvedFrameworkReference available: { Microsoft.NETCore.App, RuntimePackPath: }"`
> 
> Did you solve that "Empty ResolveFrameworkReference.RuntimePackPath" problem? I'm facing the same issue with MAUI and "net7.0-ios" target framework

@leXorNet 
@AlexeyStarkov 

Hi guys, I've got same issue with MAUI and xUnit project on MacOS.

and I've fix this problem and hope this link help.

https://cedricgabrang.medium.com/adding-xunit-test-to-your-net-maui-project-ee36c00a8542
