### ISSUE TITLE
RenderSection rendering incorrectly inside tag attribute

### ISSUE THREAD

**Issue by CoderProject** [dotnet/core#669]
To reproduce the issue write the RenderSection inside a tag attribute in your Layout in Shared folder:
Exp: `<body class="@RenderSection("cls",false)">`

Set the section content:
`@section cls{login}`

The result is rendered as following:
`<bodylogin class>`

**Comment by karelz** [comment]
Looks like ASP.NET or WebPages question - can you please file it in appropriate aspnet repo? https://github.com/aspnet
