### ISSUE TITLE
Template "ASP.NET Core Web App" could not be created.

### ISSUE THREAD

**Issue by vignesh123007** [dotnet/core#6696]
Template "ASP.NET Core Web App" could not be created.
Access to the path 'C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\myWebApp' is denied

_Originally posted by @vignesh123007 in https://github.com/dotnet/core/issues/6695#issuecomment-919674521_

**Comment by tannergooding** [comment]
Closing as duplicate of #6698, #6697, and #6695
