### ISSUE TITLE
dotnet new does not work  on Ubuntu

### ISSUE THREAD

**Issue by czhj** [dotnet/core#67]
Failed to load /usr/share/dotnet/bin/libcoreclr.so, error: /usr/share/dotnet/bin/libcoreclr.so: cannot enable executable stack as shared object requires: Invalid argument
Failed to bind to coreclr

**Comment by galich** [comment]
same trouble here

**Comment by TigerLeep** [comment]
I have the same problem.  I'm trying to use dot net core un Windows Subsystem for Linux on the latest Windows Insiders Preview (14332), so I'm not sure if this is a WSL or Ubuntu issue.

**Comment by kekyo** [comment]
14342 same problem too.

**Comment by vyurchenko** [comment]
build 14342 same problem

**Comment by rweads0520** [comment]
Being promoted as a feature for developers, I was surprised that getting dotnet working wasn't one of the first priorities. Building and testing .NET Core for Ubuntu seemed like one of the best reasons for doing WSL/Ubuntu. Hope this gets addressed soon.

**Comment by TigerLeep** [comment]
I think that by "being promoted as a feature for developers", Microsoft
meant it was providing access to standard Linux developer tools (like grep,
sed, tail, nano, etc.) for use when doing development under Windows.  That
being said, I would still love it if the Windows Subsystem for Linux could
get the point that it could be used for more than just bringing native
Linux developers tools to Windows, such as developing .Net Core
applications, MEAN stack development under Linux, etc.

On Wed, May 18, 2016 at 8:57 AM, Robb Eads <notifications@github.com> wrote:

> Being promoted as a feature for developers, I was surprised that getting
> dotnet working wasn't one of the first priorities. Building and testing
> .NET Core for Ubuntu seemed like one of the best reasons for doing
> WSL/Ubuntu. Hope this gets addressed soon.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/core/issues/67#issuecomment-220017567>
>



-- 
Lee Perkins
TigerBase Technologies
leep@tigerbase.com
------------------------------


*[image: Hampton Roads .NET Users Group]2nd Tuesday of every month. Come
meet, learn, network and eat pie!
<http://www.meetup.com/Hampton-Roads-NET-Users-Group/>*

**Comment by styfle** [comment]
@TigerLeep In a [demo video](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/) by Microsoft, they specifically show a ruby app being developed using the WSL/Ubuntu. It seems like if they support ruby development, they should also support .NET Core development.

**Comment by joshfree** [comment]
Hi folks,
The .NET Core 1.0 platform support matrix is available @ https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0.md#rtm-platform-support.

https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0-known-issues.md#bash-on-ubuntu-on-windows
Bash on Windows (WSL) is not yet supported by .NET Core 1.0.  Attempting to run applications in the WSL environment can experience intermittent crashes.
https://github.com/Microsoft/BashOnWindows/issues/520


Feel free to report any other Bash on Windows issues @ https://github.com/Microsoft/BashOnWindows
