### ISSUE TITLE
i have this problem with the installation

### ISSUE THREAD

**Issue by davideC22** [dotnet/core#6701]
despite having installed everything correctly I get this problem
[ It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download]

**Comment by mairaw** [comment]
Are you on Windows? This might be the same problem as issue #5962

Check the output of where.exe dotnet and if your system is x64 and the x86 path returns first, please follow the steps highlighted on that issue to fix the problem.

Let us know if that helps.
