### ISSUE TITLE
Add Description to the ExcludeFromCodeCoverage Attribute

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/core#6705]
Please add a Reason or Description property to this attribute. If a class, method etc. is marked to not be included in code coverage, it should be documented so the next reviewer that see it, sometimes years later, understand why the code does not need to be covered.

**Comment by mairaw** [comment]
Hey @RealDotNetDave, isn't the [Justification](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute.justification?view=net-5.0) property what you're looking for? It was added in .NET 5 it seems.

**Comment by RealDotNetDave** [comment]
Can this be added to the .NET Framework?

**Comment by jeffhandley** [comment]
Hello @RealDotNetDave. The bar for adding new APIs/properties to .NET Framework is very high, and this would not meet that bar--the workaround would be to use code comments to capture the justification.

Thanks for submitting this request nonetheless.
