### ISSUE TITLE
Problem with https://packages.microsoft.com/rhel/8/prod/

### ISSUE THREAD

**Issue by dralley** [dotnet/core#6706]
I understand this isn't really related to dotnet/core, but I was [told](https://github.com/dotnet/core/issues/6381#issuecomment-920978055) to file the issue here because no public issue tracker exists for packages.microsoft.com.

### Description

The repository at  https://packages.microsoft.com/rhel/8/prod/ contains multiple different instances of the same package NEVRA (the name-epoch-version-release-architecture tuple) with different checksums.  

![Screenshot from 2021-09-15 22-19-03](https://user-images.githubusercontent.com/2751996/133656494-a8993b89-fbf4-446c-9809-25a1a80fd1bf.png)

(this is the output of my own tool, but I also verified it manually, and I had a discussion with a DNF maintainer to confirm that this situation is problematic)

For the `blobfuse` packages, the only difference between these two packages for each version in the metadata is the checksum, build timestamp, and the filename.  From the filename we can assume that  "blobfuse-1.4.1-**RHEL-8.1**-x86_64.rpm" is meant for RHEL 8.1 and "blobfuse-1.4.1-**RHEL-8.2**-x86_64.rpm" is meant for RHEL 8.2, and that presumably the distinction does actually matter (otherwise, why have two packages?) - but the package manager has no way of knowing this.  It works off of the repository and package metadata only, and in the event that a package with the same version is listed twice, the best you can hope for is that the client (dnf / yum / zypper) picks the one with the most recent build timestamp (which is used as a tiebeaker of last resort)

So if the distinction between these RPMs does matter, then be aware that what is *likely happening*, is that the package meant for 8.2 is being installed on RHEL 8.1.  And if it doesn't matter, then there shouldn't be two different copies of it.

Likewise with the `mssql-zulu-jre` packages, it looks like the package was built twice and the file simply renamed, rather than changing the "release" metadata in the specfile when building the package.  This means that both packages think they are "mssql-zulu-jre-11.31.10-1.x86_64"

### Configuration

N/A

### Regression?

N/A

### Other information

N/A

**Comment by dralley** [comment]
Likewise with the `mssql-zulu-jre` packages, it looks like the package was built twice and the file simply renamed, rather than changing the "release" metadata in the specfile.  This means that both packages think they are "mssql-zulu-jre-11.31.10-1.x86_64"

**Comment by dralley** [comment]
@rbhanda ^

**Comment by ravindrabhartiya** [comment]
Thanks for reporting this issue. PMC engineering team is taking a look at it right now.

**Comment by ravindrabhartiya** [comment]
@dralley teams are cleaning up the duplicate packages.

**Comment by dralley** [comment]
Looks like this issue is fixed now, thank you.

**Comment by dralley** [comment]
@ravindrabhartiya I have another one, should I just continue here, file a new issue, or is there a proper issue tracker yet?

**Comment by dralley** [comment]
I can file another one if you ask but I'll go ahead and type it all out.

There are a couple of packages that have ***millions*** of duplicate "file" entries in the filelists.xml metadata, which causes it to expand to more than 1gb of data when decompressed (it's only about 8 megabytes compressed - the duplicate strings compress well).

I updated the same tool from before to detect this:

![Screenshot from 2021-12-05 18-58-34](https://user-images.githubusercontent.com/2751996/144769620-b282e247-d883-4392-89f6-c111c85150aa.png)
