### ISSUE TITLE
Write document on how to use local copies of third party dependencies

### ISSUE THREAD

**Issue by janvorli** [dotnet/core#671]
Now that we have support for local copies of third party dependencies in the self-contained apps, write down a document on how to use that feature.

**Comment by Petermarcu** [comment]
@janvorli, can we get a simple doc in place before 2.0 ships?

**Comment by richlander** [comment]
How is this diff than #672?

Is this about local resolution and #671 is the specific versions?

Send me a sample with some notes and I can write this up.

**Comment by Petermarcu** [comment]
They are related. This one is about how to copy them app local. First step is install them for your distro. Then copy the right things out of them for app local. We may even want to script both of these...

**Comment by Petermarcu** [comment]
I believe this can be closed because the doc is here: https://github.com/dotnet/core/blob/master/Documentation/self-contained-linux-apps.md
