### ISSUE TITLE
help

### ISSUE THREAD

**Issue by w00w00w** [dotnet/core#6719]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tannergooding** [comment]
Can you please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
