### ISSUE TITLE
Need to document the versions of dependencies that can be resolved by the linux-* runtimes.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core#672]

**Comment by richlander** [comment]
Is this list distro dependent? I assume so.

**Comment by Petermarcu** [comment]
Yes, it is. I just hit this problem again last night trying to get the deps installed on Raspbian.

**Comment by Petermarcu** [comment]
Closing this as this similar issue has more traction. https://github.com/dotnet/core/issues/679
