### ISSUE TITLE
DOTNET error

### ISSUE THREAD

**Issue by Lahiru-Malshan** [dotnet/core#6721]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
It shows like following;
Creating this template will make changes to existing files:
  Overwrite   ./myApp.csproj
  Overwrite   ./Program.cs

Rerun the command and pass --force to accept and create.

**Comment by tannergooding** [comment]
Can you please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Its not clear what issue you're encountering. Is it that you're trying to run `dotnet new console -o myApp` and you get that output?

**Comment by Lahiru-Malshan** [comment]
Hi! Thanks for replying me.
I tried to do as this link says:.NET Tutorial | Hello World in 5 minutes
(microsoft.com)
<https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create>,
but it wasn't successful. It shows up an error like the attachment shows.
[image: DOTNET_ERROR.png]

**Comment by Lahiru-Malshan** [comment]
Hi! Thanks for replying to my problem. I'm on Windows 11 PRO 64 bit.[image:
DOTNET_ERROR.png]
I tried to do as this link says:.NET Tutorial | Hello World in 5 minutes
(microsoft.com)
<https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create>,
but it wasn't successful. It shows up an error like the attachment shows.

**Comment by steveharter** [comment]
> Creating this template will make changes to existing files:

From this is appears you are trying to create a new project in a directory where there already a project. Try creating a new directory and from that run `dotnet new console -o myApp`.

Please re-open if this doesn't address the issue.
