### ISSUE TITLE
didnt work

### ISSUE THREAD

**Issue by mrbuilder687** [dotnet/core#6729]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

after installing a .NET on my pc, i ran "dotnet new console" command in VS, but it said " It was not possible to find any installed .NET Core SDKs" even though i installed one, i even tried uninstalling it again and then making sure i installed a core version, but still didnt work

**Comment by mairaw** [comment]
This might be the same problem as issue #5962

Check the output of where.exe dotnet and if your system is x64 and the x86 path returns first, please follow the steps highlighted on that issue to fix the problem.

Let us know if that helps.
