### ISSUE TITLE
dotnet: The term 'dotnet' is not recognized as the name of a cmdlet, Visual Studio Code

### ISSUE THREAD

**Issue by av00000** [dotnet/core#6732]
dotnet: The term 'dotnet' is not recognized as the name of a cmdlet,
function, script file, or executable program. Check if you wrote
the name correctly or, if you included a path, verify that
that path is correct and please try again.
Online: 1 Character: 1
+ dotnet
+ ~~~~~~
     + CategoryInfo: ObjectNotFound: (dotnet: String) [], CommandNo
    tFoundException
     + FullyQualifiedErrorId: CommandNotFoundException

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you install the SDK? And if so, did you open a new command prompt or PowerShell window after the installation?
