### ISSUE TITLE
provided code does not appear 

### ISSUE THREAD

**Issue by Raph-T** [dotnet/core#6735]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Once I run the code the page says this site cannot be reached.

**Comment by mairaw** [comment]
Did the project run at least once or not at all? Did the project build alright? Any error messages when you run `dotnet watch run`?

**Comment by mairaw** [comment]
Were there any errors on the console? Maybe try starting over and see if you have the same problem. One thing to pay attention to on Windows is to make sure you're editing the cshtml file and not the cshtml.cs file (sometimes the extension is hidden and users end up editing the wrong one and run into issues). Please let me know what errors you see.

**Comment by Raph-T** [comment]
I was indeed modifying the .cs file in visual  studio. The other one I
could only use notepad ++, is this the one ?

**Comment by mairaw** [comment]
Attachments don't work if you reply via e-mail, only via GitHub UI on their site.

The tutorial asks you to edit the cshtml page, not the cs page.

**Comment by Raph-T** [comment]
All is well

Thank you for your help Maira

**Comment by mairaw** [comment]
It seems you're good now so closing the issue.
