### ISSUE TITLE
4.8 framework not insttal

### ISSUE THREAD

**Issue by kushwah94** [dotnet/core#6739]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by kushwah94** [comment]
4.8 framework blocking system

**Comment by mairaw** [comment]
You can download .NET Framework 4.8 from https://dotnet.microsoft.com/download/dotnet-framework/net48

But certain operating systems like Windows 10 already have .NET Framework installed.
