### ISSUE TITLE
Run 2.0.0-preview1 on windows docker with linux settings - invalid interpolation

### ISSUE THREAD

**Issue by wisien92** [dotnet/core#674]
Hi,

I am trying to develop .net core web app that will be run on linux with docker. Development however will be done on windows machine.

I have created blank project with docker support for linux and when I try to run i get error:

```
Invalid interpolation format for "volumes" option in service "webapplication2": "${NUGET_PACKAGES}:/root/.nuget/packages:ro".
```

**Comment by karelz** [comment]
Does it happen on more than 1 machine? Is it maybe some weird setup or distro?

**Comment by richlander** [comment]
Can you share either your Dockerfile or share how you have mounted volumes?

**Comment by Petermarcu** [comment]
I'm going to close this now because its been a while without a response. Please let us know if you can provide more details.
