### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by yogeshgitika** [dotnet/core#6744]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Error :

'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mairaw** [comment]
Hi @yogeshgitika! Did you install the SDK? If so, did you open a new command prompt after the installation?
