### ISSUE TITLE
scriptcs : The term 'scriptcs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path  is correct and try again. At line:1 char:1 + scriptcs "c:\Users\Nachiket\myApp\Program.cs" + ~~~~~~~~     + CategoryInfo          : ObjectNotFound: (scriptcs:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

### ISSUE THREAD

**Issue by batwenachiket** [dotnet/core#6747]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What command did you type to get this error @batwenachiket?
