### ISSUE TITLE
Install Operating System: macos

### ISSUE THREAD

**Issue by DilharaPeiris** [dotnet/core#6748]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tannergooding** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Ideally you would provide a series of steps such as:

> **Repro:**
> 1. Run `dotnet new console` using the .NET 6 RC1 SDK
> 2. Add the following code to the project:
> ```csharp
> Console.WriteLine("Hello");
> ```
> 3. Run `dotnet run`
>
> **Expected Behavior:**
> I expected the following to happen
>
> **Actual Behavior:**
> This actually happened

This makes it very easy for anyone reading the issue to reproduce the same issue and understand the context of what's happening.
