### ISSUE TITLE
decimal numbers that end in {n}0.5 do not round to nearest upper bound whole number

### ISSUE THREAD

**Issue by atkonline** [dotnet/core#6756]
### Description
I believe I found a bug 
100.5 -> I would expect to round to 101 when using decimal.Round(num) function - except it does not. 
89.5 -> rounds to 90
90.5 -> rounds to 90
etc. 

### code example

using System;
using System.Collections.Generic;
using FluentAssertions;
using RevalDefenceTool.Extensions;
using Xunit;

namespace RevalDefenceTool.Tests.Extensions
{
    public class DecimalExtensionsTests
    {
        [Theory]
        [MemberData(nameof(Data))]
        public void ToCurrencyStringRounded_Rounds_To_Whole_Number(decimal source, string expected)
        {
            var result = source.ToCurrencyStringRounded();
            result.Should().Be(expected);
        }

        public static IEnumerable<object[]> Data =>
            new List<object[]>
            {
                new object[] { 100.5m, "£101" }, // test fails! possible bug??
                new object[] { 125.00m, "£125"},
                new object[] { 125.4m, "£125"}, 
                new object[] { 125.5m, "£126"},
                new object[] { 125.6m, "£126"},
            };  
    }
}

**Comment by ufcpp** [comment]
see [`ToEven`](https://docs.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=net-5.0)

**Comment by CarnaViire** [comment]
That's right, [Math.Round(double)](https://docs.microsoft.com/en-us/dotnet/api/system.math.round?view=net-5.0#System_Math_Round_System_Double_) and similar APIs use [MidpointRounding.ToEven](https://docs.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=net-5.0#System_MidpointRounding_ToEven) by default. You can use an overload to specify another value of MidpointRounding if required.
Closing.
