### ISSUE TITLE
~$ : The term '~$' is not recognized as the name of a cmdlet, 

### ISSUE THREAD

**Issue by Akanshasingh09** [dotnet/core#6771]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
~$ : The term '~$' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and  
try again.
At line:1 char:1
+ ~$ dotnet
+ ~~
    + CategoryInfo          : ObjectNotFound: (~$:String) [], CommandN  
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
You should only type `dotnet` without ~$

Let us know if this helps.

**Comment by Akanshasingh09** [comment]
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and  
try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], Comm  
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Akanshasingh09** [comment]
> You should only type `dotnet` without ~$
> 
> Let us know if this helps.

**Comment by Akanshasingh09** [comment]
help me I'm not able to install dotnet
