### ISSUE TITLE
not reloading

### ISSUE THREAD

**Issue by mohamedibrahim007** [dotnet/core#6772]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
i try to run the dot net run command but the edited code would not appear on the browser but the original one will

**Comment by danroth27** [comment]
I agree that the first thing to check is that the code file changes were actually saved.

Note also that if you run your app using `dotnet watch` instead of `dotnet run` your app should rebuild and restart automatically as you save changes and the automatically refresh in the browser.

**Comment by mairaw** [comment]
Let us know if any of this helped @mohamedibrahim007!

**Comment by steveharter** [comment]
Closing; please re-open if the issue still exists after ensuring the changes were saved. Thanks.
