### ISSUE TITLE
dotnet new console

### ISSUE THREAD

**Issue by JakeTheDev0000** [dotnet/core#6777]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

When I type 'dotnet new console' it says:
'
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
'
and I already have the .NET Core SDK installed

**Comment by mairaw** [comment]
This might be the same problem as issue #5962

Check the output of `where.exe dotnet` and if your system is x64 and the x86 path returns first, please follow the steps highlighted on that issue to fix the problem.

Let us know if that helps.
