### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rahul2696** [dotnet/core#6780]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by CarnaViire** [comment]
Hi @rahul2696! Have you installed .NET SDK beforehand? If so, have you opened a new command prompt afterwards?
