### ISSUE TITLE
'net5.0' is not a valid value for -f (Framework).

### ISSUE THREAD

**Issue by WaqasRazaJafri** [dotnet/core#6784]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/create
Operating System: windows

error received: 

'net5.0' is not a valid value for -f (Framework).

**Comment by mairaw** [comment]
What SDK do you have installed? Can you show the output of `dotnet --info`?

**Comment by WaqasRazaJafri** [comment]
@mairaw 

.NET Core SDK (reflecting any global.json):
 Version:   3.1.407
 Commit:    d3244d0e44

Thank you
