### ISSUE TITLE
Need to do a better job documenting SDK and Runtime dependencies

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core#679]
See: https://github.com/dotnet/core/issues/447#issuecomment-307462749

This needs to happen here: https://github.com/dotnet/core/blob/master/Documentation/prereqs.md

As well as in our official documentation. I always point people to the dockerfiles but those shouldn't be the docs.

**Comment by wfurt** [comment]
Are we positive the link has runtime dependencies @Petermarcu ? I would expect the -dev packages be needed only for building. They typically contains headers and static libraries.

**Comment by omajid** [comment]
AFAIK, many packages link against `lib<name>.so`. The `-dev` packages provide these `lib<name>.so` files. The non `-dev` packages generally provide `lib<name>.so.<version>`.

**Comment by Petermarcu** [comment]
@wfurt I was saying the docs should have the details for dev and runtime. It only has dev today and only for a few distros.

**Comment by wfurt** [comment]
agreed. I'll do some testing and I can update docs - unless we already know the answer. If @omajid is right, we should look at build process. I would expect -devel packages not needed for runtime.

**Comment by Petermarcu** [comment]
Correct, you can see my comment in the linked issue. Our runtime dockerfiles have the list with transitive closure for the runtime.

**Comment by rubberduck203** [comment]
So, this [completely burnt me this week](https://github.com/libgit2/libgit2sharp/issues/1472), and I ended up referring to the Dockerfiles as well. What makes this *really* bad is that you might not even get an indication of what's wrong if you have libicu and libunwind installed, but not some of the other dependencies. 

I ended up blindly installing all of the dependencies in the docker, but it would be nice to know exactly which dependencies I need to tell my users to install as pre-reqs to running my self-contained app.

**Comment by Petermarcu** [comment]
@danmosemsft, following up on the conversation we had a couple days ago in email, can you create an issue tracking "Good error messages for all possible missing dependencies"?

**Comment by Petermarcu** [comment]
I just made a PR to get the docs updated. https://github.com/dotnet/docs/pull/3344

**Comment by Petermarcu** [comment]
I'm going to close this issue here now because all the right follow up issues and PR's have been created.
