### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ST-dev28** [dotnet/core#6790]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I got error: Failed to spawn 'dotnet --info'

**Comment by mairaw** [comment]
Unfortunately email replies don't let you add attachments to the issue. Can you share via GitHub UI?
