### ISSUE TITLE
.NET 6 RC2

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/core#6795]
[Release Notes](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-rc.2.md)

Please report any issues you find with .NET 6, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Important thing note is that this issue impacted VS Hot Reload scenarios only. Users who experienced this issue should update to the latest VS.

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

## Update
During the hot reload compilation, tag helpers from references were not being resolved which resulted in component tags being treated as plain html. The fix for this issue has been made to the Razor Source Generator. As a result we have updated the .NET 6 RC2 SDK to 6.0.100-rc.2.21505.57.

**Comment by murbanowicz** [comment]
Snap is still broken on Fedora:
```
cannot snap-exec: cannot exec "/var/lib/snapd/snap/dotnet-sdk/145/snap/command-chain/snapcraft-runner": permission denied
```

**Comment by whistlerek** [comment]
After upgrading from .Net 5 to .Net 6 RC2, Windows authentication no longer works. I also tried created new project from template (ASP.NET Core Web App) with Windows Authentication, this doesn't work when launched it shows “Hello, !”. When do the same with .Net 5 it starts with “Hello, MyDomain\Marcin!”

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/6881
