### ISSUE TITLE
Problem getting dotnet to run

### ISSUE THREAD

**Issue by JoHenri** [dotnet/core#6799]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.  
Running Win10 on Dell Precision 3530 laptop.  Installed .Net 4.8 and it said setup was successful.  But when I type dotnet in a command prompt I get
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
Are you trying to follow the tutorial and learn how to code, or are you trying to install .NET Framework 4.8?

**Comment by JoHenri** [comment]
The first page I went to said it recommended 4.8 so that's what I
downloaded and installed.  Then I went to the tutorial.  I did not realize
that the tutorial required 5.0.  I have written lots of C code.  I'd like
to learn C# but cannot acquire Visual Studio so wanted to try through
.NET.
