### ISSUE TITLE
Remote Debugging with Docker?

### ISSUE THREAD

**Issue by tonysneed** [dotnet/core#68]
Does .NET Core supports remote debugging? I seem to recall a part of Scott Hanselman's Build demo where he used the VS Tools for Docker to remote debug into a Docker container. But I can't remember if the container was running .NET Core. I'd be grateful for any information on this.

I cross-posted my question [here](https://github.com/OmniSharp/omnisharp-vscode/issues/220) on the omnisharp-vscode repo, but I think it's probably more relevant to the .NET Core repo.

**Comment by diryboy** [comment]
He demonstrated a time zone issue, it's C# code running on Linux.

**Comment by tonysneed** [comment]
Yes, I thought it was a nice motivation for developing apps with source code mapped to a Docker container volume.  I'm just trying to piece together the debugging story.

**Comment by joelmartinez** [comment]
@tonysneed I too am trying to piece together a nice dev workflow for working with docker ... would you care to share your _Dockerfile_ that shows how to map the container volume? 

Aside from the question, also wanted to comment so that I get notifications for this issue :)

**Comment by tonysneed** [comment]
Cool, yes happy to share. I have nice demo of using dotnet-watch with Docker: https://github.com/tonysneed/Demo.DotNetWatchDocker

It would be cool to be able to attach a debugger and set breakpoints. :)

**Comment by tzwlai** [comment]
Looks like @gregg-miskelly has already answered this question in OmniSharp/omnisharp-vscode#220.
