### ISSUE TITLE
Unable to resolve 'Swashbuckle.AspNetCore (>= 5.6.3)' for 'net5.0'

### ISSUE THREAD

**Issue by geokal** [dotnet/core#6803]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run
Operating System: windows
net 5.0 SDK installed version:

`$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.402\

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download`

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

`$ dotnet run
Building...
C:\Users\bigbu\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 5.6.3)' for 'net5.0'.

The build failed. Fix the build errors and run again.`

Also doing dotnet restore failed as well :

`$ dotnet restore
  Determining projects to restore...
C:\Users\bigbu\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 5.6.3)' for 'net5.0'.
  Failed to restore C:\Users\bigbu\MyMicroservice\MyMicroservice.csproj (in 102 ms).`

**Comment by steveharter** [comment]
See also https://github.com/dotnet/core/issues/6193#issuecomment-827395026 for cases where the nuget package sources may not be defined.
