### ISSUE TITLE
Unit tests in 1.04 no longer running (xunit)

### ISSUE THREAD

**Issue by olivd** [dotnet/core#681]
Hi,

Sorry for logging this here. I am not sure which other repo to log it in.

Since upgrading from dotnet core 1.03 on mac to 1.04 the xunit tests that we were running just fine previously on both windows and mac and debian are failing... well they are just not running on windows and also in Visual Studio for Mac. (dotnet cli still runs the tests fine in mac and debian)

Not sure but it does seem like it has something to do with threading. I have had a few new issues with async Tasks that have no return statement failing in 1.04, program executes fine but the thread seems to get lost and never returns to the control thread or gets aborted when the program terminates.

I hope this helps you solve these issues as I have found VS for mac pretty nice in a few ways and would like to see it as a viable option for our dev, as it is though we run our test suite and only a handful of tests ever get executed properly.

On windows when we ran migrate and executed the tests for our coverage reporting they would also work with 1.03 but now they don't execute properly.

Thanks.

**Comment by karelz** [comment]
I am a bit confused.
First, what is 1.03 and 1.04? Did you mean [1.0.3](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.3.md) and [1.0.4](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.4.md)?

Do you see the problem only on Mac? Or also on Windows?
Do you see the problem on more than one machine?
What happens if you downgrade your machine to previous .NET Core version "1.03"?

**Comment by olivd** [comment]
Sorry yes, 1.0.3 and 1.0.4

Mac (cli works, visual studio for mac does not), Windows nothing works, tests just hang.

**Comment by karelz** [comment]
Did you try to create minimal repro? HelloWorld test. Only parts of you app?
The changes in 1.0.4 were minimal - see the list above. It is highly unlikely a problem in .NET Core itself. Try to get minimal repro (I would start with CLI on Windows), then do first-level debugging.

**Comment by olivd** [comment]
Seeing it works in the CLI I am not going to do that. I was just trying to give you guys a heads up.

**Comment by Petermarcu** [comment]
I think we'd need a repro in order to make this actionable.

**Comment by olivd** [comment]
Just an FYI as it looks like you deleted the issue I was having.

It seems like the issue was due to a version discrepancy in our
dependencies in our csproj files on referenced projects, after getting the
latest versions across all our csproj files the unit tests are running
without any issues on all platforms.

Cheers,


*Oliver D'Alton* Software Development Team Lead

*T: *02 9694 0397 *F: *02 9694 0351
*E: *oliver.dalton@winning.com.au
*A: *Level 2, 20A Danks Street, Redfern, NSW 2016

*www.winningappliances.com.au <http://www.winningappliances.com.au/>*

[image: www.winningappliances.com.au] <http://www.winningappliances.com.au/>

**Comment by olivd** [comment]
Oh cool, I couldn't find this earlier. No worries I will close it now
