### ISSUE TITLE
Question: What does the UWP 6.0 milestone on the roadmap exactly mean?

### ISSUE THREAD

**Issue by nopara73** [dotnet/core#682]
Does it mean I will be able to finally write .NET Core desktop apps with cross platform GUI? Or will it be Windows ecosystem only?

**Comment by Petermarcu** [comment]
UWP is a Windows only platform (Universal Windows Platform).

**Comment by nopara73** [comment]
I see, thank you. Is there any conversation going on about cross platform GUI on .NET Core? I thown it together with Electron for my testing release, however before I give out my first stable release in the coming years I have to properly rewrite it. My point is if Microsoft would support cross platform GUI, I would chose to not go down on the nodejs path.

**Comment by Petermarcu** [comment]
@migueldeicaza may have some advice.

**Comment by nopara73** [comment]
I think no need to reopen it, the issue is resolved (=the original question is answered), the followup questions would rather go to something like "personal guidance" category.
