### ISSUE TITLE
Types derived from MarshalByRefObject need a workaround to work when compiled for x64 runtimes

### ISSUE THREAD

**Issue by Nefarion** [dotnet/core#6833]
# The Problem:
A call to a class derived from `MarshalByRefObject`, created with `AppDomain.CreateInstanceFromAndUnwrap()` threw a `FileNotFoundException` because it tried to load the referenced Assemblies in the original, not the newly created `AppDomain`.

# This was my situation:
I have a type derived from `MarshalByRefObject`, that has simple Log methods on it. (references Serilog.dll)
```csharp
internal class Logger : MarshalByRefObject
{
    public void Information(string msg, params object?[] args) { /* implementation that uses Serilog.dll (that already got used in the ctor successfully */ }
}
```
My `<TargetFramework>` is `net48`

I create a different AppDomain with **DIFFERENT** PrivateBinPath and ApplicationBase than the current AppDomain.
This means the current AppDomain cannot resolve the libraries in PrivateBinPath automatically (it could with a AssemblyResolve event handler), but the goal is **NOT** to load into the main AppDomain:
```csharp
var domain = AppDomain.CreateDomain("LoggerAppDomain", null, new AppDomainSetup { PrivateBinPath = "...", ApplicationBase = "..." });
```

The Logger instance gets created (constructor runs fine and loads referenced assemblies correctly)
```csharp
var logger = (Logger) _appDomain.CreateInstanceFromAndUnwrap(GetType().Assembly.Location, typeof(Logger).FullName, false, BindingFlags.Default, null, new object[] { /* some args */ }, null, Array.Empty<object>() );
```

The VisualStudio Debug Window shows Serilog.dll beeing loaded into the `LoggerAppDomain`

Calling `logger.Information(...)` resulted in a `FileNotFoundException` with Serilog.dll not beeing found.

I tried this in a Unit-Test project, and it worked flawlessly.

It did not work in my library project...

# The Solution:
What i found is [this](https://social.msdn.microsoft.com/Forums/sqlserver/de-DE/c6a62351-7bc8-49ea-9bc7-3720de7444da/assemblyloader-filenotfoundexception-trotz-privatebinpath-in-64bit-windows-2008?forum=visualcsharpde): (sorry, link is in german)
It references information from a connect.microsoft.com post and an answer by `David Wrighton from the .NET Framework CLR Team` in english and thankfully also translates it in place, or the information would be lost, because connect.microsoft.com does not exist any more.

The solution is to mark the Method with `virtual` like this:
```csharp
internal class Logger : MarshalByRefObject
{
    public **virtual** void Information(string msg, params object?[] args) { /* implementation that uses Serilog.dll (that already got used in the ctor successfully */ }
}
```
Why? (Translated back from the aforementioned post)

> This problem is caused by the fact that non-virtual remote-enabled methods are jitted differently on x86 and x64 machines. 
>When a method is called, the x86 runtime performs all the necessary remoting transformations and then tries to jitter the method into the target AppDomain. 
>**The behavior of the x64 runtime is subtly different:** 
>**The runtime does not prepare the method for remoting the first time it is called, but rather at an earlier point in time (as soon as it finds this method in an AppDomain).** 
> **If this is a remote-capable method, it will now be jitted twice by the x64 runtime.** 

My code would work fine in a x86 or AnyCPU Project (like my UnitTest project), but the x64 JIT-Compiler `NEEDS` the virtual keyword to properly marshal this call...

Would it please be possible to document this behavior somewhere on the page for MarshalByRefObject or any other Remoting documentation?

**Comment by Nefarion** [comment]
I still think it would be good to mention somewhere in the docs that **ALL** remoting samples using MarshalByRef (in their current form) do not work for .net48 x64 projects , and require the virtual keyword on members.

I agree that it is an implementation detail, but it is a detail that breaks functionality/samples unexpectedly.

The explanation @jkotas added is great, but without in-depth knowledge that this assembly-load timing can be influenced, it does not fix the users/developers problem.

**Comment by jkotas** [comment]
>  ALL remoting samples using MarshalByRef (in their current form) do not work for .net48 x64 projects

Where are these samples?

**Comment by Nefarion** [comment]
These are the ones i found immediately:
https://docs.microsoft.com/en-us/dotnet/api/system.marshalbyrefobject?view=netframework-4.8#examples
https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.createinstanceandunwrap?view=netframework-4.8 (the example for the first overload is the same as in the previous link)

**Comment by jkotas** [comment]
The sample works just fine as is. 

The virtual keyword would be only needed if the sample is split into multiple assemblies, and the code made fragile assumptions about when and whether runtime loads static dependencies.
