### ISSUE TITLE
dotnet is not installing

### ISSUE THREAD

**Issue by K0NSTANT1N3** [dotnet/core#6844]
###  Hello

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My wish is to use **_VS Code_** as **_C#_** editor for Unity. For this I need to install **_dotnet_**  properly. On my way downloading it i faced a problem.

I have problem in using **_C#_** code in _**VS Code**_ for _**Unity**_. my _**VS Code**_ editor shows errors like        

> The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path

 and           

> Some projects have trouble loading. Please review the output for more details

**Comment by JoeRobich** [comment]
@eerhardt You are right that this issue usually indicated that the dotnet folder isn't part of the PATH environment variable. The C# extension and OmniSharp don't perform any path probing and simply rely on it being available.
