### ISSUE TITLE
hostfxr.dll could not be loaded

### ISSUE THREAD

**Issue by Debysonbg** [dotnet/core#6848]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows
Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\5.0.11\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\5.0.11\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by vitek-karas** [comment]
What program are you trying to run?

The URL points to trying to run `dotnet --info` - is that the command which is failing for you?
