### ISSUE TITLE
when i run the first Command it says in red creating this template will make changes to existing files

### ISSUE THREAD

**Issue by Madazahatter666** [dotnet/core#6849]
when i run dotnet new console -o myApp ir pops up in red and says :                  Creating this template will make changes to existing files:                                   Overwrite ./myApp.csproj
Overwrite   ./Program.cs 
Rerun the command and pass --force to accept and create

I have no idea what any of that means also what I'm trying to do is get  .NET working so i can use my ps4 controller on my window's pc but when I try to get ds4window running it pops up saying to run this application you must install .NET would you like to download it now? and every time I install a .NET installer run it it still says I need to install no matter how many times I go through it 

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you paste a screenshot of the pop up you're getting as well?
