### ISSUE TITLE
Can .net core 2.0 project be opened by VS 2015 ？

### ISSUE THREAD

**Issue by fuquanli** [dotnet/core#685]
Visual Studio is Community 2015,version is 14.0.25431.01 Update 3.
![image](https://user-images.githubusercontent.com/25790404/27076289-6239925c-505f-11e7-9731-1eee15eae50c.png)
I have already installed .NET Core 2.0 Preview 1

**Comment by AdrienTorris** [comment]
I don't think so. The project file is different between .NET Core 1.x and .NET Core 2.0. Every communication from Microsoft about the preview of .NET Core 2.0 mentions Visual Studio 2017, so I think it's highly recommanded to use Visual Studio 2017 to work with .NET Core 2.0.

**Comment by fuquanli** [comment]
OK，thank you！
