### ISSUE TITLE
I get an "error with code 1"

### ISSUE THREAD

**Issue by FrancescoT98** [dotnet/core#6851]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

I was just following the instructions and then, when it was supposed to finish the app, i get this message: 

"watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet..."

Over this message, there's another one that tells me that compilation could not be done and that I have to fix the mistakes and execute the proyect again

**Comment by mairaw** [comment]
Can you show what are the errors that caused the compilation not to be done?
