### ISSUE TITLE
im having using the free checking printing 

### ISSUE THREAD

**Issue by soft1197** [dotnet/core#6852]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

'dotnet' is not recognized as an internal or external command,
operable program or batch file. on window 7,  <  dotnet  comand

**Comment by mairaw** [comment]
This tutorial is for you to learn how to code. Is this really what you intended? Can you better describe the issue?
