### ISSUE TITLE
the namespace 'myApp' already contains a definition for 'Program'

### ISSUE THREAD

**Issue by diliboy88** [dotnet/core#6856]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You probably ran the command twice and dotnet is telling you that it already exists. You can either pass --force to overwrite the existing project, or delete the folder and start over. Let us know if this helps.

**Comment by diliboy88** [comment]
thanks
