### ISSUE TITLE
Add some doc for NETStandard.Library.NETFramework to relnote of NetCore2.0 P1 ?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/core#686]
App reference NS 2.0P1 libraries complie success but can't run without the package in net461+. But there is no doc for the packages, and can't found any description in relnote of NetCore2.0 P1. 
Or will the package be autoreference by future NuGet?

**Comment by karelz** [comment]
@ericstj @weshaggard what is the story here?

**Comment by ericstj** [comment]
Package is being put into the tooling.  See https://github.com/dotnet/sdk/issues/1288.

**Comment by karelz** [comment]
What does it mean for dev scenario and app deployment scenario?
Can we add relnote for Preview 1 / Preview 2? (assuming it is not fixed in either)

**Comment by ericstj** [comment]
In any scenario you need to add support for netstandard2.0 to desktop since it wasn't something that was inbox.  This is done by passing additional libraries to the compiler and redistributing a version of those with the app.

A Preview 1 rel note could say to add a reference to the NETStandard.Library.NETFramework package from any desktop app referencing a netstandard library.

The work to automate the support library addition is being done for preview2, but some of that work is still in progress (/cc @dsplaisted).

**Comment by Petermarcu** [comment]
@richlander @leecow do you want to add a rel note for preview 1 at this point? If not, we should just close this as fixed in Preview 2.

**Comment by leecow** [comment]
Post the relevant text for Preview 1 and I can amend those notes.

**Comment by Petermarcu** [comment]
@ericstj , can you give @leecow the exact text that should be in the rel note?

**Comment by ericstj** [comment]
"When referencing a NETStandard2.0 library from a .NETFramework application you must add a reference to the NETStandard.Library.NETFramework package to the .NETFramework project."

**Comment by leecow** [comment]
Thanks @ericstj - is there an issue number which I could also reference or is this just a configuration heads-up?

**Comment by ericstj** [comment]
That's just work that hadn't been completed at the time we shipped Preview1.  You could reference https://github.com/dotnet/sdk/issues/1267 if you'd like.  There are probably earlier issues that were tracking the work prior to preview1, but this is the one I opened to represent the final form.

**Comment by richlander** [comment]
@terrajobst - can you create announcements at dotnet/announcement for the following changes:

- The creation of this NuGet package and the associated scenarios.
- The removal of NETStandard.Library as NuGet dependencies.

These are pretty unrelated topics but contribute to the same scenario. I am sure folks would appreciate more info on both.

**Comment by Petermarcu** [comment]
@terrajobst , did this happen? Can we close this issue now?

**Comment by terrajobst** [comment]
No, it hasn't yet. I'll publish them next week, together with a blog post.

**Comment by Petermarcu** [comment]
@terrajobst did this happen? Can we close this issue out?

**Comment by terrajobst** [comment]
No, sadly not yet.

**Comment by Petermarcu** [comment]
@terrajobst any update?

**Comment by Petermarcu** [comment]
@terrajobst should we just close this issue?

**Comment by Petermarcu** [comment]
@terrajobst what should we do with this issue? Its been open now for months and I'd like to have it closed either because nothing is going to happen or something has happened.

**Comment by terrajobst** [comment]
We basically have published guidance in various forms now (blog posts, videos, etc).
