### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by muneerah1418** [dotnet/core#6860]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you provide more information about the issue? When do you get this error?

**Comment by muneerah1418** [comment]
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/5.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on myWebApp3\myWebApp3.csproj...
  Determining projects to restore...
  Restored C:\Users\admin\myWebApp3\myWebApp3.csproj (in 682 ms).

**Comment by eerhardt** [comment]
It looks like you were successful. What was the error you got? I'm not seeing it in your above posts.
