### ISSUE TITLE
The <#text> element under the <Project> element is not recognized. Compilation failed. Fix the compile errors and run again.

### ISSUE THREAD

**Issue by newmember0** [dotnet/core#6864]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by eerhardt** [comment]
Can you add the contents of your `.csproj` file is? It looks like it has been corrupted.

Try deleting the `.csproj` file and the `Program.cs` file and re-run the `dotnet new console` command again.
