### ISSUE TITLE
Не удалось найти файл проекта MsBuild

### ISSUE THREAD

**Issue by danyagluhov35** [dotnet/core#6868]
Следовал строго инструкциям на сайте https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
После того как дошел до главы "Запустите ваше приложение" или на английском "Run your app" выскакивает вот такая вот ошибка: 
![image](https://user-images.githubusercontent.com/76007580/140206595-32b94ec8-a239-4fa6-aa4b-43d3c9720192.png)
Не подскажите мне, что делать?

**Comment by eerhardt** [comment]
@danyagluhov35 - did you run both commands in the `Create your app` section?

```
dotnet new webApp -o myWebApp --no-https
```

AND

```
cd myWebApp
```

`dotnet watch run` needs to be run from inside the folder that contains the `myWebApp.csproj` file.

**Comment by danyagluhov35** [comment]
Oh, it helped, thank you.  I've been neglectful :(
