### ISSUE TITLE
The build failed. Fix the build errors and run again.

### ISSUE THREAD

**Issue by XxRedBlackxX** [dotnet/core#6869]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The build failed. Fix the build errors and run again.

Error above occurs when trying to run the console app tutorial for dotnet. 
When typing dotnet run this shows errors and says to fix the sdk's.
Yes it is a fresh install of dotnet.

**Comment by mairaw** [comment]
What build errors did you have?

**Comment by XxRedBlackxX** [comment]
> What build errors did you have?

Alot of SDK errors along with the error mentioned above. Ill try to attach a screenshot.

**Comment by mairaw** [comment]
Either a copy of the entire error message or a screenshot would be great!
