### ISSUE TITLE
Problem With Blazor Tutorial

### ISSUE THREAD

**Issue by jflynn12** [dotnet/core#6870]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows  11

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\John-PC>dotnet new blazorserver -o BlazorApp --no-https
Creating this template will make changes to existing files:
  Overwrite   ./App.razor
  Overwrite   ./appsettings.Development.json
  Overwrite   ./appsettings.json
  Overwrite   ./BlazorApp.csproj
  Overwrite   ./Program.cs
  Overwrite   ./Startup.cs
  Overwrite   ./_Imports.razor
  Overwrite   ./Data/WeatherForecast.cs
  Overwrite   ./Data/WeatherForecastService.cs
  Overwrite   ./Pages/Counter.razor
  Overwrite   ./Pages/Error.cshtml
  Overwrite   ./Pages/Error.cshtml.cs
  Overwrite   ./Pages/FetchData.razor
  Overwrite   ./Pages/Index.razor
  Overwrite   ./Pages/_Host.cshtml
  Overwrite   ./Properties/launchSettings.json
  Overwrite   ./Shared/MainLayout.razor
  Overwrite   ./Shared/MainLayout.razor.css
  Overwrite   ./Shared/NavMenu.razor
  Overwrite   ./Shared/NavMenu.razor.css
  Overwrite   ./Shared/SurveyPrompt.razor
  Overwrite   ./wwwroot/favicon.ico
  Overwrite   ./wwwroot/css/site.css
  Overwrite   ./wwwroot/css/bootstrap/bootstrap.min.css
  Overwrite   ./wwwroot/css/bootstrap/bootstrap.min.css.map
  Overwrite   ./wwwroot/css/open-iconic/FONT-LICENSE
  Overwrite   ./wwwroot/css/open-iconic/ICON-LICENSE
  Overwrite   ./wwwroot/css/open-iconic/README.md
  Overwrite   ./wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  Overwrite   ./wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  Overwrite   ./wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  Overwrite   ./wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  Overwrite   ./wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  Overwrite   ./wwwroot/css/open-iconic/font/fonts/open-iconic.woff

Rerun the command and pass --force to accept and create.

**Comment by eerhardt** [comment]
It looks like you have already run this command. It is complaining that the files already exist.

To fix this, you can either:

1. Delete the folder `C:\Users\John-PC\BlazorApp` and run the command again
2. Run the command again, but change `-o BlazorApp` to `-o BlazorApp2`, which will put it in a different folder.
3. Run the command again, but also pass `--force` at the end, which will overwrite the existing files.
