### ISSUE TITLE
Problem With Blazor Tutoral

### ISSUE THREAD

**Issue by jflynn12** [dotnet/core#6873]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: windows 11

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am trying the Add A Component step and getting an Internal Sever error. Here is how I changed Index.razor. I must have done something wrong.

```
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<Counter /> 
```

```
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<Counter />
```

**Comment by mairaw** [comment]
The code looks correct. @danroth27 what would you suggest here?

**Comment by danroth27** [comment]
Hi @jflynn12 An Internal Server Error indicates something went wrong on the server.  Typically the error will show up in the console output of the running app, so check there for details on the error so that we can help troubleshoot. 

Did you maybe accidentally run the app a second time while it was already running? That would result in a port conflict error.

**Comment by jflynn12** [comment]
This is what showed up on the console output.

An unhandled exception occurred while processing the request.

InvalidOperationException: The following routes are ambiguous:
'/' in 'BlazorApp.Pages.Index'
'/' in 'BlazorApp.Pages.Index'

Microsoft.AspNetCore.Components.RouteTableFactory.RouteComparison(RouteEntry x, RouteEntry y)

InvalidOperationException: Failed to compare two elements in the array.

System.Collections.Generic.ArraySortHelper<T>.Sort(Span<T> keys, Comparison<T> comparer)

*       Stack 

*       Query 

*       Cookies 

*       Headers 

*       Routing

*	InvalidOperationException: The following routes are ambiguous: '/' in 'BlazorApp.Pages.Index' '/' in 'BlazorApp.Pages.Index'

o    Microsoft.AspNetCore.Components.RouteTableFactory.RouteComparison(RouteEntry x, RouteEntry y)

o    System.Collections.Generic.ComparisonComparer<T>.Compare(T x, T y)

o    System.Linq.EnumerableSorter<TElement, TKey>.CompareAnyKeys(int index1, int index2)

o    System.Collections.Generic.ArraySortHelper<T>.InsertionSort(Span<T> keys, Comparison<T> comparer)

o    System.Collections.Generic.ArraySortHelper<T>.IntroSort(Span<T> keys, int depthLimit, Comparison<T> comparer)

o    System.Collections.Generic.ArraySortHelper<T>.IntrospectiveSort(Span<T> keys, Comparison<T> comparer)

o    System.Collections.Generic.ArraySortHelper<T>.Sort(Span<T> keys, Comparison<T> comparer)

*	 

Show raw exception details

*	InvalidOperationException: Failed to compare two elements in the array.

o    System.Collections.Generic.ArraySortHelper<T>.Sort(Span<T> keys, Comparison<T> comparer)

o    System.MemoryExtensions.Sort<T>(Span<T> span, Comparison<T> comparison)

o    System.Linq.EnumerableSorter<TElement, TKey>.QuickSort(int[] keys, int lo, int hi)

o    System.Linq.EnumerableSorter<TElement>.Sort(TElement[] elements, int count)

o    System.Linq.OrderedEnumerable<TElement>.ToArray()

o    System.Linq.Enumerable.ToArray<TSource>(IEnumerable<TSource> source)

o    Microsoft.AspNetCore.Components.RouteTableFactory.Create(Dictionary<Type, string[]> templatesByHandler)

o    Microsoft.AspNetCore.Components.RouteTableFactory.Create(IEnumerable<Type> componentTypes)

o    Microsoft.AspNetCore.Components.RouteTableFactory.Create(IEnumerable<Assembly> assemblies)

o    Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()

o    Microsoft.AspNetCore.Components.Routing.Router.Refresh(bool isNavigationIntercepted)

o    Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)

o    Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)

o    Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)

o    Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(ref DiffContext diffContext, int frameIndex)

o    Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(ref DiffContext diffContext, int frameIndex)

o    Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)

o    Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)

o    Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, int componentId, ArrayRange<RenderTreeFrame> oldTree, ArrayRange<RenderTreeFrame> newTree)

o    Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

o    Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(int componentId, RenderFragment renderFragment)

o    Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()

o    Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()

o    Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

o    Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)

o    Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)

o    Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(int componentId, ParameterView initialParameters)

o    Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)

o    Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)

o    Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c__11<TResult>+<<InvokeAsync>b__11_0>d.MoveNext()

o    Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)

o    Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)

o    Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, object parameters)

o    Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)

o    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)

o    BlazorApp.Pages.Pages__Host.<ExecuteAsync>b__14_1() in _Host.cshtml

+

20.     <component type="typeof(App)" render-mode="ServerPrerendered" />

o    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()

o    BlazorApp.Pages.Pages__Host.ExecuteAsync() in _Host.cshtml

+

5.      Layout = null;

o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)

o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)

o    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)

o    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

o    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

o    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

*	 

Show raw exception details

**Comment by danroth27** [comment]
@jflynn12 That error means you somehow ended up with two pages with the same route. Do you have multiple .razor files with `@page "/"` in your project?

**Comment by jflynn12** [comment]
Yes. This was my fault. I was copying more than just the highlighted code when I clicked on “copy” at the upper right corner of the code example.

 

Thanks

**Comment by danroth27** [comment]
Awesome, I'm glad you got it working! Thanks for trying out Blazor!
