### ISSUE TITLE
Docker daemon not starting on windows after installing it

### ISSUE THREAD

**Issue by sachithsujeewa** [dotnet/core#6875]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

It gives me an error
This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.

In order to fix this issue, I had to install 
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by mairaw** [comment]
Some issues that folks run into are specific Docker issues. @shirhatti @nishanil can you help here?
