### ISSUE TITLE
Creating this template will make changes to existing files:   Overwrite   ./myApp.csproj   Overwrite   ./Program.cs  Rerun the command and pass --force to accept and create.

### ISSUE THREAD

**Issue by MynamesRuben** [dotnet/core#6876]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
This means you already created the project once.

There are a couple of ways to go about it:
- You can simply continue the tutorial
- You can delete the myApp folder and start over
- You can pass the `--force` option

**Comment by eerhardt** [comment]
@mairaw - this seems to be a very common problem with the tutorials. In the past 2 weeks I have seen it reported at least 4 times. Is there something we can change on the tutorial to help here?

**Comment by mairaw** [comment]
I can add in the Got an error section for now.
