### ISSUE TITLE
.NET November 2021 Update - .NET 5.0.12 and .NET Core 3.1.21

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/core#6884]
Release Notes 
[5.0.12](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.12/5.0.12.md)
[3.1.21](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.21/3.1.21.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.12 | 3.1.21
|--|--|--
| Ubuntu 16.04   | ✅  | ✅ |
| Ubuntu 18.04   | ✅  | ✅ |
| Ubuntu 20.04   | ✅  | ✅ |
| Ubuntu 20.10    | ✅  | ✅ |
| Ubuntu 21.04     | ✅  | ✅ |
| Centos 7     | ✅  | ✅ |
| Centos 8     | ✅  | ✅ |
| Debian 9    | ✅  | ✅ |
| Debian 10    | ✅  | ✅ |
| Debian 11  | ✅  | ✅ |
| Fedora 33   | ✅  | ✅ |
| Fedora 34  | ✅  | ✅ |
| OpenSUSE 15   | ✅  | ✅ |
| SLES 12   | ✅  | ✅ |
| SLES15  | ✅  | ✅ |

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by scrouchman-livedrive** [comment]
Has anything changed with the package install on centos? Our new hosts that get 3.1.21 do not have a symlink in /usr/bin/dotnet whereas our older hosts with 3.1.20 do have that symlink

**Comment by jantzenc** [comment]
I came here with the same question left by scrouchman-livedrive.  I have found no mention of this in the release, but the symlink has moved to /usr/local/bin/dotnet.

**Comment by Yanz-dotcom** [comment]
> ``
[Uploading core-6.0.0.zip…]()

**Comment by vanashimko** [comment]
Encountered an issue with self-contained publish with **rhel.6-x64** RID. There are no **3.1.21** versions for `Microsoft.NETCore.App.Runtime.rhel.6-x64` and `Microsoft.NETCore.App.Host.rhel.6-x64` packages and it cause build failure:

```
error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.rhel.6-x64 with version (= 3.1.21) 
error NU1102:   - Found 32 version(s) in NuGet.org [ Nearest version: 3.1.20 ]
error NU1102: Unable to find package Microsoft.NETCore.App.Host.rhel.6-x64 with version (= 3.1.21)
error NU1102:   - Found 34 version(s) in NuGet.org [ Nearest version: 3.1.20 ]
```

**Comment by paul-777** [comment]
As mentioned above installing VS2022 has broken the build even in VS2019 - so not really side-by-side then.
Error is:
Unable to find package Microsoft.NETCore.App.Runtime.rhel.6-x64 with version (= 3.1.21) 
Is this package version going to be released onto Nuget?

**Comment by kalaskarsanket** [comment]
Closing this issue in favor of new issue https://github.com/dotnet/core/issues/703

**Comment by paul-777** [comment]
> Closing this issue in favor of new issue #703

Issue 703 appears to be an old an unrelated issue?

**Comment by kalaskarsanket** [comment]
> > Closing this issue in favor of new issue #703
> 
> Issue 703 appears to be an old an unrelated issue?

You are correct, the correct issue is updated to https://github.com/dotnet/core/issues/7036
