### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by DavidVanPluto** [dotnet/core#6886]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run#
Operating System: windows

The text: In your command prompt, run the following command: 'dotnet watch' 

should be updated to read 'dotnet watch run'

**Comment by eerhardt** [comment]
@mairaw @pranavkm - thoughts? Should the command be updated to `dotnet watch run`?

**Comment by pranavkm** [comment]
@DavidVanPluto could you list the results of running `dotnet --info`? Starting in .NET 6, `dotnet watch` is an alias for `dotnet watch run`, so I would expect it to work if you're using the 6.0 SDK that was released today: https://get.dot.net

**Comment by mairaw** [comment]
We made changes to the tutorial this morning but the first step is to install .NET 6 SDK.

There are a couple of ways we can go about this: /cc @danroth27 
1. We explicitly call out the version on the install page
2. We add a step to verify you're running on the latest/expected SDK
3. On the create step, we add the framework option so if you don't have 6 installed, you get an error

Maybe step 1 is enough?
