### ISSUE TITLE
Can't find any installed SDKs after update to .NET 6

### ISSUE THREAD

**Issue by PeterDraex** [dotnet/core#6889]
### Description

I've updated Visual Studio to 17.1.0 Preview 1.0, and I assume with that, my .NET version was updated to stable version of .NET 6 (previously, I had Release Candidate installed). Now, I can't run any dotnet sdk commands like `dotnet new tool-manifest`. It shows me the following error:
```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

When I run `dotnet --list-sdks`, the command gives no output.
When I run `where dotnet`, the command gives no output.

I've tried restarting the command prompt, restarting the computer, downloading the SDK from website and installing it manually - same behavior. Compilation in Visual Studio runs OK. 

### Configuration

* Which version of .NET is the code running on? 6.0
* What OS and version, and for Linux, what distro? Windows 11
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I don't know

### Regression?

dotnet SDK commands worked with a preview build of .NET 6 without issues, I think even with the version immediately preceding the stable version.

**Comment by mairaw** [comment]
You're probably hitting this known issue: https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows

Check the output of `where.exe dotnet` and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue

**Comment by PeterDraex** [comment]
Thanks @mairaw. Yes the issue was with PATH and it works now!
Btw can I ask what's the difference between running `where dotnet` and `where.exe dotnet`? The first one prints no output, while the second one works correctly.

**Comment by mairaw** [comment]
It seems the command where (without the .exe) is aliased to Where-Object in PowerShell (https://superuser.com/a/677731)

Since your issue is now fixed, I'll close this issue.

**Comment by hugoohlavrac** [comment]
When I write `dotnet --info`  in Command Prompt, I get this result:
```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```
When I write `where.exe dotnet` in Command Prompt, I get this result:
```
C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe
```

However, when I go to the path settings, there are no `C:\Program Files\dotnet\` or `C:\Program Files (x86)\dotnet\`. There is only `%USERPROFILE%\.dotnet\tools`. Does anybody know how can i fix it and make SDK work?
