### ISSUE TITLE
What is the alternative to get the HttpContext.Current in .net core ?

### ISSUE THREAD

**Issue by synckarthik** [dotnet/core#689]
Any one can suggest how to use the HttpContext.Current in .net core ?

**Comment by h3smith** [comment]
In what context? There are several ways to get it - you can't grab it statically anymore.

**Comment by ukphillips** [comment]
The correct (and only) way to really do this is to inject the HttpContextAccessor into the class or service you want to use it in.

**Comment by Petermarcu** [comment]
This issue is probably better to open on the aspnet/home repo where more people that know the details of HttpContext would be watching.

**Comment by Petermarcu** [comment]
@Eilon do you know who could help here?

**Comment by ukphillips** [comment]
This should be able to get you in the right direction. https://www.strathweb.com/2016/12/accessing-httpcontext-outside-of-framework-components-in-asp-net-core/

**Comment by Eilon** [comment]
That linked blog post has the answer. However, in general we don't recommend using that pattern at all. Any component that needs to know the current HttpContext needs to have the HttpContext passed to it - the same as you would do for any other piece of data that the component needs.

**Comment by richlander** [comment]
Please continue the conversation on the aspnet/home repo if you need more information. Thanks.

**Comment by naveedahmed1** [comment]
@Eilon so for the sake of clarity, suppose we have a repository class, that neesd access to HttpContext.Current , we would first inject HttpContextAccessor  in the controller calling that class, and then pass reference to context to the class from controller correct?

**Comment by Eilon** [comment]
@naveedahmed1 yes that sounds like it would work. However, I think in common/popular app architectures a "repository" class generally doesn't need access to `HttpContext.Current`. There would usually be some other app/scenario-specific interface that you'd create that the "repository" would depend on, and the implementation of that interface would use something like `IHttpContextAccessor` to get the data it needs. But both ways should work.

**Comment by naveedahmed1** [comment]
Thank you so much @Eilon for quick reply, sorry I meant a utility class but got your point.
