### ISSUE TITLE
[Documentation] Visual C++ Redistributable for Visual Studio 2015 link is invalid

### ISSUE THREAD

**Issue by MihaiTheCoder** [dotnet/core#690]
Thanks for your interest in .NET Core. 

https://github.com/dotnet/core/blob/master/Documentation/prereqs.md has a broke link to Visual C++ Redistributable for Visual Studio 2015

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

**Comment by Petermarcu** [comment]
Thanks. I've sent some emails around asking for the right link to use.

**Comment by Petermarcu** [comment]
Fixed with https://github.com/dotnet/core/commit/414505918e3c9dbf46def941bf84aa8b2eb629e3
