### ISSUE TITLE
Hash mismatch for `debian-strech` file `dotnet-sdk-5.0.202-x64.deb` on packages.microsoft.com

### ISSUE THREAD

**Issue by michael-schaller** [dotnet/core#6904]
Our mirror-in of the `microsoft-debian-stretch-prod` repo on packages.microsoft.com fails with a hash mismatch of the `pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb` file. This issue started some time between 2021-11-09 00:02:30 UTC and 2021-11-10 06:16:10 UTC. 

I'm opening a bug here as I have no clue where else to report this issue. It would be great if packages.microsoft.com would contain a file with contact information.

### Reproduction instructions:

Let's check what SHA-256 hash the file should have according to the package index:

```
$ curl -s https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/dists/stretch/main/binary-amd64/Packages.gz | zgrep -C9 'Filename: .*/dotnet-sdk-5.0.202-x64.deb'

Package: dotnet-sdk-5.0
Priority: standard
Section: devel
Installed-Size: 222041
Maintainer: Microsoft <dotnetcore@microsoft.com>
Architecture: amd64
Version: 5.0.202-1
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libstdc++6 (>= 4.4.0), dotnet-runtime-5.0 (>= 5.0.5), netstandard-targeting-pack-2.1 (>= 2.1.0), aspnetcore-runtime-5.0 (>= 5.0.5), dotnet-targeting-pack-5.0 (>= 5.0.0), aspnetcore-targeting-pack-5.0 (>= 5.0.0), dotnet-apphost-pack-5.0 (>= 5.0.5)
Filename: pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb
Size: 57105162
MD5sum: 8c762eace12a55940a48779b274aa724
SHA1: 424e8a01467993046a4c3e9c24ef1ec93d6ffaf8
SHA256: d335eb918ad93d8d42090955e7859710a56279e3bbe3261ae387a40cb39d33c9
SHA512: 0a9ede2ed4f25f2d79700a2930553db22f891186f75969ad37ed55ea42c9bd2cf266959f600e0cc0288685e4b3a65a2b72905e75e770089f2dc76e238ecf3f14
Description: Microsoft .NET SDK 5.0.202
 .NET is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/core). We happily accept issues and PRs.
Homepage: https://dotnet.github.io/core

```

So the expected SHA-256 hash of the file `pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb` is `d335eb918ad93d8d42090955e7859710a56279e3bbe3261ae387a40cb39d33c9` according to the Package index.

However the file in question has the SHA-256 hash `7612ea0058043ef44665071f0360de87856353141e427390ee7181e219062ae5`:

```
$ curl -s https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb | sha256sum
7612ea0058043ef44665071f0360de87856353141e427390ee7181e219062ae5  -
```

https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/pool/main/d/dotnet-sdk-5.0/ indicates that the file `dotnet-sdk-5.0.202-x64.deb` was last changed on 06-May-2021 17:01. So maybe the package index is faulty.

**Comment by SusLes** [comment]
@leecow @vseanreesermsft

**Comment by leecow** [comment]
Behavior confirmed and yes, I would also suspect an index issue. I suspect it will be easier to republish the affected version which should force an update to the index.

**Comment by leecow** [comment]
Looks like that took care of it: 

```
root@005c180724ab:/SOURCE# curl -s https://packages.microsoft.com/debian/9/prod/pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb | sha256sum
7612ea0058043ef44665071f0360de87856353141e427390ee7181e219062ae5  -
root@005c180724ab:/SOURCE# curl -s https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/dists/stretch/main/binary-amd64/Packages.gz | zgrep -C9 'Filename: .*/dotnet-sdk-5.0.202-x64.deb'

Package: dotnet-sdk-5.0
Priority: standard
Section: devel
Installed-Size: 222041
Maintainer: Microsoft <dotnetcore@microsoft.com>
Architecture: amd64
Version: 5.0.202-1
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libstdc++6 (>= 4.4.0), dotnet-runtime-5.0 (>= 5.0.5), netstandard-targeting-pack-2.1 (>= 2.1.0), aspnetcore-runtime-5.0 (>= 5.0.5), dotnet-targeting-pack-5.0 (>= 5.0.0), aspnetcore-targeting-pack-5.0 (>= 5.0.0), dotnet-apphost-pack-5.0 (>= 5.0.5)
Filename: pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb
Size: 57105162
MD5sum: 15f9aae6f0633d7608ca85969b9c6d05
SHA1: cdb68858bcdcfe5bf7bcc0f732d445b236df2a07
SHA256: 7612ea0058043ef44665071f0360de87856353141e427390ee7181e219062ae5
SHA512: 4df75daabd44772ffe099ffe2d96b482f90b1895641f0a85c172e9238d2024dd577b8873c40578e30f066b1a768b5c6eb7b43c81767114f9e5c6ce9646af38de
Description: Microsoft .NET SDK 5.0.202
 .NET is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/core). We happily accept issues and PRs.
Homepage: https://dotnet.github.io/core
```

**Comment by michael-schaller** [comment]
Thanks for the quick fix, Lee.

What about my other request?
Quote: `It would be great if packages.microsoft.com would contain a file with contact information.`

IMHO it would be really helpful if there would be a http://packages.microsoft.com/contact.txt (or similar) that explains how to report issues. I just happened to find a similar older bug and also filed a bug here...

**Comment by Vitexus** [comment]
:(  2021-12-12 14:23:58.799686:

 "gpgv: Signature made Fri Dec 10 19:49:09 2021 CET using RSA key ID BE1229CF",
        "gpgv: Good signature from \"Microsoft (Release signing) <gpgsecurity@microsoft.com>\"",
        "ERROR: unable to update: download errors:",
        "  https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-sdk-5.0/dotnet-sdk-5.0.202-x64.deb: md5 hash mismatch \"15f9aae6f0633d7608ca85969b9c6d05\" != \"8c762eace12a55940a48779b274aa724\"",
        "  https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msft-identity-broker/msft-identity-broker_1.0.0~alpha01_all.deb: md5 hash mismatch \"361f40f49e84ef3f677b9e3f0672b5e3\" != \"c8f3f9d52d97bfaf1e63ec8e0b8efec7\""
