### ISSUE TITLE
Drop "Core"

### ISSUE THREAD

**Issue by Varorbc** [dotnet/core#6910]
There are still many words ".Net Core" in documents, and ".Net" should be used instead

**Comment by mairaw** [comment]
We've been trying to clear up, although in some cases using .NET Core is still applicable. Do you have any examples? Are you referring to this repo, the dot.net website, docs?

**Comment by Varorbc** [comment]
I made a simple fix. If there is no problem, I can open a pull request, there may be more "Core" to be dropped
