### ISSUE TITLE
The build failed

### ISSUE THREAD

**Issue by selinacarreto** [dotnet/core#6911]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
[Document.txt](https://github.com/dotnet/core/files/7529118/Document.txt)

**Comment by mairaw** [comment]
What is your SDK version? Can you share what is the output of `dotnet --info`?
