### ISSUE TITLE
Method with Params, changes receiving data types

### ISSUE THREAD

**Issue by deadmann** [dotnet/core#6914]
When I use params in a method, the receiver method receive a list of data, that's what we all know and works fine.
The issue is when I send Nullable data, like long? x to the param, if it is null, it remain null of gods known what type, and if I send 5, I get 5 of type long (Non nullable)... the data change its type when it reaches the calling method... and I'm not sure if we had it in .Net Framwork, or in newer .Net Core or .Net, but I faced this issue in .Net 3.1 .

my method signature....

```public static bool CheckIfOnlyOneItemHasValue(params object[] values)  { ... }```

How I call it:

```if (StaticMethod.CheckIfOnlyOneItemHasValue(model.ProductTzp, model.ProductId, model.ProductPriceId))```

```
public class AddProductToCartRequestVm_Api
    {
        public string ProductTzp { get; set; }
        public long? ProductId { get; set; }
        public long? ProductPriceId { get; set; }
        
        public int Quantity { get; set; }
    }
```

**Comment by eiriktsarpalis** [comment]
You mean this behavior?
```C#
long? x = null;
long? y = 42;

object[] array = CheckIfOnlyOneItemHasValue(x, y);
array[0].GetType(); // NRE
array[1].GetType(); // long

static object[] CheckIfOnlyOneItemHasValue(params object[] values) => values;
```
This is by design, information on nullable types is lost when upcasting to `object`. I can't provide any recommendations here because I don't know `CheckIfOnlyOneItemHasValue` is meant to do. If I wrote it like the name suggests it would look like
```C#
static bool CheckIfOnlyOneItemHasValue(params object[] values)
{
    return values.Where(value => value != null).Count() == 1;
}
```
But that clearly doesn't suffer from the problem you're describing.
