### ISSUE TITLE
Windows.Storage and Windows.Web.Http unavailable after upgrade to .net 6

### ISSUE THREAD

**Issue by tinmac** [dotnet/core#6917]
WinUi 3 in Desktop project running net5.0-windows10.0.19041.0 working.

After upgrading to .net 6, build fails

- Windows.Storage
- Windows.Web.Http

![image](https://user-images.githubusercontent.com/6616946/141729192-ffd07c71-338e-4c1f-a01b-e507a928fee8.png)

![image](https://user-images.githubusercontent.com/6616946/141729281-9dd9a73c-034a-4355-903d-08e1bf00e9ad.png)

![image](https://user-images.githubusercontent.com/6616946/141729374-c00709bd-ffeb-4372-a836-bc530256d6ea.png)

csproj
![image](https://user-images.githubusercontent.com/6616946/141729650-f003a6f1-5303-4b08-b358-fb9b593c4ae4.png)

**Comment by eiriktsarpalis** [comment]
Hi @tinmac, UWP issues are tracked via Visual Studio dev community. If you are running into .NET native issues, please use https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options.
