### ISSUE TITLE
IntelliSense confused by Action<> overloads

### ISSUE THREAD

**Issue by datvm** [dotnet/core#6918]
### Description

I was trying to create a Windows Service in .NET 6 following [this documentation](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service).

I want to read the settings from `appsettings.json` so I added the following code:

```
IHost host = Host.CreateDefaultBuilder(args)
    .UseWindowsService(options =>
    {
        options.ServiceName = "My Service";
    })
    .ConfigureServices(services =>
    {
        var settings = new ScriptOptions(); // ScriptOptions is just a POCO class
        services.Configuration.Bind(settings);

        services.AddHostedService<WindowsBackgroundService>();
    })
    .Build();
```

As you can see, IntelliSense seems to recognize there is `Configuration` property in `services` (instance of `IServiceCollection` instead of `HostBuilderContext`).

![image](https://user-images.githubusercontent.com/6388546/141749318-78715711-6c8a-49ca-a6f9-a0ec81d10d7c.png)

However the code wouldn't compile because [IServiceCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection?view=dotnet-plat-ext-5.0) does NOT have `Configuration` property, but [HostBuilderContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuildercontext?view=dotnet-plat-ext-5.0) does.

I realized `ConfigureServices` method has 2 overload (actually there is one, the other is extension method):

```
// Default Method
IHostBuilder ConfigureServices(Action<HostBuilderContext, IServiceCollection> configureDelegate);

// Extension Method
public static IHostBuilder ConfigureServices(this IHostBuilder hostBuilder, Action<IServiceCollection> configureDelegate)
```

So in the case of using Extension Method, somehow IntelliSense thought `services` is `HostBuilderContext`.

Note: I already fixed my problem, just want to report strange behavior of IntelliSense that made me spend a lot of time figuring out why my code couldn't compile. Here's the fix if anyone is interested:

```
    // Add ctx parameter
    .ConfigureServices((ctx, services) =>
    {
        var settings = new ScriptOptions();
        ctx.Configuration.Bind(settings);

        services.AddHostedService<WindowsBackgroundService>();
    })
```

### Configuration

* Which version of .NET is the code running on? 6.0
* What OS and version, and for Linux, what distro? Windows 11 Pro
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I am not sure, probably not
* If you're using Blazor, which web browser(s) do you see this issue in? None

### Regression?

I don't know

### Other information

Microsoft Visual Studio Community 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

**Comment by eiriktsarpalis** [comment]
cc @mairaw

**Comment by mairaw** [comment]
This is not related to the tutorials but instead it's an IntelliSense issue. @jaredpar @terrajobst would you know who can help with this?

**Comment by eiriktsarpalis** [comment]
@datvm would it be possible to share a repo with instructions on how to reproduce the issue? We can try to take a look.

**Comment by datvm** [comment]
@eiriktsarpalis Hi, just create a new project with Worker template and you have the problem immediately in `Program.cs` file:

![image](https://user-images.githubusercontent.com/6388546/142129725-3244b2d9-860d-4f7f-ac03-fae549c56084.png)

[Github Repo](https://github.com/datvm/DemoIntelliSenseProblem) if you still need it.

**Comment by datvm** [comment]
Hi is there any update on this issue? It's still happening today (VS 2022 17.2.3)

![image](https://user-images.githubusercontent.com/6388546/172706657-e51d154f-63fa-44cd-b5d5-e80f0af9b84e.png)

**Comment by mairaw** [comment]
Since this is happening in VS, you might be able to get better support if you file the issue through Visual Studio Help menu.
