### ISSUE TITLE
Blazor template app CS0103 error 

### ISSUE THREAD

**Issue by dommnk** [dotnet/core#6926]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: Windows 10
Visual Studio v16.11.1
.Net SDK 6.0.100 installed

I have come to an issue while trying to create new project using Blazor template in Visual Studio 2019. After creating new Blazor project using template Blazor Server App I get an error at every line which includes '@' mark such as in _Host.cshtml file.

first line: @page "/".

Error CS0103 The name 'page' does not exist in the current context.

This error can be seen in all of .razor files. 
I have tried rebuilding the solution and also unloading and reloading project, nothing changed.
When I press Ctrl + F5 to run the project, everything works as intended. 

[IMPORTANT]
EDIT: I noticed the same error occurs in other provided templates such as ASP.NET Core Web App. I selected Target Framework .NET Core 3.1

![image](https://user-images.githubusercontent.com/73101500/142068532-eb658343-eb6c-4a32-9366-76f4b435a59a.png)

**Comment by mairaw** [comment]
Can you run `dotnet --list-sdks`?  Also, the tutorial has now been updated to use .NET 6 SDK, which would require Visual Studio 2022.

**Comment by dommnk** [comment]
> Can you run `dotnet --list-sdks`? Also, the tutorial has now been updated to use .NET 6 SDK, which would require Visual Studio 2022.
This is the outcome of this command
![image](https://user-images.githubusercontent.com/73101500/142071733-291d7b80-6d84-400a-9ffe-ab4807e01a76.png)

Also the problem occured before version 2022 was available

**Comment by mairaw** [comment]
.NET 6 has had a requirement for VS 2022 Previews for a while now.

But I'm curious if you still have this issue or not. Are you running .NET 6 on VS 2019 or not? It's not going to work if so.

**Comment by dommnk** [comment]
Well I did install .NET 6 Yesterday, so until yesterday I have been using .NET 5. Following your advice I installed VS 2022 and you are right, everything works fine now. I am really happy and appreciate your help since I couldn't find any helpful info about this issue on the internet. Thank you so much.

**Comment by mairaw** [comment]
Happy to heart that! I'm going to close the issue then. But please let us know if you are still having other issues that I might be missing.
