### ISSUE TITLE
Is "release-notes/releases-index.json" supported for automatic download?

### ISSUE THREAD

**Issue by hamarb123** [dotnet/core#6929]
Hi, just wondering if the json files listed in `release-notes/releases-index.json` (and `release-notes/releases-index.json` itself using the link https://raw.githubusercontent.com/dotnet/core/main/release-notes/releases-index.json) are supported for downloading .NET Runtime installer programmatically. I know there is the install-script, but I was looking for something that actually installs it globally.
By supported, I mean that the following fields won't change, or if at least you could notify me about it :)
The fields I will be using are "channel-version" (releases-index.json), "releases.json" (releases-index.json), "latest-release" (releases.json), "releases"[index]."release-version" (releases.json), "releases"[index]."runtime and windowsdesktop"."files"."rid and url and name" (releases.json).

**Comment by hamarb123** [comment]
Just to clarify, what I'm trying to achieve is some sort of function that can download the .NET Runtime or Desktop Runtime installer for x64, x86, and arm64 on Windows and macOS, as an exe or pkg. It should automatically get the latest installer for any given .NET / .NET Core version (ie. 1.0, 1.1, 2.0, 2.1, 2.2, 3.0, 3.1, 5.0, 6.0).

**Comment by mairaw** [comment]
Can you comment on that @rbhanda?

**Comment by leecow** [comment]
@hamarb123, yes, you can count on the fields not changing. We treat the file as a contract of sorts and are very careful to not break existing users of the files.
