### ISSUE TITLE
How to receive value for razor template from "Microsoft.AspNet.Mvc.Razor.HelperResult" helper

### ISSUE THREAD

**Issue by Shameer-Ali** [dotnet/core#693]
I have created a custom component by using Html Helper in ASP.NET MVC. Also, did the same logic in ASP.NET Core platform.
My component will be working fine, when I have set the properties. Now I am trying to include one additional support like displaying custom contents (like images, html elements and text) with in my component like in dialog component.
In ASP.NET MVC, I have received the inner content from “System.Web.WebPages.HelperResult” this namespace. But ASP.NET Core, I’m unable to get my component inner content which will be mentioned in my view page.
In ASP.NET Core, I’m trying to get the content from “Microsoft.AspNet.Mvc.Razor.HelperResult” namespace. But unfortunately, the expected result was unable to get from this namespace. Even, I don’t know how to get from this namespace (even surfing in internet no ideas about this).
If there is any alternative options to get the result in ASP.NET Core platform or any possible way, please suggest to me!

<img width="416" alt="razor" src="https://user-images.githubusercontent.com/29402958/27127396-8b8a13c0-5118-11e7-8003-1bb088ac1ca5.png">

**Comment by Petermarcu** [comment]
Its probably best to open this issue on the https://github.com/aspnet/mvc 

@Eilon

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#6435
