### ISSUE TITLE
[macos] x64 binary is now installed in `/usr/local/share/dotnet/x64/dotnet`

### ISSUE THREAD

**Issue by isen-ng** [dotnet/core#6930]
### Description

Recently dotnet-core for macos got support for arm64 versions. With this new support, I noticed that the x64 versions of the new packages now install the `dotnet` executable at `/usr/local/share/dotnet/x64/dotnet`, instead of `/usr/local/share/dotnet/dotnet`.

The executable for arm64 versions are still installed at the old location, `/usr/local/share/dotnet/dotnet`. Only the x64 versions changed.

Is this an intended change?

Context: I filed a ticket for the homebrew cask for dotnet-sdk and I want to confirm whether this is an intended change before they make the corrections the cask to symlink the correct executable.

On a side note: I can now install 2 different executables by installing 6.0.100 arm64 and 3.1.400 x64 on an mac M1 laptop. One at `/usr/local/share/dotnet/dotnet` and another in `/usr/local/share/dotnet/x64/dotnet`. In this case, is there a difference on which executable I use?

### Configuration

* Which version of .NET is the code running on?
6.0.100, 5.0.400, 3.1.400

* What OS and version, and for Linux, what distro?
MacOS Catalina

* What is the architecture (x64, x86, ARM, ARM64)?
X64

---

ticket reference on brew: https://github.com/Homebrew/homebrew-cask/issues/114509

**Comment by svick** [comment]
Yes, this is an intended change made so that x64 and ARM versions of .Net can live together. See [the *x64 emulation model* document on dotnet/designs](https://github.com/dotnet/designs/blob/main/accepted/2021/x64-emulation-on-arm64/x64-emulation.md) for more details.

**Comment by mairaw** [comment]
@richlander anything to add here or can this be closed?

**Comment by isen-ng** [comment]
Thank you very much!
I have all the information I need!

I'll close this ticket, but if there is anything to add, please go ahead add them!
