### ISSUE TITLE
Sdks aren't working on Windows 11

### ISSUE THREAD

**Issue by leejmonagan** [dotnet/core#6934]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I run the command to list the sdks none show, but when I look at the directory the files are where they're supposed to be.

PS C:\Users\leejm\source\repos> dotnet new console -o MyApp
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
You might be hitting this known issue if you have VS installed as well: https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows

Anyway, check the output of `where.exe dotnet` and if your system is x64 and the x86 path returns first, please follow the steps at [#5962 (comment)](https://github.com/dotnet/core/issues/5962#issuecomment-780084535) to fix the issue.

Let me know if this helps.

**Comment by leejmonagan** [comment]
Wow.

Thank you.  First I’ve ever reported an issue.  Love the fast response.

It worked.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mairaw** [comment]
Great to hear!
