### ISSUE TITLE
dotnet watch doesnt run, need to give run parameter

### ISSUE THREAD

**Issue by TanweerDreams** [dotnet/core#6938]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

on windows 10, 
running app, 
dotnet watch 
doesnt launch web page as per document.

instead 
dotnet watch run
launched web page

**Comment by mairaw** [comment]
Are you running .NET 5 SDK instead of 6?
Please paste the output of `dotnet ––info`.
