### ISSUE TITLE
System.Web.UI and System.Web.Scripts not available in .net core?

### ISSUE THREAD

**Issue by synckarthik** [dotnet/core#694]
![web ui](https://user-images.githubusercontent.com/23655474/27168570-dc92b82a-51c3-11e7-9dc0-a8f5593a6319.PNG)

In my project i have used **System.Web.UI** and **System.Web.Scripts**  classes. But when i upgrade to .net core it shows error .Please refer the image.

How to resolve this? Or is any alternative packages for this ?

**Comment by karelz** [comment]
This issue was moved to aspnet/Home#2061
