### ISSUE TITLE
.NET Framework v4.7.1 Error message when try to install

### ISSUE THREAD

**Issue by cesarvega92** [dotnet/core#6943]
I'm trying to install the .NET Framework v4.7.1 on a Windows 7 (64bit) PC, but I keep getting the following error: 'Installation Did Not Suceed' .NET Framework 4.7.1 has not been installed because: The timestamp signature and/or certificate could not be verified or is malformed.'

Does anybody run into this error before? The PC currently has installed a .Net Framework v4.6.2, .NET Framework 4.5 SDK, and .NET Framework 4.5 Multi-Targeting Pack.

**Comment by greenozon** [comment]
Have you installed SHA2 support on your OS?

ref for details over here  https://answers.microsoft.com/en-us/windows/forum/all/the-timestamp-signature-andor-certificate-could/2de7e456-f6df-42a4-82dc-9201eec07c4f
