### ISSUE TITLE
'DateTime' does not contain a definition for 'now' +     <p>The time on the server is @DateTime.now</p>

### ISSUE THREAD

**Issue by Trevor-Okwirri** [dotnet/core#6944]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Pentadome** [comment]
try using `Now` and not `now`

**Comment by scalablecory** [comment]
Seems like a syntax error as @Pentadome says. Thanks.
