### ISSUE TITLE
.NET framework installation error

### ISSUE THREAD

**Issue by Hussainbabatunde** [dotnet/core#6947]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

i tried installing a .NET framework version 4.8 but it keeps saying  (The .NET Framework 4.7.2 redistributable does not apply to this operating system. Please download the .NET Framework 4.7.2 for your operating system from the <A HREF="http://go.microsoft.com/fwlink/?LinkId=863273">Microsoft Download Center</A>. )

i have downloaded the offline version but it still keeps giving me this popup notification. Please what can i do to rectify this issue.
i am using a windows 10 operating system.

**Comment by eiriktsarpalis** [comment]
cc @mairaw

**Comment by mairaw** [comment]
How are you getting that error message? Are you trying to install a different software? 

Windows 10 already comes with .NET Framework 4.8, so you won't be able to install 4.7.2.
