### ISSUE TITLE
deps.json error while trying to add new Controller

### ISSUE THREAD

**Issue by RemiGri** [dotnet/core#695]
Hello,
I have an error when trying to add new Controller on a brand new fresh project (ASP.NET Core Web Application (.NET Core)). I have tried naming the project with a . in the middle (Test.project) and without (TestProject) as i have read that the spaces in the name could give errors. I am getting the following error when trying to add a new controller:
![capturefdf](https://user-images.githubusercontent.com/6548496/27174830-55ad3096-51b5-11e7-984a-2f5f25888e83.PNG)

It seems to be looking for the deps.json in bin\BPC\Debug\netcoreapp1.1 and ofcourse the file is not in that folder because after build the files get generated to bin\Debug\netcoreapp1.1

when i move the files generated in bin\Debug\netcoreapp1.1 to bin\BPC\Debug\netcoreapp1.1 then everything seems to work (i am able to add the controllers).

Could anyone advise if this is an error with Visual studio 2017? Or am i doing something wrong? and that is the BPC folder for? 

I am using VS 2017 (Version 15.2 (26430.13) Release)

**Comment by Petermarcu** [comment]
@Eilon @barrytang @mlorbetske can you take a look at suggest which repo may be the best place to move this issue?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#522
