### ISSUE TITLE
Issues downgrading to .NET 4.8 from .NET 6.0

### ISSUE THREAD

**Issue by gxclark** [dotnet/core#6954]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed and successfully ran the Hello World! demo located here:
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

This only seems to work for .NET 6.0.  I got an error trying to build an app that can only support .NET 4.8, so I uninstalled 6.0, installed 4.8, opened a new CMD prompt, but I cannot

**Comment by eiriktsarpalis** [comment]
I would say that this is expected, downgrading the target framework of a `net6.0` project to a `net48` target is not something that is guaranteed to work out of the box. It would help if you could share

1. The downgraded project, include source files and project configuration.
2. A description of expected versus actual behavior you are seeing.
