### ISSUE TITLE
Two Pi4 Ubuntu Server. 20.04 works as expected, 21.10 does not

### ISSUE THREAD

**Issue by lkallevig** [dotnet/core#6955]
dotnet-runtime-6.0.0-linux-arm.tar.gz installed on both using tar

This is on the 21.10 install which I did after the 20.04
kal@Pi4:~/Downloads$ sudo tar zxf dotnet-runtime-6.0.0-linux-arm.tar.gz -C $HOME/dotnet
[sudo] password for kal:
kal@Pi4:~/Downloads$ dotnet
-bash: /home/kal/dotnet/dotnet: No such file or directory

 sudo nano ~/.bashrc  for both shows (this from the one that does not work):
# manual install of dotnet 6
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

kal@Pi4:~/dotnet$ ls -l dotnet
-rwxr-xr-x 1 root root 51228 Oct 22 16:57 dotnet

************************
Pi4 has html and php websites accessible from the internet. It is the one not working.
Pi4-2 is only on my LAN. It has a dotnet core web app that I want to add to Pi4.

***********************
I am a linux rookie, not so much with windows. 
I have rebooted a couple of times.

**Comment by eiriktsarpalis** [comment]
What was the output of the `tar` operation? It would seem like the `$HOME/dotnet` folder is missing sdk contents.

**Comment by lkallevig** [comment]
kal@Pi4:~$ ls -l dotnet
total 144
-rwxr-xr-x 1 root root 51228 Oct 22 16:57 dotnet
drwxrwxr-x 3 root root  4096 Oct 22 17:03 host
-rw-rw-r-- 1 root root  1116 Oct 22 16:53 LICENSE.txt
drwxrwxr-x 3 root root  4096 Oct 22 17:03 shared
-rw-rw-r-- 1 root root 78479 Oct 22 16:53 ThirdPartyNotices.txt

I have not been able to find any differences between the one that works and the one that does not.

**Comment by lkallevig** [comment]
Would it make sense to delete that dotnet directory and do the `tar` step again? 

This is just the runtime, no sdk.

**Comment by eiriktsarpalis** [comment]
Based on your output, you seem to have extracted your sdk contents to your `$HOME` folder, not your `$HOME/dotnet` folder. I would recommend deleting and trying again, and downloading the sdk instead of the runtime.

**Comment by lkallevig** [comment]
Done, but with the same result.
This time I followed these directions:
[Manual install](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual) 
```
DOTNET_FILE=~/Downloads/dotnet-runtime-6.0.0-linux-arm.tar.gz
export DOTNET_ROOT=$(pwd)/dotnet
mkdir -p "$DOTNET_ROOT" && tar zxf "$DOTNET_FILE" -C "$DOTNET_ROOT"
export PATH=$PATH:$DOTNET_ROOT
```
`kal@Pi4:~$ ls $HOME/dotnet`
dotnet  host  LICENSE.txt  shared  ThirdPartyNotices.txt
`kal@Pi4:~$ cd dotnet`
kal@Pi4:~/dotnet$ dotnet
-bash: /home/kal/dotnet/dotnet: No such file or directory

**Comment by eiriktsarpalis** [comment]
In Linux you'd need to specify a relative path when running a local executable. Assuming you're still in the `~/dotnet` folder running
```bash
$ ./dotnet
```
Should work. In order to access dotnet from everywhere, you need to add it in your `PATH`. To do this for your current bash session, just write
```
$ export PATH=$HOME/dotnet:$PATH
```
and then you should be able to call `dotnet` from any folder. Note that this will be lost in your next session. If you're unfamiliar with Linux I would recommend either installing dotnet using a package manager or following a Linux tutorial first.

**Comment by lkallevig** [comment]
Thanks for your help.

Unfortunately , adding the ./ makes no difference.

After running the above export command I have this:
kal@Pi4:~$ echo $PATH
/home/kal/dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kal/dotnet

Now the location is on both ends of the $PATH. But bash still does not know about it.

I found some discussion of whether or not 21.10 loads .bashrc, so added to .profile the following:
```
# enable dotnet path for dotnet 6
export DOTNET_ROOT=$HOME/dotnet
export PATH=$HOME/dotnet:$PATH
```
So at this point it is in both,  and at both the beginning and end of $PATH, but -bash still reports no such file or directory.

I am beginning to think it is a 21.10 version of Ubuntu problem. Maybe it will solve itself over the next few months.

**Comment by lkallevig** [comment]
I saw this after posting. No problem though.
