### ISSUE TITLE
Tutorial didn't work as expected.

### ISSUE THREAD

**Issue by MoreporkGithub** [dotnet/core#6959]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows 10 

Everything was fine until I entered the "dotnet watch" command.

Here's what it gave me...
=================================== start of command window dump ===================
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\dashw>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\dashw>dotnet new webapp -o MyWebApp --no-https

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.403

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Getting ready...
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/5.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on MyWebApp\MyWebApp.csproj...
  Determining projects to restore...
  Restored C:\Users\dashw\MyWebApp\MyWebApp.csproj (in 66 ms).
Restore succeeded.

C:\Users\dashw>cd MyWebApp

C:\Users\dashw\MyWebApp>dotnet watch
dotnet-watch:

  Environment variables:

   DOTNET_USE_POLLING_FILE_WATCHER
   When set to '1' or 'true', dotnet-watch will poll the file system for
   changes. This is required for some file systems, such as network shares,
   Docker mounted volumes, and other virtual file systems.

   DOTNET_WATCH
   dotnet-watch sets this variable to '1' on all child processes launched.

   DOTNET_WATCH_ITERATION
   dotnet-watch sets this variable to '1' and increments by one each time
   a file is changed and the command is restarted.

  Remarks:
   The special option '--' is used to delimit the end of the options and
   the beginning of arguments that will be passed to the child dotnet process.
   Its use is optional. When the special option '--' is not used,
   dotnet-watch will use the first unrecognized argument as the beginning
   of all arguments passed into the child dotnet process.

   For example: dotnet watch -- --verbose run

   Even though '--verbose' is an option dotnet-watch supports, the use of '--'
   indicates that '--verbose' should be treated instead as an argument for
   dotnet-run.

  Examples:
   dotnet watch run
   dotnet watch test

Usage:
  dotnet-watch [options] [[--] <additional arguments>...]]

Options:
  -q, --quiet                Suppresses all output except warnings and errors
  -v, --verbose              Show verbose output
  -p, --project <project>    The project to watch
  --list                     Lists all discovered files without starting the watcher

Additional Arguments:
  Arguments passed to the application that is being run.

C:\Users\dashw\MyWebApp>dotnet watch
dotnet-watch:

  Environment variables:

   DOTNET_USE_POLLING_FILE_WATCHER
   When set to '1' or 'true', dotnet-watch will poll the file system for
   changes. This is required for some file systems, such as network shares,
   Docker mounted volumes, and other virtual file systems.

   DOTNET_WATCH
   dotnet-watch sets this variable to '1' on all child processes launched.

   DOTNET_WATCH_ITERATION
   dotnet-watch sets this variable to '1' and increments by one each time
   a file is changed and the command is restarted.

  Remarks:
   The special option '--' is used to delimit the end of the options and
   the beginning of arguments that will be passed to the child dotnet process.
   Its use is optional. When the special option '--' is not used,
   dotnet-watch will use the first unrecognized argument as the beginning
   of all arguments passed into the child dotnet process.

   For example: dotnet watch -- --verbose run

   Even though '--verbose' is an option dotnet-watch supports, the use of '--'
   indicates that '--verbose' should be treated instead as an argument for
   dotnet-run.

  Examples:
   dotnet watch run
   dotnet watch test

Usage:
  dotnet-watch [options] [[--] <additional arguments>...]]

Options:
  -q, --quiet                Suppresses all output except warnings and errors
  -v, --verbose              Show verbose output
  -p, --project <project>    The project to watch
  --list                     Lists all discovered files without starting the watcher

Additional Arguments:
  Arguments passed to the application that is being run.

C:\Users\dashw\MyWebApp>
========================= end of command window dump ====================================

The expected output never arrived.

I understand that this is showing the usage for various commands but I have no idea what it is SUPPOSED to be doing. I was following a simple tutorial and it seemed to be going fine. If anyone can help, I'd be grateful as I really want to get into ASP.NET Web Forms.

Thanks,

Pete.

**Comment by mairaw** [comment]
Hi @MoreporkGithub. That tutorial requires .NET 6 SDK. I'll update the content to make sure that is more clear. In .NET 5, the command would be `dotnet watch run`.

**Comment by MoreporkGithub** [comment]
Thanks Mairaw.

It is working in Net 5 now.
