### ISSUE TITLE
The link for the .net core 2.0 win 64bit installer is dead

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/core#696]
It links to:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

**Comment by Petermarcu** [comment]
@livarcocc , can you take a look?

**Comment by Petermarcu** [comment]
@TFTomSun it looks like it works now. Can you please reopen if you still have a problem?

**Comment by TFTomSun** [comment]
Works. thx.
