### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by lyl18667436525** [dotnet/core#6961]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
[新建文本文档.txt](https://github.com/dotnet/core/files/7586988/default.txt)

**Comment by mairaw** [comment]
Did you install the SDK? If so, you might be running into a known issue.

Check the output of `where.exe dotnet` and if your system is x64 and the x86 path returns first, please follow the steps at [#5962 (comment)](https://github.com/dotnet/core/issues/5962#issuecomment-780084535) to fix the issue

Let me know if this helps.
