### ISSUE TITLE
Product version Exception!

### ISSUE THREAD

**Issue by wf-soft** [dotnet/core#6962]
Why do I release files after upgrading version 6.0? The product version has more than a string of characters after the + sign, and I can't find any reason

![image](https://user-images.githubusercontent.com/62228539/143057198-22168ce8-622b-4fd1-8b5d-13f27b14bc5b.png)

**Comment by mairaw** [comment]
Can you provide more context on where you're seeing this or how we can repro? Is this an API?

**Comment by wf-soft** [comment]
@mairaw I have checked all configurations, including local files, but I can't find any information about the redundant part of the version number. It is only generated in qingmo.assemblyinfo.cs in the obj directory at the time of release

![image](https://user-images.githubusercontent.com/62228539/143159665-7d2d023f-e729-48c9-9a51-36d201f11079.png)
![image](https://user-images.githubusercontent.com/62228539/143159810-62b19008-3d51-4b51-970f-f15e565dabe7.png)
![image](https://user-images.githubusercontent.com/62228539/143160111-b2e95172-0075-40a1-abf1-61a9d4a0a850.png)

**Comment by wf-soft** [comment]
I found it from GitHub ID, and I'm trying to find a way to delete it

![image](https://user-images.githubusercontent.com/62228539/143180907-e96605e9-ff6b-4ff1-883f-8181c37419dc.png)

**Comment by wf-soft** [comment]
-p:IncludeSourceRevisionInInformationalVersion=false
