### ISSUE TITLE
Console.WriteLine' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by sachin407** [dotnet/core#6968]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
C:\Users\sachi\MyApp>Console.WriteLine("Hello, World!");
'[Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file.]([![Screenshot 2021-11-25 091530](https://user-images.githubusercontent.com/91829983/143376455-104c002f-13a4-4e44-b85b-01e376b92205.png)](url))

**Comment by mairaw** [comment]
The Console.WriteLine command is not supposed to be entered in the command prompt.
The code shown on the **Create your app** step is only showing the contents of the file named _Program.cs_. You should be able to open the file and see the same content if you open that file. The file is inside the new MyApp folder.

At this point, you should be able to continue the tutorial. Let us know if you run into any other issues.
