### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

### ISSUE THREAD

**Issue by Ian-Fogelman** [dotnet/core#6969]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

**Comment by mairaw** [comment]
It might be an issue with your NuGet sources. 
Can you check the file %appdata%\NuGet\NuGet.Config and see if it has the package source configured it correctly?
