### ISSUE TITLE
Package restore requirement on opening project and many builds is unsustainable.

### ISSUE THREAD

**Issue by CampsiteHelper** [dotnet/core#697]
Thanks for your interest in .NET Core. 

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

**Comment by Petermarcu** [comment]
Hi @CampsiteHelper , can you help clarify what you are seeing and what you would expect instead?
/cc @rrelyea @livarcocc

**Comment by richlander** [comment]
Please file a new issue with more info. It is fine to file it here.
