### ISSUE TITLE
problems with maxquant

### ISSUE THREAD

**Issue by llll-jy** [dotnet/core#6971]
![image](https://user-images.githubusercontent.com/84617971/143402747-8acdcc50-940e-4274-ab45-bace33db85d9.png)
how to solve？

**Comment by mairaw** [comment]
It seems to be telling you to download the .NET Core 3.1 SDK x64. Have you done that?

**Comment by olaldenoh** [comment]
Hi @mairaw I am having a similar issue. I have downloaded and installed .NET Core 3.1 SDK x64, then restarted my computer and the error keeps appearing when I try to run MaxQuant. Any ideas? Thanks!

**Comment by heuselm** [comment]
+1 - I am experiencing the same error on my Laptop.

.NET core 3.1.424 installed.
Tried a lot of different versions - to no avail.

Sysinfo:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
System Manufacturer	LENOVO
System Model	20XWCTO1WW
System Type	x64-based PC
System SKU	LENOVO_MT_20XW_BU_Think_FM_ThinkPad X1 Carbon Gen 9
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	LENOVO N32ET79W (1.55 ), 7/27/2022

**Comment by acragin** [comment]
I have also been having this issue -- updated to the latest version of Maxquant and have the latest .Net core installed yet I still get the same error every time I try to run the program -- any insights would be greatly appreciated!!

**Comment by IdRose** [comment]
same here

**Comment by HijaziHassan** [comment]
Go to "Global Parameters" tab >> "Advanced", then untick the box "Use .NET Core". No error message will appear when you hit the "Start" button.
Though I must say that I do not know the difference in outcomes when having it ticked or unticked.
