### ISSUE TITLE
ZSH: COMMAND NOT FOUND: DOTNET

### ISSUE THREAD

**Issue by aphilethethinker** [dotnet/core#6972]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos Monterey

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I ran into an issue when completing the installation of .net sdk core, the issue is when I run the command $ dotnet on my macOS Monterey terminal, what I am supposed to get after executing that command I get zsh: command not found: dotnet. I have completed the installation of .net but still have the same issue

**Comment by scalablecory** [comment]
Hi @aphilethethinker, have you opened a *new* terminal to try? There may be path environment variables that get updated.

**Comment by BeauNouvelle** [comment]
There seems to be a few other similar issues here on Github and has popped up recently...

https://github.com/dotnet/core/issues/6953

**Comment by eiriktsarpalis** [comment]
Duplicate of https://github.com/dotnet/sdk/issues/22910
