### ISSUE TITLE
intale la aplicacion cuando la abri me salio el titulo de "reparar la intalacion" y no me pasa de ahi

### ISSUE THREAD

**Issue by alejandrahernandez14** [dotnet/core#6974]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
¿Qué aplicación? Este tutorial que está siguiendo es para que aprenda a codificar usando .NET. ¿Es esto lo que estás intentando hacer?
