### ISSUE TITLE
Open the Program.cs file in any text or code editor, such as Notepad or Visual Studio Code. The Program.cs file is located on the newly created MyApp directory.

### ISSUE THREAD

**Issue by eshadoel** [dotnet/core#6981]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Please share details of the issue you're having @eshadoel. Is there something not clear in the instructions?
