### ISSUE TITLE
Blazor tutorial failed to run

### ISSUE THREAD

**Issue by programify** [dotnet/core#6983]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows 10

After entering the command "dotnet watch"

It responds with a syntax help page and nothing else. It's not listening on any port, none reported.

Running with -v verbose option I get...

===============================================================
watch : Evaluating dotnet-watch file set.
watch : Running MSBuild target 'GenerateWatchList' on 'D:\Software\Blazor\FirstBlazorApp\FirstBlazorApp.csproj'
watch : Started ....redacted....
watch : Process id 10532 ran for 610ms
watch : Watching 31 file(s) for changes
watch : Watch command will not use --no-restore. Unsupport dotnet-command ''.
watch : Browser refresh is only supported for run commands.
watch : Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 11288
watch : Running dotnet with the following arguments:
watch : Started

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
watch : Process id 11288 ran for 9ms
watch : Exited with error code -2147450751
watch : Waiting for a file to change before restarting dotnet...
===============================================================

Hangs until I press Ctrl+C.

localhost:5000 shows nothing to connect to.

**Comment by scalablecory** [comment]
Can you post the command line output here of `dotnet watch`? Thanks.
