### ISSUE TITLE
Regex POSIX character classes

### ISSUE THREAD

**Issue by Liturgist** [dotnet/core#699]
Is there any work going to support POSIX character classes? [:digit:][:alnum:][:space:] etc.

**Comment by eerhardt** [comment]
@Liturgist - I assume you are referring to http://www.regular-expressions.info/posixbrackets.html, ex. `[:alpha:]`, `[:digit:]`, etc

I don't think there is any work currently going on to support these (or at least I haven't heard of any).  The full .NET Framework didn't support these classes.

https://stackoverflow.com/questions/9643717/why-cant-i-match-posix-character-classes

According to https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#CategoryOrBlock, you can use Unicode categories and blocks, and http://www.regular-expressions.info/posixbrackets.html seems to have a mapping between POSIX character classes and Unicode.

**Comment by karelz** [comment]
Moved to https://github.com/dotnet/corefx/issues/21305

**Comment by Liturgist** [comment]
Sorry. When I could not find my post, it appears that I happened into another group. I honestly do not know the best group to address this. Thank you for closing this one.

**Comment by karelz** [comment]
@Liturgist no worries, we can route.
