### ISSUE TITLE
dotnet new webapp -o MyWebApp --no-https not executing

### ISSUE THREAD

**Issue by petesN** [dotnet/core#6993]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

dotnet new webapp -o MyWebApp --no-https
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by ryank425** [comment]
As the link suggests, try to use the stackoverflow link to fix the issue.

https://stackoverflow.com/questions/67049414/windows-or-visual-studio-cant-find-the-latest-installed-net-sdk/67049415#67049415
