### ISSUE TITLE
Error help me please

### ISSUE THREAD

**Issue by Maximeduyne** [dotnet/core#6995]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macOS M1

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by BeauNouvelle** [comment]
@Maximeduyne please see https://github.com/dotnet/core/issues/6953
I believe it could be related.

**Comment by mairaw** [comment]
@Maximeduyne what version of the SDK have you installed? For M1, you should install Arm64. If you have installed a different version, please uninstall that and install the Arm64 version.
