### ISSUE TITLE
im trying to install net5 on my Mac but I can't seem to figure out how, im trying to mod a game!

### ISSUE THREAD

**Issue by KartyrsKeep** [dotnet/core#6997]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Which version of macOS are you on?

**Comment by BeauNouvelle** [comment]
@KartyrsKeep Anything related to this?
https://github.com/dotnet/core/issues/6953
