### ISSUE TITLE
Something doesn't work with VS2022 .NET6 Copy Local set to False

### ISSUE THREAD

**Issue by psmacchia** [dotnet/core#6998]
In a regular .NET 6 project with VS2022 v17.0.0 Copy Local set to False doesn't work: the referenced assembly is still copied:
![image](https://user-images.githubusercontent.com/511445/144552339-33d6c263-257c-4bb6-bb44-b8e8ca911bec.png)

I need to set `<Private>False</Private>` instead to make it work (with or without `<CopyLocal>False</CopyLocal>`)

![image](https://user-images.githubusercontent.com/511445/144552536-8f1ed1f5-258b-41d4-bf50-08b4778b781b.png)

**Comment by Loophole62ndFF** [comment]
I've encountered this same problem, and the <private> solution - whatever that mystery tag is supposed to mean - seems to fix the problem.  I now have 64 project files with multiple references in each one, that have to be hand-edited to work around this issue.

**Comment by Loophole62ndFF** [comment]
As an alternative work-around, editing the csproj files to set:
<PropertyGroup>
	<UseCommonOutputDirectory>true</UseCommonOutputDirectory>
</PropertyGroup>

also seems to solve the problem, without requiring the "Copy Local" to be set at all.

**Comment by mairaw** [comment]
Can you confirm if this only happens when you build the project inside VS or if it also happens with the dotnet CLI command `dotnet build`?
