### ISSUE TITLE
VSCode and OmniSharp

### ISSUE THREAD

**Issue by renatormendes** [dotnet/core#7003]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install#
Operating System: linux

Problem: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/renatormendes/Documentos/code/MyApp/MyApp.csproj

I made the change in omnisharp.path and also to always update it and I still have the same problem here with .NET 6.0. I use the Solus 4.3 system and my PATH is set in /home/user/.dotnet, where user is my username.

**Comment by buyaa-n** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#4994
