### ISSUE TITLE
other version of .NET can not help me complete pushing duties to Github

### ISSUE THREAD

**Issue by NguyenMinhSu** [dotnet/core#7004]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
when i wan to push my duties to Github, the software askes me install version >NET framework 4.7.2, 
i went to install version 4.7.2 but not succeed, and other version as 4.8 or any versio is not supported.
Then, i can use Git

**Comment by mairaw** [comment]
@NguyenMinhSu we'll need a bit more information to try to help you. The tutorial is for someone trying to learn how to code using .NET 6. 

If you need .NET Framework, the downloads for that can be found at https://dotnet.microsoft.com/download/dotnet-framework

What error message are you getting that is prompting you to download .NET Framework? And what version of Windows are you on?
