### ISSUE TITLE
Unable to start Kestrel on Linux (Raspbian raspberry pi 3)

### ISSUE THREAD

**Issue by kengey** [dotnet/core#701]
After following the steps described on: [link](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md) I was unable to start my ASP.NET-CORE webapplication. I had the following error: 
```
Microsoft.AspNetCore.Server.Kestrel[0]
Unable to start Kestrel.System.AggregateException: One or more errors occurred. (Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
```

It seems that libuv is missing and needs to be installed using the steps described over here: [link](https://gist.github.com/magohl/029efefbf15527b5f10d)
:

_You're missing the installation instructions for libuv. It should be installed after mono.

```
sudo apt-get install automake libtool curl
curl -sSL https://github.com/libuv/libuv/archive/v1.4.2.tar.gz | sudo tar zxfv - -C /usr/local/src
cd /usr/local/src/libuv-1.4.2
sudo sh autogen.sh
sudo ./configure
sudo make
sudo make install
sudo rm -rf /usr/local/src/libuv-1.4.2 && cd ~/
sudo ldconfig
```_

**Comment by Petermarcu** [comment]
You shouldn't need to install libuv for ASP.NET Core on .NET Core. It should be with the app if you are doing self-contained. Are you publishing the app as described [here](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md)?

**Comment by kengey** [comment]
Hi @Petermarcu , yes, I followed those steps.

**Comment by Petermarcu** [comment]
What version of the .NET Core are you using? `dotnet --version`?

**Comment by kengey** [comment]
```
D:\Documenten\dev\NetCoreWebApplication1\NetCoreWebApplication1>dotnet --version
2.0.0-preview1-005977
```

**Comment by Petermarcu** [comment]
Ok, can you installed all the prereq packages that are listed [here](https://github.com/dotnet/core/blob/master/Documentation/prereqs.md) under Ubuntu? 

Do you see libuv in your published output? Make sure you are using the output under a `publish` folder. like `./bin/Debug/netcoreapp2.0/linux-arm/publish`.

**Comment by kengey** [comment]
@Petermarcu , I've installed all packages by doing
`sudo apt-get install libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip`

My output is not containing libuv, only:
![image](https://user-images.githubusercontent.com/5702720/27545005-02a5d4b0-5a8f-11e7-8048-19e4c7ee39c5.png)

**Comment by Petermarcu** [comment]
Looking closer at your project, it looks like you are referencing a whole bunch of .NET Core 1.X nuget packages from ASP.NET. That's my guess as to why this is happening. 

If you directly add a reference to [this](https://www.nuget.org/packages/Libuv/1.10.0-preview1-22040) does it get libuv in the output?

Since your project is targeting netcoreapp2.0. I think you should switch to referencing ASP.NET Core 2.0. If you do `dotnet new web` in a temp folder, you will see the single reference you need to get the whole ASP.NET platform. I think that will pull in most of the dependencies you have listed out in your project including libuv.

**Comment by kengey** [comment]
Creating and publishing a new project from command line is corretly outputting libuv.
Referencing the pointed libuv nuget package from my project is trouble, but that is all related to having these 1.X references.
Anyhow, I think it is clear that this is related to me having initially created a .Net Core 1.1 project and then switching to 2.0.

**Comment by Petermarcu** [comment]
Yeah, that all sounds right. 

@DamianEdwards @Eilon, should we do something to make it more obvious that they need to upgrade their ASP.NET packages when upgrading to netcoreapp2.0?

**Comment by kengey** [comment]
please also notice that VS2017 is not showing .NET core 2.0 as a selectable Target Framework.
![image](https://user-images.githubusercontent.com/5702720/27546189-5bc4b25c-5a92-11e7-9a38-0685cc3a7368.png)
But I understand this is an entirely different issue non related to this one.

**Comment by Petermarcu** [comment]
You have to have the latest preview of Visual Studio installed to see 2.0 in the that dropdown. https://www.visualstudio.com/vs/preview/

**Comment by Petermarcu** [comment]
I'm going to close this as it is resolved. Cause was not using ASP.NET Core 2.0 packages.

**Comment by Petermarcu** [comment]
I'm going to close this now because I don't think there is anything more to be done.

**Comment by allycs** [comment]
core3.1 依然存在此问题
