### ISSUE TITLE
Download of .NET 5.0

### ISSUE THREAD

**Issue by BBuno** [dotnet/core#7010]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My OS is Wn10. During the download of .NET 5.0 all was ok ,up to the final step : Edit your code.
On this last step,on Program.cs,  I have added the 3rd line : "Console.WriteLine ( "The current time...etc.)"   and a "screwdriver " has appeared on the left of this line; I was not able to understand its meaning.  Having written,and saved, the 3rd line,  I tried to enter again on Prompt (as required, to close the installation) , but I got the message (in Italian) : No Project has been found... ; I was not able to understand what was wrong .

**Comment by ryank425** [comment]
I think you are missing a semicolon at the end. If you copy and paste exactly, does it show errors again?

`Console.WriteLine("The current time is " + DateTime.Now);`

**Comment by maryamariyan** [comment]
We'll need a bit more information to try to help you. Could you please perhaps send a screenshot of what you are seeing?

cc @mairaw
