### ISSUE TITLE
Task.WhenAll swallows exceptions if more than one exception occurs 

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/core#7011]
Consider this code. 

```csharp
        try
        {

            await Task.WhenAll(Enumerable.Range(0, 5).Select(async i =>
            {
                await Task.Delay((i + 1) * 1000);
                if (i == 1 || i == 3) throw new Exception($"Error {i}");

                Console.WriteLine($"Completing {i}");

                return i;
            }));

        }
        catch (Exception e)
        {
            Console.WriteLine($"Catching {e.GetType().FullName} {e is AggregateException}");
        }
```

It outputs

> Completing 0
> Completing 2
> Completing 4
> Catching System.Exception False

`Task.WhenAll` correctly lets all Tasks finish even after the first one crashes. But it throws the first exception rather than a `AggregateException`

**Comment by ryank425** [comment]
As for the why it behaves that way, https://github.com/dotnet/runtime/issues/31494#issuecomment-553941135

As for catching all exceptions, you can use this code block from one of [StackOverflow answers](https://stackoverflow.com/a/35078873/5941660).
```

private async Task Example()
{
    var tasks = new [] { DoLongThingAsyncEx1(), DoLongThingAsyncEx2() };

    try 
    {
        await Task.WhenAll(tasks);
    }
    catch (Exception ex) 
    {
        var exceptions = tasks.Where(t => t.Exception != null)
                              .Select(t => t.Exception);
    }
}

private Task DoLongThingAsyncEx1()
{
    return Task.Run(() => { throw new InvalidTimeZoneException(); });
}

private Task DoLongThingAsyncEx2()
{
    return Task.Run(() => { throw new InvalidOperationException(); });
}
```

**Comment by svick** [comment]
It's not `Task.WhenAll` that ignores the extra exceptions, it's `await`. You can see that if you modify your code to this:

```c#
Task task = null;
try
{
    task = Task.WhenAll(...);
    await task;
}
catch (Exception e)
{
    Console.WriteLine($"Catching {e.GetType().FullName} {e is AggregateException}");
    Console.WriteLine($"Inspecting {task.Exception.GetType().FullName} {task.Exception is AggregateException}");
}
```

This prints:

```
Catching System.Exception False
Inspecting System.AggregateException True
```

This behavior is by design and [it's documented](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch?WT.mc_id=DOP-MVP-5002735#exceptions-in-async-methods):

> A task can be in a faulted state because multiple exceptions occurred in the awaited async method. For example, the task might be the result of a call to `Task.WhenAll`. When you await such a task, only one of the exceptions is caught, and you can't predict which exception will be caught.

**Comment by AndersMalmgren** [comment]
Really weird design decision, thanks guys.

**Comment by AndersMalmgren** [comment]
In our production code we already abstract Task.WhenAll for a more fluent approuch. So could fix it there.

```csharp
    public static async Task<IReadOnlyCollection<TResult>> WhenAll<TResult>(this IEnumerable<Task<TResult>> source)
    {
        var task = Task.WhenAll(source);

        try
        {
            return await task;
        }
        catch
        {
            if (task.Exception != null) ExceptionDispatchInfo.Capture(task.Exception).Throw();
            throw;
        }
    }
```

**Comment by maryamariyan** [comment]
Seems like this issue can now be closed.
