### ISSUE TITLE
.NET extension installation and verify in the Terminal window 

### ISSUE THREAD

**Issue by FaisalMW** [dotnet/core#7014]
Problem encountered on https://dotnet.microsoft.com/download/learn/dotnet/hello-world-tutorial/install
Operating System: macOS

Hi, 

I have tried to install .NET extension to support in Virtual studio code, when Installed I am trying to verify the installation in the terminal but receive the following:

Last login: Wed Dec  8 13:19:57 on ttys000
faisal@Faisals-Air ~ % dotnet
zsh: command not found: dotnet
faisal@Faisals-Air ~ % 

I am a beginner to this but I know I have installed correctly but do not know as to what I am doing wrong. 

My operating system is a MAC with the version Monterey 12.0.1.

**Comment by ryank425** [comment]
You would need .NET SDK (6 is latest at the time) installed first to make dotnet work in terminal.

[.NET Extension in VSCode](https://github.com/dotnet/vscode-dotnet-pack) only contains following, and doesn't contain SDK  
- C# for Visual Studio Code
- .NET Interactive Notebooks
- Ionide-VSCode: FSharp

After you install .NET SDK, please make sure to open the new terminal (also open a new session of VSCode by closing and opening again) and try dotnet command again.

**Comment by FaisalMW** [comment]
Thank you. It finally worked.

**Comment by mairaw** [comment]
Great to hear!
