### ISSUE TITLE
SDK 3.1.415: dotnet doesn't work on MacOs 10.13 (High Sierra)

### ISSUE THREAD

**Issue by borjafdezgauna** [dotnet/core#7016]
Hi, Not sure this is the right place to report this possible issue or if the assumed bug is intended behavior. Please forgive me if it's not

I installed the latest release of the SDK on MacOs High Sierra, tried to run "dotnet" and got an error complaining about a library (libSystem.B...) that was compiled for MacOs 11.0. According to the [compatibility chart](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md) NetCore3.1 should be compatible with MacOs 10.13, right?

I uninstalled it, installed SDK 3.1.413 and it worked fine.

This suspected incompatibilty made the artifacts produced by my Azure pipeline stop being compatible with MacOs High Sierra/Mojave/Catalina, even if they were being compiled using NetCore3.1

Cheers!

**Comment by mairaw** [comment]
@rbhanda is there anything else left to do in this issue?

**Comment by rbhanda** [comment]
This is about .NET Core 3.1 SDK which is out of support. We can close this

**Comment by mairaw** [comment]
Sure. I just wanted to make sure that process-wise we took care of everything.
