### ISSUE TITLE
Edge Ubuntu 20.04

### ISSUE THREAD

**Issue by xkid1** [dotnet/core#7017]
Err:9 https://packages.microsoft.com/repos/edge stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
W: GPG error: https://packages.microsoft.com/repos/edge stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/repos/edge stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Frenchman98** [comment]
You can fix this by running
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys (given_key)`
and then running `sudo apt update` again. So in your case,
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF`

Also, this is an Ubuntu/Edge issue, not a dotnet issue lol

**Comment by maryamariyan** [comment]
Closing as it seems there's guidance and not a dotnet issue.
