### ISSUE TITLE
Unable to verify the installation of dotnet in macos

### ISSUE THREAD

**Issue by sephali26** [dotnet/core#7018]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I was trying to verify the installation of dotnet application in macos monterey by running the command "dotnet", but I got error message that "zsh: command not found: dotnet".

**Comment by mairaw** [comment]
Are you on a M1 machine? Make sure you have installed the Arm64 version of the SDK.

You can find more information at https://github.com/dotnet/sdk/issues/22910
