### ISSUE TITLE
File.GetCreationTime  returns 01/01/0001 2:20:00 on ubuntu

### ISSUE THREAD

**Issue by petertsu** [dotnet/core#702]
Hi ,
Seems like File.GetCreationTime returns invalid date once running on ubuntu .
I am tring to run very simple example.
`using System;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string str = "test.txt";

            File.WriteAllText(str, "foo");

            var dt = File.GetCreationTime(str);

            Console.WriteLine(dt);
        }
    }
}

and I get 01/01/0001 2:20:00

dontnet --version :    1.0.4
uname -a :   Linux peter-VirtualBox 4.8.0-56-generic #61-Ubuntu SMP Wed Jun 14 08:15:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thanks

`

**Comment by stephentoub** [comment]
Linux doesn't have a creation time for files.

**Comment by tannergooding** [comment]
Some file systems store the creation time (ext4 does, iirc), but it is not directly accessible.

Would returning the last modification time be reasonable here?  It seems to be as close as you can get to creation time for all file systems, and (imp) is better than returning 1/1/0001

**Comment by stephentoub** [comment]
> Would returning the last modification time be reasonable here?

That's basically what we do starting in 2.0.

**Comment by Petermarcu** [comment]
Yes, this is addressed in a better way in 2.0.
