### ISSUE TITLE
Characters are removed when concatenating strings

### ISSUE THREAD

**Issue by Mackiovello** [dotnet/core#7021]
### Description

```
var foo = @"foo
bar
baz".Split(Environment.NewLine);

foreach (var line in foo)
{
    Console.WriteLine(line);
    Console.WriteLine(line + "O");
    Console.WriteLine("--------");
}
```

This prints:

```
foo
Ooo
--------
bar
Oar
--------
baz
bazO
--------
```

Notice how the first character is replaced by an "O" for the first and second element. It works as expected for the third.

If I do this, it works:

```
var foo = new[] {"foo", "bar", "baz"};
```

If I run the code through dotnetfiddle, I get this:

```
foo
fooO
--------
bar
barO
--------
baz
bazO
--------
```

This is the expected result.

### Configuration

I'm running a Mac mini M1 2020. 
The OS is macOS Monterey 12.0.1.

`dotnet --version` returns 6.0.100.

The application is run from the terminal with `dotnet run`.

The only other system I've run it on is in dotnetfiddle with .NET 6 compiler. That works fine.

### Other information

I tried to upgrade to the latest version of macOS. I've also upgraded .NET version from an alpha version of .NET 6 to 6.0.100. I've also deleted obj and bin and tried again.

**Comment by svick** [comment]
I get the same output if I change the first line to:

```c#
var foo = "foo\r\nbar\r\nbaz".Split("\n");
```

I think this explains the behavior you see: `line` becomes e.g. `foo\r`, and `line + "O"` becomes `foo\rO`. The character `\r` is part of the Windows newline, but on its own, it's the [carriage return](https://en.wikipedia.org/wiki/Carriage_return), which explains why `foo\rO` appears as `Ooo` on the terminal.

**Comment by Mackiovello** [comment]
That's a great explanation. I see now that it works like this:

```
var foo = @"foo
bar
baz".Split("\r\n");
```

It also works by doing `Select(v => v.Trim())` after. Do you have an idea why there would a carriage return in the multi-line string? The code has only been touched by a Mac.

**Comment by svick** [comment]
I think that's a consequence of https://github.com/dotnet/templating/issues/1248. You probably used `dotnet new`, which created a file with Windows line endings. Then whichever editor you used detected and maintained that.

**Comment by Mackiovello** [comment]
Good point! Thank you for your help
