### ISSUE TITLE
dotnet cmd 

### ISSUE THREAD

**Issue by amysy** [dotnet/core#7024]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I ran the command dotnet but got the error/message 'dotnet' is not recognized as an internal or external command error,

**Comment by mairaw** [comment]
Hi @amysy! Can you please provide more details about the issue you're encountering?

**Comment by Keithcat1** [comment]
The error message you got seems to indicate that dotnet.exe is not on your path, that is the PATH environment variable. You could try uninstalling and reinstalling .NET.

**Comment by mairaw** [comment]
And have you installed the SDK already?
