### ISSUE TITLE
Problem encountered windows

### ISSUE THREAD

**Issue by Moaviya** [dotnet/core#7041]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jeffhandley** [comment]
Closing due to not having any information provided in the issue. @Moaviya, please provide details about the problem you experienced if you'd like to have this reopened.
