### ISSUE TITLE
.NET 6.0.1 Windows Update fails with error 0x80070643 

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/core#7044]
Problem encountered when installing - Windows Update 2021-12 .NET 6.0.1 Security Update for x64 Client (KB5009191)

Operating System: Windows

Description: There have been limited reports of a failure to install the update via Microsoft Update on Windows 11.  The update fails with error code 0x80070643.  A workaround is to install the package that is failing manually by downloading it from the [.NET 6.0.101 x64 SDK download site](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-windows-x64-installer), then scanning again.

The other work around is to update Visual Studio installer to 17.0.4.

**Comment by damienmci** [comment]
I've received the same error. The work-around above has addressed the issue.

**Comment by gingters** [comment]
I also had that issue. The work-around helped for me, too.

**Comment by StefanoZamboninD22** [comment]
Same problem, same solution for me.

**Comment by mikhey** [comment]
On Windows 10, same issue.  I wish there was a better way to deal with this.  I've had to jump through some hoops to resolve similar issues with .Net Core 3.1.

**Comment by pvanlaar** [comment]
I have had the same issue (Windows 11), but solved it with the Visual Studio Installer. Updating there installed the SDK version 6.0.101.

**Comment by KD0AZT** [comment]
Same issue.  Was also able to solve it through the Visual Studio Installer.

**Comment by SMHodges** [comment]
Had the same problem, had to use the direct installation workaround.

**Comment by MichaelKoster70** [comment]
Had the same issue. Updating to VS 17.0.4 fixed the problem

**Comment by TheCakeMonster** [comment]
I've got the same problem on Windows 10; this isn't limited to Windows 11

**Comment by chrisaut** [comment]
Also getting this on fully patched machine, rebooting, retrying nothing helped, googling landed me here, Win11 22000.376

**Comment by fraluderin** [comment]
Same issue on Windows 11 22000.376. Updating to VS 17.0.4 solved for me.

**Comment by SpirTBBX** [comment]
I had the same issue with Windows 11. Updating through Visual Studio Installer fixed it.

**Comment by seantleonard** [comment]
Same issue. Error  `0x80070643` when attempting to install `2021-12 .NET 6.0.1 Security Update for x64 Client (KB5009191)`. on Windows 11 22000.376. 

I am on Visual Studio 2022 Preview so updating there, as the last workaround mentioned, did not work as I was still on .NET version 6.0.100. 

After manually installing using the 6.0.101 from the first workaround, the issue was solved.

**Comment by Mrgaton** [comment]
i need help 😢

**Comment by MikeCondra** [comment]
Worked for me. Microsoft should find a way to push this out; the typical Win11 user would be scratching his head and maybe looking at Macs.

**Comment by Kagan-Ditlevsen** [comment]
Download, install, search for updates. Worked perfekt. I have not updates to the Visual Studio Installer, so apparently the is not the solution

**Comment by AraHaan** [comment]
Oddly enough I cant seem to find an update to 17.1 Preview 1.1 that updates the Sdk to 6.0.101 so I had to manually install it.

I wonder when the next VS17.1 Preview update will be. It just seems like they forgot about it for at least a month. I remember updating it in November last time so I feel it’s due for a new preview update.

**Comment by hockeyguy2** [comment]
Another data point: saw the issue on Windows 11 22000.376, and updating to VS 17.0.4 resolved it.

Thanks for the simple workaround.  Now if we can just get Microsoft to wake up and fix this issue ...

**Comment by AraHaan** [comment]
Yes, *also please update those using 17.1 Preview soon as well please with the updated .NET SDK releases for the month like 16.9 has.*

**Comment by rbhanda** [comment]
Closing this in favor of https://github.com/dotnet/core/issues/7062

**Comment by Mist3rShey2n** [comment]
> Problem encountered when installing - Windows Update 2021-12 .NET 6.0.1 Security Update for x64 Client (KB5009191)
> 
> Operating System: Windows
> 
> Description: There have been limited reports of a failure to install the update via Microsoft Update on Windows 11. The update fails with error code 0x80070643. A workaround is to install the package that is failing manually by downloading it from the [.NET 6.0.101 x64 SDK download site](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-windows-x64-installer), then scanning again.
> 
> The other work around is to update Visual Studio installer to 17.0.4.

Same problem same solution.

**Comment by michaelkhalsa** [comment]
Manually installing the update solved it.
Updating VS to 17.04 did not, and the VS installer failed to uninstall a half dozen dll's in the process.
I suspect their was a race condition with both system and VS updating at same time?

**Comment by ksediqi** [comment]
Thanks! Manually installing .NET.... fixed the error.

**Comment by Seefer** [comment]
I found this Known Issue page detailing the problem related to this.

https://github.com/dotnet/core/issues/7062

**Comment by Froosh** [comment]
Updating Visual Studio to current version (I'm still using VS2019, so v16.11.8) solved the .NET 5.0.12 and .NET 3.1.21 issues for me.

**Comment by jespersh** [comment]
KB5009191 just managed to install today and it seems to have removed 6.0.1 installed by VS 17.1.0 preview 1.1 from my machine.

Was that intended?

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.210 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by dezsiszabi** [comment]
Same issue with `2022-02 .NET 6.0.2 Security Update for x64 Client (KB5011094)` via Windows Update.

**Comment by rbhanda** [comment]
hi @dezsiszabi can you please share the logs with us. You can send them to rbhanda@microsoft.com 

```
- Run http://aka.ms/vscollect.exe and share the resulting vslogs.zip that is created in %temp%

- Run the powershell cmdlet Get-WindowsUpdateLog and share the resulting windowsupdate.log file that is created on your desktop
```

**Comment by dezsiszabi** [comment]
Hi @rbhanda 

I sent the requested logs in email (hopefully mail won't be bounced back as size is around 10MB)

**Comment by Rand-Random** [comment]
Here we go again, same error with 6.0.2 update. :(

**Comment by danmoseley** [comment]
I don't know the cause, but installing 6.0.2 manually from https://dotnet.microsoft.com/en-us/download/dotnet/6.0 succeeded for me, then running Windows Update again cleared the error.

**Comment by Rand-Random** [comment]
@joeloff Sorry, for the late reply.
Here the requested log:
[WindowsUpdate.log](https://github.com/dotnet/core/files/8067254/WindowsUpdate.log)
 
Feel free to delete my comment after you got what you need, to "hide" potential private information.

**Comment by joeloff** [comment]
Thanks @Rand-Random

**Comment by kiwiant** [comment]
My Windows Updates were clear until just now immediately after upgrading to Visual Studio 17.1.

**Comment by Rand-Random** [comment]
@kiwiant most likely because 17.1 manually installed the 6.0.2, which is the recommended workaround to get rid of the error in windows update

**Comment by danmoseley** [comment]
Right, updating VS is apparently another option.

**Comment by kiwiant** [comment]
> @kiwiant most likely because 17.1 manually installed the 6.0.2, which is the recommended workaround to get rid of the error in windows update

Just to be clear this error only popped up after upgrading Visual Studio from 7.0 to 7.1 (ie, this upgrade caused the error to show rather than fix it).

**Comment by Rand-Random** [comment]
@kiwiant ah, sorry misunderstood you, I thought you meant the windows update immediately cleared after the update to 17.1

I wouldn’t know if the update would cause the issue or not I am on the preview channel so already had 17.1 preview when .net 6.0.2 got released 

@joeloff am I free to go and apply the workaround or do you want me to stay on the error in case you need more info?

**Comment by joeloff** [comment]
> @joeloff am I free to go and apply the workaround or do you want me to stay on the error in case you need more info?

No, please go ahead and patch your system. You should be able to just install the standalone SDK directly or update VS - the latter is probably the better route to take.

Here's a breakdown of the root cause.

In 17.1 Preview 2, we shipped a preview of SDK 6.0.200 along with the 6.0.1 runtimes. VS included a newer copy of some of the workload manifest installers compared to what was in the standalone SDK. Although the apphost/targeting packs come from the runtime, they are shipped as part of the SDK. So when MU scanned the system and detects the older packs, it will offer a new SDK. The SDK install will detect the manifest installers from VS and try to determine if their version is higher than the SDK's copies. Because the manifest installers populate the Language column in the Upgrade table, the setup engine tries to query the ProductLanguage property of the installed manifests.

(While upgrades generally trigger on the UpgradeCode, they can be extended to include the ProductLanguage of an MSI as well).

The engine queries the property against the unmanaged user context first instead of the machine context when running under local system (which is the default for MU). The property can only be queried under the machine context. Since the engine cannot determine if the ProductLanguage of the installed manifest MSI matches the language of the older copy it carries, it logs the error and then attempts to execute the MSI. The assumption here is that if the MSI is not installed to try and install it.

The manifest MSIs support upgrades, but running the older MSI triggers a launch condition that detects downgrades. This causes the MSI to fail and in turn fails the standalone SDK installation and thus the update.

When you run the standalone SDK manually and go through the UAC elevation, you're running under your user account with elevated privileges and the engine correctly queries the ProductLanguage property against the machine context, detects the downgrade and skips over executing the manifest MSI.

We placed a temporary blocker in some of the MU offerings to avoid running the SDK if it was installed by VS, but it did not catch all the previews of 6.0.200.

**Comment by Rand-Random** [comment]
@joeloff 
> or update VS - the latter is probably the better route to take.

Updated from 17.1 preview (latest - was it 6?) to 17.2 preview 1, restarted the PC but Windows Update still shows the error.
![image](https://user-images.githubusercontent.com/9868626/154241685-c71151dc-dab2-42fd-9788-d349d7e300a4.png)

So, should I go install the standalone SDK or do you want info/logs?
`dotnet --info` doesn't show that I have a 6.0.2 preview installed.

![image](https://user-images.githubusercontent.com/9868626/154242100-9d3576eb-2a6b-4894-9fb5-e29be9b96a27.png)

**Comment by SMHodges** [comment]
So what's the solution supposed to be? Installing the update from https://dotnet.microsoft.com/en-us/download/dotnet/6.0 does nothing to clear the error for me.

**Comment by joeloff** [comment]
Thank you for the updater. I'm still working on the repro and talking to a few other teams that handle the publishing of the updates.

**Comment by Rand-Random** [comment]
@joeloff 
If I am not mistaken, I found the files you are asking for
[log.zip](https://github.com/dotnet/core/files/8100526/log.zip)


Once again feel free to delete the comment, after you have what you need.

**Comment by joeloff** [comment]
will do, thank you

**Comment by cicorias** [comment]
This is still occurring now with 6.0.2 even after running the SDK for 6.0.2 which installed "ok" -- reboot and Windows Update is showing below, and `dotnet --list-sdks` shows installed. 

0x80070643 KB5011094


<img width="676" alt="image" src="https://user-images.githubusercontent.com/1080406/154804538-ac9888dc-7702-4ce6-9748-46cddb5d3177.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/1080406/154804555-de62439a-e538-4322-931b-56877bfacb88.png">

**Comment by joeloff** [comment]
Thank @cicorias I'm looking into the detection authoring. The NET 6.0.2 Update is actually a very broad classification and what's called the parent bundle and encapsulates all the various installers for the 6.0.2 release (the SDK, separate runtimes for .NET, Desktop, ASP.NET). It's possible something else is triggering an offering.

@Rand-Random I've been able to correlate some of the IDs in the logs you shared. Based on the scan/detection, the update agent is looking at three options

```
2022.02.09 09:28:38.4600099 7788  7292  Agent             Title = 2022-02 .NET 6.0.2 Security Update for x64 Client (KB5011094)
2022.02.09 09:28:38.4600116 7788  7292  Agent             UpdateId = 337C4049-17CF-431F-B6A4-255BF5BC852D.201
2022.02.09 09:28:38.4600121 7788  7292  Agent               Bundles 3 updates:
2022.02.09 09:28:38.4600136 7788  7292  Agent                 F6373F23-7FF6-412A-8CE8-BD1B8D4A261E.201
2022.02.09 09:28:38.4600148 7788  7292  Agent                 708EEB72-B8BA-4DF0-A342-F1212E1DF1D3.201
2022.02.09 09:28:38.4600181 7788  7292  Agent                 73C2FCEF-7D14-47D1-AA25-44F555FC6E0A.201
```

The first item (F6373...) is the 6.0.102 SDK. The 708EEB... one is ASP.NET Core 6.0.2 runtime and 73C2F... is the Desktop Runtime for 6.0.2

@csnellgrove1 I think I know what's going on and I'll sync with you on the details. Short of it is that the 6.0.101 SDK is present, but it bypasses the block because it's not installed by VS, but does interact with the lower versioned manifest.

@Rand-Random , @cicorias Can you try installing the 6.0.102 SDK yourself, then rerun the windows update and then have Windows Update recheck/scan.

**Comment by cicorias** [comment]
@joeloff  installing the 6.0.102 SDK worked in terms of getting Windows update to no longer offer it

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1080406/154851403-41511b08-2af9-4054-bea1-82305619cbc7.png">

**Comment by Rand-Random** [comment]
Can also verify installing 6.0.102 stops windows update from offering 6.0.2.

**Comment by DelWoodcock** [comment]
Updated VS2022 Preview to 17.2 preview 1 and I get the following error, retried a couple of times.
![image](https://user-images.githubusercontent.com/43828181/155380327-689b0efd-fc70-4956-958e-cbdc3a1b785b.png)

**Comment by DelWoodcock** [comment]
> Do you have any of the 6.0.100 SDKs installed (6.0.100 or 6.0.101)? If so, you can try manually installing the 6.0.102 SDK

Manually downloading and installing it fixed the issue, thanks.

**Comment by ptr727** [comment]
metoo, happened with 6.0.100, went away after manually installing sdk, error is back after installing vs 17.2.0 preview 1.
```
PS C:\Users\piete> dotnet --list-sdks
3.1.416 [C:\Program Files\dotnet\sdk]
5.0.211 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
```

**Comment by Rand-Random** [comment]
You need to install 6.0.102 sdk

**Comment by ptr727** [comment]
> You need to install 6.0.102 sdk

I just uninstall 6.0.101, no need to keep old SDK versions around.

**Comment by seantleonard** [comment]
6.0.3 installs from Windows update smoothly :) Thanks for getting this working out of the box!

**Comment by joeloff** [comment]
@seantleonard You're welcome. Glad to hear it's working for you.

**Comment by AraHaan** [comment]
![image](https://user-images.githubusercontent.com/15173749/157505236-cebe7864-c54d-49f5-af68-f482a162a659.png)

**Comment by joeloff** [comment]
@AraHaan is it still offering the 6.0.2 update? You should be getting the 6.0.3 offering at this point.

**Comment by AraHaan** [comment]
It is still yes.

**Comment by joeloff** [comment]
When you say 6.0.2, did you only install the runtime or did you install the 6.0.102 SDK. Updates are branded under the runtime version, but could include one or more SDK that's associated with the release.

**Comment by AraHaan** [comment]
> When you say 6.0.2, did you only install the runtime or did you install the 6.0.102 SDK. Updates are branded under the runtime version, but could include one or more SDK that's associated with the release.

The SDK installers for x86 and x64.

**Comment by PhantomGamers** [comment]
I was getting the error with 6.0.2 so I successfully installed the update manually, however I am getting the error again now with 6.0.3
![image](https://user-images.githubusercontent.com/844685/157594742-281e0661-4501-4da2-89ef-6345785eb832.png)

**Comment by milesbuckton** [comment]
I am also getting the same error for 6.0.3:
![image](https://user-images.githubusercontent.com/37063023/157620465-5c0c3584-a582-41e2-852e-b3de9b9b0b2b.png)

**Comment by Rand-Random** [comment]
I am have a different issue, hope it is okay, to post it here.
I did get the latest Windows Update offered, and it got installed correctly according to Windows Update.

![image](https://user-images.githubusercontent.com/9868626/157658784-a8a2b319-de9a-4d97-8187-ec3056d71653.png)
Hope the german User Intrace is understandable.

But out of curiosity I looked into "dotnet --info" and the version 6.0.3 is no where to be found
![image](https://user-images.githubusercontent.com/9868626/157658951-2d4f6c4b-c07e-4dba-9669-8b84b0bf9d91.png)

**Comment by jespersh** [comment]
@Rand-Random 
Could you check the x86 dotnet? I see it there, but not in x64 which it claims it installed:

```
C:\Users\jsh>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.212 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>>>  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>>>  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>>>  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>>>  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>>>  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>>>  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\jsh>"c:\Program Files (x86)\dotnet\dotnet.exe" --info

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>>>  Microsoft.AspNetCore.App 3.1.23 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>>>  Microsoft.AspNetCore.App 5.0.15 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
>>>  Microsoft.AspNetCore.App 6.0.3 [c:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>>>  Microsoft.NETCore.App 3.1.23 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>>>  Microsoft.NETCore.App 5.0.15 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>>>  Microsoft.NETCore.App 6.0.3 [c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
>>>  Microsoft.WindowsDesktop.App 3.1.23 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
>>>  Microsoft.WindowsDesktop.App 5.0.15 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
>>>  Microsoft.WindowsDesktop.App 6.0.3 [c:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Seems like it only installed the x86 version for 6.0.3?
I marked the lines from this update cycle with `>>>`


![image](https://user-images.githubusercontent.com/1004198/157660378-cc74c7b6-c8f0-44d1-b018-79a665962ef4.png)

**Comment by taspeotis** [comment]
Hello team,

I would expect someone would have ensured _the security updates_ could be installed every time. I realise Windows and .NET are both big and complicated products and patching them is non-trivial and I don't expect perfection with every patch but this is happened for 6.0.1 and 6.0.2 and now 6.03 and it happens with the .NET Core 3 and .NET 5 patches and well ... you'd think there's enough telemetry out there to fix the problem.

![image](https://user-images.githubusercontent.com/1189399/157662501-ade30288-2d83-49ca-a00d-c48d3ad195b2.png)

For now I am keeping myself up-to-date by using the VS Installer and hoping that the latest Visual Studio updates service .NET Core 3, 5, and 6 on my computer.

**Comment by Rand-Random** [comment]
@jespersh 
Yes, I do find 6.0.3 as x86

![image](https://user-images.githubusercontent.com/9868626/157670663-eba81c7f-8256-45c5-8d27-c8ad9924418d.png)

**Comment by PhantomGamers** [comment]
@jespersh ah according to `dotnet --info` the 6.0.3 runtime is installed but I only have the 6.0.201 SDK installed

**Comment by AraHaan** [comment]
The 201 SDK is 6.0.3 I think.

**Comment by Rand-Random** [comment]
@PhantomGamers 

That is to be expected as you can see here:
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Runtime Version and SDK Version are different.
They are even different between Visual Studio Versions.
Visual Studio 17.0.x uses SDK 6.0.103 but Visual Studio 17,1.x uses SDK 6.0.201.

But atleast your windows update did something as x64.
My x64 dotnet -info did nothing 
- no runtime 6.0.3
- no sdk 6.0.103
- no sdk 6.0.201

I would expected the sdk 6.0.201 to be installed as I am using Visual Studio 17.2 preview 1.0.
The only thing I got was the runtime 6.0.3 for x86.

**Comment by milesbuckton** [comment]
Hi @jespersh, `dotnet --info` does show that it is installed:

![image](https://user-images.githubusercontent.com/37063023/157854428-642b5858-c504-4770-8938-2741de21eb35.png)

**Comment by Rand-Random** [comment]
@milesbuckton 
If I had to guess, you need to manually install the 6.0.200 sdk to get rid of your windows update message.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.200-windows-x64-installer

Very basic explanation, of how I understand the problem
Windows Update seems to want everything, even older SDK version, but fails to deliver,

**Comment by milesbuckton** [comment]
@Rand-Random, you're a genius - thank you! Your solution worked for me! 😄 I uninstalled 6.0.201, then installed 6.0.103, 6.0.200, and 6.0.201 again. Now Windows Update is satisfied. See below:

![image](https://user-images.githubusercontent.com/37063023/158123907-ad30f60d-feaa-482c-b17e-591ba19fb6f5.png)

**Comment by AraHaan** [comment]
Sadly for me that is not an option as 6.0.2xx or so is part of Visual Studio and so uninstalling it might break the IDE.

**Comment by milesbuckton** [comment]
> Sadly for me that is not an option as 6.0.2xx or so is part of Visual Studio and so uninstalling it might break the IDE.
> 
> Edit: wish the IDE would not try to install the 6.x but instead the 7.x sdk's when you have only the preview version installed, else stable 6.x when non-preview install of vs2022.

Hi @AraHaan, I never uninstalled `Microsoft .NET SDK 6.0.201 (x64) from Visual Studio`, only the standard one `Microsoft .NET SDK 6.0.201 (x64)`. It appears both can coexist. See below:

![image](https://user-images.githubusercontent.com/37063023/158145386-090bbcc3-c0c1-449c-b99f-2ddb2ceef736.png)
