### ISSUE TITLE
error mscorlib.dll  The program '[21576] ConsoleDelegate.exe' has exited with code 0 (0x0)

### ISSUE THREAD

**Issue by bfernandezo** [dotnet/core#7049]
i have this problem (visual studio 2022)

[Program.txt](https://github.com/dotnet/core/files/7732127/Program.txt)

'ConsoleDelegate.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. 
'ConsoleDelegate.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\delta\source\repos\ConsoleDelegate\ConsoleDelegate\bin\Debug\ConsoleDelegate.exe'. Symbols loaded.
The program '[21576] ConsoleDelegate.exe' has exited with code 0 (0x0).

cod:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleDelegate
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Press A to simulate a button click");
            var key = Console.ReadLine();
            if (key == "a")
            {
                    KeyPressed();
                
            }

        }

        static void KeyPressed()
        {
            Button botton = new Button();

            botton.ClickEvent += (s, args) =>
            {
                Console.WriteLine("you clicked a bottom");
            };
            botton.OnClick();

        }

    }

    public class Button
    {
        public EventHandler ClickEvent;
        public void OnClick()
        { 
            ClickEvent.Invoke(this, EventArgs.Empty);
        }
    }

}

**Comment by jeffhandley** [comment]
Hello, @bfernandezo. In your program, once a key has been pressed, the `Main` function will complete and the console application will exit (successfully) since there's no loop keeping the program executing. You were likely intending to do something like this:

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleDelegate
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Press 'a' to simulate a button click. Press Enter to exit.");

            while (true)
            {
                var key = Console.ReadLine();

                if (key == string.Empty)
                {
                    break;
                }

                if (key == "a")
                {
                    KeyPressed();
                }
            }
        }

        static void KeyPressed()
        {
            Button button = new Button();

            button.ClickEvent += (s, args) =>
            {
                Console.WriteLine("You clicked a button");
            };

            button.OnClick();
        }
    }

    public class Button
    {
        public EventHandler ClickEvent;
        public void OnClick()
        {
            ClickEvent.Invoke(this, EventArgs.Empty);
        }
    }
}
```
