### ISSUE TITLE
Cannot connect to (localdb) from .NET Core except via Named Pipe on Windows 11 ARM 

### ISSUE THREAD

**Issue by benday** [dotnet/core#7050]
### Description

I'm trying to connect to SQL Server Express LocalDB from .NET Core 6 on Windows 11 ARM. If I use a connection string that refers to it using the instance name "Data Source=(localdb)\MSSQLLocalDB", it fails with the exception below. If I connect to it using a named pipe, it works.  

> Microsoft.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SNI_PN11, error: 56 - Unable to load the SQLUserInstance.dll from the location specified in the registry. Verify that the Local Database Runtime feature of SQL Server Express is properly installed.) ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application.

[I've created some simple MSTest unit tests to repro the problem](https://github.com/benday-inc/Benday.ArmDemo1). There are two test methods in the DatabaseConnectionFixture class that attempt to connect to LocalDB: one uses an ordinary connection string and the other uses a named pipe.  On Windows 11 ARM, the `ConnectToDatabase_ConnectionString()` method fails.  If I run this same code on Windows 11 x64, both tests pass.  

### Configuration
This is running on Windows 11 ARM in a Parallels VM on an M1 MacBook Pro.  The OS Build # is 22509.1011.  The dotnet core build is 6.0.100.

**Comment by jeffhandley** [comment]
Hello @benday. This issue will need be filed in the [dotnet/SqlClient](https://github.com/dotnet/SqlClient) repository. I apologize that I cannot transfer this issue to that repository on your behalf.

**Comment by benday** [comment]
Thanks, @jeffhandley.  Just resubmitted this as https://github.com/dotnet/SqlClient/issues/1441
