### ISSUE TITLE
dotnet comand cant be found on arm64 

### ISSUE THREAD

**Issue by John-Codes** [dotnet/core#7052]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jeffhandley** [comment]
Hello, @John-Codes. If you haven't done so yet, you'll need to follow the instructions to install the .NET SDK on your machine. You can find the relevant installers at https://dotnet.microsoft.com/en-us/download/dotnet/6.0, or the convenient short URL of https://get.dot.net.

If you had already installed the SDK and are still having difficulty, please create a new issue with more details about what you have installed, whether or not your PATH environment variable contains a path to the .NET SDK folder, and any other information that could help us reproduce or diagnose.

Thanks!
