### ISSUE TITLE
Feedback button doesn't work; command needs updated

### ISSUE THREAD

**Issue by Narvey** [dotnet/core#7053]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Simply enough, the page says to run `dotnet watch`, but in reality you need to run `dotnet watch run`.
However, when I try to press the feedback button to note this, it doesn't seem to do anything. It certainly doesn't provide a field for me to type in. I'm using FireFox 95.0

**Comment by ryank425** [comment]
Having an Adblock or tracking prevention plugin on your web browser prevents Feedback plugin from loading.

Please try a web browser with session that doesn't block it.

**Comment by jeffhandley** [comment]
Thanks for submitting this, @Narvey. The default for `dotnet watch` is to behave the same as `dotnet watch run`, so the "run" argument is optional. Please let us know if you were seeing an error when trying to use simply `dotnet watch` though.
