### ISSUE TITLE
Finding difficult to create app 

### ISSUE THREAD

**Issue by HarshithaRameshChandra** [dotnet/core#7059]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jeffhandley** [comment]
Hello @HarshithaRameshChandra. There isn't enough information provided here for us to be able to follow up. If you have more information you can provide such as what steps you were trying to take, and what was particularly difficult, please file a new issue. Thanks.
