### ISSUE TITLE
How Upgrade will be supported from .Net 6 to .Net 8

### ISSUE THREAD

**Issue by som-nitjsr** [dotnet/core#7060]
I have enterprise apps earlier we were targeting .net 4.8. Now we wanted to move to .net 6(LTS). but we have one of the major issue with 
upgrade. Our deployment lifecycle is around 3 years.  
 How we can run the.net 6 app targeting .net 8 without recompiling?

**Comment by svick** [comment]
Keep in mind that when you're switching from .Net *Framework* 4.8 to .Net 6, you're changing which framework you're using (.Net Framework vs. .Net Core/.Net), so you may need to do a lot of changes. But changing from .Net 6 to .Net 8 is a straight upgrade, so, apart from the documented breaking changed (e.g. [here's the list for .Net 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0?WT.mc_id=DOP-MVP-5002735)), there shouldn't be a problem.

About running the app on a newer .Net without recompiling, it depends on your deployment model. If you're using framework-dependent deployment, then [you can set `<RollForward>Major</RollForward>` in your project file](https://docs.microsoft.com/en-us/dotnet/core/versions/selection?WT.mc_id=DOP-MVP-5002735#framework-dependent-apps-roll-forward) to make it work.

**Comment by som-nitjsr** [comment]
Thanks @svick
