### ISSUE TITLE
Sur invite de commande > dotnet new console -o MyApp

### ISSUE THREAD

**Issue by mathieuishier** [dotnet/core#7065]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Message anomalie :
Le modèle « Application console » ne peut pas être créé.
Échec de la création du modèle.
Détails : Access to the path 'C:\Program Files\dotnet\MyApp' is denied..

Merci

**Comment by ondertipioglu** [comment]
You can not create the project in C:\Program Files\dotnet, because the default mode is inaccessible for this folder
You can run the command(dotnet new console -o MyApp) on desktop or any other path

**Comment by mathieuishier** [comment]
Thanks for your reply

**Comment by jeffhandley** [comment]
Thank you @ondertipioglu for helping out with this!
