### ISSUE TITLE
i need some help with visual studio.

### ISSUE THREAD

**Issue by abdulmohsinbakhsh** [dotnet/core#7066]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/modify
Operating System: windows

I added the script so that i can rotate the cube but when visual studio loaded there was no console for me to write and edit the code on. Could anyone help me please? Thank you...

**Comment by jeffhandley** [comment]
Hello @abdulmohsinbakhsh. Once Visual Studio launches, if the `SpinCube.cs` file fails to open automatically, you should be able to open it manually through the Solution Explorer.

![image](https://user-images.githubusercontent.com/1031940/147630030-eafdf0b8-bcaf-4d18-a011-1e20984a3667.png)

If the solution and project failed to open in Visual Studio, and the Solution Explorer is empty, then you should be able to find the project to open manually. Wherever you created the 3DCube project on your computer, there should be a `3DCube.sln` solution file with an `Assembly-CSharp.csproj` project file. Opening that solution file should give you access to the `SpinCube.cs` file to edit.

If this doesn't address your issue, please submit a new issue with more details about what you saw in Visual Studio once it launched.
