### ISSUE TITLE
az login

### ISSUE THREAD

**Issue by sveinfolkeson** [dotnet/core#7067]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/azure-tools
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try the az login command I am redirected to https://localhost:56982/?code=0.ATsASg3uVAsb4EmAt7Xl7kjFrpV3sATbjRpG... and the error message :
This site can’t provide a secure connectionlocalhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by jeffhandley** [comment]
Hello @sveinfolkeson. I was unable to reproduce this error on my machine, however I found this issue has been reported before in the Azure CLI project: https://github.com/Azure/azure-cli/issues/10426

I recommend reading through that issue's comments to see if those suggestions can help. There are also some alternate `az login` instructions in the documentation here: https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli#how-to-sign-into-the-azure-cli

If none of that helps, please file a new issue in the [Azure/azure-cli](https://github.com/Azure/azure-cli) repository with full reproduction steps and output.

Thanks!
