### ISSUE TITLE
Program.cs is hung up error CS8802

### ISSUE THREAD

**Issue by munmunlina** [dotnet/core#7074]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);

C:\Users\Munmunlina\MyApp>dotnet run
C:\Users\Munmunlina\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\Munmunlina\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by jeffhandley** [comment]
Hello @munmunlina. Thanks for submitting this issue.

That error leads me to believe you have another C# file in your MyApp folder, perhaps from a previous tutorial or step in the tutorial. If there are multiple C# files in the folder that have top-level statements (without being wrapped in classes/methods), then the compilation will fail with this message.

If `Program.cs` was the only C# file within this folder (or subfolders), then please reply here with the list of files and their contents that are in that folder.
