### ISSUE TITLE
command prompt issue

### ISSUE THREAD

**Issue by vaibhavbhardwajj** [dotnet/core#7077]
I was trying to create a console for vs code but it doesn't let me  do that

**Comment by jeffhandley** [comment]
Hello @vaibhavbhardwajj. I'm guessing that what you mean is that VS Code doesn't give you the ability to create a new .NET Console Application and/or edit/run one.

Please refer to the following documentation for working with .NET Core in VS Code:
* [Using .NET Core in Visual Studio Code](https://code.visualstudio.com/docs/languages/dotnet)
* [C# programming with Visual Studio Code](https://code.visualstudio.com/Docs/languages/csharp)

If the guidance from that documentation does not address your issue, please file a new issue with more details about where you are getting stuck. Thanks!
