### ISSUE TITLE
Erro de permissão

### ISSUE THREAD

**Issue by cristian-santos** [dotnet/core#7080]
Ao tentar criar uma aplicação, me deparo com esse erro: cannot snap-exec: cannot exec "/snap/dotnet-sdk/152/snap/command-chain/snapcraft-runner": permission denied

**Comment by jeffhandley** [comment]
Olá. Este erro é semelhante ao que foi relatado no dotnet/sdk#23197. Consulte esse assunto e adicione comentários conforme necessário. Vou encerrar esta edição como uma duplicata.

<details>
<summary>Machine-translated from English</summary>
Hello. This error looks similar to what was reported on dotnet/sdk#23197. Please refer to that issue and add comments as needed. I'm going to close this issue as a duplicate.
</details>
