### ISSUE TITLE
The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.   - No frameworks were found.  You can resolve the problem by installing the specified framework and/or SDK.

### ISSUE THREAD

**Issue by adammazinga** [dotnet/core#7087]
[adam@XBA API]$ dotnet run
Building...
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=archcraft-x6
![dotnet run error_sdk](https://user-images.githubusercontent.com/29223938/148151238-094705a9-5022-4649-a0db-6f485b1c9402.png)
I already have the dotnet core runtime and sdk installed; But I can't run the project.
Requesting for advice on how to go about this issue please.

**Comment by buyaa-n** [comment]
Seems you need to install AspNetCore runtime, hope this would help: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#install-the-runtime. Please close the issue if it fixes your issue, thanks

**Comment by janvanveldhuizen** [comment]
How did you solve this?
In my case ```Pacman -Sy dotnet-runtime``` didnt help

**Comment by adammazinga** [comment]
At the time, I rolled back to dotnet 5
![dotnetfix](https://user-images.githubusercontent.com/29223938/151132082-92240332-7c08-480c-89a9-912ad579d048.png)
And it worked fine for me.
You can however install your dotnet version 6 using this script [here](https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
).

**Comment by AhmedFathyDev** [comment]
```sh
# pacmac -S dotnet-sdk dotnet-runtime aspnet-sdk aspnet-runtime
```

**Comment by Bartleby2718** [comment]
For those of you who are getting this error on a Docker container, perhaps it's because you're using [`dotnet/runtime`](https://hub.docker.com/_/microsoft-dotnet-runtime) when you should be using [`dotnet/aspnet`](https://hub.docker.com/_/microsoft-dotnet-aspnet).

**Comment by smellahya** [comment]
> For those of you who are getting this error on a Docker container, perhaps it's because you're using [`dotnet/runtime`](https://hub.docker.com/_/microsoft-dotnet-runtime) when you should be using [`dotnet/aspnet`](https://hub.docker.com/_/microsoft-dotnet-aspnet).

can I have more details about this please, I have the same error in my docker container : 

Starting creatio-dev_app_1 ... done
Attaching to creatio-dev_app_1
app_1  | It was not possible to find any compatible framework version
app_1  | The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
app_1  |   - The following frameworks were found:
app_1  |       3.1.32 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
app_1  |
app_1  | You can resolve the problem by installing the specified framework and/or SDK.
app_1  |
app_1  | The specified framework can be found at:
app_1  |   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.10-x64

**Comment by Bartleby2718** [comment]
@smellahya Check the base image you're using. In my case, I had something like
```dockerfile
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
```
but it should've been
```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
```

**Comment by smellahya** [comment]
> @smellahya Check the base image you're using. In my case, I had something like
> 
> ```dockerfile
> FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
> ```
> 
> but it should've been
> 
> ```dockerfile
> FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
> ```

Here is my Dockerfile : 

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
EXPOSE 5000 5002
RUN apt-get update && \
apt-get -y --no-install-recommends install \
libgdiplus \
libc6-dev && \
apt-get clean all && \
rm -rf /var/lib/apt/lists/* /var/cache/apt/*
WORKDIR /app
COPY . ./
FROM base AS final
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT Development
ENV TZ US/Eastern
ENV COMPlus_ThreadPool_ForceMinWorkerThreads 100
ENTRYPOINT ["dotnet", "Terrasoft.WebHost.dll"]
