### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create Operating System: windows

### ISSUE THREAD

**Issue by frpkuller** [dotnet/core#7088]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Microsoft Windows [Version 10.0.19044.1288]
(c) Microsoft Corporation. All rights reserved.

C:\Users\jwm19>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\jwm19>dotnet new console -o MyApp

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.101

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\jwm19\MyApp\MyApp.csproj...
  Determining projects to restore...
  Restored C:\Users\jwm19\MyApp\MyApp.csproj (in 272 ms).
Restore succeeded.

C:\Users\jwm19>cd myapp

C:\Users\jwm19\MyApp>// See https://aka.ms/new-console-template for more information
'//' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jwm19\MyApp>Console.WriteLine("Hello, World!");
'Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jwm19\MyApp>program.cs

C:\Users\jwm19\MyApp>Console.WriteLine("Hello, World!")
'Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jwm19\MyApp>Console App
'Console' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jwm19\MyApp>Console
'Console' is not recognized as an internal or external command,
operable program or batch file.

**Comment by buyaa-n** [comment]
@frpkuller I am not sure what was your issue, looks like you did follow the instruction as needed until `cd myapp` command. After that seems you just pasted the source code into to command prompt or so, where you are supposed to run the app instead. Please run `dotnet run` command instead to see the result. 

Not sure if this solves your issue but I don't see any other issue or failure in your log. If the above was not your issue, please provide more info on what are you trying to do and/or on which step you stuck from the tutorial
