### ISSUE TITLE
watch : Waiting for a file to change before restarting dotnet...

### ISSUE THREAD

**Issue by andersenmats** [dotnet/core#7091]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: macos

I do the "Blazor Tutorial - Build your first Blazor app" but when I try to run the dotnet watch command I get this error "watch: Waiting for a file to change before restarting dotnet..."

What can I do to solve this problem?

**Comment by buyaa-n** [comment]
Probably you just need to clean the previous build outputs, please run:
- `dotnet clean`
- `dotnet restore`
before running the watch.

If it helps please close this issue

**Comment by andersenmats** [comment]
Now I try to run "dotnet clean" and "dotnet restore", but still get the same error. 

I have done exactly the same as the tutorial and everything works until I run the watch command.

**Comment by buyaa-n** [comment]
> Now I try to run "dotnet clean" and "dotnet restore", but still get the same error.

Could you try manually removing the `bin`, `obj` folder? I could not repro it, the tutorial works just fine for me, we need more info for a further investigation like the version of your macOS etc. Tagging @Pilchie for further triage

**Comment by holwon** [comment]
I have the same problem as you, but I found a solution.
This is because our computer does not have an HTTPS certificate installed.
You can try this code in terminal.
```pwsh
dotnet dev-certs https --trust
```

**Comment by boraaaydin** [comment]
For me it was a build error. Dotnet watch did not tell the error. I tried with dotnet run so after fixing build error, dotnet watch worked.
