### ISSUE TITLE
Require Sudo permission

### ISSUE THREAD

**Issue by krantikaridev** [dotnet/core#7095]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: linux

Running on Ubuntu
After following the instruction  https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap could not use dotnet but sudo dotnet worked

**Comment by ryank425** [comment]
Other people seem to have this issue as well. There is also a known workaround this for now.

https://github.com/dotnet/core/issues/4446#issuecomment-605629427

**Comment by buyaa-n** [comment]
cc @leecow

**Comment by leecow** [comment]
This issue has been resolved.
