### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by livingstonl** [dotnet/core#7096]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I see the installer pkg but I don't seem to have it installed because when I type dotnet in the terminal it says -bash: dotnet command not found
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
Please click `Download .NET SDK` button and install the dotnet
