### ISSUE TITLE
dotnet restore for f# missing reference

### ISSUE THREAD

**Issue by palutz** [dotnet/core#71]
#Hi,
I tried to create a F# project on Mac OsX Yosemite with the latest .Net Core.

> NET Command Line Tools (1.0.0-beta-001598)
> 
> Product Information:
>  Version:     1.0.0-beta-001598
>  Commit Sha:  7582649f88
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.11
>  OS Platform: Darwin
>  Runtime Id:  osx.10.11-x64
> 

The creation works fine, but when I tried to run the restore, I'm getting everytime an error:

> NotFound https://myget-2e16.kxcdn.com/artifacts/fsharp-daily/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json 

This is the verbose log of the restore command:og  : Restoring packages for 

> /Users/palutz/Projects/fsharp/dotnetcore01/project.json...
> info :   CACHE https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json
> info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/index.json
> info :   GET https://myget-2e16.kxcdn.com/artifacts/fsharp-daily/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json
> info :   NotFound https://myget-2e16.kxcdn.com/artifacts/fsharp-daily/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json 595ms
> info : Committing restore...
> log  : Restore completed in 1577ms.
> 
> NuGet Config files used:
>     /Users/palutz/Projects/fsharp/dotnetcore01/NuGet.Config
>     /Users/palutz/.nuget/NuGet/NuGet.Config
> 
> Feeds used:
>     https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
>     https://api.nuget.org/v3/index.json
>     https://www.myget.org/F/fsharp-daily/api/v3/index.json

I don't know if this is the reason why also the compile (run) is not working after.

Regards,
Stefano

**Comment by dasMulli** [comment]
Your version of the CLI is quite old. It should work with a new one from here: https://github.com/dotnet/cli

**Comment by palutz** [comment]
This is the version provided with the "official package" got directly from the "Getting started" page on the official site.
https://dotnet.github.io/getting-started/#/macosx
Which one is the latest version and how can I get it, pls?

**Comment by dasMulli** [comment]
The Readme.md on the cli github repo should be fine. The current os x link is: [https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-osx-x64.latest.pkg](https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-osx-x64.latest.pkg)

**Comment by palutz** [comment]
The result is exactly the same. Didn't change anything and didn't update anything, at least with the version number (maybe it wasn't updated).
Which version do you have on your Mac?

**Comment by dasMulli** [comment]
You'll need to remove the old one before.. it's a known bug with the installer (location of the `dotnet` executable was changed and an entries in `/etc/paths.d/dotnet` are not removed). If you installed globally (default afaik), you can `sudo rm -rf /usr/local/share/dotnet` and run the installer again.

**Comment by palutz** [comment]
I actually did it.
Anyhow, installing the new (just released) version solved all.
I used the uninstall script provided and the new installer.
Now the F# project is compiling and running. 
Nice!
