### ISSUE TITLE
Why my dot net step is not working. Someone please anwser. I am beginer

### ISSUE THREAD

**Issue by jaseelpalle** [dotnet/core#7104]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
> Why my dot net step is not working. Someone please anwser. I am beginer

Hi @jaseelpalle, we could not answer your question without knowing what problem you have encountered. Please give more info about the exact problem you are encountering, what info/message you are seeing in the console, which part of the code sample you were working on, and what steps were taken immediately before the problem occured etc.

Thanks!
