### ISSUE TITLE
.net installation

### ISSUE THREAD

**Issue by debb17** [dotnet/core#7105]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

even after installing the sdk it does not recognise the command

![net22](https://user-images.githubusercontent.com/82797686/148973467-397afb9c-daa3-4879-9dd3-730fc5a9d4ae.jpg)

**Comment by mairaw** [comment]
Did you close and open a new command prompt after the SDK installation?
