### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by smafrica** [dotnet/core#7114]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

>docker build -t pocmicro .
[+] Building 19.3s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.2s
 => => transferring dockerfile: 315B                                                                               0.1s
 => [internal] load .dockerignore                                                                                  0.2s
 => => transferring context: 68B                                                                                   0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0                                           19.1s
 => ERROR [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0                                        19.1s
------
 > [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0:
------
------
 > [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/aspnet/manifests/6.0": dial tcp 204.79.197.219:443: connect: no route to host

HERE DOCKER FILE:
![image](https://user-images.githubusercontent.com/63300783/149560813-7c5ba068-e23f-4b14-bf2a-39c8269f52ea.png)

**Comment by buyaa-n** [comment]
CC @shirhatti @nishanil

**Comment by Fydar** [comment]
Looks like an [internet or server issue](https://www.alphr.com/no-route-to-host-error-in-linux-what-to-do/#:~:text='No%20Route%20to%20Host'%20denotes,because%20of%20an%20inappropriate%20setup.) when attempting to download the ASP.NET image. Was this issue transient? Has it resolved itself?

**Comment by smafrica** [comment]
Yes, now it's working. Thanks a lot.

**Comment by mairaw** [comment]
Thanks for letting us know.

**Comment by MNHussain** [comment]
Please could you share how you resolved ?

**Comment by smafrica** [comment]
It seems a temporary network issue, thanks

**Comment by aleckendall** [comment]
This issue is happening to me. It has persisted for 24 hours.

```
[+] Building 0.2s (4/4) FINISHED                                                                                              
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 69B                                                                                      0.0s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 2B                                                                                          0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0                                               0.2s
 => CANCELED [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0                                               0.2s
------
 > [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:xxx: not found
Error response from daemon: No such image: xxx
```

**Comment by franciscocabezas** [comment]
Works to me too using --platform linux/amd64 running Docker an an Apple M1.
