### ISSUE TITLE
problem while dotnet new console

### ISSUE THREAD

**Issue by CoderSahel** [dotnet/core#7115]
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

this error is showing

**Comment by mairaw** [comment]
Hi @CoderSahel! Did you install the SDK already? Are you on a Windows machine?

If so, then you might be running into the issue explained at https://github.com/dotnet/core/issues/5962.

**Comment by CoderSahel** [comment]
no, I m on a ubuntu

**Comment by zezba9000** [comment]
Linux Snap installer has been busted since .NET 5 let alone .NET 6
https://github.com/dotnet/core/issues/4446

**Comment by mairaw** [comment]
How did you install the SDK on Linux then?

**Comment by zezba9000** [comment]
@mairaw For me I haven't tried installing in a while but think I used the install script or another manual method at the time.
./dotnet-install.sh -c Current

If you look here others have been finding the issues with Snap & work arounds: https://github.com/dotnet/core/issues/4446#issuecomment-1026116914

**Comment by mairaw** [comment]
Yeah I've seen multiple issues with snap installs unfortunately.
