### ISSUE TITLE
 983879

### ISSUE THREAD

**Issue by Vakosfuli** [dotnet/core#7117]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
@Vakosfuli please mention what problem you are encountering, else we could not help you. As this issue is not actionable by us i am closing it, next time if you see any issue/problem/error while following the tutorial please mentione what issue/error it was.

Thanks
