### ISSUE TITLE
 No executable found matching command "dotnet-ef" even after adding CLI

### ISSUE THREAD

**Issue by mehtanilay10** [dotnet/core#712]
I want to Migrate my Database with Models. I am using EF Core 2.0 Preview.

```
dotnet ef migrations add InitialCreate
dotnet : No executable found matching command "dotnet-ef"
```

### Packahe & Tools
I am already added all CLI and PM but still got error!

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview1-final" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview1-final" />
  </ItemGroup>

```

### Further technical details
```PM> dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
Version:            2.0.0-preview1-005977
Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.15063
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\
Microsoft .NET Core Shared Framework Host
Version  : 2.0.0-preview1-002111-00
Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by mehtanilay10** [comment]
It work perfectly from CMD but in VS 2017 15.3 it gives that error.

**Comment by Petermarcu** [comment]
@rowanmiller where is the best place to track this?

**Comment by mehtanilay10** [comment]
Create a new ASP.Net Core 2.0vproject using VS 2017 15.3
And add above packages from Nuget. And add CLI library, 
After adding CLI, i can use ```dotnet ef``` from CMD however in VS to give an error.

**Comment by rowanmiller** [comment]
Adding @divega and @ajcvickers who now own EF

**Comment by divega** [comment]
@bricelam does this ring any bells? Does it look to you like a possible issue in EF Core? If it is, we can move it there.

**Comment by mehtanilay10** [comment]
I am previously posted issue on EF Core.
https://github.com/aspnet/EntityFramework/issues/8996#issuecomment-311734955
But @bricelam told it follow up with CLI.
Now issue is for PMC only not CMD.

**Comment by livarcocc** [comment]
This only happens from VS? From the command line migration succeeds?

**Comment by bricelam** [comment]
@mehtanilay10 I thought the issue was resolved--you need to `cd` to the project directory before running `dotnet ef`.

**Comment by mehtanilay10** [comment]
Thanks @bricelam It works. I think that if i am selecting project from PMC's dropdown then it will automatically switch to that directory.

**Comment by divega** [comment]
>  I think that if i am selecting project from PMC's dropdown then it will automatically switch to that directory.

@mehtanilay10 I agree that would be nice. I am not sure changing the behavior of the PMC would be safe, but in any case https://github.com/NuGet/Home/ is a good place to provide that feedback.
