### ISSUE TITLE
'Console.WriteLine' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by zelihaaydogan** [dotnet/core#7120]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
Hi @zelihaaydogan, `Console.Writeline` is not a command, you are not supposed to type it into the CMD (Command line). That is the contect of code generated for you in the Program.cs file for you. if you want you can open that file from your file system and you would see that code.

Anyway, if `dotnet new console -o MyApp` and `cd MyApp` are only commands you need to run in that step, if those commands run successfully you could just continue to the next step. Please let us know if it helps
