### ISSUE TITLE
error, on rhel 7 checksum_mismatch for the package   dotnet-sdk-5.0.202-x64.rpm

### ISSUE THREAD

**Issue by lsstreet** [dotnet/core#7121]
### Description

repo: https://packages.microsoft.com/rhel/7/prod/

We are using Red Hat Satellite and often during the synchronisation for the repo https://packages.microsoft.com/rhel/7/prod/ we have errors like
 

{"checksum_type"=>"sha256", "expected_checksum"=>"6d9d4e5f2d50367aee889237fd29af87f95c95abbda0549dd9e318daa0c89a55", "error_code"=>"checksum_mismatch", "name"=>"dotnet-sdk-5.0", "actual_checksum"=>"5094b32ea172fdb7c8d15e1558501c35659aac9e52c6c203cbcfa52bb325574f"}

I made some investigation and in the xml file: https://packages.microsoft.com/rhel/7/prod/repodata/42d114f60b0c39b0f4dad45dae51f3fde7a21e9d08b1f139ec61e757216f128e-primary.xml.gz 
the checksum  for the packagedotnet-sdk-5.0.202-x64.rpm is:   
<checksum type="sha256" pkgid="YES">6d9d4e5f2d50367aee889237fd29af87f95c95abbda0549dd9e318daa0c89a55</checksum>

but I have checked directly checksum on the package and is different
# sha256sum dotnet-sdk-5.0.202-x64.rpm 
5094b32ea172fdb7c8d15e1558501c35659aac9e52c6c203cbcfa52bb325574f  dotnet-sdk-5.0.202-x64.rpm

I have downloaded the  dotnet-sdk-5.0.202-x64.rpm  on other hosts and all the time the   checksum for the package dotnet-sdk-5.0.202-x64.rpm is 5094b32ea172fdb7c8d15e1558501c35659aac9e52c6c203cbcfa52bb325574

Please remediate this issue.
Thank you

**Comment by lsstreet** [comment]
if this is not the rigth place to open such cases, please,if you know , give me a way where I could open a case destinated for the linux packages
 https://packages.microsoft.com/rhel/7/prod/
 
 Thank you

**Comment by buyaa-n** [comment]
Similar [issue](https://github.com/dotnet/core/issues/6904) might be helpful

**Comment by lsstreet** [comment]
> Similar [issue](https://github.com/dotnet/core/issues/6904) might be helpful

Thank you

**Comment by mihauck** [comment]
Hi @lsstreet, 

im facing the same problem with the SUSE Manager as a repository server.

`2022/01/30 12:00:05 +02:00 ERROR: Download failed: https://packages.microsoft.com/sles/15/prod/dotnet-sdk-5.0.202-x64.rpm - Target file isn't valid. Checksum should be 6d9d4e5f2d50367aee889237fd29af87f95c95abbda0549dd9e318daa0c89a55 (sha256).. Retrying...`


I think there is a problem with the package in  r [#5051](url) they reuploaded a packages with wrong checksum and it fixes the problem.

Checksum when i download the package
`> sha256sum dotnet-sdk-5.0.202-x64.rpm 
5094b32ea172fdb7c8d15e1558501c35659aac9e52c6c203cbcfa52bb325574f  dotnet-sdk-5.0.202-x64.rpm
`


Regards

**Comment by rbhanda** [comment]
Thanks a lot for reporting this issue. We found the problem and deleted the offending file from packages.microsoft.com. This should be resolved now
