### ISSUE TITLE
No wheels for macos 12 aarch64

### ISSUE THREAD

**Issue by sa-** [dotnet/core#7122]
### Description

```
> pip install dotnetcore2         
ERROR: Could not find a version that satisfies the requirement dotnetcore2 (from versions: none)
ERROR: No matching distribution found for dotnetcore2
```

### Configuration
Running on m1 macbook pro with macos 12.1
The issue seems to be that there are no wheels for this os/arch combo: https://pypi.org/project/dotnetcore2/#files

### Regression?
Unlikely

**Comment by bartonjs** [comment]
We're not contributors to https://pypi.org/project/dotnetcore2/ and unfortunately, all of the links for ownership on that page bring you to the dotnet/core pages.

.NET Core 2.1 went out of support on August 21, 2021.  We encourage you to move to a newer, supported version.  https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.

FYI: @leecow

**Comment by sa-** [comment]
Okay thanks
