### ISSUE TITLE
run code error

### ISSUE THREAD

**Issue by ansenchina-china** [dotnet/core#7126]
`D:\.net>dotnet new webapi -o mymicroservice --no-https -f net6.0
已成功创建模板“ASP.NET Core Web API”。

正在处理创建后操作...
在 D:\.net\mymicroservice\mymicroservice.csproj 上运行 “dotnet restore”...
  正在确定要还原的项目…
D:\.net\mymicroservice\mymicroservice.csproj : error NU1100: 无法解析 net6.0 的“Swashbuckle.AspNetCore (>= 6.2.3)”。
  未能还原 D:\.net\mymicroservice\mymicroservice.csproj (用时 165 ms)。
还原失败。
发布操作失败。
手动说明: Run 'dotnet restore'`

**Comment by mairaw** [comment]
Sometimes, error NU1100 happens because the `%appdata%\NuGet\NuGet.Config` file didn't have the package source configured it correctly.

So, can you make sure it lists https://api.nuget.org/v3/index.json as a package source?
