### ISSUE TITLE
Installing .net 6.0 on zsh

### ISSUE THREAD

**Issue by zsholl** [dotnet/core#7127]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am running into a command not found error and I am not sure how to fix it. I am new to .net and trying to learn C#.

**Comment by mairaw** [comment]
Check if the SDK installed successfully:
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos

Are you on a M1 machine?

**Comment by irving-frias** [comment]
You have to create a symbolic link, `ln -s  /usr/local/share/dotnet/dotnet /usr/local/bin`

close and open terminal and your terminal will recognize the "dotnet" command.
