### ISSUE TITLE
dotnet command not found on MacOs

### ISSUE THREAD

**Issue by dalymople** [dotnet/core#7128]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet was not available in terminal immediately after install on M1 mac.
`-bash: dotnet: command not found`

Had to run command:
`ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/bin/`

It works after doing that.

**Comment by mairaw** [comment]
Did you install the Arm64 version or the x64? For M1, it should be the Arm64. 

We're investigating how we can display the right version depending on your machine in the future.
