### ISSUE TITLE
I am facing problem accessing dotnet on macOS terminal

### ISSUE THREAD

**Issue by uttamk1408** [dotnet/core#7134]
I installed the sdk from this link https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-macos-x64-installer

Operating System: macos

After finishing dotnet 6.0 sdk installation when I try to check dotnet on the terminal it returns "command not found: dotnet".

I am new to macOS. I am not sure what is going wrong.

**Comment by allprogrammers** [comment]
Hi,

Did you uncheck any options related to PATH while installing dotnet ?

if yes then you can either uninstall and reinstall with the option enabled. 

Or

you can follow this here https://stackoverflow.com/questions/53030531/dotnet-command-not-found-in-mac

**Comment by bartonjs** [comment]
Did you try closing the terminal window and opening a new one?  The installation process may install to a place that isn't already in your ${PATH} environment variable, but potentially registers it at the end.

**Comment by mairaw** [comment]
Also, are you on a M1 machine? Just trying to confirm whether you should have installed the arm64 version instead.

**Comment by uttamk1408** [comment]
Thank you all for you quick response. It was path issue. After placing dotnet in \usr\local\bin folder it solved the issue.
