### ISSUE TITLE
cant install dotnet

### ISSUE THREAD

**Issue by SanyamThaKuR** [dotnet/core#7135]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

already installed dotnet but still when executing command  "dotnet" on command line  shhowing:
zsh: command not found: dotnet
 macos m1 2020 ; version 12.1

**Comment by bartonjs** [comment]
Did you try closing the terminal window and opening a new one? The installation process may install to a place that isn't already in your ${PATH} environment variable, but potentially registers it at the end.
