### ISSUE TITLE
zsh: command not found: dotnet

### ISSUE THREAD

**Issue by irving-frias** [dotnet/core#7136]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by bartonjs** [comment]
Your dotnet SDK installation might not have finished successfully. Please download the SDK by clicking on the `Download .NET SDK` button appropriate for your CPU architecture at https://dotnet.microsoft.com/en-us/download (on the macOS tab) and then run/install it on your machine.

If this step was successful you might need to restart your terminal, close and reopen the terminal and run the `dotnet` command again, please let us know if that helps.
