### ISSUE TITLE
i am starting to learn .net 

### ISSUE THREAD

**Issue by Mudassirak** [dotnet/core#7144]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when I try to create my app it gives the below error.
C:\WINDOWS\system32>dotnet new console -o MyApp

Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download#

please help me

**Comment by sipi41** [comment]
1) Dont work in your system32 folder, that's a system folder, you don't need to be in a system folder to create a .net app.
2) Before using dotnet, please use the following command: "dotnet --version", if you see an error, dotnet is not installed and you should download it from https://dotnet.microsoft.com/en-us/download then try again.

good luck!

**Comment by mairaw** [comment]
Did you install the SDK @Mudassirak? If so, you might be encountering the issue explained at https://github.com/dotnet/core/issues/5962

Let us know if this helps.
