### ISSUE TITLE
dotnet run

### ISSUE THREAD

**Issue by ceana8** [dotnet/core#7145]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant
<img width="1440" alt="Screenshot 2022-01-27 at 02 08 17" src="https://user-images.githubusercontent.com/89811997/151317267-b190d315-5e11-4fa8-add4-c1f9cdb9c7bf.png">
The "Hello World" string is not displayed on my terminal. 
<img width="1440" alt="Screenshot 2022-01-27 at 02 11 34" src="https://user-images.githubusercontent.com/89811997/151317742-11a9b247-7bff-469b-8ff2-50e6452e2745.png">

**Comment by bartonjs** [comment]
@ceana8 You appear to be missing the `cd MyApp` which is the second instruction on the previous (create) tutorial:  https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

**Comment by mairaw** [comment]
Let us know if the tip from @bartonjs helps you to continue
