### ISSUE TITLE
dotnet new console -o MyApp

### ISSUE THREAD

**Issue by amep-lotus** [dotnet/core#7146]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by amep-lotus** [comment]
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
Have you installed the SDK and started a new command prompt window? You could be running into this path issue: https://github.com/dotnet/core/issues/5962 

The solution is explained there.

Let us know if this helps.
