### ISSUE TITLE
Root Element is missing?

### ISSUE THREAD

**Issue by D8G** [dotnet/core#7147]
When I started coding 3 days ago, I tried to run my code. It doesn't work when I input "dotnet run" in the terminal because it says that the root element is missing. I tried uninstalling and installing the SDK download, but that doesn't work. Any suggestions?

**Comment by kmldpsng** [comment]
Hi @D8G 

I believe you don't need to use the command "run". You just need to provide the filename after "Dotnet", like: 

`dotnet myapp.dll`

You should be able to run without any issue. However, if the issue still persists please share the complete version of dotnet you are using.
You can refer the document:
[https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run](url)

Thanks

**Comment by bartonjs** [comment]
Off the top of my head it sounds like your .csproj is corrupt.  It should be an XML file that has Project as the root element.  Usually it's pretty slim, like


```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

though probably with a newer TargetFramework value.


If you've correupted your project file you can create a new project with `dotnet new`, and the same project kind (e.g. `dotnet new console`) in a clean directory, then copy the project file from that other directory over top your original one.
