### ISSUE TITLE
dotnet run dosen't work

### ISSUE THREAD

**Issue by SiamIslam077** [dotnet/core#7149]
`Problem` encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
``
C:\Users\siams>dotnet run
Couldn't find a project to run. Ensure a project exists in C:\Users\siams, or pass the path to the project using --project.

**Comment by mairaw** [comment]
You probably missed one of the commands on the previous page. You need to first do `cd myApp` to enter the project directory. 

Can you try that and then let us know if this works?
