### ISSUE TITLE
Missing Program.cs file from MyApp

### ISSUE THREAD

**Issue by areyes2022** [dotnet/core#7152]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: Windows 10 Home

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 
I'm unable to find Program.cs file from MyApp folder to complete the Edit your Code step. Did I miss any step? Thanks.

![Missing Program cs](https://user-images.githubusercontent.com/98561388/151677879-62161381-c378-4c4d-af73-1a7252db3b30.JPG)

**Comment by mairaw** [comment]
It's right there

![image](https://user-images.githubusercontent.com/12971179/151683118-e4b83b85-1ee1-4919-a6cb-8571594df3c4.png)

Windows hides the file extension depending on your system is configured. Let us know if this helps.

**Comment by areyes2022** [comment]
Thank you! I appreciate the help.

**Comment by mairaw** [comment]
Closing the issue. But let us know if you run into any other issues.
