### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Vukan55** [dotnet/core#7153]
hello,i downloaded fantome,when i want to openit i need .net,when i downloaded .net this happened,also i have 64 bit pc
![слика_2022-01-30_195018](https://user-images.githubusercontent.com/98709133/151713174-867d243e-c21c-4a3a-8a56-363457d2f081.png)
help me pls @microsoftCSE

**Comment by Vinigas** [comment]
Let's begin by naming Issues correctly. Naming issue "help" is unhelpful, spammy and disrespectful. Don't act entitled.

Second, send detailed machine hardware configuration including OS version.

**Comment by bartonjs** [comment]
cc @NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
@Vukan55 it seems that you attempted to install arm64 .NET on x64 machine. Correct installer can be found here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0 Please select x64 Windows installer from the "SDK 6.0.101" table.

**Comment by mairaw** [comment]
Can you let us know if the issue is fixed after you install the correct version?
