### ISSUE TITLE
Deployment did not work.

### ISSUE THREAD

**Issue by ggariepy** [dotnet/core#7155]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

kubectl get service mymicroservice --watch  command provides the following display:

NAME             TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)        AGE
mymicroservice   LoadBalancer   10.0.98.143   104.42.13.58   80:31176/TCP   24m

...but navigating to http://104.42.13.58/WeatherForecast results in a "this site cannot be reached."

**Comment by mairaw** [comment]
I can open that URL just fine @ggariepy

**Comment by ggariepy** [comment]
It "started working" for me this morning.  There must have been a crazy delay in the startup of the software.  Thank you, @mairaw for taking a moment to look into this for me.
