### ISSUE TITLE
"Error CS8802: Only one compilation unit" running .NET tutorial

### ISSUE THREAD

**Issue by RizzKid1** [dotnet/core#7156]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
C:\Users\mt15k\MyApp>dotnet run
C:\Users\mt15k\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\mt15k\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

Running Microsoft Windows 11 Pro, version 10.0.22000 build 22000.

**Comment by mairaw** [comment]
What are the contents of your `MyApp` directory? The `dotnet new console -o MyApp` command should have only created one .cs file called Program.cs with the following content:

```cs
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

Did you change anything in the project?

**Comment by RizzKid1** [comment]
C:\Users\mt15k\MyApp>dir

Volume in drive C is OS

Volume Serial Number is C4BD-2029

 

Directory of C:\Users\mt15k\MyApp

 

01/31/2022  10:31 PM    <DIR>          .

01/31/2022  10:23 PM    <DIR>          ..

01/31/2022  10:28 PM    <DIR>          bin

01/31/2022  10:27 PM    <DIR>          myapp

01/31/2022  10:31 PM               249 MyApp.csproj

01/31/2022  10:28 PM    <DIR>          obj

01/31/2022  10:31 PM               105 Program.cs

               2 File(s)            354 bytes

               5 Dir(s)  25,490,673,664 bytes free

 

C:\Users\mt15k\MyApp>type program.cs

∩╗┐// See https://aka.ms/new-console-template for more information

Console.WriteLine("Hello, World!");

 

C:\Users\mt15k\MyApp>

 

You’ll see some strange characters before the “//See https:…”. They don’t show up when I use Notepad to view it.

 

I reran the tutorial and get the same problem.

**Comment by mairaw** [comment]
You seem to have another myapp directory inside this project. Maybe delete everything and try again? Or just delete that internal myapp folder? If you ran the command inside the MyApp folder, it would create another Program.cs file causing this issue.

**Comment by RizzKid1** [comment]
Deleted it all, started over, and it works. Thanks for the quick help.

**Comment by mairaw** [comment]
Glad to hear. Closing the issue then.
