### ISSUE TITLE
.net issue

### ISSUE THREAD

**Issue by XFactors8** [dotnet/core#7157]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos monterey version 12.1 m1 max 
"zsh: command not found: dotnet"

**Comment by mairaw** [comment]
Which version of the SDK did you install? For M1, the correct one would be Arm64.

**Comment by XFactors8** [comment]
i tried both. none of them is working should i add it in the PATH?
