### ISSUE TITLE
Suggestion: Partner with SlickEdit

### ISSUE THREAD

**Issue by tarekgh** [dotnet/core#716]
@clrjunkie commented on [Tue Jun 27 2017](https://github.com/dotnet/corefx/issues/21615)

I recently evaluated the SlickEdit code editor and was totally blown by its speed and feature-set.

I installed it inside a VM running Ubuntu Desktop with 4GB ram/2 proc and honestly I couldn't sense a VM environment in any way.

I highly recommend the team reach out and discuss .NET Core support. It would be super to have it as an additional cross-platform editor alongside other offerings like JetBrains Rider.

https://www.slickedit.com

---

@danmosemsft commented on [Tue Jun 27 2017](https://github.com/dotnet/corefx/issues/21615#issuecomment-311430084)

@richlander 

---

@karelz commented on [Wed Jun 28 2017](https://github.com/dotnet/corefx/issues/21615#issuecomment-311826165)

That is .NET Core broad suggestion, beyond CoreFX scope. Should we move it to dotnet/core repo? @richlander

**Comment by tarekgh** [comment]
I moved  it to the core repo.

**Comment by richlander** [comment]
I would suggest SlickEdit users reach out to the developers of that product to ask for .NET support. That is even better than me (for example) reaching out. We would be happy to partner with SlickEdit at the point that they want to move forward.

The best place for SlickEdit to look is [OmniSharp](https://github.com/omnisharp). That is what VS Code uses.

**Comment by richlander** [comment]
Closing. No specific action for the team to take now. Happy to chat later.

**Comment by clrjunkie** [comment]
Reached out:

https://community.slickedit.com/index.php/topic,15336.0.html

**Comment by Petermarcu** [comment]
@richlander , how do you want to track this? I don't know that keeping this issue open is the best way.

**Comment by leecow** [comment]
The SlickEdit folks acknowledged the feature request and marked the post 'logged' so I think tracking at this point happens on their side? Looks like releases happen ~1/yr and v22 released a couple weeks ago.

**Comment by Petermarcu** [comment]
Ok, I'll close this now then
