### ISSUE TITLE
Can't use dotnet new

### ISSUE THREAD

**Issue by boburshoh01** [dotnet/core#7160]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

The problem is that I can't create new File with dotnet new. 

![Screenshot from 2022-02-03 21-52-15](https://user-images.githubusercontent.com/61194246/152391246-7df6bfa8-414d-4648-ae95-fa62e57c3d5b.png)

**Comment by greenEkatherine** [comment]
The error message says that .NET SDK is not found. Installation of this might not finished successfully. Please try to install it from the link mentioned in the error message https://aka.ms/dotnet-download After that you need to restart terminal and try again. Please let us know if it helps
