### ISSUE TITLE
لايستجيب 

### ISSUE THREAD

**Issue by same66** [dotnet/core#7162]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by same66** [comment]
لايستجيب التتبيت     برنمج تشغيل  الستلايت

**Comment by greenEkatherine** [comment]
> لايستجيب التتبيت برنمج تشغيل الستلايت

Is it an error message? Could you please try to translate it in English? I cannot find anything relevant

**Comment by greenEkatherine** [comment]
Sorry, we cannot identify the issue, closing.
