### ISSUE TITLE
No templates matched the input template name: blazorserver.

### ISSUE THREAD

**Issue by Fasunle** [dotnet/core#7165]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

`
dotnet new blazorserver -o BlazorApp --no-https
`
No templates matched the input template name: blazorserver.

**Comment by greenEkatherine** [comment]
It looks like you don't have `blazorserver` template. Please make sure that you have the latest .NET SDK https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
