### ISSUE TITLE
dotnet watch requires an addional parameter run

### ISSUE THREAD

**Issue by Quedak** [dotnet/core#7169]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by greenEkatherine** [comment]
Could you please provide an example?

**Comment by Quedak** [comment]
you can try it here
https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run

you need to use dotnet watch run (not just dotnet watch); and it seems it is something that is required for this particular tutorial (Link above).

**Comment by greenEkatherine** [comment]
> you can try it here https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
> 
> you need to use dotnet watch run (not just dotnet watch); and it seems it is something that is required for this particular tutorial (Link above).

I tried, it worked for me without `run`. @mairaw could you please help?

**Comment by Quedak** [comment]
not working for me... if I just dotnet watch in the MyWebApp folder nothing is happening... it maybe tells DotNet to watch the application folder for changes, but it is not starting the application. I have to say dotnet watch run - then the application is started and my default browser is opened with the application... then I can make a change to the application and see that it is being rebuilt and the updates can be seen in my web browser if I refresh it (F5)... With just dotnet run the application is started, but changes are not watched... so, I think the tutorial really meant to say dotnet watch run... unless I missed soemthing

**Comment by mairaw** [comment]
I need to update the tutorial to make it clear that you need .NET 6 SDK for the tutorial to work. The install step points to .NET 6 SDK download, but it's not clearly called out.

**Comment by mairaw** [comment]
Tutorial has been updated.
