### ISSUE TITLE
.NET Core 2.0 Preview 2 won't install in Ubuntu 16.04.2

### ISSUE THREAD

**Issue by MaximoTrinidad** [dotnet/core#717]
Thanks for your interest in .NET Core. 

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

I have follow both installation instructions in GitHub and the .NET Core Download page.  I'm getting the same error message:
```
Unpacking dotnet-sdk-2.0.0-preview2-006497 (2.0.0-preview2-006497-1) ...
dpkg: error processing archive /var/cache/apt/archives/dotnet-sdk-2.0.0-preview2-006497_2.0.0-preview2-006497-1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/dotnet/store/x64/netcoreapp2.0/microsoft.identitymodel.protocols/2.1.3/lib/netstandard1.4/Microsoft.IdentityModel.Protocols.dll', which is also in package dotnet-dev-2.0.0-preview1-005977 2.0.0-preview1-005977-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/dotnet-sdk-2.0.0-preview2-006497_2.0.0-preview2-006497-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Any suggestions!

**Comment by Petermarcu** [comment]
If you remove Preview1, perhaps it will get rid of the problem? `dotnet-dev-2.0.0-preview1-005977`

/cc @livarcocc it looks like we're installing the same thing to the same location and getting a conflict.

**Comment by MaximoTrinidad** [comment]
Thanks @Petermarcu!  I'll give it a try and see if uninstalling the previous version will clear the issue.
:)

**Comment by Petermarcu** [comment]
Thanks @MaximoTrinidad let us know.

**Comment by MaximoTrinidad** [comment]
HURRAY!!! @Petermarcu 

Someone need to add this additional step in the instruction:

1. remove previous version:
```
sudo apt remove dotnet-dev-2.0.0-preview1-005977
```
2. Then, install the latest one:
```
sudo apt-get install dotnet-sdk-2.0.0-preview2-006497
```

I got it loaded now.

![dotnet_fix_2017-06-29_11-01-01](https://user-images.githubusercontent.com/19892435/27695949-50724b84-5cbe-11e7-8fa4-66dcc59db83e.jpg)

Thanks for the tip!

**Comment by Petermarcu** [comment]
Glad to hear it! I've copied this issue to the dotnet/cli repo because you definitely shouldnt have had to uninstall preview1. I'm going to close this issue here now. Thanks for reporting it!

**Comment by Petermarcu** [comment]
@richlander @leecow can we get a note on the instructions that Preview1 of the sdk needs to be uninstalled?

**Comment by leecow** [comment]
Notes added to the download page, known issues doc and made the requirement more obvious on the Preview getting started page.

**Comment by MaximoTrinidad** [comment]
@Petermarcu!!  Awesome!  Thanks again.
:)
