### ISSUE TITLE
zsh: command not found: dotnet (arm)

### ISSUE THREAD

**Issue by INGCRENGIFO** [dotnet/core#7170]
### Description

Problem encountered on https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.101-macos-arm64-installer
Operating System: macOS Monterey 

https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.101-macos-arm64-installer
successful installation
open iterm (zsh) dotnet

`zsh: command not found: dotnet`

"without rosetta"

**Comment by greenEkatherine** [comment]
It looks like an issue with symlink, please try to set it up manually:
`ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/bin/`
Please let us know if it helps.

**Comment by INGCRENGIFO** [comment]
@greenEkatherine I solved it doing what do you say

`sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin`

It's strange, will I have that error if I update at some point?

**Comment by greenEkatherine** [comment]
> It's strange, will I have that error if I update at some point?

I'm not sure, might it change the path? Maybe only if /x64/ will add.

**Comment by INGCRENGIFO** [comment]
x64 does not exist, since I have installed the version for arm (mac m1)

**Comment by greenEkatherine** [comment]
> x64 does not exist, since I have installed the version for arm (mac m1)

Ah, sorry, got it. I don't know then, you may ask in the thread https://github.com/dotnet/sdk/issues/22910. I'm closing this issue as a duplicate.
