### ISSUE TITLE
.NET February 2022 Update - .NET 6.0.2, .NET 5.0.14

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7172]
Release Notes
[6.0.2](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.2/6.0.2.md)
[5.0.14](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.14/5.0.14.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 6.0.102 | 5.0.405| 5.0.211|
|--|--|--|--| 
| Ubuntu 18.04  |✅|✅|✅|   
| Ubuntu 20.04  |✅|✅|✅|  
| Ubuntu 21.04  |✅|✅|✅|   
| Centos 7     | ✅|✅|✅|    
| Debian 9     | ✅|✅|✅|  
| Debian 10   | ✅|✅|✅|  
| Debian 11   | ✅|✅|✅|
| Fedora 33   | ✅|✅|✅|   
| Fedora 34   | ✅| ✅|✅|
| OpenSUSE 15   |✅|✅|✅|  
| Oracle  |✅ |✅|✅| 

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any more issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

#### .NET 6.0.2
- [ ] There have been limited reports of a failure to install the update via Microsoft Update on Windows 11.  The update fails with error code 0x80070643.  A workaround is to install the package that is failing manually by downloading it from the [.NET 6.0.102 x64 SDK download site](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.102-windows-x64-installer), then scanning again. 

- [ ] We are aware of an [issue](https://github.com/dotnet/core/issues/7176) where some customers are unable to run Windows Forms apps built against 6.0.2. This appears a result of Windows Desktop servicing ref packs in 6.0.2.  This was reported on https://github.com/dotnet/winforms/issues/6663 . A workaround is added to the https://github.com/dotnet/core/issues/7176

**Comment by dezsiszabi** [comment]
The same issue happens with this release when trying to update via Windows Update:
- https://github.com/dotnet/core/issues/7062
- https://github.com/dotnet/core/issues/7044

Manually downloading and installing works.

**Comment by suprak** [comment]
After updating to SDK 6.0.102 we are seeing that our WPF app compiles references the following,

> // PresentationCore, Version=**6.0.2.0**, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (unresolved)
> // PresentationFramework, Version=**6.0.2.0*, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (unresolved)

However with SDK 6.0.101 (previous) references,
> // PresentationCore, Version=**6.0.0.0**, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (unresolved)
> // PresentationFramework, Version=**6.0.0.0**, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (unresolved)

The difference means that our app will not launch for folks on the 6.0.1 runtime (they must update to 6.0.2).

Is this expected behavior?

**Comment by leecow** [comment]
@marcpopMSFT - any ideas on https://github.com/dotnet/core/issues/7172#issuecomment-1034105137?

**Comment by twenzel** [comment]
6.0.2 breaks our web application build with error `CS2015 'xy.png' is a binary file instead of a text file` .
https://developercommunity.visualstudio.com/t/NET-SDK-60200-breaks-build-due-to-CS2/1667603?ref=native&refTime=1645007418972&refUserId=91f26041-a17a-4035-a156-3704387e57e3

**Comment by dhedey** [comment]
For the benefit of others searching here for a configuration error / breaking change new in dotnet 6.0.2, I've reported this issue: https://github.com/dotnet/runtime/issues/61577#issuecomment-1044959384

Environment variable configuration set up with a prefix containing `__` no longer matches to environment variables with that prefix. I've added a suggested workaround in the above linked comment.

The issue may surface as new/unexpected errors like `Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')` or other configuration-related exceptions.

**Comment by laxmanrapolu** [comment]
With 5.0.14 update our project ran into below error. 5.0.13 is working fine. We don't see deps.json file in 5.0.14 folder anymore.
Cannot use file stream for [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.14\Microsoft.NETCore.App.deps.json]: No such file or directory Error initializing the dependency resolver: A fatal error was encountered, missing dependencies manifest at: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.14\Microsoft.NETCore.App.deps.json
