### ISSUE TITLE
I just want to run simple code and this happened

### ISSUE THREAD

**Issue by catninjaOG** [dotnet/core#7175]
![image_2022-02-08_205018](https://user-images.githubusercontent.com/54153400/153106542-e6ea4981-369b-4261-9f33-829815875632.png)
![image_2022-02-08_205058](https://user-images.githubusercontent.com/54153400/153106599-9b243938-153d-4397-9013-30a24f6473e9.png)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You might have created a new MyApp project inside that folder and so `dotnet run` doesn't know which Program.cs to choose.
Can you check what are the contents of your MyApp folder and share your findings?

You can also delete everything and start over and see if that helps.

**Comment by catninjaOG** [comment]
> You might have created a new MyApp project inside that folder and so `dotnet run` doesn't know which Program.cs to choose.
> 
> Can you check what are the contents of your MyApp folder and share your findings?
> 
> 
> 
> You can also delete everything and start over and see if that helps.

Idk how to comment on this site I think this is how you do it but yes deleting and redoing it did work, thanks
