### ISSUE TITLE
Issue building with Windows Desktop 6.0.2

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#7176]
We are aware of an issue where some customers are unable to run Windows Forms apps built against 6.0.2. This appears as a result of Windows Desktop servicing ref packs in 6.0.2. 

This was reported on https://github.com/dotnet/winforms/issues/6663 (Windows Forms) and in https://github.com/dotnet/core/issues/7172#issuecomment-1034105137 (WPF). We are working on a fix for this and will update this thread once we have a resolution.

### Workaround

Add to the Project file and rebuild:

```
<ItemGroup>
<FrameworkReference
Update="Microsoft.WindowsDesktop.App;Microsoft.WindowsDesktop.App.WPF;Microsoft.WindowsDesktop.App.WindowsForms"
TargetingPackVersion="6.0.0" />
</ItemGroup>

```
Adding this will explicitly override the WindowsDesktop targeting pack used by the .NET 6.0.102 SDK, with the 6.0.0 WindowsDesktop targeting pack. This way you can use the .NET 6.0.102 SDK without using the broken .NET 6.0.2 WindowsDesktop targeting pack.

**Comment by philfontaine** [comment]
FYI, the workaround needs to be added to **all** the projects that use WPF/WinForms, not just the one being built.

**Comment by pmeems** [comment]
I found this workaround from https://github.com/dotnet/winforms/issues/6663.
I was having that issue in a Github Action for my 'x86 build and run unit test' only.
My x64 version had no issues.
After adding the suggested lines to my project, my unit tests (which uses some methods from my WinForm project) are working again.

**Comment by RussKie** [comment]
@ebussa  [arm64 packages](https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Runtime.win-arm64/) are also at 0. This likely an indication of very niche market for these platforms. Developers and end users generally gets these packs with .NET SDK or .NET runtime downloads, and NuGets probably get downloaded by CI/CD pipelines.
In either case your question is orthogonal to the issue discussed here, let's stay on the topic.

**Comment by ebussa** [comment]
I believe this error is related to the issue so I'll share it here. I have a WPF app that should compile to a single file but fails with the error "error netsdk1112: the runtime pack for microsoft.windowsdesktop.app.runtime.win-x86 was not downloaded." I have restoration of missing packages enabled during the build.

**Comment by menees** [comment]
This workaround isn't working for my [MegaBuild](https://github.com/menees/MegaBuild) solution's [.exe project](https://github.com/menees/MegaBuild/blob/master/src/MegaBuild/MegaBuild.csproj). When I comment out the `<UseWpf>` property and comment out the few lines that require WPF in MainForm.cs, then it works. But when UseWpf is true, then I get these errors in the diagnostics MSBuild output:

``` text
2>            Encountered conflict between 'Reference:C:\Users\Bill\.nuget\packages\microsoft.windowsdesktop.app.ref\6.0.0\ref/net6.0/System.Windows.Forms.dll' and 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.2\ref/net6.0/System.Windows.Forms.dll'. Choosing 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.2\ref/net6.0/System.Windows.Forms.dll' because AssemblyVersion '6.0.2.0' is greater than '6.0.0.0'.
2>            Encountered conflict between 'Reference:C:\Users\Bill\.nuget\packages\microsoft.windowsdesktop.app.ref\6.0.0\ref/net6.0/System.Windows.Forms.dll' and 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.2\ref/net6.0/System.Windows.Forms.dll'. Choosing 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.2\ref/net6.0/System.Windows.Forms.dll' because AssemblyVersion '6.0.2.0' is greater than '6.0.0.0'.
2>            Encountered conflict between 'Reference:C:\Users\Bill\.nuget\packages\microsoft.windowsdesktop.app.ref\6.0.0\ref/net6.0/System.Windows.Forms.dll' and 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.2\ref/net6.0/System.Windows.Forms.dll'. Choosing 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.2\ref/net6.0/System.Windows.Forms.dll' because AssemblyVersion '6.0.2.0' is greater than '6.0.0.0'.
2>            Encountered conflict between 'Platform:System.Windows.Forms.dll' and 'Platform:System.Windows.Forms.dll'. Could not determine winner due to equal file and assembly versions.
2>            Encountered conflict between 'Platform:System.Windows.Forms.dll' and 'Platform:System.Windows.Forms.dll'. Could not determine winner due to equal file and assembly versions.
```

I've spent hours trying to resolve these conflicts, but I've been unsuccessful. I can't reproduce the problem in a small new WinForms app targeting 6.0, setting UseWpf=true, and pulling in similar references. Hopefully, someone here can take a look and point out the problem. The MSBuild diagnostic output is 241,646 lines long, so I don't want to post that here. But getting the MegaBuild repo (from https://github.com/menees/MegaBuild.git), building in VS 2022 with the 6.0.2 SDK produces a MegaBuild.dll for .NET 6.0 that still references System.Windows.Forms.dll v6.0.2. :-(

**Comment by RussKie** [comment]
@menees have you tried https://github.com/dotnet/winforms/issues/6663#issuecomment-1034371295?

**Comment by menees** [comment]
Thanks, @RussKie! That worked! In addition to global.json, I added the following step to my GitHub [build.yml](https://github.com/menees/MegaBuild/blob/master/.github/workflows/build.yml) workflow to make sure it will keep building successfully even when GitHub updates their [windows-2022](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk) image to a newer SDK:

``` YAML
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '6.0.101' # SDK Version to use; x will use the latest version of the 6.0 channel. Force 101 for global.json compatibility.
```

**Comment by ebussa** [comment]
~~I believe this error is related to the issue so I'll share it here. I have a WPF app that should compile to a single file but fails with the error "error netsdk1112: the runtime pack for microsoft.windowsdesktop.app.runtime.win-x86 was not downloaded." I have restoration of missing packages enabled during the build.~~ 

@RussKie I now think the error above is caused by these errors:  

XamlC error XFC0000 : Cannot resolve type "Application"
XamlC error XFC0000 : Cannot resolve type "Window".

I thought these errors were secondary but now I'm thinking they are primary.  Here are the repro steps, but I'm not sure this issue belongs here?  I've tried the FrameworkReference and globals.json workarounds but it doesn't seem to address this issue.

### Repro Steps

1. Create a new WPF App.
2. Add a package reference to 'Xamarin.Forms'
3. XAML compiler can not resolve "Application" and "Window" types.  

You may ask, why would I want to do this?  I don't.  In my solution that used to work prior to the Visual Studio update, I have a project that references a third party package (`<PackageReference Include="Microcharts.Forms" Version="1.0.0-preview1" />`).  This package references Xamarin.Forms.   Referencing the third party package also causes the XAML compiler to not resolve the "Application" and "Window" types.

Any help in solving this or where to create an issue is appreciated!

**Comment by RussKie** [comment]
If this is WPF related, please raise an issue in dotnet/wpf repo.

You can also build with /bl flag to generate a binlog, and use MSBuild Structured Log Viewer tool to investigate what assemblies are referenced,  and see where it's failing.
________________________________

**Comment by tomaszmalik** [comment]
> > FYI, the workaround needs to be added to **every** referenced project that uses WPF/WinForms, not just the one being built.
> 
> Use Directory.Build.props for that.

You should use **Directory.Build.targets**, otherwise it would not override default reference.

Directory.Build.targets content:
```  
<Project>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-windows'">
    <FrameworkReference
        Update="Microsoft.WindowsDesktop.App;Microsoft.WindowsDesktop.App.WPF;Microsoft.WindowsDesktop.App.WindowsForms"
        TargetingPackVersion="6.0.0" />
  </ItemGroup>
</Project>
```

**Comment by juanp3053** [comment]
@RussKie Hello,
It doesn't seem to be WPF related to me, I have a .NET 5 MVC App (.NET Identity project) that I upgraded to .NET 6 and when I try to build I get the following errors only when using the dotnet 6.0.2+ SDK, it all goes away if I force the project to compile on 
< 6.0.102 SDK. I can rollback to .NET 5 without doing any changes to my project and all the building issues go away instantly.

Errors: 
```
CSC : error CS2015: '/src/IdentityApp/wwwroot/favicon.ico' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/icon.jpg' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/icon.png' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.eot' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.eot' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.ttf' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.woff' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
CSC : error CS2015: '/src/IdentityApp/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2' is a binary file instead of a text file [/src/IdentityApp/IdentityApp.csproj]
    321 Warning(s)
    11 Error(s)
```
