### ISSUE TITLE
The term 'msbuild' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,  verify that the path is correct and try again.

### ISSUE THREAD

**Issue by thesatyammishra** [dotnet/core#7179]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by greenEkatherine** [comment]
After what command did you get this error? That tutorial doesn't have explicit calls of `msbuild`.

**Comment by emadushe** [comment]
@greenEkatherine Hi, I have encountered the same issue with my robot framework which was working fine previously. Now I am getting this error message while building the project. Not sure how to cater this as there are no solution anywhere. Please provide the solution of it. 

![image](https://user-images.githubusercontent.com/106224971/191046707-9a51eb7a-8313-48a2-bdfb-d19e4575f35a.png)

**Comment by greenEkatherine** [comment]
@emadushe sorry, I missed your comment. 

Please check your `PATH` env variables, it looks like it lost the path to `msbuild.exe`. If it doesn't help, please open a new issue. We don't monitor closed issues, so it is better to open a new one and link an existing if you think it's the similar issue

**Comment by pallavijsaraf** [comment]
msbuild : The term 'msbuild' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  msbuild /t:restore
+  ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (msbuild:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException . getting this error on " msbuild /t:restore" this command . while running PCF component. give me proper solution
