### ISSUE TITLE
`dotnet watch` vs. `dotnet watch run`

### ISSUE THREAD

**Issue by tomhoad** [dotnet/core#7180]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

`dotnet watch` didn't work. `dotnet watch run` did.

**Comment by mairaw** [comment]
You need .NET 6 SDK for that command to work. I’ll clarify that in the tutorial.

**Comment by mairaw** [comment]
Tutorial has been updated.
