### ISSUE TITLE
no Hello World output

### ISSUE THREAD

**Issue by Dkirkwo1** [dotnet/core#7181]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Dkirkwo1** [comment]
Ran dotnet run, got no "Hello, World" response.

**Comment by mairaw** [comment]
So what did you get instead? Can you please share more details? Maybe a screenshot?
