### ISSUE TITLE
i am working with unity and every time i execute the code a message comes in the terminal that Couldn't find a project to run. Ensure a project exists in C:\Users\User, or pass the path to the project using --project

### ISSUE THREAD

**Issue by RiadAmin** [dotnet/core#7183]
help?

**Comment by greenEkatherine** [comment]
You don't have project file in unity project, right? But you should have build assemblies. In that case try to open folder with you assemblies and run it with `dotnet myapp.dll` (example from here https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore2x).

Please let us know if it helps.
