### ISSUE TITLE
Self-contained library to .so or .dylib 

### ISSUE THREAD

**Issue by iw4p** [dotnet/core#7184]
Hello,
Is it possible to do self-contained with a library? I want to load .dll files and use them on other platforms or other languages.
And as it  I can't use Publish single file option for libraries.
Is there any way I can load .dll self-contained or have it on another OS with another format like .so or .dylib?

**Comment by tarekgh** [comment]
Can you just package these DLLs in a nuget package and reference it in your library?

**Comment by iw4p** [comment]
I think it'd be still .dll via Nuget package manager.
I'm looking for something to self-contained .dll s (library) to use and load on another OS, Like what Xamarin does with .dll files, it allows to load and use .dll files on other OSs natively, but via C#.

**Comment by tarekgh** [comment]
@jkotas any thoughts around this question?

**Comment by vitek-karas** [comment]
@MichalStrehovsky might also know

**Comment by MichalStrehovsky** [comment]
If you want to build .so/.dylib/.dll files with C# that can be consumed from other non-.NET languages, you might want to look into https://github.com/AaronRobinsonMSFT/DNNE.

If you _also_ want these to be fully self-contained and single file, you should look at NativeAOT: https://github.com/dotnet/samples/tree/main/core/nativeaot and the NativeLibrary sample.
