### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR on Running tutorial

### ISSUE THREAD

**Issue by MarcoHandl** [dotnet/core#7186]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows 10

First with  the "dotnet watch" comand I just get the explanation of the comand, nothing is starting.
When I try "dotnet watch run" something happens, but with an ERR_SSL_PROTOCOL_ERROR (Connection to this side is not safe, localhost sends a invalid answer) in my Browserwindow.

This happens in G-Chrome and in MS-Edge.
Here the enviroment:
C:\Users\Iso1\BlazorApp>dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.400
 Commit:    d61950f9bf

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Iakuro-wc** [comment]
I'm getting the same error, not really sure what's going on.

**Comment by Iakuro-wc** [comment]
I deleted the BlazorApp folder and recreated it, without the "--no-https" in the command line, and it worked.
Try it out and see if it works for you too.

**Comment by danroth27** [comment]
It sounds like the browser was not able to make a successful SSL connection to the app. In the tutorial we recommend creating the Blazor app without HTTPS enabled to avoid certificate trust issues. If you prefer to run with HTTPS enabled, you'll need to first setup the ASP.NET Core development certificate by running `dotnet dev-certs https --trust`.
