### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by qwxoz** [dotnet/core#7193]
Template "Console App" could not be created.
Failed to create template.
Details: Access to the path 'C:\Program Files\dotnet\MyApp' is denied.
email me at jared.christy@yahoo.com on how to fix

**Comment by tarekgh** [comment]
There is not enough information here to try to help you. From the error, looks you have created your app inside the dotnet folder which you may not have permission to access there. Try to create your app in some other accessible place in your file system.

**Comment by mairaw** [comment]
Try creating your project on a different folder @qwxoz.
