### ISSUE TITLE
dotnet is not recognized as an internal or external command or batch file in Windows 10

### ISSUE THREAD

**Issue by Ghad1ee2r3** [dotnet/core#7196]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you install the SDK? If so, did you close the prompt window and start a new one after installation?

**Comment by Ghad1ee2r3** [comment]
yes I installed and setup SDK  
![image](https://user-images.githubusercontent.com/52378925/154724795-99a55e13-077d-463c-aae3-ef7c655f51fa.png)

**Comment by Ghad1ee2r3** [comment]
I closed prompt windows and start a new one. when I try to create a project, display to me message that informs me, it seems like I did not install but actually, I did.
![image](https://user-images.githubusercontent.com/52378925/154755260-ccfbb8d9-09e8-45d9-99ca-586ee3781456.png)

**Comment by Ghad1ee2r3** [comment]
this issue happen because when I was check where dotnet  in cdm display to me x86 path returns first,while my system is x64 . so I  fix the issue  by follow this steps :
[](https://user-images.githubusercontent.com/12971179/108114587-d697d700-704d-11eb-924f-f00fcbcf5c18.png)image
Click on the Environment Variables button
![image](https://user-images.githubusercontent.com/52378925/154853648-3f4204ce-f5cf-43ff-83a8-75a841fb6a47.png)
Under the System variables, select Path and click the Edit button
![image](https://user-images.githubusercontent.com/52378925/154853755-bc9da0b3-01a2-4ebf-b50e-c762be80abd0.png)

Find the entry C:\Program Files\dotnet\dotnet.exe and using the Move up button, leave that entry before the x86 one. like what I did in picture  :
![image](https://user-images.githubusercontent.com/52378925/154853779-b05b2431-5d3b-43da-9e86-4ed738eccabf.png)
Click the OK button until all the windows are closed. Open a new command prompt and now it works :)
