### ISSUE TITLE
Problem installing dotnet-sdk-6.0.200-win-arm64.exe 

### ISSUE THREAD

**Issue by Lagunajack** [dotnet/core#7208]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

When installing Microsoft.NET SDK 6.0.600  the setup failed. Message: The installation package is not supported by the processor type.
The processor is AMD Ryzen 5 3400G with Radeon Vega Graphics       3.70 GHz with 16GBYTES.

**Comment by mairaw** [comment]
You probably want to install the 64-bit version. To confirm:
- Click on the search icon on the Windows taskbar
- Type something like Device specifications
- Open the system settings window

You should get a window that will have many system settings. Confirm the system type. Mine for example says the following:
System type	64-bit operating system, x64-based processor

**Comment by snickler** [comment]
> Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install Operating System: windows
> 
> When installing Microsoft.NET SDK 6.0.600 the setup failed. Message: The installation package is not supported by the processor type. The processor is AMD Ryzen 5 3400G with Radeon Vega Graphics 3.70 GHz with 16GBYTES.

Use the Download .NET SDK (64-bit) link. You accidentally clicked on the Arm64 download. 

![image](https://user-images.githubusercontent.com/4016293/154724674-2e0e079d-d33e-4668-a5ad-387fa1bdd07e.png)
