### ISSUE TITLE
.NET Core 2.0 Preview 2 Installation "Waits" at end of install in Ubuntu 16.04.2

### ISSUE THREAD

**Issue by MaximoTrinidad** [dotnet/core#721]
Thanks for your interest in .NET Core. 

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

Just an FYI as I'm rolling out .NET 2.0 Core Preview 2 on my other Linux demo systems.  I notice at the end of the installation it really doesn't end unless you press Enter.

At least it does install and works.  But, there's something else happening at the end.

Linux OS: Ubuntu 16.04.2

(See Image)
![dotnet2_wait](https://user-images.githubusercontent.com/19892435/27716376-e9e98280-5d0b-11e7-9149-7ed7fc8e1373.png)

![dotnet2_enter](https://user-images.githubusercontent.com/19892435/27716459-8b7f3cac-5d0c-11e7-9118-9b2e87c9289f.png)

**Comment by Petermarcu** [comment]
@livarcocc , this looks like it's due to adding the "first run" experience to the installer.

**Comment by Petermarcu** [comment]
@MaximoTrinidad , Thanks for reporting this. I opened it in the dotnet/cli repo and tagged you there so it can be followed up on. I'm going to close it here.

**Comment by MaximoTrinidad** [comment]
@Petermarcu, Thanks for the update!
:)
