### ISSUE TITLE
dotnet run empty

### ISSUE THREAD

**Issue by hsuingram** [dotnet/core#7220]
I follow this official document (https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run) and run the main file which called Program.cs, but there is nothing happened. It should show " Hello, World! ".
![Screenshot from 2022-02-21 20-18-32](https://user-images.githubusercontent.com/92967217/154954114-16cd313b-986f-48a6-9fbf-2e3a35e449fd.png)
Operating System: Ubuntu 20.04
How could I fix it?

**Comment by tarekgh** [comment]
do you have the following line in the `Program.cs` file? 

```C#
Console.WriteLine("Hello, World!");
```

**Comment by mairaw** [comment]
Also, how did you install the SDK?
