### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by StanlsSlav** [dotnet/core#7224]
Hello, dotnet team!

The link on *.NET 7* from [core/release-notes/7.0/README.md](../tree/main/release-notes/7.0/README.md) is missing a hypen between preview and 1

https://devblogs.microsoft.com/dotnet/announcing-net-7-preview1/

**Comment by tarekgh** [comment]
@kalaskarsanket could you please have a look at this one?

**Comment by kalaskarsanket** [comment]
I have created the PR (https://github.com/dotnet/core/pull/7227) and will merge the same. Thanks for notifying :-)
