### ISSUE TITLE
when I enter the command in terminal it return comand not found even though I have resently download the file

### ISSUE THREAD

**Issue by bozyurt21** [dotnet/core#7225]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
It might be an issue with PATH.

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue

Let us know if this helps.
