### ISSUE TITLE
Hello World Issues

### ISSUE THREAD

**Issue by EnricoZamperlin** [dotnet/core#7228]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

>dotnet new console -o MyApp
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

I've got installed the sdk 6.0.200 two times and it still doesn't find it.
Operating system: Windows 11 Home 21H2

**Comment by mairaw** [comment]
It might be an issue with PATH. 

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue

Let us know if this helps.
