### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by bjimmar** [dotnet/core#7229]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: macos

I copied and paste the code from text editor and when I run my  app it says that I have a few syntax errors. I have coped and paste the error I received is below.

**Comment by bjimmar** [comment]
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,13): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,14): error CS1001: Identifier expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,6): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1001: Identifier expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1514: { expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1513: } expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,14): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(9,12): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(10,7): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
watch : Waiting for a file to change before restarting dotnet...
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,13): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,14): error CS1001: Identifier expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,6): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1001: Identifier expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1514: { expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1513: } expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,14): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(9,12): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(10,7): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
watch : Waiting for a file to change before restarting dotnet...
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,13): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,14): error CS1001: Identifier expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(4,23): error CS1525: Invalid expression term '=' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,6): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1001: Identifier expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1514: { expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1513: } expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS8803: Top-level statements must precede namespace and type declarations. [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,11): error CS1525: Invalid expression term '=' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(7,26): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,14): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,14): error CS1022: Type or namespace definition, or end-of-file expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,23): error CS1525: Invalid expression term '/' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(8,27): error CS1525: Invalid expression term '<' [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(9,12): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(9,20): error CS1003: Syntax error, ',' expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
/Users/brandijimmar/MyWebApp/Pages/Index.cshtml.cs(10,7): error CS1002: ; expected [/Users/brandijimmar/MyWebApp/MyWebApp.csproj]
watch : Waiting for a file to change before restarting dotnet...

**Comment by mairaw** [comment]
You might have edited the .cs file instead of the .cshtml one. Windows might hide the file extension.
Maybe start over again and make sure you're editing the cshtml file and not the .cs one?

**Comment by bjimmar** [comment]
Going to give that a try, I work on a Mac and I know a lot of times things can look a little different. Thank you for your help

**Comment by mairaw** [comment]
Oh right, you're on a Mac. But still, make sure you're editing the right file. 
There will be two:
- Index.cshtml
- Index.cshtml.cs
