### ISSUE TITLE
.Net Core 2.0 preview-2 issues deployed to IIS

### ISSUE THREAD

**Issue by yupingyong** [dotnet/core#723]
.Net Core 2.0 preview-2 installed in windows server 2016 Windows Server Hosting IIS does not appear AspNetCoreModule module

**Comment by Petermarcu** [comment]
I think there is something called the asp.net core hosting bundle that you need to install.

**Comment by Petermarcu** [comment]
@DamianEdwards do you know where the link to that is?

**Comment by yupingyong** [comment]
@Petermarcu  
thank you for your reply.
I installed the following files:
1.AspNetCore.2.0.0-Preview2.RuntimePackageStore_x64.exe
2.DotNetCore.2.0.0-Preview2-WindowsHosting.exe
3.dotnet-runtime-2.0.0-preview2-25407-01-win-x64.exe
Whether there are other packages that need to be installed.

**Comment by Petermarcu** [comment]
#2 in your list looks like the one I'm thinking of. @DamianEdwards would know if that's the right one or if there is another issue here.

**Comment by danroth27** [comment]
@yupingyong Could you please provide more details on the steps you performed and the error you are seeing?

**Comment by Petermarcu** [comment]
@yupingyong, any more details you can provide to @danroth27 so we can dig deeper?

**Comment by yupingyong** [comment]
@danroth27  @Petermarcu 
Thank you for your reply.
I provide my server installation environment information, whether it helps to find the problem.
1. System version: Windows Server 2016 Datacenter Chinese version
2.IIS Version: 10.0.14393.0
Steps:
1. Remove the original 1.1.2 version of Windows Server Hosting and 1.1.2 version of the Runtime
2. Start installing the following three files
    A) .AspNetCore.2.0.0-Preview2.RuntimePackageStore_x64.exe
    B) .DotNetCore.2.0.0-Preview2-WindowsHosting.exe
    C) .dotnet-runtime-2.0.0-preview2-25407-01-win-x64.exe
3. After installing the IIS module can not see AspNetCoreModule, restart the server is useless

**Comment by nzcoward** [comment]
You can add it manually into the pipeline: Go into the modules feature in IIS for the server, and Configured Native Modules. You will see AspNetCoreModule in the list. You can add it there.

However, even adding it, I still see the dreaded 502.5 error on both standalone and framework dependent apps. Now, the version it is referencing, after removing all .netcore 1.x installations from my machine is 7.1.1982 - is this the correct .netcore 2 version?

I have followed all the steps for getting a 1.x site deployed. I have added the Kestrel and IISConfiguration elements to my Program.cs (ootb template doesn't for some reason). I have tested that Kestrel runs it just fine (dotnet myapp.dll) but the reverse proxy between IIS and Kestrel is still not working. It is not an app issue, but an AspNetCore Module problem.

Do we have anyone from the .net core team even looking into this? IIS just makes administration so much easier.

**Comment by danroth27** [comment]
@yupingyong We generated the required web.config file to add the ASP.NET Core Module to your app when you run `dotnet publish`. Can you confirm that you have run `dotnet publish` on your app and that the web.config file is present in the publish output?

**Comment by eyccli** [comment]
@danroth27 We are also encountering a similar issue using Core 2.0 (not preview).  Web.config is never generated using the "dotnet publish -o etc -c "path"".  Are you saying it should?  If so, it is not.  Right now I have to manually copy the Web.config file using the IDE's Publish method.

**Comment by Petermarcu** [comment]
Is this still an issue?

**Comment by Petermarcu** [comment]
I'm going to close this issue now. Let us know if its still a problem.
