### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by BenBouck** [dotnet/core#7231]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The tutorial tells to use `dotnet watch` to start the application, instead of `dotnet watch run`

**Comment by mairaw** [comment]
I need to change the tutorial to be more clear that it needs .NET 6 SDK in order for it to work as written. So, you can use `dotnet watch run` if you're using .NET 5 or download .NET 6 SDK for the tutorial to work as-is.
