### ISSUE TITLE
ข้อผิดพลาดในการคอมไพล์!

### ISSUE THREAD

**Issue by gifhuppp** [dotnet/core#7234]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Please let us know what kind of compilation error you're getting so we can try to help.
