### ISSUE TITLE
Meine erste APP. Wie mache ich die?

### ISSUE THREAD

**Issue by RolfSchroeder** [dotnet/core#7235]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by RolfSchroeder** [comment]
syntax für App
Hallo World funktioniert nicht. Ich habe keine App.

**Comment by RolfSchroeder** [comment]
![image](https://user-images.githubusercontent.com/15377498/155860364-34b2b132-827c-4f24-80e8-3c9c20a978d6.png)
![image](https://user-images.githubusercontent.com/15377498/155860374-30bbb94c-d109-4449-b3e3-cea8c82d3168.png)

**Comment by mairaw** [comment]
Can you run the `dir` command so we can see what's on your directory?

Google translate: Können Sie den Befehl 'dir' ausführen, damit wir sehen können, was sich in Ihrem Verzeichnis befindet?

**Comment by bartonjs** [comment]
Wie haben Sie diese Verzeichnis gemacht?  (`dotnet new -o MyApp` oder etwas anderes?)

Wenn Sie `dotnet new` ausgeführt haben, sollten zwei Dateien sein: MyApp.csproj und Program.cs.  Haben Sie diese Dateien in diesem Verzeichnis? (Dass ist auch Mairas Fragen).

(Entschuldigen Sie, bitte, ob meine Deutsch schlecht ist.  Ich habe nur seit eine paar Monaten Deutsch gelernt.)

**Comment by RolfSchroeder** [comment]
Yes i can do <dir>. What shell I do?

**Comment by terrajobst** [comment]
Nach der Installation koennen sie jede Kommandozeile benutzen (regulaeres cmd.exe oder PowerShell).

Damit das Programm funktioniert, muessen sie es zuerste erzeugen:

1. Erstellen Sie ein Verzeichnis (`mkdir HalloWelt`)
2. Wechseln Sie in das Verzeichnis (`cd HalloWelt`)
3. Erstellen Sie die Applikation mittels `dotnet new console`
4. Jetzt koennen Sie es mittels `dotnet run` ausfuehren

Hat das geklappt?

**Comment by RolfSchroeder** [comment]
Deregulierte Märkte sind Ursache für Preistreiberei.
http://gemeindevertreter.nordc.de/page/2/

**Comment by mairaw** [comment]
@terrajobst the comments here seem unrelated to the problem. Can you double check?

**Comment by terrajobst** [comment]
Seems nonsensical. I suggest we close this issue.

@RolfSchroeder Ihre Kommentare sehen sehr nach Spam aus. Falls Sie weiterhin in dieser Art und Weise kommentieren, werden Sie blockiert.
