### ISSUE TITLE
Can't run "dotnet" command on Terminal

### ISSUE THREAD

**Issue by billzayy** [dotnet/core#7236]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What error message do you get?

**Comment by billzayy** [comment]
After i installed dotnet 6.0 and try to run "dotnet". My terminal give me a message like this : 
`zsh: command not found: dotnet`

**Comment by carlossanlop** [comment]
@billzayy this error shows up if you try to run dotnet on a terminal window that was open while you were installing the SDK in another terminal window, or via the UI. You need to close the terminal window and open a new one to ensure the environment variables are refreshed with the location of the dotnet executable.

@mairaw maybe the tutorial should describe the error message users would see in macos and unix. The error message isn't the same as in Windows when an executable is not found.

**Comment by mairaw** [comment]
That's a good idea @carlossanlop. So the `'dotnet' is not recognized as an internal or external command` is only for Windows machines?

**Comment by billzayy** [comment]
@carlossanlop thanks for your support ! but can i ask what is the different between .NET SDK x64 & .NET SDK Arm64 ? Because after i tried to install a x64 version and still didn't run on MacOS. But i installed Arm64 version and it run now.

**Comment by billzayy** [comment]
Oh, i get this! Thanks for your support @mairaw & @carlossanlop. My problem is solved !

**Comment by carlossanlop** [comment]
> That's a good idea @carlossanlop. So the `'dotnet' is not recognized as an internal or external command` is only for Windows machines?

That is correct, @mairaw . I opened a new issue to track this request. https://github.com/dotnet/core/issues/7245

We can close this now since it has been solved.
