### ISSUE TITLE
not able solve it

### ISSUE THREAD

**Issue by mohitsinghal271** [dotnet/core#7237]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
![Screenshot (111)](https://user-images.githubusercontent.com/93547624/156046157-b0c3ab46-fba9-46dd-9a01-9bafa19d923f.png)

**Comment by mairaw** [comment]
It might be an issue with PATH.

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue

Let us know if this helps.
