### ISSUE TITLE
.NET 6.0-windows: functions who initialize class scope fields throw warnings of not being initialized when exiting constructor when nullable=enable

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/core#7243]
### Description
functions who initialize class scope fields throw warnings of not being initialized when exiting constructor when nullable=enable inside the csproj

program.cs
```cs
namespace Example {
	
	class Program2
	{
		
		public Program2()
		{
			
		}
		
	}
	
	class Program {
		
		public Program2 example;
		
		public Program()
		{
			Initialize();
		}
		
		public void Initialize()
		{
			example = new();
		}
		
		public static void Main(string[] args)
		{
			
		}
		
	}
	
}
```

### Configuration
project.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```
Issue does not persist when Nullable turned off

### Regression?
No idea if regression. New dotnet user.

### Other information
dotnet watch run
```
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\code\example\src\Program.cs(22,10): warning CS8618: Non-nullable field 'example' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [C:\code\example\project.csproj]
  example -> C:\code\example\bin\Debug\net6.0-windows\example.dll
watch : Started
```

Issue probably does not persist when using visual studio (I use visual studio code). The form designer in msvs uses this semantic to initialize form objects in a InitializeComponents() function.

**Comment by mairaw** [comment]
@jaredpar can you help with this issue?

**Comment by jaredpar** [comment]
@jcouv @RikkiGibson

**Comment by RikkiGibson** [comment]
Perhaps here? https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-references.md#known-pitfalls
Or here? https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/nullable-reference-types.md#build-the-survey-with-nullable-and-non-nullable-reference-types

@mairaw if there's a specific place that seems right to call out how to resolve the scenario in this issue, please let us know.

**Comment by mairaw** [comment]
Not sure @RikkiGibson. Adding @BillWagner for guidance

**Comment by tilkinsc** [comment]
Dont get me wrong. I like Nullable and I understand it. I just thing it's dumb for the language not to detect the resolution of class fields by following calls made inside the constructor.

**Comment by jaredpar** [comment]
@tilkinsc understand that view point. However the C# compiler though does not do any type of cross method analysis: true for this feature and any other. The cost of adding such analysis is very high and not something that was under consideration for this feature.

**Comment by tilkinsc** [comment]
I guess the solution for me would just be careful and use the nullable override.

**Comment by RikkiGibson** [comment]
A solution which I meant to link here was to put MemberNotNullAttribute on your helper method. I would try that or adding assertions to your constructor before trying turning off nullable.

**Comment by RikkiGibson** [comment]
Reopening to track updating the documentation appropriately.

**Comment by BillWagner** [comment]
Rather than reopen this, I created dotnet/docs#28531 to address the docs issue.
