### ISSUE TITLE
The terminal process failed to launch: Path to shell executable "C:\Users\HP\MyApp\dotnet" does not exist.

### ISSUE THREAD

**Issue by Ammar4372** [dotnet/core#7246]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Are you running this on VS Code?
