### ISSUE TITLE
not supporting these file 

### ISSUE THREAD

**Issue by sumanthamaravathi** [dotnet/core#7248]
Problem encountered
<img width="960" alt="Screenshot 2022-03-03 17 42 39" src="https://user-images.githubusercontent.com/100846537/156562859-596a5359-26ca-416d-99ef-7a08ffde6b5d.png">
 on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
The screenshot shows that you typed the command `donet` instead of `dotnet`. Please try again with the proper command name and let us know if it's still not working. Also, make sure you opened a new command prompt window after installation.
