### ISSUE TITLE
Docs for AssetTargetFallback

### ISSUE THREAD

**Issue by richlander** [dotnet/core#725]
We need docs for AssetTargetFallback, both generally and migrating from PackageTargetFallback .

See: https://github.com/dotnet/core/issues/711#issuecomment-312051242

**Comment by Petermarcu** [comment]
@richlander @rrelyea should this be moved to either the nuget or docs repo to track it?

**Comment by Petermarcu** [comment]
Closing as I opened it again in nuget/home so it actually gets tracked.
