### ISSUE TITLE
Could not load file or assembly NuGet.DependencyResolver.Core

### ISSUE THREAD

**Issue by xgnxs** [dotnet/core#7252]
### Description

`dotnet new console -o MyApp` fails at "Determining projects to restore..." step with:
```
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error : Could not load file or assembly 'NuGet.DependencyResolver.Core, Version=6.1.0.103, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. An attempt was made to load a program with an incorrect format. [C:\src\Test\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error :   Could not load file or assembly 'C:\Program Files\dotnet\sdk\6.0.200\NuGet.DependencyResolver.Core.dll'. An attempt was made to load a program with an incorrect format. [C:\src\Test\MyApp\MyApp.csproj]
```

Running `dotnet restore` fails with the same error.

### Configuration

.NET version: 6.0.200
OS: Windows 11 Pro - build 22000.527
Architecture: x64 (x86?) Ryzen 9 5950x
Powershell version 7.2.1

### Other information

.NET was originally installed on this machine yesterday via Visual Studio Community 2022 17.1.0.  I am able to create and build projects through Visual Studio.  However, I am not able to create new projects (or do anything, really) with the `dotnet` command, (such as `dotnet build` or `dotnet watch` or `dotnet test`, etc).  I then tried downloading and installed the .NET 6 SDK, but the issue persists.

Issue also persists across restarts.

#### Edit:

Issue seems to be resolved after uninstalling Visual Studio, uninstalling .NET 6 SDK, restarting, reinstalling .NET 6 SDK, and reinstalling Visual Studio (with ASP.NET and web development checked), in that order. I'm not sure if this is just a temporary fix.

**Comment by mairaw** [comment]
@xgnxs are things still working for you? I'm glad you got it working and I hope the fix was not just temporary.
