### ISSUE TITLE
dotnet not able to run even after following correct procedures from official MS document

### ISSUE THREAD

**Issue by gamer-undefeated** [dotnet/core#7254]
![Screenshot from 2022-03-05 18-06-13](https://user-images.githubusercontent.com/87656219/156883276-5227f231-c244-4484-b3e4-12ee41f2e3d8.png)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
How did you install dotnet? Did you use snap or some other method?
