### ISSUE TITLE
Could not find a MSBuild project file in 'C:\Users\olade\Desktop\MyWebApp'. Specify which project to use with the --project option.

### ISSUE THREAD

**Issue by oladele1440** [dotnet/core#7258]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What are the contents of your MyWebApp directory?
