### ISSUE TITLE
.NET March 2022 Update - .NET 6.0.3, .NET 5.0.15, and .NET Core 3.1.23

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7259]
Release Notes
[6.0.3](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.3/6.0.3.md)
[5.0.15](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.15/5.0.15.md)
[3.1.23](https://github.com/dotnet/core/blob/main/release-notes/3.0/3.1.23/3.1.23.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Distro | 6.0.3 | 5.0.15 | 3.1.23
-- | -- | -- | --
Ubuntu 18.04 |✅|✅|✅| 
Ubuntu 20.04 |✅|✅|✅|
Ubuntu 21.04 |✅|✅|✅|
Centos 7 |✅|✅|✅| 
Debian 10 |✅|✅|✅| 
Debian 11 |✅|✅|✅| 
Fedora 33|✅|✅|✅| 
Fedora 34 |✅|✅|✅| 
OpenSUSE 15|✅|✅|✅| 
Oracle|✅|✅|✅|

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

Known Issues

If there are any more issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by frankyuan** [comment]
Hi team, after upgrading to 6.0.3, I got an error `Cannot access a disposed object. Object name: 'ConfigurationManager'.` in `var app = builder.Build();`. May I know what change I should do? Thanks. I tried to downgrade to 6.0.2 and it worked fine.

**Comment by philip-reed** [comment]
Also having the same issue as @frankyuan 
Not sure where the most appropriate place to log the issue is.

**Comment by philip-reed** [comment]
@frankyuan I don't suppose you are using [Convey](https://convey-stack.github.io/documentation/CQRS/)?
My initial investigations are marking that as prime suspect in my app.

**Comment by philip-reed** [comment]
Repro solution here:

https://github.com/philip-reed/40614

![image](https://user-images.githubusercontent.com/7798175/157484995-cd57fd56-6eab-4fe8-bbe9-f59d6dd45a0f.png)

**Comment by bc3** [comment]
Also having the same issue since 8/3/2022 on our build servers:

   OneTimeSetUp: System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'ConfigurationManager'.

It is an integrationtest that is bootstrapping our api using the WebApplicationFactory class

**Comment by leecow** [comment]
@Pilchie @dougbu , can you take a look at the above reports?

**Comment by dougbu** [comment]
Highlighting @BrennanConroy's workaround:

> You can likely workaround the issue by passing `builder.Configuration` to `AddConvey()`
```csharp
builder.Services.AddConvey(configuration: builder.Configuration);
```

**Comment by BrennanConroy** [comment]
That workaround is very specific to the Convey usage, not everyone who is hitting this issue is using Convey.

**Comment by frankyuan** [comment]
> That workaround is very specific to the Convey usage, not everyone who is hitting this issue is using Convey.

Yes, we don't use Convey.

**Comment by Pilchie** [comment]
@rafikiassumani-msft can you take a look here?

**Comment by Pilchie** [comment]
@rafikiassumani-msft - possibly related to https://github.com/dotnet/runtime/pull/63816?

**Comment by BrennanConroy** [comment]
There is a change coming in 6.0.4 that fixes at least one case of this issue. If other folks like @frankyuan and @bc3 could provide minimal repro apps so we can make sure we cover everything that would be helpful.

Let's continue the discussion at https://github.com/dotnet/aspnetcore/issues/40614

**Comment by rafikiassumani-msft** [comment]
@Pilchie after looking at the exception that's being thrown when adding Convey, it appears that `ReferenceCountedProviderManager` class was introduced in https://github.com/dotnet/runtime/pull/63816 to fix the configurations locking issue. I suspect this might happen in other scenarios where configurations need to be synchronized. @bc3 can you provide a minimum repro with `WebApplicationFactory `?  - Assigning to @halter73 for further investigation.

**Comment by philip-reed** [comment]
> Highlighting @BrennanConroy's workaround:
> 
> > You can likely workaround the issue by passing `builder.Configuration` to `AddConvey()`
> 
> ```cs
> builder.Services.AddConvey(configuration: builder.Configuration);
> ```

Yes, this seems to work around the issue in my repro app.

**Comment by bc3** [comment]
@rafikiassumani-msft , i finally got around to reproduce the bug. I got a solution with integration test ready for you to test the issue

for us the issue was throw eventually by this code:

`services.AddApplicationInsightsKubernetesEnricher();`

it is an extension method from package: `Microsoft.ApplicationInsights.Kubernetes` from repo https://github.com/microsoft/ApplicationInsights-Kubernetes

[IssueDotnetCore603.zip](https://github.com/dotnet/core/files/8230280/IssueDotnetCore603.zip)

**Comment by BrennanConroy** [comment]
Looks like the Kubernetes issue was fixed back in August https://github.com/microsoft/ApplicationInsights-Kubernetes/pull/237. Update your app to version 2.0.2 to fix it.

And it's the same root cause as all the other repros on this thread. Building the service provider early and then disposing it.

**Comment by rafikiassumani-msft** [comment]
I will lock conversation on this announcement. Let's continue the discussion at https://github.com/dotnet/aspnetcore/issues/40614.

**Comment by dcwhittaker** [comment]
Closed in favor of https://github.com/dotnet/core/issues/7362
