### ISSUE TITLE
[releases.json] "17.2 latest preview" is not a valid version number

### ISSUE THREAD

**Issue by arthurrump** [dotnet/core#7264]
With this months releases the 6.0/releases.json file now include "17.2 latest preview" in the `vs-version` field, but this is obviously not a valid version number. Previously this field has always had valid version numbers. It seems that the customary way to do this is to have "17.2" in the `vs-version` field and specify preview status using the `vs-support` field.

**Comment by mairaw** [comment]
@rbhanda @dcwhittaker can you please check this issue?

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/7265 to fix this

**Comment by arthurrump** [comment]
Thanks for the quick fix! Just a note that https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json still has the old one, but I'm not sure if that just takes some time to update or that some buttons still have to be pressed.

**Comment by rbhanda** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json is also updated
FYI @dcwhittaker
