### ISSUE TITLE
erro na instalação dotnet

### ISSUE THREAD

**Issue by emannuelrossano** [dotnet/core#7269]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Você pode dar mais detalhes sobre esse erro de instalação? Qual a mensagem de erro que você está vendo?
