### ISSUE TITLE
".NET Core SDK with version '6.0.103' is already installed." But unable to find it

### ISSUE THREAD

**Issue by AndriasP** [dotnet/core#7270]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have tried for a few hours now to get going with F# on this mac, for a "Functional Programming" course I have this semester, but I keep running into issues. 
When i download the .Net SDK, my mac is unable to find it, so i can't write the "Hello World" program in VS Code and nothing happens when i write "dotnet" in the bash/terminal. I have tried downloading the same file multiple times and installing, but I can't seem to figure out where it ends up on my mac. Can't find any trace of it. 

But it seems to be installed somewhere, because when i write this line of code:

curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel Current

from this guide: https://fsharp.org/use/mac/

It says that ".NET Core SDK with version '6.0.103' is already installed." 

Can someone help me? Where does it end up, and how do I get do be a part of some path? 

Thank you,
Andrias Poulsen

**Comment by mairaw** [comment]
Which version did you try to install? Are you on a M1 Mac?

**Comment by AndriasP** [comment]
I tried to install the recommended version on the website. .NET 6.0

Yes i am on a M1 mac. Here is the info
<img width="555" alt="image" src="https://user-images.githubusercontent.com/80765602/157844447-ba8c2fd4-ba8e-45a8-b425-003681f88664.png">

**Comment by AndriasP** [comment]
I tried to install the arm64 version and that was found immediately by the system :)

**Comment by carlossanlop** [comment]
That's good to hear, @AndriasP. Seems the issue got solved for you.

But I still wonder why the script was unable to detect that the machine required an ARM64 version to get installed.

this is the second issue I see reporting a similar trouble (see https://github.com/dotnet/core/issues/7263). I'll transfer this to the https://github.com/dotnet/install-scripts repo so the issue gets investigated further. The script might not be detecting the Apple M1 machines properly.

**Comment by carlossanlop** [comment]
Couldn't transfer, but I opened an issue: https://github.com/dotnet/install-scripts/issues/263
