### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ilovefoofoo** [dotnet/core#7273]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
It says "zsh: command not found: dotnet", how do I fix?

**Comment by ilovefoofoo** [comment]
I have tried setting up manually and it will say permission denied

**Comment by mairaw** [comment]
What sort of Mac do you have? Are you on a M1 chip? And which version did you try to install?
