### ISSUE TITLE
error CS1022: Type or namespace definition, or end-of-file expected

### ISSUE THREAD

**Issue by robe861Milt** [dotnet/core#7274]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
In which file are you getting this error? Can you show its contents so we can try to help you?

This error usually shows up when the .cs file has some issue like missing closing brackets.
