### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### ISSUE THREAD

**Issue by Ryanokal** [dotnet/core#7276]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Hello I am using parrot os 4.11 and I have installed the dotnet 6.0 using the binaries and experienced an error while creating a new console application

dotnet new console -o MyApp -f net6.0
Getting ready...
Couldn't find an installed template that matches the input, searching online for one that does...
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.

Console Application (C#)
Author: Microsoft
Description: A project for creating a command-line application that can run on .NET Core on Windows, Linux and macOS
Error: Invalid parameter(s):
-f net6.0
    'net6.0' is not a valid value for -f (Framework).

Options:                                                                            
  --langVersion  Sets the LangVersion property in the created project file          
                 text - Optional                                                    

  --no-restore   If specified, skips the automatic restore of the project on create.
                 bool - Optional                                                    
                 Default: false / (*) true                                          

* Indicates the value used if the switch is provided without a value.

and when i check the installed verion it gives me 
3.1.408 as the verion which is the sytem installed version yet I just installed the 6.0 version

**Comment by mairaw** [comment]
How did you install the SDK? 

You could still try to run the tutorial if you remove the -f option, but not everything would match. The templates have changed drastically in .NET 6.

**Comment by Ryanokal** [comment]
I installed the SDK using the linux binaries. Parrot OS is not accepting the terminal commands given for debian or ubuntu by microsoft

I have tried without the -f option but still getting the same error

**Comment by Ryanokal** [comment]
I installed the SDK using the binaries because the terminal commands given for Debian are bringing the following error
sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
Hit:1 http://packages.microsoft.com/repos/code stable InRelease                
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                  
Hit:3 https://brave-browser-apt-release.s3.brave.com stable InRelease          
Hit:4 https://deb.parrot.sh/parrot rolling InRelease                           
Hit:5 https://deb.parrot.sh/parrot rolling-security InRelease  
Hit:6 https://packages.microsoft.com/ubuntu/20.10/prod groovy InRelease
Reading package lists... Done                           
Building dependency tree... Done
Reading state information... Done
156 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4+parrot1).
The following packages were automatically installed and are no longer required:
  libct4 libmotif-common libxm4 python3-aiofiles python3-fastapi
  python3-orjson python3-pydantic python3-slowapi python3-starlette
  python3-uvicorn sqsh
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 156 not upgraded.
Hit:1 http://packages.microsoft.com/repos/code stable InRelease                
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                  
Hit:3 https://packages.microsoft.com/ubuntu/20.10/prod groovy InRelease        
Hit:4 https://brave-browser-apt-release.s3.brave.com stable InRelease       
Hit:5 https://deb.parrot.sh/parrot rolling InRelease  
Hit:6 https://deb.parrot.sh/parrot rolling-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
156 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-hostfxr-6.0 : Depends: dotnet-host (>= 6.0.3) but 5.0.5-1 is to be installed
E: Unable to correct problems, you have held broken packages.


And so I opted to install using the binaries which had no errors but when I checked the version
it shows the older version
dotnet --version
3.1.408

**Comment by mairaw** [comment]
@leecow can you look at this? @Ryanokal is on Parrot, but not sure if it's supported or not given it's based on Debian.

**Comment by leecow** [comment]
Looks like you're using the Ubuntu 20.10 repository rather than Debian - 

> Hit:6 https://packages.microsoft.com/ubuntu/20.10/prod groovy InRelease

First thing I would try is setting that to whatever upstream Debian version is closest to your Parrot version. Links to setup instructions for 9, 10 and 11 are available [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website#debian).

**Comment by mairaw** [comment]
@Ryanokal did you see Lee's comment? Can you make sure you're installing using Debians intructions? Let us know how that goes.

**Comment by Ryanokal** [comment]
Thanks Guys

**Comment by mairaw** [comment]
I assume you got it working now. But please let us know otherwise.
