### ISSUE TITLE
 Could not find a MSBuild project file in 'C:\Users\HP'. Specify which project to use with the --project option.

### ISSUE THREAD

**Issue by robe861Milt** [dotnet/core#7281]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Can you please share the exact command line you are trying to execute?
Note that the command must be run in a directory with the .sln or .csproj file.

**Comment by istankovic12345** [comment]
I had the exact same problem and it turns out I was in the wrong folder.. make sure you are in the app folder

**Comment by WilliamNwoke** [comment]
I just had the same problem and realized i am in the wrong folder. Who could have seen that coming!
