### ISSUE TITLE
Docker Build Failed

### ISSUE THREAD

**Issue by shiva753** [dotnet/core#7289]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

[+] Building 0.0s (1/2)                                                         
 => ERROR [internal] load build definition from Dockerfile                 0.0s
 => => transferring dockerfile: 40B                                        0.0s
------
 > [internal] load build definition from Dockerfile:
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: error from sender: open .Trash: operation not permitted

**Comment by shiva753** [comment]
Fixed needed to execute the program from MyMicroService directory and there is a difference in Docker file, need to name the solution as in directory which created another issue but both of them are resolved.

**Comment by ArvinDevel** [comment]
I think this failure was caused by that you ran it under user directory where the .Trash locates.
Even though you run `sudo ls .Trash`, the output may still be `ls: .Trash: Operation not permitted`.
