### ISSUE TITLE
Inconsistent 6.0.3 Update distributed trough KB 5012417

### ISSUE THREAD

**Issue by hankskorpio** [dotnet/core#7290]
### Description
Automatic update of .NET 6.0.2 to 6.0.3 produces inconsistent environment

### Environment:
Edition	Windows 10 Pro
Version	21H1
Installed on	‎2/‎11/‎2022
OS build	19043.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

.NET 6.0.2 Hosting bundle installed

![image](https://user-images.githubusercontent.com/45772324/158785062-ba4c500a-7b53-468e-b5c7-bd73ae3253f7.png)

### Steps : 

1) In Windows Update , Advanced options , enable "Receive updates for other Microsoft products when you update windows"
2) Check for updates

Update KB 5012417 is downloaded and installed
![image](https://user-images.githubusercontent.com/45772324/158785390-aee7510b-c301-4f19-b539-9c0fd703db4d.png)

### Result:

Microsoft.ApsNetCore.App updated to 6.0.3
Microsoft.NetCore.App still stuck at 6.0.2

![image](https://user-images.githubusercontent.com/45772324/158785704-b6cc2857-17b7-4826-b781-6d08dc79b12c.png)

### Issue:
<b>Applications that targets 6.0.x will fail to execute because they will not be able to find the correct NET Runtime.</b>

### Workaround:
Install NET 6.0.3 Hosting bundle.

### Comment:
The automatic update causes application crashes and a manual intervention is needed. This behavior is unacceptable when related to applications that are deployed on premise

**Comment by rzikm** [comment]
@NikolaMilosavljevic can you please take a look?

**Comment by joeloff** [comment]
@hankskorpio can you run `Get-WindowsUpdateLog` from powershell and attach the log. It will create a file called WindowsUpdate.log on your desktop.

@csnellgrove1-zz as an FYI. I manually installed 6.0.2 and then 6.0.3 and it seems to correctly upgrade. From the user's description it seems like it MU might be detecting and offering the wrong bundle.. Once we have the logs we should be able to confirm. I was testing in a sandbox so could not get the update to run

**Comment by joeloff** [comment]
Sorry, meant to comment, not close.

**Comment by joeloff** [comment]
@hankskorpio can you confirm whether you have IIS enabled and whether ANCM was installed from the hosting bundle. You can look for `SOFTWARE\Classes\Installer\Dependencies\IIS_AspNetCore_Module_V2,x64`

Also, can you run the VS log collection tool. It will gather additional data from the installations on the machine. The link to the tool is here: https://www.microsoft.com/en-ca/download/details.aspx?id=12493

**Comment by hankskorpio** [comment]
@joeloff : IIS is not installed on that machine and the registry entry is not present.
BUT the same behavior happens on machines with IIS Installed. I can restore a machine with IIS to show you exactly the same steps and results, but... would it be supposed to work even without IIS using Kestrel?  

In attachment the "collectInfo.txt" retrieved by VSLogCollectiontool

[CollectInfo.zip](https://github.com/dotnet/core/files/8302715/CollectInfo.zip)

**Comment by vaguepromise** [comment]
Hi. I'd opened a duplicate of this ticket last week which has now been closed but figure I can contribute. 

I have been able to reproduce this problem on both a Windows Server 2012 R2 machine with IIS installed, and a Windows Server 2019 machine without IIS installed... combing the Windows Update logs doesn't seem to show any errors so appears the package is installing correctly.. so doesn't appear to be configuration or even platform specific.

**Comment by hankskorpio** [comment]
Hi, I don't want to be pushy but ... any news about this issue? I'm a little worried about the deployment of our applications .

**Comment by donaldsonk** [comment]
We are having this issue as well at our organization.  In our case one of our apps broke because the hosting bundle was not installed form the update package and that is a dependency for the app.  We opened a case with MS to see if they can help identify what is happening.

**Comment by donaldsonk** [comment]
We are having this issue as well at our organization.  We noticed it specifically with the 6.0.3 update.  In our case one of our apps broke because the hosting bundle was not installed form the update package and that is a dependency for that app.  We opened a case with MS to see if they can help identify what is happening.

**Comment by hankskorpio** [comment]
Hi, any news? Is it ok for microsoft that a production environment can crash suddenly due to an update?

**Comment by vaguepromise** [comment]
Let's just hope this problem doesn't persist on this months released 6.0.4 update... fingers crossed.

**Comment by donaldsonk** [comment]
We received this feedback from the .Net SE.  So fingers crossed the 6.04 version works correctly.

"We have identified some issues with the updates for .Net core 6.0.3 supplied through WSUS and MUC, this is going to be fixed with the 6.0.4 update."
