### ISSUE TITLE
Problema na página de do EXe

### ISSUE THREAD

**Issue by lzfcarneiro** [dotnet/core#7294]
Prezados, 

A página não está carregando.

Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Qual página não está carregando? Você pode dar mais detalhes sobre o problema que você está encontrando?
