### ISSUE TITLE
dotnet: command not found

### ISSUE THREAD

**Issue by hurdu69** [dotnet/core#7298]
I am using Linux Mint 20.03 Cinnamon x64.
I installed dotnet using the following line of code: `curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel Current`
When I type 'dotnet' in the shell, it says: dotnet: command not found

I creates an alias in .bashrc, like this: `alias dotnet='cd ~/.dotnet;./dotnet'`
It is working when I type dotnet. I creates a console project called MyFSharpApp, like this: `dotnet new console -lang F# -o MyFSharpApp -f net6.0`
user@pc:~/.dotnet$ cd MyFSharpApp
When I type: `user@pc:~/.dotnet$ dotnet run`. It shows me the following error: Couldn't find a project to run. Ensure a project exists in /home/user/.dotnet, or pass the path to the project using --project.
Pleas, somebody help me?

**Comment by rzikm** [comment]
Your alias is changing your working directory. If not done automatically, you should make sure the `dotnet` binary is in `PATH` by adding `export PATH=$PATH:~/.dotnet` to your bashrc

**Comment by carlossanlop** [comment]
No follow up, but it has been answered. Closing.
