### ISSUE TITLE
Issue solve, thanks

### ISSUE THREAD

**Issue by RutchilynGo** [dotnet/core#7299]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

```
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>
```

got an error in my command prompt

**Comment by rzikm** [comment]
Can you please share the command prompt you are trying to run and the output (error message) of the command?
