### ISSUE TITLE
UWP app store submission fails due to certification after 3rd party library integration

### ISSUE THREAD

**Issue by Hochman85** [dotnet/core#73]
Hi,

- I have got an app which is already on the store (for QA) and I am trying to submit an update for after integrating a 3rd party voip library. 
- Submission failed due to certification problem caused by the 3rd party library apparently (please see attached screenshot)

![store rejecting voip lib](https://cloud.githubusercontent.com/assets/5698730/15189337/03846a9e-17a2-11e6-80d8-bc38d1c66d4f.JPG)

- The store suggests the certification tool be used to fix any signature issue. However, the certification tool does not work as it only takes Xap, Appx or AppxBundle while the binary I’m trying to upload is AppxUpload (which was working fine before)
- Link recommended to follow (from the store submission logs): https://msdn.microsoft.com/library/windows/apps/hh694081.aspx
- I suspect the issue happened when I decided to set AppxPackageSigningEnabled to false in MSBuild command (it was true before and submission used to work fine). If that flag was kept to true (after integrating the voip library), the MSBuild command would fail (please see attached screenshot).

- The command used was: 
MSBuild .\MyApp.sln /t:Rebuild /p:Configuration=Release /p:Platform=ARM /p:PreBuildEvent= /p:AppxPackageIsForStore=true /p:UapAppxPackageBuildMode=CI /p:AppxPackageSigningEnabled=false

![msbuild signature failure](https://cloud.githubusercontent.com/assets/5698730/15189342/0dc1bc1e-17a2-11e6-8479-9d6720aaafb9.JPG)

- The bit that is failing in the voip library is a service (that runs in the background). I was using the same main project certificate to sign it before I decided to turn off the AppxPackageSigningEnabled flag since the approach did not work!
- I am not sure whether there is any requirement third-party libraries need to fulfill. Is there anything we, as developers, need to know (and forward to that voip library tech team) regarding a third-party service certification for store submission? Or is it something I am doing wrong in the MSBuild command?

Please feel free to move this issue to any category you think is more suitable (can't find store-related issue entry).

Any help would be appreciated :)

Thanks!
Hisham

**Comment by jkotas** [comment]
cc @MattWhilden

**Comment by MattWhilden** [comment]
Not all Windows APIs are available for UWP applications. You'll need to get a version of the VOIP library that targets the UWP APIs.

This repo isn't well suited for this issue so I'm going to close out this issue. Please feel free to follow up with me in email at dotnetnative@microsoft.com if you need more information or clarification. Happy to help.

**Comment by Hochman85** [comment]
@MattWhilden 
Hi Matt, the VOIP library we have integrated is **definitely** a **UWP** one. Apart from the email address provided, could you please suggest another repo (e.g. MSBuild / store / packaging related) so I can move this issue?
If the reason of closing this issue was the fact that it did not target UWP could you please re-open it? If it was the repo scope then that'd make sense.
Thanks.

**Comment by MattWhilden** [comment]
Hmmm. GetDefaultAudioCaptureId does appear to be in the Win10 surface area. Perhaps this is a bug in the Cert tools?

Unfortunately, the vast majority of the UWP stack (compiler, cert tools, etc) aren't available on GitHub so there's no good public repo for those issues. I'm happy to get you connected with the right folks if you shoot me a mail at the above address.

**Comment by Hochman85** [comment]
Thanks Matt - already sent you an email and I think we got our first conversation (just going through the emails now as we speak). I really appreciate!
