### ISSUE TITLE
Parameter Problem in Tutorial

### ISSUE THREAD

**Issue by TheRealDeLorian** [dotnet/core#7300]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I copied the code a red squiggly line under [Parameter] appeared saying "The type or namespace name 'Parameter' could not be found (are you missing a using directive or an assembly reference?) [Final-Project-OOP-TheRealDeLorian]csharp(CS0246)"

**Comment by rzikm** [comment]
@mairaw Can you please help? Maybe the tutorials are missing adding some `using` directive.

**Comment by mairaw** [comment]
@TheRealDeLorian can you paste the contents of the files you modified to see if they match what we have on the site?

**Comment by TheRealDeLorian** [comment]
​Here is the code inside my pages/Counter.razor file 




@page ​"​/counter​" 
  
 ​<​PageTitle​>Counter</​PageTitle​> 
  
 ​<​h1​>Counter</​h1​> 
  
 ​<​p​>Current count: ​@currentCount​</​p​> 
  
 ​<​button​ ​class​=​"​btn btn-primary​"​ ​@onclick​=​"​IncrementCount​"​>Click me</​button​> 
  
 ​@code​ ​{ 
 ​    ​private​ ​int​ ​currentCount​ ​=​ ​0​; 
  
 ​    [​Parameter​] 
 ​    ​public​ ​int​ ​IncrementBy​ ​{​ ​get​; ​set​; ​}​ ​=​ ​5​; 
  
 ​    ​private​ ​void​ ​IncrementCount​() 
 ​    { 
 ​        ​currentCount​+=​IncrementBy​; 
 ​    } 
 ​}

**Comment by mairaw** [comment]
So weird! I'm glad it's working now.
