### ISSUE TITLE
After creating the BlazorApp directory and it is created succesfully, when I try to run the command cd BlazorApp it says cd: no such file or directory: BlazorApp. What went wrong?

### ISSUE THREAD

**Issue by sheilapolichetti** [dotnet/core#7303]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Are you sure you spelled the name correctly in the `dotnet new` command? You can list all files+directories in the current dir using `ls` command or by checking with MacOS equivalent of File Explorer.

**Comment by mairaw** [comment]
Can you confirm you used the command from the tutorial?
`dotnet new blazorserver -o BlazorApp --no-https -f net6.0`

Did you get any error messages after you ran that command? If not, what do you see in the directory you're trying to run the `cd` command if you run the `ls` command as @rzikm suggested?
