### ISSUE TITLE
dotnet new console -o MyApp

### ISSUE THREAD

**Issue by utrenic** [dotnet/core#7306]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: macos
```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when I run:
```
> dotnet new console -o MyApp 
```
from a terminal, I got nothing.

How long does it take for me to create files in MyApp directory?

Kel

**Comment by rzikm** [comment]
Can you please be more specific about "I got nothing?", does the command finish without creating the directory, or does the command freeze?

**Comment by utrenic** [comment]
I change the shell to zsh and it works now.

**Comment by rzikm** [comment]
I will close the issue then, if you encounter any more problems, you can create another issue
