### ISSUE TITLE
 Environment variables

### ISSUE THREAD

**Issue by chunlinWJB** [dotnet/core#7310]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by chunlinWJB** [comment]
dotnet-watch:

  Environment variables:

   DOTNET_USE_POLLING_FILE_WATCHER
   When set to '1' or 'true', dotnet-watch will poll the file system for
   changes. This is required for some file systems, such as network shares,
   Docker mounted volumes, and other virtual file systems.

   DOTNET_WATCH
   dotnet-watch sets this variable to '1' on all child processes launched.

   DOTNET_WATCH_ITERATION
   dotnet-watch sets this variable to '1' and increments by one each time
   a file is changed and the command is restarted.

  Remarks:
   The special option '--' is used to delimit the end of the options and
   the beginning of arguments that will be passed to the child dotnet process.
   Its use is optional. When the special option '--' is not used,
   dotnet-watch will use the first unrecognized argument as the beginning
   of all arguments passed into the child dotnet process.

   For example: dotnet watch -- --verbose run

   Even though '--verbose' is an option dotnet-watch supports, the use of '--'
   indicates that '--verbose' should be treated instead as an argument for
   dotnet-run.

  Examples:
   dotnet watch run
   dotnet watch test


Usage:
  dotnet-watch [options] [[--] <additional arguments>...]]

Options:
  -q, --quiet                Suppresses all output except warnings and errors
  -v, --verbose              Show verbose output
  -p, --project <project>    The project to watch
  --list                     Lists all discovered files without starting the watcher

Additional Arguments:
  Arguments passed to the application that is being run.

**Comment by rzikm** [comment]
I don't understand what the issue is for, are you getting an error when trying to run the `dotnet watch` command? If so, can you verify that you are running the command inside the project folder?

**Comment by mairaw** [comment]
I think this is something else. Are you sure you typed `dotnet watch` without the hyphen?

@danroth27 could any old tooling cause this?
