### ISSUE TITLE
Istalled the .net 6 SKD but does not work

### ISSUE THREAD

**Issue by renatamandelman** [dotnet/core#7312]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed the .net 6 skd in my M1 mac, but always show me the error zsh: command not found: dotnet

**Comment by rzikm** [comment]
Have you restarted the terminal session? Also, if you installed the SDK using the `dotnet-install.sh` script, you need to manually add the installed directory to your `PATH`

**Comment by mairaw** [comment]
Also make sure you install the Arm64 version if it's a M1 Mac.
