### ISSUE TITLE
在资源组中创建 AKS 群集

### ISSUE THREAD

**Issue by lijiandesigner** [dotnet/core#7314]
(BadRequest) The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/cpu-quota
Code: BadRequest
Message: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/cpu-quota

**Comment by rzikm** [comment]
Can you elaborate on what is the issue? What are you trying to accomplish? The error message and the link seem to explain why the action you are attempting is not possible.
