### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by L-sagar303** [dotnet/core#7318]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Where do you get the error message? Is it after you try to run dotnet in powershell prompt? If so, did you open a fresh powershell window after installation?
