### ISSUE TITLE
Dotnet is not a recognized program

### ISSUE THREAD

**Issue by Starkiller0310** [dotnet/core#7319]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed dotnet but It shows it is not a recognized internal or external command

**Comment by rzikm** [comment]
Where do you get the error message? Is it after you try to run `dotnet` in powershell prompt? If so, did you open a fresh powershell window after installation?
