### ISSUE TITLE
zsh: command not found: dotnet

### ISSUE THREAD

**Issue by vijay-a-nikam** [dotnet/core#7320]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

zsh: command not found: dotnet

**Comment by rzikm** [comment]
Hi, have you opened a new terminal session after installing dotnet SDK? The session needs to pick up the updated PATH variable.
