### ISSUE TITLE
.NET is not currently working for me

### ISSUE THREAD

**Issue by idkwhattonames** [dotnet/core#7321]
If i go into Visual Studio Code and type in: dotnet new console an then press enter it says:

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:1 char:1
+ dotnet new console
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException       
    + FullyQualifiedErrorId : CommandNotFoundException

I do not know what to do to fix this, I have spent 45 minutes trying to figure it out. (Yes, in case your wondering I have tried looking at YouTube)
![Error Image](https://user-images.githubusercontent.com/102519226/160378007-0ff54be1-1162-4209-b6c3-e9220a4915b4.PNG)

**Comment by rzikm** [comment]
Hi, did you try this right after you installed .NET? You need to open a fresh PowerShell session (or restart VS Code) in order for it to pick up the updated `PATH` environment variable.

**Comment by idkwhattonames** [comment]
OK, thanks. I'll Try that in the morning
