### ISSUE TITLE
not able  to install in windows 10

### ISSUE THREAD

**Issue by lokeshvp2000** [dotnet/core#7322]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Can you provide more information about what issues occurred during the installation process? What is the error message that is being reported? What .NET version are you trying to install?
