### ISSUE TITLE
(MacOS) dotnet process 250% CPU only when developing dotnet 5 Web mvcApp. 

### ISSUE THREAD

**Issue by seanpaulharsevoort** [dotnet/core#7328]
### Description
Got this issue when i developed on a dotnet 5 MVC WebApp for a school project. My macbook pro just started to take off. This happend when i ran the app via Visual Studio 2019 MacOs (did not try it with VS 2022 for mac yet).
I opened activity monitor and there was a dotnet process running at 250% CPU. I already stopped the app! 
When i force quit the dotnet process my macbook calmed down.  When i rebuild or re-run the same thing happens again.

### Configuration
Visual Studio 2019 for Mac
Visual Studio 2022 for Mac
Dotnet version: 5.0
Mvc App with induvidual user accounts
MacOs: Monterey version 12.0.1
Architecture: x64 (core i9)
Chrome: Version 99.0.4844.84 (Official Build) (x86_64)

### Regression?

I never came across this when developing web API's. Seems to be only occuring with mvc apps.

### Other information
Macbook specs: 16" 2019 model, core i9, 64gb ram and 2tb ssd.

<img width="789" alt="Screenshot 2022-03-29 at 17 40 13" src="https://user-images.githubusercontent.com/38066215/160650762-486db987-0594-4c71-ad48-cde02dcb9990.png">

<img width="794" alt="Screenshot 2022-03-29 at 17 46 24" src="https://user-images.githubusercontent.com/38066215/160652073-2e3ad96b-3c80-47ea-b5b9-4a131af3ef98.png">

**Comment by carlossanlop** [comment]
Can you provide more information? What version of VS Studio were you using? Can you share a sample of the project you were working on?
