### ISSUE TITLE
Framework 4.8 shows up in installed programs but cannot access it!

### ISSUE THREAD

**Issue by abycoder500** [dotnet/core#7329]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am getting dotnet is not recognized internal or external command error in both command prompt and visual studio 2019. the control panels shows that 4.8 sdk is installed but I cant use it.

**Comment by mairaw** [comment]
I think there are some mixed goals here. This tutorial is for you to learn how to create applications using .NET 6.

Are you trying to run an application that requires .NET Framework 4.8 instead?

**Comment by abycoder500** [comment]
Just installed .net 4.8 but neither command prompt or Visual studio is recognizing 4.8 installation. so I am unable to follow any tutorial whatsoever.

**Comment by mairaw** [comment]
Correct, .NET 6 requires VS 2022. If you want to develop in Visual Studio with .NET Framework 4.8, you need to install the developer pack.

You can find the link to download the developer pack at https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

Direct link: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer

Let us know if this helps.

**Comment by prajaktakapoor** [comment]
I have installed all the packs, sdk, runtime, etc that is required for .NET 4.8 still it is not getting recognized. Where should be the problem?
