### ISSUE TITLE
Encountered "Failed" message while installing 2020.3.32f1 using Install Editior on Unity Hu 3.1.1

### ISSUE THREAD

**Issue by cslchan1** [dotnet/core#7331]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
We won't be able to help you with that specific issue. Please go to https://support.unity.com/ to try to get Unity support.
