### ISSUE TITLE
Setting the product version in the project file does not work

### ISSUE THREAD

**Issue by BruceQiu1996** [dotnet/core#7332]
### Description

When I set the product version in the project file for a .NET 5 console program, it does not take effect。
I was set product version "1.0.1.220328_Beta" in my project file.but display is "1.0.0" in my debug folder.

### Other information
![image](https://user-images.githubusercontent.com/28331315/161193661-dfd98636-3273-4339-8a1d-8ee1e09a04bd.png)
![85fd10c1701c755c0be36cd22a08f35](https://user-images.githubusercontent.com/28331315/161193870-ff4c9163-188c-41ae-9d9e-e48a5451fb3a.png)

**Comment by tannergooding** [comment]
CC. @dsplaisted 

Pretty sure there isn't an actual `ProductVersion` property and you want to use `InformationalVersion` (or one of the properties used to build it, such as `VersionPrefix`/`VersionSuffix`) instead: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generateassemblyinfo

**Comment by BruceQiu1996** [comment]
Thx,that's right. @tannergooding

**Comment by d-vs** [comment]
> CC. @dsplaisted
> 
> Pretty sure there isn't an actual `ProductVersion` property and you want to use `InformationalVersion` (or one of the properties used to build it, such as `VersionPrefix`/`VersionSuffix`) instead: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generateassemblyinfo

Pretty sure this is a very misleading property in that case! Thanks for the answer.
