### ISSUE TITLE
Dotnet not found

### ISSUE THREAD

**Issue by kaushik199501** [dotnet/core#7337]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you install the SDK? If so, which version?
And are you on a M1 chip?

**Comment by kaushik199501** [comment]
Yes, i did install the SDK.
I have installed the version 6.0 of SDK x64
And i am using the M1 chip macbook pro

**Comment by mairaw** [comment]
So please uninstall the x64 version, install the Arm64 version and see if that works. I'll add a note on the tutorials that M1 chip users need to install that version until we can automatically detect that.
