### ISSUE TITLE
I am just bignner to ASP.net once ya ran dotnet watch I am unable to navigate to web page (.net 5 version)

### ISSUE THREAD

**Issue by SAMShweta** [dotnet/core#7338]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by SAMShweta** [comment]
dotnet-watch:

  Environment variables:

   DOTNET_USE_POLLING_FILE_WATCHER
   When set to '1' or 'true', dotnet-watch will poll the file system for
   changes. This is required for some file systems, such as network shares,
   Docker mounted volumes, and other virtual file systems.

   DOTNET_WATCH
   dotnet-watch sets this variable to '1' on all child processes launched.

   DOTNET_WATCH_ITERATION
   dotnet-watch sets this variable to '1' and increments by one each time
   a file is changed and the command is restarted.

  Remarks:
   The special option '--' is used to delimit the end of the options and
   the beginning of arguments that will be passed to the child dotnet process.
   Its use is optional. When the special option '--' is not used,
   dotnet-watch will use the first unrecognized argument as the beginning
   of all arguments passed into the child dotnet process.

   For example: dotnet watch -- --verbose run

   Even though '--verbose' is an option dotnet-watch supports, the use of '--'
   indicates that '--verbose' should be treated instead as an argument for
   dotnet-run.

  Examples:
   dotnet watch run
   dotnet watch test


Usage:
  dotnet-watch [options] [[--] <additional arguments>...]]

Options:
  -q, --quiet                Suppresses all output except warnings and errors
  -v, --verbose              Show verbose output
  -p, --project <project>    The project to watch
  --list                     Lists all discovered files without starting the watcher

Additional Arguments:
  Arguments passed to the application that is being run.

**Comment by SAMShweta** [comment]
Found Solution by Own Thanks!!!

**Comment by mairaw** [comment]
On .NET 5, the command was different `dotnet watch run`. The tutorial as written requires .NET 6.
