### ISSUE TITLE
Hello World in dotnet

### ISSUE THREAD

**Issue by Iwada001** [dotnet/core#7340]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant

// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);

**Comment by carlossanlop** [comment]
From the text, it's not clear what the problem is. I'm closing the issue, but if needed, please open a new issue providing a description of the problem.
