### ISSUE TITLE
Open the Program.cs file in any text or code editor, such as Notepad or Visual Studio Code. The Program.cs file is located on the newly created MyApp directory.Then, add the highlighted line after the code that prints "Hello, World!", like the following:

### ISSUE THREAD

**Issue by ranjthc** [dotnet/core#7341]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Not clear what's the issue here. Can you give more details @ranjthc?
