### ISSUE TITLE
Exception Unhandled

### ISSUE THREAD

**Issue by DrChainz** [dotnet/core#7345]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Following the tutorial and using the command like tool as directed - this causes the following error:

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Someone online said has to do with change the .net core target framework in the properties for the project - but I can't find that yet in the project defintion following these instructions:  https://stackoverflow.com/questions/71217706/net-core-could-not-load-file-or-assembly-system-runtime-version-6-0-0-0-cul

would be good if your tutorials that tell you how to use your command line tools don't generate errors dunno how to easily fix - or baring that - some better instruction how to resolve.

**Comment by mairaw** [comment]
We have removed that tutorial from the site. Please try https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro instead.

Apologies for not getting back to you sooner.
