### ISSUE TITLE
Add way to cancel execution of blocking operations

### ISSUE THREAD

**Issue by agowa338** [dotnet/core#7349]
### Description

I worked with the UIAutomation library and discovered an issue with ".Invoke" being blocking in some cases and this lead me down the whole rabbit hole of the problem of canceling stuff that went wrong.
A simple example of a thread going wrong, imagine we're calling a function of a library that contains:
```
Thread.Sleep(1000000);
```
Currently, dotnet has no way to wrap this into an async call that can be canceled. Even if it is wrapped, dotnet will *always* wait until the thread is finished. This is not an issue for the above example, BUT if the call is to a library that causes a lot of IO it is. So far the only solution to this is to restart the whole application.

### Configuration

* Which version of .NET is the code running on? => 6.0
* What OS and version, and for Linux, what distro? => Windows 11 - 22563.1
* What is the architecture (x64, x86, ARM, ARM64)? => x64
* Do you know whether it is specific to that configuration? => No
* If you're using Blazor, which web browser(s) do you see this issue in? => All, it occurs in the backend.

### Regression?

I don't know. From documentation, however, it was still supported in .NET 5 https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort?view=net-6.0

### Potential fix

Re-add System.Threading.Thread.Abort, but with a guarantee to abort immediately.
Or add something like:
```
function async abortable foo() {
  some.code(with, current, behaviour);
  blocking.library.call();
  some.other.code();
}
function main() {
  var task = Task.Factory.StartNew(() => foo());
  // some unrelated code
  task.AbortNow();
}
```

Where:
* abortable: Indicates a function that can be canceled in a potentially unsafe way.
* task.AbortNow(): This is the call to the task that forces immediate termination of the task especially when the thread is active *without* waiting for the task to complete or even process anything.

**Comment by GrabYourPitchforks** [comment]
See https://github.com/dotnet/runtime/issues/69622, which looks close to what you are looking for. If you need a new API beyond this, please feel free to file an issue in the __runtime__ repo directly.
