### ISSUE TITLE
ResourceManager in .NET core does not fallback to unspecfic resource when using an unlocalized culture

### ISSUE THREAD

**Issue by Drapondur** [dotnet/core#735]
Version: .NET Core App 1.1
OS Windows 7 (German)
Assembly System.Resources.ResourceManager, Version=4.0.0.0 
from %userprofile%\.nuget\packages\system.resources.resourcemanager\4.3.0\ref\netstandard1.0\System.Resources.ResourceManager.dll

I have a simple Resource named TestRes.resx plus three culture specific resources TestRes.de.resx, TestRes.en.resx and TestRes.it.resx.
There is one single key named "Test" with values indicating the used culture
Value from "de" resx
Value from "en" resx
Value from "it" resx
Value from unspecific resx.

Everything works just fine as long a I am using those cultures for which resx files do exist. But when calling GetString with another culture (i.e. "fr") the result (on my German OS) is: _Value from "de" resx_ instead of _Value from unspecific resx_

This behaviour is different from the .NET framework where using a culture for which no resx is given yields the value from the "default" resx (that without a culture suffix).

Am I missing something? Is this by design?

I've attached a zip file demonstrating the issue. There are two projects: a .NET Core Console App. The second one is a NET461 console app I added for comparison.

[LocalizationIssue.zip](https://github.com/dotnet/core/files/1128574/LocalizationIssue.zip)

**Comment by Drapondur** [comment]
Sorry for not having mentioned the .NET Core version in the title!

**Comment by Petermarcu** [comment]
@tarekgh can you take a look? Should we reopen this is corefx?

**Comment by tarekgh** [comment]
@Drapondur I'll take a look. I'll move the issue to corefx repo too.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/corefx #21983](https://github.com/dotnet/corefx/issues/21983) via [**ZenHub**](https://www.zenhub.com/)
