### ISSUE TITLE
bonjour je ne retrouve pas program.cs sur mon pc ?

### ISSUE THREAD

**Issue by yannick006** [dotnet/core#7350]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by joperezr** [comment]
Hello, can you please share a bit more information about what are you trying to follow and what are the issues you are facing? From the title, it seems like you are having issues finding Program.cs locally. After downloading and installing the dotnet.sdk, you should be able to run `dotnet new console` on a folder which will create a project and a Program.cs file with hello world program that you should be able to run by running: `dotnet run` on your command prompt.
