### ISSUE TITLE
Error 1053: Cannot start windows service (.Net Core worker service) due to extra extension methods on IHostBuilder

### ISSUE THREAD

**Issue by xocolatl-aficionado** [dotnet/core#7351]
Goal: I'm trying to run a .Net Core 3.1 Worker service as a windows service.

Setup: I've used the Worker service default template via Visual Studio.

To add windows service functionality to this, I installed the Microsoft.Extensions.Hosting.WindowsServices nuget and thereafter added .UseWindowsService() as follows:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseWindowsService()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                })
                ;
```
Thereafter, the service can be successfully started via:

```
sc create <WorkerSvcName> binPath=<C:/local/path/to/exe>
sc start <WorkerSvcName>
```

Problem: However, I need to use further extension methods on IHostBuilder, like for example .UseNServiceBus (NServiceBus.Extensions.Hosting nuget). When I do so, in addition to the above setup, I always get:

```
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.
```
What I've tried: This persists for all the following configurations:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                X
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                })
                X
                .UseWindowsService()
                X
```
as well as:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                X
                .UseWindowsService()
                X
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                })
                X
                ;
```
where X =

```
.UseNServiceBus(hostBuilderContext =>
                {
                    var endpointConfiguration = new EndpointConfiguration("MyEndpoint");
                    // configure endpoint here
                    return endpointConfiguration;
                })
            ;
```
The alternative placements above tell me this may not have anything to do with the order of configuration in CreateHostBuilder(). I've reproduced the same with other extensions methods too.

Question: Any ideas on why I cannot use any other extension methods and continue running the windows service?

**Comment by xocolatl-aficionado** [comment]
I see this issue alluded to [here ](https://github.com/dotnet/extensions/issues/2496#issuecomment-547302017)as well.

**Comment by joperezr** [comment]
@eerhardt I'm not very familiar with M.E.Hosting.WIndowsServices, do you mind taking a quick look here?

**Comment by eerhardt** [comment]
@xocolatl-aficionado - I am unclear on the problem. Can you show the exact code you are using?  When I use the code you have above, `dotnet run` fails with:

```
Unhandled exception. System.Exception: A transport has not been configured. Use 'EndpointConfiguration.UseTransport()' to specify a transport.
   at NServiceBus.EndpointCreator.InitializeTransportComponent()
   at NServiceBus.EndpointCreator.Initialize()
   at NServiceBus.EndpointCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IConfigureComponents configureComponents)
   at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IConfigureComponents configureComponents)
   at NServiceBus.HostBuilderExtensions.<>c__DisplayClass0_0.<UseNServiceBus>b__0(HostBuilderContext ctx, IServiceCollection serviceCollection) in /_/src/NServiceBus.Extensions.Hosting/HostBuilderExtensions.cs:line 34
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in C:\DotNetTest\AspNet\Program.cs:line 3
```

I am not familiar with NServiceBus. So I don't know what to do here. This might be a better question for the NServiceBus repo.

**Comment by xocolatl-aficionado** [comment]
I've realized the problem lies in certain implementation details inside the extension methods I was trying to test with. Using the .UseSerilog() extension does allow starting the windows service. Good to close, thanks!

**Comment by gabrieldelaparra** [comment]
Changing 
```c#
builder.SetBasePath(Environment.CurrentDirectory).AddJsonFile("appsettings.json")
```

to 
```c#
builder.SetBasePath(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location)).AddJsonFile("appsettings.json")
```

fixed it for me and allowed me to keep using Serilog.

**Comment by Woff2** [comment]
@gabrieldelaparra https://stackdev.space/questions/is-it-possible-to-operate-multiple-versions-of-code-simultaneously-within-a-solitary-windows-service-using-net
