### ISSUE TITLE
I input "dotnet"runtiming,not commend

### ISSUE THREAD

**Issue by boombbo** [dotnet/core#7353]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by joperezr** [comment]
Thank you for logging the issue @boombbo, I'm sorry but the title is not very clear to me so I don't understand which problems you are hitting when trying out the hello-world tutorial. Can you please add a bit more information like the commands you are trying to type in the console and the error that you are getting so we can further investigate what is wrong?
