### ISSUE TITLE
Problems starting .NET

### ISSUE THREAD

**Issue by CynthiaOM** [dotnet/core#7354]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/102221808/162789455-aeea3dd9-2d80-48c6-a7b1-ae0dfb8188e7.png">
<img width="522" alt="Screenshot 2022-04-11 174411" src="https://user-images.githubusercontent.com/102221808/162789740-012fcb86-3052-440c-a97e-3e853b99ee8d.png">

**Comment by dayo05** [comment]
Please check your version of dotnet

**Comment by mairaw** [comment]
That error message indicates you don’t have .NET 6 SDK installed. Please make sure you have installed that version and let us know if that worked.

**Comment by mairaw** [comment]
Sounds good @CynthiaOM. .NET 6 requires Visual Studio 2022. So let us know how that goes. But you shouldn't need VS to complete this tutorial.
