### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by Boba129** [dotnet/core#7355]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

whenever I try to download it always says network error even though everything thing else downloads fine.

**Comment by joperezr** [comment]
Thanks for logging the issue @Boba129. Could you please log more information on where are you seeing a network error? Is it when you are trying to download the SDK? We need more info in order to be able to diagnose what the issue you are hitting is.
