### ISSUE TITLE
command not found error

### ISSUE THREAD

**Issue by castroj8** [dotnet/core#7356]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Jcs-MacBook-Pro:~ jccastro$ ~dotnet
-bash: ~dotnet: command not found
Jcs-MacBook-Pro:~ jccastro$

**Comment by joperezr** [comment]
Hello @castroj8, thanks for logging the issue. Seems like the problem you are running into is that the dotnet command is not part of your PATH, which explains why the terminal can't find `dotnet` executable. Could you please share how did you install dotnet in your machine? If you haven't installed it yet, please click the purple button on the tutorial which will help you download and install the SDK which is a pre-requirement for that tutorial:
![image](https://user-images.githubusercontent.com/13854455/163456716-56e2a593-1128-4646-b996-65cffa14c673.png)
