### ISSUE TITLE
How To Multiple Database This Scenario?

### ISSUE THREAD

**Issue by msbeden** [dotnet/core#7357]
Hello.

I'm writing a marketplace integration application, but I'm stuck on something. Since I'm new to .NET Core, I don't know what to do.

The script is like this:
* Tables such as user information, general categories, marketplace categories, announcements will be in the General Database. Login to the panel will be provided from this database.

* When the user logs in, he will be able to access the information of his own company with the sql connection sentence belonging to the user in the database.

* In the database of the company; inventory information, inventory pictures, customer information tables.

We already have an API. I was able to separate migrations by session as general-company. But I could not separate the data extraction process.

I duplicated the repository transaction and created a separate one for the company. However, it gives an error.

![multiple](https://user-images.githubusercontent.com/14031329/162911141-0aa85906-fcc7-4596-84d8-c9009c724776.png)

**Startup.cs**
`
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer();
    string connectionString = Configuration.GetConnectionString("default");
    services.AddDbContext<WebApiDbContext>(options => options.UseSqlServer(connectionString));
    DBInitializer.Initialize(connectionString);
    services.AddCors();
    services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("Authentication", new OpenApiInfo { Title = "Authentication", Version = "v1" });
        c.SwaggerDoc("GeneralControllers", new OpenApiInfo { Title = "General Tables", Version = "v1" });
        c.SwaggerDoc("FirmControllers", new OpenApiInfo { Title = "Firm Tables", Version = "v1" });

        var jwtSecurityScheme = new OpenApiSecurityScheme
        {
            Scheme = "Bearer",
            BearerFormat = "Jwt",
            Name = "Jwt Authentication",
            In = ParameterLocation.Header,
            Type = SecuritySchemeType.Http,
            Description = "Aşağıdaki metin kutusuna **_SADECE_** Jwt Bearer tokenınızı girin!",
            Reference = new OpenApiReference
            {
                Id = JwtBearerDefaults.AuthenticationScheme,
                Type = ReferenceType.SecurityScheme
            }
        };

        c.AddSecurityDefinition(jwtSecurityScheme.Reference.Id, jwtSecurityScheme);
        c.AddSecurityRequirement(new OpenApiSecurityRequirement { { jwtSecurityScheme, Array.Empty<string>() } });
    });

    var mappingConfig = new MapperConfiguration(mc =>
    {
        #region General Tables
        mc.AddProfile(new CountryMapper());
        #endregion

        #region Firm Tables
        mc.AddProfile(new CustomerMapper());
        #endregion

        #region Authentication Tables
        mc.AddProfile(new AuthFirmMapper());
        mc.AddProfile(new AuthGroupMapper());
        mc.AddProfile(new AuthUserMapper());
        mc.AddProfile(new LoginMapper());
        #endregion

    });
    IMapper mapper = mappingConfig.CreateMapper();
    services.AddSingleton(mapper);
    services.AddSingleton(this.Configuration);
    services.AddSingleton<ITokenManagementService, TokenManagementService>();
    services.AddScoped(typeof(IRepository<>), typeof(GeneralRepository<>));
    services.AddScoped(typeof(IBaseService<,>), typeof(BaseService<,>));
    services.AddScoped<ILoginService, LoginService>();
    
    #region General Services
    services.AddScoped<ICountryService, CountryService>();
    #endregion
    
    #region Firm Services
    services.AddScoped(typeof(IRepositoryFirm<>), typeof(FirmRepository<>));
    services.AddScoped(typeof(IBaseServiceFirm<,>), typeof(BaseServiceFirm<,>));
    services.AddScoped<ICustomerService, CustomerService>();
    #endregion
}
`

BaseServiceFirm is copy of BaseService. I duplicated the file. 

The error I get is as follows:
![hata](https://user-images.githubusercontent.com/14031329/162913192-0ad1d081-6fce-4535-bd3c-dacaca9d2fe7.png)
`
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor '
ServiceType: WebApi.Services.Abstractions.ICustomerService Lifetime: Scoped ImplementationType: WebApi.Services.CustomerService': 
Unable to resolve service for type 'WebApi.Models.FirmDbContext' while attempting to activate 
'WebApi.Repositories.FirmRepository`1[WebApi.Models.DatabaseModels.Firm.Customer]'.)'
`

What can I do? Or can you show another example based on the above scenario. I can look at another project.

**Comment by joperezr** [comment]
Hello @msbeden thanks for logging your issue. Having an ASP.NET core application with multiple dbs is not uncommon, and it is supported. You would essentially just need to have multiple connection strings for each of your DBs, and then you would just call the AddDBContext method multiple times using one per connection string which creates a new DBContext-derived type that handles each connection, and you can then use that in your code.

By doing a quick web search online I found tutorials on how to do this, for example https://code-maze.com/aspnetcore-multiple-databases-efcore/. Can you give that a try and let us know if you need any further assitance?
