### ISSUE TITLE
Exact libicu version requirements

### ISSUE THREAD

**Issue by dcermak** [dotnet/core#7358]
The documentation mentions that on SLES 15 and openSUSE Leap, we require `libicu`.
https://github.com/dotnet/core/blob/4665fc75f5d20d8f86713055b769661470d7206a/Documentation/linux-prereqs.md?plain=1#L16

However, which version exactly? At the moment we have two versions available:
- `libicu69`
- `libicu-suse65_1`

**Comment by leecow** [comment]
Our prereq installer does not have a min libicu version indicated. @tarekgh, would you know?

**Comment by tarekgh** [comment]
We always recommend the higher versions. `69` will be better here.

**Comment by joperezr** [comment]
Closing the issue for now since @tarekgh answered the question above. @dcermak feel free to reopen if you have any comments or follow-up questions.
