### ISSUE TITLE
.NET April 2022 Update - .NET 6.0.4, .NET 5.0.16, and .NET Core 3.1.24

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7362]
Release Notes
[6.0.4](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.4/6.0.4.md)
[5.0.16](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.16/5.0.16.md)
[3.1.24](https://github.com/dotnet/core/blob/main/release-notes/3.0/3.1.24/3.1.24.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Distro | 6.0.4 | 5.0.16 | 3.1.24
-- | -- | -- | --
Ubuntu 18.04 |✅|✅|✅| 
Ubuntu 20.04 |✅|✅|✅|
Ubuntu 21.04 |✅|✅|✅|
Centos 7 |✅|✅|✅| 
Debian 10 |✅|✅|✅| 
Debian 11 |✅|✅|✅| 
Fedora 33|✅|✅|✅| 
Fedora 34 |✅|✅|✅| 
OpenSUSE 15|✅|✅|✅| 
Oracle|✅|✅|✅|

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

Known Issues

If there are any more issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by GoranHalvarsson** [comment]
I reported following isse regarding - Ubuntu 21.04:
https://github.com/dotnet/core/issues/7369

**Comment by cchild-atiba** [comment]
Language Support appears to have backpedaled in 6.0.4:
![image](https://user-images.githubusercontent.com/89472770/163239131-4f65cefd-0105-47af-985c-e1e9c950d394.png)
![image](https://user-images.githubusercontent.com/89472770/163238985-b13c18f1-e4eb-4104-8cb8-2de9bd92e3f0.png)

**Comment by dcwhittaker** [comment]
Thanks @cchild-atiba for the flag - @leecow @rbhanda FYI. 
We'll work on getting this fixed.

**Comment by dcwhittaker** [comment]
@agbarbosa are you still experiencing issues with installing? If so can you share some more details - where did you got the installer from?

**Comment by agbarbosa** [comment]
Hi.... I could fix it by installing the .NET through Visual Studio 2022. By using the SDK msi provided it didn't work due to a missing file used to uninstall the previous version.
