### ISSUE TITLE
IIS interaction

### ISSUE THREAD

**Issue by Rovastar** [dotnet/core#737]
Finally (/sadly) I have to start using .NET core now to host stuff. Been following it for many years but like many others in the IIS support community have been keeping at arms length and seeing how your little project pans out.

Are there any plans for proper IIS interaction for asp.net core stuff?

GUI stuff, similar information/diagnostic tools, WPI install components, etc. Stuff that over the decades I have been used too.

**Comment by Petermarcu** [comment]
This is probably a question best asked on the aspnet/home repo. Do you want to open another issue there?

**Comment by Rovastar** [comment]
Ummh I will but why is this the wrong place. Is this not the place for the asp.net core?

Confused as to 2 projects that have a similar description.......
Can you explain the difference?

**Comment by Petermarcu** [comment]
Because that's where issues specific to asp.net are tracked and monitored. See the filing specific issues section of the readme. https://github.com/dotnet/core/blob/master/README.md

**Comment by Rovastar** [comment]
I have asked over there. I have read the readme still doesn't not explain the difference between what question should be asked where.
I am asking about .net core. 
The readme first line is:
"The dotnet/core repository is a good starting point for .NET Core."

**Comment by Petermarcu** [comment]
@RichLander we should improve the readme so it's easier to know that for asp.net/website specific issues, aspnet/home is the best place to ask questions.

**Comment by svick** [comment]
@Rovastar 

> I am asking about .net core.

I don't think you are. .Net Core does not know anything about IIS. ASP.NET Core does (see [aspnet/AspNetCoreModule](https://github.com/aspnet/AspNetCoreModule) and [aspnet/IISIntegration](https://github.com/aspnet/IISIntegration)).

I think this distinction is nothing new: .Net Framework also does not know anything about IIS, ASP.NET does.

**Comment by Rovastar** [comment]
Yes the are differences. Finding them is a tricky. I suppose I considered this to be the master project and asp.net to be a sub project of it.
Often .net and asp.net for a decade or more have been mostly interchangeable. Erroneous maybe but for the majority of people out there you will here them used interchangeably.

And .net might not know about IIS but IIS knows about both .net and asp.net.

Anyway I have asked in the other section now.

**Comment by Petermarcu** [comment]
I think this issue has concluded here. Closing.
