### ISSUE TITLE
Wrong .NET 6 SDK version number in April Updates

### ISSUE THREAD

**Issue by ben-page** [dotnet/core#7371]
https://github.com/dotnet/announcements/issues/214

`.NET 6.0.4 and .NET SDK 6.0.104` should be `.NET 6.0.4 and .NET SDK 6.0.202`

**Comment by terrajobst** [comment]
I moved this issue because dotnet/announcements isn't supposed to be used as an issue tracker. Only announcements go there. We don't even allow commenting. The goal of that repo is to keep a super higher signal to noise ratio for watchers.

**Comment by leecow** [comment]
Looks like the SDK version was updated on the announcement. Closing this issue.
