### ISSUE TITLE
Application Starts Up with Incorrect Environment on Deployment

### ISSUE THREAD

**Issue by dbheale** [dotnet/core#7380]
This is a new issue that I just noticed within the past couple of days.

### Description

When deploying, there are some conditions that I use to ensure the proper files get deployed. All of that works. 

Here's a sample that's within the csproj file that works fine:
```
<Choose>
  <When Condition="'$(Configuration)'=='DEV'">
	  <ItemGroup>
		  <None Include="appsettings.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
		  <None Include="appsettings.DEV.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
		  <None Include="appsettings.QA.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
	  </ItemGroup>
  </When>
  <When Condition="'$(Configuration)'=='QA'">
	  <ItemGroup>
		  <None Include="appsettings.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
		  <None Include="appsettings.DEV.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
		  <None Include="appsettings.QA.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
	  </ItemGroup>
  </When>
</Choose>
```

Here's a sample of a setting that doesn't work:
```
<PropertyGroup Condition="'$(Configuration)'=='DEV'">
	<EnvironmentName>DEV</EnvironmentName>
</PropertyGroup>
```

Unfortunately, every time I publish now, no matter what configuration I choose, even Debug, it deploys as "Production".

Side note, these are my other configs: 
```
<TargetFramework>net6.0</TargetFramework>
<Nullable>enable</Nullable>
<ImplicitUsings>enable</ImplicitUsings>
<Configurations>Debug;Release;DEV;QA</Configurations>
<EnableDefaultContentItems>false</EnableDefaultContentItems>

```
I've tried publishing through VS and dotnet publish, but I have the same issue.

Here's the Web.Config output:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Hermes.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess">
        <environmentVariables>
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="DEV" />
        </environmentVariables>
      </aspNetCore>
    </system.webServer>
  </location>
</configuration>
```

### Configuration

* Visual Studio Version 17.1.4
* .NET 6.0.4
* Windows 10 x64

**Comment by joperezr** [comment]
Hello @dbheale, thank you for logging this issue. Manually editing the project file to set properties that are conditioned in other properties should be done carefully since ordering does matter as you can run into race conditions where one property might not already be set so your condition might evaluate different to what you expect. How are you doing the deployment? Is it via Visual Studio? Or some different xcopy mechanism to the output of `dotnet publish`?

**Comment by dbheale** [comment]
@joperezr I've historically just used `dotnet publish` but I've tried publishing using visual studio once I started having an issue to no avail. No matter what I do, the application thinks the environment is `Production`. I went back to a branch from January and I have the same issue. When I try the following command, it still starts up in the `Production` environment. 

`dotnet publish Hermes.csproj -c Debug -o D:\Publishes\Hermes`

I am not sure what I could be missing as I've been doing this since last November without issue.

You mentioned a race condition, but I believe that isn't the issue as, please correct me if I'm wrong, the web.config comes out with the proper `<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="DEV" />` value.

**Comment by dbheale** [comment]
Okay, very confused. I restarted the server and now it's working as expected... If anyone has any idea as to why that would have changed anything, please let me know!
