### ISSUE TITLE
error code 134 in visual studio

### ISSUE THREAD

**Issue by G3mtech** [dotnet/core#7387]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

anyone know about this error code?

**Comment by mairaw** [comment]
You don't need VS for Mac to finish this tutorial. However, it's fine to use it if you'd like. But probably the best way to reach the right team would be to report the issue through the Help menu on Visual Studio for this specific problem or go to https://developercommunity.visualstudio.com/report?space=41&entry=problem to report the issue.
