### ISSUE TITLE
sudo apt install fails when fish shell is default

### ISSUE THREAD

**Issue by richlander** [dotnet/core#739]
Encountering error when trying to install Setting up dotnet-sdk-2.0.0-preview2-006497 on a Ubuntu 16.04 based machine having fish installed as default shell.

See: https://github.com/dotnet/core/issues/711#issuecomment-313911366

/cc @livarcocc @egilh

**Comment by omajid** [comment]
Dupe of https://github.com/dotnet/core-setup/issues/2613?

**Comment by richlander** [comment]
It does look like a dupe. Closing this one.
