### ISSUE TITLE
my visual code doesn't get dotnet to run command

### ISSUE THREAD

**Issue by Nabiha23** [dotnet/core#7390]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Nabiha23** [comment]
my visual code doesn't get dotnet to run commands

**Comment by mairaw** [comment]
If you type `dotnet` on the terminal, what error do you get?
