### ISSUE TITLE
Running dotnet shows the usage instructions and then returns error code 129

### ISSUE THREAD

**Issue by mmulji-ic** [dotnet/core#7392]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Using an M1 Mac, simply running dotnet shows the usage instructions and then returns error code 129

``shell
👉  dotnet 

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

 👹 129  
 👉  echo $?
129
 ``

**Comment by mairaw** [comment]
Did you install the Arm64 version of the SDK?

**Comment by mmulji-ic** [comment]
Yes I did, just for future reference, how do I check @mairaw ?

👉  dotnet --list-sdks
6.0.101 [/usr/local/share/dotnet/sdk]
6.0.202 [/usr/local/share/dotnet/sdk]

👉  dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by mairaw** [comment]
Thanks for confirming that. This doc has some information about how to check:
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos

**Comment by mmulji-ic** [comment]
Thanks @mairaw , was looking to see if there was something specific about identifying an ARM installation. Do you have all the information you need?

**Comment by mmulji-ic** [comment]
43f9b184817e4f48ba091d068a4d517c86daafd3
6.0.301
osx-arm64

**Comment by emresindir** [comment]
Have you ever tried to build and/or run any application in your environment? If you haven't yet, you can create a new project by the following command;
`dotnet new console`

after creation is completed, you can run the app by the following command.
`dotnet run`

Please check out the result and share the output. It should be printed "Hello World"

**Comment by mairaw** [comment]
Are you still having issues @mmulji-ic? I realize this is quite old.
