### ISSUE TITLE
nao consigo prosseguir...

### ISSUE THREAD

**Issue by alvessssss** [dotnet/core#7403]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

diz que "the current time is"... nao é um comando interno compativel...

**Comment by mairaw** [comment]
@alvessssss vc pode colar aqui o código que vc está usando?
E vc colocou o código no arquivo Program.cs, salvou o arquivo e aí executou o comando `dotnet run` novamente?

**Comment by alvessssss** [comment]
Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Laptop>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\Laptop>dotnet new console -o MyApp -f net5.0

Bem-vindo(a) ao .NET 5.0.
---------------------
Versão do SDK: 5.0.212

Telemetria
---------
As ferramentas do .NET coletam dados de uso para ajudar-nos a aprimorar sua expe
riência. Eles são coletados pela Microsoft e compartilhados com a comunidade. Vo
cê pode recusar a telemetria definindo a variável de ambiente DOTNET_CLI_TELEMET
RY_OPTOUT como '1' ou 'true' usando seu shell favorito.

Leia mais sobre a telemetria das Ferramentas da CLI do .NET: https://aka.ms/dotn
et-cli-telemetry

----------------
Um certificado de desenvolvimento HTTPS ASP.NET Core foi instalado.
Para confiar no certificado, execute 'dotnet dev-certs https --trust' (somente W
indows e macOS).
Saiba mais sobre HTTPS: https://aka.ms/dotnet-https
----------------
Escreva seu primeiro aplicativo: https://aka.ms/dotnet-hello-world
Descubra o que há de novo: https://aka.ms/dotnet-whats-new
Explore a documentação: https://aka.ms/dotnet-docs
Relate problemas e encontre a fonte no GitHub: https://github.com/dotnet/core
Use 'dotnet --help' para ver os comandos disponíveis ou visite: https://aka.ms/d
otnet-cli
--------------------------------------------------------------------------------
------
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on MyApp\MyApp.csproj...
  Determinando os projetos a serem restaurados...
  C:\Users\Laptop\MyApp\MyApp.csproj restaurado (em 322 ms).
Restore succeeded.


C:\Users\Laptop>cd MyApp

C:\Users\Laptop\MyApp>dotnet run
Hello World!

C:\Users\Laptop\MyApp>The current time is 4/26/2022 10:24:58 PM
'The' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\Laptop\MyApp>the current time is 4/26/2022 10:24:58 PM
'the' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\Laptop\MyApp> the current time is 4/26/2022 10:24:58 PM
'the' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\Laptop\MyApp>current time is 4/26/2022 10:24:58 PM
'current' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\Laptop\MyApp>the current time is 4/26/2022 10:24:58 PM
'the' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\Laptop\MyApp>time is 4/26/2022 10:24:58 PM
O sistema não pode aceitar a hora digitada.
Digite a nova hora: 20:02:45 PM
O sistema não pode aceitar a hora digitada.
Digite a nova hora: 8:03:05 PM
O cliente não tem o privilégio necessário.

C:\Users\Laptop\MyApp>

**Comment by mairaw** [comment]
Alguns pontos:

- Recomendaria você a fazer download da versão 6 do .NET SDK como instruído no passo [install](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install).
- No passo [edit](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit), você precisa abrir o arquivo Program.cs num editor de texto como o Notepad ou VS Code e adicionar a seguinte linha ao programa:
`Console.WriteLine("The current time is " + DateTime.Now);`
Você está tentando digitar parte do comando no command prompt e isso não vai funcionar.

Me avise se isso não for suficiente para te ajudar a prosseguir.
