### ISSUE TITLE
NET 5.0 desktop runtime

### ISSUE THREAD

**Issue by starastins** [dotnet/core#7405]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello !

Tried to run / install the software but it says that the installation package isn't supported by this processor type . I'm running AMD ryzen 9 . is it only available for intel ? 

Regards,
Didzis Starastins. 
![Screenshot 2022-04-27 140738](https://user-images.githubusercontent.com/104507733/165526141-04147e5a-59b0-42c0-80f9-7589486989fb.jpg)

**Comment by svick** [comment]
It seems you downloaded the .Net Runtime for ARM 64 processors. For AMD (and Intel) processors, you want the x64 version.

**Comment by starastins** [comment]
> It seems you downloaded the .Net Runtime for ARM 64 processors. For AMD (and Intel) processors, you want the x64 version.

such a small silly mistake . thank you very much for spotting that :)
