### ISSUE TITLE
Error with running a new console

### ISSUE THREAD

**Issue by Elementrikx** [dotnet/core#7407]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

When I type in ''dotnet new console -o MyApp -f net6.0'' it it shows me that ''It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from: https://aka.ms/dotnet-download'' i dont know what to do

**Comment by mairaw** [comment]
Hi @Elementrikx? Did you install the SDK?

If you did and you still can't type dotnet, then it might be an issue with PATH.

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.
