### ISSUE TITLE
I dont know what I am doing and I was told to come here for help. 

### ISSUE THREAD

**Issue by AngiReynolds** [dotnet/core#7408]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What are you trying to do?

**Comment by AngiReynolds** [comment]
I don't know how to explain this so bare with me. 
I need to put .net on my laptop. I am following the directions but when I get to the part where it says to create my app it says that changes will be made to the existing one and it won't let me go farther. I am so confused.

**Comment by mairaw** [comment]
But are you trying to learn how to code with .NET or do you need .NET on your laptop for something else?

**Comment by AngiReynolds** [comment]
I need it on my laptop for a business I am starting.

**Comment by mairaw** [comment]
So, you are trying to start developing application?

> I need to put .net on my laptop. I am following the directions but when I get to the part where it says to create my app it says that changes will be made to the existing one and it won't let me go farther. I am so confused.

For this, you probably ran the command already, so the project has already been created. You can probably continue the tutorial. To confirm, you can run the `dir` command to see if there's a directory called `MyApp`.

**Comment by AngiReynolds** [comment]
There is a directory called myapp. But I cant do anything with it. I tried run my app open my app. With and without spaces. Can I delete the whole thing and start again?

**Comment by AngiReynolds** [comment]
I actually am not sure what I am doing. I think yes I am trying to develop an app. If my SS worked I could show you better.

**Comment by mairaw** [comment]
> There is a directory called myapp. But I cant do anything with it. I tried run my app open my app. With and without spaces. Can I delete the whole thing and start again?

If you run `cd MyApp` and then `dotnet run`, you should be able to run your program. But you can also delete the folder and start over, no problem.

What is SS?

**Comment by AngiReynolds** [comment]
Ok. How do I delete the folder? 
SS ~ Screen Shot

**Comment by mairaw** [comment]
You can type `del MyApp` and it should delete the folder for you.

**Comment by AngiReynolds** [comment]
Thank you so much! 
You are a life savor. 
I will try this later and let  you know if it helped me.

**Comment by AngiReynolds** [comment]
No I a out of town and have not had the chance to work on my issue, sorry.

**Comment by AngiReynolds** [comment]
I will be back in 3 days. Please do not request my help yet.

**Comment by mairaw** [comment]
Sounds good. Let us know when you're back. You can always reopen the issue as well if it gets closed by the bot.
