### ISSUE TITLE
Lack of description for the dotnet.exe 

### ISSUE THREAD

**Issue by Rovastar** [dotnet/core#741]
not sure where to post this so posting in multiple locations.

Can we have a description for the dotnet.exe (for Windows)?
Currently it just shows up in Task Manger when running with no description and just displaying the exe name "dotnet"
A more meaningful description would be useful mentioning that this is the Core version and probably the version number in there. 
".NET Core runtime" or something.

**Comment by Petermarcu** [comment]
Closing as this is already filed in the right place: https://github.com/dotnet/core-setup/issues/2817
