### ISSUE TITLE
'dotnet test --no-restore' performs no op with no failure if packages cannot be loaded

### ISSUE THREAD

**Issue by spencer-langley** [dotnet/core#7412]
### Description

Testing a project that uses Nuget, after performing a build, including package restore, attempt to run tests in a new context with no network access (this is to ensure unit tests are not calling external services). If running in a context where nuget sources all require network access then an execution of 'dotnet test --no-restore' or 'dotnet test --no-build' exits immediately with no output and no error code. Running in a CI context this is interpreted as a successful test run when in fact no tests passed.

Note that checking Nuget is not necessary in this situation - the package dlls are already in the build output directory of the test runner and projects under test.

To reproduce:
Create solution with a project and a test project with only one nuget package source which is over the network
Restore and build project with connectivity to the network
Remove network connectivity
run 'dotnet test --no-restore' or 'dotnet test --no-build' in the directory of the test project

### Configuration

.NET 6
Windows 10
x64

### Regression?

Don't know if this ever worked differently

### Other information

Believe that even when told not to restore packages or build the cli is doing some linking check before attempting to run and that when this fails it exits without an error. Work around by temporarily adding a file system Nuget source

**Comment by pi3ch** [comment]
@spencer-langley to get more verbose output on what is failing try running `docker build --no-restore` and see if dependencies are missing. 
In my case, running build or test under non-root user cased the same scenario as yours. Workaround was to copy over `.dotnet` and `.nuget` from `/root` to the new dotnet home path `DOTNET_CLI_HOME` and set the right permission for non-root user to write.

**Comment by spencer-langley** [comment]
@pi3ch Interesting - already have a work around by temporarily adding a local nuget restore source, but I hadn't considered the admin permissions angle. Either way the real issue here is that `dotnet test --no-restore` fails SILENTLY, which is potentially disastrous behavior for a test runner in a CI context.

**Comment by vasicvuk** [comment]
We are running tests with mcr.microsoft.com/dotnet/sdk:6.0 container image. And it just silently exists when specifying `--no-restore`. In general, the user has a root privilege and access to `DOTNET_CLI_HOME` but still, nothing happens.

I also tried a local NuGet source but that didn't work also. Any idea how to workaround around it?

**Comment by vasicvuk** [comment]
It was missing few packages in local store that is why it silently exited.

Some error showing reason will help :)

**Comment by mairaw** [comment]
Is this still a valid issue @spencer-langley?

/cc @baronfel

**Comment by nathanojb** [comment]
@mairaw 
I can confirm this is still a thing, as I've spent most of today trying to identifying why some broken tests were not causing a failed build.

**Comment by ElvenSpellmaker** [comment]
I've just run into this issue as we build our Post-Deploy Functional tests in the Build Job and , and it seems you need to add `<IsTestProject>true</IsTestProject>` to the `<PropertyGroup>` section when you use `--no-restore` or `--no-build`, else tests will not run.

It's a really weird error, I noticed in the logs it said:
```
deploy:functional_tests:                      Task Parameter:LogType=NoIsTestProjectProperty (TaskId:2)
deploy:functional_tests:                      Skipping running test for project {0}. To run tests with dotnet test add "<IsTestProject>true</IsTestProject>" property to project file. (TaskId:2)
deploy:functional_tests:                    Done executing task "Microsoft.TestPlatform.Build.Tasks.VSTestLogsTask". (TaskId:2)
deploy:functional_tests: 20:19:39.989     1>Done building target "ShowInfoMessageIfProjectHasNoIsTestProjectProperty" in project "xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.csproj".: (TargetId:2)
```

And then further down:
```
deploy:functional_tests:                    Task "CallTarget" skipped, due to false condition; ('$(VSTestNoBuild)' != 'true' AND '$(IsTestProject)' == 'true') was evaluated as ('true' != 'true' AND '' == 'true').
```

Also linking this thread as it talks about it too: https://github.com/dotnet/sdk/issues/3790
But it got closed without an actual resolution it seems.

According to Microsoft it _should_ be adding that property from `Microsoft.NET.Test.Sdk.props` as soon as you add a package dependency on `Microsoft.NET.Test.Sdk`, but it seems this property somehow fails to get.

**Comment by Evangelink** [comment]
Just been reading through this thread and I just want to confirm I got the scenario right. Because templates are involved in some part of the discussion

You are doing:

1. `dotnet new mstest/xunit/nunit`
2. `dotnet test --no-restore --no-build`

and this is not working?

Or you have some already built project and you are trying to do `dotnet test --no-restore --no-build`?

**Comment by ElvenSpellmaker** [comment]
@Evangelink In my case this is an already existing project. Since adding the `<IsTestProject>true</IsTestProject>` it now works for me but without it the tests get skipped if either `--no-restore` or `--no-build` is present. It seems the auto injection of that property from the test SDK doesn't happen if you supply either of those parameters.

**Comment by Evangelink** [comment]
Thanks for the clarification! I'll look into it tomorrow (I am on CET)

**Comment by Evangelink** [comment]
I can repro the issue when doing

1. `dotnet new nunit` (or another framework)
2. remove `obj` folder
3. run `dotnet test --no-build --no-restore`

I'll check what can be done and I do understand that having no message is not nice but running `dotnet test --no-restore --no-build` on a non-built project is also pretty strange. I am biased because I am part of the test team so I know the inside but basically when running this command you are calling `vstest.console.exe` with the path to the dll (that obviously doesn't exist) so it seems a bit surprising to want to run such command.

**Comment by ElvenSpellmaker** [comment]
> I can repro the issue when doing
> 
>     1. `dotnet new nunit` (or another framework)
> 
>     2. remove `obj` folder
> 
>     3. run `dotnet test --no-build --no-restore`
> 
> 
> I'll check what can be done and I do understand that having no message is not nice but running `dotnet test --no-restore --no-build` on a non-built project is also pretty strange. I am biased because I am part of the test team so I know the inside but basically when running this command you are calling `vstest.console.exe` with the path to the dll (that obviously doesn't exist) so it seems a bit surprising to want to run such command.

Hey, the project _is_ built in a previous job/stage, and is brought down for running later, so the project is definitely built and does run if I manually add the IsTestProject property.

**Comment by Evangelink** [comment]
> Hey, the project is built in a previous job/stage, and is brought down for running later, so the project is definitely built and does run if I manually add the IsTestProject property.

Interesting! I can only repro this behavior by forcing `IsTestProject` to false during the `build` step:

1. `dotnet new nunit`
2. edit csproj to add `<IsTestProject>false</IsTestProject>`
3. `dotnet build`
4. `dotnet test --no-restore --no-build`

In which case, no tests are run and no message is printed.

I have confirmed that running `vstest.console.exe` on the generated dll does work so this is purely a bug on SDK side where the task is not being called as the property is missing.

It's still not clear what's the actual real scenario that is causing `IsTestProject` to not be set...

**Comment by Evangelink** [comment]
@ElvenSpellmaker Would it be possible for you to provide some binlog of when the build of your project?

**Comment by norwd** [comment]
> ... you need to add `<IsTestProject>true</IsTestProject>` to the `<PropertyGroup>` section when you use `--no-restore` or `--no-build`, else tests will not run.

@ElvenSpellmaker, this should be marked as the accepted answer, this is exactly what I needed. Thank you!
