### ISSUE TITLE
The console cannot print dateTime

### ISSUE THREAD

**Issue by zhuyuhao2333** [dotnet/core#7415]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant
![00](https://user-images.githubusercontent.com/103302930/166148003-4c99f3b7-a5f2-430c-ab74-5a01a790940b.PNG)
.

**Comment by mairaw** [comment]
Hi @zhuyuhao2333! 
So the screenshot above shows that you're editing a file named Untitled-3.cs. You should be editing a file named Program.cs right under the MyApp folder. Can you try that and see if the date/time will print?
