### ISSUE TITLE
dotnet : 无法将“dotnet”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写 ，如果包括路径，请确保路径正确，然后再试一次。 所在位置 行:1 字符: 1 + dotnet run + ~~~~~~     + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

### ISSUE THREAD

**Issue by Star-Sky-lover** [dotnet/core#7416]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you install the SDK?

**Comment by Star-Sky-lover** [comment]
您的邮件已收到。
