### ISSUE TITLE
Still no ipv6 on packages.microsoft.com

### ISSUE THREAD

**Issue by BartjeD** [dotnet/core#7435]
In reference to the closed issue: #3016 

It's been more than 6 months and `packages.microsoft.com` still hasn't got an AAAA record.
It doesn't seem like a herculean task to get this done?

The reason for supporting this is: **Mitigate IPv4 scarcity.** 
Most infrastructure environments (which need these packages) have no need for IPv4. The lack of an AAAA record on `packages.microsoft.com` is stalling this transition.

Could someone please arrange this?

Thank you in advance!

**Comment by MihaZupan** [comment]
cc @leecow

**Comment by Fabi** [comment]
When??? It's a rather trivial task to do even in big environments to add ipv6 support for those tings. It's not nice that ipv6 only networks are excluded in 2022

**Comment by BartjeD** [comment]
This still hasn't been arranged.

It would be nice if `https://mcr.microsoft.com/` was also given an AAAA record.

**Comment by DarkMio** [comment]
A world leading cloud operating and providing company still has a  hard requirement on an IPv4 uplink.

What's the hold up here? We're running into issues and paying extra for IPv4 slots, just so dotnet runtimes can be installed and updated.

**Comment by BartjeD** [comment]
Pinging this again,

![image](https://user-images.githubusercontent.com/49863641/200786333-d4754eea-8e6c-42ea-861a-5168866e1ffc.png)


Given that countries like India are now IPv6 only, and that other countries are moving to IPv6 being a lot cheaper than having servers with IPv4 I'm wondering why the infrastructure of one of the most popular programming frameworks doesn't support this (yet?) :D

I can work around this by using Docker's IPv6 infrastructure. But I find it more charming to to install .Net using the debian package manager.

**Comment by revellion** [comment]
Another ping here, this is a necessary ability in 2023. IPv6-only environments is a thing

**Comment by Fabi** [comment]
when

**Comment by JSXRED** [comment]
we also run ipv6 networks where all servers talk purely with ipv6. it is really exhausting to use extra only for .NET apt-HTTP proxies that enable ipv6 <-> ipv4. since there are now quite a few systems. is there any timeline when ipv6 will be available?

**Comment by leecow** [comment]
Issue opened in the packages.microsoft.com repo. 

https://github.com/microsoft/linux-package-repositories/issues/89
