### ISSUE TITLE
IdentityServer / IdentityServer4.AccessTokenValidation

### ISSUE THREAD

**Issue by kalpesh44** [dotnet/core#7442]
I am getting unhandled exception when I pass empty token or null token during authorization after upgrading my API to .net 6.0
So, I am getting HTTP 500 error instead of 401 error.

Message = "Method not found: 'IdentityModel.Client.DiscoveryEndpoint IdentityModel.Client.DiscoveryEndpoint.ParseUrl(System.String)'."
source "IdentityServer4.AccessTokenValidation"
StackTrace = "   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationOptions.ConfigureJwtBearer(JwtBearerOptions jwtOptions)\r\n   at IdentityServer4.AccessTokenValidation.ConfigureInternalOptions.Configure(String name, JwtBearerOptions options)\r\n  

Any one getting this kind of error for .Net 6.0?

**Comment by adamsitnik** [comment]
Based on the input provided by @brockallen I am closing this issue. Thansk!

**Comment by kalpesh44** [comment]
Thank for your reply and help

Kalpesh Dave

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
