### ISSUE TITLE
IF the build process was a success..

### ISSUE THREAD

**Issue by blanthor** [dotnet/core#7448]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I click **Build And Run**, an open file dialog appears for me to select a folder. 
This defaults on the project folder.
I click **Select Folder**
Popup says build ing Player
and then nothing else appears to happen.

**Comment by adamsitnik** [comment]
Hi @blanthor 

Have you tried restarting VS? I wonder if running it as Admin could help (https://github.com/dotnet/core/issues/5895#issuecomment-770378767).
