### ISSUE TITLE
Packages restore failed

### ISSUE THREAD

**Issue by subek** [dotnet/core#745]
# Package restore 

Package restore failed in asp.net core 1.1 
Note : i am referencing my project to  

> "frameworks": {
>     "net461": { }
>   },

Recently i upgraded my project from asp.net core 1.0 to 1.1 and it works fine on my old laptop by i switched the project to fresh new laptop ,Installed visual studio 15 .here is the configuration of the VS 15
![image](https://user-images.githubusercontent.com/6284686/28152554-dcb815c6-67c0-11e7-8128-01e0819d3ad9.png)
I have also installed the required SDK as mentioned on this link 
https://jeremylindsayni.wordpress.com/2016/11/20/upgrading-from-net-core-1-0-t0-1-1-with-visual-studio-2015/
![image](https://user-images.githubusercontent.com/6284686/28152692-7bd88208-67c1-11e7-90be-4f72500f9288.png)
. Now my project json file looks likes this : 
![image](https://user-images.githubusercontent.com/6284686/28152730-ab97a1f4-67c1-11e7-8ae3-4d0b5b05b857.png)
and global.json looks like this 

> {
  "projects": [ "." ]
}

but as you can see the packages are not loading as expected.
when i do dotnet restore from the package manager console 
i get something like this : 
![image](https://user-images.githubusercontent.com/6284686/28152828-2e0bccfa-67c2-11e7-8fe5-ac7ef2c5ec65.png)
Any Idea ??

**Comment by Petermarcu** [comment]
It looks like you are still using the unreleased version of everything from late 2015. I would strongly recommend that you upgrade to the supported SDK and tooling. Is there a reason you can't upgrade to the supported .NET Core tooling?

**Comment by subek** [comment]
@Petermarcu  Thanks for the reply man.. i finally was able to solve the issue but not with the latest version but the version i did the update was ..
Microsoft .Net Core 1.0.1 -SDK 1.0.0 Preview 2- 003131
Microsoft .Net Core 1.0.1 -VS 2015 Tooling Preview 2
and this worked for me.

**Comment by Petermarcu** [comment]
Glad to hear it worked for you.

**Comment by shooreshi** [comment]
Same problem here except the installation of the listed SDK and Tooling did not resolve the issue for me in a particular solution while it did work in others after updating my global.json.  I am currently getting dozens of errors of the type in a specific solution:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1002	The dependency Microsoft.AspNetCore.Hosting.Abstractions 2.0.1 does not support framework .NETFramework,Version=v4.6.1.	

Where the listed dependencies in project.json are not supported.  E.g. error from output:

> error: Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)

Any suggestions other than the nuclear option of removing dotnet 2.1.4 and VS 2017 completely?  Upgrading the solution is out of the question for the moment.
