### ISSUE TITLE
I have no clue on how to open the Index.cshtml file

### ISSUE THREAD

**Issue by jenjen0219** [dotnet/core#7451]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @JENICIDE-1029 

The `.cshtml` file format might not be recognized by your OS, so in the text editor that you are using you need to go to `File -> Open` and choose `Index.cshtml` from the `Pages` directory.

**Comment by JENICIDE-1029** [comment]
Hey @adamsitnik 

Thank you so much for getting back to me, I really appreciate it! Is text editor the same thing as Terminal? 

This is my absolute first time doing this on my mac, I am used to using Visual Studio 2019 on a Windows virtual desktop but I no longer have access to it and am trying to learn how to do it here so any other tips or suggestions would be phenomenal. Thank you for your time. 

Best, 
Jen

**Comment by adamsitnik** [comment]
Hello @JENICIDE-1029

> Is text editor the same thing as Terminal?

No, text editor are things like Notepad or in case of macOS TextEdit.

> I am used to using Visual Studio 2019 

In such a case you should give a try to [Visual Studio Code](https://code.visualstudio.com/).

Here are some tutorials:
https://www.youtube.com/watch?v=LXxjCNfd5b4&ab_channel=MicrosoftDeveloperUS
https://www.youtube.com/watch?v=Z2gImsUMFwI&ab_channel=GrayProgrammer

Please let me know if this helps,
Adam

**Comment by carlossanlop** [comment]
@jenjen0219 We're hoping the above answer helped you. Closing this issue as resolved.
