### ISSUE TITLE
.net installation issue

### ISSUE THREAD

**Issue by nickez01** [dotnet/core#7456]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What kind of issue are you having?

**Comment by richasaklani** [comment]
I got this 

richasaklani@Richas-MacBook-Air ~ % ~$dotnet
zsh: permission denied: /Users/richasaklani

**Comment by richasaklani** [comment]
after installation - also I cant find the untitled folder
