### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by richasaklani** [dotnet/core#7459]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I type ~$dotnet in a new terminal I get this:
richasaklani@Richas-MacBook-Air ~ % ~$dotnet
zsh: permission denied: /Users/richasaklani

**Comment by mairaw** [comment]
Is your mac a M1 mac? If so, did you install the Arm64 version?
