### ISSUE TITLE
.net core 2.0 previewer 2 can not find in Visual Studio

### ISSUE THREAD

**Issue by LGinC** [dotnet/core#746]
# Issue Title
System : Windows10 1703
IDE : VisualStudio 2017

I have installed .net core 2.0 previewer 2 sdk and runtime, and I can use it in cmd or powershell, but I can't find it in VisualStudio2017.(when I create a console app, I try to modify framework from .net coreApp 1.0 to .net coreApp 2.0, but I can not find it)

**Comment by richlander** [comment]
Please install Visual Studio 2017 15.3. Link is here: https://blogs.msdn.microsoft.com/dotnet/2017/06/28/announcing-net-core-2-0-preview-2/. Tell me if that doesn't work.

**Comment by LGinC** [comment]
thank you, but I just add the .net core previewer 2 sdks's path to user environment variable

**Comment by richlander** [comment]
Sure. You can do that, too.
