### ISSUE TITLE
MAUI is not an option in Visual Studio community 2022?

### ISSUE THREAD

**Issue by Jricklefs** [dotnet/core#7460]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
.NET MAUI is still in preview, so it's only available in Visual Studio Community 2022 Preview version as indicated in the tutorial.
