### ISSUE TITLE
failing to run dotnet

### ISSUE THREAD

**Issue by aadenthegoat** [dotnet/core#7461]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 
The command prompt says "The build failed. Fix the build errors and run again."

**Comment by mairaw** [comment]
Can you share more details about the error message you're getting?
