### ISSUE TITLE
installation failed on macos 10.14.6

### ISSUE THREAD

**Issue by vtnate** [dotnet/core#7462]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos 10.14.6

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After installing the sdk using the link, the `dotnet` command at the terminal failed as described in the hello-world tutorial:

` ❯ dotnet` \
`zsh: correct dotnet to done [nyae]? n` \
`zsh: command not found: dotnet`

**Comment by mairaw** [comment]
As the first page states, you need to be on macOS 10.15 or later versions. 
Here's the support matrix: https://docs.microsoft.com/en-us/dotnet/core/install/macos#supported-releases

**Comment by vtnate** [comment]
Thank you for the link and the unreasonably fast response! I got to the tutorial without going through that page. Can I get away with saying "not my fault"? :)
