### ISSUE TITLE
Error: Invalid option(s): -f net6.0    'net6.0' is not a valid value for -f. The possible values are:       net5.0          - Target net5.0       netcoreapp3.1   - Target netcoreapp3.1  For more information, run 'dotnet new webapp --help'.

### ISSUE THREAD

**Issue by MonisAteeque** [dotnet/core#7465]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
That error message indicates you don't have .NET 6 SDK installed. Have you downloaded and installed .NET 6 SDK as shown on the install step?

**Comment by kewur** [comment]
```
 ~/workplace/Project                                                                     
❯ dotnet new install Amazon.Lambda.Templates
Error: Invalid option(s):
  Amazon.Lambda.Templates
For usage information, run:
   dotnet new -h
- ~/workplace/Project   main                                                                              
❯ dotnet --version
6.0.406

```
