### ISSUE TITLE
.NET MAUI is not an available VS2022 option

### ISSUE THREAD

**Issue by Andy-Baxman** [dotnet/core#7466]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Correct @Andy-Baxman. You still need Visual Studio 2022 Preview for developing with .NET MAUI.
