### ISSUE TITLE
windows docker build failed

### ISSUE THREAD

**Issue by wuxinheng** [dotnet/core#7469]
Hello, my friend:
I am a developer from China.
According to the link https://dotnet.microsoft.com/zh-cn/learn/aspnet/microservice-tutorial/docker-image
Unable to build. None of the projects will run on Windows Desktop. Is it caused by the domestic Internet environment? I tried searching baidu, the country's largest search engine, for the answer, but there was no good solution. You can reply to me on Github or by email at 17629957093@163.com.

image Url ：https://gitee.com/wuxinheng/development-of-notes/raw/master/images/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-05-20%20173828.png

**Comment by mairaw** [comment]
@nishanil can you help with this issue?

@wuxinheng do you get any error message?

**Comment by wuxinheng** [comment]
This is the error message screenshot link https://s3.bmp.ovh/imgs/2022/05/21/4b7a0fa3259f3a0a.png, using docker running project in visual studio is also the result  
@nishanil @mairaw

**Comment by nishanil** [comment]
@wuxinheng Have you installed Docker Desktop and is it running?

**Comment by wuxinheng** [comment]
Docker Desktop is already running. CTC1001 error is displayed when running in Visual Studio. Volume sharing is not enabled, you need to set it in Docker Desktop. I try to set it up. But the latest version of Docker Desktop doesn't find the Share Drive setting. I also wondered if Windos Docker could install aspNET. Use the docker pull McR.microsoft.com/dotnet/sdk:5.0 in CMD prompt: Error response from daemon: Get "https://mcr.microsoft.com/v2/": net/http:  Request Canceled while waiting for Connection (Client.Timeout exceeded while awaiting headers). The same command can be installed on centos 7.6 Docker. This is my demo video address: https://www.bilibili.com/video/BV1x94y1U76f?t=6.8  
@nishanil

**Comment by wuxinheng** [comment]
原来我也尝试过代理解决但是没有效果。真的有可能是电脑的问题，我在我的新的台式电脑上没有出现这样的问题。

**Comment by wuxinheng** [comment]
I have found the problem, since I am using Visual Studio Preview, I can reinstall Visual Studio 2022 and it will work normally
