### ISSUE TITLE
sqldependency cache support in net core 2.0?

### ISSUE THREAD

**Issue by PeterPanSuperStar** [dotnet/core#747]
Will be or not?

**Comment by richlander** [comment]
Thoughts @corivera @terrajobst ?

**Comment by karelz** [comment]
Would it be more appropriate to move it to CoreFX repo?
cc @divega

**Comment by divega** [comment]
@karelz it is a SqlClient feature, so I think yes.

**Comment by terrajobst** [comment]
It looks like it's already included:

https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDependency.cs

**Comment by divega** [comment]
Cool it seems @corivera added it post 2.0.

**Comment by richlander** [comment]
So, can we close this, then?

**Comment by divega** [comment]
@richlander Yes. I didn't close it myself because I don't know what exact state (e.g. labels and milestone) you guys would use in this repo.

**Comment by richlander** [comment]
If this issue is covered in the corefx repo, we can close here.

For new product requests, we use the appropriate repo. For bugs, I prefer to keep this bug open for customer tracking even if we create an engineering bug in the appropriate repo. That's the basic model.

**Comment by ChristopherRobinSuperStar** [comment]
Core 2.0 is released, but how to use SqlDependency now? I can't find it in ResponseCache attribute parameters.

**Comment by corivera** [comment]
@ChristopherRobinSuperStar Query notification features will be in 2.1.

**Comment by ChristopherRobinSuperStar** [comment]
https://github.com/corivera  Thank you!

**Comment by ChristopherRobinSuperStar** [comment]
https://github.com/coriverar Is it in Core 2.1 Preview1?

**Comment by corivera** [comment]
Yes, SqlDependency is available in the preview1 SqlClient builds on nuget.

**Comment by ChristopherRobinSuperStar** [comment]
Oh, thank you very very much! You are the best!
