### ISSUE TITLE
Improper Command Name

### ISSUE THREAD

**Issue by Caljay** [dotnet/core#7472]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

The first command displayed to build and run the program, 'dotnet watch' is incorrecnt and should be corrected to 'dotnet watch run'

**Comment by mairaw** [comment]
Did the `dotnet new` command run correctly as shown in the tutorial?
`dotnet new blazorserver -o BlazorApp --no-https -f net6.0`

The tutorial as written requires .NET 6 SDK. If you're getting an error message that the command should be `dotnet watch run`, then you're on a lower version of the SDK.
