### ISSUE TITLE
No templates found matching: 'blazerserver'

### ISSUE THREAD

**Issue by TassieTrooper** [dotnet/core#7473]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

No templates found matching: 'blazerserver'

**Comment by TassieTrooper** [comment]
Odd. I installed .Net 3.1 Core SDK and then it worked.

**Comment by mairaw** [comment]
Maybe it was just a typo. It's supposed to be blazorserver, not blazerserver.

**Comment by TassieTrooper** [comment]
Damn! I have these days the older I get! Thanks :)
