### ISSUE TITLE
i couldn't fix this Build errors while running console app with dotnet , any help please ?

### ISSUE THREAD

**Issue by ernestonkunzimana** [dotnet/core#7475]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.targets(64,5): error MSB4018: The "NetSdkWarning" task failed unexpectedly. [C:\User
s\Ernesto BagaboNkunzi\Desktop\DevOps Net\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.targets(64,5): error MSB4018: System.ArgumentException: Either FormattedText or Reso
urceName must be specified. [C:\Users\Ernesto BagaboNkunzi\Desktop\DevOps Net\MyApp\MyApp.c
sproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.targets(64,5): error MSB4018:    at Microsoft.NET.Build.Tasks.MessageBase.ExecuteCor
e() [C:\Users\Ernesto BagaboNkunzi\Desktop\DevOps Net\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.targets(64,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:
\Users\Ernesto BagaboNkunzi\Desktop\DevOps Net\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.targets(64,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Micros
oft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\Ernesto BagaboNkunzi\Desktop\DevOp
s Net\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.targets(64,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInsta
ntiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, Ta
skHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\Ernesto B
agaboNkunzi\Desktop\DevOps Net\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by michaelgsharp** [comment]
Are you saying you fixed the build errors and it ran?
