### ISSUE TITLE
VS2017 Build  project Error

### ISSUE THREAD

**Issue by neckhyg** [dotnet/core#7477]
The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	MyApp	D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112

**Comment by mairaw** [comment]
Hi @neckhyg!
Not sure what the issue is here. Can you clarify?
You do need Visual Studio 2019 to use .NET Core 2.1.
