### ISSUE TITLE
Update from .NET 3.1 to .NET 6,Angular app not working as before

### ISSUE THREAD

**Issue by mrjohnr** [dotnet/core#7478]
Hi
I recently migrated an Angular 13 +.NET Core 3.1 app to .Net 6, I've changed target framework from 3.1 to 6, updated all packages to v6, no changes in code (front or back).

On Vps I've uninstalled net core hosting bundle 3.1 and installed v6+restart.

Since the upgrade very often,on first start,app remains in loading screen with no error in console,no request in network tab, If I reloaded it the works and I can see requests in network tab.

If I revert back to Net 3.1 and there is no problem.I have this issue since .NET 5

I don't know how to debug this problem,thanks for any clue

**Comment by michaelgsharp** [comment]
What specific version of .net 3.1 and .net 6 are you using?

Are you able to provide a simple repo?

**Comment by mrjohnr** [comment]
Hi
net 3.1.25
net 6.0.5

not easy to create a repo
I'll try updating the app from a new created project
thanks
