### ISSUE TITLE
Command prompt gives error

### ISSUE THREAD

**Issue by Mahesh8484956291** [dotnet/core#7479]
![Screenshot (59)](https://user-images.githubusercontent.com/106162898/170044558-0bee84e9-9ec4-4513-8183-ff37a51f20b1.png)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
This error message indicates that you already have a project on a folder called BlazorApp. Have you run the command twice? You should be able to just continue the tutorial if you already created the project.
