### ISSUE TITLE
How to use json

### ISSUE THREAD

**Issue by LGinC** [dotnet/core#748]
.net core 2.0 previewer 2
How can I parse a string to a json? I can't find the APIs.oh...Maybe I need find nuget packet.

**Comment by karelz** [comment]
Try [JSon.NET](https://www.nuget.org/packages/Newtonsoft.Json/) NuGet package. It is widely used. There is also built-in JSon API for certain specific scenarios.

**Comment by LGinC** [comment]
thank you
