### ISSUE TITLE
Webpage does not load

### ISSUE THREAD

**Issue by monicaaraujopasb** [dotnet/core#7486]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

---------
I am running the tutorial and everything was fine up to here:[
](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run)

Then, after I do the first step, it does not open the page as it said it would and I do not know the number of the port.
Could you help?

**Comment by mairaw** [comment]
Oi @monicaaraujopasb! Can you perhaps share a screenshot of what do you see in the console after you type `dotnet watch`?

You should be seeing something similar to this (I'm on Windows though):
![image](https://user-images.githubusercontent.com/12971179/170326158-4e33968e-6852-4b9a-8118-19e0b9ad151b.png)

So, the port is listed there on the UI. If you don't see that, you can find the port number by inspecting the launchSettings.json file under the Properties folder.
