### ISSUE TITLE
dotnet new crashes on anything

### ISSUE THREAD

**Issue by lever1209** [dotnet/core#7487]
```
dotnet new console -o MyApp -f net6.0
[1]    31308 bus error (core dumped)  dotnet new console -o MyApp -f net6.0
```
this is all that happens, no file is created, nothing is printed to stderr or stdout except the above codeblock

mono: Mono JIT compiler version 6.12.0 (makepkg/ed0788bf61f Sun Apr 24 04:25:18 PM UTC 2022)
mono package version: mono 6.12.0.177-1
dotnet version: 6.0.102
dotnet package versions:
```
dotnet-host 6.0.2.sdk102-1
dotnet-runtime 6.0.2.sdk102-1
dotnet-sdk 6.0.2.sdk102-1
dotnet-targeting-pack 6.0.2.sdk102-1
```
`uname -a`: Linux Viriditas 5.17.8-arch1-1 #1 SMP PREEMPT Mon, 16 May 2022 20:45:27 +0000 x86_64 GNU/Linux

**Comment by omajid** [comment]
cc @alucryd

**Comment by alucryd** [comment]
Will have a look on Friday, I need to update our package, but my automated build crashed so it seems some fixes are required as far as Arch is concerned.

**Comment by lever1209** [comment]
it seems to be working today?
i wish i had more information to give

**Comment by michaelgsharp** [comment]
Did you make any changes before it began working?

**Comment by lever1209** [comment]
i removed orphan packages and rebooted

**Comment by michaelgsharp** [comment]
Closing as issue is resolved.
