### ISSUE TITLE
what is the finalized release date for .NET core 2.0

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/core#749]
Hi,
I just see the date of release .NET core 2.0 as q3 and q3 has already started. Can we have the final date on which it will be released.

**Comment by richlander** [comment]
We haven't shared the date yet but it is still safely within Q3. We like to be conservative to allow for something going wrong w/o disappointing folks on a promised date.

If anyone is trying to coordinate product launches based on our schedule, _please_ reach out to me directly at rlander@ms and we can chat a bit more on the phone.

**Comment by VenkateshSrini** [comment]
@richlander ,
We are expecting a quite a few migration projects. if you could share me your email then I can drop you a note from live id.

**Comment by VenkateshSrini** [comment]
@richlander,

I see that as per this link https://www.youtube.com/watch?v=WfFbFhD4q6A the release is planned on September 18 to 20th. Are those the mile stone dates or will it be available before that

**Comment by Petermarcu** [comment]
The best option to discuss the details would be to take @richlander up on his offer to discuss via email as rlander at microsoft dot com.

**Comment by rdzidziguri** [comment]
guys the funny staff here is that just few hours ago NET Standard 2.0 was officially released, but it reqs VIS 2017.3 preview and will only work with NET CORE 2.0 which we still have no idea when MS is going to release so maybe MS will end up with something that google did with Angular when they skipped V3 and released V4? :) MS please sync staff. we are having hard time following all this distributed releases across .

**Comment by mguinness** [comment]
@rdzidziguri Most likely .NET Core 2.0 release will be announced September 19-21 at DEVintersection Europe.  [Save the date](http://www.dotnetconf.net/?utm_source=dotnet&utm_medium=web&utm_campaign=NETConfSaveDate) and follow .NET Conf.

**Comment by emiliano84** [comment]
@mguinness Why wait for more than a month if everything looks ready? hopefully they're waiting just for the RTM of VS 15.3 that hopefully will come before :)

**Comment by mguinness** [comment]
@emiliano84 LOL, they must've heard you, see [release notes](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0.md).

**Comment by rdzidziguri** [comment]
Ha ha guys they listened to us finally Microsoft started reading what users are writing and taking actions on that. Wow good surprise from MS.

**Comment by VenkateshSrini** [comment]
Since .NET core 2.0 .NET standard 2.0 are released. I'm closing this issue

**Comment by emiliano84** [comment]
@mguinness yeah I thought so... LOL
