### ISSUE TITLE
Update .NET 7 EOL

### ISSUE THREAD

**Issue by richlander** [dotnet/core#7491]
We can add an EOL date for .NET 7.

https://github.com/dotnet/core/blob/main/release-notes/releases-index.json#L12
https://github.com/dotnet/core/blob/main/release-notes/7.0/releases.json

It is already documented at https://github.com/dotnet/core/blob/main/releases.md.

@dcwhittaker @rbhanda

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/7492 - To resolve this issue

**Comment by rbhanda** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet - .NET 7.0 EOL is now updated. Closing this issue
