### ISSUE TITLE
dotnet command not found 

### ISSUE THREAD

**Issue by vishruthsk** [dotnet/core#7496]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos m1

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

zsh: command not found: dotnet error even though opened in a new terminal

**Comment by mairaw** [comment]
Did you install the Arm64 version of the SDK?
