### ISSUE TITLE
How to use Self-contained deployment with third-party dependencies, linux x64

### ISSUE THREAD

**Issue by LGinC** [dotnet/core#750]
How to write the csproj file?
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <RuntimeIdentifiers>win10-x64;osx.10.11-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
  </ItemGroup>
</Project>
```
what should I add to the RuntimeIdentifiers?   linux-x64? Ubuntu-14.04-x64?

**Comment by Petermarcu** [comment]
For .NET Core 1.X, you need to use the specific Linux identifier. Is Ubuntu 14.04 the target OS? If so, ubuntu.14.04-x64 is the identifier. You can see the full list of identifiers [here](https://github.com/dotnet/corefx/blob/release/1.1.0/pkg/Microsoft.NETCore.Platforms/runtime.json).

**Comment by LGinC** [comment]
@Petermarcu oh...For .NET Core 2.0 Previewer 2 .................................

**Comment by Petermarcu** [comment]
You need to be netcoreapp2.0 then in your TargetFramework. Make sure you have the 2.0 sdk installed and then you can use linux-x64.
