### ISSUE TITLE
setup faild

### ISSUE THREAD

**Issue by megose** [dotnet/core#7501]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/intro
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by megose** [comment]
the installation package not supported by processor type

**Comment by mairaw** [comment]
What was the error you got? What version of Windows are you running and what is the processor type? What version of the SDK did you try to install?

**Comment by megose** [comment]
Hello.
my proccesor is Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz   2.20 GHz.
 Win 10, 64-bit operating system, x64-based processor.
the SDK  version I tried to run is "dotnet-sdk-6.0.300-win-arm64". yes itried to install got message **"the installation package not supported by processor **type"
thanks

**Comment by CarnaViire** [comment]
Hi @megose, the SDK you were trying to install is for ARM64, but you have x64 processor. So you need to install "dotnet-sdk-6.0.300-win-**x64**", not "...-arm64"
