### ISSUE TITLE
How to change the code in Prgram.ps in dotnet?

### ISSUE THREAD

**Issue by aditid-2311** [dotnet/core#7507]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You can open the Program.cs in any kind of editor like Notepad, Vs Code, etc.

Does that help?
