### ISSUE TITLE
Asset\script\player.vs(6,22):errorCS1002:;expected 

### ISSUE THREAD

**Issue by Tifebethy** [dotnet/core#7508]
It showing Asset\script\player.vs(6,22):errorCS1002:;expected after writting the code

**Comment by mairaw** [comment]
What code? Can you give more information about your issue? maybe share the code you're trying to do?

**Comment by Tifebethy** [comment]
after writing the code on vs code  , i went to my unity and press the play
icon then it shows Assets\script\player.vs(6,22):errorCS1002:;expected
I really dont know what is wrong and how to go about it

**Comment by mairaw** [comment]
CS1002 means that you're missing a semicolon on your code. Do you want to share your code here so we can help?
