### ISSUE TITLE
aks cluster

### ISSUE THREAD

**Issue by mohamedshakal** [dotnet/core#7509]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I ran into issue when I'm trying to deploy a microservice to azure I entered the following command in VS code and also in the command prompt:
"az aks create --resource-group MyMicroserviceResources --name MyMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys"
then a message says:
"(BadRequest) The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/cpu-quota
Code: BadRequest
Message: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/cpu-quota"
finally I just wanted you to note that I tried to use another location as eastus2 and southafricanorth and the same message appeared, so I hope you help me with the solution

**Comment by michaelgsharp** [comment]
This seems to be something to do with your subscription itself. Is it still happening today? If it is, you will need to reach out to azure support directly for this.

**Comment by mohamedshakal** [comment]
thank you sir I will try to change my subscription plan
