### ISSUE TITLE
Cross-platform installer for desktop apps?

### ISSUE THREAD

**Issue by angelsix** [dotnet/core#751]
Once we have a .Net Core console application ready to deploy (so one that I will install into the users PATH so it can be called inside any command line, what is the "modern" best way to install it?

Now we are looking at cross-platform, Wix is not really the ideal option and that would only cover Windows. So... have you guys thought about and already solved this problem? I'm sure you have as dotnet core installs cross-platform and is under CI. 

I am wondering what you recommend for making a unified (or automated build) installer for an end user installing your application?

**Comment by Petermarcu** [comment]
You really have to create one for Windows, one for Osx and at least one for Linux depending on the distros. The only way we've found to try and get closer to a single one is to take a dependency on a cross platform scripting language and detecting the os, and delivering the right bits through it. Is your app all .net code? No native dependencies? Are you assuming something has already installed .net core and you are just trying to install the app on top?

**Comment by angelsix** [comment]
I have multiple apps but the one I'm thinking right now it's pure .Net Core

Ok so another question what installers does the .Net Core SDK use on each platform?

**Comment by Petermarcu** [comment]
We make zip's/tar.gz's available everywhere. On Windows we use Windows Installer, on OSX we use PKG's, and on Linux we use the distros package manger. You can see a good example of the offerings in this table. https://github.com/dotnet/core-setup/blob/master/README.md

**Comment by richlander** [comment]
Each operating system has its own way of doing things. AFAIK, there is nothing like what you want. Each of MSI, PKG and apt-get (for example) are very different from one another. No one set out to make a cross-platform desktop installer easy to build.

Closing this issue since this is well outside the scope of .NET Core and @Petermarcu has given good guidance.
