### ISSUE TITLE
Problem with code

### ISSUE THREAD

**Issue by BNB2022** [dotnet/core#7510]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

I followed the steps in until I opened Pages/Index.cshtml in notepad. I replaced the code with what was on the prompt. When I saved then checked the webapp page, everything is red. There are lines telling different error codes. I listed some of the codes below. 
Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected
error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
error CS1002: ; expected

**Comment by mairaw** [comment]
The error message seems to indicate that the Index.cshtml.cs file was edited instead. Can you try to start over perhaps and make sure you opened the cshtml page?
The code should look almost the same excepted for the highlighted lines.
