### ISSUE TITLE
Dockerfile doesn't see dotnet command

### ISSUE THREAD

**Issue by Sheidu** [dotnet/core#7511]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

When I create an image with "docker build -t services .", I see this message:
![image](https://user-images.githubusercontent.com/599930/171839847-4b6490a6-fc23-4646-b4b4-5313959e2624.png)

The dotnet command itself works just fine:

![image](https://user-images.githubusercontent.com/599930/171840164-a50b98f8-16a7-45dd-9368-afb59f1b85a7.png)

What should I do to resolve the issue?

**Comment by Sheidu** [comment]
Here is the Dockerfile:

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY Services.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Services.dll"]

**Comment by michaelgsharp** [comment]
The docker file looks fine, did you follow all the steps up till that point?

Are you still having that issue, oftentimes this issues resolve with a restart.

**Comment by Sheidu** [comment]
Yes, I am still having the issue after a PC restart.
Yes, I did all the steps before that point. 
I am not quite sure where the problem is, in incorrect install of Docker or SDK?
Btw, docker version is 20.10.14. I am using Windows 10.

Shall I reinstall either Docker or SDK?

**Comment by Sheidu** [comment]
![image](https://user-images.githubusercontent.com/599930/172609262-fdea41f2-b69b-4be1-885c-0f170bf955f6.png)

**Comment by Sheidu** [comment]
![image](https://user-images.githubusercontent.com/599930/172609432-59b69315-4dad-4b86-b83b-115fc719fd74.png)

**Comment by Sheidu** [comment]
Not sure if it helps but if I run a project via Visual Studio 2022 with the Docker option, the project builds fine, but VS shows this error:

![image](https://user-images.githubusercontent.com/599930/172919259-d8851228-0110-4040-9eaa-ecf87ef32333.png)

And the site cannot be reached.

**Comment by Sheidu** [comment]
I also have to folders with dotnet.exe:

C:\Program Files\dotnet
C:\Program Files (x86)\dotnet

If we look at the installed software, we will see x86 versions for some SDKs:
![image](https://user-images.githubusercontent.com/599930/172920605-67af88f7-2a21-4d3e-a1b7-73710e09cc49.png)

Shall I remove x86 versions?

**Comment by mairaw** [comment]
Can you check what `where.exe dotnet` returns? It might be an issue with PATH like described in https://github.com/dotnet/core/issues/5962

**Comment by Sheidu** [comment]
`where.exe dotnet` returns "C:\Program Files\dotnet\dotnet.exe":

![image](https://user-images.githubusercontent.com/599930/172923931-16d2d3a8-4e9c-44c2-8a79-06a8216870d5.png)


Actually, I removed all x86 software, but it didn't help.

**Comment by Sheidu** [comment]
Yes, everything looks fine to me:

![image](https://user-images.githubusercontent.com/599930/172992771-ab8a4f65-3cc1-49b9-9d41-90d212ab1f94.png)

**Comment by Sheidu** [comment]
So, any other options to try?

**Comment by Sheidu** [comment]
Anybody?

**Comment by CarnaViire** [comment]
@nishanil @MichaelSimons would you be able to take a look please?

**Comment by MichaelSimons** [comment]
All of the previous discussions checking where dotnet is installed are not applicable because you are looking on the host machine.  You need to be checking the state of the Docker container.  I would suggest simplifying the Dockerfile to the following:

``` dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY Services.csproj .
```

Then build this, run the resulting container and try running restore inside the container to reproduce the problem.

1. build - docker build -t test .
2. run interactively - docker run -it --rm test
3. reproduce the restore issue within the running container - dotnet restore
4. debug/inspect inside the running container

**Comment by Sheidu** [comment]
It seems the restoring finished fine, I didn't face any issue:
![image](https://user-images.githubusercontent.com/599930/174953325-67fd2778-1a58-4b36-88ee-ec18fdd8cae9.png)

Inspecting the container gives these:
![image](https://user-images.githubusercontent.com/599930/174953128-188917c6-5374-4cda-ac58-611e1d7e5033.png)
![image](https://user-images.githubusercontent.com/599930/174953162-27fd3b16-8092-45e8-af35-6a033812564b.png)

![image](https://user-images.githubusercontent.com/599930/174954236-2acce2cf-3477-4b04-9429-e03814c93b8c.png)

Should I look at anything particular inside the container?

**Comment by Sheidu** [comment]
I used the original Dockerfile and built it without any issue. So, it seems everything works fine now.

Thank you.

However, I wonder what was the reason of this. Also, I didn't do anything special the past week to resolve the issue.
