### ISSUE TITLE
sudo snap alias dotnet-sdk.dotnet dotnet

### ISSUE THREAD

**Issue by abitcons** [dotnet/core#7515]
I run a new console command as follows 
 dotnet new console -o myapp
I get the following error
Segmentation fault (core dumped)

While dotnet --info 
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /snap/dotnet-sdk/168/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/snap/dotnet-sdk/168/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/snap/dotnet-sdk/168/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/snap/dotnet-sdk/168/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
There seems to be some issues with snap. This comment from @kouvel should help: https://github.com/dotnet/runtime/issues/51322#issuecomment-890306629

**Comment by carlossanlop** [comment]
@abitcons hoping the provided answer helped you, so I'm closing this issue.
