### ISSUE TITLE
Problem installing dotnet

### ISSUE THREAD

**Issue by allen1147** [dotnet/core#7516]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
When I typed ~$ dotnet in terminal, I got an error saying not found

**Comment by mairaw** [comment]
Hi @allen1147. Are you on a M1 chip? If so, can you make sure you installed the Arm64 version?

**Comment by mairaw** [comment]
Tap on the Apple menu > select the ‘About This Mac’ > Look for ‘Processor’ or ‘Chip’ in the About This Mac window.

Here you can find the whole information: https://atozapplesilicon.com/how-to-check-if-your-mac-has-m1-chip/#:~:text=How%20to%20check%20if%20your%20Mac%20has%20an,about%20your%20Mac.%20Here%20you%E2%80%99ll%20see%20...%20

**Comment by allen1147** [comment]
This is what I see, I assume that I do not have the M1 chip.  

This is the content of my Index.cshtml file but there is also a subfile with a .cs extension. 

@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

< div class= "text-center" >
 
     < h1 > Hello, world! </ h1 >
    
        < p > The time on the server is @DateTime.Now</p>
</div>

FYI, I am a retired software developer since about 2013.  I used Visual Studio on Windows to develop ASP.net <http://asp.net/> applications but now want to do some personal programming using a mac.  Things have changed a lot. Can you recommend a good book or resource to brush up on the newer Visual Studio and the differences that I need to learn for developing on the Mac with VS? 

Thank you for your help.

I’m going to be away from the computer until late afternoon AZ time.

**Comment by mairaw** [comment]
If you have an attachment, they are not shown on GitHub when you reply via email.

The docs should be a good starting point for you to learn how to develop applications using VS for Mac
https://docs.microsoft.com/en-us/visualstudio/mac/?view=vsmac-2022&preserve-view=true

There's also this video series by @jongalloway 
https://www.youtube.com/playlist?list=PLdo4fOcmZ0oVcNUzk7c08KF1QxXzframc

Let us know how else we can help!

**Comment by jongalloway** [comment]
> Problem encountered on [dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install](https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install) Operating System: macos
> 
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. When I typed ~$ dotnet in terminal, I got an error saying not found

Also, if you're following this tutorial, you don't need to type the `~ $` part in the terminal. Just type `dotnet` at the terminal prompt.

Make sure you're following the macOS version of the tutorial here: https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install?initial-os=macos

There are two main ways to develop .NET on macOS - you can use Visual Studio 2022 for Mac using the link @mairaw listed, or you can use the command prompt and a lightweight editor like Visual Studio Code. While the command prompt is a little faster to get started, if you've got experience building ASP.NET on Windows with Visual Studio I would recommend using Visual Studio for Mac as it will feel more familiar to what you're used to.
