### ISSUE TITLE
ASP.NET Core 2.0 Preview not installed properly in Ubuntu 16.4 LTS

### ISSUE THREAD

**Issue by manikandanm1757** [dotnet/core#752]
# Packages missing error while installing ASP.NET Core 2.0 Preview in Ubuntu machine

I Have tried to install ASP.NET Core pre-release version of Core2.0. While installing I have facing an error with packages.
[Please refer the image link](https://ibb.co/jarZZa)

Please provide the details to overcome this issue

**Comment by svick** [comment]
The errors say that your machine failed to connect to several repositories. Are you sure the machine is properly connected to the internet?

**Comment by manikandanm1757** [comment]
Some of the links can be opened in the browser but failed to load in the terminal.

**Comment by LGinC** [comment]
@manikandanm1757 just try more times

**Comment by richlander** [comment]
Like @svick suggests, this doesn't seem specific to .NET Core. Sorry, but you need to figure out what is going on with your machine first and then we can look at specific .NET Core issues. Your situation is much broader.
