### ISSUE TITLE
Error at running the sample file, Solution is Run the command in this form "dotnet run Program.cs"

### ISSUE THREAD

**Issue by mnsp-github** [dotnet/core#7520]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Error_CShare_0001](https://user-images.githubusercontent.com/96757973/172204218-a9a27481-2e44-4020-814e-b1135804a227.PNG)

**Comment by mnsp-github** [comment]
thanks for the hint....
sport its typical programer mistake...
its working 'dotnet run'
thanks you for quick response 
Sent from Yahoo Mail on Android 
 
  On Mon, 6 Jun 2022 at 22:38, Maira ***@***.***> wrote:   


The screenshot shows there was a typo on the first command dontnet run instead of dotnet run.
Can you try again?

**Comment by mairaw** [comment]
No worries. I'm glad it's working!

It happens to all of us.
