### ISSUE TITLE
Error attempting to run hello world tutorial

### ISSUE THREAD

**Issue by allen1147** [dotnet/core#7521]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
When I saved the Pages/Index.cshtml  the following errors displayed on the home page
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(2,8): error CS1003: Syntax error, ',' expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(3,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(4,13): error CS1002: ; expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(4,14): error CS1001: Identifier expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(4,14): error CS1001: Identifier expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(4,23): error CS1525: Invalid expression term '='
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(5,1): error CS1022: Type or namespace definition, or end-of-file expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(5,2): error CS1525: Invalid expression term '<'
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,7): error CS1002: ; expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,12): error CS1001: Identifier expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,12): error CS1514: { expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,12): error CS1513: } expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,12): error CS8803: Top-level statements must precede namespace and type declarations.
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,12): error CS1525: Invalid expression term '='
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,29): error CS1525: Invalid expression term '<'
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,18): error CS1002: ; expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,18): error CS1022: Type or namespace definition, or end-of-file expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,28): error CS1525: Invalid expression term '/'
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,34): error CS1525: Invalid expression term '<'
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(11,19): error CS1002: ; expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(11,27): error CS1003: Syntax error, ',' expected
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(12,7): error CS1002: ; expected
/Users/awegele/MyWebApp/Program.cs(1,1): error CS8802: Only one compilation unit can have top-level statements.
Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Index_cshtml.g.cs(60,71): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?)
Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Index_cshtml.g.cs(62,81): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?)
Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Index_cshtml.g.cs(63,16): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?)
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(1,1): error CS0246: The type or namespace name 'page' could not be found (are you missing a using directive or an assembly reference?)
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(4,13): error CS7014: Attributes are not valid in this context.
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(7,3): error CS0103: The name 'div' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,8): error CS0103: The name 'h1' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,13): error CS0103: The name 'Hello' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,20): error CS0103: The name 'world' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(9,30): error CS0103: The name 'h1' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(11,11): error CS0103: The name 'p' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(11,15): error CS0103: The name 'The' does not exist in the current context
/Users/awegele/MyWebApp/Pages/Index.cshtml.cs(11,19): error CS0246: The type or namespace name 'time' could not be found (are you missing a using directive or an assembly reference?)
Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Index_cshtml.g.cs(62,171): error CS0246: The type or namespace name 'IndexModel' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mairaw** [comment]
Hi @allen1147! My guess is that you might have edited the .cs file instead of the .cshtml. Windows sometimes hides the file extension. Can you double check? You could start over to make sure.
