### ISSUE TITLE
.NET June 2022 Update - .NET 6.0.6, and .NET Core 3.1.26

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7536]
Release Notes
[6.0.6](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.6/6.0.6.md)
[3.1.26](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.26/3.1.26.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Distro | 6.0.6 | 3.1.26
-- | -- | -- 
Ubuntu 18.04 |✅ |✅
Ubuntu 20.04 |✅ |✅
Ubuntu 22.04 |✅ |
Centos 7 |✅ |✅
Debian 10 | |✅
Debian 11 | |✅
Fedora 34 | |✅
OpenSUSE 15|✅ |✅
Oracle|✅ |✅

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

Known Issues

If there are any more issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by petsuter** [comment]
Windows Update automatically installed this today and now builds fail: 
```
C:\Program Files\dotnet\sdk\5.0.408\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(125, 5): error NETSDK1145: The Apphost pack is not installed and NuGet package restore is not supported. Upgrade Visual Studio, remove global.json if it specifies a certain SDK version, and uninstall the newer SDK. For more options visit   https://aka.ms/targeting-apphost-pack-missing  Pack Type:Apphost, Pack directory: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64, targetframework: netcoreapp3.1, Pack PackageId: Microsoft.NETCore.App.Host.win-x64, Pack Package Version: 3.1.25
```

**Comment by loop-evgeny** [comment]
https://github.com/dotnet/sdk/issues/26026 is quite the nasty breaking change: all our TeamCity builds failed (and the workaround of [updating the .NET plugin](https://github.com/JetBrains/teamcity-dotnet-plugin/issues/158#issuecomment-1157370284) was not enough in our case).

**Comment by kevgeni** [comment]
Hello, like @devritter, we had an issue with our software using runtime 6.0.6 and alpine linux 3.16. 
We were using docker label "mcr.microsoft.com/dotnet/aspnet:6.0-alpine"
and reverted to "mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.15" supported until 2023-11. 

Looking at our builds, it appears that asp.net runtime 6.0.5 with alpine 3.16 worked correctly, but 6.0.6 with alpine 3.16 caused issue. I am unsure what is the underlying bug. We're using aspnetboilerplate as the framework. The translations system would not work anymore.

**Comment by dcwhittaker** [comment]
Adding @danmoseley @wfurt for visibility, who may also have a perspective on any actions to take.

**Comment by kevgeni** [comment]
Installing alpine linux "icu-data-full" package fix our translation problem on image mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.16. Without this, english translation would work but not other language. 
It's probably not your problem, but I was looking for bugs in aspnetboilerplate, asp.net and .netcore and found this one with a comment from devritter and so I added on top of it. 
Maybe it's a documentation on your side, on aspnetboilerplate side, on alpinelinux, not sure.

**Comment by wfurt** [comment]
I think we should add the package to our base image so everything just works. cc: @richlander

**Comment by richlander** [comment]
We fixed that Alpine + icu issue already, in the SDK images. 

We never installed ICU at all in the runtime images. You are free to install it.

Context: https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/6.0/alpine3.16/arm32v7/Dockerfile#L19-L20

You can unset that ENV and then install ICU in your app layer.

Make sense?

@mthalman

**Comment by kevgeni** [comment]
@richlander yes/no. I see that DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is set in the base image of asp.net and runtime for amd64 alpine, but regardless I still needed to install the ICU. Perhaps it was a requirement of the underlying stack (aspnetboilerplate) that we use. I checked your link and could not find where it's set for alpine for amd64, but it's still set in the image so it must be hidden somewhere.

**Comment by richlander** [comment]
Nothing is hidden. It's all open.

This is what you are looking for: https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/3.1/alpine3.16/amd64/Dockerfile#L20

I know it says "3.1".

Can you share some code that previously worked and now doesn't? Can you also share your Dockerfile? If it's closed-source, you can send it to dotnet@microsoft.com.

**Comment by richlander** [comment]
I asked for help. Do you see this outside of Azure DevOps?

**Comment by danmoseley** [comment]
> Looks like it's associated with the 20220619.1 version of the Ubuntu 20.04 image,

Perhaps worth asking on the Ubuntu forums? They should be able to suggest what changed in that build. Perhaps there's a workaround/known issue.

**Comment by dcwhittaker** [comment]
Closed in favor of https://github.com/dotnet/core/issues/7596
