### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by solitudeX12** [dotnet/core#7547]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 10
#7296   #4026
#7091

**Comment by solitudeX12** [comment]
It's taking time for the link to load and for the browser to open

**Comment by CarnaViire** [comment]
Hi @solitudeX12 Could you please describe the problem in more details? Do you see any error/exception, or does it work, but takes a lot of time?
