### ISSUE TITLE
Multiple errors compiling with SDK 2.0

### ISSUE THREAD

**Issue by DavoBR** [dotnet/core#755]
i am trying to deploy my project to azure website, using deployments options with bitbucket 

this is the log output of "Running deployment command..." task.

[log.txt](https://github.com/dotnet/core/files/1156057/log.txt)

i think that is about azure is using sdk 2.0 but the project need sdk 1.1

**Comment by svick** [comment]
> Could not locate the assembly Microsoft.AspNetCore.Authentication

I think this could happen if you didn't run `dotnet restore` before building the project. How exactly are you deploying your project? And can you share your csproj file?

**Comment by DavoBR** [comment]
there it is

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">

  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId>aspnet-CorePanel-f4d80286-a681-45fd-b535-74b3f2b9f604</UserSecretsId>
  </PropertyGroup>

 
  
  <ItemGroup>
    <PackageReference Include="Braintree" Version="3.7.0" />
    <PackageReference Include="BundlerMinifier.Core" Version="2.4.337" />
    <PackageReference Include="EntityFramework" Version="6.1.3" />
    <PackageReference Include="EntityFramework.Extended" Version="6.1.0.168" />
    <PackageReference Include="EntityFramework.Extended.Async" Version="6.1.1" />
    <PackageReference Include="GoogleAuthenticator" Version="1.2.1" />
    <PackageReference Include="Mandrill" Version="2.4.181" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
    <PackageReference Include="RazorEngine" Version="3.9.3" />
    <PackageReference Include="Twilio" Version="5.4.1" />
    <PackageReference Include="Twilio.AspNet.Mvc" Version="5.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CorePanel.Core\CorePanel.Core.csproj" />
    <ProjectReference Include="..\CorePanel.Data\CorePanel.Data.csproj" />
    <ProjectReference Include="..\CorePanel.Services\CorePanel.Services.csproj" />
  </ItemGroup>
</Project>`

**Comment by Petermarcu** [comment]
Is this still an issue?

**Comment by Petermarcu** [comment]
I'm going to close this issue for now. Please let us know if you still hit this issue and we can re-open.
