### ISSUE TITLE
.NET download

### ISSUE THREAD

**Issue by JuanMenddes** [dotnet/core#7555]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
If i download it it appears in downloads but i have to repair it but it still does not work.

**Comment by adamsitnik** [comment]
Hello @JuanMenddes 

Could you please try to download the file again?

Is there any chance you could provide a screen shot with exact error message?

Thanks!
