### ISSUE TITLE
khắc phục lỗi cập nhật

### ISSUE THREAD

**Issue by bachkim10** [dotnet/core#7560]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @bachkim10 

Could you please provide the details about the problem you are experiencing?
