### ISSUE TITLE
found a weird error

### ISSUE THREAD

**Issue by Ruben19470** [dotnet/core#7563]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
whenever i  try running a dotnet  command i always get this error: 
It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by adamsitnik** [comment]
Hi @Ruben19470, can you paste the output of running the command `where.exe dotnet`?

If your system is x64 and the output returns the following:
C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

You might be able to fix that as explained here: https://github.com/dotnet/core/issues/5962#issuecomment-780084535
