### ISSUE TITLE
Unable to resolve 'AspNetCore.Reporting (>= 2.1.0)' for 'net5.0'.

### ISSUE THREAD

**Issue by bassent** [dotnet/core#7564]
Building...
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'AspNetCore.Reporting (>= 2.1.0)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'AspNetCore.ReportViewer (>= 3.0.0.200103)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Bold.Licensing (>= 3.2.27)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'BoldReports.AspNet.Core (>= 3.1.46)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'BoldReports.Net.Core (>= 3.1.46)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Authentication.JwtBearer (>= 5.0.0)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Authentication.OpenIdConnect (>= 5.0.0)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Http (>= 2.2.2)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Mvc.NewtonsoftJson (>= 5.0.0)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'ReportViewerCore.NETCore (>= 15.1.14)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'RestSharp (>= 105.2.3)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 5.6.3)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'Dapper (>= 2.0.35)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'System.CodeDom (>= 5.0.0)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'System.Data.SqlClient (>= 4.8.2)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'System.Runtime.Caching (>= 5.0.0)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'System.ServiceModel.Http (>= 4.8.1)' for 'net5.0'.
D:\ERP.CORE\API\API.csproj : error NU1100: Unable to resolve 'System.ServiceModel.Primitives (>= 4.8.1)' for 'net5.0'.

The build failed. Fix the build errors and run again.

dotnet watch ❌ Exited with error code 1
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

**Comment by adamsitnik** [comment]
Hi @bassent 

I've looked at some of the dependencies from your list and it _should_ just work. I suspect that it was a temporary network issue. Could you please run `dotnet restore` again and see if it works?

```cmd
cd D:\ERP.CORE\API\
dotnet restore
```


If it does not help, could you please paste `PackageReference` xml tags from your project file (`.csproj`) here so I can run it myself?
