### ISSUE TITLE
I can't put dotnet on my computer

### ISSUE THREAD

**Issue by vabrvap** [dotnet/core#7571]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

    i was installing dotnet on my notebook but in the "edit your code" step of the tutorial where it said "Open the Program.c file in any text or code editor such as Notepad or Visual Studio Code. The Program .cfile is located in the newly created MyAppdirectory.
Then add the highlighted line after the code that prints "Hello, World!", like the following:", I possibly didn't understand what I was supposed to do, and when I try to do that part I can't

I did everything I thought I was supposed to do but I couldn't.
![erro no dotnet](https://user-images.githubusercontent.com/108376109/176325581-9cd89938-bc15-43d8-932e-56fe8df3c3c8.PNG)

**Comment by mairaw** [comment]
Talvez vc tenha rodado o comando `dotnet new` mais de uma vez em diretórios diferentes, então quando `dotnet run` vai executar, ele encontra dois arquivos csproj.

Os comandos Console.WriteLine não são para serem digitados no command prompt. Você tem que abrir o arquivo Program.cs num editor e acrescentar a nova linha.
