### ISSUE TITLE
Expose a common SystemClock and ISystemClock

### ISSUE THREAD

**Issue by rsr-maersk** [dotnet/core#7575]
Hi. 

Multiple MS dotnet libs have their own SystemClock and ISystemClock.
Most projects also have their own SystemClock and ISystemClock as we don't want to user the DateTime.Now or DateTime.UtcNow in code, as it is not testable..

Hence MS also has multiple implementations of the same thing:
![image](https://user-images.githubusercontent.com/76153851/177110910-3614b151-a9fb-4414-b8f5-a450c225124a.png)

Instead of every man and his dog making a SystemClock and ISystemClock, can you not just put into System? and also auto register with the DI? Its "just" a wrapper for DateTime.Xyz, but still, why should we all make the same class/interface/wrapper? I am sure you can "just" copy paste code and tests from the best candidate.

I see that Microsoft.Extensions.Internal has a public ISystemClock, but "Microsoft.Extensions.**Internal**" seams to be the wrong namespace. Also maybe more should be wrapped. Now, Today, and other nice ones.

Thanks for considering. Cya.

**Comment by adamsitnik** [comment]
Hello @rsr-maersk 

We have already received such request: https://github.com/dotnet/runtime/issues/36617

Please follow the referenced discussion for details and updates.

Thanks!

**Comment by rsr-maersk** [comment]
Thanks @adamsitnik, i tried searching for it, but it didn't pop up. Sorry for the trouble.
