### ISSUE TITLE
.NET installation issue

### ISSUE THREAD

**Issue by Tiham69** [dotnet/core#7577]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @Tiham69 

Could you please describe the problem you are experiencing?

**Comment by Tiham69** [comment]
Thank you for your response Adam Sitnik. I was having issue with the
command Terminal that dotnet was not running but it was solved by me
smashing keyboard. And thank you again for your response though.
