### ISSUE TITLE
Ubuntu 21.10 reaches end of life on Jul 14, 2022

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#7578]
[Ubuntu 21.10 reaches end of life on July 14, 2022](https://lists.ubuntu.com/archives/ubuntu-announce/2022-May/000280.html)
This issue is created to track progress for the remove support for Ubuntu 21.10 from .NET Core 3.1 and .NET 6.0

### Repos team to update:

- [ ] Remove installers for the outdated distro
- [ ]  Remove build support
- [ ]  Remove test assets

### Infrastructure Team Accountabilities/Deliverables:

- [ ]  Notification to NetCore Engineering Partners
- [ ]  Remove the outdated version from the hardware pool 

### Release Team

- [x]  Send Notification to every team in .NET for upcoming addition
- [ ]  Supported OS content gets updated on GitHub and marketing sites. 
- [ ]  Update release manifest files. 
- [ ]  Docker files which are used for install testing needs to be updated. 

### Document updates:
- [ ] Add/Remove OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by ashnaga** [comment]
Resolving this one
