### ISSUE TITLE
.net 6.0.6 release notes link has preview in the name

### ISSUE THREAD

**Issue by grantborthwick** [dotnet/core#7579]
Looking at https://github.com/dotnet/core/releases/tag/v6.0.6

The release notes link links to https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.6.md whereas it should link to https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.6/6.0.6.md.

**Comment by mairaw** [comment]
Thanks for reporting this issue @grantborthwick. I have fixed the broken link.
