### ISSUE TITLE
Assembly specified not found when running self-contained console application

### ISSUE THREAD

**Issue by mattcanty** [dotnet/core#759]
# General

- **.Net Core Version** netcoreapp1.1
- **Runtime Identifier** win81-x64
- **Target Operating System** Windows Server 2012 R2

# Code
## Program.cs
```
using System;

namespace MyProject
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```
## MyProject.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <RuntimeIdentifiers>win81-x64</RuntimeIdentifiers>
  </PropertyGroup>

</Project>
```

# Steps
1. `dotnet restore`
2. `dotnet publish -c release -r win81-x64`
3. Copy contents of _.\bin\Release\netcoreapp1.1\win81-x64_ to server (Windows Server 2012 R2)
3. On server execute `MyProject.exe` using PowerShell

# Result
```
PS ~\Desktop\win81-x64> .\MyProject.exe
Error: assembly specified in the dependencies manifest was not found -- package: 'microsoft.codeanalysis.common', version: '1.3.0', path: 'lib/netstandard1.3/Microsoft.CodeAnalysis.dll'
```

**Comment by mattcanty** [comment]
Wow. That must be a record for the time taken to resolve an issue myself after raising an issue. I've been looking at this for several hours. But just glanced at the _.\publish_ directory and saw _MyProject.exe_ in there.

Needless to say. The resolution is to either:

1. Execute `.\publish\MyProject.exe` on the server.

or 

2. Publish the _publish_ folder.

I would like to point out that the _publish_ folder is not present in _.\bin\**Debug**\..._ which is why this probably took me a lot longer to get to the bottom of than I'd like.

**Comment by Petermarcu** [comment]
Yes, discovery of where the published output goes has been a but of a pain point.

**Comment by Doggie52** [comment]
What's most confusing is that executable files appear outside of the `publish` folder, so you're led to believe those are the ones you need to run and that `publish` simply contains the libraries. I don't quite see why anything executable should appear outside of `publish` if `dotnet publish` has been invoked...
