### ISSUE TITLE
zsh: permission denied: dotnet

### ISSUE THREAD

**Issue by davephz** [dotnet/core#7590]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Hi, I'm trying to install dotnet on MacOS for C# projects but after installing, I tried to check to see if it has been successfully installed by typing dotnet in terminal but somehow I'm getting: 

**zsh: permission denied: dotnet**

Any help would be much appreciated thanks

**Comment by mairaw** [comment]
Apologies for not replying sooner. If you still need assistance, please let us know.
