### ISSUE TITLE
i just installed the .NET 6.0 and follow the tutorial then this happened 

### ISSUE THREAD

**Issue by QuangLongVSC** [dotnet/core#7594]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

C:\Users\Admin>dotnet new console
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\Admin\Admin.csproj...
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.

C:\Users\Admin>dotnet run
C:\Users\Admin\AppData\Roaming\Code\User\History\4b58c0bd\6uFZ.cs(3,1): error CS0106: The modifier 'public' is not vali
d for this item [C:\Users\Admin\Admin.csproj]
C:\Users\Admin\AppData\Roaming\Code\User\History\4b58c0bd\krlp.cs(3,11): error CS1001: Identifier expected [C:\Users\Ad
min\Admin.csproj]
C:\Users\Admin\AppData\Roaming\Code\User\History\4b58c0bd\krlp.cs(3,11): error CS1514: { expected [C:\Users\Admin\Admin
.csproj]
C:\Users\Admin\AppData\Roaming\Code\User\History\4b58c0bd\krlp.cs(3,11): error CS1513: } expected [C:\Users\Admin\Admin
.csproj]
C:\Users\Admin\AppData\Roaming\Code\User\History\4b58c0bd\9ZoV.cs(3,1): error CS0106: The modifier 'public' is not vali
d for this item [C:\Users\Admin\Admin.csproj]

The build failed. Fix the build errors and run again.

C:\Users\Admin>

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmoseley** [comment]
Does it work if you create a new folder and put it in there?

**Comment by QuangLongVSC** [comment]
thanks it worked

**Comment by QuangLongVSC** [comment]
but how to run many or different cs files

**Comment by danmoseley** [comment]
@QuangLongVSC in .NET, you don't run a .cs file -- you run a project. The project includes one or more .cs files.

By default, the project file (.csproj) automatically includes all .cs files in its folder. So in .NET, we generally put separate projects in separate folders. (There are ways to include .cs files into more than one project if you need to)

Does that help?
