### ISSUE TITLE
.NET July 2022 Updates - .NET 6.0.7, .NET Core 3.1.27

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7596]
Release Notes
[6.0.7](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.7/6.0.7.md)
[3.1.27](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.27/3.1.27.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Distro | 6.0.7 | 3.1.27
-- | -- | -- 
Ubuntu 18.04 |✅ |✅
Ubuntu 20.04 |✅ |✅
Ubuntu 22.04 |✅ |
Centos 7 |✅ |✅
Debian 10 |✅ |✅
Debian 11 |✅ |✅
Fedora 35 |✅ | ✅
Fedora 36| | ✅
OpenSUSE 15|✅ |✅
Oracle|✅ |✅

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

Known Issues

- [✅] ~~Experiencing a delay with creating tags for releases in servicing and preview. Anticipate this issue to be resolved by 5pm PDT.~~ [**All tags for both servicing and preview releases have been created as of 4:30pm PDT**]

If there are any more issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by xtqqczze** [comment]
Issue opened for Fedora 36 support: #7676.

**Comment by dcwhittaker** [comment]
Closed in favor of https://github.com/dotnet/core/issues/7682
