### ISSUE TITLE
Visual Studio and .NET Core 2 Preview

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/core#760]
I have installed the .NET Core 2 Preview SDK and Runtime. When I open Visual Studio, I don't see an option to select the preview as the framework type.

Any ideas?
David

**Comment by richlander** [comment]
Are you using Visual Studio 2017 15.3 Preview? 

Link here: https://blogs.msdn.microsoft.com/dotnet/2017/06/28/announcing-net-core-2-0-preview-2/

**Comment by RealDotNetDave** [comment]
No, did not realize that was the only version it worked in. I'll check it out.

**Comment by Petermarcu** [comment]
Going to assume this is resolved. Closing now.
