### ISSUE TITLE
Nullable Reference Types Create Problems in Online IDEs

### ISSUE THREAD

**Issue by toviyahu** [dotnet/core#7606]
### Description

 warning CS8625: Cannot convert null literal to non-nullable reference type. 
I am in an online IDE that I do not have control over.  I am not able to add to the class the ? to fix this error, nor am I able to re-write the class.  Also, I have tried adding the  #nullable disable and this does nothing to correct this error.  According to Microsoft using  #nullable disable should allow me to be able to use null references.  I need to have null references.  This makes using C#, which is my preferred language nearly impossible to use for coding assessments.  Is there any way to make the default <Nullable>disable</Nullable> so that we can use C#?

  

### Configuration

* Which version of .NET is the code running on?
* .NET 6 SDK Version: 6.0.100
* What OS and version, and for Linux, what distro?
* Online
* What is the architecture (x64, x86, ARM, ARM64)?
* Online 
* Do you know whether it is specific to that configuration?
* If you're using Blazor, which web browser(s) do you see this issue in?
  

### Regression?

* Did this work in a previous build or release of .NET, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
I don't know as it does not belong to me.
  

### Other information

* Please include any relevant stack traces or error messages. If possible please include text as text rather than images (so it shows up in searches).
 warning CS8625: Cannot convert null literal to non-nullable reference type.
* If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
XML: `<Nullable>enable</Nullable>`
* Do you know of any workarounds?
 #nullable disable (But it does not work)

**Comment by eiriktsarpalis** [comment]
> warning CS8625: Cannot convert null literal to non-nullable reference type.
> I am not able to add to the class the ? to fix this error, nor am I able to re-write the class.

It should be possible to suppress the warning using the [null-forgiving operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving) at the end of your null expression. That being said, this invalidates the purpose non-nullable reference types so if this is happening pervasively, I would recommend simply disabling the feature project-wide using `<Nullable>disable</Nullable>`.
