### ISSUE TITLE
PK5

### ISSUE THREAD

**Issue by Ted-Jones701** [dotnet/core#7609]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Microsoft Windows [Version 10.0.19041.1]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\flami>dot net
'dot' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\flami>dot net
'dot' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\flami>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\flami>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\flami>

**Comment by eiriktsarpalis** [comment]
Have you tried installing the .NET SDK on your machine?

https://dotnet.microsoft.com/en-us/download

cc @mairaw
