### ISSUE TITLE
Ned help

### ISSUE THREAD

**Issue by samardack** [dotnet/core#7611]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by eiriktsarpalis** [comment]
Hi, could you provide more details on the error you are experiencing?

**Comment by samardack** [comment]
Спасибо за желание помочь 👍 Уже забил на это 😉

**Comment by mairaw** [comment]
Seems like issue was resolved. Closing.

**Comment by samardack** [comment]
Да снес виндовс 😉 Поставил другую🤣
