### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jalilakhtar** [dotnet/core#7612]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 10, sdks installed 2.0, 3.0, & 6.0.
Created console app by running:
>dotnet new console -o MyApp -f net6.0
>cd .\MyApp
>dotnet run
which is creating errors:
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\myWebApp.RazorAssemblyInfo.cs(10,22): error CS0234: The type or n
amespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Use
rs\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\myWebApp.RazorAssemblyInfo.cs(11,22): error CS0234: The type or n
amespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Use
rs\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\myWebApp.RazorAssemblyInfo.cs(12,22): error CS0234: The type or n
amespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Use
rs\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\myWebApp.RazorAssemblyInfo.cs(13,22): error CS0234: The type or n
amespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Use
rs\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\myWebApp.RazorTargetAssemblyInfo.cs(10,22): error CS0234: The typ
e or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [
C:\Users\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\Razor\Pages\Error.cshtml.g.cs(4,30): error CS0234: The type or na
mespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\User
s\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\Razor\Pages\Index.cshtml.g.cs(4,30): error CS0234: The type or na
mespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\User
s\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\Razor\Pages\Privacy.cshtml.g.cs(4,30): error CS0234: The type or
namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Us
ers\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\Razor\Pages\Shared\_CookieConsentPartial.cshtml.g.cs(4,30): error
 CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assemb
ly reference?) [C:\Users\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\Razor\Pages\Shared\_Layout.cshtml.g.cs(4,30): error CS0234: The t
ype or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
 [C:\Users\admin\myApp\myApp.csproj]
C:\Users\admin\myApp\myWebApp\obj\Debug\netcoreapp3.0\Razor\Pages\Shared\_ValidationScriptsPartial.cshtml.g.cs(4,30): e
rror CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an as
sembly reference?) [C:\Users\admin\myApp\myApp.csproj]

**Comment by mairaw** [comment]
The error message is pointing out that maybe there's an old ASP.NET Core 3.0 app inside the same folder?
Maybe create a brand new project on a different location to make sure.
