### ISSUE TITLE
I just want obs to show my chat over gameplay so I can read more conveniently. I dont know about all this 

### ISSUE THREAD

**Issue by AbsoluteLunaC** [dotnet/core#7613]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant
![Screenshot 2022-07-17 173357](https://user-images.githubusercontent.com/109490136/179431220-c8122d4b-37f8-49e4-a345-518b930078bc.jpg)
.

**Comment by mairaw** [comment]
I've seen this error occur before when people ran the `dotnet new` command twice, one being inside the `MyApp` directory, creating the project two times in different folder levels. Make sure that didn't occur.
You should be able to just delete everything and start over again. Let us know if this helps.
