### ISSUE TITLE
bash: ./dotnet.sh: No such file or directory

### ISSUE THREAD

**Issue by monstercatss** [dotnet/core#7616]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/install
Operating System: linux

![image](https://user-images.githubusercontent.com/45393763/179642333-f16fe2f2-074b-4b88-a5f5-1f1da87019b4.png)
![image](https://user-images.githubusercontent.com/45393763/179642378-971321fd-02ce-4186-aee8-7b4dd224b953.png)

root@ubuntu:/home/magus/runtime/Myapp# ./dotnet.sh run
bash: ./dotnet.sh: No such file or directory

**Comment by mairaw** [comment]
Have you tried running `dotnet run` as in the tutorial? Do you get the same error message?

This doc might help you troubleshoot some issues as well:
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-linux
