### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by grazikgafriginal** [dotnet/core#7619]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Macos,

/Users/grazik.gafriginal/MyApp/MyApp/Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [/Users/grazik.gafriginal/MyApp/MyApp/MyApp.csproj]

The build failed. Fix the build errors and run again.

grazik.gafriginal@Kazimirs-Air MyApp % dotnet run

**Comment by mairaw** [comment]
I usually see this error when folks run the `dotnet new` command in different folders creating a new project in the subfolder. Can you make sure you only have one project inside the directory you're trying to run?
The other option would be to delete the folder and start over.
