### ISSUE TITLE
Blazor tutorial from the welcome screen

### ISSUE THREAD

**Issue by HappyMark93** [dotnet/core#7620]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows

No welcome screen, no tutorial. I am using VS already, how to get to tutorial?

![image](https://user-images.githubusercontent.com/106931590/179833326-b606230c-b138-42df-8387-876c700577fc.png)

**Comment by mairaw** [comment]
Did you download the Visual Studio 2022 Preview version using the link from the tutorial? 

/cc @danroth27

**Comment by danroth27** [comment]
@HappyMark93 To see the integrated Blazor tutorial in VS you need to install VS Preview using this link: https://aka.ms/blazor-vs-install. Also there was a brief outage with the Welcome page and tutorial, but that should be addressed now. If you still don't see the tutorial you can always just follow the Blazor tutorial on the .NET website.
