### ISSUE TITLE
Windows Update keeps installing .NET 5 after I uninstall it.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/core#7624]
Every time I try to uninstall .NET 5 from my machine and check for updates, I get greeted by this:

![image](https://user-images.githubusercontent.com/12659251/180190833-c1d9119b-a33c-4a0e-8385-6fa920e04830.png)

Somehow Windows Update still thinks I have .NET 5 and needs to update it.

My OS is Windows 10 19044.1826. I also have Visual Studio Community 2022 in my machine, _without_ .NET 5 SDK checked.

**Comment by Spinarooni** [comment]
Same issue here.  WIndows Updates for .NET/.NET Core are just a mess.  I constantly have issues with failed updates:

![image](https://user-images.githubusercontent.com/331866/180240520-c0ad10b3-0b0c-4abb-906c-0156d6a625ff.png)

I don't have .NET 5 installed and .NET Core 3.1 is at 3.1.27 yet it keeps trying to apply the 3.1.26 security update.

**Comment by rbhanda** [comment]
Adding @joeloff and @csnellgrove1-zz who can help here

**Comment by joeloff** [comment]
Please run `Get-WindowsUpdateLog` from Powershell as well as the [.NET log collection tool](https://www.microsoft.com/en-ca/download/details.aspx?id=12493).

**Comment by teo-tsirpanis** [comment]
Done. Is it safe to publicly share them?

**Comment by joeloff** [comment]
the update logs should be fine. The .NET log zip not so much.

**Comment by teo-tsirpanis** [comment]
Here is [WindowsUpdate.log](https://github.com/dotnet/core/files/9163406/WindowsUpdate.log). I can send you the other via email.

**Comment by joeloff** [comment]
So the update specifically is offering the 5.0.408 SDK. The .NET logs zip file should help answer questions about everything that's installed. The offering would happen if it detects any of the previous 5.0.400 through 5.0.407 SDKs.

**Comment by teo-tsirpanis** [comment]
@joeloff can you give me your email address so that I can send the .NET logs to you?

**Comment by teo-tsirpanis** [comment]
After @joeloff's valuable assistance over email (big thanks!), the problem was solved.

Turned out that remnants of the 5.0.401 SDK were still on my machine, and WU offered to update it to 5.0.408, but 401 was not getting removed. After installing 401 myself and inspecting the uninstallation logs, I saw that it could not be uninstalled because `Found dependent: VS.{AEF703B8-D2CC-4343-915C-F54A30B90937}, name: Unknown`, just like #4878 and dotnet/aspnetcore#40955. Is that Visual Studio? Its name could be made more informative, or even the installer UI could show some messages that not everything was removed.

401 was forcefully uninstalled using the `msiexec` command and after that Windows Update was no longer installing .NET 5.

**Comment by joeloff** [comment]
> After @joeloff's valuable assistance over email (big thanks!), the problem was solved.
> 
> Turned out that remnants of the 5.0.401 SDK were still on my machine, and WU offered to update it to 5.0.408, but 401 was not getting removed. After installing 401 myself and inspecting the uninstallation logs, I saw that it could not be uninstalled because `Found dependent: VS.{AEF703B8-D2CC-4343-915C-F54A30B90937}, name: Unknown`, just like #4878 and [dotnet/aspnetcore#40955](https://github.com/dotnet/aspnetcore/issues/40955). Is that Visual Studio? Its name could be made more informative, or even the installer UI could show some messages that not everything was removed.
> 
> 401 was forcefully uninstalled using the `msiexec` command and after that Windows Update was no longer installing .NET 5.

Glad I could help. You are correct. The VS.{xxxx} value is used to reference count MSIs against one or more instance of Visual Studio. When the Visual Studio installer sees this dependent, it look at the catalog files of each instance to determine which instance(s) reference the MSI. IOf VS updated, but the dependent value was not removed, the new versions will not resolve the installer because they no longer exist in the new VS catalogs.

There is UI that pops up if you try to uninstall an MSI with remaining dependencies, but bundles (EXE installers) suppress the MSI UI and having multiple references isn't necessarily an error, though in this case there obviously was something that caused removing it to fail.
