### ISSUE TITLE
Build Settings--- Save? 

### ISSUE THREAD

**Issue by Kalennienna** [dotnet/core#7628]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/run
Operating System: windows

Doing the Build Settings: clicked Add Open Scenes Selected Windows Platform. Clicked Build And Run.

The tutorial says that if it was a success, the application will start running. For me, a popup came up that wants me to select a folder to save this into.....? What do I do?
![scrrenshot](https://user-images.githubusercontent.com/108205283/180628211-f7c1ac5d-6271-4200-99b9-0a051afbc1d8.JPG)

**Comment by mairaw** [comment]
Do you still need help with this issue @Kalennienna?
