### ISSUE TITLE
not able to start

### ISSUE THREAD

**Issue by diva1955** [dotnet/core#7630]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

I am not getting the output "hello World" after running the code. the screen shot is attached

![Screenshot (496)](https://user-images.githubusercontent.com/109861647/180761699-bf02ac5d-be3c-43a0-96f1-5f557d376076.png)
![Screenshot (496)](https://user-images.githubusercontent.com/109861647/180761827-528a6a39-21df-407c-9dc0-50f49fa042d1.png)

**Comment by mairaw** [comment]
If you run the command outside of VS Code, do you get the same error? Also, can you paste the error message here? The output is cut on the screenshot.

**Comment by diva1955** [comment]
Screenshot attached

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mairaw** [comment]
GitHub doesn't allow attachments via email responses. Unfortunately, you have to use their website to upload a file.
