### ISSUE TITLE
Issue with .Net 6 SDK - Failed - Network error for Downloading files

### ISSUE THREAD

**Issue by vbukhari-twn** [dotnet/core#7631]
After upgrading to .Net 6 SDK, we are having issues with downloading files. 
**Failed - Network Error  show.** 
This issue is through out different environment of our application. Issue is reproduceable in different browsers as well.  I have tried chrome, Firefox, and MS edge.
I already verified, It's not relate to browser or internet issues 

![image](https://user-images.githubusercontent.com/109978055/180825199-64ea1266-1e9f-48d9-9beb-991f39aa489f.png)

**Comment by buyaa-n** [comment]
@vbukhari-twn we need more info like what exception you are seeing in the backend, the front end error you provided could be just issue within your application. Further it would be great if you could provide sample repro application that we could investigate

**Comment by akoken** [comment]
@vbukhari-twn Where do you try it? Work or home? Maybe it's related to your corporate proxy.
