### ISSUE TITLE
Saved changes in Index.cshtml.cs

### ISSUE THREAD

**Issue by 1sermin** [dotnet/core#7642]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I copied below in the wrong Index.cshtml. I copied and saved into Index.cshtml.cs. Now the dotnet watch gives several errors, please see attached file.
[dotnet error.txt](https://github.com/dotnet/core/files/9214325/dotnet.error.txt)

@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>

OS: Microsoft Windows 10 Home

Thanks!

**Comment by mairaw** [comment]
There are two files: Index.cshtml and Index.cshtml.cs. You mentioned you saved the changes to the cs file, but the tutorial instructs to make the changes to the cshtml one. Maybe delete and start over?

**Comment by 1sermin** [comment]
Thanks for quick reply. Yes indeed the tutorial mentioned "Index.cshtml" but I chose this one "Index.cshtml.cs" due to not showing file extension.

**Comment by mairaw** [comment]
Awesome to hear. I should have been more clear that you just needed to delete the folder and start over from the create your app step. I'll make sure to be more clear next time someone hits a similar problem.
