### ISSUE TITLE
I am using windows operating. I typed --version to for my dotnet version but I got an error message. The error message is: It was not possible to find any installed .NET Core SDKs   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:       https://aka.ms/dotnet-download

### ISSUE THREAD

**Issue by Essien-SM** [dotnet/core#7643]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
@Essien-SM please download and install .NET SDK by clicking on the `Download .NET 6 SDK` button first in case you haven't don that already.
 
 If you already have installed the .Net SDK and still seeing the error message try open a new console window and run the command

If still see the error with a new command prompt please run `where.exe dotnet` to find out where dotnet is installed and copy that path, add it to the environment variables, here is the instruction: https://github.com/dotnet/core/issues/5962#issuecomment-780084535 on how to do that
