### ISSUE TITLE
`dotnet test` should verify that testhost.exe and testhost.dll are the correct artifacts

### ISSUE THREAD

**Issue by fluffynuts** [dotnet/core#7645]
### Description

Today, I created a project called `TestHost` and put some tests in it. The idea is to write some arbitrary tests that a different test project would use in conjunction with `dotnet test` to test the output from a test logger that I'm writing. (example at https://github.com:fluffynuts/break-dotnet-test), but one can literally do `dotnet new nunit -n TestHost`.

However, I literally just spent the last hour or more trying to figure out why `dotnet test` in this folder produces:
```
  Determining projects to restore...
  Restored C:\tmp\TestHost\TestHost.csproj (in 160 ms).
  TestHost -> C:\tmp\TestHost\bin\Debug\net6.0\TestHost.dll
Test run for C:\tmp\TestHost\bin\Debug\net6.0\TestHost.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.2.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: . Please check the diagnostic logs for more information.

Test Run Aborted.
```

_especially_ after enabling all diagnostic reporting (--verbosity:diagnostic --diag:test.log) and finding no error - in fact, test.log contains lines about how testhost.exe exited with code 0 and no error.

On a lark, I thought that _perhaps_ the name was a problem, and found that renaming the .csproj (which changes the output file name - so I guess specifically setting an output binary path would have also worked) causes tests to run as expected.

### Configuration

* Which version of .NET is the code running on? net6.0
* What OS and version, and for Linux, what distro? Windows 11 21H2
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I'm guessing it's not 😅

### Regression?

I imagine I'm probably the first unfortunate soul to have stumbled across this. I'd be surprised if it wasn't always this way.

### Other information

since `dotnet test` is bringing in the testhost artifacts, I'm assuming it does so _before_ building, and the build is simply wiping them out. So it would be a good idea to either:
1. verify that the testhost files haven't been changed before starting, or, simpler
2. clean before building & attempt to copy _after_ building, and fail if those artifacts are already found

**Comment by ViktorHofer** [comment]
cc @nohwnd (there is no area-vstest label).

**Comment by IBH7493** [comment]
التحقق من وجود ملفات الاختبار وكذلك  التنظيف قبل عملية البناء

**Comment by nohwnd** [comment]
Thanks for the tag. Moved your issue here: https://github.com/microsoft/vstest/issues/3918

**Comment by fluffynuts** [comment]
apologies, I wasn't quite sure where to raise the issue (:

**Comment by nohwnd** [comment]
@fluffynuts No apology needed. :)
