### ISSUE TITLE
Hi, I was wondering how can I change the certificate if I didn't choose the right options the first time. It doesn't prompt anymore when I launch

### ISSUE THREAD

**Issue by NicoHambrouck** [dotnet/core#7649]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by IBH7493** [comment]
سيقوم بإعداد شهادة تطوير لاستضافة التطبيق عبر HTTPS ثم يطالبك بالثقة في الشهادة. نوصي بالموافقة على الوثوق بالشهادة. سيتم استخدام الشهادة فقط للتنمية المحلية ، وبدونها ستشكو معظم المتصفحات من أمان موقع الويب

**Comment by mairaw** [comment]
@danroth27 can you help here?

**Comment by danroth27** [comment]
@IBH7493 You can still create and trust the certificate by running: `dotnet dev-certs https --trust`
