### ISSUE TITLE
Can not run .net core 2.0 console app Raspberry Pi

### ISSUE THREAD

**Issue by silverf1re** [dotnet/core#765]
I have followed this guid https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md for linux and windows IoT and both throw 

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/home/pi/crypto/publish/ConsoleApp2.dll'. An attempt was made to load a program with an incorrect format.

No dependencies just default hello world.

**Comment by Petermarcu** [comment]
Usually that's because the wrong publish folder is being copied. Make sure you are under the linux-arm folder and all the way down to the publish folde4 under there for linux. Win-arm for windows.

**Comment by silverf1re** [comment]
Yep that is the correct folder. Could it have to do with what command tool i use to compile? here is the folder structure i deployed ..\Documents\Visual Studio 2017\Projects\ConsoleApp3\bin\x64\Debug\netcoreapp2.0\linux-arm\publish\
the x64 bothers me. What command line tools is everyone using? Any other Ideas?

**Comment by silverf1re** [comment]
Someone in another thread said I should be using the normal command prompt to create/compile however that doesnt recognize dotnet as a valid command. I have been using cross tools x86_64 visual studio command prompt 2017 perview 15.3.

**Comment by Petermarcu** [comment]
The `x64` bothers me too. The exception is also the one you get when you are trying to use x64 bits on arm. When I publish my sample app, the contents end up here `IotSample\bin\Debug\netcoreapp2.0\linux-arm\publish`. 

Did you install the .NET Core 2.0 SDK? That should add `dotnet.exe` to your path.

**Comment by silverf1re** [comment]
Yes I have installed .net core 2.0 preview 2 SDK. So when you build your app you are using the normal windows command line, not any of the visual studio command line tools correct? If that is the case Ill install the sdk on my other computer and try it there. Looking forward to your response and thanks for the help so far.

**Comment by Petermarcu** [comment]
Correct. Just a plain command prompt.

**Comment by silverf1re** [comment]
reinstalled the sdk and it works. Not sure what was wrong, thanks for your time i appreciate it. Looking forward to .net core development.

**Comment by Petermarcu** [comment]
Glad to hear you are off and coding now!
