### ISSUE TITLE
I have an issue need to solve

### ISSUE THREAD

**Issue by hassona2010** [dotnet/core#7653]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);

**Comment by mairaw** [comment]
Hi @hassona2010! Can you give us more information about the issue you're having.
