### ISSUE TITLE
Getting error CS8802: Only one compilation unit can have top-level statements.

### ISSUE THREAD

**Issue by ashDog** [dotnet/core#7658]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed .NET today for the first time ever and ran the following steps as instructed in the Hello World tutorial:
**bash-3.2$ dotnet new console -o MyApp -f net6.0**

<img width="642" alt="Screenshot 2022-08-03 at 16 08 21" src="https://user-images.githubusercontent.com/23057050/182643173-cdfb8373-3a6d-4be8-a79b-ad00655510f9.png">

**bash-3.2$ cd MyApp
bash-3.2$ dotnet new console -o MyApp**

<img width="536" alt="Screenshot 2022-08-03 at 16 09 28" src="https://user-images.githubusercontent.com/23057050/182643387-413e37bf-11e6-4d59-a3ce-2b4d15a09bf5.png">

**bash-3.2$ dotnet run**

<img width="1070" alt="Screenshot 2022-08-03 at 16 10 43" src="https://user-images.githubusercontent.com/23057050/182643664-8041eeb0-a675-4459-a2bf-8310cbc2148a.png">

Can you help please ? 
I am on a Mac (Catalina 10.15.7)
If I do:
bash-3.2$ dotnet --version
6.0.302

**Comment by mairaw** [comment]
Hi @ashDog! I usually see this error when the `dotnet new` command has been ran twice on different folders in the same hierarchy. In your screenshot above, it seems you did cd MyApp and then ran the command again, creating a second project inside that folder. You could just delete the top MyApp folder and start over.

Let us know if this helps.

**Comment by codes-of-yildiray** [comment]
@mairaw thank you very much.
