### ISSUE TITLE
.Net core SDK not found

### ISSUE THREAD

**Issue by jabedkhanjb** [dotnet/core#7660]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mattgen88** [comment]
I'm seeing this as well on ubuntu using microsoft apt sources. Got an upgrade, no sdks found now.

**Comment by buyaa-n** [comment]
@jabedkhanjb looks you haven't installed the SDK (Software Development Kit), move back to the [Download and install](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install) step and install it first before running any command

**Comment by buyaa-n** [comment]
@mattgen88 your problem doesn't seem related to this issue, because the issue found in Windows, please file a separate issue for your case with more details

**Comment by mairaw** [comment]
Also @jabedkhanjb, if you did install the SDK and is still having that issue, then it might be an issue with PATH.

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.
