### ISSUE TITLE
dotnet test using hostfxr.dll from wrong platform when testing x86 WinForms application

### ISSUE THREAD

**Issue by martinmueller4voice** [dotnet/core#7666]
### Description

I'm trying to create a test  for a .NET 6.0 Windows Forms application which has to be 32bit, so the project is set to platform x86.
The XUnit test project also is set to x86.

My test includes starting and ending the application.
I'm using Process.Start() to call the executable and when I perform the test from within VS Enterprise 2022, everything works as expected.

Using `dotnet test` does not work, though.
The application gets started but fails to load and returns exit code -2147450750 (0x80008002).

Windows event log shows:
```
Path: E:\myproject\myproject.tests\bin\x86\Debug\net6.0-windows7.0\myproject.exe
Message: Failed to load the dll from [C:\Program Files\dotnet\host\fxr\6.0.7\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\6.0.7\hostfxr.dll failed
```

As you can see, it's trying to load the **64bit** version of **hostfxr.dll** and this fails for the **32bit** application under test.

### Configuration

* .NET 6.0
* OS: Windows 10 21H2 (B 19044.1826) x64
* Application and test project architecture: x86

### Workaround
As I found out, copying the correct 32bit hostfxr.dll to the application's output directory makes the test complete successfully, just like it does from within VS.

**Comment by buyaa-n** [comment]
CC @RussKie

**Comment by RussKie** [comment]
Do you get the same issue for a console app too?

**Comment by martinmueller4voice** [comment]
Cannot get the same issue for a console app since hostfxr.dll is not loaded unless you have a UI...

**Comment by pratikkabade** [comment]
.NET musn't be installed properly
type `dotnet --version` in terminal.

If it shows error then install .NET prerequisites this might resolve this problem [from here](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4457144#:~:text=2018%2D09%20Security%20Monthly%20Quality%20Rollup%20for%20Windows%207%20for%20x64%2Dbased%20Systems%20(KB4457144))

**Comment by RussKie** [comment]
What SDK/runtime do you have installed? Please run `dotnet --version` and provide the output.

> Cannot get the same issue for a console app since hostfxr.dll is not loaded unless you have a UI...

I don't think that is true. But @richlander  @vitek-karas may correct me.

**Comment by vitek-karas** [comment]
`hostfxr` is used always. This feels like an issue with the test runner. @MarcoRossignoli for more details. 
I'm guessing the test runner sets `DOTNET_ROOT` to point to x64 install, which will break the x86 app.

Please can you try the following:
* run `dotnet --info` and paste the output here - this will tell us exactly what version you have installed.
* run `C:\Program Files (x86)\dotnet\dotnet --info` and paste the output here as well (same as above but for the x86 install on your machine)
* Try running the test by executing `C:\Program Files (x86)\dotnet\dotnet test ....`
* In a new console, `set DOTNET_ROOT="C:\Program Files (x86)\dotnet"` and then run the test using `dotnet test`
* Try to "fix" this by changing your test to clear the `DOTNET_ROOT` environment variable before you launch the child process.

**Comment by MarcoRossignoli** [comment]
@vitek-karas is right, this is a dup of https://github.com/dotnet/sdk/issues/22647#issuecomment-973898754 , you can try the suggestions.

**Comment by martinmueller4voice** [comment]
You both are correct, I get the problem with a console app as well.

<hr/>

The output of dotnet --info is:

```
E:\>dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   6.0.302
 Commit:    c857713418

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

<hr/>

dotnet x86 info:

```
C:\Program Files (x86)\dotnet>dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x86
  Commit:       0ec02c8c96

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

<hr/>

Trying to explicitely run dotnet in C:\Program Files (x86)\dotnet always fails with this output:

```
E:\git\myproject>"c:\Program Files (x86)\dotnet\dotnet.exe" test e:\git\myproject\myproject.sln
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'test' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

```

<hr/>

Setting DOTNET_ROOT to the x86 path and calling dotnet test like before makes my tests succeed.

Thanks for pointing out this option!

But I still don't really understand why the tests succeed in VS2022 and fail from a console.

**Comment by MarcoRossignoli** [comment]
It works on Visual Studio because the test runner starts as "server" (by VS) without the DOTNET_ROOT set and with Visual Studio usually are installed almost all runtime needed/supported so the apphost will resolve the runtime from the machine wide installation.

The SDK `dotnet test` does it because on Windows x64 we host the test inside an app host(testhost.exe) and it needs to know where's the runtime in case for instance of private installation on CI. Private installation means that you download the .NET SDK/runtime in a custom folder and run tests from there, when testhost.exe starts thanks to DOTNET_ROOT we can locate the runtime(if we're on CI it's possible that machine wide we don't have any dotnet installation).

**Comment by vitek-karas** [comment]
@martinmueller4voice the best way to fix this is to remove the `DOTNET_ROOT` from the environment when you're starting your child process from the test (you can probably do this globally for the entire test assembly in some "global init" method).

We didn't want to do this "for you" because typically if the process launches a child process it expect the same setup as the process itself - and so in the case of a private install (see @MarcoRossignoli answer above) the child process should use the private install as well. The case of the child process using different architecture is relatively uncommon.

@MarcoRossignoli one more case for trying to move away from .NET 2.1 testhost to some version which understands `DOTNET_ROOT_ARCH` in which case this would be avoidable :wink:

**Comment by MarcoRossignoli** [comment]
> Trying to explicitely run dotnet in C:\Program Files (x86)\dotnet always fails with this output:

It means that you don't have the SDK installed but only the runtime.
SDK and runtime are two distinct part.
With the runtime you can run an application(in production for instance) with the SDK you can restore, build, test...

You can download the x86 SDK from here https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by MarcoRossignoli** [comment]
cc: @nohwnd @Evangelink

**Comment by martinmueller4voice** [comment]
@MarcoRossignoli Doh! once again. The one who is able to read rules the world :-P
I assumed the x86 SDKs came with VS

Meanwhile I've added DOTNET_ROOT pointing to the x86 path to the environment of my test process and now all tests succeed  on Github Actions as well.

Thank you very much once again!
