### ISSUE TITLE
MaxQuant .Net Core issue

### ISSUE THREAD

**Issue by acragin** [dotnet/core#7669]
MaxQuant not working on hpZ8 computer. Error message keeps popping up each time a session is started making it unable to process. 
[netcore issue.pdf](https://github.com/dotnet/core/files/9270846/netcore.issue.pdf)

.Net Core 3.1 is installed on my desktop and I have restarted my computer since installing the program but this error still pops up. 

Any insights on what else I could do?

**Comment by pratikkabade** [comment]
It must be because `dotnet 3.1` is outdated update it to **6.0** or atleast **5.0**

**Comment by Sino-TangML** [comment]
I met the same problem. And I have installed the latest version of .Net Core SDK, including ".Net Core SDK 3.1.421", ".NET SDK 6.0.302", ".NET Framework 4.8.1 SDK". With the older version of MaxQuant (1.6.2.10), the problem may be solved, but a new problem emerged: value is either too big or too small for a double.

**Comment by buyaa-n** [comment]
CC @tannergooding

**Comment by tannergooding** [comment]
These all sound like issues with `MaxQuant` and are not actionable by the .NET team. You should file an issue with the authors of MaxQuant to get a fix.

The first issue might be related to whether the .NET Desktop Workload is installed. The latter issue does not have enough details for anything to be actionable. Something like a stack trace or minimal repro would be needed.
