### ISSUE TITLE
Unable to confirm if .Net SDK was successfully installed on myPC

### ISSUE THREAD

**Issue by adediranmuhydeen** [dotnet/core#7670]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I ran dotnet on comand Prompt after the installation of the latest SDK but i didn't get the expected result. The error mesage is captured bellow.

dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pratikkabade** [comment]
Yes, SDK isn't installed.
Download and Install both runtime as well as SDK to avoid this error.
Both available [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)

**Comment by adediranmuhydeen** [comment]
> Yes, SDK isn't installed.
> Download and Install both runtime as well as SDK to avoid this error.
> Both available [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)

I've installed the SDK, but I got an error message that the runtime that's more latest than the one I'm trying to install has already been installed.

**Comment by pratikkabade** [comment]
It shouldn't show like this.
Is issue still unresolved?
Is so, What exactly does it show and run
`dotnet --v` to confirm whether it's installed. And as you're using windows best I'd recommend is **reinstallation**.

**Comment by adediranmuhydeen** [comment]
Thank you, the issue has been resolved.
