### ISSUE TITLE
not able to build .net 6.0 console app in visual studio 2022 

### ISSUE THREAD

**Issue by virusharma** [dotnet/core#7671]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I have recently installed visual studio 2022 and I was trying to build hello world tutorial program but it is giving me build error complaining about not able to find SDK for .Net6.0. I have checked dotnet --info command as well dotnet --list-sdks command and I see the dotnet 6.0 sdks being installed. Also, I checked the path environment variable and I see it is referring only 64 bit path of dotnet. I uninstalled and resintalled VS 2022 and that did not help either

**The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.**

can you please advise how can I resolve this issue?

**Comment by ShreyasJejurkar** [comment]
> 

Can you please paste the content of your `.csproj` file here? I guess your project targetting something different which is not installed on your machine!

**Comment by virusharma** [comment]
@ShreyasJejurkar I knew it was installation issue but I already tried to repair visual studio. I actually even did uninstall and reinstall visual studio but that did not help. What worked eventually was uninstalling all the version of visual studio from the machine and uninstalling all .net core sdks and then installing visual studio 2022.

**Comment by surfmuggle** [comment]
Visual Studio is not installed on my machine. But nonetheless i had a similar issue with the dotnet command
```bash
dotnet new console -o MyConsole -f net6.0 --use-program-main --dry-run 
```
My installed frameworks were

```bash
C:\Users\foobar>dotnet --list-sdks
3.1.120 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.118 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
```

After installing `6.0.413 [C:\Program Files\dotnet\sdk]` the problem went away.
