### ISSUE TITLE
error on loading component

### ISSUE THREAD

**Issue by ghost** [dotnet/core#7674]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
@mrizwanazeez please provide info about the what problem you're experiencing and/or what error you are seeing. This issue is not actionable because you did not mention what error you have got on loading component.
