### ISSUE TITLE
Add support for Fedora 36

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/core#7676]
This issue is created to track progress for the work to enable [Fedora 36](https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html) support for .NET Core 3.1, .NET 6.0 and .NET 7.0.

**Comment by omajid** [comment]
Do you have any specific issues/tasks in mind here? It looks like we forgot to open a Fedora 36 issue, but I am not aware of any issues that exist on Fedora 36. I use Fedora 36 as my daily driver and I am not aware of any significant issues that impact .NET there.

**Comment by xtqqczze** [comment]
> Do you have any specific issues/tasks in mind here? It looks like we forgot to open a Fedora 36 issue, but I am not aware of any issues that exist on Fedora 36. I use Fedora 36 as my daily driver and I am not aware of any significant issues that impact .NET there.

I opened a tracking issue as Fedora 36 is not listed as a [supported distribution](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-fedora.md#supported-distributions) even though it was released on 2022-05-05.

**Comment by ashnaga** [comment]
EOL - 16 May 2023. Resolving.
