### ISSUE TITLE
aspnet hello-world-tutorial error

### ISSUE THREAD

**Issue by Xat0** [dotnet/core#7678]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Operating system version 21H2
Error: Invalid option(s):
--nohttps
'--nohttps' is not a valid option

**Comment by buyaa-n** [comment]
@Xat0 please use `--no-https` option not `--nohttps`
