### ISSUE TITLE
How to get PhysicalMemory

### ISSUE THREAD

**Issue by heartlocker** [dotnet/core#769]
As the .NET Core project could run on Windows, Linux and Mac OS. Is it possible for me to get the PhysicalMemory size of the running machine on these three OS. Just like in .NET framework, by using `Microsoft.VisualBasic.Devices.ComputerInfo` to get the Physical Memory information of the windows machine

**Comment by Petermarcu** [comment]
@AlexGhiondea , should this issue be moved to CoreFX to make an API proposal?

**Comment by AlexGhiondea** [comment]
@Petermarcu yes -- I will move it.

**Comment by AlexGhiondea** [comment]
Issue moved to [dotnet/corefx #22660](https://github.com/dotnet/corefx/issues/22660) via [**ZenHub**](https://www.zenhub.com/)
