### ISSUE TITLE
Create project command not working

### ISSUE THREAD

**Issue by inurdin** [dotnet/core#7695]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos

I am using MacOS 12.4 Monterey on Apple Silicon

The installer seems to skip installing any SDKs:

```
❯ dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

This causes the create project command to fail:

```
❯ dotnet new blazorserver -o BlazorApp --no-https -f net6.0
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

I tried to install Visual Studio for Mac, which includes the dotnet SDK (https://visualstudio.microsoft.com/vs/mac/), and it works, though it requires larger hard disk space for installation

**Comment by buyaa-n** [comment]
@inurdin what error / issue did you see in the previous `Download and install` step https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install?
