### ISSUE TITLE
C# version supported with .NET 7

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/core#7702]
### Description

From the .NET 7.0 release notes, the C# version is 9, should it be C# 11?
![image](https://user-images.githubusercontent.com/7604648/184097955-39a5202e-e350-47f6-8b5f-baa47537494e.png)

https://github.com/dotnet/core/blob/main/release-notes/7.0/preview/7.0.0-preview.7.md#visual-studio-compatibility

**Comment by mairaw** [comment]
That seems to be used in other release notes as well. @dcwhittaker cam you check?

**Comment by dcwhittaker** [comment]
Closing as this has been updated and merged.
