### ISSUE TITLE
Problem encountered while installing dotnet framework 4.7.2

### ISSUE THREAD

**Issue by Ruchi031** [dotnet/core#7704]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: Windows 7, 64-bit

error on cmd: 'dotnet' is not recognized as an internal or external command.

**Comment by mairaw** [comment]
What kind of problem are you encountering? And you're trying to install .NET Framework right? Not trying to learn how to develop .NET apps with .NET 6?

**Comment by Ruchi031** [comment]
Thank you for your response!
Actually, I was trying to install MySQL workbench on my laptop, which requires a .net framework for it!

**Comment by buyaa-n** [comment]
Please install .Net framework runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

**Comment by ShreyasJejurkar** [comment]
@Ruchi031 Looking at MySQL Installer requirement, you need to install .NET Framework 4.5.2 which you can download from the following link. 
https://www.microsoft.com/en-in/download/details.aspx?id=42642

**Comment by Ruchi031** [comment]
> 

Thank you for your link! I have installed this version of .net framework!
Can you please share the MySQL workbench link for the same version compatibility?

**Comment by Ruchi031** [comment]
> Please install .Net framework runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

@buyaa-n Thank you! But this version is not compatible with my PC, installing this giving an error!

**Comment by Ruchi031** [comment]
> > 
> 
> @ShreyasJejurkar Thank you for your link! I have installed this version of .net framework!
I have encountered this attached new issue while installing MySQL workbench!
![ss](https://user-images.githubusercontent.com/111129843/184616594-54c732f9-fef8-42a5-9297-7a2e37dfb25d.PNG)

**Comment by ShreyasJejurkar** [comment]
Hi @Ruchi031, As per the official documentation workbench is supported on Windows 11. Please the see below link for pre-requisites so I would suggest you to upgrade to Windows 11 and then try again to install MySQL Workbench.

https://dev.mysql.com/doc/workbench/en/wb-installing-windows.html

Upgrade to Windows 11 -> https://www.microsoft.com/software-download/windows11

Please let me know if the issue still persists!

**Comment by Ruchi031** [comment]
> Hi @Ruchi031, As per the official documentation workbench is supported on Windows 11. Please the see below link for pre-requisites so I would suggest you to upgrade to Windows 11 and then try again to install MySQL Workbench.
> 
> https://dev.mysql.com/doc/workbench/en/wb-installing-windows.html
> 
> Upgrade to Windows 11 -> https://www.microsoft.com/software-download/windows11
> 
> Please let me know if the issue still persists!

Hi @ShreyasJejurkar Actually my PC has Windows 7 and every time I tried to upgrade to the latest operating system, my windows crashed!
You can check my PC configuration, which I am attaching below! 
Please find it!
![ss](https://user-images.githubusercontent.com/111129843/185045762-a482f3a3-6d1d-4f06-ad85-347535cb5825.PNG)

**Comment by ShreyasJejurkar** [comment]
Hi @Ruchi031 Thanks for the reply. Ummm I can see your PC configuration is low, so maybe Win 11 is crashing. 
Ideally OS version is not issue, MySql is quite compatible with all Win versions. 
Let's try to install another prerequisite.  Please install following redistribution package from the link.  
https://aka.ms/vs/17/release/vc_redist.x64.exe

After you install, restart the PC and then try to reinstall MySql workbench. I hope this will help!

**Comment by Ruchi031** [comment]
Thank you for your reply. I will give it a try and if issue still persists,
I will let you know.

**Comment by ShreyasJejurkar** [comment]
Sure @Ruchi031. No worries. Please let us know! 😇
