### ISSUE TITLE
dotnet installation

### ISSUE THREAD

**Issue by Shibil-c** [dotnet/core#7706]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
'dotnet' is not as recognized as an  a internal or external command,operable program pr batch file.This what shows when types dotnet in the command prompt after installation

**Comment by buyaa-n** [comment]
@Shibil-c  If you already have installed the .Net SDK and still seeing the error message `'dotnet' is not as recognized as an a internal or external command` try open a new console window and run the command

If still see the error with a new command prompt please run where.exe dotnet to find out where dotnet is installed and copy that path, add it to the environment variables, here is the instruction: https://github.com/dotnet/core/issues/5962#issuecomment-780084535 on how to do that

**Comment by Shibil-c** [comment]
Thanks
