### ISSUE TITLE
لا استطيع التنزيل من موجهة الاوامر

### ISSUE THREAD

**Issue by MohamedAhmdsdn** [dotnet/core#7708]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
This is not actionable @MohamedAhmdsdn. Can you provide more details?
