### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by imohweb** [dotnet/core#7711]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I ran into the **_"'dotnet' is not recognized as an internal or external command,
operable program or batch file"_** issue after install dotnet on my system. My operating system version is windows 10 Pro 64-bit (10.0 Build 19043)

**Comment by wfurt** [comment]
Did you successfully install the .NET SDK? It should be somewhere under "Program Files/Dotnet". You can check the installation @imohweb
