### ISSUE TITLE
Installing Powershell and .NET 6 on Ubuntu 22.04 (Jammy)

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/core#7713]
# Installing Powershell and .NET 6 on Ubuntu 22.04 (Jammy)

We announced support for .NET 6 on Ubuntu 22.04 with our [May 2022 Updates](https://devblogs.microsoft.com/dotnet/may-2022-updates/). At that time, the [supported installation methods](https://docs.microsoft.com/dotnet/core/install/linux-ubuntu) were manual installation via a tarball or a .deb package via packages.microsoft.com (PMC). .NET 6 is now available natively via Jammy feeds, which can cause conflicts with PMC feeds.

For specifics on installation of just .NET 6, see issue https://github.com/dotnet/core/issues/7699

The following sections explain steps for installation of .NET 6 and Powershell, using packages from various available repositories.

## Scenario 1: Install Powershell and .NET 6 from PMC repo

Install Powershell by following steps for installation from package repository: https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2#installation-via-package-repository

Configure apt preferences, to prioritize PMC repository, by creating the following file: `/etc/apt/preferences`

To create the file:
```
sudo touch /etc/apt/preferences
```
with contents:
```
Package: *
Pin: origin "packages.microsoft.com"
Pin-Priority: 1001
```
Update your APT information:

`sudo apt update`

Install .NET SDK 6.0:

`sudo apt install dotnet-sdk-6.0`

## Scenario 2: Install Powershell from PMC, but .NET 6 from Ubuntu 22.04 (Jammy) repo

Install Powershell by following steps for installation from package repository: https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2#installation-via-package-repository

Configure apt preferences, to deprioritize PMC repository, by creating the following file: `/etc/apt/preferences`

To create the file:
```
sudo touch /etc/apt/preferences
```
with contents:
```
Package: *
Pin: origin "packages.microsoft.com"
Pin-Priority: 400
```
Update your APT information:

`sudo apt update`

Install .NET SDK 6.0:

`sudo apt install dotnet-sdk-6.0`

**Comment by Jo-Zh** [comment]
Thanks all, problems solved! I actually followed this https://github.com/dotnet/core/issues/7699 with Mixed state scenario 1.

**Comment by Alexandersdr** [comment]
como criar este arquivo? Package: *
Pin: origin "packages.microsoft.com"
Pin-Priority: 1001

**Comment by moh-hassan** [comment]
Installing net6 [SDK 6.0.419](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) from jammy  in Ubuntu 22.04 , cause runtime not shown by the command ```dotnet --list-runtimes' and runtime 6 is not available for any net6 application.

I resolved the issue by installing from PMC
```
Package: *
Pin: origin "packages.microsoft.com"
Pin-Priority: 1001
```
it is documented [here](https://github.com/dotnet/core/issues/7713)
```
Note: This build of .NET 6 is for the 6.0.1xx band. 6.0.4xx builds are available via PMC. That difference matters most to Windows users. Both builds are supported.

```
