### ISSUE TITLE
What's new in .NET 7 RC 2

### ISSUE THREAD

**Issue by leecow** [dotnet/core#7717]
# What's new in .NET 7 RC 2

This issue is for teams to highlight work for the community that will release .NET 7 RC 2

To add content, use a new conversation entry. The entry should include the team name and feature title as the first line shown in the template below. 

```
## Team Name: Feature title

[link to the tracking issue or epic item for the work]

Tell the story of the feature and anything the community should pay particular attention 
to be successful using the feature.
```
Preview 1: https://github.com/dotnet/core/issues/7106
Preview 2: https://github.com/dotnet/core/issues/7107
Preview 3: https://github.com/dotnet/core/issues/7108
Preview 4: https://github.com/dotnet/core/issues/7378
Preview 5: https://github.com/dotnet/core/issues/7441
Preview 6: https://github.com/dotnet/core/issues/7454
Preview 7: https://github.com/dotnet/core/issues/7455
RC 1: https://github.com/dotnet/core/issues/7716
RC 2: https://github.com/dotnet/core/issues/7717

**Comment by sajjadarashhh** [comment]
Thank you for this big new feature your details here is complete  but i have one question
what happend if browser not support this??
and which versions are support multithreading?

**Comment by danmoseley** [comment]
@ericstj @karelz @jeffhandley @eerhardt  for any RC2 stuff

**Comment by JonDouglas** [comment]
@JeremyLikness @AngelosP FYI

**Comment by eiriktsarpalis** [comment]
## System.Text.Json AppContext switch re-enabling reflection fallback in source generation https://github.com/dotnet/runtime/pull/75615

.NET 7 introduced an [intentional breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/7.0/reflection-fallback) which removes silent fallback to reflection-based serialization in System.Text.Json source generators. Based on early feedback we have been receiving from customers , it appears that quite a few users have (mostly accidentally) taken a dependency on the fallback behavior.

Even though a workaround for the breaking change has been documented, it still requires a code change which might not be possible in certain scenaria. Starting in .NET 7 RC 2, you can re-enable reflection fallback globally using the provided AppContext compatibility switch. Add the following entry to your application's project file to re-enable reflection fallback for all source-generated contexts in your app. For more information on using AppContext switches, see the article on [.NET runtime configuration settings](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/).

```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Text.Json.Serialization.EnableSourceGenReflectionFallback" Value="true" />
</ItemGroup>
```

**Comment by buyaa-n** [comment]
We have added 2 new analyzers for correct usage of new APIs:
- [Implement Generic Math interfaces correctly](https://github.com/dotnet/runtime/issues/69775) - Ensures the .NET Generic Math interfaces that uses [Curiously Recurring Template Pattern](https://wikipedia.org/wiki/Curiously_recurring_template_pattern) (CRTP) are implemented correctly in user code. In particular it warns if a type that implements the .NET Generic Math interfaces (that implements CRTP pattern) do NOT fill the generic type parameter with the type itself.
  Example: 
  ```cs
  public readonly struct DateOnly : IParsable<DateOnly> // correct implementation of IParsable<TSelf> interface
  { ... }
  public readonly struct MyDate : IParsable<DateOnly> // incorrect implementation the type `MyDate` should be provided for the type parameter TSelf 
  { ... }
  ```
- [Prevent behavioral change in built-in operators for IntPtr and UIntPtr](https://github.com/dotnet/runtime/issues/74022) - Some built in operators added in .NET 7 for System.IntPtr and System.UIntPtr behave differently than the user defined operators in .NET 6 and below. Some operators that used to throw in unchecked context while overflowing now no longer throw unless wrapped within checked context, and some operators that not used to throw in checked context now would throw when overflow unless wrapped within unchecked context. The analyzer detects the code that could cause those behavioral changes and informs it.
  Examples:
  ```cs
  checked
  {
      intPtr2 = intPtr1 + 2; // Warns: "Starting with .NET 7 the operator '+' will throw when overflowing in a checked context. Wrap the expression with an 'unchecked' statement to restore the .NET 6 behavior."

      intPtr2 = intPtr1 - 2; // Warns: "Starting with .NET 7 the operator '-' will throw when overflowing in a checked context. Wrap the expression with an 'unchecked' statement to restore the .NET 6 behavior."

      void* ptr = (void*)intPtr1; // Warns: "Starting with .NET 7 the explicit conversion '(void*)IntPtr' will throw when overflowing in a checked context. Wrap the expression with an 'unchecked' statement to restore the .NET 6 behavior."

      intPtr2 = (IntPtr)ptr; // Warns: "Starting with .NET 7 the explicit conversion '(IntPtr)void*' will throw when overflowing in a checked context. Wrap the expression with an 'unchecked' statement to restore the .NET 6 behavior."
  }

  intPtr1 = (IntPtr)longValue; // Warns: "Starting with .NET 7 the explicit conversion '(IntPtr)Int64' will not throw when overflowing in an unchecked context. Wrap the expression with a 'checked' statement to restore the .NET 6 behavior."

  int a = (int)intPtr1; // Warns: "Starting with .NET 7 the explicit conversion '(Int32)IntPtr' will not throw when overflowing in an unchecked context. Wrap the expression with a 'checked' statement to restore the .NET 6 behavior."
  ```

**Comment by danroth27** [comment]
@JonDouglas I spoke with @lambdageek and the plan is to include the [WebAssembly multithreading content](https://github.com/dotnet/core/issues/7717#issuecomment-1248351020) in the ASP.NET Core post.

**Comment by leecow** [comment]
.NET 7 GA is available. Closing these pre-release issues.
