### ISSUE TITLE
Exit code 139 with "Your First Microservice" - Tutorial

### ISSUE THREAD

**Issue by alkn87** [dotnet/core#7721]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: linux / Ubuntu 20.04.4 LTS

I installed everything via snap according to the [snap installation guide](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap)

When I try to run the generated web api application, I run into the following error when hitting the "Run" button within Rider IDE:
`Process finished with exit code 139.`

If I try to do `dotnet run` via terminal, I don't get any feedback in terminal.

**Comment by wfurt** [comment]
You can try `dotnet build` (and/or `dotnet restore`)  it usually gives more output. What do you see when you run `dotnet --info` @alkn87?

**Comment by alkn87** [comment]
Issue resolved after rebooting my Ubuntu machine. Never had to reboot a linux machine for something like this. Anyways, will close the issue.

`dotnet --info` gives the following:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```
