### ISSUE TITLE
Error starting dotnet on MacOS 12.5

### ISSUE THREAD

**Issue by rsdfwdsa** [dotnet/core#7723]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

rsdMacBook:~ rsd$ dotnet
-bash: dotnet: command not found

**Comment by mairaw** [comment]
which version did you install? and are you on a M1 machine?

**Comment by rsdfwdsa** [comment]
dotnet-sdk-6.0.400-osx-x64.pkg <https://download.visualstudio.microsoft.com/download/pr/2382b0d3-f865-4818-b3aa-47a94ccedba8/cd1eb0d061a1e1d8d0373603c4e82a97/dotnet-sdk-6.0.400-osx-x64.pkg>

Sorry — I just realized that I am on an M1 chip

**Comment by rsdfwdsa** [comment]
I downloaded the M1 installer and am OK. I read that, but forgot that I was on an M1 chip. Sorry to bother you. Blessings.

Rich

**Comment by mairaw** [comment]
No worries. Thanks for confirming. We'll try to improve that experience in the future as well and try to offer you the correct download.
