### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by leyton200** [dotnet/core#7724]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
What is your problem @leyton200? Did you install the SDK successfully? If so, can you run `dotnet` from _new_ command line windows?
