### ISSUE TITLE
Weird behaviors on SemaphoreSlim When Calling WaitAsync and Disposed

### ISSUE THREAD

**Issue by orr226** [dotnet/core#7726]
### Description
I noticed that when i have a task that wait for SemaphoreSlim and i passed to him a CancelationToken that I call cancel right before it SemaphoreSlim disposed, it wont throw OperationCanceledException and keep waiting forever unless i wait with delay before i call disposed.

Another thing that i noticed is when i call WaitAsync on SemaphoreSlim after it disposed, The function throw ObjectDisposedException
but if i call WaitAsync and then call dispose on SemaphoreSlim, the function WaitAsync do not throw ObjectDisposedException

i build a small repo with 4 test cases that represent the issue above https://github.com/orr226/SemaphoreSlimTest.
all the test in class [SemaphoreSlimDisposedTests.cs](https://github.com/orr226/SemaphoreSlimTest/blob/main/SemaphoreSlimTest/SemaphoreSlimDisposedTests.cs)

this behavior can cause Dead Lock if there is a code that still waiting to SemaphoreSlim and i need to dispose it (i can still call dispose when the the code that used SemaphoreSlim will stop running but its really wired that if i dont do that, my code can will be in deadlock).

I think that WaitAsync should throw ObjectDisposedException when someone disposed SemaphoreSlim while i waited for him.
and WaitAsync should throw OperationCanceledException when i call to Cancel on CancellationTokenSource even after i call to dispose without wating

### Configuration
.net 6, windows x64 (i think its also in linux)

### Regression?

Don't know

**Comment by svick** [comment]
I believe that calling `Dispose()` while the `SemaphoreSlim` is still being used (e.g. when a `WaitAsync()` is active) is undefined behavior, so I think the behavior you're describing is not a bug in in `SemaphoreSlim`.

Though [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.dispose?view=net-6.0#system-threading-semaphoreslim-dispose) could be clearer if that is indeed the case.

**Comment by orr226** [comment]
Ok, Thank you
