### ISSUE TITLE
In VS2022 I chose not to use https (unchecked) and it would not let me see the page. Edge said "Hmmmm.. can't load..."

### ISSUE THREAD

**Issue by ebley** [dotnet/core#7728]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

In VS2022 I chose not to use https (unchecked) and it would not let me see the page. Edge said "Hmmmm.. can't load...". Then I redid it with https checked, then set the launchSettings: sslPort = 0 and removed the https:/localhost:7xxx and all worked as expected.

Not the best marketing for my first blazor app ;-) I am a developer since 2000 btw - so it wasn't hard to try again, but for newbie's this bug should be fixed. 

I downloaded VS2022 about 4 days ago on a new machine.

**Comment by mairaw** [comment]
@ebley is this still happening? Since the product has changed quite a bit since then, I'll close this issue, but let me know if this is still an issue for you with the latest version of VS, .NET, and the tutorial.
