### ISSUE TITLE
No release notes for Microsoft.NETFramework.ReferenceAssemblies v1.0.3

### ISSUE THREAD

**Issue by jskeet** [dotnet/core#7731]
I've received a bunch of automated PRs to updateMicrosoft.NETFramework.ReferenceAssemblies from 1.0.2 to 1.0.3 - but I'm reluctant to do so without knowing what's changed.

https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies (a repo which says not to open issues there) only shows a history as far as 1.0.2. It would be good to update that page with the latest release notes.

**Comment by mairaw** [comment]
@NikolaMilosavljevic can you help with this?

**Comment by NikolaMilosavljevic** [comment]
Created PR for update: https://github.com/microsoft/dotnet/pull/1357

**Comment by NikolaMilosavljevic** [comment]
> I've received a bunch of automated PRs to updateMicrosoft.NETFramework.ReferenceAssemblies from 1.0.2 to 1.0.3 - but I'm reluctant to do so without knowing what's changed.
> 
> https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies (a repo which says not to open issues there) only shows a history as far as 1.0.2. It would be good to update that page with the latest release notes.

We have just published v1.0.3 on Friday. The only change is the addition of 4.8.1 package. In PR at the moment. Thank you for creating this issue!
