### ISSUE TITLE
配置Net时出现问题

### ISSUE THREAD

**Issue by Usloa** [dotnet/core#7733]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![9567f51edcf0d8cda98bbd3c8946de9](https://user-images.githubusercontent.com/110350819/186113915-60e249c9-0dc0-4c3f-8047-83aeaf0d451d.png)
![efa78fcbcd65257fa4cf8b6c7a51184](https://user-images.githubusercontent.com/110350819/186113924-ce78c6ee-0eaf-4638-8121-b9db44f511e0.png)

**Comment by mairaw** [comment]
Hi @Usloa 

It seems there is a space there after the .. It should be `net6.0` not `net6. 0`.

Make sure you use `dotnet new console -o MyApp -f net6.0`.

let us know if that helps.

**Comment by Usloa** [comment]
![c56aae18ec8571f44332c668546e6cc](https://user-images.githubusercontent.com/110350819/186223138-806a4309-8c79-4d68-8b20-22bed90bc265.png)我复制了你的也没有用

**Comment by wfurt** [comment]
BTW You should not need the `-f net6.0` it should default to it (assuming you have .NET 6.0 SDK (`dotnet --info`)

It is still curious how the '6.0` renders. For me, the zero is crossed and the `dot` is in the middle. 
(But this may be be because of the language setting)

**Comment by mairaw** [comment]
Correct. You can do just `dotnet new console -o MyApp`. See if that works for you.

The reason why we added the -f parameter was to make sure folks had the required SDK for the tutorial to work as-is. Otherwise, instructions and explanations don't always match.

Can you also share a screenshot of what `dotnet --info` returns?
