### ISSUE TITLE
dotnet new console -o MyApp -f net6.0 does not give any produce the program 

### ISSUE THREAD

**Issue by bdas615** [dotnet/core#7736]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows
![image](https://user-images.githubusercontent.com/100946737/186401222-256c3a12-103d-43f9-80f5-9ccfc7e0138d.png)
![image](https://user-images.githubusercontent.com/100946737/186401351-fae2decf-5152-47c9-904c-e20fee33516e.png)
dotnet --version gives the following output
![image](https://user-images.githubusercontent.com/100946737/186401471-43ea5c1c-4994-4a59-b308-79caf572059d.png)
dotnet --info gives the following output
![image](https://user-images.githubusercontent.com/100946737/186401690-a6233bb6-0fbe-4f65-8d33-8b81d6466475.png)
dotnet runtimes and sdks list is given as - 
![image](https://user-images.githubusercontent.com/100946737/186401982-82541282-3311-4075-aabe-69ff11ac8cc8.png)

**Comment by bdas615** [comment]
program in Visual Studio give this error
![image](https://user-images.githubusercontent.com/100946737/186402249-0573094e-4023-441d-b833-d8dbb95f0c5e.png)

**Comment by bdas615** [comment]
please check

**Comment by mairaw** [comment]
Hi @bdas615, can you show here what's the content of the global.json file located at c:\users\bdas? From the error message, it seems it's set to a preview version you don't have installed.

**Comment by bdas615** [comment]
![image](https://user-images.githubusercontent.com/100946737/186562002-d0c53c3f-80d4-4628-9758-9fb961c4d2df.png)

**Comment by bdas615** [comment]
this is the global json file you were requesting for

**Comment by wfurt** [comment]
Yes, it forces different version than you have available. I would suggest just to delete that file. (unless it is there for a reason)
