### ISSUE TITLE
string.Join("\r\n", list) - Out of Memory exception

### ISSUE THREAD

**Issue by okarpov** [dotnet/core#7739]
calling the string.Join("\r\n", list) on the list that has 2446078 strings and each string in the list is 500 or more characters causes Out of Memory exception

### Configuration
.Net Core 6
x64

**Comment by wfurt** [comment]
That will create super large string @okarpov and probably does need LOT of memory. 
cc: @tarekgh

**Comment by tarekgh** [comment]
I think you are running into the case described here https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/performance#issue-an-out-of-memory-exception-is-thrown.

**Comment by okarpov** [comment]
> I think you are running into the case described here https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/performance#issue-an-out-of-memory-exception-is-thrown.
> 
> One other note, the managed string is limited to the max length `int.MaxValue` (around 2G). If the joining strings lengths are greater than that, you may run into other problems.

this is length in bytes or chars?

**Comment by tarekgh** [comment]
> this is length in bytes or chars?

Length in chars.

**Comment by okarpov** [comment]
i see, thx, 
anyway, seems strange having any limitation while there is enough memory, isn't?

**Comment by wfurt** [comment]
`String.Length` is `int`... For what ever the reason is, strings are not meant to be giant.
