### ISSUE TITLE
Wrong Installer Image for .NET 7 Preview release notes

### ISSUE THREAD

**Issue by aligoren** [dotnet/core#7742]
### URL

https://github.com/dotnet/core/blob/main/release-notes/7.0/install-windows.md

### Operating system

Windows 11

### Description

The Release Notes page displays the .NET 6 installer image. It should show 7.0 instead.

![image](https://user-images.githubusercontent.com/4205423/186730877-a896a5a7-1057-4048-8a51-35bc071ddfbc.png)

I created a PR for this issue. [#7743](https://github.com/dotnet/core/pull/7743)

**Comment by dcwhittaker** [comment]
Closing as it's now been updated. Thanks for flagging!
