### ISSUE TITLE
why am i getting an error message anytime i try to install something saying contact your administrator or no device enabled? please help someone.

### ISSUE THREAD

**Issue by ashlex8909** [dotnet/core#7746]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
Did you install the .NET SDK? What `dotnet --info` gives you?
