### ISSUE TITLE
I'm having trouble writing c# for ubuntu

### ISSUE THREAD

**Issue by tahiraltundag** [dotnet/core#7747]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

concola dotnet new console -o MyApp -f net6.0
i get this error when i type:

he command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
and so far I haven't found a solution for this.
I'm going through the steps on your site, but I'm having trouble here, I'm waiting for your help, thanks.
This is the step I couldn't progress to on your site: https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
![Screenshot from 2022-08-28 11-31-20](https://user-images.githubusercontent.com/98649118/187065120-bdd10ecd-17da-44fc-ad19-a6a55a0ab763.png)

**Comment by wfurt** [comment]
what do you get when running `dotnet --info` @tahiraltundag?

**Comment by tahiraltundag** [comment]
global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

> koşarken ne elde edersin`dotnet --info` @tahiraltundag?

**Comment by tahiraltundag** [comment]
I'm downloading the sdk but still getting the error "Cannot find"

**Comment by wfurt** [comment]
I'm not sure I understand the last comment @tahiraltundag. You only have runtime, e.g. ability to execute code, but you don't have any SDK installed e.g. ability to develop. 

you should see something like 
```
.NET SDKs installed:
  6.0.102 [..../sdk]
```

**Comment by tahiraltundag** [comment]
i don't know what to do

**Comment by wfurt** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
make sure you download and install SDK, not just the runtime.

**Comment by tahiraltundag** [comment]
I downloaded the sdk from the link you gave, but it still didn't work, I always got this error and whenever I want to create a new c# application in the terminal, I always get an error. I tried all the errors one by one from the stackowerflow site but none of them solved my problem. I've been trying everything for two days but it doesn't work

**Comment by wfurt** [comment]
did  you install them, as well? Downloading is not sufficient. When  properly installed, `dotnet --info` should give you valid entry in the SDK section.

**Comment by tahiraltundag** [comment]
What commands do I need to install?

**Comment by wfurt** [comment]
How did you install the runtime? It should be basically the same. If you on ubuntu and if you add the repositories & keys, then `apt update && apt install dotnet-sdk-6.0` should do the trick.

**Comment by tahiraltundag** [comment]
I tried this a lot. I tried every way from microsoft's installation guide for ubuntu, it really doesn't work, but I will try again now for you.

**Comment by tahiraltundag** [comment]
i tried it again i got the same long error

**Comment by wfurt** [comment]
if you get error post the details. It is difficult to see what is going on with generic statements. Did the install succeeded? Do you see the package when querying package manager?

**Comment by tahiraltundag** [comment]
global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by wfurt** [comment]
well, you don't have the sdk. So back to my question: did the package install succeeded and do you see `dotnet-sdk-6.0` with package manager?

**Comment by tahiraltundag** [comment]
What command can I query to make the sdk appear?

**Comment by wfurt** [comment]
`apt install dotnet-sdk-6.0` would install the sdk or fail with error. 
You can run`dpkg -s dotnet-sdk-6.0` to see if the package is installed. 
You can run `apt list --installed | grep dotnet` to see what packages related to dotnet you have.

**Comment by tahiraltundag** [comment]
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

dotnet-apphost-pack-6.0/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [installed]
dotnet-host/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [installed]
dotnet-hostfxr-6.0/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [installed,automatic]
dotnet-runtime-6.0/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [installed]
dotnet-sdk-6.0/hirsute,now 6.0.400-1 amd64 [installed]
dotnet-targeting-pack-6.0/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [installed,automatic]
dotnet6/jammy-updates,now 6.0.108-0ubuntu1~22.04.1 amd64 [installed]

**Comment by tahiraltundag** [comment]
what steps should i take next

**Comment by tahiraltundag** [comment]
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /snap/dotnet-sdk/177/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/snap/dotnet-sdk/177/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/snap/dotnet-sdk/177/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/snap/dotnet-sdk/177/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by wfurt** [comment]
What are the crossed lines? Do you have `dotnet-runtime-6.0` (you can try to run `apt install dotnet-runtime-6.0`)

```
dpkg -L dotnet-sdk-6.0 | grep dotnet$
/usr/share/dotnet
```
it should show you where the SDK is installed.
then:
```
$ which dotnet
/usr/bin/dotnet
$ ls -al /usr/bin/dotnet
lrwxrwxrwx 1 root root 22 Jul 13 11:07 /usr/bin/dotnet -> ../share/dotnet/dotnet
```

I suspect you are missing packages from snap with standalone packages and they go to different locations and not see each other.

**Comment by wfurt** [comment]
actually, the last post looks good. Now, you should be able to run the example using dotnet from `/snap/dotnet-sdk/177`

**Comment by tahiraltundag** [comment]
how do i do what you said

**Comment by tahiraltundag** [comment]
dpkg -L dotnet-sdk-6.0 | grep dotnet$  

==> /usr/share/dotnet
/usr/share/dotnet
bash: /usr/share/dotnet: Is a directory
---------------------------------------------------------------------------------
which dotnet
/usr/bin/dotnet  

==> /usr/bin/dotnet
/usr/local/bin/dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
--------------------------------------------------------------------
ls -al /usr/bin/dotnet
lrwxrwxrwx 1 root root 22 Jul 13 11:07 /usr/bin/dotnet -> ../share/dotnet/dotnet

lrwxrwxrwx 1 root root 22 Jul 13 11:07 /usr/bin/dotnet -> ../share/dotnet/dotnet
lrwxrwxrwx 1 root root 24 Ağu 28 20:47 /usr/bin/dotnet -> /etc/alternatives/dotnet
bash: ../share/dotnet/dotnet: No such file or directory

**Comment by wfurt** [comment]
How did you run the command that give you the sdk? You seems to have `/usr/local/bin/dotnet` and `/usr/bin/dotnet`. 
Looking at the packages try it with full path
```
/usr/share/dotnet/dotnet new console -o MyApp -f net6.0
```
if that works, figure out how to remove the extra dotnet.

**Comment by tahiraltundag** [comment]
I didn't understand what you mean and this command didn't work :)

**Comment by tahiraltundag** [comment]
bash: /usr/share/dotnet/dotnet: No such file or directory

**Comment by wfurt** [comment]
how did you get output from https://github.com/dotnet/core/issues/7747#issuecomment-1230828440 ???

**Comment by tahiraltundag** [comment]
tahir@tah9r:~$ /usr/share/dotnet new console -o MyApp -f net6.0

bash: /usr/share/dotnet: Is a directory

**Comment by tahiraltundag** [comment]
did you mean

**Comment by omajid** [comment]
In https://github.com/dotnet/core/issues/7747#issuecomment-1230818311, the apt results show:

```
....
dotnet-runtime-6.0/jammy-updates,now 6.0.108-0ubuntu122.04.1 amd64 [installed]
dotnet-sdk-6.0/hirsute,now 6.0.400-1 amd64 [installed]
...
```

The first one is a package from Ubuntu jammy repos, the second is a package form Microsoft repos (see `hirsute` and the fact 6.0.4xx is not in source-build). This is seems like a package mixup. See https://github.com/dotnet/core/issues/7699 for more. You want to either follow "Mixed state scenario 1" or "Mixed state scenario 2"

**Comment by tahiraltundag** [comment]
i tried but it still didn't work

**Comment by wfurt** [comment]
details...????

**Comment by tahiraltundag** [comment]
![Screenshot from 2022-08-30 00-07-03](https://user-images.githubusercontent.com/98649118/187299114-acdbdff2-9d0a-497a-b493-9babc0bc76e5.png)

**Comment by tahiraltundag** [comment]
tell me what commands i need to enter and i will send you the details

**Comment by wfurt** [comment]
the crash comes from mixing the binaries from different sources. And of course you cannot ignore the error about privilege. That basically means nothing happened. You can get rights either running as`root` or run it as `sudo dpkg -i packages-microsoft-prod.deb`

**Comment by tahiraltundag** [comment]
![Screenshot from 2022-08-30 00-13-57](https://user-images.githubusercontent.com/98649118/187300241-7191b1b5-d92e-4753-b126-7341fa1e41c6.png)

**Comment by tahiraltundag** [comment]
Why is it so difficult and absurd to be able to do this seamlessly? I did it by watching the video and only mine has such problems and I've been struggling for two days and couldn't find any way. I don't understand exactly what you mean, sorry because my language is different and even if I use translate, I don't fully understand :(

**Comment by wfurt** [comment]
This is because you got you system to bad state so unrolling is difficult. Do you have the `packages-microsoft-prod.deb` file? If you deleted it you will need to fetch it again. 

One option IMHO is to remove all dotnet related packages and binaries and start over. Any thoughts on that @omajid?

**Comment by tahiraltundag** [comment]
Unfortunately, I have no idea and I want only one thing from you. I want to do all the operations that I should not do, by deleting all the old data and reloading it again as you say, and for this I want a list from you. Please I would appreciate if you write step by step what I need to do. I don't think I can understand and solve this problem any other way.

**Comment by tahiraltundag** [comment]
Thank you very much for your time and help.
My problem was solved with the following commands
