### ISSUE TITLE
Blazor got issue on Firefox 104.0

### ISSUE THREAD

**Issue by vandy11** [dotnet/core#7750]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

![image](https://user-images.githubusercontent.com/8581929/187230196-ccdb032f-f011-4ab4-a1e6-d6a17f1742e5.png)

it works fine on Chrome but not working on my Firefox version 104.0

**Comment by wfurt** [comment]
any thoughts @adityamandaleeka?

**Comment by vandy11** [comment]
It seems working already now, no any change,

**Comment by mairaw** [comment]
I'm glad it started working, so I'll close the issue.

**Comment by vandy11** [comment]
ok thanks
