### ISSUE TITLE
Ran into an issue :{

### ISSUE THREAD

**Issue by Madman1744** [dotnet/core#7754]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

OS version:- Windows 10
Error :- 
![2022-08-30](https://user-images.githubusercontent.com/85007461/187429006-f8d6d23c-a143-4f3d-9143-ccb12d491c8d.png)
Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file

**Comment by mairaw** [comment]
Console.WriteLine is not a command. Inside the MyApp directory, you should see a file called Program.cs. If you open that, you'll see the Console.WriteLine call there.
Try to continue the tutorial and let us know if you have more questions.
