### ISSUE TITLE
“RestSharp” package is failing  or not able to install with “.Net 6”

### ISSUE THREAD

**Issue by svadivel0006** [dotnet/core#7756]
Issue: The stable versions or pre-releases installation are failing with “.Net 6” version

Screenshot:

Project Details

![image](https://user-images.githubusercontent.com/85741928/187446656-5017f4b9-b467-4887-8c77-3318e941b38e.png)

Pre-Release failing

![image](https://user-images.githubusercontent.com/85741928/187446721-9b3d46aa-e549-46a7-b363-ba360e828b61.png)

Stable Version failing

![image](https://user-images.githubusercontent.com/85741928/187454370-4917aef7-6c35-40a8-b143-68da404911bc.png)

Archived Stable Version Failing

![image](https://user-images.githubusercontent.com/85741928/187446970-114ba465-aba8-4811-93d1-f4dd48443609.png)

**Comment by nkolev92** [comment]
The project and the package can't have the same name.

**Comment by mairaw** [comment]
I believe the response above addresses the issue. Let us know if you still need more help.

**Comment by svadivel0006** [comment]
Hi,

The issue can be closed, thanks

Regards,
Vadivel Sekar

**Comment by mairaw** [comment]
Thanks for letting us know!
