### ISSUE TITLE
Run DotNET

### ISSUE THREAD

**Issue by Ghad1ee2r3** [dotnet/core#7758]
Hi 
I installed DOTNET Version=v4.7.2 when trying to check if install or not , display to me this message "'dotnet' is not recognized as an internal or external command, operable program or batch file."

How can I solve this error?
 my pc is windows 10

**Comment by mairaw** [comment]
The dotnet command will only work if installing the .NET/.NET Core runtimes and SDKs. It won't work with .NET Framework, which is the product for 4.7.2

**Comment by Ghad1ee2r3** [comment]
how can I decide version of the framework when working in project?

**Comment by pratikkabade** [comment]
@Ghad1ee2r3 always go with latest stable version

**Comment by GrabYourPitchforks** [comment]
Issue appears to have been resolved. Please respond back if you need further assistance. Thanks!
