### ISSUE TITLE
Build CIL into an executable on Linux

### ISSUE THREAD

**Issue by avin-kavish** [dotnet/core#7759]
As the title says, I'd like to basically run CIL code directly without going through a language like C#. I've read about `ilasm.exe`, is there a linux equivalent to it?

**Comment by rzikm** [comment]
There are ilasm and ildasm for linux available as a NuGet packages
- https://www.nuget.org/packages/runtime.linux-x64.Microsoft.NETCore.ILDAsm/.
- https://www.nuget.org/packages/runtime.linux-x64.Microsoft.NETCore.ILAsm/

Inside the packages you can find their executables.

**Comment by svick** [comment]
Or you could use Microsoft.NET.Sdk.IL. As a starting point, have a look at [this example project](https://github.com/jvbsl/ILProj) (even though it's quite outdated).
