### ISSUE TITLE
Not able to get the display port after the first run

### ISSUE THREAD

**Issue by achuss** [dotnet/core#7762]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After the first "dotnet run" the next instruction is "Wait for the app to display that it's listening on http://localhost:<port number>, and then open a browser and navigate to http://localhost:<port number>/WeatherForecast."

But I never get that message

**Comment by rzikm** [comment]
Hi, can you share the output of the `dotnet run` command?
