### ISSUE TITLE
Support podman (and other container runtimes) with vsdbg

### ISSUE THREAD

**Issue by atotalnoob** [dotnet/core#7765]
Currently all of Visual Studio's container support is centered around Docker. While docker is the dominate container runtime on Windows, there are alternatives. Additionally, since Docker is [now charging](https://www.docker.com/pricing/) for docker desktop, I suspect organizations will be seeking alternative container runtimes that are free or lower cost. 

Allowing vsdbg to use `podman` or another container runtime will allow organizations seamless adoption of various container runtimes. 

VSCode already allows one to change the executable name/path (remote container tools setting -> `Docker Path`). It seems natural to extend this support to the rest of the microsoft container ecosystem. 

One could use `doskey` or `Set-Alias` to alias `podman` to docker, but it would be better to have an official way to change the executable from Microsoft.

**Comment by rzikm** [comment]
Thank you for your feedback, can you please use [this form](https://developercommunity.visualstudio.com/report?entry=suggestion&space=8&preview2=true) to request the feature?
