### ISSUE TITLE
ConcurrentBag and Linq NullReferenceException or AccessViolationException

### ISSUE THREAD

**Issue by okarpov** [dotnet/core#7770]
### Description

I'm getting the following exception or AccessViolationException from time to time on Linq Sum of ConcurrentBag

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentBag`1.ToArray()
   at System.Collections.Concurrent.ConcurrentBag`1.GetEnumerator()
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
```

### Configuration

.Net Core 6
Windows 11

**Comment by okarpov** [comment]
sum is on non-nulable long propery

**Comment by okarpov** [comment]
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
The thread 0x3644 has exited with code 0 (0x0).
The thread 0x5588 has exited with code 0 (0x0).
The thread 0x1d44 has exited with code 0 (0x0).
The thread 0x4c1c has exited with code 0 (0x0).
The thread 0x42d0 has exited with code 0 (0x0).
The thread 0x7700 has exited with code 0 (0x0).
The thread 0x3658 has exited with code 0 (0x0).
The thread 0x73d0 has exited with code 0 (0x0).
The thread 0x4f7c has exited with code 0 (0x0).
The thread 0x4b48 has exited with code 0 (0x0).
An unhandled exception of type 'System.AccessViolationException' occurred in System.Private.CoreLib.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by okarpov** [comment]
however, seems like it is under VS mostly:

Microsoft Visual Studio Community 2022
Version 17.3.3
VisualStudio.17.Release/17.3.3+32825.248
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22423.10+b35bb0baca1071d50cc4f8cf5a1a89e7cc112461
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22423.10+b35bb0baca1071d50cc4f8cf5a1a89e7cc112461
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

**Comment by rzikm** [comment]
Can you share the code which produces the exception?
