### ISSUE TITLE
I installed dotnet 6 sdk and runrime as well. But can't find in cmd. 

### ISSUE THREAD

**Issue by nazmulaws** [dotnet/core#7772]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Did you open a new command prompt window? The installation process modifies the PATH environment variable and the change is visible only after opening a new command prompt.
