### ISSUE TITLE
Site isn't showing time as in the tutorial

### ISSUE THREAD

**Issue by EruptingStudios** [dotnet/core#7774]
The site don't show the time like it does in the screenshot images from Microsoft.

**Comment by rzikm** [comment]
Hi, can you be more specific? What tutorial are you following and what does the website look like?

**Comment by EruptingStudios** [comment]
The site is down both of them and im following the microsoft tutorial linked here https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

**Comment by mairaw** [comment]
Which site is down?

**Comment by EruptingStudios** [comment]
Sorry for only seeing its this one http://[localhost](http://localhost:5185/):5185/

**Comment by mairaw** [comment]
But the tutorial doesn't involve websites.
