### ISSUE TITLE
+ // See https://aka.ms/new-console-template for more information + ~~     + CategoryInfo          : ObjectNotFound    : (//:String) [], CommandNotFoundExcepti   on     + FullyQualifiedErrorId : CommandNotFoun    dException

### ISSUE THREAD

**Issue by iamevanfromchina** [dotnet/core#7779]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Hi, this looks like an error message from PowerShell, what are you trying to run?
