### ISSUE TITLE
dotnet' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by JettHan7** [dotnet/core#7780]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed .NET 6 SDK and I can see a folder named "dotnet" under C:/Program Files/, but I still receive a "'dotnet' is not recognized as an internal or external command" error

**Comment by mairaw** [comment]
This might be an issue with PATH.

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.

**Comment by JettHan7** [comment]
> This might be an issue with PATH.
> 
> Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at [#5962 (comment)](https://github.com/dotnet/core/issues/5962#issuecomment-780084535) to fix the issue.
> 
> Let us know how that goes.
![1662624628067](https://user-images.githubusercontent.com/113039995/189070831-522f710d-bb3f-497a-a6ec-4a87af968677.jpg)

It doesn't works

**Comment by JettHan7** [comment]
> This might be an issue with PATH.
> 
> Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at [#5962 (comment)](https://github.com/dotnet/core/issues/5962#issuecomment-780084535) to fix the issue.
> 
> Let us know how that goes.

![1662624868771](https://user-images.githubusercontent.com/113039995/189071324-39856e7c-c96a-42d7-8e43-e82fcf736c93.jpg)

It doesn't works

**Comment by mairaw** [comment]
Can you share the output of the following commands?

`where.exe dotnet`
`dotnet --info`

Make sure you open a new command prompt window.
