### ISSUE TITLE
Handbrake app

### ISSUE THREAD

**Issue by stue230** [dotnet/core#7783]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows 11

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I installed net using X64 and X86 but neither worked to launch Handbrake app

Please advise

**Comment by mairaw** [comment]
@stue230 do you know which version Handbrake is requiring? And do they want you to install .NET Framework or .NET 6?

**Comment by stue230** [comment]
I did respond with the following:
It finally installed but message says
To run this application, I must install missing frameworksfor .NET.

I am running WINDOWS 11 on hp laptop.

I have not received an update and it is not resolved.

Have A Blessed Day

Stu Estrade, MCS

504-289-3781


Confidentiality Notice: The contents of this email are confidential, and
intended only for the use of the individuals and/or entity named above. If
the reader of this email is not the intended recipient, you are hereby
notified that any dissemination, disclosure, copying, or distribution of
the contents of this email message is strictly prohibited by law. If you
received this email in error, please immediately notify the sender by
return email or by phone 504-289-3781 and delete the material from your
computer.

**Comment by mairaw** [comment]
Can you share a screenshot or share the exact message that it shows? I'm trying to determine which version Handbrake is requiring.

**Comment by stue230** [comment]
Sure, here it is.

[image: image.png]

I have downloaded and installed both
[image: image.png]
Is there a Windows 11 permission that I need to change?

Have A Blessed Day

Stu Estrade, MCS

504-289-3781


Confidentiality Notice: The contents of this email are confidential, and
intended only for the use of the individuals and/or entity named above. If
the reader of this email is not the intended recipient, you are hereby
notified that any dissemination, disclosure, copying, or distribution of
the contents of this email message is strictly prohibited by law. If you
received this email in error, please immediately notify the sender by
return email or by phone 504-289-3781 and delete the material from your
computer.

**Comment by mairaw** [comment]
Unfortunately, the images cannot be attached via email responses. Can you come to the issue on the GitHub website to upload the screenshots?

**Comment by stue230** [comment]
![image](https://user-images.githubusercontent.com/113188981/191351290-d69eaf43-c3a6-42b0-9561-3154a1c0ff46.png)

**Comment by stue230** [comment]
Yes, I can.

Have a Blessed Day

Stu Estrade, MCS
504-289-3781

**Comment by mairaw** [comment]
Thank you. And when you click on yes, where does that button take you?

**Comment by stue230** [comment]
It used to take me to the https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
until I installed both the 64 and 32 version. Now it goes no where.

I do not want to create apps but just use Handbrake

**Comment by mairaw** [comment]
Ah ok. Without knowing where they sending folks, it's hard to fix the experience on our side. It might be an issue on their end.

**Comment by mairaw** [comment]
I'd advise that you log your issue at https://github.com/HandBrake/HandBrake/issues. They'll know which frameworks they require.

**Comment by mairaw** [comment]
This thread might he;p as well: https://forum.handbrake.fr/viewtopic.php?t=42066

**Comment by stue230** [comment]
I uninstalled Handbrake to re-install
This comes up first before 

![image](https://user-images.githubusercontent.com/113188981/191642715-10bb4439-6074-4af6-aee0-bc5204b24db6.png)

**Comment by stue230** [comment]
That worked....Thanks for your time and patience

**Comment by stue230** [comment]
It finally installed but message says
To run this application, I must install missing frameworksfor .NET.

I am running WINDOWS 11 on hp laptop.

Have a Blessed Day

Stu Estrade, MCS
504-289-3781
