### ISSUE TITLE
can not install .net

### ISSUE THREAD

**Issue by wulufei** [dotnet/core#7784]
My mac is pro13. I installed SDKarm64. it seems completed.but I tried $ dotnet code in new terminal, I receive a zsh: command not found: dotnet error. I tried many times.
pls help. Thank you very much

**Comment by rzikm** [comment]
Did you follow this tutorial? https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install It says to open a *new* terminal session after you install the SDK to pick up the changes.

**Comment by mairaw** [comment]
Is your machine a M1 machine?
