### ISSUE TITLE
dotnet run :error CS8802

### ISSUE THREAD

**Issue by wxf813** [dotnet/core#7787]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
It may be possible you have encountered same situation as in https://github.com/dotnet/core/issues/7658. Can you verify there is exactly one Program.cs file in the directory (and subdirectories) you are trying to run the command in?.

**Comment by dsantos1998** [comment]
I have this issue with a MVC project by layers. I only have one program.cs and get me this error when I try to start to compile with docker:
[...]/Program.cs(4,1): error CS8802: Only one compilation unit can have top-level statements.

The code of my Program.cs starts with:
[Some usings]
![image](https://user-images.githubusercontent.com/33556430/201436487-4d515f04-cd2b-4121-8fd3-39c027d0bbcb.png)

In Dockerfile I copy all the project in a src folder and RUN the build for the app.csproj, like:
COPY ["WebApp/WebApp.csproj", "WebApp/"]
COPY ["../ControllersLayer/ControllersLayer.csproj", "ControllersLayer/"]
COPY ["../ModelsLayer/ModelsLayer.csproj", "WebApp/"]
[...]

The exit of the VS tell me the error is in the "RUN dotnet build [...]" command of the dockerfile.
