### ISSUE TITLE
Problem encoding "EUC-JP"

### ISSUE THREAD

**Issue by ll01** [dotnet/core#779]
# Issue Title
When trying  to get the encoder for EUC-JP it crashes
# General
The exception is 

`Exception has occurred: CLR/System.ArgumentException
An unhandled exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll: ''EUC-JP' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.`

The  code is something like  
`var encoder =  System.Text.Encoding.GetEncoding("EUC-JP");`

I've also tried using the page code 20932 still not working

**Comment by Petermarcu** [comment]
@tarekgh any advice?

**Comment by tarekgh** [comment]
Please try to reference the library System.Text.Encoding.CodePages and then add the following line in your app initialization code:

```C#
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

That is what the exception message suggested and may look at the link https://msdn.microsoft.com/en-us/library/mt643899(v=vs.110).aspx#Remarks for more info.
