### ISSUE TITLE
I am receiving zsh: command not found: dotnet and I am in a new terminal window what to do moving forward.

### ISSUE THREAD

**Issue by lebotreasure** [dotnet/core#7795]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What mac do you have and what version did you install?

**Comment by lebotreasure** [comment]
Good evening

I have Macbook Air and version 12.
