### ISSUE TITLE
.NET 7.0 RC 1

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7800]
[Release Notes](https://github.com/dotnet/core/blob/main/release-notes/7.0/preview/7.0.0-rc.1.md)

Please report any issues you find with [.NET 7 RC1](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-rc-1/), either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by DoomerDGR8** [comment]
Hi!

Congrats on the release.

Immediately, the `RegexGenerator` attribute is not getting resolved. Packages are updated and also the global.json too.

![image](https://user-images.githubusercontent.com/825078/190329052-47a7b9d8-8f1e-48aa-b5bc-9645aec52024.png)

```
[RegexGenerator("[(?*\",\\\\<>&#~%{}+$^@.\\s:\\/!;)]+")]
private static partial Regex FileFolderNameInvalidCharacterRegex();
```

**Comment by teo-tsirpanis** [comment]
@DoomerDGR8 it has been renamed to `[GeneratedRegex]`.

**Comment by amis92** [comment]
Hi, not sure where to raise that, but it seems the `https://dotnetcli.azureedge.net/dotnet/Sdk/7.0/latest.version` doesn't work correctly (it refers to Preview 7 still), which causes these two invocations to have different results:

```
> .\dotnet-install.ps1 -Channel 7.0 -Quality preview -DryRun
[snipped for brevity]
dotnet-install: Payload URLs:
dotnet-install: URL #0 - aka.ms: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100-rc.1.22431.12/dotnet-sdk-7.0.100-rc.1.22431.12-win-x64.zip

> .\dotnet-install.ps1 -Channel 7.0 -DryRun
[snipped for brevity]
dotnet-install: Payload URLs:
dotnet-install: URL #0 - primary: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100-preview.7.22377.5/dotnet-sdk-7.0.100-preview.7.22377.5-win-x64.zip
dotnet-install: URL #1 - legacy: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100-preview.7.22377.5/dotnet-dev-win-x64.7.0.100-preview.7.22377.5.zip
```

Which in the end will install Preview 7 for `dotnet-install -Channel 7.0` and RC1 for `dotnet-install -Channel 7.0 -Quality preview`.

It's important for CI/CD scenarios where we want to start using .NET 7 with Release Candidates and then fluently move to GA when it's released (so we want to just use the `dotnet-install -Channel 7.0` command).

**Comment by dcwhittaker** [comment]
@amis92 I've just checked all of them and updated the SDK version. If you could try again and let me know if you're still running into issues. Thanks so much!

**Comment by amis92** [comment]
I guess I'll need to wait a bit for CDN to refresh cache, as `./dotnet-install.ps1 -Channel 7.0 -DryRun -NoCdn` now does resolve to RC1, but same without `-NoCdn` switch still has Preview 7. Thanks!

**Comment by amis92** [comment]
Hmm @dcwhittaker I'm not sure how long it's going to get cached? `https://dotnetcli.azureedge.net/dotnet/Sdk/7.0/latest.version` (which is what `./dotnet-install.ps1 -Channel 7.0 -DryRun` uses afaik) is still cached on the edge if I understand correctly and returns Preview 7. Shouldn't these files have cache purged for them when updating?

**Comment by dcwhittaker** [comment]
Hi @amis92 - can you try again? We just purged the cache again.

**Comment by amis92** [comment]
I've verified - that's all fixed now, thanks so much!

**Comment by Chamberlain91** [comment]
Using `internal fixed float M[16];` for a `Mat4` struct is not being initialized to all zeros in an Android release build.

**Comment by sub7ero** [comment]
![image](https://user-images.githubusercontent.com/1119544/192137764-776b412b-92f3-4157-bd40-f2a30a698acb.png)

The code analysis breaks now. Unfortunatley no fix as described [here](https://learn.microsoft.com/en-us/answers/questions/244179/microsoftcodeanalysis-problem.html) works.

**Comment by esskar** [comment]
New issue created #7840

**Comment by dcwhittaker** [comment]
Closed in favor of https://github.com/dotnet/core/issues/7865
