### ISSUE TITLE
Ubuntu Server LTS 22.04 | Unable to locate package dotnet-sdk-6.0 

### ISSUE THREAD

**Issue by th3seb** [dotnet/core#7809]
### Description
I would like to use dotnet6 on my Raspberry PI which runs Ubuntu Server LTS 22.04.1
<img width="264" alt="CleanShot 2022-09-15 at 22 43 59@2x" src="https://user-images.githubusercontent.com/59930823/190505119-6fb3c989-f7c7-4ad3-af59-dea5f11f8dec.png">
But I am not able to install the packages with `sudo apt install dotnet6`
<img width="305" alt="CleanShot 2022-09-15 at 22 45 43@2x" src="https://user-images.githubusercontent.com/59930823/190505441-0ab68d12-f191-4361-8e6b-ecee7704bfac.png">

I've tried to of course first of all add the repo:
`wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb `
`sudo dpkg -i packages-microsoft-prod.deb`
<img width="1449" alt="CleanShot 2022-09-15 at 22 49 29@2x" src="https://user-images.githubusercontent.com/59930823/190506127-345d877f-e9d2-4231-9f88-dace25060b26.png">

and then I installed the apt-transport-https package and updated and tried to install the dotnet-sdk-6.0
`sudo apt install apt-transport-https `
`sudo apt update `
`sudo apt install dotnet-sdk-6.0 `
<img width="852" alt="CleanShot 2022-09-15 at 22 51 02@2x" src="https://user-images.githubusercontent.com/59930823/190506380-81cd69c5-4602-4a2a-aad1-885e316a897c.png">
But that doesn't work for me :/ and I don't really know what to do at this point 

### Configuration

Raspberry Pi 4b 2G 
Ubuntu 22.04.1 LTS Server 64bit

**Comment by tarekgh** [comment]
Closing it as it looks @omajid already answered it.
