### ISSUE TITLE
dotnet is not recognised in Visual Studio despite the fact that i installed. Please help I'm struggling.

### ISSUE THREAD

**Issue by XX0012** [dotnet/core#7810]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Which Visual Studio version do you have?
