### ISSUE TITLE
Problem encountered on .NET Tutorial - Deploy a microservice to Azure

### ISSUE THREAD

**Issue by migste** [dotnet/core#7812]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

Issue: Unable to continue with the tutorial by following the steps given

Command: az aks create --resource-group MyMicroserviceResources --name MyMicroserviceCluster --node-count 1 --enable-addons 

Message: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/aks/quotas-skus-regions

**Comment by fransiscuss** [comment]
@migste - Could you please try use different region e.g East US 2 or Specify the VM Size --node-vm-size Standard_DS2_v2 . Standard_DS2_v2 is just an example here, find whats available on WestUs?

https://github.com/MicrosoftDocs/azure-docs/issues/92884

**Comment by migste** [comment]
By using region "East US 2" I was able to continue with the tutorial. Thanks @fransiscuss!
