### ISSUE TITLE
Invalid base64-encoded string error occurred when trying to create aks cluster

### ISSUE THREAD

**Issue by ailani** [dotnet/core#7815]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows 11 64 Bit

I tried the command from the tutorial

az aks create --resource-group MyMicroserviceResources --name MyMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys

and it gave the error. I created free subscription on Azure and created the resource in westus region as per the tutorial. I am new to Azure so don't know what could have gone wrong. If someone has encountered this problem or know how to solve it, please help.

**Comment by mairaw** [comment]
What was the exact error message you got?

**Comment by ailani** [comment]
Thank you Maira for checking. Here is the exact error I got

Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

**Comment by ailani** [comment]
My problem got solved. I saw another thread. Problem was, I didn't have the .ssh directory in my Users directory location. Created it using ssh-keygen and then the command worked. Thank you.
