### ISSUE TITLE
I cannot create BlazorApp

### ISSUE THREAD

**Issue by RubyRahman** [dotnet/core#7816]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos

Template "Blazor Server App" could not be created.
Failed to create template.
Details: Read-only file system : '/BlazorApp'

**Comment by mairaw** [comment]
In what path are you trying to create the app? Did the error message contain any other details?

**Comment by danroth27** [comment]
Hi @RubyRahman. I'm sorry to hear you're hitting some issues creating you first Blazor app! To help us understand what's going wrong, could you please share with us the output of running the following two commands:

```
dotnet --version
dotnet new blazorserver
```
