### ISSUE TITLE
what's the matter?

### ISSUE THREAD

**Issue by loveisbelief** [dotnet/core#7818]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet new console -o MyApp -f net6.0.401
段错误 (核心已转储)

**Comment by Jozkee** [comment]
@mairaw

**Comment by mairaw** [comment]
Have you installed .NET with snap?
