### ISSUE TITLE
Asp.net Problem installing

### ISSUE THREAD

**Issue by JoeParsa** [dotnet/core#7820]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

It keeps throwing this error when I'm installing the Asp.Net
Error: Invalid option(s):
-f net6.0
   'net6.0' is not a valid value for -f. The possible values are:
      netcoreapp3.1   - Target netcoreapp3.1

For more information, run 'dotnet new webapp --help'.

**Comment by Jozkee** [comment]
@mairaw

**Comment by carlossanlop** [comment]
@JoeParsa what version of dotnet did you install? Did you make sure to open a new console _after_ installing dotnet, to ensure the environment variables were properly set and read?
