### ISSUE TITLE
Issue with creating a .Net application

### ISSUE THREAD

**Issue by Shaik-muzamil-03** [dotnet/core#7822]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/create
Operating System: windows
Blazor (server-side) (C#)
Author: Microsoft
Description: A project template for creating a Blazor application that runs server-side inside an ASP.NET Core application. This template can be used for web applications with rich dynamic user interfaces (UIs).
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.
Error: Invalid parameter(s):
-f net6.0
    'net6.0' is not a valid value for -f (Framework).

**Comment by Jozkee** [comment]
@mairaw

**Comment by pratikkabade** [comment]
If you're using vs2019 or lower lower .NET 6.0 is not supported
That's why you're seeing that error

**Comment by mairaw** [comment]
What does `dotnet --info` returns? This error message typically indicates you haven't installed the required SDK for the tutorial to work.
