### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Gouravsingh2k1** [dotnet/core#7827]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

unable to install / run dotNet and C# on my Lenovo duet 5 chromebook

**Comment by pratikkabade** [comment]
To install dotnet on Linux use `sudo` command. It'd be more faster and efficient

**Comment by michaelgsharp** [comment]
Can you please provide any steps that you have tried?

**Comment by pratikkabade** [comment]
Which Linux distribution do you use?

Try this if you're on **Ubuntu**.

```
sudo apt-get update
```

Then install dotnet
```
sudo apt-get install -y dotnet6
```

Then install runtime
```
sudo apt-get install -y dotnet-runtime-6.0
```

This should work but if you're using different distro `apt-get` won't work.
