### ISSUE TITLE
zsh: command not found: dotnet

### ISSUE THREAD

**Issue by juiceellish** [dotnet/core#7828]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

So, I've installed .NET x64 at least 12 times *successfully*, and in neither my local terminal nor VS Code terminal does the dotnet command work. I don't know how to search my mac for the installation path because I can't change the path manually. I only use the internal Macintosh HD disk so, with it showing a successful install, it's somewhere on my computer + I'm major confusion on why the command doesn't work. Send help.

**Comment by jooshellis** [comment]
Yes. I tried a new window many times and in the VS Code terminal. I get the same error.

**Comment by pratikkabade** [comment]
@jooshellis what do you see on `dotnet --version` or `dotnet --list-sdks`

**Comment by jooshellis** [comment]
> @jooshellis what do you see on `dotnet --version` or `dotnet --list-sdks`
<img width="516" alt="dotnet-fail" src="https://user-images.githubusercontent.com/107371491/193647200-10eca47c-7fed-4382-9de8-ba9b6103cc6b.png">

**Comment by pratikkabade** [comment]
So, the problem is you don't have dotnet installed
First of all install that from dotnet website then restart the process

**Comment by jooshellis** [comment]
> So, the problem is you don't have dotnet installed First of all install that from dotnet website then restart the process

done that a million times

**Comment by jooshellis** [comment]
> Tell me your steps like exactly how are you installing it


https://user-images.githubusercontent.com/107371491/193649920-63953729-52e6-44b7-b5cd-37db70b5485e.mov

**Comment by pratikkabade** [comment]
You've just installed ask what about runtime?
Have you installed that too?

**Comment by pratikkabade** [comment]
Try this command for installing it 
`brew install dotnet`

**Comment by jooshellis** [comment]
> 
This command worked. Thank you very much!

**Comment by pratikkabade** [comment]
Happy to help!

**Comment by Ramu-Bhukya** [comment]
I am also getting the same issue to solve this problem.

bhukya-MacBook-Pro-2:~ salavath$ brew install dotnet
==> Downloading https://download.visualstudio.microsoft.com/download/pr/d3fe77e7-
Already downloaded: /Users/salavath/Library/Caches/Homebrew/downloads/668c228bb267566e1f462ea3abec23890b7c2b9e3ab8bcb2635c7e233a660f51--dotnet-runtime-6.0.9-osx-x64.pkg
Error: macOS Mojave or newer is required for this software.
bhukya-MacBook-Pro-2:~ salavath$ dotnet --version
-bash: dotnet: command not found
bhukya-MacBook-Pro-2:~ salavath$ dotnet --version
-bash: dotnet: command not found
bhukya-MacBook-Pro-2:~ salavath$ dotnet --list-sdks
-bash: dotnet: command not found
bhukya-MacBook-Pro-2:~ salavath$ dotnet
-bash: dotnet: command not found.

**Comment by Ramu-Bhukya** [comment]
![Screen Shot 2022-10-15 at 10 31 34 PM](https://user-images.githubusercontent.com/96159593/195999170-f0ae1aa9-55cd-47ee-8399-cec90dacc852.png)

**Comment by pratikkabade** [comment]
You already have .net installed on your Mac there's no need to do it again.

Type 
```
dotnet --version
``` 
to confirm installation and you're good to go

**Comment by Ramu-Bhukya** [comment]
Now it works thank you!

**Comment by Ramu-Bhukya** [comment]
Hi Sir,



I have a doubt about the installation of Microsoft visual studio.


Visual Studio for Mac requires macOS 10.15 or higher to run. Your machine
is on unsupported version 10.13.6. Please update your OS to continue the
installation.




Thank you,'

Bhukya

**Comment by pratikkabade** [comment]
You've to update your Mac OS as per you statement. 

By the way if you're new to dotnet instead of using **visual studio**, I'd suggest you use **VS Code **
