### ISSUE TITLE
HttpClient throws WinHttpException

### ISSUE THREAD

**Issue by maltium** [dotnet/core#783]
# HttpClient throws WinHttpException

HttpClient GetAsync(...) fails with the inner exception message `The server returned an invalid or unrecognized response` when requesting https://www.cryptopia.co.nz/api/GetMarkets.

# General

When I retargeted to the .NET 4.5 framework I got a more detailed message `The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF`. The server in question is Microsoft-IIS/10.0.

In the case of .NET 4.5 I got around the issue by add `<httpWebRequest useUnsafeHeaderParsing="true" />` to my `app.config` file. I know of no such option for dotnet core.

This issue is reproducible on dotnet core 2 preview 2 on Windows. Issue not reproducible on Linux and Mac.

**Comment by Petermarcu** [comment]
@davidsh any advice here?

**Comment by davidsh** [comment]
I just tried this myself using .NET Framework 4.7 on a Windows 10 Version 1703 machine.

I don't see any error.  It works fine:

```c#
var client = new HttpClient();
HttpResponseMessage response = client.GetAsync("https://www.cryptopia.co.nz/api/GetMarkets").GetAwaiter().GetResult();
Console.WriteLine($"{(int)response.StatusCode} {response.ReasonPhrase}");
string body = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
Console.WriteLine(body);
```

**Comment by Petermarcu** [comment]
@davidsh how about on .NET Core 2.0?

**Comment by davidsh** [comment]
I also run a quick test building a netcoreapp on the GitHub CoreFx master branch and it also had no errors.

**Comment by maltium** [comment]
I can confirm it's working correctly now. During last week it was failing intermittently, but then early Sunday and the next few days it started failing 100%. These few days it's working normally.

Unfortunately I don't have control over that endpoint. What would be useful information to keep in case I manage to reproduce it again?

**Comment by davidsh** [comment]
Capturing Wireshark traces would be useful.

**Comment by karelz** [comment]
Seems to be resolved. Closing

**Comment by jourdant** [comment]
I have another URL where I encounter this issue.

```
var url = "https://www.waikatoregion.govt.nz/services/regional-services/river-levels-and-rainfall/river-levels-and-flow-latest-reading/";
var client = new HttpClient();
var resp = client.GetAsync(url).Result;
var body = resp.Content.ReadAsStringAsync().Result;
```

How do we do the equivalent of ```<httpWebRequest useUnsafeHeaderParsing="true" />``` on .NET Core 2.0?

**Comment by karelz** [comment]
@jourdant is it 100% repro or intermittent problem?
I don't think WinHttp has `useUnsafeHeaderParsing` setting.

**Comment by jourdant** [comment]
100% repro in this case. The web server is feeding back a malformed set of headers.


On 13/04/2018, at 2:11 AM, Karel Zikmund <notifications@github.com<mailto:notifications@github.com>> wrote:


@jourdant<https://github.com/jourdant> is it 100% repro or intermittent problem?
I don't think WinHttp has useUnsafeHeaderParsing setting.

**Comment by davidsh** [comment]
I tried the code:

```c#
var url = "https://www.waikatoregion.govt.nz/services/regional-services/river-levels-and-rainfall/river-levels-and-flow-latest-reading/";
var client = new HttpClient();
var resp = client.GetAsync(url).Result;
var body = resp.Content.ReadAsStringAsync().Result;
```

and ran this against .NET Core 2.0.  I don't see any errors.  I get back a 200 OK from the server.

**Comment by jourdant** [comment]
I have a fiddler capture I can provide showing what I’m seeing, would they help?

It seems when I run that code using .NET Core 2.0, Content-Length header is missing from the response (and I get the exception). However the same page requested by a browser has the field. I’ve tried getting .NET Core to match the headers exactly on the request,  but still have issues.

Sent from my iPhone

On 13/04/2018, at 3:19 AM, David Shulman <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried the code:

var url = "https://www.waikatoregion.govt.nz/services/regional-services/river-levels-and-rainfall/river-levels-and-flow-latest-reading/";
var client = new HttpClient();
var resp = client.GetAsync(url).Result;
var body = resp.Content.ReadAsStringAsync().Result;

and ran this against .NET Core 2.0. I don't see any errors. I get back a 200 OK from the server.

**Comment by davidsh** [comment]
>I have a fiddler capture I can provide showing what I’m seeing, would they help?

Yes, please post the Fiddler logs. Please post/zip them as binary captures and not simply text output of Fiddler.  Wireshark logs would be useful too.  Does this repro both with and without Fiddler?  Fiddler acts as an HTTP proxy and sometimes that skews repro scenarios.  Wireshark traces are preferred because they don't change the repro scenario.

**Comment by davidsh** [comment]
>It seems when I run that code using .NET Core 2.0, Content-Length header is missing from the response (and I get the exception). However the same page requested by a browser has the field. 

That by itself isn't bad.  Looking at the Fiddler traces, it seems the server is sending back responses using "Transfer-Encoding: chunked" format.  That means there won't be any "Content-Length" response headers.

I don't see anything wrong in the traces right now.  Are you getting an exception when doing HTTP requests?  I wasn't able to repro that.

It would be best for you to open a new bug since this bug is closed and might not have anything to do with the behavior you see.  Please try out the new .NET Core 2.1 Preview 2 and see if you have problems still.

See: https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/
