### ISSUE TITLE
Hi I don't know where I went wrong during the tutorial. Can someone help - i would assume it's straightforward and simple.

### ISSUE THREAD

**Issue by shajuno** [dotnet/core#7833]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![CleanShot 2022-09-27 at 20 01 19](https://user-images.githubusercontent.com/114481809/192496987-ea10d3f8-6160-4a83-b38c-fa44718f0c7c.png)

**Comment by pratikkabade** [comment]
You're not located in the project destination.

Here's a better approach 

In terminal type this to create sample console app
`dotnet new console -o project`

Then move to directory
`cd project`

Then 
`dotnet watch run`
To get live preview

**Comment by michaelgsharp** [comment]
did the steps above resolve the issue?
