### ISSUE TITLE
sdk location an vs code

### ISSUE THREAD

**Issue by Bbakac** [dotnet/core#7836]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

"The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path."
this problem comes out. I haven't figured out. also, although I downloaded the sdk, the file cannot be found on the terminal. and the problem "ln:/usr/local/bin/dotnet:File exists" comes out

**Comment by michaelgsharp** [comment]
Were you able to figure it out? Can you provide all the steps you have tried?
