### ISSUE TITLE
WPF support in .net core 2.0

### ISSUE THREAD

**Issue by dpjain** [dotnet/core#784]
Is there any support for WPF application in .Net Core 2.0 or is it on roadmap?

If no, then what is the other option to make WPF application cross platform?

**Main purpose:**
To make existing WPF application as cross platform(especially for Linux).

**Comment by snikeguo** [comment]
@dpjain https://github.com/AvaloniaUI/Avalonia      look it!

**Comment by Petermarcu** [comment]
@snikeguo gave a good example of a project that is trying to go after that. 

WPF and other desktop UI stacks are out of scope right now in the .NET Core Roadmap:
https://github.com/dotnet/core/issues/43

**Comment by parsalotfy** [comment]
https://github.com/andlabs/libui
and
https://github.com/noliar/DevZH.UI

may help you ;)

**Comment by masums** [comment]
It will be better if Microsoft includes WPF in .Net Core. One language will rule the software world.

**Comment by mwpowellhtx** [comment]
This is a pretty serious oversight, IMO.

**Comment by flybeyond** [comment]
A very good suggestion.  MS need to consider it seriously.
