### ISSUE TITLE
My directory has an issue

### ISSUE THREAD

**Issue by sunnybeatsza** [dotnet/core#7843]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
We are unable to help without any information. Closing for now. If you are still have issues can you please create a new issue and provide more information.
