### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by sunnybeatsza** [dotnet/core#7844]
The problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: Windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\makge\MyApp\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\
Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\
makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs(4,12): error CS0579: Duplica
te 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.As
semblyCompanyAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.As
semblyConfigurationAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.As
semblyFileVersionAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.As
semblyInformationalVersionAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.As
semblyProductAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.As
semblyTitleAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.As
semblyVersionAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'gl
obal::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.Assembly
CompanyAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.Assembly
ConfigurationAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.Assembly
FileVersionAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.Assembly
InformationalVersionAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.Assembly
ProductAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.Assembly
TitleAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]
C:\Users\makge\MyApp\obj\Debug\net6.0\MyApp.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.Assembly
VersionAttribute' attribute [C:\Users\makge\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by michaelgsharp** [comment]
Did that resolve your problem? Closing this issue for now, if you are still have problems please create a new issue or reopen this one and provide what you have tried.
