### ISSUE TITLE
Get "Exited with error code 139. Waiting for a file to change before restarting dotnet..." after dotnet new and dotnet watch

### ISSUE THREAD

**Issue by kunlinyu** [dotnet/core#7847]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: linux

OS: Ubuntu 20.04.4 LTS
dotnet: 6.0.401
command: dotnet new webapp -o MyWebApp --no-https -f net6.0 && cd MyWebApp && dotnet watch
result: 

dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. 
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  MyWebApp -> /home/yukunlin/ws/MyWebApp/bin/Debug/net6.0/MyWebApp.dll
dotnet watch 🚀 Started

dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

**Comment by kunlinyu** [comment]
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /snap/dotnet-sdk/180/sdk/6.0.401/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [/snap/dotnet-sdk/180/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/snap/dotnet-sdk/180/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/snap/dotnet-sdk/180/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by kunlinyu** [comment]
~/ws/MyWebApp$ dotnet watch --verbose
dotnet watch ⌚ Project supports hot reload and was configured to run with the default run-command. Watching with hot-reload
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. 
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
dotnet watch 🚀 Started '/snap/dotnet-sdk/180/dotnet' '' with process id 589219
  Determining projects to restore...
  All projects are up-to-date for restore.
  MyWebApp -> /home/yukunlin/ws/MyWebApp/bin/Debug/net6.0/MyWebApp.dll
dotnet watch ⌚ Process id 589219 ran for 840ms
dotnet watch ⌚ Running MSBuild target 'GenerateWatchList' on '/home/yukunlin/ws/MyWebApp/MyWebApp.csproj'
dotnet watch 🚀 Started '/snap/dotnet-sdk/180/dotnet' '' with process id 589255
dotnet watch ⌚ Process id 589255 ran for 351ms
dotnet watch ⌚ Watching 73 file(s) for changes
dotnet watch ⌚ dotnet-watch is configured to launch a browser on ASP.NET Core application startup.
dotnet watch ⌚ Configuring the app to use browser-refresh middleware.
dotnet watch ⌚ Refresh server running at wss://localhost:36427,ws://localhost:43815.
dotnet watch 🔥 HotReloadProfile: Default.
dotnet watch 🚀 Started '/home/yukunlin/ws/MyWebApp/bin/Debug/net6.0/MyWebApp' '' with process id 589322
dotnet watch ⌚ Running MyWebApp with the following arguments: run
dotnet watch 🚀 Started

dotnet watch ⌚ Process id 589322 ran for 1ms
dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

**Comment by kunlinyu** [comment]
After I reinstall the dotnet sdk and runtime(https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004), the issue dissapear.

The previous installation was been installed by snap.

**Comment by michaelgsharp** [comment]
Glad to hear the issue was resolved. Closing this issue for now.
