### ISSUE TITLE
dotnetcli.azureedge.net is painfully slow

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/core#785]
I'm regularly compiling the .NET core projects for CoreCLR, CoreFX and core-setup for Yocto Linux. Today I was wondering why after 10 minutes, the `init-tools.sh` script from CoreFX was still running. It turns out, that the download speed from `dotnetcli.azureedge.net` is only something around 200 kiB/s and the dotnet-dev package has over 100 MiB:

```
$ wget https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005977/dotnet-dev-linux-x64.2.0.0-preview1-005977.tar.gz
--2017-08-02 16:31:08--  https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005977/dotnet-dev-linux-x64.2.0.0-preview1-005977.tar.gz
Resolving dotnetcli.azureedge.net (dotnetcli.azureedge.net)... 2606:2800:133:206e:1315:22a5:2006:24fd, 93.184.221.200
Connecting to dotnetcli.azureedge.net (dotnetcli.azureedge.net)|2606:2800:133:206e:1315:22a5:2006:24fd|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 124040795 (118M) [application/octet-stream]
Saving to: ‘dotnet-dev-linux-x64.2.0.0-preview1-005977.tar.gz.1’

dotnet-dev-linux-x64.2.0.0-preview1-005977.tar.gz.1    3%[=>               ]   3.83M   160KB/s    eta 8m 28s
```

My feeling is that things have turned worse recently.

**Comment by Petermarcu** [comment]
I've sent an email to our infrastructure team to see if they can figure out whats going on.

**Comment by chcosta** [comment]
I'll make sure we are tracking this internally and get someone investigating this.  Thanks for reporting this potential problem.

**Comment by jcagme** [comment]
@Tragetaschen thanks for reporting. 

When checking our CDN I found some latency spikes from 9PM to 7AM PST. This is when you ran init-tools.sh and tried downloading the package. I tried on my end a hour back and the package was downloaded in no time.

Also, there was am Azure network infra outage in the Asia-Pacific region. This might also affect the download time.

Are you still experiencing the same?

**Comment by Tragetaschen** [comment]
I just realized I forgot to mention my connection type: It's a German T-Online VDSL with 100MBit/s downstream. I can regularly get to 11 MiB/s download speeds.

I tested it just now with mixed results. The speed varies between the full 11MiBs and sometimes goes down to 1 MiB/s during just one download. I had one run (starting at 07:41:12 UTC) that resulted in an average of 979KiB/s going to as low as 450 KiB/s.

**Comment by jcagme** [comment]
I see there was again a rise in latency that began at 2:57AM UTC today and looks like it started getting better at 12PM UTC. I've opened an Azure support ticket to get some help on their side to get things squared out. As soon as I hear back from them I update this issue.

**Comment by jcagme** [comment]
@Tragetaschen Azure support guys have asked to ask you to run the same wget command but with -S -O NUL (wget -S -O NUL [URL]) so we get more details on the request. Also, are you using some sort of VPN? In your logs 93.184.221.200 is located in Central US and not in Germany.

Please post the output here so I can send it to the support folks.

**Comment by Tragetaschen** [comment]
@jcagme The IPv4 address is the one from `dotnetcli.azureedge.net` as well as the IPv6 address:
```
$ host dotnetcli.azureedge.net
dotnetcli.azureedge.net is an alias for dotnetcli.ec.azureedge.net.
dotnetcli.ec.azureedge.net is an alias for cs9.wpc.v0cdn.net.
cs9.wpc.v0cdn.net has address 93.184.221.200
cs9.wpc.v0cdn.net has IPv6 address 2606:2800:133:206e:1315:22a5:2006:24fd
```
As you can see, wget chooses the IPv6 connection

Here's the output with the additional parameters: It again started with the full bandwidth and then broke down to below 600 KiB/s. I've taken the liberty to replace `NUL` by `/dev/null`

```
wget -S -O /dev/null https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005899/dotnet-dev-linux-x64.2.0.0-preview1-005899.tar.gz
--2017-08-07 13:05:10--  https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005899/dotnet-dev-linux-x64.2.0.0-preview1-005899.tar.gz
Resolving dotnetcli.azureedge.net (dotnetcli.azureedge.net)... 2606:2800:133:206e:1315:22a5:2006:24fd, 93.184.221.200
Connecting to dotnetcli.azureedge.net (dotnetcli.azureedge.net)|2606:2800:133:206e:1315:22a5:2006:24fd|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Accept-Ranges: bytes
  Content-Type: application/octet-stream
  Date: Mon, 07 Aug 2017 11:05:11 GMT
  Etag: 0x8D48E7FA37E89AC
  Last-Modified: Fri, 28 Apr 2017 21:43:42 GMT
  Server: ECAcc (arn/458A)
  X-Cache: HIT
  x-ms-blob-type: BlockBlob
  x-ms-lease-status: unlocked
  x-ms-request-id: f06a610a-0001-00d1-116c-0fdbda000000
  x-ms-version: 2009-09-19
  Content-Length: 94172246
Length: 94172246 (90M) [application/octet-stream]
Saving to: ‘/dev/null’

/dev/null                     100%[===============================================>]  89.81M   782KB/s    in 59s

2017-08-07 13:06:10 (1.51 MB/s) - ‘/dev/null’ saved [94172246/94172246]
```

**Comment by Tragetaschen** [comment]
Bingo:

When I force wget to use IPv4 with a `-4` parameter, the download is always fast. Only running via IPv6 is slow (without parameter or `-6`). I've checked back and forth and the correlation is very, very high.

```
$ wget -4 -S -O /dev/null https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005899/dotnet-dev-linux-x64.2.0.0-preview1-005899.tar.gz
--2017-08-07 13:11:13--  https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005899/dotnet-dev-linux-x64.2.0.0-preview1-005899.tar.gz
Resolving dotnetcli.azureedge.net (dotnetcli.azureedge.net)... 93.184.221.200
Connecting to dotnetcli.azureedge.net (dotnetcli.azureedge.net)|93.184.221.200|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Accept-Ranges: bytes
  Content-Type: application/octet-stream
  Date: Mon, 07 Aug 2017 11:11:13 GMT
  Etag: 0x8D48E7FA37E89AC
  Last-Modified: Fri, 28 Apr 2017 21:43:42 GMT
  Server: ECAcc (frc/8F8E)
  X-Cache: HIT
  x-ms-blob-type: BlockBlob
  x-ms-lease-status: unlocked
  x-ms-request-id: 54fdeddd-0001-00aa-529f-0bb06a000000
  x-ms-version: 2009-09-19
  Content-Length: 94172246
Length: 94172246 (90M) [application/octet-stream]
Saving to: ‘/dev/null’

/dev/null                     100%[===============================================>]  89.81M  10.2MB/s    in 9.4s

2017-08-07 13:11:23 (9.58 MB/s) - ‘/dev/null’ saved [94172246/94172246]
```

**Comment by Tragetaschen** [comment]
I had reported a similar bandwidth problem against the Visual Studio 2017 installer. The behavior there is extremely comparable to this issue:

https://developercommunity.visualstudio.com/content/problem/88440/the-installer-doesnt-use-the-available-download-ba.html

**Comment by jcagme** [comment]
Interesting. I don't know where the VS installer is hosted but it might be related. I'll pass all your report information to the Azure support folks.

Thanks for the detailed information!

**Comment by jcagme** [comment]
@Tragetaschen Azure Support found that the content is being served from Verizon's POP server cache so they've opened a ticket on them. I'll keep this issue up to date as they update the ticket.

**Comment by jcagme** [comment]
@Tragetaschen Verizon support just replied and asked if you could copy-paste the following and after waiting some time provide the output of the page please. The URL is: http://wpc.366F4.kappacdn.net/002DCC/nc/headers.html?url=http://wpc.366F4.kappacdn.net/crossdomain.xml&req=HEAD

**Comment by Tragetaschen** [comment]
Hmm, there's a slight problem: On my Linux (server) box with wget, there's no way to run the JavaScript embedded on `headers.html`. I've instead put the URL into Edge on my Windows box. Below is the Select-All+Copy from the page as well as an image.

```

END USER IP:     USER INFO: Browser CodeName: MozillaBrowser Name: NetscapeBrowser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063Cookies Enabled: truePlatform: Win32User-agent header: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063REQUEST: URL:  http://wpc.366F4.kappacdn.net/crossdomain.xmlMethod: HEADTime: 0.012 secondsHTTP Status: 200 RES. HEADERS::Accept-Ranges: bytes Content-Type: text/xml Date: Tue, 08 Aug 2017 07:28:38 GMT Last-Modified: Thu, 27 Jul 2017 12:40:13 GMT Server: ECAcc (frc/8F52) Content-Length: 329 |  
-- | --
 

```
![image](https://user-images.githubusercontent.com/1947968/29061190-19f6101c-7c1d-11e7-9c09-176210e50449.png)

**Comment by jcagme** [comment]
Thanks, details have been shared with Verizon support.

**Comment by Tragetaschen** [comment]
Just as a point of interest: I disabled IPv6 on Windows and then ran the Visual Studio installer. This gave me back the full download bandwidth.

**Comment by jcagme** [comment]
Good to know there are workarounds this problem!

Verizon folks reported they haven't found an issue neither their tests nor with the data you have provided and asked that if you are still hitting this issue if you could kindly provide the output of running mtr against the CDN url. With this we can pinpoint if and where there might be an slow hop in the middle or something. For more information about mtr please check: https://www.digitalocean.com/community/tutorials/how-to-use-traceroute-and-mtr-to-diagnose-network-issues

**Comment by Tragetaschen** [comment]
Yes, still hitting. I tried it first thing this morning and immediately got an average of <1Mb/s with lows in the 400 kb/s range.

Here's some mtr output:
```
                                       My traceroute  [v0.86]
native-linux (::)                                                           Thu Aug 10 09:47:45 2017
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                            Packets               Pings
 Host                                                     Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. fritz.box                                              4.0%   631    5.0   6.1   0.6  81.6   6.5
    p200300C513BF05F40000000000000001.dip0.t-ipconnect.de
 2. p200300C513BF05F40000000000000001.dip0.t-ipconnect.de  4.8%   631    5.0   9.1   4.7  93.3  10.9
 3. ???
 4. 2003:0:fc03:4005::2                                    4.4%   630   35.0  36.8  34.5 153.6   9.8
 5. 2606:2800:133:206e:1315:22a5:2006:24fd                 0.0%   630   30.6  31.6  30.3  96.9   5.0
```
There's a rather high packet loss percentage, but these don't happen continuously but in bursts.

**Comment by Tragetaschen** [comment]
The bursts also appear in the IPv4 version:

```
                                       My traceroute  [v0.86]
native-linux (0.0.0.0)                                                      Thu Aug 10 09:53:32 2017
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                            Packets               Pings
 Host                                                     Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. fritz.box                                              5.7%   333    4.9   6.4   0.4  79.9   9.1
    62.155.244.139
 2. 62.155.244.139                                         5.1%   333    4.9   7.0   4.5  76.7   8.8
 3. 217.5.118.26                                           4.8%   333   10.2  10.5   9.5  45.3   3.0
 4. 80.156.163.94                                          5.1%   333   10.3  11.6   9.5  94.7   6.7
 5. 152.195.100.129                                        5.1%   333   10.2  14.5   9.6 101.1   8.5
 6. 93.184.221.200                                         0.3%   333    9.0   9.5   8.7  58.8   3.5
```

**Comment by jcagme** [comment]
Thanks. I've sent this output to the Verizon folks. 

Just as a side question, this happens in all your machines, all under the same network connection? Have you tried different network/machines?

**Comment by jcagme** [comment]
Looks like Verizon still is not finding anything noticeable from the traces and asked if you could share your public IP so they can run an inverse MTR. Feel free to send it to my profile email. Also, I was thinking in adding you to the ongoing email thread with them so the link is "direct" and I am not playing a proxy role :)

**Comment by Tragetaschen** [comment]
If Verizon is fine with that (I'm not the one with the contract) I'm perfectly fine with it. However:

This morning, nothing reproduces. Everything is as fast as it should be.

**Comment by jcagme** [comment]
I'd check tomorrow and see whether the slow behavior repros or not and then we can decide if we want to follow up or close this issue.

**Comment by Tragetaschen** [comment]
Still wonderful. Also, downloading/installing VS 15.3 was a real pleasure.

I'm rather curious what happened, but I wouldn't want to consume more of your time than I already have. Let's just assume this here resulted is someone finding some faulty/misconfigured hardware somewhere and close the issue.

Thanks for all your time and effort!
