### ISSUE TITLE
Continuous Loop using Windows 10

### ISSUE THREAD

**Issue by Chriscross129** [dotnet/core#7853]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
We are unable to help you without more information. If you are still having problems please create a new issue and provide more information.
