### ISSUE TITLE
COnfiguring sdk for c#

### ISSUE THREAD

**Issue by laricom2205** [dotnet/core#7856]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
command 'dotnet' is not valid c#

**Comment by pratikkabade** [comment]
`dotnet` is not installed
Install it from their official website and try again

**Comment by michaelgsharp** [comment]
And once you have it installed make sure you restart your terminal.

Closing as this will solve the issue.
