### ISSUE TITLE
Dotnet is not recognized in command prompt

### ISSUE THREAD

**Issue by kellyreyes21** [dotnet/core#7859]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Downloaded the DOTNET 6 and got an error in the command prompt. Next steps?

**Comment by michaelgsharp** [comment]
Did you restart the terminal after doing the install?

**Comment by kellyreyes21** [comment]
Yes I restarted it several times and it gave me the same output

**Comment by kellyreyes21** [comment]
I have an HP Pavillion 360x laptop. Downloaded the correct link for windows. Not sure what went wrong?

**Comment by pratikkabade** [comment]
Try reinstalling.

Then confirm installation by this command

```
dotnet --version 
```

**Comment by mairaw** [comment]
This might be an issue with PATH.

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
