### ISSUE TITLE
PreBuildEvent Use Macros Parameter On Linux Is Not Working Properly

### ISSUE THREAD

**Issue by baiyunchen** [dotnet/core#786]
.NET Core version:***2.0.0-preview2-006497***
operating system:***CentOS***
When I use PreBuildEvent to execute some commands, the path in Macros does not seem to work properly in Linux.
My command is: `dotnet  $(SolutionDir)tools/copyfiles/CopyFiles.dll  "$(SolutionDir)src/Infrastructures/DbScript" "*.config" "Configuration/Data"`

It can work in Windows VS, but in Linux will be thrown 
```
No executable found matching command "dotnet-tools/copyfiles/CopyFiles.dll"
/opt/dotnet/sdk/2.0.0-preview2-006497/Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: The command "dotnet tools/copyfiles/CopyFiles.dll "src/Infrastructures/DbScript" "*.config" "Configuration/Data"" exited with code 1. [/usr/gitlab/builds/bee2a437/0/xxx/src/XXX.csproj]
```
I tried to manually find the root directory of the solution implementation
```
dotnet  $(SolutionDir)tools/copyfiles/CopyFiles.dll  "$(SolutionDir)src/Infrastructures/DbScript" "*.config" "Configuration/Data"
```
It looks `$(SolutionDir)` is not working properly.

**Comment by Petermarcu** [comment]
Thanks for the report. I've moved this to https://github.com/Microsoft/msbuild/issues/2397
