### ISSUE TITLE
erreur lié au navigateur

### ISSUE THREAD

**Issue by sidibewende** [dotnet/core#7860]
une erreur de navigateur quand j'execute mon projet dotnet blazor . j'utilise windows 10

l'errur lors de l'execution du projet  est :
"Votre connexion n'est pas privée
Des individus malveillants tentent peut-être de subtiliser vos informations personnelles sur le site localhost (mots de passe, messages ou numéros de carte de crédit, par exemple). [En savoir plus](chrome-error://chromewebdata/#)"

**Comment by greenEkatherine** [comment]
> a browser error when I run my dotnet blazor project. I use windows 10
> 
> the error when running the project is:
> "Your connection is not private.
> Malicious individuals may be trying to steal your personal information from the localhost site (passwords, messages or credit card numbers, for example). Learn more"

It looks like the issue with certificate. @adityamandaleeka do you know who can help with blazor?

**Comment by sebastienros** [comment]
@sidibewende le certificat the developpement semble ne pas etre "de confience". Vous pouvez le configurer en suivant cette documentation: https://learn.microsoft.com/fr-fr/dotnet/core/tools/dotnet-dev-certs

Danas le pire des cas, comme il s'agit d'une navigation locale vous pouvez tout aussi bien ignorer le message.

**Comment by mairaw** [comment]
@sidibewende let us know if that helps
