### ISSUE TITLE
dotnet run --project xxx cannot load appsetting.json file

### ISSUE THREAD

**Issue by github-amazingboy** [dotnet/core#7861]
### Description
when i use vscode, run command:

```dotnet run --project .\src\HelloABP.DbMigrator\```

the above command cannot load the project HelloABP.DbMigrator's appsettings.json

the below command can work well
```
cd .\src\HelloABP.DbMigrator 
dotnet run
```
why not auto load the project's appsetting.json? it is confused.

**Comment by greenEkatherine** [comment]
@mairaw could you please help, do we have a parameter to set up the path to appsettings.json?

**Comment by mairaw** [comment]
@baronfel @danroth27 do you what's the difference between running the commands that way?

**Comment by baronfel** [comment]
There _shouldn't_ be one - this may indicate a bug in the SDK. @greenEkatherine can you run your command with higher verbosity (`-v n` should be enough)? That should get us a bit more information about the discovery of your runsettings.

**Comment by danroth27** [comment]
@Tratcher What logic do we use to find the appsettings.json file by default?

**Comment by baronfel** [comment]
@danroth27 the core of it is [here](https://github.com/dotnet/sdk/blob/f8c661ab9c8e51587cfb1edb97d2f7d81453b03a/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L127-L141) - given the project in question, we use the language to pivot on the required folder structure and look for a launchSettings.json file in the appropriate subfolder.

**Comment by Tratcher** [comment]
We look in the content root. I just tried this and it worked fine. My net6.0 app was able to locate both the launch settings and appsettings.json.

**Comment by greenEkatherine** [comment]
> There _shouldn't_ be one - this may indicate a bug in the SDK. @greenEkatherine Katya Sokolova FTE can you run your command with higher verbosity (`-v n` should be enough)? That should get us a bit more information about the discovery of your runsettings.

cc @github-amazingboy
