### ISSUE TITLE
.NET October 2022 Update - .NET 6.0.10 and .NET Core 3.1.30

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7864]
Release Notes
[6.0.10](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.10/6.0.10.md)
[3.1.30](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.30/3.1.30.md)

Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

Distro | 6.0.10 | 3.1.30
-- | -- | -- 
Ubuntu 18.04 |✅|✅
Ubuntu 20.04 |✅ |✅
Ubuntu 22.04 | |
Centos 7 |✅ |✅
Debian 10 |✅ |✅
Debian 11 |✅ |✅
Fedora 35 |✅ |✅
Fedora 36 |✅|✅
OpenSUSE 15|✅ |✅
Oracle|✅ |✅

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

Known Issues

If there are any more issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by dcermak** [comment]
The .Net rpm repositories for [openSUSE](https://packages.microsoft.com/opensuse/15/prod/) and [SLES](https://packages.microsoft.com/sles/15/prod/) are lacking the upgrade to 6.0.10 for aarch64. Could you please publish that one as well?

**Comment by dcwhittaker** [comment]
Closed in favor of https://github.com/dotnet/core/issues/7941
