### ISSUE TITLE
dotnet is not found

### ISSUE THREAD

**Issue by olyamoskvina** [dotnet/core#7869]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @olyamoskvina! I'm sorry to hear you're running into issues. What kind of mac do you have? Which version did you install?

**Comment by olyamoskvina** [comment]
Hello.
macbook air 2020 m1
type «dotnet» in terminal but i see that command not found.
please to help me

**Comment by mairaw** [comment]
Did you install the arm64 version?

**Comment by olyamoskvina** [comment]
No, I didn't.
My tutor said me that the version x64 is better for mac m1. Isn’t it right?

Ср, 12 окт. 2022 г. в 20:26, Maira Wenzel ***@***.***>:

**Comment by olyamoskvina** [comment]
Should I install arm64?

Ср, 12 окт. 2022 г. в 20:37, Ольга Москвина ***@***.***>:

**Comment by mairaw** [comment]
Yes, M1 is an arm64 system, so installing it should make dotnet start working. Let us know how it goes.

**Comment by olyamoskvina** [comment]
Maria, hello!
Everything is good, I can finally use it, thank u!
Let me know, please, can I contact u if there are any problems later? Or
will I have to create a new issue request on GutHub?

Ср, 12 окт. 2022 г. в 21:08, Maira Wenzel ***@***.***>:

**Comment by mairaw** [comment]
I'm glad you got it working! Yes, open a new issue and someone from the team can help you.
