### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by bburch1985** [dotnet/core#7871]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: Linux (Ubuntu 22.04.1 LTS)

I am very new to programming and was trying to follow the tutorial on the above page for C# when I received an error message in the console "segmentation fault (core dumped)", and it couldn't find the file/directory...

MyComputer:~ $ dotnet new console -o MyApp -f net6.0
Segmentation fault (core dumped)
MyComputer:~ $ cd MyApp
bash: cd: MyApp: No such file or directory

**Comment by mairaw** [comment]
HI @bburch1985. Sorry to hear you're having issues.
Did you install using snap by any chance?
