### ISSUE TITLE
Can't run the tutorial

### ISSUE THREAD

**Issue by ReduceRightDave** [dotnet/core#7872]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: Ubuntu 20.04.5 LTS

On running `dotnet watch` I get error code 139:
```
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. 
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  BlazorApp -> /home/davec/code-projects/BlazorApp/bin/Debug/net6.0/BlazorApp.dll
dotnet watch 🚀 Started

dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

```

dotnet was installed with Snap via [these instructions](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap). 

`dotnet --list-sdks` gives 
`6.0.402 [/snap/dotnet-sdk/183/sdk]`

`dotnet --list-runtimes` gives
```
Microsoft.AspNetCore.App 6.0.10 [/snap/dotnet-sdk/183/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.10 [/snap/dotnet-sdk/183/shared/Microsoft.NETCore.App]
```

**Comment by omajid** [comment]
dotnet tools are likely to be broken if dotnet was installed via snap. We are in the process of fixing our docs to warn for this: https://github.com/dotnet/docs/pull/31045.

Can you try installing .NET using another mechanism?
