### ISSUE TITLE
installing .net 

### ISSUE THREAD

**Issue by soniyasukasi** [dotnet/core#7876]
![dot net](https://user-images.githubusercontent.com/105932288/195821004-42e54096-b32e-4db3-93fc-ce913f92ba25.jpg)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
i have installed the .net but after installing checking in comand promt that it was installed or not it was showing an error on command prompt
![dot net](https://user-images.githubusercontent.com/105932288/195821283-14014624-1abc-41b9-8330-ebbbc27bda38.jpg)

**Comment by greenEkatherine** [comment]
Did you open a new window? If it doesn't help, please try to reinstall dotnet

**Comment by mairaw** [comment]
This might be an issue with PATH as well.

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
