### ISSUE TITLE
-f net6.0

### ISSUE THREAD

**Issue by mario-cp** [dotnet/core#7878]
Error: Invalid parameter(s):
-f net6.0
    'net6.0' is not a valid value for -f (Framework).

**Comment by mairaw** [comment]
@mario-cp it looks like you don't have .NET 6 installed. What `dotnet --info` returns?

**Comment by mario-cp** [comment]
`dotnet --version
3.1.424`

`dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.30
Microsoft.NETCore.App 3.1.30`

`dotnet --list-sdks
3.1.424`

**Comment by pratikkabade** [comment]
So you can see you've `dotnet 3` installed on your device and not `dotnet 6` install the **dotnet 6** from the _official website_ and retry it will fix your version issue
