### ISSUE TITLE
CTRL+C issue with dotnet 7 RC2

### ISSUE THREAD

**Issue by titanix** [dotnet/core#7880]
I'm (more exactly was) running different versions of .net 7 from the preview 2 to the RC 2 and I noticed really strange behavior with RC 2, to the point I had to use global.json to force the use of 6.0 SDK, and now even remove the 7 SDK.

I'm working on a Mac with M1 Pro mostly with command line executables. It happened for the second time already that after cancelling execution of a running program with CTRL+C in a terminal, the SDK broke. The behavior is that `dotnet build` will fails, without displaying any errors. This is not only happening in the project that was interrupted, but in other unrelated folders as well.

It is not happening everytime, because I was able to make a first CTRL+C without issue, while a second during the next run broke the SDK. It already happened once in another project.

**Comment by rainersigwald** [comment]
Can you please try setting the environment variable `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER=1`? That has worked for others https://github.com/dotnet/core/issues/7840#issuecomment-1273569523, and if it works for you the GA release will resolve the issue.

cc @rokonec

**Comment by titanix** [comment]
Sorry I can't. I removed all .net 7.0 preview sdks because I need a working build system to work on my research. It's great if the problem was already spotted on will be fixed for the release, which was the point of creating this issue!

**Comment by rokonec** [comment]
@titanix It most like is known issues which shall be resolved is GA. If not, please let is know.
Thanks a lot for reporting it.
