### ISSUE TITLE
appsetting.json doesn't appear

### ISSUE THREAD

**Issue by HansBoos** [dotnet/core#7884]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by HansBoos** [comment]
Don't know if this an issue, but appsetting.json does not appear in my solution folder

**Comment by greenEkatherine** [comment]
@HansBoos can you run the solution? `appsetting.json` is not mentioned among the created files so it seems that it is not mandatory. @mairaw could you please confirm?

**Comment by pratikkabade** [comment]
@HansBoos which version of `dotnet` have you installed?
Make sure it's **5.0** or **above**

**Comment by mairaw** [comment]
We don't list all files on the tutorial but appsettings.json is supposed to be part of the project. What version of ,NET and VS are you using?

**Comment by mairaw** [comment]
Adding @danroth27 as well to see if he has any ideas

**Comment by danroth27** [comment]
The appsettings.json file should be created as part of the project template:

![image](https://user-images.githubusercontent.com/1874516/196741488-8b1216bb-bdd7-4f75-b951-9e81ded19c99.png)

Daniel Roth
