### ISSUE TITLE
Dotnet not recognized in command prompt

### ISSUE THREAD

**Issue by AutomatJsr** [dotnet/core#7888]
![dotnet runtime not working](https://user-images.githubusercontent.com/48239537/196436476-69de6dfa-5e68-4c8b-a683-15acdf7ab2b1.jpg)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you open a new terminal window after installing the SDK?

**Comment by AutomatJsr** [comment]
Yes I used the command prompt as suggested on website

**Comment by mairaw** [comment]
Check this doc to see if you see dotnet on the expected install folders:
https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows#check-for-install-folders

Also, which version did you install? Does that match your windows architecture?
