### ISSUE TITLE
Exception when serialize class contains Dictionary and DateTimeOffset via DataContractSerializer

### ISSUE THREAD

**Issue by jiemon** [dotnet/core#789]
I try serialize via DataContractSerializer simple class by example:
```
public class SimpleExampleClass2
		{
			private Dictionary<string, string> _attributes1;
			public Dictionary<string, string> Attributes1 => _attributes1;
			public DateTimeOffset TestDate { get; set; }
		}
```
Serialization code:
```
var test = new SimpleExampleClass2() { TestDate = DateTimeOffset.Now };
			var ser = new DataContractSerializer(typeof(SimpleExampleClass2));
			MemoryStream memoryStream = new MemoryStream();
			ser.WriteObject(memoryStream, test);
			memoryStream.Seek(0, SeekOrigin.Begin);
			return File(memoryStream, "application/xml", $"test.xml");
```

But on line "ser.WriteObject(memoryStream, test)" I get exception:

> InvalidDataContractException: Type 'System.Runtime.Serialization.DateTimeOffsetAdapter' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. If the type is a collection, consider marking it with the CollectionDataContractAttribute. See the Microsoft .NET Framework documentation for other supported types.

Is this bug in DataContractSerializer?

**Comment by Petermarcu** [comment]
@zhenlan @ViktorHofer @danmosemsft

**Comment by ViktorHofer** [comment]
It's not related to binary serialization with BinaryFormatter.

**Comment by Petermarcu** [comment]
@zhenlan Any thoughts?

**Comment by zhenlan** [comment]
+ @shmao

**Comment by shmao** [comment]
Issue moved to [dotnet/corefx #22965](https://github.com/dotnet/corefx/issues/22965) via [**ZenHub**](https://www.zenhub.com/)
