### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Yoppaii** [dotnet/core#7891]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Creating this template will make changes to existing files:
  Overwrite   ./wwwroot/lib/jquery/dist/jquery.js
  Overwrite   ./wwwroot/lib/jquery/dist/jquery.min.js
  Overwrite   ./wwwroot/lib/jquery/dist/jquery.min.map
  Overwrite   ./wwwroot/lib/jquery-validation/dist/additional-methods.js
  Overwrite   ./wwwroot/lib/jquery-validation/dist/additional-methods.min.js
  Overwrite   ./wwwroot/lib/jquery-validation/dist/jquery.validate.js
  Overwrite   ./wwwroot/lib/jquery-validation/dist/jquery.validate.min.js
  Overwrite   ./Pages/Shared/_Layout.cshtml
  Overwrite   ./Pages/Shared/_Layout.cshtml.css
  Overwrite   ./Pages/Shared/_ValidationScriptsPartial.cshtml
  Overwrite   ./appsettings.Development.json
  Overwrite   ./wwwroot/css/site.css
  Overwrite   ./appsettings.json
  Overwrite   ./wwwroot/js/site.js
  Overwrite   ./MyWebApp.csproj
  Overwrite   ./Program.cs
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.rtl.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.rtl.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.rtl.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.rtl.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.rtl.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.rtl.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.rtl.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap-utilities.rtl.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.rtl.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.rtl.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.rtl.min.css
  Overwrite   ./wwwroot/lib/bootstrap/dist/css/bootstrap.rtl.min.css.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.min.js
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.min.js.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.esm.js
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.esm.js.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.esm.min.js
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.esm.min.js.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.js
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.js.map
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.min.js
  Overwrite   ./wwwroot/lib/bootstrap/dist/js/bootstrap.min.js.map
  Overwrite   ./Pages/Error.cshtml
  Overwrite   ./Pages/Error.cshtml.cs
  Overwrite   ./Pages/Index.cshtml
  Overwrite   ./Pages/Index.cshtml.cs
  Overwrite   ./Pages/Privacy.cshtml
  Overwrite   ./Pages/Privacy.cshtml.cs
  Overwrite   ./Pages/_ViewImports.cshtml
  Overwrite   ./Pages/_ViewStart.cshtml
  Overwrite   ./wwwroot/lib/bootstrap/LICENSE
  Overwrite   ./Properties/launchSettings.json
  Overwrite   ./wwwroot/lib/jquery/LICENSE.txt
  Overwrite   ./wwwroot/favicon.ico
  Overwrite   ./wwwroot/lib/jquery-validation/LICENSE.md
  Overwrite   ./wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
  Overwrite   ./wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js
  Overwrite   ./wwwroot/lib/jquery-validation-unobtrusive/LICENSE.txt

Rerun the command and pass --force to accept and create.

**Comment by greenEkatherine** [comment]
@Yoppaii it seems that you already created a project and now are trying to overwrite it. If it is on purpose - just follow the instructions and add `--force`, otherwise, try to create a project in the new folder.
