### ISSUE TITLE
NJ Gambu

### ISSUE THREAD

**Issue by Ngwendu** [dotnet/core#7896]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/intro
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I just downloaded: .NET Core 3.1 Desktop Runtime (v3.1.30) - Windows x86 Installer!
I tried to follow "Hello World in 5 minutes tutorial" so that I could learn. 
Then I ran into a problem as displayed below. 

Operating System Version:
Edition	Windows 11 Home Single Language
Version	22H2

Enhxact Error Message:
PS C:\Users\nshak> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandN
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by greenEkatherine** [comment]
@Ngwendu could you please double check that dotnet was installed? You may rerun the installer and check that path to dotnet was added into `PATH` variable. Please let us know if it helps.

**Comment by mairaw** [comment]
Did you open a new terminal after installing it?

I see you installed an x86 version. Are you sure you have an x86 system? Also, why not installing .NET 6 instead? That's the recommended version since .NET Core 3.1 will be out of support pretty soon.

Also, you need to install the SDK if you wanna develop apps.

**Comment by leecow** [comment]
Installing just the runtime (3.1.30) does not enable .NET development. You need to install the .NET SDK. After installing the latest .NET 3.1 SDK, run `dotnet --info` and you should see something like the following. I have a combination of 6.0 and 3.1 installed, which is OK ...

```
PS C:\Users\leecow> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.305
 Commit:    de9a4b2f4b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.305\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.305 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
PS C:\Users\leecow> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.305
 Commit:    de9a4b2f4b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.305\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  6.0.305 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
So, make sure you install the SDK and choose the appropriate architecture. I would assume x64, rather than x86, for most desktop and laptop systems purchased in the last 5 years or so.
