### ISSUE TITLE
"Unhandled Exception" Error

### ISSUE THREAD

**Issue by farah-sm** [dotnet/core#7900]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System
<img width="567" alt="Screenshot 2022-10-26 at 15 04 45" src="https://user-images.githubusercontent.com/65547726/198047677-14ee2a45-3239-4230-a688-5cfe614ba50c.png">
: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Could you provide more details about the project you're trying to run?

**Comment by mairaw** [comment]
This is a simple console app they're trying to create. What kind of mac do you have @farah-sm? Is it a m1 machine? What version of the sdk did you install?
