### ISSUE TITLE
Code language not supported or defined.

### ISSUE THREAD

**Issue by khaledmohd202** [dotnet/core#7901]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Not enough information in the initial report.

**Comment by mairaw** [comment]
@khaledmohd202 can you provide more information? Are you trying to run from VS Code? Do you get the same issue if you do it from the command prompt?
