### ISSUE TITLE
already installed dot net still pooping up 

### ISSUE THREAD

**Issue by garysha06** [dotnet/core#7904]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Not enough information in the initial report.

**Comment by mairaw** [comment]
@garysha06 can you provide the error message you're getting?

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
