### ISSUE TITLE
error 4

### ISSUE THREAD

**Issue by faisal855** [dotnet/core#7906]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
Not enough information in the initial report.

**Comment by mairaw** [comment]
Can you provide more information @faisal855 about the error you're getting?
