### ISSUE TITLE
dotnet command did not work in command prompt . help me,

### ISSUE THREAD

**Issue by Sauvergara1513** [dotnet/core#7907]
Install .NEt 6.0, to be able to use C# in visual studio code, and when using it it generates an error, which says: "Failed to find up to date dodnet cli on the path" and when using the dotnet command in the system prompt, I get returns this: ""dodnet" is not recognized as an internal or external command,
executable program or batch file.
"
please can you help me to solve it, my operating system is windows 10

**Comment by leecow** [comment]
Can you share the output of `dotnet --info`?

This will give us some insight into your environment.
