### ISSUE TITLE
dotnet not recognised after installation

### ISSUE THREAD

**Issue by Aaron-Webb** [dotnet/core#7909]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

installed dotnet sdk 6.0 however dotnet is still not recognised as a command

**Comment by mairaw** [comment]
Hi @Aaron-Webb! I'm sorry to hear you're running into problems.

This might be an issue with PATH.

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
