### ISSUE TITLE
dotnet nuget add source Error

### ISSUE THREAD

**Issue by wf-soft** [dotnet/core#7911]
### Description

"dotnet nuget add source" Unable to execute successfully

### Configuration

.NET 7.0 RC2
Windows 11

### Other information

![image](https://user-images.githubusercontent.com/62228539/198800712-794472fb-5283-4b3a-9355-85ed4d02681e.png)

**Comment by mairaw** [comment]
@nkolev92 can you help with this?

**Comment by nkolev92** [comment]
cc @kartheekp-ms is our hot seat this week. 

I tried quickly replroing it, but no luck: `dotnet nuget add source https://api.nuget.org/v3/index.json --name MyGithub --username wf-soft --password stuff --store-password-in-clear-text`

> Package source with Name: MyGithub added successfully. 

A few questions that'll @kartheekp-ms make progress. 

- Does this repro all the time?
- Have you tried tweaking the command? Does that change it?
- Anyone else running into this issue? Any other machines etc?

**Comment by wf-soft** [comment]
@nkolev92 Then maybe there are other reasons for my failure, maybe it's my local problem, thank you for your answer.
