### ISSUE TITLE
Unable to run NET 6 app on Ubuntu 22.04 without self-contained

### ISSUE THREAD

**Issue by xenoverse-us** [dotnet/core#7913]
### Description
I am having trouble running my NET6 application on Ubuntu 22.04 unless I publish my app with `--self-contained true`

The command I used to publish my .NET 6 app is the following:
`dotnet publish --runtime ubuntu.22.04-x64 --self-contained false --configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber) --output $(Build.ArtifactStagingDirectory)/MyApp'`

In my build pipeline I made sure I have dotnet
```
Tool to install: .NET Core sdk version 6.x.
Found version 6.0.402 in channel 6.0 for user specified version spec: 6.x
Version 6.0.402 was not found in cache.
Getting URL to download .NET Core sdk version: 6.0.402.
...
Successfully installed .NET Core sdk version 6.0.402.
Creating global tool path and pre-pending to PATH.
```

But when I try to run my app on Ubuntu 22.04, I get the following error message.

```
[40954]: You must install or update .NET to run this application.
[40954]: App: /usr/sbin/MyApp/MyApp
[40954]: Architecture: x64
[40954]: Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
[40954]: .NET location: /usr/sbin/MyApp/
[40954]: No frameworks were found.
[40954]: Learn about framework resolution:
[40954]: https://aka.ms/dotnet/app-launch-failed
[40954]: To install missing framework, download:
[40954]: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.22.04-x64
```

When I use `dotnet --info` I see the following which says I have Microsoft.NETCore.App 6.0.10 runtime installed. 

```
root@localhost:~# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.110
 Commit:    ce0a42998a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.110 [/usr/lib/dotnet/dotnet6-6.0.110/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

I think I'm missing something obvious here. I can run it fine with `--self-contained true` but I'd like to figure out what I'm doing wrong.

**Comment by omajid** [comment]
> In my build pipeline I made sure I have dotnet

How are you doing that?

The symptoms feel very similar to https://github.com/dotnet/core/issues/7699; it almost feels like you have multiple .NET installations from different vendors and they are conflicting with each other?

**Comment by xenoverse-us** [comment]
@omajid I meant that my build pipeline has a step to make sure the build machine has .NET 6, here is the exact YAML snippet
```
  - task: UseDotNet@2
    displayName: 'Use .NET 6.x'
    inputs:
      version: 6.x
```

I did not have multiple .NET installations, at least I did not think so. The machine was a fresh clean VM and I followed the guideline here https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu to install the SDK and runtime.

As you can see from above, I have version `6.0.110` installed but the runtime failure says it was looking for `Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)` Does the version need to be an exact match? I thought since I have a later revision installed it should be sufficient for my app to run even if the app somehow tries to find 6.0.0.

**Comment by steveharter** [comment]
cc @NikolaMilosavljevic

**Comment by xenoverse-us** [comment]
@NikolaMilosavljevic Thanks for sharing that. 👍 I skipped that step because I did not install from `packages.microsoft.com` thus think it doesn't apply to me. But I'll follow the advisory page steps to see if I can have it fixed.

**Comment by xenoverse-us** [comment]
Just to report back. I followed the guide to remove all dotnet packages and installed from PMC and it is working fine. Soon after that I've moved to use NET 7. Please consider this issue closed.
