### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by tzx303** [dotnet/core#7914]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @tzx303! We'll need some details about the issues you're encountering.

**Comment by tzx303** [comment]
I have solved the problem
