### ISSUE TITLE
cmd not showing dotnet version

### ISSUE THREAD

**Issue by GhadageNitish** [dotnet/core#7915]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mairaw** [comment]
Hi @GhadageNitish! Did you open a new command prompt after the installation?

**Comment by GhadageNitish** [comment]
Yes.

Now the problem is solved, I have reinstalled it again. Now it is showing
in the cmd.
Thank you

**Comment by mairaw** [comment]
Great to hear. Thanks for letting us know.
