### ISSUE TITLE
No output for the simple hello world console app

### ISSUE THREAD

**Issue by liaoyd16** [dotnet/core#7917]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: ubuntu 20.04

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

terminal command:
```
dotnet new console -o MyApp -f net6.0
dotnet run
```

code: 
```
﻿// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

terminal output: no output
expected output: print "hello world"

**Comment by mairaw** [comment]
Did you get any error message? Can you share a screenshot of what happened?

**Comment by SoundedSquash** [comment]
You need to be in the new project's folder before running. With your first command of dotnet new, you're setting a name of MyApp which creates a folder MyApp to put things in.

`cd MyApp`
then
`dotnet run`

This is documented as the 2nd step on the Create your app page.

**Comment by liaoyd16** [comment]
I did execute `dotnet run` in MyApp/. I found similar case in https://github.com/dotnet/sdk/issues/23616, where dotnet ./bin/Debug/net5.0/MyApp.dll could work.

**Comment by 31ank** [comment]
did you find a solution? Having the same problem atm

**Comment by crizmo** [comment]
> did you find a solution? Having the same problem... I have an application that worked last week but when I tried to start it today with dotnet run I don't have an output. Same behavior if I try to debug it with vscode Running Ubuntu 20.04.5 dotnet --version: 6.0.403
> 
> Creating a new console application with dotnet new console and trying to run it also doesn't work

Facing the same issue , Running dotnet run simply doesnt display any output in the terminal . 
Have you found out any solution for it
