### ISSUE TITLE
It was not possible to find any installed .NET Core SDKs   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:       https://aka.ms/dotnet-download

### ISSUE THREAD

**Issue by bydavide** [dotnet/core#7921]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/83315449/199668731-e549ea5d-8781-451f-851b-7250b83ce887.png)

**Comment by buyaa-n** [comment]
@bydavide could you restart the command line window before running `dotnet new console -o MyApp -f net7.0`

If that doesn't help, please try steps mentioned in: https://github.com/dotnet/core/issues/5962#issuecomment-780084535
