### ISSUE TITLE
problem after installed sdk in window

### ISSUE THREAD

**Issue by jibikilayijonathan** [dotnet/core#7925]
hi everyone!
i got a probleme after installed .net sdk in windows 
someone can help me?
It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
I'm sorry to hear you're running into some problems. Have you open a new command prompt/terminal window after installing? Can you let us know what is your operating system and what does `dotnet --info` returns?
