### ISSUE TITLE
6.0.10 not available in Debian 9 (stretch)

### ISSUE THREAD

**Issue by Breakpoint21** [dotnet/core#7926]
### Description
The Package Sources for Debian 9 do not contain Release 6.0.10 (and also 6.0.9)

after
`sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0`

`dotnet --version`

returns

`6.0.400`

Is Debian 9 no longer supported or did this happen by mistake? 

### Configuration
* Debian 9
* Package sources configured according to https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-9-

**Comment by steveharter** [comment]
cc @rrelyea
cc @nkolev92

**Comment by leecow** [comment]
@Breakpoint21 - Yes, Debian 9 went 'end of life' 7/18/2020 making 6.0.8 the final .NET update that we published. If needed, you can still install [using the tar.gz packages or using the dotnet-install script](https://learn.microsoft.com/en-us/dotnet/core/install/linux#manual-installation), and things will likely continue to work fine. However, this is an unsupported configuration and may stop working in the future.
