### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by patgio5** [dotnet/core#7927]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

C:\Windows\System32>dotnet --info

Host (useful for support):
  Version: 5.0.17
  Commit:  6a98414363

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

If I run the following command I get this error

C:\Windows\System32>dotnet new console -o MyApp -f net6.0
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

C:\Windows\System32>

**Comment by mairaw** [comment]
Hi @patgio5!

`dotnet --info` is showing that there are no SDKs installed. If you're sure you installed, it could be an issue with PATH.

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.

**Comment by patgio5** [comment]
Thanks Maira. With your indications I believe I have solved the
problem. Unfortunately
I'm a bit "rusty" and with WIN11 I still can't move well in his programming
world. Best regards
Patrizio

Il giorno ven 4 nov 2022 alle ore 23:43 Maira Wenzel <
***@***.***> ha scritto:

**Comment by mairaw** [comment]
I'm glad to hear the problem is solved. Good luck with your adventures with the programming world. If you run into any issues, file a new issue and we'll try to help.
