### ISSUE TITLE
I am on dotnet i am a beginner also..i have encountered problem with writing "hello world" in promt. I dont know how to reopen Program.cs ,and plus if i did know how to reopen it ,i would not know with which program i should open it. I have tried and dont know what to do. Please help. Thank you.

### ISSUE THREAD

**Issue by Mickey30065** [dotnet/core#7928]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
HI @Mickey30065!
When you run the `dotnet new` command, it creates a new folder with some files in it. One it's called Program.cs.

You can open that file in a code editor like VS Code or in any text editor like Notepad.

Let me know if this helps or if you need more information about how to get started.
