### ISSUE TITLE
does not run on M1 Mac

### ISSUE THREAD

**Issue by pinakighatak** [dotnet/core#7929]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

the app never ran.

stuck at "dotnet run"

<img width="718" alt="Screenshot 2022-11-05 at 3 11 32 PM" src="https://user-images.githubusercontent.com/57876192/200124046-e96d2795-fb00-4fca-acd6-34f59f1b4ea2.png">

**Comment by mairaw** [comment]
Hi @pinakighatak! I'm sorry to hear you're running into issues.
Did you try more than once? Also, what kind of Mac do you have and which SDK version did you install?
