### ISSUE TITLE
.Net core single file build is generating multiple setting folders with different hashes for each assemblyversion

### ISSUE THREAD

**Issue by kevinvenclovas** [dotnet/core#7930]
Maybe some can help me here:

[https://stackoverflow.com/questions/74332141/net-core-single-file-build-is-generating-multiple-setting-folders-with-differen](https://stackoverflow.com/questions/74332141/net-core-single-file-build-is-generating-multiple-setting-folders-with-differen
)
Im using .Net Core 3.1 and WPF for my project and today i was playing a little bit with the settings.All worked fine. I can save values and i can access this values after restart.

After that im increased my assembly value from 1.0.0.0 to 1.0.0.1 and the settings are gone... I searched many hours to fix this issue but i did not found any solution.

[Keep user's settings after altering assembly/file version](https://stackoverflow.com/questions/23924183/keep-users-settings-after-altering-assembly-file-version/47921377#47921377)

This was a pretty nice solution but this is not working for me. WHY?

Easy to say after every single file build and access to any Setting.Default values my appilcation generates a new setting folder with an new hash.

So i have multiple folders with each one user.config. Without the single file build it works fine. The new assembly version gets generated in the latest folder and i can update ist like the solution above.

Currently i need so setup my app again on eveery new assembly version :/ Someone had the same issue and can help me? Why is my application creating multiple settings folder for each assemblyversion?

.Net Core 3.1
Visual Studio 2022 (17.2.2)

**Comment by steveharter** [comment]
cc @rainersigwald

**Comment by steveharter** [comment]
This looks like a Visual Studio config issue; you'll need to create an issue here: https://developercommunity.visualstudio.com/content/problem/post.html?space=8
