### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Nikhil-coder390** [dotnet/core#7932]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

operating system:- ubuntu(20.04) 
code sample:- dotnet new console -o MyApp -f net6.0
error message:- The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

code sample:- dotnet new console -0 MyApp
error message:- The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by mairaw** [comment]
HI @Nikhil-coder390! Can you run `dotnet --info` to see hwat you have installed? From the message, it appears that only the runtime was installed.

**Comment by Nikhil-coder390** [comment]
code:- dotnet --info



out put:-  global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by mairaw** [comment]
According to this, there are only runtimes installed. How did you install the SDK?

**Comment by Nikhil-coder390** [comment]
In .Net Tutorial website there is a option to download SDK(Install .NET 6 SDK instructions) i opened it then it redirected to install .Net on Linux page there in Microsoft package i selected ubuntu then i went to the process mentioned there

**Comment by mairaw** [comment]
Correct, but that page has several commands, one for installing SDK, one for installing runtime only.
Did you use this one?
https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#install-the-sdk

**Comment by Nikhil-coder390** [comment]
Yes

**Comment by mairaw** [comment]
@leecow any suggestions here?

**Comment by Nikhil-coder390** [comment]
@mairaw thanks for your help... I watched some videos in YouTube and downloaded sdk

**Comment by leecow** [comment]
`/usr/lib/dotnet/dotnet6-6.0.110` is not the install location created by the Microsoft packages. I'm not entirely sure what you have there unless you're installing from the Ubuntu 22.04 ppa. 

Anyway, I think the last comment from @Nikhil-coder390 means you have worked past the problem?

**Comment by Nikhil-coder390** [comment]
@leecow yes it is working now

**Comment by steveharter** [comment]
Closing as resolved

**Comment by MarlonMagalhaesC** [comment]
> @leecowsim esta funcionando agora

As? Tell the solution please

**Comment by MarlonMagalhaesC** [comment]
> @leecowsim esta funcionando agora

@Nikhil-coder390 As? Tell the solution please
