### ISSUE TITLE
botnet download issue

### ISSUE THREAD

**Issue by Norachuuuuuuu** [dotnet/core#7934]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I tried to start dotnet after completing the download but I see
Last login: Mon Nov  7 19:47:31 on ttys000
norachuw@MacBook-Pro-van-Nora ~ % dotnet

zsh: command not found: dotnet
norachuw@MacBook-Pro-van-Nora ~ % 

what did I do wrong? Im just starting and this is all very overwhelminggg

**Comment by steveharter** [comment]
cc @nishanil

**Comment by leecow** [comment]
@Norachuuuuuuu - can you run the following command in your Terminal and let us know the output? This will help us understand the state of your installation. 

`ls -l /usr/local/share/dotnet`

For example, this is what I see on my Mac ...

```
➜ ls -l /usr/local/share/dotnet
total 472
-rw-r--r--   1 root  wheel    1116 Sep 22 13:21 LICENSE.txt
-rw-r--r--   1 root  wheel   86282 Sep 22 13:22 ThirdPartyNotices.txt
-rwxr-xr-x   1 root  wheel  147424 Sep 27 17:08 dotnet
drwxr-xr-x   3 root  wheel      96 Jan 23  2021 host
drwxr-xr-x   6 root  wheel     192 Sep 15 10:30 library-packs
drwxr-xr-x   3 root  wheel      96 Sep 15 10:31 metadata
drwxr-xr-x  73 root  wheel    2336 Sep 15 10:31 packs
drwxr-xr-x   6 root  wheel     192 Oct 20 12:54 sdk
drwxr-xr-x   8 root  wheel     256 Sep 15 10:39 sdk-manifests
drwxr-xr-x   5 root  wheel     160 May  5  2022 shared
drwxr-xr-x   6 root  wheel     192 Sep 15 10:31 template-packs
drwxr-xr-x  15 root  wheel     480 Oct 20 12:54 templates
```

**Comment by Norachuuuuuuu** [comment]
I managed to fix it, I'm just starting off so even really simple things are quite confusing, thank you so much for the support though, it's very comforting to have seeing how complicated this journey is going to be...

**Comment by mairaw** [comment]
Closing this since issue seems to be resolved. Let us know if you need further assistance.
