### ISSUE TITLE
Problem encountered on dotnet.microsoft.com

### ISSUE THREAD

**Issue by asgcdesarrollo** [dotnet/core#7936]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows 10 version 21H2 - Compilacion de SO 19044.2130
>dotnet is not recognized

**Comment by steveharter** [comment]
cc @nishanil

**Comment by mairaw** [comment]
We have removed that tutorial from the site. Please try https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro instead.
