### ISSUE TITLE
Unable to run your project. Ensure you have a runnable project type and ensure 'dotnet run' supports this project. A runnable project should target a runnable TFM (for instance, net5.0) and have OutputType 'Exe'. The current OutputType is 'Library'.

### ISSUE THREAD

**Issue by chandan86605** [dotnet/core#7937]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by chandan86605** [comment]
dotnet version 6.0.402
windows 11

**Comment by steveharter** [comment]
>  exact error message, code sample, and anything else that is relevant.

**Comment by chandan86605** [comment]
problem solved, thank you for your response
