### ISSUE TITLE
.NET 7.0 GA

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7939]
## Release Notes
[7.0.0](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.0/7.0.0.md)

## Status

Asset Type | 7.0.0 | Notes
-- | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ 
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) | ✅ 
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ 
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ 

Please report any issues you find with [.NET 7.0](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7), either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

~~* Linux packages are delayed in publishing for 7.0~~
* .NET 7 availability in Ubuntu package feed is delayed and cannot be accessed via distro package manager at this time. We will provide an update once .NET 7 is available in Ubuntu.
* [[7.0] Projects using certain workloads don't load, build, and or run if .NET 7 Preview SDK workloads are installed](https://github.com/dotnet/core/blob/main/release-notes/7.0/known-issues.md#70-projects-using-certain-workloads-dont-load-build-and-or-run-if-net-7-preview-sdk-workloads-are-installed)

**Comment by mfisher214** [comment]
Hello, I am running into an issue where after updating to .NET 7, my coverlet output path is being ignored

dotnet test command I am using:
dotnet test --no-build --configuration release /p:CollectCoverage=true  /p:CoverletOutput=../CoverageResults/ /p:MergeWith="../CoverageResults/coverage.json" /p:CoverletOutputFormat=\"opencover,json\" -m:1

After updating projects from .NET 6 to .NET 7, the coverage output paths change to the following:

Old: '/home/vsts/work/_temp/coverage/coverage.json'
New: '/home/vsts/work/1/s/tests/dotnet/(project directory)/coverage.json'

This is causing our azure pipeline builds to fail sonar test coverage tollgate because coverage files are not where they are expected to be. Is there something I'm missing here?

**Comment by leecow** [comment]
@marcpopMSFT - any ideas for @mfisher214 [above](https://github.com/dotnet/core/issues/7939#issuecomment-1307817100)?

**Comment by khteh** [comment]
How to install on Ubuntu 22.10?

**Comment by GREsau** [comment]
@mfisher214's problem looks like https://github.com/coverlet-coverage/coverlet/issues/1391 / https://github.com/microsoft/vstest/issues/4014

**Comment by marcpopMSFT** [comment]
@baronfel as I believe 4014 is fixed by https://github.com/dotnet/sdk/pull/27961 which will release in 7.0.101

**Comment by SeanFarrow** [comment]
Good morning,

Has a diff been published between .Net 6 and 7?
There doesn't appear to be anything inthe core repo, so thought I'd ask.

Thanks for a really good release.

Sean.

**Comment by TehNolz** [comment]
Any ETA for the Linux packages?

**Comment by msavara** [comment]
What is the best way to install it on ubuntu 22.04 x64 and arm64? dotnet-install.sh or something else?

**Comment by D4nyi** [comment]
Any update on when will the updates (.NET 6.0.11 and .NET 7.0.X) be available on Ubuntu 22.04 LTS package feed?

**Comment by marcpopMSFT** [comment]
@rbhanda for any updates.

**Comment by dcwhittaker** [comment]
Chatted with @leecow and it looks like our 22.04 repo has the updates. As long as folks follow the guidance in https://github.com/dotnet/core/issues/7699 they should see 7.0.0 and 6.0.11.

**Comment by msavara** [comment]
I don't think so. 
sudo apt-get update
apt-cache search dotnet 
![image](https://user-images.githubusercontent.com/34938369/202849678-a12df1c4-975e-49f6-a00d-983e60801c07.png)

**Comment by EatonZ** [comment]
Where is the API diff between 6.0 and 7.0? I can't seem to find it.

**Comment by MaceWindu** [comment]
@EatonZ  #7976

**Comment by dcwhittaker** [comment]
Closing in favor of https://github.com/dotnet/core/issues/8037
