### ISSUE TITLE
.NET November 2022 Update - .NET 6.0.11 and .NET Core 3.1.31

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#7941]
# .NET November 2022 Update

## Release Notes
* [6.0.11](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.11/6.0.11.md)
* [3.1.31](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.31/3.1.31.md)

## Status

Asset Type | 6.0.11 | 3.1.31 | Notes
-- | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) | ✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ | ✅ 
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) | ✅ | ✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ | ✅ 
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos) | ✅ |  ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ |  ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ |  ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ |  ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ |  ✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse) | ✅ |  ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ |  ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ |  ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | 

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by skyfrk** [comment]
According to the [download page](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.403-windows-x64-installer) of the .NET 6 SDK, the `v6.0.403` SDK is only compatible with Visual Stuido `v17.3`:

![image](https://user-images.githubusercontent.com/27026029/205693200-89f0e28d-14fd-4f09-867d-ccbef0e4a9e0.png)

> Using Visual Studio? This release is only compatible with Visual Studio 2022 (v17.3). Using a different version? See [.NET SDKs for Visual Studio](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks).

Why can't we use the latest version of Visual Studio 2022 (`v17.4.2`) with the latest version of the .NET 6 SDK (`v6.0.403`)?

Context: Our dependency upgrade bot upgraded the `global.json` file of a directory to `v6.0.403` in one of our repositories and I updated Visual Studio to `v17.4.2` on my machine. Now I always have to downgrade the .NET 6 SDK while developing locally...

**Comment by dcwhittaker** [comment]
Closing in favor of https://github.com/dotnet/core/issues/8037

**Comment by mairaw** [comment]
@skyfrk do you mind creating a separate issue for this? I can then follow-up with some folks to see if maybe the language on the site is wrong.

**Comment by skyfrk** [comment]
Where should I open the issue? In this repo? @mairaw

**Comment by mairaw** [comment]
Yes, please @skyfrk
