### ISSUE TITLE
Compiler issues a possible null reference warning

### ISSUE THREAD

**Issue by tr4cks** [dotnet/core#7945]
### Description

I have reproduced a very small code example below. I have warnings telling me that the value can be null but I think it is not possible according to the conditions.
You can see [here](https://stackoverflow.com/questions/74369516/pattern-matching-condition-ensures-neither-property-is-null-but-compiler-issues) for more explaination.

```csharp
Console.WriteLine("Code needed to build the project");

public interface IAbove
{
    string? AboveValue { get; }
}

public interface IBelow : IAbove
{
    string? BelowValue { get; }
}

public class Test
{
    public static void Execute(IAbove above)
    {
        if (above is IBelow { AboveValue: not null, BelowValue: not null } belowTest1)
        {
            // warning CS8602: Dereferencing of a possible null reference
            Console.WriteLine(belowTest1.AboveValue.Length);
            // ok
            Console.WriteLine(belowTest1.BelowValue.Length);
        }
        if (above is not IBelow { AboveValue: not null, BelowValue: not null } belowTest2)
        {
            return;
        }
        // warning CS8602: Dereferencing of a possible null reference
        Console.WriteLine(belowTest2.AboveValue.Length);
        // ok
        Console.WriteLine(belowTest2.BelowValue.Length);
    }
}
```

### Configuration

* .NET 6
* macOS
* M1 ARM
* I don't think it's specific to this configuration

**Comment by steveharter** [comment]
This is a Roslyn issue, please log to https://github.com/dotnet/roslyn/issues

Nullability warnings are not exact when processing control flow.
