### ISSUE TITLE
dotnet new webapp -o MyWebApp --no-https -f net7.0

### ISSUE THREAD

**Issue by anujm007** [dotnet/core#7946]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by leecow** [comment]
@anujm007 - can you provide specific details on the problem you are having?
