### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ahmed23333** [dotnet/core#7947]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

                     dotnet run
C:\Users\mtrky\MyApp\Program.cs(2,36): error CS1525: Invalid expression term '/' [C:\Users\mtrky\MyApp\MyApp.csproj]
C:\Users\mtrky\MyApp\Program.cs(3,7): error CS1002: ; expected [C:\Users\mtrky\MyApp\MyApp.csproj]

on windows 11

The build failed. Fix the build errors and run again.

**Comment by leecow** [comment]
The errors indicate something isn't quite right in your tutorial program. Have a careful look at the instructions and make sure they were followed correctly. You can also copy and paste the code sample.

**Comment by buyaa-n** [comment]
From the build error messages looks like you need to add `;` at the end of row 3.
