### ISSUE TITLE
Changes in Reference project (ProjectB) not reflecting in Referencing Project (ProjectA)

### ISSUE THREAD

**Issue by ranjeetkpGit** [dotnet/core#7956]
Hi,
I have two projects in .net standard 2.0, ProjectA and ProjectB. ProjectA referencing ProjectB.

I am trying to create a nuget package (**using dotnet core 'pack' command in Release pipeline**) of ProjectA.

When I make some changes in ProjectB and package ProjectA with new version, changes are not reflecting in new package.

If I make changes in ProjectB, upgrade package version of both ProjectA and ProjectB and create nuget package for both the projects then it worked.

I don't want to create nuget package for ProjectB

**Comment by steveharter** [comment]
Closing; I see this issue is also in the SDK repo at https://github.com/dotnet/sdk/issues/29019
