### ISSUE TITLE
"Download .NET 5.0" docs page miss info about .NET 5.0 SDK version 5.0.411

### ISSUE THREAD

**Issue by bairog** [dotnet/core#7957]
On [Download .NET 5.0](https://dotnet.microsoft.com/en-us/download/dotnet/5.0) docs page latest described .NET 5.0 SDK vesion for Visual Studio 2019 16.11.x is **5.0.408**. 
I'm using latest Visual Studio 2019 **16.11.18** and is has .NET 5.0 SDK **5.0.411**. 
Add all necessary missing info on that docs page please: when .NET 5.0 SDK **5.0.411** was released, which Visual Studio 2019 version it is included in, which .NET 5.0 Runtimes it has insude, etc.
Thank you.

**Comment by mairaw** [comment]
@dcwhittaker can you check if we’re missing releases on the json files?

**Comment by rbhanda** [comment]
.NET 5.0.408 was the last public SDK. The corresponding values are correct on the website.

**Comment by mairaw** [comment]
So the behavior is by design, so closing the issue,
