### ISSUE TITLE
didnt get hello world

### ISSUE THREAD

**Issue by Pelmenis4** [dotnet/core#7958]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What did you get when you try to run the app?

**Comment by Pelmenis4** [comment]
why

**Comment by mairaw** [comment]
There was no response from you @Pelmenis4 so the issue auto closes. If you provide more information, we can try to help you.
