### ISSUE TITLE
The .NET Core SDK cannot be located

### ISSUE THREAD

**Issue by KshitijThareja** [dotnet/core#7963]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: linux

So I have installed dotnet in my laptop. But when I open a file on vs code, It shows this error.

The .NET Core SDK cannot be located: A valid dotnet installation could not be found. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.
Any idea how to reslove this issue?

My OS is Ubuntu 22.04

**Comment by tayfunuyar** [comment]
Hi @KshitijThareja  
This solution may be help you.  
https://askubuntu.com/questions/1422947/why-dont-any-of-these-methods-work-for-installing-net-core-sdk-runtime-on-22
