### ISSUE TITLE
The "Hello World in 5 minutes" example doesn't work

### ISSUE THREAD

**Issue by RuslanPrimak** [dotnet/core#7965]
The problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: Windows

The example doesn't work properly in the Chrome browser.

![image](https://user-images.githubusercontent.com/4948076/201977194-055dc5d2-4a13-484e-ba61-95f2001cadfb.png)

**Comment by leecow** [comment]
Could you provide additional information? Are you building and running the app from the command line or in another tool? If at the command line, you should see something like ...

```
➜ dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5223
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/leecow/test
```

Once this is running copying `http://localhost:5223` to your browser should take you to a 'Welcome' page.

**Comment by RuslanPrimak** [comment]
Hi,
I did all as described in the tutorial. There is my log:
`C:\Trainings\Dot.Net\Practice\Pr1\MyWebApp>dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  MyWebApp -> C:\Trainings\Dot.Net\Practice\Pr1\MyWebApp\bin\Debug\net7.0\MyWebApp.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5084
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Trainings\Dot.Net\Practice\Pr1\MyWebApp`
And how it looks like:
![image](https://user-images.githubusercontent.com/4948076/202241364-6b9147d2-d1a1-4582-bb94-aeea4e734666.png)

**Comment by mairaw** [comment]
And did you type http or https on the address bar?

**Comment by RuslanPrimak** [comment]
I didn't type anything - the page was opened automatically after executing the "dotnet watch" command.

An additional observation - when I specify the "http://localhost:5084/" address it's automatically changed into the "https://localhost:5084/". And I am unable to use just HTTP.

**Comment by mairaw** [comment]
@danroth27 any suggestions here?

**Comment by danroth27** [comment]
Hmm...that sounds like the project is setup to redirect to HTTPS, but doesn't actually enable HTTPS, so there is nothing to redirect to.

**Comment by danroth27** [comment]
@RuslanPrimak Could you share with us the exact command you ran to create the project? Could you also share the created project with us?

**Comment by RuslanPrimak** [comment]
The command is from the tutorial:
> dotnet new webapp -o MyWebApp --no-https -f net7.0
There is my project:
[MyWebApp.zip](https://github.com/dotnet/core/files/10055778/MyWebApp.zip)

**Comment by danroth27** [comment]
@RuslanPrimak Can you please try running `dotnet clean` form the project directory and then run `dotnet watch` again?

**Comment by danroth27** [comment]
@RuslanPrimak Also, can you check what URL the browser is launching at when your run `dotnet watch`? Is the browser correctly launching at the address that the app is listening on?

**Comment by RuslanPrimak** [comment]
![image](https://user-images.githubusercontent.com/4948076/203304795-9fb5a274-07f3-4082-a5ca-7330f8c840ca.png)
![image](https://user-images.githubusercontent.com/4948076/203305041-08722d9e-199e-4274-9e9a-2895422c925a.png)

In Chrome
![image](https://user-images.githubusercontent.com/4948076/203304991-78916f1d-8a94-4140-b47b-c017e2a4bee6.png)

It seems that the problem is in Chrome. I changed my default browser to FF and it works fine.
Chrome changes http to https automatically. But in the private mode, it also works fine in Chrome. It seems to be a local issue, maybe cache related.

Thank you for your help and patience )
I think the ticket can be closed as invalid.

**Comment by danroth27** [comment]
@RuslanPrimak OK, thanks for your patience as we worked through this issue. Maybe Chrome has a cached redirect for that address. It would be interesting to know if you create a new app with a different port whether you still see the issue. Regardless, I'm going to go ahead and close this issue as this doesn't appear to be a bug on our end. Let us know if there's anything else we can do to help out with your .NET journey!
