### ISSUE TITLE
after typing dotnet run it dosen't do anything

### ISSUE THREAD

**Issue by Ayobami2411** [dotnet/core#7979]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Does it give you an error message? Or what happens?

Can you share a screenshot?
