### ISSUE TITLE
.NET Core Supported OS Lifecycle Policy

### ISSUE THREAD

**Issue by leecow** [dotnet/core#798]
# .NET Core Supported OS Lifecycle Policy

## Summary

.NET Core is supported on a range of operating systems and versions. Each platform has distinct Lifecycles defined by the parent organization. .NET Core support will take these Lifecycle schedules into account when adding or removing versions from the supported list.

## Details

When an OS which is part of the .NET Core supported set releases an update, support for that version will generally be available with the next update to .NET Core. For example Fedora 26 is available and will be supported by .NET Core 2.0. Fedora 27 is scheduled to release in the fall and will be supported by a subsequent update of .NET Core.

'Support' means that .NET Core is built and tested on the OS and Microsoft Developer Support may be contacted for assistance with .NET Core on the environment.

* [.NET Core 2.0 supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md)
* [.NET Core 1.x supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0-supported-os.md)

**Comment by John0King** [comment]
> 'Support' means that .NET Core is built and tested on the OS and Microsoft Developer Support may be contacted for assistance with .NET Core on the environment.
what's the meaning of  `Out of support` in the document ,  Can do run  or  just not officially support.
I'm kind warry about win7 after 2020

**Comment by richlander** [comment]
It means no more free security or quality updates for that version of the product. The installers will still exist as-is.

There is no code in the product that says:

```csharp
if (!isSupported)
{
   throw new OutOfSupportException()
}
```

This makes no comment about OS support, from Microsoft or otherwise. That's outside our wheelhouse.

**Comment by John0King** [comment]
what about new version of  dotnet core ?  Does that mean the new version of dotnet core can no install or run on those OS.  For me I really worry about win7 after 2020 and it still have lots of users 。 Linux is free but windows not.   there are  lots of win xp  users after 2014  and that almost kill .Net (  in China it does  )  ,
 .net is the first language that do not support xp.
I really hope .net's Lifecycle Policy can consider more on users

**Comment by richlander** [comment]
Ah, I understand your point now. Sorry I missed it initially.

The policy is clear ... that we will only provide free support for "in support OSes". 

What actually works in practice is something different. As you suggest, if there are a lot of users on a given out-of-support operating system version, we may choose to keep tests in place for an extended period to avoid breaking users.

**Comment by jogibear9988** [comment]
What about Linux on ARM? (for example RPI)

**Comment by richlander** [comment]
@jogibear9988 See https://github.com/dotnet/announcements/issues/29.

**Comment by Petermarcu** [comment]
Closing as we plan on keeping these open for about 30 days.
