### ISSUE TITLE
Dotnet 7 SDK doesn't show up via --list-sdks nor does the runtime via --list-runtimes

### ISSUE THREAD

**Issue by GrumpyOldGandalf** [dotnet/core#7986]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macOS arm64

I see the .net 6 SDKs and runtimes that were already present before installing the .NET 7 SDK. How do I test specifically for .NET 7?

**Comment by ManickaP** [comment]
You should see it right next to the existing SDKs. 
How did you install it?
Have you tried closing and reopening the terminal after the installation?

**Comment by GrumpyOldGandalf** [comment]
It seems I need to set the PATH to look for it in /usr/local/share/dotnet/x64. The one in /usr/local/share/dotnet does not know about .NET 7, but that’s the location that’s in the PATH by default.

**Comment by ManickaP** [comment]
Related issue https://github.com/dotnet/core/issues/6930 and design doc https://github.com/dotnet/designs/blob/main/accepted/2021/x64-emulation-on-arm64/x64-emulation.md

Seems like you have x64 install on arm64 machine.

**Comment by arnoldpistorius** [comment]
> Related issue #6930 and design doc https://github.com/dotnet/designs/blob/main/accepted/2021/x64-emulation-on-arm64/x64-emulation.md
> 
> Seems like you have x64 install on arm64 machine.

I have exact same behavior on a M1 Macbook Air with the ARM64 installer (dotnet-sdk-7.0.100-osx-arm64.pkg)

**Comment by ManickaP** [comment]
I'm closing this issue, question was answered.
