### ISSUE TITLE
找不到要运行的项目。请确保 C:\Users\Name 中存在项目，或使用 --project 传递项目路径。

### ISSUE THREAD

**Issue by Sarah123100** [dotnet/core#7989]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: windows

找不到要运行的项目。请确保 C:\Users\Name 中存在项目，或使用 --project 传递项目路径。

**Comment by ManickaP** [comment]
@Sarah123100 could you provide more details about your issue? Preferably in English so no information gets lost in automatic translation.

**Comment by mairaw** [comment]
Also, make sure you run the command `cd MyApp` before trying to run the project.
