### ISSUE TITLE
Hot reload with Blazor (server)

### ISSUE THREAD

**Issue by rouf0007** [dotnet/core#7991]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add
Operating System: windows

I run the example. On the "https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add page" you say "Click the Hot Reload button to apply the change to the running app." but the Hot Reload button is disable. !

**Comment by ManickaP** [comment]
What version of VS your running? And what version of .NET?

**Comment by rouf0007** [comment]
Microsoft Visual Studio Community 2022
Version 17.4.0
VisualStudio.17.Release/17.4.0+33103.184
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA500
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46
C# components used in the IDE. Depending on your project type and settings,
a different version of the compiler may be used.

Code Converter   1.0
Code Converter Extension Details

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft
Azure Tools.

Cookiecutter   17.0.22263.6
Provides tools for finding, instantiating and customizing templates in
cookiecutter format.

Extensibility Message Bus   1.4.1 ***@***.***)
Provides common messaging-based MEF services for loosely coupled Visual
Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP
compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet,
visit https://docs.nuget.org/

Python - Profiling support   17.0.22263.6
Profiling support for Python projects.

Python with Pylance   17.0.22263.6
Provides IntelliSense, projects, templates, debugging, interactive windows,
and other support for Python developers.

Razor (ASP.NET Core)
17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename,
query execution and much more to SQL Server Compact & SQLite Data
Connections.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for
Boost.Test.  The use terms and Third Party Notices are available in the
extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google
Test.  The use terms and Third Party Notices are available in the extension
installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools
4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46
Visual Basic components used in the IDE. Depending on your project type and
settings, a different version of the compiler may be used.

Visual F# Tools
17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.4.0.301 ***@***.***)
Visual Studio extension to enable development for Xamarin.iOS and
Xamarin.Android.

Xamarin Designer   17.4.0.138 ***@***.***)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: ***@***.***
    SQLite: ***@***.***
    Xamarin.Android Tools: ***@***.***

Le ven. 25 nov. 2022, à 04 h 53, Marie Píchová ***@***.***> a
écrit :

**Comment by rouf0007** [comment]
I updated VS 2022 today. Now I have an other bug when trying to create a
new  WinUI project:

[image: image.png]

Could be after trying Telerik components. I tried to remove everything from
Teleric but it asks me to login when the project opens...

[image: image.png]

Thanks for your feedback

François

Le ven. 25 nov. 2022, à 09 h 16, Francois Rouleau ***@***.***> a
écrit :

**Comment by rouf0007** [comment]
Telerik sent me the solution to the latest problem:  Nuget Package Manager
=> I had to remove Telerik in Setting.

Then with VS2022 4.1  I still don't have the HotRelad button enable

Tanks

Le lun. 28 nov. 2022, à 15 h 30, Francois Rouleau ***@***.***> a
écrit :

**Comment by ManickaP** [comment]
Unfortunately, I don't know much about VS Hot Reload, but you could checkout this troubleshooting document: https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/xaml-hot-reload-troubleshooting.md
Apart from that, you can always use `dotnet watch` on the command line.

**Comment by rouf0007** [comment]
Thanks, I'll check it out.

Le mar. 29 nov. 2022, à 08 h 41, Marie Píchová ***@***.***> a
écrit :

**Comment by mairaw** [comment]
@danroth27 any suggestions here?

**Comment by danroth27** [comment]
@rouf0007 Does the Blazor Server app successfully run? Note that the hot reload button will only become enabled once the app is running. Also check if hot reload is enabled in Tools > Options > Debugging > .NET / C++ Hot Reload.

**Comment by rouf0007** [comment]
Yes, it is working when I check "Enable Hot Reload..." under  Options
Debugging > .NET / C++ Hot Reload.

Thanks

Le mar. 29 nov. 2022, à 17 h 48, Daniel Roth ***@***.***> a
écrit :

**Comment by mairaw** [comment]
Thanks for letting us know @rouf0007. It seems the issue has been solved. Let us know if there's anything else we can help you with, but for now I'm closing the issue.
