### ISSUE TITLE
Visual Studio 2022安装时卡死了，安装速度0B/s。

### ISSUE THREAD

**Issue by hhd2009** [dotnet/core#7994]
Visual Studio 2022安装时卡死了，安装速度**0B/s**。
我很苦恼，网络也没问题。

machine translation:
> Visual Studio 2022 freezes during installation, and the installation speed is 0B/s.
I'm very distressed, and the network is fine.

**Comment by swat199538** [comment]
网络问题，挂代理吧。

**Comment by mairaw** [comment]
From the answer, it seems it was network issues, so closing. Let us know if that's not the case or you still need assistance.
