### ISSUE TITLE
Azure DevOps Pipeline doesn't support .NET 7 & macos-latest for building .Net Maui iOS apps

### ISSUE THREAD

**Issue by faceoffers28** [dotnet/core#7995]
I'm using the xamarin-sdk.sh 17_4_0_301 version. I've noticed that I can't target iOS 16 using Visual Studio. I'm using Asp.net 7.0.100. It's failing at the DotNetCoreCLI@2 Task.

Looks like it's supposed to support iOS 16.0. https://devblogs.microsoft.com/dotnet/dotnet-maui-dotnet-7/

Here are some error messages coming from the DotNetCoreCLI@2 Task.

ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 16.0.1478 is Xcode 14.0 or later. The current Xcode version (found in /Applications/Xcode_13.2.1.app/Contents/Developer) is 13.2.1. [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]
  		
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 16.0 SDK (shipped with Xcode 14.0). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 16.0 SDK (shipped with Xcode 14.0). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]
/Users/runner/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]
##[error]Error: The process '/Users/runner/hostedtoolcache/dotnet/dotnet' failed with exit code 1
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : /Users/runner/work/1/s/MyApp.sln
Finishing: dotnet publish (Debug)

**Comment by ManickaP** [comment]
Hi, if this is issue occurring only in the AzDO pipeline, maybe try raise this in their repository: https://github.com/microsoft/azure-pipelines-tasks
As that repo is in different org, I cannot transfer this issue there.

**Comment by faceoffers28** [comment]
@ManickaP I raised it here like this person did. https://github.com/dotnet/core/issues/7950 Is this not the same type of issue?

**Comment by ManickaP** [comment]
As it's been pointed out in https://github.com/dotnet/core/issues/7950#issuecomment-1319072681. If you have issues with the pipeline task, it would be better to raised it there.
This does not look line .NET issue.

**Comment by faceoffers28** [comment]
@ManickaP OK, I will post it there. Thanks!
