### ISSUE TITLE
Dotnet Core5 console App fails to discover SSRS URI

### ISSUE THREAD

**Issue by sal-420** [dotnet/core#7996]
### Description
In console app -> add connected service -> Dialog box 'Add new WCF Web Service reference' - URI `'https://xx.xom/reportserver/ReportExecution2005.asmx?wsdl`'  is not found

The same URI entered in the browser is successful - results snippet:
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"`

### Configuration
* DotNet Core5
* Win10 x64
* VS2019

[Unable to discover URI.docx](https://github.com/dotnet/core/files/10107493/Unable.to.discover.URI.docx)

**Comment by ManickaP** [comment]
It says "0 services found", does the WSDL have any services defined?
This doesn't look like dotnet issue, but rather issue with your service endpoint. You can use tools like https://www.soapui.org/docs/soap-and-wsdl/ to test the interface, it might give you better info to troubleshoot.

**Comment by sal-420** [comment]
I will try https://www.soapui.org/docs/soap-and-wsdl/ to test the interface
thanks
