### ISSUE TITLE
macOS 10.15 reached end-of-life on 2022-09-12

### ISSUE THREAD

**Issue by Falco20019** [dotnet/core#7999]
As there seems to not be anyone in charge to create these currently, I will create some since I'm tracking them anyway.
Is it planned to be dropped for .NET Core 3.1, .NET 6.0 and .NET 7.0?

See https://computing.cs.cmu.edu/news/2022/eol-macos-catalina and https://endoflife.date/macos for end-of-life information.

Please add `os-support` label.

/CC @rbhanda @richlander
/awareness @mthalman @adegeo @MichaelSimons

**Comment by xtqqczze** [comment]
Fixed by https://github.com/dotnet/core/pull/9294
