### ISSUE TITLE
Error installing dotnet core on AWS Linux using dotnet.bootstrap.py

### ISSUE THREAD

**Issue by digitalray** [dotnet/core#800]
# General

When trying to install: https://github.com/dotnet/core/blob/master/tools/dotnet-bootstrap/dotnet.bootstrap.py on AWS Linux instance with OS: Amazon Linux AMI release 2017.03 (AMI ID: amzn-ami-hvm-2017.03.1.20170623-x86_64-gp2 (ami-327f5352)), I am getting the following:

** ROVER FORCED SETTINGS CHANGE: DEV MODE 'ON'
** ROVER will skip all git commands.
** ROVER requires the deletion of the directory '/home/ec2-user/dotnet_setup/amzn.2017.03-x64-dotnet' to reset the dev-mode trigger.
** ROVER Building: ['coreclr', 'corefx', 'core-setup', 'libuv']
** ROVER Patching? True
** ROVER Staging in amzn.2017.03-x64-dotnet
** ROVER RID: amzn.2017.03-x64
** ROVER CAUGHT AN UNEXPECTED EXCEPTION: "SemanticVersion instance has no attribute 'find'" of type: <type 'exceptions.AttributeError'>
  File "./dotnet.bootstrap.py", line 545, in <module>
    SpawnPatchTarget(RoverSettings._binDirectory, RoverSettings.PayloadPath)
  File "./dotnet.bootstrap.py", line 342, in SpawnPatchTarget
    RoverSettings.SetPatchTargetPath(path.join(RoverSettings._ScriptDirectory, destination_folder))
  File "./dotnet.bootstrap.py", line 261, in SetPatchTargetPath
    RoverSettings.PatchTarget_Shared   = path.join(shared_containerFolder, RoverSettings.SelectGreatestPrecendenceDirectory(shared_containerFolder))
  File "./dotnet.bootstrap.py", line 248, in SelectGreatestPrecendenceDirectory
    maxVersion = RoverSettings.MaxPrecedence(dirName, maxVersion)
  File "./dotnet.bootstrap.py", line 234, in MaxPrecedence
    versionB = SemanticVersion(versionStrB)
  File "./dotnet.bootstrap.py", line 156, in __init__
    self.VersionTuple = self.GetVersionTuple(versionStr)
  File "./dotnet.bootstrap.py", line 141, in GetVersionTuple
    middleIndex = versionStr.find('-')
** ROVER None

**Comment by omajid** [comment]
Can you try with this patch: https://gist.github.com/omajid/90ebbd58cc54473d2a295c261451c166 ?

**Comment by digitalray** [comment]
Thanks. That fixed the original error. But now I get the following:

************************************************ERROR LOG START*******************************************************
ERROR: An error occured in /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/Tools/dotnetcli/dotnet /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/Tools/run 2. Check 2 logs under /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr.
/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr
Invoking "/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/src/pal/tools/gen-buildsys-clang.sh" "/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr" 3 5 x64 Release    -DCLR_CMAKE_TARGET_OS=Linux -DCLR_CMAKE_PACKAGES_DIR=/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/packages -DCLR_CMAKE_PGO_INSTRUMENT=0 
-- The C compiler identification is Clang 3.6.2
-- The CXX compiler identification is Clang 3.6.2
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- broken

CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/clang" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeTmp

  

  Run Build Command:/usr/bin/gmake "cmTryCompileExec1621937052/fast"

  /usr/bin/gmake -f CMakeFiles/cmTryCompileExec1621937052.dir/build.make
  CMakeFiles/cmTryCompileExec1621937052.dir/build

  gmake[1]: Entering directory
  `/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeTmp'


  /usr/bin/cmake -E cmake_progress_report
  /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeTmp/CMakeFiles
  1

  Building C object
  CMakeFiles/cmTryCompileExec1621937052.dir/testCCompiler.c.o

  /usr/bin/clang -Wall -std=c11 -o
  CMakeFiles/cmTryCompileExec1621937052.dir/testCCompiler.c.o -c
  /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeTmp/testCCompiler.c


  Linking C executable cmTryCompileExec1621937052

  /usr/bin/cmake -E cmake_link_script
  CMakeFiles/cmTryCompileExec1621937052.dir/link.txt --verbose=1

  /usr/bin/clang -Wall -std=c11
  CMakeFiles/cmTryCompileExec1621937052.dir/testCCompiler.c.o -o
  cmTryCompileExec1621937052 -rdynamic

  /usr/bin/ld: cannot find crt1.o: No such file or directory

  /usr/bin/ld: cannot find crti.o: No such file or directory

  /usr/bin/ld: cannot find crtbegin.o: No such file or directory

  /usr/bin/ld: cannot find -lgcc

  /usr/bin/ld: cannot find -lgcc_s

  /usr/bin/ld: cannot find -lc

  /usr/bin/ld: cannot find -lgcc

  /usr/bin/ld: cannot find -lgcc_s

  /usr/bin/ld: cannot find crtend.o: No such file or directory

  /usr/bin/ld: cannot find crtn.o: No such file or directory

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)

  gmake[1]: Leaving directory
  `/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeTmp'


  gmake[1]: *** [cmTryCompileExec1621937052] Error 1

  gmake: *** [cmTryCompileExec1621937052/fast] Error 2
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


-- Configuring incomplete, errors occurred!
See also "/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeOutput.log".
See also "/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release/CMakeFiles/CMakeError.log".
/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr
/home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Release /home/ec2-user/dotnet/amzn.2017.03-x64-dotnet/src/coreclr
Failed to generate native component build project!
** ROVER has detected a failure. A repro shell script has been placed at amzn.2017.03-x64-dotnet/src/coreclr/rover_failure-repro.sh
** ROVER To reproduce the failure:
	cd amzn.2017.03-x64-dotnet/src/coreclr
	./rover_failure-repro.sh
** ROVER is forcefully closing. Note that re-running Rover will execute it with DevMode enabled (no git commands will be run)
************************************************ERROR LOG END********************************************************

Here is the clang version on that instance: clang.x86_64 0:3.6.2-1.12.amzn1

Thanks,
Sarkis

**Comment by Petermarcu** [comment]
We're trying to move away from dotnet.bootstrap.py and it's note really maintained anymore. The preferred approach is https://github.com/dotnet/source-build. Can you give that a try and see if it works for you?

**Comment by Petermarcu** [comment]
@chcosta

**Comment by richlander** [comment]
Please file an issue @ https://github.com/dotnet/source-build if it doesn't work for your case. We're deprecating dotnet.bootstrap.py. 

See: https://github.com/dotnet/core/pull/1063
