### ISSUE TITLE
(BadRequest) The VM size of AgentPoolProfile

### ISSUE THREAD

**Issue by MahmoudMardawi** [dotnet/core#8000]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

(BadRequest) The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/aks/quotas-skus-regions
Code: BadRequest
Message: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'.  For more details, please visit https://aka.ms/aks/quotas-skus-regions

**Comment by ManickaP** [comment]
This discussion might https://github.com/MicrosoftDocs/azure-docs/issues/45485
There are some troubleshooting suggestions and steps to follow. Suspicion is that the default VM size is not supported by that location, you might need to manually specify `--node-vm-size ...`.

**Comment by ManickaP** [comment]
Did the linked document helped? Do you still need help with something?
