### ISSUE TITLE
VS Code Update

### ISSUE THREAD

**Issue by Tyler-Krawec** [dotnet/core#8005]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

VS Code updated and cannot create a new project as the tutorial says. Needs to be updated

**Comment by ManickaP** [comment]
I assume you mean Visual Studio and not VS Code, am I right? What problem are you facing? What needs to be updated? What error you're getting? What version of .NET you have on your machine?

**Comment by Tyler-Krawec** [comment]
Good morning,

I was mistaken. I was using VS code and assuming the softwares were the
same. My apologies. I got Blazor up and running. Thank you!

**Comment by ManickaP** [comment]
No worries, closing as this is solved.
