### ISSUE TITLE
dotnet command not found

### ISSUE THREAD

**Issue by zarina06** [dotnet/core#8011]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by zarina06** [comment]
команда дотнет не найденна

**Comment by buyaa-n** [comment]
@zarina06 It seems dotnet installation was not successful, did you see any error while installation? If the installation was successful, you might to open a new terminal window and try again. Please let us know if that helps
