### ISSUE TITLE
SDK not detected but it's installed

### ISSUE THREAD

**Issue by Septercore** [dotnet/core#8013]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I've installed everything, but follwing the commands provided, I get this:

PS C:\Windows\system32> dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
PS C:\Windows\system32> dotnet new console -o MyApp -f net7.0
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
PS C:\Windows\system32> Get-WmiObject -Class Win32_product | Where-Object {$_.name -like "*net.sdk*"} | Select-Object -Property Vendor, Name, Caption, Version | Sort-Object -Property Name | Format-Table -AutoSize

Vendor                Name                                                Caption                                             Version
------                ----                                                -------                                             -------
Microsoft Corporation Microsoft.NET.Sdk.Android.Manifest-6.0.300          Microsoft.NET.Sdk.Android.Manifest-6.0.300          128.75.16384
Microsoft Corporation Microsoft.NET.Sdk.Android.Manifest-7.0.100-rc.1     Microsoft.NET.Sdk.Android.Manifest-7.0.100-rc.1     8.3.47128
Microsoft Corporation Microsoft.NET.Sdk.iOS.Manifest-6.0.300              Microsoft.NET.Sdk.iOS.Manifest-6.0.300              125.191.42208
Microsoft Corporation Microsoft.NET.Sdk.iOS.Manifest-7.0.100-rc.1         Microsoft.NET.Sdk.iOS.Manifest-7.0.100-rc.1         127.187.47038
Microsoft Corporation Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300      Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300      125.191.42208
Microsoft Corporation Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100-rc.1 Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100-rc.1 127.187.47038
Microsoft Corporation Microsoft.NET.Sdk.macOS.Manifest-6.0.300            Microsoft.NET.Sdk.macOS.Manifest-6.0.300            100.255.42208
Microsoft Corporation Microsoft.NET.Sdk.macOS.Manifest-7.0.100-rc.1       Microsoft.NET.Sdk.macOS.Manifest-7.0.100-rc.1       111.251.47038
Microsoft Corporation Microsoft.NET.Sdk.Maui.Manifest-6.0.300             Microsoft.NET.Sdk.Maui.Manifest-6.0.300             24.78.0
Microsoft Corporation Microsoft.NET.Sdk.Maui.Manifest-7.0.100-rc.1        Microsoft.NET.Sdk.Maui.Manifest-7.0.100-rc.1        28.0.6430
Microsoft Corporation Microsoft.NET.Sdk.tvOS.Manifest-6.0.300             Microsoft.NET.Sdk.tvOS.Manifest-6.0.300             125.191.42208
Microsoft Corporation Microsoft.NET.Sdk.tvOS.Manifest-7.0.100-rc.1        Microsoft.NET.Sdk.tvOS.Manifest-7.0.100-rc.1        127.187.47038

As you can see by the output of "**dotnet new console -o MyApp -f net7.0**" command and the next command, it seems that the sdk is not detected even though it is installed.

**Comment by buyaa-n** [comment]
The `dotnet new console -o MyApp -f net7.0` command would create a new `MyApp` folder with sample app within the current folder.  @Septercore I see you run the command from `C:\Windows\system32` which is special system folder you should not touch, and you could not add the new `MyApp` folder within it. Please change to the desired folder that you could create a folder and try again.

For example, you could switch to your user folder with `cd ../../Users/USER-NAME` command where you need to change the USER-NAME part with your username. Please let us know if that solves your issue
