### ISSUE TITLE
error while executing dotnet command

### ISSUE THREAD

**Issue by chetali-beniwal** [dotnet/core#8014]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Command 'dotnet' not found, but can be installed with:
sudo snap install dotnet-sdk   # version 7.0.100, or
sudo apt  install dotnet-host  # version 6.0.111-0ubuntu1~22.04.1
See 'snap info dotnet-sdk' for additional versions.

**Comment by Velorexe** [comment]
Did you install the `dotnet` SDK through `curl | bash`? If so, it could be that it wasn't added to your PATH. You can add `dotnet` to the path yourself, you can try [these steps](https://stackoverflow.com/questions/53182688/dotnet-install-sh-not-adding-dotnet-command-on-ubuntu).
