### ISSUE TITLE
Error debugging Blazor WASM 

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/core#8019]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

When I run the app in debug mode, the browser loads to the about:blank URL and not the project's URL. When I close the browser window I get the attached error.

The laptop is brand new on corporate network with Windows 10, new Visual Studio 17.4.0, and new Blazor WASM project (C# 7) with no changes. Chrome was my default so switched to Edge and received the same behavior. 

I ran VS as local admin and the error doesn't happen. We validated my regular AD account had full control over all VS folders and files then tried again with regular account to run VS. Resulted in same error. 

![image](https://user-images.githubusercontent.com/5250669/205948895-6e755567-2823-44e2-b922-ea86e058195d.png)

**Comment by buyaa-n** [comment]
From the error you are seeing I would say it is not Blazor or .Net issue. Apparently running a browser instance is not allowed by your system admin. Please try manually enabling it:
1. Go to `edge://flags` in Microsoft Edge.
2. In Search flags, type in `Enable remote debugging through Windows Device Portal`. Set that flag to Enabled. Then, click the Restart button to restart Microsoft Edge.
3. Try run the app again

If these steps did not work, probably better to contact your system admin as it is not .NET issue
