### ISSUE TITLE
Toooooo slow interacting with MS sql server under Ubuntu 16.04 (both using EF or SQLDataReader)

### ISSUE THREAD

**Issue by gorsand** [dotnet/core#802]
# Issue Title

Toooooo slow interacting with MS sql server under Ubuntu 16.04 (either by EF or SQLDataReader)

# General

I have a web API application on dotnet under Core 2.0, Ubuntu 16.04, and an MS SQL server as data storage (totally < 1Gb of data there). Core i5 with 8 GB memory laptop, SSD 120 GB. Both the app and the server run on same machine (localhost).

Under windows the same code requires about 2 sec (provided that the server is also running under windows).

When loading a table of about 150 000 rows (about 10 columns) from sql server I get about 300 sec time! Smaller tables also loaded in such a big time (proportionally to the number of rows). All requests are sync (async versions never used).

This happens for both the EF approach or with direct using of SQLDataReader, so the problem is NOT in the EF.

As a workaround I simply run sqlcmd tool with the sql request as a separate process and parse its output as a cvs file. This takes about 2 sec (not 300 sec) for the same tables.

MS SQL server was installed in a pretty "normal" way following the official instructions (https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu).

I use typical code for DB reading in C# by EF where-style request or just with SQLDataReader:

using (var connection = new SqlConnection(DataConString))
{
  var command = new SqlCommand(query, connection);
  command.Connection.Open();
  var reader = command.ExecuteReader();
  while (reader.Read())
    parse_the_line(reader);
}

My gues is that Core 2.0 handles the connection in some bad manner (eg. disconnects and connects on each row of table) or there's something in deserialization (though I think just any kind of deserialization woldn't be that bad) or maybe Core 2.0 switches to async methods under the hood (which in turn set a kind of timer and wakes on receiving each piece of data) or so on, but these are only my guesses.

Maybe it's somehow connected with the well known MS SQL server bug (feature?) under linux: sqlcmd tool becomes toooo slow when the output is redirected to a file by '>' in the command line. (Note: I don't redirect the output when using sqlcmd tool as a workaround, just read the process output line by line.) So maybe Core 2.0 works with MS SQL server the same bad way as sqlcmd tool does when redirected to a file. But again these are only my guesses.

**Upd:**

The problem is on Core side, not with the SQL server. I just tried connecting to Windows-hosted server, the problem still remains (about 300 sec for 150K rows). Though the same code under Windows works fine (about 2-3 sec).

**Comment by Ataden** [comment]
I confirm such an issue. On Windows EF Core and SQL library work great but on Linux they are way too slow. It is almost imposible to use them on Linux at all.

**Comment by ayurjev** [comment]
I noticed the same slow performance while I was trying to use Core 2.0 on MacOS...
It had been taking 40-50 seconds to execute simple query....

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24480](https://github.com/dotnet/corefx/issues/24480) via [**ZenHub**](https://www.zenhub.com/)

**Comment by NaelsonBR** [comment]
up, my website is slow connect sql in linux ubuntu, have fix?

**Comment by NaelsonBR** [comment]
@karelz Sorry... I did not pay attention in title.
