### ISSUE TITLE
 على مساعدة في حل المشكلة.Template "Console Application" could not be created. Access to the path 'C:\Windows\System32\MyApp' is denied.  إذا 

### ISSUE THREAD

**Issue by ksh5a** [dotnet/core#8020]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
As we have in the bottom of the page:
If you receive a message similar to Template "Console Application" could not be created. Access to the path 'C:\Windows\System32\MyApp' is denied., change your current directory to one where you have permissions to create a new folder and try to run the command again.


Try changing the directory and then run the command again. C:\Windows\system32 is a protected folder.

Let us know how that goes.
