### ISSUE TITLE
No Hello world

### ISSUE THREAD

**Issue by sylvainflt** [dotnet/core#8021]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Nothing happens when running the project.
The message won't appear in the console.

**Comment by mairaw** [comment]
Do you get anything? Any error messages?

**Comment by sylvainflt** [comment]
Hello,
First C# extension in VSCode says .Net is not installed properly but the build works.
The problem is that the execution doesn't print the message.

![vscodeError](https://user-images.githubusercontent.com/94616220/206392037-6e41ceb9-c6f8-496d-aeff-0546fabe7826.png)
![runEmpty](https://user-images.githubusercontent.com/94616220/206392092-58f66bfe-8d3e-4454-bcd3-d27be06e7a4e.png)
