### ISSUE TITLE
Issue while creating webapi using dotnet core

### ISSUE THREAD

**Issue by vijayvishwakarma** [dotnet/core#8026]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\10269177\MyMicroservice\MyMicroservice.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.OpenApi. No packages exist with this id in source(s): Mi
crosoft Visual Studio Offline Packages
C:\Users\10269177\MyMicroservice\MyMicroservice.csproj : error NU1101: Unable to find package Swashbuckle.AspNetCore. No packages exist with this id in source(s): Microsof
t Visual Studio Offline Packages

**Comment by buyaa-n** [comment]
Those packages exist on [NuGet](https://www.nuget.org/packages/Microsoft.AspNetCore.OpenApi#versions-body-tab), I guess your internet connection have had issue, please check your internet connection and run these commands:
`dotnet add package Microsoft.AspNetCore.OpenApi --version 7.0.1` 
`dotnet add package Swashbuckle.AspNetCore --version 6.4.0`

**Comment by xazos79** [comment]
I have the same issue. I attempt to add the package and receive this error:
error: NU1101: Unable to find package Microsoft.AspNetCore.OpenApi. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages

Is there a way to have the command search online instead of offline?

**Comment by mairaw** [comment]
The error message seems to indicate that is trying to find the package on the offline packages. Maybe try adding NuGet as a source?
run `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` then `dotnet restore`

**Comment by captix** [comment]
I'm getting this error from following this tutorial
https://dotnet.microsoft.co/m/en-us/learn/aspnet/microservice-tutorial/create
I believe it should just work

**Comment by mairaw** [comment]
I just replied to the issue you opened @captix. That happens when your nuget source got misconfigured. Let's follow up on the new issue. You try setting the source via command-line like shown above or via VS UI.
