### ISSUE TITLE
Run a Nuget Package restore to generate this file

### ISSUE THREAD

**Issue by vishnuuweshwaranR** [dotnet/core#8027]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/59354994/206431023-806d2529-61cf-475b-a791-091967334c2a.png)

**Comment by mairaw** [comment]
What is the error code in the error list?
