### ISSUE TITLE
   <p>The time on the server is @DateTime.Now</p> not showing after render

### ISSUE THREAD

**Issue by sapir0507** [dotnet/core#8028]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: Windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Problem: I wrote everything as instructed but only the Hello, World! showed up in the rendered view (localhost:5025), and the corresponding text to the HTML line: <p>The time on the server is @DateTime.Now</p> did not.

**Comment by mairaw** [comment]
Can you make sure the change was saved?
