### ISSUE TITLE
 <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

### ISSUE THREAD

**Issue by rammrtzz** [dotnet/core#8031]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

 <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

**Comment by mairaw** [comment]
Can you give more information about your issue @rammrtzz?
