### ISSUE TITLE
The .NET Core SDK cannot be located

### ISSUE THREAD

**Issue by jbechak** [dotnet/core#8032]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I just followed the instructions to install everything, and I get this message when I open the project directory in VS Code:
The .NET Core SDK cannot be located: A valid dotnet installation could not be found. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

**Comment by mairaw** [comment]
Hi @jbechak! I'm sorry to hear you're running into problems.

This might be an issue with PATH.

Check the output of the where.exe dotnet command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
