### ISSUE TITLE
Docker build error [certificate has expired]

### ISSUE THREAD

**Issue by dlopezalbarca** [dotnet/core#8033]
Problem encountered on https://learn.microsoft.com/es-es/training/modules/dotnet-microservices/3-exercise-build-docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

docker build -t pizzabackend .
[+] Building 0.7s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => CANCELED [internal] load metadata for mcr.micrososft.com/dotnet/aspnet:6.0                                     0.5s
 => ERROR [internal] load metadata for mcr.micrososft.com/dotnet/sdk:6.0                                           0.5s
------
 > [internal] load metadata for mcr.micrososft.com/dotnet/sdk:6.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://mcr.micrososft.com/v2/dotnet/sdk/manifests/6.0": x509: certificate has expired or is not yet valid: current time 2022-12-12T09:58:26Z is after 2022-09-18T12:00:00Z

HERE DOCKER FILE:
FROM mcr.micrososft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY backend.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app 
FROM mcr.micrososft.com/dotnet/aspnet:6.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app .
ENTRYPOINT ["dotnet", "backend.dll"]

**Comment by dlopezalbarca** [comment]
typyng mistake

**Comment by mairaw** [comment]
Can we close this issue then?
