### ISSUE TITLE
.NET December 2022 Update - .NET 7.0.1, .NET 6.0.12, .NET Core 3.1.32

### ISSUE THREAD

**Issue by dcwhittaker** [dotnet/core#8037]
# .NET December 2022 Update

## Release Notes
* [7.0.1](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.1/7.0.1.md)
* [6.0.12](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.12/6.0.12.md)
* [3.1.32](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.32/3.1.32.md)

## Status

Asset Type | 7.0.1 | 6.0.12 | 3.1.32 | Notes
-- | :--: | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ | ✅| ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) | ✅ | ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ | ✅ | ✅
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) | ✅ | ✅| ✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ | ✅ | ✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅| ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅ | ✅| 

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by Wedgetable** [comment]
Looking at this section in the readme: https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.12/6.0.12.md?WT.mc_id=dotnet-35129-website#additional-fixes-in-this-release

> ### Additional fixes in this release
> * [Aspnetcore](https://github.com/dotnet/aspnetcore/issues?q=milestone%3A6.0.11+is%3Aclosed+label%3Aservicing-approved+)
> * [Runtime](https://github.com/dotnet/runtime/issues?q=milestone%3A6.0.11+is%3Aclosed+label%3Aservicing-approved+)
> * [SDK](https://github.com/dotnet/sdk/issues?q=milestone%3A6.0.11+is%3Aclosed+label%3Aservicing-approved+)

Should these links go to 6.0.12 instead of 6.0.11?

**Comment by mairaw** [comment]
@Wedgetable I'd think so. Opened a PR for @dcwhittaker to review:
https://github.com/dotnet/core/pull/8039

**Comment by mattzink** [comment]
The 7.0.1 release notes seem to be missing the "Additional fixes in this release" section. It only says this release contains security fixes, but there are many functional changes in this release also ([in runtime](https://github.com/dotnet/runtime/issues?q=milestone%3A7.0.1+is%3Aclosed+label%3Aservicing-approved+), for example). This is the most useful section for me, so I hope it makes a comeback.

**Comment by dcwhittaker** [comment]
@mattzink - Sorry about that - missed it in putting the md file together. I'm working on that now and will have that updated in a few minutes. I'm glad it's helpful!

**Comment by JacobRFox** [comment]
We have been having difficulty running .NET MAUI applications as of dotnet version 7.0.101. Version 7.0.100 seems to work fine. Under 7.0.101 trying to debug default template for MAUI apps causes debugger to start and then immediately stop without an error message apparent. Is there a way for me to roll back to a specific dotnet revision so I can confirm this issue?

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/8090
