### ISSUE TITLE
.Net Core SDK docker image still use nuget 2.x which has setting issue

### ISSUE THREAD

**Issue by zhili1208** [dotnet/core#804]
From https://github.com/NuGet/Home/issues/5707 @TAGC

Nuget 2.x is installed in .Net Core SDK docker image, need to upgrade to nuget 4.x to avoid setting issue.

**Comment by leecow** [comment]
@MichaelSimons @richlander @kendrahavens to have a look.

**Comment by MichaelSimons** [comment]
@zhili1208 - can provide details about which version of the the SDK docker image you are using?  Which version of the SDK does it include?

```
$ docker run --rm microsoft/dotnet:2.0-sdk dotnet nuget --version
NuGet Command Line
4.3.0.5
```

**Comment by zhili1208** [comment]
@TAGC Could you provide the details about your docker image SDK?

**Comment by TAGC** [comment]
`microsoft/dotnet-2.0-sdk`, same as @MichaelSimons. However, Michael is using `dotnet nuget` (which is 4.3.0.5 as he shows). My understanding is that this is a stripped down version of NuGet that doesn't allow me to do things like updating local feeds or setting API keys, etc (it's not displayed under `dotnet nuget --help`.

If you try `apt-get update && apt-get install -y nuget && nuget`, you should see it listed as v2.8.7.0.

**Comment by svick** [comment]
@TAGC I believe that's the version of nuget that comes from [Debian Stretch repository](https://packages.debian.org/stretch/nuget), which is based on mono.

I think nothing can be done about that in the Docker image, because it doesn't come from the Docker image.

**Comment by MichaelSimons** [comment]
Agreed with @svick - this is not an issue with the .NET Core Docker image.

**Comment by TAGC** [comment]
Yeah, I'm aware and agree with you. This is something that the Debian Stretch maintainers would need to resolve I guess. I was hoping with NuGet/Home#5707 that the NuGet team would have a way of contacting (or even be the same people as) the people maintaining this package, or else have an alternative they can suggest.

At the moment it's not too much of an issue for me - I'm maintaining a `NuGet.Config.template` which I populate during CI builds:

```
# Add credentials (temporary workaround for NuGet/Home#5707)
- apt-get install -y gettext
- cat NuGet.Config.template | envsubst > NuGet.Config
- nuget setapikey $MYGET_API_KEY -source https://www.myget.org/F/<company>/api/v3/index.json -configFile NuGet.Config
```

**Comment by MichaelSimons** [comment]
@TAGC, Are you alright with closing this issue?

**Comment by TAGC** [comment]
Yeah, I guess so.
