### ISSUE TITLE
The created service does not run

### ISSUE THREAD

**Issue by costica-moldovanu** [dotnet/core#8041]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Operating System: windows 10

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
The template "ASP.NET Core Web API" was created successfully.

Processing post-creation actions...
Restoring C:\Users\smokey\MyMicroservice\MyMicroservice.csproj:
  Determining projects to restore...
C:\Users\smokey\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.OpenApi (>= 7.0.0)' for 'net7.0'.
C:\Users\smokey\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 6.4.0)' for 'net7.0'.
  Failed to restore C:\Users\smokey\MyMicroservice\MyMicroservice.csproj (in 194 ms).
Restore failed.
Post action failed.
Manual instructions: Run 'dotnet restore'

C:\Users\smokey\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.OpenApi (>= 7.0.0)' for 'net7.0'.
C:\Users\smokey\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 6.4.0)' for 'net7.0'.

**Comment by mairaw** [comment]
What does the `dotnet nuget list source` command returns? If it's empty, it might be an issue with your NuGet sources.

You can try `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` to fix if it's empty.

**Comment by costica-moldovanu** [comment]
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org fixed the issue
