### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by wx8sjc** [dotnet/core#8042]
When I ran dotnet in the command line it said it wasn't a valid command. Did a reboot after installing .net

**Comment by ShreyasJejurkar** [comment]
It seems like .NET is not correctly installed on your machine. Generally, the installer adds dotnet to the path variable! 

How did you install .NET on your machine!? I would suggest downloading .NET from the below site. 

https://dotnet.microsoft.com/en-us/download

**Comment by buyaa-n** [comment]
Check if you find dotnet installed in one of the installation folders:
https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows#check-for-install-folders

If you do, maybe there's an issue with the PATH environment variable.

**Comment by wx8sjc** [comment]
Got it. Was appling wrong one. Thanx everyone and Merry Christmas!
