### ISSUE TITLE
Couldn't find an installed template that matches the input, searching online for one that does...

### ISSUE THREAD

**Issue by andresantosrib** [dotnet/core#8043]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create
Operating System: windows

`#0d1117
Console Application (C#)
Author: Microsoft
Description: A project for creating a command-line application that can run on .NET Core on Windows, Linux and macOS
Error: Invalid parameter(s):
-f net7.0
    'net7.0' is not a valid value for -f (Framework).`

`#2f0017
Options:
  --langVersion  Sets the LangVersion property in the created project file
                 text - Optional`

>--no-restore   If specified, skips the automatic restore of the project on create.
                 bool - Optional
                 Default: false / (*) true

> * Indicates the value used if the switch is provided without a value.

`#90fff0
Solução encontrada:`
>* dotnet new console -o MyApp -f net

`#90fff0
ou instale a versão mais recente e chame`

>* dotnet new console -o MyApp  -f net++

**Comment by mairaw** [comment]
HI @andresantosrib!

It seems we missed your issue a while back. 
We have since rewritten the tutorial. Let us know if you still need help.

**Comment by andresantosrib** [comment]
já se  passaram tanto tempo que nem me recordo mais a que projeto estava me
referindo, talvez nem estou mais trabalhando-o


Em qua., 21 de fev. de 2024 às 23:13, Maira Wenzel ***@***.***>
escreveu:

**Comment by mairaw** [comment]
Sem problemas. Desculpa por não ter visto na época.
