### ISSUE TITLE
hi i literally have no idea about coding and i just wanna connect my ps4 controller to my pc. first time im doing code and im utterly confused. is there any way you could help me

### ISSUE THREAD

**Issue by Ineedhelp18** [dotnet/core#8045]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Okay so i think i opened the program.cs file and tried to enter everything needed and saved it. im not sure if what i named the file was important or not to the process so i named it 'Program kp lan cs'. i hope this isnt what caused the issue. the error message is in german so ill try to roughly translate:

C:\Users\akmal\MyApp\Program.cs(2,1): error CS8802: only a compilation unit can command on the highest level. [C:\Users\akmal\MyApp\MyApp.csproj].

Error in the build process.

i dont even know how to upload the file. im super bad at this so extremely detailed help would be amazing

**Comment by chuleva** [comment]
@Ineedhelp18 
Could you please add more details of what you're trying to accomplish with connecting the ps4 controller to pc.

For the Program.cs, I assume that file doesn't have too much lines of code. If so, could you please copy it and paste it as a comment?

**Comment by buyaa-n** [comment]
> im not sure if what i named the file was important or not to the process so i named it 'Program kp lan cs'.

The file name could not have space, you could separate words with underscore ('Program_kp_lan.cs') or use CamelCase ('PrograKpLan.cs')
