### ISSUE TITLE
Dotnet app not Creating instead showing to use the previously created app or to re write it.

### ISSUE THREAD

**Issue by DhawalTandon** [dotnet/core#8047]
### Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows
Windows 11 Home Insider Preview Single Language os build: 25267.1000

C:\Windows\System32>dotnet new console -o MyApp -f net7.0
Creating this template will make changes to existing files:
  Overwrite   MyApp\MyApp.csproj
  Overwrite   MyApp\Program.cs

Rerun the command and pass --force to accept and create.

**Comment by DhawalTandon** [comment]
Thank You for mailing me Your code worked! Thanks again! And hope to see you again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ShreyasJejurkar** [comment]
You can close this GitHub issue if your problem is solved. Thanks!
