### ISSUE TITLE
Json serialization/deserialization invalid behavior

### ISSUE THREAD

**Issue by Helius01** [dotnet/core#8049]
### Description
Hey. when i deserialized a type of `Dictionary<string,int>` from `appsettings.json` , I encountered an unexpected value  

**The result I expected :**
```
"https://example.com":1,
"https://example2.com":2
```

**The result I received:**
```
"https":1,
"https":2
```
I think the problem is for ```:``` character in key string

**Comment by svick** [comment]
Per https://github.com/dotnet/extensions/issues/782, this seems to be the intended behavior.

**Comment by Helius01** [comment]
> Per [dotnet/extensions#782](https://github.com/dotnet/extensions/issues/782), this seems to be the intended behavior.

Ok so i close the issue
