### ISSUE TITLE
I have installed Visual Studio 2019 and when I am trying to run the command 'donet' through command prompt, it shows an error like 'dotnet' is not recognize as an internal program.

### ISSUE THREAD

**Issue by singh-vinay** [dotnet/core#8051]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jeffhandley** [comment]
It sounds like `dotnet.exe` is not in your `PATH` environment variable. I recommend installing the .NET SDK directly from https://get.dot.net, and this SDK installer will update your `PATH`.
