### ISSUE TITLE
Redhat 9 - dotnet project create issue 

### ISSUE THREAD

**Issue by indikaaruna8** [dotnet/core#8052]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: linux

$ dotnet new webapp -o MyWebApp --no-https -f net7.0

A fatal error occurred, the folder [/usr/lib64/dotnet/host/fxr] does not contain any version-numbered child folders

**Comment by omajid** [comment]
It sounds like you have tried to install .NET from multiple package feeds? Could you please show us the output of `rpm -qa | grep dotnet` to confirm/reject that hypothesis? Please see https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup for more details on the cause and possible solutions.
