### ISSUE TITLE
kubectl get service mymicroservice --watch

### ISSUE THREAD

**Issue by robertmcateer** [dotnet/core#8054]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jeffhandley** [comment]
Hello -- this does not give us enough information to understand what problem you're having. Please add more details to describe what is happening that is unexpected.
