### ISSUE TITLE
Incorrect yaml file

### ISSUE THREAD

**Issue by UjfalusiAbel** [dotnet/core#8058]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: linux

Hello. The yaml file provided on the kubernet deployment section is not correct and can't be used in this format

**Comment by jeffhandley** [comment]
Hello! Please confirm that the YAML file contents that you saved match what is available in the tutorial, including all leading whitespace. It's likely that some of the indentation was lost in your local copy of the file.
