### ISSUE TITLE
How to fix Blazor WASM memory access out of bounds error?

### ISSUE THREAD

**Issue by Yudiz-bhargav** [dotnet/core#8060]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by greenEkatherine** [comment]
Hello @Yudiz-bhargav You provided the link to the installation part, did the error happen during installation? If not, could you please provide the code example which produced the error?
