### ISSUE TITLE
Not a bug, recommendation. Add core interfaces IAction<T...>, IFunc<T...>

### ISSUE THREAD

**Issue by vhforte** [dotnet/core#8064]
This is a thing that I always miss in .net.
Can you modify the Action and Func delegates in a way that its instances are castable to predefined interfaces: IAction, IFunc.
Same as in Java 11.

As I know each Action<T,...> is compiled into a class with 1 method. This class must implement IAction<T,...> with that method.
I need it in Unit tests.

**Comment by jeffhandley** [comment]
Hi, @vhforte. Thank you for this suggestion. The dotnet/runtime repository has an issue template for suggesting API proposals. Would you be able to fill out that template? Ideally, the submission would include sample code showing how these interfaces would be used, what types of functions this would enable for you, and what you currently need to do as a workaround in the absence of these interfaces.

You'll want to use the "API Suggestion" issue template here:
https://github.com/dotnet/runtime/issues/new/choose
