### ISSUE TITLE
Brand new blazor app not working

### ISSUE THREAD

**Issue by rmnrdi** [dotnet/core#8065]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I created a new Blazor app, clicked "Windows Machine" to start the app. 

Nothing happens...

I ran a .net core React app just a few minutes prior and it launched a browser and worked fine

**Comment by jeffhandley** [comment]
Hello, @rmnrdi; thanks for trying out the Blazor tutorial. It's possible that the port used by the tutorial is already in use by another app on your system. The instructions here show someone else getting stuck on that and how to work around it: https://github.com/dotnet/aspnetcore/issues/20754

Please try changing the port to see if that fixes it. If not, any other information from the build output or debug console might also be helpful for us to understand what's happening.

**Comment by rmnrdi** [comment]
Sorry, this is a Blazor **Maui** app. There's no port in launchsettings.json

//My launchsettings.json
{
  "profiles": {
    "Windows Machine": {
      "commandName": "MsixPackage",
      "nativeDebugging": false
    }
  }
}

Also, how do I stop the locked and unusable program?

**Comment by mairaw** [comment]
The tutorial above is not a Blazor Maui app. So are you doing your own version? It might be better to open an issue on dotnet/maui if this is a MAUI app.
