### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jana2418** [dotnet/core#8066]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by greenEkatherine** [comment]
Hello @Jana2418 , thank you for using our tutorial. Please provide the error message or any description of the issue for further investigation.
