### ISSUE TITLE
It says it is not possible to find a compatible framework version

### ISSUE THREAD

**Issue by CAMFRONONHERE** [dotnet/core#8068]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by ShreyasJejurkar** [comment]
Can you send the screenshot of the error that you are getting?
