### ISSUE TITLE
fixed it cant close submision

### ISSUE THREAD

**Issue by nighthunter9** [dotnet/core#8069]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

cant use dotnet in cmd
 'dotnet' is not recognized as an internal or external command

**Comment by ShreyasJejurkar** [comment]
It looks like dotnet is not installed properly on your machine. Or maybe re-opening of shell/cmd is necessary! 
Can you open a new CMD window and type the following and see if it returns a version? 

`dotnet --version`
