### ISSUE TITLE
Error when running "docker run" .net core 2.0 preview project in linux

### ISSUE THREAD

**Issue by milla** [dotnet/core#807]
I'm upgrading our project to .net core 2.0 preview now. 

Our project now uses .net core 2.0 preview, in Docker container, pushed to Microsoft azure container service with orchestration of kubernetes.

Package being used in project:
`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-final" />`

dotnet runtime in (VSTS) build agent machine,
```
$ dotnet --version
2.0.0-preview2-006497
```

SDKs installed in the machine,
```
$ ls /usr/share/dotnet/shared/Microsoft.NETCore.App
1.0.5  1.1.2  2.0.0-preview2-25407-01
```
DockerFile: [reference](https://hub.docker.com/r/microsoft/aspnetcore/)

```
FROM microsoft/dotnet:2.0.0-runtime-jessie

# set up network
ENV ASPNETCORE_URLS http://+:80
ENV ASPNETCORE_RUNTIMESTORE_DOWNLOAD_URL https://dist.asp.net/runtimestore/2.0.0/linux-x64/aspnetcore.runtimestore.tar.gz
ENV ASPNETCORE_PKG_VERSION 2.0.0

# set up the runtime store
RUN curl -o /tmp/runtimestore.tar.gz $ASPNETCORE_RUNTIMESTORE_DOWNLOAD_URL \
    && export DOTNET_HOME=$(dirname $(readlink $(which dotnet))) \
    && tar -x -C $DOTNET_HOME -f /tmp/runtimestore.tar.gz \
    && rm /tmp/runtimestore.tar.gz

ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish/References.Web} .

ENTRYPOINT ["dotnet", "References.Web.dll"]
```

I tried some other docker images, yet, all have the below issue when running the container,

```
It was not possible to find any compatible framework version 
The specified framework 'Microsoft.NETCore.App', version '2.0.0-preview2-25407-01' was not found. 
  - Check application dependencies and target a framework version installed at: 
      / 
  - Alternatively, install the framework version '2.0.0-preview2-25407-01'. 
```

Thanks

Created an issue in aspnet-docker project 
https://github.com/aspnet/aspnet-docker/issues/281

**Comment by varnav** [comment]
Looks like microsoft/dotnet:2.0.0-runtime-jessie now contains 2.0 RTM, since today.

**Comment by milla** [comment]
Thanks, I've upgraded to 2.0. Now it works. Closing this case.

**Comment by 68681395** [comment]
There is the same problem with my project, the workaround to resolve it successfully is that remove the item 'C:\Program Files (x86)\dotnet' from the Path of Environment Variable because I found I did not install the right netcore version under X86. I have not tried to install the proper version with x86, appreciate that you tell me if you have done that test.

**Comment by dermeister0** [comment]
Fixed the issue by changing microsoft/aspnetcore-build:2.0.0-preview2 base image to microsoft/aspnetcore-build:2.0.6-2.1.104 in Dockerfile.
