### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by bian2022** [dotnet/core#8072]
![image](https://user-images.githubusercontent.com/101516281/210339747-255fe477-c0c4-4134-bfab-4a7506db8a57.png)
During the installation process, "Click OK to try again, or enter an alternate path to a folder containing the installation package 'dotnet-host-6.0.10-win-x64.msi in the box below. ", how to solve this problem?

**Comment by greenEkatherine** [comment]
Hello @bian2022 , it looks like the issue with the path. Could you please check the correctness of it and formatting and if it doesn't help try to move installer into different folder?
