### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/create

### ISSUE THREAD

**Issue by DavidEnrique1215** [dotnet/core#8075]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/create
Operating System: windows 10

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant:
Instruction: dotnet new console -o Myapp -f net7.0
Error message: 
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by greenEkatherine** [comment]
Hello @DavidEnrique1215, could you please confirm that you installed .NET SDK and opened a new system command after that? What output do you get when run `dotnet` command?
