### ISSUE TITLE
It seems that the installation of .NET 6.0 went wrong...

### ISSUE THREAD

**Issue by nuvolanera** [dotnet/core#8078]
_Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant._

After installing the .NET 6.0 SDK (v6.0.404) - Windows x86 platform, I opened the command prompt (a new one).
From C:\>, I've tried to run the "dotnet" command, but got the message:
**"dotnet" is not recognized as an internal or external command, an executable program or a batch file.**

I tried uninstalling and reinstalling, which ended positively, but then, upon verification, the same problem occurs again

I also tried as system administrator, but in vain

**Comment by nuvolanera** [comment]
the problem is solved!
the command prompt must be placed on the directory:
C:\Program Files (x86)\dotnet <-- correct!
where the dotnet.exe executable resides, but this is not explicitly said, indeed the example suggests typing it in the root:
C:\>dotnet   <-- wrong!

shame on them! :-)

**Comment by bartonjs** [comment]
You shouldn't need to have your working directory be `C:\Program Files (x86)\dotnet`... that suggests either that A) you opened the command prompt before running the installer, or B) updating your PATH environment variable failed.

**Comment by nuvolanera** [comment]
Hi bartonjs, thank you for your reply.

hypothesis A) is to be excluded
hypothesis B) is the correct one

Now, the directory where the .NET 6.0 is installed is
C:\Program Files (x86)\dotnet,
but the directory is chosen by the installation file, without being given the possibility of modifying it or, at least, being aware of it.
Initially, I couldn't even run the "dotnet" command.
I wonder why this step hasn't been explained in the tutorial, which is very simple.

While the directory where the application is installed is
C:\Users\franc\MyApp,
as suggested by the usual tutorial.

Now, what do you suggest as a path to add?

Cheers,
Francesco

**Comment by bartonjs** [comment]
The thing to add to your path would be `C:\Program Files (x86)\dotnet`... though, if it's showing up in `Program Files (x86)` you may have used the 32-bit SDK installer on a 64-bit system, which might be part of the problem?

```
C:\Users\bartonjs>set PATH
Path=C:\Program Files\Python\Python38\Scripts\;C:\Program Files\Python\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\bartonjs\AppData\Local\Microsoft\WindowsApps;C:\Users\bartonjs\.dotnet\tools;C:\Users\bartonjs\.dotnet\tools;C:\Users\bartonjs\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
```

Turning each semi-colon into a bullet from my path, and rolling my eyes at the duplicates:


* C:\Program Files\Python\Python38\Scripts\
* C:\Program Files\Python\Python38\
* C:\WINDOWS\system32
* C:\WINDOWS
* C:\WINDOWS\System32\Wbem
* C:\WINDOWS\System32\WindowsPowerShell\v1.0\
* C:\Program Files\Git\cmd
* C:\Program Files\CMake\bin
* C:\Program Files\dotnet\ `     <--- this one`
* C:\Program Files\Microsoft\Web Platform Installer\
* C:\Program Files\Microsoft SQL Server\140\Tools\Binn\
* C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
* C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
* C:\WINDOWS\system32
* C:\WINDOWS
* C:\WINDOWS\System32\Wbem
* C:\WINDOWS\System32\WindowsPowerShell\v1.0\
* C:\Users\bartonjs\AppData\Local\Microsoft\WindowsApps
* C:\Users\bartonjs\.dotnet\tools
* C:\Users\bartonjs\.dotnet\tools
* C:\Users\bartonjs\AppData\Local\Microsoft\WindowsApps

**Comment by nuvolanera** [comment]
barton,
you're absolutely right
now i've installed the x64 version and, after updating the paths, things seem to be working fine
thank you for your support,
cheers
