### ISSUE TITLE
dotnet not found, no PATH variable

### ISSUE THREAD

**Issue by baroquedub** [dotnet/core#8080]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I installed .NET Framework 4.8 Developer Pack (online installer). No errors reported, just a successful install message. I had previously tried the normal DotNet online installer but it told me that I already had DotNet 4.8 installed.

If I go to a command prompt and type dotnet, I get the message "'dotnet' is not recognized as an internal or external command,
operable program or batch file."

I've looked in the environment variables and can't see dotnet listed under PATH (either system or user variables).

I rebooted the PC both before and after installation. 

How can I manually add the PATH variable, and what should that path be? Searching Google, it appears that I should be using C:\program files\dotnet\sdk but I don't have this folder. All I can find is C:\Windows\Microsoft.NET

Can anyone help? Thanks

**Comment by greenEkatherine** [comment]
Hello @baroquedub, the issue is that `dotnet` is a .NET Core command, not Framework that you installed. Also the path that you found  searching Google is correct for .NET Core. For .NET Framework you need to check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full. Please pay attention that tutorial that you linked is for .NET Core not .NET Framework.

**Comment by baroquedub** [comment]
Thank you for your response, and your help.

re.
> For .NET Framework you need to check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full

So I had already checked this in the registry and it is there and shows I have 4.8 installed.

The problem I have (and what got me to try the hello world tutorial, to try to understand what I needed to do to get dotnet working) is that when I run VSCode with CoPilot, it opens with the following error: '_GitHub Copilot could not connect to server. Extension activation failed: "A valid dotnet installation could not be found"_' and so searching for that error seemed to imply that what I'm missing is the PATH variable.

Now I'm even more confused... Are VSCode/CoPilot looking for a .NET Framework installation (if so, what would be the path to that?) or a .NET Core installation?

**Comment by mairaw** [comment]
Can you share what the dotnet --info command returns?

Also, if the issue might be related to PATH, check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

**Comment by mairaw** [comment]
Also, I'm not sure how copilot works, but I'd assume that a dotnet installation means it's looking for the .NET SDK, not .NET Framework.

**Comment by baroquedub** [comment]
> I'd assume that a dotnet installation means it's looking for the .NET SDK, not .NET Framework

I'm hugely greatful for the help. That's exactly what the problem was. 

I'd installed:
- .NET 7.0
- .NET Core 3.1
- .NET Framework 4.8 Developer Pack
- .NET Framework 4.8

but I needed .NET 6.0 SDK

Once CoPilot started working, VSCode also prompted me to additionally install the .NET Framework 4.7.1 Developer Pack in order to load my project, so I added that too and now I'm all good.

Thank you!

**Comment by mairaw** [comment]
Great to hear!
