### ISSUE TITLE
Error in the "dotnet new webapp -o MyWebApp --no-https -f net7.0" command

### ISSUE THREAD

**Issue by DanielIppo** [dotnet/core#8081]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I do the command "dotnet new webapp -o MyWebApp --no-https -f net7.0
" I fall into this error  "A fatal error occurred. The folder [/usr/share/dotnet/host/fxr] does not exist" How I can fix it?

**Comment by omajid** [comment]
Please take a look at https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup

What OS are you running?
