### ISSUE TITLE
tried to install dotnet, cmd window cant find it.

### ISSUE THREAD

**Issue by mad01jack** [dotnet/core#8082]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by greenEkatherine** [comment]
Hello @mad01jack , did you open new cmd window after installation? Please also check if the Path in the system's environment variables is correctly configured for your system.
