### ISSUE TITLE
Windows 7 (SP 1) and Windows  8.1 are reaching end-of-life on 2023-01-10

### ISSUE THREAD

**Issue by Falco20019** [dotnet/core#8085]
As there seems to not be anyone in charge to create these currently, I will create some since I'm tracking them anyway.
Is it planned to be dropped for .NET Core 3.1 and .NET 6.0? For .NET 7.0 they already had not been added in the first place? .NET Core 3.1 is technically end-of-life itself anyway. So I'm mostly interested in .NET 6.0.

See https://learn.microsoft.com/de-de/lifecycle/products/windows-7 and https://learn.microsoft.com/de-de/lifecycle/products/windows-81 for end-of-life information.

Please add os-support label.

/CC @rbhanda @richlander
/awareness @mthalman @adegeo @MichaelSimons

**Comment by ashnaga** [comment]
Resolving this one
