### ISSUE TITLE
I tried to create a .NET new console but everytime I try in command prompt I recive this message  

### ISSUE THREAD

**Issue by Robotinvade** [dotnet/core#8087]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Robotinvade** [comment]
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
IDK what I'm doing wrong because I went in system path and move the dotnet path up but nothing change

**Comment by mairaw** [comment]
Did you install the SDK? Can you share what the `dotnet --info` command returns?

**Comment by Robotinvade** [comment]
C:\Users\pedro>dotnet --info

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

I've had installed the sdk for dotnet what or I have to install anything more??

**Comment by Robotinvade** [comment]
![Prompt de Comando 10_01_2023 22_03_47](https://user-images.githubusercontent.com/120051033/211694112-3fa41714-95c0-4c95-91a8-b81850d1678d.png)

I followed the #5962  but still the same thing and my system is x64

**Comment by mairaw** [comment]
Did you open a new command prompt after updating path? If PATH was updated correctly, the x86 would show up in second.
Maybe share a screenshot of your environment variables for us to double check?

**Comment by mairaw** [comment]
Great to hear!
