### ISSUE TITLE
Clarify platform support

### ISSUE THREAD

**Issue by Genbox** [dotnet/core#81]
I've been searching and tried asking around, but no one seem to have the answer as to what versions of Windows is supported. I know the latest versions are supported (8.1, 10), but what about Windows XP and Vista? Some software companies still have to officially support Windows XP/Vista even if they are not officially supported by MS.

If they are not officially supported, would the .NET core framework in self-contained mode run on them?
I'd wage that Windows XP probably don't have a few of the APIs needed by the CoreFX libraries, but what about CoreCLR? Could you essentially run managed C# assemblies on Windows XP?

**Comment by aL3891** [comment]
It's windows 7+ as far as I know. I don't think even self contained will work on lower windows versions because the dependencies to windows 7+ are in the coreclr/jit

**Comment by Genbox** [comment]
Spun up a couple of VMs to test the new RC2 release. Windows XP and Vista is not supported it seems. Native builds does not work either.

@aL3891 can't imagine any dependencies for a particular OS version in the JIT, but the CLR could have some hard dependencies. For now, people will have to stick with Mono for full Windows support it seems.

**Comment by blackdwarf** [comment]
All of the information on supported OS-es can be found in https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps. With that, I will close this issue.
