### ISSUE TITLE
Mac M1 chip meet rosetta error 

### ISSUE THREAD

**Issue by luckyaq** [dotnet/core#8100]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos with M1 chip

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

So the first time I tried to run the App by 'dotnet run', it success and show the output correctly.
Then I edited it, even just added a simply space between the two words, an error occured.

rosetta error: /var/db/oah/05a014fd2f158106a68d9f0bf74fcb2774f213cd362618c38ead1fe322bc4065/dcd6ac2606d0f96a7598ee27be08ce2a18d66c98fbd03086ece92866c6c32aa1/MyApp.aot: attachment of code signature supplement failed: 1

**Comment by greenEkatherine** [comment]
Does the app work again after reverting the change?

**Comment by anhhtca** [comment]
I have been facing the same problem for two weeks now. After upgrading VSCode.
