### ISSUE TITLE
not found dotnet

### ISSUE THREAD

**Issue by nawalalhouti** [dotnet/core#8109]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by antonfirsov** [comment]
Did you reopen the terminal after installing? In case you have M1, did you follow the Arm64 link?
