### ISSUE TITLE
erro de dependencia

### ISSUE THREAD

**Issue by Maria-Lima2503** [dotnet/core#8110]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/aspnet/blazor-tutorial/run
Operating System: windows

Ao executar o plicativo, mostra-me erro do Nuget.

**Comment by antonfirsov** [comment]
@Maria-Lima2503 can you please elaborate what specific error are you seeing at what step?

**Comment by mairaw** [comment]
@Maria-Lima2503 qual é o erro do NuGet que é mostrado quando você executa o aplicativo?
