### ISSUE TITLE
Erro no componente Counter

### ISSUE THREAD

**Issue by Maria-Lima2503** [dotnet/core#8111]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/aspnet/blazor-tutorial/add
Operating System: windows

o Componente Counter tem uma váriavel, mas ela não incrementa

**Comment by mairaw** [comment]
Você pode explicar melhor o problema? O contador funciona inicialmente na página Counter? Você adicionou o componente à página Index também como indicado?
