### ISSUE TITLE
Segmentation fault hello-world tutorial on Ubuntu 22.04

### ISSUE THREAD

**Issue by frankhuurman** [dotnet/core#8113]
### Description

I tried installing the .NET SDK and runtime through Snap on this page: https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap

Installation seems successful but following the hello world example(https://learn.microsoft.com/en-us/dotnet/core/get-started) after that throws a segmentation fault(even with **sudo**):

![image](https://user-images.githubusercontent.com/19980966/212894713-11246852-5948-43ba-8a1f-3b512c3ba490.png)
![image](https://user-images.githubusercontent.com/19980966/212895294-11525e20-2efc-4ce0-acce-5e8849b2a21d.png)

(note: the dotnet alias to the SDK got exported successfully, it's just not on the screenshots)

No sample1 dir got created either.

When looking through journalctl after a crash, this shows up:
![image](https://user-images.githubusercontent.com/19980966/212897346-fe101159-64d8-41a5-a319-4f0ede6daa32.png)

### Configuration

.NET SDK = 6.0.405
Ubuntu 22.04.1 LTS
x64

### Other information

This is my first time ever installing .NET, so not used to the toolchain.

**Comment by frankhuurman** [comment]
Just in case other devs run into this and really need to use .NET / C#:

The apt dotnet-sdk-6.0 and dotnet-runtime-6.0 packages do work fine.

**Comment by antonfirsov** [comment]
Looks like an installer issue. /cc @NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
> Looks like an installer issue. /cc @NikolaMilosavljevic

This is a known issue with Snap. Please use `apt` or other options to install .NET. Check the following issue for steps to install .NET from desired package feeds: https://github.com/dotnet/core/issues/7699 .NET is available in native Jammy feeds as well as on packages.microsoft.com
