### ISSUE TITLE
dotnet installation command prompt issue

### ISSUE THREAD

**Issue by 1811saurabh** [dotnet/core#8116]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows 11
![Command Prompt 18-01-2023 12 28 52 PM](https://user-images.githubusercontent.com/75617913/213105144-a1b80a05-7500-4540-a8c6-5b60c8600e34.png)

'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by antonfirsov** [comment]
@1811saurabh you should open a new command prompt after installing. Are you sure you have done that?
