### ISSUE TITLE
dotnet error

### ISSUE THREAD

**Issue by constie2607** [dotnet/core#8119]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I received a zsh: command not found: dotnet error after downloading the dotnet app. I tried it on a new terminal but to no avail.
![IMG_1884](https://user-images.githubusercontent.com/123075967/213429397-fc354962-ead5-408a-89ce-f003b17eb872.jpg)

**Comment by antonfirsov** [comment]
Have you opened a new terminal window after installation?

**Comment by constie2607** [comment]
Yeah i have, it doesn’t work

**Comment by mairaw** [comment]
Which kind of Mac do you have? Is it an M1? Which version did you install?
