### ISSUE TITLE
Issue in cmd 

### ISSUE THREAD

**Issue by devAshShahi** [dotnet/core#8120]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error: Invalid parameter(s):
-f net7.0
    'net7.0' is not a valid value for -f (Framework).

**Comment by antonfirsov** [comment]
@devAshShahi do you have [.NET 7.0 installed](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)? What does `dotnet --info` print?
