### ISSUE TITLE
I'm trying to download Microsoft .Net 7 and when I got to the last step entering in code in the program.cs file and saving it into MyApp folder then it stated to run "dotnet run" again and I got an error message. How do I fix this? I'm only installing it because ArcGIS requires it for install. 

### ISSUE THREAD

**Issue by ghost** [dotnet/core#8121]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What is the error message that you got?

Also, this tutorial is more for people trying to learn how to code. If you're trying to install .NET because an application is required, can you share what is the dialog you get when you try to run the app?
