### ISSUE TITLE
Problem on my first run

### ISSUE THREAD

**Issue by Joaomarcos7** [dotnet/core#8124]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when i try to run the Program.cs using the command "dotnet run" the compiling never execute the program, then i give an Conntrol+C to skip the execution and the following message appears "Ocorreu uma falha no build, corrija os erros de build e execute novamente" (Portuguese)

**Comment by mairaw** [comment]
Oi @Joaomarcos7! Você pode tirar um print da tela e compartilhar com a gente? E se você tenta só rodar `dotnet build` ele executa o build ou também trava?
