### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pujasharma2058** [dotnet/core#8125]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![tt](https://user-images.githubusercontent.com/60850359/213921030-bf556bba-57cf-49ed-9b05-c5e801d4b473.JPG)

**Comment by mairaw** [comment]
From the screenshot, it seems like you might have run the `dotnet new` command inside the MyApp folder. So had you already run the command before as well? That would create two projects in two different folder levels causing that error message.
One option here would be to start over or just delete the second MyApp folder created inside the first MyApp folder.
