### ISSUE TITLE
Dotnet Tutorial - Deploy a miroservice to Azure not working after deploying to AKS

### ISSUE THREAD

**Issue by Divyesh85** [dotnet/core#8126]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![deploymicroservice_aks_1_issue](https://user-images.githubusercontent.com/17871562/213926713-cde636ed-c1d6-4ac7-b986-b1450f63adfe.PNG)

I am following step by step guide to create dot net microservice and deploy it to azure on AKS cluster

I created microservice from scratch and then containerized it using docker and also created aks cluster in azure. 
I used the default deploy.yaml file provided in the tutorial and updated with my docker image id and executed it. 
`---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: [YOUR DOCKER ID]/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: mymicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: mymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice
`

Not sure if there is anything i need to change here? apart from docker id? 
Last two commands i executed as below
 
![deploymicroservice_aks_2_issue](https://user-images.githubusercontent.com/17871562/213927159-f5d0c1b8-7f22-4c8d-916f-b5bbc9846974.PNG)

Even after executing last command i am not able to see the content of the microservice using the external ip provided after the 
`kubectl get service mymicroservice --watch` command

Can you let me know what can be wrong here?

**Comment by erjain** [comment]
Hi @antonfirsov, Can you please assign it to me? I'll take a look at it and provide the necessary updates.

**Comment by erjain** [comment]
Hi @Divyesh85, thanks for sharing your query. This seems to be some interim issue, I suggest please clean up your old docker images and azure resources and start afresh. To complete the above tutorial first rebuild the docker image using the tutorial: https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/intro and then proceed with this tutorial https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy. I have tested the tutorial and it worked for me as per the below screenshot.
![image](https://user-images.githubusercontent.com/87998741/214656866-b4ecad3b-0fac-44ed-bd8b-d212e222895b.png) . Please feel free to post here in case you are looking for further help.

**Comment by Divyesh85** [comment]
@erjain thanks for checking the issue, indeed the issue is now fixed, it was mostly because I was trying to use the TCP port 80:xxxxx  at the end of the localhost URL which indeed is not necessary in this case.
