### ISSUE TITLE
Can't find dotnet-hostfxr.msi to update/uninstall .NET Core 3.1.417

### ISSUE THREAD

**Issue by bub1ick** [dotnet/core#8128]
### Description
My Windows Update has been failing to install a security patch for my .NET Core SDK 3.1.417 for more than 3 months. I've tried to uninstall this SDK manually from Windows Apps and Features but when I try to do so, it prompts me with this:
![image](https://user-images.githubusercontent.com/51718131/213946764-beda5a6c-133b-40d9-8d0d-cc9f55a7c6db.png)
When I navigated to that folder I saw that there was nothing in it. I tried to google the ways to either download this missing file `dotnet-hostfxr-3.1.23-win-x64.msi` or install a new version of .NET Core, but I succeeded in neither.
I've also tried the .NET Uninstall Tool (`dotnet-core-uninstall`) but the same exact error occurs

### Configuration

OS: Windows 11 21H2 (build 22000.1455)
.NET version: .NET Core 3.1.417

### Other information
I know there's an issue #7093 which recommends uninstalling the .NET Core by hand, but as you can understand that doesn't work.

### What I want
I want to either uninstall this outdated .NET SDK or fix it somehow so that Windows Update doesn't fail.

If you have any questions I can provide as many details as you want.

**Comment by antonfirsov** [comment]
@bub1ick can you collect installation logs using https://aka.ms/vscollect tool? Please run the Collect tool from administrative command prompt. It will create a log archive (`%temp%\vslogs.zip`), that can be shared on OneDrive or Google Drive.

/cc @NikolaMilosavljevic as owner.

**Comment by NikolaMilosavljevic** [comment]
Logs would still be valuable.

@bub1ick can you collect installation logs using https://aka.ms/vscollect tool? Please run the Collect tool from administrative command prompt. It will create a log archive (%temp%\vslogs.zip), that can be shared on OneDrive or Google Drive.

In the meantime I will find the alternate way of cleaning the old installation.

**Comment by NikolaMilosavljevic** [comment]
@bub1ick here are the steps to repair your .NET SDK installation so your Windows update can work. You will also be able to uninstall this product successfully.

1. Download .NET SDK version 3.1.417: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.417-windows-x64-installer
2. Run the downloaded installer and select `Repair` option.
3. Product can now be successfully removed from the system, either using `Settings` app (`Apps` -> `Installed Apps`), or using `Control Panel` (`Uninstall a program`).

**Comment by bub1ick** [comment]
@NikolaMilosavljevic, I'll try to use the Repair option and if it doesn't work, I'll give you some logs

**Comment by bub1ick** [comment]
@NikolaMilosavljevic , OK, so it seems that it actually fixed my problem, so the issue is closed. Thanks for your help a lot!
