### ISSUE TITLE
ScreenCaptureKit hangs on awaiting GetShareableContentAsync

### ISSUE THREAD

**Issue by icanos** [dotnet/core#8129]
### Description
When setting up a minimal .NET Console application and changing **TargetFramework** to **net6.0-macos** and trying to get a list of windows or displays, the application hangs on awaiting the result of GetShareableContentAsync method.

The "same" code works in a minimal Swift xcode project.

Here is the code I'm running, when running using the debugger in Rider, I get "Hello world!" and then nothing more.
https://github.com/icanos/screencapturekit-issue

Simply clone and run `dotnet restore` followed by starting it in Visual Studio or Rider. When running the same dotnet code in the Terminal, no output is given at all, neither "Hello world!" nor a list of applications, nothing. The application also hangs in the Activity Monitor and needs to be quit from there (I guess that is because of the awaiting the results of GetShareableContentAsync).

When running this code, I get "Hello, World!" followed by a complete list of windows:
https://github.com/icanos/screencapturekit-swift

### Configuration

* Which version of .NET is the code running on? **.NET 6.0, .NET 7.0 (tried both)**
* What OS and version, and for Linux, what distro? **MacOS 13.1**
* What is the architecture (x64, x86, ARM, ARM64)? **ARM64**
* Do you know whether it is specific to that configuration? **I am only able to test on an ARM64 Mac**

### Other information

Output of my `dotnet --info`
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: arm64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  6.0.405 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by antonfirsov** [comment]
@icanos can you please re-open this issue under the repository that owns this feature, unfortunately we cannot transfer it to the xamarin org:
https://github.com/xamarin/xamarin-macios
