### ISSUE TITLE
I need to delete my app because I made an app inside an app

### ISSUE THREAD

**Issue by kellyg2** [dotnet/core#8130]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by kellyg2** [comment]
C:\Users\kelly\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\
kelly\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by kellyg2** [comment]
Never mind I figured it out

**Comment by mairaw** [comment]
Glad to hear it
