### ISSUE TITLE
'dotnet' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Hansdier** [dotnet/core#8131]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows 10 Pro
64-bits processor.

Installing dotnet is succesfull, but running CMD: C:\dotnet gives error message: 
"'dotnet' is not recognized as an internal or external command"

i would like to run an SDR program, but this needs dotnet to work.
Many thanks
Hans Dierickx, Aalst, Belgium

**Comment by mairaw** [comment]
Hi @Hansdier! I'm sorry to hear you're having issues.

Are you trying to learn how to code in .NET or trying to make a program to work? The tutorial is intended for folks trying to learn how to code.

Also, did you open a new command prompt after installing.NET?

**Comment by Hansdier** [comment]
Dear Maria,

                Thank you for replying this fast.

                I did open a new command prompt, and the issue is to get a program to run.
                Learning how to code is also wanted, but at a later moment.

                Many thanks!

Kind regards,

Hans Dierickx
Zaakvoerder
Opgelet: vanaf 2019 variabele openingsuren! Zie http://www.kompakt-hifi.be/Openingsuren.html
[logo kompakt-hifi met balk kleur nieuw-1 gesneden]<http://www.kompakt-hifi.be/>
Kompakt-hifi bv.
Korte Zoutstraat 7
9300 Aalst

B.t.w. BE 0437.917.980
Tel: +32(53)70.30.40

***@***.******@***.***>
www.kompakt-hifi.be<http://www.kompakt-hifi.be/>
Kwaliteitsvolle hifi systemen, home cinema systemen, televisie, video projectoren, horeca systemen.
AKG, B&W, Denon, Classé, Cyrus, Marantz, Meridian, Mission,
Mark Levinson, Quad, Rotel, Sim2, Supra, Thorens, Soundstyle, Dreamvision, e.a.
P Please consider your environmental responsibility before printing this e-mail

Van: Maira Wenzel ***@***.***>
Verzonden: maandag 23 januari 2023 23:59
Aan: dotnet/core ***@***.***>
CC: Hans Dierickx ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [dotnet/core] 'dotnet' is not recognized as an internal or external command (Issue #8131)


Hi @Hansdier<https://github.com/Hansdier>! I'm sorry to hear you're having issues.

Are you trying to learn how to code in .NET or trying to make a program to work? The tutorial is intended for folks trying to learn how to code.

Also, did you open a new command prompt after installing.NET?

**Comment by mairaw** [comment]
Thanks for clarifying your goal. Did you get your program to run? If not, can you share the error message you get?
