### ISSUE TITLE
falha de intalação

### ISSUE THREAD

**Issue by JeversonOliveira-DEV** [dotnet/core#8132]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/105593212/214384274-5649265e-9877-4fe7-84ca-59dc3ff0824f.png)

**Comment by mairaw** [comment]
@JeversonOliveira-DEV você baixou a versão arm64 do SDK. Tem certeza que esta é a arquitetura do seu PC?
