### ISSUE TITLE
couldn't create console

### ISSUE THREAD

**Issue by wretched420** [dotnet/core#8136]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.PS C:\Program Files\Microsoft Visual Studio\2022\Professional>  dotnet new console -o MyApp -f net7.0
Template "Console App" could not be created.
Failed to create template.
Details: Access to the path 'C:\Program Files\Microsoft Visual Studio\2022\Professioal  dotnet new console -o MyApp -f net7.0

**Comment by mairaw** [comment]
@wretched420 maybe it's an issue on where you're trying to create the project. Have you tried changing the folder to see if it would allow you to create the project? Typically, you don't want to create new projects under the Program Files folder.
