### ISSUE TITLE
"rosetta error" running on a mac

### ISSUE THREAD

**Issue by docalla** [dotnet/core#8138]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am following the tutorial on a Mac "Apple chip" and got an "rosetta error" pp.aot: attachment of code signature supplement failed: 1 when I run the dotnet commad. 
Resolution: run "dotnet clean"

**Comment by antonfirsov** [comment]
Did `dotnet clean` or a restart of your PC help?

**Comment by docalla** [comment]
"dotnet clean" ran on the terminal command line resolved the issue on a macOS
