### ISSUE TITLE
MAUI-VS2022-No Dependencies

### ISSUE THREAD

**Issue by shayke223** [dotnet/core#8141]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows 11

Hi,
I have these versions of **.Net** on my PC:
![image](https://user-images.githubusercontent.com/56411971/214879735-f797e756-a755-4e94-8a02-24c6866401a1.png)
**VS:** 2022 latest version.

![image](https://user-images.githubusercontent.com/56411971/214880741-e7e1c187-1357-48de-99e7-2e9a64ef994a.png)

As you can see in the picture, there are no dependencies in the project for some reason.
This is a clean project I've just created. 
I tried to use version 6 and 7, same results.
Any ideas why?

Thanks.

**Comment by mairaw** [comment]
We have a tutorial specific for MAUI that would be more appropriate:
https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/intro

Have you installed the maui workload @shayke223?

![image](https://user-images.githubusercontent.com/12971179/214916267-25e7716c-ed4c-4b10-abbd-346a97531488.png)

**Comment by mairaw** [comment]
Also, what does `dotnet workload list` return?

This is what I see on my machine that has MAUI installed:
![image](https://user-images.githubusercontent.com/12971179/214917025-d16be4c5-10c8-4826-a7a6-aa442e95b6f5.png)
