### ISSUE TITLE
Click the Hot Reload button to apply the change to the running app but not working

### ISSUE THREAD

**Issue by Nirajparmar68** [dotnet/core#8143]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by antonfirsov** [comment]
@Nirajparmar68 can you please provide more details about the issue you are experiencing?

**Comment by antonfirsov** [comment]
This looks like a Visual Studio issue/question. Can you please open a ticket here:
https://developercommunity.visualstudio.com/content/problem/post.html?space=8
