### ISSUE TITLE
Create new project creates an empty project

### ISSUE THREAD

**Issue by anupchand** [dotnet/core#8147]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create#
Operating System: Windows 10, 64 bit

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Created a new Blazor App in Visual Studio 2022. The project is empty. No files were created for Blazor App.
![empty project](https://user-images.githubusercontent.com/77399496/215283762-ec2bf31a-dc6e-4ad4-a5c9-c27a8e6f33ea.JPG)

**Comment by anupchand** [comment]
Had multiple instances of DotNet SDK paths under Environment Variable, deleted the x86 entry.

This PC > Properties > Advanced System Settings > Environment Variables > System Variables (Located @ Bottom Section) > Path 

Click Edit ---> Deleted "C:\Program Files (x86)\dotnet" 

Now works as intended.

**Comment by antonfirsov** [comment]
According to https://github.com/dotnet/core/issues/8147#issuecomment-1407475568, this has been resolved.
