### ISSUE TITLE
"Bug" net core(visual basic netcore) regarding drag and drop

### ISSUE THREAD

**Issue by WWWEdobrimCOM** [dotnet/core#8148]
1) Hi all, I've been coding in visual basic .net for years and I managed to convert an entire software to net core. Of course it was easy, just one button and build your application in netcore 6.0 or 7.0 etc.
In my application everything works but I can't figure out why Drag and drop doesn't work. In visual studio, which I've been using for years, I've always created visual basic .net applications but I wanted to take advantage of the netcore (with the dll) to have something more "modern" and for a better performance. The strange thing, I repeat, everything works but drag and drop doesn't work, the dragging the file onto a text box. Instead of pressing the button, to bring up the "show dialog", I dragged the file, with its path, appeared in the text box. Of course I don't understand if it's a bug or simply the visual basic language has been thrown in the toilet and therefore some things in visual basic net core don't work.
I repeat, I did NOT create a new application, I just took my application in visual basic net and converted it to netcore 5. Then from 5, with time and with updates, I brought it to 7.0 netcore. So actually I think it's because everyone is focused with c# or aspnet while visual basic seems uncared for and forgotten.
It seems to me like there was no cure.

2) Another thing that doesn't work besides drag and drop, I was trying to create a remote administration tool (not a rat, something legal, like team viewer but with the build file for the connection, where the question comes out: "Do you want to receive remote connection? etc.). We don't know for what strange ancestral reason, in Visual basic net I was able to create the builder, thanks to the arrays, I created the exe file (for the connection), the customer clicked, the question came out (I had made some changes): "A computer is trying to connect to yours. Do you allow the remote computer to control your pc? Attention and blah blah blah", ok, this is.
I did this to create something that is not a rat but is legal, in fact there is a window that is always open (the controlled computer can always close the connection by closing the window).
This in visual basic .net worked, now in VISUAL BASIC netcore it does NOT work(fails to create exe file for connection).
The exact same application, SAME.
I'm thinking that visual basic is really lame as a language, nothing works.

### Configuration

Netcore 7.0
Windows 10
x64
Visual studio latest version

### Regression?

Visual basic .net  4.8  >>>   Visual basic netcore 5.0 >>>   Visual Basic netcore 6.0 >>> Visual basic netcore 7.0 (latest) Windows forms

### Other information

1) No error, no message. drag and drop works in Visual basic .net but doesn't work in Visual basic netcore

2) No error, no message. creation of a exe file with a builder(made with array ecc) in Visual basic .net works but doesn't work in Visual basic netcore.

**Comment by antonfirsov** [comment]
@WWWEdobrimCOM can you please provide  more details (reproduction steps, minimal repro app / code) for point 1?

I really struggle to understand point 2. It's seems unrelated to point 1. though, therefore it should be triaged and discussed separately.  Can you please open a separate issue, and make sure to provide more details about what are you trying to achieve?  I don't know what do you mean by "build file", "builder", "arrays" etc. In the new issue, please explain step by step what are you trying to achieve in technical means and what is not working. A simple repro application would be very helpful there too.

**Comment by antonfirsov** [comment]
/CC @RussKie: are there any Framework vs .NET Core functional differences that may explain the behavior in https://github.com/dotnet/core/issues/8148#issuecomment-1409432013?

**Comment by RussKie** [comment]
@merriemcgaw @KlausLoeffelmann

**Comment by merriemcgaw** [comment]
@JeremyKuhne might have a thought here. @WWWEdobrimCOM has this ever worked in .NET Core (.NET 5+)? It's not functionality that I'm immediately familiar with (Issue #1)

**Comment by WWWEdobrimCOM** [comment]
> @JeremyKuhne might have a thought here. @WWWEdobrimCOM has this ever worked in .NET Core (.NET 5+)? It's not functionality that I'm immediately familiar with (Issue #1)



Thank you.
It actually worked in visual basic framework 4.8, it's since netcore 5 that it doesn't work

**Comment by KlausLoeffelmann** [comment]
Are you working in your software with `Option Strict On` and `Option Explicit On` to ensure type safety?

**Comment by WWWEdobrimCOM** [comment]
> Few questions:
> 
>     * Are you working in your software with `Option Strict On` and `Option Explicit On` to ensure type safety?
> 
>     * If you set a break point in your (.net 7 version) software in the methods in question, are they ever get hit?
> 
>     * If you wire-up different events for the textbox controls in the .NET 7 version of your software, do they ever get hit?




Option explicit is ON
Option Strict is OFF

No, if I set at break point nothing happens, nothing changes

By events for the textbox, do you also mean type "TextBox1_TextChanged(sender As Object, e As EventArgs) Handles TextBox1.TextChanged"? If you mean that too yes, they get hit

**Comment by KlausLoeffelmann** [comment]
But in the stand-alone-demo, the event gets hit, I assume. So, the bug is even before that: The question is: Why does the event not get hit to begin with?

Can you post the `InitializeComponent` part for the TextBox of the Code Behind file which refuses to accept the drop? Can you also post the `InitializeComponent` Part for the repro, where it is working?

**Comment by WWWEdobrimCOM** [comment]
You mean this? I don't know if what I'm pasting you is right



My app(Not working):


Partial Class Form---
    Inherits System.Windows.Forms.Form


    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub



 Private components As System.ComponentModel.IContainer



 <System.Diagnostics.DebuggerStepThrough()> _


 Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form15))
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.TextBox2 = New System.Windows.Forms.TextBox()
        Me.TextBox3 = New System.Windows.Forms.TextBox()
        Me.TextBox4 = New System.Windows.Forms.TextBox()
        Me.Button2 = New System.Windows.Forms.Button()
        Me.---- = New System.Windows.Forms.ProgressBar()
        Me.Button4 = New System.Windows.Forms.Button()
        Me.Button3 = New System.Windows.Forms.Button()
        Me.Button5 = New System.Windows.Forms.Button()
        Me.Button6 = New System.Windows.Forms.Button()
        Me.Ope = New System.Windows.Forms.OpenFileDialog()
        Me.Cartelle = New System.Windows.Forms.FolderBrowserDialog()
        Me.ImageList1 = New System.Windows.Forms.ImageList(Me.components)
        Me.Label1 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Button1 = New System.Windows.Forms.Button()
        Me.PictureBox1 = New System.Windows.Forms.PictureBox()
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'TextBox1
        '
        Me.TextBox1.AllowDrop = True
        Me.TextBox1.Location = New System.Drawing.Point(235, 32)
        Me.TextBox1.Name = "TextBox1"
        Me.TextBox1.Size = New System.Drawing.Size(404, 23)
        Me.TextBox1.TabIndex = 0
        '

  Friend WithEvents TextBox1 As TextBox
    Friend WithEvents TextBox2 As TextBox
    Friend WithEvents TextBox3 As TextBox


End Class




--------------------------------------------------------------------------------------------------------








New app(working):






Partial Class Form1
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.Button1 = New System.Windows.Forms.Button()
        Me.Button2 = New System.Windows.Forms.Button()
        Me.OpenFileDialog1 = New System.Windows.Forms.OpenFileDialog()
        Me.TextBox2 = New System.Windows.Forms.TextBox()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.SuspendLayout()
        '
        'TextBox1
        '
        Me.TextBox1.AllowDrop = True
        Me.TextBox1.Location = New System.Drawing.Point(178, 59)
        Me.TextBox1.Name = "TextBox1"
        Me.TextBox1.Size = New System.Drawing.Size(315, 23)
        Me.TextBox1.TabIndex = 0
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(31, 62)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(72, 15)
        Me.Label1.TabIndex = 1
        Me.Label1.Text = "Choose file: "
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(221, 319)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(238, 48)
        Me.Button1.TabIndex = 2
        Me.Button1.Text = "Exampe button"
        Me.Button1.UseVisualStyleBackColor = True
        '
        'Button2
        '
        Me.Button2.Location = New System.Drawing.Point(567, 44)
        Me.Button2.Name = "Button2"
        Me.Button2.Size = New System.Drawing.Size(263, 82)
        Me.Button2.TabIndex = 3
        Me.Button2.Text = "Choose file without drag and drop"
        Me.Button2.UseVisualStyleBackColor = True
        '
        'OpenFileDialog1
        '
        Me.OpenFileDialog1.FileName = "OpenFileDialog1"
        '
        'TextBox2
        '
        Me.TextBox2.AllowDrop = True
        Me.TextBox2.Location = New System.Drawing.Point(178, 135)
        Me.TextBox2.Name = "TextBox2"
        Me.TextBox2.Size = New System.Drawing.Size(315, 23)
        Me.TextBox2.TabIndex = 4
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(31, 138)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(115, 15)
        Me.Label2.TabIndex = 5
        Me.Label2.Text = "Changed extension: "
        '
        'Form1
        '
        Me.AllowDrop = True
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1003, 450)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.TextBox2)
        Me.Controls.Add(Me.Button2)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.TextBox1)
        Me.Name = "Form1"
        Me.Text = "Form1"
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents TextBox1 As TextBox
    Friend WithEvents Label1 As Label
    Friend WithEvents Button1 As Button
    Friend WithEvents Button2 As Button
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents TextBox2 As TextBox
    Friend WithEvents Label2 As Label
End Class

**Comment by WWWEdobrimCOM** [comment]
> But in the stand-alone-demo, the event gets hit, I assume. So, the bug is even before that: The question is: Why does the event not get hit to begin with?
> 
> Can you post the `InitializeComponent` part for the TextBox of the Code Behind file which refuses to accept the drop? Can you also post the `InitializeComponent` Part for the repro, where it is working?








You mean this? I don't know if what I'm pasting you is right

My app(Not working):

Partial Class Form---
Inherits System.Windows.Forms.Form

<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
    Try
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
    Finally
        MyBase.Dispose(disposing)
    End Try
End Sub

Private components As System.ComponentModel.IContainer

<System.Diagnostics.DebuggerStepThrough()> _

Private Sub InitializeComponent()
Me.components = New System.ComponentModel.Container()
Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form15))
Me.TextBox1 = New System.Windows.Forms.TextBox()
Me.TextBox2 = New System.Windows.Forms.TextBox()
Me.TextBox3 = New System.Windows.Forms.TextBox()
Me.TextBox4 = New System.Windows.Forms.TextBox()
Me.Button2 = New System.Windows.Forms.Button()
Me.---- = New System.Windows.Forms.ProgressBar()
Me.Button4 = New System.Windows.Forms.Button()
Me.Button3 = New System.Windows.Forms.Button()
Me.Button5 = New System.Windows.Forms.Button()
Me.Button6 = New System.Windows.Forms.Button()
Me.Ope = New System.Windows.Forms.OpenFileDialog()
Me.Cartelle = New System.Windows.Forms.FolderBrowserDialog()
Me.ImageList1 = New System.Windows.Forms.ImageList(Me.components)
Me.Label1 = New System.Windows.Forms.Label()
Me.Label2 = New System.Windows.Forms.Label()
Me.Button1 = New System.Windows.Forms.Button()
Me.PictureBox1 = New System.Windows.Forms.PictureBox()
CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
Me.SuspendLayout()
'
'TextBox1
'
Me.TextBox1.AllowDrop = True
Me.TextBox1.Location = New System.Drawing.Point(235, 32)
Me.TextBox1.Name = "TextBox1"
Me.TextBox1.Size = New System.Drawing.Size(404, 23)
Me.TextBox1.TabIndex = 0
'

Friend WithEvents TextBox1 As TextBox
Friend WithEvents TextBox2 As TextBox
Friend WithEvents TextBox3 As TextBox

End Class

New app(working):

Partial Class Form1
Inherits System.Windows.Forms.Form

'Form overrides dispose to clean up the component list.
<System.Diagnostics.DebuggerNonUserCode()>
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
    Try
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
    Finally
        MyBase.Dispose(disposing)
    End Try
End Sub

'Required by the Windows Form Designer
Private components As System.ComponentModel.IContainer

'NOTE: The following procedure is required by the Windows Form Designer
'It can be modified using the Windows Form Designer.  
'Do not modify it using the code editor.
<System.Diagnostics.DebuggerStepThrough()>
Private Sub InitializeComponent()
    Me.TextBox1 = New System.Windows.Forms.TextBox()
    Me.Label1 = New System.Windows.Forms.Label()
    Me.Button1 = New System.Windows.Forms.Button()
    Me.Button2 = New System.Windows.Forms.Button()
    Me.OpenFileDialog1 = New System.Windows.Forms.OpenFileDialog()
    Me.TextBox2 = New System.Windows.Forms.TextBox()
    Me.Label2 = New System.Windows.Forms.Label()
    Me.SuspendLayout()
    '
    'TextBox1
    '
    Me.TextBox1.AllowDrop = True
    Me.TextBox1.Location = New System.Drawing.Point(178, 59)
    Me.TextBox1.Name = "TextBox1"
    Me.TextBox1.Size = New System.Drawing.Size(315, 23)
    Me.TextBox1.TabIndex = 0
    '
    'Label1
    '
    Me.Label1.AutoSize = True
    Me.Label1.Location = New System.Drawing.Point(31, 62)
    Me.Label1.Name = "Label1"
    Me.Label1.Size = New System.Drawing.Size(72, 15)
    Me.Label1.TabIndex = 1
    Me.Label1.Text = "Choose file: "
    '
    'Button1
    '
    Me.Button1.Location = New System.Drawing.Point(221, 319)
    Me.Button1.Name = "Button1"
    Me.Button1.Size = New System.Drawing.Size(238, 48)
    Me.Button1.TabIndex = 2
    Me.Button1.Text = "Exampe button"
    Me.Button1.UseVisualStyleBackColor = True
    '
    'Button2
    '
    Me.Button2.Location = New System.Drawing.Point(567, 44)
    Me.Button2.Name = "Button2"
    Me.Button2.Size = New System.Drawing.Size(263, 82)
    Me.Button2.TabIndex = 3
    Me.Button2.Text = "Choose file without drag and drop"
    Me.Button2.UseVisualStyleBackColor = True
    '
    'OpenFileDialog1
    '
    Me.OpenFileDialog1.FileName = "OpenFileDialog1"
    '
    'TextBox2
    '
    Me.TextBox2.AllowDrop = True
    Me.TextBox2.Location = New System.Drawing.Point(178, 135)
    Me.TextBox2.Name = "TextBox2"
    Me.TextBox2.Size = New System.Drawing.Size(315, 23)
    Me.TextBox2.TabIndex = 4
    '
    'Label2
    '
    Me.Label2.AutoSize = True
    Me.Label2.Location = New System.Drawing.Point(31, 138)
    Me.Label2.Name = "Label2"
    Me.Label2.Size = New System.Drawing.Size(115, 15)
    Me.Label2.TabIndex = 5
    Me.Label2.Text = "Changed extension: "
    '
    'Form1
    '
    Me.AllowDrop = True
    Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
    Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
    Me.ClientSize = New System.Drawing.Size(1003, 450)
    Me.Controls.Add(Me.Label2)
    Me.Controls.Add(Me.TextBox2)
    Me.Controls.Add(Me.Button2)
    Me.Controls.Add(Me.Button1)
    Me.Controls.Add(Me.Label1)
    Me.Controls.Add(Me.TextBox1)
    Me.Name = "Form1"
    Me.Text = "Form1"
    Me.ResumeLayout(False)
    Me.PerformLayout()

End Sub

Friend WithEvents TextBox1 As TextBox
Friend WithEvents Label1 As Label
Friend WithEvents Button1 As Button
Friend WithEvents Button2 As Button
Friend WithEvents OpenFileDialog1 As OpenFileDialog
Friend WithEvents TextBox2 As TextBox
Friend WithEvents Label2 As Label

End Class

**Comment by KlausLoeffelmann** [comment]
It's difficult to give any additional advice. We would need a working repro project, which isolates the issue, so we can act on it.

**Comment by Codezile** [comment]
I have seen the same bug/feature?? with Winforms. If you have a simple Windows form with a textbox that has AllowDrop=true and the required DragEnter/DragDrop event handlers it is possible to drag/drop to the text box from Windows Explorer, but drag/drop does NOT work from  OpenFileDialog. 
However if the main form itself has AllowDrop=true and the appropriate DragEnter/DragDrop event handlers, then you can drag/drop from an OpenFileDialog to any part of the Form, because the Form itself is the drop target. This seems like an anomaly in the behavior of Explorer vs OpenFileDialog. 
Using this work-around is OK if there is only one control that is the drop target, but if there is more than one target  it's impossible to handle drag/drop events for different controls, because the events are all handled by the parent form.

**Comment by Ashley-Li** [comment]
@merriemcgaw According to @Codezile description, the issue can be reproduced. 
Repro steps:
1. Extract  "[testApp.zip](https://github.com/dotnet/core/files/11168582/testApp.zip)" open it in VS.
2. Build and run the application.
3. Drag and drop a test file into TextBox. -- **It works well.**
4. Drag and drop the test file from OpenFileDialog. --**It doesn't work and there is a ban icon.**
5. Stop debugging and go back to TestApp's Form designer, set the Form's AllowDrop property to true.
6. Build and run the application.
7. Drag and drop the test file from OpenFileDialog. --**It works.**
![8148_repro](https://user-images.githubusercontent.com/56664234/230336149-52d8c3df-f2c9-4360-9bf9-dc12f48199ee.gif)

**Comment by Codezile** [comment]
At step 5 you also need to add the event handlers for DragEnter and
DragDrop to the main form. They can be the same handlers as already exist
for the TextBox.

**Comment by Ashley-Li** [comment]
@Codezile Thanks for your reply. The step5 in the gif is not shown, but what you said was added to the program in advance, you can see after the step7
