### ISSUE TITLE
How to start Visual Studio

### ISSUE THREAD

**Issue by uekouta** [dotnet/core#8152]
Problem encountered on https://dotnet.microsoft.com/ja-jp/learn/games/unity-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm learnig Unity and programing on this tutrial.
Now, I can make Spincube script 
Next, I want to start Visual Studio by double click Spincube but Visual Studio doesn't start.

Please tell me how to slove this probelm.

**Comment by carlossanlop** [comment]
@uekouta did you install Visual Studio already?
