### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by simphiwe-mabaso** [dotnet/core#8157]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi. I am experiencing a segmentation fault (core dumped) when trying to create a new webapp using dotnet.

**Comment by simphiwe-mabaso** [comment]
I installed using this command:

sudo chmod +x ./dotnet-install.sh

**Comment by simphiwe-mabaso** [comment]
I'm sorry, I installed using this command to get the latest version:

./dotnet-install.sh --version latest

**Comment by DeafMan1983** [comment]
Hello you have same problem. My goal is like you have received "segmentation fault" If I understand correctly.

I have readden Ubuntu 20.04 - trusted repository and It got error if I already install dotnet-*-6.0 and dotnet-*-7.0 then I ran dotnet new console and it shows like this:
```
$ dotnet new console -o Test --framework net7.0

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.102

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Segmentation fault (core dumped)
```

I am using Ubuntu 20.04 x64 ( only amd64 )
dotnet from repository of microsoft
