### ISSUE TITLE
.NET WebApp Unhandled Exception

### ISSUE THREAD

**Issue by simphiwe-mabaso** [dotnet/core#8158]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: linux

Hi. I am experiencing a problem when trying to create a new dotnet webapp. Below is the exception. 
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Diagnostics.Tracing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted (core dumped)

**Comment by mairaw** [comment]
Sorry to hear you're running into issues @simphiwe-mabaso.
Which method did you use to install Linux on your machine?

**Comment by simphiwe-mabaso** [comment]
I am using a campus laptop which came pre-installed with Linux, Pop!_OS
22.04 LTS
