### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Nagendrababunc** [dotnet/core#8160]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
![Screenshot 2023-02-03 223158](https://user-images.githubusercontent.com/114580890/216662969-a7ee5b55-6ae3-4143-aa5d-9aa1c2eab3a2.png)

**Comment by carlossanlop** [comment]
Have you installed .NET in your machine already? If you did, make sure to close the CMD window and open a new one to ensure the environment variables know where to locate the dotnet executable.
