### ISSUE TITLE
i did not get time  print 

### ISSUE THREAD

**Issue by archnayadav804** [dotnet/core#8164]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Not enough information shared. What's the problem you encountered?

**Comment by mairaw** [comment]
Did you save the changes you made to the Program.cs file? Can you share the contents of it?
