### ISSUE TITLE
No project gets created in the solution

### ISSUE THREAD

**Issue by deniz-tuncbilek** [dotnet/core#8165]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/95399157/216878600-8f4b7ad1-cf3d-42af-9c8c-9b91650ee3cb.png)

**Comment by carlossanlop** [comment]
> No project gets created in the solution

Did you follow the steps described in the instructions? Can you share which step specifically didn't work?

**Comment by deniz-tuncbilek** [comment]
Hi Carlos, thanks for responding to this. Here are the steps I followed as per in the [tutorial](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install) 

The project folder and contents are created as shown in the last screenshot below but they not visible under the solution on Visual Studio. I also tried placing the solution and project in the same directory but that didn't make a difference.

![1](https://user-images.githubusercontent.com/95399157/217076843-0d7dec44-a437-4271-82d6-34fdc22b1caf.png)
![2](https://user-images.githubusercontent.com/95399157/217076854-da2f226a-3e63-4d3a-94c7-d591ecad2e19.png)
![3](https://user-images.githubusercontent.com/95399157/217076867-d0038762-c0f5-43ad-b47b-593f78fc8d74.png)
![4](https://user-images.githubusercontent.com/95399157/217076876-9c040c58-e360-4b76-94a5-97e1ec7d8ac3.png)
![5](https://user-images.githubusercontent.com/95399157/217076910-3d74fb88-d7a6-41d8-b1c9-6491ae86d6ec.png)

**Comment by mairaw** [comment]
Thanks for sharing more information. So, what does the project look like when you open it in Visual Studio? What do you see in Solution Explorer?
