### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path '/Users/lijj/.local/share/NuGet' is denied.

### ISSUE THREAD

**Issue by unlceli** [dotnet/core#8166]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
