### ISSUE TITLE
Problem with .net core

### ISSUE THREAD

**Issue by RickyZhang98** [dotnet/core#8169]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi, I have downloaded the latest .net core from our website. However, when I'm trying to open an .exe file, it bumps up a window every time saying "to run this application, you must install .NET core. Would you like to download it now?". I'm pretty sure the installation is correct and the codes looks almost the same with the ones on the tutorial webpage. Also when I tried to click on Yes from the pop-up window, nothing actually happens. I also try to run the .exe file from terminal and the same message shows up. 

The Software I'm trying to open is from here:
https://github.com/joeltroughton/QuadSMU_control/releases/tag/v0.12
The QuadSMU_Control.exe one.

Could you help me to see how I can solve this problem?

thanks

**Comment by RickyZhang98** [comment]
@mairaw

**Comment by mairaw** [comment]
Can you share a screenshot of the pop-up window you're getting? Or maybe the URL that is giving you on the terminal.

Usually, when you click yes, it would take you to the right page to download the appropriate runtime, but maybe there's a bug in our logic here. If you can share more info so we can investigate, it would be great.
