### ISSUE TITLE
Add support for Ubuntu 23.04 (Lunar Lobster)

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8171]
This issue is created to track progress for the work to enable Ubuntu 23.04 support for .NET 7.0 and .NET 6.0

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [ ] [CoreCLR/CoreFX] Runtime / RID Support update  
- [ ] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable) 
- [ ] [Infra] Replace docker tags used in builds across repos and branches
- [ ] [CLI team] Update CI legs to latest updated Dockerfile 
- [ ] [All teams] Update test infrastructure to support the new version
- [x] ~[Acquisition] Add support within nightly repos~
- [x] ~[Acquisition] Deploy to master (GA) during next patch release cycle~

## Release team:
- [ ]  Notify .NET Core teams regarding new OS release
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by mthalman** [comment]
I've updated the checklist to remove publishing of official Docker images. For Ubuntu, we only publish official Docker images for LTS versions which 23.04 is not.

**Comment by MattGal** [comment]
@michellemcdaniel / @ChadNedzlek this isn't happening til approximately April.  I get tagged on these for docker creation, FYI for your current epic.

**Comment by michellemcdaniel** [comment]
Thanks for letting us know. We may be fully migrated (should be?) by then, so hopefully we can bypass the "do it in 2 places" bit

**Comment by delanym** [comment]
We're three months into Lobster's nine month lifespan. I couldn't find a ticket for Kinetic Kudu. Perhaps you should just say you only support LTS distributions?
