### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SuchiraSumon** [dotnet/core#8175]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error: Invalid option(s):
-f net7.0
   'net7.0' is not a valid value for -f. The possible values are:
      net6.0   - Target net6.0

**Comment by mairaw** [comment]
Hi @SuchiraSumon! The tutorial is written to work with the .NET 7 SDK. From the error message, it seems you have .NET 6 installed. Can you install .NET 7 SDK and try again?

Another option would be to run the command with net6.0
`dotnet new webapp -o MyWebApp --no-https -f net6.0`

We can't guarantee though that the tutorial will work exactly the same.
