### ISSUE TITLE
dotnet no se reconoce como comando en simbolo de sistema

### ISSUE THREAD

**Issue by 1Eazy-E** [dotnet/core#8178]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
From the tutorial in Spanish at https://dotnet.microsoft.com/es-es/learn/aspnet/hello-world-tutorial/install

¿Tiene un error?
Si recibe un error ”dotnet” no se reconoce como un comando interno o externo, asegúrese de que ha abierto un nuevo comando del sistema.

Have you done that?
