### ISSUE TITLE
Could not connect to local host

### ISSUE THREAD

**Issue by GrayCoHub** [dotnet/core#8179]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
