### ISSUE TITLE
 'dotnet' is not recognized 

### ISSUE THREAD

**Issue by mimuhareb2002** [dotnet/core#8183]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows 11 home version 22H2
the problem 'dotnet' is not recognized as an internal or external command, operable program or batch file.

**Comment by carlossanlop** [comment]
Did you install the .NET SDK? Did you make sure to close and reopen the cmd window so the environment variables get properly captured?

**Comment by tarekgh** [comment]
Ensure to install .NET first. https://dotnet.microsoft.com/en-us/download/dotnet/7.0
