### ISSUE TITLE
Segmentation fault on Linux when running dotnet command

### ISSUE THREAD

**Issue by yassine-hamadou** [dotnet/core#8184]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: linux

My linux version is version 22.10 and I get a segmentation whenever I type dotnet follow by an option

**Comment by mairaw** [comment]
Apologies for not replying sooner. Is this still an issue for you? Was this a snap install? If so, I'd try different methods.
