### ISSUE TITLE
Solve this issue

### ISSUE THREAD

**Issue by MarionJhon** [dotnet/core#8186]
Template "Console App" could not be created.
Failed to create template.
Details: Access to the path 'C:\WINDOWS\system32\MyApp' is denied.

**Comment by thespragg** [comment]
Are you trying to run the command in the system32 directory?

**Comment by mairaw** [comment]
You should change the directory to create new apps. system32 is protected.

**Comment by tarekgh** [comment]
Closing per @mairaw reply as it looks this is the case.
