### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by smithersonian** [dotnet/core#8196]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

C:\Users\johnn\MyApp>dotnet run
C:\Users\johnn\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statem
ents. [C:\Users\johnn\MyApp\MyApp.csproj]

For some unknown reason my computer failed to run this even though I went through the tutorial as instructed.
Provide details about the problem you're experiencing. Include your operating system version, exact error 
message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @smithersonian! I'm sorry you're running into some issues. 

That error means you have two projects inside that directory. Usually, when I see that happen, the `dotnet new` command was run twice, once inside the MyApp folder.
You could try to check if you have two projects inside the MyApp folder (you'd see another folder named MyApp inside of it). 

Or you can try to delete and run everything from the start again. 

Let us know if this helps! And please share a screenshot of the contents of the MyApp folder if you continue to get that error. (you can run the dir command for example)
