### ISSUE TITLE
7.0.200 publish bug

### ISSUE THREAD

**Issue by mkalinski93** [dotnet/core#8198]
We have a critical bug found for the SDK version 7.0.200 in our Github action pipeline.

We have a large Asp.Net Core MVC Project that has several ViewComponents implemented.
When we publish with 7.0.200 the ViewComponents just disappear and won´t render.
We can fix this issue when we rollback to SDK Version 7.0.103.

I cannot pinpoint the exact problem but I just wanted you to let you know that there´s something breaking ViewComponents.

**Comment by campersau** [comment]
See https://github.com/dotnet/sdk/issues/30624

**Comment by mkalinski93** [comment]
I assume you want to direct me to the breaking change for the output parameter.
If that could cause the ViewComponent to break (Partial views just works fine btw) - then I take that for granted and we wait for future releases.
