### ISSUE TITLE
C:\Users\admin\MyApp>Console.WriteLine("Hello, World!"); 'Console.WriteLine' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by KMJ991** [dotnet/core#8199]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tarekgh** [comment]
Please provide more information about the steps you did to produce the issue and the detailed error messages.

**Comment by tarekgh** [comment]
`Console.WriteLine("Hello, World!")` just needs to be written in the code cs file and not a command you execute from the command prompt. Please try to follow the tutorial from scratch and make sure you execute every step in the tutorial.
