### ISSUE TITLE
Carify .NET native support

### ISSUE THREAD

**Issue by Genbox** [dotnet/core#82]
You could build native applications in RC1, even if only very simple applications worked. Could you please clarify what the status of the native support is, and what the roadmap is? The [High Level Engineering Plan](https://github.com/dotnet/corert/blob/master/Documentation/high-level-engineering-plan.md) over at CoreRT has not changed for 7 months.

Any time estimate on when we can expect .NET Core applications/libraries to run natively on the Windows platform?

**Comment by blackdwarf** [comment]
@richlander can you please comment on the overall roadmap for CoreRT?

**Comment by VladimirAkopyan** [comment]
This is interesting. Should we, at some point, expect cross-platform native executables? 
Or is .net Native team scrambling, trying to get it to work well for UWP?

**Comment by Genbox** [comment]
@VladimirAkopyan I highly doubt there will be cross-platform native assemblies. The assemblies requires the C++ runtime specific to the platform you are using, and the PE/ELF compatibility has always been an issue. Emulation with Wine is the closest we come to native cross platform assemblies, as it emulates running PE files on a layer of Win32 API written to interact with the Linux subsystem.

.NET Native on the other hand is an ongoing process of compiling IL code to native assemblies. It works fine at the moment, and the CoreRT team is [https://github.com/dotnet/corert](hard at work) improving it.

**Comment by aL3891** [comment]
Just to clarify, I think we'll never see a single native assembly work cross platform, but the CoreRT team is working on having native compilations for multiple platforms. So you'll be able to natively compile .net core apps for Linux, it will just be a different binary than the windows one.

**Comment by VladimirAkopyan** [comment]
@Genbox my bad. Bascally what I means is - is .Net Native working / ready now? 
I couldn't find it on the roadmap / documentation.

**Comment by Genbox** [comment]
@VladimirAkopyan No, it is neither working or ready at the moment. They changed from project.json to MSBuild templates which seems to break everything related to .NET native. Before the change the build tools did have a native switch (dotnet build --native) which generated a working binary (I've tested Windows and Linux). However, since the template change they have retracted .NET Native from all the tools until it is ready to be released.

**Comment by Petermarcu** [comment]
The best way to track the work on .NET Native is on the repo: https://github.com/dotnet/corert. Feel free to open issues and even contribute there if you'd like. I'm going to close this issue here. You can see [here] (https://github.com/dotnet/corert/blob/master/Documentation/prerequisites-for-building.md) for example, there are instructions for Ubuntu and OSX.

**Comment by Deilan** [comment]
Here's the corresponding issue in that repo: https://github.com/dotnet/corert/issues/6402
