### ISSUE TITLE
error cs8802: only one compilation unit can have top-level statements

### ISSUE THREAD

**Issue by vishvabhuva** [dotnet/core#8200]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tarekgh** [comment]
There is not enough information here to act on it. Please provide all detailed information including the reproducing steps and the error messages you are getting.
