### ISSUE TITLE
zsh: command not found: dotnet

### ISSUE THREAD

**Issue by rinagladkikh** [dotnet/core#8203]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I've downloaded SDK 6.0.406 x64 for Apple M1 Pro
I've installed extensions C# 

irinagladkikh@MacBook-Pro-Irina Examples % dotnet new console
zsh: command not found: dotnet

**Comment by tarekgh** [comment]
Make sure after installing the SDK, ensure the SDK installation folder is part of your path. You may issue the command `echo $PATH` from the terminal to set what current folders are set in the path.
