### ISSUE TITLE
.Net console installation failure report

### ISSUE THREAD

**Issue by kms-cse** [dotnet/core#8205]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Everytime I ran a line of command as you can see from the image attached below, I was repetitively undergoing these lines of warning even though I had already installed .Net Core downloaded from this link 'https://dotnet.microsoft.com/en-us/download/dotnet/3.1'. I really have no idea how to proceed with running the C# program in Visual Studio Code without having .Net console installed. Can you help me do so, please?

![Net console installation failure report](https://user-images.githubusercontent.com/96127042/219983434-1ab1ca41-6cc3-4c5a-9c13-bea11444eb01.png)

**Comment by tarekgh** [comment]
Net Core 3.1 is not supported any more. Please try to install .NET 6.0 or 7.0 and try again. https://dotnet.microsoft.com/en-us/download

**Comment by kms-cse** [comment]
Thank you for your response.
