### ISSUE TITLE
i download the .net but  but i dont know how to installa pleas send me the link which is related to installing the .net 7

### ISSUE THREAD

**Issue by sharanabasavamp** [dotnet/core#8208]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tarekgh** [comment]
Here is the link https://dotnet.microsoft.com/en-us/download. Clicking on `.NET SDK ...` button should download `.exe` file which you can just run it and it will install the .NET for you.
