### ISSUE TITLE
Error when editing code

### ISSUE THREAD

**Issue by MyHybrids9** [dotnet/core#8209]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I tried to edit my code and now keep running into this error:

"C:\Users\bridg\MyApp\MyApp.csproj(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

The build failed. Fix the build errors and run again."

Up until this point it had been running fine. Before this, it gave me an error because it expected my code to be found under "MyApp.csporj" so I changed the file name to that, yet it still says Program in the file directory.

**Comment by tarekgh** [comment]
The error suggests the project file is corrupted. Please try again starting from https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install and follow the steps and this should work.
