### ISSUE TITLE
support-phase for .NET 8 difference in releases-index.json and release-metadata

### ISSUE THREAD

**Issue by msallin** [dotnet/core#8220]
The releases-index contains

{
            "channel-version": "8.0",
            "latest-release": "8.0.0-preview.1",
            "latest-release-date": "2023-02-21",
            "security": false,
            "latest-runtime": "8.0.0-preview.1.23110.8",
            "latest-sdk": "8.0.100-preview.1.23115.2",
            "product": ".NET",
            "release-type" : "lts",
            **"support-phase": "active",**
            "eol-date": null,
            "releases.json": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/8.0/releases.json"
        }

https://raw.githubusercontent.com/dotnet/core/main/release-notes/releases-index.json

And the releases.json

  "channel-version": "8.0",
  "latest-release": "8.0.0-preview.1",
  "latest-release-date": "2023-02-21",
  "latest-runtime": "8.0.0-preview.1.23110.8",
  "latest-sdk": "8.0.100-preview.1.23115.2",
  "release-type" : "lts",
  **"support-phase": "preview",**
  "lifecycle-policy": "https://aka.ms/dotnetcoresupport",

https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/8.0/releases.json

**Comment by agocke** [comment]
@rbhanda The index is incorrect. The support phase should be preview.

**Comment by msallin** [comment]
It's fixed. Ty!
