### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by YuT88** [dotnet/core#8225]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I type  ~$ dotnet  and I get zsh: command not found: ~$

**Comment by tarekgh** [comment]
The error suggests you didn't install the .NET SDK. try to install it first from https://dotnet.microsoft.com/en-us/download/dotnet/7.0
