### ISSUE TITLE
Visual Studio 17.4.5 no older net core targeting

### ISSUE THREAD

**Issue by RaHorusFreak** [dotnet/core#8232]
### Description

I cannot see older net core sdk in projects template (below .net core 2.1).

### Configuration

.Net core environment path order: 
![image](https://user-images.githubusercontent.com/52793512/221389818-2ae6ffec-e5fa-48b2-a77c-ecdfb2d2561d.png)

Installed SDKs (same for x86):
![image](https://user-images.githubusercontent.com/52793512/221389875-2e2f9355-5551-4f7b-9f2a-0fd4af715611.png)

Aviable versions in VS:
![image](https://user-images.githubusercontent.com/52793512/221389909-47f157aa-4aef-4fa0-9cf2-ff8fb7de0619.png)

### Question

It´s there any approach similar to making aviable .Net Framework 4 and 4.5 for VS2022, or it´s necessary a VSIX?

### VS info

Microsoft Visual Studio Enterprise 2022
Versión 17.4.5
VisualStudio.17.Release/17.4.5+33403.182
Microsoft .NET Framework
Versión 4.8.09032

Versión instalada: Enterprise

Herramientas de arquitectura y modelado   00482-10000-00261-AA474
Diagramas y herramientas de análisis de Microsoft Architecture

Visual C++ 2022   00482-10000-00261-AA474
Microsoft Visual C++ 2022

Adaptador de prueba para Boost.Test   1.0
Habilita las herramientas de prueba de Visual Studio con las pruebas unitarias escritas para Boost.Test. Los términos de uso y los avisos de terceros están disponibles en el directorio de instalación de la extensión.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Arduino IDE for Visual Studio by Visual Micro   22.0
Visual Micro is an Arduino Compatible IDE for Visual Studio 2022. For more information and forum please visit www.visualmicro.com.

ArrayPlotter   0.12
Fast array visualisation from within the debugger for C#/C++

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.337.25083
ASP.NET and Web Tools

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.4.337.25083
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

BusinessObjectEditor   1.0
Information about my package

ChatGPT   0.1.0
Introducing the Chat GPT extension for Visual Studio. This powerful tool utilizes the cutting-edge language model of Open AI to make code modifications quickly and easily. Simply type in a command and watch as the extension automatically updates your code to match your specifications. Say goodbye to tedious manual coding and hello to efficient, effective coding with the Chat GPT extension.

Child Process Debugging Power Tool   1.0
Power tool to add child process debugging to Visual Studio.

Clean Solution   1.4.35
Cleans up the solution for the next time you open it. Closes open documents and collapses folders automatically when a solution is being closed.

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

CodeRush for Roslyn   22.2.3.0
DevExpress CodeRush for Roslyn package.

CodeRush for Roslyn Tool Windows   22.2.3.0
DevExpress CodeRush for Roslyn Tool Windows package.

Collapse Comments   2.2.1
Improve the way you work with comments in code by easily (& automatically) expanding and collapsing comments.

Color Preview   1.0.22
Shows a color preview in front of all named colors, hex, rgb and hsl values in CSS files.

Command Explorer   1.1
Provides a tool window to explorer all commands, groups and menus to help extension authors place commands/buttons in the desired location

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

Conveyor by Keyoti   1.0
Allows you to access your web applications from other machines, even if hosted on the development web server.

Cookiecutter   17.0.22263.6
Proporciona herramientas para buscar, crear instancias y personalizar plantillas con el formato de Cookiecutter.

CreateLayoutWizard   1.0
Create layout wizard.

Depuración de volcados de memoria básicos de Linux   1.0.9.33403
Habilita la depuración de volcados de memoria básicos de Linux.

DevExpress Dashboard Extension   1.4
A Visual Studio extension that invokes the Dashboard Designer editor.

DevExpress Reporting Extension   1.4
A Visual Studio extension that invokes the Report Designer editor for report definition VSREPX files.

DevExpress Reporting Tools Extension   1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

DgmlTestMonitor   1.0
This package watches the DgmlTestRunner output and animates the current state of the test in the associated DGML test diagram.

Dotfuscator Community Edition   6.5.0+76d4669002
PreEmptive Protection - Dotfuscator CE

EmojiSense   1.0.11
IntelliSense for emojis in code comments and string for all languages

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Differ   3.0.49
The easiest way to diff two files directly in Solution Explorer

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

Herramientas comunes de Windows Azure   1.10
Ofrece servicios comunes para su uso con los servicios móviles de Microsoft Azure y Microsoft Azure Tools.

Herramientas de Azure App Service v3.0.0   17.4.337.25083
Herramientas de Azure App Service v3.0.0

Herramientas de C#   4.4.0-6.23101.15+72dbad1d47f6065730a65c97621a4e93dc3efdf2
Los componentes de C# utilizados en el IDE. En función del tipo de proyecto y la configuración, se podría utilizar una versión diferente del compilador.

Herramientas de Node.js   1.5.40817.1 Commit Hash:66443775f9f3b1d8f8fee47af5002828b346688d
Agrega compatibilidad con el desarrollo y la depuración de aplicaciones de Node.js en Visual Studio

Herramientas de TypeScript   17.0.10921.2001
Herramientas de TypeScript para Microsoft Visual Studio

Herramientas de Visual Basic   4.4.0-6.23101.15+72dbad1d47f6065730a65c97621a4e93dc3efdf2
Los componentes de Visual Basic utilizados en el IDE. En función del tipo de proyecto y la configuración, se podría utilizar una versión diferente del compilador.

Herramientas de Visual F#   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Herramientas de Microsoft Visual F#

Herramientas de Workflow Manager 1.0   1.0
Este paquete contiene los componentes de integración de Visual Studio necesarios para Workflow Manager.

ILNumerics Ultimate VS - Visual Studio Extension   A5FA4B2B-B9E6-4AA3-975C-4C64AB9F2C43
ILNumerics Extension to Visual Studio. Adds graphical debugger visualizers, tool windows and licensing features for ILNumerics. This package supplements the ILNumerics infrastructure. Visit: https://ilnumerics.net for details.

IncrediBuild Build Acceleration   1.6.0.2
IncrediBuild effectively reduces compilation and development times by up to 90%.

Insert Guid   1.3.6
Makes it super easy to insert a new GUID into any editor and input field

Inspección de imágenes   1.0

JSON Schema Tools   1.0.11
Allows you to easily generate a schema file from a JSON file and generate a JSON file with dummy data based on a schema file.

Marcos de trabajo y herramientas de ASP.NET Web 2012   17.4.337.25083
Para obtener más información, visite https://www.asp.net/

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools para Visual Studio   2.9
Compatibilidad con proyectos de Azure Cloud Services

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft SARIF Viewer   3.0.115.33558
Visual Studio Static Analysis Results Interchange Format (SARIF) log file viewer

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

NpgsqlVSPackage Extension   1.0
NpgsqlVSPackage Visual Studio Extension Detailed Info

Office Developer Tools para Visual Studio   17.0.32915.00
Microsoft Office Developer Tools para Visual Studio

PeachPie Visual Studio Extension   1.0.11
PeachPie is the PHP language compiler for .NET & .NET Core. It allows for building, integrating, running and debugging of legacy PHP code bases to .NET platform. PeachPie outputs regular .NET assemblies not relying on the native PHP runtime.

This extension provides project templates and other development tools for the PeachPie platform.

Python con Pylance   17.0.22263.6
Permite usar IntelliSense, proyectos, plantillas, depuración, ventanas interactivas y otras características para desarrolladores de Python.

Python: compatibilidad con proyectos de VC   17.0.21344.1
Ofrece compatibilidad para iniciar proyectos de C++ con la depuración de Python habilitada.

Python: compatibilidad de Django   17.0.22263.6
Permite usar plantillas y facilita la integración con el marco web de Django.

Python: compatibilidad de la generación de perfiles   17.0.22263.6
Compatibilidad con la generación de perfiles para proyectos de Python.

Razor (ASP.NET Core)   17.4.5.2306901+ce80d539513291a2065f47028bef14b497dc2443
Proporciona servicios de lenguajes para ASP.NET Core Razor.

Regex Editor   1.0
.Net Regular Expressions tools

Silverlight for Visual Studio 2017, 2019, and 2022   1.0
Unofficial support for Silverlight projects in Visual Studio 2017, 2019, and 2022

SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

Solution Colors   1.1.44
Allows you to associate a color with a solution and display it in various locations within Visual Studio. Inspired by the Peacock extension for VS Code.

Solution Secrets 2022   1.1.3
This extension allows you to synchronize Visual Studio solution secrets across different development workstations.

SQL Server Data Tools   17.0.62302.03180
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

SVG Viewer   1.0.16
Makes it much easier to work with SVG files by showing a live preview in the bottom-right corner of the code window

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter para Google Test   1.0
Habilita las herramientas de prueba de Visual Studio con las pruebas unitarias escritas para Google Test. Los términos de uso y los avisos de terceros están disponibles en el directorio de instalación de la extensión.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Tweaks 2022   1.1.143
A collection of minor fixes and tweaks for Visual Studio to reduce the paper cuts and make you a happier developer

Unitverse Extension   0.177
Generates better unit test boiler plate for existing code

UpdateWebResources Extension   1.0
UpdateWebResources Visual Studio Extension Detailed Info

Visual C++ for Cross Platform Mobile Development (Android)   17.0.33006.217
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.33403
Visual C++ for Linux Development

Visual C++ para el desarrollo móvil multiplataforma (iOS)   17.0.33006.217
Visual C++ para el desarrollo móvil multiplataforma (iOS)

Visual Find References Extension   0.49
Presents a graphical, additive reference finding experience

Visual Studio Color Theme Designer   1.0
Allows users to create and edit Visual Studio themes. Themes can customize colors used for menus, toolbars, tabs, titlebars, the text editor, and other environment colors.

Visual Studio IntelliCode   2.2
Desarrollo asistido por AI para Visual Studio.

Visual Studio Tools para Unity   17.4.3.0
Visual Studio Tools para Unity

VisualStudio.DeviceLog   1.0
Información sobre el paquete

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput64   2022.2
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   17.4.0.315 (d17-4@beed03a)
Extensión de Visual Studio para habilitar la implementación de Xamarin.iOS y Xamarin.Android.

Xamarin Designer   17.4.0.138 (remotes/origin/d17-4@d36bba3cc9)
Extensión de Visual Studio para habilitar las herramientas de Xamarin Designer en Visual Studio.

Xamarin Templates   17.4.2 (c457c97)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Xamarin.iOS and Xamarin.Mac SDK   16.2.0.2 (956a059ba)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

ZenCoding   1.2.20
Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.

**Comment by liveans** [comment]
Hello,

Can you open this issue on [VS Dev Community](https://developercommunity.visualstudio.com/content/problem/post.html?space=8) website?

Closing.

**Comment by RaHorusFreak** [comment]
The workaround is based on THOMAS LEVESQUE's .NET Framework approach (https://thomaslevesque.com/2021/11/12/building-a-project-that-target-net-45-in-visual-studio-2022/).
As older .NET Frameworks SDKs are missing from C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework, the same occurs with older .NET Core Templates.

First I must explain the differences between the two approaches. For the .NET Framework it becomes very difficult to obtain the SDKs for each version below 4.5.1, so it is almost mandatory to extract the libraries from the nuget packages of the series: Microsoft.NETFramework.ReferenceAssemblies.net(ver), to then extract (as compressed files) the contents of build\.NETFramework\v(ver)\ to the local system folder.

But with .NET Core the scenario is somewhat simpler: It's easy to get the SDKs for .NET Core from https://github.com/dotnet/core/tree/main/release-notes/download-archives and install them on our OS without problems. And here comes the problem: Visual Studio 17 looks for the templates for project platform initialization in a folder (C:\Program Files (platform)\dotnet\templates) that does not contain templates from versions prior to .NET Core 3.0. However, these older versions have their own templates inside their respective folders: C:\Program Files (platform)\dotnet\sdk\(ver)\Templates.

So, we just have to copy the content of the templates folder (C:\Program Files (platform)\dotnet\sdk\(ver)\Templates), to a subdirectory named with the name of the .NET Core version in the global templates folder (C:\Program Files (platform)\dotnet\templates\(ver)).

And that's how we're able to build software for .NET Framework versions from 2.0 to 4.8.x (I haven't found a compatible SDK for 1.0) and .NET Core + .NET from 1.0 to 7.x, keeping customers comfortable in their environments, and us as developers with a single version of Visual Studio.

![Sin título](https://user-images.githubusercontent.com/52793512/222945072-c13c624a-3746-4d7d-bd19-30376028dac4.png)

![Sin título2](https://user-images.githubusercontent.com/52793512/222945079-ae1a4c84-344a-40be-a930-ecc0a291fee6.png)
