### ISSUE TITLE
Problemas na Instalação do .NET

### ISSUE THREAD

**Issue by antoniocarlosrodriguessousa** [dotnet/core#8241]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by liveans** [comment]
There isn't sufficient information, please provide exact error message, exact operating system version and anything relevant with that.

**Comment by mairaw** [comment]
@antoniocarlosrodriguessousa você pode nos dizer quais são os problemas que você está tendo com a instalação do .NET?
