### ISSUE TITLE
-bash: !": event not found

### ISSUE THREAD

**Issue by SarvaniNandipati** [dotnet/core#8244]
The problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: macos

(base) Sarvanis-Air:MyApp sarvaninandipati$ Console.WriteLine("Hello, World!");
-bash: !": event not found

Can someone help me with this issue?

![Screenshot 2023-02-28 at 2 07 37 PM](https://user-images.githubusercontent.com/79523093/221954383-54d0e6cf-b7da-471f-af37-f6067bc26487.png)

**Comment by liveans** [comment]
Hello,

You're trying to run
```c#
Console.WriteLine("Hello, World!");
```
as a command on your terminal.

Instead, you should create your project with `dotnet new console -o MyApp -f net7.0` as instructed in tutorial.
After that, if you click the continue button, you'll see `dotnet run` command to run it inside your directory.

**Comment by mairaw** [comment]
Let us know if that helped or if you still need more information.
