### ISSUE TITLE
dotnet run doesn't print out hello world

### ISSUE THREAD

**Issue by KevinMi2023p** [dotnet/core#8246]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/70293835/221993113-b616e6db-0c8c-4e8b-8908-831fdade9563.png)

**Comment by mairaw** [comment]
Can you share what `dotnet --info` returns?

@baronfel any suggestions here on why `dotnet run` doesn't return anything?
