### ISSUE TITLE
Supported .NET 8 Preview installer

### ISSUE THREAD

**Issue by daniloopinheiro** [dotnet/core#8250]
### Description

Kali GNU/Linux Rolling is not supported by the .NET 8 Preview installer.

### Configuration

OS: Kali GNU/Linux Rolling x  
Kernel: 6.1.0-kali5-amd64

**Comment by liveans** [comment]
Did you try [linux packages](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)?
Can you provide your error messages, and more information related to the issue?
