### ISSUE TITLE
There is no Program.cs file

### ISSUE THREAD

**Issue by RENCONGZHENG** [dotnet/core#8251]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by liveans** [comment]
Hello,

[Create Hello World App](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create), you can create your project/app using these steps and you can find `Program.cs` in the folder of your project.
