### ISSUE TITLE
Couldn't find an installed template that matches the input, searching online for one that does...

### ISSUE THREAD

**Issue by ZJL0027** [dotnet/core#8252]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by ZJL0027** [comment]
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet

**Comment by liveans** [comment]
Hello,

The command should be `dotnet new console -o MyApp -f net7.0`
Can you double check if you're trying the correct command?

**Comment by ZJL0027** [comment]
Thanks for reply. I dobule checked the command, it's still not working.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnet/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月3日(星期五) 晚上8:39
***@***.***&gt;;
抄送:&nbsp;"Zhu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnet/core] Couldn't find an installed template that matches the input, searching online for one that does... (Issue #8252)





 
Hello,
 
The command should be dotnet new console -o MyApp -f net7.0
 Can you double check if you're trying the correct command?

**Comment by liveans** [comment]
Thanks! Can you post your `dotnet --info` output?

**Comment by ZJL0027** [comment]
C:\Users\Lenovo&gt;dotnet


Usage: dotnet [options]
Usage: dotnet [path-to-application]


Options:
&nbsp; -h|--help&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Display help.
&nbsp; --info&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Display .NET Core information.
&nbsp; --list-sdks&nbsp; &nbsp; &nbsp; &nbsp;Display the installed SDKs.
&nbsp; --list-runtimes&nbsp; &nbsp;Display the installed runtimes.


path-to-application:
&nbsp; The path to an application .dll file to execute.


C:\Users\Lenovo&gt;dotnet new console -o MyApp -f net7.0
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Console App" (console) from author "Draco Language contributors" in pack Draco.ProjectTemplates
&nbsp; &nbsp; To use this template, run the following command and try again:
&nbsp; &nbsp; &nbsp; &nbsp; dotnet new -i Draco.ProjectTemplates::0.1.8-pre




C:\Users\Lenovo&gt;dotnet new console -o MyApp -f net7.0
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Console App" (console) from author "Draco Language contributors" in pack Draco.ProjectTemplates
&nbsp; &nbsp; To use this template, run the following command and try again:
&nbsp; &nbsp; &nbsp; &nbsp; dotnet new -i Draco.ProjectTemplates::0.1.8-pre





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnet/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月3日(星期五) 晚上8:57
***@***.***&gt;;
抄送:&nbsp;"Zhu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnet/core] Couldn't find an installed template that matches the input, searching online for one that does... (Issue #8252)





 
Thanks! Can you post your dotnet --info output?

**Comment by liveans** [comment]
Thanks, but looks like the output you sent doesn't contain `dotnet --info` output. Can you try to run `dotnet --info` command and send that output, please?
