### ISSUE TITLE
Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\7.0.3\hostfxr.dll], HRESULT: 0x800700C1 The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\7.0.3\hostfxr.dll failed,

### ISSUE THREAD

**Issue by moal223** [dotnet/core#8253]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by liveans** [comment]
Hello,

Can you paste your `dotnet --info` output here, and also can you tell us, what is the version of the operating system that you're using?
