### ISSUE TITLE
Blazor tutorial failure with default app on .NET Core 3.1 (or 6.0.14) and Visual Studio 2019

### ISSUE THREAD

**Issue by patwalt** [dotnet/core#8255]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have .NET Framework 4.7.2 installed, as well as .NET Core 3.1 installed, but when I ran the default code in the tutorial, I received the following message:
HTTP Error 500.31 - Failed to load ASP.NET Core runtime
Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.
Specific error detected by ANCM:
You must install or update .NET to run this application. App: C:\Software\learn\projects\blazor\BlazorApp\BlazorApp\bin\Debug\netcoreapp3.1\BlazorApp.dll Architecture: x64 Framework: 'Microsoft.AspNetCore.App', version '3.1.0' (x64) .NET location: C:\Program Files\dotnet\ The following frameworks were found: 6.0.14 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] Learn about framework resolution: https://aka.ms/dotnet/app-launch-failed To install missing framework, download: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64

I do have .NET Core 3.1 (admittedly, recently no longer supported) and I have .NET Framework 4.7.2 as well as Visual Studio 2019.  Since it mentioned 6.0.14, I tried altering the reference in my BlazorApp.csproj from netcoreapp3.1 to netcoreapp6.0.14, but that failed the build with the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.14.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.14.	BlazorApp	C:\Program Files\dotnet\sdk\5.0.416\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141

**Comment by liveans** [comment]
Hello,

It can be related with your [`global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file. 
Can you double check the SDK version in that file?

**Comment by mairaw** [comment]
The issue might be related to PATH, check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.
Maybe you have the x86 version installed and not x64?

If you could share with us what `dotnet --info` returns, that would be helpful as well.
