### ISSUE TITLE
Dotnet 7.0 Not Showing up after Install

### ISSUE THREAD

**Issue by NIEMDEV** [dotnet/core#8259]
dotnet new webapi -o MyMicroservice --no-https -f net7.0

After running the above command I get an error indicating:

Error: Invalid option(s):
-f net7.0
   'net7.0' is not a valid value for -f. The possible values are:
      net5.0          - Target net5.0
      net6.0          - Target net6.0
      netcoreapp2.1   - Target netcoreapp2.1
      netcoreapp3.0   - Target netcoreapp3.0
      netcoreapp3.1   - Target netcoreapp3.1

Like the SDK did not take.

**Comment by liveans** [comment]
Hello,

As a first step, can you try to [install .NET 7](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) (even if you've already done that), after that can you post your `dotnet --info` output here?

**Comment by mairaw** [comment]
Maybe it could be a PATH issue as well. Can you check all versions are all installed under the same folder?
https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions

And what `where.exe dotnet` returns?
