### ISSUE TITLE
.Net on Mac 

### ISSUE THREAD

**Issue by Toni0777** [dotnet/core#8261]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by liveans** [comment]
Hello,

There is not sufficient information to react on this, can you provide more information about the issue that you're having, please?
