### ISSUE TITLE
сyrillic in a container

### ISSUE THREAD

**Issue by codename00047** [dotnet/core#8271]
### Description
mcr.microsoft.com/dotnet/runtime:6.0 image doesn't support cyrillic symbols

### Other information

Hello,

I can't enter cyrillic characters in running container instead I get numbers and backslash like:
`root@c17514067e15:/# :\262\320\260\321\213\320\262\320\277\321\213\320\262\320\277`

How to solve it?

**Comment by liveans** [comment]
@MichaelSimons can you help with this question?

**Comment by MichaelSimons** [comment]
@codename00047 - You will need to configure the container for your desired language.  For example if you launch your container and specify the `LANG` environment variable `docker run -it --rm -e LANG=C.UTF-8 mcr.microsoft.com/dotnet/runtime:6.0`, will be able to use Cyrillic characters.  FYI, this behavior is not specific to .NET, it comes from the base OS image.  If you launch the base OS container e.g. `debian:bullseye-slim` you can try this out.

**Comment by krwq** [comment]
I'll close this issue as resolved. Please let us know if you have any further question
