### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ArdonitSaliji** [dotnet/core#8272]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet new console -o MyApp -f net7.0
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by liveans** [comment]
Hello,

Looks like your .NET SDK is missing, can you try to download it from https://dotnet.microsoft.com/en-us/download/dotnet/7.0 and install it?

**Comment by ArdonitSaliji** [comment]
That was missing yeah, installed it and all works fine now. Thanks.

**Comment by liveans** [comment]
> That was missing yeah, installed it and all works fine now. Thanks.

Great! I'm glad that it's working now!
