### ISSUE TITLE
A fatal error occurred. The folder [C:\Program Files\dotnet\host\fxr] does not exist

### ISSUE THREAD

**Issue by MyDadLeftMee** [dotnet/core#8273]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by MyDadLeftMee** [comment]
i keep getting this Error
A fatal error occurred. The folder [C:\Program Files\dotnet\host\fxr] does not exist

**Comment by liveans** [comment]
Hello,

It can be both path, wrong package issue. Can you try to uninstall .NET completely from your computer first, and try to download correct package (I assume it should be Windows x64 in your case) after that install it?

**Comment by mairaw** [comment]
What version of Windows are you on?

Also, to check if it's a path issue, run the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
