### ISSUE TITLE
the .NET MAUI projects don't appear in Visual Studio Community 2022 17.5.1 version. windows 10 

### ISSUE THREAD

**Issue by YiangosPanayides** [dotnet/core#8274]
### Description

the .NET MAUI projects don't appear in Visual Studio Community.
I try to uninstall and install again and again the Visual studio and the MAUI package but nothing changes.
Also when i download the extensions for .NET MAUI then they half projects appear on the create new project, but when i try to create a new project i receive an error ( System.Exception)

**Comment by YiangosPanayides** [comment]
I try to uninstall and install again and again the Visual studio and the MAUI package but nothing changes.
Also when i download the extensions for .NET MAUI then they half projects appear on the create new project, but when i try to create a new project i receive an error ( System.Exception)

**Comment by mairaw** [comment]
Sorry to hear that @YiangosPanayides. The best path would be to report this issue from inside Visual Studio. 

/cc @zerenaksu
