### ISSUE TITLE
No SDKs were found.

### ISSUE THREAD

**Issue by Mendoksai** [dotnet/core#8275]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

just got installed .net sdk but my system can't find any installed sdk

**Comment by liveans** [comment]
Hello,

It can be path issue; did you try to restart your command prompt?

**Comment by mairaw** [comment]
Also, to check if it's a path issue, run the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
