### ISSUE TITLE
 Error Help

### ISSUE THREAD

**Issue by ahmetakif24** [dotnet/core#8279]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/102760610/224833589-63310dff-7715-4b38-839a-d51a324847d2.png)

I got such an error when I was doing the create your application phase, I looked for a solution all day but I could not find the solution, I am using windows 11

**Comment by mairaw** [comment]
The error message is saying there is no SDK found. Have you downloaded and installed the SDK as instructed on the previous step? If so, we can look into other possible root causes.

**Comment by ahmetakif24** [comment]
I installed the SDK as requested but the error still persists


Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Maira ***@***.***>
Gönderilme: 14 Mart 2023 Salı 04:50
Kime: ***@***.***>
Bilgi: Ahmet akif ***@***.***>; ***@***.***>
Konu: Re: [dotnet/core] Error Help (Issue #8279)


The error message is saying there is no SDK found. Have you downloaded and installed the SDK as instructed on the previous step? If so, we can look into other possible root causes.

**Comment by mairaw** [comment]
Check if it's a path issue, run the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.
