### ISSUE TITLE
problem after installation

### ISSUE THREAD

**Issue by kaneez86** [dotnet/core#8280]
![Screenshot (67)](https://user-images.githubusercontent.com/89497928/224840325-892040be-5d8a-40d0-a62b-18ee3f6de487.png)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you install the SDK? And if so, did you open a new terminal window after the installation finished?

**Comment by kaneez86** [comment]
Hi Dotnet/Core,

This issue has been resolved as you guided me.

Many thanks,
Kaneez Zehra

**Comment by mairaw** [comment]
Great to hear.
