### ISSUE TITLE
.NET Installation issue on Mac

### ISSUE THREAD

**Issue by rtaub5** [dotnet/core#8281]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I tried downloading this .NET software. My installer window says it was installed successfully, but I can't find it anywhere on my computer. Also when I open a terminal in visual code and put in.        ~$ dotnet or dotnet --version, it says command not found. If I put in ~$dotnet it says permission denied. I closed the visual studio code and reopened it, and it still didn't work.

**Comment by mairaw** [comment]
What kind of Mac do you have and which version did you install? x64 or Arm64?

**Comment by rtaub5** [comment]
MacBook Air(m1, 2020). I installed x64. Now I just tried arm64, and I got a pop up message that says it's not able to be downloaded on this computer. Could it be that my computer's software needs to be updated? I am trying that now.

**Comment by mairaw** [comment]
For M1, please install the arm64 version then. We're trying to improve that experience on the site to make it less confusing.

Maybe try to uninstall x64 first and then install the arm64 version.

**Comment by rtaub5** [comment]
It worked. Thank you!

**Comment by mairaw** [comment]
That's great to hear. I'm going to close the issue then but please let us know if you run into any other issues.
