### ISSUE TITLE
'Console.WriteLine' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by dungeon123456789** [dotnet/core#8283]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by krwq** [comment]
Hey @dungeon123456789, you need to create `Program.cs` file with the content mentioned on that page rather than pasting that in the command prompt.

You can do it by i.e.:
`notepad Program.cs` and pasting the content there and pressing Ctrl+S (Save)
