### ISSUE TITLE
.NET March 2023 Update - .NET 7.0.4, .NET 6.0.15

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8285]
# .NET March 2023 Update

## Release Notes
* [7.0.4](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.4/7.0.4.md)
* [6.0.15](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.15/6.0.15.md)

## Status

Asset Type | 7.0.4 | 6.0.15 | Notes
-- | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) | ✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ | ✅ 
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) | ✅ | ✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ | ✅ |
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos) |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅ | ✅

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by mitch7222** [comment]
Hello,

Can you please keep the upgrade code for this package consistent between versions ie same upgrade code for 6.0.13, 6.0.14, 6.0.15? It makes it very difficult for a WIX installer to determine if the package is installed or not. If you cannot keep the upgrade code the same how does a WIX installer determine if the package is installed?

It seems like it should have the same upgrade code because the package will not allow older versions to be installed at the same time.

Cheers. Mitch

**Comment by reduckted** [comment]
I've discovered a regression with assembly loading. Not sure what the best place to log it was, so I've logged it in this repo: #8299

**Comment by krwq** [comment]
@reduckted we will transfer if needed, thanks for filing the issue!

**Comment by MagicAndre1981** [comment]
why does readme says you need [17.4 preview](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.4/7.0.4.md#visual-studio-compatibility)? It think it should be 17.4 LTSC.

**Comment by mairaw** [comment]
It was probably an oversight. Opened https://github.com/dotnet/core/pull/8311 to fix that

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/8383
