### ISSUE TITLE
Publish dotnet core SDK to Chocolatey

### ISSUE THREAD

**Issue by JeffJacobson** [dotnet/core#829]
Publish the .NET Core 2.0 SDK to Chocolatey repository.

Responding to [blog](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/) comment by @richlander 

> Chris McKenzie	
> 
> Would it be possible to publish the SDK installer to Chocolatey?
> 
>     23 mins ago
>     Reply
>     Rich Lander [MSFT]	
> 
>     We have been thinking about doing two things:
> 
>     – Publish the SDK to Chocolatey.
>     – Publish the SDK to Homebrew.
> 
>     Whomever wants those, please create an issue at the dotnet/core repo. Whichever one has the most feedback, we’ll do first.

**Comment by crmckenzie** [comment]
I'd love to see this as a standard part of the release pipeline. Yay!

**Comment by scullinan** [comment]
+1 for chocolatey

**Comment by ehouarn-perret** [comment]
+1 for chocolatey

**Comment by beforan** [comment]
+1 for chocolatey

**Comment by EdouardM** [comment]
+1 for chocolatey

**Comment by tomlazelle** [comment]
+1 for chocolatey

**Comment by chwebdude** [comment]
+1 for chocolatey

**Comment by navimondo** [comment]
+1 4 chocolatey

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #7779](https://github.com/dotnet/cli/issues/7779) via [**ZenHub**](https://www.zenhub.com/)
