### ISSUE TITLE
CS8802: Only one compilation unit can have top-level statements. 

### ISSUE THREAD

**Issue by cubescale** [dotnet/core#8301]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by krwq** [comment]
Hello @perolaquantum it looks like you have more than one .cs file in your folder and presumably csproj include them all (that's the default). That's what the error tells you. Let me know if you have any more questions.
