### ISSUE TITLE
Cannot resolve SDK 7.0.202

### ISSUE THREAD

**Issue by lunivore** [dotnet/core#8308]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create

Operating System: Windows 10 Pro

Ran tutorial command `dotnet new webapp -o MyWebApp --no-https -f net7.0`

Error message was:

```
D:\Dev\MyWebApp\MyWebApp.csproj : error : Could not resolve SDK "Microsoft.NET.Sdk.Web". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
D:\Dev\MyWebApp\MyWebApp.csproj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
D:\Dev\MyWebApp\MyWebApp.csproj : error :   The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
D:\Dev\MyWebApp\MyWebApp.csproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.Sdk.Web" because directory "C:\Program Files\dotnet\sdk\5.0.402\Sdks\Microsoft.NET.Sdk.Web\Sdk" did not exist.
D:\Dev\MyWebApp\MyWebApp.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
```

Running `dotnet --list-sdks` shows:

```
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
7.0.104 [C:\Program Files\dotnet\sdk]
7.0.202 [C:\Program Files\dotnet\sdk]
```

Suspect [this stackoverflow problem](https://stackoverflow.com/questions/75702346/why-does-the-presence-of-net-7-0-2-sdk-cause-the-sdk-resolver-microsoft-dotnet) is the same as mine.

**Comment by krwq** [comment]
Did you install Can you try re-installing dotnet from: https://dotnet.microsoft.com/en-us/download

also please share `dotnet --info` and share generated `csproj` file if still seeing issue.

**Comment by lud0vician** [comment]
I have tried using the uninstall tool to uninstall everything except the 7.0.202 used by Visual Studio, then reinstalled 7.0.202 from the dotnet site. Problem still persists. `dotnet --info` is:

```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  6.0.310 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by lud0vician** [comment]
MyWebApp.csproj file generated contains:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

**Comment by lunivore** [comment]
I also checked targeting net6.0 and it has the same problem.

**Comment by krwq** [comment]
IMO this looks like you have some kind of versioning problem. Something is forcing you to have `5.0.402` version installed. Do you have any global.json in your project? (`dotnet --info` says you don't but I'm not sure you've run it from your app directory or outside)

**Comment by rgeromegnace** [comment]
Same problem.

**Comment by mairaw** [comment]
@rgeromegnace please open a new issue and provide details such as `dotnet --info`.

**Comment by Chronial** [comment]
For anybody else running into this issue of:
> SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
> [...]
> MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.Sdk.Web" because directory "<some old SDK>" did not exist.

This is caused by the `MSBuildSDKsPath` Environment variable pointing to that old SDK folder. Removing that env var solves the issue.

**Comment by giaou** [comment]
> For anybody else running into this issue of:
> 
> > SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
> > [...]
> > MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.Sdk.Web" because directory "" did not exist.
> 
> This is caused by the `MSBuildSDKsPath` Environment variable pointing to that old SDK folder. Removing that env var solves the issue.

This works like a charm!! Thank you!

**Comment by manuel-esteves** [comment]
This Env var MSBuildSDKsPath is it on the agent or somewhere on the DevOps Pipeline ? 

![image](https://github.com/dotnet/core/assets/160226754/cdb4ca7e-f694-4008-85c8-8b05ef49e4f1)

**Comment by lunivore** [comment]
> This Env var MSBuildSDKsPath is it on the agent or somewhere on the DevOps Pipeline ?

@manuel-esteves I was having the problem on my own home PC (which coincidentally died so it's replaced anyway). So the env variable will be on your agent; if you can RDP into it just look for the "Environment Variable" settings.

If your agent is built from an infrastructure-as-code image (ansible / terraform), then that's your devops pipeline, so the answer is "it depends". But given it's a legacy installation issue it seems unlikely to be IAC.

**Comment by manuel-esteves** [comment]
Thanks I end up by detecting I was missing some required componentes on the agent, and that worked fine ;) it was able to detect the proper msbuild path without the env var.
