### ISSUE TITLE
WebSocket connection to 'wss://localhost:55395/' failed: 

### ISSUE THREAD

**Issue by CSagare** [dotnet/core#8309]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by krwq** [comment]
@CSagare where are you seeing the error? Which step are you on?
