### ISSUE TITLE
Dockerfile build issue on dotnet app "error NETSDK1073: Microsoft.WindowsDesktop.App' was not recognized"

### ISSUE THREAD

**Issue by devopsTamil** [dotnet/core#8310]
### **Error :**
/usr/share/dotnet/sdk/3.1.426/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized [/src/myapp/myapp.csproj]

![image](https://user-images.githubusercontent.com/113607316/226432444-9a59e065-2cdd-4da0-9be8-ae7f9a3bd17c.png)

### **Description :**
Hello Team/Community, Hope you all doing good !

- I'm trying to dockerize my dotnet application. While doing so I'm facing above issue.

- I'm using dotnet version 3.1.

Thanks !

**Comment by krwq** [comment]
Can you confirm you've installed dotnet in that container and it's available on PATH? (https://dotnet.microsoft.com/en-us/download) what does `dotnet --info` in the container return?
