### ISSUE TITLE
AOT publish error despite having desktop development for C++ workload & ARM64 build tools installed?

### ISSUE THREAD

**Issue by skausky** [dotnet/core#8312]
![image](https://user-images.githubusercontent.com/65585254/226668999-890d4f5c-df98-41dd-abbd-0d2344a42168.png)
I am getting the error "Make sure to install the Desktop Development for C++ workload. For ARM64 development also install C++ ARM64 build tools.". I have both Desktop Development for C++ and C++ ARM64 build tools installed. I only get this error on my laptop so I think it is a problem with my machine. Any suggestions on how to fix this? I am trying to publish a native console app with PublishAOT = true. I have uninstalled the build tools and desktop development for C++ and reinstalled. This did not help.

**Comment by skausky** [comment]
![image](https://user-images.githubusercontent.com/65585254/226670001-df804e69-afa3-49bf-b9a1-75adae784624.png)
![image](https://user-images.githubusercontent.com/65585254/226670213-7e706733-b4da-4279-987a-6ed4e85b0f98.png)

**Comment by skausky** [comment]
> can you try updating VS or perhaps uninstalling and reinstalling? (I think just unchecking main checkbox for C++ tooling and checking it back might work).
> 
> Also you might try to do the same using command line. That should hopefully at least give you more specific error message

I have already tried uninstalling/reinstalling C++ desktop dev tools twice. My visual studio is fully up to date.

**Comment by skausky** [comment]
Hello,

I have tried everything it seems to fix this. I have uninstalled visual studio 2019 and 2022. I reinstalled VS 2022 and then installed C++ desktop development and .NET dev packages. I installed Build tools and the C++ desktop development for that too (I am not sure why they are separate, but I am installed both). I then tried putting where.exe into my folder where my .net 7 app is and that gave me a new error: "cannot open input file advapi32.lib". I am lost. I am pretty sure there is something wrong with my PATH variables. Any suggestions?

**Comment by Kein** [comment]
Have you ever figured out what causes it?

**Comment by DamianSuess** [comment]
Same thing here. This is with a fresh install of 2026 Insiders. I have "Desktop development with C++" install and cannot publish our apps.

**Comment by vlitoms** [comment]
the error message is printed here: <img width="1193" height="121" alt="Image" src="https://github.com/user-attachments/assets/6b8ba566-c92b-4f5e-a8aa-ec8008fd9b93" /> 

findvcvarsall.bat called this way: 
<img width="1246" height="151" alt="Image" src="https://github.com/user-attachments/assets/c035e3fe-c9e4-459b-8405-0b3c41640e5f" />

Invocation of vswhere.exe returns empty list in this case:
<img width="559" height="333" alt="Image" src="https://github.com/user-attachments/assets/5c7a1715-5054-4f86-aee6-8e543f591c17" />

**HOTFIX:** I've changed it this way: 
<img width="559" height="317" alt="Image" src="https://github.com/user-attachments/assets/2b3f67db-2674-444b-a32a-3e88b48cb38d" />

And error message has disappeared and I've successfully published my application. Looks like Microsoft.Dotnet.ILCompiler 8.0.21 doesn't support new Visual Studio 2026.
Project is here: [TestAOT.zip](https://github.com/user-attachments/files/23229999/TestAOT.zip)

**Comment by DamianSuess** [comment]
@vlitoms  AHHHH!!  🤦‍♂️ 
When stepping through those files, I was so use to seeing v18 over the years and forgot, 2026 is v19!

Updated my `microsoft.dotnet.ilcompiler\9.0.10` package's **findvcvarsall.bat** to use `-version [16^,19^) ^`  and it worked like a charm.

Moreso, just remove the `-version ...` line altogether as per [dotnet/runtime PR: 115951](https://github.com/dotnet/runtime/pull/115951)

```bat
FOR /F "tokens=*" %%i IN (
    '"%vswherePath%" -latest -prerelease -products * ^
    -requires Microsoft.VisualStudio.Component.VC.Tools.%toolsSuffix% ^
    -version [16^,19^) ^
    -property installationPath'
) DO SET vsBase=%%i
```

Related to:
* https://github.com/dotnet/runtime/pull/115951
* https://github.com/dotnet/core/issues/8372
