### ISSUE TITLE
error while running the project

### ISSUE THREAD

**Issue by Sapna2005** [dotnet/core#8314]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error	NETSDK1004	Assets file 'C:\Users\DELL\source\repos\BlazorApp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	BlazorApp	C:\Program Files\dotnet\sdk\7.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266

**Comment by krwq** [comment]
can you provide `dotnet --info` output? Also can you remove bin and obj directory from your app and retry? I assume you've installed SDK (https://dotnet.microsoft.com/en-us/download)?

**Comment by Sapna2005** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\DELL\source\repos\BlazorApp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	BlazorApp	C:\Program Files\dotnet\sdk\7.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266	

where are obj and bin folders  in my app? I can't see them.

Yes i have installed SDK.

**Comment by krwq** [comment]
looking at the error message they should be here: `C:\Users\DELL\source\repos\BlazorApp\`

**Comment by Sapna2005** [comment]
no,bin and obj directrories are not created at this location.

**Comment by krwq** [comment]
can you try running `dotnet restore` in that location from command prompt?
