### ISSUE TITLE
zsh: command not found: dotnet

### ISSUE THREAD

**Issue by LaylaPHUNG** [dotnet/core#8315]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

zsh: command not found: dotnet
zsh: command not found: 2Cdotnetnet

**Comment by krwq** [comment]
You need to install dotnet first https://dotnet.microsoft.com/en-us/download and make sure it's on your PATH.

**Comment by mairaw** [comment]
Also if you're on a M1/M2 chip, make sure you installed the arm64 version.
