### ISSUE TITLE
will not build

### ISSUE THREAD

**Issue by daisy2two** [dotnet/core#8317]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

 Console.WriteLine("Hello, World!");
 Console.WriteLine("The current time is " + DateTime.Now);

**Comment by krwq** [comment]
Can you describe issue you're seeing? Are you sure you have installed https://dotnet.microsoft.com/en-us/download ?
