### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by corruptadept** [dotnet/core#8320]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\15052>dotnet new console =0 MyApp -f net7.0
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

**Comment by krwq** [comment]
note you used `=` in your command prompt rather than `-`.

Correct command:

```
dotnet new console =0 MyApp -f net7.0
```
