### ISSUE TITLE
TimeOnly is not supportedfor JsonSerializer.Serialize

### ISSUE THREAD

**Issue by RallyTuning** [dotnet/core#8321]
### Description

`TimeOnly` is not supported for `JsonSerializer.Serialize`. Would be great if you add this and other unsupported elements. Because Serialization/Deserialization is quite important in .Net Core and/or API calls.

### Configuration

* Which version of .NET is the code running on? **.Net Core 6**
* What OS and version, and for Linux, what distro? **Windows 10 22H2**
* What is the architecture (x64, x86, ARM, ARM64)? **x64**

**Comment by ufcpp** [comment]
https://github.com/dotnet/runtime/pull/69160
.NET 7

**Comment by RallyTuning** [comment]
> https://github.com/dotnet/runtime/pull/69160
> .NET 7

I think that it will not be added in .Net 6, right? Will be a mess to upgrade 1 exe + 12 dlls from .Net 6 to 7...

**Comment by svick** [comment]
@RallyTuning I believe only bugfixes are applied to released versions of .Net. You don't want to have two versions of .Net 6 that have different behavior.

Also, in general, upgrading between recent versions of .Net should not be "a mess".
