### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by annashox** [dotnet/core#8324]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have installed .NET 7.0 from https://dotnet.microsoft.com/download

When I use 'dotnet --info' I get this info: 

Host:
  Version:      7.0.4
  Architecture: x86
  Commit:       0a396acafe

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

I am unsure how this could be. Do I need to install the SDK to a certain location?

**Comment by krwq** [comment]
Hello you need to install .NET SDK from https://dotnet.microsoft.com/en-us/download . Currently you have installed .NET runtime instead of SDK.

**Comment by layomia** [comment]
Dup - https://github.com/dotnet/core/issues/8327.
