### ISSUE TITLE
no project under Solution in VS 2022 after creating new project

### ISSUE THREAD

**Issue by R0ynT** [dotnet/core#8329]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows 10

Should I wait for this loading to create the project? 

![image](https://user-images.githubusercontent.com/94928592/228008544-9ad90b65-a19e-419d-b194-f04ed9bb931a.png)

**Comment by layomia** [comment]
@R0ynT what happens if that loading indicator completes?

**Comment by R0ynT** [comment]
> @R0ynT what happens if that loading indicator completes?

it took forever. but this is fixed. thanks to this tutorial https://learn.microsoft.com/en-us/answers/questions/1163896/visual-studio-2022-doesnt-contain-project-doesnt-b
