### ISSUE TITLE
How do you dependency inject the ILoggerFactory in .net core 2.x

### ISSUE THREAD

**Issue by darewreck54** [dotnet/core#833]
Problem:

With asp.net core 1.x, you are able to dependency inject the ILoggerFactory into the controller via Startup::Configure:

```
public void Configure(IApplicationBuilder app,
    IHostingEnvironment env,
    ILoggerFactory loggerFactory)
```

However, with 2.x the ILoggerFactory is no longer passed as a param to Configure.  It's not clear to me how you would DI the ILoggerFactory into your classes without this param.

Thanks,
Derek

**Comment by benaadams** [comment]
Add it as a param to `Configure` and it will pick up that you need it and inject it (i.e. use the same signature for `Configure` you were using before)

**Comment by grokky1** [comment]
@darewreck54 @benaadams Would it not be better to inject it into the `Startup` constructor itself. Since logging is now setup in  `Program`, so I assume it's available via constructor injection.

I suppose you could even do `public Startup(ILogger<Startup>` logger) { ... }` if you need to perform logging during startup.

**Comment by karelz** [comment]
Looks like ASP.NET specific discussion. I would suggest to move it to https://github.com/aspnet repos.

**Comment by darewreck54** [comment]
Thanks, I'll try it out.  I think It's is actually asp.net core specific since it deals with the params passed into the configure method.  In asp.net core 1.1, it was passed in the params.  With asp.net core 2 it changed.  Didn't know you can add it back.

**Comment by Petermarcu** [comment]
How'd this go. As @karelz suggested, https://github.com/aspnet/home is the best place to track issues related to asp.net core.

**Comment by Petermarcu** [comment]
I'm going to close this for now. If it still ends up being an issue. Please open one up on https://github.com/aspnet/home. Thanks!
