### ISSUE TITLE
Can't use C# 11 new features 

### ISSUE THREAD

**Issue by okramarenko** [dotnet/core#8330]
I've installed .NET 7, but I can't use any of the C# 11 new features.
For instance, running this code will end up w an **_error CS0029: Cannot implicitly convert type 'string' to 'System.ReadOnlySpan<byte>' :_**

`ReadOnlySpan<byte> tmp = "tmp";`

I've checked LangVersion and TargetFramework values in Build.props, they're correct. I use 7.0.202 .NET version on Ubuntu.  

I've run out of ideas why this is happening, hope you can help. Thanks in advance!

**Comment by bartonjs** [comment]
Strings cannot be assigned to `ReadOnlySpan<byte>`.  UTF-8 literal strings can, though.  `System.String` instances (and literals) can be assigned to `ReadOnlySpan<char>`.

```C#
// ERROR
ReadOnlySpan<byte> tmp = "tmp";
```

```C#
// Either works
ReadOnlySpan<char> tmp = "tmp";
ReadOnlySpan<byte> tmp8 = "tmp"u8;
```
