### ISSUE TITLE
Unable to build a docker image

### ISSUE THREAD

**Issue by ManisCodeBase** [dotnet/core#8331]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

 => ERROR [build 4/6] RUN dotnet restore                                                                          16.2s
------
 > [build 4/6] RUN dotnet restore:
#11 0.963   Determining projects to restore...
#11 16.04 /src/MyMicroservice.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
#11 16.10   Failed to restore /src/MyMicroservice.csproj (in 14.85 sec).
------
executor failed running [/bin/sh -c dotnet restore]: exit code: 1

![image](https://user-images.githubusercontent.com/85423776/228167204-909c1f8f-b3fd-40a1-aaf0-cc55bd69976b.png)

**Comment by mairaw** [comment]
This seems like the same issue as https://github.com/dotnet/core/issues/8337#issuecomment-1488941949

See if the DNS solution works for you as well
