### ISSUE TITLE
Problem with .NET Tutorial - Your First Microservice

### ISSUE THREAD

**Issue by alsomalo** [dotnet/core#8335]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: windows 10

################

PS D:\Pomoyka\Practice0000> dotnet new webapi -o MyMicroservice --no-https -f net7.0
>>
Template 'ASP.NET Core Web API' created successfully.

Processing actions after creation...
Repair D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj:
   Determining projects to restore...
D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj : error NU1100: Failed to resolve 'Microsoft.AspNetCore
.OpenApi (>= 7.0.4)" for "net7.0".
D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj : error NU1100: Failed to resolve "Swashbuckle.AspNetCo
re (>= 6.4.0)" for "net7.0".
   Failed to restore D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj (for 97 ms).
Recovery failed.
Failed to publish action.
Manual instructions: Run "dotnet restore" command

#################

PS D:\Pomoyka\Practice0000\MyMicroservice> dotnet restore
   Determining projects to restore...
D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj : error NU1100: Failed to resolve "Microsoft.AspNetCore.OpenApi (>= 7.0.4)" to "net7.0".
D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj : error NU1100: Failed to resolve 'Swashbuckle.AspNetCore (>= 6.4.0)' for 'net7.0'.
   Failed to restore D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj (for 107 ms).

#################

PS D:\Pomoyka\Practice0000\MyMicroservice> dotnet add package Microsoft.AspNetCore.OpenApi --version 7.0.4
   Determining projects to restore...
   Writing C:\Users\heiss\AppData\Local\Temp\tmp3244.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding a PackageReference for package "Microsoft.AspNetCore.OpenApi" to project "D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj".
info : Restoring packages for D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj...
error: NU1100: Failed to resolve "Microsoft.AspNetCore.OpenApi (>= 7.0.4)" for "net7.0".
error: NU1100: Failed to resolve "Swashbuckle.AspNetCore (>= 6.4.0)" for "net7.0".
error: Package 'Microsoft.AspNetCore.OpenApi' is not compatible with 'all' platforms in project 'D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj'.

###############

PS D:\Pomoyka\Practice0000\MyMicroservice> dotnet run
Assembly:
D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj : error NU1100: Failed to resolve "Microsoft.AspNetCore.OpenApi (>= 7.0.4)" to "net7.0".
D:\Pomoyka\Practice0000\MyMicroservice\MyMicroservice.csproj : error NU1100: Failed to resolve 'Swashbuckle.AspNetCore (>= 6.4.0)' for 'net7.0'.

Build error. Fix build errors and try again.

##########

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What does the `dotnet nuget list source` command returns? If it's empty, it might be an issue with your NuGet sources.

You can try `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` to fix if it's empty.

**Comment by alsomalo** [comment]
Thank you very much, your advice helped, now everything works
