### ISSUE TITLE
Install but command not found 

### ISSUE THREAD

**Issue by swiss0exe** [dotnet/core#8338]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: linux

I used the link:
https://learn.microsoft.com/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website
did step by step the skript instalation but the order "dotnet" is not found.
I use the Raspberry Pi os lite .

I try to let a serial communication run on the Raspberry Pi 4.
I was able to start a Program but i have no results.

**Comment by mairaw** [comment]
@leecow would .NET be supported in that distro?

**Comment by swiss0exe** [comment]
Sorry my copy links was wrong i used :
https://learn.microsoft.com/de-de/dotnet/core/install/linux-scripted-manual#manual-install
"Per Skript gesteuerte Installation"

**Comment by swiss0exe** [comment]
On this page :https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Is a link for the page i was trying and at the end was a field : "I ran into an issue " with this llink i land here. So I thougt i am right here.
Thanks for the link i try to work with it.

**Comment by leecow** [comment]
There are a number of distros which can be used on Raspberry Pi which are supported for .NET. See https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md. See the distros which include ARM architectures.

**Comment by mairaw** [comment]
Answer was provided. Let us know if you still need more information.
