### ISSUE TITLE
i face an issue while create demo project in blazor

### ISSUE THREAD

**Issue by hameedjamal255** [dotnet/core#8339]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'FromResult' does not exist in the namespace 'Task' (are you missing an assembly reference?)	Task	C:\Users\hamee\source\repos\Task\Task\Data\WeatherForecastService.cs	17	Active

**Comment by mairaw** [comment]
Do you have a small repro of the code/project that is generating this error?

**Comment by hameedjamal255** [comment]
@mairaw thanks for reply i resolved it.

**Comment by mairaw** [comment]
Great to hear. Closing the issue then.
