### ISSUE TITLE
new webapi:  NU1101: Unable to find package Mic rosoft.AspNetCore.OpenApi

### ISSUE THREAD

**Issue by captix** [dotnet/core#8344]
Problem encountered on https://learn.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#create-a-service
Operating System: windows

got this from pasting in the line from the tutorial:

`dotnet new webapi -o MyMicroservice --no-https -f net7.0`

` : error NU1101: Unable to find package Mic
rosoft.AspNetCore.OpenApi. No packages exist with thi
s id in source(s): Microsoft Visual Studio Offline Pa
ckages
D:\DEV\dotNet\microservice\MyMicroservice\MyMicroserv
ice.csproj : error NU1101: Unable to find package Swa
shbuckle.AspNetCore. No packages exist with this id i
n source(s): Microsoft Visual Studio Offline Packages`

**Comment by mairaw** [comment]
Are you using Visual Studio to try the tutorial?

It seems you have Offline Packages set as the package source. Try switching to nuget.org and see if that fixes the problem?
![image](https://user-images.githubusercontent.com/12971179/229256318-b773923c-4b47-46be-8517-c2db898172a0.png)
