### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 26mmangan** [dotnet/core#8347]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/110934784/229611382-455cf9c6-f4f8-4f2a-9ebe-fb63224ead21.png)

**Comment by 26mmangan** [comment]
I installed it, and repaired it twice. Still doesnt work

**Comment by mairaw** [comment]
Hi @26mmangan! I'm sorry to hear you're running into problems.

This might be an issue with PATH.

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.

Let us know how that goes.

**Comment by 26mmangan** [comment]
Ive reinstalled it a few times, 
![image](https://user-images.githubusercontent.com/110934784/229638323-9c5080df-d261-409f-b122-053791a0fa96.png)
Doesn't look like it's working

**Comment by mairaw** [comment]
Oh, it seems they changed the behavior. Let me check with the team and get back to you.

**Comment by richlander** [comment]
Looks like you are in the user space. You want the system one. You appear to be looking at the first box. You want the second one.

![image](https://user-images.githubusercontent.com/2608468/229641089-4a470459-961b-4ae6-b4fb-832da2ce38f8.png)

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229641298-b6bae9cc-c5bc-4cc4-919d-7c0c1ef5dbeb.png)

**Comment by richlander** [comment]
Can you show your system path?

Also, show the results of this:

```bash
C:\Users\rich>where dotnet
C:\Program Files\dotnet\dotnet.exe
C:\Users\rich>dotnet --version
8.0.100-preview.1.23115.2
```

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229641778-687fc0ba-0a7a-4716-ab26-d58f39262bb5.png)

**Comment by mairaw** [comment]
Can you open the one I highlighted below?

![image](https://user-images.githubusercontent.com/12971179/229642852-17c0b15f-940c-4c37-8222-3cf2c94a6996.png)

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229643915-b82b2f5b-c54e-49bb-9aa8-8674ba989130.png)

**Comment by mairaw** [comment]
The x86 is listed first there. Can you confirm what kind of machine you have?

Type system type on your windows toolbar and open the System Information app.
If System Type is x64, then you need to move down the x86 entry to be the last one.

**Comment by 26mmangan** [comment]
I have a x64 machine. Will do.

**Comment by mairaw** [comment]
Let us know if after the change, you can type dotnet commands. Make sure to open a new window.

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229646392-15acc59b-0172-4cd4-b2d6-fa5a079e4247.png)
![image](https://user-images.githubusercontent.com/110934784/229646410-13037221-b775-48a0-9382-7bc9e5c6264e.png)

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229647757-95e9e9ba-5098-4a5c-a295-c06f6dc5f8f2.png)
Yes, I used a new window

**Comment by mairaw** [comment]
Usually that step by step works 😢 @richlander any other suggestions?

**Comment by richlander** [comment]
Make sure to close the command prompt after changing the values in the environment variables.

**Comment by 26mmangan** [comment]
I did, I restarted it twice

**Comment by 26mmangan** [comment]
Done, alright thanks

**Comment by richlander** [comment]
And type `where dotnet` again to see where that is coming from.

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229652046-121c716f-03d2-4012-963c-f7d56748186e.png)

**Comment by richlander** [comment]
That is very odd. Something is clearly injecting the x86 path. Which .NET versions do you have installed?

Like this:

![image](https://user-images.githubusercontent.com/2608468/229652398-213c2609-384c-4a47-8014-6474928f9f8a.png)

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229654000-08fd0643-130e-49b5-b047-b7bc37284edd.png)

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229654333-04eceb5f-c06c-4353-bfcf-e1f52c7cf803.png)
![image](https://user-images.githubusercontent.com/110934784/229654377-fcaa1bc9-e6a1-4d30-92c1-e3b49b1bdc2c.png)

**Comment by richlander** [comment]
That looks correct.

Can you show the output of `set` from your command prompt? It's really only the `PATH` variable I'm interested in.

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229655214-b2b73ec4-7535-4708-94d8-659d013f4d53.png)

**Comment by richlander** [comment]
That looks right.

Please show me `where dotnet` now and `dotnet --info`

**Comment by richlander** [comment]
This is the problem. You have an old 5.0 install on your machine that you need to remove.

Perhaps this was installed by Visual Studio. If you have that, can you go into the Visual Studio Installer and remove it from the installed components?

**Comment by 26mmangan** [comment]
How do I do this?

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/229663655-a04c45f1-a593-4263-8c06-7156047cc4f3.png)
This is my extensions list for VS Code if you need it.

**Comment by mairaw** [comment]
This is VS Code. Do you have Visual Studio also installed?

**Comment by NikolaMilosavljevic** [comment]
@26mmangan it appears that you have `x86` versions of .NET 5.0 `WindowsDesktop` runtime, which also carries `NETCore` runtime.

The easiest way to remove would be from Control Panel or Settings app, but if they don't show there, here's the alternative.

1. Download the following installer: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.10-windows-x86-installer

2. Run the installation. You should get a dialog that says `Modify Setup`, with multiple options, one being `Uninstall` - proceed with that. In some rare cases, it's possible that you would see a regular dialog for first-time installation - you would proceed to install the product. After that, you'd run the installer again and choose `Uninstall`.

After .NET 5 is uninstalled, open a new command prompt and try the commands that were failing, or producing unexpected results, previously, i.e. `dotnet --version` and `dotnet --info`.

**Comment by 26mmangan** [comment]
Successfully uninstalled, and reinstalled. 
![image](https://user-images.githubusercontent.com/110934784/229966595-42d22a50-912f-4fce-a7dd-8f4dcbe9ccfe.png)

**Comment by richlander** [comment]
You re-installed .NET 5? Is there a reason for that? Also, you seem to have 5.0.10. Is there a reason you are using that version? If you need .NET 5, can you install 5.0.17? https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by 26mmangan** [comment]
No, I re installed .NET 6.0.407
![image](https://user-images.githubusercontent.com/110934784/229972135-300a478e-e04e-4ce4-9e14-0f39529d1536.png)
![image](https://user-images.githubusercontent.com/110934784/229972192-d6151044-3101-42a2-adb7-249620b0179a.png)

**Comment by richlander** [comment]
You still have 5.0 installed. Did you try running the 5.0 installer and choosing uninstall?

**Comment by 26mmangan** [comment]
Done. 
![image](https://user-images.githubusercontent.com/110934784/230275908-68dc14a9-5c94-4f36-8070-af166bfe6599.png)
![image](https://user-images.githubusercontent.com/110934784/230276676-0789277d-dc1e-4abe-a9ed-0e8a36dac263.png)
![image](https://user-images.githubusercontent.com/110934784/230276777-0cd5cab3-8cfa-4bf3-95e3-1746341a9057.png)

**Comment by NikolaMilosavljevic** [comment]
@26mmangan can you share the outputs of `dotnet --info` and `set PATH` commands?

**Comment by 26mmangan** [comment]
![image](https://user-images.githubusercontent.com/110934784/230282057-d2ee97af-d12c-460b-9d69-996dcb6734c5.png)
![image](https://user-images.githubusercontent.com/110934784/230282086-23bee81c-ce5a-4172-bf36-5593d74c20d5.png)

**Comment by NikolaMilosavljevic** [comment]
Thanks - it is odd. I understand that you installed and uninstalled 5.0.408 SDK, but have you tried to install (or repair) x86 version of 5.0.10 WindowsDesktop installer, and then run the same installer to `uninstall` it? I've shared the steps 2 days ago: https://github.com/dotnet/core/issues/8347#issuecomment-1496277810

It would be good to go through those steps and see if there is any improvement in `dotnet --info` and `dotnet --version` results.

I presume you are starting a new command window after each of these install/uninstall operations, as that is necessary to get the updated values of environment variables, like PATH.

**Comment by NikolaMilosavljevic** [comment]
That's great news! If `dotnet --info` also works, you have a working .NET SDK!

**Comment by richlander** [comment]
This looks resolved. Sorry that this was so hard.
