### ISSUE TITLE
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

### ISSUE THREAD

**Issue by JyostnaSada** [dotnet/core#8348]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Subbaiahs-Air:MyWebApp subbaiah$ dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/local/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(580,5): error NETSDK1177: Failed to sign apphost with error code 0: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun [/Users/subbaiah/MyWebApp/MyWebApp.csproj]
/usr/local/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(580,5): error NETSDK1177: /Users/subbaiah/MyWebApp/obj/Debug/net7.0/apphost: the codesign_allocate helper tool cannot be found or used [/Users/subbaiah/MyWebApp/MyWebApp.csproj]
/usr/local/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(580,5): error NETSDK1177:  [/Users/subbaiah/MyWebApp/MyWebApp.csproj]
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

**Comment by mairaw** [comment]
I'm sorry we never responded to this issue before.
We no longer have this tutorial on the site. Give it a try to the new one:
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro

Let us know if you still have issues with it.
