### ISSUE TITLE
UseWebListener Fails with .Net Core 2.0

### ISSUE THREAD

**Issue by Dave3of5** [dotnet/core#835]
Note sure if this is a problem with .Net Core 2.0 or my setup but if I do the following:

dotnet new react
npm install
dotnet add package Microsoft.AspNetCore.Server.WebListener
dotnet add package Microsoft.Net.Http.Server

change Program.cs to:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Net.Http.Server;

namespace test
{
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
			    .UseWebListener()
                .UseStartup<Startup>()
                .Build();
    }
}

```

dotnet run

I get the following error:

> 
> Unhandled Exception: System.TypeLoadException: Method 'StartAsync' in type 'Microsoft.AspNetCore.Server.WebListener.MessagePump' from assembly 'Microsoft.AspNetCore.Server.WebListener, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderWebListenerExtensions.<>c.<UseWebListener>b__0_0(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at test.Program.BuildWebHost(String[] args) in C:\Users\davidk\Desktop\test\Program.cs:line 22
>    at test.Program.Main(String[] args) in C:\Users\davidk\Desktop\test\Program.cs:line 18

This is following the documentation here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth

Any help would be appreciated.

**Comment by dlaporte40** [comment]
Hi,
WebListener has been replace by HttpSys for ASP.NET Core 2.0
See : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys
Regards

**Comment by Dave3of5** [comment]
@dlaporte40 I seemed to miss that in the documentation lol thanks !
