### ISSUE TITLE
Chore: Polish MD files (in the background) via VS Code

### ISSUE THREAD

**Issue by Jay-o-Way** [dotnet/core#8352]
### Description

Hey all, I just wanted to go through the MD files and let VS Code format them with its built-in rules. This is going to be huge in numbers, but the changes should be **mostly** invisible. I'll have to create a number of branches* in order to be able to split this in different PRs.

- Also found a couple of typos.
- In some cases bits like `<T>` are present (for example `ChannelReader<T>` or `ReadOnlySpan<char>`) and that would be interpreted as (invalid) HTML which means it won't show on the MD page.

### Branches:

- [x] Misc
- [x] Release notes 1
- [x] Release notes 2
- [x] Release notes 3
- [x] Release notes 5
- [x] Release notes 6
- [x] Release notes 7
- [x] Release notes 8

**Comment by mairaw** [comment]
Thank you @Jay-o-Way. Assigned the issue to you. Thanks for improving the content here.

**Comment by Jay-o-Way** [comment]
That first one was easy. Are you guys ready for bigger pr's? 😛

**Comment by mairaw** [comment]
How large are we talking about?

**Comment by Jay-o-Way** [comment]
Not so bad actually, ranging between 6 (for version 8) to 148 (for version 2). Two causes:

- I only focussed on md files in the release-notes folders for the **major** versions
- but I also did a large search `<br>` replace `</br>`...

**Comment by mairaw** [comment]
Ok, I'll take a look and let you know.

**Comment by mairaw** [comment]
I'd probably keep it at 50 files max.

**Comment by Jay-o-Way** [comment]
Offf-topic: I see a number of _contributor.md_ files that contain lists with personal e-mail adresses. Doesn't that count as a privacy leak?
