### ISSUE TITLE
Couldn't find a project to run. Ensure a project exists in C:\Users\ksextro, or pass the path to the project using --project.

### ISSUE THREAD

**Issue by kelltro** [dotnet/core#8369]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you do `cd myApp` as instructed on the `Create your app` step? From the error message, it doesn't seem that command was ran.
