### ISSUE TITLE
Iniciando o projeto de C#

### ISSUE THREAD

**Issue by Jcordeiro22** [dotnet/core#8373]
Sinto dificuldades em resolver o problema que o .NET não reconhece os comandos que faço a ele , no caso, o "hello, world!".

Ajudem a um iniciante nessa área.

**Comment by GUSTAVPEREIRA** [comment]
Poderia descrever exatamente o que está tentando fazer?

**Comment by Jcordeiro22** [comment]
Boa noite, consegui resolver o problema.

Foi apenas uma falha na minha atenção durante a aprendizagem.

Grato pelo retorno

Em dom., 9 de abr. de 2023 às 19:25, Gustavo Pereira <
***@***.***> escreveu:

**Comment by SilverioMiranda** [comment]
Abrir um issue no github em vez de perguntar no stackoverflow é foda em

**Comment by mairaw** [comment]
Não tem problema, mas geralmente mais informações sobre qual é o problema ajuda o nosso time a tentar ajudar. Que bom que conseguiu resolver o problema @Jcordeiro22. Vou fechar o issue então.
