### ISSUE TITLE
does not contain any version-numbered child folders

### ISSUE THREAD

**Issue by freggit** [dotnet/core#8377]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Fedora 37 (Workstation Edition) 
Installed the .NET SDK or the .NET Runtime with a script.
While following steps from [Dotnet Microsoft site](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install), when I get to the section to run `dotnet new blazorserver -o BlazorApp --no-https -f net7.0` I get a error message in terminal that states:
`A fatal error occurred, the folder [/usr/lib64/dotnet/host/fxr] does not contain any version-numbered child folders`

**Comment by mairaw** [comment]
Can you `dotnet--info` and share the results with us or do you get the same error?

Do you have any other versions installed?

**Comment by freggit** [comment]
`$ dotnet--info
bash: dotnet--info: command not found...`

> Can you `dotnet--info` and share the results with us or do you get the same error?
> 
> Do you have any other versions installed?

`$ dotnet--info
bash: dotnet--info: command not found...`

This is what I get.  I've never installed dotnet before. First time using the script info from the website.

**Comment by mairaw** [comment]
@leecow can you help here? @omajid I've seen you help folks with similar issues before. Any suggestions here?

**Comment by leecow** [comment]
.NET is available natively through the Fedora package archives. If I'm following you explanation, .NET probably isn't installed so I would start with `dnf install dotnet-sdk-7.0`.

If needed, there are various troubleshooting scenarios documented [here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-redhat).

**Comment by freggit** [comment]
> `dnf install dotnet-sdk-7.0`.

This seemed to resolve my issue.  Thank You.
