### ISSUE TITLE
.NET April 2023 Update - .NET 7.0.5, .NET 6.0.16

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8383]
# .NET April 2023 Update

## Release Notes
* [7.0.5](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.5/7.0.5.md)
* [6.0.16](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.16/6.0.16.md)

## Status

Asset Type | 7.0.5 | 6.0.16 | Notes
-- | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) | ✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ | ✅ 
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) | ✅ | ✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ | ✅ |
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos) |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)|  ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora)|✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)|✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)   |✅ | ✅
## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

### Known Issues

- [x] We are currently investigating .NET installation issue with Ubuntu 23.04 on packages.microsoft.com. We will update once the issue is resolved.

**Comment by asos-chrisgreen** [comment]
We have up-streamed some of the metapackages via a private nuget artefacts feed and are failing to download these. Is MS aware of any issues at this time on downloading .NET 6.0.16 packages via the upstreaming feature of Azure Artefacts?

**Comment by amis92** [comment]
The CDN cache seems to have stalled a bit - https://dotnetcli.azureedge.net/dotnet/Sdk/7.0/latest.version returns `7.0.201` with `last-modified: Sat, 25 Feb 2023 03:28:09 GMT`. The same happened with 8.0 channel. Any chance to purge the cache?

**Comment by rbhanda** [comment]
> The CDN cache seems to have stalled a bit - https://dotnetcli.azureedge.net/dotnet/Sdk/7.0/latest.version returns `7.0.201` with `last-modified: Sat, 25 Feb 2023 03:28:09 GMT`. The same happened with 8.0 channel. Any chance to purge the cache?
> 
> There was previously a similar problem: [#7800 (comment)](https://github.com/dotnet/core/issues/7800#issuecomment-1249451244)

I have cleared the CDN cache

**Comment by TonyValenti** [comment]
Is there going to be a May update?

**Comment by rbhanda** [comment]
> Is there going to be a May update?

We will not be publishing .NET 7.0.6 or .NET 6.0.17 May updates

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/8539
