### ISSUE TITLE
dotnet product roadmap not successfully linked

### ISSUE THREAD

**Issue by barruka** [dotnet/core#8388]
At `https://github.com/dotnet/core/blob/main/roadmap.md` the second text line after the title: "If you're looking for the product roadmap, visit https://aka.ms/dotnet-product-roadmap."

`https://aka.ms/dotnet-product-roadmap` is not not working

**Comment by mairaw** [comment]
It opens this for me
![image](https://user-images.githubusercontent.com/12971179/231523465-0d647da9-72b1-44cd-aa8d-c95d4a01096d.png)

You don't see that?

@terrajobst @jamshedd I just updated that link. Can you make sure that's the appropriate one for .NET 8 roadmap?

**Comment by barruka** [comment]
Yes, it is working, sorry about that.

**Comment by mairaw** [comment]
No need to apologize. Your issue made me realize the link was outdated.
