### ISSUE TITLE
Nothing comes out in the solution explorer, it is completely empty.

### ISSUE THREAD

**Issue by Ivancuarius** [dotnet/core#8389]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Nothing comes out in the solution explorer, it is completely empty.

**Comment by mairaw** [comment]
Can you share a screenshot of your Solution Explorer window?
