### ISSUE TITLE
.NET Core 2.1 Roadmap Update

### ISSUE THREAD

**Issue by steji113** [dotnet/core#839]
# Roadmap Update
I know .NET Core 2.0 was just released, but it might be helpful for contributors to have an idea of what the roadmap for .NET Core 2.1 is looking like. Is this something that can be updated [here](https://github.com/dotnet/core/blob/master/roadmap.md)?

Thanks!

**Comment by richlander** [comment]
I am working on it. I wanted to have this done for release day, but couldn't quite manage it. Definitely agree. Will post here when it is done. It will be more minimal at first and then grow.

**Comment by steji113** [comment]
No worries, just wanted to check in and see what was cookin' so to speak.

**Comment by jcapellman** [comment]
I was just looking as well, excited to see what is in store.

**Comment by ghd258** [comment]
Enterprise Library ，Unity and AntiXss support net core?

**Comment by alexzaytsev-newsroomly** [comment]
Any updates on this?

**Comment by genifycom** [comment]
Without a 2.0 LTS version, we are currently dead in the water wrt AWS Lambda. This is a huge bottleneck now.

**Comment by richlander** [comment]
We are working on both things still:

- .NET Core 2.1 roadmap.
- .NET Core 2.0 LTS.

Both are coming.

**Comment by joehoeller** [comment]
It would be really nice if they would implement lazy loading for 2.1

**Comment by lburkovsky** [comment]
Hi,
visual studio silently installed the .NET Core SDK 2.1.1.7118. There is no official statement about it.
More transparency would not hurt.

Regards,
Ladislav

**Comment by genifycom** [comment]
So what does this mean? Since DotNet 2.0 is not yet LTS, will 2.1 become LTS?

We need to know quickly since project development does not turn on a dime!

**Comment by Petermarcu** [comment]
The plan is that a version of 2.0.X will become LTS. We are taking feedback on 2.0 and making fixes based on that feedback from real world usage. It will then be stamped with LTS at a certain patch level. So if you are on the 2.0 train, you are in the right place to be LTS. 2.1 is not planned to be an LTS release.

**Comment by mockjv** [comment]
@Petermarcu I know sometimes these things can be nebulous, but do you have a loose estimate as to when you expect 2.0 to be stamped LTS?  Even if it's a **very** loose estimate like between Q1 or Q2 of 2018?

**Comment by Petermarcu** [comment]
My hope is that it will be in Q1 of 2018. There are active discussions about it.

**Comment by lburkovsky** [comment]
In the meantime I have on my system 4 .NET Core 2.1 SDK inclusive the newest 2.1.2. I haven't been asked or informed about the installation. I want to remove at least some of them. Which are safe to remove?

Do you find it serious after 4 monts after releasing 2.0 and in the time of 2.1.2 to state we haven't started to plan 2.1? Is this the way to strengthen the confidence of the community?

**Comment by Petermarcu** [comment]
This is where things have gotten a little confusing with versioning. .NET Core 2.1 is not out yet. The roadmap and dates should be published soon for when it will be released. The .NET Core SDK has shipped a 2.1.2 but that is just the SDK version. It still builds apps for a 2.0 runtime and not a 2.1 runtime.

**Comment by Petermarcu** [comment]
To answer your other question, you should be able to remove older SDK's because only the latest is used. Uninstalling runtimes however requires you knowing what the applications one your machine depend on.

**Comment by alexzaytsev-newsroomly** [comment]
@Petermarcu it's just that the page with the roadmap says ```The .NET Core 2.1 project has not yet started```.

**Comment by Petermarcu** [comment]
Yeah, @richlander can we get an update on that page! :)

**Comment by steji113** [comment]
@richlander / @Petermarcu just to clarify, when I originally inquired about the roadmap for 2.1 way back in August, I was looking more specifically for what features and concerns are being worked on and perhaps something like API surface area that is being brought in. While release date forecasts are very handy as a consumer of .NET Core, I was asking more from the perspective of a community contributor. It is obvious things like Span<T> and overall performance improvements based on Span have been taking place, but it is not entirely clear what the priorities have been that are driving Microsoft teams and where the community could potentially help fill in the gaps.

**Comment by Petermarcu** [comment]
Hi All, I think @richlander is close to having something to post for .NET Core 2.1 all up. 

I know from a .NET Core Runtime perspective, the major focus for 2.1 has been performance. There are new API's like Span and Memory, many API's are also now leveraging those under the hood as well. We also have improvements in many other areas underway. We've significantly improved Networking performance and done a few different optimizations in the IO stack. Beyond that, we've be addressing feedback on features that shipped in 2.0 and doing general bug fixing.

As far as the community helping. I'd love to see how we can make that easier. At least in the corefx and coreclr repos, we've been marking things as up-for-grabs. We're also putting things in the 2.1 milestone that we would like to see get done in 2.1. Any help on work in that milestone from the community would be awesome to get. If there is a particular area or item of interest, I'd be happy to help identify good things to pick up and try to get someone from Microsoft to be on point to make sure support is available and questions can get answered.

**Comment by joehoeller** [comment]
I'd just like to see lazy loading added, and better/easier handling of many to manys on PUT and POST.

**Comment by lburkovsky** [comment]
It looks like we get a preview instead of roadmap update :D

**Comment by iSazonov** [comment]
It seems they still don't know how to live with MSFT internal non-public roadmap and public community roadmap.

**Comment by joehoeller** [comment]
PERFORMANCE??? Its fast enough add some features like auth, microservice support/auto discovery, lazy loading, a decent & seamless way to handle many to many on PUT and POST!

**Comment by joehoeller** [comment]
We are planning to dicth .NET Core and go w/ Python - same performance and a ton of features

**Comment by alexzaytsev-newsroomly** [comment]
@joehoeller I am not a .net core dev, but just wanted to clarify:
`auth` - that is already there, what is missing?
`microservice support/auto discovery` like what, a built-in prescriptive way of discovery? why would that be part of the development framework? That is a service (product) that lets you locate a map in your environments where bits are. how is that a .net core responsibility? (also, personally i run microservices without any discovery because why is it even needed? treat each microservice as you would an external 3rd party API)
`lazy loading` - wrong repository for that comment, also that is on EF Core roadmap.
`a decent & seamless way to handle many to many on PUT and POST` can you illustrate what you mean? everything kind of works for me...

**Comment by genifycom** [comment]
@joehoeller Your comment did not contribute to the DotNet core roadmap discussion. We are not comparing development environments. Of course you can compare features with other lambda offerings.

**Comment by Petermarcu** [comment]
I'm going to close this now, the roadmap was shared a month or two ago. https://blogs.msdn.microsoft.com/dotnet/2018/02/02/net-core-2-1-roadmap/
