### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by PANDATD** [dotnet/core#8391]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

<pre>dotnet new console -o MyApp -f net7.0

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.203

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to &apos;1&apos; or &apos;true&apos; using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run &apos;dotnet dev-certs https --trust&apos; (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what&apos;s new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use &apos;dotnet --help&apos; to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Segmentation fault (core dumped)
</pre>

**Comment by leecow** [comment]
@PANDATD - can you give some details on how .NET was installed? Also, please run `dotnet --info` and include the output.

**Comment by mairaw** [comment]
Did you install it using snap? That's usually when I see the segmentation fault error happen.

**Comment by PANDATD** [comment]
> Did you install it using snap? That's usually when I see the segmentation fault error happen.

Yes I installed it using the snap

**Comment by mairaw** [comment]
I'd recommend trying a different installation method to see if you get different results.

**Comment by PANDATD** [comment]
Okey I will try thank you so much @mairaw
