### ISSUE TITLE
Problème

### ISSUE THREAD

**Issue by jeftaxi** [dotnet/core#8396]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything els
![2023-04-14_20-20-21](https://user-images.githubusercontent.com/120931830/232125882-3348ea79-c87f-4ede-9e3a-cdc748683843.jpg)
![2023-04-14_20-20-21](https://user-images.githubusercontent.com/120931830/232125987-39f61f9e-4621-4be2-81c9-f603632b4d82.jpg)
e that is relevant.

**Comment by Chri-s** [comment]
You cannot enter the content of Program.cs in the console.
The shown content in the tutorial is already in the created Program.cs file.
After entering "cd MyApp" click continue in the tutorial and proceed with the next step.
When you are at the step "Edit your code", you need to open the file C:\Users\jefta\MyApp\Program.cs in a text editor and edit it in the editor.

**Comment by jeftaxi** [comment]
Merci beaucoup.
