### ISSUE TITLE
Cannot Install Dotnet Console

### ISSUE THREAD

**Issue by R1ggers** [dotnet/core#8398]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows 10 [Version 10.0.19045.2846]

I received a 'dotnet' is not recognized as an internal or external command error when running in a new Cmd prompt
.NET (SDK 7.0.203 (x86)) was installed successfully and PC restarted.

**Comment by mairaw** [comment]
I'm sorry we never responded. Is this is still an issue for you?
