### ISSUE TITLE
dotnet is not added to environment by the install script

### ISSUE THREAD

**Issue by stringdom** [dotnet/core#8399]
After running the install script linked by the tutorial in Linux Mint 20.3, the script claims dotnet is already installed but the command dotnet can't be found still, despite restarting the terminal. Suspect that the script doesn't config correctly some environment variable. Had to fix manually to make it work.

Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
I'm sorry you had to do some extra steps to make it work on Linux and that we didn't reply to your issue sooner. 

Since this is quite old, I'm closing this for now. But if this is still an issue, we can try to add some information to the docs. Let us know.
