### ISSUE TITLE
Publish .NET Core SDK to Homebrew

### ISSUE THREAD

**Issue by kamcma** [dotnet/core#840]
Publish the .NET Core 2.0 SDK to Homebrew repository.

Responding to [blog](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/) comment by @richlander

> Chris McKenzie
> 
> Would it be possible to publish the SDK installer to Chocolatey?
> 
>> 23 mins ago
>> Reply
>> Rich Lander [MSFT]	
>>
>> We have been thinking about doing two things:
>> 
>> – Publish the SDK to Chocolatey.
>> – Publish the SDK to Homebrew.
>> 
>> Whomever wants those, please create an issue at the dotnet/core repo. Whichever one has the most feedback, we’ll do first.

**Comment by gortok** [comment]
I don't have a full understanding of what's involved; but as I understand Homebrew, couldn't anyone create a homebrew installer for .NET Core?

**Comment by cglong** [comment]
+1 for Homebrew; also FYI there's a very active discussion already at dotnet/cli#533.

I'm far from an expert on Homebrew, but I have made [a number of contributions](https://github.com/Homebrew/homebrew-core/pulls?utf8=%E2%9C%93&q=author%3Acglong) and would be glad to help write one for .NET Core 😄

I work at Microsoft, so feel free to ping me here or offline if there's anything I can do to help! 🙂

**Comment by Petermarcu** [comment]
I"m going to close this in favor of the conversation continuing in the cli repo which is the correct place. https://github.com/dotnet/cli/issues/533
