### ISSUE TITLE
Unable to access deployed Microservice at end of tutorial

### ISSUE THREAD

**Issue by brandonvmoore** [dotnet/core#8400]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

At the end of the tutorial I attempted to navigate to "http://20.253.239.165/WeatherForecast" where 20.253.239.165 is the EXTERNAL-IP shown in the command prompt, but I get an error saying 20.253.239.165 took too long to respond.

I logged into my Azure Web Portal  and verified that it is running there. I'm not sure why I wouldn't be able to access it though. Given that I don't see any instructions about whitelisting my IP nor do I see any ability (at first glance) to do so with the given resources I'm guessing that shouldn't be necessary. Not sure how to proceed with troubleshooting at this point.

**Comment by mairaw** [comment]
I'm sorry we didn't assist you on time back then. Please let us know if this is still an issue for you.
