### ISSUE TITLE
Dotnet

### ISSUE THREAD

**Issue by Hamid2534** [dotnet/core#8406]
Hello,

I am trying to install dotnet on macOS but it is not working.
I am getting " command not found" in the terminal ouch I tray to look for it .

Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by MihaZupan** [comment]
Did you open a new terminal window after installing .NET?
Existing windows will not observe changes to the PATH variable that the installer modifies.
