### ISSUE TITLE
My first microservice

### ISSUE THREAD

**Issue by Pynappelsap** [dotnet/core#8409]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Operating System: windows

error 404 when running localhost
![Screenshot 2023-04-21 093508](https://user-images.githubusercontent.com/109960478/233572850-055929ef-2b8f-4482-aac6-124766dabc4f.png)

**Comment by MihaZupan** [comment]
Do you see the expected result if you make a request to `http://localhost:5020/WeatherForecast` instead?
