### ISSUE TITLE
hello, I can't create a c# program. Help me to understand

### ISSUE THREAD

**Issue by Olgynchik** [dotnet/core#8412]
S C:\Users\Ольга\Desktop\C#\new> dotnet new console         
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
PS C:\Users\Ольга\Desktop\C#\new>

**Comment by mairaw** [comment]
Did you install the SDK and started a new command window?
