### ISSUE TITLE
Cannot build project on external drive VS2022 Mac 17.5.4

### ISSUE THREAD

**Issue by chinwgb** [dotnet/core#8413]
### Other information

I alway got CS8785 error if I build any project in external drive on Mac and this not happen on Windows

**Comment by mairaw** [comment]
@chinwgb can you follow the instruction to report a problem through VS for Mac? That way, we can ensure the feedback goes to the right team.
https://learn.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022
