### ISSUE TITLE
dotnet will not work on my command propmt 

### ISSUE THREAD

**Issue by Flawous01** [dotnet/core#8414]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Flawous01** [comment]
C:\WINDOWS\system32 dotnet is not recognized as an internal or external command, operable program or batch file.

**Comment by mairaw** [comment]
Did you install the SDK? If so, did you close the command prompt window and started a new one?
