### ISSUE TITLE
.NETチュートリアル　エラーについて

### ISSUE THREAD

**Issue by sennohuyu** [dotnet/core#8419]
.NETチュートリアル「コード」を編集するのところで
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);
と出力するとターミナルで
C:\Users\pop20\.vscode\extensions\ms-dotnettools.csharp-1.25.4-win32-x64>dotnet run                                                                     実行するプロジェクトが見つかりませんでした。プロジェクトが C:\Users\pop20\.vscode\extensions\ms-dotnettools.csharp-1.25.4-win32-x64 に存在することを確認するか、--project を使用してパスをプロジェクトに渡してください。のようなエラーが出て進みません。
Problem encountered on https://dotnet.microsoft.com/ja-jp/learn/dotnet/hello-world-tutorial/edit
Operating System: windows　が表示されます。

**Comment by mairaw** [comment]
Apologies for not replying sooner. We changed the tutorial since then to use VS Code. See if you think it's easier.

In the previous version, you had to type a command to enter in the right directory before you were able to run the code.
