### ISSUE TITLE
probleme installation

### ISSUE THREAD

**Issue by dmaina09** [dotnet/core#8427]
C:\Users\user>dotnet new console -o MyApp -f net7.0
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by MihaZupan** [comment]
Can you please share the output of running `dotnet --info`?
