### ISSUE TITLE
MacOS Couldn't Locate Dotnet?

### ISSUE THREAD

**Issue by minghowC** [dotnet/core#8428]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I installed dotnet 7.0 on macOS Monterey, 12.6.2, but I ran into "command not found: dotnet" after installation. I made sure to open a new window.
![Screenshot 2023-05-02 at 17 38 22](https://user-images.githubusercontent.com/127394358/235632594-77bdb965-d0be-4fbf-91da-fb878b35dfbb.png)

**Comment by mairaw** [comment]
which version did you install? Please install the arm64 version if you're on M1 chip.

**Comment by minghowC** [comment]
The one I install was indeed arm64

**Comment by minghowC** [comment]
<img width="749" alt="Screenshot 2023-05-03 at 15 06 14" src="https://user-images.githubusercontent.com/127394358/235851489-aa34ce93-cec9-4641-889c-b57e86d519fb.png">
But to no avail

**Comment by mairaw** [comment]
Maybe take a look at https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos#check-for-install-folders

Did you open a new terminal after installing it?
