### ISSUE TITLE
System.Net.Mail SmtpClient  Nonsupport Implicit SSL

### ISSUE THREAD

**Issue by Monns** [dotnet/core#843]
System.Net.Mail不能使用EnableSsl指定465端口发送邮件的bug，.NET Framework中就有这个问题，到了core，这个问题依然存在。。希望能解决。

[EDIT] [Bing translation to English](https://www.bing.com/translator/?ref=TThis&IG=8F25B4387C9D4ECF9E1C04E8E7105279&IID=SERP.5407&&text=System.Net.Mail%E4%B8%8D%E8%83%BD%E4%BD%BF%E7%94%A8EnableSsl%E6%8C%87%E5%AE%9A465%E7%AB%AF%E5%8F%A3%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6%E7%9A%84bug%EF%BC%8C.NET%20Framework%E4%B8%AD%E5%B0%B1%E6%9C%89%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%8C%E5%88%B0%E4%BA%86core%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E4%BE%9D%E7%84%B6%E5%AD%98%E5%9C%A8%E3%80%82%E3%80%82%E5%B8%8C%E6%9C%9B%E8%83%BD%E8%A7%A3%E5%86%B3%E3%80%82&from=&to=en) by @karelz:
System. Net. Mail cannot send mail using the EnableSsl 465 port bug,. NET Framework has this problem, the core, the problem still exists ... Hope for a solution.

**Comment by karelz** [comment]
@Priya91 can you please comment?

**Comment by Monns** [comment]
@karelz  Thanks for translating. 
This legacy has been a long time. Here is a detailed description of the problem.

[https://blogs.msdn.microsoft.com/webdav_101/2008/06/02/system-net-mail-with-ssl-to-authenticate-against-port-465/](https://blogs.msdn.microsoft.com/webdav_101/2008/06/02/system-net-mail-with-ssl-to-authenticate-against-port-465/)

[https://support.microsoft.com/en-us/help/950260/you-cannot-use-system-net-mail-smtpclient-to-send-an-e-mail-message-wi](https://support.microsoft.com/en-us/help/950260/you-cannot-use-system-net-mail-smtpclient-to-send-an-e-mail-message-wi)

**Comment by karelz** [comment]
BTW: Forgot to post it last time: We do not plan to evolve System.Net.Mail. We recommend users to use other modern libraries, e.g. MailKit: https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md
