### ISSUE TITLE
[/usr/share/dotnet/host/fxr] path not found

### ISSUE THREAD

**Issue by george-mollz** [dotnet/core#8432]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by george-mollz** [comment]
please help me with an idea on the issue

**Comment by omajid** [comment]
What distribution are you using? https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup might have the steps to fix your issue.

**Comment by mairaw** [comment]
Also, how did you install?
