### ISSUE TITLE
.Net Core :HttpClient fails with : The server returned an invalid or unrecognized response on every request

### ISSUE THREAD

**Issue by savkris** [dotnet/core#844]
**HttpClient fails with: The server returned an invalid or unrecognized response** 

> StackTrace:
> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

# General
By requesting an API endpoint that, the first call succeeded but never again. The page loads on any browser otherwise.  
Using Fiddler to inspect to try and find out what is going on: I am getting this response back with 200 Status code and data loaded as XML:

> HTTP/1.1 200 OK
> Accept-Ranges: bytes
> Age: 4
> Cache-Control: no-cache
> Content-Type: application/xml; charset=utf-16
> Date: Wed, 16 Aug 2017 07:50:04 GMT
> Expires: -1
> Pragma: no-cache
> X-Trace-Id: 246493.030-507962550
> Content-Length: 858120
> Connection: keep-alive
> X-Iinfo: 5-4932445-4935132 NNNN CT(0 -1 0) RT(1502869770814 33059) q(0 0 0 -1) r(0 0) U5
> X-CDN: Incapsula

I am running on:
> .NET Command Line Tools (2.1.0-preview1-006958)
> 
> Product Information:
>  Version:            2.1.0-preview1-006958
>  Commit SHA-1 hash:  51567d7641
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-006958\
> 
> Microsoft .NET Core Shared Framework Host
> Version  : 2.0.0

Here is the simple code :
 ```
try
            {

               var response = await CronwBetClient.GetAsync("https://api.beteasy.com.au/RacingFeed/api/feed");
}
 catch (HttpRequestException e)
            {
                Console.WriteLine(e);
                throw;
            }

```

**Comment by karelz** [comment]
You are using preview1 bits. Do you get the same error on RTM bits (released on 8/14)?
If you can, please post code which has chance to compile - `CronwBetClient` above is not part of Framework. Thanks!

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24486](https://github.com/dotnet/corefx/issues/24486) via [**ZenHub**](https://www.zenhub.com/)
