### ISSUE TITLE
Error while running the command docker build

### ISSUE THREAD

**Issue by ganeshiyer-git** [dotnet/core#8442]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by Saibamen** [comment]
Have you installed Docker and are you sure that Docker Desktop is running?

Please also show us your Docker version: `docker --version`
