### ISSUE TITLE
Problem while checking version of dotnet in terminal

### ISSUE THREAD

**Issue by satyasharma12345** [dotnet/core#8443]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
what error do you get? and what version did you install? and which kind of Mac do you have?
