### ISSUE TITLE
Tutorial Handling Error

### ISSUE THREAD

**Issue by ejett5** [dotnet/core#8448]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify
Operating System: windows

When following the step the modify the Counter to adjust the increments to increase by an amount of 10 I received the unhandled exception error once I hot reloaded to the local host. See below for the screenshot of the error ( on the left, and the code on the right)
[Blazor Tutorial Error.docx](https://github.com/dotnet/core/files/11447606/Blazor.Tutorial.Error.docx)

I verified that there were no spelling or syntax errors by reviewing and even copying the modified code without any fix. Following that I checked the whitespace as I put a space between variables and operators and again there was no change in the output and the error persisted.

**Comment by mairaw** [comment]
What does your Counter.razor file look like? Have you added the new property as shown in the tutorial?

**Comment by ejett5** [comment]
Below is a screenshot of Counter.razor file. I did attempt to add the property in the tutorial in the index.razor file as that is the step I was at after adding that to the main page. 

![image](https://github.com/dotnet/core/assets/115510725/f9ea2b9d-3e3d-40c1-85bd-9c5ca7db0454)
