### ISSUE TITLE
Problem in Tutorial - Unable to understand error

### ISSUE THREAD

**Issue by mharleman5** [dotnet/core#8451]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When returning to the Unity editor and selecting the Cube under the Hierarchy window the Inspector window in place of where I am supposed to find the script states, "The associated script can not be loaded.  Please fix any compile errors and assign a valid script."  I do not know how to see the compiler errors.  I have followed the instructions exactly including all indentations and punctuation.  I do not know what the problem is or how to track it down.  No debugging information is provided.  Visual Studio 2022 states, "No issues found."

**Comment by mairaw** [comment]
If you try to compile the script in Visual Studio, do you get any errors? When you have your script open, go to the main menu and click **Build** > **Build Solution**.

You can also share your script here and we can try to help you.

**Comment by mharleman5** [comment]
I must've done something wrong because I installed all the development tools on my laptop and everything worked smooth as glass.  I will work on the desktop version and figure out what I've done.  Thanks though.

Michael Harleman 

    On Thursday, May 25, 2023 at 05:41:12 PM EDT, Maira Wenzel ***@***.***> wrote:  
 
 


If you try to compile the script in Visual Studio, do you get any errors? When you have your script open, go to the main menu and click Build > Build Solution.

You can also share your script here and we can try to help you.

**Comment by mharleman5** [comment]
No, I replied to you fellas.  I said I must've made a mistake because the second time I tried the code it worked fine.  It was my fault.  You can drop the issue.  Mark it as solved.  
Michael Harleman 

    On Friday, June 2, 2023 at 09:41:26 PM EDT, github-actions[bot] ***@***.***> wrote:  
 
 


This issue is stale because there has been no response to a request for more information for 7 days.

**Comment by mairaw** [comment]
Good to hear. Thanks for getting back to us. We fixed our automation to remove the needs-more-info label when you reply as well.
