### ISSUE TITLE
.NET acts weirdly on wrapped native libraries.

### ISSUE THREAD

**Issue by aymen157** [dotnet/core#8453]
using any SDL wrapper on a .NET app (eg. console application + SDL-cs) causes the flag "SDL_WINDOW_ALLOW_HIGHDPI" to not work. Manually P/invoking SetProcessDpiAwareness Enables high dpi. So i suppose this has to do with the way .NET boilerplate code is interacting with the OS ?

if dotnet has unexpected behaviors like this one, it might have other unexpected behaviors. I couldn't find any documentation online of limitations or something so I filed this.

(Tested on windows 10 x64 .Net 6) (This is not a SDL bug. other wrappers work perfectly such as Rust wrapper, native C++/C works properly)
Example is attached.

Cheers.
[highdpi_bug repository](https://github.com/aymen157/high_dpi_bug_sdl_dotnet/tree/main/highdpi_bug)

**Comment by eiriktsarpalis** [comment]
I would recommend filing an issue with the authors of the specific wrapper libraries you have been having trouble, we wouldn't be able to help you much in this forum.
