### ISSUE TITLE
.Net Core 1.1.2 LTS

### ISSUE THREAD

**Issue by rohitshrivastava04** [dotnet/core#846]
# Understanding Support for LTS

I am a little bit confused to understand the end of support date for .Net Core 1.0.5. A few days back 1.1.2 was Current before the release of 2.0. Now, this has become LTS, I believe this will change the end of support date for 1.0.5 which was LTS before. 

Does this release mean end of support for 1.0.5 will be 12 months from November 16, 2016 which is what is mentioned in the https://www.microsoft.com/net/core/support or from 14th Aug 2016.

I feel it's bit unfair to consider Nov 16, 2016, as the release date for 1.1.2 LTS as this is probably 14-Aug 2017. 

Could you please clear my doubts regarding the end of support date for .Net Core 1.0.5.

**Comment by omajid** [comment]
@leecow The updated table at https://www.microsoft.com/net/core/support is causing confusion. It is pretty obvious to me that 1.0.x and 1.1.x will EOL on the same date but the table doesnt clarify that.

**Comment by leecow** [comment]
@rohit21agrawal - sorry for the confusion and I'll try to come up with a way to represent this on the support site. Basically we're going to maintain both as LTS until a 2.0 LTS is declared which will then start the 1 year end of life countdown for both.

One thing to clarify. The lifecycle dates begin with the first release in the band and it is not reset by subsequent patch releases.

**Comment by omajid** [comment]
> Basically we're going to maintain both as LTS until a 2.0 LTS is declared which will then start the 1 year end of life countdown for both

Uhh.... So 2.0.0 isn't the start of an LTS train? The 2.0 series will be declared LTS with some future patch update? We shouldn't start the countdown for 1.x EOL?

**Comment by leecow** [comment]
Correct, 2.0 has not been declared LTS yet. See the [2.0 release notes](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0.md#support) and the Support Lifecycle section of the [2.0 blog announcement](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/).

**Comment by leecow** [comment]
@omajid and @rohitshrivastava04 - could you have a look at the note I added after the table on https://www.microsoft.com/net/core/support and let me know it helps clarify?

**Comment by omajid** [comment]
Thanks Lee. That addresses my immediate concern.
