### ISSUE TITLE
create a code for a web form in ASP.NET using the MVC framework that can connect all of its data fields to the corresponding data fields of the database’s data tables.

### ISSUE THREAD

**Issue by Pradoelaine** [dotnet/core#8467]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Sorry, but this is beyond the scope of the hello world tutorial listed there. Have you tried finding other materials online?
