### ISSUE TITLE
MacOS arm 7.0

### ISSUE THREAD

**Issue by abdallah1936** [dotnet/core#8474]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I have installed the .NET package twice now but I keep getting that my system doesn't have it. I have a macOS with an M1 chip, I installed the 7.0 arm version.

**Comment by mairaw** [comment]
I'm sorry we never replied to your inquiry before. Are you still having issues?

If so, let us know what `dotnet --info` returns.

**Comment by abdallah1936** [comment]
Hello, 

I fixed the issue, Thank you.
