### ISSUE TITLE
the asp.net core web app dont lunch  

### ISSUE THREAD

**Issue by Ebrahem123456** [dotnet/core#8480]
❌ System.BadImageFormatException: Could not load file or assembly 'C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App\7.0.5\Microsoft.Extensions.Hosting.Abstractions.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App\7.0.5\Microsoft.Extensions.Hosting.Abstractions.dll'
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.DisposeAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.DisposeAsync()
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshFilter.DisposeAsync()
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.DisposeAsync()
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.HandleWatch(CommandLineOptions options)
dotnet watch ❌ An unexpected error occurred

**Comment by Ebrahem123456** [comment]
in visual studio 2022 there a error code : 
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Program Files (x86)\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Unable to load Microsoft.NET.Sdk.Razor.SourceGenerators	WebApplication4	C:\Users\Ebrah\source\repos\WebApplication4\CSC	1	Active

**Comment by Ebrahem123456** [comment]
and when i do a dubug the page show's : 
This localhost page could not be found. No web page found for web address: http://localhost:5217/
HTTP ERROR 404

**Comment by Ebrahem123456** [comment]
i have a final project after 10 in asp.net days and tomorow the teacher want to see the half of the projet withe 20% of final grade.

**Comment by Ebrahem123456** [comment]
We have to do according to what we have learned. no nodjs You need asp.net core with one of the databases: SQL Server, SQL Server File (MDF), Access File
It is possible to combine with react in the fronthand, which is actually working with javascript in a different way .
i want to do about Employee management site.
    List of employees in a table, list of employee attendance by date and time.
    Each employee can see his profile on the website on a separate page.
    By clicking on an employee in the table, we reach his profile page.
    An employee can log in and enter attendance.
    An administrator can log in and add/update/delete employees and attendance.
    Every user who is registered in the system, his picture will be displayed on the website. 
if some one can help me in the project or similar project

**Comment by mairaw** [comment]
What version of .NET is your project referencing? How did you create your project?

/cc @pranavkm

**Comment by Ebrahem123456** [comment]
I tried .net 6 and .net7 none of them worked and I made the project in the visual studio 2022 application. Inside the application, it gives the following error code:


  Severity Code Description Project File Line Suppression State
Warning CS8034 Unable to load Analyzer assembly C:\Program Files (x86)\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Unable to load Microsoft.NET.Sdk.Razor.SourceGenerators WebApplication5 C:\Users\Ebrah\source\repos\WebApplication5\CSC 1 Active

**Comment by mairaw** [comment]
Do you get the same error if you create a brand new project and just run it?

**Comment by steveharter** [comment]
> could not load file or assembly 'C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App\7.0.5\Microsoft.Extensions.Hosting.Abstractions.dll'. Format of the executable (.exe) or library (.dll) is invalid.

Note that this is using `x86` version of .NET. Are you sure you want to use that? You may need the `x64` version and may need to uninstall the `x86` version.
