### ISSUE TITLE
Error trying to build Docker image

### ISSUE THREAD

**Issue by luisboris** [dotnet/core#8484]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

While trying to build the docker image (with `docker build -t mymicroservice .`), it gave the following error;

![image](https://github.com/dotnet/core/assets/67930812/34f24607-d68d-4a20-bf46-043ee25473fc)

**Comment by steveharter** [comment]
PTAL @MichaelSimons
