### ISSUE TITLE
"It was not possible to find any installed .NET Core SDKs" and i dont know what to do

### ISSUE THREAD

**Issue by Tjoeser** [dotnet/core#8487]
I got this error.

"  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
"

Even though the installation was succesfull.

**Comment by mairaw** [comment]
Can you share the results of `dotnet --info`? Thanks.
