### ISSUE TITLE
Erro: Não foi possível localizar um projeto para executar. Verifique se existe um projeto em C:\Users\xxx ou passe o caminho para o projeto usando --project.

### ISSUE THREAD

**Issue by giulia-donato** [dotnet/core#8488]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/run
Operating System: windows

A mensagem de erro é: "Não foi possível localizar um projeto para executar. Verifique se existe um projeto em C:\Users\Meu User ou passe o caminho para o projeto usando --project."

Como passo para --project? A instalação foi bem sucedida.

**Comment by matheusarb** [comment]
Oi, @giulia-donato 
Tive o mesmo problema que você em um outro contexto e resolvi com o seguinte comando:
```csharp
dotnet run --project <Caminho_Até_O_CS.PROJ_Desde_A_Raiz>
```
Para exemplificar, o caminho que passei na íntegra do meu comando:
```csharp
dotnet run --project .\Automations\Automations.csproj
```

Suponho que a sua IDE, por alguma razão, não está identificando o arquivo _.csproj_ para rodar a aplicação. Ainda assim, é possível "forçar" essa identificação e, consequentemente, rodar a aplicação com o uso da flag _--project_
