### ISSUE TITLE
BlazorApp new project wrong

### ISSUE THREAD

**Issue by MilesShuang** [dotnet/core#8492]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://github.com/dotnet/core/assets/73567856/681a489e-79e1-4d3f-820a-849b74d33c7a)

**Comment by mairaw** [comment]
For some reason, it seems you don't have the .NET 7 SDK installed. You can try to edit the csproj file to target .NET 6 or install the missing SDK from https://dotnet.microsoft.com/download/visual-studio-sdks.

Any other suggestions @danroth27?

**Comment by danroth27** [comment]
That is surprising! I don't know how you could create a Blazor app in Visual Studio that targets .NET 7 without the .NET 7 SDK being installed.

@MilesShuang Can you share with us the output of running `dotnet --info` from a command console? Have you ever installed or used .NET previously? Do you maybe have a global.json file somewhere that is pinning the SDK version to a lower version?
