### ISSUE TITLE
Unable to find & set .Net6 as Target Framework with VisualStudio2022 

### ISSUE THREAD

**Issue by lingxiao-microsoft** [dotnet/core#8493]
Hello Team,

I'm trying to setup the workspace for .Net6 development environment. 

I've installed the VS2022 with newest release (also tested with older version like 17.5.4) and specifically installed the .Net6 SDK. See below results from cmd & folder

![image](https://github.com/dotnet/core/assets/127797451/03d02068-2666-446b-b459-826239977a9d)
![image](https://github.com/dotnet/core/assets/127797451/c53c54df-05f8-48be-b08e-265f576e5202)

Then I used the VS2022 to create a completely new project with ConsoleApp type. 

During the creation steps, I was able to see the .Net6 option and select it 

![image](https://github.com/dotnet/core/assets/127797451/31d9a344-aec7-4bdd-87ce-703dcc56777d)

But after the project is created and try to build the solution, it gave me below errors. 

![image](https://github.com/dotnet/core/assets/127797451/e8056948-50bd-4cb0-bec2-cf1d210b00db)

And from the solution properties, I was not able to see the .Net6 sdk from the dropdown list 

![image](https://github.com/dotnet/core/assets/127797451/609769df-4e84-4be7-bd7b-9ed4c3a85705)

I've downloaded the .Net6 SDK from [here](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks) for x64. (Also tried with x86 and did not work as well)

Please kindly let us know how could we resolve the issue as it is blocking us, would really appreciate it!

Thanks again!

**Comment by steveharter** [comment]
Is there a `global.json` file in the directory of your project or any parent directory? That overrides the SDK lookup.

**Comment by lingxiao-microsoft** [comment]
hi @steveharter , there is no global.json.

**Comment by lingxiao-microsoft** [comment]
However, I previously were using VS2019, I did not uninstall VS2019 before I install the VS2022. This is due to I still need some dev work using VS2019. Not sure if this will impact anything.

**Comment by mairaw** [comment]
What does your csproj look like?
It's interesting that the dropdown is only showing .NET Framework versions. I see this on VS for a console project
![image](https://github.com/dotnet/core/assets/12971179/026ec2cf-1109-4535-a2f9-ee07b767d94f)

You should be able to run VS versions side-by-side, so having VS 2019 and VS 2022 shouldn't be a problem.

Can you also check what `where.exe dotnet` returns?

**Comment by lingxiao-microsoft** [comment]
Hi @mairaw , it's a vanilla console app project.

Below is the csproj file

![image](https://github.com/dotnet/core/assets/127797451/353e2e56-e0e7-492d-992c-e128141ce4a9)

And this is the result from the cmd you mentioned 

![image](https://github.com/dotnet/core/assets/127797451/8d3ccc2d-d012-46f3-9671-9a0cf0d161f6)

**Comment by lingxiao-microsoft** [comment]
The second file location is where I've currently installed my .Net6 SDK. 

The 1st one is a previous login to Windows which is no longer in used. currently I'm using `lingxiaoli.REDMOND`

**Comment by mairaw** [comment]
I'd try to change the path so the second entry comes first. This might be messing VS.

Some instructions on how to do that can be found at https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by lingxiao-microsoft** [comment]
Hi @mairaw , thanks for your reply. This resovled some of my issues, at least for now I'm able to see the .Net6 option in my VS22. 

However, there are still some errors complaining in our code repo build

![image](https://github.com/dotnet/core/assets/127797451/309c8dbd-80d9-4ec1-94ef-367ef5aa12c0)

Then I added a global json to point to my .Net6 version but still hitting one error

![image](https://github.com/dotnet/core/assets/127797451/297b4a2a-2b06-41c0-97cc-effe2b7d6163)

**Comment by lingxiao-microsoft** [comment]
Hi @mairaw , it looks like when building the solution, it is still trying to look for the SDK under this path. 

`C:\Program Files\dotnet\sdk\Microsoft.NET.Sdk.Worker\Sdk`

However, from my dotnet folder, the layout look like below format

`C:\Program Files\dotnet\sdk\<dotnet-version>\Microsoft.NET.Sdk.Worker\Sdk`

**Comment by lingxiao-microsoft** [comment]
I've uninstalled all SDKs, runtime related to .Net6 and reinstalled VS22 completely. The issue seems resolved for me now, thank you for help on this!
