### ISSUE TITLE
dotnet command is not working in both git and by using the command prompt

### ISSUE THREAD

**Issue by Tolikonda33** [dotnet/core#8496]
'dotnet' is not recognized as an internal or [external]([url](![Screenshot (3752)](https://github.com/dotnet/core/assets/134788416/4f616e79-c4bd-417b-bc7e-5bbe8556fde5))) command error and unable to execute the dotnet command

**Comment by steveharter** [comment]
The install should have update the `PATH` environment variable to include `C:\Program Files\dotnet` which has the `dotnet.exe` executable.

Can you verify that directory exists?

**Comment by mairaw** [comment]
did you open a new command prompt window after you installed .NET @Tolikonda33? Can you run `where.exe dotnet` and report the results back to us?

**Comment by Tolikonda33** [comment]
Hi both, I have executed the path as mentioned above and it’s working well now. Thanks a lot.
