### ISSUE TITLE
Running on Ubuntu UK problem

### ISSUE THREAD

**Issue by wocdamjack** [dotnet/core#8500]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: linux

Step 1/10 : FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
Get "https://mcr.microsoft.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by wocdamjack** [comment]
I called my project NoHttpsMU. when I create the docker I'm using :

sudo docker build -t nohttpsmu

Is that ok ?

**Comment by mairaw** [comment]
@richlander @leecow do you know who's responsible for mcr?

**Comment by leecow** [comment]
The feedback link on mcr.microsoft.com goes to https://github.com/microsoft/containerregistry. Should be a good place to start with availability issues.

**Comment by rmjoia** [comment]
There's an issue opened there too
https://github.com/microsoft/containerregistry/issues/139

**Comment by mairaw** [comment]
So I'll close this as duplicate.
