### ISSUE TITLE
Erro após o comando dotnet watch

### ISSUE THREAD

**Issue by ivanmeirelesdeabreu** [dotnet/core#8502]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet watch e recebo um erro: Application failed to start: An erro occurred trying to start process 'D<diretório>\bin\Debug\net7.0\<app>.exe' (sendo que não existe o arquivo app.exe ) with working directory

**Comment by mairaw** [comment]
Oi @ivanmeirelesdeabreu,
Can you show the full error you're getting when running `dotnet watch`? Do you get the same error if you try to run with `dotnet run`? Did you make any modification to the project beyond what's in the tutorial?

Pinging @danroth27 for some ideas here too.
