### ISSUE TITLE
Privacy Error

### ISSUE THREAD

**Issue by nswift101** [dotnet/core#8509]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
When I run the code it says "your connection is not private". I am running windows 10 and using chrome.

**Comment by steveharter** [comment]
I assume that is because `https:` \ `SSL` is not being used.

**Comment by mairaw** [comment]
Did you leave the Configure for HTTPS option checked? Was the certificate created?
