### ISSUE TITLE
HashAlgorithm.Create(string) throwing PlatformNotSupportedException on Windows 10 (.NET Core 2.0)

### ISSUE THREAD

**Issue by DaveSlinn** [dotnet/core#851]
According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.create?view=netcore-2.0#System_Security_Cryptography_HashAlgorithm_Create_System_String_), this operation should be supported in .NET core 2.0 but when I do a simple console app to test, I get the following:

![image](https://user-images.githubusercontent.com/18301427/29375338-dc693750-8271-11e7-9cd0-830a2e63ab12.png)

Here is my .csproj showing I am using 2.0:

![image](https://user-images.githubusercontent.com/18301427/29375360-f16f9cf2-8271-11e7-97ce-74ff58dbf44b.png)

**Comment by bartonjs** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/22626.

You need to either use `(HashAlgorithm)CryptoConfig.CreateFromName(algName)` or (preferred) just use what you want, e.g. `MD5.Create()`.

**Comment by DaveSlinn** [comment]
Then the docs need to be updated to reflect this.  It is confusing when the docs indicate something should work when in fact, it doesn't.

**Comment by bartonjs** [comment]
@mairaw Do we have a plan for incorporating the PlatformNotSupported details in Core into the docs?  And all of the other soft-deprecations that we're going to add to an analyzer pack?

**Comment by mairaw** [comment]
Yes, we need to add the PlatformNotSupported details. It has been in my mental backlog for a while. I've opened an issue to track this: https://github.com/dotnet/docs/issues/2934

Can you provide more info on the soft deprecations @bartonjs? We can include warnings or remarks about those. But I'll need more details.

**Comment by bartonjs** [comment]
https://github.com/dotnet/corefx/wiki/ApiCompat is one place that we have a lot of the data.  In addition to being in the PNSE section up top it's in the deprecated section at the bottom: https://github.com/dotnet/corefx/wiki/ApiCompat#systemsecuritycryptographyhashalgorithmcreatestring
