### ISSUE TITLE
Could not resolve SDK "Microso ft.NET.Sdk.Web

### ISSUE THREAD

**Issue by enigmaiiiiiiii** [dotnet/core#8512]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.

Processing post-creation actions...
Restoring D:\developments\tutorials\MyWebApp\MyWebApp.csproj:
D:\developments\tutorials\MyWebApp\MyWebApp.csproj : error : Could not resolve SDK "Microso
ft.NET.Sdk.Web". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
D:\developments\tutorials\MyWebApp\MyWebApp.csproj : error :   SDK resolver "Microsoft.DotN
et.MSBuildWorkloadSdkResolver" returned null.
D:\developments\tutorials\MyWebApp\MyWebApp.csproj : error :   The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
D:\developments\tutorials\MyWebApp\MyWebApp.csproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.Sdk.Web" because directory "C:\Program Files\dotnet\sdk\5.0.202\Microsoft.NET.Sdk.Web\Sdk" did not exist.
D:\developments\tutorials\MyWebApp\MyWebApp.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
Restore failed.
Post action failed.
Manual instructions: Run 'dotnet restore'

**Comment by mairaw** [comment]
Did you install the .NET 7 SDK? Can you share the output of `dotnet --info`?
