### ISSUE TITLE
dotnet run 

### ISSUE THREAD

**Issue by DFranc-D** [dotnet/core#8514]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\franc\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\franc\M
yApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by DFranc-D** [comment]
My apologies for not responding on time...  your answered made sense after
confirming what the issue was. THANK YOU SO MUCH.

**Comment by mairaw** [comment]
You're welcome. It seems your issue is solved, so I'm closing this.
