### ISSUE TITLE
Error while running kubectl apply -f deploy.yaml

### ISSUE THREAD

**Issue by ckyiamah** [dotnet/core#8516]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I received the following error while running kubectl apply -f deploy.yaml

MyMicroservice % kubectl apply -f deploy.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?

any help is appreciated

**Comment by adamsitnik** [comment]
Hi @ckyiamah 

Please excuse me, but I am not familiar enough with docker to provide help.

I've googled the text error and got two following results:
https://stackoverflow.com/questions/72334044/the-connection-to-the-server-localhost8080-was-refused-did-you-specify-the-r
https://discuss.kubernetes.io/t/the-connection-to-the-server-localhost-8080-was-refused-did-you-specify-the-right-host-or-port/1464/5

Could you please take a look at the recommended troubleshooting steps and see if it helps?
