### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by Angera-Silas** [dotnet/core#8519]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

angera-silas@mukagati:~/Projects/VB$ dotnet new console -o MyApp -f net7.0
Segmentation fault (core dumped)

**Comment by adamsitnik** [comment]
Hi @Angera-Silas 

That is very unexpected.

Could you please try again?

If it reproduces, would you mind sharing the dump file (when an app crashes, the OS can save it's entire state into a dump file and we can provide it to .NET Runtime team members who are going to load it into a debugger and find source of the issue).

**Comment by Angera-Silas** [comment]
i tried again and it worked

**Comment by mairaw** [comment]
Great to hear. Closing the issue then.
