### ISSUE TITLE
Not able to run command dotnet on terminal

### ISSUE THREAD

**Issue by fireideas007** [dotnet/core#8520]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @fireideas007 

Have you run the right macOS installer (x64 or arm64)?

![image](https://github.com/dotnet/core/assets/6011991/12a52827-ee53-4291-a96c-32800ed5d10c)

If you receive a 'dotnet' is not recognized as an internal or external command error, make sure you opened a new command prompt.
