### ISSUE TITLE
The command could not be loaded, possibly because:   * You intended to execute a .NET application:       The application 'new' does not exist.   * You intended to execute a .NET SDK command:       No .NET SDKs were found.

### ISSUE THREAD

**Issue by evignesh364** [dotnet/core#8521]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by adamsitnik** [comment]
Hi @evignesh364 

Did you run exact the same command provided in the tutorial?

```cmd
dotnet new console -o MyApp -f net7.0
```
