### ISSUE TITLE
The term 'dotnet' is not recognized as the name of a cmdlet - Powershell Error

### ISSUE THREAD

**Issue by tppl-repo** [dotnet/core#8522]
Windows 10 Pro - Powershell error, when run command 'dotnet'

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
![dotnet-powershell-error](https://github.com/dotnet/core/assets/110044951/e59425ff-f2c6-4998-b3ee-47a0c0e6bacb)

+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by steveharter** [comment]
The install should have set the `PATH` environment variable to `c:\Program Files\dotnet` where the `dotnet.exe` lives.


Does `dotnet` work in a command prompt, outside of PowerShell?

**Comment by mairaw** [comment]
Can you run `where.exe dotnet` and let us know the results? Did you open a new window after the installation?
