### ISSUE TITLE
.net sdk not found ( dotnet: command not found)

### ISSUE THREAD

**Issue by Allen-Ole** [dotnet/core#8529]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you install the .NET SDK? If so, did you open a new command prompt after installation?

**Comment by Allen-Ole** [comment]
Maira, Yes I got it to work fine and it took me this long to respond because I have been on vacation. Thank you.Greg Olsen Sent from Mail for Windows From: Maira WenzelSent: Thursday, June 8, 2023 8:47 PMTo: dotnet/coreCc: Allen-Ole; AuthorSubject: Re: [dotnet/core] .net sdk not found ( dotnet: command not found) (Issue #8529) Did you install the .NET SDK? If so, did you open a new command prompt after installation?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mairaw** [comment]
I hope you had a great vacation. I'm glad to hear you got it working.
