### ISSUE TITLE
error

### ISSUE THREAD

**Issue by userhghfhfhfg** [dotnet/core#8531]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error =
              Error: Invalid option(s):
-f net7.0
   'net7.0' is not a valid value for -f. The possible values are:
      net6.0   - Target net6.0

**Comment by mairaw** [comment]
Have you installed the .NET 7 SDK as instructed on the install step @userhghfhfhfg?

From the error message, it seems you have .NET 6 SDK installed.

Can you sure the results of `dotnet --info`?
