### ISSUE TITLE
Create a new project

### ISSUE THREAD

**Issue by VieiracredPlanejamento** [dotnet/core#8534]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by mairaw** [comment]
Oi @VieiracredPlanejamento!

Did you install the .NET SDK? If so, did you start a new command prompt window?
