### ISSUE TITLE
net7.0' is not a valid value for -f (Framework)

### ISSUE THREAD

**Issue by mkemall** [dotnet/core#8536]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Have you installed the .NET 7 SDK? If so, which type (arm64 or x64)? Are you on what kind of Mac?
