### ISSUE TITLE
.NET June 2023 Update - .NET 7.0.7, .NET 6.0.18

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8539]
# .NET June 2023 Update

## Release Notes
* [7.0.7](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.7/7.0.7.md)
* [6.0.18](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.18/6.0.18.md)

## Status

Asset Type | 7.0.7 | 6.0.18 | Notes
-- | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux)| ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ | ✅
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget)| ✅ | ✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ | ✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅ | ✅
## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by jahav** [comment]
When I use the new docker SDK image for build,
```docker
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
...
RUN dotnet build "Some.csproj" -c Release -o /app/build
```
I get an error about newer version of analyzers.
> The .NET SDK has newer analyzers with version '7.0.3' than what version '7.0.1' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference.

The 7.0.1 version of analyzers are resolved directly from net7.0 target (at least project.assets.json  says so)
```
"projectFileDependencyGroups": {
    "net7.0": [
      "Some.StartupInfrastructure >= 1.0.0",
      "Microsoft.CodeAnalysis.Analyzers >= 3.3.4",
      "Microsoft.CodeAnalysis.NetAnalyzers >= 7.0.1",
      "SonarAnalyzer.CSharp >= 9.0.0.68202",
      "StyleCop.Analyzers >= 1.2.0-beta.435"
    ]
  },
```

The Microsoft.CodeAnalysis.NetAnalyzers doesn't even have a published 7.0.3 version on [Nuget](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers), only preview.

The questions:
* Is the missing analyzer version from nuget intentional?
* How can I increase the version of analyzers? Do I have to reference them directly? There is quote possibly an error on my side.

**Comment by leecow** [comment]
@jahav - I see that Microsoft.CodeAnalysis.NetAnalyzers 7.0.3 was published to NuGet late yesterday. Please give it a go again and let us know if it's still a problem for you.

**Comment by jahav** [comment]
Thanks for info. As expected, an error was on my side. The direct dependendcy was hiding in `Directory.Build.props`

**Comment by shrayasr** [comment]
Hey, 

Today, we got the following error when trying to install a service on a client machine: 

```
Description: A .NET application failed.
Application: REDACTED.exe
Path: C:\Program Files (x86)\redacted\REDACTED.exe
Message: You must install or update .NET to run this application.

App: C:\Program Files (x86)\redacted\REDACTED.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.18' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  6.0.16 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.18&arch=x64&rid=win10-x64
```

The application however was built was the `6.0.408` SDK. Here is my `global.json`

```
{
  "sdk": {
    "version": "6.0.408"
  }
}
```

From my understanding, what I can see on the `6.0.16` section in https://dotnet.microsoft.com/en-us/download/dotnet/6.0 tells me that if I build with `6.0.408` then I can run with the `6.0.16` runtime. 

Additionally, I don't have the SDK  `6.0.410` which is required to build applications targeting `6.0.18`.

My confusion with the error above is that it tells me that I **need** `6.0.18`. How can a SDK built in the _past_ require a runtime in the _future_? I would be much obliged if there are any docs that I can read on this to educate myself. 

Thanks.

**Comment by shrayasr** [comment]
> My confusion with the error above is that it tells me that I **need** `6.0.18`. How can a SDK built in the _past_ require a runtime in the _future_? I would be much obliged if there are any docs that I can read on this to educate myself.

Hello,

Just checking if there are any updates on this?

**Comment by mairaw** [comment]
@shrayasr how are you building and publishing the app? Can you share the commands you're using it? Are you sure the global.json is impacting the folder you're currently publishing the app from? Maybe it was built using a later version.

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/8611
