### ISSUE TITLE
Command-line DotNet commands not found under Windows 10

### ISSUE THREAD

**Issue by marcusts** [dotnet/core#854]
I followed all f the installation instructions, but am not able to run command such as:

$ dotnet new lib -o mylibrary

ETC., ETC.

Shall I add a path to my environment?  It would be ideal if you made this more clear.

**Comment by svick** [comment]
If you successfully followed the installation instructions, then `dotnet` will be added to the PATH automatically, you shouldn't need to do anything else.

What is the error you're getting? What instructions did you follow? Did you restart your command line? Which command line are you using?

**Comment by marcusts** [comment]
I am a client-server programmer working with Visual Studio 15.3 in Windows 1.  I did indeed follow all of the instructions . The name is not known when typing it from a command line, so there is no path to that executable.

**Comment by colinbowern** [comment]
I am seeing this as well - Windows 10 x64. Looking at the install logs in temp there is no indication of path variable change. I do see the Environment parameter in the Wix source however:

https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/pkg/packaging/windows/host/host.wxs

Any way to unpack the installer executable to get at the MSI or pass along verbose logging parameters?

**Comment by Centaur** [comment]
This also happens on Mac OS.

**Comment by Petermarcu** [comment]
@rakeshsinghranchi can you help with verbose logging instructions. After installation, `dotnet` should be on the path.

**Comment by rakeshsinghranchi** [comment]
Here are the details : 

**.NET Core 2.0.0 x64 installer bundle:**
 http://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-runtime-2.0.0-win-x64.exe

**Inner MSIs of the installer:**
http://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-host-2.0.0-win-x64.msi
http://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-hostfxr-2.0.0-win-x64.msi
http://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-runtime-2.0.0-win-x64.msi

MSI Verbose logging : http://wixtoolset.org/documentation/manual/v3/howtos/general/get_a_log.html

**To extract a bundle package :**
Extract wix toolset: https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311exe.zip
Locate dark.exe and run below command :
   dark.exe -x <targetDir> <PathToBundlePackage>

**To collect VS setup log :** 
Download and run the collection tool - https://aka.ms/vscollect. Instruction is on the page.

**Comment by Petermarcu** [comment]
Is anyone that is hitting this issue able to follow the logging instructions so we can try to figure out whats going on?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #3281](https://github.com/dotnet/core-setup/issues/3281) via [**ZenHub**](https://www.zenhub.com/)
