### ISSUE TITLE
Missing present file

### ISSUE THREAD

**Issue by AndrewCoogan** [dotnet/core#8545]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am getting the following message in the terminal when I run:

/usr/local/share/dotnet/sdk/7.0.304/Current/Microsoft.Common.props(62,3): error MSB4019: The imported project "/Users/.../learning/obj/learning.csproj. * .props" was not found. Confirm that the expression in the Import declaration "/Users/.../learning/obj/learning.csproj. * .props" is correct, and that the file exists on disk. [/Users/.../learning/learning.csproj]

The build failed. Fix the build errors and run again.

The file is there:

<img width="250" alt="image" src="https://github.com/dotnet/core/assets/7774991/400ab7a9-b996-4f17-9eee-e35041cb5f56">

**Comment by adamsitnik** [comment]
Hi @AndrewCoogan 

It's very strange, could you please create a brand new app, try again and share the output if it fails again?

```cmd
dotnet new console -o MyApp2 -f net7.0
cd MyApp2 
dotnet run
```

**Comment by AndrewCoogan** [comment]
Thank you, Adam. It turns out that in the file path there was a ‘/‘ in a folder name which caused the issues. Removing that slash fixed the error.
________________________________

**Comment by adamsitnik** [comment]
@AndrewCoogan thank you for letting me know!
