### ISSUE TITLE
.NET issue

### ISSUE THREAD

**Issue by o-artemis-o** [dotnet/core#8549]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

tried to run .NET on cmd  prompt and it responded with this:
Couldn't find a project to run. Ensure a project exists in C:\Users\****, or pass the path to the project using --project.

**Comment by adamsitnik** [comment]
Hi @o-artemis-o 

The first command from the tutorial creates a new project file and puts it into `MyApp` folder.

```cmd
dotnet new console -o MyApp -f net7.0
```

`dotnet run` works only in folders where there is a project file, so you need to change the directory to a folder with the project file:

```cmd
cd MyApp 
```

Please give it a try and let me know if it helped.

**Comment by o-artemis-o** [comment]
i think it helped, thanks. not sure what to do after i run the folder i created though

**Comment by mairaw** [comment]
Can you explain a bit more? Were you able to run the project with `dotnet run`?

**Comment by o-artemis-o** [comment]
cmd prompt responded with 'hello world'

**Comment by mairaw** [comment]
So it's working, right?

**Comment by o-artemis-o** [comment]
yep, but its not responding to any code i input

**Comment by mairaw** [comment]
How are you trying to input the code? Did you open the Program.cs file, edited the program and then tried `dotnet run` again?

**Comment by o-artemis-o** [comment]
never mind, i dont really need to use the program its fine
