### ISSUE TITLE
Not able to create a project containing app.xaml using Dot Net Standard 2.0

### ISSUE THREAD

**Issue by marcusts** [dotnet/core#855]
I have installed all of the components, and can indeed create new projects using Dot Ne Standard and compile them.

*However* I am not allowed to create a *solution based on Dot Net Standard 2.0.   Only single class libraries. Is this as intended?  If so, could you state it as a headline in your blogs and announcements?

Normal users want to create a solution using this new technology.  So we want to house app.xaml in a Dot Net Standard project.  This appears to be impossible.

Are you really asking us to house our solution's application page in an old-style PCL?

**Comment by svick** [comment]
What would be the advantage of making the library that contains app.xaml a .Net Standard library? I don't think you would be able to to use that app.xaml from e.g. an ASP.NET Core application, so I think making that library a .Net Framework library (not even a PCL) makes sense.

Or am I missing something?

**Comment by marcusts** [comment]
I am a client-sever guy, hence the nature of my request.  I am not a web developer.

**Comment by Petermarcu** [comment]
Which types of applications are you trying to share your app.xaml across? WPF and UWP? These are UI frameworks and a layer above .NET Standard. Just using a .NET Framework library would allow you to share across multiple WPF applications. Can you give more insight into what you are trying to share across?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/standard #533](https://github.com/dotnet/standard/issues/533) via [**ZenHub**](https://www.zenhub.com/)
