### ISSUE TITLE
Connection is not private

### ISSUE THREAD

**Issue by benpartington** [dotnet/core#8552]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello, 

When I try to run the debugger for the first time I get this error:

![image](https://github.com/dotnet/core/assets/91614727/9e5b9a2d-d391-4949-a8f0-386211384f4c)

"Connection not private. Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_INVALID"

**Comment by mairaw** [comment]
If you launch the application again, do you still see the same error? 

/cc @danroth27

**Comment by danroth27** [comment]
It seems that browsers made a somewhat recent change that you need to shut down and restart the browser for the certificate trust to get picked up. So it's really the browser that needs to be restarted, not necessarily the app.

**Comment by benpartington** [comment]
Thanks! I tried running the app (from visual studio) as http rather than https and that worked?Sent from my iPhoneOn 17 Jun 2023, at 23:58, Daniel Roth ***@***.***> wrote:﻿
It seems that browsers made a somewhat recent change that you need to shut down and restart the browser for the certificate trust to get picked up. So it's really the browser that needs to be restarted, not necessarily the app.
