### ISSUE TITLE
dotnet run を実行すると、エラーが表示されます。エラーが示していることが分かりません

### ISSUE THREAD

**Issue by girigir** [dotnet/core#8553]
dotnet run を実行すると、エラーが表示されます。このエラー内容は何をどのようにしたら良いのでしょうか？
以下のエラー内容です。
実行するプロジェクトが見つかりませんでした。プロジェクトが C:\Users\○○ に存在することを確認するか、--project を使用してパスをプロジェクトに渡してください。

**Comment by adamsitnik** [comment]
Hi @girigir 

The first command from the tutorial creates a new project file and puts it into `MyApp` folder.

```cmd
dotnet new console -o MyApp -f net7.0
```

`dotnet run` works only in folders where there is a project file, so you need to change the directory to a folder with the project file:

```cmd
cd MyApp 
```

Please give it a try and let me know if it helped.
