### ISSUE TITLE
cannot open dotnet (cs) file

### ISSUE THREAD

**Issue by niti0309** [dotnet/core#8554]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
no matter how many times I repair it or uninstall it the problem still persists 
<img width="485" alt="image" src="https://github.com/dotnet/core/assets/136894236/58af2c3e-bb2a-46b8-9717-b976c3d29184">

**Comment by adamsitnik** [comment]
Hi @niti0309 

What error exactly are you getting? Could you copy-paste it here or provide a screen shot?
