### ISSUE TITLE
Why some class of .NET doesn't implement interfaces it uses?

### ISSUE THREAD

**Issue by Orange23333** [dotnet/core#8555]
### Description

I found this when I was trying to warp `SortedList<AClass>`. I copied all interfaces `SortedList` used, and tried to implement them. Then, I found `ICollection<AClass>` required a `void Add(AClass)` method, but `SortedList` which also inherited from `ICollection<T>` implemented `bool Add(T)` not `void Add(T)`.

![QQ截图20230618064857](https://github.com/dotnet/core/assets/18095289/b0419a0b-3b6c-4ee0-b1aa-532e1c71e471)

I confused. Why `SortedList` don't need to implement interface which it inherited from?

### Configuration

* .NET: 6.0
* OS: Windows 10 22H2 19045.2965
* Architecture: x64

**Comment by svick** [comment]
`SortedSet<T>` implements `ICollection<T>.Add` [explicitly](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation). You can see that [in the documentation](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1.system-collections-generic-icollection-t--add) and also [in the source code](https://github.com/dotnet/runtime/blob/7e798a9/src/libraries/System.Collections/src/System/Collections/Generic/SortedSet.cs#L301).

It seems that VS does not show explicit interface implementations when viewing metadata of a type.

**Comment by Orange23333** [comment]
Got it. Thank you very much!
