### ISSUE TITLE
[Android] Maui Net7 Shadow on border with RoundRectangle does not mimic the corners

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [dotnet/core#8559]
When adding a Shadow to a border with a RoundRectangle, the shadow rains square.

`<Border Stroke="#434343" StrokeThickness="2" Margin="0" Padding="10,20,10,20" BackgroundColor="#121212">`
`    <Border.StrokeShape>`
`           <RoundRectangle CornerRadius="10"/>`
`    </Border.StrokeShape>`
`    <Border.Shadow>`
`          <Shadow Brush="#656565" Offset="15,15" Radius="400" Opacity="1"/>`
`    </Border.Shadow>`
`    <Label Text="{Binding Name}" HorizontalTextAlignment="Center"/>`
`</Border>`

* What behavior are you seeing, and what behavior would you expect?
The behavior I see is: 
![image](https://github.com/dotnet/core/assets/82555340/b370eeea-11d8-472e-838a-16450c68b55e)

The behavior I expect would be the shadow to mimic the border's corner

* Which version of .NET is the code running on? net7.0
* What OS and version, and for Linux, what distro? Android (tested on API 30 and 33)

**Comment by CarnaViire** [comment]
@Redth can you please transfer the issue to dotnet/maui? Thanks!

**Comment by Imaginary-Narwhal** [comment]
Oh wow! I thought I was on the dotnet/maui, I apologize.
