### ISSUE TITLE
Strange generic expressions type check behavior

### ISSUE THREAD

**Issue by chrbaeu** [dotnet/core#856]
The following code prints with netcoreapp1.0 and net461:
```
IsExpression: True
IsExpression: True
```
And  with netcoreapp2.0:
```
IsExpression: False
IsExpression: True
```
I think netcoreapp2.0 should show the same results as the other.
```
namespace ExpressionBugTest {
    class Program {
        static void Main(string[] args) {
            Expression<Func<string, bool>> predicate = x => x != null;
            Console.WriteLine("IsExpression: " + (predicate.GetType().GetGenericTypeDefinition() == typeof(Expression<>)));
            Console.WriteLine("IsExpression: " + (typeof(Expression<Func<string, bool>>).GetGenericTypeDefinition() == typeof(Expression<>)));
            Console.ReadKey();
        }
    }
}
```

**Comment by svick** [comment]
As far as I can tell, the reason for this is that `predicate.GetType().GetGenericTypeDefinition()` returns the internal type [`Expression1<T>`](https://github.com/dotnet/corefx/blob/43f78840284de81bfd1b5fe4deceedf95c673cf8/src/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L358), which inherits from `Expression<T>` and was introduced as an optimization in https://github.com/dotnet/corefx/pull/13133.

I'm not sure what is the best way to correctly check that a `Type` is an `Expression<T>`.

**Comment by stephentoub** [comment]
cc: @bartdesmet, @VSadov

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24481](https://github.com/dotnet/corefx/issues/24481) via [**ZenHub**](https://www.zenhub.com/)
