### ISSUE TITLE
The term 'dotnet' is not recognized...

### ISSUE THREAD

**Issue by soleshhaker** [dotnet/core#8561]
### Description
Hi
In Visual Studio Code I get error saying: "dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
![obraz](https://github.com/dotnet/core/assets/66915452/65fbb0a5-0861-42ca-82d9-473b99fe52a7)

It works fine in cmd 
![obraz](https://github.com/dotnet/core/assets/66915452/955a6f90-eaec-44fc-909d-5bba71fdd8e6)

Here's my dotnet folder 
![obraz](https://github.com/dotnet/core/assets/66915452/ee736fee-2a03-4d1c-a27e-8f26834c88e9)

Even got sdk .net 6 
![obraz](https://github.com/dotnet/core/assets/66915452/88de06f9-731f-40d6-b28f-da8fd4d0e13d)
And here's my PATH
![obraz](https://github.com/dotnet/core/assets/66915452/26327802-98c3-4290-93c9-459927e9b3ff)
Also for user 
![obraz](https://github.com/dotnet/core/assets/66915452/7351ae21-86d3-4e1c-973a-5424155bab8a)

### Configuration
I'm running Win10 64x [Version 10.0.19045.3086]

### Other information
I tried repairing redistributables, reinstalling visual studio code, reinstalling .net sdk, uninstalling visual studio 2022, restarting PC each time, running as administrator, opening new terminals each time. Using custom path in C# extensions also didn't work. I'm running out of ideas, any way to fix this?

**Comment by mairaw** [comment]
And did you restart VS Code after installing it?

**Comment by timheuer** [comment]
> reinstalling .net sdk

How are you installing the SDK @soleshhaker? /cc @baronfel

**Comment by baronfel** [comment]
PATH looks good from those screenshots, but `dotnet --info` from both the terminal as well as VSCode's built-in terminal would be useful info to have.

**Comment by soleshhaker** [comment]
> And did you restart VS Code after installing it?

Yes I should have stated that when using new terminal, I meant that after restarting VS Code I additionally close old terminal and start a new one, so yes I did restart it each time.


> How are you installing the SDK @soleshhaker? /cc @baronfel

I uninstall the old one in "add or remove programs", then I just install what I downloaded from https://dotnet.microsoft.com/en-us/download specifically I Use this button to download
![obraz](https://github.com/dotnet/core/assets/66915452/463d7042-d7e9-4901-a9d2-49f07f9d737f)
I get file named dotnet-sdk-7.0.304-win-x64 and proceed with installing it as any other program.





> PATH looks good from those screenshots, but `dotnet --info` from both the terminal as well as VSCode's built-in terminal would be useful info to have.

![obraz](https://github.com/dotnet/core/assets/66915452/22e66c00-4f5b-4ccb-9ff0-35ce09357f6f)

**Comment by soleshhaker** [comment]
any chance of help with this? I'm using system cmd and it works fine, but it's kinda annoying

**Comment by MajesticalDiscomfort** [comment]
What I see from the info is that it says "Environment variables: Not set" even though I was convinced I had set them. I guess there's a syntax that nobody told me about.

Seeing as how I would *also* like a resolution to this issue, I'm hoping someone knows what's going on.
![image](https://github.com/dotnet/core/assets/114880714/46bd44bf-9e34-446b-804f-17f37d9df667)
![image](https://github.com/dotnet/core/assets/114880714/3fea3f4d-aebc-465a-b136-eb2853327a55)

**Comment by mairaw** [comment]
Not sure what causes this but this thread offers a workaround:
https://stackoverflow.com/questions/69921890/dotnet-works-from-windows-10-command-prompt-but-not-in-vscode

adding @timheuer and @baronfel to comment

**Comment by Andrei-Sager** [comment]
> And did you restart VS Code after installing it?

Hahaha this worked for me. Thanks :)
