### ISSUE TITLE
I am having an issue with dotnet and VS Code

### ISSUE THREAD

**Issue by DonTheCoder7** [dotnet/core#8567]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have Windows 11. I followed the directions of installing .NET 7 down to the T but I keep getting the dotnet not recognized error. I restarted my system, added the dotnet path to PATH in my environment variables and I still have not resolved my issue. My computer literally refuses to recognize dotnet. Also my VS Code doesn't recognize dotnet either.

**Comment by leecow** [comment]
Can you try running `dotnet --info` in a cmd prompt and let us know the result?

**Comment by DonTheCoder7** [comment]
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by CarnaViire** [comment]
Do you know the path you are installing .NET to? Can you find it there?
If it is e.g. in `C:\Program Files\dotnet\dotnet.exe`, can you call `C:\"Program Files"\dotnet\dotnet.exe --info`?

**Comment by DonTheCoder7** [comment]
I can definitely see it in the folder, and the path has been direct added to my PATH, but my computer seems to not recognize the fact that it is installed. I have tried every troubleshooting step as well. I uninstalled and reinstalled it, I restarted my computer after installation, I restarted VS Code after installation, I uninstalled and reinstalled that too, I even tried adding the Framework path as well. Nothing seems to work

**Comment by CarnaViire** [comment]
@DonTheCoder7 I am sorry for your troubles. That must be frustrating.
If you call `<path-to-dotnet>\dotnet.exe --info` (e.g. `C:\"Program Files"\dotnet\dotnet.exe --info`), does that output you anything? Can you share the output with us please? Including how you call the command as well.

**Comment by DonTheCoder7** [comment]
My computer doesn't output any of that. I found the sdk and .exe files as well, and they are exactly where they should be, and my path is exactly typed out and exactly where it should be. And I ran through every trouble shooting step I could find and think of @CarnaViire
