### ISSUE TITLE
Failed trusting the certificate error dialog

### ISSUE THREAD

**Issue by jarnoldv** [dotnet/core#8568]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I clicked yes to trust the certificate, I got an error dialog saying Adding the certificate to the Trusted Root Certificates store failed with the following error:

Failed trusting the certificate
![failedcert](https://github.com/dotnet/core/assets/97551079/f0865f5c-adbd-490c-8748-bf7125195d83)

**Comment by jarnoldv** [comment]
This is almost certainly having to do with the ESET control software installed on my dev machine. I'll take it up with our internal support.

**Comment by mahmoudsobhy74** [comment]
Hello @jarnoldv can you share with me how you solve this issue because I face it now 
![image](https://github.com/dotnet/core/assets/80815724/b396be72-2934-4a33-8206-6f17650aa53a)
