### ISSUE TITLE
.NET June OOB 2023 Update - .NET 7.0.8, .NET 6.0.19

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8570]
# .NET June 2023 Update

We are releasing a second update this month to address a regression in our earlier [release ](https://github.com/dotnet/core/issues/8539) on June 13th 2023. The new versions are .NET 6.0.19 and .NET 7.0.8. The regression is functional and doesn't require action on your part unless you are affected by the issue.

**The regression:** loading null-password-encrypted PFX certificates can fail unexpectedly for certificates that previously loaded successfully before upgrading to .NET 6.0.18 or 7.0.7. 
More Details of this regression are listed at [.NET June OOB Updates](https://support.microsoft.com/kb/5028608) and later in the blog post.

## Do I need to install 6.0.19 / 7.0.8?

There is no need to install these updates unless you are affected by the functional regression listed at [KB5028608](https://support.microsoft.com/kb/5028608). 
If you are not affected by the functional regression described above, you can safely remain on 6.0.18 / 7.0.7. 

## Is 6.0.19 / 7.0.8 a security update?

No. These updates contain no new security fixes beyond what already shipped in 6.0.18 / 7.0.7. 
As long as you are running at least 6.0.18 or 7.0.7, you are protected with all of the latest available security fixes.

## Release Notes
* [7.0.8](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.8/7.0.8.md)
* [6.0.19](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.19/6.0.19.md)

## Status

Asset Type | 7.0.8 | 6.0.19 | Notes
-- | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux)| ✅ | ✅
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows) | ✅ | ✅
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget)| ✅ | ✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅ | ✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 35](https://learn.microsoft.com/dotnet/core/install/linux-fedora) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 36](https://learn.microsoft.com/dotnet/core/install/linux-fedora)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 18.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)| ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅ | ✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅ | ✅
## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by Nothing-Works** [comment]
![image](https://github.com/dotnet/core/assets/18606648/952a5e35-6f27-40ea-811d-8672a1d40589)
@rbhanda FYI, on the [website](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) it shows `Included in
Visual Studio 17.6.3` but it is not included.

**Comment by greenorgs** [comment]
We are utilizing the base image as 'mcr.microsoft.com/dotnet/aspnet:**_7.0.8-jammy-amd64_**'; however, it has been identified to possess the following security vulnerabilities. We kindly request your attention to this matter.

**_993406-DotNet (Nuget) Security Update for Microsoft.NetCore.App.Runtime.linux-arm (GHSA-555c-2p6r-68mm)_**

![image](https://github.com/dotnet/core/assets/64127305/2eb07267-a184-4397-b809-02e1688647bd)

**Comment by mthalman** [comment]
> We are utilizing the base image as 'mcr.microsoft.com/dotnet/aspnet:**_7.0.8-jammy-amd64_**'; however, it has been identified to possess the following security vulnerabilities. We kindly request your attention to this matter.
> 
> **_993406-DotNet (Nuget) Security Update for Microsoft.NetCore.App.Runtime.linux-arm ([GHSA-555c-2p6r-68mm](https://github.com/advisories/GHSA-555c-2p6r-68mm))_**

Followed up offline on this. This was caused by the application itself having a dependency on an older version of Microsoft.Identity.Web which had a transitive dependency on a newly vulnerable version of System.Security.Cryptography.Pkcs. By upgrading the referenced version of Microsoft.Identity.Web, the issue was resolved.

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/8611
