### ISSUE TITLE
Linq to sql installed but not showing in the add item section 

### ISSUE THREAD

**Issue by Shahrukh-coder** [dotnet/core#8571]
![errorlinq](https://github.com/dotnet/core/assets/65332028/a1c075df-fb70-4c0e-a361-d6afbc027471)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by CarnaViire** [comment]
This seems to be related to VisualStudio IDE, not to .NET. Please open the issue in https://developercommunity.visualstudio.com/content/problem/post.html?space=8. Thanks!
