### ISSUE TITLE
Unexpected behaviour when parsing a string to a decimal number on Ubuntu with a French environment

### ISSUE THREAD

**Issue by Eromnoj** [dotnet/core#8575]
### Description

Hello, 
I'm learning C# following the courses from the Microsoft website, and I had an unexpected result  using decimal.TryParse, a string with a decimal number using a decimal point cannot be parsed (12.3), but can be when written with a comma (12,3) 

### Configuration

.NET version : 7.0.108 (installation following the  [official doc](https://learn.microsoft.com/fr-fr/dotnet/core/install/linux-ubuntu-2204) )
OS : Ubuntu 22.04.2 LTS
Architecture : x64
Specific : System and desktop (Gnome) configured in French, using VSCode

### Example from the solution of this [exercise](https://learn.microsoft.com/fr-fr/training/modules/csharp-convert-cast/4-challenge)

Code I tried : 

```
string[] values = { "12.3", "45", "ABC", "11", "DEF" };

decimal total = 0m;
string message = "";

foreach (var value in values)
{
    decimal number; // stores the TryParse "out" value
    if (decimal.TryParse(value, out number))
    {
        total += number;
    } else
    {
        message += value;
    }
}

Console.WriteLine($"Message: {message}");
Console.WriteLine($"Total: {total}");
```

Expected output : 
```
Message: ABCDEF
    Total: 68.3
```

Actual output : 
```
Message: 12.3ABCDEF
Total: 56
```

if I change the array declaration to : 
```
//notice the comma instead of the point
string[] values = { "12,3", "45", "ABC", "11", "DEF" }; 
```

Here is the output : 
```
//Here is the comma again
Message: ABCDEF
Total: 68,3
```

And this the error I get when I parse : 

```

Console.WriteLine((decimal.Parse("12.3")));

//Output :

Unhandled exception. System.FormatException: The input string '12.3' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Decimal.Parse(String s)
   at Program.<Main>$(String[] args) in /home/jonathan/CODE/csharp/ConsoleApp1/Program.cs:line 38
```

The results are the same if I try to parse from a string to a double or float.

Once I configured my OS to be fully in English (not only the display of the numbers) the results are the ones expected.

**Comment by svick** [comment]
This is (unfortunately), the expected behavior. The tutorial should be changed to use the invariant culture:

```c#
if (decimal.TryParse(value, CultureInfo.InvariantCulture, out number))
```

**Comment by Eromnoj** [comment]
> This is (unfortunately) the correct behavior: most number parsing methods in .Net default to using the current culture. The tutorial should be changed to use the invariant culture:
> 
> ```cs
> if (decimal.TryParse(value, CultureInfo.InvariantCulture, out number))
> ```

Oh ok, good to know. 

I find it a little disturbing, but I'll get used to it eventually.

Thanks for the reply, I close the issue.
