### ISSUE TITLE
.NET Core 3.0 Roadmap Update,I hope to support web form cross platform

### ISSUE THREAD

**Issue by ghd258** [dotnet/core#858]
I hope to support web form cross platform, in China, a lot of net programmers to Java, I hope the rapid development of net

**Comment by ghd258** [comment]
The latter will add to those API, and with those enhancements, the general release date, with these, I can plan whether the project will soon .Net core 2

**Comment by benaadams** [comment]
Do you want aspnet 3.0 roadmap? You may want to raise issue in https://github.com/aspnet/Home

You may also want to look at [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/index) and tutorial [Getting started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start)

**Comment by ghd258** [comment]
aspx Pages in ASP.NET Core
Can support the current web from ASPX page and the current controls

**Comment by ghd258** [comment]
Can support the  Web from controls

**Comment by ghd258** [comment]
Can support the ASP.NET  server control

**Comment by csharpfritz** [comment]
While I love this idea, and it's something that I think could benefit the AspNetCore platform by migrating the webforms programming model to it, it's a very hard task. 

Web forms is intertwined with IIS and will require a lot of work to disconnect the two so that it could be plugged in to the pipeline.

**Comment by ghd258** [comment]
System.Web.UI
System.Web.UI.Adapters
System.Web.UI.HtmlControls
System.Web.UI.WebControls.Adapters
System.Web.UI.WebControls.WebParts
System.Web.UI.WebControls;
Do you support these API?

**Comment by ghd258** [comment]
Do you support these
AntiXss
patterns & practices–Enterprise Library  
patterns & practices -Unity

**Comment by ghd258** [comment]
Razor Pages support ASP.Net server controls or have server controls?
The MVC programming model to his advantage, but there are also disadvantages, page data and logic processing mainly by JS control, C# is only to the front-end data transfer function, the C# instead of weakening, the enhanced JS and web; from ASPX, aspx.cs aspx.cs played this way with powerful back-end processing capabilities of C#, not only can provide data, but also can process the front interface with C# display or logical processing; hope to use the Razor Pages Cs, play the powerful function of C#

**Comment by mokeyish** [comment]
@ghd258 哥们，现在谁还用Web Form啊?构建大型项目一点都不方便，反而Angular不错，像堆积木一样，构建Web项目。

**Comment by Petermarcu** [comment]
This conversation is better had on the aspnet/home repo. I'm going to close this one here and if anyone wants to continue the conversation, please open an issue on aspnet/home.

**Comment by sgf** [comment]
turn back the wheel of history
