### ISSUE TITLE
Deploy Microservice (to Azure) Tutorial Issue

### ISSUE THREAD

**Issue by burcinsahin** [dotnet/core#8580]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
----------------------------------------------------------------------------------------------------------------
I deployed the service to Azure and watched it with the external ip adress:
![image](https://github.com/dotnet/core/assets/23029400/53cc442e-59cb-4dac-8b23-49b6caa7d90f)
However, I cannot reach the page via external ip.
http://40.83.174.50/weatherforecast

**Comment by CarnaViire** [comment]
@erjain @nishanil can you please help here?

**Comment by burcinsahin** [comment]
I am not interested in Azure anymore.
