### ISSUE TITLE
k

### ISSUE THREAD

**Issue by Mr1TeRx** [dotnet/core#8581]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Mr1TeRx** [comment]
f5

**Comment by Mr1TeRx** [comment]
rey

**Comment by mairaw** [comment]
Can you explain what is the issue you're having?
