### ISSUE TITLE
When launching the app in edge, I received a certificate error.

### ISSUE THREAD

**Issue by SDmorgan** [dotnet/core#8590]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When launching the app in edge, I received a certificate error. The certificate could not be trusted. I changed the browser to Chrome and it worked fine.

**Comment by mairaw** [comment]
Please shut down all your browser instances and try to run the project again.

Let us know if that works.

/cc @danroth27 @DamianEdwards
