### ISSUE TITLE
Can't run dotnet command after install

### ISSUE THREAD

**Issue by conoremcd** [dotnet/core#8593]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Opened a new Terminal window after installing intel version, getting following error:
<img width="566" alt="Screen Shot 2023-06-29 at 6 51 36 PM" src="https://github.com/dotnet/core/assets/39396733/de2efb45-5352-421d-a645-51d81d96bb36">

machine details:
<img width="605" alt="Screen Shot 2023-06-29 at 6 53 23 PM" src="https://github.com/dotnet/core/assets/39396733/b9fd56dc-5d61-4d67-a284-bccbb2a8f4f5">

**Comment by mairaw** [comment]
Did you install the SDK? If so, which version? And did you restart the terminal after the installation?

**Comment by conoremcd** [comment]
yes, I attempted the installation and it said it was installed successfully, but running the dotnet command in a new terminal window still gave the error.

**Comment by conoremcd** [comment]
I did restart the Terminal application too, to be clear, not just a new window.

**Comment by conoremcd** [comment]
installed the .NET SDK x64 (Intel) version

**Comment by mairaw** [comment]
Can you check if you see dotnet installed on the install folders as shown at https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos#check-for-install-folders 

Maybe dotnet is not on the path.

/cc @eiriktsarpalis

**Comment by conoremcd** [comment]
<img width="775" alt="Screen Shot 2023-07-06 at 6 00 39 PM" src="https://github.com/dotnet/core/assets/39396733/88555afb-7fc2-4ab4-a99c-ea2a35eb3bf6">

Looks like they exist, could the multiple versions be causing the issue?

**Comment by baronfel** [comment]
Hi @conoremcd - can you try running the `dotnet` binary located at `/usr/local/share/dotnet/dotnet` directly first to verify if the actual binary is executable? That would help debug any architecture-specific issues going on.

If that works, the next guess I'd have is that the symlink in (I think) `/usr/local/bin` wasn't created. There should be a symlink in that folder (or one of the other common symlinked-binary folders on macOS) that points to `/usr/local/share/dotnet/dotnet`. If there isn't then the installer may have had an issue. I believe the installer logs to the system log, which I think is `/var/logs/install.log` - is there anything interesting/relevant there?

**Comment by conoremcd** [comment]
Hi @baronfel getting a command not found when attempting to run the dotnet binary so it seems thats not actually executable for some reason. I also took a look into the install.log file and didn't see anything that stood out to me as an issue

**Comment by conoremcd** [comment]
<img width="571" alt="Screen Shot 2023-07-07 at 11 52 32 AM" src="https://github.com/dotnet/core/assets/39396733/5e100da4-329b-4601-ac8b-f0bea1303b95">

**Comment by baronfel** [comment]
@conoremcd is `dotnet` an exectuable? if you use the `file` command to inspect it, what's the output? That kind of `command not found` response is what I'd expect to see if you had an executable for a different architecture - e.g. accidentally installing an arm64 version of the SDK.

**Comment by conoremcd** [comment]
<img width="323" alt="Screen Shot 2023-07-07 at 12 31 16 PM" src="https://github.com/dotnet/core/assets/39396733/af646e5c-7f36-4223-8702-895c765c651a">
Looks like it is an executable?

**Comment by conoremcd** [comment]
I'm 100% sure I installed the intel version, but should I attempt an uninstall and just try again to be sure?

**Comment by mairaw** [comment]
It doesn't hurt @conoremcd

**Comment by mairaw** [comment]
Have you tried uninstalling and installing again?

**Comment by conoremcd** [comment]
I did and it still did not work

**Comment by ManickaP** [comment]
What's on your PATH (run `export`)? 
What might help is to add soft link to `dotnet`:
```
lrwxr-xr-x  1 root  admin  30 Mar 31 12:25 /usr/local/bin/dotnet -> /usr/local/share/dotnet/dotnet
```

That's how I have it on my mac and I think I added it myself manually.
