### ISSUE TITLE
.net problem 

### ISSUE THREAD

**Issue by musiala21** [dotnet/core#8594]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows
IT TELLS THAT THE PROCESSOR IS NOT SUITABE FOR DEVICE

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
I'm sorry to hear you're running into issues. Which kind of device do you have and what did you download/install? When are you getting the error?
