### ISSUE TITLE
Problem with ASP.NET Core 7.0 Runtime (v7.0.8).

### ISSUE THREAD

**Issue by rnikey** [dotnet/core#8595]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I downloaded ASP.NET Core 7.0 Runtime (v7.0.8).  Got message...
Thanks for downloading
ASP.NET Core 7.0 Runtime (v7.0.8) - Windows Hosting Bundle Installer!

I ran the file I downloaded, dotnet-hosting-7.0.8-win.exe.  Ran pretty fast but I guess there were no problems.

I continued down the webpage to do a Hello World tutorial.

I typed the command suggested but it gave the following message...
==================================
C:\Users\Mikey\Desktop>dotnet new console -o MyApp -f net7.0
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
=================================
I'm using Windows 11.

=================================
C:\Users\Mikey\Desktop>where dotnet
C:\Program Files\dotnet\dotnet.exe
=================================

**Comment by mairaw** [comment]
The hosting bundle only contains the runtime. You need to install the SDK separately to be able to to execute the SDK commands. To confirm what's installed on your machine, you can run `dotnet --info`. 

Let us know if you need any additional help!

**Comment by rnikey** [comment]
OK, I searched further, and yes, I needed to install the SDK.
The link labelled "Hello World in 5 minutes tutorial..." takes you to the tutorial, but missing the part where you need to download the SDK at the top.  You need to click the link on the left that says "Download and install" to expose the text at the top and get a further file to download and install.  This should be improved.
I'm moving forward so this can be closed now.  Thank you.

**Comment by mairaw** [comment]
Thanks for the feedback and I'm glad to hear it's working for you now.
