### ISSUE TITLE
Issue trying to use command prompt 

### ISSUE THREAD

**Issue by jambam64** [dotnet/core#8600]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

(The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.) thats the error i got when trying to enter this code 
C:\Users\jakey>dotnet new console -0 -f net7.0. im doing this on windows 10 if you can get back to me that would be great :)

**Comment by tarekgh** [comment]
The command your entered is wrong `dotnet new console -0 -f net7.0`. You should just execute `dotnet new console -f net7.0`. This should work. If you still have a problem, please ensure you have installed the .NET SDK as indicated in the step 
https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install.

**Comment by mairaw** [comment]
The command on the tutorial looks like this `dotnet new console -o MyApp -f net7.0` (it's the letter o, not a zero). You can use the copy button on the tutorial as well, to make sure you're typing the correct command.
