### ISSUE TITLE
error 100

### ISSUE THREAD

**Issue by SoberisSexy** [dotnet/core#8604]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

https://aka.ms/templating-exit-codes#100

**Comment by mairaw** [comment]
@baronfel are you familiar with this error code? @SoberisSexy can you provide more information about the error and when it happens?

**Comment by SoberisSexy** [comment]
I do apologize but i had some family issues to handle. I am having problems with WP API authentication. i am receiving a 401 error. Desperately need assistance.
