### ISSUE TITLE
impossible d installer 

### ISSUE THREAD

**Issue by Moez-007** [dotnet/core#8605]
![Screenshot_1](https://github.com/dotnet/core/assets/134169687/269116d6-060f-4a5a-a183-09a1dfc4f09d)
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What happens when you click on Oui?
