### ISSUE TITLE
why my project on visual studio won't  run ?

### ISSUE THREAD

**Issue by nicole621** [dotnet/core#8607]

**Comment by nicole621** [comment]
my project on visual studio won't run, it is written that the issue was the ASP.NET framework, I did almost everthing possible following the instruction given, yet struggling to understand what should I do next.. as of currently I'm a student so I don't have much acknowledge and practical experience about that.. please help me with this

**Comment by mairaw** [comment]
Are you following any tutorials? What happens when you try to run the project?

**Comment by nicole621** [comment]
Yes I followed the first tutorial where I had to input codes into command
prompt, then I followed another tutorial specifically for API when using
visual studio/JavaScript.
I also check for any updates in visual studio installer, and updated my pc,
and did a Microsoft update  as well.

What should I do next?

**Comment by mairaw** [comment]
Thanks for the information so far. Can you share which tutorial are you following and what error do you get? Do you get any error messages when you try to build?
