### ISSUE TITLE
API diff markdown - alternative version without nullable changes

### ISSUE THREAD

**Issue by espenrl** [dotnet/core#8626]
I absolutely love the API diff markdowns for me to discover new API's to use as .NET evolves. There is so much goodness being added for each major .NET release. Lately it has become a lot of reading, sifting through a lot of nullable changes, and that makes it a tough read to discover new API's.

Would it be possible to generate a version of the markdowns where the nullable changes are filtered out?

**Comment by tarekgh** [comment]
What markdown files are you looking at? Can't you just look at https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8?
