### ISSUE TITLE
I did not find asp.net and web development workload instead got a option for normal web development build tools

### ISSUE THREAD

**Issue by vishweshdhoble** [dotnet/core#8627]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tarekgh** [comment]
@vishweshdhoble please provide more details about the problem you are seeing if you still have the problem.

**Comment by mairaw** [comment]
Can you share a screenshot of what you're seeing then on the Visual Studio Installer window?
