### ISSUE TITLE
dotnet test fails if solution has sqlproj and data tools missing

### ISSUE THREAD

**Issue by mac2000** [dotnet/core#8629]
in case of solution has sqlproj, attempt to run `dotnet test` fails with error:

> error MSB4019: The imported project "/usr/local/share/dotnet/sdk/7.0.201/Microsoft/VisualStudio/v11.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/7.0.201//Microsoft/VisualStudio/v11.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.

Note: this is because of lack of data tools being installed which may be a case especially in different ci like github actions

expectations are: either download and install wanted targets the same way as it is happening for dependencies or allow ignore projects with missing targets when running tests or do nothing :) 

just wanted to share because suddenly got an complain from one of engineers about broken builds and as a workaround for now, before running `dotnet test` we are executing `for file in */*.sqlproj; do dotnet sln remove "$file"; done`, may be will be helpful if someone struggling with same issue

**Comment by tarekgh** [comment]
@mac2000 thanks for your report. Could you please open this in https://github.com/dotnet/SqlClient. It can be a better place to get SQL look or redirect this.

**Comment by mairaw** [comment]
I don't have permissions but maybe someone could transfer the issue since this is in the same org. @richlander?

**Comment by tarekgh** [comment]
@mairaw I already tried to transfer it, but I couldn't find the sqlclient repo in the list that I can transfer to :-(

**Comment by mac2000** [comment]
Thank you, did cross posted it to sqlrepo

https://github.com/dotnet/SqlClient/issues/2138
