### ISSUE TITLE
starting learning some tutorial of dotnet there is an error CS8802: Only one compilation unit can have top-level statements. while running a dotnet run command in cmd!

### ISSUE THREAD

**Issue by ayushkumar5438** [dotnet/core#8631]
[Problem]([url](<img width="666" alt="Screenshot 2023-07-19 215757" src="https://github.com/dotnet/core/assets/92110394/d1958058-a295-4a4c-9718-847b775290e3">)) encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @ayushkumar5438! Most of the cases I've seen with this error is that the person ran `dotnet new` and `cd MyApp` and then ran `dotnet new` again creating two projects inside the same folder. Maybe you can try starting over or seeing if you have an extra MyApp folder inside the first one.
