### ISSUE TITLE
no me reconoce el comando dotnet

### ISSUE THREAD

**Issue by rolotuch** [dotnet/core#8632]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Hola @rolotuch - después de que terminó la instalación de .NET, te aseguraste de cerrar y volver a abrir la ventana de línea de comandos? Este paso es importante para asegurarnos de que las variables de entorno son capturadas correctamente por la ventana de línea de comandos.
