### ISSUE TITLE
'dotnet' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by thegopher4me** [dotnet/core#8638]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by thegopher4me** [comment]
windows 10.1. exact error is title.

**Comment by mairaw** [comment]
@thegopher4me did you install the SDK? And if so, did you open a new command prompt window after that?
