### ISSUE TITLE
Dotnet Program

### ISSUE THREAD

**Issue by Nicklegg329** [dotnet/core#8639]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 10, it says the program was installed but doesn't open when attempted. I ran a repair on the program and still not working, any help is appriciated.

**Comment by mairaw** [comment]
What program are you trying to run?

**Comment by Nicklegg329** [comment]
I didn't understand that i needed to run the command for dotnet in an IDE,
i figured it out. Thanks

**Comment by mairaw** [comment]
Ok, so I'll close the issue then.
