### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by Crghost4** [dotnet/core#8640]
ERROR: error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by fernandosmace** [comment]
Possibly your docker isn't running. Make sure if the Docker Service and Docker Desktop itself are running.

If that doesn't work, try changing the daemon type by running this command below in Powershell as Administrator:

`& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon`

**Comment by tarekgh** [comment]
No response for 3 weeks after @fernandosmace comments. I am closing the issue, feel free to respond back if you still have a problem.
