### ISSUE TITLE
PROBLEM IN FINDING INDEX.CSHTML

### ISSUE THREAD

**Issue by Mehfooz7** [dotnet/core#8641]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

I cant find the index file in the pages directory in my system I can only see the _Layout.cshtml.rz.scp

**Comment by wfurt** [comment]
why are you looking for `INDEX.CSHTML` @Mehfooz7 I don't see reference to it in the linked tutorial.

**Comment by mairaw** [comment]
We have removed that tutorial from the site. Please try https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro instead.
