### ISSUE TITLE
String.IndexOf does not return the correct index

### ISSUE THREAD

**Issue by MBAatEJOT** [dotnet/core#8644]
### Description

If you try to get the index of a device control character like [DC4](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#DC4) in a string, the method index of returns the wrong index.

Run the following code in a .Net (former Core) console app:

```csharp
using System;
					
public class Program
{
  public static void Main()
  {
    Console.WriteLine("35.430\u00140\u001420".IndexOf("\u0014"));
    Console.WriteLine("35.430\u00140\u001420".IndexOf("\u00140"));
  }
}
```

The expected result should be

```
6
6
```

Instead the output of those calls is

```
0
5
```

### Configuration

- **Versions**: All .Net (Core) versions from at least version 3.1 onwards.
- **OS**: At least Windows and Linux
- **Architecture**: x64

### Regression?

It works with .Net Framework 4.7.2

### Other information

To determine the affected versions of .Net I used https://dotnetfiddle.net 

here I could test also .Net Framework 4.7.2

**Comment by gfoidl** [comment]
See [Breaking changes: Globalization APIs use ICU libraries on Windows 10](https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api) and [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu).
