### ISSUE TITLE
I Have a Problem!

### ISSUE THREAD

**Issue by popandbob1** [dotnet/core#8651]
I download the .NET sdk,and I follow the steps to do.When I type the code"dotnet new console -o MyApp -f net7.0",The cmd return me"
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were _found."
I have set the PATH.Please help me.Thanks!

**Comment by mairaw** [comment]
What does `dotnet --info` return for you?
