### ISSUE TITLE
dotnet watch run doesn't allow forced restart if you pass parameters to your project.

### ISSUE THREAD

**Issue by carlsixsmith** [dotnet/core#8657]
### Description

I have a blazor server web app. If I run 

`dotnet watch run`

Then I get the expected behaviour of dotnet watch, I am able to force a re-load of the site by pressing a CTRL + R

![image](https://github.com/dotnet/core/assets/9332472/adf0279b-4074-4b00-86c2-c6b84392f6a6)

If however, I pass a parameter through then CTRL + R is missing as an option

`dotnet watch run --DatabaseSettings:UseInMemory=true` then I do not get the above message

![image](https://github.com/dotnet/core/assets/9332472/9e249b7e-ce89-4277-9e2d-e18cd599966e)

Watch still works if it detects a change in a file, but I cannot force ones via CTRL+R

### Configuration

dotnet  7.0.302
Windows 11 22H2 (OS Build 22621.1992)
x64

**Comment by ManickaP** [comment]
AFAIU, the args for your program should be separated with `--`, e.g.: `dotnet watch run -- --DatabaseSettings:UseInMemory=true`.

I've just tested this with a small local program and it worked for me.

**Comment by mairaw** [comment]
@danroth27 should this issue be moved to a different repo?
