### ISSUE TITLE
This localhost page can’t be found.... macbook 10.15.7 (19H2026). 

### ISSUE THREAD

**Issue by stanleyfk** [dotnet/core#8658]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Walked through the steps and ran the microservice and got page cannot be found. 

macbook 10.15.7 (19H2026).

**Comment by ManickaP** [comment]
Can you share the commend line output from dotnet run? Is the app still running when you access the address in the browser? Can you share the browser screen shot of the error?
