### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by stanleyfk** [dotnet/core#8659]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

[build 1/6] FROM mcr.microsoft.com/dotnet/sdk:7.0@sha256:94e91c9e8349b4caba454beb630cf05b56ee3a985e6c0c967ce57f5c58537033:
------
failed to register layer: Error processing tar file(exit status 1): write /usr/share/powershell/.store/powershell.linux.x64/7.3.5/powershell.linux.x64/7.3.5/tools/net7.0/any/System.Private.ServiceModel.dll: no space left on device

**Comment by ManickaP** [comment]
Can you try the troubleshooting from this discussion: https://forums.docker.com/t/no-space-left-on-device-error/10894
