### ISSUE TITLE
Razor Pages support ASP.Net server controls or have server controls?

### ISSUE THREAD

**Issue by ghd258** [dotnet/core#866]
The MVC programming model to his advantage, but there are also disadvantages, page data and logic processing mainly by JS control, C# is only to the front-end data transfer function, the C# instead of weakening, the enhanced JS and web; from ASPX, aspx.cs aspx.cs played this way with powerful back-end processing capabilities of C#, not only can provide data, but also can process the front interface with C# display or logical processing; hope to use the Razor Pages Cs, play the powerful function of C#

**Comment by davidfowl** [comment]
This has nothing to do with .net core. On top of that, adding the same comment to multiple issues is bad form, please avoid that.
