### ISSUE TITLE
trava o PC ao executar dotnet run

### ISSUE THREAD

**Issue by cicinato** [dotnet/core#8661]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by cicinato** [comment]
Ao entrar no Prompt de comando e pedir para executar dotnet run o pc trava, como proceder nesse caso

**Comment by mairaw** [comment]
Se você digitar `dotnet --info`, ele trava também? Senão, vc pode informar quais informações são retornadas?
