### ISSUE TITLE
This is not really a bug, need guidance on a proper dockerfile for .net 8 preview 6 aot build for linux

### ISSUE THREAD

**Issue by jdurnil** [dotnet/core#8663]
Hello,

I have created a native aot build on the windows side and have it working using the the new api project template in .net 8 preview 6. I also managed to get a native build using visual studio code in the terminal after installing dotnet 8 preview 6 and the suggested clang install in my wsl2 distribution. My next goal was to get a linux docker container built for the application but am having trouble getting my docker file right as i am using the .net8 preview 6 linux build but it of course doesnt have the clang installed to compile the native binary. Here is my docker file its a feeble attempt to get clang installed the aspnetcore image and put it in the PATH

```
FROM debian:latest AS temp
# Install clang and zlib1g-dev
RUN apt-get update && \
    apt-get install -y clang zlib1g-dev


FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview AS base

WORKDIR /app
EXPOSE 5500

ENV ASPNETCORE_URLS=http://+:5500
USER app
FROM mcr.microsoft.com/dotnet/sdk:8.0-preview AS build
COPY --from=temp /usr/lib/x86_64-linux-gnu/libclang* /usr/lib/x86_64-linux-gnu/
COPY --from=temp /usr/include/clang* /usr/include/
COPY --from=temp /usr/lib/x86_64-linux-gnu/libz* /usr/lib/x86_64-linux-gnu/
ENV PATH="/usr/lib/llvm-7/bin:${PATH}"
ARG configuration=Release
WORKDIR /src
COPY ["MyFirstAotWebApi.csproj", "./"]
RUN dotnet restore "MyFirstAotWebApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MyFirstAotWebApi.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "MyFirstAotWebApi.csproj" -c $configuration -o /app/publish /p:UseAppHost=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyFirstAotWebApi.dll"]
```

I believe the last part is also wrong as we dont need "dotnet" to run it and I dont think a dll is being produced, what should the ENTRYPOINT be and how do i get apt-get install -y clang zlib1g-dev installed on the image for the native compile?

**Comment by vitek-karas** [comment]
@richlander I think you've been looking into this scenario, right?

**Comment by richlander** [comment]
Lots of options to consider at https://github.com/dotnet/dotnet-docker/pull/4742

**Comment by jdurnil** [comment]
Hello I looked at that link am I am still not understanding what my docker file should like to make this work.Thank you,Jason DurnilOn Aug 4, 2023, at 5:27 PM, Rich Lander ***@***.***> wrote:﻿
Lots of options to consider at dotnet/dotnet-docker#4742

**Comment by richlander** [comment]
Here's an example: https://github.com/richlander/dotnet-docker/blob/dotnet-8-samples/samples/releasesapi-aot/Dockerfile.ubuntu

**Comment by jdurnil** [comment]
Is this in a working state yetFROM mcr.microsoft.com/dotnet/aot-sdk:8.0-jammy AS buildARG TARGETARCHWORKDIR /source# copy csproj and restore as distinct layersCOPY *.csproj .RUN dotnet restore -a $TARGETARCH# copy and publish app and librariesCOPY . .RUN dotnet publish -a $TARGETARCH --no-restore -o /app releasesapi.csprojRUN rm /app/*.dbg /app/*.Development.json# final stage/imageFROM mcr.microsoft.com/dotnet/aot-deps:8.0-jammy-chiseledWORKDIR /appCOPY --from=build /app .USER $APP_UIDENTRYPOINT ["./releasesapi"]Thank you,Jason DurnilOn Aug 5, 2023, at 4:58 PM, Rich Lander ***@***.***> wrote:﻿
Here's an example: https://github.com/richlander/dotnet-docker/blob/dotnet-8-samples/samples/releasesapi-aot/Dockerfile.ubuntu

**Comment by jdurnil** [comment]
Hey Rich I get this when running your example
=> ERROR [build 2/8] RUN <<EOF (apt-get update...)
                                         2.8s
------
 > [build 2/8] RUN <<EOF (apt-get update...):
0.676 E: Invalid operation update
0.698 Reading package lists...
0.738 Building dependency tree...
0.739 Reading state information...
0.740 E: Unable to locate package build-essential
0.740 E: Unable to locate package clang
0.740 E: Unable to locate package libz-dev
------

**Comment by richlander** [comment]
Do you have buildkit enabled? These samples require it.

https://docs.docker.com/build/buildkit/

**Comment by jdurnil** [comment]
hmm no i dont, ill install it

**Comment by jdurnil** [comment]
I actually i have docker desktop installed with wsl2 support, it says there is nothing more i need to do to enable buildkit

**Comment by jdurnil** [comment]
I tried 
docker buildx build .

I am still getting 
 [stage-1 1/3] FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-jammy-chiseled@sha256:833c72f664dfa4e98ee66eab93e8a67ab  0.0s
 => CACHED [stage-1 2/3] WORKDIR /app                                                                                             0.0s
 => ERROR [build 2/8] RUN <<EOF (apt-get update...)                                                                               0.4s
------
 > [build 2/8] RUN <<EOF (apt-get update...):
0.364 E: Invalid operation update
0.369 Reading package lists...
0.376 Building dependency tree...
0.376 Reading state information...
0.377 E: Unable to locate package build-essential

**Comment by richlander** [comment]
Very odd. I haven't tried that Dockerfile in WSL. Which distro (and version) were you using. I successfully built that Dockerfile in Ubuntu 22.04.

**Comment by jdurnil** [comment]
It’s Ubuntu 22.04 distro but it completely rejected that <<EOF

**Comment by jdurnil** [comment]
I wrote the file in vscode in windows with with wsl support

**Comment by jdurnil** [comment]
But everything is running like a charm now

**Comment by jdurnil** [comment]
One last thing i wanted to mention that might be of interest when creating docker files for this is in the aot project
`<InvariantGlobalization>false</InvariantGlobalization>` gets set to true automatically. Microsoft.data.sqlclient will not work with this set to true. However my container wouldnt build when i set it to false so i had to add
`RUN apt-get install libicu70`
to get it to build. Hopefully it will now all work with my sql connections. If so you guys have something amazing here,

**Comment by richlander** [comment]
We set this value to `true` by default in AOT project files.

**Comment by jdurnil** [comment]
Yes I’ve tried it with the Microsoft.data.sqlclient package and using that
package fails in at if that is set to true.

**Comment by richlander** [comment]
Yup. You can change the default.

**Comment by richlander** [comment]
This appears to be why the Dockerfile failed on your machine.

https://github.com/moby/buildkit/issues/3329#issuecomment-1385336309

**Comment by jdurnil** [comment]
Hello Richard I am really close to a solution but i need apt-get install libicu70 to be installed on mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-jammy-chiseled. Ive noticed it is a slim build and exactly what i want but of course i cant run apt-get update or apt get install on their. In my build image I am using
`FROM mcr.microsoft.com/dotnet/sdk:8.0-preview-jammy AS build
ARG TARGETARCH
RUN apt-get update
RUN apt-get install libicu70
RUN apt-get install -y build-essential clang libz-dev`

I just want to get the libicu70 install and wgatever path env variables it might need. Is there anything you could recommend.
when i use the build image as the main final image it ends up being like 843 mn insteade of 23 mb and that is not desirable.

**Comment by richlander** [comment]
Documented at https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md#ubuntu-chiseled-images

**Comment by jdurnil** [comment]
I tried this because the other one gave me errors from the beginning

`FROM golang:1.18 as chisel

RUN git clone --depth 1 -b main https://github.com/canonical/chisel /opt/chisel
WORKDIR /opt/chisel
RUN go build ./cmd/chisel


FROM mcr.microsoft.com/dotnet/sdk:8.0-preview-jammy AS build

RUN apt-get update
RUN apt-get install clang zlib1g-dev -y
COPY --from=chisel /opt/chisel/chisel /usr/bin/
RUN mkdir /rootfs \
    && chisel cut --release "ubuntu-22.04" --root /rootfs \
        libicu70_libs


WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore -r linux-arm64


# copy and publish app and libraries
COPY . .
RUN dotnet publish -r linux-arm64 --no-restore -o /app MySecondAotWebApi.csproj   
RUN rm /app/*.dbg /app/*.Development.json

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-jammy-chiseled

COPY --from=build /rootfs /
WORKDIR /app
COPY --from=build /app . 
ENTRYPOINT ["./MySecondAotWebApi"]`


I get this globalization error when trying to build the native code part
`91.40 clang : error : linker command failed with exit code 1 (use -v to see invocation) [/source/MySecondAotWebApi.csproj]
91.42 /root/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-preview.7.23375.6/build/Microsoft.NETCore.Native.targets(357,5): error MSB3073: The command ""clang" "obj/Release/net8.0/linux-arm64/native/MySecondAotWebApi.o

" -o "bin/Release/net8.0/linux-arm64/native/MySecondAotWebApi" -fuse-ld=bfd /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/8.0.0-preview.7.23375.6/sdk/libbootstrapper.o /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/8`

**Comment by jdurnil** [comment]
figured out my issue, for some reason i had labeled the linux builds asr arm64 instead of amd064 since with this script the #TARGETARCH variable was not coming through it builds now

**Comment by richlander** [comment]
Cool. The chisel pieces should all be in the chisel stage.

**Comment by tarekgh** [comment]
Is there anything pending here or can we close this issue?

**Comment by richlander** [comment]
If this continues to be a problem, please raise the issues in dotnet/docker (assuming they are container related).
