### ISSUE TITLE
NuGet UnauthorizedAccessException on macos

### ISSUE THREAD

**Issue by mbaeum** [dotnet/core#8665]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos
OS Version 13.3.1 

When running `dotnet new blazorserver -o BlazorApp --no-https -f net7.0` I get "System.UnauthorizedAccessException: Access to the path '/Users/{myusername}/.local/share/NuGet' is denied.". Problem seems to be with nuget, same error on `dotnet nuget --help`. 

I checked, the path does not exist on my machine.

**Comment by ManickaP** [comment]
I assume that it's the last part of the path that doesn't exists, i.e. directory NuGet in .local/share. Am I right?
What about creating console project and doing `dotnet restore` on it?

**Comment by mbaeum** [comment]
@ManickaP indeed, no NuGet folder in that location. I cannot run any dotnet commands in general without encountering this error. (except for --version)

**Comment by ManickaP** [comment]
Which way did you install dotnet? https://learn.microsoft.com/en-us/dotnet/core/install/macos
Are you on x64 or arm? What version of dotnet, 7.0?
