### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by peppahannah** [dotnet/core#8667]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ManickaP** [comment]
Did you install dotnet? https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70

Have you restarted the terminal window after that?
