### ISSUE TITLE
Startup.cs file missing

### ISSUE THREAD

**Issue by DiabaGodwin** [dotnet/core#8671]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

I cannot find the startup.cs file in my project directory and i wanted to ask if has been removed from the .NET 6

**Comment by ManickaP** [comment]
It's been replaced with minimal hosting model, more info here: https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-7.0&tabs=visual-studio#new-hosting-model
You can still use the old, more verbose model.

I consider this as answered. Feel free to re-open if you have more questions.
