### ISSUE TITLE
.NET Not Installing

### ISSUE THREAD

**Issue by TheFirstMember** [dotnet/core#8679]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I just bought the new Baldurs Gate 3 on Steam which prompted me to install .NET before playing, but after attempting to install I get the error code "0x80070643 - Fatal error during installation". I am pretty technologically illiterate so sorry if some information is missing. Any help would be appreciated!
GPU - AMD Radeon RX 6600 XT
Processors - AMD Ryzen 7 5800 8-Core Processor

**Comment by ManickaP** [comment]
Try to install manually: https://dotnet.microsoft.com/en-us/download
Please make sure you're downloading the right version. Hope this helps.

If you have any further problems with the game, you should contact the game developers.

**Comment by mairaw** [comment]
@TheFirstMember are there any logs that are produced? Please share it with us if you have those.
