### ISSUE TITLE
Starting out with .NET

### ISSUE THREAD

**Issue by LucaDiBattistaMTL** [dotnet/core#8680]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am a beginner with webapp dev so this is very new to me and I wouldnt know if ive made a mistake.
All steps prior to this page have been successful, but these are the problems encountered at this stage. 

(base) lucadibattista@Lucas-MacBook-Pro ~ % cd MyWebApp
cd: no such file or directory: MyWebApp

(base) lucadibattista@Lucas-MacBook-Pro ~ % dotnet watch
dotnet watch ❌ Could not find a MSBuild project file in '/Users/lucadibattista'. Specify which project to use with the --project option.

These are the results of the prior steps if necessary :
(base) lucadibattista@Lucas-MacBook-Pro ~ % dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
(base) lucadibattista@Lucas-MacBook-Pro ~ % dotnet new webapp -o --no-https -f net7.0

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.400

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.

Processing post-creation actions...
Restoring /Users/lucadibattista/--no-https/--no-https.csproj:
  Determining projects to restore...
  Restored /Users/lucadibattista/--no-https/--no-https.csproj (in 31 ms).
Restore succeeded.

**Comment by tarekgh** [comment]
Ensure the step `dotnet new webapp -o MyWebApp --no-https -f net7.0` is executed and successful and created a folder named `MyWebApp`. Additionally, you want to execute this command from a folder which you have a write access on it.
