### ISSUE TITLE
C# does not work

### ISSUE THREAD

**Issue by Ewan-Reveille** [dotnet/core#8683]
Hello, I have a problem with the use of c#. I tried to download it, but every time I use it, I have an error message :
PS C:\myApp> Console.WriteLine("Hello, World!");
Console.WriteLine : Le terme «Console.WriteLine» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable.
Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ Console.WriteLine("Hello, World!");
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Console.WriteLine:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
Thank you for your help

**Comment by mairaw** [comment]
Are you trying to follow a tutorial online?

Console.WriteLine("Hello, World!"); is something that would show up in the code, so you shouldn't type that in the command line.

**Comment by Ewan-Reveille** [comment]
I tried to follow a tutorial online, but I found the issue, the installation wasn't totally successful, and some files weren't downloaded. Thank you for your help.

**Comment by mairaw** [comment]
Sounds good. Let us know if run into any other issues.
