### ISSUE TITLE
Your connection isn't private and I can't see the page at https://localhost?

### ISSUE THREAD

**Issue by hamoor** [dotnet/core#8684]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by ManickaP** [comment]
Did it prompt you to trust the certificate? 
> The first time you run a web app in Visual Studio, it will set up a development certificate for hosting the app over HTTPS and then prompt you to trust the certificate. We recommend agreeing to trust the certificate. The certificate will only be used for local development, and without it most browsers will complain about the security of the website.

Did you confirm it?

**Comment by hamoor** [comment]
Yes now it is working ,but it needed maybe half an hour to work by its self 
Thanks
