### ISSUE TITLE
downloading .NET Core 3.1 Runtime (v3.1.32) - Windows x64

### ISSUE THREAD

**Issue by ShivaniY4W** [dotnet/core#8687]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tarekgh** [comment]
.NET Core 3.x is not supported anymore. The tutorial requires using .NET 7.0. Please follow the tutorial instructions.
