### ISSUE TITLE
Proposal to add Regex.IsValid(string) method

### ISSUE THREAD

**Issue by liven-maksim-infotecs** [dotnet/core#8688]
There is times where you must just validate regex string on runtime.

There are two ways to achive this now:
*  Provide and support your own parser;
* Invoke new Regex(string) - overkill.

But Regex provides this functioniality already before it can create regex-ojbect.

My proposal is to create public static method of Regex class which will validate regex string wihout Regex object creation.

**Comment by svick** [comment]
This has been previously discussed at https://github.com/dotnet/runtime/issues/13942.

**Comment by tarekgh** [comment]
Yes, I am closing this issue. @liven-maksim-infotecs if you still want to discuss it more, please try to follow the [instructions](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md) to propose a new API.
