### ISSUE TITLE
<NoWarn>NU1701</NoWarn> ignored on project reference

### ISSUE THREAD

**Issue by mafalarz** [dotnet/core#869]
<NoWarn>NU1701</NoWarn> ignored on project reference

Despite adding the` <NoWarn>NU1701</NoWarn>` on all my project reference like this:
```
<ProjectReference Include="..\Reports\Reports.csproj">
   <NoWarn>NU1701</NoWarn>
</ProjectReference>
```
I still get the warning message 

> NU1701: Package 'Teradata.Net.Data.Provider 15.11.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Also on publishing Nugget and adding <`NoWarn>NU1701</NoWarn` to my nugget package:

```
> <PackageReference Include="Carbon.ClientQueries" Version="0.0.1.16-Preview">
>       <NoWarn>NU1701</NoWarn>
> </PackageReference>
```
I keep getting warning: 

> NU1701: Package 'Teradata.Net.Data.Provider 15.11.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. 

I think this is because my nugget has a reference to a project reference of my solution like this:
![image](https://user-images.githubusercontent.com/30442378/29490081-a77ebd2c-84ff-11e7-8c6c-e2514d4e2b71.png)

**Comment by Petermarcu** [comment]
closing because I moved it to https://github.com/NuGet/Home/issues/5999
