### ISSUE TITLE
Compilation Error after creating Balor App from Template

### ISSUE THREAD

**Issue by mesteves** [dotnet/core#8692]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

After creating the App via VS, and trying to launch the application gives we a compilation error

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4036	The "FormatLocalizedString" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64" directory.	BlazorApp-SK	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\TypeScript\Microsoft.TypeScript.targets	69	

Thanks for any help.

Best regards,
Manuel

**Comment by wfurt** [comment]
It seems like this was fixed https://stackoverflow.com/questions/76456584/msb4036-the-formatlocalizedstring-task-was-not-found

You will probably need to upgrade your tools @mesteves Let me know if that works
