### ISSUE TITLE
Não sei o que aconteceu, acho que tem que mudar um termo, mas por que? (Sou iniciante😅)

### ISSUE THREAD

**Issue by Millycr123** [dotnet/core#8694]
O Windows PowerShell
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Instale o PowerShell mais recente para obter novos recursos e aprimoramentos! https://aka.ms/PSWindows

PS C:\Users\tilocal> dotnet new console -o MyApp -f net7.0
A criação deste modelo fará alterações nos arquivos existentes:
  Sobrescrever   MyApp\MyApp.csproj
  Sobrescrever   MyApp\Program.cs

Para criar o modelo mesmo assim, execute o comando com a opção “--force”:
   dotnet new console -o MyApp -f net7.0 --force

**Comment by tarekgh** [comment]
This is unclear what the question is. Please try to add more information what exactly you are asking for.

**Comment by mairaw** [comment]
@Millycr123 você provavelmente executou o comando duas vezes no mesmo diretório, então está te perguntando se você quer substituir os arquivos já existentes.

Cheque se o diretório MyApp já não foi criado.

Isso te ajuda?
