### ISSUE TITLE
.NET Installation

### ISSUE THREAD

**Issue by HaouasAzza** [dotnet/core#8695]
When I try to run this command dotnet new console -o MyApp -f net7.0
It says " It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download "
How do I solve this please?

**Comment by fernandosmace** [comment]
> When I try to run this command dotnet new console -o MyApp -f net7.0 It says " It was not possible to find any installed .NET Core SDKs Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from: https://aka.ms/dotnet-download " How do I solve this please?

To start developing with .NET you need to have the SDK (Software Development Kit) installed in you operational system.

So, first make sure you have .NET 7.0 installed using the following command on the terminal: `dotnet --list-sdks`

If dotnet 7.0 isn't in the returned list of the command, then download it from Microsoft and install. After that, you can run again the command to create your application.

You can download here all versions of .NET for you operational system: https://dotnet.microsoft.com/pt-br/download
