### ISSUE TITLE
Dotnet command nto working

### ISSUE THREAD

**Issue by TGRyeet** [dotnet/core#8699]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: macos

When I tried the installation process , a 'zsh: command not found: dotnet error' kept popping up

**Comment by mairaw** [comment]
Which version is your Mac and version of the SDK have you installed @TGRyeet?

**Comment by TGRyeet** [comment]
Mac version: ventura 13.4.1
SDK: dotnet-sdk-7.0.400-osx-x64.pkg
