### ISSUE TITLE
Native AOT - Microsoft.Data.SQLite crashing

### ISSUE THREAD

**Issue by JOULTICOA** [dotnet/core#8704]
Hello

I see this issue here, not sure if related  https://github.com/dotnet/efcore/issues/29725

I am using Visual Studio 2022 LTSC 17.4.4, targeting net7.0-windows

I ran "dotnet add package Microsoft.Data.Sqlite.Core --version 8.0.0-preview.7.23375.4"  to install the package.  perhaps this is a bad version to use in my situation?

I have a simple c# app that uses Microsoft.Data.SQLite, the SqliteConnection and SqliteCommand methods

It works 100% fine when built without AOT.  

However when I publish it as AOT, I get an exception / crash.  Exception code: 0x4b1b53b5  which seems meaningless on first glance

Is there some way to get more information about the crash or solve this issue?

Thank you

**Comment by roji** [comment]
Closing as this belongs in https://github.com/dotnet/efcore.
