### ISSUE TITLE
求助！关于C++如何调用.net6.0 dll的问题，Help，an issue about how to invoke .net6.0 dll in C++11

### ISSUE THREAD

**Issue by tobecomehuman** [dotnet/core#8705]
我试图写一个C++程序来调用.net6.0所生成的dll文件，但是通过Hinstance类型可以访问文件但是却没有办法找到具体的函数，显示无法访问内存，正如下方所示.
我之前已经尝试了Clr公共语言运行时但遇到了：C++/CLI 或 C++/CX 不支持两阶段名称查找；请使用 /Zc:twoPhase- test2
另外也尝试了了直接使用#using namespace NativeLibrary的方法但此方法仅支持.net framework 4.8生成的dll文件
不知道该怎么办了，可以帮一帮我吗，有没有天才提供其他的更棒的方法

I am trying to write a program to invoke a dll file generated by .net6.0 CSharp，I have used Hinstance Class to visit dll file，but it cant locat the function I need，it views that I cant visit the storage.
I have already tried to turn on the Clr Mode but it turns out C++/CLI or C++/CX doesn't support the Two-stage name lookup ; please use /Zc:twoPhase- test2（ yes i did but its still not work’）.
I also have tried to direct use the namespace , but it only support the dll generated by .net framework 4.8.
I don't know what to do ,please please help.  Teach me some better method. 

This is the Code:
<CSharp>
```
`
using System;
using System.Runtime.InteropServices;

namespace NativeLibrary
{
	public class Class1
	{
		[UnmanagedCallersOnly(EntryPoint = "add")]
		public static int Add(int a, int b)
		{
			return a + b;
		}
	}
}
`
```

C++的代码如下<C++>
```
`#include <iostream>
#include<stdlib.h>
#include<Windows.h>

using namespace std;
int main()
{
	int a = 100;
	int b = 50;
	printf("a=%d  b=%d\n", a, b);


	HMODULE handle = LoadLibraryA("NativeLibrary.dll");
	if (handle != NULL)
	{
		//为add声明函数指针Add
		typedef int (*Add)(int, int);


		Add sum = (Add)GetProcAddress(handle, "add");
		printf("sum=%d\n", sum(a, b));

		CloseHandle(handle);
	}

	system("pause");

	return 0;
}`
```

this is the  exception message
0x00000000 处(位于 test2.exe 中)引发的异常: 0xC0000005: 执行位置 0x00000000 时发生访问冲突。
Exception thrown at 0x00000000 (in test2.exe): 0xC0000005: An access conflict occurred at execution location 0x00000000.

**Comment by tarekgh** [comment]
@jeffschwMSFT @agocke @jkotas do you know any contact in C++ team who may help with this issue?

**Comment by jeffschwMSFT** [comment]
@tgani-msft

**Comment by Akarinnnnn** [comment]
`UnmanagedCallersOnly`不是这么用的把，毕竟它又不会在EAT里导出函数，只是说明这个托管函数可以直接通过反射拿到函数指针而已

Seems like `GetProcAddress` can't find function "add". `UnmanagedCallersOnlyAttribute` don't generate a native function export item which `GetProcAddress` recognizes. By the way generate export Items in EAT for `UnamnagedCallersOnly` funcitons can be a feature though.

**Comment by jkotas** [comment]
Correct, regular managed .dll won't have any unmanaged exports.

You have to either use https://github.com/AaronRobinsonMSFT/DNNE package or publish the library with AOT (https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary is a sample that shows how to do that).

**Comment by tobecomehuman** [comment]
好的非常感谢大家，我试着研究一下
OK，many thankes，Im trying to work on it
