### ISSUE TITLE
.NET Core 2.0 Kestrel Garbage Collection Concern

### ISSUE THREAD

**Issue by antonellil** [dotnet/core#871]
All,

I am using .NET Core 2.0 in a Docker container via the microsoft/dotnet:2.0-sdk image on a Digital Ocean droplet running Docker 1.12.3 on Ubuntu 16.04, with 2GB of RAM and 2 CPUs.

Below is the memory timeline I am seeing from the past 6 hours, with around 120 users accessing the site in those 6 hours.
![image](https://user-images.githubusercontent.com/978968/29497915-2df18cf8-85bf-11e7-9aec-d0d0d37ebe5e.png)

Below are the relevant portions of my .csproj and Program.cs files.

.csproj
![image](https://user-images.githubusercontent.com/978968/29497955-45ab252e-85c0-11e7-98a8-fe592c872d0e.png)

Program.cs
![image](https://user-images.githubusercontent.com/978968/29497953-3dc61be8-85c0-11e7-85f6-17c0eb74e2c4.png)

I am using standard 2.0 Kestrel as provided in the CreateDefaultBuilder.

Any help would be extremely appreciated so I do not have to manually restart the docker image on server to reset the memory. I am aware that there is a Server Garbage Collection key that can be added to the csproj, but unsure if that could be the solution.

Thank you!

**Comment by antonellil** [comment]
Update: 
![image](https://user-images.githubusercontent.com/978968/29502399-c4182e1a-85fd-11e7-88d1-9fa376dc726c.png)

Seems to have leveled off and is GC'ing correctly. But still very interesting behavior that would be good to get to the bottom of

**Comment by antonellil** [comment]
And.... it seems to have begun rising yet again. Definitely concerning.

![image](https://user-images.githubusercontent.com/978968/29507655-120e16a4-861f-11e7-9d49-07e67e4b5eb4.png)

**Comment by halter73** [comment]
@antonellil In case you're not seeing the back references, I want to point out that this might be caused by an issue reading cgroup limits described in dotnet/coreclr#13489

**Comment by antonellil** [comment]
@halter73 great find, yes this seems to be related
