### ISSUE TITLE
what is a 'new' command window as opposed to the normal one I use everyday? how to get the empty prompt?

### ISSUE THREAD

**Issue by dmstevenson** [dotnet/core#8712]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
if you had any open command prompt windows during the installation, they won't recognize the `dotnet` command. You need to just open a new one like you always do, so the changes that happened during the installation can be applied to a new window.

Does that help?

**Comment by dmstevenson** [comment]
Yes, thanks!

Dave Stevenson

**Comment by mairaw** [comment]
Closing the issue then. Let us know if you have additional questions.
