### ISSUE TITLE
Error running blazor tutorial

### ISSUE THREAD

**Issue by rmelancon1** [dotnet/core#8715]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)

Stack Query Cookies Headers Routing
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

Show raw exception details

**Comment by mairaw** [comment]
Have you made any changes to the default template?

Adding @danroth27 to see if he can help here.

**Comment by rmelancon1** [comment]
No, just followed steps and clicked Run.

From: Maira Wenzel ***@***.***>
Sent: Friday, August 25, 2023 10:12 PM
To: dotnet/core ***@***.***>
Cc: Robert Melancon ***@***.***>; Author ***@***.***>
Subject: [External] Re: [dotnet/core] Error running blazor tutorial (Issue #8715)


Have you made any changes to the default template?

Adding @danroth27<https://github.com/danroth27> to see if he can help here.

-

**Comment by danroth27** [comment]
The error suggests that the *Pages/_Host.cshtml* page is missing from the project or is missing the `@page` directive in the file. Could you please check that the *Pages/_Host.cshtml* file is present? This file should be present when a new Blazor Server project is created.

Also, could you please share with us what version of .NET you have installed? You can check this by running `dotnet --version` from a command prompt.
