### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### ISSUE THREAD

**Issue by ChessedBoard** [dotnet/core#8716]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

im not sure what to do but i think this is the error code? 0x80070652 im just really stupid and dont know what to do

**Comment by mairaw** [comment]
I'm sorry to hear you're having problems. Can you let us know what you're trying to do? Are you trying to learn how to code or fix a problem on your computer?

Maybe try searching for a solution on Google. It seems this error code is for Windows Updates issues.
