### ISSUE TITLE
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by CasualCobra** [dotnet/core#8717]
I ran into an issue when tyring to run "dotnet new console" command in vs code 1.81.1 and I have .Net 7
(This is my first encounter with C# and I was watching a Brackeys Youtube tutorial
"https://www.youtube.com/watch?v=N775KsWQVkw&list=PLPV2KyIb3jR4CtEelGPsmPzlvP7ISPYzR&ab_channel=Brackeys")

### System Details:
Windows 10 Pro 22H2, 64bit os

![image](https://github.com/dotnet/core/assets/143222472/940db673-eaa8-465c-a58f-bcf6f1c56dbf)

Thanks in advance for your help.

**Comment by mairaw** [comment]
Sorry to hear you're having issues. Do you run into the same issue if you run this same command on a regular command prompt window? Just trying to isolate if it's a VS Code issue or a machine-wide issue.

And what does `dotnet --info` returns?

Thanks!

**Comment by CasualCobra** [comment]
In command promt I did not run into the same error, instead it gave me this.
![image](https://github.com/dotnet/core/assets/143222472/3343c141-2c24-4e39-96f3-b07e6916aa98)

And dotnet --info gives me
![image](https://github.com/dotnet/core/assets/143222472/2debdb2e-70ec-4cda-89cc-3fdf9371a61d)

**Comment by CasualCobra** [comment]
Sorry to be inpatient, but is anyone able to get back to me?

**Comment by CasualCobra** [comment]
Dont worry It fixed its self!
Thanks for your effort!
