### ISSUE TITLE
nao esta instalando 

### ISSUE THREAD

**Issue by gui386** [dotnet/core#8719]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create
Operating System: windows
![image](https://github.com/dotnet/core/assets/129689418/1c78d8c8-2436-4ecc-9c58-aab58a158118)
![Captura de Tela (1)](https://github.com/dotnet/core/assets/129689418/0a4e1f2a-2fc4-440e-a6c5-8d4bf77bade2)
![prompt  error](https://github.com/dotnet/core/assets/129689418/568470d5-ff09-469a-b654-69b088fa5fa5)

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by eduardobragaxz** [comment]
Você instalou alguma versão do .NET no pc antes de tentar o comando?
