### ISSUE TITLE
dotnet run for Core 2.0 crashes on Mac crashes (System.IO.FileSystem conflict)

### ISSUE THREAD

**Issue by stanuku** [dotnet/core#872]
Steps: 

- Installed .NET Core 2.0 SDK for MAC. (MacBook Pro 2017)
- dotnet --version outputs 2.0.0
- Created new mvc app using `dotnet new mvc -o sample20`
- cd sample20
- dotnet build successful
- dotnet run CRASHES!

```
Unhandled Exception: System.IO.FileLoadException: 
Could not load file or assembly 'System.IO.FileSystem, 
Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 
The located assembly's manifest definition does not match the assembly reference.
 (Exception from HRESULT: 0x80131040)
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at Sample20.Program.BuildWebHost(String[] args)
   at Sample20.Program.Main(String[] args)
```

**Comment by wfurt** [comment]
Are you sure you have all prerequisites and no older dotnet versions lingering around? 
Also what is you OS version. You did not provide any details about that.

**Comment by NETESudarshan** [comment]
@wfurt: 

> no older dotnet versions lingering around?

Isn't side by side the whole point? I've 1.1 lingering around on my Mac.

> Also what is you OS version. You did not provide any details about that.

MacBook Pro 2017 comes with latest OS. (Sierra)

**Comment by stanuku** [comment]
@wfurt: 

> no older dotnet versions lingering around?

Isn't side by side the whole point? I've 1.1 lingering around on my Mac.

> Also what is you OS version. You did not provide any details about that.

MacBook Pro 2017 comes with latest OS. (Sierra)

**Comment by wfurt** [comment]
It is possible to have both, one just needs to be careful not to mix them. 
I repeated your steps on 10.12.5 and I don't see any crash. 
I assume you used the pkg installer in both cases, right? 

You can run:
dotnet build  -v d| grep System.IO.FileSystem

That will produce more verbod=se output and it would show you where the System.IO.FileSystem is coming from. 


You can also try to publish standalone app and see if that makes any difference. 

dotnet publish  -r osx.10.12-x64
./bin/Debug/netcoreapp2.0/osx.10.12-x64/sample20

**Comment by stanuku** [comment]
@wfurt Thank you, I'll try and let you know soon.

**Comment by stanuku** [comment]
@wfurt This the output

```$ dotnet build -v d| grep System.IO.FileSystem
Encountered conflict between 
'Reference:/Users/sudarshan/.nuget/packages/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.FileSystem.dll' 
and 'Reference:/Users/sudarshan/.nuget/packages/system.io.filesystem/4.3.0/ref/netstandard1.3/System.IO.FileSystem.dll'.  
Choosing 'Reference:/Users/sudarshan/.nuget/packages/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.FileSystem.dll' 
because AssemblyVersion '4.1.0.0' is greater than '4.0.1.0'.
```

**Comment by stanuku** [comment]
Ok, I deleted the /Users/myusername/.nuget/NuGet folder and /Users/myusername/.nuget/packages folder and recreated empty ones by the same names. This seemed to fix the 'dotnet run' crash.

**Comment by wfurt** [comment]
good to know. I don't know why the .nuget would get polluted with incompatible version but at least you have some path to 2.0 now. You do not need to recreate the directories. "dotnet restore" should take care of all dependencies for your project.
