### ISSUE TITLE
onserverclick when I click means it's showing error i  don't know why

### ISSUE THREAD

**Issue by ain-pradeep-kumar** [dotnet/core#8721]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
Sorry @ain-pradeep-kumar it is not clear what step you were and what issue you have got, this issue is not actionable without more info.
