### ISSUE TITLE
VSDBG 17.2 and above no longer working on ARM32 system

### ISSUE THREAD

**Issue by jbatt33** [dotnet/core#8722]
When attempting to attach to a remote process on an ARM32 system, the remote debugging process will throw the following error: 
(output from strace)
[pid 10408] write(2, "FATAL ERROR: Failed to initialize dispatcher with error 8ede002b\n", 65) = 65

Running the application via VALGRIND I only see the following error: 
Can't make sense of .ARM.exidx section mapping

I'm not too sure what the issue is, but I suspect a compile of the corelib is not proper in this release. 

If I revert the debugger (force downgrade by copying the old version on top, but leaving the success text file) 

The debugger is working as expected. 

Also, from valgrind, we can read the EXIDX section as expected.
--13070-- Reading syms from /ftp/.vs-debugger/vs2022/libcoreclr.so
--13070--    object doesn't have a symbol table
--13070--   Reading EXIDX entries: 13055 available

This is with .NET  6.0.20 Linux ARM32

The version of the debugger that tested working is [17.0.10712.2](https://vsdebugger.azureedge.net/vsdbg-17-0-10712-2/vsdbg-linux-arm.zip), but it is possible some other versions are working, but I don't know all the releases.

The version that is NOT working is https://vsdebugger.azureedge.net/vsdbg-17-7-10808-2/vsdbg-linux-arm.tar.gz

**Comment by buyaa-n** [comment]
@jbatt33 this is unrelated to .NET Core, please open an issue in VS Dev Community: https://developercommunity.visualstudio.com/content/problem/post.html
