### ISSUE TITLE
Message after changing application name: "the service microsoft.visualstudio.OLE.Interop.IOleUndoManager must be installed"

### ISSUE THREAD

**Issue by WWWEdobrimCOM** [dotnet/core#8725]
### Description

Hi everyone. I have a visual basic net program/project made with netcore 8 (latest preview).
Basically I wanted to **change the name of the application** to the project by right clicking on properties. Since I changed the name of the project (i.e. the application I'm creating) I get **a strange message** on Visual Studio, "the service microsoft.visualstudio.OLE.Interop.IOleUndoManager must be installed. Ensure that this service is aviable".
Naturally, I changed the name of both the application (in the right-hand menu of Visual Studio) and the solution (always in the right-hand menu, above the application name). They are equal
To be safe, I also checked the "property group" and everything is ok.
In the end **I just changed the name of the program, that's all.**

The madness of Visual Studio. It was giving errors on another PC as well. 
**There is no time they make a light and clean stuff, mysteries.**

Sometimes after a while, not always, I get this **another message**: "**The connection to the server has been lost**". 

O_o 

### Configuration

Visual Studio free version
Netcore 8 Preview
Visual basic .net
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz
Windows 10 Home
22H2

### Other information

Mysteries of Visual Studio Vb net

**Comment by buyaa-n** [comment]
Hello @WWWEdobrimCOM, this is not .NET Core issue, so closing, please ask your question in [Visual Studio Dev Community](https://developercommunity.visualstudio.com/content/problem/post.html?space=8)


Also, I could not repro the issue, I renamed a project name and solution name without any issue/warning. If you could attach a sample app that reproes this issue would be helpful for investigation.
