### ISSUE TITLE
Visual studio vb net, all gray toolbox

### ISSUE THREAD

**Issue by Slotxa** [dotnet/core#8727]
I'm working on a project on Visual Studio with visual basic vb net language, I build in netcore 8. Basically the bar on the left, where you can add buttons and other things, has become all grey, as if it were disabled. It had happened before, just close and reopen, but now it always remains gray. How come this strange stuff happens?

### Configuration

Windows 10

**Comment by buyaa-n** [comment]
Hi @Slotxa, I could not really tell what is happening with the provided info, please attach a sample app that reproes the issue

**Comment by Slotxa** [comment]
Basically it was a problem I had always had but I solved it by restarting visual studio or the pc. 
But now I managed to solve it **by pressing left on "Reset toolbox"**. By pressing this button the toolbox reappeared normal, i.e. I can put new label buttons etc...

Thank you
