### ISSUE TITLE
can't  refresh the page, there is no use to press the botton of refresh

### ISSUE THREAD

**Issue by jaydenwzx** [dotnet/core#8729]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
Hello @jaydenwzx, it doesn't say you need to refresh the page, the browser refreshes automatically and you would see the update
 
`Once this change is saved, the dotnet watch command will apply the change to the running app and refresh it in the browser, so you can see the change in the running app.`
