### ISSUE TITLE
BlazorApp.csproj is not exist

### ISSUE THREAD

**Issue by thisismhanifi** [dotnet/core#8730]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

BlazorApp.csproj is not exist in the files listed

**Comment by buyaa-n** [comment]
Hello @thisismhanifi, I think you see the `BlazorApp` without the `.csproj` extension, if that is the case that is expected, the project file extension is not displayed in Visual Studio

**Comment by thisismhanifi** [comment]
Hello @buyaa-n thanks for answering 

yes , the main problem is this one . 
in tutorial of visual studio mode , this subject is written.
changing this subject is can be helpful.
because this subject is in visual studio mode is described .

**Comment by buyaa-n** [comment]
I assume it is by design, tag @mairaw for proper answer

**Comment by mairaw** [comment]
Can you share a screenshot @thisismhanifi?

This is what you should be seeing in VS. The csproj extension is not really shown but this is a VS behavior as it displays different icons for project files.
![image](https://github.com/dotnet/core/assets/12971179/a242db51-2d59-4aab-bafd-6a4b07863674)

**Comment by thisismhanifi** [comment]
Hello @mairaw

thanks for answering 

The mentioned files are also displayed in VS for me

But my argument was that in the written tutorial, this file is inside the VS files.

But according to what you said, this file is not displayed in Solution Explorer.

Because this case can mislead students, that's why I informed you

Thanks
