### ISSUE TITLE
Failed to download or parse releases-index.json

### ISSUE THREAD

**Issue by jytesh8** [dotnet/core#8731]
Azure pipeline failing on the error Failed to download or parse releases-index.json with error: {"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"dotnetcli.blob.core.windows.net"} 

### Configuration

Self Hosted Windows Machine

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '6.0.x'
    includePreviewVersions: true

### Regression?

Tried with version 5.0.x as well

### Other information

##[debug]Agent.ClientCert=undefined
##[debug]check path : C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]adding resource file: C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]system.culture=en-US
##[debug]Setting resource path to C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\task.json
##[debug]check path : C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\task.json
##[debug]adding resource file: C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\task.json
##[debug]system.culture=en-US
##[debug]check path : C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\node_modules\azure-pipelines-tasks-packaging-common\module.json
##[debug]adding resource file: C:\agent11\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.228.0\node_modules\azure-pipelines-tasks-packaging-common\module.json
##[debug]system.culture=en-US
##[debug]useGlobalJson=false
##[debug]packageType=sdk
##[debug]version=6.0.x
##[debug]vsVersion=undefined
##[debug]nugetVersion=undefined
##[debug]installationPath=C:\agent11\_work\_tool/dotnet
##[debug]performMultiLevelLookup=false
##[debug]includePreviewVersions=true
##[debug]workingDirectory=C:\agent11\_work\3\s
##[debug]agent.proxyurl=undefined
##[debug]AZURE_HTTP_USER_AGENT=VSTS_51b2b744-76ef-46d0-bc1f-ed84fcd51db4_build_743_0
Tool to install: .NET Core sdk version 6.0.x.
##[debug]task result: Failed
##[error]Failed to download or parse releases-index.json with error: {"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"dotnetcli.blob.core.windows.net"}
##[debug]Processed: ##vso[task.issue type=error;]Failed to download or parse releases-index.json with error: {"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"dotnetcli.blob.core.windows.net"}
##[debug]Processed: ##vso[task.complete result=Failed;]Failed to download or parse releases-index.json with error: {"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"dotnetcli.blob.core.windows.net"}
Finishing: UseDotNet

**Comment by buyaa-n** [comment]
Hello @jytesh8, sorry I do not understand what you were doing and what/how this log is produced, in order to triage your issue and direct it to the appropriate engineering team for further evaluation we need more info

**Comment by jytesh8** [comment]
the log is produced by setting system.debug = true on the Azure Devops pipelines. looks like dotnetcli.blob.core.windows.net was down at the time i created this issue. Its back again and now pipelines are working. Closing this issue
