### ISSUE TITLE
facing an issue in .NET while compiling 

### ISSUE THREAD

**Issue by priyagunali** [dotnet/core#8736]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 
i am getting a error like this: Only one compilation unit can have top-level statements. [C:\Users\
priya\MyApp\MyApp.csproj]
<img width="835" alt="image" src="https://github.com/dotnet/core/assets/117383833/efd23ba3-13fa-47a4-9454-96fd0d04b3f4">

**Comment by buyaa-n** [comment]
It sounds like you modified your program incorrectly, something like added another *.cs file or added incorrect row that cause the issue, without seeing the code/file you added could not tell exactly, please let us know what you added/updated before running the app

**Comment by mairaw** [comment]
That typically happens when you run the `dotnet new` command twice in different folders. Maybe try starting over?
