### ISSUE TITLE
 error CS8802: Only one compilation unit can have top-level statements. [C:\Users\aaa\MyApp\MyApp.csproj]  The build failed. Fix the build errors and run again.

### ISSUE THREAD

**Issue by durgambigai** [dotnet/core#8738]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
> error CS8802: Only one compilation unit can have top-level statements. [C:\Users\aaa\MyApp\MyApp.csproj] The build failed. Fix the build errors and run again.

That typically happens when you run the dotnet new command twice in different folders. Maybe try starting over?
