### ISSUE TITLE
zsh: command not found: dotnet

### ISSUE THREAD

**Issue by rambhupalreddy369** [dotnet/core#8740]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

<img width="1470" alt="Screenshot 2023-09-06 at 10 33 07 AM" src="https://github.com/dotnet/core/assets/62335908/7b8729df-6c5b-4f59-bd63-29f6f5321620">

**Comment by buyaa-n** [comment]
Hi @rambhupalreddy369, in the tutorial it says: `If you receive a zsh: command not found: dotnet error, make sure you opened a new terminal window.`. Have you tried that?
