### ISSUE TITLE
Running application on HTTPS   leads to error 

### ISSUE THREAD

**Issue by Muhammadyahyasoomro** [dotnet/core#8742]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
@Muhammadyahyasoomro what error do you see? Please provide more info

**Comment by Muhammadyahyasoomro** [comment]
I Solved the problem Sir Thanks For your Support
