### ISSUE TITLE
Help for dotnet sdka create new project

### ISSUE THREAD

**Issue by Yuri-Tokio** [dotnet/core#8744]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

This img show the problem
![image](https://github.com/dotnet/core/assets/66705619/7f1a14e7-4019-4fa5-a47b-1141fb4f7da6)

This img show the sdks instaled
![image](https://github.com/dotnet/core/assets/66705619/e801b3a0-5ef7-4720-be2f-c161f0b3f8e5)

**Comment by mairaw** [comment]
Oi @Yuri-Tokio! Can you share what `dotnet --info` and `where.exe dotnet` returns?
