### ISSUE TITLE
Release date documentation inconsistency

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/core#8746]
Hi .NET Team,

I noticed that the available release date information is not completely consistent for .NET 6 and already announced for .NET 8.

For .NET 6, there's two different release dates, either Nov 8th, 2021 or Nov. 9th, 2021. The Nov. 9th date matches the observed cadance of releasing the RTM bits of .NET on the second Tuesday in November.

Nov 8th:
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
https://devblogs.microsoft.com/dotnet/announcing-net-6/
https://github.com/dotnet/core/blob/main/releases.md

Nov 9th:
https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

Missing date:
https://github.com/dotnet/core/blob/main/README.md

And for .NET 8 (this year), there's already an announced release date (Nov 8th, 2023) in the https://github.com/dotnet/core/blob/main/README.md and it's a Wednesday the week before the .NET Conference.

I'm perfectly aware that the official release date isn't announced and that patterns observed in previous years are not a guarantee, it's just I'm guestimating Nov. 12th for the .NET release based on past experience and it would be grea to know if this year's Nov 8th, 2023 is just a copy&paste typo or if this is truly the planned official RTM date of .NET 8.

Many thanks, Michael

**Comment by mairaw** [comment]
Thanks for bringing this to our attention @MichaelKetting.

@rbhanda @jamshedd can you comment on this?

I believe the lifecycle doc has the wrong date for the release and it's also missing the end date for .NET 7
https://github.com/dotnet/core/releases/tag/v6.0.0

I created https://github.com/dotnet/core/pull/8747 to update the readme file. I believe we haven't announced the RTM date yet.

**Comment by YohanSciubukgian** [comment]
The pin issue on the aspnetcore repository is talking about the .NET 8 RTM date (Nov 14th):
https://github.com/dotnet/aspnetcore/issues/50091

**Comment by mairaw** [comment]
The readme changes were merged. We now need to fix the lifecycle doc.

**Comment by mairaw** [comment]
releases.md is also fixed

**Comment by MichaelKetting** [comment]
Thank you, @mairaw!

**Comment by leecow** [comment]
Closing as resolved.
