### ISSUE TITLE
The build failed error.

### ISSUE THREAD

**Issue by louriarte** [dotnet/core#8748]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Error thrown says only one compilation unit can have top-level statements. 

The build failed. Fix the build and run again. Please help!

**Comment by louriarte** [comment]
This is when I try (dotnet run)

**Comment by mairaw** [comment]
You probably ran the `dotnet new` command twice in different folders, creating one project inside the other. Maybe start over and see if that works?
