### ISSUE TITLE
.NET Core 2.0 new Razor project on Windows 8.1 build fails with error CS1646 in _ViewStart.cshtml

### ISSUE THREAD

**Issue by gregbradley** [dotnet/core#875]
After installing DotNet Core 2.0.0 on a Windows 8.1 machine and creating a new Razor project (dotnet new razor) the project fails to build. Have tried also creating the project using Visual Studio 2017 with the same result. Also tried on another Windows 8.1 machine with the same result.

Build FAILED.

Pages\_ViewStart.cshtml(1,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [D:\DP\Core20\Core20.csproj]
Pages\_ViewStart.cshtml(1,2): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20\Core20.csproj]
Pages\_ViewStart.cshtml(2,12): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20\Core20.csproj]
Pages\_ViewStart.cshtml(3,1): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20\Core20.csproj]
Pages\_ViewStart.cshtml(2,5): error CS0116: A namespace cannot directly containmembers such as fields or methods [D:\DP\Core20\Core20.csproj]
    0 Warning(s)
    5 Error(s)

**Comment by leecow** [comment]
@danroth27

**Comment by danroth27** [comment]
@Eilon @mlorbetske Can you guys take a look?

**Comment by Eilon** [comment]
@pranavkm - any idea on this? Why does the filename look weird in the MSBuild error?

@gregbradley - can you upload your app to GitHub so we can see if something got generated incorrectly by the template?

**Comment by pranavkm** [comment]
This seems like csc is trying to compile the _ViewStart.cshtml. Could you verify that you haven't accidentally included it to in the `Compile` itemgroup in your csproj?

**Comment by gregbradley** [comment]
@Eilon - I have uploaded the app to GitHub https://github.com/gregbradley/Core20Razor

@pranavkm, @Eilon - This is just a new project I created with `dotnet new razor` and then tried to build it without changing anything.

`D:\DP\Core20Razor>dotnet --version
2.0.0

D:\DP\Core20Razor>dotnet new razor
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/template-3pn for details.

Processing post-creation actions...
Running 'dotnet restore' on D:\DP\Core20Razor\Core20Razor.csproj...
  Restoring packages for D:\DP\Core20Razor\Core20Razor.csproj...
  Restoring packages for D:\DP\Core20Razor\Core20Razor.csproj...
  Restore completed in 4.99 sec for D:\DP\Core20Razor\Core20Razor.csproj.
  Generating MSBuild file D:\DP\Core20Razor\obj\Core20Razor.csproj.nuget.g.props.
  Generating MSBuild file D:\DP\Core20Razor\obj\Core20Razor.csproj.nuget.g.targets.
  Restore completed in 8.94 sec for D:\DP\Core20Razor\Core20Razor.csproj.


Restore succeeded.


D:\DP\Core20Razor>dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Pages\_ViewStart.cshtml(1,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(1,2): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(2,12): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(3,1): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(2,5): error CS0116: A namespace cannot directly contain members such as fields or methods [D:\DP\Core20Razor\Core20Razor.csproj]

Build FAILED.

Pages\_ViewStart.cshtml(1,1): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @ [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(1,2): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(2,12): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(3,1): error CS1022: Type or namespace definition, or end-of-file expected [D:\DP\Core20Razor\Core20Razor.csproj]
Pages\_ViewStart.cshtml(2,5): error CS0116: A namespace cannot directly contain members such as fields or methods [D:\DP\Core20Razor\Core20Razor.csproj]
    0 Warning(s)
    5 Error(s)

Time Elapsed 00:00:09.24`

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#6725
