### ISSUE TITLE
Hello, world!

### ISSUE THREAD

**Issue by netteshma** [dotnet/core#8752]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

When I copy code and paste to command this message comes up. When I select Paste anyway nothing happens.

![Picture1](https://github.com/dotnet/core/assets/144728188/e021eb56-f6fc-40da-bc82-00b293578d0b)

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Where are you trying to paste that @netteshma? You should be opening the file that contains the Index.cshtml file and replacing its contents. Is that what you're doing?
