### ISSUE TITLE
.NET September 2023 Update - .NET 7.0.11, .NET 6.0.22

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8758]
# .NET September 2023 Update

## Release Notes
* [7.0.11](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.11/7.0.11.md)
* [6.0.22](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.22/6.0.22.md)

## Status

Asset Type | 7.0.11 | 6.0.22 | Notes
-- | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet)  |✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) |✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows)  |✅ | ✅ 
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) |✅ | ✅ 
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap)  |✅ | ✅ 
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 8](https://learn.microsoft.com/dotnet/core/install/linux-centos) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 37](https://learn.microsoft.com/dotnet/core/install/linux-fedora)|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 38](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 39](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse) |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ | ✅ 
## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

### Known Issues

- [ ] https://github.com/dotnet/core/issues/8772 We are aware of a known issue where some .NET 6.0 and .NET 7.0 installers are unavailable on packages.microsoft.com for the release. We expect all of them to be available later in the day today (9/14/2023 5 PM PST)

**Comment by Sebazzz** [comment]
I'm not entirely clear on how to resolve this. For some of the previous .NET security updates it was sufficient to run Windows Update to update the base framework for Framework Dependent deployments. However, Windows Update is not mentioned this time. Am I correct in assuming apps need to be rebuilt and redeployed?

**Comment by cmenzi** [comment]
I cannot find the latest version 414 of the dotnet-sdk-6.0 in the ubuntu feed.

```
root@myhost:~# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://ppa.launchpad.net/ansible/ansible/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [3611 B]
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:7 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [234 kB]
Get:8 https://packages.microsoft.com/ubuntu/20.04/prod focal/main arm64 Packages [50.4 kB]
Get:9 https://packages.microsoft.com/ubuntu/20.04/prod focal/main armhf Packages [16.3 kB]
Get:10 https://packages.microsoft.com/ubuntu/20.04/prod focal/main all Packages [2586 B]
Fetched 307 kB in 1s (406 kB/s)
Reading package lists... Done
root@myhost:~# apt search dotnet-sdk-6.0
Sorting... Done
Full Text Search... Done
dotnet-sdk-6.0/focal 6.0.413-1 amd64 [upgradable from: 6.0.408-1]
  Microsoft .NET SDK 6.0.408
```

Shouldn't be there a `6.0.414-1`?

**Comment by chefarbeiter** [comment]
@cmenzi .NET 6.0.22 (and its SDK) is completely missing in the Microsoft packages for Ubuntu, I have created issue #8772 for it.

**Comment by LumpBloom7** [comment]
The same dependency issue is also found for dotnet6 and dotnet7 on fedora, and it renders the sdk unusable without a downgrade.


```sh
user@computer > sudo dnf upgrade
Dependencies resolved.

 Problem 1: cannot install the best update candidate for package dotnet-runtime-6.0-6.0.21-1.x86_64
  - nothing provides dotnet-runtime-deps-6.0 >= 6.0.22 needed by dotnet-runtime-6.0-6.0.22-1.x86_64 from packages-microsoft-com-prod
 Problem 2: cannot install the best update candidate for package dotnet-runtime-7.0-7.0.10-1.x86_64
  - nothing provides dotnet-runtime-deps-7.0 >= 7.0.11 needed by dotnet-runtime-7.0-7.0.11-1.x86_64 from packages-microsoft-com-prod
 Problem 3: package aspnetcore-runtime-7.0-7.0.11-1.x86_64 from packages-microsoft-com-prod requires dotnet-runtime-7.0 >= 7.0.11, but none of the providers can be installed
  - cannot install the best update candidate for package aspnetcore-runtime-7.0-7.0.10-1.x86_64
  - nothing provides dotnet-runtime-deps-7.0 >= 7.0.11 needed by dotnet-runtime-7.0-7.0.11-1.x86_64 from packages-microsoft-com-prod
 Problem 4: package aspnetcore-runtime-6.0-6.0.22-1.x86_64 from packages-microsoft-com-prod requires dotnet-runtime-6.0 >= 6.0.22, but none of the providers can be installed
  - cannot install the best update candidate for package aspnetcore-runtime-6.0-6.0.21-1.x86_64
  - nothing provides dotnet-runtime-deps-6.0 >= 6.0.22 needed by dotnet-runtime-6.0-6.0.22-1.x86_64 from packages-microsoft-com-prod

```

**Comment by hoerup** [comment]
runtime7.0.11 / sdk7.0.401 seems to be missing from Centos7 repos

**Comment by LumpBloom7** [comment]
> A similar dependency issue is also found for dotnet6 and dotnet7 on fedora, and it renders the sdk unusable without a downgrade.
> 
> ```shell
> user@computer > sudo dnf upgrade
> Dependencies resolved.
> 
>  Problem 1: cannot install the best update candidate for package dotnet-runtime-6.0-6.0.21-1.x86_64
>   - nothing provides dotnet-runtime-deps-6.0 >= 6.0.22 needed by dotnet-runtime-6.0-6.0.22-1.x86_64 from packages-microsoft-com-prod
>  Problem 2: cannot install the best update candidate for package dotnet-runtime-7.0-7.0.10-1.x86_64
>   - nothing provides dotnet-runtime-deps-7.0 >= 7.0.11 needed by dotnet-runtime-7.0-7.0.11-1.x86_64 from packages-microsoft-com-prod
>  Problem 3: package aspnetcore-runtime-7.0-7.0.11-1.x86_64 from packages-microsoft-com-prod requires dotnet-runtime-7.0 >= 7.0.11, but none of the providers can be installed
>   - cannot install the best update candidate for package aspnetcore-runtime-7.0-7.0.10-1.x86_64
>   - nothing provides dotnet-runtime-deps-7.0 >= 7.0.11 needed by dotnet-runtime-7.0-7.0.11-1.x86_64 from packages-microsoft-com-prod
>  Problem 4: package aspnetcore-runtime-6.0-6.0.22-1.x86_64 from packages-microsoft-com-prod requires dotnet-runtime-6.0 >= 6.0.22, but none of the providers can be installed
>   - cannot install the best update candidate for package aspnetcore-runtime-6.0-6.0.21-1.x86_64
>   - nothing provides dotnet-runtime-deps-6.0 >= 6.0.22 needed by dotnet-runtime-6.0-6.0.22-1.x86_64 from packages-microsoft-com-prod
> ```

This has been resolved as of today. Thanks!

**Comment by cmenzi** [comment]
I also can confirm that it's resolved on Ubuntu. 👍 

```
root@myhost:~# apt search dotnet-sdk-6.0
Sorting... Done
Full Text Search... Done
dotnet-sdk-6.0/focal 6.0.414-1 amd64 [upgradable from: 6.0.413-1]
  Microsoft .NET SDK 6.0.413
```

**Comment by hoerup** [comment]
Centos7 packages are still missing
