### ISSUE TITLE
System.PlatformNotSupportedException: 'Registry is not supported on this platform.'

### ISSUE THREAD

**Issue by saharM** [dotnet/core#876]
## Steps to reproduce:

In Visual Studio 2017 version 15.3.0, in a .NET Core 2.0 Class library I install this Nuget package:

    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />

I write a simple method that uses RegistryKey class like this:

        internal static bool ReadRegistry()
        {
            bool ret = false;
            RegistryKey sampleDir = Registry.CurrentUser.CreateSubKey("Software\\Company\\Name");
            if (!string.IsNullOrEmpty(sampleDir.GetValue("Foo", "").ToString()))
                ret = true;
            return ret;
        }

I add a new Windows Form project to the solution and in this new project add a reference to my class library and call ReadRegistry method. Building the solution is successful. 

**Side Problem:** At runtime every time that the code reaches the line that calls ReadRegistry method I get this error: 

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'`

I try a workaround for this problem by downloading the package manually and copying "\microsoft.win32.registry.4.4.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" file into WinForm project "\bin\Debug" folder. It works and I can debug inside the ReadRegistry method.

**Main Problem:** Registry.CurrentUser is null and all static properties of Registry class are null and calling RegistryKey.OpenBaseKey method throws this exception:

`System.PlatformNotSupportedException: 'Registry is not supported on this platform.'`

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24483](https://github.com/dotnet/corefx/issues/24483) via [**ZenHub**](https://www.zenhub.com/)
