### ISSUE TITLE
.NET 6.0.22 is missing from the Microsoft sources for Ubuntu

### ISSUE THREAD

**Issue by chefarbeiter** [dotnet/core#8772]
The .NET 6.0.22 update released two days ago is not included in the Microsoft package repositories for Ubuntu (affects all versions).

```bash
sudo apt update
apt-cache policy dotnet-runtime-6.0
```
```
dotnet-runtime-6.0:
  Installed: 6.0.21-1
  Candidate: 6.0.21-1
  Version table:
 *** 6.0.21-1 500
        500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     6.0.20-1 500
        500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
     6.0.19-1 500
        500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
```
It is not a local problem on one system, because even a [direct look](https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-runtime-6.0/) into the repository shows that version 6.0.22 is not included there.
![image](https://github.com/dotnet/core/assets/16866252/767c768c-893e-477b-8fd2-2a2664f85267)

```bash
curl -s https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/binary-amd64/Packages | grep "6\.0\.22"
# -> No result
```
Version 7.0.11, released on the same day, on the other hand, is included in the packages.

**Comment by cmenzi** [comment]
Seems to be resolved.

```
root@myhost:~# apt search dotnet-sdk-6.0
Sorting... Done
Full Text Search... Done
dotnet-sdk-6.0/focal 6.0.414-1 amd64 [upgradable from: 6.0.413-1]
  Microsoft .NET SDK 6.0.413
```

**Comment by leecow** [comment]
Closing as this has been resolved.
