### ISSUE TITLE
.NET not recognized in Visual Studio Code

### ISSUE THREAD

**Issue by GMontero01** [dotnet/core#8777]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The .NET SDK 7.0 is installed but it is not recognized as the name of a cmdlet, function, script file, or operable program. My machine is a macbook air and i have windows Visual Studio Code installed

**Comment by mairaw** [comment]
Interesting that it's showing that you're accessing the Windows version of the tutorial. What kind of mac do you have and which version did you install? Did you open a new terminal window before you typed the command? And what do you mean by having windows VS Code installed?

**Comment by GMontero01** [comment]
I have a MacBook Air with the M1 chip 2020. Yes I did open a new terminal
multiple times as well as closed the app multiple times however the problem
still persists. What I mean by having windows VS code is I have the windows
version of VS code installed on parallels desktop which is a windows
emulator. I don’t have the VS code for mac app installed

**Comment by JonDouglas** [comment]
Can you help confirm what architecture of windows you installed with parallels? I think for m1, you would likely be installing arm windows 11.

https://www.parallels.com/blogs/windows-11-arm-apple-m-series/

Secondly, what .NET SDK architecture did you download?

See the limitations of this scenario here: https://support.microsoft.com/en-us/windows/options-for-using-windows-11-with-mac-computers-with-apple-m1-and-m2-chips-cd15fd62-9b34-4b78-b0bc-121baa3c568c

> 32-bit Arm apps available from the Store in Windows are not supported by Mac computers with M1 and M2 chips. 32-bit Arm apps are in the process of being deprecated for all Arm versions of Windows. The preferred customer experience is to run 64-bit Arm apps, but customers can also use apps in x64 or x86 emulation on Mac M1 and M2 computers. 

So you would need to ensure you're running either the native arm64 or x86 version of dotnet SDK. The former is preferred.

**Comment by GMontero01** [comment]
Yes the architecture for the windows is arm windows 11 and the .NET
architecture I’ve  tried all different methods of installing it including
arm64 and x86 of both .NET 7.0 and 6.0. Making sure to uninstall before
Installing another one to make sure they didn’t affect one another. The
problem still persists.

**Comment by JonDouglas** [comment]
Can you include what you're seeing on a console or within Visual Studio Code? Screenshots or text/error messages would be helpful
