### ISSUE TITLE
Error: Invalid parameter(s): -f net7.0     'net7.0' is not a valid value for -f (Framework).

### ISSUE THREAD

**Issue by burhanuddin345** [dotnet/core#8781]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by antonfirsov** [comment]
@burhanuddin345 have you installed the 7.0 SDK using the link in the [previous step](https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install)? Have you **opened a new command prompt/terminal**?
