### ISSUE TITLE
ASP.NET Tutorial - Hello World in 5 minutes 

### ISSUE THREAD

**Issue by codingkorb** [dotnet/core#8782]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: Ubuntu 22.04.1

zissou@aquatic:~/MyWebApp$ dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  Restored /home/zissou/MyWebApp/MyWebApp.csproj (in 132 ms).
  MyWebApp -> /home/zissou/MyWebApp/bin/Debug/net7.0/MyWebApp.dll
dotnet watch 🚀 Started

dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

It ends here...Can anybody help me out?

**Comment by antonfirsov** [comment]
@wli3
 @dsplaisted are you the experts on `dotnet watch`? If not, could you please loop them in?

**Comment by mairaw** [comment]
Adding @mkArtakMSFT and @danroth27 

If you do `dotnet run` instead of `dotnet watch`, does it work @codingkorb?

**Comment by danroth27** [comment]
@codingkorb How did you install the .NET SDK on your Linux machine? When you run `dotnet --version` what version do you see?
