### ISSUE TITLE
Unable to resolve 'Microsoft.AspNetCore.Op enApi (>= 7.0.11)' for 'net7.0'

### ISSUE THREAD

**Issue by johnheix-g** [dotnet/core#8788]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Operating system: Windows 11 Home 22H2 
I followed the tutorial and install .net 7 and docker. then I ran `dotnet new webapi -o MyMicroservice --no-https -f net7.0` in the command prompt window. I got below error message:

Restoring c:\xxxxx\microservice\MyMicroservice\MyMicroservice.csproj:
  Determining projects to restore...
**c:\xxxxx\microservice\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Op
enApi (>= 7.0.11)' for 'net7.0'.
c:\xxxxx\microservice\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore
(>= 6.5.0)' for 'net7.0'.**
  Failed to restore c:\xxxxx\microservice\MyMicroservice\MyMicroservice.csproj (in 84 ms).
Restore failed.
Post action failed.

What had I missed?

**Comment by carlossanlop** [comment]
@erjain @nishanil

**Comment by mairaw** [comment]
It might be an issue with your NuGet sources. Follow the instructions from https://github.com/dotnet/core/issues/6193#issuecomment-827395026 and see if that solves your issue.

**Comment by jamesmontemagno** [comment]
I was not able to reproduce here. 

https://github.com/jamesmontemagno/MyMicroservice works for me

Run:

```
PS C:\Users\jamont\Desktop\MyMicroservice> dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```
