### ISSUE TITLE
confusing versioning?

### ISSUE THREAD

**Issue by lifeofguenter** [dotnet/core#879]
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md

* why is the SDK versioned on 1.04 but the runtime 1.1.2? 
* is it safe to run production apps with the SDK dotnet-cli?

**Comment by omajid** [comment]
See https://github.com/dotnet/cli/issues/3773 for more on the confusion between runtime and sdk versions. The good news is that for 2.0, the confusion should mostly be gone. 2.0 has consistency between sdk and runtime versions.

**Comment by karelz** [comment]
Seems to be answered, closing.
