### ISSUE TITLE
.NET 8 RC will not install Runtime in VS 2022

### ISSUE THREAD

**Issue by windhandel** [dotnet/core#8790]
### Description

I have installed the .NET SDK (and reinstalled it) and am unable to get .NET 8 to show in VS Installer Individual Components for VS 2022 or VS 2019.

1. Install VS .NET 8 SDK

2. Cannot see .NET 8 within Individual Components.

3. Also, cannot change Target to .NET 8 within any projects.

### Configuration

.NET 8 RC 1 - dotnet-sdk-8.0.100-rc.1.23463.5-win-x64.exe
VS 2022 recently updated (and reinstalled the RC):
![VSUpdatedVersion](https://github.com/dotnet/core/assets/5337357/ac13579a-117b-4d6b-99c4-a53d313fd9da)

Microsoft Windows [Version 10.0.19045.3448]
x64

**Comment by mairaw** [comment]
But you need the latest VS 2022 **Preview** version installed to see .NET 8.

**Comment by windhandel** [comment]
Thanks @mairaw. Did I overlook that in the documentation somewhere?

I go to the following locations and I see no reference to needing to download VS 2022 Preview as you've suggested.

https://dotnet.microsoft.com/en-us/download
Following the link [See recommended downloads for the latest version of .NET](https://dotnet.microsoft.com/en-us/download).

How does one acquire such knowledge?

**Comment by richlander** [comment]
This now longer applies.

**Comment by mairaw** [comment]
With the launch of .NET 9 Preview 1 soon, just wanted to point out where this information can be found today. But we're planning to make some design changes in the future.
For each version listed on the specific release page, you'll find the Visual Studio support info:
e.g. https://dotnet.microsoft.com/en-us/download/dotnet/8.0

![image](https://github.com/dotnet/core/assets/12971179/0221cbbb-29ac-4cb5-9c0f-5891242ad99d)
