### ISSUE TITLE
code suggestion comment is wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/core#8791]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/code-suggestion-comment-is-wrong/10387343)._

---
as the following figure showes, the comment of function task.wait() is wrong. we should exchange positions of the words "true" and "Task"
![微信截图_20230608183105.png](https://aka.ms/dc/image?name=B8381c9dd647e44ad9660d933b54f55ed638218174275906559_%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230608183105.png&tid=8381c9dd647e44ad9660d933b54f55ed638218174275906559)

---
#### Feedback Bot on 6/8/2023, 05:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by buyaa-n** [comment]
Please follow the link @gewarren shared https://aka.ms/icxlocfeedback and file a localization ticket
