### ISSUE TITLE
Docker build not running

### ISSUE THREAD

**Issue by Kavya-Jindal** [dotnet/core#8792]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

 => ERROR [build 4/6] RUN dotnet restore                                                                                                                              21.6s
------
 > [build 4/6] RUN dotnet restore:
1.522   Determining projects to restore...
13.77 /src/MyMicroservice.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
21.42 /src/MyMicroservice.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
21.52   Failed to restore /src/MyMicroservice.csproj (in 19.67 sec).
------
Dockerfile:4
--------------------
   2 |     WORKDIR /src
   3 |     COPY MyMicroservice.csproj .
   4 | >>> RUN dotnet restore
   5 |     COPY . .
   6 |     RUN dotnet publish -c release -o /app
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet restore" did not complete successfully: exit code: 1

I am getting the above error message when i try to build the docker image using the following file:
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY MyMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MyMicroservice.dll"]

**Comment by nishanil** [comment]
ping @jamesmontemagno

**Comment by jamesmontemagno** [comment]
I was not able to reproduce here. Can you verify you moved things around. I see a /src/ in there...?

https://github.com/jamesmontemagno/MyMicroservice works for me

**Comment by jamesmontemagno** [comment]
Double check your nuget sources as well...

```

PS C:\Users\jamont\Desktop\MyMicroservice> dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```


see: https://github.com/dotnet/core/issues/6193#issuecomment-827395026

**Comment by mairaw** [comment]
This seems like the same issue as https://github.com/dotnet/core/issues/8337#issuecomment-1488941949

See if the DNS solution works for you as well
