### ISSUE TITLE
GraphicsCapturePicker fails capturing Edge tabs

### ISSUE THREAD

**Issue by juanmalm** [dotnet/core#8794]
### Description

- Use GraphicsCapturePicker
- Select a Microsoft Edge tab from the list to select a window to share

Expected behavior: The full tab content should be captured

Current behavior: Just a kind of title bar is captured 
![image](https://github.com/dotnet/core/assets/22932620/f289615e-3e41-4d0d-96a7-0c9737c1ab83)

### Configuration

.NET 7
Target Windows 10.0.22000.0
Min target version 10.0.17763.0
x64

### Additional info

With Chrome you are not able to select individual tabs, just the window.

**Comment by carlossanlop** [comment]
@juanmalm this is not a .NET feature.

According to the [documentation for GraphicsCapturePicker](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker?view=winrt-22621), feedback for this product can be reported in this page: https://learn.microsoft.com/en-us/answers/tags/105/windows-uwp

Please open an issue there. Closing now.
