### ISSUE TITLE
problem with editing the index page

### ISSUE THREAD

**Issue by Hapirose** [dotnet/core#8795]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am using Microsoft windows 10 operating system, I try to follow along with the dotnet tutorial on the Hello World. All I need to do is to edit the index.cshtml.cs file. but this file carries a different content.

below is the content of my index.cshtml.cs file, I do not know where to change to give output 'Hello world'

```cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyWebApp.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}
```

below is the task:

Replace all of the code with the following, then save the file. The highlighted lines of code show the changes you'll be making.

Pages/Index.cshtml

Copy
```razor
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>
```

**Comment by fatumasukar** [comment]
I have encountered the same error. Make sure you are clicking on the file named Index.cshtml and not other similar files.
<img width="560" alt="Screen Shot 2023-10-02 at 3 38 26 PM" src="https://github.com/dotnet/core/assets/146384691/cb311074-332d-436a-a917-c07b7e4c00ed">

**Comment by mairaw** [comment]
We have removed that tutorial from the site. Please try https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro instead.
