### ISSUE TITLE
BlazorApp.styles.css: not found

### ISSUE THREAD

**Issue by mellogrand** [dotnet/core#8797]
I have tried both the cli and ws2022 version of the BlazoApp tutorial and in both cases i get a 404 for BlazorApp.styles.css

I imagine that something is not  ok with isolation?

**Comment by carlossanlop** [comment]
Hello @mellogrand - Can you please provide some more info?:

- Can you please share the link to the specific tutorial you were following? If you can also indicate the page, that would be great.
- What .NET version are you using?

**Comment by mellogrand** [comment]
thank you again.
I solved the issue related to a strange inheritance of environment not from
the json file in the project but from windows settings. I had test
instead of development.
In net 6 was not affecting, but in 7 and 8 it was. Strange, but solved.

Il giorno lun 2 ott 2023 alle ore 19:26 Carlos Sánchez López <
***@***.***> ha scritto:
