### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by HODUCVU** [dotnet/core#8798]
I code in terminal:
dotnet new webapp -o MyWebApp --no-https -f net7.0
Error:
A fatal error occurred. The folder [/usr/lib/dotnet/host/fxr] does not exist.
Please, so me what I should do!
Thanks a lot!
Note: version Linux

**Comment by carlossanlop** [comment]
Hello @HODUCVU - Did you make sure to install the .NET SDK and not the runtime?

**Comment by WhiteSymmetry** [comment]
sudo apt remove dotnet-sdk* dotnet-host* dotnet* aspnetcore* netstandard*
sudo apt remove aspnetcore*
sudo apt remove netstandard*
sudo apt remove dotnet-host8*
sudo apt purge dotnet-sdk* dotnet-host* dotnet* aspnetcore* netstandard*
sudo rm -f /etc/apt/sources.list.d/mssql-release.list
sudo rm /etc/apt/sources.list.d/microsoft-prod.list
sudo rm /etc/apt/sources.list.d/microsoft-prod.list.save
sudo apt update
Instal by App Center: .Net Core SDK, Stable 8.0.101 
there is no need for other installations!
(sudo snap install dotnet-sdk #Installed by App Center
sudo apt install dotnet-sdk-8.0 #Installed by App Center
sudo apt install dotnet-host-8.0 #Installed by dotnet-sdk-8.0)
dotnet workload update
source ~/.bashrc
dotnet sdk check
.NET SDKs:
Version      Status                     
----------------------------------------
8.0.100      Patch 8.0.101 is available.

dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/233/sdk/8.0.100/
 
 Host:
  Version:      8.0.0
  Architecture: x64

dotnet --list-sdks
8.0.100 [/snap/dotnet-sdk/233/sdk]
dotnet --version
8.0.100
