### ISSUE TITLE
"Microsoft.NETCore.Platforms": "1.0.1-*" What is it for

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/core#88]
I have been follwowing nightlys  -> RC2 so I have been following all the changes to project json etc.

One thing that still escapes me.

"Microsoft.NETCore.Platforms": "1.0.1-*"  dependency.  What is it for?

**Comment by xabikos** [comment]
I am also curious about this as it is used in cli samples repository on [project.json](https://github.com/aspnet/cli-samples/blob/master/HelloWebFull/project.json) of the example for the full .net framework

**Comment by joshfree** [comment]
It's the package that contains the runtime identifiers (RIDs) for the supported platforms - 

https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog

https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0.md#rtm-platform-support

https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

**Comment by andriysavin** [comment]
@joshfree These links explain the content of the package, but its still not clear (at least to me) when and why I need to reference that package. For example, XUnit docs instruct to add this package to be able to run tests for desktop CLR code, but I can't find any reason why: [https://xunit.github.io/docs/getting-started-dotnet-core.html#targeting-desktop](url)

**Comment by ericstj** [comment]
Usually you won't need to directly reference this.  

As a package developer you should only need to reference it if your package uses runtimes (eg: runtimes/rid/lib/tfm/foo.dll) and doesn't already bring it in indirectly.

In your project you only need to reference it if you are using the "runtimes" section in the project.json and it isn't already brought in by the packages you've referenced.

The link you posted was out of date, but I suspect that link predated the work we did to automatically reference this package in all CoreFx packages: https://github.com/dotnet/corefx/issues/8239.

**Comment by andriysavin** [comment]
Sorry, I've fixed the link. Thanks for clarification!
