### ISSUE TITLE
ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

### ISSUE THREAD

**Issue by psychohub** [dotnet/core#8801]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
@psychohub Closing as there is not enough information provided in the issue description. Please make sure to add an explanation of the problem you encountered so that we can help you.
