### ISSUE TITLE
Can someone help me with this

### ISSUE THREAD

**Issue by JeezHeart** [dotnet/core#8804]
Found .NET SDK, but did not find dotnet.dll

**Comment by JeezHeart** [comment]
I'm new in Programming can someone help me with my issue

**Comment by carlossanlop** [comment]
@JeezHeart Can you provide more details?

- Did you download and install the SDK?
- Did you close and reopen any terminal windows you had open before installing the SDK?
- Are you following a particular tutorial?
- What were you trying to do specifically?
