### ISSUE TITLE
Some issue with dotnet

### ISSUE THREAD

**Issue by AngieLuts** [dotnet/core#8810]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://github.com/dotnet/core/assets/145261151/cf3eb9b0-04dc-4605-89c4-fc1b59a42df1)
Installed dotnet, but still cannot run the command

**Comment by amccombsahce** [comment]
I'm getting that too.  I found that there is a /etc/profile.d/dotnet.sh but it doesn't seem to get executed when making a new shell session (open Terminal window). I have no idea on what I am doing, just guessing to add the $DOTNET_ROOT as older posts have suggested having $DOTNET_ROOT set. And of course there is a usr/share/dotnet and a usr/lib/dotnet, so I don't know so I put both in figuring it if worked then I could optimize it later.

dotnet.sh:
`
DOTNET_TOOLS_PATH="$HOME/.dotnet:$HOME/.dotnet/tools"
case "$PATH" in
    *"$DOTNET_TOOLS_PATH"* ) true ;;
    * ) PATH="$PATH:$DOTNET_TOOLS_PATH" ;;
esac

[ -z "$DOTNET_ROOT" ] && export DOTNET_ROOT="/usr/share/dotnet:/usr/lib/dotnet"

DOTNET_ROOT="/usr/share/dotnet:/usr/lib/dotnet"
case "$DOTNET_ROOT" in
    *"$DOTNET_ROOT"* ) true ;;
    * ) DOTNET_ROOT="$DOTNET_ROOT:$DOTNET_ROOT" ;;
esac

[ -z "$DOTNET_BUNDLE_EXTRACT_BASE_DIR" ] && export DOTNET_BUNDLE_EXTRACT_BASE_DIR="${XDG_CACHE_HOME:-"$HOME"/.cache}/dotnet_bundle_extract"
`

when I open a new Terminal window and do "export", a list of stuff is printed, however the $DOTNET_ROOT is not in the list. Even when I do "source /etc/profile.d/dotnet.sh",  it does not add the $DOTNET_ROOT to the environment, but it does add the dotnet_tools_path to path but I get an error before that about a valid identifier:

`alice@alice-VirtualBox:~$ export $PATH
bash: export: `/home/alice/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin::/snap/bin:/home/alice/.dotnet:/home/alice/.dotnet/tools': not a valid identifier`

I think it's complaining about '/snap/bin::', which is in /etc/profile.d/apps-bin-path.sh, but there isn't a double :: in that file, who knows where it's coming from as I checked all the environment areas: .bashrc, I don't have .bash_profile , .profile, /etc/environment, /etc/bash.bashrc

**Comment by vitek-karas** [comment]
@AngieLuts it seems you installed only the "runtime". We ship two main packages for .NET, the "runtime" and the "SDK". The "runtime" is the bits necessary to run .NET apps, but not to create them. The "SDK" contains all the tools build .NET apps (and it will also install the "runtime" as part of it)

Please make sure you install the SDK and then try again.
