### ISSUE TITLE
SDK not frond  

### ISSUE THREAD

**Issue by KOKOMI12345** [dotnet/core#8813]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
problem:
I use this(dotnet --version) command to Val my version but it says SDK not frond, when I used this "dotnet-runtime-7.0.11-win-x64.exe" file to download.

output:
--- trackback most recent last --- 
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by carlossanlop** [comment]
Did you make sure to close and reopen the command line window after installing dotnet? This is a necessary step to ensure the environment variables get updated and the dotnet executable is found.

**Comment by carlossanlop** [comment]
Hi - You need to install the SDK, not the runtime. Can you please try that and see if that worked?

**Comment by KOKOMI12345** [comment]
o,sorry , I solved,thanks!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carlos Sánchez ***@***.***&gt;; 
发送时间: 2023年10月10日(星期二) 凌晨0:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnet/core] SDK not frond   (Issue #8813)






嗨——你需要安装SDK，而不是运行时。你能试试看有没有用吗？

-
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
