### ISSUE TITLE
error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.

### ISSUE THREAD

**Issue by jfaigan** [dotnet/core#8814]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

I am trying to run through the tutorial and I am getting the following error: 
error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.

I am running VS 2022 on Windows 10 Pro 22H2

This is the contents of the Dockerfile:
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY backend.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app .
ENTRYPOINT ["dotnet", "backend.dll"]

This is the command I am running:
docker build -t backend .

I have tried adding the DNS entries to the Docker settings but this did not help.
![image](https://github.com/dotnet/core/assets/14929031/437c504c-c5c0-4010-bb94-9c53c6e8aa19)

Any help would be greatly appreciated!

**Comment by mairaw** [comment]
I'm sorry you're running into issues. Ae you saying you already tried what is described here?
https://github.com/dotnet/core/issues/8337#issuecomment-1488941949

**Comment by jfaigan** [comment]
Hi there,

Yes, I posted the image of the DNS change to the Docker Desktop in my original message.  Unfortunately, this has not solved the issue.

Regards,
Joel

**Comment by jfaigan** [comment]
> I'm sorry you're running into issues. Ae you saying you already tried what is described here? [#8337 (comment)](https://github.com/dotnet/core/issues/8337#issuecomment-1488941949)

Hi Maria,

I replied to you last week.  Have you had a chance to look at this?

Regards,
Joel

**Comment by jfaigan** [comment]
> > I'm sorry you're running into issues. Ae you saying you already tried what is described here? [#8337 (comment)](https://github.com/dotnet/core/issues/8337#issuecomment-1488941949)
> 
> Hi Maria,
> 
> I replied to you last week. Have you had a chance to look at this?
> 
> Regards, Joel

Hi Maria,

I was wondering if you have any other ideas?

Regards,
Joel

**Comment by wfurt** [comment]
did you try to check if the name resolves and if it is reachable @jfaigan ? e.g. `ping api.nuget.org` and `curl -v  https://api.nuget.org/` or `wget https://api.nuget.org/`

(you may need to add packages for the tools)

**Comment by jfaigan** [comment]
> did you try to check if the name resolves and if it is reachable @jfaigan ? e.g. `ping api.nuget.org` and `curl -v https://api.nuget.org/` or `wget https://api.nuget.org/`
> 
> (you may need to add packages for the tools)

It turns out it was a ZScaler issue.  I was unable to access the internet from the docker.  I added some lines to copy the certificate to the docker and then I was able to access the nuget site.

This ticket can be closed.

Regards,
