### ISSUE TITLE
Error .NET

### ISSUE THREAD

**Issue by GeralRH** [dotnet/core#8817]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![imagen_2023-10-07_154014328](https://github.com/dotnet/core/assets/143021377/de75255f-f098-4aff-901d-c778218dd0bc)

**Comment by carlossanlop** [comment]
Can you please provide more information?
- What .NET version are you using? 
- Can you show the code snippet that you were writing that failed to compile?
