### ISSUE TITLE
First part downloading and installing succeded second part creating project failed.

### ISSUE THREAD

**Issue by jojomondag** [dotnet/core#8818]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

josef@josef-System-Product-Name:~/Downloads$ dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
josef@josef-System-Product-Name:~/Downloads$ dotnet new console -o MyApp -f net7.0
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
josef@josef-System-Product-Name:~/Downloads$

**Comment by LaymanBrian** [comment]
run command `dotnet --list-sdks` to check if you installed a .NET SDK

**Comment by jojomondag** [comment]
> run command `dotnet --list-sdks` to check if you installed a .NET SDK

I solved the issue thx.
