### ISSUE TITLE
Projeto Blazor Server não executa

### ISSUE THREAD

**Issue by msmsobral** [dotnet/core#8819]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/aspnet/blazor-tutorial/run
Operating System: windows
Criei o projeto Blazor Server e tentei executa-lo mas apresenta falha:

O processo de destino saiu sem gerar um evento iniciado do CoreCLR. Certifique-se de que o processo de destino esteja configurado para usar o .NET Core. Isso pode ser esperado se o processo de destino não tiver sido executado no .NET Core.
O programa "[2976] painelFLF.exe" foi fechado com o código 2147516566 (0x80008096).

**Comment by carlossanlop** [comment]
@danroth27 for blazor.
@mairaw for tutorials (also the question is in portuguese).

**Comment by mairaw** [comment]
The English version of that error message would be something like this:

The target process exited without triggering an event fired by CoreCLR. Make sure the target process is configured to use .NET Core. This is to be expected if the target process is not running on .NET Core. The program '[2976] painelFLF.exe' exited with code 2147516566 (0x80008096).

@msmsobral você pode nos dizer o que `dotnet --info` retorna?

**Comment by mairaw** [comment]
Outra pergunta: se você tentar executar o aplicativo pela linha de comando, funciona?
https://dotnet.microsoft.com/pt-br/learn/aspnet/blazor-cli-tutorial/run

**Comment by leandromeneguim** [comment]
estou com o mesmo erro. voce conseguiu resolver?
