### ISSUE TITLE
i can not get access to localhost env when i try to update code 

### ISSUE THREAD

**Issue by Aminejemmali** [dotnet/core#8821]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
Can you provide more details? What do you mean you cannot access the localhost env? What .NET version are you using? What OS?

**Comment by Aminejemmali** [comment]
i use .net v7 with windows 
when i try to debug my code , they told me that :
 Cette page du site localhost est introuvableAucune page Web trouvée à l'adresse :http://localhost:5285/

**Comment by liveans** [comment]
Hello, @Aminejemmali I suspect your application might not be built/started. Can you double-check if your application is running through Visual Studio without any errors?

And by `debug my code`, do you mean you're trying to open your application through a web browser?

**Comment by mairaw** [comment]
And the command prompt window is not showing any errors when you run `dotnet watch`?

**Comment by Aminejemmali** [comment]
> And the command prompt window is not showing any errors when you run `dotnet watch`?

yeah its seems like i get confused in localhost port
