### ISSUE TITLE
.NET 8.0 RC2

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8828]
[Release Notes](https://github.com/dotnet/core/blob/main/release-notes/8.0/preview/8.0.0-rc.2.md)

Please report any issues you find with [.NET 8 RC 2](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc2/), either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by mairaw** [comment]
Thank you for your feedback @thabaum. I'm reaching out to some folks internally to help with that.

**Comment by eduherminio** [comment]
According to https://github.com/dotnet/core/issues/8439#issuecomment-1703217897 this piece code was needed for RC1 to make configuration binder source generator work, but it would no longer be needed for RC2 and onwards.
```
<Features>$(Features);InterceptorsPreview</Features>
```

However, (even without removing it), I'm facing with [this build error](https://github.com/lynx-chess/Lynx/actions/runs/6451139064/job/17581561605):
```bash
Error: /Users/runner/work/my_repo_dir/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(35,10): error CS9137:
The 'interceptors' experimental feature is not enabled in this namespace.
Add '<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsPreviewNamespaces>' to your project. [/Users/runner/work/my_repo_dir/MyProject.csproj]
```

If I'm not wrong, that isn't mentioned in the [package README](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder/8.0.0-rc.2.23479.6#readme-body-tab) or the [RC2 article announcement](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc2/).

Is that the intended behavior? If that's the case, it's probably worth mentioning in the places mentioned above.

cc/ @layomia

**Comment by WeihanLi** [comment]
@eduherminio it was changed to use `InterceptorsPreviewNamespaces`, and it mentions in the documentation https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md#user-opt-in

see: 
- https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md#user-opt-in
- https://github.com/dotnet/roslyn/pull/69848
- https://github.com/dotnet/sdk/pull/35024

**Comment by mairaw** [comment]
@thabaum the CVE page was updated. Thanks for letting us know!

**Comment by SirichaiThahad1993** [comment]
I found an issue about the Target framework of Project not show .NET 8.0 after I installed the SDK 8.0.100-rc.2
I solved the issue by uninstall the sdk from rc.2 to rc.1

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/8904
