### ISSUE TITLE
Dotnet run command fail

### ISSUE THREAD

**Issue by Anathi-Soga** [dotnet/core#8834]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

/usr/local/share/dotnet/sdk/7.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(594,5): error NETSDK1177: Failed to sign apphost with error code 0: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun [/Users/anathi/MyApp/MyApp.csproj]
/usr/local/share/dotnet/sdk/7.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(594,5): error NETSDK1177: /Users/anathi/MyApp/obj/Debug/net7.0/apphost: the codesign_allocate helper tool cannot be found or used [/Users/anathi/MyApp/MyApp.csproj]
/usr/local/share/dotnet/sdk/7.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(594,5): error NETSDK1177:  [/Users/anathi/MyApp/MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by liveans** [comment]
Hello,

Looks like some of the necessary tools don't exist on your machine. Can you try to run `xcode-select --install` first and then can you run `dotnet run` again?

cc: @mairaw

**Comment by Anathi-Soga** [comment]
Thank you @liveans, your solution worked :)
