### ISSUE TITLE
found but can't run

### ISSUE THREAD

**Issue by Luco2** [dotnet/core#8836]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

$ dotnet watch
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\7.0.12\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\7.0.12\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by liveans** [comment]
Hello,

Which Windows version you're currently using?

**Comment by Luco2** [comment]
figured it out thanks
