### ISSUE TITLE
.Net error on VS code

### ISSUE THREAD

**Issue by Asrorbek-Abrorov** [dotnet/core#8838]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

PS C:\Users\asabr\MyApp> scriptcs "c:\Users\asabr\MyApp\Program.cs"
scriptcs : Имя "scriptcs" не распознано как имя командлета, функции, файла сценария или выпол
няемой программы. Проверьте правильность написания имени, а также наличие и правильность пути
, после чего повторите попытку.
строка:1 знак:1
+ scriptcs "c:\Users\asabr\MyApp\Program.cs"
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scriptcs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by liveans** [comment]
Hello, 

I'm not sure which executable you're trying to run, but if you want to create a project within the folder you can use `dotnet new console`, or if you want to run the project you can use `dotnet run`.
