### ISSUE TITLE
Error running docker following tutorial instructions

### ISSUE THREAD

**Issue by dverschED** [dotnet/core#8839]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

I am following tutorial above.  My command window was Run As Administrator.  My command window contents have been copied below, including the error,  I've also attached a zip file containing my Dockerfile and .dockerignore files Please advise ASAP.  Thanks!

Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. All rights reserved.

C:\Users\dversch>docker --version
Docker version 24.0.6, build ed223bc

C:\Users\dversch>cd MyMicroservice

C:\Users\dversch\MyMicroservice>fsutil file createnew Dockerfile 0
File C:\Users\dversch\MyMicroservice\Dockerfile is created

C:\Users\dversch\MyMicroservice>start Dockerfile

C:\Users\dversch\MyMicroservice>fsutil file createnew .dockerignore 0
File C:\Users\dversch\MyMicroservice\.dockerignore is created

C:\Users\dversch\MyMicroservice>start .dockerignore

C:\Users\dversch\MyMicroservice>docker build -t mymicroservice .
ERROR: error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.

C:\Users\dversch\MyMicroservice>docker images
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/json": open //./pipe/docker_engine: The system cannot find the file specified.

C:\Users\dversch\MyMicroservice>
[dockerstuff.zip](https://github.com/dotnet/core/files/12918525/dockerstuff.zip)

**Comment by liveans** [comment]
@jamesmontemagno @bradygaster can you help here?

**Comment by dverschED** [comment]
I got it. Docker was not running.  Works fine now, thanks!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
