### ISSUE TITLE
找不到匹配“donsole”的模板或子命令。

### ISSUE THREAD

**Issue by luogod03** [dotnet/core#8840]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by liveans** [comment]
Hello,

Which problem you're facing with? Can you share with us a bit more?
