### ISSUE TITLE
can not get the date and time to show

### ISSUE THREAD

**Issue by Granny4201** [dotnet/core#8847]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows
 windows 11 I followed the instructions to the letter and went back and restarted it to make sure I did it right. But, I still can't get it to show the time and date.
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![net show time and date commands](https://github.com/dotnet/core/assets/141572781/acac6dab-a2a8-4815-bcd7-dac165c61a7e)
![net show time and date commands]

**Comment by liveans** [comment]
Hello,

You should open the `Program.cs` in an editor (for ex: Notepad, VS Code, etc.) and write the following lines in the `Program.cs` file. After that, you can run `dotnet run` on the command prompt. It will work.

```c#
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);
```
