### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hawaadam** [dotnet/core#8849]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

code:
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by liveans** [comment]
Hello, 
First of all, please make sure you downloaded and installed SDK.

If you open the command prompt before installation is completed, the command prompt will not find `dotnet`. Can you restart your command prompt and try again?
