### ISSUE TITLE
publish command with -o directive creating directories nested recursively

### ISSUE THREAD

**Issue by randolfrf** [dotnet/core#885]
# Publish command with -o directive creates nested directories at the -o target

I have a brand new asp.net core 2 mvc web project. When I run: 

`$dotnet publish -c release -o ./app/compiled`

App is built in release mode and published to /app/compiled. Everything works fine. I have the following structure:
..
/app
/app/compiled/
/app/wwwroot/
/app/wwwroot/css
/app/wwwroot/images
/app/wwwroot/js
/app/wwwroot/lib
/app/wwwroot/lib/... (a few more inside lib, with lib data)
..

This structured is the intended one, but when trying to run again the command:

`$dotnet publish -c release -o ./app/compiled`

I end up with this structure:

..
/app
/app/compiled/
/app/compiled/app
/app/compiled/app/compiled
/app/compiled/app/compiled/wwwroot
/app/compiled/app/compiled/wwwroot/lib
/app/compiled/app/compiled/wwwroot/lib/... (a few more within lib, one for each package BUT WITHOUT CONTENT)
/app/wwwroot/
/app/wwwroot/css
/app/wwwroot/images
/app/wwwroot/js
/app/wwwroot/lib
/app/wwwroot/lib/... (a few more inside lib with lib data)
..

Every time I run the publish with output command a new /app/compiled/ directory with partial contents is being created in the previous /app/compiled/ directory. After 4 executions I end up having:

/app/compiled/app/compiled/app/compiled/app/compiled/

# General

I'm running .netCore 2, installed SDK from https://www.microsoft.com/net/download/core, on a fresh new machine running macOS 10.12.6. 

I'm running: 

`dotnet new mvc`

As template and that's all. No other nuget package, nor any other extension.

**Comment by randolfrf** [comment]
Just to be clear, If I try again with another project (of another type) the behavior is the same.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #7782](https://github.com/dotnet/cli/issues/7782) via [**ZenHub**](https://www.zenhub.com/)
