### ISSUE TITLE
Visual Studio Community Update taking forever to finish

### ISSUE THREAD

**Issue by Tuhaise** [dotnet/core#8851]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: Windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am trying to update my Visual Studio Community so that I can install ASP.NET. However, the installation is taking forever to complete. The download shows that it is complete but there is no progress with the installation of packages. I have been waiting for over 40 minutes now.

![Capture](https://github.com/dotnet/core/assets/123007325/55b5b102-6494-4cb4-b7ce-0b9b3c5a4002)

**Comment by liveans** [comment]
Hello,

This is not related to dotnet, this issue is related to VS itself, Can you open the issue from [this](https://developercommunity.visualstudio.com/content/problem/post.html?space=8) link?

Thanks!
