### ISSUE TITLE
docker build -t mymicroservice . => ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? MacOS

### ISSUE THREAD

**Issue by BrayanGS** [dotnet/core#8854]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
Can you please provide more information as to what happened?
