### ISSUE TITLE
Support for Creating Sparse Files

### ISSUE THREAD

**Issue by dawn-lc** [dotnet/core#8858]
### Description

I’m working on a project where I need to create sparse files using .NET. I understand that creating sparse files requires platform-specific APIs.

I was wondering if there’s a recommended approach for doing this in a cross-platform way with .NET. Is there a recommended way to create sparse files in .NET that works across different platforms? Or are there any plans to add support for sparse files in future versions of .NET?

### Regression?

As far as I know, .NET does not currently have built-in support for creating sparse files.

**Comment by michaelgsharp** [comment]
Hey @dawn-lc, could you resubmit this into the dotnet/runtime repo with the feature request issue template? https://github.com/dotnet/runtime/issues/new/choose.  That will make sure it gets to the right place. I'll close this issue so you can do that.

Thanks!
