### ISSUE TITLE
Builing under windows bash fails due to non-executable stack

### ISSUE THREAD

**Issue by jkotas** [dotnet/core#886]
_From @sk-havok on August 22, 2017 14:14_

Repro: run dotnet.bootstrap.py
During the configuration phase, the following error is encountered.
This seems like a shortcoming of the linux subsystem, but perhaps there is some workaround?

Running: /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/dotnetcli/dotnet /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/run.exe build -Project=/home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/build.proj -generateHeaderUnix -NativeVersionSourceFile=/home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/bin/obj/Linux.x64.Debug/version.cpp -BuildArch=x64 -BuildType=Debug -BuildOS=Linux
Failed to load /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.0-rc3-002733/libcoreclr.so, error: /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.0-rc3-002733/libcoreclr.so: **cannot enable executable stack as shared object requires: Invalid argument**
Failed to bind to CoreCLR at [/home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.0-rc3-002733]
ERROR: An error occured in /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/dotnetcli/dotnet /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr/Tools/run 7. Check 7 logs under /home/stkenned/core/tools/dotnet-bootstrap/ubuntu.16.04-x64-dotnet/src/coreclr. Restoring the OptimizationData package

_Copied from original issue: dotnet/coreclr#13518_

**Comment by jkotas** [comment]
This was fixed in #4048. The problem is that the dotnet.bootstrap.py script is using very old build (Microsoft.NETCore.App/1.0.0-rc3-002733).

**Comment by jkotas** [comment]
dotnet.bootstrap.py should be updated to use more recent .NET Core build to fix this.

**Comment by Petermarcu** [comment]
@chcosta

**Comment by richlander** [comment]
We are deprecating dotnet.bootstrap.py. Please check out https://github.com/dotnet/source-build

See: #1063
