### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by aballer777** [dotnet/core#8865]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am trying to download arcgis pro 3.0.1 and I keep getting an error that I need minimum 6.0.5 .NEW Desktop runtime but I thought I downloaded that because I run the DotNet command andit shows up like it is working but when I got into the registry editor it only shows I have v4 please help I need this downloaded I dont have my laptop so I have to use my desktop

**Comment by michaelgsharp** [comment]
When you run `dotnet --version` what does it return?
