### ISSUE TITLE
Visual Studio 2017 15.3.2 Default Template - Dependencies broken

### ISSUE THREAD

**Issue by MBODM** [dotnet/core#887]
Since i can not found anything related on the interwebz, nor an issue here, i open one. 

If you just select the default WebApplication(MVC) template in VS2017 15.3 with AspNetCore 2.0 chosen, you get a template with one Package:

PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0"

Thats all fine. But inside this package there is a dependency conflict. VS shows a warning sign on the sub-package Microsoft.ApplicationInsights.AspNetCore 2.1.1 in solution explorer. If i open the NuGet dependencies treeview in solution explorer, then it shows this warning text there:

-NuGet
-> Microsoft.AspNetCore.All (2.0.0)
  ----> Microsoft.AspNetCore.ApplicationInsights.HostingStartup (2.0.0)
        -------> Microsoft.ApplicationInsights.AspNetCore (2.1.1)
                 -----------> "Package Microsoft.ApplicationInsights.AspNetCore 2.1.1 is not
                 -----------> compatible with netcoreapp2.0 (.NETCoreApp,Version=2.0).
                 -----------> Package Microsoft.ApplicationInsights.AspNetCore 2.1.1 supports 
                 -----------> - net451 (.NETFramework,Version=4.5.1)
                 -----------> - netstandard1.6 (.NETStandard,Version=1.6)

(this stupid github editor can not even use spaces here... damn... sorry, no better formatting possible)

I assume the combination of packages behind the meta package (Microsoft.AspNetCore.All) are not correct, cause of the error with Microsoft.ApplicationInsights.AspNetCore (2.1.1). Seems that package can only work with net451 and netstandard16 but not with asp.net core 2.0. Since its embedded in the meta package (Microsoft.AspNetCore.All) thats not great.

PS: I didnt have done anything with the project. Just install VS2017 Community newest version (15.3.2), open it and make a new asp.net core 2.0 project, to reproduce.

Any suggestions ?

**Comment by MBODM** [comment]
Why is nobody also having this problem (seems so, because Inet nothing reflects). On every (clean) machine i install Visual Studio 2017 15.3 i can not build a totally standard .net core 2.0 app from the template, cause Visual Studio shows this errors:

1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202: Package Microsoft.ApplicationInsights.AspNetCore 2.1.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.ApplicationInsights.AspNetCore 2.1.1 supports:
1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202:   - net451 (.NETFramework,Version=v4.5.1)
1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202:   - netstandard1.6 (.NETStandard,Version=v1.6)
1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202: Package Microsoft.ApplicationInsights.DependencyCollector 2.4.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.ApplicationInsights.DependencyCollector 2.4.1 supports:
1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202:   - net40 (.NETFramework,Version=v4.0)
1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5)
1>C:\Users\marcel\Desktop\WebApplication1\WebApplication1\WebApplication1.csproj : error NU1202:   - netstandard1.6 (.NETStandard,Version=v1.6)

i do not understand how anyone out there could run a .net core 2.0 app at the moment, since there is no newer version of that applicationinsights package ???

**Comment by MBODM** [comment]
7h after my issue was closed (with a hillarious answer) by MS, they "magically" released 15.3.3. Which fixes the above problem (Release Notes show a slightly another problem, but obviously it also do some fixing stuff for my problem).

No communication by MS. Just a fucked up support closing my issue withou even reading it or asking something, just to silently work on a fix (15.3.3). MS just became a fucked up company. Nothing less.

Or in short: Now that they released 15.3.3 you can close this issue. Thx anyway.

**Comment by Petermarcu** [comment]
Glad the issue got resolved. I'll close this.
