### ISSUE TITLE
Save changes access denied

### ISSUE THREAD

**Issue by rahatulmaksud1997** [dotnet/core#8873]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

![image](https://github.com/dotnet/core/assets/40181645/7af7bf6e-f921-4bf4-9bc0-e40643b534a2)

**Comment by mairaw** [comment]
Interesting that it let you save the project in that location. That's a protected system folder (c:\windows\system32). 

I'd start the tutorial over on a new location.

Let us know if this helps!
