### ISSUE TITLE
when write this command dotnet new console -o MyApp -f net7.0 

### ISSUE THREAD

**Issue by Marsel-prof** [dotnet/core#8874]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
when write this command dotnet new console -o MyApp -f net7.0
it give me:
 The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by mairaw** [comment]
I'm sorry to hear you're running into issues.

Have you installed the .NET 7 SDK as instructed in the previous step?
If so, can you run a few commands for us and let us know what they return? The first one is `dotnet --info` and the second one is `where.exe dotnet`.
