### ISSUE TITLE
dotnet run

### ISSUE THREAD

**Issue by simmy12** [dotnet/core#8876]
Hi. after dotnet run, I get Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5137
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\לייכטר\Desktop\סימי\MyMicroservice

i am waiting for Wait for the app to display that it's listening on http://localhost:<port number>,  but nothing comes up/

**Comment by michaelgsharp** [comment]
From the output it looks like everything is running correctly. Please make sure you are following all the steps from the tutorial.

**Comment by mairaw** [comment]
Did you try opening the URL on the browser?
