### ISSUE TITLE
 Could not find a MSBuild project file in 'C:\Users\jamuhuri'. Specify which project to use with the --project option.

### ISSUE THREAD

**Issue by EliasChege** [dotnet/core#8879]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment]
Could you please provide more information on what the issue you encountered was?

**Comment by mairaw** [comment]
Did you do `cd MyWebApp` as instructed?
