### ISSUE TITLE
Notifications about ending OS support

### ISSUE THREAD

**Issue by Falco20019** [dotnet/core#8880]
I didn't find an issue with the os-support label (or any else regarding this). Support for Alpine 3.15 ended yesterday. Is there already a tracking issue? Is it planned to be dropped for .NET 6.0 and .NET 7.0?

We have an aggregated internal overview that I want to keep updated and for that I would like to track that if possible :)

/CC @rbhanda @richlander

**Comment by richlander** [comment]
You can consider support dropped, however, @rbhanda, do we have some paper work for that?

It is interesting to hear that you have an internal overview of this. Is there something we can do better to help with that? It is always interesting to us to hear about folks that have a structured program for such things. Feel free to respond here or mail us at dotnet@microsoft.com if you want to discuss this further.

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/issues/8888 created for this

**Comment by Falco20019** [comment]
Hi @richlander,

thanks for your interest. We are mostly tracking the upcoming end of support per product and the differences between the version (especially what is dropped). While the `supported-os.md` files would have a `Out of support OS versions` section, those are generally not well maintained. For example, the .NET 7 page shows only Fedora 35 and SUSE LES 12 SP2-4 as out of support. But I know that also Alpine Linux 3.15, Fedora Linux 36, openSUSE Linux 15.0 - 15.3, Ubuntu Linux 18.04 and macOS 10.x are EOS. Upfront, I totally understand that it's not your focus to keep those documents up2date all the time as it involves some work. But I find it confusing that there is a section on the support pages that shows some but not all EoS things.

These are the lists we currently have internally:
![image](https://github.com/dotnet/core/assets/940619/95b753f1-0646-47bc-a110-6d0f3447e37f)
![image](https://github.com/dotnet/core/assets/940619/e456ba35-802e-47e0-9fa1-9b983cd66a86)
![image](https://github.com/dotnet/core/assets/940619/53f11059-c9d9-4703-8b43-d43d672dd28f)
![image](https://github.com/dotnet/core/assets/940619/ca7fa000-6996-4ffb-95d1-cc4eec269062)
You can ignore the light-red on .NET 7 and .NET 8 columns since these only have the internal meaning of "available without change but currently not used by us as we target .NET 6 LTS in our product". The dark-red means, there was a change in support towards the previous version.
The light-blue on "Upcoming EoS" means it's less then 1-2 months away. Dark-blue means EoS was already reached on .NET 6 for the one listed on the documentation page whereas the colum might already show the next upcoming EoS for that OS.

We also track the EoS OS (only those that were in support any time we used it):
OS | Version | End of Life
-- | -- | --
Windows 7 (SP 1) | ESU 3 | 01/10/2023
Windows 8.1 | All | 01/10/2023
Windows 10 | 1703 | 10/08/2019
Fedora | 30 | 05/26/2020
Fedora | 31 | 11/24/2020
Fedora | 32 | 05/25/2021
Fedora | 34 | 12/31/2021
Fedora | 35 | 12/13/2022
Fedora | 36 | 05/16/2023
Fedora | 3.8 | 05/01/2020
Alpine | 3.12 | 05/22/2022
Alpine | 3.13 | 11/01/2022
Alpine | 3.14 | 05/08/2023
Alpine | 3.15 | 11/01/2023
Ubuntu | 18.04 | 05/31/2023
Ubuntu | 19.04 | 01/23/2020
Ubuntu | 19.10 | 07/17/2020
Ubuntu | 20.10 | 07/22/2021
Ubuntu | 21.04 | 01/20/2022
Ubuntu | 21.10 | 07/14/2022
Ubuntu | 22.10 | 07/20/2023
RHEL | 6 | 11/30/2020
macOS | 10.13 | 09/13/2021
macOS | 10.14 | 11/13/2021
macOS | 10.15 | 09/12/2022
openSUSE Linux | 15.3 | 12/01/2022
iOS | 10 | 09/26/2017
iOS | 11 | 10/08/2018
iOS | 13 | 09/16/2020
iOS | 14 | 10/01/2022
CentOS Linux | 8 | 12/31/2021
SUSE Enterprise Linux | 12 SP2 | 03/31/2021
SUSE Enterprise Linux | 12 SP3 | 06/30/2022
SUSE Enterprise Linux | 12 SP4 | 06/30/2023

We have somethine similar for .NET Framework in general (.NET 1.x to .NET 4.x is of course .NET Framework, only shortened for overview purposes):
![image](https://github.com/dotnet/core/assets/940619/e39925ab-91c1-44ae-b3cd-9ffa90667ebf)

And a second one (collapsed for better overview) from past versions that we might still have terminals in the wild we ran on:
![image](https://github.com/dotnet/core/assets/940619/8065e123-1cde-457a-a205-a50c2db21a5e)
The light bulb singalizes if the .NET runtime or OS is still in support or not by Microsoft. Green ticks mean supported by OS, green with stars is supported through backwards compatability by newer installed version, yellow means supported but not pre-installed and red means not supported.

**Comment by richlander** [comment]
Is it possible you could help us maintain this information in a way that would help your downstream scenario?

**Comment by Falco20019** [comment]
> Is it possible you could help us maintain this information in a way that would help your downstream scenario?

I really like the approach that you follow with the [release.json](https://github.com/dotnet/core/blob/main/release-notes/8.0/releases.json) files including CVEs. Maybe this could fit in there as having a list of `supported-os` on the same level as `releases`. I'm open to have discussions with you, the team and/or the community on that topic.

**Comment by xtqqczze** [comment]
Fixed by https://github.com/dotnet/core/pull/9294?

**Comment by Falco20019** [comment]
Yes, I will close it.
