### ISSUE TITLE
desktop % dotnet new console -o MyApp -f net7.0    It was not possible to find any installed .NET Core SDKs   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:       https://aka.ms/dotnet-download

### ISSUE THREAD

**Issue by Collinsamazon** [dotnet/core#8889]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Sorry to hear you're running into trouble @Collinsamazon. Have you installed the SDK as instructed in the previous step? What kind of macOS do you have and can you tell me which version is showing for you on the install step at https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install? 
If you did install, did you open a new terminal after the installation?

**Comment by Collinsamazon** [comment]
Hello,

Yes i have installed the SDK and followed the steps in the documentation, however... fails when i run the dotnet new console -o MyApp -f net7.0 command 

Also i am trying to use .Net for my CDK project. This has been an issue for me for over a year now

**Comment by mairaw** [comment]
Can you run `dotnet --info` on the terminal? Just to see what it recognizes on your machine.

I'm not familiar with CDK.

This article should also help to check to see if things are installed:
https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos

**Comment by mairaw** [comment]
Also, we need to make sure you have installed the right version of .NET for your machine. Do you have a M1/M2 machine? What version of the SDK have you installed?

**Comment by sponge1220** [comment]
I would recommend using brew to install dotnet.
https://formulae.brew.sh/cask/dotnet

This reduces a lot of problems, I've been using brew to install dotnet for about 2 years now, I use a Macbook M1.
