### ISSUE TITLE
3S26cel2fah

### ISSUE THREAD

**Issue by s13752** [dotnet/core#8891]
Start
|
—> "Input temp in Celsius (non-
negative no):"
GET cel
|
Loop
|
Yes    cel>=0 and Is Number
(cel)
|   NO
PUT Invalid input Try
again!"
|
—>     “Input temp in Celsius again
(non-negative no):"
GET cel
|
fah-cel 9/5 +32
|
PUT The temp in Fahrenheit
is: +fah                      —>
|
End

**Comment by s13752** [comment]
> Start
> |
> —> "Input temp in Celsius (non-
> negative no):"
> GET cel
> |
> Loop
> |
> Yes cel>=0 and Is Number
> (cel)
> | NO
> PUT Invalid input Try
> again!"
> |
> —> “Input temp in Celsius again
> (non-negative no):"
> GET cel
> |
> fah-cel 9/5 +32
> |
> PUT The temp in Fahrenheit
> is: +fah —>
> |
> End

**Comment by mairaw** [comment]
Not clear what this issue is about. Closing.
