### ISSUE TITLE
nao consigo abrir e rodar pasta de projeto

### ISSUE THREAD

**Issue by Manoelah20** [dotnet/core#8895]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Manoelah20** [comment]
nao consigo abrir pasta e projeto no visual code em c#...pasta salva e arquivo pronto

**Comment by mairaw** [comment]
Aparece alguma mensagem de erro?
Qual foi a pasta que você selecionou para salvar seu projeto?

**Comment by Manoelah20** [comment]
Maira, agradeço seu retorno, consegui resolver.

Em sáb., 11 de nov. de 2023 às 17:19, Maira Wenzel ***@***.***>
escreveu:

**Comment by mairaw** [comment]
Que bom @Manoelah20
