### ISSUE TITLE
build is successfull but nothing is being played only static cube isn present

### ISSUE THREAD

**Issue by AKHILESH200** [dotnet/core#8896]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/games/unity-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by krwq** [comment]
Hello @AKHILESH200, this issue belong to unity: https://unity.com/releases/editor/qa/bug-reporting - I'll close this issue since we won't be able to help and I don't have ability to transfer.
