### ISSUE TITLE
zsh: 命令未找到: dotnet

### ISSUE THREAD

**Issue by Yaxnice301** [dotnet/core#8899]
I'm a student.  I have no idea to fix this problem.  I need help and help and help and help.  Thank you , VERY MUCH!!!

**Comment by Yaxnice301** [comment]
Mac OS  sonoma 14.0

**Comment by krwq** [comment]
Hello @Yaxnice301, you will need to install dotnet first :-) You can get it here: https://dotnet.microsoft.com/en-us/download

**Comment by Yaxnice301** [comment]
[detail](https://youtu.be/fUINMPaXl1I?si=fdCcD7Jm-wi-_FjS)
Do you need more info , bro? 
Should I install it again?

**Comment by krwq** [comment]
I think it should work if you simply do `brew install --cask dotnet-sdk` in your terminal. I'm not sure it will add it to PATH though (I don't have macos handy to check).

If it doesn't (the error you're currently seeing) see instructions under the steps:
![image](https://github.com/dotnet/core/assets/660048/49e375b2-8389-4924-ae69-18dc6a567eec)

Note that using `export` is per session - if you close terminal you'll need to export variable again.

To make this permanent you can edit .zshrc/.zprofile (that will make it work only on zsh) or you can edit `/etc/paths` to make this change permanent for any terminal, example article about how to do that is here: https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion

before following that please make sure that it works in your terminal when you just change PATH.

You can also follow: https://learn.microsoft.com/en-us/dotnet/core/install/macos which contains what I just wrote in more details.
