### ISSUE TITLE
.NET 8 (LTS) (Early Access) listed in App Service .NET Version dropdown, doesn't enable .NET 8

### ISSUE THREAD

**Issue by jledgett** [dotnet/core#8914]
**.NET 8 (LTS) (Early Access)** is listed in the _.NET Version_ dropdown of a Windows App Service:

![image](https://github.com/dotnet/core/assets/49896897/c69f586b-1a85-4bee-bddf-51917d7fca6c)

However, selecting this option appears to do absolutely nothing.

Enabling it, restarting the service, and deploying a .NET 8 Core app to the app service will simply result in a _HTTP Error 500.31 - ANCM Failed to Find Native Dependencies_

Instead you need to install via an extension as outlined here: https://learn.microsoft.com/en-us/answers/questions/1303909/when-will-net-8-be-available-on-azure-app-services

This is user unfriendly and an unexpected behavior.   As .NET 8 is marked as generally available and the LTS version, it should be normal access now and should automatically be enabled when **.NET 8 (LTS)** is selected from the _.NET Version_ dropdown.

**Comment by krwq** [comment]
I think this is a VS issue, can you open a ticket here: https://developercommunity.visualstudio.com/content/problem/post.html?space=8 ?

**Comment by jledgett** [comment]
@krwq  This is **not** a Visual Studio / Visual Studio code issue.  The code builds and runs correctly.   It is an issue with how the Microsoft team is provisioning the .NET 8 SDK within an Azure App Service.  

Unfortunately, they do not appear to maintain an appropriate GitHub repo for this and technical issues would require me to pay for a separate support plan just to point out the issue.   

I am not sure if someone on the internal Microsoft .NET team can forward this on to the appropriate Azure support team, or if they are so siloed that isn't feasible.

**Comment by aviita** [comment]
> @krwq This is **not** a Visual Studio / Visual Studio Code issue. The code builds and runs correctly. It is an issue with how the Microsoft team is provisioning the .NET 8 SDK within an Azure App Service.
> 
> Unfortunately, they do not appear to maintain an appropriate GitHub repo for this and technical issues would require me to pay for a separate support plan just to point out the issue.
> 
> I am not sure if someone on the internal Microsoft .NET team can forward this on to the appropriate Azure support team, or if they are so siloed that isn't feasible.

You could also use [Azure Support account on twitter](https://x.com/AzureSupport). Usually they open a private chat. I do not think they care if it is paid support customer or not. Might be that they have more light weight support than the paid support, but might be worth something. I often go to twitter before contacting Azure support from portal as it is faster to see some status there and might get replies also from others following the same channel.

**Comment by jledgett** [comment]
@aviita  Fortunately, I no longer have a Twitter/X account -- so that is not an option for me.

**Comment by krwq** [comment]
@richlander can you help redirect this?

**Comment by btardif** [comment]
hey @jledgett are you still seeing this? Given your post was early on the 14th chances are the specific vm hosting your app might have not yet picked up the change that was pushed in the morning to enable this. However things should have normalized later that same day.

**Comment by jledgett** [comment]
Site is running, but you have to manually add the extension to get it to work.

On Nov 20, 2023, at 5:18 PM, Byron Tardif ***@***.***> wrote:

﻿

hey @jledgett<https://github.com/jledgett> are you still seeing this? Given your post was early on the 14th chances are the specific vm hosting your app might have not yet picked up the change that was pushed in the morning to enable this. However things should have normalized later that same day.

**Comment by btardif** [comment]
@jledgett what do you mean by "manually add the extension"

**Comment by jledgett** [comment]
> @jledgett what do you mean by "manually add the extension"

It was outlined in the original question, but basically see: https://learn.microsoft.com/en-us/answers/questions/1303909/when-will-net-8-be-available-on-azure-app-services

I get having to do this before .NET is fully released, but it should no longer be the case once .NET 8 shows up in the dropdown.   Selecting .NET 8 from the dropdown should immediately activate .NET 8
