### ISSUE TITLE
Conflicting information between .NET 8 installer and webpage regarding the minimally required Visual Studio version

### ISSUE THREAD

**Issue by ryankangas** [dotnet/core#8915]
### Description

The .NET 8 "thank you" page for .NET 8.0.100 states: "Using Visual Studio? This release is only compatible with Visual Studio 2022 (v17.8)." The actual installer (x64) downloaded from this page states: "If you plan to use .NET 8.0 with Visual Studio, Visual Studio 2022 17.7.0 or newer is required." [Here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.100-windows-x64-installer) is the relevant page. I'm not sure what the actual minimum version required to use .NET 8 with Visual Studio 2022 is, as there is a conflict between the two sources of information.

Here is a screenshot highlighting the difference:
![conflicting-vs-versions](https://github.com/dotnet/core/assets/71091814/cfdcb869-dc4a-43d9-852e-8a2dc7d7d2bb)

### Configuration

x64 installer, Windows 10 Enterprise 22H2, Firefox 119.0.1 (x64)

**Comment by leecow** [comment]
@NikolaMilosavljevic

**Comment by ryankangas** [comment]
Self-discovered that this is a duplicate dotnet/installer#17770
