### ISSUE TITLE
Need to upgrade Package Microsoft.VisualStudio.Web.CodeGeneration.Design

### ISSUE THREAD

**Issue by omarceloribeiro** [dotnet/core#8916]
### Description
Please this package need to be upgraded too. it is still in release candidate and is blocking a project MVC created in .Net 7 to be upgraded to .Net 8
https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/

`
Error   NU1107  Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.5.0 directly to project Project.Web.MVC to resolve this issue. 

 Project.Web.MVC -> Project.Infra.Data -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0) 
 Project.Web.MVC -> Microsoft.VisualStudio.Web.CodeGeneration.Design 7.0.11 > Microsoft.DotNet.Scaffolding.Shared 7.0.11 -> Microsoft.CodeAnalysis.CSharp.Features 4.4.0 -> Microsoft.CodeAnalysis.Common (= 4.4.0)
`
No workarounds.
The solution  suggested in the error message didn't work

### Configuration
.Net 8.0.0

### Regression?

Works if rollback all projects to .Net 7

### Other information

No workarounds.
The solution  suggested in the error message didn't work

**Comment by omarceloribeiro** [comment]
**Solved setting this verison**
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0-rc.2.23509.1" />

**Comment by vlardn** [comment]
Please fix `Microsoft.EntityFrameworkCore.Design` too as it generates the same error:
```
ERROR NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly to project Common to resolve this issue. 
 Common -> Microsoft.CodeAnalysis.CSharp 4.8.0 -> Microsoft.CodeAnalysis.Common (= 4.8.0) 
 Common -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).
```

**Comment by omarceloribeiro** [comment]
> Please fix `Microsoft.EntityFrameworkCore.Design` too as it generates the same error:
> 
> ```
> ERROR NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly to project TestProject to resolve this issue. 
>  TestProject -> Microsoft.CodeAnalysis.CSharp 4.8.0 -> Microsoft.CodeAnalysis.Common (= 4.8.0) 
>  TestProject -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).
> ```

I could fix that kind of inner reference by going to Manage Nuget Packege -> Installed -> scroll all the way down to transitive package, then find the package with the old version, then update to last version.
they already released all the packages to .net 8 version, so no errors should be displaying anymore.

**Comment by mairaw** [comment]
@villelaitila I'd suggest you open a new issue since this issue is closed and unrelated to your question (other than the package name).
