### ISSUE TITLE
help

### ISSUE THREAD

**Issue by deaniebeanieboi123** [dotnet/core#8918]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
PS C:\Users\kayla> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundExc 
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by leecow** [comment]
Seems like perhaps you have not installed .NET? If this is the case, visit https://dot.net and choose 'Download'.
