### ISSUE TITLE
After install, .Net 8.0 not appear on Project Properties/Target Framework

### ISSUE THREAD

**Issue by minhdqtt** [dotnet/core#8920]
### Description
I downloaded from .net official web, installed success, but when I open old project, go to Project Properties/Target Framework, the NET 8.0 didn't appear (Windows 11/Visual Studio 2022)

Open terminal
dotnet --info-sdks
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---info-sdks does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by minhdqtt** [comment]
After update Visual Studio to version v17.8, re-install net 8, nothing changed. .NET 8.0 still not found in Target Framework select box

**Comment by jihadkhawaja** [comment]
Same here

**Comment by jihadkhawaja** [comment]
@minhdqtt Make sure you don't have any global.json set in your solution root folder.

**Comment by NessfertIndia** [comment]
@minhdqtt Any luck with this yet?  
Still .net 8 Preview is showing from visual studio 
From command prompt 
C:\Users\mathew>dotnet --info
.NET SDK:
 Version:           8.0.100

For me I created a simple ToDo Blazor Web Project and i was getting an error saying 

**_The type or namespace name 'MyToDo' could not be found (are you missing a using directive or an assembly reference?)	MyToDo	D:\LabWorks\Net8\MyToDo\MyToDo\MyToDo\Program.cs	2_**

**Comment by wingradirect** [comment]
.Net 8 only works with VS 2022 version 17.8+. I also saw .net 8.0 preview until I upgraded Visual Studio to the most current stable release.

Note: Some of the features they demo in the .Net Conf 2023 are only be available in VS 2022 Preview (v17.9), such as scaffolding "Blazor Components from Entity Framework".

**Comment by ryanlpoconnell** [comment]
Anyone with a link to download VS 17.8 (but for **Mac**)

**Comment by mairaw** [comment]
@ryanlpoconnell You can still find VS for Mac download button under All downloads at https://visualstudio.microsoft.com/downloads/

But you can check the other options we're currently recommending to folks at
https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/

**Comment by ryanlpoconnell** [comment]
@mairaw thanks, but the problem is that I cannot use .net 8 framework in VS for Mac.

I now realise there is no vs for mac version 17.8.

I have followed the steps here and still cannot select .net as a target framework:
https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vsmac

![Screenshot 2023-11-22 at 09 11 49](https://github.com/dotnet/core/assets/18209358/92f15308-ae04-4069-aab7-9259f32dbfb8)

**Comment by ryanlpoconnell** [comment]
After much agony... VS for Mac now shows .Net 8 framework as installed.
After following these instructions ... : 
https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vsmac

... The missing key was to enable Preview features (not in above documentation)
![Screenshot 2023-11-22 at 10 25 36](https://github.com/dotnet/core/assets/18209358/18d88014-bf3a-46a2-b74f-2e5ce08cba96)

To be clear, this is with the full .Net 8 release (not preview) installed:

 dotnet --list-sdks
3.1.102 [/usr/local/share/dotnet/sdk]
3.1.200 [/usr/local/share/dotnet/sdk]
3.1.201 [/usr/local/share/dotnet/sdk]
3.1.300 [/usr/local/share/dotnet/sdk]
3.1.301 [/usr/local/share/dotnet/sdk]
3.1.302 [/usr/local/share/dotnet/sdk]
3.1.402 [/usr/local/share/dotnet/sdk]
3.1.404 [/usr/local/share/dotnet/sdk]
3.1.407 [/usr/local/share/dotnet/sdk]
3.1.408 [/usr/local/share/dotnet/sdk]
3.1.409 [/usr/local/share/dotnet/sdk]
3.1.410 [/usr/local/share/dotnet/sdk]
3.1.411 [/usr/local/share/dotnet/sdk]
3.1.412 [/usr/local/share/dotnet/sdk]
3.1.413 [/usr/local/share/dotnet/sdk]
3.1.415 [/usr/local/share/dotnet/sdk]
3.1.416 [/usr/local/share/dotnet/sdk]
3.1.417 [/usr/local/share/dotnet/sdk]
3.1.418 [/usr/local/share/dotnet/sdk]
3.1.419 [/usr/local/share/dotnet/sdk]
3.1.420 [/usr/local/share/dotnet/sdk]
3.1.422 [/usr/local/share/dotnet/sdk]
3.1.425 [/usr/local/share/dotnet/sdk]
3.1.426 [/usr/local/share/dotnet/sdk]
5.0.100 [/usr/local/share/dotnet/sdk]
5.0.201 [/usr/local/share/dotnet/sdk]
5.0.202 [/usr/local/share/dotnet/sdk]
5.0.203 [/usr/local/share/dotnet/sdk]
5.0.301 [/usr/local/share/dotnet/sdk]
5.0.302 [/usr/local/share/dotnet/sdk]
5.0.400 [/usr/local/share/dotnet/sdk]
5.0.401 [/usr/local/share/dotnet/sdk]
5.0.403 [/usr/local/share/dotnet/sdk]
5.0.404 [/usr/local/share/dotnet/sdk]
5.0.405 [/usr/local/share/dotnet/sdk]
5.0.406 [/usr/local/share/dotnet/sdk]
5.0.407 [/usr/local/share/dotnet/sdk]
5.0.408 [/usr/local/share/dotnet/sdk]
6.0.400 [/usr/local/share/dotnet/sdk]
6.0.403 [/usr/local/share/dotnet/sdk]
6.0.404 [/usr/local/share/dotnet/sdk]
6.0.405 [/usr/local/share/dotnet/sdk]
6.0.406 [/usr/local/share/dotnet/sdk]
6.0.407 [/usr/local/share/dotnet/sdk]
6.0.408 [/usr/local/share/dotnet/sdk]
6.0.410 [/usr/local/share/dotnet/sdk]
6.0.412 [/usr/local/share/dotnet/sdk]
6.0.417 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]
7.0.101 [/usr/local/share/dotnet/sdk]
7.0.102 [/usr/local/share/dotnet/sdk]
7.0.103 [/usr/local/share/dotnet/sdk]
7.0.200 [/usr/local/share/dotnet/sdk]
7.0.202 [/usr/local/share/dotnet/sdk]
7.0.203 [/usr/local/share/dotnet/sdk]
7.0.302 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
7.0.311 [/usr/local/share/dotnet/sdk]
8.0.100 [/usr/local/share/dotnet/sdk]

**Comment by gavin1970** [comment]
> @mairaw thanks, but the problem is that I cannot use .net 8 framework in VS for Mac.
> 
> I now realise there is no vs for mac version 17.8.
> 
> I have followed the steps here and still cannot select .net 8 as a target framework: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vsmac
> 
> ![Screenshot 2023-11-22 at 09 11 49](https://private-user-images.githubusercontent.com/18209358/284850681-92f15308-ae04-4069-aab7-9259f32dbfb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MzExMTEsIm5iZiI6MTcwMjgzMDgxMSwicGF0aCI6Ii8xODIwOTM1OC8yODQ4NTA2ODEtOTJmMTUzMDgtYWUwNC00MDY5LWFhYjctOTI1OWYzMmRiZmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE2MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZjY5YjcyODk0M2Y5ZDI5ZmIyYWY4YWJiMWRlODRhMzdmY2Y5NmJjMmIxY2EwYzg5MjczYWIxYTc0OTM5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x25kv_Y3FHa5RqN86kA65D77Y0nbBsA94sGjvgpaibk)

I'm on Windows 11 running Visual Studio 2022 v17.7.6 and when I went to find latest, it shows v17.7.7 is the latest.
![image](https://github.com/dotnet/core/assets/31280229/21734e40-5b50-4a7f-becb-8da89a7d1baf)

**Comment by elementum** [comment]
I'm on Mac M1 and I'm not using visual studio. I had had 7.0301 installed prior to installing 8.0.101
After installation, the 8.0.101 was not on the list of `dotnet --list-sdks`

It turned out that 7.0.301 version was located at /usr/share/local/dotnet/x64, whereas 8.0.101 at /usr/share/local/dotnet
Also 7.0.301 dotnet binary was located at /usr/share/local/bin which made it a default dotnet version on the machine (because being a part of the PATH).

So what I've done is:

1. removed dotnet from /usr/share/local/bin
2. added /usr/share/local/dotnet to PATH
3. restarted the machine (or reload PATH)

Now the default dotnet version 8.0.101.

So at the end of the day, the problem was having installed .net x64 version and arm versions side by side, i guess.

**Comment by jssuthahar** [comment]
To use Visual Studio for Mac with .NET 8, enable the Visual Studio > Preferences > Other > Preview Features > Use the .NET 8 SDK if installed (requires restart) checkbox.
