### ISSUE TITLE
No Blazor template appears

### ISSUE THREAD

**Issue by jabegines** [dotnet/core#8927]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/create
Operating System: windows

When you type Blazor in the search box, no project template appears. I am using Visual Studio 2022 Version 17.8.0

**Comment by leecow** [comment]
Can you confirm the "ASP.NET and web development" workload is installed? You can check this by running the Visual Studio Installer and choosing 'Modify'. 

![Screenshot 2023-11-16 151716](https://github.com/dotnet/core/assets/2212879/878f531d-1192-4bda-a526-78c3f6ecb502)

**Comment by jabegines** [comment]
Yes, the "ASP.NET and web development" is installed

**Comment by jabegines** [comment]
Fixed by reinstalling Visual Studio 2022 again and previously fixing issues with Microsoft Visual C++ 2022 X86

**Comment by jabegines** [comment]
Thanks for the help
