### ISSUE TITLE
This step needs an import of  IntroToBlazor.Client.Pages

### ISSUE THREAD

**Issue by orlandosyv** [dotnet/core#8928]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add
Operating System: windows

This step needs the import :  @using IntroToBlazor.Client.Pages

could be located on _Imports.razor, at least now it works for me.

**Comment by krwq** [comment]
cc: @danroth27

**Comment by danroth27** [comment]
Hi @orlandosyv. It looks like you also enabled the interactive WebAssembly render mode, or maybe Auto, which moves the Counter component to the client project and into a different namespace than the Home component. But if you leave the default options, which only enable interactive Server rendering, then adding the using directive shouldn't be necessary.
