### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run Operating System: macos

### ISSUE THREAD

**Issue by ealagoz** [dotnet/core#8930]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The following frameworks were found:
  7.0.14 at [/Users/.../dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=osx.11.0-x64
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[24724] ConsoleApp1' has exited with code 150 (0x96).

**Comment by leecow** [comment]
Interesting. That looks like you have an app targeting the 8.0.0 runtime but have 7.0.14 installed. You can install 8.0 from https://dotnet.microsoft.com/en-us/download.

**Comment by ealagoz** [comment]
thanks.
