### ISSUE TITLE
找不到.NET Core SDK的位置

### ISSUE THREAD

**Issue by LucasBC624** [dotnet/core#8931]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by krwq** [comment]
Hey @LucasBC624, please make sure you've installed dotnet https://dotnet.microsoft.com/en-us/download
