### ISSUE TITLE
dotnet is not recognized

### ISSUE THREAD

**Issue by EkareGenji** [dotnet/core#8932]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I  followed the .NET Tutorial and at the end when writing dotnet it doesnt recognize the name i refreashed a few times and even restarted my pc but it still didnt work

**Comment by krwq** [comment]
Please make sure you've installed dotnet: https://dotnet.microsoft.com/en-us/download

**Comment by mairaw** [comment]
Do you see .NET on the install folders?
https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows#check-for-install-folders

Have you installed the .NET SDK?
