### ISSUE TITLE
receive an error message saying "Your connection is not private" with error code NET::ERR_CERT_INVALID

### ISSUE THREAD

**Issue by Affan8888** [dotnet/core#8934]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Did you follow the instructions on the bottom for this error?

_If you receive an error message saying "Your connection is not private" with error code NET::ERR_CERT_INVALID, try to restart all browser windows so the new certificate can be picked up by the browser and run the application again._
