### ISSUE TITLE
Docs refer to `Index.razor` instead of `Home.razor`

### ISSUE THREAD

**Issue by glen-84** [dotnet/core#8937]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/run
Operating System: windows

The docs refer to `Index.razor` instead of `Home.razor`. I guess it must have been renamed.

.NET 8

**Comment by mairaw** [comment]
Good catch @glen-84! We'll get that fixed shortly. Indeed it was renamed.
