### ISSUE TITLE
>.NET: new project does not appear when I click ctrl + shift + p  and type '>.NET: new project' in

### ISSUE THREAD

**Issue by micaariccardi** [dotnet/core#8938]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Have you installed the C# Dev Kit extension as explained on the previous step?
