### ISSUE TITLE
Blazor App Tutorial: Failed to load resource: the server responded with a status of 404 () for "name".styles.css

### ISSUE THREAD

**Issue by RiQ4** [dotnet/core#8939]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows 10

Error: 
![image](https://github.com/dotnet/core/assets/51099642/bc509405-c639-44ca-bdcc-5f6101891f21)

Page looks nothing like the example. It Looks like this:
![image](https://github.com/dotnet/core/assets/51099642/058b85d3-bc69-4b2c-b9aa-0bcde34d9963)

I have not touched anything, just running all like the example says on the page mentioned above.

**Comment by mairaw** [comment]
@danroth27 can you help here?

**Comment by quintendc** [comment]
I got something similar, are you using app.UsePathBase()? Seems like their is an issue with the middleware.
I fixed it by adding the following to the App.razor:
`<base href="@(typeof(Program).Assembly.GetName().Name)/">`

**Comment by danroth27** [comment]
@RiQ4 I believe you're hitting this problem because you have a space in your project name. Can you please try creating a new project without any spaces in the project name?

**Comment by RiQ4** [comment]
@quintendc Nope. I wasn't using app.UsePathBase() and the line of code didn't do anything, but thanks for your help.

Issue was fixed with the solution given by @danroth27. Thanks everyone.

**Comment by Borek78** [comment]
For me, deleting the blank space in the name of the app worked.
