### ISSUE TITLE
Running any command in 2.0 causes trackpad to switch to 'scroll history'

### ISSUE THREAD

**Issue by mattcanty** [dotnet/core#894]
I am - albeit experimentally - using Cloud9 IDE. I have just installed the latest version of .Net Core, and pulled down a repository I know works locally.

When I run any `dotnet` command, the terminal settings change. The trackpad begins scrolling through the command history instead of _normal_ scrolling.

Not sure if this is a problem with .Net Core or Cloud9 so I'll be posting over on their forum as well.

Appreciate any help. If anyone else is facing this issue, use this command to repair the issue:

`tput reset`

[Cloud9 Community Topic](https://community.c9.io/t/dotnet-core-commands-cause-trackpad-to-switch-to-history-scrolling/18311)

**Comment by leecow** [comment]
@nguerrera , can you have a look?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #7781](https://github.com/dotnet/cli/issues/7781) via [**ZenHub**](https://www.zenhub.com/)
