### ISSUE TITLE
无法出现 hello world

### ISSUE THREAD

**Issue by sakura920070** [dotnet/core#8941]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
无法出现 hello world

**Comment by rzikm** [comment]
What is the exact command you are running and which directory? Can you share the verbatim result of the `dotnet run` command?
