### ISSUE TITLE
Error ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY when running Hello, World app.

### ISSUE THREAD

**Issue by chrisjbreisch** [dotnet/core#8942]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Windows 11
Visual Studio 2022
.NET 8
Microsoft Edge 119.0.2151.72

When running the first app using https, I get the following error message:
Hmmm… can't reach this page
It looks like the webpage at https://localhost:7009/ might be having issues, or it may have moved permanently to a new web address.
ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

Running with http or IIS Express works fine. IIS Express also uses https but a different port.

**Comment by chrisjbreisch** [comment]
Discovered there were two App URLs in the https->Blazor App Debug Properties->https->App URL field.
Deleted the first one. Working now.

**Comment by mairaw** [comment]
Did you do other steps that could have gotten you to that state? Just wondering if there's something we need to explain better in the tutorial.

/cc @danroth27

**Comment by danroth27** [comment]
Having two app URLs configured (one HTTPS and one HTTP) for the https launch profile is normal and expected. For some reason, the browser doesn't like the transport security on the request.

@adityamandaleeka Have you seen any similar reports to this?

@chrisjbreisch Does this happen with every new Blazor Web App you create? Can you please run `dotnet dev-certs https --check` from the command-line and share with us the output?
