### ISSUE TITLE
Problem running .net

### ISSUE THREAD

**Issue by harizedd** [dotnet/core#8945]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 
![Screenshot_1](https://github.com/dotnet/core/assets/60337063/9b12e4d4-be23-4330-82b4-e6c50eef8b4f)

**Comment by mairaw** [comment]
Have you downloaded the .NET SDK as instructed in the install step? If so, can you run `dotnet --info` on the terminal and share the results with us?
