### ISSUE TITLE
ProductVersion started to behave differently with .NET 7.0.14 SDK

### ISSUE THREAD

**Issue by mocakturk** [dotnet/core#8950]
### Description

Here the csproj file:
```
    <AssemblyVersion>6.0.0.0</AssemblyVersion>
    <FileVersion>6.0.0.0</FileVersion>
    <InformationalVersion>6.0.0</InformationalVersion>
```

_Application.ProductVersion_ value was "**6.0.0**" when I was using VS 17.7.X and **.NET 7.0.11**.
_Application.ProductVersion_ is "**6.0.0+5231379ecee3b2a3134803a16a1d1bfa339d912a**" when I'm using VS 17.8.0 and **.NET 7.0.14**.

Issue can be seen in below code as well:
```
var productVersion = FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetEntryAssembly().Location).ProductVersion;
// it should be "6.0.0"
// but it is "6.0.0+5231379ecee3b2a3134803a16a1d1bfa339d912a"
```

### Configuration

It is a .NET7 WinForms application.
My PC is Windows 10 x64.
My runtime identifier is win-x86.

### Regression?

Yes it is regression. _Application.ProductVersion_ value was correct when .NET 7.0.11 was used.

**Comment by rzikm** [comment]
@dsplaisted Can you please have a look? Or tag a better person to check the issue.

**Comment by bluebat-swiss** [comment]
I have the same problem. The MSDN documentation does not define a GUID part.
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo.productversion?view=net-8.0

**Comment by brunofrance** [comment]
I have the same proble

**Comment by svick** [comment]
I believe this is caused by [this documented breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link). If you want to revert to the previous behavior, set `<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>` in your project file.

**Comment by brunofrance** [comment]
Thanks svick
solutionned using FileVersionInfo.GetVersionInfo(Application.ExecutablePath).FileVersion;

**Comment by bluebat-swiss** [comment]
I solved it by creating my own method:

        Private Version BuildProductVersion()
        {
            var vers = FileVersionInfo.GetVersionInfo(Assembly.GetEntryAssembly().Location);
            if (vers.ProductBuildPart > 0 && vers.ProductPrivatePart > 0)
                return new Version(vers.ProductMajorPart, vers.ProductMinorPart, vers.ProductBuildPart, vers.ProductPrivatePart);
            if (vers.ProductBuildPart > 0)
                return new Version(vers.ProductMajorPart, vers.ProductMinorPart, vers.ProductBuildPart);
            return new Version(vers.ProductMajorPart, vers.ProductMinorPart);
        }

**Comment by dsplaisted** [comment]
Thanks @svick for linking to the breaking change documentation for this.
