### ISSUE TITLE
你的连接不是专用连接

### ISSUE THREAD

**Issue by Carey-Chao** [dotnet/core#8951]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Google translate: "Your connection is not a private connection"

When exactly are you seeing this message, during which step of the tutorial?

**Comment by mairaw** [comment]
Did you try this as explained in the bottom?

遇到错误?
如果收到错误消息“你的连接不是专用的”，错误代码为 NET::ERR_CERT_INVALID，请尝试重新启动所有浏览器窗口，以便浏览器可以选取新证书，然后再次运行应用程序。

如果无法解决遇到的问题，请选择下面的“我遇到了问题”按钮，以获取解决问题的帮助。

**Comment by wfurt** [comment]
```dotnet dev-certs https --trust``` ?You can probably also trust  the certificate directly in the browser @Carey-Chao
