### ISSUE TITLE
Unable to restore projects when building the image

### ISSUE THREAD

**Issue by naiksrinivas** [dotnet/core#8955]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

I have been following the tutorial in the above link. When running the `docker build -t mymicroservice .` command, I get the following error : 

```
 > [build 4/6] RUN dotnet restore:
0.467   Determining projects to restore...
8.069 /src/MyMicroservice.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
15.25 /src/MyMicroservice.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
22.61 /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/MyMicroservice.csproj]
22.61 /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error :   The SSL connection could not be established, see inner exception. [/src/MyMicroservice.csproj]
22.61 /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error :   The remote certificate is invalid because of errors in the certificate chain: NotSignatureValid, UntrustedRoot [/src/MyMicroservice.csproj]
```

What could be the source of this issue? I tried updating the dns entries to "8.8.8.8" in the docker settings file based on some other similar questions posted before but that does not seem to help. 
I get this error whether I am within my corporate VPN or not.

Please help. Thanks!

**Comment by rzikm** [comment]
@jamesmontemagno, @bradygaster can you please have a look?

**Comment by DmitryLukyanov** [comment]
Might be related to this one https://github.com/dotnet/core/issues/9012

**Comment by jamesmontemagno** [comment]
Q: When you do `dotnet run` does that compile and run?

I just went through the tutorial and it seemed to work for me. Only thing I can think of is that your machine isn't on TLS 1.2? https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/
