### ISSUE TITLE
Usage: dotnet [options] Usage: dotnet [path-to-application]  Options: -h|--help         Display help. --info            Display .NET information. --list-sdks       Display the installed SDKs. --list-runtimes   Display the installed runtimes.  path-to-application: The path to an application .dll file to execute.

### ISSUE THREAD

**Issue by Bsheerali4** [dotnet/core#8957]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
On which step of the turorial did you encounter the error?
