### ISSUE TITLE
Setup of .NET Core SDK 2.0.0 x64 is hanging

### ISSUE THREAD

**Issue by torhovland** [dotnet/core#896]
The progress is simply stuck about one third in. Even cancelling the setup is hanging now.

Is there a log file anywhere I can check?

Anyway, when I rebooted the machine the installer restarted automatically and was able to complete successfully.

I did close VS before I started the setup the first time, but I did not close VS Code.

**Comment by leecow** [comment]
@wli3 for log file existence and location.

**Comment by wli3** [comment]
@torhovland  add `/l*v log.txt` to the end of execution in command line can generate the log ex `dotnet-sdk-2.0.0-win-x64.exe /l*v log.txt`

However, I think in this case you should just wait for it. The "hanging" is extracting packages for offline scenario, on my machine, SSD, it will take about a minute, for HDD it could take 4 minutes.

**Comment by torhovland** [comment]
Thank you. It was hanging for a lot longer than 4 minutes (and I use SSD), so it was truly hanging. But as I said, a reboot fixed it.

**Comment by Petermarcu** [comment]
I don't think we can do anymore here. Sounds like its resolved. Closing.

**Comment by bartoszkp** [comment]
Happend to me as well. Unfortunately, also in my case running it again after a reboot with `/l*v log.txt` didn't allow to reproduce the issue and the package installed successfully,
