### ISSUE TITLE
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]       Failed to determine the https port for redirect.

### ISSUE THREAD

**Issue by Aksh-Talati** [dotnet/core#8960]
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
@mairaw Can you please have a look?

**Comment by mairaw** [comment]
Tagging @danroth27 for help here

**Comment by mcyenikoylu** [comment]
I'm getting the same warning. And it cannot connect to the database.

`dotnet watch -lp https`

I run the project by starting with and the sql connection is successful.

[img]https://i.imgur.com/BjiioHj.png[/img]

**Comment by mcyenikoylu** [comment]
I changed the order of HTTP and HTTPS profile definitions. And as seen in the screenshot, both ports started to work actively. However, a new WARN appeared on the console.

<a href="https://imgur.com/tMYrgrd"><img src="https://i.imgur.com/tMYrgrd.png" title="source: imgur.com" /></a>

**Comment by danroth27** [comment]
@mcyenikoylu It sounds like you need to adjust how you're setting up Entity Framework Core in your app, which isn't related to this issue. You might try StackOverflow for help with that.

Since the "Failed to determine the https port for redirect" warning is generally expected, I'm going to go ahead and close this issue.
