### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Brusantos55** [dotnet/core#8961]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/create
Operating System: windows 11

i just got an error when trying to create a .net console app, i´ve installed both dotnet sdk 8 and microsoft .net framework 4.8 developer pack, and i get the expected output when runned dotnet command on powershell but it doesn list anything when i run dotnet --list-sdks command

![Captura de pantalla 2023-11-24 180010](https://github.com/dotnet/core/assets/78025343/14e8372a-a668-4e24-995a-ae0f0baab865)

in visual studio i can create a project but not run it, there is only select starting element and attach button

![imagen](https://github.com/dotnet/core/assets/78025343/86af8d5f-482f-489e-9279-ae03c3be26a6)
![imagen](https://github.com/dotnet/core/assets/78025343/03c327df-4b72-437b-be96-1f1bc60499c8)

**Comment by rzikm** [comment]
Can you share the console output of `dotnet --info` command?

**Comment by Brusantos55** [comment]
![imagen](https://github.com/dotnet/core/assets/78025343/1e5cd2f8-0405-4f24-b98d-1eb8da7afa9d)
but i ve stalled all this latelly
![imagen](https://github.com/dotnet/core/assets/78025343/d7d3db66-04f5-4d66-98e6-75f6f9745657)

**Comment by mairaw** [comment]
From the output, there seems to be a mix of x86 and x64 installations. But your machine is probably x64 if you're running Windows 11. Please confirm that.

These instructions might be helpful in your case:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by Brusantos55** [comment]
you are right thanks really appreciate it.

**Comment by Brusantos55** [comment]
you are right, thanks really appreciate it
