### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by kesoyin** [dotnet/core#8964]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Pop up says  "there were build errors. Would you like to continue and run the last successful buidl"
I click Yes
Pop up shows this
![image](https://github.com/dotnet/core/assets/149971113/d1cab4c4-7082-49b0-9447-4089c1b6fd30)
I click Ok
Error includes: Severity	Code	Description	Project	File	Line	Suppression State
Warning	NETSDK1213	Targeting .NET 8.0 or higher in Visual Studio 2022 17.7 is not supported.	BlazorApp	C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	135

**Comment by rzikm** [comment]
Hi, if there was no previous successful build, there is no binary that can be run. Does the error go away when you fix the errors in the source code and build the application?

**Comment by mairaw** [comment]
Make sure you're on the latest version of Visual Studio as well. The error message says "Targeting .NET 8.0 or higher in Visual Studio 2022 17.7 is not supported"

You need Visual Studio 2022 17.8 to run .NET 8 applications.

**Comment by kesoyin** [comment]
How do I install packages:

Microsoft.NET.Sdk.Functions
Microsoft.WindowsDesktop.App.Ref
