### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by Tjihimise27** [dotnet/core#8967]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Tjihimise27** [comment]
InvalidOperationException: Object of type 'BlazorApp1.Components.Pages.Counter' does not have a property matching the name 'IncrementAmount'.
Windows 10 operating system 
code sample @page "/counter"
@rendermode InteractiveServer

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;
    [Parameter]
    public int IncrementAmount { get; set; } = 1;

    private void IncrementCount()
    {
        currentCount += IncrementAmount;
    }
}

**Comment by rzikm** [comment]
does this happen also when you stop the application and recompile the project? the code seems okay.

**Comment by mairaw** [comment]
@danroth27 any suggestions here? The code is the one we provide in the tutorial.

**Comment by danroth27** [comment]
Hmm, yeah, the code looks fine.

@Tjihimise27 Any chance the code changes to Counter.razor to add the `IncrementAmount` parameter just weren't saved?

**Comment by Tjihimise27** [comment]
I fixed the error. Thanks. Just restarted the project
