### ISSUE TITLE
Localhost not connecting running micro-service with docker.

### ISSUE THREAD

**Issue by dhrumilpatel30** [dotnet/core#8972]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run-docker
Operating System: macOS

MacOS version: 14.1.1 (23B81) on M2 air

I am having exact same version of micro-service and dockerfile provided in the guide. It is working perfect while running on local machine with downloaded SDK. But while running with docker it doesn't connects to localhost and I am getting following message on browser and terminal.

<img width="1470" alt="image" src="https://github.com/dotnet/core/assets/105425340/0cc52c02-581c-4eae-8db9-05ac90d7b8eb">

<img width="1470" alt="image" src="https://github.com/dotnet/core/assets/105425340/176e1e09-500b-423c-be84-7603d1eb42a7">

**Comment by dhrumilpatel30** [comment]
Follow on: same error still persist on blazor-webapp. Works completely fine on local machine SDK but have same error on running with docker. 

I think it can be issue with the fact that M chips are arm64 based or some firewall issues. I was able to run spring boot docker image on my MacBook but none of the dotnet  docker is working. 

Please help if anyone has encountered similar problem.

**Comment by dhrumilpatel30** [comment]
Follow on: I was able to run directly from docker hub with this command and it works completely fine.

```
docker run -it --rm -p 8000:8080 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp
```

**Comment by rzikm** [comment]
I assume you are running on latest .NET 8? There was a breaking change in the default port used by the ASP.NET Core (from 80 to 8080), see
https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port. We didn't update the tutorials to reflect that. Instructions from https://github.com/dotnet/core/issues/8958 should apply here.

```
docker run -it --rm -p 3000:8080 --name mymicroservicecontainer mymicroservice
```

**Comment by dhrumilpatel30** [comment]
Thanks @rzikm, It is working now.

**Comment by rzikm** [comment]
Glad it helped. I will close the issue, if you encounter other problems don't hesitate to open a new one.
