### ISSUE TITLE
No Blazor Web App Option

### ISSUE THREAD

**Issue by schleppen** [dotnet/core#8975]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: Windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything relevant.

Verified installation of the product like on the previous page. I have the following options.
1. Blazor Server App
2. Blazor WebAssembly App
3. Blazor Server App Empty
4. Blazor WebAssembly App Empty

**Comment by rzikm** [comment]
@mairaw Did perhaps the names of the template change between versions? If so, we should update the tutorials.

**Comment by mairaw** [comment]
adding @danroth27 

I believe this is the new name. Can you confirm Dan?

@schleppen what version of Visual Studio you have installed? You can confirm by opening Visual Studio Installer. The minimum version for this tutorial to work is VS 17.8. Here's what my installer looks like right now

![image](https://github.com/dotnet/core/assets/12971179/6b903501-f479-49df-bba1-a3b26e006ff1)

**Comment by danroth27** [comment]
Yup, the new Blazor template in .NET 8 is the "Blazor Web App" template. You may also see the older Blazor Server and Blazor WebAssembly templates if you also have .NET 7 installed.  .NET 8 ships in-the-box with Visual Studio 17.8, so make sure you've updated to the latest Visual Studio version.

**Comment by schleppen** [comment]
Apparently, I need to update Visual Studio.
