### ISSUE TITLE
Fedora 37 reached end-of-life on 05 - December - 2023

### ISSUE THREAD

**Issue by Falco20019** [dotnet/core#8978]
Fedora 37 reaches end of life on December 5th, 2023 This issue is created to track progress for the remove support for Fedora 37 from .NET 6.0, .NET 7.0 and .NET 8.0.

### Repos team to update:
* [ ]  Remove installers for the outdated distro
* [ ]   Remove build support
* [ ]   Remove test assets

### Infrastructure Team Accountabilities/Deliverables:
* [ ]   Notification to NetCore Engineering Partners
* [ ]   Remove the outdated version from the hardware pool

### Release Team
* [ ]   Send Notification to every team in .NET for upcoming addition
* [ ]   Supported OS content gets updated on GitHub and marketing sites.
* [ ]   Update release manifest files.
* [ ]   Docker files which are used for install testing needs to be updated.

### Document updates:
* [ ]  Add/Remove OS prerequisites to the dependencies document
* [ ]  Update distro install page

/CC @rbhanda /label os-support

(I can remove the upper content once @rbhanda took over.)

**Comment by Falco20019** [comment]
This is still missing the `os-support` label :) There is also still no other ticket in place of this so that it would be obsolete.

**Comment by mairaw** [comment]
I added the label. @rbhanda to look at this issue.
