### ISSUE TITLE
p

### ISSUE THREAD

**Issue by Katulus** [dotnet/core#898]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by sylveon** [comment]
p

**Comment by Katulus** [comment]
Damn, how did this happen? So embarrassing. Consider this issue fixed. :-D
