### ISSUE TITLE
Installed the setup exe file still facing the issue that dotnet sdk is not installed

### ISSUE THREAD

**Issue by sundhar27** [dotnet/core#8980]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you let us know what `dotnet --info` returns?
