### ISSUE TITLE
Default Page of a Blazor Project is not charging

### ISSUE THREAD

**Issue by icuarezma** [dotnet/core#8983]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My default web app with blazor is not running show the warning message of Certificate SSL and the default page not charge.
![blazoristnocharging](https://github.com/dotnet/core/assets/75040705/dbbeac08-5cc9-474b-8596-586e372cc48b)

**Comment by mairaw** [comment]
Have you followed the instructions on the Got error section of that page?

Got an error?
If you receive an error message saying "Your connection is not private" with error code NET::ERR_CERT_INVALID, try to restart all browser windows so the new certificate can be picked up by the browser and run the application again.
