### ISSUE TITLE
Running tutorial code failed

### ISSUE THREAD

**Issue by Liturgist** [dotnet/core#8989]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

```
[Running] scriptcs "c:\src\.Net\MyConsoleApp\Program.cs"
'scriptcs' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.067 seconds

PS C:\src\.Net> code --version
1.85.0
af28b32d7e553898b2a91af498b1fb666fdebe0c
x64
```

**Comment by Jozkee** [comment]
@mairaw

**Comment by Liturgist** [comment]
I figured out how to edit my settings.json to make it work. I do not recall doing anything that would have installed scriptcs. This seems like a hurdle that the beginner should be able to avoid. Is the default in VS Code to use scriptcs? Or, what would I have run to install or configure it in this way?

**Comment by Jozkee** [comment]
I'm unsure how you ended up depending on scriptcs. Is this your first time installing VS Code? Perhaps a previous configuration is messing up with the defaults assumed in the tutorial. Anyway, glad you were able to workaround it.
