### ISSUE TITLE
Asp-controller and asp-action attributes order

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/core#899]
If a make an a-tag in html on the view and put asp-* tags (for example asp-controller, asp-action and asp-route) after a @(some code)-section and a class-attribute it breaks the interpretation of the asp-* attributes.

Below example doesnt pick up the route-id:
`
<a asp-controller="Some" asp-action="Something" class="@(x == y ? "something" : "")" asp-route-id="1">Click me</a>
`
if I put all after nothing happens (no href is generated):
`
<a class="@(x == y ? "something" : "")" asp-controller="Some" asp-action="Something" asp-route-id="1">Click me</a>
`
Is this behaviour as design?

VS 2017 15.3.2
.NETCore 2.1.0-preview1-26778
.EFCore 2.1.0-preview1-26778
Windows 10 Insider (slow ring)

**Comment by johanskoldekrans** [comment]
This is probably closer to what I did IRL that didn't work, if there is a difference:

`<a @(x == y ? "class=\"something\"" : "")" asp-controller="Some" asp-action="Something" asp-route-id="1">Click me</a>`

**Comment by Petermarcu** [comment]
moved here: https://github.com/aspnet/Home/issues/2231
