### ISSUE TITLE
C:\Users\info2info2\MyMicroservice>dotnet run Building... C:\Users\info2info2\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.OpenAp i (>= 8.0.0)' for 'net8.0'. C:\Users\info2info2\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 6.4.0)' for 'net8.0'.  The build failed. Fix the build errors and run again.

### ISSUE THREAD

**Issue by snlinfo2** [dotnet/core#8990]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Details error message: C:\Users\info2info2\MyMicroservice>dotnet run
Building...
C:\Users\info2info2\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.OpenAp
i (>= 8.0.0)' for 'net8.0'.
C:\Users\info2info2\MyMicroservice\MyMicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>=
6.4.0)' for 'net8.0'.
The build failed. Fix the build errors and run again.

Operating system: Windows 10 pro, version: v 22H2 os build 19045.3693

**Comment by wfurt** [comment]
try `dotnet restore` and `dotnet build` @snlinfo2 what version of do you have? (`dotnet --info`)

**Comment by snlinfo2** [comment]
Allow me to check and get back to you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
