### ISSUE TITLE
Console.WriteLine("The current time is " + DateTime.Now);

### ISSUE THREAD

**Issue by bazookastudios122** [dotnet/core#8993]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
@bazookastudios122 can you please describe the issue you are seeing with `Console.WriteLine()` or `DateTime.Now`; otherwise, this is not actionable.
