### ISSUE TITLE
failed to solve: the Dockerfile cannot be empty

### ISSUE THREAD

**Issue by Surojitmendine** [dotnet/core#8994]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

D:\MyMicroservice>docker build -t mymicroservice .
[+] Building 0.0s (2/2) FINISHED                                                                                                     docker:default
 => [internal] load .dockerignore                                                                                                              0.0s
 => => transferring context: 34B                                                                                                               0.0s
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 31B                                                                                                            0.0s
ERROR: failed to solve: the Dockerfile cannot be empty

**Comment by Jozkee** [comment]
@jamesmontemagno @bradygaster

**Comment by jamesmontemagno** [comment]
Please double check your Dockerfile and ensure you copied in the correct information from the tutorial.
