### ISSUE TITLE
NET::ERR_CERT_INVALID

### ISSUE THREAD

**Issue by zengzhanpingGit** [dotnet/core#8999]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
Did you try the "Got an error?" suggestion?

> Got an error?
> If you receive an error message saying "Your connection is not private" with error code NET::ERR_CERT_INVALID, try to restart all browser windows so the new certificate can be picked up by the browser and run the application again.
