### ISSUE TITLE
install .net core preview 1 HDInsight linux cluster

### ISSUE THREAD

**Issue by caserzer** [dotnet/core#90]
I trying to install .net core preview 1 on Linux cluster headnode
after running the script, it report install success. but when I run the dotnet --version it says:
WARNING:root:could not open file '/etc/apt/sources.list.d/HDP.list'

**Comment by Petermarcu** [comment]
Do other dotnet commands work? Which script did you run?

**Comment by caserzer** [comment]
curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet
before that I install libunwind8 & gettext

**Comment by caserzer** [comment]
Sorry , I found I used the wrong script , I should use the ubuntu script
