### ISSUE TITLE
Problem in Installation I can find the Solution Explorer?

### ISSUE THREAD

**Issue by 7ieFe** [dotnet/core#9000]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Jozkee** [comment]
It may be that you are missing the C# Dev Kit extension or ".NET: New Project" command failed and either didn't create or load the project, can you please check if that's the case?
