### ISSUE TITLE
No SDKs were found 

### ISSUE THREAD

**Issue by zarnayp** [dotnet/core#9002]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: linux

I tried manual and scripted installation of dotnet. In both cases SDK is not installed, only runtime. 

$ dotnet --info

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71
  RID:          linux-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/pet/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Jozkee** [comment]
Did you check the output of the dotnet-install.sh script?

Did you also try with a package manager? [https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#install-net (assuming you are in Ubuntu).](https://learn.microsoft.com/en-us/dotnet/core/install/linux#packages)

**Comment by zarnayp** [comment]
Still do not understand what was the problem, but I tried package manager as you suggested and finally SDK is installed. 
Thank you.
