### ISSUE TITLE
Can't create blazorserver project using .net8

### ISSUE THREAD

**Issue by eduardoboca** [dotnet/core#9003]
I'm trying to create a blazorserver project with .net8, but it uses .net5 as default. And if try to force to .net, it says (Portuguese version):

Erro: Opções inválidas:
-f net8.0
   'net8.0' não é um valor válido para '-f'. Os valores possíveis são:
      net5.0   - Target net5.0

If I create a console application, though, everything works fine. I don't even have to force .net8

**Comment by Jozkee** [comment]
What command are you running to create the blazorserver? Can you set net8.0 in <TargetFramework> in the .csproj after it's created?

cc @danroth27

**Comment by mairaw** [comment]
What does `dotnet --info` return?

**Comment by eduardoboca** [comment]
My bad :-(

In .net8 there is no longer a "Blazorserver" Template. 
Now it's "Blazor Web App" with the Interactive render mode option equal to "Server"
