### ISSUE TITLE
.net 8.0 not showing on VS project's property page.

### ISSUE THREAD

**Issue by SMaczko** [dotnet/core#9006]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm running windows 10 home, V 22H2.

I have a simple problem. I've upgraded to net 8.0 from 4.8.   But when i started Visual Studio 2022 (v 17.7.6), and loaded a recent project, the list of .NET Frameworks did not include 8.0, ending with v. 4.8.

So, I did some basics and discovered dotnet --info. The output is in the attached dotnet-info.txt.

I also rebooted, but that did not help either.

Steve Maczko
sgmaczko@gmail.com

**Comment by mairaw** [comment]
@SMaczko .NET 8 requires VS 17.8 or higher.

See if it works after you upgrade your VS and let us know.

**Comment by SMaczko** [comment]
After upgrade, I decided that I might begin a new project. (The new project routine includes    several boxes that allow you to add enhancements to the project.)  

The second item on the properties page is Target Framework: the options are now 5.0, 6, 7,8 and a set of .NET core from 1.0 to 3.1. So, part of the original issue is solved.

But then I loaded the original project that I wanted to upgrade from Framework 4.8 to 6. Here the props page was unhelpful. The highest framework allowed is still 4.8.

So, now the question is: does a way exist to convert the old 4.8 to one of the newer frameworks?

**Comment by mairaw** [comment]
Yes, check out the Upgrade assistant extension for Visual Studio.

https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview
https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-install

**Comment by SMaczko** [comment]
Sorry, but the holidays overwhelmed me.

 

I followed the suggested links, and the upgrade proceeded smoothly.

**Comment by mairaw** [comment]
Great to hear @SMaczko!
