### ISSUE TITLE
Su conexión no es privada

### ISSUE THREAD

**Issue by jsotomedina** [dotnet/core#9009]
Al ejecutar la aplicación aparece el pantallazo que adjunto
![Screenshot_1](https://github.com/dotnet/core/assets/102502815/6604195a-0750-48f7-adc7-940308ce3be0)

**Comment by mairaw** [comment]
Try the steps on the section **¿Tiene un error?**:
https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/run

Let us know if that helps.
