### ISSUE TITLE
 Failed to determine the https port for redirect.

### ISSUE THREAD

**Issue by Cesaraven19** [dotnet/core#9010]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: macOS 12.6.7

esars-Mac-mini:BlazorApp cesaravendano$ dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  BlazorApp -> /Users/cesaravendano/BlazorApp/bin/Debug/net8.0/BlazorApp.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5074
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/cesaravendano/BlazorApp
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
info: Microsoft.Hosting.Lifetime[0]

**Comment by mairaw** [comment]
@danroth27 can you help here?

**Comment by mcyenikoylu** [comment]
In the Properties/launchSettings.json file, move the "https" setting in the "profiles" property to the top so that it runs before the "http" setting.

**Comment by danroth27** [comment]
The "Failed to determine the https port for redirect" warning can be safely ignored.

**Comment by Kaiss011** [comment]
> In the Properties/launchSettings.json file, move the "https" setting in the "profiles" property to the top so that it runs before the "http" setting.

Thank you, it worked also in my case
