### ISSUE TITLE
Issue with dotnet restore on NET8 and multi nuget source configured.

### ISSUE THREAD

**Issue by DmitryLukyanov** [dotnet/core#9012]
## Description

Consider you have multi nuget source configured on the machine in nuget.config:

     <packageSources>
          <add key="nuget.org" value=https://api.nuget.org/v3/index.json protocolVersion="3" />
          <add key="externalSourceThatRequireAuth" value="https://.../nuget/v3/index.json"/>
          <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    </packageSources>

Then try to call `dotnet restore` as described below:

    c:\>mkdir issue
    c:\>cd issue
    c:\issue>mkdir app
    c:\issue>cd app
    c:\issue\app>dotnet --version
    8.0.100
    c:\issue\app>dotnet new console --no-restore
    The template "Console App" was created successfully.
    c:\issue\app>dotnet restore app.csproj
      Determining projects to restore...
    C:\Program Files\dotnet\sdk\8.0.100\NuGet.targets(156,5): error : Unable to load the service index for source https://.../nuget/v3/index.json. [c:\issue\app\app.csproj]
    C:\Program Files\dotnet\sdk\8.0.100\NuGet.targets(156,5): error :   Response status code does not indicate success: 401 (Unauthorized). [c:\issue\app\app.csproj]

Notice that I don't use `externalSourceThatRequireAuth` in this app. Then there are 3 workarounds to fix it:
1. Call something like `nuget search -take 10 -Source externalSourceThatRequireAuth` that will solve issue approximately for 30 mins.
2. Use `msbuild` instead `dotnet`: 

        c:\issue\app>msbuild app.csproj -t:Restore

4. switch back to older target frameworks, I checked with .NET5:

        c:\issue\app>cd ../    
        c:\issue>dotnet --list-sdks
        5.0.408 [C:\Program Files\dotnet\sdk]
        8.0.100 [C:\Program Files\dotnet\sdk]     
        c:\issue>dotnet new globaljson
        The template "global.json file" was created successfully.    
        c:\issue>more global.json
        {
          "sdk": {
              "version": "8.0.100"
           }
        }     
// change the sdk version on 5.0.408      

    c:\issue>more global.json
    {
      "sdk": {
        "version": "5.0.408"
      }
    }     
    c:\issue>cd app     

// change the version of the project from `net8.0` to `net5.0`

    c:\issue\app>more app.csproj
    ...
        <TargetFramework>net5.0</TargetFramework>
    ...     
    c:\issue\app>dotnet restore app.csproj
      Determining projects to restore...
      Restored c:\issue\app\app.csproj (in 63 ms).

### Configuration

* Which version of .NET is the code running on: net8.0
* What OS and version: windows 11
* What is the architecture: x64

### Regression?

yes, it works well on .net5.0 and I think it worked on .net7.0 (didn't check now though)

**Comment by wfurt** [comment]
any idea @rainersigwald ? If now who should look at this? 
It seems like `restore` should simply ignore sources that cannot be access.

**Comment by rainersigwald** [comment]
Let's move this to NuGet, just a moment.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#13129
