### ISSUE TITLE
Add support for Alpine 3.19

### ISSUE THREAD

**Issue by lbussell** [dotnet/core#9013]
[Alpine 3.19](https://alpinelinux.org/posts/Alpine-3.19.0-released.html) was released on 2023-12-07. 

I believe we need the RID ASAP due to https://github.com/PowerShell/PowerShell/issues/20945 which is blocking PowerShell support in https://github.com/dotnet/dotnet-docker/pull/5065.

Similar issue for Alpine 3.18: https://github.com/dotnet/core/issues/8470

**Comment by mairaw** [comment]
@leecow @rbhanda can you check?

**Comment by agocke** [comment]
We no longer provide support for OS-specific RIDs, only portable RIDs. The portable RID should provide equivalent functionality.

That said, I'm not sure the RID is the fundamental problem here. Powershell ran into a problem with a .NET 8 breaking change which they needed to adapt to in their code: https://github.com/PowerShell/PowerShell/issues/20685. This may be the same problem.
