### ISSUE TITLE
obj\project.assets.json not found

### ISSUE THREAD

**Issue by Delesin** [dotnet/core#9014]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Tried to run the default project, but got this error: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\Mark\source\repos\BlazorApp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	BlazorApp	C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266

**Comment by wfurt** [comment]
That looks like the app was not properly build. Do you use command line or UI @Delesin ?
For command line you can try `dotnet build` and `dotnet run` in the project directory.
