### ISSUE TITLE
After  deploying not able to see my  microservice service  runing

### ISSUE THREAD

**Issue by bhagyshricompany** [dotnet/core#9016]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
os 🪟 
as mention kubectl get service mymicroservice --watch after this cmd apply external ip address with service see its  working by=ut in my case it not seems
http://4.xxx.xxx.xx/weatherforcast

**Comment by wfurt** [comment]
what do you see @bhagyshricompany ? Is it possible that there is some security filter for your subscription?
