### ISSUE TITLE
dotnet tool failing to install csharpier

### ISSUE THREAD

**Issue by mbjasonayer** [dotnet/core#9020]
### Description

Running the following command `dotnet tool install -g csharpier` produces the following error:

```
C:\Users\jpayer\AppData\Local\Temp\c9a0f2f7-6b74-4505-bfe2-8c9a0efe4d18\restore.csproj : error NU1301: Unable to load the service index for source https://nuget.telerik.com/v3/index.json.
The tool package could not be restored.
Tool 'csharpier' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

### Configuration

OS: Windows 10 Enterprise
OS Version: 22H2
OS Build: 19045.3803
OS Experience: Windows Feature Experience Pack 1000.19053.1000.0
DotNet Version: 7.0.302
CLI app: Powershell

### Regression?

Unknown

### Other information

I have no other information other than I am unable to follow this guide beyond the first point: [https://csharpier.com/docs/Installation](https://csharpier.com/docs/Installation)

**Comment by mairaw** [comment]
@nkolev92  any suggestions here?

**Comment by ghost** [comment]
Tried to install twice on different machines  and got the same result.
dotnet csharpier format .
Could not execute because the specified command or file was not found.
csharpeir
Works

But in VS where i expect it to work it does not
