### ISSUE TITLE
docs: add a notice about the portable_pdb descrition being moved to the https://github.com/dotnet/designs repo

### ISSUE THREAD

**Issue by rgl** [dotnet/core#9022]
### Description

Like https://github.com/dotnet/core/blob/main/Documentation/diagnostics/source_link.md  page which has a notice that points to the new location at https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/source-link.md

The page at https://github.com/dotnet/core/blob/main/Documentation/diagnostics/portable_pdb.md should also have a notice that points to the new location at https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/portable-pdb.md

**Comment by wfurt** [comment]
I think the redirect is automatic and the PDB file was not moved. Any thoughts on this @tmat ?
