### ISSUE TITLE
i am not able to get blazor server app

### ISSUE THREAD

**Issue by ibrahims23** [dotnet/core#9023]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
can you let us know what command are you trying to run and what is failing and what the error message is @ibrahims23 ?
