### ISSUE TITLE
DefaultInterpolatedStringHandler: change ArrayPool<char> to ArrayPool<byte>

### ISSUE THREAD

**Issue by kefyru** [dotnet/core#9027]
`ArrayPool<byte>` and `ArrayPool<char>` are most used in .net
In most cases `ArrayPool<char>` used just by `DefaultInterpolatedStringHandler`, while `ArrayPool<byte>` uses for other tasks (like Streams, Sockets, Databases e.t.c).
This causes extra memory usage (there are allocations both `byte[]`'s and `char[]`'s).
I think using `ArrayPool<byte>` for `DefaultInterpolatedStringHandler` will decrease memory usage and performance will not change.

```cs
public DefaultInterpolatedStringHandler(int literalLength, int formattedCount)
{
    _provider = null;
    _arrayToReturnToPool = ArrayPool<byte>.Shared.Rent(
        GetDefaultLength(literalLength, formattedCount) * sizeof(char))
    )
    _chars = MemoryMarshal.CreateSpan(
        ref UnsafeAs(ref MemoryMarshal.GetArrayDataReference(_arrayToReturnToPool),
        _arrayToReturnToPool.Length >> 1
    )
    _pos = 0;
    _hasCustomFormatter = false;
}
... e.t.c.
```

**Comment by wfurt** [comment]
One can argue that everything can be represented as bytes. But `char` and `byte` are separate types and mixing them muddles clarity. If you have competing use case write benchmarks and open separate issue in https://github.com/dotnet/runtime
