### ISSUE TITLE
last step don't work.

### ISSUE THREAD

**Issue by dakifeva** [dotnet/core#9028]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

When I try to write word dotnet, the  programm write, that name don't find. Am I miss something?

**Comment by claudiaregio** [comment]
Hi @dakifeva, could you provide more details on the issue you are encountering? Does a restart of your machine fix the issue?

**Comment by Icegreeen** [comment]
See if this is your problem, the last comment is the solution: https://github.com/dotnet/core/issues/9036

**Comment by wfurt** [comment]
make sure you .NET SDK is properly installed. As @Icegreeen said there may be issue with PATH ... especially if you had Window opened before the install.
