### ISSUE TITLE
MD5 class get  31 length hash code

### ISSUE THREAD

**Issue by wantaotao1994** [dotnet/core#903]
# Issue Title

When I use Md5 for .net core2.0 , I found  it get errors
# General
This is my source string:
`C21BFBF13E7607FCF5268BA9D1C3EA47{"access_token":"JM7XaNP0prjHoRTHOy6HRMuVCbESLTe7","address":"长宁bbbbl","city":"上海市","county":"徐汇区","invoice_content":"办公用品","invoice_name":"李四","invoice_state":"1","invoice_type":"C","mobile":"11909090900","name":"万涛涛是够11","order_id":"123213213123","phone":"021-999999","province":"上海","request_type":0,"sub_order_list":[{"count":2,"out_sku_id":"out123456","Price":0.0,"sku_id":"110217","sub_order_id":"123213123"},{"count":3,"out_sku_id":"out654321","Price":0.0,"sku_id":"110519","sub_order_id":"3213"}],"zip":"20000"}C21BFBF13E7607FCF5268BA9D1C3EA47`

My code from https://msdn.microsoft.com/zh-cn/library/system.security.cryptography.md5(v=VS.110).aspx:
 ```
   static string GetMd5Hash(MD5 md5Hash, string input)
        {

            // Convert the input string to a byte array and compute the hash.
            byte[] data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes(input));

            // Create a new Stringbuilder to collect the bytes
            // and create a string.
            StringBuilder sBuilder = new StringBuilder();

            // Loop through each byte of the hashed data 
            // and format each one as a hexadecimal string.
            for (int i = 0; i < data.Length; i++)
            {
                sBuilder.Append(data[i].ToString("x2"));
            }

            // Return the hexadecimal string.
            return sBuilder.ToString();
        }

    static string GetMd5Hash(MD5 md5Hash, string input)
        {

            // Convert the input string to a byte array and compute the hash.
            byte[] data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes(input));

            // Create a new Stringbuilder to collect the bytes
            // and create a string.
            StringBuilder sBuilder = new StringBuilder();

            // Loop through each byte of the hashed data 
            // and format each one as a hexadecimal string.
            for (int i = 0; i < data.Length; i++)
            {
                sBuilder.Append(data[i].ToString("X"));
            }

            // Return the hexadecimal string.
            return sBuilder.ToString();
        }
```

And  this is my result :A29960F4BB18C4598C419EF7482386C(31 length string).
Thank you for your reply.

**Comment by svick** [comment]
You pasted two versions of `GetMd5Hash`: 

* The first one is the same as the one on MSDN (with `data[i].ToString("x2")`) and gives the correct result (`a29960f4bb180c4598c419ef7482386c`, 32 characters).
* The second one is different (with `data[i].ToString("X")`) and indeed gives incorrect result (`A29960F4BB18C4598C419EF7482386C`, 31 characters).

Was your intention to change the output to uppercase? In that case, you need `data[i].ToString("X2")`, which returns `A29960F4BB180C4598C419EF7482386C`.

**Comment by wantaotao1994** [comment]
Duplicate of #Thanks a  @lot~

>
