### ISSUE TITLE
Can´t start the docker

### ISSUE THREAD

**Issue by heh62** [dotnet/core#9030]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

I get the following error when I run the 
docker build -t mymicroservice . 
command

ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by wfurt** [comment]
what `docker --version` gives you? Do you see Docker service running as service?

**Comment by emresindir** [comment]
Looks like your docker daemon is not running. Start the docker desktop before the running any docker command.
