### ISSUE TITLE
NET::ERR_CERT_INVALID

### ISSUE THREAD

**Issue by SylenthMen** [dotnet/core#9032]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://github.com/dotnet/core/assets/33080405/95d7bb01-3460-4cd6-9ee5-d11b763894c7)

**Comment by wfurt** [comment]
It seems like browser does not trust the dev certificate.
Try to run
```
dotnet dev-certs https --check --trust
```

You can also probably make it trusted directly in browser.

**Comment by mairaw** [comment]
From the page:

**¿Tiene un error?**
Si recibe un mensaje de error que dice "Su conexión no es privada" con el código de error NET::ERR_CERT_INVALID, intente reiniciar todas las ventanas del navegador para que el navegador pueda recoger el nuevo certificado y ejecutar la aplicación nuevamente.

Si no puede resolver el problema, use el botón He tenido un problema para obtener ayuda para solucionar el problema.

Have you done that?

**Comment by professor-k** [comment]
For the sake of anyone not doing blazor tutorial but still getting `ERR_CERT_INVALID` after `dotnet dev-certs https --trust`: restart of the browser indeed helps.
