### ISSUE TITLE
how to open .net in visual studio 2019

### ISSUE THREAD

**Issue by Naveenjbnk** [dotnet/core#9034]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by wfurt** [comment]
I don't think Blazor is  supported in 2019. You should upgrade your VS @Naveenjbnk

**Comment by o00oo00o** [comment]
Visual Studio 2019 only support up to .NET 5.
If you are using .NET 6 and above, you must use Visual Studio 2022.

See here:
https://learn.microsoft.com/en-us/visualstudio/releases/2019/compatibility
