### ISSUE TITLE
命令“NET：新建项目..."导致错误

### ISSUE THREAD

**Issue by 321diner** [dotnet/core#9035]
Failed with ExitCode(2147516561）
Details
The command could not be loaded possibly because
* You intended to execute a NET application:
The application 'new' does not exist.
* You intended to execute a NET SDK command
No NET SDKs were found.
Download a.NET SDK:
https://aka.ms/dotnet-download
Learn about SDK resolution
https://aka.ms/dotnet/sdk-not-found

**Comment by wfurt** [comment]
what exactly did you try to execute @321diner ? What platform and .NET version do you use?

**Comment by mairaw** [comment]
What does `dotnet --info` returns @321diner?
