### ISSUE TITLE
I don't get the ASP.NET and web development  option in visual studio install ... as is shown in the tutorial...thank you

### ISSUE THREAD

**Issue by Janella-codes** [dotnet/core#9037]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![asp_dot_net_missing](https://github.com/dotnet/core/assets/118861074/b9167324-0bf0-41ea-9f50-4eb061044e52)

![tutorial](https://github.com/dotnet/core/assets/118861074/738365ac-4568-4854-ba49-e9b28d84a0e7)

**Comment by wfurt** [comment]
what version of Visual Studio do you have @Janella-codes ?
