### ISSUE TITLE
Error running Blazor File.

### ISSUE THREAD

**Issue by suju2011** [dotnet/core#9039]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: windows
Ifound this error encountered on running the blazor file showing this error : Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0.	BlazorApp	C:\Program Files (x86)\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	144

**Comment by wfurt** [comment]
what do you get if you run `dotnet --version` and `dotnet --info` @suju2011 ?

**Comment by suju2011** [comment]
Thanks for your responses,but the Error is resolved now it was an
installation issue.

🙂
