### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 1450417571** [dotnet/core#9042]
![QQ图片20240104160206](https://github.com/dotnet/core/assets/155619597/8549d5ca-008c-4cf4-bc17-f7709b37559f)

**Comment by wfurt** [comment]
what do you get if you run `dotnet --info`  @1450417571 ???

**Comment by Icegreeen** [comment]
@1450417571 
you can find the possible problem and fix here:
https://stackoverflow.com/questions/73247933/how-to-fix-no-net-sdks-were-found-error-vscode
