### ISSUE TITLE
the solution explorer isn't there

### ISSUE THREAD

**Issue by lordstickman543** [dotnet/core#9043]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you share a screenshot of what do you see? Can you ensure the C# Dev Kit extension was successfully installed?
