### ISSUE TITLE
host port

### ISSUE THREAD

**Issue by alexmarculino** [dotnet/core#9044]
problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
PS C:\Users\Windows\BlazorApp> dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  BlazorApp -> C:\Users\Windows\BlazorApp\bin\Debug\net8.0\BlazorApp.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Windows\BlazorApp
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by mairaw** [comment]
@danroth27 can you help here?

**Comment by danroth27** [comment]
> Failed to determine the https port for redirect.

This is just a warning, and it can be safely ignored.
