### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by nigeljohnwade** [dotnet/core#9045]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Blazorise.css does not load (404) when the app starts

**Comment by Icegreeen** [comment]
@nigeljohnwade 

1- Make sure the reference to the Blazorise.css file in your code is correct and points to the correct location. Make sure the file is present in the specified location and the path is correct.

2 - Use the "dotnet restore" command to ensure that all dependencies are up to date.

3 - If you are using static routing in your Blazor app, make sure that the Blazorise.css file is configured correctly in your wwwroot file and that static routing is configured properly in Startup.cs.

4 - Open your browser's developer tools (by pressing F12) and go to the "Console" tab. Check for error messages or warnings related to CSS file loading. This may provide additional information about the problem.

**Comment by mairaw** [comment]
Are you following the tutorial or doing your own project @nigeljohnwade? I don't see that CSS file on the template.
