### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Swayanshu18** [dotnet/core#9046]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Did you install the .NET SDK? Can you share what the command `dotnet --info` returns?
