### ISSUE TITLE
Invalid Attribute

### ISSUE THREAD

**Issue by sajis997** [dotnet/core#9050]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

`@page "/counter"
@rendermode InteractiveServer

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    [Parameter]
    public int IncrementAmount = { get; set; } = 1;

    private void IncrementCount()
    {
        currentCount += IncrementAmount;
    }
}
`

**Comment by mairaw** [comment]
Can you provide more details about the issue you're having? Also, can you share what dotnet --info returns to confirm you have the same version as the tutorial is written.

**Comment by Icegreeen** [comment]
The **IncrementAmount** property is declared incorrectly:

Correction:

```
@code {
    private int currentCount = 0;

    [Parameter]
    public int IncrementAmount { get; set; } = 1;

    private void IncrementCount()
    {
        currentCount += IncrementAmount;
    }
}
```

I corrected the declaration of the IncrementAmount property. The correct syntax is `{ get; set; }` instead of `= { get; set; }`.

**Comment by mairaw** [comment]
Thanks for noticing that small detail. I double checked https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify and the code there is declared correctly.
