### ISSUE TITLE
.NET SDK Not Recognized

### ISSUE THREAD

**Issue by cdupuisKR** [dotnet/core#9051]
### Description
I have seen the posts about the same issue where you load a solution and the projects won't load and there is a problem with the SDKs but my where.exe dotnet only brings up:
C:\Program Files\dotnet\dotnet.exe
Does anyone have a solution for this version of the problem?
Thank You!

**Comment by mairaw** [comment]
As I mentioned at https://github.com/dotnet/core/issues/5962#issuecomment-1883776011

can you confirm what is the architecture of your Windows machine and can you share the results of dotnet --info?

**Comment by cdupuisKR** [comment]
The architecture is Windows 10 pro x64.
dotnet --info gives me:
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Things look good on your output. And when you run a SDK command, you're getting the SDK not found message then @cdupuisKR? Or what kind of error you're getting when you load the project? Is it on VS or VS Code?

@baronfel any suggestions?

**Comment by baronfel** [comment]
Nothing jumps out to me as wrong from the `dotnet --info` output. I'd echo @mairaw's questions here - does a command-line build of your project work @cdupuisKR? Is the problem surfacing only in VS/VSCode?

**Comment by mairaw** [comment]
What version of VS are you using? Have you finished the upgrade and is giving you an error when you load the upgraded solution?

Can you run simple SDK commands on the console? For example, can you create a new console project using the command prompt using `dotnet new console`?

**Comment by cdupuisKR** [comment]
I'm using the most up to date VS 17.8.3. I opened the original solution that I have brought up in VS 17 before and then it gave all these update errors. Now I get that my projects won't load in both the updated solution and the backup solution before the update. I just ran dotnet new console in the command prompt and gave me this:
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring C:\Users\cdupuis\cdupuis.csproj:
  Determining projects to restore...
  Restored C:\Users\cdupuis\cdupuis.csproj (in 69 ms).
Restore succeeded.

**Comment by cdupuisKR** [comment]
I have also tried reverting back to VS 17.7 and VS 16.11 and the same error comes up.

**Comment by mairaw** [comment]
Ok, so the SDK is running fine on your machine. Seems to be a problem with Visual Studio then. I still don't know which errors you're seeing in VS. But I'd recommend that you report the bug through VS so it can go to the right team. On the main menu, select Help > Send Feedback > Report a Problem.

**Comment by cdupuisKR** [comment]
Okay thank you!

**Comment by cdupuisKR** [comment]
Sorry one last try! Visual Studio support takes a long time to respond. I recreated opening the solution for the first time and have attached the errors it gives me. Not sure you can help me but worth a try!
![Capture2](https://github.com/dotnet/core/assets/135364106/6cd3f4f5-8580-45a4-8514-c636dba21011)
![Capture3](https://github.com/dotnet/core/assets/135364106/8c1b84dd-e777-465c-9eba-071af1a34d84)

**Comment by jekelly** [comment]
Hi @cdupuisKR - can you [report this](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) on Developer Community? Providing repro steps and a recording with your ticket should give us enough information to fully investigate.

If you've already done this, please include a link to the feedback.

**Comment by cdupuisKR** [comment]
Here is the link to the developer community:
https://developercommunity.visualstudio.com/t/NET-Solutions-Not-Opening-Properly/10555085

**Comment by cdupuisKR** [comment]
Most of the post on the developer community were put as private if you need help accessing I can send some screen shots.

**Comment by mairaw** [comment]
We can see the private messages and images when logged in with the Microsoft credentials. Thank you!
