### ISSUE TITLE
error encountered "your connection is not private"

### ISSUE THREAD

**Issue by mirha786** [dotnet/core#9060]
Your connection is not private
Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_INVALID

**Comment by wfurt** [comment]
please provide more information about what you are trying to do. @mirha786.
If this is your development project you can either trust the certificate in browser or run `dotnet dev-certs  https --trust` to add development certificate as trusted. (Windows & macOS)

**Comment by mairaw** [comment]
This page also has information about what to do when you encounter this error
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
