### ISSUE TITLE
localhost 当前无法处理此请求。

### ISSUE THREAD

**Issue by lovemyxin** [dotnet/core#9062]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/run
Operating System: windows

当我点击“调试”按钮启动项目后

浏览器显示
![image](https://github.com/dotnet/core/assets/37971834/9f5b59a9-1c4f-450b-8a42-1d850bf0b352)

控制台打印
![image](https://github.com/dotnet/core/assets/37971834/e00f7aa7-ac19-4d8f-9a26-eed35c2c5401)

**Comment by wfurt** [comment]
can you try the plain HTTP port at 5138? Is it possible there is some security firewall on your machine blocking the connection @lovemyxin ?
