### ISSUE TITLE
Run Project Associated With This File Doesn't Work - HelloWorld

### ISSUE THREAD

**Issue by mrmonteith** [dotnet/core#9067]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
OS: Device name	LAPTOP-6UQFF2LG
Processor	AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G   2.40 GHz
Installed RAM	16.0 GB (15.5 GB usable)
Device ID	702FA307-4F49-4286-9D7E-855B35FF3480
Product ID	00325-80487-47168-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

namespace C_Sharp;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
    }
}

Run project associated with this file doesn't do anything.   

NOTE: At the bottom of the screen is 
Error acquiring .NET!

Launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "console": "internalConsole"
        }

    ]
}

**Comment by mairaw** [comment]
What error message do you get when trying to run the project?

/cc @claudiaregio

**Comment by mrmonteith** [comment]
Oh joy.  Spent time getting the rest and forgot an important piece. Today it was working.  toss it up to working too late and too tired .  Thanks for taking the time, and sorry.

**Comment by mrmonteith** [comment]
Oh joy.  Spent time getting the rest and forgot an important piece. Today it was working.  toss it up to working too late and too tired .  Thanks for taking the time, and sorry.
