### ISSUE TITLE
Error in Configuring  .net web application project(.net framework) project

### ISSUE THREAD

**Issue by Shubhithebeast** [dotnet/core#9070]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://github.com/dotnet/core/assets/71927968/9dc1f513-6b76-43d6-8953-c82ee64958cb)

**Comment by mairaw** [comment]
This seems to fall outside of the Blazor tutorial since it's a .NET Framework project. Please report the issue through Visual Studio
https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022
