### ISSUE TITLE
Problama na criação de novo projeto 

### ISSUE THREAD

**Issue by Bocao31** [dotnet/core#9072]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Você pode dar mais detalhes de quais problemas você está tendo na criação de um novo projeto?
