### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by masego-cyber** [dotnet/core#9074]
dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  BlazorApp -> C:\Users\30233674\BlazorApp\bin\Debug\net8.0\BlazorApp.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5192
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\30233674\BlazorApp
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by mairaw** [comment]
The message "Failed to determine the https port for redirect." is just a warning that you can safely ignore.

We're tracking an improvement of this experience at https://github.com/dotnet/aspnetcore/issues/53229.
