### ISSUE TITLE
docker pull mcr.microsoft.com/dotnet/sdk:6.0  Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

### ISSUE THREAD

**Issue by cd-linxi** [dotnet/core#9079]
### Description

docker pull mcr.microsoft.com/dotnet/sdk:6.0  
Result return：
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

My server is in the Sao Paulo area。

### Reproduction Steps

docker pull mcr.microsoft.com/dotnet/sdk:6.0  

### Expected behavior

Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

### Actual behavior

Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

**Comment by CarnaViire** [comment]
Moved to dotnet/core for cross-repo triage

**Comment by richlander** [comment]
This is almost certainly no longer an issue or else we would have heard from many more people.
