### ISSUE TITLE
FormOptions not work

### ISSUE THREAD

**Issue by sy-ing** [dotnet/core#908]
In  .net core 2.0 
I want to upload a file that size maybe 1G or more 

I  modify the  FormOptions  like

   services.Configure<FormOptions>(x =>
            {
                x.ValueLengthLimit = int.MaxValue;
                x.MultipartBodyLengthLimit = int.MaxValue;
                x.MultipartHeadersLengthLimit = int.MaxValue;
            });

But it is invalid

I still can't upload files over 10M in size

**Comment by Petermarcu** [comment]
@Eilon

**Comment by Eilon** [comment]
This issue was moved to aspnet/HttpAbstractions#930
