### ISSUE TITLE
`cve.md` only exists for .NET 6; should exist for other (later) versions

### ISSUE THREAD

**Issue by richlander** [dotnet/core#9083]
- https://github.com/dotnet/core/blob/main/release-notes/6.0/cve.md
- https://github.com/dotnet/core/blob/main/release-notes/7.0/cve.md
- https://github.com/dotnet/core/blob/main/release-notes/8.0/cve.md

@rbhanda

**Comment by rbhanda** [comment]
Ack, I will add those
