### ISSUE TITLE
Não consigo instalar o VS code

### ISSUE THREAD

**Issue by Denilson3661** [dotnet/core#9087]
Aparece a seguinte mensagem" Esse programar só poderá ser instalado em versão windows projetadas para as seguintes arquiteturas de processadores: 1% "  
 como poço resolver isso?

**Comment by mairaw** [comment]
Você pode dar mais detalhes de pq você não conseguiu instalar?

**Comment by Icegreeen** [comment]
@Denilson3661 Qual versão windows você está utilizando ? 32 ou 64 bits ?

Verifique os requisitos no vscode e veja se está compatível com a sua maquina.

**Comment by Icegreeen** [comment]
como você pode ver aqui, o vscode exige 64 bits e apenas windows 10 e 11.

![Captura de tela de 2024-01-25 13-23-19](https://github.com/dotnet/core/assets/56550632/7b3c9cc4-8bd1-4cea-a811-df7b61cd000b)

Pra não ficar sem a instalação, procure versões do vscode que rode aos requisitos compatível com a sua máquina.

Isso aqui pode te ajudar: https://stackoverflow.com/questions/74873644/32-bit-version-of-vs-code-for-windows-7
