### ISSUE TITLE
Roslyn analyzers + code fixes don't work properly in VS when installed into .NET Core project via a nuget package

### ISSUE THREAD

**Issue by HellBrick** [dotnet/core#91]
*(I can't seem to find a repo for raising VS .NET Core tooling issues, so if there's a more appropriate place for this, please tell and I'll be glad to repost it there.)*

Here's what happens when a nuget package that contains Roslyn analyzers + code fixes is installed into a .NET Core project via `install-package $(AnalyzerPackage)`:

1. Analyzer package is added to `References > .NETStandard` node of Solution Explorer instead of `References > Analyzers`.
2. Which also means there's no UI for changing rule severity.
3. Analyzers are not invoked when the code is being edited. The warnings are reported only when the project is built.
4. Even then no squiggles are displayed at the warning location, the warnings are only surfaced in the error list.
5. And probably the most tragic part: the code fixes attached to the analyzer warnings simply can't be triggered.

**Comment by blackdwarf** [comment]
@sayedihashimi where is the best place to file VS-related issues of this kind?

**Comment by sayedihashimi** [comment]
@blackdwarf let's start with https://github.com/dotnet/roslyn-project-system/issues the team can move it if that's not the right spot.

**Comment by blackdwarf** [comment]
Thanks @sayedihashimi. @HellBrick can you please move this issue to the above mentioned repo and close this one? Thanks!

**Comment by sayedihashimi** [comment]
@blackdwarf I went ahead and created https://github.com/dotnet/roslyn-project-system/issues/285 to replace this. Going forward please create the issue yourself  (or ask the OP to do so) with the following info.

- URL to original issue
- Github ID of the OP
