### ISSUE TITLE
Problème 

### ISSUE THREAD

**Issue by Raynn-00** [dotnet/core#9102]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/games/unity-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. Hello, moi j'utilise uniquement  visual studio code et non visual studio code 2022. Cela cause un problème

**Comment by mairaw** [comment]
What kind of problem are you having @Raynn-00?

There's a VS Code extension for Unity that is currently in preview, but the tutorial hasn't been updated to use that yet.
