### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Hassan-Ahmad-Siddiqui** [dotnet/core#9105]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Unable to launch 'h:\PROGRAMING\C#\hello\MyConsoleApp'. '' is not a supported file extension.

**Comment by mairaw** [comment]
What error message do you get @Hassan-Ahmad-Siddiqui? Wondering if using special characters for the folder names like C# is causing some issues.

**Comment by jamesmontemagno** [comment]
I tested out C# folder and working for me. Are you able to take a screenshot for us.
