### ISSUE TITLE
Error installing SDK

### ISSUE THREAD

**Issue by Chumeoden** [dotnet/core#9106]
I installed the .NET 8.0 SDK (v8.0.101) - Windows x64 reported success after running but when I checked with cmd, I installed the following runtime and .NET SDK:

Microsoft.AspNetCore.App 8.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
However, there weren't any .NET SDKs found on my system
![Screenshot 2024-01-30 065007](https://github.com/dotnet/core/assets/117746775/d73df9b5-78d3-44df-b380-d9fc68696843)

**Comment by mairaw** [comment]
I'm seeing some x86 on some directories above, so it might be an issue with your PATH.

Is your machine x64? Can you see what `where.exe dotnet` returns?
If x86 comes first and you have a x64 machine, you might have to follow these instructions:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535
