### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### ISSUE THREAD

**Issue by ArchanaVyas** [dotnet/core#9107]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![Screenshot (394)](https://github.com/dotnet/core/assets/156191927/2bd1af1e-fa67-4c7a-a9eb-5b4d48c6886f)

**Comment by mairaw** [comment]
@danroth27 @captainsafia can you help with this issue?

**Comment by danroth27** [comment]
@ArchanaVyas It looks like you're trying to browse to https://localhost:7137/Components/Pages/Home.razor, but that's the path to the Razor file on disk, not the route to the actual server endpoint. The Home.razor component is set up to handle request to the root of the app. Can you try browsing instead to https://localhost:7137/?

**Comment by mairaw** [comment]
Good catch @danroth27! @ArchanaVyas let us know if changing the URL works for you.
