### ISSUE TITLE
Add support for Ubuntu 24.04

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9112]
This issue is created to track progress for the work to enable Ubuntu 24.04 support for .NET 8.0, .NET 7.0 and, .NET 6.0

### Product and Test updates
- [x] [All teams] Do a compatibility check for the product with the new OS
- [x] [CoreCLR/CoreFX] Runtime / RID Support update  
- [x] [Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable) 
- [x] [Infra] Replace docker tags used in builds across repos and branches
- [x] [CLI team] Update CI legs to latest updated Dockerfile 
- [x] [All teams] Update test infrastructure to support the new version
- [x] [Acquisition] Add support within nightly repos
- [x] [Acquisition] Deploy to master (GA) during next patch release cycle

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [x] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [x] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by carlossanlop** [comment]
@rbhanda Note: Starting with .NET 8.0, the RID graph is frozen. In other words, adding RIDs is currently only needed for 6.0 and 7.0.

For reference, see issue https://github.com/dotnet/runtime/issues/90000 and PRs https://github.com/dotnet/runtime/pull/90297 (which was merged to 8.0 before it was shipped).

**Comment by carlossanlop** [comment]
The 7.0 runtime PR has been closed for the reasons described in the PR: https://github.com/dotnet/runtime/pull/98079#issuecomment-1934981974

The 6.0 runtime PR has been merged.
