### ISSUE TITLE
No se ha encontrado ninguna página web para la dirección web: https://localhost:7279/

### ISSUE THREAD

**Issue by JersseyCruceta** [dotnet/core#9117]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by steveharter** [comment]
Translation: `No web page found for the web address: https://localhost:7279`

**Comment by mairaw** [comment]
¿Puedes mostrar lo que dice el terminal cuando intentas ejecutar la aplicación?
