### ISSUE TITLE
SmtpClient throws NullReferenceException on Dispose()

### ISSUE THREAD

**Issue by sibvic** [dotnet/core#912]
I'm using:
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" />

The next code throws an exception:

            using (var client = new SmtpClient("smtp.mail.ru", 465))
            {
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(Options.EmailSenderUser, Options.EmailSenderPassword);
                client.SendAsync(emailMessage, new object());
            }//throws an exception here!!!

NullReferenceException: Object reference not set to an instance of an object.

    System.Net.Mail.SmtpConnection.ReleaseConnection()
    System.Net.Mail.SmtpClient.Dispose(bool disposing)
    System.Net.Mail.SmtpClient.Dispose()

**Comment by Petermarcu** [comment]
@Priya91, can you copy this over to corefx and maybe take a look?

**Comment by shalaka198** [comment]
Is there any update on this issue? I am facing the same.

**Comment by msvprogs** [comment]
+1, I have the same problem. OS CentOS 7, .NET Core 2.0

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24485](https://github.com/dotnet/corefx/issues/24485) via [**ZenHub**](https://www.zenhub.com/)
