### ISSUE TITLE
Code Format is lost

### ISSUE THREAD

**Issue by ilopachulia** [dotnet/core#9138]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

My code is not formatted in VS code and Rider. The code works without errors and logs everything as intended but the colors are gone.

![image](https://github.com/dotnet/core/assets/89545198/96bccb41-b501-435d-9867-e00184ad8e96)

**Comment by jamesmontemagno** [comment]
It looks like you have the F# extension highlights, but a C# project. Can you ensure you have the C# Dev Kit installed:  https://learn.microsoft.com/en-us/visualstudio/subscriptions/vs-c-sharp-dev-kit

**Comment by ilopachulia** [comment]
James, thank you for your time.
Yes, I guess I installed everything. I installed the C# dev kit and it included the other extensions. What's weird is that I had this issue in Rider as well.

![image](https://github.com/dotnet/core/assets/89545198/5c91594e-5377-4d3b-919a-acce053178d0)

**Comment by jamesmontemagno** [comment]
can you click on the file explorer and not the F# tab:
![image](https://github.com/dotnet/core/assets/1676321/ae72934d-c721-4684-b1bd-654ba72f6bda)

**Comment by ilopachulia** [comment]
The same is everywhere.
![image](https://github.com/dotnet/core/assets/89545198/e68c71d7-6416-45a4-a705-7c83e9b78afd)

**Comment by jamesmontemagno** [comment]
hmmmmm...... @timheuer ? thoughts

**Comment by ilopachulia** [comment]
I tried, deleting rider and cleaning the cash, then deleting vs code as well but it didn't work. With JS it has all the formatting. I didn't changed any settings as well.

**Comment by mairaw** [comment]
and you checked that theme you wanted is selected? when did the problem start?

**Comment by ilopachulia** [comment]
Yes, I switched between the themes as well, but the problem stayed the same. The problem started suddenly after casually opening the vs code I noticed that the theme colors were gone.

**Comment by mairaw** [comment]
I think it would be best to open an issue at https://github.com/microsoft/vscode-dotnettools for the right folks to be able to triage it.

**Comment by ilopachulia** [comment]
Thank you!
