### ISSUE TITLE
Error when running dotnet watch

### ISSUE THREAD

**Issue by janet0404** [dotnet/core#9148]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: macos

I get this error when running dotnet watch code snippet: 
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by mairaw** [comment]
The message "Failed to determine the https port for redirect." is just a warning that you can safely ignore.

We're tracking an improvement of this experience at https://github.com/dotnet/aspnetcore/issues/53229.
