### ISSUE TITLE
Microsoft .NET Core SDK requires OS X 10.12 or later

### ISSUE THREAD

**Issue by kordeviant** [dotnet/core#916]
# Microsoft .NET Core SDK requires OS X 10.12 or later
![image](https://user-images.githubusercontent.com/22198402/29886779-85b9cc3e-8dd0-11e7-95d6-a0dfabb23e85.png)

this clearly is an issue because OS X 10.12 version is not supported for all Apple's currently working products and leads to Apple's income increase, not being a support act for open movement.

**Comment by svick** [comment]
https://github.com/dotnet/core/issues/732 has some information about why 10.11 is no longer supported.

**Comment by Petermarcu** [comment]
Yes, this was a requirement to get rid of the OpenSSL dependency that was a bit of an acquisition nightmare to say the least. Closing this because it was an intentional decision.
