### ISSUE TITLE
.NET February 2024 Update - .NET 8.0.2, NET 7.0.16, .NET 6.0.27

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9163]
# .NET February 2024 Update

## Release Notes
* [8.0.2](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.2/8.0.2.md)
* [7.0.16](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.16/7.0.16.md)
* [6.0.27](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.27/6.0.27.md)

## Status

Asset Type | 8.0.2| 7.0.16 | 6.0.27 | Notes
-- | :--:  | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) | ✅|✅ | ✅ 
|| |
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) | ✅|✅ | ✅ 
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)  | NA|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 8](https://learn.microsoft.com/dotnet/core/install/linux-centos)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 37](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 38](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 39](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)   | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp;  [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅|✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  | ✅|✅ | ✅ 

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by wasabii** [comment]
https://github.com/dotnet/aspnetcore/issues/54019

**Comment by Hrxn** [comment]
Okay, so the official [`8.0.2` release notes](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.2/8.0.2.md) state the following:

> You can check your .NET SDK version by running the following command. The example version shown is for this release.
```
$ dotnet --version
8.0.200
```

I just ran Windows update, and the 8.0.2 update from February 13 should be installed (also did a restart, to be sure)
![01](https://github.com/dotnet/core/assets/12064918/86bb2df1-2860-4695-b173-7a4bfa873130)

Yet, I get this here
```bat
C:\>dotnet --version
8.0.102

C:\>
```

What's that supposed to mean?

**Comment by evgenyvalavin** [comment]
I use Microsoft-Hosted Azure DevOps agents.
Seems like there's something with `dotnet restore` command. Everything work fine yesterday before .NET 8.0.200 release.
iOS project uses .NET 8

.NET 8.0.101
`/Users/runner/hostedtoolcache/dotnet/dotnet workload restore /Users/runner/work/1/s/src/iOS.csproj`

Output:
```
Installing workloads: ios

Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.android version 34.0.52...
Installing workload manifest microsoft.net.sdk.ios version 17.2.8004...
Installing workload manifest microsoft.net.sdk.maccatalyst version 17.2.8004...
Installing workload manifest microsoft.net.sdk.macos version 14.2.8004...
Installing workload manifest microsoft.net.sdk.tvos version 17.2.8004...
Installing workload manifest microsoft.net.sdk.aspire version 8.0.0-preview.2.23619.3...
Installing pack Microsoft.iOS.Sdk version 17.2.8004...
Writing workload pack installation record for Microsoft.iOS.Sdk.net8 version 17.2.8004...
Installing pack Microsoft.iOS.Sdk version 16.4.7129...
Writing workload pack installation record for Microsoft.iOS.Sdk.net7 version 16.4.7129...
```

.NET 8.0.200
`/Users/runner/hostedtoolcache/dotnet/dotnet workload restore /Users/runner/work/1/s/src/iOS.csproj`

```
Installing workloads: ios

Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.aspire version 8.0.0-preview.3.24105.21...
Installing pack Microsoft.iOS.Sdk version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Sdk.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Sdk version 16.4.7099...
Writing workload pack installation record for Microsoft.iOS.Sdk.net7 version 16.4.7099...
Installing pack Microsoft.iOS.Ref version 16.4.8825-net8-rc1...
```

There's no sign of installing Microsoft.iOS.Sdk version 17.2 in the second case when using .NET 8.0.200.

**Comment by darthkurak** [comment]
Does the sdk 8.0.2 bump somehow use a version of MSBuild.StructuredLogger ? 
I have FAKE scripts that started to fail after upgrading to the 8.0.2 SDK

`Unsupported log file format. Latest supported version is 16, the log file has version 17.` 

(I have MSBuild.StructuredLogger (2.1.815))

**Comment by Hrxn** [comment]
> I just ran Windows update, and the 8.0.2 update from February 13 should be installed (also did a restart, to be sure) ![01](https://private-user-images.githubusercontent.com/12064918/304624634-86bb2df1-2860-4695-b173-7a4bfa873130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjkwNzAsIm5iZiI6MTcwNzkyODc3MCwicGF0aCI6Ii8xMjA2NDkxOC8zMDQ2MjQ2MzQtODZiYjJkZjEtMjg2MC00Njk1LWIxNzMtN2E0YmZhODczMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE2MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Y2VlMzY4YmE0OTM5YzVjNDlmNmJmMGY4YjkwOWI4NWNmZDYzNTk5MjE1ZGNkM2VhOTliZTg0NjJkMjMyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4VZFJNBjzqLdhL6ReG00WULpuLeJsqfOy-yAqFV8gLE)
> 
> Yet, I get this here
> 
> ```batchfile
> C:\>dotnet --version
> 8.0.102
> 
> C:\>
> ```
> 
> What's that supposed to mean?

Okay, just for kicks and giggles, I downloaded and ran the SDK x64 Installer package, you know, the thing, the one behind the big, fat purple download button on `https://dotnet.microsoft.com/en-us/download`.

And, lo and behold:

```
PS C:\> dotnet --version
8.0.200
PS C:\>
```

I assume this is intentional, but I'm not sure, maybe this should be mentioned somewhere, just to prevent confusion in the first place 🤪 
PS. Don't remember this being the case with .NET 8.0.1, though.

**Comment by vernou** [comment]
@Hrxn 
A **.NET Runtime** version can have multiple **SDK version**. See [How .NET is versioned](https://learn.microsoft.com/en-us/dotnet/core/versions/#versioning-details) for more information.

It's the case with `.NET 8.0.2` that has the two SDK versions `8.0.200` and `8.0.102` (see [.NET 8 download page](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)).

---

**Windows Update** update the runtime, but not the SDK. I think it's a VS update (can be managed by Windows Update) that updated your SDK.

**Comment by Hrxn** [comment]
Thank you @vernou , that was exactly what I was looking for. .NET documentation article explaining the versioning. Appreciate it.

**Comment by jattinc** [comment]
Github actions failing because 8.0.201 not available to download.

https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-win-x64.zip.

**Comment by AlexeyRaga** [comment]
Same for Linux, lots of CI is broken because 8.0.201 is not available to download.

https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-linux-x64.tar.gz

**Comment by baronfel** [comment]
> Does the SDK 8.0.2 bump somehow use a version of MSBuild.StructuredLogger ? 
> I have FAKE scripts that started to fail after upgrading to the 8.0.2 SDK
> 
> `Unsupported log file format. Latest supported version is 16, the log file has version 17.` 
> 
> (I have MSBuild.StructuredLogger (2.1.815)) 
> 
> And the same script is working on 8.0.1

Yes, most quarterly SDK releases will bump the format as we add new events. However, the next quarter's release (May) should be the first one where the format supports forward compatibility, so this blocking error should go away once you update to that series of MSBuild Structured Logger packages.

**Comment by mairaw** [comment]
> Same for Linux, lots of CI is broken because 8.0.201 is not available to download.
> 
> https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-linux-x64.tar.gz

@AlexeyRaga @jattinc the team is aware of the issue and is looking into it. 
The workaround would be to not use 8.0.x and specify a specific version other than 201.
We'll let you know when things are back to normal.

**Comment by rbhanda** [comment]
> > Same for Linux, lots of CI is broken because 8.0.201 is not available to download.
> > https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-linux-x64.tar.gz
> 
> @AlexeyRaga @jattinc the team is aware of the issue and is looking into it. The workaround would be to not use 8.0.x and specify a specific version other than 201. We'll let you know when things are back to normal.

Hi @AlexeyRaga @jattinc , apologies for the delay in fixing this issue. https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-linux-x64.tar.gz should be working and available now.

**Comment by csehammad** [comment]
Encountered a breaking change in #aspnet core MVC after updating to .NET 8.0.2 - "Index view not found" error. Resolved by rolling back the update. Details & discussion here:   https://techcommunity.microsoft.com/t5/net-runtime/net-8-0-2-update-causes-asp-net-core-mvc-index-view-not-found/m-p/4058976#M382

**Comment by meenzen** [comment]
There does not appear to be an oci-image `mcr.microsoft.com/dotnet/sdk:8.0.201` for the latest sdk update. Will this be published soon?

**Comment by axylophon** [comment]
Does anybody else also has problems with `dotnet format`?

We use a Blazor WASM application and use dotnet format `--verify-no-changes` in our CI Pipeline.
We also have an .editorconfig file in place.

Since 8.0.201 we get lots of false positives that Methods/Properties in razor.cs code behind files are not used. But they are all used in the .razor file.

If we revert to 8.0.101 the issue is gone.

**Comment by joncham** [comment]
I am seeing `csc` hang/delay for 20s when run with the `/shared` argument. I assume it's trying to launch the server process and failing or failing to connect.

https://github.com/dotnet/sdk/issues/38850

**Comment by Devqon** [comment]
> Encountered a breaking change in #aspnet core MVC after updating to .NET 8.0.2 - "Index view not found" error. Resolved by rolling back the update. Details & discussion here: https://techcommunity.microsoft.com/t5/net-runtime/net-8-0-2-update-causes-asp-net-core-mvc-index-view-not-found/m-p/4058976#M382

We have also experienced this issue, even creating a completely clean/new web project fails with this error. Downgrading to 8.0.102 works.
I see there is a patch released (201) but it does not mention this bug

**Comment by cmenzi** [comment]
The package is still not available here:
- https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/
- https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/binary-amd64/Packages

`apt-get install -yq dotnet-sdk-8.0=8.0.201-1` fails

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/9214
