### ISSUE TITLE
How to run tests against IL Linked assemblies?

### ISSUE THREAD

**Issue by rubberduck203** [dotnet/core#917]
The IL Linker announced in #915 is fantastic.
I'm seeing a 71% reduction in final size!

The [Linker Instructions](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) mention that the final executables need to be tested after linking.

> Linking only happens during publish, and therefore the linked app needs to be tested after publish, not just after build.

This makes complete sense, but I can't find any information on how to run my tests with `dotnet test` against an already compiled executable. Is there a way? If so, can this information (or a link to it) be added to the linker instructions?

**Comment by Petermarcu** [comment]
That is a great question. @ManishJayaswal can you give any advice on how someone can run their tests against a published output?

**Comment by ManishJayaswal** [comment]
I don't think we have a good solution at this time other than to publish the tests as apps and then run them.
@codito - do you know if you guys are thinking about this?

**Comment by Petermarcu** [comment]
Let's track this issue here and make sure folks have instructions on how to do it. https://github.com/dotnet/cli/issues/7570
