### ISSUE TITLE
.Net 8 not in CentOs 7.x repo

### ISSUE THREAD

**Issue by kingmotley** [dotnet/core#9173]
.Net 8 seems to be missing from Microsoft's CentOS 7.X repo: https://packages.microsoft.com/centos/7/prod/Packages/d/

**Comment by leecow** [comment]
Hey @kingmotley - .NET 8 is incompatible with CentOS 7 (and RHEL 7 + relatives). Complete .NET 8 OS compat list at https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md.
