### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80131500 on Linux Docker container

### ISSUE THREAD

**Issue by Parth6288** [dotnet/core#918]
Hi,

Developing the app on Windows, it runs fine on Windows. When trying to run the published release build on CentOS7, it works fine. However running it on Linux container, it throws this error:Failed to initialize CoreCLR, HRESULT: 0x80131500

Creation of a new app inside the container and running it works, but I want to build on Windows and host on Linux container.

Dotnet info:
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/
--- End breadcrumb write 0

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Any Ideas?

**Comment by omajid** [comment]
Can you install `strace` in your container and run `strace` on `dotnet`? If your original command is:

     dotnet /path/to/dll

The strace version becomes

    strace -o logfile dotnet /path/to/dll

And please upload `logfile` from the container to somewhere public.

**Comment by Parth6288** [comment]
Attached is the log file.

[dotnetstracelog.txt](https://github.com/dotnet/core/files/1269238/dotnetstracelog.txt)

**Comment by Petermarcu** [comment]
@janvorli looks like there is a lot of probing for System.Globalization.Native.so. Any thoughts?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #14444](https://github.com/dotnet/coreclr/issues/14444) via [**ZenHub**](https://www.zenhub.com/)
