### ISSUE TITLE
releases.json shows incorrect version of Visual Studio

### ISSUE THREAD

**Issue by timheuer** [dotnet/core#9181]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/8.0/releases.json#L358

### Description

This lists "Visual Studio 2023" which doesn't exist and should be "Visual Studio 2022" -- this shows up on the .NET download site pages.

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/9184 - to fix this

**Comment by mairaw** [comment]
I see the fix live on the website too
![image](https://github.com/dotnet/core/assets/12971179/98be2f81-fea1-4945-97ee-fbf3b9886ccd)
