### ISSUE TITLE
No RC2 SDK found with VS 15 Preview2?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/core#92]
No RC2 SDK found with VS 15 Preview2?

**Comment by MikeJoyce19** [comment]
Are you getting a message upon opening that solution that you have an incompatible dotnet sdk version?

If so, I had to uninstall the existing dotnet.exe after installing the new sdk version.  Both versions were on PATH and I believe the earlier version was taking precedence

**Comment by blackdwarf** [comment]
@yyjdelete in general, if you wish to use RC2 bits and newer, you need to uninstall any older (pre-RC2) bits you have on the machine. This guidance can also be found on the [Getting Started page](https://microsoft.net/core/). 

With this, I will close this issue. In the future, please open these kinds of issues on dotnet/cli repo.  Thanks!
