### ISSUE TITLE
Release indexes on the different feeds have different values

### ISSUE THREAD

**Issue by agocke** [dotnet/core#9200]
See

https://dotnetcli.azureedge.net/dotnet/release-metadata/releases-index.json

https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json

Latest SDK on the first one is 8.0.200
Latest SDK on the second one is 8.0.201

**Comment by rbhanda** [comment]
Looks like it was a cache issue. It should be resolved now. I see both jsons reflecting latest 8.0.201 sdk
