### ISSUE TITLE
Can not use dotnet command because of loading hostfxr.dll failed 

### ISSUE THREAD

**Issue by maonaoda** [dotnet/core#9203]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.2/8.0.201.md

### Description

After I upgraded Microsoft Visual Studio 17.9.0 （windows）, there seemed to be something wrong with the local dotnet environment,
So I deleted the local C:\Program Files\dotnet folder and used the downloaded dotnet-sdk-8.0.201-win-x64.exe to repair it. After that, my dotnet command could not be used at all.
``` 
>dotnet --version

Failed to load the dll from [C:\Program Files\dotnet\host\fxr\8.0.2\hostfxr.dll], HRESULT: 0x800700C1

The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\8.0.2\hostfxr.dll failed

  - Installing .NET prerequisites might help resolve this problem.

    
https://go.microsoft.com/fwlink/?linkid=798306
```

**Comment by harish-venkataramanan-cko** [comment]
I am having the same issue on m2 mac

**Comment by maonaoda** [comment]
@harish-venkataramanan-cko 
I temporarily solved this problem by using a past version of dotnet.exe, but I didn`s try it on mac.

**Comment by buyaa-n** [comment]
> So I deleted the local C:\Program Files\dotnet folder 

That would not uninstall the old dotnet properly. Try to uninstall it properly from `Apps -> Installed apps` again, and reinstall dotnet.

Anyway, this is not a dotnet issue, so closing
