### ISSUE TITLE
Entitlements.plist in the macOS (macos workload) seems to not be functioning

### ISSUE THREAD

**Issue by colmugx** [dotnet/core#9207]
### Package Id

macos workload

### Package Version(s)

14.2.8004/8.0.100

### Additional details

> Sorry, I've looked through all the categories, but I don't know where my question belongs, so I can only temporarily ask it here.

I attempted to create a net8.0-macos project and utilize the Calendars permission (I'll be accessing Reminders via EKEventStore). Everything seems set up correctly, but debugging reveals that this doesn't seem to be working.

I also tried with both Swift Native projects and Mac Catalyst projects with C#(maccatalyst workload), and they works well.

**Comment by mairaw** [comment]
@jamesmontemagno do you know how to best route this?

**Comment by jamesmontemagno** [comment]
https://github.com/xamarin/xamarin-macios

**Comment by colmugx** [comment]
Awesome! Thank you everyone!
