### ISSUE TITLE
.NET March 2024 Update - .NET 8.0.3, NET 7.0.17, .NET 6.0.28

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9214]
# .NET March 2024 Update

## Release Notes
* [8.0.3](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.3/8.0.3.md)
* [7.0.17](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.17/7.0.17.md)
* [6.0.28](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.28/6.0.28.md)

## Status

Asset Type | 8.0.3| 7.0.17 | 6.0.28 | Notes
-- | :--:  | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet)
|| |
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) |✅ |✅ |✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)  | NA|✅ |✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 8](https://learn.microsoft.com/dotnet/core/install/linux-centos)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 37](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 38](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 39](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)   |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp;  [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ |✅ |✅

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by ptasev** [comment]
The release notes document links to docker for each repo.

Also, the experience of navigating new releases is poor. I have not been able to figure out how to go from the release notes document to see what changes have been made for each repo.

Also, where do I go to find out what the difference is between the SDK versions? There's 103 and 202 now and no matter how many links I follow through these release documents I still haven't been able to figure out the difference.

**Comment by devlead** [comment]
And, last night 8.0.203 was released, but several packages and containers are still missing i.e. sdk:8.0.203-alpine3.18

**Comment by cmenzi** [comment]
Again. The package is  not available here:

- https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/
- https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/binary-amd64/Packages
apt-get install -yq dotnet-sdk-8.0=8.0.203-1 fails

**Comment by hilari0n** [comment]
Could anyone point me to where can I find the differences between SDK versions 8.0.202 and 8.0.203?

**Comment by Phyyl** [comment]
A user of ours is having issues when 8.0.3 is installed. When rolling back to 8.0.2, the application works as intended. The app crashes with this error message: 
```
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFD5906C5E4 (0x00007FFD58EE0000) with exit code 0x80131506.
```
Any ideas? Thanks a lot!

**Comment by MoeHamdan** [comment]
Ubuntu 22.04, failed to install .net 8
After this operation, 591 MB of additional disk space will be used.
Ign:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1                                                                            
Ign:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1                                                                            
Ign:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1                                                                            
Err:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
  Connection failed [IP: 13.107.213.43 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb  Connection failed [IP: 13.107.213.43 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by moritzm** [comment]
> Ubuntu 22.04, failed to install .net 8 After this operation, 591 MB of additional disk space will be used. Ign:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 Ign:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 Ign:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 Err:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 Connection failed [IP: 13.107.213.43 443] E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb Connection failed [IP: 13.107.213.43 443] E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

For me, it is now (today) working. I had the same issue for one week, but now i can update.

**Comment by MoeHamdan** [comment]
I am still having the issue, not fixed yet for me

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/9263

**Comment by hilari0n** [comment]
> closing in favor of #9263

How is it addressing the questions asked here?
