### ISSUE TITLE
Dotnet Package for centos not installing from https://packages.microsoft.com/centos/8/prod/Packages/d/

### ISSUE THREAD

**Issue by tapadarj** [dotnet/core#9224]
### URL(s)

https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm

### Description

Everything was working when installing dotnet 8.0 sdk from https://packages.microsoft.com/centos/8/prod/Packages/d/ till yesterday.

Today from 13th March, 2024 its started giving issue when installing dotnet sdk 8.0 in linux. The issue is coming when downloading dependency : https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm

After spending few hours we have noticed dotnet-runtime-8.0-8.0.3-1.x86_64.rpm is added yesterday in the packages.microsoft.com and this is causing the issue. please check the issue.

Downloading packages:
warning: /var/cache/yum/x86_64/2/packages-microsoft-com-prod/packages/aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
Public key for aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm is not installed
https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: [Errno 14] curl#92 - "HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)"
Trying other mirror.

Error downloading packages:
  dotnet-runtime-8.0-8.0.3-1.x86_64: [Errno 256] No more mirrors to try.
  
  Can you plesae look into this and provide soultion.

**Comment by ArturEnache** [comment]
Same error encountered on Rocky Linux 9 + RHEL 9 repository, for the same package:

Downloading Packages:
[SKIPPED] aspnetcore-runtime-8.0-8.0.3-1.x86_64.rpm: Already downloaded
[SKIPPED] aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm: Already downloaded
[SKIPPED] dotnet-apphost-pack-8.0-8.0.3-1.x86_64.rpm: Already downloaded
[SKIPPED] dotnet-host-8.0.3-1.x86_64.rpm: Already downloaded
[SKIPPED] dotnet-hostfxr-8.0-8.0.3-1.x86_64.rpm: Already downloaded
[SKIPPED] dotnet-runtime-deps-8.0-8.0.3-1.x86_64.rpm: Already downloaded
[SKIPPED] dotnet-targeting-pack-8.0-8.0.3-1.x86_64.rpm: Already downloaded
[MIRROR] dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: Curl error (18): Transferred a partial file for https://packages.microsoft.com/rhel/9.0/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm [transfer closed with 14151976 bytes remaining to read]
[MIRROR] dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: Curl error (18): Transferred a partial file for https://packages.microsoft.com/rhel/9.0/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm [transfer closed with 14151976 bytes remaining to read]
[MIRROR] dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: Curl error (18): Transferred a partial file for https://packages.microsoft.com/rhel/9.0/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm [transfer closed with 14151976 bytes remaining to read]
[MIRROR] dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: Curl error (18): Transferred a partial file for https://packages.microsoft.com/rhel/9.0/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm [transfer closed with 14151976 bytes remaining to read]
[FAILED] dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(9-10/10): netstandard-targeting-pack-2.1.0-x64.rpm               54% [===================================                             ] 113 MB/s | 117 MB     00:00 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Error downloading packages:
  dotnet-runtime-8.0-8.0.3-1.x86_64: Cannot download, all mirrors were already tried without success

**Comment by tbregolin** [comment]
Having the same issue trying to download _/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb_:
```
$ curl https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 45  105M   45 48.0M    0     0  92.3M      0  0:00:01 --:--:--  0:00:01 92.3M
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
$ curl --http1.1 https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 45  105M   45 48.0M    0     0  92.3M      0  0:00:01 --:--:--  0:00:01 92.4M
curl: (18) transfer closed with 59919438 bytes remaining to read
```

The previous version (_dotnet-sdk-8.0_8.0.202-1_amd64.deb_) downloads fine.

This is only in some locations. This one is not working:
```
pmc-prod-afd-endpoint-evdhh8f8byhsezfp.b01.azurefd.net.
shed.dual-low.part-0043.t-0009.t-msedge.net.
part-0043.t-0009.t-msedge.net.
13.107.246.71
13.107.213.71
```

But this one is:
```
pmc-prod-afd-endpoint-evdhh8f8byhsezfp.b01.azurefd.net.
shed.dual-low.part-0017.t-0009.t-msedge.net.
part-0017.t-0009.t-msedge.net.
13.107.213.45
13.107.246.45
```

**Comment by chriscarpenter12** [comment]
@tbregolin I'm seeing the same issue today trying to build our own runner-images. Packer builds are failing because it can't fetch the deb.

```
    vm.qemu.ubuntu: Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 [110 MB]
    vm.qemu.ubuntu: Ign:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
    vm.qemu.ubuntu: Ign:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
    vm.qemu.ubuntu: Ign:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
    vm.qemu.ubuntu: Err:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
    vm.qemu.ubuntu:   Error reading from server. Remote end closed connection [IP: 13.107.213.51 443]
    vm.qemu.ubuntu: Fetched 39.1 MB in 11s (3,458 kB/s)
==> vm.qemu.ubuntu: E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb  Error reading from server. Remote end closed connection [IP: 13.107.213.51 443]
==> vm.qemu.ubuntu: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Seems isolated to this one file as both `dotnet-sdk-6.0` and `dotnet-sdk-7.0` download fine.

**Comment by joshuaboniface** [comment]
I'm seeing similar issues as well, reported in https://github.com/dotnet/core/issues/4734#issuecomment-2029168106 first as it was the first one my search turned up. Copying here for posterity:

---

It's also happening again here, but in our case, from GitHub Actions workers (inside Docker containers of various Debian and Ubuntu versions) and my own system, over the last 4 days at least. 


4 days ago: https://github.com/jellyfin/jellyfin-packaging/actions/runs/8461568587/job/23181631250#step:8:2092
Right now: https://github.com/jellyfin/jellyfin-packaging/actions/runs/8504055422/job/23290430328#step:8:2279
My own system:
```
joshua@base git:master ~/Projects/Jellyfin/projects/server/jellyfin-packaging $ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  bsdextrautils bsdutils containerd.io docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin dotnet-sdk-8.0 fdisk firefox-esr libblkid1 libfdisk1 libmount1 libsmartcols1 libuuid1 libwbclient0 mount nodejs util-linux
  uuid-runtime
20 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 110 MB/319 MB of archives.
After this operation, 4,129 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://packages.microsoft.com/debian/11/prod bullseye/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
  Connection failed [IP: 13.107.246.35 443]
E: Failed to fetch https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb  Connection failed [IP: 13.107.246.35 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

What's very curious though is that fetching the file with `wget` does work:

```
joshua@base git:master ~/Projects/Jellyfin/projects/server/jellyfin-packaging $ wget https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb 
--2024-04-01 01:07:22--  https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.107.213.35, 13.107.246.35, 2620:1ec:46::35, ...
Connecting to packages.microsoft.com (packages.microsoft.com)|13.107.213.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110251086 (105M) [application/octet-stream]
Saving to: ‘dotnet-sdk-8.0_8.0.203-1_amd64.deb’

dotnet-sdk-8.0_8.0.203-1_amd64.deb                            6%[========>                                                                                                                                  ]   6.85M  4.21MB/s               ^C
```

But of course, being an `apt` repo, it must work in `apt`.

This should definitely be reopened and checked by whoever is in charge of this infrastructure.

**Comment by leecow** [comment]
Ok, a number of issues in this thread. I have looked at a few of them so far. 

- @tapadarj - installing .NET 8 on CentOS 8 from packages.microsoft.com tests good for me this morning. Are you still having issues there?
- @ArturEnache - installing .NET 8 on Rocky 9 from packages.microsoft.com works for me as long as I include `--disablerepo=appstream` in the yum command. Otherwise, packages.microsoft.com and the Rocky appstream get crossed up. 
- @joshuaboniface - installing .NET on Debian 11 from packages.microsoft.com is also working this morning. Can you confirm? I'll check with that team to see if there were any observed outages in the last day.

**Comment by DubyaDude** [comment]
No longer receiving the issue on Ubuntu 22.04, I was able to successfully upgrade.

**Comment by joshuaboniface** [comment]
@leecow Seems to all be working today for me as well. We build this CI regularly so if it happens again I'll report back into this thread.

**Comment by tbregolin** [comment]
No longer seeing the issue from LAX either. Thanks!

**Comment by ArturEnache** [comment]
@leecow it is working for the RHEL repository too. Thanks!

**Comment by iluwaaa** [comment]
```bash
$ sudo rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm 
Retrieving https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm sudo yum install dotnet-runtime-6.0 
curl: (7) Failed to connect to packages.microsoft.com port 443: Connection timed out 
error: skipping https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm - transfer failed
```

**Comment by leecow** [comment]
@iluwaaa - I was able to `$ sudo rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm` today. However, CentOS 8 went EOL some time ago and CentOS Stream 8 is EOL the end of this month. The 6.0 and 8.0 May updates published to packages.microsoft.com will be our last update for CentOS 8.
