### ISSUE TITLE
Release notes link broken

### ISSUE THREAD

**Issue by tomrus88** [dotnet/core#9243]
### URL(s)

https://github.com/dotnet/core/tree/main/release-notes

### Description

For .NET 9 it links to https://github.com/dotnet/core/blob/main/release-notes/release-notes/9.0/README.md (404) instead of https://github.com/dotnet/core/blob/main/release-notes/9.0/README.md

**Comment by mairaw** [comment]
Thanks for letting us know. I opened a PR to fix this.
