### ISSUE TITLE
Getting Failed to fetch https://packages.microsoft.com/repos/edge/dists/stable for the last few hours

### ISSUE THREAD

**Issue by bryan-lee-7r** [dotnet/core#9276]
### Description
Unable to download on Debian. Been getting the following on some of our machines (in CircleCI) for a few hours:

```
E: Failed to fetch https://packages.microsoft.com/repos/edge/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (8083 != 8146). Mirror sync in progress? [IP: 13.107.226.40 443]
   Hashes of expected file:
    - Filesize:8146 [weak]
    - SHA512:f88a84810e458448697df38de19eed7b211b601c7c469d6852383e4a3a0311d771d22a47a1a11987be1a3b428bf8ba4888c26c9c2346c5e381b248f4c257d999
    - SHA256:bec62db376e96d917e4ceed82a5a73b71003d555aa017b2ee5ae7f21b3ae914b
   Release file created at: Fri, 12 Apr 2024 17:59:51 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Regression?
Not really a regression, but this was working as recently as yesterday.

Other ### information
Docs said to open an issue if this lasts for more than 30 minutes:

https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#failed-to-fetch

> While installing the .NET package, you may see an error similar to Failed to fetch ... File has unexpected size ... Mirror sync in progress?. This error could mean that the package feed for .NET is being upgraded with newer package versions, and that you should try again later. During an upgrade, the package feed shouldn't be unavailable for more than 30 minutes. If you continually receive this error for more than 30 minutes, please file an issue at https://github.com/dotnet/core/issues.

**Comment by adamsitnik** [comment]
Hello @bryan-lee-7r ! Does the issue still persist?

**Comment by bryan-lee-7r** [comment]
> Hello @bryan-lee-7r ! Does the issue still persist?

Hello @adamsitnik, I just double checked and it looks like this issue has been resolved. I appreciate you checking back in, I'll close this issue now that it's resolved.
