### ISSUE TITLE
Is there an API to get the latest preview .NET SDK version

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/core#9280]
Hi there, from the devcontainer dotnet feature

We could get the latest lts version via `https://dotnetcli.azureedge.net/dotnet/Sdk/LTS/latest.version`

So is there an API to get the latest preview version info? I want to support using `preview` for the latest preview version

Is there any api catalog list for the `https://dotnetcli.azureedge.net` apis?

https://github.com/devcontainers/features/blob/main/src/dotnet/scripts/dotnet-helpers.sh

**Comment by ManickaP** [comment]
Reverse negineering https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script I got for example: https://dotnetcli.azureedge.net/dotnet/Sdk/9.0/latest.version

> Is there any api catalog list for the https://dotnetcli.azureedge.net apis?

@YuliiaKovalova any idea about the full list of APIs?

**Comment by YuliiaKovalova** [comment]
Hi @ManickaP,

I am not aware of any other APIs for preview.
@MilenaHristova, could you share details if you know more?

**Comment by MilenaHristova** [comment]
> Hi @ManickaP,
> 
> I am not aware of any other APIs for preview. @MilenaHristova, could you share details if you know more?

The latest preview is in https://dotnetcli.azureedge.net/dotnet/Sdk/9.0/latest.version as you said. This file is updated after a release so once we release .NET 9 it will have a non-preview version. I'm not aware of a proper catalog of dotnetcli, @rbhanda do you know?

**Comment by rbhanda** [comment]
> > Hi @ManickaP,
> > I am not aware of any other APIs for preview. @MilenaHristova, could you share details if you know more?
> 
> The latest preview is in https://dotnetcli.azureedge.net/dotnet/Sdk/9.0/latest.version as you said. This file is updated after a release so once we release .NET 9 it will have a non-preview version. I'm not aware of a proper catalog of dotnetcli, @rbhanda do you know?

https://github.com/dotnet/core/blob/main/release-notes/9.0/releases.json - this lists all the SDKs we have released for .NET 9.0 so far

**Comment by richlander** [comment]
The `9.0/releases.json` file is a bit large to just get one value.

The root `releases-index.json` file is much smaller and can serve the same scenario.

`https://github.com/dotnet/core/blob/main/release-notes/releases-index.json`

**Comment by ManickaP** [comment]
Hope this answers your question. I'll close this. Feel free to re-open if you have more questions.
