### ISSUE TITLE
Package installation instructions are stale and need to be updated

### ISSUE THREAD

**Issue by richlander** [dotnet/core#9287]
The instructions should be updated for .NET 6, 8, and 9. They should include all the OS versions we support. It is OK if they include out-of-support OSes. I think deleting information is bad form in this context.

- https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md
- https://github.com/dotnet/core/blob/main/release-notes/8.0/linux-packages.md
- https://github.com/dotnet/core/blob/main/release-notes/9.0/linux-packages.md

The 9.0 instructions also appear to be missing a space in several places.

https://github.com/dotnet/core/blob/c6939c4faf415feae51c530e47091a3aedc561a3/release-notes/9.0/linux-packages.md#L40

**Comment by richlander** [comment]
Can you take this @ashnaga or @rbhanda?

**Comment by ashnaga** [comment]
PRs
6.0 - https://github.com/dotnet/core/pull/9288
8.0 - https://github.com/dotnet/core/pull/9289
9.0 - https://github.com/dotnet/core/pull/9290

**Comment by richlander** [comment]
Looks good. It would be good to add Fedora 40 and Debian 13. It's fine if that's .NET 8+.

**Comment by leecow** [comment]
All changes merged. Closing this issue.
