### ISSUE TITLE
Where from I can download Preview 2 Final Version

### ISSUE THREAD

**Issue by goforgold** [dotnet/core#929]
I didn't yet updated my project to .NET Core 2.0 yet. I need to install `.NET Core 2.0 Preview 2 Final` release on my MAC OSX.

I found a link
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md

but this doesn't seem to be for Preview 2 Final version.

Can someone help me?

**Comment by svick** [comment]
That should be the final version .Net Core 2.0 Preview 2. What makes you think it's not?

Though I don't see any reason why you should use that version, the final version of .Net Core 2.0 should be better in every way.

**Comment by goforgold** [comment]
Hi @svick 

At your recommendation, I tried migrating from Preview 2 Final to Latest Stable but facing issues.

I've posted detailed in a separate issues #930 for this.

**Comment by Petermarcu** [comment]
It looks like you already have the link to the Preview 2 final version and have filed a separate issue for your issues migrating from Preview2 to RTM. Any reason this issues needs to stay open?

**Comment by goforgold** [comment]
No.

**Comment by Petermarcu** [comment]
Sounds good. Closing now.
