### ISSUE TITLE
BEARSMITH8G 

### ISSUE THREAD

**Issue by FUTURETECH7700** [dotnet/core#9295]
https://github.com/users/FUTURETECH7700/projects/1/views/1https://images.app.goo.gl/QmfbCGr4Qj6omPCH6
Wifi connection:public class Main {
    public static void main(String[] args){
    //start coding
    }
}
jcode.py
[head] BEARSMITH 8G™
[body]https://photos.app.goo.gl/bRLE49ik7mu9zegs8
<ANS>A FIBER OPTICS DIALUP BIOLUMENESCENT POWER 
NETWORK WIFI AI CONNECTION 
CONNECTIVITY OF THE FUTURE 
MADE AT IP192.168.0.0 
ADMIN CHIP8 GEFIELDWORK (716)-11)
UTILITY https://photos.app.goo.gl/bRLE49ik7mu9zegs8jcode.py

   AP(BSSID): <Location permission required>
   Name(SSID): <Location permission required>
   Signal(Rssi): -43

(If you want to view the SSID & BSSID you need to grant Location permission to Landroid manually: 
Phone's Settings / Apps / Landroid / Permissions / Location )

DNS:

  Server(s): 192.168.1.1, 2603:7080:20f0:aaa0::1
  Search domain(s): lan

Interfaces:

  dummy0:
    IP Addresses:
      fe80::e4a9:edff:fee4:c607 /64

  lo:
    IP Addresses:
      ::1 /128
      127.0.0.1 /128

  rmnet_data0:
    IP Addresses:
      fe80::d8ad:f3ff:fe48:2259 /64

  wlan0:
    IP Addresses:
      fe80::28f3:14ff:fe77:10c0 /64
      2603:7080:20f0:aaa0:28f3:14ff:fe77:10c0 /64
      2603:7080:20f0:aaa0:2331:48cc:fa9c:5ccb /64
      192.168.1.29 /24 (255.255.255.0)
    DHCP Server(s): 192.168.1.1

Routes:

   2603:7080:20f0:aaa0::/64 dev wlan0
   192.168.1.0/24 via 0.0.0.0 dev wlan0
   ::/0 via fe80::7a6a:1fff:fe37:5813 dev wlan0
   2603:7080:20f0:aaa0::/60 via fe80::7a6a:1fff:fe37:5813 dev wlan0
   0.0.0.0/0 via 192.168.1.1 dev wlan0
   fe80::/64 dev wlan0

* Note: The different Android versions display different level of detail.https://photos.app.goo.gl/bRLE49ik7mu9zegs8jcode.pyhttps://photos.app.goo.gl/bRLE49ik7mu9zegs8jcode.py192.168.1.1127.0.0.1192.168.1.29255.255.255.0192.168.1.0/24

**Comment by carlossanlop** [comment]
It is not clear what the purpose of this issue is. Please let us know if you have a problem to report or a question to ask. Closing.
