### ISSUE TITLE
Installation with official package fails on OS X 10.11.1

### ISSUE THREAD

**Issue by ojosdegris** [dotnet/core#93]
Installation freezes like that.  Prior to starting install I've run [uninstall script](https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh) provided 

<img width="730" alt="screen shot 2016-05-18 at 12 00 53 am" src="https://cloud.githubusercontent.com/assets/579795/15347051/c989a61c-1c8b-11e6-9ab1-b0fe25db73be.png">

**Comment by ojosdegris** [comment]
Was this right repo to report it ?

**Comment by blackdwarf** [comment]
@ojosdegris the right repo is dotnet/cli. If the issue still persists, can you please file it over there and close this one? Thanks!

**Comment by cunning-pony** [comment]
Hi, actually it goes away with 1.0 release. Closing it.

**Comment by ojosdegris** [comment]
Actually it goes away with 1.0 release. Closing it.
