### ISSUE TITLE
Cannot install .NET Core 2.0 on Amazon Linux AMI

### ISSUE THREAD

**Issue by goforgold** [dotnet/core#930]
I am trying to update from .NET Core 2.0 Preview 2 Final to 2.0 Final Release on the Amazon EC2 instance due to some dependency issue.

When I run install command `sudo yum install dotnet-sdk-2.0.0` it produces following error.

```
Error: Package: dotnet-runtime-2.0.0-2.0.0-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs
```

And, when I try to install `openssl-libs` using package manager with command `yum install openssl-libs`, it says `No package openssl-libs available`.

I've checked [package repository](http://mirror.centos.org/centos/6/os/x86_64/Packages/) and didn't found any package with name `openssl-libs` there. However, `openssl` is installed already in the machine, I confirmed that by running `openssl version` command. The version is `1.0.1k-fips 8 Jan 2015`.

Please suggest how to resolve this dependency.

**Comment by heathhey** [comment]
You might have better luck following the instructions here:

https://github.com/dotnet/core/blob/0b1a1631593d6d379fbdfe2b23597a5c25ea4fc9/Documentation/build-and-install-rhel6-prerequisites.md

Amazon Linux already has a later version of curl, so you might need libcurl-devel installed as well.

**Comment by goforgold** [comment]
I managed to install .NET Core 2.0 using the source code as instructed [here](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md).

I didn't find any complexity in that way. It hardly took 10 minutes to get everything setup.

**Comment by hchungi** [comment]
I was almost desperate.
I tries many ways, none of them can work for me.

Afterwards, I download the .NET Core 2.0 runtime directly with following link:
> https://download.microsoft.com/download/5/F/0/5F0362BD-7D0A-4A9D-9BF9-022C6B15B04D/dotnet-runtime-2.0.0-linux-x64.tar.gz

And, use the old fashion way like installing .net core 1.1 with commands:
```
sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet-runtime-2.0.0-linux-x64.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin
```
It worked. Very simple like you used to do.

**Comment by zl4bv** [comment]
Does not work with Amazon Linux when following [these](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md#rhel-and-fedora-based-systems) instructions.

```
[ec2-user@ip-xx-xx-xx-xx ~]$ sudo yum install dotnet-sdk-2.0.0
Loaded plugins: priorities, update-motd, upgrade-helper
Resolving Dependencies
--> Running transaction check
---> Package dotnet-sdk-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: dotnet-runtime-2.0.0 >= 2.0.0 for package: dotnet-sdk-2.0.0-2.0.0-1.x86_64
--> Processing Dependency: aspnetcore-store-2.0.0 >= 2.0.0 for package: dotnet-sdk-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package aspnetcore-store-2.0.0.x86_64 0:2.0.0-1 will be installed
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: openssl-libs for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Processing Dependency: dotnet-hostfxr-2.0.0 for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package dotnet-hostfxr-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: dotnet-host >= 2.0.0 for package: dotnet-hostfxr-2.0.0-2.0.0-1.x86_64
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: openssl-libs for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package dotnet-host.x86_64 0:2.0.0-1 will be installed
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: openssl-libs for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Finished Dependency Resolution
Error: Package: dotnet-runtime-2.0.0-2.0.0-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by wfurt** [comment]
If you already have openssl you can try to run yum with  --skip-broken (as the message suggests)
All what dotnet needs is to find dynamic libraries from openssl. (and libcurl)

**Comment by wfurt** [comment]
BTW AMI Linux is NOT one of the supported and test platforms. There should be no surprise that there are some bumps. This is one reason for publishing the tar file so you do not need to fight package dependencies.

**Comment by h3smith** [comment]
If you want to use AWS, drop it in Docker and use ECS.

**Comment by Paschoali** [comment]
Like hchungi said, I just did:

Download .NET Core 2.0.0 runtime libraries (always check if URL is right, maybe it can be changed): 
`wget https://download.microsoft.com/download/5/F/0/5F0362BD-7D0A-4A9D-9BF9-022C6B15B04D/dotnet-runtime-2.0.0-linux-x64.tar.gz`

Create folder to .NET Core and extract your tar.gz:

`mkdir -p $HOME/dotnet && tar zxf dotnet-runtime-2.0.0-linux-x64.tar.gz -C $HOME/dotnet`

Finally, export dotnet to globally variable:
`export PATH=$PATH:$HOME/dotnet`

Just it :)

**Comment by goforgold** [comment]
This is exactly how I did this around a month ago.

Thank you very much to confirm the solution.

**Comment by Petermarcu** [comment]
Sounds like people have found a good solution. I'm going to close this out now.

**Comment by goforgold** [comment]
But I wish if I could install this simply using package manager on AWS AMI.

**Comment by omajid** [comment]
Any chance you could try a distribution other than Amazon Linux? The .NET Core project publishes packages for several distributions (such as CentOS, Debian, Ubuntu) and several other distributions are now starting to carry .NET Core too (such as Arch, CentOS, Fedora, RHEL). I dont know if we have a way to contribute packages to Amazon Linux directly.

**Comment by Petermarcu** [comment]
Yes, I've been told the Centos one works: https://www.microsoft.com/net/core#linuxcentos

**Comment by Petermarcu** [comment]
I would assume that someone needs to work with AWS to get .NET Core into their package feed.

**Comment by goforgold** [comment]
Yes, I thought about that and researched on that too.

But, many resources suggests that AWS AMI perofoms best in AWS
infrastructures.

**Comment by cyroby** [comment]
I use the Aliyun ECS,The OS version is Centos 6.8. I also met this problem.The Information like this:
[root@iZwz9bh8rvZ ~]# sudo yum install dotnet-sdk-2.0.0
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package dotnet-sdk-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: dotnet-runtime-2.0.0 >= 2.0.0 for package: dotnet-sdk-2.0.0-2.0.0-1.x86_64
--> Processing Dependency: aspnetcore-store-2.0.0 >= 2.0.0 for package: dotnet-sdk-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package aspnetcore-store-2.0.0.x86_64 0:2.0.0-1 will be installed
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: openssl-libs for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Processing Dependency: dotnet-hostfxr-2.0.0 for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package dotnet-hostfxr-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: dotnet-host >= 2.0.0 for package: dotnet-hostfxr-2.0.0-2.0.0-1.x86_64
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: openssl-libs for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package dotnet-host.x86_64 0:2.0.0-1 will be installed
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: openssl-libs for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Finished Dependency Resolution
Error: Package: dotnet-runtime-2.0.0-2.0.0-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by Paschoali** [comment]
Aliyun ECS? Whatever, did you read the comments? We suggested some solutions. Sure that of them will help you.

**Comment by heathhey** [comment]
Is there a SRPM for the dotnet-runtime package? Or is there a spec file in the repo somewhere? I couldn't find one.

**Comment by omajid** [comment]
> Is there a SRPM for the dotnet-runtime package? Or is there a spec file in the repo somewhere?

We use [`fpm`](https://github.com/jordansissel/fpm) to produce RPMs (and debs) instead of using `rpmbuild`. There are no SPRMs or spec files because of that.

The configuration for `-runtime` and `-host` RPMs is available here: https://github.com/dotnet/core-setup/tree/master/src/pkg/packaging/rpm

Here is the source that reads that config files above to build command line for `fpm`: https://github.com/dotnet/core-setup/blob/master/tools-local/tasks/BuildFPMToolPreReqs.cs

**Comment by AlexLeung** [comment]
The solution no longer works. Please re-open.

**Comment by gtechx** [comment]
I am a client programmer.
I do not like to install any dependency myself on linux.
some problems are too difficulty to solve.
see golang.

**Comment by ddobric** [comment]
Unfortunately I didn't make this working. Using hortonworks sandbox withCentOS.
Error as already mentioned above:

> Error: Package: dotnet-runtime-2.0.6-2.0.6-1.x86_64 (packages-microsoft-com-prod                                                   )
>            Requires: openssl-libs
> Error: Package: dotnet-runtime-deps-2.1.0-rc1-2.1.0_rc1-1.x86_64 (packages-micro                                                   soft-com-prod)

**Comment by jchannon** [comment]
Installing Net Core 2.1 on Amazon Linux still seems to be an issue :(

**Comment by wfurt** [comment]
What base OS do you use and what .Net package? Did you check that everything works using tar distro? I'm trying to figure out if this is pure packaging issue or if there are really missing dependencies.

**Comment by jchannon** [comment]
I did `sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm and yum update and yum install dotnet-sdk-2.1`

Output is below:

```
amazon-linux-ami: Resolving Dependencies
    amazon-linux-ami: --> Running transaction check
    amazon-linux-ami: ---> Package dotnet-sdk-2.1.x86_64 0:2.1.301-1 will be installed
    amazon-linux-ami: --> Processing Dependency: dotnet-runtime-2.1 >= 2.1.1 for package: dotnet-sdk-2.1-2.1.301-1.x86_64
    amazon-linux-ami: --> Processing Dependency: aspnetcore-runtime-2.1 >= 2.1.1 for package: dotnet-sdk-2.1-2.1.301-1.x86_64
    amazon-linux-ami: --> Running transaction check
    amazon-linux-ami: ---> Package aspnetcore-runtime-2.1.x86_64 0:2.1.2-1 will be installed
    amazon-linux-ami: ---> Package dotnet-runtime-2.1.x86_64 0:2.1.2-1 will be installed
    amazon-linux-ami: --> Processing Dependency: dotnet-hostfxr-2.1 >= 2.1.2 for package: dotnet-runtime-2.1-2.1.2-1.x86_64
    amazon-linux-ami: --> Processing Dependency: dotnet-runtime-deps-2.1 >= 2.1.2 for package: dotnet-runtime-2.1-2.1.2-1.x86_64
    amazon-linux-ami: --> Running transaction check
    amazon-linux-ami: ---> Package dotnet-hostfxr-2.1.x86_64 0:2.1.2-1 will be installed
    amazon-linux-ami: --> Processing Dependency: dotnet-host >= 2.1.2 for package: dotnet-hostfxr-2.1-2.1.2-1.x86_64
    amazon-linux-ami: ---> Package dotnet-runtime-2.1.x86_64 0:2.1.2-1 will be installed
    amazon-linux-ami: --> Processing Dependency: dotnet-runtime-deps-2.1 >= 2.1.2 for package: dotnet-runtime-2.1-2.1.2-1.x86_64
    amazon-linux-ami: --> Running transaction check
    amazon-linux-ami: ---> Package dotnet-host.x86_64 0:2.1.2-1 will be installed
    amazon-linux-ami: ---> Package dotnet-runtime-2.1.x86_64 0:2.1.2-1 will be installed
    amazon-linux-ami: --> Processing Dependency: dotnet-runtime-deps-2.1 >= 2.1.2 for package: dotnet-runtime-2.1-2.1.2-1.x86_64
    amazon-linux-ami: --> Finished Dependency Resolution
    amazon-linux-ami:  You could try using --skip-broken to work around the problem
    amazon-linux-ami: Error: Package: dotnet-runtime-2.1-2.1.2-1.x86_64 (packages-microsoft-com-prod)
    amazon-linux-ami:            Requires: dotnet-runtime-deps-2.1 >= 2.1.2
    amazon-linux-ami:            Available: dotnet-runtime-deps-2.1-2.1.0-1.x86_64 (packages-microsoft-com-prod)
    amazon-linux-ami:                dotnet-runtime-deps-2.1 = 2.1.0-1
    amazon-linux-ami:            Available: dotnet-runtime-deps-2.1-2.1.1-1.x86_64 (packages-microsoft-com-prod)
    amazon-linux-ami:                dotnet-runtime-deps-2.1 = 2.1.1-1
    amazon-linux-ami:  You could try running: rpm -Va --nofiles --nodigest

```

**Comment by wfurt** [comment]
cc: @tmds. seems like  it cannot find dotnet-runtime-deps-2.1 -2.1.2

**Comment by tmds** [comment]
@wfurt, @jchannon is installing from Microsoft feed. Are those packages missing?

**Comment by jchannon** [comment]
just followed the instructions here https://www.microsoft.com/net/download/linux-package-manager/centos/sdk-current

**Comment by leecow** [comment]
Looks like the updated runtime-deps and sdk didn't make the upload. Checking into this now.

**Comment by leecow** [comment]
Alrighty, sorry about that. Give it another whirl now.

**Comment by jchannon** [comment]
A bit better but now says runtime needs openssl-libs.

I added yum install openssl-libs but it says "No package openssl-libs
available."

**Comment by wfurt** [comment]
That goes back to original issue. AMI Linux names packages different than RedHat. Now, assuming you have correct openssl 1.0.x installed you can try following trick:

[openssl-libs-ami.spec.txt](https://github.com/dotnet/core/files/2186067/openssl-libs-ami.spec.txt)

Download attached spec file.

`rpmbuild --bb  openssl-libs-ami.spec.txt`
That should produce empty openssl-libs in  /root/rpmbuild/RPMS/ 
(use find if not there as the location may wary) 
`rpm -i openssl-libs-1.0.0-0.x86_64.rpm`

and try the install again. 
Good luck. AMI linux is not tested so .net may or may not work properly. 
The instructions should help you to at least try.

**Comment by sjwoodard** [comment]
The @wfurt solution worked for me, just run `sudo yum install rpm-build` to get started.

**Comment by juancrl** [comment]
Perfect also in my case. The folder was different, as stated :

sudo yum install rpm-build
wget https://github.com/dotnet/core/files/2186067/openssl-libs-ami.spec.txt
rpmbuild --bb openssl-libs-ami.spec.txt
sudo rpm -i /root/rpmbuild/RPMS/x86_64/openssl-libs-1.0.0-0.x86_64.rpm
sudo yum install -y powershell

**Comment by ptdel** [comment]
```Processing files: openssl-libs-1.0.0-0.x86_64
Provides: openssl-libs = 1.0.0-0 openssl-libs(x86-64) = 1.0.0-0
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /usr/src/rpm/BUILDROOT/openssl-libs-1.0.0-0.x86_64
Wrote: /usr/src/rpm/RPMS/x86_64/openssl-libs-1.0.0-0.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.13DnAm
``` for whatever reason this chose today to start hanging forever during deployments.  I don't see an actual %clean step in the rpm spec.

**Comment by darshit95** [comment]
Folks who are trying to install azure powershell and have ended up here can use @juancrl mentioned solution, it surely works !
sudo yum install rpm-build
wget https://github.com/dotnet/core/files/2186067/openssl-libs-ami.spec.txt
rpmbuild --bb openssl-libs-ami.spec.txt
sudo rpm -i /root/rpmbuild/RPMS/x86_64/openssl-libs-1.0.0-0.x86_64.rpm
sudo yum install -y powershell

**Comment by vvaezian** [comment]
For me the path of created openssl-libs was different. So I had to find it first (as suggested by wfurt)
```bash
wget https://github.com/dotnet/core/files/2186067/openssl-libs-ami.spec.txt
rpmbuild --bb openssl-libs-ami.spec.txt
sudo find / -iname RPMS  # output: /usr/src/rpm/RPMS
sudo rpm -i /usr/src/rpm/RPMS/x86_64/openssl-libs-1.0.0-0.x86_64.rpm
sudo yum install -y powershell
```
