### ISSUE TITLE
Can't find symbols for 5 modules when debugging ASP.NET Core 2 web app

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/core#931]
After creating a new .NET Core ASP.NET Core 2 web site in VS 2017 Update 3 and debugging it the symbols for these 5 modules aren't loading. This significantly slows down debugging start time and causes friction. When the VS debugger can't find symbols it goes through a very expensive resolution process every time (many seconds) and it doesn't cache the binding failure, so it repeats that every time.

 * Microsoft.AI.DependencyCollector.dll	C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.applicationinsights.dependencycollector\2.4.1\lib\netstandard1.6\Microsoft.AI.DependencyCollector.dll
 * Microsoft.CodeAnalysis.CSharp.dll	C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.codeanalysis.csharp\2.3.1\lib\netstandard1.3\Microsoft.CodeAnalysis.CSharp.dll
 * Microsoft.CodeAnalysis.dll	C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.codeanalysis.common\2.3.1\lib\netstandard1.3\Microsoft.CodeAnalysis.dll
 * Microsoft.Extensions.DependencyModel.dll	C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.extensions.dependencymodel\2.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll
 * Newtonsoft.Json.dll	C:\Program Files\dotnet\store\x64\netcoreapp2.0\newtonsoft.json\10.0.1\lib\netstandard1.3\Newtonsoft.Json.dll

For these .dlls we need to ensure the symbols are published, both internally on symweb and externally for customers.

Repro: 
 1. Create a new empty ASP.NET Core 2.0 web API app
 2. F5, then watch the symbols loading and the Modules window in VS

**Comment by Petermarcu** [comment]
@jaredpar @Eilon

**Comment by jaredpar** [comment]
CC @tmat for symol publishing

**Comment by Eilon** [comment]
I don't think any of these DLLs are owned by my team. Json.NET is of course 3rd party.

**Comment by Petermarcu** [comment]
@eerhardt for dependency model. @Eilon I believe the others are brought in as dependencies for ASP.NET, can you follow up with those owners to ensure the end to end works?

**Comment by Eilon** [comment]
@livarcocc does your team own `Microsoft.Extensions.DependencyModel.dll`? Do you have a plan for missing public symbols for this DLL?
@jaredpar re: `Microsoft.CodeAnalysis.dll`. Do you have a plan for missing public symbols for these DLLs?

Not sure who owns the AI DLL, I've never seen that one before.

**Comment by livarcocc** [comment]
@eerhardt and @steveharter for the symbols question.

**Comment by eerhardt** [comment]
`Microsoft.Extensions.DependencyModel.dll` is owned by the runtime team and ships out of the `dotnet/core-setup` repo.

@dagood - it looks like no symbols for the `dotnet/core-setup` repo were published for `2.0.0`.  Can we fix that?

**Comment by jaredpar** [comment]
@Eilon these symbol should all be public today. I dont have a good explanation for why they arent showing up. 

CC @jasonmalinowski. @tmat

**Comment by dagood** [comment]
I'm working on getting the Core-Setup 2.0.0 symbols indexed/archived.

**Comment by jasonmalinowski** [comment]
Indeed, those should be archived. We'll figure out what's up but as a warning we're a bit slammed right now so might be a day or two.

**Comment by dagood** [comment]
It seems that the problem for `Microsoft.Extensions.DependencyModel.dll` was that the PDB wasn't converted from Portable PDB to Windows PDB. (This is automated in CoreCLR and CoreFX, but not Core-Setup yet.) I've created a converted copy myself and submitted a new request for archiving. So far, it's available on `symweb`, and we can expect it to be on the public Msft symbol server within a week. Unassigning myself for now because I don't know about the other DLLs.

**Comment by eerhardt** [comment]
@dagood - it wasn't listed here, but PlatformAbstractions has the same problem. It is built from core-setup and its symbols are not on the symbol server. I wasn't aware of the manual nature, I thought the whole repo would be taken care of in one shot.
We also have native assemblies - dotnet host, fxr, policy.

Did you just do this single .dll?  Or did you upload all the symbols for this repo?

**Comment by dagood** [comment]
I ran the conversion tool on all Core-Setup symbol packages, which gave me these to archive: https://gist.github.com/dagood/9237921c06cc37970913bbc89ca99e4d. (`Microsoft.DotNet.PlatformAbstractions`, `Microsoft.Extensions.DependencyModel`, `runtime.linux-arm.Microsoft.NETCore.App`.)

A few packages had portable PDBs in them to try to convert, but hit `The PDB doesn't match debug directory record in the PE file`. Another instance of that is tracked here, for CoreCLR 2.0 branch builds: https://github.com/dotnet/core-eng/issues/1771. The Core-Setup packages with the issue are `runtime.linux-x64.Microsoft.NETCore.App`, `runtime.osx-x64.Microsoft.NETCore.App`.

**Comment by tmat** [comment]
Any chance the DLLs whose PDBs fail to convert are postprocessed by some IL rewriter (like ILLinker)?

**Comment by dagood** [comment]
I'm putting discussion about `runtime.linux-x64.Microsoft.NETCore.App` and `runtime.osx-x64.Microsoft.NETCore.App` to https://github.com/dotnet/core-eng/issues/1771, since those won't help with the problem in the issue description.

**Comment by Petermarcu** [comment]
Sounds like we have this addressed for most of the core pdb's. This isn't a good repo for tracking issues in individual libraries. If there are still outliers, we should open issues for the owners of those binaries.
