### ISSUE TITLE
cannot import X509Certificate from file in .net core 2.0

### ISSUE THREAD

**Issue by xingzhougmu** [dotnet/core#932]
# Issue Title

cannot import X509Certificate from file in .net core 2.0

# General

The following code works perfectly in .net core 1.0, however, does not in .net core 2.0.
`X509Certificate clientCert = new X509Certificate(Directory.GetCurrentDirectory() + "/Certs/Production/CN_Certificate.crt");`

Under .net core 2.0, the exception is as below:

> {Interop+AppleCrypto+AppleCommonCryptoCryptographicException: Unknown format in import.
>    at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
>    at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName)
>    at Test.Program.Main(String[] args) in /Users/xzhou/Projects/Test/Program.cs:line 40}

> For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24484](https://github.com/dotnet/corefx/issues/24484) via [**ZenHub**](https://www.zenhub.com/)
