### ISSUE TITLE
9.0.0-preview.3 and 4 missing for linux

### ISSUE THREAD

**Issue by prabhu** [dotnet/core#9339]
Any ideas if these two versions would become available for Linux?

**Comment by leecow** [comment]
Hey @prabhu - preview releases are not available on packages.microsoft.com but can be installed a few other ways. 

- If you want to use deb/rpm packages, see preview install instructions in [.NET 9 installation instructions for Linux](https://github.com/dotnet/core/blob/main/release-notes/9.0/install-linux.md#install-using-debrpm-packages)
- If you don't need the rpm/deb install method, the [.NET Install Script](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) is a great way to go.

**Comment by prabhu** [comment]
@leecow I think the container images are yet to be updated. I was able to figure out the install script. Thank you.

**Comment by lbussell** [comment]
@pebezo The container images are up to date, but the syndication from the Microsoft Asset Registry to DockerHub is currently not working. See https://github.com/dotnet/dotnet-docker/issues/5327.

You can view the latest tags on MAR: https://mcr.microsoft.com/product/dotnet/runtime/tags

Or on the README files at the root of the dotnet-docker repo (where the container images are built from): https://github.com/dotnet/dotnet-docker/blob/main/README.sdk.md

**Comment by leecow** [comment]
Thanks, Logan. Closing this issue.
