### ISSUE TITLE
.net core 1.1 IFormFileCollection files Performance issue

### ISSUE THREAD

**Issue by chintan3100** [dotnet/core#934]
public async Task<bool> Put(IFormFileCollection files)
        {
            return await UpdateFile(file);
        }

I have hosted application in azure PAAS and analysis log of server. 6 second are taking to get file on server. file size 10 MB.  
Ref Link:http://weblogs.thinktecture.com/pawel/2017/03/aspnet-core-webapi-performance.html

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24495](https://github.com/dotnet/corefx/issues/24495) via [**ZenHub**](https://www.zenhub.com/)
