### ISSUE TITLE
.net core 1.1 Performance issue with Load: Azure PAAS

### ISSUE THREAD

**Issue by chintan3100** [dotnet/core#935]
I have hosted my api on Azure with Web app S1 to S3 plan.

API taking a long time to respond. This issue will get when I have tried to run load test script with multiple users.

Any setting Should we consider for multiple users or when load increase for 1.1
http://weblogs.thinktecture.com/pawel/2017/03/aspnet-core-webapi-performance.html

like
Kestrel ThreadPool 
Or
```xml
  <system.net>
    <connectionManagement>
      <add address="*" maxconnection="1000" />
    </connectionManagement>
  </system.net>
```

**Comment by Petermarcu** [comment]
@Eilon

**Comment by davidfowl** [comment]
@chintan3100 That's hard to know without more data. Are you talking about the time to communicate with an external api via HTTP? Or the time it takes your API itself to respond. Do you have any more specific data (Have you tried using application insights to measure?).

**Comment by chintan3100** [comment]
Thanks @davidfowl 
Yes I am using application insights.  The Same API will take 2-3 second to response and some time it takes 30second - 60 seconds.
Some API communicate with blob storage for upload and download file.
Upload file: we are using IFormFile file to get file.
Download file: we are using FileResult 

Note: All API and DB Operation are async. FIle upload, download Async, We created an index on DB.

**Comment by chintan3100** [comment]
@davidfowl @eilon @Petermarcu
Can you please look for this issue

**Comment by Eilon** [comment]
@chintan3100 can you share more info about the logs and data you've collected? It's nearly impossible to say what's going on without knowing where the time is spent. If you turn on detailed logging and/or Application Insights, hopefully you can at least see what part of the request is taking so long. Once you find that out, we can try to figure out why the slow part of the request is being slow.

**Comment by Petermarcu** [comment]
@chintan3100 since we haven't heard from you in over 30 days, I'm going to close this issue. If you still need help I think the best thing to do would be to open an issue with more of the details @Eilon asked for on the http://github.com/aspnet/home repo.

**Comment by chintan3100** [comment]
Sorry for delay. 
Issue with Azure logging/.net core logging feature.  when we enable logging to blob storage after 20 min we got out of memory error at string builder.
