### ISSUE TITLE
Ontbrekende sterren na klikken op "klaar met lezen"

### ISSUE THREAD

**Issue by SupportTaalinblokjes** [dotnet/core#9359]
### URL(s)

https://www.fenlexpertisecentrum.nl/faq/?fid=1541

### Description

De sterren ontbreken na het lezen van een verhaal in de reader. Zie bijgevoegde afbeeldingen van hoe het zou moeten werken, en hoe het nu werkt. 
Toevoeging ticket: add to migrations.txt mail Vera sterren weer terug

<img width="213" alt="gewenste situatie" src="https://github.com/dotnet/core/assets/161704926/b31a0976-a0fd-4534-b61b-a05ae6a9c510">

<img width="213" alt="Huidige situatie" src="https://github.com/dotnet/core/assets/161704926/3ca4042c-aef9-4656-b1e2-7538fc20b49d">

**Comment by julealgon** [comment]
Aren't issues supposed to be written in English?

**Comment by michaelgsharp** [comment]
@SupportTaalinblokjes Can you please rewrite the issue in English? Thanks!

**Comment by mairaw** [comment]
I used the translate to English function and I don't think this issue is applicable to .NET. So closing the issue.
