### ISSUE TITLE
.NET May 28 2024 Update - .NET 8.0.6, NET 7.0.20, .NET 6.0.31

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9362]
# .NET May 28 2024 Update

.NET has released an update to [.NET 14th 2024 releases](https://github.com/dotnet/core/issues/9309). This update contains following fixes:
### WiX toolset signed with incorrect certificate
The .NET 8.0.5 release on May 14, 2024 included updates to the WiX toolset which were incorrectly signed. This caused failures in scenarios on Windows where Code Integrity checks were enabled.

## Release Notes
* [8.0.6](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.6/8.0.6.md)
* [7.0.20](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.20/7.0.20.md)
* [6.0.31](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.31/6.0.31.md)

## Status

Asset Type | 8.0.6| 7.0.20 | 6.0.31 | Notes
-- | :--:  | :--: | :--: | --
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) |✅ |✅ |✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) |✅ |✅ |✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)  | NA|✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 8](https://learn.microsoft.com/dotnet/core/install/linux-centos) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)|✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian)|✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian)|✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 37](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 38](https://learn.microsoft.com/dotnet/core/install/linux-fedora)|✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 39](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 40](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)  |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp;  [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)|✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) |✅ |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 24.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) |✅ |✅ |✅

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by julealgon** [comment]
Release notes link to 8.0.6 appears to be broken.

**Comment by rbhanda** [comment]
> Release notes link to 8.0.6 appears to be broken.

Thanks for pointing it out. I have corrected the link

**Comment by Falco20019** [comment]
The `Feedback` section of the linked `Release Notes` should link back to this.

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/9390
