### ISSUE TITLE
typeof(System.Threading.Tasks.Task).GetTypeInfo().Assembly.Location returns Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Private.CoreLib.dll'

### ISSUE THREAD

**Issue by vijayshinva** [dotnet/core#937]
# typeof(System.Threading.Tasks.Task).GetTypeInfo().Assembly.Location returns Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Private.CoreLib.dll'

# Description
- .NET Core 2.0.0
- Windows 10 Version 1607

I am trying to use the Emit API from Roslyn from a dotnet core 2.0 console app on Windows 10. For this I have to pass Metadata References to the CSharpCompilation.Create method.

A standard way to pass these references is as follows

```C#
var metaDataReferences = new[]
            {
                MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Linq.Enumerable).GetTypeInfo().Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Threading.Tasks.Task).GetTypeInfo().Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Text.StringBuilder).GetTypeInfo().Assembly.Location),
            };
```

The result of this statement is an array containing the following values

```
Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Private.CoreLib.dll'
Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Linq.dll'
Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Private.CoreLib.dll'
Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Private.CoreLib.dll'

```

The Emit API fails with the following error
```
(5,41): error CS0246: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
```
The reason being 
typeof(System.Threading.Tasks.Task).GetTypeInfo().Assembly.Location is returning Assembly Path='C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Private.CoreLib.dll'

Should it not return C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Threading.Tasks.dll ?

**Comment by daningalla** [comment]
Assembly explorer shows that the Task type is defined in System.Private.CoreLib and not System.Threading.Tasks. Does the code you are trying to compile have the 'using System.Threading.Tasks' directive?

**Comment by vijayshinva** [comment]
Thanks @daningalla it turned out to be an issue with the using directive. One of my base classes was missing the directive and that was causing the compile issue.

**Comment by Petermarcu** [comment]
Sounds like this is resolved. Closing.
