### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [dotnet/core#9373]
Hi team,

 Is there a plan to include the PrivacyInfo.xcprivacy manifest as required by Apple? ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Hao

**Comment by liveans** [comment]
Hello,

Where to include this? I'm not sure I understand the question here. Can you provide more info?

Thanks
