### ISSUE TITLE
The dotnet website is down

### ISSUE THREAD

**Issue by lukshj** [dotnet/core#9376]
### URL(s)

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

### Description

Hi,

I just tried to access the link below, and it is showing an error message.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
My Location: Brazil

![image](https://github.com/dotnet/core/assets/24736536/a6a849cd-8b9e-454f-bff6-306c98db67b6)

**Comment by baronfel** [comment]
Thanks for reporting - we are aware of the issues with the dotnet website and the team is investigating now.

**Comment by pashkovdenis** [comment]
when do we expect a fix ?

**Comment by mairaw** [comment]
The site should be working now. Let us know if you're still seeing issues.
