### ISSUE TITLE
Add support for Azure Linux 3.0

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9377]
This issue is created to track progress for the work to enable Azure Linux 3.0 support for .NET 6.0 and .NET 8.0

### Product and Test updates
- [x] [All teams] Do a compatibility check for the product with the new OS
- [x] [CoreCLR/CoreFX] Runtime / RID Support update 
- [x] #9443
- [x] [Infra] Replace docker tags used in builds across repos and branches
- [x] [CLI team] Update CI legs to latest updated Dockerfile 
- [x] [All teams] Update test infrastructure to support the new version
- [x] [Acquisition] https://github.com/dotnet/dotnet-docker/issues/5331, https://github.com/dotnet/dotnet-docker/issues/5467

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [x] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [x] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by lbussell** [comment]
@rbhanda Azure Linux 3.0 support for .NET has been available for over a week now. We have shipped Azure Linux 3.0 containers and we are running tests against Azure Linux 3.0 in the runtime repo. I don't think the state of this issue reflects that. When will it be updated?

**Comment by rbhanda** [comment]
> @rbhanda Azure Linux 3.0 support for .NET has been available for over a week now. We have shipped Azure Linux 3.0 containers and we are running tests against Azure Linux 3.0 in the runtime repo. I don't think the state of this issue reflects that. When will it be updated?

since everything is complete for this, I will close this issue and mark all items as complete

**Comment by MichaelSimons** [comment]
> since everything is complete for this, I will close this issue and mark all items as complete

@rbhanda - did you intend to close this?
