### ISSUE TITLE
.NET July 2024 Update - .NET 8.0.7, .NET 6.0.32

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9390]
# .NET July 2024 Update

## Release Notes
* [8.0.7](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.7/8.0.7.md)
* [6.0.32](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.32/6.0.32.md)

## Status

Asset Type | 8.0.7| 6.0.32 | Notes
-- | :--:  | :--: | :--
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) |✅ |✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) |✅ |✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)  | NA|✅
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 8](https://learn.microsoft.com/dotnet/core/install/linux-centos)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian) |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 37](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 38](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 39](https://learn.microsoft.com/dotnet/core/install/linux-fedora) |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 40](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp;  [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)   |✅ |✅
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 24.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  |✅ |✅

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by ArturEnache** [comment]
Hi,

dotnet-runtime-deps-8.0 has not been updated to 8.0.7 on the RHEL 9 repository https://packages.microsoft.com/rhel/9/prod:

nothing provides dotnet-runtime-deps-8.0 >= 8.0.7 needed by dotnet-runtime-8.0-8.0.7-1.x86_64 from packages-microsoft-com-prod

It is a dependency for aspnetcore-runtime and dotnet-runtime

**Comment by EliaMaggioniSGS** [comment]
Hello,
The sdk docker images are still on 8.0.303, is there an ETA on those? 
Thanks

**Comment by mairaw** [comment]
The latest SDK is 8.0.303, which contains the 8.0.7 runtime.
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by 105659** [comment]
Currently trying to upgrade from 8.0.1.23580 to 8.0.7.24314 on a Windows Server 2019 standard build 17763.6054 and getting the error below:

![image](https://github.com/user-attachments/assets/38430dd3-266d-4698-a939-d7d64af9b172)

I am using the hosting package (dotnet-hosting-8.0.7-win.exe)

I can uninstall and reinstall version 8.0.1.23580 without any issues. Any ideas what is causing the issue?

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/9447
