### ISSUE TITLE
RC2 causes unicode issue in Chrome

### ISSUE THREAD

**Issue by AustinWinstanley** [dotnet/core#94]
It works fine in Edge and Firefox.

Every page in Chrome is messed up with the unicode character `&#65279;` being inserted at the top causing the `<head>` content to be inserted in the body. It happens on all pages. Tested first on an upgraded site and then on a default web project created through Visual Studio.

![untitled](https://cloud.githubusercontent.com/assets/4576933/15349022/00095a44-1c95-11e6-8b9e-c579bae8604a.png)

**Comment by davidfowl** [comment]
This looks like it might be a kestrel issue. Please file a bug on https://github.com/aspnet/KestrelHttpServer

**Comment by AustinWinstanley** [comment]
Even with the other bug filed, I wanted to update this one just in case.

Running through the command line does not have the problem.

`dotnet restore`
`dotnet run`

![untitled](https://cloud.githubusercontent.com/assets/4576933/15349636/d7ddbf92-1c99-11e6-8702-5d720906ed1f.png)

**Comment by Eilon** [comment]
Closing this issue, as it was moved to the aspnet org.
