### ISSUE TITLE
Where is .NET CORE 1.1 SDK?

### ISSUE THREAD

**Issue by adailsonfilho** [dotnet/core#943]
# Where is .NET CORE 1.1 SDK?

Can't find/install .NET CORE SDK 1.1 again.

# General
In august 22th I've downloaded and installed _.NET CORE 1.1 SDK_ and _2.0_ in my development environment. As can be seen in the following image: https://pasteboard.co/GIXVFkN.png ... 

Now I'm trying to install it into my build environment (TFS agents build machine): I explored all the .NET CORE download pages and previews versions (https://github.com/dotnet/core/tree/master/release-notes/download-archives) and I could just install SDK 1.0.4. (I used the highlighted setup) for .NET CORE 1.1:  https://pasteboard.co/GIY259w.png

# Questions
1) How could i even install 1.1 the first time? Is it some preview? How can I discover it?
2) It's was some naming change?

Thanks in advance,

My best!

**Comment by Petermarcu** [comment]
You can find all the major historical releases here: https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

That said, you should be able to build a .NET Core 1.1 application with the .NET Core 2.0 SDK.

**Comment by leecow** [comment]
The 1.1.0 SDK first shipped with Visual Studio. Today was the first standalone .NET Core release which included the 1.1 SDK and you can see details and download links in the [release notes](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.4.md).
