### ISSUE TITLE
https://github.com/dotnet/core/blob/main/Documentation/core-repos.md does not reference Blazor at all!

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#9433]
### URL(s)

Try searching for Blazor on this page https://github.com/dotnet/core/blob/main/Documentation/core-repos.md

So either Microsoft is abandoning this technology, or it is not getting any attention.

Either case is a problem.

HOW DO WE REPORT BLAZOR WASM ISSUES?

### Description

Need to report an issue on Blazor wasm and not finding any guidance!

**Comment by Jozkee** [comment]
IIUC, you can search blazor wasm issues in https://github.com/dotnet/aspnetcore/issues?q=is%3Aopen+is%3Aissue+blazor+wasm, if your issue is not there, file a new one.

Tagging @danroth27 in case we need to improve guidance to the aspnetcore repo for Blazor users.

**Comment by genifycom** [comment]
Thank you for the reference link.
