### ISSUE TITLE
.NET August 2024 Update - .NET 8.0.8, .NET 6.0.33

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9447]
# .NET August 2024 Update

## Release Notes
* [8.0.8](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.8/8.0.8.md)
* [6.0.33](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.33/6.0.33.md)

## Status

Asset Type | 8.0.8| 6.0.33 | Notes
-- | :--:  | :--: | :--
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet) |✅ |✅
[Snaps](https://learn.microsoft.com/dotnet/core/install/linux-snap) |✅ |✅
**Linux Packages** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 7](https://learn.microsoft.com/dotnet/core/install/linux-centos)  | NA||
&nbsp;&nbsp;&nbsp;&nbsp; [Centos 8](https://learn.microsoft.com/dotnet/core/install/linux-centos)  ||
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 10](https://learn.microsoft.com/dotnet/core/install/linux-debian)   ||
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 11](https://learn.microsoft.com/dotnet/core/install/linux-debian)  ||
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian)   ||
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 37](https://learn.microsoft.com/dotnet/core/install/linux-fedora)   ||
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 38](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  ||
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 39](https://learn.microsoft.com/dotnet/core/install/linux-fedora)  ||
&nbsp;&nbsp;&nbsp;&nbsp; [Fedora 40](https://learn.microsoft.com/dotnet/core/install/linux-fedora)   ||
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse)  ||
&nbsp;&nbsp;&nbsp;&nbsp;  [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)  ||
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)   ||
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 23.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)   ||
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 24.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu)   ||

## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by esanumIT** [comment]
Just as general Feedback... the list of "Changes" for both releases is ... basically non-existant, apart from listing the two CVEs for the 8.0.8 release, the "release-notes" are a list of where/how to obtain the most recent release, rather than actual release notes, telling us what changed compared to the last version!? ... might just be me wondering, tho ...

**Comment by T3rminat0r** [comment]
Just as general Feedback... the list of "Changes" for both releases is ... basically non-existant, apart from listing the two CVEs for the 8.0.8 release, the "release-notes" are a list of where/how to obtain the most recent release, rather than actual release notes, telling us what changed compared to the last version!? ... might just be me wondering, tho ...

**Comment by libreo-abrettschneider** [comment]
And AGAIN our build pipeline breaks cause of analyzer changes similar to https://github.com/dotnet/core/issues/9309#issuecomment-2112177085
"error IDE0073: A source file contains a header that does not match the required text"

Yes it is an error that we need to fix, but a patch release should not break things that worked before.
Is there any way to "fix" the analyzers to a specific version?

Also it breaks docker image builds for us:
https://github.com/dotnet/msbuild/issues/10518

**Comment by lischetzke** [comment]
Question regarding the new versions for Windows. We're running Server 2019 and noticed that the old .NET Hosting Bundles (6.0.32 and 8.0.7) install multiple packages (Windows Server Hosting, .NET Runtime, ASP.NET Core). Typically the installer will remove the old versions and install the new versions.

This time the Hosting Bundle installer installed the new version successfully, but did not remove the old versions. Add/Remove programs and `dotnet --info` are still showing the old versions for `.NET Runtime` and `ASP.NET Core`. `dotnet --info` shows the newly installed versions too. The Add/Remove Programs shows `Windows Server Hosting` in the correct version (6.0.33 and 8.0.8) and only that version, as expected.

A clean install of the Hosting Bundle only shows `Windows Server Hosting` in Add/Remove Programs. Checking the reg keys it seems that the old versions added multiple keys in `HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall` with Bundle* values. The new one only creates this key for `Windows Server Hosting`. `.NET Runtime` and `ASP.NET Core` do not get keys with Bundle* values like the previous versions.

Is it expected, that .NET Runtime and ASP.NET Core are not listed/updated in Add/Remove Programs anymore? Shouldn't the installer update/uninstall older versions like before?

---

Before update:

```txt
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

After update:

```txt
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Rockvolleyball** [comment]
Having the same issues over here as @lischetzke describes. Installation is not going as expected, ending up in mixed versions.

**Comment by SBarkovskiy** [comment]
Hey there @rbhanda 
And expectations when 8.08 will be available via Linux Packages (Microsoft distribution) on Debian, Fedora and so on?
Thank you

**Comment by renevanderheijden** [comment]
I know Debian 9 is not supported anymore, but since version 6.0.33 starting an application results in a segmentation fault.

```bash
Failed to load /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.33/libcoreclr.so, error: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.33/libcoreclr.so)
Segmentation fault
```

I didn't expect breaking changes like these in LTS versions, even if the OS is not supported anymore.

**Comment by nbren007** [comment]
> I know Debian 9 (armhf) is not supported anymore, but since version 6.0.33 starting an application results in a segmentation fault.
> 
> ```shell
> Failed to load /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.33/libcoreclr.so, error: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.33/libcoreclr.so)
> Segmentation fault
> ```
> 
> I didn't expect breaking changes like these in LTS versions, even if the OS is not supported anymore.

I have this issue.  Have you found any resolution?

**Comment by renevanderheijden** [comment]
@nbren007 Unfortunately not... We just keep on using version .31, until we migrate our application to a newer .NET version.

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/9532

**Comment by deepu9890** [comment]
.NET 8.0.8 and .NET SDK 8.0.400 after patch update the application failing with exception could not load file or assembly Microsoft.AspNetCore.SignalR.Client.Core etc.. We load all dlls from installation location and with the new patch update causing issues on client machines.

**Comment by lischetzke** [comment]
> Is it expected, that .NET Runtime and ASP.NET Core are not listed/updated in Add/Remove Programs anymore? Shouldn't the installer update/uninstall older versions like before?

Update on that issue from my side. Updating .NET using WSUS/Windows Update did the trick and ASP.NET as well as .NET Runtime are again showing up in _Add/Remove Programs_ in the correct version. The previous versions were removed cleanly in the programs list and using `dotnet --info`. 

ooking at the update in the Microsoft Update Catalog it seems to me like Windows Update is installing every component separately. This might be something to consider if someone previously installed/updated .NET using the Hosting Bundle and now experiences this issue.
Windows Update will not install the components again, if the latest Hosting Bundle was applied, but ASP.NET or .NET Runtime is not shown in the programs list. Instead it will "correct" the issue when installing an update.

Windows Update will show an available update if older .NET versions were found, i.e. because of this issue, and the update can be reapplied by an update. This could be validated with a system that had this issue where the newest Hosting Bundle was installed but an older version of .NET Runtime was still installed on the system.

This seems to be the case even for the 2024-10 .NET Hosting Bundle which in my opinion is still an issue.

@Rockvolleyball maybe this is useful information or a possible solution for you.

**Comment by Rockvolleyball** [comment]
Thanks for the update @lischetzke 

For me Windows Update is no option. 

Tried to update to the latest 6.0.35 and 8.0.10 in a test environment a minute ago and still have the issue as before. Really crap, does Microsoft even read on this pages what is going on? Still old .Net Runtime not removed and new version not installed correctly.
