### ISSUE TITLE
Docker images should point to mcr.microsoft instead of hub.docker

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/core#9454]
### URL(s)

https://github.com/dotnet/core/blob/7da6443c5099439e85de835c7d7b43bcaae83203/release-notes/9.0/preview/preview7/9.0.0-preview.7.md?plain=1#L61-L67

This also applies to previous .net versions

**Comment by mairaw** [comment]
I was planning to change them to this format instead: https://hub.docker.com/r/microsoft/dotnet-sdk/

@lbussell any comments on this?

**Comment by lbussell** [comment]
@mairaw the content on DockerHub is mostly static at this point. MAR at least has tag listings, e.g. https://mcr.microsoft.com/product/dotnet/sdk/tags. I am in favor of switching links to MAR. The link format would be https://mcr.microsoft.com/product/dotnet/sdk/.

/cc @richlander @MichaelSimons @mthalman

**Comment by MichaelSimons** [comment]
I don't like any of the options currently available.  MAR has had some terrible delays in updating the tags table which provides a bad UX.  The general UX of the tags table is poor.  IMO the best tags browsing experience is the tags table in the GH readmes.  Our GH repos still point to DH as the preferred portal because of the poor MAR UX. We should be consistent IMO.

**Comment by lbussell** [comment]
> IMO the best tags browsing experience is the tags table in the [GitHub] readmes.

Agree

> Our [GitHub] repos still point to DH as the preferred portal because of the poor MAR UX.

This was decided long before the reduced character limit on DockerHub forced us to remove the tags tables there. I think that MAR having any tags listing at all gives it a better user experience than DockerHub today (for .NET repos). Plus we (Microsoft) own MAR. I feel like the decision should be between MAR/GitHub.

**Comment by mthalman** [comment]
I vote for the links to point to the GitHub repo.

**Comment by MichaelSimons** [comment]
I am onboard with GitHub links.  Once the MAR portal is improved, we can switch to it.

**Comment by lbussell** [comment]
Then, for @mairaw's context, the format would be:

- https://github.com/dotnet/dotnet-docker/blob/main/README.runtime-deps.md
- https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md
- https://github.com/dotnet/dotnet-docker/blob/main/README.aspnet.md
- etc.

**Comment by mairaw** [comment]
Ok, thanks all! I can help with the updates.

**Comment by mairaw** [comment]
PR created. I kept the https://hub.docker.com/_/microsoft-dotnet links.

There were also links in the format https://hub.docker.com/_/microsoft-dotnet-core-runtime/ (with core in the url) that I applied the same logic. But did it in a separate commit in case my assumption was wrong.
