### ISSUE TITLE
.NET 9 Preview 7 Release notes docs link is wrong or not available

### ISSUE THREAD

**Issue by nirzaf** [dotnet/core#9459]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview6/9.0.0-preview.7.md

### Description

Given link routing to 404 not found page

**Comment by jamesmontemagno** [comment]
which page is this linked from?

**Comment by mairaw** [comment]
This is the one I reported to @rbhanda internally last night. It was at https://github.com/dotnet/core/releases/tag/v9.0.0-preview.7. It's fixed now.
