### ISSUE TITLE
.NET Core 2.0 SDK Build fail

### ISSUE THREAD

**Issue by wh1sp3r** [dotnet/core#946]
Hello,
I updated my SDK to version 2.0 and I am not able to build my project for Framework 4.6.
I am using Microsoft.AspNetCore libraries in version **1.1.3**.

Output:
```
PM> dotnet build
Microsoft (R) Build Engine verze 15.3.409.57025 pro .NET Core
Copyright (C) Microsoft Corporation. Vçechna pr va vyhrazena.

app.config : error MSB3249: Konfiguraźnˇ soubor aplikace app.config je neplatně. Index and count must refer to a location within the string. [C:\Project\Project.csproj]
app.config : error MSB3249: Parameter name: destinationIndex [C:\Project\Project.csproj]

Build failed.

app.config : error MSB3249: Konfiguraźnˇ soubor aplikace app.config je neplatně. Index and count must refer to a location within the string. [C:\Project\Project.csproj]
app.config : error MSB3249: Parameter name: destinationIndex [C:\Project\Project.csproj]
    0 warningsˇ
    Erorr count: 1
```

Well, my app.config is not used and is almost empty
`<configuration>
   <runtime>
      <gcServer enabled="true"/>
   </runtime>
</configuration>
`

Worked fine before installing 2.0 SDK.

**Comment by Petermarcu** [comment]
Moved here: https://github.com/dotnet/cli/issues/7774

**Comment by MengSung** [comment]
I got the same problem.
Just put your csproj path in ALL English
You can not have any other language than English in you csproj path.

**Comment by svick** [comment]
@MengSung I can reproduce this issue with .Net Core SDK 2.1.104, but not with 2.1.300 Preview 2. Do you want to try installing [the preview SDK](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview2) to see if it fixes the issue for you too?

**Comment by MengSung** [comment]
Thanks svick,
As I described, I solve my problem put the csproj  in all English path then solve my problem.
But I am not sure what will 2.1.300 Preview.

**Comment by hervit0** [comment]
Hi there,

I've encountered the same issue, and indeed, having special characters (`é` in my case) in the path of the `fsproj` is lead to this problem.

I'm running under .NET Core 2.1.4.
