### ISSUE TITLE
No script for Ubuntu install of SDK

### ISSUE THREAD

**Issue by nathanaeljones** [dotnet/core#947]
For 1.0, we were given a scriptable install for Trusty/Xenial, but not for 2.0 (gpg dependency was added).

Moving from 1.0 to 2.0 in the Dockerfiles has proven very difficult. I wasted most of a day on it, and I can't find any other Ubuntu Dockerfiles on github where others have succeeded in moving from 1.0/1.1 to 2.0.

**Comment by Petermarcu** [comment]
@richlander

**Comment by Petermarcu** [comment]
@nathanaeljones are the images on dockerhub for .NET Core 2.0 no help?

**Comment by nathanaeljones** [comment]
They are not for Ubuntu.

**Comment by Petermarcu** [comment]
I'm aiming to have us produce "deps" packages. So there is one thing that aggregates all the various dependencies into one things people can install. I've opened this issue to track it. https://github.com/dotnet/core-setup/issues/3280

I'm also going to try to get the instructions here updated to be the correct and minumal set. https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

**Comment by leecow** [comment]
@johnbeisner to look into updating dotnet-install.sh to account for gpg changes.

**Comment by Petermarcu** [comment]
@johnbeisner @leecow would that be in the CLI repo? If so, we can move the issue there.

**Comment by leecow** [comment]
Issue moved to [dotnet/cli #7808](https://github.com/dotnet/cli/issues/7808) via [**ZenHub**](https://www.zenhub.com/)
