### ISSUE TITLE
[CoreCLR/CoreFX] Runtime / RID Support update

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9471]

**Comment by carlossanlop** [comment]
Is there a reason why this is titled "coreclr/corefx", which are out of support? Or did you mean runtime?

**Comment by carlossanlop** [comment]
> for .NET 8.0 and .NET 9.0

Given that we're excluding 6.0, runtime does not need to make any manual RID additions starting with .NET 8.0.
