### ISSUE TITLE
"Out of support OS versions" table for .NET 6 reports misleading or conflicting information.

### ISSUE THREAD

**Issue by sicil1ano** [dotnet/core#9477]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md

### Description

At this page (https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md), the "Out of support OS versions" table reports some versions of Windows which another documentation page (https://learn.microsoft.com/en-us/dotnet/core/install/windows#supported-versions) shows them as supported instead.

Example about Windows 7:
A generic "Windows 7 SP1" version is considered out of support for .NET 6 here (https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#out-of-support-os-versions) but this page (https://learn.microsoft.com/en-us/dotnet/core/install/windows#supported-versions) says Windows 7 SP1 ESU is actually supported.

Example about Windows 10 21H1:
"Windows 10 21H1" version is considered out of support for .NET 6 here (https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#out-of-support-os-versions) but this page (https://learn.microsoft.com/en-us/dotnet/core/install/windows#supported-versions) says "Windows 10, Version 1607 or later" is supported, including version 21H1.

I don't understand then which page reports the correct information, because 2 pages of documentation for the same product are reporting different data.

**Comment by richlander** [comment]
Great questions ...

- I'll leave the Windows 7 ESU topic to @jamshedd, as to whether it is supported for .NET.
- Windows 7 SP1 is out of support. The learn page makes it clear that it is only addressing the ESU version. We have addressed ESU for Windows Server versions via notes on that same 6.0 release note page. If needed, we could do the same with Windows 7.
- "Windows 10, Version 1607 or later" is intended to mean/imply "1607 and later versions supported by Windows". 21H1 is out of support, per https://learn.microsoft.com/en-us/windows/release-health/release-information. This seems correct to me.

**Comment by jamshedd** [comment]
I think @richlander covered it for the most part. .NET has a "support matrix" - this is the list of operating systems we test on and ensure the product works on. This list is initially populated based on what OS versions are in support at the time of shipping the product. 

Over time new OS versions are introduced, they're generally covered by the forward looking versioning we use like Windows 10, version 1607+ which would imply 1703, 1709, etc. would be in the support matrix for the .NET product. 

If the OS version reaches end of life/goes out of support then it is no longer in our support matrix. In some cases certain Windows versions (usually server operating systems and some popular client operating system versions like Windows 7) have an "ESU" offering which is paid support offered by the Windows team. In those cases .NET will consider that OS version to remain included in our support matrix as long as the ESU update is installed.

**Comment by sicil1ano** [comment]
Thank you both @richlander and @jamshedd!

So, if I understand this correctly (_"Windows 10, Version 1607 or later" is intended to mean/imply "1607 and later versions supported by Windows". 21H1 is out of support,_), if a bug/security vulnerability is discovered in .NET 6 when running an application targeting .NET 6 (e.g. 6.0.100) on Windows 21H1, NO support will be provided. 
Is that correct?

In terms of installation/running applications, how should I interpret the matrix then? If I want to install the latest version of .NET 6 on Windows 21H1, will the installer warn me that is not possible to continue the installation or will I just experience problems when using its runtime? 

I am saying that because we currently have an application targeting .NET 6 (built with 6.0.100) running on Windows 10 21H1 and 1903. So far we haven't been reported problems.

**Comment by richlander** [comment]
We don't have installation blocks in our installers. Doing so would be extra work for us and a pain to manage. We also don't want to be in the business of "enforcing" user behavior this way. If users want to run on out-of-support OSes, that is their choice.

We have one build for Windows x64, for example. The August build, for example, contains one set of functional and security fixes. It is uncommon that fixes are specific to a given Windows version. We don't support the August build, for example, on 21H1 and don't test it. It is unlikely that anything will break on _only_ 21H1 but if that happens, we won't address it, nor will we offer support other than "move to a supported Windows version.

This is all about Windows. Our policies for Linux, macOS, and other OSes are the same.
