### ISSUE TITLE
Broken links on releases 

### ISSUE THREAD

**Issue by mairaw** [dotnet/core#9482]
As I run the thanks data processor, some releases fail to process. Here are some that I could gather from the logs that could potentially be fixed:

| Location | Broken link |
|-----------|--------------|
| https://github.com/dotnet/core/releases/tag/v7.0.17 | https://github.com/dotnet/templating/releases/tag/v7.0.117 |
| https://github.com/dotnet/core/releases/tag/v7.0.16 | https://github.com/dotnet/templating/releases/tag/v7.0.116 |
| https://github.com/dotnet/core/releases/tag/v5.0.4 | https://github.com/dotnet/efcore/releases/tag/v5.0.4 |
| https://github.com/dotnet/core/releases/tag/v3.1.2 | https://github.com/dotnet/ef6/releases/tag/v6.4.2 |
| https://github.com/dotnet/core/releases/tag/v2.2.1 | https://github.com/dotnet/aspnetcore/releases/tag/2.2.1 |
| https://github.com/dotnet/core/releases/tag/v2.1.24 | https://github.com/dotnet/cli/releases/tag/v2.1.617 |
| https://github.com/dotnet/core/releases/tag/v2.1.18 | https://github.com/dotnet/cli/releases/tag/v2.1.514 |
| https://github.com/dotnet/core/releases/tag/v2.1.7 | https://github.com/dotnet/aspnetcore/releases/tag/2.1.7 |
| https://github.com/dotnet/core/releases/tag/v2.1-preview2 | https://github.com/dotnet/coreclr/releases/tag/v2.1.0-preview2-26406-04 |
| https://github.com/dotnet/core/releases/tag/v2.1-preview2 | https://github.com/dotnet/corefx/releases/tag/v2.1.0-preview2-26406-04 |
| https://github.com/dotnet/core/releases/tag/v2.1-preview2 | https://github.com/dotnet/corefx/releases/tag/v2.1.0-preview1-26216-03 |
| https://github.com/dotnet/core/releases/tag/v2.1-preview1 | https://github.com/dotnet/coreclr/releases/tag/v2.1.0-preview1-26216-03 |
| https://github.com/dotnet/core/releases/tag/v2.1-preview1 | https://github.com/dotnet/corefx/releases/tag/v2.1.0-preview1-26216-03 |
| https://github.com/dotnet/core/releases/tag/v2.1-preview1 | https://github.com/dotnet/corefx/releases/tag/v2.1.0-preview1-26216-03 |
| https://github.com/dotnet/core/releases/tag/v1.0.3 | https://github.com/dotnet/coreclr/releases/tag/ |
| https://github.com/dotnet/core/releases/tag/v1.0.3 | https://github.com/dotnet/corefx/releases/tag/ |

**Comment by leecow** [comment]
Links corrected or deleted.
