### ISSUE TITLE
Using a .NET Core library from C++ or Delphi

### ISSUE THREAD

**Issue by ViRb3** [dotnet/core#950]
I have my backend as a .NET Core library and I want to build a cross-platform GUI with either Qt (C++) or Delphi. Is there any way I could build a proper self-contained library and expose certain methods to use from those GUI frontends?

Thanks

**Comment by Petermarcu** [comment]
@russellhadley do you know of any options for in process interop in this direction? I'm not sure I know of any good options...

Genrally what I've seen people do is run a local service as .NET Core and use IPC (over http or whatever other transport you choose) for the client to talk to.

**Comment by Petermarcu** [comment]
I'm going to close this issue now as I think that's the best high level guidance we have at the moment. If you want to have a deeper conversation we can open an issue for discussion on the dotnet/coreclr repo where all of the code and knowledge is for interop.
