### ISSUE TITLE
Core 2.0 CORS api doesn't work in IIS 8.5

### ISSUE THREAD

**Issue by kostyamy** [dotnet/core#951]
# Issue Title

Having some troubles with hosting .NET Core 2.0 MVC bases api (not views but pure api) on Windows 2012 R2: IIS 8.5 -> Kestrel on dynamic port.

Client is Chrome both kinds - "fetch" and "XHR" but i don't think it makes any difference

- "same origin" requests work fine
- locally on my dev machine Surface , Windows 10 same origin and cross-domain (faked via system32\drivers\etc\hosts) work fine even using IIS proxy ->Kestrel chain. Please note not IIS Express but actual IIS 10.
- 2012 box IIS 8.5 no luck :-( looks like IIS not passing through any cross-domain api calls since even IIS log and tracing show NO activities on "<domain>/api/<controller>/<method>" urls.  At the same time STATIC html files are being served just fine but not by Kestrel but pure IIS.

Tried to launch api form CLI: dotnet .\<my-api>.dll and looks like it starts just find and hosts on localhost:<dynamic port>

Here is my web.config (pretty much out of box)
<system.webServer>
    <handlers>
      <add name="aspNetCore" path="api/*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\<my-api>.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

i see no system level error in event log, no IIS logs, nothing.
If AspDotNetModule Core fails somehow while starting under IIS then where besides empty system event log i should be looking at ???

If needed I can provide more information.

Thanks in advance,
-K

**Comment by brockallen** [comment]
My guess is that IIS is eating OPTIONS requests. Do you have anything configured in IIS to process those? 

https://brockallen.com/2012/10/18/cors-iis-and-webdav/

**Comment by kostyamy** [comment]
all clean. no filters of any kind. looks like my original post is missing content of the web.config
but it's actually a default one produced by the dotnet publish -c <config> command
so only AspDotNetModule entry and that's it

**Comment by Petermarcu** [comment]
closing in favor of continuing here: https://github.com/aspnet/Home/issues/2232
