### ISSUE TITLE
Wrong fix mentioned

### ISSUE THREAD

**Issue by pascalberger** [dotnet/core#9519]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.8/8.0.402.md

### Description

> Today, we are releasing an update to .NET 8.0.400 SDK due to an issue with https://github.com/NuGet/Home/issues/13545 fixed by https://github.com/dotnet/razor/pull/10752.

This mentions that an issue in NuGet was fixed by a pull request in Razor, which seems weird to me. Is this really the correct fix for this issue?

**Comment by bryng001** [comment]
I also hope this issue competed asap.

**Comment by wfurt** [comment]
is the linked fix correct @rbhanda?

**Comment by rbhanda** [comment]
@marcpopMSFT what should be the correct links?

**Comment by marcpopMSFT** [comment]
The links are correct but the text around them is confusing. We shipped two separate fixes both included in 8.0.402. One from NuGet and one from Razor. Here's my proposal for cleaning up that text:
https://github.com/dotnet/core/pull/9520

**Comment by bartonjs** [comment]
This appears to have been resolved.
