### ISSUE TITLE
Net Core 2 not install on Raspberry PI 3 with Debian 9 (Stretch)

### ISSUE THREAD

**Issue by pandazzurro** [dotnet/core#953]
# Net Core 2 not install on Raspberry PI 3 with Debian 9 (Stretch)

I have installed last Raspbian on my Raspberry PI 3.
I format my SD card and use instruction at this link: [Install](https://www.microsoft.com/net/core#linuxdebian) 
and [this](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md)

# SSH session 

pi@raspberrypi:~ $ **sudo apt-get update**
Get:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Get:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages [1                                          1.7 MB]
Fetched 11.7 MB in 19s (613 kB/s)
Reading package lists... Done
pi@raspberrypi:~ $ **sudo apt-get install curl libunwind8 gettext apt-transport-ht                                          tps**
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.4.7).
curl is already the newest version (7.52.1-5).
Suggested packages:
  gettext-doc autopoint libasprintf-dev libgettextpo-dev
The following NEW packages will be installed:
  gettext libunwind8
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,478 kB of archives.
After this operation, 7,129 kB of additional disk space will be used.
Do you want to continue? [Y/n] **Y**
Get:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf gettext arm                                          hf 0.19.8.1-2 [1,434 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libunwind8                                           armhf 1.1-4.1 [44.0 kB]
Fetched 1,478 kB in 1s (1,133 kB/s)
Selecting previously unselected package gettext.
(Reading database ... 122683 files and directories currently installed.)
Preparing to unpack .../gettext_0.19.8.1-2_armhf.deb ...
Unpacking gettext (0.19.8.1-2) ...
Selecting previously unselected package libunwind8.
Preparing to unpack .../libunwind8_1.1-4.1_armhf.deb ...
Unpacking libunwind8 (1.1-4.1) ...
Setting up gettext (0.19.8.1-2) ...
Processing triggers for install-info (6.3.0.dfsg.1-1+b1) ...
Setting up libunwind8 (1.1-4.1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
pi@raspberrypi:~ $ **curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   2467      0 --:--:-- --:--:-- --:--:--  2469
pi@raspberrypi:~ $ **sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg**
pi@raspberrypi:~ $ **sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/dotnetdev.list'**
pi@raspberrypi:~ $ **sudo apt-get update**
Hit:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Get:3 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease [2,852 B]
Get:4 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch/main amd64 Packages [2,093 B]
Fetched 4,945 B in 4s (1,143 B/s)
Reading package lists... Done
pi@raspberrypi:~ $ **sudo apt-get install dotnet-sdk-2.0.0**

# SSH Errors:
**Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.0.0
E: Couldn't find any package by glob 'dotnet-sdk-2.0.0'
E: Couldn't find any package by regex 'dotnet-sdk-2.0.0'**

Why can not I install it?
What mistakes did I commit?

Thanks
Andrea

**Comment by pandazzurro** [comment]
Sorry, dotnet-sdk-2.0.0 must not install on Raspberry.
"dotnet publish -r linux-arm" for Linux running on Raspberry Pi

**Comment by TomasHubelbauer** [comment]
@pandazzurro What do you mean there *must not install on Raspberry*? Is .NET Core 2 not supported on the platform? This suggests it should: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md ...but I am getting the same issue.

**Comment by pandazzurro** [comment]
@TomasHubelbauer 
You must deploy only DLL and start program or website.

**Comment by TomasHubelbauer** [comment]
@pandazzurro But why? The guide leads me to believe it should be possible to set up a dev env on a Raspberry Pi. Is it out of date? Raspian should be just like Debian and Raspberry Pi 3 does have armv7 instructions required by the JIT, so what the problem?

**Comment by Petermarcu** [comment]
The sdk has not shipped an arm version and is not a supported developer configuration. That's why the instructions say that. You can publish for arm from another machine and copy the app over.

**Comment by TomasHubelbauer** [comment]
@Petermarcu yeah reading the guide again I seem to have misunderstood it the first few times I skimmed through it. Not the keywords such as *supported developer configuration* make more sense. Shame on me, should have read it twice, thank you and @pandazzurro!

**Comment by Petermarcu** [comment]
Sounds good. We are looking at supporting arm32 for development but right now, the performance on arm would make it mostly unusable even if the binaries were all assembled together.

**Comment by TomasHubelbauer** [comment]
@Petermancu that's exciting, hopefully it will become viable at some point. :-)
