### ISSUE TITLE
# Announcement

### ISSUE THREAD

**Issue by saarwin** [dotnet/core#9530]
# Announcement

We are pleased to announce the release of .NET 9 Release Candidate 1. This release comes with a [go-live license](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#previews), indicating that it is supported in production environments.

This release contains the following improvements:

## **📚Libraries**

* [WebSocket `Keep-Alive` Ping and Timeout APIs](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/libraries.md#websocket-keep-alive-ping-and-timeout)
* [Add ZLib, Brotli compression options](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/libraries.md#add-zlib-and-brotli-compression-options)
* [Add TarEntry.DataOffset](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/libraries.md#add-tarentrydataoffset)
* [`HttpClientFactory` no longer logs header values by default](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/libraries.md#httpclientfactory-no-longer-logs-header-values-by-default)
* [Out-of-proc Meter wildcard listening](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/libraries.md#Out-of-proc-Meter-wildcard-listening)

* Full [release notes](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/libraries.md)

## **🛠️ SDK**

* [Workload History](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/sdk.md#workload-history)

* Full [release notes](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/sdk.md)

## **🌐 ASP.NET Core**

* [Improvements to SignalR distributed tracing](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/aspnetcore.md#improvements-to-signalr-distributed-tracing)
* [Keep-alive timeout for WebSockets](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/aspnetcore.md#keep-alive-timeout-for-websockets)
* [Keyed DI in middleware](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/aspnetcore.md#keyed-di-in-middleware)
* [Override `InputNumber` type attribute](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/aspnetcore.md#override-inputnumber-type-attribute)
* [Trust the ASP.NET Core HTTPS development certificate on Linux](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/aspnetcore.md#trust-the-aspnet-core-https-development-certificate-on-linux)

* Full [release notes](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/aspnetcore.md)

## **📱 .NET MAUI**

* [Added `HorizontalTextAlignment.Justify`](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/dotnetmaui.md#added-horizontaltextalignmentjustify)

* Full [release notes](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/dotnetmaui.md)

## Get started

To get started with .NET 9, [install the .NET 9 SDK](https://dotnet.microsoft.com/download/dotnet/9.0).

If you're on Windows using Visual Studio, we recommend installing the latest [Visual Studio 2022 preview](https://visualstudio.microsoft.com/vs/preview/). .NET 9 is now can be installed directly through the Visual Studio installer starting with Visual Studio 2022 17.12 Preview 2.

You can also use Visual Studio Code and the [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit) extension with .NET 9.

You can find [.NET 9 RC 1 Installer & Binaries](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc1/9.0.0-rc.1.md) on GitHub.

## Team Announcements & Discussions

Discuss this release with the product teams on GitHub through the announcements for this release.

* [.NET MAUI](https://github.com/dotnet/maui/discussions/24698)
* ASP.NET Core(https://github.com/dotnet/aspnetcore/discussions/57787)

## Stay up-to-date with .NET 9

You can stay up-to-date with all the features of .NET 9 with:

* [What's new in .NET 9](https://learn.microsoft.com/dotnet/core/whats-new/dotnet-9/overview)
* [What's new in ASP.NET Core](https://learn.microsoft.com/aspnet/core/release-notes/aspnetcore-9.0)
* [What's new in .NET MAUI](https://learn.microsoft.com/dotnet/maui/whats-new/dotnet-9)
* [What's new in EF Core](https://learn.microsoft.com/ef/core/what-is-new/ef-core-9.0/whatsnew)
* [Breaking Changes in .NET 9](https://learn.microsoft.com/dotnet/core/compatibility/9.0)
* [.NET 9 Releases](https://github.com/dotnet/core/blob/main/release-notes/9.0/README.md)

For .NET 9 previews we are utilizing GitHub Discussions to make announcements. For more information [read our discussion](https://github.com/dotnet/core/discussions/9131).

Stay up to date by subscribing to the [RSS feed](https://github.com/dotnet/core/discussions/categories/news.atom) for all release announcements.

_Originally posted by @jongalloway in https://github.com/dotnet/core/discussions/9496_

**Comment by mairaw** [comment]
Core announcements are made at https://github.com/dotnet/announcements/issues and for discussions in GitHub Discussions News category: https://github.com/dotnet/core/discussions/categories/news. Please do not re-post.
