### ISSUE TITLE
NuGet for System.Collections.Immutable has unresolved dependency towards netstandard

### ISSUE THREAD

**Issue by robert-j-engdahl** [dotnet/core#954]
# Issue Title

Installing the NuGet package System.Collections.Immutable v1.4.0 targeting .Net 4.6.1 does not include its dependency towards netstandard.

# General
After

    install-package System.Collections.Immutable -ProjectName SomeProject

And using ImmutableHashSet<long> in some class, Visual Studio is fine, but my TeamCity build fails with the following errors:

    Analysis\Recalculation\Recursive\RecursiveAnalysisRecalculatorTest.cs(89, 104): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

This goes for other types I've been using for ages such as IEnumerable<> and ValueType. 

(And if this is not the right place to file such an issue, you might fix the link for the project site given here https://www.nuget.org/packages/System.Collections.Immutable/)

**Comment by robert-j-engdahl** [comment]
This could be caused by my test projects being 4.6.1 and my production being 4.6.  

It did, however, not help to

    Install-Package NETStandard.Library -Version 2.0.0

There might be issues that concern the backwards compatibility of 4.6.1 that I am not aware of.

**Comment by wijays** [comment]
Running into the same issue on 4.6.2.

**Comment by robertbaker** [comment]
You will need to install the VS 2017 (MSBuild 2017) on your team city server. Additionally 4.6.0 won't work, you need at least 4.6.2.

https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15

Additionally, I would recommend changing your nuget's to package reference if you haven't already. Look for packages that were installed using an older .net framework version, you will need to reinstall those to ensure you get the correct versions.

Please close this issue as it's not related to .net/standard/core

**Comment by Petermarcu** [comment]
There are some issues with 4.6.1's support of .NET Standard 2.0. For example netstandard.dll version 2.0.0 isn't there and needs to be present with the application (or test in this case). I'm going to move this issue to dotnet/standard because I do think there could be a problem here that we need to look into.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/standard #534](https://github.com/dotnet/standard/issues/534) via [**ZenHub**](https://www.zenhub.com/)
