### ISSUE TITLE
Winget 9.0.100-rc.2

### ISSUE THREAD

**Issue by MikeBairdRocks** [dotnet/core#9540]
### URL(s)

https://github.com/dotnet/core/releases/tag/v9.0.0-rc.2

### Description

9.0.100-rc.2 is missing from winget.

![Image](https://github.com/user-attachments/assets/0f78fdc4-875a-4341-ba0a-34eca1c9a7fc)

**Comment by xtqqczze** [comment]
The WinGet publish pipeline is currently failing, tracked by: https://github.com/microsoft/winget-pkgs/issues/180404.

**Comment by xtqqczze** [comment]
> The WinGet publish pipeline is currently failing, tracked by: [microsoft/winget-pkgs#180404](https://github.com/microsoft/winget-pkgs/issues/180404).

@MikeBairdRocks This should now be resolved.

**Comment by mairaw** [comment]
I can see rc2 now as well

![Image](https://github.com/user-attachments/assets/d3e99190-ed3a-4024-ab1e-b4395544748d)
