### ISSUE TITLE
.Close() on TcpClient & Socket missing for some platforms

### ISSUE THREAD

**Issue by danielgerlag** [dotnet/core#956]
# .Close() on TcpClient & Socket missing for some platforms

.Close() on TcpClient & Socket (System.Net.Sockets) is available in .net standard 2.0, only if compiling on a Windows machine... if I try compile on a Mac, these methods are missing.
Also, have to explicitly reference `System.Net.Sockets` when building from the Mac.

# General

.NET Standard 2.0
Windows 10 vs. MacOS

**Comment by Petermarcu** [comment]
@weshaggard, we use the same ref's in both cases don't we? Any idea what may be going on?

**Comment by weshaggard** [comment]
Yes we use the same ref everywhere when targeting netstandard20. @danielgerlag can you share more of how you are building? 

Close should be available on both of those types when targeting netstandard20

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/standard #528](https://github.com/dotnet/standard/issues/528) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Petermarcu** [comment]
Lets get further details and track this in the dotnet/standard repo https://github.com/dotnet/core/issues/956
