### ISSUE TITLE
[Fedora 39] Stop publishing container images

### ISSUE THREAD

**Issue by ashnaga** [dotnet/core#9566]
- [x] Stop publishing images from nightly repos immediately 
- [x] Stop publishing images from main repos with next .NET servicing release 
- [ ] dotnet/dotnet-buildtools-prereqs-docker#1218

**Comment by mthalman** [comment]
No official .NET images for Fedora so nothing to do there. But I have created an issue for buildtools-prereqs: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1218.

**Comment by lbussell** [comment]
[Triage] This was mistakenly closed - need to wait on https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1218 before closing this issue.

**Comment by ashnaga** [comment]
[like]  Ashita Nagar reacted to your message:
________________________________
