### ISSUE TITLE
[Alpine 3.21] Add infrastructure support for new OS version

### ISSUE THREAD

**Issue by ashnaga** [dotnet/core#9578]
- [x] Helix image support: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1282
- [x] [For non-Docker] Make the new OS Version available in the Helix pools  
- Check for any hardware updates 
- Check if new hardware needs to be added to the infra pool for support

**Comment by ilyas1974** [comment]
Created https://github.com/dotnet/dnceng/issues/4348 to track this work
