### ISSUE TITLE
[Ubuntu 24.10] Create new container images

### ISSUE THREAD

**Issue by ashnaga** [dotnet/core#9585]
- [ ] Add support within nightly repos. Detailed tasks in [here](https://github.com/dotnet/dotnet-docker/blob/main/.github/ISSUE_TEMPLATE/releases/new-distro-release.md#determining-when-to-move-a-new-distro-to-the-main-branch) 
- [ ] Deploy to main (GA) during next patch release cycle 
- [ ] [Windows only] Add new images to dotnet-framework-docker repo. Detailed tasks in [here](https://github.com/microsoft/dotnet-framework-docker/blob/main/.github/ISSUE_TEMPLATE/new-windows-release.md).

**Comment by lbussell** [comment]
Closing as not planned since Ubuntu 24.10 is not LTS, per [dotnet-docker Supported platforms documentation](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md#linux).
