### ISSUE TITLE
 release of .NET 9

### ISSUE THREAD

**Issue by Natthachai0434** [dotnet/core#9589]
We are pleased to announce the release of .NET 9 Release Candidate 2. As we prepare the general availability (GA) release of .NET 9 in November we are adding our final touches around performance, stability, and any additional optimizations to make it the best release of .NET 9.  This release comes with a [go-live license](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#previews), indicating that it is supported in production environments. We encourage developers today to try out this latest release and give the teams feedback on anything that you find in your development so we can incorporate any additional enhancements into the final release.

You can find release notes for enhancements in this release for the following:

* [📚Libraries](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/libraries.md)
* [⏱️Runtime](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/runtime.md)
* [🛠️ SDK](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/sdk.md)
* [🌐 ASP.NET Core](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/aspnetcore.md) with an [update to latest Bootstrap, jQuery, and jQuery Validation versions](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/aspnetcore.md#updated-to-latest-bootstrap-jquery-and-jquery-validation-versions)
* [📱 .NET MAUI](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/dotnetmaui.md) including [Xcode 16 and latest platform SDK versions](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/dotnetmaui.md#xcode-16-and-latest-platform-sdk-versions)

## Get started

To get started with .NET 9, [install the .NET 9 SDK](https://dotnet.microsoft.com/download/dotnet/9.0).

If you're on Windows using Visual Studio, we recommend installing the latest [Visual Studio 2022 preview](https://visualstudio.microsoft.com/vs/preview/). .NET 9 is now can be installed directly through the Visual Studio installer starting with Visual Studio 2022 17.12 Preview 3 (Available Oct. 15th).

You can also use Visual Studio Code and the [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit) extension with .NET 9.

You can find [.NET 9 RC 2 Installer & Binaries](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/rc2/9.0.0-rc.2.md) on GitHub.

## Stay up-to-date with .NET 9

You can stay up-to-date with all the features of .NET 9 with:

* [What's new in .NET 9](https://learn.microsoft.com/dotnet/core/whats-new/dotnet-9/overview)
* [What's new in ASP.NET Core](https://learn.microsoft.com/aspnet/core/release-notes/aspnetcore-9.0)
* [What's new in .NET MAUI](https://learn.microsoft.com/dotnet/maui/whats-new/dotnet-9)
* [What's new in EF Core](https://learn.microsoft.com/ef/core/what-is-new/ef-core-9.0/whatsnew)
* [Breaking Changes in .NET 9](https://learn.microsoft.com/dotnet/core/compatibility/9.0)
* [.NET 9 Releases](https://github.com/dotnet/core/blob/main/release-notes/9.0/README.md)

Be sure to subscribe to the GitHub Discussions [news feed](https://github.com/dotnet/core/discussions/categories/news.atom) for all release announcements.

_Originally posted by @jamesmontemagno in https://github.com/dotnet/core/discussions/9534_

**Comment by mairaw** [comment]
Core announcements are made at https://github.com/dotnet/announcements/issues and for discussions in GitHub Discussions News category: https://github.com/dotnet/core/discussions/categories/news. Please do not re-post.
