### ISSUE TITLE
.NetCore RC2 can not run with portable class library

### ISSUE THREAD

**Issue by peixushang** [dotnet/core#96]
I create a portable class library with targeting to .NetStandrad 1.5 profie, then I have a .net core rc2 console application which reference the portable class library, when I run the .net core console application, it throws a FileNotFoundException which saids can not load the portable library. You can reproduce this issue with the attached project. I wonder if it is a bug of .net core rc2? because I can use this like this way in core rc1.
[TestCoreApp.zip](https://github.com/dotnet/core/files/271768/TestCoreApp.zip)

**Comment by blackdwarf** [comment]
@peixushang I cannot repro this with `1.0.0-preview2-003121` version of the CLI tooling. Both projects restore and build and run properly. 

Will close this issue with the above. If the issue still repros for you, please open up a new issue on dotnet/cli repo. Thanks!
