### ISSUE TITLE
Terminal (Hot Reload) and build (Loading)

### ISSUE THREAD

**Issue by afallingstone** [dotnet/core#9609]
**Hot Reload**

In this image, you can see the first 2 Hot Reloads worked. Then my file saved in the middle of typing which caused an error but recovered after the red X. After recovery the terminal will not show "Hot Reload Succeeded" unless I restart the build. But, most of the time, Hot Reload will work for a bit.

![Image](https://github.com/user-attachments/assets/cb221f8d-f991-4acb-b8d3-21380214fa7a)

The real problem is Hot Reload will randomly stop working, and since the terminal is not updating It makes it difficult to understand why things are not updating. 

**Loading**
Requesting a restart or running "dotnet watch run"

![Image](https://github.com/user-attachments/assets/963c4a34-8638-4bf5-ab03-a1e163bda375)

It says "Using launch settings from LaunchSettings.json". But if I open the browser it is still loading / building in the background, so I am not sure when it is ready.

Before .net 9 it was showing all the processes such as and restoring and building. But now it shows nothing and worse it doesn't show it is ready.

**Comment by MelvinSnijders** [comment]
Did you fix the issue? If yes, what did you do to fix it?

**Comment by afallingstone** [comment]
> Did you fix the issue? If yes, what did you do to fix it?

I am on another issue in the asp.net core community. They’re having issues with the hot reload. 

The not showing loading / building in terminal issue, I am still having and haven’t created an issue for that. 

It’s been a frustrating few days say the least. I am considering writing a blog / issue post on how .net 10 shouldn’t have any new features and just focus on tooling issues. They’re having last year has been filled with frustrating up and downs.

**Comment by MelvinSnijders** [comment]
I agree, I just migrated a big project to .NET 9 because of some features we wanted to use. 

I'm thinking of completely rolling back to .NET 8, only because the developer experience is absolutely terrible...

Hope this is fixed ASAP!
