### ISSUE TITLE
Is there a difference between win-gs-x64 and win-x64 ?

### ISSUE THREAD

**Issue by ststeiger** [dotnet/core#961]
# Confusing download file names

I have a question regarding the download of .NET Core:
If I want to download .NET Core 2.0 SDK, I can do it either 
here: https://www.microsoft.com/net/download/core
or here: https://www.microsoft.com/net/core#windowscmd

Now, one link downloads dotnet-sdk-2.0.0-win-gs-x64.exe, the other downloads dotnet-sdk-2.0.0-win-x64.exe. 
Is there any difference between win-gs-x64 and win-x64 ?
If yes, what is the difference ?  Which is the newer one ? 
If no, why do they have 2 different names ?

**Comment by ststeiger** [comment]
Strange. 
Installed win-gs-x64, and it didn't show in visual studio. 
installed win-x64, and it showed in visual studio.
Maybe it was the restart.

**Comment by leecow** [comment]
They're the same. We needed an easy way to track downloads from either the 'getting started' pages versus downloads that came from other places. Copy and rename to the rescue :-)

**Comment by ststeiger** [comment]
OK, I see the why - thanks for the response. 
I think it's superfluous to say this, but it would be more professional to use the refer(r)er for that purpose.
