### ISSUE TITLE
Repository Doesn´t Works

### ISSUE THREAD

**Issue by warriorfenix26** [dotnet/core#962]
I try download .net sdk 2.0 follow the instructions in Raspberry and i can't it. The terminal show me: impossible found the package. I try in ubuntu and its the same.

**Comment by omajid** [comment]
There is no SDK for arm platforms (including raspberry pi). Please see https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md#net-core-on-raspberry-pi which says:

> . There is no SDK that runs on ARM32 but you can publish an application that will run on a Raspberry Pi.

If you want to use .NET Core on Raspberry Pi, you should use the SDK on a x64 (or `x86_64`/`amd64` as it called by most linux distros) machine and publish for `arm` and run it on the Raspberry Pi. Please see the doc I liked for more information.
