### ISSUE TITLE
Documentation/prereqs.md is obsolete

### ISSUE THREAD

**Issue by omajid** [dotnet/core#964]
core/Documentation/prereqs.md is incomplete and old:

- Doesnt point to any Linux distro-specific packages.
- Only mentions dependencies for .NET Core 1.x on Ubunut and CentOS.
- Refers to mostly 1.0 stuff
- Suggests using openssl on mac

 The docs site has better docs:

- https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x
- https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites
- https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

We should update our prereqs file to point to the better docs. Or we could update our prereqs file and sync it with those docs.

**Comment by leecow** [comment]
Thanks @omajid. Quick and dirty fix for now ... I've added a note to the existing document redirecting to the docs site.

**Comment by Petermarcu** [comment]
Should we just delete the rest of the page and just leave the pointers to the docs site? I'll make that PR now.

**Comment by Petermarcu** [comment]
https://github.com/dotnet/core/pull/1014

**Comment by leecow** [comment]
Updates merged.
