### ISSUE TITLE
 System.Data.SqlClient throwing System.PlatformNotSupportedException when loaded via reflection

### ISSUE THREAD

**Issue by softeering** [dotnet/core#966]
#  System.Data.SqlClient throwing System.PlatformNotSupportedException when loaded via reflection

System.Data.SqlClient does not work when loading the external library (.NET Standard DLL) at runtime through reflection except if the library has been published for a specific platform (rid).
Trying to execute a SQL query against a SQL Server instance throws "System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform" exception.

Repro steps and Visual studio solution can be found here:
https://github.com/softeering/NETStandardSQLClientRepro

I'm pretty sure this can be explained but I don't get why it doesn't work

**Comment by leedavi** [comment]
I have the same problem with different code base.

**Comment by softeering** [comment]
FYI, I opened the same issue in dotnet/corefx repository:
https://github.com/dotnet/corefx/issues/24229

**Comment by Petermarcu** [comment]
Closing because the issue in corefx is where this should be tracked.
