### ISSUE TITLE
Cannot start .sln file in visual studio

### ISSUE THREAD

**Issue by janne481** [dotnet/core#9660]
I get the message:
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

**Comment by mairaw** [comment]
Can you share a screenshot of the error you're getting? If this is happening on Visual Studio, you should use the Report a problem menu.
![Image](https://github.com/user-attachments/assets/01d40806-3331-4407-901d-31d05113e813)

But from your description, it seems you're trying to run CLI commands?
