### ISSUE TITLE
LDAP/AD Group +JWT Authentication

### ISSUE THREAD

**Issue by joehoeller** [dotnet/core#967]
# LDAP/AD Group +JWT Authentication

I feel an integral piece of the roadmap should incorporate a way to access LDAP and Windows AD groups, and issue a JWT, as well as place restrictions or filters on what data gets sent to the UI based on a group.

**Comment by joehoeller** [comment]
One suggestion is to ditch the immature Kestrel server completely and have .NET Core run on NGINX, and use NGINX's JWT modules and LDAP features for authentication via RESTful services.

**Comment by Petermarcu** [comment]
@danroth27 should this get tracked somewhere?

**Comment by danroth27** [comment]
I believe https://github.com/dotnet/corefx/issues/2089 tracks adding support for LDAP to .NET Core.

ASP.NET Core already provides support for validating [JWT tokens](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.jwtbearerextensions?view=aspnetcore-2.0) sent as bearer tokens. We support acquiring JWT tokens via [OIDC](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.openidconnectextensions?view=aspnetcore-2.0). We also plan to provide an OIDC provider component in an upcoming release.

There are no plans to ditch Kestrel - we need Kestrel as a high performance cross-platform web server that is independent of any one particular host. But you can still [use ASP.NET Core with Nginx](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x)

Does that cover all of the scenarios you are interested in?

**Comment by Petermarcu** [comment]
I'm going to close this now. Let us know if there are still more questions.
