### ISSUE TITLE
Cannot target portable or sl5

### ISSUE THREAD

**Issue by tpluscode** [dotnet/core#968]
# Issue Title

It's impossible to target some framework version (in my case portable or sl5) without adding a full framework too.

# General

In one project I multi-target for a wide variety of frameworks including Silverlight 5, .NET 3.5 and portable. It worked fine in .NET 1.1 SDK. Here's an example project file.

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Test</RootNamespace>
    <AssemblyName>Test</AssemblyName>
    <TargetFrameworks>sl5;netcoreapp1.1;net462;portable-net40+sl50+win8+wpa81+wp8</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'sl5'">
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'portable-net40+sl50+win8+wpa81+wp8'">
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
  </PropertyGroup>

</Project>
```

Not sure why I need the PropertyGroups with conditions but it worked.

After updating to .NET Core 2.0 I'm seeing these errors:

```
Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.5'. Ensure that restore has run and that you have included 'net45' in the TargetFrameworks for your project. [Test.csproj]
Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.0'. Ensure that restore has run and that you have included 'net40' in the TargetFrameworks for your project. [Test.csproj]
```

The error isn't incorrect, adding `net40;net45` to `TargetFrameworks` does help. But it shouldn't be necessary and I don't really want to target them explicitly. Especially the .NET 4.0 seems redundant given that the portable profile I use does include that.

**Comment by Petermarcu** [comment]
@livarcocc @dsplaisted should this go to the cli or sdk repo for traction?

**Comment by livarcocc** [comment]
Move it to the CLI please. The SDK repo will go away at some point and this is one less bug that we will have to move.

**Comment by Petermarcu** [comment]
copied here: https://github.com/dotnet/cli/issues/7770

Closing this one now.
