### ISSUE TITLE
System.IO.FileNotFoundException System.DirectoryServices.AccountManagement

### ISSUE THREAD

**Issue by CarlosOnline** [dotnet/core#970]
# System.DirectoryServices.AccountManagement won't load from asp.net Core 2.0 (netcoreapp2.0) website
Referencing .net 4.5.1 framework class library from asp.net Core 2.0 (netcoreapp2.0), where class library references System.DirectoryServices.AccountManagement leads to receives FileNotFound exception.  

**System.IO.FileNotFoundException** occurred
  HResult=0x80070002
  Message=Could not load file or assembly '**System.DirectoryServices.AccountManagement**, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at SUR.Util1.ActiveDirectory.GetGroupNames(String userName) in combined\Util1\ActiveDirectory.cs:line 33
   at spa.Controllers.HomeController.Index() in combined\spa\Controllers\HomeController.cs:line 15
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

# Repro
Problem solution uploaded to [DotNetCore2DirectoryServicesBug](https://github.com/CarlosOnline/DotNetCore2DirectoryServicesBug)

# Manual Repro
dotnet new aurelia
npm install
add new **Utils** .Net Framework 4.51 project _(version doesn't matter)_
add class below to Utils .Net Framework 4.51

```
    public class ActiveDirectory
    {
        public static List<string> GetGroupNames(string userName)
        {
            var result = new List<string>();

            if (string.IsNullOrEmpty(userName))
                return result;

            var domain = userName.Split('\\').FirstOrDefault();

            var pc = new PrincipalContext(ContextType.Domain, domain);
            var identity = UserPrincipal.FindByIdentity(pc, userName);
            if (identity != null)
            {
                var src = identity.GetGroups(pc);
                src.ToList().ForEach(sr => result.Add(sr.SamAccountName));
            }
            return result;
        }

    }
```
add **Utils** project reference to asp.net core app project
update HomeController.cs
```
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var groups = ActiveDirectory.GetGroupNames(User.Identity.Name);

            return View();
        }
    }
```
start debugging

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24488](https://github.com/dotnet/corefx/issues/24488) via [**ZenHub**](https://www.zenhub.com/)
