### ISSUE TITLE
Debugging dotnet core app on Raspberry Pi & Linux?

### ISSUE THREAD

**Issue by BrendanGrant** [dotnet/core#971]
Nope.

*grumble* I see the problem, there does not look to be a linux-arm debug package at present (at least where I would expect it).

Over SSH the remote device accesses https://aka.ms/getvsdbgsh and runs the script, on the Ubuntu machine, it looks something like:

GetVsDbg.sh -r linux-x64 -v vs2017u1

which results in a download of https://vsdebugger.azureedge.net/vsdbg-15-1-10630-1/vsdbg-linux-x64.zip

when run on the pi, the RID is different:

GetVsDbg.sh -r linux-arm -v vs2017u1

And then an HTTP request to https://vsdebugger.azureedge.net/vsdbg-15-1-10630-1/vsdbg-linux-arm.zip fails as there is nothing there.

Aside from the rather poor experience of having this silently fail without any information available in VS, it is a shame that there is not a debug package for linux-arm.

Looking at the x64 package, I'm not quite sure where those binaries are coming from (source/repo wise), but I guess some more hunting is required.

______________
Original issue:

I've got a .NET core (2.0) app which works perfectly on Windows and on a Raspberry Pi 2 (and 3) running Rasbian Jessie when run interactively. Wanting it to run headless and full time, so set it up as a systemd service and found it to be crashing ~30 seconds after startup, then leading to another instance being run. This of course is bad.

This made me look into the remote debugging abilities for .net core apps in VS2017 (15.3.4), which seems to be supported over SSH. I even validated this by deploying my app to an x64 Ubuntu 16.04 LTS VM. I could not only run the app, but remote debug via VS2017 over SSH.

For some reason, I cannot do the same on either a Pi 2 or Pi 3 with which I've tried on this app.

Visual Studio can connect and list processes, selecting the process I see and opting to debug with the 'Managed (.NET Core for Unix)' debugger, will initially see a modal dialog saying "Loading debug adapter..." for a period of time, then will be dropped back to VS with no further information. Further attempts to attach fail more quickly.

I can attach with "Native (GDB) code", however that doesn't give me the info I am looking for.

The .net core sdk does not today work on Raspberry Pi, but AFAIK that shouldn't matter here when it wasn't installed to the Ubuntu machine either. In all cases I am simply running the self-contained executable, so am not sure what else might need to be on the system

App is being built & published with:

dotnet publish -c debug -r linux-arm
or 
dotnet publish -c debug -r ubuntu.16.04-x64 

Are there any logs on the Linux or VS Windows side which I should be looking at to understand what might be failing?

**Comment by lt72** [comment]
@sywhang @gregg-miskelly for investigation.

**Comment by gregg-miskelly** [comment]
This issue tracks supporting ARM debugging for the vsdbg side: https://github.com/OmniSharp/omnisharp-vscode/issues/1562

The .NET Runtime likely also has work, but I don't know if they have an issue tracking it.

**Comment by BrendanGrant** [comment]
After my second post I did eventually find that OmniSharp ticket.

At the very least, the owners of GetVsDbg.sh & Visual Studio need to have a little chat and allow one to tell the other "No compatible debugger packages could be located." Better yet, also adding "In the mean time, please try debugging against a supported platform, here is a list..."

In the end, I deployed my app to the Ubuntu VM and was able to debug it and solve my issues there, which then unblocked my initial problem on the Pi... however there must be a better experience in this, as clearly I am not the only person to spend quite a bit of time trying to figure out why something (which currently isn't supported (which is ok)) doesn't work.

**Comment by Petermarcu** [comment]
@gregg-miskelly is there a place to file an issue for this comment?

>> At the very least, the owners of GetVsDbg.sh & Visual Studio need to have a little chat and allow one to tell the other "No compatible debugger packages could be located." Better yet, also adding "In the mean time, please try debugging against a supported platform, here is a list..."

For now I'm going to close this issue because it's tracked in a larger theme of enabling first class arm32 support.

**Comment by Petermarcu** [comment]
You can try this now: https://github.com/OmniSharp/omnisharp-vscode/issues/1562#issuecomment-348349242

**Comment by IvanFarkas** [comment]
How about `./getvsdbgshbeta -v latest -r linux-arm -l ~/vsdbg`?
It's from https://vsdebugger.azureedge.net/vsdbg-15-1-11120-1/vsdbg-linux-arm.zip.
I could not get it going on arm64 with .NET Core 2.0.

**Comment by gregg-miskelly** [comment]
@IvanFarkas arm is now supported, but NOT arm64. I opened https://github.com/OmniSharp/omnisharp-vscode/issues/2105 to track arm64 support.

**Comment by IvanFarkas** [comment]
I need to be able to **run and debug .NET Core 2.1 C# console app on arm64v8**.
DragonBoard 820c is a powerful single board computer to be used as an **Azure IoT Edge** hub.
We need to be able to run and debug .NET Core 2.1 C# console app on arm64v8 running in a Docker container.
**Let's hope that this will be achieved by .NET Core 2.1 RTM!**

**Comment by IvanFarkas** [comment]
I opened [ticket #1337](https://github.com/dotnet/core/issues/1337)

**Comment by IvanFarkas** [comment]
How Microsoft expect **.NET Core 2.1** to be popular for any **IoT** app if it does not run on **arm64v8** architecture?

**The success of Azure IoT Edge depends on this!**
We **MUST** be able to **Run** and **Remote Debug** an **Azure IoT Edge module** that is a **.NET Core 2.1 C# Docker** app on an **arm64v8** architecture like the **DragonBoard 410c** or **DragonBoard 820c**.

Is this the next **[Microsoft Bob](https://en.wikipedia.org/wiki/Microsoft_Bob)**?
