### ISSUE TITLE
about dotnet core 2.0 OS support

### ISSUE THREAD

**Issue by xLabel** [dotnet/core#975]
according this : https://github.com/dotnet/core/blob/master/roadmap.md 
dotnet core 2.0  support CentOS7.3+ ,

but our product environment is CentOS7.2 , can it run on CentOS7.2 without any linux kernel update ?

**Comment by Petermarcu** [comment]
It should run fine. I don't know of any technical blocker. 7.2 is definitely a min.

**Comment by xLabel** [comment]
@Petermarcu 
Thank you for your reply .  
: )

what is mean "technical blocker" ?  for example .

**Comment by leecow** [comment]
@xLabel - a technical blocker would be an issue which prevented .NET Core functioning correctly.

**Comment by huting0211** [comment]
What's the difference between bug and technical blocker?

**Comment by Petermarcu** [comment]
If you hit bugs, let us know what you hit. We expect it to work but we aren't covering it with a lot of our testing. I'm going to close this issue now.
