### ISSUE TITLE
NetCore 2.0 - Ubuntu 16.04.3 System.IO.FileLoadException System.Threading Version=4.1.0.0

### ISSUE THREAD

**Issue by brooksyott** [dotnet/core#977]
# Issue Title

I'm looking to heavily use dotnet/core, 
When doing a simple HelloWorld_NetCore tutorial, I've tried to deploy it to an Ubuntu server.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out
   at System.Console.WriteLine(String value)
   at HelloWorld_NetCore.Program.Main(String[] args)

# General

csproj file:

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win10-x64;osx.10.11-x64;linux-x64;win-x86;ubuntu.16.04-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
</Project>
```

Ubuntu Release
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Using netcore 2.0
Inside the manifest, it shows 

          "System.Threading": "4.3.0"
I can't find any reference to 4.1.

**Comment by brooksyott** [comment]
The issue appears to come up when I add newtonsoft 10.0.3. It isn't present if newtonsoft is not there.

**Comment by brooksyott** [comment]
Any idea what could be wrong?
This is very simple, so it must be something I'm doing wrong.
A simple .netcoreapp HelloWorld that is fine until I add Newtonsoft.Json 10.0.3.

**Comment by Petermarcu** [comment]
Thats odd, I've seen plenty of others use Newtonsoft.Json with .NET Core 2.0. 

Which of the bin folders are you deploying to the server? Are you publishing and copying from the appropriate publish folder?

@ericstj any ideas?

**Comment by LGinC** [comment]
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)


too.....

**Comment by laibulle** [comment]
I have the same issue 

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
when I run `dotnet ef migrations add InitialCreate`

For my part I am using OSX High Sierra and `dot net core 2.0`

**Comment by alexzaytsev-newsroomly** [comment]
@brooksyott did you build on ubuntu also? or did you build on windows?

**Comment by ericstj** [comment]
The System.Threading issues appear to be https://github.com/dotnet/sdk/issues/1502 you'll run into this when publishing for windows from MSBuild and running on unix.  You can  workaround it by using dotnet publish instead.  You also may be able to workaround it by referencing MS.NETCore.Targets (if the conflict is coming from a runtime.* package) or explicitly setting ExcludeAssets on a conflicting package.

Let me know if you'd like any more information about the workarounds.

**Comment by Petermarcu** [comment]
Sounds like we can close this. Any other follow ups can be done on the linked issue. https://github.com/dotnet/sdk/issues/1502

**Comment by LGinC** [comment]
I use CLI      "dotnet publish -c Release -r linux-x64" 
@laibulle

**Comment by shahasad** [comment]
@ericstj : 
I face similar issue on Windows machines during running tests of our project.
The project is [here](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/Microsoft.ML.OnnxRuntime.Tests.csproj).

dotnet sdk version = 2.1.403
msbuild version = 15.8.169.51996

The project is restored and built using MSbuild, and the test is run using 'dotnet test' command.
The project target is dotnet core 2.0

The error message is coming from the VSTest --
Here is the full error with callstack.

I tried adding the Microsoft.NETCore.Targets V 2.1.0 as package reference in the project, still the same error remains. This does not happen in all of out build machines, apparently.

EXEC : Testhost process exited with error : Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Net.Sockets.Socket' threw an exception. ---> System.TypeInitializat
ionException: The type initializer for 'System.Net.Sockets.SocketAsyncEventArgs' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0
, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) [D:\asad\onnxruntime\csharp\O
nnxRuntime.CSharp.proj]
     at System.Net.Sockets.SocketAsyncEventArgs..cctor()
     --- End of inner exception stack trace ---
     at System.Net.Sockets.SocketAsyncEventArgs.InitializeInternals()
     at System.Net.Sockets.Socket..cctor()
     --- End of inner exception stack trace ---
     at System.Net.Sockets.Socket.InitializeSockets()
     at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
     at System.Net.Sockets.TcpClient..ctor(AddressFamily family)
     at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient..ctor(Func`2 channelFactory)
     at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.CommunicationEndpointFactory.Create(ConnectionRole role)
     at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.InitializeCommunication()
     at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
     at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
