### ISSUE TITLE
.NET Core September 2017 Update (1.0.7 and 1.1.4 with SDK 1.1.4)

### ISSUE THREAD

**Issue by leecow** [dotnet/core#980]
.NET Core September 2017 Update is available. This release updates .NET Core 1.0.7 .NET Core 1.1.4 and SDK 1.1.4

You can read about the update in the [release notes](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.7.md). 

Please report any issues you find with September 2017 Update here, either responding to this issue or creating a new issue.

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:

* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by Petermarcu** [comment]
Closing as we plan on keeping these announcements open for about 30 days.

**Comment by ASalihov** [comment]
Why 1.x releases after 2.0??

**Comment by Petermarcu** [comment]
Because we are still bug fixing 1.1 for people that are using it.
