### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly mscorlib, Version=4.0.0.0

### ISSUE THREAD

**Issue by neyromant** [dotnet/core#989]
# An error occurred when run a self-contained .net core  application on CentOs 7.3.

Hi, I tried to create small application:

```
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win7-x64;win81-x64;centos.7-x64</RuntimeIdentifiers>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="2.0.0" />
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="2.0.0" />
    <PackageReference Include="System.Console" Version="4.3.0" />
  </ItemGroup>

</Project>
```

I compiled this and tried running on centos 7.3 ( CentOS Linux release 7.3.1611 (Core) ) (without the installed .net core sdk on this machine, but with installed dependencies libunwind libicu).
I got an error
```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. The system cannot find the file specified.

Aborted

```

**Comment by neyromant** [comment]
I tried to turn off the DisableImplicitFrameworkReferences.
Now got another error:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Aborted

```

**Comment by ViktorHofer** [comment]
cc @janvorli

**Comment by Petermarcu** [comment]
Do you actually need those Package References? They should all be automatic.

**Comment by neyromant** [comment]
I wanted to compile a minimal application that depends only System.Console.
For this I set <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>

**Comment by Petermarcu** [comment]
What is the version of your SDK? `dotnet --version`?

**Comment by Petermarcu** [comment]
I don't think the approach of referencing individual packages is going to work in .NET Core 2.0. The way to get a smaller app in .NET Core 2.0 + is to reference the platform but use the linker. Instructions for that are here: https://github.com/dotnet/core/blob/master/samples/linker-instructions.md

**Comment by neyromant** [comment]
dotnet --version
2.0.0

**Comment by neyromant** [comment]
It's a pity. This approach worked for .net core 1.0.
Ок, Thank you so much.
