### ISSUE TITLE
error: Error reading 'x\project.json' at line 5 column 26 : Package dependencies must specify a version range.

### ISSUE THREAD

**Issue by Villason** [dotnet/core#99]
`"HtmlAgilityPack": "1.4.9"`

Fails on that line. I am just migrating for .net cli.

**Comment by dumbledad** [comment]
I've just updated the tools in Visual Studio and am getting the same error on most of my 'dependencies' rows in the project.json file. What's the fix?

**Comment by Villason** [comment]
Replace "Regan.Lib": "" by "Regan.Lib": "1.0.0-*"

**Comment by Villason** [comment]
I close the issue as the fix is my last comment.
