### ISSUE TITLE
VS 2017 Installation  - Facing Multiple issues 

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/core#992]
@davidfowl @shanselman   Installed VS 2017 15.3.5/Core SDK 2.0 and see multiple issues, not able to run web api project, getting "**The project doesn’t know how to run the profile IIS Express**" (same error for for core 1.1 and 2.0)  **Not seeing .Net Standard 2.0 option for libraries**.  **dotnet --version shows 1.0 though i have 2.0 installed**. attached errors below for each. Appreciate your help with this. 

![dotnet](https://user-images.githubusercontent.com/7142390/30785456-e604acae-a134-11e7-9fa3-1bb44333c36d.png)
![dotnet1](https://user-images.githubusercontent.com/7142390/30785455-e6042b58-a134-11e7-9402-dfde046cbf64.png)

![dotnet2](https://user-images.githubusercontent.com/7142390/30785480-3fd44cb2-a135-11e7-887c-9cb4bd6003bd.png)

**Comment by robertbaker** [comment]
This is not an issue with this project.

To fix your issue, open the visual studio installer, click modify. Under workloads, scroll all the way to the bottom, under Other Toolsets you will see .NET Core cross-platform development. Check the box and click the modify button. See image: https://imgur.com/a/QPfFA

**Comment by Petermarcu** [comment]
Closing now, let us know if you are still having trouble.
