### ISSUE TITLE
ArraySegment null check is throwing ArgumentNullException

### ISSUE THREAD

**Issue by serkantkaraca** [dotnet/core#994]
SDK 2.0 breaks null check on type value contract for ArraySegment.

            var arraySegment = new ArraySegment<byte>(new byte[10]);

            // This throws as below. Should be False as per C# spec. Works on 4.6.2
            var isNull = arraySegment == null;

System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.ArraySegment`1.op_Implicit(T[] array)
   at ConsoleApp.Program.Main(String[] args) in

**Comment by Petermarcu** [comment]
Thanks for reporting this. I've copied it here: https://github.com/dotnet/corefx/issues/24441
