### ISSUE TITLE
Is .NET Core supported on zLinux ?

### ISSUE THREAD

**Issue by anubhutiK** [dotnet/core#995]
Is .NET Core supported on zLinux ?

Hello Team,

I saw the supported OS page for .NET Core. It does not mention anything about zLinux or power Linux. Are  these architectures supported ? Is there a plan in future to support them ?

Thanks

**Comment by Petermarcu** [comment]
/cc @richlander @leecow

Power PC isn't a currently supported architecture and we don't have any official plans to support it. That said, if there is community support for it, we'd be happy to engage with anyone that wants to work on bringing that support up.

**Comment by Petermarcu** [comment]
I'm going to close this issue for now. If there is community interest in doing a port, feel free to start a new issue in the dotnet/coreclr repo where the work would have to start.
