### ISSUE TITLE
Unable to resolve service for type 'Core.Data.CoreContext' while attempting to activate 'Core.Data.Repositories.UnitOfWork'

### ISSUE THREAD

**Issue by borisdj** [dotnet/core#996]
I have part of WebAPI application that I want to move to separate project as class library.
It is common base structure that almost every app has so idea is to make it easy shareable.
Application type is:
ASP.NET Core Web Application / .NET Framework - ASP.NET Core 2.0 / Web API

What I have done in that direction is created a project named Core and moved those shared elements there, including Base Entities (e.g. User, Settings, etc), CoreContext, UnitOfWork, Generic Repository, BaseRepositories,...

In the Main project of app there are others Entities, AppContext that inherits CoreContext, more Repositories, and all Controllers, ...

I was able to build the app but when starting it get the following error:

> InvalidOperationException: Unable to resolve service for type 'Core.Data.CoreContext' while attempting to activate 'Core.Data.Repositories.UnitOfWork'.

>Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet<Type> callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)...

Problem seems to be that `UnitOfWork` class is in Core project and in Main project is `Startup.cs` with method` ConfigureServices` that has `services.AddTransient<IUnitOfWork, UnitOfWork>();`.

Is this a bug or am I just not configuring it correctly and how could it be achieved, if possible at all?

### Further technical details
NetCore & EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017 15.3
Operating system: Windows 10

CODE Sample:
```
namespace Main
{
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build();
    }
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<IUnitOfWork, UnitOfWork>();
            services.AddMvc();
            var conn = Configuration.GetConnectionString("DefaultConnection"); 
            services.AddDbContext<AppContext>(options => options.UseSqlServer(conn));
        }
    }
}

namespace Main.Data
{
    public class AppContext : CoreContext
    {
        ...
    }
}
```

```
namespace Core.Data
{
    public class UnitOfWork : IUnitOfWork, IDisposable
    {
        public CoreContext context;

        public UnitOfWork(CoreContext context)
        {
            this.context = context;
        }

        public T Get<T>() where T : BaseRepository, new()
        {
            var repository = new T();
            repository.Init(context);
            return repository;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
    }
}
```

**Comment by tanmaymandal** [comment]
I am getting same issue with configuration :(

**Comment by Petermarcu** [comment]
@borisdj , Any reason why you moved this here? I think the aspnet/home repo is actually the right place to start. @muratg can you confirm?

**Comment by davidfowl** [comment]
Your code has is expecting to inject s CorecContext but you configured an AppContext in your code. Dependency injection doesn’t work that way. You need to specify the service type as CoreContext.

Yes this issue belongs on asp.net

**Comment by Petermarcu** [comment]
Ok, I'm going go close this one here. @borisdj if you need more follow up, please file an issue in the aspnet/home repo.

**Comment by borisdj** [comment]
I wasn't sure where it belongs.
There no one replied so I thought it was wrong place, but now I guess not.

**Comment by erbpsy** [comment]
Add **services.AddSingleton<IEmployee, EmployeesMockup>();** in your ConfigureServices method of Startup.cs file of your project.

```
 public void ConfigureServices(IServiceCollection services)
	{
		services.AddRazorPages();
		// To register interface with its concrite type
		services.AddSingleton<IEmployee, EmployeesMockup>();
	}
```
	
	
For More details please visit this URL : [](https://www.youtube.com/watch?v=aMjiiWtfj2M)

for All methods (i.e. AddSingleton vs AddScoped vs AddTransient) Please visit this URL: [](https://www.youtube.com/watch?v=v6Nr7Zman_Y&list=PL6n9fhu94yhVkdrusLaQsfERmL_Jh4XmU&index=44)
